Rocstar: add_aspect_ratios.C File Reference
add_aspect_ratios.C File Reference
#include "roccom.h"
#include "mapbasic.h"
#include "Rocblas.h"
#include <iostream>
#include <sstream>
#include <fstream>
Functions
COM_EXTERN_MODULE (Rocin)
COM_EXTERN_MODULE (Rocout)
COM_EXTERN_MODULE (Rocmop)
COM_EXTERN_MODULE (Rocmap)
COM_EXTERN_MODULE (Roblas)
int get_comm_rank (MPI_Comm comm)
int get_comm_size (MPI_Comm comm)
int main (int argc, char *argv[])
Function Documentation
COM_EXTERN_MODULE (Rocin)
COM_EXTERN_MODULE (Rocout)
COM_EXTERN_MODULE (Rocmop)
COM_EXTERN_MODULE (Rocmap)
COM_EXTERN_MODULE (Roblas)
int get_comm_rank (MPI_Comm comm)
Definition at line 42 of file add_aspect_ratios.C.
References rank.
{
   int rank;
   int ierr = MPI_Comm_rank( comm, &rank); assert( ierr == 0);
   return rank;
 }
int get_comm_size (MPI_Comm comm)
Definition at line 49 of file add_aspect_ratios.C.
{
   int size;
   int ierr = MPI_Comm_size( comm, &size); assert( ierr == 0);
   return size;
 }
int main (int argc, char * argv[])
Definition at line 56 of file add_aspect_ratios.C.
References COM_call_function(), COM_finalize(), COM_get_attribute_handle(), COM_get_function_handle(), COM_init(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_print_profile(), COM_set_profiling(), COM_set_verbose(), and MPI_COMM_WORLD.
{
   MPI_Init( &argc, &argv);
   if ( argc < 3) {
     std::cout << "Usage: " << argv[0]
               << " <Rocin input file> <material name>" << endl;
     exit(-1);
   }
   string inputfname(argv[1]);
   const string matname(argv[2]);
   MPI_Comm comm = MPI_COMM_WORLD;
   COM_init( &argc, &argv);
   // LOAD MODULES
   COM_LOAD_MODULE_STATIC_DYNAMIC( Rocin, "IN");
   COM_LOAD_MODULE_STATIC_DYNAMIC( Rocout, "OUT");
   COM_LOAD_MODULE_STATIC_DYNAMIC( Rocmop, "MOP");
   // GET FUNCTION HANDLES
   int OUT_write = COM_get_function_handle( "OUT.write_attribute");
   int IN_read   = COM_get_function_handle( "IN.read_by_control_file");
   int MOP_asp   = COM_get_function_handle( "MOP.add_aspect_ratios");
   // SET OUTPUT LEVELS
   COM_set_verbose(11);
   COM_set_profiling(1);
   const string newfname("with_aspect_ratios");
   // READ IN FILES
   COM_call_function( IN_read,
                      inputfname.c_str(),
                      matname.c_str(),
                      &comm);
   int MAT_all = COM_get_attribute_handle((matname+".all").c_str());
   string MyString = "001";
   // CALCULATE ASPECT RATIOS
   COM_call_function(MOP_asp, &MAT_all);
  // PRINT SMOOTHED WINDOW
   COM_call_function( OUT_write,
                      newfname.c_str(),   //filename_pre
                      &MAT_all,           // attribute
                      matname.c_str(),      // material
                      "001"               // time
                      );
   COM_print_profile("", "");
   COM_finalize();
   MPI_Finalize();
 }