Rocstar: adj.cpp File Reference
adj.cpp File Reference
#include <stdio.h>
#include "makeflo.h"
#include "face.h"
Functions
int nHops (const blockLoc &dir)
Variables
const double initNodeQuant =1.0e-6
static int originMapsTo =(1<<30)
static int blockBytes =0
Function Documentation
int nHops (const blockLoc & dir) inline
Definition at line 129 of file adj.cpp.
References NTS::abs().
Referenced by node::intersect().
{
         return abs(dir[0])+abs(dir[1])+abs(dir[2]);
 }
Variable Documentation
int blockBytes =0 static
Definition at line 242 of file adj.cpp.
Referenced by block::block().
const double initNodeQuant =1.0e-6
Definition at line 201 of file adj.cpp.
int originMapsTo =(1<<30) static
Definition at line 203 of file adj.cpp.
Referenced by hashableVector3d::checkVector().