Rocstar: Aff_transformationS3.h File Reference
Aff_transformationS3.h File Reference
#include <cmath>
#include <CGAL/Handle.h>
#include <CGAL/SimpleCartesian/simple_cartesian_classes.h>
#include <CGAL/determinant.h>
Classes
class Aff_transformationS3< FT >
class Aff_transformation_repS3< FT >
class Translation_repS3< FT >
class Scaling_repS3< FT >
class Aff_transformation_rep_baseS3< FT >
class Aff_transformation_repS3< FT >
class Translation_repS3< FT >
class Scaling_repS3< FT >
class Aff_transformationS3< FT >
Functions
template<class FT >
Aff_transformationS3< FT > _general_transformation_composition (Aff_transformation_repS3< FT > &l, Aff_transformation_repS3< FT > &r)
template<class FT >
Aff_transformationS3< FT > operator* (const Aff_transformationS3< FT > &a, const Aff_transformationS3< FT > &b)
template<class FT >
std::ostream & operator<< (std::ostream &os, Translation_repS3< FT > &t)
template<class FT >
std::ostream & operator<< (std::ostream &os, Scaling_repS3< FT > &t)
template<class FT >
std::ostream & operator<< (std::ostream &os, const Aff_transformationS3< FT > &t)
Function Documentation
Aff_transformationS3< FT > _general_transformation_composition (Aff_transformation_repS3< FT > & l, Aff_transformation_repS3< FT > & r)
Definition at line 742 of file Aff_transformationS3.h.
References Aff_transformation_repS3< FT >::t11, Aff_transformation_repS3< FT >::t12, Aff_transformation_repS3< FT >::t13, Aff_transformation_repS3< FT >::t14, Aff_transformation_repS3< FT >::t21, Aff_transformation_repS3< FT >::t22, Aff_transformation_repS3< FT >::t23, Aff_transformation_repS3< FT >::t24, Aff_transformation_repS3< FT >::t31, Aff_transformation_repS3< FT >::t32, Aff_transformation_repS3< FT >::t33, and Aff_transformation_repS3< FT >::t34.
Referenced by operator*().
 {
 return Aff_transformationS3<FT>(
             l.t11*r.t11 + l.t12*r.t21 + l.t13*r.t31,
             l.t11*r.t12 + l.t12*r.t22 + l.t13*r.t32,
             l.t11*r.t13 + l.t12*r.t23 + l.t13*r.t33,
             l.t11*r.t14 + l.t12*r.t24 + l.t13*r.t34 + l.t14,
             l.t21*r.t11 + l.t22*r.t21 + l.t23*r.t31,
             l.t21*r.t12 + l.t22*r.t22 + l.t23*r.t32,
             l.t21*r.t13 + l.t22*r.t23 + l.t23*r.t33,
             l.t21*r.t14 + l.t22*r.t24 + l.t23*r.t34 + l.t24,
             l.t31*r.t11 + l.t32*r.t21 + l.t33*r.t31,
             l.t31*r.t12 + l.t32*r.t22 + l.t33*r.t32,
             l.t31*r.t13 + l.t32*r.t23 + l.t33*r.t33,
             l.t31*r.t14 + l.t32*r.t24 + l.t33*r.t34 + l.t34);
 }
Aff_transformationS3< FT > operator* (const Aff_transformationS3< FT > & a, const Aff_transformationS3< FT > & b)
Definition at line 766 of file Aff_transformationS3.h.
References _general_transformation_composition(), and Aff_transformationS3< FT >::general_form().
 {
   return _general_transformation_composition(
          *(Aff_transformation_repS3<FT>*)(a.general_form().ptr()),
          *(Aff_transformation_repS3<FT>*)(b.general_form().ptr()));
 }
std::ostream& operator<< (std::ostream & os, Translation_repS3< FT > & t)
std::ostream& operator<< (std::ostream & os, Scaling_repS3< FT > & t)
std::ostream & operator<< (std::ostream & os, const Aff_transformationS3< FT > & t)
Definition at line 777 of file Aff_transformationS3.h.
 {
     t.print(os);
     return os;
 }