Rocstar: ainv.f90 File Reference
ainv.f90 File Reference
Functions/Subroutines
subroutine ainv (ajac, ajacin, det, ndim)
Function/Subroutine Documentation
subroutine ainv (real*8, dimension(ndim,ndim) ajac, real*8, dimension(ndim,ndim) ajacin, real*8 det, integer ndim)
Definition at line 53 of file ainv.f90.
References Plane_3< R, T >::d(), Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
Referenced by rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_invertmatrixsvd(), shcalc(), and shcalc_3d10().