Rocstar: angle_rad_3d.f90 File Reference
angle_rad_3d.f90 File Reference
Functions/Subroutines
real *8 function angle_rad_3d (x1, y1, z1, x2, y2, z2, x3, y3, z3)
Function/Subroutine Documentation
real*8 function angle_rad_3d (real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2, real*8 x3, real*8 y3, real*8 z3)
Definition at line 54 of file angle_rad_3d.f90.
References Rocblas::dot(), and sqrt().
Referenced by angle_rad_3d().