Rocstar: arruda_boyce.f90 File Reference
arruda_boyce.f90 File Reference
Functions/Subroutines
subroutine arruda_boyce (Cij, S11, S22, S33, S12, S23, S13, ielem, mu, kappa)
subroutine solve_x (x, xmu, i, stretch)
subroutine rs (nm, n, a, w, matz, z, fv1, fv2, ierr)
real *8 function pythag (a, b)
subroutine tql1 (n, d, e, ierr)
subroutine tql2 (nm, n, d, e, z, ierr)
subroutine tred1 (nm, n, a, d, e, e2)
subroutine tred2 (nm, n, a, d, e, z)
Function/Subroutine Documentation
subroutine arruda_boyce (real*8, dimension(3,3) Cij, real*8 S11, real*8 S22, real*8 S33, real*8 S12, real*8 S23, real*8 S13, integer ielem, real*8 mu, real*8 kappa)
Definition at line 53 of file arruda_boyce.f90.
References j, k, Aff_transformation_repS2< FT >::print(), rs(), solve_x(), and sqrt().
Referenced by v3d10_nl_arruda_boyce(), v3d10_nl_arruda_boyce_damping(), v3d10_nl_arruda_boyce_thermal(), and v3d4_nl_arruda_boyce().
real*8 function pythag (real*8 a, real*8 b)
Definition at line 330 of file arruda_boyce.f90.
References Line_2< R, T >::a(), Color::b(), Color::r(), and s.
Referenced by pythag(), tql1(), and tql2().
subroutine rs (integer nm, integer n, real*8, dimension(nm,n) a, real*8, dimension(n) w, integer matz, real*8, dimension(nm,n) z, real*8, dimension(n) fv1, real*8, dimension(n) fv2, integer ierr)
Definition at line 259 of file arruda_boyce.f90.
References Line_2< R, T >::a(), tql1(), tql2(), tred1(), tred2(), and z.
Referenced by arruda_boyce(), arruda_boyce_cauchy(), Rocmop::compute_medial_quadric(), MsqHessian::initialize(), CImgList< uintT >::load_parrec(), rflu_modcoloring::rflu_col_buildcolorings(), rflu_modresidual::rflu_getresidualsupport1(), rflu_modresidual::rflu_getresidualsupport2(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), and rflu_modpetscnewtonkrylov::rflu_petsc_createcoloring().
subroutine solve_x (real*8 x, real*8 xmu, integer i, real*8, dimension(3) stretch)
Definition at line 203 of file arruda_boyce.f90.
References Plane_3< R, T >::d(), Direction_2< R, T >::dx(), i, k, Aff_transformation_repS2< FT >::print(), StopWatch::stop(), and x.
Referenced by arruda_boyce(), and arruda_boyce_cauchy().
subroutine tql1 (integer n, real*8, dimension(n) d, real*8, dimension(n) e, integer ierr)
Definition at line 361 of file arruda_boyce.f90.
References Line_2< R, T >::c(), Plane_3< R, T >::d(), Color::g(), i, j, Aff_transformation_2< R_ >::m(), pythag(), Color::r(), s, and sign().
Referenced by rs().
subroutine tql2 (integer nm, integer n, real*8, dimension(n) d, real*8, dimension(n) e, real*8, dimension(nm,n) z, integer ierr)
Definition at line 512 of file arruda_boyce.f90.
References Line_2< R, T >::c(), Plane_3< R, T >::d(), Color::g(), i, j, k, Aff_transformation_2< R_ >::m(), pythag(), Color::r(), s, sign(), and z.
Referenced by rs().
subroutine tred1 (integer nm, integer n, real*8, dimension(nm,n) a, real*8, dimension(n) d, real*8, dimension(n) e, real*8, dimension(n) e2)
Definition at line 697 of file arruda_boyce.f90.
References Line_2< R, T >::a(), Plane_3< R, T >::d(), Color::g(), i, j, k, Transfer_base::scale(), sign(), and sqrt().
Referenced by rs().
subroutine tred2 (integer nm, integer n, real*8, dimension(nm,n) a, real*8, dimension(n) d, real*8, dimension(n) e, real*8, dimension(nm,n) z)
Definition at line 843 of file arruda_boyce.f90.
References Line_2< R, T >::a(), Plane_3< R, T >::d(), Color::g(), i, j, k, Transfer_base::scale(), sign(), sqrt(), and z.
Referenced by rs().