Rocstar: ArtificialDamping.f90 File Reference
ArtificialDamping.f90 File Reference
Functions/Subroutines
subroutine artificialdamping (numcstet, numnp, rho, cd_fastest, DetFold, dt, F, Fdot, Vx6, StrssVisco)
Function/Subroutine Documentation
subroutine artificialdamping (integer numcstet, integer numnp, real*8 rho, real*8 cd_fastest, real*8 DetFold, real*8 dt, real*8, dimension(3,3) F, real*8, dimension(3,3) Fdot, real*8 Vx6, real*8, dimension(3,3) StrssVisco)
Definition at line 53 of file ArtificialDamping.f90.
References id(), invert3x3(), and max().
Referenced by v3d10_nl_arruda_boyce_damping(), and v3d10_nl_damping().