Rocstar: assertions.C File Reference
assertions.C File Reference
#include <CGAL/config.h>
#include <cstdio>
#include <cstdlib>
#include <CGAL/assertions.h>
#include <iostream>
#include <cassert>
#include "commpi.h"
Functions
CGAL_BEGIN_NAMESPACE void not_implemented ()
void printStackBacktrace ()
static void _standard_error_handler (const char *what, const char *expr, const char *file, int line, const char *msg)
static void _standard_warning_handler (const char *, const char *expr, const char *file, int line, const char *msg)
void assertion_fail (const char *expr, const char *file, int line, const char *msg)
Default error handler.
void precondition_fail (const char *expr, const char *file, int line, const char *msg)
void postcondition_fail (const char *expr, const char *file, int line, const char *msg)
void warning_fail (const char *expr, const char *file, int line, const char *msg)
Failure_function set_error_handler (Failure_function handler)
Sets the handler for assertion-failures.
Failure_function set_warning_handler (Failure_function handler)
Failure_behaviour set_error_behaviour (Failure_behaviour eb)
Controls the behavior when an assertion fails.
Failure_behaviour set_warning_behaviour (Failure_behaviour eb)
Variables
static Failure_behaviour _error_behaviour = ABORT
static Failure_behaviour _warning_behaviour = CONTINUE
static Failure_function _error_handler = _standard_error_handler
static Failure_function _warning_handler = _standard_warning_handler
Function Documentation
static void _standard_error_handler (const char * what, const char * expr, const char * file, int line, const char * msg) static
Definition at line 96 of file assertions.C.
 {
     std::cerr << "Rocface error: " << what << " violation!" << std::endl
          << "Expr: " << expr << std::endl
          << "File: " << file << std::endl
          << "Line: " << line << std::endl;
     if ( msg != 0)
         std::cerr << "Explanation:" << msg << std::endl;
 }
static void _standard_warning_handler (const char * , const char * expr, const char * file, int line, const char * msg) static
Definition at line 116 of file assertions.C.
 {
     std::cerr << "Rocface warning: check violation!" << std::endl
          << "Expr: " << expr << std::endl
          << "File: " << file << std::endl
          << "Line: " << line << std::endl;
     if ( msg != 0)
         std::cerr << "Explanation:" << msg << std::endl;
 }
void assertion_fail (const char * expr, const char * file, int line, const char * msg)
Default error handler.
Definition at line 142 of file assertions.C.
References _error_behaviour, ABORT, COMMPI_Initialized(), CONTINUE, EXIT, EXIT_WITH_SUCCESS, MPI_COMM_WORLD, and printStackBacktrace().
 {
     (*_error_handler)("assertion", expr, file, line, msg);
     printStackBacktrace();
     switch (_error_behaviour) {
     case ABORT:
         if (COMMPI_Initialized()) MPI_Abort(MPI_COMM_WORLD,-1); abort();
     case EXIT:
         exit(1);  // EXIT_FAILURE
     case EXIT_WITH_SUCCESS:
         exit(0);  // EXIT_SUCCESS
     case CONTINUE:
         ;
     }
 }
CGAL_BEGIN_NAMESPACE void not_implemented ()
Definition at line 65 of file assertions.C.
 {
     assert( false);
 }
void postcondition_fail (const char * expr, const char * file, int line, const char * msg)
Definition at line 182 of file assertions.C.
References _error_behaviour, ABORT, COMMPI_Initialized(), CONTINUE, EXIT, EXIT_WITH_SUCCESS, MPI_COMM_WORLD, and printStackBacktrace().
 {
     (*_error_handler)("postcondition", expr, file, line, msg);
     printStackBacktrace();
     switch (_error_behaviour) {
     case ABORT:
         if (COMMPI_Initialized()) MPI_Abort(MPI_COMM_WORLD,-1); abort();
     case EXIT:
         exit(1);  // EXIT_FAILURE
     case EXIT_WITH_SUCCESS:
         exit(0);  // EXIT_SUCCESS
     case CONTINUE:
         ;
     }
 }
void precondition_fail (const char * expr, const char * file, int line, const char * msg)
Definition at line 162 of file assertions.C.
References _error_behaviour, ABORT, COMMPI_Initialized(), CONTINUE, EXIT, EXIT_WITH_SUCCESS, MPI_COMM_WORLD, and printStackBacktrace().
 {
     (*_error_handler)("precondition", expr, file, line, msg);
     printStackBacktrace();
     switch (_error_behaviour) {
     case ABORT:
         if (COMMPI_Initialized()) MPI_Abort(MPI_COMM_WORLD,-1); abort();
     case EXIT:
         exit(1);  // EXIT_FAILURE
     case EXIT_WITH_SUCCESS:
         exit(0);  // EXIT_SUCCESS
     case CONTINUE:
         ;
     }
 }
void printStackBacktrace ()
Definition at line 76 of file assertions.C.
References i.
Referenced by assertion_fail(), postcondition_fail(), precondition_fail(), and warning_fail().
{
 #ifdef TRACEBACK
   const int max_stack=64;
   void *stackPtrs[max_stack];
   int levels=backtrace(stackPtrs,max_stack);
   char **symbols=backtrace_symbols(stackPtrs, levels);
   const int nSkip=2;
   std::printf( "\nStack Backtrace:\n");
   for ( int i=nSkip; i<levels; i++) {
     std::printf( " [%d] %s\n", i-nSkip, symbols[i]);
   }
 #endif
 }
Failure_behaviour set_error_behaviour (Failure_behaviour eb)
Controls the behavior when an assertion fails.
Definition at line 244 of file assertions.C.
References _error_behaviour.
 {
     Failure_behaviour result = _error_behaviour;
     _error_behaviour = eb;
     return result;
 }
Failure_function set_error_handler (Failure_function handler)
Sets the handler for assertion-failures.
Definition at line 228 of file assertions.C.
References _error_handler.
 {
     Failure_function result = _error_handler;
     _error_handler = handler;
     return( result);
 }
Failure_behaviour set_warning_behaviour (Failure_behaviour eb)
Definition at line 252 of file assertions.C.
References _warning_behaviour.
 {
     Failure_behaviour result = _warning_behaviour;
     _warning_behaviour = eb;
     return result;
 }
Failure_function set_warning_handler (Failure_function handler)
Definition at line 236 of file assertions.C.
References _warning_handler.
 {
     Failure_function result = _warning_handler;
     _warning_handler = handler;
     return( result);
 }
void warning_fail (const char * expr, const char * file, int line, const char * msg)
Definition at line 205 of file assertions.C.
References _warning_behaviour, ABORT, CONTINUE, EXIT, EXIT_WITH_SUCCESS, MPI_COMM_WORLD, and printStackBacktrace().
 {
     (*_warning_handler)("warning", expr, file, line, msg);
     printStackBacktrace();
     switch (_warning_behaviour) {
     case ABORT:
         MPI_Abort(MPI_COMM_WORLD,-1); abort();
     case EXIT:
         exit(1);  // EXIT_FAILURE
     case EXIT_WITH_SUCCESS:
         exit(0);  // EXIT_SUCCESS
     case CONTINUE:
         ;
     }
 }
Variable Documentation
Failure_behaviour _error_behaviour = ABORT static
Definition at line 73 of file assertions.C.
Referenced by assertion_fail(), postcondition_fail(), precondition_fail(), and set_error_behaviour().
Failure_function _error_handler = _standard_error_handler static
Definition at line 134 of file assertions.C.
Referenced by set_error_handler().
Failure_behaviour _warning_behaviour = CONTINUE static
Definition at line 74 of file assertions.C.
Referenced by set_warning_behaviour(), and warning_fail().
Failure_function _warning_handler = _standard_warning_handler static
Definition at line 137 of file assertions.C.
Referenced by set_warning_handler().