Rocstar: basic_actions.C File Reference
basic_actions.C File Reference
#include "basic_actions.h"
#include "FluidAgent.h"
#include "SolidAgent.h"
#include "BurnAgent.h"
Functions
COM_EXTERN_MODULE (Rocsurf)
COM_EXTERN_MODULE (Rocprop)
COM_EXTERN_MODULE (Rocmap)
COM_EXTERN_MODULE (Rocon)
static void load_rocsurf ()
static void load_rocon (const RocmanControl_parameters *param, MPI_Comm comm)
static void load_rocprop (const RocmanControl_parameters *param, MPI_Comm comm)
static void load_rocmap ()
Function Documentation
COM_EXTERN_MODULE (Rocsurf)
COM_EXTERN_MODULE (Rocprop)
COM_EXTERN_MODULE (Rocmap)
COM_EXTERN_MODULE (Rocon)
static void load_rocmap () inline static
Definition at line 383 of file basic_actions.C.
References COM_get_window_handle(), COM_LOAD_MODULE_STATIC_DYNAMIC, and MAN_DEBUG.
Referenced by FluidPropagateSurface::init(), ComputePconn::init(), and SolidPropagateSurface_ALE::init().
 {
   if (COM_get_window_handle("MAP") <= 0) {
     MAN_DEBUG(3, ("Rocstar: Loading module RocMap...\n"));
     COM_LOAD_MODULE_STATIC_DYNAMIC( Rocmap, "MAP");
   }
 }
static void load_rocon (const RocmanControl_parameters * param, MPI_Comm comm) inline static
Definition at line 346 of file basic_actions.C.
References COM_call_function(), COM_get_function_handle(), COM_get_window_handle(), COM_LOAD_MODULE_STATIC_DYNAMIC, RocmanControl_parameters::PROPCON_enabled, and RocmanControl_parameters::PROPCON_ndiv.
Referenced by FluidPropagateSurface::init(), and SolidPropagateSurface_ALE::init().
 {
   if(param->PROPCON_enabled && (COM_get_window_handle("PROPCON") <= 0)){
     //    std::cout << "Rocstar: LOADING ROCON" << std::endl;
     COM_LOAD_MODULE_STATIC_DYNAMIC(Rocon,"PROPCON");
     int PROPCON_init_hndl = COM_get_function_handle("PROPCON.init_from_file");
     std::string rocon_config_file("Rocon/RoconControl.txt");
     COM_call_function(PROPCON_init_hndl,rocon_config_file.c_str(),&(param->PROPCON_ndiv));
     //    std::cout << "Rocstar: LOADED ROCON" << std::endl;
   }
 }
static void load_rocprop (const RocmanControl_parameters * param, MPI_Comm comm) inline static
Definition at line 359 of file basic_actions.C.
References COM_call_function(), COM_get_function_handle(), COM_get_window_handle(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_set_profiling_barrier(), MAN_DEBUG, RocmanControl_parameters::PROP_fangle, RocmanControl_parameters::PROP_fom, and RocmanControl_parameters::PROP_rediter.
Referenced by FluidPropagateSurface::init(), ComputePconn::init(), and SolidPropagateSurface_ALE::init().
 {
   if (COM_get_window_handle("PROP") <= 0) {
     MAN_DEBUG(3, ("Rocstar: Loading module RocProp...\n"));
     COM_LOAD_MODULE_STATIC_DYNAMIC( Rocprop, "PROP");
     int PROP_set_option = COM_get_function_handle( "PROP.set_option");
     if (param->PROP_fom)
       COM_call_function( PROP_set_option, "method", "fo");
     else
       COM_call_function( PROP_set_option, "method", "mp");
     char val[256];
     sprintf(val, "%d", param->PROP_rediter);
     COM_call_function( PROP_set_option, "rediter", val);
     sprintf(val, "%f", param->PROP_fangle);
     COM_call_function( PROP_set_option, "fangle", val);
     int PROP_initialize = COM_get_function_handle("PROP.initialize");
     int PROP_propagate = COM_get_function_handle("PROP.propagate");
     COM_set_profiling_barrier( PROP_initialize, comm);
     COM_set_profiling_barrier( PROP_propagate, comm);
   }
 }
static void load_rocsurf () inline static
Definition at line 340 of file basic_actions.C.
References COM_get_window_handle(), and COM_LOAD_MODULE_STATIC_DYNAMIC.
Referenced by ComputeFaceCenters::run().
 {
   if (COM_get_window_handle("SURF") <= 0)
     COM_LOAD_MODULE_STATIC_DYNAMIC( Rocsurf, "SURF");
 }