Rocstar: basic_constructionsS3.h File Reference
basic_constructionsS3.h File Reference
#include <CGAL/SimpleCartesian/PointS3.h>
#include <CGAL/SimpleCartesian/PlaneS3.h>
#include <CGAL/constructions/kernel_ftC3.h>
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE
CGAL_KERNEL_MEDIUM_INLINE
PointS3< FT > midpoint (PointS3< FT > const &p, PointS3< FT > const &q)
template<class FT >
PointS3< FT > circumcenter (PointS3< FT > const &p, PointS3< FT > const &q, PointS3< FT > const &r, PointS3< FT > const &s)
template<class FT >
CGAL_KERNEL_LARGE_INLINE
PointS3< FT > projection (const PointS3< FT > &p, const PlaneS3< FT > &h)
template<class FT >
FT squared_distance (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
FT scaled_distance_to_plane (const PlaneS3< FT > &h, const PointS3< FT > &p)
template<class FT >
FT scaled_distance_to_plane (const PointS3< FT > &hp, const PointS3< FT > &hq, const PointS3< FT > &hr, const PointS3< FT > &p)
template<class FT >
PlaneS3< FT > bisector (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
PointS3< FT > gp_linear_intersection (const PlaneS3< FT > &f, const PlaneS3< FT > &g, const PlaneS3< FT > &h)
Function Documentation
PlaneS3<FT> bisector (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 133 of file basic_constructionsS3.h.
References midpoint().
Referenced by pl_Bisector< Point, Line >::operator()().
 { return PlaneS3<FT>( midpoint(p,q), q-p); }
PointS3<FT> circumcenter (PointS3< FT > const & p, PointS3< FT > const & q, PointS3< FT > const & r, PointS3< FT > const & s)
Definition at line 72 of file basic_constructionsS3.h.
References circumcenterC3(), x, PointS3< FT >::x(), y, PointS3< FT >::y(), z, and PointS3< FT >::z().
Referenced by p_Circumcenter< Point >::operator()().
 {
   FT x,y,z;
   circumcenterC3(p.x(),p.y(),p.z(),
                  q.x(),q.y(),q.z(),
                  r.x(),r.y(),r.z(),
                  s.x(),s.y(),s.z(),
                  x,y,z);
   return PointS3<FT>(x,y,z);
 }
PointS3<FT> gp_linear_intersection (const PlaneS3< FT > & f, const PlaneS3< FT > & g, const PlaneS3< FT > & h) inline
Definition at line 139 of file basic_constructionsS3.h.
References PlaneS3< FT >::a(), PlaneS3< FT >::b(), PlaneS3< FT >::c(), PlaneS3< FT >::d(), and det3x3_by_formula().
 {
   return PointS3<FT>( det3x3_by_formula(-f.d(), f.b(), f.c(),
                                         -g.d(), g.b(), g.c(),
                                         -h.d(), h.b(), h.c()),
                       det3x3_by_formula( f.a(),-f.d(), f.c(),
                                          g.a(),-g.d(), g.c(),
                                          h.a(),-h.d(), h.c()),
                       det3x3_by_formula( f.a(), f.b(),-f.d(),
                                          g.a(), g.b(),-g.d(),
                                          h.a(), h.b(),-h.d()),
                       det3x3_by_formula( f.a(), f.b(), f.c(),
                                          g.a(), g.b(), g.c(),
                                          h.a(), h.b(), h.c()));
 }
CGAL_BEGIN_NAMESPACE CGAL_KERNEL_MEDIUM_INLINE PointS3<FT> midpoint (PointS3< FT > const & p, PointS3< FT > const & q)
Definition at line 63 of file basic_constructionsS3.h.
References midpointC3(), x, PointS3< FT >::x(), y, PointS3< FT >::y(), z, and PointS3< FT >::z().
Referenced by bisector(), and p_Midpoint< Point >::operator()().
 {
   FT x,y,z;
   midpointC3(p.x(),p.y(),p.z(),q.x(),q.y(),q.z(),x,y,z);
   return PointS3<FT>(x,y,z);
 }
CGAL_KERNEL_LARGE_INLINE PointS3<FT> projection (const PointS3< FT > & p, const PlaneS3< FT > & h)
Definition at line 89 of file basic_constructionsS3.h.
References PlaneS3< FT >::a(), PlaneS3< FT >::b(), PlaneS3< FT >::c(), PlaneS3< FT >::d(), projection_planeC3(), x, PointS3< FT >::x(), y, PointS3< FT >::y(), z, and PointS3< FT >::z().
Referenced by PlaneS3< FT >::projection(), Line_3< R, T >::projection(), Plane_3< R, T >::projection(), Line_2< R >::projection(), and NonSmoothSteepestDescent::search_edges_faces().
 {
   FT x,y,z;
   projection_planeC3(h.a(),h.b(),h.c(),h.d(),
                      p.x(),p.y(),p.z(),
                      x,y,z);
   return PointS3<FT>(x,y,z);
 }
FT scaled_distance_to_plane (const PlaneS3< FT > & h, const PointS3< FT > & p) inline
Definition at line 110 of file basic_constructionsS3.h.
References PlaneS3< FT >::a(), PlaneS3< FT >::b(), PlaneS3< FT >::c(), PlaneS3< FT >::d(), scaled_distance_to_planeC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   return scaled_distance_to_planeC3(h.a(),h.b(),h.c(),h.d(),
                                     p.x(),p.y(),p.z());
 }
FT scaled_distance_to_plane (const PointS3< FT > & hp, const PointS3< FT > & hq, const PointS3< FT > & hr, const PointS3< FT > & p) inline
Definition at line 119 of file basic_constructionsS3.h.
References scaled_distance_to_planeC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   return scaled_distance_to_planeC3(hp.x(),hp.y(),hp.z(),
                                     hq.x(),hq.y(),hq.z(),
                                     hr.x(),hr.y(),hr.z(),
                                     p.x(),p.y(),p.z());
 }
FT squared_distance (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 102 of file basic_constructionsS3.h.
References squared_distanceC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by SegmentS3< FT >::squared_length(), and SegmentS2< FT >::squared_length().
 {
   return squared_distanceC3(p.x(),p.y(),p.z(),q.x(),q.y(),q.z());
 }