Rocstar: BcondInflowPerf.F90 File Reference
BcondInflowPerf.F90 File Reference
Functions/Subroutines
subroutine bcondinflowperf (bcOptType, bcOptFixed, ptot, ttot, betah, betav, mach, sxn, syn, szn, cpgas, mm, rl, rul, rvl, rwl, rr, rur, rvr, rwr, rer, pr)
Function/Subroutine Documentation
subroutine bcondinflowperf (integer, intent(in) bcOptType, integer, intent(in) bcOptFixed, real(rfreal), intent(in) ptot, real(rfreal), intent(in) ttot, real(rfreal), intent(in) betah, real(rfreal), intent(in) betav, real(rfreal), intent(in) mach, real(rfreal), intent(in) sxn, real(rfreal), intent(in) syn, real(rfreal), intent(in) szn, real(rfreal), intent(in) cpgas, real(rfreal), intent(in) mm, real(rfreal), intent(in) rl, real(rfreal), intent(in) rul, real(rfreal), intent(in) rvl, real(rfreal), intent(in) rwl, real(rfreal), intent(out) rr, real(rfreal), intent(out) rur, real(rfreal), intent(out) rvr, real(rfreal), intent(out) rwr, real(rfreal), intent(out) rer, real(rfreal), intent(out) pr)
Definition at line 65 of file BcondInflowPerf.F90.
References cos, Color::g(), modtools::makenonzero(), mixtperf_c2_grt(), mixtperf_c_co2guvw(), mixtperf_c_dgp(), mixtperf_c_grt(), mixtperf_co2_cguvw(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_eo_dgpvm(), mixtperf_g_cpr(), mixtperf_p_gmapo(), mixtperf_p_gpotto(), mixtperf_po_cgpuvw(), mixtperf_po_gptto(), mixtperf_r_m(), mixtperf_t_cgr(), mixtperf_t_gmato(), mixtperf_vm_c2co2g(), sin, and sqrt().
Referenced by rflo_modboundaryconditions::rflo_bcondinflow(), rflu_centralfirstpatch(), rflu_centralsecondpatch(), and rflu_modnscbc::rflu_nscbc_initiftotang().