Rocstar: BcondInjectionPerf.F90 File Reference
BcondInjectionPerf.F90 File Reference
Functions/Subroutines
subroutine bcondinjectionperf (distrib, minj, tinj, rhoVrel, sxn, syn, szn, cpgas, mm, p, rhob, rhoub, rhovb, rhowb, rhoeb, pb, uinj, vinj, winj)
Function/Subroutine Documentation
subroutine bcondinjectionperf (integer, intent(in) distrib, real(rfreal), intent(in) minj, real(rfreal), intent(in) tinj, real(rfreal), dimension(3), intent(in) rhoVrel, real(rfreal), intent(in) sxn, real(rfreal), intent(in) syn, real(rfreal), intent(in) szn, real(rfreal), intent(in) cpgas, real(rfreal), intent(in) mm, real(rfreal), intent(in) p, real(rfreal), intent(out) rhob, real(rfreal), intent(out) rhoub, real(rfreal), intent(out) rhovb, real(rfreal), intent(out) rhowb, real(rfreal), intent(out) rhoeb, real(rfreal), intent(out) pb, real(rfreal), intent(out) uinj, real(rfreal), intent(out) vinj, real(rfreal), intent(out) winj)
Definition at line 56 of file BcondInjectionPerf.F90.
References Color::g(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), and mixtperf_r_m().
Referenced by peul_centralfluxpatch(), radi_floflimcentfluxpatch(), rflo_modboundaryconditions::rflo_bcondinjection(), rflo_centralfluxpatch(), rflo_roefluxpatch(), turb_floranssacentfluxpatch(), and turb_floranssaroefluxpatch().