Rocstar: BcondFarfieldPerf.F90 File Reference
BcondFarfieldPerf.F90 File Reference
Functions/Subroutines
subroutine bcondfarfieldperf (machInf, alphaInf, betaInf, pInf, tInf, sxn, syn, szn, cpgas, mol, rho, rhou, rhov, rhow, rhoe, press, rhob, rhoub, rhovb, rhowb, rhoeb, pb)
Function/Subroutine Documentation
subroutine bcondfarfieldperf (real(rfreal) machInf, real(rfreal) alphaInf, real(rfreal) betaInf, real(rfreal) pInf, real(rfreal) tInf, real(rfreal) sxn, real(rfreal) syn, real(rfreal) szn, real(rfreal) cpgas, real(rfreal) mol, real(rfreal) rho, real(rfreal) rhou, real(rfreal) rhov, real(rfreal) rhow, real(rfreal) rhoe, real(rfreal) press, real(rfreal) rhob, real(rfreal) rhoub, real(rfreal) rhovb, real(rfreal) rhowb, real(rfreal) rhoeb, real(rfreal) pb)
Definition at line 63 of file BcondFarfieldPerf.F90.
References cos, mixtperf_c_dgp(), mixtperf_c_grt(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_eo_dgpvm(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_r_m(), and sin.
Referenced by rflo_modboundaryconditions::rflo_bcondfarfield(), rflu_centralfirstpatch(), and rflu_centralsecondpatch().