Rocstar: BcondOutflowPerf.F90 File Reference
BcondOutflowPerf.F90 File Reference
Functions/Subroutines
subroutine bcondoutflowperf (bcOpt, pout, sxn, syn, szn, cpgas, mol, rho, rhou, rhov, rhow, rhoe, press, rhob, rhoub, rhovb, rhowb, rhoeb)
Function/Subroutine Documentation
subroutine bcondoutflowperf (integer bcOpt, real(rfreal) pout, real(rfreal) sxn, real(rfreal) syn, real(rfreal) szn, real(rfreal) cpgas, real(rfreal) mol, real(rfreal) rho, real(rfreal) rhou, real(rfreal) rhov, real(rfreal) rhow, real(rfreal) rhoe, real(rfreal) press, real(rfreal) rhob, real(rfreal) rhoub, real(rfreal) rhovb, real(rfreal) rhowb, real(rfreal) rhoeb)
Definition at line 58 of file BcondOutflowPerf.F90.
References max(), mixtperf_c_dgp(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_r_m(), sign(), sqrt(), and v.
Referenced by rflo_modboundaryconditions::rflo_bcondoutflow(), rflu_centralfirstpatch(), and rflu_centralsecondpatch().