Rocstar: BcondOutflowPerf_GL.F90 File Reference
BcondOutflowPerf_GL.F90 File Reference
Functions/Subroutines
subroutine bcondoutflowperf_gl (bcOpt, ro, Po, To, betaP, betaT, cvl, cvv, cvg, Rg, Rv, pout, sxn, syn, szn, rho, rhou, rhov, rhow, rhoe, rhogpg, rhovpv, pin, rhob, rhoub, rhovb, rhowb, rhoeb, rhogpgb, rhovpvb)
Function/Subroutine Documentation
subroutine bcondoutflowperf_gl (integer bcOpt, real(rfreal), intent(in) ro, real(rfreal), intent(in) Po, real(rfreal), intent(in) To, real(rfreal), intent(in) betaP, real(rfreal), intent(in) betaT, real(rfreal), intent(in) cvl, real(rfreal), intent(in) cvv, real(rfreal), intent(in) cvg, real(rfreal), intent(in) Rg, real(rfreal), intent(in) Rv, real(rfreal), intent(in) pout, real(rfreal), intent(in) sxn, real(rfreal), intent(in) syn, real(rfreal), intent(in) szn, real(rfreal), intent(in) rho, real(rfreal), intent(in) rhou, real(rfreal), intent(in) rhov, real(rfreal), intent(in) rhow, real(rfreal), intent(in) rhoe, real(rfreal), intent(in) rhogpg, real(rfreal), intent(in) rhovpv, real(rfreal), intent(in) pin, real(rfreal), intent(out) rhob, real(rfreal), intent(out) rhoub, real(rfreal), intent(out) rhovb, real(rfreal), intent(out) rhowb, real(rfreal), intent(out) rhoeb, real(rfreal), intent(out) rhogpgb, real(rfreal), intent(out) rhovpvb)
Definition at line 67 of file BcondOutflowPerf_GL.F90.
References max(), mixtgasliq_c(), mixtliq_c2_bp(), mixtliq_d_dobpppobttto(), mixtperf_c2_grt(), mixtperf_d_prt(), mixtperf_t_cveovm2(), block::pin(), sign(), sqrt(), and v.
Referenced by rflu_centralfirstpatch_gl(), and rflu_centralsecondpatch_gl().