Rocstar: BcondInflowPerf_GL.F90 File Reference
BcondInflowPerf_GL.F90 File Reference
Functions/Subroutines
subroutine bcondinflowperf_gl (bcOptType, ro, po, to, Bp, Bt, cvl, cvv, cvg, Rg, Rv, ur, vr, wr, vfgr, vfvr, vflr, temp, press, nx, ny, nz, rl, rul, rvl, rwl, rel, rgpgl, rvpvl, pl, rr, rur, rvr, rwr, rer, rgpgr, rvpvr, pr)
Function/Subroutine Documentation
subroutine bcondinflowperf_gl (integer, intent(in) bcOptType, real(rfreal), intent(in) ro, real(rfreal), intent(in) po, real(rfreal), intent(in) to, real(rfreal), intent(in) Bp, real(rfreal), intent(in) Bt, real(rfreal), intent(in) cvl, real(rfreal), intent(in) cvv, real(rfreal), intent(in) cvg, real(rfreal), intent(in) Rg, real(rfreal), intent(in) Rv, real(rfreal), intent(in) ur, real(rfreal), intent(in) vr, real(rfreal), intent(in) wr, real(rfreal), intent(in) vfgr, real(rfreal), intent(in) vfvr, real(rfreal), intent(in) vflr, real(rfreal), intent(in) temp, real(rfreal), intent(in) press, real(rfreal), intent(in) nx, real(rfreal), intent(in) ny, real(rfreal), intent(in) nz, real(rfreal), intent(in) rl, real(rfreal), intent(in) rul, real(rfreal), intent(in) rvl, real(rfreal), intent(in) rwl, real(rfreal), intent(in) rel, real(rfreal), intent(in) rgpgl, real(rfreal), intent(in) rvpvl, real(rfreal), intent(in) pl, real(rfreal), intent(out) rr, real(rfreal), intent(out) rur, real(rfreal), intent(out) rvr, real(rfreal), intent(out) rwr, real(rfreal), intent(out) rer, real(rfreal), intent(out) rgpgr, real(rfreal), intent(out) rvpvr, real(rfreal), intent(out) pr)
Definition at line 67 of file BcondInflowPerf_GL.F90.
References modtools::makenonzero(), mixtgasliq_c(), mixtliq_c2_bp(), mixtliq_d_dobpppobttto(), mixtperf_c2_grt(), mixtperf_d_prt(), mixtperf_t_cveovm2(), and sqrt().
Referenced by rflu_centralfirstpatch_gl(), and rflu_centralsecondpatch_gl().