Rocstar: BLCK_Main.F90 File Reference
BLCK_Main.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
program rocflo_blocks
Function/Subroutine Documentation
program rocflo_blocks ()
Definition at line 47 of file BLCK_Main.F90.
References Line_2< R, T >::a(), buildversionstring(), moderror::deregisterfunction(), moderror::errorstop(), i, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_readgridregion(), rflo_readregiontopology(), StopWatch::stop(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().