Rocstar: bordertest_struc.C File Reference
bordertest_struc.C File Reference
#include "roccom.h"
#include <iostream>
#include <sstream>
Functions
COM_EXTERN_MODULE (Rocmap)
COM_EXTERN_MODULE (Rocout)
void init_structure_mesh (double coors_s[5][6][10][3])
bool is_local (int pid, int comm_rank, int comm_size)
int main (int argc, char *argv[])
Function Documentation
COM_EXTERN_MODULE (Rocmap)
COM_EXTERN_MODULE (Rocout)
void init_structure_mesh (double coors_s[5][6][10][3])
Definition at line 34 of file bordertest_struc.C.
References i, j, and k.
Referenced by main().
{
 //void init_structure_mesh( double coors_s[3][5][6][10]) {
 for (int i=0; i<10; i++){
         for (int j=0; j<6; j++){
                 for (int k=0; k<5; k++){
                         coors_s[k][j][i][0] = i*.02;
                         coors_s[k][j][i][1] = j*.02;
                         coors_s[k][j][i][2] = k*.02;
                 }
         }
 }
 }
bool is_local (int pid, int comm_rank, int comm_size)
Definition at line 49 of file bordertest_struc.C.
Referenced by IM_Reader::read_mesh(), and Rocin::register_panes().
{
   return ( pid % comm_size == comm_rank);
 }
int main (int argc, char * argv[])
Definition at line 53 of file bordertest_struc.C.
References COM_call_function(), COM_finalize(), COM_get_attribute_handle(), COM_get_function_handle(), COM_init(), COM_INTEGER, COM_LOAD_MODULE_STATIC_DYNAMIC, COM_new_attribute(), COM_new_window(), COM_resize_array(), COM_set_array(), COM_set_array_const(), COM_set_size(), COM_window_init_done(), coors_s, init_structure_mesh(), ni, nj, and nk.
{
   const int ni=10, nj=6, nk=5;
   int total = ni*nj*nk;
   double  coors_s[nk][nj][ni][3];
   int dims[3];
   dims[0] = ni;
   dims[1] = nj;
   dims[2] = nk;
   //int     elmts[num_elmts][8];
   COM_init( &argc, &argv);
   COM_LOAD_MODULE_STATIC_DYNAMIC(Rocmap, "MAP");
   COM_LOAD_MODULE_STATIC_DYNAMIC(Rocout, "OUT");
   COM_new_window("str");
   COM_new_attribute("str.borders", 'n', COM_INTEGER, 1, "");
   init_structure_mesh( coors_s);
   COM_set_array_const("str.:st3:actual", 1, dims);
   COM_set_size("str.nc", 1, total);
   COM_set_array("str.nc", 1, &coors_s[0][0][0][0], 3);
   COM_resize_array( "str.borders");
   COM_window_init_done("str");
   int mesh_hdl = COM_get_attribute_handle("str.mesh");
     std::cout << "Get border nodes... " << endl;
   int MAP_border_nodes = COM_get_function_handle( "MAP.pane_border_nodes");
   int borders_hdl = COM_get_attribute_handle( "str.borders");
   COM_call_function( MAP_border_nodes, &mesh_hdl, &borders_hdl);
   // Output solution into file.
   int OUT_write = COM_get_function_handle( "OUT.write_attribute");
   COM_call_function( OUT_write, "strucmesh", &borders_hdl,
                      "strucmesh", "000");
   //COM_call_function( OUT_write, "strucmesh1", &mesh_hdl,
                      //"strucmesh1", "000");
   COM_finalize();
 }