Rocstar: BuildFileNameSteady.F90 File Reference
BuildFileNameSteady.F90 File Reference
Functions/Subroutines
subroutine buildfilenamesteady (global, dest, ext, id, it, fileName)
Function/Subroutine Documentation
subroutine buildfilenamesteady (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, integer, intent(in) id, integer, intent(in) it, character(chrlen), intent(out) fileName)
Definition at line 50 of file BuildFileNameSteady.F90.
References moderror::deregisterfunction(), moderror::errorstop(), id(), and moderror::registerfunction().
Referenced by rflu_modboundxvutils::rflu_bxv_readvarsascii(), rflu_modboundxvutils::rflu_bxv_readvarsbinary(), rflu_modboundxvutils::rflu_bxv_writevarsascii(), rflu_modboundxvutils::rflu_bxv_writevarsbinary(), rflu_modensight::rflu_ens_builddatainfo(), rflu_modpatchcoeffs::rflu_openpatchcoeffsascii(), rflu_modpatchcoeffs::rflu_openpatchcoeffsbinary(), rflu_modreadwriteflow::rflu_readflowascii(), rflu_modreadwriteflow::rflu_readflowbinary(), rflu_modreadwriteflow::rflu_writeflowascii(), rflu_modreadwriteflow::rflu_writeflowbinary(), spec_rflu_modreadwritevars::spec_rflu_readcvascii(), spec_rflu_modreadwritevars::spec_rflu_readcvbinary(), spec_rflu_modreadwritevars::spec_rflu_readeevascii(), spec_rflu_modreadwritevars::spec_rflu_readeevbinary(), spec_rflu_modreadwritevars::spec_rflu_writecvascii(), spec_rflu_modreadwritevars::spec_rflu_writecvbinary(), spec_rflu_modreadwritevars::spec_rflu_writeeevascii(), spec_rflu_modreadwritevars::spec_rflu_writeeevbinary(), turb_rflu_readsolutionascii(), turb_rflu_readsolutionbinary(), turb_rflu_writesolutionascii(), and turb_rflu_writesolutionbinary().