Rocstar: BuildFileNameBasic.F90 File Reference
BuildFileNameBasic.F90 File Reference
Functions/Subroutines
subroutine buildfilenamebasic (global, dest, ext, id, fileName)
Function/Subroutine Documentation
subroutine buildfilenamebasic (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, integer, intent(in) id, character(chrlen), intent(out) fileName)
Definition at line 49 of file BuildFileNameBasic.F90.
References moderror::deregisterfunction(), moderror::errorstop(), id(), and moderror::registerfunction().
Referenced by plag_moddimensions::plag_rflu_readdimensions(), plag_moddimensions::plag_rflu_writedimensions(), rflu_modcoloring::rflu_col_readcoloring(), rflu_modcoloring::rflu_col_writecoloring(), rflu_modcommlists::rflu_comm_readcommlists(), rflu_modcommlists::rflu_comm_writecommlists(), rflu_modensight::rflu_ens_writefilecase(), rflu_modreadwritebcdatafile::rflu_readbcdatafile(), rflu_moddimensions::rflu_readdimensions(), rflu_modreadwritegrid::rflu_readgridascii(), rflu_modreadwritegrid::rflu_readgridbinary(), rflu_modreadwritegridspeeds::rflu_readgridspeedsascii(), rflu_modreadwritegridspeeds::rflu_readgridspeedsbinary(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modrenumberings::rflu_rnmb_readpxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_readsc2rmap(), rflu_modrenumberings::rflu_rnmb_writepxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_writesc2rmap(), rflu_modreadwritebcdatafile::rflu_writebcdatafile(), rflu_moddimensions::rflu_writedimensions(), rflu_moddimensions::rflu_writedimensionsborders(), rflu_modreadwritegrid::rflu_writegridascii(), rflu_modreadwritegrid::rflu_writegridbinary(), rflu_modreadwritegridspeeds::rflu_writegridspeedsascii(), rflu_modreadwritegridspeeds::rflu_writegridspeedsbinary(), and rflu_modcellmapping::rflu_writeloc2globcellmapping().