Rocstar: builtin_couplings.C File Reference
builtin_couplings.C File Reference
#include "rocman.h"
#include "builtin_couplings.h"
#include "FluidAgent.h"
#include "SolidAgent.h"
#include "BurnAgent.h"
#include "basic_actions.h"
#include "transfer_actions.h"
#include "Interpolate.h"
Functions
static void declare_fluid_actions (FluidAgent *fluid_agent)
static void declare_solid_actions (SolidAgent *solid_agent)
Detailed Description
Contains the implementation of builtin coupling schemes.
Definition in file builtin_couplings.C.
Function Documentation
static void declare_fluid_actions (FluidAgent * fluid_agent) static
Definition at line 45 of file builtin_couplings.C.
References Agent::add_bcaction(), Agent::add_gmaction(), Agent::add_icaction(), FluidAgent::fluidBufB, FluidAgent::fluidBufNB, FluidAgent::fluidBufNG, and FluidAgent::ifluid_i.
Referenced by FluidAlone::FluidAlone().
{
   const std::string ifluid_i = fluid_agent->ifluid_i;
   const std::string fluidBufB = fluid_agent->fluidBufB;
   const std::string fluidBufNB = fluid_agent->fluidBufNB;
   const std::string fluidBufNG = fluid_agent->fluidBufNG;
   // No action for initial call back routine
   fluid_agent->add_icaction( new DummyAction());
   // UPDATE_INBUFF_BC_FLUID
   // Level-1 boundary condition: Set bflag and Tflm_alp to 0
   fluid_agent->add_bcaction( new SetZero( fluidBufB+".Tflm_alp"), 1);
   //fluid_agent->add_bcaction( new SetZero( fluidBufNB+".Tb_alp"), 1);
   //  fluid_agent->add_bcaction( new SetZero( fluidBufB+".bflag"), 1);
   // Level-2 boundary condition: Set mdot and rhofvf to 0
   fluid_agent->add_bcaction( new SetZero( fluidBufB+".mdot_alp"), 2);
   fluid_agent->add_bcaction( new SetZero( fluidBufNG+".rhofvf_alp"), 2);
   // Set displacement to zero.
   //fluid_agent->add_gmaction( new SetZero( fluidBufNG+".du_alp"));
   fluid_agent->add_gmaction( new Reset_du_alp( fluid_agent));
 }
static void declare_solid_actions (SolidAgent * solid_agent) static
Definition at line 90 of file builtin_couplings.C.
References Agent::add_bcaction(), Agent::add_bcinitaction(), Agent::add_icaction(), Agent::get_coupling(), Coupling::get_rocmancontrol_param(), RocmanControl_parameters::pressure, and SolidAgent::solidBuf.
{
   std::string solidBuf = solid_agent->solidBuf;
     // No action for initial call back routine
   solid_agent->add_icaction( new DummyAction());
   double pressure = solid_agent->get_coupling()->get_rocmancontrol_param()->pressure;
     // INIT_INBUFF_SOLID() in "solid_agent.f90"
   solid_agent->add_bcinitaction( new SetValueDouble(solidBuf+".ts", pressure));
     // INIT_INTERP_HANDLES() in "solid_agent.f90"
   solid_agent->add_bcaction( new Extrapolate_Linear(solid_agent, solid_agent,
                                                     solidBuf+".ts"));
 }