Rocstar: BuildFileNamePlain.F90 File Reference
BuildFileNamePlain.F90 File Reference
Functions/Subroutines
subroutine buildfilenameplain (global, dest, ext, fileName)
Function/Subroutine Documentation
subroutine buildfilenameplain (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, character(chrlen), intent(out) fileName)
Definition at line 48 of file BuildFileNamePlain.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by inrt_readmaterialinput(), readinputfile(), rflo_modrestartinfo::rflo_closerestartinfo(), rflo_modrestartinfo::rflo_openrestartinfo(), rflu_closepostinfo(), rflu_modregionmapping::rflu_closeregionmappingfile(), rflu_closerestartinfo(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_modgambit::rflu_convgambit2rocflu(), rflu_modmesh3d::rflu_convmesh3d2rocflu(), rflu_modtetmesh::rflu_convtetmesh2rocflu(), rflu_modvgridns::rflu_convvgridns2rocflu(), rflu_openconverfile(), rflu_openpostinfo(), rflu_modprobes::rflu_openprobefiles(), rflu_modregionmapping::rflu_openregionmappingfile(), rflu_openrestartinfo(), rflu_openstatsfileoles(), rflu_opentotalmassfile(), rflu_modreadbcinputfile::rflu_readbcinputfile(), rflu_modcentaur::rflu_readgridcentaurascii(), rflu_modcentaur::rflu_readgridcentaurbinary(), rflu_modcobalt::rflu_readgridcobalt(), rflu_modgambit::rflu_readgridgambitneutral(), rflu_modmesh3d::rflu_readgridmesh3d(), rflu_modtetmesh::rflu_readgridtetmesh(), rflu_modvgridns::rflu_readgridvgridns(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_modstl::rflu_stl_writesurfgridascii(), rflu_modsymmetryperiodic::rflu_sype_readtransforms(), rflu_modsymmetryperiodic::rflu_sype_setsypepatchesflag(), rflu_modsymmetryperiodic::rflu_sype_writetransforms(), rflu_modtetmesh::rflu_writesurfgridtetmesh(), spec_readinputfile(), and spec_rflu_readbcinputfile().