Rocstar: BuildFileNameUnsteady.F90 File Reference
BuildFileNameUnsteady.F90 File Reference
Functions/Subroutines
subroutine buildfilenameunsteady (global, dest, ext, id, tm, fileName)
Function/Subroutine Documentation
subroutine buildfilenameunsteady (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, integer, intent(in) id, real(rfreal), intent(in) tm, character(chrlen), intent(out) fileName)
Definition at line 50 of file BuildFileNameUnsteady.F90.
References moderror::deregisterfunction(), moderror::errorstop(), id(), and moderror::registerfunction().
Referenced by plag_modsurfstats::plag_opensurfstatsascii(), plag_modsurfstats::plag_opensurfstatsbinary(), plag_moddimensions::plag_rflu_readdimensions(), plag_rflu_readsolutionascii(), plag_rflu_readsolutionbinary(), plag_moddimensions::plag_rflu_writedimensions(), plag_rflu_writesolutionascii(), plag_rflu_writesolutionbinary(), rflu_modboundxvutils::rflu_bxv_readvarsascii(), rflu_modboundxvutils::rflu_bxv_readvarsbinary(), rflu_modboundxvutils::rflu_bxv_writevarsascii(), rflu_modboundxvutils::rflu_bxv_writevarsbinary(), rflu_modensight::rflu_ens_builddatainfo(), rflu_modpatchcoeffs::rflu_openpatchcoeffsascii(), rflu_modpatchcoeffs::rflu_openpatchcoeffsbinary(), rflu_moddimensions::rflu_readdimensions(), rflu_modreadwriteflow::rflu_readflowascii(), rflu_modreadwriteflow::rflu_readflowbinary(), rflu_modreadwritegrid::rflu_readgridascii(), rflu_modreadwritegrid::rflu_readgridbinary(), rflu_modreadwritegridspeeds::rflu_readgridspeedsascii(), rflu_modreadwritegridspeeds::rflu_readgridspeedsbinary(), rflu_moddimensions::rflu_writedimensions(), rflu_moddimensions::rflu_writedimensionsborders(), rflu_modreadwriteflow::rflu_writeflowascii(), rflu_modreadwriteflow::rflu_writeflowbinary(), rflu_modreadwritegrid::rflu_writegridascii(), rflu_modreadwritegrid::rflu_writegridbinary(), rflu_modreadwritegridspeeds::rflu_writegridspeedsascii(), rflu_modreadwritegridspeeds::rflu_writegridspeedsbinary(), spec_rflu_modreadwritevars::spec_rflu_readcvascii(), spec_rflu_modreadwritevars::spec_rflu_readcvbinary(), spec_rflu_modreadwritevars::spec_rflu_readeevascii(), spec_rflu_modreadwritevars::spec_rflu_readeevbinary(), spec_rflu_modreadwritevars::spec_rflu_writecvascii(), spec_rflu_modreadwritevars::spec_rflu_writecvbinary(), spec_rflu_modreadwritevars::spec_rflu_writeeevascii(), spec_rflu_modreadwritevars::spec_rflu_writeeevbinary(), turb_rflu_readsolutionascii(), turb_rflu_readsolutionbinary(), turb_rflu_writesolutionascii(), and turb_rflu_writesolutionbinary().