Rocstar: c3d6nm.f90 File Reference
c3d6nm.f90 File Reference
Functions/Subroutines
subroutine c3d6nm (nsubn, nsubf, nsubn2, nsubf2, CoorOverlay, ElConnOverlay, sd_subface_parents, sd_subface_parents2, sd_subface_mate, sd_subface_nat_coors, sd_subface_nat_coors_mate, FaceOfVolEl, FaceOfVolEl2, NumNp, NumEl, ElConn, nf, nf2, MapFaceEl2Vol, MapFaceEl2Vol2, deltan, deltat, sigmax, taumax, Sinit, Rnet, Disp, Sthresh, NumMatCoh, MatID, SignFlag)
subroutine crossprod_3d (x1, y1, z1, x2, y2, z2, x3, y3, z3)
Function/Subroutine Documentation
subroutine c3d6nm (integer nsubn, integer nsubf, integer nsubn2, integer nsubf2, real*8, dimension(1:3,1:nsubn) CoorOverlay, integer, dimension(1:3,1:nsubf) ElConnOverlay, integer, dimension(1:nsubf) sd_subface_parents, integer, dimension(1:nsubf2) sd_subface_parents2, integer, dimension(1:nsubf) sd_subface_mate, real*4, dimension(1:6,1:nsubf) sd_subface_nat_coors, real*4, dimension(1:6,1:nsubf2) sd_subface_nat_coors_mate, integer, dimension(1:nf) FaceOfVolEl, integer, dimension(1:nf2) FaceOfVolEl2, integer NumNp, integer NumEl, integer, dimension(1:4,1:numel) ElConn, integer nf, integer nf2, integer, dimension(1:nf) MapFaceEl2Vol, integer, dimension(1:nf2) MapFaceEl2Vol2, real*8, dimension(nummatcoh) deltan, real*8, dimension(nummatcoh) deltat, real*8, dimension(nummatcoh) sigmax, real*8, dimension(nummatcoh) taumax, real*8, dimension(nummatcoh) Sinit, real*8, dimension(3*numnp) Rnet, real*8, dimension(3*numnp) Disp, real*8, dimension(1:3,1:nsubf) Sthresh, integer NumMatCoh, integer MatID, real*8 SignFlag)
Definition at line 54 of file c3d6nm.f90.
References Direction_2< R, T >::delta(), dot_product(), i, j, k, CImg< T >::magnitude(), max(), min(), Halfedge::normal(), halfspace3d::side(), sqrt(), and x.
Referenced by updatestructuralsoln::updatestructural().
subroutine crossprod_3d (real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2, real*8 x3, real*8 y3, real*8 z3)
Definition at line 398 of file c3d6nm.f90.