Rocstar: CauchyStressPrinc.f90 File Reference
CauchyStressPrinc.f90 File Reference
Functions/Subroutines
subroutine cauchystressprinc (ndime, xmu, xlamb, detf, stret, princ, sigma, sprin)
Function/Subroutine Documentation
subroutine cauchystressprinc (ndime, xmu, xlamb, detf, dimension(3) stret, dimension(3,3) princ, dimension(3,3) sigma, dimension(3) sprin)
Definition at line 53 of file CauchyStressPrinc.f90.
References Connectivity::dimension(), id(), and CImg< T >::sum().
Referenced by v3d4_neohookeanincompressprin().