Rocstar: CellCentroid.F90 File Reference
CellCentroid.F90 File Reference
Functions/Subroutines
subroutine centroidtetra (xyzNodes, cofgX, cofgY, cofgZ)
subroutine centroidpyramid (xyzNodes, cofgX, cofgY, cofgZ)
subroutine centroidprism (xyzNodes, cofgX, cofgY, cofgZ)
subroutine centroidhexa (xyzNodes, cofgX, cofgY, cofgZ)
Function/Subroutine Documentation
subroutine centroidhexa (real(rfreal), dimension(3,8) xyzNodes, real(rfreal) cofgX, real(rfreal) cofgY, real(rfreal) cofgZ)
Definition at line 106 of file CellCentroid.F90.
Referenced by rflo_calccellcentroids(), rflo_openprobefile(), and turb_ranswalldistovpatch().
subroutine centroidprism (real(rfreal), dimension(3,6) xyzNodes, real(rfreal) cofgX, real(rfreal) cofgY, real(rfreal) cofgZ)
Definition at line 87 of file CellCentroid.F90.
subroutine centroidpyramid (real(rfreal), dimension(3,5) xyzNodes, real(rfreal) cofgX, real(rfreal) cofgY, real(rfreal) cofgZ)
Definition at line 68 of file CellCentroid.F90.
subroutine centroidtetra (real(rfreal), dimension(3,4) xyzNodes, real(rfreal) cofgX, real(rfreal) cofgY, real(rfreal) cofgZ)
Definition at line 49 of file CellCentroid.F90.