Rocstar: PointS3.h File Reference
CGAL/include/CGAL/SimpleCartesian/PointS3.h File Reference
#include <CGAL/Origin.h>
#include <CGAL/SimpleCartesian/VectorS3.h>
#include <CGAL/SimpleCartesian/Aff_transformationS3.h>
#include <CGAL/Bbox_3.h>
#include <CGAL/number_utils.h>
Classes
class PointS3< FT >
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE PointS3< FT > operator+ (const Origin &o, const VectorS3< FT > &v)
template<class FT >
PointS3< FT > operator- (const Origin &o, const VectorS3< FT > &v)
template<class FT >
PointS3< FT > operator+ (const PointS3< FT > &p, const VectorS3< FT > &v)
template<class FT >
PointS3< FT > operator- (const PointS3< FT > &p, const VectorS3< FT > &v)
template<class FT >
PointS3< FT > operator+ (const Origin &, const VectorS3< FT > &v)
template<class FT >
VectorS3< FT > operator- (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
VectorS3< FT > operator- (const PointS3< FT > &p, const Origin &)
template<class FT >
VectorS3< FT > operator- (const Origin &, const PointS3< FT > &p)
template<class FT >
std::ostream & operator<< (std::ostream &os, const PointS3< FT > &p)
template<class FT >
std::istream & operator>> (std::istream &is, PointS3< FT > &p)
Function Documentation
CGAL_BEGIN_NAMESPACE PointS3<FT> operator+ (const Origin & o, const VectorS3< FT > & v) inline
Definition at line 263 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References v.
 { return PointS3<FT>(v); }
PointS3<FT> operator+ (const PointS3< FT > & p, const VectorS3< FT > & v) inline
Definition at line 251 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References VectorS3< FT >::x(), PointS3< FT >::x(), VectorS3< FT >::y(), PointS3< FT >::y(), VectorS3< FT >::z(), and PointS3< FT >::z().
 { return PointS3<FT>(p.x() + v.x(), p.y() + v.y(), p.z() + v.z()); }
PointS3<FT> operator+ (const Origin & , const VectorS3< FT > & v) inline
Definition at line 263 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References v.
 { return PointS3<FT>(v); }
PointS3< FT > operator- (const Origin & o, const VectorS3< FT > & v) inline
Definition at line 269 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References v.
 { return PointS3<FT>(-v); }
PointS3<FT> operator- (const PointS3< FT > & p, const VectorS3< FT > & v) inline
Definition at line 257 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References VectorS3< FT >::x(), PointS3< FT >::x(), VectorS3< FT >::y(), PointS3< FT >::y(), VectorS3< FT >::z(), and PointS3< FT >::z().
 { return PointS3<FT>(p.x() - v.x(), p.y() - v.y(), p.z() - v.z()); }
VectorS3<FT> operator- (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 275 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 { return VectorS3<FT>(p.x() - q.x(), p.y() - q.y(), p.z() - q.z()); }
VectorS3<FT> operator- (const PointS3< FT > & p, const Origin &) inline
Definition at line 282 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 { return VectorS3<FT>(p); }
VectorS3<FT> operator- (const Origin & , const PointS3< FT > & p) inline
Definition at line 289 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 { return VectorS3<FT>(-p.x(), -p.y(), -p.z()); }
std::ostream& operator<< (std::ostream & os, const PointS3< FT > & p)
Definition at line 313 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References IO::ASCII, IO::BINARY, IO::mode, and write().
 {
     switch(os.iword(IO::mode)) {
     case IO::ASCII :
         return os << p.x() << ' ' << p.y()  << ' ' << p.z();
     case IO::BINARY :
         write(os, p.x());
         write(os, p.y());
         write(os, p.z());
         return os;
     default:
         os << "PointS3(" << p.x() << ", " << p.y()  << ", " << p.z() << ")";
         return os;
     }
 }
std::istream& operator>> (std::istream & is, PointS3< FT > & p)
Definition at line 332 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References IO::ASCII, IO::BINARY, CGAL_kernel_assertion_msg, IO::mode, read(), x, y, and z.
 {
     FT x, y, z;
     switch(is.iword(IO::mode)) {
     case IO::ASCII :
         is >> x >> y >> z;
         break;
     case IO::BINARY :
         read(is, x);
         read(is, y);
         read(is, z);
         break;
     default:
         CGAL_kernel_assertion_msg(false,"Stream must be in ascii or binary mode"
 );
         // throw ios_base::failure("Stream must be in ascii or binary mode");
         break;
     }
     p = PointS3<FT>(x, y, z);
     return is;
 }