Rocstar: VectorS2.h File Reference
CGAL/include/CGAL/SimpleCartesian/VectorS2.h File Reference
#include <CGAL/SimpleCartesian/PointS2.h>
#include <CGAL/SimpleCartesian/DirectionS2.h>
Classes
class VectorS2< FT >
Functions
template<class FT >
CGAL_KERNEL_INLINE VectorS2< FT > operator* (const FT &c, const VectorS2< FT > &w)
template<class FT >
std::ostream & operator<< (std::ostream &os, const VectorS2< FT > &v)
template<class FT >
std::istream & operator>> (std::istream &is, VectorS2< FT > &p)
Function Documentation
CGAL_KERNEL_INLINE VectorS2<FT> operator* (const FT & c, const VectorS2< FT > & w)
Definition at line 241 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::x(), and VectorS2< FT >::y().
 { return VectorS2<FT>( c* w.x(), c * w.y()) ; }
std::ostream& operator<< (std::ostream & os, const VectorS2< FT > & v)
Definition at line 274 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References IO::ASCII, IO::BINARY, IO::mode, v, and write().
 {
     switch(os.iword(IO::mode)) {
     case IO::ASCII :
         return os << v.x() << ' ' << v.y();
     case IO::BINARY :
         write(os, v.x());
         write(os, v.y());
         return os;
     default:
         return os << "VectorS2(" << v.x() << ", " << v.y() << ')';
     }
 }
std::istream& operator>> (std::istream & is, VectorS2< FT > & p)
Definition at line 291 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References IO::ASCII, IO::BINARY, IO::mode, read(), x, and y.
 {
     FT x, y;
     switch(is.iword(IO::mode)) {
     case IO::ASCII :
         is >> x >> y;
         break;
     case IO::BINARY :
         read(is, x);
         read(is, y);
         break;
     default:
         std::cerr << "" << std::endl;
         std::cerr << "Stream must be in ascii or binary mode" << std::endl;
         break;
     }
     p = VectorS2<FT>(x, y);
     return is;
 }