Rocstar: Bbox_2.h File Reference
CGAL/include/CGAL/Bbox_2.h File Reference
#include <CGAL/basic.h>
#include <CGAL/cartesian_classes.h>
#include <CGAL/Fourtuple.h>
Classes
class Bbox_2
Functions
bool do_overlap (const Bbox_2 &bb1, const Bbox_2 &bb2)
std::ostream & operator<< (std::ostream &os, const Bbox_2 &b)
std::istream & operator>> (std::istream &is, Bbox_2 &b)
Function Documentation
bool do_overlap (const Bbox_2 & bb1, const Bbox_2 & bb2) inline
Definition at line 138 of file CGAL/include/CGAL/Bbox_2.h.
References Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), and Bbox_2::ymin().
Referenced by Segment_2_Segment_2_pair< R >::intersection_type().
 {
     // check for emptiness ??
     if (bb1.xmax() < bb2.xmin() || bb2.xmax() < bb1.xmin())
         return false;
     if (bb1.ymax() < bb2.ymin() || bb2.ymax() < bb1.ymin())
         return false;
     return true;
 }
std::ostream& operator<< (std::ostream & os, const Bbox_2 & b) inline
Definition at line 151 of file CGAL/include/CGAL/Bbox_2.h.
References IO::ASCII, IO::BINARY, IO::mode, write(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), and Bbox_2::ymin().
 {
     switch(os.iword(IO::mode)) {
     case IO::ASCII :
         os << b.xmin() << ' ' << b.ymin() << ' '
            << b.xmax() << ' ' << b.ymax();
         break;
     case IO::BINARY :
         write(os, b.xmin());
         write(os, b.ymin());
         write(os, b.xmax());
         write(os, b.ymax());
         break;
     default:
         os << "Bbox_2(" << b.xmin() << ", " << b.ymin() << ", "
                         << b.xmax() << ", " << b.ymax() << ")";
         break;
     }
     return os;
 }
std::istream& operator>> (std::istream & is, Bbox_2 & b) inline
Definition at line 178 of file CGAL/include/CGAL/Bbox_2.h.
References IO::ASCII, IO::BINARY, IO::mode, and read().
 {
     double xmin, ymin, xmax, ymax;
     switch(is.iword(IO::mode)) {
     case IO::ASCII :
         is >> xmin >> ymin >> xmax >> ymax;
         break;
     case IO::BINARY :
         read(is, xmin);
         read(is, ymin);
         read(is, xmax);
         read(is, ymax);
         break;
     }
     b = Bbox_2(xmin, ymin, xmax, ymax);
     return is;
 }