Rocstar: VectorS3.h File Reference
CGAL/include/CGAL/SimpleCartesian/VectorS3.h File Reference
#include <CGAL/SimpleCartesian/PointS3.h>
#include <CGAL/SimpleCartesian/DirectionS3.h>
Classes
class VectorS3< FT >
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE VectorS3< FT > operator- (const PointS3< FT > &p, const Origin &o)
template<class FT >
VectorS3< FT > operator* (const FT &c, const VectorS3< FT > &w)
template<class FT >
VectorS3< FT > cross_product (const VectorS3< FT > &v, const VectorS3< FT > &w)
template<class FT >
std::ostream & operator<< (std::ostream &os, const VectorS3< FT > &v)
template<class FT >
std::istream & operator>> (std::istream &is, VectorS3< FT > &p)
Function Documentation
VectorS3<FT> cross_product (const VectorS3< FT > & v, const VectorS3< FT > & w)
Definition at line 285 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
 {
     return VectorS3<FT>( v.y() * w.z() - v.z() * w.y() ,
                          v.z() * w.x() - v.x() * w.z() ,
                          v.x() * w.y() - v.y() * w.x() );
 }
VectorS3<FT> operator* (const FT & c, const VectorS3< FT > & w) inline
Definition at line 274 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
 { return VectorS3<FT>( c* w.x(), c * w.y(), c * w.z()) ; }
CGAL_BEGIN_NAMESPACE VectorS3<FT> operator- (const PointS3< FT > & p, const Origin & o) inline
Definition at line 282 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 { return VectorS3<FT>(p); }
std::ostream& operator<< (std::ostream & os, const VectorS3< FT > & v)
Definition at line 307 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References IO::ASCII, IO::BINARY, IO::mode, v, and write().
 {
     switch(os.iword(IO::mode)) {
     case IO::ASCII :
         return os << v.x() << ' ' << v.y()  << ' ' << v.z();
     case IO::BINARY :
         write(os, v.x());
         write(os, v.y());
         write(os, v.z());
         return os;
     default:
         os << "VectorS3(" << v.x() << ", " << v.y() <<  ", " << v.z() << ")";
         return os;
     }
 }
std::istream& operator>> (std::istream & is, VectorS3< FT > & p)
Definition at line 326 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References IO::ASCII, IO::BINARY, CGAL_kernel_assertion_msg, IO::mode, read(), x, y, and z.
 {
     FT x, y, z;
     switch(is.iword(IO::mode)) {
     case IO::ASCII :
         is >> x >> y >> z;
         break;
     case IO::BINARY :
         read(is, x);
         read(is, y);
         read(is, z);
         break;
     default:
         CGAL_kernel_assertion_msg(false,"Stream must be in ascii or binary mode");
         // throw ios_base::failure("Stream must be in ascii or binary mode");
         break;
     }
     p = VectorS3<FT>(x, y, z);
     return is;
 }