Rocstar: modsortsearch Module Reference
modsortsearch Module Reference
Public Member Functions
subroutine binarysearchinteger (a, n, v, i, j)
subroutine cyclelist (a, na, i, v)
subroutine findcommonsortedintegers (a, na, b, nb, c, ncMax, nc, errorFlag)
subroutine mergesortedintegers (global, na, nb, a, b, nm, im, m)
subroutine quicksortinteger (a, n)
subroutine quicksortintegerinteger (a, b, n)
subroutine quicksortrfreal (a, n)
subroutine quicksortrfrealinteger (a, b, n)
subroutine removecommonsortedintegers (a, na, b, nb, nb2)
subroutine removecommonsortedintegersfancy (a, na, na2, b, nb, nb2, c, ncMax, nc, errorFlag)
subroutine removeinteger (a, na, iLoc)
subroutine simplifysortedintegers (a, na, nb)
Public Attributes
integer, parameter element_not_found = -1
Private Attributes
character(chrlen), parameter,
private rcsidentstring = '$RCSfile: ModSortSearch.F90,v $ $Revision: 1.18 $'
Detailed Description
Definition at line 41 of file ModSortSearch.F90.
Member Function/Subroutine Documentation
subroutine binarysearchinteger (integer, dimension(n), intent(in) a, integer, intent(in) n, integer, intent(in) v, integer, intent(out) i, integer, intent(inout), optional j)
Definition at line 98 of file ModSortSearch.F90.
References Line_2< R, T >::a(), i, j, n, and v.
Referenced by findcommonsortedintegers(), plag_moddatastruct::plag_dstr_buildcell2pcllist(), plag_rflu_initsolfromserial(), removecommonsortedintegers(), removecommonsortedintegersfancy(), rflu_modstencilsutils::rflu_addbfaces(), rflu_modstencilsutils::rflu_addcelllayer(), rflu_modstencilsutils::rflu_addcelllayer_1d(), rflu_modstencilsutils::rflu_addcelllayer_1d_g(), rflu_modstencilsutils::rflu_addfacevertneighbs(), rflu_modfacelist::rflu_buildavface2borderlist(), rflu_modfacelist::rflu_buildavface2patchlist(), rflu_modstencilscells::rflu_buildc2cstencil_1d(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modstencilscells::rflu_buildc2cstencilbasic_1d(), rflu_modedgelist::rflu_buildedge2celllist(), rflu_modpatchutils::rflu_buildpatchneighbormaps(), rflu_modtopologyutils::rflu_buildvertcellnghblist(), rflu_modcoloring::rflu_col_buildcolorings(), rflu_modcommlists::rflu_comm_buildcommlistscells(), rflu_modcommlists::rflu_comm_buildcommlistsvert(), rflu_modcommlists::rflu_comm_checkcountborders(), rflu_modcommlists::rflu_comm_countborders(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_modresidual::rflu_getresidualsupport2(), rflu_getspecialcells(), rflu_modcellfaceedgeinfo::rflu_getvirtualcellreg(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv1(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_modpartitionregion::rflu_part_buildpatchlists(), rflu_modpartitionregion::rflu_part_createpatchlists(), rflu_pickspecialcells(), rflu_printlocinfo(), rflu_modrenumberlist::rflu_renumberlist(), rflu_modrenumberlist::rflu_renumberlist2(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap3d(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2(), rflu_modsymmetryperiodic::rflu_sype_augmentcelllists(), rflu_modsymmetryperiodic::rflu_sype_augmentvertexlists(), rflu_modsymmetryperiodic::rflu_sype_buildp2vclist(), rflu_modsymmetryperiodic::rflu_sype_getactualserialcell(), rflu_modsymmetryperiodic::rflu_sype_getrelatedvertex(), rflu_modsymmetryperiodic::rflu_sype_imposevertexmap(), rflu_modtecplotutils::rflu_tec_writezonecellsspecial(), rflu_modtecplotutils::rflu_tec_writezonefacesspecial(), rflu_modtecplotutils::rflu_tec_writezonesurf(), rflu_modboundarytests::rflu_testisboundarycell(), and rflu_modboundarytests::rflu_testisboundaryvertex().
subroutine cyclelist (integer, dimension(na), intent(inout) a, integer, intent(in) na, integer, intent(in) i, integer, intent(in) v)
Definition at line 188 of file ModSortSearch.F90.
References Line_2< R, T >::a(), i, j, k, and v.
Referenced by rflu_modcobalt::rflu_convcobalt2rocflu().
subroutine findcommonsortedintegers (integer, dimension(na), intent(in) a, integer, intent(in) na, integer, dimension(nb), intent(in) b, integer, intent(in) nb, integer, dimension(ncmax), intent(out) c, integer, intent(in) ncMax, integer, intent(out) nc, integer, intent(out) errorFlag)
Definition at line 261 of file ModSortSearch.F90.
References Line_2< R, T >::a(), Color::b(), binarysearchinteger(), and Line_2< R, T >::c().
Referenced by rflu_modstencilscells::rflu_buildc2cstencilbasic().
subroutine mergesortedintegers (type(t_global), pointer global, integer, intent(in) na, integer, intent(in) nb, integer, dimension(na), intent(in) a, integer, dimension(nb), intent(in) b, integer, intent(in) nm, integer, intent(out) im, integer, dimension(nm), intent(out) m)
Definition at line 356 of file ModSortSearch.F90.
References Line_2< R, T >::a(), Color::b(), moderror::errorstop(), i, Aff_transformation_2< R_ >::m(), and simplifysortedintegers().
Referenced by rflu_modboundlists::rflu_buildbvertexmlist(), and rflu_printlocinfo().
subroutine quicksortinteger (integer, dimension(n), intent(inout) a, integer, intent(in) n)
Definition at line 482 of file ModSortSearch.F90.
References Line_2< R, T >::a(), i, j, k, n, Color::r(), s, and x.
Referenced by rflu_modstencilsutils::rflu_addbfaces(), rflu_modstencilsutils::rflu_addcelllayer(), rflu_modstencilsutils::rflu_addcelllayer_1d(), rflu_modstencilsutils::rflu_addcelllayer_1d_g(), rflu_modstencilsutils::rflu_addfacevertneighbs(), rflu_modfacelist::rflu_buildavface2patchlist(), rflu_modboundlists::rflu_buildbcellmlist(), rflu_modboundlists::rflu_buildbfacesortlists(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modstencilscells::rflu_buildc2cstencil_1d(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modstencilscells::rflu_buildc2cstencilbasic_1d(), rflu_modtopologyutils::rflu_buildcellvertlist(), rflu_modtopologyutils::rflu_buildconnvertlist(), rflu_modedgelist::rflu_buildedge2celllist(), rflu_modedgelist::rflu_buildedgelist(), rflu_modfacelist::rflu_buildfacelist(), rflu_modtopologyutils::rflu_buildfacevertlist(), rflu_modtopologyutils::rflu_buildvertcellnghblist(), rflu_modregionmapping::rflu_checkregionmapping(), rflu_modcoloring::rflu_col_buildcolorings(), rflu_modcommlists::rflu_comm_buildcommlistsvert(), rflu_modcommlists::rflu_comm_checkcountborders(), rflu_modcommlists::rflu_comm_countborders(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_modfacelist::rflu_getopposingfaces(), rflu_modresidual::rflu_getresidualsupport2(), rflu_getspecialcells(), rflu_modfacelist::rflu_insertintocell2facelist(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv1(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_pickspecialcells(), rflu_printlocinfo(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2(), rflu_modsymmetryperiodic::rflu_sype_augmentvertexlists(), rflu_modtecplotutils::rflu_tec_writezonecellsspecial(), rflu_modtecplotutils::rflu_tec_writezonefacesspecial(), and rflu_modboundarytests::rflu_testisboundarycell().
subroutine quicksortintegerinteger (integer, dimension(n), intent(inout) a, integer, dimension(n), intent(inout) b, integer, intent(in) n)
Definition at line 602 of file ModSortSearch.F90.
References Line_2< R, T >::a(), Color::b(), i, j, k, n, Color::r(), s, v, and x.
Referenced by plag_moddatastruct::plag_dstr_buildcell2pcllist(), rflu_modfacelist::rflu_buildavface2borderlist(), rflu_modpartitionregion::rflu_part_buildpatchlists(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap2d(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap3d(), rflu_modrenumberings::rflu_rnmb_buildsc2pcmap(), rflu_modrenumberings::rflu_rnmb_buildsv2pvmap(), rflu_modsymmetryperiodic::rflu_sype_augmentcelllists(), rflu_modsymmetryperiodic::rflu_sype_augmentvertexlists(), and rflu_modsymmetryperiodic::rflu_sype_getrelatedvertex().
subroutine quicksortrfreal (real(kind=rfreal), dimension(n), intent(inout) a, integer, intent(in) n)
Definition at line 722 of file ModSortSearch.F90.
References Line_2< R, T >::a(), i, j, k, n, Color::r(), s, and x.
Referenced by rflu_modgeometry::rflu_buildgeometry(), and rflu_checkgridspeeds().
subroutine quicksortrfrealinteger (real(kind=rfreal), dimension(n), intent(inout) a, integer, dimension(n), intent(inout) b, integer, intent(in) n)
Definition at line 840 of file ModSortSearch.F90.
References Line_2< R, T >::a(), Color::b(), i, j, k, n, Color::r(), s, v, and x.
Referenced by rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modsplittree::rflu_buildsplittree(), rflu_modoles::rflu_buildstencilsoles(), and rflu_modstencilsutils::rflu_sortbfaces().
subroutine removecommonsortedintegers (integer, dimension(na), intent(in) a, integer, intent(in) na, integer, dimension(nb), intent(inout) b, integer, intent(in) nb, integer, intent(out) nb2)
Definition at line 961 of file ModSortSearch.F90.
References Line_2< R, T >::a(), Color::b(), binarysearchinteger(), and removeinteger().
Referenced by rflu_modtopologyutils::rflu_buildvertcellnghblist().
subroutine removecommonsortedintegersfancy (integer, dimension(na), intent(inout) a, integer, intent(in) na, integer, intent(out) na2, integer, dimension(nb), intent(inout) b, integer, intent(in) nb, integer, intent(out) nb2, integer, dimension(ncmax), intent(out) c, integer, intent(in) ncMax, integer, intent(out) nc, integer, intent(out) errorFlag)
Definition at line 1038 of file ModSortSearch.F90.
References Line_2< R, T >::a(), Color::b(), binarysearchinteger(), Line_2< R, T >::c(), and removeinteger().
Referenced by rflu_modcommlists::rflu_comm_buildcommlistsvert().
subroutine removeinteger (integer, dimension(:), intent(inout) a, integer, intent(inout) na, integer, intent(in) iLoc)
Definition at line 1131 of file ModSortSearch.F90.
References Line_2< R, T >::a().
Referenced by removecommonsortedintegers(), removecommonsortedintegersfancy(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), and rflu_modstencilscells::rflu_buildc2cstencilbasic_1d().
subroutine simplifysortedintegers (integer, dimension(na), intent(inout) a, integer, intent(in) na, integer, intent(out) nb)
Definition at line 1197 of file ModSortSearch.F90.
References Line_2< R, T >::a(), and Aff_transformation_2< R_ >::m().
Referenced by mergesortedintegers(), rflu_modboundlists::rflu_buildbcellmlist(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modstencilscells::rflu_buildc2cstencilbasic_1d(), rflu_printlocinfo(), rflu_modtecplotutils::rflu_tec_writezonecellsspecial(), and rflu_modtecplotutils::rflu_tec_writezonefacesspecial().
Member Data Documentation
integer, parameter element_not_found = -1
Definition at line 58 of file ModSortSearch.F90.
character(chrlen), parameter, private rcsidentstring = '$RCSfile: ModSortSearch.F90,v $ $Revision: 1.18 $' private
Definition at line 59 of file ModSortSearch.F90.
The documentation for this module was generated from the following file:
ModSortSearch.F90