Rocstar: Angle_Metric_3 Class Reference
Angle_Metric_3 Class Reference
3D Max and Min Angle Metric Class
#include <Geometric_Metrics_3.h>
Public Member Functions
Angle_Metric_3 ()
Initialize a 3D Angle Metric.
virtual void compute (double atts[]) const
Calculate the metric value on this element.
double maxValue () const
Get the maximum value for this metric.
double minValue () const
Get the minimum value for this metric.
Public Member Functions inherited from Geo_Metric_Base_3
Geo_Metric_Base_3 ()
virtual ~Geo_Metric_Base_3 ()
virtual void initialize (Vector_3< double > n[], int type)
Initialize a 3D Geometric Metric by nodal coords and element type.
virtual void initialize (Element_node_enumerator &ene)
Initialize a 3D Geometric Metric by Element_node_enumerator.
Public Member Functions inherited from Metric
Metric ()
virtual ~Metric ()
Additional Inherited Members
Protected Member Functions inherited from Geo_Metric_Base_3
void compute_angles (double &min, double &max) const
Compute min and max dihedral angles.
void compute_aspects (double &R, double &r, double &l) const
Compute circumradius, inradius, and shortest edge length.
Protected Attributes inherited from Geo_Metric_Base_3
std::vector< Vector_3< double > > v
int _type
const COM::Pane * _ene_pane
int _ene_i
Detailed Description
3D Max and Min Angle Metric Class
Definition at line 87 of file Geometric_Metrics_3.h.
Constructor & Destructor Documentation
Angle_Metric_3 () inline
Initialize a 3D Angle Metric.
Definition at line 91 of file Geometric_Metrics_3.h.
 {}
Member Function Documentation
void compute (double atts[]) const virtual
Calculate the metric value on this element.
Parameters
atts[] Computed value(s) placed here.
Implements Metric.
Definition at line 249 of file Geometric_Metrics_3.C.
Referenced by Rocmop::add_aspect_ratios(), Rocmop::check_all_elem_quality(), Rocmop::check_marked_elem_quality(), main(), Rocmop::obtain_extremal_dihedrals(), Rocmop::perturb_stationary(), Rocmop::print_extremal_dihedrals(), Rocmop::print_mquality(), Rocmop::print_quality(), and Rocmop::smooth_vol_mesq_ng().
{
     compute_angles(atts[0],atts[1]);
 }
double maxValue () const virtual
Get the maximum value for this metric.
Reimplemented from Geo_Metric_Base_3.
Definition at line 253 of file Geometric_Metrics_3.C.
Referenced by main().
{
 return 180.0;
 }
double minValue () const virtual
Get the minimum value for this metric.
Reimplemented from Geo_Metric_Base_3.
Definition at line 257 of file Geometric_Metrics_3.C.
Referenced by main().
{
 return 0.0;
 }
The documentation for this class was generated from the following files:
Geometric_Metrics_3.h
Geometric_Metrics_3.C