Rocstar: rflu_modpetscadmin Module Reference
rflu_modpetscadmin Module Reference
Public Member Functions
subroutine, public rflu_petsc_finalize (global)
subroutine, public rflu_petsc_init (global)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPETScAdmin.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 39 of file RFLU_ModPETScAdmin.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_petsc_finalize (type(t_global), pointer global)
Definition at line 90 of file RFLU_ModPETScAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_endflowsolver().
subroutine, public rflu_petsc_init (type(t_global), pointer global)
Definition at line 165 of file RFLU_ModPETScAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPETScAdmin.F90,v $ $Revision: 1.4 $' private
Definition at line 62 of file RFLU_ModPETScAdmin.F90.
The documentation for this module was generated from the following file:
RFLU_ModPETScAdmin.F90