Rocstar: Attribute Class Reference
Attribute Class Reference
An Attribute object is a data member of a window.
#include <Attribute.h>
Public Types
enum Copy_dir { COPY_IN, COPY_OUT }
typedef unsigned char Shorter_size
One byte unsighed int.
typedef unsigned int Size
Unsighed int.
Public Member Functions
void set_size (int nitems, int ngitems=0) throw (COM_exception)
Set the size of items and ghost items.
void * allocate (int strd, int cap, bool force) throw (COM_exception)
Allocate memory for the attribute.
int deallocate () throw (COM_exception)
Deallocate memory if it was allocated by allocate().
void copy_array (void *buf, int strd, int nitem, int offset=0, int direction=COPY_IN) throw (COM_exception)
void append_array (const void *from, int strd, int nitem) throw (COM_exception)
Identity
const std::string & name () const
Obtain the name of the attribute.
std::string fullname () const
Obtain the full name of the attribute including window name suitable for printing out error messages.
int id () const
Obtain the id (or index) of the attribute.
Attribute * parent ()
Parent attribute used by this object.
const Attribute * parent () const
Attribute * root ()
Root of use-inheritance.
const Attribute * root () const
Physical address
const void * pointer () const
Obtain a constant pointer to the physical address.
void * pointer () throw (COM_exception)
Obtain a modifiable pointer to the physical address.
const void * get_addr (int i, int j=0) const throw (COM_exception)
Obtain the address of the jth component of the ith item, where 0<=i<size_of_items.
void * get_addr (int i, int j=0) throw (COM_exception)
Protected Types
enum {
STATUS_NOT_INITIALIZED =0, STATUS_SET =1, STATUS_SET_CONST =2, STATUS_USE =3,
STATUS_ALLOCATED =4
}
Protected Member Functions
void set_pointer (void *p, int strd, int cap, int offset, bool is_const) throw (COM_exception)
Set the physical address of the attribute values.
void inherit (Attribute *a, bool clone, bool withghost, int depth=0) throw (COM_exception)
Inherit from parent. If depth>0, then the procedure is for the subcomponents.
Protected Attributes
Pane * _pane
Pointer to its owner pane.
Attribute * _parent
Parent attribute being used.
std::string _name
Name of the attribute.
int _id
Id field data.
Shorter_size _loc
Location.
int _ncomp
Number of components.
COM_Type _type
Base data type of the attribute.
std::string _unit
Unit of the attribute.
int _nitems
Size of total items. Default value is -1.
int _ngitems
Size of ghost items.
int _gap
Gap between the IDs of real and ghost items.
Shorter_size _status
Indicating whether it has been initialized.
void * _ptr
Physical address of the attribute.
int _strd
Stride.
int _nbytes_strd
Number of bytes of the stride.
int _cap
Capacity.
Static Protected Attributes
Keywords
static const char * _keywords [COM_NUM_KEYWORDS]
List of keywords.
static const char _keylocs [COM_NUM_KEYWORDS]
Default locations.
static const COM_Type _keytypes [COM_NUM_KEYWORDS]
Default data types.
static const int _keysizes [COM_NUM_KEYWORDS]
Default sizes.
Private Member Functions
Attribute (const Attribute &a)
Disable copy constructor and copy operator.
Attribute & operator= (const Attribute &)
Constructors and destructors
Attribute ()
Default constructor.
Attribute (Pane *pane, const std::string &name, int id, Shorter_size loc, int type, const int ncomp, const std::string &unit)
Create an attribute with name n in window w.
Attribute (Pane *pane, Attribute *parent, const std::string &name, int id)
Inherit an attribute from another.
~Attribute ()
Destructors.
Attribute (Pane *pane, int i)
Constructor for keywords. The default nitems for keywords is 0.
Access methods
const Pane * pane () const
Obtain a constant pointer to the owner pane of the attribute.
Pane * pane ()
Obtain a modifiable pointer to the owner pane of the attribute.
const Window * window () const
Obtain a constant pointer to the parent window of the attribute.
Window * window ()
Obtain a modifiable pointer to the parent window of the attribute.
Shorter_size location () const
Obtain the location of the attribute.
bool is_windowed () const
Checks whether the attribute is associated with the window.
bool is_panel () const
Checks whether the attribute is associated with a pane.
bool is_elemental () const
Checks whether the attribute is associated with an element.
bool is_nodal () const
Checks whether the attribute is associated with a node.
COM_Type data_type () const
Obtain the data type of each component of the attribute.
const std::string & unit () const
Obtain the unit of the attribute.
int size_of_components () const
Obtain the number of components in the attribute.
int size_of_items () const
Obtain the number of items in the attribute.
int maxsize_of_items () const
Obtain the maximum allowed number of items in the attribute.
int size_of_ghost_items () const
Obtain the number of ghost items in the attribute.
int maxsize_of_ghost_items () const
Obtain the maximum allowed number of items in the attribute.
int size_of_real_items () const
Obtain the number of real items in the attribute.
int maxsize_of_real_items () const
Obtain the maximum allowed number of real items in the attribute.
bool empty () const
Check whether the number of items of the attribute is zero.
int capacity () const
Obtain the capacity of the array.
int stride () const
Obtain the stride of the attribute in base datatype.
int stride_in_bytes () const
Obtain the stride of the attribute in bytes.
int status () const
Obtain the status of the attribute.
bool initialized () const
Returns whether the array for the attribute has been set or allocated.
bool size_set () const
Returns whether the size for the attribute has been set.
bool allocated () const
Returns whether the array for the attribute has been set or allocated.
bool is_const () const
Returns whether the array is set to be read-only.
bool is_staggered () const
Check how the attribute values are organized.
static int get_sizeof (COM_Type type, int count=1)
static bool compatible_types (COM_Type t1, COM_Type t2)
static bool is_digit (char c)
Detailed Description
An Attribute object is a data member of a window.
It can be associated with a window, a pane, nodes, or elements. An attribute can be a vector of length size_of_items() with size_of_components() components.
Definition at line 51 of file Attribute.h.
Member Typedef Documentation
typedef unsigned char Shorter_size
One byte unsighed int.
Definition at line 53 of file Attribute.h.
typedef unsigned int Size
Unsighed int.
Definition at line 54 of file Attribute.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
STATUS_NOT_INITIALIZED
STATUS_SET
STATUS_SET_CONST
STATUS_USE
STATUS_ALLOCATED
Definition at line 316 of file Attribute.h.
        { STATUS_NOT_INITIALIZED=0, STATUS_SET=1, STATUS_SET_CONST=2,
          STATUS_USE=3, STATUS_ALLOCATED=4 };
enum Copy_dir
Enumerator
COPY_IN
COPY_OUT
Definition at line 280 of file Attribute.h.
 { COPY_IN, COPY_OUT };
Constructor & Destructor Documentation
Attribute () inline
Default constructor.
Definition at line 60 of file Attribute.h.
Referenced by Attribute().
     : _pane(NULL), _parent(NULL), _id(-1), _loc(0), _ncomp(0), _type(0),
       _nitems(-1), _ngitems(0), _gap(0), _status(STATUS_NOT_INITIALIZED),
       _ptr(NULL), _strd(0), _nbytes_strd(0), _cap(0) {}
Attribute (Pane * pane, int i) inline protected
Constructor for keywords. The default nitems for keywords is 0.
Definition at line 67 of file Attribute.h.
     : _pane(pane), _parent(NULL), _name( _keywords[i]), _id(i),
       _loc(_keylocs[i]), _ncomp(_keysizes[i]), _type(_keytypes[i]),
       _unit( i<=COM_NC3?"m":""), _nitems(0), _ngitems(0), _gap(0),
       _status(STATUS_NOT_INITIALIZED), _ptr(NULL), _strd(0),
       _nbytes_strd(0), _cap(0) {}
Attribute (Pane * pane, const std::string & name, int id, Shorter_size loc, int type, const int ncomp, const std::string & unit) inline
Create an attribute with name n in window w.
Parameters
pane pointer to its owner pane object.
name attribute name.
id attribute index.
loc location ('w', 'p', 'n', or 'e').
type base data type.
ncomp number of components.
unit unit of the attribute.
Definition at line 83 of file Attribute.h.
     : _pane(pane), _parent(NULL), _name( name), _id(id), _loc(loc),
       _ncomp(ncomp), _type(type), _unit(unit), _nitems(-1), _ngitems(0),
       _gap(0), _status(STATUS_NOT_INITIALIZED), _ptr(0), _strd(0),
       _nbytes_strd(0), _cap(0) {}
Attribute (Pane * pane, Attribute * parent, const std::string & name, int id)
Inherit an attribute from another.
Parameters
pane pointer to its owner pane object.
parent parent attribute (for supporting inheritance).
name attribute name.
id attribute index.
Definition at line 63 of file Attribute.C.
References _cap, _loc, _name, _nbytes_strd, _ncomp, _ngitems, _nitems, _parent, _status, _strd, _type, _unit, append_frame, Attribute(), COM_ERR_ATTRIBUTE_NOTEXIST, fullname(), name(), root(), and STATUS_NOT_INITIALIZED.
   : _pane( pane), _id(id), _gap(0), _status(0)
 {
   if ( !parent)
     throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST,
                          append_frame(fullname(), Attribute::Attribute));
   _name = name.size()?name:parent->name();
   _parent = NULL; _status = STATUS_NOT_INITIALIZED;
   Attribute *root = parent->root();
   _loc=root->_loc; _ncomp=root->_ncomp; _type=root->_type;
   _cap = root->_cap; _strd = root->_strd; _nbytes_strd = root->_nbytes_strd;
   _unit=root->_unit; _nitems = root->_nitems; _ngitems = root->_ngitems;
 }
~Attribute () inline
Destructors.
Definition at line 101 of file Attribute.h.
References _cap, _id, _loc, _nbytes_strd, _ncomp, _ngitems, _nitems, _pane, _parent, _ptr, _status, _strd, _type, deallocate(), and STATUS_NOT_INITIALIZED.
                {
     if (!_parent) deallocate();
     _pane=NULL; _parent=NULL; _id=-1; _loc=0; _ncomp=0; _type=0;
     _nitems=-1, _ngitems=0; _status=STATUS_NOT_INITIALIZED; _ptr=NULL;
     _strd=0; _nbytes_strd=0; _cap=0;
   }
Attribute (const Attribute & a) private
Disable copy constructor and copy operator.
Member Function Documentation
void * allocate (int strd, int cap, bool force) throw (COM_exception)
Allocate memory for the attribute.
The attribute must be a root if the attribute is to be allocated. If from is not NULL, copy its value to the newly allocated array.
Definition at line 345 of file Attribute.C.
References _cap, _ptr, _status, _strd, append_frame, cap, CATCHBADALLOC_APPEND, CATCHEXP_APPEND, COM_ERR_INVALID_CAPACITY, COM_ERR_INVALID_STRIDE, COM_ERR_OUT_OF_MEMORY, COM_ERR_RESIZE, copy_array(), get_sizeof(), i, max(), min(), set_pointer(), and strd.
Referenced by Connectivity::allocate(), inherit(), Pane::reinit_attr(), and Connectivity::set_pointer().
 {
   int nitems=size_of_items(), ncomp=size_of_components();
   if ( strd!=1 && strd<ncomp)
     throw COM_exception( COM_ERR_INVALID_STRIDE,
                          append_frame( fullname(), Attribute::allocate));
   if ( cap<nitems)
     throw COM_exception( COM_ERR_INVALID_CAPACITY,
                          append_frame( fullname(), Attribute::allocate));
   if ( !force && (_parent || _status==STATUS_SET || _status==STATUS_SET_CONST))
     throw COM_exception( COM_ERR_RESIZE,
                          append_frame( fullname(), Attribute::allocate));
   try {
     int type = data_type();
     // Go ahead to allocate for the attribute if it was not initialized
     // and not inherited or it is forced to overwrite previously set address.
     int nold, old_cap;
     if ( _status == STATUS_NOT_INITIALIZED || force)
     { nold = -1; old_cap = 0; }
     else {
       old_cap = _cap;
       nold = old_cap*get_sizeof(type, std::max(_strd,ncomp));
     }
     int nnew = cap*get_sizeof(type, std::max(strd,ncomp));
     // if the capacity is not big enough or the stride is changed.
     if ( nold < nnew || strd != _strd) {
       // Deallocate the old array and copy values to the new one
       char *old_ptr = (char*)_ptr;
       int  old_strd = _strd;
       if ( nnew) {
         _ptr = new char[nnew];
         std::fill_n( (char*)_ptr, nnew, 0);
         if (_ptr==NULL)
           throw COM_exception( COM_ERR_OUT_OF_MEMORY,
                                append_frame( fullname(), Attribute::allocate));
       }
       else _ptr = NULL;
       _cap = cap; _strd = strd; _nbytes_strd = get_sizeof( data_type(), strd);
       // Copy data from old array to the new.
       if ( old_cap && _ptr) {
         if ( _ncomp ==1 || _id<0) // Copy for connectivity and for scalars
           copy_array( old_ptr, old_strd, std::min(old_cap,_cap));
         else { // loop through individual components
           for ( int i=1; i<=ncomp; ++i) {
             Attribute *ai = this+i;
             char *old_ptr_i = (char*)ai->_ptr; old_strd=ai->_strd;
             old_cap = ai->_cap;
             ai->set_pointer( _ptr, _strd, _cap, i-1, false);
             ai->copy_array( old_ptr_i, old_strd, std::min(old_cap,_cap));
             // Delete the individual components
             if ( ai->_status == STATUS_ALLOCATED && old_ptr_i)
               delete [] old_ptr_i;
           }
         }
       }
       else {
         if ( _ncomp >1 && _id>=0) for ( int i=1; i<=ncomp; ++i) {
           this[i].set_pointer( _ptr, _strd, _cap, i-1, false);
         }
       }
       // Delete the old array for all components
       if ( _status == STATUS_ALLOCATED && old_ptr) delete [] old_ptr;
       _status = STATUS_ALLOCATED;
       if ( _parent) _parent=NULL; // Break inheritance.
     }
   }
   CATCHEXP_APPEND(Attribute::allocate) CATCHBADALLOC_APPEND(Attribute::allocate);
   return _ptr;
 }
bool allocated () const inline
Returns whether the array for the attribute has been set or allocated.
Definition at line 250 of file Attribute.h.
References _status, and STATUS_ALLOCATED.
 { return _status==STATUS_ALLOCATED; }
void append_array (const void * from, int strd, int nitem) throw (COM_exception)
Definition at line 334 of file Attribute.C.
References append_frame, COM_ERR_APPEND_ARRAY, offset(), and strd.
Referenced by Window::append_array().
 {
   if ( !is_panel() && !is_windowed() || size_of_ghost_items())
     throw COM_exception( COM_ERR_APPEND_ARRAY,
                          append_frame(fullname(), Attribute::append_array));
   int offset = size_of_items();
   copy_array( const_cast<void*>(from), strd, nitem, offset);
   set_size( offset+nitem);
 }
int capacity () const inline
Obtain the capacity of the array.
Definition at line 230 of file Attribute.h.
References _cap, _status, and root().
Referenced by Pane::init_done(), maxsize_of_items(), and Pane::reinit_attr().
 { return _status?_cap:root()->_cap; }
bool compatible_types (COM_Type t1, COM_Type t2) static
Definition at line 531 of file Attribute.C.
References COM_BYTE, COM_CHAR, COM_CHARACTER, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_FLOAT, COM_INT, COM_INTEGER, COM_LONG, COM_REAL, COM_SHORT, COM_UNSIGNED, COM_UNSIGNED_CHAR, COM_UNSIGNED_LONG, COM_UNSIGNED_SHORT, and get_sizeof().
Referenced by Pane::inherit().
{
   if (t1 == t2) return true;
   if ( Attribute::get_sizeof( t1, 1) != Attribute::get_sizeof( t2, 1))
     return false;
   switch( t1) {
   case COM_CHAR:
   case COM_CHARACTER:
   case COM_UNSIGNED_CHAR:
   case COM_BYTE:
   case COM_SHORT:
   case COM_UNSIGNED_SHORT:
     return true; // size matching
   case COM_INT:
   case COM_INTEGER:
   case COM_UNSIGNED:
   case COM_LONG:
   case COM_UNSIGNED_LONG:
     return t2 == COM_INT || t2 == COM_INTEGER || t2 == COM_UNSIGNED ||
       t2 == COM_UNSIGNED_LONG || t2 == COM_LONG;
   case COM_FLOAT:
   case COM_REAL:
     return t2 == COM_FLOAT || t2 == COM_REAL;
   case COM_DOUBLE:
   case COM_DOUBLE_PRECISION:
     return t2 == COM_DOUBLE_PRECISION || t2 == COM_DOUBLE;
   default:
     return false;
   }
 }
void copy_array (void * buf, int strd, int nitem, int offset = 0, int direction = COPY_IN) throw (COM_exception)
Definition at line 249 of file Attribute.C.
References append_frame, COM_ERR_ATTRIBUTE_CONST, COM_ERR_INVALID_SIZE, COM_ERR_INVALID_STRIDE, COM_ERR_NULL_POINTER, get_sizeof(), i, j, min(), ni, offset(), and strd.
Referenced by allocate(), and Pane::inherit().
 {
   if (direction==COPY_IN) {
     if ( is_const())
       throw COM_exception( COM_ERR_ATTRIBUTE_CONST,
                            append_frame( fullname(), Attribute::copy_array));
     if ( _status==STATUS_NOT_INITIALIZED && _parent)
     { _cap = root()->_cap; _strd = root()->_strd; _nbytes_strd=root()->_nbytes_strd; }
   }
   int nitems=size_of_items(), ncomp=size_of_components();
   if ( n ==0) { if ( direction==COPY_IN) return; else n = nitems; }
   if ( strd==0) strd=ncomp;
   if ( !buf && n)
     throw COM_exception( COM_ERR_NULL_POINTER,
                          append_frame( fullname(), Attribute::copy_array));
   // strd must be either 1 or at least as large as _strd
   if ( strd!=1 && strd<ncomp)
     throw COM_exception( COM_ERR_INVALID_STRIDE,
                          append_frame( fullname(), Attribute::copy_array));
   if ( offset<0 || n+offset>_cap)
     throw COM_exception( COM_ERR_INVALID_SIZE,
                          append_frame( fullname(), Attribute::copy_array));
   int basesize = get_sizeof( data_type());
   char *ptr0 = (char*)pointer();
   if (offset) ptr0 += offset*ncomp*basesize;
   if ( _strd == strd && (_strd == ncomp || n==_cap && strd==1) ) {
     // two arrays have the same layout
     if ( direction == COPY_IN)
       std::memcpy( ptr0, buf, n*ncomp*basesize);
     else
       std::memcpy( buf, ptr0, n*ncomp*basesize);
   }
   else if ( _strd>1 && strd>1) {
     // the components are stored contiguously in both arrays
     char *p_buf=(char*)buf;
     char *p_att = ptr0;
     int strd_att_in_bytes = _nbytes_strd;
     int strd_buf_in_bytes =  strd*basesize;
     int vecsize = ncomp*basesize;
     for ( int i=0, ni=std::min(n, nitems); i<ni; ++i) {
       if ( direction == COPY_IN)
         std::memcpy( p_att, p_buf, vecsize);
       else
         std::memcpy( p_buf, p_att, vecsize);
       p_buf += strd_buf_in_bytes;
       p_att += strd_att_in_bytes;
     }
   }
   else {
     // layouts of two arrays are very different from each
     char *p_buf=(char*)buf;
     char *p_att = ptr0;
     int strd_att_in_bytes = _nbytes_strd;
     int strd_buf_in_bytes =  strd*basesize;
     int step_att_in_bytes= (_strd==1?_cap:1)*basesize;
     int step_buf_in_bytes = (strd==1?n:1)*basesize;
     for ( int i=0, ni=std::min(n, nitems); i<ni; ++i) {
       for ( int j=0, offset_buf=0, offset_att=0; j<ncomp; ++j) {
         if ( direction == COPY_IN)
           std::memcpy( p_att+offset_att, p_buf+offset_buf, basesize);
         else
           std::memcpy( p_buf+offset_buf, p_att+offset_att, basesize);
         offset_buf += step_buf_in_bytes;
         offset_att += step_att_in_bytes;
       }
       p_buf += strd_buf_in_bytes;
       p_att += strd_att_in_bytes;
     }
   }
 }
COM_Type data_type () const inline
Obtain the data type of each component of the attribute.
Definition at line 197 of file Attribute.h.
References _type.
Referenced by Rocblas::acos(), Rocblas::add(), Rocblas::add_scalar(), Rocblas::axpy(), Rocblas::axpy_gen(), Rocblas::axpy_scalar(), Rocblas::calc(), Rocblas::calcDot(), Roccom_base::call_function(), Rocblas::copy(), Rocblas::copy_scalar(), Rocblas::div(), Rocblas::div_scalar(), Rocblas::dot_MPI(), Rocblas::dot_scalar_MPI(), Rocblas::gen2arg(), Window::get_attribute(), Roccom_base::get_f90pointer(), Pane::inherit(), Rocblas::limit1(), Rocblas::maxof_scalar(), Rocblas::mul(), Rocblas::mul_scalar(), Rocblas::neg(), Rocblas::rand(), Rocblas::rand_scalar(), Rocblas::reduce_MPI(), Rocblas::reduce_scalar_MPI(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), Roccom_base::set_f90pointer(), Roccom_base::set_member_function_helper(), Rocblas::sqrt(), Rocblas::sub(), Rocblas::sub_scalar(), Rocblas::swap(), and write_attr_CGNS().
 { return _type; }
int deallocate () throw (COM_exception)
Deallocate memory if it was allocated by allocate().
Return 0 if deallocation is successful.
Definition at line 473 of file Attribute.C.
References _id, _ncomp, _ptr, _status, CATCHEXP_APPEND, i, STATUS_ALLOCATED, and STATUS_NOT_INITIALIZED.
Referenced by Pane::reinit_attr(), and ~Attribute().
{
   try {
     // Deallocate attribute and set individual components to not initialized.
     if ( _status != STATUS_ALLOCATED) return -1; // failed
     _status = STATUS_NOT_INITIALIZED;
     if ( _ptr) { delete [] (char*)_ptr; _ptr = NULL; }
     if ( _ncomp>1 && _id>=0)
       for ( int i=1; i<=_ncomp; ++i)
         { this[i]._ptr = NULL; this[i]._status = STATUS_NOT_INITIALIZED; }
   }
   CATCHEXP_APPEND(Attribute::deallocate);
   return 0;
 }
bool empty () const inline
Check whether the number of items of the attribute is zero.
Definition at line 227 of file Attribute.h.
References _nitems, and root().
Referenced by Roccom_base::clone_attribute(), Roccom_base::copy_attribute(), and Roccom_base::use_attribute().
 { return root()->_nitems<= 0; }
std::string fullname () const
Obtain the full name of the attribute including window name suitable for printing out error messages.
Definition at line 82 of file Attribute.C.
References Window::name(), name(), and window().
Referenced by Rocblas::acos(), Rocblas::add(), Attribute(), Rocblas::axpy(), Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocblas::copy(), Rocblas::div(), Rocblas::dot_MPI(), Rocblas::gen2arg(), Pane::inherit(), Pane::init_done(), Rocblas::limit1(), Rocblas::mul(), Rocblas::neg(), Rocblas::rand(), Rocblas::reduce_MPI(), Rocblas::reduce_scalar_MPI(), Pane::reinit_attr(), Rocblas::sqrt(), and Rocblas::sub().
 { return window()->name()+"."+name(); }
const void * get_addr (int i, int j = 0) const throw (COM_exception)
Obtain the address of the jth component of the ith item, where 0<=i<size_of_items.
This function is recursive and relatively expensive, and hence should be used only for performance-insenstive tasks.
Definition at line 85 of file Attribute.C.
References append_frame, COM_ERR_INDEX_OUT_OF_BOUNDS, COM_ERR_INVALID_DIMENSION, i, and j.
Referenced by Connectivity::get_addr().
{
   if ( _parent) return root()->get_addr( i,j);
   if ( j>=_ncomp) throw COM_exception( COM_ERR_INVALID_DIMENSION);
   if ( _ncomp>1) return this[j+1].get_addr( i);
   // Check that i is between 0 and size_of_items-1.
   if ( i<0 || i>=size_of_items())
     throw COM_exception( COM_ERR_INDEX_OUT_OF_BOUNDS, append_frame
                          ( fullname(), Attribute::get_addr));
   return  ((char*)_ptr)+i*_nbytes_strd;
 }
void* get_addr (int i, int j = 0) throw (COM_exception) inline
Definition at line 162 of file Attribute.h.
References COM_ERR_ATTRIBUTE_CONST, is_const(), and j.
{
     if ( is_const()) throw COM_exception( COM_ERR_ATTRIBUTE_CONST);
     return (void*)(((const Attribute*)this)->get_addr(i,j));
   }
int get_sizeof (COM_Type type, int count = 1) static
Definition at line 488 of file Attribute.C.
References COM_assertion, COM_BOOL, COM_BYTE, COM_CHAR, COM_CHARACTER, COM_COMPLEX, COM_DOUBLE, COM_DOUBLE_COMPLEX, COM_DOUBLE_PRECISION, COM_F90POINTER, COM_FLOAT, COM_INT, COM_INTEGER, COM_LOGICAL, COM_LONG, COM_LONG_DOUBLE, COM_METADATA, COM_MPI_COMMC, COM_MPI_COMMF, COM_OBJECT, COM_REAL, COM_SHORT, COM_STRING, COM_UNSIGNED, COM_UNSIGNED_CHAR, COM_UNSIGNED_LONG, COM_UNSIGNED_SHORT, and COM_VOID.
Referenced by compatible_types(), Roccom_base::get_f90pntoffsets(), and Roccom_base::get_sizeof().
{
   switch (type) {
   case COM_CHAR:
   case COM_UNSIGNED_CHAR:
   case COM_BYTE:
   case COM_BOOL:
   case COM_CHARACTER:      return count;
   case COM_UNSIGNED_SHORT:
   case COM_SHORT:          return count*sizeof(short);
   case COM_INT:
   case COM_INTEGER:
   case COM_LOGICAL:
   case COM_UNSIGNED:       return count*sizeof(int);
   case COM_UNSIGNED_LONG:
   case COM_LONG:           return count*sizeof(long int);
   case COM_FLOAT:
   case COM_REAL:           return count*sizeof(float);
   case COM_DOUBLE_PRECISION:
   case COM_DOUBLE:         return count*sizeof(double);
   case COM_LONG_DOUBLE:    return count*sizeof(long double);
   case COM_COMPLEX:        return count*2*sizeof(float);
   case COM_DOUBLE_COMPLEX: return count*2*sizeof(double);
   case COM_MPI_COMMC:      return count*sizeof(MPI_Comm);
   case COM_MPI_COMMF:      return count*sizeof(int);
   case COM_F90POINTER:     return count*64;
   case COM_METADATA:
   case COM_VOID:           return sizeof(void*)*count;
   case COM_OBJECT:         return sizeof(COM_Object*)*count;
   case COM_STRING:         return count;
   default:  COM_assertion(false); return -1;
   }
 }
int id () const inline
Obtain the id (or index) of the attribute.
Definition at line 120 of file Attribute.h.
References _id.
Referenced by Pane::attribute(), Window::attribute(), Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocblas::copy(), Window::delete_attribute(), Rocblas::gen2arg(), Pane_ghost_connectivity::get_ents_to_send(), Pane_ghost_connectivity::get_node_total_order(), Pane::inherit(), Rocblas::rand(), Window::set_size(), Rocblas::swap(), and write_attr_CGNS().
 { return _id; }
void inherit (Attribute * a, bool clone, bool withghost, int depth = 0) throw (COM_exception) protected
Inherit from parent. If depth>0, then the procedure is for the subcomponents.
Definition at line 426 of file Attribute.C.
References _cap, _loc, _ncomp, _strd, _type, _unit, allocate(), CATCHBADALLOC_APPEND, CATCHEXP_APPEND, get_sizeof(), i, and root().
Referenced by Connectivity::inherit(), Window::inherit(), Pane::inherit(), and MarkerParticles_3::multiply_nodal_normals().
 {
   Attribute *root = parent->root();
   _loc=root->_loc; _ncomp=root->_ncomp; _type=root->_type;
   _cap = root->_cap; _strd = root->_strd;
   _nbytes_strd = get_sizeof( _type, _strd); _unit=root->_unit;
   if ( !clone) {
     _parent = parent;
     // Inherit individual components
     if ( _ncomp>1 && _id>=0) try {
       for ( int i=1; i<=_ncomp; ++i) {
         this[i].inherit( parent+i, clone, withghost, 1);
       }
     } CATCHEXP_APPEND(Attribute::inherit);
   }
   else {
     _parent = NULL;
     // Set size
     if ( withghost) {
       _nitems = parent->size_of_items();
       _ngitems = parent->size_of_ghost_items();
     }
     else {
       _nitems = parent->size_of_real_items();
       _ngitems = 0;
     }
     if ( depth>0) return;
     // Allocate and copy from parent if parent was initialized.
     try {
       if (parent->initialized()) allocate( _ncomp, _cap, true);
       else deallocate();
     }  CATCHEXP_APPEND(Attribute::inherit) CATCHBADALLOC_APPEND(Attribute::allocate);
     // Set pointer for individual components if allocated.
     if ( _ncomp>1 && _id>=0) try {
       for ( int i=1; i<=_ncomp; ++i) {
         this[i].inherit( parent+i, clone, withghost, 1);
         if (allocated())
           this[i].set_pointer( _ptr, _strd, _cap, i-1, false);
       }
     } CATCHEXP_APPEND(Attribute::inherit);
   }
 }
bool initialized () const inline
Returns whether the array for the attribute has been set or allocated.
Definition at line 244 of file Attribute.h.
References _status, and root().
Referenced by Pane::init_done().
 { return _status||root()->_status; }
bool is_const () const inline
Returns whether the array is set to be read-only.
Definition at line 253 of file Attribute.h.
References _status, root(), and STATUS_SET_CONST.
Referenced by Roccom_base::call_function(), get_addr(), Connectivity::is_const(), and pointer().
 { return root()->_status==STATUS_SET_CONST; }
static bool is_digit (char c) inline static
Definition at line 264 of file Attribute.h.
Referenced by Window::attribute(), Window::delete_attribute(), Window::new_attribute(), Pane::reinit_attr(), and Window::Window().
 { return c>='0' && c<='9'; }
bool is_elemental () const inline
Checks whether the attribute is associated with an element.
Definition at line 192 of file Attribute.h.
References _loc.
Referenced by FaceOffset_3::obtain_face_offset(), and Element_vectors_k_const< Value >::set().
 { return _loc == 'e'; }
bool is_nodal () const inline
Checks whether the attribute is associated with a node.
Definition at line 194 of file Attribute.h.
References _loc.
Referenced by FaceOffset_3::obtain_face_offset(), and Element_node_vectors_k_const< Value >::set().
 { return _loc == 'n'; }
bool is_panel () const inline
Checks whether the attribute is associated with a pane.
Definition at line 190 of file Attribute.h.
References _loc.
 { return _loc == 'p'; }
bool is_staggered () const inline
Check how the attribute values are organized.
It returns true if the components of the attribute associated with
Definition at line 258 of file Attribute.h.
References size_of_components(), and stride().
 { return stride()!=size_of_components(); }
bool is_windowed () const inline
Checks whether the attribute is associated with the window.
Definition at line 188 of file Attribute.h.
References _loc.
Referenced by Rocblas::acos(), Rocblas::axpy(), Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcChoose(), Rocblas::calcDot(), Rocblas::copy_helper(), Rocblas::dot_MPI(), Rocblas::gen2arg(), Pane::inherit(), Rocblas::neg(), Pane::Pane(), Rocblas::rand(), Rocblas::reduce_MPI(), Pane::reinit_attr(), Window::set_size(), and Rocblas::sqrt().
 { return _loc == 'w'; }
Shorter_size location () const inline
Obtain the location of the attribute.
It is encoded as follows: 'w' for windowed attribute, 'p' for panal attribute, 'n' for nodal attribute, and 'e' for elemental attribute.
Definition at line 186 of file Attribute.h.
References _loc.
Referenced by Window::get_attribute(), Roccom_base::get_f90pointer(), Pane::inherit(), Roccom_base::set_f90pointer(), and write_attr_CGNS().
 { return _loc; }
int maxsize_of_ghost_items () const
Obtain the maximum allowed number of items in the attribute.
Reserved for Roccom3.1
Definition at line 153 of file Attribute.C.
References _cap, _id, _loc, _ngitems, _nitems, _pane, _parent, Pane::attribute(), COM_CONN, COM_NC, Pane::ignore_ghost(), and maxsize_of_ghost_items().
Referenced by maxsize_of_ghost_items().
 {
   if ( _pane->ignore_ghost())
     return 0;
   else if ( _loc == 'n' && _id != COM_NC)
     return _pane->attribute(COM_NC)->maxsize_of_ghost_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->attribute(COM_CONN)->maxsize_of_ghost_items();
   else if ( _parent)
     return _parent->maxsize_of_ghost_items();
   else
     return _nitems<=0 ? 0 :_ngitems + (_cap-_nitems);
 }
int maxsize_of_items () const
Obtain the maximum allowed number of items in the attribute.
Reserved for Roccom3.1
Definition at line 125 of file Attribute.C.
References _id, _loc, _pane, _parent, Pane::attribute(), capacity(), COM_CONN, COM_NC, Pane::ignore_ghost(), maxsize_of_items(), and maxsize_of_real_items().
Referenced by maxsize_of_items().
 {
   if (_pane->ignore_ghost())
     return maxsize_of_real_items();
   if ( _loc == 'n' && _id != COM_NC)
     return _pane->attribute(COM_NC)->maxsize_of_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->attribute(COM_CONN)->maxsize_of_items();
   else if ( _parent)
     return _parent->maxsize_of_items();
   else
     return  capacity();
 }
int maxsize_of_real_items () const
Obtain the maximum allowed number of real items in the attribute.
Reserved for Roccom3.1
Definition at line 179 of file Attribute.C.
References _id, _loc, _ngitems, _nitems, _pane, _parent, Pane::attribute(), COM_CONN, COM_NC, and maxsize_of_real_items().
Referenced by maxsize_of_items(), and maxsize_of_real_items().
 {
   if ( _loc == 'n' && _id != COM_NC)
     return _pane->attribute(COM_NC)->maxsize_of_real_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->attribute(COM_CONN)->maxsize_of_real_items();
   else if ( _parent)
     return _parent->maxsize_of_real_items();
   else
     return _nitems<=0 ? 0 : _nitems - _ngitems;
 }
const std::string& name () const inline
Obtain the name of the attribute.
Definition at line 113 of file Attribute.h.
Referenced by Attribute(), Roccom_base::call_function(), Roccom_base::copy_attribute(), Window::delete_attribute(), fullname(), inrt_setmaterial(), io_pane_attribute(), Pane::new_attribute(), Pane::reinit_attr(), and Window::Window().
 { return _name; }
Attribute& operator= (const Attribute &) private
const Pane* pane () const inline
Obtain a constant pointer to the owner pane of the attribute.
Definition at line 172 of file Attribute.h.
Referenced by Pane::attributes(), Pane::delete_attribute(), Rocblas::gen2arg(), Pane::inherit(), Pane::init_done(), Pane::Pane(), Pane::reinit_attr(), rocfracsubinterface::rocfracinterfaceinitial(), Element_node_vectors_k_const< Value >::set(), and Element_vectors_k_const< Value >::set().
 { return _pane; }
Pane* pane () inline
Obtain a modifiable pointer to the owner pane of the attribute.
Definition at line 174 of file Attribute.h.
References _pane.
 { return _pane; }
Attribute* parent () inline
Parent attribute used by this object.
It determines the the meta-data of the attribute. If the array of this attribute is not set, then this attribute also uses the pointer of its parant.
Definition at line 125 of file Attribute.h.
References _parent.
 { return _parent;  }
const Attribute* parent () const inline
Definition at line 126 of file Attribute.h.
References _parent.
 { return _parent; }
const void* pointer () const inline
Obtain a constant pointer to the physical address.
Definition at line 150 of file Attribute.h.
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Roccom_base::call_function(), Rocblas::gen2arg(), Pane_ghost_connectivity::get_cpanes(), Pane_ghost_connectivity::get_ents_to_send(), Roccom_base::get_f90pointer(), Pane_ghost_connectivity::get_node_total_order(), Window::inherit(), Pane::inherit(), io_pane_attribute(), Connectivity::pointer(), Rocblas::reduce_MPI(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), Roccom_base::set_f90pointer(), and write_attr_CGNS().
 { return _status?_ptr:root()->_ptr; }
void* pointer () throw (COM_exception) inline
Obtain a modifiable pointer to the physical address.
Definition at line 152 of file Attribute.h.
References _ptr, _status, COM_ERR_ATTRIBUTE_CONST, is_const(), and root().
{
     if ( is_const()) throw COM_exception( COM_ERR_ATTRIBUTE_CONST);
     return _status?_ptr:root()->_ptr;
   }
Attribute* root () inline
Root of use-inheritance.
The basic properties of the attribute (location, data type, number of components, and unit) are copied from the root during inheritance and hence later changes in the root (by renewing the root) will not be reflected in sub-attribute. Other types of information (sizes, pointer, stride, and capacity) always use those of the root attribute.
Definition at line 134 of file Attribute.h.
References _parent.
Referenced by Attribute(), capacity(), empty(), inherit(), initialized(), is_const(), pointer(), Connectivity::root(), stride(), and stride_in_bytes().
                      {
     Attribute *a=this;
     while ( a->_parent) a=a->_parent;
     return a;
   }
const Attribute* root () const inline
Definition at line 139 of file Attribute.h.
References _parent.
{
     const Attribute *a=this;
     while ( a->_parent) a=a->_parent;
     return a;
   }
void set_pointer (void * p, int strd, int cap, int offset, bool is_const) throw (COM_exception) protected
Set the physical address of the attribute values.
Definition at line 208 of file Attribute.C.
References append_frame, cap, COM_ERR_INVALID_CAPACITY, COM_ERR_INVALID_STRIDE, get_sizeof(), i, offset(), and strd.
Referenced by allocate(), and Connectivity::set_pointer().
 {
   int nitems=size_of_items(), ncomp=size_of_components();
   // Check whether received a local variable
   // const long int stackSize = 2097152; // 2MB
   // long int dist = std::abs(((long int)p) - (long int)(&nitems));
   // if ( p && dist <= stackSize)
   //   throw COM_exception( COM_ERR_INVALID_ADDR,
   //                     append_frame( fullname(), Attribute::set_pointer));
   if ( p && strd!=1 && strd<ncomp)
     throw COM_exception( COM_ERR_INVALID_STRIDE,
                          append_frame( fullname(), Attribute::set_pointer));
   if ( p && cap<nitems)
     throw COM_exception( COM_ERR_INVALID_CAPACITY,
                          append_frame( fullname(), Attribute::set_pointer));
   _cap = cap;
   _strd = strd;
   int basesize = get_sizeof( data_type(), 1);
   _nbytes_strd = basesize*strd;
   if ( _status == STATUS_ALLOCATED) deallocate();
   if ( p && offset) {
     if ( strd==1)
       _ptr = ((char*)p) + (offset*cap)*_nbytes_strd;
     else // Staggerred
       _ptr = ((char*)p) + offset*basesize;
   }
   else
     _ptr = p;
   _status = is_const?STATUS_SET_CONST:STATUS_SET;
   if ( ncomp >1 && _id>=0) for ( int i=1; i<=ncomp; ++i) {
     this[i].set_pointer( _ptr, _strd, _cap, i-1, is_const);
   }
 }
void set_size (int nitems, int ngitems = 0) throw (COM_exception)
Set the size of items and ghost items.
Can be changed only if the attribute is a root.
Definition at line 191 of file Attribute.C.
References append_frame, COM_assertion, COM_CONN, COM_ERR_CHANGE_INHERITED, COM_NC, and i.
Referenced by Window::append_array(), Pane::reinit_attr(), and Connectivity::set_pointer().
 {
   if ( _parent)
     throw COM_exception( COM_ERR_CHANGE_INHERITED,
                          append_frame( fullname(), Attribute::set_size));
   COM_assertion( (_loc!='n'||_id==COM_NC) && (_loc!='e'||_id==COM_CONN));
   _nitems = nitems; _ngitems = ngitems;
   if ( _ncomp>1) {
     // Set sizes for each individial component
     for ( int i=1; i<=_ncomp; ++i) {
       this[i]._nitems = nitems; this[i]._ngitems = ngitems;
     }
   }
 }
int size_of_components () const inline
Obtain the number of components in the attribute.
Definition at line 203 of file Attribute.h.
References _ncomp.
Referenced by Rocblas::acos(), Window::attribute(), Pane::attributes(), Rocblas::axpy(), Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcChoose(), Rocblas::calcDot(), Rocblas::copy_helper(), Window::delete_attribute(), Pane::delete_attribute(), Rocblas::dot_MPI(), Rocblas::gen2arg(), Window::get_attribute(), Roccom_base::get_f90pntoffsets(), Pane::inherit(), is_staggered(), Rocblas::neg(), FaceOffset_3::obtain_face_offset(), Element_node_vectors_k_const< Value >::operator()(), Element_vectors_k_const< Value >::operator()(), Pane::Pane(), Rocblas::rand(), Rocblas::reduce_MPI(), Pane::reinit_attr(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), Roccom_base::set_f90pointer(), Rocblas::sqrt(), and write_attr_CGNS().
 { return _ncomp; }
int size_of_ghost_items () const
Obtain the number of ghost items in the attribute.
Definition at line 139 of file Attribute.C.
References _id, _loc, _ngitems, _pane, _parent, Pane::attribute(), COM_CONN, COM_NC, Pane::ignore_ghost(), and size_of_ghost_items().
Referenced by Connectivity::size_of_ghost_elements(), size_of_ghost_items(), and write_attr_CGNS().
 {
   if ( _pane->ignore_ghost())
     return 0;
   else if ( _loc == 'n' && _id != COM_NC)
     return _pane->attribute(COM_NC)->size_of_ghost_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->attribute(COM_CONN)->size_of_ghost_items();
   else if ( _parent)
     return _parent->size_of_ghost_items();
   else
     return _ngitems;
 }
int size_of_items () const
Obtain the number of items in the attribute.
Definition at line 111 of file Attribute.C.
References _id, _loc, _nitems, _pane, _parent, Pane::attribute(), COM_CONN, COM_NC, Pane::ignore_ghost(), size_of_items(), and size_of_real_items().
Referenced by Window::append_array(), Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocblas::gen2arg(), Rocblas::get_stride(), Pane::inherit(), Pane::init_done(), Pane::reinit_attr(), Connectivity::size_of_elements(), size_of_items(), and write_attr_CGNS().
 {
   if ( _pane->ignore_ghost())
     return size_of_real_items();
   else if ( _loc == 'n' && _id != COM_NC)
     return _pane->attribute(COM_NC)->size_of_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->attribute(COM_CONN)->size_of_items();
   else if ( _parent)
     return _parent->size_of_items();
   else
     return _nitems<=0 ? 0 : _nitems;
 }
int size_of_real_items () const
Obtain the number of real items in the attribute.
Definition at line 167 of file Attribute.C.
References _gap, _id, _loc, _ngitems, _nitems, _pane, _parent, Pane::attribute(), COM_CONN, COM_NC, and size_of_real_items().
Referenced by Pane_ghost_connectivity::finalize_pconn(), Pane_ghost_connectivity::get_cpanes(), Pane_ghost_connectivity::get_ents_to_send(), Pane::inherit(), size_of_items(), Connectivity::size_of_real_elements(), size_of_real_items(), and write_attr_CGNS().
 {
   if ( _loc == 'n' && _id != COM_NC)
     return _pane->attribute(COM_NC)->size_of_real_items();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->attribute(COM_CONN)->size_of_real_items();
   else if ( _parent)
     return _parent->size_of_real_items();
   else
     return _nitems<=0 ? 0:_nitems - _ngitems - _gap;
 }
bool size_set () const
Returns whether the size for the attribute has been set.
Definition at line 99 of file Attribute.C.
References _id, _loc, _nitems, _pane, _parent, Pane::attribute(), COM_CONN, COM_NC, and size_set().
Referenced by Window::append_array(), Pane::reinit_attr(), and size_set().
 {
   if ( _loc == 'n' && _id != COM_NC)
     return _pane->attribute(COM_NC)->size_set();
   else if ( _loc == 'e' && _id != COM_CONN)
     return _pane->attribute(COM_CONN)->size_set();
   else if ( _parent)
     return _parent->size_set();
   else
     return _nitems>=0;
 }
int status () const inline
Obtain the status of the attribute.
Definition at line 240 of file Attribute.h.
References _parent, _status, and STATUS_USE.
Referenced by apn_input_0d(), prep_modbcdistribution::bcdistributionfiles(), feminp(), genxwriterocinout(), Window::get_status(), inrt_readinputfile(), inrt_readmaterialinput(), peri_readinputfile(), peul_clearsendrequests(), peul_readbcinputfile(), peul_readinputfile(), peul_readsolution(), peul_readsolutionregion(), peul_receivecorneredgecells(), peul_receivedummyvals(), peul_writesolution(), plag_binsortnozzleinlet(), plag_binsortspatialdist(), plag_modsurfstats::plag_opensurfstatsascii(), plag_modsurfstats::plag_opensurfstatsbinary(), plag_processeulerfield(), plag_readinputfile(), plag_readpdffromfile(), plag_readsolution(), plag_readsolutionfilepost(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_clearreqstatbuff(), plag_rflo_clearsendrequests(), plag_rflo_modstats::plag_rflo_readstat(), plag_rflo_recvmetrics(), plag_rflo_modstats::plag_rflo_recvstatbuff(), plag_rflo_modstats::plag_rflo_writestat(), plag_rflu_modcomm::plag_rflu_clearrequest(), plag_moddimensions::plag_rflu_readdimensions(), plag_rflu_readsolutionascii(), plag_rflu_readsolutionbinary(), plag_rflu_modcomm::plag_rflu_recvcounters(), plag_rflu_modcomm::plag_rflu_recvdata(), plag_moddimensions::plag_rflu_writedimensions(), plag_rflu_writesolutionascii(), plag_rflu_writesolutionbinary(), plag_writesolution(), plag_writestattecascii(), plag_writetecplotascii(), radi_floflimrecvcornedgecells(), radi_floflimrecvdummyvals(), radi_rflo_flimclearsendrequests(), radi_rflo_readsolution(), radi_rflo_writesolution(), read_files(), read_frac(), read_io_files(), read_msh(), setup_py::read_properties(), readbcinputfile(), readinp(), readinputfile(), setup_py::readtable(), rflo_clearsendrequests(), rflo_exchangednoderecv(), rflo_exchangegeometryprepare(), rflo_exchangegeometryrecv(), rflo_initflowsolver(), rflo_openconverfile(), rflo_modforcesmoments::rflo_openforcemomcofile(), rflo_openprobefile(), rflo_modrestartinfo::rflo_openrestartinfo(), rflo_openthrustfile(), rflo_readbcfromfile(), rflo_readbcinputfile(), rflo_readgrid(), rflo_readgridregion(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffs(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffsreg(), rflo_readrandomstate(), rflo_readregionmapsection(), rflo_readregiontopology(), rflo_readsolution(), rflo_readsolutionregion(), rflo_readstat(), rflo_readstatregion(), rflo_readtbcinputfile(), rflo_receivecorneredgecells(), rflo_receivedummyvals(), rflo_moddegeneratecornedge::rflo_writedegeneratec(), rflo_writegrid(), rflo_writegridregion(), rflo_modforcesmoments::rflo_writeintegralforcemomco(), rflo_modpatchaerocoeffs::rflo_writepatchaerocoeffs(), rflo_modforcesmoments::rflo_writepatchcoeffsinfo(), rflo_writerandomstate(), rflo_writeregiontopology(), rflo_writesolution(), rflo_writesolutionregion(), rflo_writestat(), rflu_modboundxvutils::rflu_bxv_readvarsascii(), rflu_modboundxvutils::rflu_bxv_readvarsbinary(), rflu_modboundxvutils::rflu_bxv_writevarsascii(), rflu_modboundxvutils::rflu_bxv_writevarsbinary(), rflu_modcoloring::rflu_col_readcoloring(), rflu_modcoloring::rflu_col_writecoloring(), rflu_modcommlists::rflu_comm_readcommlists(), rflu_modcommlists::rflu_comm_writecommlists(), rflu_computeexactflowprobeerror(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_modgambit::rflu_convgambit2rocflu(), rflu_modmesh3d::rflu_convmesh3d2rocflu(), rflu_modtetmesh::rflu_convtetmesh2rocflu(), rflu_modvgridns::rflu_convvgridns2rocflu(), rflu_modensight::rflu_ens_openfilegeometry(), rflu_modensight::rflu_ens_openfilescalarvector(), rflu_modensight::rflu_ens_writefilecase(), rflu_modextractflowdata::rflu_extractflowdatablasius(), rflu_modextractflowdata::rflu_extractflowdatalinefarf(), rflu_modextractflowdata::rflu_extractflowdatanscbc(), rflu_modextractflowdata::rflu_extractflowdataproudman(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modextractflowdata::rflu_extractflowdatasod(), rflu_modextractflowdata::rflu_extractflowdatasommspi(), rflu_modextractflowdata::rflu_extractflowdatastg1d(), rflu_modextractflowdata::rflu_extractflowdatastg2d(), rflu_modrocstario::rflu_genx_openrocinctrlfiles(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modmpi::rflu_mpi_clearrequest(), rflu_modmpi::rflu_mpi_recvcelldata(), rflu_openconverfile(), rflu_modpatchcoeffs::rflu_openpatchcoeffsascii(), rflu_modpatchcoeffs::rflu_openpatchcoeffsbinary(), rflu_openpostinfo(), rflu_modprobes::rflu_openprobefiles(), rflu_modregionmapping::rflu_openregionmappingfile(), rflu_openrestartinfo(), rflu_openstatsfileoles(), rflu_opentotalmassfile(), rflu_modreadwritebcdatafile::rflu_readbcdatafile(), rflu_modreadbcinputfile::rflu_readbcinputfile(), rflu_moddimensions::rflu_readdimensions(), rflu_modreadwriteflow::rflu_readflowascii(), rflu_modreadwriteflow::rflu_readflowbinary(), rflu_modreadwritegrid::rflu_readgridascii(), rflu_modreadwritegrid::rflu_readgridbinary(), rflu_modcentaur::rflu_readgridcentaurascii(), rflu_modcentaur::rflu_readgridcentaurbinary(), rflu_modcobalt::rflu_readgridcobalt(), rflu_modgambit::rflu_readgridgambitneutral(), rflu_modmesh3d::rflu_readgridmesh3d(), rflu_modreadwritegridspeeds::rflu_readgridspeedsascii(), rflu_modreadwritegridspeeds::rflu_readgridspeedsbinary(), rflu_modtetmesh::rflu_readgridtetmesh(), rflu_modvgridns::rflu_readgridvgridns(), rflu_readintegrals1245oles(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_readstat(), rflu_readtbcinputfile(), rflu_modrenumberings::rflu_rnmb_readpxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_readsc2rmap(), rflu_modrenumberings::rflu_rnmb_writepxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_writesc2rmap(), rflu_modstl::rflu_stl_writesurfgridascii(), rflu_modsymmetryperiodic::rflu_sype_readtransforms(), rflu_modsymmetryperiodic::rflu_sype_setsypepatchesflag(), rflu_modsymmetryperiodic::rflu_sype_writetransforms(), rflu_modtecplot::rflu_tec_openfilepnt(), rflu_modthrustspecimpulse::rflu_tsi_openglobalvals(), rflu_modreadwritebcdatafile::rflu_writebcdatafile(), rflu_moddimensions::rflu_writedimensions(), rflu_moddimensions::rflu_writedimensionsborders(), rflu_modreadwriteflow::rflu_writeflowascii(), rflu_modreadwriteflow::rflu_writeflowbinary(), rflu_modforcesmoments::rflu_writeglobalforcesmoments(), rflu_modreadwritegrid::rflu_writegridascii(), rflu_modreadwritegrid::rflu_writegridbinary(), rflu_modreadwritegridspeeds::rflu_writegridspeedsascii(), rflu_modreadwritegridspeeds::rflu_writegridspeedsbinary(), rflu_writeintegrals1245oles(), rflu_modcellmapping::rflu_writeloc2globcellmapping(), rflu_modextractflowdata::rflu_writemeshbump(), rflu_writestat(), rflu_modtetmesh::rflu_writesurfgridtetmesh(), rflu_writeversionstring(), rocflo_2dto3d(), rocflo_surf(), rocfracprep(), rvav_blasiussolution(), rvav_computeanalyticalsolution(), rvav_readfilestream2analyt(), rvav_readfilestream2experm(), rvav_readinputfile(), scale_mesh(), select_bbx(), spec_readinputfile(), spec_rflu_readbcinputfile(), spec_rflu_modreadwritevars::spec_rflu_readcvascii(), spec_rflu_modreadwritevars::spec_rflu_readcvbinary(), spec_rflu_modreadwritevars::spec_rflu_readeevascii(), spec_rflu_modreadwritevars::spec_rflu_readeevbinary(), spec_rflu_modreadwritevars::spec_rflu_writecvascii(), spec_rflu_modreadwritevars::spec_rflu_writecvbinary(), spec_rflu_modreadwritevars::spec_rflu_writeeevascii(), spec_rflu_modreadwritevars::spec_rflu_writeeevbinary(), turb_coranswalldistov(), turb_floransrecvcornedgecells(), turb_floransrecvdummyvals(), turb_readbcinputfile(), turb_readinputfile(), turb_rflo_ransclearsendrequests(), turb_rflo_readsolution(), turb_rflo_readsolutionregion(), turb_rflo_writesolution(), turb_rflu_readsolutionascii(), turb_rflu_readsolutionbinary(), turb_rflu_writesolutionascii(), turb_rflu_writesolutionbinary(), write_grda(), write_grdb(), write_output(), write_output_2(), prep_modbcdistribution::writebctofile(), writeflucellmap(), writefludimens(), writeflugrid(), writegeneric(), writeprobe(), writetecplotascii(), writethrust(), and zn_input_0d().
   { if ( _parent) return STATUS_USE; else return _status; }
int stride () const inline
Obtain the stride of the attribute in base datatype.
Definition at line 233 of file Attribute.h.
References _status, _strd, and root().
Referenced by Window::append_array(), Rocblas::calcDot(), Rocblas::get_stride(), Pane::inherit(), io_pane_attribute(), is_staggered(), Pane::reinit_attr(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), and write_attr_CGNS().
 { return _status?_strd:root()->_strd; }
int stride_in_bytes () const inline
Obtain the stride of the attribute in bytes.
Definition at line 236 of file Attribute.h.
References _nbytes_strd, _status, and root().
   { return _status?_nbytes_strd:root()->_nbytes_strd; }
const std::string& unit () const inline
Obtain the unit of the attribute.
Definition at line 200 of file Attribute.h.
References _unit.
Referenced by __scalegrd.f90__(), apn_input_0d(), Window::get_attribute(), read_files(), read_frac(), read_io_files(), setup_py::read_properties(), scale_mesh(), write_attr_CGNS(), and zn_input_0d().
 { return _unit; }
const Window * window () const
Obtain a constant pointer to the parent window of the attribute.
Definition at line 80 of file Attribute.C.
References _pane, and Pane::window().
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Roccom_base::call_function(), Rocblas::copy(), Roccom_base::copy_attribute(), fullname(), Rocblas::gen2arg(), Window::inherit(), Rocblas::rand(), Rocblas::swap(), and Rocout::write_attr_internal().
 { return _pane->window(); }
Window * window ()
Obtain a modifiable pointer to the parent window of the attribute.
Definition at line 79 of file Attribute.C.
References _pane, and Pane::window().
 { return _pane->window(); }
Member Data Documentation
int _cap protected
Capacity.
Definition at line 323 of file Attribute.h.
Referenced by allocate(), Attribute(), capacity(), inherit(), maxsize_of_ghost_items(), and ~Attribute().
int _gap protected
Gap between the IDs of real and ghost items.
Definition at line 314 of file Attribute.h.
Referenced by size_of_real_items().
int _id protected
Id field data.
Definition at line 302 of file Attribute.h.
Referenced by deallocate(), id(), maxsize_of_ghost_items(), maxsize_of_items(), maxsize_of_real_items(), size_of_ghost_items(), size_of_items(), size_of_real_items(), size_set(), and ~Attribute().
const char _keylocs static protected
Initial value:
=
  { 'n', 'n', 'n', 'n', 'e', 'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p'}
Default locations.
The locations of keywords.
Definition at line 326 of file Attribute.h.
const COM_Type _keysizes static protected
Initial value:
=
  { 3, 1, 1, 1, 0, 0, 1, 2, 1, 1, 0, 0, 0 }
Default sizes.
The sizes of keywords.
Definition at line 328 of file Attribute.h.
const COM_Type _keytypes static protected
Initial value:
=
  { COM_DOUBLE, COM_DOUBLE, COM_DOUBLE, COM_DOUBLE, COM_METADATA,
    COM_METADATA, COM_INT, COM_INT, COM_INT, COM_INT, COM_METADATA,
    COM_METADATA, COM_METADATA }
Default data types.
The datatypes of keywords.
Definition at line 327 of file Attribute.h.
const char * _keywords static protected
Initial value:
=
  { "nc", "1-nc", "2-nc", "3-nc", "conn", "mesh",
    "pconn", "ridges", "1-ridges", "2-ridges", "pmesh", "atts", "all" }
List of keywords.
The names of the keywords.
Definition at line 325 of file Attribute.h.
Shorter_size _loc protected
Location.
'w' for windowed attribute, 'p' for panal attribute, 'n' for nodal attribute, 'e' for elemental attribute
Definition at line 303 of file Attribute.h.
Referenced by Attribute(), inherit(), is_elemental(), is_nodal(), is_panel(), is_windowed(), location(), maxsize_of_ghost_items(), maxsize_of_items(), maxsize_of_real_items(), size_of_ghost_items(), size_of_items(), size_of_real_items(), size_set(), and ~Attribute().
std::string _name protected
Name of the attribute.
Definition at line 301 of file Attribute.h.
Referenced by Attribute().
int _nbytes_strd protected
Number of bytes of the stride.
Definition at line 322 of file Attribute.h.
Referenced by Attribute(), stride_in_bytes(), and ~Attribute().
int _ncomp protected
Number of components.
Definition at line 308 of file Attribute.h.
Referenced by Attribute(), deallocate(), inherit(), size_of_components(), and ~Attribute().
int _ngitems protected
Size of ghost items.
Definition at line 313 of file Attribute.h.
Referenced by Attribute(), maxsize_of_ghost_items(), maxsize_of_real_items(), Connectivity::size_of_elements(), Connectivity::size_of_ghost_elements(), size_of_ghost_items(), Connectivity::size_of_ghost_nodes(), Connectivity::size_of_nodes(), Connectivity::size_of_real_elements(), size_of_real_items(), Connectivity::size_of_real_nodes(), and ~Attribute().
int _nitems protected
Size of total items. Default value is -1.
Definition at line 312 of file Attribute.h.
Referenced by Attribute(), empty(), maxsize_of_ghost_items(), maxsize_of_real_items(), size_of_items(), size_of_real_items(), size_set(), and ~Attribute().
Pane* _pane protected
Pointer to its owner pane.
Definition at line 298 of file Attribute.h.
Referenced by maxsize_of_ghost_items(), maxsize_of_items(), maxsize_of_real_items(), pane(), Connectivity::size_of_elements(), size_of_ghost_items(), Connectivity::size_of_ghost_nodes(), size_of_items(), Connectivity::size_of_nodes(), size_of_real_items(), Connectivity::size_of_real_nodes(), size_set(), window(), and ~Attribute().
Attribute* _parent protected
Parent attribute being used.
Definition at line 299 of file Attribute.h.
Referenced by Attribute(), maxsize_of_ghost_items(), maxsize_of_items(), maxsize_of_real_items(), Connectivity::parent(), parent(), root(), size_of_ghost_items(), size_of_items(), size_of_real_items(), size_set(), status(), and ~Attribute().
void* _ptr protected
Physical address of the attribute.
Definition at line 320 of file Attribute.h.
Referenced by allocate(), deallocate(), pointer(), and ~Attribute().
Shorter_size _status protected
Indicating whether it has been initialized.
Definition at line 318 of file Attribute.h.
Referenced by allocate(), allocated(), Attribute(), capacity(), deallocate(), initialized(), is_const(), pointer(), status(), stride(), stride_in_bytes(), and ~Attribute().
int _strd protected
Stride.
Definition at line 321 of file Attribute.h.
Referenced by allocate(), Attribute(), inherit(), stride(), and ~Attribute().
COM_Type _type protected
Base data type of the attribute.
Definition at line 309 of file Attribute.h.
Referenced by Attribute(), data_type(), inherit(), and ~Attribute().
std::string _unit protected
Unit of the attribute.
Definition at line 310 of file Attribute.h.
Referenced by Attribute(), inherit(), and unit().
The documentation for this class was generated from the following files:
Attribute.h
Attribute.C