Rocstar: rflo_modgridcontrolmap Module Reference
rflo_modgridcontrolmap Module Reference
Public Member Functions
subroutine, public rflo_gridcontrolgrad3d (region)
subroutine, public rflo_gridphysgrad3d (region)
subroutine, public rflo_gridcontrolfunc3d (region)
subroutine, public rflo_gridcontrolgrad2d (region, patch, iPatch)
subroutine, public rflo_gridphysgrad2d (region, patch)
subroutine, public rflo_gridcontrolfunc2d (region, patch, iPatch)
subroutine, public rflo_gridcontrolmap3d (region)
subroutine, public rflo_gridcontrolmap2d (region, patch, iPatch)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModGridControlMap.F90,v $ $Revision: 1.9 $'
Detailed Description
Definition at line 38 of file RFLO_ModGridControlMap.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_gridcontrolfunc2d (type(t_region) region, type(t_patch) patch, integer iPatch)
Definition at line 671 of file RFLO_ModGridControlMap.F90.
References moderror::deregisterfunction(), i, j, moderror::registerfunction(), rflo_modfinitedifference::rflo_findiffcompiis(), rflo_modfinitedifference::rflo_findiffcompis(), rflo_modfinitedifference::rflo_findiffcompjjs(), and rflo_modfinitedifference::rflo_findiffcompjs().
Referenced by rflo_getgeometry().
subroutine, public rflo_gridcontrolfunc3d (type(t_region) region)
Definition at line 257 of file RFLO_ModGridControlMap.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, idnbeg, idnend, j, jdnbeg, jdnend, k, kdnbeg, moderror::registerfunction(), rflo_modfinitedifference::rflo_findiffcompi(), rflo_modfinitedifference::rflo_findiffcompii(), rflo_modfinitedifference::rflo_findiffcompj(), rflo_modfinitedifference::rflo_findiffcompjj(), rflo_modfinitedifference::rflo_findiffcompk(), rflo_modfinitedifference::rflo_findiffcompkk(), rflo_getdimensdummynodes(), and rflo_getnodeoffset().
Referenced by rflo_getgeometry().
subroutine, public rflo_gridcontrolgrad2d (type(t_region) region, type(t_patch) patch, integer iPatch)
Definition at line 499 of file RFLO_ModGridControlMap.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_modfinitedifference::rflo_findiffcompis(), and rflo_modfinitedifference::rflo_findiffcompjs().
Referenced by rflo_getgeometry().
subroutine, public rflo_gridcontrolgrad3d (type(t_region) region)
Definition at line 92 of file RFLO_ModGridControlMap.F90.
References moderror::deregisterfunction(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, moderror::registerfunction(), rflo_modfinitedifference::rflo_findiffcompi(), rflo_modfinitedifference::rflo_findiffcompj(), rflo_modfinitedifference::rflo_findiffcompk(), rflo_getdimensdummynodes(), and rflo_getnodeoffset().
Referenced by rflo_getgeometry().
subroutine, public rflo_gridcontrolmap2d (type(t_region) region, type(t_patch) patch, integer iPatch)
Definition at line 1111 of file RFLO_ModGridControlMap.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), moderror::errorstop(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and sqrt().
Referenced by rflo_getgeometry().
subroutine, public rflo_gridcontrolmap3d (type(t_region) region)
Definition at line 779 of file RFLO_ModGridControlMap.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), i, ibeg, idnbeg, idnend, iend, ipnbeg, ipnend, j, jbeg, jdnbeg, jdnend, jend, jpnbeg, jpnend, k, kbeg, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_modextrapolation::rflo_extrapregdummynode(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and sqrt().
Referenced by rflo_getgeometry().
subroutine, public rflo_gridphysgrad2d (type(t_region) region, type(t_patch) patch)
Definition at line 568 of file RFLO_ModGridControlMap.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_modfinitedifference::rflo_findiffcompis(), rflo_modfinitedifference::rflo_findiffcompjs(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
Referenced by rflo_modelliptsmoothing::rflo_elliptgridgauss2d(), rflo_modelliptsmoothing::rflo_elliptgridjac2d(), and rflo_modelliptsmoothing::rflo_elliptgridsor2d().
subroutine, public rflo_gridphysgrad3d (type(t_region) region)
Definition at line 172 of file RFLO_ModGridControlMap.F90.
References moderror::deregisterfunction(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, moderror::registerfunction(), rflo_modfinitedifference::rflo_findiffcompi(), rflo_modfinitedifference::rflo_findiffcompj(), rflo_modfinitedifference::rflo_findiffcompk(), rflo_getdimensdummynodes(), and rflo_getnodeoffset().
Referenced by rflo_modelliptsmoothing::rflo_elliptgridsmoo(), and rflo_modelliptsmoothing::rflo_elliptgridsmooregion().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModGridControlMap.F90,v $ $Revision: 1.9 $' private
Definition at line 67 of file RFLO_ModGridControlMap.F90.
The documentation for this module was generated from the following file:
RFLO_ModGridControlMap.F90