Rocstar: DomainTSTT Class Reference
DomainTSTT Class Reference
Public Member Functions
DomainTSTT (TSTTG::Geometry &geom, TSTTM::Mesh &mesh, TSTTR::Relate &relate) throw (TSTTB::Error)
virtual ~DomainTSTT ()
DomainHint hint () const
Give a hint about the nature of the domain for better performance.
void snap_to (Mesh::EntityHandle entity_handle, Vector3D &coordinat) const
Modifies "coordinate" so that it lies on the domain to which "entity_handle" is constrained.
void normal_at (Mesh::EntityHandle entity_handle, Vector3D &coordinate) const
Returns the normal of the domain to which "entity_handle" is constrained.
void normal_at (Mesh::EntityHandle handle, Vector3D coordinates[], unsigned count, MsqError &err) const
evaluate surface normals
void closest_point (Mesh::EntityHandle handle, const Vector3D &position, Vector3D &closest, Vector3D &normal, MsqError &err) const
evaluate closest point and normal
Public Member Functions inherited from GeomTSTT
virtual ~GeomTSTT ()
virtual ~GeomTSTT ()
Public Member Functions inherited from MeshDomain
virtual ~MeshDomain ()
Protected Member Functions
void * geom_from_mesh (void *handle) const throw (TSTTB::Error)
Get geometric entity owning a mesh entity.
Protected Member Functions inherited from GeomTSTTCommon
GeomTSTTCommon (TSTTG::Geometry &geom) throw (TSTTB::Error)
virtual ~GeomTSTTCommon ()
void move_to (void *geom_handle, Vector3D &coord) const throw (TSTTB::Error)
Evaluate the closest point to the input position on the specified geometric entity and return the result in the passed position argument (move the passed position onto the geometry.)
void normal (void *geom_handle, Vector3D &coord) const throw (TSTTB::Error)
Given a geometric entity and a position, evaluate the normal on the geometric entity at the closest point on that entity to the input position, and pass back the result in the input coord vector.
void normal (void *geom_handle, Vector3D coords[], unsigned count) const throw (TSTTB::Error)
Given a geometric entity and a position, evaluate the normal on the geometric entity at the closest point on that entity to the input position, and pass back the result in the input coord vector.
void closest_and_normal (void *geom_handle, const Vector3D &position, Vector3D &closest, Vector3D &normal) const throw (TSTTB::Error)
Given a geometric entity and a position, get point on the geometric entity closest to the input position, and the surface normal at that position.
Private Attributes
TSTTG::Topology topoIface
TSTT interface implementation used to get dimension of geometric entities.
TSTTM::Mesh meshIface
TSTT interface used to query mesh entity properties.
TSTTR::Relate relateIface
TSTT interface implementation for mesh->geometry association.
sidl::array< void * > oneMeshHandle
Temporary storage for mesh entity handles.
sidl::array< TSTTG::GentityType > oneTypeOut
Temporary storage for geometry entity type.
Additional Inherited Members
Static Public Member Functions inherited from GeomTSTT
static GeomTSTT * create (TSTTG::Geometry &geom, TSTTM::Mesh &mesh, TSTTR::Relate &assoc, MsqError &err)
Create MeshDommain from TSTT classification and geometry interfaces.
static GeomTSTT * create (TSTTG::Geometry &geom, void *geom_ent_handle, MsqError &err)
Create a MeshDomain for a single geometric entity that uses the TSTT geometry interface for geometric evaluation.
static GeomTSTT * create (TSTTG::Geometry &geom, TSTTM::Mesh &mesh, TSTTR::Relate &assoc, MsqError &err)
Create MeshDommain from TSTT classification and geometry interfaces.
static GeomTSTT * create (TSTTG::Geometry &geom, void *geom_ent_handle, MsqError &err)
Create a MeshDomain for a single geometric entity that uses the TSTT geometry interface for geometric evaluation.
Protected Attributes inherited from GeomTSTTCommon
TSTTG::Shape geomIface
TSTT geometry interface implementation to query.
sidl::array< void * > geomHandles
Temporary storage for geometry entity handles.
sidl::array< double > positionsIn
Temporary storate for input and output vectors.
sidl::array< double > positionsOut
sidl::array< double > normalsOut
Detailed Description
Definition at line 107 of file GeomTSTT.cpp.
Constructor & Destructor Documentation
DomainTSTT (TSTTG::Geometry & geom, TSTTM::Mesh & mesh, TSTTR::Relate & relate) throw (TSTTB::Error)
Definition at line 233 of file GeomTSTT.cpp.
   : GeomTSTTCommon( geom ),
     topoIface( geom ),
     meshIface(mesh),
     relateIface( relate ),
     oneMeshHandle( alloc_sidl_vector<void*>(1) ),
     oneTypeOut( alloc_sidl_vector<TSTTG::GentityType>(1) )
 {
 }
~DomainTSTT () virtual
Definition at line 246 of file GeomTSTT.cpp.
 {}
Member Function Documentation
void closest_point (Mesh::EntityHandle handle, const Vector3D & position, Vector3D & closest, Vector3D & normal, MsqError & err) const virtual
evaluate closest point and normal
Given a position in space, return the closest position in the domain and the domain normal at that point.
Parameters
entity_handle Evaluate the subset of the domain contianing this entity
position Input position for which to evaluate
closest Closest position in the domain.
normal Domain normal at the location of 'closest'
Implements MeshDomain.
Definition at line 297 of file GeomTSTT.cpp.
References GeomTSTTCommon::closest_and_normal(), DomainTSTT::geom_from_mesh(), MsqError::INTERNAL_ERROR, MsqError::INVALID_ARG, MSQ_SETERR, and Mesquite::process_tstt_error().
 {
   try {
     void* geom = geom_from_mesh( (void*)handle );
     if (!geom) {
       MSQ_SETERR(err)(MsqError::INVALID_ARG);
       return;
     }
     closest_and_normal( geom, position, closest, normal );
   }
   catch (TSTTB::Error& tstt_err ) {
     MSQ_SETERR(err)(process_tstt_error(tstt_err),MsqError::INTERNAL_ERROR);
   }
 }
void * geom_from_mesh (void * handle) const throw (TSTTB::Error) protected
Get geometric entity owning a mesh entity.
Definition at line 318 of file GeomTSTT.cpp.
Referenced by DomainTSTT::closest_point(), DomainTSTT::normal_at(), and DomainTSTT::snap_to().
 {
   int junk;
   oneMeshHandle.set( 0, mesh_ent_handle );
   relateIface.getMeshRelatedEntities( &geomIface,
                                       &meshIface,
                                       oneMeshHandle, 1,
                                       geomHandles, junk );
   // get dimension
   junk = 1;
   topoIface.gentityGetType( geomHandles, 1, oneTypeOut, junk );
   return oneTypeOut[0] == TSTTG::GentityType_GREGION ? 0 : geomHandles.get(0);
 }
DomainHint hint () const virtual
Give a hint about the nature of the domain for better performance.
For implementations, if unsure, return NO_DOMAIN_HINT. SMOOTH_DOMAIN is a good default choice if the domain is a single geometric surface.
Implements MeshDomain.
Definition at line 249 of file GeomTSTT.cpp.
References Mesquite::NO_DOMAIN_HINT.
   { return NO_DOMAIN_HINT; }
void normal_at (Mesh::EntityHandle entity_handle, Vector3D & coordinate) const virtual
Returns the normal of the domain to which "entity_handle" is constrained.
For non-planar surfaces, the normal is calculated at the point on the domain that is closest to the passed in value of "coordinate". If the domain does not have a normal, or the normal cannot be determined, "coordinate" is set to (0,0,0). Otherwise, "coordinate" is set to the domain's normal at the appropriate point. In summary, the handle determines the domain. The coordinate determines the point of interest on that domain.
User should see also PatchData::get_domain_normal_at_vertex and PatchData::get_domain_normal_at_element .
Implements MeshDomain.
Definition at line 265 of file GeomTSTT.cpp.
References DomainTSTT::geom_from_mesh(), GeomTSTTCommon::normal(), and Mesquite::process_tstt_error().
 {
   try {
     void* geom = geom_from_mesh( (void*)handle );
     if (geom)
       normal( geom, coordinate );
   }
   catch (TSTTB::Error& tstt_err ) {
     process_tstt_error(tstt_err);
   }
 }
void normal_at (Mesh::EntityHandle handle, Vector3D coordinates[], unsigned count, MsqError & err) const virtual
evaluate surface normals
Returns normals for a domain.
Parameters
entity_handle The domain evaluated is the one in which this mesh entity is constrained.
coordinates As input, a list of positions at which to evaluate the domain. As output, the resulting domain normals.
count The length of the coordinates array.
Implements MeshDomain.
Definition at line 278 of file GeomTSTT.cpp.
References DomainTSTT::geom_from_mesh(), MsqError::INTERNAL_ERROR, MsqError::INVALID_ARG, MSQ_SETERR, GeomTSTTCommon::normal(), and Mesquite::process_tstt_error().
 {
   try {
     void* geom = geom_from_mesh( (void*)handle );
     if (!geom) {
       MSQ_SETERR(err)(MsqError::INVALID_ARG);
       return;
     }
     normal( geom, coordinates, count );
   }
   catch (TSTTB::Error& tstt_err ) {
     MSQ_SETERR(err)(process_tstt_error(tstt_err),MsqError::INTERNAL_ERROR);
   }
 }
void snap_to (Mesh::EntityHandle entity_handle, Vector3D & coordinate) const virtual
Modifies "coordinate" so that it lies on the domain to which "entity_handle" is constrained.
The handle determines the domain. The coordinate is the proposed new position on that domain.
Implements MeshDomain.
Definition at line 252 of file GeomTSTT.cpp.
References DomainTSTT::geom_from_mesh(), GeomTSTTCommon::move_to(), and Mesquite::process_tstt_error().
 {
   try {
     void* geom = geom_from_mesh( (void*)handle );
     if (geom)
       move_to( geom, coordinate );
   }
   catch (TSTTB::Error& tstt_err ) {
     process_tstt_error(tstt_err);
   }
 }
Member Data Documentation
TSTTM::Mesh meshIface mutable private
TSTT interface used to query mesh entity properties.
Definition at line 146 of file GeomTSTT.cpp.
sidl::array<void*> oneMeshHandle mutable private
Temporary storage for mesh entity handles.
Definition at line 151 of file GeomTSTT.cpp.
sidl::array<TSTTG::GentityType> oneTypeOut mutable private
Temporary storage for geometry entity type.
Definition at line 153 of file GeomTSTT.cpp.
TSTTR::Relate relateIface mutable private
TSTT interface implementation for mesh->geometry association.
Definition at line 148 of file GeomTSTT.cpp.
TSTTG::Topology topoIface mutable private
TSTT interface implementation used to get dimension of geometric entities.
Definition at line 144 of file GeomTSTT.cpp.
The documentation for this class was generated from the following file:
GeomTSTT.cpp