Rocstar: Mesh::BSExtent< T > Class Template Reference
Mesh::BSExtent< T > Class Template Reference
Simple Block Structured Mesh object.
#include <BSMesh.H>
Public Member Functions
BSExtent ()
BSExtent (const std::vector< std::vector< T > > &inextent)
BSExtent (const std::vector< T > &inflatextent)
BSExtent (const T *src, int nd=3)
void destroy ()
void Init (const std::vector< T > &inflatextent)
void Sync ()
T NNodes ()
int ND ()
void Flatten (std::vector< T > &output)
void dir_loop (int nd, T indoff, T plane, std::vector< T > &N, std::vector< T > &NP, const BSExtent< T > &inextent, std::vector< T > &indices)
void GetFlatIndices (const BSExtent< T > &extent, std::vector< T > &indices)
void Overlap (const BSExtent< T > &inextent, BSExtent< T > &outextent)
void FindSharedNodes (std::vector< BSExtent< T > > &extent_pool, std::vector< BSExtent< T > > &shared_extents, std::vector< T > &neighbors)
T NodeNum (std::vector< T > &index)
void CreateUnstructuredMesh (Connectivity &conn)
Private Attributes
size_t _nd
std::vector< size_t > _Np
std::vector< size_t > _N
Detailed Description
template<typename T>
class Mesh::BSExtent< T >
Simple Block Structured Mesh object.
Block structured mesh object holds irange, jrange, and krange. Elements are ordered in dictionary ordering of lower left node
Definition at line 16 of file BSMesh.H.
Constructor & Destructor Documentation
BSExtent () inline
Definition at line 23 of file BSMesh.H.
References Mesh::BSExtent< T >::_N, Mesh::BSExtent< T >::_nd, and Mesh::BSExtent< T >::_Np.
     {
       this->resize(0);
       _nd = 0;
       _Np.resize(0);
       _N.resize(0);
     }
BSExtent (const std::vector< std::vector< T > > & inextent) inline
Definition at line 30 of file BSMesh.H.
References Mesh::BSExtent< T >::_nd, i, and Mesh::BSExtent< T >::Sync().
     {
       _nd = inextent.size();
       this->resize(_nd);
       for(size_t i = 0; i < _nd; i++){
         typename std::vector<T>::const_iterator iei = inextent[i].begin();
         while(iei != inextent[i].end())
           (*this)[i].push_back(*iei++);
       }
       Sync();
     };
BSExtent (const std::vector< T > & inflatextent) inline
Definition at line 41 of file BSMesh.H.
References Mesh::BSExtent< T >::_nd, and Mesh::BSExtent< T >::Sync().
{
       _nd = inflatextent.size()/2;
       this->resize(_nd);
       size_t nd = 0;
       typename BSExtent<T>::iterator bsi = this->begin();
       while(bsi != this->end()){
         bsi->push_back(inflatextent[nd++]);
         bsi->push_back(inflatextent[nd++]);
         bsi++;
       }
       Sync();
     };
BSExtent (const T * src, int nd = 3) inline
Definition at line 53 of file BSMesh.H.
References Mesh::BSExtent< T >::_nd, and Mesh::BSExtent< T >::Sync().
{
       _nd = nd;
       this->resize(_nd);
       unsigned int nindex = 0;
       typename BSExtent<T>::iterator bsi = this->begin();
       while(bsi != this->end()){
         bsi->push_back(src[nindex++]);
         bsi->push_back(src[nindex++]);
         bsi++;
       }
       Sync();
     };
Member Function Documentation
void CreateUnstructuredMesh (Connectivity & conn) inline
Definition at line 199 of file BSMesh.H.
References Mesh::BSExtent< T >::_N, Mesh::BSExtent< T >::_nd, Mesh::Connectivity::AddElement(), Mesh::BSExtent< T >::GetFlatIndices(), i, offset(), and Mesh::Connectivity::Sync().
Referenced by Rocon::burnout(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), and TRAIL_Window2UnstructuredMesh().
     {
       // get coordinates of lower left hand coordinates:
       // istart to (iend - 1), or istart
       // jstart to (jend - 1), or jstart
       // kstart to (kend - 1), or kstart
       assert(_nd == 3);
       BSExtent<T> lowerleft(*this);
       int mesh_nd = 3;
       for(int i = 0;i < 3;i++){
         if(_N[i] > 1)
           lowerleft[i][1]--;
         else
           mesh_nd--;
       }
       assert(mesh_nd > 1);
       std::vector<T> indices;
       GetFlatIndices(lowerleft,indices);
       IndexType offset = (_N[0] > 1 ? _N[0] : _N[1]);
       IndexType planeoffset = (mesh_nd == 2 ? 0 : offset*_N[1]);
       IndexType number_of_elements = indices.size();
       for(IndexType i = 0;i < number_of_elements;i++){
         std::vector<IndexType> element;
         element.push_back(indices[i]);
         element.push_back(indices[i]+1);
         element.push_back(indices[i]+1+offset);
         element.push_back(indices[i]+offset);
         if(planeoffset > 0){
           element.push_back(indices[i]+planeoffset);
           element.push_back(indices[i]+1+planeoffset);
           element.push_back(indices[i]+planeoffset+offset+1);
           element.push_back(indices[i]+planeoffset+offset);
         }
         conn.AddElement(element);
       }
       conn.Sync();
     };
void destroy () inline
Definition at line 65 of file BSMesh.H.
References Mesh::BSExtent< T >::_N, Mesh::BSExtent< T >::_nd, and Mesh::BSExtent< T >::_Np.
Referenced by Mesh::BSExtent< T >::Init().
     {
       typename BSExtent<T>::iterator bsi = this->begin();
       while(bsi != this->end())
         bsi++->resize(0);
       this->resize(0);
       _nd = 0;
       _Np.resize(0);
       _N.resize(0);
     };
void dir_loop (int nd, T indoff, T plane, std::vector< T > & N, std::vector< T > & NP, const BSExtent< T > & inextent, std::vector< T > & indices) inline
Definition at line 121 of file BSMesh.H.
Referenced by Mesh::BSExtent< T >::GetFlatIndices().
     {
       int dindex = nd - 1;
       plane += NP[dindex];
       T start = inextent[dindex][0];
       T end   = inextent[dindex][1];
       for(T dd = start;dd <= end;dd++){
         if(dindex == 0)
           indices.push_back(dd - (*this)[dindex][0]+1+indoff);
         else{
           T ndoff = indoff + (dd - (*this)[dindex][0])*NP[dindex];
           dir_loop(dindex,ndoff,plane,N,NP,inextent,indices);
         }
       }
     };
void FindSharedNodes (std::vector< BSExtent< T > > & extent_pool, std::vector< BSExtent< T > > & shared_extents, std::vector< T > & neighbors) inline
Definition at line 174 of file BSMesh.H.
References Mesh::BSExtent< T >::Overlap().
Referenced by TRAIL_FD2FE_WinCreate2().
     {
       shared_extents.resize(0);
       T nindex = 0;
       typename std::vector<BSExtent<T> >::iterator epi = extent_pool.begin();
       while(epi != extent_pool.end()){
         if(*epi != *this){
           BSExtent<T> overlap;
           this->Overlap(*epi,overlap);
           if(!overlap.empty()){
             neighbors.push_back(nindex);
             shared_extents.push_back(overlap);
           }
         }
         nindex++;
         epi++;
       }
     };
void Flatten (std::vector< T > & output) inline
Definition at line 111 of file BSMesh.H.
Referenced by TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate(), and TRAIL_FD2FE_WinCreate2().
     {
       output.resize(0);
       typename BSExtent<T>::iterator bsi = this->begin();
       while(bsi != this->end()){
         output.push_back((*bsi)[0]);
         output.push_back((*bsi)[1]);
         bsi++;
       }
     };
void GetFlatIndices (const BSExtent< T > & extent, std::vector< T > & indices) inline
Definition at line 139 of file BSMesh.H.
References Mesh::BSExtent< T >::dir_loop(), and Mesh::BSExtent< T >::ND().
Referenced by Mesh::BSExtent< T >::CreateUnstructuredMesh(), main(), test2(), TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), TRAIL_FE2FD_Transfer(), and TRAIL_Window2UnstructuredMesh().
     {
       int nd = ND();
       indices.resize(0);
       std::vector<T> N(nd);
       std::vector<T> NP(nd);
       for(int nc = 0;nc < nd;nc++){
         N[nc] = (*this)[nc][1] - (*this)[nc][0] + 1;
         NP[nc] = (nc == 0 ? 1 : N[nc-1] * NP[nc-1]);
       }
       NP[0] = 0;
       dir_loop(nd,0,0,N,NP,extent,indices);
     };
void Init (const std::vector< T > & inflatextent) inline
Definition at line 75 of file BSMesh.H.
References Mesh::BSExtent< T >::_nd, Mesh::BSExtent< T >::destroy(), and Mesh::BSExtent< T >::Sync().
Referenced by Mesh::GenerateCartesianGrid(), main(), and test2().
{
       destroy();
       _nd = inflatextent.size()/2;
       this->resize(_nd);
       size_t nd = 0;
       typename BSExtent<T>::iterator bsi = this->begin();
       while(bsi != this->end()){
         bsi->push_back(inflatextent[nd++]);
         bsi->push_back(inflatextent[nd++]);
         bsi++;
       }
       Sync();
     };
int ND () inline
Definition at line 110 of file BSMesh.H.
Referenced by Mesh::BSExtent< T >::GetFlatIndices(), and Mesh::BSExtent< T >::Overlap().
 {return(this->size());};
T NNodes () inline
Definition at line 101 of file BSMesh.H.
Referenced by TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate(), and TRAIL_FD2FE_WinCreate2().
               {
       T nnodes = 1;
       typename BSExtent<T>::iterator bsi = this->begin();
       while(bsi != this->end()){
         nnodes *= (((*bsi)[1] - (*bsi)[0])+1);
         bsi++;
       }
       return(nnodes);
     };
T NodeNum (std::vector< T > & index) inline
Definition at line 193 of file BSMesh.H.
References Mesh::BSExtent< T >::_nd, Mesh::BSExtent< T >::_Np, and i.
     {
       T l0 = 1;
       for(size_t i = (_nd-1);i >= 0;i--)
         l0 += (index[i] - (*this)[i][0])*_Np[i];
     };
void Overlap (const BSExtent< T > & inextent, BSExtent< T > & outextent) inline
Definition at line 152 of file BSMesh.H.
References i, j, max(), min(), and Mesh::BSExtent< T >::ND().
Referenced by Mesh::BSExtent< T >::FindSharedNodes(), and TRAIL_FD2FE_Transfer().
     {
       size_t nd = ND();
       outextent.resize(0);
       bool match = true;
       for(size_t j = 0;j < nd && match;j++){
         if(!(((*this)[j][0] >= inextent[j][0] &&
               (*this)[j][0] <= inextent[j][1]) ||
              ((*this)[j][1] >= inextent[j][0] &&
               (*this)[j][1] <= inextent[j][1])))
           match = false;
       }
       if(match){ // then this extent has some overlap with the searched
         outextent.resize(nd);
         for(size_t i = 0;i < nd;i++)
           outextent[i].resize(2);
         for(size_t i = 0;i < nd;i++){
           outextent[i][0] = std::max((*this)[i][0],inextent[i][0]);
           outextent[i][1] = std::min((*this)[i][1],inextent[i][1]);
         }
       }
     };
void Sync () inline
Definition at line 88 of file BSMesh.H.
References Mesh::BSExtent< T >::_N, Mesh::BSExtent< T >::_nd, Mesh::BSExtent< T >::_Np, and i.
Referenced by Mesh::BSExtent< T >::BSExtent(), Mesh::BSExtent< T >::Init(), TRAIL_FD2FE_WinCreate(), and TRAIL_FD2FE_WinCreate2().
     {
       _nd = this->size();
       _N.resize(_nd);
       _Np.resize(_nd);
       for(size_t i = 0; i < _nd; i++){
         _N[i] = (*this)[i][1] - (*this)[i][0] + 1;
       }
       _Np[0] = 1;
       for(size_t i = 1; i < _nd;i++){
         _Np[i] = _N[i-1] * _Np[i-1];
       }
     };
Member Data Documentation
std::vector<size_t> _N private
Definition at line 21 of file BSMesh.H.
Referenced by Mesh::BSExtent< T >::BSExtent(), Mesh::BSExtent< T >::CreateUnstructuredMesh(), Mesh::BSExtent< T >::destroy(), and Mesh::BSExtent< T >::Sync().
size_t _nd private
Definition at line 19 of file BSMesh.H.
Referenced by Mesh::BSExtent< T >::BSExtent(), Mesh::BSExtent< T >::CreateUnstructuredMesh(), Mesh::BSExtent< T >::destroy(), Mesh::BSExtent< T >::Init(), Mesh::BSExtent< T >::NodeNum(), and Mesh::BSExtent< T >::Sync().
std::vector<size_t> _Np private
Definition at line 20 of file BSMesh.H.
Referenced by Mesh::BSExtent< T >::BSExtent(), Mesh::BSExtent< T >::destroy(), Mesh::BSExtent< T >::NodeNum(), and Mesh::BSExtent< T >::Sync().
The documentation for this class was generated from the following file:
BSMesh.H