Rocstar: externalBCpatch Class Reference
externalBCpatch Class Reference
#include <patch.h>
Public Member Functions
virtual void writeFlo (FILE *out, const bcList &bc)
virtual void writeMblock (FILE *out, mblockData &d)
virtual void writeTop (FILE *out, const bcListTop &d)
virtual bool isExternal (void) const
externalBCpatch ()
externalBCpatch (face *f_, block *src_, const blockSpan &srcSpan_, int bcNo_)
Public Member Functions inherited from patch
void setFace (face *f_)
face * getFace (void) const
patch ()
virtual ~patch ()
Public Attributes
int bcNo
Public Attributes inherited from patch
block * src
blockSpan srcSpan
Friends
class block
Additional Inherited Members
Protected Member Functions inherited from patch
patch (face *f_, block *src_, const blockSpan &srcSpan_)
Detailed Description
Definition at line 100 of file patch.h.
Constructor & Destructor Documentation
externalBCpatch () inline
Definition at line 111 of file patch.h.
 {}
externalBCpatch (face * f_, block * src_, const blockSpan & srcSpan_, int bcNo_) inline
Definition at line 112 of file patch.h.
           : patch(f_,src_,srcSpan_), bcNo(bcNo_) { }
Member Function Documentation
bool isExternal (void) const virtual
Reimplemented from patch.
Definition at line 64 of file buildface.cpp.
 {return true;}
void writeFlo (FILE * out, const bcList & bc) virtual
Implements patch.
Definition at line 170 of file writeflo.cpp.
References bcNo, getSpan(), bcList::lookup(), and patch::srcSpan.
 {
         string srcS=getSpan(srcSpan);
         string bcDesc=bc.lookup(bcNo,srcS);
         fprintf(out,"%s",bcDesc.c_str());
 }
void writeMblock (FILE * out, mblockData & d) virtual
Implements patch.
Definition at line 194 of file writemblock.cpp.
References printSpan().
 {
         fprintf(out,"%d ",bcNo);
         printSpan(out,srcSpan);
 }
void writeTop (FILE * out, const bcListTop & d) virtual
Implements patch.
Definition at line 193 of file writetop.cpp.
References bcNo, bcRecTop::isCoupled, bcListTop::lookup(), bcRecTop::outNo, patch::srcSpan, write5(), writePatchEnd(), writePatchMiddle(), writePatchStart(), and writeSpan().
 {
         bcRecTop *r=bc.lookup(bcNo);
         writePatchStart(out,r->outNo);
         writeSpan(out,srcSpan,blockLoc(1,1,1));
         //Destination block and span are zero for external boundaries
         writePatchMiddle(out,0);
         write5(out,0,0,0,0,0);
         writePatchEnd(out,r->isCoupled);
 }
Friends And Related Function Documentation
friend class block friend
Definition at line 101 of file patch.h.
Member Data Documentation
int bcNo
Definition at line 104 of file patch.h.
Referenced by block::subBlock(), writeFlo(), and writeTop().
The documentation for this class was generated from the following files:
patch.h
buildface.cpp
writeflo.cpp
writemblock.cpp
writetop.cpp