Rocstar: PatchDataParameters Class Reference
PatchDataParameters Class Reference
#include <PatchDataUser.hpp>
Public Member Functions
PatchDataParameters ()
PatchDataParameters (const PatchDataParameters &A)
void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int patch_param1=0, int patch_param2=0)
Tells the MeshSet what kind of data the patches should include.
PatchData::PatchType get_patch_type ()
Returns Patch Type (local around vertices, local around elements, global)
int get_nb_layers (MsqError &err)
Returns numbers of layers for local patch.
void set_global_patch_type ()
void set_element_on_vertex_patch_type (unsigned num_layers)
void add_culling_method (enum PatchData::culling_method cm)
Sets on a culling criterion.
void no_culling_method ()
No culling performed (sets off all culling criteria).
void remove_culling_method (enum PatchData::culling_method cm)
Sets off a certain culling criteria.
long unsigned int get_culling_method_bits ()
returns the bitset.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
PatchDataParameters ()
PatchDataParameters (const PatchDataParameters &A)
void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int patch_param1=0, int patch_param2=0)
Tells the MeshSet what kind of data the patches should include.
PatchData::PatchType get_patch_type ()
Returns Patch Type (local around vertices, local around elements, global)
int get_nb_layers (MsqError &err)
Returns numbers of layers for local patch.
void set_global_patch_type ()
void set_element_on_vertex_patch_type (unsigned num_layers)
void add_culling_method (enum PatchData::culling_method cm)
Sets on a culling criterion.
void no_culling_method ()
No culling performed (sets off all culling criteria).
void remove_culling_method (enum PatchData::culling_method cm)
Sets off a certain culling criteria.
long unsigned int get_culling_method_bits ()
returns the bitset.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Private Attributes
PatchData::PatchType mType
see the enum ...
int mParam1
int mParam2
For general use in conjunction with PatchType.
long unsigned int cullingMethodBits
type of cullings are contained in this bitset.
PatchData * globalPatch
Allows storage of global patch through successive PatchDataUsers.
Friends
class PatchDataUser
Detailed Description
contains all information necessary to fill up a PatchData instance.
Definition at line 58 of file includeLinks/PatchDataUser.hpp.
Constructor & Destructor Documentation
PatchDataParameters () inline
Definition at line 61 of file includeLinks/PatchDataUser.hpp.
                           :
       mType(PatchData::UNDEFINED_PATCH_TYPE),
       mParam1(0),
       mParam2(0),
       cullingMethodBits(0),
       globalPatch(0)
     {}
PatchDataParameters (const PatchDataParameters & A) inline
Definition at line 69 of file includeLinks/PatchDataUser.hpp.
References PatchDataParameters::cullingMethodBits, PatchDataParameters::globalPatch, PatchDataParameters::mParam1, PatchDataParameters::mParam2, and PatchDataParameters::mType.
{
       mType = A.mType;
       mParam1 = A.mParam1;
       mParam2 = A.mParam2;
       cullingMethodBits = A.cullingMethodBits;
       globalPatch = A.globalPatch;
     }
PatchDataParameters () inline
Definition at line 61 of file src/Mesh/PatchDataUser.hpp.
                           :
       mType(PatchData::UNDEFINED_PATCH_TYPE),
       mParam1(0),
       mParam2(0),
       cullingMethodBits(0),
       globalPatch(0)
     {}
PatchDataParameters (const PatchDataParameters & A) inline
Definition at line 69 of file src/Mesh/PatchDataUser.hpp.
References PatchDataParameters::cullingMethodBits, PatchDataParameters::globalPatch, PatchDataParameters::mParam1, PatchDataParameters::mParam2, and PatchDataParameters::mType.
{
       mType = A.mType;
       mParam1 = A.mParam1;
       mParam2 = A.mParam2;
       cullingMethodBits = A.cullingMethodBits;
       globalPatch = A.globalPatch;
     }
Member Function Documentation
void add_culling_method (enum PatchData::culling_method cm) inline
Sets on a culling criterion.
Definition at line 274 of file includeLinks/PatchDataUser.hpp.
References PatchDataParameters::cullingMethodBits.
Referenced by PatchDataUser::add_culling_method().
   {
     cullingMethodBits |= cm;
   }
void add_culling_method (enum PatchData::culling_method cm) inline
Sets on a culling criterion.
long unsigned int get_culling_method_bits () inline
returns the bitset.
Definition at line 104 of file includeLinks/PatchDataUser.hpp.
References PatchDataParameters::cullingMethodBits.
Referenced by PatchDataUser::get_culling_method_bits(), and MeshSet::get_next_elem_on_vert_patch().
 { return cullingMethodBits; }
long unsigned int get_culling_method_bits () inline
returns the bitset.
Definition at line 104 of file src/Mesh/PatchDataUser.hpp.
References PatchDataParameters::cullingMethodBits.
 { return cullingMethodBits; }
PatchData* get_global_patch () inline
Returns the Global Patch.
Will be 0 if not available. Make sure not to use that function if a local patch algorithm has been used since the last access to the global patch, making it invalid.
Definition at line 111 of file includeLinks/PatchDataUser.hpp.
References PatchDataParameters::globalPatch.
Referenced by PatchDataUser::get_global_patch().
     { return globalPatch; }
PatchData* get_global_patch () inline
Returns the Global Patch.
Will be 0 if not available. Make sure not to use that function if a local patch algorithm has been used since the last access to the global patch, making it invalid.
Definition at line 111 of file src/Mesh/PatchDataUser.hpp.
References PatchDataParameters::globalPatch.
     { return globalPatch; }
int get_nb_layers (MsqError & err) inline
Returns numbers of layers for local patch.
This might not always be a valid measure, depending on the partition algorythm.
Definition at line 262 of file includeLinks/PatchDataUser.hpp.
References PatchData::GLOBAL_PATCH, MsqError::INVALID_STATE, PatchDataParameters::mParam1, MSQ_SETERR, and PatchDataParameters::mType.
Referenced by PatchDataUser::get_nb_layers(), and MeshSet::get_next_elem_on_vert_patch().
   {
     if (mType == PatchData::GLOBAL_PATCH) {
       MSQ_SETERR(err)("Patch Type is GLOBAL_PATCH.", MsqError::INVALID_STATE);
       return 0;
     }
     return mParam1;
   }
int get_nb_layers (MsqError & err) inline
Returns numbers of layers for local patch.
This might not always be a valid measure, depending on the partition algorythm.
PatchData::PatchType get_patch_type () inline
Returns Patch Type (local around vertices, local around elements, global)
Definition at line 88 of file includeLinks/PatchDataUser.hpp.
References PatchDataParameters::mType.
Referenced by MeshSet::get_next_patch(), PatchDataUser::get_patch_type(), and PatchDataParameters::set_global_patch().
     {return mType;}
PatchData::PatchType get_patch_type () inline
Returns Patch Type (local around vertices, local around elements, global)
Definition at line 88 of file src/Mesh/PatchDataUser.hpp.
References PatchDataParameters::mType.
     {return mType;}
void no_culling_method () inline
No culling performed (sets off all culling criteria).
void no_culling_method () inline
No culling performed (sets off all culling criteria).
Definition at line 281 of file includeLinks/PatchDataUser.hpp.
References PatchDataParameters::cullingMethodBits.
Referenced by PatchDataUser::no_culling_method(), MeshSet::write_gnuplot(), and MeshSet::write_vtk().
   {
     cullingMethodBits = 0;
   }
void no_global_patch () inline
Sets the Global Patch pointer to NULL.
Make sure to call that function before modifying the mesh with local patches. Memory handling (creation/deletion) should be done outside PatchDataUSer, typically in InstructionQueue
Definition at line 117 of file src/Mesh/PatchDataUser.hpp.
References PatchDataParameters::globalPatch.
     { globalPatch=0; }
void no_global_patch () inline
Sets the Global Patch pointer to NULL.
Make sure to call that function before modifying the mesh with local patches. Memory handling (creation/deletion) should be done outside PatchDataUSer, typically in InstructionQueue
Definition at line 117 of file includeLinks/PatchDataUser.hpp.
References PatchDataParameters::globalPatch.
Referenced by PatchDataUser::no_global_patch().
     { globalPatch=0; }
void remove_culling_method (enum PatchData::culling_method cm) inline
Sets off a certain culling criteria.
Definition at line 288 of file includeLinks/PatchDataUser.hpp.
References PatchDataParameters::cullingMethodBits.
Referenced by PatchDataUser::remove_culling_method().
   {
     cullingMethodBits &= ~cm;
   }
void remove_culling_method (enum PatchData::culling_method cm) inline
Sets off a certain culling criteria.
void set_element_on_vertex_patch_type (unsigned num_layers) inline
void set_element_on_vertex_patch_type (unsigned num_layers) inline
Definition at line 255 of file includeLinks/PatchDataUser.hpp.
References PatchData::ELEMENTS_ON_VERTEX_PATCH, PatchDataParameters::mParam1, and PatchDataParameters::mType.
   {
     mType = PatchData::ELEMENTS_ON_VERTEX_PATCH;
     mParam1 = num_layers;
   }
void set_global_patch (PatchData * pd, MsqError & err) inline
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
Definition at line 294 of file includeLinks/PatchDataUser.hpp.
References PatchDataParameters::get_patch_type(), PatchData::GLOBAL_PATCH, PatchDataParameters::globalPatch, MsqError::INVALID_STATE, and MSQ_SETERR.
Referenced by PatchDataUser::set_global_patch().
   {
     if (get_patch_type() != PatchData::GLOBAL_PATCH)
       MSQ_SETERR(err)("Trying to set a global patch whereas the "
                   "PatchType is set to something else\n."
                   "Consider using the function no_global_patch().",
                   MsqError::INVALID_STATE);
     else {
       globalPatch = pd;
     }
   }
void set_global_patch (PatchData * pd, MsqError & err) inline
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
void set_global_patch_type () inline
Definition at line 250 of file includeLinks/PatchDataUser.hpp.
References PatchData::GLOBAL_PATCH, and PatchDataParameters::mType.
Referenced by TargetCalculator::TargetCalculator().
   {
     mType = PatchData::GLOBAL_PATCH;
   }
void set_global_patch_type () inline
void set_patch_type (PatchData::PatchType patch_type, MsqError & err, int patch_param1 = 0, int patch_param2 = 0) inline
Tells the MeshSet what kind of data the patches should include.
Parameters
patch_type see the PatchData::PatchType enumeration.
patch_param1 meaning depends on patch_type.
patch_param2 meaning depends on patch_type.
This function can be over-ridden by the concrete PatchDataUser, in order to cusotomize the Patches available to for the specific algorithm implemented.
Utimately, we might want to return an error in the Parent class implementation, in order to force the concrete classes to specify the available types.
Definition at line 219 of file includeLinks/PatchDataUser.hpp.
References PatchData::ELEMENTS_ON_VERTEX_PATCH, PatchData::GLOBAL_PATCH, PatchDataParameters::mParam1, PatchDataParameters::mParam2, MSQ_SETERR, PatchDataParameters::mType, and MsqError::NOT_IMPLEMENTED.
Referenced by TerminationCriterion::accumulate_outer(), TerminationCriterion::reset_outer(), PatchDataUser::set_patch_type(), MeshSet::write_gnuplot(), and MeshSet::write_vtk().
   {
     // For now, no support for VERTICES_ON_ELEMENT_PATCH
     if ( patch_type != PatchData::ELEMENTS_ON_VERTEX_PATCH
          && patch_type != PatchData::GLOBAL_PATCH )
       {
         MSQ_SETERR(err)("VERTICES_ON_ELEMENT_PATCH not supported yet.",
                         MsqError::NOT_IMPLEMENTED);
         return;
       }
     if (patch_type == PatchData::ELEMENTS_ON_VERTEX_PATCH)
       {
         if (patch_param1 < 0)
         {
           MSQ_SETERR(err)("ELEMENTS_ON_VERTEX_PATCH not supported yet.",
                           MsqError::NOT_IMPLEMENTED);
           return;
         }
       }
     mType = patch_type;
     mParam1 = patch_param1;
     mParam2 = patch_param2;
     return;
   }
void set_patch_type (PatchData::PatchType patch_type, MsqError & err, int patch_param1 = 0, int patch_param2 = 0) inline
Tells the MeshSet what kind of data the patches should include.
Parameters
patch_type see the PatchData::PatchType enumeration.
patch_param1 meaning depends on patch_type.
patch_param2 meaning depends on patch_type.
Friends And Related Function Documentation
PatchDataUser friend
Definition at line 77 of file includeLinks/PatchDataUser.hpp.
Member Data Documentation
long unsigned int cullingMethodBits private
type of cullings are contained in this bitset.
Definition at line 125 of file includeLinks/PatchDataUser.hpp.
Referenced by PatchDataParameters::add_culling_method(), PatchDataParameters::get_culling_method_bits(), PatchDataParameters::no_culling_method(), PatchDataParameters::PatchDataParameters(), and PatchDataParameters::remove_culling_method().
PatchData * globalPatch private
Allows storage of global patch through successive PatchDataUsers.
Definition at line 126 of file includeLinks/PatchDataUser.hpp.
Referenced by PatchDataParameters::get_global_patch(), PatchDataParameters::no_global_patch(), PatchDataParameters::PatchDataParameters(), and PatchDataParameters::set_global_patch().
int mParam1 private
Definition at line 124 of file includeLinks/PatchDataUser.hpp.
Referenced by PatchDataParameters::get_nb_layers(), PatchDataParameters::PatchDataParameters(), PatchDataParameters::set_element_on_vertex_patch_type(), and PatchDataParameters::set_patch_type().
int mParam2 private
For general use in conjunction with PatchType.
Definition at line 124 of file includeLinks/PatchDataUser.hpp.
Referenced by PatchDataParameters::PatchDataParameters(), and PatchDataParameters::set_patch_type().
PatchData::PatchType mType private
see the enum ...
Definition at line 123 of file includeLinks/PatchDataUser.hpp.
Referenced by PatchDataParameters::get_nb_layers(), PatchDataParameters::get_patch_type(), PatchDataParameters::PatchDataParameters(), PatchDataParameters::set_element_on_vertex_patch_type(), PatchDataParameters::set_global_patch_type(), and PatchDataParameters::set_patch_type().
The documentation for this class was generated from the following file:
includeLinks/PatchDataUser.hpp