Rocstar: Aff_transformation_2< R_ > Class Template Reference
Aff_transformation_2< R_ > Class Template Reference
#include <Aff_transformation_2.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Line_2_base RLine_2
typedef R::Direction_2_base RDirection_2
typedef
R::Aff_transformation_2_base RAff_transformation_2
Public Member Functions
Aff_transformation_2 ()
Aff_transformation_2 (const CGAL::Aff_transformation_2< R > &t)
Aff_transformation_2 (const RAff_transformation_2 &t)
Aff_transformation_2 (const Identity_transformation tag)
Aff_transformation_2 (const Translation tag, const CGAL::Vector_2< R > &v)
Aff_transformation_2 (const Rotation tag, const CGAL::Direction_2< R > &d, const RT &num, const RT &den=RT(1))
Aff_transformation_2 (const Rotation tag, const RT &sin, const RT &cos, const RT &den=RT(1))
Aff_transformation_2 (const Reflection tag, const CGAL::Line_2< R > &l)
Aff_transformation_2 (const Scaling tag, const RT &s, const RT &w=RT(1))
Aff_transformation_2 (const RT &m11, const RT &m12, const RT &m13, const RT &m21, const RT &m22, const RT &m23, const RT &w=RT(1))
Aff_transformation_2 (const RT &m11, const RT &m12, const RT &m21, const RT &m22, const RT &w=RT(1))
~Aff_transformation_2 ()
CGAL::Point_2< R > transform (const CGAL::Point_2< R > &p) const
CGAL::Point_2< R > operator() (const CGAL::Point_2< R > &p) const
CGAL::Vector_2< R > transform (const CGAL::Vector_2< R > &v) const
CGAL::Vector_2< R > operator() (const CGAL::Vector_2< R > &v) const
CGAL::Direction_2< R > transform (const CGAL::Direction_2< R > &d) const
CGAL::Direction_2< R > operator() (const CGAL::Direction_2< R > &d) const
CGAL::Line_2< R > transform (const CGAL::Line_2< R > &l) const
CGAL::Line_2< R > operator() (const CGAL::Line_2< R > &l) const
CGAL::Aff_transformation_2< R > inverse () const
bool is_even () const
bool is_odd () const
CGAL::Aff_transformation_2< R > operator* (const CGAL::Aff_transformation_2< R > &t) const
FT cartesian (int i, int j) const
RT homogeneous (int i, int j) const
FT m (int i, int j) const
RT hm (int i, int j) const
Detailed Description
template<class R_>
class Aff_transformation_2< R_ >
Definition at line 87 of file Aff_transformation_2.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 92 of file Aff_transformation_2.h.
typedef R_ R
Definition at line 90 of file Aff_transformation_2.h.
typedef R::Aff_transformation_2_base RAff_transformation_2
Definition at line 95 of file Aff_transformation_2.h.
typedef R::Direction_2_base RDirection_2
Definition at line 94 of file Aff_transformation_2.h.
typedef R::Line_2_base RLine_2
Definition at line 93 of file Aff_transformation_2.h.
typedef R::RT RT
Definition at line 91 of file Aff_transformation_2.h.
Constructor & Destructor Documentation
Aff_transformation_2 () inline
Definition at line 98 of file Aff_transformation_2.h.
     : RAff_transformation_2()
   {}
Aff_transformation_2 (const CGAL::Aff_transformation_2< R > & t) inline
Definition at line 103 of file Aff_transformation_2.h.
     : RAff_transformation_2(t)
   {}
Aff_transformation_2 (const RAff_transformation_2< R_ > & t) inline
Definition at line 108 of file Aff_transformation_2.h.
     : RAff_transformation_2(t)
   {}
Aff_transformation_2 (const Identity_transformation tag) inline
Definition at line 113 of file Aff_transformation_2.h.
     : RAff_transformation_2(tag)
   {}
Aff_transformation_2 (const Translation tag, const CGAL::Vector_2< R > & v) inline
Definition at line 118 of file Aff_transformation_2.h.
     : RAff_transformation_2(tag, v)
   {}
Aff_transformation_2 (const Rotation tag, const CGAL::Direction_2< R > & d, const RT & num, const RT & den = RT(1)) inline
Definition at line 124 of file Aff_transformation_2.h.
     : RAff_transformation_2(tag, RDirection_2(d), num, den)
   {}
Aff_transformation_2 (const Rotation tag, const RT & sin, const RT & cos, const RT & den = RT(1)) inline
Definition at line 131 of file Aff_transformation_2.h.
     : RAff_transformation_2(tag, sin, cos, den)
   {}
Aff_transformation_2 (const Reflection tag, const CGAL::Line_2< R > & l) inline
Definition at line 139 of file Aff_transformation_2.h.
     : RAff_transformation_2(tag, l)
   {}
Aff_transformation_2 (const Scaling tag, const RT & s, const RT & w = RT(1)) inline
Definition at line 146 of file Aff_transformation_2.h.
     : RAff_transformation_2(tag, s, w)
   {}
Aff_transformation_2 (const RT & m11, const RT & m12, const RT & m13, const RT & m21, const RT & m22, const RT & m23, const RT & w = RT(1)) inline
Definition at line 153 of file Aff_transformation_2.h.
     : RAff_transformation_2(m11, m12, m13,
                             m21, m22, m23,
                                       w)
   {}
Aff_transformation_2 (const RT & m11, const RT & m12, const RT & m21, const RT & m22, const RT & w = RT(1)) inline
Definition at line 167 of file Aff_transformation_2.h.
     : RAff_transformation_2(m11, m12,
                             m21, m22,
                                       w)
   {}
~Aff_transformation_2 () inline
Definition at line 175 of file Aff_transformation_2.h.
   {}
Member Function Documentation
FT cartesian (int i, int j) const inline
Definition at line 224 of file Aff_transformation_2.h.
               { return RAff_transformation_2::cartesian(i,j); }
RT hm (int i, int j) const inline
Definition at line 230 of file Aff_transformation_2.h.
               { return RAff_transformation_2::hm(i,j); }
RT homogeneous (int i, int j) const inline
Definition at line 226 of file Aff_transformation_2.h.
               { return RAff_transformation_2::homogeneous(i,j); }
CGAL::Aff_transformation_2<R> inverse () const inline
Definition at line 211 of file Aff_transformation_2.h.
                       { return RAff_transformation_2::inverse(); }
bool is_even () const inline
Definition at line 214 of file Aff_transformation_2.h.
Referenced by Aff_transformation_2< R_ >::is_odd().
                       { return RAff_transformation_2::is_even(); }
bool is_odd () const inline
Definition at line 217 of file Aff_transformation_2.h.
References Aff_transformation_2< R_ >::is_even().
                       { return !is_even(); }
FT m (int i, int j) const inline
Definition at line 228 of file Aff_transformation_2.h.
Referenced by rflu_modrepair3d::cavbnd(), rflu_modrepair3d::cavity(), checkindxrange(), rflu_modrepair3d::colaps(), createk(), createm(), cst_coh(), spec_rflu_modchemistry::drate_stiff(), enforcethermalbc(), get_fint(), implicit_bc_enforce(), implicit_initialize(), implicit_soln(), implicit_v3d8_me_k(), initk(), rflu_modrepair3d::insert(), intload(), ktinitcrs(), ktnumnnz(), rflu_modrepair3d::lock(), locthermstiff_v3d8(), matmul2(), modsortsearch::mergesortedintegers(), mixtperf_r_m(), rflu_modrepair3d::neighb(), newcommlist(), numknnz(), partition_ceff(), data_py::polin2(), prescribedload(), modrandom::randuniform(), spec_rflu_modchemistry::rate_stiff(), read_frac(), read_io_files(), rflu_modrepair3d::recon(), removebcht_newtemp(), removebcht_reff(), removebcs_meff(), removebcs_newa(), removebcs_pbar(), rflu_modrepair3d::replace(), rflo_extrapintcellscal(), rflo_extrapintcellvec(), rflu_computeintegral1oles(), rflu_computeintegral3oles(), rflu_computeintegral4oles(), rflu_computeintegral5oles(), rflu_modweights::rflu_computewtsx2c_1d(), rflu_modoles::rflu_definecorrelation430(), rflu_modoles::rflu_definecorrelation431(), rflu_modoles::rflu_definecorrelation432(), rflu_modoles::rflu_definecorrelation540(), rflu_modoles::rflu_definecorrelation541(), rflu_modoles::rflu_definecorrelation542(), rflu_modoles::rflu_geti4posoles(), rflu_modbessel::rflu_jyndd(), rflu_modbessel::rflu_jyzom(), rflu_modoles::rflu_mapm2ijkl(), rflu_modoctree::rflu_queryoctree(), rflu_readintegrals1245oles(), rflu_modoles::rflu_setmapfunnz2funcorr43(), rflu_modoles::rflu_setmapfunnz2funcorr44(), rflu_writeintegrals1245oles(), modsortsearch::simplifysortedintegers(), summary(), tensormul(), thermal_initialize(), thermal_soln(), tql1(), tql2(), turb_checkparaminput(), turb_floextrapintcellscal(), turb_floextrapintcellvec(), turb_floextrapolcellvec(), turb_floextrapolfacevec(), turb_flolesgenc2f(), turb_ranswalldistovpatch(), turb_statccollector(), v3d10_capacitance(), v3d10_mass(), v3d4_capacitance(), v3d4_mass(), and v3d4n_mass().
               { return RAff_transformation_2::m(i,j); }
CGAL::Point_2<R> operator() (const CGAL::Point_2< R > & p) const inline
Definition at line 181 of file Aff_transformation_2.h.
References Aff_transformation_2< R_ >::transform().
                       { return transform(p); }
CGAL::Vector_2<R> operator() (const CGAL::Vector_2< R > & v) const inline
Definition at line 187 of file Aff_transformation_2.h.
References Aff_transformation_2< R_ >::transform().
                       { return transform(v); }
CGAL::Direction_2<R> operator() (const CGAL::Direction_2< R > & d) const inline
Definition at line 193 of file Aff_transformation_2.h.
References Aff_transformation_2< R_ >::transform().
                       { return transform(d); }
CGAL::Line_2<R> operator() (const CGAL::Line_2< R > & l) const inline
Definition at line 206 of file Aff_transformation_2.h.
References Aff_transformation_2< R_ >::transform().
                       { return transform(l); }
CGAL::Aff_transformation_2<R> operator* (const CGAL::Aff_transformation_2< R > & t) const inline
Definition at line 221 of file Aff_transformation_2.h.
References operator*().
                       { return RAff_transformation_2::operator*(t); }
CGAL::Point_2<R> transform (const CGAL::Point_2< R > & p) const inline
Definition at line 178 of file Aff_transformation_2.h.
Referenced by Aff_transformation_2< R_ >::operator()().
                       { return RAff_transformation_2::transform(p); }
CGAL::Vector_2<R> transform (const CGAL::Vector_2< R > & v) const inline
Definition at line 184 of file Aff_transformation_2.h.
                       { return RAff_transformation_2::transform(v); }
CGAL::Direction_2<R> transform (const CGAL::Direction_2< R > & d) const inline
Definition at line 190 of file Aff_transformation_2.h.
                       { return RAff_transformation_2::transform(d); }
CGAL::Line_2<R> transform (const CGAL::Line_2< R > & l) const inline
Definition at line 196 of file Aff_transformation_2.h.
   {
 #ifndef CGAL_NO_LINE_TRANSFORM_IN_AT
                         return RAff_transformation_2::transform(l);
 #else
                         return
       ((const RLine_2&)l).transform((const RAff_transformation_2&)(*this));
 #endif // CGAL_NO_LINE_TRANSFORM_IN_AT
                       }
The documentation for this class was generated from the following file:
Aff_transformation_2.h