Rocstar: fdoutbuf Class Reference
fdoutbuf Class Reference
#include <FDUtils.H>
Public Member Functions
fdoutbuf ()
fdoutbuf (int _fd)
void Init (int _fd)
bool Ready ()
virtual int FD ()
Protected Member Functions
virtual int_type overflow (int_type c)
virtual std::streamsize xsputn (const char *s, std::streamsize num)
Protected Attributes
int fd
Detailed Description
Definition at line 33 of file FDUtils.H.
Constructor & Destructor Documentation
fdoutbuf () inline
Definition at line 37 of file FDUtils.H.
References fdoutbuf::fd.
 { fd = -1; };
fdoutbuf (int _fd) inline
Definition at line 39 of file FDUtils.H.
                          : fd(_fd) {
       }
Member Function Documentation
virtual int FD () inline virtual
Definition at line 43 of file FDUtils.H.
References fdoutbuf::fd.
Referenced by fdostream::FD(), and fdostream::Init().
 { return fd; };
void Init (int _fd) inline
Definition at line 41 of file FDUtils.H.
References fdoutbuf::fd.
Referenced by fdostream::Init().
 { fd = _fd; };
virtual int_type overflow (int_type c) inline protected virtual
Definition at line 46 of file FDUtils.H.
References fdoutbuf::fd, write(), and z.
{
         if (c != EOF) {
           char z = c;
           if (write (fd, &z, 1) != 1) {
             return EOF;
           }
         }
         return c;
       }
bool Ready () inline
Definition at line 42 of file FDUtils.H.
References fdoutbuf::fd.
 { return(fd >= 0); };
virtual std::streamsize xsputn (const char * s, std::streamsize num) inline protected virtual
Definition at line 57 of file FDUtils.H.
References fdoutbuf::fd, and write().
{
         return write(fd,s,num);
       }
Member Data Documentation
int fd protected
Definition at line 35 of file FDUtils.H.
Referenced by fdoutbuf::FD(), fdoutbuf::fdoutbuf(), fdoutbuf::Init(), fdoutbuf::overflow(), fdoutbuf::Ready(), and fdoutbuf::xsputn().
The documentation for this class was generated from the following file:
FDUtils.H