Rocstar: datafile Class Reference
datafile Class Reference
Base class for file parsing.
#include <file.h>
Public Member Functions
datafile (ifstream &infile, ofstream &outfile, bool loud, string filename, int dim, std::vector< std::vector< int > > rFieldMappings, std::vector< index_order > rIndexOrder, std::vector< adj_map > conv_factor, std::vector< adj_map > norm_val)
Construct data file object using specified information.
virtual string get_mod_name ()
Get class name.
virtual ~datafile ()
Free used data, delete the object.
datafile (const datafile &d)
Deep copy constructor.
virtual void parse ()
Parse the data file.
int partition_layout (int partition, int n)
Get the size of n dimension of the specified partition.
points * get_points (int partition)
Get a partitions' points.
pnt get_point (int n)
Get the nth point of the file.
pnt get_point (int n, int partition)
Get the nth point of the specified partition.
int get_num_points ()
Get the number of points in the file.
int get_num_points (int partition)
Get the number of points in the specified partition.
int get_num_vars ()
Get the number of variables in the file.
string get_title ()
Get file title if specified in file header.
int get_num_partitions ()
Get number of partition in the file.
Protected Member Functions
void error_out (string err_ps)
Log the string specified as an error event.
void status_out (string st_ps)
Log the string specified as a status event.
void LogFieldMappings ()
Log the field mapping data from the command line and stored in mFieldMappings.
int get_num_dep_vars ()
Get number of dependent variables.
index_order get_index_order (int partition)
Protected Attributes
string filename
ifstream & infile
ofstream & outfile
bool loud
partition ** data_part
int num_partitions
std::vector< string > var_names
string title
int dimensions
std::vector< adj_map > conv_factor
std::vector< adj_map > norm_val
std::vector< std::vector< int > > mFieldMappings
std::vector< index_order > mIndexOrder
Private Attributes
int dep_vars
Detailed Description
Base class for file parsing.
Definition at line 32 of file file.h.
Constructor & Destructor Documentation
datafile (ifstream & infile, ofstream & outfile, bool loud, string filename, int dim, std::vector< std::vector< int > > rFieldMappings, std::vector< index_order > rIndexOrder, std::vector< adj_map > conv_factor, std::vector< adj_map > norm_val)
Construct data file object using specified information.
Parameters
infile Input file stream
outfile Log file stream
loud Log verbosity
filename Name of the input file
dim Number of dimensions in the input file
rFieldMappings Mappings of file variables to internal representation variables
rIndexOrder The order of variables for index creation (for each partition)
conv_factor Factors multiplied with corresponding variables in order to convert values with difference units
norm_val Values multiplied with corresponding variables in order to reverse normalization
Definition at line 5 of file file.cpp.
References conv_factor, dep_vars, dimensions, filename, loud, mFieldMappings, mIndexOrder, norm_val, and num_partitions.
     : infile(infile), outfile(outfile) {
     this->loud = loud;
     this->filename = filename;
     this->conv_factor = conv_factor;
     this->norm_val = norm_val;
     this->mFieldMappings = rFieldMappings;
     this->num_partitions = -1;
     this->dep_vars = 0;
     this->dimensions = dim;
     this->mIndexOrder = rIndexOrder;
     //Seek to beginning of file
     infile.clear();
     infile.seekg(0, std::ios::beg);
 }
~datafile () virtual
Free used data, delete the object.
Definition at line 30 of file file.cpp.
References data_part, i, and num_partitions.
                    {
     if(num_partitions > 0){
         for(int i=0; i<num_partitions; i++)
             delete data_part[i];
         delete[] data_part;
     }
 }
datafile (const datafile & d)
Deep copy constructor.
Parameters
d Datafile to copy
Definition at line 40 of file file.cpp.
References dep_vars, filename, loud, num_partitions, title, and var_names.
     : infile(d.infile), outfile(d.outfile) {
     filename = d.filename;
     loud = d.loud;
     num_partitions = d.num_partitions;
     title = d.title;
     dep_vars = d.dep_vars;
     var_names = d.var_names;
 }
Member Function Documentation
void error_out (string err_ps) protected
Log the string specified as an error event.
Parameters
err_ps Error message
Definition at line 65 of file file.cpp.
References filename, and outfile.
Referenced by tecplot_data::parse(), and tecplot_data::zone_error_out().
{
     outfile << "ERROR   |  File \"" << this->filename << "\":  " << err_ps << std::endl;
     cout << "ERROR   |  File \"" << this->filename << "\":  " << err_ps << std::endl;
 }
index_order get_index_order (int partition) protected
Definition at line 167 of file file.cpp.
References empty(), and mIndexOrder.
Referenced by tecplot_data::parse().
{
     for(int record_num = 0; record_num < mIndexOrder.size(); record_num++){
         if(mIndexOrder[record_num].partition_number == partition){
             return mIndexOrder[record_num];
         }
     }
     index_order empty;
     return empty;
 }
string get_mod_name () virtual
Get class name.
Returns
Name of the class (datafile)
Reimplemented in tecplot_data.
Definition at line 53 of file file.cpp.
Referenced by parse().
{
     return string("Datafile");
 }
int get_num_dep_vars () protected
Get number of dependent variables.
Returns
Number of dependent variables
Definition at line 163 of file file.cpp.
References dimensions, and var_names.
Referenced by tecplot_data::parse().
{
     return var_names.size() - dimensions;
 }
int get_num_partitions ()
Get number of partition in the file.
Returns
Number of partitions
Definition at line 151 of file file.cpp.
References num_partitions.
Referenced by get_points(), and retrievePoints().
{
     return num_partitions;
 }
int get_num_points ()
Get the number of points in the file.
Returns
Number of points in file
Definition at line 130 of file file.cpp.
References data_part, partition::get_num_points(), i, and num_partitions.
Referenced by get_point().
{
     int ret = 0;
     //Get number of points of each partition
     for(int i=0; i<num_partitions; i++){
         if(data_part[i] != NULL)
             ret += data_part[i]->get_num_points();
     }
     return ret;
 }
int get_num_points (int partition)
Get the number of points in the specified partition.
Parameters
partition Partition number
Returns
Number of points in partition
Definition at line 143 of file file.cpp.
References data_part, and partition::get_num_points().
{
     if(data_part[partition] != NULL)
         return data_part[partition]->get_num_points();
     else
         return 0;
 }
int get_num_vars ()
Get the number of variables in the file.
Returns
Number of variables
Definition at line 159 of file file.cpp.
References var_names.
Referenced by tecplot_data::parse().
{
     return var_names.size();
 }
pnt get_point (int n)
Get the nth point of the file.
Parameters
n Point to retrieve
Returns
nth point of the entire file
Definition at line 111 of file file.cpp.
References data_part, partition::get_num_points(), get_num_points(), partition::get_point(), i, and num_partitions.
{
     //Calculate the correct partition
     int i;
     for(i=0; i<num_partitions; i++){
         if(data_part[i]->get_num_points() > n)
             break;
         n = n - data_part[i]->get_num_points();
     }
     //Retrieve point from partition
     return data_part[i]->get_point(n);
 }
pnt get_point (int n, int partition)
Get the nth point of the specified partition.
Parameters
n Point number
partition Partition number
Returns
nth point of partition
Definition at line 126 of file file.cpp.
References data_part, and partition::get_point().
{
     return data_part[partition]->get_point(n);
 }
points * get_points (int partition)
Get a partitions' points.
Parameters
partition Partition number
Returns
Points of the specified partition
Definition at line 100 of file file.cpp.
References data_part, get_num_partitions(), and partition::get_points().
Referenced by compareFiles(), and retrievePoints().
{
     if(partition >= get_num_partitions())
         return NULL;
     return data_part[partition]->get_points();
 }
string get_title ()
Get file title if specified in file header.
Returns
File title
Definition at line 155 of file file.cpp.
References title.
{
     return title;
 }
void LogFieldMappings () protected
Log the field mapping data from the command line and stored in mFieldMappings.
Definition at line 79 of file file.cpp.
References itoa(), mFieldMappings, and status_out().
Referenced by tecplot_data::read_header().
{
     for(int field=0; field<mFieldMappings.size(); field++){
         string st_out = string("Mapping VAR ");
         st_out += itoa(mFieldMappings[field][0]);
         st_out += " -> VAR ";
         st_out += itoa(mFieldMappings[field][1]);
         status_out(st_out);
     }
 }
void parse () virtual
Parse the data file.
Non functional, meant to be overriden by subclasses.
Reimplemented in tecplot_data.
Definition at line 57 of file file.cpp.
References get_mod_name(), and status_out().
Referenced by openAndParseFiles().
                     {
     //Print status
     status_out(get_mod_name());
     return;
 }
int partition_layout (int partition, int n)
Get the size of n dimension of the specified partition.
Parameters
partition Partition number
n Dimension number
Returns
Size of n in partition
Definition at line 90 of file file.cpp.
References data_part, and partition::get_layout().
{
     if(data_part[partition] != NULL)
         return data_part[partition]->get_layout()[n];
     else
         return 0;
 }
void status_out (string st_ps) protected
Log the string specified as a status event.
Parameters
st_ps Status message
Definition at line 70 of file file.cpp.
References filename, loud, and outfile.
Referenced by LogFieldMappings(), parse(), tecplot_data::parse(), tecplot_data::read_header(), and tecplot_data::zone_status_out().
{
     if(loud){
         outfile << "status  |  File \"" << this->filename << "\":  " << st_ps << std::endl;
     }
 }
Member Data Documentation
std::vector<adj_map> conv_factor protected
Definition at line 182 of file file.h.
Referenced by datafile(), and tecplot_data::parse().
partition** data_part protected
Definition at line 164 of file file.h.
Referenced by get_num_points(), get_point(), get_points(), tecplot_data::parse(), partition_layout(), and ~datafile().
int dep_vars private
Definition at line 191 of file file.h.
Referenced by datafile().
int dimensions protected
Definition at line 179 of file file.h.
Referenced by datafile(), and get_num_dep_vars().
string filename protected
Definition at line 138 of file file.h.
Referenced by datafile(), error_out(), and status_out().
ifstream& infile protected
Definition at line 141 of file file.h.
Referenced by tecplot_data::count_zones(), tecplot_data::get_zone_header(), tecplot_data::get_zone_nodes(), tecplot_data::parse(), tecplot_data::read_header(), and tecplot_data::seek_to_zone().
bool loud protected
Definition at line 143 of file file.h.
Referenced by datafile(), and status_out().
std::vector< std::vector<int> > mFieldMappings protected
Definition at line 186 of file file.h.
Referenced by datafile(), LogFieldMappings(), and tecplot_data::parse().
std::vector<index_order> mIndexOrder protected
Definition at line 197 of file file.h.
Referenced by datafile(), and get_index_order().
std::vector<adj_map> norm_val protected
Definition at line 183 of file file.h.
Referenced by datafile(), and tecplot_data::parse().
int num_partitions protected
Definition at line 167 of file file.h.
Referenced by datafile(), get_num_partitions(), get_num_points(), get_point(), tecplot_data::get_zone_nodes(), tecplot_data::parse(), and ~datafile().
ofstream& outfile protected
Definition at line 142 of file file.h.
Referenced by error_out(), and status_out().
string title protected
Definition at line 169 of file file.h.
Referenced by datafile(), get_title(), and tecplot_data::read_header().
std::vector<string> var_names protected
Definition at line 168 of file file.h.
Referenced by datafile(), get_num_dep_vars(), get_num_vars(), and tecplot_data::read_header().
The documentation for this class was generated from the following files:
file.h
file.cpp