Rocstar: DirectionS2< FT > Class Template Reference
DirectionS2< FT > Class Template Reference
#include <DirectionS2.h>
Public Member Functions
DirectionS2 ()
DirectionS2 (const VectorS2< FT > &v)
DirectionS2 (const FT &x, const FT &y)
bool operator== (const DirectionS2< FT > &d) const
bool operator!= (const DirectionS2< FT > &d) const
bool operator>= (const DirectionS2< FT > &d) const
bool operator<= (const DirectionS2< FT > &d) const
bool operator> (const DirectionS2< FT > &d) const
bool operator< (const DirectionS2< FT > &d) const
bool counterclockwise_in_between (const DirectionS2< FT > &d1, const DirectionS2< FT > &d2) const
VectorS2< FT > vector () const
DirectionS2< FT > perpendicular (const Orientation &o) const
DirectionS2< FT > transform (const Aff_transformationS2< FT > &t) const
DirectionS2< FT > operator- () const
FT delta (int i) const
FT dx () const
FT dy () const
Public Attributes
FT e0
FT e1
Detailed Description
template<class FT>
class DirectionS2< FT >
Definition at line 59 of file DirectionS2.h.
Constructor & Destructor Documentation
CGAL_KERNEL_CTOR_INLINE DirectionS2 ()
Definition at line 94 of file DirectionS2.h.
 {}
CGAL_KERNEL_CTOR_INLINE DirectionS2 (const VectorS2< FT > & v)
Definition at line 98 of file DirectionS2.h.
References VectorS2< FT >::e0, and VectorS2< FT >::e1.
 { e0 = v.e0; e1 = v.e1; }
CGAL_KERNEL_CTOR_INLINE DirectionS2 (const FT & x, const FT & y)
Definition at line 103 of file DirectionS2.h.
References x, and y.
 { e0 = x; e1 = y; }
Member Function Documentation
CGAL_KERNEL_INLINE bool counterclockwise_in_between (const DirectionS2< FT > & d1, const DirectionS2< FT > & d2) const
Definition at line 161 of file DirectionS2.h.
 {
   if ( d1 < *this)
   {
       return ( *this < d2 )||( d2 <= d1 );
   }
   else
   {
       return ( *this < d2 )&&( d2 <= d1 );
   }
 }
CGAL_KERNEL_INLINE FT delta (int i) const
Definition at line 207 of file DirectionS2.h.
References CGAL_kernel_precondition.
 {
   CGAL_kernel_precondition( ( i == 0 ) || ( i == 1 ) );
   return (i==0) ? dx() : dy();
 }
FT dx () const inline
Definition at line 217 of file DirectionS2.h.
Referenced by LineS2< FT >::LineS2(), DirectionS2< FT >::operator<(), and DirectionS2< FT >::operator==().
 { return e0; }
FT dy () const inline
Definition at line 223 of file DirectionS2.h.
Referenced by LineS2< FT >::LineS2(), DirectionS2< FT >::operator<(), and DirectionS2< FT >::operator==().
 { return e1; }
bool operator!= (const DirectionS2< FT > & d) const inline
Definition at line 119 of file DirectionS2.h.
 { return !( *this == d ); }
DirectionS2< FT > operator- () const inline
Definition at line 199 of file DirectionS2.h.
 { return DirectionS2<FT>(-dx(), -dy()); }
CGAL_KERNEL_MEDIUM_INLINE bool operator< (const DirectionS2< FT > & d) const
Definition at line 125 of file DirectionS2.h.
References DirectionS2< FT >::dx(), and DirectionS2< FT >::dy().
 {
   int quadrant_this = (dx() >= FT(0)) ? ((dy() >= FT(0))?1:4)
                                       : ((dy() >= FT(0))?2:3);
   int quadrant_d    = (d.dx() >= FT(0)) ? ((d.dy() >= FT(0))?1:4)
                                         : ((d.dy() >= FT(0))?2:3);
   if(quadrant_this < quadrant_d)
     return true;
   else if (quadrant_this > quadrant_d)
     return false;
   else
     return dy() * d.dx() < d.dy() * dx();
 }
CGAL_KERNEL_INLINE bool operator<= (const DirectionS2< FT > & d) const
Definition at line 155 of file DirectionS2.h.
 { return (*this < d) || (d == *this) ; }
bool operator== (const DirectionS2< FT > & d) const
Definition at line 108 of file DirectionS2.h.
References CGAL_NTS, DirectionS2< FT >::dx(), DirectionS2< FT >::dy(), and sign().
 {
 // Use a S2 predicate for that ?
     return (CGAL_NTS sign(dx()) == CGAL_NTS sign(d.dx()))
         && (CGAL_NTS sign(dy()) == CGAL_NTS sign(d.dy()))
         && (dy()*d.dx() == d.dy()*dx());
 }
CGAL_KERNEL_INLINE bool operator> (const DirectionS2< FT > & d) const
Definition at line 143 of file DirectionS2.h.
 { return d < *this ; }
CGAL_KERNEL_INLINE bool operator>= (const DirectionS2< FT > & d) const
Definition at line 149 of file DirectionS2.h.
 { return (d < *this) || (d == *this) ; }
CGAL_KERNEL_MEDIUM_INLINE DirectionS2< FT > perpendicular (const Orientation & o) const
Definition at line 183 of file DirectionS2.h.
References CGAL_kernel_precondition, COLLINEAR, and COUNTERCLOCKWISE.
 {
   CGAL_kernel_precondition(o != COLLINEAR);
   if (o == COUNTERCLOCKWISE)
     return DirectionS2<FT>(-dy(), dx());
   else
     return DirectionS2<FT>(dy(), -dx());
 }
CGAL_KERNEL_INLINE DirectionS2< FT > transform (const Aff_transformationS2< FT > & t) const
Definition at line 194 of file DirectionS2.h.
References Aff_transformationS2< FT >::transform().
 { return t.transform(*this); }
VectorS2< FT > vector () const inline
Definition at line 177 of file DirectionS2.h.
Referenced by RayS2< FT >::RayS2(), Rotation_repS2< FT >::Rotation_repS2(), Aff_transformation_repS2< FT >::transform(), and Rotation_repS2< FT >::transform().
 { return VectorS2<FT>(*this); }
Member Data Documentation
FT e0
Definition at line 87 of file DirectionS2.h.
Referenced by VectorS2< FT >::hx(), VectorS2< FT >::VectorS2(), and VectorS2< FT >::x().
FT e1
Definition at line 88 of file DirectionS2.h.
Referenced by VectorS2< FT >::hy(), VectorS2< FT >::VectorS2(), and VectorS2< FT >::y().
The documentation for this class was generated from the following file:
DirectionS2.h