Rocstar: Kdtree_d< Traits >::ExtPoint Class Reference
Kdtree_d< Traits >::ExtPoint Class Reference
#include <kdtree_d.h>
Classes
class coordinate_type
Public Types
enum { MINUS_INFINITY = -1, FINITE = 0, PLUS_INFINITY = 1 }
Public Member Functions
ExtPoint (int _type, int _dim)
ExtPoint ()
ExtPoint (const ExtPoint &p)
ExtPoint & operator= (const ExtPoint &p)
ExtPoint (const Point &point, int dim)
void term ()
~ExtPoint ()
void set_coord (int k, Point &point)
void set_coord (int k, const ExtPoint &point)
int compare (int k, const ExtPoint &point) const
int compare_vector (const ExtPoint &point) const
int compare (int k, const Point &point) const
int dimension () const
int get_coord_status (int d) const
const Point * get_coord_point (int d) const
Private Member Functions
void init (int _dim)
Private Attributes
coordinate_type * p_arr
int dim
Point def_pnt
Detailed Description
template<class Traits>
class Kdtree_d< Traits >::ExtPoint
Definition at line 152 of file kdtree_d.h.
Member Enumeration Documentation
anonymous enum
Enumerator
MINUS_INFINITY
FINITE
PLUS_INFINITY
Definition at line 181 of file kdtree_d.h.
 { MINUS_INFINITY = -1, FINITE = 0, PLUS_INFINITY = 1 };
Constructor & Destructor Documentation
ExtPoint (int _type, int _dim) inline
Definition at line 183 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::init(), Kdtree_d< Traits >::ExtPoint::MINUS_INFINITY, Kdtree_d< Traits >::ExtPoint::p_arr, and Kdtree_d< Traits >::ExtPoint::PLUS_INFINITY.
     {
       assert( _type == MINUS_INFINITY  ||  _type == PLUS_INFINITY );
       init( _dim );
       for  ( int  ind = 0; ind < dim; ind++ )
         p_arr[ ind ].type = _type;
     }
ExtPoint () inline
Definition at line 192 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::dim, and Kdtree_d< Traits >::ExtPoint::p_arr.
     {
       p_arr = NULL;
       dim = -1;
     }
ExtPoint (const ExtPoint & p) inline
Definition at line 198 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::def_pnt, Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::init(), Kdtree_d< Traits >::ExtPoint::p_arr, and Kdtree_d< Traits >::ExtPoint::coordinate_type::p_pnt.
     {
       init( p.dim );
       def_pnt = p.def_pnt;
       for  ( int  ind = 0; ind < dim; ind++ ) {
         p_arr[ ind ] = p.p_arr[ ind ];
         if  ( p.p_arr[ ind ].p_pnt == &p.def_pnt )
           p_arr[ ind ].p_pnt = &def_pnt;
       }
     }
ExtPoint (const Point & point, int dim) inline
Definition at line 226 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::def_pnt, Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::FINITE, Kdtree_d< Traits >::ExtPoint::init(), Kdtree_d< Traits >::ExtPoint::p_arr, Kdtree_d< Traits >::ExtPoint::coordinate_type::p_pnt, and Kdtree_d< Traits >::ExtPoint::coordinate_type::type.
     {
       init( dim );
       def_pnt = point;
       for  ( int  ind = 0; ind < dim; ind++ ) {
         p_arr[ ind ].p_pnt = &def_pnt;
         p_arr[ ind ].type = FINITE;
       }
     }
~ExtPoint () inline
Definition at line 248 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::term().
     {
       term();
     }
Member Function Documentation
int compare (int k, const ExtPoint & point) const inline
Definition at line 276 of file kdtree_d.h.
References CGAL::compare(), Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::FINITE, k, Kdtree_d< Traits >::ExtPoint::p_arr, Kdtree_d< Traits >::ExtPoint::coordinate_type::p_pnt, and Kdtree_d< Traits >::ExtPoint::coordinate_type::type.
Referenced by Kdtree_d< Traits >::ExtPoint::compare_vector(), Kdtree_d< Traits >::Box::intersect(), Kdtree_d< Traits >::Box::is_coord_in_range(), Kdtree_d< Traits >::Box::is_empty(), Kdtree_d< Traits >::Box::is_empty_open(), Kdtree_d< Traits >::Box::is_in(), Kdtree_d< Traits >::Box::is_intersect(), Kdtree_d< Traits >::Box::is_intersect_in_dim(), Kdtree_d< Traits >::Box::is_intersect_in_dim_closed(), and Kdtree_d< Traits >::Node::Plane::split().
     {
       assert( 0 <= k  &&  k < dim );
       // the following does not compile on msvc++...
       //            coordinate_type  & a( p_arr[ k ] ),
       //  & b( point.p_arr[ k ] );
       coordinate_type & a = p_arr[ k ];
       coordinate_type & b = point.p_arr[ k ];
       if  ( a.type != FINITE ) {
         if  ( b.type != FINITE ) {
           return  a.type - b.type;
         } else {
           return  a.type;
         }
       } else {
         if  ( b.type != FINITE )
           return  -b.type;
         else
           return  Traits::compare( k, *a.p_pnt, *b.p_pnt );
       }
     }
int compare (int k, const Point & point) const inline
Definition at line 313 of file kdtree_d.h.
References CGAL::compare(), Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::FINITE, k, Kdtree_d< Traits >::ExtPoint::p_arr, Kdtree_d< Traits >::ExtPoint::coordinate_type::p_pnt, and Kdtree_d< Traits >::ExtPoint::coordinate_type::type.
     {
       assert( 0 <= k  &&  k < dim );
       //            coordinate_type  & a( p_arr[ k ] );
       coordinate_type  & a = p_arr[ k ];
       if  ( a.type != FINITE )
         return  a.type;
       else
         return  Traits::compare( k, *a.p_pnt, point );
     }
int compare_vector (const ExtPoint & point) const inline
Definition at line 300 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), and Kdtree_d< Traits >::ExtPoint::dim.
Referenced by Kdtree_d< Traits >::Box::comp().
     {
       int  ind, res;
       for  ( ind = 0; ind < dim; ind++ ) {
         res = compare( ind, point );
         if  ( res != 0 )
           return  res;
       }
       return  0;
     }
int dimension () const inline
Definition at line 326 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::dim.
Referenced by Kdtree_d< Traits >::Box::intersect(), Kdtree_d< Traits >::Box::is_empty(), Kdtree_d< Traits >::Box::is_empty_open(), Kdtree_d< Traits >::Box::is_in(), and Kdtree_d< Traits >::Box::is_intersect().
     {
       return  dim;
     }
const Point* get_coord_point (int d) const inline
Definition at line 339 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::p_arr, and Kdtree_d< Traits >::ExtPoint::coordinate_type::p_pnt.
     {
       assert( 0 <= d  &&  d < dim );
       return  p_arr[ d ].p_pnt;
     }
int get_coord_status (int d) const inline
Definition at line 331 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::p_arr, and Kdtree_d< Traits >::ExtPoint::coordinate_type::type.
     {
       assert( 0 <= d  &&  d < dim );
       return  p_arr[ d ].type;
     }
void init (int _dim) inline private
Definition at line 167 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::dim, and Kdtree_d< Traits >::ExtPoint::p_arr.
Referenced by Kdtree_d< Traits >::ExtPoint::ExtPoint(), and Kdtree_d< Traits >::ExtPoint::operator=().
     {
       assert( _dim > 0 );
       dim = _dim;
       p_arr = (coordinate_type *)malloc( sizeof( coordinate_type )
                                          * dim );
       //printf( "p_arr(new): %p\n", (void *)p_arr );
       assert( p_arr != NULL );
       memset( p_arr, 0, sizeof( coordinate_type ) * dim );
     }
ExtPoint& operator= (const ExtPoint & p) inline
Definition at line 210 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::def_pnt, Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::init(), Kdtree_d< Traits >::ExtPoint::p_arr, Kdtree_d< Traits >::ExtPoint::coordinate_type::p_pnt, and Kdtree_d< Traits >::ExtPoint::term().
     {
       term();
       init( p.dim );
       def_pnt = p.def_pnt;
       for  ( int  ind = 0; ind < dim; ind++ ) {
         p_arr[ ind ] = p.p_arr[ ind ];
         if  ( p.p_arr[ ind ].p_pnt == &p.def_pnt )
           p_arr[ ind ].p_pnt = &def_pnt;
       }
       return  *this;
     }
void set_coord (int k, Point & point) inline
Definition at line 253 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::def_pnt, Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::FINITE, k, Kdtree_d< Traits >::ExtPoint::p_arr, Kdtree_d< Traits >::ExtPoint::coordinate_type::p_pnt, and Kdtree_d< Traits >::ExtPoint::coordinate_type::type.
Referenced by Kdtree_d< Traits >::Box::intersect(), Kdtree_d< Traits >::Box::set_coord_left(), Kdtree_d< Traits >::Box::set_coord_right(), and Kdtree_d< Traits >::Node::Plane::split().
     {
       assert( 0 <= k  &&  k < dim );
       p_arr[ k ].type = FINITE;
       //p_arr[ k ].p_pnt = &point;
       Traits::copy_coord( k, def_pnt, point );
       p_arr[ k ].p_pnt =  &def_pnt;
     }
void set_coord (int k, const ExtPoint & point) inline
Definition at line 264 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::def_pnt, Kdtree_d< Traits >::ExtPoint::dim, Kdtree_d< Traits >::ExtPoint::FINITE, k, Kdtree_d< Traits >::ExtPoint::p_arr, and Kdtree_d< Traits >::ExtPoint::coordinate_type::p_pnt.
     {
       assert( 0 <= k  &&  k < dim );
       assert( 0 <= k  &&  k < point.dim );
       p_arr[ k ] = point.p_arr[ k ];
       if  ( p_arr[ k ].type == FINITE ) {
         Traits::copy_coord( k, def_pnt, *(p_arr[ k ].p_pnt) );
         p_arr[ k ].p_pnt =  &def_pnt;
       }
     }
void term () inline
Definition at line 237 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::dim, and Kdtree_d< Traits >::ExtPoint::p_arr.
Referenced by descalegridspeeds(), setup_py::grid(), Kdtree_d< Traits >::ExtPoint::operator=(), reflectposition(), reflectvector(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modgeometry::rflu_buildbvertexnormals(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_modgeometry::rflu_buildgeometry(), rflu_checkgridspeeds(), rflu_modgeometry::rflu_computeapproxcentroids(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_computeenerdissoles(), rflu_computeexactflowerror(), rflu_modexactflow::rflu_computeexactflowpacoust(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_moddifferentiationbfaces::rflu_computegradbfaces(), rflu_moddifferentiationcells::rflu_computegradcells_2d(), rflu_moddifferentiationcells::rflu_computegradcells_3d(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationcells::rflu_computegradcellsfast_2d(), rflu_moddifferentiationcells::rflu_computegradcellsfast_3d(), rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_moddifferentiationfaces::rflu_computegradfaces(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_computegridspeeds(), rflu_computeintegral3oles(), rflu_modlimiters::rflu_computelimiterbarthjesp(), rflu_modlimiters::rflu_computelimitervenkat(), rflu_modplottingvars::rflu_computeplottingvarsdisc(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_computeweightsoles(), rflu_modmesh3d::rflu_convmesh3d2rocflu(), rflu_modvgridns::rflu_convvgridns2rocflu(), rflu_modexplicitmultistage::rflu_ems_setdiss(), rflu_modexplicitmultistage::rflu_ems_updateconservedvars(), rflu_finishsd(), rflu_modfacelist::rflu_getopposingfaces(), rflu_modhashtable::rflu_hashbuildkey(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_modfacelist::rflu_insertintocell2facelist(), rflu_modinterpolation::rflu_interpcells2face(), rflu_modinterpolation::rflu_interpcells2facepatch(), rflu_modinterpolation::rflu_interpcells2faces(), rflu_invflux_i(), rflu_movegriddisp(), rflu_movegridxyz(), rflu_modpetscpoisson::rflu_petsc_buildpoisson(), rflu_modroeflux::rflu_roe_computefluxd1_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_setdependentvars(), rflu_modgridspeedutils::rflu_setgridspeedscalefactor(), rflu_modoles::rflu_setmapfunnz2funcorr43(), rflu_modoles::rflu_setmapfunnz2funcorr44(), rflu_setmovegridoptions(), rflu_modrindstates::rflu_setrindstateslipwallperf(), rflu_settransportvars(), rflu_modweno::rflu_wenogradcells_2d(), rflu_modweno::rflu_wenogradcells_3d(), rflu_modweno::rflu_wenogradcellsxyz_1d(), scalegridspeeds(), spec_eqeulcorr(), zn_gen_grid(), Kdtree_d< Traits >::Box::~Box(), and Kdtree_d< Traits >::ExtPoint::~ExtPoint().
     {
       if  ( p_arr != NULL ) {
         //printf( "a: %p\n", p_arr );
         free( p_arr );
         //printf( "_a\n" );
         p_arr = NULL;
       }
       dim = 0;
     }
Member Data Documentation
Point def_pnt private
Definition at line 165 of file kdtree_d.h.
Referenced by Kdtree_d< Traits >::ExtPoint::ExtPoint(), Kdtree_d< Traits >::ExtPoint::operator=(), and Kdtree_d< Traits >::ExtPoint::set_coord().
int dim private
Definition at line 164 of file kdtree_d.h.
Referenced by Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::ExtPoint::compare_vector(), Kdtree_d< Traits >::ExtPoint::dimension(), Kdtree_d< Traits >::ExtPoint::ExtPoint(), Kdtree_d< Traits >::ExtPoint::get_coord_point(), Kdtree_d< Traits >::ExtPoint::get_coord_status(), Kdtree_d< Traits >::ExtPoint::init(), Kdtree_d< Traits >::ExtPoint::operator=(), Kdtree_d< Traits >::ExtPoint::set_coord(), and Kdtree_d< Traits >::ExtPoint::term().
coordinate_type* p_arr private
Definition at line 163 of file kdtree_d.h.
Referenced by Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::ExtPoint::ExtPoint(), Kdtree_d< Traits >::ExtPoint::get_coord_point(), Kdtree_d< Traits >::ExtPoint::get_coord_status(), Kdtree_d< Traits >::ExtPoint::init(), Kdtree_d< Traits >::ExtPoint::operator=(), Kdtree_d< Traits >::ExtPoint::set_coord(), and Kdtree_d< Traits >::ExtPoint::term().
The documentation for this class was generated from the following file:
kdtree_d.h