Rocstar: MsqInterrupt Class Reference
MsqInterrupt Class Reference
Class to watch for user-interrupt (SIGINT, ctrl-C)
#include <MsqInterrupt.hpp>
Public Member Functions
MsqInterrupt ()
Constructor, increment instance count.
~MsqInterrupt ()
Constructor, decrement instance count.
MsqInterrupt ()
Constructor, increment instance count.
~MsqInterrupt ()
Constructor, decrement instance count.
Static Public Member Functions
static void disable (MsqError &err)
Disable Mesquite's SIGINT handler.
static void allow (MsqError &err)
Allow Mesquite to register a SIGINT handler.
static void enable (MsqError &err)
Force Mesquite to register SIGINT handler.
static bool interrupt ()
Check if an interrupt was seen.
static void clear ()
Clear the interrupt flag.
static void set_interrupt ()
Set the interrupt flag.
static void set_handler ()
static void disable (MsqError &err)
Disable Mesquite's SIGINT handler.
static void allow (MsqError &err)
Allow Mesquite to register a SIGINT handler.
static void enable (MsqError &err)
Force Mesquite to register SIGINT handler.
static bool interrupt ()
Check if an interrupt was seen.
static void clear ()
Clear the interrupt flag.
static void set_interrupt ()
Set the interrupt flag.
static void set_handler ()
Private Types
enum InterruptMode {
CATCH, IGNORE, AUTO, CATCH,
IGNORE, AUTO
}
enum InterruptMode {
CATCH, IGNORE, AUTO, CATCH,
IGNORE, AUTO
}
Private Member Functions
void * operator new (size_t size)
MsqInterrupt (const MsqInterrupt &)
MsqInterrupt & operator= (const MsqInterrupt &)
void * operator new (size_t size)
MsqInterrupt (const MsqInterrupt &)
MsqInterrupt & operator= (const MsqInterrupt &)
Static Private Attributes
static InterruptMode interruptMode = MsqInterrupt::AUTO
static unsigned instanceCount = 0
static bool sawInterrupt = false
Detailed Description
Class to watch for user-interrupt (SIGINT, ctrl-C)
A class to watch for SIGINT.
Creating an instance of the class ensures that the Mesquite handler for SIGINT is registered. When all instances are destroyed, the Mesquite handler is removed. The intent is that each interruptable API declare an instance on the stack. This way the handler is automatically unregistered when the API returns. For example: void my_api(MsqError& err) { MsqInterrupt interrupt; ... //do stuff return; }
Definition at line 51 of file includeLinks/MsqInterrupt.hpp.
Member Enumeration Documentation
enum InterruptMode private
Enumerator
CATCH
IGNORE
AUTO
CATCH
IGNORE
AUTO
Definition at line 80 of file includeLinks/MsqInterrupt.hpp.
 { CATCH, IGNORE, AUTO };
enum InterruptMode private
Enumerator
CATCH
IGNORE
AUTO
CATCH
IGNORE
AUTO
Definition at line 80 of file src/Misc/MsqInterrupt.hpp.
 { CATCH, IGNORE, AUTO };
Constructor & Destructor Documentation
MsqInterrupt ()
Constructor, increment instance count.
If instance count was zero, register SIGINT handler
Definition at line 85 of file Misc/MsqInterrupt.cpp.
References MsqInterrupt::IGNORE, MsqInterrupt::instanceCount, MsqInterrupt::interruptMode, MsqInterrupt::sawInterrupt, and MsqInterrupt::set_handler().
 {
   if (!instanceCount)
   {
     if (IGNORE != interruptMode)
       set_handler();
     sawInterrupt = false;
   }
   ++instanceCount;
 }
~MsqInterrupt ()
Constructor, decrement instance count.
If instance count goes to zero, remove SIGINT handler
Definition at line 96 of file Misc/MsqInterrupt.cpp.
References MsqInterrupt::instanceCount, Mesquite::oldHandler, and MsqInterrupt::sawInterrupt.
 {
   if (!--instanceCount && SIG_ERR != oldHandler)
   {
     signal( SIGINT, oldHandler );
     oldHandler = SIG_ERR;
   }
   sawInterrupt = false;
 }
MsqInterrupt (const MsqInterrupt &) private
MsqInterrupt ()
Constructor, increment instance count.
If instance count was zero, register SIGINT handler
~MsqInterrupt ()
Constructor, decrement instance count.
If instance count goes to zero, remove SIGINT handler
MsqInterrupt (const MsqInterrupt &) private
Member Function Documentation
void allow (MsqError & err) static
Allow Mesquite to register a SIGINT handler.
Definition at line 77 of file Misc/MsqInterrupt.cpp.
References MsqInterrupt::AUTO, MsqInterrupt::instanceCount, MsqInterrupt::interruptMode, Mesquite::oldHandler, MsqInterrupt::sawInterrupt, and MsqInterrupt::set_handler().
 {
   sawInterrupt = false;
   interruptMode = AUTO;
   if (instanceCount && SIG_ERR == oldHandler)
     set_handler();
 }
static void allow (MsqError & err) static
Allow Mesquite to register a SIGINT handler.
static void clear () inline static
Clear the interrupt flag.
Definition at line 65 of file includeLinks/MsqInterrupt.hpp.
References MsqInterrupt::sawInterrupt.
 { sawInterrupt = false; }
static void clear () inline static
Clear the interrupt flag.
Definition at line 65 of file src/Misc/MsqInterrupt.hpp.
References MsqInterrupt::sawInterrupt.
 { sawInterrupt = false; }
static void disable (MsqError & err) static
Disable Mesquite's SIGINT handler.
void disable (MsqError & err) static
Disable Mesquite's SIGINT handler.
Definition at line 58 of file Misc/MsqInterrupt.cpp.
References MsqInterrupt::IGNORE, MsqInterrupt::instanceCount, MsqInterrupt::interruptMode, Mesquite::oldHandler, and MsqInterrupt::sawInterrupt.
 {
   interruptMode = IGNORE;
   if (instanceCount && SIG_ERR != oldHandler)
   {
     signal( SIGINT, oldHandler );
     oldHandler = SIG_ERR;
   }
   sawInterrupt = false;
 }
static void enable (MsqError & err) static
Force Mesquite to register SIGINT handler.
void enable (MsqError & err) static
Force Mesquite to register SIGINT handler.
Definition at line 69 of file Misc/MsqInterrupt.cpp.
References MsqInterrupt::CATCH, MsqInterrupt::instanceCount, MsqInterrupt::interruptMode, Mesquite::oldHandler, MsqInterrupt::sawInterrupt, and MsqInterrupt::set_handler().
 {
   sawInterrupt = false;
   interruptMode = CATCH;
   if (instanceCount && SIG_ERR == oldHandler)
     set_handler();
 }
static bool interrupt () inline static
Check if an interrupt was seen.
Definition at line 63 of file includeLinks/MsqInterrupt.hpp.
References MsqInterrupt::sawInterrupt.
Referenced by TerminationCriterion::terminate().
 { return sawInterrupt;  }
static bool interrupt () inline static
Check if an interrupt was seen.
Definition at line 63 of file src/Misc/MsqInterrupt.hpp.
References MsqInterrupt::sawInterrupt.
 { return sawInterrupt;  }
void* operator new (size_t size) private
void* operator new (size_t size) private
MsqInterrupt& operator= (const MsqInterrupt &) private
MsqInterrupt& operator= (const MsqInterrupt &) private
static void set_handler () static
void set_handler () static
Definition at line 47 of file Misc/MsqInterrupt.cpp.
References MsqInterrupt::AUTO, MsqInterrupt::interruptMode, Mesquite::msq_sigint_handler(), and Mesquite::oldHandler.
Referenced by MsqInterrupt::allow(), MsqInterrupt::enable(), Mesquite::msq_sigint_handler(), and MsqInterrupt::MsqInterrupt().
 {
   oldHandler = signal( SIGINT, &msq_sigint_handler );
   if (MsqInterrupt::interruptMode == MsqInterrupt::AUTO &&
       (oldHandler == SIG_DFL || oldHandler == SIG_IGN))
   {
     signal( SIGINT, oldHandler );
     oldHandler = SIG_ERR;
   }
 }
static void set_interrupt () inline static
Set the interrupt flag.
Definition at line 67 of file includeLinks/MsqInterrupt.hpp.
References MsqInterrupt::sawInterrupt.
Referenced by Mesquite::msq_sigint_handler().
 { sawInterrupt = true;  }
static void set_interrupt () inline static
Set the interrupt flag.
Definition at line 67 of file src/Misc/MsqInterrupt.hpp.
References MsqInterrupt::sawInterrupt.
 { sawInterrupt = true;  }
Member Data Documentation
unsigned instanceCount = 0 static private
Definition at line 83 of file includeLinks/MsqInterrupt.hpp.
Referenced by MsqInterrupt::allow(), MsqInterrupt::disable(), MsqInterrupt::enable(), MsqInterrupt::MsqInterrupt(), and MsqInterrupt::~MsqInterrupt().
MsqInterrupt::InterruptMode interruptMode = MsqInterrupt::AUTO static private
Definition at line 82 of file includeLinks/MsqInterrupt.hpp.
Referenced by MsqInterrupt::allow(), MsqInterrupt::disable(), MsqInterrupt::enable(), MsqInterrupt::MsqInterrupt(), and MsqInterrupt::set_handler().
bool sawInterrupt = false static private
Definition at line 84 of file includeLinks/MsqInterrupt.hpp.
Referenced by MsqInterrupt::allow(), MsqInterrupt::clear(), MsqInterrupt::disable(), MsqInterrupt::enable(), MsqInterrupt::interrupt(), MsqInterrupt::MsqInterrupt(), MsqInterrupt::set_interrupt(), and MsqInterrupt::~MsqInterrupt().
The documentation for this class was generated from the following files:
includeLinks/MsqInterrupt.hpp
Misc/MsqInterrupt.cpp