Rocstar: RI_DFT Class Reference
RI_DFT Class Reference
Class containing the target corner matrices for the context based smoothing.
#include <RI_DFT.hpp>
Public Member Functions
RI_DFT ()
virtual ~RI_DFT ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *e, double &m, MsqError &err)
Evaluate the metric for an element.
bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], int nfv, double &m, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], Matrix3D h[], int nfv, double &m, MsqError &err)
RI_DFT ()
virtual ~RI_DFT ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *e, double &m, MsqError &err)
Evaluate the metric for an element.
bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], int nfv, double &m, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], Matrix3D h[], int nfv, double &m, MsqError &err)
Public Member Functions inherited from DistanceFromTarget
virtual ~DistanceFromTarget ()
virtual destructor ensures use of polymorphism during destruction
virtual ~DistanceFromTarget ()
virtual destructor ensures use of polymorphism during destruction
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Private Attributes
double a
Exponent b
Exponent c
Vector3D mNormal
Vector3D mCoords [4]
Vector3D mGrads [4]
Vector3D mAccGrads [8]
Matrix3D mHessians [10]
Matrix3D invW
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Member Functions inherited from DistanceFromTarget
void compute_T_matrices (MsqMeshEntity &elem, PatchData &pd, Matrix3D T[], size_t num_T, double c_k[], MsqError &err)
For a given element, compute each corner matrix A, and given a target corner matrix W, returns for each corner.
bool get_barrier_function (PatchData &pd, const double &tau, double &h, MsqError &err)
void compute_T_matrices (MsqMeshEntity &elem, PatchData &pd, Matrix3D T[], size_t num_T, double c_k[], MsqError &err)
For a given element, compute each corner matrix A, and given a target corner matrix W, returns for each corner.
bool get_barrier_function (PatchData &pd, const double &tau, double &h, MsqError &err)
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
Class containing the target corner matrices for the context based smoothing.
Definition at line 51 of file includeLinks/RI_DFT.hpp.
Constructor & Destructor Documentation
RI_DFT () inline
Definition at line 55 of file includeLinks/RI_DFT.hpp.
References QualityMetric::ELEMENT_BASED, QualityMetric::LINEAR, MSQ_CHKERR, QualityMetric::NUMERICAL_GRADIENT, QualityMetric::NUMERICAL_HESSIAN, QualityMetric::set_averaging_method(), QualityMetric::set_gradient_type(), QualityMetric::set_hessian_type(), and QualityMetric::set_metric_type().
       : a(pow(2.0, MSQ_ONE_THIRD)), b(1.0), c(-4.0/3.0)
     {
       MsqError err;
       set_averaging_method(LINEAR, err); MSQ_CHKERR(err);
       set_metric_type(ELEMENT_BASED);
       set_gradient_type(NUMERICAL_GRADIENT);
       set_hessian_type(NUMERICAL_HESSIAN);
     }
virtual ~RI_DFT () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 66 of file includeLinks/RI_DFT.hpp.
        {};
RI_DFT () inline
Definition at line 55 of file src/QualityMetric/DFT/RI_DFT.hpp.
References QualityMetric::ELEMENT_BASED, QualityMetric::LINEAR, MSQ_CHKERR, QualityMetric::NUMERICAL_GRADIENT, QualityMetric::NUMERICAL_HESSIAN, QualityMetric::set_averaging_method(), QualityMetric::set_gradient_type(), QualityMetric::set_hessian_type(), and QualityMetric::set_metric_type().
       : a(pow(2.0, MSQ_ONE_THIRD)), b(1.0), c(-4.0/3.0)
     {
       MsqError err;
       set_averaging_method(LINEAR, err); MSQ_CHKERR(err);
       set_metric_type(ELEMENT_BASED);
       set_gradient_type(NUMERICAL_GRADIENT);
       set_hessian_type(NUMERICAL_HESSIAN);
     }
virtual ~RI_DFT () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 66 of file src/QualityMetric/DFT/RI_DFT.hpp.
        {};
Member Function Documentation
bool compute_element_analytical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
If that function is not over-riden in the concrete class, the base
Parameters description, see QualityMetric::compute_element_gradient() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
Definition at line 1939 of file QualityMetric/DFT/RI_DFT.cpp.
References RI_DFT::a, RI_DFT::b, RI_DFT::c, QualityMetric::compute_element_numerical_gradient(), g_fcn_ridft2(), g_fcn_ridft3(), PatchData::get_barrier_delta(), TargetMatrix::get_cK(), PatchData::get_domain_normal_at_vertex(), PatchData::get_element_index(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), Mesquite::HEXAHEDRON, i, Mesquite::inv(), RI_DFT::invW, j, k, RI_DFT::mAccGrads, RI_DFT::mCoords, RI_DFT::mGrads, RI_DFT::mNormal, Mesquite::MSQ_3RT_2_OVER_6RT_3, MSQ_CHKERR, MSQ_ERRZERO, Mesquite::MSQ_ONE_THIRD, MSQ_SETERR, MsqError::NOT_IMPLEMENTED, Mesquite::QUADRILATERAL, PatchData::targetMatrices, Mesquite::TETRAHEDRON, Mesquite::TRIANGLE, and MsqMeshEntity::vertex_count().
 {
   // Only works with the weighted average
   MsqVertex *vertices = pd.get_vertex_array(err); MSQ_ERRZERO(err);
   EntityTopology topo = e->get_element_type();
   const size_t nv = e->vertex_count();
   const size_t *v_i = e->get_vertex_index_array();
   size_t idx = pd.get_element_index(e);
   const TargetMatrix *W = pd.targetMatrices.get_element_corner_tags(&pd, idx, err );
   MSQ_ERRZERO(err);
   // Initialize constants for the metric
   const double delta = pd.get_barrier_delta(err); MSQ_ERRZERO(err);
   const int tetInd[4][4] = {{0, 1, 2, 3}, {1, 2, 0, 3},
                             {2, 0, 1, 3}, {3, 2, 1, 0}};
   const int hexInd[8][4] = {{0, 1, 3, 4}, {1, 2, 0, 5},
                             {2, 3, 1, 6}, {3, 0, 2, 7},
                             {4, 7, 5, 0}, {5, 4, 6, 1},
                             {6, 5, 7, 2}, {7, 6, 4, 3}};
   // Variables used for computing the metric
   double   mMetric;             // Metric value
   bool     mValid;              // Validity of the metric
   int      i, j;
   m = 0.0;
   switch(topo) {
   case TRIANGLE:
     assert(3 == nv);
 #ifndef ANALYTIC
     mValid = compute_element_numerical_gradient(pd, e, fv, g, nfv, m, err);
     return !MSQ_CHKERR(err) && mValid;
 #else
     // The following analytic calculation only works correctly if the
     // normal is constant.  If the normal is not constaint, you need
     // to get the gradient of the normal with respect to the vertex
     // positions to obtain the correct values.
     for (i = 0; i < 3; ++i) {
       mAccGrads[i] = 0.0;
     }
     for (i = 0; i < 3; ++i) {
       for (j = 0; j < 3; ++j) {
         mCoords[j] = vertices[v_i[tetInd[i][j]]];
       }
       pd.get_domain_normal_at_vertex(v_i[tetInd[i][0]], true, mNormal, err);
       MSQ_ERRZERO(err);
       mNormal *= MSQ_3RT_2_OVER_6RT_3);
       inv(invW, W[i]);
       mValid = g_fcn_ridft2(mMetric, mGrads, mCoords, mNormal,
                             invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
       for (j = 0; j < 3; ++j) {
         mAccGrads[tetInd[i][j]] += W[i].get_cK() * mGrads[j];
       }
     }
     m *= MSQ_ONE_THIRD;
     for (i = 0; i < 3; ++i) {
       mAccGrads[i] *= MSQ_ONE_THIRD;
     }
     // This is not very efficient, but is one way to select correct gradients.
     // For gradients, info is returned only for free vertices, in the order
     // of fv[].
     for (i = 0; i < 3; ++i) {
       for (j = 0; j < nfv; ++j) {
         if (vertices + v_i[i] == fv[j]) {
           g[j] = mAccGrads[i];
         }
       }
     }
 #endif
     break;
   case QUADRILATERAL:
 #ifndef ANALYTIC
     mValid = compute_element_numerical_gradient(pd, e, fv, g, nfv, m, err);
     return !MSQ_CHKERR(err) && mValid;
 #else
     // The following analytic calculation only works correctly if the
     // normal is constant.  If the normal is not constaint, you need
     // to get the gradient of the normal with respect to the vertex
     // positions to obtain the correct values.
     for (i = 0; i < 4; ++i) {
       mAccGrads[i] = 0.0;
     }
     for (i = 0; i < 4; ++i) {
       for (j = 0; j < 3; ++j) {
         mCoords[j] = vertices[v_i[hexInd[i][j]]];
       }
       pd.get_domain_normal_at_vertex(v_i[hexInd[i][0]], true, mNormal, err);
       MSQ_ERRZERO(err);
       inv(invW, W[i]);
       mValid = g_fcn_ridft2(mMetric, mGrads, mCoords, mNormal,
                             invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
       for (j = 0; j < 3; ++j) {
         mAccGrads[hexInd[i][j]] += W[i].get_cK() * mGrads[j];
       }
     }
     m *= 0.25;
     for (i = 0; i < 4; ++i) {
       mAccGrads[i] *= 0.25;
     }
     // This is not very efficient, but is one way to select correct gradients
     // For gradients, info is returned only for free vertices, in the order
     // of fv[].
     for (i = 0; i < 4; ++i) {
       for (j = 0; j < nfv; ++j) {
         if (vertices + v_i[i] == fv[j]) {
           g[j] = mAccGrads[i];
         }
       }
     }
 #endif
     break;
   case TETRAHEDRON:
     for (i = 0; i < 4; ++i) {
       mAccGrads[i] = 0.0;
     }
     for (i = 0; i < 4; ++i) {
       for (j = 0; j < 4; ++j) {
         mCoords[j] = vertices[v_i[tetInd[i][j]]];
       }
       inv(invW, W[i]);
       mValid = g_fcn_ridft3(mMetric, mGrads, mCoords, invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
       for (j = 0; j < 4; ++j) {
         mAccGrads[tetInd[i][j]] += W[i].get_cK() * mGrads[j];
       }
     }
     m *= 0.25;
     for (i = 0; i < 4; ++i) {
       mAccGrads[i] *= 0.25;
     }
     // This is not very efficient, but is one way to select correct gradients.
     // For gradients, info is returned only for free vertices, in the order
     // of fv[].
     for (i = 0; i < 4; ++i) {
       for (size_t k = 0; k < nv; ++k) {
         if (vertices + v_i[i] == fv[k]) {
           g[k] = mAccGrads[i];
         }
       }
     }
     break;
   case HEXAHEDRON:
     for (i = 0; i < 8; ++i) {
       mAccGrads[i] = 0.0;
     }
     for (i = 0; i < 8; ++i) {
       for (j = 0; j < 4; ++j) {
         mCoords[j] = vertices[v_i[hexInd[i][j]]];
       }
       inv(invW, W[i]);
       mValid = g_fcn_ridft3(mMetric, mGrads, mCoords, invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
       for (j = 0; j < 4; ++j) {
         mAccGrads[hexInd[i][j]] += W[i].get_cK() * mGrads[j];
       }
     }
     m *= 0.125;
     for (i = 0; i < 8; ++i) {
       mAccGrads[i] *= 0.125;
     }
     // This is not very efficient, but is one way to select correct gradients
     // For gradients, info is returned only for free vertices, in the order
     // of fv[].
     for (i = 0; i < 8; ++i) {
       for (j = 0; j < nfv; ++j) {
         if (vertices + v_i[i] == fv[j]) {
           g[j] = mAccGrads[i];
         }
       }
     }
     break;
   default:
     MSQ_SETERR(err)("element type not implemented.",MsqError::NOT_IMPLEMENTED);
     return false;
   }
   return true;
 }
bool compute_element_analytical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
If that function is not over-riden in the concrete class, the base
Parameters description, see QualityMetric::compute_element_gradient() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
bool compute_element_analytical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) virtual
If that function is not over-riden in the concrete class, the base class function makes it default to a numerical hessian.
For parameters description, see QualityMetric::compute_element_hessian() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
bool compute_element_analytical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) virtual
If that function is not over-riden in the concrete class, the base class function makes it default to a numerical hessian.
For parameters description, see QualityMetric::compute_element_hessian() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
Definition at line 2179 of file QualityMetric/DFT/RI_DFT.cpp.
References RI_DFT::a, RI_DFT::b, RI_DFT::c, QualityMetric::compute_element_numerical_hessian(), PatchData::get_barrier_delta(), TargetMatrix::get_cK(), PatchData::get_domain_normal_at_vertex(), PatchData::get_element_index(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), h_fcn_ridft2(), h_fcn_ridft3(), Mesquite::HEXAHEDRON, i, Mesquite::inv(), RI_DFT::invW, j, k, RI_DFT::mCoords, RI_DFT::mGrads, RI_DFT::mHessians, RI_DFT::mNormal, Mesquite::MSQ_3RT_2_OVER_6RT_3, MSQ_CHKERR, MSQ_ERRZERO, Mesquite::MSQ_ONE_THIRD, MSQ_SETERR, MsqError::NOT_IMPLEMENTED, Mesquite::QUADRILATERAL, PatchData::targetMatrices, Mesquite::TETRAHEDRON, Mesquite::transpose(), Mesquite::TRIANGLE, MsqMeshEntity::vertex_count(), and Matrix3D::zero().
 {
   // Only works with the weighted average
   MsqVertex *vertices = pd.get_vertex_array(err);  MSQ_ERRZERO(err);
   EntityTopology topo = e->get_element_type();
   const size_t nv = e->vertex_count();
   const size_t *v_i = e->get_vertex_index_array();
   size_t idx = pd.get_element_index(e);
   const TargetMatrix *W = pd.targetMatrices.get_element_corner_tags(&pd, idx, err );
   MSQ_ERRZERO(err);
   // Initialize constants for the metric
   const double delta = pd.get_barrier_delta(err); MSQ_ERRZERO(err);
   const int tetInd[4][4] = {{0, 1, 2, 3}, {1, 2, 0, 3},
                             {2, 0, 1, 3}, {3, 2, 1, 0}};
   const int hexInd[8][4] = {{0, 1, 3, 4}, {1, 2, 0, 5},
                             {2, 3, 1, 6}, {3, 0, 2, 7},
                             {4, 7, 5, 0}, {5, 4, 6, 1},
                             {6, 5, 7, 2}, {7, 6, 4, 3}};
   // Variables used for computing the metric
   double   mMetric;             // Metric value
   bool     mValid;              // Validity of the metric
   int      i, j, k, l;
   int      row, col, loc;
   m = 0.0;
   switch(topo) {
   case TRIANGLE:
     assert(3 == nv);
 #ifndef ANALYTIC
     mValid = compute_element_numerical_hessian(pd, e, fv, g, h, nfv, m, err);
     return !MSQ_CHKERR(err) && mValid;
 #else
     // The following analytic calculation only works correctly if the
     // normal is constant.  If the normal is not constaint, you need
     // to get the gradient of the normal with respect to the vertex
     // positions to obtain the correct values.
     // Zero out the hessian and gradient vector
     for (i = 0; i < 3; ++i) {
       g[i] = 0.0;
     }
     for (i = 0; i < 6; ++i) {
       h[i].zero();
     }
     // Compute the metric and sum them together
     for (i = 0; i < 3; ++i) {
       for (j = 0; j < 3; ++j) {
         mCoords[j] = vertices[v_i[tetInd[i][j]]];
       }
       pd.get_domain_normal_at_vertex(v_i[tetInd[i][0]], true, mNormal, err);
       MSQ_ERRZERO(err);
       mNormal *= MSQ_3RT_2_OVER_6RT_3;
       inv(invW, W[i]);
       mValid = h_fcn_ridft2(mMetric, mGrads, mHessians, mCoords, mNormal,
                             invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
       for (j = 0; j < 3; ++j) {
         g[tetInd[i][j]] += W[i].get_cK() * mGrads[j];
       }
       l = 0;
       for (j = 0; j < 3; ++j) {
         for (k = j; k < 3; ++k) {
           row = tetInd[i][j];
           col = tetInd[i][k];
           if (row <= col) {
             loc = 3*row - (row*(row+1)/2) + col;
             h[loc] += W[i].get_cK() * mHessians[l];
           }
           else {
             loc = 3*col - (col*(col+1)/2) + row;
             h[loc] += W[i].get_cK() * transpose(mHessians[l]);
           }
           ++l;
         }
       }
     }
     m *= MSQ_ONE_THIRD;
     for (i = 0; i < 3; ++i) {
       g[i] *= MSQ_ONE_THIRD;
     }
     for (i = 0; i < 6; ++i) {
       h[i] *= MSQ_ONE_THIRD;
     }
     // zero out fixed elements of g
     j = 0;
     for (i = 0; i < 3; ++i) {
       if (vertices + v_i[i] == fv[j]) {
         // if free vertex, see next
         ++j;
       }
       else {
         // else zero gradient entry and hessian entries.
         g[i] = 0.;
         switch(i) {
         case 0:
           h[0].zero(); h[1].zero(); h[2].zero();
           break;
         case 1:
           h[1].zero(); h[3].zero(); h[4].zero();
           break;
         case 2:
           h[2].zero(); h[4].zero(); h[5].zero();
           break;
         }
       }
     }
 #endif
     break;
   case QUADRILATERAL:
 #ifndef ANALYTIC
     mValid = compute_element_numerical_hessian(pd, e, fv, g, h, nfv, m, err);
     return !MSQ_CHKERR(err) && mValid;
 #else
     // The following analytic calculation only works correctly if the
     // normal is constant.  If the normal is not constaint, you need
     // to get the gradient of the normal with respect to the vertex
     // positions to obtain the correct values.
     // Zero out the hessian and gradient vector
     for (i = 0; i < 4; ++i) {
       g[i] = 0.0;
     }
     for (i = 0; i < 10; ++i) {
       h[i].zero();
     }
     // Compute the metric and sum them together
     for (i = 0; i < 4; ++i) {
       for (j = 0; j < 3; ++j) {
         mCoords[j] = vertices[v_i[hexInd[i][j]]];
       }
       pd.get_domain_normal_at_vertex(v_i[hexInd[i][0]], true, mNormal, err);
       MSQ_ERRZERO(err);
       inv(invW, W[i]);
       mValid = h_fcn_ridft2(mMetric, mGrads, mHessians, mCoords, mNormal,
                             invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
       for (j = 0; j < 3; ++j) {
         g[hexInd[i][j]] += W[i].get_cK() * mGrads[j];
       }
       l = 0;
       for (j = 0; j < 3; ++j) {
         for (k = j; k < 3; ++k) {
           row = hexInd[i][j];
           col = hexInd[i][k];
           if (row <= col) {
             loc = 4*row - (row*(row+1)/2) + col;
             h[loc] += W[i].get_cK() * mHessians[l];
           }
           else {
             loc = 4*col - (col*(col+1)/2) + row;
             h[loc] += W[i].get_cK() * transpose(mHessians[l]);
           }
           ++l;
         }
       }
     }
     m *= 0.25;
     for (i = 0; i < 4; ++i) {
       g[i] *= 0.25;
     }
     for (i = 0; i < 10; ++i) {
       h[i] *= 0.25;
     }
     // zero out fixed elements of gradient and Hessian
     j = 0;
     for (i = 0; i < 4; ++i) {
       if (vertices + v_i[i] == fv[j]) {
         // if free vertex, see next
         ++j;
       }
       else {
         // else zero gradient entry and hessian entries.
         g[i] = 0.;
         switch(i) {
         case 0:
           h[0].zero();   h[1].zero();   h[2].zero();   h[3].zero();
           break;
         case 1:
           h[1].zero();   h[4].zero();   h[5].zero();   h[6].zero();
           break;
         case 2:
           h[2].zero();   h[5].zero();   h[7].zero();  h[8].zero();
           break;
         case 3:
           h[3].zero();   h[6].zero();   h[8].zero();  h[9].zero();
           break;
         }
       }
     }
 #endif
     break;
   case TETRAHEDRON:
     // Zero out the hessian and gradient vector
     for (i = 0; i < 4; ++i) {
       g[i] = 0.0;
     }
     for (i = 0; i < 10; ++i) {
       h[i].zero();
     }
     // Compute the metric and sum them together
     for (i = 0; i < 4; ++i) {
       for (j = 0; j < 4; ++j) {
         mCoords[j] = vertices[v_i[tetInd[i][j]]];
       }
       inv(invW, W[i]);
       mValid = h_fcn_ridft3(mMetric, mGrads, mHessians, mCoords,
                            invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
       for (j = 0; j < 4; ++j) {
         g[tetInd[i][j]] += W[i].get_cK() * mGrads[j];
       }
       l = 0;
       for (j = 0; j < 4; ++j) {
         for (k = j; k < 4; ++k) {
           row = tetInd[i][j];
           col = tetInd[i][k];
           if (row <= col) {
             loc = 4*row - (row*(row+1)/2) + col;
             h[loc] += W[i].get_cK() * mHessians[l];
           }
           else {
             loc = 4*col - (col*(col+1)/2) + row;
             h[loc] += W[i].get_cK() * transpose(mHessians[l]);
           }
           ++l;
         }
       }
     }
     m *= 0.25;
     for (i = 0; i < 4; ++i) {
       g[i] *= 0.25;
     }
     for (i = 0; i < 10; ++i) {
       h[i] *= 0.25;
     }
     // zero out fixed elements of g
     j = 0;
     for (i = 0; i < 4; ++i) {
       if (vertices + v_i[i] == fv[j]) {
         // if free vertex, see next
         ++j;
       }
       else {
         // else zero gradient entry and hessian entries.
         g[i] = 0.;
         switch(i) {
         case 0:
           h[0].zero(); h[1].zero(); h[2].zero(); h[3].zero();
           break;
         case 1:
           h[1].zero(); h[4].zero(); h[5].zero(); h[6].zero();
           break;
         case 2:
           h[2].zero(); h[5].zero(); h[7].zero(); h[8].zero();
           break;
         case 3:
           h[3].zero(); h[6].zero(); h[8].zero(); h[9].zero();
           break;
         }
       }
     }
     break;
   case HEXAHEDRON:
     // Zero out the hessian and gradient vector
     for (i = 0; i < 8; ++i) {
       g[i] = 0.0;
     }
     for (i = 0; i < 36; ++i) {
       h[i].zero();
     }
     // Compute the metric and sum them together
     for (i = 0; i < 8; ++i) {
       for (j = 0; j < 4; ++j) {
         mCoords[j] = vertices[v_i[hexInd[i][j]]];
       }
       inv(invW, W[i]);
       mValid = h_fcn_ridft3(mMetric, mGrads, mHessians, mCoords,
                            invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
       for (j = 0; j < 4; ++j) {
         g[hexInd[i][j]] += W[i].get_cK() * mGrads[j];
       }
       l = 0;
       for (j = 0; j < 4; ++j) {
         for (k = j; k < 4; ++k) {
           row = hexInd[i][j];
           col = hexInd[i][k];
           if (row <= col) {
             loc = 8*row - (row*(row+1)/2) + col;
             h[loc] += W[i].get_cK() * mHessians[l];
           }
           else {
             loc = 8*col - (col*(col+1)/2) + row;
             h[loc] += W[i].get_cK() * transpose(mHessians[l]);
           }
           ++l;
         }
       }
     }
     m *= 0.125;
     for (i = 0; i < 8; ++i) {
       g[i] *= 0.125;
     }
     for (i = 0; i < 36; ++i) {
       h[i] *= 0.125;
     }
     // zero out fixed elements of gradient and Hessian
     j = 0;
     for (i = 0; i < 8; ++i) {
       if (vertices + v_i[i] == fv[j]) {
         // if free vertex, see next
         ++j;
       }
       else {
         // else zero gradient entry and hessian entries.
         g[i] = 0.;
         switch(i) {
         case 0:
           h[0].zero();   h[1].zero();   h[2].zero();   h[3].zero();
           h[4].zero();   h[5].zero();   h[6].zero();   h[7].zero();
           break;
         case 1:
           h[1].zero();   h[8].zero();   h[9].zero();   h[10].zero();
           h[11].zero();  h[12].zero();  h[13].zero();  h[14].zero();
           break;
         case 2:
           h[2].zero();   h[9].zero();   h[15].zero();  h[16].zero();
           h[17].zero();  h[18].zero();  h[19].zero();  h[20].zero();
           break;
         case 3:
           h[3].zero();   h[10].zero();  h[16].zero();  h[21].zero();
           h[22].zero();  h[23].zero();  h[24].zero();  h[25].zero();
           break;
         case 4:
           h[4].zero();   h[11].zero();  h[17].zero();  h[22].zero();
           h[26].zero();  h[27].zero();  h[28].zero();  h[29].zero();
           break;
         case 5:
           h[5].zero();   h[12].zero();  h[18].zero();  h[23].zero();
           h[27].zero();  h[30].zero();  h[31].zero();  h[32].zero();
           break;
         case 6:
           h[6].zero();   h[13].zero();  h[19].zero();  h[24].zero();
           h[28].zero();  h[31].zero();  h[33].zero();  h[34].zero();
           break;
         case 7:
           h[7].zero();   h[14].zero();  h[20].zero();  h[25].zero();
           h[29].zero();  h[32].zero();  h[34].zero();  h[35].zero();
           break;
         }
       }
     }
     break;
   default:
     MSQ_SETERR(err)("element type not implemented.",MsqError::NOT_IMPLEMENTED);
     return false;
   }
   return true;
 }
bool evaluate_element (PatchData & , MsqMeshEntity * , double & , MsqError & err) virtual
Evaluate the metric for an element.
Reimplemented from QualityMetric.
bool evaluate_element (PatchData & , MsqMeshEntity * , double & , MsqError & err) virtual
Evaluate the metric for an element.
Reimplemented from QualityMetric.
Definition at line 1812 of file QualityMetric/DFT/RI_DFT.cpp.
References RI_DFT::a, RI_DFT::b, RI_DFT::c, PatchData::get_barrier_delta(), TargetMatrix::get_cK(), PatchData::get_domain_normal_at_vertex(), PatchData::get_element_index(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), Mesquite::HEXAHEDRON, i, Mesquite::inv(), RI_DFT::invW, j, Vector3D::length(), m_fcn_ridft2(), m_fcn_ridft3(), RI_DFT::mCoords, RI_DFT::mNormal, Mesquite::MSQ_3RT_2_OVER_6RT_3, MSQ_ERRZERO, Mesquite::MSQ_ONE_THIRD, MSQ_SETERR, Vector3D::normalize(), MsqError::NOT_IMPLEMENTED, Mesquite::QUADRILATERAL, PatchData::targetMatrices, Mesquite::TETRAHEDRON, Mesquite::TRIANGLE, and MsqMeshEntity::vertex_count().
 {
   // Only works with the weighted average
   MsqError   mErr;
   MsqVertex *vertices = pd.get_vertex_array(err); MSQ_ERRZERO(err);
   EntityTopology topo = e->get_element_type();
   const size_t nv = e->vertex_count();
   const size_t *v_i = e->get_vertex_index_array();
   size_t idx = pd.get_element_index(e);
   const TargetMatrix *W = pd.targetMatrices.get_element_corner_tags(&pd, idx, err );
   MSQ_ERRZERO(err);
   // Initialize constants for the metric
   const double delta = pd.get_barrier_delta(err); MSQ_ERRZERO(err);
   const int tetInd[4][4] = {{0, 1, 2, 3}, {1, 2, 0, 3},
                             {2, 0, 1, 3}, {3, 2, 1, 0}};
   const int hexInd[8][4] = {{0, 1, 3, 4}, {1, 2, 0, 5},
                             {2, 3, 1, 6}, {3, 0, 2, 7},
                             {4, 7, 5, 0}, {5, 4, 6, 1},
                             {6, 5, 7, 2}, {7, 6, 4, 3}};
   // Variables used for computing the metric
   double   mMetric;             // Metric value
   bool     mValid;              // Validity of the metric
   int      i, j;
   m = 0.0;
   switch(topo) {
   case TRIANGLE:
     for (i = 0; i < 3; ++i) {
       for (j = 0; j < 3; ++j) {
         mCoords[j] = vertices[v_i[tetInd[i][j]]];
       }
       pd.get_domain_normal_at_vertex(v_i[tetInd[i][0]], true, mNormal, mErr);
       if (mErr || mNormal.length() == 0) {
         mNormal = (vertices[v_i[tetInd[i][1]]] - vertices[v_i[tetInd[i][0]]]) *
                   (vertices[v_i[tetInd[i][2]]] - vertices[v_i[tetInd[i][0]]]);
         mNormal.normalize();
       }
       mNormal *= MSQ_3RT_2_OVER_6RT_3;
       inv(invW, W[i]);
       mValid = m_fcn_ridft2(mMetric, mCoords, mNormal, invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
     }
     m *= MSQ_ONE_THIRD;
     break;
   case QUADRILATERAL:
     for (i = 0; i < 4; ++i) {
       for (j = 0; j < 3; ++j) {
         mCoords[j] = vertices[v_i[hexInd[i][j]]];
       }
       pd.get_domain_normal_at_vertex(v_i[hexInd[i][0]], true, mNormal, mErr);
       if (mErr || mNormal.length() == 0) {
         mNormal = (vertices[v_i[hexInd[i][1]]] - vertices[v_i[hexInd[i][0]]]) *
                   (vertices[v_i[hexInd[i][2]]] - vertices[v_i[hexInd[i][0]]]);
         mNormal.normalize();
       }
       inv(invW, W[i]);
       mValid = m_fcn_ridft2(mMetric, mCoords, mNormal, invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
     }
     m *= 0.25;
     break;
   case TETRAHEDRON:
     for (i = 0; i < 4; ++i) {
       for (j = 0; j < 4; ++j) {
         mCoords[j] = vertices[v_i[tetInd[i][j]]];
       }
       inv(invW, W[i]);
       mValid = m_fcn_ridft3(mMetric, mCoords, invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
     }
     m *= 0.25;
     break;
   case HEXAHEDRON:
     for (i = 0; i < 8; ++i) {
       for (j = 0; j < 4; ++j) {
         mCoords[j] = vertices[v_i[hexInd[i][j]]];
       }
       inv(invW, W[i]);
       mValid = m_fcn_ridft3(mMetric, mCoords, invW, a, b, c, delta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
     }
     m *= 0.125;
     break;
   default:
     MSQ_SETERR(err)("element type not implemented.", MsqError::NOT_IMPLEMENTED);
     return false;
   }
   return true;
 }
Member Data Documentation
double a private
Definition at line 94 of file includeLinks/RI_DFT.hpp.
Referenced by RI_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), and RI_DFT::evaluate_element().
Exponent b private
Definition at line 95 of file includeLinks/RI_DFT.hpp.
Referenced by RI_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), and RI_DFT::evaluate_element().
Exponent c private
Definition at line 96 of file includeLinks/RI_DFT.hpp.
Referenced by RI_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), and RI_DFT::evaluate_element().
Matrix3D invW private
Definition at line 104 of file includeLinks/RI_DFT.hpp.
Referenced by RI_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), and RI_DFT::evaluate_element().
Vector3D mAccGrads private
Definition at line 102 of file includeLinks/RI_DFT.hpp.
Referenced by RI_DFT::compute_element_analytical_gradient().
Vector3D mCoords private
Definition at line 100 of file includeLinks/RI_DFT.hpp.
Referenced by RI_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), and RI_DFT::evaluate_element().
Vector3D mGrads private
Definition at line 101 of file includeLinks/RI_DFT.hpp.
Referenced by RI_DFT::compute_element_analytical_gradient(), and RI_DFT::compute_element_analytical_hessian().
Matrix3D mHessians private
Definition at line 103 of file includeLinks/RI_DFT.hpp.
Referenced by RI_DFT::compute_element_analytical_hessian().
Vector3D mNormal private
Definition at line 99 of file includeLinks/RI_DFT.hpp.
Referenced by RI_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), and RI_DFT::evaluate_element().
The documentation for this class was generated from the following files:
includeLinks/RI_DFT.hpp
QualityMetric/DFT/RI_DFT.cpp