Rocstar: Element_vectors_k_const< Value > Class Template Reference
Element_vectors_k_const< Value > Class Template Reference
This is a helper class for accessing elemental data.
#include <Element_accessors.h>
Public Types
typedef unsigned int Size
Public Member Functions
Element_vectors_k_const ()
Default constructor.
void set (const Value *p, Element_node_enumerator &ene, int strd)
initialize the accessor with a pointer and a specific stride.
void set (const Attribute *a, Element_node_enumerator &ene)
initialize the accessor from an attribute assiciated with a pane.
const Value & operator() (int i, int j) const
const Value & operator() (int i) const
const Value & operator[] (int i) const
Protected Attributes
const Attribute * _attr
union {
int _offset
const Value * _vs
};
Detailed Description
template<class Value>
class Element_vectors_k_const< Value >
This is a helper class for accessing elemental data.
Definition at line 318 of file Element_accessors.h.
Member Typedef Documentation
typedef unsigned int Size
Definition at line 320 of file Element_accessors.h.
Constructor & Destructor Documentation
Element_vectors_k_const () inline
Default constructor.
Definition at line 323 of file Element_accessors.h.
 : _attr(NULL), _vs(NULL) {}
Member Function Documentation
const Value& operator() (int i, int j) const inline
Definition at line 350 of file Element_accessors.h.
References Element_vectors_k_const< Value >::_attr, Element_vectors_k_const< Value >::_offset, Element_vectors_k_const< Value >::_vs, COM_assertion, j, and Attribute::size_of_components().
Referenced by Element_vectors_k< Value >::operator()(), Element_vectors_k_const< Value >::operator[](), and Element_vectors_k< Value >::operator[]().
{
     if ( _attr) {
       COM_assertion( _attr->size_of_components()>1);
       const Attribute *aj = _attr+j+1;
       return reinterpret_cast<const Value*>
         (aj->pointer())[_offset*aj->stride()];
     }
     else
       return _vs[j];
   }
const Value& operator() (int i) const inline
Definition at line 361 of file Element_accessors.h.
References Element_vectors_k_const< Value >::operator()().
Referenced by Element_vectors_k_const< Value >::operator()().
 { return operator()(i,0); }
const Value& operator[] (int i) const inline
Definition at line 363 of file Element_accessors.h.
References Element_vectors_k_const< Value >::operator()().
 { return operator()(i,0); }
void set (const Value * p, Element_node_enumerator & ene, int strd) inline
initialize the accessor with a pointer and a specific stride.
Definition at line 326 of file Element_accessors.h.
References Element_vectors_k_const< Value >::_attr, Element_vectors_k_const< Value >::_vs, and Element_node_enumerator::id().
Referenced by Window_manifold_2::elements_to_nodes(), and Element_vectors_k< Value >::set().
{
     _attr = NULL;
     _vs = &p[(ene.id()-1)*strd];
   }
void set (const Attribute * a, Element_node_enumerator & ene) inline
initialize the accessor from an attribute assiciated with a pane.
Definition at line 332 of file Element_accessors.h.
References Element_vectors_k_const< Value >::_attr, Element_vectors_k_const< Value >::_offset, Element_vectors_k_const< Value >::_vs, COM_assertion, COM_get_sizeof(), Attribute::data_type(), Pane::id(), Element_node_enumerator::id(), Attribute::is_elemental(), Attribute::pane(), Attribute::pointer(), Attribute::size_of_components(), strd, and Attribute::stride().
{
     COM_assertion( a->is_elemental() && a->pane()->id());
     COM_assertion( sizeof(Value)==COM_get_sizeof( a->data_type(),1));
     int ncomp = a->size_of_components();
     int strd = a->stride();
     if ( ncomp<=strd) {
       const Value *p = reinterpret_cast<const Value*>(a->pointer());
       _attr = NULL;
       _vs = &p[(ene.id()-1)*strd];
     }
     else {
       _attr = a;
       _offset = ene.id()-1;
     }
   }
Member Data Documentation
union { ... }
const Attribute* _attr protected
Definition at line 366 of file Element_accessors.h.
Referenced by Element_vectors_k_const< Value >::operator()(), and Element_vectors_k_const< Value >::set().
int _offset
Definition at line 368 of file Element_accessors.h.
Referenced by Element_vectors_k_const< Value >::operator()(), and Element_vectors_k_const< Value >::set().
const Value* _vs
Definition at line 369 of file Element_accessors.h.
Referenced by Element_vectors_k_const< Value >::operator()(), and Element_vectors_k_const< Value >::set().
The documentation for this class was generated from the following file:
Element_accessors.h