Rocstar: rflu_modpartitionregion Module Reference
rflu_modpartitionregion Module Reference
Public Member Functions
subroutine, public rflu_part_addvirtualcells (pRegion, pRegionSerial)
subroutine, public rflu_part_buildborderfacelist (pRegion)
subroutine, public rflu_part_buildcelllists (pRegion, pRegionSerial)
subroutine, public rflu_part_buildpatchlists (pRegion, pRegionSerial)
subroutine, public rflu_part_buildreg2cellmap (pRegion)
subroutine, public rflu_part_buildvertexdata (pRegion, pRegionSerial)
subroutine, public rflu_part_buildvertexlists (pRegion, pRegionSerial)
subroutine, public rflu_part_createcelllists (pRegion, pRegionSerial)
subroutine, public rflu_part_createpatchlists (pRegion, pRegionSerial)
subroutine, public rflu_part_createreg2cellmap (pRegion)
subroutine, public rflu_part_destroyborderfacelist (pRegion)
subroutine, public rflu_part_destroycelldata (pRegion)
subroutine, public rflu_part_destroycelllists (pRegion)
subroutine, public rflu_part_destroypatchlists (pRegion)
subroutine, public rflu_part_destroyvertexdata (pRegion)
subroutine, public rflu_part_partitionregion (pRegion)
subroutine rflu_part_recreatecelllist (global, nVertPerCell, nCellsMax, x2v, x2cg)
subroutine, public rflu_part_renumbervertexlists (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPartitionRegion.F90,v $ $Revision: 1.17 $'
Detailed Description
Definition at line 39 of file RFLU_ModPartitionRegion.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_part_addvirtualcells (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 106 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, moderror::registerfunction(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv1(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), and rflu_part_recreatecelllist().
Referenced by rflupart().
subroutine, public rflu_part_buildborderfacelist (type(t_region), pointer pRegion)
Definition at line 407 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_buildcelllists (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 595 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, iend, and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_buildpatchlists (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 821 of file RFLU_ModPartitionRegion.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortintegerinteger(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_buildreg2cellmap (type(t_region), pointer pRegion)
Definition at line 1176 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_buildvertexdata (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 1288 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_buildvertexlists (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 1387 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), key, moderror::registerfunction(), rflu_modhashtable::rflu_createhashtable(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modhashtable::rflu_hashbuildkey(), rflu_modhashtable::rflu_hashvertexfancy(), rflu_modrenumberlist::rflu_renumberlist2(), and rflu_modrenumberings::rflu_rnmb_createpv2svmap().
Referenced by rflupart().
subroutine, public rflu_part_createcelllists (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 1722 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, iend, and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_createpatchlists (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 1968 of file RFLU_ModPartitionRegion.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_createreg2cellmap (type(t_region), pointer pRegion)
Definition at line 2288 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_destroyborderfacelist (type(t_region), pointer pRegion)
Definition at line 2389 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_part_destroycelldata (type(t_region), pointer pRegion)
Definition at line 2484 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_part_destroycelllists (type(t_region), pointer pRegion)
Definition at line 2578 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_destroypatchlists (type(t_region), pointer pRegion)
Definition at line 2694 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_destroyvertexdata (type(t_region), pointer pRegion)
Definition at line 2811 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_part_partitionregion (type(t_region), pointer pRegion)
Definition at line 2903 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), and rflu_modsymmetryperiodic::rflu_sype_havesypepatches().
Referenced by rflupart().
subroutine rflu_part_recreatecelllist (type(t_global), pointer global, integer, intent(in) nVertPerCell, integer, intent(inout) nCellsMax, integer, dimension(:,:), pointer x2v, integer, dimension(:), pointer x2cg)
Definition at line 3224 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_part_addvirtualcells().
subroutine, public rflu_part_renumbervertexlists (type(t_region), pointer pRegion)
Definition at line 3379 of file RFLU_ModPartitionRegion.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modrenumberlist::rflu_renumberlist2().
Referenced by rflupart().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPartitionRegion.F90,v $ $Revision: 1.17 $' private
Definition at line 75 of file RFLU_ModPartitionRegion.F90.
The documentation for this module was generated from the following file:
RFLU_ModPartitionRegion.F90