Rocstar: TopologyModifier Class Reference
TopologyModifier Class Reference abstract
#include <TopologyModifier.hpp>
Public Member Functions
virtual ~TopologyModifier ()
virtual double loop_over_mesh (MeshSet &mesh, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
virtual ~TopologyModifier ()
virtual double loop_over_mesh (MeshSet &mesh, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
Public Member Functions inherited from QualityImprover
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Protected Member Functions
TopologyModifier ()
virtual void iteration_begin ()=0
virtual void optimize_connectivity ()=0
virtual void iteration_complete ()=0
virtual void iteration_end ()=0
TopologyModifier ()
virtual void iteration_begin ()=0
virtual void optimize_connectivity ()=0
virtual void iteration_complete ()=0
virtual void iteration_end ()=0
Protected Member Functions inherited from QualityImprover
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Additional Inherited Members
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Detailed Description
Definition at line 48 of file includeLinks/TopologyModifier.hpp.
Constructor & Destructor Documentation
virtual ~TopologyModifier () inline virtual
Definition at line 52 of file includeLinks/TopologyModifier.hpp.
       {};
TopologyModifier () protected
virtual ~TopologyModifier () inline virtual
Definition at line 52 of file src/QualityImprover/TopologyModifier/TopologyModifier.hpp.
       {};
TopologyModifier () protected
Member Function Documentation
virtual void iteration_begin () protected pure virtual
Referenced by TopologyModifier::loop_over_mesh().
virtual void iteration_begin () protected pure virtual
virtual void iteration_complete () protected pure virtual
Referenced by TopologyModifier::loop_over_mesh().
virtual void iteration_complete () protected pure virtual
virtual void iteration_end () protected pure virtual
Referenced by TopologyModifier::loop_over_mesh().
virtual void iteration_end () protected pure virtual
virtual double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
This is the "run" function of PatchDataUser. It can do anything really.
Implements QualityImprover.
double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
This is the "run" function of PatchDataUser. It can do anything really.
Implements QualityImprover.
Definition at line 43 of file QualityImprover/TopologyModifier/TopologyModifier.cpp.
References TopologyModifier::iteration_begin(), TopologyModifier::iteration_complete(), TopologyModifier::iteration_end(), and TopologyModifier::optimize_connectivity().
 {
   // TODO: for all vertices
 //  cout << "o Executing TopologyModifier::loop_over_mesh()\n"
 //       << "  Here we will be looping over elements\n";
   this->iteration_begin();
   this->optimize_connectivity();
   this->iteration_complete();
   this->iteration_end();
   return 0.;
 }
virtual void optimize_connectivity () protected pure virtual
Referenced by TopologyModifier::loop_over_mesh().
virtual void optimize_connectivity () protected pure virtual
The documentation for this class was generated from the following files:
includeLinks/TopologyModifier.hpp
QualityImprover/TopologyModifier/TopologyModifier.cpp