Rocstar: fdostream Class Reference
fdostream Class Reference
#include <FDUtils.H>
Public Member Functions
fdostream ()
fdostream (int fd)
int FD ()
int Init (int _fd)
Protected Attributes
Sys::fdoutbuf buf
Detailed Description
Definition at line 63 of file FDUtils.H.
Constructor & Destructor Documentation
fdostream () inline
Definition at line 67 of file FDUtils.H.
 : std::ostream(0) {};
fdostream (int fd) inline
Definition at line 68 of file FDUtils.H.
References fdostream::buf.
                          : std::ostream(0), buf(fd) {
         rdbuf(&buf);
       }
Member Function Documentation
int FD () inline
Definition at line 71 of file FDUtils.H.
References fdostream::buf, and fdoutbuf::FD().
 { return(buf.FD()); };
int Init (int _fd) inline
Definition at line 72 of file FDUtils.H.
References fdostream::buf, fdoutbuf::FD(), and fdoutbuf::Init().
 { buf.Init(_fd); rdbuf(&buf); return(buf.FD());};
Member Data Documentation
Sys::fdoutbuf buf protected
Definition at line 65 of file FDUtils.H.
Referenced by fdostream::FD(), fdostream::fdostream(), and fdostream::Init().
The documentation for this class was generated from the following file:
FDUtils.H