Rocstar: QualityAssessor::Assessor Class Reference
QualityAssessor::Assessor Class Reference
Per-metric QualityAssessor data.
#include <QualityAssessor.hpp>
Public Member Functions
Assessor (QualityMetric *metric)
double get_average () const
double get_maximum () const
double get_minimum () const
double get_rms () const
double get_stddev () const
int get_count () const
int get_invalid_element_count () const
void get_histogram (double &lower_bound_out, double &upper_bound_out, msq_std::vector< int > &counts_out, MsqError &err) const
Get historgram of data, if calculated.
void reset_data ()
Reset all calculated data.
void print_histogram (msq_stdio::ostream &) const
Print the histogram.
QualityMetric * get_metric () const
Get the QualityMetric.
void add_value (double metric_value)
Add a value to the running counts.
void add_hist_value (double metric_value)
Add a value to the hisogram data.
void add_invalid_value ()
Note invalid result.
void calculate_histogram_range ()
If range of histogram has not yet been determined, calculate it from the min/max values.
Assessor (QualityMetric *metric)
double get_average () const
double get_maximum () const
double get_minimum () const
double get_rms () const
double get_stddev () const
int get_count () const
int get_invalid_element_count () const
void get_histogram (double &lower_bound_out, double &upper_bound_out, msq_std::vector< int > &counts_out, MsqError &err) const
Get historgram of data, if calculated.
void reset_data ()
Reset all calculated data.
void print_histogram (msq_stdio::ostream &) const
Print the histogram.
QualityMetric * get_metric () const
Get the QualityMetric.
void add_value (double metric_value)
Add a value to the running counts.
void add_hist_value (double metric_value)
Add a value to the hisogram data.
void add_invalid_value ()
Note invalid result.
void calculate_histogram_range ()
If range of histogram has not yet been determined, calculate it from the min/max values.
Private Attributes
QualityMetric *const qualMetric
unsigned funcFlags
unsigned long count
double sum
double maximum
double minimum
double sqrSum
unsigned long numInvalid
bool haveHistRange
The histogram counts, where the first and last values are counts of values below the lower bound and above the upper bound, respectively.
double histMin
double histMax
msq_std::vector< int > histogram
Friends
class QualityAssessor
Detailed Description
Per-metric QualityAssessor data.
The Assessor class holds QualityAssessor data for each metric added by the calling application, including a pointer to the metric instance, QAFunction flags dictating what is to be calculated and output, histogram parameters, and the variables used to accumulate results as the QualityAssessor is running. It also provides methods to access the calculated data once the QualityAssessor pass is completed.
Definition at line 196 of file includeLinks/QualityAssessor.hpp.
Constructor & Destructor Documentation
Assessor (QualityMetric * metric)
Definition at line 508 of file QualityAssessor/QualityAssessor.cpp.
References QualityAssessor::Assessor::reset_data().
   : qualMetric(metric),
     funcFlags(0),
     haveHistRange(false),
     histMin(1.0),
     histMax(0.0)
 {
   reset_data();
 }
Assessor (QualityMetric * metric)
Member Function Documentation
void add_hist_value (double metric_value)
Add a value to the hisogram data.
Definition at line 585 of file QualityAssessor/QualityAssessor.cpp.
 {
     // Width of one interval in histogram
   double step = (histMax - histMin) / (histogram.size()-2);
     // First and last values in array are counts of values
     // outside the user-specified range of the histogram
     // (below and above, respectively.)
   if (metric_value < histMin)
     ++histogram[0];
   else if (metric_value > histMax)
     ++histogram[histogram.size()-1];
   else
   {
       // Calculate which interval the value is in.  Add one
       // because first entry is for values below user-specifed
       // minimum value for histogram.
     unsigned cell;
     if (step > DBL_EPSILON)
       cell = 1+(unsigned)((metric_value - histMin) / step);
     else
       cell = 1;
       // If value exactly equals maximum value, put in last
       // valid interval, not the count of values above the
       // maximum.
     if (cell + 1 == histogram.size())
       --cell;
       // Add value to interval.
     ++histogram[cell];
   }
 }
void add_hist_value (double metric_value)
Add a value to the hisogram data.
void add_invalid_value ()
Note invalid result.
Definition at line 580 of file QualityAssessor/QualityAssessor.cpp.
 {
   ++numInvalid;
 }
void add_invalid_value ()
Note invalid result.
void add_value (double metric_value)
Add a value to the running counts.
void add_value (double metric_value)
Add a value to the running counts.
Definition at line 562 of file QualityAssessor/QualityAssessor.cpp.
References QualityAssessor::HISTOGRAM.
 {
   sum += metric_value;
   sqrSum += metric_value*metric_value;
   if (metric_value > maximum)
     maximum = metric_value;
   if (metric_value < minimum)
     minimum = metric_value;
     // Only add value to histogram data from this function if
     // the user has specified the range.  If user has not
     // specified the range, QualityAssessor will call add_hist_value()
     // directly once the range has been calculated.
   if (funcFlags & QualityAssessor::HISTOGRAM && haveHistRange)
     add_hist_value( metric_value );
   ++count;
 }
void calculate_histogram_range ()
If range of histogram has not yet been determined, calculate it from the min/max values.
void calculate_histogram_range ()
If range of histogram has not yet been determined, calculate it from the min/max values.
Definition at line 618 of file QualityAssessor/QualityAssessor.cpp.
References cimg_library::log10(), and Mesquite::pow().
 {
   double step = (maximum - minimum) / (histogram.size() - 2);
   double size = pow( 10, ceil(log10(step)) );
   histMin = size * floor( minimum / size );
   histMax = size *  ceil( maximum / size );
 }
double get_average () const
double get_average () const
Definition at line 141 of file QualityAssessor/QualityAssessor.cpp.
 {
   return count ? sum/count : 0;
 }
int get_count () const inline
Definition at line 207 of file src/QualityAssessor/QualityAssessor.hpp.
References QualityAssessor::Assessor::count.
 { return count; }
int get_count () const inline
Definition at line 207 of file includeLinks/QualityAssessor.hpp.
References QualityAssessor::Assessor::count.
 { return count; }
void get_histogram (double & lower_bound_out, double & upper_bound_out, msq_std::vector< int > & counts_out, MsqError & err) const
Get historgram of data, if calculated.
Parameters
lower_bound_out The lower bound of the histogram
upper_bound_out The upper bound of the histogram
counts_out An array of counts of elements where the first entry is the number of elements for which the metric is below the lower bound, the last entry is the number of elements above the upper bound, and all other values are the counts for histogram intervals between the lower and upper bounds.
Definition at line 528 of file QualityAssessor/QualityAssessor.cpp.
References QualityAssessor::HISTOGRAM, MsqError::INVALID_STATE, and MSQ_SETERR.
 {
   if ( !(funcFlags & QualityAssessor::HISTOGRAM) )
   {
     MSQ_SETERR(err)("No histogram calculated.", MsqError::INVALID_STATE);
     return;
   }
   if (haveHistRange) {
     lower_bound_out = histMin;
     upper_bound_out = histMax;
   }
   else {
     lower_bound_out = minimum;
     upper_bound_out = maximum;
   }
   counts_out = histogram;
 }
void get_histogram (double & lower_bound_out, double & upper_bound_out, msq_std::vector< int > & counts_out, MsqError & err) const
Get historgram of data, if calculated.
Parameters
lower_bound_out The lower bound of the histogram
upper_bound_out The upper bound of the histogram
counts_out An array of counts of elements where the first entry is the number of elements for which the metric is below the lower bound, the last entry is the number of elements above the upper bound, and all other values are the counts for histogram intervals between the lower and upper bounds.
int get_invalid_element_count () const inline
Definition at line 209 of file src/QualityAssessor/QualityAssessor.hpp.
References QualityAssessor::Assessor::numInvalid.
 { return numInvalid; }
int get_invalid_element_count () const inline
Definition at line 209 of file includeLinks/QualityAssessor.hpp.
References QualityAssessor::Assessor::numInvalid.
 { return numInvalid; }
double get_maximum () const inline
Definition at line 203 of file includeLinks/QualityAssessor.hpp.
References QualityAssessor::Assessor::maximum.
 { return maximum; }
double get_maximum () const inline
Definition at line 203 of file src/QualityAssessor/QualityAssessor.hpp.
References QualityAssessor::Assessor::maximum.
 { return maximum; }
QualityMetric* get_metric () const inline
Get the QualityMetric.
Definition at line 234 of file includeLinks/QualityAssessor.hpp.
References QualityAssessor::Assessor::qualMetric.
 { return qualMetric; }
QualityMetric* get_metric () const inline
Get the QualityMetric.
Definition at line 234 of file src/QualityAssessor/QualityAssessor.hpp.
References QualityAssessor::Assessor::qualMetric.
 { return qualMetric; }
double get_minimum () const inline
Definition at line 204 of file src/QualityAssessor/QualityAssessor.hpp.
References QualityAssessor::Assessor::minimum.
 { return minimum; }
double get_minimum () const inline
Definition at line 204 of file includeLinks/QualityAssessor.hpp.
References QualityAssessor::Assessor::minimum.
 { return minimum; }
double get_rms () const
Definition at line 146 of file QualityAssessor/QualityAssessor.cpp.
References sqrt().
 {
   return count ? sqrt(sqrSum/count) : 0;
 }
double get_rms () const
double get_stddev () const
double get_stddev () const
Definition at line 151 of file QualityAssessor/QualityAssessor.cpp.
References cimg_library::cimg::sqr(), and sqrt().
 {
   double sqr = sqrSum/count - sum*sum/((double)count*count);
   return sqr < 0 ? 0 : sqrt(sqr);
 }
void print_histogram (msq_stdio::ostream & stream) const
Print the histogram.
Definition at line 737 of file QualityAssessor/QualityAssessor.cpp.
References i, cimg_library::log10(), max(), and min().
 {
   // Portability notes:
   //  Use log10 rather than log10f because the float variations require
   //  including platform-dependent headers on some platforms.
   //  Explicitly cast log10 argument to double because some platforms
   //  have overloaded float and double variations in C++ making an
   //  implicit cast from an integer ambiguous.
   const char GRAPH_CHAR = '=';  // Character used to create bar graphs
   const int FLOATW = 12;        // Width of floating-point output
   const int GRAPHW = 50;        // Width of bar graph
     // range is either user-specified (histMin & histMax) or
     // calculated (minimum & maximum)
   double min, max;
   //if (haveHistRange) {
     min = histMin;
     max = histMax;
   //}
   //else {
   //  min = minimum;
   //  max = maximum;
   //}
     // Witdh of one interval of histogram
   double step = (max - min) / (histogram.size()-2);
     // Find maximum value for an interval of the histogram
   unsigned i;
   int max_interval = 1;
   for (i = 0; i < histogram.size(); ++i)
     if (histogram[i] > max_interval)
       max_interval = histogram[i];
   if (0 == max_interval)
     return; // no data
     // Calculate width of field containing counts for
     // histogram intervals (log10(max_interval)).
   int num_width = 1;
   for (int temp = max_interval; temp > 0; temp /= 10)
     ++num_width;
     // Create an array of bar graph characters for use in output
   char graph_chars[GRAPHW+1];
   memset( graph_chars, GRAPH_CHAR, sizeof(graph_chars) );
     // Check if bar-graph should be linear or log10 plot
     // Do log plot if standard deviation is less that 1.5
     // histogram intervals.
   bool log_plot = false;
   double stddev = get_stddev();
   if (stddev > 0 && stddev < 2.0*step)
   {
     int new_interval = (int)(log10((double)(1+max_interval)));
     if (new_interval > 0) {
       log_plot = true;
       max_interval = new_interval;
     }
   }
     // Write title
   stream << msq_stdio::endl << "   " << get_metric()->get_name() << " histogram:";
   if (log_plot)
     stream << " (log10 plot)";
   stream << msq_stdio::endl;
     // For each interval of histogram
   for (i = 0; i < histogram.size(); ++i)
   {
       // First value is the count of the number of values that
       // were below the minimum value of the histogram.
     if (0 == i)
     {
       if (0 == histogram[i])
         continue;
       stream << setw(FLOATW) << "under min";
     }
       // Last value is the count of the number of values that
       // were above the maximum value of the histogram.
     else if (i+1 == histogram.size())
     {
       if (0 == histogram[i])
         continue;
       stream << setw(FLOATW) << "over max";
     }
       // Anything else is a valid interval of the histogram.
       // Print the lower bound for each interval.
     else
     {
       stream << "   " << setw(FLOATW) << min + (i-1)*step;
     }
       // Print interval count.
     stream << ": " << setw(num_width) << histogram[i] << ": ";
       // Print bar graph
       // First calculate the number of characters to output
     int num_graph;
     if (log_plot)
       num_graph = GRAPHW * (int)log10((double)(1+histogram[i])) / max_interval;
     else
       num_graph = GRAPHW * histogram[i] / max_interval;
       // print num_graph characters using array of fill characters.
     graph_chars[num_graph] = '\0';
     stream << graph_chars << msq_stdio::endl;
     graph_chars[num_graph] = GRAPH_CHAR;
   }
   stream << msq_stdio::endl;
 }
void print_histogram (msq_stdio::ostream &) const
Print the histogram.
void reset_data ()
Reset all calculated data.
Definition at line 551 of file QualityAssessor/QualityAssessor.cpp.
Referenced by QualityAssessor::Assessor::Assessor().
 {
   count = 0;
   sum = 0;
   maximum = -HUGE_VAL;
   minimum = HUGE_VAL;
   sqrSum = 0;
   numInvalid = 0;
   memset( &histogram[0], 0, sizeof(int)*histogram.size() );
 }
void reset_data ()
Reset all calculated data.
Friends And Related Function Documentation
QualityAssessor friend
Definition at line 252 of file includeLinks/QualityAssessor.hpp.
Member Data Documentation
unsigned long count private
Definition at line 257 of file includeLinks/QualityAssessor.hpp.
Referenced by QualityAssessor::Assessor::get_count().
unsigned funcFlags private
Definition at line 255 of file includeLinks/QualityAssessor.hpp.
bool haveHistRange private
The histogram counts, where the first and last values are counts of values below the lower bound and above the upper bound, respectively.
The remaining values are the histogram counts.
Definition at line 270 of file includeLinks/QualityAssessor.hpp.
double histMax private
Definition at line 272 of file includeLinks/QualityAssessor.hpp.
double histMin private
Definition at line 271 of file includeLinks/QualityAssessor.hpp.
msq_std::vector< int > histogram private
Definition at line 273 of file includeLinks/QualityAssessor.hpp.
double maximum private
Definition at line 260 of file includeLinks/QualityAssessor.hpp.
Referenced by QualityAssessor::Assessor::get_maximum().
double minimum private
Definition at line 261 of file includeLinks/QualityAssessor.hpp.
Referenced by QualityAssessor::Assessor::get_minimum().
unsigned long numInvalid private
Definition at line 263 of file includeLinks/QualityAssessor.hpp.
Referenced by QualityAssessor::Assessor::get_invalid_element_count().
QualityMetric *const qualMetric private
Definition at line 254 of file includeLinks/QualityAssessor.hpp.
Referenced by QualityAssessor::Assessor::get_metric().
double sqrSum private
Definition at line 262 of file includeLinks/QualityAssessor.hpp.
double sum private
Definition at line 259 of file includeLinks/QualityAssessor.hpp.
The documentation for this class was generated from the following files:
includeLinks/QualityAssessor.hpp
QualityAssessor/QualityAssessor.cpp