Rocstar: rflu_modreadbcinputfile Module Reference
rflu_modreadbcinputfile Module Reference
Public Member Functions
subroutine rflu_readbcinflowtotangsection (pRegion)
subroutine rflu_readbcinflowveltempsection (pRegion)
subroutine rflu_readbcinjectsection (pRegion)
subroutine rflu_readbcinputfile (pRegion)
subroutine, public rflu_readbcinputfilewrapper (pRegion)
subroutine rflu_readbcnoslipwalltempsect (pRegion)
subroutine rflu_readbcoutflowsection (pRegion)
subroutine rflu_readbcperiodicsection (pRegion)
subroutine rflu_readbcslipwallsection (pRegion)
subroutine rflu_readbcsymmetrysection (pRegion)
subroutine rflu_readbcvirtualsection (pRegion)
Private Member Functions
subroutine rflu_readbcfarfsection (pRegion)
subroutine rflu_readbcnoslipwallheatsect (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadBcInputFile.F90,v $ $Revision: 1.27 $'
Detailed Description
Definition at line 39 of file RFLU_ModReadBcInputFile.F90.
Member Function/Subroutine Documentation
subroutine rflu_readbcfarfsection (type(t_region), pointer pRegion) private
Definition at line 88 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcinflowtotangsection (type(t_region), pointer pRegion)
Definition at line 392 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcinflowveltempsection (type(t_region), pointer pRegion)
Definition at line 735 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcinjectsection (type(t_region), pointer pRegion)
Definition at line 1066 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcinputfile (type(t_region), pointer pRegion)
Definition at line 1446 of file RFLU_ModReadBcInputFile.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, CImg< T >::line(), moderror::registerfunction(), rflu_readbcfarfsection(), rflu_readbcinflowtotangsection(), rflu_readbcinflowveltempsection(), rflu_readbcinjectsection(), rflu_readbcnoslipwallheatsect(), rflu_readbcnoslipwalltempsect(), rflu_readbcoutflowsection(), rflu_readbcperiodicsection(), rflu_readbcslipwallsection(), rflu_readbcsymmetrysection(), rflu_readbcvirtualsection(), and Attribute::status().
Referenced by rflu_readbcinputfilewrapper().
subroutine, public rflu_readbcinputfilewrapper (type(t_region), pointer pRegion)
Definition at line 1635 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_readbcinputfile(), and spec_rflu_readbcinputfile().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rfluconv(), rfluinit(), rflupart(), rflupick(), and turb_initinputvalues().
subroutine rflu_readbcnoslipwallheatsect (type(t_region), pointer pRegion) private
Definition at line 1717 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcnoslipwalltempsect (type(t_region), pointer pRegion)
Definition at line 2054 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcoutflowsection (type(t_region), pointer pRegion)
Definition at line 2403 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcperiodicsection (type(t_region), pointer pRegion)
Definition at line 2740 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcslipwallsection (type(t_region), pointer pRegion)
Definition at line 2887 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcsymmetrysection (type(t_region), pointer pRegion)
Definition at line 3148 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
subroutine rflu_readbcvirtualsection (type(t_region), pointer pRegion)
Definition at line 3286 of file RFLU_ModReadBcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readbcinputfile().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadBcInputFile.F90,v $ $Revision: 1.27 $' private
Definition at line 59 of file RFLU_ModReadBcInputFile.F90.
The documentation for this module was generated from the following file:
RFLU_ModReadBcInputFile.F90