Rocstar: rflu_modgatherdata Module Reference
rflu_modgatherdata Module Reference
Public Member Functions
subroutine, public rflu_countgathereddata (pRegion, nVarsOut)
subroutine, public rflu_creategathereddata (pRegion, icType, gatherMode, nVarsOut, cv)
subroutine, public rflu_destroygathereddata (pRegion, cv)
subroutine, public rflu_gatherdata (pRegion, icType, gatherMode, cv)
subroutine, public rflu_scattergathereddata (pRegion, icType, gatherMode, cv)
Public Attributes
integer, parameter, public gather_mode_actual_only = 1
integer, parameter, public gather_mode_actual_virtual = 2
Detailed Description
Definition at line 45 of file RFLU_ModGatherData.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_countgathereddata (type(t_region), pointer pRegion, integer, intent(out) nVarsOut)
Definition at line 85 of file RFLU_ModGatherData.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_creategathereddata().
subroutine, public rflu_creategathereddata (type(t_region), pointer pRegion, integer, intent(in) icType, integer, intent(in) gatherMode, integer, intent(out) nVarsOut, real(rfreal), dimension(:,:), pointer cv)
Definition at line 173 of file RFLU_ModGatherData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_countgathereddata().
subroutine, public rflu_destroygathereddata (type(t_region), pointer pRegion, real(rfreal), dimension(:,:), pointer cv)
Definition at line 298 of file RFLU_ModGatherData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_gatherdata (type(t_region), pointer pRegion, integer, intent(in) icType, integer, intent(in) gatherMode, real(rfreal), dimension(:,:), pointer cv)
Definition at line 370 of file RFLU_ModGatherData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_scattergathereddata (type(t_region), pointer pRegion, integer, intent(in) icType, integer, intent(in) gatherMode, real(rfreal), dimension(:,:), pointer cv)
Definition at line 521 of file RFLU_ModGatherData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Member Data Documentation
integer, parameter, public gather_mode_actual_only = 1
Definition at line 63 of file RFLU_ModGatherData.F90.
integer, parameter, public gather_mode_actual_virtual = 2
Definition at line 63 of file RFLU_ModGatherData.F90.
The documentation for this module was generated from the following file:
RFLU_ModGatherData.F90