Rocstar: m_rocburn_1d_apn Module Reference
m_rocburn_1d_apn Module Reference
Public Member Functions
subroutine check_alloc (ierr)
subroutine initialize_0d (G_APN, comm, Indir, nxmax, To_read)
subroutine initialize_1d (G_APN, bflag, P_mks, To, rhoc_mks, p_coor, rb_mks, Toa, fr, Tn, Tflame)
subroutine get_burning_rate_1d (G_APN, delt, P_mks, To, Tn, qc_mks, qc_old_mks, qr_mks, qr_old_mks, rhoc_mks, Toa, rb_mks, fr, bflag, Tnp1, Tflame, p_coor)
subroutine finalize_0d (G_APN)
Detailed Description
Definition at line 23 of file Rocburn_1D_APN.f90.
Member Function/Subroutine Documentation
subroutine check_alloc (integer, intent(in) ierr)
Definition at line 61 of file Rocburn_1D_APN.f90.
References Aff_transformation_repS2< FT >::print().
subroutine finalize_0d (type (g_burn_1d), pointer G_APN)
Definition at line 239 of file Rocburn_1D_APN.f90.
Referenced by m_init_1dmodules::rocburn_init_funcs_apn(), m_init_1dmodules::rocburn_init_funcs_py(), and m_init_1dmodules::rocburn_init_funcs_zn().
subroutine get_burning_rate_1d (type (g_burn_1d), pointer G_APN, real(dbl), intent(in) delt, real(dbl), intent(in) P_mks, real(dbl), intent(in) To, real(dbl), dimension(:), intent(in) Tn, real(dbl), intent(in) qc_mks, real(dbl), intent(in) qc_old_mks, real(dbl), intent(in) qr_mks, real(dbl), intent(in) qr_old_mks, real(dbl), intent(in) rhoc_mks, real(dbl), intent(inout) Toa, real(dbl), intent(inout) rb_mks, real(dbl), intent(inout) fr, integer, intent(inout) bflag, real(dbl), dimension(:), intent(out) Tnp1, real(dbl), intent(out) Tflame, real(dbl), dimension(3), intent(in) p_coor)
Definition at line 182 of file Rocburn_1D_APN.f90.
References min().
Referenced by m_init_1dmodules::rocburn_init_funcs_apn(), m_init_1dmodules::rocburn_init_funcs_py(), m_init_1dmodules::rocburn_init_funcs_zn(), and m_rocburn_2d::update().
subroutine initialize_0d (type (g_burn_1d), pointer G_APN, integer, intent(in) comm, character(*), intent(in) Indir, integer, intent(out) nxmax, real(dbl), intent(out) To_read)
Definition at line 73 of file Rocburn_1D_APN.f90.
References apn_input_0d().
Referenced by m_init_1dmodules::rocburn_init_funcs_apn(), m_init_1dmodules::rocburn_init_funcs_py(), and m_init_1dmodules::rocburn_init_funcs_zn().
subroutine initialize_1d (type (g_burn_1d), pointer G_APN, integer, intent(inout) bflag, real(dbl), intent(in) P_mks, real(dbl), intent(in) To, real(dbl), intent(in) rhoc_mks, real(dbl), dimension(3), intent(in) p_coor, real(dbl), intent(out) rb_mks, real(dbl), intent(out) Toa, real(dbl), intent(out) fr, real(dbl), dimension(:), intent(out) Tn, real(dbl), intent(out) Tflame)
Definition at line 120 of file Rocburn_1D_APN.f90.
References min().
Referenced by m_init_1dmodules::rocburn_init_funcs_apn(), m_init_1dmodules::rocburn_init_funcs_py(), and m_init_1dmodules::rocburn_init_funcs_zn().
The documentation for this module was generated from the following file:
Rocburn_1D_APN.f90