Rocstar: Halfedge Class Reference
Halfedge Class Reference
This class encapsulate a halfedge over a window manifold.
#include <Manifold_2.h>
Public Member Functions
Halfedge ()
Halfedge (const Pane_manifold_2 *pm, Edge_ID e, Access_Mode mode)
Construct a Halfedge object from a pane manifold and its edge ID.
Halfedge opposite () const
Get the ID of the opposite edge of a given edge.
Halfedge prev () const
Get the previous halfedge of its owner element.
Halfedge next () const
Get the next halfedge of its owner element.
Node origin () const
Obtain the (primary copy of the) origin of the edge.
Node destination () const
Obtain the (primary copy of the) destination of the edge.
bool is_border () const
Is the edge a border edge?
bool is_physical_border () const
Is the edge on the physical boundary?
Vector_3< Real > tangent () const
Get the tangent of the given halfedge.
Vector_3< Real > normal () const
Get the normal of the incident facet.
Vector_3< Real > deformed_normal (const COM::Attribute *disp) const
Get the normal of the deformed shape (coordinates plus given displacements) of the incident facet of the halfedge.
void edge_center (Point_3< Real > &mid) const
Get the edge center of the given halfedge.
void face_center (Point_3< Real > &cnt) const
Get the face center of the incident face of a given halfedge.
template<class Value >
void edge_average (const COM::Attribute *attr, Value &val) const
Get the avarage value of the nodes of a given halfedge.
template<class Value >
void face_average (const COM::Attribute *attr, Value &val) const
Get the average value of the nodes of the incident face of a given halfedge.
double dihedral_angle () const
Return the dihedral angle at the edge.
const Pane_manifold_2 * pane_manifold () const
Obtain the pane manifold that owns the edge.
const COM::Pane * pane () const
Obtain the owner Pane_manifold_2 of the node.
Edge_ID id () const
Obtain the ID of the edge.
const void * addr (const COM::Attribute *attr) const
Obtain the address of an attribute associated with its bounded element.
const COM::Attribute * attr (const COM::Attribute *a) const
Obtain the attribute on the parent pane of the node.
bool operator== (const Halfedge &h) const
Are two halfedges the same?
bool operator!= (const Halfedge &h) const
Are two halfedges different?
bool operator< (const Halfedge &h) const
Does the current halfedge has a smaller ID then the given one?
Protected Attributes
const Pane_manifold_2 * _pm
Edge_ID _eID
Access_Mode _mode
Detailed Description
This class encapsulate a halfedge over a window manifold.
Definition at line 446 of file Manifold_2.h.
Constructor & Destructor Documentation
Halfedge () inline
Definition at line 448 of file Manifold_2.h.
 : _pm(NULL) {}
Halfedge (const Pane_manifold_2 * pm, Edge_ID e, Access_Mode mode) inline
Construct a Halfedge object from a pane manifold and its edge ID.
Definition at line 450 of file Manifold_2.h.
     : _pm( pm), _eID( e), _mode(mode) {}
Member Function Documentation
const void * addr (const COM::Attribute * attr) const
Obtain the address of an attribute associated with its bounded element.
Note: This function can be slow O(1) if the attribute is not on the current pane, and is even slower (O(log(#panes)) if not owned by the owner window of the pane.
Definition at line 1215 of file Manifold_2.C.
References _eID, _pm, attr(), COM_assertion, COM_assertion_msg, COM_get_sizeof(), is_border(), and Simple_manifold_2::pane().
{
   COM_assertion( !is_border());
   COM_assertion_msg( a, "Unexpected NULL pointer");
   COM_assertion_msg( a->is_elemental(), "Expect a element-centered attribute");
   const COM::Attribute *attr;
   const COM::Pane *pn = _pm->pane();
   int pid = pn->id();
   if ( a->pane()->id() == pid)
     attr = a;
   else {
     if ( a->window() != pn->window()) {
       pn = &a->window()->pane( pid);
       COM_assertion_msg( pn, "Pane does not exist");
     }
     attr=pn->attribute( a->id());
     COM_assertion_msg( attr, "Attribute does not exist");
   }
   return ((const char*)attr->pointer()) +
     COM_get_sizeof( attr->data_type(), attr->stride()*(_eID.eid()-1));
 }
const COM::Attribute* attr (const COM::Attribute * a) const inline
Obtain the attribute on the parent pane of the node.
Definition at line 556 of file Manifold_2.h.
References _pm, COM_assertion_msg, and Simple_manifold_2::pane().
Referenced by addr().
{
     COM_assertion_msg( a, "Unexpected NULL pointer");
     return a->window()->pane( _pm->pane()->id()).attribute(a->id());
   }
Vector_3< Real > deformed_normal (const COM::Attribute * disp) const
Get the normal of the deformed shape (coordinates plus given displacements) of the incident facet of the halfedge.
Definition at line 1290 of file Manifold_2.C.
References get_deformed_normal().
{
   return get_deformed_normal( *this, Vector_2<Real>( 0.5, 0.5), disp);
 }
Node destination () const inline
Obtain the (primary copy of the) destination of the edge.
Definition at line 472 of file Manifold_2.h.
References _eID, _mode, _pm, Simple_manifold_2::get_destination(), and Pane_manifold_2::get_primary().
Referenced by edge_average(), and tangent().
   { return _pm->get_primary( _pm->get_destination( _eID), _mode); }
double dihedral_angle () const
Return the dihedral angle at the edge.
If the edge is a border edge, then return pi.
If the edge is a border edge, then return pi. Note that this must be called after update_bd_normals has been called.
Definition at line 1297 of file Manifold_2.C.
References cimg_library::acos(), is_physical_border(), normal(), opposite(), pi, and sqrt().
{
   const double pi=3.14159265358979;
   if ( is_physical_border()) return pi;
   Halfedge hopp = opposite();
   if ( hopp.is_physical_border()) return pi;
   Vector_3<Real> normals[2] = { normal(), hopp.normal() };
   double cos_a = normals[0]*normals[1]
     / std::sqrt( (normals[0]*normals[0])*(normals[1]*normals[1]));
   // Resolve roundoff error
   if ( cos_a>1) cos_a=1;
   if ( cos_a<-1) cos_a=-1;
   return std::acos( cos_a);
 }
void edge_average (const COM::Attribute * attr, Value & val) const inline
Get the avarage value of the nodes of a given halfedge.
Value must have operators + and * defined.
Definition at line 508 of file Manifold_2.h.
References Node::addr(), destination(), and origin().
Referenced by edge_center(), and face_average().
{
     val = 0.5*(*reinterpret_cast<const Value *>(destination().addr(attr))+
                *reinterpret_cast<const Value *>(origin().addr(attr)));
   }
void edge_center (Point_3< Real > & mid) const inline
Get the edge center of the given halfedge.
Definition at line 495 of file Manifold_2.h.
References _pm, COM_NC, edge_average(), and Simple_manifold_2::pane().
   { edge_average( _pm->pane()->attribute( COM::COM_NC),
                   reinterpret_cast<Vector_3<Real> &>(mid)); }
void face_average (const COM::Attribute * attr, Value & val) const inline
Get the average value of the nodes of the incident face of a given halfedge.
If this is a border halfedge, then return its edge averagd. Value must have operators + and * defined.
Definition at line 517 of file Manifold_2.h.
References Node::addr(), edge_average(), is_border(), next(), and origin().
Referenced by face_center().
{
     // If this is a border halfedge, then return its edge center.
     if ( is_border()) { edge_average( attr, val); return; }
     // Otherwise, compute the center
     val = Value(0);
     int count=0;
     Halfedge h=*this, h0=h;
     do {
       val += *reinterpret_cast<const Value*>(h.origin().addr( attr));
       ++count;
     } while ( (h=h.next()) != h0);
     val/=count;
   }
void face_center (Point_3< Real > & cnt) const inline
Get the face center of the incident face of a given halfedge.
If this is a border halfedge, then return its midpoint.
Definition at line 501 of file Manifold_2.h.
References _pm, COM_NC, face_average(), and Simple_manifold_2::pane().
   { face_average( _pm->pane()->attribute( COM::COM_NC),
                   reinterpret_cast<Vector_3<Real> &>(cnt)); }
Edge_ID id () const inline
Obtain the ID of the edge.
Definition at line 547 of file Manifold_2.h.
References _eID.
Referenced by get_normal().
 { return _eID; }
bool is_border () const inline
Is the edge a border edge?
Definition at line 476 of file Manifold_2.h.
References _eID, _mode, _pm, and Pane_manifold_2::is_border_edge().
Referenced by Halfedge_data_structure_decorator< _HDS >::add_facet_to_border(), Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), addr(), Rocsurf::compute_edge_lengths(), Window_manifold_2::determine_primaries(), Halfedge_data_structure_decorator< _HDS >::erase_facet(), face_average(), Halfedge_data_structure_decorator< _HDS >::fill_hole(), Pane_manifold_2::get_next_edge(), get_normal(), Pane_manifold_2::get_prev_edge(), Node::is_border(), Halfedge_data_structure_decorator< _HDS >::join_vertex(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), Polyhedron_incremental_builder_3< HDS >::lookup_hole(), and Halfedge_data_structure_decorator< _HDS >::make_hole().
   { return _pm->is_border_edge( _eID, _mode); }
bool is_physical_border () const inline
Is the edge on the physical boundary?
Definition at line 480 of file Manifold_2.h.
References _eID, _pm, and Pane_manifold_2::is_physical_border_edge().
Referenced by dihedral_angle().
   { return _pm->is_physical_border_edge( _eID); }
Halfedge next () const inline
Get the next halfedge of its owner element.
If the current edge is a border edges, it returns the next border edge along the boundary.
Definition at line 465 of file Manifold_2.h.
References _eID, _mode, _pm, and Pane_manifold_2::get_next_edge().
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Rocsurf::compute_edge_lengths(), Halfedge_data_structure_decorator< _HDS >::erase_connected_component(), Halfedge_data_structure_decorator< _HDS >::erase_connected_component_face_cycle(), Halfedge_data_structure_decorator< _HDS >::erase_facet(), face_average(), Halfedge_data_structure_decorator< _HDS >::find_prev(), Halfedge_data_structure_decorator< _HDS >::find_prev_around_vertex(), Halfedge_data_structure_decorator< _HDS >::flip_edge(), get_deformed_normal(), Pane_manifold_2::get_prev_edge(), Halfedge_data_structure_decorator< _HDS >::insert_halfedge(), Halfedge_data_structure_decorator< _HDS >::insert_tip(), Halfedge_data_structure_decorator< _HDS >::inside_out(), Halfedge_data_structure_decorator< _HDS >::is_valid(), Halfedge_data_structure_decorator< _HDS >::join_facet(), Halfedge_data_structure_decorator< _HDS >::join_loop(), Halfedge_data_structure_decorator< _HDS >::join_vertex(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), Polyhedron_incremental_builder_3< HDS >::lookup_hole(), Halfedge_data_structure_decorator< _HDS >::remove_halfedge(), Halfedge_data_structure_decorator< _HDS >::remove_tip(), Halfedge_data_structure_decorator< _HDS >::reorient_facet(), Halfedge_data_structure_decorator< _HDS >::set_facet_in_facet_loop(), Halfedge_data_structure_decorator< _HDS >::set_vertex_in_vertex_loop(), and Halfedge_data_structure_decorator< _HDS >::split_loop().
 { return _pm->get_next_edge( _eID, _mode); }
Vector_3< Real > normal () const
Get the normal of the incident facet.
Definition at line 1259 of file Manifold_2.C.
References get_normal().
Referenced by c3d6nm(), and dihedral_angle().
{
   return get_normal( *this, Vector_2<Real>( 0.5, 0.5));
 }
bool operator!= (const Halfedge & h) const inline
Are two halfedges different?
Definition at line 566 of file Manifold_2.h.
References _eID, and _pm.
   { return _pm!=h._pm || _eID!=h._eID; }
bool operator< (const Halfedge & h) const inline
Does the current halfedge has a smaller ID then the given one?
Definition at line 570 of file Manifold_2.h.
References _eID, _pm, and Simple_manifold_2::pane().
{
     int pid1=_pm->pane()->id(), pid2=h._pm->pane()->id();
     return pid1<pid2 || pid1==pid2 && _eID<h._eID;
   }
bool operator== (const Halfedge & h) const inline
Are two halfedges the same?
Definition at line 562 of file Manifold_2.h.
References _eID, and _pm.
   { return _pm==h._pm && _eID==h._eID; }
Halfedge opposite () const inline
Get the ID of the opposite edge of a given edge.
Definition at line 454 of file Manifold_2.h.
References _eID, _mode, _pm, and Pane_manifold_2::get_opposite_edge().
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Halfedge_data_structure_decorator< _HDS >::close_tip(), Rocsurf::compute_edge_lengths(), Halfedge_data_structure_decorator< _HDS >::create_loop(), Halfedge_data_structure_decorator< _HDS >::create_segment(), dihedral_angle(), Halfedge_data_structure_decorator< _HDS >::erase_connected_component(), Halfedge_data_structure_decorator< _HDS >::erase_connected_component_face_cycle(), Halfedge_data_structure_decorator< _HDS >::erase_facet(), Halfedge_data_structure_decorator< _HDS >::find_prev_around_vertex(), Halfedge_data_structure_decorator< _HDS >::flip_edge(), Pane_manifold_2::get_next_edge(), Pane_manifold_2::get_prev_edge(), Halfedge_data_structure_decorator< _HDS >::insert_tip(), Halfedge_data_structure_decorator< _HDS >::is_valid(), Halfedge_data_structure_decorator< _HDS >::join_facet(), Halfedge_data_structure_decorator< _HDS >::join_loop(), Halfedge_data_structure_decorator< _HDS >::join_vertex(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), Polyhedron_incremental_builder_3< HDS >::lookup_hole(), Halfedge_data_structure_decorator< _HDS >::remove_tip(), Halfedge_data_structure_decorator< _HDS >::set_vertex_in_vertex_loop(), Halfedge_data_structure_decorator< _HDS >::split_facet(), Halfedge_data_structure_decorator< _HDS >::split_loop(), and Halfedge_data_structure_decorator< _HDS >::split_vertex().
   { return _pm->get_opposite_edge( _eID, _mode); }
Node origin () const inline
Obtain the (primary copy of the) origin of the edge.
Definition at line 468 of file Manifold_2.h.
References _eID, _mode, _pm, Simple_manifold_2::get_origin(), and Pane_manifold_2::get_primary().
Referenced by edge_average(), face_average(), get_deformed_normal(), and tangent().
   { return _pm->get_primary( _pm->get_origin( _eID), _mode); }
const COM::Pane* pane () const inline
Obtain the owner Pane_manifold_2 of the node.
Definition at line 543 of file Manifold_2.h.
References _pm, and Simple_manifold_2::pane().
Referenced by get_normal(), and Pane_manifold_2::size_of_edges().
   { if ( _pm) return _pm->pane(); else return NULL; }
const Pane_manifold_2* pane_manifold () const inline
Obtain the pane manifold that owns the edge.
Definition at line 540 of file Manifold_2.h.
References _pm.
Referenced by get_normal(), Pane_manifold_2::get_opposite_edge(), Node::halfedge(), Pane_manifold_2::is_border_edge(), and Pane_manifold_2::size_of_edges().
 { return _pm; }
Halfedge prev () const inline
Get the previous halfedge of its owner element.
If the current edge is a border edges, it returns the previous border edge along the boundary.
Definition at line 460 of file Manifold_2.h.
References _eID, _mode, _pm, and Pane_manifold_2::get_prev_edge().
Referenced by Halfedge_data_structure_decorator< _HDS >::find_prev(), Halfedge_data_structure_decorator< _HDS >::find_prev_around_vertex(), Pane_manifold_2::get_next_edge(), and Halfedge_data_structure_decorator< _HDS >::get_prev().
 { return _pm->get_prev_edge( _eID, _mode); }
Vector_3<Real> tangent () const inline
Get the tangent of the given halfedge.
Definition at line 484 of file Manifold_2.h.
References destination(), origin(), and Node::point().
Referenced by Rocsurf::compute_edge_lengths(), and get_tangent().
   { return destination().point()-origin().point(); }
Member Data Documentation
Edge_ID _eID protected
Definition at line 577 of file Manifold_2.h.
Referenced by addr(), destination(), id(), is_border(), is_physical_border(), next(), operator!=(), operator<(), operator==(), opposite(), origin(), and prev().
Access_Mode _mode protected
Definition at line 578 of file Manifold_2.h.
Referenced by destination(), is_border(), next(), opposite(), origin(), and prev().
const Pane_manifold_2* _pm protected
Definition at line 576 of file Manifold_2.h.
Referenced by addr(), attr(), destination(), edge_center(), face_center(), is_border(), is_physical_border(), next(), operator!=(), operator<(), operator==(), opposite(), origin(), pane(), pane_manifold(), and prev().
The documentation for this class was generated from the following files:
Manifold_2.h
Manifold_2.C