Rocstar: manual_index_pts Class Reference
manual_index_pts Class Reference
#include <points.h>
Public Member Functions
manual_index_pts ()
~manual_index_pts ()
manual_index_pts (const manual_index_pts &mip)
manual_index_pts & operator= (const manual_index_pts &mip)
virtual manual_index_pts * clone ()
void set_layout (std::vector< int > index_layout)
void set_index (int point_num, std::vector< int > loc)
Public Member Functions inherited from indexed_points
indexed_points ()
virtual ~indexed_points ()
indexed_points (const indexed_points &ip)
indexed_points & operator= (const indexed_points &ip)
virtual void sort ()
pnt get_indexed_point (std::vector< int > loc)
virtual int get_closest (long double *coord)
virtual std::vector< int > get_connected_points (int point_num)
virtual std::vector< int > get_dim ()
Public Member Functions inherited from points
points ()
points (int num_points)
points (const points &p)
points & operator= (const points &p)
virtual ~points ()
void set_num_points (int n)
void set_num_vars (int n)
void set_num_indep_vars (int indep_vars)
int get_num_points ()
int get_num_vars ()
int get_num_indep_vars ()
void set_point_val (int point_number, int var, long double val)
void clear_dep_vars (int point_number)
pnt get_point (int n)
long double largest_val (int dim)
long double smallest_val (int dim)
Additional Inherited Members
Static Public Member Functions inherited from points
static void delete_all (std::vector< points * > points_vector)
static bool contains_null (std::vector< points * > points_vector)
Protected Attributes inherited from indexed_points
VariableDimensionArray index
bool index_set
std::vector< int > index_layout
Protected Attributes inherited from points
int num_points
int num_vars
int num_indep_vars
pnt ** pt_str
bitmap pt_set
Detailed Description
Definition at line 183 of file points.h.
Constructor & Destructor Documentation
manual_index_pts ()
Definition at line 520 of file points.cpp.
Referenced by clone().
{
     return;
 }
~manual_index_pts ()
Definition at line 524 of file points.cpp.
{
     return;
 }
manual_index_pts (const manual_index_pts & mip)
Definition at line 528 of file points.cpp.
                                                               : indexed_points(mip) {
     return;
 }
Member Function Documentation
manual_index_pts * clone () virtual
Reimplemented from indexed_points.
Definition at line 537 of file points.cpp.
References manual_index_pts().
{
     return new manual_index_pts(*this);
 }
manual_index_pts & operator= (const manual_index_pts & mip)
Definition at line 532 of file points.cpp.
References indexed_points::operator=().
{
     indexed_points::operator = (mip);
     return *this;
 }
void set_index (int point_num, std::vector< int > loc)
Definition at line 555 of file points.cpp.
References indexed_points::index, and VariableDimensionArray::setValue().
Referenced by tpz_ordered::build_point_index().
{
     index.setValue(loc, point_num);
 }
void set_layout (std::vector< int > index_layout)
Definition at line 541 of file points.cpp.
References i, indexed_points::index, indexed_points::index_set, and VariableDimensionArray::initArray().
Referenced by tpz_ordered::build_point_index().
{
     this->index_layout.erase(this->index_layout.begin(), this->index_layout.end());
     for(int i=0; i<index_layout.size(); i++){
         this->index_layout.push_back(index_layout[i]);
     }
     index.initArray(index_layout);
     index_set = true;
 }
The documentation for this class was generated from the following files:
points.h
points.cpp