Rocstar: MarkerParticles_3 Class Reference
MarkerParticles_3 Class Reference
#include <MarkerParticles_3.h>
Public Member Functions
MarkerParticles_3 (Manifold *wm, COM::Window *buf)
Construct an object from a window manifold.
virtual double time_stepping (const COM::Attribute *spd, double dt, COM::Attribute *disp, int *smoothed=NULL)
Main entry of the algorithm.
Public Member Functions inherited from Propagation_3
Propagation_3 ()
virtual ~Propagation_3 ()
Propagation_3 (Manifold *wm, COM::Window *buf)
Construct an object from a window manifold.
virtual void set_constraints (const COM::Attribute *cnstr_types)
Set the types and directions of nodal constraints.
void set_bounds (const COM::Attribute *bnd)
Set the bounds.
void bound_facial_speed (COM::Attribute *fa)
virtual void enforce_nodal_constraints (COM::Attribute *du)
Enforces the nodal constraints by projecting motion onto given direction.
virtual void bound_nodal_motion (COM::Attribute *disps)
void set_verbose (bool b)
Set the verbose level.
Protected Member Functions
void multiply_nodal_normals (const COM::Attribute *a, COM::Attribute *b)
Protected Member Functions inherited from Propagation_3
void convert_constraints (const COM::Attribute *ctypes_faces, COM::Attribute *ctypes_nodes)
Convert facial constraints to nodal constraints.
void determine_constraint_boundary (const COM::Attribute *ctypes_faces, COM::Attribute *ctypes_bndry_edges, COM::Attribute *ctypes_bndry_nodes)
Convert facial or panel constraints to nodal constraints.
Additional Inherited Members
Static Protected Member Functions inherited from Propagation_3
static void get_constraint_directions (int type, int &ndirs, Vector_3 dirs[2])
Get orthonormals of the constraints.
static void enforce_nodal_constraint (int type, Vector_3 &du)
Enforce constraint for a specific vector.
static void bound_nodal_motion (const Point_3 &pnt, const double *bnd, Vector_3 &du, double eps=0)
static bool check_spherical_bound (const Point_3 &pnt, const Point_3 &org, const double rad_min, const double rad_max, double eps=0)
static void bound_spherical_disp (const Point_3 &pnt, const Point_3 &org, const double rad_min, const double rad_max, Vector_3 &disp, double eps=0)
static bool check_radial_bound (const double x, const double y, const double bnd_min, const double bnd_max, double eps=0)
static void bound_radial_disp (const double x, const double y, const double bnd_min, const double bnd_max, double &dx, double &dy, double eps=0)
static bool check_axial_bound (const double x, const double bnd_min, const double bnd_max, double eps=0)
static void bound_axial_disp (const double x, const double bnd_min, const double bnd_max, double &dx, double eps=0)
static bool reached_nodal_bound (const Point_3 &pnt, const double *bnd, double eps=0)
static bool in_bounding_box (const Point_3 &pnt, const Point_3 &lb, const Point_3 &ub)
static double square (double x)
Protected Attributes inherited from Propagation_3
Manifold * _surf
SURF::Access_Mode _mode
COM::Window * _buf
int _rank
bool _verb
bool _cnstr_set
bool _bnd_set
COM::Attribute * _cnstr_nodes
COM::Attribute * _cnstr_faces
COM::Attribute * _cnstr_bndry_edges
COM::Attribute * _cnstr_bndry_nodes
COM::Attribute * _cnstr_bound
std::vector< COM::Pane * > _panes
Detailed Description
Definition at line 38 of file MarkerParticles_3.h.
Constructor & Destructor Documentation
MarkerParticles_3 (Manifold * wm, COM::Window * buf) inline
Construct an object from a window manifold.
Definition at line 41 of file MarkerParticles_3.h.
     : Propagation_3( wm, buf) {}
Member Function Documentation
void multiply_nodal_normals (const COM::Attribute * a, COM::Attribute * b) protected
Definition at line 45 of file MarkerParticles_3.C.
References Propagation_3::_surf, COM_DOUBLE, COM_MESH, E2N_ANGLE, Attribute::inherit(), and Rocblas::mul().
Referenced by time_stepping().
{
   assert( spd->size_of_components()==1);
   if ( spd->is_nodal()) {
     // compute normals
     _surf->compute_normals( disp);
     // If spd is not elemental, simply need call Rocblas
     Rocblas::mul( disp, spd, disp);
   }
   else {
     // Create a buffer window to store the element normals
     COM::Window *win = disp->window();
     COM::Window buf( win->name()+"-marker", win->get_communicator());
     buf.inherit( win->attribute( COM::COM_MESH), "", false, true, NULL, 0);
     Attribute *node_disps = buf.inherit( disp, "disps", false, true, NULL, 0);
     buf.inherit(const_cast<COM::Attribute*>(spd), "spd", false, true, NULL, 0);
     Attribute *elem_normals =
       buf.new_attribute( "elem_normals", 'e', COM_DOUBLE, 3, "");
     buf.resize_array( "elem_normals", 0, NULL);
     buf.init_done();
     // First, compute elemental normals
     _surf->compute_normals( elem_normals);
     // Multiply elemental normals by speed
     Rocblas::mul( elem_normals, spd, elem_normals);
     // Convert elemental motion to nodal motion
     _surf->elements_to_nodes( elem_normals, node_disps, SURF::E2N_ANGLE);
   }
 }
PROP_BEGIN_NAMESPACE double time_stepping (const COM::Attribute * spd, double dt, COM::Attribute * disp, int * smoothed = NULL) virtual
Main entry of the algorithm.
Implements Propagation_3.
Definition at line 31 of file MarkerParticles_3.C.
References COM_assertion, Rocblas::mul_scalar(), and multiply_nodal_normals().
{
   COM_assertion( spd->size_of_components()==1);
   COM_assertion( disp->size_of_components()==3 && disp->is_nodal());
   multiply_nodal_normals( spd, disp);
   Rocblas::mul_scalar( disp, &dt, disp);
   if ( smoothed) *smoothed = false;
   return dt;
 }
The documentation for this class was generated from the following files:
MarkerParticles_3.h
MarkerParticles_3.C