Rocstar: GeomTSTTCommon Class Reference
GeomTSTTCommon Class Reference
Common code for specific implementations of MeshDomain on TSTT interfaces.
Public Member Functions
GeomTSTTCommon (TSTTG::Geometry &geom) throw (TSTTB::Error)
virtual ~GeomTSTTCommon ()
void move_to (void *geom_handle, Vector3D &coord) const throw (TSTTB::Error)
Evaluate the closest point to the input position on the specified geometric entity and return the result in the passed position argument (move the passed position onto the geometry.)
void normal (void *geom_handle, Vector3D &coord) const throw (TSTTB::Error)
Given a geometric entity and a position, evaluate the normal on the geometric entity at the closest point on that entity to the input position, and pass back the result in the input coord vector.
void normal (void *geom_handle, Vector3D coords[], unsigned count) const throw (TSTTB::Error)
Given a geometric entity and a position, evaluate the normal on the geometric entity at the closest point on that entity to the input position, and pass back the result in the input coord vector.
void closest_and_normal (void *geom_handle, const Vector3D &position, Vector3D &closest, Vector3D &normal) const throw (TSTTB::Error)
Given a geometric entity and a position, get point on the geometric entity closest to the input position, and the surface normal at that position.
Public Attributes
TSTTG::Shape geomIface
TSTT geometry interface implementation to query.
sidl::array< void * > geomHandles
Temporary storage for geometry entity handles.
sidl::array< double > positionsIn
Temporary storate for input and output vectors.
sidl::array< double > positionsOut
sidl::array< double > normalsOut
Detailed Description
Common code for specific implementations of MeshDomain on TSTT interfaces.
This class contains the common functionality used by concrete implementations of MeshDomain on the TSTT geometry interface.
Definition at line 55 of file GeomTSTT.cpp.
Constructor & Destructor Documentation
GeomTSTTCommon (TSTTG::Geometry & geom) throw (TSTTB::Error)
Parameters
geom The TSTT geometry interface implementation to query
Definition at line 407 of file GeomTSTT.cpp.
   : geomIface( geom ),
     geomHandles( alloc_sidl_vector<void*>(1) ),
     positionsIn( alloc_sidl_vector<double>(3) )
 {
 }
~GeomTSTTCommon () virtual
Definition at line 414 of file GeomTSTT.cpp.
 {}
Member Function Documentation
void closest_and_normal (void * geom_handle, const Vector3D & position, Vector3D & closest, Vector3D & normal) const throw (TSTTB::Error)
Given a geometric entity and a position, get point on the geometric entity closest to the input position, and the surface normal at that position.
Definition at line 479 of file GeomTSTT.cpp.
References Mesquite::convert_from_sidl_vector(), and Mesquite::convert_to_sidl_vector().
Referenced by DomainTSTT::closest_point(), and GeomEntTSTT::closest_point().
 {
     // going to assume this in the following reinterpret_cast, so
     // check to make sure it is true
   assert( sizeof(Vector3D) == 3*sizeof(double) );
   memcpy( convert_from_sidl_vector(positionsIn), &position, 3*sizeof(double) );
   positionsOut = convert_to_sidl_vector( reinterpret_cast<double*>(&closest), 3 );
   normalsOut = convert_to_sidl_vector( reinterpret_cast<double*>(&normal), 3 );
   *convert_from_sidl_vector( geomHandles ) = geom;
   int junk1, junk2;
   geomIface.gentityClosestPointAndNormal( geomHandles,  1,
                                           positionsIn,  3,
                                           positionsOut, junk1,
                                           normalsOut,   junk2 );
 }
void move_to (void * geom_handle, Vector3D & coord) const throw (TSTTB::Error)
Evaluate the closest point to the input position on the specified geometric entity and return the result in the passed position argument (move the passed position onto the geometry.)
Definition at line 418 of file GeomTSTT.cpp.
References Mesquite::convert_from_sidl_vector(), Mesquite::convert_to_sidl_vector(), and coord.
Referenced by DomainTSTT::snap_to(), and GeomEntTSTT::snap_to().
 {
     // going to assume this in the following reinterpret_cast, so
     // check to make sure it is true
   assert( sizeof(Vector3D) == 3*sizeof(double) );
   memcpy( convert_from_sidl_vector(positionsIn), &coord, 3*sizeof(double) );
   positionsOut = convert_to_sidl_vector( reinterpret_cast<double*>(&coord), 3 );
   *convert_from_sidl_vector( geomHandles ) = geom;
   int junk = 3;
   geomIface.gentityClosestPoint( geomHandles,  1,
                                  positionsIn,  3,
                                  positionsOut, junk );
 }
void normal (void * geom_handle, Vector3D & coord) const throw (TSTTB::Error)
Given a geometric entity and a position, evaluate the normal on the geometric entity at the closest point on that entity to the input position, and pass back the result in the input coord vector.
Definition at line 437 of file GeomTSTT.cpp.
References Mesquite::convert_from_sidl_vector(), Mesquite::convert_to_sidl_vector(), and coord.
Referenced by DomainTSTT::normal_at(), and GeomEntTSTT::normal_at().
 {
     // going to assume this in the following reinterpret_cast, so
     // check to make sure it is true
   assert( sizeof(Vector3D) == 3*sizeof(double) );
   memcpy( convert_from_sidl_vector(positionsIn), &coord, 3*sizeof(double) );
   normalsOut = convert_to_sidl_vector( reinterpret_cast<double*>(&coord), 3 );
   *convert_from_sidl_vector( geomHandles ) = geom;
   int junk;
   geomIface.gentityNormal( geomHandles, 1,
                            positionsIn, 3,
                            normalsOut,  junk );
 }
void normal (void * geom_handle, Vector3D coords[], unsigned count) const throw (TSTTB::Error)
Given a geometric entity and a position, evaluate the normal on the geometric entity at the closest point on that entity to the input position, and pass back the result in the input coord vector.
Definition at line 454 of file GeomTSTT.cpp.
References Mesquite::convert_from_sidl_vector(), and Mesquite::convert_to_sidl_vector().
 {
     // going to assume this in the following reinterpret_cast, so
     // check to make sure it is true
   assert( sizeof(Vector3D) == 3*sizeof(double) );
   if (positionsIn.upper(0)+1 < 3*(int)count)
     positionsIn = positionsIn.create1d( 3*count );
   memcpy( convert_from_sidl_vector(positionsIn), coords, 3*count*sizeof(double) );
   normalsOut = convert_to_sidl_vector( reinterpret_cast<double*>(coords), 3*count );
   if (geomHandles.upper(0)+1 < (int)count)
     geomHandles = geomHandles.create1d( count );
   void** ptr = convert_from_sidl_vector( geomHandles );
   for (void** end = ptr + count; ptr != end; ++ptr)
     *ptr = geom;
   int junk;
   geomIface.gentityNormal( geomHandles, count,
                            positionsIn, 3*count,
                            normalsOut,  junk );
 }
Member Data Documentation
sidl::array<void*> geomHandles mutable
Temporary storage for geometry entity handles.
Definition at line 99 of file GeomTSTT.cpp.
TSTTG::Shape geomIface mutable
TSTT geometry interface implementation to query.
Definition at line 96 of file GeomTSTT.cpp.
sidl::array<double> normalsOut mutable
Definition at line 101 of file GeomTSTT.cpp.
sidl::array<double> positionsIn mutable
Temporary storate for input and output vectors.
Definition at line 101 of file GeomTSTT.cpp.
sidl::array<double> positionsOut mutable
Definition at line 101 of file GeomTSTT.cpp.
The documentation for this class was generated from the following file:
GeomTSTT.cpp