Rocstar: DirectionS3< FT > Class Template Reference
DirectionS3< FT > Class Template Reference
#include <DirectionS3.h>
Public Member Functions
DirectionS3 ()
DirectionS3 (const VectorS3< FT > &v)
DirectionS3 (const FT &x, const FT &y, const FT &z)
bool operator== (const DirectionS3< FT > &d) const
bool operator!= (const DirectionS3< FT > &d) const
VectorS3< FT > to_vector () const
VectorS3< FT > vector () const
DirectionS3 transform (const Aff_transformationS3< FT > &t) const
DirectionS3 operator- () const
const FT & delta (int i) const
const FT & dx () const
const FT & dy () const
const FT & dz () const
const FT & hdx () const
const FT & hdy () const
const FT & hdz () const
FT hw () const
Public Attributes
FT e0
FT e1
FT e2
Detailed Description
template<class FT>
class DirectionS3< FT >
Definition at line 59 of file DirectionS3.h.
Constructor & Destructor Documentation
DirectionS3 () inline
Definition at line 62 of file DirectionS3.h.
 {}
DirectionS3 (const VectorS3< FT > & v)
Definition at line 96 of file DirectionS3.h.
References VectorS3< FT >::e0, VectorS3< FT >::e1, and VectorS3< FT >::e2.
 {
   e0 = v.e0;
   e1 = v.e1;
   e2 = v.e2;
 }
DirectionS3 (const FT & x, const FT & y, const FT & z) inline
Definition at line 64 of file DirectionS3.h.
                   : e0(x), e1(y), e2(z) {}
Member Function Documentation
const FT & delta (int i) const
Definition at line 144 of file DirectionS3.h.
References CGAL_kernel_precondition.
 {
   CGAL_kernel_precondition( i >= 0 && i <= 2 );
   return (i==0) ? dx() :
          (i==1) ? dy() : dz() ;
 }
const FT & dx () const inline
Definition at line 155 of file DirectionS3.h.
Referenced by DirectionS3< FT >::operator==(), and PlaneS3< FT >::PlaneS3().
 { return e0; }
const FT & dy () const inline
Definition at line 162 of file DirectionS3.h.
Referenced by DirectionS3< FT >::operator==(), and PlaneS3< FT >::PlaneS3().
 { return e1; }
const FT & dz () const inline
Definition at line 169 of file DirectionS3.h.
Referenced by DirectionS3< FT >::operator==(), and PlaneS3< FT >::PlaneS3().
 { return e2; }
const FT & hdx () const inline
Definition at line 175 of file DirectionS3.h.
 { return e0; }
const FT & hdy () const inline
Definition at line 182 of file DirectionS3.h.
 { return e1; }
const FT & hdz () const inline
Definition at line 189 of file DirectionS3.h.
 { return e2; }
FT hw () const inline
Definition at line 195 of file DirectionS3.h.
 { return FT(1); }
bool operator!= (const DirectionS3< FT > & d) const inline
Definition at line 118 of file DirectionS3.h.
 { return !(*this == d); }
DirectionS3< FT > operator- () const inline
Definition at line 138 of file DirectionS3.h.
 { return DirectionS3<FT>(-dx(), -dy(), -dz()); }
bool operator== (const DirectionS3< FT > & d) const
Definition at line 105 of file DirectionS3.h.
References CGAL_NTS, DirectionS3< FT >::dx(), DirectionS3< FT >::dy(), DirectionS3< FT >::dz(), and sign().
 {
   return  ( dx()*d.dy() == dy()*d.dx() )
         &&( dx()*d.dz() == dz()*d.dx() )
         &&( dy()*d.dz() == dz()*d.dy() )
         &&( CGAL_NTS sign( dx() ) == CGAL_NTS sign( d.dx() ) )
         &&( CGAL_NTS sign( dy() ) == CGAL_NTS sign( d.dy() ) )
         &&( CGAL_NTS sign( dz() ) == CGAL_NTS sign( d.dz() ) );
 }
VectorS3< FT > to_vector () const inline
Definition at line 124 of file DirectionS3.h.
Referenced by DirectionS3< FT >::vector().
 { return VectorS3<FT>(*this); }
DirectionS3< FT > transform (const Aff_transformationS3< FT > & t) const inline
Definition at line 131 of file DirectionS3.h.
References Aff_transformationS3< FT >::transform().
 { return t.transform(*this); }
VectorS3<FT> vector () const inline
Definition at line 71 of file DirectionS3.h.
References DirectionS3< FT >::to_vector().
Referenced by LineS3< FT >::LineS3(), RayS3< FT >::RayS3(), and Aff_transformation_repS3< FT >::transform().
 { return to_vector(); }
Member Data Documentation
FT e0
Definition at line 90 of file DirectionS3.h.
Referenced by VectorS3< FT >::hx(), VectorS3< FT >::VectorS3(), and VectorS3< FT >::x().
FT e1
Definition at line 91 of file DirectionS3.h.
Referenced by VectorS3< FT >::hy(), VectorS3< FT >::VectorS3(), and VectorS3< FT >::y().
FT e2
Definition at line 92 of file DirectionS3.h.
Referenced by VectorS3< FT >::hz(), VectorS3< FT >::VectorS3(), and VectorS3< FT >::z().
The documentation for this class was generated from the following file:
DirectionS3.h