Rocstar: plag_moddimensions Module Reference
plag_moddimensions Module Reference
Public Member Functions
subroutine, public plag_calcnpclsglobal (regions)
subroutine, public plag_printdimensions (pRegion)
subroutine, public plag_printnpclsglobal (pRegion)
subroutine, public plag_rflu_readdimensions (pRegion)
subroutine, public plag_setdimensions (pRegion, nPcls)
subroutine, public plag_setmaxdimensions (pRegion)
subroutine, public plag_rflu_writedimensions (pRegion)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_ModDimensions.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 39 of file PLAG_ModDimensions.F90.
Member Function/Subroutine Documentation
subroutine, public plag_calcnpclsglobal (type(t_region), dimension(:), pointer regions)
Definition at line 101 of file PLAG_ModDimensions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_endflowsolver(), and rflu_timestepping().
subroutine, public plag_printdimensions (type(t_region), pointer pRegion)
Definition at line 221 of file PLAG_ModDimensions.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions().
subroutine, public plag_printnpclsglobal (type(t_region), pointer pRegion)
Definition at line 301 of file PLAG_ModDimensions.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_endflowsolver(), and rflu_timestepping().
subroutine, public plag_rflu_readdimensions (type(t_region), pointer pRegion)
Definition at line 380 of file PLAG_ModDimensions.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_moddimensions::rflu_readdimensionswrapper().
subroutine, public plag_rflu_writedimensions (type(t_region), pointer pRegion)
Definition at line 795 of file PLAG_ModDimensions.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_endflowsolver(), rflu_timestepping(), rflu_moddimensions::rflu_writedimensionswrapper(), and rfluinit().
subroutine, public plag_setdimensions (type(t_region), pointer pRegion, integer, intent(in) nPcls)
Definition at line 652 of file PLAG_ModDimensions.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rfluinit().
subroutine, public plag_setmaxdimensions (type(t_region), pointer pRegion)
Definition at line 716 of file PLAG_ModDimensions.F90.
References moderror::deregisterfunction(), max(), and moderror::registerfunction().
Referenced by plag_modreallocatememory::plag_reallocmemwrapper(), and rfluinit().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_ModDimensions.F90,v $ $Revision: 1.7 $' private
Definition at line 73 of file PLAG_ModDimensions.F90.
The documentation for this module was generated from the following file:
PLAG_ModDimensions.F90