Rocstar: plag_rflu_modcomm Module Reference
plag_rflu_modcomm Module Reference
Public Member Functions
subroutine, public plag_rflu_commdriver (regions)
subroutine, public plag_rflu_initsendcounters (pRegion)
Private Member Functions
subroutine plag_rflu_clearrequest (global, request)
subroutine plag_rflu_clearrequestwrapper (pRegion, iReqFlag)
subroutine plag_rflu_copycounters (regions)
subroutine plag_rflu_copydata (regions)
subroutine plag_rflu_copydataint (global, pclData, pclData2)
subroutine plag_rflu_copydatareal (global, pclData, pclData2)
subroutine plag_rflu_createbuffersrecv (pRegion)
subroutine plag_rflu_createbufferssend (pRegion)
subroutine plag_rflu_destroybuffersrecv (pRegion)
subroutine plag_rflu_destroybufferssend (pRegion)
subroutine plag_rflu_initrecvcounters (pRegion)
subroutine plag_rflu_isendcounters (pRegion)
subroutine plag_rflu_isenddata (pRegion)
subroutine plag_rflu_loadbufferssend (pRegion)
subroutine plag_rflu_recvcounters (pRegion)
subroutine plag_rflu_recvdata (pRegion)
subroutine plag_rflu_totalnpclscomm (regions)
subroutine plag_rflu_unloadbuffersrecv (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: PLAG_RFLU_ModComm.F90,v $ $Revision: 1.11 $'
integer, parameter, private request_type_counter = 1
integer, parameter, private request_type_data = 2
Detailed Description
Definition at line 39 of file PLAG_RFLU_ModComm.F90.
Member Function/Subroutine Documentation
subroutine plag_rflu_clearrequest (type(t_global), pointer global, integer, intent(inout) request) private
Definition at line 106 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and Attribute::status().
Referenced by plag_rflu_clearrequestwrapper().
subroutine plag_rflu_clearrequestwrapper (type(t_region), pointer pRegion, integer, intent(in) iReqFlag) private
Definition at line 179 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), plag_rflu_clearrequest(), and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine, public plag_rflu_commdriver (type(t_region), dimension(:), pointer regions)
Definition at line 274 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_calcderivedvariables(), plag_modreallocatememory::plag_reallocmemwrapper(), plag_rflu_clearrequestwrapper(), plag_rflu_copycounters(), plag_rflu_copydata(), plag_rflu_createbuffersrecv(), plag_rflu_createbufferssend(), plag_rflu_destroybuffersrecv(), plag_rflu_destroybufferssend(), plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), plag_rflu_modfindcells::plag_rflu_findcellstrajsafe(), plag_rflu_initrecvcounters(), plag_rflu_initsendcounters(), plag_rflu_isendcounters(), plag_rflu_isenddata(), plag_rflu_loadbufferssend(), plag_rflu_recvcounters(), plag_rflu_recvdata(), plag_rflu_totalnpclscomm(), plag_rflu_unloadbuffersrecv(), and moderror::registerfunction().
Referenced by rungekuttamp().
subroutine plag_rflu_copycounters (type(t_region), dimension(:), pointer regions) private
Definition at line 701 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_copydata (type(t_region), dimension(:), pointer regions) private
Definition at line 789 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_rflu_copydataint(), plag_rflu_copydatareal(), and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_copydataint (type(t_global), pointer global, integer, dimension(:,:), intent(in) pclData, integer, dimension(:,:), intent(out) pclData2) private
Definition at line 908 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_copydata().
subroutine plag_rflu_copydatareal (type(t_global), pointer global, real(rfreal), dimension(:,:), intent(in) pclData, real(rfreal), dimension(:,:), intent(out) pclData2) private
Definition at line 996 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_copydata().
subroutine plag_rflu_createbuffersrecv (type(t_region), pointer pRegion) private
Definition at line 1087 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_createbufferssend (type(t_region), pointer pRegion) private
Definition at line 1196 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_destroybuffersrecv (type(t_region), pointer pRegion) private
Definition at line 1303 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_destroybufferssend (type(t_region), pointer pRegion) private
Definition at line 1411 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_initrecvcounters (type(t_region), pointer pRegion) private
Definition at line 1507 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine, public plag_rflu_initsendcounters (type(t_region), pointer pRegion)
Definition at line 1586 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_rflu_commdriver(), and plag_rflu_update().
subroutine plag_rflu_isendcounters (type(t_region), pointer pRegion) private
Definition at line 1664 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and RFC_Data_const< _Tag >::tag().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_isenddata (type(t_region), pointer pRegion) private
Definition at line 1760 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_loadbufferssend (type(t_region), pointer pRegion) private
Definition at line 1889 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and StopWatch::stop().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_recvcounters (type(t_region), pointer pRegion) private
Definition at line 2072 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), Attribute::status(), and RFC_Data_const< _Tag >::tag().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_recvdata (type(t_region), pointer pRegion) private
Definition at line 2166 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, moderror::registerfunction(), and Attribute::status().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_totalnpclscomm (type(t_region), dimension(:), pointer regions) private
Definition at line 2293 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_commdriver().
subroutine plag_rflu_unloadbuffersrecv (type(t_region), pointer pRegion) private
Definition at line 2429 of file PLAG_RFLU_ModComm.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and StopWatch::stop().
Referenced by plag_rflu_commdriver().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: PLAG_RFLU_ModComm.F90,v $ $Revision: 1.11 $' private
Definition at line 72 of file PLAG_RFLU_ModComm.F90.
integer, parameter, private request_type_counter = 1 private
Definition at line 75 of file PLAG_RFLU_ModComm.F90.
integer, parameter, private request_type_data = 2 private
Definition at line 75 of file PLAG_RFLU_ModComm.F90.
The documentation for this module was generated from the following file:
PLAG_RFLU_ModComm.F90