Rocstar: MassTransfer Class Reference
MassTransfer Class Reference
#include <basic_actions.h>
Public Member Functions
MassTransfer (FluidAgent *ag, BurnAgent *bag, const std::string b_rhos, const std::string b_rb, const std::string f_mdot)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, char *name=NULL)
Action (int n, const char *at[], int *i=NULL, void *p=0, char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
FluidAgent * fagent
BurnAgent * bagent
int f_mdot_hdl
int b_rhos_hdl
int b_rb_hdl
int fb_mdot_hdl
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_attribute_handle (int i)
int get_attribute_handle_const (int i)
int get_attribute_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Detailed Description
Definition at line 189 of file basic_actions.h.
Constructor & Destructor Documentation
MassTransfer (FluidAgent * ag, BurnAgent * bag, const std::string b_rhos, const std::string b_rb, const std::string f_mdot)
Definition at line 655 of file basic_actions.C.
References bagent, BurnAgent::iburn_all, Action::IN, Action::OUT, BurnAgent::parentWin, Agent::register_use_attribute(), Action::set_attr(), and Action::set_io().
                                          :
   Action(0, (const char**)NULL, NULL, NULL, (char *)"MassTransfer"),
                    fagent(fag), bagent(bag)
 {
   int io[] = {IN, IN, OUT};
   set_io( 3, io);
   std::string atts[3];
   atts[0] = b_rhos;
   atts[1] = b_rb;
   atts[2] = f_mdot;
   set_attr(3, atts);
   bagent->register_use_attribute( bagent->iburn_all, ".rhos", bagent->parentWin, ".rhos");
 }
Member Function Documentation
void init (double t) virtual
Reimplemented from Action.
Definition at line 673 of file basic_actions.C.
References b_rb_hdl, b_rhos_hdl, COM_get_attribute_handle(), f_mdot_hdl, fagent, fb_mdot_hdl, FluidAgent::fluidBufB, and Action::get_attribute_handle().
{
   b_rhos_hdl = get_attribute_handle( 0);
   b_rb_hdl = get_attribute_handle( 1);
   f_mdot_hdl = get_attribute_handle( 2);
   fb_mdot_hdl = COM_get_attribute_handle( fagent->fluidBufB+".mdot");
 }
void run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 681 of file basic_actions.C.
References b_rb_hdl, b_rhos_hdl, COM_call_function(), RocBlas::copy_scalar, f_mdot_hdl, fb_mdot_hdl, MAN_DEBUG, and RocBlas::mul.
{
   MAN_DEBUG(3, ("Rocstar: MassTransfer::run() with t:%e dt:%e.\n", t, dt));
   double zero = 0.0;
   COM_call_function( RocBlas::copy_scalar, &zero, &f_mdot_hdl);
   COM_call_function( RocBlas::mul, &b_rhos_hdl, &b_rb_hdl, &fb_mdot_hdl);
   // Sets mass flux to 0.0 on burned out faces
   // BurnOutFilter(bflag,0.0,mass_flux);
   // or BurnOutFilter(bflag,mass_flux_insulation,mass_flux);
 //  debug_print(fagent->fluidBufB+".mdot", 102, 0);
 //  debug_print(bagent->iburn_ng+".rb", 102, 0);
 }
Member Data Documentation
int b_rb_hdl private
Definition at line 197 of file basic_actions.h.
Referenced by init(), and run().
int b_rhos_hdl private
Definition at line 197 of file basic_actions.h.
Referenced by init(), and run().
BurnAgent* bagent private
Definition at line 196 of file basic_actions.h.
Referenced by MassTransfer().
int f_mdot_hdl private
Definition at line 197 of file basic_actions.h.
Referenced by init(), and run().
FluidAgent* fagent private
Definition at line 195 of file basic_actions.h.
Referenced by init().
int fb_mdot_hdl private
Definition at line 197 of file basic_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C