Rocstar: Alg_Metric_Base_3 Class Reference
Alg_Metric_Base_3 Class Reference
3D Algebraic Metric Base Class
#include <Algebraic_Metrics_3.h>
Public Member Functions
Alg_Metric_Base_3 ()
Constructor.
virtual ~Alg_Metric_Base_3 ()
Virtual Destructor.
virtual void initialize (Vector_3< double > n[], int type)
Initialize a 3D Algebraic Metric.
virtual void initialize (Element_node_enumerator &ene)
virtual double maxValue () const
The maximum value for this metric.
virtual double minValue () const
The minimum value for this metric.
Public Member Functions inherited from Metric
Metric ()
virtual ~Metric ()
virtual void compute (double atts[]) const =0
Compute the value of this metric.
Protected Member Functions
double compute_size (double ref_voume=1.) const
Compute the size metric.
double compute_shape () const
Compute the shape metric.
double compute_skew () const
Compute the skew metric.
Protected Attributes
double alpha [8]
J_Matrix A [8]
Matrix L [8]
int type_
Friends
std::ostream & operator<< (std::ostream &, const Alg_Metric_Base_3 &)
Detailed Description
3D Algebraic Metric Base Class
This class is the base class for the implementation of the specific 3D algebraic metrics defined by Patrick Knupp in "Aglebraic Mesh Quality Metrics for Unstructured Initial Meshes"
Definition at line 42 of file Algebraic_Metrics_3.h.
Constructor & Destructor Documentation
Alg_Metric_Base_3 () inline
Constructor.
Definition at line 48 of file Algebraic_Metrics_3.h.
 {}
virtual ~Alg_Metric_Base_3 () inline virtual
Virtual Destructor.
Although the destructor does nothing, this member function must be declared since the class has other virtual functions.
Definition at line 55 of file Algebraic_Metrics_3.h.
 {}
Member Function Documentation
double compute_shape () const protected
Compute the shape metric.
Definition at line 141 of file Algebraic_Metrics_3.C.
References NTS::abs(), i, Mesquite::pow(), and sqrt().
{
   if (type_ == COM::Connectivity::TET4){
     double num = (3.0 * pow(alpha[0]*sqrt(2.0),(2.0/3.0)) );
     double denom = 1.5*(L[0](0,0)+L[0](1,1)+L[0](2,2))-
                        (L[0](0,1)+L[0](1,2)+L[0](0,2));
     return num/denom;
   }
   else{
     assert (type_ == COM::Connectivity::HEX8);
     double denom = 0;
     for (int i = 0; i < 8; i ++){
       denom += (L[i](0,0) + L[i](1,1) + L[i](2,2))/(pow(abs(alpha[i]),(2.0/3.0)));
     }
     return  24.0/denom;
   }
 }
double compute_size (double ref_voume = 1.) const protected
Compute the size metric.
Parameters
ref_area the ideal area for this element.
Definition at line 122 of file Algebraic_Metrics_3.C.
References i.
{
   double size = 0.0;
   if (type_ == COM::Connectivity::TET4){
     size = (alpha[0]/6.0)/ref_vol;
     size = (size < (1/size))? size : (1/size);
   }
   if (type_ == COM::Connectivity::HEX8){
     for (int i = 0; i < 8; i++){
       size += alpha[i];
     }
     if (size  < 0) {size = 0;}
     else {
       size = size / ( 8.0 * ref_vol );
       size = (size < (1/size))? size: (1/size);
     }
   }
   return size;
 }
double compute_skew () const protected
Compute the skew metric.
Definition at line 158 of file Algebraic_Metrics_3.C.
References NTS::abs(), i, Mesquite::pow(), and sqrt().
{
   // Not defined for Tets, so we return 1
   if (type_ == COM::Connectivity::TET4) {
     return 1.0;
   }
   // For quads, set flag in case of divide by zero (degenerate element)
   else{
     assert (type_ == COM::Connectivity::HEX8);
     double denom = 0.0;
     int flag = 0;
     for (int i = 0; i < 8; i ++){
       double root = sqrt(L[i](0,0)*L[i](1,1)*L[i](2,2));
       if (root == 0) { flag = 1;}
       denom += pow( abs(root/alpha[i]), (2.0/3.0));
     }
     if (flag) { return  0.0;}
     else { return 8.0/denom; }
   }
 }
void initialize (Vector_3< double > n[], int type) virtual
Initialize a 3D Algebraic Metric.
Parameters
n[] Ordered set of nodal coordinates.
type Element type: TET or QUAD
Implements Metric.
Definition at line 82 of file Algebraic_Metrics_3.C.
References A, i, j, and v.
Referenced by main().
{
   type_ = type;
   vector<Vector_3<double> > v(3);
   if (type_ == COM::Connectivity::TET4){
     double premult = 1.0;
     for ( int i = 0; i < 4; i ++){
       for (int j = 0; j < 3; j ++){
         v[0][j] = premult * (n[(i+1)%4][j] - n[i][j]);
         v[1][j] = premult * (n[(i+2)%4][j] - n[i][j]);
         v[2][j] = premult * (n[(i+3)%4][j] - n[i][j]);
       }
       A[i] = J_Matrix(&v[0],3);
       L[i] ^= A[i];
       alpha[i] = A[i].det();
       premult *= -1.0;
     }
   }
   else if (type_ == COM::Connectivity::HEX8){
     double premult = 1.0;
     for ( int i = 0; i < 8; i ++){
       if ( (i==0) || (i==3) || (i==5) || (i==6) )      { premult = 1.0;  }
       else if ( (i==1) || (i==2) || (i==4) || (i==7) ) { premult = -1.0; }
       int a,b,c;
       if ( (i == 0) || (i == 4) )   { a=1; b=3; c=4; }
       else if ( (i ==3) || (i==7) ) { a=4;b=5;c=7;   }
       else {a=1;b=4;c=7;}
       for (int j = 0; j < 3; j ++){
         v[0][j] = premult*( n[(i+a)%8][j] - n[i][j]);
         v[1][j] = premult*( n[(i+b)%8][j] - n[i][j]);
         v[2][j] = premult*( n[(i+c)%8][j] - n[i][j]);
       }
       A[i] = J_Matrix(&v[0],3);
       L[i] ^= A[i];
       alpha[i] = A[i].det();
     }
   }
 }
void initialize (Element_node_enumerator & ene) virtual
Implements Metric.
Definition at line 40 of file Algebraic_Metrics_3.C.
References A, i, j, and v.
{
   type_ = ene.type();
   Element_node_vectors_k_const<double> n;
   n.set(ene.pane()->attribute("nc"),ene);
   vector<Vector_3<double> > v(2);
   if (type_ == COM::Connectivity::TET4){
     double premult = 1.0;
     for ( int i = 0; i < 4; i ++){
       for (int j = 0; j < 3; j ++){
         v[0][j] = premult * (n((i+1)%4,j) - n(i,j));
         v[1][j] = premult * (n((i+2)%4,j) - n(i,j));
         v[2][j] = premult * (n((i+3)%4,j) - n(i,j));
       }
       A[i] = J_Matrix(&v[0],3);
       L[i] ^= A[i];
       alpha[i] = A[i].det();
       premult *= -1.0;
     }
   }
   else if (type_ == COM::Connectivity::HEX8){
     double premult = 1.0;
     for ( int i = 0; i < 8; i ++){
       if ( (i==0) || (i==3) || (i==5) || (i==6) )      { premult = 1.0;  }
       else if ( (i==1) || (i==2) || (i==4) || (i==7) ) { premult = -1.0; }
       int a,b,c;
       if ( (i == 0) || (i == 4) )   { a=1; b=3; c=4; }
       else if ( (i ==3) || (i==7) ) { a=4;b=5;c=7;   }
       else {a=1;b=4;c=7;}
       for (int j = 0; j < 3; j ++){
         v[0][j] = premult*( n((i+a)%8,j) - n(i,j));
         v[1][j] = premult*( n((i+b)%8,j) - n(i,j));
         v[2][j] = premult*( n((i+c)%8,j) - n(i,j));
       }
       A[i] = J_Matrix(&v[0],3);
       L[i] ^= A[i];
       alpha[i] = A[i].det();
     }
   }
 }
virtual double maxValue () const inline virtual
The maximum value for this metric.
Implements Metric.
Definition at line 67 of file Algebraic_Metrics_3.h.
Referenced by main().
 { return 1.0; }
virtual double minValue () const inline virtual
The minimum value for this metric.
Implements Metric.
Definition at line 70 of file Algebraic_Metrics_3.h.
Referenced by main().
 { return 0.0; }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & output, const Alg_Metric_Base_3 & m) friend
Definition at line 199 of file Algebraic_Metrics_3.C.
{
   for(int i =0; i < (m.type_-100); i ++){
     output << "A[" << i << "]:" << endl << m.A[i];
     output << "L[" << i << "]:" << endl << m.L[i];
     output << "alpha"<<i << ": " << m.alpha[i] << endl << endl;
   }
   return output;
 }
Member Data Documentation
J_Matrix A[8] protected
Definition at line 88 of file Algebraic_Metrics_3.h.
Referenced by operator<<().
double alpha[8] protected
Definition at line 87 of file Algebraic_Metrics_3.h.
Referenced by operator<<().
Matrix L[8] protected
Definition at line 89 of file Algebraic_Metrics_3.h.
Referenced by operator<<().
int type_ protected
Definition at line 90 of file Algebraic_Metrics_3.h.
Referenced by operator<<().
The documentation for this class was generated from the following files:
Algebraic_Metrics_3.h
Algebraic_Metrics_3.C