Rocstar: rflu_modfacelist Module Reference
rflu_modfacelist Module Reference
Public Member Functions
subroutine, public rflu_buildavface2borderlist (pRegion)
subroutine, public rflu_buildavface2patchlist (pRegion)
subroutine, public rflu_buildcell2facelist (pRegion)
subroutine, public rflu_buildfacelist (pRegion)
subroutine, public rflu_createavface2borderlist (pRegion)
subroutine, public rflu_createavface2patchlist (pRegion)
subroutine, public rflu_createcell2facelist (pRegion)
subroutine, public rflu_createfacelist (pRegion)
subroutine, public rflu_destroyavface2borderlist (pRegion)
subroutine, public rflu_destroyavface2patchlist (pRegion)
subroutine, public rflu_destroycell2facelist (pRegion)
subroutine, public rflu_destroyfacelist (pRegion)
subroutine, public rflu_getopposingfaces (pRegion, iPatch, ifg, nFacesOpp, faceOppInfo)
subroutine, public rflu_insertintocell2facelist (pRegion, iPatch, icg, ifg)
subroutine rflu_nullifyavface2borderlist (pRegion)
subroutine, public rflu_reorientfaces (pRegion)
Public Attributes
integer, parameter, public destroy_face_int = 1
integer, parameter, public destroy_face_ext = 2
integer, parameter, public destroy_face_all = 4
Private Member Functions
subroutine rflu_nullifyavface2patchlist (pRegion)
subroutine rflu_nullifycell2facelist (pRegion)
subroutine rflu_nullifyfacelist (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModFaceList.F90,v $ $Revision: 1.43 $'
Detailed Description
Definition at line 39 of file RFLU_ModFaceList.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildavface2borderlist (type(t_region), pointer pRegion)
Definition at line 110 of file RFLU_ModFaceList.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), max(), modsortsearch::quicksortintegerinteger(), moderror::registerfunction(), and StopWatch::stop().
Referenced by rflu_initflowsolver().
subroutine, public rflu_buildavface2patchlist (type(t_region), pointer pRegion)
Definition at line 330 of file RFLU_ModFaceList.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), moderror::registerfunction(), and StopWatch::stop().
Referenced by rflu_initflowsolver().
subroutine, public rflu_buildcell2facelist (type(t_region), pointer pRegion)
Definition at line 490 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modcellfaceedgeinfo::rflu_getglobalcellkind(), and rflu_insertintocell2facelist().
Referenced by plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflupart(), and rflupick().
subroutine, public rflu_buildfacelist (type(t_region), pointer pRegion)
Definition at line 754 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), key, modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modhashtable::rflu_createhashtable(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modcellfaceedgeinfo::rflu_getfacekind(), rflu_modcellfaceedgeinfo::rflu_getglobalcellkind(), rflu_modcellfaceedgeinfo::rflu_getglobalcelltype(), rflu_modhashtable::rflu_hashbuildkey(), rflu_modhashtable::rflu_hashface(), and rflu_modhashtable::rflu_unhashbface().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflucells(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_createavface2borderlist (type(t_region), pointer pRegion)
Definition at line 1569 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyavface2borderlist().
Referenced by rflu_initflowsolver().
subroutine, public rflu_createavface2patchlist (type(t_region), pointer pRegion)
Definition at line 1662 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyavface2patchlist().
Referenced by rflu_initflowsolver().
subroutine, public rflu_createcell2facelist (type(t_region), pointer pRegion)
Definition at line 1755 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifycell2facelist().
Referenced by plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflupart(), and rflupick().
subroutine, public rflu_createfacelist (type(t_region), pointer pRegion)
Definition at line 1878 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyfacelist().
Referenced by rflu_allocatememorywrapper(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflucells(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_destroyavface2borderlist (type(t_region), pointer pRegion)
Definition at line 2059 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyavface2borderlist().
Referenced by rflu_endflowsolver().
subroutine, public rflu_destroyavface2patchlist (type(t_region), pointer pRegion)
Definition at line 2147 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyavface2patchlist().
Referenced by rflu_endflowsolver().
subroutine, public rflu_destroycell2facelist (type(t_region), pointer pRegion)
Definition at line 2233 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifycell2facelist().
Referenced by plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflupart(), and rflupick().
subroutine, public rflu_destroyfacelist (type(t_region), pointer pRegion)
Definition at line 2350 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyfacelist().
Referenced by rflu_deallocatememorywrapper(), rflu_endflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon2(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_getopposingfaces (type(t_region), pointer pRegion, integer, intent(in) iPatch, integer, intent(in) ifg, integer, intent(out) nFacesOpp, integer, dimension(2,2), intent(out) faceOppInfo)
Definition at line 2499 of file RFLU_ModFaceList.F90.
References Line_2< R, T >::c(), moderror::deregisterfunction(), moderror::errorstop(), ic, modsortsearch::quicksortinteger(), moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_modstencilsfaces::rflu_buildf2cstencil().
subroutine, public rflu_insertintocell2facelist (type(t_region), pointer pRegion, integer, intent(in) iPatch, integer, intent(in) icg, integer, intent(in) ifg)
Definition at line 2725 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), modsortsearch::quicksortinteger(), moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_buildcell2facelist().
subroutine rflu_nullifyavface2borderlist (type(t_region), pointer pRegion)
Definition at line 3015 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createavface2borderlist(), and rflu_destroyavface2borderlist().
subroutine rflu_nullifyavface2patchlist (type(t_region), pointer pRegion) private
Definition at line 3082 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createavface2patchlist(), and rflu_destroyavface2patchlist().
subroutine rflu_nullifycell2facelist (type(t_region), pointer pRegion) private
Definition at line 3149 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createcell2facelist(), and rflu_destroycell2facelist().
subroutine rflu_nullifyfacelist (type(t_region), pointer pRegion) private
Definition at line 3222 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createfacelist(), and rflu_destroyfacelist().
subroutine, public rflu_reorientfaces (type(t_region), pointer pRegion)
Definition at line 3313 of file RFLU_ModFaceList.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Member Data Documentation
integer, parameter, public destroy_face_all = 4
Definition at line 76 of file RFLU_ModFaceList.F90.
integer, parameter, public destroy_face_ext = 2
Definition at line 76 of file RFLU_ModFaceList.F90.
integer, parameter, public destroy_face_int = 1
Definition at line 76 of file RFLU_ModFaceList.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModFaceList.F90,v $ $Revision: 1.43 $' private
Definition at line 80 of file RFLU_ModFaceList.F90.
The documentation for this module was generated from the following file:
RFLU_ModFaceList.F90