Rocstar: Ray_2< R, T > Class Template Reference
Ray_2< R, T > Class Template Reference
#include <cartesian_classes.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Ray_2_base RRay_2
Public Member Functions
Ray_2 ()
~Ray_2 ()
Ray_2 (const CGAL::Ray_2< R > &r)
Ray_2 (const RRay_2 &r)
Ray_2 (const CGAL::Point_2< R > &sp, const CGAL::Point_2< R > &secondp)
Ray_2 (const CGAL::Point_2< R > &sp, const CGAL::Direction_2< R > &d)
bool operator== (const CGAL::Ray_2< R > &r) const
bool operator!= (const CGAL::Ray_2< R > &r) const
CGAL::Point_2< R > start () const
CGAL::Point_2< R > source () const
CGAL::Point_2< R > second_point () const
CGAL::Point_2< R > point (int i) const
CGAL::Direction_2< R > direction () const
CGAL::Line_2< R > supporting_line () const
CGAL::Ray_2< R > opposite () const
CGAL::Ray_2< R > transform (const CGAL::Aff_transformation_2< R > &t) const
bool is_horizontal () const
bool is_vertical () const
bool is_degenerate () const
bool has_on (const CGAL::Point_2< R > &p) const
bool collinear_has_on (const CGAL::Point_2< R > &p) const
Detailed Description
template<class R, class T = typename R::Rep_tag>
class Ray_2< R, T >
Definition at line 68 of file cartesian_classes.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 86 of file Ray_2.h.
typedef R_ R
Definition at line 84 of file Ray_2.h.
typedef R::Ray_2_base RRay_2
Definition at line 87 of file Ray_2.h.
typedef R::RT RT
Definition at line 85 of file Ray_2.h.
Constructor & Destructor Documentation
Ray_2 () inline
Definition at line 89 of file Ray_2.h.
       : RRay_2()
   {}
~Ray_2 () inline
Definition at line 93 of file Ray_2.h.
   {}
Ray_2 (const CGAL::Ray_2< R > & r) inline
Definition at line 96 of file Ray_2.h.
     : RRay_2((const RRay_2&)r)
   {
   }
Ray_2 (const RRay_2< R, T > & r) inline
Definition at line 102 of file Ray_2.h.
     : RRay_2(r)
   {
   }
Ray_2 (const CGAL::Point_2< R > & sp, const CGAL::Point_2< R > & secondp) inline
Definition at line 108 of file Ray_2.h.
     : RRay_2(sp, secondp)
   {}
Ray_2 (const CGAL::Point_2< R > & sp, const CGAL::Direction_2< R > & d) inline
Definition at line 113 of file Ray_2.h.
     : RRay_2(sp, d)
   {}
Member Function Documentation
bool collinear_has_on (const CGAL::Point_2< R > & p) const inline
Definition at line 161 of file Ray_2.h.
   { return RRay_2::collinear_has_on(p); }
CGAL::Direction_2<R> direction () const inline
Definition at line 137 of file Ray_2.h.
   { return RRay_2::direction(); }
bool has_on (const CGAL::Point_2< R > & p) const inline
Definition at line 158 of file Ray_2.h.
   { return RRay_2::has_on(p); }
bool is_degenerate () const inline
Definition at line 155 of file Ray_2.h.
   { return RRay_2::is_degenerate(); }
bool is_horizontal () const inline
Definition at line 149 of file Ray_2.h.
   { return RRay_2::is_horizontal(); }
bool is_vertical () const inline
Definition at line 152 of file Ray_2.h.
   { return RRay_2::is_vertical(); }
bool operator!= (const CGAL::Ray_2< R > & r) const inline
Definition at line 122 of file Ray_2.h.
   { return !(*this == r); }
bool operator== (const CGAL::Ray_2< R > & r) const inline
Definition at line 119 of file Ray_2.h.
References operator==().
   { return RRay_2::operator==(r); }
CGAL::Ray_2<R> opposite () const inline
Definition at line 143 of file Ray_2.h.
References opposite().
   { return RRay_2::opposite(); }
CGAL::Point_2<R> point (int i) const inline
Definition at line 134 of file Ray_2.h.
   { return RRay_2::point(i); }
CGAL::Point_2<R> second_point () const inline
Definition at line 131 of file Ray_2.h.
   { return RRay_2::second_point(); }
CGAL::Point_2<R> source () const inline
Definition at line 128 of file Ray_2.h.
Referenced by peul_receivecorneredgecells(), peul_receivedummyvals(), plag_cecellsrecvdata(), plag_cecellsrecvsize(), plag_rflo_recvmetrics(), plag_rflo_modstats::plag_rflo_recvstatbuff(), radi_floflimrecvcornedgecells(), radi_floflimrecvdummyvals(), rflo_exchangednoderecv(), rflo_exchangegeometryprepare(), rflo_exchangegeometryrecv(), rflo_receivecorneredgecells(), rflo_receivedummyvals(), turb_floransrecvcornedgecells(), and turb_floransrecvdummyvals().
   { return RRay_2::source(); }
CGAL::Point_2<R> start () const inline
Definition at line 125 of file Ray_2.h.
   { return RRay_2::start(); }
CGAL::Line_2<R> supporting_line () const inline
Definition at line 140 of file Ray_2.h.
   { return RRay_2::supporting_line(); }
CGAL::Ray_2<R> transform (const CGAL::Aff_transformation_2< R > & t) const inline
Definition at line 146 of file Ray_2.h.
   { return RRay_2::transform(t); }
The documentation for this class was generated from the following files:
cartesian_classes.h
Ray_2.h