Rocstar: rflu_modviscousflux Module Reference
rflu_modviscousflux Module Reference
Public Member Functions
subroutine, public rflu_enforceheatflux (pRegion, tv, tvIndxCond)
subroutine, public rflu_viscousfluxes (pRegion, tv, tvIndxVisc, tvIndxCond)
subroutine, public rflu_viscousfluxespatches (pRegion, tv, tvIndxVisc, tvIndxCond)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModViscousFlux.F90,v $ $Revision: 1.10 $'
Detailed Description
Definition at line 39 of file RFLU_ModViscousFlux.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_enforceheatflux (type(t_region), pointer pRegion, real(rfreal), dimension(:,:) tv, integer, intent(in) tvIndxCond)
Definition at line 90 of file RFLU_ModViscousFlux.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modresidual::rflu_res_computeresidual(), and viscousfluxes().
subroutine, public rflu_viscousfluxes (type(t_region), pointer pRegion, real(rfreal), dimension(:,:) tv, integer, intent(in) tvIndxVisc, integer, intent(in) tvIndxCond)
Definition at line 233 of file RFLU_ModViscousFlux.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modinterpolation::rflu_interpcells2face(), and v.
Referenced by rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modresidual::rflu_res_computeresidual(), turb_coviscousfluxes(), and viscousfluxes().
subroutine, public rflu_viscousfluxespatches (type(t_region), pointer pRegion, real(rfreal), dimension(:,:) tv, integer, intent(in) tvIndxVisc, integer, intent(in) tvIndxCond)
Definition at line 431 of file RFLU_ModViscousFlux.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modinterpolation::rflu_interpcells2facepatch().
Referenced by rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modresidual::rflu_res_computeresidual(), turb_coviscousfluxes(), and viscousfluxes().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModViscousFlux.F90,v $ $Revision: 1.10 $' private
Definition at line 60 of file RFLU_ModViscousFlux.F90.
The documentation for this module was generated from the following file:
RFLU_ModViscousFlux.F90