Rocstar: SetValueDouble Class Reference
SetValueDouble Class Reference
#include <basic_actions.h>
Public Member Functions
SetValueDouble (const std::string at, const double val)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, char *name=NULL)
Action (int n, const char *at[], int *i=NULL, void *p=0, char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
int attr_hdl
double v
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_attribute_handle (int i)
int get_attribute_handle_const (int i)
int get_attribute_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Detailed Description
Definition at line 41 of file basic_actions.h.
Constructor & Destructor Documentation
SetValueDouble (const std::string at, const double val)
Definition at line 38 of file basic_actions.C.
References Action::OUT, and Action::set_io().
                                                                     :
   Action( 1, &at, NULL, NULL, (char *)"SetValueDouble"), v(val)
 {
   // Define I/O of the arguments.
   int io[] = {OUT};
   set_io( 1, io);
 }
Member Function Documentation
void init (double t) virtual
Reimplemented from Action.
Definition at line 47 of file basic_actions.C.
References attr_hdl, and Action::get_attribute_handle().
{
   attr_hdl = get_attribute_handle( 0);
 }
void run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 51 of file basic_actions.C.
References Action::attr, attr_hdl, COM_call_function(), RocBlas::copy_scalar, MAN_DEBUG, and v.
{
   MAN_DEBUG(3, ("Rocstar: SetValueDouble::run() %s with %e.\n", attr[0], v));
   COM_call_function( RocBlas::copy_scalar, &v, &attr_hdl);
 }
Member Data Documentation
int attr_hdl private
Definition at line 47 of file basic_actions.h.
Referenced by init(), and run().
double v private
Definition at line 48 of file basic_actions.h.
Referenced by run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C