Rocstar: plag_modreallocatememory Module Reference
plag_modreallocatememory Module Reference
Public Member Functions
subroutine, public plag_reallocmemwrapper (pRegion)
Public Attributes
real(rfreal), parameter plag_expand_ratio = 0.90_RFREAL
real(rfreal), parameter plag_shrink_ratio = 0.25_RFREAL
Private Member Functions
subroutine plag_copydimensions (global, pPlag, pPlagCopy)
subroutine plag_copymemory (global, pPlag, pPlagCopy)
subroutine plag_decidereallocmem (pRegion, pDecideReallocMem)
subroutine plag_reallocmem (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModReallocateMemory.F90,v $ $Revision: 1.9 $'
Detailed Description
Definition at line 39 of file PLAG_ModReallocateMemory.F90.
Member Function/Subroutine Documentation
subroutine plag_copydimensions (type(t_global), pointer global, type(t_plag), pointer pPlag, type(t_plag), pointer pPlagCopy) private
Definition at line 100 of file PLAG_ModReallocateMemory.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_reallocmem().
subroutine plag_copymemory (type(t_global), pointer global, type(t_plag), pointer pPlag, type(t_plag), pointer pPlagCopy) private
Definition at line 172 of file PLAG_ModReallocateMemory.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_reallocmem().
subroutine plag_decidereallocmem (type(t_region), pointer pRegion, logical, intent(inout) pDecideReallocMem) private
Definition at line 277 of file PLAG_ModReallocateMemory.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_reallocmemwrapper().
subroutine plag_reallocmem (type(t_region), pointer pRegion) private
Definition at line 363 of file PLAG_ModReallocateMemory.F90.
References moderror::deregisterfunction(), plag_copydimensions(), plag_copymemory(), plag_inrt_allocmemtstep(), plag_inrt_deallocmemtstep(), plag_rflu_allocmemsol(), plag_rflu_allocmemtstep(), plag_rflu_deallocmemsol(), plag_rflu_deallocmemtstep(), and moderror::registerfunction().
Referenced by plag_reallocmemwrapper().
subroutine, public plag_reallocmemwrapper (type(t_region), pointer pRegion)
Definition at line 485 of file PLAG_ModReallocateMemory.F90.
References moderror::deregisterfunction(), plag_decidereallocmem(), plag_reallocmem(), plag_moddimensions::plag_setmaxdimensions(), and moderror::registerfunction().
Referenced by plag_rflu_modcomm::plag_rflu_commdriver(), and plag_rflu_update().
Member Data Documentation
real(rfreal), parameter plag_expand_ratio = 0.90_RFREAL
Definition at line 60 of file PLAG_ModReallocateMemory.F90.
real(rfreal), parameter plag_shrink_ratio = 0.25_RFREAL
Definition at line 61 of file PLAG_ModReallocateMemory.F90.
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModReallocateMemory.F90,v $ $Revision: 1.9 $' private
Definition at line 70 of file PLAG_ModReallocateMemory.F90.
The documentation for this module was generated from the following file:
PLAG_ModReallocateMemory.F90