Rocstar: PointS3< FT > Class Template Reference
PointS3< FT > Class Template Reference
#include <PointS3.h>
Public Types
typedef PointS3< FT > Self
typedef VectorS3< FT > Vector
typedef Aff_transformationS3< FT > Aff_transformation
Public Member Functions
PointS3 ()
PointS3 (const Origin &o)
PointS3 (const FT &x, const FT &y, const FT &z)
PointS3 (const FT &x, const FT &y, const FT &z, const FT &hw)
bool operator== (const PointS3< FT > &p) const
bool operator!= (const PointS3< FT > &p) const
const FT & x () const
const FT & y () const
const FT & z () const
const FT & hx () const
const FT & hy () const
const FT & hz () const
FT hw () const
const FT & cartesian (int i) const
const FT & operator[] (int i) const
FT homogeneous (int i) const
int dimension () const
Bbox_3 bbox () const
PointS3< FT > transform (const Aff_transformationS3< FT > &) const
PointS3 (const VectorS3< FT > &v)
PointS3 ()
PointS3 (const Origin &)
PointS3 (const FT &hx, const FT &hy, const FT &hz, const FT &hw)
PointS3 (const FT &x, const FT &y, const FT &z)
~PointS3 ()
Self & operator= (const Self &p)
bool operator== (const Self &p) const
bool operator== (const Origin &) const
bool operator< (const Self &p) const
int id () const
FT hx () const
FT hy () const
FT hz () const
FT hw () const
FT homogeneous (int i) const
const FT & x () const
const FT & y () const
const FT & z () const
FT & x ()
FT & y ()
FT & z ()
const FT & cartesian (int i) const
FT & cartesian (int i)
FT & operator[] (int i)
const FT & operator[] (int i) const
int dimension () const
Self & operator+= (const Vector &v)
Self & operator-= (const Vector &v)
Bbox_3 bbox () const
Self transform (const Aff_transformation &t) const
Public Attributes
FT e0
FT e1
FT e2
Protected Attributes
FT _x
FT _y
FT _z
Friends
CGAL_FRIEND_INLINE PointS3< FT > operator+CGAL_NULL_TMPL_ARGS (const Origin &o, const VectorS3< FT > &v)
CGAL_FRIEND_INLINE PointS3< FT > operator-CGAL_NULL_TMPL_ARGS (const Origin &o, const VectorS3< FT > &v)
Detailed Description
template<class FT>
class PointS3< FT >
Definition at line 68 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
Member Typedef Documentation
typedef Aff_transformationS3<FT> Aff_transformation
Definition at line 35 of file include/CGAL/SimpleCartesian/PointS3.h.
typedef PointS3<FT> Self
Definition at line 33 of file include/CGAL/SimpleCartesian/PointS3.h.
typedef VectorS3<FT> Vector
Definition at line 34 of file include/CGAL/SimpleCartesian/PointS3.h.
Constructor & Destructor Documentation
PointS3 () inline
Definition at line 78 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 {}
PointS3 (const Origin & o) inline
Definition at line 79 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
                : e0(FT(0)), e1(FT(0)), e2(FT(0)) {}
PointS3 (const FT & x, const FT & y, const FT & z) inline
Definition at line 81 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
                : e0(x), e1(y), e2(z) {}
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE PointS3 (const FT & x, const FT & y, const FT & z, const FT & hw)
Definition at line 128 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References x, y, and z.
 {
   if (w != FT(1))
   {
     e0 = x/w;
     e1 = y/w;
     e2 = z/w;
   }
   else
   {
     e0 = x;
     e1 = y;
     e2 = z;
   }
 }
PointS3 (const VectorS3< FT > & v)
Definition at line 145 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References VectorS3< FT >::e0, VectorS3< FT >::e1, and VectorS3< FT >::e2.
 {
   e0 = v.e0;
   e1 = v.e1;
   e2 = v.e2;
 }
PointS3 () inline
Definition at line 37 of file include/CGAL/SimpleCartesian/PointS3.h.
 {}
PointS3 (const Origin &) inline
Definition at line 39 of file include/CGAL/SimpleCartesian/PointS3.h.
 : _x(0), _y(0), _z(0) {}
PointS3 (const FT & hx, const FT & hy, const FT & hz, const FT & hw) inline
Definition at line 40 of file include/CGAL/SimpleCartesian/PointS3.h.
     : _x(hx/hw), _y(hy/hw), _z(hz/hw) {}
PointS3 (const FT & x, const FT & y, const FT & z) inline
Definition at line 42 of file include/CGAL/SimpleCartesian/PointS3.h.
 : _x(x), _y(y), _z(z) {}
~PointS3 () inline
Definition at line 43 of file include/CGAL/SimpleCartesian/PointS3.h.
 {}
Member Function Documentation
Bbox_3 bbox () const inline
Definition at line 97 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 { return Bbox_3(x(),y(),z(),x(),y(),z()); }
Bbox_3 bbox () const
Definition at line 301 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References by, to_double(), x, y, and z.
 {
   // Not robust...
   double bx = CGAL::to_double(x());
   double by = CGAL::to_double(y());
   double bz = CGAL::to_double(z());
   return Bbox_3(bx, by, bz, bx, by, bz);
 }
const FT& cartesian (int i) const inline
Definition at line 72 of file include/CGAL/SimpleCartesian/PointS3.h.
References CGAL_kernel_precondition, PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
{
     CGAL_kernel_precondition( i >= 0 && i <= 2 );
     return (i==0) ? x() :
            (i==1) ? y() : z() ;
   }
FT& cartesian (int i) inline
Definition at line 78 of file include/CGAL/SimpleCartesian/PointS3.h.
References CGAL_kernel_precondition, PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
{
     CGAL_kernel_precondition( i >= 0 && i <= 2 );
     return (i==0) ? x() :
            (i==1) ? y() : z() ;
   }
const FT & cartesian (int i) const inline
Definition at line 196 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References CGAL_kernel_precondition, x, y, and z.
Referenced by PointS3< FT >::homogeneous(), and PointS3< FT >::operator[]().
 {
   CGAL_kernel_precondition( (i>=0) && (i<=2) );
   return (i==0) ? x() :
          (i==1) ? y() : z();
 }
int dimension () const inline
Definition at line 87 of file include/CGAL/SimpleCartesian/PointS3.h.
 { return 3; }
int dimension () const inline
Definition at line 189 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 { return 3; }
FT homogeneous (int i) const inline
Definition at line 63 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::cartesian().
 { return (i == 3) ? FT(1) : cartesian(i); }
FT homogeneous (int i) const
Definition at line 242 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References CGAL_kernel_precondition.
 {
   CGAL_kernel_precondition((i>=0) && (i<=3));
   return (i<3) ? cartesian(i) : FT(1);
 }
FT hw () const inline
Definition at line 62 of file include/CGAL/SimpleCartesian/PointS3.h.
 { return FT(1); }
FT hw () const inline
Definition at line 237 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 { return FT(1); }
FT hx () const inline
Definition at line 59 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::x().
 { return x(); }
const FT & hx () const inline
Definition at line 216 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 { return e0; }
FT hy () const inline
Definition at line 60 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::y().
 { return y(); }
const FT & hy () const inline
Definition at line 223 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 { return e1; }
FT hz () const inline
Definition at line 61 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::z().
 { return z(); }
const FT & hz () const inline
Definition at line 230 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 { return e2; }
int id () const inline
Definition at line 57 of file include/CGAL/SimpleCartesian/PointS3.h.
 { return (int)this; }
bool operator!= (const PointS3< FT > & p) const inline
Definition at line 161 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 { return !(*this == p); }
Self& operator+= (const Vector & v) inline
Definition at line 89 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::_x, PointS3< FT >::_y, PointS3< FT >::_z, VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
{
     _x += v.x(); _y+=v.y(); _z+=v.z();
     return *this;
   }
Self& operator-= (const Vector & v) inline
Definition at line 93 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::_x, PointS3< FT >::_y, PointS3< FT >::_z, VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
{
     _x -= v.x(); _y-=v.y(); _z-=v.z();
     return *this;
   }
bool operator< (const Self & p) const inline
Definition at line 54 of file include/CGAL/SimpleCartesian/PointS3.h.
References lexicographically_xyz_smaller().
     { return lexicographically_xyz_smaller(*this, p); }
Self& operator= (const Self & p) inline
Definition at line 45 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::_x, PointS3< FT >::_y, and PointS3< FT >::_z.
{
     _x=p._x; _y=p._y; _z=p._z;
     return *this;
   }
bool operator== (const Self & p) const inline
Definition at line 50 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
     { return x()==p.x() && y()==p.y() && z()==p.z(); }
bool operator== (const Origin &) const inline
Definition at line 52 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
     { return x()==FT(0) && y()==FT(0) && z()==FT(0); }
bool operator== (const PointS3< FT > & p) const inline
Definition at line 155 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References x, PointS3< FT >::x(), y, PointS3< FT >::y(), z, and PointS3< FT >::z().
 { return (x() == p.x()) && (y() == p.y()) && (z() == p.z()); }
FT& operator[] (int i) inline
Definition at line 84 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::cartesian().
 { return cartesian(i); }
const FT& operator[] (int i) const inline
Definition at line 85 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::cartesian().
 { return cartesian(i); }
const FT & operator[] (int i) const inline
Definition at line 207 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
 {
   return cartesian(i);
 }
Self transform (const Aff_transformation & t) const inline
Definition at line 99 of file include/CGAL/SimpleCartesian/PointS3.h.
References Aff_transformationS3< FT >::transform().
   { return t.transform(*this); }
PointS3< FT > transform (const Aff_transformationS3< FT > & t) const inline
Definition at line 296 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
References Aff_transformationS3< FT >::transform().
 { return t.transform(*this); }
const FT& x () const inline
Definition at line 65 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::_x.
 { return _x; }
FT& x () inline
Definition at line 68 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::_x.
 { return _x; }
const FT & x () const inline
Definition at line 168 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
Referenced by PointS3< FT >::bbox(), PointS3< FT >::cartesian(), circumcenter(), cmp_dist_to_point(), cmp_signed_dist_to_plane(), collinear(), collinear_are_ordered_along_line(), collinear_are_strictly_ordered_along_line(), compare_lexicographically_xy(), compare_lexicographically_xyz(), compare_x(), coplanar_orientation(), equal_xy(), equal_xyz(), has_larger_dist_to_point(), has_larger_signed_dist_to_plane(), PlaneS3< FT >::has_on_boundary(), PlaneS3< FT >::has_on_negative_side(), PlaneS3< FT >::has_on_positive_side(), has_smaller_dist_to_point(), has_smaller_signed_dist_to_plane(), PointS3< FT >::hx(), less_x(), midpoint(), PlaneS3< FT >::new_rep(), operator+(), operator-(), PointS3< FT >::operator==(), orientation(), PlaneS3< FT >::oriented_side(), PlaneS3< FT >::PlaneS3(), projection(), scaled_distance_to_plane(), side_of_bounded_sphere(), side_of_oriented_sphere(), squared_distance(), Aff_transformation_repS3< FT >::transform(), Scaling_repS3< FT >::transform(), and x_equal().
 { return e0; }
const FT& y () const inline
Definition at line 66 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::_y.
 { return _y; }
FT& y () inline
Definition at line 69 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::_y.
 { return _y; }
const FT & y () const inline
Definition at line 175 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
Referenced by PointS3< FT >::bbox(), PointS3< FT >::cartesian(), circumcenter(), cmp_dist_to_point(), cmp_signed_dist_to_plane(), collinear(), collinear_are_ordered_along_line(), collinear_are_strictly_ordered_along_line(), compare_lexicographically_xy(), compare_lexicographically_xyz(), compare_y(), coplanar_orientation(), equal_xy(), equal_xyz(), has_larger_dist_to_point(), has_larger_signed_dist_to_plane(), PlaneS3< FT >::has_on_boundary(), PlaneS3< FT >::has_on_negative_side(), PlaneS3< FT >::has_on_positive_side(), has_smaller_dist_to_point(), has_smaller_signed_dist_to_plane(), PointS3< FT >::hy(), less_y(), midpoint(), PlaneS3< FT >::new_rep(), operator+(), operator-(), PointS3< FT >::operator==(), orientation(), PlaneS3< FT >::oriented_side(), PlaneS3< FT >::PlaneS3(), projection(), scaled_distance_to_plane(), side_of_bounded_sphere(), side_of_oriented_sphere(), squared_distance(), Aff_transformation_repS3< FT >::transform(), Scaling_repS3< FT >::transform(), and y_equal().
 { return  e1; }
const FT& z () const inline
Definition at line 67 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::_z.
 { return _z; }
FT& z () inline
Definition at line 70 of file include/CGAL/SimpleCartesian/PointS3.h.
References PointS3< FT >::_z.
 { return _z; }
const FT & z () const inline
Definition at line 182 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
Referenced by PointS3< FT >::bbox(), PointS3< FT >::cartesian(), circumcenter(), cmp_dist_to_point(), cmp_signed_dist_to_plane(), collinear(), collinear_are_ordered_along_line(), collinear_are_strictly_ordered_along_line(), compare_lexicographically_xyz(), compare_z(), coplanar_orientation(), equal_xyz(), has_larger_dist_to_point(), has_larger_signed_dist_to_plane(), PlaneS3< FT >::has_on_boundary(), PlaneS3< FT >::has_on_negative_side(), PlaneS3< FT >::has_on_positive_side(), has_smaller_dist_to_point(), has_smaller_signed_dist_to_plane(), PointS3< FT >::hz(), less_z(), midpoint(), PlaneS3< FT >::new_rep(), operator+(), operator-(), PointS3< FT >::operator==(), orientation(), PlaneS3< FT >::oriented_side(), PlaneS3< FT >::PlaneS3(), projection(), scaled_distance_to_plane(), side_of_bounded_sphere(), side_of_oriented_sphere(), squared_distance(), Aff_transformation_repS3< FT >::transform(), Scaling_repS3< FT >::transform(), and z_equal().
 { return  e2; }
Friends And Related Function Documentation
CGAL_FRIEND_INLINE PointS3<FT> operator+CGAL_NULL_TMPL_ARGS (const Origin & o, const VectorS3< FT > & v) friend
CGAL_FRIEND_INLINE PointS3<FT> operator-CGAL_NULL_TMPL_ARGS (const Origin & o, const VectorS3< FT > & v) friend
Member Data Documentation
FT _x protected
Definition at line 103 of file include/CGAL/SimpleCartesian/PointS3.h.
Referenced by PointS3< FT >::operator+=(), PointS3< FT >::operator-=(), PointS3< FT >::operator=(), and PointS3< FT >::x().
FT _y protected
Definition at line 103 of file include/CGAL/SimpleCartesian/PointS3.h.
Referenced by PointS3< FT >::operator+=(), PointS3< FT >::operator-=(), PointS3< FT >::operator=(), and PointS3< FT >::y().
FT _z protected
Definition at line 103 of file include/CGAL/SimpleCartesian/PointS3.h.
Referenced by PointS3< FT >::operator+=(), PointS3< FT >::operator-=(), PointS3< FT >::operator=(), and PointS3< FT >::z().
FT e0
Definition at line 111 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
Referenced by VectorS3< FT >::VectorS3().
FT e1
Definition at line 112 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
Referenced by VectorS3< FT >::VectorS3().
FT e2
Definition at line 113 of file CGAL/include/CGAL/SimpleCartesian/PointS3.h.
Referenced by VectorS3< FT >::VectorS3().
The documentation for this class was generated from the following file:
CGAL/include/CGAL/SimpleCartesian/PointS3.h