Rocstar: rflu_modstencilscells Module Reference
rflu_modstencilscells Module Reference
Public Member Functions
subroutine rflu_buildc2cstencilbasic (pRegion, icg, stencilSizeMax, degr, c2cs)
subroutine, public rflu_buildc2cstencilwrapper (pRegion, icgInput, constrInput)
subroutine, public rflu_buildlistcc2cstencil (pRegion)
subroutine, public rflu_createc2cstencilwrapper (pRegion)
subroutine, public rflu_destroyc2cstencilwrapper (pRegion)
subroutine, public rflu_destroylistcc2cstencil (pRegion)
subroutine, public rflu_setinfoc2cstencilwrapper (pRegion, orderNominal)
Private Member Functions
subroutine rflu_buildc2cstencil_1d (pRegion, fnDir, icgBeg, icgEnd)
subroutine rflu_buildc2cstencil_1d_g (pRegion, dir, icgBeg, icgEnd)
subroutine rflu_buildc2cstencil (pRegion, icgBeg, icgEnd, addBFaces)
subroutine rflu_buildc2cstencilbasic_1d (pRegion, icg, stencilSizeMax, dir, degr, c2cs1D)
subroutine rflu_createc2cstencil_1d (pRegion)
subroutine rflu_createc2cstencil (pRegion)
subroutine rflu_destroyc2cstencil_1d (pRegion)
subroutine rflu_destroyc2cstencil (pRegion)
subroutine rflu_nullifyc2cstencil_1d (pRegion)
subroutine rflu_nullifyc2cstencil (pRegion)
subroutine rflu_setinfoc2cstencil_1d (pRegion, orderNominal)
subroutine rflu_setinfoc2cstencil (pRegion, orderNominal)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsCells.F90,v $ $Revision: 1.18 $'
Detailed Description
Definition at line 39 of file RFLU_ModStencilsCells.F90.
Member Function/Subroutine Documentation
subroutine rflu_buildc2cstencil (type(t_region), pointer pRegion, integer, intent(in) icgBeg, integer, intent(in) icgEnd, logical, intent(in) addBFaces) private
Definition at line 722 of file RFLU_ModStencilsCells.F90.
References Line_2< R, T >::a(), ainv(), moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), max(), min(), Generic_element_2::order(), moderror::registerfunction(), rflu_modstencilsutils::rflu_addbfaces(), rflu_modstencilsutils::rflu_addcelllayer(), rflu_buildc2cstencilbasic(), rflu_modcellfaceedgeinfo::rflu_getglobalcelltype(), rflu_invertmatrixsvd(), rflu_modstencilsutils::rflu_sortbfaces(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_buildc2cstencilwrapper().
subroutine rflu_buildc2cstencil_1d (type(t_region), pointer pRegion, integer, intent(in) fnDir, integer, intent(in) icgBeg, integer, intent(in) icgEnd) private
Definition at line 103 of file RFLU_ModStencilsCells.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), modsortsearch::quicksortinteger(), moderror::registerfunction(), and rflu_modstencilsutils::rflu_addcelllayer_1d().
subroutine rflu_buildc2cstencil_1d_g (type(t_region), pointer pRegion, integer, intent(in) dir, integer, intent(in) icgBeg, integer, intent(in) icgEnd) private
Definition at line 419 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), vector3d::dir(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), rflu_modstencilsutils::rflu_addcelllayer_1d_g(), rflu_buildc2cstencilbasic_1d(), and rflu_modcellfaceedgeinfo::rflu_getglobalcelltype().
Referenced by rflu_buildc2cstencilwrapper().
subroutine rflu_buildc2cstencilbasic (type(t_region), pointer pRegion, integer, intent(in) icg, integer, intent(in) stencilSizeMax, integer, intent(out) degr, integer, dimension(stencilsizemax), intent(out) c2cs)
Definition at line 1180 of file RFLU_ModStencilsCells.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::findcommonsortedintegers(), invert(), max(), Mesh::GenericCell_2::nvert(), modsortsearch::quicksortinteger(), modsortsearch::quicksortrfrealinteger(), moderror::registerfunction(), modsortsearch::removeinteger(), rflu_modcellfaceedgeinfo::rflu_getglobalcelltype(), modsortsearch::simplifysortedintegers(), and StopWatch::stop().
Referenced by rflu_buildc2cstencil().
subroutine rflu_buildc2cstencilbasic_1d (type(t_region), pointer pRegion, integer, intent(in) icg, integer, intent(in) stencilSizeMax, integer, intent(in) dir, integer, intent(out) degr, integer, dimension(stencilsizemax), intent(out) c2cs1D) private
Definition at line 1417 of file RFLU_ModStencilsCells.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), vector3d::dir(), moderror::errorstop(), max(), modsortsearch::quicksortinteger(), moderror::registerfunction(), modsortsearch::removeinteger(), rflu_modcellfaceedgeinfo::rflu_getglobalcelltype(), rflu_modgeometrytools::rflu_testvectorcartaxisaligned(), modsortsearch::simplifysortedintegers(), and StopWatch::stop().
Referenced by rflu_buildc2cstencil_1d_g().
subroutine, public rflu_buildc2cstencilwrapper (type(t_region), pointer pRegion, integer, intent(in), optional icgInput, integer, intent(in), optional constrInput)
Definition at line 1596 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_buildc2cstencil(), and rflu_buildc2cstencil_1d_g().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_postprocessregionscommon1(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2(), rflupart(), and rflupick().
subroutine, public rflu_buildlistcc2cstencil (type(t_region), pointer pRegion)
Definition at line 1703 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
subroutine rflu_createc2cstencil (type(t_region), pointer pRegion) private
Definition at line 1939 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyc2cstencil().
Referenced by rflu_createc2cstencilwrapper().
subroutine rflu_createc2cstencil_1d (type(t_region), pointer pRegion) private
Definition at line 1828 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyc2cstencil_1d().
Referenced by rflu_createc2cstencilwrapper().
subroutine, public rflu_createc2cstencilwrapper (type(t_region), pointer pRegion)
Definition at line 2036 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_createc2cstencil(), and rflu_createc2cstencil_1d().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_postprocessregionscommon1(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2(), rflupart(), and rflupick().
subroutine rflu_destroyc2cstencil (type(t_region), pointer pRegion) private
Definition at line 2240 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyc2cstencil().
Referenced by rflu_destroyc2cstencilwrapper().
subroutine rflu_destroyc2cstencil_1d (type(t_region), pointer pRegion) private
Definition at line 2108 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyc2cstencil_1d().
Referenced by rflu_destroyc2cstencilwrapper().
subroutine, public rflu_destroyc2cstencilwrapper (type(t_region), pointer pRegion)
Definition at line 2356 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_destroyc2cstencil(), and rflu_destroyc2cstencil_1d().
Referenced by rflu_endflowsolver(), rflu_mergepostprocessregions(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_postprocessregionscommon1(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2(), rflupart(), and rflupick().
subroutine, public rflu_destroylistcc2cstencil (type(t_region), pointer pRegion)
Definition at line 2427 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_endflowsolver().
subroutine rflu_nullifyc2cstencil (type(t_region), pointer pRegion) private
Definition at line 2604 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createc2cstencil(), and rflu_destroyc2cstencil().
subroutine rflu_nullifyc2cstencil_1d (type(t_region), pointer pRegion) private
Definition at line 2520 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createc2cstencil_1d(), and rflu_destroyc2cstencil_1d().
subroutine rflu_setinfoc2cstencil (type(t_region), pointer pRegion, integer, intent(in) orderNominal) private
Definition at line 2803 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_computestencilsize().
Referenced by rflu_setinfoc2cstencilwrapper().
subroutine rflu_setinfoc2cstencil_1d (type(t_region), pointer pRegion, integer, intent(in) orderNominal) private
Definition at line 2691 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_setinfoc2cstencilwrapper().
subroutine, public rflu_setinfoc2cstencilwrapper (type(t_region), pointer pRegion, integer, intent(in) orderNominal)
Definition at line 2921 of file RFLU_ModStencilsCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_setinfoc2cstencil(), and rflu_setinfoc2cstencil_1d().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_postprocessregionscommon1(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2(), rflupart(), and rflupick().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsCells.F90,v $ $Revision: 1.18 $' private
Definition at line 70 of file RFLU_ModStencilsCells.F90.
The documentation for this module was generated from the following file:
RFLU_ModStencilsCells.F90