Rocstar: rflu_moddimensionality Module Reference
rflu_moddimensionality Module Reference
Public Member Functions
subroutine, public rflu_123d_checkgeometrywrapper (pRegion)
subroutine, public rflu_123d_checktopology (pRegion)
Private Member Functions
subroutine rflu_123d_checkgeometrykernel (pRegion, dir)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModDimensionality.F90,v $ $Revision: 1.9 $'
Detailed Description
Definition at line 39 of file RFLU_ModDimensionality.F90.
Member Function/Subroutine Documentation
subroutine rflu_123d_checkgeometrykernel (type(t_region), pointer pRegion, integer, intent(in) dir) private
Definition at line 173 of file RFLU_ModDimensionality.F90.
References moderror::deregisterfunction(), vector3d::dir(), moderror::errorstop(), modtools::floatequal(), and moderror::registerfunction().
Referenced by rflu_123d_checkgeometrywrapper().
subroutine, public rflu_123d_checkgeometrywrapper (type(t_region), pointer pRegion)
Definition at line 89 of file RFLU_ModDimensionality.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_123d_checkgeometrykernel().
Referenced by rflu_initflowsolver().
subroutine, public rflu_123d_checktopology (type(t_region), pointer pRegion)
Definition at line 322 of file RFLU_ModDimensionality.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModDimensionality.F90,v $ $Revision: 1.9 $' private
Definition at line 60 of file RFLU_ModDimensionality.F90.
The documentation for this module was generated from the following file:
RFLU_ModDimensionality.F90