Rocstar: Rotation_repS2< FT > Class Template Reference
Rotation_repS2< FT > Class Template Reference
#include <Aff_transformationS2.h>
Public Member Functions
Rotation_repS2 ()
Rotation_repS2 (const FT &sinus, const FT &cosinus)
Rotation_repS2 (const DirectionS2< FT > &d, const FT &eps_num, const FT &eps_den=FT(1))
~Rotation_repS2 ()
PointS2< FT > transform (const PointS2< FT > &p) const
VectorS2< FT > transform (const VectorS2< FT > &v) const
DirectionS2< FT > transform (const DirectionS2< FT > &d) const
Aff_transformationS2< FT > inverse () const
Aff_transformationS2< FT > operator* (const Aff_transformation_rep_baseS2< FT > &t)
Aff_transformationS2< FT > compose (const Translation_repS2< FT > &t) const
virtual Aff_transformationS2< FT > compose (const Rotation_repS2< FT > &t) const
virtual Aff_transformationS2< FT > compose (const Scaling_repS2< FT > &t) const
virtual Aff_transformationS2< FT > compose (const Aff_transformation_repS2< FT > &t) const
virtual bool is_even () const
virtual FT cartesian (int i, int j) const
virtual std::ostream & print (std::ostream &os) const
Public Member Functions inherited from Aff_transformation_rep_baseS2< FT >
virtual ~Aff_transformation_rep_baseS2 ()
Private Attributes
FT _sinus
FT _cosinus
Friends
class Aff_transformation_repS2< FT >
class Translation_repS2< FT >
class Scaling_repS2< FT >
Additional Inherited Members
Protected Member Functions inherited from Leda_like_rep
Leda_like_rep ()
virtual ~Leda_like_rep ()
Protected Attributes inherited from Leda_like_rep
int count
Detailed Description
template<class FT>
class Rotation_repS2< FT >
Definition at line 74 of file Aff_transformationS2.h.
Constructor & Destructor Documentation
Rotation_repS2 () inline
Definition at line 419 of file Aff_transformationS2.h.
   {}
Rotation_repS2 (const FT & sinus, const FT & cosinus) inline
Definition at line 422 of file Aff_transformationS2.h.
     : _sinus(sinus), _cosinus(cosinus)
   {}
Rotation_repS2 (const DirectionS2< FT > & d, const FT & eps_num, const FT & eps_den = FT(1)) inline
Definition at line 426 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Rotation_repS2< FT >::_sinus, rational_rotation_approximation(), and DirectionS2< FT >::vector().
   {
     FT sin_num;
     FT cos_num;
     FT denom;
     rational_rotation_approximation(d.vector().x(),
                                     d.vector().y(),
                                     sin_num,
                                     cos_num,
                                     denom,
                                     eps_num,
                                     eps_den);
     _sinus   = sin_num/denom;
     _cosinus = cos_num/denom;
   }
~Rotation_repS2 () inline
Definition at line 445 of file Aff_transformationS2.h.
   {}
Member Function Documentation
virtual FT cartesian (int i, int j) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 537 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, and Rotation_repS2< FT >::_sinus.
   {
     switch (i)
     {
     case 0: switch (j)
             {
               case 0: return _cosinus;
               case 1: return -_sinus;
               case 2: return FT(0);
             }
     case 1: switch (j)
             {
               case 0: return _sinus;
               case 1: return _cosinus;
               case 2: return FT(0);
             }
     case 2: switch (j)
             {
               case 0: return FT(0);
               case 1: return FT(0);
               case 2: return FT(1);
             }
     }
     return FT(0);
   }
Aff_transformationS2<FT> compose (const Translation_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 488 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Rotation_repS2< FT >::_sinus, and Translation_repS2< FT >::_translationvector.
   {
     return Aff_transformationS2<FT>(_cosinus,
                                     -_sinus,
                                     t._translationvector.x(),
                                     _sinus,
                                     _cosinus,
                                     t._translationvector.y());
   }
virtual Aff_transformationS2<FT> compose (const Rotation_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 501 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Rotation_repS2< FT >::_sinus, and ROTATION.
   {
     return Aff_transformationS2<FT>(ROTATION,
                                     t._sinus*_cosinus + t._cosinus*_sinus,
                                     t._cosinus*_cosinus-t._sinus*_sinus );
   }
virtual Aff_transformationS2<FT> compose (const Scaling_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 509 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Scaling_repS2< FT >::_scalefactor, and Rotation_repS2< FT >::_sinus.
   {
     return Aff_transformationS2<FT>(t._scalefactor*_cosinus,
                                     t._scalefactor*-_sinus,
                                     t._scalefactor*_sinus,
                                     t._scalefactor*_cosinus);
   }
virtual Aff_transformationS2<FT> compose (const Aff_transformation_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 519 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Rotation_repS2< FT >::_sinus, Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, and Aff_transformation_repS2< FT >::t23.
   {
     return Aff_transformationS2<FT>(_cosinus*t.t11  + _sinus*t.t12,
                                     -_sinus*t.t11  + _cosinus*t.t12,
                                     t.t13,
                                     _cosinus*t.t21 + _sinus*t.t22,
                                     -_sinus*t.t21 + _cosinus*t.t22,
                                     t.t23);
   }
Aff_transformationS2<FT> inverse () const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 467 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Rotation_repS2< FT >::_sinus, and ROTATION.
   {
     return Aff_transformationS2<FT>(ROTATION,
                                     - _sinus, _cosinus, FT(1));
   }
virtual bool is_even () const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 532 of file Aff_transformationS2.h.
   {
     return true;
   }
Aff_transformationS2<FT> operator* (const Aff_transformation_rep_baseS2< FT > & t) inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 482 of file Aff_transformationS2.h.
References Aff_transformation_rep_baseS2< FT >::compose().
   {
     return t.compose(*this);
   }
virtual std::ostream& print (std::ostream & os) const inline virtual
Definition at line 563 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, and Rotation_repS2< FT >::_sinus.
   {
     os << "Aff_transformationS2(" << _sinus << ", " << _cosinus <<  ")";
     return os;
   }
PointS2<FT> transform (const PointS2< FT > & p) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 448 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Rotation_repS2< FT >::_sinus, PointS2< FT >::x(), and PointS2< FT >::y().
   {
     return PointS2<FT>(_cosinus * p.x() - _sinus * p.y(),
                        _sinus * p.x() + _cosinus * p.y());
   }
VectorS2<FT> transform (const VectorS2< FT > & v) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 454 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Rotation_repS2< FT >::_sinus, VectorS2< FT >::x(), and VectorS2< FT >::y().
   {
     return VectorS2<FT>(_cosinus * v.x() - _sinus * v.y(),
                         _sinus * v.x() + _cosinus * v.y());
   }
DirectionS2<FT> transform (const DirectionS2< FT > & d) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 460 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Rotation_repS2< FT >::_sinus, v, DirectionS2< FT >::vector(), VectorS2< FT >::x(), and VectorS2< FT >::y().
   {
     VectorS2<FT>  v = d.vector();
     return DirectionS2<FT>(_cosinus * v.x() - _sinus * v.y(),
                            _sinus * v.x() + _cosinus * v.y());
   }
Friends And Related Function Documentation
friend class Aff_transformation_repS2< FT > friend
Definition at line 415 of file Aff_transformationS2.h.
friend class Scaling_repS2< FT > friend
Definition at line 417 of file Aff_transformationS2.h.
friend class Translation_repS2< FT > friend
Definition at line 416 of file Aff_transformationS2.h.
Member Data Documentation
FT _cosinus private
Definition at line 571 of file Aff_transformationS2.h.
Referenced by Rotation_repS2< FT >::cartesian(), Aff_transformation_repS2< FT >::compose(), Translation_repS2< FT >::compose(), Rotation_repS2< FT >::compose(), Scaling_repS2< FT >::compose(), Rotation_repS2< FT >::inverse(), Rotation_repS2< FT >::print(), Rotation_repS2< FT >::Rotation_repS2(), and Rotation_repS2< FT >::transform().
FT _sinus private
Definition at line 570 of file Aff_transformationS2.h.
Referenced by Rotation_repS2< FT >::cartesian(), Aff_transformation_repS2< FT >::compose(), Translation_repS2< FT >::compose(), Rotation_repS2< FT >::compose(), Scaling_repS2< FT >::compose(), Rotation_repS2< FT >::inverse(), Rotation_repS2< FT >::print(), Rotation_repS2< FT >::Rotation_repS2(), and Rotation_repS2< FT >::transform().
The documentation for this class was generated from the following file:
Aff_transformationS2.h