Rocstar: EntityIterator Class Reference
EntityIterator Class Reference abstract
Iterates through a set of entities. An EntityIterator is typically obtained via Mesh::vertex_iterator() or Mesh::element_iterator(). An iterator obtained in this way iterates over the set of all vertices/elements in the Mesh from which the iterator was obtained.
#include <MeshInterface.hpp>
Public Member Functions
virtual ~EntityIterator ()
virtual void restart ()=0
Moves the iterator back to the first entity in the list.
virtual Mesh::EntityHandle operator* () const =0
*iterator.
virtual void operator++ ()=0
++iterator
virtual bool is_at_end () const =0
Returns false until the iterator has been advanced PAST the last entity.
Detailed Description
Iterates through a set of entities. An EntityIterator is typically obtained via Mesh::vertex_iterator() or Mesh::element_iterator(). An iterator obtained in this way iterates over the set of all vertices/elements in the Mesh from which the iterator was obtained.
Definition at line 416 of file MeshInterface.hpp.
Constructor & Destructor Documentation
virtual ~EntityIterator () inline virtual
Definition at line 419 of file MeshInterface.hpp.
       {}
Member Function Documentation
virtual bool is_at_end () const pure virtual
Returns false until the iterator has been advanced PAST the last entity.
Once is_at_end() returns true, *iterator returns 0.
Implemented in MyEntityIterator, MyEntityIterator, MyEntityIterator, MeshImplElemIter, MeshImplElemIter, MeshImplVertIter, MeshImplVertIter, TSTTArrIter, SIDLIterator, and TSTTIterator.
Referenced by MeshSet::clear_all_soft_fixed_flags(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::update_mesh(), and MeshImpl::write_vtk().
virtual Mesh::EntityHandle operator* () const pure virtual
*iterator.
Return the handle currently being pointed at by the iterator.
Implemented in MyEntityIterator, MyEntityIterator, MyEntityIterator, MeshImplElemIter, MeshImplElemIter, MeshImplVertIter, MeshImplVertIter, TSTTArrIter, SIDLIterator, and TSTTIterator.
virtual void operator++ () pure virtual
++iterator
Implemented in MyEntityIterator, MyEntityIterator, MyEntityIterator, MeshImplElemIter, MeshImplElemIter, MeshImplVertIter, MeshImplVertIter, TSTTArrIter, SIDLIterator, and TSTTIterator.
virtual void restart () pure virtual
Moves the iterator back to the first entity in the list.
Implemented in MyEntityIterator, MyEntityIterator, MyEntityIterator, MeshImplElemIter, MeshImplElemIter, MeshImplVertIter, MeshImplVertIter, TSTTArrIter, SIDLIterator, and TSTTIterator.
Referenced by MeshSet::reset(), and MeshImpl::write_vtk().
The documentation for this class was generated from the following file:
MeshInterface.hpp