Rocstar: IO Class Reference
IO Class Reference
#include <io.h>
Public Types
enum Mode { ASCII = 0, PRETTY, BINARY }
Static Public Attributes
static int mode = std::ios::xalloc()
Detailed Description
Definition at line 61 of file io.h.
Member Enumeration Documentation
enum Mode
Enumerator
ASCII
PRETTY
BINARY
Definition at line 64 of file io.h.
 {ASCII = 0, PRETTY, BINARY};
Member Data Documentation
CGAL_BEGIN_NAMESPACE int mode = std::ios::xalloc() static
Definition at line 63 of file io.h.
Referenced by get_mode(), is_ascii(), is_binary(), is_pretty(), operator<<(), operator>>(), Two_tuple< T >::print(), Three_tuple< int >::print(), Four_tuple< T >::print(), set_ascii_mode(), set_binary_mode(), set_mode(), and set_pretty_mode().
The documentation for this class was generated from the following files:
io.h
io.C