Rocstar: rflo_moddegeneratecornedge Module Reference
rflo_moddegeneratecornedge Module Reference
Public Member Functions
subroutine, public rflo_finddegeneratcell (regions, handleCorn, icount, iReg, iLev, iRegTest, icellTest, iTest, jTest, kTest)
subroutine, public rflo_markdegeneratvert (regions)
subroutine, public rflo_writedegeneratec (regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModDegenerateCornEdge.F90,v $ $Revision: 1.3 $'
Detailed Description
Definition at line 39 of file RFLO_ModDegenerateCornEdge.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_finddegeneratcell (type(t_region), dimension(:), pointer regions, integer handleCorn, integer icount, integer iReg, integer iLev, integer iRegTest, integer icellTest, integer iTest, integer jTest, integer kTest)
Definition at line 111 of file RFLO_ModDegenerateCornEdge.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getedgecellsindices(), and rflo_getpatchindices().
Referenced by rflo_findsourceregions().
subroutine, public rflo_markdegeneratvert (type(t_region), dimension(:), pointer regions)
Definition at line 245 of file RFLO_ModDegenerateCornEdge.F90.
References moderror::deregisterfunction(), i, ibeg, icorner, iend, ipnbeg, ipnend, j, jbeg, jend, jpnbeg, jpnend, k, kbeg, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_initflowsolver().
subroutine, public rflo_writedegeneratec (type(t_region), dimension(:), pointer regions)
Definition at line 488 of file RFLO_ModDegenerateCornEdge.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), form, icorner, moderror::registerfunction(), Attribute::status(), and x.
Referenced by rflo_initflowsolver().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModDegenerateCornEdge.F90,v $ $Revision: 1.3 $' private
Definition at line 61 of file RFLO_ModDegenerateCornEdge.F90.
The documentation for this module was generated from the following file:
RFLO_ModDegenerateCornEdge.F90