Rocstar: Scaling_repS2< FT > Class Template Reference
Scaling_repS2< FT > Class Template Reference
#include <Aff_transformationS2.h>
Public Member Functions
Scaling_repS2 ()
Scaling_repS2 (const FT &scalefactor)
~Scaling_repS2 ()
PointS2< FT > transform (const PointS2< FT > &p) const
VectorS2< FT > transform (const VectorS2< FT > &p) const
DirectionS2< FT > transform (const DirectionS2< FT > &d) const
Aff_transformationS2< FT > operator* (const Aff_transformation_rep_baseS2< FT > &t)
Aff_transformationS2< FT > compose (const Translation_repS2< FT > &t) const
virtual Aff_transformationS2< FT > compose (const Rotation_repS2< FT > &t) const
virtual Aff_transformationS2< FT > compose (const Scaling_repS2< FT > &t) const
virtual Aff_transformationS2< FT > compose (const Aff_transformation_repS2< FT > &t) const
Aff_transformationS2< FT > inverse () const
virtual bool is_even () const
virtual FT cartesian (int i, int j) const
virtual std::ostream & print (std::ostream &os) const
Public Member Functions inherited from Aff_transformation_rep_baseS2< FT >
virtual ~Aff_transformation_rep_baseS2 ()
Private Attributes
FT _scalefactor
Friends
class Aff_transformation_repS2< FT >
class Rotation_repS2< FT >
class Translation_repS2< FT >
Additional Inherited Members
Protected Member Functions inherited from Leda_like_rep
Leda_like_rep ()
virtual ~Leda_like_rep ()
Protected Attributes inherited from Leda_like_rep
int count
Detailed Description
template<class FT>
class Scaling_repS2< FT >
Definition at line 77 of file Aff_transformationS2.h.
Constructor & Destructor Documentation
Scaling_repS2 () inline
Definition at line 582 of file Aff_transformationS2.h.
   {}
Scaling_repS2 (const FT & scalefactor) inline
Definition at line 585 of file Aff_transformationS2.h.
                                        :
     _scalefactor(scalefactor)
   {}
~Scaling_repS2 () inline
Definition at line 589 of file Aff_transformationS2.h.
   {}
Member Function Documentation
virtual FT cartesian (int i, int j) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 672 of file Aff_transformationS2.h.
References Scaling_repS2< FT >::_scalefactor.
   {
     if (i!=j) return FT(0);
     return (i==2) ? FT(1) : _scalefactor;
   }
Aff_transformationS2<FT> compose (const Translation_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 622 of file Aff_transformationS2.h.
References Scaling_repS2< FT >::_scalefactor, and Translation_repS2< FT >::_translationvector.
   {
     FT ft0(0);
     return Aff_transformationS2<FT>(_scalefactor,
                                     ft0,
                                     t._translationvector.x(),
                                     ft0,
                                     _scalefactor,
                                     t._translationvector.y());
   }
virtual Aff_transformationS2<FT> compose (const Rotation_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 635 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Scaling_repS2< FT >::_scalefactor, and Rotation_repS2< FT >::_sinus.
   {
     return Aff_transformationS2<FT>(_scalefactor * t._cosinus,
                                     _scalefactor * -t._sinus,
                                     _scalefactor * t._sinus,
                                     _scalefactor * t._cosinus);
   }
virtual Aff_transformationS2<FT> compose (const Scaling_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 644 of file Aff_transformationS2.h.
References Scaling_repS2< FT >::_scalefactor, and SCALING.
   {
     return Aff_transformationS2<FT>(SCALING, _scalefactor*t._scalefactor);
   }
virtual Aff_transformationS2<FT> compose (const Aff_transformation_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 649 of file Aff_transformationS2.h.
References Scaling_repS2< FT >::_scalefactor, Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, and Aff_transformation_repS2< FT >::t23.
   {
     return Aff_transformationS2<FT>(_scalefactor * t.t11,
                                     _scalefactor * t.t12,
                                      t.t13,
                                     _scalefactor * t.t21,
                                     _scalefactor * t.t22,
                                      t.t23);
   }
Aff_transformationS2<FT> inverse () const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 662 of file Aff_transformationS2.h.
References Scaling_repS2< FT >::_scalefactor, and SCALING.
   {
     return Aff_transformationS2<FT>(SCALING, FT(1)/_scalefactor);
   }
virtual bool is_even () const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 667 of file Aff_transformationS2.h.
   {
     return true;
   }
Aff_transformationS2<FT> operator* (const Aff_transformation_rep_baseS2< FT > & t) inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 616 of file Aff_transformationS2.h.
References Aff_transformation_rep_baseS2< FT >::compose().
   {
    return t.compose(*this);
   }
virtual std::ostream& print (std::ostream & os) const inline virtual
Definition at line 678 of file Aff_transformationS2.h.
References Scaling_repS2< FT >::_scalefactor.
   {
     os << "Aff_transformationS2(" << _scalefactor <<  ")";
     return os;
   }
PointS2<FT> transform (const PointS2< FT > & p) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 592 of file Aff_transformationS2.h.
References Scaling_repS2< FT >::_scalefactor, PointS2< FT >::x(), and PointS2< FT >::y().
   {
     return PointS2<FT>(_scalefactor * p.x(), _scalefactor * p.y());
   }
VectorS2<FT> transform (const VectorS2< FT > & p) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 597 of file Aff_transformationS2.h.
References Scaling_repS2< FT >::_scalefactor, VectorS2< FT >::x(), and VectorS2< FT >::y().
   {
     return VectorS2<FT>(_scalefactor * p.x(), _scalefactor * p.y());
   }
DirectionS2<FT> transform (const DirectionS2< FT > & d) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 602 of file Aff_transformationS2.h.
   {
     return d;
   }
Friends And Related Function Documentation
friend class Aff_transformation_repS2< FT > friend
Definition at line 577 of file Aff_transformationS2.h.
friend class Rotation_repS2< FT > friend
Definition at line 578 of file Aff_transformationS2.h.
friend class Translation_repS2< FT > friend
Definition at line 579 of file Aff_transformationS2.h.
Member Data Documentation
FT _scalefactor private
Definition at line 685 of file Aff_transformationS2.h.
Referenced by Scaling_repS2< FT >::cartesian(), Aff_transformation_repS2< FT >::compose(), Translation_repS2< FT >::compose(), Rotation_repS2< FT >::compose(), Scaling_repS2< FT >::compose(), Scaling_repS2< FT >::inverse(), Scaling_repS2< FT >::print(), and Scaling_repS2< FT >::transform().
The documentation for this class was generated from the following file:
Aff_transformationS2.h