Rocstar: rflu_modgambit Module Reference
rflu_modgambit Module Reference
Data Types
type t_gridgambit
type t_patchgambit
Public Member Functions
subroutine, public rflu_convgambit2rocflu (pRegion)
subroutine, public rflu_readgridgambitneutral (pRegion)
Private Member Functions
subroutine rflu_checkgridgambit (pRegion)
subroutine rflu_printgridgambitinfo (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModGAMBIT.F90,v $ $Revision: 1.4 $'
integer, parameter gambit_ntype_edge = 1
integer, parameter gambit_ntype_quad = 2
integer, parameter gambit_ntype_tri = 3
integer, parameter gambit_ntype_hex = 4
integer, parameter gambit_ntype_pri = 5
integer, parameter gambit_ntype_tet = 6
integer, parameter gambit_ntype_pyr = 7
integer, dimension(4), parameter f2ftetgambit = (/4,1,2,3/)
integer, dimension(6), parameter f2fhexgambit = (/2,3,4,5,1,6/)
integer, dimension(5), parameter f2fprigambit = (/2,3,4,1,5/)
integer, dimension(5), parameter f2fpyrgambit = (/1,2,3,4,5/)
integer, dimension(4, 4), parameter f2vtetgambit = RESHAPE((/2,1,3,VERT_NONE,1,2,4,VERT_NONE,2,3,4,VERT_NONE,3,1,4, VERT_NONE/), (/4,4/))
integer, dimension(4, 6), parameter f2vhexgambit = RESHAPE((/1,2,6,5,2,4,8,6,4,3,7,8,3,1,5,7,2,1,3,4,5,6,7,8/), (/4,6/))
integer, dimension(4, 5), parameter f2vprigambit = RESHAPE((/1,2,5,4,2,3,6,5,3,1,4,6,1,3,2,VERT_NONE,4,5,6, VERT_NONE/), (/4,5/))
integer, dimension(4, 5), parameter f2vpyrgambit = RESHAPE((/1,3,4,2,1,2,5,VERT_NONE,2,4,5,VERT_NONE,4,3,5,VERT_NONE,3,1,5, VERT_NONE/), (/4,5/))
type(t_gridgambit) gridgambit
Detailed Description
Definition at line 39 of file RFLU_ModGAMBIT.F90.
Member Function/Subroutine Documentation
subroutine rflu_checkgridgambit (type(t_region), pointer pRegion) private
Definition at line 159 of file RFLU_ModGAMBIT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_readgridgambitneutral().
subroutine, public rflu_convgambit2rocflu (type(t_region), pointer pRegion)
Definition at line 270 of file RFLU_ModGAMBIT.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), rflu_moddimensions::rflu_setmaxdimension(), and Attribute::status().
Referenced by rflu_readconvgridwrapper().
subroutine rflu_printgridgambitinfo (type(t_region), pointer pRegion) private
Definition at line 934 of file RFLU_ModGAMBIT.F90.
Referenced by rflu_readgridgambitneutral().
subroutine, public rflu_readgridgambitneutral (type(t_region), pointer pRegion)
Definition at line 1017 of file RFLU_ModGAMBIT.F90.
References buildfilenameplain(), moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, moderror::registerfunction(), rflu_checkgridgambit(), rflu_printgridgambitinfo(), rflu_moddimensions::rflu_setmaxdimension(), and Attribute::status().
Referenced by rflu_readconvgridwrapper().
Member Data Documentation
integer, dimension(6), parameter f2fhexgambit = (/2,3,4,5,1,6/) private
Definition at line 102 of file RFLU_ModGAMBIT.F90.
integer, dimension(5), parameter f2fprigambit = (/2,3,4,1,5/) private
Definition at line 103 of file RFLU_ModGAMBIT.F90.
integer, dimension(5), parameter f2fpyrgambit = (/1,2,3,4,5/) private
Definition at line 104 of file RFLU_ModGAMBIT.F90.
integer, dimension(4), parameter f2ftetgambit = (/4,1,2,3/) private
Definition at line 101 of file RFLU_ModGAMBIT.F90.
integer, dimension(4,6), parameter f2vhexgambit = RESHAPE((/1,2,6,5,2,4,8,6,4,3,7,8,3,1,5,7,2,1,3,4,5,6,7,8/), (/4,6/)) private
Definition at line 113 of file RFLU_ModGAMBIT.F90.
integer, dimension(4,5), parameter f2vprigambit = RESHAPE((/1,2,5,4,2,3,6,5,3,1,4,6,1,3,2,VERT_NONE,4,5,6, VERT_NONE/), (/4,5/)) private
Definition at line 115 of file RFLU_ModGAMBIT.F90.
integer, dimension(4,5), parameter f2vpyrgambit = RESHAPE((/1,3,4,2,1,2,5,VERT_NONE,2,4,5,VERT_NONE,4,3,5,VERT_NONE,3,1,5, VERT_NONE/), (/4,5/)) private
Definition at line 118 of file RFLU_ModGAMBIT.F90.
integer, dimension(4,4), parameter f2vtetgambit = RESHAPE((/2,1,3,VERT_NONE,1,2,4,VERT_NONE,2,3,4,VERT_NONE,3,1,4, VERT_NONE/), (/4,4/)) private
Definition at line 110 of file RFLU_ModGAMBIT.F90.
integer, parameter gambit_ntype_edge = 1 private
Definition at line 89 of file RFLU_ModGAMBIT.F90.
integer, parameter gambit_ntype_hex = 4 private
Definition at line 89 of file RFLU_ModGAMBIT.F90.
integer, parameter gambit_ntype_pri = 5 private
Definition at line 89 of file RFLU_ModGAMBIT.F90.
integer, parameter gambit_ntype_pyr = 7 private
Definition at line 89 of file RFLU_ModGAMBIT.F90.
integer, parameter gambit_ntype_quad = 2 private
Definition at line 89 of file RFLU_ModGAMBIT.F90.
integer, parameter gambit_ntype_tet = 6 private
Definition at line 89 of file RFLU_ModGAMBIT.F90.
integer, parameter gambit_ntype_tri = 3 private
Definition at line 89 of file RFLU_ModGAMBIT.F90.
type(t_gridgambit) gridgambit private
Definition at line 122 of file RFLU_ModGAMBIT.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModGAMBIT.F90,v $ $Revision: 1.4 $' private
Definition at line 82 of file RFLU_ModGAMBIT.F90.
The documentation for this module was generated from the following file:
RFLU_ModGAMBIT.F90