Rocstar: FloGrid Class Reference
FloGrid Class Reference
#include <FloGrid.H>
Public Member Functions
FloGrid ()
FloGrid (const std::string &casename)
std::string Casename () const
double Time () const
std::vector< FloGridBlock > & Blocks ()
const std::vector< FloGridBlock > & Blocks () const
double UnknownNumber () const
int ReadAllBlocks ()
int ReadNBlocks (int first, int nblocks)
int BlockCount ()
void DestroyGrids ()
void SetGhostLayers (unsigned int n)
void CreateSolutions ()
int OpenSolutionFile (const std::string &timestamp, double time, double unknown_number)
void CloseSolutionFile ()
std::ofstream & SolnFile ()
int WriteSolutionFile (const std::string &timestamp, double time, double unknown_number)
int WriteBlocks (std::ostream &Ouf)
int ReadAllSolutions (const std::string &timestamp)
Protected Attributes
std::string _casename
std::vector< FloGridBlock > _blocks
std::ofstream _solnfile
double _time
double _unknown_number
Detailed Description
Definition at line 276 of file FloGrid.H.
Constructor & Destructor Documentation
FloGrid () inline
Definition at line 284 of file FloGrid.H.
References _blocks, and _time.
             : _casename("")
   { _blocks.resize(0); _time=0.0;};
FloGrid (const std::string & casename) inline
Definition at line 286 of file FloGrid.H.
References _blocks, and _time.
     : _casename(casename)
   {_blocks.resize(0); _time=0.0;};
Member Function Documentation
int BlockCount () inline
Definition at line 350 of file FloGrid.H.
References _casename, and FloGridBlock::ReadBlock().
Referenced by main().
   {
     std::string sourcegridfile(_casename+".grda_0.00000E-00");
     std::cout << "Reading grid file: " << sourcegridfile << std::endl;
     std::ifstream Inf;
     Inf.open(sourcegridfile.c_str());
     if(!Inf){
       std::cout << "FloGrid::ReadAllBlocks: Could not open source grid file, "
                 << sourcegridfile << std::endl;
       return(1);
     }
     std::string ftimestamp;
     std::getline(Inf,ftimestamp);
     int n = 0;
     while(Inf){
       FloGridBlock block;
       block.ReadBlock(Inf);
       n++;
     }
     Inf.close();
     return(n-1);
   };
std::vector<FloGridBlock>& Blocks () inline
Definition at line 291 of file FloGrid.H.
References _blocks.
Referenced by main().
 { return (_blocks); };
const std::vector<FloGridBlock>& Blocks () const inline
Definition at line 292 of file FloGrid.H.
References _blocks.
 { return (_blocks); };
std::string Casename () const inline
Definition at line 289 of file FloGrid.H.
References _casename.
 { return (_casename); };
void CloseSolutionFile () inline
Definition at line 407 of file FloGrid.H.
References _solnfile.
Referenced by main(), and WriteSolutionFile().
 { _solnfile.close(); };
void CreateSolutions () inline
Definition at line 386 of file FloGrid.H.
References _blocks.
Referenced by main().
   {
     std::vector<FloGridBlock>::iterator fgbi = _blocks.begin();
     while(fgbi != _blocks.end())
       fgbi++->CreateSoln();
   };
void DestroyGrids () inline
Definition at line 374 of file FloGrid.H.
References _blocks.
   {
     std::vector<FloGridBlock>::iterator fgbi = _blocks.begin();
     while(fgbi != _blocks.end())
       fgbi++->DestroyGrid();
   };
int OpenSolutionFile (const std::string & timestamp, double time, double unknown_number) inline
Definition at line 392 of file FloGrid.H.
References _casename, and _solnfile.
Referenced by main(), and WriteSolutionFile().
   {
     std::string solnfile(_casename+".sola_"+timestamp);
     //    std::ofstream Ouf;
     _solnfile.open(solnfile.c_str());
     if(!_solnfile){
       std::cout << "FloGrid::OpenSolutionFile Could not open source soln file, "
                 << solnfile << std::endl;
       return(1);
     }
     _solnfile << std::scientific << std::setprecision(16);
     _solnfile << time << "\t" << unknown_number << std::endl;
     return(0);
   };
int ReadAllBlocks () inline
Definition at line 294 of file FloGrid.H.
References _blocks, _casename, and FloGridBlock::ReadBlock().
Referenced by main().
   {
     std::string sourcegridfile(_casename+".grda_0.00000E-00");
     //    std::cout << "Reading grid file: " << sourcegridfile << std::endl;
     std::ifstream Inf;
     Inf.open(sourcegridfile.c_str());
     if(!Inf){
       std::cout << "FloGrid::ReadAllBlocks: Could not open source grid file, "
                 << sourcegridfile << std::endl;
       return(1);
     }
     std::string ftimestamp;
     std::getline(Inf,ftimestamp);
     while(Inf){
       FloGridBlock block;
       if(block.ReadBlock(Inf) == 0){
         _blocks.push_back(block);
       }
     }
     Inf.close();
     return(0);
   };
int ReadAllSolutions (const std::string & timestamp) inline
Definition at line 444 of file FloGrid.H.
References _blocks, _casename, _time, and _unknown_number.
Referenced by main().
   {
     std::string sourcesolnfile(_casename+".sola_"+timestamp);
     //    std::cout << "Reading soln file: " << sourcesolnfile << std::endl;
     std::ifstream Inf;
     Inf.open(sourcesolnfile.c_str());
     if(!Inf){
       std::cout << "FloGrid::ReadAllSoln: Could not open source soln file, "
                 << sourcesolnfile << std::endl;
       return(1);
     }
     std::string ftimestamp;
     std::getline(Inf,ftimestamp);
     std::istringstream Istr(ftimestamp);
     Istr >> _time >> _unknown_number;
     std::vector<FloGridBlock>::iterator fgbi = _blocks.begin();
     while(fgbi != _blocks.end()){
       fgbi++->ReadBlockSoln(Inf);
       if(!Inf && (fgbi != _blocks.end()))
         return(1);
     }
     Inf.close();
     return(0);
   };
int ReadNBlocks (int first, int nblocks) inline
Definition at line 319 of file FloGrid.H.
References _blocks, _casename, and FloGridBlock::ReadBlock().
Referenced by main().
   {
     std::string sourcegridfile(_casename+".grda_0.00000E-00");
     //    std::cout << "Reading grid file: " << sourcegridfile << std::endl;
     std::ifstream Inf;
     Inf.open(sourcegridfile.c_str());
     if(!Inf){
       std::cout << "FloGrid::ReadAllBlocks: Could not open source grid file, "
                 << sourcegridfile << std::endl;
       return(1);
     }
     std::string ftimestamp;
     std::getline(Inf,ftimestamp);
     int n = 1;
     while(n < first){
       FloGridBlock block;
       block.ReadBlock(Inf);
       n++;
     }
     while(n < (first + nblocks)){
       FloGridBlock block;
       if(block.ReadBlock(Inf) == 0){
         _blocks.push_back(block);
       }
       n++;
     }
     Inf.close();
     return(0);
   };
void SetGhostLayers (unsigned int n) inline
Definition at line 380 of file FloGrid.H.
References _blocks.
Referenced by main().
   {
     std::vector<FloGridBlock>::iterator fgbi = _blocks.begin();
     while(fgbi != _blocks.end())
       fgbi++->SetGhostLayers(n);
   };
std::ofstream& SolnFile () inline
Definition at line 408 of file FloGrid.H.
References _solnfile.
Referenced by main().
 { return (_solnfile); };
double Time () const inline
Definition at line 290 of file FloGrid.H.
References _time.
Referenced by main().
 { return (_time); };
double UnknownNumber () const inline
Definition at line 293 of file FloGrid.H.
References _unknown_number.
Referenced by main().
 { return (_unknown_number); };
int WriteBlocks (std::ostream & Ouf) inline
Definition at line 424 of file FloGrid.H.
References _blocks.
Referenced by main().
   {
     //    std::string sourcesolnfile(_casename+".sola_"+timestamp);
     //    std::cout << "Writing soln file: " << sourcesolnfile << std::endl;
     //    std::ofstream Ouf;
     //    Ouf.open(sourcesolnfile.c_str());
     //    if(!Ouf){
     //      std::cout << "FloGrid::WriteSolutionFile Could not open source soln file, "
     //          << sourcesolnfile << std::endl;
     //      return(1);
     //    }
     //    Ouf << std::scientific << std::setprecision(16);
     //    Ouf << time << "\t" << unknown_number << std::endl;
     int datasize = 0;
     std::vector<FloGridBlock>::iterator fgbi = _blocks.begin();
     while(fgbi != _blocks.end())
       datasize += (fgbi++->WriteBlockSoln(Ouf));
     return(datasize);
   };
int WriteSolutionFile (const std::string & timestamp, double time, double unknown_number) inline
Definition at line 409 of file FloGrid.H.
References _blocks, _solnfile, CloseSolutionFile(), and OpenSolutionFile().
   {
     if(OpenSolutionFile(timestamp,time,unknown_number))
       return(1);
     std::vector<FloGridBlock>::iterator fgbi = _blocks.begin();
     while(fgbi != _blocks.end()){
       fgbi++->WriteBlockSoln(_solnfile);
       if(!_solnfile && (fgbi != _blocks.end()))
         return(1);
     }
     CloseSolutionFile();
     return(0);
   };
Member Data Documentation
std::vector<FloGridBlock> _blocks protected
Definition at line 279 of file FloGrid.H.
Referenced by Blocks(), CreateSolutions(), DestroyGrids(), FloGrid(), ReadAllBlocks(), ReadAllSolutions(), ReadNBlocks(), SetGhostLayers(), WriteBlocks(), and WriteSolutionFile().
std::string _casename protected
Definition at line 278 of file FloGrid.H.
Referenced by BlockCount(), Casename(), OpenSolutionFile(), ReadAllBlocks(), ReadAllSolutions(), and ReadNBlocks().
std::ofstream _solnfile protected
Definition at line 280 of file FloGrid.H.
Referenced by CloseSolutionFile(), OpenSolutionFile(), SolnFile(), and WriteSolutionFile().
double _time protected
Definition at line 281 of file FloGrid.H.
Referenced by FloGrid(), ReadAllSolutions(), and Time().
double _unknown_number protected
Definition at line 282 of file FloGrid.H.
Referenced by ReadAllSolutions(), and UnknownNumber().
The documentation for this class was generated from the following file:
FloGrid.H