Rocstar: LaplacianSmoother Class Reference
LaplacianSmoother Class Reference
#include <LaplacianSmoother.hpp>
Public Member Functions
LaplacianSmoother (MsqError &err)
~LaplacianSmoother ()
LaplacianSmoother (MsqError &err)
~LaplacianSmoother ()
Public Member Functions inherited from VertexMover
virtual ~VertexMover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
Improves the quality of the MeshSet, calling some methods specified in a class derived from VertexMover.
virtual ~VertexMover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
Public Member Functions inherited from QualityImprover
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Protected Member Functions
virtual void initialize (PatchData &pd, MsqError &err)
virtual void optimize_vertex_positions (PatchData &pd, MsqError &err)
virtual void initialize_mesh_iteration (PatchData &pd, MsqError &err)
virtual void terminate_mesh_iteration (PatchData &pd, MsqError &err)
virtual void cleanup ()
virtual void initialize (PatchData &pd, MsqError &err)
virtual void optimize_vertex_positions (PatchData &pd, MsqError &err)
virtual void initialize_mesh_iteration (PatchData &pd, MsqError &err)
virtual void terminate_mesh_iteration (PatchData &pd, MsqError &err)
virtual void cleanup ()
Protected Member Functions inherited from VertexMover
VertexMover ()
size_t check_feasible (PatchData &pd, MsqError &err)
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
VertexMover ()
size_t check_feasible (PatchData &pd, MsqError &err)
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
Protected Member Functions inherited from QualityImprover
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Private Attributes
QualityMetric * edgeQM
Additional Inherited Members
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Protected Attributes inherited from VertexMover
ObjectiveFunction * objFunc
Detailed Description
Moves free center vertex to the average of the neighboring vertices.
Definition at line 57 of file includeLinks/LaplacianSmoother.hpp.
Constructor & Destructor Documentation
LaplacianSmoother (MsqError & err)
Definition at line 46 of file QualityImprover/VertexMover/LaplacianSmoothers/LaplacianSmoother.cpp.
References LaplacianSmoother::edgeQM, PatchData::ELEMENTS_ON_VERTEX_PATCH, MSQ_ERRRTN, VertexMover::objFunc, QualityMetric::RMS, QualityMetric::set_averaging_method(), QualityImprover::set_name(), and PatchDataUser::set_patch_type().
 {
   this->set_name("LaplacianSmoother");
   set_patch_type(PatchData::ELEMENTS_ON_VERTEX_PATCH, err,1,1);MSQ_ERRRTN(err);
   edgeQM = new EdgeLengthQualityMetric;
   edgeQM->set_averaging_method(QualityMetric::RMS,err);MSQ_ERRRTN(err);
   objFunc = new LPtoPTemplate(edgeQM, 2, err);MSQ_ERRRTN(err);
 }
~LaplacianSmoother ()
Definition at line 58 of file QualityImprover/VertexMover/LaplacianSmoothers/LaplacianSmoother.cpp.
References LaplacianSmoother::edgeQM, and VertexMover::objFunc.
 {
   delete edgeQM;
   delete objFunc;
 }
LaplacianSmoother (MsqError & err)
~LaplacianSmoother ()
Member Function Documentation
void cleanup () protected virtual
Implements VertexMover.
Definition at line 115 of file QualityImprover/VertexMover/LaplacianSmoothers/LaplacianSmoother.cpp.
 {
   //  cout << "- Executing LaplacianSmoother::iteration_end()\n";
 }
virtual void cleanup () protected virtual
Implements VertexMover.
void initialize (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 65 of file QualityImprover/VertexMover/LaplacianSmoothers/LaplacianSmoother.cpp.
 {
 }
virtual void initialize (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
virtual void initialize_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
void initialize_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 71 of file QualityImprover/VertexMover/LaplacianSmoothers/LaplacianSmoother.cpp.
 {
   //  cout << "- Executing LaplacianSmoother::iteration_complete()\n";
 }
void optimize_vertex_positions (PatchData & pd, MsqError & err) protected virtual
Todo:
Michael: optimize_vertex_position is probably not implemented in an optimal way. We used to use all of the vertices in the patch as 'adjacent' vertices. Now we call get_adjacent_vertex_indices. We could use a VERTICES_ON_VERTEX type of patch or a global patch?
Todo:
Michael: optimize_vertex_position is probably not implemented in an optimal way. We used to use all of the vertices in the patch as 'adjacent' vertices. Now we call get_adjacent_vertex_indices. We could use a VERTICES_ON_VERTEX type of patch or a global patch?
Implements VertexMover.
Definition at line 83 of file QualityImprover/VertexMover/LaplacianSmoothers/LaplacianSmoother.cpp.
References Mesquite::centroid_smooth_mesh(), PatchData::get_adjacent_vertex_indices(), MSQ_ERRRTN, MsqFreeVertexIndexIterator::next(), MsqFreeVertexIndexIterator::reset(), PatchData::snap_vertex_to_domain(), and MsqFreeVertexIndexIterator::value().
 {
     //default the laplacian smoother to 3 even for 2-d elements.
     //int dim = get_mesh_set()->space_dim();
   size_t dim = 3;
   // does the Laplacian smoothing
   MsqFreeVertexIndexIterator free_iter(&pd, err);  MSQ_ERRRTN(err);
   free_iter.reset();
   free_iter.next();
     //m is the free vertex.
   size_t m=free_iter.value();
   msq_std::vector<size_t> vert_indices;
   vert_indices.reserve(25);
     //get vertices adjacent to vertex m
   pd.get_adjacent_vertex_indices(m,vert_indices,err);  MSQ_ERRRTN(err);
     //move vertex m
   centroid_smooth_mesh(pd, vert_indices.size(), vert_indices,
                        m, dim, err); MSQ_ERRRTN(err);
     //snap vertex m to domain
   pd.snap_vertex_to_domain(m,err);
 }
virtual void optimize_vertex_positions (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
void terminate_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 109 of file QualityImprover/VertexMover/LaplacianSmoothers/LaplacianSmoother.cpp.
 {
   //  cout << "- Executing LaplacianSmoother::iteration_complete()\n";
 }
virtual void terminate_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Member Data Documentation
QualityMetric * edgeQM private
Definition at line 71 of file includeLinks/LaplacianSmoother.hpp.
Referenced by LaplacianSmoother::LaplacianSmoother(), and LaplacianSmoother::~LaplacianSmoother().
The documentation for this class was generated from the following files:
includeLinks/LaplacianSmoother.hpp
QualityImprover/VertexMover/LaplacianSmoothers/LaplacianSmoother.cpp