Rocstar: connect_points Class Reference
connect_points Class Reference
#include <points.h>
Classes
struct conn_points
Public Member Functions
connect_points ()
virtual ~connect_points ()
connect_points & operator= (const connect_points &cp)
connect_points (const connect_points &cp)
virtual connect_points * clone ()
virtual int get_closest (long double *coord)
void set_connectivity (int point_num, int c_point)
virtual std::vector< int > get_connected_points (int point_num)
virtual void sort ()
Public Member Functions inherited from points
points ()
points (int num_points)
points (const points &p)
points & operator= (const points &p)
virtual ~points ()
void set_num_points (int n)
void set_num_vars (int n)
void set_num_indep_vars (int indep_vars)
int get_num_points ()
int get_num_vars ()
int get_num_indep_vars ()
void set_point_val (int point_number, int var, long double val)
void clear_dep_vars (int point_number)
pnt get_point (int n)
long double largest_val (int dim)
long double smallest_val (int dim)
Private Attributes
conn_points * c_points
Additional Inherited Members
Static Public Member Functions inherited from points
static void delete_all (std::vector< points * > points_vector)
static bool contains_null (std::vector< points * > points_vector)
Protected Attributes inherited from points
int num_points
int num_vars
int num_indep_vars
pnt ** pt_str
bitmap pt_set
Detailed Description
Definition at line 95 of file points.h.
Constructor & Destructor Documentation
connect_points ()
Definition at line 250 of file points.cpp.
References c_points.
Referenced by clone().
{
     c_points = NULL;
 }
~connect_points () virtual
Definition at line 254 of file points.cpp.
References c_points.
{
     delete[] c_points;
 }
connect_points (const connect_points & cp)
Definition at line 258 of file points.cpp.
References c_points, i, and points::num_points.
                                                        : points(cp) {
     if(cp.num_points > 0){
         c_points = new conn_points[num_points];
         for(int i=0; i<num_points; i++){
             c_points[i] = cp.c_points[i];
         }
     }
 }
Member Function Documentation
connect_points * clone () virtual
Reimplemented from points.
Definition at line 289 of file points.cpp.
References connect_points().
{
     return new connect_points(*this);
 }
int get_closest (long double * coord) virtual
Reimplemented from points.
Definition at line 293 of file points.cpp.
References dist(), i, points::num_indep_vars, points::num_points, points::pt_str, and pnt::vals.
{
     long double low_dist = std::numeric_limits<long double>::infinity();
     int low_point = -1;
     //Iterate through all points and find the point that's closest
     //to the specified point
     for(int i=0; i<num_points; i++){
         long double *d_calc = new long double[num_indep_vars];
             for(int m=0; m<num_indep_vars; m++){
                 d_calc[m] = pt_str[i]->vals[m];
             }
         long double distance = dist(coord, d_calc, num_indep_vars);
         if( distance < low_dist ){
             low_dist = distance;
             low_point = i;
         }
         delete[] d_calc;
     }
     return low_point;
 }
std::vector< int > get_connected_points (int point_num) virtual
Reimplemented from points.
Definition at line 344 of file points.cpp.
References c_points, i, and connect_points::conn_points::points.
{
     std::vector<int> ret;
     //Point numbers start at 1
     //Subtract 1 for array storage (starting at 0)
     point_num = point_num - 1;
     if(point_num < 0)
         return ret;
     for(int i=0; i<c_points[point_num].points.size(); i++){
         ret.push_back(c_points[point_num].points[i]);
     }
     return ret;
 }
connect_points & operator= (const connect_points & cp)
Definition at line 270 of file points.cpp.
References c_points, i, points::num_points, and points::operator=().
{
     if(this != &cp){
         int curr_pts = num_points;
         points::operator = (cp);
         delete[] c_points;
         c_points = new conn_points[cp.num_points];
         for(int i=0; i<cp.num_points; i++){
             c_points[i] = cp.c_points[i];
         }
     }
     return *this;
 }
void set_connectivity (int point_num, int c_point)
Definition at line 321 of file points.cpp.
References c_points, i, points::num_points, connect_points::conn_points::points, and connect_points::conn_points::set_next().
Referenced by tpz_fequad::parse_data().
{
     //Point numbers start at 1
     //Subtract 1 for array storage (starting at 0)
     point_num = point_num - 1;
     if(c_points == NULL && num_points > 0){
         c_points = new conn_points[num_points];
     }
     bool dup = false;
     for(int i=0; i<c_points[point_num].points.size(); i++){
         if(c_points[point_num].points[i] == c_point){
             dup = true;
             break;
         }
     }
     if(!dup)
         c_points[point_num].set_next(c_point);
 }
void sort () virtual
Reimplemented from points.
Definition at line 363 of file points.cpp.
{
     return;
 }
Member Data Documentation
conn_points* c_points private
Definition at line 144 of file points.h.
Referenced by connect_points(), get_connected_points(), operator=(), set_connectivity(), and ~connect_points().
The documentation for this class was generated from the following files:
points.h
points.cpp