Rocstar: adjList Class Reference
adjList Class Reference
#include <adj.h>
Public Member Functions
adjList ()
~adjList ()
int getLength (void) const
bool hasFace (const face *test) const
bool hasLoc (const face *test, const blockLoc &l) const
void addFace (face *b, const blockLoc &l)
const blockLoc & getLoc (const face *b) const
bool isExternal (void) const
void print (void) const
Protected Attributes
adjRec * next
Detailed Description
Definition at line 123 of file adj.h.
Constructor & Destructor Documentation
adjList () inline
Definition at line 127 of file adj.h.
References next.
                   {
                 next=NULL;
         }
~adjList ()
Definition at line 79 of file adj.cpp.
References adjRec::getNext(), and next.
                   {
         adjRec *cur=next;
         while (cur!=NULL) {
                 adjRec *old=cur;
                 cur=cur->getNext();
                 delete old;
         }
 }
Member Function Documentation
void addFace (face * b, const blockLoc & l)
Definition at line 105 of file adj.cpp.
References hasLoc(), and next.
Referenced by face::face().
 {
         if (!hasLoc(b,l))
                 next=new adjRec(b,l,next);
 }
int getLength (void) const
Definition at line 87 of file adj.cpp.
References adjRec::getNext(), and next.
Referenced by face::face().
{
         int ret=0;
         for (adjRec *cur=next;cur!=NULL;cur=cur->getNext())
                 ret++;
         return ret;
 }
const blockLoc & getLoc (const face * b) const
Definition at line 111 of file adj.cpp.
References adjRec::getNext(), and next.
Referenced by node::getLoc().
 {
         for (adjRec *cur=next;cur!=NULL;cur=cur->getNext())
                 if (in==cur->getFace())
                         return cur->getLoc();
         static blockLoc badLoc(-1,-1,-1);
         return badLoc;
 }
bool hasFace (const face * test) const
Definition at line 93 of file adj.cpp.
References adjRec::getNext(), and next.
{
         for (adjRec *cur=next;cur!=NULL;cur=cur->getNext())
                 if (test==cur->getFace())
                         return true;
         return false;
 }
bool hasLoc (const face * test, const blockLoc & l) const
Definition at line 99 of file adj.cpp.
References adjRec::getNext(), and next.
Referenced by addFace(), and face::nodesMatch().
{
         for (adjRec *cur=next;cur!=NULL;cur=cur->getNext())
                 if (test==cur->getFace() && l==cur->getLoc())
                         return true;
         return false;
 }
bool isExternal (void) const
Definition at line 76 of file buildface.cpp.
References adjRec::getFace(), adjRec::getLoc(), adjRec::getNext(), patch::isExternal(), next, and face::patchForCoord().
Referenced by buildFaces().
 {
         adjRec *cur=next;
         while (cur!=NULL) {
                 patch *p=cur->getFace()->patchForCoord(cur->getLoc());
                 if (p->isExternal())
                         return true;
                 cur=cur->getNext();
         }
         return false;
 }
void print (void) const
Definition at line 120 of file adj.cpp.
References next, and adjRec::print().
Referenced by face::face().
{
         if (next) next->print();
         else printf("Empty.\n");
 }
Member Data Documentation
adjRec* next protected
Definition at line 125 of file adj.h.
Referenced by addFace(), adjList(), getLength(), getLoc(), hasFace(), hasLoc(), node::intersect(), isExternal(), print(), and ~adjList().
The documentation for this class was generated from the following files:
adj.h
adj.cpp
buildface.cpp