Rocstar: Vector_2< Type > Class Template Reference
Vector_2< Type > Class Template Reference
#include <mapbasic.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Vector_2_base RVector_2
Public Member Functions
Vector_2 ()
Vector_2 (Type t)
Vector_2 (Null_vector)
Vector_2 (Type a, Type b)
Type & operator[] (const int i)
const Type & operator[] (const int &i) const
Type x () const
Type y () const
Vector_2 & operator+= (const Vector_2 &v)
Assign operators.
Vector_2 & operator-= (const Vector_2 &v)
Vector_2 & operator*= (const Type t)
Vector_2 & operator/= (const Type t)
Vector_2 operator+ (const Vector_2 &v) const
Arithmatic operators.
Vector_2 operator- (const Vector_2 &v) const
Vector_2 operator* (const Type t) const
Vector_2 operator/ (const Type t) const
Type operator* (const Vector_2 &v) const
Vector_2 operator- () const
Type squared_norm () const
Type norm () const
Vector_2 & normalize ()
Vector_2 & neg ()
bool operator== (const Vector_2 &p) const
bool operator!= (const Vector_2 &p) const
bool operator< (const Vector_2 &v) const
bool is_null () const
Vector_2 ()
Vector_2 (const CGAL::Vector_2< R > &v)
Vector_2 (const RVector_2 &v)
Vector_2 (const Null_vector &v)
Vector_2 (const RT &x, const RT &y)
Vector_2 (const RT &x, const RT &y, const RT &w)
bool operator== (const CGAL::Vector_2< R > &v) const
bool operator!= (const CGAL::Vector_2< R > &v) const
bool operator== (const Null_vector &v) const
bool operator!= (const Null_vector &v) const
RT hx () const
RT hy () const
RT hw () const
FT x () const
FT y () const
RT homogeneous (int i) const
FT cartesian (int i) const
FT operator[] (int i) const
int dimension () const
CGAL::Vector_2< R > operator+ (const CGAL::Vector_2< R > &w) const
CGAL::Vector_2< R > operator- (const CGAL::Vector_2< R > &w) const
CGAL::Vector_2< R > operator- () const
FT operator* (const CGAL::Vector_2< R > &w) const
CGAL::Vector_2< R > operator* (const RT &c) const
CGAL::Vector_2< R > operator* (const Quotient< RT > &q) const
CGAL::Vector_2< R > operator/ (const Quotient< RT > &q) const
CGAL::Vector_2< R > operator/ (const RT &c) const
CGAL::Direction_2< R > direction () const
CGAL::Vector_2< R > perpendicular (const Orientation &o) const
CGAL::Vector_2< R > transform (const CGAL::Aff_transformation_2< R > &t) const
Protected Attributes
Type _x
Type _y
Private Member Functions
Vector_2 (const CGAL::Point_2< R > &p)
Vector_2 (const CGAL::Direction_2< R > &d)
Friends
CGAL_FRIEND_INLINE
CGAL::Vector_2< R > CGAL_SCOPE
point_to_vector_conversion CGAL_NULL_TMPL_ARGS (const CGAL::Point_2< R > &p)
Detailed Description
template<class Type>
class Vector_2< Type >
Definition at line 199 of file mapbasic.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 84 of file Vector_2.h.
typedef R_ R
Definition at line 82 of file Vector_2.h.
typedef R::RT RT
Definition at line 83 of file Vector_2.h.
typedef R::Vector_2_base RVector_2
Definition at line 85 of file Vector_2.h.
Constructor & Destructor Documentation
Vector_2 () inline
Definition at line 201 of file mapbasic.h.
Referenced by Vector_2< T >::operator*(), Vector_2< T >::operator+(), Vector_2< T >::operator-(), and Vector_2< T >::operator/().
 {}
Vector_2 (Type t) inline explicit
Definition at line 202 of file mapbasic.h.
 : _x(t), _y(t) {}
Vector_2 (Null_vector) inline
Definition at line 203 of file mapbasic.h.
 : _x(0), _y(0) {}
Vector_2 (Type a, Type b) inline
Definition at line 204 of file mapbasic.h.
 : _x(a), _y(b) {}
Vector_2 () inline
Definition at line 92 of file Vector_2.h.
 {}
Vector_2 (const CGAL::Vector_2< R > & v) inline
Definition at line 94 of file Vector_2.h.
 : RVector_2((const RVector_2&)v) {}
Vector_2 (const RVector_2< Type > & v) inline
Definition at line 96 of file Vector_2.h.
 : RVector_2(v) {}
Vector_2 (const Null_vector & v) inline
Definition at line 98 of file Vector_2.h.
 : RVector_2(v) {}
Vector_2 (const RT & x, const RT & y) inline
Definition at line 100 of file Vector_2.h.
 : RVector_2(x,y) {}
Vector_2 (const RT & x, const RT & y, const RT & w) inline
Definition at line 102 of file Vector_2.h.
 : RVector_2(x,y,w) {}
Vector_2 (const CGAL::Point_2< R > & p) inline private
Definition at line 201 of file Vector_2.h.
 : RVector_2(p) {}
Vector_2 (const CGAL::Direction_2< R > & d) inline private
Definition at line 203 of file Vector_2.h.
 : RVector_2(d) {}
Member Function Documentation
FT cartesian (int i) const inline
Definition at line 143 of file Vector_2.h.
Referenced by Vector_2< T >::operator[]().
   { return RVector_2::cartesian(i); }
int dimension () const inline
Definition at line 151 of file Vector_2.h.
   { return 2; }
CGAL::Direction_2<R> direction () const inline
Definition at line 189 of file Vector_2.h.
   { return RVector_2::direction(); }
RT homogeneous (int i) const inline
Definition at line 139 of file Vector_2.h.
   { return RVector_2::homogeneous(i); }
RT hw () const inline
Definition at line 130 of file Vector_2.h.
   { return RVector_2::hw(); }
RT hx () const inline
Definition at line 122 of file Vector_2.h.
   { return RVector_2::hx(); }
RT hy () const inline
Definition at line 126 of file Vector_2.h.
   { return RVector_2::hy(); }
bool is_null () const inline
Definition at line 259 of file mapbasic.h.
 { return _x==0&&_y==0; }
Vector_2& neg () inline
Definition at line 246 of file mapbasic.h.
                   {
     _x = -_x; _y = -_y; return *this;
   }
Type norm () const inline
Definition at line 238 of file mapbasic.h.
 { return std::sqrt(*this * *this); }
Vector_2& normalize () inline
Definition at line 240 of file mapbasic.h.
{
     Type s=squared_norm();
     if ( s != Type(0)) { s=std::sqrt(s); _x/=s; _y/=s; }
     return *this;
   }
bool operator!= (const CGAL::Vector_2< R > & v) const inline
Definition at line 110 of file Vector_2.h.
   { return !(*this == v); }
bool operator!= (const Null_vector & v) const inline
Definition at line 118 of file Vector_2.h.
   { return !(*this == v); }
bool operator!= (const Vector_2< Type > & p) const inline
Definition at line 253 of file mapbasic.h.
   { return x()!=p.x() || y()!=p.y(); }
FT operator* (const CGAL::Vector_2< R > & w) const inline
Definition at line 167 of file Vector_2.h.
   { return (const RVector_2&)(*this) * (const RVector_2&)(w); }
CGAL::Vector_2<R> operator* (const RT & c) const inline
Definition at line 172 of file Vector_2.h.
   { return c * (const RVector_2&)(*this); }
CGAL::Vector_2<R> operator* (const Quotient< RT > & q) const inline
Definition at line 176 of file Vector_2.h.
   { return (q.numerator() * (const RVector_2&)(*this)) / q.denominator(); }
Vector_2 operator* (const Type t) const inline
Definition at line 226 of file mapbasic.h.
   { return Vector_2(_x*t, _y*t); }
Type operator* (const Vector_2< Type > & v) const inline
Definition at line 230 of file mapbasic.h.
   { return _x*v._x + _y*v._y; }
Vector_2& operator*= (const Type t) inline
Definition at line 216 of file mapbasic.h.
   { _x*=t; _y*=t; return *this; }
CGAL::Vector_2<R> operator+ (const CGAL::Vector_2< R > & w) const inline
Definition at line 155 of file Vector_2.h.
   { return (const RVector_2&)(*this) + (const RVector_2&)(w); }
Vector_2 operator+ (const Vector_2< Type > & v) const inline
Arithmatic operators.
Definition at line 222 of file mapbasic.h.
   { return Vector_2(_x+v._x, _y+v._y); }
Vector_2& operator+= (const Vector_2< Type > & v) inline
Assign operators.
Definition at line 212 of file mapbasic.h.
   { _x+=v._x; _y+=v._y; return *this; }
CGAL::Vector_2<R> operator- (const CGAL::Vector_2< R > & w) const inline
Definition at line 159 of file Vector_2.h.
   { return (const RVector_2&)(*this) - (const RVector_2&)(w); }
CGAL::Vector_2<R> operator- () const inline
Definition at line 163 of file Vector_2.h.
   { return RVector_2::operator-(); }
Vector_2 operator- (const Vector_2< Type > & v) const inline
Definition at line 224 of file mapbasic.h.
   { return Vector_2(_x-v._x, _y-v._y); }
Vector_2 operator- () const inline
Definition at line 233 of file mapbasic.h.
   { return Vector_2(-_x, -_y); }
Vector_2& operator-= (const Vector_2< Type > & v) inline
Definition at line 214 of file mapbasic.h.
   { _x-=v._x; _y-=v._y; return *this; }
CGAL::Vector_2<R> operator/ (const Quotient< RT > & q) const inline
Definition at line 180 of file Vector_2.h.
   { return (q.denominator() * (const RVector_2&)(*this)) / q.numerator(); }
CGAL::Vector_2<R> operator/ (const RT & c) const inline
Definition at line 185 of file Vector_2.h.
   { return (const RVector_2&)(*this) / c; }
Vector_2 operator/ (const Type t) const inline
Definition at line 228 of file mapbasic.h.
   { return Vector_2(_x/t, _y/t); }
Vector_2& operator/= (const Type t) inline
Definition at line 218 of file mapbasic.h.
   { _x/=t; _y/=t; return *this; }
bool operator< (const Vector_2< Type > & v) const inline
Definition at line 256 of file mapbasic.h.
Referenced by Point_2< R >::operator<().
   { return _x<v._x || _x==v._x && _y<v._y; }
bool operator== (const CGAL::Vector_2< R > & v) const inline
Definition at line 106 of file Vector_2.h.
   { return RVector_2::operator==(v); }
bool operator== (const Null_vector & v) const inline
Definition at line 114 of file Vector_2.h.
   { return RVector_2::operator==(v); }
bool operator== (const Vector_2< Type > & p) const inline
Definition at line 250 of file mapbasic.h.
   { return x()==p.x() && y()==p.y(); }
FT operator[] (int i) const inline
Definition at line 147 of file Vector_2.h.
   { return cartesian(i); }
Type& operator[] (const int i) inline
Definition at line 205 of file mapbasic.h.
 { return i==0?_x:_y; }
const Type& operator[] (const int & i) const inline
Definition at line 206 of file mapbasic.h.
 { return i==0?_x:_y; }
CGAL::Vector_2<R> perpendicular (const Orientation & o) const inline
Definition at line 193 of file Vector_2.h.
   { return RVector_2::perpendicular(o); }
Type squared_norm () const inline
Definition at line 236 of file mapbasic.h.
Referenced by FaceOffset_3::eval_angle(), and Vector_2< T >::normalize().
 { return *this * *this; }
CGAL::Vector_2<R> transform (const CGAL::Aff_transformation_2< R > & t) const inline
Definition at line 197 of file Vector_2.h.
   { return RVector_2::transform(t); }
FT x () const inline
Definition at line 133 of file Vector_2.h.
   { return RVector_2::x(); }
Type x () const inline
Definition at line 208 of file mapbasic.h.
Referenced by Segment_2_Segment_2_pair< R >::intersection_type(), Vector_2< T >::operator!=(), Point_2< R >::operator+(), Point_2< R >::operator+=(), Point_2< R >::operator-(), Point_2< R >::operator-=(), operator<<(), and Vector_2< T >::operator==().
 { return _x; }
FT y () const inline
Definition at line 136 of file Vector_2.h.
   { return RVector_2::y(); }
Type y () const inline
Definition at line 209 of file mapbasic.h.
Referenced by Segment_2_Segment_2_pair< R >::intersection_type(), Vector_2< T >::operator!=(), Point_2< R >::operator+(), Point_2< R >::operator+=(), Point_2< R >::operator-(), Point_2< R >::operator-=(), and Vector_2< T >::operator==().
 { return _y; }
Friends And Related Function Documentation
CGAL_FRIEND_INLINE CGAL::Vector_2<R> CGAL_SCOPE point_to_vector_conversion CGAL_NULL_TMPL_ARGS (const CGAL::Point_2< R > & p) friend
Member Data Documentation
Type _x protected
Definition at line 262 of file mapbasic.h.
Referenced by Vector_2< T >::is_null(), Vector_2< T >::neg(), Vector_2< T >::normalize(), Vector_2< T >::operator*(), Vector_2< T >::operator*=(), Vector_2< T >::operator+(), Vector_2< T >::operator+=(), Vector_2< T >::operator-(), Vector_2< T >::operator-=(), Vector_2< T >::operator/(), Vector_2< T >::operator/=(), Vector_2< T >::operator<(), Vector_2< T >::operator[](), and Vector_2< T >::x().
Type _y protected
Definition at line 262 of file mapbasic.h.
Referenced by Vector_2< T >::is_null(), Vector_2< T >::neg(), Vector_2< T >::normalize(), Vector_2< T >::operator*(), Vector_2< T >::operator*=(), Vector_2< T >::operator+(), Vector_2< T >::operator+=(), Vector_2< T >::operator-(), Vector_2< T >::operator-=(), Vector_2< T >::operator/(), Vector_2< T >::operator/=(), Vector_2< T >::operator<(), Vector_2< T >::operator[](), and Vector_2< T >::y().
The documentation for this class was generated from the following files:
mapbasic.h
Vector_2.h