Rocstar: QualityAssessor Class Reference
QualityAssessor Class Reference
A QualityAssessor instance can be inserted into an InstructionQueue to calculate and summarize registered QualityMetrics for the mesh.
#include <QualityAssessor.hpp>
Classes
class Assessor
Per-metric QualityAssessor data.
Public Types
enum QAFunction {
NO_FUNCTION = 0, AVERAGE =1, HISTOGRAM =2, MAXIMUM =4,
MINIMUM =8, RMS =16, STDDEV =32, ALL_MEASURES =255,
NO_FUNCTION = 0, AVERAGE =1, HISTOGRAM =2, MAXIMUM =4,
MINIMUM =8, RMS =16, STDDEV =32, ALL_MEASURES =255
}
enum QAFunction {
NO_FUNCTION = 0, AVERAGE =1, HISTOGRAM =2, MAXIMUM =4,
MINIMUM =8, RMS =16, STDDEV =32, ALL_MEASURES =255,
NO_FUNCTION = 0, AVERAGE =1, HISTOGRAM =2, MAXIMUM =4,
MINIMUM =8, RMS =16, STDDEV =32, ALL_MEASURES =255
}
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Public Member Functions
QualityAssessor (msq_std::string name="QualityAssessor")
Constructor - output to std::cout.
QualityAssessor (msq_stdio::ostream &output_stream, msq_std::string name="QualityAssessor")
Constructor - specified output stream.
QualityAssessor (QualityMetric *metric, QAFunction function, msq_stdio::ostream &output_stream, MsqError &err, msq_std::string name="QualityAssessor")
Constructor - initial stopping assessement and specified output stream.
QualityAssessor (QualityMetric *metric, QAFunction function, MsqError &err, msq_std::string name="QualityAssessor")
Constructor - initial stopping assessement.
~QualityAssessor ()
Destructor.
void set_name (msq_std::string name)
Provides a name to the QualityAssessor (use it for default name in constructor).
virtual msq_std::string get_name ()
Retrieves the QualityAssessor name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void add_quality_assessment (QualityMetric *qm, int function_flags, MsqError &err)
Adds a quality metric and a wrapper function (min, max, ...).
void set_stopping_assessment (QualityMetric *qm, QAFunction func, MsqError &err)
void add_histogram_assessment (QualityMetric *qm, double min, double max, int intervals, MsqError &err)
Add a quality metric for which the histogram is to be calculated, and set histogram parameters.
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
Does one sweep over the mesh and assess the quality with the metrics previously added.
void disable_printing_results ()
Do not print results of assessment.
void print_summary (msq_stdio::ostream &stream) const
Print accumulated summary data to specified stream.
bool invalid_elements () const
True if any metric evaluated to an invalid value for any element.
void reset_data ()
Reset calculated data.
const Assessor * get_results (QualityMetric *metric) const
Request summary data for a specific QualityMetric This method allows the application to request the summary data for a metric it has registered with the QualityAssessor.
const msq_std::list< Assessor > & get_all_results () const
Get list of all summary data.
QualityAssessor (msq_std::string name="QualityAssessor")
Constructor - output to std::cout.
QualityAssessor (msq_stdio::ostream &output_stream, msq_std::string name="QualityAssessor")
Constructor - specified output stream.
QualityAssessor (QualityMetric *metric, QAFunction function, msq_stdio::ostream &output_stream, MsqError &err, msq_std::string name="QualityAssessor")
Constructor - initial stopping assessement and specified output stream.
QualityAssessor (QualityMetric *metric, QAFunction function, MsqError &err, msq_std::string name="QualityAssessor")
Constructor - initial stopping assessement.
~QualityAssessor ()
Destructor.
void set_name (msq_std::string name)
Provides a name to the QualityAssessor (use it for default name in constructor).
virtual msq_std::string get_name ()
Retrieves the QualityAssessor name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void add_quality_assessment (QualityMetric *qm, int function_flags, MsqError &err)
Adds a quality metric and a wrapper function (min, max, ...).
void set_stopping_assessment (QualityMetric *qm, QAFunction func, MsqError &err)
void add_histogram_assessment (QualityMetric *qm, double min, double max, int intervals, MsqError &err)
Add a quality metric for which the histogram is to be calculated, and set histogram parameters.
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
Does one sweep over the mesh and assess the quality with the metrics previously added.
void disable_printing_results ()
Do not print results of assessment.
void print_summary (msq_stdio::ostream &stream) const
Print accumulated summary data to specified stream.
bool invalid_elements () const
True if any metric evaluated to an invalid value for any element.
void reset_data ()
Reset calculated data.
const Assessor * get_results (QualityMetric *metric) const
Request summary data for a specific QualityMetric This method allows the application to request the summary data for a metric it has registered with the QualityAssessor.
const msq_std::list< Assessor > & get_all_results () const
Get list of all summary data.
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Static Public Member Functions
static msq_std::string get_QAFunction_name (enum QualityAssessor::QAFunction)
static msq_std::string get_QAFunction_name (enum QualityAssessor::QAFunction)
Private Member Functions
msq_std::list< Assessor >::iterator find_or_add (QualityMetric *qm)
Find an Assessor corresponding to the passed QualityMetric, or create it if is not found in the list.
msq_std::list< Assessor >::iterator find_or_add (QualityMetric *qm)
Find an Assessor corresponding to the passed QualityMetric, or create it if is not found in the list.
Private Attributes
msq_std::string qualityAssessorName
Name.
msq_std::list< Assessor > assessList
List of quality metrics and corresponding data.
msq_stdio::ostream & outputStream
Stream to which to write summary of metric data.
bool printSummary
Disable printing.
msq_std::list< Assessor >::iterator stoppingMetric
Metric in assessList to use as return value for loop_over_mesh.
QAFunction stoppingFunction
Value to use as return value for loop_over_mesh.
Additional Inherited Members
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Detailed Description
A QualityAssessor instance can be inserted into an InstructionQueue to calculate and summarize registered QualityMetrics for the mesh.
The relevant quality assessments are set by the user or automatically (default) by Mesquite when an InstructionQueue object is used. If the mesh has been changed (improved), it is often useful to reuse the same QualityAssessor object to reassess the mesh quality.
The QAFunction flags passed for each metric control the output for that metric. If no QAFuction flags are passed, no results are printed for the metric except the count of invalid vertices/elements reported by that metric, if any.
The "stopping assessor" and "stopping function", if set, determinte the value reported to Mesquite for the overall run of of the QualityAssessor.
All summary data except the histogram is accumulated for all registered metrics, and can be accessed by the calling application. Histogram data is accumulated only if the HISTOGRAM QUFunction output is requested for the metric (which is impled by calling add_histogram_assessment.
Definition at line 97 of file includeLinks/QualityAssessor.hpp.
Member Enumeration Documentation
enum QAFunction
type of function used in conjunction with QualityMetric to compute mesh quality
Enumerator
NO_FUNCTION
AVERAGE
HISTOGRAM
MAXIMUM
MINIMUM
RMS
STDDEV
ALL_MEASURES
NO_FUNCTION
AVERAGE
HISTOGRAM
MAXIMUM
MINIMUM
RMS
STDDEV
ALL_MEASURES
Definition at line 104 of file includeLinks/QualityAssessor.hpp.
                     {
        NO_FUNCTION = 0,
        AVERAGE=1,
        HISTOGRAM=2,
        MAXIMUM=4,
        MINIMUM=8,
        RMS=16,
        STDDEV=32,
        ALL_MEASURES=255
     };
enum QAFunction
Enumerator
NO_FUNCTION
AVERAGE
HISTOGRAM
MAXIMUM
MINIMUM
RMS
STDDEV
ALL_MEASURES
NO_FUNCTION
AVERAGE
HISTOGRAM
MAXIMUM
MINIMUM
RMS
STDDEV
ALL_MEASURES
Definition at line 104 of file src/QualityAssessor/QualityAssessor.hpp.
                     {
        NO_FUNCTION = 0,
        AVERAGE=1,
        HISTOGRAM=2,
        MAXIMUM=4,
        MINIMUM=8,
        RMS=16,
        STDDEV=32,
        ALL_MEASURES=255
     };
Constructor & Destructor Documentation
QualityAssessor (msq_std::string name = "QualityAssessor")
Constructor - output to std::cout.
QualityAssessor (msq_stdio::ostream & output_stream, msq_std::string name = "QualityAssessor")
Constructor - specified output stream.
QualityAssessor (QualityMetric * metric, QAFunction function, msq_stdio::ostream & output_stream, MsqError & err, msq_std::string name = "QualityAssessor")
Constructor - initial stopping assessement and specified output stream.
QualityAssessor (QualityMetric * metric, QAFunction function, MsqError & err, msq_std::string name = "QualityAssessor")
Constructor - initial stopping assessement.
~QualityAssessor ()
Destructor.
Definition at line 117 of file QualityAssessor/QualityAssessor.cpp.
   { }
QualityAssessor (msq_std::string name = "QualityAssessor")
Constructor - output to std::cout.
QualityAssessor (msq_stdio::ostream & output_stream, msq_std::string name = "QualityAssessor")
Constructor - specified output stream.
QualityAssessor (QualityMetric * metric, QAFunction function, msq_stdio::ostream & output_stream, MsqError & err, msq_std::string name = "QualityAssessor")
Constructor - initial stopping assessement and specified output stream.
QualityAssessor (QualityMetric * metric, QAFunction function, MsqError & err, msq_std::string name = "QualityAssessor")
Constructor - initial stopping assessement.
~QualityAssessor ()
Destructor.
Member Function Documentation
void add_histogram_assessment (QualityMetric * qm, double min_val, double max_val, int intervals, MsqError & err)
Add a quality metric for which the histogram is to be calculated, and set histogram parameters.
Checks first to see if the QualityMetric, qm, has been added to this QualityAssessor, and if it has not, adds it. It then adds HISTOGRAM as a QAFunciton for that metric. It then sets the minimum and maximum values for the histogram.
Parameters
qm Pointer to the QualityMetric to be used in histogram.
min_val (double) Minimum range of histogram.
max_val (double) Maximum range of histogram.
intervals Number of histogram intervals
Definition at line 244 of file QualityAssessor/QualityAssessor.cpp.
References MSQ_SETERR.
 {
   if (min_val >= max_val || intervals < 1) {
     MSQ_SETERR(err)("Invalid histogram range.", MsqError::INVALID_ARG );
     return;
   }
   list<Assessor>::iterator assessor = find_or_add( qm );
   assessor->funcFlags |= QualityAssessor::HISTOGRAM;
   assessor->histMin = min_val;
   assessor->histMax = max_val;
   assessor->histogram.resize( intervals + 2 );
 }
void add_histogram_assessment (QualityMetric * qm, double min, double max, int intervals, MsqError & err)
Add a quality metric for which the histogram is to be calculated, and set histogram parameters.
void add_quality_assessment (QualityMetric * qm, int function_flags, MsqError & err)
Adds a quality metric and a wrapper function (min, max, ...).
void add_quality_assessment (QualityMetric * qm, int func, MsqError & err)
Adds a quality metric and a wrapper function (min, max, ...).
Several QualityMetric objects can be added to a single QualityAssessor object. This allows to perform several quality assessments over a single mesh sweep.
Parameters
qm is the QualityMetric that will be used to evaluate the mesh quality
func is the wrapper function used over the QualityMetric (min, max, etc..)
Definition at line 167 of file QualityAssessor/QualityAssessor.cpp.
References Mesquite::DEFAULT_HISTOGRAM_INTERVALS.
 {
   msq_std::list<Assessor>::iterator iter;
   iter = find_or_add( qm );
   iter->funcFlags |= func;
   if (func&HISTOGRAM)
     iter->histogram.resize(DEFAULT_HISTOGRAM_INTERVALS+2);
 }
void disable_printing_results () inline
Do not print results of assessment.
Definition at line 170 of file includeLinks/QualityAssessor.hpp.
References QualityAssessor::printSummary.
Referenced by ShapeImprovementWrapper::ShapeImprovementWrapper().
        {
          printSummary = false;
        }
void disable_printing_results () inline
Do not print results of assessment.
Definition at line 170 of file src/QualityAssessor/QualityAssessor.hpp.
References QualityAssessor::printSummary.
        {
          printSummary = false;
        }
list< QualityAssessor::Assessor >::iterator find_or_add (QualityMetric * qm) private
Find an Assessor corresponding to the passed QualityMetric, or create it if is not found in the list.
Definition at line 179 of file QualityAssessor/QualityAssessor.cpp.
References QualityMetric::get_metric_type().
 {
   list<Assessor>::iterator iter;
     // If metric is already in list, find it
   for (iter = assessList.begin(); iter != assessList.end(); ++iter)
     if (iter->qualMetric == qm )
       break;
     // If metric not found in list, add it
   if (iter == assessList.end())
   {
     if (qm->get_metric_type() == QualityMetric::VERTEX_BASED)
     {
       assessList.push_back( Assessor(qm) );
       iter = --assessList.end();
     }
     else
     {
       assessList.push_front( Assessor(qm) );
       iter = assessList.begin();
     }
   }
   return iter;
 }
msq_std::list<Assessor>::iterator find_or_add (QualityMetric * qm) private
Find an Assessor corresponding to the passed QualityMetric, or create it if is not found in the list.
virtual AlgorithmType get_algorithm_type () inline virtual
Return the algorithm type (to avoid RTTI use).
Implements PatchDataUser.
Definition at line 144 of file includeLinks/QualityAssessor.hpp.
References PatchDataUser::QUALITY_ASSESSOR.
 { return QUALITY_ASSESSOR; }
virtual AlgorithmType get_algorithm_type () inline virtual
Return the algorithm type (to avoid RTTI use).
Implements PatchDataUser.
Definition at line 144 of file src/QualityAssessor/QualityAssessor.hpp.
References PatchDataUser::QUALITY_ASSESSOR.
 { return QUALITY_ASSESSOR; }
const msq_std::list<Assessor>& get_all_results () const inline
Get list of all summary data.
Return a const reference to the internal list of calculated data.
Definition at line 288 of file includeLinks/QualityAssessor.hpp.
References QualityAssessor::assessList.
       { return assessList; }
const msq_std::list<Assessor>& get_all_results () const inline
Get list of all summary data.
Return a const reference to the internal list of calculated data.
Definition at line 288 of file src/QualityAssessor/QualityAssessor.hpp.
References QualityAssessor::assessList.
       { return assessList; }
virtual msq_std::string get_name () inline virtual
Retrieves the QualityAssessor name. A default name should be set in the constructor.
Implements PatchDataUser.
Definition at line 142 of file src/QualityAssessor/QualityAssessor.hpp.
References QualityAssessor::qualityAssessorName.
 { return qualityAssessorName; }
virtual msq_std::string get_name () inline virtual
Retrieves the QualityAssessor name. A default name should be set in the constructor.
Implements PatchDataUser.
Definition at line 142 of file includeLinks/QualityAssessor.hpp.
References QualityAssessor::qualityAssessorName.
 { return qualityAssessorName; }
static msq_std::string get_QAFunction_name (enum QualityAssessor::QAFunction) static
string get_QAFunction_name (enum QualityAssessor::QAFunction fun) static
Definition at line 120 of file QualityAssessor/QualityAssessor.cpp.
References MAXIMUM.
 {
   switch(fun){
     case(AVERAGE):
       return "Average   ";
     case(HISTOGRAM):
       return "Histogram of metric values: ";
     case(MAXIMUM):
       return "Maximum   ";
     case(MINIMUM):
       return "Minimum   ";
     case(RMS):
       return "RMS       ";
     case(STDDEV):
       return "Stan. Dev.";
     default:
       return "DEFAULT   ";
   };
 }
const Assessor* get_results (QualityMetric * metric) const
Request summary data for a specific QualityMetric This method allows the application to request the summary data for a metric it has registered with the QualityAssessor.
If the passed QualityMetric has not been registered with the QualityAssessor instance, NULL is returned.
const QualityAssessor::Assessor * get_results (QualityMetric * metric) const
Request summary data for a specific QualityMetric This method allows the application to request the summary data for a metric it has registered with the QualityAssessor.
If the passed QualityMetric has not been registered with the QualityAssessor instance, NULL is returned.
Definition at line 518 of file QualityAssessor/QualityAssessor.cpp.
References QualityAssessor::assessList.
 {
   msq_std::list<Assessor>::const_iterator iter;
   for (iter = assessList.begin(); iter != assessList.end(); ++iter)
     if (iter->get_metric() == metric)
       return &*iter;
   return 0;
 }
bool invalid_elements () const
True if any metric evaluated to an invalid value for any element.
Definition at line 491 of file QualityAssessor/QualityAssessor.cpp.
 {
   bool result = false;
   msq_std::list<Assessor>::const_iterator iter;
   for (iter = assessList.begin(); iter != assessList.end(); ++iter)
     if (iter->get_invalid_element_count())
       result = true;
   return result;
 }
bool invalid_elements () const
True if any metric evaluated to an invalid value for any element.
double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
Does one sweep over the mesh and assess the quality with the metrics previously added.
Computes the quality data for a given MeshSet, ms. What quality information is calculated, depends on what has been requested through the use of the QualityAssessor constructor, add_quality_assessment(), and set_stopping_assessment(). The resulting data is printed in a table unless disable_printing_results() has been called. The double returned depends on the QualityMetric and QAFunction "return" combination, which can be set using set_stopping_assessemnt().
Parameters
ms (const MeshSet &) MeshSet used for quality assessment.
Implements PatchDataUser.
Definition at line 275 of file QualityAssessor/QualityAssessor.cpp.
References PatchData::element_by_index(), MeshSet::get_next_patch(), i, MAXIMUM, MSQ_ERRZERO, MSQ_SETERR, PatchData::num_elements(), PatchData::num_vertices(), and PatchData::vertex_by_index().
Referenced by ShapeImprovementWrapper::run_instructions().
 {
     // Clear out any previous data
   reset_data();
     // Check for any metrics for which a histogram is to be
     // calculated and for which the user has not specified
     // minimum and maximum values.
     // Element-based metrics are first in list, followed
     // by vertex-based metrics.  Find first vertex-based
     // metric also such that element metrics go from
     // assessList.begin() to elem_end and vertex metrics
     // go from elem_end to assessList.end()
   list<Assessor>::iterator elem_end = assessList.end();
   bool need_second_pass_for_elements = false;
   bool need_second_pass_for_vertices = false;
   list<Assessor>::iterator iter;
   for (iter = assessList.begin(); iter != assessList.end(); ++iter)
   {
     if (iter->get_metric()->get_metric_type() == QualityMetric::VERTEX_BASED)
       break;
     if (iter->funcFlags&HISTOGRAM && !iter->haveHistRange)
       need_second_pass_for_elements = true;
   }
   elem_end = iter;
   for ( ; iter != assessList.end(); ++iter)
   {
     if (iter->funcFlags&HISTOGRAM && !iter->haveHistRange)
       need_second_pass_for_vertices = true;
   }
   list<Assessor> histogramList;
     // Do element-based metrics
   if (assessList.begin() != elem_end)
   {
     bool first_pass = false;
     do { // might need to loop twice to calculate histograms
       first_pass = !first_pass;
       PatchData* pd;
       PatchData local_patch;
       no_culling_method();
       bool more_mesh = true;
       if (get_global_patch() == 0) {
         pd = &local_patch;
         more_mesh=ms.get_next_patch(*pd, this, err);  MSQ_ERRZERO(err);
       }
       else {
         pd = get_global_patch();
       }
         //until there are no more patches
         //there is another get_next_patch at
         //the end of this loop
       while (more_mesh)
       {
         for (unsigned i = 0; i < pd->num_elements(); ++i)
         {
           for (iter = assessList.begin(); iter != elem_end; ++iter)
           {
               // If first pass, get values for all metrics
             if (first_pass)
             {
               double value;
               bool valid = iter->get_metric()->evaluate_element( *pd,
                                                            &pd->element_by_index(i),
                                                            value, err );
                                                            MSQ_ERRZERO(err);
               iter->add_value(value);
               if (!valid)
                 iter->add_invalid_value();
             }
               // If second pass, only do metrics for which the
               // histogram hasn't been calculated yet.
             else if (iter->funcFlags&HISTOGRAM && !iter->haveHistRange)
             {
               double value;
               iter->get_metric()->evaluate_element( *pd,
                                                     &pd->element_by_index(i),
                                                     value, err );
                                                     MSQ_ERRZERO(err);
               iter->add_hist_value(value);
             }
           }
         }
            // If dealing with local patches, get next element group (PatchData object)
         if (get_patch_type() != PatchData::GLOBAL_PATCH)
           more_mesh = ms.get_next_patch(*pd,this, err); MSQ_ERRZERO(err);
           //Michael:: Since we are doing global right now:
           //Remove this when no longer doing global
         more_mesh=false;
       }
         // Fix up any histogram ranges which were calculated
       for (iter = assessList.begin(); iter != elem_end; ++iter)
         if (iter->funcFlags&HISTOGRAM && !iter->haveHistRange)
           if (first_pass)
             iter->calculate_histogram_range();
 // Uncomment the following to have the QA keep the first
 // calculated histogram range for all subsequent iterations.
 //          else
 //            iter->haveHistRange = true;
     } while (first_pass && need_second_pass_for_elements);
   }
       // Do vertex-based metrics
   if (assessList.end() != elem_end)
   {
     bool first_pass = false;
     do { // might need to loop twice to calculate histograms
       first_pass = !first_pass;
         //construct the patch we will send to get_next_patch
       PatchData* pd;
       PatchData local_patch;
       no_culling_method();
       bool more_mesh = true;
       if (get_global_patch() == 0) {
         pd = &local_patch;
         more_mesh=ms.get_next_patch(*pd, this, err);  MSQ_ERRZERO(err);
       }
       else {
         pd = get_global_patch();
       }
         //until there are no more patches
         //there is another get_next_patch at
         //the end of this loop
       while (more_mesh)
       {
         for (unsigned i = 0; i < pd->num_vertices(); ++i)
         {
           for (iter = elem_end; iter != assessList.end(); ++iter)
           {
               // If first pass, get values for all metrics
             if (first_pass)
             {
               double value;
               bool valid = iter->get_metric()->evaluate_vertex( *pd,
                                                            &pd->vertex_by_index(i),
                                                            value, err );
                                                            MSQ_ERRZERO(err);
               iter->add_value(value);
               if (!valid)
                 iter->add_invalid_value();
             }
               // If second pass, only do metrics for which the
               // histogram hasn't been calculated yet.
             else if (iter->funcFlags&HISTOGRAM && !iter->haveHistRange)
             {
               double value;
               iter->get_metric()->evaluate_vertex( *pd,
                                                    &pd->vertex_by_index(i),
                                                    value, err );
                                                    MSQ_ERRZERO(err);
               iter->add_hist_value(value);
             }
           }
         }
         if (get_patch_type() != PatchData::GLOBAL_PATCH)
           more_mesh = ms.get_next_patch(*pd,this, err); MSQ_ERRZERO(err);
           //Michael:: Since we are doing global right now:
           //Remove this when no longer doing global
         more_mesh=false;
       }
         // Fix up any histogram ranges which were calculated
       for (iter = elem_end; iter != assessList.end(); ++iter)
         if (iter->funcFlags&HISTOGRAM && !iter->haveHistRange)
           if (first_pass)
             iter->calculate_histogram_range();
 // Uncomment the following to have the QA keep the first
 // calculated histogram range for all subsequent iterations.
 //          else
 //            iter->haveHistRange = true;
     } while (first_pass && need_second_pass_for_vertices);
   }
     // Print results, if requested
   if (printSummary)
     print_summary( this->outputStream );
     // If no stopping function, just return zero
   if (!stoppingFunction)
     return 0.0;
     // Otherwise return requested value
   if      (stoppingFunction & STDDEV)
     return stoppingMetric->get_stddev();
   else if (stoppingFunction & AVERAGE)
     return stoppingMetric->get_average();
   else if (stoppingFunction & MAXIMUM)
     return stoppingMetric->get_maximum();
   else if (stoppingFunction & MINIMUM)
     return stoppingMetric->get_minimum();
   else if (stoppingFunction & RMS)
     return stoppingMetric->get_rms();
   else
     MSQ_SETERR(err)("Invalid stopping function for QualityAssessor",
                     MsqError::INVALID_STATE);
   return 0.0;
 }
virtual double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
Does one sweep over the mesh and assess the quality with the metrics previously added.
Implements PatchDataUser.
void print_summary (msq_stdio::ostream & stream) const
Print accumulated summary data to specified stream.
Definition at line 626 of file QualityAssessor/QualityAssessor.cpp.
References QualityAssessor::assessList, QualityAssessor::AVERAGE, QualityAssessor::HISTOGRAM, QualityAssessor::MAXIMUM, QualityAssessor::MINIMUM, QualityAssessor::qualityAssessorName, QualityAssessor::RMS, and QualityAssessor::STDDEV.
 {
   const int NAMEW = 19;  // Width of name column in table output
   const int NUMW = 12;   // Width of value columns in table output
     // Print title
   stream << msq_stdio::endl
          << "************** "
          << qualityAssessorName
          << " Summary **************"
          << msq_stdio::endl
          << msq_stdio::endl;
     // Get union of function flags, and list any metrics with invalid values
   msq_std::list<Assessor>::const_iterator iter;
   unsigned flags = 0;
   int invalid_count = 0;
   for (iter = assessList.begin(); iter != assessList.end(); ++iter)
   {
     flags |= (iter->funcFlags & ~HISTOGRAM);
     if (iter->get_invalid_element_count())
     {
       ++invalid_count;
       stream << "  " << iter->get_invalid_element_count()
              << " OF " << iter->get_count()
              << " VALUES ARE INVALID FOR "
              << iter->get_metric()->get_name()
              << msq_stdio::endl << msq_stdio::endl;
     }
   }
   if (0 == invalid_count) {
     stream << "  No invalid values for any metric."
            << msq_stdio::endl << msq_stdio::endl;
   }
     // If printing any values
   if (flags)
   {
       // Print table header line
     stream << msq_stdio::setw(NAMEW) << "metric";
     if (flags & MINIMUM)
       stream << msq_stdio::setw(NUMW) << "minimum";
     if (flags & AVERAGE)
       stream << msq_stdio::setw(NUMW) << "average";
     if (flags & RMS)
       stream << msq_stdio::setw(NUMW) << "rms";
     if (flags & MAXIMUM)
       stream << msq_stdio::setw(NUMW) << "maximum";
     if (flags & STDDEV)
       stream << msq_stdio::setw(NUMW) << "std.dev.";
     stream << msq_stdio::endl;
       // Print out values for each assessor
     for (iter = assessList.begin(); iter != assessList.end(); ++iter)
     {
         // If no output (other than histogram) for this metric, skip it
       if (!(iter->funcFlags & ~HISTOGRAM))
         continue;
         // Name column
       stream << msq_stdio::setw(NAMEW) << iter->get_metric()->get_name();
         // Value columns
       if (flags & MINIMUM)
       {
         if (iter->funcFlags & MINIMUM)
           stream << msq_stdio::setw(NUMW) << iter->get_minimum();
         else
           stream << msq_stdio::setw(NUMW) << " ";
       }
       if (flags & AVERAGE)
       {
         if (iter->funcFlags & AVERAGE)
           stream << msq_stdio::setw(NUMW) << iter->get_average();
         else
           stream << msq_stdio::setw(NUMW) << " ";
       }
       if (flags & RMS)
       {
         if (iter->funcFlags & RMS)
           stream << msq_stdio::setw(NUMW) << iter->get_rms();
         else
           stream << msq_stdio::setw(NUMW) << " ";
       }
       if (flags & MAXIMUM)
       {
         if (iter->funcFlags & MAXIMUM)
           stream << msq_stdio::setw(NUMW) << iter->get_maximum();
         else
           stream << msq_stdio::setw(NUMW) << " ";
       }
       if (flags & STDDEV)
       {
         if (iter->funcFlags & STDDEV)
           stream << msq_stdio::setw(NUMW) << iter->get_stddev();
         else
           stream << msq_stdio::setw(NUMW) << " ";
       }
       stream << msq_stdio::endl;
     } // for (assessList)
   } // if (flags)
   for (iter = assessList.begin(); iter != assessList.end(); ++iter)
     if (iter->funcFlags & HISTOGRAM)
       iter->print_histogram( stream );
 }
void print_summary (msq_stdio::ostream & stream) const
Print accumulated summary data to specified stream.
void reset_data ()
Reset calculated data.
Definition at line 501 of file QualityAssessor/QualityAssessor.cpp.
 {
   msq_std::list<Assessor>::iterator iter;
   for (iter = assessList.begin(); iter != assessList.end(); ++iter)
     iter->reset_data();
 }
void reset_data ()
Reset calculated data.
void set_name (msq_std::string name) inline
Provides a name to the QualityAssessor (use it for default name in constructor).
Definition at line 140 of file src/QualityAssessor/QualityAssessor.hpp.
References QualityAssessor::qualityAssessorName.
 { qualityAssessorName = name; };
void set_name (msq_std::string name) inline
Provides a name to the QualityAssessor (use it for default name in constructor).
Definition at line 140 of file includeLinks/QualityAssessor.hpp.
References QualityAssessor::qualityAssessorName.
 { qualityAssessorName = name; };
void set_stopping_assessment (QualityMetric * qm, QAFunction func, MsqError & err)
Sets the QualityMetric and QAFunction combination that will be returned when loop_over_mesh is called.
Sets which QualityMetric and QAFunction combination is used to determine the value return from assess_mesh_quality(). It first ensures that the inputed QAFunction was not HISTOGRAM. It then calls add_quality_assessment with the given QualityMetric and QAFunction, to ensure that this combination will be computed. Finally, it sets the stoppingMetric pointer and the stoppingFunction data members.
Parameters
qm Pointer to QualityMetric.
func (QAFUNCTION) Wrapper function for qm (e.g. MINIMUM, MAXIMUM,...).
Definition at line 216 of file QualityAssessor/QualityAssessor.cpp.
References MSQ_SETERR.
 {
   if(func==HISTOGRAM){
     MSQ_SETERR(err)("HISTOGRAM DOES NOT GIVE A VALID RETURN VALUE", MsqError::INVALID_ARG);
     return;
   }
   else if (func == NO_FUNCTION) {
     MSQ_SETERR(err)("No function specified for stopping assessment", MsqError::INVALID_ARG);
     return;
   }
   stoppingMetric = find_or_add( qm );
   stoppingFunction = func;
 }
void set_stopping_assessment (QualityMetric * qm, QAFunction func, MsqError & err)
Sets the QualityMetric and QAFunction combination that will be returned when loop_over_mesh is called.
Member Data Documentation
msq_std::list< Assessor > assessList private
List of quality metrics and corresponding data.
Definition at line 303 of file includeLinks/QualityAssessor.hpp.
Referenced by QualityAssessor::get_all_results(), QualityAssessor::get_results(), and QualityAssessor::print_summary().
msq_stdio::ostream & outputStream private
Stream to which to write summary of metric data.
Definition at line 306 of file includeLinks/QualityAssessor.hpp.
bool printSummary private
Disable printing.
Definition at line 308 of file includeLinks/QualityAssessor.hpp.
Referenced by QualityAssessor::disable_printing_results().
msq_std::string qualityAssessorName private
Name.
Definition at line 300 of file includeLinks/QualityAssessor.hpp.
Referenced by QualityAssessor::get_name(), QualityAssessor::print_summary(), and QualityAssessor::set_name().
QAFunction stoppingFunction private
Value to use as return value for loop_over_mesh.
Definition at line 313 of file includeLinks/QualityAssessor.hpp.
msq_std::list< Assessor >::iterator stoppingMetric private
Metric in assessList to use as return value for loop_over_mesh.
Definition at line 311 of file includeLinks/QualityAssessor.hpp.
The documentation for this class was generated from the following files:
includeLinks/QualityAssessor.hpp
QualityAssessor/QualityAssessor.cpp