Rocstar: updatestructuralsoln Module Reference
updatestructuralsoln Module Reference
Public Member Functions
subroutine updatestructural (glb, NumProcs, Rnet)
subroutine updatestructuralht (glb, NumProcs, Rnet, RnetHT)
subroutine internalforce_v3d4 (glb, Rnet, ElemStart, ElemEnd, iAnalysisType)
subroutine internalforce_v3d4ht (glb, Rnet, ElemStart, ElemEnd, iAnalysisType, Temperature)
subroutine internalforce_v3d10 (glb, Rnet, ElemStart, ElemEnd, iAnalysisType)
subroutine internalforce_v3d8 (glb, Rnet, ElemStart, ElemEnd, iAnalysisType)
subroutine updatestructural (glb, NumProcs, Rnet)
subroutine updatestructuralht (glb, NumProcs, Rnet, RnetHT)
subroutine internalforce_v3d4 (glb, Rnet, ElemStart, ElemEnd, iAnalysisType)
subroutine internalforce_v3d4ht (glb, Rnet, ElemStart, ElemEnd, iAnalysisType, Temperature)
subroutine internalforce_v3d10 (glb, Rnet, ElemStart, ElemEnd, iAnalysisType)
subroutine internalforce_v3d8 (glb, Rnet, ElemStart, ElemEnd, iAnalysisType)
Detailed Description
Definition at line 54 of file UpdateStructuralSoln.f90.
Member Function/Subroutine Documentation
subroutine internalforce_v3d10 (type(rocfrac_global) glb, real*8, dimension(1:3*glb%numnp) Rnet, integer, intent(in) ElemStart, integer, intent(in) ElemEnd, integer, intent(in) iAnalysisType)
Definition at line 799 of file UpdateStructuralSoln.f90.
References Aff_transformation_repS2< FT >::print(), v3d10(), v3d10_b_bar(), v3d10_nl(), v3d10_nl_arruda_boyce(), v3d10_nl_arruda_boyce_damping(), v3d10_nl_damping(), v3d10_nl_huang(), v3d10_nl_matous(), and v3d10r_nl().
Referenced by updatestructural(), and updatestructuralht().
subroutine internalforce_v3d10 (type(rocfrac_global) glb, real*8, dimension(1:3*glb%numnp) Rnet, integer, intent(in) ElemStart, integer, intent(in) ElemEnd, integer, intent(in) iAnalysisType)
Definition at line 741 of file MP/Source/UpdateStructuralSoln.f90.
References Aff_transformation_repS2< FT >::print(), v3d10(), v3d10_b_bar(), v3d10_nl(), v3d10_nl_arruda_boyce(), v3d10_nl_arruda_boyce_damping(), v3d10_nl_damping(), v3d10_nl_huang(), v3d10_nl_matous(), and v3d10r_nl().
subroutine internalforce_v3d4 (type(rocfrac_global) glb, real*8, dimension(1:3*glb%numnp) Rnet, integer, intent(in) ElemStart, integer, intent(in) ElemEnd, integer, intent(in) iAnalysisType)
Definition at line 656 of file MP/Source/UpdateStructuralSoln.f90.
References v3d4(), v3d4_damping(), v3d4_neohookeanincompress(), v3d4_nl(), and v3d4_nl_arruda_boyce().
subroutine internalforce_v3d4 (type(rocfrac_global) glb, real*8, dimension(1:3*glb%numnp) Rnet, integer, intent(in) ElemStart, integer, intent(in) ElemEnd, integer, intent(in) iAnalysisType)
Definition at line 714 of file UpdateStructuralSoln.f90.
References v3d4(), v3d4_damping(), v3d4_neohookeanincompress(), v3d4_nl(), and v3d4_nl_arruda_boyce().
Referenced by updatestructural().
subroutine internalforce_v3d4ht (type(rocfrac_global) glb, real*8, dimension(1:3*glb%numnp) Rnet, integer, intent(in) ElemStart, integer, intent(in) ElemEnd, integer, intent(in) iAnalysisType, real*8, dimension(1:glb%numnp) Temperature)
Definition at line 697 of file MP/Source/UpdateStructuralSoln.f90.
References v3d4_damping(), v3d4_neohookeanincompress(), v3d4_nl(), v3d4_nl_arruda_boyce(), and v3d4_thermalexp2().
subroutine internalforce_v3d4ht (type(rocfrac_global) glb, real*8, dimension(1:3*glb%numnp) Rnet, integer, intent(in) ElemStart, integer, intent(in) ElemEnd, integer, intent(in) iAnalysisType, real*8, dimension(1:glb%numnp) Temperature)
Definition at line 755 of file UpdateStructuralSoln.f90.
References v3d4_damping(), v3d4_neohookeanincompress(), v3d4_nl(), v3d4_nl_arruda_boyce(), and v3d4_thermalexp2().
Referenced by updatestructuralht().
subroutine internalforce_v3d8 (type(rocfrac_global) glb, real*8, dimension(1:3*glb%numnp) Rnet, integer, intent(in) ElemStart, integer, intent(in) ElemEnd, integer, intent(in) iAnalysisType)
Definition at line 901 of file UpdateStructuralSoln.f90.
References v3d8_me().
Referenced by updatestructural().
subroutine internalforce_v3d8 (type(rocfrac_global) glb, real*8, dimension(1:3*glb%numnp) Rnet, integer, intent(in) ElemStart, integer, intent(in) ElemEnd, integer, intent(in) iAnalysisType)
Definition at line 842 of file MP/Source/UpdateStructuralSoln.f90.
References v3d8_me().
subroutine updatestructural (type(rocfrac_global) glb, integer NumProcs, real*8, dimension(1:3*glb%numnp) Rnet)
Definition at line 61 of file UpdateStructuralSoln.f90.
References c3d6nm(), internalforce_v3d10(), internalforce_v3d4(), internalforce_v3d8(), j, k, v3d10_ale(), and v3d4_ale().
Referenced by rocfracmain::rocfracsoln().
subroutine updatestructural (type(rocfrac_global) glb, integer NumProcs, real*8, dimension(1:3*glb%numnp) Rnet)
Definition at line 61 of file MP/Source/UpdateStructuralSoln.f90.
References c3d6nm(), internalforce_v3d10(), internalforce_v3d4(), internalforce_v3d8(), j, k, v3d10_ale(), and v3d4_ale().
subroutine updatestructuralht (type(rocfrac_global) glb, integer NumProcs, real*8, dimension(1:3*glb%numnp) Rnet, real*8, dimension(1:glb%numnp) RnetHT)
Definition at line 329 of file MP/Source/UpdateStructuralSoln.f90.
References i, internalforce_v3d10(), internalforce_v3d4ht(), j, k, v3d10_ale(), v3d10_thermal(), v3d10_thermalexp(), v3d4_ale(), and v3d4_thermal().
subroutine updatestructuralht (type(rocfrac_global) glb, integer NumProcs, real*8, dimension(1:3*glb%numnp) Rnet, real*8, dimension(1:glb%numnp) RnetHT)
Definition at line 324 of file UpdateStructuralSoln.f90.
References i, internalforce_v3d10(), internalforce_v3d4ht(), j, k, v3d10_ale(), v3d10_thermal(), v3d10_thermalexp(), v3d4_ale(), and v3d4_thermal().
Referenced by rocfracmain::rocfracsoln().
The documentation for this module was generated from the following files:
UpdateStructuralSoln.f90
MP/Source/UpdateStructuralSoln.f90