Rocstar: Rocmap Class Reference
Rocmap Class Reference
#include <Rocmap.h>
Public Member Functions
Rocmap ()
Static Public Member Functions
static void load (const std::string &mname)
Loads Rocmap onto Roccom with a given module name.
static void unload (const std::string &mname)
Unloads Rocmap from Roccom.
static void compute_pconn (const COM::Attribute *mesh, COM::Attribute *pconn)
Compute pane connectivity map between shared nodes.
static void pane_border_nodes (const COM::Attribute *mesh, COM::Attribute *isborder, int *ghost_level=NULL)
Determine the nodes at pane boundaries of a given mesh.
static void size_of_cpanes (const COM::Attribute *pconn, const int *pane_id, int *npanes_total, int *npanes_ghost=NULL)
Get the number of communicating panes.
static void reduce_average_on_shared_nodes (COM::Attribute *att, COM::Attribute *pconn=NULL)
Perform an average-reduction on the shared nodes for the given attribute.
static void reduce_maxabs_on_shared_nodes (COM::Attribute *att, COM::Attribute *pconn=NULL)
Perform a maxabs-reduction on the shared nodes for the given attribute.
static void reduce_minabs_on_shared_nodes (COM::Attribute *att, COM::Attribute *pconn=NULL)
Perform a minabs-reduction on the shared nodes for the given attribute.
static void update_ghosts (COM::Attribute *att, const COM::Attribute *pconn=NULL)
Update ghost nodal or elemental values for the given attribute.
Detailed Description
Definition at line 39 of file Rocmap.h.
Constructor & Destructor Documentation
Rocmap () inline
Definition at line 41 of file Rocmap.h.
 {}
Member Function Documentation
MAP_BEGIN_NAMESPACE void compute_pconn (const COM::Attribute * mesh, COM::Attribute * pconn) static
Compute pane connectivity map between shared nodes.
If pconn was not yet initialized, this routine will allocate memory for it. Otherwise, this routine will copy up to the capacity of the array
Definition at line 34 of file Rocmap.C.
References Pane_connectivity::compute_pconn().
Referenced by load().
{
   // Compute the pane connectivity from scratch
   Pane_connectivity pc( mesh, mesh->window()->get_communicator());
   pc.compute_pconn( pconn);
 }
void load (const std::string & mname) static
Loads Rocmap onto Roccom with a given module name.
Definition at line 102 of file Rocmap.C.
References COM_INT, COM_METADATA, COM_new_window(), COM_set_function(), COM_window_init_done(), compute_pconn(), pane_border_nodes(), reduce_average_on_shared_nodes(), reduce_maxabs_on_shared_nodes(), reduce_minabs_on_shared_nodes(), size_of_cpanes(), and update_ghosts().
Referenced by Rocmap_load_module(), rocmap_load_module(), ROCMAP_LOAD_MODULE(), rocmap_load_module_(), and ROCMAP_LOAD_MODULE_().
{
   COM_new_window( mname.c_str());
   COM_Type types[4];
   types[0] = COM_METADATA;
   types[1] = COM_METADATA;
   COM_set_function( (mname+".reduce_average_on_shared_nodes").c_str(),
                     (Func_ptr)reduce_average_on_shared_nodes, "iI", types);
   COM_set_function( (mname+".reduce_maxabs_on_shared_nodes").c_str(),
                     (Func_ptr)reduce_maxabs_on_shared_nodes, "iI", types);
   COM_set_function( (mname+".reduce_minabs_on_shared_nodes").c_str(),
                     (Func_ptr)reduce_minabs_on_shared_nodes, "iI", types);
   COM_set_function( (mname+".update_ghosts").c_str(),
                     (Func_ptr)update_ghosts, "iI", types);
   types[0] = types[1] = COM_METADATA;
   COM_set_function( (mname+".compute_pconn").c_str(),
                     (Func_ptr)compute_pconn, "io", types);
   types[0] = types[1] = COM_METADATA; types[2] = COM_INT;
   COM_set_function( (mname+".pane_border_nodes").c_str(),
                     (Func_ptr)pane_border_nodes, "ioI", types);
   types[0] = COM_METADATA;
   types[1] = types[2] = types[3] = COM_INT;
   COM_set_function( (mname+".size_of_cpanes").c_str(),
                     (Func_ptr)size_of_cpanes, "iioO", types);
   COM_window_init_done( mname.c_str());
 }
void pane_border_nodes (const COM::Attribute * mesh, COM::Attribute * isborder, int * ghost_level = NULL) static
Determine the nodes at pane boundaries of a given mesh.
The argument isborder must be a nodal attribute of integer type. At return, isborder is set to 1 for border nodes, and 0 for others
Definition at line 43 of file Rocmap.C.
References Pane_boundary::determine_borders().
Referenced by load().
{
   Pane_boundary::determine_borders( mesh, isborder, ghost_level?*ghost_level:0);
 }
void reduce_average_on_shared_nodes (COM::Attribute * att, COM::Attribute * pconn = NULL) static
Perform an average-reduction on the shared nodes for the given attribute.
Definition at line 57 of file Rocmap.C.
References Pane_communicator::init().
Referenced by load(), and Rocmop::smooth_vol_mesq_wg().
{
   Pane_communicator pc(att->window(), att->window()->get_communicator());
   pc.init(att,pconn);
   pc.begin_update_shared_nodes();
   pc.reduce_average_on_shared_nodes();
   pc.end_update_shared_nodes();
 }
void reduce_maxabs_on_shared_nodes (COM::Attribute * att, COM::Attribute * pconn = NULL) static
Perform a maxabs-reduction on the shared nodes for the given attribute.
Definition at line 77 of file Rocmap.C.
References Pane_communicator::init().
Referenced by Rocmop::determine_physical_border(), load(), and Rocmop::smooth_vol_mesq_ng().
{
   Pane_communicator pc(att->window(), att->window()->get_communicator());
   pc.init(att,pconn);
   pc.begin_update_shared_nodes();
   pc.reduce_maxabs_on_shared_nodes();
   pc.end_update_shared_nodes();
 }
void reduce_minabs_on_shared_nodes (COM::Attribute * att, COM::Attribute * pconn = NULL) static
Perform a minabs-reduction on the shared nodes for the given attribute.
Definition at line 67 of file Rocmap.C.
References Pane_communicator::init().
Referenced by load().
{
   Pane_communicator pc(att->window(), att->window()->get_communicator());
   pc.init(att,pconn);
   pc.begin_update_shared_nodes();
   pc.reduce_minabs_on_shared_nodes();
   pc.end_update_shared_nodes();
 }
void size_of_cpanes (const COM::Attribute * pconn, const int * pane_id, int * npanes_total, int * npanes_ghost = NULL) static
Get the number of communicating panes.
Definition at line 50 of file Rocmap.C.
References Pane_connectivity::size_of_cpanes().
Referenced by load().
{
   Pane_connectivity::size_of_cpanes(pconn, pane_id, npanes_total, npanes_ghost);
 }
void unload (const std::string & mname) static
Unloads Rocmap from Roccom.
Definition at line 136 of file Rocmap.C.
References COM_delete_window().
Referenced by Rocmap_unload_module(), rocmap_unload_module(), ROCMAP_UNLOAD_MODULE(), rocmap_unload_module_(), and ROCMAP_UNLOAD_MODULE_().
{
   COM_delete_window( mname.c_str());
 }
void update_ghosts (COM::Attribute * att, const COM::Attribute * pconn = NULL) static
Update ghost nodal or elemental values for the given attribute.
Definition at line 87 of file Rocmap.C.
References Pane_communicator::init().
Referenced by Rocmop::add_aspect_ratios(), Rocmop::determine_physical_border(), Rocmop::get_usr_disp(), load(), and Rocmop::smooth_vol_mesq_wg().
{
   Pane_communicator pc(att->window(), att->window()->get_communicator());
   pc.init(att, pconn);
   if (att->is_elemental()){
     pc.begin_update_ghost_cells();
     pc.end_update_ghost_cells();
   }
   else{
     pc.begin_update_ghost_nodes();
     pc.end_update_ghost_nodes();
   }
 }
The documentation for this class was generated from the following files:
Rocmap.h
Rocmap.C