Rocstar: TopologyInfo Class Reference
TopologyInfo Class Reference
Information about different element topologies.
#include <TopologyInfo.hpp>
Static Public Member Functions
static unsigned dimension (EntityTopology topo)
Dimension of element topology.
static unsigned adjacent (EntityTopology topo, unsigned dimension)
Number of adjacent entities of a specified dimension.
static unsigned sides (EntityTopology topo)
Get number of sides a given topology type has.
static unsigned corners (EntityTopology topo)
Get the number of defining vertices for a given element topology.
static unsigned edges (EntityTopology topo)
Get the number of edges in a given topology.
static unsigned faces (EntityTopology topo)
Get the number of faces in a given topology.
static void higher_order (EntityTopology topo, unsigned num_nodes, bool &midedge, bool &midface, bool &midvol, MsqError &err)
Check which mid-nodes a higher-order element has.
static const unsigned * edge_vertices (EntityTopology topo, unsigned edge_number, MsqError &err)
Get indices of edge ends in element connectivity array.
static const unsigned * face_vertices (EntityTopology topo, unsigned face_number, unsigned &num_vertices_out, MsqError &err)
Get face corner indices in element connectivity array.
static const unsigned * side_vertices (EntityTopology topo, unsigned side_dimension, unsigned side_number, unsigned &num_verts_out, MsqError &err)
Get corner indices of side.
static void side_number (EntityTopology topo, unsigned connectivity_length, unsigned node_index, unsigned &side_dimension_out, unsigned &side_number_out, MsqError &err)
Return which side the specified mid-node lies on.
static unsigned dimension (EntityTopology topo)
Dimension of element topology.
static unsigned adjacent (EntityTopology topo, unsigned dimension)
Number of adjacent entities of a specified dimension.
static unsigned sides (EntityTopology topo)
Get number of sides a given topology type has.
static unsigned corners (EntityTopology topo)
Get the number of defining vertices for a given element topology.
static unsigned edges (EntityTopology topo)
Get the number of edges in a given topology.
static unsigned faces (EntityTopology topo)
Get the number of faces in a given topology.
static void higher_order (EntityTopology topo, unsigned num_nodes, bool &midedge, bool &midface, bool &midvol, MsqError &err)
Check which mid-nodes a higher-order element has.
static const unsigned * edge_vertices (EntityTopology topo, unsigned edge_number, MsqError &err)
Get indices of edge ends in element connectivity array.
static const unsigned * face_vertices (EntityTopology topo, unsigned face_number, unsigned &num_vertices_out, MsqError &err)
Get face corner indices in element connectivity array.
static const unsigned * side_vertices (EntityTopology topo, unsigned side_dimension, unsigned side_number, unsigned &num_verts_out, MsqError &err)
Get corner indices of side.
static void side_number (EntityTopology topo, unsigned connectivity_length, unsigned node_index, unsigned &side_dimension_out, unsigned &side_number_out, MsqError &err)
Return which side the specified mid-node lies on.
Private Types
enum {
MAX_EDGES = 12, MAX_FACES = 6, MAX_FACE_CONN = 5, FIRST_FACE = TRIANGLE,
LAST_FACE = QUADRILATERAL, FIRST_VOL = TETRAHEDRON, LAST_VOL = PYRAMID
}
enum {
MAX_EDGES = 12, MAX_FACES = 6, MAX_FACE_CONN = 5, FIRST_FACE = TRIANGLE,
LAST_FACE = QUADRILATERAL, FIRST_VOL = TETRAHEDRON, LAST_VOL = PYRAMID
}
Private Member Functions
TopologyInfo ()
TopologyInfo ()
Private Attributes
unsigned dimMap [MIXED]
Get dimension of entity given topology.
unsigned adjMap [MIXED][3]
Get number of adj entities of dimension 0, 1 and dimension 2.
unsigned edgeMap [LAST_VOL-FIRST_FACE+1][MAX_EDGES][2]
Vertex indices for element edges.
unsigned faceMap [LAST_VOL-FIRST_VOL+1][MAX_FACES][MAX_FACE_CONN]
Vertex indices for element faces.
Static Private Attributes
static TopologyInfo instance
Detailed Description
Information about different element topologies.
Definition at line 38 of file includeLinks/TopologyInfo.hpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
MAX_EDGES
MAX_FACES
MAX_FACE_CONN
FIRST_FACE
LAST_FACE
FIRST_VOL
LAST_VOL
Definition at line 145 of file includeLinks/TopologyInfo.hpp.
          {
       MAX_EDGES = 12,
       MAX_FACES = 6,
       MAX_FACE_CONN = 5,
       FIRST_FACE = TRIANGLE,
       LAST_FACE = QUADRILATERAL,
       FIRST_VOL= TETRAHEDRON,
       LAST_VOL = PYRAMID
     };
anonymous enum private
Enumerator
MAX_EDGES
MAX_FACES
MAX_FACE_CONN
FIRST_FACE
LAST_FACE
FIRST_VOL
LAST_VOL
Definition at line 145 of file src/Mesh/TopologyInfo.hpp.
          {
       MAX_EDGES = 12,
       MAX_FACES = 6,
       MAX_FACE_CONN = 5,
       FIRST_FACE = TRIANGLE,
       LAST_FACE = QUADRILATERAL,
       FIRST_VOL= TETRAHEDRON,
       LAST_VOL = PYRAMID
     };
Constructor & Destructor Documentation
TopologyInfo () private
Definition at line 38 of file Mesh/TopologyInfo.cpp.
References TopologyInfo::adjMap, TopologyInfo::dimMap, TopologyInfo::edgeMap, TopologyInfo::faceMap, TopologyInfo::FIRST_FACE, TopologyInfo::FIRST_VOL, Mesquite::HEXAHEDRON, Mesquite::POLYGON, Mesquite::POLYHEDRON, Mesquite::PRISM, Mesquite::PYRAMID, Mesquite::QUADRILATERAL, Mesquite::SEPTAHEDRON, Mesquite::TETRAHEDRON, and Mesquite::TRIANGLE.
 {
   memset( dimMap, 0, sizeof(dimMap) );
   memset( adjMap, 0, sizeof(adjMap) );
   memset( edgeMap, 0, sizeof(edgeMap) );
   memset( faceMap, 0, sizeof(faceMap) );
   dimMap[POLYGON ]      = 2;
   dimMap[TRIANGLE]      = 2;
   dimMap[QUADRILATERAL] = 2;
   dimMap[POLYHEDRON]    = 3;
   dimMap[TETRAHEDRON]   = 3;
   dimMap[HEXAHEDRON]    = 3;
   dimMap[PRISM]         = 3;
   dimMap[PYRAMID]       = 3;
   dimMap[SEPTAHEDRON]   = 3;
   adjMap[TRIANGLE][0] = 3;
   adjMap[TRIANGLE][1] = 3;
   adjMap[QUADRILATERAL][0] = 4;
   adjMap[QUADRILATERAL][1] = 4;
   adjMap[TETRAHEDRON][0] = 4;
   adjMap[TETRAHEDRON][1] = 6;
   adjMap[TETRAHEDRON][2] = 4;
   adjMap[HEXAHEDRON][0] = 8;
   adjMap[HEXAHEDRON][1] = 12;
   adjMap[HEXAHEDRON][2] = 6;
   adjMap[PRISM][0] = 6;
   adjMap[PRISM][1] = 9;
   adjMap[PRISM][2] = 5;
   adjMap[PYRAMID][0] = 5;
   adjMap[PYRAMID][1] = 8;
   adjMap[PYRAMID][2] = 5;
   adjMap[SEPTAHEDRON][0] = 7;
   adjMap[SEPTAHEDRON][1] = 11;
   adjMap[SEPTAHEDRON][2] = 6;  /* See description in TSTT mesh interface doc */
   int side;
   for (side = 0; side < 3; ++side)
   {
     edgeMap[TRIANGLE-FIRST_FACE][side][0] = side;
     edgeMap[TRIANGLE-FIRST_FACE][side][1] = (side+1)%3;
   }
   for (side = 0; side < 4; ++side)
   {
     edgeMap[QUADRILATERAL-FIRST_FACE][side][0] = side;
     edgeMap[QUADRILATERAL-FIRST_FACE][side][1] = (side+1)%4;
   }
   for (side = 0; side < 3; ++side)
   {
     edgeMap[TETRAHEDRON-FIRST_FACE][side][0] = side;
     edgeMap[TETRAHEDRON-FIRST_FACE][side][1] = (side+1)%3;
   }
   for (side = 3; side < 6; ++side)
   {
     edgeMap[TETRAHEDRON-FIRST_FACE][side][0] = side -3 ;
     edgeMap[TETRAHEDRON-FIRST_FACE][side][1] = 3;
   }
   for (side = 0; side < 4; ++side)
   {
     edgeMap[HEXAHEDRON-FIRST_FACE][side][0] = side;
     edgeMap[HEXAHEDRON-FIRST_FACE][side][1] = (side+1)%4;
   }
   for (side = 4; side < 8; ++side)
   {
     edgeMap[HEXAHEDRON-FIRST_FACE][side][0] = side - 4;
     edgeMap[HEXAHEDRON-FIRST_FACE][side][1] = side;
   }
   for (side = 8; side < 12; ++side)
   {
     edgeMap[HEXAHEDRON-FIRST_FACE][side][0] = side - 4;
     edgeMap[HEXAHEDRON-FIRST_FACE][side][1] = 4+(side+1)%4;
   }
   for (side = 0; side < 3; ++side)
   {
     edgeMap[PRISM-FIRST_FACE][side][0] = side;
     edgeMap[PRISM-FIRST_FACE][side][1] = (side+1)%3;
   }
   for (side = 3; side < 6; ++side)
   {
     edgeMap[PRISM-FIRST_FACE][side][0] = side - 3;
     edgeMap[PRISM-FIRST_FACE][side][1] = side;
   }
   for (side = 6; side < 9; ++side)
   {
     edgeMap[PRISM-FIRST_FACE][side][0] = side-3;
     edgeMap[PRISM-FIRST_FACE][side][1] = 3+(side+1)%3;
   }
   for (side = 0; side < 4; ++side)
   {
     edgeMap[PYRAMID-FIRST_FACE][side][0] = side;
     edgeMap[PYRAMID-FIRST_FACE][side][1] = (side+1)%4;
   }
   for (side = 4; side < 8; ++side)
   {
     edgeMap[PYRAMID-FIRST_FACE][side][0] = side - 4;
     edgeMap[PYRAMID-FIRST_FACE][side][1] = 4;
   }
   for (side = 0; side < 3; ++side)
   {
     faceMap[TETRAHEDRON-FIRST_VOL][side][0] = 3;
     faceMap[TETRAHEDRON-FIRST_VOL][side][1] = side;
     faceMap[TETRAHEDRON-FIRST_VOL][side][2] = (side+1)%3;
     faceMap[TETRAHEDRON-FIRST_VOL][side][3] = 3;
   }
   faceMap[TETRAHEDRON-FIRST_VOL][3][0] = 3;
   faceMap[TETRAHEDRON-FIRST_VOL][3][1] = 2;
   faceMap[TETRAHEDRON-FIRST_VOL][3][2] = 1;
   faceMap[TETRAHEDRON-FIRST_VOL][3][3] = 0;
   for (side = 0; side < 4; ++side)
   {
     faceMap[HEXAHEDRON-FIRST_VOL][side][0] = 4;
     faceMap[HEXAHEDRON-FIRST_VOL][side][1] = side;
     faceMap[HEXAHEDRON-FIRST_VOL][side][2] = (side+1)%4;
     faceMap[HEXAHEDRON-FIRST_VOL][side][3] = 4+(side+1)%4;
     faceMap[HEXAHEDRON-FIRST_VOL][side][4] = side + 4;
   }
   faceMap[HEXAHEDRON-FIRST_VOL][4][0] = 4;
   faceMap[HEXAHEDRON-FIRST_VOL][4][1] = 3;
   faceMap[HEXAHEDRON-FIRST_VOL][4][2] = 2;
   faceMap[HEXAHEDRON-FIRST_VOL][4][3] = 1;
   faceMap[HEXAHEDRON-FIRST_VOL][4][4] = 0;
   faceMap[HEXAHEDRON-FIRST_VOL][5][0] = 4;
   faceMap[HEXAHEDRON-FIRST_VOL][5][1] = 4;
   faceMap[HEXAHEDRON-FIRST_VOL][5][2] = 5;
   faceMap[HEXAHEDRON-FIRST_VOL][5][3] = 6;
   faceMap[HEXAHEDRON-FIRST_VOL][5][4] = 7;
   for (side = 0; side < 4; ++side)
   {
     faceMap[PYRAMID-FIRST_VOL][side][0] = 3;
     faceMap[PYRAMID-FIRST_VOL][side][1] = side;
     faceMap[PYRAMID-FIRST_VOL][side][2] = (side+1)%4;
     faceMap[PYRAMID-FIRST_VOL][side][3] = 4;
   }
   faceMap[PYRAMID-FIRST_VOL][4][0] = 4;
   faceMap[PYRAMID-FIRST_VOL][4][1] = 3;
   faceMap[PYRAMID-FIRST_VOL][4][2] = 2;
   faceMap[PYRAMID-FIRST_VOL][4][3] = 1;
   faceMap[PYRAMID-FIRST_VOL][4][4] = 0;
   for (side = 0; side < 3; ++side)
   {
     faceMap[PRISM-FIRST_VOL][side][0] = 4;
     faceMap[PRISM-FIRST_VOL][side][1] = side;
     faceMap[PRISM-FIRST_VOL][side][2] = (side+1)%3;
     faceMap[PRISM-FIRST_VOL][side][3] = 3+(side+1)%3;
     faceMap[PRISM-FIRST_VOL][side][4] = side + 3;
   }
   faceMap[PRISM-FIRST_VOL][3][0] = 3;
   faceMap[PRISM-FIRST_VOL][3][1] = 2;
   faceMap[PRISM-FIRST_VOL][3][2] = 1;
   faceMap[PRISM-FIRST_VOL][3][3] = 0;
   faceMap[PRISM-FIRST_VOL][4][0] = 3;
   faceMap[PRISM-FIRST_VOL][4][1] = 3;
   faceMap[PRISM-FIRST_VOL][4][2] = 4;
   faceMap[PRISM-FIRST_VOL][4][3] = 5;
 }
TopologyInfo () private
Member Function Documentation
static unsigned adjacent (EntityTopology topo, unsigned dimension) inline static
Number of adjacent entities of a specified dimension.
For a given element topology, get the number of adjacent entities of the specified dimension.
Definition at line 51 of file includeLinks/TopologyInfo.hpp.
References TopologyInfo::adjMap, TopologyInfo::dimension(), TopologyInfo::instance, and Mesquite::MIXED.
Referenced by TopologyInfo::edges(), and TopologyInfo::faces().
       { return (topo >= MIXED  || dimension > 2) ? 0 : instance.adjMap[topo][dimension]; }
static unsigned adjacent (EntityTopology topo, unsigned dimension) inline static
Number of adjacent entities of a specified dimension.
For a given element topology, get the number of adjacent entities of the specified dimension.
Definition at line 51 of file src/Mesh/TopologyInfo.hpp.
References TopologyInfo::adjMap, TopologyInfo::dimension(), TopologyInfo::instance, and Mesquite::MIXED.
       { return (topo >= MIXED  || dimension > 2) ? 0 : instance.adjMap[topo][dimension]; }
static unsigned corners (EntityTopology topo) inline static
Get the number of defining vertices for a given element topology.
Get the number of corner vertices necessary to define an element of the specified topology. This is the number of nodes a linear element of the specified topology will have.
Definition at line 71 of file includeLinks/TopologyInfo.hpp.
References TopologyInfo::adjMap, TopologyInfo::instance, and Mesquite::MIXED.
Referenced by MeshImplData::clear_element(), MeshImplData::copy_mesh(), MeshImplData::element_topology(), MeanMidNodeMover::loop_over_mesh(), MeshImplData::num_vertex_uses(), MeshImplData::set_element(), TopologyInfo::side_vertices(), and MsqMeshEntity::vertex_count().
       { return topo >= MIXED ? 0 : instance.adjMap[topo][0]; }
static unsigned corners (EntityTopology topo) inline static
Get the number of defining vertices for a given element topology.
Get the number of corner vertices necessary to define an element of the specified topology. This is the number of nodes a linear element of the specified topology will have.
Definition at line 71 of file src/Mesh/TopologyInfo.hpp.
References TopologyInfo::adjMap, TopologyInfo::instance, and Mesquite::MIXED.
       { return topo >= MIXED ? 0 : instance.adjMap[topo][0]; }
static unsigned dimension (EntityTopology topo) inline static
Dimension of element topology.
Definition at line 43 of file includeLinks/TopologyInfo.hpp.
References TopologyInfo::dimMap, TopologyInfo::instance, and Mesquite::MIXED.
Referenced by TopologyInfo::adjacent(), MeshImplData::has_adjacent_elements(), TopologyInfo::side_vertices(), and MeshImplData::skin().
       { return topo >= MIXED ? 0: instance.dimMap[topo]; }
static unsigned dimension (EntityTopology topo) inline static
Dimension of element topology.
Definition at line 43 of file src/Mesh/TopologyInfo.hpp.
References TopologyInfo::dimMap, TopologyInfo::instance, and Mesquite::MIXED.
       { return topo >= MIXED ? 0: instance.dimMap[topo]; }
const unsigned * edge_vertices (EntityTopology topo, unsigned edge_number, MsqError & err) static
Get indices of edge ends in element connectivity array.
Definition at line 255 of file Mesh/TopologyInfo.cpp.
References TopologyInfo::edgeMap, TopologyInfo::edges(), TopologyInfo::FIRST_FACE, TopologyInfo::instance, MsqError::INVALID_ARG, TopologyInfo::LAST_VOL, and MSQ_SETERR.
Referenced by TopologyInfo::side_vertices().
 {
   if (topo < (EntityTopology)FIRST_FACE ||
       topo > (EntityTopology)LAST_VOL ||
       edge >= edges( topo ) )
   {
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     topo = (EntityTopology)FIRST_FACE;
     edge = 0;
   }
   return instance.edgeMap[topo-FIRST_FACE][edge];
 }
static const unsigned* edge_vertices (EntityTopology topo, unsigned edge_number, MsqError & err) static
Get indices of edge ends in element connectivity array.
static unsigned edges (EntityTopology topo) inline static
Get the number of edges in a given topology.
Definition at line 75 of file src/Mesh/TopologyInfo.hpp.
References TopologyInfo::adjacent().
       { return adjacent(topo, 1); }
static unsigned edges (EntityTopology topo) inline static
Get the number of edges in a given topology.
Definition at line 75 of file includeLinks/TopologyInfo.hpp.
References TopologyInfo::adjacent().
Referenced by TopologyInfo::edge_vertices(), TopologyInfo::higher_order(), and TopologyInfo::side_number().
       { return adjacent(topo, 1); }
const unsigned * face_vertices (EntityTopology topo, unsigned face_number, unsigned & num_vertices_out, MsqError & err) static
Get face corner indices in element connectivity array.
Definition at line 271 of file Mesh/TopologyInfo.cpp.
References face, TopologyInfo::faceMap, TopologyInfo::faces(), TopologyInfo::FIRST_VOL, TopologyInfo::instance, MsqError::INVALID_ARG, TopologyInfo::LAST_VOL, and MSQ_SETERR.
Referenced by TopologyInfo::side_vertices().
 {
   if (topo < (EntityTopology)FIRST_VOL ||
       topo > (EntityTopology)LAST_VOL ||
       face >= faces( topo ) )
   {
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     topo = (EntityTopology)FIRST_VOL;
     face = 0;
   }
   length = instance.faceMap[topo-FIRST_VOL][face][0];
   return instance.faceMap[topo-FIRST_VOL][face] + 1;
 }
static const unsigned* face_vertices (EntityTopology topo, unsigned face_number, unsigned & num_vertices_out, MsqError & err) static
Get face corner indices in element connectivity array.
static unsigned faces (EntityTopology topo) inline static
Get the number of faces in a given topology.
Definition at line 79 of file src/Mesh/TopologyInfo.hpp.
References TopologyInfo::adjacent().
       { return adjacent(topo, 2 ); }
static unsigned faces (EntityTopology topo) inline static
Get the number of faces in a given topology.
Definition at line 79 of file includeLinks/TopologyInfo.hpp.
References TopologyInfo::adjacent().
Referenced by TopologyInfo::face_vertices(), TopologyInfo::higher_order(), and TopologyInfo::side_number().
       { return adjacent(topo, 2 ); }
static void higher_order (EntityTopology topo, unsigned num_nodes, bool & midedge, bool & midface, bool & midvol, MsqError & err) static
Check which mid-nodes a higher-order element has.
Assuming at most one mid-node per sub-entity per dimension (i.e. at most one mid-edge node, at most one mid-face node, etc.) determine which mid-nodes are present given the topology and total number of nodes.
void higher_order (EntityTopology topo, unsigned num_nodes, bool & midedge, bool & midface, bool & midvol, MsqError & err) static
Check which mid-nodes a higher-order element has.
Assuming at most one mid-node per sub-entity per dimension (i.e. at most one mid-edge node, at most one mid-face node, etc.) determine which mid-nodes are present given the topology and total number of nodes.
Definition at line 205 of file Mesh/TopologyInfo.cpp.
References TopologyInfo::adjMap, TopologyInfo::dimMap, TopologyInfo::edges(), TopologyInfo::faces(), TopologyInfo::instance, MsqError::INVALID_ARG, MsqError::INVALID_STATE, Mesquite::MIXED, and MSQ_SETERR.
 {
   midedge = midface = midvol = false;
   if (topo >= MIXED || num_nodes < instance.adjMap[topo][0])
   {
     MSQ_SETERR(err)("Invalid element topology", MsqError::INVALID_ARG);
     return;
   }
   unsigned dim = instance.dimMap[topo];
   assert( num_nodes >= instance.adjMap[topo][0] );
   unsigned nodes = num_nodes - instance.adjMap[topo][0];
   unsigned edges = instance.adjMap[topo][1];
   unsigned faces = instance.adjMap[topo][2];
   if (edges && nodes >= edges)
   {
     nodes -= edges;
     midedge = true;
   }
   if (faces && nodes >= faces)
   {
     nodes -= faces;
     midface = true;
   }
   if (1 == nodes)
   {
     if (2 == dim)
     {
       nodes -= 1;
       midface = true;
     }
     else if(3 == dim)
     {
       nodes -= 1;
       midvol = true;
     }
   }
   if (nodes)
   {
     MSQ_SETERR(err)("Invalid element topology", MsqError::INVALID_STATE);
   }
 }
void side_number (EntityTopology topo, unsigned connectivity_length, unsigned node_index, unsigned & side_dimension_out, unsigned & side_number_out, MsqError & err) static
Return which side the specified mid-node lies on.
Given an non-linear element type (specified by the topology and lenght of the connectiivty array) and the index of a node in the element's connectivity array, return the lower-dimension entity (side) of the element the mid-node lies on.
Parameters
topo Element topology
connectivity_length Number of nodes in element
node_index Which node of the element
side_dimension_out The dimension of the side containing the midnode (0 = vertex, 1 = edge, 2 = face, 3 = volume)
side_number_out The canonical number of the side
Definition at line 326 of file Mesh/TopologyInfo.cpp.
References TopologyInfo::adjMap, TopologyInfo::dimMap, TopologyInfo::edges(), TopologyInfo::faces(), TopologyInfo::instance, MsqError::INVALID_ARG, Mesquite::MIXED, and MSQ_SETERR.
Referenced by MeshImplData::copy_higher_order(), and MeanMidNodeMover::loop_over_mesh().
 {
   if (topo >= (EntityTopology)MIXED || num_nodes < instance.adjMap[topo][0])
   {
     MSQ_SETERR(err)("Invalid element topology", MsqError::INVALID_ARG);
     return;
   }
   unsigned nodes = instance.adjMap[topo][0];
   unsigned edges = instance.adjMap[topo][1];
   unsigned faces = instance.adjMap[topo][2];
   side_num_out = node_index;
   if (side_num_out < nodes)
   {
     side_dim_out = 0;
     return;
   }
   num_nodes -= nodes;
   side_num_out -= nodes;
   if (edges && num_nodes >= edges)
   {
     if (side_num_out < edges)
     {
       side_dim_out = 1;
       return;
     }
     num_nodes -= edges;
     side_num_out -= edges;
   }
   if (faces && num_nodes >= faces)
   {
     if (side_num_out < faces)
     {
       side_dim_out = 2;
       return;
     }
     num_nodes -= faces;
     side_num_out -= faces;
   }
   if (side_num_out == 0)
   {
     side_dim_out = instance.dimMap[topo];
     side_num_out = 0;
     return;
   }
   MSQ_SETERR(err)(MsqError::INVALID_ARG);
 }
static void side_number (EntityTopology topo, unsigned connectivity_length, unsigned node_index, unsigned & side_dimension_out, unsigned & side_number_out, MsqError & err) static
Return which side the specified mid-node lies on.
Given an non-linear element type (specified by the topology and lenght of the connectiivty array) and the index of a node in the element's connectivity array, return the lower-dimension entity (side) of the element the mid-node lies on.
Parameters
topo Element topology
connectivity_length Number of nodes in element
node_index Which node of the element
side_dimension_out The dimension of the side containing the midnode (0 = vertex, 1 = edge, 2 = face, 3 = volume)
side_number_out The canonical number of the side
static const unsigned* side_vertices (EntityTopology topo, unsigned side_dimension, unsigned side_number, unsigned & num_verts_out, MsqError & err) static
Get corner indices of side.
Get the indices into element connectivity list for the corners/ends of the specified side of the element. If the passed dimension equals that of the specified topology, the side number is ignored and all the corners of the element are returned. Fails if side dimension greater than the dimension of the specified topology type.
const unsigned * side_vertices (EntityTopology topo, unsigned side_dimension, unsigned side_number, unsigned & num_verts_out, MsqError & err) static
Get corner indices of side.
Get the indices into element connectivity list for the corners/ends of the specified side of the element. If the passed dimension equals that of the specified topology, the side number is ignored and all the corners of the element are returned. Fails if side dimension greater than the dimension of the specified topology type.
Definition at line 292 of file Mesh/TopologyInfo.cpp.
References TopologyInfo::corners(), TopologyInfo::dimension(), TopologyInfo::edge_vertices(), TopologyInfo::face_vertices(), MsqError::INVALID_ARG, and MSQ_SETERR.
Referenced by MeshImplData::copy_higher_order(), MeanMidNodeMover::loop_over_mesh(), and MeshImplData::skin().
 {
   static const unsigned all[] = { 0, 1, 2, 3, 4, 5, 6, 7 };
   const unsigned* result;
   if (dim != 0 && dim == dimension(topo))
   {
     count_out = corners( topo );
     result = all;
   }
   else if (dim == 1)
   {
     count_out = 2;
     result = edge_vertices( topo, side, err );
   }
   else if( dim == 2)
   {
     result = face_vertices( topo, side, count_out, err );
   }
   else
   {
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     count_out = 0;
     result = 0;
   }
   return result;
 }
static unsigned sides (EntityTopology topo) inline static
Get number of sides a given topology type has.
Get the number of sides for a given element topology. Returns the number of adjacent entities of one less dimension. The number of faces for a volume element and the number of edges for a face element
Definition at line 61 of file src/Mesh/TopologyInfo.hpp.
References TopologyInfo::adjMap, TopologyInfo::dimMap, TopologyInfo::instance, and Mesquite::MIXED.
       { return (topo >= MIXED || instance.dimMap[topo] < 1) ? 0 :
           instance.adjMap[topo][instance.dimMap[topo]-1]; }
static unsigned sides (EntityTopology topo) inline static
Get number of sides a given topology type has.
Get the number of sides for a given element topology. Returns the number of adjacent entities of one less dimension. The number of faces for a volume element and the number of edges for a face element
Definition at line 61 of file includeLinks/TopologyInfo.hpp.
References TopologyInfo::adjMap, TopologyInfo::dimMap, TopologyInfo::instance, and Mesquite::MIXED.
Referenced by MeshImplData::skin().
       { return (topo >= MIXED || instance.dimMap[topo] < 1) ? 0 :
           instance.adjMap[topo][instance.dimMap[topo]-1]; }
Member Data Documentation
unsigned adjMap private
Get number of adj entities of dimension 0, 1 and dimension 2.
Definition at line 156 of file includeLinks/TopologyInfo.hpp.
Referenced by TopologyInfo::adjacent(), TopologyInfo::corners(), TopologyInfo::higher_order(), TopologyInfo::side_number(), TopologyInfo::sides(), and TopologyInfo::TopologyInfo().
unsigned dimMap private
Get dimension of entity given topology.
Definition at line 155 of file includeLinks/TopologyInfo.hpp.
Referenced by TopologyInfo::dimension(), TopologyInfo::higher_order(), TopologyInfo::side_number(), TopologyInfo::sides(), and TopologyInfo::TopologyInfo().
unsigned edgeMap private
Vertex indices for element edges.
Definition at line 158 of file includeLinks/TopologyInfo.hpp.
Referenced by TopologyInfo::edge_vertices(), and TopologyInfo::TopologyInfo().
unsigned faceMap private
Vertex indices for element faces.
Definition at line 160 of file includeLinks/TopologyInfo.hpp.
Referenced by TopologyInfo::face_vertices(), and TopologyInfo::TopologyInfo().
TopologyInfo instance static private
Definition at line 164 of file includeLinks/TopologyInfo.hpp.
Referenced by TopologyInfo::adjacent(), TopologyInfo::corners(), TopologyInfo::dimension(), TopologyInfo::edge_vertices(), TopologyInfo::face_vertices(), TopologyInfo::higher_order(), TopologyInfo::side_number(), and TopologyInfo::sides().
The documentation for this class was generated from the following files:
includeLinks/TopologyInfo.hpp
Mesh/TopologyInfo.cpp