Rocstar: rflu_modconvertcv Module Reference
rflu_modconvertcv Module Reference
Public Member Functions
subroutine, public rflu_convertcvcons2prim (pRegion, cvStateFuture)
subroutine, public rflu_convertcvprim2cons (pRegion, cvStateFuture)
subroutine, public rflu_scalarconvertcvcons2prim (pRegion, cvScal, cvScalStateCurrent)
subroutine, public rflu_scalarconvertcvprim2cons (pRegion, cvScal, cvScalStateCurrent)
Detailed Description
Definition at line 42 of file RFLU_ModConvertCv.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_convertcvcons2prim (type(t_region), pointer pRegion, integer, intent(in) cvStateFuture)
Definition at line 90 of file RFLU_ModConvertCv.F90.
References moderror::deregisterfunction(), moderror::errorstop(), mixtperf_r_m(), mixtperf_t_dpr(), Color::r(), and moderror::registerfunction().
Referenced by cellgradientsmp(), explicitmultistage(), rflu_modplottingvars::rflu_computeplottingvarswrapper(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modnscbc::rflu_nscbc_comprhs(), rflu_modresidual::rflu_res_computeresidual(), rflu_setvarsdiscwrapper(), sourcetermsmp(), turb_coviscousfluxes(), updatedependentvarsmp(), and viscousfluxes().
subroutine, public rflu_convertcvprim2cons (type(t_region), pointer pRegion, integer, intent(in) cvStateFuture)
Definition at line 275 of file RFLU_ModConvertCv.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Color::g(), mixtgasliq_eo_cvmtvm2(), mixtperf_cv_cpr(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), Color::r(), moderror::registerfunction(), and v.
Referenced by cellgradientsmp(), explicitmultistage(), rflu_modplottingvars::rflu_computeplottingvarswrapper(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modnscbc::rflu_nscbc_comprhs(), rflu_modresidual::rflu_res_computeresidual(), rflu_setvarsdiscwrapper(), sourcetermsmp(), turb_coviscousfluxes(), updatedependentvarsmp(), and viscousfluxes().
subroutine, public rflu_scalarconvertcvcons2prim (type(t_region), pointer pRegion, real(rfreal), dimension(:,:) cvScal, integer, intent(inout) cvScalStateCurrent)
Definition at line 473 of file RFLU_ModConvertCv.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by cellgradientsmp(), convectivefluxesmp(), rflu_initflowhardcodelimwrapper(), rflu_setvarscontwrapper(), and viscousfluxesmp().
subroutine, public rflu_scalarconvertcvprim2cons (type(t_region), pointer pRegion, real(rfreal), dimension(:,:) cvScal, integer, intent(inout) cvScalStateCurrent)
Definition at line 572 of file RFLU_ModConvertCv.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Color::r(), and moderror::registerfunction().
Referenced by cellgradientsmp(), convectivefluxesmp(), rflu_initflowhardcodelimwrapper(), rflu_initflowhardcodewrapper(), rflu_initflowscratchwrapper(), rflu_setvarscontwrapper(), and viscousfluxesmp().
The documentation for this module was generated from the following file:
RFLU_ModConvertCv.F90