Rocstar: rflo_modgridmetrics Module Reference
rflo_modgridmetrics Module Reference
Public Member Functions
subroutine, public rflo_arclengthpatch (region, patch, xyzRef)
subroutine, public rflo_calcgridmetrics (regions)
subroutine, public rflo_gridqualityglobal (regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModGridMetrics.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 39 of file RFLO_ModGridMetrics.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_arclengthpatch (type(t_region) region, type(t_patch), pointer patch, real(rfreal), dimension(:,:), pointer xyzRef)
Definition at line 92 of file RFLO_ModGridMetrics.F90.
References moderror::deregisterfunction(), ibeg, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and sqrt().
Referenced by rflo_getgeometry().
subroutine, public rflo_calcgridmetrics (type (t_region), dimension(:), pointer regions)
Definition at line 245 of file RFLO_ModGridMetrics.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_checkmetrics(), rflo_gridqualityglobal(), and rflo_initavgcoeffs().
Referenced by rflo_flowsolver(), and rflo_initflowsolver().
subroutine, public rflo_gridqualityglobal (type (t_region), dimension(:), pointer regions)
Definition at line 326 of file RFLO_ModGridMetrics.F90.
References moderror::deregisterfunction(), moderror::errorstop(), min(), and moderror::registerfunction().
Referenced by rflo_calcgridmetrics(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), and rflo_modmovegridframe::rflo_movegridframe().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModGridMetrics.F90,v $ $Revision: 1.7 $' private
Definition at line 63 of file RFLO_ModGridMetrics.F90.
The documentation for this module was generated from the following file:
RFLO_ModGridMetrics.F90