Rocstar: AspectRatioGammaQualityMetric Class Reference
AspectRatioGammaQualityMetric Class Reference
Object for computing the aspect ratio gamma of simplicial elements.
#include <AspectRatioGammaQualityMetric.hpp>
Public Member Functions
AspectRatioGammaQualityMetric ()
virtual ~AspectRatioGammaQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
AspectRatioGammaQualityMetric ()
virtual ~AspectRatioGammaQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
Public Member Functions inherited from ShapeQualityMetric
virtual ~ShapeQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
virtual ~ShapeQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Private Member Functions
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &fval, MsqError &err)
Computes the aspect ratio gamma of element.
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &fval, MsqError &err)
Computes the aspect ratio gamma of element.
Private Attributes
double fourDivRootThree
double twelveDivRootTwo
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Member Functions inherited from ShapeQualityMetric
bool condition_number_2d (Vector3D temp_vec[], size_t v_ind, PatchData &pd, double &fval, MsqError &err)
Given the 2-d jacobian matrix, compute the condition number, fval.
bool condition_number_3d (Vector3D temp_vec[], PatchData &pd, double &fval, MsqError &err)
Given the 3-d jacobian matrix, compute the condition number, fval.
bool condition_number_2d (Vector3D temp_vec[], size_t v_ind, PatchData &pd, double &fval, MsqError &err)
Given the 2-d jacobian matrix, compute the condition number, fval.
bool condition_number_3d (Vector3D temp_vec[], PatchData &pd, double &fval, MsqError &err)
Given the 3-d jacobian matrix, compute the condition number, fval.
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
Object for computing the aspect ratio gamma of simplicial elements.
Definition at line 50 of file includeLinks/AspectRatioGammaQualityMetric.hpp.
Constructor & Destructor Documentation
AspectRatioGammaQualityMetric () inline
Definition at line 53 of file includeLinks/AspectRatioGammaQualityMetric.hpp.
References QualityMetric::ELEMENT_BASED, QualityMetric::ELEMENT_VERTICES, QualityMetric::feasible, AspectRatioGammaQualityMetric::fourDivRootThree, QualityMetric::set_element_evaluation_mode(), QualityMetric::set_metric_type(), QualityMetric::set_name(), sqrt(), and AspectRatioGammaQualityMetric::twelveDivRootTwo.
         {
           MsqError err;
           set_metric_type(ELEMENT_BASED);
           set_element_evaluation_mode(ELEMENT_VERTICES, err);
           fourDivRootThree=4.0/sqrt(3.0);
           twelveDivRootTwo=12.0/sqrt(2.0);
           feasible=0;
           set_name("Aspect Ratio Gamma");
         }
virtual ~AspectRatioGammaQualityMetric () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 64 of file includeLinks/AspectRatioGammaQualityMetric.hpp.
         {}
AspectRatioGammaQualityMetric () inline
Definition at line 53 of file src/QualityMetric/Shape/AspectRatioGammaQualityMetric.hpp.
References QualityMetric::ELEMENT_BASED, QualityMetric::ELEMENT_VERTICES, QualityMetric::feasible, AspectRatioGammaQualityMetric::fourDivRootThree, QualityMetric::set_element_evaluation_mode(), QualityMetric::set_metric_type(), QualityMetric::set_name(), sqrt(), and AspectRatioGammaQualityMetric::twelveDivRootTwo.
         {
           MsqError err;
           set_metric_type(ELEMENT_BASED);
           set_element_evaluation_mode(ELEMENT_VERTICES, err);
           fourDivRootThree=4.0/sqrt(3.0);
           twelveDivRootTwo=12.0/sqrt(2.0);
           feasible=0;
           set_name("Aspect Ratio Gamma");
         }
virtual ~AspectRatioGammaQualityMetric () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 64 of file src/QualityMetric/Shape/AspectRatioGammaQualityMetric.hpp.
         {}
Member Function Documentation
bool evaluate_element (PatchData & pd, MsqMeshEntity * element, double & fval, MsqError & err) private virtual
Computes the aspect ratio gamma of element.
Evaluate aspect ratio gamma on ``element''.
If element is not a tetrahedron or triangle, sets an error.
Reimplemented from QualityMetric.
Definition at line 54 of file QualityMetric/Shape/AspectRatioGammaQualityMetric.cpp.
References AspectRatioGammaQualityMetric::fourDivRootThree, PatchData::get_element_index(), MsqMeshEntity::get_element_type(), PatchData::get_element_vertex_coordinates(), MsqError::INVALID_ARG, Mesquite::length(), Vector3D::length_squared(), MSQ_ERRZERO, Mesquite::MSQ_MAX_CAP, Mesquite::MSQ_MIN, MSQ_SETERR, sqrt(), Mesquite::TETRAHEDRON, Mesquite::TRIANGLE, and AspectRatioGammaQualityMetric::twelveDivRootTwo.
 {
   EntityTopology entity = element->get_element_type();
   double vol=0;
   Vector3D temp_vec(0,0,0);
   bool return_val = true;
     //get element's nodes
   vector<Vector3D> vert;
   size_t elem_index = pd.get_element_index(element);
   pd.get_element_vertex_coordinates(elem_index, vert, err);  MSQ_ERRZERO(err);
   switch(entity)
   {
     case TRIANGLE:
         //area
       vol=(((vert[1]-vert[0])*(vert[2]-vert[0])).length())/2.0;
       vol=fabs(vol);
       if(vol<MSQ_MIN){
         fval=MSQ_MAX_CAP;
       }
       else{
           //sum of edges squared
         temp_vec=vert[1]-vert[0];
         fval=temp_vec.length_squared();
         temp_vec=vert[2]-vert[0];
         fval+=temp_vec.length_squared();
         temp_vec=vert[1]-vert[2];
         fval+=temp_vec.length_squared();
           //average sum of edges squared
         fval/=3.0;
           //normalize to equil. and div by area
           // 2.309... is 4/sqrt(3) (inverse of the area of an equil. tri
         fval/=(vol*fourDivRootThree);
       }
       break;
     case TETRAHEDRON:
       vol=(vert[1]-vert[0])%((vert[2]-vert[0])*(vert[3]-vert[0]))/6.0;
         //sum of edges squared
       if(fabs(vol)<MSQ_MIN){
         fval=MSQ_MAX_CAP;
       }
       else{
         temp_vec=vert[1]-vert[0];
         fval=temp_vec.length_squared();
         temp_vec=vert[2]-vert[0];
         fval+=temp_vec.length_squared();
         temp_vec=vert[3]-vert[0];
         fval+=temp_vec.length_squared();
         temp_vec=vert[2]-vert[1];
         fval+=temp_vec.length_squared();
         temp_vec=vert[3]-vert[1];
         fval+=temp_vec.length_squared();
         temp_vec=vert[3]-vert[2];
         fval+=temp_vec.length_squared();
           //average sum of edges squared
         fval/=6.0;
         fval=sqrt(fval);
         fval*=(fval);
         fval*=(fval);
           //normalize to equil. and div by area
         fval/=(vol*twelveDivRootTwo);
       }
       break;
     default:
       fval=MSQ_MAX_CAP;
       MSQ_SETERR(err)(MsqError::INVALID_ARG,
                      "Entity type %d is not valid for Aspect Ratio Gamma\n",
                      (int)entity);
       return_val = false;
       break;
   };
   return return_val;
 }
bool evaluate_element (PatchData & pd, MsqMeshEntity * element, double & fval, MsqError & err) private virtual
Computes the aspect ratio gamma of element.
If element is not a tetrahedron or triangle, sets an error.
Reimplemented from QualityMetric.
Member Data Documentation
double fourDivRootThree private
Definition at line 72 of file includeLinks/AspectRatioGammaQualityMetric.hpp.
Referenced by AspectRatioGammaQualityMetric::AspectRatioGammaQualityMetric(), and AspectRatioGammaQualityMetric::evaluate_element().
double twelveDivRootTwo private
Definition at line 73 of file includeLinks/AspectRatioGammaQualityMetric.hpp.
Referenced by AspectRatioGammaQualityMetric::AspectRatioGammaQualityMetric(), and AspectRatioGammaQualityMetric::evaluate_element().
The documentation for this class was generated from the following files:
includeLinks/AspectRatioGammaQualityMetric.hpp
QualityMetric/Shape/AspectRatioGammaQualityMetric.cpp