Rocstar: update_py Module Reference
update_py Module Reference
Public Member Functions
subroutine burn_get_burning_rate1d (bp, delt, P, To, Tn, Qc, Qc_old, Qr, Qr_old, rhoc, Toa, rb, fr, bflag, Tnp1, Tflame, coor)
subroutine gfun (bp, bw)
subroutine mfun (bp, bw)
subroutine tfun (bp, bw)
Detailed Description
Definition at line 23 of file update_py.f90.
Member Function/Subroutine Documentation
subroutine burn_get_burning_rate1d (type(parameter_structure), pointer bp, real(dbl), intent(in) delt, real(dbl), intent(in) P, real(dbl), intent(in) To, real(dbl), dimension(:), intent(in) Tn, real(dbl), intent(in) Qc, real(dbl), intent(in) Qc_old, real(dbl), intent(in) Qr, real(dbl), intent(in) Qr_old, real(dbl), intent(in) rhoc, real(dbl), intent(inout) Toa, real(dbl), intent(inout) rb, real(dbl), intent(inout) fr, integer, intent(inout) bflag, real(dbl), dimension(:), intent(out) Tnp1, real(dbl), intent(out) Tflame, real(dbl), dimension(3), intent(in) coor)
Definition at line 28 of file update_py.f90.
References Rocblas::add(), gfun(), i, merge, mfun(), rhs, StopWatch::stop(), tfun(), and Matrix3D::zero().
Referenced by burn_initialize().
subroutine gfun (type(parameter_structure), pointer bp, type(work_structure), intent(inout) bw)
Definition at line 159 of file update_py.f90.
References data_py::polin2().
Referenced by burn_get_burning_rate1d().
subroutine mfun (type(parameter_structure), pointer bp, type(work_structure), intent(inout) bw)
Definition at line 223 of file update_py.f90.
References data_py::polin2().
Referenced by burn_get_burning_rate1d().
subroutine tfun (type(parameter_structure), pointer bp, type(work_structure), intent(inout) bw)
Definition at line 255 of file update_py.f90.
References data_py::polin2().
Referenced by burn_get_burning_rate1d().
The documentation for this module was generated from the following file:
update_py.f90