Rocstar: I_DFT_Generalized Class Reference
I_DFT_Generalized Class Reference
I_DFT metric where mAlpha, mBeta, mGamma, and UseBarrierDelta can be set be the user. Defaults are mAlpha = .5, mBeta = 1, mGamma = 2/3.
#include <I_DFT_Generalized.hpp>
Public Member Functions
I_DFT_Generalized ()
virtual ~I_DFT_Generalized ()
virtual destructor ensures use of polymorphism during destruction
void set_alpha (double val)
set mAlpha
void set_beta (double val)
set mBeta
void set_gamma (double val)
set mGamma
void set_use_barrier_delta (bool val)
set useBarrierDelta
I_DFT_Generalized ()
virtual ~I_DFT_Generalized ()
virtual destructor ensures use of polymorphism during destruction
void set_alpha (double val)
set mAlpha
void set_beta (double val)
set mBeta
void set_gamma (double val)
set mGamma
void set_use_barrier_delta (bool val)
set useBarrierDelta
Public Member Functions inherited from I_DFT
I_DFT ()
virtual ~I_DFT ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *e, double &m, MsqError &err)
Evaluate the metric for an element.
bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], int nfv, double &m, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], Matrix3D h[], int nfv, double &m, MsqError &err)
I_DFT ()
virtual ~I_DFT ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *e, double &m, MsqError &err)
Evaluate the metric for an element.
bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], int nfv, double &m, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], Matrix3D h[], int nfv, double &m, MsqError &err)
Public Member Functions inherited from DistanceFromTarget
virtual ~DistanceFromTarget ()
virtual destructor ensures use of polymorphism during destruction
virtual ~DistanceFromTarget ()
virtual destructor ensures use of polymorphism during destruction
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Member Functions inherited from I_DFT
void p_set_alpha (double alpha)
access function to set mAlpha
double p_get_alpha ()
access function to get mAlpha
void p_set_beta (double beta)
access function to set mBeta
double p_get_beta ()
access function to get mBeta
void p_set_gamma (double gamma)
access function to set mGamma
double p_get_gamma ()
access function to get mGamma
void p_set_use_barrier_delta (bool use_delta)
access function to set useBarrierDelta
bool p_get_use_barrier_delta ()
access function to get useBarrierDelta
void p_set_alpha (double alpha)
access function to set mAlpha
double p_get_alpha ()
access function to get mAlpha
void p_set_beta (double beta)
access function to set mBeta
double p_get_beta ()
access function to get mBeta
void p_set_gamma (double gamma)
access function to set mGamma
double p_get_gamma ()
access function to get mGamma
void p_set_use_barrier_delta (bool use_delta)
access function to set useBarrierDelta
bool p_get_use_barrier_delta ()
access function to get useBarrierDelta
Protected Member Functions inherited from DistanceFromTarget
void compute_T_matrices (MsqMeshEntity &elem, PatchData &pd, Matrix3D T[], size_t num_T, double c_k[], MsqError &err)
For a given element, compute each corner matrix A, and given a target corner matrix W, returns for each corner.
bool get_barrier_function (PatchData &pd, const double &tau, double &h, MsqError &err)
void compute_T_matrices (MsqMeshEntity &elem, PatchData &pd, Matrix3D T[], size_t num_T, double c_k[], MsqError &err)
For a given element, compute each corner matrix A, and given a target corner matrix W, returns for each corner.
bool get_barrier_function (PatchData &pd, const double &tau, double &h, MsqError &err)
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
I_DFT metric where mAlpha, mBeta, mGamma, and UseBarrierDelta can be set be the user. Defaults are mAlpha = .5, mBeta = 1, mGamma = 2/3.
The form of this metric is as follows (taken from I_DFTFamilyFunctions.hpp, see that file for more detail):
              mAlpha * || A*inv(W) - mBeta * I ||_F^2                    \n
---------------------------------------------------------------—
0.5^(mGamma)*(det(A*inv(W)) + sqrt(det(A*inv(W))^2 + 4*delta^2))^(mGamma)
The default for data members (corresponding to the variables above):
  mAlpha = 1/2 \n
  mBeta = 1.0 \n
  mGamma = 2/3 \n
  delta = 0.0 \n
Definition at line 65 of file includeLinks/I_DFT_Generalized.hpp.
Constructor & Destructor Documentation
I_DFT_Generalized () inline
Definition at line 69 of file includeLinks/I_DFT_Generalized.hpp.
References I_DFT::p_set_alpha(), I_DFT::p_set_beta(), I_DFT::p_set_gamma(), I_DFT::p_set_use_barrier_delta(), and QualityMetric::set_name().
     {
       set_name("I_DFT_Generalized");
       p_set_alpha(1.0/2.0);
       p_set_beta(1.0);
       p_set_gamma(2./3.);
       p_set_use_barrier_delta(false);
    }
virtual ~I_DFT_Generalized () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 79 of file includeLinks/I_DFT_Generalized.hpp.
        {};
I_DFT_Generalized () inline
Definition at line 69 of file src/QualityMetric/DFT/I_DFT_Generalized.hpp.
References I_DFT::p_set_alpha(), I_DFT::p_set_beta(), I_DFT::p_set_gamma(), I_DFT::p_set_use_barrier_delta(), and QualityMetric::set_name().
     {
       set_name("I_DFT_Generalized");
       p_set_alpha(1.0/2.0);
       p_set_beta(1.0);
       p_set_gamma(2./3.);
       p_set_use_barrier_delta(false);
    }
virtual ~I_DFT_Generalized () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 79 of file src/QualityMetric/DFT/I_DFT_Generalized.hpp.
        {};
Member Function Documentation
void set_alpha (double val) inline
set mAlpha
Definition at line 82 of file includeLinks/I_DFT_Generalized.hpp.
References I_DFT::p_set_alpha().
       {
         p_set_alpha(val);
       }
void set_alpha (double val) inline
set mAlpha
Definition at line 82 of file src/QualityMetric/DFT/I_DFT_Generalized.hpp.
References I_DFT::p_set_alpha().
       {
         p_set_alpha(val);
       }
void set_beta (double val) inline
set mBeta
Definition at line 87 of file includeLinks/I_DFT_Generalized.hpp.
References I_DFT::p_set_beta().
       {
         p_set_beta(val);
       }
void set_beta (double val) inline
set mBeta
Definition at line 87 of file src/QualityMetric/DFT/I_DFT_Generalized.hpp.
References I_DFT::p_set_beta().
       {
         p_set_beta(val);
       }
void set_gamma (double val) inline
set mGamma
Definition at line 92 of file src/QualityMetric/DFT/I_DFT_Generalized.hpp.
References I_DFT::p_set_gamma().
       {
         p_set_gamma(val);
       }
void set_gamma (double val) inline
set mGamma
Definition at line 92 of file includeLinks/I_DFT_Generalized.hpp.
References I_DFT::p_set_gamma().
       {
         p_set_gamma(val);
       }
void set_use_barrier_delta (bool val) inline
set useBarrierDelta
Definition at line 97 of file includeLinks/I_DFT_Generalized.hpp.
References I_DFT::p_set_use_barrier_delta().
       {
         p_set_use_barrier_delta(val);
       }
void set_use_barrier_delta (bool val) inline
set useBarrierDelta
Definition at line 97 of file src/QualityMetric/DFT/I_DFT_Generalized.hpp.
References I_DFT::p_set_use_barrier_delta().
       {
         p_set_use_barrier_delta(val);
       }
The documentation for this class was generated from the following files:
includeLinks/I_DFT_Generalized.hpp
src/QualityMetric/DFT/I_DFT_Generalized.hpp