Rocstar: DriverProgramComLine Class Reference
DriverProgramComLine Class Reference
The ComLineObject for the example programs.
#include <DriverProgram.H>
Public Member Functions
DriverProgramComLine ()
DriverProgramComLine (const char *args[])
void Initialize ()
This is where the actual options and arguments are described.
Public Member Functions inherited from ComLineObject
ComLineObject ()
Default constructor.
ComLineObject (const char *args[])
Constructor.
ComLineObject (ComLineObject &incom)
Copy constructor.
void Copy (ComLineObject &incom)
Copy method.
int ProcessCommandLine (const char *args[])
One fell swoop processing of command line.
std::string GetRawComLine () const
Raw Command Line Access.
void SetRawComLine (const std::string &incl)
Raw Command Line Access.
int ProcessOptions ()
Processes all command line tokens.
void Record (const char *args[])
Minimal recording of command line.
void AddOption (char s, const std::string &l, int=0)
User interface to describe simple option.
void AddOption (char s, const std::string &l, int, const std::string argname)
User interface to describe option with argument.
void AddArgument (const std::string &a, int reqd=0)
User interface to describe an application argument.
void AddArgHelp (const std::string &a, const std::string &help)
Specify the usage info for application argument.
void SetArgName (const std::string opstr, const std::string argname)
Specify name of an option argument.
void SetArgName (char s, const std::string &argname)
Specify name of an option argument.
void AddHelp (char s, const std::string &help)
Specify usage for an option.
void AddHelp (const std::string &l, const std::string &help)
Specify usage for an option.
std::string GetOpStringByType (int mintype, int maxtype)
Obtains option strings by type.
std::string GetHelp (char s)
Obtain the usage string for an option.
std::string GetHelp (const std::string &l)
Obtain the usage string for an option.
char GetShort (const std::string &l)
Obtain the short one char option from the long word version.
std::string GetLong (const char &s)
Obtain the long word option from the short char version.
std::string ShortUsage ()
Generate short usage string.
std::string LongUsage ()
Generate long usage string.
std::string GetOption (const char &s)
Get the value of an option.
std::string GetOption (const std::string &l)
Get the value of an option.
std::string ErrorReport ()
Error reporting.
std::string ProgramName () const
Program name access.
std::vector< std::string > GetArgs () const
Argument access.
void SetDescription (const std::string &desc)
Set description string.
void SetNotes (const std::string &notes)
Set notes string.
void WriteRC (std::ostream &Ostr) const
Write an RC string that can be used for config.
void ReadRC (const std::string &RCString)
Read a config from RC string.
template<typename NumType >
void ProcessRange (NumType &t1, NumType &t2, const std::string stinter)
Process a range in the format "t1:t2".
template<typename NumType >
void ResolveOption (NumType &t2, const std::string stinter)
Resolve an option (i.e.
virtual ~ComLineObject ()
Additional Inherited Members
Public Attributes inherited from vector< T >
T elements
STL member.
Protected Attributes inherited from ComLineObject
std::string _description
application description.
std::string _notes
Notes to be displayed at the end of LongUsage().
std::string _program_name
the name of the program
std::string _line
unformatted command line
std::vector< std::string > _error_messages
stores error messages
std::vector< std::string > _nonops
stores non-option arguments
std::map< char, std::string > _options
stores the value of each option
std::map< char, std::string > _help
stores the help string for each op
std::map< char, std::string > _argname
stores a name for arguments
std::map< char, int > _type
stores the type of option
std::vector< std::pair
< std::string, int > > _args
application arguments;
std::map< std::string,
std::string > _arghelp
help string for args
Detailed Description
The ComLineObject for the example programs.
This comline object implements a basic command-line interface handler for the example programs. These command-line objects handle all of the generation of help messages, command line argument validation, and encapsulation.
Definition at line 74 of file DriverProgram.H.
Constructor & Destructor Documentation
DriverProgramComLine () inline
Definition at line 77 of file DriverProgram.H.
         : IRAD::Util::ComLineObject()
       {};
DriverProgramComLine (const char * args[]) inline
Definition at line 80 of file DriverProgram.H.
         : IRAD::Util::ComLineObject(args)
       {};
Member Function Documentation
void Initialize (void) inline virtual
This is where the actual options and arguments are described.
For details about what can be done in this function, see the documentation for the IRAD::Util::ComLineObject.
Reimplemented from ComLineObject.
Definition at line 89 of file DriverProgram.H.
References ComLineObject::_description, ComLineObject::AddArgHelp(), ComLineObject::AddArgument(), ComLineObject::AddHelp(), and ComLineObject::AddOption().
{
         AddOption('h',"help");
         AddOption('v',"verbosity",1);
         AddOption('o',"output",2,"filename");
         AddArgument("input",1);
         AddHelp("help","Prints this long version of help.");
         AddHelp("output","Specifies the name of the output file.");
         std::ostringstream Ostr;
         Ostr << "Mode-dependent input: Input <filename> for serial example"
              << "\n\t\tprogram, or <number of divisions> for parallel example.";
         AddArgHelp("input",Ostr.str());
         // The following commented string formation is kept around to
         // illustrate the required tabs and newlines to make the output
         // look proper:
         //
         //    Ostr << "Use fixed problem size in scalability analysis.  Only makes"
         //         << "\n\t\tsense when scalability mode is enabled.";
         //    Ostr.str("");
         Ostr.str("");
         Ostr << "Main GridConversion program.";
         _description.assign(Ostr.str());
       };
The documentation for this class was generated from the following file:
DriverProgram.H