Rocstar: CPlane Class Reference
CPlane Class Reference
#include <GeoPrimitives.H>
Public Member Functions
CPlane ()
CPlane (const CPoint &p1, const CPoint &p2, const CPoint &p3)
CPlane (const CVector &N, const CPoint &P)
CPlane (const CPlane &plane)
CPlane (const std::vector< CPoint > &vec)
CPlane & operator= (const CPlane &plane)
double A () const
double B () const
double C () const
double D () const
CVector & normal ()
const CVector & normal () const
CPoint & point ()
const CPoint & point () const
bool contains_point (const CPoint &P) const
bool operator== (const CPlane &plane) const
Protected Attributes
CVector n
CPoint p
Detailed Description
Definition at line 1332 of file GeoPrimitives.H.
Constructor & Destructor Documentation
CPlane () inline
Definition at line 1337 of file GeoPrimitives.H.
 {};
CPlane (const CPoint & p1, const CPoint & p2, const CPoint & p3) inline
Definition at line 1338 of file GeoPrimitives.H.
References CPlane::A(), CPlane::B(), CPlane::C(), CPlane::n, CVector::normalize(), CPoint::x(), CVector::x(), CPoint::y(), and CPoint::z().
       : p(p1)
     {
       double A = p1.y()*(p2.z() - p3.z()) + p2.y()*(p3.z() - p1.z()) +
         p3.y()*(p1.z() - p2.z());
       double B = p1.z()*(p2.x() - p3.x()) + p2.z()*(p3.x() - p1.x()) +
         p3.z()*(p1.x() - p2.x());
       double C = p1.x()*(p2.y() - p3.y()) + p2.x()*(p3.y() - p1.y()) +
         p3.x()*(p1.y() - p2.y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.normalize();
     };
CPlane (const CVector & N, const CPoint & P) inline
Definition at line 1354 of file GeoPrimitives.H.
       : n(N.unit()),p(P)
     {};
CPlane (const CPlane & plane) inline
Definition at line 1357 of file GeoPrimitives.H.
       : n(plane.n),p(plane.p)
     {};
CPlane (const std::vector< CPoint > & vec) inline
Definition at line 1360 of file GeoPrimitives.H.
References CPlane::A(), CPlane::B(), CPlane::C(), CPlane::n, CVector::normalize(), x, CVector::x(), y, and z.
       : p(vec[0])
     {
       double A = vec[0].y()*(vec[1].z() - vec[2].z()) +
         vec[1].y()*(vec[2].z() - vec[0].z()) +
         vec[2].y()*(vec[0].z() - vec[1].z());
       double B = vec[0].z()*(vec[1].x() - vec[2].x()) +
         vec[1].z()*(vec[2].x() - vec[0].x()) +
         vec[2].z()*(vec[0].x() - vec[1].x());
       double C = vec[0].x()*(vec[1].y() - vec[2].y()) +
         vec[1].x()*(vec[2].y() - vec[0].y()) +
         vec[2].x()*(vec[0].y() - vec[1].y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.normalize();
     } ;
Member Function Documentation
double A () const inline
Definition at line 1385 of file GeoPrimitives.H.
References CPlane::n, and CVector::x().
Referenced by CPlane::CPlane().
 { return(n.x()); };
double B () const inline
Definition at line 1386 of file GeoPrimitives.H.
References CPlane::n, and CVector::y().
Referenced by CPlane::CPlane().
 { return(n.y()); };
double C () const inline
Definition at line 1387 of file GeoPrimitives.H.
References CPlane::n, and CVector::z().
Referenced by CPlane::CPlane().
 { return(n.z()); };
bool contains_point (const CPoint & P) const inline
Definition at line 1396 of file GeoPrimitives.H.
References CPlane::D(), CPlane::n, GeoPrim::TOL, CPoint::x(), CVector::x(), CPoint::y(), CVector::y(), CPoint::z(), and CVector::z().
Referenced by CFacet::contains_point(), and CPlane::operator==().
     {
       return(fabs(n.x()*P.x() + n.y()*P.y() + n.z()*P.z() + D()) <= TOL);
     };
double D () const inline
Definition at line 1388 of file GeoPrimitives.H.
References CPlane::n, CPlane::p, CPoint::x(), CVector::x(), CPoint::y(), CVector::y(), CPoint::z(), and CVector::z().
Referenced by CPlane::contains_point().
     {
       return( -1.0 * ( n.x()*p.x() + n.y()*p.y() + n.z()*p.z()));
     };
CVector& normal () inline
Definition at line 1392 of file GeoPrimitives.H.
References CPlane::n.
 { return(n); };
const CVector& normal () const inline
Definition at line 1393 of file GeoPrimitives.H.
References CPlane::n.
 { return(n); };
CPlane& operator= (const CPlane & plane) inline
Definition at line 1379 of file GeoPrimitives.H.
References CPlane::n, and CPlane::p.
     {
       n = plane.n;
       p = plane.p;
       return(*this);
     };
bool operator== (const CPlane & plane) const inline
Definition at line 1400 of file GeoPrimitives.H.
References CPlane::contains_point(), CPlane::n, CPlane::p, and CVector::unit().
     {
       return((plane.n.unit() == n.unit()) && contains_point(plane.p));
     };
CPoint& point () inline
Definition at line 1394 of file GeoPrimitives.H.
References CPlane::p.
 { return(p); };
const CPoint& point () const inline
Definition at line 1395 of file GeoPrimitives.H.
References CPlane::p.
 { return(p); };
Member Data Documentation
CVector n protected
Definition at line 1334 of file GeoPrimitives.H.
Referenced by CPlane::A(), CPlane::B(), CPlane::C(), CPlane::contains_point(), CPlane::CPlane(), CPlane::D(), CPlane::normal(), CPlane::operator=(), and CPlane::operator==().
CPoint p protected
Definition at line 1335 of file GeoPrimitives.H.
Referenced by CPlane::D(), CPlane::operator=(), CPlane::operator==(), and CPlane::point().
The documentation for this class was generated from the following file:
GeoPrimitives.H