Rocstar: In_place_list_n< T, managed > Class Template Reference
In_place_list_n< T, managed > Class Template Reference
#include <In_place_list_n.h>
Public Types
typedef T value_type
typedef T * pointer
typedef const T * const_pointer
typedef T & reference
typedef const T & const_reference
typedef std::size_t size_type
typedef std::ptrdiff_t difference_type
typedef
_In_place_list_n_iterator< T > iterator
typedef
_In_place_list_n_iterator
< const T > const_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef In_place_list_n< T,
managed > Self
Public Member Functions
In_place_list_n (int d=0)
void set_dimension (int d)
void swap (Self &x)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
bool empty () const
size_type size () const
size_type max_size () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
iterator insert (iterator position, T &x)
iterator insert (T *pos, T &x)
void push_front (T &x)
void push_back (T &x)
void insert (iterator position, size_type n)
void insert (iterator position, size_type n, const T &x)
void insert (T *pos, size_type n)
void insert (T *pos, size_type n, const T &x=T())
template<class InputIterator >
void insert (iterator pos, InputIterator first, InputIterator last)
template<class InputIterator >
void insert (T *pos, InputIterator first, InputIterator last)
void insert (T *pos, const T *first, const T *last)
void erase (iterator i)
void erase (T *pos)
void pop_front ()
void pop_back ()
void erase (iterator first, iterator last)
void erase (T *first, T *last)
void clear ()
In_place_list_n (size_type n, const T &value, int d=0)
template<class InputIterator >
In_place_list_n (InputIterator first, InputIterator last, int d=0)
In_place_list_n (const T *first, const T *last, int d=0)
In_place_list_n (const Self &x)
~In_place_list_n ()
Self & operator= (const Self &x)
void destroy ()
template<class InputIterator >
void assign (InputIterator first, InputIterator last)
void assign (size_type n, const T &t)
void resize (size_type sz, T c=T())
bool operator== (const Self &y) const
bool operator!= (const Self &y) const
bool operator< (const Self &y) const
bool operator> (const Self &i) const
bool operator<= (const Self &i) const
bool operator>= (const Self &i) const
void splice (iterator position, Self &x)
void splice (T *position, Self &x)
void splice (iterator position, Self &x, iterator i)
void splice (T *position, Self &x, T *i)
void splice (iterator pos, Self &x, iterator first, iterator last)
void splice (T *p, Self &x, T *first, T *last)
void remove (const T &value)
void reverse ()
void unique ()
void merge (Self &x)
void sort ()
Protected Member Functions
T * get_node ()
T * get_node (const T &t)
void put_node (T *p)
void transfer (iterator position, iterator first, iterator last)
Protected Attributes
T * node
std::size_t length
int dim
Detailed Description
template<class T, bool managed = false>
class In_place_list_n< T, managed >
Definition at line 100 of file In_place_list_n.h.
Member Typedef Documentation
typedef _In_place_list_n_iterator<const T> const_iterator
Definition at line 235 of file In_place_list_n.h.
typedef const T* const_pointer
Definition at line 228 of file In_place_list_n.h.
typedef const T& const_reference
Definition at line 230 of file In_place_list_n.h.
typedef std::reverse_iterator<const_iterator> const_reverse_iterator
Definition at line 238 of file In_place_list_n.h.
typedef std::ptrdiff_t difference_type
Definition at line 232 of file In_place_list_n.h.
typedef _In_place_list_n_iterator<T> iterator
Definition at line 234 of file In_place_list_n.h.
typedef T* pointer
Definition at line 227 of file In_place_list_n.h.
typedef T& reference
Definition at line 229 of file In_place_list_n.h.
typedef std::reverse_iterator<iterator> reverse_iterator
Definition at line 237 of file In_place_list_n.h.
typedef In_place_list_n<T,managed> Self
Definition at line 240 of file In_place_list_n.h.
typedef std::size_t size_type
Definition at line 231 of file In_place_list_n.h.
typedef T value_type
Definition at line 226 of file In_place_list_n.h.
Constructor & Destructor Documentation
In_place_list_n (int d = 0) inline explicit
Definition at line 246 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, In_place_list_n< T, managed >::get_node(), and In_place_list_n< T, managed >::node.
                                      : length(0), dim(d) {
     // introduces an empty list.
     node = get_node();
     (*node).next_link[dim] = node;
     (*node).prev_link[dim] = node;
   }
In_place_list_n (size_type n, const T & value, int d = 0) inline explicit
Definition at line 370 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::dim, In_place_list_n< T, managed >::get_node(), In_place_list_n< T, managed >::insert(), and In_place_list_n< T, managed >::node.
                                                                  : length(0), dim(d) {
     // introduces a list with n items, all initialized with copies of
     // value.
     node = get_node();
     (*node).next_link[dim] = node;
     (*node).prev_link[dim] = node;
     insert(begin(), n, value);
   }
In_place_list_n (InputIterator first, InputIterator last, int d = 0) inline
Definition at line 380 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::dim, In_place_list_n< T, managed >::get_node(), In_place_list_n< T, managed >::insert(), and In_place_list_n< T, managed >::node.
                                                                      : length(0), dim(d) {
     // a list with copies from the range [`first,last').
     node = get_node();
     (*node).next_link[dim] = node;
     (*node).prev_link[dim] = node;
     insert( begin(), first, last);
   }
In_place_list_n (const T * first, const T * last, int d = 0) inline
Definition at line 388 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::dim, In_place_list_n< T, managed >::get_node(), In_place_list_n< T, managed >::insert(), and In_place_list_n< T, managed >::node.
                                                           : length(0), dim(d) {
     // a list with copies from the range [`first,last').
     node = get_node();
     (*node).next_link[dim] = node;
     (*node).prev_link[dim] = node;
     insert(begin(), first, last);
   }
In_place_list_n (const Self & x) inline
Definition at line 395 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::dim, In_place_list_n< T, managed >::end(), In_place_list_n< T, managed >::get_node(), In_place_list_n< T, managed >::insert(), and In_place_list_n< T, managed >::node.
                                  : length(0), dim(x.dim) {
     // copy constructor. Each item in `l1' is copied.
     node = get_node();
     (*node).next_link[dim] = node;
     (*node).prev_link[dim] = node;
     insert(begin(), x.begin(), x.end());
   }
~In_place_list_n () inline
Definition at line 402 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::end(), In_place_list_n< T, managed >::erase(), and In_place_list_n< T, managed >::put_node().
                      {
     erase(begin(), end());
     put_node(node);
   }
Member Function Documentation
void assign (InputIterator first, InputIterator last) inline
Definition at line 412 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::end(), In_place_list_n< T, managed >::erase(), and In_place_list_n< T, managed >::insert().
{
     erase( begin(), end());
     insert( begin(), first, last);
   }
void assign (size_type n, const T & t) inline
Definition at line 417 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::end(), In_place_list_n< T, managed >::erase(), and In_place_list_n< T, managed >::insert().
{
     erase( begin(), end());
     insert( begin(), n, t);
   }
reference back () inline
Definition at line 282 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim.
Referenced by Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::project_adjacent_green_vertices(), and Overlay::verify_inode().
 { return *node->prev_link[dim]; }
const_reference back () const inline
Definition at line 283 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim.
 { return *node->prev_link[dim]; }
iterator begin () inline
Definition at line 262 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim.
Referenced by In_place_list_n< T, managed >::assign(), Overlay::associate_green_vertices(), In_place_list_n< T, managed >::clear(), In_place_list_n< T, managed >::front(), Overlay::get_inodes_of_face(), In_place_list_n< T, managed >::In_place_list_n(), Overlay::intersect_blue_with_green(), In_place_list_n< T, managed >::merge(), In_place_list_n< T, managed >::operator!=(), In_place_list_n< T, managed >::operator<(), In_place_list_n< T, managed >::operator=(), In_place_list_n< T, managed >::operator==(), In_place_list_n< T, managed >::pop_front(), In_place_list_n< T, managed >::push_front(), In_place_list_n< T, managed >::rend(), In_place_list_n< T, managed >::resize(), In_place_list_n< T, managed >::sort(), Overlay::sort_on_green_edges(), In_place_list_n< T, managed >::splice(), and In_place_list_n< T, managed >::~In_place_list_n().
 { return iterator(node->next_link[dim],dim); }
const_iterator begin () const inline
Definition at line 263 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim.
 { return const_iterator(node->next_link[dim],dim); }
void clear () inline
Definition at line 366 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::end(), and In_place_list_n< T, managed >::erase().
 { erase( begin(), end()); }
void destroy ()
Definition at line 588 of file In_place_list_n.h.
References i, Mesquite::length(), and _In_place_list_n_iterator< T >::node.
           {
   iterator first = begin();
   iterator last  = end();
   while( first != last) {
     iterator i = first++;
     put_node(i.node);
   }
   length = 0;
   (*node).next_link[dim] = node;
   (*node).prev_link[dim] = node;
 }
bool empty () const inline
Definition at line 276 of file In_place_list_n.h.
References In_place_list_n< T, managed >::length.
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), In_place_list_n< T, managed >::splice(), and Overlay::verify_inode().
 { return length == 0; }
iterator end () inline
Definition at line 264 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim.
Referenced by In_place_list_n< T, managed >::assign(), Overlay::associate_green_vertices(), In_place_list_n< T, managed >::clear(), Overlay::get_inodes_of_face(), In_place_list_n< T, managed >::In_place_list_n(), Overlay::intersect_blue_with_green(), In_place_list_n< T, managed >::merge(), In_place_list_n< T, managed >::operator!=(), In_place_list_n< T, managed >::operator<(), In_place_list_n< T, managed >::operator=(), In_place_list_n< T, managed >::operator==(), In_place_list_n< T, managed >::pop_back(), In_place_list_n< T, managed >::push_back(), In_place_list_n< T, managed >::rbegin(), In_place_list_n< T, managed >::resize(), Overlay::sort_on_green_edges(), In_place_list_n< T, managed >::splice(), and In_place_list_n< T, managed >::~In_place_list_n().
 { return iterator(node,dim); }
const_iterator end () const inline
Definition at line 265 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim.
 { return const_iterator(node,dim); }
void erase (iterator i) inline
Definition at line 339 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, In_place_list_n< T, managed >::length, _In_place_list_n_iterator< T >::node, In_place_list_n< T, managed >::put_node(), and RFC_assertion.
Referenced by In_place_list_n< T, managed >::assign(), In_place_list_n< T, managed >::clear(), In_place_list_n< T, managed >::erase(), In_place_list_n< T, managed >::pop_back(), In_place_list_n< T, managed >::pop_front(), In_place_list_n< T, managed >::resize(), and In_place_list_n< T, managed >::~In_place_list_n().
{
     // removes the item from list `l', where `pos' refers to.
     RFC_assertion( length > 0);
     (*((*i.node).prev_link[dim])).next_link[dim] = (*i.node).next_link[dim];
     (*((*i.node).next_link[dim])).prev_link[dim] = (*i.node).prev_link[dim];
     if (managed)
       put_node(i.node);
     --length;
   }
void erase (T * pos) inline
Definition at line 348 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, and In_place_list_n< T, managed >::erase().
Referenced by In_place_list_n< T, managed >::erase().
 { erase( iterator( pos,dim)); }
void erase (iterator first, iterator last)
Definition at line 552 of file In_place_list_n.h.
{
   while (first != last)
     erase(first++);
 }
void erase (T * first, T * last) inline
Definition at line 362 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, and In_place_list_n< T, managed >::erase().
{
     erase( iterator(first,dim), iterator(last,dim));
   }
reference front () inline
Definition at line 280 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin().
Referenced by Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::project_adjacent_green_vertices(), and Overlay::verify_inode().
 { return *begin(); }
const_reference front () const inline
Definition at line 281 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin().
 { return *begin(); }
T* get_node () inline protected
Definition at line 185 of file In_place_list_n.h.
Referenced by In_place_list_n< T, managed >::In_place_list_n(), and In_place_list_n< T, managed >::insert().
 { return new T;}
T* get_node (const T & t) inline protected
Definition at line 186 of file In_place_list_n.h.
 { return new T(t);}
iterator insert (iterator position, T & x) inline
Definition at line 287 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, In_place_list_n< T, managed >::length, and _In_place_list_n_iterator< T >::node.
Referenced by In_place_list_n< T, managed >::assign(), In_place_list_n< T, managed >::In_place_list_n(), In_place_list_n< T, managed >::insert(), In_place_list_n< T, managed >::push_back(), In_place_list_n< T, managed >::push_front(), and In_place_list_n< T, managed >::resize().
{
     // inserts `t' in front of iterator `pos'. The return value points
     // to the inserted item.
     x.next_link[dim] = position.node;
     x.prev_link[dim] = (*position.node).prev_link[dim];
     (*((*position.node).prev_link[dim])).next_link[dim] = &x;
     (*position.node).prev_link[dim] = &x;
     ++length;
     return iterator(&x,dim);
   }
iterator insert (T * pos, T & x) inline
Definition at line 297 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, and In_place_list_n< T, managed >::insert().
{
     return insert( iterator(pos,dim), x);
   }
void insert (iterator position, size_type n)
Definition at line 538 of file In_place_list_n.h.
{
   while (n--)
     insert(position, *get_node());
 }
void insert (iterator position, size_type n, const T & x)
Definition at line 545 of file In_place_list_n.h.
{
   while (n--)
     insert(position, *get_node(x));
 }
void insert (T * pos, size_type n) inline
Definition at line 312 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, and In_place_list_n< T, managed >::insert().
Referenced by In_place_list_n< T, managed >::insert().
 { insert( iterator(pos,dim), n); }
void insert (T * pos, size_type n, const T & x = T()) inline
Definition at line 313 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, In_place_list_n< T, managed >::insert(), and x.
{
     insert( iterator(pos,dim), n, x);
   }
void insert (iterator pos, InputIterator first, InputIterator last) inline
Definition at line 318 of file In_place_list_n.h.
References In_place_list_n< T, managed >::get_node(), and In_place_list_n< T, managed >::insert().
{
     // inserts the range [`first, last') in front of iterator `pos'.
     while (first != last)
       insert(pos, *get_node(*first++));
   }
void insert (T * pos, InputIterator first, InputIterator last) inline
Definition at line 325 of file In_place_list_n.h.
References In_place_list_n< T, managed >::get_node(), and In_place_list_n< T, managed >::insert().
{
     // inserts the range [`first, last') in front of iterator `pos'.
     while (first != last)
       insert(pos, *get_node(*first++));
   }
void insert (T * pos, const T * first, const T * last) inline
Definition at line 331 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, and In_place_list_n< T, managed >::insert().
{
     insert( iterator(pos,dim), const_iterator(first,dim),
             const_iterator(last,dim));
   }
size_type max_size () const inline
Definition at line 278 of file In_place_list_n.h.
 { return size_type(-1); }
void merge (Self & x)
Definition at line 638 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::end(), In_place_list_n< T, managed >::length, and Mesquite::length().
Referenced by In_place_list_n< T, managed >::sort().
{
   iterator first1 = begin();
   iterator last1 = end();
   iterator first2 = x.begin();
   iterator last2 = x.end();
   while (first1 != last1 && first2 != last2)
     if (*first2 < *first1) {
       iterator next = first2;
       transfer(first1, first2, ++next);
       first2 = next;
     } else
       ++first1;
   if (first2 != last2)
     transfer(last1, first2, last2);
   length += x.length;
   x.length= 0;
 }
bool operator!= (const Self & y) const inline
Definition at line 439 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::end(), equal(), and In_place_list_n< T, managed >::size().
{
     return size() != y.size() || ! std::equal(begin(),end(),y.begin());
   }
bool operator< (const Self & y) const inline
Definition at line 443 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), and In_place_list_n< T, managed >::end().
{
     return std::lexicographical_compare( begin(),end(),
                                          y.begin(),y.end());
   }
bool operator<= (const Self & i) const inline
Definition at line 448 of file In_place_list_n.h.
 { return !(i < *this); }
In_place_list_n< T, managed > & operator= (const Self & x)
Definition at line 561 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::dim, and In_place_list_n< T, managed >::end().
{
   if (this != &x) {
     dim = x.dim;
     iterator first1 = begin();
     iterator last1  = end();
     const_iterator first2 = x.begin();
     const_iterator last2  = x.end();
     while (first1 != last1 && first2 != last2) {
       // Save the pointer values before assignment.
       // Assignment avoids unneccassary delete's and new's.
       T* tmp1 = (*first1).next_link[dim];
       T* tmp2 = (*first1).prev_link[dim];
       *first1 = *first2++;
       (*first1).next_link[dim] = tmp1;
       (*first1).prev_link[dim] = tmp2;
       ++first1;
     }
     if (first2 == last2)
       erase(first1, last1);
     else
       insert(last1, first2, last2);
   }
   return *this;
 }
bool operator== (const Self & y) const inline
Definition at line 435 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::end(), equal(), and In_place_list_n< T, managed >::size().
{
     return size() == y.size() && std::equal(begin(), end(), y.begin());
   }
bool operator> (const Self & i) const inline
Definition at line 447 of file In_place_list_n.h.
 { return i < *this; }
bool operator>= (const Self & i) const inline
Definition at line 449 of file In_place_list_n.h.
References i.
 { return !(*this < i); }
void pop_back () inline
Definition at line 353 of file In_place_list_n.h.
References In_place_list_n< T, managed >::end(), and In_place_list_n< T, managed >::erase().
Referenced by Overlay::insert_node_in_blue_edge().
                   {
     // removes the last item from list `l'.
     iterator tmp = end();
     erase(--tmp);
   }
void pop_front () inline
Definition at line 350 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), and In_place_list_n< T, managed >::erase().
Referenced by Overlay::insert_node_in_blue_edge(), and Overlay::intersect_blue_with_green().
 { erase(begin()); }
void push_back (T & x) inline
Definition at line 303 of file In_place_list_n.h.
References In_place_list_n< T, managed >::end(), and In_place_list_n< T, managed >::insert().
Referenced by Overlay::sort_on_green_edges().
 { insert(end(), x); }
void push_front (T & x) inline
Definition at line 300 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), and In_place_list_n< T, managed >::insert().
Referenced by Overlay::intersect_blue_with_green().
 { insert(begin(), x); }
void put_node (T * p) inline protected
Definition at line 187 of file In_place_list_n.h.
Referenced by In_place_list_n< T, managed >::erase(), and In_place_list_n< T, managed >::~In_place_list_n().
 { delete p;}
reverse_iterator rbegin () inline
Definition at line 267 of file In_place_list_n.h.
References In_place_list_n< T, managed >::end().
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), and Overlay::sort_on_green_edges().
 { return reverse_iterator(end()); }
const_reverse_iterator rbegin () const inline
Definition at line 268 of file In_place_list_n.h.
References In_place_list_n< T, managed >::end().
{
     return const_reverse_iterator(end());
   }
void remove (const T & value)
Definition at line 601 of file In_place_list_n.h.
{
   iterator first = begin();
   iterator last = end();
   while (first != last) {
     iterator next = first;
     ++next;
     if (*first == value)
       erase(first);
     first = next;
   }
 }
reverse_iterator rend () inline
Definition at line 271 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin().
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), and Overlay::sort_on_green_edges().
 { return reverse_iterator(begin()); }
const_reverse_iterator rend () const inline
Definition at line 272 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin().
{
     return const_reverse_iterator(begin());
   }
void resize (size_type sz, T c = T()) inline
Definition at line 422 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::end(), In_place_list_n< T, managed >::erase(), i, In_place_list_n< T, managed >::insert(), and In_place_list_n< T, managed >::size().
{
     if ( sz > size())
       insert( end(), sz - size(), c);
     else if ( sz < size()) {
       iterator i = begin();
       while ( sz-- > 0)
         ++i;
       erase( i, end());
     }  // else do nothing
   }
void reverse ()
Definition at line 614 of file In_place_list_n.h.
{
   if (size() < 2) return;
   for (iterator first = ++begin(); first != end();) {
     iterator old = first++;
     transfer(begin(), old, first);
   }
 }
void set_dimension (int d) inline
Definition at line 252 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim.
 { dim = d; }
size_type size () const inline
Definition at line 277 of file In_place_list_n.h.
References In_place_list_n< T, managed >::length.
Referenced by In_place_list_n< T, managed >::operator!=(), In_place_list_n< T, managed >::operator==(), Overlay::project_adjacent_green_vertices(), In_place_list_n< T, managed >::resize(), and Overlay::verify_inode().
 { return length; }
void sort ()
Definition at line 657 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), empty(), i, merge, In_place_list_n< T, managed >::merge(), In_place_list_n< T, managed >::splice(), swap(), and In_place_list_n< T, managed >::swap().
{
   if (size() < 2) return;
   In_place_list_n<T,managed> carry;
   In_place_list_n<T,managed> counter[64];
   int fill = 0;
   while (!empty()) {
     carry.splice(carry.begin(), *this, begin());
     int i = 0;
     while(i < fill && !counter[i].empty()) {
       counter[i].merge(carry);
       carry.swap(counter[i++]);
     }
     carry.swap(counter[i]);
     if (i == fill)
       ++fill;
   }
   for (int i = 1; i < fill; ++i)
     counter[i].merge(counter[i-1]);
   swap(counter[fill-1]);
 }
void splice (iterator position, Self & x) inline
Definition at line 466 of file In_place_list_n.h.
References In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::empty(), In_place_list_n< T, managed >::end(), In_place_list_n< T, managed >::length, and In_place_list_n< T, managed >::transfer().
Referenced by In_place_list_n< T, managed >::sort(), and In_place_list_n< T, managed >::splice().
{
     // inserts the list x before position `pos' and x becomes empty.
     // It takes constant time. Precondition: `&l != &x'.
     if (!x.empty()) {
       transfer(position, x.begin(), x.end());
       length += x.length;
       x.length = 0;
     }
   }
void splice (T * position, Self & x) inline
Definition at line 475 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, and In_place_list_n< T, managed >::splice().
{
     splice( iterator(position,dim), x);
   }
void splice (iterator position, Self & x, iterator i) inline
Definition at line 478 of file In_place_list_n.h.
References i, j, In_place_list_n< T, managed >::length, and In_place_list_n< T, managed >::transfer().
{
     // inserts an element pointed to by i from list x before position
     // `pos' and removes the element from x. It takes constant time. i
     // is a valid dereferenceable iterator of x. The result is
     // unchanged if `pos == i' or `pos == ++i'.
     iterator j = i;
     if (position == i || position == ++j) return;
     transfer(position, i, j);
     ++length;
     --x.length;
   }
void splice (T * position, Self & x, T * i) inline
Definition at line 489 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, and In_place_list_n< T, managed >::splice().
{
     splice( iterator(position,dim), x, iterator(i,dim));
   }
void splice (iterator pos, Self & x, iterator first, iterator last) inline
Definition at line 492 of file In_place_list_n.h.
References In_place_list_n< T, managed >::length, and In_place_list_n< T, managed >::transfer().
{
     // inserts elements in the range [`first, last') before position
     // `pos' and removes the elements from x. It takes constant time
     // if `&x == $l'; otherwise, it takes linear time. [`first,
     // last') is a valid range in x. Precondition: `pos' is not in the
     // range [`first, last').
     if (first != last) {
       if (&x != this) {
         difference_type n = 0;
         std::distance(first, last, n);
         x.length -= n;
         length += n;
       }
       transfer(pos, first, last);
     }
   }
void splice (T * p, Self & x, T * first, T * last) inline
Definition at line 508 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, and In_place_list_n< T, managed >::splice().
{
     splice( iterator(p,dim), x, iterator(first,dim), iterator(last,dim));
   }
void swap (Self & x) inline
Definition at line 254 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, In_place_list_n< T, managed >::length, In_place_list_n< T, managed >::node, and swap().
Referenced by In_place_list_n< T, managed >::sort().
                      {
     std::swap(node, x.node);
     std::swap(length, x.length);
     std::swap(dim, x.dim);
   }
void transfer (iterator position, iterator first, iterator last) inline protected
Definition at line 454 of file In_place_list_n.h.
References In_place_list_n< T, managed >::dim, and _In_place_list_n_iterator< T >::node.
Referenced by In_place_list_n< T, managed >::splice().
{
     // move the range [`first, last') before the position.
     (*((*last.node).prev_link[dim])).next_link[dim] = position.node;
     (*((*first.node).prev_link[dim])).next_link[dim] = last.node;
     (*((*position.node).prev_link[dim])).next_link[dim] = first.node;
     T* tmp = (*position.node).prev_link[dim];
     (*position.node).prev_link[dim] = (*last.node).prev_link[dim];
     (*last.node).prev_link[dim] = (*first.node).prev_link[dim];
     (*first.node).prev_link[dim] = tmp;
   }
void unique ()
Definition at line 623 of file In_place_list_n.h.
{
   iterator first = begin();
   iterator last = end();
   if (first == last) return;
   iterator next = first;
   while (++next != last) {
     if (*first == *next)
       erase(next);
     else
       first = next;
     next = first;
   }
 }
Member Data Documentation
int dim protected
Definition at line 183 of file In_place_list_n.h.
Referenced by In_place_list_n< T, managed >::back(), In_place_list_n< T, managed >::begin(), In_place_list_n< T, managed >::end(), In_place_list_n< T, managed >::erase(), In_place_list_n< T, managed >::In_place_list_n(), In_place_list_n< T, managed >::insert(), In_place_list_n< T, managed >::operator=(), In_place_list_n< T, managed >::set_dimension(), In_place_list_n< T, managed >::splice(), In_place_list_n< T, managed >::swap(), and In_place_list_n< T, managed >::transfer().
std::size_t length protected
Definition at line 182 of file In_place_list_n.h.
Referenced by In_place_list_n< T, managed >::empty(), In_place_list_n< T, managed >::erase(), In_place_list_n< T, managed >::insert(), In_place_list_n< T, managed >::merge(), In_place_list_n< T, managed >::size(), In_place_list_n< T, managed >::splice(), and In_place_list_n< T, managed >::swap().
T* node protected
Definition at line 181 of file In_place_list_n.h.
Referenced by In_place_list_n< T, managed >::In_place_list_n(), and In_place_list_n< T, managed >::swap().
The documentation for this class was generated from the following file:
In_place_list_n.h