Rocstar: Aff_transformationS3< FT > Class Template Reference
Aff_transformationS3< FT > Class Template Reference
#include <Aff_transformationS3.h>
Public Member Functions
Aff_transformationS3 ()
Aff_transformationS3 (const Identity_transformation &)
Aff_transformationS3 (const Translation, const VectorS3< FT > &v)
Aff_transformationS3 (const Scaling, const FT &s, const FT &w=FT(1))
Aff_transformationS3 (const FT &m11, const FT &m12, const FT &m13, const FT &m21, const FT &m22, const FT &m23, const FT &m31, const FT &m32, const FT &m33, const FT &w=FT(1))
Aff_transformationS3 (const FT &m11, const FT &m12, const FT &m13, const FT &m14, const FT &m21, const FT &m22, const FT &m23, const FT &m24, const FT &m31, const FT &m32, const FT &m33, const FT &m34, const FT &w=FT(1))
~Aff_transformationS3 ()
PointS3< FT > transform (const PointS3< FT > &p) const
PointS3< FT > operator() (const PointS3< FT > &p) const
VectorS3< FT > transform (const VectorS3< FT > &v) const
VectorS3< FT > operator() (const VectorS3< FT > &v) const
DirectionS3< FT > transform (const DirectionS3< FT > &d) const
DirectionS3< FT > operator() (const DirectionS3< FT > &d) const
PlaneS3< FT > transform (const PlaneS3< FT > &p) const
PlaneS3< FT > operator() (const PlaneS3< FT > &p) const
Aff_transformationS3< FT > inverse () const
Aff_transformationS3< FT > transpose () const
Aff_transformationS3< FT > general_form () const
bool is_even () const
bool is_odd () const
FT cartesian (int i, int j) const
FT homogeneous (int i, int j) const
FT m (int i, int j) const
FT hm (int i, int j) const
Private Member Functions
Aff_transformation_rep_baseS3
< FT > * ptr () const
Friends
std::ostream & operator<< CGAL_NULL_TMPL_ARGS (std::ostream &os, const Aff_transformationS3< FT > &t)
Aff_transformationS3< FT >
_general_transformation_composition CGAL_NULL_TMPL_ARGS (Aff_transformation_repS3< FT > &l, Aff_transformation_repS3< FT > &r)
Aff_transformationS3< FT > operator*CGAL_NULL_TMPL_ARGS (const Aff_transformationS3< FT > &a, const Aff_transformationS3< FT > &b)
Detailed Description
template<class FT>
class Aff_transformationS3< FT >
Definition at line 65 of file Aff_transformationS3.h.
Constructor & Destructor Documentation
Aff_transformationS3 ()
Definition at line 569 of file Aff_transformationS3.h.
 {
   FT ft1(1), ft0(0);
   PTR = new Aff_transformation_repS3<FT>(ft1, ft0, ft0,
                                          ft0, ft1, ft0,
                                          ft0, ft0, ft1);
 }
Aff_transformationS3 (const Identity_transformation &)
Definition at line 578 of file Aff_transformationS3.h.
 {
   FT ft1(1), ft0(0);
   PTR = new Aff_transformation_repS3<FT>(ft1, ft0, ft0,
                                          ft0, ft1, ft0,
                                          ft0, ft0, ft1);
 }
Aff_transformationS3 (const Translation , const VectorS3< FT > & v)
Definition at line 587 of file Aff_transformationS3.h.
References v.
 {
   PTR = new Translation_repS3<FT>(v);
 }
Aff_transformationS3 (const Scaling , const FT & s, const FT & w = FT(1))
Definition at line 594 of file Aff_transformationS3.h.
References s.
 {
   if (w != FT(1))
     PTR = new Scaling_repS3<FT>(s/w);
   else
     PTR = new Scaling_repS3<FT>(s);
 }
Aff_transformationS3 (const FT & m11, const FT & m12, const FT & m13, const FT & m21, const FT & m22, const FT & m23, const FT & m31, const FT & m32, const FT & m33, const FT & w = FT(1))
Definition at line 625 of file Aff_transformationS3.h.
 {
   if (w != FT(1))
   PTR = new Aff_transformation_repS3<FT>(m11/w, m12/w, m13/w,
                                           m21/w, m22/w, m23/w,
                                           m31/w, m32/w, m33/w);
   else
     PTR = new Aff_transformation_repS3<FT>(m11, m12, m13,
                                             m21, m22, m23,
                                             m31, m32, m33);
 }
Aff_transformationS3 (const FT & m11, const FT & m12, const FT & m13, const FT & m14, const FT & m21, const FT & m22, const FT & m23, const FT & m24, const FT & m31, const FT & m32, const FT & m33, const FT & m34, const FT & w = FT(1))
Definition at line 606 of file Aff_transformationS3.h.
 {
   if (w != FT(1))
   PTR = new Aff_transformation_repS3<FT>(m11/w, m12/w, m13/w, m14/w,
                                           m21/w, m22/w, m23/w, m24/w,
                                           m31/w, m32/w, m33/w, m34/w);
   else
     PTR = new Aff_transformation_repS3<FT>(m11, m12, m13, m14,
                                             m21, m22, m23, m24,
                                             m31, m32, m33, m34);
 }
~Aff_transformationS3 ()
Definition at line 642 of file Aff_transformationS3.h.
 {}
Member Function Documentation
FT cartesian (int i, int j) const inline
Definition at line 556 of file Aff_transformationS3.h.
References Aff_transformationS3< FT >::ptr().
Referenced by Aff_transformationS3< FT >::hm(), Aff_transformationS3< FT >::homogeneous(), and Aff_transformationS3< FT >::m().
 { return ptr()->cartesian(i,j); }
Aff_transformationS3< FT > general_form () const
Definition at line 715 of file Aff_transformationS3.h.
Referenced by operator*().
 {
   return ptr()->general_form();
 }
FT hm (int i, int j) const inline
Definition at line 559 of file Aff_transformationS3.h.
References Aff_transformationS3< FT >::cartesian().
 { return cartesian(i,j); }
FT homogeneous (int i, int j) const inline
Definition at line 557 of file Aff_transformationS3.h.
References Aff_transformationS3< FT >::cartesian().
 { return cartesian(i,j); }
Aff_transformationS3< FT > inverse () const
Definition at line 708 of file Aff_transformationS3.h.
 {
   return ptr()->inverse();
 }
bool is_even () const
Definition at line 727 of file Aff_transformationS3.h.
Referenced by PlaneS3< FT >::transform().
 {
   return ptr()->is_even();
 }
bool is_odd () const
Definition at line 733 of file Aff_transformationS3.h.
 {
   return ! (ptr()->is_even());
 }
FT m (int i, int j) const inline
Definition at line 558 of file Aff_transformationS3.h.
References Aff_transformationS3< FT >::cartesian().
 { return cartesian(i,j); }
PointS3< FT > operator() (const PointS3< FT > & p) const inline
Definition at line 652 of file Aff_transformationS3.h.
 {
   return transform(p);
 }
VectorS3< FT > operator() (const VectorS3< FT > & v) const inline
Definition at line 668 of file Aff_transformationS3.h.
 {
   return transform(v);
 }
DirectionS3< FT > operator() (const DirectionS3< FT > & d) const inline
Definition at line 684 of file Aff_transformationS3.h.
 {
   return transform(d);
 }
PlaneS3< FT > operator() (const PlaneS3< FT > & p) const inline
Definition at line 701 of file Aff_transformationS3.h.
 {
   return transform(p);
 }
Aff_transformation_rep_baseS3<FT>* ptr () const inline private
Definition at line 562 of file Aff_transformationS3.h.
Referenced by Aff_transformationS3< FT >::cartesian().
     {
       return  (Aff_transformation_rep_baseS3<FT>*)PTR;
     }
PointS3< FT > transform (const PointS3< FT > & p) const
Definition at line 645 of file Aff_transformationS3.h.
Referenced by DirectionS3< FT >::transform(), RayS3< FT >::transform(), LineS3< FT >::transform(), SegmentS3< FT >::transform(), VectorS3< FT >::transform(), PlaneS3< FT >::transform(), and PointS3< FT >::transform().
 {
   return ptr()->transform(p);
 }
VectorS3< FT > transform (const VectorS3< FT > & v) const inline
Definition at line 660 of file Aff_transformationS3.h.
 {
   return ptr()->transform(v);
 }
DirectionS3< FT > transform (const DirectionS3< FT > & d) const inline
Definition at line 676 of file Aff_transformationS3.h.
 {
   return ptr()->transform(d);
 }
PlaneS3< FT > transform (const PlaneS3< FT > & p) const inline
Definition at line 693 of file Aff_transformationS3.h.
References PlaneS3< FT >::transform().
 {
   return p.transform(*this);
 }
Aff_transformationS3< FT > transpose () const
Definition at line 721 of file Aff_transformationS3.h.
Referenced by PlaneS3< FT >::transform().
 {
   return ptr()->transpose();
 }
Friends And Related Function Documentation
Aff_transformationS3<FT> _general_transformation_composition CGAL_NULL_TMPL_ARGS (Aff_transformation_repS3< FT > & l, Aff_transformation_repS3< FT > & r) friend
Aff_transformationS3<FT> operator*CGAL_NULL_TMPL_ARGS (const Aff_transformationS3< FT > & a, const Aff_transformationS3< FT > & b) friend
std::ostream& operator<< CGAL_NULL_TMPL_ARGS (std::ostream & os, const Aff_transformationS3< FT > & t) friend
The documentation for this class was generated from the following file:
Aff_transformationS3.h