Rocstar: rflu_modrelatedpatches Module Reference
rflu_modrelatedpatches Module Reference
Public Member Functions
subroutine, public rflu_relp_transformvector (pRegion, pPatch, vx, vy, vz)
subroutine, public rflu_relp_transformwrapper (pRegion)
Private Member Functions
subroutine rflu_relp_periodicwrapper (pRegion, pPatch)
subroutine rflu_relp_symmetrywrapper (pRegion, pPatch)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRelatedPatches.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file RFLU_ModRelatedPatches.F90.
Member Function/Subroutine Documentation
subroutine rflu_relp_periodicwrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 91 of file RFLU_ModRelatedPatches.F90.
References cos, moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), sin, and v.
Referenced by rflu_relp_transformwrapper().
subroutine rflu_relp_symmetrywrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 237 of file RFLU_ModRelatedPatches.F90.
References moderror::deregisterfunction(), moderror::errorstop(), reflectvector(), and moderror::registerfunction().
Referenced by rflu_relp_transformwrapper().
subroutine, public rflu_relp_transformvector (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, real(rfreal), intent(inout) vx, real(rfreal), intent(inout) vy, real(rfreal), intent(inout) vz)
Definition at line 353 of file RFLU_ModRelatedPatches.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and v.
Referenced by plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), and plag_rflu_modfindcells::plag_rflu_findcellstrajsafe().
subroutine, public rflu_relp_transformwrapper (type(t_region), pointer pRegion)
Definition at line 437 of file RFLU_ModRelatedPatches.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_relp_periodicwrapper(), and rflu_relp_symmetrywrapper().
Referenced by rflu_explicitmultistage(), rflu_initflowsolver(), and rungekuttamp().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRelatedPatches.F90,v $ $Revision: 1.5 $' private
Definition at line 61 of file RFLU_ModRelatedPatches.F90.
The documentation for this module was generated from the following file:
RFLU_ModRelatedPatches.F90