Rocstar: HDF4 Class Reference
HDF4 Class Reference abstract
A class to serialize HDF calls for multithreaded apps.
#include <HDF4.h>
Public Member Functions
virtual ~HDF4 ()=0
virtual ~HDF4 ()=0
Static Public Member Functions
static void init ()
Create and start the I/O thread.
static void finalize ()
Destroy the I/O thread.
static int32 Select (int32 sd_id, int32 &index, char *name, int32 *rank, int32 *size, int32 *dType, int32 *nAttrs, int32 dsCount=-1)
"Open" and "close" HDF files efficiently.
static int SizeOf (int32 dType)
Get the size in bytes of an HDF data type.
static void Terminate ()
Terminate the I/O thread.
static std::string error_msg ()
return error message
static void init ()
Create and start the I/O thread.
static void finalize ()
Destroy the I/O thread.
static int32 Select (int32 sd_id, int32 &index, char *name, int32 *rank, int32 *size, int32 *dType, int32 *nAttrs, int32 dsCount=-1)
"Open" and "close" HDF files efficiently.
static int SizeOf (int32 dType)
Get the size in bytes of an HDF data type.
static void Terminate ()
Terminate the I/O thread.
static std::string error_msg ()
return error message
static intn Hishdf (const char *filename)
HDF4 wrapper functions.
static int32 SDstart (const char *filename, int32 accessMode)
static intn SDend (int32 sd_id)
static intn SDfileinfo (int32 id, int32 *dsCount, int32 *nAttrs)
static int32 SDcreate (int32 sd_id, const char *name, int32 dType, int32 rank, int32 *size)
static int32 SDselect (int32 sd_id, int32 index)
static intn SDendaccess (int32 sds_id)
static int32 SDfindattr (int32 id, const char *attrName)
static intn SDgetinfo (int32 sds_id, char *name, int32 *rank, int32 *size, int32 *dType, int32 *nAttrs)
static intn SDsetdatastrs (int32 sds_id, const char *label, const char *units, const char *format, const char *coordsys)
static intn SDgetdatastrs (int32 sds_id, char *label, char *units, char *format, char *coordsys, intn length)
static intn SDsetrange (int32 sds_id, VOIDP max, VOIDP min)
static intn SDgetrange (int32 sds_id, VOIDP max, VOIDP min)
static intn SDwritedata (int32 sds_id, int32 *start, int32 *stride, int32 *end, VOIDP data)
static intn SDreaddata (int32 sds_id, int32 *start, int32 *stride, int32 *end, VOIDP data)
static intn DFSDsetdims (intn rank, int32 dimsizes[])
Single file interface.
static intn DFSDsetNT (int32 numbertype)
static intn DFSDsetdatastrs (const char *label, const char *unit, const char *format, const char *coordsys)
static intn DFSDsetrange (VOIDP maxi, VOIDP mini)
static intn DFSDadddata (const char *filename, intn rank, int32 dimsizes[], VOIDP data)
static intn DFSDputdata (const char *filename, intn rank, int32 dimsizes[], VOIDP data)
static intn Hishdf (const char *filename)
HDF4 wrapper functions.
static int32 SDstart (const char *filename, int32 accessMode)
static intn SDend (int32 sd_id)
static intn SDfileinfo (int32 id, int32 *dsCount, int32 *nAttrs)
static int32 SDcreate (int32 sd_id, const char *name, int32 dType, int32 rank, int32 *size)
static int32 SDselect (int32 sd_id, int32 index)
static intn SDendaccess (int32 sds_id)
static int32 SDfindattr (int32 id, const char *attrName)
static intn SDgetinfo (int32 sds_id, char *name, int32 *rank, int32 *size, int32 *dType, int32 *nAttrs)
static intn SDsetdatastrs (int32 sds_id, const char *label, const char *units, const char *format, const char *coordsys)
static intn SDgetdatastrs (int32 sds_id, char *label, char *units, char *format, char *coordsys, intn length)
static intn SDsetrange (int32 sds_id, VOIDP max, VOIDP min)
static intn SDgetrange (int32 sds_id, VOIDP max, VOIDP min)
static intn SDwritedata (int32 sds_id, int32 *start, int32 *stride, int32 *end, VOIDP data)
static intn SDreaddata (int32 sds_id, int32 *start, int32 *stride, int32 *end, VOIDP data)
static intn DFSDsetdims (intn rank, int32 dimsizes[])
Single file interface.
static intn DFSDsetNT (int32 numbertype)
static intn DFSDsetdatastrs (const char *label, const char *unit, const char *format, const char *coordsys)
static intn DFSDsetrange (VOIDP maxi, VOIDP mini)
static intn DFSDadddata (const char *filename, intn rank, int32 dimsizes[], VOIDP data)
static intn DFSDputdata (const char *filename, intn rank, int32 dimsizes[], VOIDP data)
Detailed Description
A class to serialize HDF calls for multithreaded apps.
Since the HDF4 libraries aren't thread-safe, it's necessary to make sure that two threads don't use HDF routines concurrently. This class starts an I/O thread and passes HDF commands to it. It also provides a few utility functions, and supports caching of open file descriptors.
Definition at line 56 of file Rocin/include/HDF4.h.
Constructor & Destructor Documentation
virtual ~HDF4 () pure virtual
virtual ~HDF4 () pure virtual
Member Function Documentation
intn DFSDadddata (const char * filename, intn rank, int32 dimsizes[], VOIDP data) static
Definition at line 573 of file HDF4.C.
References HDF_DEBUG, and rank.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::DFSDadddata" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::DFSDadddata);
   c.m_args.resize(4);
   c.m_args[0].asCharP = const_cast<char*>(filename);
   c.m_args[1].asIntn = rank;
   c.m_args[2].asInt32P = dimsizes;
   c.m_args[3].asVOIDP = data;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::DFSDadddata(filename, rank, dimsizes, data);
 #endif // USE_PTHREADS
 }
static intn DFSDadddata (const char * filename, intn rank, int32 dimsizes[], VOIDP data) static
intn DFSDputdata (const char * filename, intn rank, int32 dimsizes[], VOIDP data) static
Definition at line 596 of file HDF4.C.
References HDF_DEBUG, and rank.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::DFSDputdata" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::DFSDputdata);
   c.m_args.resize(4);
   c.m_args[0].asCharP = const_cast<char*>(filename);
   c.m_args[1].asIntn = rank;
   c.m_args[2].asInt32P = dimsizes;
   c.m_args[3].asVOIDP = data;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::DFSDputdata(filename, rank, dimsizes, data);
 #endif // USE_PTHREADS
 }
static intn DFSDputdata (const char * filename, intn rank, int32 dimsizes[], VOIDP data) static
intn DFSDsetdatastrs (const char * label, const char * unit, const char * format, const char * coordsys) static
Definition at line 530 of file HDF4.C.
References HDF_DEBUG.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::DFSDsetdatastrs" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::DFSDsetdatastrs);
   c.m_args.resize(4);
   c.m_args[0].asCharP = const_cast<char*>(label);
   c.m_args[1].asCharP = const_cast<char*>(unit);
   c.m_args[2].asCharP = const_cast<char*>(format);
   c.m_args[3].asCharP = const_cast<char*>(coordsys);
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::DFSDsetdatastrs(label, unit, format, coordsys);
 #endif // USE_PTHREADS
 }
static intn DFSDsetdatastrs (const char * label, const char * unit, const char * format, const char * coordsys) static
static intn DFSDsetdims (intn rank, int32 dimsizes[]) static
Single file interface.
intn DFSDsetdims (intn rank, int32 dimsizes[]) static
Single file interface.
Definition at line 491 of file HDF4.C.
References HDF_DEBUG, and rank.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::DFSDsetdims" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::DFSDsetdims);
   c.m_args.resize(2);
   c.m_args[0].asIntn = rank;
   c.m_args[1].asInt32P = dimsizes;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::DFSDsetdims(rank, dimsizes);
 #endif // USE_PTHREADS
 }
static intn DFSDsetNT (int32 numbertype) static
intn DFSDsetNT (int32 numbertype) static
Definition at line 511 of file HDF4.C.
References HDF_DEBUG.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::DFSDsetNT" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::DFSDsetNT);
   c.m_args.resize(1);
   c.m_args[0].asInt32 = numbertype;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::DFSDsetNT(numbertype);
 #endif // USE_PTHREADS
 }
intn DFSDsetrange (VOIDP maxi, VOIDP mini) static
Definition at line 553 of file HDF4.C.
References HDF_DEBUG.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::DFSDsetrange" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::DFSDsetrange);
   c.m_args.resize(2);
   c.m_args[0].asVOIDP = maxi;
   c.m_args[1].asVOIDP = mini;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::DFSDsetrange(maxi, mini);
 #endif // USE_PTHREADS
 }
static intn DFSDsetrange (VOIDP maxi, VOIDP mini) static
std::string error_msg () static
return error message
Definition at line 961 of file HDF4.C.
{
   return HEstring((hdf_err_code_t)HEvalue(1));
 }
static std::string error_msg () static
return error message
void finalize () static
Destroy the I/O thread.
Definition at line 128 of file HDF4.C.
References HDF_DEBUG, and Terminate().
Referenced by Rocout::finalize(), and Rocin::finalize().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::finalize()" << std::endl;
 #ifdef USE_PTHREADS
   --sm_counter;
   if (sm_counter > 0)
     return;
   HDF4::Terminate();
   void* retval;
   pthread_join(sm_id, &retval);
   sm_id = 0;
 #endif // USE_PTHREADS
 }
static void finalize () static
Destroy the I/O thread.
intn Hishdf (const char * filename) static
HDF4 wrapper functions.
Each wrapper function adds a command request to the end of the command queue and signals the I/O thread that a command is pending.
Multi-file interface.
See the HDF4 documentation for details on parameters and return values for each function.
Definition at line 154 of file HDF4.C.
References HDF_DEBUG.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::Hishdf" << std::endl;
 #ifdef USE_PTHREADS
   // Sprecify the command.
   HDF4Cmd c(HDF4Cmd::Hishdf);
   // Add the arguments to the argument list.
   c.m_args.resize(1);
   c.m_args[0].asCharP = const_cast<char*>(filename);
   // Push the command request onto the command queue.
   PostCommand(&c);
   // Return the result.
   return c.m_result.asIntn;
 #else
  return ::Hishdf(filename);
 #endif // USE_PTHREADS
 }
static intn Hishdf (const char * filename) static
HDF4 wrapper functions.
Multi-file interface.
void init () static
Create and start the I/O thread.
Make sure that an I/O thread isn't running already.
If it is, then don't create another one.
Definition at line 108 of file HDF4.C.
References HDF_DEBUG.
Referenced by Rocout::init(), and Rocin::init().
 {
   if (HDF_DEBUG)
    std::cout << "HDF4::init()" << std::endl;
 #ifdef USE_PTHREADS
   ++sm_counter;
   // Make sure that a thread isn't already running.
   if (sm_id != 0)
     return;
   pthread_attr_t attr;
   pthread_attr_init(&attr);
   pthread_attr_setscope(&attr, PTHREAD_SCOPE_SYSTEM);
   pthread_create(&sm_id, &attr, HDF4::Entry, NULL);
   pthread_attr_destroy(&attr);
 #endif // USE_PTHREADS
 }
static void init () static
Create and start the I/O thread.
static int32 SDcreate (int32 sd_id, const char * name, int32 dType, int32 rank, int32 * size) static
int32 SDcreate (int32 sd_id, const char * name, int32 dType, int32 rank, int32 * size) static
Definition at line 244 of file HDF4.C.
References HDF_DEBUG, and rank.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDcreate" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDcreate);
   c.m_args.resize(5);
   c.m_args[0].asInt32 = sds_id;
   c.m_args[1].asCharP = const_cast<char*>(name);
   c.m_args[2].asInt32 = dType;
   c.m_args[3].asInt32 = rank;
   c.m_args[4].asInt32P = size;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDcreate(sds_id, name, dType, rank, size);
 #endif // USE_PTHREADS
 }
static intn SDend (int32 sd_id) static
intn SDend (int32 sd_id) static
Definition at line 200 of file HDF4.C.
References HDF_DEBUG.
Referenced by FindFirstGeometryDataset(), load_data_HDF4(), and scan_files_HDF4().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDend" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDend);
   c.m_args.resize(1);
   c.m_args[0].asInt32 = sd_id;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDend(sd_id);
 #endif // USE_PTHREADS
 }
static intn SDendaccess (int32 sds_id) static
intn SDendaccess (int32 sds_id) static
Definition at line 288 of file HDF4.C.
References HDF_DEBUG.
Referenced by FindFirstGeometryDataset(), load_data_HDF4(), scan_files_HDF4(), and Select().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDendaccess" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDendaccess);
   c.m_args.resize(1);
   c.m_args[0].asInt32 = sds_id;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDendaccess(sds_id);
 #endif // USE_PTHREADS
 }
static intn SDfileinfo (int32 id, int32 * dsCount, int32 * nAttrs) static
intn SDfileinfo (int32 id, int32 * dsCount, int32 * nAttrs) static
Definition at line 219 of file HDF4.C.
References HDF_DEBUG, and id().
Referenced by FindFirstGeometryDataset(), scan_files_HDF4(), and Select().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDfileinfo" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDfileinfo);
   c.m_args.resize(3);
   c.m_args[0].asInt32 = id;
   c.m_args[1].asInt32P = dsCount;
   c.m_args[2].asInt32P = nAttrs;
   if(HDF_DEBUG)
     std::cout << "  Posting command" << std::endl;
   PostCommand(&c);
   if(HDF_DEBUG)
     std::cout << "  Returning" << std::endl;
   return c.m_result.asIntn;
 #else
   return ::SDfileinfo(id, dsCount, nAttrs);
 #endif // USE_PTHREADS
 }
static int32 SDfindattr (int32 id, const char * attrName) static
int32 SDfindattr (int32 id, const char * attrName) static
Definition at line 307 of file HDF4.C.
References HDF_DEBUG, and id().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDfindattr" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDfindattr);
   c.m_args.resize(2);
   c.m_args[0].asInt32 = id;
   c.m_args[1].asCharP = const_cast<char*>(attrName);
   PostCommand(&c);
   return c.m_result.asInt32;
 #else
   return ::SDfindattr(id, attrName);
 #endif // USE_PTHREADS
 }
static intn SDgetdatastrs (int32 sds_id, char * label, char * units, char * format, char * coordsys, intn length) static
intn SDgetdatastrs (int32 sds_id, char * label, char * units, char * format, char * coordsys, intn length) static
Definition at line 376 of file HDF4.C.
References HDF_DEBUG, and Mesquite::length().
Referenced by FindFirstGeometryDataset(), and scan_files_HDF4().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDgetdatastrs" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDgetdatastrs);
   c.m_args.resize(6);
   c.m_args[0].asInt32 = sds_id;
   c.m_args[1].asCharP = label;
   c.m_args[2].asCharP = units;
   c.m_args[3].asCharP = format;
   c.m_args[4].asCharP = coordsys;
   c.m_args[5].asIntn = length;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDgetdatastrs(sds_id, label, units, format, coordsys, length);
 #endif // USE_PTHREADS
 }
intn SDgetinfo (int32 sds_id, char * name, int32 * rank, int32 * size, int32 * dType, int32 * nAttrs) static
Definition at line 327 of file HDF4.C.
References HDF_DEBUG, and rank.
Referenced by Select().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDgetinfo" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDgetinfo);
   c.m_args.resize(6);
   c.m_args[0].asInt32 = sds_id;
   c.m_args[1].asCharP = name;
   c.m_args[2].asInt32P = rank;
   c.m_args[3].asInt32P = size;
   c.m_args[4].asInt32P = dType;
   c.m_args[5].asInt32P = nAttrs;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDgetinfo(sds_id, name, rank, size, dType, nAttrs);
 #endif // USE_PTHREADS
 }
static intn SDgetinfo (int32 sds_id, char * name, int32 * rank, int32 * size, int32 * dType, int32 * nAttrs) static
static intn SDgetrange (int32 sds_id, VOIDP max, VOIDP min) static
intn SDgetrange (int32 sds_id, VOIDP max, VOIDP min) static
Definition at line 422 of file HDF4.C.
References HDF_DEBUG, max(), and min().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDgetrange" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDgetrange);
   c.m_args.resize(3);
   c.m_args[0].asInt32 = sds_id;
   c.m_args[1].asVOIDP = max;
   c.m_args[2].asVOIDP = min;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDgetrange(sds_id, max, min);
 #endif // USE_PTHREADS
 }
intn SDreaddata (int32 sds_id, int32 * start, int32 * stride, int32 * end, VOIDP data) static
Definition at line 467 of file HDF4.C.
References HDF_DEBUG.
Referenced by load_data_HDF4(), and scan_files_HDF4().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDreaddata" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDreaddata);
   c.m_args.resize(5);
   c.m_args[0].asInt32 = sds_id;
   c.m_args[1].asInt32P = start;
   c.m_args[2].asInt32P = stripe;
   c.m_args[3].asInt32P = end;
   c.m_args[4].asVOIDP = data;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDreaddata(sds_id, start, stripe, end, data);
 #endif // USE_PTHREADS
 }
static intn SDreaddata (int32 sds_id, int32 * start, int32 * stride, int32 * end, VOIDP data) static
static int32 SDselect (int32 sd_id, int32 index) static
int32 SDselect (int32 sd_id, int32 index) static
Definition at line 268 of file HDF4.C.
References HDF_DEBUG.
Referenced by load_data_HDF4(), and Select().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDselect( sd_id == " << sd_id << ", index == " << index << " )" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDselect);
   c.m_args.resize(2);
   c.m_args[0].asInt32 = sd_id;
   c.m_args[1].asInt32 = index;
   PostCommand(&c);
   return c.m_result.asInt32;
 #else
   return ::SDselect(sd_id, index);
 #endif // USE_PTHREADS
 }
static intn SDsetdatastrs (int32 sds_id, const char * label, const char * units, const char * format, const char * coordsys) static
intn SDsetdatastrs (int32 sds_id, const char * label, const char * units, const char * format, const char * coordsys) static
Definition at line 352 of file HDF4.C.
References HDF_DEBUG.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDsetdatastrs" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDsetdatastrs);
   c.m_args.resize(5);
   c.m_args[0].asInt32 = sds_id;
   c.m_args[1].asCharP = const_cast<char*>(label);
   c.m_args[2].asCharP = const_cast<char*>(units);
   c.m_args[3].asCharP = const_cast<char*>(format);
   c.m_args[4].asCharP = const_cast<char*>(coordsys);
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDsetdatastrs(sds_id, label, units, format, coordsys);
 #endif // USE_PTHREADS
 }
static intn SDsetrange (int32 sds_id, VOIDP max, VOIDP min) static
intn SDsetrange (int32 sds_id, VOIDP max, VOIDP min) static
Definition at line 401 of file HDF4.C.
References HDF_DEBUG, max(), and min().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDsetrange" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDsetrange);
   c.m_args.resize(3);
   c.m_args[0].asInt32 = sds_id;
   c.m_args[1].asVOIDP = max;
   c.m_args[2].asVOIDP = min;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDsetrange(sds_id, max, min);
 #endif // USE_PTHREADS
 }
static int32 SDstart (const char * filename, int32 accessMode) static
int32 SDstart (const char * filename, int32 accessMode) static
Definition at line 177 of file HDF4.C.
References HDF_DEBUG.
Referenced by FindFirstGeometryDataset(), load_data_HDF4(), and scan_files_HDF4().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDstart( filename == " << filename << ", accessMode == " << accessMode << " )" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDstart);
   c.m_args.resize(2);
   c.m_args[0].asCharP = const_cast<char*>(filename);
   c.m_args[1].asInt32 = accessMode;
   if (HDF_DEBUG){
     // std::cout << "  Posting Command" << std::endl << "    m_args[0] = " << c.m_args[0].asCharP << std::endl << "    m_args[1] = " << c.m_args[1].asInt32 << std::endl;
   }
   PostCommand(&c);
   return c.m_result.asInt32;
 #else
  return ::SDstart(filename, accessMode);
 #endif // USE_PTHREADS
 }
static intn SDwritedata (int32 sds_id, int32 * start, int32 * stride, int32 * end, VOIDP data) static
intn SDwritedata (int32 sds_id, int32 * start, int32 * stride, int32 * end, VOIDP data) static
Definition at line 443 of file HDF4.C.
References HDF_DEBUG.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SDwritedata" << std::endl;
 #ifdef USE_PTHREADS
   HDF4Cmd c(HDF4Cmd::SDwritedata);
   c.m_args.resize(5);
   c.m_args[0].asInt32 = sds_id;
   c.m_args[1].asInt32P = start;
   c.m_args[2].asInt32P = stripe;
   c.m_args[3].asInt32P = end;
   c.m_args[4].asVOIDP = data;
   PostCommand(&c);
   return c.m_result.asIntn;
 #else
   return ::SDwritedata(sds_id, start, stripe, end, data);
 #endif // USE_PTHREADS
 }
int32 Select (int32 sd_id, int32 & index, char * name, int32 * rank, int32 * size, int32 * dType, int32 * nAttrs, int32 dsCount = -1) static
"Open" and "close" HDF files efficiently.
The "single file" SD routines add several "fake" datasets, which severely clutter up the file and complicate searches.
Select the first non-"fakeDim" dataset, starting at index.
This more powerful version of SDselect adds the functionality of SDgetinfo and ignores fake datasets.
Parameters
index The index of the dataset to select. The difference from SDselect is that this parameter will be assigned the index of the first non-"fake" dataset (possibly the initial value).
dsCount The number of datasets in the file. If this isn't provided, the number of datasets is determined by calling SDfileinfo.
Returns
An HDF4 dataset id on success, or FAIL on failure.
Note
See the documentation for SDselect and SDgetinfo for the descriptions of the other parameters.
Definition at line 675 of file HDF4.C.
References HDF_DEBUG, MAX_NC_VARS, SDendaccess(), SDfileinfo(), SDgetinfo(), and SDselect().
Referenced by FindFirstGeometryDataset(), and scan_files_HDF4().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::Select" << std::endl;
   int32 sds_id;
   intn status;
   // If the caller didn't specify the number of datasets in the file, then
   // we have to call SDfileinfo().  <sigh>
   if (dsCount == -1) {
     int32 numAttrs;
     status = HDF4::SDfileinfo(sd_id, &dsCount, &numAttrs);
     if (status == FAIL)
       dsCount = MAX_NC_VARS;
   }
   while (index < dsCount) {
     // Open the next dataset.
     sds_id = HDF4::SDselect(sd_id, index);
     if (sds_id == FAIL) {
       std::cerr << "HDF4::Select(): unable to select dataset " << index
                 << '.' << std::endl;
       return FAIL;
     }
     // Get the dataset info.
     status = HDF4::SDgetinfo(sds_id, name, rank, size, dType, nAttrs);
     if (status == FAIL) {
       std::cerr << "HDF4::Select(): SDgetinfo() failed for dataset "
                 << index << '.' << std::endl;
       return FAIL;
     }
     // Make sure that this isn't a "fakeDim" dataset (they're so annoying).
     if (strncmp(name, "fakeDim", 7) != 0)
       return sds_id;
     // If we got this far, then it was a "fakeDim" dataset.  Close it and
     // try the next one.
     HDF4::SDendaccess(sds_id);
     ++index;
   }
   // Whoops, we're fresh out of datasets.  Sorry.
   return FAIL;
 }
static int32 Select (int32 sd_id, int32 & index, char * name, int32 * rank, int32 * size, int32 * dType, int32 * nAttrs, int32 dsCount = -1) static
"Open" and "close" HDF files efficiently.
Select the first non-"fakeDim" dataset, starting at index.
static int SizeOf (int32 dType) static
Get the size in bytes of an HDF data type.
int SizeOf (int32 dType) static
Get the size in bytes of an HDF data type.
Like the "sizeof" operator, except that this takes a HDF4 datatype id.
Parameters
dType The HDF4 datatype id.
Returns
The size, in bytes, of the datatype.
Definition at line 730 of file HDF4.C.
References HDF_DEBUG.
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::SIZEOF" << std::endl;
   switch (dType) {
     case DFNT_CHAR8:
     case DFNT_UCHAR8:
     case DFNT_INT8:
     case DFNT_NINT8:
     case DFNT_LINT8:
     case DFNT_UINT8:
     case DFNT_NUINT8:
     case DFNT_LUINT8:
       return 1;
     case DFNT_INT16:
     case DFNT_NINT16:
     case DFNT_LINT16:
     case DFNT_UINT16:
     case DFNT_NUINT16:
     case DFNT_LUINT16:
       return 2;
     case DFNT_INT32:
     case DFNT_NINT32:
     case DFNT_LINT32:
     case DFNT_UINT32:
     case DFNT_NUINT32:
     case DFNT_LUINT32:
     case DFNT_FLOAT32:
     case DFNT_NFLOAT32:
     case DFNT_LFLOAT32:
       return 4;
     case DFNT_FLOAT64:
     case DFNT_NFLOAT64:
     case DFNT_LFLOAT64:
       return 8;
   }
   return 0;
 }
void Terminate () static
Terminate the I/O thread.
This adds a "Terminate" request to the command queue.
Any commands already in the queue will be acted on, but any commands added afterward will be ignored.
Definition at line 625 of file HDF4.C.
References HDF_DEBUG.
Referenced by finalize().
 {
   if (HDF_DEBUG)
     std::cout << "HDF4::Terminate()" << std::endl;
 #ifdef USE_PTHREADS
   if (sm_counter > 0)
     return;
   HDF4Cmd c(HDF4Cmd::Terminate);
   c.m_args.clear();
   PostCommand(&c);
 #endif // USE_PTHREADS
 }
static void Terminate () static
Terminate the I/O thread.
The documentation for this class was generated from the following files:
Rocin/include/HDF4.h
HDF4.C