Rocstar: generic_list Module Reference
generic_list Module Reference
Data Types
type link_ptr_type
type link_type
type list_type
Public Member Functions
subroutine, public li_check_list (List, Message)
subroutine, public li_init_list (List)
subroutine, public li_add_to_head (Link, List)
integer function, public li_get_len (List)
logical function, public li_associated (Link)
type(link_ptr_type) function,
public li_get_next (Link)
type(link_ptr_type) function,
public li_get_head (List)
type(link_ptr_type) function,
public li_remove_head (List)
subroutine, public li_check_list (List, Message)
subroutine, public li_init_list (List)
subroutine, public li_add_to_head (Link, List)
integer function, public li_get_len (List)
logical function, public li_associated (Link)
type(link_ptr_type) function,
public li_get_next (Link)
type(link_ptr_type) function,
public li_get_head (List)
type(link_ptr_type) function,
public li_remove_head (List)
Private Member Functions
subroutine abort (Message)
subroutine abort (Message)
Detailed Description
Definition at line 92 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
Member Function/Subroutine Documentation
subroutine abort (character *(*) Message) private
Definition at line 133 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
References StopWatch::stop().
subroutine abort (character *(*) Message) private
Definition at line 133 of file utilities/RocfracPrep/GENII_LinkedList.f90.
References StopWatch::stop().
subroutine, public li_add_to_head (type(link_ptr_type), intent(inout) Link, type(list_type), intent(inout) List)
Definition at line 168 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
subroutine, public li_add_to_head (type(link_ptr_type), intent(inout) Link, type(list_type), intent(inout) List)
Definition at line 168 of file utilities/RocfracPrep/GENII_LinkedList.f90.
logical function, public li_associated (type(link_ptr_type), intent(in) Link)
Definition at line 198 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
Referenced by li_associated().
logical function, public li_associated (type(link_ptr_type), intent(in) Link)
Definition at line 198 of file utilities/RocfracPrep/GENII_LinkedList.f90.
References li_associated().
subroutine, public li_check_list (type(list_type) List, character *(*) Message)
Definition at line 144 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
References Roccom_base::abort().
subroutine, public li_check_list (type(list_type) List, character *(*) Message)
Definition at line 144 of file utilities/RocfracPrep/GENII_LinkedList.f90.
References Roccom_base::abort().
type(link_ptr_type) function, public li_get_head (type(list_type), intent(in), target List)
Definition at line 225 of file utilities/RocfracPrep/GENII_LinkedList.f90.
References li_get_head().
type(link_ptr_type) function, public li_get_head (type(list_type), intent(in), target List)
Definition at line 225 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
Referenced by li_get_head().
integer function, public li_get_len (type(list_type), intent(in), target List)
Definition at line 180 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
Referenced by li_get_len().
integer function, public li_get_len (type(list_type), intent(in), target List)
Definition at line 180 of file utilities/RocfracPrep/GENII_LinkedList.f90.
References li_get_len().
type(link_ptr_type) function, public li_get_next (type(link_ptr_type), intent(in) Link)
Definition at line 210 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
Referenced by li_get_next().
type(link_ptr_type) function, public li_get_next (type(link_ptr_type), intent(in) Link)
Definition at line 210 of file utilities/RocfracPrep/GENII_LinkedList.f90.
References li_get_next().
subroutine, public li_init_list (type(list_type), intent(inout), target List)
Definition at line 157 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
Referenced by rocfracprep().
subroutine, public li_init_list (type(list_type), intent(inout), target List)
Definition at line 157 of file utilities/RocfracPrep/GENII_LinkedList.f90.
type(link_ptr_type) function, public li_remove_head (type(list_type), intent(inout), target List)
Definition at line 236 of file utilities/RocfracPrep/GENII_LinkedList.f90.
References li_remove_head().
type(link_ptr_type) function, public li_remove_head (type(list_type), intent(inout), target List)
Definition at line 236 of file SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90.
Referenced by li_remove_head().
The documentation for this module was generated from the following file:
SourceIMP/utilities/RocfracPrep/GENII_LinkedList.f90