Rocstar: rflu_modtopologyutils Module Reference
rflu_modtopologyutils Module Reference
Public Member Functions
subroutine, public rflu_buildcellvertlist (global, pGrid, cList, cListDim, vList, vListDimMax, vListDim)
subroutine, public rflu_buildconnvertlist (global, connList, connListDim1, connListDim2, vList, vListDimMax, vListDim)
subroutine, public rflu_buildfacevertlist (global, pGrid, fList, fListDim, vList, vListDimMax, vListDim, errorFlag)
subroutine, public rflu_buildvertcellnghblist (global, pGrid, vListOrig, vListOrigDim, nLayers, iReg, cList, cListDimMax, cListDim)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModTopologyUtils.F90,v $ $Revision: 1.9 $'
Detailed Description
Definition at line 39 of file RFLU_ModTopologyUtils.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildcellvertlist (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, dimension(clistdim), intent(in) cList, integer, intent(in) cListDim, integer, dimension(vlistdimmax), intent(out) vList, integer, intent(in) vListDimMax, integer, intent(out) vListDim)
Definition at line 97 of file RFLU_ModTopologyUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, key, modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modhashtable::rflu_createhashtable(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modhashtable::rflu_hashbuildkey(), and rflu_modhashtable::rflu_hashvertex().
Referenced by rflu_buildvertcellnghblist(), and rflu_modcommlists::rflu_comm_buildcommlistsvert().
subroutine, public rflu_buildconnvertlist (type(t_global), pointer global, integer, dimension(connlistdim1,connlistdim2), intent(in) connList, integer, intent(in) connListDim1, integer, intent(in) connListDim2, integer, dimension(vlistdimmax), intent(out) vList, integer, intent(in) vListDimMax, integer, intent(out) vListDim)
Definition at line 236 of file RFLU_ModTopologyUtils.F90.
References moderror::deregisterfunction(), i, key, modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modhashtable::rflu_createhashtable(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modhashtable::rflu_hashbuildkey(), and rflu_modhashtable::rflu_hashvertex().
Referenced by rflu_modensightutils::rflu_ens_writegrid().
subroutine, public rflu_buildfacevertlist (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, dimension(flistdim), intent(in) fList, integer, intent(in) fListDim, integer, dimension(vlistdimmax), intent(out) vList, integer, intent(in) vListDimMax, integer, intent(out) vListDim, integer, intent(out) errorFlag)
Definition at line 347 of file RFLU_ModTopologyUtils.F90.
References moderror::deregisterfunction(), i, key, modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modhashtable::rflu_createhashtable(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modhashtable::rflu_hashbuildkey(), and rflu_modhashtable::rflu_hashvertex().
Referenced by rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), and rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2().
subroutine, public rflu_buildvertcellnghblist (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, dimension(vlistorigdim), intent(in) vListOrig, integer, intent(in) vListOrigDim, integer, intent(in) nLayers, integer, intent(in) iReg, integer, dimension(clistdimmax), intent(out) cList, integer, intent(in) cListDimMax, integer, intent(out) cListDim)
Definition at line 500 of file RFLU_ModTopologyUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), moderror::registerfunction(), modsortsearch::removecommonsortedintegers(), and rflu_buildcellvertlist().
Referenced by rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), and rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModTopologyUtils.F90,v $ $Revision: 1.9 $' private
Definition at line 62 of file RFLU_ModTopologyUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModTopologyUtils.F90