Rocstar: rflu_modoctree Module Reference
rflu_modoctree Module Reference
Public Member Functions
subroutine, public rflu_createoctree (global, nPoints)
subroutine, public rflu_buildoctree (XI, YI, ZI, XLOW, XUPP, YLOW, YUPP, ZLOW, ZUPP)
subroutine, public rflu_queryoctree (XPT, YPT, ZPT, NUMP, NEIGHP)
subroutine, public rflu_destroyoctree (global)
Private Member Functions
subroutine octree
Private Attributes
integer, parameter mtest = 5000
integer, parameter mnump = 100
integer moctr
integer nnode
integer, dimension(:), allocatable ichk
integer, dimension(:), allocatable nlink
integer, dimension(:,:),
allocatable noctr
real(rfreal) dismin
real(rfreal), dimension(2) xfar
real(rfreal), dimension(2) yfar
real(rfreal), dimension(2) zfar
real(rfreal), dimension(:),
allocatable x
real(rfreal), dimension(:),
allocatable y
real(rfreal), dimension(:),
allocatable z
Detailed Description
Definition at line 51 of file RFLU_ModOctree.F90.
Member Function/Subroutine Documentation
subroutine octree () private
Definition at line 216 of file RFLU_ModOctree.F90.
References i, j, k, max(), n, Element_node_enumerator::next(), and StopWatch::stop().
Referenced by rflu_buildoctree().
subroutine, public rflu_buildoctree (real(rfreal), dimension(nnode), intent(in) XI, real(rfreal), dimension(nnode), intent(in) YI, real(rfreal), dimension(nnode), intent(in) ZI, real(rfreal), intent(in) XLOW, real(rfreal), intent(in) XUPP, real(rfreal), intent(in) YLOW, real(rfreal), intent(in) YUPP, real(rfreal), intent(in) ZLOW, real(rfreal), intent(in) ZUPP)
Definition at line 152 of file RFLU_ModOctree.F90.
References n, and octree().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolserial_3d(), rflu_modoles::rflu_buildstencilsoles(), rflu_modprobes::rflu_findprobecells(), and rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps().
subroutine, public rflu_createoctree (type(t_global), pointer global, integer, intent(in) nPoints)
Definition at line 92 of file RFLU_ModOctree.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolserial_3d(), rflu_modoles::rflu_buildstencilsoles(), rflu_modprobes::rflu_findprobecells(), and rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps().
subroutine, public rflu_destroyoctree (type(t_global), pointer global)
Definition at line 668 of file RFLU_ModOctree.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolserial_3d(), rflu_modoles::rflu_buildstencilsoles(), rflu_modprobes::rflu_findprobecells(), and rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps().
subroutine, public rflu_queryoctree (real(rfreal), intent(in) XPT, real(rfreal), intent(in) YPT, real(rfreal), intent(in) ZPT, integer, intent(in) NUMP, integer, dimension(nump), intent(inout) NEIGHP)
Definition at line 405 of file RFLU_ModOctree.F90.
References dist(), i, ic, j, k, kc, Aff_transformation_2< R_ >::m(), max(), sqrt(), and StopWatch::stop().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolserial_3d(), rflu_modoles::rflu_buildstencilsoles(), rflu_modprobes::rflu_findprobecells(), and rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps().
Member Data Documentation
real(rfreal) dismin private
Definition at line 78 of file RFLU_ModOctree.F90.
integer, dimension(:), allocatable ichk private
Definition at line 75 of file RFLU_ModOctree.F90.
integer, parameter mnump = 100 private
Definition at line 70 of file RFLU_ModOctree.F90.
integer moctr private
Definition at line 73 of file RFLU_ModOctree.F90.
integer, parameter mtest = 5000 private
Definition at line 70 of file RFLU_ModOctree.F90.
integer, dimension(:), allocatable nlink private
Definition at line 75 of file RFLU_ModOctree.F90.
integer nnode private
Definition at line 73 of file RFLU_ModOctree.F90.
integer, dimension(:,:), allocatable noctr private
Definition at line 76 of file RFLU_ModOctree.F90.
real(rfreal), dimension(:), allocatable x private
Definition at line 80 of file RFLU_ModOctree.F90.
real(rfreal), dimension(2) xfar private
Definition at line 79 of file RFLU_ModOctree.F90.
real(rfreal), dimension(:), allocatable y private
Definition at line 80 of file RFLU_ModOctree.F90.
real(rfreal), dimension(2) yfar private
Definition at line 79 of file RFLU_ModOctree.F90.
real(rfreal), dimension(:), allocatable z private
Definition at line 80 of file RFLU_ModOctree.F90.
real(rfreal), dimension(2) zfar private
Definition at line 79 of file RFLU_ModOctree.F90.
The documentation for this module was generated from the following file:
RFLU_ModOctree.F90