Rocstar: rflu_modoles Module Reference
rflu_modoles Module Reference
Public Member Functions
subroutine, public rflu_createstencilsweightsoles (pRegion)
subroutine, public rflu_createintegralsoles (pRegion)
subroutine, public rflu_buildstencilsoles (pRegion)
subroutine, public rflu_findprototypefacesoles (pRegion)
subroutine, public rflu_computegeometrictermsoles (pRegion)
subroutine, public rflu_buildsymmetrymapsoles (pRegion)
subroutine, public rflu_enforcesymmetryoles (pRegion)
subroutine, public rflu_definecorrelation220 (nDim, z, nFunNZ, f)
subroutine, public rflu_definecorrelation221 (nDim, z, nFunNZ, f)
subroutine, public rflu_definecorrelation32 (nDim, z, nFunNZ, f)
subroutine, public rflu_definecorrelation430 (nDim, z, nFunNZ, f)
subroutine, public rflu_definecorrelation431 (nDim, z, nFunNZ, f)
subroutine, public rflu_definecorrelation432 (nDim, z, nFunNZ, f)
subroutine, public rflu_definecorrelation540 (nDim, z, nFunNZ, f)
subroutine, public rflu_definecorrelation541 (nDim, z, nFunNZ, f)
subroutine, public rflu_definecorrelation542 (nDim, z, nFunNZ, f)
subroutine, public rflu_mapk2ij (k, i, j)
subroutine, public rflu_mapl2ijk (l, i, j, k)
subroutine, public rflu_mapm2ijkl (m, i, j, k, l)
integer function, public rflu_geti1posoles (l, d)
integer function, public rflu_geti4posoles (l, m, d, e, nCells)
integer function, public rflu_getlposoles (j, a)
subroutine, public rflu_getlposinvoles (loc, j, a)
integer function, public rflu_getqposoles (j, k, b, g, nCells)
subroutine, public rflu_getqposinvoles (loc, nCells, j, k, b, g)
subroutine, public rflu_destroystencilsweightsoles (pRegion)
subroutine, public rflu_allocatedcuhrearrays (global, nDim, nFunNZ, nFun)
subroutine, public rflu_deallocatedcuhrearrays (global)
subroutine, public rflu_setmapfunnz2funcorr22 (nFunNZ)
subroutine, public rflu_setmapfunnz2funcorr32 (nFunNZ)
subroutine, public rflu_setmapfunnz2funcorr43 (nFunNZ)
subroutine, public rflu_setmapfunnz2funcorr44 (nFunNZ)
Public Attributes
integer, public maxcalls
integer, public ndim
integer, public neval
integer, public workarraysize
integer, public workarraysizenew
integer, parameter, public dcuhre_loop_limit = 5
integer, parameter, public max_calls_factor = 5
integer, parameter, public max_calls_limit = 50000000
integer, parameter, public max_calls_start = 100000
integer, parameter, public min_calls = 0
integer, dimension(1), public dummy
integer, dimension(:),
allocatable, public symmapi45oles
real(rfreal), public errabsreq
real(rfreal), public errrelreq
real(rfreal), dimension(:),
allocatable, public lowlim
real(rfreal), dimension(:),
allocatable, public errabsest
real(rfreal), dimension(:),
allocatable, public upplim
real(rfreal), dimension(:),
allocatable, public integral
real(rfreal), dimension(:),
allocatable, public integralnz
real(rfreal), dimension(:),
allocatable, public workarray
integer, public nzloc
integer, public nzsgn
integer, dimension(3,
3), parameter, public mapsurf2vol2 = RESHAPE((/6,4,4,4,6,5,5,5,6/), (/3,3/))
integer, dimension(3,
6), parameter, public mapsurf2vol3 = RESHAPE((/9,7,7,7,9,8,8,8,9,9,7,7,7,9,8,8,8,9/), (/3,6/))
integer, dimension(3,
3), parameter, public kd = RESHAPE((/1,0,0,0,1,0,0,0,1/), (/3,3/))
integer, dimension(9), public mapfunnz2funcorr22
integer, dimension(9), public mapfunnz2funcorr32
integer, dimension(27), public mapfunnz2funcorr43
integer, dimension(81), public mapfunnz2funcorr44
real(rfreal), public nzmag
real(rfreal), public nzval
real(rfreal), parameter, public const_kolmogorov = 2.0_RFREAL
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModOLES.F90,v $ $Revision: 1.10 $'
type(t_grid), pointer pgrid
Detailed Description
Definition at line 39 of file RFLU_ModOLES.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_allocatedcuhrearrays (type(t_global), pointer global, integer, intent(in) nDim, integer, intent(in) nFunNZ, integer, intent(in) nFun)
Definition at line 2097 of file RFLU_ModOLES.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_buildstencilsoles (type(t_region), pointer pRegion)
Definition at line 483 of file RFLU_ModOLES.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), modtools::floatequal(), ic, modsortsearch::quicksortrfrealinteger(), moderror::registerfunction(), rflu_modoctree::rflu_buildoctree(), rflu_modoctree::rflu_createoctree(), rflu_modoctree::rflu_destroyoctree(), rflu_modoctree::rflu_queryoctree(), sqrt(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by rflu_initflowsolver().
subroutine, public rflu_buildsymmetrymapsoles (type(t_region), pointer pRegion)
Definition at line 1106 of file RFLU_ModOLES.F90.
References Color::b(), moderror::deregisterfunction(), Color::g(), j, k, moderror::registerfunction(), and rflu_getqposoles().
Referenced by rflu_initflowsolver().
subroutine, public rflu_computegeometrictermsoles (type(t_region), pointer pRegion)
Definition at line 881 of file RFLU_ModOLES.F90.
References moderror::deregisterfunction(), i, ic, j, max(), min(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
subroutine, public rflu_createintegralsoles (type(t_region), pointer pRegion)
Definition at line 283 of file RFLU_ModOLES.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), and moderror::registerfunction().
Referenced by rflu_modallocatememory::rflu_allocatememorytstep().
subroutine, public rflu_createstencilsweightsoles (type(t_region), pointer pRegion)
Definition at line 149 of file RFLU_ModOLES.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), and moderror::registerfunction().
Referenced by rflu_modallocatememory::rflu_allocatememorytstep().
subroutine, public rflu_deallocatedcuhrearrays (type(t_global), pointer global)
Definition at line 2161 of file RFLU_ModOLES.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_definecorrelation220 (integer, intent(in) nDim, double precision, dimension(ndim), intent(in) z, integer, intent(in) nFunNZ, double precision, dimension(nfunnz), intent(inout) f)
Definition at line 1304 of file RFLU_ModOLES.F90.
References j, and rflu_mapk2ij().
Referenced by rflu_computeintegral2oles().
subroutine, public rflu_definecorrelation221 (integer, intent(in) nDim, double precision, dimension(ndim), intent(in) z, integer, intent(in) nFunNZ, double precision, dimension(nfunnz), intent(inout) f)
Definition at line 1333 of file RFLU_ModOLES.F90.
References j, modtools::makenonzero(), rflu_mapk2ij(), and z.
Referenced by rflu_computeintegral2oles().
subroutine, public rflu_definecorrelation32 (integer, intent(in) nDim, double precision, dimension(ndim), intent(in) z, integer, intent(in) nFunNZ, double precision, dimension(nfunnz), intent(inout) f)
Definition at line 1369 of file RFLU_ModOLES.F90.
References i, rflu_mapk2ij(), and z.
Referenced by rflu_computeintegral1oles().
subroutine, public rflu_definecorrelation430 (integer, intent(in) nDim, double precision, dimension(ndim), intent(in) z, integer, intent(in) nFunNZ, double precision, dimension(nfunnz), intent(inout) f)
Definition at line 1415 of file RFLU_ModOLES.F90.
References i, Aff_transformation_2< R_ >::m(), and rflu_mapl2ijk().
Referenced by rflu_computeintegral4oles().
subroutine, public rflu_definecorrelation431 (integer, intent(in) nDim, double precision, dimension(ndim), intent(in) z, integer, intent(in) nFunNZ, double precision, dimension(nfunnz), intent(inout) f)
Definition at line 1450 of file RFLU_ModOLES.F90.
References i, j, Aff_transformation_2< R_ >::m(), modtools::makenonzero(), rflu_mapl2ijk(), and z.
Referenced by rflu_computeintegral4oles().
subroutine, public rflu_definecorrelation432 (integer, intent(in) nDim, double precision, dimension(ndim), intent(in) z, integer, intent(in) nFunNZ, double precision, dimension(nfunnz), intent(inout) f)
Definition at line 1536 of file RFLU_ModOLES.F90.
References i, j, Aff_transformation_2< R_ >::m(), modtools::makenonzero(), rflu_mapl2ijk(), and z.
Referenced by rflu_computeintegral4oles().
subroutine, public rflu_definecorrelation540 (integer, intent(in) nDim, double precision, dimension(ndim), intent(in) z, integer, intent(in) nFunNZ, double precision, dimension(nfunnz), intent(inout) f)
Definition at line 1612 of file RFLU_ModOLES.F90.
References j, k, Aff_transformation_2< R_ >::m(), and rflu_mapm2ijkl().
Referenced by rflu_computeintegral5oles().
subroutine, public rflu_definecorrelation541 (integer, intent(in) nDim, double precision, dimension(ndim), intent(in) z, integer, intent(in) nFunNZ, double precision, dimension(nfunnz), intent(inout) f)
Definition at line 1644 of file RFLU_ModOLES.F90.
References j, k, Aff_transformation_2< R_ >::m(), modtools::makenonzero(), rflu_mapm2ijkl(), and z.
Referenced by rflu_computeintegral5oles().
subroutine, public rflu_definecorrelation542 (integer, intent(in) nDim, double precision, dimension(ndim), intent(in) z, integer, intent(in) nFunNZ, double precision, dimension(nfunnz), intent(inout) f)
Definition at line 1724 of file RFLU_ModOLES.F90.
References j, k, Aff_transformation_2< R_ >::m(), modtools::makenonzero(), rflu_mapm2ijkl(), and z.
Referenced by rflu_computeintegral5oles().
subroutine, public rflu_destroystencilsweightsoles (type(t_region), pointer pRegion)
Definition at line 2024 of file RFLU_ModOLES.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_moddeallocatememory::rflu_deallocatememorytstep(), and rflu_endflowsolver().
subroutine, public rflu_enforcesymmetryoles (type(t_region), pointer pRegion)
Definition at line 1179 of file RFLU_ModOLES.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
subroutine, public rflu_findprototypefacesoles (type(t_region), pointer pRegion)
Definition at line 742 of file RFLU_ModOLES.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
integer function, public rflu_geti1posoles (integer, intent(in) l, integer, intent(in) d)
Definition at line 1890 of file RFLU_ModOLES.F90.
References Plane_3< R, T >::d().
Referenced by rflu_computeenerdissoles(), rflu_computeintegral1oles(), rflu_computeintegral2oles(), rflu_computeintegral3oles(), rflu_readintegrals1245oles(), and rflu_writeintegrals1245oles().
integer function, public rflu_geti4posoles (integer, intent(in) l, integer, intent(in) m, integer, intent(in) d, integer, intent(in) e, integer, intent(in) nCells)
Definition at line 1909 of file RFLU_ModOLES.F90.
References Plane_3< R, T >::d(), and Aff_transformation_2< R_ >::m().
Referenced by rflu_computeintegral3oles(), rflu_computeintegral4oles(), rflu_computeintegral5oles(), rflu_readintegrals1245oles(), and rflu_writeintegrals1245oles().
subroutine, public rflu_getlposinvoles (integer, intent(in) loc, integer, intent(out) j, integer, intent(out) a)
Definition at line 1948 of file RFLU_ModOLES.F90.
References Line_2< R, T >::a(), and j.
Referenced by rflu_computeweightsoles().
integer function, public rflu_getlposoles (integer, intent(in) j, integer, intent(in) a)
Definition at line 1929 of file RFLU_ModOLES.F90.
References Line_2< R, T >::a(), and j.
Referenced by rflu_computeenerdissoles(), rflu_computeintegral2oles(), rflu_computeintegral3oles(), rflu_readintegrals1245oles(), and rflu_writeintegrals1245oles().
subroutine, public rflu_getqposinvoles (integer, intent(in) loc, integer, intent(in) nCells, integer, intent(out) j, integer, intent(out) k, integer, intent(out) b, integer, intent(out) g)
Definition at line 1989 of file RFLU_ModOLES.F90.
References Color::b(), Color::g(), j, and k.
Referenced by rflu_computeweightsoles().
integer function, public rflu_getqposoles (integer, intent(in) j, integer, intent(in) k, integer, intent(in) b, integer, intent(in) g, integer, intent(in) nCells)
Definition at line 1970 of file RFLU_ModOLES.F90.
References Color::b(), Color::g(), j, and k.
Referenced by rflu_buildsymmetrymapsoles(), rflu_computeintegral3oles(), rflu_computeintegral5oles(), rflu_readintegrals1245oles(), and rflu_writeintegrals1245oles().
subroutine, public rflu_mapk2ij (integer, intent(in) k, integer, intent(out) i, integer, intent(out) j)
Definition at line 1810 of file RFLU_ModOLES.F90.
References i, j, and k.
Referenced by rflu_computeintegral1oles(), rflu_computeintegral2oles(), rflu_definecorrelation220(), rflu_definecorrelation221(), rflu_definecorrelation32(), rflu_readintegrals1245oles(), rflu_setmapfunnz2funcorr22(), rflu_setmapfunnz2funcorr32(), and rflu_writeintegrals1245oles().
subroutine, public rflu_mapl2ijk (integer, intent(in) l, integer, intent(out) i, integer, intent(out) j, integer, intent(out) k)
Definition at line 1831 of file RFLU_ModOLES.F90.
References i, j, and k.
Referenced by rflu_computeintegral4oles(), rflu_definecorrelation430(), rflu_definecorrelation431(), rflu_definecorrelation432(), rflu_readintegrals1245oles(), rflu_setmapfunnz2funcorr43(), and rflu_writeintegrals1245oles().
subroutine, public rflu_mapm2ijkl (integer, intent(in) m, integer, intent(out) i, integer, intent(out) j, integer, intent(out) k, integer, intent(out) l)
Definition at line 1858 of file RFLU_ModOLES.F90.
References i, j, k, and Aff_transformation_2< R_ >::m().
Referenced by rflu_computeintegral5oles(), rflu_definecorrelation540(), rflu_definecorrelation541(), rflu_definecorrelation542(), rflu_readintegrals1245oles(), rflu_setmapfunnz2funcorr44(), and rflu_writeintegrals1245oles().
subroutine, public rflu_setmapfunnz2funcorr22 (integer, intent(in) nFunNZ)
Definition at line 2223 of file RFLU_ModOLES.F90.
References j, and rflu_mapk2ij().
Referenced by rflu_computeintegral2oles().
subroutine, public rflu_setmapfunnz2funcorr32 (integer, intent(in) nFunNZ)
Definition at line 2266 of file RFLU_ModOLES.F90.
References i, and rflu_mapk2ij().
Referenced by rflu_computeintegral1oles().
subroutine, public rflu_setmapfunnz2funcorr43 (integer, intent(in) nFunNZ)
Definition at line 2310 of file RFLU_ModOLES.F90.
References i, Aff_transformation_2< R_ >::m(), rflu_mapl2ijk(), s, and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_computeintegral4oles().
subroutine, public rflu_setmapfunnz2funcorr44 (integer, intent(in) nFunNZ)
Definition at line 2359 of file RFLU_ModOLES.F90.
References j, k, Aff_transformation_2< R_ >::m(), rflu_mapm2ijkl(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_computeintegral5oles().
Member Data Documentation
real(rfreal), parameter, public const_kolmogorov = 2.0_RFREAL
Definition at line 135 of file RFLU_ModOLES.F90.
integer, parameter, public dcuhre_loop_limit = 5
Definition at line 106 of file RFLU_ModOLES.F90.
integer, dimension(1), public dummy
Definition at line 111 of file RFLU_ModOLES.F90.
real(rfreal), dimension(:), allocatable, public errabsest
Definition at line 115 of file RFLU_ModOLES.F90.
real(rfreal), public errabsreq
Definition at line 114 of file RFLU_ModOLES.F90.
real(rfreal), public errrelreq
Definition at line 114 of file RFLU_ModOLES.F90.
real(rfreal), dimension(:), allocatable, public integral
Definition at line 115 of file RFLU_ModOLES.F90.
real(rfreal), dimension(:), allocatable, public integralnz
Definition at line 115 of file RFLU_ModOLES.F90.
integer, dimension(3,3), parameter, public kd = RESHAPE((/1,0,0,0,1,0,0,0,1/), (/3,3/))
Definition at line 128 of file RFLU_ModOLES.F90.
real(rfreal), dimension(:), allocatable, public lowlim
Definition at line 115 of file RFLU_ModOLES.F90.
integer, dimension(9), public mapfunnz2funcorr22
Definition at line 131 of file RFLU_ModOLES.F90.
integer, dimension(9), public mapfunnz2funcorr32
Definition at line 131 of file RFLU_ModOLES.F90.
integer, dimension(27), public mapfunnz2funcorr43
Definition at line 131 of file RFLU_ModOLES.F90.
integer, dimension(81), public mapfunnz2funcorr44
Definition at line 131 of file RFLU_ModOLES.F90.
integer, dimension(3,3), parameter, public mapsurf2vol2 = RESHAPE((/6,4,4,4,6,5,5,5,6/), (/3,3/))
Definition at line 124 of file RFLU_ModOLES.F90.
integer, dimension(3,6), parameter, public mapsurf2vol3 = RESHAPE((/9,7,7,7,9,8,8,8,9,9,7,7,7,9,8,8,8,9/), (/3,6/))
Definition at line 126 of file RFLU_ModOLES.F90.
integer, parameter, public max_calls_factor = 5
Definition at line 106 of file RFLU_ModOLES.F90.
integer, parameter, public max_calls_limit = 50000000
Definition at line 106 of file RFLU_ModOLES.F90.
integer, parameter, public max_calls_start = 100000
Definition at line 106 of file RFLU_ModOLES.F90.
integer, public maxcalls
Definition at line 105 of file RFLU_ModOLES.F90.
integer, parameter, public min_calls = 0
Definition at line 106 of file RFLU_ModOLES.F90.
integer, public ndim
Definition at line 105 of file RFLU_ModOLES.F90.
integer, public neval
Definition at line 105 of file RFLU_ModOLES.F90.
integer, public nzloc
Definition at line 123 of file RFLU_ModOLES.F90.
real(rfreal), public nzmag
Definition at line 134 of file RFLU_ModOLES.F90.
integer, public nzsgn
Definition at line 123 of file RFLU_ModOLES.F90.
real(rfreal), public nzval
Definition at line 134 of file RFLU_ModOLES.F90.
type(t_grid), pointer pgrid private
Definition at line 99 of file RFLU_ModOLES.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModOLES.F90,v $ $Revision: 1.10 $' private
Definition at line 97 of file RFLU_ModOLES.F90.
integer, dimension(:), allocatable, public symmapi45oles
Definition at line 112 of file RFLU_ModOLES.F90.
real(rfreal), dimension(:), allocatable, public upplim
Definition at line 115 of file RFLU_ModOLES.F90.
real(rfreal), dimension(:), allocatable, public workarray
Definition at line 115 of file RFLU_ModOLES.F90.
integer, public workarraysize
Definition at line 105 of file RFLU_ModOLES.F90.
integer, public workarraysizenew
Definition at line 105 of file RFLU_ModOLES.F90.
The documentation for this module was generated from the following file:
RFLU_ModOLES.F90