Rocstar: LocalSizeQualityMetric Class Reference
LocalSizeQualityMetric Class Reference
Computes the local size metric for a given vertex.
#include <LocalSizeQualityMetric.hpp>
Public Member Functions
LocalSizeQualityMetric ()
virtual ~LocalSizeQualityMetric ()
LocalSizeQualityMetric ()
virtual ~LocalSizeQualityMetric ()
Public Member Functions inherited from VolumeQualityMetric
virtual ~VolumeQualityMetric ()
virtual ~VolumeQualityMetric ()
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_element (PatchData &, MsqMeshEntity *, double &, MsqError &err)
Evaluate the metric for an element.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_element (PatchData &, MsqMeshEntity *, double &, MsqError &err)
Evaluate the metric for an element.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Protected Member Functions
bool evaluate_vertex (PatchData &pd, MsqVertex *vert, double &fval, MsqError &err)
For the given vertex, vert, calculate the local size metric value.
bool evaluate_vertex (PatchData &pd, MsqVertex *vert, double &fval, MsqError &err)
For the given vertex, vert, calculate the local size metric value.
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Private Member Functions
double compute_corner_area (PatchData &pd, size_t vert_1, size_t vert_2, size_t vert_3, MsqError &err)
Calculate the area of the triangle formed by the three vertices.
double compute_corner_volume (PatchData &pd, size_t vert_1, size_t vert_2, size_t vert_3, size_t vert_4, MsqError &err)
Calculate the volume of the tetrahedron formed by the four vertices.
double compute_corner_area (PatchData &pd, size_t vert_1, size_t vert_2, size_t vert_3, MsqError &err)
Calculate the area of the triangle formed by the three vertices.
double compute_corner_volume (PatchData &pd, size_t vert_1, size_t vert_2, size_t vert_3, size_t vert_4, MsqError &err)
Calculate the volume of the tetrahedron formed by the four vertices.
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
Computes the local size metric for a given vertex.
LocalSizeQualityMetric is a vertex based metric which computes the corner volume (or area) for the element corners attached to a given element. Then these volumes (or areas) are averaged together. The default averaging method is QualityMetric::RMS.
Definition at line 61 of file includeLinks/LocalSizeQualityMetric.hpp.
Constructor & Destructor Documentation
LocalSizeQualityMetric () inline
Definition at line 65 of file includeLinks/LocalSizeQualityMetric.hpp.
References QualityMetric::avgMethod, QualityMetric::feasible, QualityMetric::RMS, QualityMetric::set_metric_type(), QualityMetric::set_name(), and QualityMetric::VERTEX_BASED.
        {
          avgMethod=RMS;
          feasible=0;
          set_metric_type(QualityMetric::VERTEX_BASED);
          set_name("Local Size Quality Metric");
        }
virtual ~LocalSizeQualityMetric () inline virtual
Definition at line 74 of file includeLinks/LocalSizeQualityMetric.hpp.
         {}
LocalSizeQualityMetric () inline
Definition at line 65 of file src/QualityMetric/Volume/LocalSizeQualityMetric.hpp.
References QualityMetric::avgMethod, QualityMetric::feasible, QualityMetric::RMS, QualityMetric::set_metric_type(), QualityMetric::set_name(), and QualityMetric::VERTEX_BASED.
        {
          avgMethod=RMS;
          feasible=0;
          set_metric_type(QualityMetric::VERTEX_BASED);
          set_name("Local Size Quality Metric");
        }
virtual ~LocalSizeQualityMetric () inline virtual
Definition at line 74 of file src/QualityMetric/Volume/LocalSizeQualityMetric.hpp.
         {}
Member Function Documentation
double compute_corner_area (PatchData & pd, size_t vert_1, size_t vert_2, size_t vert_3, MsqError & err) inline private
Calculate the area of the triangle formed by the three vertices.
Definition at line 97 of file includeLinks/LocalSizeQualityMetric.hpp.
References PatchData::get_vertex_array(), and Vector3D::length().
Referenced by LocalSizeQualityMetric::evaluate_vertex().
    {
      MsqVertex* verts = pd.get_vertex_array(err);
      Vector3D vec_1=verts[vert_2]-verts[vert_1];
      Vector3D vec_2=verts[vert_3]-verts[vert_1];
      Vector3D cross_vec=vec_1*vec_2;
      return (cross_vec.length()/2.0);
    }
double compute_corner_area (PatchData & pd, size_t vert_1, size_t vert_2, size_t vert_3, MsqError & err) inline private
Calculate the area of the triangle formed by the three vertices.
double compute_corner_volume (PatchData & pd, size_t vert_1, size_t vert_2, size_t vert_3, size_t vert_4, MsqError & err) inline private
Calculate the volume of the tetrahedron formed by the four vertices.
double compute_corner_volume (PatchData & pd, size_t vert_1, size_t vert_2, size_t vert_3, size_t vert_4, MsqError & err) inline private
Calculate the volume of the tetrahedron formed by the four vertices.
Definition at line 111 of file includeLinks/LocalSizeQualityMetric.hpp.
References PatchData::get_vertex_array().
Referenced by LocalSizeQualityMetric::evaluate_vertex().
    {
      MsqVertex* verts = pd.get_vertex_array(err);
      Vector3D vec_1=verts[vert_2]-verts[vert_1];
      Vector3D vec_2=verts[vert_3]-verts[vert_1];
      Vector3D vec_3=verts[vert_4]-verts[vert_1];
      return fabs((vec_3%(vec_1*vec_2))/6.0);
    }
bool evaluate_vertex (PatchData & pd, MsqVertex * vert, double & fval, MsqError & err) protected virtual
For the given vertex, vert, calculate the local size metric value.
Reimplemented from QualityMetric.
bool evaluate_vertex (PatchData & pd, MsqVertex * vert, double & fval, MsqError & err) protected virtual
For the given vertex, vert, calculate the local size metric value.
For the given vertex, vert, with connected elements, e_i for i=1...K, the LocalSizeQualityMetric computes the corner volumes (or areas) of each e_i at the corner defined by vert. The corner volume is defined as the volume of the tet defined by the edges of an element which contain the common vertex, vert. That volume is then diveded by the average corner volume of all the element corners connected to this vertex. For vertices attached to pyramid elements, this metric is undefined.
Reimplemented from QualityMetric.
Definition at line 61 of file QualityMetric/Volume/LocalSizeQualityMetric.cpp.
References QualityMetric::average_metrics(), LocalSizeQualityMetric::compute_corner_area(), LocalSizeQualityMetric::compute_corner_volume(), MsqMeshEntity::get_connected_vertices(), PatchData::get_element_array(), PatchData::get_vertex_element_adjacencies(), PatchData::get_vertex_index(), i, MsqError::INTERNAL_ERROR, MSQ_ERRZERO, and MSQ_SETERR.
 {
   fval=0.0;
     //get the element array
   MsqMeshEntity* elems = pd.get_element_array(err);  MSQ_ERRZERO(err);
     //conver the MsqVertex pointer into an index
   size_t this_vert = pd.get_vertex_index(vert);
     //get the vertex to element array and the offset array
   //const size_t* elem_offset = pd.get_vertex_to_elem_offset(err);  MSQ_ERRZERO(err);
   //const size_t* v_to_e_array = pd.get_vertex_to_elem_array(err);  MSQ_ERRZERO(err);
     //find the offset for this vertex
   //size_t this_offset = elem_offset[this_vert];
     //get the number of elements attached to this vertex (given by the
     //first entry in the vertex to element array)
   //size_t num_elems = v_to_e_array[this_offset];
     //PRINT_INFO("\nIN LOCAL SIZE CPP, num_elements = %i",num_elems);
   size_t num_elems, *v_to_e_array;
   v_to_e_array = pd.get_vertex_element_adjacencies( this_vert, num_elems, err );
   MSQ_ERRZERO(err);
   if(num_elems <= 0){
     return true;
   }
     //create an array to store the local metric values before averaging
     //Can we remove this dynamic allocatio?
   double* met_vals = new double[num_elems];
     //vector to hold the other verts which form a corner.
   vector<size_t> other_vertices;
   other_vertices.reserve(4);
   double total_val=0.0;
   size_t i=0;
     //loop over the elements attached to this vertex
   for(i=0;i<num_elems;++i){
       //get the vertices which (with this_vert) form the corner of
       //the ith element.
     elems[v_to_e_array[i]].get_connected_vertices(this_vert,
                                                               other_vertices,
                                                               err);  MSQ_ERRZERO(err);
     switch(other_vertices.size()){
         //if a surface element, compute the corner area
       case 2:
         met_vals[i] = compute_corner_area(pd, this_vert, other_vertices[0],
                                           other_vertices[1], err);  MSQ_ERRZERO(err);
         break;
           //if a volume element, compute the corner volume
       case 3:
         met_vals[i] = compute_corner_volume(pd, this_vert, other_vertices[0],
                                             other_vertices[1],
                                             other_vertices[2], err);  MSQ_ERRZERO(err);
         break;
       default:
           //otherwise, there is was an error.  Either the wrong number
           //of vertices were returned fom get_connected_vertices or
           //the element does not have the correct number of edges
           //connected to this vertex (possibly a pyramid element).
         met_vals[i]=0.0;
         MSQ_SETERR(err)("Incorrect number of vertices returned from "
                         "get_connected_vertices.", MsqError::INTERNAL_ERROR);
     };
       //keep track of total so that we can compute the linear average
     total_val+=met_vals[i];
     //PRINT_INFO("\nIN LOCAL SIZE CPP, total_val = %f, i = %i",total_val,i);
       //clear the vector of other_vertices for re-use.
     other_vertices.clear();
     //PRINT_INFO("\nIN LOCAL SIZE CPP, after clean size = %f",other_vertices.size());
   }
     //calculate the linear average... num_elems is non-zero here.
   total_val /= (double) num_elems;
   //PRINT_INFO("\nIN LOCAL SIZE CPP, average = %f",total_val);
     //if the average is non-zero
     //divide each entry by the linear average
   if(total_val!=0){
     for(i=0;i<num_elems;++i){
       met_vals[i]/=total_val;
     }
       //calculate fval by averaging the corner values
     fval = average_metrics(met_vals, num_elems, err);  MSQ_ERRZERO(err);
     //PRINT_INFO("\nIN LOCAL SIZE CPP, inside if statement");
   }
   //PRINT_INFO("\nIN LOCAL SIZE CPP, fval = %f",fval);
     //clean up the dynamically allocated array
   delete []met_vals;
     //always return true... the vertex position is never invalid
   return true;
 }
The documentation for this class was generated from the following files:
includeLinks/LocalSizeQualityMetric.hpp
QualityMetric/Volume/LocalSizeQualityMetric.cpp