Rocstar: Vertex_set Class Reference
Vertex_set Class Reference
#include <Overlay_primitives.h>
Public Types
typedef Vertex_set Self
typedef Vertex_overlay Vertex
typedef Halfedge_overlay Halfedge
typedef int Value
typedef unsigned int Size
Public Member Functions
Vertex_set ()
Vertex_set (const Halfedge *h)
Vertex_set (const Halfedge *h, Size)
const RFC_Pane_overlay * pane () const
int operator[] (Size i) const
Size size_of_edges () const
Size size_of_nodes () const
Protected Member Functions
Size count_edges (const Halfedge *e) const
Protected Attributes
const RFC_Pane_overlay * _pane
std::vector< int > _nodes
Size _ne
Detailed Description
Definition at line 47 of file Overlay_primitives.h.
Member Typedef Documentation
typedef Halfedge_overlay Halfedge
Definition at line 51 of file Overlay_primitives.h.
typedef Vertex_set Self
Definition at line 49 of file Overlay_primitives.h.
typedef unsigned int Size
Definition at line 53 of file Overlay_primitives.h.
typedef int Value
Definition at line 52 of file Overlay_primitives.h.
typedef Vertex_overlay Vertex
Definition at line 50 of file Overlay_primitives.h.
Constructor & Destructor Documentation
Vertex_set () inline
Definition at line 55 of file Overlay_primitives.h.
 : _pane(NULL), _ne(0) {}
Vertex_set (const Halfedge * h) explicit
Definition at line 42 of file Overlay_primitives.C.
References _ne, _nodes, _pane, RFC_Pane_base::base(), Halfedge_overlay::facet(), RFC_Pane_overlay::get_lid(), i, RFC_assertion, RFC_precondition, Element_node_enumerator::size_of_nodes(), v, and Halfedge_overlay::vertex().
   : _pane(acc.get_pane(h)), _ne(count_edges(h))
 {
   RFC_precondition ( _ne==3 || _ne==4);
   Element_node_enumerator ene( _pane->base(), _pane->get_lid( h->facet()));
   Size nn=ene.size_of_nodes();
   int r=-1;
   Value v = _pane->get_lid(h->vertex());
   _nodes.resize(nn);
   for ( Size i=0; i<nn; ++i) {
     if ((_nodes[i] = ene[i])==v) r=(i+_ne-1)%_ne;
   }
   RFC_assertion( r>=0 && r<int(_ne));
   if (r>0) {
     std::rotate( &_nodes[0], &_nodes[r], &_nodes[_ne]);
     if (nn>_ne) std::rotate( &_nodes[_ne], &_nodes[_ne+r], &_nodes[_ne+_ne]);
   }
 }
Vertex_set (const Halfedge * h, Size)
Definition at line 64 of file Overlay_primitives.C.
References _ne, _nodes, _pane, Halfedge_overlay::destination(), RFC_Pane_overlay::get_lid(), and Halfedge_overlay::origin().
   : _pane(acc.get_pane(h)), _ne(3)
 {
   _nodes.resize(_ne, -1);
   _nodes[0] = _pane->get_lid( h->origin());
   _nodes[1] = _pane->get_lid( h->destination());
 }
Member Function Documentation
Size count_edges (const Halfedge * e) const inline protected
Definition at line 71 of file Overlay_primitives.h.
References i, and Halfedge_overlay::next().
{
     Size i=0;
     const Halfedge *h=e;
     do { ++i; } while ( (h=h->next())!= e);
     return i;
   }
int operator[] (Size i) const inline
Definition at line 65 of file Overlay_primitives.h.
References _nodes, and i.
 { return _nodes[i]; }
const RFC_Pane_overlay* pane () const inline
Definition at line 64 of file Overlay_primitives.h.
References _pane.
Referenced by Point_set::operator[](), and Normal_set::operator[]().
 { return _pane; }
Size size_of_edges () const inline
Definition at line 67 of file Overlay_primitives.h.
References _ne.
Referenced by Point_set::size_of_edges(), Normal_set::size_of_edges(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return _ne; }
Size size_of_nodes () const inline
Definition at line 68 of file Overlay_primitives.h.
References _nodes.
Referenced by Point_set::size_of_nodes(), and Normal_set::size_of_nodes().
 { return _nodes.size(); }
Member Data Documentation
Size _ne protected
Definition at line 80 of file Overlay_primitives.h.
Referenced by size_of_edges(), and Vertex_set().
std::vector<int> _nodes protected
Definition at line 79 of file Overlay_primitives.h.
Referenced by operator[](), size_of_nodes(), and Vertex_set().
const RFC_Pane_overlay* _pane protected
Definition at line 78 of file Overlay_primitives.h.
Referenced by pane(), and Vertex_set().
The documentation for this class was generated from the following files:
Overlay_primitives.h
Overlay_primitives.C