Rocstar: StopWatch Class Reference
StopWatch Class Reference
#include <MsqTimer.hpp>
Public Member Functions
StopWatch ()
void start ()
void stop ()
void reset ()
double total_time () const
int number_of_starts () const
Returns the number of times this StopWatch has been started.
StopWatch ()
void start ()
void stop ()
void reset ()
double total_time () const
int number_of_starts () const
Returns the number of times this StopWatch has been started.
Private Attributes
bool isRunning
double timeAtLastStart
double totalTime
int numStarts
Detailed Description
Definition at line 76 of file includeLinks/MsqTimer.hpp.
Constructor & Destructor Documentation
StopWatch () inline
Definition at line 81 of file includeLinks/MsqTimer.hpp.
         :isRunning(false), totalTime(0.0), numStarts(0)
       {}
StopWatch () inline
Definition at line 81 of file src/Misc/MsqTimer.hpp.
         :isRunning(false), totalTime(0.0), numStarts(0)
       {}
Member Function Documentation
int number_of_starts () const inline
Returns the number of times this StopWatch has been started.
Definition at line 103 of file includeLinks/MsqTimer.hpp.
References StopWatch::numStarts.
{
         return numStarts;
       }
int number_of_starts () const inline
Returns the number of times this StopWatch has been started.
Definition at line 103 of file src/Misc/MsqTimer.hpp.
References StopWatch::numStarts.
{
         return numStarts;
       }
void reset ()
void reset ()
Definition at line 124 of file Misc/MsqTimer.cpp.
 {
   isRunning=false;
   totalTime=0;
   numStarts=0;
 }
void start ()
Definition at line 105 of file Misc/MsqTimer.cpp.
 {
   if (!isRunning)
   {
     isRunning = true;
     timeAtLastStart=now();
     ++numStarts;
   }
 }
void start ()
void stop ()
Definition at line 115 of file Misc/MsqTimer.cpp.
Referenced by __scalegrd.f90__(), a_d_tensors(), generic_list::abort(), ainv(), update_py::burn_get_burning_rate1d(), burn_initialize(), rflu_modrepair3d::cavbnd(), rflu_modrepair3d::cavedg(), rflu_modrepair3d::cavity(), setup_py::check_input_range(), checkindxrange(), rflu_modrepair3d::colaps(), compositestiffnes(), rflu_modrepair3d::datsrf(), rflu_modrepair3d::edgerm(), element_sub(), moderror::errorstop(), eshelby(), rflu_modrepair3d::fangle(), feminp(), find_nodes(), m_rocburn_1d_zn::get_burning_rate_1d(), get_external_loads(), implicit_v3d8_mass(), rflu_modrepair3d::input(), rflu_modrepair3d::insert(), invert2(), jacobi(), rflu_modrepair3d::lock(), main(), matous_const_model(), matvol_sub(), mesh2d(), mesh2doverlay(), meshsoft_sub(), micromechanical_sub(), rflu_modrepair3d::neighb(), newcommlist(), newton(), rflu_modrepair3d::octfil(), rflu_modrepair3d::octfnd(), rflu_modoctree::octree(), rflu_modrepair3d::octrmv(), peul_rocflo_post(), plag_cecellssenddata(), plag_readsolutionfilepost(), plag_rflu_modcomm::plag_rflu_loadbufferssend(), plag_rflu_modcomm::plag_rflu_unloadbuffersrecv(), printtofluinput(), rflu_modrepair3d::putpnt(), read_files(), read_frac(), read_patran(), readinp(), rflu_modrepair3d::recon(), rflu_modrepair3d::replace(), rflo_modboundaryconditions::rflo_bcondinflowvpperf(), rflo_modboundaryconditions::rflo_bcondinflowvtperf(), rflo_checkvalidity(), rflo_modextrapolation::rflo_extrapregdummynode(), rflo_modextrapolation::rflo_extrapreglastnode(), rflo_modfinitedifference::rflo_findiffcompi(), rflo_modfinitedifference::rflo_findiffcompii(), rflo_modfinitedifference::rflo_findiffcompiis(), rflo_modfinitedifference::rflo_findiffcompis(), rflo_modfinitedifference::rflo_findiffcompj(), rflo_modfinitedifference::rflo_findiffcompjj(), rflo_modfinitedifference::rflo_findiffcompjjs(), rflo_modfinitedifference::rflo_findiffcompjs(), rflo_modfinitedifference::rflo_findiffcompk(), rflo_modfinitedifference::rflo_findiffcompkk(), rflu_modfacelist::rflu_buildavface2borderlist(), rflu_modfacelist::rflu_buildavface2patchlist(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modstencilscells::rflu_buildc2cstencilbasic_1d(), rflu_modstencilsfaces::rflu_buildf2cstencil_1d(), rflu_modplottingvars::rflu_buildplottingvarmaps(), rflu_modcoloring::rflu_col_buildcolorings(), rflu_modcommlists::rflu_comm_buildcommlistsvert(), rflu_modcommlists::rflu_comm_countborders(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_modresidual::rflu_getresidualsupport1(), rflu_modresidual::rflu_getresidualsupport2(), rflu_modincelltest::rflu_ict_testfacequadbilinear(), rflu_modoctree::rflu_queryoctree(), rflu_modrepair3d::rflu_repair3d(), rflu_modsymmetryperiodic::rflu_sype_readtransforms(), rflucells(), rfluconv(), rfluinit(), rflumap(), rflump(), rflupart(), rflupick(), rflupost(), rocflo_blocks(), rocflo_init(), rocflo_post(), rocflo_split(), rocflo_surf(), rocflo_toflu(), rocfracsubinterface::rocfracinterfaceinitial(), rocfracprep(), rocpart_post(), rocvav_post(), rvav_readfilestream1(), rvav_readfilestream2(), select_bbx(), rflu_modrepair3d::sliver(), rflu_modrepair3d::snglar(), solve_x(), rflu_modrepair3d::struct(), tensormul(), rflu_modrepair3d::tessel(), rflu_modrepair3d::tetloc(), rflu_modrepair3d::tetmv(), tractpressload(), rflu_modrepair3d::triswp(), v3d10_capacitance(), v3d10_mass(), v3d4(), v3d4_capacitance(), v3d4_mass(), v3d4_neohookeancompress(), v3d4_neohookeanincompress(), v3d4_neohookeanincompressdef(), v3d4_neohookeanincompressprin(), v3d4_nl_arruda_boyce(), v3d4_thermalexp2(), v3d4n_mass(), v3d4n_neohookeancompress(), v3d4n_neohookeanincompress(), v3d4n_nl(), v3d4n_nl_arruda_boyce(), v3d8_mass(), rflu_modrepair3d::volput(), volratio(), zn(), zn_calc_burning_rate(), zn_gen_grid(), and zn_sswsb().
 {
   if (isRunning)
   {
     isRunning = false;
     totalTime += now() - timeAtLastStart;
   }
 }
void stop ()
double total_time () const
Definition at line 131 of file Misc/MsqTimer.cpp.
Referenced by read_msh(), and write_msh().
 {
   double rv = totalTime;
   if (isRunning)
     rv += now() - timeAtLastStart;
   return rv;
 }
double total_time () const
Member Data Documentation
bool isRunning private
Definition at line 109 of file includeLinks/MsqTimer.hpp.
int numStarts private
Definition at line 112 of file includeLinks/MsqTimer.hpp.
Referenced by StopWatch::number_of_starts().
double timeAtLastStart private
Definition at line 110 of file includeLinks/MsqTimer.hpp.
double totalTime private
Definition at line 111 of file includeLinks/MsqTimer.hpp.
The documentation for this class was generated from the following files:
includeLinks/MsqTimer.hpp
Misc/MsqTimer.cpp