Rocstar: _HDS_vector_halfedge< V, H, F > Class Template Reference
_HDS_vector_halfedge< V, H, F > Class Template Reference
#include <Halfedge_data_structure_using_vector.h>
Public Types
typedef H Base
typedef _HDS_vector_vertex< V,
H, F > Vertex
typedef _HDS_vector_halfedge
< V, H, F > Halfedge
typedef _HDS_vector_facet< V,
H, F > Facet
typedef H::Supports_halfedge_prev Supports_halfedge_prev
typedef H::Supports_halfedge_vertex Supports_halfedge_vertex
typedef H::Supports_halfedge_facet Supports_halfedge_facet
typedef H Base
typedef _HDS_vector_vertex< V,
H, F > Vertex
typedef _HDS_vector_halfedge
< V, H, F > Halfedge
typedef _HDS_vector_facet< V,
H, F > Facet
typedef H::Supports_halfedge_prev Supports_halfedge_prev
typedef H::Supports_halfedge_vertex Supports_halfedge_vertex
typedef H::Supports_halfedge_facet Supports_halfedge_facet
Public Member Functions
Halfedge * opposite ()
Halfedge * next ()
Halfedge * prev ()
Vertex * vertex ()
Facet * facet ()
const Halfedge * opposite () const
const Halfedge * next () const
const Halfedge * prev () const
const Vertex * vertex () const
const Facet * facet () const
void set_next (Halfedge *h)
void set_prev (Halfedge *h)
void set_vertex (Vertex *ve)
void set_facet (Facet *facet)
Halfedge * opposite ()
Halfedge * next ()
Halfedge * prev ()
Vertex * vertex ()
Facet * facet ()
const Halfedge * opposite () const
const Halfedge * next () const
const Halfedge * prev () const
const Vertex * vertex () const
const Facet * facet () const
void set_next (Halfedge *h)
void set_prev (Halfedge *h)
void set_vertex (Vertex *ve)
void set_facet (Facet *facet)
Private Member Functions
void set_opposite (void *h)
void set_opposite (void *h)
Detailed Description
template<class V, class H, class F>
class _HDS_vector_halfedge< V, H, F >
Definition at line 89 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
Member Typedef Documentation
typedef H Base
Definition at line 114 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef H Base
Definition at line 136 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_facet<V,H,F> Facet
Definition at line 117 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_facet<V,H,F> Facet
Definition at line 139 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_halfedge<V,H,F> Halfedge
Definition at line 116 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_halfedge<V,H,F> Halfedge
Definition at line 138 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef H::Supports_halfedge_facet Supports_halfedge_facet
Definition at line 121 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef H::Supports_halfedge_facet Supports_halfedge_facet
Definition at line 143 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef H::Supports_halfedge_prev Supports_halfedge_prev
Definition at line 119 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef H::Supports_halfedge_prev Supports_halfedge_prev
Definition at line 141 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef H::Supports_halfedge_vertex Supports_halfedge_vertex
Definition at line 120 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef H::Supports_halfedge_vertex Supports_halfedge_vertex
Definition at line 142 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_vertex<V,H,F> Vertex
Definition at line 115 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_vertex<V,H,F> Vertex
Definition at line 137 of file include/CGAL/Halfedge_data_structure_using_vector.h.
Member Function Documentation
Facet* facet () inline
Definition at line 127 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (Facet*)(H::facet());}
const Facet* facet () const inline
Definition at line 133 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (const Facet*)(H::facet());}
Facet* facet () inline
Definition at line 149 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (Facet*)(H::facet());}
const Facet* facet () const inline
Definition at line 155 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (const Facet*)(H::facet());}
Halfedge* next () inline
Definition at line 124 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (Halfedge*)(H::next());}
const Halfedge* next () const inline
Definition at line 130 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (const Halfedge*)(H::next());}
Halfedge* next () inline
Definition at line 146 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (Halfedge*)(H::next());}
const Halfedge* next () const inline
Definition at line 152 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (const Halfedge*)(H::next());}
Halfedge* opposite () inline
Definition at line 123 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References opposite().
Referenced by Halfedge_data_structure_using_vector< V, H, F >::new_edge().
 {return (Halfedge*)(H::opposite());}
const Halfedge* opposite () const inline
Definition at line 129 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References opposite().
 {return (const Halfedge*)(H::opposite());}
Halfedge* opposite () inline
Definition at line 145 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References opposite().
 {return (Halfedge*)(H::opposite());}
const Halfedge* opposite () const inline
Definition at line 151 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References opposite().
 {return (const Halfedge*)(H::opposite());}
Halfedge* prev () inline
Definition at line 125 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (Halfedge*)(H::prev());}
const Halfedge* prev () const inline
Definition at line 131 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (const Halfedge*)(H::prev());}
Halfedge* prev () inline
Definition at line 147 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (Halfedge*)(H::prev());}
const Halfedge* prev () const inline
Definition at line 153 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (const Halfedge*)(H::prev());}
void set_facet (Facet * facet) inline
Definition at line 138 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_facet(facet);}
void set_facet (Facet * facet) inline
Definition at line 160 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_facet(facet);}
void set_next (Halfedge * h) inline
Definition at line 135 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_next(h);}
void set_next (Halfedge * h) inline
Definition at line 157 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_next(h);}
void set_opposite (void * h) inline private
Definition at line 141 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_opposite(h);}
void set_opposite (void * h) inline private
Definition at line 163 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_opposite(h);}
void set_prev (Halfedge * h) inline
Definition at line 136 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_prev(h);}
void set_prev (Halfedge * h) inline
Definition at line 158 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_prev(h);}
void set_vertex (Vertex * ve) inline
Definition at line 137 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_vertex(ve);}
void set_vertex (Vertex * ve) inline
Definition at line 159 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 { H::set_vertex(ve);}
Vertex* vertex () inline
Definition at line 126 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (Vertex*)(H::vertex());}
const Vertex* vertex () const inline
Definition at line 132 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (const Vertex*)(H::vertex());}
Vertex* vertex () inline
Definition at line 148 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (Vertex*)(H::vertex());}
const Vertex* vertex () const inline
Definition at line 154 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {return (const Vertex*)(H::vertex());}
The documentation for this class was generated from the following file:
CGAL/include/CGAL/Halfedge_data_structure_using_vector.h