Rocstar: Segment_2< R, T > Class Template Reference
Segment_2< R, T > Class Template Reference
#include <cartesian_classes.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Segment_2_base RSegment_2
Public Member Functions
Segment_2 ()
~Segment_2 ()
Segment_2 (const CGAL::Segment_2< R > &s)
Segment_2 (const CGAL::Point_2< R > &sp, const CGAL::Point_2< R > &ep)
Segment_2 (const RSegment_2 &s)
bool is_horizontal () const
bool is_vertical () const
bool has_on (const CGAL::Point_2< R > &p) const
bool collinear_has_on (const CGAL::Point_2< R > &p) const
bool operator== (const CGAL::Segment_2< R > &s) const
bool operator!= (const CGAL::Segment_2< R > &s) const
CGAL::Point_2< R > start () const
CGAL::Point_2< R > end () const
CGAL::Point_2< R > source () const
CGAL::Point_2< R > target () const
CGAL::Point_2< R > min () const
CGAL::Point_2< R > max () const
CGAL::Point_2< R > vertex (int i) const
CGAL::Point_2< R > point (int i) const
CGAL::Point_2< R > operator[] (int i) const
FT squared_length () const
CGAL::Direction_2< R > direction () const
CGAL::Segment_2< R > opposite () const
CGAL::Segment_2< R > transform (const CGAL::Aff_transformation_2< R > &t) const
CGAL::Line_2< R > supporting_line () const
bool is_degenerate () const
Bbox_2 bbox () const
Detailed Description
template<class R, class T = typename R::Rep_tag>
class Segment_2< R, T >
Definition at line 69 of file cartesian_classes.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 86 of file Segment_2.h.
typedef R_ R
Definition at line 84 of file Segment_2.h.
typedef R::Segment_2_base RSegment_2
Definition at line 87 of file Segment_2.h.
typedef R::RT RT
Definition at line 85 of file Segment_2.h.
Constructor & Destructor Documentation
Segment_2 () inline
Definition at line 89 of file Segment_2.h.
     : RSegment_2()  // does the handle stuff
   {}
~Segment_2 () inline
Definition at line 93 of file Segment_2.h.
   {}
Segment_2 (const CGAL::Segment_2< R > & s) inline
Definition at line 96 of file Segment_2.h.
     : RSegment_2((RSegment_2&)s)  // does the handle stuff
   {}
Segment_2 (const CGAL::Point_2< R > & sp, const CGAL::Point_2< R > & ep) inline
Definition at line 100 of file Segment_2.h.
     :  RSegment_2(sp,ep)
   {}
Segment_2 (const RSegment_2< R, T > & s) inline
Definition at line 106 of file Segment_2.h.
     : RSegment_2(s)  // does the handle stuff
   {}
Member Function Documentation
Bbox_2 bbox () const inline
Definition at line 179 of file Segment_2.h.
   { return source().bbox() + target().bbox(); }
bool collinear_has_on (const CGAL::Point_2< R > & p) const inline
Definition at line 120 of file Segment_2.h.
   { return RSegment_2::collinear_has_on(p); }
CGAL::Direction_2<R> direction () const inline
Definition at line 160 of file Segment_2.h.
   { return RSegment_2::direction(); }
CGAL::Point_2<R> end () const inline
Definition at line 133 of file Segment_2.h.
   { return RSegment_2::end(); }
bool has_on (const CGAL::Point_2< R > & p) const inline
Definition at line 117 of file Segment_2.h.
   { return RSegment_2::has_on(p); }
bool is_degenerate () const inline
Definition at line 176 of file Segment_2.h.
   { return RSegment_2::is_degenerate(); }
bool is_horizontal () const inline
Definition at line 111 of file Segment_2.h.
   { return RSegment_2::is_horizontal(); }
bool is_vertical () const inline
Definition at line 114 of file Segment_2.h.
   { return RSegment_2::is_vertical(); }
CGAL::Point_2<R> max () const inline
Definition at line 145 of file Segment_2.h.
   { return RSegment_2::max(); }
CGAL::Point_2<R> min () const inline
Definition at line 142 of file Segment_2.h.
   { return RSegment_2::min(); }
bool operator!= (const CGAL::Segment_2< R > & s) const inline
Definition at line 127 of file Segment_2.h.
   { return !(*this == s); }
bool operator== (const CGAL::Segment_2< R > & s) const inline
Definition at line 124 of file Segment_2.h.
   { return RSegment_2::operator==(s); }
CGAL::Point_2<R> operator[] (int i) const inline
Definition at line 154 of file Segment_2.h.
   { return vertex(i); }
CGAL::Segment_2<R> opposite () const inline
Definition at line 163 of file Segment_2.h.
   { return CGAL::Segment_2<R>(target(),source()); }
CGAL::Point_2<R> point (int i) const inline
Definition at line 151 of file Segment_2.h.
   { return RSegment_2::vertex(i); }
CGAL::Point_2<R> source () const inline
Definition at line 136 of file Segment_2.h.
Referenced by Segment_2< R >::bbox(), CGAL::do_intersect(), and Segment_2< R >::opposite().
   { return RSegment_2::source(); }
FT squared_length () const inline
Definition at line 157 of file Segment_2.h.
   { return RSegment_2::squared_length(); }
CGAL::Point_2<R> start () const inline
Definition at line 130 of file Segment_2.h.
   { return RSegment_2::start(); }
CGAL::Line_2<R> supporting_line () const inline
Definition at line 173 of file Segment_2.h.
   { return RSegment_2::supporting_line(); }
CGAL::Point_2<R> target () const inline
Definition at line 139 of file Segment_2.h.
Referenced by Segment_2< R >::bbox(), CGAL::do_intersect(), and Segment_2< R >::opposite().
   { return RSegment_2::target(); }
CGAL::Segment_2<R> transform (const CGAL::Aff_transformation_2< R > & t) const inline
Definition at line 169 of file Segment_2.h.
   { return  RSegment_2::transform(t); }
CGAL::Point_2<R> vertex (int i) const inline
Definition at line 148 of file Segment_2.h.
Referenced by Segment_2< R >::operator[]().
   { return RSegment_2::vertex(i); }
The documentation for this class was generated from the following files:
cartesian_classes.h
Segment_2.h