Rocstar: Element_node_vectors_k_const< Value > Class Template Reference
Element_node_vectors_k_const< Value > Class Template Reference
This is a helper class for accessing nodal data.
#include <Element_accessors.h>
Public Types
enum { MAX_NODES =9 }
typedef unsigned int Size
Public Member Functions
Element_node_vectors_k_const ()
Default constructor.
void set (const Value *p, Element_node_enumerator &ene, int strd)
initialize the accessor with a pointer and a specific stride.
void set (const Attribute *a, Element_node_enumerator &ene)
initialize the accessor from an attribute assiciated with a pane.
const Value & operator() (int i, int j) const
const Value & operator() (int i) const
const Value & operator[] (int i) const
Protected Attributes
const Attribute * _attr
union {
int _offsets [MAX_NODES]
const Value * _vs [MAX_NODES]
};
Detailed Description
template<class Value>
class Element_node_vectors_k_const< Value >
This is a helper class for accessing nodal data.
Definition at line 234 of file Element_accessors.h.
Member Typedef Documentation
typedef unsigned int Size
Definition at line 237 of file Element_accessors.h.
Member Enumeration Documentation
anonymous enum
Enumerator
MAX_NODES
Definition at line 236 of file Element_accessors.h.
 { MAX_NODES=9};
Constructor & Destructor Documentation
Element_node_vectors_k_const () inline
Default constructor.
Definition at line 240 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::_vs.
                                  : _attr(NULL)
   { std::fill_n( _vs, 9, reinterpret_cast<Value*>(NULL)); }
Member Function Documentation
const Value& operator() (int i, int j) const inline
Definition at line 271 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::_attr, Element_node_vectors_k_const< Value >::_offsets, Element_node_vectors_k_const< Value >::_vs, COM_assertion, i, j, and Attribute::size_of_components().
Referenced by Element_node_vectors_k< Value >::operator()(), Element_node_vectors_k_const< Value >::operator[](), and Element_node_vectors_k< Value >::operator[]().
{
     if ( _attr) {
       COM_assertion( _attr->size_of_components()>1);
       const Attribute *aj = _attr+j+1;
       return reinterpret_cast<const Value*>
         (aj->pointer())[_offsets[i]*aj->stride()];
     }
     else
       return _vs[i][j];
   }
const Value& operator() (int i) const inline
Definition at line 282 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::operator()().
Referenced by Element_node_vectors_k_const< Value >::operator()().
 { return operator()(i,0); }
const Value& operator[] (int i) const inline
Definition at line 284 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::operator()().
 { return operator()(i,0); }
void set (const Value * p, Element_node_enumerator & ene, int strd) inline
initialize the accessor with a pointer and a specific stride.
Definition at line 244 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::_attr, Element_node_vectors_k_const< Value >::_vs, COM_assertion, i, Element_node_vectors_k_const< Value >::MAX_NODES, Element_node_enumerator::size_of_nodes(), and strd.
Referenced by Rocsurf::compute_bounded_volumes(), Rocsurf::compute_element_areas(), Rocsurf::compute_element_normals(), Rocsurf::compute_signed_volumes(), Rocsurf::compute_swept_volumes(), Window_manifold_2::elements_to_nodes(), Rocmop::evaluate_face_normals(), get_normal(), Rocsurf::integrate(), FaceOffset_3::obtain_face_offset(), Rocmop::redistribute_vertices_smooth(), Element_node_vectors_k< Value >::set(), and turb_flowlmmetric().
{
     COM_assertion( ene.size_of_nodes() <= MAX_NODES);
     _attr = NULL;
     for ( int i=ene.size_of_nodes()-1; i>=0; --i)
       _vs[i] = &p[(ene[i]-1)*strd];
   }
void set (const Attribute * a, Element_node_enumerator & ene) inline
initialize the accessor from an attribute assiciated with a pane.
Definition at line 252 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::_attr, Element_node_vectors_k_const< Value >::_offsets, Element_node_vectors_k_const< Value >::_vs, COM_assertion, COM_get_sizeof(), Attribute::data_type(), i, Pane::id(), Attribute::is_nodal(), Attribute::pane(), Attribute::pointer(), Attribute::size_of_components(), Element_node_enumerator::size_of_nodes(), strd, and Attribute::stride().
{
     COM_assertion( a->is_nodal() && a->pane()->id());
     COM_assertion( sizeof(Value)==COM_get_sizeof( a->data_type(),1));
     int ncomp = a->size_of_components();
     int strd = a->stride();
     int nn = ene.size_of_nodes();
     if ( ncomp<=strd) {
       const Value *p = reinterpret_cast<const Value*>(a->pointer());
       _attr = NULL;
       for ( int i=0; i<nn; ++i) _vs[i] = &p[(ene[i]-1)*strd];
     }
     else {
       _attr = a;
       for ( int i=0; i<nn; ++i) _offsets[i] = ene[i]-1;
     }
   }
Member Data Documentation
union { ... }
const Attribute* _attr protected
Definition at line 287 of file Element_accessors.h.
Referenced by Element_node_vectors_k_const< Value >::operator()(), and Element_node_vectors_k_const< Value >::set().
int _offsets[MAX_NODES]
Definition at line 289 of file Element_accessors.h.
Referenced by Element_node_vectors_k_const< Value >::operator()(), and Element_node_vectors_k_const< Value >::set().
const Value* _vs[MAX_NODES]
Definition at line 290 of file Element_accessors.h.
Referenced by Element_node_vectors_k_const< Value >::Element_node_vectors_k_const(), Element_node_vectors_k_const< Value >::operator()(), and Element_node_vectors_k_const< Value >::set().
The documentation for this class was generated from the following file:
Element_accessors.h