Rocstar: spec_rflu_modchemistry Module Reference
spec_rflu_modchemistry Module Reference
Public Member Functions
subroutine, public spec_rflu_integratechemsrcterm (pRegion, CALLFLAG)
subroutine set_rate (pRegion)
Private Member Functions
subroutine rate_split (f, old_f, rho, press, fact, time_step, nout)
subroutine odesolve (yin, y, press, neqin, dtout, nout, outcome)
subroutine rate_stiff (neqin, time_stiff, ff, press, rrate)
subroutine drate_stiff (neqin, time_stiff, ff, press, ml, imu, drate, nrowpd)
subroutine lusolve (A, f, n)
Private Attributes
integer, parameter maxeqn = 2
integer, parameter maxrct = 1
integer nreaction
integer ntemp_spec
integer maxnwtn
real(rfreal) eps
real(rfreal) epy
real(rfreal) beta
real(rfreal) cpgas
real(rfreal), dimension(maxrct) damkholer
real(rfreal), dimension(maxeqn) mx
real(rfreal), dimension(maxeqn) mn
real(rfreal), dimension(maxrct) nn
real(rfreal), dimension(maxrct) pre
real(rfreal), dimension(maxrct) qg
real(rfreal), dimension(maxrct) thetay
real(rfreal), dimension(maxeqn) vec
real(rfreal), dimension(maxeqn,
maxeqn) mat
real(rfreal), dimension(maxeqn,
maxrct) yf
real(rfreal), dimension(maxrct) ratey
Detailed Description
Definition at line 40 of file SPEC_RFLU_ModChemistry.F90.
Member Function/Subroutine Documentation
subroutine drate_stiff (integer neqin, real(rfreal) time_stiff, real(rfreal), dimension(neqin) ff, real(rfreal) press, integer ml, integer imu, real(rfreal), dimension(nrowpd,neqin) drate, integer nrowpd) private
Definition at line 587 of file SPEC_RFLU_ModChemistry.F90.
References Aff_transformation_2< R_ >::m(), merge, and CImg< T >::sum().
Referenced by odesolve().
subroutine lusolve (real(rfreal), dimension(n,n) A, real(rfreal), dimension(n) f, integer n) private
Definition at line 663 of file SPEC_RFLU_ModChemistry.F90.
References Line_2< R, T >::a(), Plane_3< R, T >::d(), i, j, CImg< T >::sum(), and y.
Referenced by odesolve().
subroutine odesolve (real(rfreal), dimension(neqin) yin, real(rfreal), dimension(neqin) y, real(rfreal) press, integer, intent(in) neqin, real(rfreal) dtout, integer, intent(in) nout, logical outcome) private
Definition at line 416 of file SPEC_RFLU_ModChemistry.F90.
References drate_stiff(), lusolve(), rate_stiff(), and y.
Referenced by rate_split().
subroutine rate_split (real(rfreal), dimension(maxeqn) f, real(rfreal), dimension(maxeqn) old_f, real(rfreal), intent(in) rho, real(rfreal), intent(in) press, real(rfreal), intent(in) fact, real(rfreal), intent(in) time_step, integer nout) private
Definition at line 337 of file SPEC_RFLU_ModChemistry.F90.
References odesolve().
subroutine rate_stiff (integer neqin, real(rfreal) time_stiff, real(rfreal), dimension(neqin) ff, real(rfreal) press, real(rfreal), dimension(neqin) rrate) private
Definition at line 522 of file SPEC_RFLU_ModChemistry.F90.
References Aff_transformation_2< R_ >::m(), and CImg< T >::sum().
Referenced by odesolve().
subroutine set_rate (type(t_region), pointer pRegion)
Definition at line 252 of file SPEC_RFLU_ModChemistry.F90.
Referenced by spec_rflu_integratechemsrcterm().
subroutine, public spec_rflu_integratechemsrcterm (type(t_region), pointer pRegion, integer CALLFLAG)
Definition at line 91 of file SPEC_RFLU_ModChemistry.F90.
References moderror::deregisterfunction(), moderror::errorstop(), merge, mixtperf_d_prt(), mixtperf_eo_grtuvw(), mixtperf_g_cpr(), mixtperf_r_m(), Color::r(), moderror::registerfunction(), set_rate(), x, and y.
Referenced by integratesourcetermsmp(), and sourcetermsmp().
Member Data Documentation
real(rfreal) beta private
Definition at line 60 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal) cpgas private
Definition at line 60 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxrct) damkholer private
Definition at line 61 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal) eps private
Definition at line 60 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal) epy private
Definition at line 60 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxeqn,maxeqn) mat private
Definition at line 63 of file SPEC_RFLU_ModChemistry.F90.
integer, parameter maxeqn = 2 private
Definition at line 58 of file SPEC_RFLU_ModChemistry.F90.
integer maxnwtn private
Definition at line 59 of file SPEC_RFLU_ModChemistry.F90.
integer, parameter maxrct = 1 private
Definition at line 58 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxeqn) mn private
Definition at line 61 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxeqn) mx private
Definition at line 61 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxrct) nn private
Definition at line 61 of file SPEC_RFLU_ModChemistry.F90.
integer nreaction private
Definition at line 59 of file SPEC_RFLU_ModChemistry.F90.
integer ntemp_spec private
Definition at line 59 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxrct) pre private
Definition at line 61 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxrct) qg private
Definition at line 61 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxrct) ratey private
Definition at line 64 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxrct) thetay private
Definition at line 61 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxeqn) vec private
Definition at line 61 of file SPEC_RFLU_ModChemistry.F90.
real(rfreal), dimension(maxeqn,maxrct) yf private
Definition at line 63 of file SPEC_RFLU_ModChemistry.F90.
The documentation for this module was generated from the following file:
SPEC_RFLU_ModChemistry.F90