Rocstar: rflu_modentropyfixes Module Reference
rflu_modentropyfixes Module Reference
Public Member Functions
real(rfreal) function, public entropyfixhartenhyman (l, d)
Private Attributes
character(chrlen), parameter rcsidentstring = '$RCSfile: RFLU_ModEntropyFixes.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 39 of file RFLU_ModEntropyFixes.F90.
Member Function/Subroutine Documentation
real(rfreal) function, public entropyfixhartenhyman (real(rfreal), intent(in) l, real(rfreal), intent(in) d)
Definition at line 65 of file RFLU_ModEntropyFixes.F90.
References Plane_3< R, T >::d().
Referenced by rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux1_tcp(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxd1_tcp(), and rflu_modroeflux::rflu_roe_computefluxd2_tcp().
Member Data Documentation
character(chrlen), parameter rcsidentstring = '$RCSfile: RFLU_ModEntropyFixes.F90,v $ $Revision: 1.4 $' private
Definition at line 56 of file RFLU_ModEntropyFixes.F90.
The documentation for this module was generated from the following file:
RFLU_ModEntropyFixes.F90