Rocstar: Vector< DataType > Class Template Reference
Vector< DataType > Class Template Reference
Generic vector.
#include <PrimitiveTypes.H>
Public Member Functions
Vector (size_t size=0)
Vector (const Vector &p1, const Vector &p2)
Vector (DataType *a, size_t size=0)
Vector (const Vector< DataType > &v)
Vector (Vector< DataType > &v)
Vector (std::vector< DataType > &v)
Vector (const std::vector< DataType > &v)
~Vector ()
Vector & Copy (const Vector< DataType > &v)
Protected Attributes
DataType * D
Private Member Functions
void _create ()
void _destroy ()
Private Attributes
bool _mydata
size_t _size
Detailed Description
template<typename DataType>
class IRAD::Primitive::Vector< DataType >
Generic vector.
Definition at line 222 of file PrimitiveTypes.H.
Constructor & Destructor Documentation
Vector (size_t size = 0) inline
Definition at line 229 of file PrimitiveTypes.H.
References Vector< DataType >::_create().
         : _size(size)
       {
         _create();
       };
Vector (const Vector< DataType > & p1, const Vector< DataType > & p2) inline
Definition at line 234 of file PrimitiveTypes.H.
References Vector< DataType >::_create(), Vector< DataType >::_size, and Vector< DataType >::Copy().
       {
         assert(p1._size == p2._size);
         _size = p1._size;
         _create();
         Copy(p2-p1);
       };
Vector (DataType * a, size_t size = 0) inline
Definition at line 241 of file PrimitiveTypes.H.
References Vector< DataType >::_mydata, and Vector< DataType >::D.
         : _size(size)
       {
         _mydata = false;
         D = a;
       };
Vector (const Vector< DataType > & v) inline
Definition at line 247 of file PrimitiveTypes.H.
References Vector< DataType >::_create(), Vector< DataType >::_size, and Vector< DataType >::Copy().
       {
         _size = v._size;
         _create();
         Copy(v);
       };
Vector (Vector< DataType > & v) inline
Definition at line 253 of file PrimitiveTypes.H.
References Vector< DataType >::_mydata, Vector< DataType >::_size, and Vector< DataType >::D.
       {
         _mydata = false;
         _size = v._size;
         D = v.D;
       };
Vector (std::vector< DataType > & v) inline
Definition at line 259 of file PrimitiveTypes.H.
References Vector< DataType >::_mydata, Vector< DataType >::_size, and Vector< DataType >::D.
       {
         _mydata = false;
         _size = v.size();
         D = &v[0];
       };
Vector (const std::vector< DataType > & v) inline
Definition at line 265 of file PrimitiveTypes.H.
References Vector< DataType >::_create(), Vector< DataType >::_size, Vector< DataType >::D, and i.
       {
         _size = v.size();
         _create();
         size_t i = 0;
         typename std::vector<DataType>::const_iterator vi = v.begin();
         while(vi != v.end())
           D[i++] = *vi++;
       };
~Vector () inline
Definition at line 274 of file PrimitiveTypes.H.
References Vector< DataType >::_destroy().
       {
         _destroy();
       };
Member Function Documentation
void _create () inline private
Definition at line 496 of file PrimitiveTypes.H.
References Vector< DataType >::_mydata, Vector< DataType >::_size, and Vector< DataType >::D.
Referenced by Vector< DataType >::Vector().
       {
         if(_size > 0){
           D = new DataType [_size];
           _mydata = true;
         }
         else{
           _size = 0;
           _mydata = false;
           D = NULL;
         }
       };
void _destroy () inline private
Definition at line 508 of file PrimitiveTypes.H.
References Vector< DataType >::_mydata, and Vector< DataType >::D.
Referenced by Vector< DataType >::~Vector().
       {
         if(_mydata){
           delete [] D;
           _mydata = false;
           D = NULL;
         }
       };
Vector& Copy (const Vector< DataType > & v) inline
Definition at line 278 of file PrimitiveTypes.H.
References Vector< DataType >::_size, Vector< DataType >::D, and i.
Referenced by Vector< DataType >::Vector().
       {
         for(size_t i = 0;i < _size;i++)
           D[i] = v[i];
         return(*this);
       };
Member Data Documentation
bool _mydata private
Definition at line 224 of file PrimitiveTypes.H.
Referenced by Vector< DataType >::_create(), Vector< DataType >::_destroy(), and Vector< DataType >::Vector().
size_t _size private
Definition at line 225 of file PrimitiveTypes.H.
Referenced by Vector< DataType >::_create(), Vector< DataType >::Copy(), and Vector< DataType >::Vector().
DataType* D protected
Definition at line 227 of file PrimitiveTypes.H.
Referenced by Vector< DataType >::_create(), Vector< DataType >::_destroy(), Vector< DataType >::Copy(), and Vector< DataType >::Vector().
The documentation for this class was generated from the following file:
PrimitiveTypes.H