Rocstar: rflu_modbessel Module Reference
rflu_modbessel Module Reference
Public Member Functions
subroutine, public rflu_jyndd (N, X, BJN, DJN, FJN, BYN, DYN, FYN)
subroutine, public rflu_jyzo (N, NT, RJ0, RJ1, RY0, RY1)
subroutine, public rflu_jyzom (N, M, RJ0M, RJ1M, RY0M, RY1M)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModBessel.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 42 of file RFLU_ModBessel.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_jyndd (integer N, double precision, intent(in) X, double precision, intent(out) BJN, double precision, intent(out) DJN, double precision, intent(out) FJN, double precision, intent(out) BYN, double precision, intent(out) DYN, double precision, intent(out) FYN)
Definition at line 94 of file RFLU_ModBessel.F90.
References by, Plane_3< R, T >::d(), TestBase::f1(), k, Aff_transformation_2< R_ >::m(), and x.
Referenced by rflu_modexactflow::rflu_computeexactflowpacoust(), and rflu_jyzo().
subroutine, public rflu_jyzo (integer N, integer NT, double precision, dimension(nt), intent(out) RJ0, double precision, dimension(nt), intent(out) RJ1, double precision, dimension(nt), intent(out) RY0, double precision, dimension(nt), intent(out) RY1)
Definition at line 200 of file RFLU_ModBessel.F90.
References Plane_3< R, T >::d(), rflu_jyndd(), and x.
Referenced by rflu_jyzom().
subroutine, public rflu_jyzom (integer N, integer M, double precision, intent(out) RJ0M, double precision, intent(out) RJ1M, double precision, intent(out) RY0M, double precision, intent(out) RY1M)
Definition at line 315 of file RFLU_ModBessel.F90.
References Aff_transformation_2< R_ >::m(), and rflu_jyzo().
Referenced by rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), and rflu_initflowhardcode().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModBessel.F90,v $ $Revision: 1.4 $' private
Definition at line 57 of file RFLU_ModBessel.F90.
The documentation for this module was generated from the following file:
RFLU_ModBessel.F90