Rocstar: rflu_modweights Module Reference
rflu_modweights Module Reference
Public Member Functions
subroutine, public rflu_createwtsbf2cwrapper (pRegion, pPatch, order)
subroutine, public rflu_createwtsc2cwrapper (pRegion, order)
subroutine, public rflu_createwtsf2cwrapper (pRegion, order)
subroutine, public rflu_computewtsbf2cwrapper (pRegion, pPatch, order)
subroutine, public rflu_computewtsc2cwrapper (pRegion, order)
subroutine, public rflu_computewtsf2cwrapper (pRegion, order)
subroutine, public rflu_computewtsx2c_1d (global, m, nMembs, x, z, w)
subroutine, public rflu_destroywtsbf2cwrapper (pRegion, pPatch)
subroutine, public rflu_destroywtsc2cwrapper (pRegion)
subroutine, public rflu_destroywtsf2cwrapper (pRegion)
Private Member Functions
subroutine rflu_createwtsbf2c (pRegion, pPatch, orderInput)
subroutine rflu_createwtsc2c (pRegion, order)
subroutine rflu_createwtsf2c (pRegion, orderInput)
subroutine rflu_computewtsbf2c (pRegion, pPatch, orderInput)
subroutine rflu_computewtsc2c (pRegion, order)
subroutine rflu_computewtsf2c (pRegion, orderInput)
subroutine rflu_computestencilmoments2d1 (global, nMembs, dr, xyzMoms)
subroutine rflu_computestencilmoments3d1 (global, nMembs, dr, xyzMoms)
subroutine rflu_destroywtsbf2c (pRegion, pPatch)
subroutine rflu_destroywtsc2c (pRegion)
subroutine rflu_destroywtsf2c (pRegion)
subroutine rflu_nullifywtsbf2c (pRegion, pPatch)
subroutine rflu_nullifywtsc2c (pRegion)
subroutine rflu_nullifywtsf2c (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModWeights.F90,v $ $Revision: 1.16 $'
Detailed Description
Definition at line 39 of file RFLU_ModWeights.F90.
Member Function/Subroutine Documentation
subroutine rflu_computestencilmoments2d1 (type(t_global), pointer global, integer, intent(in) nMembs, real(rfreal), dimension(xcoord:ycoord,nmembs), intent(inout) dr, real(rfreal), dimension(xyz_mom_11:xyz_mom_33), intent(inout) xyzMoms) private
Definition at line 1623 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), moderror::registerfunction(), and sqrt().
Referenced by rflu_computewtsbf2c(), rflu_computewtsc2c(), and rflu_computewtsf2c().
subroutine rflu_computestencilmoments3d1 (type(t_global), pointer global, integer, intent(in) nMembs, real(rfreal), dimension(xcoord:zcoord,nmembs), intent(inout) dr, real(rfreal), dimension(xyz_mom_11:xyz_mom_44), intent(inout) xyzMoms) private
Definition at line 1754 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::registerfunction(), and sqrt().
Referenced by rflu_computewtsbf2c(), rflu_computewtsc2c(), and rflu_computewtsf2c().
subroutine rflu_computewtsbf2c (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) orderInput) private
Definition at line 748 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), Generic_element_2::order(), moderror::registerfunction(), rflu_computestencilmoments2d1(), and rflu_computestencilmoments3d1().
Referenced by rflu_computewtsbf2cwrapper().
subroutine, public rflu_computewtsbf2cwrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) order)
Definition at line 923 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), and rflu_computewtsbf2c().
Referenced by rflu_initflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
subroutine rflu_computewtsc2c (type(t_region), pointer pRegion, integer, intent(in) order) private
Definition at line 1003 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), rflu_computestencilmoments2d1(), and rflu_computestencilmoments3d1().
Referenced by rflu_computewtsc2cwrapper().
subroutine, public rflu_computewtsc2cwrapper (type(t_region), pointer pRegion, integer, intent(in) order)
Definition at line 1163 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), and rflu_computewtsc2c().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_postprocessregionscommon1(), and rflu_timestepping().
subroutine rflu_computewtsf2c (type(t_region), pointer pRegion, integer, intent(in) orderInput) private
Definition at line 1242 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), Generic_element_2::order(), moderror::registerfunction(), rflu_computestencilmoments2d1(), and rflu_computestencilmoments3d1().
Referenced by rflu_computewtsf2cwrapper().
subroutine, public rflu_computewtsf2cwrapper (type(t_region), pointer pRegion, integer, intent(in) order)
Definition at line 1412 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), and rflu_computewtsf2c().
Referenced by rflu_initflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
subroutine, public rflu_computewtsx2c_1d (type(t_global), pointer global, integer, intent(in) m, integer, intent(in) nMembs, real(rfreal), dimension(0:nmembs-1), intent(in) x, real(rfreal), intent(in) z, real(rfreal), dimension(0:nmembs-1), intent(out) w)
Definition at line 1497 of file RFLU_ModWeights.F90.
References Line_2< R, T >::c(), moderror::deregisterfunction(), i, j, k, Aff_transformation_2< R_ >::m(), min(), moderror::registerfunction(), x, and z.
Referenced by rflu_moddifferentiationbfaces::rflu_computegradbfaces_1d(), and rflu_moddifferentiationcells::rflu_computegradcells_1d().
subroutine rflu_createwtsbf2c (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) orderInput) private
Definition at line 100 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), Generic_element_2::order(), moderror::registerfunction(), and rflu_nullifywtsbf2c().
Referenced by rflu_createwtsbf2cwrapper().
subroutine, public rflu_createwtsbf2cwrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) order)
Definition at line 240 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), and rflu_createwtsbf2c().
Referenced by rflu_initflowsolver().
subroutine rflu_createwtsc2c (type(t_region), pointer pRegion, integer, intent(in) order) private
Definition at line 320 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), and rflu_nullifywtsc2c().
Referenced by rflu_createwtsc2cwrapper().
subroutine, public rflu_createwtsc2cwrapper (type(t_region), pointer pRegion, integer, intent(in) order)
Definition at line 452 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), and rflu_createwtsc2c().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().
subroutine rflu_createwtsf2c (type(t_region), pointer pRegion, integer, intent(in) orderInput) private
Definition at line 532 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), Generic_element_2::order(), moderror::registerfunction(), and rflu_nullifywtsf2c().
Referenced by rflu_createwtsf2cwrapper().
subroutine, public rflu_createwtsf2cwrapper (type(t_region), pointer pRegion, integer, intent(in) order)
Definition at line 669 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), and rflu_createwtsf2c().
Referenced by rflu_initflowsolver().
subroutine rflu_destroywtsbf2c (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1901 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifywtsbf2c().
Referenced by rflu_destroywtsbf2cwrapper().
subroutine, public rflu_destroywtsbf2cwrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 2000 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_destroywtsbf2c().
Referenced by rflu_endflowsolver().
subroutine rflu_destroywtsc2c (type(t_region), pointer pRegion) private
Definition at line 2077 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifywtsc2c().
Referenced by rflu_destroywtsc2cwrapper().
subroutine, public rflu_destroywtsc2cwrapper (type(t_region), pointer pRegion)
Definition at line 2175 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_destroywtsc2c().
Referenced by rflu_endflowsolver(), rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().
subroutine rflu_destroywtsf2c (type(t_region), pointer pRegion) private
Definition at line 2253 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifywtsf2c().
Referenced by rflu_destroywtsf2cwrapper().
subroutine, public rflu_destroywtsf2cwrapper (type(t_region), pointer pRegion)
Definition at line 2348 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_destroywtsf2c().
Referenced by rflu_endflowsolver().
subroutine rflu_nullifywtsbf2c (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 2425 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createwtsbf2c(), and rflu_destroywtsbf2c().
subroutine rflu_nullifywtsc2c (type(t_region), pointer pRegion) private
Definition at line 2501 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createwtsc2c(), and rflu_destroywtsc2c().
subroutine rflu_nullifywtsf2c (type(t_region), pointer pRegion) private
Definition at line 2573 of file RFLU_ModWeights.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createwtsf2c(), and rflu_destroywtsf2c().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModWeights.F90,v $ $Revision: 1.16 $' private
Definition at line 69 of file RFLU_ModWeights.F90.
The documentation for this module was generated from the following file:
RFLU_ModWeights.F90