Rocstar: Geo_Metric_Base_2 Class Reference
Geo_Metric_Base_2 Class Reference
2D Geometric Metric Base Class
#include <Geometric_Metrics_2.h>
Public Member Functions
Geo_Metric_Base_2 ()
Constructor.
virtual void initialize (Vector_3< double > n[], int type)
Initialize a 2D Geometric Metric.
virtual void initialize (Element_node_enumerator &ene)
virtual double maxValue () const
The maximum value for this metric.
virtual double minValue () const
The minimum value for this metric.
Public Member Functions inherited from Metric
Metric ()
virtual ~Metric ()
virtual void compute (double atts[]) const =0
Compute the value of this metric.
Protected Member Functions
void compute_angles (double &min, double &max) const
Compute the min and max angles.
void compute_aspects (double &R, double &r, double &l) const
Compute the circumradius, inradius, and shortest edge length.
Protected Attributes
Vector_3< double > v [4]
int type_
Detailed Description
2D Geometric Metric Base Class
This class is the base class for the implementation of various 2D geometric element quality metrics.
Definition at line 41 of file Geometric_Metrics_2.h.
Constructor & Destructor Documentation
Geo_Metric_Base_2 () inline
Constructor.
Definition at line 46 of file Geometric_Metrics_2.h.
 {}
Member Function Documentation
void compute_angles (double & min, double & max) const protected
Compute the min and max angles.
Definition at line 76 of file Geometric_Metrics_2.C.
References angle(), min_max3(), min_max4(), and v.
{
   if (type_ == COM::Connectivity::TRI3){
     double a1,a2,a3;
     a1= angle(v[0],v[2]); a2= angle(v[1],v[3]); a3= angle(v[2],v[3]);
     min_max3(a1,a2,a3,min,max);
   }
   if (type_ == COM::Connectivity::QUAD4){
     double a1,a2,a3,a4;
     a1 = angle (v[0],v[1]); a2 = angle (v[0],v[2]);
     a3 = angle (v[2],v[3]); a4 = angle (v[1],v[3]);
     min_max4(a1,a2,a3,a4,min,max);
   }
 }
void compute_aspects (double & R, double & r, double & l) const protected
Compute the circumradius, inradius, and shortest edge length.
Definition at line 90 of file Geometric_Metrics_2.C.
References edge_length(), sqrt(), and v.
{
   // Defined for Triangles only
   assert (type_ == COM::Connectivity::TRI3);
   double a = edge_length(v[0]);
   double b = edge_length(v[2]);
   double c = edge_length(v[3]);
   // Use formulas from mathworld to find circumradius (R),
   // inradius (r), and shortest edge length (l)
   l = ( a < b )? a : b;
   l = ( l < c ) ? l : c;
   R = (a*b*c) / sqrt( (a+b+c)*(b+c-a)*(c+a-b)*(a+b-c) );
   r = .5*sqrt( ((b+c-a)*(c+a-b)*(a+b-c))/(a+b+c) );
 }
void initialize (Vector_3< double > n[], int type) virtual
Initialize a 2D Geometric Metric.
Parameters
n[] Ordered set of nodal coordinates.
type Element type: TRI or QUAD
Implements Metric.
Definition at line 65 of file Geometric_Metrics_2.C.
References v.
Referenced by main().
{
   type_ = type;
   if (type_ == COM::Connectivity::TRI3){
     v[0]= n[2]-n[1]; v[1]= n[1]-n[2]; v[2]= n[2]-n[0]; v[3]= n[1]-n[0];
   }
   else if (type_ == COM::Connectivity::QUAD4){
     v[0]= n[1]-n[0]; v[1]= n[3]-n[0]; v[2]= n[1]-n[2]; v[3]= n[3] - n[2];
   }
 }
void initialize (Element_node_enumerator & ene) virtual
Implements Metric.
Definition at line 46 of file Geometric_Metrics_2.C.
References COM_assertion_msg, and v.
{
   type_ = ene.type();
   Element_node_vectors_k_const<double> n;
   n.set(ene.pane()->attribute("nc"),ene);
   if(type_ == COM::Connectivity::TRI3){
     v[0][0]=n(2,0)-n(1,0); v[0][1]=n(2,1)-n(1,1); v[0][2]=n(2,2)-n(1,2);
     v[1][0]=n(1,0)-n(2,0); v[1][1]=n(1,1)-n(2,1); v[1][2]=n(1,2)-n(2,2);
     v[2][0]=n(2,0)-n(0,0); v[2][1]=n(2,1)-n(0,1); v[2][2]=n(2,2)-n(0,2);
     v[3][0]=n(1,0)-n(0,0); v[3][1]=n(1,1)-n(0,1); v[3][2]=n(1,2)-n(0,2);
   }
   else if (type_ == COM::Connectivity::QUAD4){
     v[0][0]=n(1,0)-n(0,0); v[0][1]=n(1,1)-n(0,1); v[0][2]=n(1,2)-n(0,2);
     v[1][0]=n(3,0)-n(0,0); v[1][1]=n(3,1)-n(0,1); v[1][2]=n(3,2)-n(0,2);
     v[2][0]=n(1,0)-n(2,0); v[2][1]=n(1,1)-n(2,1); v[2][2]=n(1,2)-n(2,2);
     v[3][0]=n(3,0)-n(2,0); v[3][1]=n(3,1)-n(2,1); v[3][2]=n(3,2)-n(2,2);
   }
   else COM_assertion_msg(0,"Element type not supported for 2D geometric metrics");
 }
virtual double maxValue () const inline virtual
The maximum value for this metric.
Implements Metric.
Reimplemented in Aspect_Metric_2, and Angle_Metric_2.
Definition at line 58 of file Geometric_Metrics_2.h.
 { return 1.0; }
virtual double minValue () const inline virtual
The minimum value for this metric.
Implements Metric.
Reimplemented in Aspect_Metric_2, and Angle_Metric_2.
Definition at line 61 of file Geometric_Metrics_2.h.
 { return 0.0; }
Member Data Documentation
int type_ protected
Definition at line 73 of file Geometric_Metrics_2.h.
Vector_3<double> v[4] protected
Definition at line 72 of file Geometric_Metrics_2.h.
The documentation for this class was generated from the following files:
Geometric_Metrics_2.h
Geometric_Metrics_2.C