Rocstar: Connectivity Class Reference
Connectivity Class Reference
Encapsulates an element-connectivity of a mesh.
#include <Connectivity.h>
Public Types
enum Connectivity_type {
ST1, ST2, ST3, BAR2,
BAR3, TRI3, TRI6, QUAD4,
QUAD8, QUAD9, TET4, TET10,
PYRIMID5, PYRIMID14, PRISM6, PRISM15,
PRISM18, HEX8, HEX20, HEX27,
TYPE_MAX_CONN
}
enum Connectivity_info {
TYPE_ID, SIZE_DIM, ORDER, SIZE_NNODES,
SIZE_NCORN, SIZE_NEDGES, SIZE_NFACES, SIZE_MAX_CONN
}
typedef unsigned char Shorter_size
One byte unsighed int.
typedef unsigned int Size
Unsighed int.
Public Member Functions
bool is_const () const
Returns whether the array is set to be read-only.
Constructors and destructor
Connectivity (Pane *pane, const std::string &name, int id, const int sizes[], int type=COM_INT)
Create an attribute with name n in window w.
Connectivity (Pane *pane, Connectivity *con, const std::string &name, int id)
Construct from another connectivity table.
Identity
Connectivity * parent ()
Parent attribute being used.
const Connectivity * parent () const
Connectivity * root ()
Root of use-inheritance.
const Connectivity * root () const
void inherit (Connectivity *parent, bool clone, bool withghost) throw (COM_exception)
Inherit a connectivity table.
int element_type () const
Obtain element type ID.
int dimension () const
Get the dimension of the mesh.
bool is_structured () const
Determine whether the mesh is quadratic.
bool is_quadratic () const
Determine whether the element type is quadratic.
Array information
const int * pointer () const
Get a constant pointer to the connectivity array.
int * pointer ()
Get a pointer to the connectivity array.
const int * get_addr (int i, int j=0) const throw (COM_exception)
Obtain the address of the jth component of the ith item, where 0<=i<size_of_items.
int * get_addr (int i, int j=0) throw (COM_exception)
Protected Member Functions
void set_pointer (void *p, int strd, int cap, bool is_const) throw (COM_exception)
Set pointer of connectivity table.
void set_offset (Size offset) throw (COM_exception)
Set the index of the first element.
Protected Member Functions inherited from Attribute
void set_pointer (void *p, int strd, int cap, int offset, bool is_const) throw (COM_exception)
Set the physical address of the attribute values.
void inherit (Attribute *a, bool clone, bool withghost, int depth=0) throw (COM_exception)
Inherit from parent. If depth>0, then the procedure is for the subcomponents.
Attribute (Pane *pane, int i)
Constructor for keywords. The default nitems for keywords is 0.
void set_size (int nitems, int ngitems=0) throw (COM_exception)
Set the size of items and ghost items.
void * allocate (int strd, int cap, bool force) throw (COM_exception)
Allocate memory for the attribute.
int deallocate () throw (COM_exception)
Deallocate memory if it was allocated by allocate().
void copy_array (void *buf, int strd, int nitem, int offset=0, int direction=COPY_IN) throw (COM_exception)
void append_array (const void *from, int strd, int nitem) throw (COM_exception)
const std::string & name () const
Obtain the name of the attribute.
std::string fullname () const
Obtain the full name of the attribute including window name suitable for printing out error messages.
int id () const
Obtain the id (or index) of the attribute.
Attribute * parent ()
Parent attribute used by this object.
const Attribute * parent () const
Attribute * root ()
Root of use-inheritance.
const Attribute * root () const
const void * pointer () const
Obtain a constant pointer to the physical address.
void * pointer () throw (COM_exception)
Obtain a modifiable pointer to the physical address.
const void * get_addr (int i, int j=0) const throw (COM_exception)
Obtain the address of the jth component of the ith item, where 0<=i<size_of_items.
void * get_addr (int i, int j=0) throw (COM_exception)
Attribute ()
Default constructor.
Attribute (Pane *pane, const std::string &name, int id, Shorter_size loc, int type, const int ncomp, const std::string &unit)
Create an attribute with name n in window w.
Attribute (Pane *pane, Attribute *parent, const std::string &name, int id)
Inherit an attribute from another.
~Attribute ()
Destructors.
const Pane * pane () const
Obtain a constant pointer to the owner pane of the attribute.
Pane * pane ()
Obtain a modifiable pointer to the owner pane of the attribute.
const Window * window () const
Obtain a constant pointer to the parent window of the attribute.
Window * window ()
Obtain a modifiable pointer to the parent window of the attribute.
Shorter_size location () const
Obtain the location of the attribute.
bool is_windowed () const
Checks whether the attribute is associated with the window.
bool is_panel () const
Checks whether the attribute is associated with a pane.
bool is_elemental () const
Checks whether the attribute is associated with an element.
bool is_nodal () const
Checks whether the attribute is associated with a node.
COM_Type data_type () const
Obtain the data type of each component of the attribute.
const std::string & unit () const
Obtain the unit of the attribute.
int size_of_components () const
Obtain the number of components in the attribute.
int size_of_items () const
Obtain the number of items in the attribute.
int maxsize_of_items () const
Obtain the maximum allowed number of items in the attribute.
int size_of_ghost_items () const
Obtain the number of ghost items in the attribute.
int maxsize_of_ghost_items () const
Obtain the maximum allowed number of items in the attribute.
int size_of_real_items () const
Obtain the number of real items in the attribute.
int maxsize_of_real_items () const
Obtain the maximum allowed number of real items in the attribute.
bool empty () const
Check whether the number of items of the attribute is zero.
int capacity () const
Obtain the capacity of the array.
int stride () const
Obtain the stride of the attribute in base datatype.
int stride_in_bytes () const
Obtain the stride of the attribute in bytes.
int status () const
Obtain the status of the attribute.
bool initialized () const
Returns whether the array for the attribute has been set or allocated.
bool size_set () const
Returns whether the size for the attribute has been set.
bool allocated () const
Returns whether the array for the attribute has been set or allocated.
bool is_const () const
Returns whether the array is set to be read-only.
bool is_staggered () const
Check how the attribute values are organized.
Protected Attributes
int _offset
Offset of the first element.
const int * _size_info
Protected Attributes inherited from Attribute
Pane * _pane
Pointer to its owner pane.
Attribute * _parent
Parent attribute being used.
std::string _name
Name of the attribute.
int _id
Id field data.
Shorter_size _loc
Location.
int _ncomp
Number of components.
COM_Type _type
Base data type of the attribute.
std::string _unit
Unit of the attribute.
int _nitems
Size of total items. Default value is -1.
int _ngitems
Size of ghost items.
int _gap
Gap between the IDs of real and ghost items.
Shorter_size _status
Indicating whether it has been initialized.
void * _ptr
Physical address of the attribute.
int _strd
Stride.
int _nbytes_strd
Number of bytes of the stride.
int _cap
Capacity.
Static Protected Attributes
static const int _sizes [TYPE_MAX_CONN][SIZE_MAX_CONN]
Static Protected Attributes inherited from Attribute
static const char * _keywords [COM_NUM_KEYWORDS]
List of keywords.
static const char _keylocs [COM_NUM_KEYWORDS]
Default locations.
static const COM_Type _keytypes [COM_NUM_KEYWORDS]
Default data types.
static const int _keysizes [COM_NUM_KEYWORDS]
Default sizes.
Size information
Size size_of_corners_pe () const
Get the number of corners per element of the current connectivity table.
Size size_of_nodes_pe () const
Get the number of nodes per element of the current connectivity table.
Size size_of_edges_pe () const
Get the number of edges per element of the current connectivity table.
Size size_of_faces_pe () const
Get the number of faces per element of the current connectivity table.
Size size_of_elements () const
Get the total number of elements (including ghost elements) in the table.
Size size_of_ghost_elements () const
Get the number of ghost elements.
Size size_of_real_elements () const
Get the number of real elements.
Size size_of_nodes () const
Get the total number of nodes (including ghost nodes) of the owner pane.
Size size_of_ghost_nodes () const
Get the number of ghost nodes of the owner pane.
Size size_of_real_nodes () const
Get the number of real nodes of the owner pane.
Size index_offset () const
Get the index of the first element.
Size size_i () const
Get the number of nodes in i-dimension if the mesh is structured.
Size size_j () const
Get the number of nodes in j-dimension if the mesh is structured.
Size size_k () const
Get the number of nodes in k-dimension if the mesh is structured.
static Size size_of_corners_pe (int type)
Get the number of corners per element of the given type of element.
static Size size_of_nodes_pe (int type)
Get the number of nodes per element of the given type of element.
static Size size_of_edges_pe (int type)
Get the number of edges per element of the given type of element.
static Size size_of_faces_pe (int type)
Get the number of faces per element of the given type of element.
Helpers
void * allocate (int strd, int cap, bool force) throw (COM_exception)
Allocate memory for unstructured mesh.
void set_size (int nitems, int ngitems=0) throw (COM_exception)
Set the size of items and ghost items.
static bool is_element_name (const std::string &aname)
static const int * get_size_info (const std::string &aname)
Obtain the size info of pre-defined connectivity.
Additional Inherited Members
Protected Types inherited from Attribute
enum {
STATUS_NOT_INITIALIZED =0, STATUS_SET =1, STATUS_SET_CONST =2, STATUS_USE =3,
STATUS_ALLOCATED =4
}
enum Copy_dir { COPY_IN, COPY_OUT }
typedef unsigned char Shorter_size
One byte unsighed int.
typedef unsigned int Size
Unsighed int.
Static Protected Member Functions inherited from Attribute
static int get_sizeof (COM_Type type, int count=1)
static bool compatible_types (COM_Type t1, COM_Type t2)
static bool is_digit (char c)
Detailed Description
Encapsulates an element-connectivity of a mesh.
It supports both structured and unstructured meshes.
Definition at line 41 of file Connectivity.h.
Member Typedef Documentation
typedef unsigned char Shorter_size
One byte unsighed int.
Definition at line 53 of file Attribute.h.
typedef unsigned int Size
Unsighed int.
Definition at line 54 of file Attribute.h.
Member Enumeration Documentation
enum Connectivity_info
Enumerator
TYPE_ID
SIZE_DIM
ORDER
SIZE_NNODES
SIZE_NCORN
SIZE_NEDGES
SIZE_NFACES
SIZE_MAX_CONN
Definition at line 50 of file Connectivity.h.
     { TYPE_ID, SIZE_DIM, ORDER, SIZE_NNODES, SIZE_NCORN,
       SIZE_NEDGES, SIZE_NFACES, SIZE_MAX_CONN};
enum Connectivity_type
Enumerator
ST1
ST2
ST3
BAR2
BAR3
TRI3
TRI6
QUAD4
QUAD8
QUAD9
TET4
TET10
PYRIMID5
PYRIMID14
PRISM6
PRISM15
PRISM18
HEX8
HEX20
HEX27
TYPE_MAX_CONN
Definition at line 43 of file Connectivity.h.
     { ST1, ST2, ST3, /* structured mesh */
       BAR2, BAR3,    /* 1d unstructured mesh */
       TRI3, TRI6, QUAD4, QUAD8, QUAD9, /* 2d unstructured mesh */
       TET4, TET10, PYRIMID5, PYRIMID14, PRISM6, PRISM15, PRISM18,
       HEX8, HEX20, HEX27, /* 3d unstructured mesh */
       TYPE_MAX_CONN};
Constructor & Destructor Documentation
Connectivity (Pane * pane, const std::string & name, int id, const int sizes[], int type = COM_INT) inline
Create an attribute with name n in window w.
Parameters
pane pointer to its owner pane object.
parent parent connectivity (for supporting inheritance).
name connectivity name.
id connectivity ID (always negative).
sizes size information about the element type.
type base data type.
Definition at line 90 of file Connectivity.h.
     : Attribute( pane, name, id, 'p', type,
                  /* for structured meshes, ncomp is 1 */
                  (sizes[TYPE_ID]<=ST3)?1:sizes[SIZE_NNODES], ""),
       _offset(0), _size_info(sizes) {}
Connectivity (Pane * pane, Connectivity * con, const std::string & name, int id) inline
Construct from another connectivity table.
Definition at line 98 of file Connectivity.h.
     : Attribute( pane, (Attribute*)con, name, id),
       _offset(con->_offset), _size_info( con->_size_info) {}
Member Function Documentation
void* allocate (int strd, int cap, bool force) throw (COM_exception) inline
Allocate memory for unstructured mesh.
Definition at line 236 of file Connectivity.h.
References Attribute::allocate(), cap, COM_ERR_ALLOC_STRUCTURED, is_structured(), and strd.
{
     if ( !is_structured()) return Attribute::allocate( strd, cap, force);
     else throw COM_exception(COM_ERR_ALLOC_STRUCTURED);
   }
int dimension () const inline
Get the dimension of the mesh.
Definition at line 125 of file Connectivity.h.
References _size_info, and SIZE_DIM.
Referenced by cauchystressprinc(), get_enhanced_map(), get_external_loads(), get_jacobien(), get_mixed_map(), jacobi(), kronecker_product(), size_j(), size_k(), and tensormul().
 { return _size_info[SIZE_DIM]; }
int element_type () const inline
Obtain element type ID.
Definition at line 122 of file Connectivity.h.
References _size_info, and TYPE_ID.
Referenced by Element_node_enumerator::type().
 { return _size_info[TYPE_ID]; }
const int * get_addr (int i, int j = 0) const throw (COM_exception)
Obtain the address of the jth component of the ith item, where 0<=i<size_of_items.
This function is recursive and relatively expensive, and hence should be used only for performance-insenstive tasks.
Definition at line 64 of file Connectivity.C.
References append_frame, COM_ERR_INDEX_OUT_OF_BOUNDS, Attribute::get_addr(), i, j, and offset().
{
   if ( _parent)  return root()->get_addr( i,j);
   // Check that i is between 0 and size_of_items-1.
   if ( i<0 || i>=size_of_items())
     throw COM_exception( COM_ERR_INDEX_OUT_OF_BOUNDS, append_frame
                          ( fullname(), Attribute::get_addr));
   int offset = ( _strd == 1) ? (j*_cap) : j;
   return  ((const int*)_ptr)+offset+i*_strd;
 }
int* get_addr (int i, int j = 0) throw (COM_exception) inline
Definition at line 216 of file Connectivity.h.
References COM_ERR_ATTRIBUTE_CONST, is_const(), and j.
{
     if ( is_const()) throw COM_exception( COM_ERR_ATTRIBUTE_CONST);
     return (int*)(((const Connectivity*)this)->get_addr(i,j));
   }
const int * get_size_info (const std::string & aname) static
Obtain the size info of pre-defined connectivity.
Definition at line 234 of file Connectivity.C.
References _sizes, BAR2, BAR3, COM_assertion, HEX20, HEX27, HEX8, PRISM15, PRISM18, PRISM6, PYRIMID14, PYRIMID5, QUAD4, QUAD8, QUAD9, ST1, ST2, ST3, TET10, TET4, TRI3, TRI6, and TYPE_ID.
Referenced by Pane::connectivity(), and Window::get_attribute().
 {
   int idx = 2;
   switch (aname[1]) {
   case 'b':
     while (aname[idx]=='0') idx++;
     if ( aname[idx]=='2')
     { COM_assertion( _sizes[BAR2][TYPE_ID]==BAR2); return _sizes[BAR2]; }
     if ( aname[idx]=='3')
     { COM_assertion( _sizes[BAR3][TYPE_ID]==BAR3); return _sizes[BAR3]; }
     break;
   case 't':
     while (aname[idx]=='0') idx++;
     if ( aname[idx]=='3')
     { COM_assertion( _sizes[TRI3][TYPE_ID]==TRI3); return _sizes[TRI3]; }
     if ( aname[idx]=='6')
     { COM_assertion( _sizes[TRI6][TYPE_ID]==TRI6); return _sizes[TRI6]; }
     break;
   case 'q':
     while (aname[idx]=='0') idx++;
     if ( aname[idx]=='4')
     { COM_assertion( _sizes[QUAD4][TYPE_ID]==QUAD4); return _sizes[QUAD4]; }
     if ( aname[idx]=='8')
     { COM_assertion( _sizes[QUAD8][TYPE_ID]==QUAD8); return _sizes[QUAD8]; }
     if ( aname[idx]=='9')
     { COM_assertion( _sizes[QUAD9][TYPE_ID]==QUAD9); return _sizes[QUAD9]; }
     break;
   case 'T':
     while (aname[idx]=='0') idx++;
     if ( aname[idx]=='4')
     { COM_assertion( _sizes[TET4][TYPE_ID]==TET4); return _sizes[TET4]; }
     if ( aname[idx]=='1' && aname[idx+1]=='0')
     { COM_assertion( _sizes[TET10][TYPE_ID]==TET10); return _sizes[TET10]; }
     break;
   case 'H':
   case 'B':
     while (aname[idx]=='0') idx++;
     if ( aname[idx]=='8')
     { COM_assertion( _sizes[HEX8][TYPE_ID]==HEX8); return _sizes[HEX8]; }
     if ( aname[idx]=='2') {
       if ( aname[idx+1]=='0')
       { COM_assertion( _sizes[HEX20][TYPE_ID]==HEX20); return _sizes[HEX20]; }
       if ( aname[idx+1]=='7')
       { COM_assertion( _sizes[HEX27][TYPE_ID]==HEX27); return _sizes[HEX27]; }
     }
     break;
   case 'P':
     while (aname[idx]=='0') idx++;
     if ( aname[idx]=='5') {
       COM_assertion( _sizes[PYRIMID5][TYPE_ID]==PYRIMID5);
       return _sizes[PYRIMID5];
     }
     if ( aname[idx]=='6') {
       COM_assertion( _sizes[PRISM6][TYPE_ID]==PRISM6);
       return _sizes[PRISM6];
     }
     if ( aname[idx]=='1') {
       if ( aname[idx+1] == '4') {
         COM_assertion( _sizes[PYRIMID14][TYPE_ID]==PYRIMID14);
         return _sizes[PYRIMID14];
       }
       if ( aname[idx+1] == '5') {
         COM_assertion( _sizes[PRISM15][TYPE_ID]==PRISM15);
         return _sizes[PRISM15];
       }
       if ( aname[idx+1] == '8') {
         COM_assertion( _sizes[PRISM18][TYPE_ID]==PRISM18);
         return _sizes[PRISM18];
       }
     }
     break;
   case 'W':
     while (aname[idx]=='0') idx++;
     if ( aname[idx]=='6') {
       COM_assertion( _sizes[PRISM6][TYPE_ID]==PRISM6);
       return _sizes[PRISM6];
     }
     if ( aname[idx]=='1') {
       if ( aname[idx+1] == '5') {
         COM_assertion( _sizes[PRISM15][TYPE_ID]==PRISM15);
         return _sizes[PRISM15];
       }
       if ( aname[idx+1] == '8') {
         COM_assertion( _sizes[PRISM18][TYPE_ID]==PRISM18);
         return _sizes[PRISM18];
       }
     }
     break;
   case 's':
     if ( aname[idx++]=='t') {
       while (aname[idx]=='0') idx++;
       if ( aname[idx]=='3')
       { COM_assertion( _sizes[ST3][TYPE_ID]==ST3); return _sizes[ST3]; }
       if ( aname[idx]=='2')
       { COM_assertion( _sizes[ST2][TYPE_ID]==ST2); return _sizes[ST2]; }
       if ( aname[idx]=='1')
       { COM_assertion( _sizes[ST1][TYPE_ID]==ST1); return _sizes[ST1]; }
     }
     break;
   default: break;
   }
   return NULL;
 }
Size index_offset () const inline
Get the index of the first element.
Definition at line 189 of file Connectivity.h.
References _offset, and root().
Referenced by Pane::connectivity(), Element_node_enumerator::Element_node_enumerator(), Element_node_enumerator::id(), Element_node_enumerator::next(), and Element_node_enumerator_uns::next().
 { return root()->_offset; }
void inherit (Connectivity * parent, bool clone, bool withghost) throw (COM_exception) inline
Inherit a connectivity table.
Definition at line 118 of file Connectivity.h.
References Attribute::inherit(), and parent().
   { Attribute::inherit( parent, clone, withghost); }
bool is_const () const inline
Returns whether the array is set to be read-only.
Definition at line 223 of file Connectivity.h.
References Attribute::is_const(), and is_structured().
Referenced by get_addr().
 { return is_structured() || Attribute::is_const(); }
static bool is_element_name (const std::string & aname) inline static
Definition at line 228 of file Connectivity.h.
Referenced by Window::alloc_array(), Window::append_array(), Window::copy_array(), Window::dealloc_array(), Window::get_array(), Window::get_attribute(), Window::get_parent(), Window::get_size(), Window::get_status(), Window::new_attribute(), Window::resize_array(), Window::set_array(), and Window::set_size().
{
     return aname[0] == ':';
   }
bool is_quadratic () const inline
Determine whether the element type is quadratic.
Definition at line 132 of file Connectivity.h.
References _size_info, and ORDER.
Referenced by Element_node_enumerator::is_quadratic().
 { return _size_info[ORDER] == 2; }
bool is_structured () const inline
Determine whether the mesh is quadratic.
Definition at line 128 of file Connectivity.h.
References _size_info, ST3, and TYPE_ID.
Referenced by allocate(), is_const(), size_of_elements(), size_of_ghost_elements(), size_of_ghost_nodes(), size_of_nodes(), size_of_real_elements(), and size_of_real_nodes().
   { return _size_info[TYPE_ID] <= ST3; }
Connectivity* parent () inline
Parent attribute being used.
Definition at line 108 of file Connectivity.h.
Referenced by inherit(), and Window::reinit_conn().
 { return (Connectivity*)_parent;  }
const Connectivity* parent () const inline
Definition at line 109 of file Connectivity.h.
References Attribute::_parent.
 { return (const Connectivity*)_parent; }
const int* pointer () const inline
Get a constant pointer to the connectivity array.
Definition at line 206 of file Connectivity.h.
Referenced by Element_node_enumerator::Element_node_enumerator(), Element_node_enumerator::id(), Pane::inherit(), Element_node_enumerator::next(), Element_node_enumerator_uns::next(), size_i(), size_j(), size_k(), size_of_elements(), size_of_ghost_elements(), size_of_ghost_nodes(), size_of_nodes(), size_of_real_elements(), and size_of_real_nodes().
 { return (const int*)Attribute::pointer(); }
int* pointer () inline
Get a pointer to the connectivity array.
Definition at line 209 of file Connectivity.h.
References Attribute::pointer().
 { return (int*)Attribute::pointer(); }
Connectivity* root () inline
Root of use-inheritance.
Definition at line 112 of file Connectivity.h.
References Attribute::root().
Referenced by index_offset().
   { return (Connectivity*)(Attribute::root()); }
const Connectivity* root () const inline
Definition at line 114 of file Connectivity.h.
References Attribute::root().
   { return (const Connectivity*)(Attribute::root()); }
void set_offset (Size offset) throw (COM_exception) protected
Set the index of the first element.
Definition at line 92 of file Connectivity.C.
References offset().
Referenced by Pane::refresh_connectivity().
{
   _offset = offset;
 }
void set_pointer (void * p, int strd, int cap, bool is_const) throw (COM_exception) protected
Set pointer of connectivity table.
Definition at line 216 of file Connectivity.C.
References Attribute::allocate(), cap, COM_assertion, Attribute::set_pointer(), Attribute::set_size(), and strd.
 {
   if ( !is_structured()) {
     Attribute::set_pointer( p, strd, cap, 0, is_const);
   }
   else {
     int ndims = dimension();
     Attribute::set_size( ndims, _ngitems);
     _ptr = Attribute::allocate( 1, ndims, true);
     copy_array( p, strd, ndims);
     // Update number of nodes and elements
     COM_assertion( _parent==NULL);
     _pane->refresh_connectivity();
   }
 }
void set_size (int nitems, int ngitems = 0) throw (COM_exception)
Set the size of items and ghost items.
Can be changed only if the attribute is a root.
Definition at line 76 of file Connectivity.C.
References append_frame, and COM_ERR_CHANGE_INHERITED.
{
   if ( _parent)
     throw COM_exception( COM_ERR_CHANGE_INHERITED,
                          append_frame( fullname(), Connectivity::set_size));
   if ( !is_structured()) {
     _nitems = nitems; _ngitems = ngitems;
     _pane->refresh_connectivity();
   }
   else {
     _nitems = dimension(); _ngitems = ngitems;
     if ( initialized()) _pane->refresh_connectivity();
   }
 }
Size size_i () const inline
Get the number of nodes in i-dimension if the mesh is structured.
Definition at line 192 of file Connectivity.h.
References pointer().
   { return pointer()[0]; }
Size size_j () const inline
Get the number of nodes in j-dimension if the mesh is structured.
Definition at line 195 of file Connectivity.h.
References dimension(), and pointer().
   { return dimension()>1?pointer()[1]:1; }
Size size_k () const inline
Get the number of nodes in k-dimension if the mesh is structured.
Definition at line 198 of file Connectivity.h.
References dimension(), and pointer().
   { return dimension()>2?pointer()[2]:1; }
Size size_of_corners_pe () const inline
Get the number of corners per element of the current connectivity table.
Definition at line 139 of file Connectivity.h.
Referenced by Element_node_enumerator::size_of_corners().
   { return _size_info[SIZE_NCORN]; }
static Size size_of_corners_pe (int type) inline static
Get the number of corners per element of the given type of element.
Definition at line 143 of file Connectivity.h.
References _sizes, and SIZE_NCORN.
   { return _sizes[type][SIZE_NCORN]; }
Size size_of_edges_pe () const inline
Get the number of edges per element of the current connectivity table.
Definition at line 155 of file Connectivity.h.
References _size_info, and SIZE_NEDGES.
Referenced by Element_node_enumerator::size_of_edges().
   { return _size_info[SIZE_NEDGES]; }
static Size size_of_edges_pe (int type) inline static
Get the number of edges per element of the given type of element.
Definition at line 159 of file Connectivity.h.
References _sizes, and SIZE_NEDGES.
   { return _sizes[type][SIZE_NEDGES]; }
Connectivity::Size size_of_elements () const
Get the total number of elements (including ghost elements) in the table.
Definition at line 96 of file Connectivity.C.
References Attribute::_ngitems, Attribute::_pane, _size_info, COM_assertion, COM_assertion_msg, Pane::ignore_ghost(), is_structured(), max(), pointer(), Attribute::size_of_items(), ST1, ST2, ST3, and TYPE_ID.
Referenced by Pane::connectivity(), Element_node_enumerator::Element_node_enumerator(), Element_node_enumerator::next(), Element_node_enumerator_uns::next(), and Pane::refresh_connectivity().
 {
   if ( !is_structured())
     return size_of_items();
   else {
     COM_assertion_msg( _ngitems==0 || !_pane->ignore_ghost(),
                        "Only unstructured meshes supports inheritance without ghost");
     const int *sizes=pointer();
     if ( sizes==NULL) return 0;
     int n=0;
     switch ( _size_info[TYPE_ID]) {
     case ST1: n=sizes[0]-1; break;
     case ST2: n=(sizes[0]-1)*(sizes[1]-1); break;
     case ST3: n=(sizes[0]-1)*(sizes[1]-1)*(sizes[2]-1); break;
     default: COM_assertion(false); // Should never reach here.
     }
     return std::max(0,n);
   }
 }
Size size_of_faces_pe () const inline
Get the number of faces per element of the current connectivity table.
Definition at line 163 of file Connectivity.h.
References _size_info, and SIZE_NFACES.
Referenced by Element_node_enumerator::size_of_faces().
   { return _size_info[SIZE_NFACES]; }
static Size size_of_faces_pe (int type) inline static
Get the number of faces per element of the given type of element.
Definition at line 167 of file Connectivity.h.
References _sizes, and SIZE_NFACES.
   { return _sizes[type][SIZE_NFACES]; }
Connectivity::Size size_of_ghost_elements () const
Get the number of ghost elements.
Definition at line 117 of file Connectivity.C.
References Attribute::_ngitems, _size_info, COM_assertion, is_structured(), max(), pointer(), Attribute::size_of_ghost_items(), ST1, ST2, ST3, and TYPE_ID.
Referenced by Pane::refresh_connectivity().
 {
   if ( !is_structured())
     return size_of_ghost_items();
   else {
     const int *sizes=pointer();
     if ( sizes==NULL) return 0;
     int n=0;
     switch ( _size_info[TYPE_ID]) {
     case ST1: n=2*_ngitems; break;
     case ST2: n=(sizes[0]-1)*(sizes[1]-1)-
                 (sizes[0]-1-2*_ngitems)*(sizes[1]-1-2*_ngitems); break;
     case ST3: n=(sizes[0]-1)*(sizes[1]-1)*(sizes[2]-1)-
                 (sizes[0]-1-2*_ngitems)*(sizes[1]-1-2*_ngitems)*
                 (sizes[2]-1-2*_ngitems); break;
     default: COM_assertion(false); // Should never reach here.
     }
     return std::max(0,n);
   }
 }
Connectivity::Size size_of_ghost_nodes () const
Get the number of ghost nodes of the owner pane.
Definition at line 178 of file Connectivity.C.
References Attribute::_ngitems, Attribute::_pane, _size_info, COM_assertion, is_structured(), pointer(), Pane::size_of_ghost_nodes(), ST1, ST2, ST3, and TYPE_ID.
 {
   if ( !is_structured())
     return _pane->size_of_ghost_nodes();
   else {
     const int *sizes=pointer();
     if ( sizes==NULL) return 0;
     switch ( _size_info[TYPE_ID]) {
     case ST1: return 2*_ngitems;
     case ST2: return sizes[0]*sizes[1]-
                 (sizes[0]-2*_ngitems)*(sizes[1]-2*_ngitems);
     case ST3: return sizes[0]*sizes[1]*sizes[2]-
                 (sizes[0]-2*_ngitems)*(sizes[1]-2*_ngitems)*
                 (sizes[2]-2*_ngitems);
     default: COM_assertion(false); // Should never reach here.
     }
     return 0;
   }
 }
Connectivity::Size size_of_nodes () const
Get the total number of nodes (including ghost nodes) of the owner pane.
Definition at line 158 of file Connectivity.C.
References Attribute::_ngitems, Attribute::_pane, _size_info, COM_assertion, COM_assertion_msg, Pane::ignore_ghost(), is_structured(), pointer(), Pane::size_of_nodes(), ST1, ST2, ST3, and TYPE_ID.
 {
   if ( !is_structured())
     return _pane->size_of_nodes();
   else {
     COM_assertion_msg( _ngitems==0 || !_pane->ignore_ghost(),
                        "Only unstructured meshes supports inheritance without ghost");
     const int *sizes=pointer();
     if ( sizes==NULL) return 0;
     switch ( _size_info[TYPE_ID]) {
     case ST1: return sizes[0];
     case ST2: return sizes[0]*sizes[1];
     case ST3: return sizes[0]*sizes[1]*sizes[2];
     default: COM_assertion(false); // Should never reach here.
     }
     return 0;
   }
 }
Size size_of_nodes_pe () const inline
Get the number of nodes per element of the current connectivity table.
Definition at line 147 of file Connectivity.h.
References _size_info, and SIZE_NNODES.
Referenced by Element_node_enumerator::Element_node_enumerator(), Pane_ghost_connectivity::finalize_pconn(), Element_node_enumerator::id(), Element_node_enumerator::next(), Element_node_enumerator_uns::next(), Pane_ghost_connectivity::process_received_data(), Element_node_enumerator::size_of_nodes(), Element_node_enumerator_uns::size_of_nodes(), and Element_node_enumerator::vertex().
   { return _size_info[SIZE_NNODES]; }
static Size size_of_nodes_pe (int type) inline static
Get the number of nodes per element of the given type of element.
Definition at line 151 of file Connectivity.h.
References _sizes, and SIZE_NNODES.
   { return _sizes[type][SIZE_NNODES]; }
Connectivity::Size size_of_real_elements () const
Get the number of real elements.
Definition at line 139 of file Connectivity.C.
References Attribute::_ngitems, _size_info, COM_assertion, is_structured(), max(), pointer(), Attribute::size_of_real_items(), ST1, ST2, ST3, and TYPE_ID.
 {
   if ( !is_structured())
     return size_of_real_items();
   else {
     const int *sizes=pointer();
     if ( sizes==NULL) return 0;
     int n=0;
     switch ( _size_info[TYPE_ID]) {
     case ST1: n=sizes[0]-1-2*_ngitems; break;
     case ST2: n=(sizes[0]-1-2*_ngitems)*(sizes[1]-1-2*_ngitems); break;
     case ST3: n=(sizes[0]-1-2*_ngitems)*(sizes[1]-1-2*_ngitems)*
                 (sizes[2]-1-2*_ngitems); break;
     default: COM_assertion(false); // Should never reach here.
     }
     return std::max(0,n);
   }
 }
Connectivity::Size size_of_real_nodes () const
Get the number of real nodes of the owner pane.
Definition at line 198 of file Connectivity.C.
References Attribute::_ngitems, Attribute::_pane, _size_info, COM_assertion, is_structured(), pointer(), Pane::size_of_real_nodes(), ST1, ST2, ST3, and TYPE_ID.
 {
   if ( !is_structured())
     return _pane->size_of_real_nodes();
   else {
     const int *sizes=pointer();
     if ( sizes==NULL) return 0;
     switch ( _size_info[TYPE_ID]) {
     case ST1: return sizes[0]-2*_ngitems;
     case ST2: return (sizes[0]-2*_ngitems)*(sizes[1]-2*_ngitems);
     case ST3: return (sizes[0]-2*_ngitems)*(sizes[1]-2*_ngitems)*
                 (sizes[2]-2*_ngitems);
     default: COM_assertion(false); // Should never reach here.
     }
     return 0;
   }
 }
Member Data Documentation
int _offset protected
Offset of the first element.
Definition at line 255 of file Connectivity.h.
Referenced by index_offset().
const int* _size_info protected
Definition at line 256 of file Connectivity.h.
Referenced by dimension(), element_type(), is_quadratic(), is_structured(), size_of_edges_pe(), size_of_elements(), size_of_faces_pe(), size_of_ghost_elements(), size_of_ghost_nodes(), size_of_nodes(), size_of_nodes_pe(), size_of_real_elements(), and size_of_real_nodes().
COM_BEGIN_NAME_SPACE const int _sizes static protected
Initial value:
=
{
  {ST1,      1, 1,     2,      2,     1,     0},
  {ST2,      2, 1,     4,      4,     4,     1},
  {ST3,      3, 1,     8,      8,    12,     6},
  {BAR2,     1, 1,     2,      2,     1,     0},
  {BAR3,     1, 2,     3,      2,     1,     0},
  {TRI3,     2, 1,     3,      3,     3,     1},
  {TRI6,     2, 2,     6,      3,     3,     1},
  {QUAD4,    2, 1,     4,      4,     4,     1},
  {QUAD8,    2, 2,     8,      4,     4,     1},
  {QUAD9,    2, 2,     9,      4,     4,     1},
  {TET4,     3, 1,     4,      4,     6,     4},
  {TET10,    3, 2,     10,     4,     6,     4},
  {PYRIMID5, 3, 1,     5,      5,     8,     5},
  {PYRIMID14,3, 2,     14,     5,     8,     5},
  {PRISM6,   3, 1,     6,      6,     9,     5},
  {PRISM15,  3, 2,     15,     6,     9,     5},
  {PRISM18,  3, 2,     18,     6,     9,     5},
  {HEX8,     3, 1,     8,      8,    12,     6},
  {HEX20,    3, 2,     20,     8,    12,     6},
  {HEX27,    3, 2,     27,     8,    12,     6}
}
Definition at line 258 of file Connectivity.h.
Referenced by get_size_info(), size_of_corners_pe(), size_of_edges_pe(), size_of_faces_pe(), and size_of_nodes_pe().
The documentation for this class was generated from the following files:
Connectivity.h
Connectivity.C