Rocstar: modstatsroutines Module Reference
modstatsroutines Module Reference
Public Member Functions
subroutine, public statbuildversionstring (versionString)
subroutine, public getstatistics (regions)
subroutine, public initstatistics (regions)
subroutine, public statdataaccumulation1 (ijkbeg, ijkend, id, idtav, dTime, var, qavg)
subroutine, public statdataaccumulation2 (ijkbeg, ijkend, id1, id2, idtav, dTime, var1, var2, qavg)
subroutine, public statdatasampling (region, fluidType)
subroutine, public statmapping (global)
subroutine, public stattimeaccumulation (global)
subroutine, public statwritemp (regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: ModStatsRoutines.F90,v $ $Revision: 1.11 $'
Detailed Description
Definition at line 39 of file ModStatsRoutines.F90.
Member Function/Subroutine Documentation
subroutine, public getstatistics (type(t_region), dimension(:), pointer regions)
Definition at line 140 of file ModStatsRoutines.F90.
References moderror::deregisterfunction(), plag_modeulerian::plag_calceulerianfield(), moderror::registerfunction(), statdatasampling(), and stattimeaccumulation().
Referenced by rflo_dualtimestepping(), rflo_timestepping(), rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
subroutine, public initstatistics (type(t_region), dimension(:), pointer regions)
Definition at line 225 of file ModStatsRoutines.F90.
References moderror::deregisterfunction(), plag_rflo_modstats::plag_rflo_readstat(), moderror::registerfunction(), rflo_readstat(), rflu_readstat(), and stat_rflu_modrocstaradmin::stat_rflu_genxgetdata().
Referenced by rflo_initflowsolver(), and rflu_initflowsolver().
subroutine, public statbuildversionstring (character(*) versionString)
Definition at line 96 of file ModStatsRoutines.F90.
Referenced by rflo_initflowsolver().
subroutine, public statdataaccumulation1 (integer ijkbeg, integer ijkend, integer id, integer idtav, real(rfreal) dTime, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer qavg)
Definition at line 393 of file ModStatsRoutines.F90.
References id().
Referenced by statdatasampling().
subroutine, public statdataaccumulation2 (integer ijkbeg, integer ijkend, integer id1, integer id2, integer idtav, real(rfreal) dTime, real(rfreal), dimension(:,:), pointer var1, real(rfreal), dimension(:,:), pointer var2, real(rfreal), dimension(:,:), pointer qavg)
Definition at line 415 of file ModStatsRoutines.F90.
Referenced by statdatasampling().
subroutine, public statdatasampling (type(t_region) region, integer fluidType)
Definition at line 454 of file ModStatsRoutines.F90.
References moderror::deregisterfunction(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), statdataaccumulation1(), and statdataaccumulation2().
Referenced by getstatistics().
subroutine, public statmapping (type(t_global), pointer global)
Definition at line 650 of file ModStatsRoutines.F90.
References moderror::deregisterfunction(), moderror::errorstop(), genxstatnaming(), n, plag_statmapping(), moderror::registerfunction(), and turb_statmapping().
Referenced by rflo_initflowsolver(), and rflu_initflowsolver().
subroutine, public stattimeaccumulation (type(t_global), pointer global)
Definition at line 879 of file ModStatsRoutines.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by getstatistics().
subroutine, public statwritemp (type(t_region), dimension(:), pointer regions)
Definition at line 924 of file ModStatsRoutines.F90.
References moderror::deregisterfunction(), plag_rflo_modstats::plag_rflo_commstatbuffwrapper(), plag_rflo_modstats::plag_rflo_writestat(), moderror::registerfunction(), rflo_modstatsboundaryconditions::rflo_statboundaryconditionsset(), and rflo_writestat().
Referenced by rflo_timestepping().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: ModStatsRoutines.F90,v $ $Revision: 1.11 $' private
Definition at line 70 of file ModStatsRoutines.F90.
The documentation for this module was generated from the following file:
ModStatsRoutines.F90