Rocstar: TriFace Class Reference
TriFace Class Reference
#include <TriFace.hpp>
Public Member Functions
TriFace (Node **theNodes)
Builds the TriFace object from an array of three nodes.
TriFace ()
~TriFace ()
Destructor.
virtual int getNumNodes () const
Returns the number of nodes for this type of face (three for the triangular face).
virtual Element * buildCohesive (Element *side_elem, Node *node, Node *new_node)
Public Member Functions inherited from Face
Face (Type type)
Constructor: set type & reset params.
Face ()
~Face ()
Destructor.
void setID (int theID)
Sets the serial ID for the face.
int getID () const
Returns the serial ID of the face.
void setFlag (int theFlag)
Sets the flag for the face.
int getFlag () const
Gets the flag for the face.
Node ** getNodes ()
Returns the array of nodes.
void setElement1 (Element *elem1)
Sets the pointer to the first element that this face is associated with.
Element * getElement1 ()
Get the pointer to the first element that this face is associated with.
void setElement2 (Element *elem2)
Sets the pointer to the second element that this face is associated with.
Element * getElement2 ()
Get the pointer to the second element that this face is associated with.
void addElement (Element *theElement)
void removeElement (Element *theElement)
Type getFaceType () const
Returns the face type of this face (see the Type attribute of the Face class).
boolean isExterior () const
void replaceNode (Node *node, Node *new_node)
boolean containsNode (Node *node) const
Additional Inherited Members
Public Types inherited from Face
enum Type { e_tri, e_quad, e_MAX_TYPE }
enum eType {
e_tet, e_hex, e_tri_cohesive, e_quad_cohesive,
e_MAX_ELEMENT_TYPE
}
Static Public Member Functions inherited from Face
static Face * create (eType type)
static void setMesh (Mesh *emesh)
Protected Attributes inherited from Face
int d_ID
Serial ID assigned to this face.
int d_flag
User-defined integer flag assigned to this face.
Element * d_E1
Pointer to the first element that this face is associated with.
Element * d_E2
The second element that this face is associated with.
Node ** d_nodes
Array of nodes assigned to this face.
Type d_eType
The Type of face (triangular or square for now).
Static Protected Attributes inherited from Face
static Mesh * s_mesh = 0
Detailed Description
Definition at line 8 of file TriFace.hpp.
Constructor & Destructor Documentation
TriFace (Node ** theNodes)
Builds the TriFace object from an array of three nodes.
The element(s) must be set later with the setElement methods.
Definition at line 6 of file TriFace.cpp.
References Node::addFace(), Face::d_nodes, and i.
                                  :
   Face( e_tri )
 {
   d_nodes = new Node*[3];
   int i;
   for( i = 0; i < 3; i++ ){
     d_nodes[i] = theNodes[i];
     d_nodes[i]->addFace( this );
   }
 }
TriFace ()
Definition at line 17 of file TriFace.cpp.
References Face::d_nodes, and i.
                  {
   d_nodes = new Node*[3];
   int i;
   for (i=0; i<3; i++) d_nodes[i]=0;
 }
~TriFace ()
Destructor.
Definition at line 23 of file TriFace.cpp.
References Face::d_nodes, i, and Node::removeFace().
                  {
   int i;
   for( i = 0; i < 3; i++ ){
     d_nodes[i]->removeFace( this );
   }
 }
Member Function Documentation
Element * buildCohesive (Element * side_elem, Node * node, Node * new_node) virtual
Implements Face.
Definition at line 34 of file TriFace.cpp.
References Face::d_E1, Face::d_E2, Face::d_nodes, Element::getFaces(), i, and Element::replaceFace().
{
   int ind=-1;
   int i;
   for( i = 0; i < 3; i++ ){
     if( d_nodes[i] == node ){
       ind = i;
       break;
     }
   }
   Element* coelem;
   Node* new_nodes[6];
   //the order of the second three nodes looks wrong - need to assess and
   //correct if so.  Order should be 1,2,3, and 4,5,6 with 4 corresponding to
   //3 and not to 1.
   //Note:  when a cohesive element is made, it always has two doubled node
   //numbers:  when do they get updated?
   if( d_E1 == side_elem ){ // normal to side
     new_nodes[0] = d_nodes[0];
     new_nodes[1] = d_nodes[1];
     new_nodes[2] = d_nodes[2];
     new_nodes[3] = (ind == 0 ? new_node : d_nodes[0] );
     new_nodes[4] = (ind == 1 ? new_node : d_nodes[1] );
     new_nodes[5] = (ind == 2 ? new_node : d_nodes[2] );
     d_E1 = d_E2;
     d_E2 = 0;
     coelem = new TCoElement( new_nodes );
     // now for this face set E1 to  the coelem
     d_E2 = d_E1;
     d_E1 = coelem;
     Face* oface = coelem->getFaces()[1];
     ((TriFace*)oface)->d_E2 = side_elem;
     side_elem->replaceFace( this, oface );
   }
   else { // normal to the other side
     d_E2 = 0;
     new_nodes[0] = (ind == 0 ? new_node : d_nodes[0] );
     new_nodes[1] = (ind == 1 ? new_node : d_nodes[1] );
     new_nodes[2] = (ind == 2 ? new_node : d_nodes[2] );
     new_nodes[3] = d_nodes[0];
     new_nodes[4] = d_nodes[1];
     new_nodes[5] = d_nodes[2];
     coelem = new TCoElement( new_nodes );
     // now for the new face set E2 to side_elem (will correct the nodes later)
     Face* oface = coelem->getFaces()[0];
     ((TriFace*)oface)->d_E2 = side_elem;
     side_elem->replaceFace( this, oface );
   }
   return coelem;
 }
int getNumNodes () const virtual
Returns the number of nodes for this type of face (three for the triangular face).
Implements Face.
Definition at line 30 of file TriFace.cpp.
 { return 3; }
The documentation for this class was generated from the following files:
TriFace.hpp
TriFace.cpp