Rocstar: Point_set Class Reference
Point_set Class Reference
#include <Overlay_primitives.h>
Public Types
typedef Point_set Self
typedef Vertex_overlay Vertex
typedef Halfedge_overlay Halfedge
typedef Point_3 Value
typedef unsigned int Size
Public Member Functions
Point_set (const Halfedge *h)
Point_set (const Halfedge *h, Size)
const Point_3 & operator[] (Size i) const
Size size_of_edges () const
Size size_of_nodes () const
Protected Attributes
Vertex_set vs
Detailed Description
Definition at line 84 of file Overlay_primitives.h.
Member Typedef Documentation
typedef Halfedge_overlay Halfedge
Definition at line 88 of file Overlay_primitives.h.
typedef Point_set Self
Definition at line 86 of file Overlay_primitives.h.
typedef unsigned int Size
Definition at line 90 of file Overlay_primitives.h.
typedef Point_3 Value
Definition at line 89 of file Overlay_primitives.h.
typedef Vertex_overlay Vertex
Definition at line 87 of file Overlay_primitives.h.
Constructor & Destructor Documentation
Point_set (const Halfedge * h) inline explicit
Definition at line 92 of file Overlay_primitives.h.
 : vs(h) {}
Point_set (const Halfedge * h, Size) inline
Definition at line 93 of file Overlay_primitives.h.
 : vs(h,0) {}
Member Function Documentation
const Point_3& operator[] (Size i) const inline
Definition at line 100 of file Overlay_primitives.h.
References RFC_Pane_overlay::get_point(), Vertex_set::pane(), and vs.
 { return vs.pane()->get_point(vs[i]); }
Size size_of_edges () const inline
Definition at line 101 of file Overlay_primitives.h.
References Vertex_set::size_of_edges(), and vs.
Referenced by Overlay_primitives::get_face_normal(), Overlay_primitives::get_point(), Overlay_primitives::get_tangent(), and Overlay_primitives::project_onto_element().
 { return vs.size_of_edges(); }
Size size_of_nodes () const inline
Definition at line 102 of file Overlay_primitives.h.
References Vertex_set::size_of_nodes(), and vs.
 { return vs.size_of_nodes(); }
Member Data Documentation
Vertex_set vs protected
Definition at line 105 of file Overlay_primitives.h.
Referenced by operator[](), size_of_edges(), and size_of_nodes().
The documentation for this class was generated from the following file:
Overlay_primitives.h