Rocstar: modrandom Module Reference
modrandom Module Reference
Data Types
type t_rand_data
Public Member Functions
subroutine randomseed (seed, rdata)
subroutine randuniform (a, rdata)
subroutine randnormal (a, med, dev, rdata)
subroutine randlognormal (a, logmed, gdev, rdata)
subroutine randimposedpdf (a, pdfvalues, locMax, valmax, rdata)
REAL(RFREAL) function rand1uniform (rdata)
REAL(RFREAL) function rand1normal (med, dev, rdata)
REAL(RFREAL) function rand1lognormal (logmed, gdev, rdata)
REAL(RFREAL) function rand1imposedpdf (rdata, pdfvalues, locMax, valmax)
Public Attributes
integer, parameter rand_buffer_size = 624
integer, parameter rand_mti_index = RAND_BUFFER_SIZE
integer, parameter rand_seed_index = RAND_BUFFER_SIZE + 1
integer, parameter rand_calls_index = RAND_BUFFER_SIZE + 2
integer, parameter rand_extra_ints = 3
integer, parameter rand_total_size = RAND_BUFFER_SIZE + RAND_EXTRA_INTS
Detailed Description
Definition at line 67 of file ModRandom.F90.
Member Function/Subroutine Documentation
REAL(RFREAL) function rand1imposedpdf (type(t_rand_data), intent(inout) rdata, real(rfreal), dimension(:,:), intent(in) pdfvalues, integer, intent(in) locMax, real(rfreal), intent(in) valmax)
Definition at line 398 of file ModRandom.F90.
References Line_2< R, T >::a(), and randimposedpdf().
Referenced by plag_injcmakeparticle().
REAL(RFREAL) function rand1lognormal (real(rfreal), intent(in) logmed, real(rfreal), intent(in) gdev, type(t_rand_data), intent(inout) rdata)
Definition at line 380 of file ModRandom.F90.
References Line_2< R, T >::a(), and randlognormal().
Referenced by plag_injcmakeparticle(), and plag_rand1logskewed().
REAL(RFREAL) function rand1normal (real(rfreal), intent(in) med, real(rfreal), intent(in) dev, type(t_rand_data), intent(inout) rdata)
Definition at line 362 of file ModRandom.F90.
References Line_2< R, T >::a(), and randnormal().
REAL(RFREAL) function rand1uniform (type(t_rand_data), intent(inout) rdata)
Definition at line 345 of file ModRandom.F90.
References Line_2< R, T >::a(), and randuniform().
Referenced by plag_initpatchdata(), plag_injcejectparticle(), plag_injcmakeparticle(), plag_injcsetinjection(), plag_modinjection::plag_injcsetpoolpos(), plag_injcsetpositions(), plag_injctileinitialize(), plag_modinjection::plag_invokeconsrandejec(), plag_rand1logskewed(), plag_rflu_initsolutionrandom(), randnormal(), and rflu_modgridutils::rflu_distortgrid().
subroutine randimposedpdf (real(rfreal), dimension(:), intent(out) a, real(rfreal), dimension(:,:), intent(in) pdfvalues, integer, intent(in) locMax, real(rfreal), intent(in) valmax, type(t_rand_data), intent(inout) rdata)
Definition at line 300 of file ModRandom.F90.
References Line_2< R, T >::a(), findpdf(), i, and randuniform().
Referenced by rand1imposedpdf().
subroutine randlognormal (real(rfreal), dimension(:), intent(out) a, real(rfreal), intent(in) logmed, real(rfreal), intent(in) gdev, type(t_rand_data), intent(inout) rdata)
Definition at line 283 of file ModRandom.F90.
References Line_2< R, T >::a(), and randnormal().
Referenced by rand1lognormal().
subroutine randnormal (real(rfreal), dimension(:), intent(out) a, real(rfreal), intent(in) med, real(rfreal), intent(in) dev, type(t_rand_data), intent(inout) rdata)
Definition at line 246 of file ModRandom.F90.
References Line_2< R, T >::a(), cos, i, Color::r(), rand1uniform(), randuniform(), sin, and sqrt().
Referenced by rand1normal(), and randlognormal().
subroutine randomseed (integer, intent(in) seed, type(t_rand_data), intent(out) rdata)
Definition at line 92 of file ModRandom.F90.
References i.
Referenced by rflo_randominit(), and rflu_randominit().
subroutine randuniform (real(rfreal), dimension(:), intent(out) a, type(t_rand_data), intent(inout) rdata)
Definition at line 135 of file ModRandom.F90.
References Line_2< R, T >::a(), i, j, Aff_transformation_2< R_ >::m(), and y.
Referenced by rand1uniform(), randimposedpdf(), randnormal(), updatetbcstochastic(), and updatetbcwhitenoise().
Member Data Documentation
integer, parameter rand_buffer_size = 624
Definition at line 73 of file ModRandom.F90.
integer, parameter rand_calls_index = RAND_BUFFER_SIZE + 2
Definition at line 76 of file ModRandom.F90.
integer, parameter rand_extra_ints = 3
Definition at line 77 of file ModRandom.F90.
integer, parameter rand_mti_index = RAND_BUFFER_SIZE
Definition at line 74 of file ModRandom.F90.
integer, parameter rand_seed_index = RAND_BUFFER_SIZE + 1
Definition at line 75 of file ModRandom.F90.
integer, parameter rand_total_size = RAND_BUFFER_SIZE + RAND_EXTRA_INTS
Definition at line 78 of file ModRandom.F90.
The documentation for this module was generated from the following file:
ModRandom.F90