Rocstar: Coupling Class Reference
Coupling Class Reference
#include <Coupling.h>
Public Member Functions
Coupling (const char *coupl_name, const char *name, Control_parameters *p, const RocmanControl_parameters *mp)
Constructor. Derived class will add actions for the coupling scheme.
Coupling (const char *coupl_name, const char *fluidname, const char *solidname, Control_parameters *p, const RocmanControl_parameters *mp)
Coupling (const char *coupl_name, const char *fluidname, const char *solidname, const char *burnname, Control_parameters *p, const RocmanControl_parameters *mp)
virtual ~Coupling ()
Destructor.
const char * name ()
Agent * add_agent (Agent *)
Add new agent.
void schedule ()
Schedule the top-level actions of the coupling scheme and the actions of the agents.
void init (double t, double dt, int reinit=0)
Invoke initialization of the actions in the scheduler and the agents.
void initialize (int reinit=0)
void finalize ()
Invoke finalization of the actions in the scheduler and the agents.
double run (double t, double dt, int iPredCorr, double zoom)
Invoke the scheduler.
void run_initactions (double t, double dt)
void input (double t)
Invoke input functions of the agents.
int get_ipc () const
int get_max_ipc () const
int initial_start () const
int in_restart () const
int initial_remeshed () const
true if in initialization step and remeshed is true
int new_start (double t) const
void init_convergence (int iPredCorr)
int check_convergence ()
virtual void update_integrals (double currentTime)
virtual void update_distances (double currentTime)
void output_restart_files (double t)
void output_visualization_files (double t)
const Control_parameters * get_control_param ()
const RocmanControl_parameters * get_rocmancontrol_param ()
void read_restart_info ()
void write_restart_info (double CurrentTime, int iStep)
void restart_at_time (double t, int step)
virtual void reload_rocface (const RocmanControl_parameters *param)
void print (const char *fname)
void Interrupt (int *, const char *)
int ProcessInterrupt ()
Protected Member Functions
void callMethod (Scheduler_voidfn1_t fn, double t)
std::string normalize_modname (const char *mod)
Protected Attributes
std::string coupling_name
vector< std::string > modules
AgentList agents
UserScheduler scheduler
UserScheduler init_scheduler
int comm_rank
int init_started
int restarting
int init_remeshed
int iPredCorr
int maxPredCorr
Control_parameters * param
const RocmanControl_parameters * rocmanparam
std::string restartInfo
int overwrite_integ
std::string integFname
int overwrite_dist
std::string distFname
Private Member Functions
void baseInit ()
Detailed Description
Definition at line 97 of file Coupling.h.
Constructor & Destructor Documentation
Coupling (const char * coupl_name, const char * name, Control_parameters * p, const RocmanControl_parameters * mp)
Constructor. Derived class will add actions for the coupling scheme.
Definition at line 130 of file Coupling.C.
References baseInit(), and modules.
                                                       :
           coupling_name(coupl_name), param(param_), rocmanparam(mp)
 {
   modules.push_back(name);
   baseInit();
 }
Coupling (const char * coupl_name, const char * fluidname, const char * solidname, Control_parameters * p, const RocmanControl_parameters * mp)
Definition at line 139 of file Coupling.C.
References baseInit(), and modules.
                                                       :
           coupling_name(coupl_name), param(param_), rocmanparam(mp)
 {
   modules.push_back(fluidname);
   modules.push_back(solidname);
   baseInit();
 }
Coupling (const char * coupl_name, const char * fluidname, const char * solidname, const char * burnname, Control_parameters * p, const RocmanControl_parameters * mp)
Definition at line 150 of file Coupling.C.
References baseInit(), and modules.
                                                       :
           coupling_name(coupl_name), param(param_), rocmanparam(mp)
 {
   modules.push_back(fluidname);
   modules.push_back(solidname);
   modules.push_back(burnname);
   baseInit();
 }
~Coupling () virtual
Destructor.
Definition at line 163 of file Coupling.C.
References agents, i, and n.
                     {
   for ( int i=0, n=agents.size(); i<n; ++i) {
     delete agents[i];
   }
   agents.clear();
 }
Member Function Documentation
Agent * add_agent (Agent * agent)
Add new agent.
Definition at line 174 of file Coupling.C.
References agents.
Referenced by FluidAlone::FluidAlone(), and FluidBurnAlone::FluidBurnAlone().
 {
   agents.push_back(agent);
   return agent;
 }
void baseInit () private
Definition at line 93 of file Coupling.C.
References COM_INT, COM_new_attribute(), COM_new_window(), COM_RAWDATA, COM_set_member_function(), COM_set_object(), COM_STRING, COM_VOID, comm_rank, COMMPI_Comm_rank(), Control_parameters::communicator, Control_parameters::current_time, distFname, cimg_library::cimg::fopen(), init_remeshed, init_started, integFname, Interrupt(), iPredCorr, overwrite_dist, overwrite_integ, param, RocmanControl_parameters::remeshed, restartInfo, restarting, and rocmanparam.
Referenced by Coupling().
 {
   iPredCorr = 0;
   init_started = param->current_time==0.0;
   restarting = 0;
   init_remeshed = rocmanparam->remeshed;
   comm_rank = COMMPI_Comm_rank(param->communicator);
   restartInfo = "Restart.txt";
   integFname = "Rocman/Modout/GENX_integ.txt";
   distFname = "Rocman/Modout/GENX_dist.txt";
   overwrite_integ = overwrite_dist = 0;
   if ( param->current_time != 0.0) {
     FILE *fp = fopen(integFname.c_str(), "r");
     if (!fp) overwrite_integ = 1;
     fp = fopen(distFname.c_str(), "r");
     if (!fp) overwrite_dist = 1;
   }
   else {
     overwrite_integ = 1;
     overwrite_dist = 1;
   }
   // experimental Interrupt
   std::string manwinname = "Rocman";
   std::string manfuncname = manwinname+".interrupt";
   std::string coupobjname = manwinname+".coup";
   COM_Type types[3];
   types[0] = COM_RAWDATA;
   types[1] = COM_INT;
   types[2] = COM_STRING;
   COM_new_window(manwinname);
   COM_new_attribute(coupobjname, 'w',COM_VOID, 1, "");
   COM_set_object(coupobjname.c_str(),0,this);
   COM_set_member_function(manfuncname.c_str(),
                           (Member_func_ptr)&Coupling::Interrupt,
                           coupobjname.c_str(),"bii",types);
 }
void callMethod (Scheduler_voidfn1_t fn, double t) protected
Definition at line 217 of file Coupling.C.
References agents, i, init_scheduler, n, and scheduler.
Referenced by init().
 {
   int i, n;
   (init_scheduler.*fn)( t);
   for ( i=0, n=agents.size(); i<n; ++i)
     agents[i]->callMethod(fn, t);
   (scheduler.*fn)( t);
 }
int check_convergence ()
Definition at line 284 of file Coupling.C.
References agents, i, maxPredCorr, n, param, Control_parameters::tolerMass, Control_parameters::tolerTract, and Control_parameters::tolerVelo.
Referenced by rocstar_driver().
 {
   int InterfaceConverged;
   if ( maxPredCorr>1) {
     InterfaceConverged = 0;
     for ( int i=0, n=agents.size(); i<n; ++i)
       if (!agents[i]->check_convergence( param->tolerMass, param->tolerTract, param->tolerVelo)) return InterfaceConverged;
     InterfaceConverged = 1;
   }
   else
     InterfaceConverged = 1;
   return InterfaceConverged;
 }
void finalize ()
Invoke finalization of the actions in the scheduler and the agents.
Definition at line 230 of file Coupling.C.
References agents, Scheduler::finalize_actions(), i, init_scheduler, n, and scheduler.
Referenced by Interrupt(), restart_at_time(), and rocstar_driver().
{
   init_scheduler.finalize_actions();
   scheduler.finalize_actions();
   for ( int i=0, n=agents.size(); i<n; ++i)
     agents[i]->finalize();
 }
const Control_parameters* get_control_param () inline
Definition at line 183 of file Coupling.h.
Referenced by _load_rocface(), Agent::Agent(), BurnAgent::BurnAgent(), FluidBurnAlone::FluidBurnAlone(), restart_at_time(), and CopyBflagFromBurn::run().
 { return param; }
int get_ipc () const inline
Definition at line 160 of file Coupling.h.
Referenced by Extrapolate_Linear::run(), Extrapolate_Central::run(), and PhysicsAction::run().
 { return iPredCorr; }
int get_max_ipc () const inline
Definition at line 161 of file Coupling.h.
Referenced by BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), FluidAgent::finalize(), BurnAgent::finalize(), and SolidAgent::finalize().
 { return maxPredCorr; }
const RocmanControl_parameters* get_rocmancontrol_param () inline
Definition at line 184 of file Coupling.h.
Referenced by ComputeFluidLoad_ALE::ComputeFluidLoad_ALE(), SolidAgent::create_buffer_all(), declare_solid_actions(), LoadTransfer_FS::init(), LoadTransfer_FSc_ALE::init(), LoadTransferOnly_FSc_ALE::init(), SurfDiver::init(), MeshMotionTransfer_SF::init(), DeformationVelTransfer_SF::init(), MeshMotionTransferISS::init(), TransferSolidDensity::init(), FluidPropagateSurface::init(), TransferBurnRate_FS_ALE::init(), MassTransfer_SF_ALE::init(), TemperatureTransfer_SF::init(), HeatTransfer_FS::init(), RemeshInit::init(), ComputePconn::init(), SolidPropagateSurface_ALE::init(), LoadTransfer_FS::LoadTransfer_FS(), LoadTransfer_FSc_ALE::LoadTransfer_FSc_ALE(), LoadTransferOnly_FSc_ALE::LoadTransferOnly_FSc_ALE(), Extrapolate_Linear::run(), Extrapolate_Central::run(), LoadTransfer_FSc_ALE::run(), Interpolate_Linear::run(), Interpolate_Central::run(), GetDeformedMesh_ALE::run(), ComputeFluidLoad_ALE::run(), FluidPropagateSurface::run(), Agent::write_control_file(), and Agent::write_data_files().
 { return rocmanparam; }
int in_restart () const inline
Definition at line 164 of file Coupling.h.
Referenced by BurnAgent::unload_module(), FluidAgent::unload_module(), and SolidAgent::unload_module().
 { return restarting; }
void init (double t, double dt, int reinit = 0)
Invoke initialization of the actions in the scheduler and the agents.
Definition at line 191 of file Coupling.C.
References agents, callMethod(), i, Scheduler::init_actions(), FluidAgent::init_module(), n, and Scheduler::restarting().
Referenced by initialize().
{
   int i, n;
 #if 0
   for ( i=0, n=agents.size(); i<n; ++i)
     agents[i]->init_module( t);
   for ( i=0, n=agents.size(); i<n; ++i)
     agents[i]->init_buffers( t);
 #else
 //  void _load_rocface(FluidAgent *fagent, SolidAgent *sagent, const RocmanControl_parameters *param);
   for ( i=0, n=agents.size(); i<n; ++i)  {
 //    if (i==2) _load_rocface(agents[0], agents[1], rocmanparam);
     agents[i]->init_module( t, dt);
 //    agents[i]->init_buffers( t);
   }
 #endif
     // in warm restart, reset scheduler so that it can be re-inited
   if (reinit)
     callMethod(&Scheduler::restarting, t);
   callMethod(&Scheduler::init_actions, t);
 }
void init_convergence (int iPredCorr)
Definition at line 275 of file Coupling.C.
References agents, i, maxPredCorr, and n.
Referenced by rocstar_driver().
 {
   if ( maxPredCorr>1 && iPredCorr > 0) {
     for ( int i=0, n=agents.size(); i<n; ++i) {
       agents[i]->init_convergence( iPredCorr);
     }
   }
 }
int initial_remeshed () const inline
true if in initialization step and remeshed is true
Definition at line 167 of file Coupling.h.
 { return init_remeshed; }
int initial_start () const inline
Definition at line 163 of file Coupling.h.
Referenced by FluidBurnAlone::FluidBurnAlone(), BurnAgent::init_module(), MeshMotionTransfer_SF::run(), TransferSolidDensity::run(), CopyBflagFromBurn::run(), and SolidPropagateSurface_ALE::run().
 { return init_started; }
void initialize (int reinit = 0)
Definition at line 355 of file Coupling.C.
References Control_parameters::current_time, init(), input(), param, reload_rocface(), rocmanparam, run_initactions(), and Control_parameters::time_step.
Referenced by restart_at_time(), and rocstar_driver().
 {
   // invoke input of coupling object (Input of initial data of physics modules)
   input( param->current_time);
   // invoke initialization of coupling object, load modules
   init( param->current_time, param->time_step, reinit);
   // reset rocface if restart
   if (reinit)
      reload_rocface(rocmanparam);
   // initialize each modules by executing init schedulers
   run_initactions( param->current_time, param->time_step);
 }
void input (double t)
Invoke input functions of the agents.
Definition at line 269 of file Coupling.C.
References agents, i, and n.
Referenced by initialize().
{
   for ( int i=0, n=agents.size(); i<n; ++i) {
     agents[i]->input( t);
   }
 }
void Interrupt (int * act, const char * message)
Definition at line 480 of file Coupling.C.
References Agent::action, Control_parameters::cur_step, Control_parameters::current_time, finalize(), Control_parameters::InterruptFlag, Control_parameters::LastOutputStep, Control_parameters::LastOutputTime, MAN_DEBUG, Control_parameters::myRank, output_restart_files(), param, RocstarShutdown(), and write_restart_info().
Referenced by baseInit(), and check_for_interrupt().
 {
   int action = *act;
   if(!param->myRank){
     std::cout << "Rocstar::Interrupt invoked." << std::endl
               << "Rocstar: ***************************************************"
               << std::endl
               << "Rocstar: " << (message ? message : "") << std::endl
               << "Rocstar: ***************************************************"
               << std::endl;
   }
   switch(action){
   case 0:
     // Just stop
     if(!param->myRank)
       std::cout << "Rocstar: Halting simulation." << std::endl;
     finalize();
     RocstarShutdown();
     break;
   case 1:
     // Output solutions and stop.
     if(!param->myRank)
       std::cout << "Rocstar: Writing restart files and halting simulation."
                 << std::endl;
     output_restart_files( param->current_time);
     finalize();
     RocstarShutdown();
     break;
   case 2:
     //
     // Restart from last restart dump and increase the output
     // frequency for debugging.
     //
     // 0. Call warm restart function to junk current data, and
     //    re-initialize with last successful solution dump
     // 1. Reset the max number of timesteps and output interval
     // 2. Code will stop and dump a soln when it reaches the step just prior
     //    to this one
     //
     if(!param->myRank){
       std::cout << "Rocstar: Directed to warm restart from last dump "
                 << "and increase dump frequency." << std::endl;
     }
     param->InterruptFlag = 2;
     break;
   case 3:
     if(!param->myRank)
       std::cout << "Rocstar: Directed to remesh and warm restart from "
                 << "(time/step): ("
                 << param->LastOutputTime << "," << param->LastOutputStep
                 << ")" << std::endl;
     param->InterruptFlag = 3;
     break;
   case 4:
     if(!param->myRank)
       std::cout << "Rocstar: Directed to restart from "
                << "(time/step): (" << param->LastOutputTime << ","
                << param->LastOutputStep << ")" << std::endl;
     if(message)
       std::cout << "MESSAGE: " << message << std::endl;
     param->InterruptFlag = 4;
     break;
   case 5:
     if(!param->myRank)
       std::cout << "Rocstar: Directed to dump at (time/step): ("
                << param->current_time << "," << param->cur_step
                << ")" << std::endl;
     output_restart_files( param->current_time);
     write_restart_info( param->current_time, param->cur_step+1);
     break;
   case 6:
     if(!param->myRank)
       std::cout << "Rocstar: Directed to dump and restart at (time/step): ("
                << param->current_time << "," << param->cur_step
                << ")" << std::endl;
     output_restart_files( param->current_time);
     write_restart_info( param->current_time, param->cur_step+1);
     if(message)
       std::cout << "MESSAGE: " << message << std::endl;
     param->InterruptFlag = 4;
     break;
   default:
     if(param->myRank == 0)
       std::cout << "Rocstar: Unknown interrupt action." << std::endl;
     MAN_DEBUG(0,("Rocstar: Coupling::Interrupt(unknown action): %s.\n",
                  message));
     return;
   }
 }
const char* name () inline
Definition at line 135 of file Coupling.h.
Referenced by run_initactions().
 { return coupling_name.c_str(); }
int new_start (double t) const
Definition at line 170 of file Coupling.C.
References Control_parameters::init_time, param, RocmanControl_parameters::remeshed, and rocmanparam.
Referenced by Extrapolate_Linear::run(), Extrapolate_Central::run(), Interpolate_Linear::run(), and Interpolate_Central::run().
{
   return t==0.0 || (rocmanparam->remeshed && t == param->init_time);
 }
std::string normalize_modname (const char * mod) protected
Definition at line 464 of file Coupling.C.
References cimg_library::cimg::mod().
 {
   std::string mod = modname;
   if (mod == "RocfluDummy")
     return "Rocflu";
   if (mod == "RocfloDummy")
     return "Rocflo";
   if (mod == "RocfracDummy")
     return "Rocfrac";
   if (mod == "RocsolidDummy")
     return "Rocsolid";
   return mod;
 }
void output_restart_files (double t)
Definition at line 299 of file Coupling.C.
References agents, i, and n.
Referenced by Interrupt(), and rocstar_driver().
{
   for ( int i=0, n=agents.size(); i<n; ++i) {
     agents[i]->output_restart_files( t);
   }
 }
void output_visualization_files (double t)
Definition at line 306 of file Coupling.C.
References agents, i, and n.
Referenced by rocstar_driver().
{
   for ( int i=0, n=agents.size(); i<n; ++i) {
     agents[i]->output_visualization_files( t);
   }
 }
void print (const char * fname)
Definition at line 436 of file Coupling.C.
References agents, cimg_library::cimg::fclose(), cimg_library::cimg::fopen(), Agent::get_agent_name(), and i.
 {
   FILE *f = fopen(fname, "w");
   fprintf(f, "graph: { title: \"Coupling\" \n\
         display_edge_labels: yes \n\
         layoutalgorithm: tree   \n\
         scaling: maxspect   \n\
         node.color     : green   \n\
         node.textcolor : black   \n\
         node.bordercolor: black \n\
         node.borderwidth: 1    \n\
         edge.color     : blue   \n\
         edge.arrowsize : 7   \n\
         edge.thickness : 2   \n\
         edge.fontname:\"helvO08\"  \n\
         node.label: \"no type\" \n");
 //  scheduler.print(f, name());
   for (unsigned int i=0; i<agents.size(); i++) {
     agents[i]->print(f);
     if (i>0) fprintf(f, "edge: { sourcename: \"%s\" targetname: \"%s\" label: \"\"}\n", agents[i-1]->get_agent_name().c_str(), agents[i]->get_agent_name().c_str());
   }
   fprintf(f, "} \n");
   fclose(f);
 }
int ProcessInterrupt ()
Definition at line 572 of file Coupling.C.
References Agent::action, agents, Control_parameters::cur_step, Control_parameters::current_time, i, Control_parameters::InterruptFlag, Control_parameters::LastOutputStep, Control_parameters::LastOutputTime, Control_parameters::maxNumTimeSteps, MPI_COMM_WORLD, Control_parameters::myRank, n, Control_parameters::outputIntervalTime, param, restart_at_time(), RocstarShutdown(), and x.
Referenced by rocstar_driver().
 {
   int save_step = 0;
   bool done = false;
   int fluid_agent_index = 0;
   int action = param->InterruptFlag;
   param->InterruptFlag = 0;
   if(action > 0){
     if(param->myRank == 0)
       std::cout << "Rocstar: Processing interrupt." << std::endl;
     switch(action){
     case 2:
       save_step = param->cur_step;
       restart_at_time(param->LastOutputTime,param->LastOutputStep);
       param->maxNumTimeSteps = save_step;
       param->outputIntervalTime /= 10.0;
       if(!param->myRank){
         std::cout << "Rocstar: Restarting from (time/step): ("
                   << param->current_time << "," << param->cur_step
                   << ") with output"
                   << " interval, " << param->outputIntervalTime << "."
                   << std::endl;
       }
       return(1);
       break;
     case 3:
       for(int i = 0,n=agents.size();i<n && !done;n++){
         std::string::size_type x = agents[i]->get_agent_name().find("lu");
         if( x != string::npos){
           fluid_agent_index = i;
           done = true;
         }
       }
       if(!done){
         std::cerr << "Rocstar: Could not find fluid agent.  Dying."
                   << std::endl;
         RocstarShutdown(1);
       }
       // char* solver: Path to Rocout directory (i.e. blah/blah/Rocflu)
       // double time: timestep to read
       // bool use_parallel_transfer
       // bool remesh_surf: true=remesh surface false=leave surface alone
       // bool transfer_surf: true (only valid if remesh_surf = false)
       // double scaleFactor: scale mesh granularity
       // int fieldWidth: digits in filename partition id
       // int fileBase: 0 is partition ids start at 0, 1 otherwise
       // int debug: 0=off, 1 = some, more = more
       // int ngLayers: number of ghost layers; 0-9
       // returns 1 if success; 0 if fail
       // Rocrem_remesh(const char* solver, double time, bool remesh_surf,
       //               bool transfer_surf, double scaleFactor, MPI_Comm myComm,
       //               int fieldWidth, int fileBase, int debug, int ngLayers)
       //
       // Remeshing test case
       //
 #ifdef ARM
       if(!Rocrem_remesh("Rocflu","Rocout","",param->LastOutputTime,true,true,false,1.0,
                         agents[fluid_agent_index]->get_communicator(),
                         4,0,2,2)){
         if(!param->myRank)
           std::cerr << "Rocstar: Remeshing failed.  Stopping simulation."
                     << std::endl;
         RocstarShutdown(1);
       }
 #else
       if(!param->myRank){
         //      std::ofstream Ouf;
         //      Ouf.open("needs_remesh");
         //      Ouf.close();
         std::cerr << "Rocstar: Online remeshing not enabled. Shutting down." << std::endl;
       }
       RocstarShutdown(1);
 #endif
       MPI_Barrier(MPI_COMM_WORLD);
       restart_at_time(param->LastOutputTime,param->LastOutputStep);
       MPI_Barrier(MPI_COMM_WORLD);
       if(!param->myRank)
         std::cout << "Rocstar: Restarting after remesh at (time/step): ("
                   << param->current_time << "," << param->cur_step << ")"
                   << std::endl;
       return(1);
       break;
     case 4:
       MPI_Barrier(MPI_COMM_WORLD);
       restart_at_time(param->LastOutputTime,param->LastOutputStep);
       MPI_Barrier(MPI_COMM_WORLD);
       if(!param->myRank)
        std::cout << "Rocstar: Warm restarting at (time/step): ("
                  << param->current_time << "," << param->cur_step << ")"
                  << std::endl;
       return(1);
       break;
     default:
       if(!param->myRank)
         std::cout << "Rocstar: Unknown interrupt action: " << action << "."
                   << std::endl;
       return(0);
       break;
     }
   }
   return(0);
 }
void read_restart_info ()
Definition at line 313 of file Coupling.C.
References comm_rank, Control_parameters::current_time, cimg_library::cimg::fclose(), cimg_library::cimg::fopen(), MAN_DEBUG, MPI_COMM_WORLD, param, restartInfo, and Control_parameters::update_start_time().
Referenced by rocstar_driver().
 {
   if (param->current_time != 0.0) {
     FILE *fp = fopen(restartInfo.c_str(), "r");
     if (fp == NULL) {
       std::cerr << "Rocstar: Error: READ_RESTART: Failed to read file " << restartInfo << std::endl;
       MPI_Abort( MPI_COMM_WORLD, -1);
     }
     int curStep;
     double initialTime;
     while (!feof(fp)) {
       fscanf(fp, "%d %le", &curStep, &initialTime);
     }
     fclose(fp);
     if (comm_rank == 0)
       MAN_DEBUG(1,("Rocstar: This run is a restart continued at iteration %d with initial time %f.",curStep, initialTime));
     param->update_start_time(curStep - 1, initialTime);   // subtle - it starts from 0
   }
   else {
     if (comm_rank == 0)
       MAN_DEBUG(2,("Rocstar: This run is not a restart.\n"));
   }
 }
virtual void reload_rocface (const RocmanControl_parameters * param) inline virtual
Reimplemented in FullyCoupling.
Definition at line 190 of file Coupling.h.
Referenced by initialize().
 {}
void restart_at_time (double t, int step)
Definition at line 372 of file Coupling.C.
References agents, COM_get_window_handle(), COM_UNLOAD_MODULE_STATIC_DYNAMIC, comm_rank, Agent::communicator, finalize(), get_control_param(), i, initialize(), MAN_DEBUG, n, param, restarting, cimg_library::cimg::system(), and Control_parameters::update_start_time().
Referenced by ProcessInterrupt(), and rocstar_driver().
 {
   int i, n;
   MAN_DEBUG(3, ("Rocstar: Coupling::restart_at_time with t: %f step:%d.\n", t, step));
 #if 0
   // HACK
   system("rm RocburnAPN/Rocout/*");
   if (comm_rank == 0) {
     system("rm RocburnAPN/Rocout/*");
   }
   MPI_Barrier(get_control_param()->communicator);
 #endif
   restarting = 1;
     // reset windows and buffers
   finalize();
     // unload modules, only call unload to zero out data, skip dlclose
   for ( i=0, n=agents.size(); i<n; ++i) {
     agents[i]->unload_module();
   }
   if (COM_get_window_handle("RFC") > 0) {
     COM_UNLOAD_MODULE_STATIC_DYNAMIC( Rocface, "RFC");
   }
   if (COM_get_window_handle("SURF") > 0) {
     COM_UNLOAD_MODULE_STATIC_DYNAMIC( Rocsurf, "SURF");
   }
   if (COM_get_window_handle("PROP") > 0) {
     COM_UNLOAD_MODULE_STATIC_DYNAMIC( Rocprop, "PROP");
   }
   if (COM_get_window_handle("PROPCON") > 0) {
     COM_UNLOAD_MODULE_STATIC_DYNAMIC(Rocon,"PROPCON");
   }
   if (COM_get_window_handle("BLAS") > 0) {
     COM_UNLOAD_MODULE_STATIC_DYNAMIC(Rocblas,"BLAS");
   }
   if (COM_get_window_handle("MAP") > 0) {
     COM_UNLOAD_MODULE_STATIC_DYNAMIC(Rocmap,"MAP");
   }
     // update to given time
   param->update_start_time( step, t);
     // load module and call physics routine
   for ( i=0, n=agents.size(); i<n; ++i) {
     agents[i]->load_module();
   }
     // proceed to initialization phase
   initialize(1);    // reinit
 /*
     // read restart data
   for ( i=0, n=agents.size(); i<n; ++i) {
     agents[i]->read_restart_data();
   }
 */
   restarting = 0;
 }
double run (double t, double dt, int iPredCorr, double zoom)
Invoke the scheduler.
Definition at line 238 of file Coupling.C.
References agents, comm_rank, i, iPredCorr, MAN_DEBUG, Agent::max_timestep(), min(), n, Scheduler::run_actions(), and scheduler.
Referenced by rocstar_driver().
 {
   iPredCorr = pred;
   // Change dt to the maximum time setp allowed.
   for ( int i=0, n=agents.size(); i<n; ++i) {
     dt = std::min( dt, agents[i]->max_timestep(t, dt));
   }
   MAN_DEBUG(3, ("[%d] Rocstar: Coupling::run with t: %f dt: %f.\n", comm_rank, t, dt));
   scheduler.run_actions( t, dt);
   // Return the new time as t + dt
   if (zoom > 0.0)
     return t + dt*zoom;
   else
     return t + dt;
 }
void run_initactions (double t, double dt)
Definition at line 258 of file Coupling.C.
References comm_rank, init_remeshed, init_scheduler, init_started, MAN_DEBUG, name(), Scheduler::run_actions(), and Scheduler::set_alpha().
Referenced by initialize().
 {
   MAN_DEBUG(3, ("[%d] Rocstar: %s::run_initactions called with t:%e dt:%e.\n", comm_rank, name(), t, dt));
   init_scheduler.set_alpha(0.0);
   init_scheduler.run_actions( t, dt);
   init_started = 0;
   init_remeshed = 0;
 }
void schedule ()
Schedule the top-level actions of the coupling scheme and the actions of the agents.
Definition at line 181 of file Coupling.C.
References agents, i, init_scheduler, n, UserScheduler::schedule(), and scheduler.
Referenced by rocstar_driver().
{
   init_scheduler.schedule();
   scheduler.schedule();
   for ( int i=0, n=agents.size(); i<n; ++i) {
     agents[i]->schedule();
   }
 }
virtual void update_distances (double currentTime) inline virtual
Reimplemented in FullyCoupling.
Definition at line 175 of file Coupling.h.
Referenced by rocstar_driver().
 {}
virtual void update_integrals (double currentTime) inline virtual
Reimplemented in FullyCoupling.
Definition at line 174 of file Coupling.h.
Referenced by rocstar_driver().
 {}
void write_restart_info (double CurrentTime, int iStep)
Definition at line 337 of file Coupling.C.
References comm_rank, cimg_library::cimg::fclose(), cimg_library::cimg::fopen(), MPI_COMM_WORLD, and restartInfo.
Referenced by Interrupt(), and rocstar_driver().
 {
   FILE *fp;
   if ( comm_rank == 0 ) {
        if ( CurrentTime == 0.0)
          fp = fopen(restartInfo.c_str(), "w");
        else
          fp = fopen(restartInfo.c_str(), "a");
        if (fp == NULL) {
          std::cerr << "Rocstar: Error: Failed to open restart info file, "
                    << restartInfo << "." << std::endl;
          MPI_Abort( MPI_COMM_WORLD, -1);
        }
        fprintf( fp, "%d %.20le \n", iStep, CurrentTime);
        fclose( fp);
   }
 }
Member Data Documentation
AgentList agents protected
Definition at line 102 of file Coupling.h.
Referenced by add_agent(), callMethod(), check_convergence(), finalize(), init(), init_convergence(), input(), output_restart_files(), output_visualization_files(), print(), ProcessInterrupt(), restart_at_time(), run(), schedule(), FullyCoupling::update_integrals(), and ~Coupling().
int comm_rank protected
Definition at line 105 of file Coupling.h.
Referenced by baseInit(), read_restart_info(), restart_at_time(), run(), run_initactions(), FullyCoupling::update_distances(), FullyCoupling::update_integrals(), and write_restart_info().
std::string coupling_name protected
Definition at line 100 of file Coupling.h.
std::string distFname protected
Definition at line 123 of file Coupling.h.
Referenced by baseInit(), and FullyCoupling::update_distances().
int init_remeshed protected
Definition at line 108 of file Coupling.h.
Referenced by baseInit(), and run_initactions().
UserScheduler init_scheduler protected
Definition at line 104 of file Coupling.h.
Referenced by callMethod(), finalize(), FluidBurnAlone::FluidBurnAlone(), run_initactions(), and schedule().
int init_started protected
Definition at line 106 of file Coupling.h.
Referenced by baseInit(), and run_initactions().
std::string integFname protected
Definition at line 120 of file Coupling.h.
Referenced by baseInit(), and FullyCoupling::update_integrals().
int iPredCorr protected
Definition at line 110 of file Coupling.h.
Referenced by baseInit(), and run().
int maxPredCorr protected
Definition at line 111 of file Coupling.h.
Referenced by check_convergence(), FluidAlone::FluidAlone(), FluidBurnAlone::FluidBurnAlone(), and init_convergence().
vector<std::string> modules protected
Definition at line 101 of file Coupling.h.
Referenced by Coupling().
int overwrite_dist protected
Definition at line 122 of file Coupling.h.
Referenced by baseInit(), and FullyCoupling::update_distances().
int overwrite_integ protected
Definition at line 119 of file Coupling.h.
Referenced by baseInit(), and FullyCoupling::update_integrals().
Control_parameters* param protected
Definition at line 113 of file Coupling.h.
Referenced by baseInit(), check_convergence(), initialize(), Interrupt(), new_start(), ProcessInterrupt(), read_restart_info(), and restart_at_time().
std::string restartInfo protected
Definition at line 116 of file Coupling.h.
Referenced by baseInit(), read_restart_info(), and write_restart_info().
int restarting protected
Definition at line 107 of file Coupling.h.
Referenced by baseInit(), and restart_at_time().
const RocmanControl_parameters* rocmanparam protected
Definition at line 114 of file Coupling.h.
Referenced by baseInit(), initialize(), and new_start().
UserScheduler scheduler protected
Definition at line 103 of file Coupling.h.
Referenced by callMethod(), finalize(), FluidAlone::FluidAlone(), FluidBurnAlone::FluidBurnAlone(), run(), and schedule().
The documentation for this class was generated from the following files:
Coupling.h
Coupling.C