Rocstar: rflu_modboundxvutils Module Reference
rflu_modboundxvutils Module Reference
Public Member Functions
subroutine, public rflu_bxv_computevarscv (pRegion)
subroutine, public rflu_bxv_createvarscv (pRegion)
subroutine, public rflu_bxv_createvarsdv (pRegion)
subroutine, public rflu_bxv_createvarststep (pRegion)
subroutine, public rflu_bxv_destroyvarscv (pRegion)
subroutine, public rflu_bxv_destroyvarsdv (pRegion)
subroutine, public rflu_bxv_destroyvarststep (pRegion)
subroutine, public rflu_bxv_initvars (pRegion)
subroutine, public rflu_bxv_nullifyvarscv (pRegion)
subroutine, public rflu_bxv_nullifyvarsdv (pRegion)
subroutine, public rflu_bxv_nullifyvarststep (pRegion)
subroutine, public rflu_bxv_readvarsascii (pRegion)
subroutine, public rflu_bxv_readvarsbinary (pRegion)
subroutine, public rflu_bxv_readvarswrapper (pRegion)
subroutine, public rflu_bxv_setdependentvars (pRegion)
subroutine, public rflu_bxv_writevarsascii (pRegion)
subroutine, public rflu_bxv_writevarsbinary (pRegion)
subroutine, public rflu_bxv_writevarswrapper (pRegion)
Private Member Functions
subroutine, private rflu_bxv_compenergypatch (pRegion, pPatch)
subroutine, private rflu_bxv_compmomenergypatch (pRegion, pPatch)
subroutine, private rflu_bxv_setdependentvarspatch (pRegion, pPatch)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModBoundXvUtils.F90,v $ $Revision: 1.6 $'
Detailed Description
Definition at line 39 of file RFLU_ModBoundXvUtils.F90.
Member Function/Subroutine Documentation
subroutine, private rflu_bxv_compenergypatch (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 235 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), Color::g(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), Color::r(), moderror::registerfunction(), and v.
Referenced by rflu_bxv_computevarscv().
subroutine, private rflu_bxv_compmomenergypatch (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 338 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), Color::g(), mixtperf_eo_grtuvw(), mixtperf_g_cpr(), mixtperf_r_m(), Color::r(), moderror::registerfunction(), and v.
Referenced by rflu_bxv_computevarscv().
subroutine, public rflu_bxv_computevarscv (type(t_region), pointer pRegion)
Definition at line 140 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_bxv_compenergypatch(), and rflu_bxv_compmomenergypatch().
Referenced by rungekuttamp().
subroutine, public rflu_bxv_createvarscv (type(t_region), pointer pRegion)
Definition at line 442 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), and rfluinit().
subroutine, public rflu_bxv_createvarsdv (type(t_region), pointer pRegion)
Definition at line 519 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), and rfluinit().
subroutine, public rflu_bxv_createvarststep (type(t_region), pointer pRegion)
Definition at line 595 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
subroutine, public rflu_bxv_destroyvarscv (type(t_region), pointer pRegion)
Definition at line 685 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_bxv_nullifyvarscv().
Referenced by rflu_endflowsolver(), and rfluinit().
subroutine, public rflu_bxv_destroyvarsdv (type(t_region), pointer pRegion)
Definition at line 762 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_bxv_nullifyvarsdv().
Referenced by rflu_endflowsolver(), and rfluinit().
subroutine, public rflu_bxv_destroyvarststep (type(t_region), pointer pRegion)
Definition at line 838 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_bxv_nullifyvarststep().
Referenced by rflu_endflowsolver().
subroutine, public rflu_bxv_initvars (type(t_region), pointer pRegion)
Definition at line 923 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_bxv_setdependentvars(), rflu_modnscbc::rflu_nscbc_initff(), rflu_modnscbc::rflu_nscbc_initiftotang(), rflu_modnscbc::rflu_nscbc_initifveltemp(), rflu_modnscbc::rflu_nscbc_initij(), rflu_modnscbc::rflu_nscbc_initnswheat(), rflu_modnscbc::rflu_nscbc_initnswtemp(), rflu_modnscbc::rflu_nscbc_initof(), and rflu_modnscbc::rflu_nscbc_initsw().
Referenced by rfluinit().
subroutine, public rflu_bxv_nullifyvarscv (type(t_region), pointer pRegion)
Definition at line 1019 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_bxv_destroyvarscv().
subroutine, public rflu_bxv_nullifyvarsdv (type(t_region), pointer pRegion)
Definition at line 1091 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_bxv_destroyvarsdv().
subroutine, public rflu_bxv_nullifyvarststep (type(t_region), pointer pRegion)
Definition at line 1163 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_bxv_destroyvarststep().
subroutine, public rflu_bxv_readvarsascii (type(t_region), pointer pRegion)
Definition at line 1238 of file RFLU_ModBoundXvUtils.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_bxv_readvarswrapper().
subroutine, public rflu_bxv_readvarsbinary (type(t_region), pointer pRegion)
Definition at line 1476 of file RFLU_ModBoundXvUtils.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_bxv_readvarswrapper().
subroutine, public rflu_bxv_readvarswrapper (type(t_region), pointer pRegion)
Definition at line 1715 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_bxv_readvarsascii(), rflu_bxv_readvarsbinary(), and rflu_modnscbc::rflu_nscbc_decidehavenscbc().
Referenced by rflu_initflowsolver().
subroutine, public rflu_bxv_setdependentvars (type(t_region), pointer pRegion)
Definition at line 1787 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_bxv_setdependentvarspatch().
Referenced by rflu_bxv_initvars(), rflu_initflowsolver(), and rungekuttamp().
subroutine, private rflu_bxv_setdependentvarspatch (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1859 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), mixtperf_c_grt(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_r_m(), mixtperf_t_dpr(), Color::r(), moderror::registerfunction(), and v.
Referenced by rflu_bxv_setdependentvars().
subroutine, public rflu_bxv_writevarsascii (type(t_region), pointer pRegion)
Definition at line 2003 of file RFLU_ModBoundXvUtils.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_bxv_writevarswrapper().
subroutine, public rflu_bxv_writevarsbinary (type(t_region), pointer pRegion)
Definition at line 2159 of file RFLU_ModBoundXvUtils.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_bxv_writevarswrapper().
subroutine, public rflu_bxv_writevarswrapper (type(t_region), pointer pRegion)
Definition at line 2314 of file RFLU_ModBoundXvUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_bxv_writevarsascii(), rflu_bxv_writevarsbinary(), and rflu_modnscbc::rflu_nscbc_decidehavenscbc().
Referenced by rflu_endflowsolver(), rflu_timestepping(), and rfluinit().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModBoundXvUtils.F90,v $ $Revision: 1.6 $' private
Definition at line 79 of file RFLU_ModBoundXvUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModBoundXvUtils.F90