Rocstar: rflu_modexplicitmultistage Module Reference
rflu_modexplicitmultistage Module Reference
Public Member Functions
subroutine, public rflu_ems_computeresidual (pRegion)
subroutine, public rflu_ems_setcvold (pRegion)
subroutine, public rflu_ems_setdiss (pRegion)
subroutine, public rflu_ems_setrhs (pRegion)
subroutine, public rflu_ems_updateconservedvars (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModExplicitMultiStage.F90,v $ $Revision: 1.19 $'
Detailed Description
Definition at line 39 of file RFLU_ModExplicitMultiStage.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_ems_computeresidual (type(t_region), pointer pRegion)
Definition at line 98 of file RFLU_ModExplicitMultiStage.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_moddifferentiationbfaces::rflu_computebfgradconstrwrapper(), rflu_computefluxinv(), rflu_moddifferentiationbfaces::rflu_computegradbfaceswrapper(), rflu_moddifferentiationcells::rflu_computegradcellswrapper(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_moddifferentiationfaces::rflu_computegradfaceswrapper(), rflu_modlimiters::rflu_computelimiterbarthjesp(), rflu_modlimiters::rflu_computelimitervenkat(), rflu_modconvertcv::rflu_convertcvcons2prim(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_modlimiters::rflu_createlimiter(), rflu_decideneedbgradface(), rflu_modlimiters::rflu_destroylimiter(), rflu_ems_setdiss(), rflu_ems_setrhs(), rflu_modviscousflux::rflu_enforceheatflux(), rflu_modlimiters::rflu_limitgradcells(), rflu_modlimiters::rflu_limitgradcellssimple(), rflu_modviscousflux::rflu_viscousfluxes(), rflu_modviscousflux::rflu_viscousfluxespatches(), rflu_modweno::rflu_wenogradcellswrapper(), and rflu_modweno::rflu_wenogradcellsxyzwrapper().
Referenced by rflu_explicitmultistage().
subroutine, public rflu_ems_setcvold (type (t_region), pointer pRegion)
Definition at line 326 of file RFLU_ModExplicitMultiStage.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_explicitmultistage().
subroutine, public rflu_ems_setdiss (type (t_region), pointer pRegion)
Definition at line 408 of file RFLU_ModExplicitMultiStage.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_ems_computeresidual().
subroutine, public rflu_ems_setrhs (type (t_region), pointer pRegion)
Definition at line 507 of file RFLU_ModExplicitMultiStage.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_ems_computeresidual().
subroutine, public rflu_ems_updateconservedvars (type (t_region), pointer pRegion)
Definition at line 588 of file RFLU_ModExplicitMultiStage.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_explicitmultistage().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModExplicitMultiStage.F90,v $ $Revision: 1.19 $' private
Definition at line 67 of file RFLU_ModExplicitMultiStage.F90.
The documentation for this module was generated from the following file:
RFLU_ModExplicitMultiStage.F90