Rocstar: rflu_modexactflow Module Reference
rflu_modexactflow Module Reference
Public Member Functions
subroutine, public rflu_computeexactflowculick (global, x, y, z, d, u, v, w, p)
subroutine, public rflu_computeexactflowpacoust (global, x, y, z, t, L, ro, iBc, im, in, iq, etaqm, omega, dTot, pTot, aTot, const, d, u, v, w, p)
subroutine, public rflu_computeexactflowproudman (global, x, y, height, dInc, vInj, pTot, d, u, v, w, p)
subroutine, public rflu_computeexactflowringleb (x, y, rGas, pTot, tTot, d, u, v, w, p)
subroutine, public rflu_computeexactflowssvortex (x, y, gGas, rGas, ri, Mi, pTot, tTot, d, u, v, w, p)
subroutine, public rflu_setexactflowlinear (x, y, z, iVar, var, gx, gy, gz)
subroutine, public rflu_setexactflowtrig (global, nx, ny, nz, x, y, z, iVar, var, gx, gy, gz)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModExactFlow.F90,v $ $Revision: 1.10 $'
Detailed Description
Definition at line 42 of file RFLU_ModExactFlow.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_computeexactflowculick (type(t_global), pointer global, real(rfreal), intent(in) x, real(rfreal), intent(in) y, real(rfreal), intent(in) z, real(rfreal), intent(out) d, real(rfreal), intent(out) u, real(rfreal), intent(out) v, real(rfreal), intent(out) w, real(rfreal), intent(out) p)
Definition at line 103 of file RFLU_ModExactFlow.F90.
References CImg< T >::atan2(), Plane_3< R, T >::d(), Color::r(), sqrt(), v, x, y, and z.
Referenced by rflu_initflowhardcode().
subroutine, public rflu_computeexactflowpacoust (type(t_global), pointer global, real(rfreal), intent(in) x, real(rfreal), intent(in) y, real(rfreal), intent(in) z, real(rfreal), intent(in) t, real(rfreal), intent(in) L, real(rfreal), intent(in) ro, integer, intent(in) iBc, integer, intent(in) im, integer, intent(in) in, integer, intent(in) iq, real(rfreal), intent(in) etaqm, real(rfreal), intent(in) omega, real(rfreal), intent(in) dTot, real(rfreal), intent(in) pTot, real(rfreal), intent(in) aTot, real(rfreal), intent(in) const, real(rfreal), intent(out) d, real(rfreal), intent(out) u, real(rfreal), intent(out) v, real(rfreal), intent(out) w, real(rfreal), intent(out) p)
Definition at line 193 of file RFLU_ModExactFlow.F90.
References CImg< T >::atan2(), Plane_3< R, T >::d(), Color::r(), rflu_modbessel::rflu_jyndd(), sqrt(), Kdtree_d< Traits >::ExtPoint::term(), v, x, y, and z.
Referenced by rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), and rflu_initflowhardcode().
subroutine, public rflu_computeexactflowproudman (type(t_global), pointer global, real(rfreal), intent(in) x, real(rfreal), intent(in) y, real(rfreal), intent(in) height, real(rfreal), intent(in) dInc, real(rfreal), intent(in) vInj, real(rfreal), intent(in) pTot, real(rfreal), intent(out) d, real(rfreal), intent(out) u, real(rfreal), intent(out) v, real(rfreal), intent(out) w, real(rfreal), intent(out) p)
Definition at line 309 of file RFLU_ModExactFlow.F90.
References Plane_3< R, T >::d(), v, x, and y.
Referenced by rflu_computeexactflowerror(), rflu_modextractflowdata::rflu_extractflowdataproudman(), rflu_initbcdatahardcode(), and rflu_initflowhardcode().
subroutine, public rflu_computeexactflowringleb (real(rfreal), intent(in) x, real(rfreal), intent(in) y, real(rfreal), intent(in) rGas, real(rfreal), intent(in) pTot, real(rfreal), intent(in) tTot, real(rfreal), intent(out) d, real(rfreal), intent(out) u, real(rfreal), intent(out) v, real(rfreal), intent(out) w, real(rfreal), intent(out) p)
Definition at line 385 of file RFLU_ModExactFlow.F90.
References Line_2< R, T >::a(), Color::alpha(), Plane_3< R, T >::d(), j, k, min(), mixtperf_c_grt(), mixtperf_d_prt(), sign(), sqrt(), v, x, and y.
Referenced by rflu_computeexactflowerror(), rflu_initbcdatahardcode(), and rflu_initflowhardcode().
subroutine, public rflu_computeexactflowssvortex (real(rfreal), intent(in) x, real(rfreal), intent(in) y, real(rfreal), intent(in) gGas, real(rfreal), intent(in) rGas, real(rfreal), intent(in) ri, real(rfreal), intent(in) Mi, real(rfreal), intent(in) pTot, real(rfreal), intent(in) tTot, real(rfreal), intent(out) d, real(rfreal), intent(out) u, real(rfreal), intent(out) v, real(rfreal), intent(out) w, real(rfreal), intent(out) p)
Definition at line 535 of file RFLU_ModExactFlow.F90.
References Color::alpha(), Plane_3< R, T >::d(), mixtperf_c_grt(), mixtperf_d_dogma(), mixtperf_d_prt(), mixtperf_p_ddogpo(), mixtperf_p_gmapo(), mixtperf_t_dpr(), pi, Color::r(), sqrt(), Kdtree_d< Traits >::ExtPoint::term(), v, x, and y.
Referenced by rflu_computeexactflowerror(), rflu_initbcdatahardcode(), and rflu_initflowhardcode().
subroutine, public rflu_setexactflowlinear (real(rfreal), intent(in) x, real(rfreal), intent(in) y, real(rfreal), intent(in) z, integer, intent(in) iVar, real(rfreal), intent(out) var, real(rfreal), intent(out) gx, real(rfreal), intent(out) gy, real(rfreal), intent(out) gz)
Definition at line 622 of file RFLU_ModExactFlow.F90.
References Line_2< R, T >::a(), Color::b(), Line_2< R, T >::c(), x, y, and z.
Referenced by rflu_computeexactflowerror(), rflu_modplottingvars::rflu_computeplottingvarsgraderr(), and rflu_initflowhardcode().
subroutine, public rflu_setexactflowtrig (type(t_global), pointer global, real(rfreal), intent(in) nx, real(rfreal), intent(in) ny, real(rfreal), intent(in) nz, real(rfreal), intent(in) x, real(rfreal), intent(in) y, real(rfreal), intent(in) z, integer, intent(in) iVar, real(rfreal), intent(out) var, real(rfreal), intent(out) gx, real(rfreal), intent(out) gy, real(rfreal), intent(out) gz)
Definition at line 698 of file RFLU_ModExactFlow.F90.
References Line_2< R, T >::a(), Color::b(), Line_2< R, T >::c(), x, y, and z.
Referenced by rflu_computeexactflowerror(), rflu_modplottingvars::rflu_computeplottingvarsgraderr(), and rflu_initflowhardcode().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModExactFlow.F90,v $ $Revision: 1.10 $' private
Definition at line 63 of file RFLU_ModExactFlow.F90.
The documentation for this module was generated from the following file:
RFLU_ModExactFlow.F90