Rocstar: setup_py Module Reference
setup_py Module Reference
Public Member Functions
subroutine get_time_step_1d (bp, rb, Toa, dt_max)
subroutine burn_init_0d (bp, comm, IN_DIR, nx_read, To_read)
subroutine read_properties (bp, IN_DIR)
subroutine grid (bp)
subroutine readtable (bp, IN_DIR)
subroutine steadytemp (bp, TIN, pIN, out, rb, g)
subroutine check_input_range (bp)
subroutine burn_finalize_0d (bp)
Detailed Description
Definition at line 23 of file setup_py.f90.
Member Function/Subroutine Documentation
subroutine burn_finalize_0d (type(parameter_structure), pointer bp)
Definition at line 575 of file setup_py.f90.
subroutine burn_init_0d (type(parameter_structure), pointer bp, integer, intent(in) comm, character(*), intent(in) IN_DIR, integer, intent(out) nx_read, real(dbl), intent(out) To_read)
Definition at line 50 of file setup_py.f90.
References grid(), rank, read_properties(), and readtable().
Referenced by burn_initialize().
subroutine check_input_range (type(parameter_structure), pointer bp)
Definition at line 533 of file setup_py.f90.
References StopWatch::stop(), and Matrix3D::zero().
Referenced by read_properties().
subroutine get_time_step_1d (type(parameter_structure), pointer bp, real(dbl), intent(in) rb, real(dbl), intent(in) Toa, real(dbl), intent(out) dt_max)
Definition at line 30 of file setup_py.f90.
Referenced by m_init_1dmodules::rocburn_init_funcs_py(), m_init_1dmodules::rocburn_init_funcs_zn(), and m_rocburn_2d::update().
subroutine grid (type(parameter_structure), pointer bp)
Definition at line 257 of file setup_py.f90.
References i, Aff_transformation_repS2< FT >::print(), rank, Kdtree_d< Traits >::ExtPoint::term(), x, Bbox_2::xmax(), and z.
Referenced by burn_init_0d(), convertflo2flumesh(), convertflo2flupatch(), getbndverttype(), peul_allocatememory(), peul_rocflo_post(), plag_processeulerfield(), plag_writestattecascii(), rflo_allocatememory(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_laplacegridsmoo(), rflo_modmovegridelliptfra::rflo_mgelliptinterfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptinterfacesglo(), rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptsurfacesglo(), rflo_modmovegridframe::rflo_mgframebroadcast(), rflo_modmovegridframe::rflo_mgframecornpoints(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframeedges(), rflo_modmovegridframe::rflo_mgframeinterfaces(), rflo_modmovegridframe::rflo_mgframemovecorners(), rflo_modmovegridframe::rflo_mgframeorthoshift(), rflo_modmovegridframe::rflo_mgframerestoreexternal(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_modmovegridframe::rflo_mgframesurfaces(), rflo_movegridblocks(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_modvolmeshsmoothing::rflo_vmsinit(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rocflo_post(), rocflo_toflu(), rvav_blasiussolution(), rvav_computeanalyticalsolution(), rvav_extractvariables(), rvav_gammbumpsolution(), rvav_proudmanculicksolution(), rvav_readfilestream1(), rvav_readfilestream2analyt(), rvav_readfilestream2comput(), rvav_readfilestream2experm(), turb_initsolution(), turb_rflu_readsolutionascii(), turb_rflu_readsolutionbinary(), turb_rflu_writesolutionascii(), and turb_rflu_writesolutionbinary().
subroutine read_properties (type(parameter_structure), pointer bp, character*(*), intent(in) IN_DIR)
Definition at line 89 of file setup_py.f90.
References check_input_range(), Plane_3< R, T >::d(), rank, Attribute::status(), and Attribute::unit().
Referenced by burn_init_0d().
subroutine readtable (type(parameter_structure), pointer bp, character*(*), intent(in) IN_DIR)
Definition at line 357 of file setup_py.f90.
References Plane_3< R, T >::d(), Color::g(), i, j, max(), rank, Attribute::status(), and steadytemp().
Referenced by burn_init_0d().
subroutine steadytemp (type(parameter_structure), pointer bp, real(dbl) TIN, real(dbl) pIN, real(dbl) out, real(dbl) rb, real(dbl) g)
Definition at line 503 of file setup_py.f90.
References Color::g(), Verbose_ostream::out(), block::pin(), and data_py::polin2().
Referenced by readtable().
The documentation for this module was generated from the following file:
setup_py.f90