Rocstar: Container_from_circulator< C > Class Template Reference
Container_from_circulator< C > Class Template Reference
#include <circulator.h>
Public Types
typedef C Circulator
typedef C::value_type value_type
typedef value_type & reference
typedef const value_type & const_reference
typedef value_type * pointer
typedef const value_type * const_pointer
typedef C::size_type size_type
typedef C::difference_type difference_type
typedef
Iterator_from_circulator< C,
reference, pointer > iterator
typedef
Iterator_from_circulator< C,
const_reference, const_pointer > const_iterator
Public Member Functions
Container_from_circulator ()
Container_from_circulator (const C &c)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Private Attributes
C anchor
Detailed Description
template<class C>
class Container_from_circulator< C >
Definition at line 712 of file circulator.h.
Member Typedef Documentation
typedef C Circulator
Definition at line 731 of file circulator.h.
typedef Iterator_from_circulator< C, const_reference, const_pointer> const_iterator
Definition at line 744 of file circulator.h.
typedef const value_type* const_pointer
Definition at line 737 of file circulator.h.
typedef const value_type& const_reference
Definition at line 735 of file circulator.h.
typedef C::difference_type difference_type
Definition at line 739 of file circulator.h.
typedef Iterator_from_circulator< C, reference, pointer> iterator
Definition at line 742 of file circulator.h.
typedef value_type* pointer
Definition at line 736 of file circulator.h.
typedef value_type& reference
Definition at line 734 of file circulator.h.
typedef C::size_type size_type
Definition at line 738 of file circulator.h.
typedef C::value_type value_type
Definition at line 733 of file circulator.h.
Constructor & Destructor Documentation
Container_from_circulator () inline
Definition at line 719 of file circulator.h.
 {}
Container_from_circulator (const C & c) inline
Definition at line 722 of file circulator.h.
         : anchor(get_min_circulator(c)) {}
Member Function Documentation
iterator begin () inline
Definition at line 748 of file circulator.h.
References Container_from_circulator< C >::anchor.
                      {
         // the start iterator.
         return iterator( &anchor, 0);
     }
const_iterator begin () const inline
Definition at line 752 of file circulator.h.
References Container_from_circulator< C >::anchor.
{
         // the start const iterator.
         return const_iterator( &anchor, 0);
     }
iterator end () inline
Definition at line 756 of file circulator.h.
References Container_from_circulator< C >::anchor, and CGAL_CIRC_NULL.
Referenced by bccaseloop(), inrt_readinputfile(), inrt_readmaterialinput(), peri_readinputfile(), peul_readbcinputfile(), peul_readinputfile(), plag_readinputfile(), plag_readpdffromfile(), readbcinputfile(), readinputfile(), rflo_readbcfromfile(), rflo_readbcinputfile(), rflo_readdatafileint(), rflo_readdatafilereal(), rflo_readregionmapsection(), rflo_readregiontopology(), rflo_readtbcinputfile(), rflo_readtbcsection(), rflu_modgambit::rflu_readgridgambitneutral(), rflu_readstat(), rflu_readtbcsection(), rvav_blasiussolution(), rvav_readcomparisonssection(), rvav_readfilestream2analyt(), rvav_readfilestream2experm(), rvav_readinputfile(), turb_readbcinputfile(), and turb_readinputfile().
                    {
         // the past-the-end iterator.
         return anchor == CGAL_CIRC_NULL ?  iterator( &anchor, 0)
                                         :  iterator( &anchor, 1);
     }
const_iterator end () const inline
Definition at line 761 of file circulator.h.
References Container_from_circulator< C >::anchor, and CGAL_CIRC_NULL.
{
         // the past-the-end const iterator.
         return anchor == CGAL_CIRC_NULL ?  const_iterator( &anchor, 0)
                                         :  const_iterator( &anchor, 1);
     }
Member Data Documentation
C anchor private
Definition at line 714 of file circulator.h.
Referenced by Container_from_circulator< C >::begin(), and Container_from_circulator< C >::end().
The documentation for this class was generated from the following file:
circulator.h