Rocstar: GeneralizedConditionNumberQualityMetric Class Reference
GeneralizedConditionNumberQualityMetric Class Reference
Computes the condition number of given element. The``condition number" is scaled between one and infinity, with an ideal element having condition number one.
#include <GeneralizedConditionNumberQualityMetric.hpp>
Public Member Functions
GeneralizedConditionNumberQualityMetric ()
virtual ~GeneralizedConditionNumberQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &fval, MsqError &err)
evaluate using mesquite objects
bool evaluate_vertex (PatchData &pd, MsqVertex *vertex, double &fval, MsqError &err)
Evaluate the "condition number" for a vertex.
GeneralizedConditionNumberQualityMetric ()
virtual ~GeneralizedConditionNumberQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &fval, MsqError &err)
evaluate using mesquite objects
bool evaluate_vertex (PatchData &pd, MsqVertex *vertex, double &fval, MsqError &err)
Evaluate the "condition number" for a vertex.
Public Member Functions inherited from ShapeQualityMetric
virtual ~ShapeQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
virtual ~ShapeQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Protected Member Functions
bool compute_condition_number (PatchData &pd, MsqMeshEntity *elem, Vector3D *jacobian_vectors, int num_jacobian_vectors, double &fval, MsqError &err)
bool compute_condition_number (PatchData &pd, MsqMeshEntity *elem, Vector3D *jacobian_vectors, int num_jacobian_vectors, double &fval, MsqError &err)
Protected Member Functions inherited from ShapeQualityMetric
bool condition_number_2d (Vector3D temp_vec[], size_t v_ind, PatchData &pd, double &fval, MsqError &err)
Given the 2-d jacobian matrix, compute the condition number, fval.
bool condition_number_3d (Vector3D temp_vec[], PatchData &pd, double &fval, MsqError &err)
Given the 3-d jacobian matrix, compute the condition number, fval.
bool condition_number_2d (Vector3D temp_vec[], size_t v_ind, PatchData &pd, double &fval, MsqError &err)
Given the 2-d jacobian matrix, compute the condition number, fval.
bool condition_number_3d (Vector3D temp_vec[], PatchData &pd, double &fval, MsqError &err)
Given the 3-d jacobian matrix, compute the condition number, fval.
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
Computes the condition number of given element. The``condition number" is scaled between one and infinity, with an ideal element having condition number one.
Constructor defaults the metric to the LINEAR averaging method and ELEMENT_VERTICES sample points. The default metric name is "Condition Number". It does require a feasible region, and the metric needs to be maximized.
Definition at line 61 of file includeLinks/GeneralizedConditionNumberQualityMetric.hpp.
Constructor & Destructor Documentation
GeneralizedConditionNumberQualityMetric ()
Definition at line 51 of file QualityMetric/Shape/GeneralizedConditionNumberQualityMetric.cpp.
References MSQ_CHKERR.
 {
   MsqError err;
   set_metric_type(ELEMENT_BASED);
   set_element_evaluation_mode(ELEMENT_VERTICES, err); MSQ_CHKERR(err);
   avgMethod=QualityMetric::LINEAR;
   feasible=1;
   set_name("Generalized Condition Number");
 }
virtual ~GeneralizedConditionNumberQualityMetric () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 68 of file includeLinks/GeneralizedConditionNumberQualityMetric.hpp.
         {}
GeneralizedConditionNumberQualityMetric ()
virtual ~GeneralizedConditionNumberQualityMetric () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 68 of file src/QualityMetric/Shape/GeneralizedConditionNumberQualityMetric.hpp.
         {}
Member Function Documentation
bool compute_condition_number (PatchData & pd, MsqMeshEntity * elem, Vector3D * jacobian_vectors, int num_jacobian_vectors, double & fval, MsqError & err) inline protected
Definition at line 90 of file includeLinks/GeneralizedConditionNumberQualityMetric.hpp.
References PatchData::domain_set(), PatchData::get_domain_normal_at_vertex(), MsqMeshEntity::get_vertex_index(), Mesquite::length(), MSQ_ERRZERO, Mesquite::MSQ_MAX_CAP, Mesquite::MSQ_MIN, and sqrt().
    {
        //PRINT_INFO("INSIDE CONDITION NUMBER COMPUTE_CON\n");
      double temp_var=0;
      if(num_jacobian_vectors==2){
        size_t vert=element->get_vertex_index(0);
        Vector3D cross_vec=jacobian_vectors[0]*jacobian_vectors[1];
        if ( pd.domain_set() ) {
          Vector3D norm_vec;
          pd.get_domain_normal_at_vertex(vert,false,norm_vec,err);MSQ_ERRZERO(err);
          if(cross_vec%norm_vec<0.0){
            return false;
          }
        }
        temp_var=fabs((cross_vec).length());
        fval=jacobian_vectors[0].length_squared();
        fval+=jacobian_vectors[1].length_squared();
        if(temp_var>=MSQ_MIN){ //if not degenerate
          fval/=(2.0*temp_var);
        }
        else{
          fval=MSQ_MAX_CAP;
        }
        return true;
      }
        //if three jacobian vectors (3D elem)
      else if(num_jacobian_vectors==3){
          //norm squared of J
        double term1=jacobian_vectors[0]%jacobian_vectors[0]+
           jacobian_vectors[1]%jacobian_vectors[1]+
           jacobian_vectors[2]%jacobian_vectors[2];
          //norm squared of adjoint of J
        double term2=(jacobian_vectors[0]*jacobian_vectors[1])%
           (jacobian_vectors[0]*jacobian_vectors[1])+
           (jacobian_vectors[1]*jacobian_vectors[2])%
           (jacobian_vectors[1]*jacobian_vectors[2])+
           (jacobian_vectors[2]*jacobian_vectors[0])%
           (jacobian_vectors[2]*jacobian_vectors[0]);
          //det of J
        temp_var=jacobian_vectors[0]%(jacobian_vectors[1]*jacobian_vectors[2]);
        if(temp_var<=0.0){
          return false;
        }
        fval=sqrt(term1*term2);
        if(fval>MSQ_MIN){
            //if not degenerate or inverted???
          fval/=(3*temp_var);
        }
        else{
          fval=MSQ_MAX_CAP;
        }
      }
      else{
        fval=MSQ_MAX_CAP;
      }
      return true;
    }
bool compute_condition_number (PatchData & pd, MsqMeshEntity * elem, Vector3D * jacobian_vectors, int num_jacobian_vectors, double & fval, MsqError & err) protected
bool evaluate_element (PatchData & pd, MsqMeshEntity * element, double & fval, MsqError & err) virtual
evaluate using mesquite objects
Reimplemented from QualityMetric.
bool evaluate_element (PatchData & pd, MsqMeshEntity * element, double & fval, MsqError & err) virtual
evaluate using mesquite objects
Reimplemented from QualityMetric.
Definition at line 103 of file QualityMetric/Shape/GeneralizedConditionNumberQualityMetric.cpp.
References MsqMeshEntity::compute_weighted_jacobian(), MsqMeshEntity::get_sample_points(), i, MSQ_CHKERR, and MSQ_ERRZERO.
 {
   int num_sample_points;
   bool return_flag;
   vector<Vector3D> sample_points;
   ElementEvaluationMode eval_mode = get_element_evaluation_mode();
   element->get_sample_points(eval_mode,sample_points,err);  MSQ_ERRZERO(err);
   vector<Vector3D>::iterator iter=sample_points.begin();
     // loop over sample points
   Vector3D jacobian_vectors[3];
   short num_jacobian_vectors;
   int i=0;
   num_sample_points=sample_points.size();
   std::vector<double> metric_values(num_sample_points);
     //Vector3D* current_sample_point;
   for(i=0;i<num_sample_points;++i){
       // compute weighted jacobian
     element->compute_weighted_jacobian(pd, (*iter),
                                        jacobian_vectors,
                                        num_jacobian_vectors, err); MSQ_ERRZERO(err);
       // evaluate condition number at ith sample point
       //if 2 jacobian vectors (2D elem)
     return_flag=compute_condition_number(pd, element, jacobian_vectors,
                                          num_jacobian_vectors,
                                          metric_values[i],err);
     if(MSQ_CHKERR(err) || !return_flag){
       return false;
     }
     ++iter;
   }// end loop over sample points
   fval=average_metrics(&metric_values[0],num_sample_points,err); MSQ_ERRZERO(err);
   return true;
 }
bool evaluate_vertex (PatchData & pd, MsqVertex * vertex, double & fval, MsqError & err) virtual
Evaluate the "condition number" for a vertex.
Reimplemented from QualityMetric.
Definition at line 142 of file QualityMetric/Shape/GeneralizedConditionNumberQualityMetric.cpp.
References MSQ_SETERR.
 {
   MSQ_SETERR(err)("Condition Number's evaluate_vertex is currently "
                   "being implemented", MsqError::NOT_IMPLEMENTED);
   fval=0.0;
   return false;
     /*
   fval=0.0;
   size_t this_vert = pd.get_vertex_index(vert);
   vector<size_t> adj_elems;
   pd.get_vertex_element_indices(this_vert, adg_elems, err);
   double num_elems = adj_elems.size();
   double *metric_values=new double[ num_elems ];
   int num_jacobian_vectors;
   Vector3D sample_point;
   Vecotr3D jacobian_vectors[3];
   int i;
   for ( i = 0; i<num_elems; i++){
     elems[i]->get_sample_point(vertex, sample_point, err); MSQ_CHKERR(err);
     elems[i]->compute_weighted_jacobian(&current_sample_point,
                                         jacobian_vectors,
                                         num_jacobian_vectors, err);
                                         MSQ_CHKERR(err);
     metric_values[i]=compute_condition_number(jacobian_vectors,
                                               num_jacobian_vectors, err);
                                               MSQ_CHKERR(err);
   }
   total_metric=average_metrics(metric_values, num_elems, err);
   MSQ_CHKERR(err);
   delete metric_values;
     */
 }
bool evaluate_vertex (PatchData & pd, MsqVertex * vertex, double & fval, MsqError & err) virtual
Evaluate the "condition number" for a vertex.
Reimplemented from QualityMetric.
The documentation for this class was generated from the following files:
includeLinks/GeneralizedConditionNumberQualityMetric.hpp
QualityMetric/Shape/GeneralizedConditionNumberQualityMetric.cpp