Rocstar: rflo_modforcesmoments Module Reference
rflo_modforcesmoments Module Reference
Public Member Functions
subroutine, public rflo_computepatchforcemomco (region)
subroutine, public rflo_computeintegralforcemomco (global)
subroutine, public rflo_writeintegralforcemomco (global)
subroutine, public rflo_openforcemomcofile (global)
subroutine, public rflo_findpatchcoeffsglo (regions)
subroutine, public rflo_writepatchcoeffsinfo (regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModForcesMoments.F90,v $ $Revision: 1.6 $'
Detailed Description
Definition at line 39 of file RFLO_ModForcesMoments.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_computeintegralforcemomco (type(t_global), pointer global)
Definition at line 349 of file RFLO_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflo_dualtimestepping(), and rflo_timestepping().
subroutine, public rflo_computepatchforcemomco (type (t_region) region)
Definition at line 93 of file RFLO_ModForcesMoments.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, max(), min(), moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), rflo_getpatchindicesnodes(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by rflo_dualtimestepping(), and rflo_timestepping().
subroutine, public rflo_findpatchcoeffsglo (type (t_region), dimension(:), pointer regions)
Definition at line 647 of file RFLO_ModForcesMoments.F90.
References moderror::deregisterfunction(), i, j, k, max(), min(), moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by rflo_getgeometry().
subroutine, public rflo_openforcemomcofile (type (t_global), pointer global)
Definition at line 503 of file RFLO_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modtools::floatless(), form, Aff_transformation_repS2< FT >::print(), moderror::registerfunction(), and Attribute::status().
Referenced by rflo_initflowsolver().
subroutine, public rflo_writeintegralforcemomco (type(t_global), pointer global)
Definition at line 421 of file RFLO_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflo_dualtimestepping(), and rflo_timestepping().
subroutine, public rflo_writepatchcoeffsinfo (type(t_region), dimension(:), pointer regions)
Definition at line 764 of file RFLO_ModForcesMoments.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), Attribute::status(), RFC_Data_const< _Tag >::tag(), and x.
Referenced by rflo_getgeometry().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModForcesMoments.F90,v $ $Revision: 1.6 $' private
Definition at line 66 of file RFLO_ModForcesMoments.F90.
The documentation for this module was generated from the following file:
RFLO_ModForcesMoments.F90