Rocstar: rflu_modgeometry Module Reference
rflu_modgeometry Module Reference
Public Member Functions
subroutine, public rflu_buildbvertexnormals (pRegion)
subroutine, public rflu_buildgeometry (pRegion, sypeFaceFlag)
subroutine, public rflu_computeapproxcentroids (pRegion)
subroutine, public rflu_computefacedist (pRegion)
subroutine, public rflu_createapproxcentroids (pRegion)
subroutine, public rflu_createfacedist (pRegion)
subroutine, public rflu_creategeometry (pRegion)
subroutine, public rflu_destroyapproxcentroids (pRegion)
subroutine, public rflu_destroyfacedist (pRegion)
subroutine, public rflu_destroygeometry (pRegion)
subroutine, public rflu_nullifyapproxcentroids (pRegion)
subroutine, public rflu_nullifygeometry (pRegion)
Private Member Functions
subroutine rflu_nullifyfacedist (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModGeometry.F90,v $ $Revision: 1.35 $'
Detailed Description
Definition at line 46 of file RFLU_ModGeometry.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildbvertexnormals (type(t_region), pointer pRegion)
Definition at line 110 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), ic, moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_buildgeometry().
subroutine, public rflu_buildgeometry (type (t_region), pointer pRegion, logical, optional sypeFaceFlag)
Definition at line 280 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), moderror::errorstop(), facecentroidquad(), facecentroidtria(), facevectorquad(), facevectortria(), ic, max(), modsortsearch::quicksortrfreal(), moderror::registerfunction(), rflu_buildbvertexnormals(), rflu_computeapproxcentroids(), rflu_createapproxcentroids(), rflu_destroyapproxcentroids(), rflu_modcellfaceedgeinfo::rflu_getfacekind(), rflu_modcellfaceedgeinfo::rflu_getglobalcellkind(), rflu_printlocinfo(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_flowsolver(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_postprocessregionscommon1(), rflu_timestepping(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_computeapproxcentroids (type(t_region), pointer pRegion)
Definition at line 1208 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_buildgeometry(), and rflu_modcobalt::rflu_convcobalt2rocflu().
subroutine, public rflu_computefacedist (type(t_region), pointer pRegion)
Definition at line 1451 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), dot_product(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
subroutine, public rflu_createapproxcentroids (type(t_region), pointer pRegion)
Definition at line 1558 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyapproxcentroids().
Referenced by rflu_buildgeometry(), and rflu_modcobalt::rflu_convcobalt2rocflu().
subroutine, public rflu_createfacedist (type(t_region), pointer pRegion)
Definition at line 1648 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyfacedist().
Referenced by rflu_initflowsolver().
subroutine, public rflu_creategeometry (type(t_region), pointer pRegion)
Definition at line 1754 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), moderror::errorstop(), ic, moderror::registerfunction(), and rflu_nullifygeometry().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_destroyapproxcentroids (type(t_region), pointer pRegion)
Definition at line 1960 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyapproxcentroids().
Referenced by rflu_buildgeometry(), and rflu_modcobalt::rflu_convcobalt2rocflu().
subroutine, public rflu_destroyfacedist (type(t_region), pointer pRegion)
Definition at line 2051 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyfacedist().
subroutine, public rflu_destroygeometry (type(t_region), pointer pRegion)
Definition at line 2155 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifygeometry().
Referenced by rflu_endflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon2(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_nullifyapproxcentroids (type(t_region), pointer pRegion)
Definition at line 2296 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createapproxcentroids(), and rflu_destroyapproxcentroids().
subroutine rflu_nullifyfacedist (type(t_region), pointer pRegion) private
Definition at line 2376 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createfacedist(), and rflu_destroyfacedist().
subroutine, public rflu_nullifygeometry (type(t_region), pointer pRegion)
Definition at line 2464 of file RFLU_ModGeometry.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_creategeometry(), and rflu_destroygeometry().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModGeometry.F90,v $ $Revision: 1.35 $' private
Definition at line 79 of file RFLU_ModGeometry.F90.
The documentation for this module was generated from the following file:
RFLU_ModGeometry.F90