Rocstar: Direction_3< R, T > Class Template Reference
Direction_3< R, T > Class Template Reference
#include <cartesian_classes.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Direction_3_base RDirection_3
typedef R::Vector_3_base RVector_3
Public Member Functions
Direction_3 ()
Direction_3 (const CGAL::Direction_3< R > &d)
Direction_3 (const RDirection_3 &d)
Direction_3 (const RVector_3 &v)
Direction_3 (const RT &hx, const RT &hy, const RT &hz)
bool operator== (const CGAL::Direction_3< R > &d) const
bool operator!= (const CGAL::Direction_3< R > &d) const
CGAL::Vector_3< R > vector () const
CGAL::Vector_3< R > to_vector () const
CGAL::Direction_3< R > transform (const CGAL::Aff_transformation_3< R > &t) const
CGAL::Direction_3< R > operator- () const
RT delta (int i) const
RT dx () const
RT dy () const
RT dz () const
Detailed Description
template<class R, class T = typename R::Rep_tag>
class Direction_3< R, T >
Definition at line 80 of file cartesian_classes.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 87 of file Direction_3.h.
typedef R_ R
Definition at line 85 of file Direction_3.h.
typedef R::Direction_3_base RDirection_3
Definition at line 88 of file Direction_3.h.
typedef R::RT RT
Definition at line 86 of file Direction_3.h.
typedef R::Vector_3_base RVector_3
Definition at line 89 of file Direction_3.h.
Constructor & Destructor Documentation
Direction_3 () inline
Definition at line 91 of file Direction_3.h.
   {}
Direction_3 (const CGAL::Direction_3< R > & d) inline
Definition at line 93 of file Direction_3.h.
     : RDirection_3( (const RDirection_3& )d )
   {}
Direction_3 (const RDirection_3< R, T > & d) inline
Definition at line 96 of file Direction_3.h.
     : RDirection_3(d)
   {}
Direction_3 (const RVector_3 & v) inline
Definition at line 99 of file Direction_3.h.
     : RDirection_3(v)
   {}
Direction_3 (const RT & hx, const RT & hy, const RT & hz) inline
Definition at line 102 of file Direction_3.h.
     : RDirection_3(hx, hy, hz)
   {}
Member Function Documentation
RT delta (int i) const inline
Definition at line 124 of file Direction_3.h.
   { return RDirection_3::delta(i); }
RT dx () const inline
Definition at line 127 of file Direction_3.h.
   { return RDirection_3::dx(); }
RT dy () const inline
Definition at line 130 of file Direction_3.h.
   { return RDirection_3::dy(); }
RT dz () const inline
Definition at line 133 of file Direction_3.h.
Referenced by rflu_modrepair3d::angfnd(), mixtgasliq_p(), mixtliq_d_dobpppobttto(), plag_rflu_correctmixtproperties(), rflu_modrepair3d::replace(), rflo_modelliptsmoothing::rflo_elliptgridgauss2d(), rflo_modelliptsmoothing::rflo_elliptgridjac2d(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modelliptsmoothing::rflo_elliptgridsmooregion(), rflo_modelliptsmoothing::rflo_elliptgridsor2d(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangegeometrycopy(), rflo_exchangegeometryrecv(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modbilinearpatch::rflu_blin_findclosestpoint(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationbfaces::rflu_computegradbfaces(), rflu_moddifferentiationcells::rflu_computegradcells_3d(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationcells::rflu_computegradcellsfast_3d(), rflu_moddifferentiationfaces::rflu_computegradfaces(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_modweights::rflu_computestencilmoments3d1(), rflu_modgridutils::rflu_distortgrid(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_modincelltest::rflu_ict_testfacequadbilinear(), rflu_modinterpolation::rflu_interpcells2face(), rflu_modinterpolation::rflu_interpcells2facepatch(), rflu_modinterpolation::rflu_interpcells2faces(), rflu_modlimiters::rflu_limitgradcellssimple(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modrepair3d::rflu_repair3d(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxc2_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_scalarsecondpatch(), rflu_timestepviscous(), rocflo_2dto3d(), rflu_modrepair3d::smooth(), rflu_modrepair3d::tessel(), and rflu_modrepair3d::tetmod().
   { return RDirection_3::dz(); }
bool operator!= (const CGAL::Direction_3< R > & d) const inline
Definition at line 109 of file Direction_3.h.
   { return !(*this == d); }
CGAL::Direction_3<R> operator- () const inline
Definition at line 121 of file Direction_3.h.
References operator-().
   { return RDirection_3::operator-(); }
bool operator== (const CGAL::Direction_3< R > & d) const inline
Definition at line 106 of file Direction_3.h.
References operator==().
   { return RDirection_3::operator==(d); }
CGAL::Vector_3<R> to_vector () const inline
Definition at line 115 of file Direction_3.h.
   { return (CGAL::Vector_3<R>)RDirection_3::to_vector(); }
CGAL::Direction_3<R> transform (const CGAL::Aff_transformation_3< R > & t) const inline
Definition at line 118 of file Direction_3.h.
   { return RDirection_3::transform(t); }
CGAL::Vector_3<R> vector () const inline
Definition at line 112 of file Direction_3.h.
   { return (CGAL::Vector_3<R>)RDirection_3::to_vector(); }
The documentation for this class was generated from the following files:
cartesian_classes.h
Direction_3.h