Rocstar: rflu_modpetscpoisson Module Reference
rflu_modpetscpoisson Module Reference
Public Member Functions
subroutine, public rflu_petsc_buildpoisson (pRegion)
subroutine, public rflu_petsc_createpoisson (pRegion)
subroutine, public rflu_petsc_setsolverpoisson (pRegion)
subroutine, public rflu_petsc_solvepressurepoisson (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPETScPoisson.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file RFLU_ModPETScPoisson.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_petsc_buildpoisson (type(t_region), pointer pRegion)
Definition at line 99 of file RFLU_ModPETScPoisson.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, j, jbeg, jend, moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
subroutine, public rflu_petsc_createpoisson (type(t_region), pointer pRegion)
Definition at line 267 of file RFLU_ModPETScPoisson.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and CImg< T >::sum().
subroutine, public rflu_petsc_setsolverpoisson (type(t_region), pointer pRegion)
Definition at line 459 of file RFLU_ModPETScPoisson.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_petsc_solvepressurepoisson (type(t_region), pointer pRegion)
Definition at line 602 of file RFLU_ModPETScPoisson.F90.
References Color::b(), moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_getcvloc(), CImg< T >::sum(), and x.
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPETScPoisson.F90,v $ $Revision: 1.5 $' private
Definition at line 70 of file RFLU_ModPETScPoisson.F90.
The documentation for this module was generated from the following file:
RFLU_ModPETScPoisson.F90