Rocstar: Matrix3D Class Reference
Matrix3D Class Reference
3*3 Matric class, row-oriented, 0-based [i][j] indexing.
#include <Matrix3D.hpp>
Public Member Functions
Matrix3D ()
Default constructor sets all entries to 0.
Matrix3D (const Matrix3D &A)
Matrix3D (const double &value)
sets all entries of the matrix to value.
Matrix3D (const double *v)
sets matrix entries to values in array.
Matrix3D (const char *s)
for test purposes, matrices can be instantiated as
~Matrix3D ()
Matrix3D & operator= (const Matrix3D &A)
Matrix3D & operator= (const double &scalar)
Matrix3D & operator= (const char *s)
for test purposes, matrices can be assigned as follows
void zero ()
Sets all entries to zero (more efficient than assignement).
void set_column (int j, const Vector3D &c)
Sets column j (0, 1 or 2) to Vector3D c.
double column_length (int i) const
returns the column length – i is 0-based.
const Matrix3D operator* (const double &s) const
multiplies each entry by the scalar s
void operator+= (const Matrix3D &rhs)
void operator-= (const Matrix3D &rhs)
void operator*= (const double &s)
multiplies each entry by the scalar s
Matrix3D plus_transpose (const Matrix3D &B) const
void plus_transpose_equal (const Matrix3D &B)
Matrix3D & outer_product (const Vector3D &v1, const Vector3D &v2)
Computes .
void fill_lower_triangle ()
size_t num_rows () const
size_t num_cols () const
double * operator[] (unsigned i)
returns a pointer to a row.
const double * operator[] (unsigned i) const
returns a pointer to a row.
Matrix3D ()
Default constructor sets all entries to 0.
Matrix3D (const Matrix3D &A)
Matrix3D (const double &value)
sets all entries of the matrix to value.
Matrix3D (const double *v)
sets matrix entries to values in array.
Matrix3D (const char *s)
for test purposes, matrices can be instantiated as
~Matrix3D ()
Matrix3D & operator= (const Matrix3D &A)
Matrix3D & operator= (const double &scalar)
Matrix3D & operator= (const char *s)
for test purposes, matrices can be assigned as follows
void zero ()
Sets all entries to zero (more efficient than assignement).
void set_column (int j, const Vector3D &c)
Sets column j (0, 1 or 2) to Vector3D c.
double column_length (int i) const
returns the column length – i is 0-based.
const Matrix3D operator* (const double &s) const
void operator+= (const Matrix3D &rhs)
void operator-= (const Matrix3D &rhs)
void operator*= (const double &s)
Matrix3D plus_transpose (const Matrix3D &B) const
void plus_transpose_equal (const Matrix3D &B)
Matrix3D & outer_product (const Vector3D &v1, const Vector3D &v2)
void fill_lower_triangle ()
size_t num_rows () const
size_t num_cols () const
double * operator[] (unsigned i)
returns a pointer to a row.
const double * operator[] (unsigned i) const
returns a pointer to a row.
Protected Member Functions
void copy (const double *v)
void set (const double &val)
void set_values (const char *s)
void copy (const double *v)
void set (const double &val)
void set_values (const char *s)
Protected Attributes
double v_ [9]
Friends
bool operator== (const Matrix3D &lhs, const Matrix3D &rhs)
bool operator!= (const Matrix3D &lhs, const Matrix3D &rhs)
double Frobenius_2 (const Matrix3D &A)
Return the square of the Frobenius norm of A, i.e. sum (diag (A' * A))
Matrix3D transpose (const Matrix3D &A)
const Matrix3D operator+ (const Matrix3D &A, const Matrix3D &B)
const Matrix3D operator- (const Matrix3D &A, const Matrix3D &B)
const Matrix3D operator* (const Matrix3D &A, const Matrix3D &B)
const Matrix3D mult_element (const Matrix3D &A, const Matrix3D &B)
Multiplies entry by entry. This is NOT a matrix multiplication.
int matmult (Matrix3D &C, const Matrix3D &A, const Matrix3D &B)
const Vector3D operator* (const Matrix3D &A, const Vector3D &x)
Computes .
const Vector3D operator* (const Vector3D &x, const Matrix3D &A)
Computes .
const Matrix3D operator* (const double &s, const Matrix3D &A)
friend function to allow for commutatative property of scalar mulitplication.
void eqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqTransAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqaA (Matrix3D &B, const double a, const Matrix3D &A)
double det (const Matrix3D &A)
determinant of matrix A, det(A).
void inv (Matrix3D &B, const Matrix3D &A)
void timesInvA (Matrix3D &B, const Matrix3D &A)
void QR (Matrix3D &Q, Matrix3D &R, const Matrix3D &A)
bool operator== (const Matrix3D &lhs, const Matrix3D &rhs)
bool operator!= (const Matrix3D &lhs, const Matrix3D &rhs)
double Frobenius_2 (const Matrix3D &A)
Return the square of the Frobenius norm of A, i.e. sum (diag (A' * A))
Matrix3D transpose (const Matrix3D &A)
const Matrix3D operator+ (const Matrix3D &A, const Matrix3D &B)
const Matrix3D operator- (const Matrix3D &A, const Matrix3D &B)
const Matrix3D operator* (const Matrix3D &A, const Matrix3D &B)
const Matrix3D mult_element (const Matrix3D &A, const Matrix3D &B)
Multiplies entry by entry. This is NOT a matrix multiplication.
int matmult (Matrix3D &C, const Matrix3D &A, const Matrix3D &B)
const Vector3D operator* (const Matrix3D &A, const Vector3D &x)
Computes .
const Vector3D operator* (const Vector3D &x, const Matrix3D &A)
Computes .
const Matrix3D operator* (const double &s, const Matrix3D &A)
friend function to allow for commutatative property of scalar mulitplication.
void eqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqTransAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqaA (Matrix3D &B, const double a, const Matrix3D &A)
double det (const Matrix3D &A)
determinant of matrix A, det(A).
void inv (Matrix3D &B, const Matrix3D &A)
void timesInvA (Matrix3D &B, const Matrix3D &A)
void QR (Matrix3D &Q, Matrix3D &R, const Matrix3D &A)
Detailed Description
3*3 Matric class, row-oriented, 0-based [i][j] indexing.
Since the size of the object is fixed at compile time, the Matrix3D object is as fast as a double[9] array.
Definition at line 78 of file includeLinks/Matrix3D.hpp.
Constructor & Destructor Documentation
Matrix3D () inline
Default constructor sets all entries to 0.
Definition at line 110 of file includeLinks/Matrix3D.hpp.
References Matrix3D::zero().
     {
       zero();
     }
Matrix3D (const Matrix3D & A) inline
Definition at line 115 of file includeLinks/Matrix3D.hpp.
References Matrix3D::copy(), and Matrix3D::v_.
     {
       copy(A.v_);
     }
Matrix3D (const double & value) inline
sets all entries of the matrix to value.
Definition at line 121 of file includeLinks/Matrix3D.hpp.
References Matrix3D::set().
     {
       set(value);
     }
Matrix3D (const double * v) inline
sets matrix entries to values in array.
Parameters
v is an array of 9 doubles.
Definition at line 128 of file includeLinks/Matrix3D.hpp.
References Matrix3D::copy().
     {
       copy(v);
     }
Matrix3D (const char * s) inline
for test purposes, matrices can be instantiated as
Matrix3D A("3 2 1  4 5 6  9 8 7");
Definition at line 135 of file includeLinks/Matrix3D.hpp.
References Matrix3D::set_values().
     {
       set_values(s);
     }
~Matrix3D () inline
Definition at line 141 of file includeLinks/Matrix3D.hpp.
 { }
Matrix3D () inline
Default constructor sets all entries to 0.
Definition at line 110 of file src/Misc/Matrix3D.hpp.
References Matrix3D::zero().
     {
       zero();
     }
Matrix3D (const Matrix3D & A) inline
Definition at line 115 of file src/Misc/Matrix3D.hpp.
References Matrix3D::copy().
     {
       copy(A.v_);
     }
Matrix3D (const double & value) inline
sets all entries of the matrix to value.
Definition at line 121 of file src/Misc/Matrix3D.hpp.
References Matrix3D::set().
     {
       set(value);
     }
Matrix3D (const double * v) inline
sets matrix entries to values in array.
Parameters
v is an array of 9 doubles.
Definition at line 128 of file src/Misc/Matrix3D.hpp.
References Matrix3D::copy().
     {
       copy(v);
     }
Matrix3D (const char * s) inline
for test purposes, matrices can be instantiated as
Matrix3D A("3 2 1  4 5 6  9 8 7");
Definition at line 135 of file src/Misc/Matrix3D.hpp.
References Matrix3D::set_values().
     {
       set_values(s);
     }
~Matrix3D () inline
Definition at line 141 of file src/Misc/Matrix3D.hpp.
 { }
Member Function Documentation
double column_length (int i) const inline
returns the column length – i is 0-based.
Definition at line 183 of file includeLinks/Matrix3D.hpp.
References sqrt(), and Matrix3D::v_.
Referenced by TargetCalculator::compute_Delta_3D(), TargetCalculator::compute_Q_3D(), and TargetCalculator::compute_V_3D().
     { return sqrt( v_[0+i]*v_[0+i] + v_[3+i]*v_[3+i] + v_[6+i]*v_[6+i] ); }
double column_length (int i) const inline
returns the column length – i is 0-based.
Definition at line 183 of file src/Misc/Matrix3D.hpp.
References sqrt(), and Matrix3D::v_.
     { return sqrt( v_[0+i]*v_[0+i] + v_[3+i]*v_[3+i] + v_[6+i]*v_[6+i] ); }
void copy (const double * v) inline protected
Definition at line 84 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
Referenced by Matrix3D::Matrix3D(), and Matrix3D::operator=().
     { memcpy(v_, v, 9*sizeof(double)); }
void copy (const double * v) inline protected
Definition at line 84 of file src/Misc/Matrix3D.hpp.
References Matrix3D::v_.
     { memcpy(v_, v, 9*sizeof(double)); }
void fill_lower_triangle () inline
Definition at line 428 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
Referenced by Mesquite::h_fcn_2e(), Mesquite::h_fcn_2i(), Mesquite::h_fcn_3e(), Mesquite::h_fcn_3e_v3(), Mesquite::h_fcn_3i(), h_fcn_ridft2(), h_fcn_ridft3(), Mesquite::h_gdft_2(), Mesquite::h_gdft_2_v0(), Mesquite::h_gdft_2_v1(), Mesquite::h_gdft_2_v2(), Mesquite::h_gdft_3(), Mesquite::h_gdft_3_v0(), Mesquite::h_gdft_3_v1(), and Mesquite::h_gdft_3_v2().
   {
     v_[3] = v_[1];
     v_[6] = v_[2];
     v_[7] = v_[5];
   }
void fill_lower_triangle ()
size_t num_cols () const inline
Definition at line 231 of file includeLinks/Matrix3D.hpp.
 { return 3; }
size_t num_cols () const inline
Definition at line 231 of file src/Misc/Matrix3D.hpp.
 { return 3; }
size_t num_rows () const inline
Definition at line 230 of file src/Misc/Matrix3D.hpp.
 { return 3; }
size_t num_rows () const inline
Definition at line 230 of file includeLinks/Matrix3D.hpp.
 { return 3; }
const Matrix3D operator* (const double & s) const inline
multiplies each entry by the scalar s
Definition at line 453 of file includeLinks/Matrix3D.hpp.
References s, and Matrix3D::v_.
   {
     Matrix3D temp;
     temp[0][0]=v_[0] * s; temp[0][1]=v_[1] * s; temp[0][2]=v_[2] * s;
     temp[1][0]=v_[3] * s; temp[1][1]=v_[4] * s; temp[1][2]=v_[5] * s;
     temp[2][0]=v_[6] * s; temp[2][1]=v_[7] * s; temp[2][2]=v_[8] * s;
     return temp;
   }
const Matrix3D operator* (const double & s) const
void operator*= (const double & s)
void operator*= (const double & s) inline
multiplies each entry by the scalar s
Definition at line 362 of file includeLinks/Matrix3D.hpp.
References s, and Matrix3D::v_.
   {
       v_[0] *= s; v_[1] *= s; v_[2] *= s;
       v_[3] *= s; v_[4] *= s; v_[5] *= s;
       v_[6] *= s; v_[7] *= s; v_[8] *= s;
   }
void operator+= (const Matrix3D & rhs)
void operator+= (const Matrix3D & rhs) inline
Definition at line 347 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
   {
       v_[0] += rhs.v_[0]; v_[1] += rhs.v_[1]; v_[2] += rhs.v_[2];
       v_[3] += rhs.v_[3]; v_[4] += rhs.v_[4]; v_[5] += rhs.v_[5];
       v_[6] += rhs.v_[6]; v_[7] += rhs.v_[7]; v_[8] += rhs.v_[8];
   }
void operator-= (const Matrix3D & rhs)
void operator-= (const Matrix3D & rhs) inline
Definition at line 354 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
   {
       v_[0] -= rhs.v_[0]; v_[1] -= rhs.v_[1]; v_[2] -= rhs.v_[2];
       v_[3] -= rhs.v_[3]; v_[4] -= rhs.v_[4]; v_[5] -= rhs.v_[5];
       v_[6] -= rhs.v_[6]; v_[7] -= rhs.v_[7]; v_[8] -= rhs.v_[8];
   }
Matrix3D& operator= (const Matrix3D & A) inline
Definition at line 144 of file includeLinks/Matrix3D.hpp.
References Matrix3D::copy(), and Matrix3D::v_.
Referenced by TargetMatrix::operator=().
     {
       if (v_ == A.v_)
         return *this;
       copy(A.v_);
       return *this;
     }
Matrix3D& operator= (const Matrix3D & A) inline
Definition at line 144 of file src/Misc/Matrix3D.hpp.
References Matrix3D::copy(), and Matrix3D::v_.
     {
       if (v_ == A.v_)
         return *this;
       copy(A.v_);
       return *this;
     }
Matrix3D& operator= (const double & scalar) inline
Definition at line 152 of file includeLinks/Matrix3D.hpp.
References Matrix3D::set().
     {
       set(scalar);
       return *this;
     }
Matrix3D& operator= (const double & scalar) inline
Definition at line 152 of file src/Misc/Matrix3D.hpp.
References Matrix3D::set().
     {
       set(scalar);
       return *this;
     }
Matrix3D& operator= (const char * s) inline
for test purposes, matrices can be assigned as follows
A = "3 2 1  4 5 6  9 8 7";
Definition at line 160 of file src/Misc/Matrix3D.hpp.
References Matrix3D::set_values().
     {
       set_values(s);
       return *this;
     }
Matrix3D& operator= (const char * s) inline
for test purposes, matrices can be assigned as follows
A = "3 2 1  4 5 6  9 8 7";
Definition at line 160 of file includeLinks/Matrix3D.hpp.
References Matrix3D::set_values().
     {
       set_values(s);
       return *this;
     }
double* operator[] (unsigned i) inline
returns a pointer to a row.
Definition at line 234 of file includeLinks/Matrix3D.hpp.
References i, and Matrix3D::v_.
     {
       return v_ + 3*i;
     }
double* operator[] (unsigned i) inline
returns a pointer to a row.
Definition at line 234 of file src/Misc/Matrix3D.hpp.
References i, and Matrix3D::v_.
     {
       return v_ + 3*i;
     }
const double* operator[] (unsigned i) const inline
returns a pointer to a row.
Definition at line 240 of file includeLinks/Matrix3D.hpp.
References i, and Matrix3D::v_.
     {
       return v_ + 3*i;
     }
const double* operator[] (unsigned i) const inline
returns a pointer to a row.
Definition at line 240 of file src/Misc/Matrix3D.hpp.
References i, and Matrix3D::v_.
     {
       return v_ + 3*i;
     }
Matrix3D & outer_product (const Vector3D & v1, const Vector3D & v2) inline
Computes .
Definition at line 406 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_hessian().
   {
     // remember, matrix entries are v_[0] to v_[8].
     // diagonal
     v_[0] = v1[0]*v2[0];
     v_[4] = v1[1]*v2[1];
     v_[8] = v1[2]*v2[2];
     // upper triangular part
     v_[1] = v1[0]*v2[1];
     v_[2] = v1[0]*v2[2];
     v_[5] = v1[1]*v2[2];
     // lower triangular part
     v_[3] = v2[0]*v1[1];
     v_[6] = v2[0]*v1[2];
     v_[7] = v2[1]*v1[2];
     return *this;
   }
Matrix3D& outer_product (const Vector3D & v1, const Vector3D & v2)
Matrix3D plus_transpose (const Matrix3D & B) const
Matrix3D plus_transpose (const Matrix3D & B) const inline
Definition at line 370 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
   {
     Matrix3D tmp;
     tmp.v_[0] = v_[0] + B.v_[0];
     tmp.v_[1] = v_[1] + B.v_[3];
     tmp.v_[2] = v_[2] + B.v_[6];
     tmp.v_[3] = v_[3] + B.v_[1];
     tmp.v_[4] = v_[4] + B.v_[4];
     tmp.v_[5] = v_[5] + B.v_[7];
     tmp.v_[6] = v_[6] + B.v_[2];
     tmp.v_[7] = v_[7] + B.v_[5];
     tmp.v_[8] = v_[8] + B.v_[8];
     return tmp;
   }
void plus_transpose_equal (const Matrix3D & B) inline
Definition at line 390 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
Referenced by MsqHessian::accumulate_entries().
   {
     v_[0] += B.v_[0];
     v_[1] += B.v_[3];
     v_[2] += B.v_[6];
     v_[3] += B.v_[1];
     v_[4] += B.v_[4];
     v_[5] += B.v_[7];
     v_[6] += B.v_[2];
     v_[7] += B.v_[5];
     v_[8] += B.v_[8];
   }
void plus_transpose_equal (const Matrix3D & B)
void set (const double & val) inline protected
Definition at line 87 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
Referenced by Matrix3D::Matrix3D(), and Matrix3D::operator=().
     {
       v_[0]=val;  v_[1]=val;  v_[2]=val;
       v_[3]=val;  v_[4]=val;  v_[5]=val;
       v_[6]=val;  v_[7]=val;  v_[8]=val;
     }
void set (const double & val) inline protected
Definition at line 87 of file src/Misc/Matrix3D.hpp.
References Matrix3D::v_.
     {
       v_[0]=val;  v_[1]=val;  v_[2]=val;
       v_[3]=val;  v_[4]=val;  v_[5]=val;
       v_[6]=val;  v_[7]=val;  v_[8]=val;
     }
void set_column (int j, const Vector3D & c) inline
Sets column j (0, 1 or 2) to Vector3D c.
Definition at line 175 of file includeLinks/Matrix3D.hpp.
References j, and Matrix3D::v_.
Referenced by MsqMeshEntity::compute_corner_matrices(), and TargetCalculator::compute_V_3D().
     {
       v_[0+j]=c[0];
       v_[3+j]=c[1];
       v_[6+j]=c[2];
     }
void set_column (int j, const Vector3D & c) inline
Sets column j (0, 1 or 2) to Vector3D c.
Definition at line 175 of file src/Misc/Matrix3D.hpp.
References j, and Matrix3D::v_.
     {
       v_[0+j]=c[0];
       v_[3+j]=c[1];
       v_[6+j]=c[2];
     }
void set_values (const char * s) inline protected
Definition at line 94 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
Referenced by Matrix3D::Matrix3D(), and Matrix3D::operator=().
     {
 #ifdef MSQ_USE_OLD_IO_HEADERS
       ::istrstream ins(s);
 #else
       std::istringstream ins(s);
 #endif
       ins>>v_[0];  ins>>v_[1];  ins>>v_[2];
       ins>>v_[3];  ins>>v_[4];  ins>>v_[5];
       ins>>v_[6];  ins>>v_[7];  ins>>v_[8];
     }
void set_values (const char * s) inline protected
Definition at line 94 of file src/Misc/Matrix3D.hpp.
References Matrix3D::v_.
     {
 #ifdef MSQ_USE_OLD_IO_HEADERS
       ::istrstream ins(s);
 #else
       std::istringstream ins(s);
 #endif
       ins>>v_[0];  ins>>v_[1];  ins>>v_[2];
       ins>>v_[3];  ins>>v_[4];  ins>>v_[5];
       ins>>v_[6];  ins>>v_[7];  ins>>v_[8];
     }
void zero () inline
Sets all entries to zero (more efficient than assignement).
Definition at line 167 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
Referenced by update_py::burn_get_burning_rate1d(), burn_initialize(), cal_shdx(), setup_py::check_input_range(), RI_DFT::compute_element_analytical_hessian(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightMeanRatio::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), get_enhanced_map(), get_jacobien(), get_mixed_map(), implicit_v3d8_me_k(), m_rocburn_2d::initialize(), invert3x3(), Matrix3D::Matrix3D(), rflu_modpetscnewtonkrylov::rflu_petsc_createvectors(), shcalc(), shcalc_3d10(), m_rocburn_2d::update(), v3d10_ale(), v3d10_r_bar(), and MsqHessian::zero_out().
     {
       v_[0]=0.;  v_[1]=0.;  v_[2]=0.;
       v_[3]=0.;  v_[4]=0.;  v_[5]=0.;
       v_[6]=0.;  v_[7]=0.;  v_[8]=0.;
     }
void zero () inline
Sets all entries to zero (more efficient than assignement).
Definition at line 167 of file src/Misc/Matrix3D.hpp.
References Matrix3D::v_.
     {
       v_[0]=0.;  v_[1]=0.;  v_[2]=0.;
       v_[3]=0.;  v_[4]=0.;  v_[5]=0.;
       v_[6]=0.;  v_[7]=0.;  v_[8]=0.;
     }
Friends And Related Function Documentation
double det (const Matrix3D & A) friend
determinant of matrix A, det(A).
Definition at line 549 of file includeLinks/Matrix3D.hpp.
{
     return (  A.v_[0]*(A.v_[4]*A.v_[8]-A.v_[7]*A.v_[5])
             -A.v_[1]*(A.v_[3]*A.v_[8]-A.v_[6]*A.v_[5])
             +A.v_[2]*(A.v_[3]*A.v_[7]-A.v_[6]*A.v_[4]) );
   }
double det (const Matrix3D & A) friend
determinant of matrix A, det(A).
Definition at line 549 of file includeLinks/Matrix3D.hpp.
{
     return (  A.v_[0]*(A.v_[4]*A.v_[8]-A.v_[7]*A.v_[5])
             -A.v_[1]*(A.v_[3]*A.v_[8]-A.v_[6]*A.v_[5])
             +A.v_[2]*(A.v_[3]*A.v_[7]-A.v_[6]*A.v_[4]) );
   }
void eqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 522 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] = A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] = A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] = A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void eqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 522 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] = A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] = A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] = A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
double Frobenius_2 (const Matrix3D & A) friend
Return the square of the Frobenius norm of A, i.e. sum (diag (A' * A))
Definition at line 326 of file includeLinks/Matrix3D.hpp.
   {
     double fro=0.;
     for (int i=0; i<3; ++i) {
         fro += A[0][i]*A[0][i] + A[1][i]*A[1][i] + A[2][i]*A[2][i] ;
     }
     return fro;
   }
double Frobenius_2 (const Matrix3D & A) friend
Return the square of the Frobenius norm of A, i.e. sum (diag (A' * A))
Definition at line 326 of file includeLinks/Matrix3D.hpp.
   {
     double fro=0.;
     for (int i=0; i<3; ++i) {
         fro += A[0][i]*A[0][i] + A[1][i]*A[1][i] + A[2][i]*A[2][i] ;
     }
     return fro;
   }
void inv (Matrix3D & B, const Matrix3D & A) friend
Definition at line 555 of file includeLinks/Matrix3D.hpp.
{
     double inv_detA = 1 / (det(A));
     Ainv[0][0] = inv_detA*( A.v_[4]*A.v_[8]-A.v_[5]*A.v_[7] );
     Ainv[0][1] = inv_detA*( A.v_[2]*A.v_[7]-A.v_[8]*A.v_[1] );
     Ainv[0][2] = inv_detA*( A.v_[1]*A.v_[5]-A.v_[4]*A.v_[2] );
     Ainv[1][0] = inv_detA*( A.v_[5]*A.v_[6]-A.v_[8]*A.v_[3] );
     Ainv[1][1] = inv_detA*( A.v_[0]*A.v_[8]-A.v_[6]*A.v_[2] );
     Ainv[1][2] = inv_detA*( A.v_[2]*A.v_[3]-A.v_[5]*A.v_[0] );
     Ainv[2][0] = inv_detA*( A.v_[3]*A.v_[7]-A.v_[6]*A.v_[4] );
     Ainv[2][1] = inv_detA*( A.v_[1]*A.v_[6]-A.v_[7]*A.v_[0] );
     Ainv[2][2] = inv_detA*( A.v_[0]*A.v_[4]-A.v_[3]*A.v_[1] );
     return;
   }
void inv (Matrix3D & B, const Matrix3D & A) friend
Definition at line 555 of file includeLinks/Matrix3D.hpp.
{
     double inv_detA = 1 / (det(A));
     Ainv[0][0] = inv_detA*( A.v_[4]*A.v_[8]-A.v_[5]*A.v_[7] );
     Ainv[0][1] = inv_detA*( A.v_[2]*A.v_[7]-A.v_[8]*A.v_[1] );
     Ainv[0][2] = inv_detA*( A.v_[1]*A.v_[5]-A.v_[4]*A.v_[2] );
     Ainv[1][0] = inv_detA*( A.v_[5]*A.v_[6]-A.v_[8]*A.v_[3] );
     Ainv[1][1] = inv_detA*( A.v_[0]*A.v_[8]-A.v_[6]*A.v_[2] );
     Ainv[1][2] = inv_detA*( A.v_[2]*A.v_[3]-A.v_[5]*A.v_[0] );
     Ainv[2][0] = inv_detA*( A.v_[3]*A.v_[7]-A.v_[6]*A.v_[4] );
     Ainv[2][1] = inv_detA*( A.v_[1]*A.v_[6]-A.v_[7]*A.v_[0] );
     Ainv[2][2] = inv_detA*( A.v_[0]*A.v_[4]-A.v_[3]*A.v_[1] );
     return;
   }
int matmult (Matrix3D & C, const Matrix3D & A, const Matrix3D & B) friend
Definition at line 470 of file includeLinks/Matrix3D.hpp.
   {
     double sum;
     const double* row_i;
     const double* col_k;
     for (size_t i=0; i<3; ++i)
       for (size_t k=0; k<3; ++k)
         {
           row_i  = &(A[i][0]);
           col_k  = &(B[0][k]);
           sum = 0;
           for (size_t j=0; j<3; ++j)
             {
               sum  += *row_i * *col_k;
               row_i++;
               col_k += 3;
             }
           C[i][k] = sum;
         }
     return 0;
   }
int matmult (Matrix3D & C, const Matrix3D & A, const Matrix3D & B) friend
Definition at line 470 of file includeLinks/Matrix3D.hpp.
   {
     double sum;
     const double* row_i;
     const double* col_k;
     for (size_t i=0; i<3; ++i)
       for (size_t k=0; k<3; ++k)
         {
           row_i  = &(A[i][0]);
           col_k  = &(B[0][k]);
           sum = 0;
           for (size_t j=0; j<3; ++j)
             {
               sum  += *row_i * *col_k;
               row_i++;
               col_k += 3;
             }
           C[i][k] = sum;
         }
     return 0;
   }
const Matrix3D mult_element (const Matrix3D & A, const Matrix3D & B) friend
Multiplies entry by entry. This is NOT a matrix multiplication.
Definition at line 312 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D tmp;
     size_t i;
     for (i=0; i<3; ++i) {
       tmp[i][0] = A[i][0] * B[i][0];
       tmp[i][1] = A[i][1] * B[i][1];
       tmp[i][2] = A[i][2] * B[i][2];
     }
     return tmp;
   }
const Matrix3D mult_element (const Matrix3D & A, const Matrix3D & B) friend
Multiplies entry by entry. This is NOT a matrix multiplication.
Definition at line 312 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D tmp;
     size_t i;
     for (i=0; i<3; ++i) {
       tmp[i][0] = A[i][0] * B[i][0];
       tmp[i][1] = A[i][1] * B[i][1];
       tmp[i][2] = A[i][2] * B[i][2];
     }
     return tmp;
   }
bool operator!= (const Matrix3D & lhs, const Matrix3D & rhs) friend
Definition at line 278 of file includeLinks/Matrix3D.hpp.
   {
     return (memcmp(lhs.v_, rhs.v_, 9*sizeof(double)) != 0);
   }
bool operator!= (const Matrix3D & lhs, const Matrix3D & rhs) friend
Definition at line 278 of file includeLinks/Matrix3D.hpp.
   {
     return (memcmp(lhs.v_, rhs.v_, 9*sizeof(double)) != 0);
   }
const Matrix3D operator* (const Matrix3D & A, const Matrix3D & B) friend
Returns
A*B
Definition at line 436 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D tmp;
     double sum;
     for (size_t i=0; i<3; ++i)
       for (size_t k=0; k<3; ++k)
         {
           sum = 0;
           for (size_t j=0; j<3; j++)
             sum = sum +  A[i][j] * B[j][k];
           tmp[i][k] = sum;
         }
     return tmp;
   }
const Matrix3D operator* (const Matrix3D & A, const Matrix3D & B) friend
Returns
A*B
Definition at line 436 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D tmp;
     double sum;
     for (size_t i=0; i<3; ++i)
       for (size_t k=0; k<3; ++k)
         {
           sum = 0;
           for (size_t j=0; j<3; j++)
             sum = sum +  A[i][j] * B[j][k];
           tmp[i][k] = sum;
         }
     return tmp;
   }
const Vector3D operator* (const Matrix3D & A, const Vector3D & x) friend
Computes .
Definition at line 494 of file includeLinks/Matrix3D.hpp.
   {
     Vector3D tmp; // initializes to 0
     for (size_t i=0; i<3; ++i)
       {
         const double* rowi = A[i];
         tmp[i] = rowi[0]*x[0] + rowi[1]*x[1] + rowi[2]*x[2];
       }
     return tmp;
   }
const Vector3D operator* (const Matrix3D & A, const Vector3D & x) friend
Computes .
Definition at line 494 of file includeLinks/Matrix3D.hpp.
   {
     Vector3D tmp; // initializes to 0
     for (size_t i=0; i<3; ++i)
       {
         const double* rowi = A[i];
         tmp[i] = rowi[0]*x[0] + rowi[1]*x[1] + rowi[2]*x[2];
       }
     return tmp;
   }
const Vector3D operator* (const Vector3D & x, const Matrix3D & A) friend
Computes .
This function implicitly considers the transpose of vector x times the matrix A and it is implicit that the returned vector must be transposed.
Definition at line 510 of file includeLinks/Matrix3D.hpp.
   {
     Vector3D res(0., 0., 0.);
     for (size_t i=0; i<3; ++i)
       {
         const double* rowi = A[i];
         for (size_t j=0; j<3; ++j)
           res[j] += rowi[j] * x[i];
       }
     return res;
   }
const Vector3D operator* (const Vector3D & x, const Matrix3D & A) friend
Computes .
This function implicitly considers the transpose of vector x times the matrix A and it is implicit that the returned vector must be transposed.
Definition at line 510 of file includeLinks/Matrix3D.hpp.
   {
     Vector3D res(0., 0., 0.);
     for (size_t i=0; i<3; ++i)
       {
         const double* rowi = A[i];
         for (size_t j=0; j<3; ++j)
           res[j] += rowi[j] * x[i];
       }
     return res;
   }
const Matrix3D operator* (const double & s, const Matrix3D & A) friend
friend function to allow for commutatative property of scalar mulitplication.
Definition at line 463 of file includeLinks/Matrix3D.hpp.
    {
      return (A.operator*(s));
    }
const Matrix3D operator* (const double & s, const Matrix3D & A) friend
friend function to allow for commutatative property of scalar mulitplication.
Definition at line 463 of file includeLinks/Matrix3D.hpp.
    {
      return (A.operator*(s));
    }
const Matrix3D operator+ (const Matrix3D & A, const Matrix3D & B) friend
Returns
A+B
Definition at line 284 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D tmp;
     size_t i;
     for (i=0; i<3; ++i) {
       tmp[i][0] = A[i][0] + B[i][0];
       tmp[i][1] = A[i][1] + B[i][1];
       tmp[i][2] = A[i][2] + B[i][2];
     }
     return tmp;
   }
const Matrix3D operator+ (const Matrix3D & A, const Matrix3D & B) friend
Returns
A+B
Definition at line 284 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D tmp;
     size_t i;
     for (i=0; i<3; ++i) {
       tmp[i][0] = A[i][0] + B[i][0];
       tmp[i][1] = A[i][1] + B[i][1];
       tmp[i][2] = A[i][2] + B[i][2];
     }
     return tmp;
   }
const Matrix3D operator- (const Matrix3D & A, const Matrix3D & B) friend
Returns
A-B
Definition at line 298 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D tmp;
     size_t i;
     for (i=0; i<3; ++i) {
       tmp[i][0] = A[i][0] - B[i][0];
       tmp[i][1] = A[i][1] - B[i][1];
       tmp[i][2] = A[i][2] - B[i][2];
     }
     return tmp;
   }
const Matrix3D operator- (const Matrix3D & A, const Matrix3D & B) friend
Returns
A-B
Definition at line 298 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D tmp;
     size_t i;
     for (i=0; i<3; ++i) {
       tmp[i][0] = A[i][0] - B[i][0];
       tmp[i][1] = A[i][1] - B[i][1];
       tmp[i][2] = A[i][2] - B[i][2];
     }
     return tmp;
   }
bool operator== (const Matrix3D & lhs, const Matrix3D & rhs) friend
Definition at line 274 of file includeLinks/Matrix3D.hpp.
   {
     return (memcmp(lhs.v_, rhs.v_, 9*sizeof(double)) == 0);
   }
bool operator== (const Matrix3D & lhs, const Matrix3D & rhs) friend
Definition at line 274 of file includeLinks/Matrix3D.hpp.
   {
     return (memcmp(lhs.v_, rhs.v_, 9*sizeof(double)) == 0);
   }
void plusEqaA (Matrix3D & B, const double a, const Matrix3D & A) friend
Definition at line 543 of file includeLinks/Matrix3D.hpp.
{
     B.v_[0] += a*A.v_[0]; B.v_[1] += a*A.v_[1]; B.v_[2] += a*A.v_[2];
     B.v_[3] += a*A.v_[3]; B.v_[4] += a*A.v_[4]; B.v_[5] += a*A.v_[5];
     B.v_[6] += a*A.v_[6]; B.v_[7] += a*A.v_[7]; B.v_[8] += a*A.v_[8];
   }
void plusEqaA (Matrix3D & B, const double a, const Matrix3D & A) friend
Definition at line 543 of file includeLinks/Matrix3D.hpp.
{
     B.v_[0] += a*A.v_[0]; B.v_[1] += a*A.v_[1]; B.v_[2] += a*A.v_[2];
     B.v_[3] += a*A.v_[3]; B.v_[4] += a*A.v_[4]; B.v_[5] += a*A.v_[5];
     B.v_[6] += a*A.v_[6]; B.v_[7] += a*A.v_[7]; B.v_[8] += a*A.v_[8];
   }
void plusEqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 529 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] += A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] += A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] += A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void plusEqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 529 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] += A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] += A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] += A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void plusEqTransAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 536 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] += A.v_[0]*x.mCoords[0] + A.v_[3]*x.mCoords[1] + A.v_[6]*x.mCoords[2];
      v.mCoords[1] += A.v_[1]*x.mCoords[0] + A.v_[4]*x.mCoords[1] + A.v_[7]*x.mCoords[2];
      v.mCoords[2] += A.v_[2]*x.mCoords[0] + A.v_[5]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void plusEqTransAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 536 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] += A.v_[0]*x.mCoords[0] + A.v_[3]*x.mCoords[1] + A.v_[6]*x.mCoords[2];
      v.mCoords[1] += A.v_[1]*x.mCoords[0] + A.v_[4]*x.mCoords[1] + A.v_[7]*x.mCoords[2];
      v.mCoords[2] += A.v_[2]*x.mCoords[0] + A.v_[5]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void QR (Matrix3D & Q, Matrix3D & R, const Matrix3D & A) friend
Definition at line 593 of file includeLinks/Matrix3D.hpp.
{
     // Compute the QR factorization of A.  This code uses the
     // Modified Gram-Schmidt method for computing the factorization.
     // The Householder version is more stable, but costs twice as many
     // floating point operations.
     Q = A;
     R[0][0] = sqrt(Q[0][0]*Q[0][0] + Q[1][0]*Q[1][0] + Q[2][0]*Q[2][0]);
     R[1][0] = 0.0L;
     R[2][0] = 0.0L;
     Q[0][0] /= R[0][0];
     Q[1][0] /= R[0][0];
     Q[2][0] /= R[0][0];
     R[0][1]  = Q[0][0]*Q[0][1] + Q[1][0]*Q[1][1] + Q[2][0]*Q[2][1];
     Q[0][1] -= Q[0][0]*R[0][1];
     Q[1][1] -= Q[1][0]*R[0][1];
     Q[2][1] -= Q[2][0]*R[0][1];
     R[0][2]  = Q[0][0]*Q[0][2] + Q[1][0]*Q[1][2] + Q[2][0]*Q[2][2];
     Q[0][2] -= Q[0][0]*R[0][2];
     Q[1][2] -= Q[1][0]*R[0][2];
     Q[2][2] -= Q[2][0]*R[0][2];
     R[1][1] = sqrt(Q[0][1]*Q[0][1] + Q[1][1]*Q[1][1] + Q[2][1]*Q[2][1]);
     R[2][1] = 0.0L;
     Q[0][1] /= R[1][1];
     Q[1][1] /= R[1][1];
     Q[2][1] /= R[1][1];
     R[1][2]  = Q[0][1]*Q[0][2] + Q[1][1]*Q[1][2] + Q[2][1]*Q[2][2];
     Q[0][2] -= Q[0][1]*R[1][2];
     Q[1][2] -= Q[1][1]*R[1][2];
     Q[2][2] -= Q[2][1]*R[1][2];
     R[2][2] = sqrt(Q[0][2]*Q[0][2] + Q[1][2]*Q[1][2] + Q[2][2]*Q[2][2]);
     Q[0][2] /= R[2][2];
     Q[1][2] /= R[2][2];
     Q[2][2] /= R[2][2];
     return;
   }
void QR (Matrix3D & Q, Matrix3D & R, const Matrix3D & A) friend
Definition at line 593 of file includeLinks/Matrix3D.hpp.
{
     // Compute the QR factorization of A.  This code uses the
     // Modified Gram-Schmidt method for computing the factorization.
     // The Householder version is more stable, but costs twice as many
     // floating point operations.
     Q = A;
     R[0][0] = sqrt(Q[0][0]*Q[0][0] + Q[1][0]*Q[1][0] + Q[2][0]*Q[2][0]);
     R[1][0] = 0.0L;
     R[2][0] = 0.0L;
     Q[0][0] /= R[0][0];
     Q[1][0] /= R[0][0];
     Q[2][0] /= R[0][0];
     R[0][1]  = Q[0][0]*Q[0][1] + Q[1][0]*Q[1][1] + Q[2][0]*Q[2][1];
     Q[0][1] -= Q[0][0]*R[0][1];
     Q[1][1] -= Q[1][0]*R[0][1];
     Q[2][1] -= Q[2][0]*R[0][1];
     R[0][2]  = Q[0][0]*Q[0][2] + Q[1][0]*Q[1][2] + Q[2][0]*Q[2][2];
     Q[0][2] -= Q[0][0]*R[0][2];
     Q[1][2] -= Q[1][0]*R[0][2];
     Q[2][2] -= Q[2][0]*R[0][2];
     R[1][1] = sqrt(Q[0][1]*Q[0][1] + Q[1][1]*Q[1][1] + Q[2][1]*Q[2][1]);
     R[2][1] = 0.0L;
     Q[0][1] /= R[1][1];
     Q[1][1] /= R[1][1];
     Q[2][1] /= R[1][1];
     R[1][2]  = Q[0][1]*Q[0][2] + Q[1][1]*Q[1][2] + Q[2][1]*Q[2][2];
     Q[0][2] -= Q[0][1]*R[1][2];
     Q[1][2] -= Q[1][1]*R[1][2];
     Q[2][2] -= Q[2][1]*R[1][2];
     R[2][2] = sqrt(Q[0][2]*Q[0][2] + Q[1][2]*Q[1][2] + Q[2][2]*Q[2][2]);
     Q[0][2] /= R[2][2];
     Q[1][2] /= R[2][2];
     Q[2][2] /= R[2][2];
     return;
   }
void timesInvA (Matrix3D & B, const Matrix3D & A) friend
Definition at line 572 of file includeLinks/Matrix3D.hpp.
{
     Matrix3D Ainv;
     double inv_detA = 1 / ( det(A) );
     Ainv[0][0] = inv_detA*( A.v_[4]*A.v_[8]-A.v_[5]*A.v_[7] );
     Ainv[0][1] = inv_detA*( A.v_[2]*A.v_[7]-A.v_[8]*A.v_[1] );
     Ainv[0][2] = inv_detA*( A.v_[1]*A.v_[5]-A.v_[4]*A.v_[2] );
     Ainv[1][0] = inv_detA*( A.v_[5]*A.v_[6]-A.v_[8]*A.v_[3] );
     Ainv[1][1] = inv_detA*( A.v_[0]*A.v_[8]-A.v_[6]*A.v_[2] );
     Ainv[1][2] = inv_detA*( A.v_[2]*A.v_[3]-A.v_[5]*A.v_[0] );
     Ainv[2][0] = inv_detA*( A.v_[3]*A.v_[7]-A.v_[6]*A.v_[4] );
     Ainv[2][1] = inv_detA*( A.v_[1]*A.v_[6]-A.v_[7]*A.v_[0] );
     Ainv[2][2] = inv_detA*( A.v_[0]*A.v_[4]-A.v_[3]*A.v_[1] );
     B = B*Ainv;
   }
void timesInvA (Matrix3D & B, const Matrix3D & A) friend
Definition at line 572 of file includeLinks/Matrix3D.hpp.
{
     Matrix3D Ainv;
     double inv_detA = 1 / ( det(A) );
     Ainv[0][0] = inv_detA*( A.v_[4]*A.v_[8]-A.v_[5]*A.v_[7] );
     Ainv[0][1] = inv_detA*( A.v_[2]*A.v_[7]-A.v_[8]*A.v_[1] );
     Ainv[0][2] = inv_detA*( A.v_[1]*A.v_[5]-A.v_[4]*A.v_[2] );
     Ainv[1][0] = inv_detA*( A.v_[5]*A.v_[6]-A.v_[8]*A.v_[3] );
     Ainv[1][1] = inv_detA*( A.v_[0]*A.v_[8]-A.v_[6]*A.v_[2] );
     Ainv[1][2] = inv_detA*( A.v_[2]*A.v_[3]-A.v_[5]*A.v_[0] );
     Ainv[2][0] = inv_detA*( A.v_[3]*A.v_[7]-A.v_[6]*A.v_[4] );
     Ainv[2][1] = inv_detA*( A.v_[1]*A.v_[6]-A.v_[7]*A.v_[0] );
     Ainv[2][2] = inv_detA*( A.v_[0]*A.v_[4]-A.v_[3]*A.v_[1] );
     B = B*Ainv;
   }
Matrix3D transpose (const Matrix3D & A) friend
Definition at line 335 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D S;
     size_t i;
     for (i=0; i<3; ++i) {
         S[size_t(0)][i] = A[i][0];
         S[size_t(1)][i] = A[i][1];
         S[size_t(2)][i] = A[i][2];
     }
     return S;
   }
Matrix3D transpose (const Matrix3D & A) friend
Definition at line 335 of file includeLinks/Matrix3D.hpp.
   {
     Matrix3D S;
     size_t i;
     for (i=0; i<3; ++i) {
         S[size_t(0)][i] = A[i][0];
         S[size_t(1)][i] = A[i][1];
         S[size_t(2)][i] = A[i][2];
     }
     return S;
   }
Member Data Documentation
double v_ protected
Definition at line 81 of file includeLinks/Matrix3D.hpp.
Referenced by Matrix3D::column_length(), Matrix3D::copy(), Mesquite::det(), Mesquite::eqAx(), Matrix3D::fill_lower_triangle(), Mesquite::inv(), Matrix3D::Matrix3D(), Mesquite::operator!=(), Matrix3D::operator*(), Matrix3D::operator*=(), Matrix3D::operator+=(), Matrix3D::operator-=(), Matrix3D::operator=(), Mesquite::operator==(), Matrix3D::operator[](), Matrix3D::outer_product(), Matrix3D::plus_transpose(), Matrix3D::plus_transpose_equal(), Mesquite::plusEqaA(), Mesquite::plusEqAx(), Mesquite::plusEqTransAx(), Matrix3D::set(), Matrix3D::set_column(), Matrix3D::set_values(), Mesquite::timesInvA(), and Matrix3D::zero().
The documentation for this class was generated from the following file:
includeLinks/Matrix3D.hpp