Rocstar: rflu_modreadwritegrid Module Reference
rflu_modreadwritegrid Module Reference
Public Member Functions
subroutine rflu_readgridbinary (pRegion)
subroutine, public rflu_readgridwrapper (pRegion)
subroutine rflu_writegridbinary (pRegion)
subroutine, public rflu_writegridwrapper (pRegion)
Private Member Functions
subroutine rflu_readgridascii (pRegion)
subroutine rflu_writegridascii (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadWriteGrid.F90,v $ $Revision: 1.10 $'
Detailed Description
Definition at line 39 of file RFLU_ModReadWriteGrid.F90.
Member Function/Subroutine Documentation
subroutine rflu_readgridascii (type(t_region), pointer pRegion) private
Definition at line 94 of file RFLU_ModReadWriteGrid.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, i, j, k, Color::r(), moderror::registerfunction(), and Attribute::status().
Referenced by rflu_readgridwrapper().
subroutine rflu_readgridbinary (type(t_region), pointer pRegion)
Definition at line 591 of file RFLU_ModReadWriteGrid.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, i, j, k, Color::r(), moderror::registerfunction(), and Attribute::status().
Referenced by rflu_readgridwrapper().
subroutine, public rflu_readgridwrapper (type(t_region), pointer pRegion)
Definition at line 1082 of file RFLU_ModReadWriteGrid.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modrocstario::rflu_genx_decidereadfile(), rflu_modrocstario::rflu_genx_getgrid(), rflu_readgridascii(), and rflu_readgridbinary().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflucells(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine rflu_writegridascii (type(t_region), pointer pRegion) private
Definition at line 1164 of file RFLU_ModReadWriteGrid.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, i, j, k, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_writegridwrapper().
subroutine rflu_writegridbinary (type(t_region), pointer pRegion)
Definition at line 1433 of file RFLU_ModReadWriteGrid.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, i, j, k, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_writegridwrapper().
subroutine, public rflu_writegridwrapper (type(t_region), pointer pRegion)
Definition at line 1700 of file RFLU_ModReadWriteGrid.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modrocstario::rflu_genx_decidewritefile(), rflu_modrocstario::rflu_genx_putgrid(), rflu_writegridascii(), and rflu_writegridbinary().
Referenced by rflu_endflowsolver(), rflu_mergepostprocessregions(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_timestepping(), rfluconv(), and rflupart().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadWriteGrid.F90,v $ $Revision: 1.10 $' private
Definition at line 60 of file RFLU_ModReadWriteGrid.F90.
The documentation for this module was generated from the following file:
RFLU_ModReadWriteGrid.F90