Rocstar: CFacet Class Reference
CFacet Class Reference
#include <GeoPrimitives.H>
Public Member Functions
CFacet ()
CFacet (const CPoint &P1, const CPoint &P2, const CPoint &P3)
CFacet (const CPoint &P1, const CPoint &P2, const CPoint &P3, const CPoint &P4)
CFacet (const std::vector< CPoint > &v)
CFacet (const CFacet &face)
CVector normal () const
CPoint centroid () const
CFacet & operator= (const CFacet &face)
bool operator== (const CFacet &face) const
bool contains_point (const CPoint &P)
Detailed Description
Definition at line 1520 of file GeoPrimitives.H.
Constructor & Destructor Documentation
CFacet () inline
Definition at line 1523 of file GeoPrimitives.H.
 {};
CFacet (const CPoint & P1, const CPoint & P2, const CPoint & P3) inline
Definition at line 1524 of file GeoPrimitives.H.
     {
       this->resize(3);
       (*this)[0] = P1;
       (*this)[1] = P2;
       (*this)[2] = P3;
     };
CFacet (const CPoint & P1, const CPoint & P2, const CPoint & P3, const CPoint & P4) inline
Definition at line 1531 of file GeoPrimitives.H.
     {
       this->resize(4);
       (*this)[0] = P1;
       (*this)[1] = P2;
       (*this)[2] = P3;
       (*this)[3] = P4;
     };
CFacet (const std::vector< CPoint > & v) inline
Definition at line 1540 of file GeoPrimitives.H.
References pi.
     {
       std::vector<CPoint>::const_iterator pi = v.begin();
       while(pi != v.end())
         this->push_back(*pi++);
     };
CFacet (const CFacet & face) inline
Definition at line 1546 of file GeoPrimitives.H.
     {
       std::vector<CPoint>::const_iterator fi = face.begin();
       while(fi != face.end())
         this->push_back(*fi++);
     };
Member Function Documentation
CPoint centroid () const inline
Definition at line 1558 of file GeoPrimitives.H.
References GeoPrim::Centroid().
     {
       return(Centroid(*this));
     };
bool contains_point (const CPoint & P) inline
Definition at line 1580 of file GeoPrimitives.H.
References cimg_library::acos(), angle(), CPlane::contains_point(), GeoPrim::PI, GeoPrim::TOL, and v.
     {
       CPlane plane((*this)[0],(*this)[1],(*this)[2]);
       if(!(plane.contains_point(P)))
         return false;
       std::vector<CPoint>::const_iterator fi = this->begin();
       CVector v1(P,*fi);
       CVector vp(v1);
       fi++;
       double angle = 0.0;
       while(fi != this->end()){
         CVector v(P,(*fi));
         angle += acos(v*vp);
         vp = v;
         fi++;
       }
       angle += acos(vp*v1);
       return((fabs(angle) - 2*PI) <= TOL);
     };
CVector normal () const inline
Definition at line 1552 of file GeoPrimitives.H.
     {
       CVector v1((*this)[0],(*this)[1]);
       CVector v2((*this)[0],(*this)[2]);
       return(.5*(v1%v2));
     };
CFacet& operator= (const CFacet & face) inline
Definition at line 1562 of file GeoPrimitives.H.
     {
       this->clear();
       std::vector<CPoint>::const_iterator fi = face.begin();
       while(fi != face.end())
         this->push_back(*fi++);
       return(*this);
     };
bool operator== (const CFacet & face) const inline
Definition at line 1570 of file GeoPrimitives.H.
     {
       std::vector<CPoint>::const_iterator li = this->begin();
       std::vector<CPoint>::const_iterator fi = face.begin();
       if(this->size() != face.size()) return false;
       while(li != this->end())
         if(!(*li++ == *fi++))
           return(false);
       return(true);
     };
The documentation for this class was generated from the following file:
GeoPrimitives.H