Rocstar: FluidAlone Class Reference
FluidAlone Class Reference
#include <builtin_couplings.h>
Public Member Functions
FluidAlone (const char *, MPI_Comm com, Control_parameters *p, const RocmanControl_parameters *mp)
Public Member Functions inherited from Coupling
Coupling (const char *coupl_name, const char *name, Control_parameters *p, const RocmanControl_parameters *mp)
Constructor. Derived class will add actions for the coupling scheme.
Coupling (const char *coupl_name, const char *fluidname, const char *solidname, Control_parameters *p, const RocmanControl_parameters *mp)
Coupling (const char *coupl_name, const char *fluidname, const char *solidname, const char *burnname, Control_parameters *p, const RocmanControl_parameters *mp)
virtual ~Coupling ()
Destructor.
const char * name ()
Agent * add_agent (Agent *)
Add new agent.
void schedule ()
Schedule the top-level actions of the coupling scheme and the actions of the agents.
void init (double t, double dt, int reinit=0)
Invoke initialization of the actions in the scheduler and the agents.
void initialize (int reinit=0)
void finalize ()
Invoke finalization of the actions in the scheduler and the agents.
double run (double t, double dt, int iPredCorr, double zoom)
Invoke the scheduler.
void run_initactions (double t, double dt)
void input (double t)
Invoke input functions of the agents.
int get_ipc () const
int get_max_ipc () const
int initial_start () const
int in_restart () const
int initial_remeshed () const
true if in initialization step and remeshed is true
int new_start (double t) const
void init_convergence (int iPredCorr)
int check_convergence ()
virtual void update_integrals (double currentTime)
virtual void update_distances (double currentTime)
void output_restart_files (double t)
void output_visualization_files (double t)
const Control_parameters * get_control_param ()
const RocmanControl_parameters * get_rocmancontrol_param ()
void read_restart_info ()
void write_restart_info (double CurrentTime, int iStep)
void restart_at_time (double t, int step)
virtual void reload_rocface (const RocmanControl_parameters *param)
void print (const char *fname)
void Interrupt (int *, const char *)
int ProcessInterrupt ()
Protected Attributes
double flm_temp
Protected Attributes inherited from Coupling
std::string coupling_name
vector< std::string > modules
AgentList agents
UserScheduler scheduler
UserScheduler init_scheduler
int comm_rank
int init_started
int restarting
int init_remeshed
int iPredCorr
int maxPredCorr
Control_parameters * param
const RocmanControl_parameters * rocmanparam
std::string restartInfo
int overwrite_integ
std::string integFname
int overwrite_dist
std::string distFname
Additional Inherited Members
Protected Member Functions inherited from Coupling
void callMethod (Scheduler_voidfn1_t fn, double t)
std::string normalize_modname (const char *mod)
Detailed Description
Definition at line 30 of file builtin_couplings.h.
Constructor & Destructor Documentation
FluidAlone (const char * module, MPI_Comm com, Control_parameters * p, const RocmanControl_parameters * mp)
Definition at line 69 of file builtin_couplings.C.
References UserScheduler::add_action(), Coupling::add_agent(), declare_fluid_actions(), Agent::get_main_action(), Coupling::maxPredCorr, and Coupling::scheduler.
                                                                                                                   : Coupling("FluidAloneNoBurn", module, p, mp)
 {
 //  p->zoomFactor = 1;    // ignore zoom factor
   maxPredCorr = 1;
   // Create agents
   FluidAgent *fluid_agent = new FluidAgent( this, module, module, com);
   add_agent( fluid_agent);
   // Create and register actions
   scheduler.add_action( fluid_agent->get_main_action());
   // Declare the actions for fluid-agent
   declare_fluid_actions( fluid_agent);
 }
Member Data Documentation
double flm_temp protected
Definition at line 35 of file builtin_couplings.h.
The documentation for this class was generated from the following files:
builtin_couplings.h
builtin_couplings.C