Rocstar: rflu_modpatchcoeffs Module Reference
rflu_modpatchcoeffs Module Reference
Public Member Functions
subroutine, public rflu_createpatchcoeffs (pRegion)
subroutine, public rflu_destroypatchcoeffs (pRegion)
subroutine, public rflu_readpatchcoeffswrapper (pRegion)
subroutine, public rflu_writepatchcoeffswrapper (pRegion)
Private Member Functions
subroutine, private rflu_closepatchcoeffs (pRegion)
subroutine, private rflu_initpatchcoeffs (pRegion)
subroutine, private rflu_nullifypatchcoeffs (pRegion)
subroutine, private rflu_openpatchcoeffsascii (pRegion, fileStatus, fileExists)
subroutine, private rflu_openpatchcoeffsbinary (pRegion, fileStatus, fileExists)
subroutine, private rflu_readpatchcoeffsascii (pRegion)
subroutine, private rflu_readpatchcoeffsbinary (pRegion)
subroutine, private rflu_writepatchcoeffsascii (pRegion)
subroutine, private rflu_writepatchcoeffsbinary (pRegion)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModPatchCoeffs.F90,v $ $Revision: 1.6 $'
Detailed Description
Definition at line 39 of file RFLU_ModPatchCoeffs.F90.
Member Function/Subroutine Documentation
subroutine, private rflu_closepatchcoeffs (type(t_region), pointer pRegion) private
Definition at line 114 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_readpatchcoeffswrapper(), and rflu_writepatchcoeffswrapper().
subroutine, public rflu_createpatchcoeffs (type(t_region), pointer pRegion)
Definition at line 194 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_initpatchcoeffs().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().
subroutine, public rflu_destroypatchcoeffs (type(t_region), pointer pRegion)
Definition at line 303 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifypatchcoeffs().
Referenced by rflu_endflowsolver(), rflu_mergepostprocessregions(), and rflu_postprocessregionscommon2().
subroutine, private rflu_initpatchcoeffs (type(t_region), pointer pRegion) private
Definition at line 408 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createpatchcoeffs().
subroutine, private rflu_nullifypatchcoeffs (type(t_region), pointer pRegion) private
Definition at line 491 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_destroypatchcoeffs().
subroutine, private rflu_openpatchcoeffsascii (type(t_region), pointer pRegion, integer, intent(in) fileStatus, logical, intent(out), optional fileExists) private
Definition at line 572 of file RFLU_ModPatchCoeffs.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_readpatchcoeffswrapper(), and rflu_writepatchcoeffswrapper().
subroutine, private rflu_openpatchcoeffsbinary (type(t_region), pointer pRegion, integer, intent(in) fileStatus, logical, intent(out), optional fileExists) private
Definition at line 708 of file RFLU_ModPatchCoeffs.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_readpatchcoeffswrapper(), and rflu_writepatchcoeffswrapper().
subroutine, private rflu_readpatchcoeffsascii (type(t_region), pointer pRegion) private
Definition at line 840 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_readpatchcoeffswrapper().
subroutine, private rflu_readpatchcoeffsbinary (type(t_region), pointer pRegion) private
Definition at line 1032 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_readpatchcoeffswrapper().
subroutine, public rflu_readpatchcoeffswrapper (type(t_region), pointer pRegion)
Definition at line 1221 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_closepatchcoeffs(), rflu_openpatchcoeffsascii(), rflu_openpatchcoeffsbinary(), rflu_readpatchcoeffsascii(), and rflu_readpatchcoeffsbinary().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().
subroutine, private rflu_writepatchcoeffsascii (type(t_region), pointer pRegion) private
Definition at line 1315 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_writepatchcoeffswrapper().
subroutine, private rflu_writepatchcoeffsbinary (type(t_region), pointer pRegion) private
Definition at line 1478 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_writepatchcoeffswrapper().
subroutine, public rflu_writepatchcoeffswrapper (type(t_region), pointer pRegion)
Definition at line 1641 of file RFLU_ModPatchCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_closepatchcoeffs(), rflu_openpatchcoeffsascii(), rflu_openpatchcoeffsbinary(), rflu_writepatchcoeffsascii(), and rflu_writepatchcoeffsbinary().
Referenced by rflu_endflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModPatchCoeffs.F90,v $ $Revision: 1.6 $' private
Definition at line 63 of file RFLU_ModPatchCoeffs.F90.
The documentation for this module was generated from the following file:
RFLU_ModPatchCoeffs.F90