Rocstar: QualityImprover Class Reference
QualityImprover Class Reference abstract
Base class for all quality improvers. Mote that the PatchData settings are inherited from the PathDataUser class.
#include <QualityImprover.hpp>
Public Member Functions
virtual ~QualityImprover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)=0
This is the "run" function of PatchDataUser. It can do anything really.
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
virtual ~QualityImprover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)=0
This is the "run" function of PatchDataUser. It can do anything really.
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Protected Member Functions
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Private Attributes
MeshSet * mMeshSet
msq_std::string qualityImproverName
int patchDepth
TerminationCriterion * innerTerminationCriterion
TerminationCriterion * outerTerminationCriterion
TerminationCriterion defaultOuterCriterion
TerminationCriterion defaultInnerCriterion
Friends
class MeshSet
Additional Inherited Members
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Detailed Description
Base class for all quality improvers. Mote that the PatchData settings are inherited from the PathDataUser class.
Definition at line 57 of file includeLinks/QualityImprover.hpp.
Constructor & Destructor Documentation
virtual ~QualityImprover () inline virtual
Definition at line 64 of file includeLinks/QualityImprover.hpp.
 { };
QualityImprover () inline protected
The default constructor initialises a few member variables to default values. This can be reused by concrete class constructor.
Definition at line 96 of file includeLinks/QualityImprover.hpp.
References TerminationCriterion::add_criterion_type_with_int(), QualityImprover::defaultInnerCriterion, QualityImprover::defaultOuterCriterion, QualityImprover::innerTerminationCriterion, TerminationCriterion::NUMBER_OF_ITERATES, and QualityImprover::outerTerminationCriterion.
                       : mMeshSet(0), qualityImproverName("noname")
       {
           //Temporary solution to not having an err object
         MsqError temp_err;
         defaultOuterCriterion.add_criterion_type_with_int(TerminationCriterion::NUMBER_OF_ITERATES,1,temp_err);
         outerTerminationCriterion = & defaultOuterCriterion;
         innerTerminationCriterion = & defaultInnerCriterion;
       }
virtual ~QualityImprover () inline virtual
Definition at line 64 of file src/QualityImprover/QualityImprover.hpp.
 { };
QualityImprover () inline protected
The default constructor initialises a few member variables to default values. This can be reused by concrete class constructor.
Definition at line 96 of file src/QualityImprover/QualityImprover.hpp.
References TerminationCriterion::add_criterion_type_with_int(), QualityImprover::defaultInnerCriterion, QualityImprover::defaultOuterCriterion, QualityImprover::innerTerminationCriterion, TerminationCriterion::NUMBER_OF_ITERATES, and QualityImprover::outerTerminationCriterion.
                       : mMeshSet(0), qualityImproverName("noname")
       {
           //Temporary solution to not having an err object
         MsqError temp_err;
         defaultOuterCriterion.add_criterion_type_with_int(TerminationCriterion::NUMBER_OF_ITERATES,1,temp_err);
         outerTerminationCriterion = & defaultOuterCriterion;
         innerTerminationCriterion = & defaultInnerCriterion;
       }
Member Function Documentation
virtual AlgorithmType get_algorithm_type () inline virtual
Return the algorithm type (to avoid RTTI use).
Implements PatchDataUser.
Definition at line 76 of file includeLinks/QualityImprover.hpp.
References PatchDataUser::QUALITY_IMPROVER.
 { return QUALITY_IMPROVER; }
virtual AlgorithmType get_algorithm_type () inline virtual
Return the algorithm type (to avoid RTTI use).
Implements PatchDataUser.
Definition at line 76 of file src/QualityImprover/QualityImprover.hpp.
References PatchDataUser::QUALITY_IMPROVER.
 { return QUALITY_IMPROVER; }
TerminationCriterion* get_inner_termination_criterion () inline protected
return the inner termination criterion pointer
Definition at line 123 of file includeLinks/QualityImprover.hpp.
References QualityImprover::innerTerminationCriterion.
Referenced by ConjugateGradient::ConjugateGradient(), FeasibleNewton::FeasibleNewton(), VertexMover::loop_over_mesh(), ConjugateGradient::optimize_vertex_positions(), SteepestDescent::optimize_vertex_positions(), and FeasibleNewton::optimize_vertex_positions().
       { return innerTerminationCriterion; }
TerminationCriterion* get_inner_termination_criterion () inline protected
return the inner termination criterion pointer
Definition at line 123 of file src/QualityImprover/QualityImprover.hpp.
References QualityImprover::innerTerminationCriterion.
       { return innerTerminationCriterion; }
const MeshSet* get_mesh_set () const inline protected
Definition at line 109 of file src/QualityImprover/QualityImprover.hpp.
References QualityImprover::mMeshSet.
       { return mMeshSet; }
const MeshSet* get_mesh_set () const inline protected
Definition at line 109 of file includeLinks/QualityImprover.hpp.
References QualityImprover::mMeshSet.
Referenced by NonSmoothSteepestDescent::optimize_vertex_positions().
       { return mMeshSet; }
MeshSet* get_mesh_set () inline protected
Definition at line 111 of file src/QualityImprover/QualityImprover.hpp.
References QualityImprover::mMeshSet.
       { return mMeshSet; }
MeshSet* get_mesh_set () inline protected
Definition at line 111 of file includeLinks/QualityImprover.hpp.
References QualityImprover::mMeshSet.
       { return mMeshSet; }
virtual msq_std::string get_name () inline virtual
retrieves the QualityImprover name. A default name should be set in the constructor.
Implements PatchDataUser.
Definition at line 75 of file includeLinks/QualityImprover.hpp.
References QualityImprover::qualityImproverName.
 { return qualityImproverName; }
virtual msq_std::string get_name () inline virtual
retrieves the QualityImprover name. A default name should be set in the constructor.
Implements PatchDataUser.
Definition at line 75 of file src/QualityImprover/QualityImprover.hpp.
References QualityImprover::qualityImproverName.
 { return qualityImproverName; }
TerminationCriterion* get_outer_termination_criterion () inline protected
return the outer termination criterion pointer
Definition at line 120 of file src/QualityImprover/QualityImprover.hpp.
References QualityImprover::outerTerminationCriterion.
       { return outerTerminationCriterion; }
TerminationCriterion* get_outer_termination_criterion () inline protected
return the outer termination criterion pointer
Definition at line 120 of file includeLinks/QualityImprover.hpp.
References QualityImprover::outerTerminationCriterion.
Referenced by VertexMover::loop_over_mesh().
       { return outerTerminationCriterion; }
virtual double loop_over_mesh (MeshSet & ms, MsqError & err) pure virtual
This is the "run" function of PatchDataUser. It can do anything really.
Implements PatchDataUser.
Implemented in VertexMover, VertexMover, TopologyModifier, and TopologyModifier.
virtual double loop_over_mesh (MeshSet & ms, MsqError & err) pure virtual
This is the "run" function of PatchDataUser. It can do anything really.
Implements PatchDataUser.
Implemented in VertexMover, VertexMover, TopologyModifier, and TopologyModifier.
void set_inner_termination_criterion (TerminationCriterion * crit) inline
Sets in the termination criterion for the concrete solver's optimization.
Definition at line 80 of file src/QualityImprover/QualityImprover.hpp.
References QualityImprover::innerTerminationCriterion.
       {
         innerTerminationCriterion=crit;
       }
void set_inner_termination_criterion (TerminationCriterion * crit) inline
Sets in the termination criterion for the concrete solver's optimization.
Definition at line 80 of file includeLinks/QualityImprover.hpp.
References QualityImprover::innerTerminationCriterion.
Referenced by ShapeImprovementWrapper::ShapeImprovementWrapper().
       {
         innerTerminationCriterion=crit;
       }
void set_mesh_set (MeshSet * ms) inline protected
Definition at line 115 of file src/QualityImprover/QualityImprover.hpp.
References QualityImprover::mMeshSet.
       {
         mMeshSet=ms;
       }
void set_mesh_set (MeshSet * ms) inline protected
Definition at line 115 of file includeLinks/QualityImprover.hpp.
References QualityImprover::mMeshSet.
Referenced by VertexMover::loop_over_mesh().
       {
         mMeshSet=ms;
       }
void set_name (msq_std::string name) inline
provides a name to the QualityImprover (use it in constructor).
Definition at line 69 of file src/QualityImprover/QualityImprover.hpp.
References QualityImprover::qualityImproverName.
       {
         qualityImproverName = name;
       };
void set_name (msq_std::string name) inline
provides a name to the QualityImprover (use it in constructor).
Definition at line 69 of file includeLinks/QualityImprover.hpp.
References QualityImprover::qualityImproverName.
Referenced by ConjugateGradient::ConjugateGradient(), FeasibleNewton::FeasibleNewton(), LaplacianSmoother::LaplacianSmoother(), NonSmoothSteepestDescent::NonSmoothSteepestDescent(), Randomize::Randomize(), SmartLaplacianSmoother::SmartLaplacianSmoother(), and SteepestDescent::SteepestDescent().
       {
         qualityImproverName = name;
       };
void set_outer_termination_criterion (TerminationCriterion * crit) inline
Sets in the termination criterion for the outer loop over patches.
Definition at line 86 of file includeLinks/QualityImprover.hpp.
References QualityImprover::outerTerminationCriterion.
Referenced by LaplacianIQ::LaplacianIQ(), and ShapeImprovementWrapper::ShapeImprovementWrapper().
       {
         outerTerminationCriterion=crit;
       }
void set_outer_termination_criterion (TerminationCriterion * crit) inline
Sets in the termination criterion for the outer loop over patches.
Definition at line 86 of file src/QualityImprover/QualityImprover.hpp.
References QualityImprover::outerTerminationCriterion.
       {
         outerTerminationCriterion=crit;
       }
Friends And Related Function Documentation
MeshSet friend
Definition at line 105 of file includeLinks/QualityImprover.hpp.
Member Data Documentation
TerminationCriterion defaultInnerCriterion private
Definition at line 136 of file includeLinks/QualityImprover.hpp.
Referenced by QualityImprover::QualityImprover().
TerminationCriterion defaultOuterCriterion private
Definition at line 134 of file includeLinks/QualityImprover.hpp.
Referenced by QualityImprover::QualityImprover().
TerminationCriterion * innerTerminationCriterion private
Definition at line 131 of file includeLinks/QualityImprover.hpp.
Referenced by QualityImprover::get_inner_termination_criterion(), QualityImprover::QualityImprover(), and QualityImprover::set_inner_termination_criterion().
MeshSet * mMeshSet private
Definition at line 127 of file includeLinks/QualityImprover.hpp.
Referenced by QualityImprover::get_mesh_set(), and QualityImprover::set_mesh_set().
TerminationCriterion * outerTerminationCriterion private
Definition at line 132 of file includeLinks/QualityImprover.hpp.
Referenced by QualityImprover::get_outer_termination_criterion(), QualityImprover::QualityImprover(), and QualityImprover::set_outer_termination_criterion().
int patchDepth private
Definition at line 129 of file includeLinks/QualityImprover.hpp.
msq_std::string qualityImproverName private
Definition at line 128 of file includeLinks/QualityImprover.hpp.
Referenced by QualityImprover::get_name(), and QualityImprover::set_name().
The documentation for this class was generated from the following file:
includeLinks/QualityImprover.hpp