Rocstar: BoundingBox Class Reference
BoundingBox Class Reference
A concrete object that provides the functionality for representing a bounding box geometric primitive and associated operations such as bounding box intersection.
#include <BoundingBox.hpp>
Public Member Functions
void setCoordinates (const double x, const double y, const double z, const double X, const double Y, const double Z)
Sets the coordinates of this BoundingBox instance.
BoundingBox ()
Default Constructor.
BoundingBox (const double x, const double y, const double z, const double X, const double Y, const double Z)
Custom Constructor.
~BoundingBox ()
Destructor.
double getMinX ()
double getMinY ()
double getMinZ ()
double getMaxX ()
double getMaxY ()
double getMaxZ ()
bool hasPoint (const double x, const double y, const double z)
Determines if a point is inside the bounding box.
Static Public Member Functions
static BoundingBox intersection (BoundingBox &b1, BoundingBox &b2)
Computes the bounding box intersection between bounding box b1,b2.
static size_t Size ()
Same as BoundingBox::getBytesize() but does not require a BoundingBox instance to be allocated.
Protected Attributes
double max [3]
double min [3]
Detailed Description
A concrete object that provides the functionality for representing a bounding box geometric primitive and associated operations such as bounding box intersection.
Author
George Zagaris (gzaga.nosp@m.ris@.nosp@m.illin.nosp@m.ois..nosp@m.edu)
Date
1/30/2009
Definition at line 21 of file BoundingBox.hpp.
Constructor & Destructor Documentation
BoundingBox () inline
Default Constructor.
Constructs a 1x1x1 cube
Definition at line 116 of file BoundingBox.hpp.
Referenced by intersection().
                 {
                         this ->min[ 0 ]  = 0.0;
                         this ->min[ 1 ]  = 0.0;
                         this ->min[ 2 ]  = 0.0;
                         this ->max[ 0 ]  = 1.0;
                         this ->max[ 1 ]  = 1.0;
                         this ->max[ 2 ]  = 1.0;
                 }
BoundingBox (const double x, const double y, const double z, const double X, const double Y, const double Z) inline
Custom Constructor.
Parameters
x min x of the bounding box
y min y of the bounding box
z min z of the bounding box
X max x of the bounding box
Y max y of the bounding box
Z max z of the bounding box
Definition at line 135 of file BoundingBox.hpp.
                 {
                         this ->setCoordinates( x,y,z, X,Y,Z );
                 }
~BoundingBox () inline
Destructor.
Definition at line 144 of file BoundingBox.hpp.
                 {
                 }
Member Function Documentation
double getMaxX () inline
Returns
x max x
Definition at line 167 of file BoundingBox.hpp.
Referenced by hasPoint(), and intersection().
 { return this ->max[ 0 ]; };
double getMaxY () inline
Returns
y max y
Definition at line 172 of file BoundingBox.hpp.
Referenced by hasPoint(), and intersection().
 { return this ->max[ 1 ]; };
double getMaxZ () inline
Returns
z max z
Definition at line 177 of file BoundingBox.hpp.
Referenced by hasPoint(), and intersection().
 { return this ->max[ 2 ]; };
double getMinX () inline
Returns
x min x
Definition at line 152 of file BoundingBox.hpp.
Referenced by hasPoint(), and intersection().
 { return this ->min[ 0 ]; };
double getMinY () inline
Returns
y min y
Definition at line 157 of file BoundingBox.hpp.
Referenced by hasPoint(), and intersection().
 { return this ->min[ 1 ]; };
double getMinZ () inline
Returns
z min z
Definition at line 162 of file BoundingBox.hpp.
Referenced by hasPoint(), and intersection().
 { return this ->min[ 2 ]; };
bool hasPoint (const double x, const double y, const double z) inline
Determines if a point is inside the bounding box.
Parameters
x the x-coordinate of the point in query.
y the y-coordinate of the point in query.
z the z-coordinate of the point in query.
Returns
status true if the point (x,y,z) is inside this instance of bounding box, else false.
Definition at line 187 of file BoundingBox.hpp.
References Numerics::fpointequals(), getMaxX(), getMaxY(), getMaxZ(), getMinX(), getMinY(), and getMinZ().
                 {
                         return(
                                 ( x > this ->getMinX( ) || Numerics::fpointequals( x, this ->getMinX( ) ) ) &&
                                 ( x < this ->getMaxX( ) || Numerics::fpointequals( x, this ->getMaxX( ) ) ) &&
                                 ( y > this ->getMinY( ) || Numerics::fpointequals( y, this ->getMinY( ) ) ) &&
                                 ( y < this ->getMaxY( ) || Numerics::fpointequals( y, this ->getMaxY( ) ) ) &&
                                 ( z > this ->getMinZ( ) || Numerics::fpointequals( z, this ->getMinZ( ) ) ) &&
                                 ( z < this ->getMaxZ( ) || Numerics::fpointequals( z, this ->getMaxZ( ) ) )
                         );
                 }
static BoundingBox intersection (BoundingBox & b1, BoundingBox & b2) inline static
Computes the bounding box intersection between bounding box b1,b2.
Parameters
b1 the bounding box instance to intersect with bounding box b2.
b2 the bounding box instance to intersect with bounding box b1.
Returns
c the bounding box intersection of b1,b2.
Definition at line 36 of file BoundingBox.hpp.
References BoundingBox(), getMaxX(), getMaxY(), getMaxZ(), getMinX(), getMinY(), getMinZ(), max, and min.
                 {
                          double min[3]; double max[3];
                                 std::vector< double > xaxis; xaxis.resize( 4 );
                                 std::vector< double > yaxis; yaxis.resize( 4 );
                                 std::vector< double > zaxis; zaxis.resize( 4 );
                                 xaxis[ 0 ] = b1.getMinX( );
                                 xaxis[ 1 ] = b1.getMaxX( );
                                 xaxis[ 2 ] = b2.getMinX( );
                                 xaxis[ 3 ] = b2.getMaxX( );
                                 yaxis[ 0 ] = b1.getMinY( );
                                 yaxis[ 1 ] = b1.getMaxY( );
                                 yaxis[ 2 ] = b2.getMinY( );
                                 yaxis[ 3 ] = b2.getMaxY( );
                                 zaxis[ 0 ] = b1.getMinZ( );
                                 zaxis[ 1 ] = b1.getMaxZ( );
                                 zaxis[ 2 ] = b2.getMinZ( );
                                 zaxis[ 3 ] = b2.getMaxZ( );
                                 std::sort( xaxis.begin( ), xaxis.end( ) );
                                 std::sort( yaxis.begin( ), yaxis.end( ) );
                                 std::sort( zaxis.begin( ), zaxis.end( ) );
                                 min[ 0 ] = xaxis[ 1 ];
                                 max[ 0 ] = xaxis[ 2 ];
                                 min[ 1 ] = yaxis[ 1 ];
                                 max[ 1 ] = yaxis[ 2 ];
                                 min[ 2 ] = zaxis[ 1 ];
                                 max[ 2 ] = zaxis[ 2 ];
                                 xaxis.clear( );
                                 yaxis.clear( );
                                 zaxis.clear( );
                                 return ( BoundingBox( min[ 0 ], min[ 1 ], min[ 2 ],
                                                                                                                         max[ 0 ], max[ 1 ], max[ 2 ] ) );
                 }
void setCoordinates (const double x, const double y, const double z, const double X, const double Y, const double Z) inline
Sets the coordinates of this BoundingBox instance.
Parameters
x min x of the bounding box
y min y of the bounding box
z min z of the bounding box
X max x of the bounding box
Y max y of the bounding box
Z max z of the bounding box
Definition at line 101 of file BoundingBox.hpp.
References x, y, and z.
Referenced by ComSwitch::parseValuesFromArguments().
{
                                         this ->min[ 0 ] = x;
                                         this ->min[ 1 ] = y;
                                         this ->min[ 2 ] = z;
                                         this ->max[ 0 ] = X;
                                         this ->max[ 1 ] = Y;
                                         this ->max[ 2 ] = Z;
                         };
static size_t Size () inline static
Same as BoundingBox::getBytesize() but does not require a BoundingBox instance to be allocated.
Returns
The size of a BoundingBox instance.
Definition at line 87 of file BoundingBox.hpp.
                 {
                         return( 6*sizeof( double ) );
                 }
Member Data Documentation
double max[3] protected
Definition at line 24 of file BoundingBox.hpp.
Referenced by intersection().
double min[3] protected
Definition at line 25 of file BoundingBox.hpp.
Referenced by intersection().
The documentation for this class was generated from the following file:
BoundingBox.hpp