Rocstar: FDSetMan Class Reference
FDSetMan Class Reference
#include <FDUtils.H>
Public Types
typedef std::vector< int > FDContainerType
Public Member Functions
FDSetMan ()
fd_set & ReadSet ()
const fd_set ReadSet () const
fd_set & WriteSet ()
const fd_set WriteSet () const
fd_set & ExceptionSet ()
const fd_set ExceptionSet () const
void SetOutDescriptor (int infd)
void SetInDescriptor (int infd)
void ClearOutDescriptor (int infd)
void ClearInDescriptor (int infd)
int AddOutDescriptor (int infd)
int AddInDescriptor (int infd)
int AddIODescriptor (int infd)
void Zero ()
void Clear (int infd)
void SetForRead (int infd=-1)
template<class FDContainer >
void SetForRead (const FDContainer &fds, bool reset=true)
void SetForWrite (int infd=-1)
template<class FDContainer >
void SetForWrite (const FDContainer &fds)
void SetForIO (int infd=-1)
template<class FDContainer >
void SetForIO (const FDContainer &fds, bool reset=true)
int ReadyForOutput (int infd=-1)
int ReadyForInput (int infd=-1)
template<class FDContainer >
int ReadyForOutput (const FDContainer &fds)
template<class FDContainer >
int ReadyForInput (const FDContainer &fds)
int Select (float seconds=0.0, bool reset=true)
int ListenForInput (float seconds=0.0, bool reset=true)
int ListenForOutput (float seconds=0.0, bool reset=true)
template<class FDContainer >
int NSet (const FDContainer &fds, fd_set *fdset)
template<class FDContainer >
void Set (const FDContainer &fds, fd_set *fdset, bool reset=true)
Private Attributes
fd_set readset
fd_set writeset
fd_set exset
int max_descriptor
FDContainerType o_descriptors
FDContainerType i_descriptors
FDContainerType io_descriptors
Detailed Description
Definition at line 201 of file FDUtils.H.
Member Typedef Documentation
typedef std::vector<int> FDContainerType
Definition at line 204 of file FDUtils.H.
Constructor & Destructor Documentation
FDSetMan () inline
Definition at line 217 of file FDUtils.H.
References FDSetMan::exset, FDSetMan::i_descriptors, FDSetMan::io_descriptors, FDSetMan::o_descriptors, FDSetMan::readset, and FDSetMan::writeset.
                  : max_descriptor(-1)
       {
         FD_ZERO(&readset);
         FD_ZERO(&writeset);
         FD_ZERO(&exset);
         o_descriptors.resize(0);
         i_descriptors.resize(0);
         io_descriptors.resize(0);
         //      instreams[0]  = &std::cin;
         //      outstreams[1] = &std::out;
         //      outstreams[2] = &std::cerr;
       };
Member Function Documentation
int AddInDescriptor (int infd) inline
Definition at line 265 of file FDUtils.H.
References FDSetMan::i_descriptors, and FDSetMan::SetInDescriptor().
Referenced by IRAD::TestTCPInterface().
       {
         if(infd < 0)
           return(-1);
         i_descriptors.push_back(infd);
         SetInDescriptor(infd);
         return(0);
       };
int AddIODescriptor (int infd) inline
Definition at line 273 of file FDUtils.H.
References FDSetMan::io_descriptors, FDSetMan::SetInDescriptor(), and FDSetMan::SetOutDescriptor().
Referenced by IRAD::TestTCPInterface().
       {
         if(infd < 0)
           return(-1);
         io_descriptors.push_back(infd);
         SetInDescriptor(infd);
         SetOutDescriptor(infd);
         return(0);
       };
int AddOutDescriptor (int infd) inline
Definition at line 255 of file FDUtils.H.
References FDSetMan::o_descriptors, and FDSetMan::SetOutDescriptor().
       {
         if(infd < 0)
           return(-1);
         o_descriptors.push_back(infd);
         SetOutDescriptor(infd);
         //      if(infd > max_descriptor)
         //      max_descriptor = infd;
         return(0);
       };
void Clear (int infd) inline
Definition at line 288 of file FDUtils.H.
References FDSetMan::exset, FDSetMan::readset, and FDSetMan::writeset.
       {
         if(infd >= 0){
           FD_CLR(infd,&readset);
           FD_CLR(infd,&writeset);
           FD_CLR(infd,&exset);
         }
       };
void ClearInDescriptor (int infd) inline
Definition at line 251 of file FDUtils.H.
References FDSetMan::readset.
{
         if(infd >= 0)
           FD_CLR(infd,&readset);
       };
void ClearOutDescriptor (int infd) inline
Definition at line 247 of file FDUtils.H.
References FDSetMan::writeset.
{
         if(infd >= 0)
           FD_CLR(infd,&writeset);
       };
fd_set& ExceptionSet () inline
Definition at line 233 of file FDUtils.H.
References FDSetMan::exset.
 { return(exset); };
const fd_set ExceptionSet () const inline
Definition at line 234 of file FDUtils.H.
References FDSetMan::exset.
 { return(exset); };
int ListenForInput (float seconds = 0.0, bool reset = true) inline
Definition at line 398 of file FDUtils.H.
References FDSetMan::exset, FDSetMan::max_descriptor, FDSetMan::readset, FDSetMan::SetForRead(), and FDSetMan::Zero().
       {
         float usec = 1.0E-6;
         struct timeval tv;
         struct timeval *tv_ptr = NULL;
         if(seconds >= 0.0){
           tv_ptr = &tv;
           tv.tv_sec  = static_cast<long>(seconds);
           tv.tv_usec = static_cast<long>((seconds - tv.tv_sec)/usec);
         }
         if(reset){
           this->Zero();
           this->SetForRead();
         }
         int retval = select(max_descriptor+1,&readset,NULL,&exset,tv_ptr);
         if(retval < 0)
           perror("Sys::FDStreamSet::Select::select");
         return(retval);
       };
int ListenForOutput (float seconds = 0.0, bool reset = true) inline
Definition at line 417 of file FDUtils.H.
References FDSetMan::exset, FDSetMan::max_descriptor, FDSetMan::SetForWrite(), FDSetMan::writeset, and FDSetMan::Zero().
       {
         float usec = 1.0E-6;
         struct timeval tv;
         struct timeval *tv_ptr = NULL;
         if(seconds >= 0.0){
           tv_ptr = &tv;
           tv.tv_sec  = static_cast<long>(seconds);
           tv.tv_usec = static_cast<long>((seconds - tv.tv_sec)/usec);
         }
         if(reset){
           this->Zero();
           this->SetForWrite();
         }
         int retval = select(max_descriptor+1,NULL,&writeset,&exset,tv_ptr);
         if(retval < 0)
           perror("Sys::FDStreamSet::Select::select");
         return(retval);
       };
int NSet (const FDContainer & fds, fd_set * fdset) inline
Definition at line 437 of file FDUtils.H.
Referenced by FDSetMan::ReadyForInput(), and FDSetMan::ReadyForOutput().
       {
         int retval = 0;
         typename FDContainer::const_iterator fdi = fds.begin();
         while(fdi != fds.end())
           retval += FD_ISSET(*fdi++,fdset);
         return(retval);
       };
fd_set& ReadSet () inline
Definition at line 229 of file FDUtils.H.
References FDSetMan::readset.
 { return(readset);    };
const fd_set ReadSet () const inline
Definition at line 230 of file FDUtils.H.
References FDSetMan::readset.
 { return(readset);    };
int ReadyForInput (int infd = -1) inline
Definition at line 356 of file FDUtils.H.
References FDSetMan::i_descriptors, FDSetMan::io_descriptors, FDSetMan::NSet(), and FDSetMan::readset.
Referenced by IRAD::TestTCPInterface().
       {
         int retval = 0;
         if(infd >= 0){
           retval = FD_ISSET(infd,&readset);
         }
         else {
           retval += NSet(i_descriptors,&readset);
           retval += NSet(io_descriptors,&readset);
         }
         return(retval);
       };
int ReadyForInput (const FDContainer & fds) inline
Definition at line 374 of file FDUtils.H.
References FDSetMan::NSet(), and FDSetMan::readset.
       {
         return(NSet(fds,&readset));
       };
int ReadyForOutput (int infd = -1) inline
Definition at line 345 of file FDUtils.H.
References FDSetMan::io_descriptors, FDSetMan::NSet(), FDSetMan::o_descriptors, and FDSetMan::writeset.
Referenced by IRAD::TestTCPInterface().
       {
         int retval = 0;
         if(infd >= 0)
           retval = FD_ISSET(infd,&writeset);
         else {
           retval += NSet(o_descriptors,&writeset);
           retval += NSet(io_descriptors,&writeset);
         }
         return(retval);
       };
int ReadyForOutput (const FDContainer & fds) inline
Definition at line 369 of file FDUtils.H.
References FDSetMan::NSet(), and FDSetMan::writeset.
       {
         return(NSet(fds,&writeset));
       };
int Select (float seconds = 0.0, bool reset = true) inline
Definition at line 378 of file FDUtils.H.
References FDSetMan::exset, FDSetMan::max_descriptor, FDSetMan::readset, FDSetMan::SetForRead(), FDSetMan::SetForWrite(), FDSetMan::writeset, and FDSetMan::Zero().
Referenced by IRAD::TestTCPInterface().
       {
         float usec = 1.0E-6;
         struct timeval tv;
         struct timeval *tv_ptr = NULL;
         if(seconds >= 0.0){
           tv_ptr = &tv;
           tv.tv_sec  = static_cast<long>(seconds);
           tv.tv_usec = static_cast<long>((seconds - tv.tv_sec)/usec);
         }
         if(reset){
           this->Zero();
           this->SetForRead();
           this->SetForWrite();
         }
         int retval = select(max_descriptor+1,&readset,&writeset,&exset,tv_ptr);
         if(retval < 0)
           perror("Sys::FDStreamSet::Select::select");
         return(retval);
       };
void Set (const FDContainer & fds, fd_set * fdset, bool reset = true) inline
Definition at line 446 of file FDUtils.H.
Referenced by FDSetMan::SetForIO(), FDSetMan::SetForRead(), and FDSetMan::SetForWrite().
       {
         if(reset)
           FD_ZERO(fdset);
         typename FDContainer::const_iterator fdi = fds.begin();
         while(fdi != fds.end()){
           int descriptor = *fdi++;
           FD_SET(descriptor,fdset);
         }
       };
void SetForIO (int infd = -1) inline
Definition at line 324 of file FDUtils.H.
References FDSetMan::i_descriptors, FDSetMan::io_descriptors, FDSetMan::o_descriptors, FDSetMan::readset, FDSetMan::Set(), and FDSetMan::writeset.
       {
         if(infd >= 0){
           FD_SET(infd,&readset);
           FD_SET(infd,&writeset);
         }
         else{
           Set(i_descriptors,&readset);
           Set(o_descriptors,&writeset);
           Set(io_descriptors,&readset,false);
           Set(io_descriptors,&writeset,false);
         }
       };
void SetForIO (const FDContainer & fds, bool reset = true) inline
Definition at line 338 of file FDUtils.H.
References FDSetMan::i_descriptors, FDSetMan::io_descriptors, FDSetMan::o_descriptors, FDSetMan::readset, FDSetMan::Set(), and FDSetMan::writeset.
       {
         Set(i_descriptors,&readset,reset);
         Set(o_descriptors,&writeset,reset);
         Set(io_descriptors,&readset,false);
         Set(io_descriptors,&writeset,false);
       };
void SetForRead (int infd = -1) inline
Definition at line 296 of file FDUtils.H.
References FDSetMan::i_descriptors, FDSetMan::io_descriptors, FDSetMan::readset, and FDSetMan::Set().
Referenced by FDSetMan::ListenForInput(), and FDSetMan::Select().
       {
         if(infd >= 0)
           FD_SET(infd,&readset);
         else {
           Set(i_descriptors,&readset);
           Set(io_descriptors,&readset,false);
         }
       };
void SetForRead (const FDContainer & fds, bool reset = true) inline
Definition at line 306 of file FDUtils.H.
References FDSetMan::readset, and FDSetMan::Set().
       {
         Set(fds,&readset,reset);
       };
void SetForWrite (int infd = -1) inline
Definition at line 310 of file FDUtils.H.
References FDSetMan::io_descriptors, FDSetMan::o_descriptors, FDSetMan::Set(), and FDSetMan::writeset.
Referenced by FDSetMan::ListenForOutput(), and FDSetMan::Select().
       {
         if(infd >= 0)
           FD_SET(infd,&writeset);
         else{
           Set(o_descriptors,&writeset);
           Set(io_descriptors,&writeset,false);
         }
       };
void SetForWrite (const FDContainer & fds) inline
Definition at line 320 of file FDUtils.H.
References FDSetMan::Set(), and FDSetMan::writeset.
       {
         Set(fds,&writeset);
       };
void SetInDescriptor (int infd) inline
Definition at line 241 of file FDUtils.H.
References FDSetMan::max_descriptor, and FDSetMan::readset.
Referenced by FDSetMan::AddInDescriptor(), and FDSetMan::AddIODescriptor().
{
         if(infd >= 0)
           FD_SET(infd,&readset);
         if(infd > max_descriptor)
           max_descriptor = infd;
       };
void SetOutDescriptor (int infd) inline
Definition at line 235 of file FDUtils.H.
References FDSetMan::max_descriptor, and FDSetMan::writeset.
Referenced by FDSetMan::AddIODescriptor(), and FDSetMan::AddOutDescriptor().
{
         if(infd >= 0)
           FD_SET(infd,&writeset);
         if(infd > max_descriptor)
           max_descriptor = infd;
       };
fd_set& WriteSet () inline
Definition at line 231 of file FDUtils.H.
References FDSetMan::writeset.
 { return(writeset);  };
const fd_set WriteSet () const inline
Definition at line 232 of file FDUtils.H.
References FDSetMan::writeset.
 { return(writeset);  };
void Zero () inline
Definition at line 282 of file FDUtils.H.
References FDSetMan::exset, FDSetMan::readset, and FDSetMan::writeset.
Referenced by FDSetMan::ListenForInput(), FDSetMan::ListenForOutput(), and FDSetMan::Select().
       {
         FD_ZERO(&readset);
         FD_ZERO(&writeset);
         FD_ZERO(&exset);
       };
Member Data Documentation
fd_set exset private
Definition at line 208 of file FDUtils.H.
Referenced by FDSetMan::Clear(), FDSetMan::ExceptionSet(), FDSetMan::FDSetMan(), FDSetMan::ListenForInput(), FDSetMan::ListenForOutput(), FDSetMan::Select(), and FDSetMan::Zero().
FDContainerType i_descriptors private
Definition at line 211 of file FDUtils.H.
Referenced by FDSetMan::AddInDescriptor(), FDSetMan::FDSetMan(), FDSetMan::ReadyForInput(), FDSetMan::SetForIO(), and FDSetMan::SetForRead().
FDContainerType io_descriptors private
Definition at line 212 of file FDUtils.H.
Referenced by FDSetMan::AddIODescriptor(), FDSetMan::FDSetMan(), FDSetMan::ReadyForInput(), FDSetMan::ReadyForOutput(), FDSetMan::SetForIO(), FDSetMan::SetForRead(), and FDSetMan::SetForWrite().
int max_descriptor private
Definition at line 209 of file FDUtils.H.
Referenced by FDSetMan::ListenForInput(), FDSetMan::ListenForOutput(), FDSetMan::Select(), FDSetMan::SetInDescriptor(), and FDSetMan::SetOutDescriptor().
FDContainerType o_descriptors private
Definition at line 210 of file FDUtils.H.
Referenced by FDSetMan::AddOutDescriptor(), FDSetMan::FDSetMan(), FDSetMan::ReadyForOutput(), FDSetMan::SetForIO(), and FDSetMan::SetForWrite().
fd_set readset private
Definition at line 206 of file FDUtils.H.
Referenced by FDSetMan::Clear(), FDSetMan::ClearInDescriptor(), FDSetMan::FDSetMan(), FDSetMan::ListenForInput(), FDSetMan::ReadSet(), FDSetMan::ReadyForInput(), FDSetMan::Select(), FDSetMan::SetForIO(), FDSetMan::SetForRead(), FDSetMan::SetInDescriptor(), and FDSetMan::Zero().
fd_set writeset private
Definition at line 207 of file FDUtils.H.
Referenced by FDSetMan::Clear(), FDSetMan::ClearOutDescriptor(), FDSetMan::FDSetMan(), FDSetMan::ListenForOutput(), FDSetMan::ReadyForOutput(), FDSetMan::Select(), FDSetMan::SetForIO(), FDSetMan::SetForWrite(), FDSetMan::SetOutDescriptor(), FDSetMan::WriteSet(), and FDSetMan::Zero().
The documentation for this class was generated from the following file:
FDUtils.H