Rocstar: rflu_modcellfaceedgeinfo Module Reference
rflu_modcellfaceedgeinfo Module Reference
Public Member Functions
integer function, public rflu_getglobalcelltype (global, pGrid, icg)
integer function, public rflu_getglobalcellkind (global, pGrid, icg)
integer function, public rflu_getvirtualcellreg (global, pGrid, icg)
integer function, public rflu_getfacekind (global, c1k, c2k)
integer function, public rflu_getedgekind (global, pGrid, v1, v2)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModCellFaceEdgeInfo.F90,v $ $Revision: 1.12 $'
Detailed Description
Definition at line 40 of file RFLU_ModCellFaceEdgeInfo.F90.
Member Function/Subroutine Documentation
integer function, public rflu_getedgekind (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, intent(in) v1, integer, intent(in) v2)
Definition at line 433 of file RFLU_ModCellFaceEdgeInfo.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modedgelist::rflu_buildedge2celllist(), and rflu_modedgelist::rflu_buildedgelist().
integer function, public rflu_getfacekind (type(t_global), pointer global, integer, intent(in) c1k, integer, intent(in) c2k)
Definition at line 358 of file RFLU_ModCellFaceEdgeInfo.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellslohner(), plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), plag_rflu_modfindcells::plag_rflu_findcellstrajsafe(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), and rflu_modtecplotutils::rflu_tec_writezoneinterf().
integer function, public rflu_getglobalcellkind (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, intent(in) icg)
Definition at line 163 of file RFLU_ModCellFaceEdgeInfo.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellslohner(), plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), plag_rflu_modfindcells::plag_rflu_findcellstrajsafe(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), and rflu_modtecplotutils::rflu_tec_writezoneinterf().
integer function, public rflu_getglobalcelltype (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, intent(in) icg)
Definition at line 96 of file RFLU_ModCellFaceEdgeInfo.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modstencilsutils::rflu_addcelllayer(), rflu_modstencilsutils::rflu_addcelllayer_1d_g(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil_1d_g(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modstencilscells::rflu_buildc2cstencilbasic_1d(), rflu_modfacelist::rflu_buildfacelist(), and rflu_modvertexlists::rflu_buildvert2celllist().
integer function, public rflu_getvirtualcellreg (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, intent(in) icg)
Definition at line 273 of file RFLU_ModCellFaceEdgeInfo.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), and moderror::registerfunction().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModCellFaceEdgeInfo.F90,v $ $Revision: 1.12 $' private
Definition at line 65 of file RFLU_ModCellFaceEdgeInfo.F90.
The documentation for this module was generated from the following file:
RFLU_ModCellFaceEdgeInfo.F90