Rocstar: plag_rflo_modstats Module Reference
plag_rflo_modstats Module Reference
Public Member Functions
subroutine plag_rflo_clearreqstatbuff (regions, iReg)
subroutine, public plag_rflo_createstatbuff (regions, iReg)
subroutine, public plag_rflo_commstatbuffwrapper (regions)
subroutine plag_rflo_copystatbuff (pRegion, pRegionSrc, pPatch, pPatchSrc)
subroutine, public plag_rflo_readstat (regions)
subroutine plag_rflo_recvstatbuffwrapper (regions, iReg)
subroutine plag_rflo_recvstatbuff (pRegion, pRegionSrc, pPatch, pPatchSrc)
subroutine plag_rflo_sendstatbuffwrapper (regions, iReg)
subroutine plag_rflo_sendstatbuffconf (pRegion, pRegionSrc, pPatch)
subroutine, public plag_rflo_writestat (regions)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_RFLO_ModStats.F90,v $ $Revision: 1.9 $'
Detailed Description
Definition at line 39 of file PLAG_RFLO_ModStats.F90.
Member Function/Subroutine Documentation
subroutine plag_rflo_clearreqstatbuff (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 128 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and Attribute::status().
Referenced by plag_rflo_commstatbuffwrapper().
subroutine, public plag_rflo_commstatbuffwrapper (type(t_region), dimension(:), pointer regions)
Definition at line 396 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_rflo_clearreqstatbuff(), plag_rflo_copystatbuff(), plag_rflo_recvstatbuffwrapper(), plag_rflo_sendstatbuffwrapper(), moderror::registerfunction(), and CImg< T >::select().
Referenced by modstatsroutines::statwritemp().
subroutine plag_rflo_copystatbuff (type(t_region), pointer pRegion, type(t_region), pointer pRegionSrc, type(t_patch), pointer pPatch, type(t_patch), pointer pPatchSrc)
Definition at line 570 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, modindexing::indijkmap(), j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and rflo_getpatchmapping().
Referenced by plag_rflo_commstatbuffwrapper().
subroutine, public plag_rflo_createstatbuff (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 238 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_allocatedatabuffers().
subroutine, public plag_rflo_readstat (type(t_region), dimension(:), pointer regions)
Definition at line 731 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, idcbeg, idcend, j, jdcbeg, jdcend, k, kdcbeg, COM_exception::msg(), n, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_readdatafileint(), rflo_readdatafilereal(), and Attribute::status().
Referenced by modstatsroutines::initstatistics().
subroutine plag_rflo_recvstatbuff (type(t_region), pointer pRegion, type(t_region), pointer pRegionSrc, type(t_patch), pointer pPatch, type(t_patch), pointer pPatchSrc)
Definition at line 1189 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchindices(), Ray_2< R, T >::source(), Attribute::status(), and RFC_Data_const< _Tag >::tag().
Referenced by plag_rflo_recvstatbuffwrapper().
subroutine plag_rflo_recvstatbuffwrapper (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 1084 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), plag_rflo_recvstatbuff(), and moderror::registerfunction().
Referenced by plag_rflo_commstatbuffwrapper().
subroutine plag_rflo_sendstatbuffconf (type(t_region), pointer pRegion, type(t_region), pointer pRegionSrc, type(t_patch), pointer pPatch)
Definition at line 1540 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchindices(), and RFC_Data_const< _Tag >::tag().
Referenced by plag_rflo_sendstatbuffwrapper().
subroutine plag_rflo_sendstatbuffwrapper (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 1408 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_rflo_sendstatbuffconf(), moderror::registerfunction(), and CImg< T >::select().
Referenced by plag_rflo_commstatbuffwrapper().
subroutine, public plag_rflo_writestat (type(t_region), dimension(:), pointer regions)
Definition at line 1958 of file PLAG_RFLO_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, idcbeg, idcend, j, jdcbeg, jdcend, k, kdcbeg, n, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_writedatafileint(), rflo_writedatafilereal(), and Attribute::status().
Referenced by modstatsroutines::statwritemp().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_RFLO_ModStats.F90,v $ $Revision: 1.9 $' private
Definition at line 75 of file PLAG_RFLO_ModStats.F90.
The documentation for this module was generated from the following file:
PLAG_RFLO_ModStats.F90