Rocstar: UntangleBetaQualityMetric Class Reference
UntangleBetaQualityMetric Class Reference
The untangle beta quality metric.
#include <UntangleBetaQualityMetric.hpp>
Public Member Functions
UntangleBetaQualityMetric (double bet=0.05)
For untangle beta, the constructor defaults to the SUM averaging method, and to the ELEMENT_VERTICES evaluation mode.
virtual ~UntangleBetaQualityMetric ()
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &fval, MsqError &err)
void set_beta (double beta_in)
double get_beta ()
UntangleBetaQualityMetric (double bet=0.05)
virtual ~UntangleBetaQualityMetric ()
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &fval, MsqError &err)
void set_beta (double beta_in)
double get_beta ()
Public Member Functions inherited from UntangleQualityMetric
virtual ~UntangleQualityMetric ()
virtual ~UntangleQualityMetric ()
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Protected Member Functions
void untangle_function_2d (Vector3D temp_vec[], size_t e_ind, PatchData &pd, double &fval, MsqError &err)
void untangle_function_3d (Vector3D temp_vec[], double &fval, MsqError &err)
void untangle_function_2d (Vector3D temp_vec[], size_t e_ind, PatchData &pd, double &fval, MsqError &err)
void untangle_function_3d (Vector3D temp_vec[], double &fval, MsqError &err)
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Private Attributes
double mBeta
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
The untangle beta quality metric.
Given a scalar value beta and local signed element volume alpha_i, define delta_i to be alpha_i minus beta. The Untangle beta value is then defined as square root of the sum over sample points of the absolute value of delta_i minus delta_i, difference squared. That is, the root mean square of the difference, abs(delta_i) minus delta_i.
The constructor defaults to RMS AveragingMethod and ELEMENT_VERTICES evaluationMode. The default beta value is .05.
Definition at line 60 of file includeLinks/UntangleBetaQualityMetric.hpp.
Constructor & Destructor Documentation
UntangleBetaQualityMetric (double bet = 0.05)
For untangle beta, the constructor defaults to the SUM averaging method, and to the ELEMENT_VERTICES evaluation mode.
Definition at line 53 of file QualityMetric/Untangle/UntangleBetaQualityMetric.cpp.
References QualityMetric::avgMethod, QualityMetric::ELEMENT_BASED, QualityMetric::ELEMENT_VERTICES, QualityMetric::feasible, UntangleBetaQualityMetric::mBeta, MSQ_CHKERR, QualityMetric::NUMERICAL_GRADIENT, QualityMetric::RMS, QualityMetric::set_element_evaluation_mode(), QualityMetric::set_gradient_type(), QualityMetric::set_metric_type(), and QualityMetric::set_name().
 {
   MsqError err;
   set_metric_type(ELEMENT_BASED);
   set_element_evaluation_mode(ELEMENT_VERTICES, err); MSQ_CHKERR(err);
   avgMethod=QualityMetric::RMS;
   feasible=0;
   set_name("Untangle Beta");
   set_gradient_type(QualityMetric::NUMERICAL_GRADIENT);
   mBeta=bet;
 }
virtual ~UntangleBetaQualityMetric () inline virtual
Definition at line 67 of file includeLinks/UntangleBetaQualityMetric.hpp.
         {}
UntangleBetaQualityMetric (double bet = 0.05)
virtual ~UntangleBetaQualityMetric () inline virtual
Definition at line 67 of file src/QualityMetric/Untangle/UntangleBetaQualityMetric.hpp.
         {}
Member Function Documentation
bool evaluate_element (PatchData & pd, MsqMeshEntity * element, double & fval, MsqError & err) virtual
Evaluate the Untangle Beta metric value for an element.
Todo:
This function needs to be modified so that it no longer uses compute_weighted_jacobian. It also needs to set an error whenever sent a 2D element and the surface normal information is not available.
Evaluate the Untangle Beta value of the MsqMeshEntity pointed to by 'element'.
Reimplemented from QualityMetric.
Definition at line 67 of file QualityMetric/Untangle/UntangleBetaQualityMetric.cpp.
References QualityMetric::average_metrics(), PatchData::get_element_index(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), Mesquite::HEXAHEDRON, MSQ_ERRZERO, Mesquite::MSQ_MAX_CAP, Mesquite::MSQ_MAX_NUM_VERT_PER_ENT, MSQ_SETERR, Mesquite::MSQ_SQRT_THREE, Mesquite::MSQ_SQRT_THREE_INV, Mesquite::MSQ_SQRT_TWO, MsqError::NOT_IMPLEMENTED, Mesquite::QUADRILATERAL, Mesquite::TETRAHEDRON, Mesquite::TRIANGLE, UntangleBetaQualityMetric::untangle_function_2d(), and UntangleBetaQualityMetric::untangle_function_3d().
{
   double met_vals[MSQ_MAX_NUM_VERT_PER_ENT];
   fval=MSQ_MAX_CAP;
   const size_t* v_i = element->get_vertex_index_array();
   size_t e_ind = pd.get_element_index(element);
     //only 3 temp_vec will be sent to untangle calculator, but the
     //additional vector3Ds may be needed during the calculations
   Vector3D temp_vec[6];
   MsqVertex *vertices=pd.get_vertex_array(err);  MSQ_ERRZERO(err);
   switch(element->get_element_type()){
     case TRIANGLE:
       temp_vec[0]=vertices[v_i[1]]-vertices[v_i[0]];
       temp_vec[2]=vertices[v_i[2]]-vertices[v_i[0]];
         //make relative to equilateral
       temp_vec[1]=((2*temp_vec[2])-temp_vec[0])*MSQ_SQRT_THREE_INV;
       untangle_function_2d(temp_vec,e_ind,pd,fval,err);
       return true;
     case QUADRILATERAL:
       temp_vec[0]=vertices[v_i[1]]-vertices[v_i[0]];
       temp_vec[1]=vertices[v_i[3]]-vertices[v_i[0]];
       untangle_function_2d(temp_vec,e_ind,pd,met_vals[0],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[2]]-vertices[v_i[1]];
       temp_vec[1]=vertices[v_i[0]]-vertices[v_i[1]];
       untangle_function_2d(temp_vec,e_ind,pd,met_vals[1],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[3]]-vertices[v_i[2]];
       temp_vec[1]=vertices[v_i[1]]-vertices[v_i[2]];
       untangle_function_2d(temp_vec,e_ind,pd,met_vals[2],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[0]]-vertices[v_i[3]];
       temp_vec[1]=vertices[v_i[2]]-vertices[v_i[3]];
       untangle_function_2d(temp_vec,e_ind,pd,met_vals[3],err);  MSQ_ERRZERO(err);
       fval=average_metrics(met_vals, 4, err);  MSQ_ERRZERO(err);
   return true;
     case TETRAHEDRON:
       temp_vec[0]=vertices[v_i[1]]-vertices[v_i[0]];
       temp_vec[3]=vertices[v_i[2]]-vertices[v_i[0]];
       temp_vec[4]=vertices[v_i[3]]-vertices[v_i[0]];
         //transform to equilateral tet
       temp_vec[1]=((2*temp_vec[3])-temp_vec[0])/MSQ_SQRT_THREE;
       temp_vec[2]=((3*temp_vec[4])-temp_vec[0]-temp_vec[3])/
         (MSQ_SQRT_THREE*MSQ_SQRT_TWO);
       untangle_function_3d(temp_vec,fval,err);  MSQ_ERRZERO(err);
       return true;
     case HEXAHEDRON:
         //transform to v_i[0]
       temp_vec[0]=vertices[v_i[1]]-vertices[v_i[0]];
       temp_vec[1]=vertices[v_i[3]]-vertices[v_i[0]];
       temp_vec[2]=vertices[v_i[4]]-vertices[v_i[0]];
       untangle_function_3d(temp_vec,met_vals[0],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[2]]-vertices[v_i[1]];
       temp_vec[1]=vertices[v_i[0]]-vertices[v_i[1]];
       temp_vec[2]=vertices[v_i[5]]-vertices[v_i[1]];
       untangle_function_3d(temp_vec,met_vals[1],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[3]]-vertices[v_i[2]];
       temp_vec[1]=vertices[v_i[1]]-vertices[v_i[2]];
       temp_vec[2]=vertices[v_i[6]]-vertices[v_i[2]];
       untangle_function_3d(temp_vec,met_vals[2],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[0]]-vertices[v_i[3]];
       temp_vec[1]=vertices[v_i[2]]-vertices[v_i[3]];
       temp_vec[2]=vertices[v_i[7]]-vertices[v_i[3]];
       untangle_function_3d(temp_vec,met_vals[3],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[7]]-vertices[v_i[4]];
       temp_vec[1]=vertices[v_i[5]]-vertices[v_i[4]];
       temp_vec[2]=vertices[v_i[0]]-vertices[v_i[4]];
       untangle_function_3d(temp_vec,met_vals[4],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[4]]-vertices[v_i[5]];
       temp_vec[1]=vertices[v_i[6]]-vertices[v_i[5]];
       temp_vec[2]=vertices[v_i[1]]-vertices[v_i[5]];
       untangle_function_3d(temp_vec,met_vals[5],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[5]]-vertices[v_i[6]];
       temp_vec[1]=vertices[v_i[7]]-vertices[v_i[6]];
       temp_vec[2]=vertices[v_i[2]]-vertices[v_i[6]];
       untangle_function_3d(temp_vec,met_vals[6],err);  MSQ_ERRZERO(err);
       temp_vec[0]=vertices[v_i[6]]-vertices[v_i[7]];
       temp_vec[1]=vertices[v_i[4]]-vertices[v_i[7]];
       temp_vec[2]=vertices[v_i[3]]-vertices[v_i[7]];
       untangle_function_3d(temp_vec,met_vals[7],err);  MSQ_ERRZERO(err);
       fval=average_metrics(met_vals, 8, err);  MSQ_ERRZERO(err);
       return true;
     default:
       MSQ_SETERR(err)("Element of incorrect type sent to "
                       "UntangleBetaQualityMetric",
                       MsqError::NOT_IMPLEMENTED);
       return false;
   }// end switch over element type
 }
bool evaluate_element (PatchData & pd, MsqMeshEntity * element, double & fval, MsqError & err) virtual
Evaluate the Untangle Beta metric value for an element.
Todo:
This function needs to be modified so that it no longer uses compute_weighted_jacobian. It also needs to set an error whenever sent a 2D element and the surface normal information is not available.
Reimplemented from QualityMetric.
double get_beta () inline
Function to allow the user to check the value of beta.
Definition at line 82 of file src/QualityMetric/Untangle/UntangleBetaQualityMetric.hpp.
References UntangleBetaQualityMetric::mBeta.
        {return mBeta;}
double get_beta () inline
Function to allow the user to check the value of beta.
Definition at line 82 of file includeLinks/UntangleBetaQualityMetric.hpp.
References UntangleBetaQualityMetric::mBeta.
        {return mBeta;}
void set_beta (double beta_in) inline
Function to allow users to set the beta value after the metric has already been created.
Definition at line 79 of file includeLinks/UntangleBetaQualityMetric.hpp.
References UntangleBetaQualityMetric::mBeta.
        {mBeta = beta_in;}
void set_beta (double beta_in) inline
Function to allow users to set the beta value after the metric has already been created.
Definition at line 79 of file src/QualityMetric/Untangle/UntangleBetaQualityMetric.hpp.
References UntangleBetaQualityMetric::mBeta.
        {mBeta = beta_in;}
void untangle_function_2d (Vector3D temp_vec[], size_t e_ind, PatchData & pd, double & fval, MsqError & err) inline protected
Definition at line 98 of file includeLinks/UntangleBetaQualityMetric.hpp.
References PatchData::get_domain_normal_at_element(), Vector3D::length(), UntangleBetaQualityMetric::mBeta, and MSQ_ERRRTN.
Referenced by UntangleBetaQualityMetric::evaluate_element().
    {
      Vector3D surface_normal;
      pd.get_domain_normal_at_element(e_ind,surface_normal,err); MSQ_ERRRTN(err);
      Vector3D cross_vec=temp_vec[0]*temp_vec[1];
        //cout<<"\nsurface_normal "<<surface_normal;
        //cout<<"\cross_vec "<<cross_vec;
      double temp_var=cross_vec.length();
      if(cross_vec%surface_normal<0.0){
        temp_var*=-1;
      }
      temp_var -= mBeta;
        //cout<<"temp_var == "<<temp_var;
      fval=0.0;
      if(temp_var<0.0){
         fval=fabs(temp_var)-temp_var;
      }
        //  cout<<"\nfval == "<<fval<<"  e_ind "<<e_ind;
    }
void untangle_function_2d (Vector3D temp_vec[], size_t e_ind, PatchData & pd, double & fval, MsqError & err) inline protected
void untangle_function_3d (Vector3D temp_vec[], double & fval, MsqError & err) inline protected
void untangle_function_3d (Vector3D temp_vec[], double & fval, MsqError & err) inline protected
Definition at line 118 of file includeLinks/UntangleBetaQualityMetric.hpp.
References UntangleBetaQualityMetric::mBeta.
Referenced by UntangleBetaQualityMetric::evaluate_element().
    {
      double temp_var=temp_vec[0]%(temp_vec[1]*temp_vec[2]);
      temp_var-=mBeta;
      fval=0.0;
      if(temp_var<0.0){
        fval=fabs(temp_var)-temp_var;
      }
    }
Member Data Documentation
double mBeta private
Definition at line 94 of file includeLinks/UntangleBetaQualityMetric.hpp.
Referenced by UntangleBetaQualityMetric::get_beta(), UntangleBetaQualityMetric::set_beta(), UntangleBetaQualityMetric::untangle_function_2d(), UntangleBetaQualityMetric::untangle_function_3d(), and UntangleBetaQualityMetric::UntangleBetaQualityMetric().
The documentation for this class was generated from the following files:
includeLinks/UntangleBetaQualityMetric.hpp
QualityMetric/Untangle/UntangleBetaQualityMetric.cpp