Rocstar: PartitionPatch Class Reference
PartitionPatch Class Reference
#include <Partition.H>
Public Member Functions
bool ReadPartitionPatchASCII (ifstream &Inf)
bool WritePartitionPatchASCII (ofstream &Ouf)
bool ReadPartitionPatch (ifstream &Inf)
PartitionPatch ()
PartitionPatch (const GEM_DomainBoundary &db)
Public Member Functions inherited from GEM_DomainBoundary
unsigned int NNodes (void)
bool SetSolverDataBlock (const std::string &wname, double *cell_data, int nval_cells, double *node_data, int nval_nodes)
GEM_DomainBoundary (const GEM_DomainBoundary &db)
GEM_DomainBoundary ()
GEM_DomainBoundary & operator= (const GEM_DomainBoundary &db)
bool debug (bool s=true)
void report ()
void PopulateSurfaceArrays (const std::vector< double > &, unsigned int)
bool Register_com_surfmesh (const std::string &wname)
void Create_com_surfsoln (const std::string &wname, const std::string &fname, std::vector< double > &fvec, unsigned int ncomp, const std::string &unit)
Public Attributes
unsigned int _nfaces
unsigned int _ngfaces
vector< unsigned int > _faceconn
Public Attributes inherited from GEM_DomainBoundary
unsigned int _id
unsigned int _ngtri
unsigned int _ngquad
unsigned int _nnodes
std::vector< unsigned int > _triconn
std::vector< unsigned int > _quadconn
std::vector< double > surface_coordinates
unsigned int surface_ngnodes
std::vector< unsigned int > surface_tri
std::vector< unsigned int > surface_quad
GEM_UserData _data
GEM_UserData _solver_data
bool _debug
std::ostream * _out
int pane_id
Detailed Description
Definition at line 68 of file Partition.H.
Constructor & Destructor Documentation
PartitionPatch () inline
Definition at line 76 of file Partition.H.
References _nfaces, and _ngfaces.
     : GEM_DomainBoundary()
   {
     _nfaces = 0;
     _ngfaces = 0;
   };
PartitionPatch (const GEM_DomainBoundary & db) inline
Definition at line 82 of file Partition.H.
References _nfaces, _ngfaces, GEM_DomainBoundary::_ngquad, GEM_DomainBoundary::_ngtri, GEM_DomainBoundary::_quadconn, and GEM_DomainBoundary::_triconn.
     : GEM_DomainBoundary(db)
   {
     _nfaces  = db._triconn.size()/3 + db._quadconn.size()/4;
     _ngfaces = db._ngtri + db._ngquad;
   };
Member Function Documentation
bool ReadPartitionPatch (ifstream & Inf)
Definition at line 42 of file Partition.C.
Referenced by Partition::ReadPartitionPatches().
 {
   int buf[3];
   Inf.read(reinterpret_cast<char *>(buf),12);
   _id      = -buf[0];
   _nfaces  = buf[1];
   _ngfaces = buf[2];
   //  _faceconn.resize(4*_nfaces);
   //  Inf.read(reinterpret_cast<char *>(&_faceconn[0]),4 * nfaces);
   // skip the face connectivity until Bill tell us whats up with it
   Inf.seekg(16 * _nfaces,ios::cur);
   return(true);
 }
bool ReadPartitionPatchASCII (ifstream & Inf)
Definition at line 57 of file Partition.C.
Referenced by Partition::ReadPartitionPatchesASCII().
 {
   _ngtri = 0;
   _ngquad = 0;
   Inf >> _id >> _nfaces >> _ngfaces;
   unsigned int nfaces_accum = 0;
   nfaces_accum += _nfaces;
   _ngtri = _ngfaces;
   _id *= -1;
   _triconn.resize(3*_nfaces);
   unsigned int face = 0;
   while(face < _nfaces){
     unsigned int node1,node2,node3;
     Inf >> node1 >> node2 >> node3;
     _triconn[face*3]   = node1;
     _triconn[face*3+1] = node2;
     _triconn[face*3+2] = node3;
     face++;
   }
   Inf >> _nfaces >> _ngfaces;
   nfaces_accum += _nfaces;
   _ngquad = _ngfaces;
   _quadconn.resize(4*_nfaces);
   face = 0;
   while(face < _nfaces){
     unsigned int node1,node2,node3,node4;
     Inf >> node1 >> node2 >> node3 >> node4;
     _quadconn[face*4]   = (node1);
     _quadconn[face*4+1] = (node2);
     _quadconn[face*4+2] = (node3);
     _quadconn[face*4+3] = (node4);
     face++;
   }
   _nfaces = nfaces_accum;
   _ngfaces = _ngquad + _ngtri;
   return(true);
 }
bool WritePartitionPatchASCII (ofstream & Ouf)
Definition at line 96 of file Partition.C.
Referenced by Partition::WritePartitionPatchesASCII().
 {
   unsigned int nfaces = _triconn.size()/3;
   unsigned int face = 0;
   Ouf << setw(12) << (_id < 0 ? _id : -1*_id) << endl
       << setw(12) << nfaces << endl
       << setw(12) << _ngtri << endl;
   while(face < nfaces){
     Ouf << setw(12) << _triconn[face*3]
         << setw(12) << _triconn[face*3+1]
         << setw(12) << _triconn[face*3+2] << endl;
     face++;
   }
   nfaces = _quadconn.size()/4;
   face = 0;
   Ouf << setw(12) << nfaces << endl
       << setw(12) << _ngquad << endl;
   while(face < nfaces){
     Ouf << setw(12) << _quadconn[face*4]
         << setw(12) << _quadconn[face*4+1]
         << setw(12) << _quadconn[face*4+2]
         << setw(12) << _quadconn[face*4+3] << endl;
     face++;
   }
   return(true);
 }
Member Data Documentation
vector<unsigned int> _faceconn
Definition at line 72 of file Partition.H.
unsigned int _nfaces
Definition at line 70 of file Partition.H.
Referenced by PartitionPatch().
unsigned int _ngfaces
Definition at line 71 of file Partition.H.
Referenced by PartitionPatch().
The documentation for this class was generated from the following files:
Partition.H
Partition.C