Rocstar: rflu_modreadwriteflow Module Reference
rflu_modreadwriteflow Module Reference
Public Member Functions
subroutine, public rflu_readflowwrapper (pRegion)
subroutine, public rflu_writeflowwrapper (pRegion)
Private Member Functions
subroutine rflu_readflowascii (pRegion)
subroutine rflu_readflowbinary (pRegion)
subroutine rflu_writeflowascii (pRegion)
subroutine rflu_writeflowbinary (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadWriteFlow.F90,v $ $Revision: 1.13 $'
Detailed Description
Definition at line 39 of file RFLU_ModReadWriteFlow.F90.
Member Function/Subroutine Documentation
subroutine rflu_readflowascii (type(t_region), pointer pRegion) private
Definition at line 97 of file RFLU_ModReadWriteFlow.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), rflu_getcvloc(), and Attribute::status().
Referenced by rflu_readflowwrapper().
subroutine rflu_readflowbinary (type(t_region), pointer pRegion) private
Definition at line 566 of file RFLU_ModReadWriteFlow.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), rflu_getcvloc(), and Attribute::status().
Referenced by rflu_readflowwrapper().
subroutine, public rflu_readflowwrapper (type(t_region), pointer pRegion)
Definition at line 1035 of file RFLU_ModReadWriteFlow.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_rflu_readsolutionascii(), plag_rflu_readsolutionbinary(), moderror::registerfunction(), rflu_modrocstario::rflu_genx_decidereadfile(), rflu_modrocstario::rflu_genx_getdataflow(), rflu_readflowascii(), rflu_readflowbinary(), spec_rflu_modreadwritevars::spec_rflu_readcvascii(), spec_rflu_modreadwritevars::spec_rflu_readcvbinary(), spec_rflu_modreadwritevars::spec_rflu_readeevascii(), spec_rflu_modreadwritevars::spec_rflu_readeevbinary(), turb_initsolution(), turb_rflu_modrocstaradmin::turb_rflu_genxgetdata(), turb_rflu_readsolutionascii(), and turb_rflu_readsolutionbinary().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rfluconv(), and rfluinit().
subroutine rflu_writeflowascii (type(t_region), pointer pRegion) private
Definition at line 1218 of file RFLU_ModReadWriteFlow.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), rflu_getcvloc(), and Attribute::status().
Referenced by rflu_writeflowwrapper().
subroutine rflu_writeflowbinary (type(t_region), pointer pRegion) private
Definition at line 1531 of file RFLU_ModReadWriteFlow.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), rflu_getcvloc(), and Attribute::status().
Referenced by rflu_writeflowwrapper().
subroutine, public rflu_writeflowwrapper (type(t_region), pointer pRegion)
Definition at line 1842 of file RFLU_ModReadWriteFlow.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_rflu_writesolutionascii(), plag_rflu_writesolutionbinary(), moderror::registerfunction(), rflu_modrocstario::rflu_genx_decidewritefile(), rflu_modrocstario::rflu_genx_putdataflow(), rflu_writeflowascii(), rflu_writeflowbinary(), spec_rflu_modreadwritevars::spec_rflu_writecvascii(), spec_rflu_modreadwritevars::spec_rflu_writecvbinary(), spec_rflu_modreadwritevars::spec_rflu_writeeevascii(), spec_rflu_modreadwritevars::spec_rflu_writeeevbinary(), turb_rflu_writesolutionascii(), and turb_rflu_writesolutionbinary().
Referenced by rflu_endflowsolver(), rflu_mergepostprocessregions(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_timestepping(), rfluconv(), and rfluinit().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadWriteFlow.F90,v $ $Revision: 1.13 $' private
Definition at line 65 of file RFLU_ModReadWriteFlow.F90.
The documentation for this module was generated from the following file:
RFLU_ModReadWriteFlow.F90