Rocstar: RayS2< FT > Class Template Reference
RayS2< FT > Class Template Reference
#include <RayS2.h>
Public Member Functions
RayS2 ()
RayS2 (const PointS2< FT > &sp, const PointS2< FT > &secondp)
RayS2 (const PointS2< FT > &sp, const DirectionS2< FT > &d)
bool operator== (const RayS2< FT > &r) const
bool operator!= (const RayS2< FT > &r) const
const PointS2< FT > & start () const
const PointS2< FT > & source () const
PointS2< FT > point (int i) const
PointS2< FT > second_point () const
DirectionS2< FT > direction () const
LineS2< FT > supporting_line () const
RayS2< FT > opposite () const
RayS2< FT > transform (const Aff_transformationS2< FT > &t) const
bool is_horizontal () const
bool is_vertical () const
bool is_degenerate () const
bool has_on (const PointS2< FT > &p) const
bool collinear_has_on (const PointS2< FT > &p) const
Public Attributes
PointS2< FT > s
PointS2< FT > t
Detailed Description
template<class FT>
class RayS2< FT >
Definition at line 60 of file RayS2.h.
Constructor & Destructor Documentation
RayS2 () inline
Definition at line 63 of file RayS2.h.
 {};
RayS2 (const PointS2< FT > & sp, const PointS2< FT > & secondp) inline
Definition at line 64 of file RayS2.h.
                                                     : s(sp), t(secondp) {};
CGAL_KERNEL_CTOR_INLINE RayS2 (const PointS2< FT > & sp, const DirectionS2< FT > & d)
Definition at line 99 of file RayS2.h.
References s, and DirectionS2< FT >::vector().
 { s = sp; t = sp + d.vector(); }
Member Function Documentation
CGAL_KERNEL_MEDIUM_INLINE bool collinear_has_on (const PointS2< FT > & p) const
Definition at line 201 of file RayS2.h.
References compare_x(), compare_y(), LARGER, and SMALLER.
 {
     switch(compare_x(source(), second_point())){
     case SMALLER:
         return compare_x(source(), p) != LARGER;
     case LARGER:
         return compare_x(p, source()) != LARGER;
     default:
         switch(compare_y(source(), second_point())){
         case SMALLER:
             return compare_y(source(), p) != LARGER;
         case LARGER:
             return compare_y(p, source()) != LARGER;
         default:
             return true; // p == source()
         }
     }
 }
DirectionS2< FT > direction () const inline
Definition at line 149 of file RayS2.h.
Referenced by RayS2< FT >::operator==().
 { return DirectionS2<FT>(  second_point() - source() ); }
CGAL_KERNEL_INLINE bool has_on (const PointS2< FT > & p) const
Definition at line 191 of file RayS2.h.
References collinear().
 {
   return ( p == source()
            || ( collinear(source(), p, second_point())
           && ( DirectionS2<FT>(p - source()) == direction() )));
 }
CGAL_KERNEL_INLINE bool is_degenerate () const
Definition at line 185 of file RayS2.h.
 { return (source() == second_point()); }
CGAL_KERNEL_INLINE bool is_horizontal () const
Definition at line 173 of file RayS2.h.
References y.
 { return (source().y() ==  second_point().y()); }
CGAL_KERNEL_INLINE bool is_vertical () const
Definition at line 179 of file RayS2.h.
References x.
 { return  (source().x() == second_point().x()); }
bool operator!= (const RayS2< FT > & r) const
Definition at line 110 of file RayS2.h.
 { return !(*this == r); }
CGAL_KERNEL_INLINE bool operator== (const RayS2< FT > & r) const
Definition at line 105 of file RayS2.h.
References RayS2< FT >::direction(), and RayS2< FT >::source().
 { return ((source() == r.source()) && (direction() == r.direction()) ); }
RayS2< FT > opposite () const inline
Definition at line 159 of file RayS2.h.
 { return RayS2<FT>( source(), - direction() ); }
CGAL_KERNEL_INLINE PointS2< FT > point (int i) const
Definition at line 134 of file RayS2.h.
References CGAL_kernel_precondition, and s.
 {
   CGAL_kernel_precondition( i >= 0 );
   if (i == 0)
     return s;
   if (i == 1)
     return t;
   return source() + FT(i) * (second_point() - source());
 }
PointS2< FT > second_point () const inline
Definition at line 128 of file RayS2.h.
Referenced by LineS2< FT >::LineS2().
 { return t; }
const PointS2< FT > & source () const inline
Definition at line 122 of file RayS2.h.
References s.
Referenced by RayS2< FT >::operator==().
 { return s; }
const PointS2< FT > & start () const inline
Definition at line 116 of file RayS2.h.
References s.
Referenced by LineS2< FT >::LineS2().
 { return s; }
LineS2< FT > supporting_line () const inline
Definition at line 154 of file RayS2.h.
 { return LineS2<FT>(*this); }
CGAL_KERNEL_INLINE RayS2< FT > transform (const Aff_transformationS2< FT > & t) const
Definition at line 166 of file RayS2.h.
References Aff_transformationS2< FT >::transform().
 { return RayS2<FT>(t.transform(source()), t.transform(second_point())); }
Member Data Documentation
PointS2<FT> s
Definition at line 92 of file RayS2.h.
PointS2<FT> t
Definition at line 93 of file RayS2.h.
The documentation for this class was generated from the following file:
RayS2.h