Rocstar: CloneAttribute Class Reference
CloneAttribute Class Reference
#include <Agent.h>
Public Member Functions
CloneAttribute (Agent *ag, int cond, std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_=1, const char *ptnname_=0, int val_=0)
void create (std::string bufname)
Public Member Functions inherited from AttributeBase
AttributeBase (Agent *ag, std::string target_window_, std::string attr_)
virtual ~AttributeBase ()
virtual void assign (std::string bufname)
Protected Attributes
std::string parent_window
std::string parent_attr
int wg
const char * ptnname
int val
int condition
Additional Inherited Members
Public Attributes inherited from AttributeBase
Agent * agent
std::string target_window
std::string attr
Detailed Description
Definition at line 71 of file Agent.h.
Constructor & Destructor Documentation
CloneAttribute (Agent * ag, int cond, std::string target_window_, std::string attr_, std::string parent_window_, std::string parent_attr_, int wg_ = 1, const char * ptnname_ = 0, int val_ = 0)
Definition at line 129 of file Agent.C.
References ptnname.
                                                                     :
                 AttributeBase(ag, target_window_, attr_),
                 parent_window(parent_window_), parent_attr(parent_attr_),
                 wg(wg_), val(val_), condition(cond)
 {
   ptnname = ptnname_?strdup(ptnname_):NULL;
 }
Member Function Documentation
void create (std::string bufname) virtual
Reimplemented from AttributeBase.
Definition at line 140 of file Agent.C.
References AttributeBase::agent, AttributeBase::attr, COM_clone_attribute(), COM_get_attribute(), COM_get_attribute_handle(), condition, Agent::get_surface_window(), MAN_DEBUG, MPI_COMM_WORLD, parent_attr, parent_window, ptnname, AttributeBase::target_window, val, and wg.
 {
   if (parent_window=="") {   // filling
     parent_window = agent->get_surface_window();
   }
   if (COM_get_attribute_handle( bufname+attr) > 0) {
     char loc1, loc2;
     int type1, type2;
     int ncomp1, ncomp2;
     std::string unit1, unit2;
     COM_get_attribute( bufname+attr, &loc1, &type1, &ncomp1, &unit1);
     COM_get_attribute( parent_window+parent_attr, &loc2, &type2, &ncomp2, &unit2);
     if (loc1 != loc2 || type1 != type2 || ncomp1 != ncomp2 || unit1 != unit2) {
       std::cerr << "Rocstar Error: CloneAttribute::create(): Could not create " << target_window+attr << " in two different ways " << std::endl;
       MPI_Abort(MPI_COMM_WORLD, -1);
     }
     else {
       MAN_DEBUG(3, ("CloneAttribute::create: %s%s %s%s condition:%d handle:%d SKIPPED.\n", bufname.c_str(), attr.c_str(), parent_window.c_str(), parent_attr.c_str(), condition, COM_get_attribute_handle( parent_window+parent_attr)));
       return;
     }
   }
   MAN_DEBUG(3, ("CloneAttribute::create: %s%s %s%s condition:%d handle:%d.\n", bufname.c_str(), attr.c_str(), parent_window.c_str(), parent_attr.c_str(), condition, COM_get_attribute_handle( parent_window+parent_attr)));
   if (condition)
     if (COM_get_attribute_handle( parent_window+parent_attr) <= 0)  return;
   if (ptnname) {
     if (ptnname[0] == '.')
       ptnname = strdup((agent->get_surface_window() + ptnname).c_str());
   }
   COM_clone_attribute( bufname+attr, parent_window+parent_attr, wg, ptnname, val);
 }
Member Data Documentation
int condition protected
Definition at line 78 of file Agent.h.
Referenced by create().
std::string parent_attr protected
Definition at line 74 of file Agent.h.
Referenced by create().
std::string parent_window protected
Definition at line 73 of file Agent.h.
Referenced by create().
const char* ptnname protected
Definition at line 76 of file Agent.h.
Referenced by CloneAttribute(), and create().
int val protected
Definition at line 77 of file Agent.h.
Referenced by create().
int wg protected
Definition at line 75 of file Agent.h.
Referenced by create().
The documentation for this class was generated from the following files:
Agent.h
Agent.C