Rocstar: rflu_modboundlists Module Reference
rflu_modboundlists Module Reference
Public Member Functions
subroutine, public rflu_buildbcellmlist (pRegion)
subroutine, public rflu_buildbfaceloclists (pRegion)
subroutine, public rflu_buildbfacesortlists (pRegion)
subroutine, public rflu_buildbvertexlists (pRegion)
subroutine, public rflu_buildbvertexmlist (pRegion)
subroutine, public rflu_createbcellmlist (pRegion)
subroutine, public rflu_createbfaceloclists (pRegion)
subroutine, public rflu_createbfacesortlists (pRegion)
subroutine, public rflu_createbvertexlists (pRegion)
subroutine, public rflu_createbvertexmlist (pRegion)
subroutine, public rflu_denumberbfacelists (pRegion)
subroutine, public rflu_destroybcellmlist (pRegion)
subroutine, public rflu_destroybfaceloclists (pRegion)
subroutine, public rflu_destroybfacesortlists (pRegion)
subroutine, public rflu_destroybvertexlists (pRegion)
subroutine, public rflu_destroybvertexmlist (pRegion)
subroutine, public rflu_nullifybcellmlist (pRegion)
subroutine, public rflu_nullifybfaceloclists (pRegion)
subroutine, public rflu_nullifybfacesortlists (pRegion)
subroutine, public rflu_nullifybvertexlists (pRegion)
subroutine, public rflu_nullifybvertexmlist (pRegion)
subroutine, public rflu_renumberbfacelists (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModBoundLists.F90,v $ $Revision: 1.33 $'
Detailed Description
Definition at line 42 of file RFLU_ModBoundLists.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildbcellmlist (type(t_region), pointer pRegion)
Definition at line 123 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), modsortsearch::quicksortinteger(), moderror::registerfunction(), and modsortsearch::simplifysortedintegers().
Referenced by rflupart().
subroutine, public rflu_buildbfaceloclists (type(t_region), pointer pRegion)
Definition at line 244 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modrenumberlist::rflu_renumberlist().
Referenced by rflu_modrocstaradmin::rflu_genx_buildgridsurf().
subroutine, public rflu_buildbfacesortlists (type(t_region), pointer pRegion)
Definition at line 356 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), modsortsearch::quicksortinteger(), and moderror::registerfunction().
subroutine, public rflu_buildbvertexlists (type(t_region), pointer pRegion)
Definition at line 452 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), key, modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modhashtable::rflu_createhashtable(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modhashtable::rflu_hashbuildkey1(), and rflu_modhashtable::rflu_hashvertex().
Referenced by rflu_modtetmesh::rflu_convrocflu2tetmesh(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_buildbvertexmlist (type(t_region), pointer pRegion)
Definition at line 771 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::mergesortedintegers(), and moderror::registerfunction().
subroutine, public rflu_createbcellmlist (type(t_region), pointer pRegion)
Definition at line 974 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybcellmlist().
Referenced by rflupart().
subroutine, public rflu_createbfaceloclists (type(t_region), pointer pRegion)
Definition at line 1079 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybfaceloclists().
Referenced by rflu_modrocstaradmin::rflu_genx_creategridsurf().
subroutine, public rflu_createbfacesortlists (type(t_region), pointer pRegion)
Definition at line 1188 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybfacesortlists().
subroutine, public rflu_createbvertexlists (type(t_region), pointer pRegion)
Definition at line 1287 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybvertexlists().
Referenced by rflu_modtetmesh::rflu_convrocflu2tetmesh(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_createbvertexmlist (type(t_region), pointer pRegion)
Definition at line 1419 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybvertexmlist().
subroutine, public rflu_denumberbfacelists (type(t_region), pointer pRegion)
Definition at line 1522 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modrenumberlist::rflu_denumberlist().
Referenced by rflu_modtetmesh::rflu_convrocflu2tetmesh().
subroutine, public rflu_destroybcellmlist (type(t_region), pointer pRegion)
Definition at line 1690 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybcellmlist().
Referenced by rflupart().
subroutine, public rflu_destroybfaceloclists (type(t_region), pointer pRegion)
Definition at line 1785 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybfaceloclists().
Referenced by rflu_modrocstaradmin::rflu_genx_destroygridsurf().
subroutine, public rflu_destroybfacesortlists (type(t_region), pointer pRegion)
Definition at line 1895 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybfacesortlists().
subroutine, public rflu_destroybvertexlists (type(t_region), pointer pRegion)
Definition at line 1994 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybvertexlists().
Referenced by rflu_modtetmesh::rflu_convrocflu2tetmesh(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon2(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_destroybvertexmlist (type(t_region), pointer pRegion)
Definition at line 2092 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybvertexmlist().
subroutine, public rflu_nullifybcellmlist (type(t_region), pointer pRegion)
Definition at line 2187 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createbcellmlist(), and rflu_destroybcellmlist().
subroutine, public rflu_nullifybfaceloclists (type(t_region), pointer pRegion)
Definition at line 2270 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createbfaceloclists(), and rflu_destroybfaceloclists().
subroutine, public rflu_nullifybfacesortlists (type(t_region), pointer pRegion)
Definition at line 2362 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createbfacesortlists(), and rflu_destroybfacesortlists().
subroutine, public rflu_nullifybvertexlists (type(t_region), pointer pRegion)
Definition at line 2454 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createbvertexlists(), and rflu_destroybvertexlists().
subroutine, public rflu_nullifybvertexmlist (type(t_region), pointer pRegion)
Definition at line 2543 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createbvertexmlist(), and rflu_destroybvertexmlist().
subroutine, public rflu_renumberbfacelists (type(t_region), pointer pRegion)
Definition at line 2626 of file RFLU_ModBoundLists.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modrenumberlist::rflu_renumberlist().
Referenced by rflu_modtetmesh::rflu_convrocflu2tetmesh(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rfluconv(), rfluinit(), rflupart(), and rflupick().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModBoundLists.F90,v $ $Revision: 1.33 $' private
Definition at line 87 of file RFLU_ModBoundLists.F90.
The documentation for this module was generated from the following file:
RFLU_ModBoundLists.F90