Rocstar: bcReader Class Reference
bcReader Class Reference
Public Member Functions
bcReader (FILE *in_)
~bcReader ()
bool read (int *dest)
bool read (blockSpan &ret)
bool read (blockDim &d)
bool skipLine (void)
Private Attributes
FILE * in
Detailed Description
Definition at line 70 of file readinp.cpp.
Constructor & Destructor Documentation
bcReader (FILE * in_) inline
Definition at line 73 of file readinp.cpp.
                 :in(in_)
         {
         }
~bcReader () inline
Definition at line 78 of file readinp.cpp.
References cimg_library::cimg::fclose(), and in.
 {fclose(in);}
Member Function Documentation
bool read (int * dest) inline
Definition at line 81 of file readinp.cpp.
References in.
Referenced by read(), and readBoundaries().
{
                 int count=fscanf(in,"%d",dest);
                 return (count==1);
         }
bool read (blockSpan & ret) inline
Definition at line 86 of file readinp.cpp.
References i, and read().
{
                 blockLoc start,end;
                 for (int i=0;i<3;i++) {
                         if (!(read(&start[i]) && read(&end[i])))
                                 return false;
                         //Fix up some oddities in the .inp files
                         if (end[i]<0) end[i]=-end[i];
                         if (start[i]<0) start[i]=-start[i];
                         //Make zero-based
                         end[i]--; start[i]--;
                         if (end[i]<start[i])
                         { //Start and end are backwards for this axis:
                                 int tmp=end[i];
                                 end[i]=start[i];
                                 start[i]=tmp;
                         }
                         end[i]++; //Make end into c-style
                 }
                 ret=blockSpan(start,end);
                 return true;
         }
bool read (blockDim & d) inline
Definition at line 110 of file readinp.cpp.
References i, and read().
{
                 for (int i=0;i<3;i++)
                         if (!read(&d[i]))
                                 return false;
                 return true;
         }
bool skipLine (void) inline
Definition at line 117 of file readinp.cpp.
References in.
Referenced by readBoundaries().
{
                 char str[1024];
                 return NULL!=fgets(str,1024,in);
         }
Member Data Documentation
FILE* in private
Definition at line 71 of file readinp.cpp.
Referenced by read(), skipLine(), and ~bcReader().
The documentation for this class was generated from the following file:
readinp.cpp