Rocstar: rflu_modprobes Module Reference
rflu_modprobes Module Reference
Public Member Functions
subroutine, public rflu_closeprobefiles (pRegion)
logical function, public rflu_decidewriteprobes (global)
subroutine, public rflu_findprobecells (pRegion)
subroutine, public rflu_openprobefiles (pRegion)
subroutine, public rflu_printprobeinfo (global)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModProbes.F90,v $ $Revision: 1.6 $'
Detailed Description
Definition at line 39 of file RFLU_ModProbes.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_closeprobefiles (type (t_region), pointer pRegion)
Definition at line 92 of file RFLU_ModProbes.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_endflowsolver(), rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().
logical function, public rflu_decidewriteprobes (type(t_global), pointer global)
Definition at line 174 of file RFLU_ModProbes.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
subroutine, public rflu_findprobecells (type(t_region), pointer pRegion)
Definition at line 272 of file RFLU_ModProbes.F90.
References moderror::deregisterfunction(), moderror::errorstop(), min(), moderror::registerfunction(), rflu_modoctree::rflu_buildoctree(), rflu_modoctree::rflu_createoctree(), rflu_modoctree::rflu_destroyoctree(), rflu_modincelltest::rflu_ict_testincell(), rflu_modoctree::rflu_queryoctree(), rflu_modgeometrytools::rflu_testinboundbox(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_postprocessregionscommon1(), and rflu_timestepping().
subroutine, public rflu_openprobefiles (type (t_region), pointer pRegion)
Definition at line 450 of file RFLU_ModProbes.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), modtools::floatless(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().
subroutine, public rflu_printprobeinfo (type(t_global), pointer global)
Definition at line 638 of file RFLU_ModProbes.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModProbes.F90,v $ $Revision: 1.6 $' private
Definition at line 62 of file RFLU_ModProbes.F90.
The documentation for this module was generated from the following file:
RFLU_ModProbes.F90