Rocstar: RayS3< FT > Class Template Reference
RayS3< FT > Class Template Reference
#include <RayS3.h>
Public Member Functions
RayS3 ()
RayS3 (const PointS3< FT > &sp, const PointS3< FT > &secondp)
RayS3 (const PointS3< FT > &sp, const DirectionS3< FT > &d)
bool operator== (const RayS3< FT > &r) const
bool operator!= (const RayS3< FT > &r) const
PointS3< FT > start () const
PointS3< FT > source () const
PointS3< FT > second_point () const
PointS3< FT > point (int i) const
DirectionS3< FT > direction () const
LineS3< FT > supporting_line () const
RayS3 opposite () const
RayS3 transform (const Aff_transformationS3< FT > &t) const
bool is_degenerate () const
bool has_on (const PointS3< FT > &p) const
bool collinear_has_on (const PointS3< FT > &p) const
Public Attributes
PointS3< FT > e0
PointS3< FT > e1
Detailed Description
template<class FT>
class RayS3< FT >
Definition at line 59 of file RayS3.h.
Constructor & Destructor Documentation
RayS3 () inline
Definition at line 62 of file RayS3.h.
 {}
RayS3 (const PointS3< FT > & sp, const PointS3< FT > & secondp)
Definition at line 91 of file RayS3.h.
 {
   e0 = sp;
   e1 = secondp;
 }
RayS3 (const PointS3< FT > & sp, const DirectionS3< FT > & d)
Definition at line 99 of file RayS3.h.
References DirectionS3< FT >::vector().
 {
   e0 = sp;
   e1 = sp + d.vector();
 }
Member Function Documentation
bool collinear_has_on (const PointS3< FT > & p) const inline
Definition at line 200 of file RayS3.h.
References CGAL_kernel_exactness_precondition, collinear(), compare_x(), compare_y(), compare_z(), and EQUAL.
 {
   CGAL_kernel_exactness_precondition( collinear(source(), p, second_point()) );
   Comparison_result cx = compare_x(source(), second_point());
   if (cx != EQUAL)
     return cx != compare_x(p, source());
   Comparison_result cy = compare_y(source(), second_point());
   if (cy != EQUAL)
     return cy != compare_y(p, source());
   Comparison_result cz = compare_z(source(), second_point());
   if (cz != EQUAL)
     return cz != compare_z(p, source());
   return true; // p == source()
 }
DirectionS3< FT > direction () const inline
Definition at line 155 of file RayS3.h.
Referenced by RayS3< FT >::operator==().
 { return DirectionS3<FT>( second_point() - source() ); }
bool has_on (const PointS3< FT > & p) const
Definition at line 182 of file RayS3.h.
References collinear().
 {
   return (p == source()) ||
          ( collinear(source(), p, second_point())
            && ( DirectionS3<FT>(p - source()) == direction() ));
 }
bool is_degenerate () const inline
Definition at line 193 of file RayS3.h.
 { return source() == second_point(); }
bool operator!= (const RayS3< FT > & r) const inline
Definition at line 116 of file RayS3.h.
 { return !(*this == r); }
bool operator== (const RayS3< FT > & r) const inline
Definition at line 109 of file RayS3.h.
References RayS3< FT >::direction(), and RayS3< FT >::source().
 { return (source() == r.source()) && (direction() == r.direction()); }
RayS3< FT > opposite () const inline
Definition at line 169 of file RayS3.h.
 { return RayS3<FT>( source(), - direction() ); }
PointS3< FT > point (int i) const
Definition at line 139 of file RayS3.h.
References CGAL_kernel_precondition.
 {
   CGAL_kernel_precondition( i >= 0 );
   if (i == 0)
     return e0;
   if (i == 1)
     return e1;
   return source() + FT(i) * (second_point() - source());
 }
PointS3< FT > second_point () const
Definition at line 133 of file RayS3.h.
Referenced by LineS3< FT >::LineS3(), and PlaneS3< FT >::PlaneS3().
 { return e1; }
PointS3< FT > source () const
Definition at line 128 of file RayS3.h.
Referenced by RayS3< FT >::operator==().
 { return e0; }
PointS3< FT > start () const
Definition at line 122 of file RayS3.h.
Referenced by LineS3< FT >::LineS3(), and PlaneS3< FT >::PlaneS3().
 { return e0; }
LineS3< FT > supporting_line () const inline
Definition at line 162 of file RayS3.h.
 { return LineS3<FT>(*this); }
RayS3< FT > transform (const Aff_transformationS3< FT > & t) const inline
Definition at line 176 of file RayS3.h.
References Aff_transformationS3< FT >::transform().
 { return RayS3<FT>(t.transform(source()), t.transform(second_point())); }
Member Data Documentation
PointS3<FT> e0
Definition at line 85 of file RayS3.h.
PointS3<FT> e1
Definition at line 86 of file RayS3.h.
The documentation for this class was generated from the following file:
RayS3.h