Rocstar: rflu_modmergeregions Module Reference
rflu_modmergeregions Module Reference
Public Member Functions
subroutine, public rflu_merg_mergegrid (pRegion, pRegionSerial)
subroutine, public rflu_merg_mergepatchcoeffs (pRegion, pRegionSerial)
subroutine, public rflu_merg_mergesolwrapper (pRegion, pRegionSerial)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModMergeRegions.F90,v $ $Revision: 1.10 $'
Detailed Description
Definition at line 39 of file RFLU_ModMergeRegions.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_merg_mergegrid (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 94 of file RFLU_ModMergeRegions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions().
subroutine, public rflu_merg_mergepatchcoeffs (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 374 of file RFLU_ModMergeRegions.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions().
subroutine, public rflu_merg_mergesolwrapper (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 492 of file RFLU_ModMergeRegions.F90.
References moderror::deregisterfunction(), plag_moddatastruct::plag_dstr_mergeparticlewrapper(), moderror::registerfunction(), rflu_modcopydata::rflu_copy_celldatap2s_r2d(), and rflu_modcopydata::rflu_copy_celldatap2s_r3d().
Referenced by rflu_mergepostprocessregions().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModMergeRegions.F90,v $ $Revision: 1.10 $' private
Definition at line 61 of file RFLU_ModMergeRegions.F90.
The documentation for this module was generated from the following file:
RFLU_ModMergeRegions.F90