Rocstar: Aspect_Metric_3 Class Reference
Aspect_Metric_3 Class Reference
3D Aspect Ratios Metric Class
#include <Geometric_Metrics_3.h>
Public Member Functions
Aspect_Metric_3 ()
Initialize a 3D Aspect Metric.
virtual void compute (double atts[]) const
Calculate the metric value on this element.
double maxValue () const
Get the maximum value for this metric.
double minValue () const
Get the minimum value for this metric.
void getAspects (double &R, double &r, double &l)
Get the geometric aspects.
Public Member Functions inherited from Geo_Metric_Base_3
Geo_Metric_Base_3 ()
virtual ~Geo_Metric_Base_3 ()
virtual void initialize (Vector_3< double > n[], int type)
Initialize a 3D Geometric Metric by nodal coords and element type.
virtual void initialize (Element_node_enumerator &ene)
Initialize a 3D Geometric Metric by Element_node_enumerator.
Public Member Functions inherited from Metric
Metric ()
virtual ~Metric ()
Additional Inherited Members
Protected Member Functions inherited from Geo_Metric_Base_3
void compute_angles (double &min, double &max) const
Compute min and max dihedral angles.
void compute_aspects (double &R, double &r, double &l) const
Compute circumradius, inradius, and shortest edge length.
Protected Attributes inherited from Geo_Metric_Base_3
std::vector< Vector_3< double > > v
int _type
const COM::Pane * _ene_pane
int _ene_i
Detailed Description
3D Aspect Ratios Metric Class
Definition at line 107 of file Geometric_Metrics_3.h.
Constructor & Destructor Documentation
Aspect_Metric_3 () inline
Initialize a 3D Aspect Metric.
Definition at line 111 of file Geometric_Metrics_3.h.
 {}
Member Function Documentation
void compute (double atts[]) const virtual
Calculate the metric value on this element.
Parameters
atts[] Computed value(s) placed here.
Note that R/r and R/l are only implemented for simplical elements. This method will return -1 for both metrics if used on a hexahedron.
Implements Metric.
Definition at line 261 of file Geometric_Metrics_3.C.
Referenced by main().
{
   if (_type == COM::Connectivity::HEX8) {
     atts[0] = -1;
     atts[1] = -1;
   }
   else{
     double R, r, l;
     compute_aspects(R,r,l);
     atts[0] = (r/R)*3.0;
     atts[1] = (l/R)*.61237243569579447;
     if(atts[0] > 1.0)
       atts[0] = 1.0;
     if(atts[1] > 1.0)
       atts[0] = 1.0;
   }
 }
void getAspects (double & R, double & r, double & l) inline
Get the geometric aspects.
Definition at line 130 of file Geometric_Metrics_3.h.
References Geo_Metric_Base_3::compute_aspects().
Referenced by Rocmop::add_aspect_ratios().
{
     compute_aspects(R,r,l);
   }
double maxValue () const virtual
Get the maximum value for this metric.
Reimplemented from Geo_Metric_Base_3.
Definition at line 278 of file Geometric_Metrics_3.C.
Referenced by main().
{
   if (_type == COM::Connectivity::TET4) {
     return 1.0;
   }
   else { return -1.0; }
 }
double minValue () const virtual
Get the minimum value for this metric.
Reimplemented from Geo_Metric_Base_3.
Definition at line 285 of file Geometric_Metrics_3.C.
Referenced by main().
{
   if (_type == COM::Connectivity::TET4) {
     return 0.0;
   }
   else { return -1.0; }
 }
The documentation for this class was generated from the following files:
Geometric_Metrics_3.h
Geometric_Metrics_3.C