Rocstar: bcList Class Reference
bcList Class Reference
Public Member Functions
bcList (FILE *inF)
string lookup (int bcNo, string insert) const
Private Attributes
vector< bcRec * > b
Detailed Description
Definition at line 91 of file writeflo.cpp.
Constructor & Destructor Documentation
bcList (FILE * inF)
Definition at line 99 of file writeflo.cpp.
References bcRec::addLine(), and b.
 {
         int lineCount=0;
         char line[200];
         bcRec *curBC=NULL;
         int bcNo;
         while (NULL!=fgets(line,200,inF)) {
                 lineCount++;
                 switch(line[0]) {
                 case '#': break; //Skip comment line
                 case '\n': case '\r': case 0:
                         break; //Skip empty lines
                 case '@': //Start of new boundary condition
                         bcNo=0;
                         if (1!=sscanf(&line[1],"%d",&bcNo)) {
                                 fprintf(stderr,"ERROR!\n"
                                         "Can't parse boundary condition number from '%s',\n"
                                         "found on line %d of the boundary condition file\n",
                                         line,lineCount);
                                 exit(1);
                         }
                         //Flush the old bc:
                         if (curBC!=NULL) b.push_back(curBC);
                         curBC=new bcRec(bcNo);
                         break;
                 default: //Just a regular description line
                         if (curBC!=NULL) curBC->addLine(line);
                         break;
                 };
         }
         if (curBC!=NULL) b.push_back(curBC);
 }
Member Function Documentation
string lookup (int bcNo, string insert) const
Definition at line 133 of file writeflo.cpp.
References b, and i.
Referenced by writeBlock(), and externalBCpatch::writeFlo().
 {
         unsigned int i;
         for (i=0;i<b.size();i++)
                 if (b[i]->hasNumber(bcNo))
                         return b[i]->getString(insert);
         //If we got here, we couldn't find bcNo
         fprintf(stderr,"ERROR! Can't find boundary condition %d in .bc file!\n",bcNo);
         exit(1);
         return "";//<- for whining compilers
 }
Member Data Documentation
vector<bcRec *> b private
Definition at line 92 of file writeflo.cpp.
Referenced by bcList(), and lookup().
The documentation for this class was generated from the following file:
writeflo.cpp