Rocstar: C3Vector Class Reference
C3Vector Class Reference
/brief Cartesian 3 Vector
#include <GeoPrimitives.H>
Public Member Functions
C3Vector ()
C3Vector (const GeoPrim::CVector &inv)
C3Vector (const CPoint &inp)
C3Vector (double ix, double iy, double iz=0.0)
C3Vector (const C3Vector &p1, const C3Vector &p2)
C3Vector (double *a)
C3Vector (const double *a)
C3Vector (const C3Vector &v)
~C3Vector ()
C3Vector & Copy (const C3Vector &v)
C3Vector & Init (const double *a)
C3Vector & Init (const C3Vector &v)
C3Vector & Init (double ix, double iy, double iz)
C3Vector & Init (const C3Vector &p1, const C3Vector &p2)
C3Vector & Init ()
C3Vector & Clear ()
double Norm () const
double Mag () const
double Mag2 () const
C3Vector & Normalize ()
C3Vector Unit () const
double operator* (const C3Vector &v2) const
Dot Product.
C3Vector operator* (double num) const
Scaling.
C3Vector & operator*= (double num)
C3Vector operator% (const C3Vector &v2) const
Cross Product.
C3Vector & operator= (const C3Vector &v2)
C3Vector & operator%= (const C3Vector &v2)
C3Vector operator+ (const C3Vector &v2) const
C3Vector operator- (const C3Vector &v2) const
C3Vector & operator+= (const C3Vector &v2)
C3Vector & operator-= (const C3Vector &v2)
double & x ()
double x () const
C3Vector & x (double i)
double & y ()
double y () const
C3Vector & y (double i)
double & z ()
double z () const
C3Vector & z (double i)
const double & operator[] (unsigned int i) const
double & operator[] (unsigned int i)
bool operator== (const C3Vector &v) const
bool operator< (const C3Vector &v) const
bool operator> (const C3Vector &v) const
bool operator<= (const C3Vector &v) const
bool operator>= (const C3Vector &v) const
void DestroyData ()
void SetData (double *d)
Protected Attributes
double * V
Private Member Functions
void _create ()
void _destroy ()
Private Attributes
bool _mydata
Friends
C3Vector operator* (double, const C3Vector &)
std::ostream & operator<< (std::ostream &, const C3Vector &)
std::istream & operator>> (std::istream &, C3Vector &)
Detailed Description
/brief Cartesian 3 Vector
Definition at line 468 of file GeoPrimitives.H.
Constructor & Destructor Documentation
C3Vector () inline
Definition at line 477 of file GeoPrimitives.H.
References C3Vector::_create(), and C3Vector::V.
     {
       _create();
       V[0] = V[1] = V[2] = 0.;
     };
C3Vector (const GeoPrim::CVector & inv) inline
Definition at line 482 of file GeoPrimitives.H.
References C3Vector::_create(), C3Vector::V, CVector::x(), CVector::y(), and CVector::z().
     {
       _create();
       V[0] = inv.x();
       V[1] = inv.y();
       V[2] = inv.z();
     };
C3Vector (const CPoint & inp) inline
Definition at line 489 of file GeoPrimitives.H.
References C3Vector::_create(), C3Vector::V, CPoint::x(), CPoint::y(), and CPoint::z().
     {
       _create();
       V[0] = inp.x();
       V[1] = inp.y();
       V[2] = inp.z();
     };
C3Vector (double ix, double iy, double iz = 0.0) inline
Definition at line 496 of file GeoPrimitives.H.
References C3Vector::_create(), and C3Vector::V.
     {
       _create();
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
     };
C3Vector (const C3Vector & p1, const C3Vector & p2) inline
Definition at line 503 of file GeoPrimitives.H.
References C3Vector::_create(), and C3Vector::Copy().
     {
       _create();
       Copy(p2-p1);
     };
C3Vector (double * a) inline
Definition at line 508 of file GeoPrimitives.H.
References C3Vector::_mydata, and C3Vector::V.
     {
       _mydata = false;
       V = a;
     };
C3Vector (const double * a) inline
Definition at line 513 of file GeoPrimitives.H.
References C3Vector::_create(), and C3Vector::V.
     {
       _create();
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
     };
C3Vector (const C3Vector & v) inline
Definition at line 520 of file GeoPrimitives.H.
References C3Vector::_create(), and C3Vector::Copy().
     {
       _create();
       Copy(v);
     };
~C3Vector () inline
Definition at line 525 of file GeoPrimitives.H.
References C3Vector::_destroy().
     {
       _destroy();
     };
Member Function Documentation
void _create () inline private
Definition at line 748 of file GeoPrimitives.H.
References C3Vector::_mydata, and C3Vector::V.
Referenced by C3Vector::C3Vector().
     {
       V = new double [3];
       _mydata = true;
     };
void _destroy () inline private
Definition at line 753 of file GeoPrimitives.H.
References C3Vector::_mydata, and C3Vector::V.
Referenced by C3Vector::DestroyData(), and C3Vector::~C3Vector().
     {
       if(_mydata){
         delete [] V;
         _mydata = false;
         V = NULL;
       }
     };
C3Vector& Clear () inline
Definition at line 567 of file GeoPrimitives.H.
References C3Vector::V.
     {
       V[0] = V[1] = V[2] = 0.0;
       return(*this);
     };
C3Vector& Copy (const C3Vector & v) inline
Definition at line 529 of file GeoPrimitives.H.
References C3Vector::V.
Referenced by C3Facet::_copycreate_point(), C3Vector::C3Vector(), C3Vector::Init(), and C3Vector::operator=().
     {
       V[0] = v.V[0];
       V[1] = v.V[1];
       V[2] = v.V[2];
       return(*this);
     };
void DestroyData () inline
Definition at line 742 of file GeoPrimitives.H.
References C3Vector::_destroy().
 { _destroy(); };
C3Vector& Init (const double * a) inline
Definition at line 536 of file GeoPrimitives.H.
References C3Vector::V.
Referenced by Mesh::GenericElement::Centroid().
     {
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
       return(*this);
     };
C3Vector& Init (const C3Vector & v) inline
Definition at line 543 of file GeoPrimitives.H.
References C3Vector::V.
     {
       V[0] = v[0];
       V[1] = v[1];
       V[2] = v[2];
       return(*this);
     };
C3Vector& Init (double ix, double iy, double iz) inline
Definition at line 550 of file GeoPrimitives.H.
References C3Vector::V.
     {
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
       return(*this);
     };
C3Vector& Init (const C3Vector & p1, const C3Vector & p2) inline
Definition at line 557 of file GeoPrimitives.H.
References C3Vector::Copy().
     {
       Copy(p2 - p1);
       return(*this);
     };
C3Vector& Init () inline
Definition at line 562 of file GeoPrimitives.H.
References C3Vector::V.
     {
       V[0] = V[1] = V[2] = 0.0;
       return(*this);
     };
double Mag () const inline
Definition at line 576 of file GeoPrimitives.H.
References C3Vector::Norm().
Referenced by GeoPrim::Distance().
     {
       return (Norm());
     };
double Mag2 () const inline
Definition at line 580 of file GeoPrimitives.H.
References C3Vector::V.
Referenced by C3Vector::operator<(), and C3Vector::operator>().
     {
       return ((V[0]*V[0])+(V[1]*V[1])+(V[2]*V[2]));
     };
double Norm () const inline
Definition at line 572 of file GeoPrimitives.H.
References sqrt(), and C3Vector::V.
Referenced by C3Vector::Mag(), and C3Vector::Normalize().
     {
       return(sqrt((V[0] * V[0]) + (V[1] * V[1]) + (V[2] * V[2])));
     };
C3Vector& Normalize () inline
Definition at line 584 of file GeoPrimitives.H.
References C3Vector::Norm(), and C3Vector::V.
Referenced by C3Plane::C3Plane(), and C3Vector::Unit().
     {
       double n = Norm();
       V[0] /= n;
       V[1] /= n;
       V[2] /= n;
       return(*this);
     };
C3Vector operator% (const C3Vector & v2) const inline
Cross Product.
Definition at line 624 of file GeoPrimitives.H.
References v, and C3Vector::V.
     {
       C3Vector v;
       v.V[0] = ((v2.V[2] * V[1]) - (v2.V[1] * V[2]));
       v.V[1] = ((v2.V[0] * V[2]) - (v2.V[2] * V[0]));
       v.V[2] = ((v2.V[1] * V[0]) - (v2.V[0] * V[1]));
       return(v);
     };
C3Vector& operator%= (const C3Vector & v2) inline
Definition at line 636 of file GeoPrimitives.H.
References C3Vector::V.
     {
       double t0 = V[0];
       double t1 = V[1];
       double t2 = V[2];
       V[0] = ((v2.V[2] * t1) - (v2.V[1] * t2));
       V[1] = ((v2.V[0] * t2) - (v2.V[2] * t0));
       V[2] = ((v2.V[1] * t0) - (v2.V[0] * t1));
       return(*this);
     };
double operator* (const C3Vector & v2) const inline
Dot Product.
Definition at line 600 of file GeoPrimitives.H.
References C3Vector::V.
     {
       return((V[0] * v2.V[0]) +
              (V[1] * v2.V[1]) +
              (V[2] * v2.V[2]));
     };
C3Vector operator* (double num) const inline
Scaling.
Definition at line 609 of file GeoPrimitives.H.
References C3Vector::V.
     {
       C3Vector rv(num*V[0],num*V[1],num*V[2]);
       return(rv);
     };
C3Vector& operator*= (double num) inline
Definition at line 614 of file GeoPrimitives.H.
References C3Vector::V.
     {
       V[0] *= num;
       V[1] *= num;
       V[2] *= num;
       return(*this);
     };
C3Vector operator+ (const C3Vector & v2) const inline
Definition at line 646 of file GeoPrimitives.H.
References v, and C3Vector::V.
     {
       C3Vector v(V[0] + v2.V[0], V[1] + v2.V[1], V[2] + v2.V[2]);
       return(v);
     };
C3Vector& operator+= (const C3Vector & v2) inline
Definition at line 655 of file GeoPrimitives.H.
References C3Vector::V.
     {
       V[0] += v2.V[0];
       V[1] += v2.V[1];
       V[2] += v2.V[2];
       return(*this);
     };
C3Vector operator- (const C3Vector & v2) const inline
Definition at line 651 of file GeoPrimitives.H.
     {
       return((*this) + (-1.0 * v2));
     };
C3Vector& operator-= (const C3Vector & v2) inline
Definition at line 662 of file GeoPrimitives.H.
References C3Vector::V.
     {
       V[0] -= v2.V[0];
       V[1] -= v2.V[1];
       V[2] -= v2.V[2];
       return(*this);
     };
bool operator< (const C3Vector & v) const inline
Definition at line 724 of file GeoPrimitives.H.
References C3Vector::Mag2().
     {
       return (Mag2() < v.Mag2());
     };
bool operator<= (const C3Vector & v) const inline
Definition at line 732 of file GeoPrimitives.H.
     {
       return ( (*this < v) ||
                (*this == v));
     };
C3Vector& operator= (const C3Vector & v2) inline
Definition at line 632 of file GeoPrimitives.H.
References C3Vector::Copy().
     {
       return(Copy(v2));
     };
bool operator== (const C3Vector & v) const inline
Definition at line 718 of file GeoPrimitives.H.
References GeoPrim::TOL, and C3Vector::V.
     {
       return( (fabs(V[0] - v.V[0]) < TOL) &&
               (fabs(V[1] - v.V[1]) < TOL) &&
               (fabs(V[2] - v.V[2]) < TOL) );
     };
bool operator> (const C3Vector & v) const inline
Definition at line 728 of file GeoPrimitives.H.
References C3Vector::Mag2().
     {
       return (Mag2() > v.Mag2());
     };
bool operator>= (const C3Vector & v) const inline
Definition at line 737 of file GeoPrimitives.H.
     {
       return ( (*this > v) ||
                (*this == v) );
     };
const double& operator[] (unsigned int i) const inline
Definition at line 708 of file GeoPrimitives.H.
References C3Vector::V.
     {
       assert(i>0 && i<4);
       return(V[i-1]);
     };
double& operator[] (unsigned int i) inline
Definition at line 713 of file GeoPrimitives.H.
References C3Vector::V.
     {
       assert(i>0 && i<4);
       return(V[i-1]);
     };
void SetData (double * d) inline
Definition at line 743 of file GeoPrimitives.H.
References C3Vector::_mydata, and C3Vector::V.
{
       V = d;
       _mydata = false;
     };
C3Vector Unit () const inline
Definition at line 592 of file GeoPrimitives.H.
References C3Vector::Normalize(), and v.
Referenced by C3Plane::operator==().
     {
       C3Vector v(*this);
       return(v.Normalize());
     };
double& x () inline
Definition at line 669 of file GeoPrimitives.H.
References C3Vector::V.
Referenced by C3Plane::A(), C3Plane::C3Plane(), C3Plane::contains_point(), C3Plane::D(), GeoPrim::Distance(), Mesh::GenerateCartesianGrid(), and GeoPrim::operator<<().
     {
       return(V[0]);
     };
double x () const inline
Definition at line 673 of file GeoPrimitives.H.
References C3Vector::V.
     {
       return(V[0]);
     };
C3Vector& x (double i) inline
Definition at line 677 of file GeoPrimitives.H.
References i, and C3Vector::V.
     {
       V[0] = i;
       return(*this);
     };
double& y () inline
Definition at line 682 of file GeoPrimitives.H.
References C3Vector::V.
Referenced by C3Plane::B(), C3Plane::C3Plane(), C3Plane::contains_point(), C3Plane::D(), GeoPrim::Distance(), Mesh::GenerateCartesianGrid(), and GeoPrim::operator<<().
     {
       return(V[1]);
     };
double y () const inline
Definition at line 686 of file GeoPrimitives.H.
References C3Vector::V.
     {
       return(V[1]);
     };
C3Vector& y (double i) inline
Definition at line 690 of file GeoPrimitives.H.
References i, and C3Vector::V.
     {
       V[1] = i;
       return(*this);
     };
double& z () inline
Definition at line 695 of file GeoPrimitives.H.
References C3Vector::V.
Referenced by C3Plane::C(), C3Plane::C3Plane(), C3Plane::contains_point(), C3Plane::D(), GeoPrim::Distance(), Mesh::GenerateCartesianGrid(), and GeoPrim::operator<<().
     {
       return(V[2]);
     };
double z () const inline
Definition at line 699 of file GeoPrimitives.H.
References C3Vector::V.
     {
       return(V[2]);
     };
C3Vector& z (double i) inline
Definition at line 703 of file GeoPrimitives.H.
References i, and C3Vector::V.
     {
       V[2] = i;
       return(*this);
     };
Friends And Related Function Documentation
C3Vector operator* (double scalar, const C3Vector & v) friend
Definition at line 126 of file GeoPrimitives.C.
   {
     GeoPrim::C3Vector rv(v);
     return(rv *= scalar);
   }
std::ostream& operator<< (std::ostream & oS, const C3Vector & v) friend
Definition at line 104 of file GeoPrimitives.C.
   {
     oS << v.x() << "  " << v.y() << "  " << v.z();
     return(oS);
   }
std::istream& operator>> (std::istream & iS, GeoPrim::C3Vector & v) friend
Definition at line 111 of file GeoPrimitives.C.
   {
     iS >> v[0] >> v[1] >> v[2];
     return(iS);
   }
Member Data Documentation
bool _mydata private
Definition at line 473 of file GeoPrimitives.H.
Referenced by C3Vector::_create(), C3Vector::_destroy(), C3Vector::C3Vector(), and C3Vector::SetData().
double* V protected
Definition at line 475 of file GeoPrimitives.H.
Referenced by C3Vector::_create(), C3Vector::_destroy(), C3Vector::C3Vector(), C3Vector::Clear(), C3Vector::Copy(), C3Vector::Init(), C3Vector::Mag2(), C3Vector::Norm(), C3Vector::Normalize(), C3Vector::operator%(), C3Vector::operator%=(), C3Vector::operator*(), C3Vector::operator*=(), C3Vector::operator+(), C3Vector::operator+=(), C3Vector::operator-=(), C3Vector::operator==(), C3Vector::operator[](), C3Vector::SetData(), C3Vector::x(), C3Vector::y(), and C3Vector::z().
The documentation for this class was generated from the following file:
GeoPrimitives.H