Rocstar: Pane_dual_connectivity Class Reference
Pane_dual_connectivity Class Reference
Constructs the dual connectivity for the whole pane (including ghost nodes and elements), which contains information about incident elements for each node.
#include <Dual_connectivity.h>
Public Member Functions
Pane_dual_connectivity (const COM::Pane *p, bool with_ghost=true)
Constructs the dual connectivity for a given pane.
void incident_elements (int node_id, std::vector< int > &elists)
Obtain the IDs of the elements incident on a given node.
Protected Member Functions
void construct_connectivity_str_2 ()
Construct dual connectivity for 2-D structured meshes.
void construct_connectivity_unstr ()
Construct dual connectivity for unstructured meshes.
Private Attributes
const COM::Pane & _pane
bool _with_ghost
std::vector< int > _offsets
std::vector< int > _eids
Detailed Description
Constructs the dual connectivity for the whole pane (including ghost nodes and elements), which contains information about incident elements for each node.
Definition at line 36 of file Dual_connectivity.h.
Constructor & Destructor Documentation
MAP_BEGIN_NAMESPACE Pane_dual_connectivity (const COM::Pane * p, bool with_ghost = true) explicit
Constructs the dual connectivity for a given pane.
Definition at line 31 of file Dual_connectivity.C.
References construct_connectivity_str_2(), and construct_connectivity_unstr().
   : _pane(*p), _with_ghost(with_ghost) {
   if ( p->dimension()==2 && p->is_structured())
     construct_connectivity_str_2();
   else {
     assert( !p->is_structured());
     construct_connectivity_unstr();
   }
 }
Member Function Documentation
void construct_connectivity_str_2 () protected
Construct dual connectivity for 2-D structured meshes.
Definition at line 50 of file Dual_connectivity.C.
References _eids, _offsets, _pane, _with_ghost, COM_assertion_msg, i, k, Element_node_enumerator_str_2::next(), ni, and nj.
Referenced by Pane_dual_connectivity().
{
   COM_assertion_msg( _with_ghost || _pane.size_of_ghost_layers()==0,
                      "Not yet implemented for structured mesh with ghosts");
   int n=_with_ghost ? _pane.size_of_nodes() : _pane.size_of_real_nodes();
   { // First, count the number of incident elements of each .
     std::vector<char> nielems(n);
     std::fill_n( nielems.begin(), n, 4);
     int ni=_pane.size_i(), nj=_pane.size_j();
     std::fill_n( nielems.begin(), ni, 2);
     std::fill_n( nielems.begin()+ni*(nj-1), ni, 2);
     for ( int i=ni; i<ni*(nj-1); i+=ni)
       nielems[i] = nielems[i+ni-1] = 2;
     nielems[0] = nielems[ni-1] = 1;
     nielems[ni*nj-ni] = nielems[ni*nj-1] = 1;
     // Now construct a vector for storing the offsets
     _offsets.clear(); _offsets.resize(n+1, 0);
     for ( int i=1; i<=n; ++i) _offsets[i] = _offsets[i-1]+nielems[i-1];
     _eids.resize( _offsets[n]);
   }
   { // Fill in the connectivity table
     const int nn = 4;
     Element_node_enumerator_str_2 ene( &_pane, 1);
     for ( int i=1,size=_pane.size_of_elements(); i<=size; ++i, ene.next())
       for ( int k=0; k<nn; ++k)
         _eids[ _offsets[ene[k]-1]++] = i;
     // Recover _offsets
     for ( int i=n; i>0; --i) _offsets[i] = _offsets[i-1];
     _offsets[0] = 0;
   }
 }
void construct_connectivity_unstr () protected
Construct dual connectivity for unstructured meshes.
Definition at line 90 of file Dual_connectivity.C.
References _eids, _offsets, _pane, _with_ghost, i, k, Element_node_enumerator_uns::next(), and Element_node_enumerator_uns::size_of_nodes().
Referenced by Pane_dual_connectivity().
{
   int nnodes, nelems;
   if ( _with_ghost) {
     nnodes=_pane.size_of_nodes();
     nelems=_pane.size_of_elements();
   }
   else {
     nnodes=_pane.size_of_real_nodes();
     nelems=_pane.size_of_real_elements();
   }
   { // First, count the number of incident elements of each node.
     std::vector<char> nielems(nnodes);
     std::fill_n( nielems.begin(), nnodes, 0);
     Element_node_enumerator_uns ene( &_pane, 1);
     for ( int i=1; i<=nelems; ++i, ene.next())
       for ( int k=0, nn=ene.size_of_nodes(); k<nn; ++k)
         ++nielems[ ene[k]-1];
     // Now construct a vector for storing the offsets
     _offsets.clear(); _offsets.resize(nnodes+1);
     _offsets[0] = 0;
     for ( int i=1; i<=nnodes; ++i) _offsets[i] = _offsets[i-1]+nielems[i-1];
     _eids.resize( _offsets[nnodes]);
   }
   { // Fill in the connectivity table
     Element_node_enumerator_uns ene( &_pane, 1);
     for ( int i=1; i<=nelems; ++i, ene.next())
       for ( int k=0, nn=ene.size_of_nodes(); k<nn; ++k)
         _eids[ _offsets[ene[k]-1]++] = i;
     // Recover _offsets
     for ( int i=nnodes; i>0; --i) _offsets[i] = _offsets[i-1];
     _offsets[0] = 0;
   }
 }
void incident_elements (int node_id, std::vector< int > & elists)
Obtain the IDs of the elements incident on a given node.
Definition at line 43 of file Dual_connectivity.C.
References _eids, _offsets, and COM_assertion.
Referenced by Simple_manifold_2::determine_opposite_halfedges().
{
   COM_assertion( node_id > 0); // Node id start from 1.
   elists.clear();
   elists.insert( elists.begin(), &_eids[_offsets[node_id-1]], &_eids[_offsets[node_id]]);
 }
Member Data Documentation
std::vector< int> _eids private
Definition at line 54 of file Dual_connectivity.h.
Referenced by construct_connectivity_str_2(), construct_connectivity_unstr(), and incident_elements().
std::vector< int> _offsets private
Definition at line 53 of file Dual_connectivity.h.
Referenced by construct_connectivity_str_2(), construct_connectivity_unstr(), and incident_elements().
const COM::Pane& _pane private
Definition at line 51 of file Dual_connectivity.h.
Referenced by construct_connectivity_str_2(), and construct_connectivity_unstr().
bool _with_ghost private
Definition at line 52 of file Dual_connectivity.h.
Referenced by construct_connectivity_str_2(), and construct_connectivity_unstr().
The documentation for this class was generated from the following files:
Dual_connectivity.h
Dual_connectivity.C