Rocstar: Normal_set Class Reference
Normal_set Class Reference
#include <Overlay_primitives.h>
Public Types
typedef Normal_set Self
typedef Vertex_overlay Vertex
typedef Halfedge_overlay Halfedge
typedef Facet_overlay Facet
typedef Vector_3 Value
typedef unsigned int Size
Public Member Functions
Normal_set (const Halfedge *h)
Normal_set (const Halfedge *h, Size)
const Value & operator[] (Size i) const
Size size_of_edges () const
Size size_of_nodes () const
Protected Attributes
Vertex_set vs
std::vector< const Halfedge * > hs
Detailed Description
Definition at line 109 of file Overlay_primitives.h.
Member Typedef Documentation
typedef Facet_overlay Facet
Definition at line 114 of file Overlay_primitives.h.
typedef Halfedge_overlay Halfedge
Definition at line 113 of file Overlay_primitives.h.
typedef Normal_set Self
Definition at line 111 of file Overlay_primitives.h.
typedef unsigned int Size
Definition at line 116 of file Overlay_primitives.h.
typedef Vector_3 Value
Definition at line 115 of file Overlay_primitives.h.
typedef Vertex_overlay Vertex
Definition at line 112 of file Overlay_primitives.h.
Constructor & Destructor Documentation
Normal_set (const Halfedge * h) inline explicit
Definition at line 118 of file Overlay_primitives.h.
References hs, i, Halfedge_overlay::next(), and s.
                                           : vs(h), hs(vs.size_of_nodes()) {
     for ( unsigned int i=0, s=hs.size(); i<s; ++i)
     { hs[i] = h; h = h->next(); }
   }
Normal_set (const Halfedge * h, Size) inline
Definition at line 122 of file Overlay_primitives.h.
References hs, i, Halfedge_overlay::next(), and s.
                                        : vs(h,0), hs(vs.size_of_nodes()) {
     for ( unsigned int i=0, s=hs.size(); i<s; ++i)
     { hs[i] = h; h = h->next(); }
   }
Member Function Documentation
const Value& operator[] (Size i) const inline
Definition at line 131 of file Overlay_primitives.h.
References RFC_Pane_overlay::get_normal(), hs, Vertex_set::pane(), and vs.
   { return vs.pane()->get_normal(hs[i], vs[i]); }
Size size_of_edges () const inline
Definition at line 133 of file Overlay_primitives.h.
References Vertex_set::size_of_edges(), and vs.
Referenced by Overlay_primitives::get_projdir().
 { return vs.size_of_edges(); }
Size size_of_nodes () const inline
Definition at line 134 of file Overlay_primitives.h.
References Vertex_set::size_of_nodes(), and vs.
 { return vs.size_of_nodes(); }
Member Data Documentation
std::vector< const Halfedge*> hs protected
Definition at line 138 of file Overlay_primitives.h.
Referenced by Normal_set(), and operator[]().
Vertex_set vs protected
Definition at line 137 of file Overlay_primitives.h.
Referenced by operator[](), size_of_edges(), and size_of_nodes().
The documentation for this class was generated from the following file:
Overlay_primitives.h