Rocstar: plag_modstats Module Reference
plag_modstats Module Reference
Public Member Functions
subroutine, public plag_createstat (pRegion, pPlag)
subroutine, public plag_destroystat (pRegion, pPlag)
subroutine, public plag_initstat (pRegion, pPlag)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_ModStats.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 39 of file PLAG_ModStats.F90.
Member Function/Subroutine Documentation
subroutine, public plag_createstat (pRegion, type(t_plag), pointer pPlag)
Definition at line 124 of file PLAG_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), and rflo_getdimensdummy().
Referenced by plag_allocatememory(), and rocpart_post().
subroutine, public plag_destroystat (pRegion, type(t_plag), pointer pPlag)
Definition at line 226 of file PLAG_ModStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rocpart_post().
subroutine, public plag_initstat (pRegion, type(t_plag), pointer pPlag)
Definition at line 308 of file PLAG_ModStats.F90.
References moderror::deregisterfunction(), icell, idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), and rflo_getdimensdummy().
Referenced by plag_initmemory().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_ModStats.F90,v $ $Revision: 1.4 $' private
Definition at line 69 of file PLAG_ModStats.F90.
The documentation for this module was generated from the following file:
PLAG_ModStats.F90