Rocstar: SphericalDomain Class Reference
SphericalDomain Class Reference
#include <SphericalDomain.hpp>
Public Member Functions
SphericalDomain (const Vector3D &center, double radius)
virtual ~SphericalDomain ()
DomainHint hint () const
Give a hint about the nature of the domain for better performance.
void set_sphere (const Vector3D &center, double radius)
virtual void snap_to (Mesh::EntityHandle entity_handle, Vector3D &coordinate) const
Modifies "coordinate" so that it lies on the domain to which "entity_handle" is constrained.
virtual void normal_at (Mesh::EntityHandle entity_handle, Vector3D &coordinate) const
Returns the normal of the domain to which "entity_handle" is constrained.
virtual void normal_at (Mesh::EntityHandle handle, Vector3D coords[], unsigned count, MsqError &err) const
evaluate surface normals
virtual void closest_point (Mesh::EntityHandle handle, const Vector3D &position, Vector3D &closest, Vector3D &normal, MsqError &err) const
evaluate closest point and normal
SphericalDomain (const Vector3D &center, double radius)
virtual ~SphericalDomain ()
DomainHint hint () const
Give a hint about the nature of the domain for better performance.
void set_sphere (const Vector3D &center, double radius)
virtual void snap_to (Mesh::EntityHandle entity_handle, Vector3D &coordinate) const
Modifies "coordinate" so that it lies on the domain to which "entity_handle" is constrained.
virtual void normal_at (Mesh::EntityHandle entity_handle, Vector3D &coordinate) const
Returns the normal of the domain to which "entity_handle" is constrained.
virtual void normal_at (Mesh::EntityHandle handle, Vector3D coords[], unsigned count, MsqError &err) const
evaluate surface normals
virtual void closest_point (Mesh::EntityHandle handle, const Vector3D &position, Vector3D &closest, Vector3D &normal, MsqError &err) const
evaluate closest point and normal
Public Member Functions inherited from MeshDomain
virtual ~MeshDomain ()
Private Attributes
Vector3D mCenter
double mRadius
Detailed Description
This is a template for a spherical domain. It will provide the normal information necessary for surface mesh optimization.
Definition at line 48 of file includeLinks/SphericalDomain.hpp.
Constructor & Destructor Documentation
SphericalDomain (const Vector3D & center, double radius) inline
Definition at line 51 of file includeLinks/SphericalDomain.hpp.
         : mCenter(center), mRadius(radius)
       {}
virtual ~SphericalDomain () inline virtual
Definition at line 55 of file includeLinks/SphericalDomain.hpp.
 { }
SphericalDomain (const Vector3D & center, double radius) inline
Definition at line 51 of file src/Misc/SphericalDomain.hpp.
         : mCenter(center), mRadius(radius)
       {}
virtual ~SphericalDomain () inline virtual
Definition at line 55 of file src/Misc/SphericalDomain.hpp.
 { }
Member Function Documentation
void closest_point (Mesh::EntityHandle handle, const Vector3D & position, Vector3D & closest, Vector3D & normal, MsqError & err) const virtual
evaluate closest point and normal
Given a position in space, return the closest position in the domain and the domain normal at that point.
Parameters
entity_handle Evaluate the subset of the domain contianing this entity
position Input position for which to evaluate
closest Closest position in the domain.
normal Domain normal at the location of 'closest'
Implements MeshDomain.
Definition at line 76 of file Misc/SphericalDomain.cpp.
References Vector3D::normalize(), Vector3D::set(), and Vector3D::x().
 {
   normal = position - mCenter;
   normal.normalize();
   if (!finite(normal.x()))
     normal.set( 1.0, 0.0, 0.0 );
   closest = mCenter + mRadius * normal;
 }
virtual void closest_point (Mesh::EntityHandle handle, const Vector3D & position, Vector3D & closest, Vector3D & normal, MsqError & err) const virtual
evaluate closest point and normal
Given a position in space, return the closest position in the domain and the domain normal at that point.
Parameters
entity_handle Evaluate the subset of the domain contianing this entity
position Input position for which to evaluate
closest Closest position in the domain.
normal Domain normal at the location of 'closest'
Implements MeshDomain.
DomainHint hint () const inline virtual
Give a hint about the nature of the domain for better performance.
For implementations, if unsure, return NO_DOMAIN_HINT. SMOOTH_DOMAIN is a good default choice if the domain is a single geometric surface.
Implements MeshDomain.
Definition at line 57 of file includeLinks/SphericalDomain.hpp.
References Mesquite::SMOOTH_DOMAIN.
 { return SMOOTH_DOMAIN; }
DomainHint hint () const inline virtual
Give a hint about the nature of the domain for better performance.
For implementations, if unsure, return NO_DOMAIN_HINT. SMOOTH_DOMAIN is a good default choice if the domain is a single geometric surface.
Implements MeshDomain.
Definition at line 57 of file src/Misc/SphericalDomain.hpp.
References Mesquite::SMOOTH_DOMAIN.
 { return SMOOTH_DOMAIN; }
void normal_at (Mesh::EntityHandle entity_handle, Vector3D & coordinate) const virtual
Returns the normal of the domain to which "entity_handle" is constrained.
For non-planar surfaces, the normal is calculated at the point on the domain that is closest to the passed in value of "coordinate". If the domain does not have a normal, or the normal cannot be determined, "coordinate" is set to (0,0,0). Otherwise, "coordinate" is set to the domain's normal at the appropriate point. In summary, the handle determines the domain. The coordinate determines the point of interest on that domain.
User should see also PatchData::get_domain_normal_at_vertex and PatchData::get_domain_normal_at_element .
Implements MeshDomain.
Definition at line 53 of file Misc/SphericalDomain.cpp.
References Vector3D::length(), Mesquite::length(), Vector3D::set(), and Vector3D::x().
 {
     // normal is vector from center to input position
   coordinate -= mCenter;
     // make it a unit vector
   double length = coordinate.length();
   coordinate /= length;
     // if input position was at center, choose same position
     // on sphere as snap_to.
   if (!finite(coordinate.x()))
     coordinate.set( 1.0, 0.0, 0.0 );
 }
virtual void normal_at (Mesh::EntityHandle entity_handle, Vector3D & coordinate) const virtual
Returns the normal of the domain to which "entity_handle" is constrained.
For non-planar surfaces, the normal is calculated at the point on the domain that is closest to the passed in value of "coordinate". If the domain does not have a normal, or the normal cannot be determined, "coordinate" is set to (0,0,0). Otherwise, "coordinate" is set to the domain's normal at the appropriate point. In summary, the handle determines the domain. The coordinate determines the point of interest on that domain.
User should see also PatchData::get_domain_normal_at_vertex and PatchData::get_domain_normal_at_element .
Implements MeshDomain.
virtual void normal_at (Mesh::EntityHandle handle, Vector3D coordinates[], unsigned count, MsqError & err) const virtual
evaluate surface normals
Returns normals for a domain.
Parameters
entity_handle The domain evaluated is the one in which this mesh entity is constrained.
coordinates As input, a list of positions at which to evaluate the domain. As output, the resulting domain normals.
count The length of the coordinates array.
Implements MeshDomain.
void normal_at (Mesh::EntityHandle handle, Vector3D coordinates[], unsigned count, MsqError & err) const virtual
evaluate surface normals
Returns normals for a domain.
Parameters
entity_handle The domain evaluated is the one in which this mesh entity is constrained.
coordinates As input, a list of positions at which to evaluate the domain. As output, the resulting domain normals.
count The length of the coordinates array.
Implements MeshDomain.
Definition at line 67 of file Misc/SphericalDomain.cpp.
References i.
 {
   for (unsigned i = 0; i < count; ++i)
     normal_at( handle, coords[i] );
 }
void set_sphere (const Vector3D & center, double radius) inline
Definition at line 59 of file src/Misc/SphericalDomain.hpp.
References SphericalDomain::mCenter, and SphericalDomain::mRadius.
       {
         mCenter = center;
         mRadius = radius;
       }
void set_sphere (const Vector3D & center, double radius) inline
Definition at line 59 of file includeLinks/SphericalDomain.hpp.
References SphericalDomain::mCenter, and SphericalDomain::mRadius.
       {
         mCenter = center;
         mRadius = radius;
       }
void snap_to (Mesh::EntityHandle entity_handle, Vector3D & coordinate) const virtual
Modifies "coordinate" so that it lies on the domain to which "entity_handle" is constrained.
The handle determines the domain. The coordinate is the proposed new position on that domain.
Implements MeshDomain.
Definition at line 36 of file Misc/SphericalDomain.cpp.
References Vector3D::length(), SphericalDomain::mCenter, SphericalDomain::mRadius, Vector3D::set(), and Vector3D::x().
 {
     // Get vector center to coordinate, store in coordinate.
   coordinate -= mCenter;
     // Get distance from center of sphere
   double len = coordinate.length();
     // Scale vector to have length of radius
   coordinate *= mRadius / len;
     // If was at center, return arbitrary position on sphere
     // (all possitions are equally close)
   if (!finite(coordinate.x()))
     coordinate.set( mRadius, 0.0, 0.0 );
     // Get position from vector
   coordinate += mCenter;
 }
virtual void snap_to (Mesh::EntityHandle entity_handle, Vector3D & coordinate) const virtual
Modifies "coordinate" so that it lies on the domain to which "entity_handle" is constrained.
The handle determines the domain. The coordinate is the proposed new position on that domain.
Implements MeshDomain.
Member Data Documentation
Vector3D mCenter private
Definition at line 83 of file includeLinks/SphericalDomain.hpp.
Referenced by SphericalDomain::set_sphere(), and SphericalDomain::snap_to().
double mRadius private
Definition at line 84 of file includeLinks/SphericalDomain.hpp.
Referenced by SphericalDomain::set_sphere(), and SphericalDomain::snap_to().
The documentation for this class was generated from the following files:
includeLinks/SphericalDomain.hpp
Misc/SphericalDomain.cpp