Rocstar: Program< GlobalType, ComLineType > Class Template Reference
Program< GlobalType, ComLineType > Class Template Reference
#include <Global.H>
Public Member Functions
Program ()
Program (GlobalType &inglob)
Program (ComLineType &incom)
Program (ComLineType &incom, GlobalType &inglob)
Program (int narg, char **args)
virtual int Initialize ()
ComLineType & CommandLine ()
virtual int Run ()
virtual int Finalize ()
virtual ~Program ()
Protected Attributes
ComLineType _command_line
Detailed Description
template<typename GlobalType, typename ComLineType>
class IRAD::Global::Program< GlobalType, ComLineType >
Definition at line 557 of file Global.H.
Constructor & Destructor Documentation
Program () inline
Definition at line 562 of file Global.H.
                 :
         GlobalType()
       {};
Program (GlobalType & inglob) inline
Definition at line 565 of file Global.H.
                                   :
         GlobalType(inglob){};
Program (ComLineType & incom) inline
Definition at line 567 of file Global.H.
                                   :
         GlobalType(),_command_line(incom)
       {};
Program (ComLineType & incom, GlobalType & inglob) inline
Definition at line 570 of file Global.H.
                                                      :
         GlobalType(inglob), _command_line(incom) {};
Program (int narg, char ** args) inline
Definition at line 572 of file Global.H.
                                     :
         GlobalType(narg,args)
       {
         _command_line.Record((const char **)args);
         //      SetName(_command_line.ProgramName());
       };
virtual ~Program () inline virtual
Definition at line 586 of file Global.H.
 {};
Member Function Documentation
ComLineType& CommandLine () inline
Definition at line 583 of file Global.H.
 {return _command_line; };
virtual int Finalize () inline virtual
Definition at line 585 of file Global.H.
Referenced by GridConversion::ExampleProgram::Driver(), GridConversion::DriverProgram::Driver(), and IRAD::MyTestProgram().
 {return(GlobalType::Finalize());};
virtual int Initialize (void) inline virtual
Reimplemented in SerialProgram, SerialProgram, and TestProgram.
Definition at line 578 of file Global.H.
Referenced by TestProgram::Initialize(), and SerialProgram::Initialize().
       {
         _command_line.Initialize();
         return(_command_line.ProcessOptions());
       };
virtual int Run () inline virtual
Reimplemented in SerialProgram, and SerialProgram.
Definition at line 584 of file Global.H.
Referenced by IRAD::MyTestProgram().
 {return(0);};
Member Data Documentation
ComLineType _command_line protected
Definition at line 560 of file Global.H.
Referenced by Program< TestGlobal, TestComLine >::CommandLine(), SerialProgram::Initialize(), Program< TestGlobal, TestComLine >::Initialize(), and Program< TestGlobal, TestComLine >::Program().
The documentation for this class was generated from the following file:
Global.H