Rocstar: rflu_modnewtonkrylov Module Reference
rflu_modnewtonkrylov Module Reference
Public Member Functions
subroutine, public rflu_nk_timestepping (dTimeSystem, dIterSystem, regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModNewtonKrylov.F90,v $ $Revision: 1.16 $'
Detailed Description
Definition at line 39 of file RFLU_ModNewtonKrylov.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_nk_timestepping (real(rfreal) dTimeSystem, integer dIterSystem, type(t_region), dimension(:), pointer regions)
Definition at line 140 of file RFLU_ModNewtonKrylov.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), modstatsroutines::getstatistics(), ic, plag_modsurfstats::plag_writesurfstatswrapper(), Aff_transformation_repS2< FT >::print(), Color::r(), moderror::registerfunction(), rflu_modgeometry::rflu_buildgeometry(), rflu_checkgridspeeds(), rflu_checkpositivity(), rflu_checkvalidity(), rflu_modforcesmoments::rflu_computeglobalforcesmoments(), rflu_computegridspeeds(), rflu_computeintegralvalues(), rflu_modforcesmoments::rflu_computelocalforcesmoments(), rflu_modweights::rflu_computewtsbf2cwrapper(), rflu_modweights::rflu_computewtsc2cwrapper(), rflu_modweights::rflu_computewtsf2cwrapper(), rflu_decideneedbgradface(), rflu_decideprint(), rflu_decidewrite(), rflu_modprobes::rflu_decidewriteprobes(), rflu_modprobes::rflu_findprobecells(), rflu_getdeformationwrapper(), rflu_movegridwrapper(), rflu_modmpi::rflu_mpi_clearrequestwrapper(), rflu_modmpi::rflu_mpi_isendwrapper(), rflu_modmpi::rflu_mpi_recvwrapper(), rflu_modpetscnewtonkrylov::rflu_petsc_formjacobian(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidual(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidualfirstorder(), rflu_printchangeinfo(), rflu_modforcesmoments::rflu_printglobalforcesmoments(), rflu_printgridinfo(), rflu_modprobes::rflu_printprobeinfo(), rflu_printwriteconvergence(), rflu_putboundaryvalues(), rflu_residualnorm(), rflu_setdependentvars(), rflu_timestepinviscid(), rflu_timestepviscous(), rflu_moddimensions::rflu_writedimensionswrapper(), rflu_modreadwriteflow::rflu_writeflowwrapper(), rflu_modforcesmoments::rflu_writeglobalforcesmoments(), rflu_modreadwritegridspeeds::rflu_writegridspeedswrapper(), rflu_modreadwritegrid::rflu_writegridwrapper(), rflu_modpatchcoeffs::rflu_writepatchcoeffswrapper(), rflu_writerestartinfo(), rflu_writestat(), rflu_writestatsfileoles(), writeprobe(), and writetotalmass().
Referenced by rflu_flowsolver().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModNewtonKrylov.F90,v $ $Revision: 1.16 $' private
Definition at line 108 of file RFLU_ModNewtonKrylov.F90.
The documentation for this module was generated from the following file:
RFLU_ModNewtonKrylov.F90