Rocstar: modindexing Module Reference
modindexing Module Reference
Public Member Functions
subroutine getijk (ijk, iOffset, ijOffset, nDumCells, i, j, k)
INTEGER function indijkmap (i, j, k, mapMat, iOffset, ijOffset)
Detailed Description
Definition at line 46 of file ModIndexing.F90.
Member Function/Subroutine Documentation
subroutine getijk (integer ijk, integer iOffset, integer ijOffset, integer nDumCells, integer i, integer j, integer k)
Definition at line 54 of file ModIndexing.F90.
References i, j, k, and q.
Referenced by plag_bufferdatasend(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_corncellsloaddata(), plag_edgecellsloaddata(), plag_patchexchangeconf(), plag_rflo_findgridmapping(), plag_rflo_sendmetrics(), plag_rflo_sourcecell(), and rflo_sourcecell().
INTEGER function indijkmap (integer i, integer j, integer k, integer, dimension(3,4) mapMat, integer iOffset, integer ijOffset)
Definition at line 67 of file ModIndexing.F90.
References i, j, and k.
Referenced by peul_exchangedummyconf(), plag_bufferdatasend(), plag_patchexchangeconf(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_copystatbuff(), plag_rflo_sourcecell(), radi_floflimexchangedummyconf(), rflo_exchangednodecopy(), rflo_exchangedummyconf(), rflo_exchangegeometrycopy(), rflo_sourcecell(), and turb_floransexchangedummyconf().
The documentation for this module was generated from the following file:
ModIndexing.F90