Rocstar: VertexMover Class Reference
VertexMover Class Reference abstract
#include <VertexMover.hpp>
Public Member Functions
virtual ~VertexMover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
Improves the quality of the MeshSet, calling some methods specified in a class derived from VertexMover.
virtual ~VertexMover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
Public Member Functions inherited from QualityImprover
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Protected Member Functions
VertexMover ()
virtual void initialize (PatchData &pd, MsqError &err)=0
virtual void cleanup ()=0
virtual void optimize_vertex_positions (PatchData &pd, MsqError &err)=0
virtual void initialize_mesh_iteration (PatchData &pd, MsqError &err)=0
virtual void terminate_mesh_iteration (PatchData &, MsqError &err)=0
size_t check_feasible (PatchData &pd, MsqError &err)
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
VertexMover ()
virtual void initialize (PatchData &pd, MsqError &err)=0
virtual void cleanup ()=0
virtual void optimize_vertex_positions (PatchData &pd, MsqError &err)=0
virtual void initialize_mesh_iteration (PatchData &pd, MsqError &err)=0
virtual void terminate_mesh_iteration (PatchData &, MsqError &err)=0
size_t check_feasible (PatchData &pd, MsqError &err)
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
Protected Member Functions inherited from QualityImprover
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Protected Attributes
ObjectiveFunction * objFunc
Additional Inherited Members
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Detailed Description
Base class for all Vertex Movers.
Definition at line 52 of file includeLinks/VertexMover.hpp.
Constructor & Destructor Documentation
VertexMover () protected
Definition at line 45 of file QualityImprover/VertexMover/VertexMover.cpp.
References VertexMover::objFunc.
                          :
   QualityImprover()
 {
   objFunc=NULL;
 }
virtual ~VertexMover () inline virtual
Definition at line 58 of file includeLinks/VertexMover.hpp.
 { };
VertexMover () protected
virtual ~VertexMover () inline virtual
Definition at line 58 of file src/QualityImprover/VertexMover/VertexMover.hpp.
 { };
Member Function Documentation
size_t check_feasible (PatchData & pd, MsqError & err) inline protected
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
Takes a PatchData object (by reference) and returns whether the patch is within the feasible region, 0, or outside the region, 1.
Definition at line 85 of file includeLinks/VertexMover.hpp.
References MsqMeshEntity::compute_weighted_jacobian(), QualityMetric::ELEMENT_VERTICES, PatchData::get_element_array(), MsqMeshEntity::get_sample_points(), i, and PatchData::num_elements().
   {
     MsqMeshEntity* elems=pd.get_element_array(err);
     size_t num_elements=pd.num_elements();
     msq_std::vector<Vector3D> sample_points;
     Vector3D jacobian_vectors[3];
     short num_jacobian_vectors;
     size_t i =0;
     for(i=0;i<num_elements;++i){
       elems[i].get_sample_points(QualityMetric::ELEMENT_VERTICES,sample_points,err);
       msq_std::vector<Vector3D>::iterator iter=sample_points.begin();
       while(iter!=sample_points.end()){
         elems[i].compute_weighted_jacobian(pd, (*iter),
                                            jacobian_vectors,
                                            num_jacobian_vectors, err);
         if(num_jacobian_vectors==2){
             //2-d not yet implemented
         }
         else if(num_jacobian_vectors==3){
           if(jacobian_vectors[0]%(jacobian_vectors[1]*
                                    jacobian_vectors[2])<=0.0){
             return 1;
           }
         }
         ++iter;
       }
     }
     return 0;
   }
size_t check_feasible (PatchData & pd, MsqError & err) protected
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
virtual void cleanup () protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, ConjugateGradient, ConjugateGradient, SteepestDescent, SteepestDescent, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
virtual void cleanup () protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, ConjugateGradient, ConjugateGradient, SteepestDescent, SteepestDescent, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
Referenced by VertexMover::loop_over_mesh().
virtual void initialize (PatchData & pd, MsqError & err) protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, SteepestDescent, SteepestDescent, ConjugateGradient, ConjugateGradient, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
virtual void initialize (PatchData & pd, MsqError & err) protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, SteepestDescent, SteepestDescent, ConjugateGradient, ConjugateGradient, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
Referenced by VertexMover::loop_over_mesh().
virtual void initialize_mesh_iteration (PatchData & pd, MsqError & err) protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, SteepestDescent, SteepestDescent, ConjugateGradient, ConjugateGradient, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
Referenced by VertexMover::loop_over_mesh().
virtual void initialize_mesh_iteration (PatchData & pd, MsqError & err) protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, SteepestDescent, SteepestDescent, ConjugateGradient, ConjugateGradient, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
virtual double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
This is the "run" function of PatchDataUser. It can do anything really.
Implements QualityImprover.
double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
Improves the quality of the MeshSet, calling some methods specified in a class derived from VertexMover.
Parameters
const MeshSet &: this MeshSet is looped over. Only the mutable data members are changed (such as currentVertexInd).
Implements QualityImprover.
Definition at line 118 of file QualityImprover/VertexMover/VertexMover.cpp.
References TerminationCriterion::accumulate_outer(), TerminationCriterion::accumulate_patch(), VertexMover::cleanup(), TerminationCriterion::cleanup(), TerminationCriterion::cull_vertices(), PatchDataUser::get_global_patch(), QualityImprover::get_inner_termination_criterion(), MeshSet::get_next_patch(), QualityImprover::get_outer_termination_criterion(), PatchDataUser::get_patch_type(), PatchData::GLOBAL_PATCH, VertexMover::initialize(), VertexMover::initialize_mesh_iteration(), MsqError::INVALID_STATE, MSQ_CHKERR, MSQ_SETERR, VertexMover::objFunc, VertexMover::optimize_vertex_positions(), MeshSet::reset(), TerminationCriterion::reset_inner(), TerminationCriterion::reset_outer(), TerminationCriterion::reset_patch(), TerminationCriterion::set_debug_output_level(), QualityImprover::set_mesh_set(), TerminationCriterion::terminate(), VertexMover::terminate_mesh_iteration(), and PatchData::update_mesh().
Referenced by ShapeImprovementWrapper::run_instructions().
 {
   set_mesh_set(&ms);
     // Get the patch data to use for the first iteration
   bool next_patch = true;
   PatchData local_patch_data;
   PatchData* patch_data=0;
   if (get_global_patch() != 0) {
     if (get_patch_type() != PatchData::GLOBAL_PATCH) {
       MSQ_SETERR(err)("PatchDataUser::globalPatch should be NULL.", MsqError::INVALID_STATE);
       return 0;
     }
     patch_data = get_global_patch();
   }
   else {
     patch_data = &local_patch_data;
   }
     // Get termination criteria
   TerminationCriterion* outer_crit=this->get_outer_termination_criterion();
   TerminationCriterion* inner_crit=this->get_inner_termination_criterion();
   if(outer_crit == 0){
     MSQ_SETERR(err)("Termination Criterion pointer is Null", MsqError::INVALID_STATE);
     return 0.;
   }
   if(inner_crit == 0){
     MSQ_SETERR(err)("Termination Criterion pointer for inner loop is Null", MsqError::INVALID_STATE);
     return 0.;
   }
     // If using a local patch, suppress output of inner termination criterion
   if (get_patch_type() != PatchData::GLOBAL_PATCH) {
     inner_crit->set_debug_output_level(3);
   }
     // Initialize outer loop
   this->initialize(*patch_data, err);
   if (MSQ_CHKERR(err)) goto ERROR;
   outer_crit->reset_outer(ms, objFunc, err);
   if (MSQ_CHKERR(err)) goto ERROR;
     // Loop until outer termination criterion is met
   while (!outer_crit->terminate())
   {
     if (get_global_patch() == 0)
     {
       next_patch = ms.get_next_patch( *patch_data, this, err );
       if (MSQ_CHKERR(err)) goto ERROR;
     }
     if (!next_patch) // all vertices culled
       break;
       // Loop over each patch
     do
     {
         // Initialize for inner iteration
       this->initialize_mesh_iteration(*patch_data, err);
       if (MSQ_CHKERR(err)) goto ERROR;
       outer_crit->reset_patch( *patch_data, err );
       if (MSQ_CHKERR(err)) goto ERROR;
       inner_crit->reset_inner( *patch_data, objFunc, err );
       if (MSQ_CHKERR(err)) goto ERROR;
       inner_crit->reset_patch( *patch_data, err );
       if (MSQ_CHKERR(err)) goto ERROR;
         // Don't even call optimizer if inner termination
         // criterion has already been met.
       if (!inner_crit->terminate())
       {
           // Call optimizer - should loop on inner_crit->terminate()
         this->optimize_vertex_positions( *patch_data, err );
         if (MSQ_CHKERR(err)) goto ERROR;
           // Update for changes during inner iteration
           // (during optimizer loop)
         outer_crit->accumulate_patch( *patch_data, err );
         if (MSQ_CHKERR(err)) goto ERROR;
         inner_crit->cull_vertices( *patch_data, objFunc, err );
         if (MSQ_CHKERR(err)) goto ERROR;
         patch_data->update_mesh( err );
         if (MSQ_CHKERR(err)) goto ERROR;
       }
         // If a global patch, then we're done with the inner loop.
       next_patch = false;
       if (get_patch_type() != PatchData::GLOBAL_PATCH)
       {
         next_patch = ms.get_next_patch( *patch_data, this, err );
         if (MSQ_CHKERR(err)) goto ERROR;
       }
     } while (next_patch);
     this->terminate_mesh_iteration(*patch_data, err);
     if (MSQ_CHKERR(err)) goto ERROR;
     if (get_global_patch() == 0)
     {
       ms.reset(err);
       if (MSQ_CHKERR(err)) goto ERROR;
     }
     outer_crit->accumulate_outer( ms, err );
     if (MSQ_CHKERR(err)) goto ERROR;
   }
 ERROR:
     //call the criteria's cleanup funtions.
   outer_crit->cleanup(ms,err);
   inner_crit->cleanup(ms,err);
     //call the optimization cleanup function.
   this->cleanup();
   return 0.;
 }
virtual void optimize_vertex_positions (PatchData & pd, MsqError & err) protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, SteepestDescent, SteepestDescent, ConjugateGradient, ConjugateGradient, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
virtual void optimize_vertex_positions (PatchData & pd, MsqError & err) protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, SteepestDescent, SteepestDescent, ConjugateGradient, ConjugateGradient, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
Referenced by VertexMover::loop_over_mesh().
virtual void terminate_mesh_iteration (PatchData & , MsqError & err) protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, ConjugateGradient, SteepestDescent, ConjugateGradient, SteepestDescent, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
virtual void terminate_mesh_iteration (PatchData & , MsqError & err) protected pure virtual
Implemented in NonSmoothSteepestDescent, NonSmoothSteepestDescent, FeasibleNewton, FeasibleNewton, ConjugateGradient, SteepestDescent, ConjugateGradient, SteepestDescent, LaplacianSmoother, Randomize, LaplacianSmoother, Randomize, SmartLaplacianSmoother, SmartLaplacianSmoother, NullImprover, and NullImprover.
Referenced by VertexMover::loop_over_mesh().
Member Data Documentation
ObjectiveFunction * objFunc protected
Definition at line 77 of file includeLinks/VertexMover.hpp.
Referenced by NonSmoothSteepestDescent::compute_function(), NonSmoothSteepestDescent::compute_gradient(), ConjugateGradient::ConjugateGradient(), FeasibleNewton::FeasibleNewton(), ConjugateGradient::get_step(), LaplacianSmoother::LaplacianSmoother(), VertexMover::loop_over_mesh(), NonSmoothSteepestDescent::NonSmoothSteepestDescent(), SmartLaplacianSmoother::optimize_vertex_positions(), ConjugateGradient::optimize_vertex_positions(), SteepestDescent::optimize_vertex_positions(), FeasibleNewton::optimize_vertex_positions(), SmartLaplacianSmoother::SmartLaplacianSmoother(), SteepestDescent::SteepestDescent(), VertexMover::VertexMover(), and LaplacianSmoother::~LaplacianSmoother().
The documentation for this class was generated from the following files:
includeLinks/VertexMover.hpp
src/QualityImprover/VertexMover/VertexMover.hpp
QualityImprover/VertexMover/VertexMover.cpp
inks/VertexMover.cpp