Rocstar: Mesh::GenericElement Class Reference
Mesh::GenericElement Class Reference
#include <Mesh.H>
Public Member Functions
GenericElement (IndexType s=4)
void init (IndexType s=4)
IndexType size () const
GeoPrim::C3Point Centroid ()
void Centroid (std::vector< IndexType > &ec, NodalCoordinates &nc, GeoPrim::C3Point &centroid) const
IndexType nedges () const
IndexType nfaces () const
bool Inverted (std::vector< IndexType > &ec, NodalCoordinates &nc) const
bool ShapeOK (std::vector< IndexType > &ec, NodalCoordinates &nc) const
void ReOrient (std::vector< IndexType > &ec)
GeoPrim::C3Point Centroid (std::vector< IndexType > &ec, NodalCoordinates &nc) const
void get_face_connectivities (Connectivity &, const std::vector< IndexType > &) const
Face conn for given element.
void shape_func (const GeoPrim::CVector &, double[]) const
void dshape_func (const GeoPrim::CVector &, double[][3]) const
void jacobian (const GeoPrim::CPoint p[], const GeoPrim::CVector &nc, GeoPrim::CVector J[]) const
void interpolate (const GeoPrim::CVector f[], const GeoPrim::CVector &nc, GeoPrim::CVector &) const
void shapef_jacobian_at (const GeoPrim::CPoint &p, GeoPrim::CVector &natc, IndexType elnum, const Connectivity &ec, const NodalCoordinates &nc, GeoPrim::CVector &fvec, GeoPrim::CVector fjac[]) const
Protected Attributes
IndexType _size
Detailed Description
Definition at line 600 of file Mesh.H.
Constructor & Destructor Documentation
GenericElement (IndexType s = 4) inline
Definition at line 604 of file Mesh.H.
       : _size(s)
     {};
Member Function Documentation
GeoPrim::C3Point Centroid ()
Referenced by Mesh::GetMeshCentroids(), Inverted(), and ShapeOK().
void Centroid (std::vector< IndexType > & ec, NodalCoordinates & nc, GeoPrim::C3Point & centroid) const
Definition at line 1463 of file Mesh.C.
References i, and C3Vector::Init().
   {
     centroid.Init();
     IndexType i = 0;
     IndexType esize = ec.size();
     while(i < esize)
       centroid += GeoPrim::C3Point(nc[ec[i++]]);
     double scal = 1.0/(static_cast<double>(esize));
     centroid *= scal;
   };
GeoPrim::C3Point Centroid (std::vector< IndexType > & ec, NodalCoordinates & nc) const
Definition at line 1451 of file Mesh.C.
References i.
   {
     GeoPrim::C3Point centroid(0,0,0);
     IndexType i = 0;
     IndexType esize = ec.size();
     while(i < esize)
       centroid += GeoPrim::C3Point(nc[ec[i++]]);
     double scal = 1.0/(static_cast<double>(esize));
     return(centroid *= scal);
   };
void dshape_func (const GeoPrim::CVector & nc, double dSF[][3]) const
Definition at line 962 of file Mesh.C.
References _size, CVector::x(), CVector::y(), and CVector::z().
   {
     switch (_size) {
     case 4: {
       dSF[0][0] = -1;  dSF[0][1] = -1;  dSF[0][2] = -1;
       dSF[1][0] =  1;  dSF[1][1] =  0;  dSF[1][2] =  0;
       dSF[2][0] =  0;  dSF[2][1] =  1;  dSF[2][2] =  0;
       dSF[3][0] =  0;  dSF[3][1] =  0;  dSF[3][2] =  1;
       break;
     }
     case 10:{
       const double xi = nc.x();
       const double eta = nc.y();
       const double zeta = nc.z();
       const double alpha = (1. - xi - eta - zeta);
       dSF[0][0] = (4.*(xi+eta+zeta)-3.);      dSF[0][1] = dSF[0][0];                 dSF[0][2] = dSF[0][0];
       dSF[1][0] = 4.*xi - 1.;                 dSF[1][1] = 0;                         dSF[1][2] = 0;
       dSF[2][0] = 0;                          dSF[2][1] = 4.*eta - 1.;               dSF[2][2] = 0;
       dSF[3][0] = 0;                          dSF[3][1] = 0;                         dSF[3][2] = 4.*zeta - 1.;
       dSF[4][0] = 4.*(alpha - xi);            dSF[4][1] = -4.*xi;                    dSF[4][2] = -4.*xi;
       dSF[5][0] = -4.*eta;                    dSF[5][1] = 4.*(alpha - eta);          dSF[5][2] = -4.*eta;
       dSF[6][0] = -4.*zeta;                   dSF[6][1] = -4.*zeta;                  dSF[6][2] = 4.*(alpha - zeta);
       dSF[7][0] = 4.*eta;                     dSF[7][1] = 4.*xi;                     dSF[7][2] = 0;
       dSF[8][0] = 0;                          dSF[8][1] = 4.*zeta;                   dSF[8][2] = 4.*eta;
       dSF[9][0] = 4.*zeta;                    dSF[9][1] = 0;                         dSF[9][2] = 4.*xi;
       break;
     }
     case 8: {
       const double xi = nc.x();
       const double xi_minus = 1. - xi;
       const double eta = nc.y();
       const double eta_minus = 1. - eta;
       const double zeta = nc.z();
       const double zeta_minus = 1. - zeta;
       dSF[0][0] = -1.*eta_minus*zeta_minus;  dSF[0][1] = -1.*xi_minus*zeta_minus;  dSF[0][2] = -1.*xi_minus*eta_minus;
       dSF[1][0] = eta_minus*zeta_minus;      dSF[1][1] = -1.*xi*zeta_minus;        dSF[1][2] = -1.*xi*eta_minus;
       dSF[2][0] = eta*zeta_minus;            dSF[2][1] = xi*zeta_minus;            dSF[2][2] = -1.*xi*eta;
       dSF[3][0] = -1.*eta*zeta_minus;        dSF[3][1] = xi_minus*zeta_minus;      dSF[3][2] = -1.*xi_minus*eta;
       dSF[4][0] = -1.*eta_minus*zeta;        dSF[4][1] = -1.*xi_minus*zeta;        dSF[4][2] = xi_minus*eta_minus;
       dSF[5][0] = eta_minus*zeta;            dSF[5][1] = -1.*xi*zeta;              dSF[5][2] = xi*eta_minus;
       dSF[6][0] = eta*zeta;                  dSF[6][1] = xi*zeta;                  dSF[6][2] = xi*eta;
       dSF[7][0] = -1.*eta*zeta;              dSF[7][1] = xi_minus * zeta;          dSF[7][2] = xi_minus*eta;
       break;
     }
     default:
       std::cerr << "GenericElement::dshape_func:error: Unknown element type."
                 << std::endl;
       exit(1);
     }
   }
void get_face_connectivities (Connectivity & rv, const std::vector< IndexType > & e) const
Face conn for given element.
Tet Faces: 132 241 342 143 Pyr Faces: 1432 251 352 453 154 Prism Faces: 2541 3652 1463 132 456 Hex Faces: 1432 2651 3762 4873 1584 5678.
Returns a vector of lists where each list is the face connectivity for the i'th face of the element, and i is the index into the vector. This function was created as a utility for building overarching face containers for the whole mesh (on this processor).
Hex Faces: 1432 2651 3762 4873 1584 5678
Definition at line 1714 of file Mesh.C.
References _size, and Mesh::Connectivity::Resize().
Referenced by Mesh::Connectivity::BuildFaceConnectivity().
   {
     //    std::vector<std::vector<IndexType> > rv;
     switch(_size){
     case 4:   // Tet Faces:      132 241 342 143
     case 10:
       rv.Resize(4);
       rv[0].resize(3);
       //      std::vector<Mesh::IndexType>(rv[0]).swap(rv[0]);
       rv[0][0] = e[0]; // 1
       rv[0][1] = e[2]; // 3
       rv[0][2] = e[1]; // 2
       rv[1].resize(3);
       //      std::vector<Mesh::IndexType>(rv[1]).swap(rv[1]);
       rv[1][0] = e[1]; // 2
       rv[1][1] = e[3]; // 4
       rv[1][2] = e[0]; // 1
       rv[2].resize(3);
       //      std::vector<Mesh::IndexType>(rv[2]).swap(rv[2]);
       rv[2][0] = e[2]; // 3
       rv[2][1] = e[3]; // 4
       rv[2][2] = e[1]; // 2
       rv[3].resize(3);
       //      std::vector<Mesh::IndexType>(rv[3]).swap(rv[3]);
       rv[3][0] = e[0]; // 1
       rv[3][1] = e[3]; // 4
       rv[3][2] = e[2]; // 3
       break;
     case 5:   // Pyr Faces:      1432 251 352 453 154
     case 13:
       rv.Resize(5);
       rv[0].resize(4);
       //      std::vector<Mesh::IndexType>(rv[0]).swap(rv[0]);
       rv[0][0] = e[0]; // 1
       rv[0][1] = e[3]; // 4
       rv[0][2] = e[2]; // 3
       rv[0][3] = e[1]; // 2
       rv[1].resize(3);
       //      std::vector<Mesh::IndexType>(rv[1]).swap(rv[1]);
       rv[1][0] = e[1]; // 2
       rv[1][1] = e[4]; // 5
       rv[1][2] = e[0]; // 1
       rv[2].resize(3);
       //      std::vector<Mesh::IndexType>(rv[2]).swap(rv[2]);
       rv[2][0] = e[2]; // 3
       rv[2][1] = e[4]; // 5
       rv[2][2] = e[1]; // 2
       rv[3].resize(3);
       //      std::vector<Mesh::IndexType>(rv[3]).swap(rv[3]);
       rv[3][0] = e[3]; // 4
       rv[3][1] = e[4]; // 5
       rv[3][2] = e[2]; // 3
       rv[4].resize(3);
       //      std::vector<Mesh::IndexType>(rv[4]).swap(rv[4]);
       rv[4][0] = e[0]; // 1
       rv[4][1] = e[4]; // 5
       rv[4][2] = e[3]; // 4
       break;
     case 6:   // Prism Faces:    2541 3652 1463 132 456
     case 15:
       rv.Resize(5);
       rv[0].resize(4);
       //      std::vector<Mesh::IndexType>(rv[0]).swap(rv[0]);
       rv[0][0] = e[1]; // 2
       rv[0][1] = e[4]; // 5
       rv[0][2] = e[3]; // 4
       rv[0][3] = e[0]; // 1
       rv[1].resize(4);
       //      std::vector<Mesh::IndexType>(rv[1]).swap(rv[1]);
       rv[1][0] = e[2]; // 3
       rv[1][1] = e[5]; // 6
       rv[1][2] = e[4]; // 5
       rv[1][3] = e[1]; // 2
       rv[2].resize(4);
       //      std::vector<Mesh::IndexType>(rv[2]).swap(rv[2]);
       rv[2][0] = e[0]; // 1
       rv[2][1] = e[3]; // 4
       rv[2][2] = e[5]; // 6
       rv[2][3] = e[2]; // 3
       rv[3].resize(3);
       //      std::vector<Mesh::IndexType>(rv[3]).swap(rv[3]);
       rv[3][0] = e[0]; // 1
       rv[3][1] = e[2]; // 3
       rv[3][2] = e[1]; // 2
       rv[4].resize(3);
       //      std::vector<Mesh::IndexType>(rv[4]).swap(rv[4]);
       rv[4][0] = e[4]; // 5
       rv[4][1] = e[5]; // 6
       rv[4][2] = e[3]; // 4
       break;
     case 8:
     case 20:
       rv.Resize(6);
       rv[0].resize(4);
       //      std::vector<Mesh::IndexType>(rv[0]).swap(rv[0]);
       rv[0][0] = e[0]; // 1
       rv[0][1] = e[3]; // 4
       rv[0][2] = e[2]; // 3
       rv[0][3] = e[1]; // 2
       rv[1].resize(4);
       //      std::vector<Mesh::IndexType>(rv[1]).swap(rv[1]);
       rv[1][0] = e[1]; // 2
       rv[1][1] = e[5]; // 6
       rv[1][2] = e[4]; // 5
       rv[1][3] = e[0]; // 1
       rv[2].resize(4);
       //      std::vector<Mesh::IndexType>(rv[2]).swap(rv[2]);
       rv[2][0] = e[2]; // 3
       rv[2][1] = e[6]; // 7
       rv[2][2] = e[5]; // 6
       rv[2][3] = e[1]; // 2
       rv[3].resize(4);
       //      std::vector<Mesh::IndexType>(rv[3]).swap(rv[3]);
       rv[3][0] = e[3]; // 4
       rv[3][1] = e[7]; // 8
       rv[3][2] = e[6]; // 7
       rv[3][3] = e[2]; // 3
       rv[4].resize(4);
       //      std::vector<Mesh::IndexType>(rv[4]).swap(rv[4]);
       rv[4][0] = e[0]; // 1
       rv[4][1] = e[4]; // 5
       rv[4][2] = e[7]; // 8
       rv[4][3] = e[3]; // 4
       rv[5].resize(4);
       //      std::vector<Mesh::IndexType>(rv[5]).swap(rv[5]);
       rv[5][0] = e[4]; // 5
       rv[5][1] = e[5]; // 6
       rv[5][2] = e[6]; // 7
       rv[5][3] = e[7]; // 8
       break;
     default:
       rv.Resize(0);
     }
     //    return(rv);
   };
void init (IndexType s = 4) inline
Definition at line 607 of file Mesh.H.
References _size, and s.
     {
       _size = s;
     };
void interpolate (const GeoPrim::CVector f[], const GeoPrim::CVector & nc, GeoPrim::CVector & v) const
Definition at line 1066 of file Mesh.C.
References _size, CVector::x(), CVector::y(), and CVector::z().
   {
     const double xi = nc.x();
     const double eta = nc.y();
     const double zeta = nc.z();
     switch(_size) {
     case 4: {
       v = f[0];
       v += (((f[1]-f[0])*=xi) += ((f[2]-f[0])*=eta) += ((f[3] - f[0])*=zeta));
       //    v += (f[1]-f[0])*=xi+=(f[2]-f[0])*=eta+=(f[3]-f[0])*=zeta;
       break;
     }
     case 10: {
       const double alpha = (1.-xi-eta-zeta);
       v = (alpha*(1.-2.*(xi+eta+zeta))*f[0] +
            xi*(2.*xi-1.)*f[1] +
            eta*(2.*eta-1.)*f[2] +
            zeta*(2.*zeta-1.)*f[3] +
            4.*xi*alpha*f[4] +
            4.*eta*alpha*f[5] +
            4.*zeta*alpha*f[6] +
            4.*xi*eta*f[7] +
            4.*eta*zeta*f[8] +
            4.*zeta*xi*f[9]);
       break;
     }
     case 8: {
       const double xi = nc.x();
       const double xi_minus = 1. - xi;
       const double eta = nc.y();
       const double eta_minus = 1. - eta;
       const double zeta = nc.z();
       const double zeta_minus = 1. - zeta;
       v = (xi_minus*eta_minus*zeta_minus*f[0] +
            xi*eta_minus*zeta_minus*f[1] +
            xi*eta*zeta_minus*f[2] +
            xi_minus*eta*zeta_minus*f[3] +
            xi_minus*eta_minus*zeta*f[4] +
            xi*eta_minus*zeta*f[5] +
            xi*eta*zeta*f[6] +
            xi_minus*eta*zeta*f[7]);
       break;
     }
     default:
      std::cerr << "interpolate::error Cannot handle this element "
            << "type (yet)." << std::endl;
       exit(1);
     }
   }
bool Inverted (std::vector< IndexType > & ec, NodalCoordinates & nc) const
Definition at line 1475 of file Mesh.C.
References _size, Centroid(), C3Facet::Centroid(), and C3Facet::Normal().
Referenced by main().
   {
     // Form the vector V1 from element centroid to first face centroid
     // Dot V1 with the first face normal
     // return(result < 0)
     if(_size == 4 || _size == 10){ // Tet Faces:      132 241 342 143
       GeoPrim::C3Point p1(nc[ec[0]]);
       GeoPrim::C3Point p2(nc[ec[2]]);
       GeoPrim::C3Point p3(nc[ec[1]]);
       GeoPrim::C3Facet aface(&p1,&p2,&p3);
       GeoPrim::C3Vector avec(Centroid(ec,nc),aface.Centroid());
       return((avec*aface.Normal()) < 0);
     }
     else if(_size == 5 || _size == 13){            // Pyr Faces:      1432 251 352 453 154
       GeoPrim::C3Point p1(nc[ec[0]]);
       GeoPrim::C3Point p2(nc[ec[3]]);
       GeoPrim::C3Point p3(nc[ec[2]]);
       GeoPrim::C3Point p4(nc[ec[1]]);
       GeoPrim::C3Facet bface(&p1,&p2,&p3,&p4);
       GeoPrim::C3Vector bvec(Centroid(ec,nc),bface.Centroid());
       return((bvec*bface.Normal()) < 0);
     }
     else if(_size == 6 || _size == 15){            // Prism Faces:    2541 3652 1463 132 456
       GeoPrim::C3Point p1(nc[ec[1]]);
       GeoPrim::C3Point p2(nc[ec[4]]);
       GeoPrim::C3Point p3(nc[ec[3]]);
       GeoPrim::C3Point p4(nc[ec[0]]);
       GeoPrim::C3Facet cface(&p1,&p2,&p3,&p4);
       GeoPrim::C3Vector cvec(Centroid(ec,nc),cface.Centroid());
       return((cvec*cface.Normal()) < 0);
     }
     else if(_size == 8 || _size == 20){            // Hex Faces:      1432 2651 3762 4873 1584 5678
       GeoPrim::C3Point p1(nc[ec[0]]);
       GeoPrim::C3Point p2(nc[ec[3]]);
       GeoPrim::C3Point p3(nc[ec[2]]);
       GeoPrim::C3Point p4(nc[ec[1]]);
       GeoPrim::C3Facet dface(&p1,&p2,&p3,&p4);
       GeoPrim::C3Vector dvec(Centroid(ec,nc),dface.Centroid());
       return((dvec*dface.Normal()) < 0);
     }
     else
       return(false);
     return(false);
   };
void jacobian (const GeoPrim::CPoint p[], const GeoPrim::CVector & nc, GeoPrim::CVector J[]) const
Definition at line 1016 of file Mesh.C.
References _size, CVector::x(), CVector::y(), and CVector::z().
Referenced by shapef_jacobian_at().
   {
     switch(_size){
     case 4: {
       J[0] = p[1] - p[0];
       J[1] = p[2] - p[0];
       J[2] = p[3] - p[0];
       break;
     }
     case 10: {
       const double xi = nc.x();
       const double eta = nc.y();
       const double zeta = nc.z();
       const double alpha = (1. - xi - eta - zeta);
       GeoPrim::CPoint P(p[0]*(4.*(xi+eta+zeta)-3.));
       J[0] = ((p[9]-p[6])*=4.*zeta)+=((p[7]-p[5])*=4.*eta)+=
         (p[4]*(4.*(alpha-xi))+p[1]*(4.*xi-1.)+P);
       J[1] = ((p[8]-p[6])*=4.*zeta)+=((p[7]-p[4])*=4.*xi)+=
         (p[5]*(4.*(alpha-eta))+p[2]*(4.*eta-1.)+P);
       J[2] = ((p[9]-p[4])*=4.*xi)+=((p[8]-p[5])*=4.*eta)+=
         (p[6]*(4.*(alpha-zeta))+p[3]*(4.*zeta-1.)+P);
       break;
     }
     case 8: {
       const double xi = nc.x();
       const double xi_minus = 1. - xi;
       const double eta = nc.y();
       const double eta_minus = 1. - eta;
       const double zeta = nc.z();
       const double zeta_minus = 1. - zeta;
       J[0] = ((p[6]-p[7])*=eta*zeta)+=((p[5]-p[4])*=eta_minus*zeta)+=
         ((p[2]-p[3])*=eta*zeta_minus)+=((p[1]-p[0])*=eta_minus*zeta_minus);
       J[1] = ((p[7]-p[4])*=xi_minus*zeta)+=((p[6]-p[5])*=xi*zeta)+=
         ((p[3]-p[0])*=xi_minus*zeta_minus)+=((p[2]-p[1])*=xi*zeta_minus);
       J[2] = ((p[7]-p[3])*=xi_minus*eta)+=((p[6]-p[2])*=xi*eta)+=
         ((p[5]-p[1])*=xi*eta_minus)+=((p[4]-p[0])*=xi_minus*eta_minus);
       break;
     }
     default:
       std::cerr << "GenericElement::jacobian:Error: Cannot handle this"
                 << " element size (yet)." << std::endl;
       exit(1);
     }
   }
IndexType nedges () const inline
Definition at line 617 of file Mesh.H.
References _size.
     {
       switch(_size){
       case 4:
       case 10:
         // tet
         return (6);
       case 8:
       case 20:
         // hex
         return (12);
       case 5:
       case 13:
         // pyr
         return(8);
       case 6:
       case 15:
         // pris
         return(9);
       default:
         return(0);
       }
       return(0);
     };
IndexType nfaces () const inline
Definition at line 641 of file Mesh.H.
References _size.
Referenced by Mesh::Connectivity::BuildFaceConnectivity(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_rflo_recvmetrics(), plag_rflo_sendmetrics(), plag_rflo_sendrecvmetrics(), rflu_modstencilsutils::rflu_addcelllayer_1d(), rflu_modstencilscells::rflu_buildc2cstencil_1d(), rflu_computeenerdissoles(), rflu_computeintegral3oles(), rflu_modgeometrytools::rflu_computelinecellxsectfast(), rflu_modgeometrytools::rflu_computelinecellxsectsafe(), rflu_modoles::rflu_createintegralsoles(), rflu_modoles::rflu_createstencilsweightsoles(), rflu_modresidual::rflu_getresidualsupport1(), rflu_modincelltest::rflu_ict_testincell(), rflu_modincelltest::rflu_ict_testincellfancy(), rflu_modincelltest::rflu_ict_testincelllohner(), rflu_modfacelist::rflu_insertintocell2facelist(), rflu_modpartitionregion::rflu_part_partitionregion(), rflu_modreadwritegridspeeds::rflu_readgridspeedsascii(), rflu_modreadwritegridspeeds::rflu_readgridspeedsbinary(), rflu_modtecplotutils::rflu_tec_writezoneinterf(), turb_allocatememory(), turb_coviscousfluxes(), and turb_lescalceddyvis().
     {
       switch(_size){
       case 4:
       case 10:
         // tet
         return(4);
       case 8:
       case 20:
         // hex
         return(6);
       case 5:
       case 13:
         // pyr
         return(5);
       case 6:
       case 15:
         // pris
         return(5);
       default:
         return(0);
       }
       return(0);
     };
void ReOrient (std::vector< IndexType > & ec)
Hex Faces: 1432 2651 3762 4873 1584 5678
Definition at line 1601 of file Mesh.C.
References _size.
Referenced by main().
   {
     IndexType temp;
     switch(_size){
     case 4:   // Tet Faces:      132 241 342 143
     case 10:
       temp = ec[1];
       ec[1] = ec[0];
       ec[0] = temp;
       break;
     case 5:   // Pyr Faces:      1432 251 352 453 154
     case 13:
       temp = ec[2];
       ec[2] = ec[0];
       ec[0] = ec[2];
       break;
     case 6:   // Prism Faces:    2541 3652 1463 132 456
     case 15:
       temp = ec[1];
       ec[1] = ec[0];
       ec[0] = ec[1];
       temp = ec[4];
       ec[4] = ec[3];
       ec[3] = temp;
       break;
     case 8:
     case 20:
       temp = ec[2];
       ec[2] = ec[0];
       ec[0] = ec[2];
       temp = ec[6];
       ec[6] = ec[4];
       ec[4] = temp;
       break;
     }
   };
void shape_func (const GeoPrim::CVector & nc, double SF[]) const
Definition at line 906 of file Mesh.C.
References _size, CVector::x(), CVector::y(), and CVector::z().
Referenced by shapef_jacobian_at().
   {
     switch (_size) {
       // Tets are 4 nodes or 10
     case 4: {
       SF[0] = 1. - nc.x() - nc.y() - nc.z();
       SF[1] = nc.x();
       SF[2] = nc.y();
       SF[3] = nc.z();
       break;
     }
     case 10: {
       const double xi = nc.x();
       const double eta = nc.y();
       const double zeta = nc.z();
       const double alpha = (1. - xi - eta - zeta);
       SF[0] = alpha*(1. - 2.*(xi + eta + zeta));
       SF[1] = xi *(2.* xi - 1.);
       SF[2] = eta *(2. * eta - 1.);
       SF[3] = zeta *(2. * zeta - 1.);
       SF[4] = 4.* xi * alpha;
       SF[5] = 4.* eta * alpha;
       SF[6] = 4.* zeta * alpha;
       SF[7] = 4. * xi * eta;
       SF[8] = 4. * eta * zeta;
       SF[9] = 4. * xi * zeta;
       break;
     }
       // Hex's are 8 nodes or 20
     case 8: {
       const double xi = nc.x();
       const double xi_minus = 1. - xi;
       const double eta = nc.y();
       const double eta_minus = 1. - eta;
       const double zeta = nc.z();
       const double zeta_minus = 1. - zeta;
       SF[0] = xi_minus * eta_minus * zeta_minus;
       SF[1] = xi * eta_minus * zeta_minus;
       SF[2] = xi * eta * zeta_minus;
       SF[3] = xi_minus * eta * zeta_minus;
       SF[4] = xi_minus * eta_minus * zeta;
       SF[5] = xi * eta_minus * zeta;
       SF[6] = xi * eta * zeta;
       SF[7] = xi_minus * eta * zeta;
       break;
     }
     default:
       std::cerr << "GenericElement::shape_func:Error: unkown element type."
                 << std::endl;
       exit(1);
     }
   }
void shapef_jacobian_at (const GeoPrim::CPoint & p, GeoPrim::CVector & natc, IndexType elnum, const Connectivity & ec, const NodalCoordinates & nc, GeoPrim::CVector & fvec, GeoPrim::CVector fjac[]) const
Definition at line 883 of file Mesh.C.
References _size, i, CVector::init(), jacobian(), Mesh::Connectivity::Node(), shape_func(), and GeoPrim::Transpose().
   {
     GeoPrim::CPoint P[(const IndexType)_size];
     double SF[(const IndexType)_size];
     this->shape_func(natc,SF);
     fvec.init(-1.0*p);
     for(IndexType i = 0;i < _size;i++){
       //      std::cout << "debugging: " << GeoPrim::CPoint(nc[ec.Node(elnum,i+1)]) << std::endl;
       P[i].init(nc[ec.Node(elnum,i+1)]);
       fvec += SF[i]*P[i];
     }
     this->jacobian(P,natc,fjac);
     Transpose(fjac);
   }
bool ShapeOK (std::vector< IndexType > & ec, NodalCoordinates & nc) const
Definition at line 1521 of file Mesh.C.
References _size, Centroid(), C3Facet::Centroid(), C3Plane::contains_point(), and C3Facet::Normal().
Referenced by main().
   {
     // ensure element is not poorly shaped
     //  make sure point 3 is not co-linear with points 1 and 2
     //  make sure 4th point not co-planar with base
     if(_size == 4){ // Tet Faces:      132 241 342 143
       GeoPrim::C3Point p1(nc[ec[0]]);
       GeoPrim::C3Point p2(nc[ec[2]]);
       GeoPrim::C3Point p3(nc[ec[1]]);
       GeoPrim::C3Point p4(nc[ec[3]]);
       GeoPrim::C3Plane plane(p1,p2,p3);
       return(!plane.contains_point(p4));
     }
     // ensure element in not poorly shaped
     //   make sure quad base is planar
     //   make sure area of quad base is positive
     //   make sure 5th point not co-planar with quad base
     else if(_size == 5){            // Pyr Faces:      1432 251 352 453 154
       GeoPrim::C3Point p1(nc[ec[0]]);
       GeoPrim::C3Point p2(nc[ec[3]]);
       GeoPrim::C3Point p3(nc[ec[2]]);
       GeoPrim::C3Point p4(nc[ec[1]]);
       GeoPrim::C3Point p5(nc[ec[4]]);
       GeoPrim::C3Facet bface(&p1,&p2,&p3,&p4);
       GeoPrim::C3Vector bvec(Centroid(ec,nc),bface.Centroid());
       return((bvec*bface.Normal()) < 0);
     }
     // ensure element is not poorly shaped
     //   make sure both triangular faces are triangles (i.e. not co-linear)
     //   make sure no points of opposing face is co-planar with base
     //   make sure quad faces are planar
     //   make sure quad faces have positive area
     else if(_size == 6){            // Prism Faces:    2541 3652 1463 132 456
       GeoPrim::C3Point p1(nc[ec[1]]);
       GeoPrim::C3Point p2(nc[ec[4]]);
       GeoPrim::C3Point p3(nc[ec[3]]);
       GeoPrim::C3Point p4(nc[ec[0]]);
       GeoPrim::C3Facet cface(&p1,&p2,&p3,&p4);
       GeoPrim::C3Vector cvec(Centroid(ec,nc),cface.Centroid());
       return((cvec*cface.Normal()) < 0);
     }
     // ensure element is not poorly shaped
     //   make sure each face is planar
     //   make sure each face has positive area
     else if(_size == 8){            // Hex Faces:      1432 2651 3762 4873 1584 5678
       GeoPrim::C3Point p1(nc[ec[0]]);
       GeoPrim::C3Point p2(nc[ec[1]]);
       GeoPrim::C3Point p3(nc[ec[2]]);
       GeoPrim::C3Point p4(nc[ec[3]]);
       GeoPrim::C3Point p5(nc[ec[4]]);
       GeoPrim::C3Point p6(nc[ec[5]]);
       GeoPrim::C3Point p7(nc[ec[6]]);
       GeoPrim::C3Point p8(nc[ec[7]]);
       GeoPrim::C3Plane plane1(p1,p4,p3);
       if(!plane1.contains_point(p2))
         return(false);
       GeoPrim::C3Plane plane2(p2,p6,p5);
       if(!plane2.contains_point(p1))
         return(false);
       GeoPrim::C3Plane plane3(p3,p7,p6);
       if(!plane3.contains_point(p2))
         return(false);
       GeoPrim::C3Plane plane4(p4,p8,p7);
       if(!plane4.contains_point(p3))
         return(false);
       GeoPrim::C3Plane plane5(p1,p5,p8);
       if(!plane5.contains_point(p4))
         return(false);
       GeoPrim::C3Plane plane6(p5,p6,p7);
       if(!plane6.contains_point(p8))
         return(false);
     }
     else
       return(true);
     return(true);
   };
IndexType size () const inline
Definition at line 611 of file Mesh.H.
References _size.
     {
       return(_size);
     };
Member Data Documentation
IndexType _size protected
Definition at line 602 of file Mesh.H.
Referenced by dshape_func(), get_face_connectivities(), init(), interpolate(), Inverted(), jacobian(), nedges(), nfaces(), ReOrient(), shape_func(), shapef_jacobian_at(), ShapeOK(), and size().
The documentation for this class was generated from the following files:
Mesh.H
Mesh.C