Rocstar: Point_3< T > Class Template Reference
Point_3< T > Class Template Reference
#include <mapbasic.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Point_3_base RPoint_3
typedef R::Vector_3_base RVector_3
Public Member Functions
Point_3 ()
Point_3 (T t)
Point_3 (Origin)
Point_3 (T a, T b, T c)
T & operator[] (const int i)
const T & operator[] (const int i) const
Point_3 & operator+= (const Vector_3< T > &v)
Assign operators.
Point_3 & operator-= (const Vector_3< T > &v)
Point_3 operator+ (const Vector_3< T > &v) const
Arithmatic operators.
Point_3 operator- (const Vector_3< T > &v) const
Vector_3< T > operator- (const Point_3 &v) const
bool operator== (const Point_3 &p) const
bool operator!= (const Point_3 &p) const
bool operator< (const Point_3 &v) const
bool is_origin () const
Point_3 ()
Point_3 (const Origin &o)
Point_3 (const CGAL::Point_3< R > &p)
Point_3 (const RPoint_3 &p)
Point_3 (const RT &hx, const RT &hy, const RT &hz)
Point_3 (const RT &hx, const RT &hy, const RT &hz, const RT &hw)
bool operator== (const CGAL::Point_3< R > &p) const
bool operator!= (const CGAL::Point_3< R > &p) const
RT hx () const
RT hy () const
RT hz () const
RT hw () const
FT x () const
FT y () const
FT z () const
RT homogeneous (int i) const
FT cartesian (int i) const
FT operator[] (int i) const
int dimension () const
Bbox_3 bbox () const
CGAL::Point_3< R > transform (const CGAL::Aff_transformation_3< R > &t) const
Point_3 ()
Point_3 (Type a, Type b, Type c)
Type & operator[] (const int i)
const Type & operator[] (const int i) const
Protected Attributes
Type _x
Type _y
Type _z
Private Types
typedef double Type
Private Member Functions
Point_3 (const RVector_3 &v)
Friends
CGAL_FRIEND_INLINE
CGAL::Point_3< R >
vector_to_point_conversion CGAL_NULL_TMPL_ARGS (const CGAL::Vector_3< R > &v)
Detailed Description
template<class T>
class Point_3< T >
Definition at line 147 of file mapbasic.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 85 of file Point_3.h.
typedef R_ R
Definition at line 83 of file Point_3.h.
typedef R::Point_3_base RPoint_3
Definition at line 86 of file Point_3.h.
typedef R::RT RT
Definition at line 84 of file Point_3.h.
typedef R::Vector_3_base RVector_3
Definition at line 87 of file Point_3.h.
typedef double Type private
Definition at line 43 of file plot3d.C.
Constructor & Destructor Documentation
Point_3 () inline
Definition at line 149 of file mapbasic.h.
Referenced by Point_3< Real >::operator+(), and Point_3< Real >::operator-().
 {}
Point_3 (T t) inline explicit
Definition at line 150 of file mapbasic.h.
 : Vector_3<T>(t) {}
Point_3 (Origin) inline
Definition at line 151 of file mapbasic.h.
 : Vector_3<T>(0, 0, 0) {}
Point_3 (T a, T b, T c) inline
Definition at line 153 of file mapbasic.h.
 : Vector_3<T>(a, b, c) {}
Point_3 () inline
Definition at line 95 of file Point_3.h.
   {}
Point_3 (const Origin & o) inline
Definition at line 97 of file Point_3.h.
                            : RPoint_3(o)
   {}
Point_3 (const CGAL::Point_3< R > & p) inline
Definition at line 99 of file Point_3.h.
                                    : RPoint_3( (const RPoint_3& )p )
   {}
Point_3 (const RPoint_3< T > & p) inline
Definition at line 101 of file Point_3.h.
                               : RPoint_3(p)
   {}
Point_3 (const RT & hx, const RT & hy, const RT & hz) inline
Definition at line 103 of file Point_3.h.
     : RPoint_3(hx, hy, hz)
   {}
Point_3 (const RT & hx, const RT & hy, const RT & hz, const RT & hw) inline
Definition at line 106 of file Point_3.h.
     : RPoint_3(hx, hy, hz, hw)
   {}
Point_3 (const RVector_3 & v) inline private
Definition at line 157 of file Point_3.h.
                                : RPoint_3(v)
   {}
Point_3 () inline
Definition at line 45 of file plot3d.C.
 {}
Point_3 (Type a, Type b, Type c) inline
Definition at line 46 of file plot3d.C.
 : _x(a), _y(b), _z(c) {}
Member Function Documentation
Bbox_3 bbox () const inline
Definition at line 150 of file Point_3.h.
   { return RPoint_3::bbox(); }
FT cartesian (int i) const inline
Definition at line 141 of file Point_3.h.
Referenced by Point_3< Real >::operator[]().
   { return RPoint_3::cartesian(i); }
int dimension () const inline
Definition at line 147 of file Point_3.h.
   { return 3; }
RT homogeneous (int i) const inline
Definition at line 138 of file Point_3.h.
   { return RPoint_3::homogeneous(i); }
RT hw () const inline
Definition at line 126 of file Point_3.h.
   { return RPoint_3::hw(); }
RT hx () const inline
Definition at line 117 of file Point_3.h.
   { return RPoint_3::hx(); }
RT hy () const inline
Definition at line 120 of file Point_3.h.
   { return RPoint_3::hy(); }
RT hz () const inline
Definition at line 123 of file Point_3.h.
   { return RPoint_3::hz(); }
bool is_origin () const inline
Definition at line 183 of file mapbasic.h.
 { return _x==0&&_y==0&&_z==0; }
bool operator!= (const CGAL::Point_3< R > & p) const inline
Definition at line 113 of file Point_3.h.
   { return !(*this == p); }
bool operator!= (const Point_3< T > & p) const inline
Definition at line 177 of file mapbasic.h.
   { return x()!=p.x() || y()!=p.y() || z()!=p.z(); }
Point_3 operator+ (const Vector_3< T > & v) const inline
Arithmatic operators.
Definition at line 167 of file mapbasic.h.
   { return Point_3(_x+v.x(), _y+v.y(), _z+v.z()); }
Point_3& operator+= (const Vector_3< T > & v) inline
Assign operators.
Definition at line 161 of file mapbasic.h.
   { _x+=v.x(); _y+=v.y(); _z+=v.z(); return *this; }
Point_3 operator- (const Vector_3< T > & v) const inline
Definition at line 169 of file mapbasic.h.
   { return Point_3(_x-v.x(), _y-v.y(), _z-v.z()); }
Vector_3<T> operator- (const Point_3< T > & v) const inline
Definition at line 171 of file mapbasic.h.
   { return Vector_3<T>(_x-v.x(), _y-v.y(), _z-v.z()); }
Point_3& operator-= (const Vector_3< T > & v) inline
Definition at line 163 of file mapbasic.h.
   { _x-=v.x(); _y-=v.y(); _z-=v.z(); return *this; }
bool operator< (const Point_3< T > & v) const inline
Definition at line 180 of file mapbasic.h.
   { return Vector_3<T>::operator<(v); }
bool operator== (const CGAL::Point_3< R > & p) const inline
Definition at line 110 of file Point_3.h.
   { return RPoint_3::operator==(p); }
bool operator== (const Point_3< T > & p) const inline
Definition at line 174 of file mapbasic.h.
   { return x()==p.x() && y()==p.y() && z()==p.z(); }
Type& operator[] (const int i) inline
Definition at line 47 of file plot3d.C.
 { return (&_x)[i]; }
const Type& operator[] (const int i) const inline
Definition at line 48 of file plot3d.C.
 { return (&_x)[i]; }
FT operator[] (int i) const inline
Definition at line 144 of file Point_3.h.
   { return cartesian(i); }
T& operator[] (const int i) inline
Definition at line 154 of file mapbasic.h.
 { return (&_x)[i]; }
const T& operator[] (const int i) const inline
Definition at line 155 of file mapbasic.h.
 { return (&_x)[i]; }
CGAL::Point_3<R> transform (const CGAL::Aff_transformation_3< R > & t) const inline
Definition at line 153 of file Point_3.h.
   { return RPoint_3::transform(t); }
FT x () const inline
Definition at line 129 of file Point_3.h.
Referenced by collect_coincident_nodes(), Pane_connectivity::create_b2map(), Pane_connectivity::determine_coisolated_nodes(), intersect_bbox(), Point_3< Real >::operator!=(), Point_3< Real >::operator-(), Point_3< Real >::operator==(), and RFC_Pane_base::write_tec_sub().
   { return RPoint_3::x(); }
FT y () const inline
Definition at line 132 of file Point_3.h.
Referenced by collect_coincident_nodes(), Pane_connectivity::create_b2map(), Pane_connectivity::determine_coisolated_nodes(), intersect_bbox(), Point_3< Real >::operator!=(), Point_3< Real >::operator-(), Point_3< Real >::operator==(), and RFC_Pane_base::write_tec_sub().
   { return RPoint_3::y(); }
FT z () const inline
Definition at line 135 of file Point_3.h.
Referenced by collect_coincident_nodes(), Pane_connectivity::create_b2map(), Pane_connectivity::determine_coisolated_nodes(), intersect_bbox(), Point_3< Real >::operator!=(), Point_3< Real >::operator-(), Point_3< Real >::operator==(), and RFC_Pane_base::write_tec_sub().
   { return RPoint_3::z(); }
Friends And Related Function Documentation
CGAL_FRIEND_INLINE CGAL::Point_3<R> vector_to_point_conversion CGAL_NULL_TMPL_ARGS (const CGAL::Vector_3< R > & v) friend
Member Data Documentation
Type _x protected
Definition at line 51 of file plot3d.C.
Referenced by Point_3< Real >::is_origin(), Point_3< Real >::operator+(), Point_3< Real >::operator+=(), Point_3< Real >::operator-(), Point_3< Real >::operator-=(), and Point_3< Real >::operator[]().
Type _y protected
Definition at line 51 of file plot3d.C.
Referenced by Point_3< Real >::is_origin(), Point_3< Real >::operator+(), Point_3< Real >::operator+=(), Point_3< Real >::operator-(), and Point_3< Real >::operator-=().
Type _z protected
Definition at line 51 of file plot3d.C.
Referenced by Point_3< Real >::is_origin(), Point_3< Real >::operator+(), Point_3< Real >::operator+=(), Point_3< Real >::operator-(), and Point_3< Real >::operator-=().
The documentation for this class was generated from the following files:
mapbasic.h
Point_3.h
plot3d.C