Rocstar: MeshPointIdToGlobalIdMap Class Reference
MeshPointIdToGlobalIdMap Class Reference
#include <MeshPointIdToGlobalIdMap.hpp>
Public Member Functions
MeshPointIdToGlobalIdMap ()
Constructor.
~MeshPointIdToGlobalIdMap ()
Destructor.
bool exists (const int meshPaneId, const int meshPointId)
Checks if the point meshPointId of the mesh associated with the provided meshPaneId exists in this MeshPointIdToGlobalIdMap instance.
int getGlobalId (const int meshPaneId, const int meshPointId)
Returns the assigned global id to meshPointId of the mesh associated with the provided meshPaneId.
void insert (const int meshPaneId, const int meshPointId, const int globalId)
This method constructs a new key-pair for the meshPaneId and meshPointId which maps into globalId and inserts it into the data-structure.
int size () const
Returns the size of the map.
Private Attributes
std::map< std::pair< int, int >
, int > local2global
Detailed Description
Definition at line 19 of file MeshPointIdToGlobalIdMap.hpp.
Constructor & Destructor Documentation
MeshPointIdToGlobalIdMap () inline
Constructor.
Postcondition
this ->size() == 0.
Definition at line 30 of file MeshPointIdToGlobalIdMap.hpp.
 { }
~MeshPointIdToGlobalIdMap () inline
Destructor.
Definition at line 35 of file MeshPointIdToGlobalIdMap.hpp.
 { this ->local2global.clear( ); }
Member Function Documentation
bool exists (const int meshPaneId, const int meshPointId) inline
Checks if the point meshPointId of the mesh associated with the provided meshPaneId exists in this MeshPointIdToGlobalIdMap instance.
Parameters
meshPaneId the pane id of the mesh in query.
meshPointId the local point id of the point in query.
Returns
Status true iff exists else false.
Definition at line 44 of file MeshPointIdToGlobalIdMap.hpp.
References MeshPointIdToGlobalIdMap::local2global.
Referenced by MeshPointIdToGlobalIdMap::insert().
{
                                 std::pair< int, int > keyPair = std::make_pair( meshPaneId, meshPointId );
                                 if( this ->local2global.find( keyPair ) != this ->local2global.end( ) )
                                         return true;
                                 else
                                         return false;
                         }
int getGlobalId (const int meshPaneId, const int meshPointId) inline
Returns the assigned global id to meshPointId of the mesh associated with the provided meshPaneId.
Parameters
meshPaneId the pane id of the mesh in query.
meshPointId the point id of the mesh point in query.
Returns
ID the global id assigned to the point.
Postcondition
ID >= 0 or -1 iff ! this ->exists(meshPaneId, meshPoint).
Definition at line 61 of file MeshPointIdToGlobalIdMap.hpp.
References MeshPointIdToGlobalIdMap::local2global.
Referenced by stitchSolutionData().
{
                                 std::pair< int, int > keyPair = std::make_pair( meshPaneId, meshPointId );
                                 if( this ->local2global.find( keyPair ) != this ->local2global.end( ) )
                                         return( this ->local2global[ keyPair ] );
                                 else
                                         return(-1);
                         }
void insert (const int meshPaneId, const int meshPointId, const int globalId) inline
This method constructs a new key-pair for the meshPaneId and meshPointId which maps into globalId and inserts it into the data-structure.
Parameters
meshPaneId the pane id of the mesh in query.
meshPointId the point id of the mesh point in query.
globalId the global id assigned to the point.
Precondition
globalId >= 0 && meshPointId >= 0.
this ->exists(meshPaneId, meshPointId) == false.
Postcondition
this ->exists(meshPaneId, meshPointId) == true.
Definition at line 80 of file MeshPointIdToGlobalIdMap.hpp.
References MeshPointIdToGlobalIdMap::exists().
Referenced by stitchGrids(), and updateHash().
{
 //                              std::cout << "Mesh Pane Id: " << meshPaneId << " ";
 //                              std::cout << "Mesh Point Id: " << meshPointId << " ";
 //                              std::cout << std::endl;
 //                              std::cout.flush( );
                                 #ifdef ASSERT_ON
                                         assert( globalId >= 0 );
                                         assert( meshPointId >= 0);
                                         assert( !this ->exists( meshPaneId, meshPointId ) );
                                 #endif
                                 std::pair< int, int > keyPair  = std::make_pair( meshPaneId, meshPointId );
                                 this ->local2global[ keyPair ] = globalId;
                                 #ifdef ASSERT_ON
                                         assert( this ->exists( meshPaneId, meshPointId ) );
                                 #endif
                         }
int size () const inline
Returns the size of the map.
Returns
N the number of elements in the map.
Postcondition
N >= 0.
Definition at line 108 of file MeshPointIdToGlobalIdMap.hpp.
 { return this ->local2global.size( ); }
Member Data Documentation
std::map< std::pair< int, int >, int > local2global private
Definition at line 22 of file MeshPointIdToGlobalIdMap.hpp.
Referenced by MeshPointIdToGlobalIdMap::exists(), and MeshPointIdToGlobalIdMap::getGlobalId().
The documentation for this class was generated from the following file:
MeshPointIdToGlobalIdMap.hpp