Rocstar: rflu_modtecplot Module Reference
rflu_modtecplot Module Reference
Public Member Functions
subroutine, public rflu_tec_builddatafieldsurf (pRegion, pPatch)
subroutine, public rflu_tec_builddatafieldvol (pRegion)
subroutine, public rflu_tec_builddatapatch (pRegion, pPatch)
subroutine, public rflu_tec_builddatapatchstats (pRegion, pPatch)
subroutine, public rflu_tec_closefilefield (global)
subroutine, public rflu_tec_closefilepatch (global)
subroutine, public rflu_tec_closefilepatchstats (global)
subroutine, public rflu_tec_closefilepnt (global)
subroutine, public rflu_tec_destroydatafieldsurf (pRegion, pPatch)
subroutine, public rflu_tec_destroydatafieldvol (pRegion)
subroutine, public rflu_tec_destroydatapatch (pRegion, pPatch)
subroutine, public rflu_tec_init (global)
subroutine, public rflu_tec_openfilefield (pRegion)
subroutine, public rflu_tec_openfilepatch (pRegion)
subroutine, public rflu_tec_openfilepatchstats (pRegion)
subroutine, public rflu_tec_openfilepnt (pRegion)
subroutine, public rflu_tec_writefilefieldsurf (pRegion, pPatch)
subroutine, public rflu_tec_writefilefieldvol (pRegion)
subroutine, public rflu_tec_writefilepatch (pRegion, pPatch)
subroutine, public rflu_tec_writefilepnt (pRegion)
Private Member Functions
subroutine, private rflu_tec_buildheaderfield (pRegion)
subroutine, private rflu_tec_buildheaderpatch (pRegion)
subroutine, private rflu_tec_buildheaderpatchstats (pRegion)
Private Attributes
character(chrlen), parameter,
private rcsidentstring = '$RCSfile: RFLU_ModTECPLOT.F90,v $ $Revision: 1.38 $'
Detailed Description
Definition at line 47 of file RFLU_ModTECPLOT.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_tec_builddatafieldsurf (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 136 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_builddatafieldvol (type(t_region), pointer pRegion)
Definition at line 668 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_builddatapatch (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 1164 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_builddatapatchstats (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 1405 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, private rflu_tec_buildheaderfield (type(t_region), pointer pRegion) private
Definition at line 1668 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_tec_openfilefield().
subroutine, private rflu_tec_buildheaderpatch (type(t_region), pointer pRegion) private
Definition at line 1804 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_tec_openfilepatch().
subroutine, private rflu_tec_buildheaderpatchstats (type(t_region), pointer pRegion) private
Definition at line 1893 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_tec_openfilepatchstats().
subroutine, public rflu_tec_closefilefield (type(t_global), pointer global)
Definition at line 1999 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modtecplotutils::rflu_tec_closefile().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_closefilepatch (type(t_global), pointer global)
Definition at line 2088 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modtecplotutils::rflu_tec_closefile().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_closefilepatchstats (type(t_global), pointer global)
Definition at line 2176 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modtecplotutils::rflu_tec_closefile().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_closefilepnt (type(t_global), pointer global)
Definition at line 2267 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_destroydatafieldsurf (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 2342 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_destroydatafieldvol (type(t_region), pointer pRegion)
Definition at line 2436 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_destroydatapatch (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 2530 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_init (type(t_global), pointer global)
Definition at line 2625 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_openfilefield (type(t_region), pointer pRegion)
Definition at line 2694 of file RFLU_ModTECPLOT.F90.
References modbuildfilenames::buildfilenameplainsteady(), modbuildfilenames::buildfilenameplainunsteady(), moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_tec_buildheaderfield(), and rflu_modtecplotutils::rflu_tec_openfile().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_openfilepatch (type(t_region), pointer pRegion)
Definition at line 2811 of file RFLU_ModTECPLOT.F90.
References modbuildfilenames::buildfilenameplainsteady(), modbuildfilenames::buildfilenameplainunsteady(), moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_tec_buildheaderpatch(), and rflu_modtecplotutils::rflu_tec_openfile().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_openfilepatchstats (type(t_region), pointer pRegion)
Definition at line 2930 of file RFLU_ModTECPLOT.F90.
References modbuildfilenames::buildfilenameplainsteady(), modbuildfilenames::buildfilenameplainunsteady(), moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_tec_buildheaderpatchstats(), and rflu_modtecplotutils::rflu_tec_openfile().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_openfilepnt (type(t_region), pointer pRegion)
Definition at line 3049 of file RFLU_ModTECPLOT.F90.
References modbuildfilenames::buildfilenameplainunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_writefilefieldsurf (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 3154 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modtecplotutils::rflu_tec_writezonesurf().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_writefilefieldvol (type(t_region), pointer pRegion)
Definition at line 3269 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_modtecplotutils::rflu_tec_writezonecellsspecial(), rflu_modtecplotutils::rflu_tec_writezonefacesspecial(), rflu_modtecplotutils::rflu_tec_writezoneinterf(), and rflu_modtecplotutils::rflu_tec_writezonevol().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_writefilepatch (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 3463 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modtecplotutils::rflu_tec_writezonesurfmixed().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
subroutine, public rflu_tec_writefilepnt (type(t_region), pointer pRegion)
Definition at line 3545 of file RFLU_ModTECPLOT.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions().
Member Data Documentation
character(chrlen), parameter, private rcsidentstring = '$RCSfile: RFLU_ModTECPLOT.F90,v $ $Revision: 1.38 $' private
Definition at line 73 of file RFLU_ModTECPLOT.F90.
The documentation for this module was generated from the following file:
RFLU_ModTECPLOT.F90