Rocstar: MeshImplData Class Reference
MeshImplData Class Reference
Class to store mesh representation for MeshImpl.
#include <MeshImplData.hpp>
Classes
struct Element
Struct holding an element.
struct Vertex
Struct holding a vertex.
Public Member Functions
void clear ()
Clear all data.
size_t num_vertices () const
Get number of vertices, does not include mid-nodes.
size_t num_elements () const
Get number of elements.
size_t num_vertex_uses () const
Get number of vertex uses (sum of connectivity length for all elements) Does not count mid-nodes.
size_t max_vertex_index () const
size_t max_element_index () const
void copy_mesh (size_t *vertex_handle_array, size_t *element_hanlde_array, size_t *element_conn_offsets, size_t *element_conn_indices)
Copy internal representation into CSR rep Does not include mid-nodes.
void all_vertices (msq_std::vector< size_t > &list, MsqError &err) const
Get all vertices, including mid-nodes.
void all_elements (msq_std::vector< size_t > &list, MsqError &err) const
Get all elements.
bool is_vertex_valid (size_t index) const
Check if passed vertex index is valid.
bool is_element_valid (size_t index) const
Check if passed element index is valid.
bool is_mid_node (size_t index) const
Check if the specified node is used as a mid-node on any element.
bool is_corner_node (size_t index) const
Check if the specified node is used as a corner vertex on any element.
const Vector3D & get_vertex_coords (size_t index, MsqError &err) const
Get vertex coordinates.
void set_vertex_coords (size_t index, const Vector3D &coords, MsqError &err)
Set vertex coordinates.
bool vertex_is_fixed (size_t index, MsqError &err) const
Get vertex fixed flag.
void fix_vertex (size_t index, bool flag, MsqError &err)
Set vertex fixed flag.
unsigned char get_vertex_byte (size_t index, MsqError &err) const
Get vertex byte.
void set_vertex_byte (size_t index, unsigned char value, MsqError &err)
Set vertex byte.
EntityTopology element_topology (size_t index, MsqError &err) const
Get element type.
void element_topology (size_t index, EntityTopology type, MsqError &err)
Set element type.
const msq_std::vector< size_t > & element_connectivity (size_t index, MsqError &err) const
Get element connectivity list, including mid-nodes.
const msq_std::vector< size_t > & vertex_adjacencies (size_t index, MsqError &err) const
Get vertex adjacency list.
void allocate_vertices (size_t count, MsqError &err)
Allocate space for specified number of vertices.
void allocate_elements (size_t count, MsqError &err)
Allocate space for specified number of elements.
void reset_vertex (size_t index, const Vector3D &coords, bool fixed, MsqError &err)
Set allocated but unset veretx to specified values.
void reset_element (size_t index, const msq_std::vector< size_t > &vertices, EntityTopology topology, MsqError &err)
Clear element at specified index (if any) including connectivity and adjacency data, and re-initialize with passed data.
size_t add_vertex (const Vector3D &coords, bool fixed, MsqError &err)
Add a new vertex.
size_t add_element (const msq_std::vector< size_t > &vertices, EntityTopology topology, MsqError &err)
Add a new element.
void delete_vertex (size_t index, MsqError &err)
Delete a vertex - may not be referenced by any element.
void delete_element (size_t index, MsqError &err)
Delete an element.
void copy_higher_order (msq_std::vector< size_t > &mid_nodes, msq_std::vector< size_t > &vertices, msq_std::vector< size_t > &vertex_indices, msq_std::vector< size_t > &index_offsets, MsqError &err)
Get all mid-nodes and their adjacent corner vertices.
void get_adjacent_elements (msq_std::vector< size_t >::const_iterator nodes, msq_std::vector< size_t >::const_iterator nodes_end, msq_std::vector< size_t > &elems_out, MsqError &err)
Get elements adjacent to ALL of the passed nodes.
void skin (msq_std::vector< size_t > &sides, MsqError &err)
Skin mesh.
void clear ()
Clear all data.
size_t num_vertices () const
Get number of vertices, does not include mid-nodes.
size_t num_elements () const
Get number of elements.
size_t num_vertex_uses () const
Get number of vertex uses (sum of connectivity length for all elements) Does not count mid-nodes.
size_t max_vertex_index () const
size_t max_element_index () const
void copy_mesh (size_t *vertex_handle_array, size_t *element_hanlde_array, size_t *element_conn_offsets, size_t *element_conn_indices)
Copy internal representation into CSR rep Does not include mid-nodes.
void all_vertices (msq_std::vector< size_t > &list, MsqError &err) const
Get all vertices, including mid-nodes.
void all_elements (msq_std::vector< size_t > &list, MsqError &err) const
Get all elements.
bool is_vertex_valid (size_t index) const
Check if passed vertex index is valid.
bool is_element_valid (size_t index) const
Check if passed element index is valid.
bool is_mid_node (size_t index) const
Check if the specified node is used as a mid-node on any element.
bool is_corner_node (size_t index) const
Check if the specified node is used as a corner vertex on any element.
const Vector3D & get_vertex_coords (size_t index, MsqError &err) const
Get vertex coordinates.
void set_vertex_coords (size_t index, const Vector3D &coords, MsqError &err)
Set vertex coordinates.
bool vertex_is_fixed (size_t index, MsqError &err) const
Get vertex fixed flag.
void fix_vertex (size_t index, bool flag, MsqError &err)
Set vertex fixed flag.
unsigned char get_vertex_byte (size_t index, MsqError &err) const
Get vertex byte.
void set_vertex_byte (size_t index, unsigned char value, MsqError &err)
Set vertex byte.
EntityTopology element_topology (size_t index, MsqError &err) const
Get element type.
void element_topology (size_t index, EntityTopology type, MsqError &err)
Set element type.
const msq_std::vector< size_t > & element_connectivity (size_t index, MsqError &err) const
Get element connectivity list, including mid-nodes.
const msq_std::vector< size_t > & vertex_adjacencies (size_t index, MsqError &err) const
Get vertex adjacency list.
void allocate_vertices (size_t count, MsqError &err)
Allocate space for specified number of vertices.
void allocate_elements (size_t count, MsqError &err)
Allocate space for specified number of elements.
void reset_vertex (size_t index, const Vector3D &coords, bool fixed, MsqError &err)
Set allocated but unset veretx to specified values.
void reset_element (size_t index, const msq_std::vector< size_t > &vertices, EntityTopology topology, MsqError &err)
Clear element at specified index (if any) including connectivity and adjacency data, and re-initialize with passed data.
size_t add_vertex (const Vector3D &coords, bool fixed, MsqError &err)
Add a new vertex.
size_t add_element (const msq_std::vector< size_t > &vertices, EntityTopology topology, MsqError &err)
Add a new element.
void delete_vertex (size_t index, MsqError &err)
Delete a vertex - may not be referenced by any element.
void delete_element (size_t index, MsqError &err)
Delete an element.
void copy_higher_order (msq_std::vector< size_t > &mid_nodes, msq_std::vector< size_t > &vertices, msq_std::vector< size_t > &vertex_indices, msq_std::vector< size_t > &index_offsets, MsqError &err)
Get all mid-nodes and their adjacent corner vertices.
void get_adjacent_elements (msq_std::vector< size_t >::const_iterator nodes, msq_std::vector< size_t >::const_iterator nodes_end, msq_std::vector< size_t > &elems_out, MsqError &err)
Get elements adjacent to ALL of the passed nodes.
void skin (msq_std::vector< size_t > &sides, MsqError &err)
Skin mesh.
Private Member Functions
bool has_adjacent_elements (size_t elem, const msq_std::vector< size_t > &nodes, MsqError &err)
helper function for skinning
void clear_element (size_t index, MsqError &err)
Clear existing element data.
void set_element (size_t index, const msq_std::vector< size_t > &vertices, EntityTopology topology, MsqError &err)
Set cleared element.
bool has_adjacent_elements (size_t elem, const msq_std::vector< size_t > &nodes, MsqError &err)
helper function for skinning
void clear_element (size_t index, MsqError &err)
Clear existing element data.
void set_element (size_t index, const msq_std::vector< size_t > &vertices, EntityTopology topology, MsqError &err)
Set cleared element.
Private Attributes
msq_std::vector< Vertex > vertexList
Array of vertices.
msq_std::vector< Element > elementList
Array of elements.
msq_std::vector< size_t > deletedVertexList
List of unused indices in vertex list.
msq_std::vector< size_t > deletedElementList
List of unused indices in element list.
Detailed Description
Class to store mesh representation for MeshImpl.
Definition at line 47 of file includeLinks/MeshImplData.hpp.
Member Function Documentation
size_t add_element (const msq_std::vector< size_t > & vertices, EntityTopology topology, MsqError & err)
Add a new element.
Definition at line 352 of file Mesh/MeshImplData.cpp.
References MeshImplData::deletedElementList, MeshImplData::elementList, MSQ_ERRZERO, and MeshImplData::set_element().
 {
   size_t index;
   if (!deletedElementList.empty())
   {
     index = deletedElementList[deletedElementList.size()-1];
     deletedElementList.pop_back();
   }
   else
   {
     index = elementList.size();
     elementList.resize( elementList.size() + 1 );
   }
   set_element( index, vertices, topology, err ); MSQ_ERRZERO(err);
   return index;
 }
size_t add_element (const msq_std::vector< size_t > & vertices, EntityTopology topology, MsqError & err)
Add a new element.
size_t add_vertex (const Vector3D & coords, bool fixed, MsqError & err)
Add a new vertex.
size_t add_vertex (const Vector3D & coords, bool fixed, MsqError & err)
Add a new vertex.
Definition at line 333 of file Mesh/MeshImplData.cpp.
References MeshImplData::deletedVertexList, MSQ_ERRZERO, MeshImplData::reset_vertex(), and MeshImplData::vertexList.
 {
   size_t index;
   if (!deletedVertexList.empty())
   {
     index = deletedVertexList[deletedVertexList.size()-1];
     deletedVertexList.pop_back();
     reset_vertex( index, coords, fixed, err ); MSQ_ERRZERO(err);
   }
   else
   {
     index = vertexList.size();
     vertexList.push_back( Vertex(coords, fixed ) );
   }
   return index;
 }
void all_elements (msq_std::vector< size_t > & list, MsqError & err) const
Get all elements.
void all_elements (msq_std::vector< size_t > & list, MsqError & err) const
Get all elements.
Definition at line 552 of file Mesh/MeshImplData.cpp.
References MeshImplData::elementList.
Referenced by MeshImpl::vtk_read_cell_data().
 {
   list.clear();
   for (size_t idx = 0; idx < elementList.size(); ++idx)
     if (!elementList[idx].connectivity.empty())
       list.push_back( idx );
 }
void all_vertices (msq_std::vector< size_t > & list, MsqError & err) const
Get all vertices, including mid-nodes.
Definition at line 544 of file Mesh/MeshImplData.cpp.
References MeshImplData::vertexList.
Referenced by MeshImpl::vtk_read_point_data().
 {
   list.clear();
   for (size_t idx = 0; idx < vertexList.size(); ++idx)
     if (vertexList[idx].valid)
       list.push_back( idx );
 }
void all_vertices (msq_std::vector< size_t > & list, MsqError & err) const
Get all vertices, including mid-nodes.
void allocate_elements (size_t count, MsqError & err)
Allocate space for specified number of elements.
Definition at line 205 of file Mesh/MeshImplData.cpp.
References MeshImplData::elementList, MsqError::INVALID_STATE, and MSQ_SETERR.
Referenced by MeshImpl::read_exodus(), MeshImpl::vtk_create_structured_elems(), MeshImpl::vtk_read_polygons(), and MeshImpl::vtk_read_unstructured_grid().
 {
   if (elementList.size())
   {
     MSQ_SETERR(err)(MsqError::INVALID_STATE);
     return;
   }
   elementList.resize( count );
 }
void allocate_elements (size_t count, MsqError & err)
Allocate space for specified number of elements.
void allocate_vertices (size_t count, MsqError & err)
Allocate space for specified number of vertices.
Definition at line 194 of file Mesh/MeshImplData.cpp.
References MsqError::INVALID_STATE, MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImpl::read_exodus(), MeshImpl::vtk_read_polydata(), MeshImpl::vtk_read_rectilinear_grid(), MeshImpl::vtk_read_structured_grid(), MeshImpl::vtk_read_structured_points(), and MeshImpl::vtk_read_unstructured_grid().
 {
   if (vertexList.size())
   {
     MSQ_SETERR(err)(MsqError::INVALID_STATE);
     return;
   }
   vertexList.resize(count);
 }
void allocate_vertices (size_t count, MsqError & err)
Allocate space for specified number of vertices.
void clear ()
Clear all data.
Definition at line 186 of file Mesh/MeshImplData.cpp.
References MeshImplData::deletedElementList, MeshImplData::deletedVertexList, MeshImplData::elementList, and MeshImplData::vertexList.
Referenced by MeshImpl::clear().
 {
   vertexList.clear();
   elementList.clear();
   deletedVertexList.clear();
   deletedElementList.clear();
 }
void clear ()
Clear all data.
void clear_element (size_t index, MsqError & err) private
Clear existing element data.
void clear_element (size_t index, MsqError & err) private
Clear existing element data.
Definition at line 263 of file Mesh/MeshImplData.cpp.
References TopologyInfo::corners(), MeshImplData::elementList, i, MsqError::INVALID_ARG, MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImplData::delete_element(), and MeshImplData::reset_element().
 {
   if (index >= elementList.size())
   {
     MSQ_SETERR(err)("Invalid element handle", MsqError::INVALID_ARG);
     return;
   }
   unsigned numvert = TopologyInfo::corners( elementList[index].topology );
   if (numvert)
     for (unsigned i = numvert; i < elementList[index].connectivity.size(); ++i)
       --vertexList[elementList[index].connectivity[i]].midcount;
   msq_std::vector<size_t>& conn = elementList[index].connectivity;
   for (msq_std::vector<size_t>::iterator iter = conn.begin();
        iter != conn.end(); ++iter)
   {
     msq_std::vector<size_t>& adj = vertexList[*iter].adjacencies;
     for (msq_std::vector<size_t>::iterator iter2 = adj.begin();
          iter2 != adj.end(); ++iter2)
     {
       if (*iter2 == index)
       {
         adj.erase(iter2);
         break;
       }
     }
   }
   conn.clear();
 }
void copy_higher_order (msq_std::vector< size_t > & mid_nodes, msq_std::vector< size_t > & vertices, msq_std::vector< size_t > & vertex_indices, msq_std::vector< size_t > & index_offsets, MsqError & err)
Get all mid-nodes and their adjacent corner vertices.
Definition at line 447 of file Mesh/MeshImplData.cpp.
References MeshImplData::Vertex::adjacencies, MeshImplData::Element::connectivity, MeshImplData::elementList, i, MsqError::INTERNAL_ERROR, MsqError::INVALID_STATE, MeshImplData::is_vertex_valid(), MeshImplData::Vertex::midcount, MSQ_ERRRTN, MSQ_SETERR, TopologyInfo::side_number(), TopologyInfo::side_vertices(), MeshImplData::Element::topology, v, MeshImplData::Vertex::valid, and MeshImplData::vertexList.
 {
   mid_nodes.clear();
   vertices.clear();
   vertex_indices.clear();
   index_offsets.clear();
     // Create a map of from vertex handle to index in "vertices"
     // Use vertexList.size() to mean uninitialized.
   size_t v;
   msq_std::vector<size_t> vert_map( vertexList.size() );
   for (v = 0; v < vertexList.size(); ++v)
     vert_map[v] = vertexList.size();
     // Loop over all mid-side vertices
   for (v = 0; v < vertexList.size(); ++v)
   {
     const Vertex& vert = vertexList[v];
       // Not a mid-side vertex, skip it
     if (!vert.valid || !vert.midcount)
       continue;
       // Populate "verts" with the handles of all adjacent corner vertices
     assert( vert.adjacencies.size() ); // shouldn't be able to fail if vert.midcount > 0
     int elem_indx = vert.adjacencies[0];
     Element& elem = elementList[elem_indx];
       // Find index of node in elem's connectivity list
     unsigned index;
     for (index = 0; index < elem.connectivity.size(); ++index)
       if (elem.connectivity[index] == v)
         break;
     if (index == elem.connectivity.size())
     {
       MSQ_SETERR(err)("Inconsistent data.", MsqError::INTERNAL_ERROR);
       return;
     }
       // Given the index in the element's connectivity list,
       // get the side of the element containing the mid-node.
     unsigned side_dim, side_num;
     TopologyInfo::side_number( elem.topology, elem.connectivity.size(),
                           index, side_dim, side_num, err ); MSQ_ERRRTN(err);
     if (!side_dim) // Not a mid-side node
     {
       MSQ_SETERR(err)(MsqError::INVALID_STATE,"Improperly connected mesh.");
       return;
     }
       // Get the adjacent corner vertices from the element side.
     unsigned num_corners;
     const unsigned* corner_indices = TopologyInfo::side_vertices(
       elem.topology, side_dim, side_num, num_corners, err ); MSQ_ERRRTN(err);
       // Add the mid-side node to the output list
     mid_nodes.push_back( v );
       // Store offset at which the indices of the corner
       // vertices adjacent to this mid-side node will be
       // stored in "vertex_indices".
     index_offsets.push_back( vertex_indices.size() );
       // For each adjacent corner vertex, if the vertex is not
       // already in "vertices" add it, and add the index to
       // the adjacency list for this mid-side node.
     for (unsigned i = 0; i < num_corners; ++i)
     {
       size_t vert_idx = elem.connectivity[corner_indices[i]];
       assert( is_vertex_valid(vert_idx) );
       if (vert_map[vert_idx] == vertexList.size())
       {
         vert_map[vert_idx] = vertices.size();
         vertices.push_back( vert_idx );
       }
       vertex_indices.push_back( vert_map[vert_idx] );
     }
   }
   index_offsets.push_back( vertex_indices.size() );
 }
void copy_higher_order (msq_std::vector< size_t > & mid_nodes, msq_std::vector< size_t > & vertices, msq_std::vector< size_t > & vertex_indices, msq_std::vector< size_t > & index_offsets, MsqError & err)
Get all mid-nodes and their adjacent corner vertices.
void copy_mesh (size_t * vertex_handle_array, size_t * element_hanlde_array, size_t * element_conn_offsets, size_t * element_conn_indices)
Copy internal representation into CSR rep Does not include mid-nodes.
void copy_mesh (size_t * vertex_handle_array, size_t * element_hanlde_array, size_t * element_conn_offsets, size_t * element_conn_indices)
Copy internal representation into CSR rep Does not include mid-nodes.
Definition at line 390 of file Mesh/MeshImplData.cpp.
References MeshImplData::Element::connectivity, TopologyInfo::corners(), MeshImplData::elementList, offset(), MeshImplData::Element::topology, v, and MeshImplData::vertexList.
Referenced by MeshImpl::get_all_mesh().
 {
   msq_std::vector<size_t> vertex_map( vertexList.size() );
   size_t vh_index = 0;
   for (size_t v = 0; v < vertexList.size(); ++v)
   {
     if (vertexList[v].valid
 #ifdef SEPARATE_MID_NODES
         && vertexList[v].midcount < vertexList[v].adjacencies.size()
 #endif
        )
     {
       vertex_handle_array[vh_index] = v;
       vertex_map[v] = vh_index;
       ++vh_index;
     }
     else
     {
       vertex_map[v] = vertexList.size();
     }
   }
   size_t offset = 0;
   for (size_t e = 0; e < elementList.size(); ++e)
   {
     Element& elem = elementList[e];
     size_t cl;
 #ifdef SEPARATE_MID_NODES
     cl = TopologyInfo::corners( elem.topology );
     if (!cl)
 #endif
       cl = elem.connectivity.size();
     if (cl)
     {
       *element_handle_array = e;
       ++element_handle_array;
       *element_conn_offsets = offset;
       ++element_conn_offsets;
       offset += cl;
       msq_std::vector<size_t>::iterator conn = elem.connectivity.begin();
       msq_std::vector<size_t>::iterator end = conn + cl;
       while (conn != end)
       {
         *element_conn_indices = vertex_map[*conn];
         ++element_conn_indices;
         ++conn;
       }
     }
   }
   *element_conn_offsets = offset;
 }
void delete_element (size_t index, MsqError & err)
Delete an element.
void delete_element (size_t index, MsqError & err)
Delete an element.
Definition at line 384 of file Mesh/MeshImplData.cpp.
References MeshImplData::clear_element(), MeshImplData::deletedElementList, and MSQ_ERRRTN.
 {
   clear_element( index, err ); MSQ_ERRRTN(err);
   deletedElementList.push_back( index );
 }
void delete_vertex (size_t index, MsqError & err)
Delete a vertex - may not be referenced by any element.
void delete_vertex (size_t index, MsqError & err)
Delete a vertex - may not be referenced by any element.
Definition at line 372 of file Mesh/MeshImplData.cpp.
References MeshImplData::deletedVertexList, MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
 {
   if (!is_vertex_valid( index ))
   {
     MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
     return;
   }
   vertexList[index].valid = false;
   deletedVertexList.push_back( index );
 }
const msq_std::vector< size_t > & element_connectivity (size_t index, MsqError & err) const
Get element connectivity list, including mid-nodes.
Definition at line 164 of file Mesh/MeshImplData.cpp.
References Mesquite::dummy_list, MeshImplData::elementList, MsqError::INVALID_ARG, MeshImplData::is_element_valid(), and MSQ_SETERR.
Referenced by MeshImpl::element_get_attached_vertex_count(), MeshImpl::element_get_connectivity(), MeshImpl::elements_get_attached_vertices(), MeshImpl::get_vertex_use_count(), and MeshImpl::vtk_read_unstructured_grid().
 {
   if (!is_element_valid( index ))
   {
     MSQ_SETERR(err)("Invalid element handle", MsqError::INVALID_ARG);
     return dummy_list;
   }
   return elementList[index].connectivity;
 }
const msq_std::vector<size_t>& element_connectivity (size_t index, MsqError & err) const
Get element connectivity list, including mid-nodes.
EntityTopology element_topology (size_t index, MsqError & err) const
Get element type.
Definition at line 129 of file Mesh/MeshImplData.cpp.
References MeshImplData::elementList, MsqError::INVALID_ARG, MeshImplData::is_element_valid(), Mesquite::MIXED, and MSQ_SETERR.
Referenced by MeshImpl::vtk_read_unstructured_grid().
 {
   if (!is_element_valid( index ))
   {
     MSQ_SETERR(err)("Invalid element handle", MsqError::INVALID_ARG);
     return MIXED;
   }
   return elementList[index].topology;
 }
EntityTopology element_topology (size_t index, MsqError & err) const
Get element type.
void element_topology (size_t index, EntityTopology type, MsqError & err)
Set element type.
Definition at line 140 of file Mesh/MeshImplData.cpp.
References TopologyInfo::corners(), MeshImplData::elementList, i, MsqError::INVALID_ARG, MeshImplData::is_element_valid(), MSQ_SETERR, and MeshImplData::vertexList.
 {
   if (!is_element_valid( index ))
   {
     MSQ_SETERR(err)("Invalid element handle", MsqError::INVALID_ARG);
     return ;
   }
   unsigned i, numvert;
   numvert = TopologyInfo::corners( elementList[index].topology );
   if (numvert)
     for (i = numvert; i < elementList[index].connectivity.size(); ++i)
       --vertexList[elementList[index].connectivity[i]].midcount;
   elementList[index].topology = type;
   numvert = TopologyInfo::corners( elementList[index].topology );
   if (numvert)
     for (i = numvert; i < elementList[index].connectivity.size(); ++i)
       ++vertexList[elementList[index].connectivity[i]].midcount;
 }
void element_topology (size_t index, EntityTopology type, MsqError & err)
Set element type.
void fix_vertex (size_t index, bool flag, MsqError & err)
Set vertex fixed flag.
Definition at line 95 of file Mesh/MeshImplData.cpp.
References MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImpl::read_exodus(), and MeshImpl::read_vtk().
 {
   if (!is_vertex_valid( index ))
   {
     MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
     return;
   }
   vertexList[index].fixed = flag;
 }
void fix_vertex (size_t index, bool flag, MsqError & err)
Set vertex fixed flag.
void get_adjacent_elements (msq_std::vector< size_t >::const_iterator nodes, msq_std::vector< size_t >::const_iterator nodes_end, msq_std::vector< size_t > & elems_out, MsqError & err)
Get elements adjacent to ALL of the passed nodes.
Return the list of elements that is the intersection of the adjacency lists of the specified vertices.
Definition at line 560 of file Mesh/MeshImplData.cpp.
References MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImplData::has_adjacent_elements().
 {
   if (node_iter == node_end || !is_vertex_valid( *node_iter ))
   {
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     return;
   }
     // Get list of elements adjacent to first node
   elems = vertexList[*node_iter].adjacencies;
     // For each aditional node, intersect elems with elements adjacent to node
   for (++node_iter; node_iter != node_end; ++node_iter)
   {
     msq_std::vector<size_t>::iterator elem_iter = elems.begin();
     while (elem_iter != elems.end())
     {
       msq_std::vector<size_t>::const_iterator adj_iter = vertexList[*node_iter].adjacencies.begin();
       const msq_std::vector<size_t>::const_iterator adj_end = vertexList[*node_iter].adjacencies.end();
       for (; adj_iter != adj_end; ++adj_iter)
         if (*elem_iter == *adj_iter)
           break;
       if (adj_iter == adj_end)
       {
         *elem_iter = elems[elems.size()-1];
         elems.pop_back();
       }
       else
       {
         ++elem_iter;
       }
     }
   }
 }
void get_adjacent_elements (msq_std::vector< size_t >::const_iterator nodes, msq_std::vector< size_t >::const_iterator nodes_end, msq_std::vector< size_t > & elems_out, MsqError & err)
Get elements adjacent to ALL of the passed nodes.
Return the list of elements that is the intersection of the adjacency lists of the specified vertices.
unsigned char get_vertex_byte (size_t index, MsqError & err) const
Get vertex byte.
Definition at line 107 of file Mesh/MeshImplData.cpp.
References MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImpl::vertices_get_byte().
 {
   if (!is_vertex_valid( index ))
   {
     MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
     return 0;
   }
   return vertexList[index].byte;
 }
unsigned char get_vertex_byte (size_t index, MsqError & err) const
Get vertex byte.
const Vector3D & get_vertex_coords (size_t index, MsqError & err) const
Get vertex coordinates.
Definition at line 73 of file Mesh/MeshImplData.cpp.
References Mesquite::dummy_vtx, MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImpl::vertices_get_coordinates(), and MeshImpl::write_vtk().
 {
   if (!is_vertex_valid( index ))
   {
     MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
     return dummy_vtx;
   }
   return vertexList[index].coords;
 }
const Vector3D& get_vertex_coords (size_t index, MsqError & err) const
Get vertex coordinates.
bool has_adjacent_elements (size_t elem, const msq_std::vector< size_t > & nodes, MsqError & err) private
helper function for skinning
Check if any elements adjacent to a side of an element are of the same dimension as the input element.
Parameters
elem The element
nodes The nodes composing the side of the element
Definition at line 599 of file Mesh/MeshImplData.cpp.
References TopologyInfo::dimension(), MeshImplData::elementList, and MeshImplData::get_adjacent_elements().
Referenced by MeshImplData::skin().
 {
   msq_std::vector<size_t> adj_elems;
   const unsigned dim = TopologyInfo::dimension( elementList[elem].topology );
   get_adjacent_elements( nodes.begin(), nodes.end(), adj_elems, err );
   msq_std::vector<size_t>::iterator iter;
   for (iter = adj_elems.begin(); iter != adj_elems.end(); ++iter)
     if (*iter != elem &&
         TopologyInfo::dimension( elementList[*iter].topology ) == dim )
       break;
   return iter != adj_elems.end();
 }
bool has_adjacent_elements (size_t elem, const msq_std::vector< size_t > & nodes, MsqError & err) private
helper function for skinning
Check if any elements adjacent to a side of an element are of the same dimension as the input element.
Parameters
elem The element
nodes The nodes composing the side of the element
bool is_corner_node (size_t index) const
Check if the specified node is used as a corner vertex on any element.
Definition at line 537 of file Mesh/MeshImplData.cpp.
References MeshImplData::is_vertex_valid(), and MeshImplData::vertexList.
Referenced by MeshImplVertIter::operator++().
 {
   return is_vertex_valid(index) && vertexList[index].midcount < vertexList[index].adjacencies.size();
 }
bool is_corner_node (size_t index) const
Check if the specified node is used as a corner vertex on any element.
bool is_element_valid (size_t index) const inline
Check if passed element index is valid.
Definition at line 83 of file includeLinks/MeshImplData.hpp.
References MeshImplData::elementList.
Referenced by MeshImplData::element_connectivity(), MeshImplData::element_topology(), MeshImplElemIter::operator++(), MeshImplElemIter::restart(), MeshImplData::skin(), and MeshImpl::write_vtk().
       { return index < elementList.size() &&
                !elementList[index].connectivity.empty(); }
bool is_element_valid (size_t index) const inline
Check if passed element index is valid.
Definition at line 83 of file src/Mesh/MeshImplData.hpp.
References MeshImplData::elementList.
       { return index < elementList.size() &&
                !elementList[index].connectivity.empty(); }
bool is_mid_node (size_t index) const
Check if the specified node is used as a mid-node on any element.
bool is_mid_node (size_t index) const
Check if the specified node is used as a mid-node on any element.
Definition at line 532 of file Mesh/MeshImplData.cpp.
References MeshImplData::is_vertex_valid(), and MeshImplData::vertexList.
 {
   return is_vertex_valid(index) && vertexList[index].midcount > 0;
 }
bool is_vertex_valid (size_t index) const inline
Check if passed vertex index is valid.
Definition at line 79 of file src/Mesh/MeshImplData.hpp.
References MeshImplData::vertexList.
     {return index < vertexList.size() && vertexList[index].valid; }
bool is_vertex_valid (size_t index) const inline
Check if passed vertex index is valid.
Definition at line 79 of file includeLinks/MeshImplData.hpp.
References MeshImplData::vertexList.
Referenced by MeshImplData::copy_higher_order(), MeshImplData::delete_vertex(), MeshImplData::fix_vertex(), MeshImplData::get_adjacent_elements(), MeshImplData::get_vertex_byte(), MeshImplData::get_vertex_coords(), MeshImplData::is_corner_node(), MeshImplData::is_mid_node(), MeshImplVertIter::operator++(), MeshImplVertIter::restart(), MeshImplData::set_element(), MeshImplData::set_vertex_byte(), MeshImplData::set_vertex_coords(), MeshImplData::vertex_adjacencies(), MeshImplData::vertex_is_fixed(), and MeshImpl::write_vtk().
     {return index < vertexList.size() && vertexList[index].valid; }
size_t max_element_index () const inline
Definition at line 63 of file includeLinks/MeshImplData.hpp.
References MeshImplData::elementList.
Referenced by MeshImplElemIter::is_at_end(), and MeshImpl::write_vtk().
 { return elementList.size(); }
size_t max_element_index () const inline
Definition at line 63 of file src/Mesh/MeshImplData.hpp.
References MeshImplData::elementList.
 { return elementList.size(); }
size_t max_vertex_index () const inline
Definition at line 62 of file src/Mesh/MeshImplData.hpp.
References MeshImplData::vertexList.
 { return vertexList.size(); }
size_t max_vertex_index () const inline
Definition at line 62 of file includeLinks/MeshImplData.hpp.
References MeshImplData::vertexList.
Referenced by MeshImplVertIter::is_at_end(), MeshImpl::read_vtk(), and MeshImpl::write_vtk().
 { return vertexList.size(); }
size_t num_elements () const
Get number of elements.
size_t num_elements () const
Get number of elements.
Definition at line 54 of file Mesh/MeshImplData.cpp.
References MeshImplData::deletedElementList, and MeshImplData::elementList.
Referenced by MeshImpl::get_all_sizes(), MeshImpl::read_vtk(), MeshImpl::vtk_read_cell_data(), and MeshImpl::write_vtk().
   { return elementList.size() - deletedElementList.size(); }
size_t num_vertex_uses () const
Get number of vertex uses (sum of connectivity length for all elements) Does not count mid-nodes.
size_t num_vertex_uses () const
Get number of vertex uses (sum of connectivity length for all elements) Does not count mid-nodes.
Definition at line 57 of file Mesh/MeshImplData.cpp.
References TopologyInfo::corners(), and MeshImplData::elementList.
Referenced by MeshImpl::get_all_sizes(), and MeshImpl::write_vtk().
 {
   size_t result = 0;
   for (msq_std::vector<Element>::const_iterator iter = elementList.begin();
        iter != elementList.end(); ++iter)
   {
 #ifdef SEPARATE_MID_NODES
     unsigned from_topo = TopologyInfo::corners( iter->topology );
     result += from_topo ? from_topo : iter->connectivity.size();
 #else
     result += iter->connectivity.size();
 #endif
   }
   return result;
 }
size_t num_vertices () const
Get number of vertices, does not include mid-nodes.
size_t num_vertices () const
Get number of vertices, does not include mid-nodes.
Definition at line 40 of file Mesh/MeshImplData.cpp.
References MeshImplData::vertexList.
Referenced by MeshImpl::get_all_sizes(), MeshImpl::read_vtk(), MeshImpl::vtk_read_point_data(), and MeshImpl::write_vtk().
 {
   size_t count = 0;
   for (msq_std::vector<Vertex>::const_iterator iter = vertexList.begin();
        iter != vertexList.end(); ++iter)
 #ifdef SEPARATE_MID_NODES
     if (iter->valid && iter->midcount < iter->adjacencies.size())
 #else
     if (iter->valid)
 #endif
       ++count;
   return count;
 }
void reset_element (size_t index, const msq_std::vector< size_t > & vertices, EntityTopology topology, MsqError & err)
Clear element at specified index (if any) including connectivity and adjacency data, and re-initialize with passed data.
void reset_element (size_t index, const msq_std::vector< size_t > & vertices, EntityTopology topology, MsqError & err)
Clear element at specified index (if any) including connectivity and adjacency data, and re-initialize with passed data.
Definition at line 253 of file Mesh/MeshImplData.cpp.
References MeshImplData::clear_element(), MSQ_ERRRTN, and MeshImplData::set_element().
Referenced by MeshImpl::read_exodus(), MeshImpl::vtk_create_structured_elems(), MeshImpl::vtk_read_polygons(), and MeshImpl::vtk_read_unstructured_grid().
 {
   clear_element( index, err );                   MSQ_ERRRTN(err);
   set_element( index, vertices, topology, err ); MSQ_ERRRTN(err);
 }
void reset_vertex (size_t index, const Vector3D & coords, bool fixed, MsqError & err)
Set allocated but unset veretx to specified values.
void reset_vertex (size_t index, const Vector3D & coords, bool fixed, MsqError & err)
Set allocated but unset veretx to specified values.
Definition at line 229 of file Mesh/MeshImplData.cpp.
References MeshImplData::Vertex::adjacencies, MeshImplData::Vertex::coords, MeshImplData::Vertex::fixed, MsqError::INVALID_ARG, MsqError::INVALID_STATE, MSQ_SETERR, MeshImplData::Vertex::valid, and MeshImplData::vertexList.
Referenced by MeshImplData::add_vertex(), MeshImpl::read_exodus(), MeshImpl::vtk_read_polydata(), MeshImpl::vtk_read_rectilinear_grid(), MeshImpl::vtk_read_structured_grid(), MeshImpl::vtk_read_structured_points(), and MeshImpl::vtk_read_unstructured_grid().
 {
   if (index >= vertexList.size())
   {
     MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
     return;
   }
   Vertex& vert = vertexList[index];
   if (!vert.adjacencies.empty())
   {
     MSQ_SETERR(err)("Cannot overwrite referenced vertex", MsqError::INVALID_STATE);
     return;
   }
   vert.coords = coords;
   vert.fixed = fixed;
   vert.valid = true;
 }
void set_element (size_t index, const msq_std::vector< size_t > & vertices, EntityTopology topology, MsqError & err) private
Set cleared element.
Definition at line 294 of file Mesh/MeshImplData.cpp.
References TopologyInfo::corners(), MeshImplData::elementList, i, MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImplData::add_element(), and MeshImplData::reset_element().
 {
   if (index >= elementList.size())
   {
     MSQ_SETERR(err)("Invalid element handle", MsqError::INVALID_ARG);
     return;
   }
   msq_std::vector<size_t>& conn = elementList[index].connectivity;
   conn = vertices;
   elementList[index].topology = topology;
   for (msq_std::vector<size_t>::iterator iter = conn.begin();
        iter != conn.end(); ++iter)
   {
     if (!is_vertex_valid( *iter ))
     {
       MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
       return;
     }
     msq_std::vector<size_t>& adj = vertexList[*iter].adjacencies;
     for (msq_std::vector<size_t>::iterator iter2 = adj.begin();
          iter2 != adj.end(); ++iter2)
       if (*iter2 == index)
         return;
     adj.push_back( index );
   }
   unsigned numvert = TopologyInfo::corners( elementList[index].topology );
   if (numvert)
     for (unsigned i = numvert; i < elementList[index].connectivity.size(); ++i)
       ++vertexList[elementList[index].connectivity[i]].midcount;
 }
void set_element (size_t index, const msq_std::vector< size_t > & vertices, EntityTopology topology, MsqError & err) private
Set cleared element.
void set_vertex_byte (size_t index, unsigned char value, MsqError & err)
Set vertex byte.
void set_vertex_byte (size_t index, unsigned char value, MsqError & err)
Set vertex byte.
Definition at line 118 of file Mesh/MeshImplData.cpp.
References MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImpl::vertices_set_byte().
 {
   if (!is_vertex_valid( index ))
   {
     MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
     return;
   }
   vertexList[index].byte = value;
 }
void set_vertex_coords (size_t index, const Vector3D & coords, MsqError & err)
Set vertex coordinates.
Definition at line 216 of file Mesh/MeshImplData.cpp.
References MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImpl::vertex_set_coordinates().
 {
   if (!is_vertex_valid( index ))
   {
     MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
     return;
   }
   vertexList[index].coords = coords;
 }
void set_vertex_coords (size_t index, const Vector3D & coords, MsqError & err)
Set vertex coordinates.
void skin (msq_std::vector< size_t > & sides, MsqError & err)
Skin mesh.
Get the boundary of a mesh as element sides
Parameters
sides Element sides as pairs of values : { elem_index, side_number }
void skin (msq_std::vector< size_t > & sides, MsqError & err)
Skin mesh.
Get the boundary of a mesh as element sides
Parameters
sides Element sides as pairs of values : { elem_index, side_number }
Definition at line 617 of file Mesh/MeshImplData.cpp.
References TopologyInfo::dimension(), MeshImplData::elementList, MeshImplData::has_adjacent_elements(), MeshImplData::is_element_valid(), k, MSQ_ERRRTN, Mesquite::POLYGON, Mesquite::POLYHEDRON, TopologyInfo::side_vertices(), and TopologyInfo::sides().
 {
   msq_std::vector<size_t> side_nodes;
     // For each element in mesh
   for (size_t elem = 0; elem < elementList.size(); ++elem)
   {
     if (!is_element_valid(elem))
       continue;
       // For each side of the element, check if there
       // are any adjacent elements.
     const EntityTopology topo = elementList[elem].topology;
     msq_std::vector<size_t>& conn = elementList[elem].connectivity;
     switch (topo)
     {
         // For normal elements (not poly****)
       default:
       {
         unsigned num = TopologyInfo::sides( topo );
         unsigned dim = TopologyInfo::dimension( topo ) - 1;
           // For each side
         for (unsigned side = 0; side < num; ++side)
         {
             // Get list of vertices defining the side
           unsigned count;
           const unsigned* indices = TopologyInfo::side_vertices( topo, dim, side, count, err );
           MSQ_ERRRTN(err);
           side_nodes.clear();
           for (unsigned k = 0; k < count; ++k)
             side_nodes.push_back( conn[indices[k]] );
             // If no adjacent element, add side to output list
           bool adj = has_adjacent_elements( elem, side_nodes, err );
           MSQ_ERRRTN(err);
           if ( !adj )
           {
             sides.push_back( elem );
             sides.push_back( side );
           }
         }
       }
       break;
       case POLYGON:
       {
         for (unsigned side = 0, next = 1; next < conn.size(); ++side, ++next)
         {
           side_nodes.clear();
           side_nodes.push_back( conn[side] );
           side_nodes.push_back( conn[next] );
             // If no adjacent element, add side to output list
           bool adj = has_adjacent_elements( elem, side_nodes, err );
           MSQ_ERRRTN(err);
           if ( !adj )
           {
             sides.push_back( elem );
             sides.push_back( side );
           }
         }
       }
       break;
       case POLYHEDRON:
       {
         for (unsigned side = 0; side < conn.size(); ++side)
         {
           side_nodes = elementList[conn[side]].connectivity;
             // If no adjacent element, add side to output list
           bool adj = has_adjacent_elements( elem, side_nodes, err );
           MSQ_ERRRTN(err);
           if ( !adj )
           {
             sides.push_back( elem );
             sides.push_back( side );
           }
         }
       }
       break;
     } // switch(topo)
   } // for (elementList)
 }
const msq_std::vector<size_t>& vertex_adjacencies (size_t index, MsqError & err) const
Get vertex adjacency list.
const msq_std::vector< size_t > & vertex_adjacencies (size_t index, MsqError & err) const
Get vertex adjacency list.
Definition at line 175 of file Mesh/MeshImplData.cpp.
References Mesquite::dummy_list, MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImpl::vertex_get_attached_element_count(), and MeshImpl::vertex_get_attached_elements().
 {
   if (!is_vertex_valid( index ))
   {
     MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
     return dummy_list;
   }
   return vertexList[index].adjacencies;
 }
bool vertex_is_fixed (size_t index, MsqError & err) const
Get vertex fixed flag.
Definition at line 84 of file Mesh/MeshImplData.cpp.
References MsqError::INVALID_ARG, MeshImplData::is_vertex_valid(), MSQ_SETERR, and MeshImplData::vertexList.
Referenced by MeshImpl::vertices_are_on_boundary(), and MeshImpl::write_vtk().
 {
   if (!is_vertex_valid( index ))
   {
     MSQ_SETERR(err)("Invalid vertex handle", MsqError::INVALID_ARG);
     return false;
   }
   return vertexList[index].fixed;
 }
bool vertex_is_fixed (size_t index, MsqError & err) const
Get vertex fixed flag.
Member Data Documentation
msq_std::vector< size_t > deletedElementList private
List of unused indices in element list.
Definition at line 238 of file includeLinks/MeshImplData.hpp.
Referenced by MeshImplData::add_element(), MeshImplData::clear(), MeshImplData::delete_element(), and MeshImplData::num_elements().
msq_std::vector< size_t > deletedVertexList private
List of unused indices in vertex list.
Definition at line 236 of file includeLinks/MeshImplData.hpp.
Referenced by MeshImplData::add_vertex(), MeshImplData::clear(), and MeshImplData::delete_vertex().
msq_std::vector< Element > elementList private
Array of elements.
Definition at line 233 of file includeLinks/MeshImplData.hpp.
Referenced by MeshImplData::add_element(), MeshImplData::all_elements(), MeshImplData::allocate_elements(), MeshImplData::clear(), MeshImplData::clear_element(), MeshImplData::copy_higher_order(), MeshImplData::copy_mesh(), MeshImplData::element_connectivity(), MeshImplData::element_topology(), MeshImplData::has_adjacent_elements(), MeshImplData::is_element_valid(), MeshImplData::max_element_index(), MeshImplData::num_elements(), MeshImplData::num_vertex_uses(), MeshImplData::set_element(), and MeshImplData::skin().
msq_std::vector< Vertex > vertexList private
Array of vertices.
Definition at line 232 of file includeLinks/MeshImplData.hpp.
Referenced by MeshImplData::add_vertex(), MeshImplData::all_vertices(), MeshImplData::allocate_vertices(), MeshImplData::clear(), MeshImplData::clear_element(), MeshImplData::copy_higher_order(), MeshImplData::copy_mesh(), MeshImplData::delete_vertex(), MeshImplData::element_topology(), MeshImplData::fix_vertex(), MeshImplData::get_adjacent_elements(), MeshImplData::get_vertex_byte(), MeshImplData::get_vertex_coords(), MeshImplData::is_corner_node(), MeshImplData::is_mid_node(), MeshImplData::is_vertex_valid(), MeshImplData::max_vertex_index(), MeshImplData::num_vertices(), MeshImplData::reset_vertex(), MeshImplData::set_element(), MeshImplData::set_vertex_byte(), MeshImplData::set_vertex_coords(), MeshImplData::vertex_adjacencies(), and MeshImplData::vertex_is_fixed().
The documentation for this class was generated from the following files:
includeLinks/MeshImplData.hpp
Mesh/MeshImplData.cpp