Rocstar: rflo_modelliptsmoothing Module Reference
rflo_modelliptsmoothing Module Reference
Public Member Functions
subroutine, public rflo_elliptgridsmoo (regions, resid)
subroutine, public rflo_elliptgridsmooregion (region, resid)
subroutine, public rflo_elliptgridpatch (region, patch)
subroutine, public rflo_elliptmatrixcoeffs3d (region)
subroutine, public rflo_elliptmatrixcoeffs2d (region, patch, iPatch)
subroutine, public rflo_elliptgridjac3d (region)
subroutine, public rflo_elliptgridgauss3d (region)
subroutine, public rflo_elliptgridsor3d (region)
subroutine, public rflo_elliptgridjac2d (region, patch, iPatch)
subroutine, public rflo_elliptgridgauss2d (region, patch, iPatch)
subroutine, public rflo_elliptgridsor2d (region, patch, iPatch)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModElliptSmoothing.F90,v $ $Revision: 1.15 $'
Detailed Description
Definition at line 37 of file RFLO_ModElliptSmoothing.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_elliptgridgauss2d (type(t_region) region, type(t_patch) patch, integer iPatch)
Definition at line 1398 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_elliptmatrixcoeffs2d(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and rflo_modgridcontrolmap::rflo_gridphysgrad2d().
Referenced by rflo_modmovegridelliptglo::rflo_mgelliptbnddeformation().
subroutine, public rflo_elliptgridgauss3d (type(t_region) region)
Definition at line 943 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
subroutine, public rflo_elliptgridjac2d (type(t_region) region, type(t_patch) patch, integer iPatch)
Definition at line 1227 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_elliptmatrixcoeffs2d(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and rflo_modgridcontrolmap::rflo_gridphysgrad2d().
Referenced by rflo_modmovegridelliptglo::rflo_mgelliptbnddeformation().
subroutine, public rflo_elliptgridjac3d (type(t_region) region)
Definition at line 802 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_elliptgridsmoo(), and rflo_elliptgridsmooregion().
subroutine, public rflo_elliptgridpatch (type(t_region) region, type(t_patch) patch)
Definition at line 433 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine, public rflo_elliptgridsmoo (type(t_region), dimension(:), pointer regions, real(rfreal) resid)
Definition at line 94 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), setup_py::grid(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_calccellcentroids(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_changeinteriorgrid(), rflo_clearsendrequests(), rflo_copygeometrydummy(), rflo_elliptgridjac3d(), rflo_elliptmatrixcoeffs3d(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and rflo_modgridcontrolmap::rflo_gridphysgrad3d().
Referenced by rflo_modmovegridelliptfra::rflo_movegridelliptfra(), and rflo_modmovegridelliptglo::rflo_movegridelliptglo().
subroutine, public rflo_elliptgridsmooregion (type(t_region) region, real(rfreal) resid)
Definition at line 339 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_elliptgridjac3d(), rflo_elliptmatrixcoeffs3d(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and rflo_modgridcontrolmap::rflo_gridphysgrad3d().
Referenced by rflo_modmovegridelliptfra::rflo_movegridelliptfra(), and rflo_modmovegridelliptglo::rflo_movegridelliptglo().
subroutine, public rflo_elliptgridsor2d (type(t_region) region, type(t_patch) patch, integer iPatch)
Definition at line 1569 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_elliptmatrixcoeffs2d(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and rflo_modgridcontrolmap::rflo_gridphysgrad2d().
Referenced by rflo_modmovegridelliptglo::rflo_mgelliptbnddeformation().
subroutine, public rflo_elliptgridsor3d (type(t_region) region)
Definition at line 1083 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
subroutine, public rflo_elliptmatrixcoeffs2d (type(t_region) region, type(t_patch) patch, integer iPatch)
Definition at line 687 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), dot_product(), i, j, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_elliptgridgauss2d(), rflo_elliptgridjac2d(), and rflo_elliptgridsor2d().
subroutine, public rflo_elliptmatrixcoeffs3d (type(t_region) region)
Definition at line 519 of file RFLO_ModElliptSmoothing.F90.
References moderror::deregisterfunction(), dot_product(), i, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_elliptgridsmoo(), and rflo_elliptgridsmooregion().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModElliptSmoothing.F90,v $ $Revision: 1.15 $' private
Definition at line 69 of file RFLO_ModElliptSmoothing.F90.
The documentation for this module was generated from the following file:
RFLO_ModElliptSmoothing.F90