Rocstar: Data_accessorS2< FT_ > Class Template Reference
Data_accessorS2< FT_ > Class Template Reference
#include <simple_cartesian_rep.h>
Public Types
typedef FT_ FT
typedef PointS2< FT > Point
typedef FT_ FT
typedef PointS2< FT > Point
Public Member Functions
FT get_x (Point const &p) const
FT get_y (Point const &p) const
void get (Point const &p, FT &x, FT &y) const
void set (Point &p, FT const &x, FT const &y) const
FT get_x (Point const &p) const
FT get_y (Point const &p) const
void get (Point const &p, FT &x, FT &y) const
void set (Point &p, FT const &x, FT const &y) const
Detailed Description
template<class FT_>
class Data_accessorS2< FT_ >
Definition at line 59 of file CGAL/include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
Member Typedef Documentation
typedef FT_ FT
Definition at line 62 of file CGAL/include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
typedef FT_ FT
Definition at line 84 of file include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
typedef PointS2<FT> Point
Definition at line 63 of file CGAL/include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
typedef PointS2<FT> Point
Definition at line 85 of file include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
Member Function Documentation
void get (Point const & p, FT & x, FT & y) const inline
Definition at line 69 of file CGAL/include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
References Data_accessorS2< FT_ >::get_x(), Data_accessorS2< FT_ >::get_y(), x, and y.
     {
         x = get_x( p);
         y = get_y( p);
     }
void get (Point const & p, FT & x, FT & y) const inline
Definition at line 91 of file include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
References Data_accessorS2< FT_ >::get_x(), Data_accessorS2< FT_ >::get_y(), x, and y.
     {
         x = get_x( p);
         y = get_y( p);
     }
FT get_x (Point const & p) const inline
Definition at line 65 of file CGAL/include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
References PointS2< FT >::x().
Referenced by Data_accessorS2< FT_ >::get().
 { return( p.x()); }
FT get_x (Point const & p) const inline
Definition at line 87 of file include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
References PointS2< FT >::x().
 { return( p.x()); }
FT get_y (Point const & p) const inline
Definition at line 66 of file CGAL/include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
References PointS2< FT >::y().
Referenced by Data_accessorS2< FT_ >::get().
 { return( p.y()); }
FT get_y (Point const & p) const inline
Definition at line 88 of file include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
References PointS2< FT >::y().
 { return( p.y()); }
void set (Point & p, FT const & x, FT const & y) const inline
Definition at line 76 of file CGAL/include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
     {
         p = Point( x, y);
     }
void set (Point & p, FT const & x, FT const & y) const inline
Definition at line 98 of file include/CGAL/SimpleCartesian/simple_cartesian_rep.h.
     {
         p = Point( x, y);
     }
The documentation for this class was generated from the following file:
CGAL/include/CGAL/SimpleCartesian/simple_cartesian_rep.h