Rocstar: rflu_modcentaur Module Reference
rflu_modcentaur Module Reference
Data Types
type t_gridcentaur
Public Member Functions
subroutine, public rflu_convcentaur2rocflu (pRegion)
subroutine, public rflu_readgridcentaurascii (pRegion)
subroutine, public rflu_readgridcentaurbinary (pRegion)
Private Member Functions
subroutine rflu_checkgridcentaur (pRegion)
subroutine rflu_printgridcentaurinfo (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCENTAUR.F90,v $ $Revision: 1.4 $'
type(t_gridcentaur) gridcentaur
Detailed Description
Definition at line 39 of file RFLU_ModCENTAUR.F90.
Member Function/Subroutine Documentation
subroutine rflu_checkgridcentaur (type(t_region), pointer pRegion) private
Definition at line 110 of file RFLU_ModCENTAUR.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_readgridcentaurascii(), and rflu_readgridcentaurbinary().
subroutine, public rflu_convcentaur2rocflu (type(t_region), pointer pRegion)
Definition at line 345 of file RFLU_ModCENTAUR.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_moddimensions::rflu_setmaxdimension().
Referenced by rflu_readconvgridwrapper().
subroutine rflu_printgridcentaurinfo (type(t_region), pointer pRegion) private
Definition at line 657 of file RFLU_ModCENTAUR.F90.
Referenced by rflu_readgridcentaurascii(), and rflu_readgridcentaurbinary().
subroutine, public rflu_readgridcentaurascii (type(t_region), pointer pRegion)
Definition at line 741 of file RFLU_ModCENTAUR.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, i, j, moderror::registerfunction(), rflu_checkgridcentaur(), rflu_printgridcentaurinfo(), rflu_moddimensions::rflu_setmaxdimension(), rflu_modsymmetryperiodic::rflu_sype_setsypepatchesflag(), and Attribute::status().
Referenced by rflu_readconvgridwrapper().
subroutine, public rflu_readgridcentaurbinary (type(t_region), pointer pRegion)
Definition at line 1082 of file RFLU_ModCENTAUR.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, i, j, moderror::registerfunction(), rflu_checkgridcentaur(), rflu_printgridcentaurinfo(), rflu_moddimensions::rflu_setmaxdimension(), and Attribute::status().
Referenced by rflu_readconvgridwrapper().
Member Data Documentation
type(t_gridcentaur) gridcentaur private
Definition at line 74 of file RFLU_ModCENTAUR.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCENTAUR.F90,v $ $Revision: 1.4 $' private
Definition at line 64 of file RFLU_ModCENTAUR.F90.
The documentation for this module was generated from the following file:
RFLU_ModCENTAUR.F90