Rocstar: VertexConditionNumberQualityMetric Class Reference
VertexConditionNumberQualityMetric Class Reference
Computes the condition numbers of the corner's of elements connected to the given vertex and then averages those values.
#include <VertexConditionNumberQualityMetric.hpp>
Public Member Functions
VertexConditionNumberQualityMetric ()
virtual ~VertexConditionNumberQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_vertex (PatchData &pd, MsqVertex *vert, double &fval, MsqError &err)
evaluate using mesquite objects
VertexConditionNumberQualityMetric ()
virtual ~VertexConditionNumberQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_vertex (PatchData &pd, MsqVertex *vert, double &fval, MsqError &err)
evaluate using mesquite objects
Public Member Functions inherited from ShapeQualityMetric
virtual ~ShapeQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
virtual ~ShapeQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_element (PatchData &, MsqMeshEntity *, double &, MsqError &err)
Evaluate the metric for an element.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_element (PatchData &, MsqMeshEntity *, double &, MsqError &err)
Evaluate the metric for an element.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Member Functions inherited from ShapeQualityMetric
bool condition_number_2d (Vector3D temp_vec[], size_t v_ind, PatchData &pd, double &fval, MsqError &err)
Given the 2-d jacobian matrix, compute the condition number, fval.
bool condition_number_3d (Vector3D temp_vec[], PatchData &pd, double &fval, MsqError &err)
Given the 3-d jacobian matrix, compute the condition number, fval.
bool condition_number_2d (Vector3D temp_vec[], size_t v_ind, PatchData &pd, double &fval, MsqError &err)
Given the 2-d jacobian matrix, compute the condition number, fval.
bool condition_number_3d (Vector3D temp_vec[], PatchData &pd, double &fval, MsqError &err)
Given the 3-d jacobian matrix, compute the condition number, fval.
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
Computes the condition numbers of the corner's of elements connected to the given vertex and then averages those values.
The metric does not use the sample point functionality or the compute_weighted_jacobian. It uses the isotropic ideal element. This metric does require a feasible region, and the metric needs to be minimized.
Definition at line 54 of file includeLinks/VertexConditionNumberQualityMetric.hpp.
Constructor & Destructor Documentation
VertexConditionNumberQualityMetric ()
Definition at line 49 of file QualityMetric/Shape/VertexConditionNumberQualityMetric.cpp.
References QualityMetric::avgMethod, QualityMetric::feasible, QualityMetric::LINEAR, QualityMetric::set_metric_type(), QualityMetric::set_name(), and QualityMetric::VERTEX_BASED.
 {
   set_metric_type(VERTEX_BASED);
   avgMethod=QualityMetric::LINEAR;
   feasible=1;
   set_name("Vertex Condition Number");
 }
virtual ~VertexConditionNumberQualityMetric () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 60 of file includeLinks/VertexConditionNumberQualityMetric.hpp.
         {}
VertexConditionNumberQualityMetric ()
virtual ~VertexConditionNumberQualityMetric () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 60 of file src/QualityMetric/Shape/VertexConditionNumberQualityMetric.hpp.
         {}
Member Function Documentation
bool evaluate_vertex (PatchData & pd, MsqVertex * vert, double & fval, MsqError & err) virtual
evaluate using mesquite objects
Reimplemented from QualityMetric.
Definition at line 57 of file QualityMetric/Shape/VertexConditionNumberQualityMetric.cpp.
References QualityMetric::average_metrics(), ShapeQualityMetric::condition_number_2d(), ShapeQualityMetric::condition_number_3d(), MsqMeshEntity::get_connected_vertices(), PatchData::get_element_array(), PatchData::get_vertex_array(), PatchData::get_vertex_element_adjacencies(), PatchData::get_vertex_index(), Mesquite::HEXAHEDRON, i, MSQ_ERRZERO, Mesquite::MSQ_MAX_CAP, Mesquite::MSQ_SQRT_THREE, Mesquite::MSQ_SQRT_THREE_INV, Mesquite::MSQ_SQRT_TWO, Mesquite::QUADRILATERAL, Mesquite::TETRAHEDRON, and Mesquite::TRIANGLE.
 {
     //pd.generate_vertex_to_element_data();
   bool return_flag;
   fval=MSQ_MAX_CAP;
     //get the element array
   MsqMeshEntity* elems = pd.get_element_array(err);
     //convert the MsqVertex pointer into an index
   size_t this_vert = pd.get_vertex_index(vert);
     //get the vertex to element array and the offset array
   //const size_t* elem_offset = pd.get_vertex_to_elem_offset(err);  MSQ_ERRZERO(err);
   //const size_t* v_to_e_array = pd.get_vertex_to_elem_array(err);  MSQ_ERRZERO(err);
     //find the offset for this vertex
   //size_t this_offset = elem_offset[this_vert];
     //get the number of elements attached to this vertex (given by the
     //first entry in the vertex to element array)
   //size_t num_elems = v_to_e_array[this_offset];
     //PRINT_INFO("\nIN LOCAL SIZE CPP, num_elements = %i",num_elems);
     //if no elements, then return true
   size_t num_elems, *v_to_e_array;
   v_to_e_array = pd.get_vertex_element_adjacencies( this_vert, num_elems, err );
   MSQ_ERRZERO(err);
   if(num_elems <= 0){
     return true;
   }
     //create an array to store the local metric values before averaging
     //Can we remove this dynamic allocatio?
   double* met_vals = new double[num_elems];
     //vector to hold the other verts which form a corner.
   vector<size_t> other_vertices;
   other_vertices.reserve(4);
   size_t i=0;
     //only 3 temp_vec will be sent to cond-num calculator, but the
     //additional vector3Ds may be needed during the calculations
   Vector3D temp_vec[6];
   MsqVertex *vertices=pd.get_vertex_array(err);
   //loop over the elements attached to this vertex
   for(i=0;i<num_elems;++i){
       //get the vertices connected to this vertex for this element
     elems[v_to_e_array[i]].get_connected_vertices(this_vert,
                                                                 other_vertices,
                                                                 err);  MSQ_ERRZERO(err);
       //switch over the element type of this element
     switch(elems[v_to_e_array[i]].get_element_type()){
       case TRIANGLE:
         temp_vec[0]=vertices[other_vertices[0]]-vertices[this_vert];
         temp_vec[2]=vertices[other_vertices[1]]-vertices[this_vert];
           //make relative to equilateral
         temp_vec[1]=((2*temp_vec[2])-temp_vec[0])*MSQ_SQRT_THREE_INV;
         return_flag=condition_number_2d(temp_vec,this_vert,pd,met_vals[i],err);  MSQ_ERRZERO(err);
         if(!return_flag)
           return return_flag;
         break;
       case QUADRILATERAL:
         temp_vec[0]=vertices[other_vertices[0]]-vertices[this_vert];
         temp_vec[1]=vertices[other_vertices[1]]-vertices[this_vert];
         return_flag=condition_number_2d(temp_vec,this_vert,pd,met_vals[i],err);  MSQ_ERRZERO(err);
         if(!return_flag)
           return return_flag;
         break;
       case TETRAHEDRON:
         temp_vec[0]=vertices[other_vertices[0]]-vertices[this_vert];
         temp_vec[3]=vertices[other_vertices[1]]-vertices[this_vert];
         temp_vec[4]=vertices[other_vertices[2]]-vertices[this_vert];
           //transform to equilateral tet
         temp_vec[1]=((2*temp_vec[3])-temp_vec[0])/MSQ_SQRT_THREE;
         temp_vec[2]=((3*temp_vec[4])-temp_vec[0]-temp_vec[3])/
           (MSQ_SQRT_THREE*MSQ_SQRT_TWO);
         return_flag=condition_number_3d(temp_vec,pd,met_vals[i],err);  MSQ_ERRZERO(err);
         if(!return_flag)
           return return_flag;
         break;
       case HEXAHEDRON:
         temp_vec[0]=vertices[other_vertices[0]]-vertices[this_vert];
         temp_vec[1]=vertices[other_vertices[1]]-vertices[this_vert];
         temp_vec[2]=vertices[other_vertices[2]]-vertices[this_vert];
         return_flag=condition_number_3d(temp_vec,pd,met_vals[i],err);  MSQ_ERRZERO(err);
         if(!return_flag)
           return return_flag;
         break;
       default:
         fval=MSQ_MAX_CAP;
         return false;
     }// end switch over element type
     other_vertices.clear();
   }//end loop over elements
   fval = average_metrics(met_vals, num_elems, err);  MSQ_ERRZERO(err);
   delete []met_vals;
   return true;
 }
bool evaluate_vertex (PatchData & pd, MsqVertex * vert, double & fval, MsqError & err) virtual
evaluate using mesquite objects
Reimplemented from QualityMetric.
The documentation for this class was generated from the following files:
includeLinks/VertexConditionNumberQualityMetric.hpp
QualityMetric/Shape/VertexConditionNumberQualityMetric.cpp