Rocstar: gridgenGrdFormatter Class Reference
gridgenGrdFormatter Class Reference abstract
Abstracts the file format of a gridgen .grd file.
Public Member Functions
void setFile (FILE *f_)
virtual const char * readInt (int *dest)=0
virtual const char * readDouble (double *dest)=0
Protected Attributes
FILE * f
Detailed Description
Abstracts the file format of a gridgen .grd file.
Definition at line 105 of file readgrd.cpp.
Member Function Documentation
virtual const char* readDouble (double * dest) pure virtual
Implemented in gridgenBinaryFormatter< coordT >, gridgenBinaryFormatter< double >, gridgenBinaryFormatter< float >, and gridgenAsciiFormatter.
Referenced by read_general().
virtual const char* readInt (int * dest) pure virtual
Implemented in gridgenBinaryFormatter< coordT >, gridgenBinaryFormatter< double >, gridgenBinaryFormatter< float >, and gridgenAsciiFormatter.
Referenced by read_general().
void setFile (FILE * f_) inline
Definition at line 109 of file readgrd.cpp.
References f.
Referenced by read_general().
 {f=f_;}
Member Data Documentation
FILE* f protected
Definition at line 107 of file readgrd.cpp.
Referenced by gridgenAsciiFormatter::readDouble(), gridgenBinaryFormatter< float >::readDouble(), gridgenAsciiFormatter::readInt(), gridgenBinaryFormatter< float >::readInt(), and setFile().
The documentation for this class was generated from the following file:
readgrd.cpp