Rocstar: MsqDebug Class Reference
MsqDebug Class Reference
Mesquite debug output
Run-time activation/deactivation of debug flags.
#include <MsqDebug.hpp>
Classes
class FormatPrinter
class InitializeFlags
Public Types
enum { WARN = 1, INFO = 2 }
enum { WARN = 1, INFO = 2 }
Static Public Member Functions
static void enable (unsigned flag)
Enable a debug flag.
static void disable (unsigned flag)
Disable a debug flag.
static void set (unsigned flag, bool state)
Set a debug flag.
static bool get (unsigned flag)
Check a debug flag.
static void disable_all ()
Disable all debug streams.
static msq_stdio::ostream & get_stream (unsigned flag)
Get the output stream to be used for a given debug flag.
static void set_stream (unsigned flag, msq_stdio::ostream &stream)
Set the output stream to be used for a given debug flag.
static void enable (unsigned flag)
Enable a debug flag.
static void disable (unsigned flag)
Disable a debug flag.
static void set (unsigned flag, bool state)
Set a debug flag.
static bool get (unsigned flag)
Check a debug flag.
static void disable_all ()
Disable all debug streams.
static msq_stdio::ostream & get_stream (unsigned flag)
Get the output stream to be used for a given debug flag.
static void set_stream (unsigned flag, msq_stdio::ostream &stream)
Set the output stream to be used for a given debug flag.
Static Private Attributes
static msq_std::vector
< msq_stdio::ostream * > streams
static msq_std::vector< bool > flags
static InitializeFlags init
Detailed Description
Run-time activation/deactivation of debug flags.
Author
Jason Kraftcheck
Date
2004-10-18
Wrap static functions for managing debug flags and associated output streams. Output is expected do be done using the provided macros MSQ_DBGOUT, MSQ_PRINT, and MSQ_DBG.
The default output stream for all flags is cout.
Definition at line 87 of file includeLinks/MsqDebug.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator
WARN
INFO
Definition at line 92 of file includeLinks/MsqDebug.hpp.
          {
       WARN = 1,
       INFO = 2
     };
anonymous enum
Enumerator
WARN
INFO
Definition at line 92 of file src/Misc/MsqDebug.hpp.
          {
       WARN = 1,
       INFO = 2
     };
Member Function Documentation
static void disable (unsigned flag) inline static
Disable a debug flag.
Definition at line 100 of file includeLinks/MsqDebug.hpp.
References MsqDebug::set().
 { set( flag, false ); }
static void disable (unsigned flag) inline static
Disable a debug flag.
Definition at line 100 of file src/Misc/MsqDebug.hpp.
References MsqDebug::set().
 { set( flag, false ); }
void disable_all () static
Disable all debug streams.
Definition at line 76 of file Misc/MsqDebug.cpp.
References MsqDebug::flags.
 {
   flags.clear();
 }
static void disable_all () static
Disable all debug streams.
static void enable (unsigned flag) inline static
Enable a debug flag.
Definition at line 98 of file src/Misc/MsqDebug.hpp.
References MsqDebug::set().
 { set( flag, true );  }
static void enable (unsigned flag) inline static
Enable a debug flag.
Definition at line 98 of file includeLinks/MsqDebug.hpp.
References MsqDebug::set().
 { set( flag, true );  }
bool get (unsigned flag) static
Check a debug flag.
Definition at line 54 of file Misc/MsqDebug.cpp.
References MsqDebug::flags.
Referenced by MsqDebug::FormatPrinter::print().
 {
   return flag < flags.size() && flags[flag];
 }
static bool get (unsigned flag) static
Check a debug flag.
static msq_stdio::ostream& get_stream (unsigned flag) static
Get the output stream to be used for a given debug flag.
msq_stdio::ostream & get_stream (unsigned flag) static
Get the output stream to be used for a given debug flag.
Definition at line 81 of file Misc/MsqDebug.cpp.
References MsqDebug::streams.
Referenced by MsqDebug::FormatPrinter::print().
 {
   if (flag < streams.size())
     return *streams[flag];
   else
     return msq_stdio::cout;
 }
static void set (unsigned flag, bool state) static
Set a debug flag.
void set (unsigned flag, bool state) static
Set a debug flag.
Definition at line 59 of file Misc/MsqDebug.cpp.
References MsqDebug::flags.
Referenced by MsqDebug::disable(), and MsqDebug::enable().
 {
   if (state)
   {
     if (flag >= flags.size())
     {
       flags.resize(flag+1);
     }
     flags[flag] = true;
   }
   else
   {
     if (flag < flags.size())
       flags[flag] = false;
   }
 }
void set_stream (unsigned flag, msq_stdio::ostream & stream) static
Set the output stream to be used for a given debug flag.
Definition at line 89 of file Misc/MsqDebug.cpp.
References i, and MsqDebug::streams.
 {
   if (flag >= streams.size())
   {
     size_t old_size = streams.size();
     streams.resize( flag );
     for (unsigned i = old_size; i < flag; ++i)
       streams[i] = &msq_stdio::cout;
   }
   streams[flag] = &stream;
 }
static void set_stream (unsigned flag, msq_stdio::ostream & stream) static
Set the output stream to be used for a given debug flag.
Member Data Documentation
msq_std::vector< bool > flags static private
Definition at line 139 of file includeLinks/MsqDebug.hpp.
Referenced by MsqDebug::disable_all(), MsqDebug::get(), and MsqDebug::set().
MsqDebug::InitializeFlags init static private
Definition at line 140 of file includeLinks/MsqDebug.hpp.
msq_std::vector< msq_stdio::ostream * > streams static private
Definition at line 138 of file includeLinks/MsqDebug.hpp.
Referenced by MsqDebug::get_stream(), and MsqDebug::set_stream().
The documentation for this class was generated from the following files:
includeLinks/MsqDebug.hpp
Misc/MsqDebug.cpp