Rocstar: rflu_modcobalt Module Reference
rflu_modcobalt Module Reference
Data Types
type t_gridcobalt
Public Member Functions
subroutine, public rflu_convcobalt2rocflu (pRegion)
subroutine, public rflu_readgridcobalt (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCOBALT.F90,v $ $Revision: 1.5 $'
type(t_gridcobalt) gridcobalt
Detailed Description
Definition at line 39 of file RFLU_ModCOBALT.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_convcobalt2rocflu (type(t_region), pointer pRegion)
Definition at line 115 of file RFLU_ModCOBALT.F90.
References modsortsearch::binarysearchinteger(), buildfilenameplain(), modsortsearch::cyclelist(), moderror::deregisterfunction(), moderror::errorstop(), facecentroidquad(), facecentroidtria(), facevectorquad(), facevectortria(), form, j, key, modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modcellmapping::rflu_buildloc2globcellmapping(), rflu_modgeometry::rflu_computeapproxcentroids(), rflu_modgeometry::rflu_createapproxcentroids(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modgeometry::rflu_destroyapproxcentroids(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_moddimensions::rflu_setmaxdimension(), rflu_moddimensions::rflu_setmaxdimensions(), and Attribute::status().
Referenced by rflu_readconvgridwrapper().
subroutine, public rflu_readgridcobalt (type(t_region), pointer pRegion)
Definition at line 1581 of file RFLU_ModCOBALT.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), rflu_moddimensions::rflu_setmaxdimension(), and Attribute::status().
Referenced by rflu_readconvgridwrapper().
Member Data Documentation
type(t_gridcobalt) gridcobalt private
Definition at line 76 of file RFLU_ModCOBALT.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCOBALT.F90,v $ $Revision: 1.5 $' private
Definition at line 66 of file RFLU_ModCOBALT.F90.
The documentation for this module was generated from the following file:
RFLU_ModCOBALT.F90