Rocstar: SteepestDescent Class Reference
SteepestDescent Class Reference
#include <SteepestDescent.hpp>
Public Member Functions
SteepestDescent (ObjectiveFunction *of)
virtual ~SteepestDescent ()
void set_maximum_iteration (int iter)
void set_lower_gradient_bound (double gradc)
SteepestDescent (ObjectiveFunction *of)
virtual ~SteepestDescent ()
void set_maximum_iteration (int iter)
void set_lower_gradient_bound (double gradc)
Public Member Functions inherited from VertexMover
virtual ~VertexMover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
Improves the quality of the MeshSet, calling some methods specified in a class derived from VertexMover.
virtual ~VertexMover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
Public Member Functions inherited from QualityImprover
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Protected Member Functions
virtual void initialize (PatchData &pd, MsqError &err)
virtual void optimize_vertex_positions (PatchData &pd, MsqError &err)
virtual void initialize_mesh_iteration (PatchData &pd, MsqError &err)
virtual void terminate_mesh_iteration (PatchData &pd, MsqError &err)
virtual void cleanup ()
virtual void initialize (PatchData &pd, MsqError &err)
virtual void optimize_vertex_positions (PatchData &pd, MsqError &err)
virtual void initialize_mesh_iteration (PatchData &pd, MsqError &err)
virtual void terminate_mesh_iteration (PatchData &pd, MsqError &err)
virtual void cleanup ()
Protected Member Functions inherited from VertexMover
VertexMover ()
size_t check_feasible (PatchData &pd, MsqError &err)
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
VertexMover ()
size_t check_feasible (PatchData &pd, MsqError &err)
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
Protected Member Functions inherited from QualityImprover
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Private Attributes
double gradientLessThan
int maxIteration
Additional Inherited Members
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Protected Attributes inherited from VertexMover
ObjectiveFunction * objFunc
Detailed Description
This is a very basic implementation of the steepest descent optimization algorythm. It works on patches of any size but the step size is hard-wired. Obvisouly, this is for testing purposed only.
Definition at line 55 of file includeLinks/SteepestDescent.hpp.
Constructor & Destructor Documentation
SteepestDescent (ObjectiveFunction * of)
Definition at line 44 of file QualityImprover/VertexMover/SteepestDescent/SteepestDescent.cpp.
References PatchData::GLOBAL_PATCH, SteepestDescent::gradientLessThan, SteepestDescent::maxIteration, VertexMover::objFunc, QualityImprover::set_name(), and PatchDataUser::set_patch_type().
                                                       :
   VertexMover()
 {
   objFunc=of;
   MsqError err;
   gradientLessThan=.01;
   maxIteration=6;
   this->set_name("SteepestDescent");
   set_patch_type(PatchData::GLOBAL_PATCH, err);
 }
virtual ~SteepestDescent () inline virtual
Definition at line 60 of file includeLinks/SteepestDescent.hpp.
 { }
SteepestDescent (ObjectiveFunction * of)
virtual ~SteepestDescent () inline virtual
Definition at line 60 of file src/QualityImprover/VertexMover/SteepestDescent/SteepestDescent.hpp.
 { }
Member Function Documentation
void cleanup () protected virtual
Implements VertexMover.
Definition at line 192 of file QualityImprover/VertexMover/SteepestDescent/SteepestDescent.cpp.
 {
   //  cout << "- Executing SteepestDescent::iteration_end()\n";
 }
virtual void cleanup () protected virtual
Implements VertexMover.
virtual void initialize (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
void initialize (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 56 of file QualityImprover/VertexMover/SteepestDescent/SteepestDescent.cpp.
 {
 }
void initialize_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 60 of file QualityImprover/VertexMover/SteepestDescent/SteepestDescent.cpp.
 {
 }
virtual void initialize_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
virtual void optimize_vertex_positions (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
void optimize_vertex_positions (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 64 of file QualityImprover/VertexMover/SteepestDescent/SteepestDescent.cpp.
References TerminationCriterion::accumulate_inner(), ObjectiveFunction::compute_gradient(), PatchData::create_vertices_memento(), ObjectiveFunction::evaluate(), QualityImprover::get_inner_termination_criterion(), PatchData::get_vertex_array(), SteepestDescent::gradientLessThan, i, MsqError::INVALID_ARG, MsqError::INVALID_MESH, j, SteepestDescent::maxIteration, PatchData::move_free_vertices_constrained(), MSQ_CHKERR, MSQ_DBG, MSQ_DBGOUT, MSQ_ERRRTN, MSQ_FUNCTION_TIMER, MSQ_SETERR, MsqFreeVertexIndexIterator::next(), nvc::norm(), PatchData::num_free_vertices(), PatchData::num_vertices(), VertexMover::objFunc, MsqFreeVertexIndexIterator::reset(), PatchData::set_to_vertices_memento(), sqrt(), TerminationCriterion::terminate(), and MsqFreeVertexIndexIterator::value().
 {
   MSQ_FUNCTION_TIMER( "SteepestDescent::optimize_vertex_positions" );
     //PRINT_INFO("\no  Performing Steepest Descent optimization.\n");
   // Get the array of vertices of the patch. Free vertices are first.
   int num_vertices = pd.num_vertices();
   msq_std::vector<Vector3D> gradient(num_vertices), dk(num_vertices);
   int nb_iterations = 0;
   double norm=10e6;
   bool sd_bool=true;//bool for OF values
   double smallest_edge = 0.4; // TODO -- update -- used for step_size
   TerminationCriterion* term_crit=get_inner_termination_criterion();
   // does the steepest descent iteration until stopping is required.
   while ( (nb_iterations<maxIteration &&
           norm>gradientLessThan ) && !term_crit->terminate()) {
     ++nb_iterations;
     double original_value = 0.0;
       //get intial objective function value, original_value, and gradient
     objFunc->compute_gradient(pd, &gradient[0], original_value,
                               err, gradient.size()); MSQ_ERRRTN(err);
     // Prints out free vertices coordinates.
     if (MSQ_DBG(3)) {
       int num_free_vertices = pd.num_free_vertices(err); MSQ_ERRRTN(err);
       MSQ_DBGOUT(3) << "\n  o Free vertices ("<< num_free_vertices <<")original coordinates:\n ";
       MsqVertex* toto1 = pd.get_vertex_array(err); MSQ_ERRRTN(err);
       MsqFreeVertexIndexIterator ind1(&pd, err); MSQ_ERRRTN(err);
       ind1.reset();
       while (ind1.next()) {
         MSQ_DBGOUT(3) << "\t\t\t" << toto1[ind1.value()];
       }
     }
       // computes the gradient norm
     norm=0;
     for (int n=0; n<num_vertices; ++n)
       norm += gradient[n] % gradient[n]; // dot product
     norm = sqrt(norm);
     MSQ_DBGOUT(3) << "  o  gradient norm: " << norm << msq_stdio::endl;
     if (norm <= gradientLessThan) {
       break;
     }
     // ******** Chooses the search direction ********
     // i.e., -gradient for the steepest descent
     for (int i=0; i<num_vertices; ++i)
       for (int j=0; j<3; ++j)
         dk[i][j] = -gradient[i][j] / norm;
     // ******* Improve Quality *******
       //set an error if initial patch is invalid.
     if(!sd_bool){
       MSQ_SETERR(err)("SteepestDescent passed invalid initial patch.",
                       MsqError::INVALID_ARG);
       return;
     }
     MSQ_DBGOUT(3) << "  o  original_value: " << original_value << msq_stdio::endl;
     double new_value = original_value+1;
     // reduces the step size until we get an improvement
     int nb_iter = 0;
     // saves the PatchData coordinates in a memento
     PatchDataVerticesMemento* pd_previous_coords;
     pd_previous_coords = pd.create_vertices_memento(err);
     if (MSQ_CHKERR(err)) { delete pd_previous_coords; return; }
     // Loop to find a step size that improves quality
     double step_size = smallest_edge;
     while (new_value > original_value
            && nb_iter < 10 ) {
       nb_iter++;
         // change vertices coordinates in PatchData according to descent
         //direction.
       pd.move_free_vertices_constrained(&dk[0], dk.size(), step_size, err);
       if (MSQ_CHKERR(err)) { delete pd_previous_coords; return; }
       // and evaluate the objective function with the new node positions.
       sd_bool=objFunc->evaluate(pd, new_value, err);
       if (MSQ_CHKERR(err)) { delete pd_previous_coords; return; }
       if(!sd_bool){
         MSQ_SETERR(err)("SteepestDescent created invalid patch.",
                         MsqError::INVALID_MESH);
         delete pd_previous_coords;
         return;
       }
       MSQ_DBGOUT(3) << "    o  step_size: " << step_size << msq_stdio::endl;
       MSQ_DBGOUT(3) << "    o  new_value: " << new_value << msq_stdio::endl;
       // if no improvement
       if (new_value > original_value) {
         // undoes node movement
         pd.set_to_vertices_memento( pd_previous_coords, err );
         if (MSQ_CHKERR(err)) { delete pd_previous_coords; return; }
         // and reduces step size to try again.
         step_size /= 2;
       }
     }
     // Prints out free vertices coordinates.
     if (MSQ_DBG(3)) {
       MSQ_DBGOUT(3) << "  o Free vertices new coordinates: \n";
       MsqVertex* toto1 = pd.get_vertex_array(err);
       if (MSQ_CHKERR(err)) { delete pd_previous_coords; return; }
       MsqFreeVertexIndexIterator ind(&pd, err);
       if (MSQ_CHKERR(err)) { delete pd_previous_coords; return; }
       ind.reset();
       while (ind.next()) {
         MSQ_DBGOUT(3) << "\t\t\t" << toto1[ind.value()];
       }
     }
     delete pd_previous_coords; // user manages the memento.
     term_crit->accumulate_inner( pd, err ); MSQ_ERRRTN(err);
   }
 }
void set_lower_gradient_bound (double gradc) inline
Sets a minimum value for the gradient. If the gradient is below that value, we stop iterating.
Definition at line 70 of file src/QualityImprover/VertexMover/SteepestDescent/SteepestDescent.hpp.
References SteepestDescent::gradientLessThan.
{
         gradientLessThan=gradc;}
void set_lower_gradient_bound (double gradc) inline
Sets a minimum value for the gradient. If the gradient is below that value, we stop iterating.
Definition at line 70 of file includeLinks/SteepestDescent.hpp.
References SteepestDescent::gradientLessThan.
{
         gradientLessThan=gradc;}
void set_maximum_iteration (int iter) inline
sets the maximum number of iteration of the steepest descent algorythm, i.e. the number of times we compute the gradient and try to move the nodes in the opposite direction. This is different from the number of passes over the mesh.
Definition at line 65 of file includeLinks/SteepestDescent.hpp.
References SteepestDescent::maxIteration.
{
         maxIteration=iter;}
void set_maximum_iteration (int iter) inline
sets the maximum number of iteration of the steepest descent algorythm, i.e. the number of times we compute the gradient and try to move the nodes in the opposite direction. This is different from the number of passes over the mesh.
Definition at line 65 of file src/QualityImprover/VertexMover/SteepestDescent/SteepestDescent.hpp.
References SteepestDescent::maxIteration.
{
         maxIteration=iter;}
void terminate_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 187 of file QualityImprover/VertexMover/SteepestDescent/SteepestDescent.cpp.
 {
   //  cout << "- Executing SteepestDescent::iteration_complete()\n";
 }
virtual void terminate_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Member Data Documentation
double gradientLessThan private
Definition at line 83 of file includeLinks/SteepestDescent.hpp.
Referenced by SteepestDescent::optimize_vertex_positions(), SteepestDescent::set_lower_gradient_bound(), and SteepestDescent::SteepestDescent().
int maxIteration private
Definition at line 84 of file includeLinks/SteepestDescent.hpp.
Referenced by SteepestDescent::optimize_vertex_positions(), SteepestDescent::set_maximum_iteration(), and SteepestDescent::SteepestDescent().
The documentation for this class was generated from the following files:
includeLinks/SteepestDescent.hpp
QualityImprover/VertexMover/SteepestDescent/SteepestDescent.cpp