Rocstar: mblockData Class Reference
mblockData Class Reference
Classes
class blockPatches
Public Member Functions
mblockData (vector< block * > &blocks_)
~mblockData ()
void write (block *b, FILE *out)
int getPatchNumber (block *dest, patch *partner)
vector< patch * > & getPatchListWith (block *dest, patch *partner, int *hisFace=NULL)
Private Attributes
int nBlock
vector< block * > & blocks
blockPatches * block2patches
Detailed Description
Definition at line 63 of file writemblock.cpp.
Constructor & Destructor Documentation
mblockData (vector< block * > & blocks_) inline
Definition at line 101 of file writemblock.cpp.
References block2patches, blocks, and nBlock.
                 :blocks(blocks_)
         {
                 int b;
                 nBlock=blocks.size();
                 block2patches=new blockPatches[nBlock];
                 for (b=0;b<nBlock;b++)
                         block2patches[b].init(blocks[b]);
         }
~mblockData () inline
Definition at line 110 of file writemblock.cpp.
References block2patches.
                       {
                 delete[] block2patches;
         }
Member Function Documentation
vector<patch *>& getPatchListWith (block * dest, patch * partner, int * hisFace = NULL) inline
Definition at line 124 of file writemblock.cpp.
References block2patches, face, block::getBlockNumber(), mblockData::blockPatches::getPatchNumber(), and mblockData::blockPatches::patches.
         {
                 blockPatches &b=block2patches[dest->getBlockNumber()];
                 int face;
                 b.getPatchNumber(partner,&face);
                 if (hisFace!=NULL) *hisFace=face;
                 return b.patches[face];
         }
int getPatchNumber (block * dest, patch * partner) inline
Definition at line 119 of file writemblock.cpp.
References block2patches, and block::getBlockNumber().
Referenced by internalBCpatch::writeMblock().
         {
                 return block2patches[dest->getBlockNumber()].
                         getPatchNumber(partner);
         }
void write (block * b, FILE * out) inline
Definition at line 114 of file writemblock.cpp.
References block2patches, block::getBlockNumber(), and mblockData::blockPatches::write().
Referenced by writeMblock().
{
                 block2patches[b->getBlockNumber()].write(out,*this,b);
         }
Member Data Documentation
blockPatches* block2patches private
Definition at line 99 of file writemblock.cpp.
Referenced by getPatchListWith(), getPatchNumber(), mblockData(), write(), and ~mblockData().
vector<block *>& blocks private
Definition at line 65 of file writemblock.cpp.
Referenced by mblockData().
int nBlock private
Definition at line 64 of file writemblock.cpp.
Referenced by mblockData().
The documentation for this class was generated from the following file:
writemblock.cpp