Rocstar: rflu_modstencilsutils Module Reference
rflu_modstencilsutils Module Reference
Public Member Functions
subroutine, public rflu_addbfaces (pRegion, nBFaceMembsMaxTemp, nCellMembs, cellMembs, nBFaceMembs, bFaceMembs)
subroutine, public rflu_addcelllayer_1d (global, pGrid, stencilSizeMax, ixg, degr, x2csBeg, x2csEnd, x2cs, fnDir)
subroutine, public rflu_addcelllayer_1d_g (global, pGrid, stencilSizeMax, ixg, degr, x2csBeg, x2csEnd, x2cs, rc, dir)
subroutine, public rflu_addcelllayer (global, pGrid, stencilSizeMax, ixg, degr, x2csBeg, x2csEnd, x2cs)
subroutine, public rflu_addfacevertneighbs (global, pGrid, stencilSizeMax, f2v, degr, x2cs)
INTEGER function, public rflu_computestencilsize (global, dimens, factor, order)
subroutine, public rflu_computestencilweights (global, dimens, wtsMode, scalMode, derivDegree, orderNominal, nRows, dr, wts, sCount)
subroutine, public rflu_sortbfaces (pRegion, xyz, nBFaceMembs, bFaceMembs)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsUtils.F90,v $ $Revision: 1.14 $'
Detailed Description
Definition at line 39 of file RFLU_ModStencilsUtils.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_addbfaces (type(t_region), pointer pRegion, integer, intent(in) nBFaceMembsMaxTemp, integer, intent(in) nCellMembs, integer, dimension(ncellmembs), intent(in) cellMembs, integer, intent(out) nBFaceMembs, integer, dimension(2,nbfacemembsmaxtemp), intent(out) bFaceMembs)
Definition at line 104 of file RFLU_ModStencilsUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), and moderror::registerfunction().
Referenced by rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), and rflu_modstencilsfaces::rflu_buildf2cstencil().
subroutine, public rflu_addcelllayer (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, intent(in) stencilSizeMax, integer, intent(in) ixg, integer, intent(inout) degr, integer, intent(in) x2csBeg, integer, intent(in) x2csEnd, integer, dimension(stencilsizemax), intent(inout) x2cs)
Definition at line 669 of file RFLU_ModStencilsUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), moderror::registerfunction(), and rflu_modcellfaceedgeinfo::rflu_getglobalcelltype().
Referenced by rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), and rflu_modstencilsvert::rflu_buildstencilvert2cell().
subroutine, public rflu_addcelllayer_1d (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, intent(in) stencilSizeMax, integer, intent(in) ixg, integer, intent(inout) degr, integer, intent(in) x2csBeg, integer, intent(in) x2csEnd, integer, dimension(stencilsizemax), intent(inout) x2cs, integer, intent(in) fnDir)
Definition at line 306 of file RFLU_ModStencilsUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), modsortsearch::quicksortinteger(), and moderror::registerfunction().
Referenced by rflu_modstencilsbfaces::rflu_buildbf2cstencil_1d(), rflu_modstencilscells::rflu_buildc2cstencil_1d(), and rflu_modstencilsfaces::rflu_buildf2cstencil_1d().
subroutine, public rflu_addcelllayer_1d_g (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, intent(in) stencilSizeMax, integer, intent(in) ixg, integer, intent(inout) degr, integer, intent(in) x2csBeg, integer, intent(in) x2csEnd, integer, dimension(stencilsizemax), intent(inout) x2cs, real(rfreal), dimension(xcoord:zcoord), intent(in) rc, integer, intent(in) dir)
Definition at line 485 of file RFLU_ModStencilsUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), vector3d::dir(), moderror::errorstop(), modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modcellfaceedgeinfo::rflu_getglobalcelltype(), and rflu_modgeometrytools::rflu_testvectorcartaxisaligned().
Referenced by rflu_modstencilscells::rflu_buildc2cstencil_1d_g().
subroutine, public rflu_addfacevertneighbs (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, intent(in) stencilSizeMax, integer, dimension(4), intent(in) f2v, integer, intent(inout) degr, integer, dimension(stencilsizemax), intent(inout) x2cs)
Definition at line 953 of file RFLU_ModStencilsUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), modsortsearch::quicksortinteger(), and moderror::registerfunction().
Referenced by rflu_modstencilsbfaces::rflu_buildbf2cstencil(), and rflu_modstencilsfaces::rflu_buildf2cstencil().
INTEGER function, public rflu_computestencilsize (type(t_global), pointer global, integer, intent(in) dimens, integer, intent(in) factor, integer, intent(in) order)
Definition at line 1068 of file RFLU_ModStencilsUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), and rflu_computestencilsize().
subroutine, public rflu_computestencilweights (type(t_global), pointer global, integer, intent(in) dimens, integer, intent(in) wtsMode, integer, intent(in) scalMode, integer, intent(in) derivDegree, integer, intent(in) orderNominal, integer, intent(in) nRows, real(rfreal), dimension(xcoord:zcoord,nrows), intent(in) dr, real(rfreal), dimension(:,:), intent(out) wts, integer, intent(out), optional sCount)
Definition at line 1165 of file RFLU_ModStencilsUtils.F90.
References Line_2< R, T >::a(), ainv(), modtools::compfact(), moderror::deregisterfunction(), moderror::errorstop(), j, Generic_element_2::order(), q, Color::r(), moderror::registerfunction(), rflu_computestencilsize(), rflu_invertmatrixsvd(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_modstencilsvert::rflu_buildstencilvert2cell(), and rflu_modinterpolation::rflu_interpcells2verts().
subroutine, public rflu_sortbfaces (type(t_region), pointer pRegion, real(rfreal), dimension(xcoord:zcoord), intent(in) xyz, integer, intent(in) nBFaceMembs, integer, dimension(2,nbfacemembs), intent(inout) bFaceMembs)
Definition at line 1484 of file RFLU_ModStencilsUtils.F90.
References moderror::deregisterfunction(), dist(), key, modsortsearch::quicksortrfrealinteger(), and moderror::registerfunction().
Referenced by rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), and rflu_modstencilsfaces::rflu_buildf2cstencil().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsUtils.F90,v $ $Revision: 1.14 $' private
Definition at line 71 of file RFLU_ModStencilsUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModStencilsUtils.F90