Rocstar: rflo_modrestartinfo Module Reference
rflo_modrestartinfo Module Reference
Public Member Functions
subroutine rflo_closerestartinfo (global)
subroutine, public rflo_readrestartinfo (global)
subroutine, public rflo_writerestartinfo (global)
Private Member Functions
subroutine rflo_openrestartinfo (global, filePosition, fileExists)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModRestartInfo.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 37 of file RFLO_ModRestartInfo.F90.
Member Function/Subroutine Documentation
subroutine rflo_closerestartinfo (type(t_global), pointer global)
Definition at line 192 of file RFLO_ModRestartInfo.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflo_readrestartinfo(), and rflo_writerestartinfo().
subroutine rflo_openrestartinfo (type(t_global), pointer global, integer, intent(in) filePosition, logical, intent(out) fileExists) private
Definition at line 95 of file RFLO_ModRestartInfo.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflo_readrestartinfo(), and rflo_writerestartinfo().
subroutine, public rflo_readrestartinfo (type(t_global), pointer global)
Definition at line 267 of file RFLO_ModRestartInfo.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_closerestartinfo(), and rflo_openrestartinfo().
Referenced by rflo_initflowsolver().
subroutine, public rflo_writerestartinfo (type(t_global), pointer global)
Definition at line 395 of file RFLO_ModRestartInfo.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_closerestartinfo(), and rflo_openrestartinfo().
Referenced by rflo_dualtimestepping(), and rflo_timestepping().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModRestartInfo.F90,v $ $Revision: 1.5 $' private
Definition at line 61 of file RFLO_ModRestartInfo.F90.
The documentation for this module was generated from the following file:
RFLO_ModRestartInfo.F90