Rocstar: rflo_modmovegridelliptfra Module Reference
rflo_modmovegridelliptfra Module Reference
Public Member Functions
subroutine, public rflo_movegridelliptfra (regions)
subroutine rflo_mgelliptsurfacesfra (regions, someMoved)
subroutine rflo_mgelliptedgesfra (region, boundMoved, allExternal, edgeMoved, arcLen12, arcLen34, arcLen56, xyzRef, xyzOld, dNode)
subroutine rflo_mgelliptboundaries (region, boundMoved, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgelliptinterfacesfra (regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModMoveGridElliptFra.F90,v $ $Revision: 1.16 $'
Detailed Description
Definition at line 40 of file RFLO_ModMoveGridElliptFra.F90.
Member Function/Subroutine Documentation
subroutine rflo_mgelliptboundaries (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 709 of file RFLO_ModMoveGridElliptFra.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, p1, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint2d(), s, and sqrt().
subroutine rflo_mgelliptedgesfra (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(6) allExternal, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzRef, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 521 of file RFLO_ModMoveGridElliptFra.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint1d(), s, and sqrt().
Referenced by rflo_mgelliptinterfacesfra(), and rflo_mgelliptsurfacesfra().
subroutine rflo_mgelliptinterfacesfra (type(t_region), dimension(:), pointer regions)
Definition at line 929 of file RFLO_ModMoveGridElliptFra.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_clearsendrequests(), rflo_edgedeformation(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), and rflo_mgelliptedgesfra().
Referenced by rflo_movegridelliptfra().
subroutine rflo_mgelliptsurfacesfra (type(t_region), dimension(:), pointer regions, logical someMoved)
Definition at line 371 of file RFLO_ModMoveGridElliptFra.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_arclengthbounds(), rflo_boundarydeformation(), rflo_edgedeformationstraight(), rflo_getdeformation(), rflo_mgelliptedgesfra(), rflo_modmovegridframe::rflo_mgframebroadcast(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframemovecorners(), and rflo_modmovegridframe::rflo_mgframeorthoshift().
Referenced by rflo_movegridelliptfra().
subroutine, public rflo_movegridelliptfra (type(t_region), dimension(:), pointer regions)
Definition at line 92 of file RFLO_ModMoveGridElliptFra.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_copygeometrydummy(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modelliptsmoothing::rflo_elliptgridsmooregion(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_modgridmetrics::rflo_gridqualityglobal(), rflo_laplacegridsmoo(), rflo_modmovegridelliptglo::rflo_mgelliptbnddeformation(), rflo_mgelliptinterfacesfra(), rflo_mgelliptsurfacesfra(), rflo_movegridinterfaces(), sqrt(), and x.
Referenced by rflo_dualtimestepping(), and rflo_timestepping().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModMoveGridElliptFra.F90,v $ $Revision: 1.16 $' private
Definition at line 65 of file RFLO_ModMoveGridElliptFra.F90.
The documentation for this module was generated from the following file:
RFLO_ModMoveGridElliptFra.F90