Rocstar: Plane_3< R, T > Class Template Reference
Plane_3< R, T > Class Template Reference
#include <cartesian_classes.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Plane_3_base RPlane_3
Public Member Functions
Plane_3 ()
Plane_3 (const CGAL::Plane_3< R > &p)
Plane_3 (const RPlane_3 &p)
Plane_3 (const CGAL::Point_3< R > &p, const CGAL::Point_3< R > &q, const CGAL::Point_3< R > &r)
Plane_3 (const CGAL::Point_3< R > &p, const CGAL::Direction_3< R > &d)
Plane_3 (const CGAL::Point_3< R > &p, const CGAL::Vector_3< R > &v)
Plane_3 (const RT &a, const RT &b, const RT &c, const RT &d)
Plane_3 (const CGAL::Line_3< R > &l, const CGAL::Point_3< R > &p)
Plane_3 (const CGAL::Segment_3< R > &s, const CGAL::Point_3< R > &p)
Plane_3 (CGAL::Ray_3< R > &r, const CGAL::Point_3< R > &p)
bool operator== (const CGAL::Plane_3< R > &p) const
bool operator!= (const CGAL::Plane_3< R > &p) const
RT a () const
RT b () const
RT c () const
RT d () const
CGAL::Line_3< R > perpendicular_line (const CGAL::Point_3< R > &p) const
CGAL::Plane_3< R > opposite () const
CGAL::Point_3< R > projection (const CGAL::Point_3< R > &p) const
CGAL::Point_3< R > point () const
CGAL::Vector_3< R > orthogonal_vector () const
CGAL::Direction_3< R > orthogonal_direction () const
CGAL::Vector_3< R > base1 () const
CGAL::Vector_3< R > base2 () const
CGAL::Point_2< R > to_2d (const CGAL::Point_3< R > &p) const
CGAL::Point_3< R > to_3d (const CGAL::Point_2< R > &p) const
CGAL::Plane_3< R > transform (CGAL::Aff_transformation_3< R > &t) const
Oriented_side oriented_side (const CGAL::Point_3< R > &p) const
bool has_on (const CGAL::Point_3< R > &p) const
bool has_on (const CGAL::Line_3< R > &l) const
bool has_on_boundary (const CGAL::Point_3< R > &p) const
bool has_on_boundary (const CGAL::Line_3< R > &l) const
bool has_on_positive_side (const CGAL::Point_3< R > &p) const
bool has_on_negative_side (const CGAL::Point_3< R > &p) const
bool is_degenerate () const
Detailed Description
template<class R, class T = typename R::Rep_tag>
class Plane_3< R, T >
Definition at line 77 of file cartesian_classes.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 95 of file Plane_3.h.
typedef R_ R
Definition at line 93 of file Plane_3.h.
typedef R::Plane_3_base RPlane_3
Definition at line 96 of file Plane_3.h.
typedef R::RT RT
Definition at line 94 of file Plane_3.h.
Constructor & Destructor Documentation
Plane_3 () inline
Definition at line 98 of file Plane_3.h.
             : RPlane_3()
   {}
Plane_3 (const CGAL::Plane_3< R > & p) inline
Definition at line 100 of file Plane_3.h.
                                    : RPlane_3(p)
   {}
Plane_3 (const RPlane_3< R, T > & p) inline
Definition at line 102 of file Plane_3.h.
                               : RPlane_3(p)
   {}
Plane_3 (const CGAL::Point_3< R > & p, const CGAL::Point_3< R > & q, const CGAL::Point_3< R > & r) inline
Definition at line 104 of file Plane_3.h.
     : RPlane_3(p,q,r)
   {}
Plane_3 (const CGAL::Point_3< R > & p, const CGAL::Direction_3< R > & d) inline
Definition at line 109 of file Plane_3.h.
     : RPlane_3(p,d)
   {}
Plane_3 (const CGAL::Point_3< R > & p, const CGAL::Vector_3< R > & v) inline
Definition at line 112 of file Plane_3.h.
     : RPlane_3(p,v)
   {}
Plane_3 (const RT & a, const RT & b, const RT & c, const RT & d) inline
Definition at line 115 of file Plane_3.h.
     : RPlane_3(a,b,c,d)
   {}
Plane_3 (const CGAL::Line_3< R > & l, const CGAL::Point_3< R > & p) inline
Definition at line 118 of file Plane_3.h.
     : RPlane_3(l,p)
   {}
Plane_3 (const CGAL::Segment_3< R > & s, const CGAL::Point_3< R > & p) inline
Definition at line 121 of file Plane_3.h.
     : RPlane_3(s,p)
   {}
Plane_3 (CGAL::Ray_3< R > & r, const CGAL::Point_3< R > & p) inline
Definition at line 124 of file Plane_3.h.
     : RPlane_3(r,p)
   {}
Member Function Documentation
RT a () const inline
Definition at line 135 of file Plane_3.h.
   { return RPlane_3::a(); }
RT b () const inline
Definition at line 138 of file Plane_3.h.
   { return RPlane_3::b(); }
CGAL::Vector_3<R> base1 () const inline
Definition at line 165 of file Plane_3.h.
   { return RPlane_3::base1(); }
CGAL::Vector_3<R> base2 () const inline
Definition at line 168 of file Plane_3.h.
   { return RPlane_3::base2(); }
RT c () const inline
Definition at line 141 of file Plane_3.h.
   { return RPlane_3::c(); }
RT d () const inline
Definition at line 144 of file Plane_3.h.
Referenced by ainv(), bc_enforce(), init_py::burn_get_film_coeff_1d(), cst_coh(), rflu_modrepair3d::dihed(), entropy_corr1(), entropy_corr2(), rflu_modentropyfixes::entropyfixhartenhyman(), implicit_soln(), spec_rflu_modchemistry::lusolve(), mixtgasliq_c(), mixtperf_c_dgp(), mixtperf_eo_dgpuvw(), mixtperf_eo_dgpvm(), mixtperf_p_ddogpo(), mixtperf_p_deogvm2(), mixtperf_p_drt(), mixtperf_t_dpr(), peul_residualsmoothing(), radi_rflo_flimressmoothing(), setup_py::read_properties(), setup_py::readtable(), rflo_laplacegridsolve(), rflo_modlaplacesmoothing::rflo_laplacegridsolve(), rflo_residualsmoothing(), rflu_computeenerdissoles(), rflu_modexactflow::rflu_computeexactflowculick(), rflu_modexactflow::rflu_computeexactflowpacoust(), rflu_modexactflow::rflu_computeexactflowproudman(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_computeintegral3oles(), rflu_modoles::rflu_geti1posoles(), rflu_modoles::rflu_geti4posoles(), rflu_initbcdatahardcode(), rflu_initflowhardcode(), rflu_initflowhardcodelim(), rflu_modbessel::rflu_jyndd(), rflu_modbessel::rflu_jyzo(), rflu_modrepair3d::snglar(), solve_x(), tql1(), tql2(), tred1(), tred2(), tridg(), turb_rflo_ransressmoothing(), v3d10(), v3d10_ale(), v3d10_b_bar(), v3d10_nl(), v3d10_nl_arruda_boyce(), v3d10_nl_arruda_boyce_damping(), v3d10_nl_arruda_boyce_thermal(), v3d10_nl_damping(), v3d10_nl_huang(), v3d10_nl_matous(), v3d10r_nl(), v3d4(), v3d4_ale(), v3d4_neohookeancompress(), v3d4_neohookeanincompress(), v3d4_neohookeanincompressdef(), v3d4_neohookeanincompressprin(), v3d4_nl(), v3d4_nl_arruda_boyce(), and v3d4_thermalexp2().
   { return RPlane_3::d(); }
bool has_on (const CGAL::Point_3< R > & p) const inline
Definition at line 183 of file Plane_3.h.
   { return RPlane_3::has_on_boundary(p); }
bool has_on (const CGAL::Line_3< R > & l) const inline
Definition at line 186 of file Plane_3.h.
   { return RPlane_3::has_on_boundary(l); }
bool has_on_boundary (const CGAL::Point_3< R > & p) const inline
Definition at line 189 of file Plane_3.h.
   { return RPlane_3::has_on_boundary(p); }
bool has_on_boundary (const CGAL::Line_3< R > & l) const inline
Definition at line 192 of file Plane_3.h.
   { return RPlane_3::has_on_boundary(l); }
bool has_on_negative_side (const CGAL::Point_3< R > & p) const inline
Definition at line 198 of file Plane_3.h.
   { return RPlane_3::has_on_negative_side(p); }
bool has_on_positive_side (const CGAL::Point_3< R > & p) const inline
Definition at line 195 of file Plane_3.h.
   { return RPlane_3::has_on_positive_side(p); }
bool is_degenerate () const inline
Definition at line 201 of file Plane_3.h.
   { return RPlane_3::is_degenerate(); }
bool operator!= (const CGAL::Plane_3< R > & p) const inline
Definition at line 131 of file Plane_3.h.
   { return !(*this == p); }
bool operator== (const CGAL::Plane_3< R > & p) const inline
Definition at line 128 of file Plane_3.h.
References operator==().
   { return RPlane_3::operator==(p); }
CGAL::Plane_3<R> opposite () const inline
Definition at line 150 of file Plane_3.h.
References opposite().
   { return RPlane_3::opposite(); }
Oriented_side oriented_side (const CGAL::Point_3< R > & p) const inline
Definition at line 180 of file Plane_3.h.
   { return RPlane_3::oriented_side(p); }
CGAL::Direction_3<R> orthogonal_direction () const inline
Definition at line 162 of file Plane_3.h.
   { return RPlane_3::orthogonal_direction(); }
CGAL::Vector_3<R> orthogonal_vector () const inline
Definition at line 159 of file Plane_3.h.
   { return RPlane_3::orthogonal_vector(); }
CGAL::Line_3<R> perpendicular_line (const CGAL::Point_3< R > & p) const inline
Definition at line 147 of file Plane_3.h.
   { return RPlane_3::perpendicular_line(p); }
CGAL::Point_3<R> point () const inline
Definition at line 156 of file Plane_3.h.
   { return RPlane_3::point(); }
CGAL::Point_3<R> projection (const CGAL::Point_3< R > & p) const inline
Definition at line 153 of file Plane_3.h.
References projection().
   { return RPlane_3::projection(p); }
CGAL::Point_2<R> to_2d (const CGAL::Point_3< R > & p) const inline
Definition at line 171 of file Plane_3.h.
   { return RPlane_3::to_2d(p); }
CGAL::Point_3<R> to_3d (const CGAL::Point_2< R > & p) const inline
Definition at line 174 of file Plane_3.h.
   { return RPlane_3::to_3d(p); }
CGAL::Plane_3<R> transform (CGAL::Aff_transformation_3< R > & t) const inline
Definition at line 177 of file Plane_3.h.
   { return CGAL::Plane_3<R>( RPlane_3::transform(t) ); }
The documentation for this class was generated from the following files:
cartesian_classes.h
Plane_3.h