Rocstar: fdistream Class Reference
fdistream Class Reference
#include <FDUtils.H>
Public Member Functions
fdistream ()
fdistream (int fd)
int FD ()
int Init (int _fd)
Protected Attributes
Sys::fdinbuf buf
Detailed Description
Definition at line 154 of file FDUtils.H.
Constructor & Destructor Documentation
fdistream () inline
Definition at line 158 of file FDUtils.H.
 : std::istream(0) {};
fdistream (int fd) inline
Definition at line 159 of file FDUtils.H.
References fdistream::buf.
                          : std::istream(0), buf(fd) {
         rdbuf(&buf);
       };
Member Function Documentation
int FD () inline
Definition at line 162 of file FDUtils.H.
References fdistream::buf, and fdinbuf::FD().
 { return(buf.FD()); };
int Init (int _fd) inline
Definition at line 163 of file FDUtils.H.
References fdistream::buf, fdinbuf::FD(), and fdinbuf::Init().
Referenced by InProcess::Execute(), and InProcess::InProcess().
 { buf.Init(_fd); rdbuf(&buf); return(buf.FD());};
Member Data Documentation
Sys::fdinbuf buf protected
Definition at line 156 of file FDUtils.H.
Referenced by fdistream::FD(), fdistream::fdistream(), and fdistream::Init().
The documentation for this class was generated from the following file:
FDUtils.H