Rocstar: MsqError Class Reference
MsqError Class Reference
Mesquite internal error handling
Used to hold the error state and return it to the application.
#include <MsqError.hpp>
Classes
class Setter
class Trace
One line of stack trace data.
Public Types
enum ErrorCode {
NO_ERROR = 0, UNKNOWN_ERROR, OUT_OF_MEMORY, INVALID_ARG,
NOT_INITIALIZED, INVALID_STATE, FILE_ACCESS, FILE_FORMAT,
PARSE_ERROR, IO_ERROR, INVALID_MESH, NO_PD_STORAGE_MODE,
NOT_IMPLEMENTED, INTERNAL_ERROR, INTERRUPTED, TAG_ALREADY_EXISTS,
TAG_NOT_FOUND, LAST_ERROR_CODE, NO_ERROR = 0, UNKNOWN_ERROR,
OUT_OF_MEMORY, INVALID_ARG, NOT_INITIALIZED, INVALID_STATE,
FILE_ACCESS, FILE_FORMAT, PARSE_ERROR, IO_ERROR,
INVALID_MESH, NO_PD_STORAGE_MODE, NOT_IMPLEMENTED, INTERNAL_ERROR,
INTERRUPTED, TAG_ALREADY_EXISTS, TAG_NOT_FOUND, LAST_ERROR_CODE
}
Error codes.
enum ErrorCode {
NO_ERROR = 0, UNKNOWN_ERROR, OUT_OF_MEMORY, INVALID_ARG,
NOT_INITIALIZED, INVALID_STATE, FILE_ACCESS, FILE_FORMAT,
PARSE_ERROR, IO_ERROR, INVALID_MESH, NO_PD_STORAGE_MODE,
NOT_IMPLEMENTED, INTERNAL_ERROR, INTERRUPTED, TAG_ALREADY_EXISTS,
TAG_NOT_FOUND, LAST_ERROR_CODE, NO_ERROR = 0, UNKNOWN_ERROR,
OUT_OF_MEMORY, INVALID_ARG, NOT_INITIALIZED, INVALID_STATE,
FILE_ACCESS, FILE_FORMAT, PARSE_ERROR, IO_ERROR,
INVALID_MESH, NO_PD_STORAGE_MODE, NOT_IMPLEMENTED, INTERNAL_ERROR,
INTERRUPTED, TAG_ALREADY_EXISTS, TAG_NOT_FOUND, LAST_ERROR_CODE
}
Error codes.
typedef msq_std::list< Trace > StackTrace
Container type used to store stack trace.
typedef msq_std::list< Trace > StackTrace
Container type used to store stack trace.
Public Member Functions
void clear ()
resets error object to non-active state (no error).
bool error () const
Check if an error has occured.
operator bool () const
Check if an error has occured.
MsqError ()
Initialize to cleared state.
virtual ~MsqError ()
Destructor - empty but must declar virtual destrucor if virtual functions.
ErrorCode error_code () const
Get error code.
const char * error_message () const
Get error message.
const StackTrace & stack () const
Get stack trace.
virtual bool push (const char *function, const char *file, int line)
Add to back-trace of call stack.
virtual bool set_error (ErrorCode num, const char *msg=0)
Initialize the error object with the passed data.
void clear ()
resets error object to non-active state (no error).
bool error () const
Check if an error has occured.
operator bool () const
Check if an error has occured.
MsqError ()
Initialize to cleared state.
virtual ~MsqError ()
Destructor - empty but must declar virtual destrucor if virtual functions.
ErrorCode error_code () const
Get error code.
const char * error_message () const
Get error message.
const StackTrace & stack () const
Get stack trace.
virtual bool push (const char *function, const char *file, int line)
Add to back-trace of call stack.
virtual bool set_error (ErrorCode num, const char *msg=0)
Initialize the error object with the passed data.
Static Public Member Functions
static Setter setter (MsqError &err, const char *function, const char *file, int line)
static Setter setter (MsqError &err, const char *function, const char *file, int line)
Private Attributes
ErrorCode errorCode
msq_std::string errorMessage
StackTrace stackTrace
Detailed Description
Used to hold the error state and return it to the application.
Author
Jason Kraftcheck
Date
2004-09-17
Used to hold error state and related information. Internal Mesquite code should access this object via the MSQ_SETERR and MSQ_CHKERR macros.
For applications, the cast-to-bool operator and << operator are provided for convenient, if simple access to this data. E.g.: if (err) cout << err << endl;
There are two options for an application to gain more detailed access to the error data. The application may either access the data stored in this class via the provided methods or subclass MsqError, overriding set_error and push to handle the error data as it is generated.
Definition at line 106 of file includeLinks/MsqError.hpp.
Member Typedef Documentation
typedef msq_std::list<Trace> StackTrace
Container type used to store stack trace.
Return type for stack
Definition at line 173 of file includeLinks/MsqError.hpp.
typedef msq_std::list<Trace> StackTrace
Container type used to store stack trace.
Return type for stack
Definition at line 173 of file src/Misc/MsqError.hpp.
Member Enumeration Documentation
enum ErrorCode
Error codes.
Enumerator
NO_ERROR
no error
UNKNOWN_ERROR
unknown error occured
OUT_OF_MEMORY
unable to allocate the necessary memory
INVALID_ARG
invalid function argument passed
NOT_INITIALIZED
object not initialized
INVALID_STATE
object is in an invalid state
FILE_ACCESS
File cannot be opened/created.
FILE_FORMAT
Wrong file type.
PARSE_ERROR
Error parsing input (or input file)
IO_ERROR
An I/O error occured (e.g.
read from file failed.)
INVALID_MESH
The mesh is invalid.
NO_PD_STORAGE_MODE
no storage mode chosen within PatchData
NOT_IMPLEMENTED
requested functionality is not (yet) implemented
INTERNAL_ERROR
A bug in Mesquite.
INTERRUPTED
Application or user interrupted operation.
TAG_ALREADY_EXISTS
Attempt to create tag that already exists.
TAG_NOT_FOUND
Specified tag does not exist.
LAST_ERROR_CODE
NO_ERROR
no error
UNKNOWN_ERROR
unknown error occured
OUT_OF_MEMORY
unable to allocate the necessary memory
INVALID_ARG
invalid function argument passed
NOT_INITIALIZED
object not initialized
INVALID_STATE
object is in an invalid state
FILE_ACCESS
File cannot be opened/created.
FILE_FORMAT
Wrong file type.
PARSE_ERROR
Error parsing input (or input file)
IO_ERROR
An I/O error occured (e.g.
read from file failed.)
INVALID_MESH
The mesh is invalid.
NO_PD_STORAGE_MODE
no storage mode chosen within PatchData
NOT_IMPLEMENTED
requested functionality is not (yet) implemented
INTERNAL_ERROR
A bug in Mesquite.
INTERRUPTED
Application or user interrupted operation.
TAG_ALREADY_EXISTS
Attempt to create tag that already exists.
TAG_NOT_FOUND
Specified tag does not exist.
LAST_ERROR_CODE
Definition at line 115 of file includeLinks/MsqError.hpp.
                  {
     NO_ERROR          =  0,
     UNKNOWN_ERROR,
     OUT_OF_MEMORY,
     INVALID_ARG ,
     NOT_INITIALIZED,
     INVALID_STATE,
     FILE_ACCESS,
     FILE_FORMAT,
     PARSE_ERROR,
     IO_ERROR,
     INVALID_MESH,
     NO_PD_STORAGE_MODE,
     NOT_IMPLEMENTED,
     INTERNAL_ERROR,
     INTERRUPTED,
     TAG_ALREADY_EXISTS,
     TAG_NOT_FOUND,
     LAST_ERROR_CODE
   };
enum ErrorCode
Error codes.
Enumerator
NO_ERROR
no error
UNKNOWN_ERROR
unknown error occured
OUT_OF_MEMORY
unable to allocate the necessary memory
INVALID_ARG
invalid function argument passed
NOT_INITIALIZED
object not initialized
INVALID_STATE
object is in an invalid state
FILE_ACCESS
File cannot be opened/created.
FILE_FORMAT
Wrong file type.
PARSE_ERROR
Error parsing input (or input file)
IO_ERROR
An I/O error occured (e.g.
read from file failed.)
INVALID_MESH
The mesh is invalid.
NO_PD_STORAGE_MODE
no storage mode chosen within PatchData
NOT_IMPLEMENTED
requested functionality is not (yet) implemented
INTERNAL_ERROR
A bug in Mesquite.
INTERRUPTED
Application or user interrupted operation.
TAG_ALREADY_EXISTS
Attempt to create tag that already exists.
TAG_NOT_FOUND
Specified tag does not exist.
LAST_ERROR_CODE
NO_ERROR
no error
UNKNOWN_ERROR
unknown error occured
OUT_OF_MEMORY
unable to allocate the necessary memory
INVALID_ARG
invalid function argument passed
NOT_INITIALIZED
object not initialized
INVALID_STATE
object is in an invalid state
FILE_ACCESS
File cannot be opened/created.
FILE_FORMAT
Wrong file type.
PARSE_ERROR
Error parsing input (or input file)
IO_ERROR
An I/O error occured (e.g.
read from file failed.)
INVALID_MESH
The mesh is invalid.
NO_PD_STORAGE_MODE
no storage mode chosen within PatchData
NOT_IMPLEMENTED
requested functionality is not (yet) implemented
INTERNAL_ERROR
A bug in Mesquite.
INTERRUPTED
Application or user interrupted operation.
TAG_ALREADY_EXISTS
Attempt to create tag that already exists.
TAG_NOT_FOUND
Specified tag does not exist.
LAST_ERROR_CODE
Definition at line 115 of file src/Misc/MsqError.hpp.
                  {
     NO_ERROR          =  0,
     UNKNOWN_ERROR,
     OUT_OF_MEMORY,
     INVALID_ARG ,
     NOT_INITIALIZED,
     INVALID_STATE,
     FILE_ACCESS,
     FILE_FORMAT,
     PARSE_ERROR,
     IO_ERROR,
     INVALID_MESH,
     NO_PD_STORAGE_MODE,
     NOT_IMPLEMENTED,
     INTERNAL_ERROR,
     INTERRUPTED,
     TAG_ALREADY_EXISTS,
     TAG_NOT_FOUND,
     LAST_ERROR_CODE
   };
Constructor & Destructor Documentation
MsqError () inline
Initialize to cleared state.
Definition at line 145 of file includeLinks/MsqError.hpp.
 : errorCode(NO_ERROR) { }
~MsqError () virtual
Destructor - empty but must declar virtual destrucor if virtual functions.
Definition at line 82 of file Misc/MsqError.cpp.
 {}
MsqError () inline
Initialize to cleared state.
Definition at line 145 of file src/Misc/MsqError.hpp.
 : errorCode(NO_ERROR) { }
virtual ~MsqError () virtual
Destructor - empty but must declar virtual destrucor if virtual functions.
Member Function Documentation
void clear ()
resets error object to non-active state (no error).
Definition at line 150 of file Misc/MsqError.cpp.
References MsqError::errorCode, MsqError::errorMessage, MsqError::NO_ERROR, and MsqError::stackTrace.
Referenced by ParameterSet::generic_add_parameter(), and MeshImpl::read_vtk().
 {
   errorCode = NO_ERROR;
         // MS VC6 doesn't have string::clear()!
   errorMessage.resize(0);
   stackTrace.clear();
 }
void clear ()
resets error object to non-active state (no error).
bool error () const inline
Check if an error has occured.
Definition at line 140 of file includeLinks/MsqError.hpp.
References MsqError::errorCode, and MsqError::NO_ERROR.
Referenced by MsqPrintError::~MsqPrintError().
 { return NO_ERROR != errorCode; }
bool error () const inline
Check if an error has occured.
Definition at line 140 of file src/Misc/MsqError.hpp.
References MsqError::errorCode, and MsqError::NO_ERROR.
 { return NO_ERROR != errorCode; }
ErrorCode error_code () const inline
Get error code.
Definition at line 155 of file includeLinks/MsqError.hpp.
References MsqError::errorCode.
Referenced by Mesquite::operator<<().
 { return errorCode; }
ErrorCode error_code () const inline
Get error code.
Definition at line 155 of file src/Misc/MsqError.hpp.
References MsqError::errorCode.
 { return errorCode; }
const char * error_message () const
Get error message.
Definition at line 45 of file Misc/MsqError.cpp.
References MsqError::errorCode, MsqError::errorMessage, and MsqError::LAST_ERROR_CODE.
Referenced by Mesquite::operator<<().
 {
   static const char* const error_messages[] = {
    "No Error",
    "<unknown>",
    "Out of memory",
    "Invalid argument",
    "Data not initialized",
    "Invalid state",
    "File access error",
    "File format error",
    "Syntax error",
    "I/O error",
    "Invalid mesh",
    "No storage mode for PatchData",
    "Not implemented",
    "Internal error",
    "Interrupted",
    "Duplicate tag name",
    "Tag not found",
    "Invalid Error Code"
   };
     /* If this is ever false, it should be caught by a unit test.
        Do an assert here so the unit test fails.
        This asserts that all error codes have a string in the above list. */
   assert( sizeof(error_messages) == sizeof(char*) * (LAST_ERROR_CODE+1) );
   if (!errorMessage.empty())
     return errorMessage.c_str();
   if (errorCode >= 0 && errorCode < LAST_ERROR_CODE)
     return error_messages[errorCode];
   return error_messages[LAST_ERROR_CODE];
 }
const char* error_message () const
Get error message.
operator bool () const inline
Check if an error has occured.
Definition at line 142 of file src/Misc/MsqError.hpp.
References MsqError::errorCode, and MsqError::NO_ERROR.
 { return NO_ERROR != errorCode; }
operator bool () const inline
Check if an error has occured.
Definition at line 142 of file includeLinks/MsqError.hpp.
References MsqError::errorCode, and MsqError::NO_ERROR.
 { return NO_ERROR != errorCode; }
virtual bool push (const char * function, const char * file, int line) virtual
Add to back-trace of call stack.
Called by MSQ_CHKERR. Must always return true.
bool push (const char * function, const char * file, int line) virtual
Add to back-trace of call stack.
Called by MSQ_CHKERR. Must always return true.
Definition at line 130 of file Misc/MsqError.cpp.
References MsqError::stackTrace.
Referenced by MsqError::Setter::set().
 {
   stackTrace.push_back( Trace(function, file, line) );
   return true;
 }
bool set_error (ErrorCode num, const char * msg = 0) virtual
Initialize the error object with the passed data.
Definition at line 136 of file Misc/MsqError.cpp.
References MsqError::errorCode, MsqError::errorMessage, MsqError::NO_ERROR, and MsqError::stackTrace.
Referenced by MsqError::Setter::set().
 {
   errorCode = num;
   stackTrace.clear();
   if (msg)
     errorMessage = msg;
   else
           // MS VC6 doesn't have string::clear()!
         errorMessage.resize(0);
   return num != NO_ERROR;
 }
virtual bool set_error (ErrorCode num, const char * msg = 0) virtual
Initialize the error object with the passed data.
static Setter setter (MsqError & err, const char * function, const char * file, int line) inline static
Definition at line 213 of file includeLinks/MsqError.hpp.
   { return Setter( err, function, file, line ); }
static Setter setter (MsqError & err, const char * function, const char * file, int line) inline static
Definition at line 213 of file src/Misc/MsqError.hpp.
   { return Setter( err, function, file, line ); }
const StackTrace& stack () const inline
Get stack trace.
Definition at line 176 of file includeLinks/MsqError.hpp.
References MsqError::stackTrace.
Referenced by Mesquite::operator<<().
 { return stackTrace; }
const StackTrace& stack () const inline
Get stack trace.
Definition at line 176 of file src/Misc/MsqError.hpp.
References MsqError::stackTrace.
 { return stackTrace; }
Member Data Documentation
ErrorCode errorCode private
Definition at line 218 of file includeLinks/MsqError.hpp.
Referenced by MsqError::clear(), MsqError::error(), MsqError::error_code(), MsqError::error_message(), MsqError::operator bool(), and MsqError::set_error().
msq_std::string errorMessage private
Definition at line 219 of file includeLinks/MsqError.hpp.
Referenced by MsqError::clear(), MsqError::error_message(), and MsqError::set_error().
StackTrace stackTrace private
Definition at line 220 of file includeLinks/MsqError.hpp.
Referenced by MsqError::clear(), MsqError::push(), MsqError::set_error(), and MsqError::stack().
The documentation for this class was generated from the following files:
includeLinks/MsqError.hpp
Misc/MsqError.cpp