Rocstar: Polyhedron_incremental_builder_3< HDS > Class Template Reference
Polyhedron_incremental_builder_3< HDS > Class Template Reference
#include <Polyhedron_incremental_builder_3.h>
Public Types
typedef HDS Halfedge_data_structure
typedef HDS::Vertex Vertex
typedef HDS::Halfedge Halfedge
typedef HDS::Facet Facet
typedef HDS::Point Point
typedef HDS::Size Size
Public Member Functions
bool error () const
m_verbose (verbose)
hds (h)
~Polyhedron_incremental_builder_3 ()
void begin_surface (Size v, Size f, Size h=0)
void add_vertex (const Point &p)
void begin_facet ()
void add_vertex_to_facet (Size i)
void end_facet ()
void end_surface ()
bool check_unconnected_vertices ()
bool remove_unconnected_vertices (Tag_true)
bool remove_unconnected_vertices (Tag_false)
bool remove_unconnected_vertices ()
void rollback ()
Public Attributes
__pad0__: m_error(false)
Protected Types
typedef
HDS::Supports_vertex_halfedge Supports_vertex_halfedge
typedef HDS::Supports_removal Supports_removal
typedef HDS::Vertex_iterator Vertex_iterator
typedef
Random_access_value_adaptor
< Vertex_iterator, Vertex > Random_access_index
Protected Member Functions
CGAL_assertion_code (int check_protocoll;) void initialize_vertex_to_edge_map(Size
Tag_true void initialize_vertex_to_edge_map (Size n, Tag_false)
void initialize_vertex_to_edge_map (Size n)
void push_back_vertex_to_edge_map (Halfedge *, Tag_true)
void push_back_vertex_to_edge_map (Halfedge *h, Tag_false)
void push_back_vertex_to_edge_map (Halfedge *h)
Halfedge * get_vertex_to_edge_map (int i, Tag_true)
Halfedge * get_vertex_to_edge_map (int i, Tag_false)
Halfedge * get_vertex_to_edge_map (int i)
void set_vertex_to_edge_map (int i, Halfedge *h, Tag_true)
void set_vertex_to_edge_map (int i, Halfedge *h, Tag_false)
void set_vertex_to_edge_map (int i, Halfedge *h)
Halfedge * lookup_hole (Size w)
Size find_vertex (Vertex *v)
Size find_facet (Facet *f)
Halfedge * lookup_halfedge (Size w, Size v)
Halfedge * lookup_hole (Halfedge *e)
Protected Attributes
bool m_error
bool m_verbose
HDS & hds
Size rollback_v
Size rollback_f
Size rollback_h
Size new_vertices
Size new_facets
Size new_halfedges
Facet * current_facet
Random_access_index index_to_vertex_map
std::vector< Halfedge * > vertex_to_edge_map
Halfedge * g1
Halfedge * gprime
Halfedge * h1
Size w1
Size w2
Size v1
bool first_vertex
bool last_vertex
Detailed Description
template<class HDS>
class Polyhedron_incremental_builder_3< HDS >
Definition at line 71 of file Polyhedron_incremental_builder_3.h.
Member Typedef Documentation
typedef HDS::Facet Facet
Definition at line 76 of file Polyhedron_incremental_builder_3.h.
typedef HDS::Halfedge Halfedge
Definition at line 75 of file Polyhedron_incremental_builder_3.h.
typedef HDS Halfedge_data_structure
Definition at line 73 of file Polyhedron_incremental_builder_3.h.
typedef HDS::Point Point
Definition at line 77 of file Polyhedron_incremental_builder_3.h.
typedef Random_access_value_adaptor<Vertex_iterator,Vertex> Random_access_index protected
Definition at line 86 of file Polyhedron_incremental_builder_3.h.
typedef HDS::Size Size
Definition at line 78 of file Polyhedron_incremental_builder_3.h.
typedef HDS::Supports_removal Supports_removal protected
Definition at line 83 of file Polyhedron_incremental_builder_3.h.
typedef HDS::Supports_vertex_halfedge Supports_vertex_halfedge protected
Definition at line 82 of file Polyhedron_incremental_builder_3.h.
typedef HDS::Vertex Vertex
Definition at line 74 of file Polyhedron_incremental_builder_3.h.
typedef HDS::Vertex_iterator Vertex_iterator protected
Definition at line 84 of file Polyhedron_incremental_builder_3.h.
Constructor & Destructor Documentation
~Polyhedron_incremental_builder_3 () inline
Definition at line 189 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion.
{
         CGAL_assertion( check_protocoll == 0);
     }
Member Function Documentation
CGAL_MEDIUM_INLINE void add_vertex (const Point & p)
Definition at line 666 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::hds, Polyhedron_incremental_builder_3< HDS >::index_to_vertex_map, Polyhedron_incremental_builder_3< HDS >::m_error, Polyhedron_incremental_builder_3< HDS >::m_verbose, Halfedge_data_structure_decorator< _HDS >::new_vertex(), Polyhedron_incremental_builder_3< HDS >::new_vertices, Random_access_adaptor< IC >::push_back(), Polyhedron_incremental_builder_3< HDS >::push_back_vertex_to_edge_map(), and Halfedge_data_structure_decorator< _HDS >::set_vertex_halfedge().
{
     CGAL_assertion( check_protocoll == 1);
     if ( hds.size_of_vertices() >= hds.capacity_of_vertices()) {
         Verbose_ostream verr( m_verbose);
         verr << " " << std::endl;
         verr << "Polyhedron_incremental_builder_3<HDS>::" << std::endl;
         verr << "add_vertex(): capacity error: more than " << new_vertices
              << " vertices added." << std::endl;
         m_error = true;
         return;
     }
     Halfedge_data_structure_decorator<HDS> decorator;
     Vertex* v = decorator.new_vertex( hds, p);
     index_to_vertex_map.push_back( Vertex_iterator(v));
     decorator.set_vertex_halfedge( v, 0);
     push_back_vertex_to_edge_map( 0);
     ++new_vertices;
 }
void add_vertex_to_facet (Size i)
Definition at line 765 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::CGAL_assertion_code(), Polyhedron_incremental_builder_3< HDS >::current_facet, Polyhedron_incremental_builder_3< HDS >::end_facet(), Polyhedron_incremental_builder_3< HDS >::find_facet(), Polyhedron_incremental_builder_3< HDS >::first_vertex, Polyhedron_incremental_builder_3< HDS >::g1, Halfedge_data_structure_decorator< _HDS >::get_facet(), Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::gprime, Polyhedron_incremental_builder_3< HDS >::h1, Polyhedron_incremental_builder_3< HDS >::hds, Polyhedron_incremental_builder_3< HDS >::index_to_vertex_map, Halfedge::is_border(), k, Polyhedron_incremental_builder_3< HDS >::last_vertex, Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), Polyhedron_incremental_builder_3< HDS >::lookup_hole(), Polyhedron_incremental_builder_3< HDS >::m_error, Polyhedron_incremental_builder_3< HDS >::m_verbose, Polyhedron_incremental_builder_3< HDS >::new_vertices, Halfedge::next(), Halfedge::opposite(), Halfedge_data_structure_decorator< _HDS >::set_prev(), Polyhedron_incremental_builder_3< HDS >::set_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::v1, Polyhedron_incremental_builder_3< HDS >::w1, and Polyhedron_incremental_builder_3< HDS >::w2.
Referenced by Polyhedron_incremental_builder_3< HDS >::end_facet().
{
 #else
 add_vertex_to_facet( std::size_t v2) {
 #endif
     if ( m_error)
         return;
     Verbose_ostream verr( m_verbose);
     CGAL_assertion( check_protocoll == 2);
     if ( v2 >= new_vertices) {
         verr << " " << std::endl;
         verr << "Polyhedron_incremental_builder_3<HDS>::" << std::endl;
         verr << "add_vertex_to_facet(): vertex index " << v2
              << " is out-of-range [0," << new_vertices-1 << "]."
              << std::endl;
         m_error = true;
         return;
     }
     Halfedge_data_structure_decorator<HDS> decorator;
     if ( first_vertex) {
         CGAL_assertion( ! last_vertex);
         w1 = v2;
         first_vertex = false;
         return;
     }
     if ( g1 == 0) {
         CGAL_assertion( ! last_vertex);
         gprime  = lookup_halfedge( w1, v2);
         if ( m_error)
             return;
         h1 = g1 = gprime->next();
         v1 = w2 = v2;
         return;
     }
     // g1, h1, v1, w1, w2 are set. Insert halfedge.
     // Lookup v1-->v2
     Halfedge* hprime;
     if ( last_vertex)
         hprime = gprime;
     else {
         hprime = lookup_halfedge( v1, v2);
         if ( m_error)
             return;
     }
     Halfedge* h2 = hprime->next();
     CGAL_assertion( ! last_vertex || h2 == g1);
     Halfedge* prev = h1->next();
     h1->set_next( h2);
     decorator.set_prev( h2, h1);
     if ( get_vertex_to_edge_map( v1) == 0) {                  // case 1:
         h2->opposite()->set_next( h1->opposite());
         decorator.set_prev( h1->opposite(), h2->opposite());
     } else {                                                  // case 2:
         bool b1 = h1->opposite()->is_border();
         bool b2 = h2->opposite()->is_border();
         if ( b1 && b2) {
             Halfedge* hole = lookup_hole( v1);
             if ( m_error)
                 return;
             CGAL_assertion( hole != NULL);
             h2->opposite()->set_next( hole->next());
             decorator.set_prev( hole->next(), h2->opposite());
             hole->set_next( h1->opposite());
             decorator.set_prev( h1->opposite(), hole);
         } else if ( b2) {                                     // case 2.b:
             CGAL_assertion( prev->is_border());
             h2->opposite()->set_next( prev);
             decorator.set_prev( prev, h2->opposite());
         } else if ( b1) {                                     // case 2.c:
             CGAL_assertion( hprime->is_border());
             hprime->set_next( h1->opposite());
             decorator.set_prev( h1->opposite(), hprime);
         } else if ( h2->opposite()->next() == h1->opposite()) {// case 2.d:
             // f1 == f2
             CGAL_assertion( decorator.get_facet( h1->opposite()) ==
                        decorator.get_facet( h2->opposite()));
         } else {                                              // case 2.e:
             if ( prev == h2) {                                // case _i:
                 // nothing to be done, hole is closed.
             } else {                                          // case _ii:
                 CGAL_assertion( prev->is_border());
                 CGAL_assertion( hprime->is_border());
                 hprime->set_next( prev);
                 decorator.set_prev( prev, hprime);
                 // Check whether the halfedges around v1 are connected.
                 // It is sufficient to check it for h1 to prev.
                 // Assert loop termination.
                 CGAL_assertion_code( std::size_t k = 0;)
                 // Look for a hole in the facet complex starting at h1.
                 Halfedge* hole = 0;
                 Halfedge* e    = h1;
                 do {
                     if ( e->is_border())
                         hole = e;
                     e = e->next()->opposite();
                     CGAL_assertion( k++ < hds.size_of_halfedges());
                 } while ( e->next() != prev && e != h1);
                 if ( e == h1) {
                     // disconnected facet complexes
                     if ( hole) {
                         // The complex can be connected with
                         // the hole at hprime.
                         hprime->set_next( hole->next());
                         decorator.set_prev( hole->next(), hprime);
                         hole->set_next( prev);
                         decorator.set_prev( prev, hole);
                     } else {
                         verr << " " << std::endl;
                         verr << "Polyhedron_incremental_builder_3<"
                                 "HDS>::" << std::endl;
                         verr << "add_vertex_to_facet(): input error: "
                                 "disconnected facet complexes at vertex "
                              << v1 << ":" << std::endl;
                         if ( current_facet && m_verbose) {
                             verr << "           involved facets are:";
                             do {
                                 if ( ! e->is_border())
                                     verr << " " << find_facet(
                                                 decorator.get_facet(e));
                                 e = e->next()->opposite();
                             } while ( e != h1);
                             verr << " (closed cycle) and";
                             e = hprime;
                             do {
                                 if ( ! e->is_border())
                                     verr << " " << find_facet(
                                                 decorator.get_facet(e));
                             } while ( e != hprime);
                             verr << "." << std::endl;
                         }
                         m_error = true;
                         return;
                     }
                 }
             }
         }
     }
     if( h1->vertex() == &(index_to_vertex_map[v1]))
         set_vertex_to_edge_map( v1, h1);
     CGAL_assertion( h1->vertex() == &(index_to_vertex_map[v1]));
     h1 = h2;
     v1 = v2;
 }
CGAL_MEDIUM_INLINE void begin_facet ()
Definition at line 738 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::CGAL_assertion_code(), Polyhedron_incremental_builder_3< HDS >::current_facet, Polyhedron_incremental_builder_3< HDS >::first_vertex, Polyhedron_incremental_builder_3< HDS >::g1, Polyhedron_incremental_builder_3< HDS >::hds, Polyhedron_incremental_builder_3< HDS >::last_vertex, Polyhedron_incremental_builder_3< HDS >::m_error, Polyhedron_incremental_builder_3< HDS >::m_verbose, Halfedge_data_structure_decorator< _HDS >::new_facet(), and Polyhedron_incremental_builder_3< HDS >::new_vertices.
Referenced by Polyhedron_incremental_builder_3< HDS >::begin_surface().
               {
     if ( m_error)
         return;
     CGAL_assertion( check_protocoll == 1);
     CGAL_assertion_code( check_protocoll = 2;)
     if ( hds.size_of_facets() >= hds.capacity_of_facets()) {
         Verbose_ostream verr( m_verbose);
         verr << " " << std::endl;
         verr << "Polyhedron_incremental_builder_3<HDS>::" << std::endl;
         verr << "begin_facet(): capacity error: more than " << new_vertices
              << " facets added." << std::endl;
         m_error = true;
         return;
     }
     // initialize all status variables.
     first_vertex = true;  // denotes 'no vertex yet'
     g1 =  0;  // denotes 'no halfedge yet'
     last_vertex = false;
     Halfedge_data_structure_decorator<HDS> decorator;
     current_facet = decorator.new_facet( hds);
 }
CGAL_MEDIUM_INLINE void begin_surface (Size v, Size f, Size h = 0)
Definition at line 707 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::begin_facet(), CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::CGAL_assertion_code(), CGAL_MEDIUM_INLINE, Polyhedron_incremental_builder_3< HDS >::hds, Polyhedron_incremental_builder_3< HDS >::index_to_vertex_map, Polyhedron_incremental_builder_3< HDS >::initialize_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::m_error, Polyhedron_incremental_builder_3< HDS >::new_facets, Polyhedron_incremental_builder_3< HDS >::new_halfedges, Polyhedron_incremental_builder_3< HDS >::new_vertices, Random_access_adaptor< IC >::reserve(), Polyhedron_incremental_builder_3< HDS >::rollback_f, Polyhedron_incremental_builder_3< HDS >::rollback_h, Polyhedron_incremental_builder_3< HDS >::rollback_v, and v.
{
 #else
 begin_surface( std::size_t v, std::size_t f, std::size_t h) {
 #endif
     CGAL_assertion( check_protocoll == 0);
     CGAL_assertion_code( check_protocoll = 1;)
     CGAL_assertion( ! m_error);
     new_vertices  = 0;
     new_facets    = 0;
     new_halfedges = 0;
     rollback_v = hds.size_of_vertices();
     rollback_f = hds.size_of_facets();
     rollback_h = hds.size_of_halfedges();
     if ( h == 0) {
         // Use the Eulerian equation for connected planar graphs. We do
         // not know the number of facets that are holes and we do not
         // know the genus of the surface. So we add 12 and a factor of
         // 5 percent.
         h = int((v + f - 2 + 12) * 2.1);
     }
     hds.reserve( hds.size_of_vertices()  + v,
                  hds.size_of_halfedges() + h,
                  hds.size_of_facets()    + f);
     index_to_vertex_map = Random_access_index( hds.vertices_end());
     index_to_vertex_map.reserve(v);
     initialize_vertex_to_edge_map( v);
 }
CGAL_assertion_code (int check_protocoll;) protected
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::begin_facet(), Polyhedron_incremental_builder_3< HDS >::begin_surface(), Polyhedron_incremental_builder_3< HDS >::end_facet(), Polyhedron_incremental_builder_3< HDS >::end_surface(), Polyhedron_incremental_builder_3< HDS >::hds(), and Polyhedron_incremental_builder_3< HDS >::rollback().
bool check_unconnected_vertices ()
Definition at line 944 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map(), i, Polyhedron_incremental_builder_3< HDS >::m_error, Polyhedron_incremental_builder_3< HDS >::m_verbose, and Polyhedron_incremental_builder_3< HDS >::new_vertices.
Referenced by Polyhedron_incremental_builder_3< HDS >::remove_unconnected_vertices().
{
     if ( m_error)
         return false;
     bool unconnected = false;
     Verbose_ostream verr( m_verbose);
     for( std::size_t i = 0; i < new_vertices; i++) {
         if( get_vertex_to_edge_map( i) == NULL) {
             verr << "Polyhedron_incremental_builder_3<HDS>::\n"
                  << "check_unconnected_vertices( verb = true): "
                  << "vertex " << i << " is unconnected." << std::endl;
             unconnected = true;
         }
     }
     return unconnected;
 }
void end_facet ()
Definition at line 914 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::CGAL_assertion_code(), Polyhedron_incremental_builder_3< HDS >::current_facet, Polyhedron_incremental_builder_3< HDS >::first_vertex, Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::last_vertex, Polyhedron_incremental_builder_3< HDS >::m_error, Polyhedron_incremental_builder_3< HDS >::new_facets, Halfedge_data_structure_decorator< _HDS >::set_facet_halfedge(), Polyhedron_incremental_builder_3< HDS >::w1, and Polyhedron_incremental_builder_3< HDS >::w2.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet().
             {
     if ( m_error)
         return;
     CGAL_assertion( check_protocoll == 2);
     CGAL_assertion( ! first_vertex);
     // cleanup all static status variables
     add_vertex_to_facet( w1);
     last_vertex = true;
     add_vertex_to_facet( w2);
     CGAL_assertion( check_protocoll == 2);
     CGAL_assertion_code( check_protocoll = 1;)
     Halfedge_data_structure_decorator<HDS> decorator;
     decorator.set_facet_halfedge( current_facet,
                                   get_vertex_to_edge_map(w1));
     ++new_facets;
 }
CGAL_MEDIUM_INLINE void end_surface ()
Definition at line 934 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::CGAL_assertion_code(), and Polyhedron_incremental_builder_3< HDS >::m_error.
               {
     if ( m_error)
         return;
     CGAL_assertion( check_protocoll == 1);
     CGAL_assertion_code( check_protocoll = 0;)
 }
bool error () const inline
Definition at line 178 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::m_error.
Referenced by moderror::errorstop(), get_jacobien(), implicit_v3d8_mass(), implicit_v3d8_mass_consistent(), implicit_v3d8_me_k(), locthermcap_v3d8(), locthermstiff_v3d8(), rflo_modextrapolation::rflo_extrapregdummynode(), rflo_modextrapolation::rflo_extrapreglastnode(), rflo_modfinitedifference::rflo_findiffcompi(), rflo_modfinitedifference::rflo_findiffcompii(), rflo_modfinitedifference::rflo_findiffcompiis(), rflo_modfinitedifference::rflo_findiffcompis(), rflo_modfinitedifference::rflo_findiffcompj(), rflo_modfinitedifference::rflo_findiffcompjj(), rflo_modfinitedifference::rflo_findiffcompjjs(), rflo_modfinitedifference::rflo_findiffcompjs(), rflo_modfinitedifference::rflo_findiffcompk(), rflo_modfinitedifference::rflo_findiffcompkk(), v3d8_mass(), and v3d8_me().
 { return m_error; }
CGAL_LARGE_INLINE HDS::Size find_facet (Facet * f) protected
Definition at line 513 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::hds, n, and Polyhedron_incremental_builder_3< HDS >::new_facets.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), and Polyhedron_incremental_builder_3< HDS >::lookup_hole().
                       {
     if ( ! f)
         return 0;
     Size n = 0;
     typename HDS::Facet_iterator it = hds.facets_begin();
     while ( &(*it) != f) {
         CGAL_assertion( it != hds.facets_end());
         ++n;
         ++it;
     }
     n = n - ( hds.size_of_facets() - new_facets);
     return n;
 }
CGAL_LARGE_INLINE HDS::Size find_vertex (Vertex * v) protected
Definition at line 492 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::hds, n, and Polyhedron_incremental_builder_3< HDS >::new_vertices.
Referenced by Polyhedron_incremental_builder_3< HDS >::lookup_hole().
{
     if ( ! v)
         return 0;
     Size n = 0;
     typename HDS::Vertex_iterator it = hds.vertices_begin();
     while ( &(*it) != v) {
         CGAL_assertion( it != hds.vertices_end());
         ++n;
         ++it;
     }
     n = n - ( hds.size_of_vertices() - new_vertices);
     return n;
 }
Halfedge* get_vertex_to_edge_map (int i, Tag_true) inline protected
Definition at line 131 of file Polyhedron_incremental_builder_3.h.
References i, and Polyhedron_incremental_builder_3< HDS >::index_to_vertex_map.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::check_unconnected_vertices(), Polyhedron_incremental_builder_3< HDS >::end_facet(), Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), Polyhedron_incremental_builder_3< HDS >::lookup_hole(), and Polyhedron_incremental_builder_3< HDS >::remove_unconnected_vertices().
{
         // Use the halfedge pointer within the vertex.
         return index_to_vertex_map[i].halfedge();
     }
Halfedge* get_vertex_to_edge_map (int i, Tag_false) inline protected
Definition at line 135 of file Polyhedron_incremental_builder_3.h.
References i, and Polyhedron_incremental_builder_3< HDS >::vertex_to_edge_map.
{
         // Use the self-managed array vertex_to_edge_map.
         return vertex_to_edge_map[i];
     }
Halfedge* get_vertex_to_edge_map (int i) inline protected
Definition at line 139 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map().
{
         return get_vertex_to_edge_map( i, Supports_vertex_halfedge());
     }
hds (h) inline
Definition at line 185 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::CGAL_assertion_code().
       : m_error( false), m_verbose( verbose), hds(h) {
         CGAL_assertion_code(check_protocoll = 0;)
     }
Tag_true void initialize_vertex_to_edge_map (Size n, Tag_false) inline protected
Definition at line 117 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::vertex_to_edge_map.
Referenced by Polyhedron_incremental_builder_3< HDS >::begin_surface(), and Polyhedron_incremental_builder_3< HDS >::initialize_vertex_to_edge_map().
{
         vertex_to_edge_map = std::vector<Halfedge*>();
         vertex_to_edge_map.reserve(n);
     }
void initialize_vertex_to_edge_map (Size n) inline protected
Definition at line 121 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::initialize_vertex_to_edge_map().
{
         initialize_vertex_to_edge_map( n, Supports_vertex_halfedge());
     }
CGAL_LARGE_INLINE HDS::Halfedge * lookup_halfedge (Size w, Size v) protected
Definition at line 534 of file Polyhedron_incremental_builder_3.h.
References Assert_compile_time_tag(), CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::current_facet, Polyhedron_incremental_builder_3< HDS >::find_facet(), Halfedge_data_structure_decorator< _HDS >::get_facet(), Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::hds, Polyhedron_incremental_builder_3< HDS >::index_to_vertex_map, Halfedge::is_border(), Polyhedron_incremental_builder_3< HDS >::last_vertex, Polyhedron_incremental_builder_3< HDS >::m_error, Polyhedron_incremental_builder_3< HDS >::m_verbose, Polyhedron_incremental_builder_3< HDS >::new_facets, Polyhedron_incremental_builder_3< HDS >::new_halfedges, Polyhedron_incremental_builder_3< HDS >::new_vertices, Halfedge::next(), Halfedge::opposite(), Halfedge_data_structure_decorator< _HDS >::set_facet(), Halfedge_data_structure_decorator< _HDS >::set_prev(), and v.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet().
{
     typedef typename HDS::Supports_halfedge_vertex
         Supports_halfedge_vertex;
     Assert_compile_time_tag( Supports_halfedge_vertex(), Tag_true());
     CGAL_assertion( w < new_vertices);
     CGAL_assertion( v < new_vertices);
     CGAL_assertion( ! last_vertex);
     Verbose_ostream verr( m_verbose);
     Halfedge_data_structure_decorator<HDS> decorator;
     Halfedge* e = get_vertex_to_edge_map( w);
     if ( e) {
         CGAL_assertion( e->vertex() == &(index_to_vertex_map[w]));
         // check that the facet has no self intersections
         if ( current_facet && current_facet == decorator.get_facet(e)) {
             verr << " " << std::endl;
             verr << "Polyhedron_incremental_builder_3<HDS>::"
                  << std::endl;
             verr << "lookup_halfedge(): input error: facet "
                  << new_facets << " has a self intersection at vertex "
                  << w << "." << std::endl;
             m_error = true;
             return 0;
         }
         Halfedge* start_edge = e;
         do {
             if ( e->next()->vertex() == &(index_to_vertex_map[v]) ) {
                 if ( ! e->next()->is_border()) {
                     verr << " " << std::endl;
                     verr << "Polyhedron_incremental_builder_3"
                             "<HDS>::" << std::endl;
                     verr << "lookup_halfedge(): input error: facet "
                          << new_facets << " shares a halfedge from "
                             "vertex " <<  w << " to vertex " << v
                          << " with";
                     if ( current_facet)
                         verr << " facet "
                              << find_facet( decorator.get_facet(e->next()))
                              << '.' << std::endl;
                     else
                         verr << " another facet." << std::endl;
                     m_error = true;
                     return 0;
                 }
                 CGAL_assertion( ! e->next()->opposite()->is_border());
                 if ( current_facet &&
                      current_facet ==
                      decorator.get_facet( e->next()->opposite())) {
                     verr << " " << std::endl;
                     verr << "Polyhedron_incremental_builder_3"
                             "<HDS>::" << std::endl;
                     verr << "lookup_halfedge(): input error: facet "
                          << new_facets << " has a self intersection "
                             "at the halfedge from vertex " << w
                          << " to vertex " << v << "." << std::endl;
                     m_error = true;
                     return 0;
                 }
                 decorator.set_facet( e->next(), current_facet);
                 return e;
             }
             e = e->next()->opposite();
         } while ( e != start_edge);
     }
     // create a new halfedge
     if ( hds.size_of_halfedges() >= hds.capacity_of_halfedges()) {
         verr << " " << std::endl;
         verr << "Polyhedron_incremental_builder_3<HDS>::" << std::endl;
         verr << "lookup_halfedge(): capacity error: more than "
              << new_halfedges << " halfedges added while creating facet"
              << new_facets << '.' << std::endl;
         m_error = true;
         return 0;
     }
     e = hds.new_edge();
     new_halfedges++;
     new_halfedges++;
     decorator.set_facet( e, current_facet);
     e->set_vertex( &(index_to_vertex_map[v]));
     e->set_next( 0);
     decorator.set_prev( e, e->opposite());
     e = e->opposite();
     e->set_vertex( &(index_to_vertex_map[w]));
     e->set_next( e->opposite());
     return e;
 }
Halfedge* lookup_hole (Size w) inline protected
Definition at line 251 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map(), and Polyhedron_incremental_builder_3< HDS >::new_vertices.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet().
{
         CGAL_assertion( w < new_vertices);
         return lookup_hole( get_vertex_to_edge_map( w));
     }
CGAL_LARGE_INLINE HDS::Halfedge * lookup_hole (Halfedge * e) protected
Definition at line 627 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::current_facet, Polyhedron_incremental_builder_3< HDS >::find_facet(), Polyhedron_incremental_builder_3< HDS >::find_vertex(), Halfedge_data_structure_decorator< _HDS >::get_facet(), Halfedge::is_border(), Polyhedron_incremental_builder_3< HDS >::m_error, Polyhedron_incremental_builder_3< HDS >::m_verbose, Polyhedron_incremental_builder_3< HDS >::new_facets, Halfedge::next(), and Halfedge::opposite().
{
     CGAL_assertion( e != NULL);
     Halfedge_data_structure_decorator<HDS> decorator;
     Halfedge* start_edge = e;
     do {
         if ( e->next()->is_border()) {
             return e;
         }
         e = e->next()->opposite();
     } while ( e != start_edge);
     Verbose_ostream verr( m_verbose);
     verr << " " << std::endl;
     verr << "Polyhedron_incremental_builder_3<HDS>::" << std::endl;
     verr << "lookup_hole(): input error: at vertex "
         << find_vertex( e->vertex())
         << " a closed surface already exists and facet "
         << new_facets << " is nonetheless adjacent." << std::endl;
     if ( current_facet) {
         verr << "             The closed cycle of facets is:";
         do {
             if ( ! e->is_border())
                 verr << " " << find_facet( decorator.get_facet(e));
             e = e->next()->opposite();
         } while ( e != start_edge);
         verr << '.' << std::endl;
     }
     m_error = true;
     return 0;
 }
m_verbose (verbose)
void push_back_vertex_to_edge_map (Halfedge * , Tag_true) inline protected
Definition at line 124 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex(), and Polyhedron_incremental_builder_3< HDS >::push_back_vertex_to_edge_map().
 {}
void push_back_vertex_to_edge_map (Halfedge * h, Tag_false) inline protected
Definition at line 125 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::vertex_to_edge_map.
{
         vertex_to_edge_map.push_back(h);
     }
void push_back_vertex_to_edge_map (Halfedge * h) inline protected
Definition at line 128 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::push_back_vertex_to_edge_map().
{
         push_back_vertex_to_edge_map( h, Supports_vertex_halfedge());
     }
bool remove_unconnected_vertices (Tag_true)
Definition at line 963 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::hds, i, Polyhedron_incremental_builder_3< HDS >::index_to_vertex_map, Polyhedron_incremental_builder_3< HDS >::m_error, and Polyhedron_incremental_builder_3< HDS >::new_vertices.
{
     if ( m_error)
         return true;
     for( std::size_t i = 0; i < new_vertices; i++) {
         if( get_vertex_to_edge_map( i) == NULL) {
             hds.delete_vertex( &index_to_vertex_map[i]);
         }
     }
     return true;
 }
bool remove_unconnected_vertices (Tag_false) inline
Definition at line 239 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::check_unconnected_vertices().
{
         return ! check_unconnected_vertices();
     }
bool remove_unconnected_vertices () inline
Definition at line 242 of file Polyhedron_incremental_builder_3.h.
{
         // returns `true' if all unconnected vertices could be removed
         // succesfully.
         return remove_unconnected_vertices( Supports_removal());
     }
void rollback ()
Definition at line 688 of file Polyhedron_incremental_builder_3.h.
References CGAL_assertion, Polyhedron_incremental_builder_3< HDS >::CGAL_assertion_code(), CGAL_MEDIUM_INLINE, Polyhedron_incremental_builder_3< HDS >::hds, Polyhedron_incremental_builder_3< HDS >::m_error, Polyhedron_incremental_builder_3< HDS >::rollback_f, Polyhedron_incremental_builder_3< HDS >::rollback_h, and Polyhedron_incremental_builder_3< HDS >::rollback_v.
            {
     CGAL_assertion( rollback_v <= hds.size_of_vertices());
     CGAL_assertion( rollback_h <= hds.size_of_halfedges());
     CGAL_assertion( rollback_f <= hds.size_of_facets());
     while ( rollback_v != hds.size_of_vertices())
         hds.vertex_pop_back();
     CGAL_assertion((( hds.size_of_halfedges() - rollback_h) & 1) == 0);
     while ( rollback_h != hds.size_of_halfedges())
         hds.edge_pop_back();
     while ( rollback_f != hds.size_of_facets())
         hds.facet_pop_back();
     m_error = false;
     CGAL_assertion_code( check_protocoll = 0;)
 }
void set_vertex_to_edge_map (int i, Halfedge * h, Tag_true) inline protected
Definition at line 142 of file Polyhedron_incremental_builder_3.h.
References i, and Polyhedron_incremental_builder_3< HDS >::index_to_vertex_map.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), and Polyhedron_incremental_builder_3< HDS >::set_vertex_to_edge_map().
{
         // Use the halfedge pointer within the vertex.
         index_to_vertex_map[i].set_halfedge(h);
     }
void set_vertex_to_edge_map (int i, Halfedge * h, Tag_false) inline protected
Definition at line 146 of file Polyhedron_incremental_builder_3.h.
References i, and Polyhedron_incremental_builder_3< HDS >::vertex_to_edge_map.
{
         // Use the self-managed array vertex_to_edge_map.
         vertex_to_edge_map[i] = h;
     }
void set_vertex_to_edge_map (int i, Halfedge * h) inline protected
Definition at line 150 of file Polyhedron_incremental_builder_3.h.
References Polyhedron_incremental_builder_3< HDS >::set_vertex_to_edge_map().
{
         set_vertex_to_edge_map( i, h, Supports_vertex_halfedge());
     }
Member Data Documentation
__pad0__
Definition at line 185 of file Polyhedron_incremental_builder_3.h.
Facet* current_facet protected
Definition at line 97 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::begin_facet(), Polyhedron_incremental_builder_3< HDS >::end_facet(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), and Polyhedron_incremental_builder_3< HDS >::lookup_hole().
bool first_vertex protected
Definition at line 107 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::begin_facet(), and Polyhedron_incremental_builder_3< HDS >::end_facet().
Halfedge* g1 protected
Definition at line 101 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), and Polyhedron_incremental_builder_3< HDS >::begin_facet().
Halfedge* gprime protected
Definition at line 102 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet().
Halfedge* h1 protected
Definition at line 103 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet().
HDS& hds protected
Definition at line 90 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex(), Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::begin_facet(), Polyhedron_incremental_builder_3< HDS >::begin_surface(), Polyhedron_incremental_builder_3< HDS >::find_facet(), Polyhedron_incremental_builder_3< HDS >::find_vertex(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), Polyhedron_incremental_builder_3< HDS >::remove_unconnected_vertices(), and Polyhedron_incremental_builder_3< HDS >::rollback().
Random_access_index index_to_vertex_map protected
Definition at line 98 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex(), Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::begin_surface(), Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), Polyhedron_incremental_builder_3< HDS >::remove_unconnected_vertices(), and Polyhedron_incremental_builder_3< HDS >::set_vertex_to_edge_map().
bool last_vertex protected
Definition at line 108 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::begin_facet(), Polyhedron_incremental_builder_3< HDS >::end_facet(), and Polyhedron_incremental_builder_3< HDS >::lookup_halfedge().
bool m_error protected
Definition at line 88 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex(), Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::begin_facet(), Polyhedron_incremental_builder_3< HDS >::begin_surface(), Polyhedron_incremental_builder_3< HDS >::check_unconnected_vertices(), Polyhedron_incremental_builder_3< HDS >::end_facet(), Polyhedron_incremental_builder_3< HDS >::end_surface(), Polyhedron_incremental_builder_3< HDS >::error(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), Polyhedron_incremental_builder_3< HDS >::lookup_hole(), Polyhedron_incremental_builder_3< HDS >::remove_unconnected_vertices(), and Polyhedron_incremental_builder_3< HDS >::rollback().
bool m_verbose protected
Definition at line 89 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex(), Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::begin_facet(), Polyhedron_incremental_builder_3< HDS >::check_unconnected_vertices(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), and Polyhedron_incremental_builder_3< HDS >::lookup_hole().
Size new_facets protected
Definition at line 95 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::begin_surface(), Polyhedron_incremental_builder_3< HDS >::end_facet(), Polyhedron_incremental_builder_3< HDS >::find_facet(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), and Polyhedron_incremental_builder_3< HDS >::lookup_hole().
Size new_halfedges protected
Definition at line 96 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::begin_surface(), and Polyhedron_incremental_builder_3< HDS >::lookup_halfedge().
Size new_vertices protected
Definition at line 94 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex(), Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), Polyhedron_incremental_builder_3< HDS >::begin_facet(), Polyhedron_incremental_builder_3< HDS >::begin_surface(), Polyhedron_incremental_builder_3< HDS >::check_unconnected_vertices(), Polyhedron_incremental_builder_3< HDS >::find_vertex(), Polyhedron_incremental_builder_3< HDS >::lookup_halfedge(), Polyhedron_incremental_builder_3< HDS >::lookup_hole(), and Polyhedron_incremental_builder_3< HDS >::remove_unconnected_vertices().
Size rollback_f protected
Definition at line 92 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::begin_surface(), and Polyhedron_incremental_builder_3< HDS >::rollback().
Size rollback_h protected
Definition at line 93 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::begin_surface(), and Polyhedron_incremental_builder_3< HDS >::rollback().
Size rollback_v protected
Definition at line 91 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::begin_surface(), and Polyhedron_incremental_builder_3< HDS >::rollback().
Size v1 protected
Definition at line 106 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet().
std::vector<Halfedge*> vertex_to_edge_map protected
Definition at line 99 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::get_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::initialize_vertex_to_edge_map(), Polyhedron_incremental_builder_3< HDS >::push_back_vertex_to_edge_map(), and Polyhedron_incremental_builder_3< HDS >::set_vertex_to_edge_map().
Size w1 protected
Definition at line 104 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), and Polyhedron_incremental_builder_3< HDS >::end_facet().
Size w2 protected
Definition at line 105 of file Polyhedron_incremental_builder_3.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex_to_facet(), and Polyhedron_incremental_builder_3< HDS >::end_facet().
The documentation for this class was generated from the following file:
Polyhedron_incremental_builder_3.h