Rocstar: C3Facet Class Reference
C3Facet Class Reference
#include <GeoPrimitives.H>
Public Member Functions
C3Facet ()
C3Facet (const C3Point *P1, const C3Point *P2, const C3Point *P3)
C3Facet (const C3Point *P1, const C3Point *P2, const C3Point *P3, const C3Point *P4)
C3Facet (const C3Point &P1, const C3Point &P2, const C3Point &P3)
C3Facet (const C3Point &P1, const C3Point &P2, const C3Point &P3, const C3Point &P4)
C3Facet (const std::vector< const C3Point * > &v)
C3Facet (const C3Facet &face)
C3Vector Normal () const
C3Point Centroid () const
C3Facet & operator= (const C3Facet &face)
bool operator== (const C3Facet &face) const
Private Member Functions
C3Point * _copycreate_point (const C3Point &p)
C3Point * _create_point ()
Private Attributes
bool _mydata
Detailed Description
Definition at line 1604 of file GeoPrimitives.H.
Constructor & Destructor Documentation
C3Facet () inline
Definition at line 1609 of file GeoPrimitives.H.
References C3Facet::_mydata.
     {
       _mydata = false;
     };
C3Facet (const C3Point * P1, const C3Point * P2, const C3Point * P3) inline
Definition at line 1613 of file GeoPrimitives.H.
References C3Facet::_mydata.
     {
       _mydata = false;
       this->resize(3);
       (*this)[0] = P1;
       (*this)[1] = P2;
       (*this)[2] = P3;
     };
C3Facet (const C3Point * P1, const C3Point * P2, const C3Point * P3, const C3Point * P4) inline
Definition at line 1621 of file GeoPrimitives.H.
References C3Facet::_mydata.
     {
       _mydata = false;
       this->resize(4);
       (*this)[0] = P1;
       (*this)[1] = P2;
       (*this)[2] = P3;
       (*this)[3] = P4;
     };
C3Facet (const C3Point & P1, const C3Point & P2, const C3Point & P3) inline
Definition at line 1630 of file GeoPrimitives.H.
References C3Facet::_copycreate_point(), and C3Facet::_mydata.
     {
       _mydata = true;
       this->resize(3);
       (*this)[0] = _copycreate_point(P1);
       (*this)[1] = _copycreate_point(P2);
       (*this)[2] = _copycreate_point(P3);
     };
C3Facet (const C3Point & P1, const C3Point & P2, const C3Point & P3, const C3Point & P4) inline
Definition at line 1638 of file GeoPrimitives.H.
References C3Facet::_copycreate_point(), and C3Facet::_mydata.
     {
       _mydata = true;
       this->resize(4);
       (*this)[0] = _copycreate_point(P1);
       (*this)[1] = _copycreate_point(P2);
       (*this)[2] = _copycreate_point(P3);
       (*this)[3] = _copycreate_point(P4);
     };
C3Facet (const std::vector< const C3Point * > & v) inline
Definition at line 1648 of file GeoPrimitives.H.
References pi.
     {
       std::vector<const C3Point *>::const_iterator pi = v.begin();
       while(pi != v.end())
         this->push_back(*pi++);
     };
C3Facet (const C3Facet & face) inline
Definition at line 1660 of file GeoPrimitives.H.
     {
       C3Facet::const_iterator fi = face.begin();
       while(fi != face.end())
         this->push_back(*fi++);
     };
Member Function Documentation
C3Point* _copycreate_point (const C3Point & p) inline private
Definition at line 1714 of file GeoPrimitives.H.
References C3Vector::Copy().
Referenced by C3Facet::C3Facet().
     {
       C3Point *rp = new C3Point;
       rp->Copy(p);
       return(rp);
     };
C3Point* _create_point () inline private
Definition at line 1720 of file GeoPrimitives.H.
     {
       C3Point *rp = new C3Point;
       return(rp);
     };
C3Point Centroid () const inline
Definition at line 1672 of file GeoPrimitives.H.
References GeoPrim::C3Centroid().
Referenced by Mesh::GenericElement::Inverted(), and Mesh::GenericElement::ShapeOK().
     {
       return(C3Centroid(*this));
     };
C3Vector Normal () const inline
Definition at line 1666 of file GeoPrimitives.H.
Referenced by Mesh::GenericElement::Inverted(), and Mesh::GenericElement::ShapeOK().
     {
       C3Vector v1(*((*this)[0]),*((*this)[1]));
       C3Vector v2(*((*this)[0]),*((*this)[2]));
       return(.5*(v1%v2));
     };
C3Facet& operator= (const C3Facet & face) inline
Definition at line 1676 of file GeoPrimitives.H.
     {
       this->clear();
       C3Facet::const_iterator fi = face.begin();
       while(fi != face.end())
         this->push_back(*fi++);
       return(*this);
     };
bool operator== (const C3Facet & face) const inline
Definition at line 1684 of file GeoPrimitives.H.
     {
       C3Facet::const_iterator li = this->begin();
       C3Facet::const_iterator fi = face.begin();
       if(this->size() != face.size()) return false;
       while(li != this->end())
         if(!(*(*li++) == *(*fi++)))
           return(false);
       return(true);
     };
Member Data Documentation
bool _mydata private
Definition at line 1607 of file GeoPrimitives.H.
Referenced by C3Facet::C3Facet().
The documentation for this class was generated from the following file:
GeoPrimitives.H