Rocstar: rflu_modroeflux Module Reference
rflu_modroeflux Module Reference
Public Member Functions
subroutine, public rflu_roe_computeflux (pRegion, fluxPart)
subroutine, public rflu_roe_computefluxc1 (pRegion)
subroutine, public rflu_roe_computefluxc2_tcp (pRegion)
subroutine, public rflu_roe_computefluxd1_tcp (pRegion)
subroutine, public rflu_roe_computefluxd2_tcp (pRegion)
subroutine, public rflu_roe_computeflux1_gl (pRegion)
subroutine, public rflu_roe_computeflux1_tcp (pRegion)
subroutine, public rflu_roe_computeflux2_gl (pRegion)
subroutine, public rflu_roe_computeflux2_tcp (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRoeFlux.F90,v $ $Revision: 1.10 $'
Detailed Description
Definition at line 39 of file RFLU_ModRoeFlux.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_roe_computeflux (type(t_region), pointer pRegion, integer, intent(in) fluxPart)
Definition at line 103 of file RFLU_ModRoeFlux.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_roe_computeflux1_gl(), rflu_roe_computeflux1_tcp(), rflu_roe_computeflux2_gl(), rflu_roe_computeflux2_tcp(), rflu_roe_computefluxc1(), rflu_roe_computefluxc2_tcp(), rflu_roe_computefluxd1_tcp(), and rflu_roe_computefluxd2_tcp().
Referenced by rflu_computefluxinv().
subroutine, public rflu_roe_computeflux1_gl (type(t_region), pointer pRegion)
Definition at line 1263 of file RFLU_ModRoeFlux.F90.
References moderror::deregisterfunction(), rflu_modentropyfixes::entropyfixhartenhyman(), mixtgasliq_c(), mixtliq_c2_bp(), mixtliq_d_dobpppobttto(), mixtperf_c2_grt(), mixtperf_cv_cpr(), mixtperf_d_prt(), mixtperf_r_cpg(), mixtperf_r_m(), moderror::registerfunction(), rflu_centralfirstpatch_gl(), and sqrt().
Referenced by rflu_roe_computeflux().
subroutine, public rflu_roe_computeflux1_tcp (type(t_region), pointer pRegion)
Definition at line 1680 of file RFLU_ModRoeFlux.F90.
References moderror::deregisterfunction(), rflu_modentropyfixes::entropyfixhartenhyman(), Color::g(), mixtperf_c_ghovm2(), mixtperf_ho_cptuvw(), moderror::registerfunction(), rflu_centralfirstpatch(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), and sqrt().
Referenced by rflu_roe_computeflux().
subroutine, public rflu_roe_computeflux2_gl (type(t_region), pointer pRegion)
Definition at line 1973 of file RFLU_ModRoeFlux.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), rflu_modentropyfixes::entropyfixhartenhyman(), moderror::errorstop(), mixtgasliq_c(), mixtliq_c2_bp(), mixtliq_d_dobpppobttto(), mixtperf_c2_grt(), mixtperf_cv_cpr(), mixtperf_d_prt(), mixtperf_r_cpg(), mixtperf_r_m(), moderror::registerfunction(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch_gl(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), and sqrt().
Referenced by rflu_roe_computeflux().
subroutine, public rflu_roe_computeflux2_tcp (type(t_region), pointer pRegion)
Definition at line 2519 of file RFLU_ModRoeFlux.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), rflu_modentropyfixes::entropyfixhartenhyman(), moderror::errorstop(), Color::g(), mixtperf_c_ghovm2(), mixtperf_ho_cptuvw(), mixtperf_r_cpg(), mixtperf_t_dpr(), moderror::registerfunction(), rflu_centralfirstpatch(), rflu_centralsecondpatch(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), and sqrt().
Referenced by rflu_roe_computeflux().
subroutine, public rflu_roe_computefluxc1 (type(t_region), pointer pRegion)
Definition at line 298 of file RFLU_ModRoeFlux.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_centralfirstpatch(), and rflu_modnscbc::rflu_nscbc_compfirstpatchflux().
Referenced by rflu_roe_computeflux().
subroutine, public rflu_roe_computefluxc2_tcp (type(t_region), pointer pRegion)
Definition at line 487 of file RFLU_ModRoeFlux.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), Color::g(), mixtperf_eo_dgpuvw(), moderror::registerfunction(), rflu_centralfirstpatch(), rflu_centralsecondpatch(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), and rflu_modnscbc::rflu_nscbc_compsecondpatchflux().
Referenced by rflu_roe_computeflux().
subroutine, public rflu_roe_computefluxd1_tcp (type(t_region), pointer pRegion)
Definition at line 738 of file RFLU_ModRoeFlux.F90.
References moderror::deregisterfunction(), rflu_modentropyfixes::entropyfixhartenhyman(), Color::g(), mixtperf_c_ghovm2(), mixtperf_ho_cptuvw(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_roe_computeflux().
subroutine, public rflu_roe_computefluxd2_tcp (type(t_region), pointer pRegion)
Definition at line 975 of file RFLU_ModRoeFlux.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), rflu_modentropyfixes::entropyfixhartenhyman(), Color::g(), mixtperf_c_ghovm2(), mixtperf_ho_cptuvw(), mixtperf_r_cpg(), mixtperf_t_dpr(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_roe_computeflux().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRoeFlux.F90,v $ $Revision: 1.10 $' private
Definition at line 71 of file RFLU_ModRoeFlux.F90.
The documentation for this module was generated from the following file:
RFLU_ModRoeFlux.F90