Rocstar: rflu_modsplittree Module Reference
rflu_modsplittree Module Reference
Public Member Functions
subroutine, public rflu_createsplittree (global, nDataPoints)
subroutine, public rflu_buildsplittree (global, xyz)
subroutine, public rflu_destroysplittree (global)
Private Attributes
integer, parameter nlevels_max = 50
integer, parameter nbuckets_max = 10000
integer, parameter npoints_max = 5
integer, private npoints
integer, dimension(:), allocatable pointlist
integer, dimension(:,:),
allocatable tree
real(rfreal), dimension(:),
allocatable pointxyz
Detailed Description
Definition at line 42 of file RFLU_ModSplitTree.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildsplittree (type(t_global), pointer global, real(rfreal), dimension(3,npoints), intent(in) xyz)
Definition at line 142 of file RFLU_ModSplitTree.F90.
References moderror::deregisterfunction(), modsortsearch::quicksortrfrealinteger(), and moderror::registerfunction().
subroutine, public rflu_createsplittree (type(t_global), pointer global, integer, intent(in) nDataPoints)
Definition at line 84 of file RFLU_ModSplitTree.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_destroysplittree (type(t_global), pointer global)
Definition at line 272 of file RFLU_ModSplitTree.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Member Data Documentation
integer, parameter nbuckets_max = 10000 private
Definition at line 63 of file RFLU_ModSplitTree.F90.
integer, parameter nlevels_max = 50 private
Definition at line 63 of file RFLU_ModSplitTree.F90.
integer, private npoints private
Definition at line 67 of file RFLU_ModSplitTree.F90.
integer, parameter npoints_max = 5 private
Definition at line 63 of file RFLU_ModSplitTree.F90.
integer, dimension(:), allocatable pointlist private
Definition at line 69 of file RFLU_ModSplitTree.F90.
real(rfreal), dimension(:), allocatable pointxyz private
Definition at line 72 of file RFLU_ModSplitTree.F90.
integer, dimension(:,:), allocatable tree private
Definition at line 70 of file RFLU_ModSplitTree.F90.
The documentation for this module was generated from the following file:
RFLU_ModSplitTree.F90