Rocstar: Kdtree_d< Traits >::Node::Plane Class Reference
Kdtree_d< Traits >::Node::Plane Class Reference
#include <kdtree_d.h>
Public Member Functions
Plane ()
Plane (int k, Point &p)
Plane (Plane &p)
void dump (void)
bool is_in (const Point &p) const
void set_plane (int k, Point &p)
void split (Box &region, bool f_neg)
void orient_half_space (bool f_neg_side)
int get_coord () const
Private Attributes
int coord
Point * normal
bool f_plus
Detailed Description
template<class Traits>
class Kdtree_d< Traits >::Node::Plane
Definition at line 561 of file kdtree_d.h.
Constructor & Destructor Documentation
Plane () inline
Definition at line 570 of file kdtree_d.h.
 : coord( 0), normal(NULL), f_plus(false) {}
Plane (int k, Point & p) inline
Definition at line 572 of file kdtree_d.h.
 : coord(k), normal(&p), f_plus(false) {}
Plane (Plane & p) inline
Definition at line 574 of file kdtree_d.h.
 : coord( p.coord), normal( p.normal), f_plus(p.f_plus){}
Member Function Documentation
void dump (void) inline
Definition at line 576 of file kdtree_d.h.
References Kdtree_d< Traits >::Node::Plane::coord, and Kdtree_d< Traits >::Node::Plane::normal.
Referenced by Kdtree_d< Traits >::Node::dump().
       {
         std::cout << "(" << coord << ": " << *normal << ")";
       }
int get_coord () const inline
Definition at line 617 of file kdtree_d.h.
References Kdtree_d< Traits >::Node::Plane::coord.
Referenced by Kdtree_d< Traits >::Node::search_recursive().
       {
         return  coord;
       }
bool is_in (const Point & p) const inline
Definition at line 581 of file kdtree_d.h.
References CGAL::compare(), Kdtree_d< Traits >::Node::Plane::coord, Kdtree_d< Traits >::Node::Plane::f_plus, and Kdtree_d< Traits >::Node::Plane::normal.
Referenced by Kdtree_d< Traits >::Node::is_points_in_hs().
       {
         int  cmp;
         cmp = Traits::compare( coord, p, *normal );
         if  ( ! f_plus )
           cmp = -cmp;
         return  cmp >= 0;
       }
void orient_half_space (bool f_neg_side) inline
Definition at line 612 of file kdtree_d.h.
References Kdtree_d< Traits >::Node::Plane::f_plus.
Referenced by Kdtree_d< Traits >::Node::get_hs().
       {
         f_plus = ! f_neg_side;
       }
void set_plane (int k, Point & p) inline
Definition at line 593 of file kdtree_d.h.
References Kdtree_d< Traits >::Node::Plane::coord, k, and Kdtree_d< Traits >::Node::Plane::normal.
       {
         coord = k;
         normal = &p;
         //normal->copy( coord, p );
       }
void split (Box & region, bool f_neg) inline
Definition at line 600 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::Node::Plane::coord, Kdtree_d< Traits >::Box::get_vertex(), Kdtree_d< Traits >::Node::Plane::normal, and Kdtree_d< Traits >::ExtPoint::set_coord().
Referenced by peri_printuserinput(), and Kdtree_d< Traits >::Node::search_recursive().
       {
         ExtPoint  * p_p = &(region.get_vertex( ! f_neg ));
         if  ( f_neg ) {
           if  ( p_p->compare( coord, *normal ) > 0 )
             p_p->set_coord( coord, *normal );
         } else
           if  ( p_p->compare( coord, *normal ) < 0 )
             p_p->set_coord( coord, *normal );
       }
Member Data Documentation
int coord private
Definition at line 564 of file kdtree_d.h.
Referenced by Kdtree_d< Traits >::Node::Plane::dump(), Kdtree_d< Traits >::Node::Plane::get_coord(), Kdtree_d< Traits >::Node::Plane::is_in(), Kdtree_d< Traits >::Node::Plane::set_plane(), and Kdtree_d< Traits >::Node::Plane::split().
bool f_plus private
Definition at line 566 of file kdtree_d.h.
Referenced by Kdtree_d< Traits >::Node::Plane::is_in(), and Kdtree_d< Traits >::Node::Plane::orient_half_space().
Point* normal private
Definition at line 565 of file kdtree_d.h.
Referenced by Kdtree_d< Traits >::Node::Plane::dump(), Kdtree_d< Traits >::Node::Plane::is_in(), Kdtree_d< Traits >::Node::Plane::set_plane(), and Kdtree_d< Traits >::Node::Plane::split().
The documentation for this class was generated from the following file:
kdtree_d.h