Rocstar: rflu_modweno Module Reference
rflu_modweno Module Reference
Public Member Functions
subroutine, public rflu_wenogradcellswrapper (pRegion, iBegGrad, iEndGrad, grad)
subroutine, public rflu_wenogradcellsxyzwrapper (pRegion, iBegGrad, iEndGrad, grad)
Private Member Functions
subroutine rflu_wenogradcells_2d (pRegion, iBegGrad, iEndGrad, grad)
subroutine rflu_wenogradcells_3d (pRegion, iBegGrad, iEndGrad, grad)
subroutine rflu_wenogradcellsxyz_1d (pRegion, iBegGrad, iEndGrad, grad)
subroutine rflu_wenogradcellsxyz_2d (pRegion, iBegGrad, iEndGrad, grad)
subroutine rflu_wenogradcellsxyz_3d (pRegion, iBegGrad, iEndGrad, grad)
subroutine rflu_wenogradcellsxyzfast_2d (pRegion, iBegGrad, iEndGrad, grad)
subroutine rflu_wenogradcellsxyzfast_3d (pRegion, iBegGrad, iEndGrad, grad)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModWENO.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 39 of file RFLU_ModWENO.F90.
Member Function/Subroutine Documentation
subroutine rflu_wenogradcells_2d (type(t_region), pointer pRegion, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 96 of file RFLU_ModWENO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_wenogradcellswrapper().
subroutine rflu_wenogradcells_3d (type(t_region), pointer pRegion, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 275 of file RFLU_ModWENO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_wenogradcellswrapper().
subroutine, public rflu_wenogradcellswrapper (type(t_region), pointer pRegion, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 464 of file RFLU_ModWENO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_wenogradcells_2d(), rflu_wenogradcells_3d(), and rflu_wenogradcellsxyz_1d().
Referenced by cellgradientsmp(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), and rflu_modresidual::rflu_res_computeresidual().
subroutine rflu_wenogradcellsxyz_1d (type(t_region), pointer pRegion, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 542 of file RFLU_ModWENO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), idir, moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_wenogradcellswrapper(), and rflu_wenogradcellsxyzwrapper().
subroutine rflu_wenogradcellsxyz_2d (type(t_region), pointer pRegion, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 757 of file RFLU_ModWENO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine rflu_wenogradcellsxyz_3d (type(t_region), pointer pRegion, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 961 of file RFLU_ModWENO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine rflu_wenogradcellsxyzfast_2d (type(t_region), pointer pRegion, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 1180 of file RFLU_ModWENO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_wenogradcellsxyzwrapper().
subroutine rflu_wenogradcellsxyzfast_3d (type(t_region), pointer pRegion, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 1379 of file RFLU_ModWENO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_wenogradcellsxyzwrapper().
subroutine, public rflu_wenogradcellsxyzwrapper (type(t_region), pointer pRegion, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 1593 of file RFLU_ModWENO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_wenogradcellsxyz_1d(), rflu_wenogradcellsxyzfast_2d(), and rflu_wenogradcellsxyzfast_3d().
Referenced by cellgradientsmp(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), and rflu_modresidual::rflu_res_computeresidual().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModWENO.F90,v $ $Revision: 1.4 $' private
Definition at line 60 of file RFLU_ModWENO.F90.
The documentation for this module was generated from the following file:
RFLU_ModWENO.F90