Rocstar: PatchData Class Reference
PatchData Class Reference
#include <PatchData.hpp>
Public Types
enum ComputedInfo {
MIN_UNSIGNED_AREA = 0, MAX_UNSIGNED_AREA, MIN_EDGE_LENGTH, MAX_EDGE_LENGTH,
MINMAX_SIGNED_DET2D, MINMAX_SIGNED_DET3D, AVERAGE_DET3D, MAX_COMPUTED_INFO_ENUM,
MIN_UNSIGNED_AREA = 0, MAX_UNSIGNED_AREA, MIN_EDGE_LENGTH, MAX_EDGE_LENGTH,
MINMAX_SIGNED_DET2D, MINMAX_SIGNED_DET3D, AVERAGE_DET3D, MAX_COMPUTED_INFO_ENUM
}
enum PatchType {
UNDEFINED_PATCH_TYPE, VERTICES_ON_VERTEX_PATCH, ELEMENTS_ON_VERTEX_PATCH, GLOBAL_PATCH,
UNDEFINED_PATCH_TYPE, VERTICES_ON_VERTEX_PATCH, ELEMENTS_ON_VERTEX_PATCH, GLOBAL_PATCH
}
Tells MeshSet how to retrieve the mesh entities that will be stored in PatchData.
enum culling_method {
NO_BOUNDARY_VTX = 1<<0, NO_INTERIOR_VTX = 1<<1, CULL_METHOD_3 = 1<<2, CULL_METHOD_4 = 1<<3,
NO_BOUNDARY_VTX = 1<<0, NO_INTERIOR_VTX = 1<<1, CULL_METHOD_3 = 1<<2, CULL_METHOD_4 = 1<<3
}
enum ComputedInfo {
MIN_UNSIGNED_AREA = 0, MAX_UNSIGNED_AREA, MIN_EDGE_LENGTH, MAX_EDGE_LENGTH,
MINMAX_SIGNED_DET2D, MINMAX_SIGNED_DET3D, AVERAGE_DET3D, MAX_COMPUTED_INFO_ENUM,
MIN_UNSIGNED_AREA = 0, MAX_UNSIGNED_AREA, MIN_EDGE_LENGTH, MAX_EDGE_LENGTH,
MINMAX_SIGNED_DET2D, MINMAX_SIGNED_DET3D, AVERAGE_DET3D, MAX_COMPUTED_INFO_ENUM
}
enum PatchType {
UNDEFINED_PATCH_TYPE, VERTICES_ON_VERTEX_PATCH, ELEMENTS_ON_VERTEX_PATCH, GLOBAL_PATCH,
UNDEFINED_PATCH_TYPE, VERTICES_ON_VERTEX_PATCH, ELEMENTS_ON_VERTEX_PATCH, GLOBAL_PATCH
}
Tells MeshSet how to retrieve the mesh entities that will be stored in PatchData.
enum culling_method {
NO_BOUNDARY_VTX = 1<<0, NO_INTERIOR_VTX = 1<<1, CULL_METHOD_3 = 1<<2, CULL_METHOD_4 = 1<<3,
NO_BOUNDARY_VTX = 1<<0, NO_INTERIOR_VTX = 1<<1, CULL_METHOD_3 = 1<<2, CULL_METHOD_4 = 1<<3
}
Public Member Functions
PatchData ()
~PatchData ()
void clear_computed_info ()
This function clears the patch information such as maximum volume, etc ...
bool have_computed_info (ComputedInfo info) const
void get_minmax_element_unsigned_area (double &min, double &max, MsqError &err)
Returns the maximum volume or area out of all the elements in the patch This information is stored in the patch and should not decrease performance when used properly.
double get_barrier_delta (MsqError &err)
Returns delta based on the minimum and maximum corner determinant over all elements in the patch This information is stored in the patch and should not decrease performance when used properly.
double get_average_Lambda_3d (MsqError &err)
Returns average corner determinant over all corners in the patch This information is stored in the patch and should not decrease performance when used properly.
void clear ()
Removes data.
void reorder ()
Reorders the mesh data.
void allocate_storage (size_t vertex_count, size_t element_count, size_t vertex_use_count, MsqError &err)
Used by test code when creating a PatchData directly.
void initialize_data (size_t *elem_offset_array, MsqError &err)
Call after filling vertex handle and connectivity arrays to finish initializing the PatchData.
size_t num_vertices () const
number of vertices in the patch.
size_t num_elements () const
number of elements in the Patch.
size_t num_corners ()
number of elements corners in the Patch.
size_t num_nodes () const
Get number of nodes (vertex + higher-order nodes)
int num_free_vertices (MsqError &err) const
Returns the number of elements in the current patch who are free to move.
unsigned num_free_nodes (MsqError &err) const
const MsqVertex * get_vertex_array (MsqError &err) const
Returns a pointer to the start of the vertex array.
MsqVertex * get_vertex_array (MsqError &err)
const MsqMeshEntity * get_element_array (MsqError &err) const
Returns a pointer to the start of the element array.
MsqMeshEntity * get_element_array (MsqError &err)
size_t * get_connectivity_array ()
const Mesh::ElementHandle * get_element_handles_array () const
MsqVertex & vertex_by_index (size_t index)
Returns the start of the vertex->element array.
MsqMeshEntity & element_by_index (size_t index)
size_t get_vertex_index (MsqVertex *vertex)
size_t get_element_index (MsqMeshEntity *element)
void get_element_vertex_coordinates (size_t elem_index, msq_std::vector< Vector3D > &coords, MsqError &err)
Get the coordinates of vertices attached to the specified element.
void get_element_vertex_indices (size_t elem_index, msq_std::vector< size_t > &vertex_indices, MsqError &err)
void get_vertex_element_indices (size_t vertex_index, msq_std::vector< size_t > &elem_indices, MsqError &err)
size_t * get_vertex_element_adjacencies (size_t vertex_index, size_t &array_len_out, MsqError &err)
void get_adjacent_vertex_indices (size_t vertex_index, msq_std::vector< size_t > &vert_indices, MsqError &err)
void get_adjacent_entities_via_n_dim (int n, size_t ent_ind, msq_std::vector< size_t > &adj_ents, MsqError &err)
Get the indices of entities attached to entity (given by ent_ind). adj_ents is filled with the indices into the entity array of elements adjacent to the given element via an n-dimensional entity.
void generate_vertex_to_element_data ()
void set_vertex_coordinates (const Vector3D &coords, size_t index, MsqError &err)
set the coordinates of a vertex in the raw array
void snap_vertex_to_domain (size_t vertex_index, MsqError &err)
Adjust the position of the specified vertex so that it lies on its constraining domain.
bool domain_set ()
void get_domain_normal_at_vertex (size_t vertex_index, bool normalize, Vector3D &surf_norm, MsqError &err)
void get_domain_normal_at_element (size_t elem_index, Vector3D &surf_norm, MsqError &err) const
void get_domain_normals_at_corners (size_t element_index, Vector3D normals_out[], MsqError &err)
Get surface normal at a point where the surface is the domain of an element and the point is the location of one of the element corners.
void get_domain_normal_at_element (MsqMeshEntity *elem_ptr, Vector3D &surf_norm, MsqError &err) const
Alternative signature. Same functionality.
void move_free_vertices_constrained (Vector3D dk[], size_t nb_vtx, double step_size, MsqError &err)
Moves free vertices and then snaps the free vertices to the domain.
void set_free_vertices_constrained (PatchDataVerticesMemento *memento, Vector3D dk[], size_t nb_vtx, double step_size, MsqError &err)
double get_max_vertex_movement_squared (PatchDataVerticesMemento *memento, MsqError &err)
Calculates the distance each vertex has moved from its original position as defined by the PatchDataVerticesMememnto.
void update_mesh (MsqError &err)
Updates the underlying mesh (the Mesquite::Mesh implementation) with new node coordinates and flag values.
void set_all_vertices_soft_free (MsqError &err)
Remove the soft_fixed flag from all vertices in the patch.
void set_all_vertices_soft_fixed (MsqError &err)
Add a soft_fixed flag to all vertices in the patch.
void set_free_vertices_soft_fixed (MsqError &err)
Add a soft_fixed flag to all free vertices in the patch.
void get_subpatch (size_t center_vertex_index, PatchData &pd_to_fill, MsqError &err)
Fills a PatchData with the elements attached to a center vertex.
PatchDataVerticesMemento * create_vertices_memento (MsqError &err, bool include_higher_order=false)
Creates a memento that holds the current state of the PatchData coordinates.
void recreate_vertices_memento (PatchDataVerticesMemento *memento, MsqError &err, bool include_higher_order=false)
reinstantiates a memento to holds the current state of the PatchData coordinates.
void set_to_vertices_memento (PatchDataVerticesMemento *memento, MsqError &err)
Restore the PatchData coordinates to the state contained in the memento.
PatchType type () const
void set_mesh_set (MeshSet *ms)
Sets the originating meshSet.
MeshSet * get_mesh_set ()
Returns the originating meshSet.
void clear_tag_data ()
PatchData ()
~PatchData ()
void clear_computed_info ()
This function clears the patch information such as maximum volume, etc ...
bool have_computed_info (ComputedInfo info) const
void get_minmax_element_unsigned_area (double &min, double &max, MsqError &err)
Returns the maximum volume or area out of all the elements in the patch This information is stored in the patch and should not decrease performance when used properly.
double get_barrier_delta (MsqError &err)
Returns delta based on the minimum and maximum corner determinant over all elements in the patch This information is stored in the patch and should not decrease performance when used properly.
double get_average_Lambda_3d (MsqError &err)
Returns average corner determinant over all corners in the patch This information is stored in the patch and should not decrease performance when used properly.
void clear ()
Removes data.
void reorder ()
Reorders the mesh data.
void allocate_storage (size_t vertex_count, size_t element_count, size_t vertex_use_count, MsqError &err)
Used by test code when creating a PatchData directly.
void initialize_data (size_t *elem_offset_array, MsqError &err)
Call after filling vertex handle and connectivity arrays to finish initializing the PatchData.
size_t num_vertices () const
number of vertices in the patch.
size_t num_elements () const
number of elements in the Patch.
size_t num_corners ()
number of elements corners in the Patch.
size_t num_nodes () const
Get number of nodes (vertex + higher-order nodes)
int num_free_vertices (MsqError &err) const
Returns the number of elements in the current patch who are free to move.
unsigned num_free_nodes (MsqError &err) const
const MsqVertex * get_vertex_array (MsqError &err) const
Returns a pointer to the start of the vertex array.
MsqVertex * get_vertex_array (MsqError &err)
const MsqMeshEntity * get_element_array (MsqError &err) const
Returns a pointer to the start of the element array.
MsqMeshEntity * get_element_array (MsqError &err)
size_t * get_connectivity_array ()
const Mesh::ElementHandle * get_element_handles_array () const
MsqVertex & vertex_by_index (size_t index)
Returns the start of the vertex->element array.
MsqMeshEntity & element_by_index (size_t index)
size_t get_vertex_index (MsqVertex *vertex)
size_t get_element_index (MsqMeshEntity *element)
void get_element_vertex_coordinates (size_t elem_index, msq_std::vector< Vector3D > &coords, MsqError &err)
Get the coordinates of vertices attached to the specified element.
void get_element_vertex_indices (size_t elem_index, msq_std::vector< size_t > &vertex_indices, MsqError &err)
void get_vertex_element_indices (size_t vertex_index, msq_std::vector< size_t > &elem_indices, MsqError &err)
size_t * get_vertex_element_adjacencies (size_t vertex_index, size_t &array_len_out, MsqError &err)
void get_adjacent_vertex_indices (size_t vertex_index, msq_std::vector< size_t > &vert_indices, MsqError &err)
void get_adjacent_entities_via_n_dim (int n, size_t ent_ind, msq_std::vector< size_t > &adj_ents, MsqError &err)
Get the indices of entities attached to entity (given by ent_ind). adj_ents is filled with the indices into the entity array of elements adjacent to the given element via an n-dimensional entity.
void generate_vertex_to_element_data ()
void set_vertex_coordinates (const Vector3D &coords, size_t index, MsqError &err)
void snap_vertex_to_domain (size_t vertex_index, MsqError &err)
bool domain_set ()
void get_domain_normal_at_vertex (size_t vertex_index, bool normalize, Vector3D &surf_norm, MsqError &err)
void get_domain_normal_at_element (size_t elem_index, Vector3D &surf_norm, MsqError &err) const
void get_domain_normals_at_corners (size_t element_index, Vector3D normals_out[], MsqError &err)
Get surface normal at a point where the surface is the domain of an element and the point is the location of one of the element corners.
void get_domain_normal_at_element (MsqMeshEntity *elem_ptr, Vector3D &surf_norm, MsqError &err) const
Alternative signature. Same functionality.
void move_free_vertices_constrained (Vector3D dk[], size_t nb_vtx, double step_size, MsqError &err)
Moves free vertices and then snaps the free vertices to the domain.
void set_free_vertices_constrained (PatchDataVerticesMemento *memento, Vector3D dk[], size_t nb_vtx, double step_size, MsqError &err)
double get_max_vertex_movement_squared (PatchDataVerticesMemento *memento, MsqError &err)
Calculates the distance each vertex has moved from its original position as defined by the PatchDataVerticesMememnto.
void update_mesh (MsqError &err)
Updates the underlying mesh (the Mesquite::Mesh implementation) with new node coordinates and flag values.
void set_all_vertices_soft_free (MsqError &err)
Remove the soft_fixed flag from all vertices in the patch.
void set_all_vertices_soft_fixed (MsqError &err)
Add a soft_fixed flag to all vertices in the patch.
void set_free_vertices_soft_fixed (MsqError &err)
Add a soft_fixed flag to all free vertices in the patch.
void get_subpatch (size_t center_vertex_index, PatchData &pd_to_fill, MsqError &err)
Fills a PatchData with the elements attached to a center vertex.
PatchDataVerticesMemento * create_vertices_memento (MsqError &err, bool include_higher_order=false)
Creates a memento that holds the current state of the PatchData coordinates.
void recreate_vertices_memento (PatchDataVerticesMemento *memento, MsqError &err, bool include_higher_order=false)
reinstantiates a memento to holds the current state of the PatchData coordinates.
void set_to_vertices_memento (PatchDataVerticesMemento *memento, MsqError &err)
Restore the PatchData coordinates to the state contained in the memento.
PatchType type () const
void set_mesh_set (MeshSet *ms)
Sets the originating meshSet.
MeshSet * get_mesh_set ()
Returns the originating meshSet.
void clear_tag_data ()
Public Attributes
CornerTag< TargetMatrix > targetMatrices
Target matrix data.
Private Member Functions
PatchData (const PatchData &pd)
Doesn't allow PatchData to be copied implicitly.
PatchData & operator= (const PatchData &pd)
Doesn't allow a PatchData object to be assigned to another.
void note_have_info (ComputedInfo info)
void update_cached_normals (MsqError &)
PatchData (const PatchData &pd)
Doesn't allow PatchData to be copied implicitly.
PatchData & operator= (const PatchData &pd)
Doesn't allow a PatchData object to be assigned to another.
void note_have_info (ComputedInfo info)
void update_cached_normals (MsqError &)
Private Attributes
MeshSet * meshSet
bool domainSet
DomainHint domainHint
PatchType mType
PatchDataMem< MsqVertex > vertexArray
PatchDataMem< Mesh::VertexHandle > vertexHandlesArray
PatchDataMem< MsqMeshEntity > elementArray
PatchDataMem< Mesh::ElementHandle > elementHandlesArray
PatchDataMem< size_t > elemConnectivityArray
PatchDataMem< size_t > vertAdjacencyArray
PatchDataMem< size_t > vertAdjacencyOffsets
PatchDataMem< Vector3D > vertexNormals
size_t numCornerVertices
double computedInfos [MAX_COMPUTED_INFO_ENUM]
unsigned haveComputedInfos
Friends
class MeshSet
msq_stdio::ostream & operator<< (msq_stdio::ostream &, const PatchData &)
Display the coordinates and connectivity information.
msq_stdio::ostream & operator<< (msq_stdio::ostream &, const PatchData &)
Display the coordinates and connectivity information.
Detailed Description
Contains all the mesh information necessary for one iteration of the optimization algorithms over a local mesh patch.
Definition at line 87 of file includeLinks/PatchData.hpp.
Member Enumeration Documentation
enum ComputedInfo
Enumerator
MIN_UNSIGNED_AREA
minimum volume or area out of all elements in the patch
MAX_UNSIGNED_AREA
maximum volume or area out of all elements in the patch
MIN_EDGE_LENGTH
minimum edge length in the patch
MAX_EDGE_LENGTH
maximum edge length in the patch
MINMAX_SIGNED_DET2D
minimum and maximum corner area out of all elements in the patch
MINMAX_SIGNED_DET3D
minimum and maximum corner volume out of all elements in the patch
AVERAGE_DET3D
average corner determinant out of all elements in the patch
MAX_COMPUTED_INFO_ENUM
MIN_UNSIGNED_AREA
minimum volume or area out of all elements in the patch
MAX_UNSIGNED_AREA
maximum volume or area out of all elements in the patch
MIN_EDGE_LENGTH
minimum edge length in the patch
MAX_EDGE_LENGTH
maximum edge length in the patch
MINMAX_SIGNED_DET2D
minimum and maximum corner area out of all elements in the patch
MINMAX_SIGNED_DET3D
minimum and maximum corner volume out of all elements in the patch
AVERAGE_DET3D
average corner determinant out of all elements in the patch
MAX_COMPUTED_INFO_ENUM
Definition at line 104 of file includeLinks/PatchData.hpp.
                       {
       MIN_UNSIGNED_AREA = 0,
       MAX_UNSIGNED_AREA,
       MIN_EDGE_LENGTH,
       MAX_EDGE_LENGTH,
       MINMAX_SIGNED_DET2D,
       MINMAX_SIGNED_DET3D,
       AVERAGE_DET3D,
       MAX_COMPUTED_INFO_ENUM
     };
enum ComputedInfo
Enumerator
MIN_UNSIGNED_AREA
minimum volume or area out of all elements in the patch
MAX_UNSIGNED_AREA
maximum volume or area out of all elements in the patch
MIN_EDGE_LENGTH
minimum edge length in the patch
MAX_EDGE_LENGTH
maximum edge length in the patch
MINMAX_SIGNED_DET2D
minimum and maximum corner area out of all elements in the patch
MINMAX_SIGNED_DET3D
minimum and maximum corner volume out of all elements in the patch
AVERAGE_DET3D
average corner determinant out of all elements in the patch
MAX_COMPUTED_INFO_ENUM
MIN_UNSIGNED_AREA
minimum volume or area out of all elements in the patch
MAX_UNSIGNED_AREA
maximum volume or area out of all elements in the patch
MIN_EDGE_LENGTH
minimum edge length in the patch
MAX_EDGE_LENGTH
maximum edge length in the patch
MINMAX_SIGNED_DET2D
minimum and maximum corner area out of all elements in the patch
MINMAX_SIGNED_DET3D
minimum and maximum corner volume out of all elements in the patch
AVERAGE_DET3D
average corner determinant out of all elements in the patch
MAX_COMPUTED_INFO_ENUM
Definition at line 104 of file src/Mesh/PatchData.hpp.
                       {
       MIN_UNSIGNED_AREA = 0,
       MAX_UNSIGNED_AREA,
       MIN_EDGE_LENGTH,
       MAX_EDGE_LENGTH,
       MINMAX_SIGNED_DET2D,
       MINMAX_SIGNED_DET3D,
       AVERAGE_DET3D,
       MAX_COMPUTED_INFO_ENUM
     };
enum culling_method
Enumerator
NO_BOUNDARY_VTX
removes vertices on the boundary. (i.e. with a TSTT tag "boundary").
NO_INTERIOR_VTX
removes vertices that are not on the boundary
CULL_METHOD_3
no other culling method yet.
CULL_METHOD_4
NO_BOUNDARY_VTX
removes vertices on the boundary. (i.e. with a TSTT tag "boundary").
NO_INTERIOR_VTX
removes vertices that are not on the boundary
CULL_METHOD_3
no other culling method yet.
CULL_METHOD_4
Definition at line 407 of file src/Mesh/PatchData.hpp.
{
       NO_BOUNDARY_VTX = 1<<0,
       NO_INTERIOR_VTX = 1<<1,
       CULL_METHOD_3   = 1<<2,
       CULL_METHOD_4   = 1<<3
     };
enum culling_method
Those are the culling method available to the users. Developpers: The values used in that enum are used by a bitset, so they have to be 2-based (2,4,8,16,32, ...)
Enumerator
NO_BOUNDARY_VTX
removes vertices on the boundary. (i.e. with a TSTT tag "boundary").
NO_INTERIOR_VTX
removes vertices that are not on the boundary
CULL_METHOD_3
no other culling method yet.
CULL_METHOD_4
NO_BOUNDARY_VTX
removes vertices on the boundary. (i.e. with a TSTT tag "boundary").
NO_INTERIOR_VTX
removes vertices that are not on the boundary
CULL_METHOD_3
no other culling method yet.
CULL_METHOD_4
Definition at line 407 of file includeLinks/PatchData.hpp.
{
       NO_BOUNDARY_VTX = 1<<0,
       NO_INTERIOR_VTX = 1<<1,
       CULL_METHOD_3   = 1<<2,
       CULL_METHOD_4   = 1<<3
     };
enum PatchType
Tells MeshSet how to retrieve the mesh entities that will be stored in PatchData.
The PatchType is set by the QualityImprover etc... and mesquite propagates it to the MeshSet.
Enumerator
UNDEFINED_PATCH_TYPE
Default.
VERTICES_ON_VERTEX_PATCH
fills PatchData with the vertices connected through edges to the center vertex.
ELEMENTS_ON_VERTEX_PATCH
fills PatchData with the vertices connected through elements to the center vertex.
GLOBAL_PATCH
Fills PatchData with all elements and vertices contained in all the meshes of the MeshSet.
UNDEFINED_PATCH_TYPE
Default.
VERTICES_ON_VERTEX_PATCH
fills PatchData with the vertices connected through edges to the center vertex.
ELEMENTS_ON_VERTEX_PATCH
fills PatchData with the vertices connected through elements to the center vertex.
GLOBAL_PATCH
Fills PatchData with all elements and vertices contained in all the meshes of the MeshSet.
Definition at line 391 of file includeLinks/PatchData.hpp.
       {
         UNDEFINED_PATCH_TYPE,
         VERTICES_ON_VERTEX_PATCH,
         ELEMENTS_ON_VERTEX_PATCH,
         GLOBAL_PATCH
       };
enum PatchType
Tells MeshSet how to retrieve the mesh entities that will be stored in PatchData.
The PatchType is set by the QualityImprover etc... and mesquite propagates it to the MeshSet.
Enumerator
UNDEFINED_PATCH_TYPE
Default.
VERTICES_ON_VERTEX_PATCH
fills PatchData with the vertices connected through edges to the center vertex.
ELEMENTS_ON_VERTEX_PATCH
fills PatchData with the vertices connected through elements to the center vertex.
GLOBAL_PATCH
Fills PatchData with all elements and vertices contained in all the meshes of the MeshSet.
UNDEFINED_PATCH_TYPE
Default.
VERTICES_ON_VERTEX_PATCH
fills PatchData with the vertices connected through edges to the center vertex.
ELEMENTS_ON_VERTEX_PATCH
fills PatchData with the vertices connected through elements to the center vertex.
GLOBAL_PATCH
Fills PatchData with all elements and vertices contained in all the meshes of the MeshSet.
Definition at line 391 of file src/Mesh/PatchData.hpp.
       {
         UNDEFINED_PATCH_TYPE,
         VERTICES_ON_VERTEX_PATCH,
         ELEMENTS_ON_VERTEX_PATCH,
         GLOBAL_PATCH
       };
Constructor & Destructor Documentation
PatchData ()
Definition at line 67 of file Mesh/PatchData.cpp.
   : targetMatrices( "MSQ_TARGET_MATRIX", Mesh::DOUBLE ),
     meshSet(0),
     domainSet(false),
     domainHint(NO_DOMAIN_HINT),
     mType(UNDEFINED_PATCH_TYPE),
     numCornerVertices(0),
     haveComputedInfos(0)
 {
 }
~PatchData ()
Definition at line 81 of file Mesh/PatchData.cpp.
 {
 }
PatchData (const PatchData & pd) private
Doesn't allow PatchData to be copied implicitly.
Mementos such as PatchDataVerticesMemento should be used when necessary.
PatchData ()
~PatchData ()
PatchData (const PatchData & pd) private
Doesn't allow PatchData to be copied implicitly.
Mementos such as PatchDataVerticesMemento should be used when necessary.
Member Function Documentation
void allocate_storage (size_t vertex_count, size_t element_count, size_t vertex_use_count, MsqError & err)
Used by test code when creating a PatchData directly.
PatchData should be constructed by first calling this function, then initializing arrays and then calling initalize_data.
Definition at line 1471 of file Mesh/PatchData.cpp.
References PatchData::clear_tag_data(), PatchData::elemConnectivityArray, PatchData::elementArray, PatchData::elementHandlesArray, PatchData::numCornerVertices, PatchDataMem< X >::resize(), PatchData::vertexArray, and PatchData::vertexHandlesArray.
 {
   vertexArray.resize( vertex_count );
   vertexHandlesArray.resize( vertex_count );
   elementArray.resize( element_count );
   elementHandlesArray.resize( element_count );
   elemConnectivityArray.resize( vertex_use_count );
   clear_tag_data();
   numCornerVertices = 0;
 }
void allocate_storage (size_t vertex_count, size_t element_count, size_t vertex_use_count, MsqError & err)
Used by test code when creating a PatchData directly.
PatchData should be constructed by first calling this function, then initializing arrays and then calling initalize_data.
void clear () inline
Removes data.
Definition at line 491 of file includeLinks/PatchData.hpp.
References PatchDataMem< X >::clear(), PatchData::elemConnectivityArray, PatchData::elementArray, PatchData::elementHandlesArray, PatchData::haveComputedInfos, PatchData::meshSet, PatchData::numCornerVertices, PatchData::vertAdjacencyArray, PatchData::vertAdjacencyOffsets, PatchData::vertexArray, PatchData::vertexHandlesArray, and PatchData::vertexNormals.
Referenced by MeshSet::get_next_patch().
   {
     vertexArray.clear();
     vertexHandlesArray.clear();
     elementArray.clear();
     elementHandlesArray.clear();
     elemConnectivityArray.clear();
     vertAdjacencyArray.clear();
     vertAdjacencyOffsets.clear();
     vertexNormals.clear();
     numCornerVertices = 0;
     haveComputedInfos = 0;
     meshSet = 0;
   }
void clear ()
Removes data.
void clear_computed_info () inline
This function clears the patch information such as maximum volume, etc ...
Definition at line 116 of file includeLinks/PatchData.hpp.
References PatchData::haveComputedInfos.
 { haveComputedInfos = 0; }
void clear_computed_info () inline
This function clears the patch information such as maximum volume, etc ...
Definition at line 116 of file src/Mesh/PatchData.hpp.
References PatchData::haveComputedInfos.
 { haveComputedInfos = 0; }
void clear_tag_data ()
Definition at line 1485 of file Mesh/PatchData.cpp.
References PatchData::targetMatrices.
Referenced by PatchData::allocate_storage(), PatchData::initialize_data(), and PatchData::reorder().
 {
   targetMatrices.clear();
 }
void clear_tag_data ()
PatchDataVerticesMemento * create_vertices_memento (MsqError & err, bool include_higher_order = false) inline
Creates a memento that holds the current state of the PatchData coordinates.
Definition at line 615 of file includeLinks/PatchData.hpp.
References PatchDataVerticesMemento::arraySize, PatchData::num_nodes(), PatchData::num_vertices(), PatchDataVerticesMemento::numVertices, PatchDataVerticesMemento::originator, PatchData::vertexArray, and PatchDataVerticesMemento::vertices.
Referenced by ConjugateGradient::initialize(), FeasibleNewton::initialize(), SteepestDescent::optimize_vertex_positions(), TerminationCriterion::reset_inner(), and TerminationCriterion::reset_patch().
   {
     size_t num_verts = include_higher_order ? num_nodes() : num_vertices();
     PatchDataVerticesMemento* memento = new PatchDataVerticesMemento;
     memento->originator = this;
     if (num_verts)
       memento->vertices = new MsqVertex[num_verts];
     memento->numVertices = num_verts;
     memento->arraySize = num_verts;
       // Copy the coordinates
     msq_stdc::memcpy(memento->vertices, &vertexArray[0], num_verts*sizeof(MsqVertex) );
     return memento;
   }
PatchDataVerticesMemento* create_vertices_memento (MsqError & err, bool include_higher_order = false)
Creates a memento that holds the current state of the PatchData coordinates.
bool domain_set () inline
Returns whether a domain is associated with the MeshSet from which the Patch originates. If false, you cannot ask for a surface normal.
Definition at line 280 of file includeLinks/PatchData.hpp.
References PatchData::domainSet.
Referenced by GeneralizedConditionNumberQualityMetric::compute_condition_number(), MsqMeshEntity::compute_corner_normals(), and ShapeQualityMetric::condition_number_2d().
     { return domainSet; }
bool domain_set () inline
Returns whether a domain is associated with the MeshSet from which the Patch originates. If false, you cannot ask for a surface normal.
Definition at line 280 of file src/Mesh/PatchData.hpp.
References PatchData::domainSet.
     { return domainSet; }
MsqMeshEntity& element_by_index (size_t index)
MsqMeshEntity & element_by_index (size_t index) inline
Definition at line 589 of file includeLinks/PatchData.hpp.
References PatchData::elementArray.
Referenced by NonSmoothSteepestDescent::compute_function(), MeanMidNodeMover::loop_over_mesh(), QualityAssessor::loop_over_mesh(), and CornerTagHandles::num_corners().
   {
     return elementArray[index];
   }
void generate_vertex_to_element_data ()
Create the arrays that store which elements are attached to each node. If you know how many total vertex uses there are, pass it in. Otherwise the PatchData will calculate that number.
Definition at line 944 of file Mesh/PatchData.cpp.
References PatchDataMem< X >::begin(), PatchData::elemConnectivityArray, PatchData::elementArray, PatchDataMem< X >::empty(), PatchDataMem< X >::end(), i, MSQ_FUNCTION_TIMER, PatchData::num_nodes(), PatchDataMem< X >::resize(), PatchDataMem< X >::size(), PatchData::vertAdjacencyArray, and PatchData::vertAdjacencyOffsets.
Referenced by PatchData::get_vertex_element_adjacencies(), and PatchData::reorder().
 {
   MSQ_FUNCTION_TIMER( "PatchData::generate_vertex_to_element_data" );
     // Skip if data already exists
   if (!vertAdjacencyArray.empty())
     return;
     // Allocate offset array
   vertAdjacencyOffsets.resize( num_nodes() + 1 );
   memset( &vertAdjacencyOffsets[0], 0, sizeof(size_t)*vertAdjacencyOffsets.size() );
     // Temporarily use offsets array to hold per-vertex element count
   PatchDataMem<MsqMeshEntity>::iterator elem_iter;
   const PatchDataMem<MsqMeshEntity>::iterator elem_end = elementArray.end();
   for (elem_iter = elementArray.begin(); elem_iter != elem_end; ++elem_iter)
   {
     size_t* conn_iter = elem_iter->get_vertex_index_array();
     const size_t* conn_end = conn_iter + elem_iter->node_count();
     for ( ; conn_iter != conn_end; ++conn_iter )
       ++vertAdjacencyOffsets[*conn_iter];
   }
     // Convert counts to end indices.
     // When done, vertAdjacencyOffsets will contain, for each vertex,
     // one more than the *last* index for that vertex's data in the
     // adjacency array.  This is *not* the final state for this data.
     // See comments for next loop.
   PatchDataMem<size_t>::iterator off_iter = vertAdjacencyOffsets.begin();
   const PatchDataMem<size_t>::iterator off_end = vertAdjacencyOffsets.end();
   size_t prev = *off_iter;
   ++off_iter;
   for ( ; off_iter != off_end; ++off_iter)
   {
     prev += *off_iter;
     *off_iter = prev;
   }
     // Allocate space for element numbers
   const size_t num_vert_uses = vertAdjacencyOffsets[num_nodes()-1];
   assert( num_vert_uses == elemConnectivityArray.size() );
   vertAdjacencyArray.resize( num_vert_uses );
     // Fill vertAdjacencyArray, using the indices in vertAdjacencyOffsets
     // as the location to insert the next element number in
     // vertAdjacencyArray.  When done, vertAdjacenyOffsets will contain
     // the start index for each vertex, rather than one past the last
     // index.
   for (size_t i = 0; i < elementArray.size(); ++i)
   {
     size_t* conn_iter = elementArray[i].get_vertex_index_array();
     const size_t* conn_end = conn_iter + elementArray[i].node_count();
     for ( ; conn_iter != conn_end; ++conn_iter )
     {
       const size_t array_index = --vertAdjacencyOffsets[*conn_iter];
       vertAdjacencyArray[array_index] = i;
     }
   }
     // Last entry should be number of vertex uses (one past the
     // last index of the last vertex.)
   vertAdjacencyOffsets[num_nodes()] = num_vert_uses;
 }
void generate_vertex_to_element_data ()
Create the arrays that store which elements are attached to each node. If you know how many total vertex uses there are, pass it in. Otherwise the PatchData will calculate that number.
void get_adjacent_entities_via_n_dim (int n, size_t ent_ind, msq_std::vector< size_t > & adj_ents, MsqError & err)
Get the indices of entities attached to entity (given by ent_ind). adj_ents is filled with the indices into the entity array of elements adjacent to the given element via an n-dimensional entity.
Referenced by ASMQualityMetric::evaluate_element().
void get_adjacent_entities_via_n_dim (int n, size_t ent_ind, msq_std::vector< size_t > & adj_ents, MsqError & err)
Get the indices of entities attached to entity (given by ent_ind). adj_ents is filled with the indices into the entity array of elements adjacent to the given element via an n-dimensional entity.
void get_adjacent_vertex_indices (size_t vertex_index, msq_std::vector< size_t > & vert_indices, MsqError & err)
Get the indices of vertices that are attached to vertex (given by vertex_index) by an element edge.
void get_adjacent_vertex_indices (size_t vertex_index, msq_std::vector< size_t > & vert_indices, MsqError & err)
Get the indices of vertices that are attached to vertex (given by vertex_index) by an element edge.
Referenced by LPtoPTemplate::compute_analytical_gradient(), EdgeLengthQualityMetric::evaluate_vertex(), EdgeLengthRangeQualityMetric::evaluate_vertex(), SmartLaplacianSmoother::optimize_vertex_positions(), and LaplacianSmoother::optimize_vertex_positions().
double get_average_Lambda_3d (MsqError & err)
Returns average corner determinant over all corners in the patch This information is stored in the patch and should not decrease performance when used properly.
See also PatchData::clear_computed_info() .
Definition at line 158 of file Mesh/PatchData.cpp.
References A, PatchData::AVERAGE_DET3D, TargetCalculator::compute_Lambda(), PatchData::computedInfos, PatchData::elementArray, PatchData::have_computed_info(), i, MSQ_ERRZERO, Mesquite::MSQ_MAX_NUM_VERT_PER_ENT, and PatchData::note_have_info().
Referenced by LVQDTargetCalculator::compute_target_matrices().
 {
   double avg;
   if (have_computed_info(AVERAGE_DET3D))
   {
     avg = computedInfos[AVERAGE_DET3D];
   }
   else
   {
     avg =0.;
     int total_num_corners =0;
     Matrix3D A[MSQ_MAX_NUM_VERT_PER_ENT];
     for (size_t i=0; i<elementArray.size(); ++i) {
       int nve = elementArray[i].vertex_count();
       elementArray[i].compute_corner_matrices(*this, A, nve, err);
       MSQ_ERRZERO(err);
       total_num_corners += nve;
       for (int c=0; c<nve; ++c) {
         avg += TargetCalculator::compute_Lambda(A[c], err);
         MSQ_ERRZERO(err);
       }
     }
     avg = avg / total_num_corners;
     computedInfos[AVERAGE_DET3D] = avg;
     note_have_info(AVERAGE_DET3D);
   }
   return avg;
 }
double get_average_Lambda_3d (MsqError & err)
Returns average corner determinant over all corners in the patch This information is stored in the patch and should not decrease performance when used properly.
See also PatchData::clear_computed_info() .
double get_barrier_delta (MsqError & err)
Returns delta based on the minimum and maximum corner determinant over all elements in the patch This information is stored in the patch and should not decrease performance when used properly.
See also PatchData::clear_computed_info() .
Definition at line 117 of file Mesh/PatchData.cpp.
References A, PatchData::computedInfos, Mesquite::det(), PatchData::elementArray, PatchData::have_computed_info(), i, MsqError::INVALID_MESH, j, max(), min(), PatchData::MINMAX_SIGNED_DET3D, Mesquite::MSQ_DBL_MAX, MSQ_ERRZERO, Mesquite::MSQ_MAX_NUM_VERT_PER_ENT, Mesquite::MSQ_MIN, MSQ_SETERR, PatchData::note_have_info(), and PatchData::num_elements().
Referenced by RI_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), ShapeQualityMetric::condition_number_2d(), ShapeQualityMetric::condition_number_3d(), RI_DFT::evaluate_element(), I_DFT::evaluate_element(), and DistanceFromTarget::get_barrier_function().
 {
   double result;
   if (have_computed_info(MINMAX_SIGNED_DET3D))
   {
     result = computedInfos[MINMAX_SIGNED_DET3D];
   }
   else
   {
     double min= MSQ_DBL_MAX;
     double max=-MSQ_DBL_MAX;
     size_t count = num_elements();
     for (size_t i=0; i<count; ++i) {
       Matrix3D A[MSQ_MAX_NUM_VERT_PER_ENT];
       size_t nve = elementArray[i].vertex_count();
       elementArray[i].compute_corner_matrices(*this, A, nve, err);
       MSQ_ERRZERO(err);
       for (size_t j=0; j<nve; ++j) {
         min = det(A[j]) < min ? det(A[j]) : min;
         max = det(A[j]) > max ? det(A[j]) : max;
       }
     }
     if (max <= 0) {
       MSQ_SETERR(err)("Sigma_max is not positive.", MsqError::INVALID_MESH);
       return 0;
     }
       //We set delta to zero if everything in the initial mesh is valid.
       //  This causes metrics with a barrier between valid and inverted
       //  meshes to retain that barrier.  If there is a negative jacobian
       //  corner in the mesh, we set delta to a small fraction of the
       //  maximum jacobian in the mesh.
     result = (min<=MSQ_MIN) ? 0.001 * max : 0;
     computedInfos[MINMAX_SIGNED_DET3D] = result;
     note_have_info(MINMAX_SIGNED_DET3D);
   }
   return result;
 }
double get_barrier_delta (MsqError & err)
Returns delta based on the minimum and maximum corner determinant over all elements in the patch This information is stored in the patch and should not decrease performance when used properly.
See also PatchData::clear_computed_info() .
size_t* get_connectivity_array () inline
Definition at line 201 of file src/Mesh/PatchData.hpp.
References PatchData::elemConnectivityArray.
       { return &elemConnectivityArray[0]; }
size_t* get_connectivity_array () inline
Definition at line 201 of file includeLinks/PatchData.hpp.
References PatchData::elemConnectivityArray.
       { return &elemConnectivityArray[0]; }
void get_domain_normal_at_element (size_t elem_index, Vector3D & surf_norm, MsqError & err) const
Get the normal to the domain at the centroid (projected to the domain) of a given element. Normal is returned in Vector3D &surf_norm. If the normal cannot be determined, or if the underlying domain is not a surface, the normal will be set to (0,0,0). Check PatchData::domain_set() is not false first.
Definition at line 1184 of file Mesh/PatchData.cpp.
References PatchData::elementArray, PatchData::elementHandlesArray, MeshSet::get_domain_constraint(), MsqError::INVALID_STATE, PatchData::meshSet, MSQ_ERRRTN, MSQ_SETERR, and MeshDomain::normal_at().
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightMeanRatio::compute_element_analytical_hessian(), MsqMeshEntity::compute_signed_area(), IdealWeightInverseMeanRatio::evaluate_element(), IdealWeightMeanRatio::evaluate_element(), PatchData::get_domain_normal_at_element(), and UntangleBetaQualityMetric::untangle_function_2d().
 {
   if (meshSet && meshSet->get_domain_constraint())
   {
     elementArray[elem_index].get_centroid(surf_norm, *this, err);
     MSQ_ERRRTN(err);
     meshSet->get_domain_constraint()->normal_at(
       elementHandlesArray[elem_index],
       surf_norm);
   }
   else
     MSQ_SETERR(err)( "No domain constraint set.", MsqError::INVALID_STATE );
 }
void get_domain_normal_at_element (size_t elem_index, Vector3D & surf_norm, MsqError & err) const
Get the normal to the domain at the centroid (projected to the domain) of a given element. Normal is returned in Vector3D &surf_norm. If the normal cannot be determined, or if the underlying domain is not a surface, the normal will be set to (0,0,0). Check PatchData::domain_set() is not false first.
void get_domain_normal_at_element (MsqMeshEntity * elem_ptr, Vector3D & surf_norm, MsqError & err) const inline
Alternative signature. Same functionality.
Definition at line 321 of file includeLinks/PatchData.hpp.
References PatchData::elementArray, and PatchData::get_domain_normal_at_element().
     { get_domain_normal_at_element(size_t(elem_ptr-&(elementArray[0])), surf_norm, err); }
void get_domain_normal_at_element (MsqMeshEntity * elem_ptr, Vector3D & surf_norm, MsqError & err) const inline
Alternative signature. Same functionality.
Definition at line 321 of file src/Mesh/PatchData.hpp.
References PatchData::elementArray, and PatchData::get_domain_normal_at_element().
     { get_domain_normal_at_element(size_t(elem_ptr-&(elementArray[0])), surf_norm, err); }
void get_domain_normal_at_vertex (size_t vertex_index, bool normalize, Vector3D & surf_norm, MsqError & err)
Get the normal of the surface for a given vertex. Normal is returned in Vector3D &surf_norm. If the normal cannot be determined, or if the underlying domain is not a surface, the normal will be set to (0,0,0). Check PatchData::domain_set() is not false first.
Definition at line 1117 of file Mesh/PatchData.cpp.
References PatchData::domainHint, MeshSet::get_domain_constraint(), MsqError::INVALID_STATE, PatchData::meshSet, MSQ_ERRRTN, MSQ_SETERR, Mesquite::NO_DOMAIN_HINT, MeshDomain::normal_at(), Vector3D::normalize(), Mesquite::PLANAR_DOMAIN, PatchData::update_cached_normals(), PatchData::vertexArray, PatchData::vertexHandlesArray, and PatchData::vertexNormals.
Referenced by GeneralizedConditionNumberQualityMetric::compute_condition_number(), RI_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), ShapeQualityMetric::condition_number_2d(), and RI_DFT::evaluate_element().
 {
   if (domainHint != NO_DOMAIN_HINT)
   {
     if (vertexNormals.empty())
     {
       update_cached_normals( err ); MSQ_ERRRTN(err);
     }
     if (domainHint == PLANAR_DOMAIN)
       vertex_index = 0;
     surf_norm = vertexNormals[vertex_index];
   }
   else
   {
     MeshDomain* domain = meshSet ? meshSet->get_domain_constraint() : 0;
     if (!domain)
     {
       MSQ_SETERR(err)( "No domain constraint set.", MsqError::INVALID_STATE );
       return;
     }
     surf_norm = vertexArray[vertex_index];
     domain->normal_at( vertexHandlesArray[vertex_index], surf_norm );
   }
   if (normalize)
     surf_norm.normalize();
 }
void get_domain_normal_at_vertex (size_t vertex_index, bool normalize, Vector3D & surf_norm, MsqError & err)
Get the normal of the surface for a given vertex. Normal is returned in Vector3D &surf_norm. If the normal cannot be determined, or if the underlying domain is not a surface, the normal will be set to (0,0,0). Check PatchData::domain_set() is not false first.
void get_domain_normals_at_corners (size_t element_index, Vector3D normals_out[], MsqError & err)
Get surface normal at a point where the surface is the domain of an element and the point is the location of one of the element corners.
Get surface normals at element corners. normals_out must be of sufficient size to hold the normals of all the corners.
Definition at line 1221 of file Mesh/PatchData.cpp.
References PatchData::domainHint, PatchData::elementArray, PatchData::elementHandlesArray, MeshSet::get_domain_constraint(), MsqMeshEntity::get_vertex_index_array(), i, MsqError::INVALID_STATE, PatchData::meshSet, MSQ_CHKERR, MSQ_ERRRTN, MSQ_SETERR, Mesquite::NO_DOMAIN_HINT, MeshDomain::normal_at(), Mesquite::PLANAR_DOMAIN, PatchData::update_cached_normals(), MsqMeshEntity::vertex_count(), PatchData::vertexArray, and PatchData::vertexNormals.
Referenced by MsqMeshEntity::compute_corner_normals().
 {
   const MsqMeshEntity& elem = elementArray[elem_index];
   const unsigned count = elem.vertex_count();
   const size_t* const vertex_indices = elem.get_vertex_index_array();
   if (domainHint != NO_DOMAIN_HINT)
   {
     if (vertexNormals.empty())
     {
       update_cached_normals( err ); MSQ_ERRRTN(err);
     }
     if (domainHint == PLANAR_DOMAIN)
     {
       for (unsigned i = 0; i < count; ++i)
         normals_out[i] = vertexNormals[0];
     }
     else
     {
       for (unsigned i = 0; i < count; ++i)
         normals_out[i] = vertexNormals[vertex_indices[i]];
     }
   }
   else
   {
     MeshDomain* domain = meshSet ? meshSet->get_domain_constraint() : 0;
     if (!domain)
     {
       MSQ_SETERR(err)( "No domain constraint set.", MsqError::INVALID_STATE );
       return;
     }
     for (unsigned i = 0; i < count; ++i)
       normals_out[i] = vertexArray[ vertex_indices[i] ];
     domain->normal_at( elementHandlesArray[elem_index],
                        normals_out, count,
                        err ); MSQ_CHKERR(err);
   }
 }
void get_domain_normals_at_corners (size_t element_index, Vector3D normals_out[], MsqError & err)
Get surface normal at a point where the surface is the domain of an element and the point is the location of one of the element corners.
Get surface normals at element corners. normals_out must be of sufficient size to hold the normals of all the corners.
const MsqMeshEntity * get_element_array (MsqError & err) const inline
Returns a pointer to the start of the element array.
Returns the PatchData element array.
Definition at line 530 of file includeLinks/PatchData.hpp.
References PatchData::elementArray, MsqError::INVALID_STATE, and MSQ_SETERR.
Referenced by MsqHessian::accumulate_entries(), VertexMover::check_feasible(), LPtoPTemplate::compute_analytical_gradient(), LPtoPTemplate::compute_analytical_hessian(), TargetCalculator::compute_default_target_matrices(), TargetCalculator::compute_guide_matrices(), TargetCalculator::compute_reference_corner_matrices(), WTargetCalculator::compute_target_matrices(), LVQDTargetCalculator::compute_target_matrices(), TargetCalculator::compute_target_matrices_and_check_det(), LInfTemplate::concrete_evaluate(), MaxTemplate::concrete_evaluate(), LPtoPTemplate::concrete_evaluate(), ASMQualityMetric::evaluate_element(), VertexConditionNumberQualityMetric::evaluate_vertex(), LocalSizeQualityMetric::evaluate_vertex(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), MsqHessian::initialize(), NonSmoothSteepestDescent::optimize_vertex_positions(), and CornerTagHandles::save_load_tags().
   {
     if (elementArray.empty())
       MSQ_SETERR(err)( "No element array defined", MsqError::INVALID_STATE );
     return &elementArray[0];
   }
const MsqMeshEntity* get_element_array (MsqError & err) const
Returns a pointer to the start of the element array.
MsqMeshEntity* get_element_array (MsqError & err)
MsqMeshEntity * get_element_array (MsqError & err) inline
Definition at line 536 of file includeLinks/PatchData.hpp.
References PatchData::elementArray, MsqError::INVALID_STATE, and MSQ_SETERR.
   {
     if (elementArray.empty())
       MSQ_SETERR(err)( "No element array defined", MsqError::INVALID_STATE );
     return &elementArray[0];
   }
const Mesh::ElementHandle* get_element_handles_array () const inline
Definition at line 204 of file src/Mesh/PatchData.hpp.
References PatchData::elementHandlesArray.
       { return &elementHandlesArray[0]; }
const Mesh::ElementHandle* get_element_handles_array () const inline
Definition at line 204 of file includeLinks/PatchData.hpp.
References PatchData::elementHandlesArray.
Referenced by CornerTagHandles::save_load_tags().
       { return &elementHandlesArray[0]; }
size_t get_element_index (MsqMeshEntity * element)
size_t get_element_index (MsqMeshEntity * element) inline
Definition at line 601 of file includeLinks/PatchData.hpp.
References PatchData::elementArray.
Referenced by MsqMeshEntity::compute_corner_normals(), RI_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), MsqMeshEntity::compute_signed_area(), DistanceFromTarget::compute_T_matrices(), RI_DFT::evaluate_element(), ASMQualityMetric::evaluate_element(), UntangleBetaQualityMetric::evaluate_element(), AspectRatioGammaQualityMetric::evaluate_element(), and I_DFT::evaluate_element().
   {
     return element - &elementArray[0];
   }
void get_element_vertex_coordinates (size_t elem_index, msq_std::vector< Vector3D > & coords, MsqError & err)
Get the coordinates of vertices attached to the specified element.
void get_element_vertex_coordinates (size_t elem_index, msq_std::vector< Vector3D > & coords, MsqError & err)
Get the coordinates of vertices attached to the specified element.
Referenced by AspectRatioGammaQualityMetric::evaluate_element().
void get_element_vertex_indices (size_t elem_index, msq_std::vector< size_t > & vertex_indices, MsqError & err)
Get the indices of vertices of specified element. !inefficient!
void get_element_vertex_indices (size_t elem_index, msq_std::vector< size_t > & vertex_indices, MsqError & err)
Get the indices of vertices of specified element. !inefficient!
double get_max_vertex_movement_squared (PatchDataVerticesMemento * memento, MsqError & err)
Calculates the distance each vertex has moved from its original position as defined by the PatchDataVerticesMememnto.
Finds the maximum movement (in the distance norm) of the vertices in a patch. The previous vertex positions are givena as a PatchDataVerticesMemento (memento). The distance squared which each vertex has moved is then calculated, and the largest of those distances is returned. This function only considers the movement of vertices that are currently 'free'.
Parameters
memento a memento of this patch's vertex position at some (prior) time in the optimization.
Definition at line 679 of file Mesh/PatchData.cpp.
References Vector3D::length_squared(), MSQ_ERRZERO, MsqFreeVertexIndexIterator::next(), MsqFreeVertexIndexIterator::reset(), MsqFreeVertexIndexIterator::value(), PatchData::vertexArray, and PatchDataVerticesMemento::vertices.
Referenced by TerminationCriterion::accumulate_inner(), TerminationCriterion::accumulate_patch(), and TerminationCriterion::cull_vertices().
 {
   int m=0;
   Vector3D temp_vec;
   double temp_dist=0.0;
   double max_dist=0.0;
   MsqFreeVertexIndexIterator free_iter(this, err); MSQ_ERRZERO(err);
   free_iter.reset();
   while (free_iter.next())
   {
     m=free_iter.value();
     temp_vec=vertexArray[m] - memento->vertices[m];
     temp_dist=temp_vec.length_squared();
     if(temp_dist>max_dist)
     {
       max_dist=temp_dist;
     }
   }
   return max_dist;
 }
double get_max_vertex_movement_squared (PatchDataVerticesMemento * memento, MsqError & err)
Calculates the distance each vertex has moved from its original position as defined by the PatchDataVerticesMememnto.
MeshSet* get_mesh_set () inline
Returns the originating meshSet.
Definition at line 423 of file includeLinks/PatchData.hpp.
References PatchData::meshSet.
Referenced by CornerTagHandles::get_current_mesh().
       { return meshSet; }
MeshSet* get_mesh_set () inline
Returns the originating meshSet.
Definition at line 423 of file src/Mesh/PatchData.hpp.
References PatchData::meshSet.
       { return meshSet; }
void get_minmax_element_unsigned_area (double & min, double & max, MsqError & err)
Returns the maximum volume or area out of all the elements in the patch This information is stored in the patch and should not decrease performance when used properly.
See also PatchData::clear_computed_info() .
Definition at line 86 of file Mesh/PatchData.cpp.
References PatchData::computedInfos, PatchData::elementArray, PatchData::have_computed_info(), i, MsqError::INTERNAL_ERROR, max(), PatchData::MAX_UNSIGNED_AREA, min(), PatchData::MIN_UNSIGNED_AREA, Mesquite::MSQ_DBL_MAX, MSQ_ERRRTN, MSQ_SETERR, PatchData::note_have_info(), and PatchData::num_elements().
 {
   if (!have_computed_info(MAX_UNSIGNED_AREA) ||
       !have_computed_info(MIN_UNSIGNED_AREA))
   {
     max=0;
     min=MSQ_DBL_MAX;
     size_t count = num_elements();
     for (size_t i=0; i<count; ++i) {
       double vol;
       vol = elementArray[i].compute_unsigned_area(*this, err); MSQ_ERRRTN(err);
       if (vol > max)
         max = vol;
       if (vol < min)
         min = vol;
     }
     note_have_info(MAX_UNSIGNED_AREA);
     note_have_info(MIN_UNSIGNED_AREA);
     computedInfos[MAX_UNSIGNED_AREA] = max;
     computedInfos[MIN_UNSIGNED_AREA] = min;
   }
   else
   {
     max = computedInfos[MAX_UNSIGNED_AREA];
     min = computedInfos[MIN_UNSIGNED_AREA];
   }
   if (max <= 0 || min < 0 || min == MSQ_DBL_MAX)
     MSQ_SETERR(err)(MsqError::INTERNAL_ERROR);
 }
void get_minmax_element_unsigned_area (double & min, double & max, MsqError & err)
Returns the maximum volume or area out of all the elements in the patch This information is stored in the patch and should not decrease performance when used properly.
See also PatchData::clear_computed_info() .
void get_subpatch (size_t center_vertex_index, PatchData & pd_to_fill, MsqError & err)
Fills a PatchData with the elements attached to a center vertex.
Note that all entities in the sub-patch are copies of the entities in 'this' patch. As such, moving a vertex in the sub-patch won't move the corresponding vertex in the source patch. Also, calling 'update_mesh()' on the sub-patch WILL modify the TSTT mesh, but the source patch won't see the changes.
Definition at line 1008 of file Mesh/PatchData.cpp.
References PatchData::elemConnectivityArray, PatchData::elementArray, PatchData::elementHandlesArray, MsqMeshEntity::get_element_type(), PatchData::get_vertex_element_adjacencies(), MsqMeshEntity::get_vertex_index(), PatchData::initialize_data(), MsqError::INVALID_ARG, MSQ_ERRRTN, MSQ_SETERR, MsqMeshEntity::node_count(), PatchData::num_vertices(), PatchDataMem< X >::resize(), PatchData::vertexArray, and PatchData::vertexHandlesArray.
Referenced by ObjectiveFunction::compute_numerical_gradient().
 {
     // Make sure we're in range
   if (center_vertex_index >= num_vertices())
   {
     MSQ_SETERR(err)("Invalid index for center vertex",MsqError::INVALID_ARG);
     return;
   }
     // Map vertex indices from this patch data to indices in new patch data
   msq_std::map<size_t, size_t> vertex_index_map;
   size_t num_elems;
   const size_t* vertex_adjacencies;
   vertex_adjacencies = get_vertex_element_adjacencies( center_vertex_index,
                                                        num_elems, err );
   MSQ_ERRRTN(err);
     // Loop through each element, populating vertex_index_map.
   size_t which_elem, which_vert, vertex_count = 0;
   size_t vertex_uses = 0;
   for (which_elem = 0; which_elem < num_elems; ++which_elem )
   {
     size_t elem_index = vertex_adjacencies[which_elem];
     MsqMeshEntity& elem = elementArray[elem_index];
     for (which_vert = elem.node_count(); which_vert--; )
     {
       size_t vert_index = elem.get_vertex_index(which_vert);
       if (vertex_index_map.find(vert_index) != vertex_index_map.end())
         vertex_index_map[vert_index] = vertex_count++;
     }
     vertex_uses += elem.node_count();
   }
     // Allocate storage in subpatch
   subpatch.vertexHandlesArray.resize( vertex_count );
   subpatch.elementArray.resize( num_elems );
   subpatch.elementHandlesArray.resize( num_elems );
   subpatch.elemConnectivityArray.resize( vertex_uses );
     // For now, put reverse of index map into handles array (such that
     // the handles array in the subpatch contains the index in this
     // patch for each vertex.)  When PatchData::initalize_data re-orders
     // the vertices, we can then use this array to determine which vertices
     // where placed where.
   msq_std::map<size_t,size_t>::iterator iter;
   for (iter = vertex_index_map.begin(); iter != vertex_index_map.end(); ++iter)
     subpatch.vertexHandlesArray[iter->second] = (Mesh::VertexHandle)(iter->first);
     // Store elements with updated connectivity list in subpatch
   msq_std::vector<size_t> elem_conn_offsets(vertex_uses);
   size_t* elem_connectivity = &(subpatch.elemConnectivityArray[0]);
   size_t elem_conn_index = 0;
   for (which_elem = 0; which_elem < num_elems; ++which_elem)
   {
     size_t elem_index = vertex_adjacencies[which_elem];
     MsqMeshEntity& elem = elementArray[elem_index];
     elem_conn_offsets[which_elem] = elem_conn_index;
     for (which_vert = 0; which_vert < elem.node_count(); which_vert++ )
     {
       size_t vert_index = elem.get_vertex_index(which_vert);
         // Add this vertex to the new element's array
       elem_connectivity[elem_conn_index++] = vertex_index_map[vert_index];
     }
     subpatch.elementArray[which_elem].set_element_type( elem.get_element_type() );
   }
     // Re-order vertices and initialize other data in subpatch
   subpatch.initialize_data( &elem_conn_offsets[0], err ); MSQ_ERRRTN(err);
     // Copy vertex data into subpatch.  subpatch.vertexHandlesArray contains
     // the indices into this PatchData for each vertex
   subpatch.vertexArray.resize( vertex_count );
   for (which_vert = 0; which_vert < vertex_count; ++which_vert)
   {
     size_t vert_index = (size_t)(subpatch.vertexHandlesArray[which_vert]);
     subpatch.vertexHandlesArray[which_vert] = vertexHandlesArray[vert_index];
     subpatch.vertexArray[which_vert] = vertexArray[vert_index];
   }
 }
void get_subpatch (size_t center_vertex_index, PatchData & pd_to_fill, MsqError & err)
Fills a PatchData with the elements attached to a center vertex.
Note that all entities in the sub-patch are copies of the entities in 'this' patch. As such, moving a vertex in the sub-patch won't move the corresponding vertex in the source patch. Also, calling 'update_mesh()' on the sub-patch WILL modify the TSTT mesh, but the source patch won't see the changes.
const MsqVertex * get_vertex_array (MsqError & err) const inline
Returns a pointer to the start of the vertex array.
Returns an array of all vertices in the PatchData.
Definition at line 513 of file includeLinks/PatchData.hpp.
References MsqError::INVALID_STATE, MSQ_SETERR, and PatchData::vertexArray.
Referenced by TerminationCriterion::accumulate_patch(), Mesquite::centroid_smooth_mesh(), LPtoPTemplate::compute_analytical_gradient(), LPtoPTemplate::compute_analytical_hessian(), LocalSizeQualityMetric::compute_corner_area(), MsqMeshEntity::compute_corner_matrices(), LocalSizeQualityMetric::compute_corner_volume(), RI_DFT::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightMeanRatio::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightMeanRatio::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), ObjectiveFunction::compute_numerical_gradient(), MsqMeshEntity::compute_signed_area(), MsqMeshEntity::compute_signed_volume(), MsqMeshEntity::compute_unsigned_area(), MsqMeshEntity::compute_unsigned_volume(), MsqMeshEntity::compute_weighted_jacobian(), LInfTemplate::concrete_evaluate(), MaxTemplate::concrete_evaluate(), LPtoPTemplate::concrete_evaluate(), ConditionNumberQualityMetric::evaluate_element(), RI_DFT::evaluate_element(), UntangleBetaQualityMetric::evaluate_element(), IdealWeightInverseMeanRatio::evaluate_element(), IdealWeightMeanRatio::evaluate_element(), I_DFT::evaluate_element(), VertexConditionNumberQualityMetric::evaluate_vertex(), EdgeLengthQualityMetric::evaluate_vertex(), EdgeLengthRangeQualityMetric::evaluate_vertex(), MsqMeshEntity::get_centroid(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), MeshTransform::loop_over_mesh(), MsqFreeVertexIndexIterator::MsqFreeVertexIndexIterator(), SmartLaplacianSmoother::optimize_vertex_positions(), Randomize::optimize_vertex_positions(), ConjugateGradient::optimize_vertex_positions(), SteepestDescent::optimize_vertex_positions(), FeasibleNewton::optimize_vertex_positions(), NonSmoothSteepestDescent::optimize_vertex_positions(), and Randomize::randomize_vertex().
   {
     if (vertexArray.empty())
       MSQ_SETERR(err)( "No vertex array defined", MsqError::INVALID_STATE );
     return &vertexArray[0];
   }
const MsqVertex* get_vertex_array (MsqError & err) const
Returns a pointer to the start of the vertex array.
MsqVertex* get_vertex_array (MsqError & err)
MsqVertex * get_vertex_array (MsqError & err) inline
Definition at line 519 of file includeLinks/PatchData.hpp.
References MsqError::INVALID_STATE, MSQ_SETERR, and PatchData::vertexArray.
   {
     if (vertexArray.empty())
       MSQ_SETERR(err)( "No vertex array defined", MsqError::INVALID_STATE );
     return &vertexArray[0];
   }
size_t* get_vertex_element_adjacencies (size_t vertex_index, size_t & array_len_out, MsqError & err)
Get indices of elements attached to specified vertex
size_t * get_vertex_element_adjacencies (size_t vertex_index, size_t & array_len_out, MsqError & err)
Get indices of elements attached to specified vertex
Definition at line 778 of file Mesh/PatchData.cpp.
References PatchDataMem< X >::empty(), PatchData::generate_vertex_to_element_data(), PatchData::vertAdjacencyArray, and PatchData::vertAdjacencyOffsets.
Referenced by VertexConditionNumberQualityMetric::evaluate_vertex(), LocalSizeQualityMetric::evaluate_vertex(), PatchData::get_subpatch(), and MeanMidNodeMover::loop_over_mesh().
 {
     // Make sure we've got the data
   if (vertAdjacencyArray.empty())
   {
     generate_vertex_to_element_data();
   }
   const size_t begin = vertAdjacencyOffsets[vertex_index];
   const size_t end = vertAdjacencyOffsets[vertex_index+1];
   array_len_out = end - begin;
   return &vertAdjacencyArray[begin];
 }
void get_vertex_element_indices (size_t vertex_index, msq_std::vector< size_t > & elem_indices, MsqError & err)
Get the indices of the elements attached to the specified vertex.
void get_vertex_element_indices (size_t vertex_index, msq_std::vector< size_t > & elem_indices, MsqError & err)
Get the indices of the elements attached to the specified vertex.
size_t get_vertex_index (MsqVertex * vertex)
size_t get_vertex_index (MsqVertex * vertex) inline
gets the index of a vertex in the PatchData vertex array, given a pointer to the vertex.
Definition at line 596 of file includeLinks/PatchData.hpp.
References PatchData::vertexArray.
Referenced by LPtoPTemplate::compute_analytical_gradient(), QualityMetric::compute_element_gradient_expanded(), QualityMetric::compute_element_hessian(), QualityMetric::compute_element_numerical_hessian(), VertexConditionNumberQualityMetric::evaluate_vertex(), EdgeLengthQualityMetric::evaluate_vertex(), LocalSizeQualityMetric::evaluate_vertex(), EdgeLengthRangeQualityMetric::evaluate_vertex(), and Randomize::randomize_vertex().
   {
     return vertex - &vertexArray[0];
   }
bool have_computed_info (ComputedInfo info) const inline
Definition at line 118 of file includeLinks/PatchData.hpp.
References PatchData::haveComputedInfos, and cimg_library::cimg::info().
Referenced by PatchData::get_average_Lambda_3d(), PatchData::get_barrier_delta(), PatchData::get_minmax_element_unsigned_area(), and Mesquite::operator<<().
       { return 0 != (haveComputedInfos&(1<<info)); }
bool have_computed_info (ComputedInfo info) const inline
Definition at line 118 of file src/Mesh/PatchData.hpp.
References PatchData::haveComputedInfos, and cimg_library::cimg::info().
       { return 0 != (haveComputedInfos&(1<<info)); }
void initialize_data (size_t * elem_offset_array, MsqError & err)
Call after filling vertex handle and connectivity arrays to finish initializing the PatchData.
Reorders vertex handles array such that all higher-order nodes are at end of array, updates element connectivity array appropriately, initalizes numCornerVertices, and per-element vertex and node counts.
NOTE: If the patch contains higher-order elements, this function will re-order the nodes in the vertex array. Do NOT assume vertex indices are the same after calling this function!
NOTE: This function expects the following data to be initalized: vertexHandlesArray elemConnectivityArray the topology type for all elements in elementArray The function assumes the following data has not been initialized and therefore does not need to be updated: vertexArray
Parameters
elem_offset_array Offset into connectivity array for each element
void initialize_data (size_t * elem_offset_array, MsqError & err)
Call after filling vertex handle and connectivity arrays to finish initializing the PatchData.
Reorders vertex handles array such that all higher-order nodes are at end of array, updates element connectivity array appropriately, initalizes numCornerVertices, and per-element vertex and node counts.
NOTE: If the patch contains higher-order elements, this function will re-order the nodes in the vertex array. Do NOT assume vertex indices are the same after calling this function!
NOTE: This function expects the following data to be initalized: vertexHandlesArray elemConnectivityArray the topology type for all elements in elementArray The function assumes the following data has not been initialized and therefore does not need to be updated: vertexArray
Parameters
elem_offset_array Offset into connectivity array for each element
Definition at line 1354 of file Mesh/PatchData.cpp.
References PatchDataMem< X >::clear(), PatchData::clear_tag_data(), PatchData::domainHint, PatchData::elemConnectivityArray, PatchData::elementArray, MsqMeshEntity::get_vertex_index_array(), i, MsqError::INVALID_STATE, j, MSQ_SETERR, MsqMeshEntity::node_count(), PatchData::num_nodes(), PatchData::num_vertices(), PatchData::numCornerVertices, Mesquite::PLANAR_DOMAIN, PatchDataMem< X >::resize(), PatchDataMem< X >::size(), swap(), PatchData::vertAdjacencyArray, PatchData::vertAdjacencyOffsets, MsqMeshEntity::vertex_count(), PatchData::vertexHandlesArray, and PatchData::vertexNormals.
Referenced by MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), and PatchData::get_subpatch().
 {
   if (numCornerVertices)
   {
     MSQ_SETERR(err)(MsqError::INVALID_STATE);
     return;
   }
     // Clear out data specific to patch
   clear_tag_data();
   if (domainHint != PLANAR_DOMAIN)
     vertexNormals.clear();
     // Clear any vertex->element adjacency data.  It
     // is probably invalid, and certainly will be by the time
     // this function completes if the mesh contains higher-order
     // elements.
   vertAdjacencyArray.clear();
   vertAdjacencyOffsets.clear();
     // Initialize connectivity data in each element
   size_t i, j;
   bool higher_order = false;
   for (i = 0; i < elementArray.size(); ++i)
   {
     size_t start = elem_offset_array[i];
     size_t conn_len = elem_offset_array[i+1] - start;
     assert(conn_len > 0);
     elementArray[i].set_connectivity( &elemConnectivityArray[start], conn_len );
     if (conn_len != elementArray[i].vertex_count())
       higher_order = true;
   }
     // If no higher-order elements, then we're done
   if (!higher_order)
   {
       // All nodes are corner vertices
     numCornerVertices = vertexHandlesArray.size();
     return;
   }
     // Need to move higher-order nodes to end of list.
     // Use vertAdjacencyOffsets array as temporary storage.
   vertAdjacencyOffsets.resize( vertexHandlesArray.size() + 1 );
   size_t* vertex_index_map = &vertAdjacencyOffsets[0];
     // Note which are mid-nodes (1) and which are corner vertices (0)
   for (i = 0; i < elementArray.size(); ++i)
   {
     MsqMeshEntity& elem = elementArray[i];
     size_t* conn_array = elem.get_vertex_index_array();
     size_t num_vertices = elem.vertex_count();
     size_t num_nodes = elem.node_count();
     for (j = 0; j < num_vertices; ++j)
       vertex_index_map[ conn_array[j] ] = 0;
     for ( ; j < num_nodes; ++j)
       vertex_index_map[ conn_array[j] ] = 1;
   }
     // Shuffle nodes around such that all higher-order nodes
     // are at the end of the array.
     // Store new index for each node in index_map, replacing
     // flag value currently there for each node.
   i = 0;
   j = vertexHandlesArray.size() - 1;
   while (i < j)
   {
     if (!vertex_index_map[i])
     {
       // Is a corner vertex in first part of array, skip it.
       vertex_index_map[i] = i;
       ++i;
     }
     else if (vertex_index_map[j])
     {
       // Is a mid-node in latter part of array, skip it
       vertex_index_map[j] = j;
       --j;
     }
     else
     {
       // Swap mid-node from first part of array with
       // corner vertex from latter part of array.
       msq_std::swap( vertexHandlesArray[i], vertexHandlesArray[j] );
       vertex_index_map[i] = j;
       vertex_index_map[j] = i;
       ++i;
       --j;
     }
   }
     // Finish up - set numCornerVertices to indicate
     // where corner vertices end and mid-nodes begin in
     // vertexArray, and get the handle remaining vertex
     // if missed in the above loop.
   if (i > j)
   {
     numCornerVertices = i;
   }
   else // (i == j)
   {
     if (vertex_index_map[i])
       numCornerVertices = i;
     else
       numCornerVertices = i+1;
     vertex_index_map[i] = i;
   }
     // Update element connectivity data for new vertex indices
   for (i = 0; i < elemConnectivityArray.size(); ++i)
     elemConnectivityArray[i] = vertex_index_map[elemConnectivityArray[i]];
   vertAdjacencyOffsets.clear();
 }
void move_free_vertices_constrained (Vector3D dk[], size_t nb_vtx, double step_size, MsqError & err)
Moves free vertices and then snaps the free vertices to the domain.
void move_free_vertices_constrained (Vector3D dk[], size_t nb_vtx, double step_size, MsqError & err)
Moves free vertices and then snaps the free vertices to the domain.
Definition at line 580 of file Mesh/PatchData.cpp.
References MsqError::INVALID_ARG, MSQ_DBG, MSQ_DBGOUT, MSQ_ERRRTN, MSQ_SETERR, MsqFreeVertexIndexIterator::next(), PatchData::num_vertices(), MsqFreeVertexIndexIterator::reset(), PatchData::snap_vertex_to_domain(), MsqFreeVertexIndexIterator::value(), and PatchData::vertexArray.
Referenced by SteepestDescent::optimize_vertex_positions(), and FeasibleNewton::optimize_vertex_positions().
 {
   if (nb_vtx != num_vertices())
   {
     MSQ_SETERR(err)("The directional vector must be of length numVertices.",
                     MsqError::INVALID_ARG);
     return;
   }
   MsqFreeVertexIndexIterator free_iter(this, err);
   free_iter.reset();
   while (free_iter.next())
   {
     vertexArray[free_iter.value()] += (step_size * dk[free_iter.value()]);
     snap_vertex_to_domain(free_iter.value(), err);
     MSQ_ERRRTN(err);
   }
     // Checks that moving direction is zero for fixed vertices.
   if (MSQ_DBG(3)) {
   for (size_t m=0; m<num_vertices(); ++m) {
     Vector3D zero_3d(0.,0.,0.);
     if (!vertexArray[m].is_free_vertex()
      && dk[m] != zero_3d
      && dk[m] != -zero_3d )
     {
       MSQ_DBGOUT(3) << "dk["<<m<<"]: " << dk[m] << endl;
       MSQ_DBGOUT(3) << "moving a fixed vertex." << endl;
     }
   }
   }
 }
void note_have_info (ComputedInfo info) inline private
Definition at line 436 of file src/Mesh/PatchData.hpp.
References PatchData::haveComputedInfos, and cimg_library::cimg::info().
       { haveComputedInfos |= (1<<info); }
void note_have_info (ComputedInfo info) inline private
Definition at line 436 of file includeLinks/PatchData.hpp.
References PatchData::haveComputedInfos, and cimg_library::cimg::info().
Referenced by PatchData::get_average_Lambda_3d(), PatchData::get_barrier_delta(), and PatchData::get_minmax_element_unsigned_area().
       { haveComputedInfos |= (1<<info); }
size_t num_corners ()
number of elements corners in the Patch.
size_t num_corners ()
number of elements corners in the Patch.
Definition at line 1491 of file Mesh/PatchData.cpp.
References PatchData::elementArray, and i.
 {
   size_t result = 0;
   for (unsigned i = 0; i < elementArray.size(); ++i)
     result += elementArray[i].vertex_count();
   return result;
 }
size_t num_elements () const inline
number of elements in the Patch.
Definition at line 179 of file src/Mesh/PatchData.hpp.
References PatchData::elementArray.
       { return elementArray.size(); }
size_t num_elements () const inline
number of elements in the Patch.
Definition at line 179 of file includeLinks/PatchData.hpp.
References PatchData::elementArray.
Referenced by VertexMover::check_feasible(), LPtoPTemplate::compute_analytical_gradient(), LPtoPTemplate::compute_analytical_hessian(), TargetCalculator::compute_default_target_matrices(), TargetCalculator::compute_reference_corner_matrices(), WTargetCalculator::compute_target_matrices(), LVQDTargetCalculator::compute_target_matrices(), TargetCalculator::compute_target_matrices_and_check_det(), LInfTemplate::concrete_evaluate(), MaxTemplate::concrete_evaluate(), LPtoPTemplate::concrete_evaluate(), PatchData::get_barrier_delta(), PatchData::get_minmax_element_unsigned_area(), MsqHessian::initialize(), QualityAssessor::loop_over_mesh(), Mesquite::operator<<(), NonSmoothSteepestDescent::optimize_vertex_positions(), PatchData::reorder(), MeshSet::write_gnuplot(), and MeshSet::write_vtk().
       { return elementArray.size(); }
unsigned num_free_nodes (MsqError & err) const
Definition at line 470 of file Mesh/PatchData.cpp.
References i, PatchData::num_nodes(), and PatchData::vertexArray.
 {
   unsigned result = 0;
   size_t count = num_nodes();
   for (size_t i = 0; i < count; ++i)
     if (vertexArray[i].is_free_vertex())
       ++result;
   return result;
 }
unsigned num_free_nodes (MsqError & err) const
int num_free_vertices (MsqError & err) const
Returns the number of elements in the current patch who are free to move.
This is a costly function, since we have to check the flags of all vertices in the patch.
int num_free_vertices (MsqError & err) const
Returns the number of elements in the current patch who are free to move.
This is a costly function, since we have to check the flags of all vertices in the patch.
Definition at line 458 of file Mesh/PatchData.cpp.
References i, PatchData::num_vertices(), and PatchData::vertexArray.
Referenced by ConjugateGradient::optimize_vertex_positions(), SteepestDescent::optimize_vertex_positions(), FeasibleNewton::optimize_vertex_positions(), and NonSmoothSteepestDescent::optimize_vertex_positions().
 {
   int num_free_vertices=0;
   size_t count = num_vertices();
   for (size_t i = 0; i < count; ++i)
     if (vertexArray[i].is_free_vertex())
       ++num_free_vertices;
   return num_free_vertices;
 }
size_t num_nodes () const inline
Get number of nodes (vertex + higher-order nodes)
Definition at line 184 of file includeLinks/PatchData.hpp.
References PatchData::vertexArray.
Referenced by PatchData::create_vertices_memento(), PatchData::generate_vertex_to_element_data(), PatchData::initialize_data(), MeanMidNodeMover::loop_over_mesh(), PatchData::num_free_nodes(), Mesquite::operator<<(), PatchData::recreate_vertices_memento(), PatchData::set_to_vertices_memento(), MeshSet::update_mesh(), and MeshSet::write_vtk().
       { return vertexArray.size(); }
size_t num_nodes () const inline
Get number of nodes (vertex + higher-order nodes)
Definition at line 184 of file src/Mesh/PatchData.hpp.
References PatchData::vertexArray.
       { return vertexArray.size(); }
size_t num_vertices () const inline
number of vertices in the patch.
Definition at line 176 of file src/Mesh/PatchData.hpp.
References PatchData::numCornerVertices.
       { return numCornerVertices;}
size_t num_vertices () const inline
number of vertices in the patch.
Definition at line 176 of file includeLinks/PatchData.hpp.
References PatchData::numCornerVertices.
Referenced by TerminationCriterion::accumulate_inner(), TerminationCriterion::accumulate_patch(), CompositeOFMultiply::compute_analytical_gradient(), CompositeOFAdd::compute_analytical_gradient(), CompositeOFScalarMultiply::compute_analytical_gradient(), LPtoPTemplate::compute_analytical_gradient(), LPtoPTemplate::compute_analytical_hessian(), ObjectiveFunction::compute_numerical_gradient(), TargetCalculator::compute_reference_corner_matrices(), WTargetCalculator::compute_target_matrices(), LVQDTargetCalculator::compute_target_matrices(), LInfTemplate::concrete_evaluate(), MaxTemplate::concrete_evaluate(), LPtoPTemplate::concrete_evaluate(), PatchData::create_vertices_memento(), ConjugateGradient::get_step(), PatchData::get_subpatch(), MsqHessian::initialize(), PatchData::initialize_data(), MeanMidNodeMover::loop_over_mesh(), MeshTransform::loop_over_mesh(), QualityAssessor::loop_over_mesh(), PatchData::move_free_vertices_constrained(), MsqFreeVertexIndexIterator::next(), PatchData::num_free_vertices(), Mesquite::operator<<(), Randomize::optimize_vertex_positions(), ConjugateGradient::optimize_vertex_positions(), SteepestDescent::optimize_vertex_positions(), FeasibleNewton::optimize_vertex_positions(), NonSmoothSteepestDescent::optimize_vertex_positions(), PatchData::recreate_vertices_memento(), PatchData::reorder(), TerminationCriterion::reset_inner(), PatchData::set_all_vertices_soft_fixed(), PatchData::set_all_vertices_soft_free(), PatchData::set_free_vertices_constrained(), PatchData::set_free_vertices_soft_fixed(), PatchData::set_to_vertices_memento(), and PatchData::update_cached_normals().
       { return numCornerVertices;}
PatchData& operator= (const PatchData & pd) private
Doesn't allow a PatchData object to be assigned to another.
Mementos such as PatchDataVerticesMemento should be used when necessary.
PatchData& operator= (const PatchData & pd) private
Doesn't allow a PatchData object to be assigned to another.
Mementos such as PatchDataVerticesMemento should be used when necessary.
void recreate_vertices_memento (PatchDataVerticesMemento * memento, MsqError & err, bool include_higher_order = false) inline
reinstantiates a memento to holds the current state of the PatchData coordinates.
Improves memory management.
Definition at line 640 of file includeLinks/PatchData.hpp.
References PatchDataVerticesMemento::arraySize, PatchData::num_nodes(), PatchData::num_vertices(), PatchDataVerticesMemento::numVertices, PatchDataVerticesMemento::originator, PatchData::vertexArray, and PatchDataVerticesMemento::vertices.
Referenced by TerminationCriterion::accumulate_patch(), ConjugateGradient::get_step(), FeasibleNewton::optimize_vertex_positions(), TerminationCriterion::reset_inner(), and TerminationCriterion::reset_patch().
   {
     size_t num_verts = include_higher_order ? num_nodes() : num_vertices();
     memento->originator = this;
     if ( num_verts > memento->arraySize
          || num_verts < memento->arraySize/10)
     {
       delete[] memento->vertices;
         // Allocate the new array
       memento->vertices = new MsqVertex[num_verts];
       memento->arraySize = num_verts;
     }
       // Copy the coordinates
     msq_stdc::memcpy(memento->vertices, &vertexArray[0],num_verts*sizeof(MsqVertex) );
     memento->numVertices = num_verts;
   }
void recreate_vertices_memento (PatchDataVerticesMemento * memento, MsqError & err, bool include_higher_order = false)
reinstantiates a memento to holds the current state of the PatchData coordinates.
Improves memory management.
void reorder ()
Reorders the mesh data.
Physically reorder the vertices and elements in the PatchData to improve the locality of reference. This method implements a Reverse Breadth First Search order starting with the vertex furthest from the origin. Other orderings can also be implemented.
Definition at line 196 of file Mesh/PatchData.cpp.
References PatchDataMem< X >::clear(), PatchData::clear_tag_data(), PatchData::domainHint, PatchData::elementArray, PatchData::elementHandlesArray, PatchData::generate_vertex_to_element_data(), i, j, max(), PatchData::num_elements(), PatchData::num_vertices(), Mesquite::PLANAR_DOMAIN, PatchDataMem< X >::size(), PatchData::vertAdjacencyArray, PatchData::vertAdjacencyOffsets, PatchData::vertexArray, PatchData::vertexHandlesArray, and PatchData::vertexNormals.
Referenced by FeasibleNewton::initialize_mesh_iteration().
 {
   const size_t numv = num_vertices();
   const size_t nume = num_elements();
   size_t *vtx;
   size_t *tmp;
   size_t *sta = new size_t[numv + 1];
   size_t *vte;
   size_t *ord = new size_t[numv];
   size_t *per = new size_t[numv];
   size_t *pel;
   size_t *que1 = new size_t[numv];
   size_t *que2 = new size_t[numv];
   //MsqVertex *v2a;
   //Mesh::VertexHandle *v2h;
   //MsqMeshEntity *e2a;
   //Mesh::ElementHandle *e2h;
     // Copy arrays so higher-order nodes get copied
   PatchDataMem<MsqVertex> v2a( vertexArray );
   PatchDataMem<Mesh::VertexHandle> v2h( vertexHandlesArray );
   PatchDataMem<MsqMeshEntity> e2a( elementArray.size() );
   PatchDataMem<Mesh::ElementHandle> e2h( elementHandlesArray.size() );
   double val, max;
   size_t toc;
   size_t vtc;
   size_t idx;
   size_t loc;
   size_t i, j;
   size_t q1l, q2l, q;
   size_t st, en;
   // Step -1: Clear any data that will be invalidated by this
   clear_tag_data();
   // Step 0:  Make sure patch data is valid.
   // Step 1:  Find the length of the element to vertex list for each
   //          individual vertex.
   memset(sta, 0, (numv+1)*sizeof(size_t));
   for (i = 0; i < nume; ++i) {
     vtc = elementArray[i].vertex_count();
     vtx = elementArray[i].get_vertex_index_array();
     for (j = 0; j < vtc; ++j) {
       ++sta[vtx[j]];
     }
   }
   // Step 2:  Compute the offsets, total length of the element to vertex
   //          list, and allocate the data.
   toc = sta[0];
   sta[0] = 0;
   for (i = 1; i <= numv; ++i) {
     j = sta[i];
     sta[i] = toc;
     toc += j;
   }
   vte = new size_t[toc];
   // Step 3:  Finish constructing the vertex to element list.
   for (i = 0; i < nume; ++i) {
     vtc = elementArray[i].vertex_count();
     vtx = elementArray[i].get_vertex_index_array();
     for (j = 0; j < vtc; ++j) {
       vte[sta[vtx[j]]++] = i;
     }
   }
   for (i = numv; i > 0; --i) {
     sta[i] = sta[i-1];
   }
   sta[i] = 0;
   // Step 4:  Begin the reodering by computing the vertex furthest from the
   //          origin.
   max = -1.0;
   idx =  0;
   for (i = 0; i < numv; ++i) {
     val = vertexArray[i].length_squared();
     if (val > max) {
       max = val;
       idx = i+1;
     }
   }
   // Step 5:  Perform a breadth first search to find the ordering.
   memset(per, 0, numv*sizeof(size_t));
   loc = 0;
   while (idx > 0) {
     // The vertex referenced by idx has not been visited yet.  Insert it
     // into the queue for processing.
     --idx;
     q1l = 1;
     que1[0] = idx;
     per[idx] = 1;
     while (q1l) {
       q = 0;
       q2l = 0;
       while (q < q1l) {
         idx = que1[q++];
         ord[loc++] = idx;
         st = sta[idx];
         en = sta[idx+1];
         while (st < en) {
           vtc = elementArray[vte[st]].vertex_count();
           vtx = elementArray[vte[st]].get_vertex_index_array();
           ++st;
           for (j = 0; j < vtc; ++j) {
             idx = vtx[j];
             if (!per[idx]) {
               que2[q2l++] = idx;
               per[idx] = 1;
             }
           }
         }
       }
       q1l = q2l;
       tmp  = que1;
       que1 = que2;
       que2 = tmp;
     }
     if (loc >= numv) {
       break;
     }
     // The mesh is not connected.  There is another piece with some vertices
     // remaining.  Repeat the breadth-first search algorithm on the new
     // mesh component.
     max = -1.0;
     idx =  0;
     for (i = 0; i < numv; ++i) {
       if (!per[i]) {
         val = vertexArray[i].length_squared();
         if (val > max) {
           max = val;
           idx = i+1;
         }
       }
     }
   }
   delete[] que1;
   delete[] que2;
   // Step 6:  Compute the permutation vectors
   pel = new size_t[nume];
   for (i = 0; i < nume; ++i) {
     pel[i] = nume;
   }
   toc = 0;
   for (i = 0; i < numv; ++i) {
     loc = ord[numv-1-i];
     per[loc] = i;
     st = sta[loc];
     en = sta[loc+1];
     while (st < en) {
       loc = vte[st++];
       if (nume == pel[loc]) {
         pel[loc] = toc++;
       }
     }
   }
   delete[] ord;
   delete[] vte;
   delete[] sta;
   // Step 7:  Permute the vertices
   //v2a = new MsqVertex[vertexArraySize];
   //v2h = new Mesh::VertexHandle[vertexArraySize];
   for (i = 0; i < numv; ++i) {
     loc = per[i];
     v2a[loc] = vertexArray[i];
     v2h[loc] = vertexHandlesArray[i];
   }
   if (!vertexNormals.empty() && domainHint != PLANAR_DOMAIN) {
     PatchDataMem<Vector3D> v2n(numv);
     for (i = 0; i < numv; ++i) {
       loc = per[i];
       v2n[loc] = vertexNormals[i];
     }
     vertexNormals = v2n;
   }
   //delete[] vertexArray;
   //delete[] vertexHandlesArray;
   vertexArray = v2a;
   vertexHandlesArray = v2h;
   // Step 8: Permute the elements and vertex indices for the elements
   //e2a = new MsqMeshEntity[elemArraySize];
   //e2h = new Mesh::ElementHandle[elemArraySize];
   for (i = 0; i < nume; ++i) {
     vtc = elementArray[i].vertex_count();
     vtx = elementArray[i].get_vertex_index_array();
     for (j = 0; j < vtc; ++j) {
       vtx[j] = per[vtx[j]];
     }
     loc = pel[i];
     e2a[loc] = elementArray[i];
     e2h[loc] = elementHandlesArray[i];
   }
   //delete[] elementArray;
   //delete[] elementHandlesArray;
   elementArray = e2a;
   elementHandlesArray = e2h;
   // Step 9: Finish by deleting allocated memory
   delete[] per;
   delete[] pel;
   // Step 10: Recompute vertex to element mapping if it existed.
   if (vertAdjacencyOffsets.size()) {
     vertAdjacencyOffsets.clear();
     vertAdjacencyArray.clear();
     generate_vertex_to_element_data();
   }
   return;
 }
void reorder ()
Reorders the mesh data.
void set_all_vertices_soft_fixed (MsqError & err)
Add a soft_fixed flag to all vertices in the patch.
Definition at line 704 of file Mesh/PatchData.cpp.
References i, PatchData::num_vertices(), and PatchData::vertexArray.
 {
   for(size_t i=0;i<num_vertices();++i)
     vertexArray[i].set_soft_fixed_flag();
 }
void set_all_vertices_soft_fixed (MsqError & err)
Add a soft_fixed flag to all vertices in the patch.
void set_all_vertices_soft_free (MsqError & err)
Remove the soft_fixed flag from all vertices in the patch.
Definition at line 722 of file Mesh/PatchData.cpp.
References i, PatchData::num_vertices(), and PatchData::vertexArray.
Referenced by TerminationCriterion::cull_vertices().
   {
     for(size_t i=0;i<num_vertices();++i)
       vertexArray[i].remove_soft_fixed_flag();
   }
void set_all_vertices_soft_free (MsqError & err)
Remove the soft_fixed flag from all vertices in the patch.
void set_free_vertices_constrained (PatchDataVerticesMemento * memento, Vector3D dk[], size_t nb_vtx, double step_size, MsqError & err)
Moves free vertices from a memento position along a certain direction and then snaps the free vertices to the domain.
Parameters
dk an array of directions, ordered like the vertices in the PatchData.
nb_vtx number of vertices.
step_size a scalar that multiplies the vectors given in dk.
void set_free_vertices_constrained (PatchDataVerticesMemento * memento, Vector3D dk[], size_t nb_vtx, double step_size, MsqError & err)
Moves free vertices from a memento position along a certain direction and then snaps the free vertices to the domain.
Parameters
dk an array of directions, ordered like the vertices in the PatchData.
nb_vtx number of vertices.
step_size a scalar that multiplies the vectors given in dk.
set_free_vertices_constrained is similar to PatchData::move_free_vertices_constrained() except the original vertex positions are those stored in the PatchDataVerticesMemento instead of the actual vertex position stored in the PatchData Vertex array. The final location is stored in the PatchData; the PatchDataVerticesMemento is unchanged.
Parameters
dk must be a [nb_vtx] array of Vector3D that contains the direction in which to move each vertex. Fixed vertices moving direction should be zero, although fixed vertices will not be moved regardless of their corresponding dk value.
nb_vtx is the number of vertices to move. must corresponds to the number of vertices in the PatchData.
step_size will multiply the moving direction given in dk for each vertex.
Definition at line 630 of file Mesh/PatchData.cpp.
References MsqError::INVALID_ARG, MSQ_DBG, MSQ_DBGOUT, MSQ_ERRRTN, MSQ_SETERR, MsqFreeVertexIndexIterator::next(), PatchData::num_vertices(), PatchDataVerticesMemento::numVertices, MsqFreeVertexIndexIterator::reset(), PatchData::snap_vertex_to_domain(), MsqFreeVertexIndexIterator::value(), PatchData::vertexArray, and PatchDataVerticesMemento::vertices.
Referenced by ConjugateGradient::get_step().
 {
   if (nb_vtx != memento->numVertices)
   {
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     return;
   }
   size_t m=0;
   MsqFreeVertexIndexIterator free_iter(this, err);
   MSQ_ERRRTN(err);
   free_iter.reset();
   while (free_iter.next())
   {
     m=free_iter.value();
     vertexArray[m] = memento->vertices[m] + (step_size * dk[m]);
     snap_vertex_to_domain(m, err);
     MSQ_ERRRTN(err);
   }
     // Checks that moving direction is zero for fixed vertices.
   if (MSQ_DBG(3)) {
   for (m=0; m<num_vertices(); ++m)
   {
     Vector3D zero_3d(0.,0.,0.);
     if (   ! vertexArray[m].is_free_vertex()
            && ( dk[m] != zero_3d && dk[m] != -zero_3d)  )
     {
       MSQ_DBGOUT(3) << "dk["<<m<<"]: " << dk[m] << endl;
       MSQ_DBGOUT(3) <<"moving a fixed vertex." << endl;
     }
   }
   }
 }
void set_free_vertices_soft_fixed (MsqError & err)
Add a soft_fixed flag to all free vertices in the patch.
void set_free_vertices_soft_fixed (MsqError & err)
Add a soft_fixed flag to all free vertices in the patch.
Definition at line 712 of file Mesh/PatchData.cpp.
References i, PatchData::num_vertices(), and PatchData::vertexArray.
Referenced by TerminationCriterion::cull_vertices().
 {
   for(size_t i=0;i<num_vertices();++i){
     if(vertexArray[i].is_free_vertex())
       vertexArray[i].set_soft_fixed_flag();
   }
 }
void set_mesh_set (MeshSet * ms)
Sets the originating meshSet.
This is normally done in MeshSet::get_next_patch(). This function is only for tests purposes.
Definition at line 1266 of file Mesh/PatchData.cpp.
References PatchData::domainSet, MeshSet::get_domain_constraint(), and PatchData::meshSet.
 { meshSet = ms;
   if (ms->get_domain_constraint()!=NULL) domainSet = true; }
void set_mesh_set (MeshSet * ms)
Sets the originating meshSet.
This is normally done in MeshSet::get_next_patch(). This function is only for tests purposes.
void set_to_vertices_memento (PatchDataVerticesMemento * memento, MsqError & err) inline
Restore the PatchData coordinates to the state contained in the memento.
This function restores a PatchData object coordinates to a previous state hold in a PatchDataVerticesMemento object (see create_vertices_memento()).
The function checks whether the memento originates from this particular PatchData object. The function does not destroy the memento object: this is the caller responsibility.
Definition at line 669 of file includeLinks/PatchData.hpp.
References MsqError::INVALID_ARG, MsqError::INVALID_STATE, MSQ_SETERR, PatchData::num_nodes(), PatchData::num_vertices(), PatchDataVerticesMemento::numVertices, PatchDataVerticesMemento::originator, PatchData::vertexArray, and PatchDataVerticesMemento::vertices.
Referenced by ConjugateGradient::get_step(), SteepestDescent::optimize_vertex_positions(), and FeasibleNewton::optimize_vertex_positions().
   {
     if (memento->originator != this)
     {
       MSQ_SETERR(err)("Memento may only be used to restore the PatchData "
                       "object from which it was created.",
                       MsqError::INVALID_ARG);
       return;
     }
     if (memento->numVertices != num_vertices() &&
         memento->numVertices != num_nodes())
     {
       MSQ_SETERR(err)("Unable to restore patch coordinates.  Number of "
                       "vertices in PatchData has changed.",
                       MsqError::INVALID_STATE);
       return;
     }
       // copies the memento array into the PatchData array.
     msq_stdc::memcpy(&vertexArray[0], memento->vertices, memento->numVertices*sizeof(MsqVertex) );
   }
void set_to_vertices_memento (PatchDataVerticesMemento * memento, MsqError & err)
Restore the PatchData coordinates to the state contained in the memento.
void set_vertex_coordinates (const Vector3D & coords, size_t index, MsqError & err)
void set_vertex_coordinates (const Vector3D & coords, size_t index, MsqError & err) inline
set the coordinates of a vertex in the raw array
Definition at line 547 of file includeLinks/PatchData.hpp.
References MsqError::INVALID_ARG, MSQ_SETERR, and PatchData::vertexArray.
Referenced by MeanMidNodeMover::loop_over_mesh().
   {
     if (index >= vertexArray.size()) {
       MSQ_SETERR(err)( "Index bigger than numVertices.", MsqError::INVALID_ARG );
       return;
     }
     vertexArray[index] = coords;
   }
void snap_vertex_to_domain (size_t vertex_index, MsqError & err)
Adjust the position of the specified vertex so that it lies on its constraining domain. The actual domain constraint is managed by the MeshSet's MeshDomain object.
void snap_vertex_to_domain (size_t vertex_index, MsqError & err)
Adjust the position of the specified vertex so that it lies on its constraining domain.
Adjust the position of the specified vertex so that it lies on its constraining domain. The actual domain constraint is managed by the MeshSet's MeshDomain object.
The actual domain constraint is managed by the TSTT mesh implementation
Definition at line 1095 of file Mesh/PatchData.cpp.
References MeshDomain::closest_point(), PatchData::domainHint, MeshSet::get_domain_constraint(), PatchData::meshSet, MSQ_ERRRTN, Mesquite::SMOOTH_DOMAIN, MeshDomain::snap_to(), PatchData::vertexArray, PatchData::vertexHandlesArray, and PatchData::vertexNormals.
Referenced by MeanMidNodeMover::loop_over_mesh(), PatchData::move_free_vertices_constrained(), SmartLaplacianSmoother::optimize_vertex_positions(), LaplacianSmoother::optimize_vertex_positions(), Randomize::optimize_vertex_positions(), ConjugateGradient::optimize_vertex_positions(), and PatchData::set_free_vertices_constrained().
 {
   if (meshSet && meshSet->get_domain_constraint())
   {
     if (domainHint == SMOOTH_DOMAIN && !vertexNormals.empty())
     {
       meshSet->get_domain_constraint()->closest_point(
                                           vertexHandlesArray[vertex_index],
                                           Vector3D(vertexArray[vertex_index]),
                                           vertexArray[vertex_index],
                                           vertexNormals[vertex_index],
                                           err ); MSQ_ERRRTN(err);
     }
     else
     {
       meshSet->get_domain_constraint()->snap_to(vertexHandlesArray[vertex_index],
                                                 vertexArray[vertex_index]);
     }
   }
 }
PatchType type () const inline
Definition at line 415 of file src/Mesh/PatchData.hpp.
References PatchData::mType.
       { return mType; }
PatchType type () const inline
Definition at line 415 of file includeLinks/PatchData.hpp.
References PatchData::mType.
Referenced by MeshSet::update_mesh().
       { return mType; }
void update_cached_normals (MsqError & err) private
Definition at line 1151 of file Mesh/PatchData.cpp.
References PatchData::domainHint, PatchData::elementHandlesArray, MeshSet::get_domain_constraint(), i, MsqError::INVALID_STATE, PatchData::meshSet, MSQ_SETERR, nvc::norm(), MeshDomain::normal_at(), PatchData::num_vertices(), Mesquite::PLANAR_DOMAIN, PatchData::vertex_by_index(), PatchData::vertexArray, PatchData::vertexHandlesArray, and PatchData::vertexNormals.
Referenced by PatchData::get_domain_normal_at_vertex(), and PatchData::get_domain_normals_at_corners().
 {
   MeshDomain* domain = meshSet ? meshSet->get_domain_constraint() : 0;
   if (!domain)
   {
     MSQ_SETERR(err)( "No domain constraint set.", MsqError::INVALID_STATE );
     vertexNormals.clear();
     return;
   }
   if (domainHint == PLANAR_DOMAIN)
   {
     vertexNormals.resize(1);
     vertexNormals[0] = vertex_by_index(0);
     domain->normal_at( elementHandlesArray[0], vertexNormals[0] );
   }
   else
   {
     vertexNormals.resize( num_vertices() );
     for ( unsigned i = 0; i < num_vertices(); ++i)
     {
       Vector3D& norm = vertexNormals[i];
       norm = vertexArray[i];
       domain->normal_at( vertexHandlesArray[i], norm );
       //norm.normalize();
       //if (!finite(norm.x()) || !finite(norm.y()) || !finite(norm.z()))
       //  norm.set(0,0,0);
     }
   }
 }
void update_cached_normals (MsqError &) private
void update_mesh (MsqError & err)
Updates the underlying mesh (the Mesquite::Mesh implementation) with new node coordinates and flag values.
This function copies to the TSTT mesh the changes made to the free vertices / elements of the PatchData object.
Definition at line 935 of file Mesh/PatchData.cpp.
References PatchData::meshSet, MSQ_CHKERR, and MeshSet::update_mesh().
Referenced by MeanMidNodeMover::loop_over_mesh(), VertexMover::loop_over_mesh(), and MeshTransform::loop_over_mesh().
 {
   if (!meshSet)
     return;
   meshSet->update_mesh(*this, err);
   MSQ_CHKERR(err);
 }
void update_mesh (MsqError & err)
Updates the underlying mesh (the Mesquite::Mesh implementation) with new node coordinates and flag values.
MsqVertex& vertex_by_index (size_t index)
Returns the start of the vertex->element array.
For each vertex in the patch, this array holds the number of elements the vertex is attached to, followed by the indices of those elements. Returns the start of the vertex->element offset array (v2e_o). For vertex i, v2e_o[i] is the index into the vertex->element array (v2e) where vertex i's data begins. So, v2e[v2e_o[i]] gives you the number of elements vertex i is attached to, and v2e[v2e_o[i]+1] gives you the index of the first element attached to vertex i.
MsqVertex & vertex_by_index (size_t index) inline
Returns the start of the vertex->element array.
For each vertex in the patch, this array holds the number of elements the vertex is attached to, followed by the indices of those elements. Returns the start of the vertex->element offset array (v2e_o). For vertex i, v2e_o[i] is the index into the vertex->element array (v2e) where vertex i's data begins. So, v2e[v2e_o[i]] gives you the number of elements vertex i is attached to, and v2e[v2e_o[i]+1] gives you the index of the first element attached to vertex i.
Definition at line 584 of file includeLinks/PatchData.hpp.
References PatchData::vertexArray.
Referenced by MsqMeshEntity::compute_corner_normals(), MeanMidNodeMover::loop_over_mesh(), QualityAssessor::loop_over_mesh(), and PatchData::update_cached_normals().
   {
     return vertexArray[index];
   }
Friends And Related Function Documentation
MeshSet friend
Definition at line 441 of file includeLinks/PatchData.hpp.
msq_stdio::ostream& operator<< (msq_stdio::ostream & , const PatchData &) friend
Display the coordinates and connectivity information.
msq_stdio::ostream& operator<< (msq_stdio::ostream & , const PatchData &) friend
Display the coordinates and connectivity information.
Member Data Documentation
double computedInfos private
Definition at line 459 of file includeLinks/PatchData.hpp.
Referenced by PatchData::get_average_Lambda_3d(), PatchData::get_barrier_delta(), PatchData::get_minmax_element_unsigned_area(), and Mesquite::operator<<().
DomainHint domainHint private
Definition at line 445 of file includeLinks/PatchData.hpp.
Referenced by PatchData::get_domain_normal_at_vertex(), PatchData::get_domain_normals_at_corners(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), PatchData::initialize_data(), PatchData::reorder(), PatchData::snap_vertex_to_domain(), and PatchData::update_cached_normals().
bool domainSet private
Definition at line 444 of file includeLinks/PatchData.hpp.
Referenced by PatchData::domain_set(), MeshSet::get_next_patch(), Mesquite::operator<<(), and PatchData::set_mesh_set().
PatchDataMem< size_t > elemConnectivityArray private
Definition at line 452 of file includeLinks/PatchData.hpp.
Referenced by PatchData::allocate_storage(), PatchData::clear(), PatchData::generate_vertex_to_element_data(), PatchData::get_connectivity_array(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), PatchData::get_subpatch(), and PatchData::initialize_data().
PatchDataMem< MsqMeshEntity > elementArray private
Definition at line 450 of file includeLinks/PatchData.hpp.
Referenced by PatchData::allocate_storage(), PatchData::clear(), PatchData::element_by_index(), PatchData::generate_vertex_to_element_data(), PatchData::get_average_Lambda_3d(), PatchData::get_barrier_delta(), PatchData::get_domain_normal_at_element(), PatchData::get_domain_normals_at_corners(), PatchData::get_element_array(), PatchData::get_element_index(), PatchData::get_minmax_element_unsigned_area(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), PatchData::get_subpatch(), PatchData::initialize_data(), PatchData::num_corners(), PatchData::num_elements(), Mesquite::operator<<(), PatchData::reorder(), MeshSet::write_gnuplot(), and MeshSet::write_vtk().
PatchDataMem< Mesh::ElementHandle > elementHandlesArray private
Definition at line 451 of file includeLinks/PatchData.hpp.
Referenced by PatchData::allocate_storage(), PatchData::clear(), PatchData::get_domain_normal_at_element(), PatchData::get_domain_normals_at_corners(), PatchData::get_element_handles_array(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), PatchData::get_subpatch(), PatchData::reorder(), and PatchData::update_cached_normals().
unsigned haveComputedInfos private
Definition at line 460 of file includeLinks/PatchData.hpp.
Referenced by PatchData::clear(), PatchData::clear_computed_info(), PatchData::have_computed_info(), PatchData::note_have_info(), and Mesquite::operator<<().
MeshSet * meshSet private
Definition at line 443 of file includeLinks/PatchData.hpp.
Referenced by PatchData::clear(), PatchData::get_domain_normal_at_element(), PatchData::get_domain_normal_at_vertex(), PatchData::get_domain_normals_at_corners(), PatchData::get_mesh_set(), MeshSet::get_next_patch(), Mesquite::operator<<(), PatchData::set_mesh_set(), PatchData::snap_vertex_to_domain(), PatchData::update_cached_normals(), and PatchData::update_mesh().
PatchType mType private
Definition at line 446 of file includeLinks/PatchData.hpp.
Referenced by MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), Mesquite::operator<<(), and PatchData::type().
size_t numCornerVertices private
Definition at line 456 of file includeLinks/PatchData.hpp.
Referenced by PatchData::allocate_storage(), PatchData::clear(), PatchData::initialize_data(), and PatchData::num_vertices().
CornerTag< TargetMatrix > targetMatrices
Target matrix data.
Definition at line 427 of file includeLinks/PatchData.hpp.
Referenced by PatchData::clear_tag_data(), TargetCalculator::compute_default_target_matrices(), RI_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), TargetCalculator::compute_reference_corner_matrices(), DistanceFromTarget::compute_T_matrices(), WTargetCalculator::compute_target_matrices(), LVQDTargetCalculator::compute_target_matrices(), TargetCalculator::compute_target_matrices_and_check_det(), RI_DFT::evaluate_element(), and I_DFT::evaluate_element().
PatchDataMem< size_t > vertAdjacencyArray private
Definition at line 453 of file includeLinks/PatchData.hpp.
Referenced by PatchData::clear(), PatchData::generate_vertex_to_element_data(), PatchData::get_vertex_element_adjacencies(), PatchData::initialize_data(), Mesquite::operator<<(), and PatchData::reorder().
PatchDataMem< size_t > vertAdjacencyOffsets private
Definition at line 454 of file includeLinks/PatchData.hpp.
Referenced by PatchData::clear(), PatchData::generate_vertex_to_element_data(), PatchData::get_vertex_element_adjacencies(), PatchData::initialize_data(), Mesquite::operator<<(), and PatchData::reorder().
PatchDataMem< MsqVertex > vertexArray private
Definition at line 448 of file includeLinks/PatchData.hpp.
Referenced by PatchData::allocate_storage(), PatchData::clear(), PatchData::create_vertices_memento(), PatchData::get_domain_normal_at_vertex(), PatchData::get_domain_normals_at_corners(), PatchData::get_max_vertex_movement_squared(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), PatchData::get_subpatch(), PatchData::get_vertex_array(), PatchData::get_vertex_index(), PatchData::move_free_vertices_constrained(), PatchData::num_free_nodes(), PatchData::num_free_vertices(), PatchData::num_nodes(), Mesquite::operator<<(), PatchData::recreate_vertices_memento(), PatchData::reorder(), PatchData::set_all_vertices_soft_fixed(), PatchData::set_all_vertices_soft_free(), PatchData::set_free_vertices_constrained(), PatchData::set_free_vertices_soft_fixed(), PatchData::set_to_vertices_memento(), PatchData::set_vertex_coordinates(), PatchData::snap_vertex_to_domain(), PatchData::update_cached_normals(), MeshSet::update_mesh(), PatchData::vertex_by_index(), MeshSet::write_gnuplot(), and MeshSet::write_vtk().
PatchDataMem< Mesh::VertexHandle > vertexHandlesArray private
Definition at line 449 of file includeLinks/PatchData.hpp.
Referenced by PatchData::allocate_storage(), PatchData::clear(), PatchData::get_domain_normal_at_vertex(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), PatchData::get_subpatch(), PatchData::initialize_data(), PatchData::reorder(), PatchData::snap_vertex_to_domain(), PatchData::update_cached_normals(), and MeshSet::update_mesh().
PatchDataMem< Vector3D > vertexNormals private
Definition at line 455 of file includeLinks/PatchData.hpp.
Referenced by PatchData::clear(), PatchData::get_domain_normal_at_vertex(), PatchData::get_domain_normals_at_corners(), PatchData::initialize_data(), PatchData::reorder(), PatchData::snap_vertex_to_domain(), and PatchData::update_cached_normals().
The documentation for this class was generated from the following files:
includeLinks/PatchData.hpp
Mesh/PatchData.cpp