Rocstar: tpz_fequad Class Reference
tpz_fequad Class Reference
#include <partition.h>
Public Member Functions
tpz_fequad (string *zheader, string *zdata)
void build_point_index ()
~tpz_fequad ()
virtual void parse_layout ()
virtual bool parse_data (int num_dep_vars, int num_vars, std::vector< std::vector< int > > rFieldMappings, index_order rIndexOrder, std::vector< adj_map > conv_factor, std::vector< adj_map > norm_val)
Public Member Functions inherited from tpzone
tpzone (string *zheader, string *zdata)
virtual ~tpzone ()
Public Member Functions inherited from partition
partition ()
virtual ~partition ()
std::vector< int > get_layout ()
string get_error ()
string get_status ()
int get_num_points ()
points * get_points ()
pnt get_point (int n)
Private Attributes
connect_points * data_pts_local
Additional Inherited Members
Protected Member Functions inherited from partition
long double get_adj (std::vector< adj_map > adj, int var)
int GetFieldMapping (std::vector< std::vector< int > > rFieldMapping, int rSearchField)
Protected Attributes inherited from tpzone
string * zheader
string * zdata
Protected Attributes inherited from partition
std::vector< int > p_layout
string error
string status
points * data_pts
bool data_pts_set
Detailed Description
Definition at line 103 of file partition.h.
Constructor & Destructor Documentation
tpz_fequad (string * zheader, string * zdata)
Definition at line 346 of file partition.cpp.
References partition::data_pts, data_pts_local, and partition::data_pts_set.
                                                      : tpzone(zheader, zdata){
     data_pts_local = new connect_points;
     data_pts = data_pts_local;
     data_pts_set = true;
 }
~tpz_fequad ()
Definition at line 353 of file partition.cpp.
{
     return;
 }
Member Function Documentation
void build_point_index ()
bool parse_data (int num_dep_vars, int num_vars, std::vector< std::vector< int > > rFieldMappings, index_order rIndexOrder, std::vector< adj_map > conv_factor, std::vector< adj_map > norm_val) virtual
Reimplemented from partition.
Definition at line 398 of file partition.cpp.
References partition::data_pts, data_pts_local, partition::get_adj(), partition::GetFieldMapping(), i, itoa(), Mesquite::length(), nvc::norm(), partition::p_layout, read(), connect_points::set_connectivity(), points::set_num_indep_vars(), points::set_num_points(), points::set_num_vars(), points::set_point_val(), partition::status, and tpzone::zdata.
{
     std::stringstream data(std::stringstream::in | std::stringstream::out);
     data << *zdata;
     int length = 1;
     for(int i=0; i < (num_vars - num_dep_vars); i++){
         if(i >= p_layout.size())
             break;
         length *= p_layout[i];
     }
     //Initialize storage
     data_pts->set_num_points(length);
     data_pts->set_num_vars(num_vars);
     data_pts->set_num_indep_vars(num_vars - num_dep_vars);
     //Read Data
     string out;
     for(int n=0; n<num_vars; n++){
         long double conv = get_adj(conv_factor, n);
         long double norm = get_adj(norm_val, n);
         //Get variable number from mapping
         int var_location = GetFieldMapping(rFieldMappings, n);
         for(int i=0; i<length; i++){
             data >> out;
             //Skip saving the point if the dimension is mapped to null
             if(var_location < 0)
                 continue;
             long double read = strtold(out.c_str(), NULL);
             //Apply conversion and normalization factors
             read = read * conv * norm;
             //Store point value
             data_pts->set_point_val(i, var_location, read);
         }
     }
     //Read Connectivity Information
     int first, sec, third, fourth;
     first = 0;
     sec = 0;
     third = 0;
     fourth = 0;
     //Read 4 values
     data >> first >> sec >> third >> fourth;
     while(!data.eof()){
         data_pts_local->set_connectivity(first, sec);
         data_pts_local->set_connectivity(first, fourth);
         data_pts_local->set_connectivity(sec, third);
         data_pts_local->set_connectivity(sec, first);
         data_pts_local->set_connectivity(third, fourth);
         data_pts_local->set_connectivity(third, sec);
         data_pts_local->set_connectivity(fourth, first);
         data_pts_local->set_connectivity(fourth, third);
         first = 0;
         sec = 0;
         third = 0;
         fourth = 0;
         data >> first >> sec >> third >> fourth;
     }
     //Set Status
     string zs_out("Extracted ");
     zs_out += itoa(length) + " datapoints";
     status = zs_out;
     return true;
 }
void parse_layout () virtual
Reimplemented from partition.
Definition at line 357 of file partition.cpp.
References check_non_numeric_str(), partition::error, itoa(), partition::p_layout, readCommaExpression(), partition::status, and tpzone::zheader.
{
     int nodes = 0;
     int elements = 0;
     //Parse number of nodes
     std::vector<string> nodes_str = readCommaExpression( *zheader, string("Nodes") );
     if(nodes_str.size() == 1){
         if( !check_non_numeric_str(string(nodes_str[0])) )
             nodes = atoi(nodes_str[0].c_str());
     }
     else{
         error = string("Unable to read Nodes value from zone header");
         return;
     }
     //Parse number of elements
     std::vector<string> elements_str = readCommaExpression( *zheader, string("Elements") );
     if(elements_str.size() == 1){
         if( !check_non_numeric_str(string(elements_str[0])) )
             elements = atoi(elements_str[0].c_str());
     }
     else{
         error = string("Unable to read Elements value from zone header");
         return;
     }
     //Set Status
     status = string("Nodes = ") + itoa(nodes) + string(", Elements = ") + itoa(elements);
     p_layout.erase(p_layout.begin(), p_layout.end());
     p_layout.push_back(nodes);
 }
Member Data Documentation
connect_points* data_pts_local private
Definition at line 119 of file partition.h.
Referenced by parse_data(), and tpz_fequad().
The documentation for this class was generated from the following files:
partition.h
partition.cpp