Rocstar: Line_3< R, T > Class Template Reference
Line_3< R, T > Class Template Reference
#include <cartesian_classes.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Line_3_base RLine_3
Public Member Functions
Line_3 ()
Line_3 (const CGAL::Line_3< R > &l)
Line_3 (const CGAL::Point_3< R > &p, const CGAL::Point_3< R > &q)
Line_3 (const RLine_3 &l)
Line_3 (const CGAL::Segment_3< R > &s)
Line_3 (const CGAL::Ray_3< R > &r)
Line_3 (const CGAL::Point_3< R > &p, const CGAL::Direction_3< R > &d)
bool operator== (const CGAL::Line_3< R > &l) const
bool operator!= (const CGAL::Line_3< R > &l) const
CGAL::Plane_3< R > perpendicular_plane (const CGAL::Point_3< R > &p) const
CGAL::Line_3< R > opposite () const
CGAL::Point_3< R > point () const
CGAL::Point_3< R > point (int i) const
CGAL::Point_3< R > projection (const CGAL::Point_3< R > &p) const
CGAL::Direction_3< R > direction () const
bool has_on (const CGAL::Point_3< R > &p) const
bool is_degenerate () const
CGAL::Line_3< R > transform (const CGAL::Aff_transformation_3< R > &t) const
Detailed Description
template<class R, class T = typename R::Rep_tag>
class Line_3< R, T >
Definition at line 81 of file cartesian_classes.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 94 of file Line_3.h.
typedef R_ R
Definition at line 92 of file Line_3.h.
typedef R::Line_3_base RLine_3
Definition at line 95 of file Line_3.h.
typedef R::RT RT
Definition at line 93 of file Line_3.h.
Constructor & Destructor Documentation
Line_3 () inline
Definition at line 97 of file Line_3.h.
            : RLine_3()
   {}
Line_3 (const CGAL::Line_3< R > & l) inline
Definition at line 99 of file Line_3.h.
                                    : RLine_3( ( const RLine_3&  )l)
   {}
Line_3 (const CGAL::Point_3< R > & p, const CGAL::Point_3< R > & q) inline
Definition at line 101 of file Line_3.h.
                                         : RLine_3(p,q)
   {}
Line_3 (const RLine_3< R, T > & l) inline
Definition at line 105 of file Line_3.h.
                             : RLine_3(l)
   {}
Line_3 (const CGAL::Segment_3< R > & s) inline
Definition at line 107 of file Line_3.h.
                                      : RLine_3( s )
   {}
Line_3 (const CGAL::Ray_3< R > & r) inline
Definition at line 109 of file Line_3.h.
                                  : RLine_3( r )
   {}
Line_3 (const CGAL::Point_3< R > & p, const CGAL::Direction_3< R > & d) inline
Definition at line 111 of file Line_3.h.
                                             : RLine_3( p, d )
   {}
Member Function Documentation
CGAL::Direction_3<R> direction () const inline
Definition at line 136 of file Line_3.h.
   { return RLine_3::direction(); }
bool has_on (const CGAL::Point_3< R > & p) const inline
Definition at line 139 of file Line_3.h.
   { return RLine_3::has_on(p); }
bool is_degenerate () const inline
Definition at line 142 of file Line_3.h.
   { return RLine_3::is_degenerate(); }
bool operator!= (const CGAL::Line_3< R > & l) const inline
Definition at line 118 of file Line_3.h.
   { return !(*this == l); }
bool operator== (const CGAL::Line_3< R > & l) const inline
Definition at line 115 of file Line_3.h.
References operator==().
   { return RLine_3::operator==(l); }
CGAL::Line_3<R> opposite () const inline
Definition at line 124 of file Line_3.h.
References opposite().
   { return RLine_3::opposite(); }
CGAL::Plane_3<R> perpendicular_plane (const CGAL::Point_3< R > & p) const inline
Definition at line 121 of file Line_3.h.
   { return RLine_3::perpendicular_plane(p); }
CGAL::Point_3<R> point () const inline
Definition at line 127 of file Line_3.h.
   { return RLine_3::point(); }
CGAL::Point_3<R> point (int i) const inline
Definition at line 130 of file Line_3.h.
   { return RLine_3::point(i); }
CGAL::Point_3<R> projection (const CGAL::Point_3< R > & p) const inline
Definition at line 133 of file Line_3.h.
References projection().
   { return RLine_3::projection(p); }
CGAL::Line_3<R> transform (const CGAL::Aff_transformation_3< R > & t) const inline
Definition at line 145 of file Line_3.h.
   { return RLine_3::transform(t); }
The documentation for this class was generated from the following files:
cartesian_classes.h
Line_3.h