Rocstar: rflu_modhashtable Module Reference
rflu_modhashtable Module Reference
Public Member Functions
subroutine, public rflu_createhashtable (global, size)
subroutine, public rflu_destroyhashtable (global)
subroutine, public rflu_hashbuildkey (a, aSize, key)
subroutine rflu_hashbuildkey1 (a, key)
subroutine, public rflu_hashedge (global, key, pGrid, v, edgeType)
subroutine, public rflu_hashface (global, key, pGrid, icg, ifl, fv, nVert, faceType)
subroutine, public rflu_hashvertex (global, key, ivg, nVert, vert, errorFlag)
subroutine, public rflu_hashvertexfancy (global, key, ivg, nVert, vert, indx, ivgStat, ivgIndx)
subroutine, public rflu_unhashbface (global, key, pGrid, fv, nVert, bcType, icg, ifg)
Public Attributes
integer, parameter, public hashtable_entrystatus_old = 0
integer, parameter, public hashtable_entrystatus_new = 1
integer, public hashtablecollisions
integer, public hashtablesize
integer, dimension(:),
allocatable, public hashtable
Private Member Functions
subroutine, private rflu_findnearestprime (size, primeSize)
subroutine, private rflu_hashfuncprimary (key, addr)
subroutine, private rflu_hashfuncsecondary (key, addr)
Private Attributes
integer, parameter, private hashtable_init = 0
integer, parameter, private nprimes = 48
integer, dimension(nprimes),
private primenumbers = (/ 1, 251, 379, 509, 761, 1021, 1531, 2039, 3067, 4093, 6143, 8191, 12289, 16381, 24571, 32749, 49139, 65521, 98297, 131071, 196613, 262139, 393209, 524287, 786431, 1048573, 1572853, 2097143, 3145721, 4194301, 6291449, 8388593, 12582917, 16777213, 25165807, 33554393, 50331599, 67108859, 100663261, 134217689, 201326549, 268435399, 402653171, 536870909, 805306349, 1073741789, 1610612711, 2147483647 /)
Detailed Description
Definition at line 44 of file RFLU_ModHashTable.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_createhashtable (type(t_global), pointer global, integer, intent(in) size)
Definition at line 131 of file RFLU_ModHashTable.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_findnearestprime().
Referenced by rflu_modboundlists::rflu_buildbvertexlists(), rflu_modtopologyutils::rflu_buildcellvertlist(), rflu_modtopologyutils::rflu_buildconnvertlist(), rflu_modedgelist::rflu_buildedgelist(), rflu_modfacelist::rflu_buildfacelist(), rflu_modtopologyutils::rflu_buildfacevertlist(), and rflu_modpartitionregion::rflu_part_buildvertexlists().
subroutine, public rflu_destroyhashtable (type(t_global), pointer global)
Definition at line 210 of file RFLU_ModHashTable.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modboundlists::rflu_buildbvertexlists(), rflu_modtopologyutils::rflu_buildcellvertlist(), rflu_modtopologyutils::rflu_buildconnvertlist(), rflu_modedgelist::rflu_buildedgelist(), rflu_modfacelist::rflu_buildfacelist(), rflu_modtopologyutils::rflu_buildfacevertlist(), and rflu_modpartitionregion::rflu_part_buildvertexlists().
subroutine, private rflu_findnearestprime (integer, intent(in) size, integer, intent(out) primeSize) private
Definition at line 279 of file RFLU_ModHashTable.F90.
References i.
Referenced by rflu_createhashtable().
subroutine, public rflu_hashbuildkey (integer, dimension(1:asize), intent(in) a, integer, intent(in) aSize, integer, intent(out) key)
Definition at line 339 of file RFLU_ModHashTable.F90.
References Line_2< R, T >::a(), i, key, and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_modtopologyutils::rflu_buildcellvertlist(), rflu_modtopologyutils::rflu_buildconnvertlist(), rflu_modedgelist::rflu_buildedgelist(), rflu_modfacelist::rflu_buildfacelist(), rflu_modtopologyutils::rflu_buildfacevertlist(), and rflu_modpartitionregion::rflu_part_buildvertexlists().
subroutine rflu_hashbuildkey1 (integer, intent(in) a, integer, intent(out) key)
Definition at line 416 of file RFLU_ModHashTable.F90.
References Line_2< R, T >::a(), and key.
Referenced by rflu_modboundlists::rflu_buildbvertexlists().
subroutine, public rflu_hashedge (type(t_global), pointer global, integer, intent(in) key, type(t_grid), pointer pGrid, integer, dimension(1:2), intent(in) v, integer, intent(out) edgeType)
Definition at line 474 of file RFLU_ModHashTable.F90.
References Node::addr(), moderror::deregisterfunction(), moderror::errorstop(), key, moderror::registerfunction(), rflu_hashfuncprimary(), rflu_hashfuncsecondary(), and v.
Referenced by rflu_modedgelist::rflu_buildedgelist().
subroutine, public rflu_hashface (type(t_global), pointer global, integer, intent(in) key, type(t_grid), pointer pGrid, integer, intent(in) icg, integer, intent(in) ifl, integer, dimension(1:3), intent(in) fv, integer, intent(in) nVert, integer, intent(out) faceType)
Definition at line 591 of file RFLU_ModHashTable.F90.
References Node::addr(), moderror::deregisterfunction(), moderror::errorstop(), key, Mesh::GenericCell_2::nvert(), moderror::registerfunction(), rflu_hashfuncprimary(), and rflu_hashfuncsecondary().
Referenced by rflu_modfacelist::rflu_buildfacelist().
subroutine, private rflu_hashfuncprimary (integer, intent(in) key, integer, intent(out) addr) private
Definition at line 732 of file RFLU_ModHashTable.F90.
References Node::addr(), and key.
Referenced by rflu_hashedge(), rflu_hashface(), rflu_hashvertex(), rflu_hashvertexfancy(), and rflu_unhashbface().
subroutine, private rflu_hashfuncsecondary (integer, intent(in) key, integer, intent(out) addr) private
Definition at line 782 of file RFLU_ModHashTable.F90.
References Node::addr(), and key.
Referenced by rflu_hashedge(), rflu_hashface(), rflu_hashvertex(), rflu_hashvertexfancy(), and rflu_unhashbface().
subroutine, public rflu_hashvertex (type(t_global), pointer global, integer, intent(in) key, integer, intent(in) ivg, integer, intent(inout) nVert, integer, dimension(:), intent(inout) vert, integer, intent(out), optional errorFlag)
Definition at line 838 of file RFLU_ModHashTable.F90.
References Node::addr(), moderror::deregisterfunction(), moderror::errorstop(), key, Mesh::GenericCell_2::nvert(), moderror::registerfunction(), rflu_hashfuncprimary(), and rflu_hashfuncsecondary().
Referenced by rflu_modboundlists::rflu_buildbvertexlists(), rflu_modtopologyutils::rflu_buildcellvertlist(), rflu_modtopologyutils::rflu_buildconnvertlist(), and rflu_modtopologyutils::rflu_buildfacevertlist().
subroutine, public rflu_hashvertexfancy (type(t_global), pointer global, integer, intent(in) key, integer, intent(in) ivg, integer, intent(inout) nVert, integer, dimension(:), intent(inout) vert, integer, dimension(:), intent(inout) indx, integer, intent(out) ivgStat, integer, intent(out) ivgIndx)
Definition at line 962 of file RFLU_ModHashTable.F90.
References Node::addr(), moderror::deregisterfunction(), moderror::errorstop(), key, Mesh::GenericCell_2::nvert(), moderror::registerfunction(), rflu_hashfuncprimary(), and rflu_hashfuncsecondary().
Referenced by rflu_modpartitionregion::rflu_part_buildvertexlists().
subroutine, public rflu_unhashbface (type(t_global), pointer global, integer, intent(in) key, type(t_grid), pointer pGrid, integer, dimension(1:3), intent(in) fv, integer, intent(in) nVert, integer, intent(in) bcType, integer, intent(out) icg, integer, intent(out) ifg)
Definition at line 1084 of file RFLU_ModHashTable.F90.
References Node::addr(), moderror::deregisterfunction(), moderror::errorstop(), key, Mesh::GenericCell_2::nvert(), moderror::registerfunction(), rflu_hashfuncprimary(), and rflu_hashfuncsecondary().
Referenced by rflu_modfacelist::rflu_buildfacelist().
Member Data Documentation
integer, dimension(:), allocatable, public hashtable
Definition at line 82 of file RFLU_ModHashTable.F90.
integer, parameter, public hashtable_entrystatus_new = 1
Definition at line 78 of file RFLU_ModHashTable.F90.
integer, parameter, public hashtable_entrystatus_old = 0
Definition at line 78 of file RFLU_ModHashTable.F90.
integer, parameter, private hashtable_init = 0 private
Definition at line 88 of file RFLU_ModHashTable.F90.
integer, public hashtablecollisions
Definition at line 81 of file RFLU_ModHashTable.F90.
integer, public hashtablesize
Definition at line 81 of file RFLU_ModHashTable.F90.
integer, parameter, private nprimes = 48 private
Definition at line 89 of file RFLU_ModHashTable.F90.
integer, dimension(nprimes), private primenumbers = (/ 1, 251, 379, 509, 761, 1021, 1531, 2039, 3067, 4093, 6143, 8191, 12289, 16381, 24571, 32749, 49139, 65521, 98297, 131071, 196613, 262139, 393209, 524287, 786431, 1048573, 1572853, 2097143, 3145721, 4194301, 6291449, 8388593, 12582917, 16777213, 25165807, 33554393, 50331599, 67108859, 100663261, 134217689, 201326549, 268435399, 402653171, 536870909, 805306349, 1073741789, 1610612711, 2147483647 /) private
Definition at line 91 of file RFLU_ModHashTable.F90.
The documentation for this module was generated from the following file:
RFLU_ModHashTable.F90