Rocstar: IdealWeightInverseMeanRatio Class Reference
IdealWeightInverseMeanRatio Class Reference
Computes the inverse mean ratio of given element.
#include <IdealWeightInverseMeanRatio.hpp>
Public Member Functions
IdealWeightInverseMeanRatio (MsqError &err, double pow_dbl=1.0)
virtual ~IdealWeightInverseMeanRatio ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &fval, MsqError &err)
evaluate using mesquite objects
bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *e, MsqVertex *v[], Vector3D g[], Matrix3D h[], int nv, double &m, MsqError &err)
IdealWeightInverseMeanRatio (MsqError &err, double pow_dbl=1.0)
virtual ~IdealWeightInverseMeanRatio ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &fval, MsqError &err)
evaluate using mesquite objects
bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *e, MsqVertex *v[], Vector3D g[], Matrix3D h[], int nv, double &m, MsqError &err)
Public Member Functions inherited from ShapeQualityMetric
virtual ~ShapeQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
virtual ~ShapeQualityMetric ()
virtual destructor ensures use of polymorphism during destruction
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Private Member Functions
void set_metric_power (double pow_dbl, MsqError &err)
Sets the power value in the metric computation.
void set_metric_power (double pow_dbl, MsqError &err)
Sets the power value in the metric computation.
Private Attributes
Vector3D mCoords [4]
Vector3D mGradients [32]
Vector3D mAccumGrad [8]
Matrix3D mHessians [80]
double mMetrics [8]
double g_factor [8]
double h_factor [8]
double a2Con
Exponent b2Con
Exponent c2Con
double a3Con
Exponent b3Con
Exponent c3Con
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Member Functions inherited from ShapeQualityMetric
bool condition_number_2d (Vector3D temp_vec[], size_t v_ind, PatchData &pd, double &fval, MsqError &err)
Given the 2-d jacobian matrix, compute the condition number, fval.
bool condition_number_3d (Vector3D temp_vec[], PatchData &pd, double &fval, MsqError &err)
Given the 3-d jacobian matrix, compute the condition number, fval.
bool condition_number_2d (Vector3D temp_vec[], size_t v_ind, PatchData &pd, double &fval, MsqError &err)
Given the 2-d jacobian matrix, compute the condition number, fval.
bool condition_number_3d (Vector3D temp_vec[], PatchData &pd, double &fval, MsqError &err)
Given the 3-d jacobian matrix, compute the condition number, fval.
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
Computes the inverse mean ratio of given element.
The metric does not use the sample point functionality or the compute_weighted_jacobian. It evaluates the metric at the element vertices, and uses the isotropic ideal element. Optionally, the metric computation can be raised to the 'pow_dbl' power. This does not necessarily raise the metric value to the 'pow_dbl' power but instead raises each local metric. For example, if the corner inverse mean ratios of a quadraliteral element were m1,m2,m3, and m4 and we set pow_dbl=2 and used linear averaging, the metric value would then be m = .25(m1*m1 + m2*m2 + m3*m3 + m4*m4). The metric does require a feasible region, and the metric needs to be minimized if pow_dbl is greater than zero and maximized if pow_dbl is less than zero. pow_dbl being equal to zero is invalid.
Definition at line 71 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Constructor & Destructor Documentation
IdealWeightInverseMeanRatio (MsqError & err, double pow_dbl = 1.0)
Definition at line 53 of file QualityMetric/Shape/IdealWeightInverseMeanRatio.cpp.
References QualityMetric::ANALYTICAL_GRADIENT, QualityMetric::ANALYTICAL_HESSIAN, QualityMetric::avgMethod, QualityMetric::ELEMENT_BASED, QualityMetric::ELEMENT_VERTICES, QualityMetric::feasible, QualityMetric::LINEAR, MSQ_ERRRTN, QualityMetric::set_element_evaluation_mode(), QualityMetric::set_gradient_type(), QualityMetric::set_hessian_type(), IdealWeightInverseMeanRatio::set_metric_power(), QualityMetric::set_metric_type(), and QualityMetric::set_name().
 {
   set_metric_type(ELEMENT_BASED);
   set_element_evaluation_mode(ELEMENT_VERTICES, err); MSQ_ERRRTN(err);
   set_gradient_type(ANALYTICAL_GRADIENT);
   set_hessian_type(ANALYTICAL_HESSIAN);
   avgMethod=QualityMetric::LINEAR;
   feasible=1;
   set_name("Inverse Mean Ratio");
   set_metric_power(pow_dbl, err);  MSQ_ERRRTN(err);
 }
virtual ~IdealWeightInverseMeanRatio () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 77 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
{
       }
IdealWeightInverseMeanRatio (MsqError & err, double pow_dbl = 1.0)
virtual ~IdealWeightInverseMeanRatio () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 77 of file src/QualityMetric/Shape/IdealWeightInverseMeanRatio.hpp.
{
       }
Member Function Documentation
bool compute_element_analytical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
If that function is not over-riden in the concrete class, the base
Parameters description, see QualityMetric::compute_element_gradient() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
Definition at line 168 of file QualityMetric/Shape/IdealWeightInverseMeanRatio.cpp.
References IdealWeightInverseMeanRatio::a2Con, IdealWeightInverseMeanRatio::a3Con, QualityMetric::average_metric_and_weights(), QualityMetric::avgMethod, IdealWeightInverseMeanRatio::b2Con, IdealWeightInverseMeanRatio::b3Con, IdealWeightInverseMeanRatio::c2Con, IdealWeightInverseMeanRatio::c3Con, Mesquite::g_fcn_2e(), Mesquite::g_fcn_2i(), Mesquite::g_fcn_3e(), Mesquite::g_fcn_3i(), PatchData::get_domain_normal_at_element(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), Mesquite::HEXAHEDRON, i, j, Vector3D::length(), IdealWeightInverseMeanRatio::mAccumGrad, QualityMetric::MAXIMUM, IdealWeightInverseMeanRatio::mCoords, IdealWeightInverseMeanRatio::mGradients, QualityMetric::MINIMUM, IdealWeightInverseMeanRatio::mMetrics, MSQ_DBGOUT, MSQ_ERRZERO, Mesquite::QUADRILATERAL, Mesquite::TETRAHEDRON, and Mesquite::TRIANGLE.
 {
   EntityTopology topo = e->get_element_type();
   if (((topo == QUADRILATERAL) || (topo == HEXAHEDRON)) &&
       ((avgMethod == MINIMUM) || (avgMethod == MAXIMUM))) {
     MSQ_DBGOUT(1) <<
       "Minimum and maximum not continuously differentiable.\n"
       "Element of subdifferential will be returned.\n";
   }
   MsqVertex *vertices = pd.get_vertex_array(err);  MSQ_ERRZERO(err);
   const size_t *v_i = e->get_vertex_index_array();
   Vector3D n;                   // Surface normal for 2D objects
   // Hex element descriptions
   static const int locs_hex[8][4] = {{0, 1, 3, 4},
                                      {1, 2, 0, 5},
                                      {2, 3, 1, 6},
                                      {3, 0, 2, 7},
                                      {4, 7, 5, 0},
                                      {5, 4, 6, 1},
                                      {6, 5, 7, 2},
                                      {7, 6, 4, 3}};
   const Vector3D d_con(1.0, 1.0, 1.0);
   int i, j;
   bool metric_valid = false;
   int vert_per_elem = 0;
   m = 0.0;
   switch(topo) {
   case TRIANGLE:
     pd.get_domain_normal_at_element(e, n, err); MSQ_ERRZERO(err);
     n /= n.length();            // Need unit normal
     mCoords[0] = vertices[v_i[0]];
     mCoords[1] = vertices[v_i[1]];
     mCoords[2] = vertices[v_i[2]];
     if (!g_fcn_2e(m, mAccumGrad, mCoords, n, a2Con, b2Con, c2Con)) return false;
     vert_per_elem = 3;
     break;
   case QUADRILATERAL:
     pd.get_domain_normal_at_element(e, n, err); MSQ_ERRZERO(err);
     n /= n.length();    // Need unit normal
     for (i = 0; i < 4; ++i) {
       mAccumGrad[i] = 0.0;
       mCoords[0] = vertices[v_i[locs_hex[i][0]]];
       mCoords[1] = vertices[v_i[locs_hex[i][1]]];
       mCoords[2] = vertices[v_i[locs_hex[i][2]]];
       if (!g_fcn_2i(mMetrics[i], mGradients+3*i, mCoords, n,
                     a2Con, b2Con, c2Con, d_con)) return false;
     }
     m = average_metric_and_weights( mMetrics, 4, err ); MSQ_ERRZERO(err);
     for (i = 0; i < 4; ++i) {
       mAccumGrad[locs_hex[i][0]] += mMetrics[i]*mGradients[3*i+0];
       mAccumGrad[locs_hex[i][1]] += mMetrics[i]*mGradients[3*i+1];
       mAccumGrad[locs_hex[i][2]] += mMetrics[i]*mGradients[3*i+2];
     }
     vert_per_elem = 4;
     break;
   case TETRAHEDRON:
     mCoords[0] = vertices[v_i[0]];
     mCoords[1] = vertices[v_i[1]];
     mCoords[2] = vertices[v_i[2]];
     mCoords[3] = vertices[v_i[3]];
     metric_valid = g_fcn_3e(m, mAccumGrad, mCoords, a3Con, b3Con, c3Con);
     if (!metric_valid) return false;
     vert_per_elem = 4;
     break;
   case HEXAHEDRON:
     for (i = 0; i < 8; ++i) {
       mAccumGrad[i] = 0.0;
       mCoords[0] = vertices[v_i[locs_hex[i][0]]];
       mCoords[1] = vertices[v_i[locs_hex[i][1]]];
       mCoords[2] = vertices[v_i[locs_hex[i][2]]];
       mCoords[3] = vertices[v_i[locs_hex[i][3]]];
       if (!g_fcn_3i(mMetrics[i], mGradients+4*i, mCoords,
                     a3Con, b3Con, c3Con, d_con)) return false;
     }
     m = average_metric_and_weights( mMetrics, 8, err ); MSQ_ERRZERO(err);
     for (i = 0; i < 8; ++i) {
       mAccumGrad[locs_hex[i][0]] += mMetrics[i]*mGradients[4*i+0];
       mAccumGrad[locs_hex[i][1]] += mMetrics[i]*mGradients[4*i+1];
       mAccumGrad[locs_hex[i][2]] += mMetrics[i]*mGradients[4*i+2];
       mAccumGrad[locs_hex[i][3]] += mMetrics[i]*mGradients[4*i+3];
     }
     vert_per_elem = 8;
     break;
   default:
     break;
   } // end switch over element type
   // This is not very efficient, but is one way to select correct gradients
   // For gradients, info is returned only for free vertices, in the order of v[].
   for (i = 0; i < vert_per_elem; ++i) {
     for (j = 0; j < nv; ++j) {
       if (vertices + v_i[i] == v[j]) {
         g[j] = mAccumGrad[i];
       }
     }
   }
   return true;
 }
bool compute_element_analytical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
If that function is not over-riden in the concrete class, the base
Parameters description, see QualityMetric::compute_element_gradient() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
bool compute_element_analytical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) virtual
If that function is not over-riden in the concrete class, the base class function makes it default to a numerical hessian.
For parameters description, see QualityMetric::compute_element_hessian() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
bool compute_element_analytical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) virtual
If that function is not over-riden in the concrete class, the base class function makes it default to a numerical hessian.
For parameters description, see QualityMetric::compute_element_hessian() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
Definition at line 298 of file QualityMetric/Shape/IdealWeightInverseMeanRatio.cpp.
References IdealWeightInverseMeanRatio::a2Con, IdealWeightInverseMeanRatio::a3Con, QualityMetric::avgMethod, IdealWeightInverseMeanRatio::b2Con, IdealWeightInverseMeanRatio::b3Con, IdealWeightInverseMeanRatio::c2Con, IdealWeightInverseMeanRatio::c3Con, IdealWeightInverseMeanRatio::g_factor, QualityMetric::GEOMETRIC, PatchData::get_domain_normal_at_element(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), IdealWeightInverseMeanRatio::h_factor, Mesquite::h_fcn_2e(), Mesquite::h_fcn_2i(), Mesquite::h_fcn_3e(), Mesquite::h_fcn_3i(), QualityMetric::HARMONIC, Mesquite::HEXAHEDRON, QualityMetric::HMS, i, MsqError::INVALID_STATE, j, k, Vector3D::length(), QualityMetric::LINEAR, QualityMetric::MAXIMUM, IdealWeightInverseMeanRatio::mCoords, IdealWeightInverseMeanRatio::mGradients, IdealWeightInverseMeanRatio::mHessians, QualityMetric::MINIMUM, IdealWeightInverseMeanRatio::mMetrics, MSQ_DBGOUT, MSQ_ERRZERO, MSQ_SETERR, MsqError::NOT_IMPLEMENTED, Matrix3D::outer_product(), Mesquite::pow(), Mesquite::QUADRILATERAL, QualityMetric::RMS, QualityMetric::SUM, QualityMetric::SUM_SQUARED, Mesquite::TETRAHEDRON, Mesquite::transpose(), Mesquite::TRIANGLE, and Matrix3D::zero().
 {
   EntityTopology topo = e->get_element_type();
   if (((topo == QUADRILATERAL) || (topo == HEXAHEDRON)) &&
       ((avgMethod == MINIMUM) || (avgMethod == MAXIMUM))) {
     MSQ_DBGOUT(1) <<
       "Minimum and maximum not continuously differentiable.\n"
       "Element of subdifferential will be returned.\n"
       "Who knows what the Hessian is?\n" ;
   }
   MsqVertex *vertices = pd.get_vertex_array(err);  MSQ_ERRZERO(err);
   const size_t *v_i = e->get_vertex_index_array();
   Vector3D n;                   // Surface normal for 2D objects
   Matrix3D outer;
   double   nm, t=0;
   // Hex element descriptions
   static const int locs_hex[8][4] = {{0, 1, 3, 4},
                                      {1, 2, 0, 5},
                                      {2, 3, 1, 6},
                                      {3, 0, 2, 7},
                                      {4, 7, 5, 0},
                                      {5, 4, 6, 1},
                                      {6, 5, 7, 2},
                                      {7, 6, 4, 3}};
   const Vector3D d_con(1.0, 1.0, 1.0);
   int i, j, k, l, ind;
   int r, c, loc;
   bool metric_valid = false;
   m = 0.0;
   switch(topo) {
   case TRIANGLE:
     pd.get_domain_normal_at_element(e, n, err); MSQ_ERRZERO(err);
     n /= n.length();            // Need unit normal
     mCoords[0] = vertices[v_i[0]];
     mCoords[1] = vertices[v_i[1]];
     mCoords[2] = vertices[v_i[2]];
     if (!h_fcn_2e(m, g, h, mCoords, n, a2Con, b2Con, c2Con)) return false;
     // zero out fixed elements of g
     j = 0;
     for (i = 0; i < 3; ++i) {
       // if free vertex, see next
       if (j<nfv && vertices + v_i[i] == fv[j] )
         ++j;
       // else zero gradient and Hessian entries
       else {
         g[i] = 0.;
         switch(i) {
         case 0:
           h[0].zero(); h[1].zero(); h[2].zero();
           break;
         case 1:
           h[1].zero(); h[3].zero(); h[4].zero();
           break;
         case 2:
           h[2].zero(); h[4].zero(); h[5].zero();
         }
       }
     }
     break;
   case QUADRILATERAL:
     for (i=0; i < 10; ++i) {
       h[i].zero();
     }
     pd.get_domain_normal_at_element(e, n, err); MSQ_ERRZERO(err);
     n /= n.length();    // Need unit normal
     for (i = 0; i < 4; ++i) {
       g[i] = 0.0;
       mCoords[0] = vertices[v_i[locs_hex[i][0]]];
       mCoords[1] = vertices[v_i[locs_hex[i][1]]];
       mCoords[2] = vertices[v_i[locs_hex[i][2]]];
       if (!h_fcn_2i(mMetrics[i], mGradients+3*i, mHessians+6*i, mCoords, n,
                     a2Con, b2Con, c2Con, d_con)) return false;
     }
     switch(avgMethod) {
     case MINIMUM:
       MSQ_SETERR(err)("MINIMUM averaging method does not work.",MsqError::INVALID_STATE);
       return false;
     case MAXIMUM:
       MSQ_SETERR(err)("MAXIMUM averaging method does not work.",MsqError::INVALID_STATE);
       return false;
     case SUM:
       m = 0;
       for (i = 0; i < 4; ++i) {
         m += mMetrics[i];
       }
       l = 0;
       for (i = 0; i < 4; ++i) {
         g[locs_hex[i][0]] += mGradients[3*i+0];
         g[locs_hex[i][1]] += mGradients[3*i+1];
         g[locs_hex[i][2]] += mGradients[3*i+2];
         for (j = 0; j < 3; ++j) {
           for (k = j; k < 3; ++k) {
             r = locs_hex[i][j];
             c = locs_hex[i][k];
             if (r <= c) {
               loc = 4*r - (r*(r+1)/2) + c;
               h[loc] += mHessians[l];
             }
             else {
               loc = 4*c - (c*(c+1)/2) + r;
               h[loc] += transpose(mHessians[l]);
             }
             ++l;
           }
         }
       }
       break;
     case SUM_SQUARED:
       m = 0;
       for (i = 0; i < 4; ++i) {
         m += (mMetrics[i]*mMetrics[i]);
         mMetrics[i] *= 2;
       }
       l = 0;
       for (i = 0; i < 4; ++i) {
         g[locs_hex[i][0]] += mMetrics[i]*mGradients[3*i+0];
         g[locs_hex[i][1]] += mMetrics[i]*mGradients[3*i+1];
         g[locs_hex[i][2]] += mMetrics[i]*mGradients[3*i+2];
         for (j = 0; j < 3; ++j) {
           for (k = j; k < 3; ++k) {
             outer = 2.0*outer.outer_product(mGradients[3*i+j],
                                             mGradients[3*i+k]);
             r = locs_hex[i][j];
             c = locs_hex[i][k];
             if (r <= c) {
               loc = 4*r - (r*(r+1)/2) + c;
               h[loc] += mMetrics[i]*mHessians[l] + outer;
             }
             else {
               loc = 4*c - (c*(c+1)/2) + r;
               h[loc] += transpose(mMetrics[i]*mHessians[l] + outer);
             }
             ++l;
           }
         }
       }
       break;
     case LINEAR:
       m = 0;
       for (i = 0; i < 4; ++i) {
         m += mMetrics[i];
       }
       m *= 0.25;
       l = 0;
       for (i = 0; i < 4; ++i) {
         g[locs_hex[i][0]] += 0.25*mGradients[3*i+0];
         g[locs_hex[i][1]] += 0.25*mGradients[3*i+1];
         g[locs_hex[i][2]] += 0.25*mGradients[3*i+2];
         for (j = 0; j < 3; ++j) {
           for (k = j; k < 3; ++k) {
             r = locs_hex[i][j];
             c = locs_hex[i][k];
             if (r <= c) {
               loc = 4*r - (r*(r+1)/2) + c;
               h[loc] += mHessians[l];
             }
             else {
               loc = 4*c - (c*(c+1)/2) + r;
               h[loc] += transpose(mHessians[l]);
             }
             ++l;
           }
         }
       }
       for (i=0; i<10; ++i) {
         h[i] *= 0.25;
       }
       break;
     case GEOMETRIC:
       MSQ_SETERR(err)("GEOMETRIC averaging method does not work.",MsqError::INVALID_STATE);
       return false;
     default:
       switch(avgMethod) {
       case RMS:
         t = 2.0;
         break;
       case HARMONIC:
         t = -1.0;
         break;
       case HMS:
         t = -2.0;
         break;
       default:
         MSQ_SETERR(err)("averaging method not available.",MsqError::NOT_IMPLEMENTED);
         break;
       }
       m = 0;
       for (i = 0; i < 4; ++i) {
         nm = pow(mMetrics[i], t);
         m += nm;
         g_factor[i] = 0.25*t*nm / mMetrics[i];
         h_factor[i] = (t-1)*g_factor[i] / mMetrics[i];
       }
       nm = 0.25 * m;
       l = 0;
       for (i = 0; i < 4; ++i) {
         g[locs_hex[i][0]] += g_factor[i]*mGradients[3*i+0];
         g[locs_hex[i][1]] += g_factor[i]*mGradients[3*i+1];
         g[locs_hex[i][2]] += g_factor[i]*mGradients[3*i+2];
         for (j = 0; j < 3; ++j) {
           for (k = j; k < 3; ++k) {
             outer = h_factor[i] * outer.outer_product(mGradients[3*i+j],
                                                       mGradients[3*i+k]);
             r = locs_hex[i][j];
             c = locs_hex[i][k];
             if (r <= c) {
               loc = 4*r - (r*(r+1)/2) + c;
               h[loc] += g_factor[i]*mHessians[l] + outer;
             }
             else {
               loc = 4*c - (c*(c+1)/2) + r;
               h[loc] += transpose(g_factor[i]*mHessians[l] + outer);
             }
             ++l;
           }
         }
       }
       m = pow(nm, 1.0 / t);
       g_factor[0] = m / (t*nm);
       h_factor[0] = (1.0 / t - 1)*g_factor[0] / nm;
       l = 0;
       for (i = 0; i < 4; ++i) {
         for (j = i; j < 4; ++j) {
           outer = outer.outer_product(g[i], g[j]);
           h[l] = g_factor[0]*h[l] + h_factor[0]*outer;
           ++l;
         }
         g[i] *= g_factor[0];
       }
       break;
     }
     // zero out fixed elements of gradient and Hessian
     ind = 0;
     for (i=0; i<4; ++i) {
       // if free vertex, see next
       if (ind<nfv && vertices+v_i[i] == fv[ind] )
         ++ind;
       // else zero gradient entry and hessian entries.
       else {
         g[i] = 0.;
         switch(i) {
         case 0:
           h[0].zero();   h[1].zero();   h[2].zero();   h[3].zero();
           break;
         case 1:
           h[1].zero();   h[4].zero();   h[5].zero();   h[6].zero();
           break;
         case 2:
           h[2].zero();   h[5].zero();   h[7].zero();   h[8].zero();
           break;
         case 3:
           h[3].zero();   h[6].zero();   h[8].zero();   h[9].zero();
           break;
         }
       }
     }
     break;
   case TETRAHEDRON:
     mCoords[0] = vertices[v_i[0]];
     mCoords[1] = vertices[v_i[1]];
     mCoords[2] = vertices[v_i[2]];
     mCoords[3] = vertices[v_i[3]];
     metric_valid = h_fcn_3e(m, g, h, mCoords, a3Con, b3Con, c3Con);
     if (!metric_valid) return false;
     // zero out fixed elements of g
     j = 0;
     for (i = 0; i < 4; ++i) {
       // if free vertex, see next
       if (j<nfv && vertices + v_i[i] == fv[j] )
         ++j;
       // else zero gradient entry
       else {
         g[i] = 0.;
         switch(i) {
         case 0:
           h[0].zero(); h[1].zero(); h[2].zero(); h[3].zero();
           break;
         case 1:
           h[1].zero(); h[4].zero(); h[5].zero(); h[6].zero();
           break;
         case 2:
           h[2].zero(); h[5].zero(); h[7].zero(); h[8].zero();
           break;
         case 3:
           h[3].zero(); h[6].zero(); h[8].zero(); h[9].zero();
           break;
         }
       }
     }
     break;
   case HEXAHEDRON:
     for (i=0; i<36; ++i)
       h[i].zero();
     for (i = 0; i < 8; ++i) {
       g[i] = 0.0;
       mCoords[0] = vertices[v_i[locs_hex[i][0]]];
       mCoords[1] = vertices[v_i[locs_hex[i][1]]];
       mCoords[2] = vertices[v_i[locs_hex[i][2]]];
       mCoords[3] = vertices[v_i[locs_hex[i][3]]];
       if (!h_fcn_3i(mMetrics[i], mGradients+4*i, mHessians+10*i, mCoords,
                     a3Con, b3Con, c3Con, d_con)) return false;
     }
     switch(avgMethod) {
     case MINIMUM:
       MSQ_SETERR(err)("MINIMUM averaging method does not work.",MsqError::NOT_IMPLEMENTED);
       return false;
     case MAXIMUM:
       MSQ_SETERR(err)("MAXIMUM averaging method does not work.",MsqError::NOT_IMPLEMENTED);
       return false;
     case SUM:
       m = 0;
       for (i = 0; i < 8; ++i) {
         m += mMetrics[i];
       }
       l = 0;
       for (i = 0; i < 8; ++i) {
         g[locs_hex[i][0]] += mGradients[4*i+0];
         g[locs_hex[i][1]] += mGradients[4*i+1];
         g[locs_hex[i][2]] += mGradients[4*i+2];
         g[locs_hex[i][3]] += mGradients[4*i+3];
         for (j = 0; j < 4; ++j) {
           for (k = j; k < 4; ++k) {
             r = locs_hex[i][j];
             c = locs_hex[i][k];
             if (r <= c) {
               loc = 8*r - (r*(r+1)/2) + c;
               h[loc] += mHessians[l];
             }
             else {
               loc = 8*c - (c*(c+1)/2) + r;
               h[loc] += transpose(mHessians[l]);
             }
             ++l;
           }
         }
       }
       break;
     case SUM_SQUARED:
       m = 0;
       for (i = 0; i < 8; ++i) {
         m += (mMetrics[i]*mMetrics[i]);
         mMetrics[i] *= 2.0;
       }
       l = 0;
       for (i = 0; i < 8; ++i) {
         g[locs_hex[i][0]] += mMetrics[i]*mGradients[4*i+0];
         g[locs_hex[i][1]] += mMetrics[i]*mGradients[4*i+1];
         g[locs_hex[i][2]] += mMetrics[i]*mGradients[4*i+2];
         g[locs_hex[i][3]] += mMetrics[i]*mGradients[4*i+3];
         for (j = 0; j < 4; ++j) {
           for (k = j; k < 4; ++k) {
             outer = 2.0*outer.outer_product(mGradients[4*i+j],
                                             mGradients[4*i+k]);
             r = locs_hex[i][j];
             c = locs_hex[i][k];
             if (r <= c) {
               loc = 8*r - (r*(r+1)/2) + c;
               h[loc] += mMetrics[i]*mHessians[l] + outer;
             }
             else {
               loc = 8*c - (c*(c+1)/2) + r;
               h[loc] += transpose(mMetrics[i]*mHessians[l] + outer);
             }
             ++l;
           }
         }
       }
       break;
     case LINEAR:
       m = 0;
       for (i = 0; i < 8; ++i) {
         m += mMetrics[i];
       }
       m *= 0.125;
       l = 0;
       for (i = 0; i < 8; ++i) {
         g[locs_hex[i][0]] += 0.125*mGradients[4*i+0];
         g[locs_hex[i][1]] += 0.125*mGradients[4*i+1];
         g[locs_hex[i][2]] += 0.125*mGradients[4*i+2];
         g[locs_hex[i][3]] += 0.125*mGradients[4*i+3];
         for (j = 0; j < 4; ++j) {
           for (k = j; k < 4; ++k) {
             r = locs_hex[i][j];
             c = locs_hex[i][k];
             if (r <= c) {
               loc = 8*r - (r*(r+1)/2) + c;
               h[loc] += mHessians[l];
             }
             else {
               loc = 8*c - (c*(c+1)/2) + r;
               h[loc] += transpose(mHessians[l]);
             }
             ++l;
           }
         }
       }
       for (i=0; i<36; ++i)
         h[i] *= 0.125;
       break;
     case GEOMETRIC:
       MSQ_SETERR(err)("GEOMETRIC averaging method does not work.",MsqError::NOT_IMPLEMENTED);
       return false;
     default:
       switch(avgMethod) {
       case RMS:
         t = 2.0;
         break;
       case HARMONIC:
         t = -1.0;
         break;
       case HMS:
         t = -2.0;
         break;
       default:
         MSQ_SETERR(err)("averaging method not available.",MsqError::NOT_IMPLEMENTED);
         break;
       }
       m = 0;
       for (i = 0; i < 8; ++i) {
         nm = pow(mMetrics[i], t);
         m += nm;
         g_factor[i] = 0.125*t*nm / mMetrics[i];
         h_factor[i] = (t-1)*g_factor[i] / mMetrics[i];
       }
       nm = 0.125 * m;
       l = 0;
       for (i = 0; i < 8; ++i) {
         g[locs_hex[i][0]] += g_factor[i]*mGradients[4*i+0];
         g[locs_hex[i][1]] += g_factor[i]*mGradients[4*i+1];
         g[locs_hex[i][2]] += g_factor[i]*mGradients[4*i+2];
         g[locs_hex[i][3]] += g_factor[i]*mGradients[4*i+3];
         for (j = 0; j < 4; ++j) {
           for (k = j; k < 4; ++k) {
             outer = h_factor[i]*outer.outer_product(mGradients[4*i+j],
                                                     mGradients[4*i+k]);
             r = locs_hex[i][j];
             c = locs_hex[i][k];
             if (r <= c) {
               loc = 8*r - (r*(r+1)/2) + c;
               h[loc] += g_factor[i]*mHessians[l] + outer;
             }
             else {
               loc = 8*c - (c*(c+1)/2) + r;
               h[loc] += transpose(g_factor[i]*mHessians[l] + outer);
             }
             ++l;
           }
         }
       }
       m = pow(nm, 1.0 / t);
       g_factor[0] = m / (t*nm);
       h_factor[0] = (1.0 / t - 1)*g_factor[0] / nm;
       l = 0;
       for (i = 0; i < 8; ++i) {
         for (j = i; j < 8; ++j) {
           outer = outer.outer_product(g[i], g[j]);
           h[l] = g_factor[0]*h[l] + h_factor[0]*outer;
           ++l;
         }
         g[i] *= g_factor[0];
       }
       break;
     }
     // zero out fixed elements of gradient and Hessian
     ind = 0;
     for (i=0; i<8; ++i) {
       // if free vertex, see next
       if (ind<nfv && vertices+v_i[i] == fv[ind] )
         ++ind;
       // else zero gradient entry and hessian entries.
       else {
         g[i] = 0.;
         switch(i) {
         case 0:
           h[0].zero();   h[1].zero();   h[2].zero();   h[3].zero();
           h[4].zero();   h[5].zero();   h[6].zero();   h[7].zero();
           break;
         case 1:
           h[1].zero();   h[8].zero();   h[9].zero();   h[10].zero();
           h[11].zero();  h[12].zero();  h[13].zero();  h[14].zero();
           break;
         case 2:
           h[2].zero();   h[9].zero();   h[15].zero();  h[16].zero();
           h[17].zero();  h[18].zero();  h[19].zero();  h[20].zero();
           break;
         case 3:
           h[3].zero();   h[10].zero();  h[16].zero();  h[21].zero();
           h[22].zero();  h[23].zero();  h[24].zero();  h[25].zero();
           break;
         case 4:
           h[4].zero();   h[11].zero();  h[17].zero();  h[22].zero();
           h[26].zero();  h[27].zero();  h[28].zero();  h[29].zero();
           break;
         case 5:
           h[5].zero();   h[12].zero();  h[18].zero();  h[23].zero();
           h[27].zero();  h[30].zero();  h[31].zero();  h[32].zero();
           break;
         case 6:
           h[6].zero();   h[13].zero();  h[19].zero();  h[24].zero();
           h[28].zero();  h[31].zero();  h[33].zero();  h[34].zero();
           break;
         case 7:
           h[7].zero();   h[14].zero();  h[20].zero();  h[25].zero();
           h[29].zero();  h[32].zero();  h[34].zero();  h[35].zero();
           break;
         }
       }
     }
     break;
   default:
     break;
   } // end switch over element type
   return true;
 }
bool evaluate_element (PatchData & pd, MsqMeshEntity * element, double & fval, MsqError & err) virtual
evaluate using mesquite objects
Reimplemented from QualityMetric.
bool evaluate_element (PatchData & pd, MsqMeshEntity * element, double & fval, MsqError & err) virtual
evaluate using mesquite objects
Reimplemented from QualityMetric.
Definition at line 87 of file QualityMetric/Shape/IdealWeightInverseMeanRatio.cpp.
References IdealWeightInverseMeanRatio::a2Con, IdealWeightInverseMeanRatio::a3Con, QualityMetric::average_metrics(), IdealWeightInverseMeanRatio::b2Con, IdealWeightInverseMeanRatio::b3Con, IdealWeightInverseMeanRatio::c2Con, IdealWeightInverseMeanRatio::c3Con, PatchData::get_domain_normal_at_element(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), Mesquite::HEXAHEDRON, i, Vector3D::length(), Mesquite::m_fcn_2e(), Mesquite::m_fcn_2i(), Mesquite::m_fcn_3e(), Mesquite::m_fcn_3i(), IdealWeightInverseMeanRatio::mCoords, IdealWeightInverseMeanRatio::mMetrics, MSQ_ERRZERO, Mesquite::QUADRILATERAL, Mesquite::TETRAHEDRON, and Mesquite::TRIANGLE.
 {
   EntityTopology topo = e->get_element_type();
   MsqVertex *vertices = pd.get_vertex_array(err);  MSQ_ERRZERO(err);
   const size_t *v_i = e->get_vertex_index_array();
   Vector3D n;                   // Surface normal for 2D objects
   // Hex element descriptions
   static const int locs_hex[8][4] = {{0, 1, 3, 4},
                                      {1, 2, 0, 5},
                                      {2, 3, 1, 6},
                                      {3, 0, 2, 7},
                                      {4, 7, 5, 0},
                                      {5, 4, 6, 1},
                                      {6, 5, 7, 2},
                                      {7, 6, 4, 3}};
   const Vector3D d_con(1.0, 1.0, 1.0);
   int i;
   m = 0.0;
   bool metric_valid = false;
   switch(topo) {
   case TRIANGLE:
     pd.get_domain_normal_at_element(e, n, err); MSQ_ERRZERO(err);
     n = n / n.length();         // Need unit normal
     mCoords[0] = vertices[v_i[0]];
     mCoords[1] = vertices[v_i[1]];
     mCoords[2] = vertices[v_i[2]];
     metric_valid = m_fcn_2e(m, mCoords, n, a2Con, b2Con, c2Con);
     if (!metric_valid) return false;
     break;
   case QUADRILATERAL:
     pd.get_domain_normal_at_element(e, n, err); MSQ_ERRZERO(err);
     n = n / n.length(); // Need unit normal
     for (i = 0; i < 4; ++i) {
       mCoords[0] = vertices[v_i[locs_hex[i][0]]];
       mCoords[1] = vertices[v_i[locs_hex[i][1]]];
       mCoords[2] = vertices[v_i[locs_hex[i][2]]];
       metric_valid = m_fcn_2i(mMetrics[i], mCoords, n,
                               a2Con, b2Con, c2Con, d_con);
       if (!metric_valid) return false;
     }
     m = average_metrics(mMetrics, 4, err);
     break;
   case TETRAHEDRON:
     mCoords[0] = vertices[v_i[0]];
     mCoords[1] = vertices[v_i[1]];
     mCoords[2] = vertices[v_i[2]];
     mCoords[3] = vertices[v_i[3]];
     metric_valid = m_fcn_3e(m, mCoords, a3Con, b3Con, c3Con);
     if (!metric_valid) return false;
     break;
   case HEXAHEDRON:
     for (i = 0; i < 8; ++i) {
       mCoords[0] = vertices[v_i[locs_hex[i][0]]];
       mCoords[1] = vertices[v_i[locs_hex[i][1]]];
       mCoords[2] = vertices[v_i[locs_hex[i][2]]];
       mCoords[3] = vertices[v_i[locs_hex[i][3]]];
       metric_valid = m_fcn_3i(mMetrics[i], mCoords,
                               a3Con, b3Con, c3Con, d_con);
       if (!metric_valid) return false;
     }
     m = average_metrics(mMetrics, 8, err); MSQ_ERRZERO(err);
     break;
   default:
     break;
   } // end switch over element type
   return true;
 }
void set_metric_power (double pow_dbl, MsqError & err) private
Sets the power value in the metric computation.
void set_metric_power (double pow_dbl, MsqError & err) private
Sets the power value in the metric computation.
Definition at line 68 of file QualityMetric/Shape/IdealWeightInverseMeanRatio.cpp.
References IdealWeightInverseMeanRatio::a2Con, IdealWeightInverseMeanRatio::a3Con, IdealWeightInverseMeanRatio::b2Con, IdealWeightInverseMeanRatio::b3Con, IdealWeightInverseMeanRatio::c2Con, IdealWeightInverseMeanRatio::c3Con, MsqError::INVALID_ARG, Mesquite::MSQ_MIN, MSQ_SETERR, Mesquite::pow(), and QualityMetric::set_negate_flag().
Referenced by IdealWeightInverseMeanRatio::IdealWeightInverseMeanRatio().
 {
   if(fabs(pow_dbl)<=MSQ_MIN){
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     return;
   }
   if(pow_dbl<0)
     set_negate_flag(-1);
   else
     set_negate_flag(1);
   a2Con=pow(.5,pow_dbl);
   b2Con=pow_dbl;
   c2Con=-pow_dbl;
   a3Con=pow(1.0/3.0,pow_dbl);
   b3Con=pow_dbl;
   c3Con=-2.0*pow_dbl/3.0;
 }
Member Data Documentation
double a2Con private
Definition at line 116 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightInverseMeanRatio::set_metric_power().
double a3Con private
Definition at line 120 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightInverseMeanRatio::set_metric_power().
Exponent b2Con private
Definition at line 117 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightInverseMeanRatio::set_metric_power().
Exponent b3Con private
Definition at line 121 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightInverseMeanRatio::set_metric_power().
Exponent c2Con private
Definition at line 118 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightInverseMeanRatio::set_metric_power().
Exponent c3Con private
Definition at line 122 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightInverseMeanRatio::set_metric_power().
double g_factor private
Definition at line 113 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_hessian().
double h_factor private
Definition at line 114 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_hessian().
Vector3D mAccumGrad private
Definition at line 110 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient().
Vector3D mCoords private
Definition at line 108 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), and IdealWeightInverseMeanRatio::evaluate_element().
Vector3D mGradients private
Definition at line 109 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), and IdealWeightInverseMeanRatio::compute_element_analytical_hessian().
Matrix3D mHessians private
Definition at line 111 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_hessian().
double mMetrics private
Definition at line 112 of file includeLinks/IdealWeightInverseMeanRatio.hpp.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), and IdealWeightInverseMeanRatio::evaluate_element().
The documentation for this class was generated from the following files:
includeLinks/IdealWeightInverseMeanRatio.hpp
QualityMetric/Shape/IdealWeightInverseMeanRatio.cpp