Rocstar: LineS2< FT > Class Template Reference
LineS2< FT > Class Template Reference
#include <LineS2.h>
Public Member Functions
LineS2 ()
LineS2 (const PointS2< FT > &p, const PointS2< FT > &q)
LineS2 (const FT &a, const FT &b, const FT &c)
LineS2 (const SegmentS2< FT > &s)
LineS2 (const RayS2< FT > &r)
LineS2 (const PointS2< FT > &p, const DirectionS2< FT > &d)
bool operator== (const LineS2< FT > &l) const
bool operator!= (const LineS2< FT > &l) const
FT a () const
FT b () const
FT c () const
FT x_at_y (const FT &y) const
FT y_at_x (const FT &x) const
LineS2< FT > perpendicular (const PointS2< FT > &p) const
LineS2< FT > opposite () const
PointS2< FT > point (int i) const
PointS2< FT > point () const
PointS2< FT > projection (const PointS2< FT > &p) const
DirectionS2< FT > direction () const
Oriented_side oriented_side (const PointS2< FT > &p) const
bool has_on_boundary (const PointS2< FT > &p) const
bool has_on_positive_side (const PointS2< FT > &p) const
bool has_on_negative_side (const PointS2< FT > &p) const
bool is_horizontal () const
bool is_vertical () const
bool is_degenerate () const
LineS2< FT > transform (const Aff_transformationS2< FT > &t) const
void new_rep (const PointS2< FT > &p, const PointS2< FT > &q)
void new_rep (const FT &a, const FT &b, const FT &c)
Public Attributes
FT e0
FT e1
FT e2
Detailed Description
template<class FT>
class LineS2< FT >
Definition at line 62 of file LineS2.h.
Constructor & Destructor Documentation
LineS2 () inline
Definition at line 117 of file LineS2.h.
 {}
LineS2 (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 140 of file LineS2.h.
 { new_rep(p,q); }
LineS2 (const FT & a, const FT & b, const FT & c) inline
Definition at line 145 of file LineS2.h.
 { new_rep(a,b,c); }
LineS2 (const SegmentS2< FT > & s) inline
Definition at line 150 of file LineS2.h.
References SegmentS2< FT >::end(), and SegmentS2< FT >::start().
 { new_rep( s.start(), s.end()); }
LineS2 (const RayS2< FT > & r) inline
Definition at line 155 of file LineS2.h.
References RayS2< FT >::second_point(), and RayS2< FT >::start().
 { new_rep(r.start(), r.second_point()); }
CGAL_KERNEL_INLINE LineS2 (const PointS2< FT > & p, const DirectionS2< FT > & d)
Definition at line 160 of file LineS2.h.
References DirectionS2< FT >::dx(), DirectionS2< FT >::dy(), PointS2< FT >::x(), and PointS2< FT >::y().
 { new_rep(-d.dy(), d.dx(), -d.dx()* p.y()  + d.dy() * p.x()); }
Member Function Documentation
FT a () const inline
Definition at line 188 of file LineS2.h.
Referenced by LineS2< FT >::operator==().
 { return e0; }
FT b () const inline
Definition at line 193 of file LineS2.h.
Referenced by LineS2< FT >::operator==().
 { return e1; }
FT c () const inline
Definition at line 198 of file LineS2.h.
Referenced by LineS2< FT >::operator==().
 { return e2; }
DirectionS2< FT > direction () const inline
Definition at line 270 of file LineS2.h.
Referenced by Aff_transformationS2< FT >::transform().
 { return DirectionS2<FT>( b(), -a() ); }
bool has_on_boundary (const PointS2< FT > & p) const inline
Definition at line 280 of file LineS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 { return (a()*p.x() + b()*p.y() + c()) == FT(0); }
CGAL_KERNEL_INLINE bool has_on_negative_side (const PointS2< FT > & p) const
Definition at line 290 of file LineS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 { return (a()*p.x() + b()*p.y() + c()) <  FT(0); }
bool has_on_positive_side (const PointS2< FT > & p) const inline
Definition at line 285 of file LineS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 { return (a()*p.x() + b()*p.y() + c()) >  FT(0); }
bool is_degenerate () const inline
Definition at line 305 of file LineS2.h.
 { return (a() == FT(0)) && (b() == FT(0)) ; }
bool is_horizontal () const inline
Definition at line 295 of file LineS2.h.
 { return a() == FT(0) ; }
bool is_vertical () const inline
Definition at line 300 of file LineS2.h.
 { return b() == FT(0) ; }
CGAL_KERNEL_INLINE void new_rep (const PointS2< FT > & p, const PointS2< FT > & q)
Definition at line 122 of file LineS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 {
   e0 = p.y() - q.y();
   e1 = q.x() - p.x();
   e2 = p.x()*q.y() - p.y()*q.x();
 }
CGAL_KERNEL_INLINE void new_rep (const FT & a, const FT & b, const FT & c)
Definition at line 131 of file LineS2.h.
 {
   e0 = a;
   e1 = b;
   e2 = c;
 }
bool operator!= (const LineS2< FT > & l) const inline
Definition at line 183 of file LineS2.h.
 { return !(*this == l); }
CGAL_KERNEL_MEDIUM_INLINE bool operator== (const LineS2< FT > & l) const
Definition at line 166 of file LineS2.h.
References LineS2< FT >::a(), LineS2< FT >::b(), LineS2< FT >::c(), CGAL_NTS, and sign().
 {
   if (  (a() * l.c() != l.a() * c())
       ||(b() * l.c() != l.b() * c()) )
       return false;
   int sc  = CGAL_NTS sign(c());
   int slc = CGAL_NTS sign(l.c());
   if ( sc == slc )
       return (sc == 0) ?  ( a()*l.b() ==  b()*l.a() )
                          && (CGAL_NTS sign(a() ) == CGAL_NTS sign( l.a() ))
                          && (CGAL_NTS sign(b() ) == CGAL_NTS sign( l.b() ))
                        : true;
   return false;
 }
LineS2< FT > opposite () const inline
Definition at line 226 of file LineS2.h.
 { return LineS2<FT>( -a(), -b(), -c() ); }
CGAL_KERNEL_INLINE Oriented_side oriented_side (const PointS2< FT > & p) const
Definition at line 275 of file LineS2.h.
References CGAL_NTS, sign(), PointS2< FT >::x(), and PointS2< FT >::y().
 { return Oriented_side(CGAL_NTS sign(a()*p.x() + b()*p.y() + c())); }
LineS2< FT > perpendicular (const PointS2< FT > & p) const inline
Definition at line 221 of file LineS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 { return LineS2<FT>( -b() , a() , b() * p.x() - a() * p.y()  ); }
CGAL_KERNEL_MEDIUM_INLINE PointS2< FT > point (int i) const
Definition at line 231 of file LineS2.h.
Referenced by Aff_transformationS2< FT >::transform().
 {
   if (i == 0)
     return is_vertical() ? PointS2<FT>( (-b()-c())/a(), FT(1) )
                          : PointS2<FT>( FT(1), -(a()+c())/b());
   if (i == 1)
     return is_vertical() ? PointS2<FT>( (-b()-c())/a() + b(), FT(1) - a() )
                          : PointS2<FT>( FT(1) + b(), -(a()+c())/b() - a() );
   // we add i times the direction
   if (is_vertical())
     return PointS2<FT>( (-b()-c())/a() + FT(i)*b(), FT(1) - FT(i)*a() );
   return PointS2<FT>( FT(1) + FT(i)*b(), -(a()+c())/b() - FT(i)*a() );
 }
CGAL_KERNEL_INLINE PointS2< FT > point () const
Definition at line 247 of file LineS2.h.
 {
   return is_vertical() ? PointS2<FT>( (-b()-c())/a(), FT(1) )
                        : PointS2<FT>( FT(1), -(a()+c())/b());
 }
CGAL_KERNEL_MEDIUM_INLINE PointS2< FT > projection (const PointS2< FT > & p) const
Definition at line 255 of file LineS2.h.
References PointS2< FT >::x(), PointS2< FT >::y(), and y.
 {
   if (is_horizontal())
       return PointS2<FT>(p.x(), -c()/b());
   if (is_vertical())
       return PointS2<FT>( -c()/a(), p.y());
   FT ab = a()/b(), ba = b()/a(), ca = c()/a();
   FT y = ( -p.x() + ab*p.y() - ca ) / ( ba + ab );
   return PointS2<FT>(-ba * y - ca, y);
 }
LineS2< FT > transform (const Aff_transformationS2< FT > & t) const inline
Definition at line 310 of file LineS2.h.
References Aff_transformationS2< FT >::transform().
 { return LineS2<FT>( t.transform(point(0) ), t.transform(direction() )); }
CGAL_KERNEL_INLINE FT x_at_y (const FT & y) const
Definition at line 203 of file LineS2.h.
References CGAL_kernel_precondition_msg.
 {
   CGAL_kernel_precondition_msg( (a() != FT(0)),
                "Line::x_at_y(const FT& y) is undefined for horizontal line" );
   return ( -b()*y - c() ) / a();
 }
CGAL_KERNEL_INLINE FT y_at_x (const FT & x) const
Definition at line 212 of file LineS2.h.
References CGAL_kernel_precondition_msg.
 {
   CGAL_kernel_precondition_msg( (b() != FT(0)),
               "Line::x_at_y(const FT& y) is undefined for vertical line");
   return ( -a()*x - c() ) / b();
 }
Member Data Documentation
FT e0
Definition at line 108 of file LineS2.h.
FT e1
Definition at line 109 of file LineS2.h.
FT e2
Definition at line 110 of file LineS2.h.
The documentation for this class was generated from the following file:
LineS2.h