Rocstar: rflu_modinterpolation Module Reference
rflu_modinterpolation Module Reference
Public Member Functions
subroutine, public rflu_interpcells2face (pRegion, ifg, src, dst)
subroutine, public rflu_interpcells2facepatch (pRegion, pPatch, ifl, src, dst)
subroutine, public rflu_interpcells2faces (pRegion, src, dst)
subroutine, public rflu_interpcells2verts (pRegion, orderNominal, nVar, src, dst)
subroutine, public rflu_interpsimplecells2verts (pRegion, nVar, src, dst)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModInterpolation.F90,v $ $Revision: 1.21 $'
Detailed Description
Definition at line 41 of file RFLU_ModInterpolation.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_interpcells2face (type(t_region), pointer pRegion, integer, intent(in) ifg, real(rfreal), dimension(:,:), intent(in) src, real(rfreal), dimension(:), intent(out) dst)
Definition at line 102 of file RFLU_ModInterpolation.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_modviscousflux::rflu_viscousfluxes().
subroutine, public rflu_interpcells2facepatch (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) ifl, real(rfreal), dimension(:,:), intent(in) src, real(rfreal), dimension(:), intent(out) dst)
Definition at line 329 of file RFLU_ModInterpolation.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_modviscousflux::rflu_viscousfluxespatches().
subroutine, public rflu_interpcells2faces (type(t_region), pointer pRegion, real(rfreal), dimension(:,:), intent(in) src, real(rfreal), dimension(:,:), intent(out) dst)
Definition at line 521 of file RFLU_ModInterpolation.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by turb_leslij().
subroutine, public rflu_interpcells2verts (type(t_region), pointer pRegion, integer, intent(in) orderNominal, integer, intent(in) nVar, real(rfreal), dimension(:,:), intent(in) src, real(rfreal), dimension(:,:), intent(out) dst)
Definition at line 719 of file RFLU_ModInterpolation.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modstencilsutils::rflu_computestencilweights().
Referenced by rflu_interpolatewrapper().
subroutine, public rflu_interpsimplecells2verts (type(t_region), pointer pRegion, integer, intent(in) nVar, real(rfreal), dimension(:,:), intent(in) src, real(rfreal), dimension(:,:), intent(out) dst)
Definition at line 884 of file RFLU_ModInterpolation.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_interpolatewrapper().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModInterpolation.F90,v $ $Revision: 1.21 $' private
Definition at line 72 of file RFLU_ModInterpolation.F90.
The documentation for this module was generated from the following file:
RFLU_ModInterpolation.F90