Rocstar: Node Class Reference
Node Class Reference
This class encapsulate a node over a window manifold.
#include <Manifold_2.h>
Public Types
enum FlagType { e_unset_flag = -1 }
Public Member Functions
Node ()
Default constructor.
Node (const Pane_manifold_2 *pm, int vid, Access_Mode mode)
Construct a Node object from a pane manifold and its node ID.
Halfedge halfedge () const
Get an incident halfedge originated from the node.
const Pane_manifold_2 * pane_manifold () const
Obtain the pane manifold that owns the edge.
const COM::Pane * pane () const
Obtain the owner Pane_manifold_2 of the node.
int id () const
Obtain the node ID within its Pane_manifold_2.
const Point_3< Real > & point () const
Obtain the coordinates of a node.
const void * addr (const COM::Attribute *attr) const
Obtain the address of an attribute associated with the node.
const COM::Attribute * attr (const COM::Attribute *a) const
Obtain the attribute on the parent pane of the node.
bool is_border () const
Is the node on the physical boundary?
bool is_isolated () const
Is the node isolated?
bool is_primary () const
Is the node a primary?
Node get_primary () const
Get the primary copy of the node.
bool coincide (const Node &n) const
Check whether the current node coincide with the given node.
bool operator== (const Node &n) const
Are two nodes the same?
bool operator!= (const Node &n) const
Are two nodes different?
bool operator< (const Node &n) const
Does the current node has a smaller ID then the given node?
Node ()
Node (MVec pos)
Node (MVec pos, int flag)
~Node ()
void setID (int theID)
int getID ()
void setPosition (MVec pos)
MVec getPosition ()
void addFace (Face *face)
void removeFace (Face *face)
int getNumFaces ()
retrieves the number of faces currently associated with this node.
Face * getFace (int Index)
Retrieves a pointer to the face referenced by the supplied index that is associated with this node, i.e., if there are 3 faces associated with this node (use getNumFaces), then index should run from 0 to 2.
Face ** getAllFaces ()
Retrieves a pointer to the internal array of faces associated with this node.
void addElement (Element *elem)
void removeElement (Element *elem)
int getNumElements ()
retrieves the number of elements currently associated with this node.
Element * getElement (int Index)
Retrieves a pointer to the element referenced by the supplied index that is associated with this node, i.e., if there are 3 elements associated with this node (use getNumElements), then index should run from 0 to 2.
Element ** getAllElements ()
Retrieves a pointer to the internal array of elements associated with this node.
Face * sharedFace (Node *n2, Node *n3, Node *n4=0)
Node * getNext ()
void addNextLink (Node *link)
boolean separate (Mesh *mesh, FaceList *list, int new_material)
int getFlag () const
void setFlag (int flag)
Protected Attributes
const Pane_manifold_2 * _pm
int _vID
Access_Mode _mode
Private Member Functions
ElementList * getSeparateElements (FaceList *list)
Private Attributes
MVec d_position
int d_ID
int d_flag
Node * d_nextNode
Face ** d_faces
int d_faceArraySize
int d_numFaces
Element ** d_elements
int d_elementArraySize
int d_numElements
Friends
istream & operator>> (istream &stream, Node &n)
ostream & operator<< (ostream &stream, Node &n)
Detailed Description
This class encapsulate a node over a window manifold.
Definition at line 370 of file Manifold_2.h.
Member Enumeration Documentation
enum FlagType
Enumerator
e_unset_flag
Definition at line 15 of file Node.hpp.
                  {
        e_unset_flag = -1
     };
Constructor & Destructor Documentation
Node () inline
Default constructor.
Definition at line 373 of file Manifold_2.h.
Referenced by separate().
 : _pm(NULL), _vID(0), _mode( ACROSS_PANE) {}
Node (const Pane_manifold_2 * pm, int vid, Access_Mode mode) inline
Construct a Node object from a pane manifold and its node ID.
Definition at line 376 of file Manifold_2.h.
     : _pm( pm), _vID( vid), _mode( mode) {}
Node ()
Node (MVec pos)
Definition at line 23 of file Node.cpp.
                    :
 d_position( pos ),
 d_ID(-1),
 d_flag(e_unset_flag),
 d_nextNode (this),
 d_faceArraySize(0),
 d_numFaces(0),
 d_elementArraySize(0),
 d_numElements(0)
 {}
Node (MVec pos, int flag)
Definition at line 34 of file Node.cpp.
                              :
 d_position( pos ),
 d_ID(-1),
 d_flag(flag),
 d_nextNode (this),
 d_faceArraySize(0),
 d_numFaces(0),
 d_elementArraySize(0),
 d_numElements(0)
 {}
~Node ()
Definition at line 45 of file Node.cpp.
References d_elementArraySize, d_elements, d_faceArraySize, and d_faces.
            {
   if( d_faceArraySize > 0 ){
     delete [] d_faces;
   }
   if( d_elementArraySize > 0 ){
     delete [] d_elements;
   }
 }
Member Function Documentation
void addElement (Element * elem)
Definition at line 86 of file Node.cpp.
References d_elementArraySize, d_elements, and d_numElements.
Referenced by operator>>(), TCoElement::replaceFaceNode(), QCoElement::replaceFaceNode(), Element::replaceNode(), and Element::setFromNodes().
{
   if( d_elementArraySize == d_numElements ){
     d_elementArraySize =  (int)( d_elementArraySize * 1.25 + 3);
     Element **new_arr = new Element*[d_elementArraySize];
     if( d_numElements > 0 ){
       memcpy(new_arr, d_elements, d_numElements * sizeof(Element*) );
       delete [] d_elements;
     }
     d_elements = new_arr;
   }
   d_elements[d_numElements] = elem;
   d_numElements++;
 }
void addFace (Face * face)
Definition at line 55 of file Node.cpp.
References d_faceArraySize, d_faces, d_numFaces, and face.
Referenced by QuadFace::QuadFace(), Face::replaceNode(), and TriFace::TriFace().
{
   if( d_faceArraySize == d_numFaces ){
     d_faceArraySize =  (int)( d_faceArraySize * 1.25 + 3);
     Face **new_arr = new Face*[d_faceArraySize];
     if( d_numFaces > 0 ){
       memcpy(new_arr, d_faces, d_numFaces * sizeof(Face*) );
       delete [] d_faces;
     }
     d_faces = new_arr;
   }
   d_faces[d_numFaces] = face;
   d_numFaces++;
 }
void addNextLink (Node * link)
Definition at line 139 of file Node.cpp.
References d_nextNode.
Referenced by QCoElement::setFromMyNodes(), and TCoElement::setFromMyNodes().
{
   Node* prev = this;
   while( prev->d_nextNode != this ){
     prev = prev->d_nextNode;
   }
   // now prev->next is this one
   prev->d_nextNode = link;
   prev = link;
   while( prev->d_nextNode != link ){
     prev = prev->d_nextNode;
   }
   // now prev->next is link
   prev->d_nextNode = this;
   prev = this;
   while( prev->d_nextNode != this ){
     prev = prev->d_nextNode;
   }
 }
const void * addr (const COM::Attribute * attr) const
Obtain the address of an attribute associated with the node.
Note: This function can be slow O(log(#panes)) if the attribute is not on the current pane.
Definition at line 1191 of file Manifold_2.C.
References _pm, _vID, attr(), COM_assertion_msg, COM_get_sizeof(), and Simple_manifold_2::pane().
Referenced by Halfedge::edge_average(), Halfedge::face_average(), get_deformed_normal(), rflu_modhashtable::rflu_hashedge(), rflu_modhashtable::rflu_hashface(), rflu_modhashtable::rflu_hashfuncprimary(), rflu_modhashtable::rflu_hashfuncsecondary(), rflu_modhashtable::rflu_hashvertex(), rflu_modhashtable::rflu_hashvertexfancy(), and rflu_modhashtable::rflu_unhashbface().
{
   COM_assertion_msg( a, "Unexpected NULL pointer");
   COM_assertion_msg( a->is_nodal(), "Expect a nodal attribute");
   const COM::Attribute *attr;
   const COM::Pane *pn = _pm->pane();
   int pid = pn->id();
   if ( a->pane()->id() == pid)
     attr = a;
   else {
     if ( a->window() != pn->window()) {
       pn = &a->window()->pane( pid);
       COM_assertion_msg( pn, "Pane does not exist");
     }
     attr=pn->attribute( a->id());
     COM_assertion_msg( attr, "Attribute does not exist");
   }
   return ((const char*)attr->pointer()) +
     COM_get_sizeof( attr->data_type(), attr->stride()*(_vID-1));
 }
const COM::Attribute* attr (const COM::Attribute * a) const inline
Obtain the attribute on the parent pane of the node.
It takes O(log(#panes)) time.
Definition at line 404 of file Manifold_2.h.
References _pm, COM_assertion_msg, and Simple_manifold_2::pane().
Referenced by addr(), rocstar_rocfrac::associate_pointer(), modrocstar::associate_pointer(), and m_rocburn_interface_data::associate_pointer().
{
     COM_assertion_msg( a, "Unexpected NULL pointer");
     return a->window()->pane( _pm->pane()->id()).attribute(a->id());
   }
bool coincide (const Node & n) const inline
Check whether the current node coincide with the given node.
Definition at line 422 of file Manifold_2.h.
References _mode, _pm, _vID, and Pane_manifold_2::get_primary().
   { return _pm->get_primary( _vID, _mode) == n._pm->get_primary( n._vID, n._mode); }
Node get_primary () const inline
Get the primary copy of the node.
Definition at line 419 of file Manifold_2.h.
References _mode, _pm, _vID, and Pane_manifold_2::get_primary().
Referenced by Window_manifold_2::assign_global_nodeIDs().
 { return _pm->get_primary( _vID, _mode); }
Element ** getAllElements () inline
Retrieves a pointer to the internal array of elements associated with this node.
Use getNumElements to find out how many are in the array.
Definition at line 147 of file Node.hpp.
References d_elements.
 { return d_elements; }
Face ** getAllFaces () inline
Retrieves a pointer to the internal array of faces associated with this node.
Use getNumFaces to find out how many are in the array.
Definition at line 135 of file Node.hpp.
References d_faces.
 { return d_faces; }
Element * getElement (int Index) inline
Retrieves a pointer to the element referenced by the supplied index that is associated with this node, i.e., if there are 3 elements associated with this node (use getNumElements), then index should run from 0 to 2.
Definition at line 143 of file Node.hpp.
References d_elements.
 { return d_elements[Index]; }
Face * getFace (int Index) inline
Retrieves a pointer to the face referenced by the supplied index that is associated with this node, i.e., if there are 3 faces associated with this node (use getNumFaces), then index should run from 0 to 2.
Definition at line 131 of file Node.hpp.
References d_faces.
 { return d_faces[Index]; }
int getFlag () const inline
Definition at line 150 of file Node.hpp.
References d_flag.
Referenced by operator<<().
 {return d_flag; }
int getID () inline
Definition at line 119 of file Node.hpp.
References d_ID.
Referenced by operator<<().
 { return d_ID; }
Node* getNext ()
int getNumElements () inline
retrieves the number of elements currently associated with this node.
Definition at line 140 of file Node.hpp.
References d_numElements.
 { return d_numElements; }
int getNumFaces () inline
retrieves the number of faces currently associated with this node.
Definition at line 128 of file Node.hpp.
References d_numFaces.
 { return d_numFaces; }
MVec getPosition () inline
Definition at line 125 of file Node.hpp.
References d_position.
Referenced by TetElement::getMinEdgeLength().
 { return d_position; }
ElementList * getSeparateElements (FaceList * list) private
Definition at line 192 of file Node.cpp.
References d_elements, d_faces, d_numElements, d_numFaces, FALSE, FaceList::get(), ElementList::get(), Face::getElement1(), Face::getElement2(), i, FaceList::insert_first(), ElementList::insert_first(), Element::isCohesive(), j, FaceList::move_to(), ElementList::move_to(), FaceList::next(), ElementList::next(), FaceList::remove(), ElementList::reset(), FaceList::size(), ElementList::size(), and TRUE.
Referenced by separate().
{
   // Collect ONLY regular faces - not in cohesive,
   // not boundary, not in the "list" ("list" is a facelist of
   // the faces involving the node that is trying to be separated).
   //"list" is used as a separator list of faces.  We need to build a list of
   //faces that CAN be traversed. That list will be node_faces.
   FaceList node_faces;
   int i;
   for( i = 0; i < d_numFaces; i++ ){
         //step through all the faces in the d_faces array for this node.
     Face *face = d_faces[i];
     //see if each face is on the "list" of separable faces sent in.
     if( list->move_to( face )){
       continue; //if it is, then go to the next face.
     }
     //if this face is an exterior face, or if either element that it
     //is associated with is cohesive, then don't add it to the facelist.
     if( !face->getElement2() || face->getElement1()->isCohesive() ||
         face->getElement2()->isCohesive() ){
       continue;
     }
     node_faces.insert_first( face );
   }
   //count the number of non-cohesive ("real") elements attached to this node.
   int count_real=0;
   for( i = 0; i < d_numElements; i++ ){
     if( !d_elements[i]->isCohesive() ){
       count_real++;
     }
   }
   // Try to find ONE non-cohesive element.  Note the "break" in the "if"
   // below if one is found!
   ElementList *shared_elements = new ElementList;
   for( i = 0; i < d_numElements; i++ ){
     if( !d_elements[i]->isCohesive() ){
       shared_elements->insert_first(d_elements[i]);
       break;
     }
   }
   //We should always find at least one non-cohesive element (says Alla).
   if( shared_elements->size() != 1 ){
     // thoretically this should not happen (pure cohesive node)
     delete shared_elements;
     return 0;  //get out of town if node is pure cohesive - can't separate.
   }
   // Since we found one non-cohesive element, now try to add more
   boolean changed = TRUE;
   while( changed ) {
     changed = FALSE;
     //number of faces with non-cohesive or non-exterior elements on both sides.
     int size = node_faces.size();
     int i;
     //loop over all the candidate faces for this node.
     for( i = 0; i < size; i++ ) {
       //retrieve the list of faces for this node.
       Face* face = node_faces.get();
       boolean found=FALSE;
       // check if face belongs to any shared element
       shared_elements->reset();
       int nums = shared_elements->size();
       int j;
       //for each element in the shared_elements list...
       for( j = 0; j < nums; j++ ) {
                 Element* sh_el = shared_elements->get();
                 Element* oelem(0);
                 //check and see if the current face involves one of the elements on the list.
                 //If so, get the other element that is on the other side of the face (put
                 //in oelem).
                 if( face->getElement1() == sh_el ){
                         oelem = face->getElement2();
                 }
                 else if( face->getElement2() == sh_el ){
                         oelem = face->getElement1();
                 }
                 //if find the second element ...
                 if( oelem ){
                         found = TRUE;
                         //if it's not already on the shared elements list, then put it on the list.
                         if( !shared_elements->move_to( oelem ) ){
                         shared_elements->insert_first( oelem );
                         }
                         break; //exit j loop (element loop)
                 }
                 //get ready to check the next element.
                 shared_elements->next();
       } //for (j=0...
       if( found ){
         //remove the current face from the facelist
                 node_faces.remove();
                 //get ready to look at the new facelist (sans the current face)
                 changed = TRUE;
                 //exit the i loop and go back to the while (start over with new list of faces)
                 break;
       }
       //one of the faces must be part of elements that are already on the list, so go on!
       node_faces.next();
     } //for (i=0 ...
   } //while(changed)
   // count_real is the number of non-cohesive elements attached to this node.
   // have separation surface
   //if the actual number of elements is greater than the number you found, then there must
   //be a separation plane.  If it is the same, then you went all the way around and found no
   //boundary.
   if( count_real > shared_elements->size() ){
     return shared_elements;
   }
   delete shared_elements;
   return 0;
 }
Halfedge halfedge () const inline
Get an incident halfedge originated from the node.
If the node is on the physical boundary, the halfedge must be a physical border edge.
Definition at line 670 of file Manifold_2.h.
References _mode, _pm, _vID, Pane_manifold_2::get_counterpart(), Simple_manifold_2::get_incident_edge(), Simple_manifold_2::get_incident_real_edge(), Halfedge::pane_manifold(), REAL_PANE, and WHOLE_PANE.
Referenced by Window_manifold_2::determine_primaries(), and is_border().
 {
   Edge_ID eID;
   switch ( _mode) {
   case REAL_PANE:
     eID = _pm->get_incident_real_edge( _vID); break;
   case WHOLE_PANE:
     eID = _pm->get_incident_edge( _vID); break;
   default: {
     eID =_pm->get_incident_real_edge( _vID);
     // the current node (vertex) is in general the origin of the edge or
     // the edge center, unless the node is isolated.
     if ( eID.is_border()) {
       Halfedge h=_pm->get_counterpart( eID);
       if ( h.pane_manifold()) return h;
     }
   }
   }
   return Halfedge(_pm, eID, _mode);
 }
int id () const inline
Obtain the node ID within its Pane_manifold_2.
Definition at line 391 of file Manifold_2.h.
References _vID.
Referenced by Window_manifold_2::assign_global_nodeIDs().
 { return _vID; }
bool is_border () const inline
Is the node on the physical boundary?
Definition at line 668 of file Manifold_2.h.
References halfedge(), and Halfedge::is_border().
 { return halfedge().is_border(); }
bool is_isolated () const inline
Is the node isolated?
Definition at line 413 of file Manifold_2.h.
References _pm, _vID, and Simple_manifold_2::is_isolated_node().
Referenced by Window_manifold_2::determine_primaries().
 { return _pm->is_isolated_node( _vID); }
bool is_primary () const inline
Is the node a primary?
Definition at line 416 of file Manifold_2.h.
References _mode, _pm, _vID, and Pane_manifold_2::is_primary().
 { return _pm->is_primary( _vID, _mode); }
bool operator!= (const Node & n) const inline
Are two nodes different?
Definition at line 430 of file Manifold_2.h.
References _pm, and _vID.
   { return _pm != n._pm || _vID != n._vID; }
bool operator< (const Node & n) const inline
Does the current node has a smaller ID then the given node?
Definition at line 434 of file Manifold_2.h.
References _pm, _vID, and Simple_manifold_2::pane().
{
     return _pm->pane()->id() < n._pm->pane()->id() ||
       _pm == n._pm && _vID < n._vID;
   }
bool operator== (const Node & n) const inline
Are two nodes the same?
Definition at line 426 of file Manifold_2.h.
References _pm, and _vID.
   { return _pm == n._pm && _vID == n._vID; }
const COM::Pane* pane () const inline
Obtain the owner Pane_manifold_2 of the node.
Definition at line 387 of file Manifold_2.h.
References _pm, and Simple_manifold_2::pane().
Referenced by Window_manifold_2::assign_global_nodeIDs().
   { if ( _pm) return _pm->pane(); else return NULL; }
const Pane_manifold_2* pane_manifold () const inline
Obtain the pane manifold that owns the edge.
Definition at line 384 of file Manifold_2.h.
References _pm.
 { return _pm; }
const Point_3<Real>& point () const inline
Obtain the coordinates of a node.
Definition at line 394 of file Manifold_2.h.
References _pm, _vID, and Simple_manifold_2::pane().
Referenced by get_deformed_normal(), and Halfedge::tangent().
   { return (const Point_3<Real>&)_pm->pane()->coordinates()[ 3*_vID-3]; }
void removeElement (Element * elem)
Definition at line 102 of file Node.cpp.
References d_elements, d_numElements, and i.
Referenced by QCoElement::replaceFaceNode(), TCoElement::replaceFaceNode(), Element::replaceNode(), HexElement::~HexElement(), QCoElement::~QCoElement(), TCoElement::~TCoElement(), and TetElement::~TetElement().
{
   int i;
   int dif = 0;
   for( i = 0; i < d_numElements; i++ ){
     if( (dif == 0) && (d_elements[i] == element) ){
       dif++;
       continue;
     }
     if( dif > 0 ){
       d_elements[i - dif] = d_elements[i];
     }
   }
   d_numElements -= dif;
 }
void removeFace (Face * face)
Definition at line 70 of file Node.cpp.
References d_faces, d_numFaces, and i.
Referenced by Face::replaceNode(), QuadFace::~QuadFace(), and TriFace::~TriFace().
{
   int i;
   int dif = 0;
   for( i = 0; i < d_numFaces; i++ ){
     if( (dif == 0) && (d_faces[i] == face) ){
       dif++;
       continue;
     }
     if( dif > 0 ){
       d_faces[i - dif] = d_faces[i];
     }
   }
   d_numFaces -= dif;
 }
boolean separate (Mesh * mesh, FaceList * list, int new_material)
Definition at line 162 of file Node.cpp.
References Mesh::addNode(), d_flag, d_position, FALSE, getSeparateElements(), Node(), Mesh::replaceNode(), separate(), and TRUE.
Referenced by Mesh::addCohesive(), and separate().
{
   //Use the facelist to get a list of involved elements, and see if they can
   //be separated or not.  This method should be called getSeparableElements. It
   //returns an element list with the involved elements if separable, empty if not
   //separable.
   ElementList* sep_elements = getSeparateElements( list );
   if( !sep_elements ){ //not a separable node.
     return FALSE;
   }
   //Its separable - make a new node at the same position, and add it to the mesh.
   //Note that it should have the same nodeflag as the initial node.
   Node *new_node = new Node(d_position, d_flag);
   mesh->addNode( new_node );
   //now we have to go back to the mesh class... kind of wierd design.
   mesh->replaceNode(this, new_node, sep_elements, new_material );
   delete sep_elements;
   // now can call separate again for this & for new_node
   // recursion to separate further
   new_node->separate( mesh, list, new_material );
   separate( mesh, list, new_material);
   return TRUE;
 }
void setFlag (int flag) inline
Definition at line 153 of file Node.hpp.
References d_flag.
Referenced by operator>>().
 { d_flag = flag; }
void setID (int theID) inline
Definition at line 116 of file Node.hpp.
References d_ID.
Referenced by Mesh::addNode(), and Mesh::removeNode().
 { d_ID = theID; }
void setPosition (MVec pos) inline
Definition at line 122 of file Node.hpp.
References d_position.
 { d_position = pos; }
Face * sharedFace (Node * n2, Node * n3, Node * n4 = 0)
Definition at line 118 of file Node.cpp.
References d_faces, d_numFaces, Face::getNodes(), Face::getNumNodes(), i, and k.
Referenced by HexElement::setFaceFromNodes(), TetElement::setFaceFromNodes(), TCoElement::setFaceFromNodes(), and QCoElement::setFaceFromNodes().
{
   int i;
   for( i = 0; i < d_numFaces; i++ ){
     Node** fnodes = d_faces[i]->getNodes();
     int numn = d_faces[i]->getNumNodes();
     int count=0;
     int k;
     for( k = 0; k < numn; k++ ){
       if( fnodes[k] == n2 || fnodes[k] == n3 || fnodes[k] == n4){
         count++;
       }
     }
     if( ( n4 == 0 && count == 2) || count == 3 ){
       return d_faces[i];
     }
   }
   return 0;
 }
Friends And Related Function Documentation
ostream& operator<< (ostream & stream, Node & n) friend
Definition at line 156 of file Node.hpp.
{
   stream << n.d_ID << '\t' << n.d_position << endl;
   return stream;
 }
istream& operator>> (istream & stream, Node & n) friend
Definition at line 161 of file Node.hpp.
{
   stream >> n.d_ID >> n.d_position;
   return stream;
 }
Member Data Documentation
Access_Mode _mode protected
Definition at line 442 of file Manifold_2.h.
Referenced by coincide(), get_primary(), halfedge(), and is_primary().
const Pane_manifold_2* _pm protected
Definition at line 440 of file Manifold_2.h.
Referenced by addr(), attr(), coincide(), get_primary(), halfedge(), is_isolated(), is_primary(), operator!=(), operator<(), operator==(), pane(), pane_manifold(), and point().
int _vID protected
Definition at line 441 of file Manifold_2.h.
Referenced by addr(), coincide(), get_primary(), halfedge(), id(), is_isolated(), is_primary(), operator!=(), operator<(), operator==(), and point().
int d_elementArraySize private
Definition at line 111 of file Node.hpp.
Referenced by addElement(), and ~Node().
Element* * d_elements private
Definition at line 110 of file Node.hpp.
Referenced by addElement(), getAllElements(), getElement(), getSeparateElements(), removeElement(), and ~Node().
int d_faceArraySize private
Definition at line 107 of file Node.hpp.
Referenced by addFace(), and ~Node().
Face* * d_faces private
Definition at line 106 of file Node.hpp.
Referenced by addFace(), getAllFaces(), getFace(), getSeparateElements(), removeFace(), sharedFace(), and ~Node().
int d_flag private
Definition at line 102 of file Node.hpp.
Referenced by getFlag(), separate(), and setFlag().
int d_ID private
Definition at line 100 of file Node.hpp.
Referenced by getID(), operator<<(), operator>>(), and setID().
Node* d_nextNode private
Definition at line 104 of file Node.hpp.
Referenced by addNextLink().
int d_numElements private
Definition at line 112 of file Node.hpp.
Referenced by addElement(), getNumElements(), getSeparateElements(), and removeElement().
int d_numFaces private
Definition at line 108 of file Node.hpp.
Referenced by addFace(), getNumFaces(), getSeparateElements(), removeFace(), and sharedFace().
MVec d_position private
Definition at line 99 of file Node.hpp.
Referenced by getPosition(), operator<<(), operator>>(), separate(), and setPosition().
The documentation for this class was generated from the following files:
Manifold_2.h
Node.hpp
Manifold_2.C
Node.cpp