Rocstar: Bbox_3 Class Reference
Bbox_3 Class Reference
#include <Bbox_3.h>
Public Member Functions
Bbox_3 ()
Bbox_3 (double x_min, double y_min, double zmin, double x_max, double y_max, double z_max)
double xmin () const
double ymin () const
double zmin () const
double xmax () const
double ymax () const
double zmax () const
Bbox_3 operator+ (const Bbox_3 &b) const
Bbox_3 ()
Bbox_3 (double x_min, double y_min, double z_min, double x_max, double y_max, double z_max)
template<class Point3 >
Bbox_3 (const Point3 &p)
double xmin () const
double ymin () const
double zmin () const
double xmax () const
double ymax () const
double zmax () const
Bbox_3 operator+ (const Bbox_3 &b) const
Bbox_3 & operator+= (const Bbox_3 &b)
bool do_match (const Bbox_3 &bb, double tol) const
Private Attributes
double _min [3]
double _max [3]
Detailed Description
Definition at line 65 of file CGAL/include/CGAL/Bbox_3.h.
Constructor & Destructor Documentation
Bbox_3 () inline
Definition at line 83 of file CGAL/include/CGAL/Bbox_3.h.
Referenced by operator+().
 { new ( static_cast< void*>(ptr)) Sixtuple<double>(); }
Bbox_3 (double x_min, double y_min, double zmin, double x_max, double y_max, double z_max) inline
Definition at line 87 of file CGAL/include/CGAL/Bbox_3.h.
 {
   new ( static_cast< void*>(ptr)) Sixtuple<double>(x_min, y_min, z_min,
                                                    x_max, y_max, z_max);
 }
Bbox_3 () inline
Definition at line 36 of file include/CGAL/Bbox_3.h.
References _max, and _min.
            {
     _min[0] = _min[1] = _min[2] = HUGE_VAL;
     _max[0] = _max[1] = _max[2] = -HUGE_VAL;
   }
Bbox_3 (double x_min, double y_min, double z_min, double x_max, double y_max, double z_max) inline
Definition at line 41 of file include/CGAL/Bbox_3.h.
References _max, and _min.
{
     _min[0]=x_min; _min[1]=y_min; _min[2]=z_min;
     _max[0]=x_max; _max[1]=y_max; _max[2]=z_max;
   }
Bbox_3 (const Point3 & p) inline explicit
Definition at line 48 of file include/CGAL/Bbox_3.h.
References _max, and _min.
{
     _min[0]=p[0]; _min[1]=p[1]; _min[2]=p[2];
     _max[0]=p[0]; _max[1]=p[1]; _max[2]=p[2];
   }
Member Function Documentation
bool do_match (const Bbox_3 & bb, double tol) const inline
Definition at line 83 of file include/CGAL/Bbox_3.h.
References NTS::abs(), xmax(), xmin(), ymax(), ymin(), zmax(), and zmin().
Referenced by Overlay::overlay().
{
     return (std::abs(xmax()-bb.xmax()) <= tol &&
             std::abs(xmin()-bb.xmin()) <= tol &&
             std::abs(ymax()-bb.ymax()) <= tol &&
             std::abs(ymin()-bb.ymin()) <= tol &&
             std::abs(zmax()-bb.zmax()) <= tol &&
             std::abs(zmin()-bb.zmin()) <= tol);
   }
Bbox_3 operator+ (const Bbox_3 & b) const inline
Definition at line 64 of file include/CGAL/Bbox_3.h.
{
     Bbox_3 box=*this; box+=b; return box;
   }
Bbox_3 operator+ (const Bbox_3 & b) const inline
Definition at line 123 of file CGAL/include/CGAL/Bbox_3.h.
References Bbox_3(), max(), min(), xmax(), xmin(), ymax(), ymin(), zmax(), and zmin().
 {
   return Bbox_3(std::min(xmin(), b.xmin()),
                 std::min(ymin(), b.ymin()),
                 std::min(zmin(), b.zmin()),
                 std::max(xmax(), b.xmax()),
                 std::max(ymax(), b.ymax()),
                 std::max(zmax(), b.zmax()));
 }
Bbox_3& operator+= (const Bbox_3 & b) inline
Definition at line 68 of file include/CGAL/Bbox_3.h.
References _max, _min, max(), and min().
{
     _min[0] = std::min(_min[0], b._min[0]);
     _min[1] = std::min(_min[1], b._min[1]);
     _min[2] = std::min(_min[2], b._min[2]);
     _max[0] = std::max(_max[0], b._max[0]);
     _max[1] = std::max(_max[1], b._max[1]);
     _max[2] = std::max(_max[2], b._max[2]);
     return *this;
   }
double xmax () const inline
Definition at line 60 of file include/CGAL/Bbox_3.h.
References _max.
 { return _max[0]; }
double xmax () const inline
Definition at line 111 of file CGAL/include/CGAL/Bbox_3.h.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator+(), operator<<(), and Overlay::overlay().
 { return ptr->e3; }
double xmin () const inline
Definition at line 57 of file include/CGAL/Bbox_3.h.
References _min.
 { return _min[0]; }
double xmin () const inline
Definition at line 96 of file CGAL/include/CGAL/Bbox_3.h.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator+(), operator<<(), and Overlay::overlay().
 { return ptr->e0; }
double ymax () const inline
Definition at line 61 of file include/CGAL/Bbox_3.h.
References _max.
 { return _max[1]; }
double ymax () const inline
Definition at line 116 of file CGAL/include/CGAL/Bbox_3.h.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator+(), operator<<(), and Overlay::overlay().
 { return ptr->e4; }
double ymin () const inline
Definition at line 58 of file include/CGAL/Bbox_3.h.
References _min.
 { return _min[1]; }
double ymin () const inline
Definition at line 101 of file CGAL/include/CGAL/Bbox_3.h.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator+(), operator<<(), and Overlay::overlay().
 { return ptr->e1; }
double zmax () const inline
Definition at line 62 of file include/CGAL/Bbox_3.h.
References _max.
 { return _max[2]; }
double zmax () const inline
Definition at line 121 of file CGAL/include/CGAL/Bbox_3.h.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator+(), operator<<(), Overlay::overlay(), peri_cocnlinitsolution(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_3d(), plag_rflu_initsolutionrandom(), prep_modbcdistribution::profinflowvttaylorcyl(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_openprobefile(), rflu_modoles::rflu_buildstencilsoles(), rflu_modprobes::rflu_findprobecells(), rflu_pickregionscoord(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modgeometrytools::rflu_testinboundbox(), rocflo_blocks(), and select_bbx().
 { return ptr->e5; }
double zmin () const inline
Definition at line 59 of file include/CGAL/Bbox_3.h.
References _min.
 { return _min[2]; }
double zmin () const inline
Definition at line 106 of file CGAL/include/CGAL/Bbox_3.h.
Referenced by do_match(), do_overlap(), do_overlap_eps(), do_overlap_strict(), equal(), operator+(), operator<<(), Overlay::overlay(), peri_cocnlinitsolution(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_3d(), plag_rflu_initsolutionrandom(), prep_modbcdistribution::profinflowvttaylorcyl(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_openprobefile(), rflu_modoles::rflu_buildstencilsoles(), rflu_modprobes::rflu_findprobecells(), rflu_initflowhardcode(), rflu_pickregionscoord(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modgeometrytools::rflu_testinboundbox(), rocflo_blocks(), and select_bbx().
 { return ptr->e2; }
Member Data Documentation
double _max[3] private
Definition at line 93 of file include/CGAL/Bbox_3.h.
Referenced by Bbox_3(), operator+=(), xmax(), ymax(), and zmax().
double _min[3] private
Definition at line 93 of file include/CGAL/Bbox_3.h.
Referenced by Bbox_3(), operator+=(), xmin(), ymin(), and zmin().
The documentation for this class was generated from the following files:
CGAL/include/CGAL/Bbox_3.h
include/CGAL/Bbox_3.h