Rocstar: Pane_node_enumerator Class Reference
Pane_node_enumerator Class Reference
#include <Pane_node_accessors.h>
Public Member Functions
Pane_node_enumerator ()
Pane_node_enumerator (const Pane *pane, int i, const Connectivity *conn=NULL)
Constructor for an element in a structured or an unstructured mesh.
int next ()
Go to the next element within the connectivity tables of a pane.
int dimension () const
Get the dimension of the base pane.
int id () const
Get the local id of the element within the pane.
const Pane * pane () const
Protected Member Functions
bool position_allowed3D ()
Determine in the current node number is a real node or a ghost node If it is a ghost node, return false.
bool position_allowed2D ()
Determine in the current node number is a real node or a ghost node If it is a ghost node, return false.
void set_first ()
Protected Attributes
const Pane * _pane
const Connectivity * _conn
int _node_num
int ni
int nj
int nk
int _buffer
int _size_of_nodes
Detailed Description
Definition at line 40 of file Pane_node_accessors.h.
Constructor & Destructor Documentation
Pane_node_enumerator () inline
Definition at line 42 of file Pane_node_accessors.h.
 : _pane(NULL){}
COM_BEGIN_NAME_SPACE Pane_node_enumerator (const Pane * pane, int i, const Connectivity * conn = NULL)
Constructor for an element in a structured or an unstructured mesh.
If conn==NULL, then i is an element index local to the pane. If conn!=NULL, then i is an element index local to the connectivity.
Definition at line 33 of file Pane_node_accessors.C.
References _buffer, _node_num, _pane, _size_of_nodes, COM_assertion, Pane::dimension(), i, Pane::is_unstructured(), ni, nj, nk, set_first(), Pane::size_i(), Pane::size_j(), Pane::size_k(), Pane::size_of_ghost_layers(), and Pane::size_of_nodes().
   : _pane(pane), _conn( _pane->is_structured()?NULL:
                         (conn==NULL?pane->connectivity(i-1):conn))
 {
   if ( _pane->is_unstructured()) {
         if (i == 0) {
                 _node_num = 1;
                 _size_of_nodes = _pane->size_of_nodes();
         }
   }
   else if ( _pane->dimension()==2) {
         ni = _pane->size_i();
         nj = _pane->size_j();
         nk=1;
         _buffer = _pane->size_of_ghost_layers() - i;
         _buffer = _buffer < 0 ? 0 : _buffer;
         _node_num = 1;
         set_first();
   } else  if ( _pane->dimension()==3) {
         ni = _pane->size_i();
         nj = _pane->size_i();
         nk = _pane->size_k();
         _buffer = _pane->size_of_ghost_layers() - i;
         _buffer = _buffer < 0 ? 0 : _buffer;
         _node_num = 1;
         set_first();
     } else {
     COM_assertion(false); // Not yet supported.
     }
 }
Member Function Documentation
int dimension () const inline
Get the dimension of the base pane.
Definition at line 54 of file Pane_node_accessors.h.
References _pane, and Pane::dimension().
 { return _pane->dimension(); }
int id () const inline
Get the local id of the element within the pane.
Definition at line 57 of file Pane_node_accessors.h.
References _node_num.
                  {
           return _node_num;
   }
int next ()
Go to the next element within the connectivity tables of a pane.
Return the next allowed node number.
For structured meshes with ghost layers, one cannot number sequentially, so this method iterates to the next allowed node number
Definition at line 103 of file Pane_node_accessors.C.
References _node_num, _pane, _size_of_nodes, COM_assertion, Pane::dimension(), Pane::is_unstructured(), position_allowed2D(), and position_allowed3D().
{
   if (_node_num == _size_of_nodes)
           return _node_num;
   if (_pane->is_unstructured()) {
           return _node_num++;
   }
   else if (_pane->dimension()==2) { // Structured mesh
     _node_num++;
     while (!position_allowed2D()){
             _node_num++;
     }
     return _node_num;
   }
   else if (_pane->dimension()==3) {
     _node_num++;
     while (!position_allowed3D()){
             _node_num++;
     }
     return _node_num++;
   }
   else {
     COM_assertion(false); // Not yet supported.
     return -1;
   }
 }
const Pane* pane () const inline
Definition at line 62 of file Pane_node_accessors.h.
References _pane.
 { return _pane; }
bool position_allowed2D () protected
Determine in the current node number is a real node or a ghost node If it is a ghost node, return false.
Definition at line 86 of file Pane_node_accessors.C.
References _buffer, _node_num, ni, nj, and nk.
Referenced by next().
{
         int indx = _node_num - 1;
         if (((indx%(ni*nj))/ni) < _buffer)  //too near top
                 return false;
              else if ( indx%ni < _buffer )  //too far left
                      return false;
                   else if ( indx%ni > (ni-_buffer) ) //too far right
                           return false;
                        else if ( (indx%(ni*nj))/ni > (nk-_buffer) ) //too near bottom
                                return false;
                             else return true;
 }
bool position_allowed3D () protected
Determine in the current node number is a real node or a ghost node If it is a ghost node, return false.
Definition at line 67 of file Pane_node_accessors.C.
References _buffer, _node_num, ni, nj, and nk.
Referenced by next().
{
         int indx = _node_num - 1;
         if (indx < ni*nj*_buffer) //too low
                 return false;
         else if (((indx%(ni*nj))/ni) < _buffer)  //too near top
                 return false;
              else if ( indx%ni < _buffer )  //too far left
                      return false;
                   else if ( indx%ni > (ni-_buffer) ) //too far right
                           return false;
                        else if ( (indx%(ni*nj))/ni > (nk-_buffer) ) //too near bottom
                                return false;
                             else if  ( indx > ni*nj*(nk-_buffer) ) //too high
                                     return false;
                             else return true;
 }
void set_first () inline protected
Definition at line 75 of file Pane_node_accessors.h.
References _buffer, _node_num, ni, and nj.
Referenced by Pane_node_enumerator().
                    {
           _node_num = ni*nj*_buffer + ni*_buffer + _buffer+1;
   }
Member Data Documentation
int _buffer protected
Definition at line 73 of file Pane_node_accessors.h.
Referenced by Pane_node_enumerator(), position_allowed2D(), position_allowed3D(), and set_first().
const Connectivity* _conn protected
Definition at line 66 of file Pane_node_accessors.h.
int _node_num protected
Definition at line 69 of file Pane_node_accessors.h.
Referenced by id(), next(), Pane_node_enumerator(), position_allowed2D(), position_allowed3D(), and set_first().
const Pane* _pane protected
Definition at line 65 of file Pane_node_accessors.h.
Referenced by dimension(), next(), pane(), and Pane_node_enumerator().
int _size_of_nodes protected
Definition at line 74 of file Pane_node_accessors.h.
Referenced by next(), and Pane_node_enumerator().
int ni protected
Definition at line 70 of file Pane_node_accessors.h.
Referenced by Pane_node_enumerator(), position_allowed2D(), position_allowed3D(), and set_first().
int nj protected
Definition at line 71 of file Pane_node_accessors.h.
Referenced by Pane_node_enumerator(), position_allowed2D(), position_allowed3D(), and set_first().
int nk protected
Definition at line 72 of file Pane_node_accessors.h.
Referenced by Pane_node_enumerator(), position_allowed2D(), and position_allowed3D().
The documentation for this class was generated from the following files:
Pane_node_accessors.h
Pane_node_accessors.C