Rocstar: rflu_modextractflowdatautils Module Reference
rflu_modextractflowdatautils Module Reference
Public Member Functions
subroutine, public rflu_extractshocklocation1d (pRegion, icgBeg, icgEnd, nCellsX, xs)
Private Attributes
character(chrlen), parameter,
private rcsidentstring = '$RCSfile: RFLU_ModExtractFlowDataUtils.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 43 of file RFLU_ModExtractFlowDataUtils.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_extractshocklocation1d (type(t_region), pointer pRegion, integer, intent(in) icgBeg, integer, intent(in) icgEnd, integer, intent(in) nCellsX, real(rfreal), intent(out) xs)
Definition at line 114 of file RFLU_ModExtractFlowDataUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Color::r(), moderror::registerfunction(), sign(), and x.
Referenced by rflu_modextractflowdata::rflu_extractflowdatasommspi(), and rflu_modextractflowdata::rflu_extractflowdatastg1d().
Member Data Documentation
character(chrlen), parameter, private rcsidentstring = '$RCSfile: RFLU_ModExtractFlowDataUtils.F90,v $ $Revision: 1.4 $' private
Definition at line 67 of file RFLU_ModExtractFlowDataUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModExtractFlowDataUtils.F90