Rocstar: rflo_modvolmeshsmoothing Module Reference
rflo_modvolmeshsmoothing Module Reference
Public Member Functions
subroutine, public rflo_movegridvms (regions)
subroutine rflo_vmsinit (regions, someMoved)
subroutine rflo_vmslaplaceiterate (regions, iter, resid)
subroutine rflo_vmsaveragevertices (region, vxyz)
subroutine rflo_vmslaplaceperturb (region)
subroutine rflo_vmslaplaceprocedure (region, iter)
subroutine rflo_vmsprojectvertices (region, vxyz)
subroutine rflo_vmsrestorebounddeform (region, ibn, ien, dxyz)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModVolMeshSmoothing.F90,v $ $Revision: 1.8 $'
Detailed Description
Definition at line 39 of file RFLO_ModVolMeshSmoothing.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_movegridvms (type(t_region), dimension(:), pointer regions)
Definition at line 93 of file RFLO_ModVolMeshSmoothing.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacevectors(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_copygeometrydummy(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_laplacegridsmoo(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), rflo_vmsinit(), rflo_vmslaplaceiterate(), sqrt(), and x.
Referenced by rflo_dualtimestepping(), and rflo_timestepping().
subroutine rflo_vmsaveragevertices (type(t_region) region, real(rfreal), dimension(:,:), pointer vxyz)
Definition at line 561 of file RFLO_ModVolMeshSmoothing.F90.
References moderror::deregisterfunction(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_vmslaplaceprocedure().
subroutine rflo_vmsinit (type(t_region), dimension(:), pointer regions, logical someMoved)
Definition at line 265 of file RFLO_ModVolMeshSmoothing.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), and rflo_getdeformation().
Referenced by rflo_movegridvms().
subroutine rflo_vmslaplaceiterate (type(t_region), dimension(:), pointer regions, integer iter, real(rfreal) resid)
Definition at line 343 of file RFLO_ModVolMeshSmoothing.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), setup_py::grid(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_calcfacevectors(), rflo_changeinteriorgrid(), rflo_clearsendrequests(), rflo_copygeometrydummy(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_laplacegridpatch(), and rflo_vmslaplaceprocedure().
Referenced by rflo_movegridvms().
subroutine rflo_vmslaplaceperturb (type(t_region) region)
Definition at line 639 of file RFLO_ModVolMeshSmoothing.F90.
References moderror::deregisterfunction(), i, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_vmslaplaceprocedure().
subroutine rflo_vmslaplaceprocedure (type(t_region) region, integer iter)
Definition at line 745 of file RFLO_ModVolMeshSmoothing.F90.
References moderror::deregisterfunction(), moderror::errorstop(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, moderror::registerfunction(), rflo_calccellcentroids(), rflo_calcfacevectors(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), rflo_vmsaveragevertices(), rflo_vmslaplaceperturb(), rflo_vmsprojectvertices(), and rflo_vmsrestorebounddeform().
Referenced by rflo_vmslaplaceiterate().
subroutine rflo_vmsprojectvertices (type(t_region) region, real(rfreal), dimension(:,:), pointer vxyz)
Definition at line 882 of file RFLO_ModVolMeshSmoothing.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ic, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and sqrt().
Referenced by rflo_vmslaplaceprocedure().
subroutine rflo_vmsrestorebounddeform (type(t_region) region, integer ibn, integer ien, real(rfreal), dimension(:,:), pointer dxyz)
Definition at line 1200 of file RFLO_ModVolMeshSmoothing.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
Referenced by rflo_vmslaplaceprocedure().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModVolMeshSmoothing.F90,v $ $Revision: 1.8 $' private
Definition at line 67 of file RFLO_ModVolMeshSmoothing.F90.
The documentation for this module was generated from the following file:
RFLO_ModVolMeshSmoothing.F90