Rocstar: rflu_modreadwritegridspeeds Module Reference
rflu_modreadwritegridspeeds Module Reference
Public Member Functions
subroutine rflu_readgridspeedsbinary (pRegion)
subroutine, public rflu_readgridspeedswrapper (pRegion)
subroutine rflu_writegridspeedsbinary (pRegion)
subroutine, public rflu_writegridspeedswrapper (pRegion)
Private Member Functions
subroutine rflu_readgridspeedsascii (pRegion)
subroutine rflu_writegridspeedsascii (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadWriteGridSpeeds.F90,v $ $Revision: 1.3 $'
Detailed Description
Definition at line 39 of file RFLU_ModReadWriteGridSpeeds.F90.
Member Function/Subroutine Documentation
subroutine rflu_readgridspeedsascii (type(t_region), pointer pRegion) private
Definition at line 91 of file RFLU_ModReadWriteGridSpeeds.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, Mesh::GenericElement::nfaces(), Color::r(), moderror::registerfunction(), and Attribute::status().
Referenced by rflu_readgridspeedswrapper().
subroutine rflu_readgridspeedsbinary (type(t_region), pointer pRegion)
Definition at line 352 of file RFLU_ModReadWriteGridSpeeds.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, Mesh::GenericElement::nfaces(), Color::r(), moderror::registerfunction(), and Attribute::status().
Referenced by rflu_readgridspeedswrapper().
subroutine, public rflu_readgridspeedswrapper (type(t_region), pointer pRegion)
Definition at line 613 of file RFLU_ModReadWriteGridSpeeds.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modrocstario::rflu_genx_getdatagspeedssurf(), rflu_modrocstario::rflu_genx_getdatagspeedsvol(), rflu_readgridspeedsascii(), and rflu_readgridspeedsbinary().
Referenced by rflu_initflowsolver().
subroutine rflu_writegridspeedsascii (type(t_region), pointer pRegion) private
Definition at line 692 of file RFLU_ModReadWriteGridSpeeds.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_writegridspeedswrapper().
subroutine rflu_writegridspeedsbinary (type(t_region), pointer pRegion)
Definition at line 881 of file RFLU_ModReadWriteGridSpeeds.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_writegridspeedswrapper().
subroutine, public rflu_writegridspeedswrapper (type(t_region), pointer pRegion)
Definition at line 1070 of file RFLU_ModReadWriteGridSpeeds.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modrocstario::rflu_genx_decidewritefile(), rflu_modrocstario::rflu_genx_putdatagspeedssurf(), rflu_modrocstario::rflu_genx_putdatagspeedsvol(), rflu_writegridspeedsascii(), and rflu_writegridspeedsbinary().
Referenced by rflu_endflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_timestepping(), and rfluinit().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadWriteGridSpeeds.F90,v $ $Revision: 1.3 $' private
Definition at line 60 of file RFLU_ModReadWriteGridSpeeds.F90.
The documentation for this module was generated from the following file:
RFLU_ModReadWriteGridSpeeds.F90