Rocstar: QualityMetric Class Reference
QualityMetric Class Reference
Base class for concrete quality metrics.
#include <QualityMetric.hpp>
Public Types
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Public Member Functions
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
virtual bool evaluate_element (PatchData &, MsqMeshEntity *, double &, MsqError &err)
Evaluate the metric for an element.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
virtual bool evaluate_element (PatchData &, MsqMeshEntity *, double &, MsqError &err)
Evaluate the metric for an element.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Protected Member Functions
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Protected Attributes
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Private Attributes
ElementEvaluationMode evalMode
MetricType mType
GRADIENT_TYPE gradType
HESSIAN_TYPE hessianType
int negateFlag
Friends
class MsqMeshEntity
Detailed Description
Base class for concrete quality metrics.
Definition at line 64 of file includeLinks/QualityMetric.hpp.
Member Enumeration Documentation
enum AveragingMethod
AveragingMethod allows you to set how the quality metric values attained at each sample point will be averaged together to produce a single metric value for an element.
Enumerator
NONE
LINEAR
RMS
HMS
MINIMUM
MAXIMUM
HARMONIC
GEOMETRIC
SUM
SUM_SQUARED
GENERALIZED_MEAN
STANDARD_DEVIATION
MAX_OVER_MIN
MAX_MINUS_MIN
SUM_OF_RATIOS_SQUARED
NONE
LINEAR
RMS
HMS
MINIMUM
MAXIMUM
HARMONIC
GEOMETRIC
SUM
SUM_SQUARED
GENERALIZED_MEAN
STANDARD_DEVIATION
MAX_OVER_MIN
MAX_MINUS_MIN
SUM_OF_RATIOS_SQUARED
Definition at line 131 of file includeLinks/QualityMetric.hpp.
      {
         NONE,
         LINEAR,
         RMS,
         HMS,
         MINIMUM,
         MAXIMUM,
         HARMONIC,
         GEOMETRIC,
         SUM,
         SUM_SQUARED,
         GENERALIZED_MEAN,
         STANDARD_DEVIATION,
         MAX_OVER_MIN,
         MAX_MINUS_MIN,
         SUM_OF_RATIOS_SQUARED
      };
enum AveragingMethod
AveragingMethod allows you to set how the quality metric values attained at each sample point will be averaged together to produce a single metric value for an element.
Enumerator
NONE
LINEAR
RMS
HMS
MINIMUM
MAXIMUM
HARMONIC
GEOMETRIC
SUM
SUM_SQUARED
GENERALIZED_MEAN
STANDARD_DEVIATION
MAX_OVER_MIN
MAX_MINUS_MIN
SUM_OF_RATIOS_SQUARED
NONE
LINEAR
RMS
HMS
MINIMUM
MAXIMUM
HARMONIC
GEOMETRIC
SUM
SUM_SQUARED
GENERALIZED_MEAN
STANDARD_DEVIATION
MAX_OVER_MIN
MAX_MINUS_MIN
SUM_OF_RATIOS_SQUARED
Definition at line 131 of file src/QualityMetric/QualityMetric.hpp.
      {
         NONE,
         LINEAR,
         RMS,
         HMS,
         MINIMUM,
         MAXIMUM,
         HARMONIC,
         GEOMETRIC,
         SUM,
         SUM_SQUARED,
         GENERALIZED_MEAN,
         STANDARD_DEVIATION,
         MAX_OVER_MIN,
         MAX_MINUS_MIN,
         SUM_OF_RATIOS_SQUARED
      };
enum ElementEvaluationMode
is for metrics of type ELEMENT_BASED only. It allows you to indicate whether we are evaluating the metric based on element vertices, or element gauss points.
Enumerator
EEM_UNDEFINED
ELEMENT_VERTICES
LINEAR_GAUSS_POINTS
QUADRATIC_GAUSS_POINTS
CUBIC_GAUSS_POINTS
EEM_UNDEFINED
ELEMENT_VERTICES
LINEAR_GAUSS_POINTS
QUADRATIC_GAUSS_POINTS
CUBIC_GAUSS_POINTS
Definition at line 111 of file includeLinks/QualityMetric.hpp.
      {
        EEM_UNDEFINED,
        ELEMENT_VERTICES,
        LINEAR_GAUSS_POINTS,
        QUADRATIC_GAUSS_POINTS,
        CUBIC_GAUSS_POINTS
      };
enum ElementEvaluationMode
Enumerator
EEM_UNDEFINED
ELEMENT_VERTICES
LINEAR_GAUSS_POINTS
QUADRATIC_GAUSS_POINTS
CUBIC_GAUSS_POINTS
EEM_UNDEFINED
ELEMENT_VERTICES
LINEAR_GAUSS_POINTS
QUADRATIC_GAUSS_POINTS
CUBIC_GAUSS_POINTS
Definition at line 111 of file src/QualityMetric/QualityMetric.hpp.
      {
        EEM_UNDEFINED,
        ELEMENT_VERTICES,
        LINEAR_GAUSS_POINTS,
        QUADRATIC_GAUSS_POINTS,
        CUBIC_GAUSS_POINTS
      };
enum GRADIENT_TYPE
Sets to either NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT
Enumerator
NUMERICAL_GRADIENT
ANALYTICAL_GRADIENT
NUMERICAL_GRADIENT
ANALYTICAL_GRADIENT
Definition at line 205 of file includeLinks/QualityMetric.hpp.
      {
         NUMERICAL_GRADIENT,
         ANALYTICAL_GRADIENT
      };
enum GRADIENT_TYPE
Enumerator
NUMERICAL_GRADIENT
ANALYTICAL_GRADIENT
NUMERICAL_GRADIENT
ANALYTICAL_GRADIENT
Definition at line 205 of file src/QualityMetric/QualityMetric.hpp.
      {
         NUMERICAL_GRADIENT,
         ANALYTICAL_GRADIENT
      };
enum HESSIAN_TYPE
Sets to either NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN
Enumerator
NUMERICAL_HESSIAN
ANALYTICAL_HESSIAN
NUMERICAL_HESSIAN
ANALYTICAL_HESSIAN
Definition at line 217 of file includeLinks/QualityMetric.hpp.
      {
         NUMERICAL_HESSIAN,
         ANALYTICAL_HESSIAN
      };
enum HESSIAN_TYPE
Enumerator
NUMERICAL_HESSIAN
ANALYTICAL_HESSIAN
NUMERICAL_HESSIAN
ANALYTICAL_HESSIAN
Definition at line 217 of file src/QualityMetric/QualityMetric.hpp.
      {
         NUMERICAL_HESSIAN,
         ANALYTICAL_HESSIAN
      };
enum MetricType
is a property of the metric. It should be set correctly in the constructor of the concrete QualityMetric. An example of a (mediocre) VERTEX_BASED metric is the smallest edge connected to a vertex. An example of a (mediocre) ELEMENT_BASED metric is the aspect ratio of an element.
Enumerator
MT_UNDEFINED
VERTEX_BASED
ELEMENT_BASED
VERTEX_BASED_FREE_ONLY
MT_UNDEFINED
VERTEX_BASED
ELEMENT_BASED
VERTEX_BASED_FREE_ONLY
Definition at line 97 of file includeLinks/QualityMetric.hpp.
      {
         MT_UNDEFINED,
         VERTEX_BASED,
         ELEMENT_BASED,
         VERTEX_BASED_FREE_ONLY
      };
enum MetricType
Enumerator
MT_UNDEFINED
VERTEX_BASED
ELEMENT_BASED
VERTEX_BASED_FREE_ONLY
MT_UNDEFINED
VERTEX_BASED
ELEMENT_BASED
VERTEX_BASED_FREE_ONLY
Definition at line 97 of file src/QualityMetric/QualityMetric.hpp.
      {
         MT_UNDEFINED,
         VERTEX_BASED,
         ELEMENT_BASED,
         VERTEX_BASED_FREE_ONLY
      };
Constructor & Destructor Documentation
QualityMetric () inline protected
Constructor defaults concrete QualityMetric's to gradType=NUMERCIAL_GRADIENT and negateFlag=1. Concrete QualityMetric constructors over-write these defaults when appropriate.
Definition at line 72 of file includeLinks/QualityMetric.hpp.
                      :
        evalMode(EEM_UNDEFINED),
        mType(MT_UNDEFINED),
        gradType(NUMERICAL_GRADIENT),
        hessianType(NUMERICAL_HESSIAN),
        negateFlag(1)
      {}
virtual ~QualityMetric () inline virtual
Definition at line 86 of file includeLinks/QualityMetric.hpp.
         {};
QualityMetric () inline protected
Constructor defaults concrete QualityMetric's to gradType=NUMERCIAL_GRADIENT and negateFlag=1. Concrete QualityMetric constructors over-write these defaults when appropriate.
Definition at line 72 of file src/QualityMetric/QualityMetric.hpp.
                      :
        evalMode(EEM_UNDEFINED),
        mType(MT_UNDEFINED),
        gradType(NUMERICAL_GRADIENT),
        hessianType(NUMERICAL_HESSIAN),
        negateFlag(1)
      {}
virtual ~QualityMetric () inline virtual
Definition at line 86 of file src/QualityMetric/QualityMetric.hpp.
         {};
Member Function Documentation
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError & err) protected
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
Parameters
metric_values : As input, a set of quality metric values to average. As output, the fraction of the corresponding gradient vector that contributes to the average gradient.
num_metric_values The number of values in the passed array.
Definition at line 495 of file QualityMetric/QualityMetric.cpp.
References cimg_library::exp(), i, MsqError::INVALID_STATE, cimg_library::log(), MAXIMUM, Mesquite::MSQ_MIN, MSQ_SETERR, and sqrt().
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), and IdealWeightMeanRatio::compute_element_analytical_gradient().
 {
   double avg = 0.0;
   int i, tmp_count;
   double f;
   switch (avgMethod)
   {
   case MINIMUM:
     avg = metrics[0];
     for (i = 1; i < count; ++i)
       if (metrics[i] < avg)
         avg = metrics[i];
     tmp_count = 0;
     for (i = 0; i < count; ++i)
     {
       if( metrics[i] - avg <= MSQ_MIN )
       {
         metrics[i] = 1.0;
         ++tmp_count;
       }
       else
       {
         metrics[i] = 0.0;
       }
     }
     f = 1.0 / tmp_count;
     for (i = 0; i < count; ++i)
       metrics[i] *= f;
     break;
   case MAXIMUM:
     avg = metrics[0];
     for (i = 1; i < count; ++i)
       if (metrics[i] > avg)
         avg = metrics[i];
     tmp_count = 0;
     for (i = 0; i < count; ++i)
     {
       if( avg - metrics[i] <= MSQ_MIN )
       {
         metrics[i] = 1.0;
         ++tmp_count;
       }
       else
       {
         metrics[i] = 0.0;
       }
     }
     f = 1.0 / tmp_count;
     for (i = 0; i < count; ++i)
       metrics[i] *= f;
     break;
   case SUM:
     for (i = 0; i < count; ++i)
     {
       avg += metrics[i];
       metrics[i] = 1.0;
     }
     break;
   case SUM_SQUARED:
     for (i = 0; i < count; ++i)
     {
       avg += (metrics[i]*metrics[i]);
       metrics[i] *= 2;
     }
     break;
   case LINEAR:
     f = 1.0 / count;
     for (i = 0; i < count; ++i)
     {
       avg += metrics[i];
       metrics[i] = f;
     }
     avg *= f;
     break;
   case GEOMETRIC:
     for (i = 0; i < count; ++i)
       avg += log(metrics[i]);
     avg = exp( avg/count );
     f = avg / count;
     for (i = 0; i < count; ++i)
       metrics[i] = f / metrics[i];
     break;
   case RMS:
     for (i = 0; i < count; ++i)
       avg += metrics[i] * metrics[i];
     avg = sqrt( avg / count );
     f = 1. / (avg*count);
     for (i = 0; i < count; ++i)
       metrics[i] *= f;
     break;
   case HARMONIC:
     for (i = 0; i < count; ++i)
       avg += 1.0 / metrics[i];
     avg = count / avg;
     for (i = 0; i < count; ++i)
       metrics[i] = (avg * avg) / (count * metrics[i] * metrics[i]);
     break;
   case HMS:
     for (i = 0; i < count; ++i)
       avg += 1. / (metrics[i] * metrics[i]);
     avg = sqrt( count / avg );
     f = avg*avg*avg / count;
     for (i = 0; i < count; ++i)
       metrics[i] = f / (metrics[i] * metrics[i] * metrics[i]);
     break;
   default:
     MSQ_SETERR(err)("averaging method not available.",MsqError::INVALID_STATE);
   }
   return avg;
 }
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError & err) protected
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
Parameters
metric_values : As input, a set of quality metric values to average. As output, the fraction of the corresponding gradient vector that contributes to the average gradient.
num_metric_values The number of values in the passed array.
double average_metrics (const double metric_values[], const int & num_values, MsqError & err) inline protected
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
average_metrics takes an array of length num_value and averages the contents using averaging method 'method'.
Definition at line 524 of file includeLinks/QualityMetric.hpp.
References QualityMetric::avgMethod, QualityMetric::GEOMETRIC, QualityMetric::HARMONIC, QualityMetric::HMS, i, MsqError::INVALID_ARG, j, QualityMetric::LINEAR, QualityMetric::MAX_MINUS_MIN, QualityMetric::MAX_OVER_MIN, QualityMetric::MAXIMUM, QualityMetric::MINIMUM, Mesquite::MSQ_MAX_CAP, Mesquite::MSQ_MIN, MSQ_SETERR, QualityMetric::NONE, MsqError::NOT_IMPLEMENTED, Mesquite::pow(), QualityMetric::RMS, sqrt(), QualityMetric::STANDARD_DEVIATION, QualityMetric::SUM, QualityMetric::SUM_OF_RATIOS_SQUARED, and QualityMetric::SUM_SQUARED.
Referenced by ConditionNumberQualityMetric::evaluate_element(), ASMQualityMetric::evaluate_element(), UntangleBetaQualityMetric::evaluate_element(), IdealWeightInverseMeanRatio::evaluate_element(), IdealWeightMeanRatio::evaluate_element(), VertexConditionNumberQualityMetric::evaluate_vertex(), EdgeLengthQualityMetric::evaluate_vertex(), LocalSizeQualityMetric::evaluate_vertex(), and EdgeLengthRangeQualityMetric::evaluate_vertex().
    {
        //MSQ_MAX needs to be made global?
      //double MSQ_MAX=1e10;
      double total_value=0.0;
      double temp_value=0.0;
      int i=0;
      int j=0;
        //if no values, return zero
      if (num_values<=0){
        return 0.0;
      }
      switch(avgMethod){
        case GEOMETRIC:
           total_value=1.0;
           for (i=0;i<num_values;++i){
             total_value*=(metric_values[i]);
           }
           total_value=pow(total_value, (1/((double) num_values)));
           break;
        case HARMONIC:
             //ensure no divide by zero, return zero
           for (i=0;i<num_values;++i){
             if(metric_values[i]<MSQ_MIN){
               if(metric_values[i]>MSQ_MIN){
                 return 0.0;
               }
             }
             total_value+=(1/metric_values[i]);
           }
             //ensure no divide by zero, return MSQ_MAX_CAP
           if(total_value<MSQ_MIN){
             if(total_value>MSQ_MIN){
               return MSQ_MAX_CAP;
             }
           }
           total_value=num_values/total_value;
           break;
        case LINEAR:
           for (i=0;i<num_values;++i){
             total_value+=metric_values[i];
           }
           total_value/= (double) num_values;
           break;
        case MAXIMUM:
           total_value = metric_values[0];
           for (i = 1; i < num_values; ++i){
             if (metric_values[i] > total_value){
               total_value = metric_values[i];
             }
           }
           break;
        case MINIMUM:
           total_value = metric_values[0];
           for (i = 1; i < num_values; ++i){
             if (metric_values[i] < total_value) {
               total_value = metric_values[i];
             }
           }
           break;
        case NONE:
           MSQ_SETERR(err)("Averaging method set to NONE", MsqError::INVALID_ARG);
           break;
        case RMS:
           for (i=0;i<num_values;++i){
             total_value+=(metric_values[i]*metric_values[i]);
           }
           total_value/= (double) num_values;
           total_value=sqrt(total_value);
           break;
        case HMS:
           //ensure no divide by zero, return zero
           for (i=0;i<num_values;++i){
             if (metric_values[i]*metric_values[i] < MSQ_MIN) {
               return 0.0;
             }
             total_value += (1.0/(metric_values[i]*metric_values[i]));
           }
           //ensure no divide by zero, return MSQ_MAX_CAP
           if (total_value < MSQ_MIN) {
             return MSQ_MAX_CAP;
           }
           total_value = sqrt(num_values/total_value);
           break;
        case STANDARD_DEVIATION:
           total_value=0;
           temp_value=0;
           for (i=0;i<num_values;++i){
             temp_value+=metric_values[i];
             total_value+=(metric_values[i]*metric_values[i]);
           }
           temp_value/= (double) num_values;
           temp_value*=temp_value;
           total_value/= (double) num_values;
           total_value-=temp_value;
           break;
        case SUM:
           for (i=0;i<num_values;++i){
             total_value+=metric_values[i];
           }
           break;
        case SUM_SQUARED:
           for (i=0;i<num_values;++i){
             total_value+= (metric_values[i]*metric_values[i]);
           }
           break;
        case MAX_MINUS_MIN:
           //total_value used to store the maximum
             //temp_value used to store the minimum
           temp_value=MSQ_MAX_CAP;
           for (i=0;i<num_values;++i){
             if(metric_values[i]<temp_value){
               temp_value=metric_values[i];
             }
             if(metric_values[i]>total_value){
               total_value=metric_values[i];
             }
           }
             //ensure no divide by zero, return MSQ_MAX_CAP
           if (temp_value < MSQ_MIN) {
             return MSQ_MAX_CAP;
           }
           total_value-=temp_value;
           break;
        case MAX_OVER_MIN:
             //total_value used to store the maximum
             //temp_value used to store the minimum
           temp_value=MSQ_MAX_CAP;
           for (i=0;i<num_values;++i){
             if(metric_values[i]<temp_value){
               temp_value=metric_values[i];
             }
             if(metric_values[i]>total_value){
               total_value=metric_values[i];
             }
           }
             //ensure no divide by zero, return MSQ_MAX_CAP
           if (temp_value < MSQ_MIN) {
             return MSQ_MAX_CAP;
           }
           total_value/=temp_value;
           break;
        case SUM_OF_RATIOS_SQUARED:
           for (j=0;j<num_values;++j){
             //ensure no divide by zero, return MSQ_MAX_CAP
             if (metric_values[j] < MSQ_MIN) {
               return MSQ_MAX_CAP;
             }
             for (i=0;i<num_values;++i){
               total_value+=((metric_values[i]/metric_values[j])*
                             (metric_values[i]/metric_values[j]));
             }
           }
           total_value/=(double)(num_values*num_values);
           break;
        default:
             //Return error saying Averaging Method mode not implemented
           MSQ_SETERR(err)("Requested Averaging Method Not Implemented", MsqError::NOT_IMPLEMENTED);
           return 0;
      }
      return total_value;
    }
double average_metrics (const double metric_values[], const int & num_values, MsqError & err) protected
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
void change_metric_type (MetricType t, MsqError & err) virtual
This function is user accessible and virtual. The base class implementation sets an error, because many metrics will only be defined as Element_based or Vertex_based, and this function will not be needed. Some concrete metrics will have both Element_based and Vertex_based definintions, and those metrics will re-implement this function to the MetricType to be changed to either QualityMetric::VERTEX_BASED or QualityMetric::ELEMENT_BASED.
Definition at line 151 of file QualityMetric/QualityMetric.cpp.
References MSQ_SETERR, and MsqError::NOT_IMPLEMENTED.
 {
   MSQ_SETERR(err)("This QualityMetric's MetricType can not be changed.",
                   MsqError::NOT_IMPLEMENTED);
 }
virtual void change_metric_type (MetricType t, MsqError & err) virtual
This function is user accessible and virtual. The base class implementation sets an error, because many metrics will only be defined as Element_based or Vertex_based, and this function will not be needed. Some concrete metrics will have both Element_based and Vertex_based definintions, and those metrics will re-implement this function to the MetricType to be changed to either QualityMetric::VERTEX_BASED or QualityMetric::ELEMENT_BASED.
bool compute_element_analytical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) protected virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
If that function is not over-riden in the concrete class, the base
Parameters description, see QualityMetric::compute_element_gradient() .
Returns
true if the element is valid, false otherwise.
Reimplemented in I_DFT, I_DFT, IdealWeightMeanRatio, IdealWeightMeanRatio, IdealWeightInverseMeanRatio, IdealWeightInverseMeanRatio, RI_DFT, and RI_DFT.
Definition at line 164 of file QualityMetric/QualityMetric.cpp.
References MSQ_CHKERR, and MSQ_PRINT.
Referenced by QualityMetric::compute_element_gradient().
 {
   MSQ_PRINT(1)("QualityMetric has no analytical gradient defined. "
                 "Defaulting to numerical gradient.\n");
   set_gradient_type(NUMERICAL_GRADIENT);
   bool b = compute_element_numerical_gradient(pd, element, free_vtces, grad_vec, num_free_vtx, metric_value, err);
   return !MSQ_CHKERR(err) && b;
 }
virtual bool compute_element_analytical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) protected virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
Reimplemented in I_DFT, I_DFT, IdealWeightMeanRatio, IdealWeightMeanRatio, IdealWeightInverseMeanRatio, IdealWeightInverseMeanRatio, RI_DFT, and RI_DFT.
bool compute_element_analytical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) protected virtual
If that function is not over-riden in the concrete class, the base class function makes it default to a numerical hessian.
For parameters description, see QualityMetric::compute_element_hessian() .
Returns
true if the element is valid, false otherwise.
Reimplemented in I_DFT, I_DFT, IdealWeightMeanRatio, IdealWeightMeanRatio, IdealWeightInverseMeanRatio, IdealWeightInverseMeanRatio, RI_DFT, and RI_DFT.
Definition at line 185 of file QualityMetric/QualityMetric.cpp.
References MSQ_CHKERR, and MSQ_PRINT.
 {
   MSQ_PRINT(1)("QualityMetric has no analytical hessian defined. "
                 "Defaulting to numerical hessian.\n");
   set_hessian_type(NUMERICAL_HESSIAN);
   bool b = compute_element_numerical_hessian(pd, element, free_vtces, grad_vec,
                                            hessian, num_free_vtx, metric_value, err);
   return !MSQ_CHKERR(err) && b;
 }
virtual bool compute_element_analytical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) protected virtual
Reimplemented in I_DFT, I_DFT, IdealWeightMeanRatio, IdealWeightMeanRatio, IdealWeightInverseMeanRatio, IdealWeightInverseMeanRatio, RI_DFT, and RI_DFT.
bool compute_element_gradient (PatchData & pd, MsqMeshEntity * el, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) inline
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
Parameters
free_vtces base address of an array of pointers to the element vertices which are considered free for purposes of computing the gradient. The quality metric gradient relative to each of those vertices is computed and stored in grad_vec.
grad_vec base address of an array of Vector3D where the gradient is stored, in the order specified by the free_vtces array.
num_free_vtx This is the size of the vertices and gradient arrays.
metric_value Since the metric is computed, we return it.
Returns
true if the element is valid, false otherwise.
Definition at line 494 of file includeLinks/QualityMetric.hpp.
References QualityMetric::ANALYTICAL_GRADIENT, QualityMetric::compute_element_analytical_gradient(), QualityMetric::compute_element_numerical_gradient(), QualityMetric::gradType, MSQ_CHKERR, and QualityMetric::NUMERICAL_GRADIENT.
Referenced by LPtoPTemplate::compute_analytical_gradient().
    {
      bool ret=false;
      switch(gradType)
      {
        case NUMERICAL_GRADIENT:
           ret = compute_element_numerical_gradient(pd, el, free_vtces, grad_vec,
                                                   num_free_vtx, metric_value, err);
           MSQ_CHKERR(err);
           break;
        case ANALYTICAL_GRADIENT:
           ret = compute_element_analytical_gradient(pd, el, free_vtces, grad_vec,
                                                    num_free_vtx, metric_value, err);
           MSQ_CHKERR(err);
           break;
      }
      return ret;
    }
bool compute_element_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData & pd, MsqMeshEntity * el, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err)
same as compute_element_gradient(), but fills fixed vertices spots with zeros instead of not returning values for fixed vertices. Also, the vertices are now ordered according to the element vertices array.
Note that for this function, grad_vec should be an array of size the number of vertices in el, not of size num_free_vtx.
Definition at line 205 of file QualityMetric/QualityMetric.cpp.
References PatchData::get_vertex_index(), MsqMeshEntity::get_vertex_indices(), i, and MSQ_CHKERR.
 {
   int i, g, e;
   bool ret;
   Vector3D* grad_vec_nz = new Vector3D[num_free_vtx];
   ret = compute_element_gradient(pd, el, free_vtces, grad_vec_nz,
                                  num_free_vtx, metric_value, err);
   if (MSQ_CHKERR(err)) {
     delete [] grad_vec_nz;
     return false;
   }
   vector<size_t> gv_i;
   gv_i.reserve(num_free_vtx);
   i=0;
   for (i=0; i<num_free_vtx; ++i) {
     gv_i.push_back( pd.get_vertex_index(free_vtces[i]) );
   }
   vector<size_t> ev_i;
   el->get_vertex_indices(ev_i);
   bool inc;
   vector<size_t>::iterator ev;
   vector<size_t>::iterator gv;
   for (ev=ev_i.begin(), e=0; ev!=ev_i.end(); ++ev, ++e) {
     inc = false; g=0;
     gv = gv_i.begin();
     while (gv!=gv_i.end()) {
       if (*ev == *gv) {
         inc = true;
         break;
       }
       ++gv; ++g;
     }
     if (inc == true)
       grad_vec[e] = grad_vec_nz[g];
     else
       grad_vec[e] = 0;
   }
   delete []grad_vec_nz;
   return ret;
 }
bool compute_element_gradient_expanded (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err)
same as compute_element_gradient(), but fills fixed vertices spots with zeros instead of not returning values for fixed vertices. Also, the vertices are now ordered according to the element vertices array.
bool compute_element_hessian (PatchData & pd, MsqMeshEntity * el, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
Parameters
pd PatchData that contains the element which Hessian we want.
el this is the element for which the Hessian will be returned.
free_vtces base address of an array of pointers to the element vertices which are considered free for purposes of computing the hessian. The vertices within this array must be ordered in the same order as the vertices within the element, el. Only the Hessian entries corresponding to a pair of free vertices will be non-zero.
grad_vec this is an array of nve Vector3D, where nve is the total number of vertices in the element. Only the entries corresponding to free vertices specified in free_vtces will be non-zero. The order is the same as the order of the vertices in el.
hessian this is a 1D array of Matrix3D that will contain the upper triangular part of the Hessian. It has size nve*(nve+1)/2, i.e. the number of entries in the upper triangular part of a nve*nve matrix.
num_free_vtx is the number df free vertices in the element. Essentially, this gives the size of free_vtces[]. The gradient array has the size of the number of vertices in the element, regardless.
metric_value Since the metric is computed, we return it.
Returns
true if the element is valid, false otherwise.
Definition at line 81 of file QualityMetric/QualityMetric.cpp.
References PatchData::get_vertex_index(), MsqMeshEntity::get_vertex_indices(), i, MsqError::INTERNAL_ERROR, MSQ_ERRZERO, MSQ_SETERR, and v.
Referenced by LPtoPTemplate::compute_analytical_hessian().
 {
   // first, checks that free vertices order is consistent with the
   // element order.
   vector<size_t> elem_vtx_indices;
   vector<size_t>::const_iterator v;
   el->get_vertex_indices(elem_vtx_indices);
   int i;
   v=elem_vtx_indices.begin();
   for (i=0; i<num_free_vtx; ++i) {
     while ( v!=elem_vtx_indices.end() &&
             *v != pd.get_vertex_index(free_vtces[i]) ) {
       ++v;
     }
     if ( v==elem_vtx_indices.end() ) {
       MSQ_SETERR(err)("free vertices cannot be given in a different"
                       "order than the element's.", MsqError::INTERNAL_ERROR);
       return false;
     }
   }
   bool ret=false;
   switch(hessianType)
     {
     case NUMERICAL_HESSIAN:
       ret = compute_element_numerical_hessian(pd, el, free_vtces, grad_vec, hessian,
                                               num_free_vtx, metric_value, err);
       MSQ_ERRZERO(err);
       break;
     case ANALYTICAL_HESSIAN:
       ret = compute_element_analytical_hessian(pd, el, free_vtces, grad_vec, hessian,
                                                num_free_vtx, metric_value, err);
       MSQ_ERRZERO(err);
       break;
     }
   return ret;
 }
bool compute_element_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
bool compute_element_numerical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) protected
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) protected
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
Parameters description, see QualityMetric::compute_element_gradient() .
Returns
true if the element is valid, false otherwise.
TODO: (MICHAEL) Try to inline this function (currenlty conflicts with MsqVertex.hpp).
Definition at line 262 of file QualityMetric/QualityMetric.cpp.
References MsqError::INTERNAL_ERROR, j, MSQ_CHKERR, MSQ_FUNCTION_TIMER, MSQ_PRINT, MSQ_SETERR, and v.
Referenced by RI_DFT::compute_element_analytical_gradient(), and QualityMetric::compute_element_gradient().
 {
   MSQ_FUNCTION_TIMER( "QualityMetric::compute_element_numerical_gradient" );
   MSQ_PRINT(3)("Computing Numerical Gradient\n");
   bool valid=this->evaluate_element(pd, element, metric_value, err);
   if (MSQ_CHKERR(err) || !valid)
     return false;
   const double delta_C = 10e-6;
   double delta = delta_C;
   const double delta_inv_C = 1. / delta; // avoids division in the loop.
   double delta_inv = delta_inv_C;
   int counter=0;
   double pos=0.0;
   double metric_value1=0;
   const int reduction_limit = 15;
   for (int v=0; v<num_free_vtx; ++v)
   {
     /* gradient in the x, y, z direction */
     for (int j=0;j<3;++j)
     {
         //re-initialize variables.
       valid=false;
       delta = delta_C;
       delta_inv = delta_inv_C;
       counter=0;
         //perturb the node and calculate gradient.  The while loop is a
         //safety net to make sure the epsilon perturbation does not take
         //the element out of the feasible region.
       while(!valid && counter<reduction_limit){
         //save the original coordinate before the perturbation
         pos=(*free_vtces[v])[j];
           // perturb the coordinates of the free vertex in the j direction
           // by delta
         (*free_vtces[v])[j]+=delta;
           //compute the function at the perturbed point location
         valid=this->evaluate_element(pd, element,  metric_value1, err);
         MSQ_CHKERR(err);
           //compute the numerical gradient
         grad_vec[v][j]=(metric_value1-metric_value)*delta_inv;
           // put the coordinates back where they belong
         (*free_vtces[v])[j] = pos;
         ++counter;
         delta*=0.1;
         delta_inv*=10.;
       }
       if(counter>=reduction_limit){
         MSQ_SETERR(err)("Perturbing vertex by delta caused an inverted element.",
                         MsqError::INTERNAL_ERROR);
         return false;
       }
     }
   }
   return true;
 }
bool compute_element_numerical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) protected
bool compute_element_numerical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) protected
Note that for this function, grad_vec should be an array of size the number of vertices in el, not of size num_free_vtx. Entries that do not correspond with the vertices argument array will be null.
For parameters description, see QualityMetric::compute_element_hessian() .
Returns
true if the element is valid, false otherwise.
Definition at line 337 of file QualityMetric/QualityMetric.cpp.
References free_vertex(), PatchData::get_vertex_index(), MsqMeshEntity::get_vertex_indices(), i, j, k, MSQ_CHKERR, MSQ_FUNCTION_TIMER, MSQ_PRINT, v, and MsqMeshEntity::vertex_count().
Referenced by RI_DFT::compute_element_analytical_hessian().
 {
   MSQ_FUNCTION_TIMER( "QualityMetric::compute_element_numerical_hessian" );
   MSQ_PRINT(3)("Computing Numerical Hessian\n");
   bool valid=this->compute_element_gradient_expanded(pd, element, free_vtces, grad_vec,
                                     num_free_vtx, metric_value, err);
   if (MSQ_CHKERR(err) || !valid)
     return false;
   double delta = 10e-6;
   double delta_inv = 1./delta;
   double vj_coord;
   short nve = element->vertex_count();
   Vector3D* grad_vec1 = new Vector3D[nve];
   Vector3D fd;
   vector<size_t> ev_i;
   element->get_vertex_indices(ev_i);
   short w, v, i, j, sum_w, mat_index, k;
   int fv_ind=0; // index in array free_vtces .
   // loop over all vertices in element.
   for (v=0; v<nve; ++v) {
     // finds out whether vertex v in the element is fixed or free,
     // as according to argument free_vtces[]
     bool free_vertex = false;
     for (k=0; k<num_free_vtx; ++k) {
       if ( ev_i[v] == pd.get_vertex_index(free_vtces[k]) )
         free_vertex = true;
     }
     // If vertex is fixed, enters null blocks for that column.
     // Note that null blocks for the row will be taken care of by
     // the gradient null entries.
     if (free_vertex==false) {
       for (w=0; w<nve; ++w) {
         if (v>=w) {
           sum_w = w*(w+1)/2; // 1+2+3+...+w
           mat_index = w*nve+v-sum_w;
           hessian[mat_index] = 0.;
         }
       }
     }
     else  {
     // If vertex is free, use finite difference on the gradient to find the Hessian.
       for (j=0;j<3;++j) {
         // perturb the coordinates of the vertex v in the j direction by delta
         vj_coord = (*free_vtces[fv_ind])[j];
         (*free_vtces[fv_ind])[j]+=delta;
         //compute the gradient at the perturbed point location
         valid = this->compute_element_gradient_expanded(pd, element, free_vtces,
                               grad_vec1, num_free_vtx, metric_value, err); MSQ_CHKERR(err);
         assert(valid);
         //compute the numerical Hessian
         for (w=0; w<nve; ++w) {
           if (v>=w) {
             //finite difference to get some entries of the Hessian
             fd = (grad_vec1[w]-grad_vec[w])*delta_inv;
             // For the block at position w,v in a matrix, we need the corresponding index
             // (mat_index) in a 1D array containing only upper triangular blocks.
             sum_w = w*(w+1)/2; // 1+2+3+...+w
             mat_index = w*nve+v-sum_w;
             for (i=0; i<3; ++i)
               hessian[mat_index][i][j] = fd[i];
           }
         }
         // put the coordinates back where they belong
         (*free_vtces[fv_ind])[j] = vj_coord;
       }
       ++fv_ind;
     }
   }
   delete[] grad_vec1;
   return true;
 }
virtual bool compute_vertex_analytical_gradient (PatchData & pd, MsqVertex & vertex, MsqVertex * vertices[], Vector3D grad_vec[], int num_vtx, double & metric_value, MsqError & err) protected virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
bool compute_vertex_analytical_gradient (PatchData & pd, MsqVertex & vertex, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) protected virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
If that function is not over-riden in the concrete class, the base class function makes it default to a numerical gradient.
Parameters
vertex Vertex which is considered free for purposes of computing the gradient.
grad_vec Vector where the gradient is stored.
metric_value Since the metric is computed, we return it.
Returns
true if the element is valid, false otherwise.
Definition at line 135 of file QualityMetric/QualityMetric.cpp.
References MSQ_CHKERR, and MSQ_PRINT.
Referenced by QualityMetric::compute_vertex_gradient().
 {
   MSQ_PRINT(1)("QualityMetric has no analytical gradient defined. "
                             "Defaulting to numerical gradient.\n");
   set_gradient_type(NUMERICAL_GRADIENT);
   bool b = compute_vertex_numerical_gradient(pd, vertex, free_vtces, grad_vec,
                                            num_free_vtx, metric_value, err);
   return !MSQ_CHKERR(err) && b;
 }
bool compute_vertex_gradient (PatchData & pd, MsqVertex & vertex, MsqVertex * vertices[], Vector3D grad_vec[], int num_vtx, double & metric_value, MsqError & err)
For MetricType == VERTEX_BASED. Calls either compute_vertex_numerical_gradient or compute_vertex_analytical_gradient for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
Returns
true if the element is valid, false otherwise.
bool compute_vertex_gradient (PatchData & pd, MsqVertex & vertex, MsqVertex * vertices[], Vector3D grad_vec[], int num_vtx, double & metric_value, MsqError & err) inline
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
For MetricType == VERTEX_BASED. Calls either compute_vertex_numerical_gradient or compute_vertex_analytical_gradient for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
Returns
true if the element is valid, false otherwise.
Definition at line 456 of file includeLinks/QualityMetric.hpp.
References QualityMetric::ANALYTICAL_GRADIENT, QualityMetric::compute_vertex_analytical_gradient(), QualityMetric::compute_vertex_numerical_gradient(), QualityMetric::gradType, MSQ_CHKERR, and QualityMetric::NUMERICAL_GRADIENT.
Referenced by LPtoPTemplate::compute_analytical_gradient().
    {
      bool ret=false;;
      switch(gradType)
      {
        case NUMERICAL_GRADIENT:
           ret = compute_vertex_numerical_gradient(pd, vertex, vertices,
                                                   grad_vec, num_vtx,
                                                   metric_value, err);
           MSQ_CHKERR(err);
           break;
        case ANALYTICAL_GRADIENT:
           ret = compute_vertex_analytical_gradient(pd, vertex, vertices,
                                                    grad_vec,num_vtx,
                                                    metric_value, err);
           MSQ_CHKERR(err);
           break;
      }
      return ret;
    }
bool compute_vertex_numerical_gradient (PatchData & pd, MsqVertex & vertex, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) protected
Non-virtual function which numerically computes the gradient of a QualityMetric of a given free vertex. This is used by metric which mType is VERTEX_BASED.
Returns
true if the element is valid, false otherwise.
Numerically calculates the gradient of a vertex-based QualityMetric value on the given free vertex. The metric is evaluated at MsqVertex 'vertex', and the gradient is calculated with respect to the degrees of freedom associated with MsqVertices in the 'vertices' array.
TODO: (MICHAEL) Try to inline this function (currenlty conflicts with MsqVertex.hpp).
Definition at line 431 of file QualityMetric/QualityMetric.cpp.
References j, MSQ_CHKERR, MSQ_ERRZERO, MSQ_PRINT, and v.
Referenced by QualityMetric::compute_vertex_gradient().
 {
   MSQ_PRINT(2)("Computing Gradient (QualityMetric's numeric, vertex based.\n");
   bool valid=this->evaluate_vertex(pd, &(vertex), metric_value, err);
   if (MSQ_CHKERR(err) || !valid)
     return false;
   const double delta = 10e-6;
   const double delta_inv = 1./delta;
   double metric_value1=0;
   double pos;
   int v=0;
   for (v=0; v<num_free_vtx; ++v)
   {
     /* gradient in the x, y, z direction */
     int j=0;
     for (j=0;j<3;++j)
     {
       //save the original coordinate before the perturbation
       pos=(*free_vtces[v])[j];
       // perturb the coordinates of the free vertex in the j direction by delta
       (*free_vtces[v])[j]+=delta;
       //compute the function at the perturbed point location
       this->evaluate_vertex(pd, &(vertex),  metric_value1, err); MSQ_ERRZERO(err);
       //compute the numerical gradient
       grad_vec[v][j]=(metric_value1-metric_value)*delta_inv;
       // put the coordinates back where they belong
       (*free_vtces[v])[j] = pos;
     }
   }
   return true;
 }
bool compute_vertex_numerical_gradient (PatchData & pd, MsqVertex & vertex, MsqVertex * vertices[], Vector3D grad_vec[], int num_vtx, double & metric_value, MsqError & err) protected
Non-virtual function which numerically computes the gradient of a QualityMetric of a given free vertex. This is used by metric which mType is VERTEX_BASED.
Returns
true if the element is valid, false otherwise.
virtual bool evaluate_element (PatchData & , MsqMeshEntity * , double & , MsqError & err) virtual
Evaluate the metric for an element.
Reimplemented in I_DFT, I_DFT, IdealWeightMeanRatio, IdealWeightMeanRatio, AddQualityMetric, AddQualityMetric, IdealWeightInverseMeanRatio, IdealWeightInverseMeanRatio, MultiplyQualityMetric, MultiplyQualityMetric, AspectRatioGammaQualityMetric, AspectRatioGammaQualityMetric, CornerJacobianQualityMetric, UntangleBetaQualityMetric, UntangleBetaQualityMetric, CornerJacobianQualityMetric, GeneralizedConditionNumberQualityMetric, GeneralizedConditionNumberQualityMetric, ASMQualityMetric, ASMQualityMetric, PowerQualityMetric, PowerQualityMetric, RI_DFT, RI_DFT, ConditionNumberQualityMetric, sI_DFT, sRI_DFT, sI_DFT, sRI_DFT, ConditionNumberQualityMetric, ScalarAddQualityMetric, ScalarMultiplyQualityMetric, ScalarAddQualityMetric, and ScalarMultiplyQualityMetric.
bool evaluate_element (PatchData & , MsqMeshEntity * , double & , MsqError & err) virtual
Evaluate the metric for an element.
Reimplemented in I_DFT, I_DFT, IdealWeightMeanRatio, IdealWeightMeanRatio, AddQualityMetric, AddQualityMetric, IdealWeightInverseMeanRatio, IdealWeightInverseMeanRatio, MultiplyQualityMetric, MultiplyQualityMetric, AspectRatioGammaQualityMetric, AspectRatioGammaQualityMetric, CornerJacobianQualityMetric, UntangleBetaQualityMetric, UntangleBetaQualityMetric, CornerJacobianQualityMetric, GeneralizedConditionNumberQualityMetric, GeneralizedConditionNumberQualityMetric, ASMQualityMetric, ASMQualityMetric, PowerQualityMetric, PowerQualityMetric, RI_DFT, RI_DFT, ConditionNumberQualityMetric, sI_DFT, sRI_DFT, sI_DFT, sRI_DFT, ConditionNumberQualityMetric, ScalarAddQualityMetric, ScalarMultiplyQualityMetric, ScalarAddQualityMetric, and ScalarMultiplyQualityMetric.
Definition at line 485 of file QualityMetric/QualityMetric.cpp.
References MSQ_SETERR, and MsqError::NOT_IMPLEMENTED.
Referenced by NonSmoothSteepestDescent::compute_function(), LInfTemplate::concrete_evaluate(), MaxTemplate::concrete_evaluate(), LPtoPTemplate::concrete_evaluate(), ScalarAddQualityMetric::evaluate_element(), ScalarMultiplyQualityMetric::evaluate_element(), PowerQualityMetric::evaluate_element(), MultiplyQualityMetric::evaluate_element(), and AddQualityMetric::evaluate_element().
         {
           MSQ_SETERR(err)("No implementation for a element-version of this "
                           "metric.", MsqError::NOT_IMPLEMENTED);
           return false;
         }
bool evaluate_vertex (PatchData & , MsqVertex * , double & , MsqError & err) virtual
Evaluate the metric for a vertex.
Reimplemented in EdgeLengthRangeQualityMetric, EdgeLengthRangeQualityMetric, AddQualityMetric, AddQualityMetric, LocalSizeQualityMetric, LocalSizeQualityMetric, MultiplyQualityMetric, MultiplyQualityMetric, EdgeLengthQualityMetric, EdgeLengthQualityMetric, GeneralizedConditionNumberQualityMetric, GeneralizedConditionNumberQualityMetric, PowerQualityMetric, PowerQualityMetric, ScalarAddQualityMetric, ScalarMultiplyQualityMetric, ScalarAddQualityMetric, ScalarMultiplyQualityMetric, VertexConditionNumberQualityMetric, and VertexConditionNumberQualityMetric.
Definition at line 475 of file QualityMetric/QualityMetric.cpp.
References MSQ_SETERR, and MsqError::NOT_IMPLEMENTED.
Referenced by LInfTemplate::concrete_evaluate(), MaxTemplate::concrete_evaluate(), LPtoPTemplate::concrete_evaluate(), ScalarMultiplyQualityMetric::evaluate_vertex(), PowerQualityMetric::evaluate_vertex(), MultiplyQualityMetric::evaluate_vertex(), and AddQualityMetric::evaluate_vertex().
         {
           MSQ_SETERR(err)("No implementation for a "
                       "vertex-version of this metric.",
                       MsqError::NOT_IMPLEMENTED);
           return false;
         }
virtual bool evaluate_vertex (PatchData & , MsqVertex * , double & , MsqError & err) virtual
Evaluate the metric for a vertex.
Reimplemented in EdgeLengthRangeQualityMetric, EdgeLengthRangeQualityMetric, AddQualityMetric, AddQualityMetric, LocalSizeQualityMetric, LocalSizeQualityMetric, MultiplyQualityMetric, MultiplyQualityMetric, EdgeLengthQualityMetric, EdgeLengthQualityMetric, GeneralizedConditionNumberQualityMetric, GeneralizedConditionNumberQualityMetric, PowerQualityMetric, PowerQualityMetric, ScalarAddQualityMetric, ScalarMultiplyQualityMetric, ScalarAddQualityMetric, ScalarMultiplyQualityMetric, VertexConditionNumberQualityMetric, and VertexConditionNumberQualityMetric.
ElementEvaluationMode get_element_evaluation_mode () inline
Returns the evaluation mode for the metric.
Definition at line 124 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::evalMode.
         { return evalMode; }
ElementEvaluationMode get_element_evaluation_mode () inline
Returns the evaluation mode for the metric.
Definition at line 124 of file includeLinks/QualityMetric.hpp.
References QualityMetric::evalMode.
         { return evalMode; }
int get_feasible_constraint () inline
Returns the feasible flag for this metric.
Definition at line 177 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::feasible.
         { return feasible; }
int get_feasible_constraint () inline
Returns the feasible flag for this metric.
Definition at line 177 of file includeLinks/QualityMetric.hpp.
References QualityMetric::feasible.
Referenced by AddQualityMetric::AddQualityMetric(), MultiplyQualityMetric::MultiplyQualityMetric(), PowerQualityMetric::PowerQualityMetric(), ScalarAddQualityMetric::ScalarAddQualityMetric(), and ScalarMultiplyQualityMetric::ScalarMultiplyQualityMetric().
         { return feasible; }
MetricType get_metric_type () inline
Definition at line 105 of file includeLinks/QualityMetric.hpp.
References QualityMetric::mType.
Referenced by AddQualityMetric::AddQualityMetric(), LPtoPTemplate::compute_analytical_gradient(), LInfTemplate::concrete_evaluate(), MaxTemplate::concrete_evaluate(), LPtoPTemplate::concrete_evaluate(), QualityAssessor::find_or_add(), MultiplyQualityMetric::MultiplyQualityMetric(), PowerQualityMetric::PowerQualityMetric(), ScalarAddQualityMetric::ScalarAddQualityMetric(), and ScalarMultiplyQualityMetric::ScalarMultiplyQualityMetric().
 { return mType; }
MetricType get_metric_type () inline
Definition at line 105 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::mType.
 { return mType; }
msq_std::string get_name () inline
Returns the name of this metric (as a string).
Definition at line 185 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::metricName.
         { return metricName; }
msq_std::string get_name () inline
Returns the name of this metric (as a string).
Definition at line 185 of file includeLinks/QualityMetric.hpp.
References QualityMetric::metricName.
         { return metricName; }
int get_negate_flag () inline
Returns negateFlag.
Definition at line 274 of file includeLinks/QualityMetric.hpp.
References QualityMetric::negateFlag.
Referenced by AddQualityMetric::AddQualityMetric(), LInfTemplate::LInfTemplate(), LPtoPTemplate::LPtoPTemplate(), MaxTemplate::MaxTemplate(), MultiplyQualityMetric::MultiplyQualityMetric(), PowerQualityMetric::PowerQualityMetric(), ScalarAddQualityMetric::ScalarAddQualityMetric(), and ScalarMultiplyQualityMetric::ScalarMultiplyQualityMetric().
         { return negateFlag; }
int get_negate_flag () inline
Returns negateFlag.
Definition at line 274 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::negateFlag.
         { return negateFlag; }
void set_averaging_method (AveragingMethod method, MsqError & err) inline
Set the averaging method for the quality metric. Current options are NONE: the values are not averaged, GEOMETRIC: the geometric average, HARMONIC: the harmonic average, LINEAR: the linear average, MAXIMUM: the maximum value, MINIMUM: the minimum value, RMS: the root-mean-squared average, HMS: the harmonic-mean-squared average, SUM: the sum of the values, SUM_SQUARED: the sum of the squares of the values, GENERALIZED_MEAN: self explainatory, STANDARD_DEVIATION: the standard deviation squared of the values, MAX_MINUS_MIN: the maximum value minus the minum value, MAX_OVER_MIN: the maximum value divided by the minimum value, SUM_OF_RATIOS_SQUARED: (1/(N^2))*(SUM (SUM (v_i/v_j)^2))
Definition at line 424 of file includeLinks/QualityMetric.hpp.
References QualityMetric::avgMethod, QualityMetric::GEOMETRIC, QualityMetric::HARMONIC, QualityMetric::HMS, QualityMetric::LINEAR, QualityMetric::MAX_MINUS_MIN, QualityMetric::MAX_OVER_MIN, QualityMetric::MAXIMUM, QualityMetric::MINIMUM, MSQ_SETERR, QualityMetric::NONE, MsqError::NOT_IMPLEMENTED, QualityMetric::RMS, QualityMetric::STANDARD_DEVIATION, QualityMetric::SUM, QualityMetric::SUM_OF_RATIOS_SQUARED, and QualityMetric::SUM_SQUARED.
Referenced by I_DFT::I_DFT(), LaplacianSmoother::LaplacianSmoother(), RI_DFT::RI_DFT(), ShapeImprovementWrapper::ShapeImprovementWrapper(), sI_DFT::sI_DFT(), and sRI_DFT::sRI_DFT().
   {
     switch(method)
     {
       case(NONE):
       case(GEOMETRIC):
       case(HARMONIC):
       case(LINEAR):
       case(MAXIMUM):
       case(MINIMUM):
       case(RMS):
       case(HMS):
       case(STANDARD_DEVIATION):
       case(SUM):
       case(SUM_SQUARED):
       case(MAX_OVER_MIN):
       case(MAX_MINUS_MIN):
       case(SUM_OF_RATIOS_SQUARED):
         avgMethod=method;
         break;
       default:
        MSQ_SETERR(err)("Requested Averaging Method Not Implemented", MsqError::NOT_IMPLEMENTED);
       };
     return;
   }
void set_averaging_method (AveragingMethod method, MsqError & err) inline
Set the averaging method for the quality metric. Current options are NONE: the values are not averaged, GEOMETRIC: the geometric average, HARMONIC: the harmonic average, LINEAR: the linear average, MAXIMUM: the maximum value, MINIMUM: the minimum value, RMS: the root-mean-squared average, HMS: the harmonic-mean-squared average, SUM: the sum of the values, SUM_SQUARED: the sum of the squares of the values, GENERALIZED_MEAN: self explainatory, STANDARD_DEVIATION: the standard deviation squared of the values, MAX_MINUS_MIN: the maximum value minus the minum value, MAX_OVER_MIN: the maximum value divided by the minimum value, SUM_OF_RATIOS_SQUARED: (1/(N^2))*(SUM (SUM (v_i/v_j)^2))
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError & err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError & err) inline
Sets the evaluation mode for the ELEMENT_BASED metrics.
Definition at line 402 of file includeLinks/QualityMetric.hpp.
References QualityMetric::CUBIC_GAUSS_POINTS, QualityMetric::ELEMENT_VERTICES, QualityMetric::evalMode, MsqError::INVALID_STATE, QualityMetric::LINEAR_GAUSS_POINTS, MSQ_SETERR, QualityMetric::mType, MsqError::NOT_IMPLEMENTED, QualityMetric::QUADRATIC_GAUSS_POINTS, and QualityMetric::VERTEX_BASED.
Referenced by ASMQualityMetric::ASMQualityMetric(), AspectRatioGammaQualityMetric::AspectRatioGammaQualityMetric(), ConditionNumberQualityMetric::ConditionNumberQualityMetric(), CornerJacobianQualityMetric::CornerJacobianQualityMetric(), IdealWeightInverseMeanRatio::IdealWeightInverseMeanRatio(), IdealWeightMeanRatio::IdealWeightMeanRatio(), and UntangleBetaQualityMetric::UntangleBetaQualityMetric().
   {
     if (mType == VERTEX_BASED) {
       MSQ_SETERR(err)("function must only be used for ELEMENT_BASED metrics.", MsqError::INVALID_STATE);
       return;
     }
     switch(mode)
       {
       case(ELEMENT_VERTICES):
       case(LINEAR_GAUSS_POINTS):
       case(QUADRATIC_GAUSS_POINTS):
       case(CUBIC_GAUSS_POINTS):
         evalMode=mode;
         break;
       default:
         MSQ_SETERR(err)("Requested mode not implemented", MsqError::NOT_IMPLEMENTED);
       }
     return;
   }
void set_feasible_constraint (int alpha) inline
Set feasible flag (i.e., does this metric have a feasible region that the mesh must maintain.)
Definition at line 173 of file includeLinks/QualityMetric.hpp.
References QualityMetric::feasible.
         { feasible=alpha; }
void set_feasible_constraint (int alpha) inline
Set feasible flag (i.e., does this metric have a feasible region that the mesh must maintain.)
Definition at line 173 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::feasible.
         { feasible=alpha; }
void set_gradient_type (GRADIENT_TYPE grad) inline
Sets gradType for this metric.
Definition at line 212 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::gradType.
         { gradType=grad; }
void set_gradient_type (GRADIENT_TYPE grad) inline
Sets gradType for this metric.
Definition at line 212 of file includeLinks/QualityMetric.hpp.
References QualityMetric::gradType.
Referenced by I_DFT::I_DFT(), IdealWeightInverseMeanRatio::IdealWeightInverseMeanRatio(), IdealWeightMeanRatio::IdealWeightMeanRatio(), RI_DFT::RI_DFT(), ShapeImprovementWrapper::ShapeImprovementWrapper(), sI_DFT::sI_DFT(), sRI_DFT::sRI_DFT(), and UntangleBetaQualityMetric::UntangleBetaQualityMetric().
         { gradType=grad; }
void set_hessian_type (HESSIAN_TYPE ht) inline
Sets hessianType for this metric.
Definition at line 224 of file includeLinks/QualityMetric.hpp.
References QualityMetric::hessianType.
Referenced by I_DFT::I_DFT(), IdealWeightInverseMeanRatio::IdealWeightInverseMeanRatio(), IdealWeightMeanRatio::IdealWeightMeanRatio(), RI_DFT::RI_DFT(), ShapeImprovementWrapper::ShapeImprovementWrapper(), sI_DFT::sI_DFT(), and sRI_DFT::sRI_DFT().
         { hessianType=ht; }
void set_hessian_type (HESSIAN_TYPE ht) inline
Sets hessianType for this metric.
Definition at line 224 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::hessianType.
         { hessianType=ht; }
void set_metric_type (MetricType t) inline protected
This function should be used in the constructor of every concrete quality metric.
Errors will result if type is left to MT_UNDEFINED.
Definition at line 291 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::mType.
 { mType = t; }
void set_metric_type (MetricType t) inline protected
This function should be used in the constructor of every concrete quality metric.
Errors will result if type is left to MT_UNDEFINED.
Definition at line 291 of file includeLinks/QualityMetric.hpp.
References QualityMetric::mType.
Referenced by AddQualityMetric::AddQualityMetric(), ASMQualityMetric::ASMQualityMetric(), AspectRatioGammaQualityMetric::AspectRatioGammaQualityMetric(), ConditionNumberQualityMetric::ConditionNumberQualityMetric(), CornerJacobianQualityMetric::CornerJacobianQualityMetric(), EdgeLengthQualityMetric::EdgeLengthQualityMetric(), EdgeLengthRangeQualityMetric::EdgeLengthRangeQualityMetric(), I_DFT::I_DFT(), IdealWeightInverseMeanRatio::IdealWeightInverseMeanRatio(), IdealWeightMeanRatio::IdealWeightMeanRatio(), LocalSizeQualityMetric::LocalSizeQualityMetric(), MultiplyQualityMetric::MultiplyQualityMetric(), PowerQualityMetric::PowerQualityMetric(), RI_DFT::RI_DFT(), ScalarAddQualityMetric::ScalarAddQualityMetric(), ScalarMultiplyQualityMetric::ScalarMultiplyQualityMetric(), sI_DFT::sI_DFT(), sRI_DFT::sRI_DFT(), UntangleBetaQualityMetric::UntangleBetaQualityMetric(), and VertexConditionNumberQualityMetric::VertexConditionNumberQualityMetric().
 { mType = t; }
void set_name (msq_std::string st) inline
Sets the name of this metric.
Definition at line 181 of file includeLinks/QualityMetric.hpp.
References QualityMetric::metricName.
Referenced by AddQualityMetric::AddQualityMetric(), ASMQualityMetric::ASMQualityMetric(), AspectRatioGammaQualityMetric::AspectRatioGammaQualityMetric(), ConditionNumberQualityMetric::ConditionNumberQualityMetric(), CornerJacobianQualityMetric::CornerJacobianQualityMetric(), EdgeLengthQualityMetric::EdgeLengthQualityMetric(), EdgeLengthRangeQualityMetric::EdgeLengthRangeQualityMetric(), I_DFT::I_DFT(), I_DFT_Generalized::I_DFT_Generalized(), I_DFT_InverseMeanRatio::I_DFT_InverseMeanRatio(), I_DFT_NoBarrier::I_DFT_NoBarrier(), I_DFT_StrongBarrier::I_DFT_StrongBarrier(), I_DFT_WeakBarrier::I_DFT_WeakBarrier(), IdealWeightInverseMeanRatio::IdealWeightInverseMeanRatio(), IdealWeightMeanRatio::IdealWeightMeanRatio(), LocalSizeQualityMetric::LocalSizeQualityMetric(), MultiplyQualityMetric::MultiplyQualityMetric(), PowerQualityMetric::PowerQualityMetric(), ScalarAddQualityMetric::ScalarAddQualityMetric(), ScalarMultiplyQualityMetric::ScalarMultiplyQualityMetric(), UntangleBetaQualityMetric::UntangleBetaQualityMetric(), and VertexConditionNumberQualityMetric::VertexConditionNumberQualityMetric().
         { metricName=st; }
void set_name (msq_std::string st) inline
Sets the name of this metric.
Definition at line 181 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::metricName.
         { metricName=st; }
void set_negate_flag (int neg) inline
Set the value of QualityMetric's negateFlag. Concrete QualityMetrics should set this flag to -1 if the QualityMetric needs to be maximized.
Definition at line 270 of file src/QualityMetric/QualityMetric.hpp.
References QualityMetric::negateFlag.
         { negateFlag=neg; }
void set_negate_flag (int neg) inline
Set the value of QualityMetric's negateFlag. Concrete QualityMetrics should set this flag to -1 if the QualityMetric needs to be maximized.
Definition at line 270 of file includeLinks/QualityMetric.hpp.
References QualityMetric::negateFlag.
Referenced by AddQualityMetric::AddQualityMetric(), IdealWeightMeanRatio::IdealWeightMeanRatio(), MultiplyQualityMetric::MultiplyQualityMetric(), PowerQualityMetric::PowerQualityMetric(), ScalarAddQualityMetric::ScalarAddQualityMetric(), ScalarMultiplyQualityMetric::ScalarMultiplyQualityMetric(), and IdealWeightInverseMeanRatio::set_metric_power().
         { negateFlag=neg; }
double vertex_barrier_function (double det, double delta) inline
Escobar Barrier Function for Shape and Other Metrics.
Definition at line 191 of file includeLinks/QualityMetric.hpp.
References sqrt().
Referenced by ShapeQualityMetric::condition_number_2d(), and ShapeQualityMetric::condition_number_3d().
             { return 0.5*(det+sqrt(det*det+4*delta*delta)); }
double vertex_barrier_function (double det, double delta) inline
Escobar Barrier Function for Shape and Other Metrics.
Definition at line 191 of file src/QualityMetric/QualityMetric.hpp.
References sqrt().
             { return 0.5*(det+sqrt(det*det+4*delta*delta)); }
double weighted_average_metrics (const double coef[], const double metric_values[], const int & num_values, MsqError & err) protected
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
double weighted_average_metrics (const double coef[], const double metric_values[], const int & num_values, MsqError & err) inline protected
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
Definition at line 708 of file includeLinks/QualityMetric.hpp.
References QualityMetric::avgMethod, i, QualityMetric::LINEAR, MSQ_SETERR, and MsqError::NOT_IMPLEMENTED.
Referenced by sI_DFT::evaluate_element(), and sRI_DFT::evaluate_element().
   {
     //MSQ_MAX needs to be made global?
     //double MSQ_MAX=1e10;
     double total_value=0.0;
     int i=0;
     //if no values, return zero
     if (num_values<=0){
       return 0.0;
     }
     switch(avgMethod){
     case LINEAR:
       for (i=0;i<num_values;++i){
         total_value += coef[i]*metric_values[i];
       }
       total_value /= (double) num_values;
       break;
     default:
       //Return error saying Averaging Method mode not implemented
       MSQ_SETERR(err)("Requested Averaging Method Not Implemented",MsqError::NOT_IMPLEMENTED);
       return 0;
     }
     return total_value;
   }
Friends And Related Function Documentation
MsqMeshEntity friend
Definition at line 387 of file includeLinks/QualityMetric.hpp.
Member Data Documentation
AveragingMethod avgMethod protected
Definition at line 390 of file includeLinks/QualityMetric.hpp.
Referenced by ASMQualityMetric::ASMQualityMetric(), QualityMetric::average_metrics(), IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightMeanRatio::compute_element_analytical_hessian(), ConditionNumberQualityMetric::ConditionNumberQualityMetric(), CornerJacobianQualityMetric::CornerJacobianQualityMetric(), EdgeLengthQualityMetric::EdgeLengthQualityMetric(), EdgeLengthRangeQualityMetric::EdgeLengthRangeQualityMetric(), IdealWeightInverseMeanRatio::IdealWeightInverseMeanRatio(), IdealWeightMeanRatio::IdealWeightMeanRatio(), LocalSizeQualityMetric::LocalSizeQualityMetric(), QualityMetric::set_averaging_method(), UntangleBetaQualityMetric::UntangleBetaQualityMetric(), VertexConditionNumberQualityMetric::VertexConditionNumberQualityMetric(), and QualityMetric::weighted_average_metrics().
ElementEvaluationMode evalMode private
Definition at line 394 of file includeLinks/QualityMetric.hpp.
Referenced by QualityMetric::get_element_evaluation_mode(), and QualityMetric::set_element_evaluation_mode().
int feasible protected
Definition at line 391 of file includeLinks/QualityMetric.hpp.
Referenced by AddQualityMetric::AddQualityMetric(), ASMQualityMetric::ASMQualityMetric(), AspectRatioGammaQualityMetric::AspectRatioGammaQualityMetric(), ConditionNumberQualityMetric::ConditionNumberQualityMetric(), CornerJacobianQualityMetric::CornerJacobianQualityMetric(), EdgeLengthQualityMetric::EdgeLengthQualityMetric(), EdgeLengthRangeQualityMetric::EdgeLengthRangeQualityMetric(), QualityMetric::get_feasible_constraint(), IdealWeightInverseMeanRatio::IdealWeightInverseMeanRatio(), IdealWeightMeanRatio::IdealWeightMeanRatio(), LocalSizeQualityMetric::LocalSizeQualityMetric(), MultiplyQualityMetric::MultiplyQualityMetric(), PowerQualityMetric::PowerQualityMetric(), ScalarAddQualityMetric::ScalarAddQualityMetric(), ScalarMultiplyQualityMetric::ScalarMultiplyQualityMetric(), QualityMetric::set_feasible_constraint(), UntangleBetaQualityMetric::UntangleBetaQualityMetric(), and VertexConditionNumberQualityMetric::VertexConditionNumberQualityMetric().
GRADIENT_TYPE gradType private
Definition at line 396 of file includeLinks/QualityMetric.hpp.
Referenced by QualityMetric::compute_element_gradient(), QualityMetric::compute_vertex_gradient(), and QualityMetric::set_gradient_type().
HESSIAN_TYPE hessianType private
Definition at line 397 of file includeLinks/QualityMetric.hpp.
Referenced by QualityMetric::set_hessian_type().
msq_std::string metricName protected
Definition at line 392 of file includeLinks/QualityMetric.hpp.
Referenced by QualityMetric::get_name(), and QualityMetric::set_name().
MetricType mType private
Definition at line 395 of file includeLinks/QualityMetric.hpp.
Referenced by QualityMetric::get_metric_type(), QualityMetric::set_element_evaluation_mode(), and QualityMetric::set_metric_type().
int negateFlag private
Definition at line 398 of file includeLinks/QualityMetric.hpp.
Referenced by QualityMetric::get_negate_flag(), and QualityMetric::set_negate_flag().
The documentation for this class was generated from the following files:
includeLinks/QualityMetric.hpp
QualityMetric/QualityMetric.cpp