Rocstar: rflu_modcellmapping Module Reference
rflu_modcellmapping Module Reference
Public Member Functions
subroutine, public rflu_nullifycellmapping (pRegion)
subroutine, public rflu_createcellmapping (pRegion)
subroutine, public rflu_buildglob2loccellmapping (pRegion)
subroutine, public rflu_buildloc2globcellmapping (pRegion)
subroutine, public rflu_destroycellmapping (pRegion)
subroutine, public rflu_readloc2globcellmapping (pRegion)
subroutine, public rflu_writeloc2globcellmapping (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCellMapping.F90,v $ $Revision: 1.16 $'
Detailed Description
Definition at line 39 of file RFLU_ModCellMapping.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildglob2loccellmapping (type(t_region), pointer pRegion)
Definition at line 307 of file RFLU_ModCellMapping.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_buildloc2globcellmapping (type(t_region), pointer pRegion)
Definition at line 463 of file RFLU_ModCellMapping.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modcobalt::rflu_convcobalt2rocflu(), and rflupart().
subroutine, public rflu_createcellmapping (type(t_region), pointer pRegion)
Definition at line 181 of file RFLU_ModCellMapping.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifycellmapping().
Referenced by rflu_allocatememorywrapper(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflucells(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_destroycellmapping (type(t_region), pointer pRegion)
Definition at line 648 of file RFLU_ModCellMapping.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifycellmapping().
Referenced by rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_deallocatememorywrapper(), rflu_endflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon2(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_nullifycellmapping (type(t_region), pointer pRegion)
Definition at line 93 of file RFLU_ModCellMapping.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createcellmapping(), and rflu_destroycellmapping().
subroutine, public rflu_readloc2globcellmapping (type(t_region), pointer pRegion)
Definition at line 774 of file RFLU_ModCellMapping.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rfluconv(), rfluinit(), rflupart(), and rflupick().
subroutine, public rflu_writeloc2globcellmapping (type(t_region), pointer pRegion)
Definition at line 1015 of file RFLU_ModCellMapping.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_mergepostprocessregions(), and rflupart().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCellMapping.F90,v $ $Revision: 1.16 $' private
Definition at line 64 of file RFLU_ModCellMapping.F90.
The documentation for this module was generated from the following file:
RFLU_ModCellMapping.F90