Rocstar: StopWatchCollection Class Reference
StopWatchCollection Class Reference
#include <MsqTimer.hpp>
Public Types
typedef size_t Key
typedef size_t Key
Public Member Functions
StopWatchCollection ()
Key add (const msq_std::string &name, bool fail_if_exists=true)
Key get_key (const msq_std::string &name) const
msq_std::string get_string (const Key key)
Gets the string associated with a key.
void get_string (const Key key, msq_std::string &new_string)
Gets the string associated with a key.
void remove (const Key key)
void remove (const msq_std::string &name)
void start (const Key key)
void start (const msq_std::string &name)
void stop (const Key key)
void stop (const msq_std::string &name)
void reset (const Key key)
void reset (const msq_std::string &name)
double total_time (const Key key) const
double total_time (const msq_std::string &name) const
int number_of_starts (const Key key) const
int number_of_starts (const msq_std::string &name) const
int number_of_stop_watches ()
void get_keys_sorted_by_time (msq_std::vector< Key > &sorted_keys)
StopWatchCollection ()
Key add (const msq_std::string &name, bool fail_if_exists=true)
Key get_key (const msq_std::string &name) const
msq_std::string get_string (const Key key)
Gets the string associated with a key.
void get_string (const Key key, msq_std::string &new_string)
Gets the string associated with a key.
void remove (const Key key)
void remove (const msq_std::string &name)
void start (const Key key)
void start (const msq_std::string &name)
void stop (const Key key)
void stop (const msq_std::string &name)
void reset (const Key key)
void reset (const msq_std::string &name)
double total_time (const Key key) const
double total_time (const msq_std::string &name) const
int number_of_starts (const Key key) const
int number_of_starts (const msq_std::string &name) const
int number_of_stop_watches ()
void get_keys_sorted_by_time (msq_std::vector< Key > &sorted_keys)
Private Attributes
msq_std::vector< msq_std::pair
< msq_std::string, StopWatch > > mEntries
Detailed Description
Definition at line 115 of file includeLinks/MsqTimer.hpp.
Member Typedef Documentation
typedef size_t Key
Definition at line 118 of file includeLinks/MsqTimer.hpp.
typedef size_t Key
Definition at line 118 of file src/Misc/MsqTimer.hpp.
Constructor & Destructor Documentation
StopWatchCollection () inline
Definition at line 121 of file includeLinks/MsqTimer.hpp.
       {}
StopWatchCollection () inline
Definition at line 121 of file src/Misc/MsqTimer.hpp.
       {}
Member Function Documentation
Mesquite::StopWatchCollection::Key add (const msq_std::string & name, bool fail_if_exists = true)
Definition at line 139 of file Misc/MsqTimer.cpp.
References i, and key.
 {
     // Don't allow empty name
   if (name == "")
     return 0;
   Key key = get_key(name);
     // If the named stopwatch doesn't exist...
   if (!key)
   {
       // See if there is an unused existing stopwatch
     size_t i;
     for (i = 0; i < mEntries.size(); i++)
     {
       if (mEntries[i].first == "")
       {
         mEntries[i].first = name;
         mEntries[i].second.reset();
         break;
       }
     }
       // If not, create a new one
     if (i == mEntries.size())
     {
       mEntries.push_back(msq_std::pair<msq_std::string, StopWatch>(name, StopWatch()));
     }
     key = i+1;
   }
     // If it already existed...
   else if (fail_if_exists)
     key = 0;
   return key;
 }
Key add (const msq_std::string & name, bool fail_if_exists = true)
Mesquite::StopWatchCollection::Key get_key (const msq_std::string & name) const
Definition at line 178 of file Misc/MsqTimer.cpp.
References i, and key.
Referenced by StopWatchCollection::number_of_starts(), StopWatchCollection::remove(), StopWatchCollection::reset(), StopWatchCollection::start(), StopWatchCollection::stop(), and StopWatchCollection::total_time().
 {
   Key key = 0;
   for (size_t i = 0; i < mEntries.size(); i++)
   {
     if (mEntries[i].first == name)
     {
       key = i + 1;
       break;
     }
   }
   return key;
 }
Key get_key (const msq_std::string & name) const
void get_keys_sorted_by_time (msq_std::vector< Key > & sorted_keys)
Fills a vector of StopWatchCollection::Key in which the Keys are ordered by the associated StopWatch's total_time. The key associated with the largest total_time StopWatch is in the first position of the vector. The key associated with the smallest total_time StopWatch is in the last position of the vector.
Definition at line 269 of file Misc/MsqTimer.cpp.
References i.
Referenced by Mesquite::operator<<().
 {
   int num_watches=mEntries.size();
   int *sorted_indices=new int[num_watches];
   int i=0;
   int counter=0;
   for(i=0;i<num_watches;++i){
     sorted_indices[i]=0;
   }
   double current_max;
   int index_to_max;
     //While we haven't added all of the Keys to the vector
   while(counter<num_watches){
     current_max=-1;
     index_to_max=-1;
       //loop over the times and find the largest remaining
     for(i=0;i<num_watches;++i){
       if(mEntries[i].second.total_time()>current_max && sorted_indices[i]==0){
         current_max=mEntries[i].second.total_time();
         index_to_max=i;
       }
     }
       //Add the key associated with index_to_max and any subsequent
       //keys which are associated with a StopWatch that has a total
       //time equal to current_max;
     for(i=index_to_max;i<num_watches;++i){
       if(mEntries[i].second.total_time()>=current_max && sorted_indices[i]==0)
       {
         counter++;
         sorted_indices[i]=counter;
         sorted_keys.push_back(i+1);
       }
     }
   }
     //clean up
   delete[] sorted_indices;
 }
void get_keys_sorted_by_time (msq_std::vector< Key > & sorted_keys)
msq_std::string get_string (const Key key) inline
Gets the string associated with a key.
Definition at line 137 of file src/Misc/MsqTimer.hpp.
References StopWatchCollection::mEntries.
{
         return mEntries[key-1].first;}
msq_std::string get_string (const Key key) inline
Gets the string associated with a key.
Definition at line 137 of file includeLinks/MsqTimer.hpp.
References StopWatchCollection::mEntries.
Referenced by Mesquite::operator<<().
{
         return mEntries[key-1].first;}
void get_string (const Key key, msq_std::string & new_string) inline
Gets the string associated with a key.
Definition at line 140 of file includeLinks/MsqTimer.hpp.
References StopWatchCollection::mEntries.
{
       new_string=mEntries[key-1].first;}
void get_string (const Key key, msq_std::string & new_string) inline
Gets the string associated with a key.
Definition at line 140 of file src/Misc/MsqTimer.hpp.
References StopWatchCollection::mEntries.
{
       new_string=mEntries[key-1].first;}
int number_of_starts (const Key key) const
int number_of_starts (const Key key) const
Definition at line 254 of file Misc/MsqTimer.cpp.
Referenced by StopWatchCollection::number_of_starts(), and Mesquite::operator<<().
 {
   if (key > 0 &&
       key <= mEntries.size() &&
       mEntries[key-1].first != "")
     return mEntries[key-1].second.number_of_starts();
   else
     return 0;
 }
int number_of_starts (const msq_std::string & name) const inline
Definition at line 170 of file includeLinks/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::number_of_starts().
       { return number_of_starts(get_key(name));}
int number_of_starts (const msq_std::string & name) const inline
Definition at line 170 of file src/Misc/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::number_of_starts().
       { return number_of_starts(get_key(name));}
int number_of_stop_watches () inline
Definition at line 174 of file includeLinks/MsqTimer.hpp.
References StopWatchCollection::mEntries.
{
       return mEntries.size();}
int number_of_stop_watches () inline
Definition at line 174 of file src/Misc/MsqTimer.hpp.
References StopWatchCollection::mEntries.
{
       return mEntries.size();}
void remove (const Key key)
Definition at line 195 of file Misc/MsqTimer.cpp.
 {
     // Get rid of anything at the end of the list
   if (key == mEntries.size())
   {
     mEntries.pop_back();
     while (!mEntries.empty() && mEntries.back().first == "")
     {
       mEntries.pop_back();
     }
   }
   else if (key > 0 && key < mEntries.size())
   {
       // If in the middle of the list, set its name to ""
     mEntries[key-1].first = "";
   }
 }
void remove (const Key key)
void remove (const msq_std::string & name) inline
Definition at line 145 of file includeLinks/MsqTimer.hpp.
References StopWatchCollection::get_key().
       { remove(get_key(name)); }
void remove (const msq_std::string & name) inline
Definition at line 145 of file src/Misc/MsqTimer.hpp.
References StopWatchCollection::get_key().
       { remove(get_key(name)); }
void reset (const Key key)
Definition at line 234 of file Misc/MsqTimer.cpp.
Referenced by StopWatchCollection::reset().
 {
   if (key > 0 &&
       key <= mEntries.size())
     mEntries[key-1].second.reset();
 }
void reset (const Key key)
void reset (const msq_std::string & name) inline
Definition at line 160 of file includeLinks/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::reset().
       { reset(get_key(name)); }
void reset (const msq_std::string & name) inline
Definition at line 160 of file src/Misc/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::reset().
       { reset(get_key(name)); }
void start (const Key key)
void start (const Key key)
Definition at line 216 of file Misc/MsqTimer.cpp.
Referenced by StopWatchCollection::start(), and FunctionTimer::start().
 {
   if (key > 0 &&
       key <= mEntries.size() &&
       mEntries[key-1].first != "")
     mEntries[key-1].second.start();
 }
void start (const msq_std::string & name) inline
Definition at line 150 of file includeLinks/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::start().
       { start(get_key(name)); }
void start (const msq_std::string & name) inline
Definition at line 150 of file src/Misc/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::start().
       { start(get_key(name)); }
void stop (const Key key)
void stop (const Key key)
Definition at line 225 of file Misc/MsqTimer.cpp.
Referenced by StopWatchCollection::stop(), and FunctionTimer::~FunctionTimer().
 {
   if (key > 0 &&
       key <= mEntries.size() &&
       mEntries[key-1].first != "")
     mEntries[key-1].second.stop();
 }
void stop (const msq_std::string & name) inline
Definition at line 155 of file src/Misc/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::stop().
       { stop(get_key(name)); }
void stop (const msq_std::string & name) inline
Definition at line 155 of file includeLinks/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::stop().
       { stop(get_key(name)); }
double total_time (const Key key) const
double total_time (const Key key) const
Definition at line 243 of file Misc/MsqTimer.cpp.
Referenced by Mesquite::operator<<(), and StopWatchCollection::total_time().
 {
   if (key > 0 &&
       key <= mEntries.size() &&
       mEntries[key-1].first != "")
     return mEntries[key-1].second.total_time();
   else
     return 0.0;
 }
double total_time (const msq_std::string & name) const inline
Definition at line 166 of file includeLinks/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::total_time().
       { return total_time(get_key(name)); }
double total_time (const msq_std::string & name) const inline
Definition at line 166 of file src/Misc/MsqTimer.hpp.
References StopWatchCollection::get_key(), and StopWatchCollection::total_time().
       { return total_time(get_key(name)); }
Member Data Documentation
msq_std::vector< msq_std::pair< msq_std::string, StopWatch > > mEntries private
Definition at line 180 of file includeLinks/MsqTimer.hpp.
Referenced by StopWatchCollection::get_string(), and StopWatchCollection::number_of_stop_watches().
The documentation for this class was generated from the following files:
includeLinks/MsqTimer.hpp
Misc/MsqTimer.cpp