Rocstar: tpz_ordered Class Reference
tpz_ordered Class Reference
#include <partition.h>
Public Member Functions
tpz_ordered (string *zheader, string *zdata)
~tpz_ordered ()
virtual void parse_layout ()
virtual bool parse_data (int num_dep_vars, int num_vars, std::vector< std::vector< int > > rFieldMappings, index_order rIndexOrder, std::vector< adj_map > conv_factor, std::vector< adj_map > norm_val)
Public Member Functions inherited from tpzone
tpzone (string *zheader, string *zdata)
virtual ~tpzone ()
Public Member Functions inherited from partition
partition ()
virtual ~partition ()
std::vector< int > get_layout ()
string get_error ()
string get_status ()
int get_num_points ()
points * get_points ()
pnt get_point (int n)
Private Member Functions
void build_point_index (std::vector< std::vector< int > > rFieldMappings)
int get_index_value (int i, int j, int k, index_order rIndexOrder)
Private Attributes
manual_index_pts * data_pts_local
Additional Inherited Members
Protected Member Functions inherited from partition
long double get_adj (std::vector< adj_map > adj, int var)
int GetFieldMapping (std::vector< std::vector< int > > rFieldMapping, int rSearchField)
Protected Attributes inherited from tpzone
string * zheader
string * zdata
Protected Attributes inherited from partition
std::vector< int > p_layout
string error
string status
points * data_pts
bool data_pts_set
Detailed Description
Definition at line 79 of file partition.h.
Constructor & Destructor Documentation
tpz_ordered (string * zheader, string * zdata)
Definition at line 108 of file partition.cpp.
References partition::data_pts, data_pts_local, and partition::data_pts_set.
                                                        : tpzone(zheader, zdata){
     data_pts_local = new manual_index_pts;
     data_pts = data_pts_local;
     data_pts_set = true;
 }
~tpz_ordered ()
Definition at line 115 of file partition.cpp.
{
     return;
 }
Member Function Documentation
void build_point_index (std::vector< std::vector< int > > rFieldMappings) private
Definition at line 249 of file partition.cpp.
References data_pts_local, partition::get_point(), partition::GetFieldMapping(), i, j, k, partition::p_layout, manual_index_pts::set_index(), and manual_index_pts::set_layout().
Referenced by parse_data().
{
     int dimension_0 = GetFieldMapping(rFieldMappings, 0);
     int dimension_1 = GetFieldMapping(rFieldMappings, 1);
     int dimension_2 = GetFieldMapping(rFieldMappings, 2);
     std::vector<int> point_layout;
     for(int i=0; i<p_layout.size(); i++){
         point_layout.push_back(p_layout[i]);
     }
     //Set layout
     data_pts_local->set_layout(point_layout);
     //Build index
     int n=0;
     for(int i=0; i < p_layout[0]; i++){
         for(int j=0; j < p_layout[1]; j++){
             for(int k=0; k < p_layout[2]; k++){
                 std::vector<int> loc;
                 loc.push_back(i);
                 loc.push_back(j);
                 loc.push_back(k);
                 data_pts_local->set_index(n, loc);
                 pnt curr = get_point(n);
                 n++;
             }
         }
     }
 }
int get_index_value (int i, int j, int k, index_order rIndexOrder) private
Definition at line 287 of file partition.cpp.
References i, j, k, index_order::order, and partition::p_layout.
Referenced by parse_data().
{
     if(rIndexOrder.order.size() <= 0 || rIndexOrder.order.size() > 3){
         int index_val =   i * p_layout[ 1 ]
                         + j * p_layout[ 2 ]
                         + k;
         return index_val;
     }
     int vars[3] = {i, j, k};
     int layout[3] = {0, 1, 2};
     for(int dim = 0; dim < rIndexOrder.order.size(); dim++){
         switch( rIndexOrder.order[dim] ){
             case 0 :
                 vars[dim] = i;
                 layout[dim] = 0;
                 break;
             case 1 :
                 vars[dim] = j;
                 layout[dim] = 1;
                 break;
             case 2 :
                 vars[dim] = k;
                 layout[dim] = 2;
                 break;
             default :
                 break;
         }
     }
 /*
     std::cout << "------------------------" << std::endl << std::endl;
     for(int m=0; m<3; m++){
         std::cout << m << ": " << layout[m] << " | " << p_layout[ layout[m] ] << std::endl;
     }
     std::cout << "===========" << std::endl;
     std::cout << "i | " << i << ": " << vars[0] << std::endl;
     std::cout << "j | " << j << ": " << vars[1] << std::endl;
     std::cout << "k | " << k << ": " << vars[2] << std::endl;
     std::cout << std::endl;
 */
     int index_val =   vars[0] * p_layout[ layout[1] ]
                     + vars[1] * p_layout[ layout[2] ]
                     + vars[2];
     return index_val;
 }
bool parse_data (int num_dep_vars, int num_vars, std::vector< std::vector< int > > rFieldMappings, index_order rIndexOrder, std::vector< adj_map > conv_factor, std::vector< adj_map > norm_val) virtual
Reimplemented from partition.
Definition at line 172 of file partition.cpp.
References build_point_index(), partition::data_pts, data_pts_local, partition::get_adj(), get_index_value(), partition::GetFieldMapping(), i, itoa(), Mesquite::length(), nvc::norm(), partition::p_layout, read(), points::set_num_indep_vars(), points::set_num_points(), points::set_num_vars(), points::set_point_val(), partition::status, x, y, z, and tpzone::zdata.
{
     std::stringstream data(std::stringstream::in | std::stringstream::out);
     data << *zdata;
     //Get the length of each dimension
     int length = 1;
     for(int i=0; i < 3; i++){
         length *= p_layout[i];
     }
     //Initialize storage
     data_pts->set_num_points(length);
     data_pts->set_num_vars(num_vars);
     data_pts->set_num_indep_vars(num_vars - num_dep_vars);
     //Read Data
     string out;
     bool swi = false;
     for(int n=0; n<(num_vars); n++){
         long double conv = get_adj(conv_factor, n);
         long double norm = get_adj(norm_val, n);
         int var_location = GetFieldMapping(rFieldMappings, n);
         for(int z=0; z<p_layout[ 2 ]; z++){
             for(int y=0; y<p_layout[ 1 ]; y++){
                 for(int x=0; x<p_layout[ 0 ]; x++){
                     //Read the value
                     data >> out;
                     //Discard data if dimension is mapped to null
                     if(var_location < 0)
                         continue;
                     long double read = strtold(out.c_str(), NULL);
                     //Apply conversion and normalization values
                     read = read * conv * norm;
                     //Calculate the storage index
                     int index_val = get_index_value(x, y, z, rIndexOrder);
 /*
                     std::cout << index_val << " (" << var_location << ") ";
                     std::cout << ": " << "(" << x << ", " << y << ", " << z << ") > ";
                     std::cout << read << std::endl;
 */
                     //Store the point
                     data_pts_local->set_point_val(index_val, var_location, read);
                 }
             }
         }
         //std::cout << std::endl;
     }
     //std::cout << "=====================================================" << std::endl << std::endl;
     //Write Status
     string zs_out("Extracted ");
     zs_out += itoa(length) + " datapoints";
     status = zs_out;
     //Build point index
     build_point_index(rFieldMappings);
     return true;
 }
void parse_layout () virtual
Reimplemented from partition.
Definition at line 119 of file partition.cpp.
References check_non_numeric_str(), partition::error, itoa(), partition::p_layout, readCommaExpression(), partition::status, and tpzone::zheader.
{
     //Get I value
     std::vector<string> i_val = readCommaExpression( *zheader, string("I") );
     if(i_val.size() == 1){
         if( !check_non_numeric_str(string(i_val[0])) )
             p_layout.push_back(atoi(i_val[0].c_str()));
     }
     else{
         error = string("Unable to read I value from zone header");
         p_layout.erase(p_layout.begin(), p_layout.end());
         return;
     }
     //Get J value
     std::vector<string> j_val = readCommaExpression(*zheader, string("J"));
     if(j_val.size() == 1){
         if( !check_non_numeric_str(string(j_val[0])) )
             p_layout.push_back(atoi(j_val[0].c_str()));
     }
     else{
         error = string("Unable to read J value from zone header");
         p_layout.erase(p_layout.begin(), p_layout.end());
         return;
     }
     //Get K value
     std::vector<string> k_val = readCommaExpression(*zheader, string("K"));
     if(k_val.size() == 1){
         if( !check_non_numeric_str(string(k_val[0])) )
             p_layout.push_back(atoi(k_val[0].c_str()));
     }
     else{
         error = string("Unable to read K value from zone header");
         p_layout.erase(p_layout.begin(), p_layout.end());
         return;
     }
     status =  "I = " + itoa(p_layout[0]);
     status += ", J = " + itoa(p_layout[1]);
     status += ", K = " + itoa(p_layout[2]);
 }
Member Data Documentation
manual_index_pts* data_pts_local private
Definition at line 99 of file partition.h.
Referenced by build_point_index(), parse_data(), and tpz_ordered().
The documentation for this class was generated from the following files:
partition.h
partition.cpp