Rocstar: Mesh::GenericCell_2 Class Reference
Mesh::GenericCell_2 Class Reference
#include <Mesh.H>
Public Member Functions
GenericCell_2 (IndexType s=3)
void init (IndexType s=3)
IndexType size () const
GeoPrim::C3Point Centroid ()
IndexType nedges () const
IndexType nvert () const
void ReOrient (std::vector< IndexType > &ec)
GeoPrim::C3Point Centroid (std::vector< IndexType > &ec, NodalCoordinates &nc) const
void shape_func (const GeoPrim::CVector &, double[]) const
void dshape_func (const GeoPrim::CVector &, double[][2]) const
void jacobian (const GeoPrim::CPoint p[], const GeoPrim::CVector &, GeoPrim::CVector J[]) const
void interpolate (const GeoPrim::CVector f[], const GeoPrim::CVector &nc, GeoPrim::CVector &) const
void GetNormalSet (GeoPrim::CVector ns[], IndexType elnum, const Connectivity &ec, const NodalCoordinates &nc)
void GetPointSet (GeoPrim::CPoint ps[], IndexType elnum, const Connectivity &ec, const NodalCoordinates &nc)
void shapef_jacobian_at (const GeoPrim::CPoint &p, GeoPrim::CVector &natc, IndexType elnum, const Connectivity &ec, const NodalCoordinates &nc, GeoPrim::CVector &fvec, GeoPrim::CVector jac[]) const
Protected Attributes
IndexType _size
Detailed Description
Definition at line 556 of file Mesh.H.
Constructor & Destructor Documentation
GenericCell_2 (IndexType s = 3) inline
Definition at line 560 of file Mesh.H.
 : _size(s){};
Member Function Documentation
GeoPrim::C3Point Centroid ()
GeoPrim::C3Point Centroid (std::vector< IndexType > & ec, NodalCoordinates & nc) const
Definition at line 630 of file Mesh.C.
References i.
   {
     GeoPrim::C3Point centroid(0,0,0);
     IndexType i = 0;
     IndexType esize = ec.size();
     while(i < esize)
       centroid += GeoPrim::C3Point(nc[ec[i++]]);
     double scal = 1.0/(static_cast<double>(esize));
     return(centroid *= scal);
   };
void dshape_func (const GeoPrim::CVector & natc, double Np[][2]) const
Definition at line 675 of file Mesh.C.
References _size.
{
     switch ( _size) {
     case 3: {
       Np[0][0] = -1;    Np[0][1] = -1;
       Np[1][0] =  1;    Np[1][1] =  0;
       Np[2][0] =  0;    Np[2][1] =  1;
       return;
     }
     case 4: {
       const double xi = natc[0];
       const double xi_minus = 1. - xi;
       const double eta = natc[1];
       const double eta_minus = 1. - eta;
       Np[0][0] = -eta_minus;   Np[0][1] = -xi_minus;
       Np[1][0] = eta_minus;    Np[1][1] = -xi;
       Np[2][0] = eta;          Np[2][1] = xi;
       Np[3][0] = -eta;         Np[3][1] = xi_minus;
       return;
     }
     default:
       std::cerr << "GenericCell_2::dshape_func:error: Unknown element type."
                 << std::endl;
       exit(1);
     }
   };
void GetNormalSet (GeoPrim::CVector ns[], IndexType elnum, const Connectivity & ec, const NodalCoordinates & nc)
Definition at line 757 of file Mesh.C.
References _size, i, and Mesh::Connectivity::Node().
      {
        GeoPrim::CPoint P[3];
        for(IndexType i = 0;i < _size;i++){
          IndexType i_minus = (i==0 ? _size -1 : i - 1);
          P[i_minus] = nc[ec.Node(elnum,i_minus+1)];
          P[i] = nc[ec.Node(elnum,i+1)];
          IndexType i_plus = (i == (_size-1) ? 0 : i+1);
          P[i_plus] = nc[ec.Node(elnum,i_plus+1)];
          ns[i] = GeoPrim::CVector(P[i] - P[i_minus])%GeoPrim::CVector(P[i_plus] - P[i]);
        }
      };
void GetPointSet (GeoPrim::CPoint ps[], IndexType elnum, const Connectivity & ec, const NodalCoordinates & nc)
Definition at line 773 of file Mesh.C.
References _size, i, init(), and Mesh::Connectivity::Node().
      {
        for(IndexType i = 0;i < _size;i++)
          P[i].init(nc[ec.Node(elnum,i+1)]);
      };
void init (IndexType s = 3) inline
Definition at line 561 of file Mesh.H.
References _size, and s.
Referenced by GetPointSet().
 {_size = s;};
void interpolate (const GeoPrim::CVector f[], const GeoPrim::CVector & nc, GeoPrim::CVector & v) const
Definition at line 810 of file Mesh.C.
References _size, CVector::x(), and CVector::y().
Referenced by main().
   {
     const double xi = nc.x();
     const double eta = nc.y();
     v = f[0];
     switch(_size) {
     case 3: {
       v += ((f[1]-f[0])*=xi) += ((f[2]-f[0])*=eta);
       return;
     }
     case 4: {
       v += ((f[1]-f[0]) *= (xi * (1.-eta)))
         += ((f[3]-f[0]) *= eta)
         += ((f[2]-f[3]) *= xi*eta);
       return;
     }
    case 6: {
       const double zeta=1.-xi-eta;
       v += ((f[1]-f[0]) *= xi * (2.*xi-1.))
         += ((f[3]-f[0]) *= 4.* xi * zeta)
         += ((f[2]-f[0]) *= eta * (2.*eta-1.))
         += ((f[5]-f[0]) *= 4. * eta * zeta)
         += ((f[4]-f[0]) *= 4.*xi*eta);
       return;
     }
     case 8: {
       const double xi_minus = 1. - xi;
       const double eta_minus = 1. - eta;
       v += ((f[1]-f[0]) *= eta * (2.*eta-1.))
         += ((f[3]-f[0]) *= eta)
         += ((f[2]-f[3]) *= xi * eta)
         -= ((((f[0]-f[4])+=(f[1]-f[4])) *= 2.*xi*xi_minus*eta_minus)
             += (((f[2]-f[6])+=(f[3]-f[6])) *= 2.*xi*xi_minus*eta)
             += (((f[1]-f[5])+=(f[2]-f[5])) *= 2.*xi*eta*eta_minus)
             += (((f[0]-f[7])+=(f[3]-f[7])) *= 2.*xi_minus*eta*eta_minus));
       return;
     }
     default:
       assert(false);
     }
     return;
   }
void jacobian (const GeoPrim::CPoint p[], const GeoPrim::CVector & nc, GeoPrim::CVector J[]) const
Definition at line 704 of file Mesh.C.
References _size.
Referenced by cal_shdx().
{
     switch (_size) {
     case 3:
       J[0] = p[1]-p[0]; J[1] = p[2]-p[0];
       return;
     case 4: {
       const double xi        = nc[0];
       const double xi_minus  = 1. - xi;
       const double eta       = nc[1];
       const double eta_minus = 1. - eta;
       J[0] = ((p[1]-p[0]) *= eta_minus) += (( p[2]-p[3]) *= eta );
       J[1] = ((p[3]-p[0]) *= xi_minus) += (( p[2]-p[1]) *= xi);
       return;
     }
     case 6: {
       const double xi   = nc[0];
       const double eta  = nc[1];
       const double zeta = 1.-xi-eta;
       J[0] = ((p[1]-p[0]) *= 4.*xi -1.)
         += ((p[3]-p[0]) *= 4.*zeta-4*xi)
         += ((p[4]-p[5]) *= 4.*eta);
       J[1] = ((p[2]-p[0]) *= 4.*eta -1.)
         += ((p[5]-p[0]) *= 4*zeta-4*eta)
         += ((p[4]-p[3]) *= 4.*xi);
       return;
     }
     case 8: {
       const double xi        = nc[0];
       const double xi_minus  = 1. - xi;
       const double eta       = nc[1];
       const double eta_minus = 1. - eta;
       J[0] = ((p[1]-p[0]) *= eta_minus) += ((p[2]-p[3]) *= eta)
         -= ((((p[0]-p[4])+=(p[1]-p[4])) *= 2.*eta_minus*(xi_minus-xi))
             += (((p[2]-p[6])+=(p[3]-p[6])) *= 2.*eta*(xi_minus-xi))
             += (((p[1]-p[5])+=(p[2]-p[5])-=((p[0]-p[7])+=(p[3]-p[7])))
                 *= 2.*eta*eta_minus));
       ((J[1] = p[3]-p[0]) *= xi_minus) += ((p[2]-p[1]) *= xi)
         -= ((((p[1]-p[5])+=(p[2]-p[5])) *= 2.*xi*(eta_minus-eta))
             += (((p[0]-p[7])+=(p[3]-p[7])) *= 2.*xi_minus*(eta_minus-eta))
             += (((p[2]-p[6])+=(p[1]-p[4])-=((p[3]-p[6])+=(p[0]-p[4])))
                 *= 2.*xi*xi_minus));
       return;
     }
     default:
       abort(); // Should never reach here
     }
   };
IndexType nedges () const inline
Definition at line 564 of file Mesh.H.
References _size.
Referenced by inrt_allocateauxillary(), inrt_augmentdissources(), inrt_calcburning(), inrt_calcscouring(), inrt_defineboilingregulation(), inrt_defineburning(), inrt_definedrag(), inrt_defineheattransfernonburn(), inrt_definescouring(), plag_cecellsexchange(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_cecellsgetbuffersize(), plag_cecellssendsize(), plag_edgecellsloaddata(), plag_edgecellsloadsendbuff(), plag_rflo_findgridmapping(), plag_rflo_recvmetrics(), plag_rflo_sendmetrics(), plag_rflo_sendrecvmetrics(), and rflu_modedgelist::rflu_buildedgelist().
 {return(_size);};
IndexType nvert () const inline
Definition at line 565 of file Mesh.H.
References _size.
Referenced by rflu_modrepair3d::colaps(), plag_modinjection::plag_ejectparticle(), plag_modinjection::plag_injcsetpoolpos(), plag_modinjection::plag_invokeconsrandejec(), plag_modinjection::plag_invokeejecmodel1(), plag_rflu_injectiondriver(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modhashtable::rflu_hashface(), rflu_modhashtable::rflu_hashvertex(), rflu_modhashtable::rflu_hashvertexfancy(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_modtecplotutils::rflu_tec_writezonecellsspecial(), rflu_modtecplotutils::rflu_tec_writezonefacesspecial(), rflu_modtecplotutils::rflu_tec_writezoneinterf(), rflu_modtecplotutils::rflu_tec_writezonevol(), and rflu_modhashtable::rflu_unhashbface().
 {return(_size);};
void ReOrient (std::vector< IndexType > & ec)
Definition at line 856 of file Mesh.C.
References _size.
Referenced by TRAIL_FD2FE_WinCreate2().
   {
     switch(_size) {
     case 3: {
       Mesh::IndexType temp = ec[0];
       ec[0] = ec[1];
       ec[1] = temp;
       return;
     }
     case 4: {
       Mesh::IndexType temp = ec[0];
       ec[0] = ec[1];
       ec[1] = temp;
       temp = ec[2];
       ec[2] = ec[3];
       ec[3] = temp;
       return;
     }
     default:
       assert(false);
     }
     return;
   }
void shape_func (const GeoPrim::CVector & natc, double SF[]) const
Definition at line 643 of file Mesh.C.
References _size.
   {
     switch (_size) {
     case 3: {
       SF[0] = 1. - natc[0] - natc[1];
       SF[1] = natc[0];
       SF[2] = natc[1];
       return;
     }
     case 4: {
       const double xi = natc[0];
       const double xi_minus = 1. - xi;
       const double eta = natc[1];
       const double eta_minus = 1. - eta;
       SF[0] = xi_minus * eta_minus;
       SF[1] = xi * eta_minus;
       SF[2] = xi * eta;
       SF[3] = xi_minus * eta;
       return;
     }
     default:
       std::cerr << "GenericCell_2::shape_func:Error: unkown element type."
                 << std::endl;
       exit(1);
     }
   };
void shapef_jacobian_at (const GeoPrim::CPoint & p, GeoPrim::CVector & natc, IndexType elnum, const Connectivity & ec, const NodalCoordinates & nc, GeoPrim::CVector & fvec, GeoPrim::CVector jac[]) const
Definition at line 784 of file Mesh.C.
References i, CVector::normalize(), and GeoPrim::Transpose().
   {
     GeoPrim::CPoint P[(const IndexType)_size];
     double SF[(const IndexType)_size];
     this->shape_func(natc,SF);
     fvec.init(-1.0*p);
     for(IndexType i = 0;i < _size;i++){
       P[i].init(nc[ec.Node(elnum,i+1)]);
       fvec += SF[i]*P[i];
     }
     GeoPrim::CVector v1(P[0],P[1]);
     GeoPrim::CVector v2(P[0],P[2]);
     this->jacobian(P,natc,jac);
     jac[2] = v1%v2;
     jac[2].normalize();
     Transpose(jac);
   }
IndexType size () const inline
Definition at line 562 of file Mesh.H.
References _size.
 {return(_size);};
Member Data Documentation
IndexType _size protected
Definition at line 558 of file Mesh.H.
Referenced by dshape_func(), GetNormalSet(), GetPointSet(), init(), interpolate(), jacobian(), nedges(), nvert(), ReOrient(), shape_func(), and size().
The documentation for this class was generated from the following files:
Mesh.H
Mesh.C