Rocstar: metric Class Reference
metric Class Reference
#include <metric.h>
Public Member Functions
metric (std::vector< points * > datasets1, std::vector< points * > datasets2, int var_ds1, int var_ds2, ofstream &outfile, string outprefix)
void set_datasets1 (std::vector< points * > datasets1)
void set_datasets2 (std::vector< points * > datasets2)
void setRange (BoundingBox *rangePtr)
virtual string get_res ()
virtual string get_metric_name ()
Protected Member Functions
void error_out (string err_ps)
Protected Attributes
bool restrictToBoxRange
BoundingBox * range
string outprefix
std::vector< points * > datasets1
std::vector< points * > datasets2
int var_ds1
int var_ds2
ofstream & outfile
Detailed Description
Definition at line 35 of file metric.h.
Constructor & Destructor Documentation
metric (std::vector< points * > datasets1, std::vector< points * > datasets2, int var_ds1, int var_ds2, ofstream & outfile, string outprefix)
Definition at line 6 of file metric.cpp.
References datasets1, datasets2, outprefix, var_ds1, and var_ds2.
                                                     : outfile(outfile)
 {
                 this ->restrictToBoxRange = false;
     this->outprefix = outprefix;
     this->datasets1 = datasets1;
     this->datasets2 = datasets2;
     this->var_ds1 = var_ds1;
     this->var_ds2 = var_ds2;
 }
Member Function Documentation
void error_out (string err_ps) protected
Definition at line 38 of file metric.cpp.
References get_metric_name(), and outfile.
{
     string out;
     out = "ERROR   |  Metric \"" + this->get_metric_name() + "\":  " + err_ps;
     outfile << out  << std::endl;
     cout << out << std::endl;
 }
string get_metric_name () virtual
Definition at line 34 of file metric.cpp.
Referenced by compareFiles(), and error_out().
{
     return string("Metric");
 }
string get_res () virtual
Definition at line 30 of file metric.cpp.
Referenced by compareFiles().
                       {
     return string("No Metric Performed");
 }
void set_datasets1 (std::vector< points * > datasets1)
Definition at line 22 of file metric.cpp.
References datasets1.
{
     this->datasets1 = datasets1;
 }
void set_datasets2 (std::vector< points * > datasets2)
Definition at line 26 of file metric.cpp.
References datasets2.
{
     this->datasets2 = datasets2;
 }
void setRange (BoundingBox * rangePtr) inline
Definition at line 46 of file metric.h.
Referenced by compareFiles().
         {
                 if( rangePtr != NULL )
                 {
                         this ->restrictToBoxRange = true;
                         this ->range                                              = rangePtr;
                 }
         }
Member Data Documentation
std::vector<points*> datasets1 protected
Definition at line 68 of file metric.h.
Referenced by metric(), and set_datasets1().
std::vector<points*> datasets2 protected
Definition at line 69 of file metric.h.
Referenced by metric(), and set_datasets2().
ofstream& outfile protected
Definition at line 74 of file metric.h.
Referenced by error_out().
string outprefix protected
Definition at line 66 of file metric.h.
Referenced by metric().
BoundingBox* range protected
Definition at line 64 of file metric.h.
bool restrictToBoxRange protected
Definition at line 63 of file metric.h.
int var_ds1 protected
Definition at line 71 of file metric.h.
Referenced by metric().
int var_ds2 protected
Definition at line 72 of file metric.h.
Referenced by metric().
The documentation for this class was generated from the following files:
metric.h
metric.cpp