Rocstar: blockConsumer Class Reference
blockConsumer Class Reference abstract
#include <gridutil.h>
Public Member Functions
virtual ~blockConsumer ()
const char * read (const char *gridFile)
virtual vector3d * allocateBlock (blockDim &dim)
virtual void freeBlock (vector3d *blk)
virtual const char * consume (const blockDim &dim, vector3d *locs)=0
Detailed Description
Definition at line 239 of file gridutil.h.
Constructor & Destructor Documentation
~blockConsumer () virtual
Definition at line 155 of file read.cpp.
 { }
Member Function Documentation
vector3d * allocateBlock (blockDim & dim) virtual
Definition at line 146 of file read.cpp.
References blockDim::getSize().
Referenced by read_general(), read_hdf(), and read_reg().
 {
         return new vector3d[dim.getSize()];
 }
virtual const char* consume (const blockDim & dim, vector3d * locs) pure virtual
Implemented in blockReader.
Referenced by read_general(), read_hdf(), and read_reg().
void freeBlock (vector3d * blk) virtual
Reimplemented in blockReader.
Definition at line 150 of file read.cpp.
Referenced by read_general(), read_hdf(), and read_reg().
 {
         delete[] blk;
 }
const char * read (const char * gridFile)
Definition at line 140 of file read.cpp.
References read_multiple().
Referenced by main().
 {
         return read_multiple(file,*this);
 }
The documentation for this class was generated from the following files:
gridutil.h
read.cpp