Rocstar: rflu_modpatchutils Module Reference
rflu_modpatchutils Module Reference
Public Member Functions
subroutine, public rflu_buildpatchneighbormaps (pRegion)
subroutine, public rflu_checkpatchbcconsistency (pRegion)
subroutine, public rflu_computepatchnormalsglobal (regions)
subroutine, public rflu_computepatchnormalslocal (pRegion)
subroutine, public rflu_createpatchneighbormaps (pRegion)
subroutine, public rflu_destroypatchneighbormaps (pRegion)
subroutine rflu_setpatchflatflags (global, nxMin, nxMax, nyMin, nyMax, nzMin, nzMax, eqTol, xFlatFlag, yFlatFlag, zFlatFlag)
subroutine, public rflu_getpatchnormaldirection (global, pPatch, pnDir, pnDirFlag)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModPatchUtils.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 39 of file RFLU_ModPatchUtils.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildpatchneighbormaps (type(t_region), pointer pRegion)
Definition at line 108 of file RFLU_ModPatchUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_checkpatchbcconsistency (type(t_region), pointer pRegion)
Definition at line 220 of file RFLU_ModPatchUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modtools::floatequal(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), and rflupart().
subroutine, public rflu_computepatchnormalsglobal (type(t_region), dimension(:), pointer regions)
Definition at line 330 of file RFLU_ModPatchUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), min(), moderror::registerfunction(), and rflu_setpatchflatflags().
Referenced by rflu_initflowsolver().
subroutine, public rflu_computepatchnormalslocal (type(t_region), pointer pRegion)
Definition at line 633 of file RFLU_ModPatchUtils.F90.
References moderror::deregisterfunction(), max(), min(), moderror::registerfunction(), and rflu_setpatchflatflags().
Referenced by rflu_initflowsolver(), and rflupart().
subroutine, public rflu_createpatchneighbormaps (type(t_region), pointer pRegion)
Definition at line 794 of file RFLU_ModPatchUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_destroypatchneighbormaps (type(t_region), pointer pRegion)
Definition at line 887 of file RFLU_ModPatchUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_getpatchnormaldirection (type(t_global), pointer global, type(t_patch), pointer pPatch, integer, intent(out) pnDir, logical, intent(out) pnDirFlag)
Definition at line 1096 of file RFLU_ModPatchUtils.F90.
References moderror::deregisterfunction(), modtools::floatequal(), and moderror::registerfunction().
Referenced by rflu_modstencilsbfaces::rflu_buildbf2cstencil_1d(), and rflu_moddifferentiationbfaces::rflu_computegradbfaces_1d().
subroutine rflu_setpatchflatflags (type(t_global), pointer global, real(rfreal), intent(in) nxMin, real(rfreal), intent(in) nxMax, real(rfreal), intent(in) nyMin, real(rfreal), intent(in) nyMax, real(rfreal), intent(in) nzMin, real(rfreal), intent(in) nzMax, real(rfreal), intent(in) eqTol, logical, intent(out) xFlatFlag, logical, intent(out) yFlatFlag, logical, intent(out) zFlatFlag)
Definition at line 983 of file RFLU_ModPatchUtils.F90.
References moderror::deregisterfunction(), modtools::floatequal(), moderror::registerfunction(), and sign().
Referenced by rflu_computepatchnormalsglobal(), and rflu_computepatchnormalslocal().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModPatchUtils.F90,v $ $Revision: 1.7 $' private
Definition at line 60 of file RFLU_ModPatchUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModPatchUtils.F90