Rocstar: Angle_Metric_2 Class Reference
Angle_Metric_2 Class Reference
2D Max and Min Angle Metric Class
#include <Geometric_Metrics_2.h>
Public Member Functions
Angle_Metric_2 ()
Initialize a 2D Angle Metric.
virtual void compute (double atts[]) const
Calculate max and min angles.
double maxValue () const
The maximum value for this metric.
double minValue () const
The minimum value for this metric.
Public Member Functions inherited from Geo_Metric_Base_2
Geo_Metric_Base_2 ()
Constructor.
virtual void initialize (Vector_3< double > n[], int type)
Initialize a 2D Geometric Metric.
virtual void initialize (Element_node_enumerator &ene)
Public Member Functions inherited from Metric
Metric ()
virtual ~Metric ()
Additional Inherited Members
Protected Member Functions inherited from Geo_Metric_Base_2
void compute_angles (double &min, double &max) const
Compute the min and max angles.
void compute_aspects (double &R, double &r, double &l) const
Compute the circumradius, inradius, and shortest edge length.
Protected Attributes inherited from Geo_Metric_Base_2
Vector_3< double > v [4]
int type_
Detailed Description
2D Max and Min Angle Metric Class
Definition at line 77 of file Geometric_Metrics_2.h.
Constructor & Destructor Documentation
Angle_Metric_2 () inline
Initialize a 2D Angle Metric.
Definition at line 81 of file Geometric_Metrics_2.h.
 {}
Member Function Documentation
void compute (double atts[]) const virtual
Calculate max and min angles.
Parameters
atts[] Two computed values placed here.
Implements Metric.
Definition at line 108 of file Geometric_Metrics_2.C.
Referenced by main().
{
   compute_angles(atts[0],atts[1]);
 }
double maxValue () const virtual
The maximum value for this metric.
Reimplemented from Geo_Metric_Base_2.
Definition at line 112 of file Geometric_Metrics_2.C.
Referenced by main().
{
 return 180.0;
 }
double minValue () const virtual
The minimum value for this metric.
Reimplemented from Geo_Metric_Base_2.
Definition at line 116 of file Geometric_Metrics_2.C.
Referenced by main().
{
 return 0.0;
 }
The documentation for this class was generated from the following files:
Geometric_Metrics_2.h
Geometric_Metrics_2.C