Rocstar: rflu_modtecplotutils Module Reference
rflu_modtecplotutils Module Reference
Public Member Functions
subroutine, public rflu_tec_closefile (global)
subroutine, public rflu_tec_openfile (global, title, fileName)
subroutine, public rflu_tec_writezonecellsspecial (pRegion)
subroutine, public rflu_tec_writezonefacesspecial (pRegion)
subroutine, public rflu_tec_writezoneinterf (pRegion)
subroutine, public rflu_tec_writezonesurf (pRegion, pPatch, faceType, faceKind)
subroutine, public rflu_tec_writezonesurfmixed (pRegion, pPatch)
subroutine, public rflu_tec_writezonevol (pRegion, cellType, cellKind)
Public Attributes
character(1), parameter, public nullchar = CHAR(0)
character(2 *chrlen), public headertec
integer, parameter, public zone_type_tri = 2
integer, parameter, public zone_type_quad = 3
integer, parameter, public zone_type_tet = 4
integer, parameter, public zone_type_hex = 5
integer, parameter, public zone_form_block = 1
integer, parameter, public var_pos_cell = 0
integer, parameter, public var_pos_face = 0
integer, parameter, public var_pos_vert = 1
integer, parameter, public file_type_field = 1
integer, parameter, public file_type_patch = 2
integer, parameter, public file_type_patch_stats = 3
integer, parameter, public file_cntr_tec_max = 10
integer, public debugflagtec
integer, public doubleflagtec
integer, public filecntrtec
integer, public nvarstec
integer, public nvarstottec
integer, public nvarscelltec
integer, public nvarsfacetec
integer, public nvarsverttec
integer, dimension(file_cntr_tec_max),
public filetype2cntrtec
integer, dimension(8),
parameter, public tet2vtec = (/1,2,3,3,4,4,4,4/)
integer, dimension(8),
parameter, public hex2vtec = (/1,2,3,4,5,6,7,8/)
integer, dimension(8),
parameter, public pri2vtec = (/1,2,3,1,4,5,6,4/)
integer, dimension(8),
parameter, public pyr2vtec = (/1,2,3,4,5,5,5,5/)
integer, dimension(:),
allocatable, public postec
real(rfreal), dimension(:,:),
allocatable, public varcelltec
real(rfreal), dimension(:,:),
allocatable, public varfacetec
real(rfreal), dimension(:,:),
allocatable, public varverttec
Private Attributes
character(chrlen), parameter,
private rcsidentstring = '$RCSfile: RFLU_ModTECPLOTUtils.F90,v $ $Revision: 1.14 $'
Detailed Description
Definition at line 43 of file RFLU_ModTECPLOTUtils.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_tec_closefile (type(t_global), pointer global)
Definition at line 139 of file RFLU_ModTECPLOTUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modtecplot::rflu_tec_closefilefield(), rflu_modtecplot::rflu_tec_closefilepatch(), and rflu_modtecplot::rflu_tec_closefilepatchstats().
subroutine, public rflu_tec_openfile (type(t_global), pointer global, character(chrlen) title, character(chrlen) fileName)
Definition at line 213 of file RFLU_ModTECPLOTUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modtecplot::rflu_tec_openfilefield(), rflu_modtecplot::rflu_tec_openfilepatch(), and rflu_modtecplot::rflu_tec_openfilepatchstats().
subroutine, public rflu_tec_writezonecellsspecial (type(t_region), pointer pRegion)
Definition at line 302 of file RFLU_ModTECPLOTUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericCell_2::nvert(), modsortsearch::quicksortinteger(), moderror::registerfunction(), and modsortsearch::simplifysortedintegers().
Referenced by rflu_modtecplot::rflu_tec_writefilefieldvol().
subroutine, public rflu_tec_writezonefacesspecial (type(t_region), pointer pRegion)
Definition at line 646 of file RFLU_ModTECPLOTUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericCell_2::nvert(), modsortsearch::quicksortinteger(), moderror::registerfunction(), and modsortsearch::simplifysortedintegers().
Referenced by rflu_modtecplot::rflu_tec_writefilefieldvol().
subroutine, public rflu_tec_writezoneinterf (type(t_region), pointer pRegion)
Definition at line 928 of file RFLU_ModTECPLOTUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), Mesh::GenericCell_2::nvert(), moderror::registerfunction(), rflu_modcellfaceedgeinfo::rflu_getfacekind(), and rflu_modcellfaceedgeinfo::rflu_getglobalcellkind().
Referenced by rflu_modtecplot::rflu_tec_writefilefieldvol().
subroutine, public rflu_tec_writezonesurf (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) faceType, integer, intent(in) faceKind)
Definition at line 1492 of file RFLU_ModTECPLOTUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modtecplot::rflu_tec_writefilefieldsurf().
subroutine, public rflu_tec_writezonesurfmixed (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 1900 of file RFLU_ModTECPLOTUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modtecplot::rflu_tec_writefilepatch().
subroutine, public rflu_tec_writezonevol (type(t_region), pointer pRegion, integer, intent(in) cellType, integer, intent(in) cellKind)
Definition at line 2095 of file RFLU_ModTECPLOTUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericCell_2::nvert(), and moderror::registerfunction().
Referenced by rflu_modtecplot::rflu_tec_writefilefieldvol().
Member Data Documentation
integer, public debugflagtec
Definition at line 86 of file RFLU_ModTECPLOTUtils.F90.
integer, public doubleflagtec
Definition at line 86 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public file_cntr_tec_max = 10
Definition at line 85 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public file_type_field = 1
Definition at line 82 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public file_type_patch = 2
Definition at line 82 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public file_type_patch_stats = 3
Definition at line 82 of file RFLU_ModTECPLOTUtils.F90.
integer, public filecntrtec
Definition at line 86 of file RFLU_ModTECPLOTUtils.F90.
integer, dimension(file_cntr_tec_max), public filetype2cntrtec
Definition at line 88 of file RFLU_ModTECPLOTUtils.F90.
character(2*chrlen), public headertec
Definition at line 73 of file RFLU_ModTECPLOTUtils.F90.
integer, dimension(8), parameter, public hex2vtec = (/1,2,3,4,5,6,7,8/)
Definition at line 90 of file RFLU_ModTECPLOTUtils.F90.
character(1), parameter, public nullchar = CHAR(0)
Definition at line 72 of file RFLU_ModTECPLOTUtils.F90.
integer, public nvarscelltec
Definition at line 86 of file RFLU_ModTECPLOTUtils.F90.
integer, public nvarsfacetec
Definition at line 86 of file RFLU_ModTECPLOTUtils.F90.
integer, public nvarstec
Definition at line 86 of file RFLU_ModTECPLOTUtils.F90.
integer, public nvarstottec
Definition at line 86 of file RFLU_ModTECPLOTUtils.F90.
integer, public nvarsverttec
Definition at line 86 of file RFLU_ModTECPLOTUtils.F90.
integer, dimension(:), allocatable, public postec
Definition at line 93 of file RFLU_ModTECPLOTUtils.F90.
integer, dimension(8), parameter, public pri2vtec = (/1,2,3,1,4,5,6,4/)
Definition at line 91 of file RFLU_ModTECPLOTUtils.F90.
integer, dimension(8), parameter, public pyr2vtec = (/1,2,3,4,5,5,5,5/)
Definition at line 92 of file RFLU_ModTECPLOTUtils.F90.
character(chrlen), parameter, private rcsidentstring = '$RCSfile: RFLU_ModTECPLOTUtils.F90,v $ $Revision: 1.14 $' private
Definition at line 65 of file RFLU_ModTECPLOTUtils.F90.
integer, dimension(8), parameter, public tet2vtec = (/1,2,3,3,4,4,4,4/)
Definition at line 89 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public var_pos_cell = 0
Definition at line 79 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public var_pos_face = 0
Definition at line 79 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public var_pos_vert = 1
Definition at line 79 of file RFLU_ModTECPLOTUtils.F90.
real(rfreal), dimension(:,:), allocatable, public varcelltec
Definition at line 94 of file RFLU_ModTECPLOTUtils.F90.
real(rfreal), dimension(:,:), allocatable, public varfacetec
Definition at line 94 of file RFLU_ModTECPLOTUtils.F90.
real(rfreal), dimension(:,:), allocatable, public varverttec
Definition at line 94 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public zone_form_block = 1
Definition at line 78 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public zone_type_hex = 5
Definition at line 74 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public zone_type_quad = 3
Definition at line 74 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public zone_type_tet = 4
Definition at line 74 of file RFLU_ModTECPLOTUtils.F90.
integer, parameter, public zone_type_tri = 2
Definition at line 74 of file RFLU_ModTECPLOTUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModTECPLOTUtils.F90