Rocstar: indexed_points Class Reference
indexed_points Class Reference
#include <points.h>
Public Member Functions
indexed_points ()
virtual ~indexed_points ()
indexed_points (const indexed_points &ip)
indexed_points & operator= (const indexed_points &ip)
virtual indexed_points * clone ()
virtual void sort ()
pnt get_indexed_point (std::vector< int > loc)
virtual int get_closest (long double *coord)
virtual std::vector< int > get_connected_points (int point_num)
virtual std::vector< int > get_dim ()
Public Member Functions inherited from points
points ()
points (int num_points)
points (const points &p)
points & operator= (const points &p)
virtual ~points ()
void set_num_points (int n)
void set_num_vars (int n)
void set_num_indep_vars (int indep_vars)
int get_num_points ()
int get_num_vars ()
int get_num_indep_vars ()
void set_point_val (int point_number, int var, long double val)
void clear_dep_vars (int point_number)
pnt get_point (int n)
long double largest_val (int dim)
long double smallest_val (int dim)
Protected Attributes
VariableDimensionArray index
bool index_set
std::vector< int > index_layout
Protected Attributes inherited from points
int num_points
int num_vars
int num_indep_vars
pnt ** pt_str
bitmap pt_set
Additional Inherited Members
Static Public Member Functions inherited from points
static void delete_all (std::vector< points * > points_vector)
static bool contains_null (std::vector< points * > points_vector)
Detailed Description
Definition at line 150 of file points.h.
Constructor & Destructor Documentation
indexed_points ()
Definition at line 393 of file points.cpp.
Referenced by clone().
{
     index_set = false;
     return;
 }
~indexed_points () virtual
Definition at line 398 of file points.cpp.
{
     return;
 }
indexed_points (const indexed_points & ip)
Definition at line 402 of file points.cpp.
References index, index_layout, and index_set.
                                                        : points(ip) {
     index_set = ip.index_set;
     index_layout = ip.index_layout;
     index = ip.index;
 }
Member Function Documentation
indexed_points * clone () virtual
Reimplemented from points.
Reimplemented in manual_index_pts.
Definition at line 425 of file points.cpp.
References indexed_points().
{
     return new indexed_points(*this);
 }
int get_closest (long double * coord) virtual
Reimplemented from points.
Definition at line 440 of file points.cpp.
References dist(), i, points::num_indep_vars, points::num_points, points::pt_str, and pnt::vals.
{
     //TODO
     //Data is ordered;
     //Improve search algorithm
     long double low_dist = std::numeric_limits<long double>::infinity();
     int low_point = -1;
     //Iterate through all points and find the point in the dataset
     //that's closest to the specified point
     for(int i=0; i<num_points; i++){
         long double *d_calc = new long double[num_indep_vars];
             for(int m=0; m<num_indep_vars; m++){
                 d_calc[m] = pt_str[i]->vals[m];
             }
         long double distance = dist(coord, d_calc, num_indep_vars);
         if( distance < low_dist ){
             low_dist = distance;
             low_point = i;
         }
         delete[] d_calc;
     }
     return low_point;
 }
std::vector< int > get_connected_points (int point_num) virtual
Reimplemented from points.
Definition at line 472 of file points.cpp.
References i, index, j, VariableDimensionArray::translate_coord_to_index(), and VariableDimensionArray::translate_index_to_coords().
{
     std::vector<int> coords = index.translate_index_to_coords(point_num);
     std::vector<int> ret;
     //Iterate through each independent variable
     for(int i=0; i<coords.size(); i++){
         std::vector<int> loc;
         //Positive Direction
         for(int j=0; j<coords.size(); j++){
             if(j == i)
                 loc.push_back(coords[j] + 1);
             else
                 loc.push_back(coords[j]);
         }
         int ptup = index.translate_coord_to_index(loc);
         //Erase coordinates
         loc.erase(loc.begin(), loc.end());
         //Negative Direction
         for(int j=0; j<coords.size(); j++){
             if(j == i)
                 loc.push_back(coords[j] - 1);
             else
                 loc.push_back(coords[j]);
         }
         int ptdown = index.translate_coord_to_index(loc);
         if(ptup > 0)
             ret.push_back(ptup);
         if(ptdown > 0)
             ret.push_back(ptdown);
     }
     return ret;
 }
std::vector< int > get_dim () virtual
Definition at line 512 of file points.cpp.
References index_layout.
Referenced by TecplotOrderedWriter::writePartition(), and TecplotOrderedWriter::writePoints().
{
     return index_layout;
 }
pnt get_indexed_point (std::vector< int > loc)
Definition at line 433 of file points.cpp.
References VariableDimensionArray::getValue(), index, and points::pt_str.
{
     int index_loc = index.getValue(loc);
     return *(pt_str[ index_loc ]);
 }
indexed_points & operator= (const indexed_points & ip)
Definition at line 410 of file points.cpp.
References index, index_layout, index_set, and points::operator=().
Referenced by manual_index_pts::operator=().
{
     if(this != &ip){
         points::operator = (ip);
         index_set = ip.index_set;
         index_layout = ip.index_layout;
         index = ip.index;
     }
     return *this;
 }
void sort () virtual
Reimplemented from points.
Definition at line 429 of file points.cpp.
{
     return;
 }
Member Data Documentation
VariableDimensionArray index protected
Definition at line 175 of file points.h.
Referenced by get_connected_points(), get_indexed_point(), indexed_points(), operator=(), manual_index_pts::set_index(), and manual_index_pts::set_layout().
std::vector<int> index_layout protected
Definition at line 178 of file points.h.
Referenced by get_dim(), indexed_points(), and operator=().
bool index_set protected
Definition at line 176 of file points.h.
Referenced by indexed_points(), operator=(), and manual_index_pts::set_layout().
The documentation for this class was generated from the following files:
points.h
points.cpp