Rocstar: modbuildfilenames Module Reference
modbuildfilenames Module Reference
Public Member Functions
subroutine, public buildfilenamebasic (global, dest, ext, regId, fileName)
subroutine, public buildfilenameplain (global, dest, ext, fileName)
subroutine, public buildfilenameplainsteady (global, dest, ext, it, fileName)
subroutine, public buildfilenameplainunsteady (global, dest, ext, tm, fileName)
subroutine, public buildfilenamesteady (global, dest, ext, regId, it, fileName)
subroutine, public buildfilenameunsteady (global, dest, ext, regId, tm, fileName)
subroutine, public buildregionidstring (global, regId, regIdString)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: ModBuildFileNames.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file ModBuildFileNames.F90.
Member Function/Subroutine Documentation
subroutine, public buildfilenamebasic (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, integer, intent(in) regId, character(chrlen), intent(out) fileName)
Definition at line 108 of file ModBuildFileNames.F90.
References buildregionidstring(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public buildfilenameplain (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, character(chrlen), intent(out) fileName)
Definition at line 191 of file ModBuildFileNames.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public buildfilenameplainsteady (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, integer, intent(in) it, character(chrlen), intent(out) fileName)
Definition at line 272 of file ModBuildFileNames.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modtecplot::rflu_tec_openfilefield(), rflu_modtecplot::rflu_tec_openfilepatch(), and rflu_modtecplot::rflu_tec_openfilepatchstats().
subroutine, public buildfilenameplainunsteady (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, real(rfreal), intent(in) tm, character(chrlen), intent(out) fileName)
Definition at line 354 of file ModBuildFileNames.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modtecplot::rflu_tec_openfilefield(), rflu_modtecplot::rflu_tec_openfilepatch(), rflu_modtecplot::rflu_tec_openfilepatchstats(), and rflu_modtecplot::rflu_tec_openfilepnt().
subroutine, public buildfilenamesteady (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, integer, intent(in) regId, integer, intent(in) it, character(chrlen), intent(out) fileName)
Definition at line 438 of file ModBuildFileNames.F90.
References buildregionidstring(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public buildfilenameunsteady (type(t_global), pointer global, integer, intent(in) dest, character(*), intent(in) ext, integer, intent(in) regId, real(rfreal), intent(in) tm, character(chrlen), intent(out) fileName)
Definition at line 522 of file ModBuildFileNames.F90.
References buildregionidstring(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public buildregionidstring (type(t_global), pointer global, integer, intent(in) regId, character(chrlen), intent(out) regIdString)
Definition at line 604 of file ModBuildFileNames.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by buildfilenamebasic(), buildfilenamesteady(), buildfilenameunsteady(), rflu_modrocstario::rflu_genx_putdataflow(), rflu_modrocstario::rflu_genx_putdatagspeedssurf(), rflu_modrocstario::rflu_genx_putdatagspeedsvol(), rflu_modrocstario::rflu_genx_putdatainterf(), rflu_modrocstario::rflu_genx_putgridsurf(), rflu_modrocstario::rflu_genx_putgridvol(), and rflu_modrocstario::rflu_genx_readwindow().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: ModBuildFileNames.F90,v $ $Revision: 1.5 $' private
Definition at line 60 of file ModBuildFileNames.F90.
The documentation for this module was generated from the following file:
ModBuildFileNames.F90