Rocstar: LInfTemplate Class Reference
LInfTemplate Class Reference
Computes the L_infinity objective function for a given patch, i.e., LInfTemplate::concrete_evaluate returns the maximum absolute value of the quality metric values on 'patch'.
#include <LInfTemplate.hpp>
Public Member Functions
LInfTemplate (QualityMetric *)
virtual ~LInfTemplate ()
virtual bool concrete_evaluate (PatchData &patch, double &fval, MsqError &err)
LInfTemplate (QualityMetric *)
virtual ~LInfTemplate ()
virtual bool concrete_evaluate (PatchData &patch, double &fval, MsqError &err)
Public Member Functions inherited from ObjectiveFunction
ObjectiveFunction ()
virtual ~ObjectiveFunction ()
bool evaluate (PatchData &patch, double &fval, MsqError &err)
void set_gradient_type (GRADIENT_TYPE grad)
Set gradType to either NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT.
bool compute_gradient (PatchData &patch, Vector3D *const &grad, double &OF_val, MsqError &err, size_t array_size=0)
Calls either compute_numerical_gradient or compute_analytical_gradient depending on the value of gradType. Function returns 'false' if the patch is not within a required feasible regeion. Otherwise, it returns 'true'.
bool compute_hessian (PatchData &patch, MsqHessian &hessian, Vector3D *const &grad, double &OF_val, MsqError &err)
Calls compute_analytical_hessian. Function returns 'false' if the patch is not within a required feasible regeion. Otherwise, it returns 'true'.
QualityMetric * get_quality_metric ()
virtual msq_std::list
< QualityMetric * > get_quality_metric_list ()
void set_quality_metric (QualityMetric *qm)
Set the value of qMetric.
void set_negate_flag (int neg)
Set the value of ObjectiveFunction's negateFlag. Unless composite, concrete ObjectiveFunctions should set this flag to to the value of the associated QualityMetric's negateFLag.
int get_negate_flag ()
Returns negateFlag.
ObjectiveFunction ()
virtual ~ObjectiveFunction ()
bool evaluate (PatchData &patch, double &fval, MsqError &err)
void set_gradient_type (GRADIENT_TYPE grad)
Set gradType to either NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT.
bool compute_gradient (PatchData &patch, Vector3D *const &grad, double &OF_val, MsqError &err, size_t array_size=0)
Calls either compute_numerical_gradient or compute_analytical_gradient depending on the value of gradType. Function returns 'false' if the patch is not within a required feasible regeion. Otherwise, it returns 'true'.
bool compute_hessian (PatchData &patch, MsqHessian &hessian, Vector3D *const &grad, double &OF_val, MsqError &err)
Calls compute_analytical_hessian. Function returns 'false' if the patch is not within a required feasible regeion. Otherwise, it returns 'true'.
QualityMetric * get_quality_metric ()
virtual msq_std::list
< QualityMetric * > get_quality_metric_list ()
void set_quality_metric (QualityMetric *qm)
Set the value of qMetric.
void set_negate_flag (int neg)
Set the value of ObjectiveFunction's negateFlag. Unless composite, concrete ObjectiveFunctions should set this flag to to the value of the associated QualityMetric's negateFLag.
int get_negate_flag ()
Returns negateFlag.
Protected Member Functions
virtual bool compute_analytical_gradient (PatchData &patch, Vector3D *const &grad, double &OF_val, MsqError &err, size_t array_size)
virtual bool compute_analytical_gradient (PatchData &patch, Vector3D *const &grad, double &OF_val, MsqError &err, size_t array_size)
Protected Member Functions inherited from ObjectiveFunction
bool compute_numerical_gradient (PatchData &patch, Vector3D *const &grad, double &OF_val, MsqError &err, size_t array_size)
Non-virtual function which numerically computes the gradient of the Objective Function. Function returns 'false' if the patch is not within a required feasible regeion. Otherwise, it returns 'true'.
virtual bool compute_analytical_hessian (PatchData &, MsqHessian &, Vector3D *const &, double &, MsqError &)
double get_eps (PatchData &pd, double &local_val, int k, MsqVertex *vertex, MsqError &err)
Returns eps used in the numerical gradient calculation.
void set_use_local_gradient (bool new_bool)
Sets useLocalGradient This variable determines whether compute_numercial_gradient can use the most efficient gradient calculation.
bool compute_numerical_gradient (PatchData &patch, Vector3D *const &grad, double &OF_val, MsqError &err, size_t array_size)
Non-virtual function which numerically computes the gradient of the Objective Function. Function returns 'false' if the patch is not within a required feasible regeion. Otherwise, it returns 'true'.
virtual bool compute_analytical_hessian (PatchData &, MsqHessian &, Vector3D *const &, double &, MsqError &)
double get_eps (PatchData &pd, double &local_val, int k, MsqVertex *vertex, MsqError &err)
Returns eps used in the numerical gradient calculation.
void set_use_local_gradient (bool new_bool)
Sets useLocalGradient This variable determines whether compute_numercial_gradient can use the most efficient gradient calculation.
Additional Inherited Members
Public Types inherited from ObjectiveFunction
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
Detailed Description
Computes the L_infinity objective function for a given patch, i.e., LInfTemplate::concrete_evaluate returns the maximum absolute value of the quality metric values on 'patch'.
Definition at line 55 of file includeLinks/LInfTemplate.hpp.
Constructor & Destructor Documentation
LInfTemplate (QualityMetric * qualitymetric)
Definition at line 42 of file ObjectiveFunction/LInfTemplate.cpp.
References ObjectiveFunction::ANALYTICAL_GRADIENT, QualityMetric::get_negate_flag(), ObjectiveFunction::set_gradient_type(), ObjectiveFunction::set_negate_flag(), and ObjectiveFunction::set_quality_metric().
{
    set_quality_metric(qualitymetric);
    set_gradient_type(ObjectiveFunction::ANALYTICAL_GRADIENT);
    set_negate_flag(qualitymetric->get_negate_flag());
 }
~LInfTemplate () virtual
Definition at line 50 of file ObjectiveFunction/LInfTemplate.cpp.
{
 }
LInfTemplate (QualityMetric *)
virtual ~LInfTemplate () virtual
Member Function Documentation
bool compute_analytical_gradient (PatchData & patch, Vector3D *const & grad, double & OF_val, MsqError & err, size_t array_size) protected virtual
Fills an array of Vector3D, grad, with the gradient of the objective function computed using the gradient of the quality metric. If the function has not been over-riden in the concrete Objective Function, the base class implementation prints a warning and then defaults to numerical gradient. Function returns 'false' if the patch is not within a required feasible regeion. Otherwise, it returns 'true'.
Parameters
patch The PatchData object for which the objective function gradient is computed.
grad An array of Vector3D, at least the size of the number of vertices in the patch.
OF_val is set to the value of the objective function.
array_size is the size of the grad Vector3D[] array and must correspond to the number of vertices in the patch.
Reimplemented from ObjectiveFunction.
Definition at line 105 of file ObjectiveFunction/LInfTemplate.cpp.
References MsqError::INVALID_STATE, and MSQ_SETERR.
   {
     MSQ_SETERR(err)("The LInfTemplate is not sufficient for methods requiring\n"
                     "  gradient information.  If you neeed to try this anyway, \n"
                     "  set the gradient type to numerical.\n",
                     MsqError::INVALID_STATE);
     return false;
   }
virtual bool compute_analytical_gradient (PatchData & patch, Vector3D *const & grad, double & OF_val, MsqError & err, size_t array_size) protected virtual
Fills an array of Vector3D, grad, with the gradient of the objective function computed using the gradient of the quality metric. If the function has not been over-riden in the concrete Objective Function, the base class implementation prints a warning and then defaults to numerical gradient. Function returns 'false' if the patch is not within a required feasible regeion. Otherwise, it returns 'true'.
Parameters
patch The PatchData object for which the objective function gradient is computed.
grad An array of Vector3D, at least the size of the number of vertices in the patch.
OF_val is set to the value of the objective function.
array_size is the size of the grad Vector3D[] array and must correspond to the number of vertices in the patch.
Reimplemented from ObjectiveFunction.
virtual bool concrete_evaluate (PatchData & patch, double & fval, MsqError & err) virtual
Evaluate the objective function on a given patch.
Implements ObjectiveFunction.
bool concrete_evaluate (PatchData & patch, double & fval, MsqError & err) virtual
Evaluate the objective function on a given patch.
Implements ObjectiveFunction.
Definition at line 54 of file ObjectiveFunction/LInfTemplate.cpp.
References QualityMetric::ELEMENT_BASED, QualityMetric::evaluate_element(), QualityMetric::evaluate_vertex(), PatchData::get_element_array(), QualityMetric::get_metric_type(), ObjectiveFunction::get_quality_metric(), ObjectiveFunction::get_quality_metric_list(), PatchData::get_vertex_array(), MSQ_ERRZERO, PatchData::num_elements(), and PatchData::num_vertices().
{
     //Total value of objective function
   double temp_value=0;
   fval=0.0;
   bool obj_bool=true;
     //For elements in Patch
   int index;
   QualityMetric* currentQM = get_quality_metric();
   if(currentQM==NULL)
     currentQM=get_quality_metric_list().front();
   if(currentQM->get_metric_type()==QualityMetric::ELEMENT_BASED){
     int num_elements=patch.num_elements();
     MsqMeshEntity* elems=patch.get_element_array(err);  MSQ_ERRZERO(err);
       //Michael:  this may not do what we want
       //Set currentQM to be the first quality metric* in the list
     for (index=0; index<num_elements;index++){
         //evaluate metric for this elem
       obj_bool=currentQM->evaluate_element(patch, &elems[index], temp_value,
                                            err);  MSQ_ERRZERO(err);
         //if invalid patch
       if(!obj_bool){
         return false;
       }
       temp_value = fabs(temp_value);
       if(temp_value>fval)
         fval=temp_value;
     }//end loop over elements
   }//end if not VERTEX
   else {//VERTEX
     int num_vertices=patch.num_vertices();
     MsqVertex* vertices=patch.get_vertex_array(err);  MSQ_ERRZERO(err);
       //Michael:  this may not do what we want
       //Set currentQM to be the first quality metric* in the list
     for (index=0; index<num_vertices;index++){
         //evaluate metric for this vertex
       obj_bool=currentQM->evaluate_vertex(patch,&vertices[index],
                                           temp_value, err);  MSQ_ERRZERO(err);
         //if invalid patch
       if(!obj_bool){
         return false;
       }
       temp_value = fabs(temp_value);
       if(temp_value>fval)
         fval=temp_value;
     }//end loop over vertices
   }//end elseVERTEX
   return true;
 }
The documentation for this class was generated from the following files:
includeLinks/LInfTemplate.hpp
ObjectiveFunction/LInfTemplate.cpp