Rocstar: rflu_modrepair3d Module Reference
rflu_modrepair3d Module Reference
Public Member Functions
subroutine rflu_repair3d (NBPTS, NBFACE, NNODE, NCELL, XI, NFCEI, NDCI, XBNDYI, modFlag)
subroutine input (X, NNODE, NDC, NCELL, NFCE, NBPTS, NBFACE, ITYP, NPROP, XBNDY, XFAR, YFAR, ZFAR)
subroutine struct (X, NNODE, NDC, NBH, IPROT, NCELL, NFCE, NBFACE, NEDGE, NDG, IDGP, NDGP, IPOINT, NPOINT, NPTET, XCEN, YCEN, ZCEN, VOL, RC, RAT, XFAR, YFAR, ZFAR, IOCTR, NLINK, NOCTR, IDONE, NREF, VOLMIN, RCMX)
subroutine tetmv (X, XNEWBN, NNODE, NDC, NBH, NCELL, NFCE, NBFACE, NFAIL, ITYP, XCEN, YCEN, ZCEN, VOL, RC, RAT, NEDGE, NDG, IDGP, NDGP, IPOINT, FCOUNT, XC, RESID, SV, SIG1, SIG2, SIG3, XFAR, YFAR, ZFAR, TOLV)
subroutine tetmod (X, ITYP, NNODE, NDC, NBH, IPROT, NCELL, NDG, IDGP, NDGP, NEDGE, NFCE, NBFACE, VOL, XCEN, YCEN, ZCEN, RC, RAT, DENS, NPTET, NACPT, SIG1, SIG2, SIG3, NVCNT, RESID, COUNT, FAC, IDONE, NREF, NLINK, NOCTR, IOCTR, XFAR, YFAR, ZFAR, XOCTR, YOCTR, ZOCTR, XHOLD, YHOLD, ZHOLD, XKEEP, YKEEP, ZKEEP, KSRCH, NSRCH, IPOINT, NPOINT, IFLAG, NFLAG, DX, DY, DZ, DS, VLT, IRING, NTETKP, NFAD, NEWC, NBHKP, IEDKP, LNBR, ISHK, MNBR, KSHK, NPP, NFILL, NEWCEL, NTRI, NCAV, NSHAKE, NEWNBH, NOLD, NCAVFC, IKEEP, LDEL, NEDGRM, XC, YC, ZC, V, RAD, RCRIN, LNKUP, LNKDN, LISTF, VOLMIN, RCMX, TOLV)
subroutine octfil (N, X, NOCTR, IOCTR, NLINK, NREF, XFAR, YFAR, ZFAR)
subroutine octfnd (NCODE, NCLOSE, XPT, YPT, ZPT, N1, N2, N3, DISMIN, X, NOCTR, NLINK, XFAR, YFAR, ZFAR, IDONE, XOCTR, YOCTR, ZOCTR, XHOLD, YHOLD, ZHOLD, XKEEP, YKEEP, ZKEEP, KSRCH, NSRCH)
subroutine octrmv (N, X, NOCTR, NLINK, IDONE, NREF)
subroutine edgerm (NEDG, NDG, IDGP, NDGP)
subroutine tree (PROP, NLEFT, NRIGHT, NBACK, LISTF, NACPT, NTOT, NBH, IPROT, NCELL)
subroutine snglar (NNODE, X, XD, NCELL, NDC, NBH, SIGMN, SIGMX, SIG1, SIG2, SIG3, CNDMIN, CNDMAX)
subroutine densfn (X, NNODE, NFCE, NBFACE, NEDGE, NDG, DENS, RESID, FVCNT)
subroutine edglen (X, NNODE, ITYP, NEDGE, NDG, DENS, NVCNT)
subroutine coarsn (LC, X, NNODE, NDC, NBH, IPROT, NCELL, ITYP, XCEN, YCEN, ZCEN, VOL, RC, RAT, NVCNT, DENS, IFLAG, NFLAG, NPTET, NEDGE, NDG, IDGP, NDGP, NOCTR, IOCTR, NLINK, XFAR, YFAR, ZFAR, IDONE, NREF, FAC, SIG1, SIG2, SIG3, KSRCH, NSRCH, IRING, NTETKP, LNBR, ISHK, MNBR, KSHK, TOLV)
subroutine radrat (X, NNODE, NDC, NBH, IPROT, NCELL, NFCE, NBFACE, ITYP, IPOINT, VOL, RC, RAT)
subroutine volput (X, ITYP, NBPTS, NNODE, NDC, NBH, IPROT, NCELL, NDG, IDGP, NDGP, NEDGE, VOL, XCEN, YCEN, ZCEN, RC, RAT, DENS, NPTET, NACPT, IDONE, NREF, NLINK, NOCTR, IOCTR, XFAR, YFAR, ZFAR, XOCTR, YOCTR, ZOCTR, XHOLD, YHOLD, ZHOLD, XKEEP, YKEEP, ZKEEP, KSRCH, NSRCH, IPOINT, NPOINT, IFLAG, NFLAG, NFILL, NEWCEL, NTRI, NCAV, NSHAKE, NEWNBH, NOLD, NCAVFC, IKEEP, LDEL, NEDGRM, XC, YC, ZC, V, RAD, RCRIN, LNKUP, LNKDN, JLAST, JFIRST, NTRACK, VOLMIN, RCMX, TOLV)
subroutine putpnt (J, NFAIL, X, ITYP, NNODE, NDC, NBH, IPROT, NCELL, NDG, IDGP, NDGP, NEDGE, VOL, XCEN, YCEN, ZCEN, RC, RAT, DENS, NPTET, NACPT, IDONE, NREF, NLINK, NOCTR, IOCTR, XFAR, YFAR, ZFAR, XOCTR, YOCTR, ZOCTR, XHOLD, YHOLD, ZHOLD, XKEEP, YKEEP, ZKEEP, KSRCH, NSRCH, IPOINT, NPOINT, IFLAG, NFLAG, NFILL, NEWCEL, NTRI, NCAV, NSHAKE, NEWNBH, NOLD, NCAVFC, IKEEP, LDEL, NEDGRM, XC, YC, ZC, V, RAD, RCRIN, LNKUP, LNKDN, VOLMIN, RCMX, TOLV)
subroutine insert (NP, NCLOSE, LBRK, JCONT, NFAIL, X, NDC, NBH, IPROT, NCELL, NDG, IDGP, NDGP, NEDGE, VOL, XCEN, YCEN, ZCEN, RC, RAT, DENS, NPTET, NACPT, IPOINT, NPOINT, IFLAG, NFLAG, NFILL, NEWCEL, NTRI, NCAV, NSHAKE, NEWNBH, NOLD, NCAVFC, IKEEP, LDEL, NEDGRM, XC, YC, ZC, V, RAD, RCRIN, LNKUP, LNKDN, JLAST, JFIRST, NTRACK, VOLMIN, RCMX, TOLV)
subroutine tetloc (NP, NCLOSE, LBRK, LCONT, NFAIL, X, NDC, NBH, IPROT, DENS, VOL, IFLAG, NFLAG, NFILL, NEWCEL, TOLV)
subroutine cavity (NP, LCONT, NDEL, LDEL, X, NDC, NBH, IPROT, IFLAG, NFLAG, XCEN, YCEN, ZCEN, RC, NFILL, NEWCEL, TOLV)
subroutine cavbnd (NP, LCONT, NDEL, LDEL, NCNT, X, NDC, NBH, VOL, IFLAG, NFLAG, NFILL, NEWCEL, NTRI, NEWNBH, NOLD, TOLV)
subroutine recon (LDEL, NDEL, NCNT, NDC, NBH, IPROT, NDG, IDGP, NDGP, NFLAG, NTRI, NCAVFC, IKEEP, NEDGRM, IEDGRM)
subroutine cavedg (NCNT, NEDG, IPOINT, NPOINT, NTRI, NCAV, NEWNBH, NEWCEL)
subroutine datsrf (NP, NCNT, NEDG, NDG, IDGP, NDGP, NEDGE, IPOINT, NCAV, NEDGRM, IEDGRM)
subroutine colaps (NA, NB, NCOL, NVERT, NFAIL, X, NDC, NBH, IPROT, ITYP, XCEN, YCEN, ZCEN, VOL, RC, RAT, NVCNT, IFLAG, NFLAG, NPTET, NDG, IDGP, NDGP, NOCTR, IOCTR, NLINK, XFAR, YFAR, ZFAR, IDONE, NREF, KSRCH, NSRCH, IRING, NTETKP, LNBR, ISHK, MNBR, KSHK, TOLV)
subroutine smooth (X, ITYP, NNODE, NDC, NBH, IPROT, NCELL, NDG, IDGP, NDGP, NEDGE, VOL, XCEN, YCEN, ZCEN, RC, RAT, DENS, NPTET, NACPT, IDONE, NREF, NLINK, NOCTR, IOCTR, XFAR, YFAR, ZFAR, XOCTR, YOCTR, ZOCTR, XHOLD, YHOLD, ZHOLD, XKEEP, YKEEP, ZKEEP, KSRCH, NSRCH, IPOINT, NPOINT, IFLAG, NFLAG, DX, DY, DZ, DS, VLT, IRING, NTETKP, NFAD, NEWC, NBHKP, IEDKP, LNBR, ISHK, MNBR, KSHK, NPP, NFILL, NEWCEL, NTRI, NCAV, NSHAKE, NEWNBH, NOLD, NCAVFC, IKEEP, LDEL, NEDGRM, XC, YC, ZC, V, RAD, RCRIN, LNKUP, LNKDN, LISTF, VOLMIN, RCMX, TOLV)
subroutine replace (N1, N2, NA, NB, J, NRING, NPASS, NFAIL, X, DENS, ITYP, NNODE, NDC, NBH, IPROT, NCELL, NDG, IDGP, NDGP, NEDGE, IPOINT, NPOINT, VOL, XCEN, YCEN, ZCEN, RC, RAT, NPTET, NACPT, NOCTR, IOCTR, NLINK, NREF, XFAR, YFAR, ZFAR, IRING, NTETKP, LNBR, ISHK, MNBR, KSHK, NFAD, NBHKP, IEDKP, NEWC, DX, DY, DZ, DS, NP, VLT, TOLV)
subroutine triswp (NPT, N1, N2, N3, J, NFAIL, X, NDC, NBH, IPROT, NCELL, NDG, IDGP, NDGP, NEDGE, VOL, XCEN, YCEN, ZCEN, RC, RAT, NPTET, NACPT, TOLV)
subroutine tessel (IRING, NRING, NFAD, NBHKP, IEDKP, NEDK, IMEET, ITOUCH, X, IPOINT, NPOINT, DX, DY, DZ, DS, NP)
subroutine angfnd (NUM, IRING, IMIN, IMEET, ITOUCH, X, DX, DY, DZ, DS)
subroutine sliver (IRING, NRING, NA, NB, NFAIL, VORIG, X, DENS, ITYP, IPOINT, NNODE, NOCTR, IOCTR, NLINK, NREF, XFAR, YFAR, ZFAR, VLT)
subroutine circum (X, N1, N2, N3, N4, XCN, YCN, ZCN, VTET, RCIR, IFLAG, TOL)
subroutine circum2 (X, N1, N2, N3, XPT, YPT, ZPT, XCN, YCN, ZCN, VTET, RCIR, IFLAG, TOL)
subroutine neighb (L1, N1, N2, N3, L2, K1, K2, NDC, NBH)
subroutine lock (L1, L2, N1, N2, N3, N4, N5, K1, K2, NDC, NBH)
double precision function facear (X, N1, N2, N3)
double precision function dihed (N1, N2, N3, N4, X)
double precision function tetar (L, X, NDC)
double precision function tetar2 (M1, M2, M3, M4, X)
double precision function tetar3 (M1, M2, M3, XPT, YPT, ZPT, X)
subroutine fangle (J, X, NFCE, ANGL1, ANGL2, ANGL3, Q)
subroutine tetang (X, NDC, NBH, IPROT, NCELL)
subroutine tetcof (N1, N2, N3, N4, XPT, YPT, ZPT, V1, V2, V3, V4, VTET, X)
subroutine volcom (L, NPT, VDIFF, NCONT, X, NDC)
double precision function cofact (A1, A2, A3, B1, B2, B3)
Public Attributes
integer, parameter mnode = 100000
integer, parameter mcell = 6*MNODE
integer, parameter medge = 7*MNODE
integer, parameter mbpts = 40000
integer, parameter mbface = 2*MBPTS
integer, parameter moctr = 60000
integer, parameter mtest = 50000
integer, parameter mcav = 24000
integer, parameter mring = 80
integer, parameter medkp = 2*MRING
integer mxbpts
integer mxcav
integer mxcell
integer mxedge
integer mxface
integer mxnode
integer mxoctr
integer mxring
integer mxtest
Detailed Description
Definition at line 55 of file RFLU_ModRepair3D.F90.
Member Function/Subroutine Documentation
subroutine angfnd (integer NUM, integer, dimension(*) IRING, integer IMIN, integer IMEET, integer ITOUCH, double precision, dimension(3,*) X, double precision, dimension(*) DX, double precision, dimension(*) DY, double precision, dimension(*) DZ, double precision, dimension(*) DS)
Definition at line 6197 of file RFLU_ModRepair3D.F90.
References CImg< T >::atan2(), Rocblas::div(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), i, pi, sqrt(), CImg< T >::sum(), and x.
Referenced by tessel().
subroutine cavbnd (integer NP, integer LCONT, integer NDEL, integer, dimension(*) LDEL, integer NCNT, double precision, dimension(3,*) X, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, double precision, dimension(*) VOL, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, integer, dimension(*) NFILL, integer, dimension(*) NEWCEL, integer, dimension(3,*) NTRI, integer, dimension(4,*) NEWNBH, integer, dimension(*) NOLD, double precision TOLV)
Definition at line 3938 of file RFLU_ModRepair3D.F90.
References cofact(), j, k, Aff_transformation_2< R_ >::m(), max(), min(), sqrt(), StopWatch::stop(), tetcof(), volcom(), and x.
Referenced by insert().
subroutine cavedg (integer NCNT, integer NEDG, integer, dimension(*) IPOINT, integer, dimension(*) NPOINT, integer, dimension(3,*) NTRI, integer, dimension(4,*) NCAV, integer, dimension(4,*) NEWNBH, integer, dimension(*) NEWCEL)
Definition at line 4334 of file RFLU_ModRepair3D.F90.
References i, k, max(), min(), Element_node_enumerator::next(), StopWatch::stop(), and x.
Referenced by insert().
subroutine cavity (integer NP, integer LCONT, integer NDEL, integer, dimension(*) LDEL, double precision, dimension(3,*) X, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) RC, integer, dimension(*) NFILL, integer, dimension(*) NEWCEL, double precision TOLV)
Definition at line 3788 of file RFLU_ModRepair3D.F90.
References cofact(), k, lock(), Aff_transformation_2< R_ >::m(), max(), min(), sqrt(), StopWatch::stop(), and x.
Referenced by insert().
subroutine circum (double precision, dimension(3,*) X, integer N1, integer N2, integer N3, integer N4, double precision XCN, double precision YCN, double precision ZCN, double precision VTET, double precision RCIR, integer IFLAG, double precision TOL)
Definition at line 6421 of file RFLU_ModRepair3D.F90.
References cofact(), sqrt(), and x.
Referenced by colaps(), insert(), replace(), tetmv(), and triswp().
subroutine circum2 (double precision, dimension(3,*) X, integer N1, integer N2, integer N3, double precision XPT, double precision YPT, double precision ZPT, double precision XCN, double precision YCN, double precision ZCN, double precision VTET, double precision RCIR, integer IFLAG, double precision TOL)
Definition at line 6507 of file RFLU_ModRepair3D.F90.
References cofact(), sqrt(), and x.
Referenced by colaps().
subroutine coarsn (integer LC, double precision, dimension(3,*) X, integer NNODE, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(*) ITYP, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) VOL, double precision, dimension(*) RC, double precision, dimension(*) RAT, integer, dimension(*) NVCNT, double precision, dimension(*) DENS, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, integer, dimension(*) NPTET, integer NEDGE, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer, dimension(2,*) NOCTR, integer IOCTR, integer, dimension(*) NLINK, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, integer, dimension(*) IDONE, integer, dimension(*) NREF, double precision, dimension(*) FAC, double precision, dimension(*) SIG1, double precision, dimension(*) SIG2, double precision, dimension(*) SIG3, integer, dimension(*) KSRCH, integer, dimension(*) NSRCH, integer, dimension(*) IRING, integer, dimension(*) NTETKP, integer, dimension(*) LNBR, integer, dimension(*) ISHK, integer, dimension(*) MNBR, integer, dimension(*) KSHK, double precision TOLV)
Definition at line 2472 of file RFLU_ModRepair3D.F90.
References colaps(), dist(), i, j, max(), min(), ncol, sqrt(), and x.
Referenced by tetmod().
double precision function cofact (double precision, intent(in) A1, double precision, intent(in) A2, double precision, intent(in) A3, double precision, intent(in) B1, double precision, intent(in) B2, double precision, intent(in) B3)
Definition at line 7381 of file RFLU_ModRepair3D.F90.
Referenced by cavbnd(), cavity(), circum(), circum2(), colaps(), dihed(), octfnd(), putpnt(), replace(), sliver(), struct(), tetar(), tetar2(), tetar3(), tetcof(), tetmv(), triswp(), volcom(), and volput().
subroutine colaps (integer NA, integer NB, integer NCOL, integer NVERT, integer NFAIL, double precision, dimension(3,*) X, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer, dimension(*) ITYP, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) VOL, double precision, dimension(*) RC, double precision, dimension(*) RAT, integer, dimension(*) NVCNT, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, integer, dimension(*) NPTET, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer, dimension(2,*) NOCTR, integer IOCTR, integer, dimension(*) NLINK, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, integer, dimension(*) IDONE, integer, dimension(*) NREF, integer, dimension(*) KSRCH, integer, dimension(*) NSRCH, integer, dimension(*) IRING, integer, dimension(*) NTETKP, integer, dimension(*) LNBR, integer, dimension(*) ISHK, integer, dimension(*) MNBR, integer, dimension(*) KSHK, double precision TOLV)
Definition at line 4527 of file RFLU_ModRepair3D.F90.
References circum(), circum2(), cofact(), edgerm(), i, k, Aff_transformation_2< R_ >::m(), max(), min(), ncol, neighb(), Mesh::GenericCell_2::nvert(), octfil(), octrmv(), StopWatch::stop(), tetar(), tetar3(), and x.
Referenced by coarsn().
subroutine datsrf (integer NP, integer NCNT, integer NEDG, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer NEDGE, integer, dimension(*) IPOINT, integer, dimension(4,*) NCAV, integer, dimension(*) NEDGRM, integer IEDGRM)
Definition at line 4436 of file RFLU_ModRepair3D.F90.
References i, max(), min(), StopWatch::stop(), and x.
Referenced by insert().
subroutine densfn (double precision, dimension(3,*) X, integer NNODE, integer, dimension(3,*) NFCE, integer NBFACE, integer NEDGE, integer, dimension(2,*) NDG, double precision, dimension(*) DENS, double precision, dimension(*) RESID, double precision, dimension(*) FVCNT)
Definition at line 2260 of file RFLU_ModRepair3D.F90.
References dist(), i, j, k, max(), sqrt(), and x.
Referenced by tetmod().
double precision function dihed (integer N1, integer N2, integer N3, integer N4, double precision, dimension(3,*) X)
Definition at line 6801 of file RFLU_ModRepair3D.F90.
References CImg< T >::atan2(), by, cofact(), Plane_3< R, T >::d(), pi, sqrt(), and x.
Referenced by smooth(), and tetang().
subroutine edgerm (integer NEDG, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP)
Definition at line 1839 of file RFLU_ModRepair3D.F90.
References i, min(), StopWatch::stop(), and x.
Referenced by colaps(), recon(), and replace().
subroutine edglen (double precision, dimension(3,*) X, integer NNODE, integer, dimension(*) ITYP, integer NEDGE, integer, dimension(2,*) NDG, double precision, dimension(*) DENS, integer, dimension(*) NVCNT)
Definition at line 2392 of file RFLU_ModRepair3D.F90.
References i, max(), min(), sqrt(), and x.
Referenced by tetmod().
double precision function facear (double precision, dimension(3,*) X, integer N1, integer N2, integer N3)
Definition at line 6765 of file RFLU_ModRepair3D.F90.
References sqrt(), and x.
Referenced by input(), and radrat().
subroutine fangle (integer J, double precision, dimension(3,*) X, integer, dimension(3,*) NFCE, double precision ANGL1, double precision ANGL2, double precision ANGL3, double precision Q)
Definition at line 7039 of file RFLU_ModRepair3D.F90.
References j, sqrt(), StopWatch::stop(), and x.
Referenced by input(), and radrat().
subroutine input (double precision, dimension(3,*) X, integer NNODE, integer, dimension(4,*) NDC, integer NCELL, integer, dimension(3,*) NFCE, integer NBPTS, integer NBFACE, integer, dimension(*) ITYP, integer, dimension(*) NPROP, double precision, dimension(3,*) XBNDY, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR)
Definition at line 275 of file RFLU_ModRepair3D.F90.
References facear(), fangle(), j, max(), min(), StopWatch::stop(), and x.
Referenced by initializeflowfield(), initinputvalues(), inrt_augmentdissources(), inrt_checkuserinput(), inrt_defineboilingregulation(), inrt_defineburning(), inrt_definedrag(), inrt_defineheattransfernonburn(), inrt_definescouring(), inrt_determinetokens(), inrt_initialize(), inrt_printuserinput(), inrt_readboilingregulation(), inrt_readburning(), inrt_readdefaultsection(), inrt_readdrag(), inrt_readheattransfernonburn(), inrt_readscouring(), peri_checkparaminput(), peri_derivedinputvalues(), peri_initinputvalues(), peri_initsolution(), peul_derivedinputvalues(), peul_initinputvalues(), peul_readconpartsection(), rflo_checkbcinput(), rflo_derivedinputvalues(), rflo_initinputvalues(), rflo_setmstagecoeffs(), rflu_allocatememorytbc(), rflu_repair3d(), turb_checkparaminput(), turb_derivedinputvalues(), and turb_initinputvalues().
subroutine insert (integer NP, integer NCLOSE, integer LBRK, integer JCONT, integer NFAIL, double precision, dimension(3,*) X, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer NEDGE, double precision, dimension(*) VOL, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) RC, double precision, dimension(*) RAT, double precision, dimension(*) DENS, integer, dimension(*) NPTET, integer, dimension(*) NACPT, integer, dimension(*) IPOINT, integer, dimension(*) NPOINT, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, integer, dimension(*) NFILL, integer, dimension(*) NEWCEL, integer, dimension(3,*) NTRI, integer, dimension(4,*) NCAV, integer, dimension(*) NSHAKE, integer, dimension(4,*) NEWNBH, integer, dimension(*) NOLD, integer, dimension(3,*) NCAVFC, integer, dimension(*) IKEEP, integer, dimension(*) LDEL, integer, dimension(*) NEDGRM, double precision, dimension(*) XC, double precision, dimension(*) YC, double precision, dimension(*) ZC, double precision, dimension(*) V, double precision, dimension(*) RAD, double precision, dimension(*) RCRIN, integer, dimension(*) LNKUP, integer, dimension(*) LNKDN, integer JLAST, integer JFIRST, integer NTRACK, double precision VOLMIN, double precision RCMX, double precision TOLV)
Definition at line 3173 of file RFLU_ModRepair3D.F90.
References cavbnd(), cavedg(), cavity(), circum(), datsrf(), i, j, k, Aff_transformation_2< R_ >::m(), max(), min(), recon(), StopWatch::stop(), tetar2(), tetloc(), v, and x.
subroutine lock (integer L1, integer L2, integer N1, integer N2, integer N3, integer N4, integer N5, integer K1, integer K2, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH)
Definition at line 6679 of file RFLU_ModRepair3D.F90.
References Aff_transformation_2< R_ >::m(), max(), min(), StopWatch::stop(), and x.
Referenced by cavity(), putpnt(), and volput().
subroutine neighb (integer L1, integer N1, integer N2, integer N3, integer L2, integer K1, integer K2, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH)
Definition at line 6597 of file RFLU_ModRepair3D.F90.
References k, Aff_transformation_2< R_ >::m(), max(), min(), StopWatch::stop(), and x.
Referenced by colaps(), replace(), tetloc(), and triswp().
subroutine octfil (integer N, double precision, dimension(3,*) X, integer, dimension(2,*) NOCTR, integer IOCTR, integer, dimension(*) NLINK, integer, dimension(*) NREF, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR)
Definition at line 1333 of file RFLU_ModRepair3D.F90.
References i, j, k, max(), Element_node_enumerator::next(), StopWatch::stop(), and x.
Referenced by colaps(), putpnt(), sliver(), struct(), and volput().
subroutine octfnd (integer NCODE, integer NCLOSE, double precision XPT, double precision YPT, double precision ZPT, integer N1, integer N2, integer N3, double precision DISMIN, double precision, dimension(3,*) X, integer, dimension(2,*) NOCTR, integer, dimension(*) NLINK, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, integer, dimension(*) IDONE, double precision, dimension(2,*) XOCTR, double precision, dimension(2,*) YOCTR, double precision, dimension(2,*) ZOCTR, double precision, dimension(2,*) XHOLD, double precision, dimension(2,*) YHOLD, double precision, dimension(2,*) ZHOLD, double precision, dimension(2) XKEEP, double precision, dimension(2) YKEEP, double precision, dimension(2) ZKEEP, integer, dimension(*) KSRCH, integer, dimension(*) NSRCH)
Definition at line 1537 of file RFLU_ModRepair3D.F90.
References cofact(), dist(), i, ic, j, k, kc, max(), Element_node_enumerator::next(), sqrt(), StopWatch::stop(), and x.
Referenced by putpnt(), and volput().
subroutine octrmv (integer N, double precision, dimension(3,*) X, integer, dimension(2,*) NOCTR, integer, dimension(*) NLINK, integer, dimension(*) IDONE, integer, dimension(*) NREF)
Definition at line 1782 of file RFLU_ModRepair3D.F90.
References i, Element_node_enumerator::next(), StopWatch::stop(), and x.
Referenced by colaps().
subroutine putpnt (integer J, integer NFAIL, double precision, dimension(3,*) X, integer, dimension(*) ITYP, integer NNODE, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer NEDGE, double precision, dimension(*) VOL, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) RC, double precision, dimension(*) RAT, double precision, dimension(*) DENS, integer, dimension(*) NPTET, integer, dimension(*) NACPT, integer, dimension(*) IDONE, integer, dimension(*) NREF, integer, dimension(*) NLINK, integer, dimension(2,*) NOCTR, integer IOCTR, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, double precision, dimension(2,*) XOCTR, double precision, dimension(2,*) YOCTR, double precision, dimension(2,*) ZOCTR, double precision, dimension(2,*) XHOLD, double precision, dimension(2,*) YHOLD, double precision, dimension(2,*) ZHOLD, double precision, dimension(2) XKEEP, double precision, dimension(2) YKEEP, double precision, dimension(2) ZKEEP, integer, dimension(*) KSRCH, integer, dimension(*) NSRCH, integer, dimension(*) IPOINT, integer, dimension(*) NPOINT, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, integer, dimension(*) NFILL, integer, dimension(*) NEWCEL, integer, dimension(3,*) NTRI, integer, dimension(4,*) NCAV, integer, dimension(*) NSHAKE, integer, dimension(4,*) NEWNBH, integer, dimension(*) NOLD, integer, dimension(3,*) NCAVFC, integer, dimension(*) IKEEP, integer, dimension(*) LDEL, integer, dimension(*) NEDGRM, double precision, dimension(*) XC, double precision, dimension(*) YC, double precision, dimension(*) ZC, double precision, dimension(*) V, double precision, dimension(*) RAD, double precision, dimension(*) RCRIN, integer, dimension(*) LNKUP, integer, dimension(*) LNKDN, double precision VOLMIN, double precision RCMX, double precision TOLV)
Definition at line 3026 of file RFLU_ModRepair3D.F90.
References cofact(), Pane::insert(), j, k, lock(), octfil(), octfnd(), StopWatch::stop(), v, and x.
Referenced by smooth().
subroutine radrat (double precision, dimension(3,*) X, integer NNODE, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(3,*) NFCE, integer NBFACE, integer, dimension(*) ITYP, integer, dimension(*) IPOINT, double precision, dimension(*) VOL, double precision, dimension(*) RC, double precision, dimension(*) RAT)
Definition at line 2609 of file RFLU_ModRepair3D.F90.
References facear(), fangle(), j, k, max(), min(), sqrt(), tetang(), and x.
Referenced by rflu_repair3d().
subroutine recon (integer, dimension(*) LDEL, integer NDEL, integer NCNT, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer, dimension(*) NFLAG, integer, dimension(3,*) NTRI, integer, dimension(3,*) NCAVFC, integer, dimension(*) IKEEP, integer, dimension(*) NEDGRM, integer IEDGRM)
Definition at line 4151 of file RFLU_ModRepair3D.F90.
References edgerm(), j, k, Aff_transformation_2< R_ >::m(), max(), min(), StopWatch::stop(), and x.
Referenced by insert().
subroutine replace (integer N1, integer N2, integer NA, integer NB, integer J, integer NRING, integer NPASS, integer NFAIL, double precision, dimension(3,*) X, double precision, dimension(*) DENS, integer, dimension(*) ITYP, integer NNODE, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer NEDGE, integer, dimension(*) IPOINT, integer, dimension(*) NPOINT, double precision, dimension(*) VOL, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) RC, double precision, dimension(*) RAT, integer, dimension(*) NPTET, integer, dimension(*) NACPT, integer, dimension(2,*) NOCTR, integer IOCTR, integer, dimension(*) NLINK, integer, dimension(*) NREF, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, integer, dimension(*) IRING, integer, dimension(*) NTETKP, integer, dimension(*) LNBR, integer, dimension(*) ISHK, integer, dimension(*) MNBR, integer, dimension(*) KSHK, integer, dimension(3,*) NFAD, integer, dimension(3,*) NBHKP, integer, dimension(4,*) IEDKP, integer, dimension(*) NEWC, double precision, dimension(*) DX, double precision, dimension(*) DY, double precision, dimension(*) DZ, double precision, dimension(*) DS, integer, dimension(*) NP, double precision, dimension(*) VLT, double precision TOLV)
Definition at line 5314 of file RFLU_ModRepair3D.F90.
References circum(), cofact(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), edgerm(), i, j, k, Aff_transformation_2< R_ >::m(), max(), min(), neighb(), sliver(), StopWatch::stop(), tessel(), tetar(), tetar2(), and x.
Referenced by smooth().
subroutine rflu_repair3d (integer, intent(inout) NBPTS, integer, intent(inout) NBFACE, integer, intent(inout) NNODE, integer, intent(inout) NCELL, double precision, dimension(3,nnode), intent(inout) XI, integer, dimension(3,nbface), intent(inout) NFCEI, integer, dimension(4,ncell), intent(inout) NDCI, double precision, dimension(3,nbpts), intent(inout) XBNDYI, logical, intent(in) modFlag)
Definition at line 76 of file RFLU_ModRepair3D.F90.
References Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), input(), radrat(), StopWatch::stop(), struct(), tetmod(), tetmv(), v, and x.
subroutine sliver (integer, dimension(*) IRING, integer NRING, integer NA, integer NB, integer NFAIL, double precision VORIG, double precision, dimension(3,*) X, double precision, dimension(*) DENS, integer, dimension(*) ITYP, integer, dimension(*) IPOINT, integer NNODE, integer, dimension(2,*) NOCTR, integer IOCTR, integer, dimension(*) NLINK, integer, dimension(*) NREF, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, double precision, dimension(*) VLT)
Definition at line 6297 of file RFLU_ModRepair3D.F90.
References cofact(), i, octfil(), StopWatch::stop(), and x.
Referenced by replace().
subroutine smooth (double precision, dimension(3,*) X, integer, dimension(*) ITYP, integer NNODE, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer NEDGE, double precision, dimension(*) VOL, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) RC, double precision, dimension(*) RAT, double precision, dimension(*) DENS, integer, dimension(*) NPTET, integer, dimension(*) NACPT, integer, dimension(*) IDONE, integer, dimension(*) NREF, integer, dimension(*) NLINK, integer, dimension(2,*) NOCTR, integer IOCTR, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, double precision, dimension(2,*) XOCTR, double precision, dimension(2,*) YOCTR, double precision, dimension(2,*) ZOCTR, double precision, dimension(2,*) XHOLD, double precision, dimension(2,*) YHOLD, double precision, dimension(2,*) ZHOLD, double precision, dimension(2) XKEEP, double precision, dimension(2) YKEEP, double precision, dimension(2) ZKEEP, integer, dimension(*) KSRCH, integer, dimension(*) NSRCH, integer, dimension(*) IPOINT, integer, dimension(*) NPOINT, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, double precision, dimension(*) DX, double precision, dimension(*) DY, double precision, dimension(*) DZ, double precision, dimension(*) DS, double precision, dimension(*) VLT, integer, dimension(*) IRING, integer, dimension(*) NTETKP, integer, dimension(3,*) NFAD, integer, dimension(*) NEWC, integer, dimension(3,*) NBHKP, integer, dimension(4,*) IEDKP, integer, dimension(*) LNBR, integer, dimension(*) ISHK, integer, dimension(*) MNBR, integer, dimension(*) KSHK, integer, dimension(*) NPP, integer, dimension(*) NFILL, integer, dimension(*) NEWCEL, integer, dimension(3,*) NTRI, integer, dimension(4,*) NCAV, integer, dimension(*) NSHAKE, integer, dimension(4,*) NEWNBH, integer, dimension(*) NOLD, integer, dimension(3,*) NCAVFC, integer, dimension(*) IKEEP, integer, dimension(*) LDEL, integer, dimension(*) NEDGRM, double precision, dimension(*) XC, double precision, dimension(*) YC, double precision, dimension(*) ZC, double precision, dimension(*) V, double precision, dimension(*) RAD, double precision, dimension(*) RCRIN, integer, dimension(*) LNKUP, integer, dimension(*) LNKDN, integer, dimension(*) LISTF, double precision VOLMIN, double precision RCMX, double precision TOLV)
Definition at line 5053 of file RFLU_ModRepair3D.F90.
References dihed(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), i, j, k, max(), min(), putpnt(), replace(), tree(), triswp(), v, and x.
Referenced by tetmod().
subroutine snglar (integer NNODE, double precision, dimension(3,*) X, double precision, dimension(3,*) XD, integer NCELL, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, double precision SIGMN, double precision SIGMX, double precision, dimension(*) SIG1, double precision, dimension(*) SIG2, double precision, dimension(*) SIG3, double precision CNDMIN, double precision CNDMAX)
Definition at line 1998 of file RFLU_ModRepair3D.F90.
References CImg< T >::atan2(), Plane_3< R, T >::d(), max(), min(), Color::r(), s, sqrt(), StopWatch::stop(), and x.
Referenced by tetmv().
subroutine struct (double precision, dimension(3,*) X, integer NNODE, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(3,*) NFCE, integer NBFACE, integer NEDGE, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer, dimension(*) IPOINT, integer, dimension(*) NPOINT, integer, dimension(*) NPTET, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) VOL, double precision, dimension(*) RC, double precision, dimension(*) RAT, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, integer IOCTR, integer, dimension(*) NLINK, integer, dimension(2,*) NOCTR, integer, dimension(*) IDONE, integer, dimension(*) NREF, double precision VOLMIN, double precision RCMX)
Definition at line 496 of file RFLU_ModRepair3D.F90.
References cofact(), i, j, k, max(), min(), octfil(), sqrt(), StopWatch::stop(), v, and x.
Referenced by rflu_repair3d().
subroutine tessel (integer, dimension(*) IRING, integer NRING, integer, dimension(3,*) NFAD, integer, dimension(3,*) NBHKP, integer, dimension(4,*) IEDKP, integer NEDK, integer IMEET, integer ITOUCH, double precision, dimension(3,*) X, integer, dimension(*) IPOINT, integer, dimension(*) NPOINT, double precision, dimension(*) DX, double precision, dimension(*) DY, double precision, dimension(*) DZ, double precision, dimension(*) DS, integer, dimension(*) NP)
Definition at line 5999 of file RFLU_ModRepair3D.F90.
References angfnd(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), i, k, max(), min(), StopWatch::stop(), and x.
Referenced by replace().
subroutine tetang (double precision, dimension(3,*) X, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL)
Definition at line 7133 of file RFLU_ModRepair3D.F90.
References dihed(), j, max(), min(), sqrt(), and x.
Referenced by radrat().
double precision function tetar (integer L, double precision, dimension(3,*) X, integer, dimension(4,*) NDC)
Definition at line 6886 of file RFLU_ModRepair3D.F90.
References cofact(), sqrt(), and x.
Referenced by colaps(), replace(), tetmv(), and triswp().
double precision function tetar2 (integer M1, integer M2, integer M3, integer M4, double precision, dimension(3,*) X)
Definition at line 6936 of file RFLU_ModRepair3D.F90.
References cofact(), sqrt(), and x.
Referenced by insert(), replace(), and triswp().
double precision function tetar3 (integer M1, integer M2, integer M3, double precision XPT, double precision YPT, double precision ZPT, double precision, dimension(3,*) X)
Definition at line 6986 of file RFLU_ModRepair3D.F90.
References cofact(), sqrt(), and x.
Referenced by colaps().
subroutine tetcof (integer N1, integer N2, integer N3, integer N4, double precision XPT, double precision YPT, double precision ZPT, double precision V1, double precision V2, double precision V3, double precision V4, double precision VTET, double precision, dimension(3,*) X)
Definition at line 7229 of file RFLU_ModRepair3D.F90.
References cofact(), and x.
Referenced by cavbnd(), and tetloc().
subroutine tetloc (integer NP, integer NCLOSE, integer LBRK, integer LCONT, integer NFAIL, double precision, dimension(3,*) X, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, double precision, dimension(*) DENS, double precision, dimension(*) VOL, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, integer, dimension(*) NFILL, integer, dimension(*) NEWCEL, double precision TOLV)
Definition at line 3540 of file RFLU_ModRepair3D.F90.
References k, max(), neighb(), StopWatch::stop(), tetcof(), volcom(), and x.
Referenced by insert().
subroutine tetmod (double precision, dimension(3,*) X, integer, dimension(*) ITYP, integer NNODE, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer NEDGE, integer, dimension(3,*) NFCE, integer NBFACE, double precision, dimension(*) VOL, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) RC, double precision, dimension(*) RAT, double precision, dimension(*) DENS, integer, dimension(*) NPTET, integer, dimension(*) NACPT, double precision, dimension(*) SIG1, double precision, dimension(*) SIG2, double precision, dimension(*) SIG3, integer, dimension(*) NVCNT, double precision, dimension(*) RESID, double precision, dimension(*) COUNT, double precision, dimension(*) FAC, integer, dimension(*) IDONE, integer, dimension(*) NREF, integer, dimension(*) NLINK, integer, dimension(2,*) NOCTR, integer IOCTR, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, double precision, dimension(2,*) XOCTR, double precision, dimension(2,*) YOCTR, double precision, dimension(2,*) ZOCTR, double precision, dimension(2,*) XHOLD, double precision, dimension(2,*) YHOLD, double precision, dimension(2,*) ZHOLD, double precision, dimension(2) XKEEP, double precision, dimension(2) YKEEP, double precision, dimension(2) ZKEEP, integer, dimension(*) KSRCH, integer, dimension(*) NSRCH, integer, dimension(*) IPOINT, integer, dimension(*) NPOINT, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, double precision, dimension(*) DX, double precision, dimension(*) DY, double precision, dimension(*) DZ, double precision, dimension(*) DS, double precision, dimension(*) VLT, integer, dimension(*) IRING, integer, dimension(*) NTETKP, integer, dimension(3,*) NFAD, integer, dimension(*) NEWC, integer, dimension(3,*) NBHKP, integer, dimension(4,*) IEDKP, integer, dimension(*) LNBR, integer, dimension(*) ISHK, integer, dimension(*) MNBR, integer, dimension(*) KSHK, integer, dimension(*) NPP, integer, dimension(*) NFILL, integer, dimension(*) NEWCEL, integer, dimension(3,*) NTRI, integer, dimension(4,*) NCAV, integer, dimension(*) NSHAKE, integer, dimension(4,*) NEWNBH, integer, dimension(*) NOLD, integer, dimension(3,*) NCAVFC, integer, dimension(*) IKEEP, integer, dimension(*) LDEL, integer, dimension(*) NEDGRM, double precision, dimension(*) XC, double precision, dimension(*) YC, double precision, dimension(*) ZC, double precision, dimension(*) V, double precision, dimension(*) RAD, double precision, dimension(*) RCRIN, integer, dimension(*) LNKUP, integer, dimension(*) LNKDN, integer, dimension(*) LISTF, double precision VOLMIN, double precision RCMX, double precision TOLV)
Definition at line 1180 of file RFLU_ModRepair3D.F90.
References coarsn(), densfn(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), edglen(), smooth(), v, volput(), and x.
Referenced by rflu_repair3d().
subroutine tetmv (double precision, dimension(3,*) X, double precision, dimension(3,*) XNEWBN, integer NNODE, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer NCELL, integer, dimension(3,*) NFCE, integer NBFACE, integer NFAIL, integer, dimension(*) ITYP, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) VOL, double precision, dimension(*) RC, double precision, dimension(*) RAT, integer NEDGE, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer, dimension(*) IPOINT, double precision, dimension(*) FCOUNT, double precision, dimension(3,*) XC, double precision, dimension(*) RESID, double precision, dimension(*) SV, double precision, dimension(*) SIG1, double precision, dimension(*) SIG2, double precision, dimension(*) SIG3, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, double precision TOLV)
Definition at line 796 of file RFLU_ModRepair3D.F90.
References circum(), cofact(), i, j, k, max(), min(), snglar(), StopWatch::stop(), tetar(), and x.
Referenced by rflu_repair3d().
subroutine tree (double precision, dimension(*) PROP, integer, dimension(*) NLEFT, integer, dimension(*) NRIGHT, integer, dimension(*) NBACK, integer, dimension(*) LISTF, integer, dimension(*) NACPT, integer NTOT, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL)
Definition at line 1897 of file RFLU_ModRepair3D.F90.
References j, and nj.
Referenced by smooth().
subroutine triswp (integer NPT, integer N1, integer N2, integer N3, integer J, integer NFAIL, double precision, dimension(3,*) X, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer NEDGE, double precision, dimension(*) VOL, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) RC, double precision, dimension(*) RAT, integer, dimension(*) NPTET, integer, dimension(*) NACPT, double precision TOLV)
Definition at line 5783 of file RFLU_ModRepair3D.F90.
References circum(), cofact(), i, j, k, max(), min(), neighb(), StopWatch::stop(), tetar(), tetar2(), and x.
Referenced by smooth().
subroutine volcom (integer L, integer NPT, double precision VDIFF, integer NCONT, double precision, dimension(3,*) X, integer, dimension(4,*) NDC)
Definition at line 7288 of file RFLU_ModRepair3D.F90.
References cofact(), sign(), v, and x.
Referenced by cavbnd(), and tetloc().
subroutine volput (double precision, dimension(3,*) X, integer, dimension(*) ITYP, integer NBPTS, integer NNODE, integer, dimension(4,*) NDC, integer, dimension(4,*) NBH, integer, dimension(*) IPROT, integer NCELL, integer, dimension(2,*) NDG, integer, dimension(*) IDGP, integer, dimension(*) NDGP, integer NEDGE, double precision, dimension(*) VOL, double precision, dimension(*) XCEN, double precision, dimension(*) YCEN, double precision, dimension(*) ZCEN, double precision, dimension(*) RC, double precision, dimension(*) RAT, double precision, dimension(*) DENS, integer, dimension(*) NPTET, integer, dimension(*) NACPT, integer, dimension(*) IDONE, integer, dimension(*) NREF, integer, dimension(*) NLINK, integer, dimension(2,*) NOCTR, integer IOCTR, double precision, dimension(2) XFAR, double precision, dimension(2) YFAR, double precision, dimension(2) ZFAR, double precision, dimension(2,*) XOCTR, double precision, dimension(2,*) YOCTR, double precision, dimension(2,*) ZOCTR, double precision, dimension(2,*) XHOLD, double precision, dimension(2,*) YHOLD, double precision, dimension(2,*) ZHOLD, double precision, dimension(2) XKEEP, double precision, dimension(2) YKEEP, double precision, dimension(2) ZKEEP, integer, dimension(*) KSRCH, integer, dimension(*) NSRCH, integer, dimension(*) IPOINT, integer, dimension(*) NPOINT, integer, dimension(*) IFLAG, integer, dimension(*) NFLAG, integer, dimension(*) NFILL, integer, dimension(*) NEWCEL, integer, dimension(3,*) NTRI, integer, dimension(4,*) NCAV, integer, dimension(*) NSHAKE, integer, dimension(4,*) NEWNBH, integer, dimension(*) NOLD, integer, dimension(3,*) NCAVFC, integer, dimension(*) IKEEP, integer, dimension(*) LDEL, integer, dimension(*) NEDGRM, double precision, dimension(*) XC, double precision, dimension(*) YC, double precision, dimension(*) ZC, double precision, dimension(*) V, double precision, dimension(*) RAD, double precision, dimension(*) RCRIN, integer, dimension(*) LNKUP, integer, dimension(*) LNKDN, integer JLAST, integer JFIRST, integer NTRACK, double precision VOLMIN, double precision RCMX, double precision TOLV)
Definition at line 2788 of file RFLU_ModRepair3D.F90.
References cofact(), Pane::insert(), j, k, lock(), octfil(), octfnd(), sqrt(), StopWatch::stop(), v, and x.
Referenced by tetmod().
Member Data Documentation
integer, parameter mbface = 2*MBPTS
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer, parameter mbpts = 40000
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer, parameter mcav = 24000
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer, parameter mcell = 6*MNODE
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer, parameter medge = 7*MNODE
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer, parameter medkp = 2*MRING
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer, parameter mnode = 100000
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer, parameter moctr = 60000
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer, parameter mring = 80
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer, parameter mtest = 50000
Definition at line 57 of file RFLU_ModRepair3D.F90.
integer mxbpts
Definition at line 68 of file RFLU_ModRepair3D.F90.
integer mxcav
Definition at line 68 of file RFLU_ModRepair3D.F90.
integer mxcell
Definition at line 68 of file RFLU_ModRepair3D.F90.
integer mxedge
Definition at line 68 of file RFLU_ModRepair3D.F90.
integer mxface
Definition at line 68 of file RFLU_ModRepair3D.F90.
integer mxnode
Definition at line 68 of file RFLU_ModRepair3D.F90.
integer mxoctr
Definition at line 68 of file RFLU_ModRepair3D.F90.
integer mxring
Definition at line 68 of file RFLU_ModRepair3D.F90.
integer mxtest
Definition at line 68 of file RFLU_ModRepair3D.F90.
The documentation for this module was generated from the following file:
RFLU_ModRepair3D.F90