Rocstar: rflo_modboundaryconditions Module Reference
rflo_modboundaryconditions Module Reference
Public Member Functions
subroutine, public rflo_bcondfarfield (region, patch)
subroutine, public rflo_bcondinflow (region, patch)
subroutine rflo_bcondinjectionapn (region, patch)
subroutine, public rflo_bcondinjection (region, patch)
subroutine, public rflo_bcondinjectioninit (region)
subroutine, public rflo_bcondnoslipwall (region, patch)
subroutine, public rflo_bcondoutflow (region, patch)
subroutine, public rflo_bcondrotatperiod (region, regionSrc, patch, patchSrc)
subroutine, public rflo_bcondslipwall (region, patch)
subroutine, public rflo_bcondsymmetry (region, patch)
subroutine, public rflo_boundaryconditionsrecv (regions, iReg)
subroutine, public rflo_boundaryconditionssend (regions, iReg)
subroutine, public rflo_boundaryconditionsset (regions, iReg)
subroutine rflo_bcondoutflowperf (bcOpt, pout, sxn, syn, szn, cpgas, mol, rho, rhou, rhov, rhow, rhoe, press, ud, vd, wd, tempd, uOld, vOld, wOld, udOld, vdOld, wdOld, rdOld, edOld, refLength, dtMin, kappa, rhob, rhoub, rhovb, rhowb, rhoeb)
subroutine rflo_bcondinflowvtperf (model, bcOpt, uInfl, vInfl, wInfl, tInfl, pInfl, sxn, syn, szn, cpgas, mol, rho, rhou, rhov, rhow, rhoe, press, rhob, rhoub, rhovb, rhowb, rhoeb)
subroutine rflo_bcondinflowvpperf (model, bcOpt, uInfl, vInfl, wInfl, tInfl, pInfl, sxn, syn, szn, cpgas, mol, rho, rhou, rhov, rhow, rhoe, press, rhob, rhoub, rhovb, rhowb, rhoeb)
subroutine rflo_bcondinflowfluc (bcOptModel, ufluc, vfluc, wfluc, Tfluc, pfluc, uvel, vvel, wvel, temp, pres, muvel, mvvel, mwvel, mtemp, mpres)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModBoundaryConditions.F90,v $ $Revision: 1.30 $'
Detailed Description
Definition at line 39 of file RFLO_ModBoundaryConditions.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_bcondfarfield (type(t_region) region, type(t_patch) patch)
Definition at line 99 of file RFLO_ModBoundaryConditions.F90.
References bcondfarfieldperf(), moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by rflo_boundaryconditionsset().
subroutine, public rflo_bcondinflow (type(t_region) region, type(t_patch) patch)
Definition at line 268 of file RFLO_ModBoundaryConditions.F90.
References bcondinflowperf(), moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, mixtureproperties(), moderror::registerfunction(), rflo_bcondinflowfluc(), rflo_bcondinflowvpperf(), rflo_bcondinflowvtperf(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by rflo_boundaryconditionsset().
subroutine rflo_bcondinflowfluc (integer bcOptModel, real(rfreal) ufluc, real(rfreal) vfluc, real(rfreal) wfluc, real(rfreal) Tfluc, real(rfreal) pfluc, real(rfreal) uvel, real(rfreal) vvel, real(rfreal) wvel, real(rfreal) temp, real(rfreal) pres, real(rfreal) muvel, real(rfreal) mvvel, real(rfreal) mwvel, real(rfreal) mtemp, real(rfreal) mpres)
Definition at line 2570 of file RFLO_ModBoundaryConditions.F90.
Referenced by rflo_bcondinflow().
subroutine rflo_bcondinflowvpperf (integer model, integer bcOpt, real(rfreal) uInfl, real(rfreal) vInfl, real(rfreal) wInfl, real(rfreal) tInfl, real(rfreal) pInfl, real(rfreal) sxn, real(rfreal) syn, real(rfreal) szn, real(rfreal) cpgas, real(rfreal) mol, real(rfreal) rho, real(rfreal) rhou, real(rfreal) rhov, real(rfreal) rhow, real(rfreal) rhoe, real(rfreal) press, real(rfreal) rhob, real(rfreal) rhoub, real(rfreal) rhovb, real(rfreal) rhowb, real(rfreal) rhoeb)
Definition at line 2453 of file RFLO_ModBoundaryConditions.F90.
References mixtperf_c_dgp(), mixtperf_c_grt(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), and StopWatch::stop().
Referenced by rflo_bcondinflow().
subroutine rflo_bcondinflowvtperf (integer model, integer bcOpt, real(rfreal) uInfl, real(rfreal) vInfl, real(rfreal) wInfl, real(rfreal) tInfl, real(rfreal) pInfl, real(rfreal) sxn, real(rfreal) syn, real(rfreal) szn, real(rfreal) cpgas, real(rfreal) mol, real(rfreal) rho, real(rfreal) rhou, real(rfreal) rhov, real(rfreal) rhow, real(rfreal) rhoe, real(rfreal) press, real(rfreal) rhob, real(rfreal) rhoub, real(rfreal) rhovb, real(rfreal) rhowb, real(rfreal) rhoeb)
Definition at line 2329 of file RFLO_ModBoundaryConditions.F90.
References mixtperf_c_dgp(), mixtperf_c_grt(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), and StopWatch::stop().
Referenced by rflo_bcondinflow().
subroutine, public rflo_bcondinjection (type(t_region) region, type(t_patch) patch)
Definition at line 693 of file RFLO_ModBoundaryConditions.F90.
References bcondinjectionperf(), moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by rflo_boundaryconditionsset().
subroutine rflo_bcondinjectionapn (type(t_region) region, type(t_patch) patch)
Definition at line 564 of file RFLO_ModBoundaryConditions.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by rflo_boundaryconditionsset().
subroutine, public rflo_bcondinjectioninit (type(t_region) region)
Definition at line 925 of file RFLO_ModBoundaryConditions.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_copyboundarydata(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by rflo_getflowsolution().
subroutine, public rflo_bcondnoslipwall (type(t_region) region, type(t_patch) patch)
Definition at line 1103 of file RFLO_ModBoundaryConditions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and v.
Referenced by rflo_boundaryconditionsset().
subroutine, public rflo_bcondoutflow (type(t_region) region, type(t_patch) patch)
Definition at line 1309 of file RFLO_ModBoundaryConditions.F90.
References bcondoutflowperf(), moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, mixtureproperties(), moderror::registerfunction(), rflo_bcondoutflowperf(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by rflo_boundaryconditionsset().
subroutine rflo_bcondoutflowperf (integer bcOpt, real(rfreal) pout, real(rfreal) sxn, real(rfreal) syn, real(rfreal) szn, real(rfreal) cpgas, real(rfreal) mol, real(rfreal) rho, real(rfreal) rhou, real(rfreal) rhov, real(rfreal) rhow, real(rfreal) rhoe, real(rfreal) press, real(rfreal) ud, real(rfreal) vd, real(rfreal) wd, real(rfreal) tempd, real(rfreal) uOld, real(rfreal) vOld, real(rfreal) wOld, real(rfreal) udOld, real(rfreal) vdOld, real(rfreal) wdOld, real(rfreal) rdOld, real(rfreal) edOld, real(rfreal) refLength, real(rfreal) dtMin, real(rfreal) kappa, real(rfreal) rhob, real(rfreal) rhoub, real(rfreal) rhovb, real(rfreal) rhowb, real(rfreal) rhoeb)
Definition at line 2202 of file RFLO_ModBoundaryConditions.F90.
References min(), mixtperf_c_dgp(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_r_m(), sign(), sqrt(), and v.
Referenced by rflo_bcondoutflow().
subroutine, public rflo_bcondrotatperiod (type(t_region) region, type(t_region) regionSrc, type(t_patch) patch, type(t_patch) patchSrc)
Definition at line 1529 of file RFLO_ModBoundaryConditions.F90.
References moderror::deregisterfunction(), mixtureproperties(), and moderror::registerfunction().
Referenced by rflo_boundaryconditionssend(), and rflo_boundaryconditionsset().
subroutine, public rflo_bcondslipwall (type(t_region) region, type(t_patch) patch)
Definition at line 1571 of file RFLO_ModBoundaryConditions.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_boundaryconditionsset().
subroutine, public rflo_bcondsymmetry (type(t_region) region, type(t_patch) patch)
Definition at line 1698 of file RFLO_ModBoundaryConditions.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_boundaryconditionsset().
subroutine, public rflo_boundaryconditionsrecv (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 1804 of file RFLO_ModBoundaryConditions.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_correctcorneredgecells(), rflo_exchangecorneredgecells(), rflo_receivecorneredgecells(), rflo_receivedummyvals(), and rflo_setcorneredgecells().
Referenced by explicitmultistage(), and updateboundaryconditionsmp().
subroutine, public rflo_boundaryconditionssend (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 1901 of file RFLO_ModBoundaryConditions.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_bcondrotatperiod(), rflo_sendcorneredgecells(), rflo_senddummyconf(), rflo_senddummyint(), and rflo_senddummyireg().
Referenced by explicitmultistage(), and initcommunicationmp().
subroutine, public rflo_boundaryconditionsset (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 2018 of file RFLO_ModBoundaryConditions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflo_bcondfarfield(), rflo_bcondinflow(), rflo_bcondinjection(), rflo_bcondinjectionapn(), rflo_bcondnoslipwall(), rflo_bcondoutflow(), rflo_bcondrotatperiod(), rflo_bcondslipwall(), rflo_bcondsymmetry(), rflo_exchangedummyconf(), rflo_exchangedummyint(), and rflo_exchangedummyireg().
Referenced by explicitmultistage(), and updateboundaryconditionsmp().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModBoundaryConditions.F90,v $ $Revision: 1.30 $' private
Definition at line 75 of file RFLO_ModBoundaryConditions.F90.
The documentation for this module was generated from the following file:
RFLO_ModBoundaryConditions.F90