Rocstar: CPoint Class Reference
CPoint Class Reference
#include <GeoPrimitives.H>
Public Member Functions
CPoint ()
CPoint (double ix, double iy, double iz=0.0)
CPoint (const double *p)
CPoint (const CPoint &in)
CPoint & init ()
CPoint & init (double ix, double iy, double iz=0.0)
CPoint & init (const double *p)
CPoint & operator= (const CPoint &p)
CPoint & copy (const CPoint &p)
double norm () const
bool operator== (const CPoint &p) const
bool operator!= (const CPoint &p) const
bool operator< (const CPoint &p) const
bool operator> (const CPoint &p) const
bool operator<= (const CPoint &p) const
bool operator>= (const CPoint &p) const
CPoint & operator+= (const CPoint &p)
CPoint & operator-= (const CPoint &p)
CPoint operator* (double num) const
CPoint & operator*= (double num)
double & x ()
CPoint & x (double i)
const double & x () const
double & y ()
CPoint & y (double i)
const double & y () const
double & z ()
CPoint & z (double i)
const double & z () const
const double & operator[] (unsigned int i) const
double & operator[] (unsigned int i)
CPoint operator+ (const CPoint &p) const
CPoint operator- (const CPoint &p) const
double Distance (const CPoint &p) const
CPoint & set (double ix, double iy, double iz)
CPoint & reset ()
Protected Attributes
double P [3]
Friends
CPoint operator* (double, const CPoint &p)
std::ostream & operator<< (std::ostream &oSt, const CPoint &p)
std::istream & operator>> (std::istream &iSt, CPoint &p)
double Distance (const CPoint &p, const GeoPrim::CLine &l)
Detailed Description
Definition at line 22 of file GeoPrimitives.H.
Constructor & Destructor Documentation
CPoint () inline
Definition at line 30 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] = P[1] = P[2] = 0.0;
     };
CPoint (double ix, double iy, double iz = 0.0) inline
Definition at line 34 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] = ix;
       P[1] = iy;
       P[2] = iz;
     };
CPoint (const double * p) inline
Definition at line 40 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] = p[0];
       P[1] = p[1];
       P[2] = p[2];
     };
CPoint (const CPoint & in) inline
Definition at line 46 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] = in.P[0];
       P[1] = in.P[1];
       P[2] = in.P[2];
     };
Member Function Documentation
CPoint& copy (const CPoint & p) inline
Definition at line 80 of file GeoPrimitives.H.
     {
       *this = p;
       return(*this);
     };
double Distance (const CPoint & p) const inline
Definition at line 184 of file GeoPrimitives.H.
References CPoint::norm().
     {
       return((*this - p).norm());
     }
CPoint& init () inline
Definition at line 52 of file GeoPrimitives.H.
References CPoint::P.
Referenced by test().
     {
       P[0] = 0.;
       P[1] = 0.;
       P[2] = 0;
       return(*this);
     };
CPoint& init (double ix, double iy, double iz = 0.0) inline
Definition at line 59 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] = ix;
       P[1] = iy;
       P[2] = iz;
       return(*this);
     };
CPoint& init (const double * p) inline
Definition at line 66 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] = p[0];
       P[1] = p[1];
       P[2] = p[2];
       return(*this);
     };
double norm () const inline
Definition at line 85 of file GeoPrimitives.H.
References sqrt(), CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by CPoint::Distance(), CPoint::operator<(), CPoint::operator<=(), CPoint::operator>(), and CPoint::operator>=().
     {
       return(sqrt((x()*x()) + (y()*y()) + (z()*z())));
     };
bool operator!= (const CPoint & p) const inline
Definition at line 95 of file GeoPrimitives.H.
     {
       return (!((*this)==p));
     };
CPoint operator* (double num) const inline
Definition at line 131 of file GeoPrimitives.H.
References CPoint::P.
     {
       CPoint rp(P[0]*num,P[1]*num,P[2]*num);
       return(rp);
     };
CPoint& operator*= (double num) inline
Definition at line 136 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] *= num;
       P[1] *= num;
       P[2] *= num;
       return(*this);
     };
CPoint operator+ (const CPoint & p) const inline
Definition at line 174 of file GeoPrimitives.H.
References CPoint::P.
     {
       CPoint rp(P[0]+p.P[0],P[1]+p.P[1],P[2]+p.P[2]);
       return(rp);
     };
CPoint& operator+= (const CPoint & p) inline
Definition at line 117 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] += p.P[0];
       P[1] += p.P[1];
       P[2] += p.P[2];
       return(*this);
     };
CPoint operator- (const CPoint & p) const inline
Definition at line 179 of file GeoPrimitives.H.
References CPoint::P.
     {
       CPoint rp(P[0]-p.P[0],P[1]-p.P[1],P[2]-p.P[2]);
       return(rp);
     };
CPoint& operator-= (const CPoint & p) inline
Definition at line 124 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] -= p.P[0];
       P[1] -= p.P[1];
       P[2] -= p.P[2];
       return(*this);
     };
bool operator< (const CPoint & p) const inline
Definition at line 99 of file GeoPrimitives.H.
References CPoint::norm().
     {
       return (norm() < p.norm());
     };
bool operator<= (const CPoint & p) const inline
Definition at line 107 of file GeoPrimitives.H.
References CPoint::norm().
     {
       return ((norm() < p.norm()) ||
               (*this == p));
     };
CPoint& operator= (const CPoint & p) inline
Definition at line 73 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] = p.P[0];
       P[1] = p.P[1];
       P[2] = p.P[2];
       return(*this);
     };
bool operator== (const CPoint & p) const inline
Definition at line 89 of file GeoPrimitives.H.
References CPoint::P, and GeoPrim::TOL.
     {
       return( (fabs(P[0] - p.P[0]) < TOL) &&
               (fabs(P[1] - p.P[1]) < TOL) &&
               (fabs(P[2] - p.P[2]) < TOL) );
     };
bool operator> (const CPoint & p) const inline
Definition at line 103 of file GeoPrimitives.H.
References CPoint::norm().
     {
       return (norm() > p.norm());
     };
bool operator>= (const CPoint & p) const inline
Definition at line 112 of file GeoPrimitives.H.
References CPoint::norm().
     {
       return((norm() > p.norm()) ||
              (*this == p));
     };
const double& operator[] (unsigned int i) const inline
Definition at line 164 of file GeoPrimitives.H.
References CPoint::P.
     {
       if( i > 2 ) i = 0;
       return(P[i]);
     };
double& operator[] (unsigned int i) inline
Definition at line 169 of file GeoPrimitives.H.
References CPoint::P.
     {
       if (i > 2) i = 0;
       return(P[i]);
     };
CPoint& reset () inline
Definition at line 195 of file GeoPrimitives.H.
References CPoint::P.
Referenced by CBox::CBox().
     {
       P[0] = 0.0;
       P[1] = 0.0;
       P[2] = 0.0;
       return(*this);
     };
CPoint& set (double ix, double iy, double iz) inline
Definition at line 188 of file GeoPrimitives.H.
References CPoint::P.
     {
       P[0] = ix;
       P[1] = iy;
       P[2] = iz;
       return(*this);
     };
double& x () inline
Definition at line 143 of file GeoPrimitives.H.
References CPoint::P.
Referenced by CBox::AddPoint(), CBox::around(), C3Vector::C3Vector(), CBox::CBox(), CBox::collide(), CBox::contains(), CPlane::contains_point(), CPlane::CPlane(), CVector::CVector(), CPlane::D(), GeoPrim::Distance(), CBox::empty(), Mesh::GenerateCartesianGrid(), CLineSegment::has_point(), CBox::init(), Mesh::NodalCoordinates::init_node(), CBox::intersect(), main(), CBox::merge(), CPoint::norm(), GeoPrim::operator*(), CVector::operator+=(), GeoPrim::operator<<(), CVector::operator=(), and FloGridBlock::ReadBlock().
 { return P[0]; };
CPoint& x (double i) inline
Definition at line 144 of file GeoPrimitives.H.
References i, and CPoint::P.
     {
       P[0] = i;
       return(*this);
     };
const double& x () const inline
Definition at line 149 of file GeoPrimitives.H.
References CPoint::P.
 { return P[0]; };
double& y () inline
Definition at line 150 of file GeoPrimitives.H.
References CPoint::P.
Referenced by CBox::AddPoint(), CBox::around(), C3Vector::C3Vector(), CBox::CBox(), CBox::collide(), CBox::contains(), CPlane::contains_point(), CPlane::CPlane(), CVector::CVector(), CPlane::D(), GeoPrim::Distance(), CBox::empty(), Mesh::GenerateCartesianGrid(), CLineSegment::has_point(), CBox::init(), Mesh::NodalCoordinates::init_node(), CBox::intersect(), main(), CBox::merge(), CPoint::norm(), GeoPrim::operator*(), CVector::operator+=(), GeoPrim::operator<<(), CVector::operator=(), and FloGridBlock::ReadBlock().
 { return P[1]; };
CPoint& y (double i) inline
Definition at line 151 of file GeoPrimitives.H.
References i, and CPoint::P.
     {
       P[1] = i;
       return(*this);
     };
const double& y () const inline
Definition at line 156 of file GeoPrimitives.H.
References CPoint::P.
 { return P[1]; };
double& z () inline
Definition at line 157 of file GeoPrimitives.H.
References CPoint::P.
Referenced by CBox::AddPoint(), CBox::around(), C3Vector::C3Vector(), CBox::CBox(), CBox::collide(), CBox::contains(), CPlane::contains_point(), CPlane::CPlane(), CVector::CVector(), CPlane::D(), GeoPrim::Distance(), CBox::empty(), Mesh::GenerateCartesianGrid(), CLineSegment::has_point(), CBox::init(), Mesh::NodalCoordinates::init_node(), CBox::intersect(), main(), CBox::merge(), CPoint::norm(), GeoPrim::operator*(), CVector::operator+=(), GeoPrim::operator<<(), CVector::operator=(), and FloGridBlock::ReadBlock().
 { return P[2]; };
CPoint& z (double i) inline
Definition at line 158 of file GeoPrimitives.H.
References i, and CPoint::P.
     {
       P[2] = i;
       return(*this);
     }
const double& z () const inline
Definition at line 163 of file GeoPrimitives.H.
References CPoint::P.
 { return P[2]; };
Friends And Related Function Documentation
double Distance (const CPoint & p, const GeoPrim::CLine & l) friend
Definition at line 35 of file GeoPrimitives.C.
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     CPoint p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     CVector v(p,p2);
     return(v.mag());
   }
CPoint operator* (double scalar, const CPoint & p) friend
Definition at line 117 of file GeoPrimitives.C.
   {
     GeoPrim::CPoint rv(p);
     rv.x() *= scalar;
     rv.y() *= scalar;
     rv.z() *= scalar;
     return(rv);
   }
std::ostream& operator<< (std::ostream & oSt, const CPoint & p) friend
Definition at line 62 of file GeoPrimitives.C.
   {
     oS << p.x() << "  " << p.y() << "  " << p.z();
     return(oS);
   }
std::istream& operator>> (std::istream & iSt, GeoPrim::CPoint & p) friend
Definition at line 69 of file GeoPrimitives.C.
   {
     iS >> p[0] >> p[1] >> p[2];
     return(iS);
   }
Member Data Documentation
double P[3] protected
Definition at line 28 of file GeoPrimitives.H.
Referenced by CPoint::CPoint(), CPoint::init(), CPoint::operator*(), CPoint::operator*=(), CPoint::operator+(), CPoint::operator+=(), CPoint::operator-(), CPoint::operator-=(), CPoint::operator=(), CPoint::operator==(), CPoint::operator[](), CPoint::reset(), CPoint::set(), CPoint::x(), CPoint::y(), and CPoint::z().
The documentation for this class was generated from the following file:
GeoPrimitives.H