Rocstar: data_declarations Module Reference
data_declarations Module Reference
Data Types
type elem_list
type element_struct
type face_struct
type file_struct
type id_struct
type node_struct
type scale_struct
type surface_struct
type surfscale_struct
Public Member Functions
integer function length (STRING)
Public Attributes
integer i
integer j
integer k
integer l
integer m
integer n
integer etype
integer ftype
integer numnp
integer numbndnp
integer numel
integer npfixed
integer numsub
integer numfaces
integer numbndfaces
integer numscale_bk
integer numscale_ft
integer numscale_np
integer mark
integer scale
integer count
integer frontfile
integer backfile
integer priv1
integer priv2
integer numprop
integer numbound
integer numboundmesh
integer ndbcflag
integer numco
integer iaux
integer numclst
integer numcstet
integer numcohshared
integer nproc_neigh
integer num_border_coh
integer num_border_cst
integer numboundmid
integer numboundend
integer numboundfirst
integer numbmeshmid
integer numbmeshend
integer numbmeshfirst
real *8 delta
real *8 maxz
real *8 minz
real *8, dimension(:,:),
allocatable coor
real *8, dimension(:,:),
allocatable meshcoor
real *8, dimension(:,:),
allocatable xm
integer, dimension(:), allocatable nboundtype
integer, dimension(:), allocatable matcstet
integer, dimension(:), allocatable ts_proportion
integer, dimension(:,:),
allocatable lmcstet
real *8, dimension(:), allocatable proportion
integer nboundryel3d
type(id_struct), dimension(:),
allocatable id
type(id_struct), dimension(:),
allocatable idmesh
real *8, dimension(3) xyz
real *8 ztrans
character *40 prefix
character *4 scaleid
type(surface_struct),
dimension(:), allocatable surface
type(surfscale_struct), pointer frontsnode
type(surfscale_struct), pointer first_frontsnode
type(surfscale_struct), pointer backsnode
type(surfscale_struct), pointer first_backsnode
type(element_struct),
dimension(:), allocatable element
type(node_struct), dimension(:),
allocatable node
type(node_struct), dimension(:),
allocatable surfnode
type(face_struct), pointer facelist
type(face_struct), pointer firstface
type(file_struct), dimension(:),
allocatable fileid
type(scale_struct), pointer frontnode
type(scale_struct), pointer first_front_node
type(scale_struct), pointer backnode
type(scale_struct), pointer first_back_node
type(scale_struct), pointer bnplist
type(scale_struct), pointer firstnode
type(elem_list), pointer elemlist
type(elem_list), pointer firstelem
type(elem_list), pointer eboundlist
type(elem_list), pointer firstebound
Detailed Description
Definition at line 53 of file data_declarations.f90.
Member Function/Subroutine Documentation
integer function length (character*(*) STRING)
Definition at line 229 of file data_declarations.f90.
References Element_node_enumerator::next(), parameter(), and type< T >::string().
Member Data Documentation
integer backfile
Definition at line 57 of file data_declarations.f90.
type(scale_struct), pointer backnode
Definition at line 211 of file data_declarations.f90.
type(surfscale_struct), pointer backsnode
Definition at line 202 of file data_declarations.f90.
type(scale_struct), pointer bnplist
Definition at line 211 of file data_declarations.f90.
real*8, dimension(:,:), allocatable coor
Definition at line 101 of file data_declarations.f90.
integer count
Definition at line 57 of file data_declarations.f90.
real*8 delta
Definition at line 98 of file data_declarations.f90.
type(elem_list), pointer eboundlist
Definition at line 221 of file data_declarations.f90.
type(element_struct), dimension(:), allocatable element
Definition at line 206 of file data_declarations.f90.
type(elem_list), pointer elemlist
Definition at line 221 of file data_declarations.f90.
integer etype
Definition at line 57 of file data_declarations.f90.
type(face_struct), pointer facelist
Definition at line 209 of file data_declarations.f90.
type(file_struct), dimension(:), allocatable fileid
Definition at line 210 of file data_declarations.f90.
type(scale_struct), pointer first_back_node
Definition at line 211 of file data_declarations.f90.
type(surfscale_struct), pointer first_backsnode
Definition at line 202 of file data_declarations.f90.
type(scale_struct), pointer first_front_node
Definition at line 211 of file data_declarations.f90.
type(surfscale_struct), pointer first_frontsnode
Definition at line 202 of file data_declarations.f90.
type(elem_list), pointer firstebound
Definition at line 221 of file data_declarations.f90.
type(elem_list), pointer firstelem
Definition at line 221 of file data_declarations.f90.
type(face_struct), pointer firstface
Definition at line 209 of file data_declarations.f90.
type(scale_struct), pointer firstnode
Definition at line 211 of file data_declarations.f90.
integer frontfile
Definition at line 57 of file data_declarations.f90.
type(scale_struct), pointer frontnode
Definition at line 211 of file data_declarations.f90.
type(surfscale_struct), pointer frontsnode
Definition at line 202 of file data_declarations.f90.
integer ftype
Definition at line 57 of file data_declarations.f90.
integer i
Definition at line 57 of file data_declarations.f90.
integer iaux
Definition at line 79 of file data_declarations.f90.
type(id_struct), dimension(:), allocatable id
Definition at line 126 of file data_declarations.f90.
type(id_struct), dimension(:), allocatable idmesh
Definition at line 126 of file data_declarations.f90.
integer j
Definition at line 57 of file data_declarations.f90.
integer k
Definition at line 57 of file data_declarations.f90.
integer l
Definition at line 57 of file data_declarations.f90.
integer, dimension(:,:), allocatable lmcstet
Definition at line 111 of file data_declarations.f90.
integer m
Definition at line 57 of file data_declarations.f90.
integer mark
Definition at line 57 of file data_declarations.f90.
integer, dimension(:), allocatable matcstet
Definition at line 106 of file data_declarations.f90.
real*8 maxz
Definition at line 99 of file data_declarations.f90.
real*8, dimension(:,:), allocatable meshcoor
Definition at line 101 of file data_declarations.f90.
real*8 minz
Definition at line 99 of file data_declarations.f90.
integer n
Definition at line 57 of file data_declarations.f90.
integer nboundryel3d
Definition at line 118 of file data_declarations.f90.
integer, dimension(:), allocatable nboundtype
Definition at line 106 of file data_declarations.f90.
integer ndbcflag
Definition at line 79 of file data_declarations.f90.
type(node_struct), dimension(:), allocatable node
Definition at line 207 of file data_declarations.f90.
integer npfixed
Definition at line 57 of file data_declarations.f90.
integer nproc_neigh
Definition at line 79 of file data_declarations.f90.
integer num_border_coh
Definition at line 79 of file data_declarations.f90.
integer num_border_cst
Definition at line 79 of file data_declarations.f90.
integer numbmeshend
Definition at line 79 of file data_declarations.f90.
integer numbmeshfirst
Definition at line 79 of file data_declarations.f90.
integer numbmeshmid
Definition at line 79 of file data_declarations.f90.
integer numbndfaces
Definition at line 57 of file data_declarations.f90.
integer numbndnp
Definition at line 57 of file data_declarations.f90.
integer numbound
Definition at line 79 of file data_declarations.f90.
integer numboundend
Definition at line 79 of file data_declarations.f90.
integer numboundfirst
Definition at line 79 of file data_declarations.f90.
integer numboundmesh
Definition at line 79 of file data_declarations.f90.
integer numboundmid
Definition at line 79 of file data_declarations.f90.
integer numclst
Definition at line 79 of file data_declarations.f90.
integer numco
Definition at line 79 of file data_declarations.f90.
integer numcohshared
Definition at line 79 of file data_declarations.f90.
integer numcstet
Definition at line 79 of file data_declarations.f90.
integer numel
Definition at line 57 of file data_declarations.f90.
integer numfaces
Definition at line 57 of file data_declarations.f90.
integer numnp
Definition at line 57 of file data_declarations.f90.
integer numprop
Definition at line 79 of file data_declarations.f90.
integer numscale_bk
Definition at line 57 of file data_declarations.f90.
integer numscale_ft
Definition at line 57 of file data_declarations.f90.
integer numscale_np
Definition at line 57 of file data_declarations.f90.
integer numsub
Definition at line 57 of file data_declarations.f90.
character*40 prefix
Definition at line 137 of file data_declarations.f90.
integer priv1
Definition at line 57 of file data_declarations.f90.
integer priv2
Definition at line 57 of file data_declarations.f90.
real*8, dimension(:), allocatable proportion
Definition at line 115 of file data_declarations.f90.
integer scale
Definition at line 57 of file data_declarations.f90.
character*4 scaleid
Definition at line 138 of file data_declarations.f90.
type(surface_struct), dimension(:), allocatable surface
Definition at line 200 of file data_declarations.f90.
type(node_struct), dimension(:), allocatable surfnode
Definition at line 208 of file data_declarations.f90.
integer, dimension(:), allocatable ts_proportion
Definition at line 106 of file data_declarations.f90.
real*8, dimension(:,:), allocatable xm
Definition at line 101 of file data_declarations.f90.
real*8, dimension(3) xyz
Definition at line 134 of file data_declarations.f90.
real*8 ztrans
Definition at line 135 of file data_declarations.f90.
The documentation for this module was generated from the following file:
data_declarations.f90