Rocstar: rflu_modregionmapping Module Reference
rflu_modregionmapping Module Reference
Public Member Functions
subroutine, public rflu_applyregionmapping (global, levels)
subroutine, public rflu_buildregionmappingsimple (global)
subroutine, public rflu_checkregionmapping (global)
subroutine, public rflu_closeregionmappingfile (global)
subroutine, public rflu_createregionmapping (global, mapType)
subroutine, public rflu_destroyregionmapping (global, mapType)
subroutine, public rflu_getproclocregids (global, regIds, nRegIds, procIds, locRegIds)
subroutine, public rflu_imposeregionmappingserial (global)
subroutine, public rflu_openregionmappingfile (global)
subroutine, public rflu_readregionmappingfile (global, readMode, myProcId)
subroutine, public rflu_setregionmappingserial (global)
subroutine, public rflu_writeregionmappingfile (global)
Public Attributes
integer, parameter, public maptype_reg = 1
integer, parameter, public maptype_proc2reg = 2
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRegionMapping.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 43 of file RFLU_ModRegionMapping.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_applyregionmapping (type(t_global), pointer global, type(t_level), dimension(:), pointer levels)
Definition at line 109 of file RFLU_ModRegionMapping.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), rfluconv(), rfluinit(), rflumap(), rflupart(), rflupick(), and rflupost().
subroutine, public rflu_buildregionmappingsimple (type(t_global), pointer global)
Definition at line 196 of file RFLU_ModRegionMapping.F90.
References moderror::deregisterfunction(), i, ibeg, iend, and moderror::registerfunction().
Referenced by rflumap().
subroutine, public rflu_checkregionmapping (type(t_global), pointer global)
Definition at line 295 of file RFLU_ModRegionMapping.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, modsortsearch::quicksortinteger(), and moderror::registerfunction().
Referenced by rflumap().
subroutine, public rflu_closeregionmappingfile (type(t_global), pointer global)
Definition at line 397 of file RFLU_ModRegionMapping.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modcommlists::rflu_comm_getproclocregids(), rflu_readregionmappingfile(), and rflumap().
subroutine, public rflu_createregionmapping (type(t_global), pointer global, integer, intent(in) mapType)
Definition at line 475 of file RFLU_ModRegionMapping.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), rfluconv(), rfluinit(), rflumap(), rflupart(), rflupick(), and rflupost().
subroutine, public rflu_destroyregionmapping (type(t_global), pointer global, integer, intent(in) mapType)
Definition at line 567 of file RFLU_ModRegionMapping.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), rfluconv(), rfluinit(), rflumap(), rflupart(), rflupick(), and rflupost().
subroutine, public rflu_getproclocregids (type(t_global), pointer global, integer, dimension(nregids), intent(in) regIds, integer, intent(in) nRegIds, integer, dimension(nregids), intent(out) procIds, integer, dimension(nregids), intent(out) locRegIds)
Definition at line 662 of file RFLU_ModRegionMapping.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modcommlists::rflu_comm_getproclocregids().
subroutine, public rflu_imposeregionmappingserial (type(t_global), pointer global)
Definition at line 812 of file RFLU_ModRegionMapping.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), rfluconv(), rfluinit(), rflupart(), rflupick(), and rflupost().
subroutine, public rflu_openregionmappingfile (type(t_global), pointer global)
Definition at line 891 of file RFLU_ModRegionMapping.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modcommlists::rflu_comm_getproclocregids(), rflu_readregionmappingfile(), and rflumap().
subroutine, public rflu_readregionmappingfile (type(t_global), pointer global, integer, intent(in) readMode, integer, intent(in) myProcId)
Definition at line 979 of file RFLU_ModRegionMapping.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_closeregionmappingfile(), and rflu_openregionmappingfile().
Referenced by rflu_initflowsolver(), rfluconv(), rfluinit(), rflumap(), rflupart(), rflupick(), and rflupost().
subroutine, public rflu_setregionmappingserial (type(t_global), pointer global)
Definition at line 1185 of file RFLU_ModRegionMapping.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rfluconv(), rfluinit(), rflupart(), rflupick(), and rflupost().
subroutine, public rflu_writeregionmappingfile (type(t_global), pointer global)
Definition at line 1257 of file RFLU_ModRegionMapping.F90.
References moderror::deregisterfunction(), i, ibeg, iend, and moderror::registerfunction().
Referenced by rflumap().
Member Data Documentation
integer, parameter, public maptype_proc2reg = 2
Definition at line 77 of file RFLU_ModRegionMapping.F90.
integer, parameter, public maptype_reg = 1
Definition at line 77 of file RFLU_ModRegionMapping.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRegionMapping.F90,v $ $Revision: 1.7 $' private
Definition at line 74 of file RFLU_ModRegionMapping.F90.
The documentation for this module was generated from the following file:
RFLU_ModRegionMapping.F90