Rocstar: COM_Object_derived Class Reference
COM_Object_derived Class Reference
Static Public Member Functions
static bool cast_obj ()
Protected Types
enum { DERIVED_COOKIE =3374833 }
Protected Member Functions
COM_Object_derived ()
virtual ~COM_Object_derived ()
void validate_object (int *ierr)
Protected Attributes
int _cookie
Detailed Description
Definition at line 596 of file Roccom_base.C.
Member Enumeration Documentation
anonymous enum protected
Enumerator
DERIVED_COOKIE
Definition at line 619 of file Roccom_base.C.
 { DERIVED_COOKIE=3374833 };
Constructor & Destructor Documentation
COM_Object_derived () inline protected
Definition at line 609 of file Roccom_base.C.
 : _cookie( DERIVED_COOKIE) {}
virtual ~COM_Object_derived () inline protected virtual
Definition at line 611 of file Roccom_base.C.
 {}
Member Function Documentation
static bool cast_obj () inline static
Definition at line 598 of file Roccom_base.C.
References validate_object().
Referenced by Roccom_base::set_object().
{
     typedef void(COM_Object::*Member_Func)( int *);
     Member_Func f = (Member_Func)&COM_Object_derived::validate_object;
     COM_Object_derived obj;
     int ierr; (reinterpret_cast<COM_Object*>((void *)&obj)->*f)( &ierr);
     return ierr != 0;
   }
void validate_object (int * ierr) inline protected
Definition at line 613 of file Roccom_base.C.
References _cookie, and DERIVED_COOKIE.
Referenced by cast_obj().
{
     if ( _cookie != DERIVED_COOKIE) *ierr = -1;
     else *ierr = COM_Object::validate_object();
   }
Member Data Documentation
int _cookie protected
Definition at line 620 of file Roccom_base.C.
Referenced by validate_object().
The documentation for this class was generated from the following file:
Roccom_base.C