Rocstar: plag_modcheckvars Module Reference
plag_modcheckvars Module Reference
Public Member Functions
subroutine, public plag_checkpositivity (pRegion)
subroutine, public plag_checkvalidity (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModCheckVars.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 39 of file PLAG_ModCheckVars.F90.
Member Function/Subroutine Documentation
subroutine, public plag_checkpositivity (type(t_region), pointer pRegion)
Definition at line 93 of file PLAG_ModCheckVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and CImg< T >::sum().
Referenced by rflu_checkpositivitywrapper().
subroutine, public plag_checkvalidity (type(t_region), pointer pRegion)
Definition at line 255 of file PLAG_ModCheckVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modtools::isnan(), moderror::registerfunction(), and CImg< T >::sum().
Referenced by afterupdatemp(), and rflu_checkvaliditywrapper().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModCheckVars.F90,v $ $Revision: 1.7 $' private
Definition at line 63 of file PLAG_ModCheckVars.F90.
The documentation for this module was generated from the following file:
PLAG_ModCheckVars.F90