Rocstar: rocstar_rocfrac Module Reference
rocstar_rocfrac Module Reference
Data Types
type bcvalues
type rocfrac_global
Public Member Functions
character *9 function gettimestring (time)
subroutine associate_pointer (attr, ptr)
character *9 function gettimestring (time)
subroutine associate_pointer (attr, ptr)
Public Attributes
character(*), parameter surwin = "sfrac"
character(*), parameter volwin = "vfrac"
Detailed Description
Definition at line 53 of file ROCSTAR_RocFrac.f90.
Member Function/Subroutine Documentation
subroutine associate_pointer (type(rocfrac_global), pointer attr, type(rocfrac_global), pointer ptr)
Definition at line 488 of file ROCSTAR_RocFrac.f90.
References Node::attr(), and Aff_transformationS2< FT >::ptr().
subroutine associate_pointer (type(rocfrac_global), pointer attr, type(rocfrac_global), pointer ptr)
Definition at line 504 of file MP/Source/ROCSTAR_RocFrac.f90.
References Node::attr(), and Aff_transformationS2< FT >::ptr().
character*9 function gettimestring (real*8 time)
Definition at line 494 of file MP/Source/ROCSTAR_RocFrac.f90.
References gettimestring().
character*9 function gettimestring (real*8 time)
Definition at line 478 of file ROCSTAR_RocFrac.f90.
Referenced by gettimestring().
Member Data Documentation
character(*) parameter surwin = "sfrac"
Definition at line 71 of file ROCSTAR_RocFrac.f90.
character(*) parameter volwin = "vfrac"
Definition at line 72 of file ROCSTAR_RocFrac.f90.
The documentation for this module was generated from the following file:
ROCSTAR_RocFrac.f90