Rocstar: block Class Reference
block Class Reference
#include <adj.h>
Public Types
enum {
iMin =0, jMin =1, kMin =2, iMax =3,
jMax =4, kMax =5, nFaces =6
}
Public Member Functions
block (const blockDim &dim_, int originalNo_, int blockNo_, vector3d *nodeLocs_)
~block ()
int getBlockNumber (void) const
int getOriginalNumber (void) const
const blockDim & getDim (void) const
const vector3d & getLoc (const blockLoc &l) const
void split (int nPieces, vector< block * > &dest)
void addBC (const blockSpan &span, int bcNo)
void buildFaces (nodeMatcher &map)
face & getFace (int faceNo)
const face & getFace (int faceNo) const
int getFaceNo (const face *f)
Static Public Attributes
static const char * face2name [nFaces]
Private Member Functions
blockLoc pin (const blockLoc &l) const
block * subBlock (const blockSpan &span) const
Private Attributes
blockDim dim
int originalNo
int blockNo
vector3d * nodeLocs
vector< externalBCpatch > BCs [nFaces]
face * faces [nFaces]
Detailed Description
Definition at line 203 of file adj.h.
Member Enumeration Documentation
anonymous enum
Enumerator
iMin
jMin
kMin
iMax
jMax
kMax
nFaces
Definition at line 230 of file adj.h.
              {
           iMin=0,jMin=1,kMin=2,
           iMax=3,jMax=4,kMax=5,
           nFaces=6
         };
Constructor & Destructor Documentation
block (const blockDim & dim_, int originalNo_, int blockNo_, vector3d * nodeLocs_)
Definition at line 244 of file adj.cpp.
References blockBytes, hashableVector3d::checkVector(), dim, faces, blockDim::getSize(), i, nFaces, and nodeLocs.
Referenced by subBlock().
         :dim(dim_), originalNo(orig),blockNo(blockNo_), nodeLocs(nodeLocs_)
 {
         hashableVector3d::checkVector(nodeLocs[0]);
         hashableVector3d::checkVector(nodeLocs[dim.getSize()-1]);
         blockBytes+=dim.getSize()*sizeof(nodeLocs[0]);
         for (int i=0;i<nFaces;i++)
                 faces[i]=0;
 }
~block ()
Definition at line 254 of file adj.cpp.
References faces, i, nFaces, and nodeLocs.
 {
         for (int i=0;i<nFaces;i++)
                 delete faces[i];
         delete[] nodeLocs;
 }
Member Function Documentation
void addBC (const blockSpan & span, int bcNo)
Definition at line 262 of file adj.cpp.
References BCs, and blockSpan::getFace().
Referenced by readBoundaries(), and subBlock().
 {
         //Find the face the BC applies to
         int faceNo=span.getFace();
         if (faceNo==-1) {fprintf(stderr,"Boundary condition is volumetric!\n");abort();}
         //Apply the BC to that face
         BCs[faceNo].push_back(externalBCpatch(NULL,this,span,bcNo));
 }
void buildFaces (nodeMatcher & map)
Definition at line 273 of file adj.cpp.
References BCs, dim, face, and faces.
{
         int nx=dim[0];
         int ny=dim[1];
         int nz=dim[2];
         faces[0]=new face(this,map,BCs[0],
                 1,2,blockSpan(blockLoc(0,0,0),blockLoc(1,ny,nz)));
         faces[1]=new face(this,map,BCs[1],
                 0,2,blockSpan(blockLoc(0,0,0),blockLoc(nx,1,nz)));
         faces[2]=new face(this,map,BCs[2],
                 0,1,blockSpan(blockLoc(0,0,0),blockLoc(nx,ny,1)));
         faces[3]=new face(this,map,BCs[3],
                 1,2,blockSpan(blockLoc(nx-1,0,0),blockLoc(nx,ny,nz)));
         faces[4]=new face(this,map,BCs[4],
                 0,2,blockSpan(blockLoc(0,ny-1,0),blockLoc(nx,ny,nz)));
         faces[5]=new face(this,map,BCs[5],
                 0,1,blockSpan(blockLoc(0,0,nz-1),blockLoc(nx,ny,nz)));
 }
int getBlockNumber (void) const inline
Definition at line 219 of file adj.h.
References blockNo.
Referenced by buildFaces(), face::buildPatches(), findPartner(), mblockData::getPatchListWith(), mblockData::getPatchNumber(), face::markPatched(), adjRec::print(), mblockData::blockPatches::write(), mblockData::write(), writeBlock(), internalBCpatch::writeFlo(), and internalBCpatch::writeTop().
 { return blockNo; }
const blockDim& getDim (void) const inline
Definition at line 222 of file adj.h.
References dim.
Referenced by face::buildPatches(), checkQuality(), dirToCorner(), readBoundaries(), volume(), mblockData::blockPatches::write(), and writeBlock().
 {return dim;}
face& getFace (int faceNo) inline
Definition at line 248 of file adj.h.
References faces.
Referenced by buildFaces(), findPartner(), mblockData::blockPatches::init(), and writeBlock().
 {return *faces[faceNo];}
const face& getFace (int faceNo) const inline
Definition at line 249 of file adj.h.
References faces.
 {return *faces[faceNo];}
int getFaceNo (const face * f) inline
Definition at line 250 of file adj.h.
References faces, i, and nFaces.
Referenced by face::buildPatches().
{
                 for (int i=0;i<nFaces;i++)
                         if (faces[i]==f) return i;
                 return nFaces;
         }
const vector3d& getLoc (const blockLoc & l) const inline
Definition at line 223 of file adj.h.
References dim, and nodeLocs.
Referenced by buildFaces(), checkQuality(), and face::face().
           {return nodeLocs[dim[l]];}
int getOriginalNumber (void) const inline
Definition at line 220 of file adj.h.
References originalNo.
Referenced by face::buildPatches(), checkQuality(), face::face(), split(), and writeBlock().
 { return originalNo; }
blockLoc pin (const blockLoc & l) const private
Definition at line 77 of file split.cpp.
References dim, and i.
Referenced by bcondoutflowperf_gl(), modinterfacesbcond::BcondOutflowPerf_GL::bcondoutflowperf_gl(), init_py::burn_init_1d(), setup_py::steadytemp(), and subBlock().
 {
         blockLoc ret=l;
         for (int i=0;i<3;i++) {
                 if (ret[i]<0) ret[i]=0;
                 if (ret[i]>dim[i]) ret[i]=dim[i];
         }
         return ret;
 }
void split (int nPieces, vector< block * > & dest)
Definition at line 113 of file split.cpp.
References blockNo, dim, getOriginalNumber(), makefloParam::levelBad, makefloParam::levelGood, parameters, split(), makefloParam::splitAxis, makefloParam::splitRCB, and subBlock().
Referenced by split().
 {
         if (nPieces<=0) {
                 fprintf(stderr,"Asked to split block into %d pieces!\n",
                         nPieces);
                 abort();
         }
         else if (nPieces==1) {
                 //Reset serial number according to new position
                 blockNo=dest.size();
                 dest.push_back(this);
         }
         else
         { //Must split into several pieces
                 int splitAxis=parameters.splitAxis;
                 if (splitAxis==-1) //No axis specified--
                 { //Split on longest remaining axis
                         int splitLen=0;
                         for (int a=0;a<3;a++)
                                 if (dim[a]>splitLen) {
                                         splitAxis=a;
                                         splitLen=dim[a];
                                 }
                 }
                 int splitLen=dim[splitAxis];
                 //Determine the size of each half
                 int loPieces=(int)floor(nPieces/2.0);
                 int hiPieces=nPieces-loPieces;
                 int loSize;
                 if (parameters.splitRCB) //Always cut in half
                         loSize=(int)(splitLen/2);
                 else //Adapt cut location to corresponding number of pieces
                         loSize=splitLen*loPieces/nPieces;
                 //Round cut to the multigrid:
                 loSize=parameters.levelGood&((parameters.levelBad>>1)+loSize);
                 if (loSize==0)
                 { /*Asked to split too far*/
                         fprintf(stderr,"Couldn't split block %d any further-- you must:\n"
                         " -increase the input grid resolution\n"
                         " -decrease the number of requested output blocks\n"
                         "%s",
                         1+getOriginalNumber(),
                         (parameters.levelBad)?" -decrease the multigrid resolution\n":"");
                         exit(1);
                 }
                 //Split this block along that axis
                 blockDim origin(0,0,0);
                 blockDim loEnd=dim; loEnd[splitAxis]=loSize+1;
                 blockDim hiStart=origin; hiStart[splitAxis]=loSize;
                 block *lo=subBlock(blockSpan(origin,loEnd));
                 block *hi=subBlock(blockSpan(hiStart,dim));
                 //Remove ourselves-- we are completely
                 // replaced by our children
                 delete this;
                 //Recursively split the new blocks
                 lo->split(loPieces,dest);
                 hi->split(hiPieces,dest);
         }
 }
block * subBlock (const blockSpan & span) const private
Definition at line 88 of file split.cpp.
References addBC(), externalBCpatch::bcNo, BCs, block(), BLOCKSPAN_FOR, dim, blockSpan::end, blockSpan::getDim(), blockDim::getSize(), i, nFaces, nodeLocs, originalNo, pin(), patch::srcSpan, and blockSpan::start.
Referenced by split().
 {
         //Create the new node location array
         blockDim ns=span.getDim();
         vector3d *newLocs=new vector3d[ns.getSize()];
         blockLoc i;
         BLOCKSPAN_FOR(i,span)
                 newLocs[ns[i-span.start]]=nodeLocs[dim[i]];
         block *ret=new block(ns,originalNo,-1,newLocs);
         //Copy over boundary conditions, remapping locations
         for (int f=0;f<nFaces;f++)
         for (unsigned int c=0;c<BCs[f].size();c++) {
                 const externalBCpatch &bc=BCs[f][c];
                 blockSpan bs(ret->pin(bc.srcSpan.start-span.start),
                              ret->pin(bc.srcSpan.end  -span.start));
                 if (bs.hasArea())
                 //Add this boundary to the new block
                         ret->addBC(bs,bc.bcNo);
         }
         return ret;
 }
Member Data Documentation
vector<externalBCpatch> BCs[nFaces] private
Definition at line 240 of file adj.h.
Referenced by addBC(), buildFaces(), and subBlock().
int blockNo private
Definition at line 206 of file adj.h.
Referenced by getBlockNumber(), and split().
blockDim dim private
Definition at line 204 of file adj.h.
Referenced by block(), buildFaces(), getDim(), getLoc(), pin(), split(), and subBlock().
const char * face2name static
Initial value:
={
        "iMin","jMin","kMin",
        "iMax","jMax","kMax"
}
Definition at line 236 of file adj.h.
Referenced by buildFaces(), face::buildPatches(), and writeBlock().
face* faces[nFaces] private
Definition at line 241 of file adj.h.
Referenced by block(), buildFaces(), getFace(), getFaceNo(), and ~block().
vector3d* nodeLocs private
Definition at line 207 of file adj.h.
Referenced by block(), getLoc(), subBlock(), and ~block().
int originalNo private
Definition at line 205 of file adj.h.
Referenced by getOriginalNumber(), and subBlock().
The documentation for this class was generated from the following files:
adj.h
adj.cpp
split.cpp