Rocstar: CLineSegment Class Reference
CLineSegment Class Reference
#include <GeoPrimitives.H>
Public Member Functions
CLineSegment ()
CLineSegment (const CPoint &p)
CLineSegment (const CPoint &pb, const CPoint &pe)
double length () const
CVector slope () const
bool has_point (const CPoint &p3) const
CPoint & point1 ()
CPoint & point2 ()
const CPoint & point1 () const
const CPoint & point2 () const
CLineSegment & point1 (const CPoint &p)
CLineSegment & point2 (const CPoint &p)
Protected Attributes
CPoint p1
CPoint p2
Detailed Description
Definition at line 1059 of file GeoPrimitives.H.
Constructor & Destructor Documentation
CLineSegment () inline
Definition at line 1064 of file GeoPrimitives.H.
       : p1(0,0,0),p2(0,0,0)
     {};
CLineSegment (const CPoint & p) inline
Definition at line 1067 of file GeoPrimitives.H.
       : p1(0,0,0),p2(p)
     {};
CLineSegment (const CPoint & pb, const CPoint & pe) inline
Definition at line 1070 of file GeoPrimitives.H.
       : p1(pb),p2(pe)
     {};
Member Function Documentation
bool has_point (const CPoint & p3) const inline
Definition at line 1083 of file GeoPrimitives.H.
References CLine::has_point(), CLineSegment::p1, CLineSegment::p2, CPoint::x(), CPoint::y(), and CPoint::z().
     {
       if(p3 == p1 || p3 == p2) return true;
       if(p1 == p2) return false;
       CLine l(p1,p2);
       if(!l.has_point(p3)) return false;
       double u;
       if(p1.x() != p2.x())
         u = (p3.x() - p1.x())/(p2.x() - p1.x());
       else if(p1.y() != p2.y())
         u = (p3.y() - p1.y())/(p2.y() - p1.y());
       else if(p1.z() != p2.z())
         u = (p3.z() - p1.z())/(p2.z() - p1.z());
       return ( u >= 0.0 && u <= 1.0 );
     };
double length () const inline
Definition at line 1073 of file GeoPrimitives.H.
References CVector::norm(), CLineSegment::p1, CLineSegment::p2, and v.
     {
       CVector v(p1,p2);
       return(v.norm());
     };
CPoint& point1 () inline
Definition at line 1098 of file GeoPrimitives.H.
References CLineSegment::p1.
     {
       return (p1);
     };
const CPoint& point1 () const inline
Definition at line 1106 of file GeoPrimitives.H.
References CLineSegment::p1.
     {
       return (p1);
     };
CLineSegment& point1 (const CPoint & p) inline
Definition at line 1114 of file GeoPrimitives.H.
References CLineSegment::p1.
     {
       p1 = p;
       return(*this);
     };
CPoint& point2 () inline
Definition at line 1102 of file GeoPrimitives.H.
References CLineSegment::p2.
     {
       return (p2);
     };
const CPoint& point2 () const inline
Definition at line 1110 of file GeoPrimitives.H.
References CLineSegment::p2.
     {
       return (p2);
     };
CLineSegment& point2 (const CPoint & p) inline
Definition at line 1119 of file GeoPrimitives.H.
References CLineSegment::p2.
     {
       p2 = p;
       return(*this);
     };
CVector slope () const inline
Definition at line 1078 of file GeoPrimitives.H.
References CLineSegment::p1, CLineSegment::p2, and v.
     {
       CVector v(p1,p2);
     return(v);
     };
Member Data Documentation
CPoint p1 protected
Definition at line 1061 of file GeoPrimitives.H.
Referenced by CLineSegment::has_point(), CLineSegment::length(), CLineSegment::point1(), and CLineSegment::slope().
CPoint p2 protected
Definition at line 1062 of file GeoPrimitives.H.
Referenced by CLineSegment::has_point(), CLineSegment::length(), CLineSegment::point2(), and CLineSegment::slope().
The documentation for this class was generated from the following file:
GeoPrimitives.H