Rocstar: rflu_moddimensions Module Reference
rflu_moddimensions Module Reference
Public Member Functions
subroutine, public rflu_readdimensions (pRegion)
subroutine, public rflu_readdimensionswrapper (pRegion)
integer function, public rflu_setmaxdimension (global, nXyzTot)
subroutine, public rflu_setmaxdimensions (pRegion)
subroutine, public rflu_writedimensions (pRegion)
subroutine, public rflu_writedimensionsborders (pRegion)
subroutine, public rflu_writedimensionswrapper (pRegion, writeMode)
Public Attributes
integer, parameter, public write_dimens_mode_force = 0
integer, parameter, public write_dimens_mode_maybe = 1
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModDimensions.F90,v $ $Revision: 1.15 $'
integer, parameter, private ratiomax2tot = 4
Detailed Description
Definition at line 39 of file RFLU_ModDimensions.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_readdimensions (type(t_region), pointer pRegion)
Definition at line 108 of file RFLU_ModDimensions.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_readdimensionswrapper(), rflucells(), rfluconv(), rfluinit(), rflumap(), rflupart(), rflupick(), and turb_initinputvalues().
subroutine, public rflu_readdimensionswrapper (type(t_region), pointer pRegion)
Definition at line 474 of file RFLU_ModDimensions.F90.
References moderror::deregisterfunction(), plag_moddimensions::plag_rflu_readdimensions(), moderror::registerfunction(), rflu_modrocstario::rflu_genx_getdimensions(), and rflu_readdimensions().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregions_ens(), rflu_postprocessregionscommon1(), and rfluinit().
integer function, public rflu_setmaxdimension (type(t_global), pointer global, integer, intent(in) nXyzTot)
Definition at line 559 of file RFLU_ModDimensions.F90.
Referenced by rflu_modcentaur::rflu_convcentaur2rocflu(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_modgambit::rflu_convgambit2rocflu(), rflu_modmesh3d::rflu_convmesh3d2rocflu(), rflu_modtetmesh::rflu_convtetmesh2rocflu(), rflu_modvgridns::rflu_convvgridns2rocflu(), rflu_modcentaur::rflu_readgridcentaurascii(), rflu_modcentaur::rflu_readgridcentaurbinary(), rflu_modcobalt::rflu_readgridcobalt(), rflu_modgambit::rflu_readgridgambitneutral(), rflu_modmesh3d::rflu_readgridmesh3d(), rflu_modtetmesh::rflu_readgridtetmesh(), and rflu_modvgridns::rflu_readgridvgridns().
subroutine, public rflu_setmaxdimensions (type(t_region), pointer pRegion)
Definition at line 613 of file RFLU_ModDimensions.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modcobalt::rflu_convcobalt2rocflu(), and rflupart().
subroutine, public rflu_writedimensions (type(t_region), pointer pRegion)
Definition at line 720 of file RFLU_ModDimensions.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_writedimensionswrapper(), and rflupart().
subroutine, public rflu_writedimensionsborders (type(t_region), pointer pRegion)
Definition at line 928 of file RFLU_ModDimensions.F90.
References buildfilenamebasic(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflupart().
subroutine, public rflu_writedimensionswrapper (type(t_region), pointer pRegion, integer, intent(in) writeMode)
Definition at line 1112 of file RFLU_ModDimensions.F90.
References moderror::deregisterfunction(), plag_moddimensions::plag_rflu_writedimensions(), moderror::registerfunction(), rflu_modrocstario::rflu_genx_decidewritefile(), and rflu_writedimensions().
Referenced by rflu_endflowsolver(), rflu_mergepostprocessregions(), rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
Member Data Documentation
integer, parameter, private ratiomax2tot = 4 private
Definition at line 80 of file RFLU_ModDimensions.F90.
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModDimensions.F90,v $ $Revision: 1.15 $' private
Definition at line 77 of file RFLU_ModDimensions.F90.
integer, parameter, public write_dimens_mode_force = 0
Definition at line 70 of file RFLU_ModDimensions.F90.
integer, parameter, public write_dimens_mode_maybe = 1
Definition at line 70 of file RFLU_ModDimensions.F90.
The documentation for this module was generated from the following file:
RFLU_ModDimensions.F90