Rocstar: rflu_modrocstartools Module Reference
rflu_modrocstartools Module Reference
Public Member Functions
subroutine, public rflu_genx_constraindisp (pRegion)
subroutine, public rflu_genx_initbflag (pRegion)
subroutine, public rflu_genx_movegrid (regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRocstarTools.F90,v $ $Revision: 1.29 $'
Detailed Description
Definition at line 39 of file RFLU_ModRocstarTools.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_genx_constraindisp (type(t_region), pointer pRegion)
Definition at line 145 of file RFLU_ModRocstarTools.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), sign(), sqrt(), x, y, and z.
Referenced by rflu_movegridwrapper().
subroutine, public rflu_genx_initbflag (type(t_region), pointer pRegion)
Definition at line 551 of file RFLU_ModRocstarTools.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), sign(), sqrt(), x, y, and z.
Referenced by rflu_flowsolver(), rflu_modrocstaradmin::rflu_genx_createdatainterf(), rflu_initflowsolver(), and rungekuttamp().
subroutine, public rflu_genx_movegrid (type(t_region), dimension(:), pointer regions)
Definition at line 829 of file RFLU_ModRocstarTools.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and sqrt().
Referenced by rflu_movegridwrapper().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRocstarTools.F90,v $ $Revision: 1.29 $' private
Definition at line 67 of file RFLU_ModRocstarTools.F90.
The documentation for this module was generated from the following file:
RFLU_ModRocstarTools.F90