Rocstar: Randomize Class Reference
Randomize Class Reference
Randomly perftubs the (un-culled) vertices.
#include <Randomize.hpp>
Public Member Functions
Randomize ()
Constructor defaulting mPercent to .05.
Randomize (double percent)
Constructor allowing user to set mPercent.
virtual ~Randomize ()
Randomize ()
Constructor defaulting mPercent to .05.
Randomize (double percent)
Constructor allowing user to set mPercent.
virtual ~Randomize ()
Public Member Functions inherited from VertexMover
virtual ~VertexMover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
Improves the quality of the MeshSet, calling some methods specified in a class derived from VertexMover.
virtual ~VertexMover ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
Public Member Functions inherited from QualityImprover
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
virtual ~QualityImprover ()
void set_name (msq_std::string name)
provides a name to the QualityImprover (use it in constructor).
virtual msq_std::string get_name ()
retrieves the QualityImprover name. A default name should be set in the constructor.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
void set_inner_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the concrete solver's optimization.
void set_outer_termination_criterion (TerminationCriterion *crit)
Sets in the termination criterion for the outer loop over patches.
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Protected Member Functions
virtual void initialize (PatchData &pd, MsqError &err)
virtual void optimize_vertex_positions (PatchData &pd, MsqError &err)
virtual void initialize_mesh_iteration (PatchData &pd, MsqError &err)
virtual void terminate_mesh_iteration (PatchData &pd, MsqError &err)
virtual void cleanup ()
virtual void initialize (PatchData &pd, MsqError &err)
virtual void optimize_vertex_positions (PatchData &pd, MsqError &err)
virtual void initialize_mesh_iteration (PatchData &pd, MsqError &err)
virtual void terminate_mesh_iteration (PatchData &pd, MsqError &err)
virtual void cleanup ()
Protected Member Functions inherited from VertexMover
VertexMover ()
size_t check_feasible (PatchData &pd, MsqError &err)
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
VertexMover ()
size_t check_feasible (PatchData &pd, MsqError &err)
CHECK FEASIBLE IS NOT YET IMPLEMENTED.
Protected Member Functions inherited from QualityImprover
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
QualityImprover ()
const MeshSet * get_mesh_set () const
MeshSet * get_mesh_set ()
void set_mesh_set (MeshSet *ms)
TerminationCriterion * get_outer_termination_criterion ()
return the outer termination criterion pointer
TerminationCriterion * get_inner_termination_criterion ()
return the inner termination criterion pointer
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Private Member Functions
void randomize_vertex (PatchData &pd, size_t num_vtx, MsqVertex &free_vtx, MsqError &err)
Perturbs the free vertex randomly.
void randomize_vertex (PatchData &pd, size_t num_vtx, MsqVertex &free_vtx, MsqError &err)
Private Attributes
double mPercent
Additional Inherited Members
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Protected Attributes inherited from VertexMover
ObjectiveFunction * objFunc
Detailed Description
Randomly perftubs the (un-culled) vertices.
Definition at line 52 of file includeLinks/Randomize.hpp.
Constructor & Destructor Documentation
Randomize ()
Constructor defaulting mPercent to .05.
Definition at line 44 of file QualityImprover/VertexMover/Randomize/Randomize.cpp.
References Randomize::mPercent, and QualityImprover::set_name().
 {
   this->set_name("Randomize");
   mPercent=.05;
 }
Randomize (double percent)
Constructor allowing user to set mPercent.
Definition at line 50 of file QualityImprover/VertexMover/Randomize/Randomize.cpp.
References Randomize::mPercent, and QualityImprover::set_name().
 {
   this->set_name("Randomize");
   mPercent=percent;
 }
virtual ~Randomize () inline virtual
Definition at line 60 of file includeLinks/Randomize.hpp.
 { }
Randomize ()
Constructor defaulting mPercent to .05.
Randomize (double percent)
Constructor allowing user to set mPercent.
virtual ~Randomize () inline virtual
Definition at line 60 of file src/QualityImprover/VertexMover/Randomize/Randomize.hpp.
 { }
Member Function Documentation
void cleanup () protected virtual
Implements VertexMover.
Definition at line 90 of file QualityImprover/VertexMover/Randomize/Randomize.cpp.
 {
   //  cout << "- Executing Randomize::iteration_end()\n";
 }
virtual void cleanup () protected virtual
Implements VertexMover.
void initialize (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 56 of file QualityImprover/VertexMover/Randomize/Randomize.cpp.
References PatchData::ELEMENTS_ON_VERTEX_PATCH, and PatchDataUser::set_patch_type().
 {
   this->set_patch_type(PatchData::ELEMENTS_ON_VERTEX_PATCH, err, 1);
 }
virtual void initialize (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
virtual void initialize_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
void initialize_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 61 of file QualityImprover/VertexMover/Randomize/Randomize.cpp.
 {
   //  cout << "- Executing Randomize::iteration_complete()\n";
 }
virtual void optimize_vertex_positions (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
void optimize_vertex_positions (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 66 of file QualityImprover/VertexMover/Randomize/Randomize.cpp.
References PatchData::get_vertex_array(), MSQ_ERRRTN, MsqFreeVertexIndexIterator::next(), PatchData::num_vertices(), Randomize::randomize_vertex(), MsqFreeVertexIndexIterator::reset(), PatchData::snap_vertex_to_domain(), and MsqFreeVertexIndexIterator::value().
 {
     //cout << "- Executing Randomize::optimize_vertex_position()\n";
   int num_local_vertices = pd.num_vertices();
   // gets the array of coordinates for the patch and print it
   MsqVertex *patch_coords = pd.get_vertex_array(err); MSQ_ERRRTN(err);
   // does the randomize smooth
   MsqFreeVertexIndexIterator free_iter(&pd, err); MSQ_ERRRTN(err);
   free_iter.reset();
   free_iter.next();
     //find the free vertex.
   int m=free_iter.value();
   randomize_vertex(pd, num_local_vertices,
                    patch_coords[m], err);  MSQ_ERRRTN(err);
   pd.snap_vertex_to_domain(m,err); MSQ_ERRRTN(err);
 }
void randomize_vertex (PatchData & pd, size_t num_vtx, MsqVertex & free_vtx, MsqError & err) inline private
Function calculates a scale factor for the patch, then moves the incident vertex randomly in each of the three coordinate directions (relative to the scale factor multiplied by mPercent).
void randomize_vertex (PatchData & pd, size_t num_vtx, MsqVertex & free_vtx, MsqError & err) inline private
Perturbs the free vertex randomly.
Function calculates a scale factor for the patch, then moves the incident vertex randomly in each of the three coordinate directions (relative to the scale factor multiplied by mPercent).
Definition at line 83 of file includeLinks/Randomize.hpp.
References PatchData::get_vertex_array(), PatchData::get_vertex_index(), i, j, Mesquite::length(), Randomize::mPercent, MSQ_ERRRTN, MSQ_PRINT, and cimg_library::cimg::rand().
Referenced by Randomize::optimize_vertex_positions().
   {
     size_t i;
     short j;
     MsqVertex* verts = pd.get_vertex_array(err);  MSQ_ERRRTN(err);
       //a scale w.r.t. the patch size
     double scale_factor=0.0;
       //a "random" number between -1 and 1
     double rand_double=0.0;
       //a "random" int
     int rand_int=0;
     if (num_vtx<=1){
       MSQ_PRINT(1)("WARNING: Number of incident vertex is zero.  Returning.\n");
       return;
     }
     size_t free_ind = pd.get_vertex_index(&(free_vtx));
     for (i=0;i<num_vtx;++i){
       if(i != free_ind)
         scale_factor+=(verts[i]-free_vtx).length();
     }
     scale_factor/=( (double) num_vtx - 1.0 );
     for (j=0;j<3;++j){
       rand_int = rand();
         //number between 0 and 1000
       rand_int = rand_int%1000;
         //number between -1 and 1
       rand_double = (((double) rand_int)/500.0)-1.0;
       free_vtx[j] += scale_factor*rand_double*mPercent;
     }
     return;
   }
void terminate_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Definition at line 85 of file QualityImprover/VertexMover/Randomize/Randomize.cpp.
 {
   //  cout << "- Executing Randomize::iteration_complete()\n";
 }
virtual void terminate_mesh_iteration (PatchData & pd, MsqError & err) protected virtual
Implements VertexMover.
Member Data Documentation
double mPercent private
Parameters
The percentage of the scale factor each vertex will be moved.
Definition at line 71 of file includeLinks/Randomize.hpp.
Referenced by Randomize::Randomize(), and Randomize::randomize_vertex().
The documentation for this class was generated from the following files:
includeLinks/Randomize.hpp
QualityImprover/VertexMover/Randomize/Randomize.cpp