Rocstar: rflo_modgridregionshape Module Reference
rflo_modgridregionshape Module Reference
Public Member Functions
subroutine, public rflo_gridflatpatch (region, patch)
subroutine, public rflo_findfunkyblocks (regions)
subroutine rflo_blockskewedcell (region)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModGridRegionShape.F90,v $ $Revision: 1.3 $'
Detailed Description
Definition at line 39 of file RFLO_ModGridRegionShape.F90.
Member Function/Subroutine Documentation
subroutine rflo_blockskewedcell (type(t_region) region)
Definition at line 452 of file RFLO_ModGridRegionShape.F90.
References moderror::deregisterfunction(), i, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, moderror::registerfunction(), rflo_getdimensphys(), rflo_getnodeoffset(), and sqrt().
Referenced by rflo_findfunkyblocks().
subroutine, public rflo_findfunkyblocks (type (t_region), dimension(:), pointer regions)
Definition at line 393 of file RFLO_ModGridRegionShape.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_blockskewedcell(), and rflo_calcfacevectors().
Referenced by rflo_getgeometry().
subroutine, public rflo_gridflatpatch (type(t_region) region, type(t_patch) patch)
Definition at line 86 of file RFLO_ModGridRegionShape.F90.
References moderror::deregisterfunction(), ibeg, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_modvectortensor::rflo_normcrossprod(), and sqrt().
Referenced by rflo_getgeometry().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModGridRegionShape.F90,v $ $Revision: 1.3 $' private
Definition at line 62 of file RFLO_ModGridRegionShape.F90.
The documentation for this module was generated from the following file:
RFLO_ModGridRegionShape.F90