Rocstar: TestObject Class Reference
TestObject Class Reference
#include <UtilTest.H>
Public Member Functions
void Prologue ()
Set up the tests and any test fixture constructs.
void Test__GetNextContent (Util::TestResults &result)
void Process (Util::TestResults &result)
Process all tests and populate a "results" object.
void ProcessTests (std::list< std::string > &test_names, Util::TestResults &result)
Process named tests from a list and populate a "results" object.
Public Member Functions inherited from TestingObject< Util::TestResults >
virtual void RunTest (const std::string &name, Util::TestResults &results)
Run a particular test.
virtual void Epilogue ()
Clean up any test fixtures that need cleaning.
virtual ~TestingObject ()
Private Attributes
std::string TestString1
Detailed Description
Definition at line 16 of file UtilTest.H.
Member Function Documentation
void Process (Util::TestResults & results) inline virtual
Process all tests and populate a "results" object.
Reimplemented from TestingObject< Util::TestResults >.
Definition at line 46 of file UtilTest.H.
References TestingObject< Util::TestResults >::Epilogue(), TestObject::Prologue(), and TestObject::Test__GetNextContent().
Referenced by IRAD::Util::UtilTest().
{
         Prologue();
         Test__GetNextContent(result);
         Epilogue();
       }
void ProcessTests (std::list< std::string > & names, Util::TestResults & results) inline virtual
Process named tests from a list and populate a "results" object.
Reimplemented from TestingObject< Util::TestResults >.
Definition at line 53 of file UtilTest.H.
References TestingObject< Util::TestResults >::Epilogue(), TestObject::Prologue(), and TestObject::Test__GetNextContent().
{
         Prologue();
         std::list<std::string>::iterator tni = test_names.begin();
         while(tni != test_names.end())
           {
             std::string testname(*tni++);
             if(testname == "GetNextContent")
               Test__GetNextContent(result);
           }
         Epilogue();
       }
void Prologue () inline virtual
Set up the tests and any test fixture constructs.
Reimplemented from TestingObject< Util::TestResults >.
Definition at line 21 of file UtilTest.H.
References TestObject::TestString1.
Referenced by TestObject::Process(), and TestObject::ProcessTests().
                       {
         std::ostringstream Ostr;
         Ostr << "#"       << std::endl
              << " " << std::endl
              << "\t" << std::endl
              << "Test       # Comment" << std::endl
              << "#         " << std::endl;
         TestString1.assign(Ostr.str());
       }
void Test__GetNextContent (Util::TestResults & result) inline
Definition at line 34 of file UtilTest.H.
References IRAD::Util::GetNextContent(), TestObject::TestString1, and TestResults::UpdateResult().
Referenced by TestObject::Process(), and TestObject::ProcessTests().
{
         std::istringstream Istr(TestString1);
         std::string next_content(Util::GetNextContent(Istr));
         std::string line;
         std::getline(Istr,line);
         result.UpdateResult("GetNextContent:CommentsAndWhiteSpace",
                             next_content == "Test       ");
         result.UpdateResult("GetNextContent:StreamObject",
                             line == "#         ");
       }
Member Data Documentation
std::string TestString1 private
Definition at line 19 of file UtilTest.H.
Referenced by TestObject::Prologue(), and TestObject::Test__GetNextContent().
The documentation for this class was generated from the following file:
UtilTest.H