Rocstar: rflu_modstencilsbfaces Module Reference
rflu_modstencilsbfaces Module Reference
Public Member Functions
subroutine rflu_buildbf2cstencil (pRegion, pPatch)
subroutine, public rflu_buildbf2cstencilwrapper (pRegion, pPatch, constrInput)
subroutine, public rflu_createbf2cstencilwrapper (pRegion, pPatch)
subroutine, public rflu_destroybf2cstencilwrapper (pRegion, pPatch)
subroutine, public rflu_setinfobf2cstencilwrapper (pRegion, pPatch, orderNominal)
Private Member Functions
subroutine rflu_buildbf2cstencil_1d (pRegion, pPatch)
subroutine rflu_createbf2cstencil_1d (pRegion, pPatch)
subroutine rflu_createbf2cstencil (pRegion, pPatch)
subroutine rflu_destroybf2cstencil_1d (pRegion, pPatch)
subroutine rflu_destroybf2cstencil (pRegion, pPatch)
subroutine rflu_nullifybf2cstencil_1d (pRegion, pPatch)
subroutine rflu_nullifybf2cstencil (pRegion, pPatch)
subroutine rflu_setinfobf2cstencil_1d (pRegion, pPatch, orderNominalInput)
subroutine rflu_setinfobf2cstencil (pRegion, pPatch, orderNominalInput)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsBFaces.F90,v $ $Revision: 1.10 $'
Detailed Description
Definition at line 39 of file RFLU_ModStencilsBFaces.F90.
Member Function/Subroutine Documentation
subroutine rflu_buildbf2cstencil (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 424 of file RFLU_ModStencilsBFaces.F90.
References Line_2< R, T >::a(), ainv(), moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), max(), min(), Generic_element_2::order(), moderror::registerfunction(), rflu_modstencilsutils::rflu_addbfaces(), rflu_modstencilsutils::rflu_addcelllayer(), rflu_modstencilsutils::rflu_addfacevertneighbs(), rflu_invertmatrixsvd(), rflu_modstencilsutils::rflu_sortbfaces(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_buildbf2cstencilwrapper().
subroutine rflu_buildbf2cstencil_1d (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 98 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modtools::floatequal(), moderror::registerfunction(), rflu_modstencilsutils::rflu_addcelllayer_1d(), and rflu_modpatchutils::rflu_getpatchnormaldirection().
Referenced by rflu_buildbf2cstencilwrapper().
subroutine, public rflu_buildbf2cstencilwrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in), optional constrInput)
Definition at line 920 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_buildbf2cstencil(), and rflu_buildbf2cstencil_1d().
Referenced by rflu_initflowsolver(), and rflupick().
subroutine rflu_createbf2cstencil (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1111 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybf2cstencil().
Referenced by rflu_createbf2cstencilwrapper().
subroutine rflu_createbf2cstencil_1d (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1010 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybf2cstencil_1d().
Referenced by rflu_createbf2cstencilwrapper().
subroutine, public rflu_createbf2cstencilwrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 1212 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_createbf2cstencil(), and rflu_createbf2cstencil_1d().
Referenced by rflu_initflowsolver(), and rflupick().
subroutine rflu_destroybf2cstencil (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1404 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybf2cstencil().
Referenced by rflu_destroybf2cstencilwrapper().
subroutine rflu_destroybf2cstencil_1d (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1284 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifybf2cstencil_1d().
Referenced by rflu_destroybf2cstencilwrapper().
subroutine, public rflu_destroybf2cstencilwrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 1526 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_destroybf2cstencil(), and rflu_destroybf2cstencil_1d().
Referenced by rflu_endflowsolver(), and rflupick().
subroutine rflu_nullifybf2cstencil (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1665 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createbf2cstencil(), and rflu_destroybf2cstencil().
subroutine rflu_nullifybf2cstencil_1d (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1599 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createbf2cstencil_1d(), and rflu_destroybf2cstencil_1d().
subroutine rflu_setinfobf2cstencil (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) orderNominalInput) private
Definition at line 1847 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), max(), moderror::registerfunction(), and rflu_computestencilsize().
Referenced by rflu_setinfobf2cstencilwrapper().
subroutine rflu_setinfobf2cstencil_1d (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) orderNominalInput) private
Definition at line 1736 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), max(), and moderror::registerfunction().
Referenced by rflu_setinfobf2cstencilwrapper().
subroutine, public rflu_setinfobf2cstencilwrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) orderNominal)
Definition at line 1958 of file RFLU_ModStencilsBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_setinfobf2cstencil(), and rflu_setinfobf2cstencil_1d().
Referenced by rflu_initflowsolver(), and rflupick().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsBFaces.F90,v $ $Revision: 1.10 $' private
Definition at line 68 of file RFLU_ModStencilsBFaces.F90.
The documentation for this module was generated from the following file:
RFLU_ModStencilsBFaces.F90