Rocstar: Segment_2_Segment_2_pair< R > Class Template Reference
Segment_2_Segment_2_pair< R > Class Template Reference
#include <Segment_2_Segment_2_intersection.h>
Public Types
enum Intersection_results { NO, POINT, SEGMENT }
Public Member Functions
Segment_2_Segment_2_pair ()
Segment_2_Segment_2_pair (Segment_2< R > const *seg1, Segment_2< R > const *seg2)
~Segment_2_Segment_2_pair ()
Intersection_results intersection_type () const
bool intersection (Point_2< R > &result) const
bool intersection (Segment_2< R > &result) const
Protected Attributes
Segment_2< R > const * _seg1
Segment_2< R > const * _seg2
bool _known
Intersection_results _result
Point_2< R > _intersection_point
Point_2< R > _other_point
Detailed Description
template<class R>
class Segment_2_Segment_2_pair< R >
Definition at line 61 of file Segment_2_Segment_2_intersection.h.
Member Enumeration Documentation
enum Intersection_results
Enumerator
NO
POINT
SEGMENT
Definition at line 63 of file Segment_2_Segment_2_intersection.h.
 {NO, POINT, SEGMENT};
Constructor & Destructor Documentation
CGAL_BEGIN_NAMESPACE Segment_2_Segment_2_pair ()
Definition at line 437 of file Segment_2_Segment_2_intersection.h.
 {
     _seg1 = 0;
     _seg2 = 0;
     _known = false;
 }
Segment_2_Segment_2_pair (Segment_2< R > const * seg1, Segment_2< R > const * seg2)
Definition at line 445 of file Segment_2_Segment_2_intersection.h.
 {
     _seg1 = seg1;
     _seg2 = seg2;
     _known = false;
 }
~Segment_2_Segment_2_pair () inline
Definition at line 67 of file Segment_2_Segment_2_intersection.h.
 {}
Member Function Documentation
bool intersection (Point_2< R > & result) const
Definition at line 570 of file Segment_2_Segment_2_intersection.h.
 {
     if (!_known)
         intersection_type();
     if (_result != POINT)
         return false;
     result = _intersection_point;
     return true;
 }
bool intersection (Segment_2< R > & result) const
Definition at line 582 of file Segment_2_Segment_2_intersection.h.
 {
     if (!_known)
         intersection_type();
     if (_result != SEGMENT)
         return false;
     result = Segment_2<R>(_intersection_point, _other_point);
     return true;
 }
Segment_2_Segment_2_pair< R >::Intersection_results intersection_type () const
Definition at line 456 of file Segment_2_Segment_2_intersection.h.
References NTS::abs(), CGAL_NTS, do_overlap(), Line_2_Line_2_pair< R >::intersection(), Line_2_Line_2_pair< R >::intersection_type(), Point_2< T >::x(), Vector_2< Type >::x(), Point_2< T >::y(), and Vector_2< Type >::y().
 {
     if (_known)
         return _result;
     // The non const this pointer is used to cast away const.
     _known = true;
     if (!do_overlap(_seg1->bbox(), _seg2->bbox())) {
         _result = NO;
         return _result;
     }
     Line_2<R> const &l1 = _seg1->supporting_line();
     Line_2<R> const &l2 = _seg2->supporting_line();
     Line_2_Line_2_pair<R> linepair(&l1, &l2);
     switch ( linepair.intersection_type()) {
     case Line_2_Line_2_pair<R>::NO:
         _result = NO;
         break;
     case Line_2_Line_2_pair<R>::POINT:
         linepair.intersection(_intersection_point);
         _result = (_seg1->collinear_has_on(_intersection_point)
             && _seg2->collinear_has_on(_intersection_point)) ? POINT : NO;
         break;
     case Line_2_Line_2_pair<R>::LINE:
         {
         typedef typename R::RT RT;
         Point_2<R> const &start1 = _seg1->start();
         Point_2<R> const &end1   = _seg1->end();
         Point_2<R> const &start2 = _seg2->start();
         Point_2<R> const &end2   = _seg2->end();
         Vector_2<R> diff1 = end1-start1;
         Point_2<R> const *minpt;
         Point_2<R> const *maxpt;
         if (CGAL_NTS abs(diff1.x()) > CGAL_NTS abs(diff1.y())) {
             if (start1.x() < end1.x()) {
                 minpt = &start1;
                 maxpt = &end1;
             } else {
                 minpt = &end1;
                 maxpt = &start1;
             }
             if (start2.x() < end2.x()) {
                 if (start2.x() > minpt->x()) {
                     minpt = &start2;
                 }
                 if (end2.x() < maxpt->x()) {
                     maxpt = &end2;
                 }
             } else {
                 if (end2.x() > minpt->x()) {
                     minpt = &end2;
                 }
                 if (start2.x() < maxpt->x()) {
                     maxpt = &start2;
                 }
             }
             if (maxpt->x() < minpt->x()) {
                 _result = NO;
                 return _result;
             }
             if (maxpt->x() == minpt->x()) {
                 _intersection_point = *minpt;
                 _result = POINT;
                 return _result;
             }
             _intersection_point = *minpt;
             _other_point = *maxpt;
             _result = SEGMENT;
             return _result;
         } else {
             if (start1.y() < end1.y()) {
                 minpt = &start1;
                 maxpt = &end1;
             } else {
                 minpt = &end1;
                 maxpt = &start1;
             }
             if (start2.y() < end2.y()) {
                 if (start2.y() > minpt->y()) {
                     minpt = &start2;
                 }
                 if (end2.y() < maxpt->y()) {
                     maxpt = &end2;
                 }
             } else {
                 if (end2.y() > minpt->y()) {
                     minpt = &end2;
                 }
                 if (start2.y() < maxpt->y()) {
                     maxpt = &start2;
                 }
             }
             if (maxpt->y() < minpt->y()) {
                 _result = NO;
                 return _result;
             }
             if (maxpt->y() == minpt->y()) {
                 _intersection_point = *minpt;
                 _result = POINT;
                 return _result;
             }
             _intersection_point = *minpt;
             _other_point = *maxpt;
             _result = SEGMENT;
             return _result;
         }
         }
     }
     return _result;
 }
Member Data Documentation
Point_2<R> _intersection_point mutable protected
Definition at line 190 of file Segment_2_Segment_2_intersection.h.
bool _known mutable protected
Definition at line 188 of file Segment_2_Segment_2_intersection.h.
Point_2<R> _other_point mutable protected
Definition at line 190 of file Segment_2_Segment_2_intersection.h.
Intersection_results _result mutable protected
Definition at line 189 of file Segment_2_Segment_2_intersection.h.
Segment_2<R> const* _seg1 protected
Definition at line 186 of file Segment_2_Segment_2_intersection.h.
Segment_2<R> const* _seg2 protected
Definition at line 187 of file Segment_2_Segment_2_intersection.h.
The documentation for this class was generated from the following file:
Segment_2_Segment_2_intersection.h