Rocstar: Element Class Reference
Element Class Reference abstract
#include <Element.hpp>
Public Types
enum Type {
e_tet, e_hex, e_tri_cohesive, e_quad_cohesive,
e_MAX_TYPE
}
enum fType { e_tri, e_quad, e_MAX_FACE_TYPE }
enum MaterialType { e_unset_material = -1 }
Public Member Functions
Element (Type type)
~Element ()
int getID () const
void setID (int theID)
virtual int getNumNodes () const =0
Node ** getNodes ()
virtual int getNumFaces () const =0
Face ** getFaces ()
Type getElementType () const
boolean isCohesive () const
int getMaterialType () const
void setMaterialType (int mtype)
virtual void setFromNodes (Node **thenodes)
void replaceNode (Node *node, Node *new_node)
void replaceFace (Face *face, Face *new_face)
virtual void replaceFaceNode (Node *node, Node *new_node, Face *face)
virtual double getMinEdgeLength ()
Static Public Member Functions
static Element * create (int id, Type type)
static void setMesh (Mesh *emesh)
Protected Member Functions
virtual void setFromMyNodes ()=0
virtual void setFaceFromNodes (int num, Node **nodes)=0
void setFace (int num, Face *face)
Protected Attributes
Type d_eType
int d_ID
Node ** d_nodes
Face ** d_faces
int d_materialType
Static Protected Attributes
static Mesh * s_mesh = 0
Friends
istream & operator>> (istream &stream, Element &elem)
ostream & operator<< (ostream &stream, Element &elem)
Detailed Description
Definition at line 12 of file Element.hpp.
Member Enumeration Documentation
enum fType
Enumerator
e_tri
e_quad
e_MAX_FACE_TYPE
Definition at line 23 of file Element.hpp.
              {e_tri,                    //0
                           e_quad,                       //1
                           e_MAX_FACE_TYPE};
enum MaterialType
Enumerator
e_unset_material
Definition at line 29 of file Element.hpp.
                    {
          e_unset_material = -1
   };
enum Type
Enumerator
e_tet
e_hex
e_tri_cohesive
e_quad_cohesive
e_MAX_TYPE
Definition at line 15 of file Element.hpp.
             {
         e_tet,      // 0
         e_hex,      // 1
         e_tri_cohesive,  // 2
         e_quad_cohesive,  // 3
         e_MAX_TYPE
   };
Constructor & Destructor Documentation
Element (Type type)
Definition at line 17 of file Element.cpp.
                             :
 d_eType( type ),
 d_ID(-1),
 d_nodes(0),
 d_faces(0),
 d_materialType( e_unset_material )
 {}
~Element ()
Definition at line 25 of file Element.cpp.
References d_faces, and d_nodes.
                  {
   if( d_nodes ){
     delete [] d_nodes;
   }
   if( d_faces ){
     delete [] d_faces;
   }
 }
Member Function Documentation
Element * create (int id, Element::Type type) static
Definition at line 35 of file Element.cpp.
References e_hex, e_quad_cohesive, e_tet, e_tri_cohesive, and setID().
Referenced by operator>>().
{
   Element *elem;
   switch( type ){
   case e_hex:
     elem = new HexElement();
     break;
   case e_tet:
     elem = new TetElement();
     break;
   case e_tri_cohesive:
     elem = new TCoElement();
     break;
   case e_quad_cohesive:
     elem = new QCoElement();
     break;
   default:
     cerr << "BUG: Illegal element type in construction " << type << endl;
   }
   elem->setID( id );
   return elem;
 }
Element::Type getElementType () const inline
Definition at line 109 of file Element.hpp.
References d_eType.
 { return d_eType; }
Face ** getFaces () inline
Definition at line 106 of file Element.hpp.
References d_faces.
Referenced by TriFace::buildCohesive(), QuadFace::buildCohesive(), Mesh::replaceNode(), and Mesh::write_boundary().
 { return d_faces; }
int getID () const inline
Definition at line 97 of file Element.hpp.
References d_ID.
Referenced by Mesh::write_boundary().
 { return d_ID; }
int getMaterialType () const inline
Definition at line 118 of file Element.hpp.
References d_materialType.
Referenced by Mesh::addCohesive().
 { return d_materialType; }
double getMinEdgeLength () virtual
Reimplemented in TetElement.
Definition at line 173 of file Element.cpp.
{
   assert( 0 );
 }
Node ** getNodes () inline
Definition at line 103 of file Element.hpp.
References d_nodes.
 { return d_nodes; }
virtual int getNumFaces () const pure virtual
Implemented in TetElement, HexElement, QCoElement, and TCoElement.
Referenced by replaceFace(), replaceNode(), Mesh::replaceNode(), and Mesh::write_boundary().
virtual int getNumNodes () const pure virtual
Implemented in TetElement, HexElement, QCoElement, and TCoElement.
Referenced by operator<<(), operator>>(), replaceNode(), and setFromNodes().
boolean isCohesive () const inline
Definition at line 112 of file Element.hpp.
References d_eType, e_quad_cohesive, e_tri_cohesive, FALSE, and TRUE.
Referenced by Mesh::addCohesive(), Node::getSeparateElements(), and Mesh::replaceNode().
{
   return ( d_eType == e_tri_cohesive || d_eType == e_quad_cohesive
            ? TRUE
            : FALSE );
 }
void replaceFace (Face * face, Face * new_face)
Definition at line 155 of file Element.cpp.
References d_faces, getNumFaces(), and i.
Referenced by TriFace::buildCohesive().
{
   int i;
   int numf = getNumFaces();
   for( i = 0; i< numf; i++ ){
     if( d_faces[i] == face ){
       d_faces[i] = new_face;
     }
   }
 }
void replaceFaceNode (Node * node, Node * new_node, Face * face) virtual
Reimplemented in QCoElement, and TCoElement.
Definition at line 168 of file Element.cpp.
Referenced by Mesh::replaceNode().
{
   assert( 0 );
 }
void replaceNode (Node * node, Node * new_node)
Definition at line 138 of file Element.cpp.
References Node::addElement(), d_faces, d_nodes, getNumFaces(), getNumNodes(), i, Node::removeElement(), and Face::replaceNode().
Referenced by Mesh::replaceNode().
{
   int i;
   int numn = getNumNodes();
   for( i = 0; i< numn; i++ ){
     if( d_nodes[i] == node ){
       d_nodes[i] = new_node;
       node->removeElement( this );
       new_node->addElement( this );
     }
   }
   int numf = getNumFaces();
   for( i = 0; i < numf; i++ ){
     d_faces[i]->replaceNode( node, new_node );
   }
 }
void setFace (int num, Face * face) inline protected
Definition at line 127 of file Element.hpp.
References Face::addElement(), d_faces, and face.
Referenced by HexElement::setFaceFromNodes(), TetElement::setFaceFromNodes(), TCoElement::setFaceFromNodes(), and QCoElement::setFaceFromNodes().
{
   d_faces[num] = face;
   face->addElement( this );
 }
virtual void setFaceFromNodes (int num, Node ** nodes) protected pure virtual
Implemented in QCoElement, TCoElement, TetElement, and HexElement.
virtual void setFromMyNodes () protected pure virtual
Implemented in QCoElement, TCoElement, TetElement, and HexElement.
Referenced by operator>>(), and setFromNodes().
void setFromNodes (Node ** thenodes) virtual
Definition at line 59 of file Element.cpp.
References Node::addElement(), d_nodes, getNumNodes(), i, and setFromMyNodes().
Referenced by HexElement::HexElement(), QCoElement::QCoElement(), TCoElement::TCoElement(), and TetElement::TetElement().
{
   int numn = getNumNodes();
   int i;
   for( i = 0; i < numn; i++ ){
     d_nodes[i] = thenodes[i];
     d_nodes[i]->addElement( this );
   }
   setFromMyNodes();
 }
void setID (int theID) inline
Definition at line 100 of file Element.hpp.
References d_ID.
Referenced by Mesh::addElement(), create(), and Mesh::removeElement().
 { d_ID = theID; }
void setMaterialType (int mtype) inline
Definition at line 121 of file Element.hpp.
References d_materialType.
Referenced by Mesh::replaceNode().
 { d_materialType = mtype; }
void setMesh (Mesh * emesh) inline static
Definition at line 124 of file Element.hpp.
References s_mesh.
Referenced by Mesh::Mesh().
 { s_mesh =  emesh; }
Friends And Related Function Documentation
ostream& operator<< (ostream & stream, Element & elem) friend
Definition at line 91 of file Element.cpp.
{
         stream << elem.d_ID << '\t' << elem.d_eType << '\t' << elem.d_materialType;
         // write nodes out to file.
         //OK, we have to special-case the cohesive elements due to
         //the strange way that they are supposed to be output.  So,
         //the tet-cohesive element needs to have 1-2-3 as usual, but then "4" should be
         //the node that matches up with node 3, instead of node 1.  Thus, since
         //the elements are stored 1-2-3 4-5-6, with 4 matched with 1, 5 matched
         //with 2, etc., we have to output 1-2-3-6-4-5.  Similarly, for the
         //quad cohesive, we output 1-2-3-4-8-5-6-7.
         switch(elem.d_eType) {
         case 2:  //e_tri_cohesive
                 stream << '\t' << elem.d_nodes[0]->getID();
                 stream << '\t' << elem.d_nodes[1]->getID();
                 stream << '\t' << elem.d_nodes[2]->getID();
                 stream << '\t' << elem.d_nodes[5]->getID();
                 stream << '\t' << elem.d_nodes[3]->getID();
                 stream << '\t' << elem.d_nodes[4]->getID();
                 stream << endl;
                 break;
         case 3:  //e_quad_cohesive
                 stream << '\t' << elem.d_nodes[0]->getID();
                 stream << '\t' << elem.d_nodes[1]->getID();
                 stream << '\t' << elem.d_nodes[2]->getID();
                 stream << '\t' << elem.d_nodes[3]->getID();
                 stream << '\t' << elem.d_nodes[7]->getID();
                 stream << '\t' << elem.d_nodes[4]->getID();
                 stream << '\t' << elem.d_nodes[5]->getID();
                 stream << '\t' << elem.d_nodes[6]->getID();
                 stream << endl;
                 break;
         default:
                 //put out in the order it's stored in the d_nodes array.
                 //default for normal tet and brick elements.
                 int numn = elem.getNumNodes();
                 int i;
                 for( i = 0; i < numn; i++ ){
                 stream << '\t' << elem.d_nodes[i]->getID();
                 }
                 stream << endl;
         }
         return stream;
 }
istream& operator>> (istream & stream, Element & elem) friend
Definition at line 70 of file Element.cpp.
{
   // read material
   stream >> elem.d_materialType;
   // read nodes & set
   int numn = elem.getNumNodes();
   int i;
   for( i = 0; i < numn; i++ ){
     int node_id;
     stream >> node_id;
     Node *node = elem.s_mesh->getNode(node_id);
     elem.d_nodes[i] = node;
     node->addElement( &elem );
   }
   elem.setFromMyNodes();
   return stream;
 }
Member Data Documentation
Type d_eType protected
Definition at line 82 of file Element.hpp.
Referenced by getElementType(), isCohesive(), and operator<<().
Face** d_faces protected
Definition at line 87 of file Element.hpp.
Referenced by getFaces(), HexElement::HexElement(), QCoElement::QCoElement(), replaceFace(), QCoElement::replaceFaceNode(), TCoElement::replaceFaceNode(), replaceNode(), setFace(), TCoElement::TCoElement(), TetElement::TetElement(), ~Element(), HexElement::~HexElement(), QCoElement::~QCoElement(), TCoElement::~TCoElement(), and TetElement::~TetElement().
int d_ID protected
Definition at line 84 of file Element.hpp.
Referenced by getID(), operator<<(), and setID().
int d_materialType protected
Definition at line 89 of file Element.hpp.
Referenced by getMaterialType(), operator<<(), operator>>(), and setMaterialType().
Node** d_nodes protected
Definition at line 86 of file Element.hpp.
Referenced by TetElement::getMinEdgeLength(), getNodes(), HexElement::HexElement(), operator<<(), operator>>(), QCoElement::QCoElement(), TCoElement::replaceFaceNode(), QCoElement::replaceFaceNode(), replaceNode(), HexElement::setFaceFromNodes(), QCoElement::setFaceFromNodes(), HexElement::setFromMyNodes(), TetElement::setFromMyNodes(), TCoElement::setFromMyNodes(), QCoElement::setFromMyNodes(), setFromNodes(), TCoElement::TCoElement(), TetElement::TetElement(), ~Element(), HexElement::~HexElement(), QCoElement::~QCoElement(), TCoElement::~TCoElement(), and TetElement::~TetElement().
Mesh * s_mesh = 0 static protected
Definition at line 91 of file Element.hpp.
Referenced by operator>>(), HexElement::setFaceFromNodes(), TetElement::setFaceFromNodes(), QCoElement::setFaceFromNodes(), TCoElement::setFaceFromNodes(), and setMesh().
The documentation for this class was generated from the following files:
Element.hpp
Element.cpp