Rocstar: Aff_transformation_3< R_ > Class Template Reference
Aff_transformation_3< R_ > Class Template Reference
#include <Aff_transformation_3.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Plane_3_base RPlane_3
typedef
R::Aff_transformation_3_base RAff_transformation_3
Public Member Functions
Aff_transformation_3 ()
Aff_transformation_3 (const CGAL::Aff_transformation_3< R > &t)
Aff_transformation_3 (const RAff_transformation_3 &t)
Aff_transformation_3 (const Identity_transformation &tag)
Aff_transformation_3 (const Translation tag, const CGAL::Vector_3< R > &v)
Aff_transformation_3 (const Scaling tag, const RT &s, const RT &w=RT(1))
Aff_transformation_3 (const RT &m11, const RT &m12, const RT &m13, const RT &m14, const RT &m21, const RT &m22, const RT &m23, const RT &m24, const RT &m31, const RT &m32, const RT &m33, const RT &m34, const RT &w=RT(1))
Aff_transformation_3 (const RT &m11, const RT &m12, const RT &m13, const RT &m21, const RT &m22, const RT &m23, const RT &m31, const RT &m32, const RT &m33, const RT &w=RT(1))
~Aff_transformation_3 ()
CGAL::Point_3< R > transform (const CGAL::Point_3< R > &p) const
CGAL::Point_3< R > operator() (const CGAL::Point_3< R > &p) const
CGAL::Vector_3< R > transform (const CGAL::Vector_3< R > &v) const
CGAL::Vector_3< R > operator() (const CGAL::Vector_3< R > &v) const
CGAL::Direction_3< R > transform (const CGAL::Direction_3< R > &d) const
CGAL::Direction_3< R > operator() (const CGAL::Direction_3< R > &d) const
CGAL::Plane_3< R > transform (const CGAL::Plane_3< R > &pl) const
CGAL::Plane_3< R > operator() (const CGAL::Plane_3< R > &pl) const
CGAL::Aff_transformation_3< R > inverse () const
bool is_even () const
bool is_odd () const
FT cartesian (int i, int j) const
RT homogeneous (int i, int j) const
FT m (int i, int j) const
RT hm (int i, int j) const
CGAL::Aff_transformation_3< R > operator* (const CGAL::Aff_transformation_3< R > &t) const
Detailed Description
template<class R_>
class Aff_transformation_3< R_ >
Definition at line 84 of file Aff_transformation_3.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 89 of file Aff_transformation_3.h.
typedef R_ R
Definition at line 87 of file Aff_transformation_3.h.
typedef R::Aff_transformation_3_base RAff_transformation_3
Definition at line 91 of file Aff_transformation_3.h.
typedef R::Plane_3_base RPlane_3
Definition at line 90 of file Aff_transformation_3.h.
typedef R::RT RT
Definition at line 88 of file Aff_transformation_3.h.
Constructor & Destructor Documentation
Aff_transformation_3 () inline
Definition at line 94 of file Aff_transformation_3.h.
                          : RAff_transformation_3()
   {}
Aff_transformation_3 (const CGAL::Aff_transformation_3< R > & t) inline
Definition at line 98 of file Aff_transformation_3.h.
     : RAff_transformation_3(t)
   {}
Aff_transformation_3 (const RAff_transformation_3< R_ > & t) inline
Definition at line 103 of file Aff_transformation_3.h.
     : RAff_transformation_3(t)
   {}
Aff_transformation_3 (const Identity_transformation & tag) inline
Definition at line 108 of file Aff_transformation_3.h.
     : RAff_transformation_3(tag)
   {}
Aff_transformation_3 (const Translation tag, const CGAL::Vector_3< R > & v) inline
Definition at line 113 of file Aff_transformation_3.h.
     : RAff_transformation_3(tag, v)
   {}
Aff_transformation_3 (const Scaling tag, const RT & s, const RT & w = RT(1)) inline
Definition at line 119 of file Aff_transformation_3.h.
     : RAff_transformation_3(tag, s, w)
   {}
Aff_transformation_3 (const RT & m11, const RT & m12, const RT & m13, const RT & m14, const RT & m21, const RT & m22, const RT & m23, const RT & m24, const RT & m31, const RT & m32, const RT & m33, const RT & m34, const RT & w = RT(1)) inline
Definition at line 126 of file Aff_transformation_3.h.
     : RAff_transformation_3(m11, m12, m13, m14,
                             m21, m22, m23, m24,
                             m31, m32, m33, m34,
                                            w)
   {}
Aff_transformation_3 (const RT & m11, const RT & m12, const RT & m13, const RT & m21, const RT & m22, const RT & m23, const RT & m31, const RT & m32, const RT & m33, const RT & w = RT(1)) inline
Definition at line 136 of file Aff_transformation_3.h.
     : RAff_transformation_3(m11, m12, m13,
                            m21, m22, m23,
                            m31, m32, m33,
                                           w)
   {}
~Aff_transformation_3 () inline
Definition at line 147 of file Aff_transformation_3.h.
   {}
Member Function Documentation
FT cartesian (int i, int j) const inline
Definition at line 184 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::cartesian(i,j); }
RT hm (int i, int j) const inline
Definition at line 190 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::hm(i,j); }
RT homogeneous (int i, int j) const inline
Definition at line 186 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::homogeneous(i,j); }
CGAL::Aff_transformation_3<R> inverse () const inline
Definition at line 177 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::inverse(); }
bool is_even () const inline
Definition at line 179 of file Aff_transformation_3.h.
Referenced by Aff_transformation_3< R_ >::is_odd().
                         { return RAff_transformation_3::is_even(); }
bool is_odd () const inline
Definition at line 181 of file Aff_transformation_3.h.
References Aff_transformation_3< R_ >::is_even().
                         { return !is_even(); }
FT m (int i, int j) const inline
Definition at line 188 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::m(i,j); }
CGAL::Point_3<R> operator() (const CGAL::Point_3< R > & p) const inline
Definition at line 152 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::transform(p); }
CGAL::Vector_3<R> operator() (const CGAL::Vector_3< R > & v) const inline
Definition at line 156 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::transform(v); }
CGAL::Direction_3<R> operator() (const CGAL::Direction_3< R > & d) const inline
Definition at line 160 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::transform(d); }
CGAL::Plane_3<R> operator() (const CGAL::Plane_3< R > & pl) const inline
Definition at line 173 of file Aff_transformation_3.h.
References Aff_transformation_3< R_ >::transform().
                         { return transform(pl); }
CGAL::Aff_transformation_3<R> operator* (const CGAL::Aff_transformation_3< R > & t) const inline
Definition at line 194 of file Aff_transformation_3.h.
{
                           return
                           static_cast<const RAff_transformation_3&>(*this) *
                           static_cast<const RAff_transformation_3&>(t) ;
                         }
CGAL::Point_3<R> transform (const CGAL::Point_3< R > & p) const inline
Definition at line 150 of file Aff_transformation_3.h.
Referenced by Aff_transformation_3< R_ >::operator()().
                         { return RAff_transformation_3::transform(p); }
CGAL::Vector_3<R> transform (const CGAL::Vector_3< R > & v) const inline
Definition at line 154 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::transform(v); }
CGAL::Direction_3<R> transform (const CGAL::Direction_3< R > & d) const inline
Definition at line 158 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::transform(d); }
CGAL::Plane_3<R> transform (const CGAL::Plane_3< R > & pl) const inline
Definition at line 163 of file Aff_transformation_3.h.
                         { return RAff_transformation_3::transform(pl); }
The documentation for this class was generated from the following file:
Aff_transformation_3.h