Rocstar: rflu_modedgelist Module Reference
rflu_modedgelist Module Reference
Public Member Functions
subroutine, public rflu_nullifyedgelist (pRegion)
subroutine, public rflu_nullifyedge2celllist (pRegion)
subroutine, public rflu_createedgelist (pRegion)
subroutine, public rflu_createedge2celllist (pRegion)
subroutine, public rflu_buildedgelist (pRegion)
subroutine, public rflu_buildedge2celllist (pRegion)
subroutine, public rflu_destroyedgelist (pRegion)
subroutine, public rflu_destroyedge2celllist (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModEdgeList.F90,v $ $Revision: 1.13 $'
integer, dimension(edge_kind_aa:edge_kind_vv),
private ekcntr
integer, dimension(edge_kind_aa:edge_kind_vv),
private ekoffs
integer, dimension(edge_kind_aa:edge_kind_vv),
private ekstrt
integer, dimension(:,:),
allocatable, private degr
integer, dimension(:,:),
allocatable, private strt
Detailed Description
Definition at line 42 of file RFLU_ModEdgeList.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildedge2celllist (type(t_region), pointer pRegion)
Definition at line 972 of file RFLU_ModEdgeList.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modcellfaceedgeinfo::rflu_getedgekind(), and v.
Referenced by rflu_initflowsolver().
subroutine, public rflu_buildedgelist (type(t_region), pointer pRegion)
Definition at line 497 of file RFLU_ModEdgeList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), key, Mesh::GenericCell_2::nedges(), modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modhashtable::rflu_createhashtable(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modcellfaceedgeinfo::rflu_getedgekind(), rflu_modhashtable::rflu_hashbuildkey(), rflu_modhashtable::rflu_hashedge(), and v.
Referenced by rflu_initflowsolver().
subroutine, public rflu_createedge2celllist (type(t_region), pointer pRegion)
Definition at line 397 of file RFLU_ModEdgeList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyedge2celllist().
Referenced by rflu_initflowsolver().
subroutine, public rflu_createedgelist (type(t_region), pointer pRegion)
Definition at line 264 of file RFLU_ModEdgeList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyedgelist().
Referenced by rflu_initflowsolver().
subroutine, public rflu_destroyedge2celllist (type(t_region), pointer pRegion)
Definition at line 1470 of file RFLU_ModEdgeList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyedge2celllist().
Referenced by rflu_initflowsolver().
subroutine, public rflu_destroyedgelist (type(t_region), pointer pRegion)
Definition at line 1375 of file RFLU_ModEdgeList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyedgelist().
Referenced by rflu_endflowsolver().
subroutine, public rflu_nullifyedge2celllist (type(t_region), pointer pRegion)
Definition at line 180 of file RFLU_ModEdgeList.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createedge2celllist(), and rflu_destroyedge2celllist().
subroutine, public rflu_nullifyedgelist (type(t_region), pointer pRegion)
Definition at line 101 of file RFLU_ModEdgeList.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createedgelist(), and rflu_destroyedgelist().
Member Data Documentation
integer, dimension(:,:), allocatable, private degr private
Definition at line 76 of file RFLU_ModEdgeList.F90.
integer, dimension(edge_kind_aa:edge_kind_vv), private ekcntr private
Definition at line 73 of file RFLU_ModEdgeList.F90.
integer, dimension(edge_kind_aa:edge_kind_vv), private ekoffs private
Definition at line 73 of file RFLU_ModEdgeList.F90.
integer, dimension(edge_kind_aa:edge_kind_vv), private ekstrt private
Definition at line 73 of file RFLU_ModEdgeList.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModEdgeList.F90,v $ $Revision: 1.13 $' private
Definition at line 71 of file RFLU_ModEdgeList.F90.
integer, dimension(:,:), allocatable, private strt private
Definition at line 76 of file RFLU_ModEdgeList.F90.
The documentation for this module was generated from the following file:
RFLU_ModEdgeList.F90