Rocstar: rflo_modstatsboundaryconditions Module Reference
rflo_modstatsboundaryconditions Module Reference
Public Member Functions
subroutine, public rflo_statbcondcopy (region, patch, istbeg, istend, tav)
subroutine, public rflo_statbcondnegate (region, patch, istbeg, istend, tav)
subroutine, public rflo_statbcondextrap (region, patch, istbeg, istend, tav)
subroutine, public rflo_statboundaryconditionsset (regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModStatsBoundaryConditions.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 39 of file RFLO_ModStatsBoundaryConditions.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_statbcondcopy (type(t_region) region, type(t_patch) patch, integer istbeg, integer istend, real(rfreal), dimension(:,:), pointer tav)
Definition at line 88 of file RFLO_ModStatsBoundaryConditions.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_statboundaryconditionsset().
subroutine, public rflo_statbcondextrap (type(t_region) region, type(t_patch) patch, integer istbeg, integer istend, real(rfreal), dimension(:,:), pointer tav)
Definition at line 258 of file RFLO_ModStatsBoundaryConditions.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_statboundaryconditionsset().
subroutine, public rflo_statbcondnegate (type(t_region) region, type(t_patch) patch, integer istbeg, integer istend, real(rfreal), dimension(:,:), pointer tav)
Definition at line 173 of file RFLO_ModStatsBoundaryConditions.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_statboundaryconditionsset().
subroutine, public rflo_statboundaryconditionsset (type(t_region), dimension(:), pointer regions)
Definition at line 344 of file RFLO_ModStatsBoundaryConditions.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_statbcondcopy(), rflo_statbcondextrap(), and rflo_statbcondnegate().
Referenced by rflo_dualtimestepping(), and modstatsroutines::statwritemp().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModStatsBoundaryConditions.F90,v $ $Revision: 1.4 $' private
Definition at line 62 of file RFLO_ModStatsBoundaryConditions.F90.
The documentation for this module was generated from the following file:
RFLO_ModStatsBoundaryConditions.F90