Rocstar: rflu_modhllcflux Module Reference
rflu_modhllcflux Module Reference
Public Member Functions
subroutine, public rflu_hllc_computeflux (pRegion)
subroutine rflu_hllc_computeflux1_mtcp (pRegion)
subroutine rflu_hllc_computeflux1_tcp (pRegion)
subroutine rflu_hllc_computeflux2_gl (pRegion)
subroutine rflu_hllc_computeflux2_mtcp (pRegion)
subroutine rflu_hllc_computeflux2_tcp (pRegion)
Private Member Functions
subroutine rflu_hllc_computeflux1_gl (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModHLLCFlux.F90,v $ $Revision: 1.10 $'
Detailed Description
Definition at line 39 of file RFLU_ModHLLCFlux.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_hllc_computeflux (type(t_region), pointer pRegion)
Definition at line 89 of file RFLU_ModHLLCFlux.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_hllc_computeflux1_gl(), rflu_hllc_computeflux1_mtcp(), rflu_hllc_computeflux1_tcp(), rflu_hllc_computeflux2_gl(), rflu_hllc_computeflux2_mtcp(), and rflu_hllc_computeflux2_tcp().
Referenced by rflu_computefluxinv().
subroutine rflu_hllc_computeflux1_gl (type(t_region), pointer pRegion) private
Definition at line 202 of file RFLU_ModHLLCFlux.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), min(), mixtgasliq_c(), mixtliq_c2_bp(), mixtliq_d_dobpppobttto(), mixtperf_c2_grt(), mixtperf_cv_cpr(), mixtperf_d_prt(), mixtperf_r_cpg(), mixtperf_r_m(), moderror::registerfunction(), rflu_centralfirstpatch_gl(), rs(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_hllc_computeflux().
subroutine rflu_hllc_computeflux1_mtcp (type(t_region), pointer pRegion)
Definition at line 561 of file RFLU_ModHLLCFlux.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), min(), mixtperf_c_dgp(), mixtperf_c_ghovm2(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), moderror::registerfunction(), rflu_centralfirstpatch(), rs(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_hllc_computeflux().
subroutine rflu_hllc_computeflux1_tcp (type(t_region), pointer pRegion)
Definition at line 905 of file RFLU_ModHLLCFlux.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Color::g(), max(), min(), mixtperf_c_ghovm2(), moderror::registerfunction(), rflu_centralfirstpatch(), rs(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_hllc_computeflux().
subroutine rflu_hllc_computeflux2_gl (type(t_region), pointer pRegion)
Definition at line 1181 of file RFLU_ModHLLCFlux.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), max(), min(), mixtgasliq_c(), mixtgasliq_p(), mixtliq_c2_bp(), mixtliq_d_dobpppobttto(), mixtperf_c2_grt(), mixtperf_cv_cpr(), mixtperf_d_prt(), mixtperf_r_cpg(), mixtperf_r_m(), moderror::registerfunction(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch_gl(), rs(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_hllc_computeflux().
subroutine rflu_hllc_computeflux2_mtcp (type(t_region), pointer pRegion)
Definition at line 1692 of file RFLU_ModHLLCFlux.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), min(), mixtperf_c_dgp(), mixtperf_c_ghovm2(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), moderror::registerfunction(), rflu_centralfirstpatch(), rflu_centralsecondpatch(), rs(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_hllc_computeflux().
subroutine rflu_hllc_computeflux2_tcp (type(t_region), pointer pRegion)
Definition at line 2125 of file RFLU_ModHLLCFlux.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), Color::g(), max(), min(), mixtperf_c_dgp(), mixtperf_c_ghovm2(), mixtperf_eo_dgpuvw(), moderror::registerfunction(), rflu_centralfirstpatch(), rflu_centralsecondpatch(), rs(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_hllc_computeflux().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModHLLCFlux.F90,v $ $Revision: 1.10 $' private
Definition at line 59 of file RFLU_ModHLLCFlux.F90.
The documentation for this module was generated from the following file:
RFLU_ModHLLCFlux.F90