Rocstar: PointS2< FT > Class Template Reference
PointS2< FT > Class Template Reference
#include <PointS2.h>
Public Member Functions
PointS2 ()
PointS2 (const Origin &)
PointS2 (const FT &hx, const FT &hy, const FT &hw)
PointS2 (const FT &x, const FT &y)
bool operator== (const PointS2< FT > &p) const
bool operator!= (const PointS2< FT > &p) const
const FT & hx () const
const FT & hy () const
FT hw () const
const FT & x () const
const FT & y () const
FT cartesian (int i) const
FT operator[] (int i) const
FT homogeneous (int i) const
int dimension () const
Bbox_2 bbox () const
PointS2< FT > transform (const Aff_transformationS2< FT > &) const
PointS2 (const VectorS2< FT > &v)
PointS2 ()
PointS2 (const Origin &)
PointS2 (const FT &hx, const FT &hy, const FT &hw)
PointS2 (const FT &x, const FT &y)
~PointS2 ()
Self & operator= (const Self &p)
bool operator== (const Self &p) const
bool operator== (const Origin &) const
bool operator< (const Self &p) const
int id () const
FT hx () const
FT hy () const
FT hw () const
FT homogeneous (int i) const
const FT & x () const
const FT & y () const
FT & x ()
FT & y ()
const FT & cartesian (int i) const
FT & cartesian (int i)
FT & operator[] (int i)
const FT & operator[] (int i) const
int dimension () const
Self & operator+= (const Vector &v)
Self & operator-= (const Vector &v)
Bbox_2 bbox () const
Self transform (const Aff_transformation &t) const
Public Attributes
FT e0
FT e1
Private Types
typedef PointS2< FT > Self
typedef VectorS2< FT > Vector
typedef Aff_transformationS2< FT > Aff_transformation
Private Attributes
FT _x
FT _y
Detailed Description
template<class FT>
class PointS2< FT >
Definition at line 58 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
Member Typedef Documentation
typedef Aff_transformationS2<FT> Aff_transformation private
Definition at line 34 of file include/CGAL/SimpleCartesian/PointS2.h.
typedef PointS2<FT> Self private
Definition at line 32 of file include/CGAL/SimpleCartesian/PointS2.h.
typedef VectorS2<FT> Vector private
Definition at line 33 of file include/CGAL/SimpleCartesian/PointS2.h.
Constructor & Destructor Documentation
PointS2 () inline
Definition at line 61 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
 {}
PointS2 (const Origin &) inline
Definition at line 62 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
 : e0(FT(0)), e1(FT(0)) {}
CGAL_KERNEL_CTOR_INLINE PointS2 (const FT & hx, const FT & hy, const FT & hw)
Definition at line 109 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
 {
   if( hw != FT(1))
   { e0 = hx/hw; e1 = hy/hw; }
   else
   { e0 = hx; e1 = hy; }
 }
CGAL_KERNEL_CTOR_INLINE PointS2 (const FT & x, const FT & y)
Definition at line 119 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
References x, and y.
 { e0 = x; e1 = y; }
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE CGAL_KERNEL_CTOR_INLINE PointS2 (const VectorS2< FT > & v)
Definition at line 104 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
References VectorS2< FT >::e0, and VectorS2< FT >::e1.
 { e0 = v.e0; e1 = v.e1; }
PointS2 () inline
Definition at line 36 of file include/CGAL/SimpleCartesian/PointS2.h.
 {}
PointS2 (const Origin &) inline
Definition at line 38 of file include/CGAL/SimpleCartesian/PointS2.h.
 : _x(0), _y(0) {}
PointS2 (const FT & hx, const FT & hy, const FT & hw) inline
Definition at line 39 of file include/CGAL/SimpleCartesian/PointS2.h.
 : _x(hx/hw), _y(hy/hw) {}
PointS2 (const FT & x, const FT & y) inline
Definition at line 40 of file include/CGAL/SimpleCartesian/PointS2.h.
 : _x(x), _y(y) {}
~PointS2 () inline
Definition at line 41 of file include/CGAL/SimpleCartesian/PointS2.h.
 {}
Member Function Documentation
CGAL_KERNEL_INLINE Bbox_2 bbox () const
Definition at line 245 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
References by, to_double(), x, and y.
 {
   double bx = CGAL::to_double(x());
   double by = CGAL::to_double(y());
   return Bbox_2(bx,by, bx,by);
 }
Bbox_2 bbox () const inline
Definition at line 86 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 { return Bbox_2(x(),y(),x(),y()); }
const FT& cartesian (int i) const inline
Definition at line 62 of file include/CGAL/SimpleCartesian/PointS2.h.
References CGAL_kernel_precondition, PointS2< FT >::x(), and PointS2< FT >::y().
{
     CGAL_kernel_precondition( (i == 0) || (i == 1) );
     return (i == 0) ? x() : y();
   }
FT& cartesian (int i) inline
Definition at line 67 of file include/CGAL/SimpleCartesian/PointS2.h.
References CGAL_kernel_precondition, PointS2< FT >::x(), and PointS2< FT >::y().
{
     CGAL_kernel_precondition( (i == 0) || (i == 1) );
     return (i == 0) ? x() : y();
   }
CGAL_KERNEL_INLINE FT cartesian (int i) const
Definition at line 149 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
References CGAL_kernel_precondition, x, and y.
Referenced by PointS2< FT >::homogeneous(), and PointS2< FT >::operator[]().
 {
   CGAL_kernel_precondition( (i == 0) || (i == 1) );
   return (i == 0) ? x() : y();
 }
int dimension () const inline
Definition at line 75 of file include/CGAL/SimpleCartesian/PointS2.h.
 { return 2; }
int dimension () const inline
Definition at line 164 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
 { return 2; }
FT homogeneous (int i) const inline
Definition at line 55 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::cartesian().
 { return (i == 2) ? FT(1) : cartesian(i); }
FT homogeneous (int i) const inline
Definition at line 188 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
References CGAL_kernel_precondition.
 {
   CGAL_kernel_precondition( (i>=0) && (i<=2) );
   if (i<2) return cartesian(i);
   return FT(1);
 }
FT hw () const inline
Definition at line 54 of file include/CGAL/SimpleCartesian/PointS2.h.
 { return FT(1); }
FT hw () const inline
Definition at line 182 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
 { return FT(1); }
FT hx () const inline
Definition at line 52 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::x().
 { return x(); }
const FT & hx () const inline
Definition at line 170 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
 { return e0; }
FT hy () const inline
Definition at line 53 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::y().
 { return y(); }
const FT & hy () const inline
Definition at line 176 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
 { return e1; }
int id () const inline
Definition at line 50 of file include/CGAL/SimpleCartesian/PointS2.h.
 { return (int)this; }
bool operator!= (const PointS2< FT > & p) const inline
Definition at line 131 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
 { return !(*this == p); }
Self& operator+= (const Vector & v) inline
Definition at line 77 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::_x, PointS2< FT >::_y, VectorS2< FT >::x(), and VectorS2< FT >::y().
{
     _x += v.x(); _y+=v.y();
     return *this;
   }
Self& operator-= (const Vector & v) inline
Definition at line 81 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::_x, PointS2< FT >::_y, VectorS2< FT >::x(), and VectorS2< FT >::y().
{
     _x -= v.x(); _y-=v.y();
     return *this;
   }
bool operator< (const Self & p) const inline
Definition at line 47 of file include/CGAL/SimpleCartesian/PointS2.h.
References lexicographically_xy_smaller().
     { return lexicographically_xy_smaller(*this, p); }
Self& operator= (const Self & p) inline
Definition at line 43 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::_x, and PointS2< FT >::_y.
 { _x = p._x; _y = p._y; return *this; }
bool operator== (const Self & p) const inline
Definition at line 45 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 { return x()==p.x() && y()==p.y(); }
bool operator== (const Origin &) const inline
Definition at line 46 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 { return x()==FT(0) && y()==FT(0); }
bool operator== (const PointS2< FT > & p) const inline
Definition at line 125 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::x(), x, PointS2< FT >::y(), and y.
 { return ((x() == p.x()) && (y() == p.y())) ; }
FT& operator[] (int i) inline
Definition at line 72 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::cartesian().
 { return cartesian(i); }
const FT& operator[] (int i) const inline
Definition at line 73 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::cartesian().
 { return cartesian(i); }
FT operator[] (int i) const inline
Definition at line 158 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
 { return cartesian(i); }
CGAL_KERNEL_INLINE PointS2< FT > transform (const Aff_transformationS2< FT > & t) const
Definition at line 239 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
References Aff_transformationS2< FT >::transform().
 { return t.transform(*this); }
Self transform (const Aff_transformation & t) const inline
Definition at line 88 of file include/CGAL/SimpleCartesian/PointS2.h.
References Aff_transformationS2< FT >::transform().
     { return t.transform(*this); }
const FT& x () const inline
Definition at line 57 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::_x.
 { return _x; }
FT& x () inline
Definition at line 59 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::_x.
 { return _x; }
const FT & x () const inline
Definition at line 137 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
Referenced by PointS2< FT >::bbox(), PointS2< FT >::cartesian(), collinear_are_ordered_along_line(), collinear_are_strictly_ordered_along_line(), SegmentS2< FT >::collinear_has_on(), compare_deltax_deltay(), compare_lexicographically_xy(), compare_lexicographically_yx(), compare_x(), equal_xy(), Data_accessorS2< FT_ >::get_x(), LineS2< FT >::has_on_boundary(), LineS2< FT >::has_on_negative_side(), LineS2< FT >::has_on_positive_side(), PointS2< FT >::hx(), leftturn(), less_x(), LineS2< FT >::LineS2(), LineS2< FT >::new_rep(), operator+(), operator-(), PointS2< FT >::operator==(), orientation(), LineS2< FT >::oriented_side(), LineS2< FT >::perpendicular(), LineS2< FT >::projection(), rightturn(), side_of_bounded_circle(), side_of_oriented_circle(), PlaneS3< FT >::to_3d(), Aff_transformation_repS2< FT >::transform(), Rotation_repS2< FT >::transform(), Scaling_repS2< FT >::transform(), and x_equal().
 { return e0; }
const FT& y () const inline
Definition at line 58 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::_y.
 { return _y; }
FT& y () inline
Definition at line 60 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::_y.
 { return _y; }
const FT & y () const inline
Definition at line 143 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
Referenced by PointS2< FT >::bbox(), PointS2< FT >::cartesian(), collinear_are_ordered_along_line(), collinear_are_strictly_ordered_along_line(), SegmentS2< FT >::collinear_has_on(), compare_deltax_deltay(), compare_lexicographically_xy(), compare_lexicographically_yx(), compare_y(), equal_xy(), Data_accessorS2< FT_ >::get_y(), LineS2< FT >::has_on_boundary(), LineS2< FT >::has_on_negative_side(), LineS2< FT >::has_on_positive_side(), PointS2< FT >::hy(), leftturn(), less_y(), LineS2< FT >::LineS2(), LineS2< FT >::new_rep(), operator+(), operator-(), PointS2< FT >::operator==(), orientation(), LineS2< FT >::oriented_side(), LineS2< FT >::perpendicular(), LineS2< FT >::projection(), rightturn(), side_of_bounded_circle(), side_of_oriented_circle(), PlaneS3< FT >::to_3d(), Aff_transformation_repS2< FT >::transform(), Rotation_repS2< FT >::transform(), Scaling_repS2< FT >::transform(), and y_equal().
 { return  e1 ; }
Member Data Documentation
FT _x private
Definition at line 92 of file include/CGAL/SimpleCartesian/PointS2.h.
Referenced by PointS2< FT >::operator+=(), PointS2< FT >::operator-=(), PointS2< FT >::operator=(), and PointS2< FT >::x().
FT _y private
Definition at line 92 of file include/CGAL/SimpleCartesian/PointS2.h.
Referenced by PointS2< FT >::operator+=(), PointS2< FT >::operator-=(), PointS2< FT >::operator=(), and PointS2< FT >::y().
FT e0
Definition at line 87 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
Referenced by VectorS2< FT >::VectorS2().
FT e1
Definition at line 88 of file CGAL/include/CGAL/SimpleCartesian/PointS2.h.
Referenced by VectorS2< FT >::VectorS2().
The documentation for this class was generated from the following file:
CGAL/include/CGAL/SimpleCartesian/PointS2.h