Rocstar: FileTokenizer Class Reference
FileTokenizer Class Reference
Parse a file as space-separated tokens.
#include <FileTokenizer.hpp>
Public Member Functions
FileTokenizer (msq_stdc::FILE *file_ptr)
constructor
~FileTokenizer ()
destructor : closes file.
const char * get_string (MsqError &err)
get next token
bool get_newline (MsqError &err)
check for newline
bool get_doubles (size_t count, double *array, MsqError &err)
Parse a sequence of double values.
bool get_floats (size_t count, float *array, MsqError &err)
Parse a sequence of float values.
bool get_integers (size_t count, int *array, MsqError &err)
Parse a sequence of integer values.
bool get_long_ints (size_t count, long *array, MsqError &err)
Parse a sequence of integer values.
bool get_short_ints (size_t count, short *array, MsqError &err)
Parse a sequence of integer values.
bool get_bytes (size_t count, unsigned char *array, MsqError &err)
Parse a sequence of integer values.
bool get_booleans (size_t count, bool *array, MsqError &err)
Parse a sequence of bit or boolean values.
bool eof () const
Check for end-of-file condition.
int line_number () const
Get the line number the last token was read from.
void unget_token ()
Put current token back in buffer.
bool match_token (const char *string, MsqError &err)
Match current token to passed string.
int match_token (const char *const *string_list, MsqError &err)
Match the current token to one of an array of strings.
FileTokenizer (msq_stdc::FILE *file_ptr)
constructor
~FileTokenizer ()
destructor : closes file.
const char * get_string (MsqError &err)
get next token
bool get_newline (MsqError &err)
check for newline
bool get_doubles (size_t count, double *array, MsqError &err)
Parse a sequence of double values.
bool get_floats (size_t count, float *array, MsqError &err)
Parse a sequence of float values.
bool get_integers (size_t count, int *array, MsqError &err)
Parse a sequence of integer values.
bool get_long_ints (size_t count, long *array, MsqError &err)
Parse a sequence of integer values.
bool get_short_ints (size_t count, short *array, MsqError &err)
Parse a sequence of integer values.
bool get_bytes (size_t count, unsigned char *array, MsqError &err)
Parse a sequence of integer values.
bool get_booleans (size_t count, bool *array, MsqError &err)
Parse a sequence of bit or boolean values.
bool eof () const
Check for end-of-file condition.
int line_number () const
Get the line number the last token was read from.
void unget_token ()
Put current token back in buffer.
bool match_token (const char *string, MsqError &err)
Match current token to passed string.
int match_token (const char *const *string_list, MsqError &err)
Match the current token to one of an array of strings.
Private Member Functions
bool get_double_internal (double &result, MsqError &err)
Internal implementation of get_doubles.
bool get_long_int_internal (long &result, MsqError &err)
Internal implementation of get_long_ints.
bool get_boolean_internal (bool &result, MsqError &err)
Internal implementation of get_Booleans.
bool get_float_internal (float &result, MsqError &err)
Internal implementation of get_floats.
bool get_integer_internal (int &result, MsqError &err)
Internal implementation of get_integers.
bool get_short_int_internal (short &result, MsqError &err)
Internal implementation of get_short_ints.
bool get_byte_internal (unsigned char &result, MsqError &err)
Internal implementation of get_bytes.
bool get_double_internal (double &result, MsqError &err)
Internal implementation of get_doubles.
bool get_long_int_internal (long &result, MsqError &err)
Internal implementation of get_long_ints.
bool get_boolean_internal (bool &result, MsqError &err)
Internal implementation of get_Booleans.
bool get_float_internal (float &result, MsqError &err)
Internal implementation of get_floats.
bool get_integer_internal (int &result, MsqError &err)
Internal implementation of get_integers.
bool get_short_int_internal (short &result, MsqError &err)
Internal implementation of get_short_ints.
bool get_byte_internal (unsigned char &result, MsqError &err)
Internal implementation of get_bytes.
Private Attributes
msq_stdc::FILE * filePtr
Pointer to standard C FILE struct.
char buffer [512]
Input buffer.
char * nextToken
One past the end of the last token returned.
char * bufferEnd
One past the last used byte of the buffer.
int lineNumber
Line number of last returned token.
char lastChar
The whitespace character marking the end of the last returned token.
Detailed Description
Parse a file as space-separated tokens.
Author
Jason Kraftcheck
Date
30 Sept 2004
Read a file, separating it into space-separated tokens. This is provided in place of using the standard C or C++ file parsing routines because it counts lines, which is useful for error reporting. Also provides some useful utility methods for parsing VTK files (which is the intended use of this implementation.)
Uses raw reads/writes, implementing internal buffering. Token size may not exceed buffer size.
Definition at line 60 of file includeLinks/FileTokenizer.hpp.
Constructor & Destructor Documentation
FileTokenizer (msq_stdc::FILE * file_ptr)
constructor
Parameters
file_ptr The file to read from.
~FileTokenizer ()
destructor : closes file.
The destructor closes the passed file handle. This is done as a convenience feature. If the caller creates an instance of this object on the stack, the file will automatically be closed when the caller returns.
Definition at line 50 of file Misc/FileTokenizer.cpp.
References cimg_library::cimg::fclose().
   { fclose( filePtr ); }
FileTokenizer (msq_stdc::FILE * file_ptr)
constructor
Parameters
file_ptr The file to read from.
~FileTokenizer ()
destructor : closes file.
The destructor closes the passed file handle. This is done as a convenience feature. If the caller creates an instance of this object on the stack, the file will automatically be closed when the caller returns.
Member Function Documentation
bool eof () const
Check for end-of-file condition.
Definition at line 53 of file Misc/FileTokenizer.cpp.
Referenced by MeshImpl::read_vtk().
   { return nextToken == bufferEnd && feof(filePtr); }
bool eof () const
Check for end-of-file condition.
bool get_boolean_internal (bool & result, MsqError & err) private
Internal implementation of get_Booleans.
Definition at line 272 of file Misc/FileTokenizer.cpp.
References MSQ_CHKERR, and MSQ_SETERR.
 {
     // Get a token
   const char *token = get_string( err );
   if (MSQ_CHKERR(err))
     return false;
   if (token[1] || (token[0] != '0' && token[0] != '1'))
   {
     MSQ_SETERR(err)( MsqError::PARSE_ERROR,
       "Syntax error at line %d: expected 0 or 1, got \"%s\"",
       line_number(), token );
     return false;
   }
   result = token[0] == '1';
   return true;
 }
bool get_boolean_internal (bool & result, MsqError & err) private
Internal implementation of get_Booleans.
bool get_booleans (size_t count, bool * array, MsqError & err)
Parse a sequence of bit or boolean values.
Read the specified number of space-deliminated values.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
Definition at line 363 of file Misc/FileTokenizer.cpp.
References i, and MSQ_CHKERR.
Referenced by MeshImpl::vtk_read_typed_data().
 {
   for (size_t i = 0; i < count; ++i)
   {
     get_boolean_internal( *array, err );
     if (MSQ_CHKERR(err))
       return false;
     ++array;
   }
   return true;
 }
bool get_booleans (size_t count, bool * array, MsqError & err)
Parse a sequence of bit or boolean values.
Read the specified number of space-deliminated values.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
bool get_byte_internal (unsigned char & result, MsqError & err) private
Internal implementation of get_bytes.
Definition at line 221 of file Misc/FileTokenizer.cpp.
References i, MSQ_CHKERR, and MSQ_SETERR.
 {
   long i;
   get_long_int_internal( i, err );
   if (MSQ_CHKERR(err))
     return false;
   result = (unsigned char)i;
   if (i != (long)result)
   {
     MSQ_SETERR(err)( MsqError::PARSE_ERROR, "Numberic overflow at line %d.", line_number() );
     return false;
   }
   return true;
 }
bool get_byte_internal (unsigned char & result, MsqError & err) private
Internal implementation of get_bytes.
bool get_bytes (size_t count, unsigned char * array, MsqError & err)
Parse a sequence of integer values.
Read the specified number of space-deliminated ints.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
Definition at line 314 of file Misc/FileTokenizer.cpp.
References i, and MSQ_CHKERR.
 {
   for (size_t i = 0; i < count; ++i)
   {
     get_byte_internal( *array, err );
     if (MSQ_CHKERR(err))
       return false;
     ++array;
   }
   return true;
 }
bool get_bytes (size_t count, unsigned char * array, MsqError & err)
Parse a sequence of integer values.
Read the specified number of space-deliminated ints.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
bool get_double_internal (double & result, MsqError & err) private
Internal implementation of get_doubles.
bool get_double_internal (double & result, MsqError & err) private
Internal implementation of get_doubles.
Definition at line 144 of file Misc/FileTokenizer.cpp.
References MSQ_CHKERR, and MSQ_SETERR.
 {
     // Get a token
   const char *token_end, *token = get_string( err );
   if (MSQ_CHKERR(err))
     return false;
     // Check for hex value -- on some platforms (e.g. Linux), strtod
     // will accept hex values, on others (e.g. Sun) it wil not.  Force
     // failure on hex numbers for consistancy.
   if (token[0] && token[1] && token[0] == '0' && toupper(token[1]) == 'X')
   {
     MSQ_SETERR(err)( MsqError::PARSE_ERROR,
       "Syntax error at line %d: expected number, got \"%s\"",
       line_number(), token );
     return false;
   }
     // Parse token as double
   result = strtod( token, (char**)&token_end );
     // If the one past the last char read by strtod is
     // not the NULL character terminating the string,
     // then parse failed.
   if (*token_end)
   {
     MSQ_SETERR(err)( MsqError::PARSE_ERROR,
       "Syntax error at line %d: expected number, got \"%s\"",
       line_number(), token );
     return false;
   }
   return true;
 }
bool get_doubles (size_t count, double * array, MsqError & err)
Parse a sequence of double values.
Read the specified number of space-deliminated doubles.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
Definition at line 302 of file Misc/FileTokenizer.cpp.
References i, and MSQ_CHKERR.
Referenced by MeshImpl::vtk_read_field(), MeshImpl::vtk_read_polydata(), MeshImpl::vtk_read_rectilinear_grid(), MeshImpl::vtk_read_scalar_attrib(), MeshImpl::vtk_read_structured_grid(), MeshImpl::vtk_read_structured_points(), MeshImpl::vtk_read_typed_data(), and MeshImpl::vtk_read_unstructured_grid().
 {
   for (size_t i = 0; i < count; ++i)
   {
     get_double_internal( *array, err );
     if (MSQ_CHKERR(err))
       return false;
     ++array;
   }
   return true;
 }
bool get_doubles (size_t count, double * array, MsqError & err)
Parse a sequence of double values.
Read the specified number of space-deliminated doubles.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
bool get_float_internal (float & result, MsqError & err) private
Internal implementation of get_floats.
Definition at line 180 of file Misc/FileTokenizer.cpp.
References MSQ_CHKERR, and MSQ_SETERR.
 {
   double d;
   get_double_internal( d, err );
   if (MSQ_CHKERR(err))
     return false;
   result = (float)d;
   if (d != (double)result)
   {
     MSQ_SETERR(err)( MsqError::PARSE_ERROR, "Numberic overflow at line %d.", line_number() );
     return false;
   }
   return true;
 }
bool get_float_internal (float & result, MsqError & err) private
Internal implementation of get_floats.
bool get_floats (size_t count, float * array, MsqError & err)
Parse a sequence of float values.
Read the specified number of space-deliminated doubles.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
Definition at line 291 of file Misc/FileTokenizer.cpp.
References i.
Referenced by MeshImpl::vtk_read_color_attrib(), and MeshImpl::vtk_read_scalar_attrib().
 {
   for (size_t i = 0; i < count; ++i)
   {
     if (!get_float_internal( *array, err ))
       return false;
     ++array;
   }
   return true;
 }
bool get_floats (size_t count, float * array, MsqError & err)
Parse a sequence of float values.
Read the specified number of space-deliminated doubles.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
bool get_integer_internal (int & result, MsqError & err) private
Internal implementation of get_integers.
bool get_integer_internal (int & result, MsqError & err) private
Internal implementation of get_integers.
Definition at line 255 of file Misc/FileTokenizer.cpp.
References i, MSQ_CHKERR, and MSQ_SETERR.
 {
   long i;
   get_long_int_internal( i, err );
   if (MSQ_CHKERR(err))
     return false;
   result = (int)i;
   if (i != (long)result)
   {
     MSQ_SETERR(err)( MsqError::PARSE_ERROR, "Numberic overflow at line %d.", line_number() );
     return false;
   }
   return true;
 }
bool get_integers (size_t count, int * array, MsqError & err)
Parse a sequence of integer values.
Read the specified number of space-deliminated ints.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
bool get_integers (size_t count, int * array, MsqError & err)
Parse a sequence of integer values.
Read the specified number of space-deliminated ints.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
Definition at line 339 of file Misc/FileTokenizer.cpp.
References i, and MSQ_CHKERR.
Referenced by MeshImpl::vtk_read_texture_attrib(), and MeshImpl::vtk_read_typed_data().
 {
   for (size_t i = 0; i < count; ++i)
   {
     get_integer_internal( *array, err );
     if (MSQ_CHKERR(err))
       return false;
     ++array;
   }
   return true;
 }
bool get_long_int_internal (long & result, MsqError & err) private
Internal implementation of get_long_ints.
Definition at line 197 of file Misc/FileTokenizer.cpp.
References MSQ_CHKERR, and MSQ_SETERR.
 {
     // Get a token
   const char *token_end, *token = get_string( err );
   if (MSQ_CHKERR(err))
     return false;
     // Parse token as long
   result = strtol( token, (char**)&token_end, 0 );
     // If the one past the last char read by strtol is
     // not the NULL character terminating the string,
     // then parse failed.
   if (*token_end)
   {
     MSQ_SETERR(err)( MsqError::PARSE_ERROR,
       "Syntax error at line %d: expected integer, got \"%s\"",
       line_number(), token );
     return false;
   }
   return true;
 }
bool get_long_int_internal (long & result, MsqError & err) private
Internal implementation of get_long_ints.
bool get_long_ints (size_t count, long * array, MsqError & err)
Parse a sequence of integer values.
Read the specified number of space-deliminated ints.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
bool get_long_ints (size_t count, long * array, MsqError & err)
Parse a sequence of integer values.
Read the specified number of space-deliminated ints.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
Definition at line 351 of file Misc/FileTokenizer.cpp.
References i, and MSQ_CHKERR.
Referenced by MeshImpl::read_vtk(), MeshImpl::vtk_read_color_attrib(), MeshImpl::vtk_read_field(), MeshImpl::vtk_read_polydata(), MeshImpl::vtk_read_polygons(), MeshImpl::vtk_read_rectilinear_grid(), MeshImpl::vtk_read_scalar_attrib(), MeshImpl::vtk_read_structured_grid(), MeshImpl::vtk_read_structured_points(), and MeshImpl::vtk_read_unstructured_grid().
 {
   for (size_t i = 0; i < count; ++i)
   {
     get_long_int_internal( *array, err );
     if (MSQ_CHKERR(err))
       return false;
     ++array;
   }
   return true;
 }
bool get_newline (MsqError & err)
check for newline
Consume whitespace upto and including the next newline. If a non-space character is found before a newline, the function will stop, set the error message, and return false.
Returns
True if a newline was found before any non-space character. False otherwise.
bool get_newline (MsqError & err)
check for newline
Consume whitespace upto and including the next newline. If a non-space character is found before a newline, the function will stop, set the error message, and return false.
Returns
True if a newline was found before any non-space character. False otherwise.
Definition at line 442 of file Misc/FileTokenizer.cpp.
References cimg_library::cimg::fread(), and MSQ_SETERR.
Referenced by MeshImpl::vtk_read_polydata(), MeshImpl::vtk_read_polygons(), MeshImpl::vtk_read_rectilinear_grid(), MeshImpl::vtk_read_structured_grid(), MeshImpl::vtk_read_structured_points(), and MeshImpl::vtk_read_unstructured_grid().
 {
   if (lastChar == '\n')
   {
     lastChar = ' ';
     ++lineNumber;
     return true;
   }
     // Loop until either we a) find a newline, b) find a non-whitespace
     // character or c) reach the end of the file.
   for (;;)
   {
       // If the buffer is empty, read more.
     if (nextToken == bufferEnd)
     {
       size_t count = fread( buffer, 1, sizeof(buffer), filePtr );
       if (!count)
       {
         if (eof())
           MSQ_SETERR(err)( "File truncated.", MsqError::PARSE_ERROR );
         else
           MSQ_SETERR(err)( MsqError::IO_ERROR );
         return false;
       }
       nextToken = buffer;
       bufferEnd = buffer + count;
     }
       // If the current character is not a space, the we've failed.
     if (!isspace(*nextToken))
     {
       MSQ_SETERR(err)( MsqError::PARSE_ERROR, "Expected newline at line %d.", line_number() );
       return false;
     }
       // If the current space character is a newline,
       // increment the line number count.
     if (*nextToken == '\n')
     {
       ++lineNumber;
       ++nextToken;
       lastChar = ' ';
       return true;
     }
     ++nextToken;
   }
     // should never reach this
   return false;
 }
bool get_short_int_internal (short & result, MsqError & err) private
Internal implementation of get_short_ints.
Definition at line 238 of file Misc/FileTokenizer.cpp.
References i, MSQ_CHKERR, and MSQ_SETERR.
 {
   long i;
   get_long_int_internal( i, err );
   if (MSQ_CHKERR(err))
     return false;
   result = (short)i;
   if (i != (long)result)
   {
     MSQ_SETERR(err)( MsqError::PARSE_ERROR, "Numberic overflow at line %d.", line_number() );
     return false;
   }
   return true;
 }
bool get_short_int_internal (short & result, MsqError & err) private
Internal implementation of get_short_ints.
bool get_short_ints (size_t count, short * array, MsqError & err)
Parse a sequence of integer values.
Read the specified number of space-deliminated ints.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
bool get_short_ints (size_t count, short * array, MsqError & err)
Parse a sequence of integer values.
Read the specified number of space-deliminated ints.
Parameters
count The number of values to read.
array The memory at which to store the values.
Returns
true if successful, false otherwise.
Definition at line 326 of file Misc/FileTokenizer.cpp.
References i, and MSQ_CHKERR.
 {
   for (size_t i = 0; i < count; ++i)
   {
     get_short_int_internal( *array, err );
     if (MSQ_CHKERR(err))
       return false;
     ++array;
   }
   return true;
 }
const char * get_string (MsqError & err)
get next token
Get the next whitesapce-deliminated token from the file. NOTE: The returned string is only valid until the next call to any of the functions in this class that read from the file.
Returns
A pointer to the buffer space containing the string, or NULL if an error occured.
Definition at line 56 of file Misc/FileTokenizer.cpp.
References cimg_library::cimg::fread(), and MSQ_SETERR.
Referenced by MeshImpl::vtk_read_attrib_data(), MeshImpl::vtk_read_field(), and MeshImpl::vtk_read_scalar_attrib().
 {
     // If the whitepsace character marking the end of the
     // last token was a newline, increment the line count.
   if (lastChar == '\n')
     ++lineNumber;
     // Loop until either found the start of a token to return or have
     // reached the end of the file.
   for (;;)
   {
       // If the buffer is empty, read more.
     if (nextToken == bufferEnd)
     {
       size_t count = fread( buffer, 1, sizeof(buffer) - 1, filePtr );
       if (!count)
       {
         if (feof(filePtr))
           MSQ_SETERR(err)( "File truncated.\n", MsqError::PARSE_ERROR );
         else
           MSQ_SETERR(err)( MsqError::IO_ERROR );
         return NULL;
       }
       nextToken = buffer;
       bufferEnd = buffer + count;
     }
       // If the current character is not a space, we've found a token.
     if (!isspace(*nextToken))
       break;
       // If the current space character is a newline,
       // increment the line number count.
     if (*nextToken == '\n')
       ++lineNumber;
     ++nextToken;
   }
     // Store the start of the token in "result" and
     // advance "nextToken" to one past the end of the
     // token.
   char* result = nextToken;
   while (nextToken != bufferEnd && !isspace(*nextToken))
     ++nextToken;
     // If we have reached the end of the buffer without finding
     // a whitespace character terminating the token, we need to
     // read more from the file.  Only try once.  If the token is
     // too large to fit in the buffer, give up.
   if (nextToken == bufferEnd)
   {
       // Shift the (possibly) partial token to the start of the buffer.
     size_t remaining = bufferEnd - result;
     memmove( buffer, result, remaining );
     result = buffer;
     nextToken =  result + remaining;
       // Fill the remainder of the buffer after the token.
     size_t count = fread( nextToken, 1, sizeof(buffer) - remaining - 1, filePtr );
     if (!count && !feof(filePtr))
     {
       MSQ_SETERR(err)( "I/O error.\n", MsqError::IO_ERROR );
       return NULL;
     }
     bufferEnd = nextToken + count;
       // Continue to advance nextToken until we find the space
       // terminating the token.
     while (nextToken != bufferEnd && !isspace(*nextToken))
       ++nextToken;
     if (nextToken == bufferEnd) // EOF
     {
       *bufferEnd = '\0';
       ++bufferEnd;
     }
   }
     // Save terminating whitespace character (or NULL char if EOF).
   lastChar = *nextToken;
     // Put null in buffer to mark end of current token.
   *nextToken = '\0';
     // Advance nextToken to the next character to search next time.
   ++nextToken;
   return result;
 }
const char* get_string (MsqError & err)
get next token
Get the next whitesapce-deliminated token from the file. NOTE: The returned string is only valid until the next call to any of the functions in this class that read from the file.
Returns
A pointer to the buffer space containing the string, or NULL if an error occured.
int line_number () const inline
Get the line number the last token was read from.
Definition at line 184 of file src/Misc/FileTokenizer.hpp.
References FileTokenizer::lineNumber.
 { return lineNumber; }
int line_number () const inline
Get the line number the last token was read from.
Definition at line 184 of file includeLinks/FileTokenizer.hpp.
References FileTokenizer::lineNumber.
Referenced by MeshImpl::read_vtk(), MeshImpl::vtk_read_attrib_data(), MeshImpl::vtk_read_cell_data(), MeshImpl::vtk_read_color_attrib(), MeshImpl::vtk_read_point_data(), MeshImpl::vtk_read_polydata(), MeshImpl::vtk_read_rectilinear_grid(), MeshImpl::vtk_read_scalar_attrib(), MeshImpl::vtk_read_structured_grid(), MeshImpl::vtk_read_structured_points(), MeshImpl::vtk_read_texture_attrib(), and MeshImpl::vtk_read_unstructured_grid().
 { return lineNumber; }
bool match_token (const char * string, MsqError & err)
Match current token to passed string.
If token doesn't match, set error message.
bool match_token (const char * string, MsqError & err)
Match current token to passed string.
If token doesn't match, set error message.
Definition at line 392 of file Misc/FileTokenizer.cpp.
References MSQ_CHKERR, and MSQ_SETERR.
Referenced by MeshImpl::read_vtk(), MeshImpl::vtk_read_attrib_data(), MeshImpl::vtk_read_dataset(), MeshImpl::vtk_read_field(), MeshImpl::vtk_read_polydata(), MeshImpl::vtk_read_rectilinear_grid(), MeshImpl::vtk_read_scalar_attrib(), MeshImpl::vtk_read_structured_grid(), MeshImpl::vtk_read_structured_points(), MeshImpl::vtk_read_tensor_attrib(), MeshImpl::vtk_read_texture_attrib(), MeshImpl::vtk_read_unstructured_grid(), and MeshImpl::vtk_read_vector_attrib().
 {
     // Get a token
   const char *token = get_string( err );
   if (MSQ_CHKERR(err))
     return false;
     // Check if it matches
   if (0 == strcmp( token, str ))
     return true;
     // Construct error message
   MSQ_SETERR(err)( MsqError::PARSE_ERROR,
     "Syntax error at line %d: expected \"%s\", got \"%s\"",
     line_number(), str, token );
   return false;
 }  // namespace Mesquite
int match_token (const char *const * string_list, MsqError & err)
Match the current token to one of an array of strings.
Sets the error message if the current token doesn't match any of the input strings.
Parameters
string_list A NULL-terminated array of strings.
Returns
One greater than the index of the matched string, or zero if no match.
int match_token (const char *const * string_list, MsqError & err)
Match the current token to one of an array of strings.
Sets the error message if the current token doesn't match any of the input strings.
Parameters
string_list A NULL-terminated array of strings.
Returns
One greater than the index of the matched string, or zero if no match.
Definition at line 411 of file Misc/FileTokenizer.cpp.
References MSQ_CHKERR, and MSQ_SETERR.
 {
     // Get a token
   const char *token = get_string( err );
   if (MSQ_CHKERR(err))
     return false;
     // Check if it matches any input string
   const char* const* ptr;
   for (ptr = list; *ptr; ++ptr)
     if (0 == strcmp( token, *ptr ))
       return ptr - list + 1;
     // No match, constuct error message
   msq_std::string message( "Parsing error at line " );
   char lineno[16];
   sprintf( lineno, "%d", line_number() );
   message += lineno;
   message += ": expected one of {";
   for (ptr = list; *ptr; ++ptr)
   {
     message += " ";
     message += *ptr;
   }
   message += " } got \"";
   message += token;
   message += "\"";
   MSQ_SETERR(err)( message, MsqError::PARSE_ERROR );
   return false;
 }
void unget_token ()
Put current token back in buffer.
Can only unget one token.
void unget_token ()
Put current token back in buffer.
Can only unget one token.
Definition at line 375 of file Misc/FileTokenizer.cpp.
Referenced by MeshImpl::read_vtk(), and MeshImpl::vtk_read_scalar_attrib().
 {
   if (nextToken - buffer < 2)
     return;
   --nextToken;
   *nextToken = lastChar;
   --nextToken;
   while (nextToken > buffer && *nextToken)
     --nextToken;
   if (!*nextToken)
     ++nextToken;
   lastChar = '\0';
 }
Member Data Documentation
char buffer private
Input buffer.
Definition at line 230 of file includeLinks/FileTokenizer.hpp.
char * bufferEnd private
One past the last used byte of the buffer.
Definition at line 235 of file includeLinks/FileTokenizer.hpp.
msq_stdc::FILE * filePtr private
Pointer to standard C FILE struct.
Definition at line 227 of file includeLinks/FileTokenizer.hpp.
char lastChar private
The whitespace character marking the end of the last returned token.
Saved here because if it is a newline, the line count will need to be incremented when the next token is returned.
Definition at line 245 of file includeLinks/FileTokenizer.hpp.
int lineNumber private
Line number of last returned token.
Definition at line 238 of file includeLinks/FileTokenizer.hpp.
Referenced by FileTokenizer::line_number().
char * nextToken private
One past the end of the last token returned.
Definition at line 233 of file includeLinks/FileTokenizer.hpp.
The documentation for this class was generated from the following files:
includeLinks/FileTokenizer.hpp
Misc/FileTokenizer.cpp