Rocstar: rflu_modrocstarutils Module Reference
rflu_modrocstarutils Module Reference
Public Member Functions
subroutine, public rflu_genx_buildpaneid (iRegion, iPatch, paneId)
subroutine, public rflu_genx_buildtimestring (time, timeString)
subroutine, public rflu_genx_getfilestemsurf (fileStem)
subroutine, public rflu_genx_getfilestemvol (fileStem)
subroutine, public rflu_genx_getfilestemgridsurf (fileStem)
subroutine, public rflu_genx_getfilestemgridvol (fileStem)
subroutine, public rflu_genx_getfilestemgspsurf (fileStem)
subroutine, public rflu_genx_getfilestemgspvol (fileStem)
subroutine, public rflu_genx_getfilestemmixtsurf (fileStem)
subroutine, public rflu_genx_getfilestemmixtvol (fileStem)
integer function, public rflu_genx_setcnstrtype (movePatchDir)
Public Attributes
integer, parameter, public genx_time_string_len = 9
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModGENXUtils.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 40 of file RFLU_ModRocstarUtils.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_genx_buildpaneid (integer, intent(in) iRegion, integer, intent(in) iPatch, integer, intent(out) paneId)
Definition at line 108 of file RFLU_ModRocstarUtils.F90.
Referenced by rflu_modrocstaradmin::rflu_genx_buildpconn(), rflu_modrocstario::rflu_genx_buildrocinpanestrings(), rflu_modrocstario::rflu_genx_getdimensions(), rflu_modrocstario::rflu_genx_getdimensionsderived(), rflu_modrocstario::rflu_genx_putdataflow(), rflu_modrocstario::rflu_genx_putdatagspeedssurf(), rflu_modrocstario::rflu_genx_putdatagspeedsvol(), rflu_modrocstario::rflu_genx_putdatainterf(), rflu_modrocstario::rflu_genx_putgridsurf(), rflu_modrocstario::rflu_genx_putgridvol(), rflu_modrocstario::rflu_genx_readwindow(), rflu_modrocstaradmin::rflu_genx_registerdataflow(), rflu_modrocstaradmin::rflu_genx_registerdatagspeeds(), rflu_modrocstaradmin::rflu_genx_registerdatainterf(), rflu_modrocstaradmin::rflu_genx_registerdisp(), rflu_modrocstaradmin::rflu_genx_registergridsurf(), rflu_modrocstaradmin::rflu_genx_registergridvol(), rflu_modrocstaradmin::rflu_genx_setconnsize(), stat_rflu_modrocstaradmin::stat_rflu_genxregisterdata(), and turb_rflu_modrocstaradmin::turb_rflu_genxregisterdata().
subroutine, public rflu_genx_buildtimestring (real(rfreal), intent(in) time, character(genx_time_string_len), intent(out) timeString)
Definition at line 157 of file RFLU_ModRocstarUtils.F90.
Referenced by rflu_modrocstaradmin::rflu_genx_closerocinctrlfiles(), rflu_modrocstario::rflu_genx_closerocinctrlfiles(), rflu_modrocstario::rflu_genx_openrocinctrlfiles(), rflu_modrocstario::rflu_genx_putdataflow(), rflu_modrocstario::rflu_genx_putdatagspeedssurf(), rflu_modrocstario::rflu_genx_putdatagspeedsvol(), rflu_modrocstario::rflu_genx_putdatainterf(), rflu_modrocstario::rflu_genx_putgridsurf(), rflu_modrocstario::rflu_genx_putgridvol(), rflu_modrocstario::rflu_genx_readwindow(), and rflu_modrocstario::rflu_genx_writerocinctrlfiles().
subroutine, public rflu_genx_getfilestemgridsurf (character(*), intent(out) fileStem)
Definition at line 307 of file RFLU_ModRocstarUtils.F90.
References rflu_genx_getfilestemsurf().
Referenced by rflu_modrocstario::rflu_genx_putdatagspeedssurf(), rflu_modrocstario::rflu_genx_putdatainterf(), rflu_modrocstario::rflu_genx_putgridsurf(), and rflu_modrocstario::rflu_genx_readwindow().
subroutine, public rflu_genx_getfilestemgridvol (character(*), intent(out) fileStem)
Definition at line 357 of file RFLU_ModRocstarUtils.F90.
References rflu_genx_getfilestemvol().
Referenced by rflu_modrocstario::rflu_genx_putdataflow(), rflu_modrocstario::rflu_genx_putdatagspeedsvol(), rflu_modrocstario::rflu_genx_putgridvol(), and rflu_modrocstario::rflu_genx_readwindow().
subroutine, public rflu_genx_getfilestemgspsurf (character(*), intent(out) fileStem)
Definition at line 408 of file RFLU_ModRocstarUtils.F90.
References rflu_genx_getfilestemsurf().
Referenced by rflu_modrocstario::rflu_genx_putdatagspeedssurf().
subroutine, public rflu_genx_getfilestemgspvol (character(*), intent(out) fileStem)
Definition at line 458 of file RFLU_ModRocstarUtils.F90.
References rflu_genx_getfilestemvol().
Referenced by rflu_modrocstario::rflu_genx_putdatagspeedsvol().
subroutine, public rflu_genx_getfilestemmixtsurf (character(*), intent(out) fileStem)
Definition at line 507 of file RFLU_ModRocstarUtils.F90.
References rflu_genx_getfilestemsurf().
Referenced by rflu_modrocstario::rflu_genx_putdatainterf().
subroutine, public rflu_genx_getfilestemmixtvol (character(*), intent(out) fileStem)
Definition at line 558 of file RFLU_ModRocstarUtils.F90.
References rflu_genx_getfilestemvol().
Referenced by rflu_modrocstario::rflu_genx_putdataflow().
subroutine, public rflu_genx_getfilestemsurf (character(*), intent(out) fileStem)
Definition at line 211 of file RFLU_ModRocstarUtils.F90.
Referenced by rflu_genx_getfilestemgridsurf(), rflu_genx_getfilestemgspsurf(), rflu_genx_getfilestemmixtsurf(), and rflu_modrocstario::rflu_genx_writerocinctrlfiles().
subroutine, public rflu_genx_getfilestemvol (character(*), intent(out) fileStem)
Definition at line 258 of file RFLU_ModRocstarUtils.F90.
Referenced by rflu_genx_getfilestemgridvol(), rflu_genx_getfilestemgspvol(), rflu_genx_getfilestemmixtvol(), and rflu_modrocstario::rflu_genx_writerocinctrlfiles().
integer function, public rflu_genx_setcnstrtype (integer, intent(in) movePatchDir)
Definition at line 606 of file RFLU_ModRocstarUtils.F90.
Referenced by rflu_modrocstaradmin::rflu_genx_creategridsurf().
Member Data Documentation
integer, parameter, public genx_time_string_len = 9
Definition at line 77 of file RFLU_ModRocstarUtils.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModGENXUtils.F90,v $ $Revision: 1.5 $' private
Definition at line 70 of file RFLU_ModRocstarUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModRocstarUtils.F90