Rocstar: rflu_modtime Module Reference
rflu_modtime Module Reference
Public Member Functions
real(rfreal) function, public rflu_gettimerk (global)
subroutine, public rflu_settimerk (pRegion, iStage)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModTime.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 39 of file RFLU_ModTime.F90.
Member Function/Subroutine Documentation
real(rfreal) function, public rflu_gettimerk (type(t_global), pointer global)
Definition at line 88 of file RFLU_ModTime.F90.
subroutine, public rflu_settimerk (type(t_region), pointer pRegion, integer, intent(in) iStage)
Definition at line 140 of file RFLU_ModTime.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rungekuttamp().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModTime.F90,v $ $Revision: 1.4 $' private
Definition at line 58 of file RFLU_ModTime.F90.
The documentation for this module was generated from the following file:
RFLU_ModTime.F90