Rocstar: blockDim Class Reference
blockDim Class Reference
#include <gridutil.h>
Public Member Functions
blockDim ()
blockDim (int i_, int j_, int k_)
int getSize (void) const
int c_index (int xi, int xj, int xk) const
int operator[] (const blockLoc &l) const
int & operator[] (int d)
int operator[] (int d) const
Public Member Functions inherited from blockLoc
blockLoc ()
blockLoc (int i_, int j_, int k_)
blockLoc operator+ (const blockLoc &b) const
blockLoc & operator+= (const blockLoc &b)
blockDim operator- (const blockLoc &b) const
bool operator== (const blockLoc &o) const
bool operator!= (const blockLoc &o) const
int & operator[] (int d)
int operator[] (int d) const
Additional Inherited Members
Protected Attributes inherited from blockLoc
int i
int j
int k
Detailed Description
Definition at line 120 of file gridutil.h.
Constructor & Destructor Documentation
blockDim () inline
Definition at line 122 of file gridutil.h.
 { }
blockDim (int i_, int j_, int k_) inline
Definition at line 123 of file gridutil.h.
                 :blockLoc(i_,j_,k_)
                 { }
Member Function Documentation
int c_index (int xi, int xj, int xk) const inline
Definition at line 129 of file gridutil.h.
References blockLoc::i, and blockLoc::j.
Referenced by operator[]().
                 { return xi+i*(xj+j*xk);  }
int getSize (void) const inline
Definition at line 126 of file gridutil.h.
References blockLoc::i, blockLoc::j, and blockLoc::k.
Referenced by blockConsumer::allocateBlock(), block::block(), isSmaller(), main(), read_general(), read_hdf(), block::subBlock(), volume(), write_fortran(), and write_hdf().
                 { return i*j*k; }
int operator[] (const blockLoc & l) const inline
Definition at line 133 of file gridutil.h.
References c_index().
           { return c_index(l[0],l[1],l[2]); }
int& operator[] (int d) inline
Definition at line 137 of file gridutil.h.
References d, and blockLoc::i.
 {return (&i)[d];}
int operator[] (int d) const inline
Definition at line 138 of file gridutil.h.
References d, and blockLoc::i.
 {return (&i)[d];}
The documentation for this class was generated from the following file:
gridutil.h