Rocstar: rflu_modstencilsvert Module Reference
rflu_modstencilsvert Module Reference
Public Member Functions
subroutine, public rflu_buildstencilvert2cell (pRegion)
subroutine, public rflu_createstencilvert2cell (pRegion)
subroutine, public rflu_destroystencilvert2cell (pRegion)
subroutine, public rflu_nullifystencilvert2cell (pRegion)
subroutine, public rflu_setinfostencilvert2cell (pRegion, orderNominal)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsVert.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file RFLU_ModStencilsVert.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildstencilvert2cell (type(t_region), pointer pRegion)
Definition at line 97 of file RFLU_ModStencilsVert.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), rflu_modstencilsutils::rflu_addcelllayer(), and rflu_modstencilsutils::rflu_computestencilweights().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), and rflupick().
subroutine, public rflu_createstencilvert2cell (type(t_region), pointer pRegion)
Definition at line 441 of file RFLU_ModStencilsVert.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifystencilvert2cell().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), and rflupick().
subroutine, public rflu_destroystencilvert2cell (type(t_region), pointer pRegion)
Definition at line 541 of file RFLU_ModStencilsVert.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifystencilvert2cell().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), and rflupick().
subroutine, public rflu_nullifystencilvert2cell (type(t_region), pointer pRegion)
Definition at line 642 of file RFLU_ModStencilsVert.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createstencilvert2cell(), and rflu_destroystencilvert2cell().
subroutine, public rflu_setinfostencilvert2cell (type(t_region), pointer pRegion, integer, intent(in) orderNominal)
Definition at line 724 of file RFLU_ModStencilsVert.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_computestencilsize().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), and rflupick().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsVert.F90,v $ $Revision: 1.5 $' private
Definition at line 69 of file RFLU_ModStencilsVert.F90.
The documentation for this module was generated from the following file:
RFLU_ModStencilsVert.F90