Rocstar: rflu_modsymmetryperiodic Module Reference
rflu_modsymmetryperiodic Module Reference
Public Member Functions
subroutine, public rflu_sype_addvirtualcells (pRegion)
subroutine rflu_sype_addvirtualcellsinv1 (pRegion, pPatch, vc, nCellsVirtMax, nCellsVirt)
subroutine rflu_sype_augmentcelllists (pRegion, pPatch, vc, nCellsVirt)
subroutine rflu_sype_augmentvertexlists (pRegion, pGrid, pPatch, pBorder, pBorderRelated, x2v, icl, nXTot, ivgSendSorted, ivgRecvSorted, ivgSharedSorted)
subroutine, public rflu_sype_buildp2vclist (pRegion, pRegionSerial)
subroutine, public rflu_sype_buildp2vclistserial (pRegion)
subroutine, public rflu_sype_buildtransforms (pRegion)
subroutine, public rflu_sype_buildvertexmaps (pRegion)
subroutine rflu_sype_createp2vclist (pRegion)
subroutine, public rflu_sype_createvertexmaps (pRegion)
subroutine, public rflu_sype_destroyp2vclist (pRegion)
subroutine, public rflu_sype_getactualserialcell (pRegionSerial, icgs, icgs2)
subroutine, public rflu_sype_getrelatedvertex (pRegionSerial, pRegion, ivgs, ivg)
LOGICAL function, public rflu_sype_havesypepatches (pRegion)
subroutine rflu_sype_imposevertexmap (pRegion, pPatch, ivg, ivgm)
subroutine, public rflu_sype_readtransforms (pRegion)
subroutine, public rflu_sype_setsypepatchesflag (global)
subroutine, public rflu_sype_writetransforms (pRegion)
Private Member Functions
subroutine, private rflu_sype_addvirtualcellsinv2 (pRegion, pPatch, vc, nCellsVirtMax, nCellsVirt)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModSymmetryPeriodic.F90,v $ $Revision: 1.8 $'
Detailed Description
Definition at line 39 of file RFLU_ModSymmetryPeriodic.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_sype_addvirtualcells (type(t_region), pointer pRegion)
Definition at line 117 of file RFLU_ModSymmetryPeriodic.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_sype_addvirtualcellsinv1(), rflu_sype_addvirtualcellsinv2(), and rflu_sype_augmentcelllists().
Referenced by rflupart().
subroutine rflu_sype_addvirtualcellsinv1 (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, dimension(ncellsvirtmax), intent(inout) vc, integer, intent(in) nCellsVirtMax, integer, intent(out) nCellsVirt)
Definition at line 295 of file RFLU_ModSymmetryPeriodic.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_sype_addvirtualcells().
subroutine, private rflu_sype_addvirtualcellsinv2 (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, dimension(ncellsvirtmax), intent(inout) vc, integer, intent(in) nCellsVirtMax, integer, intent(out) nCellsVirt) private
Definition at line 404 of file RFLU_ModSymmetryPeriodic.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), i, j, modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modtopologyutils::rflu_buildfacevertlist(), rflu_modtopologyutils::rflu_buildvertcellnghblist(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), and rflu_modstencilscells::rflu_setinfoc2cstencilwrapper().
Referenced by rflu_sype_addvirtualcells().
subroutine rflu_sype_augmentcelllists (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, dimension(ncellsvirt), intent(in) vc, integer, intent(in) nCellsVirt)
Definition at line 665 of file RFLU_ModSymmetryPeriodic.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortintegerinteger(), moderror::registerfunction(), rflu_sype_augmentvertexlists(), modtools::swapintegers(), and modtools::swaprfreals().
Referenced by rflu_sype_addvirtualcells().
subroutine rflu_sype_augmentvertexlists (type(t_region), pointer pRegion, type(t_grid), pointer pGrid, type(t_patch), pointer pPatch, type(t_border), pointer pBorder, type(t_border), pointer pBorderRelated, integer, dimension(:,:), pointer x2v, integer, intent(in) icl, integer, intent(inout) nXTot, integer, dimension(:) ivgSendSorted, integer, dimension(:) ivgRecvSorted, integer, dimension(:) ivgSharedSorted)
Definition at line 1200 of file RFLU_ModSymmetryPeriodic.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), modsortsearch::quicksortintegerinteger(), reflectposition(), moderror::registerfunction(), and rflu_sype_imposevertexmap().
Referenced by rflu_sype_augmentcelllists().
subroutine, public rflu_sype_buildp2vclist (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 1455 of file RFLU_ModSymmetryPeriodic.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_sype_createp2vclist().
Referenced by rflupart().
subroutine, public rflu_sype_buildp2vclistserial (type(t_region), pointer pRegion)
Definition at line 1664 of file RFLU_ModSymmetryPeriodic.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_sype_buildtransforms (type(t_region), pointer pRegion)
Definition at line 1778 of file RFLU_ModSymmetryPeriodic.F90.
References cos, moderror::deregisterfunction(), moderror::errorstop(), modtools::floatequal(), moderror::registerfunction(), and sin.
Referenced by rflupart().
subroutine, public rflu_sype_buildvertexmaps (type(t_region), pointer pRegion)
Definition at line 1976 of file RFLU_ModSymmetryPeriodic.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), max(), min(), moderror::registerfunction(), rflu_modoctree::rflu_buildoctree(), rflu_modoctree::rflu_createoctree(), rflu_modoctree::rflu_destroyoctree(), rflu_modoctree::rflu_queryoctree(), sqrt(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by rflupart().
subroutine rflu_sype_createp2vclist (type(t_region), pointer pRegion)
Definition at line 2274 of file RFLU_ModSymmetryPeriodic.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_sype_buildp2vclist().
subroutine, public rflu_sype_createvertexmaps (type(t_region), pointer pRegion)
Definition at line 2372 of file RFLU_ModSymmetryPeriodic.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_sype_destroyp2vclist (type(t_region), pointer pRegion)
Definition at line 2463 of file RFLU_ModSymmetryPeriodic.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_sype_getactualserialcell (type(t_region), pointer pRegionSerial, integer, intent(in) icgs, integer, intent(out) icgs2)
Definition at line 2566 of file RFLU_ModSymmetryPeriodic.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modcommlists::rflu_comm_buildcommlistscells(), and rflu_modcommlists::rflu_comm_countborders().
subroutine, public rflu_sype_getrelatedvertex (type(t_region), pointer pRegionSerial, type(t_region), pointer pRegion, integer, intent(in) ivgs, integer, intent(out) ivg)
Definition at line 2690 of file RFLU_ModSymmetryPeriodic.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortintegerinteger(), and moderror::registerfunction().
Referenced by rflu_modcommlists::rflu_comm_buildcommlistsvert().
LOGICAL function, public rflu_sype_havesypepatches (type(t_region), pointer pRegion)
Definition at line 2899 of file RFLU_ModSymmetryPeriodic.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modcommlists::rflu_comm_buildcommlists(), rflu_modcommlists::rflu_comm_buildcommlistsvert(), rflu_modcommlists::rflu_comm_countborders(), rflu_initflowsolver(), rflu_modpartitionregion::rflu_part_partitionregion(), and rflupart().
subroutine rflu_sype_imposevertexmap (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) ivg, integer, intent(out) ivgm)
Definition at line 2993 of file RFLU_ModSymmetryPeriodic.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_sype_augmentvertexlists().
subroutine, public rflu_sype_readtransforms (type(t_region), pointer pRegion)
Definition at line 3075 of file RFLU_ModSymmetryPeriodic.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), Attribute::status(), and StopWatch::stop().
Referenced by rflu_initflowsolver().
subroutine, public rflu_sype_setsypepatchesflag (type(t_global), pointer global)
Definition at line 3309 of file RFLU_ModSymmetryPeriodic.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, CImg< T >::line(), moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modcentaur::rflu_readgridcentaurascii().
subroutine, public rflu_sype_writetransforms (type(t_region), pointer pRegion)
Definition at line 3431 of file RFLU_ModSymmetryPeriodic.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflupart().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModSymmetryPeriodic.F90,v $ $Revision: 1.8 $' private
Definition at line 63 of file RFLU_ModSymmetryPeriodic.F90.
The documentation for this module was generated from the following file:
RFLU_ModSymmetryPeriodic.F90