Rocstar: HDS_accessor< _MP > Class Template Reference
HDS_accessor< _MP > Class Template Reference
#include <HDS_accessor.h>
Public Types
typedef HDS_overlay HDS
typedef Vertex_overlay Vertex
typedef Halfedge_overlay Halfedge
typedef Facet_overlay Facet
typedef HDS::Point Point
typedef Vector_3 Vector
typedef _MP Supports_multiple_panes
Public Member Functions
Halfedge * get_halfedge (Vertex *v) const
Vertex * get_vertex (Halfedge *h) const
Vertex * get_origin (Halfedge *h) const
Vertex * get_destination (Halfedge *h) const
Halfedge * get_opposite (Halfedge *h) const
Halfedge * get_prev (Halfedge *h) const
Halfedge * get_next (Halfedge *h) const
Facet * get_facet (Halfedge *h) const
Halfedge * get_halfedge (Facet *f) const
Vertex * get_primary (Vertex *v) const
HDS_overlay * get_hds (Vertex *v) const
HDS_overlay * get_hds (Halfedge *h) const
RFC_Pane_overlay * get_pane (Vertex *v) const
RFC_Pane_overlay * get_pane (Halfedge *h) const
Halfedge * get_prev_around_origin (Halfedge *h) const
Halfedge * get_next_around_origin (Halfedge *h) const
Halfedge * get_prev_around_destination (Halfedge *h) const
Halfedge * get_next_around_destination (Halfedge *h) const
bool is_border (const Halfedge *h) const
bool is_border (const Halfedge *h, Tag_false) const
bool is_border (const Halfedge *h, Tag_true) const
bool is_border (const Vertex *v) const
bool is_border (const Vertex *v, Tag_false) const
bool is_border (const Vertex *v, Tag_true) const
bool is_on_feature (const Vertex *v) const
bool is_feature_0 (const Vertex *v) const
bool is_feature_1 (const Halfedge *h) const
bool is_primary (const Vertex *v) const
const Vertex * get_primary (const Vertex *v) const
const Halfedge * get_halfedge (const Vertex *v) const
const Vertex * get_vertex (const Halfedge *h) const
const Vertex * get_origin (const Halfedge *h) const
const Vertex * get_destination (const Halfedge *h) const
const Halfedge * get_opposite (const Halfedge *h) const
const Halfedge * get_prev (const Halfedge *h) const
const Halfedge * get_next (const Halfedge *h) const
const Facet * get_facet (const Halfedge *h) const
const Halfedge * get_halfedge (const Facet *f) const
const HDS_overlay * get_hds (const Vertex *v) const
const HDS_overlay * get_hds (const Halfedge *h) const
const RFC_Pane_overlay * get_pane (const Vertex *v) const
const RFC_Pane_overlay * get_pane (const Halfedge *h) const
const Halfedge * get_prev_around_origin (const Halfedge *h) const
const Halfedge * get_next_around_origin (const Halfedge *h) const
const Halfedge * get_prev_around_destination (const Halfedge *h) const
const Halfedge * get_next_around_destination (const Halfedge *h) const
const Vector_3 & get_normal (const Halfedge *h) const
const Vector_3 & get_normal (const Halfedge *h, const Vertex *v) const
void mark (Halfedge *h) const
void unmark (Halfedge *h) const
bool marked (const Halfedge *h) const
Halfedge * get_halfedge (Vertex *v, Tag_false) const
Halfedge * get_halfedge (Vertex *v, Tag_true) const
Vertex * get_vertex (Halfedge *h, Tag_false) const
Vertex * get_vertex (Halfedge *h, Tag_true) const
Halfedge * get_opposite (Halfedge *h, Tag_false) const
Halfedge * get_opposite (Halfedge *i, Tag_true) const
Vertex * get_primary (Vertex *v, Tag_false) const
Vertex * get_primary (Vertex *v, Tag_true) const
const Halfedge * get_halfedge (const Vertex *v, Tag_false) const
const Halfedge * get_halfedge (const Vertex *v, Tag_true) const
const Vertex * get_vertex (const Halfedge *h, Tag_false) const
const Vertex * get_vertex (const Halfedge *h, Tag_true) const
const Halfedge * get_opposite (const Halfedge *h, Tag_false) const
const Halfedge * get_opposite (const Halfedge *i, Tag_true) const
const Vertex * get_primary (const Vertex *v, Tag_false) const
const Vertex * get_primary (const Vertex *v, Tag_true) const
void set_parent (INode *i, Halfedge *h, const Point_2 &p, int color)
INode * get_inode (Vertex *v) const
const INode * get_inode (const Vertex *v) const
void set_inode (Vertex *v, INode *i) const
INode_list & get_inode_list (Halfedge *h) const
const INode_list & get_inode_list (const Halfedge *h) const
INode * get_buffered_inode (Halfedge *h, int tag) const
void set_buffered_inode (Halfedge *h, int tag, INode *i) const
Protected Member Functions
Halfedge * get_counterpart (Halfedge *h) const
const Halfedge * get_counterpart (const Halfedge *h) const
Detailed Description
template<class _MP = Tag_false>
class HDS_accessor< _MP >
Definition at line 48 of file HDS_accessor.h.
Member Typedef Documentation
typedef Facet_overlay Facet
Definition at line 56 of file HDS_accessor.h.
typedef Halfedge_overlay Halfedge
Definition at line 55 of file HDS_accessor.h.
typedef HDS_overlay HDS
Definition at line 53 of file HDS_accessor.h.
typedef HDS::Point Point
Definition at line 59 of file HDS_accessor.h.
typedef _MP Supports_multiple_panes
Definition at line 65 of file HDS_accessor.h.
typedef Vector_3 Vector
Definition at line 60 of file HDS_accessor.h.
typedef Vertex_overlay Vertex
Definition at line 54 of file HDS_accessor.h.
Member Function Documentation
INode* get_buffered_inode (Halfedge * h, int tag) const inline
Definition at line 383 of file HDS_accessor.h.
Referenced by Overlay::insert_node_in_green_edge().
{
     return get_pane(h)->get_buffered_inode( h, tag);
   }
Halfedge* get_counterpart (Halfedge * h) const inline protected
Definition at line 390 of file HDS_accessor.h.
Referenced by HDS_accessor< Tag_true >::get_halfedge(), HDS_accessor< Tag_true >::get_next(), HDS_accessor< Tag_true >::get_opposite(), and HDS_accessor< Tag_true >::get_prev().
   { return get_pane(h)->get_counterpart( h); }
const Halfedge* get_counterpart (const Halfedge * h) const inline protected
Definition at line 392 of file HDS_accessor.h.
   { return get_pane(h)->get_counterpart( h); }
Vertex* get_destination (Halfedge * h) const inline
Definition at line 93 of file HDS_accessor.h.
Referenced by RFC_Window_overlay::check_false_strong_1(), Overlay::contains(), RFC_Window_overlay::cos_edge_angle(), RFC_Window_overlay::detect_features(), RFC_Window_overlay::evaluate_normals(), Overlay::get_edge_parent(), Overlay::get_next_inode_ccw(), RFC_Window_overlay::identify_features_0(), Overlay::intersect_blue_with_green(), Overlay::intersect_link_helper(), RFC_Window_overlay::merge_features_1(), RFC_Window_overlay::print_features(), Overlay::project_adjacent_green_vertices(), Overlay_primitives::snap_blue_ridge_edge(), RFC_Window_overlay::subdiv_feature_curve(), and Overlay::verify_inode().
{
     // returns the incident vertex of h. If supports connected
     // panes, return the primary copy of the vertex.
     return get_vertex( h);
   }
const Vertex* get_destination (const Halfedge * h) const inline
Definition at line 210 of file HDS_accessor.h.
{
     // returns the incident vertex of h. If supports connected
     // panes, return the primary copy of the vertex.
     return get_vertex( h);
   }
Facet* get_facet (Halfedge * h) const inline
Definition at line 111 of file HDS_accessor.h.
Referenced by Overlay::contains().
{
     // returns the incident facet of h.
     return h->facet();
   }
const Facet* get_facet (const Halfedge * h) const inline
Definition at line 250 of file HDS_accessor.h.
{
     // returns the incident facet of h.
     return h->facet();
   }
Halfedge* get_halfedge (Vertex * v) const inline
Definition at line 75 of file HDS_accessor.h.
Referenced by Overlay::associate_green_vertices(), RFC_Window_overlay::check_false_strong_1(), RFC_Window_overlay::comp_angle_defect(), RFC_Window_overlay::evaluate_normals(), Overlay::get_green_parent(), HDS_accessor< Tag_true >::get_halfedge(), Overlay::get_inodes_of_face(), HDS_accessor< Tag_true >::is_border(), RFC_Window_overlay::is_strong_ad(), Overlay::match_features_0(), RFC_Window_overlay::print_features(), and Overlay::sort_on_green_edges().
{
     // returns the incident halfedge of a vertex v. If supports connected
     // panes, return the primary copy of the halfedge.
      return get_halfedge( v, Supports_multiple_panes());
   }
Halfedge* get_halfedge (Facet * f) const inline
Definition at line 116 of file HDS_accessor.h.
{
     // returns the incident halfedge of f.
     // Note that the halfedge is necessarily a primary copy.
     return f->halfedge();
   }
const Halfedge* get_halfedge (const Vertex * v) const inline
Definition at line 192 of file HDS_accessor.h.
{
     // returns the incident halfedge of a vertex v. If supports connected
     // panes, return the primary copy of the halfedge.
     return get_halfedge( v, Supports_multiple_panes());
   }
const Halfedge* get_halfedge (const Facet * f) const inline
Definition at line 255 of file HDS_accessor.h.
{
     // returns the incident halfedge of f.
     // Note that the halfedge is necessarily a primary copy.
     return f->halfedge();
   }
Halfedge* get_halfedge (Vertex * v, Tag_false) const inline
Definition at line 307 of file HDS_accessor.h.
 { return v->halfedge(); }
Halfedge* get_halfedge (Vertex * v, Tag_true) const inline
Definition at line 308 of file HDS_accessor.h.
{
     Halfedge *h = v->halfedge();
     return h->is_border() ? get_counterpart( h) : h;
   }
const Halfedge* get_halfedge (const Vertex * v, Tag_false) const inline
Definition at line 331 of file HDS_accessor.h.
   { return v->halfedge(); }
const Halfedge* get_halfedge (const Vertex * v, Tag_true) const inline
Definition at line 333 of file HDS_accessor.h.
{
     const Halfedge *h = v->halfedge();
     return h->is_border() ? get_counterpart( h) : h;
   }
HDS_overlay* get_hds (Vertex * v) const inline
Definition at line 125 of file HDS_accessor.h.
 { return v->pane()->hds(); }
HDS_overlay* get_hds (Halfedge * h) const inline
Definition at line 126 of file HDS_accessor.h.
Referenced by HDS_accessor< Tag_true >::get_hds().
 { return get_hds(h->vertex()); }
const HDS_overlay* get_hds (const Vertex * v) const inline
Definition at line 261 of file HDS_accessor.h.
 { return v->pane()->hds(); }
const HDS_overlay* get_hds (const Halfedge * h) const inline
Definition at line 262 of file HDS_accessor.h.
Referenced by HDS_accessor< Tag_true >::get_hds().
 { return get_hds(h->vertex()); }
INode* get_inode (Vertex * v) const inline
Definition at line 370 of file HDS_accessor.h.
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::match_features_0(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), and Overlay::verify_inode().
   { RFC_assertion( is_primary( v)); return get_pane( v)->get_inode( v); }
const INode* get_inode (const Vertex * v) const inline
Definition at line 372 of file HDS_accessor.h.
   { RFC_assertion( is_primary( v)); return get_pane( v)->get_inode( v); }
INode_list& get_inode_list (Halfedge * h) const inline
Definition at line 377 of file HDS_accessor.h.
Referenced by Overlay::associate_green_vertices(), Overlay::get_inodes_of_face(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), and Overlay::verify_inode().
   { return get_pane(h)->get_inode_list(h); }
const INode_list& get_inode_list (const Halfedge * h) const inline
Definition at line 380 of file HDS_accessor.h.
   { return get_pane(h)->get_inode_list(h); }
Halfedge* get_next (Halfedge * h) const inline
Definition at line 108 of file HDS_accessor.h.
Referenced by Overlay::associate_green_vertices(), RFC_Window_overlay::comp_angle_defect(), Overlay::contains(), Overlay::get_green_parent(), Overlay::get_inodes_of_face(), Overlay::get_nat_coor(), HDS_accessor< Tag_true >::get_next(), HDS_accessor< Tag_true >::get_next_around_destination(), HDS_accessor< Tag_true >::get_next_around_origin(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link_helper(), Overlay::intersect_link_helper2(), Overlay::match_features_0(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), and Overlay::verify_inode().
   { return (Halfedge*)get_next( (const Halfedge*)h); }
const Halfedge* get_next (const Halfedge * h) const inline
Definition at line 236 of file HDS_accessor.h.
{
     const Halfedge *next = h->next();
     if ( !is_border( h)) return next;
     RFC_assertion_code( int count=0);
     while ( !is_border(next)) {
       RFC_assertion( next->is_border());
       next = get_counterpart(next)->opposite()->next();
       RFC_assertion( is_border(next) || h != get_counterpart(next));
       RFC_assertion( ++count<100);
     }
     return next;
   }
Halfedge* get_next_around_destination (Halfedge * h) const inline
Definition at line 146 of file HDS_accessor.h.
Referenced by RFC_Window_overlay::check_false_strong_1(), RFC_Window_overlay::comp_angle_defect(), RFC_Window_overlay::evaluate_normals(), HDS_accessor< Tag_true >::is_border(), RFC_Window_overlay::is_strong_ad(), Overlay::match_features_0(), RFC_Window_overlay::print_features(), and RFC_Window_overlay::remove_feature_1().
{
     // returns the next halfedge around h->destination().
     return get_opposite( get_next( h));
   }
const Halfedge* get_next_around_destination (const Halfedge * h) const inline
Definition at line 284 of file HDS_accessor.h.
{
     // returns the next halfedge around h->destination().
     return get_opposite( get_next(h));
   }
Halfedge* get_next_around_origin (Halfedge * h) const inline
Definition at line 136 of file HDS_accessor.h.
Referenced by Overlay::count_subnodes(), RFC_Window_overlay::detect_features(), Overlay::get_edge_parent(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::match_features_0(), and Overlay::number_a_subnode().
{
     // returns the next halfedge around h->origin().
     return get_next( get_opposite( h));
   }
const Halfedge* get_next_around_origin (const Halfedge * h) const inline
Definition at line 274 of file HDS_accessor.h.
{
     // returns the next halfedge around h->origin().
     return get_next( get_opposite( h));
   }
const Vector_3& get_normal (const Halfedge * h) const inline
Definition at line 289 of file HDS_accessor.h.
Referenced by Overlay::get_green_parent(), Overlay_primitives::intersect(), and Overlay_primitives::normalmatch().
   { return get_pane(h)->get_normal(h, h->destination()); }
const Vector_3& get_normal (const Halfedge * h, const Vertex * v) const inline
Definition at line 292 of file HDS_accessor.h.
   { return get_pane(h)->get_normal(h, v); }
Halfedge* get_opposite (Halfedge * h) const inline
Definition at line 99 of file HDS_accessor.h.
Referenced by Overlay::associate_green_vertices(), RFC_Window_overlay::check_false_strong_1(), Overlay::contains(), RFC_Window_overlay::detect_features(), RFC_Window_overlay::evaluate_normals(), Overlay::get_edge_pair_parents(), Overlay::get_edge_parent(), Overlay::get_green_parent(), Overlay::get_inodes_of_face(), Overlay::get_nat_coor(), HDS_accessor< Tag_true >::get_next_around_destination(), HDS_accessor< Tag_true >::get_next_around_origin(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), HDS_accessor< Tag_true >::get_opposite(), HDS_accessor< Tag_true >::get_origin(), Overlay::get_parent_face(), HDS_accessor< Tag_true >::get_prev_around_destination(), HDS_accessor< Tag_true >::get_prev_around_origin(), RFC_Pane_overlay::get_tangent(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay_primitives::intersect(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::is_queue_empty(), Overlay::match_features_0(), RFC_Window_overlay::merge_features_1(), Overlay_primitives::normalmatch(), Overlay::number_a_subnode(), RFC_Window_overlay::print_features(), Overlay::project_adjacent_green_vertices(), RFC_Window_overlay::remove_feature_1(), HDS_accessor< Tag_true >::set_parent(), Overlay_primitives::snap_blue_ridge_edge(), Overlay::sort_on_green_edges(), RFC_Window_overlay::subdiv_feature_curve(), and Overlay::verify_inode().
{
     // Get the opposite halfedge of h. If supports connected
     // panes, return the primary copy of the opposite halfedge.
     return get_opposite( h, Supports_multiple_panes());
   }
const Halfedge* get_opposite (const Halfedge * h) const inline
Definition at line 216 of file HDS_accessor.h.
{
     // Get the opposite halfedge of h. If supports connected
     // panes, return the primary copy of the opposite halfedge.
     return get_opposite( h, Supports_multiple_panes());
   }
Halfedge* get_opposite (Halfedge * h, Tag_false) const inline
Definition at line 317 of file HDS_accessor.h.
   { return h->opposite(); }
Halfedge* get_opposite (Halfedge * i, Tag_true) const inline
Definition at line 319 of file HDS_accessor.h.
{
     Halfedge *h = i->opposite();
     return h->is_border() ? get_counterpart( h) : h;
   }
const Halfedge* get_opposite (const Halfedge * h, Tag_false) const inline
Definition at line 343 of file HDS_accessor.h.
   { return h->opposite(); }
const Halfedge* get_opposite (const Halfedge * i, Tag_true) const inline
Definition at line 345 of file HDS_accessor.h.
{
     const Halfedge *h = i->opposite();
     return h->is_border() ? get_counterpart( h) : h;
   }
Vertex* get_origin (Halfedge * h) const inline
Definition at line 87 of file HDS_accessor.h.
Referenced by Overlay::associate_green_vertices(), RFC_Window_overlay::check_false_strong_1(), Overlay::contains(), RFC_Window_overlay::cos_edge_angle(), RFC_Window_overlay::detect_features(), Overlay::get_edge_parent(), Overlay::get_inodes_of_face(), Overlay::get_nat_coor(), Overlay::get_next_inode_cw(), RFC_Window_overlay::identify_features_0(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), RFC_Window_overlay::is_strong_ad(), Overlay::match_features_0(), RFC_Window_overlay::merge_features_1(), Overlay::project_adjacent_green_vertices(), Overlay_primitives::snap_blue_ridge_edge(), Overlay_primitives::snap_blue_ridge_vertex(), Overlay::sort_on_green_edges(), RFC_Window_overlay::subdiv_feature_curve(), and Overlay::verify_inode().
{
     // returns the incident vertex of h. If supports connected
     // panes, return the primary copy of the vertex.
     return get_vertex( get_opposite(h,Tag_false()));
   }
const Vertex* get_origin (const Halfedge * h) const inline
Definition at line 204 of file HDS_accessor.h.
{
     // returns the incident vertex of h. If supports connected
     // panes, return the primary copy of the vertex.
     return get_vertex( get_opposite(h,Tag_false()));
   }
RFC_Pane_overlay* get_pane (Vertex * v) const inline
Definition at line 128 of file HDS_accessor.h.
Referenced by RFC_Window_overlay::check_false_strong_1(), RFC_Window_overlay::comp_angle_defect(), Overlay::convert_nat_coordinates(), RFC_Window_overlay::cos_edge_angle(), RFC_Window_overlay::cos_face_angle(), Overlay::count_subnodes(), RFC_Window_overlay::detect_features(), RFC_Window_overlay::evaluate_normals(), HDS_accessor< Tag_true >::get_buffered_inode(), HDS_accessor< Tag_true >::get_counterpart(), Overlay::get_green_parent(), HDS_accessor< Tag_true >::get_inode(), HDS_accessor< Tag_true >::get_inode_list(), RFC_Pane_overlay::get_normal(), HDS_accessor< Tag_true >::get_normal(), HDS_accessor< Tag_true >::get_pane(), HDS_accessor< Tag_true >::get_primary(), RFC_Pane_overlay::get_tangent(), RFC_Window_overlay::identify_features_0(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), HDS_accessor< Tag_true >::is_border(), HDS_accessor< Tag_true >::is_feature_0(), HDS_accessor< Tag_true >::is_feature_1(), HDS_accessor< Tag_true >::is_on_feature(), HDS_accessor< Tag_true >::is_primary(), HDS_accessor< Tag_true >::mark(), HDS_accessor< Tag_true >::marked(), Overlay::match_features_0(), Overlay::number_a_subnode(), Overlay::number_subfaces(), Overlay::overlay_init(), RFC_Window_overlay::print_features(), Overlay::project_adjacent_green_vertices(), Overlay::project_next_vertex(), RFC_Window_overlay::remove_feature_0(), RFC_Window_overlay::remove_feature_1(), HDS_accessor< Tag_true >::set_buffered_inode(), HDS_accessor< Tag_true >::set_inode(), Overlay_primitives::snap_blue_ridge_edge(), Overlay_primitives::snap_blue_ridge_vertex(), RFC_Window_overlay::subdiv_feature_curve(), and HDS_accessor< Tag_true >::unmark().
 { return v->pane(); }
RFC_Pane_overlay* get_pane (Halfedge * h) const inline
Definition at line 129 of file HDS_accessor.h.
Referenced by HDS_accessor< Tag_true >::get_pane().
 { return get_pane(h->vertex()); }
const RFC_Pane_overlay* get_pane (const Vertex * v) const inline
Definition at line 264 of file HDS_accessor.h.
   { return v->pane();}
const RFC_Pane_overlay* get_pane (const Halfedge * h) const inline
Definition at line 266 of file HDS_accessor.h.
   { return get_pane(h->vertex());}
Halfedge* get_prev (Halfedge * h) const inline
Definition at line 105 of file HDS_accessor.h.
Referenced by HDS_accessor< Tag_true >::get_prev(), HDS_accessor< Tag_true >::get_prev_around_destination(), HDS_accessor< Tag_true >::get_prev_around_origin(), and Overlay::intersect_link().
   { return (Halfedge*)get_prev( (const Halfedge*)h); }
const Halfedge* get_prev (const Halfedge * h) const inline
Definition at line 222 of file HDS_accessor.h.
{
     const Halfedge *prev = h->prev();
     if ( !is_border( h)) return prev;
     RFC_assertion_code( int count=0);
     while ( !is_border(prev)) {
       RFC_assertion( prev->is_border());
       prev = get_counterpart(prev)->opposite()->prev();
       RFC_assertion( is_border(prev) || h != get_counterpart(prev));
       RFC_assertion( ++count<100);
     }
     return prev;
   }
Halfedge* get_prev_around_destination (Halfedge * h) const inline
Definition at line 141 of file HDS_accessor.h.
Referenced by RFC_Pane_overlay::get_normal().
{
     // returns the previous halfedge around h->destination().
     return get_prev( get_opposite( h));
   }
const Halfedge* get_prev_around_destination (const Halfedge * h) const inline
Definition at line 279 of file HDS_accessor.h.
{
     // returns the previous halfedge around h->destination().
     return get_prev( get_opposite( h));
   }
Halfedge* get_prev_around_origin (Halfedge * h) const inline
Definition at line 131 of file HDS_accessor.h.
{
     // returns the previous halfedge around h->origin().
     return get_opposite( get_prev( h));
   }
const Halfedge* get_prev_around_origin (const Halfedge * h) const inline
Definition at line 269 of file HDS_accessor.h.
{
     // returns the previous halfedge around h->origin().
     return get_opposite( get_prev( h));
   }
Vertex* get_primary (Vertex * v) const inline
Definition at line 122 of file HDS_accessor.h.
Referenced by HDS_accessor< Tag_true >::get_primary(), HDS_accessor< Tag_true >::get_vertex(), HDS_accessor< Tag_true >::is_feature_0(), HDS_accessor< Tag_true >::is_on_feature(), RFC_Window_overlay::print_features(), and RFC_Window_overlay::reduce_coordinates_to_all().
   { return v?get_primary( v, Supports_multiple_panes()):v; }
const Vertex* get_primary (const Vertex * v) const inline
Definition at line 189 of file HDS_accessor.h.
   { return v?get_primary( v, Supports_multiple_panes()):v; }
Vertex* get_primary (Vertex * v, Tag_false) const inline
Definition at line 324 of file HDS_accessor.h.
 { return v; }
Vertex* get_primary (Vertex * v, Tag_true) const inline
Definition at line 325 of file HDS_accessor.h.
   { return get_pane(v)->get_primary(v); }
const Vertex* get_primary (const Vertex * v, Tag_false) const inline
Definition at line 350 of file HDS_accessor.h.
   { return v; }
const Vertex* get_primary (const Vertex * v, Tag_true) const inline
Definition at line 352 of file HDS_accessor.h.
   { return v?get_pane(v)->get_primary(v):v; }
Vertex* get_vertex (Halfedge * h) const inline
Definition at line 81 of file HDS_accessor.h.
Referenced by HDS_accessor< Tag_true >::get_destination(), HDS_accessor< Tag_true >::get_origin(), and HDS_accessor< Tag_true >::get_vertex().
{
     // returns the incident vertex of h. If supports connected
     // panes, return the primary copy of the vertex.
     return get_vertex( h, Supports_multiple_panes());
   }
const Vertex* get_vertex (const Halfedge * h) const inline
Definition at line 198 of file HDS_accessor.h.
{
     // returns the incident vertex of h. If supports connected
     // panes, return the primary copy of the vertex.
     return get_vertex( h, Supports_multiple_panes());
   }
Vertex* get_vertex (Halfedge * h, Tag_false) const inline
Definition at line 313 of file HDS_accessor.h.
 { return h->vertex(); }
Vertex* get_vertex (Halfedge * h, Tag_true) const inline
Definition at line 314 of file HDS_accessor.h.
   { return get_primary( h->vertex()); }
const Vertex* get_vertex (const Halfedge * h, Tag_false) const inline
Definition at line 338 of file HDS_accessor.h.
   { return h->vertex(); }
const Vertex* get_vertex (const Halfedge * h, Tag_true) const inline
Definition at line 340 of file HDS_accessor.h.
   { return get_primary( h->vertex()); }
bool is_border (const Halfedge * h) const inline
Definition at line 153 of file HDS_accessor.h.
Referenced by Overlay::associate_green_vertices(), RFC_Window_overlay::comp_angle_defect(), RFC_Window_overlay::cos_face_angle(), Overlay::get_edge_pair_parents(), Overlay::get_edge_parent(), Overlay::get_green_parent(), Overlay::get_inodes_of_face(), Overlay::get_nat_coor(), HDS_accessor< Tag_true >::get_next(), Overlay::get_next_inode(), HDS_accessor< Tag_true >::get_prev(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay_primitives::intersect(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), HDS_accessor< Tag_true >::is_border(), Overlay::match_features_0(), Overlay::overlay_init(), HDS_accessor< Tag_true >::set_parent(), Overlay_primitives::snap_blue_ridge_edge(), and Overlay_primitives::snap_blue_ridge_vertex().
   { return is_border( h, Supports_multiple_panes()); }
bool is_border (const Halfedge * h, Tag_false) const inline
Definition at line 155 of file HDS_accessor.h.
   { return h->is_border(); }
bool is_border (const Halfedge * h, Tag_true) const inline
Definition at line 157 of file HDS_accessor.h.
   { return get_pane(h)->is_physical_border(h); }
bool is_border (const Vertex * v) const inline
Definition at line 160 of file HDS_accessor.h.
   { return is_border( v, Supports_multiple_panes()); }
bool is_border (const Vertex * v, Tag_false) const inline
Definition at line 163 of file HDS_accessor.h.
   { return v->halfedge()->is_border(); }
bool is_border (const Vertex * v, Tag_true) const inline
Definition at line 165 of file HDS_accessor.h.
{
     if ( !v->halfedge()->is_border()) return false;
     const Halfedge *h = get_halfedge( v), *h0=h;
     do {
       if (h->is_border()) return true;
     } while ( ( h=get_next_around_destination( h)) != h0);
     return false;
   }
bool is_feature_0 (const Vertex * v) const inline
Definition at line 179 of file HDS_accessor.h.
Referenced by Overlay::insert_edge_into_queue().
   { const Vertex *vprim = get_primary( v);
     return get_pane(vprim)->is_feature_0(vprim);
   }
bool is_feature_1 (const Halfedge * h) const inline
Definition at line 184 of file HDS_accessor.h.
Referenced by Overlay::insert_edge_into_queue(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), and Overlay_primitives::normalmatch().
   { return get_pane(h)->is_feature_1(h); }
bool is_on_feature (const Vertex * v) const inline
Definition at line 174 of file HDS_accessor.h.
Referenced by Overlay::insert_edge_into_queue(), Overlay::intersect_blue_with_green(), Overlay_primitives::snap_blue_ridge_edge(), and Overlay_primitives::snap_blue_ridge_vertex().
   { const Vertex *vprim = get_primary( v);
     return get_pane(vprim)->is_on_feature(vprim);
   }
bool is_primary (const Vertex * v) const inline
Definition at line 187 of file HDS_accessor.h.
Referenced by Overlay::get_green_parent(), HDS_accessor< Tag_true >::get_inode(), HDS_accessor< Tag_true >::set_inode(), and Overlay::sort_on_green_edges().
 { return get_pane(v)->is_primary(v);}
void mark (Halfedge * h) const inline
Definition at line 295 of file HDS_accessor.h.
Referenced by RFC_Window_overlay::detect_features(), Overlay::get_green_parent(), Overlay::insert_edge_into_queue(), Overlay::is_queue_empty(), and read_files().
   { get_pane(h)->mark( h); }
bool marked (const Halfedge * h) const inline
Definition at line 299 of file HDS_accessor.h.
Referenced by RFC_Window_overlay::detect_features(), Overlay::get_green_parent(), Overlay::insert_edge_into_queue(), and Overlay::is_queue_empty().
   { return get_pane(h)->marked( h); }
void set_buffered_inode (Halfedge * h, int tag, INode * i) const inline
Definition at line 386 of file HDS_accessor.h.
Referenced by Overlay::insert_node_in_green_edge().
{
     get_pane(h)->set_buffered_inode( h, tag, i);
   }
void set_inode (Vertex * v, INode * i) const inline
Definition at line 374 of file HDS_accessor.h.
Referenced by Overlay::insert_node_in_blue_edge(), and Overlay::project_adjacent_green_vertices().
   { RFC_assertion( is_primary( v)); get_pane(v)->set_inode(v,i); }
void set_parent (INode * i, Halfedge * h, const Point_2 & p, int color) inline
Definition at line 355 of file HDS_accessor.h.
Referenced by Overlay::project_next_vertex().
{
     Real x=p[0];  RFC_assertion( x>=0. && x<=1.);
     if ( x == 1) { h=get_opposite(h); x = 0; }
     if ( is_border( h)) {
       if (x==0) h = h->opposite()->next();
       else { h = h->opposite(); x=1.-x; }
       RFC_assertion( !h->is_border());
     }
     if ( x!=p[0])
       i->set_parent( h, Point_2(x,p[1]), color);
     else
       i->set_parent( h, p, color);
   }
void unmark (Halfedge * h) const inline
Definition at line 297 of file HDS_accessor.h.
Referenced by Overlay::get_green_parent().
   { get_pane(h)->unmark( h); }
The documentation for this class was generated from the following file:
HDS_accessor.h