Rocstar: TestingObject< ResultsType > Class Template Reference
TestingObject< ResultsType > Class Template Reference
Project-specific testing object.
#include <RocstarTest.H>
Public Member Functions
TestingObject ()
Default constructor.
virtual void Epilogue ()
Tears down the testing fixtures if needed.
virtual void Prologue ()
Sets up the data fixtures for the tests.
double F1 (double x)
Simple test function fixture returns .
double F2 (double x)
Simple test function fixture returns .
virtual void Test__ExampleFunction (ResultsType &result)
Test for Rocstar::ExampleFunction.
virtual void Test__TrapezoidQuadrature (ResultsType &result)
Test for Rocstar::TrapezoidQuadrature.
virtual void Test__MidPointQuadrature (ResultsType &result)
Test for Rocstar::MidPointQuadrature.
virtual void Process (ResultsType &result)
Runs all tests implemented by the Rocstar::TestingObject.
virtual void RunTest (const std::string &name, ResultsType &result)
Runs a test specified by name.
virtual void ProcessTests (std::list< std::string > &test_names, ResultsType &result)
Runs a list of tests specified by name.
Protected Attributes
std::string ExampleTestFixture
A sample string test fixture.
std::vector< int > N
A set of values for testing quadrature methods.
Private Types
typedef
IRAD::Util::TestingObject
< ResultsType > TestingObjectBaseType
Detailed Description
template<typename ResultsType>
class Rocstar::TestingObject< ResultsType >
Project-specific testing object.
The project-specific testing object encapsulates all tests for the project. This is the interface to all testing available for the given project. It implements the interface given by IRAD::Util::TestingObject.
Every project should define a "TestingObject" which implements (or interfaces) all of the tests for the project. If necessary (e.g. for parallel tests through batch systems), this is the object responsible for spawning off children processes to conduct parallel tests and for gathering the results of those tests.
Definition at line 71 of file RocstarTest.H.
Member Typedef Documentation
typedef IRAD::Util::TestingObject<ResultsType> TestingObjectBaseType private
Definition at line 73 of file RocstarTest.H.
Constructor & Destructor Documentation
TestingObject () inline
Default constructor.
Definition at line 91 of file RocstarTest.H.
 : TestingObjectBaseType() {};
Member Function Documentation
virtual void Epilogue () inline virtual
Tears down the testing fixtures if needed.
Definition at line 96 of file RocstarTest.H.
Referenced by TestingObject< ResultsType >::Process(), TestingObject< ResultsType >::ProcessTests(), and TestingObject< ResultsType >::RunTest().
 {};
double F1 (double x) inline
Simple test function fixture returns .
F1 is a 1st order function in x that has unity integral over [0,1].
Definition at line 114 of file RocstarTest.H.
 { return (2.0*x); };
double F2 (double x) inline
Simple test function fixture returns .
F2 is quadratic function in x and integrates to unity over [0,1].
Definition at line 120 of file RocstarTest.H.
 { return (3.0*x*x); };
virtual void Process (ResultsType & result) inline virtual
Runs all tests implemented by the Rocstar::TestingObject.
Parameters
result Rocstar::TestResults object to store test results.
Definition at line 255 of file RocstarTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__ExampleFunction(), TestingObject< ResultsType >::Test__MidPointQuadrature(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
Referenced by Rocstar::Test().
{
       Prologue();
       Test__ExampleFunction(result);
       Test__TrapezoidQuadrature(result);
       Test__MidPointQuadrature(result);
       Epilogue();
     }
virtual void ProcessTests (std::list< std::string > & test_names, ResultsType & result) inline virtual
Runs a list of tests specified by name.
Parameters
test_names list of string test names
result Rocstar::TestResults object to store test results.
Definition at line 287 of file RocstarTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), and TestingObject< ResultsType >::RunTest().
{
       Prologue();
       std::list<std::string>::iterator tni = test_names.begin();
       while(tni != test_names.end())
         RunTest(*tni++,result);
       Epilogue();
     }
virtual void Prologue () inline virtual
Sets up the data fixtures for the tests.
This function gives the object a chance to allocate and set up any "fixtures" before the tests are run.
Definition at line 105 of file RocstarTest.H.
References TestingObject< ResultsType >::ExampleTestFixture, i, and TestingObject< ResultsType >::N.
Referenced by TestingObject< ResultsType >::Process(), TestingObject< ResultsType >::ProcessTests(), and TestingObject< ResultsType >::RunTest().
{
       ExampleTestFixture.assign("ExampleTestData");
       for(int i = 10;i < 10000000;i*=10) N.push_back(i);
     }
virtual void RunTest (const std::string & name, ResultsType & result) inline virtual
Runs a test specified by name.
Parameters
name String name of the test to run.
result Rocstar::TestResults object to store test results.
Definition at line 269 of file RocstarTest.H.
References TestingObject< ResultsType >::Epilogue(), TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__ExampleFunction(), TestingObject< ResultsType >::Test__MidPointQuadrature(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
Referenced by TestingObject< ResultsType >::ProcessTests(), and Rocstar::Test().
     {
       Prologue();
       if(name == "ExampleFunction")
         Test__ExampleFunction(result);
       else if(name == "TrapezoidQuadrature")
         Test__TrapezoidQuadrature(result);
       else if(name == "MidPointQuadrature")
         Test__MidPointQuadrature(result);
       Epilogue();
     }
virtual void Test__ExampleFunction (ResultsType & result) inline virtual
Test for Rocstar::ExampleFunction.
Parameters
result Rocstar::TestResults object to store test results.
This function implements a simple test of the function Rocstar::ExampleFunction - which is designed to simply return a copy of the input string.
Definition at line 130 of file RocstarTest.H.
References GridConversion::ExampleFunction(), and TestingObject< ResultsType >::ExampleTestFixture.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       // This is an actual test of the function called
       // ExampleFunction.   The name Test__XXXXX will
       // eventually help automated utilities with
       // running tests by name.
       std::string ExampleResult(ExampleFunction(ExampleTestFixture));
       result.UpdateResult("ExampleFunction:Works",
                           ExampleResult == ExampleTestFixture);
       result.UpdateResult("ExampleFunction:Fails",
                           ExampleResult != ExampleTestFixture);
     }
virtual void Test__MidPointQuadrature (ResultsType & result) inline virtual
Test for Rocstar::MidPointQuadrature.
Parameters
result Rocstar::TestResults object to store test results.
This function implements a simple test of the function Rocstar::MidPointQuadrature - which is designed to integrate a function, f, over an interval .
The test first makes sure that the method integrates a linear function exactly, and then that the error term has the proper dependence on the spacings.
Definition at line 207 of file RocstarTest.H.
References NTS::abs(), Rocstar::TestFixture::F1(), Rocstar::TestFixture::F2(), i, cimg_library::log(), GridConversion::MidPointQuadrature(), and TestingObject< ResultsType >::N.
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       std::vector<double> Ibar;
       std::vector<double> E;
       size_t n = 2*N.size();
       bool runs = true;
       bool order2 = true;
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = Rocstar::MidPointQuadrature(TestFixture::F1,0,1,*i);
         } catch (...) {
           runs = false;
         }
         Ibar.push_back(Ii);
         E.push_back(std::fabs(Ii-1.0));
       }
       order2 = (E[0] < 1e-14);
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = Rocstar::MidPointQuadrature(TestFixture::F2,0,1,*i);
         } catch (...) {
           runs = false;
         }
         Ibar.push_back(Ii);
         E.push_back(std::fabs(Ii-1.0));
       }
       result.UpdateResult("MidPointQuadrature:Runs",runs);
       result.UpdateResult("MidPointQuadrature:Accurate",E[n-1] < 1e-12);
       for(int i = N.size();i < n - 1;i++){
         double e = E[i+1]/E[i];
         double n1 = static_cast<double>(N[i-N.size()])/static_cast<double>(N[(i-N.size())+1]);
         double p = std::log(e)/std::log(n1);
         p -= 2;
         p = std::abs(p);
         if(p > 1e-2){
           order2 = false;
         }
       }
       result.UpdateResult("MidPointQuadrature:Order2",order2);
     }
virtual void Test__TrapezoidQuadrature (ResultsType & result) inline virtual
Test for Rocstar::TrapezoidQuadrature.
Parameters
result Rocstar::TestResults object to store test results.
This function implements a simple test of the function Rocstar::TrapezoidQuadrature - which is designed to integrate a function, f, over an n-way partitioned interval .
The test first makes sure that the method integrates a linear function exactly, and then that the error term has the proper dependence on the spacings.
Definition at line 155 of file RocstarTest.H.
References NTS::abs(), Rocstar::TestFixture::F1(), Rocstar::TestFixture::F2(), i, cimg_library::log(), TestingObject< ResultsType >::N, and GridConversion::TrapezoidQuadrature().
Referenced by TestingObject< ResultsType >::Process(), and TestingObject< ResultsType >::RunTest().
{
       std::ostringstream Ostr;
       std::vector<double> E;
       size_t n = 2*N.size();
       bool runs = true;
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = Rocstar::TrapezoidQuadrature(TestFixture::F1,0,1,*i);
         } catch (...) {
           runs = false;
         }
         E.push_back(std::fabs(Ii-1.0));
       }
       bool order2 = (E[0] < 1e-14);
       for(std::vector<int>::iterator i = N.begin();i != N.end();i++){
         double Ii = 0.0;
         try {
           Ii = Rocstar::TrapezoidQuadrature(TestFixture::F2,0,1,*i);
         } catch (...) {
           runs = false;
         }
         E.push_back(std::fabs(Ii-1.0));
       }
       result.UpdateResult("TrapezoidQuadrature:Runs",runs);
       result.UpdateResult("TrapezoidQuadrature:Accurate",E[n-1] < 1e-12);
       for(int i = N.size();i < n - 1;i++){
         double e = E[i+1]/E[i];
         double n1 = static_cast<double>(N[i-N.size()])/static_cast<double>(N[(i-N.size())+1]);
         double p = std::log(e)/std::log(n1);
         p -= 2;
         p = std::abs(p);
         if(p > 2e-2){
           order2 = false;
         }
       }
       result.UpdateResult("TrapezoidQuadrature:Order2",order2);
     }
Member Data Documentation
std::string ExampleTestFixture protected
A sample string test fixture.
Definition at line 82 of file RocstarTest.H.
Referenced by TestingObject< ResultsType >::Prologue(), and TestingObject< ResultsType >::Test__ExampleFunction().
std::vector<int> N protected
A set of values for testing quadrature methods.
Definition at line 86 of file RocstarTest.H.
Referenced by TestingObject< ResultsType >::Prologue(), TestingObject< ResultsType >::Test__MidPointQuadrature(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
The documentation for this class was generated from the following file:
RocstarTest.H