Rocstar: MeshTransform Class Reference
MeshTransform Class Reference
#include <MeshTransform.hpp>
Public Member Functions
MeshTransform (Matrix3D &in_mat, Vector3D &in_vec, MsqError &err)
virtual ~MeshTransform ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
Loop over the mesh and perform the affine transformation.
virtual msq_std::string get_name ()
Return the name of this PatchDataUser: Mesh Transform.
virtual AlgorithmType get_algorithm_type ()
Return the AlgorithmType of thsi PatchDataUser: MESH_TRANSFORM.
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1, int param2)
MeshTransform is built to use ELEMETNS_ON_VERTEX_PATCH with a depth one.
MeshTransform (Matrix3D &in_mat, Vector3D &in_vec, MsqError &err)
virtual ~MeshTransform ()
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
Loop over the mesh and perform the affine transformation.
virtual msq_std::string get_name ()
Return the name of this PatchDataUser: Mesh Transform.
virtual AlgorithmType get_algorithm_type ()
Return the AlgorithmType of thsi PatchDataUser: MESH_TRANSFORM.
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1, int param2)
MeshTransform is built to use ELEMETNS_ON_VERTEX_PATCH with a depth one.
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Private Attributes
Matrix3D mMat
Vector3D mVec
Matrix for the affine transformation.
Additional Inherited Members
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Detailed Description
Perform an Affine transformation on Mesh vertex positions. Essentially define the new vertex position, v_new, from the original vertex position, v_old, s.t. v_new = (mMat * v_old) + mVec, where mMat is a constant matrix and mVec is a constant vector.
Definition at line 58 of file includeLinks/MeshTransform.hpp.
Constructor & Destructor Documentation
MeshTransform (Matrix3D & in_mat, Vector3D & in_vec, MsqError & err)
Constructor sets the matrix and the vector for the affine transformation. It also sets the patch type and culling method. My default the patches are just created such that a patch is created around each vertex but no elements are added to the patch (each patch consists of a single vertex, ELEMENTS_ON_VERTEX_PATCH with a layer depth of 1).
Definition at line 50 of file Misc/MeshTransform.cpp.
References PatchData::ELEMENTS_ON_VERTEX_PATCH, MeshTransform::mMat, MeshTransform::mVec, PatchDataUser::no_culling_method(), and MeshTransform::set_patch_type().
   {
     mMat = in_mat;
     mVec = in_vec;
     set_patch_type(PatchData::ELEMENTS_ON_VERTEX_PATCH ,err, 0, 1);
     no_culling_method();
   }
virtual ~MeshTransform () inline virtual
Definition at line 64 of file includeLinks/MeshTransform.hpp.
 { };
MeshTransform (Matrix3D & in_mat, Vector3D & in_vec, MsqError & err)
virtual ~MeshTransform () inline virtual
Definition at line 64 of file src/Misc/MeshTransform.hpp.
 { };
Member Function Documentation
virtual AlgorithmType get_algorithm_type () inline virtual
Return the AlgorithmType of thsi PatchDataUser: MESH_TRANSFORM.
Implements PatchDataUser.
Definition at line 71 of file includeLinks/MeshTransform.hpp.
References PatchDataUser::MESH_TRANSFORM.
 { return MESH_TRANSFORM; }
virtual AlgorithmType get_algorithm_type () inline virtual
Return the AlgorithmType of thsi PatchDataUser: MESH_TRANSFORM.
Implements PatchDataUser.
Definition at line 71 of file src/Misc/MeshTransform.hpp.
References PatchDataUser::MESH_TRANSFORM.
 { return MESH_TRANSFORM; }
virtual msq_std::string get_name () inline virtual
Return the name of this PatchDataUser: Mesh Transform.
Implements PatchDataUser.
Definition at line 69 of file includeLinks/MeshTransform.hpp.
 { return "Mesh Transform.";}
virtual msq_std::string get_name () inline virtual
Return the name of this PatchDataUser: Mesh Transform.
Implements PatchDataUser.
Definition at line 69 of file src/Misc/MeshTransform.hpp.
 { return "Mesh Transform.";}
virtual double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
Loop over the mesh and perform the affine transformation.
Implements PatchDataUser.
double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
Loop over the mesh and perform the affine transformation.
Actually apply the affine transformation
Parameters
const MeshSet &: this MeshSet is looped over. Only the mutable data members are changed (such as currentVertexInd).
Implements PatchDataUser.
Definition at line 72 of file Misc/MeshTransform.cpp.
References PatchData::ELEMENTS_ON_VERTEX_PATCH, MeshSet::get_next_patch(), PatchDataUser::get_patch_type(), PatchData::get_vertex_array(), MsqError::INVALID_STATE, MeshTransform::mMat, MSQ_SETERR, MeshTransform::mVec, PatchData::num_vertices(), and PatchData::update_mesh().
   {
       //This shouldn't be an issue, but make sure the patch type is still
       //correct.
     if(get_patch_type() != PatchData::ELEMENTS_ON_VERTEX_PATCH){
       MSQ_SETERR(err)("Incorrect patch type being used.\n",
                       MsqError::INVALID_STATE );
       return 1.;
     }
       //get the first patch
     PatchData patch_data;
     bool next_patch=ms.get_next_patch(patch_data, this, err);
     assert(!err);
     if(err)
       return 1.0;
       //loop over the patches (ie, loop over the vertices.
     while( next_patch )
     {
         //make sure we have a vertex.
       if(patch_data.num_vertices()!=1){
         MSQ_SETERR(err)( "Incorrect patch depth being used.",
                          MsqError::INVALID_STATE );
         return 1.;
       }
       MsqVertex* vert_array = patch_data.get_vertex_array(err);
       if(err)
         return 1.0;
         //perform the affine transormation
       Vector3D temp_vec = vert_array[0];
       vert_array[0]=mMat*temp_vec+mVec;
         //update the vertex postion
       patch_data.update_mesh(err);
         //get the next patch
       next_patch =  ms.get_next_patch(patch_data, this, err);
       if(err)
         return 1.0;
     }
       //return
     return 0.;
   }
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError & err, int param1, int param2) virtual
MeshTransform is built to use ELEMETNS_ON_VERTEX_PATCH with a depth one.
We implement set_patch_type to ensure this is the patch that is used.
Reimplemented from PatchDataUser.
void set_patch_type (PatchData::PatchType patch_type, MsqError & err, int param1 = 0, int param2 = 0) virtual
MeshTransform is built to use ELEMETNS_ON_VERTEX_PATCH with a depth one.
We implement set_patch_type to ensure this is the patch that is used.
Reimplemented from PatchDataUser.
Definition at line 57 of file Misc/MeshTransform.cpp.
References PatchData::ELEMENTS_ON_VERTEX_PATCH, MsqError::INVALID_ARG, MSQ_SETERR, and PatchDataUser::set_patch_type().
Referenced by MeshTransform::MeshTransform().
{
     if(patch_type != PatchData::ELEMENTS_ON_VERTEX_PATCH ||
        param1 != 0){
       MSQ_SETERR(err)("Patch type must be ELEMENTS_ON_VERTEX_PATCH, depth 1.\n", MsqError::INVALID_ARG);
     }
     PatchDataUser::set_patch_type(PatchData::ELEMENTS_ON_VERTEX_PATCH ,err,
                                   0, param2);
   }
Member Data Documentation
Matrix3D mMat private
Definition at line 79 of file includeLinks/MeshTransform.hpp.
Referenced by MeshTransform::loop_over_mesh(), and MeshTransform::MeshTransform().
Vector3D mVec private
Matrix for the affine transformation.
Definition at line 80 of file includeLinks/MeshTransform.hpp.
Referenced by MeshTransform::loop_over_mesh(), and MeshTransform::MeshTransform().
The documentation for this class was generated from the following files:
includeLinks/MeshTransform.hpp
Misc/MeshTransform.cpp