Rocstar: plag_rflu_modfindcells Module Reference
plag_rflu_modfindcells Module Reference
Public Member Functions
subroutine, public plag_rflu_computedisttot (pRegion)
subroutine, public plag_rflu_findcellsbrute (pRegion)
subroutine, public plag_rflu_findcellsbrutemod (pRegion)
subroutine, public plag_rflu_findcellslohner (pRegion)
subroutine, public plag_rflu_findcellsoct (pRegion)
subroutine plag_rflu_findcellsoctkernel (pRegion, xLoc, yLoc, zLoc, xMin, xMax, yMin, yMax, zMin, zMax, icgOut)
subroutine, public plag_rflu_findcellsoctmod (pRegion)
subroutine, public plag_rflu_findcellstrajfast (pRegion, iPclBeg, iPclEnd)
subroutine, public plag_rflu_findcellstrajsafe (pRegion, iPclBeg, iPclEnd)
Private Member Functions
subroutine plag_rflu_findcellsbrutekernel (pRegion, xLoc, yLoc, zLoc, icgOut)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: PLAG_RFLU_ModFindCells.F90,v $ $Revision: 1.16 $'
Detailed Description
Definition at line 39 of file PLAG_RFLU_ModFindCells.F90.
Member Function/Subroutine Documentation
subroutine, public plag_rflu_computedisttot (type(t_region), pointer pRegion)
Definition at line 120 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and sqrt().
Referenced by plag_rflu_update().
subroutine, public plag_rflu_findcellsbrute (type(t_region), pointer pRegion)
Definition at line 220 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modincelltest::rflu_ict_testincell().
subroutine plag_rflu_findcellsbrutekernel (type(t_region), pointer pRegion, real(rfreal), intent(in) xLoc, real(rfreal), intent(in) yLoc, real(rfreal), intent(in) zLoc, integer, intent(out) icgOut) private
Definition at line 335 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modincelltest::rflu_ict_testincell().
Referenced by plag_rflu_findcellsbrutemod().
subroutine, public plag_rflu_findcellsbrutemod (type(t_region), pointer pRegion)
Definition at line 422 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_rflu_findcellsbrutekernel(), moderror::registerfunction(), and rflu_modincelltest::rflu_ict_testincell().
Referenced by plag_rflu_update().
subroutine, public plag_rflu_findcellslohner (type(t_region), pointer pRegion)
Definition at line 546 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modcellfaceedgeinfo::rflu_getfacekind(), rflu_modcellfaceedgeinfo::rflu_getglobalcellkind(), and rflu_modincelltest::rflu_ict_testincelllohner().
Referenced by plag_rflu_update().
subroutine, public plag_rflu_findcellsoct (type(t_region), pointer pRegion)
Definition at line 715 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), min(), moderror::registerfunction(), rflu_modoctree::rflu_buildoctree(), rflu_modoctree::rflu_createoctree(), rflu_modoctree::rflu_destroyoctree(), rflu_modincelltest::rflu_ict_testincell(), rflu_modoctree::rflu_queryoctree(), rflu_modgeometrytools::rflu_testinboundbox(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
subroutine plag_rflu_findcellsoctkernel (type(t_region), pointer pRegion, real(rfreal), intent(in) xLoc, real(rfreal), intent(in) yLoc, real(rfreal), intent(in) zLoc, real(rfreal), intent(in) xMin, real(rfreal), intent(in) xMax, real(rfreal), intent(in) yMin, real(rfreal), intent(in) yMax, real(rfreal), intent(in) zMin, real(rfreal), intent(in) zMax, integer, intent(inout) icgOut)
Definition at line 915 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), min(), moderror::registerfunction(), rflu_modincelltest::rflu_ict_testincell(), rflu_modoctree::rflu_queryoctree(), rflu_modgeometrytools::rflu_testinboundbox(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
subroutine, public plag_rflu_findcellsoctmod (type(t_region), pointer pRegion)
Definition at line 1065 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), min(), moderror::registerfunction(), rflu_modoctree::rflu_buildoctree(), rflu_modoctree::rflu_createoctree(), rflu_modoctree::rflu_destroyoctree(), rflu_modincelltest::rflu_ict_testincell(), rflu_modoctree::rflu_queryoctree(), rflu_modgeometrytools::rflu_testinboundbox(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by plag_rflu_update().
subroutine, public plag_rflu_findcellstrajfast (type(t_region), pointer pRegion, integer iPclBeg, integer iPclEnd)
Definition at line 1286 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), plag_modsurfstats::plag_gathersurfstats(), plag_reflectparticledata(), moderror::registerfunction(), rflu_modgeometrytools::rflu_computelinecellxsectfast(), rflu_modcellfaceedgeinfo::rflu_getfacekind(), rflu_modcellfaceedgeinfo::rflu_getglobalcellkind(), rflu_modincelltest::rflu_ict_testincellfancy(), rflu_modmpi::rflu_mpi_recreatebufferipclsend(), rflu_modrelatedpatches::rflu_relp_transformvector(), and sqrt().
Referenced by plag_rflu_modcomm::plag_rflu_commdriver(), and plag_rflu_update().
subroutine, public plag_rflu_findcellstrajsafe (type(t_region), pointer pRegion, integer iPclBeg, integer iPclEnd)
Definition at line 1659 of file PLAG_RFLU_ModFindCells.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), plag_modsurfstats::plag_gathersurfstats(), plag_reflectparticledata(), moderror::registerfunction(), rflu_modgeometrytools::rflu_computelinecellxsectsafe(), rflu_modcellfaceedgeinfo::rflu_getfacekind(), rflu_modcellfaceedgeinfo::rflu_getglobalcellkind(), rflu_modincelltest::rflu_ict_testincellfancy(), rflu_modmpi::rflu_mpi_recreatebufferipclsend(), rflu_modrelatedpatches::rflu_relp_transformvector(), and sqrt().
Referenced by plag_rflu_modcomm::plag_rflu_commdriver(), and plag_rflu_update().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: PLAG_RFLU_ModFindCells.F90,v $ $Revision: 1.16 $' private
Definition at line 86 of file PLAG_RFLU_ModFindCells.F90.
The documentation for this module was generated from the following file:
PLAG_RFLU_ModFindCells.F90