Rocstar: rflu_moddifferentiationfaces Module Reference
rflu_moddifferentiationfaces Module Reference
Public Member Functions
subroutine, public rflu_computegradfacesconstr (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, varInfo, var, grad)
subroutine, public rflu_computegradfaceswrapper (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
subroutine, public rflu_computegradconstrained (global, dimens, nCellMembs, nBFaceMembs, order, dra, drb, rhsa, rhsb, gradLocal)
Private Member Functions
subroutine rflu_computegradfaces (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModDifferentiationFaces.F90,v $ $Revision: 1.9 $'
Detailed Description
Definition at line 39 of file RFLU_ModDifferentiationFaces.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_computegradconstrained (type(t_global), pointer global, integer, intent(in) dimens, integer nCellMembs, integer nBFaceMembs, integer order, real(rfreal), dimension(xcoord:zcoord,ncellmembs) dra, real(rfreal), dimension(xcoord:zcoord,nbfacemembs) drb, real(rfreal), dimension(ncellmembs) rhsa, real(rfreal), dimension(nbfacemembs) rhsb, real(rfreal), dimension(xcoord:xyzmag) gradLocal)
Definition at line 913 of file RFLU_ModDifferentiationFaces.F90.
References Line_2< R, T >::a(), Color::b(), modtools::compfact(), moderror::deregisterfunction(), moderror::errorstop(), j, max(), Generic_element_2::order(), Color::r(), moderror::registerfunction(), rflu_computestencilsize(), and Kdtree_d< Traits >::ExtPoint::term().
subroutine rflu_computegradfaces (type(t_region), pointer pRegion, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 105 of file RFLU_ModDifferentiationFaces.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_computegradfaceswrapper().
subroutine, public rflu_computegradfacesconstr (type(t_region), pointer pRegion, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, integer, dimension(ibegvar:iendvar), intent(in) varInfo, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 382 of file RFLU_ModDifferentiationFaces.F90.
References Line_2< R, T >::a(), ainv(), moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), max(), moderror::registerfunction(), rflu_modconstraintutils::rflu_getconstrtype(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_invertmatrixsvd(), sqrt(), StopWatch::stop(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modresidual::rflu_res_computeresidual(), viscousfluxes(), and viscousfluxesmp().
subroutine, public rflu_computegradfaceswrapper (type(t_region), pointer pRegion, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 827 of file RFLU_ModDifferentiationFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_computegradfaces().
Referenced by rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modresidual::rflu_res_computeresidual(), turb_lesgeteddyvis(), turb_ranssavisflux(), viscousfluxes(), and viscousfluxesmp().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModDifferentiationFaces.F90,v $ $Revision: 1.9 $' private
Definition at line 63 of file RFLU_ModDifferentiationFaces.F90.
The documentation for this module was generated from the following file:
RFLU_ModDifferentiationFaces.F90