Rocstar: rflo_modextrapolation Module Reference
rflo_modextrapolation Module Reference
Public Member Functions
subroutine, public rflo_extrapregdummynode (ibeg, iend, jbeg, jend, kbeg, kend, ndum, iNOff, ijNOff, idb, ide, var)
subroutine, public rflo_extrapreglastnode (ibeg, iend, jbeg, jend, kbeg, kend, iNOff, ijNOff, idb, ide, var)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModExtrapolation.F90,v $ $Revision: 1.3 $'
Detailed Description
Definition at line 37 of file RFLO_ModExtrapolation.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_extrapregdummynode (integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer ndum, integer iNOff, integer ijNOff, integer idb, integer ide, real(rfreal), dimension(:,:), pointer var)
Definition at line 88 of file RFLO_ModExtrapolation.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolmap3d().
subroutine, public rflo_extrapreglastnode (integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer iNOff, integer ijNOff, integer idb, integer ide, real(rfreal), dimension(:,:), pointer var)
Definition at line 195 of file RFLO_ModExtrapolation.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and StopWatch::stop().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModExtrapolation.F90,v $ $Revision: 1.3 $' private
Definition at line 60 of file RFLO_ModExtrapolation.F90.
The documentation for this module was generated from the following file:
RFLO_ModExtrapolation.F90