Rocstar: FloGridBlock Class Reference
FloGridBlock Class Reference
#include <FloGrid.H>
Public Member Functions
FloGridBlock ()
FloGridBlock (unsigned int i, unsigned int j, unsigned int k)
FloGridBlock (const FloGridBlock &inblock)
void DestroyGrid ()
void SetGhostLayers (unsigned int n)
unsigned int NGhostLayers () const
int CreateSoln ()
unsigned int NNodes () const
unsigned int NumCells () const
unsigned int NTotalCells () const
std::vector< double > & Solution ()
const std::vector< double > & Solution () const
void FloLayout ()
void MeshLayout ()
FloGridBlock & operator= (const FloGridBlock &inblock)
unsigned int isize () const
unsigned int jsize () const
unsigned int ksize () const
unsigned int * NCells ()
const unsigned int * NCells () const
void Resize (unsigned int i, unsigned int j, unsigned int k)
void ResizeSoln (unsigned int i, unsigned int j, unsigned int k, unsigned int ng)
std::vector< double > & Coords ()
const std::vector< double > & Coords () const
int ReadBlock (std::istream &BlockIn)
int ReadBlockSoln (std::istream &BlockSolnIn)
int WriteBlockSoln (std::ostream &Ouf)
Protected Attributes
unsigned int _ncells [3]
std::vector< double > _incoords
unsigned int _ng
std::vector< double > _soln
unsigned int _grid_no
Private Attributes
bool flolayout
Detailed Description
Definition at line 27 of file FloGrid.H.
Constructor & Destructor Documentation
FloGridBlock () inline
Definition at line 37 of file FloGrid.H.
References _grid_no, _incoords, _ncells, _ng, _soln, and flolayout.
   {
     _ncells[0] = _ncells[1] = _ncells[2] = _ng = 0;
     _incoords.resize(0);
     _soln.resize(0);
     _grid_no = 0;
     flolayout = false;
   };
FloGridBlock (unsigned int i, unsigned int j, unsigned int k) inline
Definition at line 45 of file FloGrid.H.
References _grid_no, _incoords, _ncells, _ng, flolayout, i, j, and k.
   {
     _ncells[0] = i;
     _ncells[1] = j;
     _ncells[2] = k;
     _ng = 0;
     _grid_no = 0;
     _incoords.resize(3*(i+1)*(j+1)*(k+1));
     flolayout = false;
   };
FloGridBlock (const FloGridBlock & inblock) inline
Definition at line 55 of file FloGrid.H.
References _grid_no, _incoords, _ncells, _ng, _soln, flolayout, and ni.
   {
     _ncells[0] = inblock._ncells[0];
     _ncells[1] = inblock._ncells[1];
     _ncells[2] = inblock._ncells[2];
     _grid_no = inblock._grid_no;
     _incoords.resize(3*(inblock._ncells[0]+1)*(inblock._ncells[1]+1)*
                      (inblock._ncells[2]+1));
     std::vector<double>::const_iterator ii = inblock._incoords.begin();
     std::vector<double>::iterator ni = _incoords.begin();
     while(ni != _incoords.end())
       *ni++ = *ii++;
     flolayout = inblock.flolayout;
     _soln = inblock._soln;
     _ng = inblock._ng;
   };
Member Function Documentation
std::vector<double>& Coords () inline
Definition at line 161 of file FloGrid.H.
References _incoords.
 { return _incoords; };
const std::vector<double>& Coords () const inline
Definition at line 162 of file FloGrid.H.
References _incoords.
 { return _incoords; };
int CreateSoln () inline
Definition at line 82 of file FloGrid.H.
References _soln, and NTotalCells().
   {
     _soln.resize(5*NTotalCells());
   };
void DestroyGrid () inline
Definition at line 71 of file FloGrid.H.
References _incoords, and swap().
   {
     _incoords.resize(0);
     // release the memory for real...
     std::vector<double>(_incoords).swap(_incoords);
   };
void FloLayout () inline
Definition at line 91 of file FloGrid.H.
References _incoords, flolayout, i, and NNodes().
   {
     if(!flolayout){
       flolayout = true;
       unsigned int nnodes = NNodes();
       std::vector<double> coordcopy(3*nnodes);
       std::vector<double>::iterator ci = _incoords.begin();
       std::vector<double>::iterator cci = coordcopy.begin();
       while(ci != _incoords.end())
         *cci++ = *ci++;
       for(int i = 0;i < nnodes;i++){
         _incoords[i]   = coordcopy[3*i];
         _incoords[nnodes+i] = coordcopy[(3*i) + 1];
         _incoords[2*nnodes+i] = coordcopy[(3*i) + 2];
       }
     }
   };
unsigned int isize () const inline
Definition at line 143 of file FloGrid.H.
References _ncells.
 { return _ncells[0]; };
unsigned int jsize () const inline
Definition at line 144 of file FloGrid.H.
References _ncells.
 { return _ncells[1]; };
unsigned int ksize () const inline
Definition at line 145 of file FloGrid.H.
References _ncells.
Referenced by turb_flowlmupdateloglay().
 { return _ncells[2]; };
void MeshLayout () inline
Definition at line 109 of file FloGrid.H.
References _incoords, flolayout, i, and NNodes().
   {
     if(flolayout){
       flolayout = false;
       unsigned int nnodes = NNodes();
       std::vector<double> coordcopy(3*nnodes);
       std::vector<double>::iterator ci = _incoords.begin();
       std::vector<double>::iterator cci = coordcopy.begin();
       while(ci != _incoords.end())
         *cci++ = *ci++;
       for(int i = 0;i < nnodes;i++){
         _incoords[3*i]   = coordcopy[i];
         _incoords[3*i+1] = coordcopy[nnodes + i];
         _incoords[3*i+2] = coordcopy[(2*nnodes) + i];
       }
     }
   };
unsigned int* NCells () inline
Definition at line 146 of file FloGrid.H.
References _ncells.
 { return (_ncells); };
const unsigned int* NCells () const inline
Definition at line 147 of file FloGrid.H.
References _ncells.
 { return(_ncells); };
unsigned int NGhostLayers () const inline
Definition at line 81 of file FloGrid.H.
References _ng.
 {return (_ng); };
unsigned int NNodes () const inline
Definition at line 86 of file FloGrid.H.
References _ncells.
Referenced by FloLayout(), and MeshLayout().
 { return ((_ncells[0]+1)*(_ncells[1]+1)*(_ncells[2]+1)); };
unsigned int NTotalCells () const inline
Definition at line 88 of file FloGrid.H.
References _ncells, and _ng.
Referenced by CreateSoln().
 { return ((_ncells[0]+(2*_ng))*(_ncells[1]+(2*_ng))*(_ncells[2]+(2*_ng))); };
unsigned int NumCells () const inline
Definition at line 87 of file FloGrid.H.
References _ncells.
Referenced by ReadBlockSoln().
 { return (_ncells[0]*_ncells[1]*_ncells[2]); };
FloGridBlock& operator= (const FloGridBlock & inblock) inline
Definition at line 128 of file FloGrid.H.
References _incoords, _ncells, flolayout, and ni.
   {
     _ncells[0] = inblock._ncells[0];
     _ncells[1] = inblock._ncells[1];
     _ncells[2] = inblock._ncells[2];
     _incoords.resize(3*(inblock._ncells[0]+1)*(inblock._ncells[1]+1)*
                      (inblock._ncells[2]+1));
     std::vector<double>::const_iterator ii = inblock._incoords.begin();
     std::vector<double>::iterator ni = _incoords.begin();
     while(ni != _incoords.end())
       *ni++ = *ii++;
     flolayout = inblock.flolayout;
   };
int ReadBlock (std::istream & BlockIn) inline
Definition at line 163 of file FloGrid.H.
References _grid_no, _incoords, flolayout, max(), min(), ni, nj, nk, Resize(), CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by FloGrid::BlockCount(), FloGrid::ReadAllBlocks(), and FloGrid::ReadNBlocks().
   {
     std::string line;
     std::getline(BlockIn,line);
     if(line.empty())
       return(1);
     std::istringstream Istr(line);
     unsigned int ni      = 0;
     unsigned int nj      = 0;
     unsigned int nk      = 0;
     Istr >> _grid_no >> ni >> nj >> nk;
     if((_grid_no <= 0) || (ni <= 0) || (nj <= 0) || (nk <= 0)){
       std::cout << "FloGridBlock::ReadBlock: Error reading block" << std::endl
                 << "FloGridBlock::ReadBlock: line:" << line << std::endl
                 << "FloGridBlock::ReadBlock: grid no: " << _grid_no << "ni = " << ni
                 << " nj = " << nj << " nk = " << nk << std::endl;
       return(1);
     }
     unsigned int number_of_nodes = (ni+1)*(nj+1)*(nk+1);
     //    std::cout << "Partition " << grid_no << ": (" << ni
     //        << "," << nj << "," << nk << ")" << std::endl
     //        << "npts = " << number_of_nodes << std::endl;
     this->Resize(ni,nj,nk);
     double VERYSMALL = std::numeric_limits<double>::min();
     double VERYLARGE = std::numeric_limits<double>::max();
     std::vector<double>::iterator ici = _incoords.begin();
     while(ici != _incoords.end())
       BlockIn >> *ici++;
     std::getline(BlockIn,line);
     GeoPrim::CPoint minp(VERYLARGE,VERYLARGE,VERYLARGE);
     GeoPrim::CPoint maxp(-1.0*VERYLARGE,-1.0*VERYLARGE,-1.0*VERYLARGE);
     ici = _incoords.begin();
     unsigned int ncount = 0;
     while(ici != _incoords.end()){
       double *minval = NULL;
       double *maxval = NULL;
       double value = *ici++;
       if(ncount < number_of_nodes){
         minval = &minp.x();
         maxval = &maxp.x();
       }
       else if(ncount < 2*number_of_nodes){
         minval = &minp.y();
         maxval = &maxp.y();
       }
       else {
         minval = &minp.z();
         maxval = &maxp.z();
       }
       ncount++;
       if (value < *minval)
         *minval = value;
       if (value > *maxval)
         *maxval = value;
     }
     //    std::cout << "Mesh limits: " << std::endl
     //        << "Minimum point: " << minp << std::endl
     //      << "Maximum point: " << maxp << std::endl;
     flolayout = true;
     return(0);
   };
int ReadBlockSoln (std::istream & BlockSolnIn) inline
Definition at line 224 of file FloGrid.H.
References _grid_no, _soln, ni, nj, nk, NumCells(), and ResizeSoln().
   {
     std::string line;
     std::getline(BlockSolnIn,line);
     if(line.empty())
       return(1);
     std::istringstream Istr(line);
     unsigned int grid_no = 0;
     unsigned int ni      = 0;
     unsigned int nj      = 0;
     unsigned int nk      = 0;
     unsigned int ng      = 0;
     Istr >> grid_no >> ni >> nj >> nk >> ng;
     if(_grid_no != grid_no) std::cout << "grid " << _grid_no << " tried to read soln for block " << grid_no << std::endl;
     assert(_grid_no == grid_no);
     if((grid_no <= 0) || (ni <= 0) || (nj <= 0) || (nk <= 0)){
       std::cout << "FloGridBlock::ReadBlockSoln: Error reading block" << std::endl
                 << "FloGridBlock::ReadBlockSoln: line:" << line << std::endl
                 << "FloGridBlock::ReadBlockSoln: grid no: " << grid_no << "ni = " << ni
                 << " nj = " << nj << " nk = " << nk << std::endl;
       return(1);
     }
     unsigned int number_of_total_cells = (ni+(2*ng))*(nj+(2*ng))*(nk+(2*ng));
     unsigned int number_of_real_cells  = (ni*nj*nk);
     assert(number_of_real_cells == NumCells());
     //    std::cout << "Partition " << grid_no << ": (" << ni
     //        << "," << nj << "," << nk << ")" << std::endl
     //        << "npts = " << number_of_nodes << std::endl;
     this->ResizeSoln(ni,nj,nk,ng);
     std::vector<double>::iterator ici = _soln.begin();
     while(ici != _soln.end())
       BlockSolnIn >> *ici++;
     std::getline(BlockSolnIn,line);
     return(0);
   };
void Resize (unsigned int i, unsigned int j, unsigned int k) inline
Definition at line 148 of file FloGrid.H.
References _incoords, _ncells, flolayout, i, j, and k.
Referenced by ReadBlock().
   {
     _ncells[0] = i; _ncells[1] = j; _ncells[2] = k;
     _incoords.resize(3*(i+1)*(j+1)*(k+1));
     flolayout = false;
   };
void ResizeSoln (unsigned int i, unsigned int j, unsigned int k, unsigned int ng) inline
Definition at line 154 of file FloGrid.H.
References _ncells, _ng, _soln, i, j, and k.
Referenced by ReadBlockSoln().
   {
     _ncells[0] = i; _ncells[1] = j; _ncells[2] = k;
     _ng = ng;
     _soln.resize(5*((i+(2*ng))*(j+(2*ng))*(k+(2*ng))));
     //    flolayout = false;
   };
void SetGhostLayers (unsigned int n) inline
Definition at line 77 of file FloGrid.H.
References _ng.
   {
     _ng = n;
   };
std::vector<double>& Solution () inline
Definition at line 89 of file FloGrid.H.
References _soln.
 { return (_soln); };
const std::vector<double>& Solution () const inline
Definition at line 90 of file FloGrid.H.
References _soln.
 { return (_soln); };
int WriteBlockSoln (std::ostream & Ouf) inline
Definition at line 259 of file FloGrid.H.
References _grid_no, _ncells, _ng, and _soln.
   {
     std::ostringstream Ostr;
     Ostr << _grid_no << " " << _ncells[0] << " " << _ncells[1]
         << " " << _ncells[2] << " " << _ng << std::endl;
     std::vector<double>::iterator si = _soln.begin();
     while(si != _soln.end()){
       Ostr << std::scientific << std::setprecision(16) << *si++ << " ";
     }
     Ostr << std::endl;
     Ouf << Ostr.str();
     return(Ostr.str().size());
   };
Member Data Documentation
unsigned int _grid_no protected
Definition at line 33 of file FloGrid.H.
Referenced by FloGridBlock(), ReadBlock(), ReadBlockSoln(), and WriteBlockSoln().
std::vector<double> _incoords protected
Definition at line 30 of file FloGrid.H.
Referenced by Coords(), DestroyGrid(), FloGridBlock(), FloLayout(), MeshLayout(), operator=(), ReadBlock(), and Resize().
unsigned int _ncells[3] protected
Definition at line 29 of file FloGrid.H.
Referenced by FloGridBlock(), isize(), jsize(), ksize(), NCells(), NNodes(), NTotalCells(), NumCells(), operator=(), Resize(), ResizeSoln(), and WriteBlockSoln().
unsigned int _ng protected
Definition at line 31 of file FloGrid.H.
Referenced by FloGridBlock(), NGhostLayers(), NTotalCells(), ResizeSoln(), SetGhostLayers(), and WriteBlockSoln().
std::vector<double> _soln protected
Definition at line 32 of file FloGrid.H.
Referenced by CreateSoln(), FloGridBlock(), ReadBlockSoln(), ResizeSoln(), Solution(), and WriteBlockSoln().
bool flolayout private
Definition at line 35 of file FloGrid.H.
Referenced by FloGridBlock(), FloLayout(), MeshLayout(), operator=(), ReadBlock(), and Resize().
The documentation for this class was generated from the following file:
FloGrid.H