Rocstar: rflu_modboundarytests Module Reference
rflu_modboundarytests Module Reference
Public Member Functions
logical function, public rflu_testisboundarycell (pRegion, icg)
logical function, public rflu_testisboundaryvertex (pRegion, ivg)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModBoundaryTests.F90,v $ $Revision: 1.3 $'
Detailed Description
Definition at line 40 of file RFLU_ModBoundaryTests.F90.
Member Function/Subroutine Documentation
logical function, public rflu_testisboundarycell (type(t_region), pointer pRegion, integer, intent(in) icg)
Definition at line 112 of file RFLU_ModBoundaryTests.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), and moderror::registerfunction().
Referenced by rflu_computeexactflowerror().
logical function, public rflu_testisboundaryvertex (type(t_region), pointer pRegion, integer, intent(in) ivg)
Definition at line 220 of file RFLU_ModBoundaryTests.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modgridutils::rflu_distortgrid().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModBoundaryTests.F90,v $ $Revision: 1.3 $' private
Definition at line 63 of file RFLU_ModBoundaryTests.F90.
The documentation for this module was generated from the following file:
RFLU_ModBoundaryTests.F90