Rocstar: Line_2_Line_2_pair< R > Class Template Reference
Line_2_Line_2_pair< R > Class Template Reference
#include <Line_2_Line_2_intersection.h>
Public Types
enum Intersection_results { NO, POINT, LINE }
Public Member Functions
Line_2_Line_2_pair ()
Line_2_Line_2_pair (Line_2< R > const *line1, Line_2< R > const *line2)
~Line_2_Line_2_pair ()
Intersection_results intersection_type () const
bool intersection (Point_2< R > &result) const
bool intersection (Line_2< R > &result) const
Protected Attributes
Line_2< R > const * _line1
Line_2< R > const * _line2
bool _known
Intersection_results _result
Point_2< R > _intersection_point
Detailed Description
template<class R>
class Line_2_Line_2_pair< R >
Definition at line 61 of file Line_2_Line_2_intersection.h.
Member Enumeration Documentation
enum Intersection_results
Enumerator
NO
POINT
LINE
Definition at line 63 of file Line_2_Line_2_intersection.h.
 {NO, POINT, LINE};
Constructor & Destructor Documentation
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE Line_2_Line_2_pair ()
Definition at line 184 of file Line_2_Line_2_intersection.h.
 {
     _line1 = 0;
     _line2 = 0;
     _known = false;
 }
Line_2_Line_2_pair (Line_2< R > const * line1, Line_2< R > const * line2)
Definition at line 192 of file Line_2_Line_2_intersection.h.
 {
     _line1 = line1;
     _line2 = line2;
     _known = false;
 }
~Line_2_Line_2_pair () inline
Definition at line 67 of file Line_2_Line_2_intersection.h.
 {}
Member Function Documentation
bool intersection (Point_2< R > & result) const
Definition at line 244 of file Line_2_Line_2_intersection.h.
Referenced by Segment_2_Segment_2_pair< R >::intersection_type().
 {
     if (!_known)
         intersection_type();
     if (_result != POINT)
         return false;
     pt = _intersection_point;
     return true;
 }
bool intersection (Line_2< R > & result) const
Definition at line 256 of file Line_2_Line_2_intersection.h.
 {
     if (!_known)
         intersection_type();
     if (_result != LINE)
         return false;
     l = *_line1;
     return true;
 }
Line_2_Line_2_pair< R >::Intersection_results intersection_type () const
Definition at line 203 of file Line_2_Line_2_intersection.h.
References construct_if_finite(), and is_finite().
Referenced by Segment_2_Segment_2_pair< R >::intersection_type().
 {
     typedef typename R::RT RT;
     if (_known)
         return _result;
     RT nom1, nom2, denom;
     // The non const this pointer is used to cast away const.
     _known = true;
     denom = _line1->a()*_line2->b() - _line2->a()*_line1->b();
     if (denom == RT(0)) {
         if (RT(0) == (_line1->a()*_line2->c() - _line2->a()*_line1->c()) &&
             RT(0) == (_line1->b()*_line2->c() - _line2->b()*_line1->c()))
             _result = LINE;
         else
             _result = NO;
         return _result;
     }
     nom1 = (_line1->b()*_line2->c() - _line2->b()*_line1->c());
     if (!::CGAL::is_finite(nom1)) {
         _result = NO;
         return _result;
     }
     nom2 = (_line2->a()*_line1->c() - _line1->a()*_line2->c());
     if (!::CGAL::is_finite(nom2)) {
         _result = NO;
         return _result;
     }
     R dummyR;
     if (!construct_if_finite(_intersection_point,
                             nom1, nom2, denom, dummyR)){
         _result = NO;
         return _result;
     }
     _result = POINT;
     return _result;
 }
Member Data Documentation
Point_2<R> _intersection_point mutable protected
Definition at line 119 of file Line_2_Line_2_intersection.h.
bool _known mutable protected
Definition at line 117 of file Line_2_Line_2_intersection.h.
Line_2<R> const* _line1 protected
Definition at line 115 of file Line_2_Line_2_intersection.h.
Line_2<R> const* _line2 protected
Definition at line 116 of file Line_2_Line_2_intersection.h.
Intersection_results _result mutable protected
Definition at line 118 of file Line_2_Line_2_intersection.h.
The documentation for this class was generated from the following file:
Line_2_Line_2_intersection.h