Rocstar: NewAttribute Class Reference
NewAttribute Class Reference
#include <Agent.h>
Public Member Functions
NewAttribute (Agent *ag, std::string target_window_, std::string attr_, char loc_, int type_, int ncomp_, const char *unit_)
void create (std::string bufname)
Public Member Functions inherited from AttributeBase
AttributeBase (Agent *ag, std::string target_window_, std::string attr_)
virtual ~AttributeBase ()
virtual void assign (std::string bufname)
Protected Attributes
char loc
int type
int ncomp
const char * unit
Additional Inherited Members
Public Attributes inherited from AttributeBase
Agent * agent
std::string target_window
std::string attr
Detailed Description
Definition at line 58 of file Agent.h.
Constructor & Destructor Documentation
NewAttribute (Agent * ag, std::string target_window_, std::string attr_, char loc_, int type_, int ncomp_, const char * unit_)
Definition at line 102 of file Agent.C.
                                                                                                                                      :
                 AttributeBase(ag, target_window_, attr_),
                 loc(loc_), type(type_), ncomp(ncomp_), unit(unit_)
 {
 }
Member Function Documentation
void create (std::string bufname) virtual
Reimplemented from AttributeBase.
Definition at line 108 of file Agent.C.
References AttributeBase::attr, COM_get_attribute(), COM_get_attribute_handle(), COM_new_attribute(), COM_resize_array(), loc, MAN_DEBUG, MPI_COMM_WORLD, ncomp, type, and unit.
 {
   // test if already created
   if (COM_get_attribute_handle( bufname+attr) > 0) {
     char loc_;
     int type_;
     int ncomp_;
     std::string unit_;
     COM_get_attribute( bufname+attr, &loc_, &type_, &ncomp_, &unit_);
     if (loc_ != loc || type_ != type || ncomp_ != ncomp || unit_ != unit) {
       std::cerr << "Rocstar Error: NewAttribute::create(): Could not create " << bufname+attr << " in two different ways " << std::endl;
       MPI_Abort(MPI_COMM_WORLD, -1);
     }
     else
       return;
   }
   MAN_DEBUG(3, ("NewAttribute::create: %s%s.\n", bufname.c_str(), attr.c_str()));
   COM_new_attribute( bufname+attr, loc, type, ncomp, unit);
   COM_resize_array( bufname+attr);
 }
Member Data Documentation
char loc protected
Definition at line 61 of file Agent.h.
Referenced by create().
int ncomp protected
Definition at line 63 of file Agent.h.
Referenced by create().
int type protected
Definition at line 62 of file Agent.h.
Referenced by create().
const char* unit protected
Definition at line 64 of file Agent.h.
Referenced by create().
The documentation for this class was generated from the following files:
Agent.h
Agent.C