Rocstar: rflu_modextractflowdata Module Reference
rflu_modextractflowdata Module Reference
Public Member Functions
subroutine, public rflu_extractflowdata (pRegion)
subroutine rflu_extractflowdatasommspi (pRegion)
subroutine rflu_extractflowdatastg1d (pRegion)
Private Member Functions
subroutine, private rflu_extractflowdatablasius (pRegion)
subroutine, private rflu_extractflowdatanscbc (pRegion)
subroutine, private rflu_extractflowdatalinefarf (pRegion)
subroutine, private rflu_extractflowdataproudman (pRegion)
subroutine, private rflu_extractflowdatasod (pRegion)
subroutine, private rflu_extractflowdatastg2d (pRegion)
subroutine, private rflu_extractflowdataskews (pRegion)
subroutine, private rflu_writemeshbump (pRegion)
Private Attributes
character(chrlen), parameter,
private rcsidentstring = '$RCSfile: RFLU_ModExtractFlowData.F90,v $ $Revision: 1.24 $'
Detailed Description
Definition at line 46 of file RFLU_ModExtractFlowData.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_extractflowdata (type(t_region), pointer pRegion)
Definition at line 122 of file RFLU_ModExtractFlowData.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_extractflowdatablasius(), rflu_extractflowdatalinefarf(), rflu_extractflowdatanscbc(), rflu_extractflowdataproudman(), rflu_extractflowdataskews(), rflu_extractflowdatasod(), rflu_extractflowdatasommspi(), rflu_extractflowdatastg1d(), rflu_extractflowdatastg2d(), and rflu_writemeshbump().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().
subroutine, private rflu_extractflowdatablasius (type(t_region), pointer pRegion) private
Definition at line 288 of file RFLU_ModExtractFlowData.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dy(), moderror::errorstop(), form, i, j, k, Color::r(), moderror::registerfunction(), CLine::slope(), sqrt(), Attribute::status(), v, x, and y.
Referenced by rflu_extractflowdata().
subroutine, private rflu_extractflowdatalinefarf (type(t_region), pointer pRegion) private
Definition at line 964 of file RFLU_ModExtractFlowData.F90.
References moderror::deregisterfunction(), CImg< T >::distance(), moderror::errorstop(), form, Color::r(), moderror::registerfunction(), sqrt(), Attribute::status(), and v.
Referenced by rflu_extractflowdata().
subroutine, private rflu_extractflowdatanscbc (type(t_region), pointer pRegion) private
Definition at line 830 of file RFLU_ModExtractFlowData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, Color::r(), moderror::registerfunction(), Attribute::status(), and v.
Referenced by rflu_extractflowdata().
subroutine, private rflu_extractflowdataproudman (type(t_region), pointer pRegion) private
Definition at line 1189 of file RFLU_ModExtractFlowData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, j, Color::r(), moderror::registerfunction(), rflu_modexactflow::rflu_computeexactflowproudman(), rflu_modflowhardcode::rflu_getparamshardcodeproudman(), Attribute::status(), v, x, and y.
Referenced by rflu_extractflowdata().
subroutine, private rflu_extractflowdataskews (type(t_region), pointer pRegion) private
Definition at line 2310 of file RFLU_ModExtractFlowData.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), form, Color::r(), moderror::registerfunction(), sqrt(), Attribute::status(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), and Bbox_2::ymin().
Referenced by rflu_extractflowdata().
subroutine, private rflu_extractflowdatasod (type(t_region), pointer pRegion) private
Definition at line 1415 of file RFLU_ModExtractFlowData.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), form, Color::r(), moderror::registerfunction(), and Attribute::status().
Referenced by rflu_extractflowdata().
subroutine rflu_extractflowdatasommspi (type(t_region), pointer pRegion)
Definition at line 1565 of file RFLU_ModExtractFlowData.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), form, Color::r(), moderror::registerfunction(), rflu_modextractflowdatautils::rflu_extractshocklocation1d(), and Attribute::status().
Referenced by rflu_extractflowdata().
subroutine rflu_extractflowdatastg1d (type(t_region), pointer pRegion)
Definition at line 1791 of file RFLU_ModExtractFlowData.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), form, Color::r(), moderror::registerfunction(), rflu_modextractflowdatautils::rflu_extractshocklocation1d(), and Attribute::status().
Referenced by rflu_extractflowdata().
subroutine, private rflu_extractflowdatastg2d (type(t_region), pointer pRegion) private
Definition at line 2062 of file RFLU_ModExtractFlowData.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), form, Color::r(), moderror::registerfunction(), and Attribute::status().
Referenced by rflu_extractflowdata().
subroutine, private rflu_writemeshbump (type(t_region), pointer pRegion) private
Definition at line 2465 of file RFLU_ModExtractFlowData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_extractflowdata().
Member Data Documentation
character(chrlen), parameter, private rcsidentstring = '$RCSfile: RFLU_ModExtractFlowData.F90,v $ $Revision: 1.24 $' private
Definition at line 72 of file RFLU_ModExtractFlowData.F90.
The documentation for this module was generated from the following file:
RFLU_ModExtractFlowData.F90