Rocstar: rflo_modvectortensor Module Reference
rflo_modvectortensor Module Reference
Public Member Functions
subroutine, public rflo_normcrossprod (s1, s2, s3)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModVectorTensor.F90,v $ $Revision: 1.3 $'
Detailed Description
Definition at line 39 of file RFLO_ModVectorTensor.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_normcrossprod (real(rfreal), dimension(:) s1, real(rfreal), dimension(:) s2, real(rfreal), dimension(:) s3)
Definition at line 84 of file RFLO_ModVectorTensor.F90.
References sqrt().
Referenced by rflo_modgridregionshape::rflo_gridflatpatch(), and rflo_modmovegridframe::rflo_mgframeorthoshift().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModVectorTensor.F90,v $ $Revision: 1.3 $' private
Definition at line 61 of file RFLO_ModVectorTensor.F90.
The documentation for this module was generated from the following file:
RFLO_ModVectorTensor.F90