Rocstar: LineS3< FT > Class Template Reference
LineS3< FT > Class Template Reference
#include <LineS3.h>
Public Member Functions
LineS3 ()
LineS3 (const PointS3< FT > &p, const PointS3< FT > &q)
LineS3 (const SegmentS3< FT > &s)
LineS3 (const RayS3< FT > &r)
LineS3 (const PointS3< FT > &p, const DirectionS3< FT > &d)
bool operator== (const LineS3< FT > &l) const
bool operator!= (const LineS3< FT > &l) const
PlaneS3< FT > perpendicular_plane (const PointS3< FT > &p) const
LineS3< FT > opposite () const
PointS3< FT > point () const
PointS3< FT > point (int i) const
PointS3< FT > projection (const PointS3< FT > &p) const
DirectionS3< FT > direction () const
bool has_on (const PointS3< FT > &p) const
bool is_degenerate () const
LineS3< FT > transform (const Aff_transformationS3< FT > &t) const
void new_rep (const PointS3< FT > &p, const VectorS3< FT > &v)
Public Attributes
PointS3< FT > e0
PointS3< FT > e1
Detailed Description
template<class FT>
class LineS3< FT >
Definition at line 59 of file LineS3.h.
Constructor & Destructor Documentation
LineS3 () inline
Definition at line 62 of file LineS3.h.
 {}
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE LineS3 (const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 118 of file LineS3.h.
 { new_rep(p, q - p); }
LineS3 (const SegmentS3< FT > & s)
Definition at line 122 of file LineS3.h.
References SegmentS3< FT >::end(), and SegmentS3< FT >::start().
 { new_rep(s.start(), s.end() - s.start()); }
LineS3 (const RayS3< FT > & r)
Definition at line 126 of file LineS3.h.
References RayS3< FT >::second_point(), and RayS3< FT >::start().
 { new_rep(r.start(), r.second_point() - r.start()); }
LineS3 (const PointS3< FT > & p, const DirectionS3< FT > & d)
Definition at line 130 of file LineS3.h.
References DirectionS3< FT >::vector().
 { new_rep(p, d.vector()); }
Member Function Documentation
DirectionS3< FT > direction () const
Definition at line 150 of file LineS3.h.
References ORIGIN.
Referenced by PlaneS3< FT >::has_on_boundary(), LineS3< FT >::operator==(), and PlaneS3< FT >::PlaneS3().
 { return (e1 - ORIGIN).direction(); }
bool has_on (const PointS3< FT > & p) const
Definition at line 180 of file LineS3.h.
References collinear().
 { return collinear(point(), point()+direction().vector(), p); }
bool is_degenerate () const
Definition at line 186 of file LineS3.h.
 { return direction() == DirectionS3<FT>(0,0,0); }
void new_rep (const PointS3< FT > & p, const VectorS3< FT > & v) inline
Definition at line 102 of file LineS3.h.
References ORIGIN, and v.
 {
   e0 = p;
   e1 = ORIGIN + v;
 }
bool operator!= (const LineS3< FT > & l) const inline
Definition at line 140 of file LineS3.h.
 { return !(*this == l); }
bool operator== (const LineS3< FT > & l) const
Definition at line 134 of file LineS3.h.
References LineS3< FT >::direction(), and LineS3< FT >::point().
 { return has_on(l.point()) && (direction() == l.direction()); }
LineS3< FT > opposite () const
Definition at line 166 of file LineS3.h.
 { return LineS3<FT>(point(), -direction()); }
PlaneS3< FT > perpendicular_plane (const PointS3< FT > & p) const
Definition at line 161 of file LineS3.h.
 { return PlaneS3<FT>(p, direction().vector()); }
PointS3< FT > point () const
Definition at line 145 of file LineS3.h.
Referenced by PlaneS3< FT >::has_on_boundary(), LineS3< FT >::operator==(), and PlaneS3< FT >::PlaneS3().
 { return e0; }
PointS3< FT > point (int i) const
Definition at line 156 of file LineS3.h.
References ORIGIN.
 { return PointS3<FT>(point() + FT(i) * (e1 - ORIGIN)); }
PointS3< FT > projection (const PointS3< FT > & p) const
Definition at line 171 of file LineS3.h.
 {
   return point() + ( ((direction().vector() * (p - point())) /
                       (direction().vector() * direction().vector()))
                      * direction().vector() );
 }
LineS3< FT > transform (const Aff_transformationS3< FT > & t) const inline
Definition at line 193 of file LineS3.h.
References Aff_transformationS3< FT >::transform().
 { return LineS3<FT>( t.transform(point()), t.transform(direction())); }
Member Data Documentation
PointS3<FT> e0
Definition at line 93 of file LineS3.h.
PointS3<FT> e1
Definition at line 94 of file LineS3.h.
The documentation for this class was generated from the following file:
LineS3.h