Rocstar: MeanMidNodeMover Class Reference
MeanMidNodeMover Class Reference
Class to adjust positions of higher-order nodes.
#include <MeanMidNodeMover.hpp>
Public Member Functions
MeanMidNodeMover ()
virtual ~MeanMidNodeMover ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
virtual msq_std::string get_name ()
Returns the algorithm name.
virtual
PatchDataUser::AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
MeanMidNodeMover ()
virtual ~MeanMidNodeMover ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
virtual msq_std::string get_name ()
Returns the algorithm name.
virtual
PatchDataUser::AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Additional Inherited Members
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Detailed Description
Class to adjust positions of higher-order nodes.
Move all higher-order nodes to average position of adjacent nodes.
Definition at line 44 of file includeLinks/MeanMidNodeMover.hpp.
Constructor & Destructor Documentation
MeanMidNodeMover ()
Definition at line 34 of file QualityImprover/VertexMover/MeanMidNodeMover.cpp.
References PatchData::GLOBAL_PATCH, MSQ_CHKERR, and PatchDataUser::set_patch_type().
 {
   MsqError err;
   PatchDataUser::set_patch_type( PatchData::GLOBAL_PATCH, err );
   MSQ_CHKERR(err);
 }
~MeanMidNodeMover () virtual
Definition at line 41 of file QualityImprover/VertexMover/MeanMidNodeMover.cpp.
 {}
MeanMidNodeMover ()
virtual ~MeanMidNodeMover () virtual
Member Function Documentation
PatchDataUser::AlgorithmType get_algorithm_type () virtual
Return the algorithm type (to avoid RTTI use).
Implements PatchDataUser.
Definition at line 52 of file QualityImprover/VertexMover/MeanMidNodeMover.cpp.
References PatchDataUser::QUALITY_IMPROVER.
 { return PatchDataUser::QUALITY_IMPROVER; }
virtual PatchDataUser::AlgorithmType get_algorithm_type () virtual
Return the algorithm type (to avoid RTTI use).
Implements PatchDataUser.
msq_std::string get_name () virtual
Returns the algorithm name.
Implements PatchDataUser.
Definition at line 49 of file QualityImprover/VertexMover/MeanMidNodeMover.cpp.
 { return "MeanMidNodeMover"; }
virtual msq_std::string get_name () virtual
Returns the algorithm name.
Implements PatchDataUser.
double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
This is the "run" function of PatchDataUser. It can do anything really.
Implements PatchDataUser.
Definition at line 56 of file QualityImprover/VertexMover/MeanMidNodeMover.cpp.
References TopologyInfo::corners(), PatchData::element_by_index(), MsqMeshEntity::get_element_type(), PatchDataUser::get_global_patch(), PatchDataUser::get_patch_type(), PatchData::get_vertex_element_adjacencies(), MsqMeshEntity::get_vertex_index_array(), PatchData::GLOBAL_PATCH, i, MsqError::INTERNAL_ERROR, MsqError::INVALID_MESH, MsqError::INVALID_STATE, MSQ_ERRZERO, MSQ_SETERR, MsqMeshEntity::node_count(), PatchData::num_nodes(), PatchData::num_vertices(), PatchData::set_vertex_coordinates(), TopologyInfo::side_number(), TopologyInfo::side_vertices(), PatchData::snap_vertex_to_domain(), PatchData::update_mesh(), and PatchData::vertex_by_index().
 {
   if (get_patch_type() != PatchData::GLOBAL_PATCH) {
     MSQ_SETERR(err)(MsqError::INVALID_STATE);
     return 0;
   }
   if (!get_global_patch()) {
     MSQ_SETERR(err)("No global patch", MsqError::INVALID_STATE);
     return 0;
   }
   PatchData& pd = *get_global_patch();
     // For each higher-order node in the patch
   for (size_t vtx = pd.num_vertices(); vtx < pd.num_nodes(); ++vtx)
   {
       // Get an adjacent element
     size_t num_elems, *elem_list;
     elem_list = pd.get_vertex_element_adjacencies( vtx, num_elems, err ); MSQ_ERRZERO(err);
     if (num_elems < 1) // Mid-node without adjacent elements????
       continue;
     size_t element_index = elem_list[0];
     MsqMeshEntity& element = pd.element_by_index( element_index );
       // Find position of current vertex in element connectivity list
     unsigned elem_vert_index;
     size_t num_verts = element.node_count();
     size_t* vert_list = element.get_vertex_index_array();
     for (elem_vert_index = 0; elem_vert_index < num_verts; ++elem_vert_index)
       if (vert_list[elem_vert_index] == vtx)
         break;
       // Sanity checks
       // Mesh is corrupt if vertex not in connectivity list
     if (elem_vert_index == num_verts)
     {
       MSQ_SETERR(err)("Inconsistent connectivity/adjacency data.", MsqError::INVALID_MESH );
       return 0;
     }
       // Must be appropriate element type (e.g. can't have higher-order
       // nodes on a polygon)
     EntityTopology topo = element.get_element_type();
     unsigned num_corners = TopologyInfo::corners( topo );
     if (!num_corners)
     {
       MSQ_SETERR(err)( MsqError::INVALID_MESH,
                        "Element type %d cannot have higher-order nodes.",
                        (int)topo );
       return 0;
     }
       // The current vertex must be one of the higher-order nodes of the element
     if (elem_vert_index < num_corners)
     {
       MSQ_SETERR(err)( "Invalid mid-node flag for mesh (mixed connectivity?)",
                        MsqError::INVALID_MESH );
       return 9;
     }
       // Get the element "side" that the node is a mid-node of.
     unsigned side, dimension;
     TopologyInfo::side_number( topo, element.node_count(), elem_vert_index,
                                side, dimension, err ); MSQ_ERRZERO(err);
       // Get the indices of the vertices defining the "side"
     unsigned side_size;
     const unsigned* side_indices =
       TopologyInfo::side_vertices( topo, side, dimension, side_size, err ); MSQ_ERRZERO(err);
     if (!side_size)
     {
       MSQ_SETERR(err)(MsqError::INTERNAL_ERROR);
       return 0;
     }
       // Calculate average position of side vertices
     const msq_stdc::size_t* conn_array = element.get_vertex_index_array();
     Vector3D pos(0,0,0);
     for (unsigned i = 0; i < side_size; ++i)
       pos += pd.vertex_by_index( conn_array[side_indices[i]] );
     pos /= side_size;
       // Set new vertex position
     pd.set_vertex_coordinates( pos, vtx, err ); MSQ_ERRZERO(err);
     pd.snap_vertex_to_domain( vtx, err );       MSQ_ERRZERO(err);
   }
   pd.update_mesh(err); MSQ_ERRZERO(err);
   return 0;
 }
virtual double loop_over_mesh (MeshSet & ms, MsqError & err) virtual
This is the "run" function of PatchDataUser. It can do anything really.
Implements PatchDataUser.
void set_patch_type (PatchData::PatchType patch_type, MsqError & err, int param1 = 0, int param2 = 0) virtual
Sets the Patch Type.
Reimplemented from PatchDataUser.
Definition at line 43 of file QualityImprover/VertexMover/MeanMidNodeMover.cpp.
References MsqError::INVALID_ARG, and MSQ_SETERR.
 {
   MSQ_SETERR(err)("Patch type cannot be changed for MeanMidNodeMover.",MsqError::INVALID_ARG);
   return;
 }
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError & err, int param1 = 0, int param2 = 0) virtual
Sets the Patch Type.
Reimplemented from PatchDataUser.
The documentation for this class was generated from the following files:
includeLinks/MeanMidNodeMover.hpp
QualityImprover/VertexMover/MeanMidNodeMover.cpp