Rocstar: rflu_modmpi Module Reference
rflu_modmpi Module Reference
Public Member Functions
subroutine, public rflu_mpi_clearrequestwrapper (pRegion)
subroutine, public rflu_mpi_copywrapper (regions)
subroutine, public rflu_mpi_createbufferipclsend (pRegion, pBorder)
subroutine, public rflu_mpi_createbufferswrapper (pRegion)
subroutine, public rflu_mpi_destroybufferipclsend (pRegion, pBorder)
subroutine, public rflu_mpi_destroybufferswrapper (pRegion)
subroutine, public rflu_mpi_recreatebufferipclsend (pRegion, pBorder)
subroutine, public rflu_mpi_isendwrapper (pRegion)
subroutine, public rflu_mpi_recvwrapper (pRegion)
subroutine, public rflu_mpi_settagswrapper (pRegion)
Private Member Functions
subroutine rflu_mpi_clearrequest (global, request)
subroutine rflu_mpi_copycelldata (global, pBorder, pBorder2, cellData, cellData2)
subroutine rflu_mpi_createbuffers (global, pBorder, borderData, nVars)
subroutine rflu_mpi_destroybuffers (global, pBorder, borderData)
subroutine rflu_mpi_isendcelldata (global, pBorder, cellDataBuff, cellData, tag, request)
subroutine rflu_mpi_recvcelldata (global, pBorder, cellDataBuff, cellData, tag)
integer function rflu_mpi_settag (global, iReg1, iReg2, iMsg, tagMax)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModMPI.F90,v $ $Revision: 1.17 $'
Detailed Description
Definition at line 39 of file RFLU_ModMPI.F90.
Member Function/Subroutine Documentation
subroutine rflu_mpi_clearrequest (type(t_global), pointer global, integer, intent(inout) request) private
Definition at line 100 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and Attribute::status().
Referenced by rflu_mpi_clearrequestwrapper().
subroutine, public rflu_mpi_clearrequestwrapper (type(t_region), pointer pRegion)
Definition at line 170 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_mpi_clearrequest().
Referenced by explicitmultistage(), rflu_explicitmultistage(), rflu_initflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidual(), and rungekuttamp().
subroutine rflu_mpi_copycelldata (type(t_global), pointer global, type(t_border), pointer pBorder, type(t_border), pointer pBorder2, real(rfreal), dimension(:,:), intent(in) cellData, real(rfreal), dimension(:,:), intent(out) cellData2) private
Definition at line 279 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mpi_copywrapper().
subroutine, public rflu_mpi_copywrapper (type(t_region), dimension(:), pointer regions)
Definition at line 363 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_mpi_copycelldata().
Referenced by explicitmultistage(), rflu_explicitmultistage(), rflu_initflowsolver(), and rungekuttamp().
subroutine, public rflu_mpi_createbufferipclsend (type(t_region), pointer pRegion, type(t_border), optional, pointer pBorder)
Definition at line 491 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), and rflu_mpi_recreatebufferipclsend().
subroutine rflu_mpi_createbuffers (type(t_global), pointer global, type(t_border), pointer pBorder, type(t_border_data) borderData, integer, intent(in) nVars) private
Definition at line 594 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mpi_createbufferswrapper().
subroutine, public rflu_mpi_createbufferswrapper (type(t_region), pointer pRegion)
Definition at line 669 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_mpi_createbuffers().
Referenced by rflu_initflowsolver().
subroutine, public rflu_mpi_destroybufferipclsend (type(t_region), pointer pRegion, type(t_border), optional, pointer pBorder)
Definition at line 782 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_endflowsolver(), and rflu_mpi_recreatebufferipclsend().
subroutine rflu_mpi_destroybuffers (type(t_global), pointer global, type(t_border), pointer pBorder, type(t_border_data) borderData) private
Definition at line 879 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mpi_destroybufferswrapper().
subroutine, public rflu_mpi_destroybufferswrapper (type(t_region), pointer pRegion)
Definition at line 953 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_mpi_destroybuffers().
Referenced by rflu_endflowsolver().
subroutine rflu_mpi_isendcelldata (type(t_global), pointer global, type(t_border), pointer pBorder, real(rfreal), dimension(:,:), intent(out) cellDataBuff, real(rfreal), dimension(:,:), intent(in) cellData, integer, intent(in) tag, integer, intent(out) request) private
Definition at line 1068 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and RFC_Data_const< _Tag >::tag().
Referenced by rflu_mpi_isendwrapper().
subroutine, public rflu_mpi_isendwrapper (type(t_region), pointer pRegion)
Definition at line 1295 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_mpi_isendcelldata().
Referenced by explicitmultistage(), rflu_explicitmultistage(), rflu_initflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidual(), and rungekuttamp().
subroutine, public rflu_mpi_recreatebufferipclsend (type(t_region), pointer pRegion, type(t_border), optional, pointer pBorder)
Definition at line 1163 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_mpi_createbufferipclsend(), and rflu_mpi_destroybufferipclsend().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), and plag_rflu_modfindcells::plag_rflu_findcellstrajsafe().
subroutine rflu_mpi_recvcelldata (type(t_global), pointer global, type(t_border), pointer pBorder, real(rfreal), dimension(:,:), intent(in) cellDataBuff, real(rfreal), dimension(:,:), intent(out) cellData, integer, intent(in) tag) private
Definition at line 1410 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), Attribute::status(), and RFC_Data_const< _Tag >::tag().
Referenced by rflu_mpi_recvwrapper().
subroutine, public rflu_mpi_recvwrapper (type(t_region), pointer pRegion)
Definition at line 1502 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_mpi_recvcelldata().
Referenced by explicitmultistage(), rflu_explicitmultistage(), rflu_initflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidual(), and rungekuttamp().
integer function rflu_mpi_settag (type(t_global), pointer global, integer, intent(in) iReg1, integer, intent(in) iReg2, integer, intent(in) iMsg, integer, intent(in) tagMax) private
Definition at line 1612 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), min(), and moderror::registerfunction().
Referenced by rflu_mpi_settagswrapper().
subroutine, public rflu_mpi_settagswrapper (type(t_region), pointer pRegion)
Definition at line 1686 of file RFLU_ModMPI.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_mpi_settag().
Referenced by rflu_initflowsolver().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModMPI.F90,v $ $Revision: 1.17 $' private
Definition at line 69 of file RFLU_ModMPI.F90.
The documentation for this module was generated from the following file:
RFLU_ModMPI.F90