Rocstar: ParameterSet Class Reference
ParameterSet Class Reference
#include <ParameterSet.hpp>
Classes
struct ParameterRecord
Public Member Functions
ParameterSet ()
~ParameterSet ()
void add_int_parameter (const char *name, int initial_value, MsqError &err)
void set_int_parameter (const char *name, int value, MsqError &err)
void get_int_parameter (const char *name, int *value, MsqError &err)
void remove_parameter (const char *name, MsqError &err)
ParameterSet ()
~ParameterSet ()
void add_int_parameter (const char *name, int initial_value, MsqError &err)
void set_int_parameter (const char *name, int value, MsqError &err)
void get_int_parameter (const char *name, int *value, MsqError &err)
void remove_parameter (const char *name, MsqError &err)
Private Member Functions
msq_stdc::size_t get_parameter_index (const char *name, MsqError &err)
void generic_add_parameter (const char *name, MsqError &err)
msq_stdc::size_t get_parameter_index (const char *name, MsqError &err)
void generic_add_parameter (const char *name, MsqError &err)
Private Attributes
ParameterRecord * mParameterArray
msq_stdc::size_t mNumParameters
Detailed Description
Definition at line 43 of file includeLinks/ParameterSet.hpp.
Constructor & Destructor Documentation
ParameterSet ()
Definition at line 62 of file ParameterSet.cpp.
     : mParameterArray(NULL),
       mNumParameters(0)
 {
 }
~ParameterSet ()
Definition at line 68 of file ParameterSet.cpp.
References ParameterSet::mNumParameters, ParameterSet::mParameterArray, MSQ_STRING, ParameterSet::ParameterRecord::name, ParameterSet::ParameterRecord::ParameterValue::strVal, and ParameterSet::ParameterRecord::value.
 {
   while (mNumParameters--)
   {
     delete [] mParameterArray[mNumParameters].name;
       // If it's a string, free the string value
     if (mParameterArray[mNumParameters].type == MSQ_STRING &&
         mParameterArray[mNumParameters].value.strVal != NULL)
     {
       delete [] mParameterArray[mNumParameters].value.strVal;
     }
   }
   delete mParameterArray;
 }
ParameterSet ()
~ParameterSet ()
Member Function Documentation
void add_int_parameter (const char * name, int initial_value, MsqError & err)
Definition at line 147 of file ParameterSet.cpp.
References ParameterSet::generic_add_parameter(), ParameterSet::ParameterRecord::ParameterValue::intVal, ParameterSet::mNumParameters, ParameterSet::mParameterArray, MSQ_ERRRTN, MSQ_INT, ParameterSet::ParameterRecord::type, and ParameterSet::ParameterRecord::value.
 {
   generic_add_parameter(name, err);
   MSQ_ERRRTN(err);
   mParameterArray[mNumParameters - 1].type = MSQ_INT;
   mParameterArray[mNumParameters - 1].value.intVal = initial_value;
   return;
 }
void add_int_parameter (const char * name, int initial_value, MsqError & err)
void generic_add_parameter (const char * name, MsqError & err) private
void generic_add_parameter (const char * name, MsqError & err) private
Definition at line 120 of file ParameterSet.cpp.
References MsqError::clear(), ParameterSet::get_parameter_index(), MsqError::INVALID_ARG, ParameterSet::mNumParameters, ParameterSet::mParameterArray, MSQ_SETERR, and ParameterSet::ParameterRecord::name.
Referenced by ParameterSet::add_int_parameter().
 {
     // Make sure it doesn't already exist
   if(get_parameter_index(name, err) == mNumParameters) {
     err.clear();
   } else {
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     return;
   }
     // Make the array big enough
   ParameterRecord* new_array = new ParameterRecord[mNumParameters + 1];
     // Copy the old into the new
   memcpy(new_array, mParameterArray, mNumParameters*sizeof(ParameterRecord));
     // Toss the old
   delete [] mParameterArray;
     // Save the new
   mNumParameters++;
   mParameterArray = new_array;
     // Now add the new parameter, with no initial value
   mParameterArray[mNumParameters - 1].name = new char[strlen(name) + 1];
   strcpy(mParameterArray[mNumParameters - 1].name, name);
   return;
 }
void get_int_parameter (const char * name, int * value, MsqError & err)
void get_int_parameter (const char * name, int * value, MsqError & err)
Definition at line 176 of file ParameterSet.cpp.
References ParameterSet::get_parameter_index(), MsqError::INVALID_ARG, ParameterSet::mParameterArray, MSQ_ERRRTN, MSQ_INT, MSQ_SETERR, and ParameterSet::ParameterRecord::value.
 {
     // Make sure it exists
   size_t index = get_parameter_index(name, err);
   MSQ_ERRRTN(err);
     // Make sure it's the right type
   if (mParameterArray[index].type != MSQ_INT) {
      MSQ_SETERR(err)(MsqError::INVALID_ARG);
     return;
   }
     // Get the value
   *value = *reinterpret_cast<int*>(&(mParameterArray[index].value));
   return;
 }
msq_stdc::size_t get_parameter_index (const char * name, MsqError & err) private
Definition at line 84 of file ParameterSet.cpp.
References i, MsqError::INVALID_ARG, ParameterSet::mNumParameters, ParameterSet::mParameterArray, and MSQ_SETERR.
Referenced by ParameterSet::generic_add_parameter(), ParameterSet::get_int_parameter(), ParameterSet::remove_parameter(), and ParameterSet::set_int_parameter().
 {
     // Search for a parameter with the same name
   for (size_t i = 0; (i < mNumParameters; ++i)
     if (!msq_stdc::strcmp(mParameterArray[i].name, name))
       return i;
   MSQ_SETERR(err)( MsqError::INVALID_ARG );
   return mNumParameters;
 }
msq_stdc::size_t get_parameter_index (const char * name, MsqError & err) private
void remove_parameter (const char * name, MsqError & err)
Definition at line 95 of file ParameterSet.cpp.
References ParameterSet::get_parameter_index(), ParameterSet::mNumParameters, ParameterSet::mParameterArray, MSQ_ERRRTN, MSQ_STRING, ParameterSet::ParameterRecord::name, ParameterSet::ParameterRecord::ParameterValue::strVal, and ParameterSet::ParameterRecord::value.
 {
     // Make sure it exists
   size_t index = get_parameter_index(name);  MSQ_ERRRTN(err);
     // Free the string holding the name
   delete [] mParameterArray[index].name;
     // If it's a string, free the string value
   if (mParameterArray[index].type == MSQ_STRING &&
       mParameterArray[index].value.strVal != NULL)
   {
     delete [] mParameterArray[index].value.strVal;
   }
     // If it isn't at the end, move the last parameter
     // into the spot this one was using
   if (index != mNumParameters - 1)
   {
     mParameterArray[index] = mParameterArray[mNumParameters - 1];
   }
   mNumParameters--;
 }
void remove_parameter (const char * name, MsqError & err)
void set_int_parameter (const char * name, int value, MsqError & err)
Definition at line 159 of file ParameterSet.cpp.
References ParameterSet::get_parameter_index(), ParameterSet::ParameterRecord::ParameterValue::intVal, MsqError::INVALID_ARG, ParameterSet::mParameterArray, MSQ_ERRRTN, MSQ_INT, MSQ_SETERR, and ParameterSet::ParameterRecord::value.
 {
     // Make sure it exists
   size_t index = get_parameter_index(name, err);
   MSQ_ERRRTN(err);
     // Make sure it's the right type
   if (mParameterArray[index].type != MSQ_INT)  {
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     return;
   }
     // Set the value
   mParameterArray[index].value.intVal = value;
 }
void set_int_parameter (const char * name, int value, MsqError & err)
Member Data Documentation
msq_stdc::size_t mNumParameters private
Definition at line 86 of file includeLinks/ParameterSet.hpp.
Referenced by ParameterSet::add_int_parameter(), ParameterSet::generic_add_parameter(), ParameterSet::get_parameter_index(), ParameterSet::remove_parameter(), and ParameterSet::~ParameterSet().
ParameterRecord * mParameterArray private
Definition at line 85 of file includeLinks/ParameterSet.hpp.
Referenced by ParameterSet::add_int_parameter(), ParameterSet::generic_add_parameter(), ParameterSet::get_int_parameter(), ParameterSet::get_parameter_index(), ParameterSet::remove_parameter(), ParameterSet::set_int_parameter(), and ParameterSet::~ParameterSet().
The documentation for this class was generated from the following files:
includeLinks/ParameterSet.hpp
ParameterSet.cpp