Rocstar: C3Plane Class Reference
C3Plane Class Reference
#include <GeoPrimitives.H>
Public Member Functions
C3Plane ()
C3Plane (const C3Point &p1, const C3Point &p2, const C3Point &p3)
C3Plane (const C3Vector &N, const C3Point &P)
C3Plane (const C3Plane &plane)
C3Plane (const std::vector< C3Point > &vec)
C3Plane & operator= (const C3Plane &plane)
double A () const
double B () const
double C () const
double D () const
C3Vector & normal ()
const C3Vector & normal () const
C3Point & point ()
const C3Point & point () const
bool contains_point (const C3Point &P) const
bool operator== (const C3Plane &plane) const
Protected Attributes
C3Vector n
C3Point p
Detailed Description
Definition at line 1406 of file GeoPrimitives.H.
Constructor & Destructor Documentation
C3Plane () inline
Definition at line 1411 of file GeoPrimitives.H.
 {};
C3Plane (const C3Point & p1, const C3Point & p2, const C3Point & p3) inline
Definition at line 1412 of file GeoPrimitives.H.
References C3Plane::A(), C3Plane::B(), C3Plane::C(), C3Plane::n, C3Vector::Normalize(), C3Vector::x(), C3Vector::y(), and C3Vector::z().
       : p(p1)
     {
       double A = p1.y()*(p2.z() - p3.z()) + p2.y()*(p3.z() - p1.z()) +
         p3.y()*(p1.z() - p2.z());
       double B = p1.z()*(p2.x() - p3.x()) + p2.z()*(p3.x() - p1.x()) +
         p3.z()*(p1.x() - p2.x());
       double C = p1.x()*(p2.y() - p3.y()) + p2.x()*(p3.y() - p1.y()) +
         p3.x()*(p1.y() - p2.y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.Normalize();
     };
C3Plane (const C3Vector & N, const C3Point & P) inline
Definition at line 1428 of file GeoPrimitives.H.
       : n(N.Unit()),p(P)
     {};
C3Plane (const C3Plane & plane) inline
Definition at line 1431 of file GeoPrimitives.H.
       : n(plane.n),p(plane.p)
     {};
C3Plane (const std::vector< C3Point > & vec) inline
Definition at line 1434 of file GeoPrimitives.H.
References C3Plane::A(), C3Plane::B(), C3Plane::C(), C3Plane::n, C3Vector::Normalize(), x, C3Vector::x(), y, and z.
       : p(vec[0])
     {
       double A = vec[0].y()*(vec[1].z() - vec[2].z()) +
         vec[1].y()*(vec[2].z() - vec[0].z()) +
         vec[2].y()*(vec[0].z() - vec[1].z());
       double B = vec[0].z()*(vec[1].x() - vec[2].x()) +
         vec[1].z()*(vec[2].x() - vec[0].x()) +
         vec[2].z()*(vec[0].x() - vec[1].x());
       double C = vec[0].x()*(vec[1].y() - vec[2].y()) +
         vec[1].x()*(vec[2].y() - vec[0].y()) +
         vec[2].x()*(vec[0].y() - vec[1].y());
       //      double D = -1.0 * ( p1.x()*(p2.y()*p3.z() - p3.y()*p2.z()) +
       //                          p2.x()*(p3.y()*p1.z() - p1.y()*p3.z()) +
       //                          p3.x()*(p1.y()*p2.z() - p2.y()*p1.z()) );
       n.x(A).y(B).z(C);
       n.Normalize();
     } ;
Member Function Documentation
double A () const inline
Definition at line 1459 of file GeoPrimitives.H.
References C3Plane::n, and C3Vector::x().
Referenced by C3Plane::C3Plane().
 { return(n.x()); };
double B () const inline
Definition at line 1460 of file GeoPrimitives.H.
References C3Plane::n, and C3Vector::y().
Referenced by C3Plane::C3Plane().
 { return(n.y()); };
double C () const inline
Definition at line 1461 of file GeoPrimitives.H.
References C3Plane::n, and C3Vector::z().
Referenced by C3Plane::C3Plane().
 { return(n.z()); };
bool contains_point (const C3Point & P) const inline
Definition at line 1470 of file GeoPrimitives.H.
References C3Plane::D(), C3Plane::n, GeoPrim::TOL, C3Vector::x(), C3Vector::y(), and C3Vector::z().
Referenced by C3Plane::operator==(), and Mesh::GenericElement::ShapeOK().
     {
       return(fabs(n.x()*P.x() + n.y()*P.y() + n.z()*P.z() + D()) <= TOL);
     };
double D () const inline
Definition at line 1462 of file GeoPrimitives.H.
References C3Plane::n, C3Plane::p, C3Vector::x(), C3Vector::y(), and C3Vector::z().
Referenced by C3Plane::contains_point().
     {
       return( -1.0 * ( n.x()*p.x() + n.y()*p.y() + n.z()*p.z()));
     };
C3Vector& normal () inline
Definition at line 1466 of file GeoPrimitives.H.
References C3Plane::n.
 { return(n); };
const C3Vector& normal () const inline
Definition at line 1467 of file GeoPrimitives.H.
References C3Plane::n.
 { return(n); };
C3Plane& operator= (const C3Plane & plane) inline
Definition at line 1453 of file GeoPrimitives.H.
References C3Plane::n, and C3Plane::p.
     {
       n = plane.n;
       p = plane.p;
       return(*this);
     };
bool operator== (const C3Plane & plane) const inline
Definition at line 1474 of file GeoPrimitives.H.
References C3Plane::contains_point(), C3Plane::n, C3Plane::p, and C3Vector::Unit().
     {
       return((plane.n.Unit() == n.Unit()) && contains_point(plane.p));
     };
C3Point& point () inline
Definition at line 1468 of file GeoPrimitives.H.
References C3Plane::p.
 { return(p); };
const C3Point& point () const inline
Definition at line 1469 of file GeoPrimitives.H.
References C3Plane::p.
 { return(p); };
Member Data Documentation
C3Vector n protected
Definition at line 1408 of file GeoPrimitives.H.
Referenced by C3Plane::A(), C3Plane::B(), C3Plane::C(), C3Plane::C3Plane(), C3Plane::contains_point(), C3Plane::D(), C3Plane::normal(), C3Plane::operator=(), and C3Plane::operator==().
C3Point p protected
Definition at line 1409 of file GeoPrimitives.H.
Referenced by C3Plane::D(), C3Plane::operator=(), C3Plane::operator==(), and C3Plane::point().
The documentation for this class was generated from the following file:
GeoPrimitives.H