Rocstar: SegmentS2< FT > Class Template Reference
SegmentS2< FT > Class Template Reference
#include <SegmentS2.h>
Public Member Functions
SegmentS2 ()
SegmentS2 (const PointS2< FT > &sp, const PointS2< FT > &ep)
bool is_horizontal () const
bool is_vertical () const
bool has_on (const PointS2< FT > &p) const
bool collinear_has_on (const PointS2< FT > &p) const
bool operator== (const SegmentS2< FT > &s) const
bool operator!= (const SegmentS2< FT > &s) const
int id () const
const PointS2< FT > & start () const
const PointS2< FT > & end () const
const PointS2< FT > & source () const
const PointS2< FT > & target () const
PointS2< FT > min () const
PointS2< FT > max () const
PointS2< FT > vertex (int i) const
PointS2< FT > point (int i) const
PointS2< FT > operator[] (int i) const
FT squared_length () const
DirectionS2< FT > direction () const
LineS2< FT > supporting_line () const
SegmentS2< FT > opposite () const
SegmentS2< FT > transform (const Aff_transformationS2< FT > &t) const
bool is_degenerate () const
Bbox_2 bbox () const
Public Attributes
PointS2< FT > s
PointS2< FT > t
Detailed Description
template<class FT>
class SegmentS2< FT >
Definition at line 59 of file SegmentS2.h.
Constructor & Destructor Documentation
CGAL_KERNEL_CTOR_INLINE SegmentS2 ()
Definition at line 104 of file SegmentS2.h.
 {}
CGAL_KERNEL_CTOR_INLINE SegmentS2 (const PointS2< FT > & sp, const PointS2< FT > & ep)
Definition at line 108 of file SegmentS2.h.
  : s(sp), t(ep) {}
Member Function Documentation
CGAL_KERNEL_INLINE Bbox_2 bbox () const
Definition at line 220 of file SegmentS2.h.
 { return source().bbox() + target().bbox(); }
CGAL_KERNEL_MEDIUM_INLINE bool collinear_has_on (const PointS2< FT > & p) const
Definition at line 289 of file SegmentS2.h.
References NTS::abs(), CGAL_kernel_exactness_precondition, CGAL_NTS, collinear(), PointS2< FT >::x(), x, PointS2< FT >::y(), and y.
 {
     CGAL_kernel_exactness_precondition( collinear(source(), p, target()) );
     if (CGAL_NTS abs(target().x()-source().x())
       > CGAL_NTS abs(target().y()-source().y())) {
         if (p.x() < source().x())
             return (p.x() >= target().x());
         if (p.x() <= target().x())
             return true;
         return (p.x() == source().x());
     } else {
         if (p.y() < source().y())
             return (p.y() >= target().y());
         if (p.y() <= target().y())
             return true;
         return (p.y() == source().y());
     }
 }
CGAL_KERNEL_INLINE DirectionS2< FT > direction () const
Definition at line 196 of file SegmentS2.h.
 { return DirectionS2<FT>( target() - source() ); }
const PointS2< FT > & end () const inline
Definition at line 134 of file SegmentS2.h.
Referenced by LineS2< FT >::LineS2().
 { return t; }
CGAL_KERNEL_INLINE bool has_on (const PointS2< FT > & p) const
Definition at line 273 of file SegmentS2.h.
References collinear().
 {
   return(( p == source() )
          || ( p == target() )
          || ( collinear(source(), p, target())
              && ( DirectionS2<FT>(p - source())
                   !=
                   DirectionS2<FT>(p - target()))
              )
          );
 }
int id () const
bool is_degenerate () const inline
Definition at line 226 of file SegmentS2.h.
 { return (source() == target()); }
CGAL_KERNEL_INLINE bool is_horizontal () const
Definition at line 261 of file SegmentS2.h.
 { return source().y() == target().y(); }
CGAL_KERNEL_INLINE bool is_vertical () const
Definition at line 267 of file SegmentS2.h.
 { return source().x() == target().x(); }
CGAL_KERNEL_INLINE PointS2< FT > max () const
Definition at line 163 of file SegmentS2.h.
References lexicographically_xy_smaller().
 {
   return (lexicographically_xy_smaller(source(),target())) ? target()
                                                            : source();
 }
CGAL_KERNEL_INLINE PointS2< FT > min () const
Definition at line 154 of file SegmentS2.h.
References lexicographically_xy_smaller().
 {
   return (lexicographically_xy_smaller(source(),target())) ? source()
                                                            : target();
 }
bool operator!= (const SegmentS2< FT > & s) const inline
Definition at line 122 of file SegmentS2.h.
References s.
 { return !(*this == s); }
bool operator== (const SegmentS2< FT > & s) const inline
Definition at line 116 of file SegmentS2.h.
References SegmentS2< FT >::source(), and SegmentS2< FT >::target().
 { return ( (source() == s.source()) && (target() == s.target()) ); }
PointS2< FT > operator[] (int i) const inline
Definition at line 184 of file SegmentS2.h.
 { return vertex(i); }
SegmentS2< FT > opposite () const inline
Definition at line 208 of file SegmentS2.h.
 { return SegmentS2<FT>(target(), source()); }
CGAL_KERNEL_INLINE PointS2< FT > point (int i) const
Definition at line 178 of file SegmentS2.h.
 { return (i%2 ==0) ? source() : target(); }
const PointS2< FT > & source () const inline
Definition at line 141 of file SegmentS2.h.
References s.
Referenced by SegmentS2< FT >::operator==().
 { return s; }
CGAL_KERNEL_INLINE FT squared_length () const
Definition at line 190 of file SegmentS2.h.
References squared_distance().
 { return squared_distance(source(), target()); }
const PointS2< FT > & start () const inline
Definition at line 128 of file SegmentS2.h.
References s.
Referenced by LineS2< FT >::LineS2().
 { return s; }
LineS2< FT > supporting_line () const inline
Definition at line 202 of file SegmentS2.h.
 { return LineS2<FT>(*this); }
const PointS2< FT > & target () const inline
Definition at line 147 of file SegmentS2.h.
Referenced by SegmentS2< FT >::operator==().
 { return t; }
SegmentS2< FT > transform (const Aff_transformationS2< FT > & t) const inline
Definition at line 214 of file SegmentS2.h.
References Aff_transformationS2< FT >::transform().
 { return SegmentS2<FT>(t.transform(source()), t.transform(target())); }
CGAL_KERNEL_INLINE PointS2< FT > vertex (int i) const
Definition at line 172 of file SegmentS2.h.
 { return (i%2 ==0) ? source() : target(); }
Member Data Documentation
PointS2<FT> s
Definition at line 98 of file SegmentS2.h.
PointS2<FT> t
Definition at line 99 of file SegmentS2.h.
The documentation for this class was generated from the following file:
SegmentS2.h