Rocstar: Mesh::NodalCoordinates Class Reference
Mesh::NodalCoordinates Class Reference
#include <Mesh.H>
Public Member Functions
NodalCoordinates ()
NodalCoordinates (IndexType n)
NodalCoordinates (IndexType n, double *data)
~NodalCoordinates ()
bool good () const
IndexType size () const
IndexType Size () const
void destroy ()
void init ()
void init (IndexType n)
void init (IndexType n, double *data)
void init_node (IndexType n, const GeoPrim::CPoint &)
void init_copy (IndexType n, double *data)
int NNodes () const
double & x (IndexType n=1)
const double & x (IndexType n=1) const
double & y (IndexType n=1)
const double & y (IndexType n=1) const
double & z (IndexType n=1)
const double & z (IndexType n=1) const
double * operator[] (IndexType n)
const double * operator[] (IndexType n) const
const GeoPrim::CPoint closest_point (const GeoPrim::CPoint &p) const
Mesh::IndexType closest_node (const GeoPrim::CPoint &p, double *dist_ptr=NULL) const
Protected Attributes
double * ncdata
IndexType nnodes
Private Attributes
bool mydata
int verblevel
std::ostream * Out
std::ostream * Err
Friends
std::ostream & operator<< (std::ostream &oSt, const Mesh::NodalCoordinates &nc)
std::istream & operator>> (std::istream &iSt, Mesh::NodalCoordinates &nc)
Detailed Description
Definition at line 250 of file Mesh.H.
Constructor & Destructor Documentation
NodalCoordinates ()
Definition at line 14 of file Mesh.C.
   {
     ncdata = NULL;
     nnodes = 0;
     mydata = false;
   };
NodalCoordinates (IndexType n)
Definition at line 20 of file Mesh.C.
   {
     if(n > 0){
       ncdata = new double [3 * n];
       nnodes = n;
       mydata = true;
     }
     else {
       ncdata = NULL;
       nnodes = 0;
       mydata = false;
     }
   };
NodalCoordinates (IndexType n, double * data)
Definition at line 33 of file Mesh.C.
   {
     if((n > 0) && (data != NULL)){
       mydata = false;
       nnodes = n;
       ncdata = data;
     }
     else {
       ncdata = NULL;
       nnodes = 0;
       mydata = false;
     }
   };
~NodalCoordinates ()
Definition at line 46 of file Mesh.C.
 {destroy();};
Member Function Documentation
Mesh::IndexType closest_node (const GeoPrim::CPoint & p, double * dist_ptr = NULL) const
Definition at line 100 of file Mesh.C.
References dist(), i, ncdata, nnodes, and nvc::norm().
   {
     double dist = 1000000;
     Mesh::IndexType reti = 0;
     for(unsigned int i = 0;i < nnodes;i++){
       GeoPrim::CPoint testp(&ncdata[3*i]);
       double testd = (p-testp).norm();
       if(testd < dist){
         dist = testd;
         reti = i + 1;
       }
     }
     if(dist_ptr)
       *dist_ptr = dist;
     return(reti);
   };
const GeoPrim::CPoint closest_point (const GeoPrim::CPoint & p) const
Definition at line 85 of file Mesh.C.
References dist(), i, ncdata, nnodes, and nvc::norm().
   {
     double dist = 1000000;
     GeoPrim::CPoint retval;
     for(unsigned int i = 0;i < nnodes;i++){
       GeoPrim::CPoint testp(&ncdata[3*i]);
       double testd = (p-testp).norm();
       if(testd < dist){
         dist = testd;
         retval = testp;
       }
     }
     return(retval);
   };
void destroy ()
Definition at line 50 of file Mesh.C.
Referenced by init_copy(), and Mesh::MeshUtilityObject::~MeshUtilityObject().
{
     if(ncdata && mydata){
       delete [] ncdata;
       nnodes = 0;
       ncdata = NULL;
       mydata = false;
     }
   };
bool good () const
Definition at line 47 of file Mesh.C.
 { return(ncdata ? true : false);};
void init ()
Definition at line 58 of file Mesh.C.
Referenced by Mesh::GenerateCartesianGrid(), main(), and Mesh::operator>>().
 {destroy();};
void init (IndexType n)
Definition at line 59 of file Mesh.C.
   {
     destroy();
     if(n > 0){
       ncdata = new double [3 * n];
       nnodes = n;
       mydata = true;
     }
   };
void init (IndexType n, double * data)
Definition at line 68 of file Mesh.C.
   {
     destroy();
     if(n > 0){
       ncdata = data;
       nnodes = n;
       mydata = false;
     }
   };
void init_copy (IndexType n, double * data)
Definition at line 117 of file Mesh.C.
References destroy(), mydata, ncdata, and nnodes.
   {
     destroy();
     if(n > 0 && data){
       ncdata = new double [3*n];
       nnodes = n;
       mydata = true;
       std::memcpy(ncdata,data,n*sizeof(double)*3);
     }
   };
void init_node (IndexType n, const GeoPrim::CPoint & point)
Definition at line 78 of file Mesh.C.
References x, CPoint::x(), y, CPoint::y(), z, and CPoint::z().
Referenced by main(), and test().
   {
     this->x(n) = point.x();
     this->y(n) = point.y();
     this->z(n) = point.z();
   };
int NNodes (void) const inline
Definition at line 278 of file Mesh.H.
References nnodes.
Referenced by writeVtkData().
 { return nnodes; };
double* operator[] (IndexType n) inline
Definition at line 310 of file Mesh.H.
References ncdata, and nnodes.
     {
       assert(!(n > nnodes || n == 0));
       return(&ncdata[3*(n-1)]);
     };
const double* operator[] (IndexType n) const inline
Definition at line 315 of file Mesh.H.
References ncdata, and nnodes.
     {
       assert(!(n > nnodes || n == 0));
       return(&ncdata[3*(n-1)]);
     };
Mesh::IndexType size () const
Definition at line 48 of file Mesh.C.
Referenced by Mesh::operator<<(), and Mesh::operator>>().
 { return(nnodes);};
Mesh::IndexType Size () const
Definition at line 49 of file Mesh.C.
Referenced by main(), Mesh::MeshUtilityObject::NumberOfNodes(), stitchGrids(), TRAIL_SurfaceMesh2Window(), and TRAIL_UnstructuredMesh2Pane().
 { return(nnodes);};
double& x (IndexType n = 1) inline
Definition at line 280 of file Mesh.H.
References ncdata, and nnodes.
Referenced by main().
     {
       assert(!(n > nnodes || n == 0));
       return(ncdata[(n-1)*3]);
     };
const double& x (IndexType n = 1) const inline
Definition at line 285 of file Mesh.H.
References ncdata, and nnodes.
     {
       assert(!(n > nnodes || n == 0));
       return(ncdata[(n-1)*3]);
     };
double& y (IndexType n = 1) inline
Definition at line 290 of file Mesh.H.
References ncdata, and nnodes.
Referenced by main(), and stitchGrids().
     {
       assert(!(n > nnodes || n == 0));
       return(ncdata[(3*(n-1))+1]);
     };
const double& y (IndexType n = 1) const inline
Definition at line 295 of file Mesh.H.
References ncdata, and nnodes.
     {
       assert(!(n > nnodes || n == 0));
       return(ncdata[(3*(n-1))+1]);
     };
double& z (IndexType n = 1) inline
Definition at line 300 of file Mesh.H.
References ncdata, and nnodes.
Referenced by main(), and stitchGrids().
     {
       assert(!(n > nnodes || n == 0));
       return(ncdata[(3*(n-1))+2]);
     };
const double& z (IndexType n = 1) const inline
Definition at line 305 of file Mesh.H.
References ncdata, and nnodes.
     {
       assert(!(n > nnodes || n == 0));
       return(ncdata[(3*(n-1))+2]);
     };
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & oSt, const Mesh::NodalCoordinates & nc) friend
Definition at line 2128 of file Mesh.C.
   {
     //  if(nc.size() == 0) return(oSt);
     oSt.setf(std::ios::scientific);
     oSt.setf(std::ios::showpoint);
     oSt << std::setprecision(10) << std::setiosflags(std::ios::left);
     oSt << nc.size();
     if(nc.size() > 0) oSt << "\n";
     for(IndexType n = 1;n <= nc.size() ;n++){
       oSt << std::setw(16) << nc[n][0] << "\t"
           << std::setw(16) << nc[n][1] << "\t"
           << std::setw(16) << nc[n][2];
       if(n != nc.size())
         oSt << std::endl;
     }
     return (oSt);
   }
std::istream& operator>> (std::istream & iSt, Mesh::NodalCoordinates & nc) friend
Definition at line 2108 of file Mesh.C.
   {
     //  if(nc.size() == 0) return (iSt);
     std::string line;
     IndexType nnodes;
     std::getline(iSt,line);
     std::istringstream Istr(line);
     Istr >> nnodes;
     if(nnodes > 0){
       nc.init(nnodes);
       for(IndexType n = 1;n <= nc.size();n++){
         double *inPtr = nc[n];
         std::getline(iSt,line);
         std::istringstream Istr2(line);
         Istr2 >> inPtr[0] >> inPtr[1] >> inPtr[2];
       }
     }
     return(iSt);
   }
Member Data Documentation
std::ostream* Err private
Definition at line 259 of file Mesh.H.
bool mydata private
Definition at line 256 of file Mesh.H.
Referenced by init_copy().
double* ncdata protected
Definition at line 261 of file Mesh.H.
Referenced by closest_node(), closest_point(), init_copy(), operator[](), x(), y(), and z().
IndexType nnodes protected
Definition at line 262 of file Mesh.H.
Referenced by closest_node(), closest_point(), init_copy(), NNodes(), operator[](), x(), y(), and z().
std::ostream* Out private
Definition at line 258 of file Mesh.H.
int verblevel private
Definition at line 257 of file Mesh.H.
The documentation for this class was generated from the following files:
Mesh.H
Mesh.C