Rocstar: rflu_modensight Module Reference
rflu_modensight Module Reference
Data Types
type t_var_info
Public Member Functions
subroutine, public rflu_ens_builddatainfo (pRegion, iServer)
subroutine rflu_ens_closefileflowwrapper (global)
subroutine, public rflu_ens_closefilegeometry (global)
subroutine rflu_ens_closefilescalarvector (global, iFile)
subroutine, public rflu_ens_destroydatainfo (global)
subroutine, public rflu_ens_initpartnumber (global)
integer function, public rflu_ens_mapregion2server (iReg, nRegions, nServers)
subroutine rflu_ens_openfileflowwrapper (global, iServer)
subroutine, public rflu_ens_openfilegeometry (global, iServer)
subroutine rflu_ens_openfilescalarvector (global, iFile, iFileName)
subroutine rflu_ens_restorepartnumber (global)
subroutine rflu_ens_storepartnumber (global)
subroutine rflu_ens_writefilecase (global, iServer)
subroutine, public rflu_ens_writeflowwrapper (pRegion, emptyPartFlagIn)
subroutine, public rflu_ens_writegridwrapper (pRegion, emptyPartFlagIn)
Public Attributes
type(t_var_info) geoinfo
type(t_var_info), dimension(:),
allocatable scalarinfo
type(t_var_info), dimension(:),
allocatable vectorinfo
Private Attributes
character(chrlen), parameter,
private rcsidentstring = '$RCSfile: RFLU_ModENSIGHT.F90,v $ $Revision: 1.6 $'
integer, private nscalars
integer, private nscalars1
integer, private nvectors
integer, private partnumber
integer, private partnumbersave
Detailed Description
Definition at line 43 of file RFLU_ModENSIGHT.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_ens_builddatainfo (type(t_region), pointer pRegion, integer, intent(in) iServer)
Definition at line 121 of file RFLU_ModENSIGHT.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
subroutine rflu_ens_closefileflowwrapper (type(t_global), pointer global)
Definition at line 431 of file RFLU_ModENSIGHT.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_ens_closefilescalarvector().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
subroutine, public rflu_ens_closefilegeometry (type(t_global), pointer global)
Definition at line 508 of file RFLU_ModENSIGHT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
subroutine rflu_ens_closefilescalarvector (type(t_global), pointer global, integer, intent(in) iFile)
Definition at line 580 of file RFLU_ModENSIGHT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_ens_closefileflowwrapper().
subroutine, public rflu_ens_destroydatainfo (type(t_global), pointer global)
Definition at line 645 of file RFLU_ModENSIGHT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
subroutine, public rflu_ens_initpartnumber (type(t_global), pointer global)
Definition at line 730 of file RFLU_ModENSIGHT.F90.
Referenced by rflu_postprocessregions_ens().
integer function, public rflu_ens_mapregion2server (integer, intent(in) iReg, integer, intent(in) nRegions, integer, intent(in) nServers)
Definition at line 778 of file RFLU_ModENSIGHT.F90.
References min().
Referenced by rflu_postprocessregions_ens().
subroutine rflu_ens_openfileflowwrapper (type(t_global), pointer global, integer, intent(in) iServer)
Definition at line 823 of file RFLU_ModENSIGHT.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_ens_openfilescalarvector().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
subroutine, public rflu_ens_openfilegeometry (type(t_global), pointer global, integer, intent(in) iServer)
Definition at line 902 of file RFLU_ModENSIGHT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
subroutine rflu_ens_openfilescalarvector (type(t_global), pointer global, integer, intent(in) iFile, character(chrlen) iFileName)
Definition at line 1000 of file RFLU_ModENSIGHT.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_ens_openfileflowwrapper().
subroutine rflu_ens_restorepartnumber (type(t_global), pointer global)
Definition at line 1077 of file RFLU_ModENSIGHT.F90.
Referenced by rflu_ens_writeflowwrapper().
subroutine rflu_ens_storepartnumber (type(t_global), pointer global)
Definition at line 1122 of file RFLU_ModENSIGHT.F90.
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
subroutine rflu_ens_writefilecase (type(t_global), pointer global, integer, intent(in) iServer)
Definition at line 1170 of file RFLU_ModENSIGHT.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
subroutine, public rflu_ens_writeflowwrapper (type(t_region), pointer pRegion, logical, optional emptyPartFlagIn)
Definition at line 1267 of file RFLU_ModENSIGHT.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_ens_restorepartnumber(), rflu_modensightutils::rflu_ens_writescalar(), and rflu_modensightutils::rflu_ens_writevector().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
subroutine, public rflu_ens_writegridwrapper (type(t_region), pointer pRegion, logical, optional emptyPartFlagIn)
Definition at line 1486 of file RFLU_ModENSIGHT.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modensightutils::rflu_ens_writegrid().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregions_ens().
Member Data Documentation
type(t_var_info) geoinfo
Definition at line 77 of file RFLU_ModENSIGHT.F90.
integer, private nscalars private
Definition at line 69 of file RFLU_ModENSIGHT.F90.
integer, private nscalars1 private
Definition at line 69 of file RFLU_ModENSIGHT.F90.
integer, private nvectors private
Definition at line 69 of file RFLU_ModENSIGHT.F90.
integer, private partnumber private
Definition at line 69 of file RFLU_ModENSIGHT.F90.
integer, private partnumbersave private
Definition at line 69 of file RFLU_ModENSIGHT.F90.
character(chrlen), parameter, private rcsidentstring = '$RCSfile: RFLU_ModENSIGHT.F90,v $ $Revision: 1.6 $' private
Definition at line 66 of file RFLU_ModENSIGHT.F90.
type(t_var_info), dimension(:), allocatable scalarinfo
Definition at line 78 of file RFLU_ModENSIGHT.F90.
type(t_var_info), dimension(:), allocatable vectorinfo
Definition at line 79 of file RFLU_ModENSIGHT.F90.
The documentation for this module was generated from the following file:
RFLU_ModENSIGHT.F90