Rocstar: Generic_element_2 Class Reference
Generic_element_2 Class Reference
Encapsulation of the element-wise computations for two-dimensional elements.
#include <Generic_element_2.h>
Public Types
enum { MAX_SIZE = 9 }
typedef Generic_element_2 Self
typedef double Real
typedef unsigned int Size
typedef SURF::Vector_2< Real > Vector_2
typedef SURF::Vector_3< Real > Vector_3
typedef Vector_2 Nat_coor
Public Member Functions
Generic_element_2 (Size ne, Size nn=0)
Constructor.
Size size_of_edges () const
Number of edges.
Size size_of_nodes () const
Number of nodes.
Size order () const
Degree of the element. 1 for linear and 2 for quadratic.
Interpolation \{
void shape_func (const Nat_coor &nc, Real N[]) const
Evaluates the shape functions of the element and output the barycentric coordinates into the array N.
void shape_func_deriv (const Nat_coor &nc, Vector_2 Np[]) const
Evaluates the derivatives of the shape functions.
template<class Field , class Value >
void interpolate (const Field &f, const Nat_coor &nc, Value *v) const throw (int)
Interpolates the field data at a given point.
template<class Field >
void interpolate (const Field &f, const Nat_coor &nc, Real *v) const throw (int)
Customized interpolation for primitive data types.
template<class Field , class Value >
void interpolate (const Field &f, const Real xi, Value *v) const throw (int)
Interpolates the field data at a given point on an edge.
template<class Field >
void interpolate (const Field &f, const Real xi, Real *v) const throw (int)
Customized interpolation for primitive data types.
template<class Field >
Field_traits< Field >::Value interpolate (const Field &f, const Nat_coor &nc) const throw (int)
Interpolates the field data at a given point and return the result.
template<class Field >
Field_traits< Field >::Value interpolate (const Field &f, const Real xi) const throw (int)
Interpolates the field data at a given point on an edge and return the result.
template<class Field , class Value >
void interpolate_to_center (const Field &f, Value *v) const throw (int)
Interpolates the field data to the center of the element.
template<class Field >
Field_traits< Field >::Value interpolate_to_center (const Field &f) const throw (int)
Interpolates the field data to the center and return the value.
Gradient
template<class Field >
void Jacobian (const Field &f, const Nat_coor &nc, Vector_3 J[2]) const
Evaluates the Jacobian at a given point.
template<class Field >
void Jacobian (const Field &f, const Real xi, Vector_3 &v) const
template<class Pnts >
void gradients (const Pnts &ps, const Nat_coor &nc, Vector_3 grads[3]) const
Evaluates the gradient of the shape functions.
template<class Field >
Real Jacobian_det (const Field &f, const Nat_coor &nc) const
Evaluates the determinant of the Jacobian (dx/dxi,dx/deta).
template<class Field >
Real Jacobian_det (const Field &f1, const Field &f2, Real alpha, const Nat_coor &nc2) const
Evaluates the determinant of the Jacobian (dx/dxi,dx/deta), where x is (1-alpha)*f1+alpha*f2.
Gaussian quadrature rules \{
Size get_num_gp (const Size doa=0) const
Get the number of Gauss points.
Real get_gp_weight (const Size i, const Size doa=0) const
Get the weight associated with a Gauss point.
void get_gp_nat_coor (const Size i, Nat_coor &nc, const Size doa=0) const
Get the natrual coordinate associated with a Gauss point.
Protected Member Functions
void solve (const Vector_3 M[2], Vector_3 x[], const Vector_2 b[]) const
template<class Field , class Value >
void interpolate_nopt (const Field &f, const Nat_coor &nc, Value *v) const throw (int)
Nonoptimized version of interpolation.
template<class Field , class Value >
void interpolate_nopt (const Field &f, const Real xi, Value *v) const throw (int)
Nonoptimized version of interpolation.
Private Attributes
const Size _nedges
const Size _nnodes
const Size _order
Detailed Description
Encapsulation of the element-wise computations for two-dimensional elements.
It supports linear/quadratic triangle/quadrilateral elements. It does not contain any geometric or field data but only defines the master element. Geometric or field data data should be provided as parameters to the member functions as necessary. NOTE: We normalized the natural (local) coodinates so that they always fall between 0 and 1.
Definition at line 94 of file Generic_element_2.h.
Member Typedef Documentation
typedef Vector_2 Nat_coor
Definition at line 101 of file Generic_element_2.h.
typedef double Real
Definition at line 97 of file Generic_element_2.h.
typedef Generic_element_2 Self
Definition at line 96 of file Generic_element_2.h.
typedef unsigned int Size
Definition at line 98 of file Generic_element_2.h.
typedef SURF::Vector_2<Real> Vector_2
Definition at line 99 of file Generic_element_2.h.
typedef SURF::Vector_3<Real> Vector_3
Definition at line 100 of file Generic_element_2.h.
Member Enumeration Documentation
anonymous enum
Enumerator
MAX_SIZE
Definition at line 103 of file Generic_element_2.h.
 { MAX_SIZE = 9}; // MAX_NV is maximum number of nodes per element.
Constructor & Destructor Documentation
SURF_BEGIN_NAMESPACE Generic_element_2 (Size ne, Size nn = 0)
Constructor.
Parameters
ne specifies the number of edges.
nn specifies the number of nodes.
Definition at line 32 of file Generic_element_2.C.
References _nnodes.
   : _nedges( ne), _nnodes( std::max(ne,nn)), _order( 1+ (_nedges!=_nnodes)) {
   assert( ne==3 || ne==4);
   assert( _nnodes==ne || _nnodes==ne+ne);
 }
Member Function Documentation
void get_gp_nat_coor (const Size i, Nat_coor & nc, const Size doa = 0) const
Get the natrual coordinate associated with a Gauss point.
Definition at line 182 of file Generic_element_2.C.
References _nedges, _order, and max().
Referenced by compute_lbop_weights(), and get_face_volume().
{
   if ( std::max( doa, _order)==1) {
     if ( _nedges==3)
       nc = Nat_coor( 0.333333333333333, 0.333333333333333);
     else {
       const Real coors[4][2] = { {0.2113248654051871, 0.2113248654051871},
                                  {0.2113248654051871, 0.7886751345948129},
                                  {0.7886751345948129, 0.2113248654051871},
                                  {0.7886751345948129, 0.7886751345948129}};
       nc = Nat_coor( coors[i][0], coors[i][1]);
     }
   }
   else if ( std::max( doa, _order)==2) {
     if ( _nedges == 3) {
       const Real coors[3][2] = { {0.666666666666667, 0.166666666666667},
                                  {0.166666666666667, 0.666666666666667},
                                  {0.166666666666667, 0.166666666666667}};
       nc = Nat_coor( coors[i][0], coors[i][1]);
     }
     else {
       const Real coors[9][2] = { {0.112701665379258, 0.112701665379258},
                                  {0.887298334620742, 0.112701665379258},
                                  {0.887298334620742, 0.887298334620742},
                                  {0.112701665379258, 0.887298334620742},
                                  {0.5,               0.112701665379258},
                                  {0.887298334620742, 0.5              },
                                  {0.5,               0.887298334620742},
                                  {0.112701665379258, 0.5              },
                                  {0.5,               0.5              }};
       nc = Nat_coor( coors[i][0], coors[i][1]);
     }
   }
   else {
     assert( std::max( doa, _order)==4 && _nedges==3);
     const Real coors[6][2] = { {0.816847572980459, 0.091576213509771},
                                {0.091576213509771, 0.816847572980459},
                                {0.091576213509771, 0.091576213509771},
                                {0.108103018168070, 0.445948490915965},
                                {0.445948490915965, 0.108103018168070},
                                {0.445948490915965, 0.445948490915965}};
     nc = Nat_coor( coors[i][0], coors[i][1]);
   }
 }
Generic_element_2::Real get_gp_weight (const Size i, const Size doa = 0) const
Get the weight associated with a Gauss point.
Definition at line 159 of file Generic_element_2.C.
References _nedges, _order, and max().
Referenced by compute_lbop_weights(), and get_face_volume().
{
   if ( std::max( doa, _order)==1) {
     return (_nedges == 3) ? 1./2. : 1./4.;
   }
   else if ( std::max( doa, _order)==2) {
     if ( _nedges==3)
       return 1./6.;
     else {
       if (i==8) return 16./81.;
       else if (i<4) return 25./324.;
       else return 10./81.;
     }
   }
   else {
     assert( std::max( doa, _order)==4 && _nedges==3);
     return (i<3) ? 0.054975871827661 : 0.1116907948390055;
   }
 }
Generic_element_2::Size get_num_gp (const Size doa = 0) const
Get the number of Gauss points.
Definition at line 145 of file Generic_element_2.C.
References _nedges, _order, and max().
Referenced by compute_lbop_weights(), and get_face_volume().
{
   if ( std::max( doa, _order)==1) {
     return _nedges==3 ? 1 : 4;
   }
   else if ( std::max( doa, _order)==2) {
     return _nedges==3 ? 3: 9;
   }
   else {
     assert( std::max( doa, _order)==4 && _nedges==3);
     return _nedges==3 ? 6: 9;
   }
 }
void gradients (const Pnts & ps, const Nat_coor & nc, Vector_3 grads[3]) const
Evaluates the gradient of the shape functions.
Definition at line 506 of file Generic_element_2.h.
References Jacobian(), shape_func_deriv(), and solve().
{
   Vector_3 J[2];
   Jacobian( pnts, nc, J);
   Vector_2 deriv[9];
   shape_func_deriv( nc, deriv);
   solve( J, grads, deriv);
 }
void interpolate (const Field & f, const Nat_coor & nc, Value * v) const throw (int)
Interpolates the field data at a given point.
Definition at line 242 of file Generic_element_2.h.
References v.
Referenced by get_face_volume(), and interpolate().
{
   const Real xi = nc[0], eta = nc[1];
   if ( eta == 0) // Interpolate on the edge.
   { interpolate( f, xi, v); return; }
   *v = f[0];
   switch ( _nnodes) {
   case 3:
     // *v = f[0] + xi*(f[1]-f[0]) + eta*(f[2]-f[0]);
     *v += ((f[1]-f[0])*=xi) += ((f[2]-f[0])*=eta);
     return;
   case 4: {
     //  *v = f[0] + xi * (1.-eta) * (f[1]-f[0])
     //    + eta * ( f[3]-f[0] + xi *(f[2]-f[3]));
     *v += ((f[1]-f[0]) *= (xi * (1.-eta)))
        += ((f[3]-f[0]) *= eta)
        += ((f[2]-f[3]) *= xi*eta);
     return;
   }
   case 6: {
     const Real zeta=1.-xi-eta;
     //  *v = f[0] + xi*( (2.*xi-1.)*(f[1]-f[0]) + 4.*zeta*(f[3]-f[0])) +
     //    eta * ( (2.*eta-1.)*(f[2]-f[0]) + 4.*zeta*(f[5]-f[0])) +
     //    4.*xi*eta*(f[4]-f[0]);
     *v += ((f[1]-f[0]) *= xi * (2.*xi-1.))
        += ((f[3]-f[0]) *= 4.* xi * zeta)
        += ((f[2]-f[0]) *= eta * (2.*eta-1.))
        += ((f[5]-f[0]) *= 4. * eta * zeta)
        += ((f[4]-f[0]) *= 4.*xi*eta);
     return;
   }
   case 8: {
     const Real xi_minus = 1. - xi;
     const Real eta_minus = 1. - eta;
     //  *v = f[0] + xi * eta_minus * (f[1]-f[0]) +
     //     eta * ( f[3]-f[0] + xi *(f[2]-f[3])) -
     //     2.*xi*xi_minus*eta_minus*( (f[0]-f[4])+(f[1]-f[4])) -
     //     2.*xi*xi_minus*eta*( (f[2]-f[6])+(f[3]-f[6])) -
     //     2.*xi*eta*eta_minus*( (f[1]-f[5])+(f[2]-f[5])) -
     //     2.*xi_minus*eta*eta_minus*( (f[0]-f[7])+(f[3]-f[7]));
     *v += ((f[1]-f[0]) *= eta * (2.*eta-1.))
        += ((f[3]-f[0]) *= eta)
        += ((f[2]-f[3]) *= xi * eta)
        -= ((((f[0]-f[4])+=(f[1]-f[4])) *= 2.*xi*xi_minus*eta_minus)
            += (((f[2]-f[6])+=(f[3]-f[6])) *= 2.*xi*xi_minus*eta)
            += (((f[1]-f[5])+=(f[2]-f[5])) *= 2.*xi*eta*eta_minus)
            += (((f[0]-f[7])+=(f[3]-f[7])) *= 2.*xi_minus*eta*eta_minus));
     return;
   }
   default:
     throw(-1);
   }
 }
void interpolate (const Field & f, const Nat_coor & nc, Real * v) const throw (int) inline
Customized interpolation for primitive data types.
Definition at line 136 of file Generic_element_2.h.
References interpolate_nopt(), and v.
   { interpolate_nopt( f, nc, v); }
void interpolate (const Field & f, const Real xi, Value * v) const throw (int)
Interpolates the field data at a given point on an edge.
Definition at line 351 of file Generic_element_2.h.
References v.
{
   *v = f[0];
   switch ( _nnodes) {
   case 3:
   case 4:
     // *v = f[0] + xi*(f[1]-f[0]);
     *v += ((f[1]-f[0]) *= xi);
     return;
   case 6: {
     // *v = f[0] + xi*( (2.*xi-1.)*(f[1]-f[0]) + 4.*(1.-xi)*(f[3]-f[0]));
     *v += ((f[1]-f[0]) *= xi*(2.*xi-1.))
        += ((f[3]-f[0]) *= 4.*xi*(1.-xi));
     return;
   }
   case 8: {
     // *v = f[0] + xi * (f[1]-f[0]) - 2.*xi*(1.-xi)*( (f[0]-f[4])+(f[1]-f[4]));
     *v += ((f[1]-f[0]) *= xi)
        -= (((f[0]-f[4])+=(f[1]-f[4])) *= 2.*xi*(1.-xi));
     return;
   }
   default:
     throw(-1);
   }
 }
void interpolate (const Field & f, const Real xi, Real * v) const throw (int) inline
Customized interpolation for primitive data types.
Definition at line 147 of file Generic_element_2.h.
References interpolate_nopt(), and v.
   { interpolate_nopt( f, xi, v); }
Field_traits<Field>::Value interpolate (const Field & f, const Nat_coor & nc) const throw (int) inline
Interpolates the field data at a given point and return the result.
Definition at line 154 of file Generic_element_2.h.
References interpolate(), and v.
{
     typename Field_traits<Field>::Value v;
     this->interpolate( f, nc, &v); // Use this-> to get around a stupid bug in SGI C++ compiler
     return v;
   }
Field_traits<Field>::Value interpolate (const Field & f, const Real xi) const throw (int) inline
Interpolates the field data at a given point on an edge and return the result.
Definition at line 163 of file Generic_element_2.h.
References interpolate(), and v.
{
     typename Field_traits<Field>::Value v;
     interpolate( f, xi, &v);
     return v;
   }
void interpolate_nopt (const Field & f, const Nat_coor & nc, Value * v) const throw (int) protected
Nonoptimized version of interpolation.
Definition at line 303 of file Generic_element_2.h.
References v.
Referenced by interpolate().
{
   const Real xi = nc[0], eta = nc[1];
   if ( eta == 0) // Interpolate on the edge.
   { interpolate_nopt( f, xi, v); return; }
   *v = f[0];
   switch ( _nnodes) {
   case 3:
     *v += ((f[1]-f[0])*xi) + ((f[2]-f[0])*eta);
     return;
   case 4: {
     *v += ((f[1]-f[0]) * (xi * (1.-eta)))
        +  ((f[3]-f[0]) * eta)
        +  ((f[2]-f[3]) * xi*eta);
     return;
   }
   case 6: {
     const Real zeta=1.-xi-eta;
     *v += ((f[1]-f[0]) * xi * (2.*xi-1.))
        +  ((f[3]-f[0]) * 4.* xi * zeta)
        +  ((f[2]-f[0]) * eta * (2.*eta-1.))
        +  ((f[5]-f[0]) * 4. * eta * zeta)
        +  ((f[4]-f[0]) * 4.*xi*eta);
     return;
   }
   case 8: {
     const Real xi_minus = 1. - xi;
     const Real eta_minus = 1. - eta;
     *v += ((f[1]-f[0]) * eta * (2.*eta-1.))
        +  ((f[3]-f[0]) * eta)
        +  ((f[2]-f[3]) * xi * eta)
        -  ((((f[0]-f[4])+(f[1]-f[4])) * 2.*xi*xi_minus*eta_minus)
            + (((f[2]-f[6])+(f[3]-f[6])) * 2.*xi*xi_minus*eta)
            + (((f[1]-f[5])+(f[2]-f[5])) * 2.*xi*eta*eta_minus)
            + (((f[0]-f[7])+(f[3]-f[7])) * 2.*xi_minus*eta*eta_minus));
     return;
   }
   default:
     throw(-1);
   }
 }
void interpolate_nopt (const Field & f, const Real xi, Value * v) const throw (int) protected
Nonoptimized version of interpolation.
Definition at line 379 of file Generic_element_2.h.
References v.
{
   *v = f[0];
   switch ( _nnodes) {
   case 3:
   case 4:
     *v += ((f[1]-f[0]) * xi);
     return;
   case 6: {
     *v += ((f[1]-f[0]) * xi*(2.*xi-1.))
        +  ((f[3]-f[0]) * 4.*xi*(1.-xi));
     return;
   }
   case 8: {
     *v += ((f[1]-f[0]) * xi)
        -  (((f[0]-f[4])+(f[1]-f[4])) * 2.*xi*(1.-xi));
     return;
   }
   default:
     throw(-1);
   }
 }
void interpolate_to_center (const Field & f, Value * v) const throw (int)
Interpolates the field data to the center of the element.
Definition at line 405 of file Generic_element_2.h.
References i, v, and x.
Referenced by interpolate_to_center().
{
   if ( _order == 1) {
     *v = f[0];
     for ( Size i=1; i<_nnodes; ++i) *v += f[i];
     *v /= _nnodes;
   }
   else {
     Real x = size_of_edges()==3 ? 1./3. : 1./2.;
     interpolate( f, Nat_coor(x, x), v);
   }
 }
Field_traits<Field>::Value interpolate_to_center (const Field & f) const throw (int) inline
Interpolates the field data to the center and return the value.
Definition at line 176 of file Generic_element_2.h.
References interpolate_to_center(), and v.
{
     typename Field_traits<Field>::Value v;
     interpolate_to_center( f, &v);
     return v;
   }
void Jacobian (const Field & f, const Nat_coor & nc, Vector_3 J[2]) const
Evaluates the Jacobian at a given point.
Definition at line 419 of file Generic_element_2.h.
References _nnodes.
Referenced by Window_manifold_2::elements_to_nodes(), get_deformed_normal(), get_face_volume(), get_normal(), gradients(), and Jacobian_det().
{
   switch (_nnodes) {
   case 3:
     J[0] = f[1]-f[0]; J[1] = f[2]-f[0];
     return;
   case 4: {
     const Real xi = nc[0], xi_minus = 1. - xi;
     const Real eta = nc[1], eta_minus = 1. - eta;
     //  J[0] = eta_minus * ( f[1] - f[0]) + eta * ( f[2] - f[3]);
     J[0] = ((f[1]-f[0]) *= eta_minus) += (( f[2]-f[3]) *= eta );
     //  J[1] = xi_minus * ( f[3] - f[0]) + xi * ( f[2] - f[1]);
     J[1] = ((f[3]-f[0]) *= xi_minus) += (( f[2]-f[1]) *= xi);
     return;
   }
   case 6: {
     const Real xi=nc[0], eta=nc[1], zeta=1.-xi-eta;
     // J[0] = (4.*xi -1.)*(f[1]-f[0]) +
     //   (4.*zeta-4.*xi)*(f[3]-f[0]) + 4.*eta*(f[4] -f[5]);
     J[0] = ((f[1]-f[0]) *= 4.*xi -1.)
         += ((f[3]-f[0]) *= 4.*zeta-4*xi)
         += ((f[4]-f[5]) *= 4.*eta);
     // J[1] = (4.*eta -1.)*(f[2]-f[0]) +
     //   (4.*zeta-4.*eta)*(f[5]-f[0]) + 4.*xi*(f[4] -f[3]);
     J[1] = ((f[2]-f[0]) *= 4.*eta -1.)
         += ((f[5]-f[0]) *= 4*zeta-4*eta)
         += ((f[4]-f[3]) *= 4.*xi);
     return;
   }
   case 8: {
     const Real xi = nc[0], xi_minus = 1. - xi;
     const Real eta = nc[1], eta_minus = 1. - eta;
     //  J[0] = eta_minus * ( f[1] - f[0]) + eta * ( f[2] - f[3]) -
     //    2.*eta_minus*(xi_minus-xi)*( (f[0]-f[4])+(f[1]-f[4])) -
     //    2.*eta*(xi_minus-xi)*( (f[2]-f[6])+(f[3]-f[6])) -
     //    2.*eta*eta_minus*( (f[1]-f[5])+(f[2]-f[5])-(f[0]-f[7])-(f[3]-f[7]));
     J[0] = ((f[1]-f[0]) *= eta_minus) += ((f[2]-f[3]) *= eta)
         -= ((((f[0]-f[4])+=(f[1]-f[4])) *= 2.*eta_minus*(xi_minus-xi))
             += (((f[2]-f[6])+=(f[3]-f[6])) *= 2.*eta*(xi_minus-xi))
             += (((f[1]-f[5])+=(f[2]-f[5])-=((f[0]-f[7])+=(f[3]-f[7])))
                 *= 2.*eta*eta_minus));
     //  J[1] = xi_minus * ( f[3] - f[0]) + xi * ( f[2] - f[1]) -
     //    2.*xi*(eta_minus-eta)*( (f[1]-f[5])+(f[2]-f[5]))-
     //    2.*xi_minus*(eta_minus-eta)*( (f[0]-f[7])+(f[3]-f[7])) -
     //    2.*xi*xi_minus*( (f[2]-f[6])-(f[3]-f[6])-(f[0]-f[4])+(f[1]-f[4]));
     ((J[1] = f[3]-f[0]) *= xi_minus) += ((f[2]-f[1]) *= xi)
           -= ((((f[1]-f[5])+=(f[2]-f[5])) *= 2.*xi*(eta_minus-eta))
               += (((f[0]-f[7])+=(f[3]-f[7])) *= 2.*xi_minus*(eta_minus-eta))
               += (((f[2]-f[6])+=(f[1]-f[4])-=((f[3]-f[6])+=(f[0]-f[4])))
                   *= 2.*xi*xi_minus));
     return;
   }
   default:
     abort(); // Should never reach here
   }
 }
void Jacobian (const Field & f, const Real xi, Vector_3 & v) const
Definition at line 483 of file Generic_element_2.h.
References _nnodes.
{
   switch ( _nnodes) {
   case 3:
   case 4:
     v = f[1] - f[0]; return;
   case 6:
     // return (4.*xi -1.)*(f[1]-f[0]) + (4.-8.*xi)*(f[3]-f[0]);
     v = (((f[1]-f[0]) *= 4.*xi -1.) += ((f[3]-f[0]) *= 4.-8.*xi)); return;
   case 8:
     // return (f[1]-f[0]) - (2.-4.*xi)*( (f[0]-f[4])+(f[1]-f[4]));
     v = ((f[1]-f[0]) -= (((f[0]-f[4])+=(f[1]-f[4])) *= 2.-4*xi)); return;
   default:
     assert( false);
     v = Vector_3(0,0,0);
     return;
   }
 }
Generic_element_2::Real Jacobian_det (const Field & f, const Nat_coor & nc) const
Evaluates the determinant of the Jacobian (dx/dxi,dx/deta).
Definition at line 521 of file Generic_element_2.h.
References Vector_3< Type >::cross_product(), Jacobian(), and sqrt().
{
   Vector_3 J[2];
   Jacobian( f, nc, J);
   return std::sqrt( Vector_3::cross_product( J[0], J[1]).squared_norm());
 }
Generic_element_2::Real Jacobian_det (const Field & f1, const Field & f2, Real alpha, const Nat_coor & nc2) const
Evaluates the determinant of the Jacobian (dx/dxi,dx/deta), where x is (1-alpha)*f1+alpha*f2.
Used by Rocface.
Definition at line 533 of file Generic_element_2.h.
References Vector_3< Type >::cross_product(), Jacobian(), and sqrt().
{
   Vector_3 J1[2],J2[2];
   if ( alpha!=1.) {
     Jacobian( f1, nc, J1);
   }
   if ( alpha!=0.) {
     Jacobian( f2, nc, J2);
     if ( alpha!=1) {
       J2[0] = (1-alpha)*J1[0]+alpha*J2[0];
       J2[1] = (1-alpha)*J1[1]+alpha*J2[1];
     }
   }
   else {
     J2[0] = J1[0]; J2[1] = J1[1];
   }
   return std::sqrt( Vector_3::cross_product( J2[0], J2[1]).squared_norm());
 }
Size order () const inline
Degree of the element. 1 for linear and 2 for quadratic.
Definition at line 117 of file Generic_element_2.h.
References _order.
Referenced by rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil_1d_g(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_modstencilsvert::rflu_buildstencilvert2cell(), rflu_moddifferentiationbfaces::rflu_computegradbfaces_1d(), rflu_moddifferentiationcells::rflu_computegradcells_1d(), rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_computestencilsize(), rflu_modstencilsutils::rflu_computestencilsize(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_modweights::rflu_computewtsbf2c(), rflu_modweights::rflu_computewtsbf2cwrapper(), rflu_modweights::rflu_computewtsc2c(), rflu_modweights::rflu_computewtsc2cwrapper(), rflu_modweights::rflu_computewtsf2c(), rflu_modweights::rflu_computewtsf2cwrapper(), rflu_modweights::rflu_createwtsbf2c(), rflu_modweights::rflu_createwtsbf2cwrapper(), rflu_modweights::rflu_createwtsc2c(), rflu_modweights::rflu_createwtsc2cwrapper(), rflu_modweights::rflu_createwtsf2c(), rflu_modweights::rflu_createwtsf2cwrapper(), and updatetbcpiecewise().
 { return _order; }
void shape_func (const Nat_coor & nc, Real N[]) const
Evaluates the shape functions of the element and output the barycentric coordinates into the array N.
Definition at line 42 of file Generic_element_2.C.
References _nnodes.
{
   switch ( _nnodes) {
   case 3: {
     N[0] = 1. - nc[0] - nc[1];
     N[1] = nc[0];
     N[2] = nc[1];
     return;
   }
   case 4: {
     const Real xi = nc[0], xi_minus = 1. - xi;
     const Real eta = nc[1], eta_minus = 1. - eta;
     N[0] = xi_minus * eta_minus;
     N[1] = xi * eta_minus;
     N[2] = xi * eta;
     N[3] = xi_minus * eta;
     return;
   }
   case 6: {
     const Real xi=nc[0], eta=nc[1], zeta=1.-xi-eta;
     N[0] = 2*zeta*zeta-zeta;
     N[1] = 2*xi*xi-xi;
     N[2] = 2*eta*eta-eta;
     N[3] = 4*zeta*xi;
     N[4] = 4*xi*eta;
     N[5] = 4*eta*zeta;
     return;
   }
   case 8: {
     const Real xi = nc[0], xi_minus = 1. - xi;
     const Real eta = nc[1], eta_minus = 1. - eta;
     N[0] = xi_minus * eta_minus * (1. - 2.*xi - 2.*eta);
     N[1] = xi * eta_minus * (-1. + 2.*xi - 2.*eta);
     N[2] = xi * eta * (-3. + 2.*xi + 2.*eta);
     N[3] = xi_minus * eta * (-1. - 2.*xi + 2.*eta);
     N[4] = 4. * xi_minus * eta_minus * xi;
     N[5] = 4. * xi * eta_minus * eta;
     N[6] = 4. * xi * eta * xi_minus;
     N[7] = 4. * xi_minus * eta * eta_minus;
     return;
   }
   default:
     abort(); // Should never reach here
   }
 }
void shape_func_deriv (const Nat_coor & nc, Vector_2 Np[]) const
Evaluates the derivatives of the shape functions.
Definition at line 94 of file Generic_element_2.C.
References _nnodes.
Referenced by gradients().
{
   switch ( _nnodes) {
   case 3: {
     Np[0][0] = -1;   Np[0][1] = -1.;
     Np[1][0] = 1;    Np[1][1] = 0;
     Np[2][0] = 0;    Np[2][1] = 1;
     return;
   }
   case 4: {
     const Real xi = nc[0], xi_minus = 1. - xi;
     const Real eta = nc[1], eta_minus = 1. - eta;
     Np[0][0] = -eta_minus;   Np[0][1] = -xi_minus;
     Np[1][0] = eta_minus;    Np[1][1] = -xi;
     Np[2][0] = eta;          Np[2][1] = xi;
     Np[3][0] = -eta;         Np[3][1] = xi_minus;
     return;
   }
   case 6: {
     const Real xi=nc[0], eta=nc[1], zeta=1.-xi-eta;
     Np[0][0] = 1.-4.*zeta;   Np[0][1] = 1.-4.*zeta;
     Np[1][0] = 4.*xi-1;      Np[1][1] = 0;
     Np[2][0] = 0;            Np[2][1] = 4*eta-1;
     Np[3][0] = 4*(zeta-xi);  Np[3][1] = -4*xi;
     Np[4][0] = 4*eta;        Np[4][1] = 4*xi;
     Np[5][0] = -4*eta;       Np[5][1] = 4*(zeta-eta);
     return;
   }
   case 8: {
     const Real xi = nc[0], xi_minus = 1. - xi;
     const Real eta = nc[1], eta_minus = 1. - eta;
     Np[0][0] = eta_minus * ( -3+4*xi+2*eta);  Np[0][1] = xi_minus * ( -3+4*eta+2*xi);
     Np[1][0] = eta_minus * ( -1+4*xi-2*eta);  Np[1][1] = xi * (1-2*xi+4.*eta);
     Np[2][0] = eta * ( -3+4*xi+2*eta);        Np[2][1] = xi * ( -3+4*eta+2*xi);
     Np[3][0] = eta * ( 1 + 4*xi-2*eta);       Np[3][1] = xi_minus * ( -1-2*xi+4.*eta);
     Np[4][0] = eta_minus * (-8 * xi);         Np[4][1] = -4*xi*xi_minus;
     Np[5][0] = 4*eta_minus*eta;               Np[5][1] = xi*(-8*eta);
     Np[6][0] = eta * (-8 * xi);               Np[6][1] = 4*xi*xi_minus;
     Np[7][0] = -4*eta*eta_minus;              Np[7][1] = xi_minus*(-8*eta);
   }
   default:
     abort(); // Should never reach here
   }
 }
Size size_of_edges () const inline
Number of edges.
Definition at line 113 of file Generic_element_2.h.
References _nedges.
 { return _nedges; }
Size size_of_nodes () const inline
Number of nodes.
Definition at line 115 of file Generic_element_2.h.
References _nnodes.
Referenced by solve().
 { return _nnodes; }
void solve (const Vector_3 M[2], Vector_3 x[], const Vector_2 b[]) const protected
Definition at line 231 of file Generic_element_2.C.
References Vector_3< Type >::cross_product(), i, size_of_nodes(), and Vector_3< Type >::squared_norm().
Referenced by gradients().
{
   Real area_sq = Vector_3::cross_product( J[0], J[1]).squared_norm();
   Vector_2 t[2] = { Vector_2( J[1]*J[1]/area_sq, J[0]*J[1]/-area_sq),
                     Vector_2( J[1]*J[0]/-area_sq,  J[0]*J[0]/area_sq) };
   // Jinv = J'(JJ')^-1, containing column vectors
   Vector_3 Jinv[2] = { J[0]*t[0][0]+=J[1]*t[1][0], J[0]*t[0][1]+=J[1]*t[1][1]};
   for ( unsigned int i=0; i<size_of_nodes(); ++i) {
     x[i] = Jinv[0]*b[i][0] += Jinv[1]*b[i][1];
   }
 }
Member Data Documentation
const Size _nedges private
Definition at line 236 of file Generic_element_2.h.
Referenced by get_gp_nat_coor(), get_gp_weight(), get_num_gp(), and size_of_edges().
const Size _nnodes private
Definition at line 237 of file Generic_element_2.h.
Referenced by Generic_element_2(), Jacobian(), shape_func(), shape_func_deriv(), and size_of_nodes().
const Size _order private
Definition at line 238 of file Generic_element_2.h.
Referenced by get_gp_nat_coor(), get_gp_weight(), get_num_gp(), and order().
The documentation for this class was generated from the following files:
Generic_element_2.h
Generic_element_2.C