Rocstar: Vector_3< Type > Class Template Reference
Vector_3< Type > Class Template Reference
Some basic geometric data types.
#include <mapbasic.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Vector_3_base RVector_3
Public Member Functions
Vector_3 ()
Vector_3 (Type t)
Vector_3 (Null_vector)
Vector_3 (Type a, Type b, Type c)
Type & operator[] (const int i)
const Type & operator[] (const int i) const
Type x () const
Type y () const
Type z () const
Vector_3 & operator+= (const Type t)
Assign operators.
Vector_3 & operator+= (const Vector_3 &v)
Vector_3 & operator-= (const Type t)
Vector_3 & operator-= (const Vector_3 &v)
Vector_3 & operator*= (const Type t)
Vector_3 & operator*= (const Vector_3 &v)
Vector_3 & operator/= (const Type t)
Vector_3 & operator/= (const Vector_3 &v)
Vector_3 operator+ (const Type t) const
Arithmatic operators.
Vector_3 operator+ (const Vector_3 &v) const
Vector_3 operator- (const Type t) const
Vector_3 operator- (const Vector_3 &v) const
Vector_3 operator* (const Type t) const
Vector_3 operator/ (const Type t) const
Type operator* (const Vector_3 &v) const
Vector_3 operator- () const
Type squared_norm () const
Type norm () const
Vector_3 & normalize ()
Vector_3 & neg ()
bool operator== (const Vector_3 &p) const
bool operator!= (const Vector_3 &p) const
bool operator< (const Vector_3 &v) const
bool is_null () const
Vector_3 ()
Vector_3 (const CGAL::Vector_3< R > &v)
Vector_3 (const RVector_3 &v)
Vector_3 (const Null_vector &v)
Vector_3 (const RT &x, const RT &y, const RT &z)
Vector_3 (const RT &x, const RT &y, const RT &z, const RT &w)
bool operator== (const CGAL::Vector_3< R > &v) const
bool operator!= (const CGAL::Vector_3< R > &v) const
bool operator== (const Null_vector &v) const
bool operator!= (const Null_vector &v) const
RT hx () const
RT hy () const
RT hz () const
RT hw () const
FT x () const
FT y () const
FT z () const
RT homogeneous (int i) const
FT cartesian (int i) const
FT operator[] (int i) const
int dimension () const
CGAL::Vector_3< R > operator+ (const CGAL::Vector_3< R > &w) const
CGAL::Vector_3< R > operator- (const CGAL::Vector_3< R > &w) const
CGAL::Vector_3< R > operator- () const
FT operator* (const CGAL::Vector_3< R > &w) const
CGAL::Vector_3< R > operator* (const RT &c) const
CGAL::Vector_3< R > operator* (const Quotient< RT > &q) const
CGAL::Vector_3< R > operator/ (const Quotient< RT > &q) const
CGAL::Vector_3< R > operator/ (const RT &c) const
CGAL::Direction_3< R > direction () const
CGAL::Vector_3< R > transform (const CGAL::Aff_transformation_3< R > &t) const
Static Public Member Functions
static Vector_3 cross_product (const Vector_3 &v, const Vector_3 &w)
Protected Attributes
Type _x
Type _y
Type _z
Private Member Functions
Vector_3 (const CGAL::Point_3< R > &p)
Vector_3 (const CGAL::Direction_3< R > &d)
Friends
CGAL_FRIEND_INLINE
CGAL::Vector_3< R >
point_to_vector_conversion CGAL_NULL_TMPL_ARGS (const CGAL::Point_3< R > &p)
Detailed Description
template<class Type>
class Vector_3< Type >
Some basic geometric data types.
Definition at line 54 of file mapbasic.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 82 of file Vector_3.h.
typedef R_ R
Definition at line 80 of file Vector_3.h.
typedef R::RT RT
Definition at line 81 of file Vector_3.h.
typedef R::Vector_3_base RVector_3
Definition at line 83 of file Vector_3.h.
Constructor & Destructor Documentation
Vector_3 () inline
Definition at line 56 of file mapbasic.h.
Referenced by Vector_3< Real >::cross_product(), Vector_3< Real >::operator*(), Vector_3< Real >::operator+(), Vector_3< Real >::operator-(), and Vector_3< Real >::operator/().
 {}
Vector_3 (Type t) inline explicit
Definition at line 57 of file mapbasic.h.
 : _x(t), _y(t), _z(t) {}
Vector_3 (Null_vector) inline
Definition at line 58 of file mapbasic.h.
 : _x(0), _y(0), _z(0) {}
Vector_3 (Type a, Type b, Type c) inline
Definition at line 59 of file mapbasic.h.
 : _x(a), _y(b), _z(c) {}
Vector_3 () inline
Definition at line 94 of file Vector_3.h.
   {}
Vector_3 (const CGAL::Vector_3< R > & v) inline
Definition at line 96 of file Vector_3.h.
     : RVector_3( (const RVector_3& )v )
   {}
Vector_3 (const RVector_3< Type > & v) inline
Definition at line 99 of file Vector_3.h.
                                 : RVector_3(v)
   {}
Vector_3 (const Null_vector & v) inline
Definition at line 101 of file Vector_3.h.
                                  : RVector_3(v)
   {}
Vector_3 (const RT & x, const RT & y, const RT & z) inline
Definition at line 103 of file Vector_3.h.
     : RVector_3(x, y, z)
   {}
Vector_3 (const RT & x, const RT & y, const RT & z, const RT & w) inline
Definition at line 106 of file Vector_3.h.
     : RVector_3(x, y, z, w)
   {}
Vector_3 (const CGAL::Point_3< R > & p) inline private
Definition at line 172 of file Vector_3.h.
                                     : RVector_3(p)
   {}
Vector_3 (const CGAL::Direction_3< R > & d) inline private
Definition at line 174 of file Vector_3.h.
                                         : RVector_3(d)
   {}
Member Function Documentation
FT cartesian (int i) const inline
Definition at line 134 of file Vector_3.h.
Referenced by Vector_3< Real >::operator[]().
   { return RVector_3::cartesian(i); }
static Vector_3 cross_product (const Vector_3< Type > & v, const Vector_3< Type > & w) inline static
Definition at line 104 of file mapbasic.h.
Referenced by Rocsurf::compute_element_normals(), compute_lbop_weights(), Rocmop::compute_medial_quadric(), Propagation_3::convert_constraints(), Window_manifold_2::elements_to_nodes(), Rocmop::evaluate_face_normals(), func1(), func2(), func3(), get_deformed_normal(), Overlay_primitives::get_face_normal(), get_face_volume(), get_normal(), Rocmop::get_redist_safe_factor(), Overlay_primitives::intersect(), Generic_element_2::Jacobian_det(), FaceOffset_3::nulaplacian_smooth(), FaceOffset_3::obtain_constrained_directions(), FaceOffset_3::obtain_face_offset(), one_sided_normal(), Overlay_primitives::project_blue_feature(), Overlay_primitives::project_green_feature(), FaceOffset_3::rescale_displacements(), and Generic_element_2::solve().
{
     return Vector_3( v._y * w._z - v._z * w._y ,
                      v._z * w._x - v._x * w._z ,
                      v._x * w._y - v._y * w._x );
   }
int dimension () const inline
Definition at line 138 of file Vector_3.h.
   { return 3; }
CGAL::Direction_3<R> direction () const inline
Definition at line 166 of file Vector_3.h.
   { return RVector_3::direction(); }
RT homogeneous (int i) const inline
Definition at line 132 of file Vector_3.h.
   { return RVector_3::homogeneous(i); }
RT hw () const inline
Definition at line 124 of file Vector_3.h.
   { return RVector_3::hw(); }
RT hx () const inline
Definition at line 118 of file Vector_3.h.
   { return RVector_3::hx(); }
RT hy () const inline
Definition at line 120 of file Vector_3.h.
   { return RVector_3::hy(); }
RT hz () const inline
Definition at line 122 of file Vector_3.h.
   { return RVector_3::hz(); }
bool is_null () const inline
Definition at line 133 of file mapbasic.h.
Referenced by Propagation_3::bound_spherical_disp().
 { return _x==0&&_y==0&&_z==0; }
Vector_3& neg () inline
Definition at line 120 of file mapbasic.h.
                   {
     _x = -_x; _y = -_y; _z = -_z; return *this;
   }
Type norm () const inline
Definition at line 112 of file mapbasic.h.
Referenced by Rocmop::check_displacements(), Rocsurf::compute_edge_lengths(), compute_lbop_weights(), Window_manifold_2::compute_mcn(), Rocmop::compute_medial_quadric(), Rocmop::constrain_displacements(), FaceOffset_3::obtain_face_offset(), and Rocmop::smooth_vol_mesq_ng().
 { return std::sqrt(*this * *this); }
Vector_3& normalize () inline
Definition at line 114 of file mapbasic.h.
Referenced by Rocsurf::compute_element_normals(), Rocmop::compute_medial_quadric(), Propagation_3::convert_constraints(), Rocmop::eigen_analyze_vertex(), Rocmop::evaluate_face_normals(), FaceOffset_3::filter_and_identify_ridge_edges(), Overlay_primitives::get_face_normal(), Rocmop::get_redist_safe_factor(), Rocmop::identify_ridge_edges(), FaceOffset_3::nulaplacian_smooth(), FaceOffset_3::obtain_constrained_directions(), FaceOffset_3::obtain_directions(), FaceOffset_3::obtain_face_offset(), one_sided_normal(), project_edge(), FaceOffset_3::reclassify_ridge_vertices(), Rocmop::smooth_vol_mesq_ng(), and Window_manifold_2::update_bd_normals().
{
     Type s=squared_norm();
     if ( s != Type(0)) { s=std::sqrt(s); _x/=s; _y/=s; _z/=s; }
     return *this;
   }
bool operator!= (const CGAL::Vector_3< R > & v) const inline
Definition at line 112 of file Vector_3.h.
   { return !(*this == v); }
bool operator!= (const Null_vector & v) const inline
Definition at line 116 of file Vector_3.h.
   { return !(*this == v); }
bool operator!= (const Vector_3< Type > & p) const inline
Definition at line 126 of file mapbasic.h.
   { return x()!=p.x() || y()!=p.y() || z()!=p.z(); }
Vector_3 operator* (const Type t) const inline
Definition at line 94 of file mapbasic.h.
   { return Vector_3(_x*t, _y*t, _z*t); }
Type operator* (const Vector_3< Type > & v) const inline
Definition at line 98 of file mapbasic.h.
   { return _x*v._x + _y*v._y + _z*v._z; }
FT operator* (const CGAL::Vector_3< R > & w) const inline
Definition at line 146 of file Vector_3.h.
   { return (const RVector_3& )(*this) * (const RVector_3& )(w); }
CGAL::Vector_3<R> operator* (const RT & c) const inline
Definition at line 150 of file Vector_3.h.
   { return c * (const RVector_3& )(*this) ; }
CGAL::Vector_3<R> operator* (const Quotient< RT > & q) const inline
Definition at line 152 of file Vector_3.h.
   {
     return (q.numerator() * (const RVector_3& )(*this)) /
             q.denominator();
   }
Vector_3& operator*= (const Type t) inline
Definition at line 76 of file mapbasic.h.
   { _x*=t; _y*=t; _z*=t; return *this; }
Vector_3& operator*= (const Vector_3< Type > & v) inline
Definition at line 78 of file mapbasic.h.
   { _x*=v._x; _y*=v._y; _z*=v._z; return *this; }
Vector_3 operator+ (const Type t) const inline
Arithmatic operators.
Definition at line 86 of file mapbasic.h.
   { return Vector_3(_x+t, _y+t, _z+t); }
Vector_3 operator+ (const Vector_3< Type > & v) const inline
Definition at line 88 of file mapbasic.h.
   { return Vector_3(_x+v._x, _y+v._y, _z+v._z); }
CGAL::Vector_3<R> operator+ (const CGAL::Vector_3< R > & w) const inline
Definition at line 140 of file Vector_3.h.
   { return (const RVector_3& )(*this) + (const RVector_3& )(w); }
Vector_3& operator+= (const Type t) inline
Assign operators.
Definition at line 68 of file mapbasic.h.
   { _x+=t; _y+=t; _z+=t; return *this; }
Vector_3& operator+= (const Vector_3< Type > & v) inline
Definition at line 70 of file mapbasic.h.
   { _x+=v._x; _y+=v._y; _z+=v._z; return *this; }
Vector_3 operator- (const Type t) const inline
Definition at line 90 of file mapbasic.h.
   { return Vector_3(_x-t, _y-t, _z-t); }
Vector_3 operator- (const Vector_3< Type > & v) const inline
Definition at line 92 of file mapbasic.h.
   { return Vector_3(_x-v._x, _y-v._y, _z-v._z); }
Vector_3 operator- () const inline
Definition at line 101 of file mapbasic.h.
   { return Vector_3(-_x, -_y, -_z); }
CGAL::Vector_3<R> operator- (const CGAL::Vector_3< R > & w) const inline
Definition at line 142 of file Vector_3.h.
   { return (const RVector_3& )(*this) - (const RVector_3& )(w); }
CGAL::Vector_3<R> operator- () const inline
Definition at line 144 of file Vector_3.h.
   { return RVector_3::operator-(); }
Vector_3& operator-= (const Type t) inline
Definition at line 72 of file mapbasic.h.
   { _x-=t; _y-=t; _z-=t; return *this; }
Vector_3& operator-= (const Vector_3< Type > & v) inline
Definition at line 74 of file mapbasic.h.
   { _x-=v._x; _y-=v._y; _z-=v._z; return *this; }
Vector_3 operator/ (const Type t) const inline
Definition at line 96 of file mapbasic.h.
   { return Vector_3(_x/t, _y/t, _z/t); }
CGAL::Vector_3<R> operator/ (const Quotient< RT > & q) const inline
Definition at line 157 of file Vector_3.h.
   {
     return (q.denominator() * (const RVector_3& )(*this)) /
             q.numerator();
   }
CGAL::Vector_3<R> operator/ (const RT & c) const inline
Definition at line 164 of file Vector_3.h.
   { return (const RVector_3& )(*this) / c; }
Vector_3& operator/= (const Type t) inline
Definition at line 80 of file mapbasic.h.
   { _x/=t; _y/=t; _z/=t; return *this; }
Vector_3& operator/= (const Vector_3< Type > & v) inline
Definition at line 82 of file mapbasic.h.
   { _x/=v._x; _y/=v._y; _z/=v._z; return *this; }
bool operator< (const Vector_3< Type > & v) const inline
Definition at line 129 of file mapbasic.h.
Referenced by Point_3< Real >::operator<().
   { return _x<v._x || _x==v._x && _y<v._y ||
       _x==v._x && _y==v._y && _z<v._z; }
bool operator== (const CGAL::Vector_3< R > & v) const inline
Definition at line 110 of file Vector_3.h.
   { return RVector_3::operator==(v); }
bool operator== (const Null_vector & v) const inline
Definition at line 114 of file Vector_3.h.
   { return RVector_3::operator==(v); }
bool operator== (const Vector_3< Type > & p) const inline
Definition at line 124 of file mapbasic.h.
   { return x()==p.x() && y()==p.y() && z()==p.z(); }
Type& operator[] (const int i) inline
Definition at line 60 of file mapbasic.h.
 { return (&_x)[i]; }
const Type& operator[] (const int i) const inline
Definition at line 61 of file mapbasic.h.
 { return (&_x)[i]; }
FT operator[] (int i) const inline
Definition at line 136 of file Vector_3.h.
   { return cartesian(i); }
Type squared_norm () const inline
Definition at line 110 of file mapbasic.h.
Referenced by Propagation_3::bound_spherical_disp(), Window_manifold_2::elements_to_nodes(), FaceOffset_3::eval_angle(), Rocmop::get_constraint_directions(), Vector_3< Real >::normalize(), and Generic_element_2::solve().
 { return *this * *this; }
CGAL::Vector_3<R> transform (const CGAL::Aff_transformation_3< R > & t) const inline
Definition at line 168 of file Vector_3.h.
   { return RVector_3::transform(t); }
Type x () const inline
Definition at line 63 of file mapbasic.h.
Referenced by Vector_3< Real >::operator!=(), Point_3< Real >::operator+(), Point_3< Real >::operator+=(), Point_3< Real >::operator-(), Point_3< Real >::operator-=(), operator<<(), and Vector_3< Real >::operator==().
 { return _x; }
FT x () const inline
Definition at line 126 of file Vector_3.h.
   { return RVector_3::x(); }
Type y () const inline
Definition at line 64 of file mapbasic.h.
Referenced by Vector_3< Real >::operator!=(), Point_3< Real >::operator+(), Point_3< Real >::operator+=(), Point_3< Real >::operator-(), Point_3< Real >::operator-=(), and Vector_3< Real >::operator==().
 { return _y; }
FT y () const inline
Definition at line 128 of file Vector_3.h.
   { return RVector_3::y(); }
Type z () const inline
Definition at line 65 of file mapbasic.h.
Referenced by Vector_3< Real >::operator!=(), Point_3< Real >::operator+(), Point_3< Real >::operator+=(), Point_3< Real >::operator-(), Point_3< Real >::operator-=(), and Vector_3< Real >::operator==().
 { return _z; }
FT z () const inline
Definition at line 130 of file Vector_3.h.
   { return RVector_3::z(); }
Friends And Related Function Documentation
CGAL_FRIEND_INLINE CGAL::Vector_3<R> point_to_vector_conversion CGAL_NULL_TMPL_ARGS (const CGAL::Point_3< R > & p) friend
Member Data Documentation
Type _x protected
Definition at line 135 of file mapbasic.h.
Referenced by Vector_3< Real >::cross_product(), Vector_3< Real >::is_null(), Vector_3< Real >::neg(), Vector_3< Real >::normalize(), Vector_3< Real >::operator*(), Vector_3< Real >::operator*=(), Vector_3< Real >::operator+(), Vector_3< Real >::operator+=(), Vector_3< Real >::operator-(), Vector_3< Real >::operator-=(), Vector_3< Real >::operator/(), Vector_3< Real >::operator/=(), Vector_3< Real >::operator<(), Vector_3< Real >::operator[](), and Vector_3< Real >::x().
Type _y protected
Definition at line 135 of file mapbasic.h.
Referenced by Vector_3< Real >::cross_product(), Vector_3< Real >::is_null(), Vector_3< Real >::neg(), Vector_3< Real >::normalize(), Vector_3< Real >::operator*(), Vector_3< Real >::operator*=(), Vector_3< Real >::operator+(), Vector_3< Real >::operator+=(), Vector_3< Real >::operator-(), Vector_3< Real >::operator-=(), Vector_3< Real >::operator/(), Vector_3< Real >::operator/=(), Vector_3< Real >::operator<(), and Vector_3< Real >::y().
Type _z protected
Definition at line 135 of file mapbasic.h.
Referenced by Vector_3< Real >::cross_product(), Vector_3< Real >::is_null(), Vector_3< Real >::neg(), Vector_3< Real >::normalize(), Vector_3< Real >::operator*(), Vector_3< Real >::operator*=(), Vector_3< Real >::operator+(), Vector_3< Real >::operator+=(), Vector_3< Real >::operator-(), Vector_3< Real >::operator-=(), Vector_3< Real >::operator/(), Vector_3< Real >::operator/=(), Vector_3< Real >::operator<(), and Vector_3< Real >::z().
The documentation for this class was generated from the following files:
mapbasic.h
Vector_3.h