Rocstar: rflu_modconstraintutils Module Reference
rflu_modconstraintutils Module Reference
Public Member Functions
integer function, public rflu_getconstrtype (pRegion, pPatch, var, ifl)
real(rfreal) function, public rflu_getconstrvalue (pRegion, pPatch, var, ifl)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModConstraintUtils.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 39 of file RFLU_ModConstraintUtils.F90.
Member Function/Subroutine Documentation
integer function, public rflu_getconstrtype (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) var, integer, intent(in) ifl)
Definition at line 92 of file RFLU_ModConstraintUtils.F90.
References moderror::deregisterfunction(), dist(), modtools::floatequal(), moderror::registerfunction(), and rflu_modgridspeedutils::rflu_descalegridspeed().
Referenced by rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), and rflu_moddifferentiationfaces::rflu_computegradfacesconstr().
real(rfreal) function, public rflu_getconstrvalue (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) var, integer, intent(in) ifl)
Definition at line 345 of file RFLU_ModConstraintUtils.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), modtools::floatequal(), moderror::registerfunction(), rflu_modgridspeedutils::rflu_descalegridspeed(), and rflu_modrindstates::rflu_setrindstateinjectperf().
Referenced by rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), and rflu_moddifferentiationfaces::rflu_computegradfacesconstr().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModConstraintUtils.F90,v $ $Revision: 1.7 $' private
Definition at line 61 of file RFLU_ModConstraintUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModConstraintUtils.F90