Rocstar: plag_moddatastruct Module Reference
plag_moddatastruct Module Reference
Public Member Functions
subroutine, public plag_dstr_buildcell2pcllist (pRegion)
subroutine plag_dstr_copyparticle (global, pPlag, pPlag2, iPcl)
subroutine, public plag_dstr_copyparticlewrapper (global, pPlag, pPlag2)
subroutine, public plag_dstr_createpcllistcsr (pRegion)
subroutine, public plag_dstr_destroycell2pcllist (pRegion)
subroutine, public plag_dstr_destroypcllistcsr (pRegion)
subroutine, public plag_dstr_mergeparticlewrapper (pRegion, pPlag, pPlag2)
Private Member Functions
subroutine plag_dstr_createcell2pcllist (pRegion)
subroutine plag_dstr_recreatecell2pcllist (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModDataStruct.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file PLAG_ModDataStruct.F90.
Member Function/Subroutine Documentation
subroutine, public plag_dstr_buildcell2pcllist (type(t_region), pointer pRegion)
Definition at line 104 of file PLAG_ModDataStruct.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), min(), plag_dstr_createcell2pcllist(), plag_dstr_recreatecell2pcllist(), modsortsearch::quicksortintegerinteger(), and moderror::registerfunction().
Referenced by rfluinit().
subroutine plag_dstr_copyparticle (type(t_global), pointer global, type(t_plag), pointer pPlag, type(t_plag), pointer pPlag2, integer, intent(in) iPcl)
Definition at line 291 of file PLAG_ModDataStruct.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_dstr_copyparticlewrapper().
subroutine, public plag_dstr_copyparticlewrapper (type(t_global), pointer global, type(t_plag), pointer pPlag, type(t_plag), pointer pPlag2)
Definition at line 393 of file PLAG_ModDataStruct.F90.
References moderror::deregisterfunction(), plag_dstr_copyparticle(), and moderror::registerfunction().
Referenced by plag_dstr_mergeparticlewrapper().
subroutine plag_dstr_createcell2pcllist (type(t_region), pointer pRegion) private
Definition at line 458 of file PLAG_ModDataStruct.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_dstr_buildcell2pcllist(), and plag_dstr_recreatecell2pcllist().
subroutine, public plag_dstr_createpcllistcsr (type(t_region), pointer pRegion)
Definition at line 540 of file PLAG_ModDataStruct.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rfluinit().
subroutine, public plag_dstr_destroycell2pcllist (type(t_region), pointer pRegion)
Definition at line 613 of file PLAG_ModDataStruct.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_dstr_recreatecell2pcllist(), and rfluinit().
subroutine, public plag_dstr_destroypcllistcsr (type(t_region), pointer pRegion)
Definition at line 690 of file PLAG_ModDataStruct.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rfluinit().
subroutine, public plag_dstr_mergeparticlewrapper (type(t_region), pointer pRegion, type(t_plag), pointer pPlag, type(t_plag), pointer pPlag2)
Definition at line 766 of file PLAG_ModDataStruct.F90.
References moderror::deregisterfunction(), plag_dstr_copyparticlewrapper(), and moderror::registerfunction().
Referenced by rflu_modmergeregions::rflu_merg_mergesolwrapper().
subroutine plag_dstr_recreatecell2pcllist (type(t_region), pointer pRegion) private
Definition at line 851 of file PLAG_ModDataStruct.F90.
References moderror::deregisterfunction(), moderror::errorstop(), min(), plag_dstr_createcell2pcllist(), plag_dstr_destroycell2pcllist(), and moderror::registerfunction().
Referenced by plag_dstr_buildcell2pcllist().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModDataStruct.F90,v $ $Revision: 1.5 $' private
Definition at line 67 of file PLAG_ModDataStruct.F90.
The documentation for this module was generated from the following file:
PLAG_ModDataStruct.F90