Rocstar: rflu_modensightutils Module Reference
rflu_modensightutils Module Reference
Public Member Functions
subroutine, public rflu_ens_writegrid (pRegion, emptyPartFlag)
subroutine, public rflu_ens_writescalar (pRegion, var, iFile, emptyPartFlag)
subroutine, public rflu_ens_writevector (pRegion, var, iFile, emptyPartFlag)
Private Attributes
character(chrlen), parameter,
private rcsidentstring = '$RCSfile: RFLU_ModENSIGHTUtils.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 43 of file RFLU_ModENSIGHTUtils.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_ens_writegrid (type(t_region), pointer pRegion, logical, intent(in) emptyPartFlag)
Definition at line 101 of file RFLU_ModENSIGHTUtils.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modtopologyutils::rflu_buildconnvertlist(), rflu_modrenumberlist::rflu_denumberlist(), and rflu_modrenumberlist::rflu_renumberlist().
Referenced by rflu_modensight::rflu_ens_writegridwrapper().
subroutine, public rflu_ens_writescalar (type(t_region), pointer pRegion, real(rfreal), dimension(:), pointer var, integer, intent(in) iFile, logical, intent(in) emptyPartFlag)
Definition at line 574 of file RFLU_ModENSIGHTUtils.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modensight::rflu_ens_writeflowwrapper().
subroutine, public rflu_ens_writevector (type(t_region), pointer pRegion, real(rfreal), dimension(:,:), pointer var, integer, intent(in) iFile, logical, intent(in) emptyPartFlag)
Definition at line 826 of file RFLU_ModENSIGHTUtils.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modensight::rflu_ens_writeflowwrapper().
Member Data Documentation
character(chrlen), parameter, private rcsidentstring = '$RCSfile: RFLU_ModENSIGHTUtils.F90,v $ $Revision: 1.4 $' private
Definition at line 63 of file RFLU_ModENSIGHTUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModENSIGHTUtils.F90