Rocstar: rflu_modincelltest Module Reference
rflu_modincelltest Module Reference
Public Member Functions
subroutine, public rflu_ict_computetolerance (pRegion)
subroutine, public rflu_ict_testfaceplanar (pRegion, xLoc, yLoc, zLoc, icg, iPatch, ifg, dotp)
subroutine, public rflu_ict_testfacequadbilinear (pRegion, xLoc, yLoc, zLoc, iPatch, ifg, dotp)
logical function, public rflu_ict_testincell (pRegion, xLoc, yLoc, zLoc, icg)
subroutine, public rflu_ict_testincellfancy (pRegion, xLoc, yLoc, zLoc, icg, testInCell, iPatchOut, ifgOut)
subroutine, public rflu_ict_testincelllohner (pRegion, xLoc, yLoc, zLoc, icg, testInCell, iPatchOut, ifgOut)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModInCellTest.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 39 of file RFLU_ModInCellTest.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_ict_computetolerance (type(t_region), pointer pRegion)
Definition at line 92 of file RFLU_ModInCellTest.F90.
References moderror::deregisterfunction(), max(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
subroutine, public rflu_ict_testfaceplanar (type(t_region), pointer pRegion, real(rfreal), intent(in) xLoc, real(rfreal), intent(in) yLoc, real(rfreal), intent(in) zLoc, integer, intent(in) icg, integer, intent(in) iPatch, integer, intent(in) ifg, real(rfreal), intent(out) dotp)
Definition at line 262 of file RFLU_ModInCellTest.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_ict_testincell(), rflu_ict_testincellfancy(), and rflu_ict_testincelllohner().
subroutine, public rflu_ict_testfacequadbilinear (type(t_region), pointer pRegion, real(rfreal), intent(in) xLoc, real(rfreal), intent(in) yLoc, real(rfreal), intent(in) zLoc, integer, intent(in) iPatch, integer, intent(in) ifg, real(rfreal), intent(out) dotp)
Definition at line 377 of file RFLU_ModInCellTest.F90.
References by, moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::registerfunction(), rflu_modbilinearpatch::rflu_blin_computenormal(), rflu_modbilinearpatch::rflu_blin_findclosestpoint(), StopWatch::stop(), v, x, y, and z.
logical function, public rflu_ict_testincell (type(t_region), pointer pRegion, real(rfreal), intent(in) xLoc, real(rfreal), intent(in) yLoc, real(rfreal), intent(in) zLoc, integer, intent(in) icg)
Definition at line 544 of file RFLU_ModInCellTest.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), and rflu_ict_testfaceplanar().
Referenced by plag_modinjection::plag_ejectparticle(), plag_rflu_modfindcells::plag_rflu_findcellsbrute(), plag_rflu_modfindcells::plag_rflu_findcellsbrutekernel(), plag_rflu_modfindcells::plag_rflu_findcellsbrutemod(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), and rflu_modprobes::rflu_findprobecells().
subroutine, public rflu_ict_testincellfancy (type(t_region), pointer pRegion, real(rfreal), intent(in) xLoc, real(rfreal), intent(in) yLoc, real(rfreal), intent(in) zLoc, integer, intent(in) icg, logical, intent(out) testInCell, integer, intent(out) iPatchOut, integer, intent(out) ifgOut)
Definition at line 780 of file RFLU_ModInCellTest.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), and rflu_ict_testfaceplanar().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), and plag_rflu_modfindcells::plag_rflu_findcellstrajsafe().
subroutine, public rflu_ict_testincelllohner (type(t_region), pointer pRegion, real(rfreal), intent(in) xLoc, real(rfreal), intent(in) yLoc, real(rfreal), intent(in) zLoc, integer, intent(in) icg, logical, intent(out) testInCell, integer, intent(out) iPatchOut, integer, intent(out) ifgOut)
Definition at line 966 of file RFLU_ModInCellTest.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), and rflu_ict_testfaceplanar().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellslohner().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModInCellTest.F90,v $ $Revision: 1.4 $' private
Definition at line 64 of file RFLU_ModInCellTest.F90.
The documentation for this module was generated from the following file:
RFLU_ModInCellTest.F90