Rocstar: rflu_modtetmesh Module Reference
rflu_modtetmesh Module Reference
Data Types
type t_gridtetmesh
Public Member Functions
subroutine, public rflu_convrocflu2tetmesh (pRegion)
subroutine, public rflu_convtetmesh2rocflu (pRegion)
subroutine, public rflu_readgridtetmesh (pRegion)
subroutine, public rflu_writesurfgridtetmesh (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModTETMESH.F90,v $ $Revision: 1.8 $'
type(t_gridtetmesh) gridtetmesh
Detailed Description
Definition at line 39 of file RFLU_ModTETMESH.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_convrocflu2tetmesh (type(t_region), pointer pRegion)
Definition at line 115 of file RFLU_ModTETMESH.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modboundlists::rflu_denumberbfacelists(), rflu_modboundlists::rflu_destroybvertexlists(), and rflu_modboundlists::rflu_renumberbfacelists().
Referenced by rfluconv().
subroutine, public rflu_convtetmesh2rocflu (type(t_region), pointer pRegion)
Definition at line 407 of file RFLU_ModTETMESH.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, ic, moderror::registerfunction(), rflu_moddimensions::rflu_setmaxdimension(), and Attribute::status().
Referenced by rflu_readconvgridwrapper().
subroutine, public rflu_readgridtetmesh (type(t_region), pointer pRegion)
Definition at line 745 of file RFLU_ModTETMESH.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, i, ic, moderror::registerfunction(), rflu_moddimensions::rflu_setmaxdimension(), and Attribute::status().
Referenced by rflu_readconvgridwrapper().
subroutine, public rflu_writesurfgridtetmesh (type(t_region), pointer pRegion)
Definition at line 933 of file RFLU_ModTETMESH.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rfluconv().
Member Data Documentation
type(t_gridtetmesh) gridtetmesh private
Definition at line 75 of file RFLU_ModTETMESH.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModTETMESH.F90,v $ $Revision: 1.8 $' private
Definition at line 66 of file RFLU_ModTETMESH.F90.
The documentation for this module was generated from the following file:
RFLU_ModTETMESH.F90