Rocstar: rflu_modcopydata Module Reference
rflu_modcopydata Module Reference
Public Member Functions
subroutine, public rflu_copy_celldatap2s_r2d (global, pGrid, var, varSerial)
subroutine, public rflu_copy_celldatap2s_r3d (global, pGrid, var, varSerial)
subroutine, public rflu_copy_celldatas2p_i1d (global, pGrid, var, varSerial)
subroutine, public rflu_copy_celldatas2p_r2d (global, pGrid, var, varSerial)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCopyData.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 39 of file RFLU_ModCopyData.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_copy_celldatap2s_r2d (type(t_global), pointer global, type(t_grid), pointer pGrid, real(rfreal), dimension(:,:) var, real(rfreal), dimension(:,:) varSerial)
Definition at line 95 of file RFLU_ModCopyData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modmergeregions::rflu_merg_mergesolwrapper().
subroutine, public rflu_copy_celldatap2s_r3d (type(t_global), pointer global, type(t_grid), pointer pGrid, real(rfreal), dimension(:,:,:) var, real(rfreal), dimension(:,:,:) varSerial)
Definition at line 178 of file RFLU_ModCopyData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modmergeregions::rflu_merg_mergesolwrapper().
subroutine, public rflu_copy_celldatas2p_i1d (type(t_global), pointer global, type(t_grid), pointer pGrid, integer, dimension(:) var, integer, dimension(:) varSerial)
Definition at line 269 of file RFLU_ModCopyData.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modcoloring::rflu_col_buildcoloringp().
subroutine, public rflu_copy_celldatas2p_r2d (type(t_global), pointer global, type(t_grid), pointer pGrid, real(rfreal), dimension(:,:) var, real(rfreal), dimension(:,:) varSerial)
Definition at line 342 of file RFLU_ModCopyData.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowserialwrapper().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCopyData.F90,v $ $Revision: 1.7 $' private
Definition at line 60 of file RFLU_ModCopyData.F90.
The documentation for this module was generated from the following file:
RFLU_ModCopyData.F90