Rocstar: TecplotOrderedWriter Class Reference
TecplotOrderedWriter Class Reference
#include <tecplotwriter.h>
Public Member Functions
TecplotOrderedWriter ()
Default constructor.
TecplotOrderedWriter (string rFilename)
Constructor.
virtual ~TecplotOrderedWriter ()
Destructor.
bool writeFile (string rTitle, std::vector< string > rVariableNames)
Write all information to file.
bool addOrderedPartition (string rTitle, indexed_points *rpPoints, int rPartitionVariable)
Add ordered partition of points to the file write queue Points are written after WriteFile call Partitions must have the same number of variables.
Public Member Functions inherited from TecplotWriter
TecplotWriter ()
Default constructor.
TecplotWriter (string rFilename)
Constructor.
~TecplotWriter ()
Destructor.
void setOutputFilename (string rFilename)
Set filename.
string getOutputFilename ()
Get filename.
bool init ()
Initialize writer.
Private Member Functions
bool writePartition (int rPartitionNum)
Write partition to file.
bool writePoints (int rPartitionNum)
Write the points of the partition specified to file.
Private Attributes
std::vector< indexed_points * > mPartitionPoints
std::vector< string > mPartitionTitles
std::vector< int > mPartitionVariable
Static Private Attributes
static const int POINT_WIDTH = 5
Number of points per line.
Additional Inherited Members
Protected Attributes inherited from TecplotWriter
string mFilename
ofstream mFileHandle
Detailed Description
Definition at line 83 of file tecplotwriter.h.
Constructor & Destructor Documentation
TecplotOrderedWriter ()
Default constructor.
Definition at line 69 of file tecplotwriter.cpp.
                                            : TecplotWriter(){
     return;
 }
TecplotOrderedWriter (string rFilename)
Constructor.
Parameters
rFilename Output filename
Definition at line 77 of file tecplotwriter.cpp.
                                                            : TecplotWriter(rFilename){
     return;
 }
~TecplotOrderedWriter () virtual
Destructor.
Definition at line 84 of file tecplotwriter.cpp.
{
     return;
 }
Member Function Documentation
bool addOrderedPartition (string rTitle, indexed_points * rpPoints, int rPartitionVariable)
Add ordered partition of points to the file write queue Points are written after WriteFile call Partitions must have the same number of variables.
Parameters
rTitle Title of partition
rpPoints Datapoints to write to file
rPartitionVariable Variable number to write (after the independent variables). If -1, all variables will be written
Definition at line 127 of file tecplotwriter.cpp.
References points::get_num_indep_vars(), points::get_num_vars(), mPartitionPoints, mPartitionTitles, and mPartitionVariable.
{
     if(rpPoints == NULL)
         return false;
     if(mPartitionPoints.size() != 0){
         //Calculate the number of vars in the supplied dataset
         int curr_num_vars = -1;
         if(rPartitionVariable == -1)
             curr_num_vars = rpPoints->get_num_vars();
         else
             curr_num_vars = rpPoints->get_num_indep_vars() + 1;
         //Calculate the number of vars in the previous dataset
         int prev_var = mPartitionVariable.back();
         int prev_num_vars = -1;
         if(prev_var == -1)
             prev_num_vars = mPartitionPoints.back()->get_num_vars();
         else
             prev_num_vars = mPartitionPoints.back()->get_num_indep_vars() + 1;
         //Check variable consistency
         if(curr_num_vars != prev_num_vars)
             return false;
     }
     mPartitionPoints.push_back(rpPoints);
     mPartitionTitles.push_back(rTitle);
     mPartitionVariable.push_back(rPartitionVariable);
     return true;
 }
bool writeFile (string rTitle, std::vector< string > rVariableNames)
Write all information to file.
Parameters
rTitle Dataset Title
rVariableNames Variable names for header
Returns
True if write is successful, otherwise false
Definition at line 94 of file tecplotwriter.cpp.
References TecplotWriter::mFileHandle, mPartitionPoints, and writePartition().
{
     //Check file handle
     if(!mFileHandle.is_open())
         return false;
     //Check to make sure the number of variables match
     if(mPartitionPoints.size() != 0){
         if(rVariableNames.size() != mPartitionPoints[0]->get_num_vars())
             return false;
     }
     mFileHandle << "TITLE = \"" << rTitle << "\"" << endl;
     //Write variable names to file
     mFileHandle << "VARIABLES = ";
     for(int var_num = 0; var_num < rVariableNames.size(); var_num++){
         mFileHandle << "\"" << rVariableNames[var_num] << "\"" << endl;
     }
     //Write partitions to file
     for(int partition_num = 0; partition_num < mPartitionPoints.size(); partition_num++){
         writePartition(partition_num);
     }
     return false;
 }
bool writePartition (int rPartitionNum) private
Write partition to file.
Parameters
rPartitionPoints Partition datapoints
Returns
True if write is successful, otherwise false
Definition at line 165 of file tecplotwriter.cpp.
References indexed_points::get_dim(), i, j, k, TecplotWriter::mFileHandle, mPartitionPoints, mPartitionTitles, and writePoints().
Referenced by writeFile().
{
     //Sanity check
     if(rPartitionNum >= mPartitionPoints.size() || rPartitionNum > mPartitionTitles.size())
         return false;
     indexed_points *curr_points = mPartitionPoints[rPartitionNum];
     //Zone and title
     mFileHandle << "ZONE ";
     mFileHandle << "T = \"" << mPartitionTitles[rPartitionNum] << "\"" << endl;
     //Don't know what this is...
     mFileHandle << "STRANDID=0, SOLUTIONTIME=0" << endl;
     if(curr_points->get_dim().size() < 3)
         return false;
     //Write i,j,k values
     int i = curr_points->get_dim()[0];
     int j = curr_points->get_dim()[1];
     int k = curr_points->get_dim()[2];
     mFileHandle << "I=" << i << ", ";
     mFileHandle << "J=" << j << ", ";
     mFileHandle << "K=" << k << ", ";
     //Write other properties
     mFileHandle << "ZONETYPE=Ordered" << endl;
     mFileHandle << "DATAPACKING=BLOCK" << endl;
     mFileHandle << "DT=(SINGLE SINGLE SINGLE SINGLE )" << endl;
     return writePoints(rPartitionNum);
 }
bool writePoints (int rPartitionNum) private
Write the points of the partition specified to file.
Points are written in block format.
Parameters
rPartitionNum Index of the parition's points in local storage
Returns
True on success, otherwise false
Definition at line 207 of file tecplotwriter.cpp.
References indexed_points::get_dim(), points::get_num_indep_vars(), points::get_num_points(), points::get_num_vars(), points::get_point(), TecplotWriter::mFileHandle, mPartitionPoints, mPartitionVariable, POINT_WIDTH, pnt::vals, x, y, and z.
Referenced by writePartition().
{
     if(mPartitionPoints.size() <= rPartitionNum)
         return false;
     indexed_points *curr_points = mPartitionPoints[rPartitionNum];
     int num_pts = curr_points->get_num_points();
     int vars = curr_points->get_num_vars();
     int values_printed = 0;
     //Loop through and write points
     for(int var_num = 0; var_num < vars; var_num++){
         if(mPartitionVariable[rPartitionNum] != -1 && var_num >= curr_points->get_num_indep_vars()){
             if(var_num != mPartitionVariable[rPartitionNum])
                 continue;
         }
         for(int z = 0; z < curr_points->get_dim()[2]; z++){
             for(int y = 0; y < curr_points->get_dim()[1]; y++){
                 for(int x = 0; x < curr_points->get_dim()[0]; x++){
                     //Line break after every POINT_WIDTH values are written
                     if(values_printed == POINT_WIDTH){
                         mFileHandle << endl;
                         values_printed = 0;
                     }
                     //Calculate value index (see tecplot docs)
                     int index =   x * curr_points->get_dim()[1]
                                 + y * curr_points->get_dim()[2]
                                 + z;
                     mFileHandle << " " << std::uppercase << std::scientific << curr_points->get_point(index).vals[var_num];
                     values_printed++;
                 }
             }
         }
     }
     mFileHandle << std::endl;
     return false;
 }
Member Data Documentation
std::vector<indexed_points *> mPartitionPoints private
Definition at line 139 of file tecplotwriter.h.
Referenced by addOrderedPartition(), writeFile(), writePartition(), and writePoints().
std::vector<string> mPartitionTitles private
Definition at line 140 of file tecplotwriter.h.
Referenced by addOrderedPartition(), and writePartition().
std::vector<int> mPartitionVariable private
Definition at line 141 of file tecplotwriter.h.
Referenced by addOrderedPartition(), and writePoints().
const int POINT_WIDTH = 5 static private
Number of points per line.
Definition at line 144 of file tecplotwriter.h.
Referenced by writePoints().
The documentation for this class was generated from the following files:
tecplotwriter.h
tecplotwriter.cpp