Rocstar: rflu_modrenumberlist Module Reference
rflu_modrenumberlist Module Reference
Public Member Functions
subroutine, public rflu_denumberlist (global, listDim1, listDim2, list, keyDim, key)
subroutine, public rflu_renumberlist (global, listDim1, listDim2, list, keyDim, key)
subroutine, public rflu_renumberlist2 (global, listDim1, listDim2, list, keyDim, key1, key2)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRenumberList.F90,v $ $Revision: 1.6 $'
Detailed Description
Definition at line 39 of file RFLU_ModRenumberList.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_denumberlist (type(t_global), pointer global, integer, intent(in) listDim1, integer, intent(in) listDim2, integer, dimension(listdim1,listdim2), intent(inout) list, integer, intent(in) keyDim, integer, dimension(keydim), intent(in) key)
Definition at line 93 of file RFLU_ModRenumberList.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, j, k, key, and moderror::registerfunction().
Referenced by rflu_modboundlists::rflu_denumberbfacelists(), and rflu_modensightutils::rflu_ens_writegrid().
subroutine, public rflu_renumberlist (type(t_global), pointer global, integer, intent(in) listDim1, integer, intent(in) listDim2, integer, dimension(listdim1,listdim2), intent(inout) list, integer, intent(in) keyDim, integer, dimension(keydim), intent(in) key)
Definition at line 175 of file RFLU_ModRenumberList.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), i, j, k, key, and moderror::registerfunction().
Referenced by rflu_modboundlists::rflu_buildbfaceloclists(), rflu_modensightutils::rflu_ens_writegrid(), and rflu_modboundlists::rflu_renumberbfacelists().
subroutine, public rflu_renumberlist2 (type(t_global), pointer global, integer, intent(in) listDim1, integer, intent(in) listDim2, integer, dimension(listdim1,listdim2), intent(inout) list, integer, intent(in) keyDim, integer, dimension(keydim), intent(in) key1, integer, dimension(keydim), intent(in) key2)
Definition at line 264 of file RFLU_ModRenumberList.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), i, j, k, and moderror::registerfunction().
Referenced by rflu_modpartitionregion::rflu_part_buildvertexlists(), and rflu_modpartitionregion::rflu_part_renumbervertexlists().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRenumberList.F90,v $ $Revision: 1.6 $' private
Definition at line 59 of file RFLU_ModRenumberList.F90.
The documentation for this module was generated from the following file:
RFLU_ModRenumberList.F90