Rocstar: KeyValuePairObj< K, V > Class Template Reference
KeyValuePairObj< K, V > Class Template Reference
Simple key-value pair.
#include <PrimitiveTypes.H>
Public Member Functions
KeyValuePairObj (const std::pair< K, V > &p)
KeyValuePairObj (const K &k, const V &v)
KeyValuePairObj ()
K Key () const
V Value () const
K & Key ()
V & Value ()
K & Key (const K &k)
V & Value (const V &v)
Detailed Description
template<typename K, typename V>
class IRAD::Primitive::KeyValuePairObj< K, V >
Simple key-value pair.
Definition at line 194 of file PrimitiveTypes.H.
Constructor & Destructor Documentation
KeyValuePairObj (const std::pair< K, V > & p) inline
Definition at line 197 of file PrimitiveTypes.H.
{
         this->first = p.first;
         this->second = p.second;
       };
KeyValuePairObj (const K & k, const V & v) inline
Definition at line 201 of file PrimitiveTypes.H.
References k, and v.
{
         this->first = k;
         this->second = v;
       };
KeyValuePairObj () inline
Definition at line 205 of file PrimitiveTypes.H.
 {};
Member Function Documentation
K Key () const inline
Definition at line 206 of file PrimitiveTypes.H.
Referenced by TestResults::AddResult(), IRAD::Util::operator<<(), and Parameters::ReadFromStream().
 { return this->first; };
K& Key () inline
Definition at line 208 of file PrimitiveTypes.H.
 { return this->first; };
K& Key (const K & k) inline
Definition at line 210 of file PrimitiveTypes.H.
References k.
 { this->first = k; return(this->first); };
V Value () const inline
Definition at line 207 of file PrimitiveTypes.H.
Referenced by TestResults::AddResult(), IRAD::Util::operator<<(), Parameters::ReadFromStream(), and Parameters::SetValue().
 { return this->second; };
V& Value () inline
Definition at line 209 of file PrimitiveTypes.H.
 { return this->second; };
V& Value (const V & v) inline
Definition at line 211 of file PrimitiveTypes.H.
References v.
 { this->second = v; return(this->second); };
The documentation for this class was generated from the following file:
PrimitiveTypes.H