Rocstar: LeVeque_flow Class Reference
LeVeque_flow Class Reference
#include <speeds.h>
Public Member Functions
LeVeque_flow (double T=3)
virtual ~LeVeque_flow ()
Vector_3 get_velocity (const Point_3 &p, double t) const
Public Member Functions inherited from Speed
Speed ()
virtual ~Speed ()
Protected Member Functions
double square (double x) const
Protected Attributes
double _t
Detailed Description
Definition at line 95 of file speeds.h.
Constructor & Destructor Documentation
LeVeque_flow (double T = 3) inline explicit
Definition at line 98 of file speeds.h.
 : _t(T) {}
virtual ~LeVeque_flow () inline virtual
Definition at line 99 of file speeds.h.
 {}
Member Function Documentation
Vector_3 get_velocity (const Point_3 & p, double t) const inline virtual
Reimplemented from Speed.
Definition at line 101 of file speeds.h.
References _t, cimg_library::cos(), pi, s, cimg_library::sin(), square(), and v.
{
     const double pi = 3.14159265358979;
     Vector_3 v;
     v[0] = 2*square(std::sin(pi*p[0]))*std::sin(2*pi*p[1])*std::sin(2*pi*p[2]);
     v[1] = -std::sin(2*pi*p[0])*square(std::sin(pi*p[1]))*std::sin(2*pi*p[2]);
     v[2] = -std::sin(2*pi*p[0])*std::sin(2*pi*p[1])*square(std::sin(pi*p[2]));
     double s;
     if ( _t<0) s = std::cos(pi*(0.5-t/_t));
     else s = std::cos(pi*t/_t);
     return (v *= s);
   }
double square (double x) const inline protected
Definition at line 117 of file speeds.h.
References x.
Referenced by get_velocity().
 { return x*x; }
Member Data Documentation
double _t protected
Definition at line 118 of file speeds.h.
Referenced by get_velocity().
The documentation for this class was generated from the following file:
speeds.h