Rocstar: rflo_modpatchaerocoeffs Module Reference
rflo_modpatchaerocoeffs Module Reference
Public Member Functions
subroutine, public rflo_initpatchaerocoeffs (region, patch)
subroutine, public rflo_readpatchaerocoeffs (regions)
subroutine, public rflo_writepatchaerocoeffs (regions)
subroutine, public rflo_readpatchaerocoeffsreg (iReg, regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModPatchAeroCoeffs.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file RFLO_ModPatchAeroCoeffs.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_initpatchaerocoeffs (type(t_region) region, type(t_patch) patch)
Definition at line 90 of file RFLO_ModPatchAeroCoeffs.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflo_modinitialization::rflo_initnoncvsolution().
subroutine, public rflo_readpatchaerocoeffs (type(t_region), dimension(:), pointer regions)
Definition at line 143 of file RFLO_ModPatchAeroCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, ic, moderror::registerfunction(), rflo_readdatafileint(), rflo_readdatafilereal(), Attribute::status(), and RFC_Data_const< _Tag >::tag().
subroutine, public rflo_readpatchaerocoeffsreg (integer iReg, type(t_region), dimension(:), pointer regions)
Definition at line 696 of file RFLO_ModPatchAeroCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, ic, moderror::registerfunction(), rflo_readdatafileint(), rflo_readdatafilereal(), and Attribute::status().
subroutine, public rflo_writepatchaerocoeffs (type(t_region), dimension(:), pointer regions)
Definition at line 434 of file RFLO_ModPatchAeroCoeffs.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, ic, moderror::registerfunction(), rflo_writedatafileint(), rflo_writedatafilereal(), Attribute::status(), and RFC_Data_const< _Tag >::tag().
Referenced by rflo_dualtimestepping(), and rflo_timestepping().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModPatchAeroCoeffs.F90,v $ $Revision: 1.5 $' private
Definition at line 64 of file RFLO_ModPatchAeroCoeffs.F90.
The documentation for this module was generated from the following file:
RFLO_ModPatchAeroCoeffs.F90