Rocstar: TargetMatrix Class Reference
TargetMatrix Class Reference
Class containing the target corner matrices for the context based smoothing.
#include <TargetMatrix.hpp>
Public Member Functions
TargetMatrix ()
TargetMatrix (const Matrix3D &A)
TargetMatrix & operator= (const Matrix3D &A)
TargetMatrix & operator= (const TargetMatrix &A)
double get_cK () const
TargetMatrix ()
TargetMatrix (const Matrix3D &A)
TargetMatrix & operator= (const Matrix3D &A)
TargetMatrix & operator= (const TargetMatrix &A)
double get_cK () const
Public Member Functions inherited from Matrix3D
Matrix3D ()
Default constructor sets all entries to 0.
Matrix3D (const Matrix3D &A)
Matrix3D (const double &value)
sets all entries of the matrix to value.
Matrix3D (const double *v)
sets matrix entries to values in array.
Matrix3D (const char *s)
for test purposes, matrices can be instantiated as
~Matrix3D ()
Matrix3D & operator= (const Matrix3D &A)
Matrix3D & operator= (const double &scalar)
Matrix3D & operator= (const char *s)
for test purposes, matrices can be assigned as follows
void zero ()
Sets all entries to zero (more efficient than assignement).
void set_column (int j, const Vector3D &c)
Sets column j (0, 1 or 2) to Vector3D c.
double column_length (int i) const
returns the column length – i is 0-based.
const Matrix3D operator* (const double &s) const
multiplies each entry by the scalar s
void operator+= (const Matrix3D &rhs)
void operator-= (const Matrix3D &rhs)
void operator*= (const double &s)
multiplies each entry by the scalar s
Matrix3D plus_transpose (const Matrix3D &B) const
void plus_transpose_equal (const Matrix3D &B)
Matrix3D & outer_product (const Vector3D &v1, const Vector3D &v2)
Computes .
void fill_lower_triangle ()
size_t num_rows () const
size_t num_cols () const
double * operator[] (unsigned i)
returns a pointer to a row.
const double * operator[] (unsigned i) const
returns a pointer to a row.
Matrix3D ()
Default constructor sets all entries to 0.
Matrix3D (const Matrix3D &A)
Matrix3D (const double &value)
sets all entries of the matrix to value.
Matrix3D (const double *v)
sets matrix entries to values in array.
Matrix3D (const char *s)
for test purposes, matrices can be instantiated as
~Matrix3D ()
Matrix3D & operator= (const Matrix3D &A)
Matrix3D & operator= (const double &scalar)
Matrix3D & operator= (const char *s)
for test purposes, matrices can be assigned as follows
void zero ()
Sets all entries to zero (more efficient than assignement).
void set_column (int j, const Vector3D &c)
Sets column j (0, 1 or 2) to Vector3D c.
double column_length (int i) const
returns the column length – i is 0-based.
const Matrix3D operator* (const double &s) const
void operator+= (const Matrix3D &rhs)
void operator-= (const Matrix3D &rhs)
void operator*= (const double &s)
Matrix3D plus_transpose (const Matrix3D &B) const
void plus_transpose_equal (const Matrix3D &B)
Matrix3D & outer_product (const Vector3D &v1, const Vector3D &v2)
void fill_lower_triangle ()
size_t num_rows () const
size_t num_cols () const
double * operator[] (unsigned i)
returns a pointer to a row.
const double * operator[] (unsigned i) const
returns a pointer to a row.
Private Attributes
double cK
Additional Inherited Members
Protected Member Functions inherited from Matrix3D
void copy (const double *v)
void set (const double &val)
void set_values (const char *s)
void copy (const double *v)
void set (const double &val)
void set_values (const char *s)
Protected Attributes inherited from Matrix3D
double v_ [9]
Detailed Description
Class containing the target corner matrices for the context based smoothing.
Definition at line 49 of file includeLinks/TargetMatrix.hpp.
Constructor & Destructor Documentation
TargetMatrix () inline
Definition at line 53 of file includeLinks/TargetMatrix.hpp.
References TargetMatrix::cK.
                    : Matrix3D()
     {
       cK = 1.;
     }
TargetMatrix (const Matrix3D & A) inline
Definition at line 58 of file includeLinks/TargetMatrix.hpp.
References TargetMatrix::cK.
                                     : Matrix3D(A)
     {
       cK = 1.;
     }
TargetMatrix () inline
Definition at line 53 of file src/Misc/TargetMatrix.hpp.
References TargetMatrix::cK.
                    : Matrix3D()
     {
       cK = 1.;
     }
TargetMatrix (const Matrix3D & A) inline
Definition at line 58 of file src/Misc/TargetMatrix.hpp.
References TargetMatrix::cK.
                                     : Matrix3D(A)
     {
       cK = 1.;
     }
Member Function Documentation
double get_cK () const inline
Definition at line 79 of file includeLinks/TargetMatrix.hpp.
References TargetMatrix::cK.
Referenced by RI_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), DistanceFromTarget::compute_T_matrices(), RI_DFT::evaluate_element(), and I_DFT::evaluate_element().
 { return cK; }
double get_cK () const inline
Definition at line 79 of file src/Misc/TargetMatrix.hpp.
References TargetMatrix::cK.
 { return cK; }
TargetMatrix& operator= (const Matrix3D & A) inline
Definition at line 63 of file src/Misc/TargetMatrix.hpp.
References TargetMatrix::cK, and Matrix3D::operator=().
     {
       if (&A != this)
         Matrix3D::operator=(A);
       cK = 1.;
       return *this;
     }
TargetMatrix& operator= (const Matrix3D & A) inline
Definition at line 63 of file includeLinks/TargetMatrix.hpp.
References TargetMatrix::cK, and Matrix3D::operator=().
     {
       if (&A != this)
         Matrix3D::operator=(A);
       cK = 1.;
       return *this;
     }
TargetMatrix& operator= (const TargetMatrix & A) inline
Definition at line 71 of file includeLinks/TargetMatrix.hpp.
References TargetMatrix::cK, and Matrix3D::operator=().
     {
       if (&A != this)
         Matrix3D::operator=(A);
       cK = A.cK;
       return *this;
     }
TargetMatrix& operator= (const TargetMatrix & A) inline
Definition at line 71 of file src/Misc/TargetMatrix.hpp.
References TargetMatrix::cK, and Matrix3D::operator=().
     {
       if (&A != this)
         Matrix3D::operator=(A);
       cK = A.cK;
       return *this;
     }
Member Data Documentation
double cK private
Definition at line 84 of file includeLinks/TargetMatrix.hpp.
Referenced by TargetMatrix::get_cK(), TargetMatrix::operator=(), and TargetMatrix::TargetMatrix().
The documentation for this class was generated from the following file:
includeLinks/TargetMatrix.hpp