Rocstar: Roccom_map< Object > Class Template Reference
Roccom_map< Object > Class Template Reference
Supports mapping from names to handles and vice-versa for a module, window, function, or attribute.
#include <maps.h>
Public Types
typedef Object value_type
Public Member Functions
Roccom_map ()
~Roccom_map ()
int add_object (std::string name, Object t, bool is_const=false) throw (COM_exception)
Insert an object into the table.
void remove_object (std::string name, bool is_const=false) throw (COM_exception)
Remove an object from the table.
bool is_immutable (int i) const
whether the object mutable
const Object & operator[] (int i) const throw (COM_exception)
Access an object using its handle.
Object & operator[] (int i) throw (COM_exception)
const std::string & name (int i) const
Name of the object.
int size () const
std::pair< int, Object * > find (const std::string &name, bool is_const=false)
std::vector< std::string > get_names ()
Protected Attributes
I2O i2o
Mapping from index to objects.
N2I n2i
Mapping from names to indices.
std::list< int > salvaged
List of salvaged indices.
std::vector< std::string > names
Name of the objects.
Private Types
typedef std::vector< Object > I2O
Mapping from indices to objects.
typedef std::map< std::string,
int > N2I
Mapping from names to indices.
Detailed Description
template<class Object>
class Roccom_map< Object >
Supports mapping from names to handles and vice-versa for a module, window, function, or attribute.
Definition at line 43 of file maps.h.
Member Typedef Documentation
typedef std::vector<Object> I2O private
Mapping from indices to objects.
Definition at line 44 of file maps.h.
typedef std::map<std::string, int> N2I private
Mapping from names to indices.
Definition at line 45 of file maps.h.
typedef Object value_type
Definition at line 47 of file maps.h.
Constructor & Destructor Documentation
Roccom_map () inline
Definition at line 49 of file maps.h.
 {}
~Roccom_map () inline
Definition at line 50 of file maps.h.
 {}
Member Function Documentation
int add_object (std::string name, Object t, bool is_const = false) throw (COM_exception)
Insert an object into the table.
Definition at line 97 of file maps.h.
References i.
Referenced by Function_map::add_object().
 {
   if (is_const) name.append( " (const)");
   N2I::iterator it = n2i.find(name);
   int i = ( it == n2i.end()) ? -1 : it->second;
   if ( i>0)
   { i2o[i] = t; }
   else if ( salvaged.empty()) {
     i=i2o.size(); n2i[name] = i;
     i2o.push_back( t); names.push_back( name);
   }
   else {
     i=salvaged.front(); salvaged.pop_front();
     n2i[name] = i; i2o[i] = t; names[i] = name;
   }
   return i;
 }
std::pair<int,Object *> find (const std::string & name, bool is_const = false) inline
Definition at line 80 of file maps.h.
{
     N2I::iterator it=n2i.find( is_const?name+"(const)":name);
     if ( it == n2i.end())
       return std::pair<int,Object *>(-1,NULL);
     else
       return std::pair<int,Object *>(it->second, &i2o[ it->second]);
   }
std::vector<std::string> get_names () inline
Definition at line 88 of file maps.h.
 { return names; }
bool is_immutable (int i) const inline
whether the object mutable
Definition at line 61 of file maps.h.
   { return names[i].find(" (const)")!=std::string::npos; }
const std::string& name (int i) const inline
Name of the object.
Definition at line 76 of file maps.h.
Referenced by Roccom_base::print_profile(), and Roccom_base::set_profiling_barrier().
 { return names[i]; }
const Object& operator[] (int i) const throw (COM_exception) inline
Access an object using its handle.
Definition at line 65 of file maps.h.
{
     if ( i>=(int)i2o.size()) throw COM_exception( COM_UNKNOWN_ERROR);
     return i2o[i];
   }
Object& operator[] (int i) throw (COM_exception) inline
Definition at line 70 of file maps.h.
{
     if ( i>=(int)i2o.size()) throw COM_exception( COM_UNKNOWN_ERROR);
     return i2o[i];
   }
void remove_object (std::string name, bool is_const = false) throw (COM_exception)
Remove an object from the table.
Definition at line 119 of file maps.h.
References COM_UNKNOWN_ERROR.
{
   if (is_const) name.append( " (const)");
   N2I::iterator it = n2i.find(name);
   if ( it == n2i.end()) throw COM_exception( COM_UNKNOWN_ERROR);
   salvaged.push_back( it->second);
   n2i.erase(it);
 }
int size () const inline
Definition at line 78 of file maps.h.
Referenced by Roccom_base::set_profiling_barrier().
 { return names.size(); }
Member Data Documentation
I2O i2o protected
Mapping from index to objects.
Definition at line 90 of file maps.h.
Referenced by Roccom_map< std::pair< void *, std::set< std::string > > >::find(), and Roccom_map< std::pair< void *, std::set< std::string > > >::operator[]().
N2I n2i protected
Mapping from names to indices.
Definition at line 91 of file maps.h.
Referenced by Roccom_map< std::pair< void *, std::set< std::string > > >::find().
std::vector<std::string> names protected
Name of the objects.
Definition at line 93 of file maps.h.
Referenced by Roccom_map< std::pair< void *, std::set< std::string > > >::get_names(), Roccom_map< std::pair< void *, std::set< std::string > > >::is_immutable(), Roccom_map< std::pair< void *, std::set< std::string > > >::name(), and Roccom_map< std::pair< void *, std::set< std::string > > >::size().
std::list<int> salvaged protected
List of salvaged indices.
Definition at line 92 of file maps.h.
The documentation for this class was generated from the following file:
maps.h