Rocstar: rflu_modreadwritebcdatafile Module Reference
rflu_modreadwritebcdatafile Module Reference
Public Member Functions
logical function, public rflu_decidereadwritebcdatafile (pRegion)
subroutine, public rflu_readbcdatafile (pRegion)
subroutine, public rflu_writebcdatafile (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadWriteBcDataFile.F90,v $ $Revision: 1.6 $'
Detailed Description
Definition at line 39 of file RFLU_ModReadWriteBcDataFile.F90.
Member Function/Subroutine Documentation
logical function, public rflu_decidereadwritebcdatafile (type(t_region), pointer pRegion)
Definition at line 92 of file RFLU_ModReadWriteBcDataFile.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), and rfluinit().
subroutine, public rflu_readbcdatafile (type(t_region), pointer pRegion)
Definition at line 186 of file RFLU_ModReadWriteBcDataFile.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_initflowsolver().
subroutine, public rflu_writebcdatafile (type(t_region), pointer pRegion)
Definition at line 406 of file RFLU_ModReadWriteBcDataFile.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rfluinit().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModReadWriteBcDataFile.F90,v $ $Revision: 1.6 $' private
Definition at line 61 of file RFLU_ModReadWriteBcDataFile.F90.
The documentation for this module was generated from the following file:
RFLU_ModReadWriteBcDataFile.F90