Rocstar: Mesh::MeshUtilityObject Class Reference
Mesh::MeshUtilityObject Class Reference
#include <Mesh.H>
Public Types
enum MeshConType {
EN =0, ENDUAL, ED, EDDUAL,
EF, EFDUAL, DN, DNDUAL,
DF, DFDUAL, FN, FNDUAL,
NCONS
}
Public Member Functions
MeshUtilityObject ()
int NumberOfNodes () const
int NumberOfElements () const
NodalCoordinates & NC ()
const NodalCoordinates & NC () const
Connectivity & ECon ()
const Connectivity & ECon () const
Connectivity & Con (const MeshConType type)
const Connectivity & Con (const MeshConType type) const
Connectivity & GetCon (const MeshConType type)
const Connectivity & GetCon (const MeshConType type) const
int FormConnectivity (const MeshConType type)
int DestroyConnectivity (const MeshConType type)
~MeshUtilityObject ()
Protected Attributes
NodalCoordinates _nodal_coordinates
std::vector< Connectivity > _connectivities
Detailed Description
Definition at line 455 of file Mesh.H.
Member Enumeration Documentation
enum MeshConType
Enumerator
EN
ENDUAL
ED
EDDUAL
EF
EFDUAL
DN
DNDUAL
DF
DFDUAL
FN
FNDUAL
NCONS
Definition at line 457 of file Mesh.H.
 { EN=0,ENDUAL,ED,EDDUAL,EF,EFDUAL,DN,DNDUAL,DF,DFDUAL,FN, FNDUAL ,NCONS};
Constructor & Destructor Documentation
MeshUtilityObject () inline
Definition at line 462 of file Mesh.H.
References _connectivities, and NCONS.
                         : _nodal_coordinates()
     {
       //      std::cout << "Mesh utility constructor" << std::endl;
       //      _nodal_coordinates_ptr = new NodalCoordinates();
       _connectivities.resize(NCONS);
       //      _connectivities[EN] = new Connectivity();
     };
~MeshUtilityObject () inline
Definition at line 541 of file Mesh.H.
References _connectivities, _nodal_coordinates, and Mesh::NodalCoordinates::destroy().
     {
       //      std::cout << "destroying mesh util" << std::endl;
       _nodal_coordinates.destroy();
       //      delete _nodal_coordinates_ptr;
       std::vector<Connectivity>::iterator cpi = _connectivities.begin();
       while(cpi != _connectivities.end())
         cpi++->destroy();
     };
Member Function Documentation
Connectivity& Con (const MeshConType type) inline
Definition at line 487 of file Mesh.H.
References _connectivities.
     {
       //      if(!_connectivities[type])
       //        FormConnectivity(type);
       return(_connectivities[type]);
     };
const Connectivity& Con (const MeshConType type) const inline
Definition at line 493 of file Mesh.H.
References _connectivities.
     {
       //      if(!_connectivities[type])
       //        (const_cast<MeshUtilityObject*>(this))->FormConnectivity(type);
       return(_connectivities[type]);
     };
int DestroyConnectivity (const MeshConType type) inline
Definition at line 532 of file Mesh.H.
References _connectivities.
     {
       //      if(_connectivities[type]){
       _connectivities[type].destroy();
       //        delete _connectivities[type];
       //        _connectivities[type] = NULL;
       //      }
       return(0);
     };
Connectivity& ECon () inline
Definition at line 479 of file Mesh.H.
References _connectivities, and EN.
Referenced by FormConnectivity(), and Mesh::Partition::Read().
     {
       return(_connectivities[EN]);
     };
const Connectivity& ECon () const inline
Definition at line 483 of file Mesh.H.
References _connectivities, and EN.
     {
       return(_connectivities[EN]);
     };
int FormConnectivity (const MeshConType type) inline
Definition at line 513 of file Mesh.H.
References _connectivities, ECon(), ENDUAL, Mesh::Connectivity::Inverse(), and NC().
Referenced by GetCon().
     {
       switch(type)
         {
         case ENDUAL:
           //      if(_connectivities[type]){
           //        _connectivities[type]->destroy();
           //      }
           //      else
           //        _connectivities[type] = new Connectivity();
           ECon().Inverse(_connectivities[type],NC().Size());
           break;
         default:
           bool connectivity_known_type = false;
           assert(connectivity_known_type);
           break;
         }
       return(0);
     };
Connectivity& GetCon (const MeshConType type) inline
Definition at line 500 of file Mesh.H.
References _connectivities, empty(), and FormConnectivity().
Referenced by Mesh::Partition::GetBorderElements().
     {
       if(_connectivities[type].empty())
         FormConnectivity(type);
       return(_connectivities[type]);
     };
const Connectivity& GetCon (const MeshConType type) const inline
Definition at line 506 of file Mesh.H.
References _connectivities, and empty().
     {
       if(_connectivities[type].empty())
         (const_cast<MeshUtilityObject*>(this))->FormConnectivity(type);
       return(_connectivities[type]);
     };
NodalCoordinates& NC () inline
Definition at line 471 of file Mesh.H.
References _nodal_coordinates.
Referenced by FormConnectivity(), and Mesh::Partition::Read().
     {
       return(_nodal_coordinates);
     };
const NodalCoordinates& NC () const inline
Definition at line 475 of file Mesh.H.
References _nodal_coordinates.
     {
       return(_nodal_coordinates);
     };
int NumberOfElements () const inline
Definition at line 470 of file Mesh.H.
References _connectivities, and EN.
Referenced by Mesh::Partition::GetBorderElements(), and Mesh::Partition::Read().
 { return(_connectivities[EN].Nelem()); };
int NumberOfNodes () const inline
Definition at line 469 of file Mesh.H.
References _nodal_coordinates, and Mesh::NodalCoordinates::Size().
Referenced by Mesh::Partition::GetBorderElements(), and Mesh::Partition::Read().
 { return(_nodal_coordinates.Size()); };
Member Data Documentation
std::vector<Connectivity> _connectivities protected
Definition at line 460 of file Mesh.H.
Referenced by Con(), DestroyConnectivity(), ECon(), FormConnectivity(), GetCon(), MeshUtilityObject(), NumberOfElements(), and ~MeshUtilityObject().
NodalCoordinates _nodal_coordinates protected
Definition at line 459 of file Mesh.H.
Referenced by NC(), NumberOfNodes(), and ~MeshUtilityObject().
The documentation for this class was generated from the following file:
Mesh.H