Rocstar: MeshImplTags Class Reference
MeshImplTags Class Reference
Store tags and tag data for Mesquite's native mesh representation.
#include <MeshImplTags.hpp>
Classes
class TagData
Store data for a single tag.
class TagIterator
Iterate over list of valid tag handles.
Public Member Functions
~MeshImplTags ()
void clear ()
Clear all data.
size_t handle (const msq_std::string &name, MsqError &err) const
Get tag index from name.
const TagDescription & properties (size_t tag_handle, MsqError &err) const
Get tag properties.
size_t create (const msq_std::string &name, Mesh::TagType type, unsigned length, const void *defval, MsqError &err)
Create a new tag.
size_t create (const TagDescription &desc, MsqError &err)
Create a new tag.
void destroy (size_t tag_index, MsqError &err)
Remove a tag.
void set_element_data (size_t tag_handle, size_t num_indices, const size_t *elem_indices, const void *tag_data, MsqError &err)
Set tag data on elements.
void set_vertex_data (size_t tag_handle, size_t num_indices, const size_t *elem_indices, const void *tag_data, MsqError &err)
Set tag data on vertices.
void get_element_data (size_t tag_handle, size_t num_indices, const size_t *elem_indices, void *tag_data, MsqError &err) const
Get tag data on elements.
void get_vertex_data (size_t tag_handle, size_t num_indices, const size_t *elem_indices, void *tag_data, MsqError &err) const
Get tag data on vertices.
TagIterator tag_begin ()
TagIterator tag_end ()
bool tag_has_vertex_data (size_t index, MsqError &err)
Check if any vertices have tag.
bool tag_has_element_data (size_t index, MsqError &err)
Check if any elements have tag.
~MeshImplTags ()
void clear ()
Clear all data.
size_t handle (const msq_std::string &name, MsqError &err) const
Get tag index from name.
const TagDescription & properties (size_t tag_handle, MsqError &err) const
Get tag properties.
size_t create (const msq_std::string &name, Mesh::TagType type, unsigned length, const void *defval, MsqError &err)
Create a new tag.
size_t create (const TagDescription &desc, MsqError &err)
Create a new tag.
void destroy (size_t tag_index, MsqError &err)
Remove a tag.
void set_element_data (size_t tag_handle, size_t num_indices, const size_t *elem_indices, const void *tag_data, MsqError &err)
Set tag data on elements.
void set_vertex_data (size_t tag_handle, size_t num_indices, const size_t *elem_indices, const void *tag_data, MsqError &err)
Set tag data on vertices.
void get_element_data (size_t tag_handle, size_t num_indices, const size_t *elem_indices, void *tag_data, MsqError &err) const
Get tag data on elements.
void get_vertex_data (size_t tag_handle, size_t num_indices, const size_t *elem_indices, void *tag_data, MsqError &err) const
Get tag data on vertices.
TagIterator tag_begin ()
TagIterator tag_end ()
bool tag_has_vertex_data (size_t index, MsqError &err)
Check if any vertices have tag.
bool tag_has_element_data (size_t index, MsqError &err)
Check if any elements have tag.
Static Public Member Functions
static size_t size_from_tag_type (Mesh::TagType type)
Get the size of the passed data type.
static size_t size_from_tag_type (Mesh::TagType type)
Get the size of the passed data type.
Private Attributes
msq_std::vector< TagData * > tagList
Friends
class MeshImplTags::TagIterator
Detailed Description
Store tags and tag data for Mesquite's native mesh representation.
Stores for each tag: properties, element data, and vertex data. The tag element and vertex data sets are maps between some element or vertex index and a tag value.
Definition at line 72 of file includeLinks/MeshImplTags.hpp.
Constructor & Destructor Documentation
~MeshImplTags () inline
Definition at line 75 of file includeLinks/MeshImplTags.hpp.
References MeshImplTags::clear().
 { clear(); }
~MeshImplTags () inline
Definition at line 75 of file src/Mesh/MeshImplTags.hpp.
References MeshImplTags::clear().
 { clear(); }
Member Function Documentation
void clear ()
Clear all data.
Definition at line 48 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::tagList.
Referenced by MeshImpl::clear(), and MeshImplTags::~MeshImplTags().
 {
   for (msq_std::vector<TagData*>::iterator iter = tagList.begin();
        iter != tagList.end(); ++iter)
     if (*iter)
       delete *iter;
   tagList.clear();
 }
void clear ()
Clear all data.
size_t create (const msq_std::string & name, Mesh::TagType type, unsigned length, const void * defval, MsqError & err)
Create a new tag.
Create a new tag with the passed properties
Parameters
name Tag name (must be unique)
type Tag data type
length Number of values in tag (array length, 1 for scalar)
defval Optional default value for tag
Definition at line 70 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::TagData::defaultValue, MeshImplTags::TagData::desc, MeshImplTags::handle(), MsqError::INVALID_ARG, MSQ_SETERR, TagDescription::size, MeshImplTags::size_from_tag_type(), MsqError::TAG_ALREADY_EXISTS, and MeshImplTags::tagList.
Referenced by MeshImpl::vtk_read_cell_data(), and MeshImpl::vtk_read_point_data().
 {
   size_t h = handle( name, err );
   if (h)
   {
     MSQ_SETERR(err)(name, MsqError::TAG_ALREADY_EXISTS);
     return 0;
   }
   if (length == 0 || size_from_tag_type(type) == 0)
   {
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     return 0;
   }
   TagData* tag = new TagData( name, type, length );
   h = tagList.size();
   tagList.push_back(tag);
   if (defval)
   {
     tag->defaultValue = malloc( tag->desc.size );
     memcpy( tag->defaultValue, defval, tag->desc.size );
   }
   return h+1;
 }
size_t create (const msq_std::string & name, Mesh::TagType type, unsigned length, const void * defval, MsqError & err)
Create a new tag.
Create a new tag with the passed properties
Parameters
name Tag name (must be unique)
type Tag data type
length Number of values in tag (array length, 1 for scalar)
defval Optional default value for tag
size_t create (const TagDescription & desc, MsqError & err)
Create a new tag.
Create a new tag with the passed properties
size_t create (const TagDescription & desc, MsqError & err)
Create a new tag.
Create a new tag with the passed properties
Definition at line 102 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::handle(), MsqError::INVALID_ARG, MSQ_SETERR, TagDescription::name, TagDescription::size, MeshImplTags::size_from_tag_type(), MsqError::TAG_ALREADY_EXISTS, MeshImplTags::tagList, and TagDescription::type.
 {
   size_t h = handle( desc.name.c_str(), err );
   if (h)
   {
     MSQ_SETERR(err)(desc.name.c_str(), MsqError::TAG_ALREADY_EXISTS);
     return 0;
   }
   if (desc.size == 0 || (desc.size % size_from_tag_type(desc.type)) != 0)
   {
     MSQ_SETERR(err)(MsqError::INVALID_ARG);
     return 0;
   }
   TagData* tag = new TagData( desc );
   h = tagList.size();
   tagList.push_back(tag);
   return h+1;
 }
void destroy (size_t tag_index, MsqError & err)
Remove a tag.
void destroy (size_t tag_index, MsqError & err)
Remove a tag.
Definition at line 125 of file Mesh/MeshImplTags.cpp.
References MSQ_SETERR, MsqError::TAG_NOT_FOUND, and MeshImplTags::tagList.
Referenced by MeshImpl::tag_delete().
 {
   --tag_index;
   if (tag_index >= tagList.size() || 0 == tagList[tag_index])
   {
     MSQ_SETERR(err)(MsqError::TAG_NOT_FOUND);
     return ;
   }
   delete tagList[tag_index];
   tagList[tag_index] = 0;
 }
void get_element_data (size_t tag_handle, size_t num_indices, const size_t * elem_indices, void * tag_data, MsqError & err) const
Get tag data on elements.
Definition at line 213 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::TagData::defaultValue, MeshImplTags::TagData::desc, MeshImplTags::TagData::elementCount, MeshImplTags::TagData::elementData, for(), i, MsqError::INVALID_ARG, MSQ_SETERR, TagDescription::size, MsqError::TAG_NOT_FOUND, and MeshImplTags::tagList.
Referenced by MeshImpl::tag_get_element_data(), and MeshImpl::write_vtk().
 {
   --tag_index;
   if (tag_index >= tagList.size() || !tagList[tag_index])
   {
     MSQ_SETERR(err)("Invalid tag handle", MsqError::INVALID_ARG);
     return;
   }
   TagData* tag = tagList[tag_index];
   char* iter = (char*)values;
   const char* data = (const char*)tag->elementData;
   for (size_t i = 0; i < num_indices; ++i)
   {
     const void* ptr;
     size_t index = index_array[i];
     if (index >= tag->elementCount)
     {
       ptr = tag->defaultValue;
       if (!ptr)
       {
         MSQ_SETERR(err)(MsqError::TAG_NOT_FOUND);
         return;
       }
     }
     else
     {
       ptr = data + index * tag->desc.size;
     }
     memcpy( iter, ptr, tag->desc.size );
     iter += tag->desc.size;
   }
 }
void get_element_data (size_t tag_handle, size_t num_indices, const size_t * elem_indices, void * tag_data, MsqError & err) const
Get tag data on elements.
void get_vertex_data (size_t tag_handle, size_t num_indices, const size_t * elem_indices, void * tag_data, MsqError & err) const
Get tag data on vertices.
Definition at line 305 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::TagData::defaultValue, MeshImplTags::TagData::desc, for(), i, MsqError::INVALID_ARG, MSQ_SETERR, TagDescription::size, MsqError::TAG_NOT_FOUND, MeshImplTags::tagList, MeshImplTags::TagData::vertexCount, and MeshImplTags::TagData::vertexData.
Referenced by MeshImpl::read_vtk(), MeshImpl::tag_get_vertex_data(), and MeshImpl::write_vtk().
 {
   --tag_index;
   if (tag_index >= tagList.size() || !tagList[tag_index])
   {
     MSQ_SETERR(err)("Invalid tag handle", MsqError::INVALID_ARG);
     return;
   }
   TagData* tag = tagList[tag_index];
   char* iter = (char*)values;
   const char* data = (const char*)tag->vertexData;
   for (size_t i = 0; i < num_indices; ++i)
   {
     const void* ptr;
     size_t index = index_array[i];
     if (index >= tag->vertexCount)
     {
       ptr = tag->defaultValue;
       if (!ptr)
       {
         MSQ_SETERR(err)(MsqError::TAG_NOT_FOUND);
         return;
       }
     }
     else
     {
       ptr = data + index * tag->desc.size;
     }
     memcpy( iter, ptr, tag->desc.size );
     iter += tag->desc.size;
   }
 }
void get_vertex_data (size_t tag_handle, size_t num_indices, const size_t * elem_indices, void * tag_data, MsqError & err) const
Get tag data on vertices.
size_t handle (const msq_std::string & name, MsqError & err) const
Get tag index from name.
size_t handle (const msq_std::string & name, MsqError & err) const
Get tag index from name.
Definition at line 138 of file Mesh/MeshImplTags.cpp.
References i, and MeshImplTags::tagList.
Referenced by MeshImplTags::create(), rflo_initgenxinterface(), rflu_modrocstaradmin::rflu_genx_initrocman(), MeshImpl::tag_get(), MeshImpl::vtk_read_cell_data(), and MeshImpl::vtk_read_point_data().
 {
   for (size_t i = 0; i < tagList.size(); ++i)
     if (tagList[i] && tagList[i]->desc.name == name)
       return i+1;
   return 0;
 }
const TagDescription& properties (size_t tag_handle, MsqError & err) const
Get tag properties.
const TagDescription & properties (size_t tag_handle, MsqError & err) const
Get tag properties.
Definition at line 147 of file Mesh/MeshImplTags.cpp.
References MsqError::INVALID_ARG, MSQ_SETERR, and MeshImplTags::tagList.
Referenced by MeshImpl::read_vtk(), MeshImpl::tag_properties(), MeshImpl::vtk_read_cell_data(), MeshImpl::vtk_read_point_data(), and MeshImpl::write_vtk().
 {
   static TagDescription dummy_desc;
   --tag_index;
   if (tag_index >= tagList.size() || !tagList[tag_index])
   {
     MSQ_SETERR(err)("Invalid tag handle", MsqError::INVALID_ARG);
     return dummy_desc;
   }
   return tagList[tag_index]->desc;
 }
void set_element_data (size_t tag_handle, size_t num_indices, const size_t * elem_indices, const void * tag_data, MsqError & err)
Set tag data on elements.
Definition at line 162 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::TagData::defaultValue, MeshImplTags::TagData::desc, MeshImplTags::TagData::elementCount, MeshImplTags::TagData::elementData, i, MsqError::INVALID_ARG, MSQ_SETERR, TagDescription::size, and MeshImplTags::tagList.
Referenced by MeshImpl::tag_set_element_data(), and MeshImpl::vtk_read_cell_data().
 {
   size_t i;
   char* data;
   --tag_index;
   if (tag_index >= tagList.size() || !tagList[tag_index])
   {
     MSQ_SETERR(err)("Invalid tag handle", MsqError::INVALID_ARG);
     return;
   }
   TagData* tag = tagList[tag_index];
     // Get highest element index
   size_t total = tag->elementCount;
   for (i = 0; i < num_indices; ++i)
     if (index_array[i] >= total)
       total = index_array[i] + 1;
     // If need more space
   if (total > tag->elementCount)
   {
       // allocate more space
     tag->elementData = realloc( tag->elementData, tag->desc.size * total );
       // if a default value, initialize new space with it
     if (tag->defaultValue)
     {
       data = ((char*)tag->elementData) + tag->elementCount * tag->desc.size;
       for (i = tag->elementCount; i < total; ++i)
       {
         memcpy( data, tag->defaultValue, tag->desc.size );
         data += tag->desc.size;
       }
     }
     tag->elementCount = total;
   }
     // Store passed tag values
   data = (char*)tag->elementData;
   const char* iter = (const char*)values;
   for (i = 0; i < num_indices; ++i)
   {
     memcpy( data + index_array[i]*tag->desc.size, iter, tag->desc.size );
     iter += tag->desc.size;
   }
 }
void set_element_data (size_t tag_handle, size_t num_indices, const size_t * elem_indices, const void * tag_data, MsqError & err)
Set tag data on elements.
void set_vertex_data (size_t tag_handle, size_t num_indices, const size_t * elem_indices, const void * tag_data, MsqError & err)
Set tag data on vertices.
Definition at line 254 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::TagData::defaultValue, MeshImplTags::TagData::desc, i, MsqError::INVALID_ARG, MSQ_SETERR, TagDescription::size, MeshImplTags::tagList, MeshImplTags::TagData::vertexCount, and MeshImplTags::TagData::vertexData.
Referenced by MeshImpl::tag_set_vertex_data(), and MeshImpl::vtk_read_point_data().
 {
   size_t i;
   char* data;
   --tag_index;
   if (tag_index >= tagList.size() || !tagList[tag_index])
   {
     MSQ_SETERR(err)("Invalid tag handle", MsqError::INVALID_ARG);
     return;
   }
   TagData* tag = tagList[tag_index];
     // Get highest element index
   size_t total = tag->vertexCount;
   for (i = 0; i < num_indices; ++i)
     if (index_array[i] >= total)
       total = index_array[i] + 1;
     // If need more space
   if (total > tag->vertexCount)
   {
       // allocate more space
     tag->vertexData = realloc( tag->vertexData, tag->desc.size * total );
       // if a default value, initialize new space with it
     if (tag->defaultValue)
     {
       data = ((char*)tag->vertexData) + tag->vertexCount * tag->desc.size;
       for (i = tag->vertexCount; i < total; ++i)
       {
         memcpy( data, tag->defaultValue, tag->desc.size );
         data += tag->desc.size;
       }
     }
     tag->vertexCount = total;
   }
     // Store passed tag values
   data = (char*)tag->vertexData;
   const char* iter = (const char*)values;
   for (i = 0; i < num_indices; ++i)
   {
     memcpy( data + index_array[i]*tag->desc.size, iter, tag->desc.size );
     iter += tag->desc.size;
   }
 }
void set_vertex_data (size_t tag_handle, size_t num_indices, const size_t * elem_indices, const void * tag_data, MsqError & err)
Set tag data on vertices.
static size_t size_from_tag_type (Mesh::TagType type) static
Get the size of the passed data type.
size_t size_from_tag_type (Mesh::TagType type) static
Get the size of the passed data type.
Definition at line 58 of file Mesh/MeshImplTags.cpp.
References Mesh::BOOL, Mesh::BYTE, Mesh::DOUBLE, Mesh::HANDLE, and Mesh::INT.
Referenced by MeshImplTags::create(), MeshImpl::tag_properties(), and MeshImpl::vtk_write_attrib_data().
 {
   switch( type ) {
     case Mesh::BYTE:   return 1;
     case Mesh::BOOL:   return sizeof(bool);
     case Mesh::DOUBLE: return sizeof(double);
     case Mesh::INT:    return sizeof(int);
     case Mesh::HANDLE: return sizeof(void*);
     default: assert(0); return 0;
   }
 }
TagIterator tag_begin ()
MeshImplTags::TagIterator tag_begin ()
Definition at line 372 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::tagList.
Referenced by MeshImpl::write_vtk().
 {
   size_t index = 0;
   while (index < tagList.size() && tagList[index] == NULL)
     ++index;
   return TagIterator( this, index );
 }
TagIterator tag_end () inline
Definition at line 210 of file src/Mesh/MeshImplTags.hpp.
References MeshImplTags::tagList.
 { return TagIterator(this,tagList.size()); }
TagIterator tag_end () inline
Definition at line 210 of file includeLinks/MeshImplTags.hpp.
References MeshImplTags::tagList.
Referenced by MeshImpl::write_vtk().
 { return TagIterator(this,tagList.size()); }
bool tag_has_element_data (size_t index, MsqError & err)
Check if any elements have tag.
Definition at line 359 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::TagData::defaultValue, MeshImplTags::TagData::elementData, MsqError::INVALID_ARG, MSQ_SETERR, and MeshImplTags::tagList.
Referenced by MeshImpl::write_vtk().
 {
   --tag_index;
   if (tag_index >= tagList.size() || !tagList[tag_index])
   {
     MSQ_SETERR(err)("Invalid tag handle", MsqError::INVALID_ARG);
     return false;
   }
   TagData* tag = tagList[tag_index];
   return 0 != tag->elementData || tag->defaultValue;
 }
bool tag_has_element_data (size_t index, MsqError & err)
Check if any elements have tag.
bool tag_has_vertex_data (size_t index, MsqError & err)
Check if any vertices have tag.
bool tag_has_vertex_data (size_t index, MsqError & err)
Check if any vertices have tag.
Definition at line 346 of file Mesh/MeshImplTags.cpp.
References MeshImplTags::TagData::defaultValue, MsqError::INVALID_ARG, MSQ_SETERR, MeshImplTags::tagList, and MeshImplTags::TagData::vertexData.
Referenced by MeshImpl::read_vtk(), and MeshImpl::write_vtk().
 {
   --tag_index;
   if (tag_index >= tagList.size() || !tagList[tag_index])
   {
     MSQ_SETERR(err)("Invalid tag handle", MsqError::INVALID_ARG);
     return false;
   }
   TagData* tag = tagList[tag_index];
   return 0 != tag->vertexData || tag->defaultValue;
 }
Friends And Related Function Documentation
MeshImplTags::TagIterator friend
Definition at line 219 of file includeLinks/MeshImplTags.hpp.
Member Data Documentation
msq_std::vector< TagData * > tagList private
Definition at line 221 of file includeLinks/MeshImplTags.hpp.
Referenced by MeshImplTags::clear(), MeshImplTags::create(), MeshImplTags::destroy(), MeshImplTags::get_element_data(), MeshImplTags::get_vertex_data(), MeshImplTags::handle(), MeshImplTags::TagIterator::operator++(), MeshImplTags::TagIterator::operator--(), MeshImplTags::properties(), MeshImplTags::set_element_data(), MeshImplTags::set_vertex_data(), MeshImplTags::tag_begin(), MeshImplTags::tag_end(), MeshImplTags::tag_has_element_data(), and MeshImplTags::tag_has_vertex_data().
The documentation for this class was generated from the following files:
includeLinks/MeshImplTags.hpp
Mesh/MeshImplTags.cpp