Rocstar: VectorS2< FT > Class Template Reference
VectorS2< FT > Class Template Reference
#include <simple_cartesian_classes.h>
Public Types
typedef VectorS2< FT > Self
typedef DirectionS2< FT > Direction
typedef Aff_transformationS2< FT > Aff_transformation
Public Member Functions
VectorS2 ()
VectorS2 (const Null_vector &)
VectorS2 (const FT &hx, const FT &hy, const FT &hw)
VectorS2 (const FT &x, const FT &y)
bool operator== (const VectorS2< FT > &v) const
bool operator!= (const VectorS2< FT > &v) const
bool operator== (const Null_vector &) const
bool operator!= (const Null_vector &p) const
int id () const
FT hx () const
FT hy () const
FT hw () const
FT x () const
FT y () const
FT cartesian (int i) const
FT operator[] (int i) const
FT homogeneous (int i) const
int dimension () const
VectorS2< FT > operator+ (const VectorS2< FT > &w) const
VectorS2< FT > operator- (const VectorS2< FT > &w) const
VectorS2< FT > operator- () const
FT operator* (const VectorS2< FT > &w) const
VectorS2< FT > operator/ (const FT &c) const
DirectionS2< FT > direction () const
VectorS2< FT > perpendicular (const Orientation &o) const
VectorS2< FT > transform (const Aff_transformationS2< FT > &) const
VectorS2 ()
VectorS2 (const Null_vector &)
VectorS2 (const FT &hx, const FT &hy, const FT &hw)
VectorS2 (const FT &x, const FT &y)
~VectorS2 ()
Self & operator= (const Self &v)
bool operator== (const Self &v) const
bool operator== (const Null_vector &) const
int id () const
FT hx () const
FT hy () const
FT hw () const
FT homogeneous (int i) const
const FT & x () const
const FT & y () const
FT & x ()
FT & y ()
const FT & cartesian (int i) const
FT & cartesian (int i)
FT & operator[] (int i)
const FT & operator[] (int i) const
int dimension () const
Self operator+ (const Self &v) const
Self operator- (const Self &v) const
Self operator- (const Null_vector &) const
Self operator- () const
FT operator* (const Self &v) const
Self operator/ (const FT &c) const
Self & operator+= (const Self &v)
Self & operator-= (const Self &v)
Self & operator*= (const FT c)
Self & operator/= (const FT c)
Self & operator*= (const Self &v)
Self & operator/= (const Self &v)
Self perpendicular (const Orientation &o) const
Self transform (const Aff_transformation &t) const
const Direction & direction () const
Public Attributes
FT e0
FT e1
Protected Member Functions
VectorS2 (const PointS2< FT > &p)
VectorS2 (const DirectionS2< FT > &d)
Private Attributes
FT _x
FT _y
Friends
class DirectionS2< FT >
Detailed Description
template<class FT>
class VectorS2< FT >
Definition at line 55 of file simple_cartesian_classes.h.
Member Typedef Documentation
typedef Aff_transformationS2<FT> Aff_transformation
Definition at line 35 of file include/CGAL/SimpleCartesian/VectorS2.h.
typedef DirectionS2<FT> Direction
Definition at line 34 of file include/CGAL/SimpleCartesian/VectorS2.h.
typedef VectorS2<FT> Self
Definition at line 33 of file include/CGAL/SimpleCartesian/VectorS2.h.
Constructor & Destructor Documentation
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE VectorS2 ()
Definition at line 117 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
 {}
CGAL_KERNEL_CTOR_INLINE VectorS2 (const Null_vector &)
Definition at line 121 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
 : e0(FT(0)), e1(FT(0)) {}
CGAL_KERNEL_CTOR_MEDIUM_INLINE VectorS2 (const FT & hx, const FT & hy, const FT & hw)
Definition at line 125 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References DirectionS2< FT >::e0, and DirectionS2< FT >::e1.
 {
   if( hw != FT(1))
   { e0 = hx/hw; e1 = hy/hw; }
   else
   { e0 = hx; e1 = hy; }
 }
CGAL_KERNEL_CTOR_INLINE VectorS2 (const FT & x, const FT & y)
Definition at line 135 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
 : e0(x), e1(y) {}
CGAL_KERNEL_CTOR_INLINE VectorS2 (const PointS2< FT > & p) protected
Definition at line 144 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References DirectionS2< FT >::e0, PointS2< FT >::e0, DirectionS2< FT >::e1, and PointS2< FT >::e1.
 { e0 = d.e0; e1 = d.e1; }
CGAL_KERNEL_CTOR_INLINE VectorS2 (const DirectionS2< FT > & d) protected
Definition at line 139 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References DirectionS2< FT >::e0, and DirectionS2< FT >::e1.
 { e0 = d.e0; e1 = d.e1; }
VectorS2 () inline
Definition at line 37 of file include/CGAL/SimpleCartesian/VectorS2.h.
 {}
VectorS2 (const Null_vector &) inline
Definition at line 39 of file include/CGAL/SimpleCartesian/VectorS2.h.
 : _x(0), _y(0) {}
VectorS2 (const FT & hx, const FT & hy, const FT & hw) inline
Definition at line 40 of file include/CGAL/SimpleCartesian/VectorS2.h.
 : _x(hx/hw), _y(hy/hw) {}
VectorS2 (const FT & x, const FT & y) inline
Definition at line 41 of file include/CGAL/SimpleCartesian/VectorS2.h.
 : _x(x), _y(y) {}
~VectorS2 () inline
Definition at line 42 of file include/CGAL/SimpleCartesian/VectorS2.h.
 {}
Member Function Documentation
const FT& cartesian (int i) const inline
Definition at line 61 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, VectorS2< FT >::_y, and CGAL_kernel_precondition.
{
     CGAL_kernel_precondition( (i == 0) || (i == 1) );
     return (i == 0) ? _x : _y;
   }
FT& cartesian (int i) inline
Definition at line 66 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, VectorS2< FT >::_y, and CGAL_kernel_precondition.
{
     CGAL_kernel_precondition( (i == 0) || (i == 1) );
     return (i == 0) ? _x : _y;
   }
CGAL_KERNEL_INLINE FT cartesian (int i) const
Definition at line 183 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References CGAL_kernel_precondition, x, and y.
Referenced by VectorS2< FT >::homogeneous(), and VectorS2< FT >::operator[]().
 {
   CGAL_kernel_precondition( (i == 0) || (i == 1) );
   return (i == 0) ? x() : y();
 }
int dimension () const inline
Definition at line 74 of file include/CGAL/SimpleCartesian/VectorS2.h.
 { return 2; }
int dimension () const inline
Definition at line 196 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
 { return 2; }
DirectionS2< FT > direction () const inline
Definition at line 251 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
 { return DirectionS2<FT>(*this) ; }
const Direction& direction () const inline
Definition at line 112 of file include/CGAL/SimpleCartesian/VectorS2.h.
     { return reinterpret_cast<const Direction&>(*this); }
FT homogeneous (int i) const inline
Definition at line 54 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::cartesian().
 { return (i == 2) ? FT(1) : cartesian(i); }
CGAL_KERNEL_INLINE FT homogeneous (int i) const
Definition at line 216 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
 { return (i == 2) ? FT(1) : cartesian(i); }
FT hw () const inline
Definition at line 53 of file include/CGAL/SimpleCartesian/VectorS2.h.
 { return FT(1); }
FT hw () const inline
Definition at line 211 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
 { return FT(1); }
FT hx () const inline
Definition at line 51 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x.
 { return _x; }
FT hx () const inline
Definition at line 201 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References DirectionS2< FT >::e0.
 { return e0; }
FT hy () const inline
Definition at line 52 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_y.
 { return _y; }
FT hy () const inline
Definition at line 206 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References DirectionS2< FT >::e1.
 { return e1; }
int id () const inline
Definition at line 49 of file include/CGAL/SimpleCartesian/VectorS2.h.
 { return (int)this; }
int id () const
bool operator!= (const VectorS2< FT > & v) const inline
Definition at line 154 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References v.
 { return !(*this == v); }
bool operator!= (const Null_vector & p) const inline
Definition at line 164 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References v.
 { return !(*this == v); }
FT operator* (const Self & v) const inline
Definition at line 81 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
 { return _x * v._x + _y * v._y; }
CGAL_KERNEL_INLINE FT operator* (const VectorS2< FT > & w) const
Definition at line 236 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References x, VectorS2< FT >::x(), y, and VectorS2< FT >::y().
 { return x() * w.x() + y() * w.y() ; }
Self& operator*= (const FT c) inline
Definition at line 93 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
     { _x *= c; _y *=c; return *this; }
Self& operator*= (const Self & v) inline
Definition at line 98 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
     { _x *= v._x; _y *=v._y; return *this; }
Self operator+ (const Self & v) const inline
Definition at line 76 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
 { return Self(_x + v._x, _y + v._y); }
CGAL_KERNEL_INLINE VectorS2< FT > operator+ (const VectorS2< FT > & w) const
Definition at line 221 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References x, VectorS2< FT >::x(), y, and VectorS2< FT >::y().
 { return VectorS2<FT>(x() + w.x(), y() + w.y()) ; }
Self& operator+= (const Self & v) inline
Definition at line 85 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
{
     _x += v._x; _y+=v._y;
     return *this;
   }
Self operator- (const Self & v) const inline
Definition at line 77 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
 { return Self(_x - v._x, _y - v._y); }
Self operator- (const Null_vector &) const inline
Definition at line 78 of file include/CGAL/SimpleCartesian/VectorS2.h.
 { return *this; }
Self operator- () const inline
Definition at line 79 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
 { return Self(-_x, -_y); }
CGAL_KERNEL_INLINE VectorS2< FT > operator- (const VectorS2< FT > & w) const
Definition at line 226 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References x, VectorS2< FT >::x(), y, and VectorS2< FT >::y().
 { return VectorS2<FT>(x() - w.x(), y() - w.y()) ; }
CGAL_KERNEL_INLINE VectorS2< FT > operator- () const
Definition at line 231 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References x, and y.
 { return VectorS2<FT>(-x(), -y()) ; }
Self& operator-= (const Self & v) inline
Definition at line 89 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
{
     _x -= v._x; _y-=v._y;
     return *this;
   }
Self operator/ (const FT & c) const inline
Definition at line 82 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
 { return Self( _x/c, _y/c); }
CGAL_KERNEL_INLINE VectorS2< FT > operator/ (const FT & c) const
Definition at line 246 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References x, and y.
 { return VectorS2<FT>( x()/c, y()/c) ; }
Self& operator/= (const FT c) inline
Definition at line 95 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
     { _x /= c; _y /=c; return *this; }
Self& operator/= (const Self & v) inline
Definition at line 100 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
     { _x /= v._x; _y /=v._y; return *this; }
Self& operator= (const Self & v) inline
Definition at line 44 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
 { _x=v._x; _y=v._y; return *this; }
bool operator== (const Self & v) const inline
Definition at line 46 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
 { return _x==v._x && _y==v._y; }
bool operator== (const Null_vector &) const inline
Definition at line 47 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, and VectorS2< FT >::_y.
 { return _x==FT(0) && _y==FT(0); }
CGAL_KERNEL_INLINE bool operator== (const VectorS2< FT > & v) const
Definition at line 149 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References x, VectorS2< FT >::x(), y, and VectorS2< FT >::y().
 { return (x() == v.x()) && (y() == v.y()); }
bool operator== (const Null_vector &) const inline
Definition at line 159 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References x, and y.
 { return (x() == FT(0)) && (y() == FT(0)); }
FT& operator[] (int i) inline
Definition at line 71 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::cartesian().
 { return cartesian(i); }
const FT& operator[] (int i) const inline
Definition at line 72 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::cartesian().
 { return cartesian(i); }
FT operator[] (int i) const inline
Definition at line 191 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
 { return cartesian(i); }
CGAL_KERNEL_MEDIUM_INLINE VectorS2< FT > perpendicular (const Orientation & o) const
Definition at line 256 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References CGAL_kernel_precondition, COLLINEAR, COUNTERCLOCKWISE, x, and y.
 {
   CGAL_kernel_precondition( o != COLLINEAR );
   if (o == COUNTERCLOCKWISE)
     return VectorS2<FT>(-y(), x());
   else
     return VectorS2<FT>(y(), -x());
 }
Self perpendicular (const Orientation & o) const inline
Definition at line 103 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x, VectorS2< FT >::_y, CGAL_kernel_precondition, COLLINEAR, and COUNTERCLOCKWISE.
{
     CGAL_kernel_precondition( o != COLLINEAR );
     if (o == COUNTERCLOCKWISE) return Self(-_y, _x);
     else return Self(_y, -_x);
   }
VectorS2< FT > transform (const Aff_transformationS2< FT > & t) const inline
Definition at line 267 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References Aff_transformationS2< FT >::transform().
 { return t.transform(*this); }
Self transform (const Aff_transformation & t) const inline
Definition at line 108 of file include/CGAL/SimpleCartesian/VectorS2.h.
References Aff_transformationS2< FT >::transform().
     { return t.transform(*this); }
const FT& x () const inline
Definition at line 56 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x.
 { return _x; }
FT& x () inline
Definition at line 58 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_x.
 { return _x; }
FT x () const inline
Definition at line 169 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References DirectionS2< FT >::e0.
Referenced by VectorS2< FT >::operator*(), operator*(), VectorS2< FT >::operator+(), operator+(), PointS2< FT >::operator+=(), VectorS2< FT >::operator-(), operator-(), PointS2< FT >::operator-=(), operator<<(), VectorS2< FT >::operator==(), operator>>(), Aff_transformation_repS2< FT >::transform(), Rotation_repS2< FT >::transform(), and Scaling_repS2< FT >::transform().
 {
   return e0;
 }
const FT& y () const inline
Definition at line 57 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_y.
 { return _y; }
FT& y () inline
Definition at line 59 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::_y.
 { return _y; }
FT y () const inline
Definition at line 176 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
References DirectionS2< FT >::e1.
Referenced by VectorS2< FT >::operator*(), operator*(), VectorS2< FT >::operator+(), operator+(), PointS2< FT >::operator+=(), VectorS2< FT >::operator-(), operator-(), PointS2< FT >::operator-=(), operator<<(), VectorS2< FT >::operator==(), operator>>(), Aff_transformation_repS2< FT >::transform(), Rotation_repS2< FT >::transform(), and Scaling_repS2< FT >::transform().
 {
   return e1;
 }
Friends And Related Function Documentation
friend class DirectionS2< FT > friend
Definition at line 61 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
Member Data Documentation
FT _x private
Definition at line 115 of file include/CGAL/SimpleCartesian/VectorS2.h.
Referenced by VectorS2< FT >::cartesian(), VectorS2< FT >::hx(), VectorS2< FT >::operator*(), VectorS2< FT >::operator*=(), VectorS2< FT >::operator+(), VectorS2< FT >::operator+=(), VectorS2< FT >::operator-(), VectorS2< FT >::operator-=(), VectorS2< FT >::operator/(), VectorS2< FT >::operator/=(), VectorS2< FT >::operator=(), VectorS2< FT >::operator==(), VectorS2< FT >::perpendicular(), and VectorS2< FT >::x().
FT _y private
Definition at line 115 of file include/CGAL/SimpleCartesian/VectorS2.h.
Referenced by VectorS2< FT >::cartesian(), VectorS2< FT >::hy(), VectorS2< FT >::operator*(), VectorS2< FT >::operator*=(), VectorS2< FT >::operator+(), VectorS2< FT >::operator+=(), VectorS2< FT >::operator-(), VectorS2< FT >::operator-=(), VectorS2< FT >::operator/(), VectorS2< FT >::operator/=(), VectorS2< FT >::operator=(), VectorS2< FT >::operator==(), VectorS2< FT >::perpendicular(), and VectorS2< FT >::y().
FT e0
Definition at line 105 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
Referenced by DirectionS2< FT >::DirectionS2(), and PointS2< FT >::PointS2().
FT e1
Definition at line 106 of file CGAL/include/CGAL/SimpleCartesian/VectorS2.h.
Referenced by DirectionS2< FT >::DirectionS2(), and PointS2< FT >::PointS2().
The documentation for this class was generated from the following files:
simple_cartesian_classes.h
include/CGAL/SimpleCartesian/VectorS2.h