Rocstar: Random_access_adaptor< IC > Class Template Reference
Random_access_adaptor< IC > Class Template Reference
#include <Random_access_adaptor.h>
Public Types
typedef Index::size_type size_type
typedef IC iterator
typedef IC Circulator
Public Member Functions
void init_index (IC i, const IC &j, std::forward_iterator_tag)
void init_index (const IC &i, const IC &j, std::bidirectional_iterator_tag)
void init_index (const IC &i, const IC &, std::random_access_iterator_tag)
void init_index (const IC &i, const IC &j)
void reserve (size_type r, std::forward_iterator_tag)
void reserve (size_type r, std::bidirectional_iterator_tag)
void reserve (size_type, std::random_access_iterator_tag)
void push_back (const IC &k, std::forward_iterator_tag)
void push_back (const IC &k, std::bidirectional_iterator_tag)
void push_back (const IC &, std::random_access_iterator_tag)
const IC & find (size_type n, std::forward_iterator_tag) const
const IC & find (size_type n, std::bidirectional_iterator_tag) const
IC find (size_type n, std::random_access_iterator_tag) const
Random_access_adaptor ()
Random_access_adaptor (const IC &i)
Random_access_adaptor (const IC &i, const IC &j)
void reserve (size_type r)
IC find (size_type n) const
IC operator[] (size_type n) const
void push_back (const IC &k)
Protected Types
typedef std::vector< IC > Index
Protected Attributes
Index index
IC start
Detailed Description
template<class IC>
class Random_access_adaptor< IC >
Definition at line 61 of file Random_access_adaptor.h.
Member Typedef Documentation
typedef IC Circulator
Definition at line 133 of file Random_access_adaptor.h.
typedef std::vector< IC> Index protected
Definition at line 75 of file Random_access_adaptor.h.
typedef IC iterator
Definition at line 132 of file Random_access_adaptor.h.
typedef Index::size_type size_type
Definition at line 80 of file Random_access_adaptor.h.
Constructor & Destructor Documentation
Random_access_adaptor () inline
Definition at line 135 of file Random_access_adaptor.h.
 : start(IC()) {}
Random_access_adaptor (const IC & i) inline
Definition at line 138 of file Random_access_adaptor.h.
 : start(i) {}
Random_access_adaptor (const IC & i, const IC & j) inline
Definition at line 141 of file Random_access_adaptor.h.
                                                    : start(i) {
     // random access index initialized with range [i,j).
     init_index( i, j);
   }
Member Function Documentation
const IC& find (size_type n, std::forward_iterator_tag) const inline
Definition at line 120 of file Random_access_adaptor.h.
Referenced by Random_access_adaptor< Vertex_iterator >::find(), and Random_access_adaptor< Vertex_iterator >::operator[]().
{
     // returns inverse index of k.
     CGAL_assertion( n < index.size());
     return index[n];
   }
const IC& find (size_type n, std::bidirectional_iterator_tag) const inline
Definition at line 125 of file Random_access_adaptor.h.
{
     return find( n, std::forward_iterator_tag());
   }
IC find (size_type n, std::random_access_iterator_tag) const inline
Definition at line 128 of file Random_access_adaptor.h.
{
     return start + n;
   }
IC find (size_type n) const inline
Definition at line 159 of file Random_access_adaptor.h.
{
     // returns inverse index of k.
 #if !defined(CGAL_CFG_NO_ITERATOR_TRAITS) || \
     defined(CGAL_LIMITED_ITERATOR_TRAITS_SUPPORT)
     typedef typename std::iterator_traits<IC>::iterator_category ICC;
     return find( n, ICC());
 #else
     return find( n, std::iterator_category( IC()));
 #endif
   }
void init_index (IC i, const IC & j, std::forward_iterator_tag)
Definition at line 186 of file Random_access_adaptor.h.
References is_empty_range().
Referenced by Random_access_adaptor< Vertex_iterator >::init_index(), and Random_access_adaptor< Vertex_iterator >::Random_access_adaptor().
{
   if ( ! is_empty_range( i, j)) {
     do {
       index.push_back( i);
     } while ((++i) != (j));
   }
 }
void init_index (const IC & i, const IC & j, std::bidirectional_iterator_tag) inline
Definition at line 83 of file Random_access_adaptor.h.
{
     init_index( i, j, std::forward_iterator_tag());
   }
void init_index (const IC & i, const IC & , std::random_access_iterator_tag) inline
Definition at line 87 of file Random_access_adaptor.h.
{
     start = i;
   }
void init_index (const IC & i, const IC & j) inline
Definition at line 91 of file Random_access_adaptor.h.
{
 #if !defined(CGAL_CFG_NO_ITERATOR_TRAITS) || \
     defined(CGAL_LIMITED_ITERATOR_TRAITS_SUPPORT)
     typedef typename std::iterator_traits<IC>::iterator_category ICC;
     init_index( i, j, ICC());
 #else
     init_index( i, j, std::iterator_category( i));
 #endif
   }
IC operator[] (size_type n) const inline
Definition at line 170 of file Random_access_adaptor.h.
Referenced by Random_access_value_adaptor< Vertex_iterator, Vertex >::operator[]().
 { return find(n); }
void push_back (const IC & k, std::forward_iterator_tag) inline
Definition at line 111 of file Random_access_adaptor.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::add_vertex(), and Random_access_adaptor< Vertex_iterator >::push_back().
{
     index.push_back(k);
   }
void push_back (const IC & k, std::bidirectional_iterator_tag) inline
Definition at line 114 of file Random_access_adaptor.h.
{
     push_back( k, std::forward_iterator_tag());
   }
void push_back (const IC & , std::random_access_iterator_tag) inline
Definition at line 117 of file Random_access_adaptor.h.
 {}
void push_back (const IC & k) inline
Definition at line 172 of file Random_access_adaptor.h.
{
     // adds k at the end of the indices.
 #if !defined(CGAL_CFG_NO_ITERATOR_TRAITS) || \
     defined(CGAL_LIMITED_ITERATOR_TRAITS_SUPPORT)
     typedef typename std::iterator_traits<IC>::iterator_category ICC;
     push_back( k, ICC());
 #else
     push_back( k, std::iterator_category( k));
 #endif
   }
void reserve (size_type r, std::forward_iterator_tag) inline
Definition at line 102 of file Random_access_adaptor.h.
Referenced by Polyhedron_incremental_builder_3< HDS >::begin_surface(), and Random_access_adaptor< Vertex_iterator >::reserve().
{
     index.reserve( r);
   }
void reserve (size_type r, std::bidirectional_iterator_tag) inline
Definition at line 105 of file Random_access_adaptor.h.
{
     reserve( r, std::forward_iterator_tag());
   }
void reserve (size_type , std::random_access_iterator_tag) inline
Definition at line 108 of file Random_access_adaptor.h.
 {}
void reserve (size_type r) inline
Definition at line 146 of file Random_access_adaptor.h.
{
     // reserve r entries, if a `vector' is used internally.
 #if !defined(CGAL_CFG_NO_ITERATOR_TRAITS) || \
     defined(CGAL_LIMITED_ITERATOR_TRAITS_SUPPORT)
     typedef typename std::iterator_traits<IC>::iterator_category ICC;
     reserve( r, ICC());
 #else
     reserve( r, std::iterator_category( IC()));
 #endif
   }
Member Data Documentation
Index index protected
Definition at line 76 of file Random_access_adaptor.h.
Referenced by Random_access_adaptor< Vertex_iterator >::find(), Random_access_adaptor< Vertex_iterator >::push_back(), and Random_access_adaptor< Vertex_iterator >::reserve().
IC start protected
Definition at line 77 of file Random_access_adaptor.h.
Referenced by Random_access_adaptor< Vertex_iterator >::find(), and Random_access_adaptor< Vertex_iterator >::init_index().
The documentation for this class was generated from the following file:
Random_access_adaptor.h