Rocstar: CLine Class Reference
CLine Class Reference
#include <GeoPrimitives.H>
Public Member Functions
CLine ()
CLine (const CPoint &p1, const CPoint &p2)
CLine (const CLine &l)
CLine (const CPoint &p1, const CVector &v1)
CLine (const CVector &v1)
CLine & move (const CPoint &p1)
bool operator== (const CLine &l) const
bool has_point (const CPoint &p2) const
CVector & slope ()
const CVector & slope () const
CPoint & point ()
const CPoint & point () const
Protected Attributes
CPoint p
CVector v
Friends
double Distance (const CPoint &p, const CLine &l)
double Distance (const C3Point &p, const CLine &l)
Detailed Description
Definition at line 1002 of file GeoPrimitives.H.
Constructor & Destructor Documentation
CLine () inline
Definition at line 1009 of file GeoPrimitives.H.
     {};
CLine (const CPoint & p1, const CPoint & p2) inline
Definition at line 1011 of file GeoPrimitives.H.
       : p(p1),v(p1,p2)
     {};
CLine (const CLine & l) inline
Definition at line 1014 of file GeoPrimitives.H.
       : p(l.p), v(l.v)
     {};
CLine (const CPoint & p1, const CVector & v1) inline
Definition at line 1017 of file GeoPrimitives.H.
       : p(p1),v(v1)
     {};
CLine (const CVector & v1) inline
Definition at line 1020 of file GeoPrimitives.H.
       : p(0,0,0),v(v1)
     {};
Member Function Documentation
bool has_point (const CPoint & p2) const inline
Definition at line 1033 of file GeoPrimitives.H.
References CVector::normalize(), GeoPrim::TOL, CVector::unit(), and CLine::v.
Referenced by CLineSegment::has_point().
     {
       CVector v2(p2,p);
       v2.normalize();
       double r = v2 * v.unit();
       return( (fabs(r - 1.0) < TOL) ||
               (fabs(r + 1.0) < TOL) );
     };
CLine& move (const CPoint & p1) inline
Definition at line 1023 of file GeoPrimitives.H.
     {
       p = p1;
       return(*this);
     };
bool operator== (const CLine & l) const inline
Definition at line 1028 of file GeoPrimitives.H.
References CLine::p, and CLine::v.
     {
       return( (p == l.p)  &&
               (v == l.v) );
     };
CPoint& point () inline
Definition at line 1049 of file GeoPrimitives.H.
     {
       return(p);
     };
const CPoint& point () const inline
Definition at line 1053 of file GeoPrimitives.H.
     {
       return(p);
     };
CVector& slope () inline
Definition at line 1041 of file GeoPrimitives.H.
References CLine::v.
Referenced by bc_enforce(), and rflu_modextractflowdata::rflu_extractflowdatablasius().
     {
       return(v);
     };
const CVector& slope () const inline
Definition at line 1045 of file GeoPrimitives.H.
References CLine::v.
     {
       return(v);
     };
Friends And Related Function Documentation
double Distance (const CPoint & p, const CLine & l) friend
Definition at line 35 of file GeoPrimitives.C.
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     CPoint p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     CVector v(p,p2);
     return(v.mag());
   }
double Distance (const C3Point & p, const CLine & l) friend
Definition at line 45 of file GeoPrimitives.C.
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     C3Point p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     C3Vector v(p,p2);
     return(v.Mag());
   }
Member Data Documentation
CPoint p protected
Definition at line 1006 of file GeoPrimitives.H.
Referenced by GeoPrim::Distance(), and CLine::operator==().
CVector v protected
Definition at line 1007 of file GeoPrimitives.H.
Referenced by GeoPrim::Distance(), CLine::has_point(), CLine::operator==(), and CLine::slope().
The documentation for this class was generated from the following file:
GeoPrimitives.H