Rocstar: RFC_Pane_overlay Class Reference
RFC_Pane_overlay Class Reference
#include <RFC_Window_overlay.h>
Public Types
typedef RFC_Pane_overlay Self
typedef RFC_Pane_base Base
typedef Vertex_overlay Vertex
typedef Halfedge_overlay Halfedge
typedef Facet_overlay Facet
typedef HDS_overlay HDS
typedef
CGAL::Halfedge_data_structure_decorator
< HDS > HDS_decorator
typedef
CGAL::Polyhedron_incremental_builder_3
< HDS > HDS_builder
Public Types inherited from RFC_Pane_base
typedef RFC_Pane_base Self
typedef COM::Pane Base
typedef COM::Attribute Attribute
typedef Base::Size Size
typedef RFC::Real Real
typedef std::pair< int, int > V2b
Pane id and local boundary id.
typedef std::map< int, V2b > V2b_table
From node id to its corresponding map.
typedef std::vector< int > B2v
From local boundary ids to node ids.
typedef std::map< int, B2v > B2v_table
From pane id to its corresponding mapping.
Public Member Functions
RFC_Pane_overlay (COM::Pane *b, int color)
virtual ~RFC_Pane_overlay ()
RFC_Window_overlay * window ()
const RFC_Window_overlay * window () const
HDS & hds ()
const HDS & hds () const
int get_index (const Vertex *v) const
int get_index (const Halfedge *h) const
int get_index (const Facet *f) const
int get_lid (const Vertex *v) const
int get_lid (const Facet *f) const
Vertex * get_vertex_from_id (int i)
const Vertex * get_vertex_from_id (int i) const
bool is_primary (const Vertex *v) const
const Vertex * get_primary (const Vertex *v) const
Vertex * get_primary (Vertex *v)
const Point_3 & get_point (int id) const
const Point_3 & get_point (const Vertex *v) const
const Halfedge * get_counterpart (const Halfedge *h) const
Halfedge * get_counterpart (Halfedge *h)
bool is_physical_border (const Halfedge *h) const
Determine whether an edge is on the physical boundary of the window.
Vector_3 & get_normal (int v)
const Vector_3 & get_normal (int v) const
void set_normal (int v, const Vector_3 &vec)
Vector_3 & get_normal (Halfedge *h, Vertex *v)
Vector_3 & get_normal (Halfedge *h, int i)
Vector_3 & get_tangent (Halfedge *h, Vertex *v)
const Vector_3 & get_normal (const Halfedge *h, const Vertex *v) const
const Vector_3 & get_normal (const Halfedge *h, int i) const
const Vector_3 & get_tangent (const Halfedge *h, const Vertex *v) const
void add_tangent (Halfedge *h, const Vector_3 &v)
INode * get_inode (const Vertex *v) const
void set_inode (Vertex *v, INode *i)
INode_list & get_inode_list (Halfedge *h)
const INode_list & get_inode_list (const Halfedge *h) const
INode * get_buffered_inode (Halfedge *h, int tag) const
void set_buffered_inode (Halfedge *h, int tag, INode *inode)
void mark (Halfedge *h)
void unmark (Halfedge *h)
bool marked (const Halfedge *h) const
bool is_on_feature (const Vertex *v) const
bool is_feature_0 (const Vertex *v) const
bool is_feature_1 (const Halfedge *h) const
const int & size_of_subfaces () const
int & size_of_subfaces ()
void allocate_subnodes (int num_sn)
Allocate memory space for the arrays for storing the subdivision.
void allocate_subfaces (const std::vector< int > &cnts)
Allocate memory space for the arrays for storing the subdivision.
void insert_subface (int idx, int plid, const int *lids, const Edge_ID *eids, const Point_2 *nc, int rp_id, int cnt, const int *rids)
Insert all the infomation related to a subface into the database.
Public Member Functions inherited from RFC_Pane_base
RFC_Pane_base (Base *b, int color)
A constructor.
void init ()
virtual ~RFC_Pane_base ()
The default destructor.
Base * base ()
The id of its base COM::Pane object.
const Base * base () const
int id () const
bool is_master () const
Is this pane a master copy?
bool is_replicate () const
Is this pane not a master copy?
bool is_quadratic () const
Does this pane contain quadratic elements?
bool is_border_node (int i) const
Is a give node on the boundary of the pane?
bool is_isolated_node (int i) const
Is a give node an isolated node not belong to any element?
bool coincident (int i, int j) const
Report whether the two given nodes are coincident.
int size_of_nodes () const
The total number of nodes in the pane.
int size_of_faces () const
The total number of faces in the pane.
int size_of_isolated_nodes () const
int size_of_border_nodes () const
Edge_ID get_edge_id (const int face_lid, const int vertex_lid) const
Get the edge id within a given face.
int size_of_subnodes () const
The total number of nodes in the subdivision of the pane.
int size_of_subfaces () const
The total number of faces in the subdivision of the pane.
Real * pointer (int i)
Get the address of a given attribute with id i.
const Real * pointer (int i) const
bool is_primary_node (const int vid) const
Is the node with given local id a primary one?
int size_of_primary_nodes () const
Get total number of primary nodes contained in the pane.
const Point_3 & get_point (int id) const
Get the physical coordinates of the node with given local id.
const Point_3 & get_point (int id, int) const
const Real * coordinates () const
Point_3 get_point_of_subnode (int id) const
Bbox_3 get_bounding_box () const
Get the bounding box of the pane.
int color () const
The color of the parent window (BLUE or GREEN).
int parent_type_of_subnode (int) const
Determine the parent type of a subnode of given tyep.
int get_parent_node (int) const
Get the local parent node id of a given subnode.
int get_parent_face (int id) const
Get the local parent face id of a given subface.
template<class Point >
void normalize_nat_coor (int idx, int e, Point &nc) const
void get_host_element_of_subnode (int i, Element_node_enumerator &ene, Point_2 &nc) const
void get_host_element_of_subface (int i, Element_node_enumerator &ene) const
void get_nat_coor_in_element (const int eid, const int lid, Point_2 &nc) const
Take a subface id and a local subnode id, return the natual coordinates of the subnode within the parent element.
void get_nat_coor_in_element (const int sn_id, Element_node_enumerator &ene, Point_2 &nc) const
Take a subnode id and an element, return the natrual coordinates within the element.
std::pair< const
COM::Connectivity *, int > get_element (int face_id) const
Get the connectivity object and the id within the connectivity object for a given element.
const Node_ID & get_subnode_counterpart (int i) const
const Face_ID & get_subface_counterpart (int i) const
int get_lvid (const Element_node_enumerator &ene, const int v) const
Protected Member Functions
void build_hds ()
void evaluate_normals ()
void determine_counterparts ()
void unmark_alledges ()
void mark_ridge (Halfedge *h)
const float & get_cos_face_angle (const Halfedge *h) const
float & get_cos_face_angle (Halfedge *h)
void init_face_angle ()
const float & get_angle_defect (const Vertex *v) const
float & get_angle_defect (Vertex *v)
void init_angle_defect ()
const float & get_cos_edge_angle (const Vertex *v) const
float & get_cos_edge_angle (Vertex *v)
void reset_cos_edge_angle (Vertex *v)
void init_edge_angle ()
void set_strong_edge (Halfedge *h)
void unset_strong_edge (Halfedge *h)
void set_feature_0 (Vertex *v)
void unset_feature_0 (Vertex *v)
void set_on_feature (Vertex *v)
void unset_on_feature (Vertex *v)
void create_overlay_data ()
void delete_overlay_data ()
void construct_bvpair2edge ()
int get_border_index (const Halfedge *h) const
Protected Member Functions inherited from RFC_Pane_base
void comp_nat_coors ()
Compute the natural coordinates.
void build_v2b_from_b2v (const RFC_Window_base *w)
Build pane connectivity.
void write_tec_ij (std::ostream &, const COM::Attribute *a=0) const
void write_tec_tri (std::ostream &, const COM::Connectivity &, const COM::Attribute *a=0) const
void write_tec_mixed (std::ostream &, const std::vector< const COM::Connectivity * > &, const COM::Attribute *a=0) const
void write_tec_sub (std::ostream &) const
void write_tec_ascii (std::ostream &os, const COM::Attribute *attr=0) const
void write_binary (std::ostream &os) const
void read_binary (std::istream &is, std::vector< int > *b2v_all=NULL, COM::Pane *p=NULL)
void register_sdv_attributes (const std::string &wname) const
void read_rocin (const std::string &sdv_wname, const std::string &parent_wname="", COM::Pane *p=NULL)
Read in using Rocin.
Protected Attributes
HDS _hds
RFC_Window_overlay * _window
std::map< std::pair< int, int >
, Halfedge * > _bv2edges
std::vector< Halfedge * > _cntrs
std::vector< Vertex * > _primaries
std::vector< Vector_3 > _nrmls
std::vector< Vector_3 > _f_nrmls
std::vector< int > _f_n_index
std::vector< Vector_3 > _f_tngts
std::vector< int > _f_t_index
std::vector< float > _ad_0
std::vector< float > _ea_0
std::vector< float > _fd_1
std::vector< bool > _is_f_0
std::vector< bool > _is_on_f
std::vector< bool > _is_f_1
std::vector< INode * > _v_nodes
std::vector< INode * > _e_node_buf
std::vector< INode_list > _e_node_list
std::vector< int > _e_marks
int _size_of_subfaces
std::vector< const INode * > _subnodes
Protected Attributes inherited from RFC_Pane_base
Base * _base
Reference to its base object.
bool _is_master
Is the pane a master copy?
bool _quadratic
Does it contain quadratic elements?
std::vector< bool > _is_border
Is a node on border?
std::vector< bool > _is_isolated
Is a node isolated?
int _n_border
int _n_isolated
V2b_table _v2b_table
B2v_table _b2v_table
std::vector< Edge_ID > _subnode_parents
Edge ids of parents.
std::vector< Point_2S > _subnode_nat_coors
Natual coordinates in the parent face.
std::vector< Point_2S > _subnode_normalized_nc
Natual coordinates in the parent face.
std::vector< int > _subnode_subID
Sub-node ID of nodes in the pane.
std::vector< Node_ID > _subnode_counterparts
Ids of counterparts of subnodes.
std::vector< Three_tuple< int > > _subfaces
std::vector< int > _subface_parents
Face ids of the parents of the subfaces.
std::vector< int > _subface_offsets
Offsets of first subfaces contained in a face.
std::vector< Face_ID > _subface_counterparts
Ids of counterparts of faces.
std::vector< Three_tuple
< Point_2S > > _subface_nat_coors
Element connectivity of the subfaces.
Static Protected Attributes
static HDS_accessor< Tag_true > acc
Friends
class RFC_Window_overlay
Detailed Description
Definition at line 58 of file RFC_Window_overlay.h.
Member Typedef Documentation
typedef RFC_Pane_base Base
Definition at line 61 of file RFC_Window_overlay.h.
typedef Facet_overlay Facet
Definition at line 64 of file RFC_Window_overlay.h.
typedef Halfedge_overlay Halfedge
Definition at line 63 of file RFC_Window_overlay.h.
typedef HDS_overlay HDS
Definition at line 65 of file RFC_Window_overlay.h.
typedef CGAL::Polyhedron_incremental_builder_3<HDS> HDS_builder
Definition at line 67 of file RFC_Window_overlay.h.
typedef CGAL::Halfedge_data_structure_decorator< HDS> HDS_decorator
Definition at line 66 of file RFC_Window_overlay.h.
typedef RFC_Pane_overlay Self
Definition at line 60 of file RFC_Window_overlay.h.
typedef Vertex_overlay Vertex
Definition at line 62 of file RFC_Window_overlay.h.
Constructor & Destructor Documentation
RFC_Pane_overlay (COM::Pane * b, int color)
Definition at line 64 of file RFC_Window_overlay.C.
   : Base(b, color), _hds( this) {}
virtual ~RFC_Pane_overlay () inline virtual
Definition at line 72 of file RFC_Window_overlay.h.
 {}
Member Function Documentation
void add_tangent (Halfedge * h, const Vector_3 & v) inline
Definition at line 159 of file RFC_Window_overlay.h.
References _f_t_index, _f_tngts, get_index(), and v.
Referenced by RFC_Window_overlay::evaluate_normals().
{
     int &ind = _f_t_index[ get_index(h)];
     if ( ind < 0) { ind = _f_tngts.size(); _f_tngts.push_back( v); }
     else _f_tngts[ind] += v;
   }
void allocate_subfaces (const std::vector< int > & cnts) inline
Allocate memory space for the arrays for storing the subdivision.
Definition at line 206 of file RFC_Window_overlay.h.
References RFC_Pane_base::_subface_counterparts, RFC_Pane_base::_subface_offsets, RFC_Pane_base::_subface_parents, RFC_Pane_base::_subfaces, i, RFC_assertion, and RFC_Pane_base::size_of_faces().
Referenced by Overlay::number_subfaces().
{
     int nf = size_of_faces();  RFC_assertion( nf == int(cnts.size()));
     _subface_offsets.resize( nf+1);
     _subface_offsets[0] = 0;
     for ( int i=1; i<=nf; ++i) {
       _subface_offsets[i] = _subface_offsets[i-1]+cnts[i-1];
     }
     int nsf=_subface_offsets[nf];
     _subfaces.resize( nsf);
     _subface_parents.resize( nsf);
     _subface_counterparts.resize( nsf);
   }
void allocate_subnodes (int num_sn) inline
Allocate memory space for the arrays for storing the subdivision.
Definition at line 199 of file RFC_Window_overlay.h.
References RFC_Pane_base::_subnode_counterparts, RFC_Pane_base::_subnode_nat_coors, and RFC_Pane_base::_subnode_parents.
{
     _subnode_parents.resize( num_sn);
     _subnode_nat_coors.resize( num_sn);
     _subnode_counterparts.resize( num_sn);
   }
void build_hds () protected
Definition at line 130 of file RFC_Window_overlay.C.
References RFC_Pane_base::_base, _hds, RFC_Pane_base::_quadratic, get_vertex_from_id(), Facet_overlay::halfedge(), i, k, Halfedge_overlay::next(), HDS_overlay::normalize_border_vertices(), RFC_assertion, Vertex_overlay::set_halfedge(), RFC_Pane_base::size_of_nodes(), and v.
{
   RFC_assertion( _base);
   if ( _base->size_of_nodes() == 0) return;
   HDS_builder  B(_hds,true);
   B.begin_surface( _base->size_of_nodes(), _base->size_of_elements());
   // insert the vertices
   for (Size i=0; i<_base->size_of_nodes(); ++i)
   { B.add_vertex( Vertex::Point()); }
   Element_node_enumerator ene( _base, 1);
   for (int i=_base->size_of_elements(); i>0; --i, ene.next()) {
     B.begin_facet();
     for ( int k=0, ne=ene.size_of_edges(); k<ne; ++k) {
       B.add_vertex_to_facet( ene[k]-1);
     }
     B.end_facet();
   }
   B.end_surface();
   // Normalize border vertices such that every border vertex point to its
   // incident border halfedge.
   _hds.normalize_border_vertices();
   // Insert the vertices in edge/face centers for quadratic elements
   if ( _quadratic) {
     Facet *fs = &*_hds.facets_begin();
     Element_node_enumerator ene( _base, 1);
     for (int i=_base->size_of_elements(); i>0; --i, ene.next(), ++fs) {
       int nn = ene.size_of_nodes();
       int ne = ene.size_of_edges();
       Halfedge *h = fs->halfedge();
       for ( int k=ne; k<ne+ne; ++k) {
         Vertex *v = get_vertex_from_id( ene[k]);
         v->set_halfedge( h);
         h = h->next();
       }
       if ( nn == 9) {
         Vertex *v = get_vertex_from_id( ene[8]);
         v->set_halfedge( fs->halfedge());
       }
     }
   }
 }
void construct_bvpair2edge () protected
Definition at line 470 of file RFC_Window_overlay.C.
References _bv2edges, get_lid(), hds(), and RFC_assertion.
{
   HDS_overlay::Halfedge_iterator hit = hds().border_halfedges_begin();
   HDS_overlay::Halfedge_iterator hend = hds().halfedges_end();
   for ( ; hit != hend; ++ ++hit) {
     RFC_assertion( !hit->is_border());
     _bv2edges[ make_pair( get_lid( hit->origin()),
                                get_lid( hit->destination()))] = &*hit;
   }
 }
void create_overlay_data () protected
Definition at line 507 of file RFC_Window_overlay.C.
References _e_marks, _e_node_buf, _e_node_list, _hds, _v_nodes, and RFC_Pane_base::color().
Referenced by RFC_Window_overlay::create_overlay_data().
{
   _v_nodes.resize(0);
   _e_node_list.resize(0);
   _e_node_buf.resize(0);
   _e_marks.resize(0);
   _v_nodes.resize( _hds.size_of_vertices(),0);
   _e_node_list.resize( _hds.size_of_halfedges(), INode_list( color()));
   _e_node_buf.resize( _hds.size_of_halfedges(), 0);
   _e_marks.resize( _hds.size_of_halfedges(), 0);
 }
void delete_overlay_data () protected
Definition at line 520 of file RFC_Window_overlay.C.
References _ad_0, _cntrs, _e_marks, _e_node_buf, _e_node_list, _ea_0, _f_n_index, _f_nrmls, _f_t_index, _f_tngts, _fd_1, _primaries, _v_nodes, and free_vector().
Referenced by RFC_Window_overlay::delete_overlay_data().
{
   free_vector( _v_nodes);
   free_vector( _e_node_list);
   free_vector( _e_node_buf);
   free_vector( _e_marks);
   free_vector( _cntrs); free_vector( _primaries);
   free_vector( _f_nrmls); free_vector( _f_tngts);
   free_vector( _f_n_index); free_vector( _f_t_index);
   free_vector( _ad_0); free_vector( _ea_0); free_vector( _fd_1);
 }
void determine_counterparts () protected
Definition at line 370 of file RFC_Window_overlay.C.
References RFC_Pane_base::_b2v_table, _bv2edges, _cntrs, _primaries, _window, get_border_index(), get_lid(), RFC_Window_derived< _Pane >::get_primary(), hds(), i, RFC_Pane_base::id(), iend, RFC_Window_base::name(), RFC_Window_derived< _Pane >::pane(), RFC_assertion, swap(), and v.
{
   typedef set< pair<int,int> >      V2h;
   typedef map<int, V2h>                  V2h_table;
   V2h_table  _v2h_table;
   //`Loop through the B2v_table
   for ( B2v_table::iterator
           it=_b2v_table.begin(), iend=_b2v_table.end(); it != iend; ++it) {
     for ( int i=0, size=it->second.size(); i<size; ++i) {
       pair<int,int> p(it->first, i);
       if ( it->first==id()) {
         if ( i&1) --p.second; else ++p.second;
       }
       _v2h_table[it->second[i]].insert( p);
     }
   }
   _cntrs.resize( hds().size_of_border_edges(), NULL);
   // Loop through all border edges.
   HDS_overlay::Halfedge_iterator hit = hds().border_halfedges_begin();
   HDS_overlay::Halfedge_iterator hend = hds().halfedges_end();
   for ( ; hit != hend; ++hit) {
     ++hit; RFC_assertion( hit->is_border());
     Vertex *v = hit->vertex();
     V2h_table::iterator it = _v2h_table.find( get_lid(v));
     if ( it == _v2h_table.end()) continue;
     V2h_table::iterator i0=_v2h_table.find(get_lid( hit->origin()));
     // If the origin not incident with any, there is no counterpart.
     if ( i0==_v2h_table.end()) continue;
     // check whether the two vertices are overlapping.
     V2h::iterator j0=i0->second.begin(), j1=it->second.begin();
     while ( j0 != i0->second.end() && j1 != it->second.end()) {
       if ( j0->first == j1->first) {
         bool found=false;
         V2h::iterator k0, k1;
         for ( k0=j0; k0!=i0->second.end()&&k0->first==j0->first; ++k0) {
           if (found) continue;
           for ( k1=j1; k1!=it->second.end()&&k1->first==j1->first; ++k1) {
             if (found) continue;
             // Check whether it is an edge in that pane
             const RFC_Pane_overlay &p = _window->pane(k0->first);
             const B2v  &b2v = p._b2v_table.find(id())->second;
             pair<int,int> e( b2v[k0->second], b2v[k1->second]);
             RFC_assertion( e.first>0 && e.second>0);
             map< pair<int,int>, Halfedge*>::const_iterator
               b2e_it = p._bv2edges.find( e);
             if ( b2e_it != p._bv2edges.end()) {
               _cntrs[get_border_index(&*hit)] = b2e_it->second;
               found=true;
             }
             else if ( k0->first != id()) {
               swap( e.first, e.second);
               if (p._bv2edges.find( e) != p._bv2edges.end()) {
                 std::cerr << "ERROR: Inconsistency in window \""
                           << _window->name() << "\"!!!! \n\tPanes " << id()
                           << " and " << j0->first
                           << " have opposite orientation!" << std::endl
                           << "\tComputation can not continue. Aborting..."
                           << std::endl;
                 RFC_assertion( p._bv2edges.find( e) == p._bv2edges.end());
                 abort();
               }
             }
           }
         }
         if ( found) { j0 = k0; j1 = k1; }
         else { ++j0; ++j1; }
       }
       else
         if ( j0->first < j1->first) ++j0; else ++j1;
     }
   }
   // Fix physical border ones to have them point to themselves
   hit = hds().border_halfedges_begin();
   for ( vector<Halfedge*>::iterator it=_cntrs.begin(), iend=_cntrs.end();
         it!=iend; ++it, ++hit) {
     ++hit; RFC_assertion( hit->is_border());
     if ( *it == NULL) *it = &*hit;
   }
   // Determine the primaries of the border vertices
   _primaries.resize( hds().size_of_border_edges(), NULL);
   hit = hds().border_halfedges_begin();
   for ( vector<Vertex*>::iterator it=_primaries.begin();
         it != _primaries.end(); ++it, ++hit) {
     ++hit; RFC_assertion( hit->is_border());
     pair<Self*,int>
       t=_window->get_primary( this, get_lid( hit->destination()));
     *it = t.first->get_vertex_from_id( t.second);
   }
 }
void evaluate_normals () protected
Definition at line 183 of file RFC_Window_overlay.C.
References _hds, _nrmls, Halfedge_overlay::destination(), Overlay_primitives::get_face_normal(), Vertex_overlay::halfedge(), i, iend, RFC_assertion, scheme, set_normal(), and v.
{
   _nrmls.resize( _hds.size_of_vertices(), Vector_3(0.,0.,0.));
   int vid=1;
   for ( HDS::Vertex_iterator it=_hds.vertices_begin(),
           iend=_hds.vertices_end(); it != iend; ++it, ++vid) {
     Vertex *v = &*it;
     Vector_3 d(0.,0.,0.);
     Halfedge *h = v->halfedge(), *i = h;
     if (!h || h->destination() != v) continue;
     do {
       RFC_assertion( i->destination() == v);
       if ( !i->is_border()) {
         d += Overlay_primitives().get_face_normal( i, Point_2(0,0), scheme);
       }
     } while ( ( i = i->next()->opposite()) != h);
     // Note that the normal vector is not normalized.
     set_normal( vid, d);
   }
 }
const float& get_angle_defect (const Vertex * v) const inline protected
Definition at line 251 of file RFC_Window_overlay.h.
References _ad_0, and get_index().
Referenced by RFC_Window_overlay::comp_angle_defect(), and RFC_Window_overlay::print_features().
   { return _ad_0[ get_index( v)]; }
float& get_angle_defect (Vertex * v) inline protected
Definition at line 253 of file RFC_Window_overlay.h.
References _ad_0, and get_index().
   { return _ad_0[ get_index( v)]; }
int get_border_index (const Halfedge * h) const inline protected
Definition at line 279 of file RFC_Window_overlay.h.
References hds(), i, and RFC_assertion.
Referenced by determine_counterparts(), get_counterpart(), get_primary(), is_physical_border(), and is_primary().
{
     const Halfedge *t = &*hds().border_halfedges_begin();
     int i = h - t; RFC_assertion(i>=0 && (i&1)==1);
     return i>>1;
   }
INode* get_buffered_inode (Halfedge * h, int tag) const inline
Definition at line 174 of file RFC_Window_overlay.h.
References _e_marks, _e_node_buf, get_index(), and i.
Referenced by HDS_accessor< Tag_true >::get_buffered_inode().
{
     int i=get_index(h);
     if ( _e_marks[i] == tag) return _e_node_buf[i];
     else return NULL;
   }
const float& get_cos_edge_angle (const Vertex * v) const inline protected
Definition at line 258 of file RFC_Window_overlay.h.
References _ea_0, and get_index().
Referenced by RFC_Window_overlay::cos_edge_angle(), and RFC_Window_overlay::print_features().
   { return _ea_0[ get_index( v)]; }
float& get_cos_edge_angle (Vertex * v) inline protected
Definition at line 260 of file RFC_Window_overlay.h.
References _ea_0, and get_index().
   { return _ea_0[ get_index( v)]; }
const float& get_cos_face_angle (const Halfedge * h) const inline protected
Definition at line 244 of file RFC_Window_overlay.h.
References _fd_1, and get_index().
Referenced by RFC_Window_overlay::cos_face_angle().
   { return _fd_1[ get_index( h)>>1]; }
float& get_cos_face_angle (Halfedge * h) inline protected
Definition at line 246 of file RFC_Window_overlay.h.
References _fd_1, and get_index().
   { return _fd_1[ get_index( h)>>1]; }
const Halfedge* get_counterpart (const Halfedge * h) const inline
Definition at line 120 of file RFC_Window_overlay.h.
References _cntrs, get_border_index(), Halfedge_overlay::is_border(), Vertex_overlay::pane(), RFC_assertion, and Halfedge_overlay::vertex().
Referenced by get_counterpart(), and HDS_accessor< Tag_true >::get_counterpart().
{
     if ( !h->is_border()) return h;
     RFC_assertion( h->vertex()->pane()==this);
     return _cntrs[get_border_index(h)];
   }
Halfedge* get_counterpart (Halfedge * h) inline
Definition at line 126 of file RFC_Window_overlay.h.
References get_counterpart().
   { return const_cast<Halfedge*>( get_counterpart( (const Halfedge*)h)); }
int get_index (const Vertex * v) const inline
Definition at line 81 of file RFC_Window_overlay.h.
References _hds.
Referenced by add_tangent(), RFC_Window_overlay::evaluate_normals(), get_angle_defect(), get_buffered_inode(), get_cos_edge_angle(), get_cos_face_angle(), get_inode(), get_inode_list(), get_normal(), get_point(), get_tangent(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), is_feature_0(), is_feature_1(), is_on_feature(), mark(), marked(), Overlay::match_features_0(), Overlay::number_subfaces(), RFC_Window_overlay::remove_feature_1(), reset_cos_edge_angle(), set_buffered_inode(), set_feature_0(), set_inode(), set_on_feature(), set_strong_edge(), unmark(), unset_feature_0(), unset_on_feature(), and unset_strong_edge().
   { return v - (const Vertex*)&*_hds.vertices_begin(); }
int get_index (const Halfedge * h) const inline
Definition at line 83 of file RFC_Window_overlay.h.
References _hds.
   { return h - (const Halfedge*)&*_hds.halfedges_begin(); }
int get_index (const Facet * f) const inline
Definition at line 85 of file RFC_Window_overlay.h.
References _hds.
   { return f - (const Facet*)&*_hds.facets_begin(); }
INode* get_inode (const Vertex * v) const inline
Definition at line 165 of file RFC_Window_overlay.h.
References _v_nodes, get_index(), is_primary(), and RFC_assertion.
Referenced by HDS_accessor< Tag_true >::get_inode().
   { RFC_assertion( is_primary(v)); return _v_nodes[ get_index(v)]; }
INode_list& get_inode_list (Halfedge * h) inline
Definition at line 169 of file RFC_Window_overlay.h.
References _e_node_list, and get_index().
Referenced by HDS_accessor< Tag_true >::get_inode_list().
   { return _e_node_list[ get_index(h)]; }
const INode_list& get_inode_list (const Halfedge * h) const inline
Definition at line 171 of file RFC_Window_overlay.h.
References _e_node_list, and get_index().
   { return _e_node_list[ get_index(h)]; }
int get_lid (const Vertex * v) const inline
Definition at line 88 of file RFC_Window_overlay.h.
References _hds.
Referenced by construct_bvpair2edge(), Overlay::convert_nat_coordinates(), determine_counterparts(), Overlay::number_subfaces(), and Vertex_set::Vertex_set().
   { return v - (const Vertex*)&*_hds.vertices_begin() + 1; }
int get_lid (const Facet * f) const inline
Definition at line 90 of file RFC_Window_overlay.h.
References _hds.
   { return f - (const Facet*)&*_hds.facets_begin() + 1; }
Vector_3& get_normal (int v) inline
Definition at line 141 of file RFC_Window_overlay.h.
References _nrmls, and RFC_assertion.
Referenced by Overlay::get_green_parent(), get_normal(), HDS_accessor< Tag_true >::get_normal(), Normal_set::operator[](), Overlay::project_adjacent_green_vertices(), and Overlay::project_next_vertex().
   { RFC_assertion(v>0); return _nrmls[v-1]; }
const Vector_3& get_normal (int v) const inline
Definition at line 143 of file RFC_Window_overlay.h.
References _nrmls, and RFC_assertion.
   { RFC_assertion(v>0); return _nrmls[v-1]; }
Vector_3 & get_normal (Halfedge * h, Vertex * v)
Definition at line 358 of file RFC_Window_overlay.C.
References get_normal().
{
   return const_cast< Vector_3&>(get_normal( h, (const Vertex*)(v)));
 }
Vector_3& get_normal (Halfedge * h, int i) inline
Definition at line 150 of file RFC_Window_overlay.h.
References get_normal(), and get_vertex_from_id().
   { return get_normal( h, get_vertex_from_id(i)); }
const Vector_3 & get_normal (const Halfedge * h, const Vertex * v) const
Definition at line 323 of file RFC_Window_overlay.C.
References _f_n_index, _f_nrmls, _nrmls, acc, Halfedge_overlay::destination(), get_index(), HDS_accessor< _MP >::get_pane(), HDS_accessor< _MP >::get_prev_around_destination(), Halfedge_overlay::is_border(), j, Halfedge_overlay::prev(), and RFC_assertion.
{
   RFC_assertion( acc.get_pane(h) == this && acc.get_pane(v)==this);
   if ( v != h->destination()) {
     h = h->prev();
     RFC_assertion( v == h->destination());
   }
   if ( h->is_border())
     h = acc.get_prev_around_destination( h);
   int j=_f_n_index[get_index( h)];
   if ( j < 0)
     return _nrmls[ get_index(v)];
   else
     return _f_nrmls[j];
 }
const Vector_3& get_normal (const Halfedge * h, int i) const inline
Definition at line 155 of file RFC_Window_overlay.h.
References get_normal(), and get_vertex_from_id().
   { return get_normal( h, get_vertex_from_id(i)); }
const Point_3& get_point (int id) const inline
Definition at line 115 of file RFC_Window_overlay.h.
References RFC_Pane_base::get_point().
Referenced by Overlay::get_green_parent(), Point_set::operator[](), and Overlay::overlay_init().
   { return Base::get_point(id); }
const Point_3& get_point (const Vertex * v) const inline
Definition at line 117 of file RFC_Window_overlay.h.
References get_index(), and RFC_Pane_base::get_point().
   { return Base::get_point( get_index(v),0); }
const Vertex* get_primary (const Vertex * v) const inline
Definition at line 106 of file RFC_Window_overlay.h.
References _primaries, get_border_index(), Vertex_overlay::halfedge(), Halfedge_overlay::is_border(), and RFC_assertion.
Referenced by get_primary(), HDS_accessor< Tag_true >::get_primary(), and RFC_Window_overlay::is_same_node().
{
     RFC_assertion( v->halfedge());
     // Precondition: v is a border vertex and v is not an isolated node
     if ( !v->halfedge()->is_border()) return v;
     else return _primaries[get_border_index(v->halfedge())];
   }
Vertex* get_primary (Vertex * v) inline
Definition at line 112 of file RFC_Window_overlay.h.
References get_primary().
   { return const_cast<Vertex*>( get_primary( (const Vertex*)v)); }
Vector_3 & get_tangent (Halfedge * h, Vertex * v)
Definition at line 364 of file RFC_Window_overlay.C.
Referenced by get_tangent(), and Overlay::project_next_vertex().
{
   return const_cast< Vector_3&>(get_tangent( h, (const Vertex*)(v)));
 }
const Vector_3 & get_tangent (const Halfedge * h, const Vertex * v) const
Definition at line 344 of file RFC_Window_overlay.C.
References _f_t_index, _f_tngts, acc, Halfedge_overlay::destination(), get_index(), HDS_accessor< _MP >::get_opposite(), HDS_accessor< _MP >::get_pane(), get_tangent(), is_feature_1(), j, and RFC_assertion.
{
   if ( v != h->destination()) {
     h = acc.get_opposite(h);
     return acc.get_pane( h)->get_tangent( h, h->destination());
   }
   RFC_assertion( is_feature_1(h));
   int j=_f_t_index[get_index( h)];
   RFC_assertion( j >= 0 && int(_f_tngts.size())>j);
   return _f_tngts[j];
 }
Vertex* get_vertex_from_id (int i) inline
Definition at line 93 of file RFC_Window_overlay.h.
References _hds, and RFC_assertion.
Referenced by build_hds(), and get_normal().
   { RFC_assertion(i>0); return &_hds.vertices_begin()[ i-1]; }
const Vertex* get_vertex_from_id (int i) const inline
Definition at line 95 of file RFC_Window_overlay.h.
References _hds, and RFC_assertion.
   { RFC_assertion(i>0); return &_hds.vertices_begin()[ i-1]; }
HDS& hds () inline
Definition at line 77 of file RFC_Window_overlay.h.
References _hds.
Referenced by construct_bvpair2edge(), RFC_Window_overlay::detect_features(), determine_counterparts(), RFC_Window_overlay::evaluate_normals(), get_border_index(), Overlay::get_green_parent(), HDS_accessor< Tag_true >::get_hds(), Overlay::number_subfaces(), RFC_Window_overlay::print_features(), and RFC_Window_overlay::reduce_coordinates_to_all().
 { return _hds; }
const HDS& hds () const inline
Definition at line 78 of file RFC_Window_overlay.h.
References _hds.
 { return _hds; }
void init_angle_defect () inline protected
Definition at line 255 of file RFC_Window_overlay.h.
References _ad_0, _hds, and HUGE_VALF.
Referenced by RFC_Window_overlay::detect_features().
   { _ad_0.clear(); _ad_0.resize( _hds.size_of_vertices(), HUGE_VALF); }
void init_edge_angle () inline protected
Definition at line 264 of file RFC_Window_overlay.h.
References _ea_0, _hds, and HUGE_VALF.
Referenced by RFC_Window_overlay::detect_features().
   { _ea_0.clear(); _ea_0.resize( _hds.size_of_vertices(), HUGE_VALF); }
void init_face_angle () inline protected
Definition at line 248 of file RFC_Window_overlay.h.
References _fd_1, _hds, and HUGE_VALF.
Referenced by RFC_Window_overlay::detect_features().
   { _fd_1.clear(); _fd_1.resize( _hds.size_of_halfedges()>>1, HUGE_VALF); }
void insert_subface (int idx, int plid, const int * lids, const Edge_ID * eids, const Point_2 * nc, int rp_id, int cnt, const int * rids)
Insert all the infomation related to a subface into the database.
Parameters
idx the index of the subface (i.e., starting from 0).
plid the local id of the parent face of the subface.
h an halfedge of the its parent face in the pane.
lids the local ids of the nodes of the subface.
nc the local coordinates of the nodes of the subface within its parent face.
rp_id the pane id of the correponding subface in the other window.
cnt the local id of the subface's counterpart in the other window.
rids the local ids of the nodes of the correponding subface in the other window.
Definition at line 564 of file RFC_Window_overlay.C.
References RFC_Pane_base::_subface_counterparts, RFC_Pane_base::_subface_parents, RFC_Pane_base::_subfaces, RFC_Pane_base::_subnode_counterparts, RFC_Pane_base::_subnode_nat_coors, RFC_Pane_base::_subnode_parents, i, and RFC_assertion.
Referenced by Overlay::number_subfaces().
{
   RFC_assertion( idx>=0 && idx<int(_subface_parents.size()) && cnt>=1);
   for ( int i=0; i<3; ++i) {
     _subfaces[idx][i] = lids[i];
     _subnode_parents[ lids[i]-1] = eids[i];
     _subnode_nat_coors[ lids[i]-1] = Point_2S(nc[i][0],nc[i][1]);
     _subnode_counterparts[ lids[i]-1] = Node_ID( rp_id, rids[i]);
   }
   _subface_parents[idx] = plid;
   _subface_counterparts[idx] = Face_ID( rp_id, cnt);
 }
bool is_feature_0 (const Vertex * v) const inline
Definition at line 190 of file RFC_Window_overlay.h.
References _is_f_0, and get_index().
Referenced by HDS_accessor< Tag_true >::is_feature_0(), and RFC_Window_overlay::is_feature_0().
 { return _is_f_0[ get_index(v)]; }
bool is_feature_1 (const Halfedge * h) const inline
Definition at line 191 of file RFC_Window_overlay.h.
References _is_f_1, and get_index().
Referenced by get_tangent(), Overlay::intersect_blue_with_green(), HDS_accessor< Tag_true >::is_feature_1(), RFC_Window_overlay::is_feature_1(), Overlay_primitives::snap_blue_ridge_edge(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return _is_f_1[get_index(h)]; }
bool is_on_feature (const Vertex * v) const inline
Definition at line 189 of file RFC_Window_overlay.h.
References _is_on_f, and get_index().
Referenced by RFC_Window_overlay::get_an_unmarked_halfedge(), HDS_accessor< Tag_true >::is_on_feature(), and RFC_Window_overlay::is_on_feature().
 { return _is_on_f[ get_index(v)]; }
bool is_physical_border (const Halfedge * h) const inline
Determine whether an edge is on the physical boundary of the window.
A edge is on a physical boundary if it is on the pane boundary and it does not have a counterpart in any other pane.
Definition at line 133 of file RFC_Window_overlay.h.
References _cntrs, get_border_index(), Halfedge_overlay::is_border(), Vertex_overlay::pane(), RFC_assertion, and Halfedge_overlay::vertex().
Referenced by HDS_accessor< Tag_true >::is_border().
{
     if ( !h->is_border()) return false;
     RFC_assertion( h->vertex()->pane()==this);
     return _cntrs[ get_border_index(h)] == h;
   }
bool is_primary (const Vertex * v) const inline
Definition at line 100 of file RFC_Window_overlay.h.
References _primaries, get_border_index(), Vertex_overlay::halfedge(), and Halfedge_overlay::is_border().
Referenced by get_inode(), HDS_accessor< Tag_true >::is_primary(), and set_inode().
{
     return !v->halfedge()->is_border() ||
       _primaries[get_border_index(v->halfedge())]==v;
   }
void mark (Halfedge * h) inline
Definition at line 185 of file RFC_Window_overlay.h.
References _e_marks, and get_index().
Referenced by HDS_accessor< Tag_true >::mark().
 { _e_marks[get_index(h)] = true; }
void mark_ridge (Halfedge * h) protected
bool marked (const Halfedge * h) const inline
Definition at line 187 of file RFC_Window_overlay.h.
References _e_marks, and get_index().
Referenced by RFC_Window_overlay::get_an_unmarked_halfedge(), and HDS_accessor< Tag_true >::marked().
 { return _e_marks[get_index(h)]; }
void reset_cos_edge_angle (Vertex * v) inline protected
Definition at line 262 of file RFC_Window_overlay.h.
References _ea_0, get_index(), and HUGE_VALF.
   { _ea_0[ get_index( v)] = HUGE_VALF; }
void set_buffered_inode (Halfedge * h, int tag, INode * inode) inline
Definition at line 179 of file RFC_Window_overlay.h.
References _e_marks, _e_node_buf, get_index(), i, and inode.
Referenced by HDS_accessor< Tag_true >::set_buffered_inode().
{
     int i=get_index(h);
     _e_marks[i] = tag;
     _e_node_buf[i] = inode;
   }
void set_feature_0 (Vertex * v) inline protected
Definition at line 269 of file RFC_Window_overlay.h.
References _is_f_0, and get_index().
Referenced by RFC_Window_overlay::identify_features_0(), and RFC_Window_overlay::set_feature_0().
 { _is_f_0[ get_index(v)] = true; }
void set_inode (Vertex * v, INode * i) inline
Definition at line 167 of file RFC_Window_overlay.h.
References _v_nodes, get_index(), i, is_primary(), and RFC_assertion.
Referenced by HDS_accessor< Tag_true >::set_inode().
   { RFC_assertion( is_primary(v)); _v_nodes[ get_index(v)] = i; }
void set_normal (int v, const Vector_3 & vec) inline
Definition at line 145 of file RFC_Window_overlay.h.
References _nrmls, and RFC_assertion.
Referenced by evaluate_normals().
   { RFC_assertion(v>0); _nrmls[v-1] = vec; }
void set_on_feature (Vertex * v) inline protected
Definition at line 271 of file RFC_Window_overlay.h.
References _is_on_f, and get_index().
Referenced by RFC_Window_overlay::set_on_feature().
 { _is_on_f[ get_index(v)] = true; }
void set_strong_edge (Halfedge * h) inline protected
Definition at line 267 of file RFC_Window_overlay.h.
References _is_f_1, and get_index().
Referenced by RFC_Window_overlay::detect_features().
 { _is_f_1[ get_index(h)] = true; }
const int& size_of_subfaces () const inline
Definition at line 195 of file RFC_Window_overlay.h.
References _size_of_subfaces.
 { return _size_of_subfaces; }
int& size_of_subfaces () inline
Definition at line 196 of file RFC_Window_overlay.h.
References _size_of_subfaces.
 { return _size_of_subfaces; }
void unmark (Halfedge * h) inline
Definition at line 186 of file RFC_Window_overlay.h.
References _e_marks, and get_index().
Referenced by HDS_accessor< Tag_true >::unmark().
 { _e_marks[get_index(h)] = false; }
void unmark_alledges () protected
void unset_feature_0 (Vertex * v) inline protected
Definition at line 270 of file RFC_Window_overlay.h.
References _is_f_0, and get_index().
Referenced by RFC_Window_overlay::identify_features_0(), and RFC_Window_overlay::remove_feature_0().
 { _is_f_0[ get_index(v)] = false; }
void unset_on_feature (Vertex * v) inline protected
Definition at line 272 of file RFC_Window_overlay.h.
References _is_on_f, and get_index().
 { _is_on_f[ get_index(v)] = false; }
void unset_strong_edge (Halfedge * h) inline protected
Definition at line 268 of file RFC_Window_overlay.h.
References _is_f_1, and get_index().
Referenced by RFC_Window_overlay::check_false_strong_1(), RFC_Window_overlay::subdiv_feature_curve(), and RFC_Window_overlay::unset_strong_edge().
 { _is_f_1[ get_index(h)] = false; }
RFC_Window_overlay* window () inline
Definition at line 74 of file RFC_Window_overlay.h.
References _window.
 { return _window; }
const RFC_Window_overlay* window () const inline
Definition at line 75 of file RFC_Window_overlay.h.
References _window.
 { return _window; }
Friends And Related Function Documentation
friend class RFC_Window_overlay friend
Definition at line 69 of file RFC_Window_overlay.h.
Member Data Documentation
std::vector< float> _ad_0 protected
Definition at line 308 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::detect_features(), get_angle_defect(), and init_angle_defect().
std::map< std::pair<int,int>, Halfedge*> _bv2edges protected
Definition at line 290 of file RFC_Window_overlay.h.
Referenced by construct_bvpair2edge(), and determine_counterparts().
std::vector<Halfedge*> _cntrs protected
Definition at line 291 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), determine_counterparts(), get_counterpart(), and is_physical_border().
std::vector<int> _e_marks protected
Definition at line 320 of file RFC_Window_overlay.h.
Referenced by create_overlay_data(), delete_overlay_data(), get_buffered_inode(), mark(), marked(), set_buffered_inode(), unmark(), and RFC_Window_overlay::unmark_alledges().
std::vector<INode*> _e_node_buf protected
Definition at line 318 of file RFC_Window_overlay.h.
Referenced by create_overlay_data(), delete_overlay_data(), get_buffered_inode(), and set_buffered_inode().
std::vector<INode_list> _e_node_list protected
Definition at line 319 of file RFC_Window_overlay.h.
Referenced by create_overlay_data(), delete_overlay_data(), and get_inode_list().
std::vector< float> _ea_0 protected
Definition at line 309 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::detect_features(), get_cos_edge_angle(), init_edge_angle(), and reset_cos_edge_angle().
std::vector< int> _f_n_index protected
Definition at line 301 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::evaluate_normals(), get_normal(), and RFC_Window_overlay::remove_feature_1().
std::vector<Vector_3> _f_nrmls protected
Definition at line 297 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::evaluate_normals(), and get_normal().
std::vector< int> _f_t_index protected
Definition at line 305 of file RFC_Window_overlay.h.
Referenced by add_tangent(), delete_overlay_data(), RFC_Window_overlay::evaluate_normals(), and get_tangent().
std::vector< Vector_3> _f_tngts protected
Definition at line 304 of file RFC_Window_overlay.h.
Referenced by add_tangent(), delete_overlay_data(), RFC_Window_overlay::evaluate_normals(), and get_tangent().
std::vector< float> _fd_1 protected
Definition at line 310 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), RFC_Window_overlay::detect_features(), get_cos_face_angle(), and init_face_angle().
HDS _hds protected
Definition at line 287 of file RFC_Window_overlay.h.
Referenced by build_hds(), create_overlay_data(), RFC_Window_overlay::detect_features(), evaluate_normals(), RFC_Window_overlay::get_an_unmarked_halfedge(), get_index(), get_lid(), get_vertex_from_id(), hds(), init_angle_defect(), init_edge_angle(), and init_face_angle().
std::vector< bool> _is_f_0 protected
Definition at line 312 of file RFC_Window_overlay.h.
Referenced by RFC_Window_overlay::detect_features(), is_feature_0(), set_feature_0(), and unset_feature_0().
std::vector< bool> _is_f_1 protected
Definition at line 314 of file RFC_Window_overlay.h.
Referenced by RFC_Window_overlay::detect_features(), is_feature_1(), set_strong_edge(), and unset_strong_edge().
std::vector< bool> _is_on_f protected
Definition at line 313 of file RFC_Window_overlay.h.
Referenced by RFC_Window_overlay::detect_features(), is_on_feature(), set_on_feature(), and unset_on_feature().
std::vector<Vector_3> _nrmls protected
Definition at line 295 of file RFC_Window_overlay.h.
Referenced by evaluate_normals(), RFC_Window_overlay::evaluate_normals(), get_normal(), RFC_Window_overlay::reduce_normals_to_all(), and set_normal().
std::vector<Vertex*> _primaries protected
Definition at line 292 of file RFC_Window_overlay.h.
Referenced by delete_overlay_data(), determine_counterparts(), get_primary(), and is_primary().
int _size_of_subfaces protected
Definition at line 322 of file RFC_Window_overlay.h.
Referenced by size_of_subfaces().
std::vector< const INode*> _subnodes protected
Definition at line 323 of file RFC_Window_overlay.h.
std::vector<INode*> _v_nodes protected
Definition at line 317 of file RFC_Window_overlay.h.
Referenced by create_overlay_data(), delete_overlay_data(), get_inode(), and set_inode().
RFC_Window_overlay* _window protected
Definition at line 288 of file RFC_Window_overlay.h.
Referenced by determine_counterparts(), and window().
HDS_accessor< Tag_true > acc static protected
Definition at line 324 of file RFC_Window_overlay.h.
Referenced by get_normal(), and get_tangent().
The documentation for this class was generated from the following files:
RFC_Window_overlay.h
RFC_Window_overlay.C