Rocstar: rflu_modvgridns Module Reference
rflu_modvgridns Module Reference
Data Types
type t_gridvgridns
Public Member Functions
subroutine, public rflu_convvgridns2rocflu (pRegion)
subroutine, public rflu_readgridvgridns (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModVGRIDns.F90,v $ $Revision: 1.5 $'
type(t_gridvgridns) gridvgridns
Detailed Description
Definition at line 39 of file RFLU_ModVGRIDns.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_convvgridns2rocflu (type(t_region), pointer pRegion)
Definition at line 111 of file RFLU_ModVGRIDns.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, i, ic, moderror::registerfunction(), rflu_moddimensions::rflu_setmaxdimension(), Attribute::status(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_readconvgridwrapper().
subroutine, public rflu_readgridvgridns (type(t_region), pointer pRegion)
Definition at line 535 of file RFLU_ModVGRIDns.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, i, ic, moderror::registerfunction(), rflu_moddimensions::rflu_setmaxdimension(), and Attribute::status().
Referenced by rflu_readconvgridwrapper().
Member Data Documentation
type(t_gridvgridns) gridvgridns private
Definition at line 75 of file RFLU_ModVGRIDns.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModVGRIDns.F90,v $ $Revision: 1.5 $' private
Definition at line 66 of file RFLU_ModVGRIDns.F90.
The documentation for this module was generated from the following file:
RFLU_ModVGRIDns.F90