Rocstar: spec_rflu_modreadwritevars Module Reference
spec_rflu_modreadwritevars Module Reference
Public Member Functions
subroutine, public spec_rflu_readcvascii (pRegion)
subroutine, public spec_rflu_readcvbinary (pRegion)
subroutine, public spec_rflu_readeevascii (pRegion)
subroutine, public spec_rflu_readeevbinary (pRegion)
subroutine, public spec_rflu_writecvascii (pRegion)
subroutine, public spec_rflu_writecvbinary (pRegion)
subroutine, public spec_rflu_writeeevascii (pRegion)
subroutine, public spec_rflu_writeeevbinary (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: SPEC_RFLU_ModReadWriteVars.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 39 of file SPEC_RFLU_ModReadWriteVars.F90.
Member Function/Subroutine Documentation
subroutine, public spec_rflu_readcvascii (type(t_region), pointer pRegion)
Definition at line 106 of file SPEC_RFLU_ModReadWriteVars.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modreadwriteflow::rflu_readflowwrapper().
subroutine, public spec_rflu_readcvbinary (type(t_region), pointer pRegion)
Definition at line 389 of file SPEC_RFLU_ModReadWriteVars.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modreadwriteflow::rflu_readflowwrapper().
subroutine, public spec_rflu_readeevascii (type(t_region), pointer pRegion)
Definition at line 674 of file SPEC_RFLU_ModReadWriteVars.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modreadwriteflow::rflu_readflowwrapper().
subroutine, public spec_rflu_readeevbinary (type(t_region), pointer pRegion)
Definition at line 985 of file SPEC_RFLU_ModReadWriteVars.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modreadwriteflow::rflu_readflowwrapper().
subroutine, public spec_rflu_writecvascii (type(t_region), pointer pRegion)
Definition at line 1293 of file SPEC_RFLU_ModReadWriteVars.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modreadwriteflow::rflu_writeflowwrapper().
subroutine, public spec_rflu_writecvbinary (type(t_region), pointer pRegion)
Definition at line 1451 of file SPEC_RFLU_ModReadWriteVars.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modreadwriteflow::rflu_writeflowwrapper().
subroutine, public spec_rflu_writeeevascii (type(t_region), pointer pRegion)
Definition at line 1608 of file SPEC_RFLU_ModReadWriteVars.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modreadwriteflow::rflu_writeflowwrapper().
subroutine, public spec_rflu_writeeevbinary (type(t_region), pointer pRegion)
Definition at line 1778 of file SPEC_RFLU_ModReadWriteVars.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, j, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modreadwriteflow::rflu_writeflowwrapper().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: SPEC_RFLU_ModReadWriteVars.F90,v $ $Revision: 1.4 $' private
Definition at line 72 of file SPEC_RFLU_ModReadWriteVars.F90.
The documentation for this module was generated from the following file:
SPEC_RFLU_ModReadWriteVars.F90