Rocstar: I_DFT Class Reference
I_DFT Class Reference
Class containing the target corner matrices for the context based smoothing.
#include <I_DFT.hpp>
Public Member Functions
I_DFT ()
virtual ~I_DFT ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *e, double &m, MsqError &err)
Evaluate the metric for an element.
bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], int nfv, double &m, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], Matrix3D h[], int nfv, double &m, MsqError &err)
I_DFT ()
virtual ~I_DFT ()
virtual destructor ensures use of polymorphism during destruction
bool evaluate_element (PatchData &pd, MsqMeshEntity *e, double &m, MsqError &err)
Evaluate the metric for an element.
bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], int nfv, double &m, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *e, MsqVertex *fv[], Vector3D g[], Matrix3D h[], int nfv, double &m, MsqError &err)
Public Member Functions inherited from DistanceFromTarget
virtual ~DistanceFromTarget ()
virtual destructor ensures use of polymorphism during destruction
virtual ~DistanceFromTarget ()
virtual destructor ensures use of polymorphism during destruction
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
virtual bool evaluate_vertex (PatchData &, MsqVertex *, double &, MsqError &err)
Evaluate the metric for a vertex.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Protected Member Functions
void p_set_alpha (double alpha)
access function to set mAlpha
double p_get_alpha ()
access function to get mAlpha
void p_set_beta (double beta)
access function to set mBeta
double p_get_beta ()
access function to get mBeta
void p_set_gamma (double gamma)
access function to set mGamma
double p_get_gamma ()
access function to get mGamma
void p_set_use_barrier_delta (bool use_delta)
access function to set useBarrierDelta
bool p_get_use_barrier_delta ()
access function to get useBarrierDelta
void p_set_alpha (double alpha)
access function to set mAlpha
double p_get_alpha ()
access function to get mAlpha
void p_set_beta (double beta)
access function to set mBeta
double p_get_beta ()
access function to get mBeta
void p_set_gamma (double gamma)
access function to set mGamma
double p_get_gamma ()
access function to get mGamma
void p_set_use_barrier_delta (bool use_delta)
access function to set useBarrierDelta
bool p_get_use_barrier_delta ()
access function to get useBarrierDelta
Protected Member Functions inherited from DistanceFromTarget
void compute_T_matrices (MsqMeshEntity &elem, PatchData &pd, Matrix3D T[], size_t num_T, double c_k[], MsqError &err)
For a given element, compute each corner matrix A, and given a target corner matrix W, returns for each corner.
bool get_barrier_function (PatchData &pd, const double &tau, double &h, MsqError &err)
void compute_T_matrices (MsqMeshEntity &elem, PatchData &pd, Matrix3D T[], size_t num_T, double c_k[], MsqError &err)
For a given element, compute each corner matrix A, and given a target corner matrix W, returns for each corner.
bool get_barrier_function (PatchData &pd, const double &tau, double &h, MsqError &err)
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Private Attributes
double mAlpha
double mBeta
Exponent mGamma
bool useBarrierDelta
Vector3D mNormals [4]
Vector3D mCoords [4]
Vector3D mGrads [4]
Vector3D mAccGrads [8]
Matrix3D mHessians [10]
Matrix3D mR
Matrix3D invR
Matrix3D mQ
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
Class containing the target corner matrices for the context based smoothing.
The form of this metric is as follows (taken from I_DFTFamilyFunctions.hpp, see that file for more detail):
              mAlpha * || A*inv(W) - mBeta * I ||_F^2                    \n
---------------------------------------------------------------—
0.5^(mGamma)*(det(A*inv(W)) + sqrt(det(A*inv(W))^2 + 4*delta^2))^(mGamma)
The default for data members (corresponding to the variables above):
  mAlpha = 1/2.0; \n
  mBeta = 1.0; \n
  mGamma = MSQ_TWO_THIRDS; \n
delta, above, is calculated using PatchData::get_barrier_delta(MsqError &err), if useBarrierDelta == true. Otherwise, delta is zero.
Definition at line 69 of file includeLinks/I_DFT.hpp.
Constructor & Destructor Documentation
I_DFT () inline
Definition at line 73 of file includeLinks/I_DFT.hpp.
References QualityMetric::ANALYTICAL_GRADIENT, QualityMetric::ANALYTICAL_HESSIAN, QualityMetric::ELEMENT_BASED, QualityMetric::LINEAR, I_DFT::mAlpha, I_DFT::mBeta, I_DFT::mGamma, Mesquite::MSQ_TWO_THIRDS, QualityMetric::set_averaging_method(), QualityMetric::set_gradient_type(), QualityMetric::set_hessian_type(), QualityMetric::set_metric_type(), QualityMetric::set_name(), and I_DFT::useBarrierDelta.
     {
       MsqError err;
       set_averaging_method(LINEAR, err);
       set_metric_type(ELEMENT_BASED);
       set_gradient_type(ANALYTICAL_GRADIENT);
       set_hessian_type(ANALYTICAL_HESSIAN);
       set_name("I_DFT");
       mAlpha = 1/2.0;
       mBeta = 1.0;
       mGamma = MSQ_TWO_THIRDS;
       useBarrierDelta = true;
    }
virtual ~I_DFT () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 88 of file includeLinks/I_DFT.hpp.
        {};
I_DFT () inline
Definition at line 73 of file src/QualityMetric/DFT/I_DFT.hpp.
References QualityMetric::ANALYTICAL_GRADIENT, QualityMetric::ANALYTICAL_HESSIAN, QualityMetric::ELEMENT_BASED, QualityMetric::LINEAR, I_DFT::mAlpha, I_DFT::mBeta, I_DFT::mGamma, Mesquite::MSQ_TWO_THIRDS, QualityMetric::set_averaging_method(), QualityMetric::set_gradient_type(), QualityMetric::set_hessian_type(), QualityMetric::set_metric_type(), QualityMetric::set_name(), and I_DFT::useBarrierDelta.
     {
       MsqError err;
       set_averaging_method(LINEAR, err);
       set_metric_type(ELEMENT_BASED);
       set_gradient_type(ANALYTICAL_GRADIENT);
       set_hessian_type(ANALYTICAL_HESSIAN);
       set_name("I_DFT");
       mAlpha = 1/2.0;
       mBeta = 1.0;
       mGamma = MSQ_TWO_THIRDS;
       useBarrierDelta = true;
    }
virtual ~I_DFT () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 88 of file src/QualityMetric/DFT/I_DFT.hpp.
        {};
Member Function Documentation
bool compute_element_analytical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
If that function is not over-riden in the concrete class, the base
Parameters description, see QualityMetric::compute_element_gradient() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
Definition at line 174 of file QualityMetric/DFT/I_DFT.cpp.
References MsqMeshEntity::compute_corner_normals(), Mesquite::g_gdft_2(), Mesquite::g_gdft_2_v0(), Mesquite::g_gdft_2_v1(), Mesquite::g_gdft_2_v2(), Mesquite::g_gdft_3(), Mesquite::g_gdft_3_v0(), Mesquite::g_gdft_3_v1(), Mesquite::g_gdft_3_v2(), Mesquite::g_gdft_3_v3(), PatchData::get_barrier_delta(), TargetMatrix::get_cK(), PatchData::get_element_index(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), Mesquite::HEXAHEDRON, i, Mesquite::inv(), I_DFT::invR, j, Mesquite::m_gdft_2(), Mesquite::m_gdft_3(), I_DFT::mAccGrads, I_DFT::mAlpha, I_DFT::mBeta, I_DFT::mCoords, I_DFT::mGamma, I_DFT::mGrads, I_DFT::mNormals, I_DFT::mQ, I_DFT::mR, Mesquite::MSQ_3RT_2_OVER_6RT_3, MSQ_ERRZERO, Mesquite::MSQ_ONE_THIRD, MSQ_SETERR, MsqError::NOT_IMPLEMENTED, Mesquite::QR(), Mesquite::QUADRILATERAL, PatchData::targetMatrices, Mesquite::TETRAHEDRON, Mesquite::TRIANGLE, I_DFT::useBarrierDelta, and MsqMeshEntity::vertex_count().
 {
   // Only works with the weighted average
   MsqVertex *vertices = pd.get_vertex_array(err); MSQ_ERRZERO(err);
   EntityTopology topo = e->get_element_type();
   const size_t nv = e->vertex_count();
   const size_t *v_i = e->get_vertex_index_array();
   size_t idx = pd.get_element_index(e);
   const TargetMatrix *W = pd.targetMatrices.get_element_corner_tags(&pd, idx, err );
   MSQ_ERRZERO(err);
   // Initialize constants for the metric
   const double delta = useBarrierDelta ? pd.get_barrier_delta(err) :
     (mGamma ? 0 : 1);
     //const double delta = useBarrierDelta ? pd.get_barrier_delta(err) : 0;
   MSQ_ERRZERO(err);
   const int tetInd[4][4] = {{0, 1, 2, 3}, {1, 2, 0, 3},
                             {2, 0, 1, 3}, {3, 2, 1, 0}};
   const int hexInd[8][4] = {{0, 1, 3, 4}, {1, 2, 0, 5},
                             {2, 3, 1, 6}, {3, 0, 2, 7},
                             {4, 7, 5, 0}, {5, 4, 6, 1},
                             {6, 5, 7, 2}, {7, 6, 4, 3}};
   // Variables used for computing the metric
   double   mMetric;             // Metric value
   bool     mValid;              // Validity of the metric
   int      i, j, mVert;
   m = 0.0;
   switch(topo) {
   case TRIANGLE:
     assert(3 == nv);
     e->compute_corner_normals( mNormals, pd, err ); MSQ_ERRZERO(err);
     // The following analytic calculation only works correctly if the
     // normal is constant.  If the normal is not constant, you need
     // to get the gradient of the normal with respect to the vertex
     // positions to obtain the correct values.
     if (1 == nfv) {
       // One free vertex; use the specialized code for computing the gradient.
       g[0] = 0.0;
       for (i = 0; i < 3; ++i) {
         mVert = -1;
         for (j = 0; j < 3; ++j) {
           mCoords[j] = vertices[v_i[tetInd[i][j]]];
           if (vertices + v_i[tetInd[i][j]] == fv[0]) {
             mVert = j;
           }
         }
         if (mVert >= 0) {
           mNormals[i] *= MSQ_3RT_2_OVER_6RT_3;
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           switch(mVert) {
           case 0:
             mValid = g_gdft_2_v0(mMetric, mGrads[0], mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           case 1:
             mValid = g_gdft_2_v1(mMetric, mGrads[0], mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           default:
             mValid = g_gdft_2_v2(mMetric, mGrads[0], mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           }
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
           g[0] += W[i].get_cK() * mGrads[0];
         }
         else {
           // For triangles, the free vertex must appear in every element.
           // Therefore, there these accumulations should not get used.
           mNormals[i] *= MSQ_3RT_2_OVER_6RT_3;
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           mValid = m_gdft_2(mMetric, mCoords, mNormals[i],
                             invR, mQ, mAlpha, mGamma, delta, mBeta);
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
         }
       }
       m *= MSQ_ONE_THIRD;
       g[0] *= MSQ_ONE_THIRD;
     }
     else {
       for (i = 0; i < 3; ++i) {
         mAccGrads[i] = 0.0;
       }
       for (i = 0; i < 3; ++i) {
         for (j = 0; j < 3; ++j) {
           mCoords[j] = vertices[v_i[tetInd[i][j]]];
         }
         mNormals[i] *= MSQ_3RT_2_OVER_6RT_3;
         QR(mQ, mR, W[i]);
         inv(invR, mR);
         mValid = g_gdft_2(mMetric, mGrads, mCoords, mNormals[i], invR, mQ,
                           mAlpha, mGamma, delta, mBeta);
         if (!mValid) return false;
         m += W[i].get_cK() * mMetric;
         for (j = 0; j < 3; ++j) {
           mAccGrads[tetInd[i][j]] += W[i].get_cK() * mGrads[j];
         }
       }
       m *= MSQ_ONE_THIRD;
       for (i = 0; i < 3; ++i) {
         mAccGrads[i] *= MSQ_ONE_THIRD;
       }
       // This is not very efficient, but is one way to select correct
       // gradients.  For gradients, info is returned only for free
       // vertices, in the order of fv[].
       for (i = 0; i < 3; ++i) {
         for (j = 0; j < nfv; ++j) {
           if (vertices + v_i[i] == fv[j]) {
             g[j] = mAccGrads[i];
           }
         }
       }
     }
     break;
   case QUADRILATERAL:
     assert(4 == nv);
     e->compute_corner_normals( mNormals, pd, err ); MSQ_ERRZERO(err);
     // The following analytic calculation only works correctly if the
     // normal is constant.  If the normal is not constant, you need
     // to get the gradient of the normal with respect to the vertex
     // positions to obtain the correct values.
     if (1 == nfv) {
       // One free vertex; use the specialized code for computing the gradient.
       g[0] = 0.0;
       for (i = 0; i < 4; ++i) {
         mVert = -1;
         for (j = 0; j < 3; ++j) {
           mCoords[j] = vertices[v_i[hexInd[i][j]]];
           if (vertices + v_i[hexInd[i][j]] == fv[0]) {
             mVert = j;
           }
         }
         if (mVert >= 0) {
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           switch(mVert) {
           case 0:
             mValid = g_gdft_2_v0(mMetric, mGrads[0], mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           case 1:
             mValid = g_gdft_2_v1(mMetric, mGrads[0], mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           default:
             mValid = g_gdft_2_v2(mMetric, mGrads[0], mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           }
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
           g[0] += W[i].get_cK() * mGrads[0];
         }
         else {
           // For quadrilaterals, the free vertex only appears in three
           // elements.  Therefore, there these accumulations are needed
           // to get the true local objective function.  Note: this code
           // can be commented out for local codes to improve performance
           // because you are unable to change the contributions from the
           // elements where the free vertex does not appear.  (If the
           // weight matrices change, then the code needs to be modified.)
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           mValid = m_gdft_2(mMetric, mCoords, mNormals[i],
                             invR, mQ, mAlpha, mGamma, delta, mBeta);
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
         }
       }
       m *= 0.25;
       g[0] *= 0.25;
     }
     else {
       for (i = 0; i < 4; ++i) {
         mAccGrads[i] = 0.0;
       }
       for (i = 0; i < 4; ++i) {
         for (j = 0; j < 3; ++j) {
           mCoords[j] = vertices[v_i[hexInd[i][j]]];
         }
         QR(mQ, mR, W[i]);
         inv(invR, mR);
         mValid = g_gdft_2(mMetric, mGrads, mCoords, mNormals[i], invR, mQ,
                           mAlpha, mGamma, delta, mBeta);
         if (!mValid) return false;
         m += W[i].get_cK() * mMetric;
         for (j = 0; j < 3; ++j) {
           mAccGrads[hexInd[i][j]] += W[i].get_cK() * mGrads[j];
         }
       }
       m *= 0.25;
       for (i = 0; i < 4; ++i) {
         mAccGrads[i] *= 0.25;
       }
       // This is not very efficient, but is one way to select correct gradients
       // For gradients, info is returned only for free vertices, in the order
       // of fv[].
       for (i = 0; i < 4; ++i) {
         for (j = 0; j < nfv; ++j) {
           if (vertices + v_i[i] == fv[j]) {
             g[j] = mAccGrads[i];
           }
         }
       }
     }
     break;
   case TETRAHEDRON:
     assert(4 == nv);
     if (1 == nfv) {
       // One free vertex; use the specialized code for computing the gradient.
       g[0] = 0.0;
       for (i = 0; i < 4; ++i) {
         mVert = -1;
         for (j = 0; j < 4; ++j) {
           mCoords[j] = vertices[v_i[tetInd[i][j]]];
           if (vertices + v_i[tetInd[i][j]] == fv[0]) {
             mVert = j;
           }
         }
         if (mVert >= 0) {
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           switch(mVert) {
           case 0:
             mValid = g_gdft_3_v0(mMetric, mGrads[0], mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           case 1:
             mValid = g_gdft_3_v1(mMetric, mGrads[0], mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           case 2:
             mValid = g_gdft_3_v2(mMetric, mGrads[0], mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           default:
             mValid = g_gdft_3_v3(mMetric, mGrads[0], mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           }
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
           g[0] += W[i].get_cK() * mGrads[0];
         }
         else {
           // For tetrahedrons, the free vertex must appear in every element.
           // Therefore, there these accumulations should not get used.
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           mValid = m_gdft_3(mMetric, mCoords, invR, mQ,
                             mAlpha, mGamma, delta, mBeta);
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
         }
       }
       m *= 0.25;
       g[0] *= 0.25;
     }
     else {
       for (i = 0; i < 4; ++i) {
         mAccGrads[i] = 0.0;
       }
       for (i = 0; i < 4; ++i) {
         for (j = 0; j < 4; ++j) {
           mCoords[j] = vertices[v_i[tetInd[i][j]]];
         }
         QR(mQ, mR, W[i]);
         inv(invR, mR);
         mValid = g_gdft_3(mMetric, mGrads, mCoords, invR, mQ,
                           mAlpha, mGamma, delta, mBeta);
         if (!mValid) return false;
         m += W[i].get_cK() * mMetric;
         for (j = 0; j < 4; ++j) {
           mAccGrads[tetInd[i][j]] += W[i].get_cK() * mGrads[j];
         }
       }
       m *= 0.25;
       for (i = 0; i < 4; ++i) {
         mAccGrads[i] *= 0.25;
       }
       // This is not very efficient, but is one way to select correct
       // gradients.  For gradients, info is returned only for free vertices,
       // in the order of fv[].
       for (i = 0; i < 4; ++i) {
         for (j = 0; j < nfv; ++j) {
           if (vertices + v_i[i] == fv[j]) {
             g[j] = mAccGrads[i];
           }
         }
       }
     }
     break;
   case HEXAHEDRON:
     assert(8 == nv);
     if (1 == nfv) {
       // One free vertex; use the specialized code for computing the gradient.
       g[0] = 0.0;
       for (i = 0; i < 8; ++i) {
         mVert = -1;
         for (j = 0; j < 4; ++j) {
           mCoords[j] = vertices[v_i[hexInd[i][j]]];
           if (vertices + v_i[hexInd[i][j]] == fv[0]) {
             mVert = j;
           }
         }
         if (mVert >= 0) {
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           switch(mVert) {
           case 0:
             mValid = g_gdft_3_v0(mMetric, mGrads[0], mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           case 1:
             mValid = g_gdft_3_v1(mMetric, mGrads[0], mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           case 2:
             mValid = g_gdft_3_v2(mMetric, mGrads[0], mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           default:
             mValid = g_gdft_3_v3(mMetric, mGrads[0], mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           }
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
           g[0] += W[i].get_cK() * mGrads[0];
         }
         else {
           // For hexahedrons, the free vertex only appears in four elements.
           // Therefore, there these accumulations are needed to get the
           // true local objective function.  Note: this code can be commented
           // out for local codes to improve performance because you are
           // unable to change the contributions from the elements where the
           // free vertex does not appear.  (If the weight matrices change,
           // then the code needs to be modified.)
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           mValid = m_gdft_3(mMetric, mCoords, invR, mQ,
                             mAlpha, mGamma, delta, mBeta);
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
         }
       }
       m *= 0.125;
       g[0] *= 0.125;
     }
     else {
       for (i = 0; i < 8; ++i) {
         mAccGrads[i] = 0.0;
       }
       for (i = 0; i < 8; ++i) {
         for (j = 0; j < 4; ++j) {
           mCoords[j] = vertices[v_i[hexInd[i][j]]];
         }
         QR(mQ, mR, W[i]);
         inv(invR, mR);
         mValid = g_gdft_3(mMetric, mGrads, mCoords, invR, mQ,
                           mAlpha, mGamma, delta, mBeta);
         if (!mValid) return false;
         m += W[i].get_cK() * mMetric;
         for (j = 0; j < 4; ++j) {
           mAccGrads[hexInd[i][j]] += W[i].get_cK() * mGrads[j];
         }
       }
       m *= 0.125;
       for (i = 0; i < 8; ++i) {
         mAccGrads[i] *= 0.125;
       }
       // This is not very efficient, but is one way to select correct
       // gradients.  For gradients, info is returned only for free
       // vertices, in the order of fv[].
       for (i = 0; i < 8; ++i) {
         for (j = 0; j < nfv; ++j) {
           if (vertices + v_i[i] == fv[j]) {
             g[j] = mAccGrads[i];
           }
         }
       }
     }
     break;
   default:
     MSQ_SETERR(err)("element type not implemented.",MsqError::NOT_IMPLEMENTED);
     return false;
   }
   return true;
 }
bool compute_element_analytical_gradient (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], int num_free_vtx, double & metric_value, MsqError & err) virtual
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
If that function is not over-riden in the concrete class, the base
Parameters description, see QualityMetric::compute_element_gradient() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
bool compute_element_analytical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) virtual
If that function is not over-riden in the concrete class, the base class function makes it default to a numerical hessian.
For parameters description, see QualityMetric::compute_element_hessian() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
Definition at line 658 of file QualityMetric/DFT/I_DFT.cpp.
References MsqMeshEntity::compute_corner_normals(), PatchData::get_barrier_delta(), TargetMatrix::get_cK(), PatchData::get_element_index(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), Mesquite::h_gdft_2(), Mesquite::h_gdft_2_v0(), Mesquite::h_gdft_2_v1(), Mesquite::h_gdft_2_v2(), Mesquite::h_gdft_3(), Mesquite::h_gdft_3_v0(), Mesquite::h_gdft_3_v1(), Mesquite::h_gdft_3_v2(), Mesquite::h_gdft_3_v3(), Mesquite::HEXAHEDRON, i, Mesquite::inv(), I_DFT::invR, j, k, Mesquite::m_gdft_2(), Mesquite::m_gdft_3(), I_DFT::mAlpha, I_DFT::mBeta, I_DFT::mCoords, I_DFT::mGamma, I_DFT::mGrads, I_DFT::mHessians, I_DFT::mNormals, I_DFT::mQ, I_DFT::mR, Mesquite::MSQ_3RT_2_OVER_6RT_3, MSQ_ERRZERO, Mesquite::MSQ_ONE_THIRD, MSQ_SETERR, MsqError::NOT_IMPLEMENTED, Mesquite::QR(), Mesquite::QUADRILATERAL, PatchData::targetMatrices, Mesquite::TETRAHEDRON, Mesquite::transpose(), Mesquite::TRIANGLE, I_DFT::useBarrierDelta, MsqMeshEntity::vertex_count(), and Matrix3D::zero().
 {
   // Only works with the weighted average
   MsqVertex *vertices = pd.get_vertex_array(err);  MSQ_ERRZERO(err);
   EntityTopology topo = e->get_element_type();
   const size_t nv = e->vertex_count();
   const size_t *v_i = e->get_vertex_index_array();
   size_t idx = pd.get_element_index(e);
   const TargetMatrix *W = pd.targetMatrices.get_element_corner_tags(&pd, idx, err );
   MSQ_ERRZERO(err);
   // Initialize constants for the metric
   const double delta = useBarrierDelta ? pd.get_barrier_delta(err) :
     (mGamma ? 0 : 1);
     //const double delta = useBarrierDelta ? pd.get_barrier_delta(err) : 0;
   MSQ_ERRZERO(err);
   const int tetInd[4][4] = {{0, 1, 2, 3}, {1, 2, 0, 3},
                             {2, 0, 1, 3}, {3, 2, 1, 0}};
   const int hexInd[8][4] = {{0, 1, 3, 4}, {1, 2, 0, 5},
                             {2, 3, 1, 6}, {3, 0, 2, 7},
                             {4, 7, 5, 0}, {5, 4, 6, 1},
                             {6, 5, 7, 2}, {7, 6, 4, 3}};
   // Variables used for computing the metric
   double   mMetric;             // Metric value
   bool     mValid;              // Validity of the metric
   int      i, j, k, l, mVert;
   int      row, col, loc;
   m = 0.0;
   switch(topo) {
   case TRIANGLE:
     assert(3 == nv);
     e->compute_corner_normals( mNormals, pd, err ); MSQ_ERRZERO(err);
     // The following analytic calculation only works correctly if the
     // normal is constant.  If the normal is not constant, you need
     // to get the gradient of the normal with respect to the vertex
     // positions to obtain the correct values.
     // Zero out the hessian and gradient vector
     for (i = 0; i < 3; ++i) {
       g[i] = 0.0;
     }
     for (i = 0; i < 6; ++i) {
       h[i].zero();
     }
     if (1 == nfv) {
       // One free vertex; use the specialized code for computing the
       // gradient and Hessian.
       Vector3D mG;
       Matrix3D mH;
       mG = 0.0;
       mH.zero();
       for (i = 0; i < 3; ++i) {
         mVert = -1;
         for (j = 0; j < 3; ++j) {
           mCoords[j] = vertices[v_i[tetInd[i][j]]];
           if (vertices + v_i[tetInd[i][j]] == fv[0]) {
             mVert = j;
           }
         }
         if (mVert >= 0) {
           mNormals[i] *= MSQ_3RT_2_OVER_6RT_3;
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           switch(mVert) {
           case 0:
             mValid = h_gdft_2_v0(mMetric, mGrads[0], mHessians[0],
                                  mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           case 1:
             mValid = h_gdft_2_v1(mMetric, mGrads[0], mHessians[0],
                                  mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           default:
             mValid = h_gdft_2_v2(mMetric, mGrads[0], mHessians[0],
                                  mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           }
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
           mG += W[i].get_cK() * mGrads[0];
           mH += W[i].get_cK() * mHessians[0];
         }
         else {
           // For triangles, the free vertex must appear in every element.
           // Therefore, there these accumulations should not get used.
           mNormals[i] *= MSQ_3RT_2_OVER_6RT_3;
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           mValid = m_gdft_2(mMetric, mCoords, mNormals[i],
                             invR, mQ, mAlpha, mGamma, delta, mBeta);
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
         }
       }
       m *= MSQ_ONE_THIRD;
       mG *= MSQ_ONE_THIRD;
       mH *= MSQ_ONE_THIRD;
       for (i = 0; i < 3; ++i) {
         if (vertices + v_i[i] == fv[0]) {
           // free vertex, see next
           g[i] = mG;
           switch(i) {
           case 0:
             h[0] = mH;
             break;
           case 1:
             h[3] = mH;
             break;
           default:
             h[5] = mH;
             break;
           }
           break;
         }
       }
     }
     else {
       // Compute the metric and sum them together
       for (i = 0; i < 3; ++i) {
         for (j = 0; j < 3; ++j) {
           mCoords[j] = vertices[v_i[tetInd[i][j]]];
         }
         mNormals[i] *= MSQ_3RT_2_OVER_6RT_3;
         QR(mQ, mR, W[i]);
         inv(invR, mR);
         mValid = h_gdft_2(mMetric, mGrads, mHessians, mCoords, mNormals[i],
                           invR, mQ, mAlpha, mGamma, delta, mBeta);
         if (!mValid) return false;
         m += W[i].get_cK() * mMetric;
         for (j = 0; j < 3; ++j) {
           g[tetInd[i][j]] += W[i].get_cK() * mGrads[j];
         }
         l = 0;
         for (j = 0; j < 3; ++j) {
           for (k = j; k < 3; ++k) {
             row = tetInd[i][j];
             col = tetInd[i][k];
             if (row <= col) {
               loc = 3*row - (row*(row+1)/2) + col;
               h[loc] += W[i].get_cK() * mHessians[l];
             }
             else {
               loc = 3*col - (col*(col+1)/2) + row;
               h[loc] += W[i].get_cK() * transpose(mHessians[l]);
             }
             ++l;
           }
         }
       }
       m *= MSQ_ONE_THIRD;
       for (i = 0; i < 3; ++i) {
         g[i] *= MSQ_ONE_THIRD;
       }
       for (i = 0; i < 6; ++i) {
         h[i] *= MSQ_ONE_THIRD;
       }
       // zero out fixed elements of g
       j = 0;
       for (i = 0; i < 3; ++i) {
         if (vertices + v_i[i] == fv[j]) {
           // if free vertex, see next
           ++j;
         }
         else {
           // else zero gradient entry and hessian entries.
           g[i] = 0.;
           switch(i) {
           case 0:
             h[0].zero(); h[1].zero(); h[2].zero();
             break;
           case 1:
             h[1].zero(); h[3].zero(); h[4].zero();
             break;
           case 2:
             h[2].zero(); h[4].zero(); h[5].zero();
             break;
           }
         }
       }
     }
     break;
   case QUADRILATERAL:
     assert(4 == nv);
     e->compute_corner_normals( mNormals, pd, err ); MSQ_ERRZERO(err);
     // The following analytic calculation only works correctly if the
     // normal is constant.  If the normal is not constant, you need
     // to get the gradient of the normal with respect to the vertex
     // positions to obtain the correct values.
     // Zero out the hessian and gradient vector
     for (i = 0; i < 4; ++i) {
       g[i] = 0.0;
     }
     for (i = 0; i < 10; ++i) {
       h[i].zero();
     }
     if (1 == nfv) {
       // One free vertex; use the specialized code for computing the
       // gradient and Hessian.
       Vector3D mG;
       Matrix3D mH;
       mG = 0.0;
       mH.zero();
       for (i = 0; i < 4; ++i) {
         mVert = -1;
         for (j = 0; j < 3; ++j) {
           mCoords[j] = vertices[v_i[hexInd[i][j]]];
           if (vertices + v_i[hexInd[i][j]] == fv[0]) {
             mVert = j;
           }
         }
         if (mVert >= 0) {
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           switch(mVert) {
           case 0:
             mValid = h_gdft_2_v0(mMetric, mGrads[0], mHessians[0],
                                  mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           case 1:
             mValid = h_gdft_2_v1(mMetric, mGrads[0], mHessians[0],
                                  mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           default:
             mValid = h_gdft_2_v2(mMetric, mGrads[0], mHessians[0],
                                  mCoords, mNormals[i],
                                  invR, mQ, mAlpha, mGamma, delta, mBeta);
             break;
           }
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
           mG += W[i].get_cK() * mGrads[0];
           mH += W[i].get_cK() * mHessians[0];
         }
         else {
           // For quadrilaterals, the free vertex only appears in three
           // elements.  Therefore, there these accumulations are needed
           // to get the true local objective function.  Note: this code
           // can be commented out for local codes to improve performance
           // because you are unable to change the contributions from the
           // elements where the free vertex does not appear.  (If the
           // weight matrices change, then the code needs to be modified.)
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           mValid = m_gdft_2(mMetric, mCoords, mNormals[i],
                             invR, mQ, mAlpha, mGamma, delta, mBeta);
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
         }
       }
       m *= 0.25;
       mG *= 0.25;
       mH *= 0.25;
       for (i = 0; i < 4; ++i) {
         if (vertices + v_i[i] == fv[0]) {
           // free vertex, see next
           g[i] = mG;
           switch(i) {
           case 0:
             h[0] = mH;
             break;
           case 1:
             h[4] = mH;
             break;
           case 2:
             h[7] = mH;
             break;
           default:
             h[9] = mH;
             break;
           }
           break;
         }
       }
     }
     else {
       // Compute the metric and sum them together
       for (i = 0; i < 4; ++i) {
         for (j = 0; j < 3; ++j) {
           mCoords[j] = vertices[v_i[hexInd[i][j]]];
         }
         QR(mQ, mR, W[i]);
         inv(invR, mR);
         mValid = h_gdft_2(mMetric, mGrads, mHessians, mCoords, mNormals[i],
                           invR, mQ, mAlpha, mGamma, delta, mBeta);
         if (!mValid) return false;
         m += W[i].get_cK() * mMetric;
         for (j = 0; j < 3; ++j) {
           g[hexInd[i][j]] += W[i].get_cK() * mGrads[j];
         }
         l = 0;
         for (j = 0; j < 3; ++j) {
           for (k = j; k < 3; ++k) {
             row = hexInd[i][j];
             col = hexInd[i][k];
             if (row <= col) {
               loc = 4*row - (row*(row+1)/2) + col;
               h[loc] += W[i].get_cK() * mHessians[l];
             }
             else {
               loc = 4*col - (col*(col+1)/2) + row;
               h[loc] += W[i].get_cK() * transpose(mHessians[l]);
             }
             ++l;
           }
         }
       }
       m *= 0.25;
       for (i = 0; i < 4; ++i) {
         g[i] *= 0.25;
       }
       for (i = 0; i < 10; ++i) {
         h[i] *= 0.25;
       }
       // zero out fixed elements of gradient and Hessian
       j = 0;
       for (i = 0; i < 4; ++i) {
         if (vertices + v_i[i] == fv[j]) {
           // if free vertex, see next
           ++j;
         }
         else {
           // else zero gradient entry and hessian entries.
           g[i] = 0.;
           switch(i) {
           case 0:
             h[0].zero();   h[1].zero();   h[2].zero();   h[3].zero();
             break;
           case 1:
             h[1].zero();   h[4].zero();   h[5].zero();   h[6].zero();
             break;
           case 2:
             h[2].zero();   h[5].zero();   h[7].zero();  h[8].zero();
             break;
           case 3:
             h[3].zero();   h[6].zero();   h[8].zero();  h[9].zero();
             break;
           }
         }
       }
     }
     break;
   case TETRAHEDRON:
     assert(4 == nv);
     // Zero out the hessian and gradient vector
     for (i = 0; i < 4; ++i) {
       g[i] = 0.0;
     }
     for (i = 0; i < 10; ++i) {
       h[i].zero();
     }
     if (1 == nfv) {
       // One free vertex; use the specialized code for computing the
       // gradient and Hessian.
       Vector3D mG;
       Matrix3D mH;
       mG = 0.0;
       mH.zero();
       for (i = 0; i < 4; ++i) {
         mVert = -1;
         for (j = 0; j < 4; ++j) {
           mCoords[j] = vertices[v_i[tetInd[i][j]]];
           if (vertices + v_i[tetInd[i][j]] == fv[0]) {
             mVert = j;
           }
         }
         if (mVert >= 0) {
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           switch(mVert) {
           case 0:
             mValid = h_gdft_3_v0(mMetric, mGrads[0], mHessians[0],
                                  mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           case 1:
             mValid = h_gdft_3_v1(mMetric, mGrads[0], mHessians[0],
                                  mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           case 2:
             mValid = h_gdft_3_v2(mMetric, mGrads[0], mHessians[0],
                                  mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           default:
             mValid = h_gdft_3_v3(mMetric, mGrads[0], mHessians[0],
                                  mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           }
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
           mG += W[i].get_cK() * mGrads[0];
           mH += W[i].get_cK() * mHessians[0];
         }
         else {
           // For tetrahedrons, the free vertex must appear in every element.
           // Therefore, there these accumulations should not get used.
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           mValid = m_gdft_3(mMetric, mCoords, invR, mQ,
                             mAlpha, mGamma, delta, mBeta);
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
         }
       }
       m *= 0.25;
       mG *= 0.25;
       mH *= 0.25;
       for (i = 0; i < 4; ++i) {
         if (vertices + v_i[i] == fv[0]) {
           // free vertex, see next
           g[i] = mG;
           switch(i) {
           case 0:
             h[0] = mH;
             break;
           case 1:
             h[4] = mH;
             break;
           case 2:
             h[7] = mH;
             break;
           default:
             h[9] = mH;
             break;
           }
           break;
         }
       }
     }
     else {
       // Compute the metric and sum them together
       for (i = 0; i < 4; ++i) {
         for (j = 0; j < 4; ++j) {
           mCoords[j] = vertices[v_i[tetInd[i][j]]];
         }
         QR(mQ, mR, W[i]);
         inv(invR, mR);
         mValid = h_gdft_3(mMetric, mGrads, mHessians, mCoords, invR, mQ,
                           mAlpha, mGamma, delta, mBeta);
         if (!mValid) return false;
         m += W[i].get_cK() * mMetric;
         for (j = 0; j < 4; ++j) {
           g[tetInd[i][j]] += W[i].get_cK() * mGrads[j];
         }
         l = 0;
         for (j = 0; j < 4; ++j) {
           for (k = j; k < 4; ++k) {
             row = tetInd[i][j];
             col = tetInd[i][k];
             if (row <= col) {
               loc = 4*row - (row*(row+1)/2) + col;
               h[loc] += W[i].get_cK() * mHessians[l];
             }
             else {
               loc = 4*col - (col*(col+1)/2) + row;
               h[loc] += W[i].get_cK() * transpose(mHessians[l]);
             }
             ++l;
           }
         }
       }
       m *= 0.25;
       for (i = 0; i < 4; ++i) {
         g[i] *= 0.25;
       }
       for (i = 0; i < 10; ++i) {
         h[i] *= 0.25;
       }
       // zero out fixed elements of g
       j = 0;
       for (i = 0; i < 4; ++i) {
         if (vertices + v_i[i] == fv[j]) {
           // if free vertex, see next
           ++j;
         }
         else {
           // else zero gradient entry and hessian entries.
           g[i] = 0.;
           switch(i) {
           case 0:
             h[0].zero(); h[1].zero(); h[2].zero(); h[3].zero();
             break;
           case 1:
             h[1].zero(); h[4].zero(); h[5].zero(); h[6].zero();
             break;
           case 2:
             h[2].zero(); h[5].zero(); h[7].zero(); h[8].zero();
             break;
           case 3:
             h[3].zero(); h[6].zero(); h[8].zero(); h[9].zero();
             break;
           }
         }
       }
     }
     break;
   case HEXAHEDRON:
     assert(8 == nv);
     // Zero out the hessian and gradient vector
     for (i = 0; i < 8; ++i) {
       g[i] = 0.0;
     }
     for (i = 0; i < 36; ++i) {
       h[i].zero();
     }
     if (1 == nfv) {
       // One free vertex; use the specialized code for computing the
       // gradient and Hessian.
       Vector3D mG;
       Matrix3D mH;
       mG = 0.0;
       mH.zero();
       for (i = 0; i < 8; ++i) {
         mVert = -1;
         for (j = 0; j < 4; ++j) {
           mCoords[j] = vertices[v_i[hexInd[i][j]]];
           if (vertices + v_i[hexInd[i][j]] == fv[0]) {
             mVert = j;
           }
         }
         if (mVert >= 0) {
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           switch(mVert) {
           case 0:
             mValid = h_gdft_3_v0(mMetric, mGrads[0], mHessians[0],
                                  mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           case 1:
             mValid = h_gdft_3_v1(mMetric, mGrads[0], mHessians[0],
                                  mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           case 2:
             mValid = h_gdft_3_v2(mMetric, mGrads[0], mHessians[0],
                                  mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           default:
             mValid = h_gdft_3_v3(mMetric, mGrads[0], mHessians[0],
                                  mCoords, invR, mQ,
                                  mAlpha, mGamma, delta, mBeta);
             break;
           }
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
           mG += W[i].get_cK() * mGrads[0];
           mH += W[i].get_cK() * mHessians[0];
         }
         else {
           // For hexahedrons, the free vertex only appears in four elements.
           // Therefore, there these accumulations are needed to get the
           // true local objective function.  Note: this code can be commented
           // out for local codes to improve performance because you are
           // unable to change the contributions from the elements where the
           // free vertex does not appear.  (If the weight matrices change,
           // then the code needs to be modified.)
           QR(mQ, mR, W[i]);
           inv(invR, mR);
           mValid = m_gdft_3(mMetric, mCoords, invR, mQ,
                             mAlpha, mGamma, delta, mBeta);
           if (!mValid) return false;
           m += W[i].get_cK() * mMetric;
         }
       }
       m *= 0.125;
       mG *= 0.125;
       mH *= 0.125;
       for (i = 0; i < 8; ++i) {
         if (vertices + v_i[i] == fv[0]) {
           // free vertex, see next
           g[i] = mG;
           switch(i) {
           case 0:
             h[0] = mH;
             break;
           case 1:
             h[8] = mH;
             break;
           case 2:
             h[15] = mH;
             break;
           case 3:
             h[21] = mH;
             break;
           case 4:
             h[26] = mH;
             break;
           case 5:
             h[30] = mH;
             break;
           case 6:
             h[33] = mH;
             break;
           default:
             h[35] = mH;
             break;
           }
           break;
         }
       }
     }
     else {
       // Compute the metric and sum them together
       for (i = 0; i < 8; ++i) {
         for (j = 0; j < 4; ++j) {
           mCoords[j] = vertices[v_i[hexInd[i][j]]];
         }
         QR(mQ, mR, W[i]);
         inv(invR, mR);
         mValid = h_gdft_3(mMetric, mGrads, mHessians, mCoords, invR, mQ,
                           mAlpha, mGamma, delta, mBeta);
         if (!mValid) return false;
         m += W[i].get_cK() * mMetric;
         for (j = 0; j < 4; ++j) {
           g[hexInd[i][j]] += W[i].get_cK() * mGrads[j];
         }
         l = 0;
         for (j = 0; j < 4; ++j) {
           for (k = j; k < 4; ++k) {
             row = hexInd[i][j];
             col = hexInd[i][k];
             if (row <= col) {
               loc = 8*row - (row*(row+1)/2) + col;
               h[loc] += W[i].get_cK() * mHessians[l];
             }
             else {
               loc = 8*col - (col*(col+1)/2) + row;
               h[loc] += W[i].get_cK() * transpose(mHessians[l]);
             }
             ++l;
           }
         }
       }
       m *= 0.125;
       for (i = 0; i < 8; ++i) {
         g[i] *= 0.125;
       }
       for (i = 0; i < 36; ++i) {
         h[i] *= 0.125;
       }
       // zero out fixed elements of gradient and Hessian
       j = 0;
       for (i = 0; i < 8; ++i) {
         if (vertices + v_i[i] == fv[j]) {
           // if free vertex, see next
           ++j;
         }
         else {
           // else zero gradient entry and hessian entries.
           g[i] = 0.;
           switch(i) {
           case 0:
             h[0].zero();   h[1].zero();   h[2].zero();   h[3].zero();
             h[4].zero();   h[5].zero();   h[6].zero();   h[7].zero();
             break;
           case 1:
             h[1].zero();   h[8].zero();   h[9].zero();   h[10].zero();
             h[11].zero();  h[12].zero();  h[13].zero();  h[14].zero();
             break;
           case 2:
             h[2].zero();   h[9].zero();   h[15].zero();  h[16].zero();
             h[17].zero();  h[18].zero();  h[19].zero();  h[20].zero();
             break;
           case 3:
             h[3].zero();   h[10].zero();  h[16].zero();  h[21].zero();
             h[22].zero();  h[23].zero();  h[24].zero();  h[25].zero();
             break;
           case 4:
             h[4].zero();   h[11].zero();  h[17].zero();  h[22].zero();
             h[26].zero();  h[27].zero();  h[28].zero();  h[29].zero();
             break;
           case 5:
             h[5].zero();   h[12].zero();  h[18].zero();  h[23].zero();
             h[27].zero();  h[30].zero();  h[31].zero();  h[32].zero();
             break;
           case 6:
             h[6].zero();   h[13].zero();  h[19].zero();  h[24].zero();
             h[28].zero();  h[31].zero();  h[33].zero();  h[34].zero();
             break;
           case 7:
             h[7].zero();   h[14].zero();  h[20].zero();  h[25].zero();
             h[29].zero();  h[32].zero();  h[34].zero();  h[35].zero();
             break;
           }
         }
       }
     }
     break;
   default:
     MSQ_SETERR(err)("element type not implemented.",MsqError::NOT_IMPLEMENTED);
     return false;
   }
   return true;
 }
bool compute_element_analytical_hessian (PatchData & pd, MsqMeshEntity * element, MsqVertex * free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double & metric_value, MsqError & err) virtual
If that function is not over-riden in the concrete class, the base class function makes it default to a numerical hessian.
For parameters description, see QualityMetric::compute_element_hessian() .
Returns
true if the element is valid, false otherwise.
Reimplemented from QualityMetric.
bool evaluate_element (PatchData & , MsqMeshEntity * , double & , MsqError & err) virtual
Evaluate the metric for an element.
Reimplemented from QualityMetric.
Definition at line 43 of file QualityMetric/DFT/I_DFT.cpp.
References MsqMeshEntity::compute_corner_normals(), PatchData::get_barrier_delta(), TargetMatrix::get_cK(), PatchData::get_element_index(), MsqMeshEntity::get_element_type(), PatchData::get_vertex_array(), MsqMeshEntity::get_vertex_index_array(), Mesquite::HEXAHEDRON, i, Mesquite::inv(), I_DFT::invR, j, Mesquite::m_gdft_2(), Mesquite::m_gdft_3(), I_DFT::mAlpha, I_DFT::mBeta, I_DFT::mCoords, I_DFT::mGamma, I_DFT::mNormals, I_DFT::mQ, I_DFT::mR, Mesquite::MSQ_3RT_2_OVER_6RT_3, MSQ_ERRZERO, Mesquite::MSQ_ONE_THIRD, MSQ_SETERR, MsqError::NOT_IMPLEMENTED, Mesquite::QR(), Mesquite::QUADRILATERAL, PatchData::targetMatrices, Mesquite::TETRAHEDRON, Mesquite::TRIANGLE, I_DFT::useBarrierDelta, and MsqMeshEntity::vertex_count().
 {
   // Only works with the weighted average
   MsqError  mErr;
   MsqVertex *vertices = pd.get_vertex_array(err); MSQ_ERRZERO(err);
   EntityTopology topo = e->get_element_type();
   const size_t nv = e->vertex_count();
   const size_t *v_i = e->get_vertex_index_array();
   size_t idx = pd.get_element_index(e);
   const TargetMatrix *W = pd.targetMatrices.get_element_corner_tags(&pd, idx, err );
   MSQ_ERRZERO(err);
   // Initialize constants for the metric
   const double delta = useBarrierDelta ? pd.get_barrier_delta(err) :
     (mGamma ? 0 : 1);
   MSQ_ERRZERO(err);
   const int tetInd[4][4] = {{0, 1, 2, 3}, {1, 2, 0, 3},
                             {2, 0, 1, 3}, {3, 2, 1, 0}};
   const int hexInd[8][4] = {{0, 1, 3, 4}, {1, 2, 0, 5},
                             {2, 3, 1, 6}, {3, 0, 2, 7},
                             {4, 7, 5, 0}, {5, 4, 6, 1},
                             {6, 5, 7, 2}, {7, 6, 4, 3}};
   // Variables used for computing the metric
   double   mMetric;             // Metric value
   bool     mValid;              // Validity of the metric
   int      i, j;
   m = 0.0;
   switch(topo) {
   case TRIANGLE:
     assert(3 == nv);
     e->compute_corner_normals( mNormals, pd, err ); MSQ_ERRZERO(err);
     for (i = 0; i < 3; ++i) {
       for (j = 0; j < 3; ++j) {
         mCoords[j] = vertices[v_i[tetInd[i][j]]];
       }
       mNormals[i] *= MSQ_3RT_2_OVER_6RT_3;
       QR(mQ, mR, W[i]);
       inv(invR, mR);
       mValid = m_gdft_2(mMetric, mCoords, mNormals[i], invR, mQ,
                         mAlpha, mGamma, delta, mBeta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
     }
     m *= MSQ_ONE_THIRD;
     break;
   case QUADRILATERAL:
     assert(4 == nv);
     e->compute_corner_normals( mNormals, pd, err ); MSQ_ERRZERO(err);
     for (i = 0; i < 4; ++i) {
       for (j = 0; j < 3; ++j) {
         mCoords[j] = vertices[v_i[hexInd[i][j]]];
       }
       QR(mQ, mR, W[i]);
       inv(invR, mR);
       mValid = m_gdft_2(mMetric, mCoords, mNormals[i], invR, mQ,
                         mAlpha, mGamma, delta, mBeta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
     }
     m *= 0.25;
     break;
   case TETRAHEDRON:
     assert(4 == nv);
     for (i = 0; i < 4; ++i) {
       for (j = 0; j < 4; ++j) {
         mCoords[j] = vertices[v_i[tetInd[i][j]]];
       }
       QR(mQ, mR, W[i]);
       inv(invR, mR);
       mValid = m_gdft_3(mMetric, mCoords, invR, mQ,
                         mAlpha, mGamma, delta, mBeta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
     }
     m *= 0.25;
     break;
   case HEXAHEDRON:
     assert(8 == nv);
     for (i = 0; i < 8; ++i) {
       for (j = 0; j < 4; ++j) {
         mCoords[j] = vertices[v_i[hexInd[i][j]]];
       }
       QR(mQ, mR, W[i]);
       inv(invR, mR);
       mValid = m_gdft_3(mMetric, mCoords, invR, mQ,
                         mAlpha, mGamma, delta, mBeta);
       if (!mValid) return false;
       m += W[i].get_cK() * mMetric;
     }
     m *= 0.125;
     break;
   default:
     MSQ_SETERR(err)("element type not implemented.",MsqError::NOT_IMPLEMENTED);
     return false;
   }
   return true;
 }
bool evaluate_element (PatchData & , MsqMeshEntity * , double & , MsqError & err) virtual
Evaluate the metric for an element.
Reimplemented from QualityMetric.
double p_get_alpha () inline protected
access function to get mAlpha
Definition at line 119 of file src/QualityMetric/DFT/I_DFT.hpp.
References I_DFT::mAlpha.
       {return mAlpha;}
double p_get_alpha () inline protected
access function to get mAlpha
Definition at line 119 of file includeLinks/I_DFT.hpp.
References I_DFT::mAlpha.
       {return mAlpha;}
double p_get_beta () inline protected
access function to get mBeta
Definition at line 125 of file src/QualityMetric/DFT/I_DFT.hpp.
References I_DFT::mBeta.
       {return mBeta;}
double p_get_beta () inline protected
access function to get mBeta
Definition at line 125 of file includeLinks/I_DFT.hpp.
References I_DFT::mBeta.
       {return mBeta;}
double p_get_gamma () inline protected
access function to get mGamma
Definition at line 131 of file includeLinks/I_DFT.hpp.
References I_DFT::mGamma.
       {return mGamma;}
double p_get_gamma () inline protected
access function to get mGamma
Definition at line 131 of file src/QualityMetric/DFT/I_DFT.hpp.
References I_DFT::mGamma.
       {return mGamma;}
bool p_get_use_barrier_delta () inline protected
access function to get useBarrierDelta
Definition at line 137 of file includeLinks/I_DFT.hpp.
References I_DFT::useBarrierDelta.
       {return useBarrierDelta;}
bool p_get_use_barrier_delta () inline protected
access function to get useBarrierDelta
Definition at line 137 of file src/QualityMetric/DFT/I_DFT.hpp.
References I_DFT::useBarrierDelta.
       {return useBarrierDelta;}
void p_set_alpha (double alpha) inline protected
access function to set mAlpha
Definition at line 116 of file includeLinks/I_DFT.hpp.
References I_DFT::mAlpha.
Referenced by I_DFT_Generalized::I_DFT_Generalized(), I_DFT_InverseMeanRatio::I_DFT_InverseMeanRatio(), I_DFT_NoBarrier::I_DFT_NoBarrier(), I_DFT_StrongBarrier::I_DFT_StrongBarrier(), I_DFT_WeakBarrier::I_DFT_WeakBarrier(), and I_DFT_Generalized::set_alpha().
       {mAlpha = alpha;}
void p_set_alpha (double alpha) inline protected
access function to set mAlpha
Definition at line 116 of file src/QualityMetric/DFT/I_DFT.hpp.
References I_DFT::mAlpha.
       {mAlpha = alpha;}
void p_set_beta (double beta) inline protected
access function to set mBeta
Definition at line 122 of file src/QualityMetric/DFT/I_DFT.hpp.
References I_DFT::mBeta.
       {mBeta = beta;}
void p_set_beta (double beta) inline protected
access function to set mBeta
Definition at line 122 of file includeLinks/I_DFT.hpp.
References I_DFT::mBeta.
Referenced by I_DFT_Generalized::I_DFT_Generalized(), I_DFT_InverseMeanRatio::I_DFT_InverseMeanRatio(), I_DFT_NoBarrier::I_DFT_NoBarrier(), I_DFT_StrongBarrier::I_DFT_StrongBarrier(), I_DFT_WeakBarrier::I_DFT_WeakBarrier(), and I_DFT_Generalized::set_beta().
       {mBeta = beta;}
void p_set_gamma (double gamma) inline protected
access function to set mGamma
Definition at line 128 of file src/QualityMetric/DFT/I_DFT.hpp.
References I_DFT::mGamma.
       {mGamma = gamma;}
void p_set_gamma (double gamma) inline protected
access function to set mGamma
Definition at line 128 of file includeLinks/I_DFT.hpp.
References I_DFT::mGamma.
Referenced by I_DFT_Generalized::I_DFT_Generalized(), I_DFT_InverseMeanRatio::I_DFT_InverseMeanRatio(), I_DFT_NoBarrier::I_DFT_NoBarrier(), I_DFT_StrongBarrier::I_DFT_StrongBarrier(), I_DFT_WeakBarrier::I_DFT_WeakBarrier(), and I_DFT_Generalized::set_gamma().
       {mGamma = gamma;}
void p_set_use_barrier_delta (bool use_delta) inline protected
access function to set useBarrierDelta
Definition at line 134 of file includeLinks/I_DFT.hpp.
References I_DFT::useBarrierDelta.
Referenced by I_DFT_Generalized::I_DFT_Generalized(), I_DFT_InverseMeanRatio::I_DFT_InverseMeanRatio(), I_DFT_NoBarrier::I_DFT_NoBarrier(), I_DFT_StrongBarrier::I_DFT_StrongBarrier(), I_DFT_WeakBarrier::I_DFT_WeakBarrier(), and I_DFT_Generalized::set_use_barrier_delta().
       {useBarrierDelta = use_delta;}
void p_set_use_barrier_delta (bool use_delta) inline protected
access function to set useBarrierDelta
Definition at line 134 of file src/QualityMetric/DFT/I_DFT.hpp.
References I_DFT::useBarrierDelta.
       {useBarrierDelta = use_delta;}
Member Data Documentation
Matrix3D invR private
Definition at line 154 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), and I_DFT::evaluate_element().
Vector3D mAccGrads private
Definition at line 151 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient().
double mAlpha private
Definition at line 143 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), I_DFT::evaluate_element(), I_DFT::I_DFT(), I_DFT::p_get_alpha(), and I_DFT::p_set_alpha().
double mBeta private
Definition at line 144 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), I_DFT::evaluate_element(), I_DFT::I_DFT(), I_DFT::p_get_beta(), and I_DFT::p_set_beta().
Vector3D mCoords private
Definition at line 149 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), and I_DFT::evaluate_element().
Exponent mGamma private
Definition at line 145 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), I_DFT::evaluate_element(), I_DFT::I_DFT(), I_DFT::p_get_gamma(), and I_DFT::p_set_gamma().
Vector3D mGrads private
Definition at line 150 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), and I_DFT::compute_element_analytical_hessian().
Matrix3D mHessians private
Definition at line 152 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_hessian().
Vector3D mNormals private
Definition at line 148 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), and I_DFT::evaluate_element().
Matrix3D mQ private
Definition at line 155 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), and I_DFT::evaluate_element().
Matrix3D mR private
Definition at line 153 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), and I_DFT::evaluate_element().
bool useBarrierDelta private
Definition at line 146 of file includeLinks/I_DFT.hpp.
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), I_DFT::evaluate_element(), I_DFT::I_DFT(), I_DFT::p_get_use_barrier_delta(), and I_DFT::p_set_use_barrier_delta().
The documentation for this class was generated from the following files:
includeLinks/I_DFT.hpp
QualityMetric/DFT/I_DFT.cpp