Rocstar: Aff_transformation_rep_baseS2< FT > Class Template Reference
Aff_transformation_rep_baseS2< FT > Class Template Reference abstract
#include <Aff_transformationS2.h>
Public Member Functions
virtual ~Aff_transformation_rep_baseS2 ()
virtual PointS2< FT > transform (const PointS2< FT > &p) const =0
virtual VectorS2< FT > transform (const VectorS2< FT > &v) const =0
virtual DirectionS2< FT > transform (const DirectionS2< FT > &d) const =0
virtual Aff_transformationS2< FT > operator* (const Aff_transformation_rep_baseS2< FT > &t)=0
virtual Aff_transformationS2< FT > compose (const Translation_repS2< FT > &t) const =0
virtual Aff_transformationS2< FT > compose (const Rotation_repS2< FT > &t) const =0
virtual Aff_transformationS2< FT > compose (const Scaling_repS2< FT > &t) const =0
virtual Aff_transformationS2< FT > compose (const Aff_transformation_repS2< FT > &t) const =0
virtual Aff_transformationS2< FT > inverse () const =0
virtual bool is_even () const =0
virtual FT cartesian (int i, int j) const =0
Additional Inherited Members
Protected Member Functions inherited from Leda_like_rep
Leda_like_rep ()
virtual ~Leda_like_rep ()
Protected Attributes inherited from Leda_like_rep
int count
Detailed Description
template<class FT>
class Aff_transformation_rep_baseS2< FT >
Definition at line 84 of file Aff_transformationS2.h.
Constructor & Destructor Documentation
virtual ~Aff_transformation_rep_baseS2 () inline virtual
Definition at line 87 of file Aff_transformationS2.h.
 {}
Member Function Documentation
virtual FT cartesian (int i, int j) const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
virtual Aff_transformationS2<FT> compose (const Translation_repS2< FT > & t) const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
Referenced by Aff_transformation_repS2< FT >::operator*(), Translation_repS2< FT >::operator*(), Rotation_repS2< FT >::operator*(), and Scaling_repS2< FT >::operator*().
virtual Aff_transformationS2<FT> compose (const Rotation_repS2< FT > & t) const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
virtual Aff_transformationS2<FT> compose (const Scaling_repS2< FT > & t) const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
virtual Aff_transformationS2<FT> compose (const Aff_transformation_repS2< FT > & t) const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
virtual Aff_transformationS2<FT> inverse () const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
virtual bool is_even () const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
virtual Aff_transformationS2<FT> operator* (const Aff_transformation_rep_baseS2< FT > & t) pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
virtual PointS2<FT> transform (const PointS2< FT > & p) const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
virtual VectorS2<FT> transform (const VectorS2< FT > & v) const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
virtual DirectionS2<FT> transform (const DirectionS2< FT > & d) const pure virtual
Implemented in Scaling_repS2< FT >, Rotation_repS2< FT >, Translation_repS2< FT >, and Aff_transformation_repS2< FT >.
The documentation for this class was generated from the following file:
Aff_transformationS2.h