Rocstar: rflu_modthrustspecimpulse Module Reference
rflu_modthrustspecimpulse Module Reference
Public Member Functions
subroutine, public rflu_tsi_computeglobalthrustsi (pRegion)
subroutine, public rflu_tsi_printglobalvals (pRegion)
subroutine, public rflu_tsi_writeglobalvals (pRegion)
Private Member Functions
subroutine, private rflu_tsi_closeglobalvals (global, iPatch, iFile1, iFile2)
subroutine, private rflu_tsi_openglobalvals (global, iPatch, iFile1, iFile2)
Private Attributes
character(chrlen), private rcsidentstring = '$$'
Detailed Description
Definition at line 39 of file RFLU_ModThrustSpecImpulse.F90.
Member Function/Subroutine Documentation
subroutine, private rflu_tsi_closeglobalvals (type(t_global), pointer global, integer, intent(in) iPatch, integer, intent(in) iFile1, integer, intent(in) iFile2) private
Definition at line 103 of file RFLU_ModThrustSpecImpulse.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_tsi_writeglobalvals().
subroutine, public rflu_tsi_computeglobalthrustsi (type(t_region), pointer pRegion)
Definition at line 207 of file RFLU_ModThrustSpecImpulse.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_timestepping().
subroutine, private rflu_tsi_openglobalvals (type(t_global), pointer global, integer, intent(in) iPatch, integer, intent(out) iFile1, integer, intent(out) iFile2) private
Definition at line 350 of file RFLU_ModThrustSpecImpulse.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_tsi_writeglobalvals().
subroutine, public rflu_tsi_printglobalvals (type(t_region), pointer pRegion)
Definition at line 493 of file RFLU_ModThrustSpecImpulse.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_timestepping().
subroutine, public rflu_tsi_writeglobalvals (type(t_region), pointer pRegion)
Definition at line 593 of file RFLU_ModThrustSpecImpulse.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_tsi_closeglobalvals(), and rflu_tsi_openglobalvals().
Referenced by rflu_timestepping().
Member Data Documentation
character(chrlen), private rcsidentstring = '$$' private
Definition at line 60 of file RFLU_ModThrustSpecImpulse.F90.
The documentation for this module was generated from the following file:
RFLU_ModThrustSpecImpulse.F90