Rocstar: rflu_modausmflux Module Reference
rflu_modausmflux Module Reference
Public Member Functions
subroutine, public rflu_ausm_computeflux (pRegion)
subroutine rflu_ausm_computeflux2_mpsd (pRegion)
subroutine rflu_ausm_computeflux2_mtcp (pRegion)
subroutine rflu_ausm_computeflux2_tcp (pRegion)
Private Member Functions
subroutine rflu_ausm_fluxfunction (nx, ny, nz, nm, fs, rl, ul, vl, wl, pl, Hl, al, rr, ur, vr, wr, pr, Hr, ar, flx, vf)
subroutine rflu_ausm_computeflux1 (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModAUSMFlux.F90,v $ $Revision: 1.11 $'
Detailed Description
Definition at line 39 of file RFLU_ModAUSMFlux.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_ausm_computeflux (type(t_region), pointer pRegion)
Definition at line 88 of file RFLU_ModAUSMFlux.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_ausm_computeflux1(), rflu_ausm_computeflux2_mpsd(), rflu_ausm_computeflux2_mtcp(), and rflu_ausm_computeflux2_tcp().
Referenced by rflu_computefluxinv().
subroutine rflu_ausm_computeflux1 (type(t_region), pointer pRegion) private
Definition at line 342 of file RFLU_ModAUSMFlux.F90.
References moderror::deregisterfunction(), mixtperf_ho_cptuvw(), moderror::registerfunction(), rflu_ausm_fluxfunction(), and rflu_centralfirstpatch().
Referenced by rflu_ausm_computeflux().
subroutine rflu_ausm_computeflux2_mpsd (type(t_region), pointer pRegion)
Definition at line 555 of file RFLU_ModAUSMFlux.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), mixtperf_c_grt(), mixtperf_g_cpr(), mixtperf_ho_cptuvw(), mixtperf_m_r(), mixtperf_r_m(), mixtperf_t_dpr(), moderror::registerfunction(), rflu_ausm_fluxfunction(), rflu_centralfirstpatch(), and rflu_centralsecondpatch().
Referenced by rflu_ausm_computeflux().
subroutine rflu_ausm_computeflux2_mtcp (type(t_region), pointer pRegion)
Definition at line 932 of file RFLU_ModAUSMFlux.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), mixtperf_c_grt(), mixtperf_g_cpr(), mixtperf_ho_cptuvw(), mixtperf_r_m(), mixtperf_t_dpr(), moderror::registerfunction(), rflu_ausm_fluxfunction(), rflu_centralfirstpatch(), and rflu_centralsecondpatch().
Referenced by rflu_ausm_computeflux().
subroutine rflu_ausm_computeflux2_tcp (type(t_region), pointer pRegion)
Definition at line 1270 of file RFLU_ModAUSMFlux.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), Color::g(), mixtperf_c_grt(), mixtperf_ho_cptuvw(), mixtperf_r_cpg(), mixtperf_t_dpr(), moderror::registerfunction(), rflu_ausm_fluxfunction(), rflu_centralfirstpatch(), and rflu_centralsecondpatch().
Referenced by rflu_ausm_computeflux().
subroutine rflu_ausm_fluxfunction (real(rfreal), intent(in) nx, real(rfreal), intent(in) ny, real(rfreal), intent(in) nz, real(rfreal), intent(in) nm, real(rfreal), intent(in) fs, real(rfreal), intent(in) rl, real(rfreal), intent(in) ul, real(rfreal), intent(in) vl, real(rfreal), intent(in) wl, real(rfreal), intent(in) pl, real(rfreal), intent(in) Hl, real(rfreal), intent(in) al, real(rfreal), intent(in) rr, real(rfreal), intent(in) ur, real(rfreal), intent(in) vr, real(rfreal), intent(in) wr, real(rfreal), intent(in) pr, real(rfreal), intent(in) Hr, real(rfreal), intent(in) ar, real(rfreal), dimension(5), intent(out) flx, real(rfreal), dimension(3), intent(out) vf) private
Definition at line 230 of file RFLU_ModAUSMFlux.F90.
Referenced by rflu_ausm_computeflux1(), rflu_ausm_computeflux2_mpsd(), rflu_ausm_computeflux2_mtcp(), and rflu_ausm_computeflux2_tcp().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModAUSMFlux.F90,v $ $Revision: 1.11 $' private
Definition at line 59 of file RFLU_ModAUSMFlux.F90.
The documentation for this module was generated from the following file:
RFLU_ModAUSMFlux.F90