Rocstar: Element_node_vectors_k< Value > Class Template Reference
Element_node_vectors_k< Value > Class Template Reference
#include <Element_accessors.h>
Public Member Functions
Element_node_vectors_k ()
void set (Value *p, Element_node_enumerator &ene, int strd)
void set (Attribute *a, Element_node_enumerator &ene)
Value & operator() (int i, int j) const
Value & operator() (int i) const
Value & operator[] (int i) const
Public Member Functions inherited from Element_node_vectors_k_const< Value >
Element_node_vectors_k_const ()
Default constructor.
void set (const Value *p, Element_node_enumerator &ene, int strd)
initialize the accessor with a pointer and a specific stride.
void set (const Attribute *a, Element_node_enumerator &ene)
initialize the accessor from an attribute assiciated with a pane.
const Value & operator() (int i, int j) const
const Value & operator() (int i) const
const Value & operator[] (int i) const
Private Types
typedef
Element_node_vectors_k_const
< Value > Base
Additional Inherited Members
Public Types inherited from Element_node_vectors_k_const< Value >
enum { MAX_NODES =9 }
typedef unsigned int Size
Protected Attributes inherited from Element_node_vectors_k_const< Value >
const Attribute * _attr
union {
int _offsets [MAX_NODES]
const Value * _vs [MAX_NODES]
};
Detailed Description
template<class Value>
class Element_node_vectors_k< Value >
Definition at line 295 of file Element_accessors.h.
Member Typedef Documentation
typedef Element_node_vectors_k_const<Value> Base private
Definition at line 296 of file Element_accessors.h.
Constructor & Destructor Documentation
Element_node_vectors_k () inline
Definition at line 298 of file Element_accessors.h.
 : Base() {}
Member Function Documentation
Value& operator() (int i, int j) const inline
Definition at line 306 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::operator()().
   { return const_cast<Value&>(Base::operator()(i,j)); }
Value& operator() (int i) const inline
Definition at line 309 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::operator()().
   { return const_cast<Value&>(Base::operator()(i,0)); }
Value& operator[] (int i) const inline
Definition at line 312 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::operator()().
   { return const_cast<Value&>(Base::operator()(i,0)); }
void set (Value * p, Element_node_enumerator & ene, int strd) inline
Definition at line 300 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::set().
Referenced by Window_manifold_2::elements_to_nodes().
   { Base::set( p, ene, strd); }
void set (Attribute * a, Element_node_enumerator & ene) inline
Definition at line 303 of file Element_accessors.h.
References Element_node_vectors_k_const< Value >::set().
   { Base::set( a, ene); }
The documentation for this class was generated from the following file:
Element_accessors.h