Rocstar: Mesh::Partition Class Reference
Mesh::Partition Class Reference
#include <PMesh.H>
Public Member Functions
Partition ()
int Read (const std::string &meshname, int id)
int Read (const std::string &MeshName, IRAD::Comm::CommunicatorObject &comm, bool allow_n2m, std::ostream &ErrOut)
MeshUtilityObject & Mesh ()
const MeshUtilityObject & Mesh () const
PartInfo & Info ()
const PartInfo & Info () const
std::vector< Border > & Borders ()
const std::vector< Border > & Borders () const
IRAD::Comm::CommunicatorObject * CommunicatorPtr ()
int GetBorderElements (std::vector< Mesh::IndexType > &be) const
Public Attributes
MeshUtilityObject _mesh
PartInfo _info
std::vector< Border > _borders
Private Attributes
IRAD::Comm::CommunicatorObject * _communicator
Detailed Description
Definition at line 95 of file PMesh.H.
Constructor & Destructor Documentation
Partition () inline
Definition at line 99 of file PMesh.H.
 : _communicator(NULL), _mesh(),_info(),_borders() {};
Member Function Documentation
std::vector<Border>& Borders () inline
Definition at line 114 of file PMesh.H.
References _borders.
 { return(_borders); };
const std::vector<Border>& Borders () const inline
Definition at line 115 of file PMesh.H.
References _borders.
 { return(_borders); };
IRAD::Comm::CommunicatorObject* CommunicatorPtr () inline
Definition at line 116 of file PMesh.H.
References _communicator.
 { return(_communicator); };
int GetBorderElements (std::vector< Mesh::IndexType > & be) const
Definition at line 13 of file PMesh.C.
References _info, _mesh, Mesh::MeshUtilityObject::ENDUAL, Mesh::MeshUtilityObject::GetCon(), Mesh::PartInfo::nshared, Mesh::MeshUtilityObject::NumberOfElements(), and Mesh::MeshUtilityObject::NumberOfNodes().
   {
     std::list<Mesh::IndexType> belist;
     Mesh::IndexType number_of_nodes = _mesh.NumberOfNodes();
     Mesh::IndexType number_of_elements = _mesh.NumberOfElements();
     std::vector<bool> element_processed(number_of_elements,false);
     Mesh::IndexType nvolume_nodes = number_of_nodes - _info.nshared;
     const Mesh::Connectivity &dc = _mesh.GetCon(MeshUtilityObject::ENDUAL);
     for(Mesh::IndexType nn = nvolume_nodes;nn < number_of_nodes;nn++){
       std::vector<Mesh::IndexType>::const_iterator ei =
         dc[nn].begin();
       while(ei != dc[nn].end()){
         if(!element_processed[*ei-1]){
           element_processed[*ei-1] = true; // cheap uniquity
           belist.push_back(*ei);
         }
         ei++;
       }
     }
     belist.sort();
     std::list<Mesh::IndexType>::iterator beli = belist.begin();
     be.resize(belist.size());
     std::vector<Mesh::IndexType>::iterator bei = be.begin();
     while(bei != be.end())
       *bei++ = *beli++;
     return(0);
   };
PartInfo& Info () inline
Definition at line 112 of file PMesh.H.
References _info.
 { return (_info); };
const PartInfo& Info () const inline
Definition at line 113 of file PMesh.H.
References _info.
 { return(_info); };
MeshUtilityObject& Mesh () inline
Definition at line 110 of file PMesh.H.
References _mesh.
 { return (_mesh); };
const MeshUtilityObject& Mesh () const inline
Definition at line 111 of file PMesh.H.
References _mesh.
 { return (_mesh); };
int Read (const std::string & meshname, int id)
Definition at line 127 of file PMesh.C.
References _borders, _info, _mesh, Mesh::MeshUtilityObject::ECon(), Mesh::PartInfo::nborder, Mesh::MeshUtilityObject::NC(), Mesh::PartInfo::nelem, Mesh::PartInfo::nlocal, Mesh::PartInfo::nnodes, Mesh::PartInfo::nown, Mesh::PartInfo::npart, Mesh::PartInfo::nshared, Mesh::PartInfo::part, Mesh::Connectivity::ShrinkWrap(), and Mesh::Connectivity::Sync().
   {
     // rank = id - 1
     std::ifstream Inf;
     std::ostringstream FNOstr;
     if(id > 0){
       FNOstr << MeshName << "." << id << ".info";
       Inf.open(FNOstr.str().c_str());
       if(!Inf)
         return(2);
       Inf >> _info.npart >> _info.part >> _info.nelem >> _info.nnodes >> _info.nborder >> _info.nshared >> _info.nown;
       Inf.close();
       _info.nlocal = _info.nnodes - _info.nshared + _info.nown;
       FNOstr.str("");
     }
     _info.nborder = 0;
     _info.nshared = 0;
     _info.nown = 0;
     if(id > 0)
       FNOstr << MeshName << "." << id << ".pmesh";
     else
       FNOstr << MeshName;
     Inf.open(FNOstr.str().c_str());
     if(!Inf)
       return(3);
     //    Inf >> _nc;
     //    Inf >> _ec;
     //    _ec.ShrinkWrap();
     //    _ec.Sync();
     Inf >> _mesh.NC();
     Inf >> _mesh.ECon();
     _mesh.ECon().ShrinkWrap();
     _mesh.ECon().Sync();
     if(id > 0){
       Inf >> _info.nborder;
       _borders.resize(_info.nborder);
       for(Mesh::IndexType nn = 0;nn < _info.nborder;nn++){
         Mesh::IndexType nrecv = 0;
         Mesh::IndexType nsend = 0;
         Inf >> _borders[nn].rpart >> nrecv >> nsend;
         for(Mesh::IndexType ii = 0;ii < nrecv;ii++){
           Mesh::IndexType nodeid = 0;
           Inf >> nodeid;
           _borders[nn].nrecv.push_back(nodeid);
           Inf >> nodeid;
         }
         for(Mesh::IndexType ii = 0;ii < nsend;ii++){
           Mesh::IndexType nodeid = 0;
           Inf >> nodeid;
           _borders[nn].nsend.push_back(nodeid);
           Inf >> nodeid;
         }
       }
     }
     Inf.close();
     return(0);
   };
int Read (const std::string & MeshName, IRAD::Comm::CommunicatorObject & comm, bool allow_n2m, std::ostream & ErrOut)
Definition at line 41 of file PMesh.C.
References _borders, _communicator, _info, _mesh, Mesh::MeshUtilityObject::ECon(), Mesh::PartInfo::nborder, Mesh::MeshUtilityObject::NC(), Mesh::PartInfo::nelem, Mesh::PartInfo::nlocal, Mesh::PartInfo::nnodes, Mesh::PartInfo::nown, Mesh::PartInfo::npart, Mesh::PartInfo::nshared, Mesh::MeshUtilityObject::NumberOfElements(), Mesh::MeshUtilityObject::NumberOfNodes(), Mesh::PartInfo::part, rank, and Mesh::Connectivity::ShrinkWrap().
   {
     unsigned int nproc = comm.Size();
     unsigned int rank = comm.Rank();
     unsigned int id = rank + 1;
     // Read the partitioning info
     if(nproc > 1){
       std::ifstream InfoInf;
       std::ostringstream FNOstr;
       FNOstr << MeshName << "." << id << ".info";
       InfoInf.open(FNOstr.str().c_str());
       if(!InfoInf){
         comm.SetErr(1);
       }
       if(comm.Check()){
         ErrOut << "Partition::Read Could not find partition info for " << MeshName;
         return(1);
       }
       InfoInf >> _info.npart >> _info.part >> _info.nelem >> _info.nnodes >> _info.nborder
               >> _info.nshared >> _info.nown;
       if(_info.npart != nproc && !allow_n2m){
         comm.SetErr(1);
       }
       if(comm.Check()){
         ErrOut << "Partition::Read " << MeshName << " has partition/processor mismatch: ("
                << _info.npart << "/" << nproc << ").\n";
         return(1);
       }
       _info.nlocal = _info.nnodes  - _info.nshared + _info.nown;
       InfoInf.close();
     }
     else{
       _info.nborder = 0;
       _info.nshared = 0;
     }
     // done reading partition info
     std::ifstream Inf;
     std::ostringstream Ostr;
     Ostr << MeshName;
     if(nproc > 1)
       Ostr << "." << id << ".pmesh";
     else
       Ostr << ".mesh";
     Inf.open(Ostr.str().c_str());
     // Don't blink or you'll miss the mesh actually being loaded here.
     Inf >> _mesh.NC() >> _mesh.ECon();
     _mesh.ECon().ShrinkWrap();
     //    Inf >> _nc >> _ec;
     //    _ec.ShrinkWrap();
     // done loading actual mesh
     //    Mesh::IndexType number_of_nodes    = _nc.Size();
     //    Mesh::IndexType number_of_elements = _ec.Nelem();
     Mesh::IndexType number_of_nodes    = _mesh.NumberOfNodes();
     Mesh::IndexType number_of_elements = _mesh.NumberOfElements();
     if(nproc == 1){
       _info.nnodes = number_of_nodes;
       _info.nown   = 0;
       _info.nlocal = number_of_nodes;
       _info.nelem  = number_of_elements;
     }
     else{
       Inf >> _info.nborder;
       _borders.resize(_info.nborder);
       for(Mesh::IndexType nn = 0;nn < _info.nborder;nn++){
         Mesh::IndexType nrecv = 0;
         Mesh::IndexType nsend = 0;
         Inf >> _borders[nn].rpart >> nrecv >> nsend;
         _borders[nn].nrecv.resize(nrecv);
         for(Mesh::IndexType ii = 0;ii < nrecv;ii++){
           Mesh::IndexType nodeid = 0;
           Inf >> _borders[nn].nrecv[ii] >> nodeid;
         }
         _borders[nn].nsend.resize(nsend);
         for(Mesh::IndexType ii = 0;ii < nsend;ii++){
           Mesh::IndexType nodeid = 0;
           Inf >> _borders[nn].nsend[ii] >> nodeid;
         }
       }
     }
     Inf.close();
     _communicator = &comm;
     return(0);
   }
Member Data Documentation
std::vector<Border> _borders
Definition at line 104 of file PMesh.H.
Referenced by Borders(), and Read().
IRAD::Comm::CommunicatorObject* _communicator private
Definition at line 97 of file PMesh.H.
Referenced by CommunicatorPtr(), and Read().
PartInfo _info
Definition at line 103 of file PMesh.H.
Referenced by GetBorderElements(), Info(), and Read().
MeshUtilityObject _mesh
Definition at line 99 of file PMesh.H.
Referenced by GetBorderElements(), Mesh(), and Read().
The documentation for this class was generated from the following files:
PMesh.H
PMesh.C