Rocstar: rflu_modgeometrytools Module Reference
rflu_modgeometrytools Module Reference
Public Member Functions
subroutine, public rflu_computelinecellxsectfast (pRegion, xLoc, yLoc, zLoc, ex, ey, ez, icg, distOut, iPatchOut, ifgOut)
subroutine, public rflu_computelinecellxsectsafe (pRegion, xLoc, yLoc, zLoc, ex, ey, ez, icg, distOut, iPatchOut, ifgOut)
logical function, public rflu_testinboundbox (global, xLoc, yLoc, zLoc, xMin, xMax, yMin, yMax, zMin, zMax)
logical function, public rflu_testvectorcartaxisaligned (global, dr, dir)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModGeometryTools.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file RFLU_ModGeometryTools.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_computelinecellxsectfast (type(t_region), pointer pRegion, real(rfreal), intent(inout) xLoc, real(rfreal), intent(inout) yLoc, real(rfreal), intent(inout) zLoc, real(rfreal), intent(in) ex, real(rfreal), intent(in) ey, real(rfreal), intent(in) ez, integer, intent(in) icg, real(rfreal), intent(out) distOut, integer, intent(out) iPatchOut, integer, intent(out) ifgOut)
Definition at line 106 of file RFLU_ModGeometryTools.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), max(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), and rflu_modbilinearpatch::rflu_blin_computexsectline().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellstrajfast().
subroutine, public rflu_computelinecellxsectsafe (type(t_region), pointer pRegion, real(rfreal), intent(inout) xLoc, real(rfreal), intent(inout) yLoc, real(rfreal), intent(inout) zLoc, real(rfreal), intent(in) ex, real(rfreal), intent(in) ey, real(rfreal), intent(in) ez, integer, intent(in) icg, real(rfreal), intent(out) distOut, integer, intent(out) iPatchOut, integer, intent(out) ifgOut)
Definition at line 378 of file RFLU_ModGeometryTools.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), and rflu_modbilinearpatch::rflu_blin_computexsectline().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellstrajsafe().
logical function, public rflu_testinboundbox (type(t_global), pointer global, real(rfreal), intent(in) xLoc, real(rfreal), intent(in) yLoc, real(rfreal), intent(in) zLoc, real(rfreal), intent(in) xMin, real(rfreal), intent(in) xMax, real(rfreal), intent(in) yMin, real(rfreal), intent(in) yMax, real(rfreal), intent(in) zMin, real(rfreal), intent(in) zMax)
Definition at line 665 of file RFLU_ModGeometryTools.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), and rflu_modprobes::rflu_findprobecells().
logical function, public rflu_testvectorcartaxisaligned (type(t_global), pointer global, real(rfreal), dimension(xcoord:zcoord), intent(inout) dr, integer, intent(in) dir)
Definition at line 746 of file RFLU_ModGeometryTools.F90.
References moderror::deregisterfunction(), vector3d::dir(), and moderror::registerfunction().
Referenced by rflu_modstencilsutils::rflu_addcelllayer_1d_g(), and rflu_modstencilscells::rflu_buildc2cstencilbasic_1d().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModGeometryTools.F90,v $ $Revision: 1.5 $' private
Definition at line 62 of file RFLU_ModGeometryTools.F90.
The documentation for this module was generated from the following file:
RFLU_ModGeometryTools.F90