Rocstar: Function Class Reference
Function Class Reference
A Function object corresponds to a function member of a window.
#include <Function.h>
Public Types
enum { MAX_NUMARG =14 }
enum { F_FUNC, C_FUNC, CPP_MEMBER }
Public Member Functions
Constructors
Function ()
Default constructor.
Function (Func_ptr p, const std::string &s, const int *t, Attribute *a, bool b=false)
Create a function object with physical address p.
Function (Member_func_ptr p, const std::string &s, const int *t, Attribute *a)
Access methods
Func_ptr pointer ()
Get physical address of the function.
int num_of_args () const
Get the number of arguments.
bool is_input (int i) const
Check whether the ith argument is for input.
bool is_output (int i) const
Check whether the ith argument is for output.
bool is_literal (int i) const
Check whether the ith argument is literal type.
bool is_optional (int i) const
Check whether the ith argument is optional.
bool is_rawdata (int i) const
Check whether the ith argument is raw.
bool is_metadata (int i) const
Check whether the ith argument is meta.
bool is_fortran () const
COM_Type data_type (int i) const
char intent (int i) const
void set_communicator (MPI_Comm c)
MPI_Comm communicator () const
Attribute * attribute ()
Invocation
void operator() ()
void operator() (void *a1)
void operator() (void *a1, void *a2)
void operator() (void *a1, void *a2, void *a3)
void operator() (void *a1, void *a2, void *a3, void *a4)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5, void *a6)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8, void *a9)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8, void *a9, void *a10)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8, void *a9, void *a10, void *a11)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8, void *a9, void *a10, void *a11, void *a12)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8, void *a9, void *a10, void *a11, void *a12, void *a13)
void operator() (void *a1, void *a2, void *a3, void *a4, void *a5, void *a6, void *a7, void *a8, void *a9, void *a10, void *a11, void *a12, void *a13, void *a14)
void operator() (int n, void **ps) throw (COM_exception)
invoke with an array of arguments
Private Member Functions
void validate_object (void *a1)
Private Attributes
union {
Func_ptr _ptr
Pointer to a regular function.
Member_func_ptr _mem_ptr
Pointer to a member function.
};
std::string _intents
Intention of the argument.
std::vector< COM_Type > _types
Data type of the arguments.
Attribute * _attr
Member function.
MPI_Comm _comm
int _ftype
Indicate the type of the function.
Detailed Description
A Function object corresponds to a function member of a window.
It can take up to MAX_NUMARG arguments of void* type (excluding the implicit arguments) and return no value.
Definition at line 49 of file Function.h.
Member Enumeration Documentation
anonymous enum
Enumerator
MAX_NUMARG
Definition at line 51 of file Function.h.
 { MAX_NUMARG=14};
anonymous enum
Enumerator
F_FUNC
C_FUNC
CPP_MEMBER
Definition at line 52 of file Function.h.
 { F_FUNC, C_FUNC, CPP_MEMBER};
Constructor & Destructor Documentation
Function () inline
Default constructor.
Definition at line 58 of file Function.h.
              : _ptr(NULL), _attr(NULL), _comm(MPI_COMM_NULL),
                _ftype(C_FUNC) {}
Function (Func_ptr p, const std::string & s, const int * t, Attribute * a, bool b = false) inline
Create a function object with physical address p.
Parameters
p physical address of the function.
s the intentions of the arguments. Its length indicates the number of arguments. Each entry indicates the intention of its corresponding argument: 'i'/'I' for input-only; 'o'/'O' for output-only; 'b'/'B' for input and output. Uppercase indicates optional arguments.
t the data types of the arguments. If it is COM_METADATA, then the argument should be a pointer to an attribute. If it is COM_RAWDATA, then argument should be the physical address of the values of an attribute. Otherwise, it is literal type and the argument should be a pointer to corresponding data type.
a attribute with which a member functions is associated.
b whether the function is a Fortran subroutine
Definition at line 77 of file Function.h.
     : _ptr(p), _intents(s), _types( t, t+s.size()), _attr(a),
       _comm(MPI_COMM_NULL), _ftype( b?F_FUNC:C_FUNC) {}
Function (Member_func_ptr p, const std::string & s, const int * t, Attribute * a) inline
Definition at line 81 of file Function.h.
     : _mem_ptr(p), _intents(s), _types( t, t+s.size()), _attr(a),
       _comm(MPI_COMM_NULL),_ftype(CPP_MEMBER) {}
Member Function Documentation
Attribute* attribute () inline
Definition at line 121 of file Function.h.
References _attr.
Referenced by Roccom_base::call_function().
 { return _attr; }
MPI_Comm communicator () const inline
Definition at line 119 of file Function.h.
References _comm.
Referenced by rflo_initflowsolver(), rflu_modrocstaradmin::rflu_genx_createwindows(), rflu_modrocstario::rflu_genx_putdataflow(), rflu_modrocstario::rflu_genx_putdatagspeedssurf(), rflu_modrocstario::rflu_genx_putdatagspeedsvol(), rflu_modrocstario::rflu_genx_putdatainterf(), rflu_modrocstario::rflu_genx_putgridsurf(), rflu_modrocstario::rflu_genx_putgridvol(), rflu_modrocstario::rflu_genx_readwindow(), rflu_modrocstaradmin::rflu_genx_storecommunicator(), rflu_initflowsolver(), and rflu_initglobal().
 { return _comm; }
COM_Type data_type (int i) const inline
Definition at line 115 of file Function.h.
References _types, and i.
Referenced by Roccom_base::call_function().
 { return _types[i]; }
char intent (int i) const inline
Definition at line 116 of file Function.h.
References _intents, and i.
Referenced by Roccom_base::call_function().
 { return _intents[i]; }
bool is_fortran () const inline
Definition at line 114 of file Function.h.
References _ftype, and F_FUNC.
Referenced by Roccom_base::call_function().
 { return _ftype==F_FUNC; }
bool is_input (int i) const inline
Check whether the ith argument is for input.
Definition at line 95 of file Function.h.
References _intents, and i.
   { return _intents[i]!='o' && _intents[i]!='O'; }
bool is_literal (int i) const inline
Check whether the ith argument is literal type.
Definition at line 101 of file Function.h.
References _types, COM_F90POINTER, COM_METADATA, COM_RAWDATA, and i.
Referenced by Roccom_base::call_function().
   { return _types[i] != COM_RAWDATA &&  _types[i] != COM_F90POINTER &&
       _types[i] != COM_METADATA; }
bool is_metadata (int i) const inline
Check whether the ith argument is meta.
Definition at line 111 of file Function.h.
References _types, COM_METADATA, and i.
   { return _types[i] == COM_METADATA; }
bool is_optional (int i) const inline
Check whether the ith argument is optional.
Definition at line 105 of file Function.h.
References _intents, and i.
Referenced by Roccom_base::call_function().
   { return _intents[i]>='A' &&  _intents[i]<='Z'; }
bool is_output (int i) const inline
Check whether the ith argument is for output.
Definition at line 98 of file Function.h.
References _intents, and i.
   { return _intents[i]!='i' && _intents[i]!='I'; }
bool is_rawdata (int i) const inline
Check whether the ith argument is raw.
Definition at line 108 of file Function.h.
References _types, COM_F90POINTER, COM_RAWDATA, and i.
Referenced by Roccom_base::call_function().
   { return _types[i] == COM_RAWDATA || _types[i] == COM_F90POINTER; }
int num_of_args () const inline
Get the number of arguments.
Definition at line 93 of file Function.h.
References _intents.
Referenced by Roccom_base::call_function(), and Roccom_base::get_num_arguments().
 { return _intents.size(); }
void operator() () inline
Definition at line 129 of file Function.h.
References _ptr.
Referenced by operator()().
 { _ptr(); }
void operator() (void * a1) inline
Definition at line 131 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func1)(void*);
       (*(Func1)(_ptr))(a1);
     }
     else {
       typedef void(COM_Object::*Member_Func1)();
       Member_Func1 f = (Member_Func1)_mem_ptr;
       validate_object( a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)();
     }
   }
void operator() (void * a1, void * a2) inline
Definition at line 144 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func2)(void*,void*);
       (*(Func2)(_ptr))(a1,a2);
     }
     else {
       typedef void(COM_Object::*Member_Func2)(void*);
       Member_Func2 f = (Member_Func2)_mem_ptr;
       validate_object(a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2);
     }
   }
void operator() (void * a1, void * a2, void * a3) inline
Definition at line 157 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func3)(void*,void*,void*);
       (*(Func3)(_ptr))(a1,a2,a3);
     }
     else {
       typedef void(COM_Object::*Member_Func3)(void*,void*);
       Member_Func3 f = (Member_Func3)_mem_ptr;
       validate_object(a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3);
     }
   }
void operator() (void * a1, void * a2, void * a3, void * a4) inline
Definition at line 171 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func4)(void*,void*,void*,void*);
       (*(Func4)(_ptr))(a1,a2,a3,a4);
     }
     else {
       typedef void(COM_Object::*Member_Func4)(void*,void*,void*);
       Member_Func4 f = (Member_Func4)_mem_ptr;
       validate_object( a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4);
     }
   }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5) inline
Definition at line 185 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func5)(void*,void*,void*,void*,void*);
       (*(Func5)(_ptr))(a1,a2,a3,a4,a5);
     }
     else {
       typedef void(COM_Object::*Member_Func5)(void*,void*,void*,void*);
       Member_Func5 f = (Member_Func5)_mem_ptr;
       validate_object( a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5);
     }
   }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5, void * a6) inline
Definition at line 199 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func6)(void*,void*,void*,void*,void*,void*);
       (*(Func6)(_ptr))(a1,a2,a3,a4,a5,a6);
     }
     else {
       typedef void(COM_Object::*Member_Func6)(void*,void*,void*,void*,void*);
       Member_Func6 f = (Member_Func6)_mem_ptr;
       validate_object( a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5,a6);
     }
   }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5, void * a6, void * a7) inline
Definition at line 214 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func7)(void*,void*,void*,void*,void*,void*,void*);
       (*(Func7)(_ptr))(a1,a2,a3,a4,a5,a6,a7);
     }
     else {
       typedef void(COM_Object::*Member_Func7)(void*,void*,void*,void*,
                                               void*,void*);
       Member_Func7 f = (Member_Func7)_mem_ptr;
       validate_object( a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5,a6,a7);
     }
   }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5, void * a6, void * a7, void * a8) inline
Definition at line 230 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func8)(void*,void*,void*,void*,void*,void*,void*,void*);
       (*(Func8)(_ptr))(a1,a2,a3,a4,a5,a6,a7,a8);
     }
     else {
       typedef void(COM_Object::*Member_Func8)(void*,void*,void*,void*,
                                               void*,void*,void*);
       Member_Func8 f = (Member_Func8)_mem_ptr;
       validate_object( a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5,a6,a7,a8);
     }
   }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5, void * a6, void * a7, void * a8, void * a9) inline
Definition at line 246 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func9)(void*,void*,void*,void*,void*,void*,
                            void*,void*,void*);
       (*(Func9)(_ptr))(a1,a2,a3,a4,a5,a6,a7,a8,a9);
     }
     else {
       typedef void(COM_Object::*Member_Func9)(void*,void*,void*,void*,void*,
                                               void*,void*,void*);
       Member_Func9 f = (Member_Func9)_mem_ptr;
       validate_object( a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5,a6,a7,a8,a9);
     }
   }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5, void * a6, void * a7, void * a8, void * a9, void * a10) inline
Definition at line 263 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func10)(void*,void*,void*,void*,void*,void*,
                             void*,void*,void*,void*);
       (*(Func10)(_ptr))(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10);
     }
     else {
       typedef void(COM_Object::*Member_Func10)(void*,void*,void*,void*,void*,
                                                void*,void*,void*,void*);
       Member_Func10 f = (Member_Func10)_mem_ptr;
       validate_object( a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5,a6,a7,a8,a9,a10);
     }
   }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5, void * a6, void * a7, void * a8, void * a9, void * a10, void * a11) inline
Definition at line 280 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
{
     if ( _ftype!=CPP_MEMBER) {
       typedef void(*Func11)(void*,void*,void*,void*,void*,void*,
                             void*,void*,void*,void*,void*);
       (*(Func11)(_ptr))(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11);
     }
     else {
       typedef void(COM_Object::*Member_Func11)(void*,void*,void*,void*,void*,
                                                void*,void*,void*,void*,void*);
       Member_Func11 f = (Member_Func11)_mem_ptr;
       validate_object( a1);
       (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5,a6,a7,a8,a9,a10,a11);
     }
   }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5, void * a6, void * a7, void * a8, void * a9, void * a10, void * a11, void * a12) inline
Definition at line 297 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
   {
                 if ( _ftype!=CPP_MEMBER) {
                         typedef void(*Func11)(void*,void*,void*,void*,void*,void*,
                                         void*,void*,void*,void*,void*,void*);
                         (*(Func11)(_ptr))(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12);
                 }
                 else {
                         typedef void(COM_Object::*Member_Func11)(void*,void*,void*,void*,void*,
                                                                  void*,void*,void*,void*,void*,void*);
                         Member_Func11 f = (Member_Func11)_mem_ptr;
                         validate_object( a1);
                         (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12);
                 }
         }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5, void * a6, void * a7, void * a8, void * a9, void * a10, void * a11, void * a12, void * a13) inline
Definition at line 317 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
   {
                         if ( _ftype!=CPP_MEMBER) {
                                 typedef void(*Func11)(void*,void*,void*,void*,void*,void*,
                                                 void*,void*,void*,void*,void*,void*,void*);
                                 (*(Func11)(_ptr))(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13);
                         }
                         else {
                                 typedef void(COM_Object::*Member_Func11)(void*,void*,void*,void*,void*,
                                                                          void*,void*,void*,void*,void*,void*,void*);
                                 Member_Func11 f = (Member_Func11)_mem_ptr;
                                 validate_object( a1);
                                 (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13);
                         }
         }
void operator() (void * a1, void * a2, void * a3, void * a4, void * a5, void * a6, void * a7, void * a8, void * a9, void * a10, void * a11, void * a12, void * a13, void * a14) inline
Definition at line 336 of file Function.h.
References _ftype, _mem_ptr, _ptr, CPP_MEMBER, and validate_object().
         {
                         if ( _ftype!=CPP_MEMBER) {
                                 typedef void(*Func11)(void*,void*,void*,void*,void*,void*,
                                                 void*,void*,void*,void*,void*,void*,void*,void*);
                                 (*(Func11)(_ptr))(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14);
                         }
                         else {
                                 typedef void(COM_Object::*Member_Func11)(void*,void*,void*,void*,void*,
                                                                          void*,void*,void*,void*,void*,void*,void*,void*);
                                 Member_Func11 f = (Member_Func11)_mem_ptr;
                                 validate_object( a1);
                                 (reinterpret_cast<COM_Object*>(a1)->*f)(a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14);
                         }
         }
void operator() (int n, void ** ps) throw (COM_exception) inline
invoke with an array of arguments
Definition at line 357 of file Function.h.
References COM_ERR_TOO_MANY_ARGS, and operator()().
   {
         switch ( n)
         {
                         case 0: operator()(); break;
                         case 1: operator()( ps[0] ); break;
                         case 2: operator()( ps[0],ps[1] ); break;
                         case 3: operator()( ps[0],ps[1],ps[2] ); break;
                         case 4: operator()( ps[0],ps[1],ps[2],ps[3] ); break;
                         case 5: operator()( ps[0],ps[1],ps[2],ps[3],ps[4] ); break;
                         case 6: operator()( ps[0],ps[1],ps[2],ps[3],ps[4],ps[5] ); break;
                         case 7: operator()( ps[0],ps[1],ps[2],ps[3],ps[4],ps[5],ps[6] ); break;
                         case 8: operator()( ps[0],ps[1],ps[2],ps[3],ps[4],ps[5],ps[6],ps[7] ); break;
                         case 9: operator()( ps[0],ps[1],ps[2],ps[3],ps[4],ps[5],ps[6],ps[7],ps[8] ); break;
                         case 10:operator()( ps[0],ps[1],ps[2],ps[3],ps[4],ps[5],ps[6],ps[7],ps[8],ps[9] ); break;
                         case 11:operator()( ps[0],ps[1],ps[2],ps[3],ps[4],ps[5],ps[6],ps[7],ps[8],ps[9],ps[10] ); break;
                         case 12:operator()( ps[0],ps[1],ps[2],ps[3],ps[4],ps[5],ps[6],ps[7],ps[8],ps[9],ps[10],ps[11] ); break;
                         case 13:operator()( ps[0],ps[1],ps[2],ps[3],ps[4],ps[5],ps[6],ps[7],ps[8],ps[9],ps[10],ps[11],ps[12] ); break;
                         case 14:operator()( ps[0],ps[1],ps[2],ps[3],ps[4],ps[5],ps[6],ps[7],ps[8],ps[9],ps[10],ps[11],ps[12],ps[13] ); break;
                         default:  throw COM_exception(COM_ERR_TOO_MANY_ARGS);
     }
   }
Func_ptr pointer () inline
Get physical address of the function.
Definition at line 91 of file Function.h.
 { return _ptr; }
void set_communicator (MPI_Comm c) inline
Definition at line 118 of file Function.h.
References _comm.
Referenced by Roccom_base::set_profiling_barrier().
 { _comm = c; }
void validate_object (void * a1) inline private
Definition at line 384 of file Function.h.
References COM_assertion_msg.
Referenced by operator()().
{
     int ierr = reinterpret_cast<COM_Object*>(a1)->validate_object(a1);
     switch ( ierr) {
     case 1: COM_assertion_msg( ierr==0, "Invalid pointer after casting");
     case 3: COM_assertion_msg( ierr==0, "Invalid pointer and cookie after casting");
     default:;
     }
   }
Member Data Documentation
union { ... }
Attribute* _attr private
Member function.
Definition at line 401 of file Function.h.
Referenced by attribute().
MPI_Comm _comm private
Definition at line 402 of file Function.h.
Referenced by communicator(), and set_communicator().
int _ftype private
Indicate the type of the function.
Definition at line 403 of file Function.h.
Referenced by is_fortran(), and operator()().
std::string _intents private
Intention of the argument.
Its length indicates the number of arguments
Definition at line 398 of file Function.h.
Referenced by intent(), is_input(), is_optional(), is_output(), and num_of_args().
Member_func_ptr _mem_ptr
Pointer to a member function.
Definition at line 396 of file Function.h.
Referenced by operator()().
Func_ptr _ptr
Pointer to a regular function.
Definition at line 395 of file Function.h.
Referenced by operator()().
std::vector<COM_Type> _types private
Data type of the arguments.
Definition at line 400 of file Function.h.
Referenced by data_type(), is_literal(), is_metadata(), and is_rawdata().
The documentation for this class was generated from the following file:
Function.h