Rocstar: rflu_modbilinearpatch Module Reference
rflu_modbilinearpatch Module Reference
Public Member Functions
subroutine, public rflu_blin_computenormal (global, ax, ay, az, bx, by, bz, cx, cy, cz, dx, dy, dz, u, v, nx, ny, nz)
subroutine, public rflu_blin_computexsectline (pRegion, xLoc, yLoc, zLoc, ex, ey, ez, icg, iPatch, ifg, nt, t)
subroutine, public rflu_blin_findclosestpoint (global, ax, ay, az, bx, by, bz, cx, cy, cz, dx, dy, dz, xq, yq, zq, u, v, x, y, z)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModBilinearPatch.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file RFLU_ModBilinearPatch.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_blin_computenormal (type(t_global), pointer global, real(rfreal), intent(in) ax, real(rfreal), intent(in) ay, real(rfreal), intent(in) az, real(rfreal), intent(in) bx, real(rfreal), intent(in) by, real(rfreal), intent(in) bz, real(rfreal), intent(in) cx, real(rfreal), intent(in) cy, real(rfreal), intent(in) cz, real(rfreal), intent(in) dx, real(rfreal), intent(in) dy, real(rfreal), intent(in) dz, real(rfreal), intent(in) u, real(rfreal), intent(in) v, real(rfreal), intent(out) nx, real(rfreal), intent(out) ny, real(rfreal), intent(out) nz)
Definition at line 99 of file RFLU_ModBilinearPatch.F90.
References by, moderror::deregisterfunction(), moderror::registerfunction(), sqrt(), and v.
Referenced by rflu_blin_computexsectline(), and rflu_modincelltest::rflu_ict_testfacequadbilinear().
subroutine, public rflu_blin_computexsectline (type(t_region), pointer pRegion, real(rfreal), intent(in) xLoc, real(rfreal), intent(in) yLoc, real(rfreal), intent(in) zLoc, real(rfreal), intent(in) ex, real(rfreal), intent(in) ey, real(rfreal), intent(in) ez, integer, intent(in) icg, integer, intent(in) iPatch, integer, intent(in) ifg, integer, intent(inout) nt, real(rfreal), dimension(2), intent(out) t)
Definition at line 188 of file RFLU_ModBilinearPatch.F90.
References Line_2< R, T >::a(), Color::b(), by, Line_2< R, T >::c(), moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), moderror::registerfunction(), rflu_blin_computenormal(), sign(), sqrt(), modtools::swaprfreals(), and v.
Referenced by rflu_modgeometrytools::rflu_computelinecellxsectfast(), and rflu_modgeometrytools::rflu_computelinecellxsectsafe().
subroutine, public rflu_blin_findclosestpoint (type(t_global), pointer global, real(rfreal), intent(in) ax, real(rfreal), intent(in) ay, real(rfreal), intent(in) az, real(rfreal), intent(in) bx, real(rfreal), intent(in) by, real(rfreal), intent(in) bz, real(rfreal), intent(in) cx, real(rfreal), intent(in) cy, real(rfreal), intent(in) cz, real(rfreal), intent(in) dx, real(rfreal), intent(in) dy, real(rfreal), intent(in) dz, real(rfreal), intent(in) xq, real(rfreal), intent(in) yq, real(rfreal), intent(in) zq, real(rfreal), intent(out) u, real(rfreal), intent(out) v, real(rfreal), intent(out) x, real(rfreal), intent(out) y, real(rfreal), intent(out) z)
Definition at line 570 of file RFLU_ModBilinearPatch.F90.
References by, moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), Color::g(), moderror::registerfunction(), v, x, y, and z.
Referenced by rflu_modincelltest::rflu_ict_testfacequadbilinear().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModBilinearPatch.F90,v $ $Revision: 1.5 $' private
Definition at line 61 of file RFLU_ModBilinearPatch.F90.
The documentation for this module was generated from the following file:
RFLU_ModBilinearPatch.F90