Rocstar: rflu_modcoloring Module Reference
rflu_modcoloring Module Reference
Data Types
interface rflu_col_buildcoloring
Public Member Functions
subroutine rflu_col_buildcolorings (pRegion)
subroutine, public rflu_col_createcoloring (pRegion)
subroutine, public rflu_col_destroycoloring (pRegion)
subroutine, public rflu_col_readcoloring (pRegion)
subroutine rflu_col_recreatecelllist (global, nVertPerCell, nCellsMax, x2v, x2cg)
subroutine, public rflu_col_writecoloring (pRegion)
Private Member Functions
subroutine rflu_col_buildcoloringp (pRegion, pRegionSerial)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModColoring.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 40 of file RFLU_ModColoring.F90.
Member Function/Subroutine Documentation
subroutine rflu_col_buildcoloringp (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial) private
Definition at line 104 of file RFLU_ModColoring.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modcopydata::rflu_copy_celldatas2p_i1d().
subroutine rflu_col_buildcolorings (type(t_region), pointer pRegion)
Definition at line 174 of file RFLU_ModColoring.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modresidual::rflu_getresidualsupport1(), rflu_modresidual::rflu_getresidualsupport2(), rs(), and StopWatch::stop().
subroutine, public rflu_col_createcoloring (type(t_region), pointer pRegion)
Definition at line 483 of file RFLU_ModColoring.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modpetscnewtonkrylov::rflu_petsc_createcoloring(), and rflupart().
subroutine, public rflu_col_destroycoloring (type(t_region), pointer pRegion)
Definition at line 556 of file RFLU_ModColoring.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modpetscnewtonkrylov::rflu_petsc_createcoloring(), and rflupart().
subroutine, public rflu_col_readcoloring (type(t_region), pointer pRegion)
Definition at line 629 of file RFLU_ModColoring.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modpetscnewtonkrylov::rflu_petsc_createcoloring().
subroutine rflu_col_recreatecelllist (type(t_global), pointer global, integer, intent(in) nVertPerCell, integer, intent(inout) nCellsMax, integer, dimension(:,:), pointer x2v, integer, dimension(:), pointer x2cg)
Definition at line 835 of file RFLU_ModColoring.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_col_writecoloring (type(t_region), pointer pRegion)
Definition at line 985 of file RFLU_ModColoring.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflupart().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModColoring.F90,v $ $Revision: 1.7 $' private
Definition at line 72 of file RFLU_ModColoring.F90.
The documentation for this module was generated from the following file:
RFLU_ModColoring.F90