Rocstar: MeshBndSurf Class Reference
MeshBndSurf Class Reference
#include <BndSurface.h>
Public Member Functions
MeshBndSurf ()
MeshBndSurf (Vec3D *n, Tri *t, unsigned int nv, unsigned int nt)
~MeshBndSurf ()
bool intersection (const Vec3D &p, const Vec3D &d, Vec3D &x)
void initialize (double *nodes, int *triangles, unsigned int nv, unsigned int nt, int divisions=50)
bool intersection (double *p, double *d, double *x)
MeshBndSurf ()
MeshBndSurf (Vec3D *n, Tri *t, unsigned int nv, unsigned int nt)
~MeshBndSurf ()
bool intersection (const Vec3D &p, const Vec3D &d, Vec3D &x)
void initialize (double *nodes, int *triangles, unsigned int nv, unsigned int nt, int divisions=50)
bool intersection (double *p, double *d, double *x)
Private Member Functions
void compute_bbox (Point3D &bbmin, Point3D &bbmax)
void compute_bbox (Point3D &bbmin, Point3D &bbmax)
Private Attributes
KNN_Grid< Tri > * gSpace
Point3D bbmin
Point3D bbmax
Vec3D * node_array
Tri * tri_array
unsigned int numv
unsigned int numt
Detailed Description
Definition at line 85 of file Rocon/include/BndSurface.h.
Constructor & Destructor Documentation
MeshBndSurf () inline
Definition at line 123 of file Rocon/include/BndSurface.h.
 :gSpace(NULL),node_array(NULL),tri_array(NULL),numv(0),numt(0){}
MeshBndSurf (Vec3D * n, Tri * t, unsigned int nv, unsigned int nt) inline
Definition at line 125 of file Rocon/include/BndSurface.h.
References i.
                               :node_array(n),tri_array(t),numv(nv),numt(nt)
   {
         compute_bbox(bbmin, bbmax);
         gSpace = new KNN_Grid< Tri > (bbmin, bbmax, 8);
         for(unsigned int i=0; i<nt; ++i){
            Point3D p(n[t[i][0]][0], n[t[i][0]][1], n[t[i][0]][2]);
                 Point3D q(n[t[i][1]][0], n[t[i][1]][1], n[t[i][1]][2]);
                 Point3D r(n[t[i][2]][0], n[t[i][2]][1], n[t[i][2]][2]);
            gSpace->insertRange(t[i], p,q,r);
         }
   }
~MeshBndSurf () inline
Definition at line 138 of file Rocon/include/BndSurface.h.
                 {
         delete gSpace;
         delete [] node_array;
         delete [] tri_array;
   }
MeshBndSurf () inline
Definition at line 123 of file Rocprop/include/BndSurface.h.
 :gSpace(NULL),node_array(NULL),tri_array(NULL),numv(0),numt(0){}
MeshBndSurf (Vec3D * n, Tri * t, unsigned int nv, unsigned int nt) inline
Definition at line 125 of file Rocprop/include/BndSurface.h.
References i.
                               :node_array(n),tri_array(t),numv(nv),numt(nt)
   {
         compute_bbox(bbmin, bbmax);
         gSpace = new KNN_Grid< Tri > (bbmin, bbmax, 8);
         for(int i=0; i<nt; ++i){
            Point3D p(n[t[i][0]][0], n[t[i][0]][1], n[t[i][0]][2]);
                 Point3D q(n[t[i][1]][0], n[t[i][1]][1], n[t[i][1]][2]);
                 Point3D r(n[t[i][2]][0], n[t[i][2]][1], n[t[i][2]][2]);
            gSpace->insertRange(t[i], p,q,r);
         }
   }
~MeshBndSurf () inline
Definition at line 139 of file Rocprop/include/BndSurface.h.
                 {
         delete gSpace;
         delete [] node_array;
         delete [] tri_array;
   }
Member Function Documentation
void compute_bbox (Point3D & bbmin, Point3D & bbmax) inline private
Definition at line 96 of file Rocon/include/BndSurface.h.
References i, and v.
   {
         if (numv == 0)
           {
             bbmin = bbmax = 0.0;
           }
         else
           {
             bbmin = bbmax = node_array[0];
           }
         for(unsigned int i=1; i<numv; i++)
           {
             Vertex3D & v = node_array[i];
             if(v[0] < bbmin[0])  bbmin[0]=v[0];
             if(v[1] < bbmin[1])  bbmin[1]=v[1];
             if(v[2] < bbmin[2])  bbmin[2]=v[2];
             if(v[0] > bbmax[0])  bbmax[0]=v[0];
             if(v[1] > bbmax[1])  bbmax[1]=v[1];
             if(v[2] > bbmax[2])  bbmax[2]=v[2];
           }
   }
void compute_bbox (Point3D & bbmin, Point3D & bbmax) inline private
Definition at line 96 of file Rocprop/include/BndSurface.h.
References i, and v.
   {
         if (numv == 0)
           {
             bbmin = bbmax = 0.0;
           }
         else
           {
             bbmin = bbmax = node_array[0];
           }
         for(unsigned int i=1; i<numv; i++)
           {
             Vertex3D & v = node_array[i];
             if(v[0] < bbmin[0])  bbmin[0]=v[0];
             if(v[1] < bbmin[1])  bbmin[1]=v[1];
             if(v[2] < bbmin[2])  bbmin[2]=v[2];
             if(v[0] > bbmax[0])  bbmax[0]=v[0];
             if(v[1] > bbmax[1])  bbmax[1]=v[1];
             if(v[2] > bbmax[2])  bbmax[2]=v[2];
           }
   }
void initialize (double * nodes, int * triangles, unsigned int nv, unsigned int nt, int divisions = 50) inline
Definition at line 193 of file Rocprop/include/BndSurface.h.
References i, j, and MAX_GRID_DIV.
  {
    numv=nv;
     numt=nt;
     //make sure grid divisions are sane
     if (divisions > MAX_GRID_DIV)
       {
         cerr << "Grid divsisions on longest dimension must be less than or equal to " << MAX_GRID_DIV << endl;
         divisions = MAX_GRID_DIV;
       }
     //Copy nodal coordinates
     if (node_array != NULL)
       delete [] node_array;
     node_array = new Vec3D[numv];
     for(int i=0;i<numv;i++)
       {
         for(int j=0;j<3;j++)
           {
             (node_array[i])[j]=nodes[i*3+j];
           }
       }
     //Copy triangle connectivity
     if (tri_array != NULL)
       delete [] tri_array;
     tri_array = new Tri[numt];
     for(int i=0;i<numt;i++)
       {
         for(int j=0;j<3;j++)
           {
             (tri_array[i])[j]=triangles[i*3+j];
           }
       }
     compute_bbox(bbmin, bbmax);
     if (gSpace != NULL)
       delete gSpace;
     gSpace = new KNN_Grid< Tri > (bbmin, bbmax, divisions);
     for(int i=0; i<nt; ++i)
       {
         Point3D p(node_array[tri_array[i][0]][0], node_array[tri_array[i][0]][1], node_array[tri_array[i][0]][2]);
         Point3D q(node_array[tri_array[i][1]][0], node_array[tri_array[i][1]][1], node_array[tri_array[i][1]][2]);
         Point3D r(node_array[tri_array[i][2]][0], node_array[tri_array[i][2]][1], node_array[tri_array[i][2]][2]);
         gSpace->insertRange(tri_array[i], p,q,r);
       }
   }
void initialize (double * nodes, int * triangles, unsigned int nv, unsigned int nt, int divisions = 50) inline
Definition at line 197 of file Rocon/include/BndSurface.h.
References i, j, and MAX_GRID_DIV.
Referenced by Rocon::initialize().
  {
    numv=nv;
    numt=nt;
    //make sure grid divisions are sane
    if (divisions > MAX_GRID_DIV)
      {
        cerr << "Grid divsisions on longest dimension must be less than or equal to "
             << MAX_GRID_DIV << endl;
        divisions = MAX_GRID_DIV;
      }
    //Copy nodal coordinates
    if (node_array != NULL)
      delete [] node_array;
    node_array = new Vec3D[numv];
    for(unsigned int i=0;i<numv;i++)
      {
        for(int j=0;j<3;j++)
          {
            (node_array[i])[j]=nodes[i*3+j];
          }
      }
    //Copy triangle connectivity
    if (tri_array != NULL)
      delete [] tri_array;
    tri_array = new Tri[numt];
    for(unsigned int i=0;i<numt;i++)
      {
        for(int j=0;j<3;j++)
          {
            (tri_array[i])[j]=triangles[i*3+j];
          }
      }
    compute_bbox(bbmin, bbmax);
    if (gSpace != NULL)
      delete gSpace;
    gSpace = new KNN_Grid< Tri > (bbmin, bbmax, divisions);
    for(unsigned int i=0; i<nt; ++i)
      {
        Point3D p(node_array[tri_array[i][0]][0], node_array[tri_array[i][0]][1], node_array[tri_array[i][0]][2]);
        Point3D q(node_array[tri_array[i][1]][0], node_array[tri_array[i][1]][1], node_array[tri_array[i][1]][2]);
        Point3D r(node_array[tri_array[i][2]][0], node_array[tri_array[i][2]][1], node_array[tri_array[i][2]][2]);
        gSpace->insertRange(tri_array[i], p,q,r);
      }
  }
bool intersection (const Vec3D & p, const Vec3D & d, Vec3D & x) inline
Definition at line 144 of file Rocon/include/BndSurface.h.
References j, and rayIntersectsTriangle().
Referenced by Rocon::find_intersections(), and Rocon::initialize().
   {
     double orig[3];
     double dir[3];
     double v1[3];
     double v2[3];
     double v3[3];
     double t;
         Point3D a,b;
         a = p;
         b = p+d;
         vector<Tri> * hitTri = gSpace->get_cell_range(a,b);
         t = 0;
         for(int j=0;j<3;j++)
           {
             orig[j] = p[j];
             dir[j]  = d[j];
           }
         for(vector<Tri>::iterator it = hitTri->begin(); it !=hitTri->end(); it++)
           {
             Tri & cur = *it;
             for(int j=0;j<3;j++)
               {
                 v1[j]=(node_array[cur[0]])[j];
                 v2[j]=(node_array[cur[1]])[j];
                 v3[j]=(node_array[cur[2]])[j];
               }
             if (rayIntersectsTriangle(orig, dir,v1,v2,v3,x))
               {
                 //Debugging info
                 std::cerr << "XXXX Ray " << p << " to " << d
                           << " Tri " << std::endl;
                 std::cerr << node_array[cur[0]] << std::endl;
                 std::cerr << node_array[cur[1]] << std::endl;
                 std::cerr << node_array[cur[2]] << std::endl << std::endl;
                 return true;
               }
             else
             {
               std::cerr << "0000 Ray "<< p << " to" << d
                         << " Tri " << std::endl;
               std::cerr << node_array[cur[0]] << std::endl;
               std::cerr << node_array[cur[1]] << std::endl;
               std::cerr << node_array[cur[2]] << std::endl << std::endl;
             }
           }
         return false;
   }
bool intersection (const Vec3D & p, const Vec3D & d, Vec3D & x) inline
Definition at line 145 of file Rocprop/include/BndSurface.h.
References j, and rayIntersectsTriangle().
   {
     double orig[3];
     double dir[3];
     double v1[3];
     double v2[3];
     double v3[3];
     double t;
         Point3D a,b;
         a = p;
         b = p+d;
         vector<Tri> * hitTri = gSpace->get_cell_range(a,b);
         t = 0;
         for(int j=0;j<3;j++)
           {
             orig[j] = p[j];
             dir[j]  = d[j];
           }
         for(vector<Tri>::iterator it = hitTri->begin(); it !=hitTri->end(); it++)
           {
             Tri & cur = *it;
             for(int j=0;j<3;j++)
               {
                 v1[j]=(node_array[cur[0]])[j];
                 v2[j]=(node_array[cur[1]])[j];
                 v3[j]=(node_array[cur[2]])[j];
               }
             if (rayIntersectsTriangle(orig, dir,v1,v2,v3,x))
               {
                 //Debugging info
                 //cerr << "XXXX Ray " << p << " to " << d << " Tri " << endl;
                 //cerr << node_array[cur[0]] << endl;
                 //cerr << node_array[cur[1]] << endl;
                 //cerr << node_array[cur[2]] << endl << endl;
                 return true;
               }
             //else
             //{
             //cerr<<"0000 Ray "<< p << " to" << d << " Tri " << endl;
             //}
           }
         return false;
   }
bool intersection (double * p, double * d, double * x) inline
Definition at line 244 of file Rocprop/include/BndSurface.h.
References i, j, and rayIntersectsTriangle().
   {
     double orig[3];
     double dir[3];
     double v1[3];
     double v2[3];
     double v3[3];
     double t;
     Vec3D xint;
     Point3D a,b;
     for(int j=0;j<3;j++)
       {
         a[j] = p[j];
         b[j] = p[j]+d[j];
       }
     vector<Tri> * hitTri = gSpace->get_cell_range(a,b);
     t = 0;
     for(int j=0;j<3;j++)
       {
         orig[j] = p[j];
         dir[j]  = d[j];
       }
         for(vector<Tri>::iterator it = hitTri->begin(); it !=hitTri->end(); it++)
           {
             Tri & cur = *it;
             for(int j=0;j<3;j++)
               {
                 v1[j]=(node_array[cur[0]])[j];
                 v2[j]=(node_array[cur[1]])[j];
                 v3[j]=(node_array[cur[2]])[j];
               }
             if (rayIntersectsTriangle(orig, dir,v1,v2,v3,xint))
               {
                 for(int i=0;i<3;i++)
                   x[i]=xint[i];
                 return true;
               }
           }
         return false;
   }
bool intersection (double * p, double * d, double * x) inline
Definition at line 249 of file Rocon/include/BndSurface.h.
References i, j, and rayIntersectsTriangle().
  {
    double orig[3];
    double dir[3];
    double v1[3];
    double v2[3];
    double v3[3];
    double t;
    Vec3D xint;
    Point3D a,b;
    for(int j=0;j<3;j++)
      {
        a[j] = p[j];
        b[j] = p[j]+d[j];
      }
    vector<Tri> * hitTri = gSpace->get_cell_range(a,b);
    if(hitTri->size() == 0){
      //     std::cout << "Rocon> WARNING: No constraint boundary found for p("
      //        << a[0] << "," << a[1] << "," << a[2] << "), d(" << d[0]
      //        << "," << d[1] << "," << d[2] << std::endl;
    }
    //    else
    //      std::cout << "Rocon> Checking " << hitTri->size() << " triangles for intersection for < "
    //           << a[0] << "," << a[1] << "," << a[2] << " >" << std::endl;
    t = 0;
    for(int j=0;j<3;j++)
      {
        orig[j] = p[j];
        dir[j]  = d[j];
      }
    for(vector<Tri>::iterator it = hitTri->begin(); it !=hitTri->end(); it++)
      {
        Tri & cur = *it;
        for(int j=0;j<3;j++)
          {
            v1[j]=(node_array[cur[0]])[j];
            v2[j]=(node_array[cur[1]])[j];
            v3[j]=(node_array[cur[2]])[j];
          }
        if (rayIntersectsTriangle(orig, dir,v1,v2,v3,xint))
          {
            for(int i=0;i<3;i++)
              x[i]=xint[i];
            hitTri->resize(0);
            delete hitTri;
            return true;
          }
        //       else
        //         {
        //           std::cout << "Rocon> " " Tri< " << node_array[cur[0]]
        //                     << ","<< node_array[cur[1]] << ","
        //                     << node_array[cur[2]] << "  >" << std::endl;
        //         }
      }
    if(hitTri){
      hitTri->resize(0);
      delete hitTri;
    }
    return false;
  }
Member Data Documentation
Point3D bbmax private
Definition at line 90 of file Rocon/include/BndSurface.h.
Point3D bbmin private
Definition at line 90 of file Rocon/include/BndSurface.h.
KNN_Grid< Tri > * gSpace private
Definition at line 89 of file Rocon/include/BndSurface.h.
Vec3D * node_array private
Definition at line 91 of file Rocon/include/BndSurface.h.
unsigned int numt private
Definition at line 94 of file Rocon/include/BndSurface.h.
unsigned int numv private
Definition at line 93 of file Rocon/include/BndSurface.h.
Tri * tri_array private
Definition at line 92 of file Rocon/include/BndSurface.h.
The documentation for this class was generated from the following file:
Rocon/include/BndSurface.h