Rocstar: rflu_modnscbc Module Reference
rflu_modnscbc Module Reference
Public Member Functions
subroutine, public rflu_nscbc_compfirstpatchflux (pRegion, pPatch)
subroutine, public rflu_nscbc_comppatchflux (pRegion, pPatch)
subroutine, public rflu_nscbc_compsecondpatchflux (pRegion, pPatch)
subroutine, public rflu_nscbc_comprhs (pRegion)
logical function, public rflu_nscbc_decidehavenscbc (pRegion)
subroutine, public rflu_nscbc_initff (pRegion, pPatch)
subroutine, public rflu_nscbc_initiftotang (pRegion, pPatch)
subroutine, public rflu_nscbc_initifveltemp (pRegion, pPatch)
subroutine, public rflu_nscbc_initij (pRegion, pPatch)
subroutine, public rflu_nscbc_initnswheat (pRegion, pPatch)
subroutine, public rflu_nscbc_initnswtemp (pRegion, pPatch)
subroutine, public rflu_nscbc_initof (pRegion, pPatch)
subroutine, public rflu_nscbc_initsw (pRegion, pPatch)
Private Member Functions
subroutine, private rflu_nscbc_comprhsff (pRegion, pPatch)
subroutine, private rflu_nscbc_comprhsiftotang (pRegion, pPatch)
subroutine, private rflu_nscbc_comprhsifveltemp (pRegion, pPatch)
subroutine, private rflu_nscbc_comprhsij (pRegion, pPatch)
subroutine, private rflu_nscbc_comprhsnswheat (pRegion, pPatch)
subroutine, private rflu_nscbc_comprhsnswtemp (pRegion, pPatch)
subroutine, private rflu_nscbc_comprhsof (pRegion, pPatch)
subroutine, private rflu_nscbc_comprhssw (pRegion, pPatch)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModNSCBC.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 39 of file RFLU_ModNSCBC.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_nscbc_compfirstpatchflux (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 148 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), rflu_modentropyfixes::entropyfixhartenhyman(), max(), min(), mixtperf_c_ghovm2(), mixtperf_ho_cptuvw(), mixtperf_r_cpg(), mixtperf_t_dpr(), moderror::registerfunction(), rflu_decideprint(), rflu_printlocinfo(), and sqrt().
Referenced by rflu_modroeflux::rflu_roe_computeflux1_tcp(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxc1(), and rflu_modroeflux::rflu_roe_computefluxc2_tcp().
subroutine, public rflu_nscbc_comppatchflux (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 478 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), rflu_modentropyfixes::entropyfixhartenhyman(), max(), min(), mixtperf_c_ghovm2(), mixtperf_ho_cptuvw(), mixtperf_r_cpg(), mixtperf_t_dpr(), moderror::registerfunction(), rflu_decideprint(), rflu_printlocinfo(), and sqrt().
subroutine, public rflu_nscbc_comprhs (type(t_region), pointer pRegion)
Definition at line 1154 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modboundconvertcv::rflu_bxv_convertcvcons2prim(), rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_moddifferentiationbfaces::rflu_computegradbfaceswrapper(), rflu_modconvertcv::rflu_convertcvcons2prim(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_decideneedbgradface(), rflu_nscbc_comprhsff(), rflu_nscbc_comprhsiftotang(), rflu_nscbc_comprhsifveltemp(), rflu_nscbc_comprhsij(), rflu_nscbc_comprhsnswheat(), rflu_nscbc_comprhsnswtemp(), rflu_nscbc_comprhsof(), and rflu_nscbc_comprhssw().
Referenced by convectivefluxes().
subroutine, private rflu_nscbc_comprhsff (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1273 of file RFLU_ModNSCBC.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), Color::g(), mixtperf_g_cpr(), mixtperf_r_m(), Color::r(), moderror::registerfunction(), and v.
Referenced by rflu_nscbc_comprhs().
subroutine, private rflu_nscbc_comprhsiftotang (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1616 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_nscbc_comprhs().
subroutine, private rflu_nscbc_comprhsifveltemp (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 1684 of file RFLU_ModNSCBC.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), Color::g(), mixtperf_g_cpr(), mixtperf_r_m(), Color::r(), moderror::registerfunction(), and v.
Referenced by rflu_nscbc_comprhs().
subroutine, private rflu_nscbc_comprhsij (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 2018 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_nscbc_comprhs().
subroutine, private rflu_nscbc_comprhsnswheat (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 2084 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_nscbc_comprhs().
subroutine, private rflu_nscbc_comprhsnswtemp (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 2150 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_nscbc_comprhs().
subroutine, private rflu_nscbc_comprhsof (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 2216 of file RFLU_ModNSCBC.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), Color::g(), mixtperf_g_cpr(), mixtperf_r_m(), Color::r(), moderror::registerfunction(), and v.
Referenced by rflu_nscbc_comprhs().
subroutine, private rflu_nscbc_comprhssw (type(t_region), pointer pRegion, type(t_patch), pointer pPatch) private
Definition at line 2549 of file RFLU_ModNSCBC.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), Color::g(), mixtperf_g_cpr(), mixtperf_r_m(), Color::r(), moderror::registerfunction(), and v.
Referenced by rflu_nscbc_comprhs().
subroutine, public rflu_nscbc_compsecondpatchflux (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 805 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), rflu_modentropyfixes::entropyfixhartenhyman(), max(), min(), mixtperf_c_ghovm2(), mixtperf_ho_cptuvw(), mixtperf_r_cpg(), mixtperf_t_dpr(), moderror::registerfunction(), rflu_decideprint(), rflu_printlocinfo(), and sqrt().
Referenced by rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), and rflu_modroeflux::rflu_roe_computefluxc2_tcp().
logical function, public rflu_nscbc_decidehavenscbc (type(t_region), pointer pRegion)
Definition at line 2747 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by convectivefluxes(), rflu_modboundxvutils::rflu_bxv_readvarswrapper(), rflu_modboundxvutils::rflu_bxv_writevarswrapper(), rflu_endflowsolver(), rflu_initflowsolver(), rfluinit(), rkinitmp(), rkupdatemp(), and rungekuttamp().
subroutine, public rflu_nscbc_initff (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 2828 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Color::g(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), moderror::registerfunction(), and rflu_modrindstates::rflu_setrindstatefarfieldperf().
Referenced by rflu_modboundxvutils::rflu_bxv_initvars().
subroutine, public rflu_nscbc_initiftotang (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 2982 of file RFLU_ModNSCBC.F90.
References bcondinflowperf(), moderror::deregisterfunction(), moderror::errorstop(), Color::g(), mixtperf_g_cpr(), mixtperf_r_m(), and moderror::registerfunction().
Referenced by rflu_modboundxvutils::rflu_bxv_initvars().
subroutine, public rflu_nscbc_initifveltemp (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 3106 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Color::g(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_p_drt(), mixtperf_r_m(), and moderror::registerfunction().
Referenced by rflu_modboundxvutils::rflu_bxv_initvars().
subroutine, public rflu_nscbc_initij (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 3226 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modboundxvutils::rflu_bxv_initvars().
subroutine, public rflu_nscbc_initnswheat (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 3294 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modboundxvutils::rflu_bxv_initvars().
subroutine, public rflu_nscbc_initnswtemp (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 3361 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modboundxvutils::rflu_bxv_initvars().
subroutine, public rflu_nscbc_initof (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 3428 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Color::g(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), and moderror::registerfunction().
Referenced by rflu_modboundxvutils::rflu_bxv_initvars().
subroutine, public rflu_nscbc_initsw (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 3549 of file RFLU_ModNSCBC.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Color::g(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), and moderror::registerfunction().
Referenced by rflu_modboundxvutils::rflu_bxv_initvars().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModNSCBC.F90,v $ $Revision: 1.7 $' private
Definition at line 86 of file RFLU_ModNSCBC.F90.
The documentation for this module was generated from the following file:
RFLU_ModNSCBC.F90