Rocstar: Window Class Reference
Window Class Reference
A Window object contains multiple panes and multiple data attributes.
#include <Window.h>
Classes
class Pane_friend
struct Pointer_descriptor
Public Types
typedef std::map< int, int > Proc_map
Public Member Functions
Constructor and destructor
Window (const std::string &name, MPI_Comm c)
Create a window with a given name and MPI communicator.
virtual ~Window ()
Destructor.
Identity
const std::string & name () const
Obtain the window's name.
MPI_Comm get_communicator () const
Obtain the communicator of the window.
Function and data management
void set_function (const std::string &fname, Func_ptr func, const std::string &intents, const COM_Type *types, Attribute *a, bool if_f90=false) throw (COM_exception)
Initialize a Function record.
void set_function (const std::string &fname, Member_func_ptr func, const std::string &intents, const COM_Type *types, Attribute *a, bool if_f90=false) throw (COM_exception)
Initialize a Function record.
Attribute * new_attribute (const std::string &aname, const char loc, const int type, int ncomp, const std::string &unit) throw (COM_exception)
Create a new Attribute object with given properties.
void delete_attribute (const std::string &aname) throw (COM_exception)
Delete an existing Attribute object.
void set_size (const std::string &aname, int pane_id, int nitems, int ng=0) throw (COM_exception)
Set the sizes of an attribute for a specific pane.
void set_array (const std::string &aname, const int pane_id, void *addr, int strd=0, int cap=0, bool is_const=false) throw (COM_exception)
Associate an array with an attribute for a specific pane.
void alloc_array (const std::string &aname, const int pane_id, void **addr, int strd=0, int cap=0) throw (COM_exception)
Allocate memory for an attribute for a specific pane and set addr to the address.
void resize_array (const std::string &aname, const int pane_id, void **addr, int strd=-1, int cap=0) throw (COM_exception)
Resize memory for an attribute for a specific pane and set addr to the address.
void resize_array (Attribute *a, void **addr, int strd=-1, int cap=0) throw (COM_exception)
void resize_array (Connectivity *c, void **addr, int strd=-1, int cap=0) throw (COM_exception)
void append_array (const std::string &aname, const int pane_id, const void *val, int v_strd, int v_size) throw (COM_exception)
Append the given array to the end of the attribute on a specific pane, and reallocate memory for the attribute if necessary.
void dealloc_array (const std::string &aname, const int pane_id=0) throw (COM_exception)
Deallocate memory for an attribute for a specific pane if allocated by Roccom.
void dealloc_array (Attribute *a) throw (COM_exception)
void dealloc_array (Connectivity *c) throw (COM_exception)
Attribute * inherit (Attribute *from, const std::string &aname, int inherit_mode, bool withghost, const Attribute *cond, int val) throw (COM_exception)
Inherit the attributes of another window with a different name.
void copy_attribute (const Attribute *from, Attribute *to) throw (COM_exception)
Copy an attribute object onto another.
Attribute * get_attribute (const std::string &aname, char *l, int *t, int *n, std::string *u) const throw (COM_exception)
Get the meta-information about an attribute.
void get_size (const std::string &aname, int pane_id, int *nitems, int *ng) const throw (COM_exception)
Get the sizes of an attribute for a specific pane.
int get_status (const std::string &aname, int pane_id) const throw (COM_exception)
Get the status of an attribute or pane.
void get_parent (const std::string &aname, int pane_id, std::string &name) const throw (COM_exception)
Get the parent name of an attribute and load into name.
void get_array (const std::string &aname, const int pane_id, Pointer_descriptor &addr, int *strd=NULL, int *cap=NULL, bool is_const=false) throw (COM_exception)
Get the address associated with an attribute for a specific pane.
void copy_array (const std::string &aname, const int pane_id, void *val, int v_strd=0, int v_size=0, int offset=0) const throw (COM_exception)
Copy an attribute on a specific pane into a given array.
void init_done (bool pane_changed=true) throw (COM_exception)
Perform some final checking of the window.
Pane management
int size_of_panes () const
Obtain the number of local panes in the window.
int size_of_panes_global () const
Obtain the total number of panes in the window on all processes.
int owner_rank (const int pane_id) const
Obtain the process rank that owns a given pane.
int last_attribute_id () const
Return the last attribute id.
const Proc_map & proc_map () const
Obtain the process map.
void delete_pane (const int pane_id) throw (COM_exception)
Remove the pane with given ID.
Miscellaneous
Pane & pane (const int pane_id, bool insert=false) throw (COM_exception)
Find the pane with given ID. If not found, insert a pane with given ID.
const Pane & pane (const int pane_id) const throw (COM_exception)
void panes (std::vector< int > &ps, int rank=-2)
Obtain all the local panes of the window.
void panes (std::vector< Pane * > &ps)
Obtain all the local panes of the window.
void panes (std::vector< const Pane * > &ps) const
Obtain all the local panes of the window.
void attributes (std::vector< Attribute * > &as)
Obtain all the attributes of the pane.
void attributes (std::vector< const Attribute * > &as) const
Obtain all the attributes of the pane.
Attribute * attribute (const std::string &a) throw (COM_exception)
Obtain a pointer to the attribute metadata from its name.
const Attribute * attribute (const std::string &a) const throw (COM_exception)
Attribute * attribute (int i) throw (COM_exception)
Obtain a pointer to the attribute metadata from its index.
const Attribute * attribute (int i) const throw (COM_exception)
Function * function (const std::string &f)
Obtain the function pointer from its name.
const Function * function (const std::string &f) const
Protected Types
enum { STATUS_SHRUNK, STATUS_CHANGED, STATUS_NOCHANGE }
Protected Member Functions
void reinit_attr (Attribute *attr, OP_Init op, void **addr=NULL, int strd=0, int cap=0) throw (COM_exception)
Implementation for setting (op==OP_SET or OP_SET_CONST), allocating (op==OP_ALLOC), resizing (op==OP_RESIZE) and deallocating (op==OP_DEALLOC) an array for a specific attribute.
void reinit_conn (Connectivity *con, OP_Init op, int **addr=NULL, int strd=0, int cap=0) throw (COM_exception)
Template implementation for setting (op==OP_SET or OP_SET_CONST), allocating (op==OP_ALLOC), resizing (op==OP_RESIZE) and deallocating (op==OP_DEALLOC) an array for a specific connectivity table.
Protected Attributes
Pane _dummy
Dummy pane.
std::string _name
Name of the window.
Attr_map _attr_map
Map from attribute names to their metadata.
Func_map _func_map
Map from function names to their metadata.
Pane_map _pane_map
Map from pane ID to their metadata.
Proc_map _proc_map
Map from pane ID to process ranks.
int _last_id
The last used attribute index.
MPI_Comm _comm
the MPI communicator of the window.
int _status
Status of the window.
Private Types
typedef std::map< std::string,
Function > Func_map
typedef std::map< std::string,
Attribute * > Attr_map
typedef std::map< int, Pane * > Pane_map
typedef Pane::OP_Init OP_Init
Private Member Functions
Window (const Window &)
Window & operator= (const Window &)
Detailed Description
A Window object contains multiple panes and multiple data attributes.
Definition at line 42 of file Window.h.
Member Typedef Documentation
typedef std::map< std::string, Attribute*> Attr_map private
Definition at line 44 of file Window.h.
typedef std::map< std::string, Function> Func_map private
Definition at line 43 of file Window.h.
typedef Pane::OP_Init OP_Init private
Definition at line 58 of file Window.h.
typedef std::map< int, Pane*> Pane_map private
Definition at line 45 of file Window.h.
typedef std::map<int,int> Proc_map
Definition at line 61 of file Window.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
STATUS_SHRUNK
STATUS_CHANGED
STATUS_NOCHANGE
Definition at line 388 of file Window.h.
 { STATUS_SHRUNK, STATUS_CHANGED, STATUS_NOCHANGE };
Constructor & Destructor Documentation
COM_BEGIN_NAME_SPACE Window (const std::string & name, MPI_Comm c)
Create a window with a given name and MPI communicator.
Parameters
name name of the window
c MPI communicator where the window resides
Definition at line 42 of file Window.C.
References _attr_map, _dummy, Pane::attribute(), COM_NUM_KEYWORDS, i, Attribute::is_digit(), and Attribute::name().
   : _dummy( this, 0), _name( s), _last_id(COM_NUM_KEYWORDS),
     _comm(c), _status( STATUS_NOCHANGE)
 {
   // Insert keywords into _attr_map
   for ( int i=0; i<COM_NUM_KEYWORDS; ++i) {
     Attribute *a = _dummy.attribute(i);
     if ( !Attribute::is_digit(a->name()[0])) _attr_map[ a->name()] = a;
   }
 }
~Window () virtual
Destructor.
Definition at line 53 of file Window.C.
References _pane_map.
 {
   for ( Pane_map::iterator it=_pane_map.begin(); it!=_pane_map.end(); ++it)
     delete it->second;
 }
Window (const Window &) private
Member Function Documentation
void alloc_array (const std::string & aname, const int pane_id, void ** addr, int strd = 0, int cap = 0) throw (COM_exception)
Allocate memory for an attribute for a specific pane and set addr to the address.
alloc_array, resize_array, append_array
Definition at line 238 of file Window.C.
References addr, append_frame, cap, COM_ERR_ATTRIBUTE_NOTEXIST, Connectivity::is_element_name(), Pane::OP_ALLOC, pane_id, and strd.
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane &pn = pane(pane_id,true);
     Connectivity *con = ((Pane_friend&)pn).connectivity( aname);
     if ( con==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname,Window::alloc_array));
     reinit_conn( con, Pane::OP_ALLOC, (int**)addr, strd, cap);
   }
   else {
     Attribute *a = pane( pane_id,true).attribute( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname,Window::alloc_array));
     reinit_attr( a, Pane::OP_ALLOC, addr, strd, cap);
   }
 }
void append_array (const std::string & aname, const int pane_id, const void * val, int v_strd, int v_size) throw (COM_exception)
Append the given array to the end of the attribute on a specific pane, and reallocate memory for the attribute if necessary.
set_array, alloc_array, resize_array
Definition at line 284 of file Window.C.
References Attribute::append_array(), append_frame, COM_assertion_msg, COM_ERR_ATTRIBUTE_NOTEXIST, Connectivity::is_element_name(), COM_exception::msg, Pane::OP_RESIZE, pane_id, Attribute::set_size(), Attribute::size_of_items(), Attribute::size_set(), and Attribute::stride().
 {
   COM_assertion_msg( !Connectivity::is_element_name( aname),
                      "append_array supports only window and pane attributes");
   Attribute *a = pane( pane_id,true).attribute( aname);
   if ( a==NULL)
     throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                          (name()+"."+aname,Window::append_array));
   try {
     // Set size to 0 if not yet set.
     if ( !a->size_set()) a->set_size(0);
     // resize the target attribute.
     reinit_attr( a, Pane::OP_RESIZE, NULL, a->stride(),
                  a->size_of_items()+v_size);
   }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, Window::append_array);
     throw ex;
   }
   // copy the array to the back of the target array
   a->append_array( val, v_strd, v_size);
 }
Attribute * attribute (const std::string & a) throw (COM_exception)
Obtain a pointer to the attribute metadata from its name.
Definition at line 842 of file Window.C.
References append_frame, COM_ERR_INVALID_ATTRIBUTE_NAME, i, Attribute::id(), Attribute::is_digit(), and Attribute::size_of_components().
Referenced by Pane::attribute(), and attribute().
 {
   if ( !Attribute::is_digit(aname[0])) {
     Attr_map::iterator it = _attr_map.find( aname);
     if ( it == _attr_map.end())
       return NULL;
     else
       return it->second;
   }
   else {
     std::string::size_type start = aname.find( '-');
     if ( start == aname.npos)
       throw COM_exception( COM_ERR_INVALID_ATTRIBUTE_NAME, append_frame
                            (_name+"."+aname,Window::attribute));
     Attr_map::iterator it = _attr_map.find( &aname[start+1]);
     if ( it != _attr_map.end()) {
       Attribute *att = it->second;
       if ( att->size_of_components()>1) {
         // Get the subcomponent
         int i = std::atoi( aname.c_str());
         if ( i<=0 || i>att->size_of_components())
           throw COM_exception( COM_ERR_INVALID_ATTRIBUTE_NAME, append_frame
                                (_name+"."+aname,Window::attribute));
         return attribute( att->id()+i);
       }
     }
     return NULL;
   }
 }
const Attribute* attribute (const std::string & a) const throw (COM_exception) inline
Definition at line 336 of file Window.h.
References attribute().
   { return const_cast<Window*>(this)->attribute( a); }
Attribute* attribute (int i) throw (COM_exception) inline
Obtain a pointer to the attribute metadata from its index.
Definition at line 340 of file Window.h.
References _dummy, Pane::attribute(), and i.
   { return _dummy.attribute( i); }
const Attribute* attribute (int i) const throw (COM_exception) inline
Definition at line 342 of file Window.h.
References _dummy, Pane::attribute(), and i.
   { return _dummy.attribute( i); }
void attributes (std::vector< Attribute * > & as) inline
Obtain all the attributes of the pane.
Definition at line 328 of file Window.h.
References _dummy, and Pane::attributes().
Referenced by Rocblas::copy(), Rocblas::rand(), and Rocblas::swap().
   { _dummy.attributes( as); }
void attributes (std::vector< const Attribute * > & as) const inline
Obtain all the attributes of the pane.
Definition at line 331 of file Window.h.
References _dummy, and Pane::attributes().
   { _dummy.attributes( as); }
void copy_array (const std::string & aname, const int pane_id, void * val, int v_strd = 0, int v_size = 0, int offset = 0) const throw (COM_exception)
Copy an attribute on a specific pane into a given array.
Parameters
aname attribute name
pane_id pane ID
val address of the user array
v_strd stride of user array. 0 (the default) indicates number of components.
v_size number of items to be copied. 0 (the default) indicates number of items of the attribute.
offset starting item to be copied in the attribute. alloc_array, resize_array, get_array
Definition at line 685 of file Window.C.
References append_frame, Pane::attribute(), COM_ERR_ATTRIBUTE_NOTEXIST, Pane::connectivity(), copy_array_common(), Connectivity::is_element_name(), COM_exception::msg, offset(), and pane_id.
 {
   const Pane_friend *pn;
   try { pn = &(Pane_friend&)pane(pane_id); }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, Window::copy_array);
     throw ex;
   }
   if ( Connectivity::is_element_name( aname)) {
     const Connectivity *conn = pn->connectivity( aname);
     if ( conn == NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname, Window::copy_array));
     copy_array_common( conn, pane_id,
                        val, v_strd, v_size, offset);
   }
   else {
     const Attribute *attr = pn->attribute( aname);
     if ( attr == NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname, Window::copy_array));
     copy_array_common( attr, pane_id,
                        val, v_strd, v_size, offset);
   }
 }
void copy_attribute (const Attribute * from, Attribute * to) throw (COM_exception) inline
Copy an attribute object onto another.
Definition at line 207 of file Window.h.
References inherit(), and Pane::INHERIT_COPY.
{
     inherit( const_cast<Attribute*>(from), to->name(),
              Pane::INHERIT_COPY, true, NULL, 0);
   }
void dealloc_array (const std::string & aname, const int pane_id = 0) throw (COM_exception)
Deallocate memory for an attribute for a specific pane if allocated by Roccom.
alloc_array, resize_array
Definition at line 311 of file Window.C.
References append_frame, COM_ERR_ATTRIBUTE_NOTEXIST, Connectivity::is_element_name(), Pane::OP_DEALLOC, and pane_id.
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane &pn = pane(pane_id);
     Connectivity *con = ((Pane_friend&)pn).connectivity( aname);
     if ( con==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname,Window::dealloc_array));
     reinit_conn( con, Pane::OP_DEALLOC);
   }
   else {
     Attribute *a = pane( pane_id).attribute( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname,Window::dealloc_array));
     reinit_attr( a, Pane::OP_DEALLOC);
   }
 }
void dealloc_array (Attribute * a) throw (COM_exception) inline
Definition at line 188 of file Window.h.
References Pane::OP_DEALLOC, and reinit_attr().
   { reinit_attr( a, Pane::OP_DEALLOC); }
void dealloc_array (Connectivity * c) throw (COM_exception) inline
Definition at line 191 of file Window.h.
References Pane::OP_DEALLOC, and reinit_conn().
   { reinit_conn( c, Pane::OP_DEALLOC); }
void delete_attribute (const std::string & aname) throw (COM_exception)
Delete an existing Attribute object.
Definition at line 137 of file Window.C.
References append_frame, COM_ATTS, COM_ERR_ATTRIBUTE_NOTEXIST, COM_ERR_INVALID_ATTRIBUTE_NAME, COM_NUM_KEYWORDS, Pane::delete_attribute(), i, id(), Attribute::id(), Attribute::is_digit(), Attribute::name(), and Attribute::size_of_components().
 {
   Attr_map::iterator it = _attr_map.find( aname);
   if ( it == _attr_map.end())
     throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST,append_frame
                          (_name+"."+aname,Window::delete_attribute));
   Attribute *attr = it->second;
   int id = attr->id(), ncomp=attr->size_of_components();
   if ( id < COM_NUM_KEYWORDS && id != COM_ATTS)
     throw COM_exception( COM_ERR_INVALID_ATTRIBUTE_NAME,append_frame
                          (_name+"."+aname,Window::delete_attribute));
   // Remove the object from both the set
   ((Pane_friend&)_dummy).delete_attribute( id);
   // Remove from all panes.
   for (Pane_map::iterator it=_pane_map.begin(); it!=_pane_map.end(); ++it) {
     Pane_friend *pn = (Pane_friend*)it->second;
     pn->delete_attribute( id);
   }
   // Update last id
   if (id != COM_ATTS) {
     _attr_map.erase( it); // Remove from _attr_map
     if ( _last_id == id + ncomp+(ncomp>1)) {
       _last_id = id;
       if ( _status==STATUS_NOCHANGE) _status = STATUS_CHANGED;
     }
     else
       _status = STATUS_SHRUNK;
   }
   else if (_last_id>COM_NUM_KEYWORDS) {
     _attr_map.clear();
     for ( int i=0; i<COM_NUM_KEYWORDS; ++i) {
       Attribute *a = _dummy.attribute(i);
       if ( !Attribute::is_digit(a->name()[0])) _attr_map[ a->name()] = a;
     }
     _status = STATUS_CHANGED;
     _last_id = COM_NUM_KEYWORDS;
   }
 }
void delete_pane (const int pane_id) throw (COM_exception) inline
Remove the pane with given ID.
Definition at line 297 of file Window.h.
References _pane_map, and COM_ERR_PANE_NOTEXIST.
{
     if ( pane_id == 0) { // delete all panes
       _pane_map.clear();
     }
     else {
       Pane_map::iterator it = _pane_map.find( pane_id);
       if ( it == _pane_map.end()) throw COM_exception(COM_ERR_PANE_NOTEXIST);
       delete it->second;
       _pane_map.erase( it);
     }
   }
Function * function (const std::string & f)
Obtain the function pointer from its name.
Definition at line 877 of file Window.C.
References _func_map.
 {
   Func_map::iterator it = _func_map.find( fname);
   if ( it == _func_map.end())
     return NULL;
   else
     return &it->second;
 }
const Function* function (const std::string & f) const inline
Definition at line 347 of file Window.h.
   { return const_cast<Window*>(this)->function( f); }
void get_array (const std::string & aname, const int pane_id, Pointer_descriptor & addr, int * strd = NULL, int * cap = NULL, bool is_const = false) throw (COM_exception)
Get the address associated with an attribute for a specific pane.
Parameters
aname attribute name
pane_id pane ID
addr address of the array
strd Stride between two items of each component
cap capacity of the array alloc_array, resize_array, copy_array
Definition at line 641 of file Window.C.
References addr, append_frame, Pane::attribute(), cap, COM_ERR_ATTRIBUTE_NOTEXIST, Pane::connectivity(), get_array_common(), Connectivity::is_element_name(), COM_exception::msg, pane_id, and strd.
Referenced by get_array_common().
 {
   Pane_friend *pn;
   try { pn = &(Pane_friend&)pane(pane_id); }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, Window::get_array);
     throw ex;
   }
   if ( Connectivity::is_element_name( aname)) {
     // Define as const reference to avoid exception.
     const Connectivity *con=pn->connectivity( aname);
     if ( con==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST,append_frame
                            (name()+"."+aname,Window::get_array));
     get_array_common( con, pane_id, addr, strd, cap, is_const);
   }
   else {
     // Define as const reference to avoid exception.
     const Attribute *a = pn->attribute( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST,append_frame
                            (name()+"."+aname,Window::get_array));
     get_array_common( a, pane_id, addr, strd, cap, is_const);
   }
 }
Attribute * get_attribute (const std::string & aname, char * l, int * t, int * n, std::string * u) const throw (COM_exception)
Get the meta-information about an attribute.
Parameters
aname attribute name
l location
t data type
n number of components
u unit
Definition at line 462 of file Window.C.
References append_frame, COM_ERR_ATTRIBUTE_NOTEXIST, COM_INT, Attribute::data_type(), Connectivity::get_size_info(), Connectivity::is_element_name(), Attribute::location(), Connectivity::SIZE_NNODES, Attribute::size_of_components(), and Attribute::unit().
{
   // Special handing for connectivity tables
   if ( Connectivity::is_element_name( aname)) {
     // Set the arguments if not NULL.
     if ( loc) *loc = 'p';
     if ( type) *type = COM_INT;
     // Return the number of nodes.
     if ( ncomp) *ncomp = Connectivity::get_size_info(aname)
                   [Connectivity::SIZE_NNODES];
     if ( unit) *unit = "";
     return NULL; // A connectivity is not defined in Window scope.
   }
   else {
     // Obtain reference to the attribute
     Attr_map::const_iterator it = _attr_map.find( aname);
     if ( it == _attr_map.end())
       throw COM_exception(COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                           (_name+"."+aname,Window::get_attribute));
     Attribute &a = *it->second;
     // Set the arguments if not NULL.
     if ( loc) *loc = a.location();
     if ( type) *type = a.data_type();
     if ( ncomp) *ncomp = a.size_of_components();
     if ( unit) *unit = a.unit();
     return &a;
   }
 }
MPI_Comm get_communicator () const inline
Obtain the communicator of the window.
Definition at line 95 of file Window.h.
References _comm.
Referenced by Roccom_base::get_communicator(), and Rocout::write_attr_internal().
 { return _comm; }
void get_parent (const std::string & aname, int pane_id, std::string & name) const throw (COM_exception)
Get the parent name of an attribute and load into name.
If the attribute has no parent, then name is empty.
Definition at line 566 of file Window.C.
References append_frame, Pane::attribute(), COM_ERR_ATTRIBUTE_NOTEXIST, Pane::connectivity(), Connectivity::is_element_name(), and COM_exception::msg.
{
   const Pane_friend *pn;
   try {
     pn = &(Pane_friend&)pane(pid);
     // Special handing for connectivity
     if ( Connectivity::is_element_name( aname)) {
       // Get the corresponding attribute object.
       const COM::Connectivity *conn = pn->connectivity( aname);
       if ( conn==NULL)
         throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                              (name()+"."+aname,Window::get_parent));
       conn = conn->parent();
       if ( conn==NULL) parent.clear();
       else parent = conn->fullname();
     }
     else {
       // Get the corresponding attribute object.
       const COM::Attribute *attr = pn->attribute( aname);
       if ( attr==NULL)
         throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                              (name()+"."+aname,Window::get_parent));
       if ( attr==NULL) parent.clear();
       else parent = attr->fullname();
     }
   } catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, Window::get_parent);
     throw ex;
   }
 }
void get_size (const std::string & aname, int pane_id, int * nitems, int * ng) const throw (COM_exception)
Get the sizes of an attribute for a specific pane.
Parameters
aname attribute name
pane_id pane ID
nitems total number of items (including ghosts)
ng number of ghosts
Definition at line 505 of file Window.C.
References append_frame, Pane::attribute(), COM_ERR_ATTRIBUTE_NOTEXIST, Pane::connectivity(), get_size_common(), Connectivity::is_element_name(), and COM_exception::msg.
Referenced by get_size_common().
{
   const Pane_friend *pn;
   try { pn = &(Pane_friend&)pane(pid); }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, Window::get_size);
     throw ex;
   }
   // Special handing for connectivity
   if ( Connectivity::is_element_name( aname)) {
     // Get the corresponding attribute object.
     const COM::Connectivity *conn = pn->connectivity( aname);
     if ( conn==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            ( name()+"."+aname, Window::get_size));
     get_size_common( conn, pid, nitem, ng);
   }
   else {
     // Get the corresponding attribute object.
     const COM::Attribute *attr = pn->attribute( aname);
     if ( attr==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            ( name()+"."+aname, Window::get_size));
     get_size_common( attr, pid, nitem, ng);
   }
 }
int get_status (const std::string & aname, int pane_id) const throw (COM_exception)
Get the status of an attribute or pane.
Roccom_base::get_status()
Definition at line 535 of file Window.C.
References append_frame, Pane::attribute(), Pane::connectivity(), Connectivity::is_element_name(), COM_exception::msg, and Attribute::status().
Referenced by Roccom_base::get_status().
{
   // If aname is empty, then check the status of the pane.
   if ( aname.empty()) {
     Pane_map::const_iterator pit = _pane_map.find( pid);
     if ( pit == _pane_map.end()) return -1;
     else return 0;
   }
   const Pane_friend *pn;
   try { pn = &(Pane_friend&)pane(pid); }
   catch ( COM_exception ex) {
     ex.msg = append_frame( ex.msg, Window::get_status);
     throw ex;
   }
   // Special handing for connectivity
   if ( Connectivity::is_element_name( aname)) {
     // Get the corresponding attribute object.
     const COM::Connectivity *conn = pn->connectivity( aname);
     if ( conn==NULL) return -1;
     else return conn->status();
   }
   else {
     // Get the corresponding attribute object.
     const COM::Attribute *attr = pn->attribute( aname);
     if ( attr==NULL) return -1;
     else return attr->status();
   }
 }
Attribute * inherit (Attribute * from, const std::string & aname, int inherit_mode, bool withghost, const Attribute * cond, int val) throw (COM_exception)
Inherit the attributes of another window with a different name.
Returns the corresponding value.
Parameters
from attribute being copied from
aname new name of the attribute
cond an integer pane-attribute
val value to be compared against cond
inherit_mode mode of inheritance
withghost wheather ghost nodes/elements should be ignored
Definition at line 334 of file Window.C.
References _pane_map, append_frame, Pane::attribute(), COM_ALL, COM_CONN, COM_ERR_INCOMPATIBLE_ATTRS, COM_MESH, COM_PMESH, Pane::id(), Attribute::inherit(), Pane::inherit(), Pane::INHERIT_COPY, Attribute::pointer(), and Attribute::window().
Referenced by Roccom_base::copy_attribute(), copy_attribute(), and Rocout::write_attr_internal().
 {
   Attribute *a = ((Pane_friend&)_dummy).inherit(from, aname, mode, withghost);
   if ( from->is_windowed()) return a;
   // Copy the panes
   Pane_map &ps = from->window()->_pane_map;
   bool with_conn = from->id()==COM_CONN || from->id()==COM_MESH ||
     from->id()==COM_PMESH || from->id()==COM_ALL;
   bool insert_pane = (mode != Pane::INHERIT_COPY) && with_conn;
   if ( with_conn && aname.size() && from->name() != aname)
     throw COM_exception( COM_ERR_INCOMPATIBLE_ATTRS, append_frame
                          (from->fullname()+" and " +aname,
                           Window::inherit));
   if ( cond && cond->window()!=from->window()) {
     throw COM_exception( COM_ERR_INCOMPATIBLE_ATTRS, append_frame
                          (from->fullname()+" and "+cond->fullname(),
                           Window::inherit));
   }
   for ( Pane_map::iterator ppit = ps.begin(); ppit!=ps.end(); ++ppit) {
     Pane *ppn=ppit->second;
     const int *cnd = NULL;
     if ( cond) {
       const Attribute *cond_pn = ppn->attribute( cond->id());
       cnd = (const int*)cond_pn->pointer();
     }
     // Inherit the pane if the condition was set to an variable (cnd!=NULL),
     // or set to to pane ID (cnd==NULL && val!=0), or not set.
     if ( !cond && (val==0 || val==ppn->id()) || cnd && *cnd == val) {
       // Create new panes only when we are inheriting the mesh.
       Pane_friend *pn;
       if ( insert_pane)
         pn = (Pane_friend*)( &pane( ppit->first, true));
       else {
         Pane_map::iterator it = _pane_map.find( ppit->first);
         pn = ( it!=_pane_map.end())?(Pane_friend*)(it->second):NULL;
       }
       if ( pn)
         pn->inherit( ppn->attribute( from->id()), aname, mode, withghost);
     }
   }
   return a;
 }
void init_done (bool pane_changed = true) throw (COM_exception)
Perform some final checking of the window.
Definition at line 388 of file Window.C.
References append_frame, COM_ERR_INIT_DONE_PANEMAP, i, j, and max().
{
   // Loop through the attributes.
   if ( _status == STATUS_SHRUNK) {
     int max_id=0;
     for (Attr_map::iterator it=_attr_map.begin(); it!=_attr_map.end(); ++it) {
       int id = it->second->id(), ncomp=it->second->size_of_components();
       max_id = std::max( max_id, id+ncomp+(ncomp>1));
     }
     if (max_id < _last_id) _last_id = max_id;
   }
   int npanes = _pane_map.size();
   std::vector< int> pane_ids; pane_ids.reserve(npanes);
   for (Pane_map::iterator it=_pane_map.begin(); it!=_pane_map.end(); ++it) {
     it->second->init_done();
     pane_ids.push_back( it->second->id());
   }
   _status = STATUS_NOCHANGE;
   if ( !pane_changed) {
     if ( npanes>int(_pane_map.size())) {
       throw COM_exception( COM_ERR_INIT_DONE_PANEMAP, append_frame
                            (_name,Window::init_done));
     }
     return;
   }
   // communicate pane mapping
   int flag; MPI_Initialized( &flag);
   if ( _comm == MPI_COMM_NULL) flag = 0;
   // Compute proc_map
   int nprocs;
   if ( flag) MPI_Comm_size( _comm, &nprocs); else nprocs = 1;
   // Obtain the number of panes.
   std::vector<int> npanes_all(nprocs);
   if ( flag)
     MPI_Allgather( &npanes, 1, MPI_INT, &npanes_all[0], 1, MPI_INT, _comm);
   else
     npanes_all[0] = npanes;
   std::vector<int> disps(nprocs+1);
   disps[0]=0;
   for ( int i=0; i<nprocs; ++i) disps[i+1] = disps[i]+npanes_all[i];
   std::vector<int> pane_ids_all( disps[nprocs]);
   if ( flag)
     MPI_Allgatherv( &pane_ids[0], npanes, MPI_INT, &pane_ids_all[0],
                     &npanes_all[0], &disps[0], MPI_INT, _comm);
   else
     pane_ids_all = pane_ids;
   // Build process map
   _proc_map.clear();
   for ( int p=0; p<nprocs; ++p) {
     for ( int j=disps[p], jn=disps[p+1]; j<jn; ++j)
       _proc_map[ pane_ids_all[j]] = p;
   }
 }
int last_attribute_id () const inline
Return the last attribute id.
Definition at line 291 of file Window.h.
References _last_id.
Referenced by Pane::init_done().
 { return _last_id; }
const std::string& name () const inline
Obtain the window's name.
Definition at line 92 of file Window.h.
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Roccom_base::call_function(), Rocblas::copy(), Attribute::fullname(), Rocblas::gen2arg(), Rocblas::rand(), Pane::refresh_connectivity(), Rocblas::swap(), and Rocout::write_attr_internal().
 { return _name; }
Attribute * new_attribute (const std::string & aname, const char loc, const int type, int ncomp, const std::string & unit) throw (COM_exception)
Create a new Attribute object with given properties.
Parameters
aname attribute name.
loc location ('w', 'p', 'n', or 'e').
type base data type.
ncomp number of components.
unit unit of the attribute.
Definition at line 86 of file Window.C.
References append_frame, COM_assertion_msg, COM_ERR_INVALID_ATTRIBUTE_NAME, COM_ERR_INVALID_DIMENSION, COM_ERR_UNKNOWN_DATATYPE, COM_ERR_UNKNOWN_KEYWORD, COM_MAX_TYPEID, COM_NUM_KEYWORDS, Attribute::is_digit(), Connectivity::is_element_name(), and Pane::new_attribute().
 {
   // Special handing for connectivity
   if ( Connectivity::is_element_name( aname) ||
        Attribute::is_digit(aname[0]))
     throw COM_exception( COM_ERR_INVALID_ATTRIBUTE_NAME,append_frame
                          (_name+"."+aname,Window::new_attribute));
   if ( ncomp<=0)
     throw COM_exception( COM_ERR_INVALID_DIMENSION,append_frame
                          (_name+"."+aname,Window::new_attribute));
   if ( loc != 'w' && loc != 'p' && loc != 'e' && loc != 'n' && loc != 'c')
     throw COM_exception( COM_ERR_UNKNOWN_KEYWORD,append_frame
                          (_name+"."+aname,Window::new_attribute));
   if ( type<COM_MIN_TYPEID || type > COM_MAX_TYPEID)
     throw COM_exception( COM_ERR_UNKNOWN_DATATYPE,append_frame
                          (_name+"."+aname,Window::new_attribute));
   // Redefine an attribute if it pre-exists, but ncomp cannot be increased.
   Attr_map::const_iterator it = _attr_map.find( aname);
   if ( it != _attr_map.end() && ncomp > it->second->size_of_components()) {
     COM_assertion_msg( it->second->id()>=COM_NUM_KEYWORDS,
                        "Cannot increase size of keywords");
     delete_attribute( it->first);
     it = _attr_map.end();
   }
   int id = (it==_attr_map.end())?_last_id:it->second->id();
   // Insert the object into both the set and the map.
   Attribute *a = ((Pane_friend&)_dummy).
     new_attribute( aname, id, loc, type, ncomp, unit);
   _attr_map[aname] = a;
   // Propagete onto all existing panes.
   for (Pane_map::iterator it=_pane_map.begin(); it!=_pane_map.end(); ++it) {
     Pane_friend *pn = (Pane_friend*)it->second;
     pn->new_attribute( aname, id, loc, type, ncomp, unit);
   }
   // Update last available id
   if ( it == _attr_map.end()) _last_id = id+ncomp+(ncomp>1);
   if ( _status == STATUS_NOCHANGE) _status = STATUS_CHANGED;
   return a;
 }
Window& operator= (const Window &) private
int owner_rank (const int pane_id) const
Obtain the process rank that owns a given pane.
Returns -1 if the pane cannot be found in the process map.
Definition at line 452 of file Window.C.
References _pane_map, _proc_map, and COM_assertion_msg.
{
   COM_assertion_msg( _pane_map.size()<=_proc_map.size(),
                      "init_done must be called before owner_rank is called");
   Proc_map::const_iterator it = _proc_map.find( pane_id);
   if ( it==_proc_map.end()) return -1;
   else return it->second;
 }
Pane & pane (const int pane_id, bool insert = false) throw (COM_exception)
Find the pane with given ID. If not found, insert a pane with given ID.
Definition at line 769 of file Window.C.
References append_frame, COM_assertion, and COM_ERR_PANE_NOTEXIST.
Referenced by pane(), write_attr_CGNS(), and write_attr_HDF4().
 {
   if ( pid==0) return _dummy;
   COM_assertion( pid>0);
   Pane_map::iterator pit = _pane_map.find( pid);
   if ( pit == _pane_map.end()) {
     if (insert)
       return *(_pane_map[pid] = new Pane( &_dummy, pid));
     else {
         // print missing pane ID and known IDs in the pane map
       std::cerr << "No such Pane ID: " << pid << std::endl;
       std::cerr << "While the known Pane IDs are: [ ";
       Pane_map::iterator pit;
       for ( pit=_pane_map.begin(); pit != _pane_map.end(); ++pit)
         std::cerr << pit->first << " ";
       std::cerr << "]" << std::endl;
       throw COM_exception( COM_ERR_PANE_NOTEXIST, append_frame
                            (_name,Window::pane));
     }
   }
   return *pit->second;
 }
const Pane & pane (const int pane_id) const throw (COM_exception)
Definition at line 794 of file Window.C.
References append_frame, COM_assertion, COM_ERR_PANE_NOTEXIST, and pane().
 {
   if ( pid==0) return _dummy;
   COM_assertion( pid>0);
   Pane_map::const_iterator pit = _pane_map.find( pid);
   if ( pit == _pane_map.end()) {
     throw COM_exception( COM_ERR_PANE_NOTEXIST, append_frame
                          (_name,Window::pane));
   }
   return *pit->second;
 }
void panes (std::vector< int > & ps, int rank = -2)
Obtain all the local panes of the window.
Definition at line 809 of file Window.C.
References _pane_map, _proc_map, _status, COM_assertion_msg, iend, and STATUS_NOCHANGE.
Referenced by Rocblas::axpy_gen(), Rocblas::calc(), Rocblas::calcDot(), Rocblas::gen2arg(), and panes().
 {
   pane_ids.clear();
   if ( rank == -2) {
     pane_ids.reserve( _pane_map.size());
     for ( Pane_map::iterator it=_pane_map.begin(); it != _pane_map.end(); ++it)
       pane_ids.push_back( it->first);
   }
   else {
     COM_assertion_msg( _status == STATUS_NOCHANGE,
                        "Can only obtain panes after calling window_init_done");
     std::map<int,int>::const_iterator it, iend;
     for ( it=_proc_map.begin(), iend=_proc_map.end(); it!= iend; ++it) {
       if ( rank==-1 || it->second == rank)
         pane_ids.push_back( it->first);
     }
   }
 }
void panes (std::vector< Pane * > & ps)
Obtain all the local panes of the window.
Definition at line 833 of file Window.C.
References _pane_map.
 {
   ps.reserve( _pane_map.size());
   Pane_map::iterator it=_pane_map.begin();
   for ( ; it != _pane_map.end(); ++it)
     ps.push_back( it->second);
 }
void panes (std::vector< const Pane * > & ps) const inline
Obtain all the local panes of the window.
Definition at line 324 of file Window.h.
References panes().
   { const_cast<Window*>(this)->panes( (std::vector<Pane*> &)ps); }
const Proc_map& proc_map () const inline
Obtain the process map.
Definition at line 294 of file Window.h.
References _proc_map.
 { return _proc_map; }
void reinit_attr (Attribute * attr, OP_Init op, void ** addr = NULL, int strd = 0, int cap = 0) throw (COM_exception) protected
Implementation for setting (op==OP_SET or OP_SET_CONST), allocating (op==OP_ALLOC), resizing (op==OP_RESIZE) and deallocating (op==OP_DEALLOC) an array for a specific attribute.
Parameters
attr attribute
op Operation (OP_SET, OP_SET_CONST, OP_ALLOC, OP_RESIZE)
addr address
strd stride
cap capacity
Definition at line 717 of file Window.C.
References addr, cap, COM_ALL, COM_assertion, COM_ATTS, Pane::id(), iend, Pane::OP_SET, Pane::OP_SET_CONST, Pane::reinit_attr(), and strd.
Referenced by dealloc_array(), and resize_array().
 {
   int aid = a->id();
   if ( a->location()=='w')
     // Initialize window attributes in dummy pane
     ((Pane_friend&)_dummy).reinit_attr( aid, op, addr, strd, cap);
   else {
     // Initialize other attributes in regular panes
     Pane *pn = a->pane();
     if ( pn->id()>0)
       ((Pane_friend*)pn)->reinit_attr( aid, op, addr, strd, cap);
     else {
       if ( aid == COM_ALL || aid == COM_ATTS)
         ((Pane_friend&)_dummy).reinit_attr( aid, op, addr, strd, cap);
       COM_assertion( op != Pane::OP_SET && op != Pane::OP_SET_CONST );
       // Loop through the panes to initialize each pane
       for (Pane_map::iterator it=_pane_map.begin(), iend=_pane_map.end();
            it != iend; ++it) {
         ((Pane_friend*)it->second)->reinit_attr( aid, op, NULL, strd, cap);
       }
       if ( addr) *addr= NULL; // Do not return any address.
       return;
     }
   }
 }
void reinit_conn (Connectivity * con, OP_Init op, int ** addr = NULL, int strd = 0, int cap = 0) throw (COM_exception) protected
Template implementation for setting (op==OP_SET or OP_SET_CONST), allocating (op==OP_ALLOC), resizing (op==OP_RESIZE) and deallocating (op==OP_DEALLOC) an array for a specific connectivity table.
Parameters
attr connectivity table
op Operation (OP_SET, OP_SET_CONST, OP_ALLOC, OP_RESIZE)
addr address
strd stride
cap capacity
Definition at line 747 of file Window.C.
References addr, cap, COM_assertion, Pane::id(), iend, Pane::OP_SET, Pane::OP_SET_CONST, Connectivity::parent(), and strd.
Referenced by dealloc_array(), and resize_array().
 {
   Pane *pn = con->pane();
   if ( pn->id()==0) {
     COM_assertion( op != Pane::OP_SET && op != Pane::OP_SET_CONST);
     // Loop through the panes to proecess the connectivity in each pane.
     for (Pane_map::iterator it=_pane_map.begin(), iend=_pane_map.end();
          it != iend; ++it) {
       Connectivity *c=((Pane_friend*)it->second)->connectivity( con->name());
       if ( c && !c->parent())
         ((Pane_friend*)it->second)->reinit_conn( c, op, NULL, strd, cap);
     }
     if ( addr) *addr= NULL; // Do not return address.
     return;
   }
   else {
     ((Pane_friend*)pn)->reinit_conn( con, op, addr, strd, cap);
   }
 }
void resize_array (const std::string & aname, const int pane_id, void ** addr, int strd = -1, int cap = 0) throw (COM_exception)
Resize memory for an attribute for a specific pane and set addr to the address.
set_array, alloc_array, append_array
Definition at line 261 of file Window.C.
References addr, append_frame, cap, COM_ERR_ATTRIBUTE_NOTEXIST, Connectivity::is_element_name(), Pane::OP_RESIZE, pane_id, and strd.
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane &pn = pane(pane_id,true);
     Connectivity *con = ((Pane_friend&)pn).connectivity( aname);
     if ( con==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname,Window::resize_array));
     reinit_conn( con, Pane::OP_RESIZE, (int**)addr, strd, cap);
   }
   else {
     Attribute *a = pane( pane_id,true).attribute( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname,Window::resize_array));
     reinit_attr( a, Pane::OP_RESIZE, addr, strd, cap);
   }
 }
void resize_array (Attribute * a, void ** addr, int strd = -1, int cap = 0) throw (COM_exception) inline
Definition at line 166 of file Window.h.
References Pane::OP_RESIZE, and reinit_attr().
   { reinit_attr( a, Pane::OP_RESIZE, addr, strd, cap); }
void resize_array (Connectivity * c, void ** addr, int strd = -1, int cap = 0) throw (COM_exception) inline
Definition at line 170 of file Window.h.
References cap, Pane::OP_RESIZE, reinit_conn(), and strd.
   { reinit_conn( c, Pane::OP_RESIZE, (int**)addr, strd, cap); }
void set_array (const std::string & aname, const int pane_id, void * addr, int strd = 0, int cap = 0, bool is_const = false) throw (COM_exception)
Associate an array with an attribute for a specific pane.
Parameters
aname attribute name
pane_id pane ID
addr address of the array
strd Stride between two items of each component
cap capacity of the array alloc_array, resize_array
Definition at line 212 of file Window.C.
References addr, append_frame, cap, COM_ERR_ATTRIBUTE_NOTEXIST, Connectivity::is_element_name(), Pane::OP_SET, Pane::OP_SET_CONST, pane_id, and strd.
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane &pn = pane(pane_id,true);
     Connectivity *con = ((Pane_friend&)pn).connectivity( aname,true);
     if ( con==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname,Window::set_array));
     reinit_conn( con, is_const?Pane::OP_SET_CONST:Pane::OP_SET,
                  &(int*&)addr, strd, cap);
   }
   else {
     Attribute *a = pane( pane_id,true).attribute( aname);
     if ( a==NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST, append_frame
                            (name()+"."+aname,Window::set_array));
     reinit_attr( a, is_const?Pane::OP_SET_CONST:Pane::OP_SET,
                  &addr, strd, cap);
   }
 }
void set_function (const std::string & fname, Func_ptr func, const std::string & intents, const COM_Type * types, Attribute * a, bool if_f90 = false) throw (COM_exception)
Initialize a Function record.
Definition at line 59 of file Window.C.
References append_frame, and COM_WARN_DUP_FUNC.
{
   if ( _func_map.find( fname) != _func_map.end())
     throw COM_exception(COM_WARN_DUP_FUNC, append_frame
                         (_name+"."+fname,Window::init_function));
   _func_map[fname] = Function( func, intents, types, a, is_f90);
 }
void set_function (const std::string & fname, Member_func_ptr func, const std::string & intents, const COM_Type * types, Attribute * a, bool if_f90 = false) throw (COM_exception)
Initialize a Function record.
Definition at line 72 of file Window.C.
References _func_map, _name, append_frame, and COM_WARN_DUP_FUNC.
{
   if ( _func_map.find( fname) != _func_map.end())
     throw COM_exception(COM_WARN_DUP_FUNC, append_frame
                         (_name+"."+fname,Window::init_function));
   _func_map[fname] = Function( func, intents, types, a);
 }
void set_size (const std::string & aname, int pane_id, int nitems, int ng = 0) throw (COM_exception)
Set the sizes of an attribute for a specific pane.
Parameters
aname attribute name
pane_id pane ID
nitems total number of items (including ghosts)
ng number of ghosts
Definition at line 182 of file Window.C.
References append_frame, COM_ERR_ATTRIBUTE_NOTEXIST, Pane::connectivity(), Attribute::id(), iend, Connectivity::is_element_name(), Attribute::is_windowed(), and Pane::set_size().
 {
   if ( Connectivity::is_element_name( aname)) {
     Pane_friend &pn = (Pane_friend&)pane(pid,true);
     Connectivity *con = pn.connectivity( aname,true);
     pn.set_size( con, nitems, ng);
   }
   else {
     Attribute *a = attribute(aname);
     if ( a == NULL)
       throw COM_exception( COM_ERR_ATTRIBUTE_NOTEXIST,append_frame
                            (_name+"."+aname,Window::set_size));
     if ( a->is_windowed())
       ((Pane_friend&)_dummy).set_size( a, nitems, ng);
     else if ( pid==0) {
       // Loop through the panes to set the sizes.
       for (Pane_map::iterator it=_pane_map.begin(), iend=_pane_map.end();
            it != iend; ++it) {
         ((Pane_friend*)it->second)->set_size
           ( it->second->attribute( a->id()), nitems, ng);
       }
     }
     else
       ((Pane_friend&)pane(pid,true)).set_size( a, nitems, ng);
   }
 }
int size_of_panes () const inline
Obtain the number of local panes in the window.
Definition at line 281 of file Window.h.
 { return _pane_map.size(); }
int size_of_panes_global () const inline
Obtain the total number of panes in the window on all processes.
Definition at line 284 of file Window.h.
References _proc_map.
 { return _proc_map.size(); }
Member Data Documentation
Attr_map _attr_map protected
Map from attribute names to their metadata.
It does not contain individual components.
Definition at line 379 of file Window.h.
Referenced by Window().
MPI_Comm _comm protected
the MPI communicator of the window.
Definition at line 387 of file Window.h.
Referenced by get_communicator().
Pane _dummy protected
Dummy pane.
Definition at line 377 of file Window.h.
Referenced by attribute(), attributes(), and Window().
Func_map _func_map protected
Map from function names to their metadata.
Definition at line 381 of file Window.h.
Referenced by function(), and set_function().
int _last_id protected
The last used attribute index.
The next available one is _last_id+1.
Definition at line 385 of file Window.h.
Referenced by last_attribute_id().
std::string _name protected
Name of the window.
Definition at line 378 of file Window.h.
Referenced by set_function().
Pane_map _pane_map protected
Map from pane ID to their metadata.
Definition at line 382 of file Window.h.
Referenced by delete_pane(), inherit(), owner_rank(), panes(), and ~Window().
Proc_map _proc_map protected
Map from pane ID to process ranks.
Definition at line 383 of file Window.h.
Referenced by owner_rank(), panes(), proc_map(), and size_of_panes_global().
int _status protected
Status of the window.
Definition at line 389 of file Window.h.
Referenced by panes().
The documentation for this class was generated from the following files:
Window.h
Window.C