Rocstar: FullyCoupling Class Reference
FullyCoupling Class Reference
#include <Coupling.h>
Public Member Functions
FullyCoupling (const char *coupl_name, const char *fluidname, const char *solidname, Control_parameters *p, const RocmanControl_parameters *mp)
FullyCoupling (const char *coupl_name, const char *fluidname, const char *solidname, const char *burnname, Control_parameters *p, const RocmanControl_parameters *mp)
virtual void update_integrals (double currentTime)
virtual void update_distances (double currentTime)
virtual void reload_rocface (const RocmanControl_parameters *param)
Public Member Functions inherited from Coupling
Coupling (const char *coupl_name, const char *name, Control_parameters *p, const RocmanControl_parameters *mp)
Constructor. Derived class will add actions for the coupling scheme.
Coupling (const char *coupl_name, const char *fluidname, const char *solidname, Control_parameters *p, const RocmanControl_parameters *mp)
Coupling (const char *coupl_name, const char *fluidname, const char *solidname, const char *burnname, Control_parameters *p, const RocmanControl_parameters *mp)
virtual ~Coupling ()
Destructor.
const char * name ()
Agent * add_agent (Agent *)
Add new agent.
void schedule ()
Schedule the top-level actions of the coupling scheme and the actions of the agents.
void init (double t, double dt, int reinit=0)
Invoke initialization of the actions in the scheduler and the agents.
void initialize (int reinit=0)
void finalize ()
Invoke finalization of the actions in the scheduler and the agents.
double run (double t, double dt, int iPredCorr, double zoom)
Invoke the scheduler.
void run_initactions (double t, double dt)
void input (double t)
Invoke input functions of the agents.
int get_ipc () const
int get_max_ipc () const
int initial_start () const
int in_restart () const
int initial_remeshed () const
true if in initialization step and remeshed is true
int new_start (double t) const
void init_convergence (int iPredCorr)
int check_convergence ()
void output_restart_files (double t)
void output_visualization_files (double t)
const Control_parameters * get_control_param ()
const RocmanControl_parameters * get_rocmancontrol_param ()
void read_restart_info ()
void write_restart_info (double CurrentTime, int iStep)
void restart_at_time (double t, int step)
void print (const char *fname)
void Interrupt (int *, const char *)
int ProcessInterrupt ()
Protected Attributes
FluidAgent * fluid_agent
SolidAgent * solid_agent
BurnAgent * burn_agent
Protected Attributes inherited from Coupling
std::string coupling_name
vector< std::string > modules
AgentList agents
UserScheduler scheduler
UserScheduler init_scheduler
int comm_rank
int init_started
int restarting
int init_remeshed
int iPredCorr
int maxPredCorr
Control_parameters * param
const RocmanControl_parameters * rocmanparam
std::string restartInfo
int overwrite_integ
std::string integFname
int overwrite_dist
std::string distFname
Additional Inherited Members
Protected Member Functions inherited from Coupling
void callMethod (Scheduler_voidfn1_t fn, double t)
std::string normalize_modname (const char *mod)
Detailed Description
Definition at line 205 of file Coupling.h.
Constructor & Destructor Documentation
FullyCoupling (const char * coupl_name, const char * fluidname, const char * solidname, Control_parameters * p, const RocmanControl_parameters * mp) inline
Definition at line 211 of file Coupling.h.
                                                                                                                                                 :
       Coupling(coupl_name, fluidname, solidname, p, mp), burn_agent(NULL) {}
FullyCoupling (const char * coupl_name, const char * fluidname, const char * solidname, const char * burnname, Control_parameters * p, const RocmanControl_parameters * mp) inline
Definition at line 213 of file Coupling.h.
                                                                                                                                                                       :
       Coupling(coupl_name, fluidname, solidname, burnname, p, mp) {}
Member Function Documentation
void reload_rocface (const RocmanControl_parameters * param) virtual
Reimplemented from Coupling.
Definition at line 753 of file Coupling.C.
References _load_rocface(), fluid_agent, and solid_agent.
 {
   _load_rocface(fluid_agent, solid_agent, param);
 }
void update_distances (double currentTime) virtual
Reimplemented from Coupling.
Definition at line 714 of file Coupling.C.
References COM_call_function(), COM_get_function_handle(), Coupling::comm_rank, Agent::communicator, Coupling::distFname, cimg_library::cimg::fclose(), fluid_agent, cimg_library::cimg::fopen(), Agent::get_communicator(), MAN_DEBUG, RocBlas::max_scalar_MPI, RocBlas::min_scalar_MPI, MPI_COMM_WORLD, FluidAgent::nc_hdl, FluidAgent::nc_tmp_hdl, RocBlas::nrm2, Coupling::overwrite_dist, solid_agent, FluidAgent::sq_dist_hdl, sqrt(), RocBlas::sub, RocBlas::sum_scalar_MPI, and SolidAgent::y_hdl.
 {
   double dist_max=-1, dist_min=-1, dist_nrm2=-1;
   MPI_Comm communicator = fluid_agent->get_communicator();
   int RFC_interpolate = COM_get_function_handle("RFC.interpolate");
   COM_call_function( RFC_interpolate, &solid_agent->y_hdl, &fluid_agent->nc_tmp_hdl);
   COM_call_function( RocBlas::sub, &fluid_agent->nc_tmp_hdl, &fluid_agent->nc_hdl, &fluid_agent->nc_tmp_hdl);
   COM_call_function( RocBlas::nrm2, &fluid_agent->nc_tmp_hdl, &fluid_agent->sq_dist_hdl);
   COM_call_function( RocBlas::max_scalar_MPI, &fluid_agent->sq_dist_hdl, &dist_max, &communicator);
   COM_call_function( RocBlas::min_scalar_MPI, &fluid_agent->sq_dist_hdl, &dist_min, &communicator);
   COM_call_function( RocBlas::sum_scalar_MPI, &fluid_agent->sq_dist_hdl, &dist_nrm2, &communicator);
   if ( comm_rank == 0) {
        FILE *fp;
        if ( overwrite_dist)
          fp = fopen(distFname.c_str(), "w");
        else
          fp = fopen(distFname.c_str(), "a");
        if (fp == NULL) {
          std::cerr << "Rocstar: Failed to open distance file, " << distFname
                    << "." << std::endl;
          MPI_Abort( MPI_COMM_WORLD, -1);
        }
        MAN_DEBUG(3, ("Rocstar: FullyCoupling::update_distances with t: %f.\n", currentTime));
        if ( overwrite_dist) {
          fprintf( fp, "# time    distance-min    distance-max    distance-norm2  \n");
          overwrite_dist = 0;
        }
        fprintf( fp, "%.18le %.18le %.18le %.18le\n",
              currentTime, sqrt(dist_min), sqrt(dist_max), sqrt(dist_nrm2));
        fclose( fp);
   }
 }
void update_integrals (double currentTime) virtual
Reimplemented from Coupling.
Definition at line 676 of file Coupling.C.
References Coupling::agents, Coupling::comm_rank, cimg_library::cimg::fclose(), fluid_agent, cimg_library::cimg::fopen(), Agent::get_integrals(), i, Coupling::integFname, MAN_DEBUG, MAN_INTEG_IBAREA, MAN_INTEG_INBAREA, MAN_INTEG_MASS, MAN_INTEG_VOL, MAN_INTEG_VOL_UND, MPI_COMM_WORLD, n, Coupling::overwrite_integ, and solid_agent.
 {
   int i, n, count=0;
   for ( i=0, n=agents.size(); i<n; ++i) {
     count += agents[i]->compute_integrals();
   }
   if ( comm_rank == 0 && count == 2) {
        FILE *fp;
        if ( overwrite_integ)
          fp = fopen(integFname.c_str(), "w");
        else
          fp = fopen(integFname.c_str(), "a");
        if (fp == NULL) {
          std::cerr << "Rocstar: Failed to open integral file, "
                    << integFname << "." << std::endl;
          MPI_Abort( MPI_COMM_WORLD, -1);
        }
        MAN_DEBUG(3, ("Rocstar: FullyCoupling::update_integrals with t: %f.\n", currentTime));
        if ( overwrite_integ) {
          fprintf( fp, " time    f-volume        s-volume        f-mass          s-mass          f-burn area     s-burn area     f-non-burn area s-non-burn area s-volume-undef\n");
          overwrite_integ = 0;
        }
        double *f_integrals = fluid_agent->get_integrals();
        double *s_integrals = solid_agent->get_integrals();
        fprintf( fp, "%.18le %.18le %.18le %.18le %.18le %.18le %.18le %.18le %.18le %.18le\n",
              currentTime,
              f_integrals[MAN_INTEG_VOL], s_integrals[MAN_INTEG_VOL],
              f_integrals[MAN_INTEG_MASS], s_integrals[MAN_INTEG_MASS],
              f_integrals[MAN_INTEG_IBAREA], s_integrals[MAN_INTEG_IBAREA],
              f_integrals[MAN_INTEG_INBAREA], s_integrals[MAN_INTEG_INBAREA],
              f_integrals[MAN_INTEG_VOL_UND]);
        fclose( fp);
   }
 }
Member Data Documentation
BurnAgent* burn_agent protected
Definition at line 209 of file Coupling.h.
FluidAgent* fluid_agent protected
Definition at line 207 of file Coupling.h.
Referenced by reload_rocface(), update_distances(), and update_integrals().
SolidAgent* solid_agent protected
Definition at line 208 of file Coupling.h.
Referenced by reload_rocface(), update_distances(), and update_integrals().
The documentation for this class was generated from the following files:
Coupling.h
Coupling.C