Rocstar: rflu_moddifferentiationbfaces Module Reference
rflu_moddifferentiationbfaces Module Reference
Public Member Functions
subroutine, public rflu_computegradbfaces_1d (pRegion, pPatch, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
subroutine, public rflu_computegradbfaces (pRegion, pPatch, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
subroutine rflu_computebfgradconstr (pRegion, pPatch, iBegVar, iEndVar, iBegGrad, iEndGrad, varInfo, var, grad)
subroutine, public rflu_computebfgradconstrwrapper (pRegion, pPatch, iBegVar, iEndVar, iBegGrad, iEndGrad, varInfo, var, grad)
subroutine, public rflu_computegradbfaceswrapper (pRegion, pPatch, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModDifferentiationBFaces.F90,v $ $Revision: 1.6 $'
Detailed Description
Definition at line 40 of file RFLU_ModDifferentiationBFaces.F90.
Member Function/Subroutine Documentation
subroutine rflu_computebfgradconstr (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, integer, dimension(ibegvar:iendvar), intent(in) varInfo, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 637 of file RFLU_ModDifferentiationBFaces.F90.
References Line_2< R, T >::a(), ainv(), moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), max(), moderror::registerfunction(), rflu_modconstraintutils::rflu_getconstrtype(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_invertmatrixsvd(), sqrt(), StopWatch::stop(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_computebfgradconstrwrapper().
subroutine, public rflu_computebfgradconstrwrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, integer, dimension(ibegvar:iendvar), intent(in) varInfo, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 1199 of file RFLU_ModDifferentiationBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_computebfgradconstr().
Referenced by rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modresidual::rflu_res_computeresidual(), viscousfluxes(), and viscousfluxesmp().
subroutine, public rflu_computegradbfaces (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 343 of file RFLU_ModDifferentiationBFaces.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), moderror::registerfunction(), rflu_invertmatrixsvd(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_computegradbfaceswrapper().
subroutine, public rflu_computegradbfaces_1d (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 102 of file RFLU_ModDifferentiationBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), rflu_modweights::rflu_computewtsx2c_1d(), and rflu_modpatchutils::rflu_getpatchnormaldirection().
Referenced by rflu_computegradbfaceswrapper().
subroutine, public rflu_computegradbfaceswrapper (type(t_region), pointer pRegion, type(t_patch), pointer pPatch, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 1285 of file RFLU_ModDifferentiationBFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_computegradbfaces(), and rflu_computegradbfaces_1d().
Referenced by rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modnscbc::rflu_nscbc_comprhs(), rflu_modresidual::rflu_res_computeresidual(), turb_lesgeteddyvis(), turb_ranssavisflux(), viscousfluxes(), and viscousfluxesmp().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModDifferentiationBFaces.F90,v $ $Revision: 1.6 $' private
Definition at line 65 of file RFLU_ModDifferentiationBFaces.F90.
The documentation for this module was generated from the following file:
RFLU_ModDifferentiationBFaces.F90