Rocstar: rflu_moddifferentiationcells Module Reference
rflu_moddifferentiationcells Module Reference
Public Member Functions
subroutine rflu_computegradcells_2d (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
subroutine, public rflu_computegradcellswrapper (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, varInfo, var, grad)
Private Member Functions
subroutine rflu_computegradcells_1d (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
subroutine rflu_computegradcells_3d (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
subroutine rflu_computegradcellsfast_2d (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
subroutine rflu_computegradcellsfast_3d (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad)
subroutine rflu_computegradcellsconstr (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, varInfo, var, grad)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModDifferentiationCells.F90,v $ $Revision: 1.12 $'
Detailed Description
Definition at line 39 of file RFLU_ModDifferentiationCells.F90.
Member Function/Subroutine Documentation
subroutine rflu_computegradcells_1d (type(t_region), pointer pRegion, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 95 of file RFLU_ModDifferentiationCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Generic_element_2::order(), moderror::registerfunction(), and rflu_modweights::rflu_computewtsx2c_1d().
Referenced by rflu_computegradcellswrapper().
subroutine rflu_computegradcells_2d (type(t_region), pointer pRegion, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 331 of file RFLU_ModDifferentiationCells.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), moderror::errorstop(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
subroutine rflu_computegradcells_3d (type(t_region), pointer pRegion, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 503 of file RFLU_ModDifferentiationCells.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
subroutine rflu_computegradcellsconstr (type(t_region), pointer pRegion, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, integer, dimension(ibegvar:iendvar), intent(in) varInfo, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 1181 of file RFLU_ModDifferentiationCells.F90.
References Line_2< R, T >::a(), ainv(), moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), max(), moderror::registerfunction(), rflu_modconstraintutils::rflu_getconstrtype(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_invertmatrixsvd(), sqrt(), StopWatch::stop(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_computegradcellswrapper().
subroutine rflu_computegradcellsfast_2d (type(t_region), pointer pRegion, integer iBegVar, integer iEndVar, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 693 of file RFLU_ModDifferentiationCells.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), moderror::errorstop(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_computegradcellswrapper().
subroutine rflu_computegradcellsfast_3d (type(t_region), pointer pRegion, integer iBegVar, integer iEndVar, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad) private
Definition at line 925 of file RFLU_ModDifferentiationCells.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), moderror::registerfunction(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_computegradcellswrapper().
subroutine, public rflu_computegradcellswrapper (type(t_region), pointer pRegion, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, integer, dimension(ibegvar:iendvar), intent(in) varInfo, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 1612 of file RFLU_ModDifferentiationCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_computegradcells_1d(), rflu_computegradcellsconstr(), rflu_computegradcellsfast_2d(), and rflu_computegradcellsfast_3d().
Referenced by cellgradientsmp(), rflu_computeexactflowerror(), rflu_modplottingvars::rflu_computeplottingvarscore(), rflu_modplottingvars::rflu_computeplottingvarsdisc(), rflu_modplottingvars::rflu_computeplottingvarsgraderr(), rflu_modplottingvars::rflu_computeplottingvarsvort(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), and rflu_modresidual::rflu_res_computeresidual().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModDifferentiationCells.F90,v $ $Revision: 1.12 $' private
Definition at line 61 of file RFLU_ModDifferentiationCells.F90.
The documentation for this module was generated from the following file:
RFLU_ModDifferentiationCells.F90