Rocstar: Scaling_repS3< FT > Class Template Reference
Scaling_repS3< FT > Class Template Reference
#include <Aff_transformationS3.h>
Public Member Functions
Scaling_repS3 ()
Scaling_repS3 (const FT &s)
~Scaling_repS3 ()
PointS3< FT > transform (const PointS3< FT > &p) const
VectorS3< FT > transform (const VectorS3< FT > &v) const
DirectionS3< FT > transform (const DirectionS3< FT > &d) const
Aff_transformationS3< FT > inverse () const
Aff_transformationS3< FT > general_form () const
Aff_transformationS3< FT > transpose () const
virtual bool is_even () const
virtual FT cartesian (int i, int j) const
virtual std::ostream & print (std::ostream &os) const
Public Member Functions inherited from Aff_transformation_rep_baseS3< FT >
virtual ~Aff_transformation_rep_baseS3 ()
Private Attributes
FT scalefactor
Friends
std::ostream & operator<< CGAL_NULL_TMPL_ARGS (std::ostream &os, Scaling_repS3< FT > &t)
Aff_transformationS3< FT > operator*CGAL_NULL_TMPL_ARGS (const Aff_transformationS3< FT > &a, const Aff_transformationS3< FT > &b)
Additional Inherited Members
Protected Member Functions inherited from Leda_like_rep
Leda_like_rep ()
virtual ~Leda_like_rep ()
Protected Attributes inherited from Leda_like_rep
int count
Detailed Description
template<class FT>
class Scaling_repS3< FT >
Definition at line 68 of file Aff_transformationS3.h.
Constructor & Destructor Documentation
Scaling_repS3 () inline
Definition at line 406 of file Aff_transformationS3.h.
   {}
Scaling_repS3 (const FT & s) inline
Definition at line 409 of file Aff_transformationS3.h.
                              :
     scalefactor(s)
   {}
~Scaling_repS3 () inline
Definition at line 413 of file Aff_transformationS3.h.
   {}
Member Function Documentation
virtual FT cartesian (int i, int j) const inline virtual
Implements Aff_transformation_rep_baseS3< FT >.
Definition at line 457 of file Aff_transformationS3.h.
References Scaling_repS3< FT >::scalefactor.
   {
     if (i!=j) return FT(0);
     if (i==3) return FT(1);
     return scalefactor;
   }
Aff_transformationS3<FT> general_form () const inline virtual
Implements Aff_transformation_rep_baseS3< FT >.
Definition at line 438 of file Aff_transformationS3.h.
References Scaling_repS3< FT >::scalefactor.
Referenced by Scaling_repS3< FT >::transpose().
   {
     FT ft0(0);
     return Aff_transformationS3<FT>(scalefactor, ft0, ft0,
                                     ft0, scalefactor, ft0,
                                     ft0, ft0, scalefactor);
   }
Aff_transformationS3<FT> inverse () const inline virtual
Implements Aff_transformation_rep_baseS3< FT >.
Definition at line 433 of file Aff_transformationS3.h.
References Scaling_repS3< FT >::scalefactor, and SCALING.
   {
     return Aff_transformationS3<FT>(SCALING, FT(1)/scalefactor);
   }
virtual bool is_even () const inline virtual
Implements Aff_transformation_rep_baseS3< FT >.
Definition at line 452 of file Aff_transformationS3.h.
   {
     return true;
   }
virtual std::ostream& print (std::ostream & os) const inline virtual
Implements Aff_transformation_rep_baseS3< FT >.
Definition at line 465 of file Aff_transformationS3.h.
References Scaling_repS3< FT >::scalefactor.
   {
     FT ft0(0);
     os << "                   "<< scalefactor <<' '<< ft0 <<' '<< ft0 << ' '
        << ft0 << "\n";
     os << "                   "<< ft0 <<' '<< scalefactor <<' '<< ft0 << ' '
        << ft0 << "\n";
     os << "                   "<< ft0 <<' '<<  ft0 <<' '<< scalefactor <<' '
        << ft0 << ")\n";
     return os;
   }
PointS3<FT> transform (const PointS3< FT > & p) const inline virtual
Implements Aff_transformation_rep_baseS3< FT >.
Definition at line 416 of file Aff_transformationS3.h.
References Scaling_repS3< FT >::scalefactor, PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
   {
     return PointS3<FT>(scalefactor * p.x(), scalefactor * p.y(),
                        scalefactor * p.z());
   }
VectorS3<FT> transform (const VectorS3< FT > & v) const inline virtual
Implements Aff_transformation_rep_baseS3< FT >.
Definition at line 422 of file Aff_transformationS3.h.
References Scaling_repS3< FT >::scalefactor, VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
   {
     return VectorS3<FT>(scalefactor * v.x(), scalefactor * v.y(),
                         scalefactor * v.z());
   }
DirectionS3<FT> transform (const DirectionS3< FT > & d) const inline virtual
Implements Aff_transformation_rep_baseS3< FT >.
Definition at line 428 of file Aff_transformationS3.h.
   {
     return d;
   }
Aff_transformationS3<FT> transpose () const inline virtual
Implements Aff_transformation_rep_baseS3< FT >.
Definition at line 447 of file Aff_transformationS3.h.
References Scaling_repS3< FT >::general_form().
   {
     return general_form();
   }
Friends And Related Function Documentation
Aff_transformationS3<FT> operator*CGAL_NULL_TMPL_ARGS (const Aff_transformationS3< FT > & a, const Aff_transformationS3< FT > & b) friend
std::ostream& operator<< CGAL_NULL_TMPL_ARGS (std::ostream & os, Scaling_repS3< FT > & t) friend
Member Data Documentation
FT scalefactor private
Definition at line 479 of file Aff_transformationS3.h.
Referenced by Scaling_repS3< FT >::cartesian(), Scaling_repS3< FT >::general_form(), Scaling_repS3< FT >::inverse(), Scaling_repS3< FT >::print(), and Scaling_repS3< FT >::transform().
The documentation for this class was generated from the following file:
Aff_transformationS3.h