Rocstar: rflu_modgridspeedutils Module Reference
rflu_modgridspeedutils Module Reference
Public Member Functions
logical function, public rflu_decideneedgridspeeds (pRegion)
real(rfreal) function, public rflu_descalegridspeed (pRegion, fs)
subroutine, public rflu_descalegridspeeds (pRegion)
subroutine, public rflu_initgridspeedscalefactor (pRegion)
real(rfreal) function, public rflu_scalegridspeed (pRegion, fs)
subroutine, public rflu_scalegridspeeds (pRegion)
subroutine, public rflu_setgridspeedscalefactor (pRegion)
Detailed Description
Definition at line 39 of file RFLU_ModGridSpeedUtils.F90.
Member Function/Subroutine Documentation
logical function, public rflu_decideneedgridspeeds (type(t_region), pointer pRegion)
Definition at line 83 of file RFLU_ModGridSpeedUtils.F90.
Referenced by rflu_modallocatememory::rflu_allocatememorygspeeds(), rflu_initflowsolver(), rfluinit(), and rflupart().
real(rfreal) function, public rflu_descalegridspeed (type(t_region), pointer pRegion, real(rfreal), intent(inout) fs)
Definition at line 138 of file RFLU_ModGridSpeedUtils.F90.
Referenced by rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_modconstraintutils::rflu_getconstrtype(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_putboundaryvalues(), rflu_putboundaryvaluesalpha(), rflu_timestepinviscid(), rflu_timestepviscous(), and rflu_modtimezoom::rflu_timezoomsumaddsource().
subroutine, public rflu_descalegridspeeds (type(t_region), pointer pRegion)
Definition at line 187 of file RFLU_ModGridSpeedUtils.F90.
Referenced by rungekuttamp().
subroutine, public rflu_initgridspeedscalefactor (type(t_region), pointer pRegion)
Definition at line 262 of file RFLU_ModGridSpeedUtils.F90.
Referenced by rflu_initflowsolver().
real(rfreal) function, public rflu_scalegridspeed (type(t_region), pointer pRegion, real(rfreal), intent(inout) fs)
Definition at line 312 of file RFLU_ModGridSpeedUtils.F90.
Referenced by rflu_modtimezoom::rflu_timezoomsumaddsource().
subroutine, public rflu_scalegridspeeds (type(t_region), pointer pRegion)
Definition at line 361 of file RFLU_ModGridSpeedUtils.F90.
Referenced by rungekuttamp().
subroutine, public rflu_setgridspeedscalefactor (type(t_region), pointer pRegion)
Definition at line 434 of file RFLU_ModGridSpeedUtils.F90.
References moderror::errorstop(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rungekuttamp().
The documentation for this module was generated from the following file:
RFLU_ModGridSpeedUtils.F90