Rocstar: TSTTIterator Class Reference
TSTTIterator Class Reference
Wrapper around single-entity TSTT interator.
Public Member Functions
TSTTIterator (TSTTM::Entity &mesh, void *meshset, TSTTM::EntityType type, TSTTM::EntityTopology topo, MsqError &err)
virtual void restart ()
reset iterator
virtual Mesh::EntityHandle operator* () const
get current entity handle
virtual bool is_at_end () const
check if any remaining entity handles
virtual void operator++ ()
step
virtual ~TSTTIterator ()
Public Member Functions inherited from EntityIterator
virtual ~EntityIterator ()
Private Member Functions
void get_next_entity ()
Advance the iterator to the next entity.
Private Attributes
TSTTM::Entity tsttMesh
TSTT mesh interface.
void * tsttIter
TSTT iterator handle.
bool notAtEnd
Flag to mark if end of iterator had been reached.
void * entityHandle
Current TSTT entity handle.
Detailed Description
Wrapper around single-entity TSTT interator.
Definition at line 75 of file MeshTSTT.cpp.
Constructor & Destructor Documentation
TSTTIterator (TSTTM::Entity & mesh, void * meshset, TSTTM::EntityType type, TSTTM::EntityTopology topo, MsqError & err)
Parameters
mesh The TSTT mesh interface instance
meshset The meshset to iterate over
type TSTT type in meshset to iterate over
topo TSTT topology in meshset to iterate over
Definition at line 117 of file MeshTSTT.cpp.
References TSTTIterator::get_next_entity(), MsqError::INTERNAL_ERROR, MSQ_SETERR, Mesquite::process_tstt_error(), TSTTIterator::tsttIter, and TSTTIterator::tsttMesh.
   : tsttMesh(mesh), tsttIter(0), notAtEnd(true), entityHandle(0)
 {
   try {
     tsttMesh.initEntIter( meshset, type, topo, tsttIter );
     get_next_entity();
   }
   catch (TSTTB::Error& tstt_err) {
     MSQ_SETERR(err)( process_tstt_error( tstt_err ), MsqError::INTERNAL_ERROR );
   }
 }
~TSTTIterator () virtual
Definition at line 131 of file MeshTSTT.cpp.
References TSTTIterator::tsttIter, and TSTTIterator::tsttMesh.
 {
   if (tsttIter)
     tsttMesh.endEntIter( tsttIter );
 }
Member Function Documentation
void get_next_entity () inline private
Advance the iterator to the next entity.
Updates entityHandle and notAtEnd
Definition at line 87 of file MeshTSTT.cpp.
References TSTTIterator::entityHandle, TSTTIterator::notAtEnd, TSTTIterator::tsttIter, and TSTTIterator::tsttMesh.
Referenced by TSTTIterator::operator++(), TSTTIterator::restart(), and TSTTIterator::TSTTIterator().
       { notAtEnd = tsttMesh.getNextEntIter( tsttIter, entityHandle ); }
bool is_at_end () const virtual
check if any remaining entity handles
Implements EntityIterator.
Definition at line 154 of file MeshTSTT.cpp.
References TSTTIterator::notAtEnd.
 {
   return !notAtEnd;
 }
Mesh::EntityHandle operator* () const virtual
get current entity handle
Implements EntityIterator.
Definition at line 149 of file MeshTSTT.cpp.
References TSTTIterator::entityHandle.
 {
   return entityHandle;
 }
void operator++ () virtual
step
Implements EntityIterator.
Definition at line 159 of file MeshTSTT.cpp.
References TSTTIterator::get_next_entity(), and Mesquite::process_tstt_error().
 {
   try {
     get_next_entity();
   }
   catch (TSTTB::Error& tstt_err) {
     process_tstt_error( tstt_err );
     throw;
   }
 }
void restart () virtual
reset iterator
Implements EntityIterator.
Definition at line 137 of file MeshTSTT.cpp.
References TSTTIterator::get_next_entity(), Mesquite::process_tstt_error(), TSTTIterator::tsttIter, and TSTTIterator::tsttMesh.
 {
   try {
     tsttMesh.resetEntIter( tsttIter );
     get_next_entity();
   }
   catch (TSTTB::Error& tstt_err) {
     process_tstt_error( tstt_err );
     throw;
   }
 }
Member Data Documentation
void* entityHandle private
Current TSTT entity handle.
Definition at line 81 of file MeshTSTT.cpp.
Referenced by TSTTIterator::get_next_entity(), and TSTTIterator::operator*().
bool notAtEnd private
Flag to mark if end of iterator had been reached.
Definition at line 80 of file MeshTSTT.cpp.
Referenced by TSTTIterator::get_next_entity(), and TSTTIterator::is_at_end().
void* tsttIter private
TSTT iterator handle.
Definition at line 79 of file MeshTSTT.cpp.
Referenced by TSTTIterator::get_next_entity(), TSTTIterator::restart(), TSTTIterator::TSTTIterator(), and TSTTIterator::~TSTTIterator().
TSTTM::Entity tsttMesh private
TSTT mesh interface.
Definition at line 78 of file MeshTSTT.cpp.
Referenced by TSTTIterator::get_next_entity(), TSTTIterator::restart(), TSTTIterator::TSTTIterator(), and TSTTIterator::~TSTTIterator().
The documentation for this class was generated from the following file:
MeshTSTT.cpp