Rocstar: init_py Module Reference
init_py Module Reference
Public Member Functions
subroutine burn_get_film_coeff_1d (bp, p_coor, Ts, Teuler, P_in, Qc, Qcprime)
subroutine burn_init_1d (bp, bflag, Pin, To, rhoc, p_coor, rb, Toa, fr, Tn, Tflame)
Detailed Description
Definition at line 23 of file init_py.f90.
Member Function/Subroutine Documentation
subroutine burn_get_film_coeff_1d (type(parameter_structure), pointer bp, real(dbl), dimension(3), intent(in) p_coor, real(dbl), intent(in) Ts, real(dbl), intent(in) Teuler, real(dbl), intent(in) P_in, real(dbl), intent(out) Qc, real(dbl), intent(out) Qcprime)
Definition at line 30 of file init_py.f90.
References d, max(), merge, and min().
subroutine burn_init_1d (type(parameter_structure), pointer bp, integer, intent(inout) bflag, real(dbl), intent(in) Pin, real(dbl), intent(in) To, real(dbl), intent(in) rhoc, real(dbl), dimension(3), intent(in) p_coor, real(dbl), intent(out) rb, real(dbl), intent(out) Toa, real(dbl), intent(out) fr, real(dbl), dimension(:), intent(out) Tn, real(dbl), intent(out) Tflame)
Definition at line 90 of file init_py.f90.
References i, block::pin(), data_py::polin2(), and data_py::polint().
Referenced by burn_initialize().
The documentation for this module was generated from the following file:
init_py.f90