Rocstar: rflu_modrenumberings Module Reference
rflu_modrenumberings Module Reference
Public Member Functions
subroutine, public rflu_rnmb_buildsbc2pcmap (pRegion, pRegionSerial)
subroutine, public rflu_rnmb_buildsc2pcmap (pRegion, sortFlag)
subroutine, public rflu_rnmb_buildsv2pvmap (pRegion)
subroutine, public rflu_rnmb_createsc2rmap (pRegion)
subroutine, public rflu_rnmb_createpc2scmap (pRegion)
subroutine, public rflu_rnmb_createpbf2sbfmap (pRegion)
subroutine, public rflu_rnmb_createpv2svmap (pRegion)
subroutine, public rflu_rnmb_destroypc2scmap (pRegion)
subroutine, public rflu_rnmb_destroypbf2sbfmap (pRegion)
subroutine, public rflu_rnmb_destroypv2svmap (pRegion)
subroutine, public rflu_rnmb_destroysbc2pcmap (pRegion)
subroutine, public rflu_rnmb_destroysc2pcmap (pRegion)
subroutine, public rflu_rnmb_destroysc2rmap (pRegion)
subroutine, public rflu_rnmb_destroysv2pvmap (pRegion)
subroutine, public rflu_rnmb_readsc2rmap (pRegion)
subroutine, public rflu_rnmb_readpxx2sxxmaps (pRegion)
subroutine, public rflu_rnmb_writesc2rmap (pRegion)
subroutine, public rflu_rnmb_writepxx2sxxmaps (pRegion)
Private Member Functions
subroutine rflu_rnmb_buildsbc2pcmap2d (pRegion)
subroutine rflu_rnmb_buildsbc2pcmap3d (pRegion, pRegionSerial)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRenumberings.F90,v $ $Revision: 1.16 $'
Detailed Description
Definition at line 40 of file RFLU_ModRenumberings.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_rnmb_buildsbc2pcmap (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 111 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_rnmb_buildsbc2pcmap2d(), and rflu_rnmb_buildsbc2pcmap3d().
Referenced by rflupart().
subroutine rflu_rnmb_buildsbc2pcmap2d (type(t_region), pointer pRegion) private
Definition at line 185 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortintegerinteger(), and moderror::registerfunction().
Referenced by rflu_rnmb_buildsbc2pcmap().
subroutine rflu_rnmb_buildsbc2pcmap3d (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial) private
Definition at line 300 of file RFLU_ModRenumberings.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), min(), modsortsearch::quicksortintegerinteger(), and moderror::registerfunction().
Referenced by rflu_rnmb_buildsbc2pcmap().
subroutine, public rflu_rnmb_buildsc2pcmap (type(t_region), pointer pRegion, logical, intent(in), optional sortFlag)
Definition at line 557 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortintegerinteger(), and moderror::registerfunction().
Referenced by plag_rflu_initsolfromserial(), and rflupart().
subroutine, public rflu_rnmb_buildsv2pvmap (type(t_region), pointer pRegion)
Definition at line 675 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortintegerinteger(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_rnmb_createpbf2sbfmap (type(t_region), pointer pRegion)
Definition at line 968 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_initsolfromserial(), rflu_mergepostprocessregions(), rfluinit(), and rflupart().
subroutine, public rflu_rnmb_createpc2scmap (type(t_region), pointer pRegion)
Definition at line 868 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_initsolfromserial(), rflu_mergepostprocessregions(), rfluinit(), and rflupart().
subroutine, public rflu_rnmb_createpv2svmap (type(t_region), pointer pRegion)
Definition at line 1086 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_initsolfromserial(), rflu_mergepostprocessregions(), rflu_modpartitionregion::rflu_part_buildvertexlists(), rfluinit(), and rflupart().
subroutine, public rflu_rnmb_createsc2rmap (type(t_region), pointer pRegion)
Definition at line 774 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_rnmb_destroypbf2sbfmap (type(t_region), pointer pRegion)
Definition at line 1274 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_initsolfromserial(), rflu_mergepostprocessregions(), rfluinit(), and rflupart().
subroutine, public rflu_rnmb_destroypc2scmap (type(t_region), pointer pRegion)
Definition at line 1179 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), rfluinit(), and rflupart().
subroutine, public rflu_rnmb_destroypv2svmap (type(t_region), pointer pRegion)
Definition at line 1370 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_initsolfromserial(), rflu_mergepostprocessregions(), rfluinit(), and rflupart().
subroutine, public rflu_rnmb_destroysbc2pcmap (type(t_region), pointer pRegion)
Definition at line 1463 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_rnmb_destroysc2pcmap (type(t_region), pointer pRegion)
Definition at line 1559 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_rflu_initsolfromserial(), and rflupart().
subroutine, public rflu_rnmb_destroysc2rmap (type(t_region), pointer pRegion)
Definition at line 1652 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_rnmb_destroysv2pvmap (type(t_region), pointer pRegion)
Definition at line 1745 of file RFLU_ModRenumberings.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_rnmb_readpxx2sxxmaps (type(t_region), pointer pRegion)
Definition at line 2037 of file RFLU_ModRenumberings.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by plag_rflu_initsolfromserial(), rflu_mergepostprocessregions(), rfluinit(), and rflupart().
subroutine, public rflu_rnmb_readsc2rmap (type(t_region), pointer pRegion)
Definition at line 1837 of file RFLU_ModRenumberings.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
subroutine, public rflu_rnmb_writepxx2sxxmaps (type(t_region), pointer pRegion)
Definition at line 2422 of file RFLU_ModRenumberings.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflupart().
subroutine, public rflu_rnmb_writesc2rmap (type(t_region), pointer pRegion)
Definition at line 2264 of file RFLU_ModRenumberings.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflupart().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRenumberings.F90,v $ $Revision: 1.16 $' private
Definition at line 79 of file RFLU_ModRenumberings.F90.
The documentation for this module was generated from the following file:
RFLU_ModRenumberings.F90