Rocstar: rflu_modstencilsfaces Module Reference
rflu_modstencilsfaces Module Reference
Public Member Functions
subroutine rflu_buildf2cstencil (pRegion, addBFaces)
subroutine, public rflu_buildf2cstencilwrapper (pRegion, constrInput)
subroutine, public rflu_buildlistcf2cstencil (pRegion)
subroutine, public rflu_createf2cstencilwrapper (pRegion)
subroutine, public rflu_destroyf2cstencilwrapper (pRegion)
subroutine, public rflu_destroylistcf2cstencil (pRegion)
subroutine, public rflu_setinfof2cstencilwrapper (pRegion, orderNominal)
Private Member Functions
subroutine rflu_buildf2cstencil_1d (pRegion)
subroutine rflu_createf2cstencil_1d (pRegion)
subroutine rflu_createf2cstencil (pRegion)
subroutine rflu_destroyf2cstencil_1d (pRegion)
subroutine rflu_destroyf2cstencil (pRegion)
subroutine rflu_nullifyf2cstencil_1d (pRegion)
subroutine rflu_nullifyf2cstencil (pRegion)
subroutine rflu_setinfof2cstencil_1d (pRegion, orderNominalInput)
subroutine rflu_setinfof2cstencil (pRegion, orderNominalInput)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsFaces.F90,v $ $Revision: 1.11 $'
Detailed Description
Definition at line 39 of file RFLU_ModStencilsFaces.F90.
Member Function/Subroutine Documentation
subroutine rflu_buildf2cstencil (type(t_region), pointer pRegion, logical, intent(in) addBFaces)
Definition at line 390 of file RFLU_ModStencilsFaces.F90.
References Line_2< R, T >::a(), ainv(), moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), max(), min(), Generic_element_2::order(), moderror::registerfunction(), rflu_modstencilsutils::rflu_addbfaces(), rflu_modstencilsutils::rflu_addcelllayer(), rflu_modstencilsutils::rflu_addfacevertneighbs(), rflu_modfacelist::rflu_getopposingfaces(), rflu_invertmatrixsvd(), rflu_modstencilsutils::rflu_sortbfaces(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_buildf2cstencilwrapper().
subroutine rflu_buildf2cstencil_1d (type(t_region), pointer pRegion) private
Definition at line 102 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modtools::floatequal(), max(), moderror::registerfunction(), rflu_modstencilsutils::rflu_addcelllayer_1d(), and StopWatch::stop().
Referenced by rflu_buildf2cstencilwrapper().
subroutine, public rflu_buildf2cstencilwrapper (type(t_region), pointer pRegion, integer, intent(in), optional constrInput)
Definition at line 829 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_buildf2cstencil(), and rflu_buildf2cstencil_1d().
Referenced by rflu_initflowsolver(), and rflupick().
subroutine, public rflu_buildlistcf2cstencil (type(t_region), pointer pRegion)
Definition at line 919 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
subroutine rflu_createf2cstencil (type(t_region), pointer pRegion) private
Definition at line 1142 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyf2cstencil().
Referenced by rflu_createf2cstencilwrapper().
subroutine rflu_createf2cstencil_1d (type(t_region), pointer pRegion) private
Definition at line 1043 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyf2cstencil_1d().
Referenced by rflu_createf2cstencilwrapper().
subroutine, public rflu_createf2cstencilwrapper (type(t_region), pointer pRegion)
Definition at line 1240 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_createf2cstencil(), and rflu_createf2cstencil_1d().
Referenced by rflu_initflowsolver(), and rflupick().
subroutine rflu_destroyf2cstencil (type(t_region), pointer pRegion) private
Definition at line 1422 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyf2cstencil().
Referenced by rflu_destroyf2cstencilwrapper().
subroutine rflu_destroyf2cstencil_1d (type(t_region), pointer pRegion) private
Definition at line 1312 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyf2cstencil_1d().
Referenced by rflu_destroyf2cstencilwrapper().
subroutine, public rflu_destroyf2cstencilwrapper (type(t_region), pointer pRegion)
Definition at line 1533 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_destroyf2cstencil(), and rflu_destroyf2cstencil_1d().
Referenced by rflu_endflowsolver(), and rflupick().
subroutine, public rflu_destroylistcf2cstencil (type(t_region), pointer pRegion)
Definition at line 1603 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_endflowsolver().
subroutine rflu_nullifyf2cstencil (type(t_region), pointer pRegion) private
Definition at line 1778 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createf2cstencil(), and rflu_destroyf2cstencil().
subroutine rflu_nullifyf2cstencil_1d (type(t_region), pointer pRegion) private
Definition at line 1695 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createf2cstencil_1d(), and rflu_destroyf2cstencil_1d().
subroutine rflu_setinfof2cstencil (type(t_region), pointer pRegion, integer, intent(in) orderNominalInput) private
Definition at line 1981 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), max(), moderror::registerfunction(), and rflu_computestencilsize().
Referenced by rflu_setinfof2cstencilwrapper().
subroutine rflu_setinfof2cstencil_1d (type(t_region), pointer pRegion, integer, intent(in) orderNominalInput) private
Definition at line 1866 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), max(), and moderror::registerfunction().
Referenced by rflu_setinfof2cstencilwrapper().
subroutine, public rflu_setinfof2cstencilwrapper (type(t_region), pointer pRegion, integer, intent(in) orderNominal)
Definition at line 2098 of file RFLU_ModStencilsFaces.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_setinfof2cstencil(), and rflu_setinfof2cstencil_1d().
Referenced by rflu_initflowsolver(), and rflupick().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModStencilsFaces.F90,v $ $Revision: 1.11 $' private
Definition at line 70 of file RFLU_ModStencilsFaces.F90.
The documentation for this module was generated from the following file:
RFLU_ModStencilsFaces.F90