Rocstar: Vertex_overlay Class Reference
Vertex_overlay Class Reference
#include <HDS_overlay.h>
Public Types
typedef Vertex_overlay Self
typedef Tag_true Supports_vertex_point
typedef Tag_true Supports_vertex_halfedge
typedef Point_3 Point
Public Member Functions
Vertex_overlay ()
Vertex_overlay (const Point &)
~Vertex_overlay ()
RFC_Pane_overlay * pane ()
const RFC_Pane_overlay * pane () const
void set_pane (RFC_Pane_overlay *p)
Halfedge_overlay * halfedge ()
const Halfedge_overlay * halfedge () const
void set_halfedge (Halfedge_overlay *h)
const Point & point () const
Protected Attributes
Halfedge_overlay * hdg
RFC_Pane_overlay * pn
Detailed Description
Definition at line 47 of file HDS_overlay.h.
Member Typedef Documentation
typedef Point_3 Point
Definition at line 58 of file HDS_overlay.h.
typedef Vertex_overlay Self
Definition at line 55 of file HDS_overlay.h.
typedef Tag_true Supports_vertex_halfedge
Definition at line 57 of file HDS_overlay.h.
typedef Tag_true Supports_vertex_point
Definition at line 56 of file HDS_overlay.h.
Constructor & Destructor Documentation
Vertex_overlay () inline
Definition at line 60 of file HDS_overlay.h.
 : hdg(NULL), pn(NULL) {}
Vertex_overlay (const Point &) inline explicit
Definition at line 61 of file HDS_overlay.h.
 : hdg(NULL), pn(NULL) {}
~Vertex_overlay () inline
Definition at line 62 of file HDS_overlay.h.
References hdg, and RFC_assertion_code.
 {  RFC_assertion_code(hdg=NULL); }
Member Function Documentation
Halfedge_overlay* halfedge () inline
Definition at line 73 of file HDS_overlay.h.
References hdg.
Referenced by Overlay::count_subnodes(), RFC_Pane_overlay::evaluate_normals(), HDS_accessor< Tag_true >::get_halfedge(), RFC_Pane_overlay::get_primary(), HDS_accessor< Tag_true >::is_border(), RFC_Pane_overlay::is_primary(), RFC_Window_overlay::is_same_node(), and Overlay::number_a_subnode().
 { return hdg;}
const Halfedge_overlay* halfedge () const inline
Definition at line 74 of file HDS_overlay.h.
References hdg.
 { return hdg;}
RFC_Pane_overlay* pane () inline
Definition at line 69 of file HDS_overlay.h.
References pn.
Referenced by RFC_Pane_overlay::get_counterpart(), HDS_accessor< Tag_true >::get_hds(), HDS_accessor< Tag_true >::get_pane(), RFC_Window_overlay::is_feature_0(), RFC_Window_overlay::is_feature_1(), RFC_Window_overlay::is_on_feature(), RFC_Pane_overlay::is_physical_border(), RFC_Window_overlay::is_same_node(), RFC_Window_overlay::set_feature_0(), RFC_Window_overlay::set_on_feature(), and RFC_Window_overlay::unset_strong_edge().
 { return pn; }
const RFC_Pane_overlay* pane () const inline
Definition at line 70 of file HDS_overlay.h.
References pn.
 { return pn; }
const Point_3 & point () const
Definition at line 40 of file RFC_Window_overlay.C.
Referenced by RFC_Window_overlay::detect_features(), RFC_Window_overlay::evaluate_normals(), Overlay_primitives::get_point(), RFC_Window_overlay::get_tangent(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Overlay::match_features_0(), RFC_Window_overlay::Feature_0::operator<(), RFC_Window_overlay::Feature_0::point(), RFC_Window_overlay::print_features(), Overlay::project_adjacent_green_vertices(), Overlay::project_next_vertex(), RFC_Window_overlay::reduce_coordinates_to_all(), and Overlay::sq_length().
 { return pane()->get_point(this); }
void set_halfedge (Halfedge_overlay * h) inline
Definition at line 75 of file HDS_overlay.h.
References hdg.
Referenced by RFC_Pane_overlay::build_hds().
 { hdg = h;}
void set_pane (RFC_Pane_overlay * p) inline
Definition at line 71 of file HDS_overlay.h.
References pn.
 { pn = p; }
Member Data Documentation
Halfedge_overlay* hdg protected
Definition at line 51 of file HDS_overlay.h.
Referenced by halfedge(), set_halfedge(), and ~Vertex_overlay().
RFC_Pane_overlay* pn protected
Definition at line 52 of file HDS_overlay.h.
Referenced by pane(), and set_pane().
The documentation for this class was generated from the following files:
HDS_overlay.h
RFC_Window_overlay.C