Rocstar: Vector3D Class Reference
Vector3D Class Reference
Vector3D is the object that effeciently stores information about about three-deminsional vectors. It is also the parent class of MsqVertex.
#include <Vector3D.hpp>
Public Member Functions
Vector3D ()
Vector3D (const double &x, const double &y, const double &z)
Vector3D (const double xyz[3])
Vector3D (const Vector3D &to_copy)
double x () const
double y () const
double z () const
void get_coordinates (double &x, double &y, double &z) const
void get_coordinates (double xyz[3]) const
const double & operator[] (size_t index) const
void x (const double x)
void y (const double y)
void z (const double z)
void set (const double x, const double y, const double z)
void set (const double xyz[3])
void set (const Vector3D &to_copy)
double & operator[] (size_t index)
Vector3D & operator= (const Vector3D &to_copy)
Vector3D & operator= (const double &to_copy)
Vector3D operator- () const
Vector3D & operator*= (const double scalar)
Vector3D & operator/= (const double scalar)
divides each Vector3D entry by the given scalar.
Vector3D & operator*= (const Vector3D &rhs)
Vector3D & operator+= (const Vector3D &rhs)
Vector3D & operator-= (const Vector3D &rhs)
int within_tolerance_box (const Vector3D &compare_to, double tolerance) const
double length_squared () const
double length () const
void set_length (const double new_length)
void normalize ()
const double * to_array () const
Vector3D ()
Vector3D (const double &x, const double &y, const double &z)
Vector3D (const double xyz[3])
Vector3D (const Vector3D &to_copy)
double x () const
double y () const
double z () const
void get_coordinates (double &x, double &y, double &z) const
void get_coordinates (double xyz[3]) const
const double & operator[] (size_t index) const
void x (const double x)
void y (const double y)
void z (const double z)
void set (const double x, const double y, const double z)
void set (const double xyz[3])
void set (const Vector3D &to_copy)
double & operator[] (size_t index)
Vector3D & operator= (const Vector3D &to_copy)
Vector3D & operator= (const double &to_copy)
Vector3D operator- () const
Vector3D & operator*= (const double scalar)
Vector3D & operator/= (const double scalar)
Vector3D & operator*= (const Vector3D &rhs)
Vector3D & operator+= (const Vector3D &rhs)
Vector3D & operator-= (const Vector3D &rhs)
int within_tolerance_box (const Vector3D &compare_to, double tolerance) const
double length_squared () const
double length () const
void set_length (const double new_length)
void normalize ()
const double * to_array () const
Static Public Member Functions
static double distance_between (const Vector3D &p1, const Vector3D &p2)
static double interior_angle (const Vector3D &a, const Vector3D &b, MsqError &err)
static Vector3D interpolate (const double param, const Vector3D &p1, const Vector3D &p2)
static double distance_between (const Vector3D &p1, const Vector3D &p2)
static double interior_angle (const Vector3D &a, const Vector3D &b, MsqError &err)
static Vector3D interpolate (const double param, const Vector3D &p1, const Vector3D &p2)
Protected Attributes
double mCoords [3]
Friends
const Vector3D operator+ (const Vector3D &lhs, const Vector3D &rhs)
const Vector3D operator- (const Vector3D &lhs, const Vector3D &rhs)
const Vector3D operator* (const Vector3D &lhs, const double scalar)
lhs * scalar
const Vector3D operator* (const double scalar, const Vector3D &rhs)
scalar * rhs
const Vector3D operator/ (const Vector3D &lhs, const double scalar)
double operator% (const Vector3D &v1, const Vector3D &v2)
dot product
double inner (const Vector3D v1[], const Vector3D v2[], int n)
dot product for array
double operator% (const double scalar, const Vector3D &v2)
scalar * sum_i v2[i]
double operator% (const Vector3D &v1, const double scalar)
scalar * sum_i v1[i]
const Vector3D operator* (const Vector3D &v1, const Vector3D &v2)
cross product
void eqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqTransAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
bool operator== (const Vector3D &lhs, const Vector3D &rhs)
bool operator!= (const Vector3D &lhs, const Vector3D &rhs)
double length (Vector3D *const v, int n)
L2 norm for an array of Vector3Ds.
double Linf (Vector3D *const v, int n)
L inf norm for array of Vector3Ds.
const Vector3D operator+ (const Vector3D &lhs, const Vector3D &rhs)
const Vector3D operator- (const Vector3D &lhs, const Vector3D &rhs)
const Vector3D operator* (const Vector3D &lhs, const double scalar)
lhs * scalar
const Vector3D operator* (const double scalar, const Vector3D &rhs)
scalar * rhs
const Vector3D operator/ (const Vector3D &lhs, const double scalar)
double operator% (const Vector3D &v1, const Vector3D &v2)
dot product
double inner (const Vector3D v1[], const Vector3D v2[], int n)
dot product for array
double operator% (const double scalar, const Vector3D &v2)
scalar * sum_i v2[i]
double operator% (const Vector3D &v1, const double scalar)
scalar * sum_i v1[i]
const Vector3D operator* (const Vector3D &v1, const Vector3D &v2)
cross product
void eqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqTransAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
bool operator== (const Vector3D &lhs, const Vector3D &rhs)
bool operator!= (const Vector3D &lhs, const Vector3D &rhs)
double length (Vector3D *const v, int n)
L2 norm for an array of Vector3Ds.
double Linf (Vector3D *const v, int n)
L inf norm for array of Vector3Ds.
Detailed Description
Vector3D is the object that effeciently stores information about about three-deminsional vectors. It is also the parent class of MsqVertex.
Definition at line 64 of file includeLinks/Vector3D.hpp.
Constructor & Destructor Documentation
Vector3D () inline
Definition at line 171 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
Referenced by Vector3D::operator-().
   {
     mCoords[0] = 0;
     mCoords[1] = 0;
     mCoords[2] = 0;
   }
Vector3D (const double & x, const double & y, const double & z) inline
Definition at line 177 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords, Vector3D::x(), Vector3D::y(), and Vector3D::z().
   {
     mCoords[0] = x;
     mCoords[1] = y;
     mCoords[2] = z;
   }
Vector3D (const double xyz[3]) inline
Definition at line 185 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   { msq_stdc::memcpy(mCoords, xyz, 3*sizeof(double)); }
Vector3D (const Vector3D & to_copy) inline
Definition at line 187 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   { msq_stdc::memcpy(mCoords, to_copy.mCoords, 3*sizeof(double)); }
Vector3D ()
Vector3D (const double & x, const double & y, const double & z)
Vector3D (const double xyz[3])
Vector3D (const Vector3D & to_copy)
Member Function Documentation
double distance_between (const Vector3D & p1, const Vector3D & p2) inline static
Definition at line 373 of file includeLinks/Vector3D.hpp.
References Vector3D::length(), and v.
   {
     Vector3D v = p2 - p1;
     return v.length();
   }
static double distance_between (const Vector3D & p1, const Vector3D & p2) static
void get_coordinates (double & x, double & y, double & z) const inline
Definition at line 197 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
Referenced by NonSmoothSteepestDescent::validity_check(), and MesqPane::vertex_set_coordinates().
   {
     x = mCoords[0];
     y = mCoords[1];
     z = mCoords[2];
   }
void get_coordinates (double & x, double & y, double & z) const
void get_coordinates (double xyz[3]) const
void get_coordinates (double xyz[3]) const inline
Definition at line 203 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   { msq_stdc::memcpy(xyz, mCoords, 3*sizeof(double)); }
double interior_angle (const Vector3D & a, const Vector3D & b, MsqError & err) static
Definition at line 49 of file Misc/Vector3D.cpp.
References cimg_library::acos(), MsqError::INTERNAL_ERROR, len1, len2, Vector3D::length(), and MSQ_SETERR.
   {
     double len1 = lhs.length();
     double len2 = rhs.length();
     double angle_cos = (lhs % rhs)/(len1 * len2);
     if (!finite( angle_cos ))
     {
       MSQ_SETERR(err)(MsqError::INTERNAL_ERROR);
       return 0.0;
     }
     // Adjust the cosine if slightly out of range
     if ((angle_cos > 1.0) && (angle_cos < 1.0001))
       {
         angle_cos = 1.0;
       }
     else if (angle_cos < -1.0 && angle_cos > -1.0001)
       {
         angle_cos = -1.0;
       }
     return msq_stdc::acos(angle_cos);
   }
static double interior_angle (const Vector3D & a, const Vector3D & b, MsqError & err) static
Vector3D interpolate (const double param, const Vector3D & p1, const Vector3D & p2) inline static
Definition at line 430 of file includeLinks/Vector3D.hpp.
   {
     return (1-param)*p1 + param*p2;
   }
static Vector3D interpolate (const double param, const Vector3D & p1, const Vector3D & p2) static
double length () const inline
Definition at line 394 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords, and sqrt().
Referenced by LocalSizeQualityMetric::compute_corner_area(), MsqMeshEntity::compute_corner_normals(), IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), IdealWeightMeanRatio::compute_element_analytical_gradient(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightMeanRatio::compute_element_analytical_hessian(), TargetCalculator::compute_Q_3D(), MsqMeshEntity::compute_signed_area(), TargetCalculator::compute_V_3D(), Vector3D::distance_between(), RI_DFT::evaluate_element(), IdealWeightInverseMeanRatio::evaluate_element(), IdealWeightMeanRatio::evaluate_element(), EdgeLengthQualityMetric::evaluate_vertex(), EdgeLengthRangeQualityMetric::evaluate_vertex(), Vector3D::interior_angle(), SphericalDomain::normal_at(), Vector3D::set_length(), SphericalDomain::snap_to(), and UntangleBetaQualityMetric::untangle_function_2d().
   {
     return msq_stdc::sqrt(mCoords[0]*mCoords[0] +
                           mCoords[1]*mCoords[1] +
                           mCoords[2]*mCoords[2]);
   }
double length () const inline
double length_squared () const inline
Definition at line 388 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
Referenced by AspectRatioGammaQualityMetric::evaluate_element(), and PatchData::get_max_vertex_movement_squared().
   {
     return (mCoords[0]*mCoords[0] +
             mCoords[1]*mCoords[1] +
             mCoords[2]*mCoords[2]);
   }
double length_squared () const inline
void normalize () inline
Definition at line 426 of file includeLinks/Vector3D.hpp.
References Vector3D::set_length().
Referenced by SphericalDomain::closest_point(), MsqMeshEntity::compute_corner_normals(), RI_DFT::evaluate_element(), PatchData::get_domain_normal_at_vertex(), and PlanarDomain::set_plane().
   { set_length(1.0); }
void normalize () inline
Vector3D & operator*= (const double scalar) inline
Definition at line 254 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     mCoords[0] *= scalar;
     mCoords[1] *= scalar;
     mCoords[2] *= scalar;
     return *this;
   }
Vector3D& operator*= (const double scalar)
Vector3D & operator*= (const Vector3D & rhs) inline
Definition at line 269 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     double new_coords[3] =
       {mCoords[1]*rhs.mCoords[2] - mCoords[2]*rhs.mCoords[1],
        mCoords[2]*rhs.mCoords[0] - mCoords[0]*rhs.mCoords[2],
        mCoords[0]*rhs.mCoords[1] - mCoords[1]*rhs.mCoords[0]
       };
     msq_stdc::memcpy(mCoords, new_coords, 3*sizeof(double));
     return *this;
   }
Vector3D& operator*= (const Vector3D & rhs)
Vector3D & operator+= (const Vector3D & rhs) inline
Definition at line 279 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     mCoords[0] += rhs.mCoords[0];
     mCoords[1] += rhs.mCoords[1];
     mCoords[2] += rhs.mCoords[2];
     return *this;
   }
Vector3D& operator+= (const Vector3D & rhs)
Vector3D operator- (void) const inline
Definition at line 250 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords, and Vector3D::Vector3D().
   {
     return Vector3D(-mCoords[0], -mCoords[1], -mCoords[2]);
   }
Vector3D operator- () const
Vector3D& operator-= (const Vector3D & rhs)
Vector3D & operator-= (const Vector3D & rhs) inline
Definition at line 286 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     mCoords[0] -= rhs.mCoords[0];
     mCoords[1] -= rhs.mCoords[1];
     mCoords[2] -= rhs.mCoords[2];
     return *this;
   }
Vector3D & operator/= (const double scalar) inline
divides each Vector3D entry by the given scalar.
Definition at line 262 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     mCoords[0] /= scalar;
     mCoords[1] /= scalar;
     mCoords[2] /= scalar;
     return *this;
   }
Vector3D& operator/= (const double scalar)
Vector3D& operator= (const Vector3D & to_copy)
Vector3D & operator= (const Vector3D & to_copy) inline
Definition at line 232 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
Referenced by MsqVertex::operator=().
   {
     mCoords[0] = to_copy.mCoords[0];
     mCoords[1] = to_copy.mCoords[1];
     mCoords[2] = to_copy.mCoords[2];
 //    memcpy(mCoords, to_copy.mCoords, 3*sizeof(double));
     return *this;
   }
Vector3D & operator= (const double & to_copy) inline
Definition at line 241 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     mCoords[0] = to_copy;
     mCoords[1] = to_copy;
     mCoords[2] = to_copy;
     return *this;
   }
Vector3D& operator= (const double & to_copy)
const double& operator[] (size_t index) const
const double & operator[] (size_t index) const inline
Definition at line 205 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     return mCoords[index];
   }
double& operator[] (size_t index)
double & operator[] (size_t index) inline
Definition at line 229 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   { return mCoords[index]; }
void set (const double x, const double y, const double z)
void set (const double x, const double y, const double z) inline
Definition at line 217 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords, Vector3D::x(), Vector3D::y(), and Vector3D::z().
Referenced by SphericalDomain::closest_point(), MsqMeshEntity::compute_weighted_jacobian(), SphericalDomain::normal_at(), ConjugateGradient::optimize_vertex_positions(), SphericalDomain::snap_to(), MesqPane::vertices_get_coordinates(), and MeshTSTTImpl::vertices_get_coordinates().
   {
     mCoords[0] = x;
     mCoords[1] = y;
     mCoords[2] = z;
   }
void set (const double xyz[3]) inline
Definition at line 225 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   { msq_stdc::memcpy(mCoords, xyz, 3*sizeof(double)); }
void set (const double xyz[3])
void set (const Vector3D & to_copy)
void set (const Vector3D & to_copy) inline
Definition at line 227 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   { msq_stdc::memcpy(mCoords, to_copy.mCoords, 3*sizeof(double)); }
void set_length (const double new_length) inline
Definition at line 421 of file includeLinks/Vector3D.hpp.
References Vector3D::length().
Referenced by Vector3D::normalize().
   {
     double factor = new_length / length();
     *this *= factor;
   }
void set_length (const double new_length) inline
const double* to_array () const inline
Definition at line 163 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
Referenced by MeshTSTTImpl::vertex_set_coordinates(), MeshImpl::vtk_read_polydata(), MeshImpl::vtk_read_structured_grid(), and MeshImpl::vtk_read_unstructured_grid().
       { return mCoords; }
const double* to_array () const inline
Definition at line 163 of file src/Misc/Vector3D.hpp.
References Vector3D::mCoords.
       { return mCoords; }
int within_tolerance_box (const Vector3D & compare_to, double tolerance) const inline
Definition at line 379 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     return ((msq_stdc::fabs(this->mCoords[0] - compare_to.mCoords[0]) < tolerance) &&
             (msq_stdc::fabs(this->mCoords[1] - compare_to.mCoords[1]) < tolerance) &&
             (msq_stdc::fabs(this->mCoords[2] - compare_to.mCoords[2]) < tolerance));
   }
int within_tolerance_box (const Vector3D & compare_to, double tolerance) const
double x () const
double x () const inline
Definition at line 191 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
Referenced by SphericalDomain::closest_point(), SphericalDomain::normal_at(), Mesquite::operator*(), Mesquite::operator+(), Mesquite::operator-(), Mesquite::operator/(), Vector3D::set(), SphericalDomain::snap_to(), Vector3D::Vector3D(), MeshTSTTImpl::vertices_get_coordinates(), MeshImpl::write_exodus(), and Vector3D::x().
   { return mCoords[0]; }
void x (const double x) inline
Definition at line 211 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords, and Vector3D::x().
   { mCoords[0] = x; }
void x (const double x)
double y () const
double y () const inline
Definition at line 193 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
Referenced by Mesquite::operator*(), Mesquite::operator+(), Mesquite::operator-(), Mesquite::operator/(), Vector3D::set(), Vector3D::Vector3D(), MeshTSTTImpl::vertices_get_coordinates(), MeshImpl::write_exodus(), and Vector3D::y().
   { return mCoords[1]; }
void y (const double y) inline
Definition at line 213 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords, and Vector3D::y().
   { mCoords[1] = y; }
void y (const double y)
double z () const
double z () const inline
Definition at line 195 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
Referenced by Mesquite::operator*(), Mesquite::operator+(), Mesquite::operator-(), Mesquite::operator/(), Vector3D::set(), Vector3D::Vector3D(), MeshTSTTImpl::vertices_get_coordinates(), MeshImpl::write_exodus(), and Vector3D::z().
   { return mCoords[2]; }
void z (const double z)
void z (const double z) inline
Definition at line 215 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords, and Vector3D::z().
   { mCoords[2] = z; }
Friends And Related Function Documentation
void eqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 522 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] = A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] = A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] = A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void eqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 522 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] = A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] = A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] = A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
double inner (const Vector3D v1[], const Vector3D v2[], int n) friend
dot product for array
Dot product for arrays of Vector3Ds. see also operator% .
Definition at line 340 of file includeLinks/Vector3D.hpp.
   {
     int i;
     double dot=0;
     for (i=0; i<n; ++i)
       dot+= lhs[i].mCoords[0] * rhs[i].mCoords[0] +
             lhs[i].mCoords[1] * rhs[i].mCoords[1] +
             lhs[i].mCoords[2] * rhs[i].mCoords[2];
     return dot;
   }
double inner (const Vector3D v1[], const Vector3D v2[], int n) friend
dot product for array
Dot product for arrays of Vector3Ds. see also operator% .
Definition at line 340 of file includeLinks/Vector3D.hpp.
   {
     int i;
     double dot=0;
     for (i=0; i<n; ++i)
       dot+= lhs[i].mCoords[0] * rhs[i].mCoords[0] +
             lhs[i].mCoords[1] * rhs[i].mCoords[1] +
             lhs[i].mCoords[2] * rhs[i].mCoords[2];
     return dot;
   }
double length (Vector3D *const v, int n) friend
L2 norm for an array of Vector3Ds.
Definition at line 400 of file includeLinks/Vector3D.hpp.
   {
     double l=0;
     for (int j=0; j<n; ++j)
       l += v[j].mCoords[0]*v[j].mCoords[0] +
            v[j].mCoords[1]*v[j].mCoords[1] +
            v[j].mCoords[2]*v[j].mCoords[2];
     return msq_stdc::sqrt(l);
   }
double length (Vector3D *const v, int n) friend
L2 norm for an array of Vector3Ds.
Definition at line 400 of file includeLinks/Vector3D.hpp.
   {
     double l=0;
     for (int j=0; j<n; ++j)
       l += v[j].mCoords[0]*v[j].mCoords[0] +
            v[j].mCoords[1]*v[j].mCoords[1] +
            v[j].mCoords[2]*v[j].mCoords[2];
     return msq_stdc::sqrt(l);
   }
double Linf (Vector3D *const v, int n) friend
L inf norm for array of Vector3Ds.
Definition at line 409 of file includeLinks/Vector3D.hpp.
   {
     double max=0;
     //loop over the length of the array
     for(int i=0;i<n;++i){
       if ( max < msq_stdc::fabs(v[i][0]) )   max=msq_stdc::fabs(v[i][0]) ;
       if ( max < msq_stdc::fabs(v[i][1]) )   max=msq_stdc::fabs(v[i][1]) ;
       if ( max < msq_stdc::fabs(v[i][2]) )   max=msq_stdc::fabs(v[i][2]) ;
     }
     //return the value of the largest entry in the array
     return max;
   }
double Linf (Vector3D *const v, int n) friend
L inf norm for array of Vector3Ds.
Definition at line 409 of file includeLinks/Vector3D.hpp.
   {
     double max=0;
     //loop over the length of the array
     for(int i=0;i<n;++i){
       if ( max < msq_stdc::fabs(v[i][0]) )   max=msq_stdc::fabs(v[i][0]) ;
       if ( max < msq_stdc::fabs(v[i][1]) )   max=msq_stdc::fabs(v[i][1]) ;
       if ( max < msq_stdc::fabs(v[i][2]) )   max=msq_stdc::fabs(v[i][2]) ;
     }
     //return the value of the largest entry in the array
     return max;
   }
bool operator!= (const Vector3D & lhs, const Vector3D & rhs) friend
Definition at line 442 of file includeLinks/Vector3D.hpp.
     { return v1.mCoords[0] != v2.mCoords[0] ||
              v1.mCoords[1] != v2.mCoords[1] ||
              v1.mCoords[2] != v2.mCoords[2]; }
bool operator!= (const Vector3D & lhs, const Vector3D & rhs) friend
Definition at line 442 of file includeLinks/Vector3D.hpp.
     { return v1.mCoords[0] != v2.mCoords[0] ||
              v1.mCoords[1] != v2.mCoords[1] ||
              v1.mCoords[2] != v2.mCoords[2]; }
double operator% (const Vector3D & v1, const Vector3D & v2) friend
dot product
Definition at line 331 of file includeLinks/Vector3D.hpp.
   {
     return( lhs.mCoords[0] * rhs.mCoords[0] +
             lhs.mCoords[1] * rhs.mCoords[1] +
             lhs.mCoords[2] * rhs.mCoords[2] );
   }
double operator% (const Vector3D & v1, const Vector3D & v2) friend
dot product
Definition at line 331 of file includeLinks/Vector3D.hpp.
   {
     return( lhs.mCoords[0] * rhs.mCoords[0] +
             lhs.mCoords[1] * rhs.mCoords[1] +
             lhs.mCoords[2] * rhs.mCoords[2] );
   }
double operator% (const double scalar, const Vector3D & v2) friend
scalar * sum_i v2[i]
Definition at line 352 of file includeLinks/Vector3D.hpp.
   {
     return( scalar * (rhs.mCoords[0] + rhs.mCoords[1] + rhs.mCoords[2]) );
   }
double operator% (const double scalar, const Vector3D & v2) friend
scalar * sum_i v2[i]
Definition at line 352 of file includeLinks/Vector3D.hpp.
   {
     return( scalar * (rhs.mCoords[0] + rhs.mCoords[1] + rhs.mCoords[2]) );
   }
double operator% (const Vector3D & v1, const double scalar) friend
scalar * sum_i v1[i]
Definition at line 357 of file includeLinks/Vector3D.hpp.
   {
     return( scalar * (lhs.mCoords[0] + lhs.mCoords[1] + lhs.mCoords[2]) );
   }
double operator% (const Vector3D & v1, const double scalar) friend
scalar * sum_i v1[i]
Definition at line 357 of file includeLinks/Vector3D.hpp.
   {
     return( scalar * (lhs.mCoords[0] + lhs.mCoords[1] + lhs.mCoords[2]) );
   }
const Vector3D operator* (const Vector3D & lhs, const double scalar) friend
lhs * scalar
Definition at line 309 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(lhs.x() * scalar,
                     lhs.y() * scalar,
                     lhs.z() * scalar);
   }
const Vector3D operator* (const Vector3D & lhs, const double scalar) friend
lhs * scalar
Definition at line 309 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(lhs.x() * scalar,
                     lhs.y() * scalar,
                     lhs.z() * scalar);
   }
const Vector3D operator* (const double scalar, const Vector3D & rhs) friend
scalar * rhs
Definition at line 316 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(rhs.x() * scalar,
                     rhs.y() * scalar,
                     rhs.z() * scalar);
   }
const Vector3D operator* (const double scalar, const Vector3D & rhs) friend
scalar * rhs
Definition at line 316 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(rhs.x() * scalar,
                     rhs.y() * scalar,
                     rhs.z() * scalar);
   }
const Vector3D operator* (const Vector3D & v1, const Vector3D & v2) friend
cross product
Definition at line 362 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(lhs.mCoords[1]*rhs.mCoords[2]-lhs.mCoords[2]*rhs.mCoords[1],
                     lhs.mCoords[2]*rhs.mCoords[0]-lhs.mCoords[0]*rhs.mCoords[2],
                     lhs.mCoords[0]*rhs.mCoords[1]-lhs.mCoords[1]*rhs.mCoords[0]);
   }
const Vector3D operator* (const Vector3D & v1, const Vector3D & v2) friend
cross product
Definition at line 362 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(lhs.mCoords[1]*rhs.mCoords[2]-lhs.mCoords[2]*rhs.mCoords[1],
                     lhs.mCoords[2]*rhs.mCoords[0]-lhs.mCoords[0]*rhs.mCoords[2],
                     lhs.mCoords[0]*rhs.mCoords[1]-lhs.mCoords[1]*rhs.mCoords[0]);
   }
const Vector3D operator+ (const Vector3D & lhs, const Vector3D & rhs) friend
Definition at line 295 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(lhs.x() + rhs.x(),
                     lhs.y() + rhs.y(),
                     lhs.z() + rhs.z());
   }
const Vector3D operator+ (const Vector3D & lhs, const Vector3D & rhs) friend
Definition at line 295 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(lhs.x() + rhs.x(),
                     lhs.y() + rhs.y(),
                     lhs.z() + rhs.z());
   }
const Vector3D operator- (const Vector3D & lhs, const Vector3D & rhs) friend
Definition at line 302 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(lhs.x() - rhs.x(),
                     lhs.y() - rhs.y(),
                     lhs.z() - rhs.z());
   }
const Vector3D operator- (const Vector3D & lhs, const Vector3D & rhs) friend
Definition at line 302 of file includeLinks/Vector3D.hpp.
   {
     return Vector3D(lhs.x() - rhs.x(),
                     lhs.y() - rhs.y(),
                     lhs.z() - rhs.z());
   }
const Vector3D operator/ (const Vector3D & lhs, const double scalar) friend
Definition at line 323 of file includeLinks/Vector3D.hpp.
   {
     assert (scalar != 0);
     return Vector3D(lhs.x() / scalar,
                     lhs.y() / scalar,
                     lhs.z() / scalar);
   }
const Vector3D operator/ (const Vector3D & lhs, const double scalar) friend
Definition at line 323 of file includeLinks/Vector3D.hpp.
   {
     assert (scalar != 0);
     return Vector3D(lhs.x() / scalar,
                     lhs.y() / scalar,
                     lhs.z() / scalar);
   }
bool operator== (const Vector3D & lhs, const Vector3D & rhs) friend
Definition at line 437 of file includeLinks/Vector3D.hpp.
     { return v1.mCoords[0] == v2.mCoords[0] &&
              v1.mCoords[1] == v2.mCoords[1] &&
              v1.mCoords[2] == v2.mCoords[2]; }
bool operator== (const Vector3D & lhs, const Vector3D & rhs) friend
Definition at line 437 of file includeLinks/Vector3D.hpp.
     { return v1.mCoords[0] == v2.mCoords[0] &&
              v1.mCoords[1] == v2.mCoords[1] &&
              v1.mCoords[2] == v2.mCoords[2]; }
void plusEqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 529 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] += A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] += A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] += A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void plusEqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 529 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] += A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] += A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] += A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void plusEqTransAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 536 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] += A.v_[0]*x.mCoords[0] + A.v_[3]*x.mCoords[1] + A.v_[6]*x.mCoords[2];
      v.mCoords[1] += A.v_[1]*x.mCoords[0] + A.v_[4]*x.mCoords[1] + A.v_[7]*x.mCoords[2];
      v.mCoords[2] += A.v_[2]*x.mCoords[0] + A.v_[5]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void plusEqTransAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) friend
Definition at line 536 of file includeLinks/Matrix3D.hpp.
   {
      v.mCoords[0] += A.v_[0]*x.mCoords[0] + A.v_[3]*x.mCoords[1] + A.v_[6]*x.mCoords[2];
      v.mCoords[1] += A.v_[1]*x.mCoords[0] + A.v_[4]*x.mCoords[1] + A.v_[7]*x.mCoords[2];
      v.mCoords[2] += A.v_[2]*x.mCoords[0] + A.v_[5]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
Member Data Documentation
double mCoords protected
Definition at line 167 of file includeLinks/Vector3D.hpp.
Referenced by Mesquite::eqAx(), Vector3D::get_coordinates(), Vector3D::length(), Vector3D::length_squared(), Mesquite::operator!=(), Mesquite::operator%(), Mesquite::operator*(), Vector3D::operator*=(), Vector3D::operator+=(), Vector3D::operator-(), Vector3D::operator-=(), Vector3D::operator/=(), Vector3D::operator=(), Mesquite::operator==(), Vector3D::operator[](), Mesquite::plusEqAx(), Mesquite::plusEqTransAx(), Vector3D::set(), Vector3D::to_array(), Vector3D::Vector3D(), Vector3D::within_tolerance_box(), Vector3D::x(), Vector3D::y(), and Vector3D::z().
The documentation for this class was generated from the following files:
includeLinks/Vector3D.hpp
Misc/Vector3D.cpp