Rocstar: rflu_modrindstates Module Reference
rflu_modrindstates Module Reference
Public Member Functions
subroutine, public rflu_setrindstatefarfieldperf (global, cpGas, mmGas, nx, ny, nz, machInf, pInf, tInf, alphaInf, betaInf, corrFlag, liftCoef, xc, yc, zc, rl, rul, rvl, rwl, rel, rr, rur, rvr, rwr, rer, pr)
subroutine, public rflu_setrindstateinjectperf (cpGas, mmGas, nx, ny, nz, mInj, tInj, pl, fs, rl, ul, vl, wl, Hl)
subroutine, public rflu_setrindstateslipwallperf (cpGas, mmGas, nx, ny, nz, rl, rul, rvl, rwl, fs, pl)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModRindStates.F90,v $ $Revision: 1.6 $'
Detailed Description
Definition at line 39 of file RFLU_ModRindStates.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_setrindstatefarfieldperf (type(t_global), pointer global, real(rfreal), intent(in) cpGas, real(rfreal), intent(in) mmGas, real(rfreal), intent(in) nx, real(rfreal), intent(in) ny, real(rfreal), intent(in) nz, real(rfreal), intent(in) machInf, real(rfreal), intent(in) pInf, real(rfreal), intent(in) tInf, real(rfreal), intent(in) alphaInf, real(rfreal), intent(in) betaInf, logical, intent(in) corrFlag, real(rfreal), intent(in) liftCoef, real(rfreal), intent(in) xc, real(rfreal), intent(in) yc, real(rfreal), intent(in) zc, real(rfreal), intent(in) rl, real(rfreal), intent(in) rul, real(rfreal), intent(in) rvl, real(rfreal), intent(in) rwl, real(rfreal), intent(in) rel, real(rfreal), intent(out) rr, real(rfreal), intent(out) rur, real(rfreal), intent(out) rvr, real(rfreal), intent(out) rwr, real(rfreal), intent(out) rer, real(rfreal), intent(out) pr)
Definition at line 130 of file RFLU_ModRindStates.F90.
References CImg< T >::atan2(), dist(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), mixtperf_c_dgp(), mixtperf_c_grt(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_eo_dgpvm(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_r_m(), pi, and sqrt().
Referenced by rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), and rflu_modnscbc::rflu_nscbc_initff().
subroutine, public rflu_setrindstateinjectperf (real(rfreal), intent(in) cpGas, real(rfreal), intent(in) mmGas, real(rfreal), intent(in) nx, real(rfreal), intent(in) ny, real(rfreal), intent(in) nz, real(rfreal), intent(in) mInj, real(rfreal), intent(in) tInj, real(rfreal), intent(in) pl, real(rfreal), intent(in) fs, real(rfreal), intent(out) rl, real(rfreal), intent(out) ul, real(rfreal), intent(out) vl, real(rfreal), intent(out) wl, real(rfreal), intent(out) Hl)
Definition at line 341 of file RFLU_ModRindStates.F90.
References mixtperf_d_prt(), mixtperf_g_cpr(), mixtperf_ho_cptuvw(), and mixtperf_r_m().
Referenced by rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_putboundaryvalues(), rflu_putboundaryvaluesalpha(), rflu_timestepinviscid(), and rflu_timestepviscous().
subroutine, public rflu_setrindstateslipwallperf (real(rfreal), intent(in) cpGas, real(rfreal), intent(in) mmGas, real(rfreal), intent(in) nx, real(rfreal), intent(in) ny, real(rfreal), intent(in) nz, real(rfreal), intent(in) rl, real(rfreal), intent(in) rul, real(rfreal), intent(in) rvl, real(rfreal), intent(in) rwl, real(rfreal), intent(in) fs, real(rfreal), intent(inout) pl)
Definition at line 417 of file RFLU_ModRindStates.F90.
References mixtperf_c_dgp(), mixtperf_g_cpr(), mixtperf_r_m(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), and rflu_putboundaryvalues().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModRindStates.F90,v $ $Revision: 1.6 $' private
Definition at line 73 of file RFLU_ModRindStates.F90.
The documentation for this module was generated from the following file:
RFLU_ModRindStates.F90