Rocstar: turb_rflu_modrocstaradmin Module Reference
turb_rflu_modrocstaradmin Module Reference
Public Member Functions
subroutine, public turb_rflu_genxcreateattr (pRegion)
subroutine, public turb_rflu_genxregisterdata (pRegion)
subroutine, public turb_rflu_genxgetdata (pRegion)
subroutine, public turb_rflu_genxcreateattr (pRegion)
subroutine, public turb_rflu_genxregisterdata (pRegion)
subroutine, public turb_rflu_genxgetdata (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: TURB_RFLU_ModRocstarAdmin.F90,v $ $Revision: 1.7 $'
Detailed Description
Definition at line 39 of file TURB_RFLU_ModGenxAdmin.F90.
Member Function/Subroutine Documentation
subroutine, public turb_rflu_genxcreateattr (type(t_region), pointer pRegion)
Definition at line 101 of file TURB_RFLU_ModGenxAdmin.F90.
Referenced by rflu_modrocstaradmin::rflu_genx_createattrturb().
subroutine, public turb_rflu_genxcreateattr (type(t_region), pointer pRegion)
Definition at line 101 of file TURB_RFLU_ModRocstarAdmin.F90.
subroutine, public turb_rflu_genxgetdata (type(t_region), pointer pRegion)
Definition at line 306 of file TURB_RFLU_ModRocstarAdmin.F90.
subroutine, public turb_rflu_genxgetdata (type(t_region), pointer pRegion)
Definition at line 306 of file TURB_RFLU_ModGenxAdmin.F90.
Referenced by rflu_modreadwriteflow::rflu_readflowwrapper().
subroutine, public turb_rflu_genxregisterdata (type(t_region), pointer pRegion)
Definition at line 155 of file TURB_RFLU_ModGenxAdmin.F90.
References moderror::errorstop(), and rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_modrocstaradmin::rflu_genx_registerdataturb().
subroutine, public turb_rflu_genxregisterdata (type(t_region), pointer pRegion)
Definition at line 155 of file TURB_RFLU_ModRocstarAdmin.F90.
References moderror::errorstop(), and rflu_modrocstarutils::rflu_genx_buildpaneid().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: TURB_RFLU_ModRocstarAdmin.F90,v $ $Revision: 1.7 $' private
Definition at line 70 of file TURB_RFLU_ModGenxAdmin.F90.
The documentation for this module was generated from the following files:
TURB_RFLU_ModGenxAdmin.F90
TURB_RFLU_ModRocstarAdmin.F90