Rocstar: Element_node_enumerator Class Reference
Element_node_enumerator Class Reference
An adaptor for enumerating node IDs of an element.
#include <Element_accessors.h>
Public Member Functions
Element_node_enumerator ()
Element_node_enumerator (const Pane *pane, int i, const Connectivity *conn=NULL)
Constructor for an element in a structured or an unstructured mesh.
Element_node_enumerator (const Pane *pane, const std::pair< int, int > &id)
A constructor for an element in a structured mesh.
void next ()
Go to the next element within the connectivity tables of a pane.
int type () const
Obtain the type of the element.
int is_quadratic () const
Check whether the element is quadratic.
int size_of_nodes () const
Number of nodes per element.
int size_of_corners () const
Number of corners per element.
void get_nodes (std::vector< int > &nodes)
Get a vector of all of the nodes in the element.
int size_of_edges () const
Number of edges per element.
int size_of_faces () const
Number of faces per element.
int dimension () const
Get the dimension of the base pane.
int id () const
Get the local id of the element within the pane.
int vertex (int lvid, bool level=false) const
Get the vertex index of an vertex within the element.
int operator[] (int i) const
Obtain the pane-scope node ID from its element-scope index.
const Pane * pane () const
Protected Attributes
const Pane * _pane
const Connectivity * _conn
union {
const int * _start
int _base
};
int _res
Detailed Description
An adaptor for enumerating node IDs of an element.
Definition at line 43 of file Element_accessors.h.
Constructor & Destructor Documentation
Element_node_enumerator () inline
Definition at line 45 of file Element_accessors.h.
 : _pane(NULL), _conn(NULL), _start(NULL), _res(0){}
COM_BEGIN_NAME_SPACE Element_node_enumerator (const Pane * pane, int i, const Connectivity * conn = NULL)
Constructor for an element in a structured or an unstructured mesh.
If conn==NULL, then i is an element index local to the pane. If conn!=NULL, then i is an element index local to the connectivity.
Definition at line 32 of file Element_accessors.C.
References _base, _conn, _pane, _res, _start, COM_assertion, Pane::dimension(), i, Connectivity::index_offset(), Pane::is_unstructured(), max(), Connectivity::pointer(), Pane::size_i(), Pane::size_of_elements(), Connectivity::size_of_elements(), and Connectivity::size_of_nodes_pe().
   : _pane(pane), _conn( _pane->is_structured()?NULL:
                         (conn==NULL?pane->connectivity(i):conn))
 {
   if ( _pane->is_unstructured()) {
     if ( conn == NULL && _conn != NULL) i -= _conn->index_offset()+1;
     else --i;
     if ( _conn) {
       COM_assertion( i>=0 && i<std::max(int(_conn->size_of_elements()),1));
       _start = _conn->pointer()+i*_conn->size_of_nodes_pe();
       _res = _conn->size_of_elements() - i;
     }
     else {
       _pane = NULL;
       _conn = NULL;
       _start = NULL;
       _res = -1;
     }
   }
   else if ( _pane->dimension()==2) {
     COM_assertion( i>=1 && i<=int(_pane->size_of_elements()));
     _res = (i-1) % (_pane->size_i()-1);
     _base = i + (i-1) / (_pane->size_i()-1);
   }
   else {
     COM_assertion(false); // Not yet supported.
   }
 }
Element_node_enumerator (const Pane * pane, const std::pair< int, int > & id)
A constructor for an element in a structured mesh.
Parameters
pane a pointer to the owner pane.
r the row id of the element (starting from 1).
c the column id of the element (starting from 1).
Definition at line 68 of file Element_accessors.C.
References _base, _pane, _res, COM_assertion, Pane::is_structured(), Pane::size_i(), and Pane::size_j().
   : _pane(pane), _conn(NULL) {
   COM_assertion( _pane != NULL && _pane->is_structured());
   COM_assertion( id.first>0 && id.first<=int(_pane->size_i()));
   COM_assertion( id.second>0 && id.second<=int(_pane->size_j()));
   _res = id.first-1;
   _base = (id.second-1)*_pane->size_i()+id.first;
 }
Member Function Documentation
int dimension () const inline
Get the dimension of the base pane.
Definition at line 105 of file Element_accessors.h.
References _pane, and Pane::dimension().
Referenced by Facet_node_enumerator::Facet_node_enumerator().
 { return _pane->dimension(); }
void get_nodes (std::vector< int > & nodes)
Get a vector of all of the nodes in the element.
Definition at line 146 of file Element_accessors.C.
References i, num_nodes, and size_of_nodes().
{
   int num_nodes = size_of_nodes();
   nodes.resize( num_nodes);
   for (int i=0; i<num_nodes; i++) nodes[i] = (*this)[i];
 }
int id () const inline
Get the local id of the element within the pane.
Definition at line 108 of file Element_accessors.h.
References _base, _conn, _pane, _start, Connectivity::index_offset(), Pane::is_structured(), Connectivity::pointer(), Pane::size_i(), and Connectivity::size_of_nodes_pe().
Referenced by RFC_Pane_base::comp_nat_coors(), Transfer_base::compute_load_vector_wra(), Simple_manifold_2::determine_incident_halfedges(), Simple_manifold_2::determine_opposite_halfedges(), RFC_Pane_base::get_host_element_of_subface(), RFC_Pane_base::get_host_element_of_subnode(), RFC_Pane_base::get_nat_coor_in_element(), Transfer_base::init_load_vector(), Transfer_base::integrate_subface(), Transfer_base::make_field(), FaceOffset_3::obtain_face_offset(), Element_vectors_k_const< Value >::set(), and Transfer_base::transfer_2f().
                  {
     if ( _pane->is_structured()) {
       return _base - (_base-1) / _pane->size_i();
     }
     else {
       return _conn->index_offset() + 1 +
         (_start - _conn->pointer()) / _conn->size_of_nodes_pe();
     }
   }
int is_quadratic () const inline
Check whether the element is quadratic.
Definition at line 68 of file Element_accessors.h.
References _conn, and Connectivity::is_quadratic().
Referenced by Facet_node_enumerator::size_of_nodes().
{
     if ( _conn) return _conn->is_quadratic();
     else return false;
   }
void next ()
Go to the next element within the connectivity tables of a pane.
Definition at line 79 of file Element_accessors.C.
References _base, _conn, _pane, _res, _start, COM_assertion, Pane::connectivity(), Pane::dimension(), Connectivity::index_offset(), Connectivity::pointer(), Pane::size_i(), Connectivity::size_of_elements(), and Connectivity::size_of_nodes_pe().
Referenced by Propagation_3::bound_facial_speed(), rflu_modrepair3d::cavedg(), RFC_Pane_base::comp_nat_coors(), FaceOffset_3::compute_anisotropic_vertex_centers(), Rocsurf::compute_bounded_volumes(), Rocsurf::compute_element_areas(), Rocsurf::compute_element_normals(), Window_manifold_2::compute_mcn(), FaceOffset_3::compute_quadrics(), Window_manifold_2::compute_shortest_edgelen_elements(), Window_manifold_2::compute_shortest_edgelen_nodes(), Rocsurf::compute_signed_volumes(), Rocsurf::compute_swept_volumes(), Propagation_3::convert_constraints(), Pane_boundary::determine_border_nodes_3(), Propagation_3::determine_constraint_boundary(), Simple_manifold_2::determine_incident_halfedges(), Simple_manifold_2::determine_opposite_halfedges(), FaceOffset_3::distribute_volume_e2n(), Window_manifold_2::elements_to_nodes(), Rocmop::evaluate_face_normals(), FaceOffset_3::filter_and_identify_ridge_edges(), Rocmop::get_redist_safe_factor(), Rocmop::identify_ridge_edges(), FaceOffset_3::insert_boundary_edges(), Rocsurf::integrate(), data_declarations::length(), FaceOffset_3::nulaplacian_smooth(), rflu_modrepair3d::octfil(), rflu_modrepair3d::octfnd(), rflu_modoctree::octree(), rflu_modrepair3d::octrmv(), Rocmop::redistribute_vertices_smooth(), and FaceOffset_3::rescale_displacements().
{
   if ( _conn) {
     if ( --_res==0) {
       _conn = _pane->connectivity( _conn->index_offset()+1+
                                    _conn->size_of_elements());
       if ( _conn) {
         _start = _conn->pointer();
         _res = _conn->size_of_elements();
       }
       else {
         _pane = NULL;
         _conn = NULL;
         _start = NULL;
         _res = -1;
       }
     }
     else
       _start += _conn->size_of_nodes_pe();
   }
   else if (_pane->dimension()==2) { // Structured mesh
     ++_base;
     if ( ++_res == int(_pane->size_i()-1)) { ++_base; _res=0; }
   }
   else {
     COM_assertion(false); // Not yet supported.
   }
 }
int operator[] (int i) const inline
Obtain the pane-scope node ID from its element-scope index.
Parameters
i the element-scope index of a node (starting from 0).
Definition at line 124 of file Element_accessors.h.
References _base, _conn, _pane, _start, i, and Pane::size_i().
{
     if ( _conn) // Unstructured mesh
       return _start[i];
     else { // Structured mesh; Only support 2-D mesh now.
       int t=_base;
       if ( i>1) t+=_pane->size_i();
       return ( i==1 || i==2)? t+1 : t;
     }
   }
const Pane* pane () const inline
Definition at line 135 of file Element_accessors.h.
References _pane.
Referenced by RFC_Pane_base::comp_nat_coors(), RFC_Pane_base::get_host_element_of_subface(), RFC_Pane_base::get_host_element_of_subnode(), and Transfer_base::integrate_subface().
 { return _pane; }
int size_of_corners () const inline
Number of corners per element.
Definition at line 81 of file Element_accessors.h.
References _conn, _pane, Pane::dimension(), and Connectivity::size_of_corners_pe().
{
     if ( _conn) return _conn->size_of_corners_pe();
     if ( _pane->dimension()==2) return 4;
     return 8;
   }
int size_of_edges () const inline
Number of edges per element.
Definition at line 91 of file Element_accessors.h.
References _conn, _pane, Pane::dimension(), and Connectivity::size_of_edges_pe().
Referenced by Propagation_3::bound_facial_speed(), FaceOffset_3::build_ridge_neighbor_list(), FaceOffset_3::compute_anisotropic_vertex_centers(), Rocsurf::compute_bounded_volumes(), Rocsurf::compute_element_areas(), Rocsurf::compute_element_normals(), Transfer_base::compute_load_vector_wra(), Window_manifold_2::compute_mcn(), FaceOffset_3::compute_quadrics(), Window_manifold_2::compute_shortest_edgelen_elements(), Window_manifold_2::compute_shortest_edgelen_nodes(), Rocsurf::compute_signed_volumes(), Rocsurf::compute_swept_volumes(), Propagation_3::convert_constraints(), Propagation_3::determine_constraint_boundary(), Simple_manifold_2::determine_incident_halfedges(), Simple_manifold_2::determine_opposite_halfedges(), FaceOffset_3::distribute_volume_e2n(), Window_manifold_2::elements_to_nodes(), Rocmop::evaluate_face_normals(), FaceOffset_3::filter_and_identify_ridge_edges(), RFC_Pane_base::get_nat_coor_in_element(), Facet_node_enumerator::get_nodes(), get_normal(), RFC_Pane_base::get_point_of_subnode(), Rocmop::get_redist_safe_factor(), FaceOffset_3::insert_boundary_edges(), Rocsurf::integrate(), Transfer_base::integrate_subface(), Transfer_base::interpolate_fe(), FaceOffset_3::nulaplacian_smooth(), FaceOffset_3::obtain_face_offset(), Facet_node_enumerator::operator[](), Rocmop::redistribute_vertices_ridge(), Rocmop::redistribute_vertices_smooth(), FaceOffset_3::rescale_displacements(), and FaceOffset_3::update_vertex_centers().
{
     if ( _conn) return _conn->size_of_edges_pe();
     if ( _pane->dimension()==2) return 4;
     return 12;
   }
int size_of_faces () const inline
Number of faces per element.
Definition at line 98 of file Element_accessors.h.
References _conn, _pane, Pane::dimension(), and Connectivity::size_of_faces_pe().
Referenced by Pane_boundary::determine_border_nodes_3().
{
     if ( _conn) return _conn->size_of_faces_pe();
     if ( _pane->dimension()==2) return 1;
     return 6;
   }
int size_of_nodes () const inline
Number of nodes per element.
Definition at line 74 of file Element_accessors.h.
References _conn, _pane, Pane::dimension(), and Connectivity::size_of_nodes_pe().
Referenced by Rocsurf::compute_element_areas(), Rocsurf::compute_element_normals(), Transfer_base::compute_load_vector_wra(), Window_manifold_2::compute_shortest_edgelen_nodes(), Propagation_3::convert_constraints(), Simple_manifold_2::determine_incident_halfedges(), Window_manifold_2::elements_to_nodes(), Rocmop::evaluate_face_normals(), Facet_node_enumerator::Facet_node_enumerator(), RFC_Pane_base::get_lvid(), get_nodes(), RFC_Pane_base::get_point_of_subnode(), Rocsurf::integrate(), Transfer_base::integrate_subface(), Transfer_base::interpolate_fe(), Element_node_vectors_k_const< Value >::set(), Facet_node_enumerator::size_of_nodes(), and Vertex_set::Vertex_set().
{
     if ( _conn) return _conn->size_of_nodes_pe();
     if ( _pane->dimension()==2) return 4;
     return 8;
   }
int type () const inline
Obtain the type of the element.
Definition at line 61 of file Element_accessors.h.
References _conn, _pane, Pane::dimension(), Connectivity::element_type(), Connectivity::ST2, and Connectivity::ST3.
                    {
     if ( _conn) return _conn->element_type();
     else if ( _pane->dimension()==2) return Connectivity::ST2;
     else return Connectivity::ST3;
   }
int vertex (int lvid, bool level = false) const
Get the vertex index of an vertex within the element.
Definition at line 108 of file Element_accessors.C.
References _base, _conn, _pane, _start, NTS::abs(), COM_assertion, i, Pane::is_structured(), Pane::size_i(), Pane::size_j(), and Connectivity::size_of_nodes_pe().
Referenced by RFC_Pane_base::get_lvid().
{
   if ( _pane->is_structured()) { // Structured mesh
     if ( lvid == _base) return 0;
     if ( lvid == _base+1) return 1;
     const int nr = _pane->size_i();
     if ( lvid == int(_base+nr)) return 3;
     if ( lvid == int(_base+nr+1)) return 2;
     // There is a branch cut in the pane. Resort to more expensive step.
     // Check which boundary lvid is on.
     if ( !level) {
       COM_assertion( nr>2 && _pane->size_j()>2);
       const int c1 = (_base-1)/nr, r1 = (_base-1)%nr;
       const int c2 = (lvid-1)/nr, r2 = (lvid-1)%nr;
       if ( std::abs( r1-r2)<=1) {
         const int nc = _pane->size_j();
         if ( c2 == 0) return vertex( (nc-1)*nr+r2+1, true);
         if ( c2 == nc-1) return vertex( r2+1, true);
       }
       else {
         COM_assertion( std::abs( c1-c2)<=1);
         if ( r2 == 0) return vertex( (c2+1)*nr, true);
         if ( r2 == nr-1) return vertex( c2*nr+1, true);
       }
     }
     COM_assertion( false); return -1;
   }
   else { // Unstructured
     const int *p=_start;
     for ( int i=0, size=_conn->size_of_nodes_pe(); i<size; ++i,++p) {
       if ( lvid == *p) return i;
     }
     return -1; // The node is not in the table
   }
 }
Member Data Documentation
union { ... }
int _base
Definition at line 142 of file Element_accessors.h.
Referenced by Element_node_enumerator(), id(), next(), Element_node_enumerator_str_2::next(), operator[](), Element_node_enumerator_str_2::operator[](), and vertex().
const Connectivity* _conn protected
Definition at line 139 of file Element_accessors.h.
Referenced by Element_node_enumerator(), id(), is_quadratic(), next(), Element_node_enumerator_uns::next(), operator[](), size_of_corners(), size_of_edges(), size_of_faces(), size_of_nodes(), Element_node_enumerator_uns::size_of_nodes(), type(), and vertex().
const Pane* _pane protected
Definition at line 138 of file Element_accessors.h.
Referenced by dimension(), Element_node_enumerator(), id(), next(), Element_node_enumerator_str_2::next(), Element_node_enumerator_uns::next(), operator[](), Element_node_enumerator_str_2::operator[](), pane(), size_of_corners(), size_of_edges(), size_of_faces(), size_of_nodes(), type(), and vertex().
int _res protected
Definition at line 144 of file Element_accessors.h.
Referenced by Element_node_enumerator(), next(), Element_node_enumerator_str_2::next(), and Element_node_enumerator_uns::next().
const int* _start
Definition at line 141 of file Element_accessors.h.
Referenced by Element_node_enumerator(), id(), next(), Element_node_enumerator_uns::next(), operator[](), Element_node_enumerator_uns::operator[](), and vertex().
The documentation for this class was generated from the following files:
Element_accessors.h
Element_accessors.C