Rocstar: rflu_modpetscnewtonkrylov Module Reference
rflu_modpetscnewtonkrylov Module Reference
Public Member Functions
subroutine, public rflu_petsc_createvectors (pRegion)
subroutine, public rflu_petsc_createjacobian (pRegion)
subroutine, public rflu_petsc_destroyvectors (pRegion)
subroutine, public rflu_petsc_destroyjacobian (pRegion)
subroutine, public rflu_petsc_formjacobian (snes, v, J, pJ, flag, pRegion, ierr)
subroutine, public rflu_petsc_formresidual (snes, x, f, pRegion, ierr)
subroutine, public rflu_petsc_formresidualfirstorder (snes, x, f, pRegion, ierr)
subroutine, public rflu_petsc_createcoloring (pRegion)
subroutine, public rflu_petsc_createapplicationordering (pRegion)
subroutine, public rflu_petsc_destroyapplicationordering (pRegion)
subroutine, public rflu_petsc_getdtscale (global, dtscale)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPETScNewtonKrylov.F90,v $ $Revision: 1.9 $'
Detailed Description
Definition at line 33 of file RFLU_ModPETScNewtonKrylov.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_petsc_createapplicationordering (type(t_region), pointer pRegion)
Definition at line 1251 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_petsc_createjacobian().
subroutine, public rflu_petsc_createcoloring (type(t_region), pointer pRegion)
Definition at line 878 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, j, moderror::registerfunction(), rflu_modcoloring::rflu_col_createcoloring(), rflu_modcoloring::rflu_col_destroycoloring(), rflu_modcoloring::rflu_col_readcoloring(), rflu_modresidual::rflu_getresidualsupport1(), rflu_modresidual::rflu_getresidualsupport2(), and rs().
Referenced by rflu_petsc_createjacobian().
subroutine, public rflu_petsc_createjacobian (type(t_region), pointer pRegion)
Definition at line 183 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_petsc_createapplicationordering(), and rflu_petsc_createcoloring().
Referenced by rflu_initflowsolver().
subroutine, public rflu_petsc_createvectors (type(t_region), pointer pRegion)
Definition at line 100 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and Matrix3D::zero().
Referenced by rflu_initflowsolver().
subroutine, public rflu_petsc_destroyapplicationordering (type(t_region), pointer pRegion)
Definition at line 1368 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_petsc_destroyjacobian().
subroutine, public rflu_petsc_destroyjacobian (type(t_region), pointer pRegion)
Definition at line 414 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_petsc_destroyapplicationordering().
Referenced by rflu_endflowsolver().
subroutine, public rflu_petsc_destroyvectors (type(t_region), pointer pRegion)
Definition at line 353 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_endflowsolver().
subroutine, public rflu_petsc_formjacobian (snes, v, J, pJ, flag, type(t_region), pointer pRegion, integer ierr)
Definition at line 497 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), j, moderror::registerfunction(), and v.
Referenced by rflu_modnewtonkrylov::rflu_nk_timestepping().
subroutine, public rflu_petsc_formresidual (snes, x, f, type(t_region), pointer pRegion, integer ierr)
Definition at line 613 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_checkpositivity(), rflu_modmpi::rflu_mpi_clearrequestwrapper(), rflu_modmpi::rflu_mpi_isendwrapper(), rflu_modmpi::rflu_mpi_recvwrapper(), rflu_modresidual::rflu_res_computeresidual(), rflu_setdependentvars(), and x.
Referenced by rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_petsc_formresidualfirstorder().
subroutine, public rflu_petsc_formresidualfirstorder (snes, x, f, type(t_region), pointer pRegion, integer ierr)
Definition at line 795 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_petsc_formresidual(), and x.
Referenced by rflu_modnewtonkrylov::rflu_nk_timestepping().
subroutine, public rflu_petsc_getdtscale (type(t_global), pointer global, real(rfreal) dtscale)
Definition at line 1432 of file RFLU_ModPETScNewtonKrylov.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_timestepinviscid().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPETScNewtonKrylov.F90,v $ $Revision: 1.9 $' private
Definition at line 69 of file RFLU_ModPETScNewtonKrylov.F90.
The documentation for this module was generated from the following file:
RFLU_ModPETScNewtonKrylov.F90