Rocstar: plag_modinjection Module Reference
plag_modinjection Module Reference
Public Member Functions
subroutine, public plag_ejectparticle (pRegion, pPlag, pTilePlag, iTile, icg, burnStat, nVert, normDirFlag, xyzVertex, fn, fc, cellHeight, plagVolRatio)
subroutine, public plag_invokeejecmodel1 (pRegion, pPlag, pTilePlag, iTile, icg, burnStat, nVert, normDirFlag, xyzVertex, volMeanPart, fn, fc, cellHeight)
subroutine, public plag_invokeconsrandejec (pRegion, pPlag, pTilePlag, iTile, icg, burnStat, nVert, normDirFlag, xyzVertex, volMeanPart, fn, fc, cellHeight)
Private Member Functions
subroutine plag_injcsetpoolpos (pRegion, nVert, normDirFlag, xyzVertex, faceCentroid, sNormal, cellHeight, posPlag)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModInjection.F90,v $ $Revision: 1.11 $'
Detailed Description
Definition at line 39 of file PLAG_ModInjection.F90.
Member Function/Subroutine Documentation
subroutine, public plag_ejectparticle (type(t_region), pointer pRegion, type(t_plag), pointer pPlag, type(t_tile_plag), pointer pTilePlag, integer, intent(in) iTile, integer, intent(in) icg, integer, intent(in) burnStat, integer, intent(in) nVert, integer, intent(in) normDirFlag, real(rfreal), dimension(zcoord,4), intent(in) xyzVertex, real(rfreal), dimension(zcoord), intent(in) fn, real(rfreal), dimension(zcoord), intent(in) fc, real(rfreal), intent(in) cellHeight, real(rfreal), intent(in) plagVolRatio)
Definition at line 109 of file PLAG_ModInjection.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericCell_2::nvert(), plag_injcsetpoolpos(), moderror::registerfunction(), and rflu_modincelltest::rflu_ict_testincell().
Referenced by plag_invokeconsrandejec(), and plag_invokeejecmodel1().
subroutine plag_injcsetpoolpos (type(t_region), pointer pRegion, integer, intent(in) nVert, integer, intent(in) normDirFlag, real(rfreal), dimension(zcoord,4), intent(in) xyzVertex, real(rfreal), dimension(zcoord), intent(in) faceCentroid, real(rfreal), dimension(zcoord), intent(in) sNormal, real(rfreal), intent(in) cellHeight, real(rfreal), dimension(zcoord), intent(out) posPlag) private
Definition at line 354 of file PLAG_ModInjection.F90.
References moderror::deregisterfunction(), dot_product(), Mesh::GenericCell_2::nvert(), modrandom::rand1uniform(), and moderror::registerfunction().
Referenced by plag_ejectparticle().
subroutine, public plag_invokeconsrandejec (type(t_region), pointer pRegion, type(t_plag), pointer pPlag, type(t_tile_plag), pointer pTilePlag, integer, intent(in) iTile, integer, intent(in) icg, integer, intent(in) burnStat, integer, intent(in) nVert, integer, intent(in) normDirFlag, real(rfreal), dimension(zcoord,4), intent(in) xyzVertex, real(rfreal), intent(in) volMeanPart, real(rfreal), dimension(zcoord), intent(in) fn, real(rfreal), dimension(zcoord), intent(in) fc, real(rfreal), intent(in) cellHeight)
Definition at line 695 of file PLAG_ModInjection.F90.
References moderror::deregisterfunction(), Mesh::GenericCell_2::nvert(), pi, plag_ejectparticle(), plag_injcmakeparticle(), Aff_transformation_repS2< FT >::print(), modrandom::rand1uniform(), moderror::registerfunction(), sqrt(), and CImg< T >::sum().
Referenced by plag_rflu_injectiondriver().
subroutine, public plag_invokeejecmodel1 (type(t_region), pointer pRegion, type(t_plag), pointer pPlag, type(t_tile_plag), pointer pTilePlag, integer, intent(in) iTile, integer, intent(in) icg, integer, intent(in) burnStat, integer, intent(in) nVert, integer, intent(in) normDirFlag, real(rfreal), dimension(zcoord,4), intent(in) xyzVertex, real(rfreal), intent(in) volMeanPart, real(rfreal), dimension(zcoord), intent(in) fn, real(rfreal), dimension(zcoord), intent(in) fc, real(rfreal), intent(in) cellHeight)
Definition at line 535 of file PLAG_ModInjection.F90.
References moderror::deregisterfunction(), Mesh::GenericCell_2::nvert(), plag_ejectparticle(), plag_injcmakeparticle(), plag_injcsetinjection(), moderror::registerfunction(), and CImg< T >::sum().
Referenced by plag_rflu_injectiondriver().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModInjection.F90,v $ $Revision: 1.11 $' private
Definition at line 69 of file PLAG_ModInjection.F90.
The documentation for this module was generated from the following file:
PLAG_ModInjection.F90