Rocstar: Aff_transformationS2< FT > Class Template Reference
Aff_transformationS2< FT > Class Template Reference
#include <Aff_transformationS2.h>
Public Member Functions
Aff_transformationS2 ()
Aff_transformationS2 (const Identity_transformation &)
Aff_transformationS2 (const Aff_transformationS2< FT > &t)
Aff_transformationS2 (const Translation, const VectorS2< FT > &v)
Aff_transformationS2 (const Rotation, const DirectionS2< FT > &d, const FT &num, const FT &den=FT(1))
Aff_transformationS2 (const Rotation, const FT &sine_rho, const FT &cosine_rho, const FT &hw=FT(1))
Aff_transformationS2 (const Scaling, const FT &s, const FT &w=FT(1))
Aff_transformationS2 (const FT &m11, const FT &m12, const FT &m13, const FT &m21, const FT &m22, const FT &m23, const FT &w=FT(1))
Aff_transformationS2 (const FT &m11, const FT &m12, const FT &m21, const FT &m22, const FT &w=FT(1))
~Aff_transformationS2 ()
PointS2< FT > transform (const PointS2< FT > &p) const
PointS2< FT > operator() (const PointS2< FT > &p) const
VectorS2< FT > transform (const VectorS2< FT > &p) const
VectorS2< FT > operator() (const VectorS2< FT > &p) const
DirectionS2< FT > transform (const DirectionS2< FT > &d) const
DirectionS2< FT > operator() (const DirectionS2< FT > &d) const
LineS2< FT > transform (const LineS2< FT > &l) const
LineS2< FT > operator() (const LineS2< FT > &l) const
Aff_transformationS2< FT > inverse () const
bool is_even () const
bool is_odd () const
FT cartesian (int i, int j) const
FT homogeneous (int i, int j) const
FT m (int i, int j) const
FT hm (int i, int j) const
Aff_transformationS2< FT > operator* (const Aff_transformationS2< FT > &t) const
std::ostream & print (std::ostream &os) const
Private Member Functions
Aff_transformation_rep_baseS2
< FT > * ptr () const
Detailed Description
template<class FT>
class Aff_transformationS2< FT >
Definition at line 690 of file Aff_transformationS2.h.
Constructor & Destructor Documentation
Aff_transformationS2 ()
Definition at line 807 of file Aff_transformationS2.h.
 { PTR = new Aff_transformation_repS2<FT>(FT(1), FT(0), FT(0), FT(1)); }
Aff_transformationS2 (const Identity_transformation &)
Definition at line 811 of file Aff_transformationS2.h.
 { PTR = new Aff_transformation_repS2<FT>(FT(1), FT(0), FT(0), FT(1)); }
Aff_transformationS2 (const Aff_transformationS2< FT > & t)
Definition at line 815 of file Aff_transformationS2.h.
   : Handle(t)
 {}
Aff_transformationS2 (const Translation , const VectorS2< FT > & v)
Definition at line 834 of file Aff_transformationS2.h.
References v.
 { PTR = new Translation_repS2<FT>(v); }
Aff_transformationS2 (const Rotation , const DirectionS2< FT > & d, const FT & num, const FT & den = FT(1))
Definition at line 839 of file Aff_transformationS2.h.
 { PTR = new Rotation_repS2<FT>(d, num, den); }
Aff_transformationS2 (const Rotation , const FT & sine_rho, const FT & cosine_rho, const FT & hw = FT(1))
Definition at line 847 of file Aff_transformationS2.h.
 {
   if (w != FT(1))
     PTR = new Rotation_repS2<FT>(sine/w, cosine/w);
   else
     PTR = new Rotation_repS2<FT>(sine, cosine);
 }
Aff_transformationS2 (const Scaling , const FT & s, const FT & w = FT(1))
Definition at line 859 of file Aff_transformationS2.h.
References s.
 {
   if (w != FT(1))
     PTR = new Scaling_repS2<FT>(s/w);
   else
     PTR = new Scaling_repS2<FT>(s);
 }
Aff_transformationS2 (const FT & m11, const FT & m12, const FT & m13, const FT & m21, const FT & m22, const FT & m23, const FT & w = FT(1))
Definition at line 872 of file Aff_transformationS2.h.
 {
   if (w != FT(1))
     PTR = new Aff_transformation_repS2<FT>(m11/w, m12/w, m13/w,
                                            m21/w, m22/w, m23/w);
   else
     PTR = new Aff_transformation_repS2<FT>(m11, m12, m13,
                                            m21, m22, m23);
 }
Aff_transformationS2 (const FT & m11, const FT & m12, const FT & m21, const FT & m22, const FT & w = FT(1))
Definition at line 821 of file Aff_transformationS2.h.
 {
   if (w != FT(1))
     PTR = new Aff_transformation_repS2<FT>(m11/w, m12/w, m21/w, m22/w);
   else
     PTR = new Aff_transformation_repS2<FT>(m11, m12, m21, m22);
 }
~Aff_transformationS2 ()
Definition at line 886 of file Aff_transformationS2.h.
 {}
Member Function Documentation
FT cartesian (int i, int j) const inline
Definition at line 755 of file Aff_transformationS2.h.
References Aff_transformationS2< FT >::ptr().
Referenced by Aff_transformationS2< FT >::hm(), Aff_transformationS2< FT >::homogeneous(), and Aff_transformationS2< FT >::m().
 { return ptr()->cartesian(i,j); }
FT hm (int i, int j) const inline
Definition at line 758 of file Aff_transformationS2.h.
References Aff_transformationS2< FT >::cartesian().
 { return cartesian(i,j); }
FT homogeneous (int i, int j) const inline
Definition at line 756 of file Aff_transformationS2.h.
References Aff_transformationS2< FT >::cartesian().
 { return cartesian(i,j); }
Aff_transformationS2< FT > inverse () const
Definition at line 942 of file Aff_transformationS2.h.
 {
   return ptr()->inverse();
 }
bool is_even () const inline
Definition at line 752 of file Aff_transformationS2.h.
References Aff_transformationS2< FT >::ptr().
 { return ptr()->is_even(); }
bool is_odd () const
Definition at line 950 of file Aff_transformationS2.h.
 {
   return ! (ptr()->is_even());
 }
FT m (int i, int j) const inline
Definition at line 757 of file Aff_transformationS2.h.
References Aff_transformationS2< FT >::cartesian().
 { return cartesian(i,j); }
PointS2< FT > operator() (const PointS2< FT > & p) const inline
Definition at line 898 of file Aff_transformationS2.h.
 { return transform(p); }
VectorS2< FT > operator() (const VectorS2< FT > & p) const inline
Definition at line 909 of file Aff_transformationS2.h.
 { return transform(p); }
DirectionS2< FT > operator() (const DirectionS2< FT > & d) const inline
Definition at line 920 of file Aff_transformationS2.h.
 { return transform(d); }
LineS2< FT > operator() (const LineS2< FT > & l) const inline
Definition at line 936 of file Aff_transformationS2.h.
 { return transform(l); }
Aff_transformationS2<FT> operator* (const Aff_transformationS2< FT > & t) const inline
Definition at line 787 of file Aff_transformationS2.h.
References Aff_transformationS2< FT >::ptr().
 {
   return (*ptr()) * (*t.ptr());
 }
std::ostream & print (std::ostream & os) const
Definition at line 958 of file Aff_transformationS2.h.
Referenced by operator<<().
 {
   ptr()->print(os);
   return os;
 }
Aff_transformation_rep_baseS2<FT>* ptr () const inline private
Definition at line 797 of file Aff_transformationS2.h.
Referenced by m_rocburn_interface_data::associate_pointer(), rocstar_rocfrac::associate_pointer(), modrocstar::associate_pointer(), Aff_transformationS2< FT >::cartesian(), m_init_1dmodules::COM_set_data::com_set_data(), Aff_transformationS2< FT >::is_even(), linked_list2::list_procelemlist(), newcommlist(), and Aff_transformationS2< FT >::operator*().
     {
       return  (Aff_transformation_rep_baseS2<FT>*)PTR;
     }
PointS2< FT > transform (const PointS2< FT > & p) const
Definition at line 892 of file Aff_transformationS2.h.
Referenced by DirectionS2< FT >::transform(), PointS2< FT >::transform(), RayS2< FT >::transform(), SegmentS2< FT >::transform(), VectorS2< FT >::transform(), and LineS2< FT >::transform().
 { return ptr()->transform(p); }
VectorS2< FT > transform (const VectorS2< FT > & p) const
Definition at line 903 of file Aff_transformationS2.h.
 { return ptr()->transform(p); }
DirectionS2< FT > transform (const DirectionS2< FT > & d) const
Definition at line 914 of file Aff_transformationS2.h.
 { return ptr()->transform(d); }
LineS2< FT > transform (const LineS2< FT > & l) const inline
Definition at line 927 of file Aff_transformationS2.h.
References LineS2< FT >::direction(), and LineS2< FT >::point().
 {
   return LineS2<FT>(ptr()->transform(l.point(0)),
                      ptr()->transform(l.direction()));
 }
The documentation for this class was generated from the following file:
Aff_transformationS2.h