Rocstar: Point_2< T > Class Template Reference
Point_2< T > Class Template Reference
#include <mapbasic.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Point_2_base RPoint_2
typedef R::Vector_2_base RVector_2
Public Member Functions
Point_2 ()
Point_2 (Origin)
Point_2 (T t)
Point_2 (T a, T b)
T & operator[] (const int i)
const T & operator[] (const int i) const
Point_2 & operator+= (const Vector_2< T > &v)
Assign operators.
Point_2 & operator-= (const Vector_2< T > &v)
Point_2 operator+ (const Vector_2< T > &v) const
Arithmatic operators.
Point_2 operator- (const Vector_2< T > &v) const
Vector_2< T > operator- (const Point_2 &v) const
bool operator== (const Point_2 &p) const
bool operator!= (const Point_2 &p) const
bool operator< (const Point_2 &v) const
bool is_origin () const
Point_2 ()
Point_2 (const Origin &o)
Point_2 (const CGAL::Point_2< R > &p)
Point_2 (const RPoint_2 &p)
Point_2 (const RT &hx, const RT &hy)
Point_2 (const RT &hx, const RT &hy, const RT &hw)
bool operator== (const CGAL::Point_2< R > &p) const
bool operator!= (const CGAL::Point_2< R > &p) const
RT hx () const
RT hy () const
RT hw () const
FT x () const
FT y () const
RT homogeneous (int i) const
FT cartesian (int i) const
FT operator[] (int i) const
int dimension () const
Bbox_2 bbox () const
CGAL::Point_2< R > transform (const CGAL::Aff_transformation_2< R > &t) const
Private Member Functions
Point_2 (const RVector_2 &v)
Friends
CGAL_FRIEND_INLINE
CGAL::Point_2< R > CGAL_SCOPE
vector_to_point_conversion CGAL_NULL_TMPL_ARGS (const CGAL::Vector_2< R > &v)
Additional Inherited Members
Protected Types inherited from Vector_2< T >
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Vector_2_base RVector_2
Protected Member Functions inherited from Vector_2< T >
Vector_2 ()
Vector_2 (Tt)
Vector_2 (Null_vector)
Vector_2 (Ta, Tb)
Vector_2 ()
Vector_2 (const CGAL::Vector_2< R > &v)
Vector_2 (const RVector_2 &v)
Vector_2 (const Null_vector &v)
Vector_2 (const RT &x, const RT &y)
Vector_2 (const RT &x, const RT &y, const RT &w)
T & operator[] (const int i)
const T & operator[] (const int &i) const
FT operator[] (int i) const
T x () const
FT x () const
T y () const
FT y () const
Vector_2 & operator+= (const Vector_2 &v)
Assign operators.
Vector_2 & operator-= (const Vector_2 &v)
Vector_2 & operator*= (const Tt)
Vector_2 & operator/= (const Tt)
Vector_2 operator+ (const Vector_2 &v) const
Arithmatic operators.
CGAL::Vector_2< R > operator+ (const CGAL::Vector_2< R > &w) const
Vector_2 operator- (const Vector_2 &v) const
Vector_2 operator- () const
CGAL::Vector_2< R > operator- (const CGAL::Vector_2< R > &w) const
CGAL::Vector_2< R > operator- () const
Vector_2 operator* (const Tt) const
T operator* (const Vector_2 &v) const
FT operator* (const CGAL::Vector_2< R > &w) const
CGAL::Vector_2< R > operator* (const RT &c) const
CGAL::Vector_2< R > operator* (const Quotient< RT > &q) const
Vector_2 operator/ (const Tt) const
CGAL::Vector_2< R > operator/ (const Quotient< RT > &q) const
CGAL::Vector_2< R > operator/ (const RT &c) const
T squared_norm () const
T norm () const
Vector_2 & normalize ()
Vector_2 & neg ()
bool operator== (const Vector_2 &p) const
bool operator== (const CGAL::Vector_2< R > &v) const
bool operator== (const Null_vector &v) const
bool operator!= (const Vector_2 &p) const
bool operator!= (const CGAL::Vector_2< R > &v) const
bool operator!= (const Null_vector &v) const
bool operator< (const Vector_2 &v) const
bool is_null () const
RT hx () const
RT hy () const
RT hw () const
RT homogeneous (int i) const
FT cartesian (int i) const
int dimension () const
CGAL::Direction_2< R > direction () const
CGAL::Vector_2< R > perpendicular (const Orientation &o) const
CGAL::Vector_2< R > transform (const CGAL::Aff_transformation_2< R > &t) const
Protected Attributes inherited from Vector_2< T >
T _x
T _y
Detailed Description
template<class T>
class Point_2< T >
Definition at line 274 of file mapbasic.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 81 of file Point_2.h.
typedef R_ R
Definition at line 79 of file Point_2.h.
typedef R::Point_2_base RPoint_2
Definition at line 82 of file Point_2.h.
typedef R::RT RT
Definition at line 80 of file Point_2.h.
typedef R::Vector_2_base RVector_2
Definition at line 83 of file Point_2.h.
Constructor & Destructor Documentation
Point_2 () inline
Definition at line 276 of file mapbasic.h.
Referenced by Point_2< R >::operator+(), and Point_2< R >::operator-().
 {}
Point_2 (Origin) inline
Definition at line 277 of file mapbasic.h.
 : Vector_2<T>( 0, 0) {}
Point_2 (T t) inline explicit
Definition at line 278 of file mapbasic.h.
 : Vector_2<T>(t) {}
Point_2 (T a, T b) inline
Definition at line 279 of file mapbasic.h.
 : Vector_2<T>(a, b) {}
Point_2 () inline
Definition at line 91 of file Point_2.h.
   {}
Point_2 (const Origin & o) inline
Definition at line 94 of file Point_2.h.
     : RPoint_2(o)
   {}
Point_2 (const CGAL::Point_2< R > & p) inline
Definition at line 98 of file Point_2.h.
     : RPoint_2((RPoint_2&)p)
   {}
Point_2 (const RPoint_2< T > & p) inline
Definition at line 102 of file Point_2.h.
     : RPoint_2(p)
   {}
Point_2 (const RT & hx, const RT & hy) inline
Definition at line 106 of file Point_2.h.
     : RPoint_2(hx, hy)
   {}
Point_2 (const RT & hx, const RT & hy, const RT & hw) inline
Definition at line 110 of file Point_2.h.
     : RPoint_2(hx, hy, hw)
   {}
Point_2 (const RVector_2 & v) inline private
Definition at line 181 of file Point_2.h.
     : RPoint_2(v)
   {}
Member Function Documentation
Bbox_2 bbox () const inline
Definition at line 169 of file Point_2.h.
   {
     return RPoint_2::bbox();
   }
FT cartesian (int i) const inline
Definition at line 154 of file Point_2.h.
Referenced by Point_2< R >::operator[]().
   {
     return RPoint_2::cartesian(i);
   }
int dimension () const inline
Definition at line 164 of file Point_2.h.
   {
     return 2;
   }
RT homogeneous (int i) const inline
Definition at line 149 of file Point_2.h.
   {
     return RPoint_2::homogeneous(i);
   }
RT hw () const inline
Definition at line 135 of file Point_2.h.
   {
     return RPoint_2::hw();
   }
RT hx () const inline
Definition at line 125 of file Point_2.h.
   {
     return RPoint_2::hx();
   }
RT hy () const inline
Definition at line 130 of file Point_2.h.
   {
     return RPoint_2::hy();
   }
bool is_origin () const inline
Definition at line 308 of file mapbasic.h.
 { return _x==0&&_y==0; }
bool operator!= (const CGAL::Point_2< R > & p) const inline
Definition at line 120 of file Point_2.h.
   {
     return !(*this == p);
   }
bool operator!= (const Point_2< T > & p) const inline
Definition at line 302 of file mapbasic.h.
   { return x()!=p.x() || y()!=p.y(); }
Point_2 operator+ (const Vector_2< T > & v) const inline
Arithmatic operators.
Definition at line 292 of file mapbasic.h.
   { return Point_2(_x+v.x(), _y+v.y()); }
Point_2& operator+= (const Vector_2< T > & v) inline
Assign operators.
Definition at line 286 of file mapbasic.h.
   { _x+=v.x(); _y+=v.y(); return *this; }
Point_2 operator- (const Vector_2< T > & v) const inline
Definition at line 294 of file mapbasic.h.
   { return Point_2(_x-v.x(), _y-v.y()); }
Vector_2<T> operator- (const Point_2< T > & v) const inline
Definition at line 296 of file mapbasic.h.
   { return Vector_2<T>(_x-v.x(), _y-v.y()); }
Point_2& operator-= (const Vector_2< T > & v) inline
Definition at line 288 of file mapbasic.h.
   { _x-=v.x(); _y-=v.y(); return *this; }
bool operator< (const Point_2< T > & v) const inline
Definition at line 305 of file mapbasic.h.
   { return Vector_2<T>::operator<(v); }
bool operator== (const CGAL::Point_2< R > & p) const inline
Definition at line 115 of file Point_2.h.
   {
     return RPoint_2::operator==(p);
   }
bool operator== (const Point_2< T > & p) const inline
Definition at line 299 of file mapbasic.h.
   { return x()==p.x() && y()==p.y(); }
FT operator[] (int i) const inline
Definition at line 159 of file Point_2.h.
   {
     return cartesian(i);
   }
T& operator[] (const int i) inline
Definition at line 280 of file mapbasic.h.
 { return (&_x)[i]; }
const T& operator[] (const int i) const inline
Definition at line 281 of file mapbasic.h.
 { return (&_x)[i]; }
CGAL::Point_2<R> transform (const CGAL::Aff_transformation_2< R > & t) const inline
Definition at line 174 of file Point_2.h.
   {
     return RPoint_2::transform(t);
   }
FT x () const inline
Definition at line 139 of file Point_2.h.
Referenced by Segment_2_Segment_2_pair< R >::intersection_type(), Point_2< R >::operator!=(), Point_2< R >::operator-(), and Point_2< R >::operator==().
   {
     return RPoint_2::x();
   }
FT y () const inline
Definition at line 144 of file Point_2.h.
Referenced by Segment_2_Segment_2_pair< R >::intersection_type(), Point_2< R >::operator!=(), Point_2< R >::operator-(), and Point_2< R >::operator==().
   {
     return RPoint_2::y();
   }
Friends And Related Function Documentation
CGAL_FRIEND_INLINE CGAL::Point_2<R> CGAL_SCOPE vector_to_point_conversion CGAL_NULL_TMPL_ARGS (const CGAL::Vector_2< R > & v) friend
The documentation for this class was generated from the following files:
mapbasic.h
Point_2.h