Rocstar: tecplot_data Class Reference
tecplot_data Class Reference
Base class for tecplot files Implements useful functions for tecplot file parsing.
#include <file.h>
Public Member Functions
virtual string get_mod_name ()
Get the name of the class (tecplot_data)
tecplot_data (ifstream &infile, ofstream &outfile, bool loud, string filename, int dim, std::vector< std::vector< int > > rFieldMappings, std::vector< index_order > rIndexOrder, std::vector< adj_map > conv_factor, std::vector< adj_map > norm_val)
Constructor that initializes values.
virtual ~tecplot_data ()
Destructor.
virtual void parse ()
Parse the tecplot file.
Public Member Functions inherited from datafile
datafile (ifstream &infile, ofstream &outfile, bool loud, string filename, int dim, std::vector< std::vector< int > > rFieldMappings, std::vector< index_order > rIndexOrder, std::vector< adj_map > conv_factor, std::vector< adj_map > norm_val)
Construct data file object using specified information.
virtual ~datafile ()
Free used data, delete the object.
datafile (const datafile &d)
Deep copy constructor.
int partition_layout (int partition, int n)
Get the size of n dimension of the specified partition.
points * get_points (int partition)
Get a partitions' points.
pnt get_point (int n)
Get the nth point of the file.
pnt get_point (int n, int partition)
Get the nth point of the specified partition.
int get_num_points ()
Get the number of points in the file.
int get_num_points (int partition)
Get the number of points in the specified partition.
int get_num_vars ()
Get the number of variables in the file.
string get_title ()
Get file title if specified in file header.
int get_num_partitions ()
Get number of partition in the file.
Protected Member Functions
void read_header ()
Read the tecplot header from the file and retrieve the title, variable names, and number of variables.
int count_zones ()
Count the number of zones in the tecplot file, starting from the current location of the file stream.
void seek_to_zone ()
Seek to the next zone in the file.
string * get_zone_header (int zone)
Read the zone header.
string * get_zone_nodes (int zone)
Retrieve zone point data from the zone body.
void zone_error_out (int zone, string zs_err)
Log an error message with appended zone information so the error can be located.
void zone_status_out (int zone, string zs_out)
Log a status message with appended zone information.
tpzone * zone_detect (int zone)
Read the header information for the specified zone, then create a new zone object based on the type of zone detected.
Protected Member Functions inherited from datafile
void error_out (string err_ps)
Log the string specified as an error event.
void status_out (string st_ps)
Log the string specified as a status event.
void LogFieldMappings ()
Log the field mapping data from the command line and stored in mFieldMappings.
int get_num_dep_vars ()
Get number of dependent variables.
index_order get_index_order (int partition)
Static Private Attributes
static const int BUFFER_SIZE = 512
Additional Inherited Members
Protected Attributes inherited from datafile
string filename
ifstream & infile
ofstream & outfile
bool loud
partition ** data_part
int num_partitions
std::vector< string > var_names
string title
int dimensions
std::vector< adj_map > conv_factor
std::vector< adj_map > norm_val
std::vector< std::vector< int > > mFieldMappings
std::vector< index_order > mIndexOrder
Detailed Description
Base class for tecplot files Implements useful functions for tecplot file parsing.
Definition at line 206 of file file.h.
Constructor & Destructor Documentation
tecplot_data (ifstream & infile, ofstream & outfile, bool loud, string filename, int dim, std::vector< std::vector< int > > rFieldMappings, std::vector< index_order > rIndexOrder, std::vector< adj_map > conv_factor, std::vector< adj_map > norm_val)
Constructor that initializes values.
Definition at line 186 of file file.cpp.
     : datafile(infile, outfile, loud, filename, dim, rFieldMappings, rIndexOrder, conv_factor, norm_val){
     return;
 }
~tecplot_data () virtual
Destructor.
Definition at line 182 of file file.cpp.
{
     return;
 }
Member Function Documentation
int count_zones () protected
Count the number of zones in the tecplot file, starting from the current location of the file stream.
For count of all zones, seek to beginning of file then call.
Returns
Number of zones from the current location.
Definition at line 262 of file file.cpp.
References datafile::infile, and seek_to_zone().
Referenced by parse().
{
     int zones = 0;
     //Seek to the next zone until
     //end of file is reached
     seek_to_zone();
     while(!infile.eof()){
         zones++;
         seek_to_zone();
     }
     infile.clear();
     infile.seekg(0, std::ios::beg);
     return zones;
 }
string get_mod_name () virtual
Get the name of the class (tecplot_data)
Returns
Name of the class
Reimplemented from datafile.
Definition at line 194 of file file.cpp.
{
     return string("Tecplot File");
 }
string * get_zone_header (int zone) protected
Read the zone header.
Returns
String of zone header
Definition at line 373 of file file.cpp.
References i, datafile::infile, and seek_to_zone().
Referenced by zone_detect().
{
     //Seek to beginning
     infile.clear();
     infile.seekg(0, std::ios::beg);
     //Seek to specified zone
     for(int i=0; i<=zone; i++){
         seek_to_zone();
     }
     string temp;
     infile >> temp;
     string *header = new string;
     //TODO
     //Make finding the end of the header
     //more robust
     while( (temp.find("DT=") == string::npos || temp.find("\"") != string::npos) && !infile.eof()){
         *header += temp;
         *header += " ";
         infile >> temp;
     }
     *header += temp;
     //Get the last line
     char c;
     infile.get(c);
     while(c != '\n'){
         *header += c;
         infile.get(c);
     }
     return header;
 }
string * get_zone_nodes (int zone) protected
Retrieve zone point data from the zone body.
Returns
String of zone data points.
Definition at line 414 of file file.cpp.
References BUFFER_SIZE, i, datafile::infile, datafile::num_partitions, and seek_to_zone().
Referenced by zone_detect().
{
     string *ret = new string;
     //Seek to beginning
     infile.clear();
     infile.seekg(0, std::ios::beg);
     //Check valid zone number
     if(zone+1 > num_partitions)
         return NULL;
     //Seek to specified zone
     for(int i=0; i<=zone; i++){
         seek_to_zone();
     }
     char line[BUFFER_SIZE];
     string curr_line;
     infile.getline(line, BUFFER_SIZE-1);
     curr_line = line;
     //Skip through the zone header
     while( (curr_line.find("DT=") == string::npos || curr_line.find("\"") != string::npos)
             && !infile.eof() ){
         infile.getline(line, 511);
         curr_line = line;
     }
     //Read zone point data
     infile.getline(line, 511);
     curr_line = line;
     //Stop when the next zone is reached, or eof
     while( (curr_line.find("ZONE") == string::npos) && !infile.eof() ){
         *ret += curr_line;
         infile.getline(line, 511);
         curr_line = line;
     }
     if(infile.eof()){
         infile.clear();
         infile.seekg(0, std::ios::beg);
     }
     return ret;
 }
void parse () virtual
Parse the tecplot file.
Read the header using read_header(), iterate through each zone and retrieve the zone header and zone body. Create a new partition object and have that object parse the zone. Log and error output.
Reimplemented from datafile.
Definition at line 281 of file file.cpp.
References CGAL::compare(), datafile::conv_factor, count_zones(), datafile::data_part, datafile::error_out(), datafile::get_index_order(), datafile::get_num_dep_vars(), datafile::get_num_vars(), i, datafile::infile, itoa(), datafile::mFieldMappings, datafile::norm_val, datafile::num_partitions, partition::parse_layout(), read_header(), datafile::status_out(), zone_detect(), zone_error_out(), and zone_status_out().
{
     //Get header information
     //  - Sets num_vars
     //  - Sets title
     read_header();
     int zone_count = count_zones();
     if(zone_count == 0){
         string err_ps("No Zones Found");
         error_out(err_ps);
         return;
     }
     status_out(itoa(zone_count) + " Zone(s) Detected");
     //Seek to beginning
     infile.clear();
     infile.seekg(0, std::ios::beg);
     this->num_partitions = zone_count;
     this->data_part = new partition*[this->num_partitions];
     for(int i=0; i<zone_count; i++){
         //Detect zone
         //Create proper zone object
         data_part[i] = zone_detect(i);
         //Parse zone header
         if(data_part[i] != NULL){
             data_part[i]->parse_layout();
             if( data_part[i]->get_error().compare("") != 0)
                 zone_error_out(i, data_part[i]->get_error());
             else
                 zone_status_out(i, data_part[i]->get_status());
         }
         else{
             string err_ps("Invalid Zone");
             zone_error_out(i, err_ps);
         }
     }
     //Parse zone data
     for(int i=0; i<zone_count; i++){
         if(data_part[i] != NULL){
             if(data_part[i]->parse_data(get_num_dep_vars(), get_num_vars(), mFieldMappings,
                                         get_index_order(i), conv_factor, norm_val))
                 zone_status_out(i, data_part[i]->get_status());
             else
                 zone_error_out(i, data_part[i]->get_error());
         }
     }
     return;
 }
void read_header () protected
Read the tecplot header from the file and retrieve the title, variable names, and number of variables.
Log the information as a status event.
Definition at line 207 of file file.cpp.
References datafile::infile, itoa(), datafile::LogFieldMappings(), readQuoteExpression(), datafile::status_out(), datafile::title, and datafile::var_names.
Referenced by parse().
{
     //Seek to beginning
     infile.clear();
     infile.seekg(0, std::ios::beg);
     string temp;
     string header;
     infile >> temp;
     //Read until a Zone header is reached
     while(temp.compare(string("ZONE")) != 0){
         header += temp;
         header += " ";
         infile >> temp;
     }
     //Parse the file title
     std::vector<string> title_parse = readQuoteExpression(header, string("TITLE"));
     if(title_parse.size() == 1){
         this->title = title_parse[0];
     }
     //Parse variable names
     this->var_names = readQuoteExpression(header, string("VARIABLES"));
     status_out(itoa(this->var_names.size()) + " Variable(s) Detected");
     //Log Field Mapping
     LogFieldMappings();
     //Seek to beginning
     infile.clear();
     infile.seekg(0, std::ios::beg);
 }
void seek_to_zone () protected
Seek to the next zone in the file.
Starting position is the current location of the infile object.
Definition at line 198 of file file.cpp.
References datafile::infile.
Referenced by count_zones(), get_zone_header(), and get_zone_nodes().
{
     string tmp("");
     while(!infile.eof() && tmp.compare(string("ZONE")) != 0)
         infile >> tmp;
 }
tpzone * zone_detect (int zone) protected
Read the header information for the specified zone, then create a new zone object based on the type of zone detected.
Parameters
zone Zone number
Returns
Zone object
Definition at line 340 of file file.cpp.
References CGAL::compare(), get_zone_header(), get_zone_nodes(), readCommaExpression(), and zone_status_out().
Referenced by parse().
{
     //Retrieve zone header and read zone type
     string *zheader = get_zone_header(zone);
     std::vector<string> ztype = readCommaExpression(*zheader, string("ZONETYPE"));
     tpzone *retzone = NULL;
     if(ztype.size() == 1){
         //Get zone data
         string *zdata = get_zone_nodes(zone);
         //If the zone is an ordered zone, create a new ordered zone object
         if(ztype[0].compare(string("Ordered")) == 0){
             retzone = new tpz_ordered( zheader, zdata );
             string zone_st("Ordered Zone Detected");
             zone_status_out(zone, zone_st);
         }
         //If the zone is FEQuad, create a new FEQuad object
         else if(ztype[0].compare(string("FEQuadrilateral")) == 0){
             retzone = new tpz_fequad( zheader, zdata );
             string zone_st("FEQuadrilateral Zone Detected");
             zone_status_out(zone, zone_st);
         }
     }
     return retzone;
 }
void zone_error_out (int zone, string zs_err) protected
Log an error message with appended zone information so the error can be located.
Parameters
zone Zone number affected.
zs_err Error message.
Definition at line 252 of file file.cpp.
References datafile::error_out(), and itoa().
Referenced by parse().
{
     string err_ps("Zone ");
     err_ps = err_ps + itoa(zone) + "  |  " + zs_err;
     error_out(err_ps);
 }
void zone_status_out (int zone, string zs_out) protected
Log a status message with appended zone information.
Parameters
zone Zone number affected.
zs_out Status message.
Definition at line 245 of file file.cpp.
References itoa(), and datafile::status_out().
Referenced by parse(), and zone_detect().
{
     string st_ps("Zone ");
     st_ps = st_ps + itoa(zone) + "  |  " + zs_out;
     status_out(st_ps);
 }
Member Data Documentation
const int BUFFER_SIZE = 512 static private
Definition at line 293 of file file.h.
Referenced by get_zone_nodes().
The documentation for this class was generated from the following files:
file.h
file.cpp