Rocstar: INode Class Reference
INode Class Reference
#include <HDS_overlay.h>
Public Types
typedef INode Self
typedef Halfedge_overlay Halfedge
typedef In_place_list_n_base
< INode, 2 > Base
Public Member Functions
INode ()
~INode ()
bool operator== (const INode &x)
const Point_2S & nat_coor (const int color) const
void nat_coor (const int color, Point_2 &p) const
void set_parent (Halfedge *h, const Point_2 &p, int color)
int id () const
void set_id (int i)
Parent_type parent_type (const int color) const
Parent_type blue_parent_type () const
Parent_type green_parent_type () const
Halfedge * halfedge (const int color) const
Halfedge * blue_halfedge () const
Halfedge * green_halfedge () const
Protected Attributes
Host_face bp
Host_face gp
Point_2S b_nc
Point_2S g_nc
int _id
Private Member Functions
Parent_type pt (const Point_2 &p)
Private Member Functions inherited from In_place_list_n_base< INode, 2 >
In_place_list_n_base ()
Additional Inherited Members
Private Attributes inherited from In_place_list_n_base< INode, 2 >
INode * next_link [n]
INode * prev_link [n]
Detailed Description
Definition at line 305 of file HDS_overlay.h.
Member Typedef Documentation
typedef In_place_list_n_base<INode,2> Base
Definition at line 309 of file HDS_overlay.h.
typedef Halfedge_overlay Halfedge
Definition at line 308 of file HDS_overlay.h.
typedef INode Self
Definition at line 307 of file HDS_overlay.h.
Constructor & Destructor Documentation
INode () inline
Definition at line 321 of file HDS_overlay.h.
 : _id(-1) {}
~INode () inline
Definition at line 322 of file HDS_overlay.h.
References bp, gp, and RFC_assertion_code.
 { RFC_assertion_code(bp=gp=Host_face()); }
Member Function Documentation
Halfedge* blue_halfedge () const inline
Definition at line 361 of file HDS_overlay.h.
References bp, and Host_face::halfedge().
 { return bp.halfedge(); }
Parent_type blue_parent_type () const inline
Definition at line 354 of file HDS_overlay.h.
References bp, and Host_face::parent_type().
 { return bp.parent_type(); }
Halfedge* green_halfedge () const inline
Definition at line 362 of file HDS_overlay.h.
References gp, and Host_face::halfedge().
 { return gp.halfedge(); }
Parent_type green_parent_type () const inline
Definition at line 355 of file HDS_overlay.h.
References gp, and Host_face::parent_type().
 { return gp.parent_type(); }
Halfedge* halfedge (const int color) const inline
Definition at line 357 of file HDS_overlay.h.
References BLUE, bp, gp, GREEN, Host_face::halfedge(), and RFC_assertion.
Referenced by Overlay::convert_nat_coordinates(), Overlay::count_subnodes(), Overlay::get_edge_parent(), Overlay::get_nat_coor(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::number_a_subnode(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), Overlay::verify_inode(), Overlay::write_inodes_tec(), and Overlay::write_inodes_vec().
{
     if ( color == BLUE) { return bp.halfedge(); }
     else { RFC_assertion( color == GREEN); return gp.halfedge(); }
   }
int id () const inline
Definition at line 347 of file HDS_overlay.h.
References _id.
Referenced by Overlay::get_subnode_copies(), Overlay::get_subnode_id(), and Overlay::set_subnode_id().
 { return _id; }
const Point_2S& nat_coor (const int color) const inline
Definition at line 327 of file HDS_overlay.h.
References b_nc, BLUE, g_nc, GREEN, and RFC_assertion.
Referenced by Overlay::convert_nat_coordinates(), Overlay::get_edge_parent(), Overlay::get_nat_coor(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::write_inodes_tec(), and Overlay::write_inodes_vec().
{
     if ( color == BLUE) return b_nc;
     else { RFC_assertion(color == GREEN); return g_nc; }
   }
void nat_coor (const int color, Point_2 & p) const inline
Definition at line 332 of file HDS_overlay.h.
References b_nc, BLUE, g_nc, GREEN, and RFC_assertion.
{
     if ( color == BLUE) { p[0]=b_nc[0]; p[1]=b_nc[1]; }
     else { RFC_assertion(color == GREEN); p[0]=g_nc[0]; p[1]=g_nc[1]; }
   }
bool operator== (const INode & x) inline
Definition at line 324 of file HDS_overlay.h.
References b_nc, bp, g_nc, and gp.
   { return ( b_nc == x.b_nc && g_nc == x.g_nc && bp == x.bp && gp == x.gp); }
Parent_type parent_type (const int color) const inline
Definition at line 350 of file HDS_overlay.h.
References BLUE, bp, gp, GREEN, Host_face::parent_type(), and RFC_assertion.
Referenced by Overlay::associate_green_vertices(), Overlay::convert_nat_coordinates(), Overlay::count_subnodes(), Overlay::get_edge_parent(), Overlay::get_nat_coor(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::number_a_subnode(), Overlay::project_adjacent_green_vertices(), Overlay::sort_on_green_edges(), and Overlay::verify_inode().
{
     if ( color == BLUE) { return bp.parent_type(); }
     else { RFC_assertion( color == GREEN); return gp.parent_type(); }
   }
Parent_type pt (const Point_2 & p) inline private
Definition at line 365 of file HDS_overlay.h.
References PARENT_EDGE, PARENT_FACE, and PARENT_VERTEX.
Referenced by set_parent().
{
     if ( p[1] != 0) return PARENT_FACE;
     else if ( p[0] != 0) return PARENT_EDGE;
     else return PARENT_VERTEX;
   }
void set_id (int i) inline
Definition at line 348 of file HDS_overlay.h.
References _id, and i.
 { _id = i; }
void set_parent (Halfedge * h, const Point_2 & p, int color) inline
Definition at line 337 of file HDS_overlay.h.
References b_nc, BLUE, bp, g_nc, gp, GREEN, pt(), and RFC_assertion.
Referenced by Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::match_features_0(), Overlay::overlay_init(), Overlay::project_adjacent_green_vertices(), and HDS_accessor< Tag_true >::set_parent().
{
     if ( color == BLUE) {
       bp = Host_face( h, pt(p)); b_nc[0]=p[0]; b_nc[1]=p[1];
     }
     else {
       RFC_assertion( color == GREEN);
       gp = Host_face( h, pt(p)); g_nc[0]=p[0]; g_nc[1]=p[1];
     }
   }
Member Data Documentation
int _id protected
Definition at line 318 of file HDS_overlay.h.
Referenced by id(), and set_id().
Point_2S b_nc protected
Definition at line 316 of file HDS_overlay.h.
Referenced by nat_coor(), operator==(), and set_parent().
Host_face bp protected
Definition at line 314 of file HDS_overlay.h.
Referenced by blue_halfedge(), blue_parent_type(), halfedge(), operator==(), parent_type(), set_parent(), and ~INode().
Point_2S g_nc protected
Definition at line 317 of file HDS_overlay.h.
Referenced by nat_coor(), operator==(), and set_parent().
Host_face gp protected
Definition at line 315 of file HDS_overlay.h.
Referenced by green_halfedge(), green_parent_type(), halfedge(), operator==(), parent_type(), set_parent(), and ~INode().
The documentation for this class was generated from the following file:
HDS_overlay.h