Rocstar: Timer Class Reference
Timer Class Reference
#include <MsqTimer.hpp>
Public Member Functions
Timer ()
void reset ()
double since_last_check ()
double since_birth () const
Timer ()
void reset ()
double since_last_check ()
double since_birth () const
Private Attributes
double atBirth
double atLastCheck
Detailed Description
Definition at line 54 of file includeLinks/MsqTimer.hpp.
Constructor & Destructor Documentation
Timer ()
Definition at line 80 of file Misc/MsqTimer.cpp.
References Timer::atBirth, and Timer::atLastCheck.
     : atBirth(now())
 {
   atLastCheck = atBirth;
 }
Timer ()
Member Function Documentation
void reset ()
Definition at line 86 of file Misc/MsqTimer.cpp.
Referenced by TerminationCriterion::reset_inner().
 {
   atBirth=now();
   atLastCheck = atBirth;
 }
void reset ()
double since_birth () const
double since_birth () const
Definition at line 100 of file Misc/MsqTimer.cpp.
Referenced by ConjugateGradient::optimize_vertex_positions(), and TerminationCriterion::terminate().
 {
   return now() - atBirth;
 }
double since_last_check ()
Definition at line 92 of file Misc/MsqTimer.cpp.
 {
   double right_now = now();
   double rv = right_now - atLastCheck;
   atLastCheck = right_now;
   return rv;
 }
double since_last_check ()
Member Data Documentation
double atBirth private
Definition at line 71 of file includeLinks/MsqTimer.hpp.
Referenced by Timer::Timer().
double atLastCheck private
Definition at line 72 of file includeLinks/MsqTimer.hpp.
Referenced by Timer::Timer().
The documentation for this class was generated from the following files:
includeLinks/MsqTimer.hpp
Misc/MsqTimer.cpp