Rocstar: SchedulerAction Class Reference
SchedulerAction Class Reference abstract
#include <Action.h>
Public Member Functions
SchedulerAction (Scheduler *s, int n, const char *at[], int i[], void *p=0, char *name=NULL)
virtual ~SchedulerAction ()
virtual void declare (Scheduler &)=0
virtual void init (double t)
virtual void run (double t, double dt, double alpha)
virtual void finalize ()
virtual void print (FILE *f, char *container_name)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Public Member Functions inherited from Action
Action (void *p=0, char *name=NULL)
Action (int n, const char *at[], int *i=NULL, void *p=0, char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, char *name=NULL)
virtual ~Action ()
virtual char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
Private Attributes
Scheduler * sched
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_attribute_handle (int i)
int get_attribute_handle_const (int i)
int get_attribute_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Detailed Description
Definition at line 78 of file Action.h.
Constructor & Destructor Documentation
SchedulerAction (Scheduler * s, int n, const char * at[], int i[], void * p = 0, char * name = NULL) inline
Definition at line 83 of file Action.h.
 : Action(n, at, i, p, name), sched(s)  {}
~SchedulerAction () virtual
Definition at line 119 of file Action.C.
References sched.
{
   if ( sched) delete sched;
 }
Member Function Documentation
virtual void declare (Scheduler &) pure virtual
Reimplemented from Action.
Implemented in ActionE.
void finalize () virtual
Reimplemented from Action.
Definition at line 138 of file Action.C.
References Scheduler::finalize_actions(), and sched.
 {
   sched->finalize_actions();
 }
void init (double t) virtual
Reimplemented from Action.
Definition at line 123 of file Action.C.
References Scheduler::init_actions(), and sched.
 {
   sched->init_actions(t);
 }
void print (FILE * f, char * container_name) virtual
Definition at line 143 of file Action.C.
References Action::name(), Scheduler::print(), and sched.
 {
   fprintf(f, "graph: { title: \"%s\" label: \"%s\" \n\
         status: folded \n\
         display_edge_labels: yes \n\
         layoutalgorithm: tree   \n\
         scaling: maxspect   \n\
         color :  red           \n\
         node.color     : black   \n\
         node.textcolor : red   \n\
         node.bordercolor: black \n\
         node.borderwidth: 1    \n\
         edge.color     : lightblue   \n\
         edge.arrowsize : 7   \n\
         edge.thickness : 2   \n\
         edge.fontname:\"helvO08\"  \n\
         node.label: \"no type\" \n", name(), name());
   sched->print(f, container_name);
   fprintf(f, "}\n");
 }
void print_toposort (FILE * f) virtual
Reimplemented from Action.
Definition at line 164 of file Action.C.
References Scheduler::print_toposort(), and sched.
 {
   fprintf(f, "( ");
   sched->print_toposort(f);
   fprintf(f, ") ");
 }
void run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 132 of file Action.C.
References Scheduler::run_actions(), and sched.
 {
   //sched->set_alpha(alpha);
   sched->run_actions(t, dt);
 }
void schedule () virtual
Reimplemented from Action.
Definition at line 128 of file Action.C.
References sched, and Scheduler::schedule().
{
   sched->schedule();
 }
Member Data Documentation
Scheduler* sched private
Definition at line 81 of file Action.h.
Referenced by finalize(), init(), print(), print_toposort(), run(), schedule(), and ~SchedulerAction().
The documentation for this class was generated from the following files:
Action.h
Action.C