Rocstar: Line_2< R, T > Class Template Reference
Line_2< R, T > Class Template Reference
#include <cartesian_classes.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Line_2_base RLine_2
Public Member Functions
Line_2 ()
~Line_2 ()
Line_2 (const CGAL::Line_2< R > &l)
Line_2 (const CGAL::Point_2< R > &p, const CGAL::Point_2< R > &q)
Line_2 (const RT &a, const RT &b, const RT &c)
Line_2 (const RLine_2 &l)
Line_2 (const CGAL::Segment_2< R > &s)
Line_2 (const CGAL::Ray_2< R > &r)
Line_2 (const CGAL::Point_2< R > &p, const CGAL::Direction_2< R > &d)
bool operator== (const CGAL::Line_2< R > &l) const
bool operator!= (const CGAL::Line_2< R > &l) const
RT a () const
RT b () const
RT c () const
FT x_at_y (const FT &y) const
FT y_at_x (const FT &x) const
CGAL::Line_2< R > perpendicular (const CGAL::Point_2< R > &p) const
CGAL::Line_2< R > opposite () const
CGAL::Point_2< R > point (int i) const
CGAL::Point_2< R > projection (const CGAL::Point_2< R > &p) const
CGAL::Point_2< R > point () const
CGAL::Direction_2< R > direction () const
Oriented_side oriented_side (const CGAL::Point_2< R > &p) const
bool has_on (const CGAL::Point_2< R > &p) const
bool has_on_boundary (const CGAL::Point_2< R > &p) const
bool has_on_positive_side (const CGAL::Point_2< R > &p) const
bool has_on_negative_side (const CGAL::Point_2< R > &p) const
bool is_horizontal () const
bool is_vertical () const
bool is_degenerate () const
CGAL::Line_2< R > transform (const CGAL::Aff_transformation_2< R > &t) const
Detailed Description
template<class R, class T = typename R::Rep_tag>
class Line_2< R, T >
Definition at line 67 of file cartesian_classes.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 89 of file Line_2.h.
typedef R_ R
Definition at line 87 of file Line_2.h.
typedef R::Line_2_base RLine_2
Definition at line 90 of file Line_2.h.
typedef R::RT RT
Definition at line 88 of file Line_2.h.
Constructor & Destructor Documentation
Line_2 () inline
Definition at line 92 of file Line_2.h.
     : RLine_2()
   {}
~Line_2 () inline
Definition at line 96 of file Line_2.h.
   {}
Line_2 (const CGAL::Line_2< R > & l) inline
Definition at line 99 of file Line_2.h.
     : RLine_2((RLine_2&)l)
   {}
Line_2 (const CGAL::Point_2< R > & p, const CGAL::Point_2< R > & q) inline
Definition at line 103 of file Line_2.h.
     : RLine_2(p,q)
   {}
Line_2 (const RT & a, const RT & b, const RT & c) inline
Definition at line 107 of file Line_2.h.
     : RLine_2(a,b,c)
   {}
Line_2 (const RLine_2< R, T > & l) inline
Definition at line 112 of file Line_2.h.
     : RLine_2(l)
   {}
Line_2 (const CGAL::Segment_2< R > & s) inline
Definition at line 117 of file Line_2.h.
     : RLine_2(s)
   {}
Line_2 (const CGAL::Ray_2< R > & r) inline
Definition at line 121 of file Line_2.h.
     : RLine_2(r)
   {}
Line_2 (const CGAL::Point_2< R > & p, const CGAL::Direction_2< R > & d) inline
Definition at line 125 of file Line_2.h.
     : RLine_2(p,d)
   {}
Member Function Documentation
RT a () const inline
Definition at line 140 of file Line_2.h.
Referenced by a_d_tensors(), bc_enforce(), modsortsearch::binarysearchinteger(), cmpct1(), cmpct2(), com_settypeinfo(), comp_row_k(), comp_row_mat(), compositestiffnes(), modtools::comppythag(), modsortsearch::cyclelist(), modsortsearch::findcommonsortedintegers(), modtools::floatequal(), modtools::floatgreater(), modtools::floatless(), genxwriterocinout(), implicit_bc_enforce(), implicit_soln(), inrt_checkuserinput(), inrt_printmaterialinput(), inrt_printuserinput(), invert(), invert2(), invert3x3(), kronecker_product(), spec_rflu_modchemistry::lusolve(), matmul2(), modsortsearch::mergesortedintegers(), peri_printuserinput(), peul_printuserinput(), peul_rocflo_post(), plag_allocatememory(), plag_allocatememorypost(), plag_binsortnozzleinlet(), plag_binsortspatialdist(), plag_getcellindices(), plag_printuserinput(), plag_processeulerfield(), plag_writestattecascii(), plag_writetecplotascii(), data_py::polin2(), principal_stress(), printpostinput(), printprepinput(), printtofluinput(), prep_modbcdistribution::profinflowvttaylorcyl(), pythag(), modsortsearch::quicksortinteger(), modsortsearch::quicksortintegerinteger(), modsortsearch::quicksortrfreal(), modsortsearch::quicksortrfrealinteger(), modrandom::rand1imposedpdf(), modrandom::rand1lognormal(), modrandom::rand1normal(), modrandom::rand1uniform(), modrandom::randimposedpdf(), modrandom::randlognormal(), modrandom::randnormal(), modrandom::randuniform(), read_msh(), removebcht_newtemp(), removebcs_newa(), modsortsearch::removecommonsortedintegers(), modsortsearch::removecommonsortedintegersfancy(), modsortsearch::removeinteger(), rflo_checkvalidity(), rflo_dualmultigrid(), rflo_flowsolver(), rflo_gridremesh(), rflo_initflowsolver(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_multigrid(), rflo_openthrustfile(), rflo_printuserinput(), rflo_timestepping(), rflo_moddegeneratecornedge::rflo_writedegeneratec(), rflo_modforcesmoments::rflo_writepatchcoeffsinfo(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_computeenerdissoles(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_computeintegral3oles(), rflu_modplottingvars::rflu_computeplottingvarscore(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_computeweightsoles(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modextractflowdata::rflu_extractflowdatasod(), rflu_modextractflowdata::rflu_extractflowdatasommspi(), rflu_modextractflowdata::rflu_extractflowdatastg1d(), rflu_modextractflowdata::rflu_extractflowdatastg2d(), rflu_flowsolver(), rflu_modoles::rflu_getlposinvoles(), rflu_modoles::rflu_getlposoles(), rflu_modhashtable::rflu_hashbuildkey(), rflu_modhashtable::rflu_hashbuildkey1(), rflu_initflowhardcode(), rflu_invertmatrixsvd(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_modnscbc::rflu_nscbc_comprhsff(), rflu_modnscbc::rflu_nscbc_comprhsifveltemp(), rflu_modnscbc::rflu_nscbc_comprhsof(), rflu_modnscbc::rflu_nscbc_comprhssw(), rflu_modexactflow::rflu_setexactflowlinear(), rflu_modexactflow::rflu_setexactflowtrig(), rmat3_det(), rocflo_blocks(), rocflo_init(), rocflo_post(), rocflo_surf(), rocflo_toflu(), rocfracmain::rocfracinitialize(), rocfracsubinterface::rocfracinterfaceinitial(), rocpart_post(), rs(), modsortsearch::simplifysortedintegers(), modtools::swapintegers(), modtools::swaprfreals(), tensormul(), tred1(), tred2(), tridg(), turb_printuserinput(), vecmatvecmul(), write_grda(), write_grdb(), write_msh(), writeconvergence(), writetecplotascii(), and writetecplotbinary().
   {
     return RLine_2::a();
   }
RT b () const inline
Definition at line 145 of file Line_2.h.
   {
     return RLine_2::b();
   }
RT c () const inline
Definition at line 150 of file Line_2.h.
Referenced by a_d_tensors(), compositestiffnes(), modsortsearch::findcommonsortedintegers(), huang_const_model(), jacobi(), kronecker_product(), matmul2(), mixtperf_co2_cguvw(), mixtperf_d_cgp(), mixtperf_po_cgpuvw(), mixtperf_t_cgr(), modsortsearch::removecommonsortedintegersfancy(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modweights::rflu_computewtsx2c_1d(), rflu_modfacelist::rflu_getopposingfaces(), rflu_initflowhardcode(), rflu_modexactflow::rflu_setexactflowlinear(), rflu_modexactflow::rflu_setexactflowtrig(), modtools::swapintegers(), modtools::swaprfreals(), tensormul(), tql1(), tql2(), tridg(), vecmatvecmul(), writegeneric(), writetecplotascii(), and writetecplotbinary().
   {
     return RLine_2::c();
   }
CGAL::Direction_2<R> direction () const inline
Definition at line 191 of file Line_2.h.
   {
     return RLine_2::direction();
   }
bool has_on (const CGAL::Point_2< R > & p) const inline
Definition at line 202 of file Line_2.h.
   {
     return RLine_2::has_on_boundary(p);
   }
bool has_on_boundary (const CGAL::Point_2< R > & p) const inline
Definition at line 207 of file Line_2.h.
   {
     return RLine_2::has_on_boundary(p);
   }
bool has_on_negative_side (const CGAL::Point_2< R > & p) const inline
Definition at line 217 of file Line_2.h.
   {
     return RLine_2::has_on_negative_side(p);
   }
bool has_on_positive_side (const CGAL::Point_2< R > & p) const inline
Definition at line 212 of file Line_2.h.
   {
     return RLine_2::has_on_positive_side(p);
   }
bool is_degenerate () const inline
Definition at line 234 of file Line_2.h.
   {
     return RLine_2::is_degenerate();
   }
bool is_horizontal () const inline
Definition at line 222 of file Line_2.h.
   {
     return RLine_2::is_horizontal();
   }
bool is_vertical () const inline
Definition at line 228 of file Line_2.h.
   {
     return RLine_2::is_vertical();
   }
bool operator!= (const CGAL::Line_2< R > & l) const inline
Definition at line 135 of file Line_2.h.
   {
     return !(*this == l);
   }
bool operator== (const CGAL::Line_2< R > & l) const inline
Definition at line 130 of file Line_2.h.
   {
     return RLine_2::operator==(l);
   }
CGAL::Line_2<R> opposite () const inline
Definition at line 171 of file Line_2.h.
   {
     return RLine_2::opposite();
   }
Oriented_side oriented_side (const CGAL::Point_2< R > & p) const inline
Definition at line 197 of file Line_2.h.
   {
     return RLine_2::oriented_side(p);
   }
CGAL::Line_2<R> perpendicular (const CGAL::Point_2< R > & p) const inline
Definition at line 166 of file Line_2.h.
   {
     return RLine_2::perpendicular(p);
   }
CGAL::Point_2<R> point (int i) const inline
Definition at line 176 of file Line_2.h.
   {
     return RLine_2::point(i);
   }
CGAL::Point_2<R> point () const inline
Definition at line 186 of file Line_2.h.
   {
     return RLine_2::point();
   }
CGAL::Point_2<R> projection (const CGAL::Point_2< R > & p) const inline
Definition at line 181 of file Line_2.h.
   {
     return RLine_2::projection(p);
   }
CGAL::Line_2<R> transform (const CGAL::Aff_transformation_2< R > & t) const inline
Definition at line 240 of file Line_2.h.
   {
     return  RLine_2::transform(t);
   }
FT x_at_y (const FT & y) const inline
Definition at line 156 of file Line_2.h.
   {
     return RLine_2::x_at_y(y);
   }
FT y_at_x (const FT & x) const inline
Definition at line 161 of file Line_2.h.
   {
     return RLine_2::y_at_x(x);
   }
The documentation for this class was generated from the following files:
cartesian_classes.h
Line_2.h