Rocstar: moderror Module Reference
moderror Module Reference
Public Member Functions
subroutine registerfunction (global, funName, fileName)
subroutine deregisterfunction (global)
subroutine errorstop (global, errorCode, errorLine, addMessage)
Public Attributes
integer, parameter err_none = 0
integer, parameter err_register_fun = 1
integer, parameter err_reached_default = 2
integer, parameter err_previous_errors = 3
integer, parameter err_external_funct = 4
integer, parameter err_exceeds_decl_mem = 5
integer, parameter err_unknown_option = 6
integer, parameter err_illegal_value = 7
integer, parameter err_system_command = 8
integer, parameter err_compile_option = 9
integer, parameter err_allocate = 10
integer, parameter err_deallocate = 11
integer, parameter err_associated = 12
integer, parameter err_allocated = 13
integer, parameter err_dependent_input = 15
integer, parameter err_file_open = 20
integer, parameter err_file_close = 21
integer, parameter err_file_read = 22
integer, parameter err_file_write = 23
integer, parameter err_file_exist = 24
integer, parameter err_unknown_format = 25
integer, parameter err_probe_location = 26
integer, parameter err_probe_specified = 27
integer, parameter err_val_undefined = 28
integer, parameter err_stopfile_found = 29
integer, parameter err_unknown_bc = 30
integer, parameter err_no_bcspecified = 31
integer, parameter err_bcval_missing = 32
integer, parameter err_no_bcswitch = 33
integer, parameter err_val_bcswitch = 34
integer, parameter err_patch_range = 35
integer, parameter err_bc_varname = 36
integer, parameter err_val_bcval = 37
integer, parameter err_tbc_noninit = 38
integer, parameter err_bcval_extra = 39
integer, parameter err_time_grid = 40
integer, parameter err_time_solution = 41
integer, parameter err_time_global = 42
integer, parameter err_dtime_negative = 43
integer, parameter err_diter_negative = 44
integer, parameter err_steady = 45
integer, parameter err_mpi_trouble = 50
integer, parameter err_no_procmap = 51
integer, parameter err_no_procmatch = 52
integer, parameter err_patch_offset = 53
integer, parameter err_proc_mismatch = 54
integer, parameter err_grid_level = 60
integer, parameter err_grad_index = 65
integer, parameter err_facevec_sum = 70
integer, parameter err_volume_size = 71
integer, parameter err_face_split = 72
integer, parameter err_face_inverted = 73
integer, parameter err_option_type = 80
integer, parameter err_merge_sorted = 90
integer, parameter err_binary_search = 91
integer, parameter err_grad_mismatch = 100
integer, parameter err_negative_posdef = 200
integer, parameter err_invalid_value = 201
integer, parameter err_sec_read_twice = 240
integer, parameter err_mp_allornone = 250
integer, parameter err_missing_value = 260
integer, parameter err_unknown_viscmodel = 300
integer, parameter err_rk_scheme_invalid = 301
integer, parameter err_rand_seed_type_invalid = 400
integer, parameter err_region_range = 500
integer, parameter err_patch_2align = 501
integer, parameter err_patch_noalign = 502
integer, parameter err_patch_nosource = 503
integer, parameter err_patch_dimens = 504
integer, parameter err_patch_notcovered = 505
integer, parameter err_wrong_regionface = 506
integer, parameter err_patch_overlap = 507
integer, parameter err_patch_overspec = 508
integer, parameter err_grid_dimensions = 509
integer, parameter err_grid_dumcells = 510
integer, parameter err_srcregion_off = 511
integer, parameter err_number_cells = 512
integer, parameter err_region_number = 513
integer, parameter err_patch_number = 514
integer, parameter err_volume_edges = 900
integer, parameter err_volume_corners = 901
integer, parameter limit_infinite_loop = 1E6
integer, parameter err_vertex_number = 1000
integer, parameter err_nbfaces_wrong = 1001
integer, parameter err_patch_numbering = 1002
integer, parameter err_cell_type = 1003
integer, parameter err_hashtable = 1004
integer, parameter err_nfaces_wrong = 1005
integer, parameter err_nedges_estimate = 1006
integer, parameter err_nfaces_estimate = 1007
integer, parameter err_ncells_wrong = 1008
integer, parameter err_volume_diff = 1009
integer, parameter err_volume_negative = 1010
integer, parameter err_facesum = 1011
integer, parameter err_nbvert_estimate = 1012
integer, parameter err_nbvert_extrema = 1013
integer, parameter err_bface_list_extrema = 1014
integer, parameter err_facelist_invalid = 1015
integer, parameter err_dimens_invalid = 1016
integer, parameter err_movepatch_bc_invalid = 1017
integer, parameter err_nedges_wrong = 1018
integer, parameter err_cell_kind_check = 1019
integer, parameter err_face_nvert_invalid = 1020
integer, parameter err_patch_renumflag = 1021
integer, parameter err_bvert_list_invalid = 1022
integer, parameter err_edgelist_invalid = 1023
integer, parameter err_svert_list_invalid = 1024
integer, parameter err_movepatch_bc_notset = 1025
integer, parameter err_ncells_special_max = 1026
integer, parameter err_nfaces_special_max = 1027
integer, parameter err_c2flist_invalid = 1028
integer, parameter err_face_kind = 1029
integer, parameter err_bfacemembs_invalid = 1030
integer, parameter err_cellgrad_unavailable = 1031
integer, parameter err_bf2bg_inconsistent = 1032
integer, parameter err_c2cskey_inconsistent = 1033
integer, parameter err_distrib_invalid = 1034
integer, parameter err_bcdata_value_invalid = 1035
integer, parameter err_indmfmixt_invalid = 1036
integer, parameter err_denumber_list = 1037
integer, parameter err_proc2reg_mapping = 1038
integer, parameter err_optional_missing = 1039
integer, parameter err_nvert_estimate = 1040
integer, parameter err_nfacescut_invalid = 1041
integer, parameter err_cell_not_found = 1042
integer, parameter err_vertex_not_found = 1043
integer, parameter err_nborders_invalid = 1044
integer, parameter err_region_ids_invalid = 1045
integer, parameter err_cell_kind_invalid = 1046
integer, parameter err_cell_type_invalid = 1047
integer, parameter err_vertex_kind_invalid = 1048
integer, parameter err_partition_invalid = 1049
integer, parameter err_datadim_mismatch = 1050
integer, parameter err_bufferdim_mismatch = 1051
integer, parameter err_nregions_mismatch = 1052
integer, parameter err_nprocs_mismatch = 1053
integer, parameter err_num_bc_virtual = 1054
integer, parameter err_nvertshared_mismatch = 1055
integer, parameter err_lubound_mismatch = 1056
integer, parameter err_allocate_adaptive = 1057
integer, parameter err_reconst_invalid = 1058
integer, parameter err_discr_invalid = 1059
integer, parameter err_order_invalid = 1060
integer, parameter err_solver_type_invalid = 1061
integer, parameter err_bf2csorted_invalid = 1062
integer, parameter err_constr_invalid = 1063
integer, parameter err_gasmodel_invalid = 1064
integer, parameter err_gasmodel_discr_mismatch = 1065
integer, parameter err_face_normal_invalid = 1066
integer, parameter err_tolerict_invalid = 1067
integer, parameter err_stencildimens_invalid = 1068
integer, parameter err_stencilmember_invalid = 1069
integer, parameter err_bc_invalid = 1070
integer, parameter err_patch_bc_inconsistent = 1071
integer, parameter err_region_id_invalid = 1072
integer, parameter err_flatflag_inconsistent = 1073
integer, parameter err_vertex_match_failed = 1074
integer, parameter err_border_index_invalid = 1075
integer, parameter err_region_id_not_found = 1076
integer, parameter err_patch_not_flat = 1077
integer, parameter err_patch_not_aligned = 1078
integer, parameter err_virtualcells_notdb2 = 1079
integer, parameter err_bcvar_value_invalid = 1080
integer, parameter err_invalid_marker = 1100
integer, parameter err_invalid_ncells = 1101
integer, parameter err_invalid_nvars = 1102
integer, parameter err_oles_stencil = 1200
integer, parameter err_oles_flowmodel = 1201
integer, parameter err_ndimens_invalid = 1400
integer, parameter err_nzones_invalid = 1401
integer, parameter err_facetype_invalid = 1402
integer, parameter err_c2vlist_invalid = 1403
integer, parameter err_face_orient = 1404
integer, parameter err_string_invalid = 1405
integer, parameter err_ntype_invalid = 1406
integer, parameter err_ndp_invalid = 1407
integer, parameter err_lapack_output = 1500
integer, parameter err_dcuhre_output = 1510
integer, parameter err_tecplot_output = 1520
integer, parameter err_tecplot_filecntr = 1521
integer, parameter err_petsc_output = 1530
integer, parameter err_mpi_output = 1540
integer, parameter err_mpi_tagmax = 1541
integer, parameter err_infinite_loop = 1900
integer, parameter err_prec_range = 1901
integer, parameter err_cv_state_invalid = 1902
integer, parameter err_filedest_invalid = 1903
integer, parameter err_post_output_format_invalid = 1904
integer, parameter err_post_nservers_invalid = 1905
integer, parameter err_exceed_dimens = 1906
integer, parameter err_string_read = 1907
integer, parameter err_turb_module = 2001
integer, parameter err_plag_module = 3001
integer, parameter err_peul_module = 4001
integer, parameter err_inrt_module = 5001
integer, parameter err_spec_module = 6001
integer, parameter err_spec_ntypes = 6002
integer, parameter err_spec_maxeqn = 6003
integer, parameter err_spec_props_invalid = 6004
integer, parameter err_spec_nspec_invalid = 6005
integer, parameter err_spec_source_type_invalid = 6006
Detailed Description
Definition at line 39 of file ModError.F90.
Member Function/Subroutine Documentation
subroutine deregisterfunction (type(t_global), pointer global)
Definition at line 469 of file ModError.F90.
Referenced by afterupdatemp(), allocatememorywork(), prep_modbcdistribution::bcdistributionfiles(), prep_modbcdistribution::bcfarfdistrib(), prep_modbcdistribution::bcinflowtotangdistrib(), prep_modbcdistribution::bcinflowveldistrib(), prep_modbcdistribution::bcinjectdistrib(), prep_modbcdistribution::bcnoslipdistrib(), prep_modbcdistribution::bcoutflowdistrib(), prep_modbcdistribution::bcslipwalldistrib(), buildfilenamebasic(), modbuildfilenames::buildfilenamebasic(), buildfilenameplain(), modbuildfilenames::buildfilenameplain(), modbuildfilenames::buildfilenameplainsteady(), modbuildfilenames::buildfilenameplainunsteady(), buildfilenamesteady(), modbuildfilenames::buildfilenamesteady(), buildfilenameunsteady(), modbuildfilenames::buildfilenameunsteady(), modbuildfilenames::buildregionidstring(), cellgradientsmp(), checkbcvalidity(), convectivefluxes(), convectivefluxesmp(), convertflo2flumesh(), convertflo2flupatch(), correctnedges(), countinteractingpatches(), descalegridspeeds(), explicitmultistage(), fluid_posthdfoutput(), fluid_prehdfoutput(), function(), genxinitsolution(), genxstatnaming(), genxwriterocinout(), genxwritesolution(), getbndverttype(), getgrid(), modstatsroutines::getstatistics(), globalcommunicationmp(), initcommunicationmp(), initializeflowfield(), initinputvalues(), modstatsroutines::initstatistics(), inrt_allocateauxillary(), inrt_augmentconsources(), inrt_augmentdissources(), inrt_burnstatusupdate(), inrt_calcburning(), inrt_calcdrag(), inrt_calcheattransfernonburn(), inrt_calcscouring(), inrt_checkuserinput(), inrt_computemaxedges(), inrt_defineboilingregulation(), inrt_defineburning(), inrt_definedrag(), inrt_defineheattransfernonburn(), inrt_definescouring(), inrt_determinetokens(), inrt_finishmomentumedge(), inrt_initialize(), inrt_printmaterialinput(), inrt_printuserinput(), inrt_readboilingregulation(), inrt_readburning(), inrt_readdefaultsection(), inrt_readdrag(), inrt_readheattransfernonburn(), inrt_readinputfile(), inrt_readmaterialinput(), inrt_readscouring(), inrt_setactiveness(), inrt_setmaterial(), inrt_setparticletemp(), inrt_setpermission(), inrt_sourceterms(), inrt_twodimaverage(), inrt_userinput(), inrt_vaporenergyconversion(), integratesourcetermsmp(), mixtureproperties(), numericaldissipation(), numericaldissipationmp(), peri_allocatememory(), peri_checkparaminput(), peri_cnlforceterm(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_cocprslowterms(), peri_copgradupdate(), peri_derivedinputvalues(), peri_initinputvalues(), peri_initsolution(), peri_printuserinput(), peri_readinputfile(), peri_readperisection(), peri_rflu_deallocatememory(), peri_solutionupdate(), peri_sourceterms(), peri_userinput(), peul_allocatedatabuffers(), peul_allocatememory(), peul_bcondinflow(), peul_bcondinjection(), peul_bcondoutflow(), peul_bcondslipwall(), peul_bcondsymmetry(), peul_boundaryconditionsrecv(), peul_boundaryconditionssend(), peul_boundaryconditionsset(), peul_centraldissipation(), peul_centralflux(), peul_centralfluxpatch(), peul_clearsendrequests(), peul_convectivefluxes(), peul_correctcorneredgecells(), peul_derivedinputvalues(), peul_enforcepositivity(), peul_exchangecorneredgecells(), peul_exchangedummyconf(), peul_initgenxinterface(), peul_initinputvalues(), peul_initsolution(), peul_printuserinput(), peul_readbcfarfsection(), peul_readbcinflowsection(), peul_readbcinjectsection(), peul_readbcinputfile(), peul_readconpartptypesection(), peul_readconpartsection(), peul_readinputfile(), peul_readsolution(), peul_readsolutionregion(), peul_receivecorneredgecells(), peul_receivedummyvals(), peul_residualsmoothing(), peul_residualsmoothingcoeffs(), peul_rocflo_post(), peul_sendcorneredgecells(), peul_senddummyconf(), peul_setcorneredgecells(), peul_sourceeqeul(), peul_sourceterms(), peul_spectralradii(), peul_userinput(), peul_writesolution(), plag_allocatedatabuffers(), plag_allocatememory(), plag_allocatememorypost(), plag_allocatememorytile(), plag_appenddatafrombuffers(), plag_binsortnozzleinlet(), plag_binsortspatialdist(), plag_boundaryconditionsset(), plag_bufferdatarecv(), plag_bufferdatasend(), plag_buffersizerecv(), plag_buffersizesend(), plag_calcbreakup(), plag_calcderivedvariables(), plag_modeulerian::plag_calceulerianfield(), plag_calcfacecentroids(), plag_moddimensions::plag_calcnpclsglobal(), plag_calcrhsposition(), plag_cecellsallocatedata(), plag_cecellsclearrequestsdata(), plag_cecellsclearrequestssize(), plag_cecellsdeallocatedata(), plag_cecellsexchange(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_cecellsgetbuffersize(), plag_cecellsloaddatawrapper(), plag_cecellsrecvdata(), plag_cecellsrecvsize(), plag_cecellssenddata(), plag_cecellssendrecvwrapper(), plag_cecellssendsize(), plag_cecellswrapper(), plag_modcheckvars::plag_checkpositivity(), plag_checkuserinput(), plag_modcheckvars::plag_checkvalidity(), plag_cleardatasendrequests(), plag_clearsizesendrequests(), plag_modsurfstats::plag_closesurfstats(), plag_modreallocatememory::plag_copydimensions(), plag_copyfacevectors(), plag_modreallocatememory::plag_copymemory(), plag_corncellsloaddata(), plag_corncellsloadsendbuff(), plag_modeulerian::plag_createeulerianfield(), plag_modstats::plag_createstat(), plag_modsurfstats::plag_createsurfstats(), plag_modsurfstats::plag_createsurfstatskernel(), plag_deallocatedatabuffers(), plag_deallocatememorypost(), plag_modreallocatememory::plag_decidereallocmem(), plag_derivedinputvalues(), plag_modeulerian::plag_destroyeulerianfield(), plag_modstats::plag_destroystat(), plag_modsurfstats::plag_destroysurfstats(), plag_modsurfstats::plag_destroysurfstatskernel(), plag_moddatastruct::plag_dstr_buildcell2pcllist(), plag_moddatastruct::plag_dstr_copyparticle(), plag_moddatastruct::plag_dstr_copyparticlewrapper(), plag_moddatastruct::plag_dstr_createcell2pcllist(), plag_moddatastruct::plag_dstr_createpcllistcsr(), plag_moddatastruct::plag_dstr_destroycell2pcllist(), plag_moddatastruct::plag_dstr_destroypcllistcsr(), plag_moddatastruct::plag_dstr_mergeparticlewrapper(), plag_moddatastruct::plag_dstr_recreatecell2pcllist(), plag_edgecellsloaddata(), plag_edgecellsloadsendbuff(), plag_modinjection::plag_ejectparticle(), plag_modsurfstats::plag_gathersurfstats(), plag_getcellindices(), plag_getcellindicesoutflow(), plag_incelltest(), plag_incelltestrobust(), plag_modeulerian::plag_initeulerianfield(), plag_initgenxinterface(), plag_initinputvalues(), plag_initmemory(), plag_initpatchdata(), plag_initsolution(), plag_modstats::plag_initstat(), plag_modsurfstats::plag_initsurfstats(), plag_injcejectparticle(), plag_injcmakeparticle(), plag_injcsetinjection(), plag_modinjection::plag_injcsetpoolpos(), plag_injctilecalcrhs(), plag_injctileinitialize(), plag_modrkinit::plag_injctilerkinit(), plag_injctilerkupdate(), plag_injctileupdate(), plag_injctilezerorhs(), plag_inrt_allocmemtstep(), plag_inrt_deallocmemtstep(), plag_intrpmixtproperties(), plag_modinjection::plag_invokeconsrandejec(), plag_modinjection::plag_invokeejecmodel1(), plag_noncvupdate(), plag_modsurfstats::plag_nullifysurfstats(), plag_modsurfstats::plag_opensurfstatsascii(), plag_modsurfstats::plag_opensurfstatsbinary(), plag_patchbuffersendrecv(), plag_patchexchangeconf(), plag_patchgetbuffersize(), plag_patchloaddatabuffers(), plag_patchremovedataoutflow(), plag_patchupdate(), plag_patchupdatewrapper(), plag_moddimensions::plag_printdimensions(), plag_moddimensions::plag_printnpclsglobal(), plag_printuserinput(), plag_processeulerfield(), plag_readdispartinitsection(), plag_readdispartncontsection(), plag_readdispartsection(), plag_readinputfile(), plag_readpdffromfile(), plag_readsolution(), plag_readsolutionfilepost(), plag_readstatpost(), plag_modsurfstats::plag_readsurfstatsascii(), plag_modsurfstats::plag_readsurfstatsbinary(), plag_modsurfstats::plag_readsurfstatskernelascii(), plag_modsurfstats::plag_readsurfstatskernelbinary(), plag_modsurfstats::plag_readsurfstatswrapper(), plag_modreallocatememory::plag_reallocmem(), plag_modreallocatememory::plag_reallocmemwrapper(), plag_rflo_modstats::plag_rflo_clearreqstatbuff(), plag_rflo_clearsendrequests(), plag_rflo_modstats::plag_rflo_commstatbuffwrapper(), plag_rflo_modstats::plag_rflo_copystatbuff(), plag_rflo_modstats::plag_rflo_createstatbuff(), plag_rflo_findgridmapping(), plag_rflo_findsourcecell(), plag_rflo_modstats::plag_rflo_readstat(), plag_rflo_recvmetrics(), plag_rflo_modstats::plag_rflo_recvstatbuff(), plag_rflo_modstats::plag_rflo_recvstatbuffwrapper(), plag_rflo_sendmetrics(), plag_rflo_sendrecvmetrics(), plag_rflo_modstats::plag_rflo_sendstatbuffconf(), plag_rflo_modstats::plag_rflo_sendstatbuffwrapper(), plag_rflo_setmetrics(), plag_rflo_sourcecell(), plag_rflo_modstats::plag_rflo_writestat(), plag_rflu_allocmemsol(), plag_rflu_allocmemsoltile(), plag_rflu_allocmemtstep(), plag_rflu_allocmemtsteptile(), plag_rflu_modcomm::plag_rflu_clearrequest(), plag_rflu_modcomm::plag_rflu_clearrequestwrapper(), plag_rflu_modcomm::plag_rflu_commdriver(), plag_rflu_modfindcells::plag_rflu_computedisttot(), plag_rflu_modcomm::plag_rflu_copycounters(), plag_rflu_modcomm::plag_rflu_copydata(), plag_rflu_modcomm::plag_rflu_copydataint(), plag_rflu_modcomm::plag_rflu_copydatareal(), plag_rflu_correctmixtproperties(), plag_rflu_modcomm::plag_rflu_createbuffersrecv(), plag_rflu_modcomm::plag_rflu_createbufferssend(), plag_rflu_deallocmemsol(), plag_rflu_deallocmemsoltile(), plag_rflu_deallocmemtstep(), plag_rflu_deallocmemtsteptile(), plag_rflu_modcomm::plag_rflu_destroybuffersrecv(), plag_rflu_modcomm::plag_rflu_destroybufferssend(), plag_rflu_modfindcells::plag_rflu_findcellsbrute(), plag_rflu_modfindcells::plag_rflu_findcellsbrutekernel(), plag_rflu_modfindcells::plag_rflu_findcellsbrutemod(), plag_rflu_modfindcells::plag_rflu_findcellslohner(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), plag_rflu_modfindcells::plag_rflu_findcellstrajsafe(), plag_rflu_modcomm::plag_rflu_initrecvcounters(), plag_rflu_modcomm::plag_rflu_initsendcounters(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), plag_rflu_initsolserialwrapper(), plag_rflu_initsolutionrandom(), plag_rflu_initsolutionscratch(), plag_rflu_injctilecalcrhs(), plag_rflu_injectiondriver(), plag_rflu_modcomm::plag_rflu_isendcounters(), plag_rflu_modcomm::plag_rflu_isenddata(), plag_rflu_modcomm::plag_rflu_loadbufferssend(), plag_moddimensions::plag_rflu_readdimensions(), plag_rflu_readsolutionascii(), plag_rflu_readsolutionbinary(), plag_rflu_modcomm::plag_rflu_recvcounters(), plag_rflu_modcomm::plag_rflu_recvdata(), plag_rflu_modcomm::plag_rflu_totalnpclscomm(), plag_rflu_modcomm::plag_rflu_unloadbuffersrecv(), plag_rflu_update(), plag_moddimensions::plag_rflu_writedimensions(), plag_rflu_writesolutionascii(), plag_rflu_writesolutionbinary(), plag_rkinit(), plag_modrkinit::plag_rkinitgenericint(), plag_modrkinit::plag_rkinitgenericreal(), plag_modrkinit::plag_rkinitprimary(), plag_rkupdatewrapper(), plag_modsurfstats::plag_setbinindex(), plag_moddimensions::plag_setdimensions(), plag_moddimensions::plag_setmaxdimensions(), plag_setsizegenx(), plag_statmapping(), plag_update(), plag_userinput(), plag_wallbounce(), plag_writesolution(), plag_writestattecascii(), plag_modsurfstats::plag_writesurfstatsascii(), plag_modsurfstats::plag_writesurfstatsbinary(), plag_modsurfstats::plag_writesurfstatskernelascii(), plag_modsurfstats::plag_writesurfstatskernelbinary(), plag_modsurfstats::plag_writesurfstatswrapper(), plag_writetecplotascii(), plag_zerorhs(), printpostinput(), printprepinput(), printtofluinput(), prep_modbcdistribution::profinflowvttaylorcyl(), radi_allocatememory(), radi_calcefftemp(), radi_diffradflux(), radi_diffradfluxpatch(), radi_diffradintens(), radi_emsinit(), radi_extinctioncoef(), radi_flimconvectivefluxes(), radi_flimdiffflux(), radi_flimdifffluxpatch(), radi_flimemsinit(), radi_flimemsupdate(), radi_flimnumericaldissipation(), radi_flimrkinit(), radi_flimrkupdate(), radi_flimsourceterms(), radi_flimzerodummycells(), radi_floflimbconddiffuse(), radi_floflimbcondinjection(), radi_floflimbcondsymmetry(), radi_floflimbcondzerograd(), radi_floflimcentflux(), radi_floflimcentfluxpatch(), radi_floflimcentraldissipation(), radi_floflimcorrcornedgecells(), radi_floflimexchangedummyconf(), radi_floflimexchcornedgecells(), radi_floflimrecvcornedgecells(), radi_floflimrecvdummyvals(), radi_floflimsendcornedgecells(), radi_floflimsenddummyconf(), radi_floflimsetcornedgecells(), radi_fluxlimiter(), radi_initgenxinterface(), radi_mixtsourcetermsflim(), radi_peulsourcetermsflim(), radi_plagsourcetermsflim(), radi_rflo_flimallocdatabuffers(), radi_rflo_flimbndconditionsrecv(), radi_rflo_flimbndconditionssend(), radi_rflo_flimbndconditionsset(), radi_rflo_flimclearsendrequests(), radi_rflo_flimressmoothing(), radi_rflo_flimressmoothingcoeff(), radi_rflo_flimspectralradii(), radi_rflo_readsolution(), radi_rflo_writesolution(), radi_rkinit(), radi_solutionupdate(), radi_sourceterms(), randinitgenxinterface(), readaccelerationsection(), readbcinputfile(), readflowsection(), readforcessection(), readformatssection(), readinitflowsection(), readinputfile(), readmixturesection(), readmultigridsection(), readnumericssection(), prep_modbcdistribution::readpatchsection(), readpostsection(), readprepsection(), readprobesection(), readrandomsection(), readreferencesection(), readrocketsection(), readstatisticsection(), readthrustsection(), readtimestepsection(), readtimezoomingsection(), readtransformsection(), readviscositysection(), rflo_allocatedatabuffers(), rflo_allocatememory(), rflo_arclengthbounds(), rflo_modgridmetrics::rflo_arclengthpatch(), rflo_modboundaryconditions::rflo_bcondfarfield(), rflo_modboundaryconditions::rflo_bcondinflow(), rflo_modboundaryconditions::rflo_bcondinjection(), rflo_modboundaryconditions::rflo_bcondinjectionapn(), rflo_modboundaryconditions::rflo_bcondinjectioninit(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflow(), rflo_modboundaryconditions::rflo_bcondrotatperiod(), rflo_modboundaryconditions::rflo_bcondslipwall(), rflo_modboundaryconditions::rflo_bcondsymmetry(), rflo_modgridregionshape::rflo_blockskewedcell(), rflo_modboundaryconditions::rflo_boundaryconditionsrecv(), rflo_modboundaryconditions::rflo_boundaryconditionssend(), rflo_modboundaryconditions::rflo_boundaryconditionsset(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2eavgcoeffsdegec(), rflo_c2favgcoeffs(), rflo_c2favgcoeffsdegec(), rflo_c2favgcoeffsdummy(), rflo_c2favgcoeffsdummyconn(), rflo_c2favgcoeffsdummyphys(), rflo_c2favgcoeffspatch(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_calcforces(), rflo_calcgradconnbc(), rflo_calcgraddummy(), rflo_calcgraddummyconn(), rflo_calcgraddummyphys(), rflo_calcgraddummysymm(), rflo_calcgradfaces(), rflo_calcgradphysbc(), rflo_calcgradvector(), rflo_modgridmetrics::rflo_calcgridmetrics(), rflo_calcgridspeeds(), rflo_calcmassflow(), rflo_calcthrust(), rflo_calctotalmass(), rflo_centraldissipation(), rflo_centralflux(), rflo_centralfluxpatch(), rflo_changeinteriorgrid(), rflo_checkbcinput(), rflo_checkderiveduserinput(), rflo_checkmetrics(), rflo_checkminimumcells(), rflo_checkregionfaces(), rflo_checkuserinput(), rflo_checkvalidity(), rflo_clearsendrequests(), rflo_modrestartinfo::rflo_closerestartinfo(), rflo_modforcesmoments::rflo_computeintegralforcemomco(), rflo_computeintegralvalues(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_copyboundarydata(), rflo_copyedgefacenorm(), rflo_copyedgefaceparal(), rflo_copygeometrydummy(), rflo_copymatrixcorners(), rflo_copymatrixedges(), rflo_copymatrixpatches(), rflo_copytopologylevels(), rflo_copyvectorcorners(), rflo_copyvectoredges(), rflo_copyvectorpatches(), rflo_correctcorneredgecells(), rflo_derivedinputvalues(), rflo_domemoryallocation(), rflo_dualmultigrid(), rflo_dualtimestepping(), rflo_dualtstinit(), rflo_dualtstpredict(), rflo_dualtstshift(), rflo_dualtststerm(), rflo_edgedeformation(), rflo_edgedeformationstraight(), rflo_modelliptsmoothing::rflo_elliptgridgauss2d(), rflo_modelliptsmoothing::rflo_elliptgridgauss3d(), rflo_modelliptsmoothing::rflo_elliptgridjac2d(), rflo_modelliptsmoothing::rflo_elliptgridjac3d(), rflo_modelliptsmoothing::rflo_elliptgridpatch(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modelliptsmoothing::rflo_elliptgridsmooregion(), rflo_modelliptsmoothing::rflo_elliptgridsor2d(), rflo_modelliptsmoothing::rflo_elliptgridsor3d(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs2d(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs3d(), rflo_endflowsolver(), rflo_exchangecorneredgecells(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangedummyconf(), rflo_exchangedummyint(), rflo_exchangedummyireg(), rflo_exchangegeometry(), rflo_exchangegeometrycopy(), rflo_exchangegeometrylevels(), rflo_exchangegeometryprepare(), rflo_exchangegeometryrecv(), rflo_exchangegeometrysend(), rflo_extrapintcellscal(), rflo_extrapintcellvec(), rflo_extrapolategeometry(), rflo_moddegeneratecornedge::rflo_finddegeneratcell(), rflo_modgridregionshape::rflo_findfunkyblocks(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_findsourcecell(), rflo_findsourcecellinvert(), rflo_findsourcepatches(), rflo_findsourceregions(), rflo_findthrustpatches(), rflo_flowsolver(), rflo_flowsolverdummy(), rflo_generatecoarsegrids(), rflo_getboundaryvalues(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getdeformation(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getedgecellsindices(), rflo_getflowsolution(), rflo_getgeometry(), rflo_getnodeoffset(), rflo_getpatchindices(), rflo_getpatchindicesnodes(), rflo_getuserinput(), rflo_modgridcontrolmap::rflo_gridcontrolfunc2d(), rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad2d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad3d(), rflo_modgridcontrolmap::rflo_gridcontrolmap2d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_modgridregionshape::rflo_gridflatpatch(), rflo_modgridcontrolmap::rflo_gridphysgrad2d(), rflo_modgridcontrolmap::rflo_gridphysgrad3d(), rflo_modgridmetrics::rflo_gridqualityglobal(), rflo_gridremesh(), rflo_initavgcoeffs(), rflo_initflowsolver(), rflo_initgenxinterface(), rflo_initgenxinterfaceprep(), rflo_initgridprocedures(), rflo_initinputvalues(), rflo_modinitialization::rflo_initnoncvsolution(), rflo_modpatchaerocoeffs::rflo_initpatchaerocoeffs(), rflo_interpoltofinerlevel(), rflo_modlaplacesmoothing::rflo_laplacegridjump(), rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_modlaplacesmoothing::rflo_laplacegridortho1(), rflo_modlaplacesmoothing::rflo_laplacegridortho2(), rflo_laplacegridpatch(), rflo_modlaplacesmoothing::rflo_laplacegridpatch(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_laplacegridsolve(), rflo_modlaplacesmoothing::rflo_laplacegridsolve(), rflo_limiterreference(), rflo_mapregionsprocessors(), rflo_moddegeneratecornedge::rflo_markdegeneratvert(), rflo_modmovegridelliptglo::rflo_mgelliptbnddeformation(), rflo_modmovegridelliptfra::rflo_mgelliptboundaries(), rflo_modmovegridelliptfra::rflo_mgelliptedgesfra(), rflo_modmovegridelliptglo::rflo_mgelliptedgesglo(), rflo_modmovegridelliptfra::rflo_mgelliptinterfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptinterfacesglo(), rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptsurfacesglo(), rflo_modmovegridframe::rflo_mgframebnddeformation(), rflo_modmovegridframe::rflo_mgframebnddeformation0(), rflo_modmovegridframe::rflo_mgframebroadcast(), rflo_modmovegridframe::rflo_mgframecornpoints(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframeedges(), rflo_modmovegridframe::rflo_mgframeedgeso(), rflo_modmovegridframe::rflo_mgframeinterfaces(), rflo_modmovegridframe::rflo_mgframemovecorners(), rflo_modmovegridframe::rflo_mgframeorthoshift(), rflo_modmovegridframe::rflo_mgframerestoreexternal(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_modmovegridframe::rflo_mgframesurfaces(), rflo_minimumtimestep(), rflo_movegridblocks(), rflo_modmovegridutil::rflo_movegridcurvedpatch(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_movegridinterfaces(), rflo_modmovegridutil::rflo_movegridqflatpatch(), rflo_movegridsurfaces(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_multigrid(), rflo_newgrid(), rflo_openconverfile(), rflo_modforcesmoments::rflo_openforcemomcofile(), rflo_openprobefile(), rflo_modrestartinfo::rflo_openrestartinfo(), rflo_openthrustfile(), rflo_printuserinput(), rflo_randominit(), rflo_readbcfarfsection(), rflo_readbcfromfile(), rflo_readbcinflowtotangsection(), rflo_readbcinflowvelsection(), rflo_readbcinjectapnsection(), rflo_readbcinjectmratesection(), rflo_readbcinputfile(), rflo_readbcnoslipsection(), rflo_readbcoutflowsection(), rflo_readbcslipwallsection(), rflo_readdatafileint(), rflo_readdatafilereal(), rflo_readgrid(), rflo_readgridregion(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffs(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffsreg(), rflo_readrandomstate(), rflo_readregionmapsection(), rflo_readregiontopology(), rflo_modrestartinfo::rflo_readrestartinfo(), rflo_readsolution(), rflo_readsolutionregion(), rflo_readstat(), rflo_readstatregion(), rflo_readtbcinputfile(), rflo_readtbcsection(), rflo_receivecorneredgecells(), rflo_receivedummyvals(), rflo_residualnorm(), rflo_residualsmoothing(), rflo_residualsmoothingcoeffs(), rflo_roedissipfirst(), rflo_roedissipsecond(), rflo_roefluxfirst(), rflo_roefluxpatch(), rflo_roefluxsecond(), rflo_sendboundaryvalues(), rflo_sendboundaryvaluesalpha(), rflo_sendcorneredgecells(), rflo_senddummyconf(), rflo_senddummyint(), rflo_senddummyireg(), rflo_setcorneredgecells(), rflo_sourcecell(), rflo_modstatsboundaryconditions::rflo_statbcondcopy(), rflo_modstatsboundaryconditions::rflo_statbcondextrap(), rflo_modstatsboundaryconditions::rflo_statbcondnegate(), rflo_modstatsboundaryconditions::rflo_statboundaryconditionsset(), rflo_timestepinviscid(), rflo_timestepping(), rflo_timestepviscous(), rflo_updateinbuffgm(), rflo_userinput(), rflo_viscousflux(), rflo_viscousfluxpatch(), rflo_modvolmeshsmoothing::rflo_vmsaveragevertices(), rflo_modvolmeshsmoothing::rflo_vmsinit(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rflo_modvolmeshsmoothing::rflo_vmslaplaceperturb(), rflo_modvolmeshsmoothing::rflo_vmslaplaceprocedure(), rflo_modvolmeshsmoothing::rflo_vmsprojectvertices(), rflo_modvolmeshsmoothing::rflo_vmsrestorebounddeform(), rflo_writedatafileint(), rflo_writedatafilereal(), rflo_moddegeneratecornedge::rflo_writedegeneratec(), rflo_writegrid(), rflo_writegridregion(), rflo_modforcesmoments::rflo_writeintegralforcemomco(), rflo_modpatchaerocoeffs::rflo_writepatchaerocoeffs(), rflo_modforcesmoments::rflo_writepatchcoeffsinfo(), rflo_writerandomstate(), rflo_writeregiontopology(), rflo_modrestartinfo::rflo_writerestartinfo(), rflo_writesolution(), rflo_writesolutionregion(), rflo_writestat(), rflo_zerodummycells(), rflu_moddimensionality::rflu_123d_checkgeometrykernel(), rflu_moddimensionality::rflu_123d_checkgeometrywrapper(), rflu_moddimensionality::rflu_123d_checktopology(), rflu_modstencilsutils::rflu_addbfaces(), rflu_modstencilsutils::rflu_addcelllayer(), rflu_modstencilsutils::rflu_addcelllayer_1d(), rflu_modstencilsutils::rflu_addcelllayer_1d_g(), rflu_modstencilsutils::rflu_addfacevertneighbs(), rflu_modoles::rflu_allocatedcuhrearrays(), rflu_allocatedcuhrearrays(), rflu_allocatememory(), rflu_modallocatememory::rflu_allocatememorygspeeds(), rflu_modallocatememory::rflu_allocatememorysol(), rflu_modallocatememory::rflu_allocatememorysolcv(), rflu_modallocatememory::rflu_allocatememorysoldv(), rflu_modallocatememory::rflu_allocatememorysolgv(), rflu_modallocatememory::rflu_allocatememorysoltv(), rflu_allocatememorytbc(), rflu_modallocatememory::rflu_allocatememorytstep(), rflu_modallocatememory::rflu_allocatememorytstep_c(), rflu_modallocatememory::rflu_allocatememorytstep_i(), rflu_allocatememoryvert(), rflu_allocatememorywrapper(), rflu_allocmemsolwrapper(), rflu_allocmemvertwrapper(), rflu_modregionmapping::rflu_applyregionmapping(), rflu_modausmflux::rflu_ausm_computeflux(), rflu_modausmflux::rflu_ausm_computeflux1(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modbilinearpatch::rflu_blin_computenormal(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modbilinearpatch::rflu_blin_findclosestpoint(), rflu_modfacelist::rflu_buildavface2borderlist(), rflu_modfacelist::rflu_buildavface2patchlist(), rflu_modboundlists::rflu_buildbcellmlist(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilsbfaces::rflu_buildbf2cstencil_1d(), rflu_modstencilsbfaces::rflu_buildbf2cstencilwrapper(), rflu_modbfacegradaccesslist::rflu_buildbfacegradaccesslist(), rflu_modboundlists::rflu_buildbfaceloclists(), rflu_modboundlists::rflu_buildbfacesortlists(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modboundlists::rflu_buildbvertexmlist(), rflu_modgeometry::rflu_buildbvertexnormals(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil_1d(), rflu_modstencilscells::rflu_buildc2cstencil_1d_g(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modstencilscells::rflu_buildc2cstencilbasic_1d(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_modtopologyutils::rflu_buildcellvertlist(), rflu_modtopologyutils::rflu_buildconnvertlist(), rflu_builddatastruct(), rflu_modedgelist::rflu_buildedge2celllist(), rflu_modedgelist::rflu_buildedgelist(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil_1d(), rflu_modstencilsfaces::rflu_buildf2cstencilwrapper(), rflu_modfacelist::rflu_buildfacelist(), rflu_modtopologyutils::rflu_buildfacevertlist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modstencilscells::rflu_buildlistcc2cstencil(), rflu_modstencilsfaces::rflu_buildlistcf2cstencil(), rflu_modcellmapping::rflu_buildloc2globcellmapping(), rflu_modpatchutils::rflu_buildpatchneighbormaps(), rflu_modplottingvars::rflu_buildplottingvarmaps(), rflu_modplottingvars::rflu_buildplottingvarnames(), rflu_modregionmapping::rflu_buildregionmappingsimple(), rflu_modsplittree::rflu_buildsplittree(), rflu_modoles::rflu_buildstencilsoles(), rflu_modstencilsvert::rflu_buildstencilvert2cell(), rflu_modoles::rflu_buildsymmetrymapsoles(), rflu_modvertexlists::rflu_buildvert2celllist(), rflu_modtopologyutils::rflu_buildvertcellnghblist(), rflu_modboundxvutils::rflu_bxv_compenergypatch(), rflu_modboundxvutils::rflu_bxv_compmomenergypatch(), rflu_modboundxvutils::rflu_bxv_computevarscv(), rflu_modboundconvertcv::rflu_bxv_convertcvcons2prim(), rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_modboundxvutils::rflu_bxv_createvarscv(), rflu_modboundxvutils::rflu_bxv_createvarsdv(), rflu_modboundxvutils::rflu_bxv_createvarststep(), rflu_modboundxvutils::rflu_bxv_destroyvarscv(), rflu_modboundxvutils::rflu_bxv_destroyvarsdv(), rflu_modboundxvutils::rflu_bxv_destroyvarststep(), rflu_modboundxvutils::rflu_bxv_initvars(), rflu_modboundxvutils::rflu_bxv_nullifyvarscv(), rflu_modboundxvutils::rflu_bxv_nullifyvarsdv(), rflu_modboundxvutils::rflu_bxv_nullifyvarststep(), rflu_modboundxvutils::rflu_bxv_readvarsascii(), rflu_modboundxvutils::rflu_bxv_readvarsbinary(), rflu_modboundxvutils::rflu_bxv_readvarswrapper(), rflu_modboundxvutils::rflu_bxv_setdependentvars(), rflu_modboundxvutils::rflu_bxv_setdependentvarspatch(), rflu_modboundxvutils::rflu_bxv_writevarsascii(), rflu_modboundxvutils::rflu_bxv_writevarsbinary(), rflu_modboundxvutils::rflu_bxv_writevarswrapper(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_checkcouplinginput(), rflu_checkderiveduserinput(), rflu_modcentaur::rflu_checkgridcentaur(), rflu_modgambit::rflu_checkgridgambit(), rflu_checkgridspeeds(), rflu_modpatchutils::rflu_checkpatchbcconsistency(), rflu_checkpositivity(), rflu_checkpositivity_gl(), rflu_checkpositivitywrapper(), rflu_modregionmapping::rflu_checkregionmapping(), rflu_checkuserinput(), rflu_checkvalidity(), rflu_checkvalidity_gl(), rflu_checkvaliditywrapper(), rflu_modpatchcoeffs::rflu_closepatchcoeffs(), rflu_closepostinfo(), rflu_modprobes::rflu_closeprobefiles(), rflu_modregionmapping::rflu_closeregionmappingfile(), rflu_closerestartinfo(), rflu_modcoloring::rflu_col_buildcoloringp(), rflu_modcoloring::rflu_col_buildcolorings(), rflu_modcoloring::rflu_col_createcoloring(), rflu_modcoloring::rflu_col_destroycoloring(), rflu_modcoloring::rflu_col_readcoloring(), rflu_modcoloring::rflu_col_recreatecelllist(), rflu_modcoloring::rflu_col_writecoloring(), rflu_modcommlists::rflu_comm_buildcommlists(), rflu_modcommlists::rflu_comm_buildcommlistscells(), rflu_modcommlists::rflu_comm_buildcommlistsvert(), rflu_modcommlists::rflu_comm_checkcountborders(), rflu_modcommlists::rflu_comm_countborders(), rflu_modcommlists::rflu_comm_countbordersserial(), rflu_modcommlists::rflu_comm_createbordercntr(), rflu_modcommlists::rflu_comm_createborders(), rflu_modcommlists::rflu_comm_createcommlists(), rflu_modcommlists::rflu_comm_destroybordercntr(), rflu_modcommlists::rflu_comm_destroyborders(), rflu_modcommlists::rflu_comm_destroycommlists(), rflu_modcommlists::rflu_comm_getproclocregids(), rflu_modcommlists::rflu_comm_readcommlists(), rflu_modcommlists::rflu_comm_writecommlists(), rflu_modgeometry::rflu_computeapproxcentroids(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationbfaces::rflu_computebfgradconstrwrapper(), rflu_computedcuhreinfo(), rflu_computeenerdissoles(), rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), rflu_modgeometry::rflu_computefacedist(), rflu_computefluxinv(), rflu_modoles::rflu_computegeometrictermsoles(), rflu_modforcesmoments::rflu_computeglobalforcesmoments(), rflu_moddifferentiationbfaces::rflu_computegradbfaces(), rflu_moddifferentiationbfaces::rflu_computegradbfaces_1d(), rflu_moddifferentiationbfaces::rflu_computegradbfaceswrapper(), rflu_moddifferentiationcells::rflu_computegradcells_1d(), rflu_moddifferentiationcells::rflu_computegradcells_2d(), rflu_moddifferentiationcells::rflu_computegradcells_3d(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationcells::rflu_computegradcellsfast_2d(), rflu_moddifferentiationcells::rflu_computegradcellsfast_3d(), rflu_moddifferentiationcells::rflu_computegradcellswrapper(), rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_moddifferentiationfaces::rflu_computegradfaces(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_moddifferentiationfaces::rflu_computegradfaceswrapper(), rflu_computegridspeeds(), rflu_computeintegral1oles(), rflu_computeintegral2oles(), rflu_computeintegral3oles(), rflu_computeintegral4oles(), rflu_computeintegral5oles(), rflu_computeintegrals1245oles(), rflu_computeintegralvalues(), rflu_modlimiters::rflu_computelimiterbarthjesp(), rflu_modlimiters::rflu_computelimitervenkat(), rflu_modgeometrytools::rflu_computelinecellxsectfast(), rflu_modgeometrytools::rflu_computelinecellxsectsafe(), rflu_modforcesmoments::rflu_computelocalforcesmoments(), rflu_modpatchutils::rflu_computepatchnormalsglobal(), rflu_modpatchutils::rflu_computepatchnormalslocal(), rflu_modplottingvars::rflu_computeplottingvarscore(), rflu_modplottingvars::rflu_computeplottingvarsdisc(), rflu_modplottingvars::rflu_computeplottingvarsgraderr(), rflu_modplottingvars::rflu_computeplottingvarsvort(), rflu_modplottingvars::rflu_computeplottingvarswrapper(), rflu_modweights::rflu_computestencilmoments2d1(), rflu_modweights::rflu_computestencilmoments3d1(), rflu_computestencilsize(), rflu_modstencilsutils::rflu_computestencilsize(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_computevertexvariables(), rflu_computeweightsoles(), rflu_modweights::rflu_computewtsbf2c(), rflu_modweights::rflu_computewtsbf2cwrapper(), rflu_modweights::rflu_computewtsc2c(), rflu_modweights::rflu_computewtsc2cwrapper(), rflu_modweights::rflu_computewtsf2c(), rflu_modweights::rflu_computewtsf2cwrapper(), rflu_modweights::rflu_computewtsx2c_1d(), rflu_modcentaur::rflu_convcentaur2rocflu(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_modconvertcv::rflu_convertcvcons2prim(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_convfluxoles(), rflu_modgambit::rflu_convgambit2rocflu(), rflu_modmesh3d::rflu_convmesh3d2rocflu(), rflu_modtetmesh::rflu_convrocflu2tetmesh(), rflu_modtetmesh::rflu_convtetmesh2rocflu(), rflu_modvgridns::rflu_convvgridns2rocflu(), rflu_modcopydata::rflu_copy_celldatap2s_r2d(), rflu_modcopydata::rflu_copy_celldatap2s_r3d(), rflu_modcopydata::rflu_copy_celldatas2p_i1d(), rflu_modcopydata::rflu_copy_celldatas2p_r2d(), rflu_modgatherdata::rflu_countgathereddata(), rflu_modplottingvars::rflu_countplottingvars(), rflu_modgeometry::rflu_createapproxcentroids(), rflu_modfacelist::rflu_createavface2borderlist(), rflu_modfacelist::rflu_createavface2patchlist(), rflu_modboundlists::rflu_createbcellmlist(), rflu_modstencilsbfaces::rflu_createbf2cstencil(), rflu_modstencilsbfaces::rflu_createbf2cstencil_1d(), rflu_modstencilsbfaces::rflu_createbf2cstencilwrapper(), rflu_modbfacegradaccesslist::rflu_createbfacegradaccesslist(), rflu_modboundlists::rflu_createbfaceloclists(), rflu_modboundlists::rflu_createbfacesortlists(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modboundlists::rflu_createbvertexmlist(), rflu_modstencilscells::rflu_createc2cstencil(), rflu_modstencilscells::rflu_createc2cstencil_1d(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modedgelist::rflu_createedge2celllist(), rflu_modedgelist::rflu_createedgelist(), rflu_modstencilsfaces::rflu_createf2cstencil(), rflu_modstencilsfaces::rflu_createf2cstencil_1d(), rflu_modstencilsfaces::rflu_createf2cstencilwrapper(), rflu_modgeometry::rflu_createfacedist(), rflu_modfacelist::rflu_createfacelist(), rflu_modforcesmoments::rflu_createforcesmoments(), rflu_modgatherdata::rflu_creategathereddata(), rflu_modgeometry::rflu_creategeometry(), rflu_modforcesmoments::rflu_createglobalthrustflags(), rflu_creategrid(), rflu_modhashtable::rflu_createhashtable(), rflu_modoles::rflu_createintegralsoles(), rflu_modlimiters::rflu_createlimiter(), rflu_modoctree::rflu_createoctree(), rflu_modpatchcoeffs::rflu_createpatchcoeffs(), rflu_modpatchutils::rflu_createpatchneighbormaps(), rflu_modplottingvars::rflu_createplottingvarmaps(), rflu_modplottingvars::rflu_createplottingvars(), rflu_modplottingvars::rflu_createplottingvarsvert(), rflu_modregionmapping::rflu_createregionmapping(), rflu_createregions(), rflu_modsplittree::rflu_createsplittree(), rflu_modoles::rflu_createstencilsweightsoles(), rflu_modstencilsvert::rflu_createstencilvert2cell(), rflu_modvertexlists::rflu_createvert2celllist(), rflu_modweights::rflu_createwtsbf2c(), rflu_modweights::rflu_createwtsbf2cwrapper(), rflu_modweights::rflu_createwtsc2c(), rflu_modweights::rflu_createwtsc2cwrapper(), rflu_modweights::rflu_createwtsf2c(), rflu_modweights::rflu_createwtsf2cwrapper(), rflu_modoles::rflu_deallocatedcuhrearrays(), rflu_deallocatedcuhrearrays(), rflu_deallocatememory(), rflu_moddeallocatememory::rflu_deallocatememorygspeeds(), rflu_moddeallocatememory::rflu_deallocatememorysol(), rflu_moddeallocatememory::rflu_deallocatememorysolcv(), rflu_moddeallocatememory::rflu_deallocatememorysoldv(), rflu_moddeallocatememory::rflu_deallocatememorysolgv(), rflu_moddeallocatememory::rflu_deallocatememorysoltv(), rflu_moddeallocatememory::rflu_deallocatememorytstep(), rflu_moddeallocatememory::rflu_deallocatememorytstep_c(), rflu_moddeallocatememory::rflu_deallocatememorytstep_i(), rflu_deallocatememoryvert(), rflu_deallocatememorywrapper(), rflu_deallocmemsolwrapper(), rflu_deallocmemvertwrapper(), rflu_decideneedbgradface(), rflu_decideprint(), rflu_modreadwritebcdatafile::rflu_decidereadwritebcdatafile(), rflu_decidewrite(), rflu_modprobes::rflu_decidewriteprobes(), rflu_modboundlists::rflu_denumberbfacelists(), rflu_modrenumberlist::rflu_denumberlist(), rflu_derivedinputvalues(), rflu_modgeometry::rflu_destroyapproxcentroids(), rflu_modfacelist::rflu_destroyavface2borderlist(), rflu_modfacelist::rflu_destroyavface2patchlist(), rflu_modboundlists::rflu_destroybcellmlist(), rflu_modstencilsbfaces::rflu_destroybf2cstencil(), rflu_modstencilsbfaces::rflu_destroybf2cstencil_1d(), rflu_modstencilsbfaces::rflu_destroybf2cstencilwrapper(), rflu_modbfacegradaccesslist::rflu_destroybfacegradaccesslist(), rflu_modboundlists::rflu_destroybfaceloclists(), rflu_modboundlists::rflu_destroybfacesortlists(), rflu_modboundlists::rflu_destroybvertexlists(), rflu_modboundlists::rflu_destroybvertexmlist(), rflu_modstencilscells::rflu_destroyc2cstencil(), rflu_modstencilscells::rflu_destroyc2cstencil_1d(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), rflu_modfacelist::rflu_destroycell2facelist(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modedgelist::rflu_destroyedge2celllist(), rflu_modedgelist::rflu_destroyedgelist(), rflu_modstencilsfaces::rflu_destroyf2cstencil(), rflu_modstencilsfaces::rflu_destroyf2cstencil_1d(), rflu_modstencilsfaces::rflu_destroyf2cstencilwrapper(), rflu_modgeometry::rflu_destroyfacedist(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modforcesmoments::rflu_destroyforcesmoments(), rflu_modgatherdata::rflu_destroygathereddata(), rflu_modgeometry::rflu_destroygeometry(), rflu_modforcesmoments::rflu_destroyglobalthrustflags(), rflu_destroygrid(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modlimiters::rflu_destroylimiter(), rflu_modstencilscells::rflu_destroylistcc2cstencil(), rflu_modstencilsfaces::rflu_destroylistcf2cstencil(), rflu_modoctree::rflu_destroyoctree(), rflu_modpatchcoeffs::rflu_destroypatchcoeffs(), rflu_modpatchutils::rflu_destroypatchneighbormaps(), rflu_modplottingvars::rflu_destroyplottingvarmaps(), rflu_modplottingvars::rflu_destroyplottingvars(), rflu_modplottingvars::rflu_destroyplottingvarsvert(), rflu_modregionmapping::rflu_destroyregionmapping(), rflu_modsplittree::rflu_destroysplittree(), rflu_modoles::rflu_destroystencilsweightsoles(), rflu_modstencilsvert::rflu_destroystencilvert2cell(), rflu_modvertexlists::rflu_destroyvert2celllist(), rflu_modweights::rflu_destroywtsbf2c(), rflu_modweights::rflu_destroywtsbf2cwrapper(), rflu_modweights::rflu_destroywtsc2c(), rflu_modweights::rflu_destroywtsc2cwrapper(), rflu_modweights::rflu_destroywtsf2c(), rflu_modweights::rflu_destroywtsf2cwrapper(), rflu_modgridutils::rflu_distortgrid(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modexplicitmultistage::rflu_ems_setcvold(), rflu_modexplicitmultistage::rflu_ems_setdiss(), rflu_modexplicitmultistage::rflu_ems_setrhs(), rflu_modexplicitmultistage::rflu_ems_updateconservedvars(), rflu_endflowsolver(), rflu_enforceboundswrapper(), rflu_modviscousflux::rflu_enforceheatflux(), rflu_modoles::rflu_enforcesymmetryoles(), rflu_modensight::rflu_ens_builddatainfo(), rflu_modensight::rflu_ens_closefileflowwrapper(), rflu_modensight::rflu_ens_closefilegeometry(), rflu_modensight::rflu_ens_closefilescalarvector(), rflu_modensight::rflu_ens_destroydatainfo(), rflu_modensight::rflu_ens_openfileflowwrapper(), rflu_modensight::rflu_ens_openfilegeometry(), rflu_modensight::rflu_ens_openfilescalarvector(), rflu_modensight::rflu_ens_writefilecase(), rflu_modensight::rflu_ens_writeflowwrapper(), rflu_modensightutils::rflu_ens_writegrid(), rflu_modensight::rflu_ens_writegridwrapper(), rflu_modensightutils::rflu_ens_writescalar(), rflu_modensightutils::rflu_ens_writevector(), rflu_equilibriumeulerian(), rflu_explicitmultistage(), rflu_modextractflowdata::rflu_extractflowdata(), rflu_modextractflowdata::rflu_extractflowdatablasius(), rflu_modextractflowdata::rflu_extractflowdatalinefarf(), rflu_modextractflowdata::rflu_extractflowdatanscbc(), rflu_modextractflowdata::rflu_extractflowdataproudman(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modextractflowdata::rflu_extractflowdatasod(), rflu_modextractflowdata::rflu_extractflowdatasommspi(), rflu_modextractflowdata::rflu_extractflowdatastg1d(), rflu_modextractflowdata::rflu_extractflowdatastg2d(), rflu_modextractflowdatautils::rflu_extractshocklocation1d(), rflu_modprobes::rflu_findprobecells(), rflu_modoles::rflu_findprototypefacesoles(), rflu_finishsd(), rflu_flowsolver(), rflu_flowsolverdummy(), rflu_modgatherdata::rflu_gatherdata(), rflu_modrocstaradmin::rflu_genx_buildgridsurf(), rflu_modrocstaradmin::rflu_genx_buildpconn(), rflu_modrocstario::rflu_genx_buildrocinpanestrings(), rflu_modrocstaradmin::rflu_genx_closerocinctrlfiles(), rflu_modrocstario::rflu_genx_closerocinctrlfiles(), rflu_modrocstartools::rflu_genx_constraindisp(), rflu_modrocstaradmin::rflu_genx_createdatainterf(), rflu_modrocstaradmin::rflu_genx_creategridsurf(), rflu_modrocstaradmin::rflu_genx_createpconn(), rflu_modrocstario::rflu_genx_decidereadfile(), rflu_modrocstario::rflu_genx_decidewritefile(), rflu_modrocstaradmin::rflu_genx_destroydatainterf(), rflu_modrocstaradmin::rflu_genx_destroygridsurf(), rflu_modrocstaradmin::rflu_genx_destroypconn(), rflu_modrocstartools::rflu_genx_initbflag(), rflu_modrocstartools::rflu_genx_movegrid(), rflu_modrocstario::rflu_genx_openrocinctrlfiles(), rflu_modrocstario::rflu_genx_putdatagspeedssurf(), rflu_modrocstario::rflu_genx_putdatagspeedsvol(), rflu_modrocstario::rflu_genx_putgridsurf(), rflu_modrocstario::rflu_genx_putgridvol(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modrocstario::rflu_genx_readwindow(), rflu_modrocstario::rflu_genx_writerocinctrlfiles(), rflu_getboundaryvalues(), rflu_modconstraintutils::rflu_getconstrtype(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_getcvloc(), rflu_getdeformation(), rflu_getdeformationwrapper(), rflu_modcellfaceedgeinfo::rflu_getedgekind(), rflu_modcellfaceedgeinfo::rflu_getfacekind(), rflu_modcellfaceedgeinfo::rflu_getglobalcellkind(), rflu_modcellfaceedgeinfo::rflu_getglobalcelltype(), rflu_modfacelist::rflu_getopposingfaces(), rflu_modpatchutils::rflu_getpatchnormaldirection(), rflu_modregionmapping::rflu_getproclocregids(), rflu_modresidual::rflu_getresidualsupport1(), rflu_modresidual::rflu_getresidualsupport2(), rflu_getspecialcells(), rflu_getuserinput(), rflu_modcellfaceedgeinfo::rflu_getvirtualcellreg(), rflu_modhashtable::rflu_hashedge(), rflu_modhashtable::rflu_hashface(), rflu_modhashtable::rflu_hashvertex(), rflu_modhashtable::rflu_hashvertexfancy(), rflu_modhllcflux::rflu_hllc_computeflux(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_modincelltest::rflu_ict_computetolerance(), rflu_modincelltest::rflu_ict_testfaceplanar(), rflu_modincelltest::rflu_ict_testfacequadbilinear(), rflu_modincelltest::rflu_ict_testincell(), rflu_modincelltest::rflu_ict_testincellfancy(), rflu_modincelltest::rflu_ict_testincelllohner(), rflu_modregionmapping::rflu_imposeregionmappingserial(), rflu_initbcdatahardcode(), rflu_initflowhardcode(), rflu_initflowhardcodelim(), rflu_initflowhardcodelimwrapper(), rflu_initflowhardcodewrapper(), rflu_initflowscratch(), rflu_initflowscratchwrapper(), rflu_initflowserialwrapper(), rflu_initflowsolver(), rflu_modforcesmoments::rflu_initforcesmoments(), rflu_modforcesmoments::rflu_initglobalthrustflags(), rflu_initinputvalues(), rflu_modpatchcoeffs::rflu_initpatchcoeffs(), rflu_modplottingvars::rflu_initplottingvars(), rflu_modplottingvars::rflu_initplottingvarsvert(), rflu_modfacelist::rflu_insertintocell2facelist(), rflu_modinterpolation::rflu_interpcells2face(), rflu_modinterpolation::rflu_interpcells2facepatch(), rflu_modinterpolation::rflu_interpcells2faces(), rflu_modinterpolation::rflu_interpcells2verts(), rflu_interpolatewrapper(), rflu_modinterpolation::rflu_interpsimplecells2verts(), rflu_invertmatrixsvd(), rflu_invflux_i(), rflu_modlimiters::rflu_limitgradcells(), rflu_modlimiters::rflu_limitgradcellssimple(), rflu_modmergeregions::rflu_merg_mergegrid(), rflu_modmergeregions::rflu_merg_mergepatchcoeffs(), rflu_modmergeregions::rflu_merg_mergesolwrapper(), rflu_mergepostprocessregions(), rflu_minimumtimestep(), rflu_movegriddisp(), rflu_movegridwrapper(), rflu_movegridxyz(), rflu_modmpi::rflu_mpi_clearrequest(), rflu_modmpi::rflu_mpi_clearrequestwrapper(), rflu_modmpi::rflu_mpi_copycelldata(), rflu_modmpi::rflu_mpi_copywrapper(), rflu_modmpi::rflu_mpi_createbufferipclsend(), rflu_modmpi::rflu_mpi_createbuffers(), rflu_modmpi::rflu_mpi_createbufferswrapper(), rflu_modmpi::rflu_mpi_destroybufferipclsend(), rflu_modmpi::rflu_mpi_destroybuffers(), rflu_modmpi::rflu_mpi_destroybufferswrapper(), rflu_modmpi::rflu_mpi_isendcelldata(), rflu_modmpi::rflu_mpi_isendwrapper(), rflu_modmpi::rflu_mpi_recreatebufferipclsend(), rflu_modmpi::rflu_mpi_recvcelldata(), rflu_modmpi::rflu_mpi_recvwrapper(), rflu_modmpi::rflu_mpi_settag(), rflu_modmpi::rflu_mpi_settagswrapper(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_comprhs(), rflu_modnscbc::rflu_nscbc_comprhsff(), rflu_modnscbc::rflu_nscbc_comprhsiftotang(), rflu_modnscbc::rflu_nscbc_comprhsifveltemp(), rflu_modnscbc::rflu_nscbc_comprhsij(), rflu_modnscbc::rflu_nscbc_comprhsnswheat(), rflu_modnscbc::rflu_nscbc_comprhsnswtemp(), rflu_modnscbc::rflu_nscbc_comprhsof(), rflu_modnscbc::rflu_nscbc_comprhssw(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modnscbc::rflu_nscbc_decidehavenscbc(), rflu_modnscbc::rflu_nscbc_initff(), rflu_modnscbc::rflu_nscbc_initiftotang(), rflu_modnscbc::rflu_nscbc_initifveltemp(), rflu_modnscbc::rflu_nscbc_initij(), rflu_modnscbc::rflu_nscbc_initnswheat(), rflu_modnscbc::rflu_nscbc_initnswtemp(), rflu_modnscbc::rflu_nscbc_initof(), rflu_modnscbc::rflu_nscbc_initsw(), rflu_modgeometry::rflu_nullifyapproxcentroids(), rflu_modfacelist::rflu_nullifyavface2borderlist(), rflu_modfacelist::rflu_nullifyavface2patchlist(), rflu_modboundlists::rflu_nullifybcellmlist(), rflu_modstencilsbfaces::rflu_nullifybf2cstencil(), rflu_modstencilsbfaces::rflu_nullifybf2cstencil_1d(), rflu_modbfacegradaccesslist::rflu_nullifybfacegradaccesslist(), rflu_modboundlists::rflu_nullifybfaceloclists(), rflu_modboundlists::rflu_nullifybfacesortlists(), rflu_modboundlists::rflu_nullifybvertexlists(), rflu_modboundlists::rflu_nullifybvertexmlist(), rflu_modstencilscells::rflu_nullifyc2cstencil(), rflu_modstencilscells::rflu_nullifyc2cstencil_1d(), rflu_modfacelist::rflu_nullifycell2facelist(), rflu_modcellmapping::rflu_nullifycellmapping(), rflu_modedgelist::rflu_nullifyedge2celllist(), rflu_modedgelist::rflu_nullifyedgelist(), rflu_modstencilsfaces::rflu_nullifyf2cstencil(), rflu_modstencilsfaces::rflu_nullifyf2cstencil_1d(), rflu_modgeometry::rflu_nullifyfacedist(), rflu_modfacelist::rflu_nullifyfacelist(), rflu_modforcesmoments::rflu_nullifyforcesmoments(), rflu_modgeometry::rflu_nullifygeometry(), rflu_modforcesmoments::rflu_nullifyglobalthrustflags(), rflu_modpatchcoeffs::rflu_nullifypatchcoeffs(), rflu_modplottingvars::rflu_nullifyplottingvarmaps(), rflu_modplottingvars::rflu_nullifyplottingvars(), rflu_modplottingvars::rflu_nullifyplottingvarsvert(), rflu_modstencilsvert::rflu_nullifystencilvert2cell(), rflu_modvertexlists::rflu_nullifyvert2celllist(), rflu_modweights::rflu_nullifywtsbf2c(), rflu_modweights::rflu_nullifywtsc2c(), rflu_modweights::rflu_nullifywtsf2c(), rflu_openconverfile(), rflu_modpatchcoeffs::rflu_openpatchcoeffsascii(), rflu_modpatchcoeffs::rflu_openpatchcoeffsbinary(), rflu_openpostinfo(), rflu_modprobes::rflu_openprobefiles(), rflu_modregionmapping::rflu_openregionmappingfile(), rflu_openrestartinfo(), rflu_openstatsfileoles(), rflu_opentotalmassfile(), rflu_modpartitionregion::rflu_part_addvirtualcells(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv1(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_modpartitionregion::rflu_part_buildborderfacelist(), rflu_modpartitionregion::rflu_part_buildcelllists(), rflu_modpartitionregion::rflu_part_buildpatchlists(), rflu_modpartitionregion::rflu_part_buildreg2cellmap(), rflu_modpartitionregion::rflu_part_buildvertexdata(), rflu_modpartitionregion::rflu_part_buildvertexlists(), rflu_modpartitionregion::rflu_part_createcelllists(), rflu_modpartitionregion::rflu_part_createpatchlists(), rflu_modpartitionregion::rflu_part_createreg2cellmap(), rflu_modpartitionregion::rflu_part_destroyborderfacelist(), rflu_modpartitionregion::rflu_part_destroycelldata(), rflu_modpartitionregion::rflu_part_destroycelllists(), rflu_modpartitionregion::rflu_part_destroypatchlists(), rflu_modpartitionregion::rflu_part_destroyvertexdata(), rflu_modpartitionregion::rflu_part_partitionregion(), rflu_modpartitionregion::rflu_part_recreatecelllist(), rflu_modpartitionregion::rflu_part_renumbervertexlists(), rflu_modpetscpoisson::rflu_petsc_buildpoisson(), rflu_modpetscnewtonkrylov::rflu_petsc_createapplicationordering(), rflu_modpetscnewtonkrylov::rflu_petsc_createcoloring(), rflu_modpetscnewtonkrylov::rflu_petsc_createjacobian(), rflu_modpetscpoisson::rflu_petsc_createpoisson(), rflu_modpetscnewtonkrylov::rflu_petsc_createvectors(), rflu_modpetscnewtonkrylov::rflu_petsc_destroyapplicationordering(), rflu_modpetscnewtonkrylov::rflu_petsc_destroyjacobian(), rflu_modpetscnewtonkrylov::rflu_petsc_destroyvectors(), rflu_modpetscadmin::rflu_petsc_finalize(), rflu_modpetscnewtonkrylov::rflu_petsc_formjacobian(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidual(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidualfirstorder(), rflu_modpetscnewtonkrylov::rflu_petsc_getdtscale(), rflu_modpetscadmin::rflu_petsc_init(), rflu_modpetscpoisson::rflu_petsc_setsolverpoisson(), rflu_modpetscpoisson::rflu_petsc_solvepressurepoisson(), rflu_pickregions(), rflu_pickregionscoord(), rflu_pickregionsmanual(), rflu_pickspecialcells(), rflu_pickspecialfaces(), rflu_postprocessregions(), rflu_postprocessregions_ens(), rflu_postprocessregionscommon1(), rflu_postprocessregionscommon2(), rflu_printchangeinfo(), rflu_printflowinfo(), rflu_printflowinfowrapper(), rflu_modforcesmoments::rflu_printglobalforcesmoments(), rflu_printgridinfo(), rflu_printheader(), rflu_printlocinfo(), rflu_modplottingvars::rflu_printplottingvarsinfo(), rflu_modprobes::rflu_printprobeinfo(), rflu_printprogressdots(), rflu_printuserinput(), rflu_printwarninfo(), rflu_printwriteconvergence(), rflu_putboundaryvalues(), rflu_putboundaryvaluesalpha(), rflu_randominit(), rflu_modreadwritebcdatafile::rflu_readbcdatafile(), rflu_modreadbcinputfile::rflu_readbcfarfsection(), rflu_modreadbcinputfile::rflu_readbcinflowtotangsection(), rflu_modreadbcinputfile::rflu_readbcinflowveltempsection(), rflu_modreadbcinputfile::rflu_readbcinjectsection(), rflu_modreadbcinputfile::rflu_readbcinputfile(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), rflu_modreadbcinputfile::rflu_readbcnoslipwallheatsect(), rflu_modreadbcinputfile::rflu_readbcnoslipwalltempsect(), rflu_modreadbcinputfile::rflu_readbcoutflowsection(), rflu_modreadbcinputfile::rflu_readbcperiodicsection(), rflu_modreadbcinputfile::rflu_readbcslipwallsection(), rflu_modreadbcinputfile::rflu_readbcsymmetrysection(), rflu_modreadbcinputfile::rflu_readbcvirtualsection(), rflu_readconvgridwrapper(), rflu_moddimensions::rflu_readdimensions(), rflu_moddimensions::rflu_readdimensionswrapper(), rflu_modreadwriteflow::rflu_readflowascii(), rflu_modreadwriteflow::rflu_readflowbinary(), rflu_modreadwriteflow::rflu_readflowwrapper(), rflu_modreadwritegrid::rflu_readgridascii(), rflu_modreadwritegrid::rflu_readgridbinary(), rflu_modcentaur::rflu_readgridcentaurascii(), rflu_modcentaur::rflu_readgridcentaurbinary(), rflu_modcobalt::rflu_readgridcobalt(), rflu_modgambit::rflu_readgridgambitneutral(), rflu_modmesh3d::rflu_readgridmesh3d(), rflu_modreadwritegridspeeds::rflu_readgridspeedsascii(), rflu_modreadwritegridspeeds::rflu_readgridspeedsbinary(), rflu_modreadwritegridspeeds::rflu_readgridspeedswrapper(), rflu_modtetmesh::rflu_readgridtetmesh(), rflu_modvgridns::rflu_readgridvgridns(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_readintegrals1245oles(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modpatchcoeffs::rflu_readpatchcoeffsascii(), rflu_modpatchcoeffs::rflu_readpatchcoeffsbinary(), rflu_modpatchcoeffs::rflu_readpatchcoeffswrapper(), rflu_readpostinfo(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_readrestartinfo(), rflu_readstat(), rflu_readtbcinputfile(), rflu_readtbcsection(), rflu_modrelatedpatches::rflu_relp_periodicwrapper(), rflu_modrelatedpatches::rflu_relp_symmetrywrapper(), rflu_modrelatedpatches::rflu_relp_transformvector(), rflu_modrelatedpatches::rflu_relp_transformwrapper(), rflu_modboundlists::rflu_renumberbfacelists(), rflu_modrenumberlist::rflu_renumberlist(), rflu_modrenumberlist::rflu_renumberlist2(), rflu_modfacelist::rflu_reorientfaces(), rflu_modresidual::rflu_res_computeresidual(), rflu_modresidual::rflu_res_setcvold(), rflu_modresidual::rflu_res_setdiss(), rflu_modresidual::rflu_res_setrhs(), rflu_residualnorm(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap2d(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap3d(), rflu_modrenumberings::rflu_rnmb_buildsc2pcmap(), rflu_modrenumberings::rflu_rnmb_buildsv2pvmap(), rflu_modrenumberings::rflu_rnmb_createpbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_createpc2scmap(), rflu_modrenumberings::rflu_rnmb_createpv2svmap(), rflu_modrenumberings::rflu_rnmb_createsc2rmap(), rflu_modrenumberings::rflu_rnmb_destroypbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_destroypc2scmap(), rflu_modrenumberings::rflu_rnmb_destroypv2svmap(), rflu_modrenumberings::rflu_rnmb_destroysbc2pcmap(), rflu_modrenumberings::rflu_rnmb_destroysc2pcmap(), rflu_modrenumberings::rflu_rnmb_destroysc2rmap(), rflu_modrenumberings::rflu_rnmb_destroysv2pvmap(), rflu_modrenumberings::rflu_rnmb_readpxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_readsc2rmap(), rflu_modrenumberings::rflu_rnmb_writepxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_writesc2rmap(), rflu_modroeflux::rflu_roe_computeflux(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux1_tcp(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxc1(), rflu_modroeflux::rflu_roe_computefluxc2_tcp(), rflu_modroeflux::rflu_roe_computefluxd1_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_scalarcheckpositivity(), rflu_modconvertcv::rflu_scalarconvertcvcons2prim(), rflu_modconvertcv::rflu_scalarconvertcvprim2cons(), rflu_scalarfirst(), rflu_scalarfirstpatch(), rflu_scalarinitrhs(), rflu_scalarsecond(), rflu_scalarsecondpatch(), rflu_scalarviscousfluxes(), rflu_modgatherdata::rflu_scattergathereddata(), rflu_setdependentvars(), rflu_setderiveduserinput(), rflu_setgasvars(), rflu_modforcesmoments::rflu_setglobalthrustflags(), rflu_modstencilsbfaces::rflu_setinfobf2cstencil(), rflu_modstencilsbfaces::rflu_setinfobf2cstencil_1d(), rflu_modstencilsbfaces::rflu_setinfobf2cstencilwrapper(), rflu_modstencilscells::rflu_setinfoc2cstencil(), rflu_modstencilscells::rflu_setinfoc2cstencil_1d(), rflu_modstencilscells::rflu_setinfoc2cstencilwrapper(), rflu_modstencilsfaces::rflu_setinfof2cstencil(), rflu_modstencilsfaces::rflu_setinfof2cstencil_1d(), rflu_modstencilsfaces::rflu_setinfof2cstencilwrapper(), rflu_modstencilsvert::rflu_setinfostencilvert2cell(), rflu_moddimensions::rflu_setmaxdimensions(), rflu_setmovegridoptions(), rflu_modpatchutils::rflu_setpatchflatflags(), rflu_setpatchplotflags(), rflu_modregionmapping::rflu_setregionmappingserial(), rflu_setrestarttimeflag(), rflu_modtime::rflu_settimerk(), rflu_settransportvars(), rflu_setvarinfo(), rflu_setvarinfowrapper(), rflu_setvars(), rflu_setvarscontwrapper(), rflu_setvarsdiscwrapper(), rflu_setvarswrapper(), rflu_modstencilsutils::rflu_sortbfaces(), rflu_modstl::rflu_stl_writesurfgridascii(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcells(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv1(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2(), rflu_modsymmetryperiodic::rflu_sype_augmentcelllists(), rflu_modsymmetryperiodic::rflu_sype_augmentvertexlists(), rflu_modsymmetryperiodic::rflu_sype_buildp2vclist(), rflu_modsymmetryperiodic::rflu_sype_buildp2vclistserial(), rflu_modsymmetryperiodic::rflu_sype_buildtransforms(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modsymmetryperiodic::rflu_sype_createp2vclist(), rflu_modsymmetryperiodic::rflu_sype_createvertexmaps(), rflu_modsymmetryperiodic::rflu_sype_destroyp2vclist(), rflu_modsymmetryperiodic::rflu_sype_getactualserialcell(), rflu_modsymmetryperiodic::rflu_sype_getrelatedvertex(), rflu_modsymmetryperiodic::rflu_sype_havesypepatches(), rflu_modsymmetryperiodic::rflu_sype_imposevertexmap(), rflu_modsymmetryperiodic::rflu_sype_readtransforms(), rflu_modsymmetryperiodic::rflu_sype_setsypepatchesflag(), rflu_modsymmetryperiodic::rflu_sype_writetransforms(), rflu_modtecplot::rflu_tec_builddatafieldsurf(), rflu_modtecplot::rflu_tec_builddatafieldvol(), rflu_modtecplot::rflu_tec_builddatapatch(), rflu_modtecplot::rflu_tec_builddatapatchstats(), rflu_modtecplot::rflu_tec_buildheaderfield(), rflu_modtecplot::rflu_tec_buildheaderpatch(), rflu_modtecplot::rflu_tec_buildheaderpatchstats(), rflu_modtecplotutils::rflu_tec_closefile(), rflu_modtecplot::rflu_tec_closefilefield(), rflu_modtecplot::rflu_tec_closefilepatch(), rflu_modtecplot::rflu_tec_closefilepatchstats(), rflu_modtecplot::rflu_tec_closefilepnt(), rflu_modtecplot::rflu_tec_destroydatafieldsurf(), rflu_modtecplot::rflu_tec_destroydatafieldvol(), rflu_modtecplot::rflu_tec_destroydatapatch(), rflu_modtecplot::rflu_tec_init(), rflu_modtecplotutils::rflu_tec_openfile(), rflu_modtecplot::rflu_tec_openfilefield(), rflu_modtecplot::rflu_tec_openfilepatch(), rflu_modtecplot::rflu_tec_openfilepatchstats(), rflu_modtecplot::rflu_tec_openfilepnt(), rflu_modtecplot::rflu_tec_writefilefieldsurf(), rflu_modtecplot::rflu_tec_writefilefieldvol(), rflu_modtecplot::rflu_tec_writefilepatch(), rflu_modtecplot::rflu_tec_writefilepnt(), rflu_modtecplotutils::rflu_tec_writezonecellsspecial(), rflu_modtecplotutils::rflu_tec_writezonefacesspecial(), rflu_modtecplotutils::rflu_tec_writezoneinterf(), rflu_modtecplotutils::rflu_tec_writezonesurf(), rflu_modtecplotutils::rflu_tec_writezonesurfmixed(), rflu_modtecplotutils::rflu_tec_writezonevol(), rflu_modgeometrytools::rflu_testinboundbox(), rflu_modboundarytests::rflu_testisboundarycell(), rflu_modboundarytests::rflu_testisboundaryvertex(), rflu_modgeometrytools::rflu_testvectorcartaxisaligned(), rflu_timestepinviscid(), rflu_timestepping(), rflu_timestepviscous(), rflu_modthrustspecimpulse::rflu_tsi_closeglobalvals(), rflu_modthrustspecimpulse::rflu_tsi_computeglobalthrustsi(), rflu_modthrustspecimpulse::rflu_tsi_openglobalvals(), rflu_modthrustspecimpulse::rflu_tsi_printglobalvals(), rflu_modthrustspecimpulse::rflu_tsi_writeglobalvals(), rflu_modhashtable::rflu_unhashbface(), rflu_updateboundaryvalues(), rflu_updateinbuffgm(), rflu_updateinbuffwrapper(), rflu_user_enforcepatchcoords(), rflu_user_getdeformation(), rflu_userinput(), rflu_modviscousflux::rflu_viscousfluxes(), rflu_modviscousflux::rflu_viscousfluxespatches(), rflu_modweno::rflu_wenogradcells_2d(), rflu_modweno::rflu_wenogradcells_3d(), rflu_modweno::rflu_wenogradcellswrapper(), rflu_modweno::rflu_wenogradcellsxyz_1d(), rflu_modweno::rflu_wenogradcellsxyz_2d(), rflu_modweno::rflu_wenogradcellsxyz_3d(), rflu_modweno::rflu_wenogradcellsxyzfast_2d(), rflu_modweno::rflu_wenogradcellsxyzfast_3d(), rflu_modweno::rflu_wenogradcellsxyzwrapper(), rflu_modreadwritebcdatafile::rflu_writebcdatafile(), rflu_moddimensions::rflu_writedimensions(), rflu_moddimensions::rflu_writedimensionsborders(), rflu_moddimensions::rflu_writedimensionswrapper(), rflu_modreadwriteflow::rflu_writeflowascii(), rflu_modreadwriteflow::rflu_writeflowbinary(), rflu_modreadwriteflow::rflu_writeflowwrapper(), rflu_modforcesmoments::rflu_writeglobalforcesmoments(), rflu_modreadwritegrid::rflu_writegridascii(), rflu_modreadwritegrid::rflu_writegridbinary(), rflu_modreadwritegridspeeds::rflu_writegridspeedsascii(), rflu_modreadwritegridspeeds::rflu_writegridspeedsbinary(), rflu_modreadwritegridspeeds::rflu_writegridspeedswrapper(), rflu_modreadwritegrid::rflu_writegridwrapper(), rflu_writeintegrals1245oles(), rflu_modcellmapping::rflu_writeloc2globcellmapping(), rflu_modextractflowdata::rflu_writemeshbump(), rflu_modpatchcoeffs::rflu_writepatchcoeffsascii(), rflu_modpatchcoeffs::rflu_writepatchcoeffsbinary(), rflu_modpatchcoeffs::rflu_writepatchcoeffswrapper(), rflu_writepostinfo(), rflu_modregionmapping::rflu_writeregionmappingfile(), rflu_writerestartinfo(), rflu_writespecialcells(), rflu_writestat(), rflu_writestatsfileoles(), rflu_modtetmesh::rflu_writesurfgridtetmesh(), rflu_writeversionstring(), rflu_zerovirtualcellvars(), rflucells(), rfluconv(), rfluinit(), rflupart(), rflupick(), rflupost(), rkinitgeneric(), rkinitmp(), rkinitpointscalar(), rkinitsd(), rkupdategeneric(), rkupdatemp(), rkupdatepointscalar(), rocflo_2dto3d(), rocflo_blocks(), rocflo_init(), rocflo_post(), rocflo_split(), rocflo_surf(), rocflo_toflu(), rocpart_post(), rocvav_post(), rungekuttamp(), rvav_blasiussolution(), rvav_computeanalyticalsolution(), rvav_computeerror(), rvav_computesimilarfield(), rvav_extractvariables(), rvav_gammbumpsolution(), rvav_plotresults(), rvav_proudmanculicksolution(), rvav_readcomparisonssection(), rvav_readfilestream1(), rvav_readfilestream2(), rvav_readfilestream2analyt(), rvav_readfilestream2comput(), rvav_readfilestream2experm(), rvav_readinputfile(), rvav_readsectionstream1(), rvav_readsectionstream2(), scalegridspeeds(), sourceterms(), sourcetermsmp(), spec_checkuserinput(), spec_derivedinputvalues(), spec_eqeulcorr(), spec_eqeulcorrpatch(), spec_initinputvalues(), spec_initinputvaluesspectype(), spec_printuserinput(), spec_readinputfile(), spec_readspecsection(), spec_readspectypesection(), spec_rflu_allocatememory(), spec_rflu_allocatememoryeev(), spec_rflu_allocatememorysol(), spec_rflu_allocatememorytstep(), spec_rflu_allocatememoryvert(), spec_rflu_deallocatememory(), spec_rflu_deallocatememoryeev(), spec_rflu_deallocatememorysol(), spec_rflu_deallocatememorytstep(), spec_rflu_deallocatememoryvert(), spec_rflu_enforcebounds(), spec_rflu_initflowhardcode(), spec_rflu_initflowscratch(), spec_rflu_modchemistry::spec_rflu_integratechemsrcterm(), spec_rflu_printflowinfo(), spec_rflu_readbcfarfsection(), spec_rflu_readbcinflowsection(), spec_rflu_readbcinjectsection(), spec_rflu_readbcinputfile(), spec_rflu_readbcsectiondummy(), spec_rflu_modreadwritevars::spec_rflu_readcvascii(), spec_rflu_modreadwritevars::spec_rflu_readcvbinary(), spec_rflu_modreadwritevars::spec_rflu_readeevascii(), spec_rflu_modreadwritevars::spec_rflu_readeevbinary(), spec_rflu_seteev(), spec_rflu_setvarinfo(), spec_rflu_sourceterms_gl(), spec_rflu_modreadwritevars::spec_rflu_writecvascii(), spec_rflu_modreadwritevars::spec_rflu_writecvbinary(), spec_rflu_modreadwritevars::spec_rflu_writeeevascii(), spec_rflu_modreadwritevars::spec_rflu_writeeevbinary(), spec_updatedependentvars(), spec_userinput(), splitgrid(), splitquadface(), splittopology(), modstatsroutines::statdatasampling(), modstatsroutines::statmapping(), modstatsroutines::stattimeaccumulation(), modstatsroutines::statwritemp(), turb_allocatememory(), turb_calcmetrics(), turb_calcvortic(), turb_checkparaminput(), turb_coranswalldistov(), turb_coviscousfluxes(), turb_cowlmreadbcsection(), turb_derivedinputvalues(), turb_emsinit(), turb_floextrapintcellscal(), turb_floextrapintcellvec(), turb_floextrapolcellvec(), turb_floextrapolfacevec(), turb_flofacevolume(), turb_flofacewidth(), turb_flofacewidthdummy(), turb_flofacewidthdummyconn(), turb_flofacewidthdummyphys(), turb_flolesaverageface(), turb_flolesgenc2f(), turb_flolesgencocc(), turb_flolesgencocchi(), turb_flolesgencocclo(), turb_flolesgencofchi(), turb_flolesgencofclo(), turb_flolesgencoff(), turb_flolesgencoffhi(), turb_flolesgencofflo(), turb_flolesgenfiltcc(), turb_flolesgenfiltcci(), turb_flolesgenfiltccj(), turb_flolesgenfiltcck(), turb_flolesgenfiltff(), turb_flolesgenfiltffi(), turb_flolesgenfiltffj(), turb_flolesgenfiltffk(), turb_flolesunifiltcc(), turb_flolesunifiltcci(), turb_flolesunifiltccj(), turb_flolesunifiltcck(), turb_flolesunifiltff(), turb_flolesunifiltffi(), turb_flolesunifiltffj(), turb_flolesunifiltffk(), turb_floransbcondinflow(), turb_floransbcondinjection(), turb_floransbcondnoslipwall(), turb_floransbcondsymmetry(), turb_floransbcondzerograd(), turb_floranscentraldissipation(), turb_floranscorrcornedgecells(), turb_floransexchangedummyconf(), turb_floransexchcornedgecells(), turb_floransrecvcornedgecells(), turb_floransrecvdummyvals(), turb_floranssacentflux(), turb_floranssacentfluxpatch(), turb_floranssaroe1stflux(), turb_floranssaroe2ndflux(), turb_floranssaroefluxpatch(), turb_floranssendcornedgecells(), turb_floranssenddummyconf(), turb_floranssetcornedgecells(), turb_flowlmmetric(), turb_flowlmupdateloglay(), turb_flucv2cons(), turb_flucv2prim(), turb_flufacevolume(), turb_flulesblij(), turb_flulesbmij(), turb_flulesc2f(), turb_getmodelstresscell(), turb_gettvcell(), turb_initgenxinterface(), turb_initinputvalues(), turb_initsolution(), turb_lescalceddyvis(), turb_lescoefdynmixd(), turb_lescoefdynsmag(), turb_lescommunication(), turb_lescontract(), turb_lesesgmodel4(), turb_lesfluxfixsmag(), turb_lesfluxscalsim(), turb_lesgeteddyvis(), turb_leshij(), turb_leslij(), turb_lesmij(), turb_lesrkinit(), turb_lestestrhov(), turb_printuserinput(), turb_ransconvectivefluxes(), turb_ransemsinit(), turb_ransemsupdate(), turb_ransnumericaldissipation(), turb_ransrkinit(), turb_ranssageteddyvis(), turb_ranssasourceterms(), turb_ranssavisflux(), turb_ranssavisfluxpatch(), turb_ranssourceterms(), turb_ranstotaltv(), turb_ranswalldistovpatch(), turb_ranszerodummycells(), turb_readbcinputfile(), turb_readinputfile(), turb_readturbsection(), turb_rflo_ransallocdatabuffers(), turb_rflo_ransbndconditionsrecv(), turb_rflo_ransbndconditionssend(), turb_rflo_ransbndconditionsset(), turb_rflo_ransclearsendrequests(), turb_rflo_ransressmoothing(), turb_rflo_ransressmoothingcoeff(), turb_rflo_ransspectralradii(), turb_rflo_readsolution(), turb_rflo_readsolutionregion(), turb_rflo_writesolution(), turb_modpostflu::turb_rflu_allocmempost(), turb_modpostflu::turb_rflu_allocmempostvert(), turb_rflu_deallocatememory(), turb_modpostflu::turb_rflu_deallocmempost(), turb_modpostflu::turb_rflu_deallocmempostvert(), turb_rflu_readsolutionascii(), turb_rflu_readsolutionbinary(), turb_rflu_writesolutionascii(), turb_rflu_writesolutionbinary(), turb_rkinit(), turb_solutionupdate(), turb_statccollector(), turb_statmapping(), turb_userinput(), turb_vfluxhybrid(), turb_vfluxhybridpatch(), turb_visfluxeddy(), turb_visfluxeddypatch(), turb_wlmfluxpatch(), turb_wlminitia(), turb_wlmreyanalogy(), turb_wlmtauwallmapping(), turb_wlmupdate(), turb_wlmupdatebndlay(), updateboundaryconditionsmp(), updatedependentvarsmp(), updatetbc(), updatetbcpiecewise(), updatetbcsinusoidal(), updatetbcstochastic(), updatetbcwhitenoise(), viscousfluxes(), viscousfluxesmp(), prep_modbcdistribution::writebctofile(), writeconvergence(), writeflucellmap(), writefludimens(), writeflugrid(), writegeneric(), writeprobe(), writesurfacegrid(), writetecplotascii(), writetecplotbinary(), writethrust(), writetotalmass(), zerodummycellsmp(), and zeroresidualsmp().
subroutine errorstop (type(t_global), pointer global, integer errorCode, integer errorLine, character(*), optional addMessage)
Definition at line 483 of file ModError.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, and StopWatch::stop().
Referenced by allocatememorywork(), bccaseloop(), prep_modbcdistribution::bcdistributionfiles(), prep_modbcdistribution::bcfarfdistrib(), prep_modbcdistribution::bcinflowtotangdistrib(), prep_modbcdistribution::bcinflowveldistrib(), prep_modbcdistribution::bcinjectdistrib(), prep_modbcdistribution::bcnoslipdistrib(), prep_modbcdistribution::bcoutflowdistrib(), prep_modbcdistribution::bcslipwalldistrib(), modbuildfilenames::buildfilenamebasic(), buildfilenamebasic(), buildfilenameplain(), modbuildfilenames::buildfilenameplain(), modbuildfilenames::buildfilenameplainsteady(), modbuildfilenames::buildfilenameplainunsteady(), buildfilenamesteady(), modbuildfilenames::buildfilenamesteady(), modbuildfilenames::buildfilenameunsteady(), buildfilenameunsteady(), cellgradientsmp(), checkbcvalidity(), checkindxrange(), computefluxtot(), convectivefluxes(), convectivefluxesmp(), convertflo2flumesh(), genxinitsolution(), genxwriterocinout(), genxwritesolution(), getgrid(), initializeflowfield(), inrt_allocateauxillary(), inrt_augmentdissources(), inrt_burnstatusupdate(), inrt_calcburning(), inrt_calcdrag(), inrt_calcheattransfernonburn(), inrt_calcscouring(), inrt_checkuserinput(), inrt_defineburning(), inrt_definescouring(), inrt_initialize(), inrt_readboilingregulation(), inrt_readburning(), inrt_readdefaultsection(), inrt_readdrag(), inrt_readheattransfernonburn(), inrt_readinputfile(), inrt_readmaterialinput(), inrt_readscouring(), inrt_setactiveness(), inrt_setmaterial(), inrt_setparticletemp(), inrt_setpermission(), inrt_sourceterms(), inrt_twodimaverage(), inrt_vaporenergyconversion(), modsortsearch::mergesortedintegers(), mixtureproperties(), nodestr(), peri_allocatememory(), peri_checkparaminput(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_cocprslowterms(), peri_copgradupdate(), peri_derivedinputvalues(), peri_initsolution(), peri_readinputfile(), permstr(), peul_allocatedatabuffers(), peul_allocatememory(), peul_bcondinflow(), peul_bcondinjection(), peul_boundaryconditionsset(), peul_centraldissipation(), peul_centralflux(), peul_centralfluxpatch(), peul_clearsendrequests(), peul_derivedinputvalues(), peul_exchangedummyconf(), peul_printuserinput(), peul_readbcfarfsection(), peul_readbcinflowsection(), peul_readbcinjectsection(), peul_readbcinputfile(), peul_readconpartptypesection(), peul_readconpartsection(), peul_readinputfile(), peul_readsolution(), peul_readsolutionregion(), peul_receivecorneredgecells(), peul_receivedummyvals(), peul_rocflo_post(), peul_sendcorneredgecells(), peul_senddummyconf(), peul_sourceeqeul(), peul_writesolution(), plag_allocatedatabuffers(), plag_allocatememory(), plag_allocatememorypost(), plag_allocatememorytile(), plag_binsortnozzleinlet(), plag_binsortspatialdist(), plag_boundaryconditionsset(), plag_bufferdatarecv(), plag_bufferdatasend(), plag_buffersizerecv(), plag_buffersizesend(), plag_calcbreakup(), plag_moddimensions::plag_calcnpclsglobal(), plag_cecellsallocatedata(), plag_cecellsclearrequestsdata(), plag_cecellsclearrequestssize(), plag_cecellsdeallocatedata(), plag_cecellsexchange(), plag_cecellsrecvdata(), plag_cecellsrecvsize(), plag_cecellssenddata(), plag_cecellssendrecvwrapper(), plag_cecellssendsize(), plag_cecellswrapper(), plag_modcheckvars::plag_checkpositivity(), plag_checkuserinput(), plag_modcheckvars::plag_checkvalidity(), plag_cleardatasendrequests(), plag_clearsizesendrequests(), plag_modsurfstats::plag_closesurfstats(), plag_corncellsloaddata(), plag_modeulerian::plag_createeulerianfield(), plag_modstats::plag_createstat(), plag_modsurfstats::plag_createsurfstats(), plag_modsurfstats::plag_createsurfstatskernel(), plag_deallocatedatabuffers(), plag_deallocatememorypost(), plag_modeulerian::plag_destroyeulerianfield(), plag_modstats::plag_destroystat(), plag_modsurfstats::plag_destroysurfstats(), plag_modsurfstats::plag_destroysurfstatskernel(), plag_moddatastruct::plag_dstr_buildcell2pcllist(), plag_moddatastruct::plag_dstr_copyparticle(), plag_moddatastruct::plag_dstr_createcell2pcllist(), plag_moddatastruct::plag_dstr_createpcllistcsr(), plag_moddatastruct::plag_dstr_destroycell2pcllist(), plag_moddatastruct::plag_dstr_destroypcllistcsr(), plag_moddatastruct::plag_dstr_recreatecell2pcllist(), plag_edgecellsloaddata(), plag_modinjection::plag_ejectparticle(), plag_modeulerian::plag_initeulerianfield(), plag_injcejectparticle(), plag_injcmakeparticle(), plag_inrt_allocmemtstep(), plag_inrt_deallocmemtstep(), plag_intrpmixtproperties(), plag_modsurfstats::plag_opensurfstatsascii(), plag_modsurfstats::plag_opensurfstatsbinary(), plag_patchbuffersendrecv(), plag_patchexchangeconf(), plag_patchloaddatabuffers(), plag_processeulerfield(), plag_readdispartinitsection(), plag_readdispartncontsection(), plag_readinputfile(), plag_readpdffromfile(), plag_readsolution(), plag_readsolutionfilepost(), plag_readstatpost(), plag_modsurfstats::plag_readsurfstatsascii(), plag_modsurfstats::plag_readsurfstatsbinary(), plag_modsurfstats::plag_readsurfstatswrapper(), plag_rflo_modstats::plag_rflo_clearreqstatbuff(), plag_rflo_clearsendrequests(), plag_rflo_modstats::plag_rflo_commstatbuffwrapper(), plag_rflo_modstats::plag_rflo_copystatbuff(), plag_rflo_modstats::plag_rflo_createstatbuff(), plag_rflo_ejectparticle(), plag_rflo_modstats::plag_rflo_readstat(), plag_rflo_recvmetrics(), plag_rflo_modstats::plag_rflo_recvstatbuff(), plag_rflo_sendmetrics(), plag_rflo_sendrecvmetrics(), plag_rflo_modstats::plag_rflo_sendstatbuffconf(), plag_rflo_modstats::plag_rflo_sendstatbuffwrapper(), plag_rflo_modstats::plag_rflo_writestat(), plag_rflu_allocmemsol(), plag_rflu_allocmemsoltile(), plag_rflu_allocmemtstep(), plag_rflu_allocmemtsteptile(), plag_rflu_modcomm::plag_rflu_clearrequest(), plag_rflu_modcomm::plag_rflu_commdriver(), plag_rflu_modcomm::plag_rflu_copydata(), plag_rflu_modcomm::plag_rflu_copydataint(), plag_rflu_modcomm::plag_rflu_copydatareal(), plag_rflu_correctmixtproperties(), plag_rflu_modcomm::plag_rflu_createbuffersrecv(), plag_rflu_modcomm::plag_rflu_createbufferssend(), plag_rflu_deallocmemsol(), plag_rflu_deallocmemsoltile(), plag_rflu_deallocmemtstep(), plag_rflu_deallocmemtsteptile(), plag_rflu_modcomm::plag_rflu_destroybuffersrecv(), plag_rflu_modcomm::plag_rflu_destroybufferssend(), plag_rflu_modfindcells::plag_rflu_findcellsbrute(), plag_rflu_modfindcells::plag_rflu_findcellsbrutemod(), plag_rflu_modfindcells::plag_rflu_findcellslohner(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), plag_rflu_modfindcells::plag_rflu_findcellstrajsafe(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), plag_rflu_initsolserialwrapper(), plag_rflu_initsolutionrandom(), plag_rflu_injctilecalcrhs(), plag_rflu_injectiondriver(), plag_rflu_modcomm::plag_rflu_isendcounters(), plag_rflu_modcomm::plag_rflu_isenddata(), plag_moddimensions::plag_rflu_readdimensions(), plag_rflu_readsolutionascii(), plag_rflu_readsolutionbinary(), plag_rflu_modcomm::plag_rflu_recvcounters(), plag_rflu_modcomm::plag_rflu_recvdata(), plag_rflu_modcomm::plag_rflu_totalnpclscomm(), plag_rflu_update(), plag_moddimensions::plag_rflu_writedimensions(), plag_rflu_writesolutionascii(), plag_rflu_writesolutionbinary(), plag_modrkinit::plag_rkinitgenericint(), plag_modrkinit::plag_rkinitgenericreal(), plag_modsurfstats::plag_setbinindex(), plag_statmapping(), plag_writesolution(), plag_writestattecascii(), plag_modsurfstats::plag_writesurfstatswrapper(), plag_writetecplotascii(), radi_allocatememory(), radi_extinctioncoef(), radi_floflimcentfluxpatch(), radi_floflimexchangedummyconf(), radi_floflimrecvcornedgecells(), radi_floflimrecvdummyvals(), radi_floflimsendcornedgecells(), radi_floflimsenddummyconf(), radi_fluxlimiter(), radi_initgenxinterface(), radi_rflo_flimallocdatabuffers(), radi_rflo_flimbndconditionssend(), radi_rflo_flimbndconditionsset(), radi_rflo_flimclearsendrequests(), radi_rflo_readsolution(), radi_rflo_writesolution(), readbcinputfile(), readinitflowsection(), readinputfile(), prep_modbcdistribution::readpatchsection(), readprobesection(), readrandomsection(), readstatisticsection(), registerfunction(), rflo_allocatedatabuffers(), rflo_allocatememory(), rflo_modboundaryconditions::rflo_bcondfarfield(), rflo_modboundaryconditions::rflo_bcondinflow(), rflo_modboundaryconditions::rflo_bcondinjection(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflow(), rflo_modboundaryconditions::rflo_boundaryconditionsset(), rflo_centralfluxpatch(), rflo_changeinteriorgrid(), rflo_checkbcinput(), rflo_checkderiveduserinput(), rflo_checkmetrics(), rflo_checkminimumcells(), rflo_checkregionfaces(), rflo_checkuserinput(), rflo_clearsendrequests(), rflo_modrestartinfo::rflo_closerestartinfo(), rflo_modforcesmoments::rflo_computeintegralforcemomco(), rflo_computeintegralvalues(), rflo_copyboundarydata(), rflo_copytopologylevels(), rflo_domemoryallocation(), rflo_endflowsolver(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangedummyconf(), rflo_exchangegeometrycopy(), rflo_exchangegeometryprepare(), rflo_exchangegeometryrecv(), rflo_exchangegeometrysend(), rflo_findsourcepatches(), rflo_findsourceregions(), rflo_flowsolver(), rflo_getboundaryvalues(), rflo_getcornercellsindices(), rflo_getdeformation(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getedgecellsindices(), rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modgridcontrolmap::rflo_gridcontrolmap2d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_modgridmetrics::rflo_gridqualityglobal(), rflo_initflowsolver(), rflo_initgenxinterface(), rflo_initgenxinterfaceprep(), rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_modlaplacesmoothing::rflo_laplacegridortho1(), rflo_modlaplacesmoothing::rflo_laplacegridortho2(), rflo_mapregionsprocessors(), rflo_modmovegridframe::rflo_mgframebroadcast(), rflo_modmovegridframe::rflo_mgframecornpoints(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframemovecorners(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_minimumtimestep(), rflo_movegridblocks(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_modmovegridutil::rflo_movegridqflatpatch(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_openconverfile(), rflo_modforcesmoments::rflo_openforcemomcofile(), rflo_openprobefile(), rflo_modrestartinfo::rflo_openrestartinfo(), rflo_openthrustfile(), rflo_randominit(), rflo_readbcfarfsection(), rflo_readbcfromfile(), rflo_readbcinflowtotangsection(), rflo_readbcinflowvelsection(), rflo_readbcinjectapnsection(), rflo_readbcinjectmratesection(), rflo_readbcinputfile(), rflo_readbcnoslipsection(), rflo_readbcoutflowsection(), rflo_readbcslipwallsection(), rflo_readdatafileint(), rflo_readdatafilereal(), rflo_readgrid(), rflo_readgridregion(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffs(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffsreg(), rflo_readrandomstate(), rflo_readregionmapsection(), rflo_readregiontopology(), rflo_readsolution(), rflo_readsolutionregion(), rflo_readstat(), rflo_readstatregion(), rflo_readtbcinputfile(), rflo_readtbcsection(), rflo_receivecorneredgecells(), rflo_receivedummyvals(), rflo_residualnorm(), rflo_roefluxpatch(), rflo_sendboundaryvalues(), rflo_sendcorneredgecells(), rflo_senddummyconf(), rflo_setmstagecoeffs(), rflo_timestepping(), rflo_userinput(), rflo_modvolmeshsmoothing::rflo_vmslaplaceprocedure(), rflo_modvolmeshsmoothing::rflo_vmsprojectvertices(), rflo_writedatafileint(), rflo_writedatafilereal(), rflo_moddegeneratecornedge::rflo_writedegeneratec(), rflo_writegrid(), rflo_writegridregion(), rflo_modforcesmoments::rflo_writeintegralforcemomco(), rflo_modpatchaerocoeffs::rflo_writepatchaerocoeffs(), rflo_modforcesmoments::rflo_writepatchcoeffsinfo(), rflo_writerandomstate(), rflo_writeregiontopology(), rflo_writesolution(), rflo_writesolutionregion(), rflo_writestat(), rflu_moddimensionality::rflu_123d_checkgeometrykernel(), rflu_moddimensionality::rflu_123d_checkgeometrywrapper(), rflu_moddimensionality::rflu_123d_checktopology(), rflu_modstencilsutils::rflu_addbfaces(), rflu_modstencilsutils::rflu_addcelllayer(), rflu_modstencilsutils::rflu_addcelllayer_1d(), rflu_modstencilsutils::rflu_addcelllayer_1d_g(), rflu_modoles::rflu_allocatedcuhrearrays(), rflu_allocatedcuhrearrays(), rflu_allocatememory(), rflu_modallocatememory::rflu_allocatememorygspeeds(), rflu_modallocatememory::rflu_allocatememorysolcv(), rflu_modallocatememory::rflu_allocatememorysoldv(), rflu_modallocatememory::rflu_allocatememorysolgv(), rflu_modallocatememory::rflu_allocatememorysoltv(), rflu_allocatememorytbc(), rflu_modallocatememory::rflu_allocatememorytstep(), rflu_modallocatememory::rflu_allocatememorytstep_c(), rflu_modallocatememory::rflu_allocatememorytstep_i(), rflu_allocatememoryvert(), rflu_allocatememorywrapper(), rflu_modausmflux::rflu_ausm_computeflux(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modbilinearpatch::rflu_blin_findclosestpoint(), rflu_modfacelist::rflu_buildavface2borderlist(), rflu_modfacelist::rflu_buildavface2patchlist(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilsbfaces::rflu_buildbf2cstencil_1d(), rflu_modstencilsbfaces::rflu_buildbf2cstencilwrapper(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modboundlists::rflu_buildbvertexmlist(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil_1d(), rflu_modstencilscells::rflu_buildc2cstencil_1d_g(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modstencilscells::rflu_buildc2cstencilbasic_1d(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_modtopologyutils::rflu_buildcellvertlist(), rflu_builddatastruct(), rflu_modedgelist::rflu_buildedge2celllist(), rflu_modedgelist::rflu_buildedgelist(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil_1d(), rflu_modstencilsfaces::rflu_buildf2cstencilwrapper(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modstencilscells::rflu_buildlistcc2cstencil(), rflu_modstencilsfaces::rflu_buildlistcf2cstencil(), rflu_modoles::rflu_buildstencilsoles(), rflu_modstencilsvert::rflu_buildstencilvert2cell(), rflu_modvertexlists::rflu_buildvert2celllist(), rflu_modtopologyutils::rflu_buildvertcellnghblist(), rflu_modboundxvutils::rflu_bxv_computevarscv(), rflu_modboundconvertcv::rflu_bxv_convertcvcons2prim(), rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_modboundxvutils::rflu_bxv_createvarscv(), rflu_modboundxvutils::rflu_bxv_createvarsdv(), rflu_modboundxvutils::rflu_bxv_createvarststep(), rflu_modboundxvutils::rflu_bxv_destroyvarscv(), rflu_modboundxvutils::rflu_bxv_destroyvarsdv(), rflu_modboundxvutils::rflu_bxv_destroyvarststep(), rflu_modboundxvutils::rflu_bxv_initvars(), rflu_modboundxvutils::rflu_bxv_readvarsascii(), rflu_modboundxvutils::rflu_bxv_readvarsbinary(), rflu_modboundxvutils::rflu_bxv_readvarswrapper(), rflu_modboundxvutils::rflu_bxv_setdependentvarspatch(), rflu_modboundxvutils::rflu_bxv_writevarsascii(), rflu_modboundxvutils::rflu_bxv_writevarsbinary(), rflu_modboundxvutils::rflu_bxv_writevarswrapper(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_checkcouplinginput(), rflu_checkderiveduserinput(), rflu_modcentaur::rflu_checkgridcentaur(), rflu_modgambit::rflu_checkgridgambit(), rflu_checkgridspeeds(), rflu_modpatchutils::rflu_checkpatchbcconsistency(), rflu_checkpositivity(), rflu_checkpositivity_gl(), rflu_checkpositivitywrapper(), rflu_modregionmapping::rflu_checkregionmapping(), rflu_checkuserinput(), rflu_checkvalidity(), rflu_checkvalidity_gl(), rflu_checkvaliditywrapper(), rflu_modpatchcoeffs::rflu_closepatchcoeffs(), rflu_closepostinfo(), rflu_modprobes::rflu_closeprobefiles(), rflu_modregionmapping::rflu_closeregionmappingfile(), rflu_closerestartinfo(), rflu_modcoloring::rflu_col_buildcolorings(), rflu_modcoloring::rflu_col_createcoloring(), rflu_modcoloring::rflu_col_destroycoloring(), rflu_modcoloring::rflu_col_readcoloring(), rflu_modcoloring::rflu_col_recreatecelllist(), rflu_modcoloring::rflu_col_writecoloring(), rflu_modcommlists::rflu_comm_buildcommlistscells(), rflu_modcommlists::rflu_comm_buildcommlistsvert(), rflu_modcommlists::rflu_comm_checkcountborders(), rflu_modcommlists::rflu_comm_countborders(), rflu_modcommlists::rflu_comm_countbordersserial(), rflu_modcommlists::rflu_comm_createbordercntr(), rflu_modcommlists::rflu_comm_createborders(), rflu_modcommlists::rflu_comm_createcommlists(), rflu_modcommlists::rflu_comm_destroybordercntr(), rflu_modcommlists::rflu_comm_destroyborders(), rflu_modcommlists::rflu_comm_destroycommlists(), rflu_modcommlists::rflu_comm_getproclocregids(), rflu_modcommlists::rflu_comm_readcommlists(), rflu_modcommlists::rflu_comm_writecommlists(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationbfaces::rflu_computebfgradconstrwrapper(), rflu_computedcuhreinfo(), rflu_computeenerdissoles(), rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), rflu_computefluxinv(), rflu_modforcesmoments::rflu_computeglobalforcesmoments(), rflu_moddifferentiationbfaces::rflu_computegradbfaces(), rflu_moddifferentiationbfaces::rflu_computegradbfaces_1d(), rflu_moddifferentiationbfaces::rflu_computegradbfaceswrapper(), rflu_moddifferentiationcells::rflu_computegradcells_1d(), rflu_moddifferentiationcells::rflu_computegradcells_2d(), rflu_moddifferentiationcells::rflu_computegradcells_3d(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationcells::rflu_computegradcellsfast_2d(), rflu_moddifferentiationcells::rflu_computegradcellsfast_3d(), rflu_moddifferentiationcells::rflu_computegradcellswrapper(), rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_moddifferentiationfaces::rflu_computegradfaces(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_moddifferentiationfaces::rflu_computegradfaceswrapper(), rflu_computeintegral1oles(), rflu_computeintegral2oles(), rflu_computeintegral3oles(), rflu_computeintegral4oles(), rflu_computeintegral5oles(), rflu_computeintegralvalues(), rflu_modlimiters::rflu_computelimiterbarthjesp(), rflu_modlimiters::rflu_computelimitervenkat(), rflu_modgeometrytools::rflu_computelinecellxsectfast(), rflu_modgeometrytools::rflu_computelinecellxsectsafe(), rflu_modpatchutils::rflu_computepatchnormalsglobal(), rflu_modplottingvars::rflu_computeplottingvarscore(), rflu_modplottingvars::rflu_computeplottingvarsdisc(), rflu_modplottingvars::rflu_computeplottingvarsgraderr(), rflu_modplottingvars::rflu_computeplottingvarsvort(), rflu_modstencilsutils::rflu_computestencilsize(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_computevertexvariables(), rflu_modweights::rflu_computewtsbf2c(), rflu_modweights::rflu_computewtsbf2cwrapper(), rflu_modweights::rflu_computewtsc2c(), rflu_modweights::rflu_computewtsc2cwrapper(), rflu_modweights::rflu_computewtsf2c(), rflu_modweights::rflu_computewtsf2cwrapper(), rflu_modcentaur::rflu_convcentaur2rocflu(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_modconvertcv::rflu_convertcvcons2prim(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_modgambit::rflu_convgambit2rocflu(), rflu_modmesh3d::rflu_convmesh3d2rocflu(), rflu_modtetmesh::rflu_convrocflu2tetmesh(), rflu_modtetmesh::rflu_convtetmesh2rocflu(), rflu_modvgridns::rflu_convvgridns2rocflu(), rflu_modcopydata::rflu_copy_celldatap2s_r2d(), rflu_modcopydata::rflu_copy_celldatap2s_r3d(), rflu_modcopydata::rflu_copy_celldatas2p_r2d(), rflu_modgeometry::rflu_createapproxcentroids(), rflu_modfacelist::rflu_createavface2borderlist(), rflu_modfacelist::rflu_createavface2patchlist(), rflu_modboundlists::rflu_createbcellmlist(), rflu_modstencilsbfaces::rflu_createbf2cstencil(), rflu_modstencilsbfaces::rflu_createbf2cstencil_1d(), rflu_modstencilsbfaces::rflu_createbf2cstencilwrapper(), rflu_modboundlists::rflu_createbfaceloclists(), rflu_modboundlists::rflu_createbfacesortlists(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modboundlists::rflu_createbvertexmlist(), rflu_modstencilscells::rflu_createc2cstencil(), rflu_modstencilscells::rflu_createc2cstencil_1d(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modedgelist::rflu_createedge2celllist(), rflu_modedgelist::rflu_createedgelist(), rflu_modstencilsfaces::rflu_createf2cstencil(), rflu_modstencilsfaces::rflu_createf2cstencil_1d(), rflu_modstencilsfaces::rflu_createf2cstencilwrapper(), rflu_modgeometry::rflu_createfacedist(), rflu_modfacelist::rflu_createfacelist(), rflu_modforcesmoments::rflu_createforcesmoments(), rflu_modgatherdata::rflu_creategathereddata(), rflu_modgeometry::rflu_creategeometry(), rflu_modforcesmoments::rflu_createglobalthrustflags(), rflu_creategrid(), rflu_modhashtable::rflu_createhashtable(), rflu_modoles::rflu_createintegralsoles(), rflu_modlimiters::rflu_createlimiter(), rflu_modoctree::rflu_createoctree(), rflu_modpatchcoeffs::rflu_createpatchcoeffs(), rflu_modpatchutils::rflu_createpatchneighbormaps(), rflu_modplottingvars::rflu_createplottingvarmaps(), rflu_modplottingvars::rflu_createplottingvars(), rflu_modplottingvars::rflu_createplottingvarsvert(), rflu_modregionmapping::rflu_createregionmapping(), rflu_createregions(), rflu_modsplittree::rflu_createsplittree(), rflu_modoles::rflu_createstencilsweightsoles(), rflu_modstencilsvert::rflu_createstencilvert2cell(), rflu_modvertexlists::rflu_createvert2celllist(), rflu_modweights::rflu_createwtsbf2c(), rflu_modweights::rflu_createwtsbf2cwrapper(), rflu_modweights::rflu_createwtsc2c(), rflu_modweights::rflu_createwtsc2cwrapper(), rflu_modweights::rflu_createwtsf2c(), rflu_modweights::rflu_createwtsf2cwrapper(), rflu_modoles::rflu_deallocatedcuhrearrays(), rflu_deallocatedcuhrearrays(), rflu_deallocatememory(), rflu_moddeallocatememory::rflu_deallocatememorygspeeds(), rflu_moddeallocatememory::rflu_deallocatememorysolcv(), rflu_moddeallocatememory::rflu_deallocatememorysoldv(), rflu_moddeallocatememory::rflu_deallocatememorysolgv(), rflu_moddeallocatememory::rflu_deallocatememorysoltv(), rflu_moddeallocatememory::rflu_deallocatememorytstep(), rflu_moddeallocatememory::rflu_deallocatememorytstep_c(), rflu_moddeallocatememory::rflu_deallocatememorytstep_i(), rflu_deallocatememoryvert(), rflu_modrenumberlist::rflu_denumberlist(), rflu_derivedinputvalues(), rflu_modgeometry::rflu_destroyapproxcentroids(), rflu_modfacelist::rflu_destroyavface2borderlist(), rflu_modfacelist::rflu_destroyavface2patchlist(), rflu_modboundlists::rflu_destroybcellmlist(), rflu_modstencilsbfaces::rflu_destroybf2cstencil(), rflu_modstencilsbfaces::rflu_destroybf2cstencil_1d(), rflu_modstencilsbfaces::rflu_destroybf2cstencilwrapper(), rflu_modboundlists::rflu_destroybfaceloclists(), rflu_modboundlists::rflu_destroybfacesortlists(), rflu_modboundlists::rflu_destroybvertexlists(), rflu_modboundlists::rflu_destroybvertexmlist(), rflu_modstencilscells::rflu_destroyc2cstencil(), rflu_modstencilscells::rflu_destroyc2cstencil_1d(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), rflu_modfacelist::rflu_destroycell2facelist(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modedgelist::rflu_destroyedge2celllist(), rflu_modedgelist::rflu_destroyedgelist(), rflu_modstencilsfaces::rflu_destroyf2cstencil(), rflu_modstencilsfaces::rflu_destroyf2cstencil_1d(), rflu_modstencilsfaces::rflu_destroyf2cstencilwrapper(), rflu_modgeometry::rflu_destroyfacedist(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modforcesmoments::rflu_destroyforcesmoments(), rflu_modgatherdata::rflu_destroygathereddata(), rflu_modgeometry::rflu_destroygeometry(), rflu_modforcesmoments::rflu_destroyglobalthrustflags(), rflu_destroygrid(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modlimiters::rflu_destroylimiter(), rflu_modstencilscells::rflu_destroylistcc2cstencil(), rflu_modstencilsfaces::rflu_destroylistcf2cstencil(), rflu_modoctree::rflu_destroyoctree(), rflu_modpatchcoeffs::rflu_destroypatchcoeffs(), rflu_modpatchutils::rflu_destroypatchneighbormaps(), rflu_modplottingvars::rflu_destroyplottingvarmaps(), rflu_modplottingvars::rflu_destroyplottingvars(), rflu_modplottingvars::rflu_destroyplottingvarsvert(), rflu_modregionmapping::rflu_destroyregionmapping(), rflu_modsplittree::rflu_destroysplittree(), rflu_modoles::rflu_destroystencilsweightsoles(), rflu_modstencilsvert::rflu_destroystencilvert2cell(), rflu_modvertexlists::rflu_destroyvert2celllist(), rflu_modweights::rflu_destroywtsbf2c(), rflu_modweights::rflu_destroywtsbf2cwrapper(), rflu_modweights::rflu_destroywtsc2c(), rflu_modweights::rflu_destroywtsc2cwrapper(), rflu_modweights::rflu_destroywtsf2c(), rflu_modweights::rflu_destroywtsf2cwrapper(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_endflowsolver(), rflu_modensight::rflu_ens_builddatainfo(), rflu_modensight::rflu_ens_closefilegeometry(), rflu_modensight::rflu_ens_closefilescalarvector(), rflu_modensight::rflu_ens_destroydatainfo(), rflu_modensight::rflu_ens_openfilegeometry(), rflu_modensight::rflu_ens_openfilescalarvector(), rflu_modensight::rflu_ens_writefilecase(), rflu_modensightutils::rflu_ens_writegrid(), rflu_modextractflowdata::rflu_extractflowdatablasius(), rflu_modextractflowdata::rflu_extractflowdatalinefarf(), rflu_modextractflowdata::rflu_extractflowdatanscbc(), rflu_modextractflowdata::rflu_extractflowdataproudman(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modextractflowdata::rflu_extractflowdatasod(), rflu_modextractflowdata::rflu_extractflowdatasommspi(), rflu_modextractflowdata::rflu_extractflowdatastg1d(), rflu_modextractflowdata::rflu_extractflowdatastg2d(), rflu_modextractflowdatautils::rflu_extractshocklocation1d(), rflu_modprobes::rflu_findprobecells(), rflu_finishsd(), rflu_flowsolver(), rflu_flowsolverdummy(), rflu_modgatherdata::rflu_gatherdata(), rflu_modrocstaradmin::rflu_genx_closerocinctrlfiles(), rflu_modrocstario::rflu_genx_closerocinctrlfiles(), rflu_modrocstartools::rflu_genx_constraindisp(), rflu_modrocstaradmin::rflu_genx_createdatainterf(), rflu_modrocstaradmin::rflu_genx_creategridsurf(), rflu_modrocstaradmin::rflu_genx_createpconn(), rflu_modrocstario::rflu_genx_decidereadfile(), rflu_modrocstario::rflu_genx_decidewritefile(), rflu_modrocstaradmin::rflu_genx_destroydatainterf(), rflu_modrocstaradmin::rflu_genx_destroygridsurf(), rflu_modrocstaradmin::rflu_genx_destroypconn(), rflu_modrocstario::rflu_genx_getdimensions(), rflu_modrocstartools::rflu_genx_initbflag(), rflu_modrocstartools::rflu_genx_movegrid(), rflu_modrocstario::rflu_genx_openrocinctrlfiles(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modrocstario::rflu_genx_readwindow(), rflu_modrocstaradmin::rflu_genx_storenameshandles(), rflu_getboundaryvalues(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_getcvloc(), rflu_modcellfaceedgeinfo::rflu_getedgekind(), rflu_modcellfaceedgeinfo::rflu_getfacekind(), rflu_modcellfaceedgeinfo::rflu_getglobalcellkind(), rflu_modcellfaceedgeinfo::rflu_getglobalcelltype(), rflu_modfacelist::rflu_getopposingfaces(), rflu_modregionmapping::rflu_getproclocregids(), rflu_modresidual::rflu_getresidualsupport1(), rflu_modresidual::rflu_getresidualsupport2(), rflu_getspecialcells(), rflu_modhashtable::rflu_hashedge(), rflu_modhashtable::rflu_hashface(), rflu_modhashtable::rflu_hashvertex(), rflu_modhashtable::rflu_hashvertexfancy(), rflu_modhllcflux::rflu_hllc_computeflux(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_modincelltest::rflu_ict_testfaceplanar(), rflu_modincelltest::rflu_ict_testincell(), rflu_modincelltest::rflu_ict_testincellfancy(), rflu_modincelltest::rflu_ict_testincelllohner(), rflu_initbcdatahardcode(), rflu_initflowhardcode(), rflu_initflowhardcodelim(), rflu_initflowhardcodelimwrapper(), rflu_initflowhardcodewrapper(), rflu_initflowscratch(), rflu_initflowsolver(), rflu_modfacelist::rflu_insertintocell2facelist(), rflu_modinterpolation::rflu_interpcells2face(), rflu_modinterpolation::rflu_interpcells2facepatch(), rflu_modinterpolation::rflu_interpcells2faces(), rflu_modinterpolation::rflu_interpcells2verts(), rflu_interpolatewrapper(), rflu_invertmatrixsvd(), rflu_modlimiters::rflu_limitgradcellssimple(), rflu_modmergeregions::rflu_merg_mergegrid(), rflu_mergepostprocessregions(), rflu_minimumtimestep(), rflu_movegriddisp(), rflu_movegridwrapper(), rflu_movegridxyz(), rflu_modmpi::rflu_mpi_clearrequest(), rflu_modmpi::rflu_mpi_copycelldata(), rflu_modmpi::rflu_mpi_copywrapper(), rflu_modmpi::rflu_mpi_createbufferipclsend(), rflu_modmpi::rflu_mpi_createbuffers(), rflu_modmpi::rflu_mpi_destroybufferipclsend(), rflu_modmpi::rflu_mpi_destroybuffers(), rflu_modmpi::rflu_mpi_isendcelldata(), rflu_modmpi::rflu_mpi_recreatebufferipclsend(), rflu_modmpi::rflu_mpi_recvcelldata(), rflu_modmpi::rflu_mpi_settag(), rflu_modmpi::rflu_mpi_settagswrapper(), rflu_modnscbc::rflu_nscbc_comprhs(), rflu_modnscbc::rflu_nscbc_comprhsff(), rflu_modnscbc::rflu_nscbc_comprhsifveltemp(), rflu_modnscbc::rflu_nscbc_comprhsof(), rflu_modnscbc::rflu_nscbc_initff(), rflu_modnscbc::rflu_nscbc_initiftotang(), rflu_modnscbc::rflu_nscbc_initifveltemp(), rflu_modnscbc::rflu_nscbc_initof(), rflu_modnscbc::rflu_nscbc_initsw(), rflu_openconverfile(), rflu_modpatchcoeffs::rflu_openpatchcoeffsascii(), rflu_modpatchcoeffs::rflu_openpatchcoeffsbinary(), rflu_openpostinfo(), rflu_modprobes::rflu_openprobefiles(), rflu_modregionmapping::rflu_openregionmappingfile(), rflu_openrestartinfo(), rflu_openstatsfileoles(), rflu_opentotalmassfile(), rflu_modpartitionregion::rflu_part_addvirtualcells(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv1(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_modpartitionregion::rflu_part_buildborderfacelist(), rflu_modpartitionregion::rflu_part_buildcelllists(), rflu_modpartitionregion::rflu_part_buildpatchlists(), rflu_modpartitionregion::rflu_part_buildvertexdata(), rflu_modpartitionregion::rflu_part_buildvertexlists(), rflu_modpartitionregion::rflu_part_createcelllists(), rflu_modpartitionregion::rflu_part_createpatchlists(), rflu_modpartitionregion::rflu_part_createreg2cellmap(), rflu_modpartitionregion::rflu_part_destroyborderfacelist(), rflu_modpartitionregion::rflu_part_destroycelldata(), rflu_modpartitionregion::rflu_part_destroycelllists(), rflu_modpartitionregion::rflu_part_destroypatchlists(), rflu_modpartitionregion::rflu_part_destroyvertexdata(), rflu_modpartitionregion::rflu_part_partitionregion(), rflu_modpartitionregion::rflu_part_recreatecelllist(), rflu_modpetscpoisson::rflu_petsc_buildpoisson(), rflu_modpetscnewtonkrylov::rflu_petsc_createapplicationordering(), rflu_modpetscnewtonkrylov::rflu_petsc_createcoloring(), rflu_modpetscpoisson::rflu_petsc_createpoisson(), rflu_modpetscadmin::rflu_petsc_finalize(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidual(), rflu_modpetscadmin::rflu_petsc_init(), rflu_modpetscpoisson::rflu_petsc_setsolverpoisson(), rflu_modpetscpoisson::rflu_petsc_solvepressurepoisson(), rflu_pickspecialcells(), rflu_pickspecialfaces(), rflu_postprocessregions(), rflu_printchangeinfo(), rflu_printflowinfo(), rflu_printlocinfo(), rflu_modprobes::rflu_printprobeinfo(), rflu_printwriteconvergence(), rflu_putboundaryvalues(), rflu_putboundaryvaluesalpha(), rflu_randominit(), rflu_modreadwritebcdatafile::rflu_readbcdatafile(), rflu_modreadbcinputfile::rflu_readbcfarfsection(), rflu_modreadbcinputfile::rflu_readbcinflowtotangsection(), rflu_modreadbcinputfile::rflu_readbcinflowveltempsection(), rflu_modreadbcinputfile::rflu_readbcinjectsection(), rflu_modreadbcinputfile::rflu_readbcinputfile(), rflu_modreadbcinputfile::rflu_readbcnoslipwallheatsect(), rflu_modreadbcinputfile::rflu_readbcnoslipwalltempsect(), rflu_modreadbcinputfile::rflu_readbcoutflowsection(), rflu_modreadbcinputfile::rflu_readbcperiodicsection(), rflu_modreadbcinputfile::rflu_readbcslipwallsection(), rflu_modreadbcinputfile::rflu_readbcsymmetrysection(), rflu_modreadbcinputfile::rflu_readbcvirtualsection(), rflu_readconvgridwrapper(), rflu_moddimensions::rflu_readdimensions(), rflu_modreadwriteflow::rflu_readflowascii(), rflu_modreadwriteflow::rflu_readflowbinary(), rflu_modreadwriteflow::rflu_readflowwrapper(), rflu_modreadwritegrid::rflu_readgridascii(), rflu_modreadwritegrid::rflu_readgridbinary(), rflu_modcentaur::rflu_readgridcentaurascii(), rflu_modcentaur::rflu_readgridcentaurbinary(), rflu_modcobalt::rflu_readgridcobalt(), rflu_modgambit::rflu_readgridgambitneutral(), rflu_modmesh3d::rflu_readgridmesh3d(), rflu_modreadwritegridspeeds::rflu_readgridspeedsascii(), rflu_modreadwritegridspeeds::rflu_readgridspeedsbinary(), rflu_modreadwritegridspeeds::rflu_readgridspeedswrapper(), rflu_modtetmesh::rflu_readgridtetmesh(), rflu_modvgridns::rflu_readgridvgridns(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_readintegrals1245oles(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modpatchcoeffs::rflu_readpatchcoeffsascii(), rflu_modpatchcoeffs::rflu_readpatchcoeffsbinary(), rflu_modpatchcoeffs::rflu_readpatchcoeffswrapper(), rflu_readpostinfo(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_readstat(), rflu_readtbcinputfile(), rflu_readtbcsection(), rflu_modrelatedpatches::rflu_relp_periodicwrapper(), rflu_modrelatedpatches::rflu_relp_symmetrywrapper(), rflu_modrelatedpatches::rflu_relp_transformvector(), rflu_modrelatedpatches::rflu_relp_transformwrapper(), rflu_modrenumberlist::rflu_renumberlist(), rflu_modrenumberlist::rflu_renumberlist2(), rflu_modresidual::rflu_res_computeresidual(), rflu_residualnorm(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap2d(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap3d(), rflu_modrenumberings::rflu_rnmb_buildsc2pcmap(), rflu_modrenumberings::rflu_rnmb_buildsv2pvmap(), rflu_modrenumberings::rflu_rnmb_createpbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_createpc2scmap(), rflu_modrenumberings::rflu_rnmb_createpv2svmap(), rflu_modrenumberings::rflu_rnmb_createsc2rmap(), rflu_modrenumberings::rflu_rnmb_destroypbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_destroypc2scmap(), rflu_modrenumberings::rflu_rnmb_destroypv2svmap(), rflu_modrenumberings::rflu_rnmb_destroysbc2pcmap(), rflu_modrenumberings::rflu_rnmb_destroysc2pcmap(), rflu_modrenumberings::rflu_rnmb_destroysc2rmap(), rflu_modrenumberings::rflu_rnmb_destroysv2pvmap(), rflu_modrenumberings::rflu_rnmb_readpxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_readsc2rmap(), rflu_modrenumberings::rflu_rnmb_writepxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_writesc2rmap(), rflu_modroeflux::rflu_roe_computeflux(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxc2_tcp(), rflu_scalarcheckpositivity(), rflu_modconvertcv::rflu_scalarconvertcvcons2prim(), rflu_modconvertcv::rflu_scalarconvertcvprim2cons(), rflu_scalarfirst(), rflu_scalarfirstpatch(), rflu_scalarsecond(), rflu_scalarsecondpatch(), rflu_modgatherdata::rflu_scattergathereddata(), rflu_setdependentvars(), rflu_setderiveduserinput(), rflu_setgasvars(), rflu_modforcesmoments::rflu_setglobalthrustflags(), rflu_modgridspeedutils::rflu_setgridspeedscalefactor(), rflu_modstencilsbfaces::rflu_setinfobf2cstencilwrapper(), rflu_modstencilscells::rflu_setinfoc2cstencilwrapper(), rflu_modstencilsfaces::rflu_setinfof2cstencilwrapper(), rflu_setmovegridoptions(), rflu_setpatchplotflags(), rflu_settransportvars(), rflu_setvarinfo(), rflu_modstl::rflu_stl_writesurfgridascii(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcells(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv1(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2(), rflu_modsymmetryperiodic::rflu_sype_augmentcelllists(), rflu_modsymmetryperiodic::rflu_sype_augmentvertexlists(), rflu_modsymmetryperiodic::rflu_sype_buildp2vclist(), rflu_modsymmetryperiodic::rflu_sype_buildp2vclistserial(), rflu_modsymmetryperiodic::rflu_sype_buildtransforms(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modsymmetryperiodic::rflu_sype_createp2vclist(), rflu_modsymmetryperiodic::rflu_sype_createvertexmaps(), rflu_modsymmetryperiodic::rflu_sype_destroyp2vclist(), rflu_modsymmetryperiodic::rflu_sype_getactualserialcell(), rflu_modsymmetryperiodic::rflu_sype_getrelatedvertex(), rflu_modsymmetryperiodic::rflu_sype_imposevertexmap(), rflu_modsymmetryperiodic::rflu_sype_readtransforms(), rflu_modsymmetryperiodic::rflu_sype_setsypepatchesflag(), rflu_modsymmetryperiodic::rflu_sype_writetransforms(), rflu_modtecplot::rflu_tec_builddatafieldsurf(), rflu_modtecplot::rflu_tec_builddatafieldvol(), rflu_modtecplot::rflu_tec_builddatapatch(), rflu_modtecplot::rflu_tec_builddatapatchstats(), rflu_modtecplot::rflu_tec_buildheaderfield(), rflu_modtecplotutils::rflu_tec_closefile(), rflu_modtecplot::rflu_tec_closefilefield(), rflu_modtecplot::rflu_tec_closefilepatch(), rflu_modtecplot::rflu_tec_closefilepatchstats(), rflu_modtecplot::rflu_tec_closefilepnt(), rflu_modtecplot::rflu_tec_destroydatafieldsurf(), rflu_modtecplot::rflu_tec_destroydatafieldvol(), rflu_modtecplot::rflu_tec_destroydatapatch(), rflu_modtecplotutils::rflu_tec_openfile(), rflu_modtecplot::rflu_tec_openfilefield(), rflu_modtecplot::rflu_tec_openfilepatch(), rflu_modtecplot::rflu_tec_openfilepatchstats(), rflu_modtecplot::rflu_tec_openfilepnt(), rflu_modtecplotutils::rflu_tec_writezonecellsspecial(), rflu_modtecplotutils::rflu_tec_writezonefacesspecial(), rflu_modtecplotutils::rflu_tec_writezoneinterf(), rflu_modtecplotutils::rflu_tec_writezonesurf(), rflu_modtecplotutils::rflu_tec_writezonesurfmixed(), rflu_modtecplotutils::rflu_tec_writezonevol(), rflu_modboundarytests::rflu_testisboundarycell(), rflu_timestepinviscid(), rflu_timestepviscous(), rflu_modtimezoom::rflu_timezoomcomputebulkvars(), rflu_modtimezoom::rflu_timezoomsumresiduals(), rflu_modthrustspecimpulse::rflu_tsi_closeglobalvals(), rflu_modthrustspecimpulse::rflu_tsi_openglobalvals(), rflu_modhashtable::rflu_unhashbface(), rflu_user_enforcepatchcoords(), rflu_modviscousflux::rflu_viscousfluxes(), rflu_modviscousflux::rflu_viscousfluxespatches(), rflu_modweno::rflu_wenogradcells_2d(), rflu_modweno::rflu_wenogradcells_3d(), rflu_modweno::rflu_wenogradcellswrapper(), rflu_modweno::rflu_wenogradcellsxyz_1d(), rflu_modweno::rflu_wenogradcellsxyz_2d(), rflu_modweno::rflu_wenogradcellsxyz_3d(), rflu_modweno::rflu_wenogradcellsxyzfast_2d(), rflu_modweno::rflu_wenogradcellsxyzfast_3d(), rflu_modweno::rflu_wenogradcellsxyzwrapper(), rflu_modreadwritebcdatafile::rflu_writebcdatafile(), rflu_moddimensions::rflu_writedimensions(), rflu_moddimensions::rflu_writedimensionsborders(), rflu_modreadwriteflow::rflu_writeflowascii(), rflu_modreadwriteflow::rflu_writeflowbinary(), rflu_modreadwriteflow::rflu_writeflowwrapper(), rflu_modforcesmoments::rflu_writeglobalforcesmoments(), rflu_modreadwritegrid::rflu_writegridascii(), rflu_modreadwritegrid::rflu_writegridbinary(), rflu_modreadwritegridspeeds::rflu_writegridspeedsascii(), rflu_modreadwritegridspeeds::rflu_writegridspeedsbinary(), rflu_modreadwritegridspeeds::rflu_writegridspeedswrapper(), rflu_modreadwritegrid::rflu_writegridwrapper(), rflu_writeintegrals1245oles(), rflu_modcellmapping::rflu_writeloc2globcellmapping(), rflu_modextractflowdata::rflu_writemeshbump(), rflu_modpatchcoeffs::rflu_writepatchcoeffswrapper(), rflu_writestat(), rflu_modtetmesh::rflu_writesurfgridtetmesh(), rflu_writeversionstring(), rfluconv(), rfluinit(), rflumap(), rflupost(), rkinitgeneric(), rkinitmp(), rkinitpointscalar(), rkupdategeneric(), rkupdatepointscalar(), rocflo_2dto3d(), rocflo_blocks(), rocflo_init(), rocflo_post(), rocflo_split(), rocflo_surf(), rocflo_toflu(), rocpart_post(), rocvav_post(), rvav_blasiussolution(), rvav_computeanalyticalsolution(), rvav_gammbumpsolution(), rvav_proudmanculicksolution(), rvav_readcomparisonssection(), rvav_readfilestream1(), rvav_readfilestream2analyt(), rvav_readfilestream2comput(), rvav_readfilestream2experm(), rvav_readinputfile(), scalegridspeeds(), spec_checkuserinput(), spec_derivedinputvalues(), spec_eqeulcorr(), spec_eqeulcorrpatch(), spec_printuserinput(), spec_readinputfile(), spec_rflu_allocatememoryeev(), spec_rflu_allocatememorysol(), spec_rflu_allocatememorytstep(), spec_rflu_allocatememoryvert(), spec_rflu_deallocatememoryeev(), spec_rflu_deallocatememorysol(), spec_rflu_deallocatememorytstep(), spec_rflu_deallocatememoryvert(), spec_rflu_initflowhardcode(), spec_rflu_modchemistry::spec_rflu_integratechemsrcterm(), spec_rflu_printflowinfo(), spec_rflu_readbcfarfsection(), spec_rflu_readbcinflowsection(), spec_rflu_readbcinjectsection(), spec_rflu_readbcinputfile(), spec_rflu_readbcsectiondummy(), spec_rflu_modreadwritevars::spec_rflu_readcvascii(), spec_rflu_modreadwritevars::spec_rflu_readcvbinary(), spec_rflu_modreadwritevars::spec_rflu_readeevascii(), spec_rflu_modreadwritevars::spec_rflu_readeevbinary(), spec_rflu_seteev(), spec_rflu_modreadwritevars::spec_rflu_writecvascii(), spec_rflu_modreadwritevars::spec_rflu_writecvbinary(), spec_rflu_modreadwritevars::spec_rflu_writeeevascii(), spec_rflu_modreadwritevars::spec_rflu_writeeevbinary(), splitgrid(), splitquadface(), modstatsroutines::statmapping(), tedgestr(), turb_allocatememory(), turb_calcmetrics(), turb_checkparaminput(), turb_coranswalldistov(), turb_coviscousfluxes(), turb_cowlmreadbcsection(), turb_derivedinputvalues(), turb_flolesaverageface(), turb_floransbcondinjection(), turb_floransbcondnoslipwall(), turb_floransexchangedummyconf(), turb_floransrecvcornedgecells(), turb_floransrecvdummyvals(), turb_floranssacentfluxpatch(), turb_floranssaroefluxpatch(), turb_floranssendcornedgecells(), turb_floranssenddummyconf(), turb_flucv2cons(), turb_flucv2prim(), turb_getmodelstresscell(), turb_gettvcell(), turb_initgenxinterface(), turb_initinputvalues(), turb_initsolution(), turb_lescalceddyvis(), turb_lescoefdynmixd(), turb_lescoefdynsmag(), turb_lescommunication(), turb_lesfluxscalsim(), turb_lesgeteddyvis(), turb_lesmovegrid(), turb_readbcinputfile(), turb_readinputfile(), turb_rflo_ransallocdatabuffers(), turb_rflo_ransbndconditionssend(), turb_rflo_ransbndconditionsset(), turb_rflo_ransclearsendrequests(), turb_rflo_readsolution(), turb_rflo_readsolutionregion(), turb_rflo_writesolution(), turb_modpostflu::turb_rflu_allocmempost(), turb_modpostflu::turb_rflu_allocmempostvert(), turb_modpostflu::turb_rflu_deallocmempost(), turb_modpostflu::turb_rflu_deallocmempostvert(), turb_rflu_modrocstaradmin::turb_rflu_genxregisterdata(), turb_rflu_readsolutionascii(), turb_rflu_readsolutionbinary(), turb_rflu_writesolutionascii(), turb_rflu_writesolutionbinary(), turb_statccollector(), turb_statmapping(), turb_vfluxhybridpatch(), turb_visfluxeddypatch(), turb_wlminitia(), turb_wlmreyanalogy(), turb_wlmtauwallmapping(), updatetbc(), viscousfluxesmp(), prep_modbcdistribution::writebctofile(), writeconvergence(), writeflucellmap(), writefludimens(), writeflugrid(), writegeneric(), writeprobe(), writesurfacegrid(), writetecplotascii(), writetecplotbinary(), and writethrust().
subroutine registerfunction (type(t_global), pointer global, character(*) funName, character(*) fileName)
Definition at line 449 of file ModError.F90.
References errorstop().
Referenced by afterupdatemp(), allocatememorywork(), prep_modbcdistribution::bcdistributionfiles(), prep_modbcdistribution::bcfarfdistrib(), prep_modbcdistribution::bcinflowtotangdistrib(), prep_modbcdistribution::bcinflowveldistrib(), prep_modbcdistribution::bcinjectdistrib(), prep_modbcdistribution::bcnoslipdistrib(), prep_modbcdistribution::bcoutflowdistrib(), prep_modbcdistribution::bcslipwalldistrib(), buildfilenamebasic(), modbuildfilenames::buildfilenamebasic(), buildfilenameplain(), modbuildfilenames::buildfilenameplain(), modbuildfilenames::buildfilenameplainsteady(), modbuildfilenames::buildfilenameplainunsteady(), buildfilenamesteady(), modbuildfilenames::buildfilenamesteady(), buildfilenameunsteady(), modbuildfilenames::buildfilenameunsteady(), modbuildfilenames::buildregionidstring(), cellgradientsmp(), checkbcvalidity(), convectivefluxes(), convectivefluxesmp(), convertflo2flumesh(), convertflo2flupatch(), correctnedges(), countinteractingpatches(), descalegridspeeds(), explicitmultistage(), fluid_posthdfoutput(), fluid_prehdfoutput(), function(), genxinitsolution(), genxstatnaming(), genxwriterocinout(), genxwritesolution(), getbndverttype(), getgrid(), modstatsroutines::getstatistics(), globalcommunicationmp(), initcommunicationmp(), initializeflowfield(), initinputvalues(), modstatsroutines::initstatistics(), inrt_allocateauxillary(), inrt_augmentconsources(), inrt_augmentdissources(), inrt_burnstatusupdate(), inrt_calcburning(), inrt_calcdrag(), inrt_calcheattransfernonburn(), inrt_calcscouring(), inrt_checkuserinput(), inrt_computemaxedges(), inrt_defineboilingregulation(), inrt_defineburning(), inrt_definedrag(), inrt_defineheattransfernonburn(), inrt_definescouring(), inrt_determinetokens(), inrt_finishmomentumedge(), inrt_initialize(), inrt_printmaterialinput(), inrt_printuserinput(), inrt_readboilingregulation(), inrt_readburning(), inrt_readdefaultsection(), inrt_readdrag(), inrt_readheattransfernonburn(), inrt_readinputfile(), inrt_readmaterialinput(), inrt_readscouring(), inrt_setactiveness(), inrt_setmaterial(), inrt_setparticletemp(), inrt_setpermission(), inrt_sourceterms(), inrt_twodimaverage(), inrt_userinput(), inrt_vaporenergyconversion(), integratesourcetermsmp(), mixtureproperties(), numericaldissipation(), numericaldissipationmp(), peri_allocatememory(), peri_checkparaminput(), peri_cnlforceterm(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_cocprslowterms(), peri_copgradupdate(), peri_derivedinputvalues(), peri_initinputvalues(), peri_initsolution(), peri_printuserinput(), peri_readinputfile(), peri_readperisection(), peri_rflu_deallocatememory(), peri_solutionupdate(), peri_sourceterms(), peri_userinput(), peul_allocatedatabuffers(), peul_allocatememory(), peul_bcondinflow(), peul_bcondinjection(), peul_bcondoutflow(), peul_bcondslipwall(), peul_bcondsymmetry(), peul_boundaryconditionsrecv(), peul_boundaryconditionssend(), peul_boundaryconditionsset(), peul_centraldissipation(), peul_centralflux(), peul_centralfluxpatch(), peul_clearsendrequests(), peul_convectivefluxes(), peul_correctcorneredgecells(), peul_derivedinputvalues(), peul_enforcepositivity(), peul_exchangecorneredgecells(), peul_exchangedummyconf(), peul_initgenxinterface(), peul_initinputvalues(), peul_initsolution(), peul_printuserinput(), peul_readbcfarfsection(), peul_readbcinflowsection(), peul_readbcinjectsection(), peul_readbcinputfile(), peul_readconpartptypesection(), peul_readconpartsection(), peul_readinputfile(), peul_readsolution(), peul_readsolutionregion(), peul_receivecorneredgecells(), peul_receivedummyvals(), peul_residualsmoothing(), peul_residualsmoothingcoeffs(), peul_rocflo_post(), peul_sendcorneredgecells(), peul_senddummyconf(), peul_setcorneredgecells(), peul_sourceeqeul(), peul_sourceterms(), peul_spectralradii(), peul_userinput(), peul_writesolution(), plag_allocatedatabuffers(), plag_allocatememory(), plag_allocatememorypost(), plag_allocatememorytile(), plag_appenddatafrombuffers(), plag_binsortnozzleinlet(), plag_binsortspatialdist(), plag_boundaryconditionsset(), plag_bufferdatarecv(), plag_bufferdatasend(), plag_buffersizerecv(), plag_buffersizesend(), plag_calcbreakup(), plag_calcderivedvariables(), plag_modeulerian::plag_calceulerianfield(), plag_calcfacecentroids(), plag_moddimensions::plag_calcnpclsglobal(), plag_calcrhsposition(), plag_cecellsallocatedata(), plag_cecellsclearrequestsdata(), plag_cecellsclearrequestssize(), plag_cecellsdeallocatedata(), plag_cecellsexchange(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_cecellsgetbuffersize(), plag_cecellsloaddatawrapper(), plag_cecellsrecvdata(), plag_cecellsrecvsize(), plag_cecellssenddata(), plag_cecellssendrecvwrapper(), plag_cecellssendsize(), plag_cecellswrapper(), plag_modcheckvars::plag_checkpositivity(), plag_checkuserinput(), plag_modcheckvars::plag_checkvalidity(), plag_cleardatasendrequests(), plag_clearsizesendrequests(), plag_modsurfstats::plag_closesurfstats(), plag_modreallocatememory::plag_copydimensions(), plag_copyfacevectors(), plag_modreallocatememory::plag_copymemory(), plag_corncellsloaddata(), plag_corncellsloadsendbuff(), plag_modeulerian::plag_createeulerianfield(), plag_modstats::plag_createstat(), plag_modsurfstats::plag_createsurfstats(), plag_modsurfstats::plag_createsurfstatskernel(), plag_deallocatedatabuffers(), plag_deallocatememorypost(), plag_modreallocatememory::plag_decidereallocmem(), plag_derivedinputvalues(), plag_modeulerian::plag_destroyeulerianfield(), plag_modstats::plag_destroystat(), plag_modsurfstats::plag_destroysurfstats(), plag_modsurfstats::plag_destroysurfstatskernel(), plag_moddatastruct::plag_dstr_buildcell2pcllist(), plag_moddatastruct::plag_dstr_copyparticle(), plag_moddatastruct::plag_dstr_copyparticlewrapper(), plag_moddatastruct::plag_dstr_createcell2pcllist(), plag_moddatastruct::plag_dstr_createpcllistcsr(), plag_moddatastruct::plag_dstr_destroycell2pcllist(), plag_moddatastruct::plag_dstr_destroypcllistcsr(), plag_moddatastruct::plag_dstr_mergeparticlewrapper(), plag_moddatastruct::plag_dstr_recreatecell2pcllist(), plag_edgecellsloaddata(), plag_edgecellsloadsendbuff(), plag_modinjection::plag_ejectparticle(), plag_modsurfstats::plag_gathersurfstats(), plag_getcellindices(), plag_getcellindicesoutflow(), plag_incelltest(), plag_incelltestrobust(), plag_modeulerian::plag_initeulerianfield(), plag_initgenxinterface(), plag_initinputvalues(), plag_initmemory(), plag_initpatchdata(), plag_initsolution(), plag_modstats::plag_initstat(), plag_modsurfstats::plag_initsurfstats(), plag_injcejectparticle(), plag_injcmakeparticle(), plag_injcsetinjection(), plag_modinjection::plag_injcsetpoolpos(), plag_injctilecalcrhs(), plag_injctileinitialize(), plag_modrkinit::plag_injctilerkinit(), plag_injctilerkupdate(), plag_injctileupdate(), plag_injctilezerorhs(), plag_inrt_allocmemtstep(), plag_inrt_deallocmemtstep(), plag_intrpmixtproperties(), plag_modinjection::plag_invokeconsrandejec(), plag_modinjection::plag_invokeejecmodel1(), plag_noncvupdate(), plag_modsurfstats::plag_nullifysurfstats(), plag_modsurfstats::plag_opensurfstatsascii(), plag_modsurfstats::plag_opensurfstatsbinary(), plag_patchbuffersendrecv(), plag_patchexchangeconf(), plag_patchgetbuffersize(), plag_patchloaddatabuffers(), plag_patchremovedataoutflow(), plag_patchupdate(), plag_patchupdatewrapper(), plag_moddimensions::plag_printdimensions(), plag_moddimensions::plag_printnpclsglobal(), plag_printuserinput(), plag_processeulerfield(), plag_readdispartinitsection(), plag_readdispartncontsection(), plag_readdispartsection(), plag_readinputfile(), plag_readpdffromfile(), plag_readsolution(), plag_readsolutionfilepost(), plag_readstatpost(), plag_modsurfstats::plag_readsurfstatsascii(), plag_modsurfstats::plag_readsurfstatsbinary(), plag_modsurfstats::plag_readsurfstatskernelascii(), plag_modsurfstats::plag_readsurfstatskernelbinary(), plag_modsurfstats::plag_readsurfstatswrapper(), plag_modreallocatememory::plag_reallocmem(), plag_modreallocatememory::plag_reallocmemwrapper(), plag_rflo_modstats::plag_rflo_clearreqstatbuff(), plag_rflo_clearsendrequests(), plag_rflo_modstats::plag_rflo_commstatbuffwrapper(), plag_rflo_modstats::plag_rflo_copystatbuff(), plag_rflo_modstats::plag_rflo_createstatbuff(), plag_rflo_findgridmapping(), plag_rflo_findsourcecell(), plag_rflo_modstats::plag_rflo_readstat(), plag_rflo_recvmetrics(), plag_rflo_modstats::plag_rflo_recvstatbuff(), plag_rflo_modstats::plag_rflo_recvstatbuffwrapper(), plag_rflo_sendmetrics(), plag_rflo_sendrecvmetrics(), plag_rflo_modstats::plag_rflo_sendstatbuffconf(), plag_rflo_modstats::plag_rflo_sendstatbuffwrapper(), plag_rflo_setmetrics(), plag_rflo_sourcecell(), plag_rflo_modstats::plag_rflo_writestat(), plag_rflu_allocmemsol(), plag_rflu_allocmemsoltile(), plag_rflu_allocmemtstep(), plag_rflu_allocmemtsteptile(), plag_rflu_modcomm::plag_rflu_clearrequest(), plag_rflu_modcomm::plag_rflu_clearrequestwrapper(), plag_rflu_modcomm::plag_rflu_commdriver(), plag_rflu_modfindcells::plag_rflu_computedisttot(), plag_rflu_modcomm::plag_rflu_copycounters(), plag_rflu_modcomm::plag_rflu_copydata(), plag_rflu_modcomm::plag_rflu_copydataint(), plag_rflu_modcomm::plag_rflu_copydatareal(), plag_rflu_correctmixtproperties(), plag_rflu_modcomm::plag_rflu_createbuffersrecv(), plag_rflu_modcomm::plag_rflu_createbufferssend(), plag_rflu_deallocmemsol(), plag_rflu_deallocmemsoltile(), plag_rflu_deallocmemtstep(), plag_rflu_deallocmemtsteptile(), plag_rflu_modcomm::plag_rflu_destroybuffersrecv(), plag_rflu_modcomm::plag_rflu_destroybufferssend(), plag_rflu_modfindcells::plag_rflu_findcellsbrute(), plag_rflu_modfindcells::plag_rflu_findcellsbrutekernel(), plag_rflu_modfindcells::plag_rflu_findcellsbrutemod(), plag_rflu_modfindcells::plag_rflu_findcellslohner(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), plag_rflu_modfindcells::plag_rflu_findcellstrajsafe(), plag_rflu_modcomm::plag_rflu_initrecvcounters(), plag_rflu_modcomm::plag_rflu_initsendcounters(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), plag_rflu_initsolserialwrapper(), plag_rflu_initsolutionrandom(), plag_rflu_initsolutionscratch(), plag_rflu_injctilecalcrhs(), plag_rflu_injectiondriver(), plag_rflu_modcomm::plag_rflu_isendcounters(), plag_rflu_modcomm::plag_rflu_isenddata(), plag_rflu_modcomm::plag_rflu_loadbufferssend(), plag_moddimensions::plag_rflu_readdimensions(), plag_rflu_readsolutionascii(), plag_rflu_readsolutionbinary(), plag_rflu_modcomm::plag_rflu_recvcounters(), plag_rflu_modcomm::plag_rflu_recvdata(), plag_rflu_modcomm::plag_rflu_totalnpclscomm(), plag_rflu_modcomm::plag_rflu_unloadbuffersrecv(), plag_rflu_update(), plag_moddimensions::plag_rflu_writedimensions(), plag_rflu_writesolutionascii(), plag_rflu_writesolutionbinary(), plag_rkinit(), plag_modrkinit::plag_rkinitgenericint(), plag_modrkinit::plag_rkinitgenericreal(), plag_modrkinit::plag_rkinitprimary(), plag_rkupdatewrapper(), plag_modsurfstats::plag_setbinindex(), plag_moddimensions::plag_setdimensions(), plag_moddimensions::plag_setmaxdimensions(), plag_setsizegenx(), plag_statmapping(), plag_update(), plag_userinput(), plag_wallbounce(), plag_writesolution(), plag_writestattecascii(), plag_modsurfstats::plag_writesurfstatsascii(), plag_modsurfstats::plag_writesurfstatsbinary(), plag_modsurfstats::plag_writesurfstatskernelascii(), plag_modsurfstats::plag_writesurfstatskernelbinary(), plag_modsurfstats::plag_writesurfstatswrapper(), plag_writetecplotascii(), plag_zerorhs(), printpostinput(), printprepinput(), printtofluinput(), prep_modbcdistribution::profinflowvttaylorcyl(), radi_allocatememory(), radi_calcefftemp(), radi_diffradflux(), radi_diffradfluxpatch(), radi_diffradintens(), radi_emsinit(), radi_extinctioncoef(), radi_flimconvectivefluxes(), radi_flimdiffflux(), radi_flimdifffluxpatch(), radi_flimemsinit(), radi_flimemsupdate(), radi_flimnumericaldissipation(), radi_flimrkinit(), radi_flimrkupdate(), radi_flimsourceterms(), radi_flimzerodummycells(), radi_floflimbconddiffuse(), radi_floflimbcondinjection(), radi_floflimbcondsymmetry(), radi_floflimbcondzerograd(), radi_floflimcentflux(), radi_floflimcentfluxpatch(), radi_floflimcentraldissipation(), radi_floflimcorrcornedgecells(), radi_floflimexchangedummyconf(), radi_floflimexchcornedgecells(), radi_floflimrecvcornedgecells(), radi_floflimrecvdummyvals(), radi_floflimsendcornedgecells(), radi_floflimsenddummyconf(), radi_floflimsetcornedgecells(), radi_fluxlimiter(), radi_initgenxinterface(), radi_mixtsourcetermsflim(), radi_peulsourcetermsflim(), radi_plagsourcetermsflim(), radi_rflo_flimallocdatabuffers(), radi_rflo_flimbndconditionsrecv(), radi_rflo_flimbndconditionssend(), radi_rflo_flimbndconditionsset(), radi_rflo_flimclearsendrequests(), radi_rflo_flimressmoothing(), radi_rflo_flimressmoothingcoeff(), radi_rflo_flimspectralradii(), radi_rflo_readsolution(), radi_rflo_writesolution(), radi_rkinit(), radi_solutionupdate(), radi_sourceterms(), randinitgenxinterface(), readaccelerationsection(), readbcinputfile(), readflowsection(), readforcessection(), readformatssection(), readinitflowsection(), readinputfile(), readmixturesection(), readmultigridsection(), readnumericssection(), prep_modbcdistribution::readpatchsection(), readpostsection(), readprepsection(), readprobesection(), readrandomsection(), readreferencesection(), readrocketsection(), readstatisticsection(), readthrustsection(), readtimestepsection(), readtimezoomingsection(), readtransformsection(), readviscositysection(), rflo_allocatedatabuffers(), rflo_allocatememory(), rflo_arclengthbounds(), rflo_modgridmetrics::rflo_arclengthpatch(), rflo_modboundaryconditions::rflo_bcondfarfield(), rflo_modboundaryconditions::rflo_bcondinflow(), rflo_modboundaryconditions::rflo_bcondinjection(), rflo_modboundaryconditions::rflo_bcondinjectionapn(), rflo_modboundaryconditions::rflo_bcondinjectioninit(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflow(), rflo_modboundaryconditions::rflo_bcondrotatperiod(), rflo_modboundaryconditions::rflo_bcondslipwall(), rflo_modboundaryconditions::rflo_bcondsymmetry(), rflo_modgridregionshape::rflo_blockskewedcell(), rflo_modboundaryconditions::rflo_boundaryconditionsrecv(), rflo_modboundaryconditions::rflo_boundaryconditionssend(), rflo_modboundaryconditions::rflo_boundaryconditionsset(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2eavgcoeffsdegec(), rflo_c2favgcoeffs(), rflo_c2favgcoeffsdegec(), rflo_c2favgcoeffsdummy(), rflo_c2favgcoeffsdummyconn(), rflo_c2favgcoeffsdummyphys(), rflo_c2favgcoeffspatch(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_calcforces(), rflo_calcgradconnbc(), rflo_calcgraddummy(), rflo_calcgraddummyconn(), rflo_calcgraddummyphys(), rflo_calcgraddummysymm(), rflo_calcgradfaces(), rflo_calcgradphysbc(), rflo_calcgradvector(), rflo_modgridmetrics::rflo_calcgridmetrics(), rflo_calcgridspeeds(), rflo_calcmassflow(), rflo_calcthrust(), rflo_calctotalmass(), rflo_centraldissipation(), rflo_centralflux(), rflo_centralfluxpatch(), rflo_changeinteriorgrid(), rflo_checkbcinput(), rflo_checkderiveduserinput(), rflo_checkmetrics(), rflo_checkminimumcells(), rflo_checkregionfaces(), rflo_checkuserinput(), rflo_checkvalidity(), rflo_clearsendrequests(), rflo_modrestartinfo::rflo_closerestartinfo(), rflo_modforcesmoments::rflo_computeintegralforcemomco(), rflo_computeintegralvalues(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_copyboundarydata(), rflo_copyedgefacenorm(), rflo_copyedgefaceparal(), rflo_copygeometrydummy(), rflo_copymatrixcorners(), rflo_copymatrixedges(), rflo_copymatrixpatches(), rflo_copytopologylevels(), rflo_copyvectorcorners(), rflo_copyvectoredges(), rflo_copyvectorpatches(), rflo_correctcorneredgecells(), rflo_derivedinputvalues(), rflo_domemoryallocation(), rflo_dualmultigrid(), rflo_dualtimestepping(), rflo_dualtstinit(), rflo_dualtstpredict(), rflo_dualtstshift(), rflo_dualtststerm(), rflo_edgedeformation(), rflo_edgedeformationstraight(), rflo_modelliptsmoothing::rflo_elliptgridgauss2d(), rflo_modelliptsmoothing::rflo_elliptgridgauss3d(), rflo_modelliptsmoothing::rflo_elliptgridjac2d(), rflo_modelliptsmoothing::rflo_elliptgridjac3d(), rflo_modelliptsmoothing::rflo_elliptgridpatch(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modelliptsmoothing::rflo_elliptgridsmooregion(), rflo_modelliptsmoothing::rflo_elliptgridsor2d(), rflo_modelliptsmoothing::rflo_elliptgridsor3d(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs2d(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs3d(), rflo_endflowsolver(), rflo_exchangecorneredgecells(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangedummyconf(), rflo_exchangedummyint(), rflo_exchangedummyireg(), rflo_exchangegeometry(), rflo_exchangegeometrycopy(), rflo_exchangegeometrylevels(), rflo_exchangegeometryprepare(), rflo_exchangegeometryrecv(), rflo_exchangegeometrysend(), rflo_extrapintcellscal(), rflo_extrapintcellvec(), rflo_extrapolategeometry(), rflo_moddegeneratecornedge::rflo_finddegeneratcell(), rflo_modgridregionshape::rflo_findfunkyblocks(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_findsourcecell(), rflo_findsourcecellinvert(), rflo_findsourcepatches(), rflo_findsourceregions(), rflo_findthrustpatches(), rflo_flowsolver(), rflo_flowsolverdummy(), rflo_generatecoarsegrids(), rflo_getboundaryvalues(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getdeformation(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getedgecellsindices(), rflo_getflowsolution(), rflo_getgeometry(), rflo_getnodeoffset(), rflo_getpatchindices(), rflo_getpatchindicesnodes(), rflo_getuserinput(), rflo_modgridcontrolmap::rflo_gridcontrolfunc2d(), rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad2d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad3d(), rflo_modgridcontrolmap::rflo_gridcontrolmap2d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_modgridregionshape::rflo_gridflatpatch(), rflo_modgridcontrolmap::rflo_gridphysgrad2d(), rflo_modgridcontrolmap::rflo_gridphysgrad3d(), rflo_modgridmetrics::rflo_gridqualityglobal(), rflo_gridremesh(), rflo_initavgcoeffs(), rflo_initflowsolver(), rflo_initgenxinterface(), rflo_initgenxinterfaceprep(), rflo_initgridprocedures(), rflo_initinputvalues(), rflo_modinitialization::rflo_initnoncvsolution(), rflo_modpatchaerocoeffs::rflo_initpatchaerocoeffs(), rflo_interpoltofinerlevel(), rflo_modlaplacesmoothing::rflo_laplacegridjump(), rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_modlaplacesmoothing::rflo_laplacegridortho1(), rflo_modlaplacesmoothing::rflo_laplacegridortho2(), rflo_laplacegridpatch(), rflo_modlaplacesmoothing::rflo_laplacegridpatch(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_laplacegridsolve(), rflo_modlaplacesmoothing::rflo_laplacegridsolve(), rflo_limiterreference(), rflo_mapregionsprocessors(), rflo_moddegeneratecornedge::rflo_markdegeneratvert(), rflo_modmovegridelliptglo::rflo_mgelliptbnddeformation(), rflo_modmovegridelliptfra::rflo_mgelliptboundaries(), rflo_modmovegridelliptfra::rflo_mgelliptedgesfra(), rflo_modmovegridelliptglo::rflo_mgelliptedgesglo(), rflo_modmovegridelliptfra::rflo_mgelliptinterfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptinterfacesglo(), rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptsurfacesglo(), rflo_modmovegridframe::rflo_mgframebnddeformation(), rflo_modmovegridframe::rflo_mgframebnddeformation0(), rflo_modmovegridframe::rflo_mgframebroadcast(), rflo_modmovegridframe::rflo_mgframecornpoints(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframeedges(), rflo_modmovegridframe::rflo_mgframeedgeso(), rflo_modmovegridframe::rflo_mgframeinterfaces(), rflo_modmovegridframe::rflo_mgframemovecorners(), rflo_modmovegridframe::rflo_mgframeorthoshift(), rflo_modmovegridframe::rflo_mgframerestoreexternal(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_modmovegridframe::rflo_mgframesurfaces(), rflo_minimumtimestep(), rflo_movegridblocks(), rflo_modmovegridutil::rflo_movegridcurvedpatch(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_movegridinterfaces(), rflo_modmovegridutil::rflo_movegridqflatpatch(), rflo_movegridsurfaces(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_multigrid(), rflo_newgrid(), rflo_openconverfile(), rflo_modforcesmoments::rflo_openforcemomcofile(), rflo_openprobefile(), rflo_modrestartinfo::rflo_openrestartinfo(), rflo_openthrustfile(), rflo_printuserinput(), rflo_randominit(), rflo_readbcfarfsection(), rflo_readbcfromfile(), rflo_readbcinflowtotangsection(), rflo_readbcinflowvelsection(), rflo_readbcinjectapnsection(), rflo_readbcinjectmratesection(), rflo_readbcinputfile(), rflo_readbcnoslipsection(), rflo_readbcoutflowsection(), rflo_readbcslipwallsection(), rflo_readdatafileint(), rflo_readdatafilereal(), rflo_readgrid(), rflo_readgridregion(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffs(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffsreg(), rflo_readrandomstate(), rflo_readregionmapsection(), rflo_readregiontopology(), rflo_modrestartinfo::rflo_readrestartinfo(), rflo_readsolution(), rflo_readsolutionregion(), rflo_readstat(), rflo_readstatregion(), rflo_readtbcinputfile(), rflo_readtbcsection(), rflo_receivecorneredgecells(), rflo_receivedummyvals(), rflo_residualnorm(), rflo_residualsmoothing(), rflo_residualsmoothingcoeffs(), rflo_roedissipfirst(), rflo_roedissipsecond(), rflo_roefluxfirst(), rflo_roefluxpatch(), rflo_roefluxsecond(), rflo_sendboundaryvalues(), rflo_sendboundaryvaluesalpha(), rflo_sendcorneredgecells(), rflo_senddummyconf(), rflo_senddummyint(), rflo_senddummyireg(), rflo_setcorneredgecells(), rflo_sourcecell(), rflo_modstatsboundaryconditions::rflo_statbcondcopy(), rflo_modstatsboundaryconditions::rflo_statbcondextrap(), rflo_modstatsboundaryconditions::rflo_statbcondnegate(), rflo_modstatsboundaryconditions::rflo_statboundaryconditionsset(), rflo_timestepinviscid(), rflo_timestepping(), rflo_timestepviscous(), rflo_updateinbuffgm(), rflo_userinput(), rflo_viscousflux(), rflo_viscousfluxpatch(), rflo_modvolmeshsmoothing::rflo_vmsaveragevertices(), rflo_modvolmeshsmoothing::rflo_vmsinit(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rflo_modvolmeshsmoothing::rflo_vmslaplaceperturb(), rflo_modvolmeshsmoothing::rflo_vmslaplaceprocedure(), rflo_modvolmeshsmoothing::rflo_vmsprojectvertices(), rflo_modvolmeshsmoothing::rflo_vmsrestorebounddeform(), rflo_writedatafileint(), rflo_writedatafilereal(), rflo_moddegeneratecornedge::rflo_writedegeneratec(), rflo_writegrid(), rflo_writegridregion(), rflo_modforcesmoments::rflo_writeintegralforcemomco(), rflo_modpatchaerocoeffs::rflo_writepatchaerocoeffs(), rflo_modforcesmoments::rflo_writepatchcoeffsinfo(), rflo_writerandomstate(), rflo_writeregiontopology(), rflo_modrestartinfo::rflo_writerestartinfo(), rflo_writesolution(), rflo_writesolutionregion(), rflo_writestat(), rflo_zerodummycells(), rflu_moddimensionality::rflu_123d_checkgeometrykernel(), rflu_moddimensionality::rflu_123d_checkgeometrywrapper(), rflu_moddimensionality::rflu_123d_checktopology(), rflu_modstencilsutils::rflu_addbfaces(), rflu_modstencilsutils::rflu_addcelllayer(), rflu_modstencilsutils::rflu_addcelllayer_1d(), rflu_modstencilsutils::rflu_addcelllayer_1d_g(), rflu_modstencilsutils::rflu_addfacevertneighbs(), rflu_modoles::rflu_allocatedcuhrearrays(), rflu_allocatedcuhrearrays(), rflu_allocatememory(), rflu_modallocatememory::rflu_allocatememorygspeeds(), rflu_modallocatememory::rflu_allocatememorysol(), rflu_modallocatememory::rflu_allocatememorysolcv(), rflu_modallocatememory::rflu_allocatememorysoldv(), rflu_modallocatememory::rflu_allocatememorysolgv(), rflu_modallocatememory::rflu_allocatememorysoltv(), rflu_allocatememorytbc(), rflu_modallocatememory::rflu_allocatememorytstep(), rflu_modallocatememory::rflu_allocatememorytstep_c(), rflu_modallocatememory::rflu_allocatememorytstep_i(), rflu_allocatememoryvert(), rflu_allocatememorywrapper(), rflu_allocmemsolwrapper(), rflu_allocmemvertwrapper(), rflu_modregionmapping::rflu_applyregionmapping(), rflu_modausmflux::rflu_ausm_computeflux(), rflu_modausmflux::rflu_ausm_computeflux1(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modbilinearpatch::rflu_blin_computenormal(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modbilinearpatch::rflu_blin_findclosestpoint(), rflu_modfacelist::rflu_buildavface2borderlist(), rflu_modfacelist::rflu_buildavface2patchlist(), rflu_modboundlists::rflu_buildbcellmlist(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilsbfaces::rflu_buildbf2cstencil_1d(), rflu_modstencilsbfaces::rflu_buildbf2cstencilwrapper(), rflu_modbfacegradaccesslist::rflu_buildbfacegradaccesslist(), rflu_modboundlists::rflu_buildbfaceloclists(), rflu_modboundlists::rflu_buildbfacesortlists(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modboundlists::rflu_buildbvertexmlist(), rflu_modgeometry::rflu_buildbvertexnormals(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil_1d(), rflu_modstencilscells::rflu_buildc2cstencil_1d_g(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modstencilscells::rflu_buildc2cstencilbasic_1d(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_modtopologyutils::rflu_buildcellvertlist(), rflu_modtopologyutils::rflu_buildconnvertlist(), rflu_builddatastruct(), rflu_modedgelist::rflu_buildedge2celllist(), rflu_modedgelist::rflu_buildedgelist(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil_1d(), rflu_modstencilsfaces::rflu_buildf2cstencilwrapper(), rflu_modfacelist::rflu_buildfacelist(), rflu_modtopologyutils::rflu_buildfacevertlist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modstencilscells::rflu_buildlistcc2cstencil(), rflu_modstencilsfaces::rflu_buildlistcf2cstencil(), rflu_modcellmapping::rflu_buildloc2globcellmapping(), rflu_modpatchutils::rflu_buildpatchneighbormaps(), rflu_modplottingvars::rflu_buildplottingvarmaps(), rflu_modplottingvars::rflu_buildplottingvarnames(), rflu_modregionmapping::rflu_buildregionmappingsimple(), rflu_modsplittree::rflu_buildsplittree(), rflu_modoles::rflu_buildstencilsoles(), rflu_modstencilsvert::rflu_buildstencilvert2cell(), rflu_modoles::rflu_buildsymmetrymapsoles(), rflu_modvertexlists::rflu_buildvert2celllist(), rflu_modtopologyutils::rflu_buildvertcellnghblist(), rflu_modboundxvutils::rflu_bxv_compenergypatch(), rflu_modboundxvutils::rflu_bxv_compmomenergypatch(), rflu_modboundxvutils::rflu_bxv_computevarscv(), rflu_modboundconvertcv::rflu_bxv_convertcvcons2prim(), rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_modboundxvutils::rflu_bxv_createvarscv(), rflu_modboundxvutils::rflu_bxv_createvarsdv(), rflu_modboundxvutils::rflu_bxv_createvarststep(), rflu_modboundxvutils::rflu_bxv_destroyvarscv(), rflu_modboundxvutils::rflu_bxv_destroyvarsdv(), rflu_modboundxvutils::rflu_bxv_destroyvarststep(), rflu_modboundxvutils::rflu_bxv_initvars(), rflu_modboundxvutils::rflu_bxv_nullifyvarscv(), rflu_modboundxvutils::rflu_bxv_nullifyvarsdv(), rflu_modboundxvutils::rflu_bxv_nullifyvarststep(), rflu_modboundxvutils::rflu_bxv_readvarsascii(), rflu_modboundxvutils::rflu_bxv_readvarsbinary(), rflu_modboundxvutils::rflu_bxv_readvarswrapper(), rflu_modboundxvutils::rflu_bxv_setdependentvars(), rflu_modboundxvutils::rflu_bxv_setdependentvarspatch(), rflu_modboundxvutils::rflu_bxv_writevarsascii(), rflu_modboundxvutils::rflu_bxv_writevarsbinary(), rflu_modboundxvutils::rflu_bxv_writevarswrapper(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_checkcouplinginput(), rflu_checkderiveduserinput(), rflu_modcentaur::rflu_checkgridcentaur(), rflu_modgambit::rflu_checkgridgambit(), rflu_checkgridspeeds(), rflu_modpatchutils::rflu_checkpatchbcconsistency(), rflu_checkpositivity(), rflu_checkpositivity_gl(), rflu_checkpositivitywrapper(), rflu_modregionmapping::rflu_checkregionmapping(), rflu_checkuserinput(), rflu_checkvalidity(), rflu_checkvalidity_gl(), rflu_checkvaliditywrapper(), rflu_modpatchcoeffs::rflu_closepatchcoeffs(), rflu_closepostinfo(), rflu_modprobes::rflu_closeprobefiles(), rflu_modregionmapping::rflu_closeregionmappingfile(), rflu_closerestartinfo(), rflu_modcoloring::rflu_col_buildcoloringp(), rflu_modcoloring::rflu_col_buildcolorings(), rflu_modcoloring::rflu_col_createcoloring(), rflu_modcoloring::rflu_col_destroycoloring(), rflu_modcoloring::rflu_col_readcoloring(), rflu_modcoloring::rflu_col_recreatecelllist(), rflu_modcoloring::rflu_col_writecoloring(), rflu_modcommlists::rflu_comm_buildcommlists(), rflu_modcommlists::rflu_comm_buildcommlistscells(), rflu_modcommlists::rflu_comm_buildcommlistsvert(), rflu_modcommlists::rflu_comm_checkcountborders(), rflu_modcommlists::rflu_comm_countborders(), rflu_modcommlists::rflu_comm_countbordersserial(), rflu_modcommlists::rflu_comm_createbordercntr(), rflu_modcommlists::rflu_comm_createborders(), rflu_modcommlists::rflu_comm_createcommlists(), rflu_modcommlists::rflu_comm_destroybordercntr(), rflu_modcommlists::rflu_comm_destroyborders(), rflu_modcommlists::rflu_comm_destroycommlists(), rflu_modcommlists::rflu_comm_getproclocregids(), rflu_modcommlists::rflu_comm_readcommlists(), rflu_modcommlists::rflu_comm_writecommlists(), rflu_modgeometry::rflu_computeapproxcentroids(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationbfaces::rflu_computebfgradconstrwrapper(), rflu_computedcuhreinfo(), rflu_computeenerdissoles(), rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), rflu_modgeometry::rflu_computefacedist(), rflu_computefluxinv(), rflu_modoles::rflu_computegeometrictermsoles(), rflu_modforcesmoments::rflu_computeglobalforcesmoments(), rflu_moddifferentiationbfaces::rflu_computegradbfaces(), rflu_moddifferentiationbfaces::rflu_computegradbfaces_1d(), rflu_moddifferentiationbfaces::rflu_computegradbfaceswrapper(), rflu_moddifferentiationcells::rflu_computegradcells_1d(), rflu_moddifferentiationcells::rflu_computegradcells_2d(), rflu_moddifferentiationcells::rflu_computegradcells_3d(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationcells::rflu_computegradcellsfast_2d(), rflu_moddifferentiationcells::rflu_computegradcellsfast_3d(), rflu_moddifferentiationcells::rflu_computegradcellswrapper(), rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_moddifferentiationfaces::rflu_computegradfaces(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_moddifferentiationfaces::rflu_computegradfaceswrapper(), rflu_computegridspeeds(), rflu_computeintegral1oles(), rflu_computeintegral2oles(), rflu_computeintegral3oles(), rflu_computeintegral4oles(), rflu_computeintegral5oles(), rflu_computeintegrals1245oles(), rflu_computeintegralvalues(), rflu_modlimiters::rflu_computelimiterbarthjesp(), rflu_modlimiters::rflu_computelimitervenkat(), rflu_modgeometrytools::rflu_computelinecellxsectfast(), rflu_modgeometrytools::rflu_computelinecellxsectsafe(), rflu_modforcesmoments::rflu_computelocalforcesmoments(), rflu_modpatchutils::rflu_computepatchnormalsglobal(), rflu_modpatchutils::rflu_computepatchnormalslocal(), rflu_modplottingvars::rflu_computeplottingvarscore(), rflu_modplottingvars::rflu_computeplottingvarsdisc(), rflu_modplottingvars::rflu_computeplottingvarsgraderr(), rflu_modplottingvars::rflu_computeplottingvarsvort(), rflu_modplottingvars::rflu_computeplottingvarswrapper(), rflu_modweights::rflu_computestencilmoments2d1(), rflu_modweights::rflu_computestencilmoments3d1(), rflu_computestencilsize(), rflu_modstencilsutils::rflu_computestencilsize(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_computevertexvariables(), rflu_computeweightsoles(), rflu_modweights::rflu_computewtsbf2c(), rflu_modweights::rflu_computewtsbf2cwrapper(), rflu_modweights::rflu_computewtsc2c(), rflu_modweights::rflu_computewtsc2cwrapper(), rflu_modweights::rflu_computewtsf2c(), rflu_modweights::rflu_computewtsf2cwrapper(), rflu_modweights::rflu_computewtsx2c_1d(), rflu_modcentaur::rflu_convcentaur2rocflu(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_modconvertcv::rflu_convertcvcons2prim(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_convfluxoles(), rflu_modgambit::rflu_convgambit2rocflu(), rflu_modmesh3d::rflu_convmesh3d2rocflu(), rflu_modtetmesh::rflu_convrocflu2tetmesh(), rflu_modtetmesh::rflu_convtetmesh2rocflu(), rflu_modvgridns::rflu_convvgridns2rocflu(), rflu_modcopydata::rflu_copy_celldatap2s_r2d(), rflu_modcopydata::rflu_copy_celldatap2s_r3d(), rflu_modcopydata::rflu_copy_celldatas2p_i1d(), rflu_modcopydata::rflu_copy_celldatas2p_r2d(), rflu_modgatherdata::rflu_countgathereddata(), rflu_modplottingvars::rflu_countplottingvars(), rflu_modgeometry::rflu_createapproxcentroids(), rflu_modfacelist::rflu_createavface2borderlist(), rflu_modfacelist::rflu_createavface2patchlist(), rflu_modboundlists::rflu_createbcellmlist(), rflu_modstencilsbfaces::rflu_createbf2cstencil(), rflu_modstencilsbfaces::rflu_createbf2cstencil_1d(), rflu_modstencilsbfaces::rflu_createbf2cstencilwrapper(), rflu_modbfacegradaccesslist::rflu_createbfacegradaccesslist(), rflu_modboundlists::rflu_createbfaceloclists(), rflu_modboundlists::rflu_createbfacesortlists(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modboundlists::rflu_createbvertexmlist(), rflu_modstencilscells::rflu_createc2cstencil(), rflu_modstencilscells::rflu_createc2cstencil_1d(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modedgelist::rflu_createedge2celllist(), rflu_modedgelist::rflu_createedgelist(), rflu_modstencilsfaces::rflu_createf2cstencil(), rflu_modstencilsfaces::rflu_createf2cstencil_1d(), rflu_modstencilsfaces::rflu_createf2cstencilwrapper(), rflu_modgeometry::rflu_createfacedist(), rflu_modfacelist::rflu_createfacelist(), rflu_modforcesmoments::rflu_createforcesmoments(), rflu_modgatherdata::rflu_creategathereddata(), rflu_modgeometry::rflu_creategeometry(), rflu_modforcesmoments::rflu_createglobalthrustflags(), rflu_creategrid(), rflu_modhashtable::rflu_createhashtable(), rflu_modoles::rflu_createintegralsoles(), rflu_modlimiters::rflu_createlimiter(), rflu_modoctree::rflu_createoctree(), rflu_modpatchcoeffs::rflu_createpatchcoeffs(), rflu_modpatchutils::rflu_createpatchneighbormaps(), rflu_modplottingvars::rflu_createplottingvarmaps(), rflu_modplottingvars::rflu_createplottingvars(), rflu_modplottingvars::rflu_createplottingvarsvert(), rflu_modregionmapping::rflu_createregionmapping(), rflu_createregions(), rflu_modsplittree::rflu_createsplittree(), rflu_modoles::rflu_createstencilsweightsoles(), rflu_modstencilsvert::rflu_createstencilvert2cell(), rflu_modvertexlists::rflu_createvert2celllist(), rflu_modweights::rflu_createwtsbf2c(), rflu_modweights::rflu_createwtsbf2cwrapper(), rflu_modweights::rflu_createwtsc2c(), rflu_modweights::rflu_createwtsc2cwrapper(), rflu_modweights::rflu_createwtsf2c(), rflu_modweights::rflu_createwtsf2cwrapper(), rflu_modoles::rflu_deallocatedcuhrearrays(), rflu_deallocatedcuhrearrays(), rflu_deallocatememory(), rflu_moddeallocatememory::rflu_deallocatememorygspeeds(), rflu_moddeallocatememory::rflu_deallocatememorysol(), rflu_moddeallocatememory::rflu_deallocatememorysolcv(), rflu_moddeallocatememory::rflu_deallocatememorysoldv(), rflu_moddeallocatememory::rflu_deallocatememorysolgv(), rflu_moddeallocatememory::rflu_deallocatememorysoltv(), rflu_moddeallocatememory::rflu_deallocatememorytstep(), rflu_moddeallocatememory::rflu_deallocatememorytstep_c(), rflu_moddeallocatememory::rflu_deallocatememorytstep_i(), rflu_deallocatememoryvert(), rflu_deallocatememorywrapper(), rflu_deallocmemsolwrapper(), rflu_deallocmemvertwrapper(), rflu_decideneedbgradface(), rflu_decideprint(), rflu_modreadwritebcdatafile::rflu_decidereadwritebcdatafile(), rflu_decidewrite(), rflu_modprobes::rflu_decidewriteprobes(), rflu_modboundlists::rflu_denumberbfacelists(), rflu_modrenumberlist::rflu_denumberlist(), rflu_derivedinputvalues(), rflu_modgeometry::rflu_destroyapproxcentroids(), rflu_modfacelist::rflu_destroyavface2borderlist(), rflu_modfacelist::rflu_destroyavface2patchlist(), rflu_modboundlists::rflu_destroybcellmlist(), rflu_modstencilsbfaces::rflu_destroybf2cstencil(), rflu_modstencilsbfaces::rflu_destroybf2cstencil_1d(), rflu_modstencilsbfaces::rflu_destroybf2cstencilwrapper(), rflu_modbfacegradaccesslist::rflu_destroybfacegradaccesslist(), rflu_modboundlists::rflu_destroybfaceloclists(), rflu_modboundlists::rflu_destroybfacesortlists(), rflu_modboundlists::rflu_destroybvertexlists(), rflu_modboundlists::rflu_destroybvertexmlist(), rflu_modstencilscells::rflu_destroyc2cstencil(), rflu_modstencilscells::rflu_destroyc2cstencil_1d(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), rflu_modfacelist::rflu_destroycell2facelist(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modedgelist::rflu_destroyedge2celllist(), rflu_modedgelist::rflu_destroyedgelist(), rflu_modstencilsfaces::rflu_destroyf2cstencil(), rflu_modstencilsfaces::rflu_destroyf2cstencil_1d(), rflu_modstencilsfaces::rflu_destroyf2cstencilwrapper(), rflu_modgeometry::rflu_destroyfacedist(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modforcesmoments::rflu_destroyforcesmoments(), rflu_modgatherdata::rflu_destroygathereddata(), rflu_modgeometry::rflu_destroygeometry(), rflu_modforcesmoments::rflu_destroyglobalthrustflags(), rflu_destroygrid(), rflu_modhashtable::rflu_destroyhashtable(), rflu_modlimiters::rflu_destroylimiter(), rflu_modstencilscells::rflu_destroylistcc2cstencil(), rflu_modstencilsfaces::rflu_destroylistcf2cstencil(), rflu_modoctree::rflu_destroyoctree(), rflu_modpatchcoeffs::rflu_destroypatchcoeffs(), rflu_modpatchutils::rflu_destroypatchneighbormaps(), rflu_modplottingvars::rflu_destroyplottingvarmaps(), rflu_modplottingvars::rflu_destroyplottingvars(), rflu_modplottingvars::rflu_destroyplottingvarsvert(), rflu_modregionmapping::rflu_destroyregionmapping(), rflu_modsplittree::rflu_destroysplittree(), rflu_modoles::rflu_destroystencilsweightsoles(), rflu_modstencilsvert::rflu_destroystencilvert2cell(), rflu_modvertexlists::rflu_destroyvert2celllist(), rflu_modweights::rflu_destroywtsbf2c(), rflu_modweights::rflu_destroywtsbf2cwrapper(), rflu_modweights::rflu_destroywtsc2c(), rflu_modweights::rflu_destroywtsc2cwrapper(), rflu_modweights::rflu_destroywtsf2c(), rflu_modweights::rflu_destroywtsf2cwrapper(), rflu_modgridutils::rflu_distortgrid(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_modexplicitmultistage::rflu_ems_setcvold(), rflu_modexplicitmultistage::rflu_ems_setdiss(), rflu_modexplicitmultistage::rflu_ems_setrhs(), rflu_modexplicitmultistage::rflu_ems_updateconservedvars(), rflu_endflowsolver(), rflu_enforceboundswrapper(), rflu_modviscousflux::rflu_enforceheatflux(), rflu_modoles::rflu_enforcesymmetryoles(), rflu_modensight::rflu_ens_builddatainfo(), rflu_modensight::rflu_ens_closefileflowwrapper(), rflu_modensight::rflu_ens_closefilegeometry(), rflu_modensight::rflu_ens_closefilescalarvector(), rflu_modensight::rflu_ens_destroydatainfo(), rflu_modensight::rflu_ens_openfileflowwrapper(), rflu_modensight::rflu_ens_openfilegeometry(), rflu_modensight::rflu_ens_openfilescalarvector(), rflu_modensight::rflu_ens_writefilecase(), rflu_modensight::rflu_ens_writeflowwrapper(), rflu_modensightutils::rflu_ens_writegrid(), rflu_modensight::rflu_ens_writegridwrapper(), rflu_modensightutils::rflu_ens_writescalar(), rflu_modensightutils::rflu_ens_writevector(), rflu_equilibriumeulerian(), rflu_explicitmultistage(), rflu_modextractflowdata::rflu_extractflowdata(), rflu_modextractflowdata::rflu_extractflowdatablasius(), rflu_modextractflowdata::rflu_extractflowdatalinefarf(), rflu_modextractflowdata::rflu_extractflowdatanscbc(), rflu_modextractflowdata::rflu_extractflowdataproudman(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modextractflowdata::rflu_extractflowdatasod(), rflu_modextractflowdata::rflu_extractflowdatasommspi(), rflu_modextractflowdata::rflu_extractflowdatastg1d(), rflu_modextractflowdata::rflu_extractflowdatastg2d(), rflu_modextractflowdatautils::rflu_extractshocklocation1d(), rflu_modprobes::rflu_findprobecells(), rflu_modoles::rflu_findprototypefacesoles(), rflu_finishsd(), rflu_flowsolver(), rflu_flowsolverdummy(), rflu_modgatherdata::rflu_gatherdata(), rflu_modrocstaradmin::rflu_genx_buildgridsurf(), rflu_modrocstaradmin::rflu_genx_buildpconn(), rflu_modrocstario::rflu_genx_buildrocinpanestrings(), rflu_modrocstaradmin::rflu_genx_closerocinctrlfiles(), rflu_modrocstario::rflu_genx_closerocinctrlfiles(), rflu_modrocstartools::rflu_genx_constraindisp(), rflu_modrocstaradmin::rflu_genx_createdatainterf(), rflu_modrocstaradmin::rflu_genx_creategridsurf(), rflu_modrocstaradmin::rflu_genx_createpconn(), rflu_modrocstario::rflu_genx_decidereadfile(), rflu_modrocstario::rflu_genx_decidewritefile(), rflu_modrocstaradmin::rflu_genx_destroydatainterf(), rflu_modrocstaradmin::rflu_genx_destroygridsurf(), rflu_modrocstaradmin::rflu_genx_destroypconn(), rflu_modrocstartools::rflu_genx_initbflag(), rflu_modrocstartools::rflu_genx_movegrid(), rflu_modrocstario::rflu_genx_openrocinctrlfiles(), rflu_modrocstario::rflu_genx_putdatagspeedssurf(), rflu_modrocstario::rflu_genx_putdatagspeedsvol(), rflu_modrocstario::rflu_genx_putgridsurf(), rflu_modrocstario::rflu_genx_putgridvol(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modrocstario::rflu_genx_readwindow(), rflu_modrocstario::rflu_genx_writerocinctrlfiles(), rflu_getboundaryvalues(), rflu_modconstraintutils::rflu_getconstrtype(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_getcvloc(), rflu_getdeformation(), rflu_getdeformationwrapper(), rflu_modcellfaceedgeinfo::rflu_getedgekind(), rflu_modcellfaceedgeinfo::rflu_getfacekind(), rflu_modcellfaceedgeinfo::rflu_getglobalcellkind(), rflu_modcellfaceedgeinfo::rflu_getglobalcelltype(), rflu_modfacelist::rflu_getopposingfaces(), rflu_modpatchutils::rflu_getpatchnormaldirection(), rflu_modregionmapping::rflu_getproclocregids(), rflu_modresidual::rflu_getresidualsupport1(), rflu_modresidual::rflu_getresidualsupport2(), rflu_getspecialcells(), rflu_getuserinput(), rflu_modcellfaceedgeinfo::rflu_getvirtualcellreg(), rflu_modhashtable::rflu_hashedge(), rflu_modhashtable::rflu_hashface(), rflu_modhashtable::rflu_hashvertex(), rflu_modhashtable::rflu_hashvertexfancy(), rflu_modhllcflux::rflu_hllc_computeflux(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_modincelltest::rflu_ict_computetolerance(), rflu_modincelltest::rflu_ict_testfaceplanar(), rflu_modincelltest::rflu_ict_testfacequadbilinear(), rflu_modincelltest::rflu_ict_testincell(), rflu_modincelltest::rflu_ict_testincellfancy(), rflu_modincelltest::rflu_ict_testincelllohner(), rflu_modregionmapping::rflu_imposeregionmappingserial(), rflu_initbcdatahardcode(), rflu_initflowhardcode(), rflu_initflowhardcodelim(), rflu_initflowhardcodelimwrapper(), rflu_initflowhardcodewrapper(), rflu_initflowscratch(), rflu_initflowscratchwrapper(), rflu_initflowserialwrapper(), rflu_initflowsolver(), rflu_modforcesmoments::rflu_initforcesmoments(), rflu_modforcesmoments::rflu_initglobalthrustflags(), rflu_initinputvalues(), rflu_modpatchcoeffs::rflu_initpatchcoeffs(), rflu_modplottingvars::rflu_initplottingvars(), rflu_modplottingvars::rflu_initplottingvarsvert(), rflu_modfacelist::rflu_insertintocell2facelist(), rflu_modinterpolation::rflu_interpcells2face(), rflu_modinterpolation::rflu_interpcells2facepatch(), rflu_modinterpolation::rflu_interpcells2faces(), rflu_modinterpolation::rflu_interpcells2verts(), rflu_interpolatewrapper(), rflu_modinterpolation::rflu_interpsimplecells2verts(), rflu_invertmatrixsvd(), rflu_invflux_i(), rflu_modlimiters::rflu_limitgradcells(), rflu_modlimiters::rflu_limitgradcellssimple(), rflu_modmergeregions::rflu_merg_mergegrid(), rflu_modmergeregions::rflu_merg_mergepatchcoeffs(), rflu_modmergeregions::rflu_merg_mergesolwrapper(), rflu_mergepostprocessregions(), rflu_minimumtimestep(), rflu_movegriddisp(), rflu_movegridwrapper(), rflu_movegridxyz(), rflu_modmpi::rflu_mpi_clearrequest(), rflu_modmpi::rflu_mpi_clearrequestwrapper(), rflu_modmpi::rflu_mpi_copycelldata(), rflu_modmpi::rflu_mpi_copywrapper(), rflu_modmpi::rflu_mpi_createbufferipclsend(), rflu_modmpi::rflu_mpi_createbuffers(), rflu_modmpi::rflu_mpi_createbufferswrapper(), rflu_modmpi::rflu_mpi_destroybufferipclsend(), rflu_modmpi::rflu_mpi_destroybuffers(), rflu_modmpi::rflu_mpi_destroybufferswrapper(), rflu_modmpi::rflu_mpi_isendcelldata(), rflu_modmpi::rflu_mpi_isendwrapper(), rflu_modmpi::rflu_mpi_recreatebufferipclsend(), rflu_modmpi::rflu_mpi_recvcelldata(), rflu_modmpi::rflu_mpi_recvwrapper(), rflu_modmpi::rflu_mpi_settag(), rflu_modmpi::rflu_mpi_settagswrapper(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_comprhs(), rflu_modnscbc::rflu_nscbc_comprhsff(), rflu_modnscbc::rflu_nscbc_comprhsiftotang(), rflu_modnscbc::rflu_nscbc_comprhsifveltemp(), rflu_modnscbc::rflu_nscbc_comprhsij(), rflu_modnscbc::rflu_nscbc_comprhsnswheat(), rflu_modnscbc::rflu_nscbc_comprhsnswtemp(), rflu_modnscbc::rflu_nscbc_comprhsof(), rflu_modnscbc::rflu_nscbc_comprhssw(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modnscbc::rflu_nscbc_decidehavenscbc(), rflu_modnscbc::rflu_nscbc_initff(), rflu_modnscbc::rflu_nscbc_initiftotang(), rflu_modnscbc::rflu_nscbc_initifveltemp(), rflu_modnscbc::rflu_nscbc_initij(), rflu_modnscbc::rflu_nscbc_initnswheat(), rflu_modnscbc::rflu_nscbc_initnswtemp(), rflu_modnscbc::rflu_nscbc_initof(), rflu_modnscbc::rflu_nscbc_initsw(), rflu_modgeometry::rflu_nullifyapproxcentroids(), rflu_modfacelist::rflu_nullifyavface2borderlist(), rflu_modfacelist::rflu_nullifyavface2patchlist(), rflu_modboundlists::rflu_nullifybcellmlist(), rflu_modstencilsbfaces::rflu_nullifybf2cstencil(), rflu_modstencilsbfaces::rflu_nullifybf2cstencil_1d(), rflu_modbfacegradaccesslist::rflu_nullifybfacegradaccesslist(), rflu_modboundlists::rflu_nullifybfaceloclists(), rflu_modboundlists::rflu_nullifybfacesortlists(), rflu_modboundlists::rflu_nullifybvertexlists(), rflu_modboundlists::rflu_nullifybvertexmlist(), rflu_modstencilscells::rflu_nullifyc2cstencil(), rflu_modstencilscells::rflu_nullifyc2cstencil_1d(), rflu_modfacelist::rflu_nullifycell2facelist(), rflu_modcellmapping::rflu_nullifycellmapping(), rflu_modedgelist::rflu_nullifyedge2celllist(), rflu_modedgelist::rflu_nullifyedgelist(), rflu_modstencilsfaces::rflu_nullifyf2cstencil(), rflu_modstencilsfaces::rflu_nullifyf2cstencil_1d(), rflu_modgeometry::rflu_nullifyfacedist(), rflu_modfacelist::rflu_nullifyfacelist(), rflu_modforcesmoments::rflu_nullifyforcesmoments(), rflu_modgeometry::rflu_nullifygeometry(), rflu_modforcesmoments::rflu_nullifyglobalthrustflags(), rflu_modpatchcoeffs::rflu_nullifypatchcoeffs(), rflu_modplottingvars::rflu_nullifyplottingvarmaps(), rflu_modplottingvars::rflu_nullifyplottingvars(), rflu_modplottingvars::rflu_nullifyplottingvarsvert(), rflu_modstencilsvert::rflu_nullifystencilvert2cell(), rflu_modvertexlists::rflu_nullifyvert2celllist(), rflu_modweights::rflu_nullifywtsbf2c(), rflu_modweights::rflu_nullifywtsc2c(), rflu_modweights::rflu_nullifywtsf2c(), rflu_openconverfile(), rflu_modpatchcoeffs::rflu_openpatchcoeffsascii(), rflu_modpatchcoeffs::rflu_openpatchcoeffsbinary(), rflu_openpostinfo(), rflu_modprobes::rflu_openprobefiles(), rflu_modregionmapping::rflu_openregionmappingfile(), rflu_openrestartinfo(), rflu_openstatsfileoles(), rflu_opentotalmassfile(), rflu_modpartitionregion::rflu_part_addvirtualcells(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv1(), rflu_modpartitionregionutils::rflu_part_addvirtualcellsinv2(), rflu_modpartitionregion::rflu_part_buildborderfacelist(), rflu_modpartitionregion::rflu_part_buildcelllists(), rflu_modpartitionregion::rflu_part_buildpatchlists(), rflu_modpartitionregion::rflu_part_buildreg2cellmap(), rflu_modpartitionregion::rflu_part_buildvertexdata(), rflu_modpartitionregion::rflu_part_buildvertexlists(), rflu_modpartitionregion::rflu_part_createcelllists(), rflu_modpartitionregion::rflu_part_createpatchlists(), rflu_modpartitionregion::rflu_part_createreg2cellmap(), rflu_modpartitionregion::rflu_part_destroyborderfacelist(), rflu_modpartitionregion::rflu_part_destroycelldata(), rflu_modpartitionregion::rflu_part_destroycelllists(), rflu_modpartitionregion::rflu_part_destroypatchlists(), rflu_modpartitionregion::rflu_part_destroyvertexdata(), rflu_modpartitionregion::rflu_part_partitionregion(), rflu_modpartitionregion::rflu_part_recreatecelllist(), rflu_modpartitionregion::rflu_part_renumbervertexlists(), rflu_modpetscpoisson::rflu_petsc_buildpoisson(), rflu_modpetscnewtonkrylov::rflu_petsc_createapplicationordering(), rflu_modpetscnewtonkrylov::rflu_petsc_createcoloring(), rflu_modpetscnewtonkrylov::rflu_petsc_createjacobian(), rflu_modpetscpoisson::rflu_petsc_createpoisson(), rflu_modpetscnewtonkrylov::rflu_petsc_createvectors(), rflu_modpetscnewtonkrylov::rflu_petsc_destroyapplicationordering(), rflu_modpetscnewtonkrylov::rflu_petsc_destroyjacobian(), rflu_modpetscnewtonkrylov::rflu_petsc_destroyvectors(), rflu_modpetscadmin::rflu_petsc_finalize(), rflu_modpetscnewtonkrylov::rflu_petsc_formjacobian(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidual(), rflu_modpetscnewtonkrylov::rflu_petsc_formresidualfirstorder(), rflu_modpetscnewtonkrylov::rflu_petsc_getdtscale(), rflu_modpetscadmin::rflu_petsc_init(), rflu_modpetscpoisson::rflu_petsc_setsolverpoisson(), rflu_modpetscpoisson::rflu_petsc_solvepressurepoisson(), rflu_pickregions(), rflu_pickregionscoord(), rflu_pickregionsmanual(), rflu_pickspecialcells(), rflu_pickspecialfaces(), rflu_postprocessregions(), rflu_postprocessregions_ens(), rflu_postprocessregionscommon1(), rflu_postprocessregionscommon2(), rflu_printchangeinfo(), rflu_printflowinfo(), rflu_printflowinfowrapper(), rflu_modforcesmoments::rflu_printglobalforcesmoments(), rflu_printgridinfo(), rflu_printheader(), rflu_printlocinfo(), rflu_modplottingvars::rflu_printplottingvarsinfo(), rflu_modprobes::rflu_printprobeinfo(), rflu_printprogressdots(), rflu_printuserinput(), rflu_printwarninfo(), rflu_printwriteconvergence(), rflu_putboundaryvalues(), rflu_putboundaryvaluesalpha(), rflu_randominit(), rflu_modreadwritebcdatafile::rflu_readbcdatafile(), rflu_modreadbcinputfile::rflu_readbcfarfsection(), rflu_modreadbcinputfile::rflu_readbcinflowtotangsection(), rflu_modreadbcinputfile::rflu_readbcinflowveltempsection(), rflu_modreadbcinputfile::rflu_readbcinjectsection(), rflu_modreadbcinputfile::rflu_readbcinputfile(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), rflu_modreadbcinputfile::rflu_readbcnoslipwallheatsect(), rflu_modreadbcinputfile::rflu_readbcnoslipwalltempsect(), rflu_modreadbcinputfile::rflu_readbcoutflowsection(), rflu_modreadbcinputfile::rflu_readbcperiodicsection(), rflu_modreadbcinputfile::rflu_readbcslipwallsection(), rflu_modreadbcinputfile::rflu_readbcsymmetrysection(), rflu_modreadbcinputfile::rflu_readbcvirtualsection(), rflu_readconvgridwrapper(), rflu_moddimensions::rflu_readdimensions(), rflu_moddimensions::rflu_readdimensionswrapper(), rflu_modreadwriteflow::rflu_readflowascii(), rflu_modreadwriteflow::rflu_readflowbinary(), rflu_modreadwriteflow::rflu_readflowwrapper(), rflu_modreadwritegrid::rflu_readgridascii(), rflu_modreadwritegrid::rflu_readgridbinary(), rflu_modcentaur::rflu_readgridcentaurascii(), rflu_modcentaur::rflu_readgridcentaurbinary(), rflu_modcobalt::rflu_readgridcobalt(), rflu_modgambit::rflu_readgridgambitneutral(), rflu_modmesh3d::rflu_readgridmesh3d(), rflu_modreadwritegridspeeds::rflu_readgridspeedsascii(), rflu_modreadwritegridspeeds::rflu_readgridspeedsbinary(), rflu_modreadwritegridspeeds::rflu_readgridspeedswrapper(), rflu_modtetmesh::rflu_readgridtetmesh(), rflu_modvgridns::rflu_readgridvgridns(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_readintegrals1245oles(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modpatchcoeffs::rflu_readpatchcoeffsascii(), rflu_modpatchcoeffs::rflu_readpatchcoeffsbinary(), rflu_modpatchcoeffs::rflu_readpatchcoeffswrapper(), rflu_readpostinfo(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_readrestartinfo(), rflu_readstat(), rflu_readtbcinputfile(), rflu_readtbcsection(), rflu_modrelatedpatches::rflu_relp_periodicwrapper(), rflu_modrelatedpatches::rflu_relp_symmetrywrapper(), rflu_modrelatedpatches::rflu_relp_transformvector(), rflu_modrelatedpatches::rflu_relp_transformwrapper(), rflu_modboundlists::rflu_renumberbfacelists(), rflu_modrenumberlist::rflu_renumberlist(), rflu_modrenumberlist::rflu_renumberlist2(), rflu_modfacelist::rflu_reorientfaces(), rflu_modresidual::rflu_res_computeresidual(), rflu_modresidual::rflu_res_setcvold(), rflu_modresidual::rflu_res_setdiss(), rflu_modresidual::rflu_res_setrhs(), rflu_residualnorm(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap2d(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap3d(), rflu_modrenumberings::rflu_rnmb_buildsc2pcmap(), rflu_modrenumberings::rflu_rnmb_buildsv2pvmap(), rflu_modrenumberings::rflu_rnmb_createpbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_createpc2scmap(), rflu_modrenumberings::rflu_rnmb_createpv2svmap(), rflu_modrenumberings::rflu_rnmb_createsc2rmap(), rflu_modrenumberings::rflu_rnmb_destroypbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_destroypc2scmap(), rflu_modrenumberings::rflu_rnmb_destroypv2svmap(), rflu_modrenumberings::rflu_rnmb_destroysbc2pcmap(), rflu_modrenumberings::rflu_rnmb_destroysc2pcmap(), rflu_modrenumberings::rflu_rnmb_destroysc2rmap(), rflu_modrenumberings::rflu_rnmb_destroysv2pvmap(), rflu_modrenumberings::rflu_rnmb_readpxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_readsc2rmap(), rflu_modrenumberings::rflu_rnmb_writepxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_writesc2rmap(), rflu_modroeflux::rflu_roe_computeflux(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux1_tcp(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxc1(), rflu_modroeflux::rflu_roe_computefluxc2_tcp(), rflu_modroeflux::rflu_roe_computefluxd1_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_scalarcheckpositivity(), rflu_modconvertcv::rflu_scalarconvertcvcons2prim(), rflu_modconvertcv::rflu_scalarconvertcvprim2cons(), rflu_scalarfirst(), rflu_scalarfirstpatch(), rflu_scalarinitrhs(), rflu_scalarsecond(), rflu_scalarsecondpatch(), rflu_scalarviscousfluxes(), rflu_modgatherdata::rflu_scattergathereddata(), rflu_setdependentvars(), rflu_setderiveduserinput(), rflu_setgasvars(), rflu_modforcesmoments::rflu_setglobalthrustflags(), rflu_modstencilsbfaces::rflu_setinfobf2cstencil(), rflu_modstencilsbfaces::rflu_setinfobf2cstencil_1d(), rflu_modstencilsbfaces::rflu_setinfobf2cstencilwrapper(), rflu_modstencilscells::rflu_setinfoc2cstencil(), rflu_modstencilscells::rflu_setinfoc2cstencil_1d(), rflu_modstencilscells::rflu_setinfoc2cstencilwrapper(), rflu_modstencilsfaces::rflu_setinfof2cstencil(), rflu_modstencilsfaces::rflu_setinfof2cstencil_1d(), rflu_modstencilsfaces::rflu_setinfof2cstencilwrapper(), rflu_modstencilsvert::rflu_setinfostencilvert2cell(), rflu_moddimensions::rflu_setmaxdimensions(), rflu_setmovegridoptions(), rflu_modpatchutils::rflu_setpatchflatflags(), rflu_setpatchplotflags(), rflu_modregionmapping::rflu_setregionmappingserial(), rflu_setrestarttimeflag(), rflu_modtime::rflu_settimerk(), rflu_settransportvars(), rflu_setvarinfo(), rflu_setvarinfowrapper(), rflu_setvars(), rflu_setvarscontwrapper(), rflu_setvarsdiscwrapper(), rflu_setvarswrapper(), rflu_modstencilsutils::rflu_sortbfaces(), rflu_modstl::rflu_stl_writesurfgridascii(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcells(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv1(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcellsinv2(), rflu_modsymmetryperiodic::rflu_sype_augmentcelllists(), rflu_modsymmetryperiodic::rflu_sype_augmentvertexlists(), rflu_modsymmetryperiodic::rflu_sype_buildp2vclist(), rflu_modsymmetryperiodic::rflu_sype_buildp2vclistserial(), rflu_modsymmetryperiodic::rflu_sype_buildtransforms(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modsymmetryperiodic::rflu_sype_createp2vclist(), rflu_modsymmetryperiodic::rflu_sype_createvertexmaps(), rflu_modsymmetryperiodic::rflu_sype_destroyp2vclist(), rflu_modsymmetryperiodic::rflu_sype_getactualserialcell(), rflu_modsymmetryperiodic::rflu_sype_getrelatedvertex(), rflu_modsymmetryperiodic::rflu_sype_havesypepatches(), rflu_modsymmetryperiodic::rflu_sype_imposevertexmap(), rflu_modsymmetryperiodic::rflu_sype_readtransforms(), rflu_modsymmetryperiodic::rflu_sype_setsypepatchesflag(), rflu_modsymmetryperiodic::rflu_sype_writetransforms(), rflu_modtecplot::rflu_tec_builddatafieldsurf(), rflu_modtecplot::rflu_tec_builddatafieldvol(), rflu_modtecplot::rflu_tec_builddatapatch(), rflu_modtecplot::rflu_tec_builddatapatchstats(), rflu_modtecplot::rflu_tec_buildheaderfield(), rflu_modtecplot::rflu_tec_buildheaderpatch(), rflu_modtecplot::rflu_tec_buildheaderpatchstats(), rflu_modtecplotutils::rflu_tec_closefile(), rflu_modtecplot::rflu_tec_closefilefield(), rflu_modtecplot::rflu_tec_closefilepatch(), rflu_modtecplot::rflu_tec_closefilepatchstats(), rflu_modtecplot::rflu_tec_closefilepnt(), rflu_modtecplot::rflu_tec_destroydatafieldsurf(), rflu_modtecplot::rflu_tec_destroydatafieldvol(), rflu_modtecplot::rflu_tec_destroydatapatch(), rflu_modtecplot::rflu_tec_init(), rflu_modtecplotutils::rflu_tec_openfile(), rflu_modtecplot::rflu_tec_openfilefield(), rflu_modtecplot::rflu_tec_openfilepatch(), rflu_modtecplot::rflu_tec_openfilepatchstats(), rflu_modtecplot::rflu_tec_openfilepnt(), rflu_modtecplot::rflu_tec_writefilefieldsurf(), rflu_modtecplot::rflu_tec_writefilefieldvol(), rflu_modtecplot::rflu_tec_writefilepatch(), rflu_modtecplot::rflu_tec_writefilepnt(), rflu_modtecplotutils::rflu_tec_writezonecellsspecial(), rflu_modtecplotutils::rflu_tec_writezonefacesspecial(), rflu_modtecplotutils::rflu_tec_writezoneinterf(), rflu_modtecplotutils::rflu_tec_writezonesurf(), rflu_modtecplotutils::rflu_tec_writezonesurfmixed(), rflu_modtecplotutils::rflu_tec_writezonevol(), rflu_modgeometrytools::rflu_testinboundbox(), rflu_modboundarytests::rflu_testisboundarycell(), rflu_modboundarytests::rflu_testisboundaryvertex(), rflu_modgeometrytools::rflu_testvectorcartaxisaligned(), rflu_timestepinviscid(), rflu_timestepping(), rflu_timestepviscous(), rflu_modthrustspecimpulse::rflu_tsi_closeglobalvals(), rflu_modthrustspecimpulse::rflu_tsi_computeglobalthrustsi(), rflu_modthrustspecimpulse::rflu_tsi_openglobalvals(), rflu_modthrustspecimpulse::rflu_tsi_printglobalvals(), rflu_modthrustspecimpulse::rflu_tsi_writeglobalvals(), rflu_modhashtable::rflu_unhashbface(), rflu_updateboundaryvalues(), rflu_updateinbuffgm(), rflu_updateinbuffwrapper(), rflu_user_enforcepatchcoords(), rflu_user_getdeformation(), rflu_userinput(), rflu_modviscousflux::rflu_viscousfluxes(), rflu_modviscousflux::rflu_viscousfluxespatches(), rflu_modweno::rflu_wenogradcells_2d(), rflu_modweno::rflu_wenogradcells_3d(), rflu_modweno::rflu_wenogradcellswrapper(), rflu_modweno::rflu_wenogradcellsxyz_1d(), rflu_modweno::rflu_wenogradcellsxyz_2d(), rflu_modweno::rflu_wenogradcellsxyz_3d(), rflu_modweno::rflu_wenogradcellsxyzfast_2d(), rflu_modweno::rflu_wenogradcellsxyzfast_3d(), rflu_modweno::rflu_wenogradcellsxyzwrapper(), rflu_modreadwritebcdatafile::rflu_writebcdatafile(), rflu_moddimensions::rflu_writedimensions(), rflu_moddimensions::rflu_writedimensionsborders(), rflu_moddimensions::rflu_writedimensionswrapper(), rflu_modreadwriteflow::rflu_writeflowascii(), rflu_modreadwriteflow::rflu_writeflowbinary(), rflu_modreadwriteflow::rflu_writeflowwrapper(), rflu_modforcesmoments::rflu_writeglobalforcesmoments(), rflu_modreadwritegrid::rflu_writegridascii(), rflu_modreadwritegrid::rflu_writegridbinary(), rflu_modreadwritegridspeeds::rflu_writegridspeedsascii(), rflu_modreadwritegridspeeds::rflu_writegridspeedsbinary(), rflu_modreadwritegridspeeds::rflu_writegridspeedswrapper(), rflu_modreadwritegrid::rflu_writegridwrapper(), rflu_writeintegrals1245oles(), rflu_modcellmapping::rflu_writeloc2globcellmapping(), rflu_modextractflowdata::rflu_writemeshbump(), rflu_modpatchcoeffs::rflu_writepatchcoeffsascii(), rflu_modpatchcoeffs::rflu_writepatchcoeffsbinary(), rflu_modpatchcoeffs::rflu_writepatchcoeffswrapper(), rflu_writepostinfo(), rflu_modregionmapping::rflu_writeregionmappingfile(), rflu_writerestartinfo(), rflu_writespecialcells(), rflu_writestat(), rflu_writestatsfileoles(), rflu_modtetmesh::rflu_writesurfgridtetmesh(), rflu_writeversionstring(), rflu_zerovirtualcellvars(), rflucells(), rfluconv(), rfluinit(), rflupart(), rflupick(), rflupost(), rkinitgeneric(), rkinitmp(), rkinitpointscalar(), rkinitsd(), rkupdategeneric(), rkupdatemp(), rkupdatepointscalar(), rocflo_2dto3d(), rocflo_blocks(), rocflo_init(), rocflo_post(), rocflo_split(), rocflo_surf(), rocflo_toflu(), rocpart_post(), rocvav_post(), rungekuttamp(), rvav_blasiussolution(), rvav_computeanalyticalsolution(), rvav_computeerror(), rvav_computesimilarfield(), rvav_extractvariables(), rvav_gammbumpsolution(), rvav_plotresults(), rvav_proudmanculicksolution(), rvav_readcomparisonssection(), rvav_readfilestream1(), rvav_readfilestream2(), rvav_readfilestream2analyt(), rvav_readfilestream2comput(), rvav_readfilestream2experm(), rvav_readinputfile(), rvav_readsectionstream1(), rvav_readsectionstream2(), scalegridspeeds(), sourceterms(), sourcetermsmp(), spec_checkuserinput(), spec_derivedinputvalues(), spec_eqeulcorr(), spec_eqeulcorrpatch(), spec_initinputvalues(), spec_initinputvaluesspectype(), spec_printuserinput(), spec_readinputfile(), spec_readspecsection(), spec_readspectypesection(), spec_rflu_allocatememory(), spec_rflu_allocatememoryeev(), spec_rflu_allocatememorysol(), spec_rflu_allocatememorytstep(), spec_rflu_allocatememoryvert(), spec_rflu_deallocatememory(), spec_rflu_deallocatememoryeev(), spec_rflu_deallocatememorysol(), spec_rflu_deallocatememorytstep(), spec_rflu_deallocatememoryvert(), spec_rflu_enforcebounds(), spec_rflu_initflowhardcode(), spec_rflu_initflowscratch(), spec_rflu_modchemistry::spec_rflu_integratechemsrcterm(), spec_rflu_printflowinfo(), spec_rflu_readbcfarfsection(), spec_rflu_readbcinflowsection(), spec_rflu_readbcinjectsection(), spec_rflu_readbcinputfile(), spec_rflu_readbcsectiondummy(), spec_rflu_modreadwritevars::spec_rflu_readcvascii(), spec_rflu_modreadwritevars::spec_rflu_readcvbinary(), spec_rflu_modreadwritevars::spec_rflu_readeevascii(), spec_rflu_modreadwritevars::spec_rflu_readeevbinary(), spec_rflu_seteev(), spec_rflu_setvarinfo(), spec_rflu_sourceterms_gl(), spec_rflu_modreadwritevars::spec_rflu_writecvascii(), spec_rflu_modreadwritevars::spec_rflu_writecvbinary(), spec_rflu_modreadwritevars::spec_rflu_writeeevascii(), spec_rflu_modreadwritevars::spec_rflu_writeeevbinary(), spec_updatedependentvars(), spec_userinput(), splitgrid(), splitquadface(), splittopology(), modstatsroutines::statdatasampling(), modstatsroutines::statmapping(), modstatsroutines::stattimeaccumulation(), modstatsroutines::statwritemp(), turb_allocatememory(), turb_calcmetrics(), turb_calcvortic(), turb_checkparaminput(), turb_coranswalldistov(), turb_coviscousfluxes(), turb_cowlmreadbcsection(), turb_derivedinputvalues(), turb_emsinit(), turb_floextrapintcellscal(), turb_floextrapintcellvec(), turb_floextrapolcellvec(), turb_floextrapolfacevec(), turb_flofacevolume(), turb_flofacewidth(), turb_flofacewidthdummy(), turb_flofacewidthdummyconn(), turb_flofacewidthdummyphys(), turb_flolesaverageface(), turb_flolesgenc2f(), turb_flolesgencocc(), turb_flolesgencocchi(), turb_flolesgencocclo(), turb_flolesgencofchi(), turb_flolesgencofclo(), turb_flolesgencoff(), turb_flolesgencoffhi(), turb_flolesgencofflo(), turb_flolesgenfiltcc(), turb_flolesgenfiltcci(), turb_flolesgenfiltccj(), turb_flolesgenfiltcck(), turb_flolesgenfiltff(), turb_flolesgenfiltffi(), turb_flolesgenfiltffj(), turb_flolesgenfiltffk(), turb_flolesunifiltcc(), turb_flolesunifiltcci(), turb_flolesunifiltccj(), turb_flolesunifiltcck(), turb_flolesunifiltff(), turb_flolesunifiltffi(), turb_flolesunifiltffj(), turb_flolesunifiltffk(), turb_floransbcondinflow(), turb_floransbcondinjection(), turb_floransbcondnoslipwall(), turb_floransbcondsymmetry(), turb_floransbcondzerograd(), turb_floranscentraldissipation(), turb_floranscorrcornedgecells(), turb_floransexchangedummyconf(), turb_floransexchcornedgecells(), turb_floransrecvcornedgecells(), turb_floransrecvdummyvals(), turb_floranssacentflux(), turb_floranssacentfluxpatch(), turb_floranssaroe1stflux(), turb_floranssaroe2ndflux(), turb_floranssaroefluxpatch(), turb_floranssendcornedgecells(), turb_floranssenddummyconf(), turb_floranssetcornedgecells(), turb_flowlmmetric(), turb_flowlmupdateloglay(), turb_flucv2cons(), turb_flucv2prim(), turb_flufacevolume(), turb_flulesblij(), turb_flulesbmij(), turb_flulesc2f(), turb_getmodelstresscell(), turb_gettvcell(), turb_initgenxinterface(), turb_initinputvalues(), turb_initsolution(), turb_lescalceddyvis(), turb_lescoefdynmixd(), turb_lescoefdynsmag(), turb_lescommunication(), turb_lescontract(), turb_lesesgmodel4(), turb_lesfluxfixsmag(), turb_lesfluxscalsim(), turb_lesgeteddyvis(), turb_leshij(), turb_leslij(), turb_lesmij(), turb_lesrkinit(), turb_lestestrhov(), turb_printuserinput(), turb_ransconvectivefluxes(), turb_ransemsinit(), turb_ransemsupdate(), turb_ransnumericaldissipation(), turb_ransrkinit(), turb_ranssageteddyvis(), turb_ranssasourceterms(), turb_ranssavisflux(), turb_ranssavisfluxpatch(), turb_ranssourceterms(), turb_ranstotaltv(), turb_ranswalldistovpatch(), turb_ranszerodummycells(), turb_readbcinputfile(), turb_readinputfile(), turb_readturbsection(), turb_rflo_ransallocdatabuffers(), turb_rflo_ransbndconditionsrecv(), turb_rflo_ransbndconditionssend(), turb_rflo_ransbndconditionsset(), turb_rflo_ransclearsendrequests(), turb_rflo_ransressmoothing(), turb_rflo_ransressmoothingcoeff(), turb_rflo_ransspectralradii(), turb_rflo_readsolution(), turb_rflo_readsolutionregion(), turb_rflo_writesolution(), turb_modpostflu::turb_rflu_allocmempost(), turb_modpostflu::turb_rflu_allocmempostvert(), turb_rflu_deallocatememory(), turb_modpostflu::turb_rflu_deallocmempost(), turb_modpostflu::turb_rflu_deallocmempostvert(), turb_rflu_readsolutionascii(), turb_rflu_readsolutionbinary(), turb_rflu_writesolutionascii(), turb_rflu_writesolutionbinary(), turb_rkinit(), turb_solutionupdate(), turb_statccollector(), turb_statmapping(), turb_userinput(), turb_vfluxhybrid(), turb_vfluxhybridpatch(), turb_visfluxeddy(), turb_visfluxeddypatch(), turb_wlmfluxpatch(), turb_wlminitia(), turb_wlmreyanalogy(), turb_wlmtauwallmapping(), turb_wlmupdate(), turb_wlmupdatebndlay(), updateboundaryconditionsmp(), updatedependentvarsmp(), updatetbc(), updatetbcpiecewise(), updatetbcsinusoidal(), updatetbcstochastic(), updatetbcwhitenoise(), viscousfluxes(), viscousfluxesmp(), prep_modbcdistribution::writebctofile(), writeconvergence(), writeflucellmap(), writefludimens(), writeflugrid(), writegeneric(), writeprobe(), writesurfacegrid(), writetecplotascii(), writetecplotbinary(), writethrust(), writetotalmass(), zerodummycellsmp(), and zeroresidualsmp().
Member Data Documentation
integer, parameter err_allocate = 10
Definition at line 62 of file ModError.F90.
integer, parameter err_allocate_adaptive = 1057
Definition at line 170 of file ModError.F90.
integer, parameter err_allocated = 13
Definition at line 62 of file ModError.F90.
integer, parameter err_associated = 12
Definition at line 62 of file ModError.F90.
integer, parameter err_bc_invalid = 1070
Definition at line 170 of file ModError.F90.
integer, parameter err_bc_varname = 36
Definition at line 80 of file ModError.F90.
integer, parameter err_bcdata_value_invalid = 1035
Definition at line 170 of file ModError.F90.
integer, parameter err_bcval_extra = 39
Definition at line 80 of file ModError.F90.
integer, parameter err_bcval_missing = 32
Definition at line 80 of file ModError.F90.
integer, parameter err_bcvar_value_invalid = 1080
Definition at line 170 of file ModError.F90.
integer, parameter err_bf2bg_inconsistent = 1032
Definition at line 170 of file ModError.F90.
integer, parameter err_bf2csorted_invalid = 1062
Definition at line 170 of file ModError.F90.
integer, parameter err_bface_list_extrema = 1014
Definition at line 170 of file ModError.F90.
integer, parameter err_bfacemembs_invalid = 1030
Definition at line 170 of file ModError.F90.
integer, parameter err_binary_search = 91
Definition at line 122 of file ModError.F90.
integer, parameter err_border_index_invalid = 1075
Definition at line 170 of file ModError.F90.
integer, parameter err_bufferdim_mismatch = 1051
Definition at line 170 of file ModError.F90.
integer, parameter err_bvert_list_invalid = 1022
Definition at line 170 of file ModError.F90.
integer, parameter err_c2cskey_inconsistent = 1033
Definition at line 170 of file ModError.F90.
integer, parameter err_c2flist_invalid = 1028
Definition at line 170 of file ModError.F90.
integer, parameter err_c2vlist_invalid = 1403
Definition at line 266 of file ModError.F90.
integer, parameter err_cell_kind_check = 1019
Definition at line 170 of file ModError.F90.
integer, parameter err_cell_kind_invalid = 1046
Definition at line 170 of file ModError.F90.
integer, parameter err_cell_not_found = 1042
Definition at line 170 of file ModError.F90.
integer, parameter err_cell_type = 1003
Definition at line 170 of file ModError.F90.
integer, parameter err_cell_type_invalid = 1047
Definition at line 170 of file ModError.F90.
integer, parameter err_cellgrad_unavailable = 1031
Definition at line 170 of file ModError.F90.
integer, parameter err_compile_option = 9
Definition at line 51 of file ModError.F90.
integer, parameter err_constr_invalid = 1063
Definition at line 170 of file ModError.F90.
integer, parameter err_cv_state_invalid = 1902
Definition at line 283 of file ModError.F90.
integer, parameter err_datadim_mismatch = 1050
Definition at line 170 of file ModError.F90.
integer, parameter err_dcuhre_output = 1510
Definition at line 275 of file ModError.F90.
integer, parameter err_deallocate = 11
Definition at line 62 of file ModError.F90.
integer, parameter err_denumber_list = 1037
Definition at line 170 of file ModError.F90.
integer, parameter err_dependent_input = 15
Definition at line 67 of file ModError.F90.
integer, parameter err_dimens_invalid = 1016
Definition at line 170 of file ModError.F90.
integer, parameter err_discr_invalid = 1059
Definition at line 170 of file ModError.F90.
integer, parameter err_distrib_invalid = 1034
Definition at line 170 of file ModError.F90.
integer, parameter err_diter_negative = 44
Definition at line 91 of file ModError.F90.
integer, parameter err_dtime_negative = 43
Definition at line 91 of file ModError.F90.
integer, parameter err_edgelist_invalid = 1023
Definition at line 170 of file ModError.F90.
integer, parameter err_exceed_dimens = 1906
Definition at line 283 of file ModError.F90.
integer, parameter err_exceeds_decl_mem = 5
Definition at line 51 of file ModError.F90.
integer, parameter err_external_funct = 4
Definition at line 51 of file ModError.F90.
integer, parameter err_face_inverted = 73
Definition at line 108 of file ModError.F90.
integer, parameter err_face_kind = 1029
Definition at line 170 of file ModError.F90.
integer, parameter err_face_normal_invalid = 1066
Definition at line 170 of file ModError.F90.
integer, parameter err_face_nvert_invalid = 1020
Definition at line 170 of file ModError.F90.
integer, parameter err_face_orient = 1404
Definition at line 266 of file ModError.F90.
integer, parameter err_face_split = 72
Definition at line 108 of file ModError.F90.
integer, parameter err_facelist_invalid = 1015
Definition at line 170 of file ModError.F90.
integer, parameter err_facesum = 1011
Definition at line 170 of file ModError.F90.
integer, parameter err_facetype_invalid = 1402
Definition at line 266 of file ModError.F90.
integer, parameter err_facevec_sum = 70
Definition at line 108 of file ModError.F90.
integer, parameter err_file_close = 21
Definition at line 69 of file ModError.F90.
integer, parameter err_file_exist = 24
Definition at line 69 of file ModError.F90.
integer, parameter err_file_open = 20
Definition at line 69 of file ModError.F90.
integer, parameter err_file_read = 22
Definition at line 69 of file ModError.F90.
integer, parameter err_file_write = 23
Definition at line 69 of file ModError.F90.
integer, parameter err_filedest_invalid = 1903
Definition at line 283 of file ModError.F90.
integer, parameter err_flatflag_inconsistent = 1073
Definition at line 170 of file ModError.F90.
integer, parameter err_gasmodel_discr_mismatch = 1065
Definition at line 170 of file ModError.F90.
integer, parameter err_gasmodel_invalid = 1064
Definition at line 170 of file ModError.F90.
integer, parameter err_grad_index = 65
Definition at line 106 of file ModError.F90.
integer, parameter err_grad_mismatch = 100
Definition at line 125 of file ModError.F90.
integer, parameter err_grid_dimensions = 509
Definition at line 145 of file ModError.F90.
integer, parameter err_grid_dumcells = 510
Definition at line 145 of file ModError.F90.
integer, parameter err_grid_level = 60
Definition at line 104 of file ModError.F90.
integer, parameter err_hashtable = 1004
Definition at line 170 of file ModError.F90.
integer, parameter err_illegal_value = 7
Definition at line 51 of file ModError.F90.
integer, parameter err_indmfmixt_invalid = 1036
Definition at line 170 of file ModError.F90.
integer, parameter err_infinite_loop = 1900
Definition at line 283 of file ModError.F90.
integer, parameter err_inrt_module = 5001
Definition at line 391 of file ModError.F90.
integer, parameter err_invalid_marker = 1100
Definition at line 252 of file ModError.F90.
integer, parameter err_invalid_ncells = 1101
Definition at line 252 of file ModError.F90.
integer, parameter err_invalid_nvars = 1102
Definition at line 252 of file ModError.F90.
integer, parameter err_invalid_value = 201
Definition at line 127 of file ModError.F90.
integer, parameter err_lapack_output = 1500
Definition at line 275 of file ModError.F90.
integer, parameter err_lubound_mismatch = 1056
Definition at line 170 of file ModError.F90.
integer, parameter err_merge_sorted = 90
Definition at line 122 of file ModError.F90.
integer, parameter err_missing_value = 260
Definition at line 134 of file ModError.F90.
integer, parameter err_movepatch_bc_invalid = 1017
Definition at line 170 of file ModError.F90.
integer, parameter err_movepatch_bc_notset = 1025
Definition at line 170 of file ModError.F90.
integer, parameter err_mp_allornone = 250
Definition at line 132 of file ModError.F90.
integer, parameter err_mpi_output = 1540
Definition at line 275 of file ModError.F90.
integer, parameter err_mpi_tagmax = 1541
Definition at line 275 of file ModError.F90.
integer, parameter err_mpi_trouble = 50
Definition at line 98 of file ModError.F90.
integer, parameter err_nbfaces_wrong = 1001
Definition at line 170 of file ModError.F90.
integer, parameter err_nborders_invalid = 1044
Definition at line 170 of file ModError.F90.
integer, parameter err_nbvert_estimate = 1012
Definition at line 170 of file ModError.F90.
integer, parameter err_nbvert_extrema = 1013
Definition at line 170 of file ModError.F90.
integer, parameter err_ncells_special_max = 1026
Definition at line 170 of file ModError.F90.
integer, parameter err_ncells_wrong = 1008
Definition at line 170 of file ModError.F90.
integer, parameter err_ndimens_invalid = 1400
Definition at line 266 of file ModError.F90.
integer, parameter err_ndp_invalid = 1407
Definition at line 266 of file ModError.F90.
integer, parameter err_nedges_estimate = 1006
Definition at line 170 of file ModError.F90.
integer, parameter err_nedges_wrong = 1018
Definition at line 170 of file ModError.F90.
integer, parameter err_negative_posdef = 200
Definition at line 127 of file ModError.F90.
integer, parameter err_nfaces_estimate = 1007
Definition at line 170 of file ModError.F90.
integer, parameter err_nfaces_special_max = 1027
Definition at line 170 of file ModError.F90.
integer, parameter err_nfaces_wrong = 1005
Definition at line 170 of file ModError.F90.
integer, parameter err_nfacescut_invalid = 1041
Definition at line 170 of file ModError.F90.
integer, parameter err_no_bcspecified = 31
Definition at line 80 of file ModError.F90.
integer, parameter err_no_bcswitch = 33
Definition at line 80 of file ModError.F90.
integer, parameter err_no_procmap = 51
Definition at line 98 of file ModError.F90.
integer, parameter err_no_procmatch = 52
Definition at line 98 of file ModError.F90.
integer, parameter err_none = 0
Definition at line 51 of file ModError.F90.
integer, parameter err_nprocs_mismatch = 1053
Definition at line 170 of file ModError.F90.
integer, parameter err_nregions_mismatch = 1052
Definition at line 170 of file ModError.F90.
integer, parameter err_ntype_invalid = 1406
Definition at line 266 of file ModError.F90.
integer, parameter err_num_bc_virtual = 1054
Definition at line 170 of file ModError.F90.
integer, parameter err_number_cells = 512
Definition at line 145 of file ModError.F90.
integer, parameter err_nvert_estimate = 1040
Definition at line 170 of file ModError.F90.
integer, parameter err_nvertshared_mismatch = 1055
Definition at line 170 of file ModError.F90.
integer, parameter err_nzones_invalid = 1401
Definition at line 266 of file ModError.F90.
integer, parameter err_oles_flowmodel = 1201
Definition at line 256 of file ModError.F90.
integer, parameter err_oles_stencil = 1200
Definition at line 256 of file ModError.F90.
integer, parameter err_option_type = 80
Definition at line 120 of file ModError.F90.
integer, parameter err_optional_missing = 1039
Definition at line 170 of file ModError.F90.
integer, parameter err_order_invalid = 1060
Definition at line 170 of file ModError.F90.
integer, parameter err_partition_invalid = 1049
Definition at line 170 of file ModError.F90.
integer, parameter err_patch_2align = 501
Definition at line 145 of file ModError.F90.
integer, parameter err_patch_bc_inconsistent = 1071
Definition at line 170 of file ModError.F90.
integer, parameter err_patch_dimens = 504
Definition at line 145 of file ModError.F90.
integer, parameter err_patch_noalign = 502
Definition at line 145 of file ModError.F90.
integer, parameter err_patch_nosource = 503
Definition at line 145 of file ModError.F90.
integer, parameter err_patch_not_aligned = 1078
Definition at line 170 of file ModError.F90.
integer, parameter err_patch_not_flat = 1077
Definition at line 170 of file ModError.F90.
integer, parameter err_patch_notcovered = 505
Definition at line 145 of file ModError.F90.
integer, parameter err_patch_number = 514
Definition at line 145 of file ModError.F90.
integer, parameter err_patch_numbering = 1002
Definition at line 170 of file ModError.F90.
integer, parameter err_patch_offset = 53
Definition at line 98 of file ModError.F90.
integer, parameter err_patch_overlap = 507
Definition at line 145 of file ModError.F90.
integer, parameter err_patch_overspec = 508
Definition at line 145 of file ModError.F90.
integer, parameter err_patch_range = 35
Definition at line 80 of file ModError.F90.
integer, parameter err_patch_renumflag = 1021
Definition at line 170 of file ModError.F90.
integer, parameter err_petsc_output = 1530
Definition at line 275 of file ModError.F90.
integer, parameter err_peul_module = 4001
Definition at line 374 of file ModError.F90.
integer, parameter err_plag_module = 3001
Definition at line 349 of file ModError.F90.
integer, parameter err_post_nservers_invalid = 1905
Definition at line 283 of file ModError.F90.
integer, parameter err_post_output_format_invalid = 1904
Definition at line 283 of file ModError.F90.
integer, parameter err_prec_range = 1901
Definition at line 283 of file ModError.F90.
integer, parameter err_previous_errors = 3
Definition at line 51 of file ModError.F90.
integer, parameter err_probe_location = 26
Definition at line 69 of file ModError.F90.
integer, parameter err_probe_specified = 27
Definition at line 69 of file ModError.F90.
integer, parameter err_proc2reg_mapping = 1038
Definition at line 170 of file ModError.F90.
integer, parameter err_proc_mismatch = 54
Definition at line 98 of file ModError.F90.
integer, parameter err_rand_seed_type_invalid = 400
Definition at line 139 of file ModError.F90.
integer, parameter err_reached_default = 2
Definition at line 51 of file ModError.F90.
integer, parameter err_reconst_invalid = 1058
Definition at line 170 of file ModError.F90.
integer, parameter err_region_id_invalid = 1072
Definition at line 170 of file ModError.F90.
integer, parameter err_region_id_not_found = 1076
Definition at line 170 of file ModError.F90.
integer, parameter err_region_ids_invalid = 1045
Definition at line 170 of file ModError.F90.
integer, parameter err_region_number = 513
Definition at line 145 of file ModError.F90.
integer, parameter err_region_range = 500
Definition at line 145 of file ModError.F90.
integer, parameter err_register_fun = 1
Definition at line 51 of file ModError.F90.
integer, parameter err_rk_scheme_invalid = 301
Definition at line 136 of file ModError.F90.
integer, parameter err_sec_read_twice = 240
Definition at line 130 of file ModError.F90.
integer, parameter err_solver_type_invalid = 1061
Definition at line 170 of file ModError.F90.
integer, parameter err_spec_maxeqn = 6003
Definition at line 432 of file ModError.F90.
integer, parameter err_spec_module = 6001
Definition at line 432 of file ModError.F90.
integer, parameter err_spec_nspec_invalid = 6005
Definition at line 432 of file ModError.F90.
integer, parameter err_spec_ntypes = 6002
Definition at line 432 of file ModError.F90.
integer, parameter err_spec_props_invalid = 6004
Definition at line 432 of file ModError.F90.
integer, parameter err_spec_source_type_invalid = 6006
Definition at line 432 of file ModError.F90.
integer, parameter err_srcregion_off = 511
Definition at line 145 of file ModError.F90.
integer, parameter err_steady = 45
Definition at line 91 of file ModError.F90.
integer, parameter err_stencildimens_invalid = 1068
Definition at line 170 of file ModError.F90.
integer, parameter err_stencilmember_invalid = 1069
Definition at line 170 of file ModError.F90.
integer, parameter err_stopfile_found = 29
Definition at line 69 of file ModError.F90.
integer, parameter err_string_invalid = 1405
Definition at line 266 of file ModError.F90.
integer, parameter err_string_read = 1907
Definition at line 283 of file ModError.F90.
integer, parameter err_svert_list_invalid = 1024
Definition at line 170 of file ModError.F90.
integer, parameter err_system_command = 8
Definition at line 51 of file ModError.F90.
integer, parameter err_tbc_noninit = 38
Definition at line 80 of file ModError.F90.
integer, parameter err_tecplot_filecntr = 1521
Definition at line 275 of file ModError.F90.
integer, parameter err_tecplot_output = 1520
Definition at line 275 of file ModError.F90.
integer, parameter err_time_global = 42
Definition at line 91 of file ModError.F90.
integer, parameter err_time_grid = 40
Definition at line 91 of file ModError.F90.
integer, parameter err_time_solution = 41
Definition at line 91 of file ModError.F90.
integer, parameter err_tolerict_invalid = 1067
Definition at line 170 of file ModError.F90.
integer, parameter err_turb_module = 2001
Definition at line 296 of file ModError.F90.
integer, parameter err_unknown_bc = 30
Definition at line 80 of file ModError.F90.
integer, parameter err_unknown_format = 25
Definition at line 69 of file ModError.F90.
integer, parameter err_unknown_option = 6
Definition at line 51 of file ModError.F90.
integer, parameter err_unknown_viscmodel = 300
Definition at line 136 of file ModError.F90.
integer, parameter err_val_bcswitch = 34
Definition at line 80 of file ModError.F90.
integer, parameter err_val_bcval = 37
Definition at line 80 of file ModError.F90.
integer, parameter err_val_undefined = 28
Definition at line 69 of file ModError.F90.
integer, parameter err_vertex_kind_invalid = 1048
Definition at line 170 of file ModError.F90.
integer, parameter err_vertex_match_failed = 1074
Definition at line 170 of file ModError.F90.
integer, parameter err_vertex_not_found = 1043
Definition at line 170 of file ModError.F90.
integer, parameter err_vertex_number = 1000
Definition at line 170 of file ModError.F90.
integer, parameter err_virtualcells_notdb2 = 1079
Definition at line 170 of file ModError.F90.
integer, parameter err_volume_corners = 901
Definition at line 161 of file ModError.F90.
integer, parameter err_volume_diff = 1009
Definition at line 170 of file ModError.F90.
integer, parameter err_volume_edges = 900
Definition at line 161 of file ModError.F90.
integer, parameter err_volume_negative = 1010
Definition at line 170 of file ModError.F90.
integer, parameter err_volume_size = 71
Definition at line 108 of file ModError.F90.
integer, parameter err_wrong_regionface = 506
Definition at line 145 of file ModError.F90.
integer, parameter limit_infinite_loop = 1E6
Definition at line 168 of file ModError.F90.
The documentation for this module was generated from the following file:
ModError.F90