Rocstar: flowprobe Class Reference
flowprobe Class Reference
#include <ProbeMon.H>
Public Types
enum probedata {
TIME =0, RHO, U, V,
W, P, T, NPROBEDATA
}
Public Member Functions
flowprobe ()
flowprobe (const flowprobe &inFlowProbe)
void Clear ()
unsigned int ReadProbeData (std::istream &inStream)
void WriteData (std::ostream &outStream, bool writeLoc=false)
void SetLocation (double xLoc, double yLoc, double zLoc)
Protected Attributes
double locX
double locY
double locZ
Detailed Description
Definition at line 13 of file ProbeMon.H.
Member Enumeration Documentation
enum probedata
Enumerator
TIME
RHO
U
V
W
P
T
NPROBEDATA
Definition at line 16 of file ProbeMon.H.
 {TIME=0,RHO,U,V,W,P,T,NPROBEDATA};
Constructor & Destructor Documentation
flowprobe () inline
Definition at line 17 of file ProbeMon.H.
References flowprobe::NPROBEDATA.
     {
       this->resize(NPROBEDATA);
     };
flowprobe (const flowprobe & inFlowProbe) inline
Definition at line 21 of file ProbeMon.H.
References flowprobe::NPROBEDATA, flowprobe::P, flowprobe::RHO, flowprobe::T, flowprobe::TIME, flowprobe::U, flowprobe::V, and flowprobe::W.
     {
       this->resize(NPROBEDATA);
       (*this)[TIME] = inFlowProbe[TIME];
       (*this)[RHO]  = inFlowProbe[RHO];
       (*this)[U]    = inFlowProbe[U];
       (*this)[V]    = inFlowProbe[V];
       (*this)[W]    = inFlowProbe[W];
       (*this)[P]    = inFlowProbe[P];
       (*this)[T]    = inFlowProbe[T];
     };
Member Function Documentation
void Clear () inline
Definition at line 32 of file ProbeMon.H.
References flowprobe::NPROBEDATA.
Referenced by flowprobe::ReadProbeData().
     {
       this->resize(0);
       this->resize(NPROBEDATA);
     };
unsigned int ReadProbeData (std::istream & inStream) inline
Definition at line 37 of file ProbeMon.H.
References flowprobe::Clear(), flowprobe::P, flowprobe::RHO, flowprobe::T, flowprobe::TIME, cimg_library::cimg::time(), flowprobe::U, flowprobe::V, and flowprobe::W.
Referenced by main().
     {
       Clear();
       std::string probeLine;
       while(std::getline(inStream,probeLine)){
         if(probeLine[0] == '#')
           continue;
         std::istringstream Instr(probeLine);
         double time  = 0;
         double rho   = 0;
         double rhou  = 0;
         double rhov  = 0;
         double rhow  = 0;
         double press = 0;
         double temp  = 0;
         Instr >> time >> rho >> rhou >> rhov >> rhow >> press >> temp;
         (*this)[TIME].push_back(time);
         (*this)[RHO].push_back(rho);
         (*this)[U].push_back(rhou/rho);
         (*this)[V].push_back(rhov/rho);
         (*this)[W].push_back(rhow/rho);
         (*this)[P].push_back(press);
         (*this)[T].push_back(temp);
       }
       return((*this)[TIME].size());
     };
void SetLocation (double xLoc, double yLoc, double zLoc) inline
Definition at line 76 of file ProbeMon.H.
References flowprobe::locX, flowprobe::locY, and flowprobe::locZ.
Referenced by main().
     {
       locX = xLoc;
       locY = yLoc;
       locZ = zLoc;
     };
void WriteData (std::ostream & outStream, bool writeLoc = false) inline
Definition at line 63 of file ProbeMon.H.
References i, j, flowprobe::locX, flowprobe::locY, flowprobe::locZ, flowprobe::NPROBEDATA, and flowprobe::TIME.
Referenced by main().
     {
       unsigned int nTimes = (*this)[TIME].size();
       for(unsigned int i = 0;i < nTimes;i++){
         if(writeLoc){
           outStream << locX << " " << locY << " " << locZ << " ";
         }
         for(unsigned int j = 0;j < NPROBEDATA;j++){
           outStream << (*this)[j][i] << " ";
         }
         outStream << std::endl;
       }
     };
Member Data Documentation
double locX protected
Definition at line 81 of file ProbeMon.H.
Referenced by flowprobe::SetLocation(), and flowprobe::WriteData().
double locY protected
Definition at line 84 of file ProbeMon.H.
Referenced by flowprobe::SetLocation(), and flowprobe::WriteData().
double locZ protected
Definition at line 85 of file ProbeMon.H.
Referenced by flowprobe::SetLocation(), and flowprobe::WriteData().
The documentation for this class was generated from the following file:
ProbeMon.H