Rocstar: Rocblas Class Reference
Rocblas Class Reference
#include <Rocblas.h>
Classes
struct acosa
struct assn
struct limit1v
struct maxof
struct maxv
struct minv
struct nega
struct random
struct random< double >
struct sqrta
struct sumv
struct swapp
Static Public Member Functions
static void init (const std::string &name)
Creates window for Rocblas and registers functions.
static void finalize (const std::string &name)
Delete window for Rocblas.
static void add (const Attribute *x, const Attribute *y, Attribute *z)
Operation wrapper for addition.
static void sub (const Attribute *x, const Attribute *y, Attribute *z)
Operation wrapper for subtraction.
static void mul (const Attribute *x, const Attribute *y, Attribute *z)
Operation wrapper for multiplication.
static void limit1 (const Attribute *x, const Attribute *y, Attribute *z)
Operation wrapper for limit1.
static void div (const Attribute *x, const Attribute *y, Attribute *z)
Operation wrapper for division.
static void add_scalar (const Attribute *x, const void *y, Attribute *z, int swap=0)
Operation wrapper for addition with y as a scalar pointer.
static void sub_scalar (const Attribute *x, const void *y, Attribute *z, int swap=0)
Operation wrapper for subtraction with y as a scalar pointer.
static void mul_scalar (const Attribute *x, const void *y, Attribute *z, int swap=0)
Operation wrapper for multiplication with y as a scalar pointer.
static void div_scalar (const Attribute *x, const void *y, Attribute *z, int swap=0)
Operation wrapper for division with y as a scalar pointer.
static void maxof_scalar (const Attribute *x, const void *y, Attribute *z, int swap=0)
Operation wrapper for addition with y as a scalar pointer.
static void dot (const Attribute *x, const Attribute *y, Attribute *z, const Attribute *mults=NULL)
Wrapper for dot product.
static void dot_scalar (const Attribute *x, const Attribute *y, void *z, const Attribute *mults=NULL)
Wrapper for 2-norm with z as a scalar pointer.
static void dot_MPI (const Attribute *x, const Attribute *y, Attribute *z, const MPI_Comm *comm=NULL, const Attribute *mults=NULL)
Wrapper for dot product.
static void dot_scalar_MPI (const Attribute *x, const Attribute *y, void *z, const MPI_Comm *comm=NULL, const Attribute *mults=NULL)
Wrapper for 2-norm with z as a scalar pointer.
static void nrm2 (const Attribute *x, Attribute *y, const Attribute *mults=NULL)
Wrapper for 2-norm.
static void nrm2_scalar (const Attribute *x, void *y, const Attribute *mults=NULL)
Wrapper for 2-norm with y as a scalar pointer.
static void nrm2_MPI (const Attribute *x, Attribute *y, const MPI_Comm *comm=NULL, const Attribute *mults=NULL)
Wrapper for 2-norm with MPI.
static void nrm2_scalar_MPI (const Attribute *x, void *y, const MPI_Comm *comm, const Attribute *mults=NULL)
Wrapper for 2-norm with y as a scalar pointer with MPI.
static void swap (Attribute *x, Attribute *y)
Wrapper for swap.
static void copy (const Attribute *x, Attribute *y)
Wrapper for copy.
static void rand (const Attribute *a, Attribute *z)
Generate a random number between 0 and $a$ for each entry in z.
static void copy_scalar (const void *x, Attribute *y)
Operation wrapper for copy (x is a scalar pointer).
static void rand_scalar (const void *a, Attribute *z)
Generate a random number between 0 and $a$ for each entry in z.
static void neg (const Attribute *x, Attribute *y)
Wrapper for neg (y=-x).
static void sqrt (const Attribute *x, Attribute *y)
Wrapper for sqrt (y=sqrt(x)).
static void acos (const Attribute *x, Attribute *y)
Wrapper for acos (y=acos(x)).
static void max_MPI (const Attribute *x, Attribute *y, const MPI_Comm *comm=NULL)
Wrapper for max.
static void max_scalar_MPI (const Attribute *x, void *y, const MPI_Comm *comm=NULL)
Operation wrapper for max (y is a scalar pointer).
static void min_MPI (const Attribute *x, Attribute *y, const MPI_Comm *comm=NULL)
Wrapper for min.
static void min_scalar_MPI (const Attribute *x, void *y, const MPI_Comm *comm=NULL)
Operation wrapper for min (y is a scalar pointer).
static void sum_MPI (const Attribute *x, Attribute *y, const MPI_Comm *comm=NULL)
Wrapper for sum.
static void sum_scalar_MPI (const Attribute *x, void *y, const MPI_Comm *comm=NULL)
Operation wrapper for sum (y is a scalar pointer).
static void axpy (const Attribute *a, const Attribute *x, const Attribute *y, Attribute *z)
Operation wrapper for z = a * x + y.
static void axpy_scalar (const void *a, const Attribute *x, const Attribute *y, Attribute *z)
Operation wrapper for z = a * x + y (a is a scalar pointer).
Protected Types
enum {
BLAS_VOID, BLAS_SCALAR, BLAS_VEC, BLAS_SCNE,
BLAS_VEC2D
}
Static Protected Member Functions
template<class FuncType , int ytype>
static void calc (Attribute *z, const Attribute *x, const void *yin, FuncType opp, bool swap=false)
Performs the operation: z = x op y.
template<class data_type , int ztype>
static void calcDot (void *zout, const Attribute *x, const Attribute *y, const MPI_Comm *comm=NULL, const Attribute *mults=NULL)
Performs the operation: z = <x, y>
template<class FuncType , int ytype>
static void gen2arg (Attribute *z, void *yin, FuncType opp)
Performs the operation opp(x, y)
template<class data_type , int atype>
static void axpy_gen (const void *a, const Attribute *x, const Attribute *y, Attribute *z)
Performs the operation: z = a*x + y.
template<class FuncType >
static void calcChoose (const Attribute *x, const Attribute *y, Attribute *z, FuncType opp)
Chooses which calc function to call based on type of y.
template<class Op >
static void copy_helper (const Attribute *x, Attribute *z)
template<int attr_type>
static int get_stride (const Attribute *attr)
template<class data_type , int attr_type, bool is_staggered>
static data_type & getref (data_type *base, const int r, const int c, const int nc)
template<class data_type , int attr_type, bool is_staggered>
static const data_type & getref (const data_type *base, const int r, const int c, const int nc)
template<class OPint , class OPdbl , int OPMPI>
static void reduce_MPI (const Attribute *x, Attribute *z, const MPI_Comm *comm, int, double)
template<class OPint , class OPdbl , int OPMPI>
static void reduce_scalar_MPI (const Attribute *x, void *y, const MPI_Comm *comm, int, double)
static std::string to_str (int i)
Private Types
typedef unsigned int Size
Detailed Description
Definition at line 37 of file Rocblas.h.
Member Typedef Documentation
typedef unsigned int Size private
Definition at line 38 of file Rocblas.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
BLAS_VOID
BLAS_SCALAR
BLAS_VEC
BLAS_SCNE
BLAS_VEC2D
Definition at line 259 of file Rocblas.h.
 { BLAS_VOID, BLAS_SCALAR, BLAS_VEC, BLAS_SCNE, BLAS_VEC2D};
Member Function Documentation
void acos (const Attribute * x, Attribute * y) static
Wrapper for acos (y=acos(x)).
Definition at line 545 of file op2args.C.
References BLAS_SCALAR, BLAS_SCNE, BLAS_VEC, BLAS_VEC2D, COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), Attribute::fullname(), Attribute::is_windowed(), Attribute::size_of_components(), x, and z.
Referenced by init().
{
   COM_Type att_type = x->data_type();
   const int xncomp = x->size_of_components();
   if ( att_type == COM_INT || att_type == COM_INTEGER) {
     if ( x->is_windowed()) {
       if ( xncomp == 1)
         gen2arg<acosa<int>,BLAS_SCALAR>(z, const_cast<Attribute*>(x), acosa<int>());
       else
         gen2arg<acosa<int>,BLAS_VEC>(z, const_cast<Attribute*>(x), acosa<int>());
     }
     else {
       if ( xncomp == 1)
         gen2arg<acosa<int>,BLAS_SCNE>(z, const_cast<Attribute*>(x), acosa<int>());
       else
         gen2arg<acosa<int>,BLAS_VEC2D>(z, const_cast<Attribute*>(x), acosa<int>());
     }
   }
   else {
     COM_assertion_msg( att_type==COM_DOUBLE || att_type==COM_DOUBLE_PRECISION,
                        (std::string("Unsupported data type in ")+
                         x->fullname()).c_str());
     if ( x->is_windowed()) {
       if ( xncomp == 1)
         gen2arg<acosa<double>,BLAS_SCALAR>(z, const_cast<Attribute*>(x), acosa<double>());
       else
         gen2arg<acosa<double>,BLAS_VEC>(z, const_cast<Attribute*>(x), acosa<double>());
     }
     else {
       if ( xncomp == 1)
         gen2arg<acosa<double>,BLAS_SCNE>(z, const_cast<Attribute*>(x), acosa<double>());
       else
         gen2arg<acosa<double>,BLAS_VEC2D>(z, const_cast<Attribute*>(x), acosa<double>());
     }
   }
 }
void add (const Attribute * x, const Attribute * y, Attribute * z) static
Operation wrapper for addition.
Definition at line 221 of file op3args.C.
References calcChoose(), COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), and Attribute::fullname().
Referenced by FaceOffset_3::balance_mass(), update_py::burn_get_burning_rate1d(), init(), Window_manifold_2::perturb_mesh(), Rocprop::propagate(), FaceOffset_3::rescale_displacements(), and FaceOffset_3::time_stepping().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calcChoose(x, y, z, std::plus<int>());
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calcChoose(x, y, z, std::plus<double>());
   }
 }
void add_scalar (const Attribute * x, const void * y, Attribute * z, int swap = 0) static
Operation wrapper for addition with y as a scalar pointer.
Definition at line 299 of file op3args.C.
References BLAS_VOID, COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), x, y, and z.
Referenced by init(), and rescale_object().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calc<std::plus<int>,BLAS_VOID>(z, x, y, std::plus<int>(), swap);
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calc<std::plus<double>,BLAS_VOID>(z, x, y, std::plus<double>(), swap);
   }
 }
void axpy (const Attribute * a, const Attribute * x, const Attribute * y, Attribute * z) static
Operation wrapper for z = a * x + y.
Definition at line 170 of file axpy.C.
References COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), Attribute::fullname(), Attribute::is_windowed(), Attribute::size_of_components(), x, y, and z.
Referenced by init().
{
   COM_Type att_type = z->data_type();
   const int ancomp = a->size_of_components();
   if(att_type == COM_INT || att_type == COM_INTEGER) {
     if ( a->is_windowed()) {
       if ( ancomp == 1)
         axpy_gen<int,BLAS_SCALAR>(a, x, y, z);
       else
         axpy_gen<int,BLAS_VEC>(a, x, y, z);
     }
     else {
       if ( ancomp == 1)
         axpy_gen<int,BLAS_SCNE>(a, x, y, z);
       else
         axpy_gen<int,BLAS_VEC2D>(a, x, y, z);
     }
   }
   else {
     COM_assertion_msg( att_type==COM_DOUBLE || att_type==COM_DOUBLE_PRECISION,
                        (std::string("Unsupported data type in ")+
                         z->fullname()).c_str());
     if ( a->is_windowed()) {
       if ( ancomp == 1)
         axpy_gen<double,BLAS_SCALAR>(a, x, y, z);
       else
         axpy_gen<double,BLAS_VEC>(a, x, y, z);
     }
     else {
       if ( ancomp == 1)
         axpy_gen<double,BLAS_SCNE>(a, x, y, z);
       else
         axpy_gen<double,BLAS_VEC2D>(a, x, y, z);
     }
   }
 }
void axpy_gen (const void * a, const Attribute * x, const Attribute * y, Attribute * z) static protected
Performs the operation: z = a*x + y.
Definition at line 27 of file axpy.C.
References BLAS_SCNE, BLAS_VEC, BLAS_VEC2D, BLAS_VOID, COM_assertion_msg, COM_compatible_types(), Attribute::data_type(), Attribute::fullname(), i, Attribute::id(), Attribute::is_windowed(), j, Mesquite::length(), Window::name(), Window::panes(), Attribute::pointer(), s, Attribute::size_of_components(), Attribute::size_of_items(), to_str(), and Attribute::window().
{
   COM_assertion_msg(!x->is_windowed() && !y->is_windowed() && !z->is_windowed(),
                     "Unsupported attribute type");
   COM_assertion_msg( COM_compatible_types(x->data_type(),y->data_type()),
                      (std::string("Incompatible data types between ")+
                      x->fullname()+" and "+y->fullname()).c_str());
   COM_assertion_msg( COM_compatible_types(x->data_type(),z->data_type()),
                      (std::string("Incompatible data types between ")+
                       x->fullname()+" and "+z->fullname()).c_str());
   int num_dims = z->size_of_components();
   COM_assertion_msg(num_dims == x->size_of_components() &&
                     num_dims == y->size_of_components(),
                     (std::string("Numbers of components do not match between ")+
                      x->fullname()+" and "+y->fullname()).c_str());
   std::vector<const Pane*> apanes, xpanes, ypanes;
   std::vector<Pane*> zpanes;
   x->window()->panes(xpanes);
   y->window()->panes(ypanes);
   z->window()->panes(zpanes);
   COM_assertion_msg( xpanes.size() == ypanes.size(),
                      (std::string("Numbers of panes do not match between ")+
                       x->window()->name()+" and "+y->window()->name()).c_str());
   COM_assertion_msg( xpanes.size() == zpanes.size(),
                      (std::string("Numbers of panes do not match between ")+
                       x->window()->name()+" and "+z->window()->name()).c_str());
   std::vector<Pane*>::iterator zit, zend;
   std::vector<const Pane*>::const_iterator xit, yit;
   const Pane** ait=NULL;
   const Attribute *a=NULL;
   const data_type *aval=NULL;
   if ( atype == BLAS_VOID)
     aval = reinterpret_cast<const data_type *>( ain);
   else {
     a = reinterpret_cast<const Attribute*>(ain);
     if ( !a->is_windowed()) {
       a->window()->panes( apanes);
       COM_assertion_msg(xpanes.size() == ypanes.size(),
                         (std::string("Numbers of panes do not match between ")+
                          x->window()->name()+" and "+y->window()->name()).c_str());
       ait = &apanes[0];
     }
     else {
       COM_assertion_msg( a->size_of_items()==1, "Size of items do not match");
       aval = reinterpret_cast<const data_type *>( a->pointer());
       COM_assertion_msg( aval, (std::string("Caught NULL pointer in ")+
                                 a->fullname()).c_str());
     }
   }
   const int anum_dims = atype!=BLAS_VOID ? a->size_of_components() : 0;
   COM_assertion_msg( atype==BLAS_VOID || (anum_dims==1 || anum_dims==num_dims),
                     (std::string("Numbers of components do not match between ")+
                      a->fullname()+" and "+z->fullname()).c_str());
   for(zit=zpanes.begin(),zend=zpanes.end(),xit=xpanes.begin(),yit=ypanes.begin();
       zit != zend; ++zit, ait+=(atype!=BLAS_VOID&&ait), ++xit, ++yit) {
     Attribute *pz = (*zit)->attribute(z->id());
     const int  length = pz->size_of_items();
     int  zstrd=get_stride<BLAS_VEC2D>(pz);
     const bool zstg = num_dims!=zstrd;
     const Attribute *px = (*xit)->attribute(x->id());
     int  xstrd = get_stride<BLAS_VEC2D>(px);
     COM_assertion_msg(length == px->size_of_items() || xstrd==0,
                       (std::string("Numbers of items do not match between ")+
                        x->fullname()+" and "+z->fullname()+
                        " on pane "+to_str((*zit)->id())).c_str());
     const bool xstg = num_dims!=xstrd || xstrd==0;
     const Attribute *py = (*yit)->attribute(y->id());
     int  ystrd = get_stride<BLAS_VEC2D>(py);
     COM_assertion_msg(length == py->size_of_items() || ystrd==0,
                       (std::string("Numbers of items do not match between ")+
                        y->fullname()+" and "+z->fullname()+
                        " on pane "+to_str((*zit)->id())).c_str());
     const bool ystg = num_dims!=ystrd || ystrd==0;
     const Attribute *pa = (atype!=BLAS_VOID&&ait)?(*ait)->attribute(a->id()):a;
     int astrd = get_stride<atype>(pa);
     const bool astg = pa && (anum_dims!=num_dims || anum_dims!=astrd);
     COM_assertion_msg( atype!=BLAS_SCNE && atype!=BLAS_VEC2D ||
                        length == int(pa->size_of_items()) || astrd==0,
                        (std::string("Numbers of items do not match between ")+
                         a->fullname()+" and "+z->fullname()+
                         " on pane "+to_str((*zit)->id())).c_str());
     // Optimized version for contiguous attributes
     if ( !xstg && !zstg && !ystg && !astg && atype != BLAS_VEC
          && (atype != BLAS_SCNE || num_dims==1)) {
       const data_type *xval = (const data_type *)px->pointer();
       const data_type *yval = (const data_type *)py->pointer();
       data_type *zval = (data_type *)pz->pointer();
       // Get address for a if a is not window attribute
       if ( atype != BLAS_VOID && ait)
         aval = reinterpret_cast<const data_type *>(pa->pointer());
       //Loop for each element/node and for each dimension
       for(Size i = 0, s = length*num_dims; i<s; ++i, ++zval, ++xval, ++yval)
         *zval = getref<data_type,atype,0>(aval,i,0,1)* *xval+ *yval;
     }
     else { // General version
       //Loop for each dimension.
       for(int i = 0; i < num_dims; ++i) {
         Attribute *pz_i = num_dims==1?pz:(*zit)->attribute(z->id()+i+1);
         data_type *zval = (data_type *)pz_i->pointer();
         zstrd=get_stride<BLAS_VEC2D>(pz_i);
         const Attribute *px_i = num_dims==1?px:(*xit)->attribute(x->id()+i+1);
         const data_type *xval = (const data_type *)px_i->pointer();
         xstrd=get_stride<BLAS_VEC2D>(px_i);
         const Attribute *py_i = num_dims==1?py:(*yit)->attribute(y->id()+i+1);
         const data_type *yval = (const data_type *)py_i->pointer();
         ystrd=get_stride<BLAS_VEC2D>(py_i);
         if ( atype != BLAS_VOID && ait) {
           const Attribute *pa_i=anum_dims==1?pa:(*ait)->attribute(a->id()+i+1);
           aval = reinterpret_cast<const data_type *>( pa_i->pointer());
           astrd = get_stride<atype>( pa_i);
         }
         //Loop for each element/node.
         for(int j=0; j<length; ++j, xval+=xstrd, zval+=zstrd, yval+=ystrd)
           *zval = getref<data_type,atype,1>(aval,j,i,astrd) * *xval + *yval;
       }
     } // end if
   } // end for
 }
void axpy_scalar (const void * a, const Attribute * x, const Attribute * y, Attribute * z) static
Operation wrapper for z = a * x + y (a is a scalar pointer).
Definition at line 210 of file axpy.C.
References COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), x, y, and z.
Referenced by init().
{
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     axpy_gen<int,BLAS_VOID>(a, x, y, z);
   else if (att_type == COM_DOUBLE || att_type == COM_DOUBLE_PRECISION)
     axpy_gen<double,BLAS_VOID>(a, x, y, z);
 }
void calc (Attribute * z, const Attribute * x, const void * yin, FuncType opp, bool swap = false) static protected
Performs the operation: z = x op y.
Definition at line 49 of file op3args.C.
References BLAS_SCNE, BLAS_VEC, BLAS_VEC2D, BLAS_VOID, COM_assertion_msg, COM_compatible_types(), Attribute::data_type(), Attribute::fullname(), i, Attribute::id(), Attribute::is_windowed(), j, Mesquite::length(), Window::name(), Window::panes(), Attribute::pointer(), s, Attribute::size_of_components(), Attribute::size_of_items(), to_str(), Attribute::window(), and y.
 {
   typedef typename FuncType::result_type data_type;
   COM_assertion_msg( !x->is_windowed() && !z->is_windowed(),
                      (std::string("Unsupported data type in ")+
                       x->fullname()).c_str());
   COM_assertion_msg( COM_compatible_types(x->data_type(),z->data_type()),
                      (std::string("Incompatible data types between ")+
                       x->fullname()+" and "+z->fullname()).c_str());
   int num_dims = z->size_of_components();
   COM_assertion_msg( num_dims == x->size_of_components(),
                      (std::string("Numbers of components do not match between ")+
                       x->fullname()+" and "+z->fullname()).c_str());
   std::vector<Pane*> zpanes;
   std::vector<const Pane*> xpanes, ypanes;
   z->window()->panes(zpanes);
   x->window()->panes(xpanes);
   COM_assertion_msg( xpanes.size() == zpanes.size(),
                      (std::string("Numbers of panes do not match between ")+
                       x->window()->name()+" and "+z->window()->name()).c_str());
   std::vector<Pane*>::iterator zit, zend;
   std::vector<const Pane*>::const_iterator xit;
   const Pane **yit=NULL;
   const Attribute *y=NULL;
   const data_type *yval=NULL;
   // Obtain yval for BLAS_VOID or window attributes
   if ( ytype==BLAS_VOID)
     yval = reinterpret_cast<const data_type *>( yin);
   else {
     y = reinterpret_cast<const Attribute *>(yin);
     if ( !y->is_windowed()) {
       y->window()->panes(ypanes);
       COM_assertion_msg(xpanes.size() == ypanes.size(),
                         (std::string("Numbers of panes do not match between ")+
                          x->window()->name()+" and "+
                          y->window()->name()).c_str());
       yit = &ypanes[0];
     }
     else {
       COM_assertion_msg( y->size_of_items()==1,
                          (std::string("Numbers of items do not match between ")+
                           x->fullname()+" and "+y->fullname()).c_str());
       yval = reinterpret_cast<const data_type *>( y->pointer());
       COM_assertion_msg( yval, (std::string("Caught NULL pointer in ")+
                                 y->fullname()).c_str());
     }
   }
   const int ynum_dims = ytype!=BLAS_VOID ? y->size_of_components() : 0;
   COM_assertion_msg( ytype==BLAS_VOID || (ynum_dims==1 || ynum_dims==num_dims),
                      (std::string("Numbers of components do not match between ")+
                       z->fullname()+" and "+y->fullname()).c_str());
   for( zit=zpanes.begin(), zend=zpanes.end(), xit=xpanes.begin(); zit!=zend;
        ++zit, ++xit, yit+=( ytype!=BLAS_VOID && yit!=NULL)) {
     Attribute *pz = (*zit)->attribute(z->id());
     const int  length = pz->size_of_items();
     int  zstrd=get_stride<BLAS_VEC2D>(pz);
     const bool zstg = num_dims!=zstrd;
     const Attribute *px = (*xit)->attribute(x->id());
     int  xstrd = get_stride<BLAS_VEC2D>(px);
     COM_assertion_msg(length == px->size_of_items() || xstrd==0,
                       (std::string("Numbers of items do not match between ")+
                        x->fullname()+" and "+z->fullname()+
                        " on pane "+to_str((*zit)->id())).c_str());
     const bool xstg = num_dims!=xstrd || xstrd==0;
     const Attribute *py = (ytype!=BLAS_VOID&&yit)?(*yit)->attribute(y->id()):y;
     int ystrd = get_stride<ytype>(py);
     COM_assertion_msg( ytype!=BLAS_SCNE && ytype!=BLAS_VEC2D ||
                        (length == int(py->size_of_items()) || ystrd==0),
                        (std::string("Numbers of items do not match between ")+
                         y->fullname()+" and "+z->fullname()+
                         " on pane "+to_str((*zit)->id())).c_str());
     const bool ystg = py && (ynum_dims!=num_dims || ynum_dims!=ystrd);
     // Optimized version for contiguous attributes
     if ( !xstg && !zstg && !ystg && ytype != BLAS_VEC
          && (ytype != BLAS_SCNE || num_dims==1)) {
       const data_type *xval = (const data_type *)px->pointer();
       data_type *zval = (data_type *)pz->pointer();
       // Get address for y if y is not window attribute
       if ( ytype != BLAS_VOID && yit)
         yval = reinterpret_cast<const data_type *>(py->pointer());
       //Loop for each element/node and for each dimension
       if ( swap == false)
         for(Size i = 0, s = length*num_dims; i<s; ++i, ++zval, ++xval)
           *zval = opp( *xval, getref<data_type,ytype,0>(yval,i,0,1));
       else
         for(Size i = 0, s = length*num_dims; i<s; ++i, ++zval, ++xval)
           *zval = opp( getref<data_type,ytype,0>(yval,i,0,1), *xval);
     }
     else { // General version
       //Loop for each dimension.
       for(int i = 0; i < num_dims; ++i) {
         Attribute *pz_i = num_dims==1?pz:(*zit)->attribute(z->id()+i+1);
         data_type *zval = (data_type *)pz_i->pointer();
         zstrd=get_stride<BLAS_VEC2D>(pz_i);
         const Attribute *px_i = num_dims==1?px:(*xit)->attribute(x->id()+i+1);
         const data_type *xval = (const data_type *)px_i->pointer();
         xstrd=get_stride<BLAS_VEC2D>(px_i);
         if ( ytype != BLAS_VOID && yit) {
           const Attribute *py_i=ynum_dims==1?py:(*yit)->attribute(y->id()+i+1);
           yval = reinterpret_cast<const data_type *>( py_i->pointer());
           ystrd = get_stride<ytype>( py_i);
         }
         // Loop for each element/node.
         if ( swap == false) {
           for(int j = 0; j < length; ++j, zval+=zstrd, xval+=xstrd)
             *zval = opp( *xval, getref<data_type,ytype,1>(yval,j,i,ystrd));
         }
         else {
           for(int j = 0; j < length; ++j, zval+=zstrd, xval+=xstrd)
             *zval = opp( getref<data_type,ytype,1>(yval,j,i,ystrd), *xval);
         }
       } // end for i
     }  // end if
   } // end for
 }
void calcChoose (const Attribute * x, const Attribute * y, Attribute * z, FuncType opp) static protected
Chooses which calc function to call based on type of y.
Definition at line 192 of file op3args.C.
References Attribute::is_windowed(), Attribute::size_of_components(), x, y, and z.
Referenced by add(), div(), limit1(), mul(), and sub().
 {
   typedef typename FuncType::result_type data_type;
   if (x->is_windowed()) {
     if ( x->size_of_components() == 1)
       calc<FuncType,BLAS_SCALAR>(z, y, x, opp, true);
     else
       calc<FuncType,BLAS_VEC>(z, y, x, opp, true);
   }
   else if (y->is_windowed()) {
     if ( y->size_of_components() == 1)
       calc<FuncType,BLAS_SCALAR>(z, x, y, opp, false);
     else
       calc<FuncType,BLAS_VEC>(z, x, y, opp, false);
   }
   else if ( x->size_of_components()<y->size_of_components()) {
     calc<FuncType,BLAS_SCNE>(z, y, x, opp, true);
   }
   else {
     if ( y->size_of_components() == 1)
       calc<FuncType,BLAS_SCNE>(z, x, y, opp, false);
     else
       calc<FuncType,BLAS_VEC2D>(z, x, y, opp, false);
   }
 }
void calcDot (void * zout, const Attribute * x, const Attribute * y, const MPI_Comm * comm = NULL, const Attribute * mults = NULL) static protected
Performs the operation: z = <x, y>
Definition at line 27 of file dots.C.
References BLAS_SCALAR, BLAS_VEC, BLAS_VOID, COM_assertion_msg, COM_compatible_types(), COM_INT, COM_INTEGER, COMMPI_Initialized(), Attribute::data_type(), Attribute::fullname(), i, Attribute::id(), Attribute::is_windowed(), j, Mesquite::length(), MPI_SUM, Window::name(), ni, nj, Window::panes(), Attribute::pointer(), s, Attribute::size_of_components(), Attribute::size_of_items(), strd, Attribute::stride(), to_str(), Attribute::window(), and y.
{
   COM_assertion_msg( !x->is_windowed() && !z->is_windowed(),
                      "Unsupported attribute type");
   COM_assertion_msg( COM_compatible_types(x->data_type(),z->data_type()),
                      (std::string("Incompatible data types between ")+
                       x->fullname()+" and "+z->fullname()).c_str());
   int num_dims = z->size_of_components();
   COM_assertion_msg( num_dims == x->size_of_components(),
                      (std::string("Numbers of components do not match between ")+
                       x->fullname()+" and "+z->fullname()).c_str());
   std::vector<const Pane*> xpanes, zpanes, mpanes;
   std::vector<Pane*> ypanes;
   z->window()->panes(zpanes);
   x->window()->panes(xpanes);
   COM_assertion_msg( xpanes.size() == zpanes.size(),
                      (std::string("Numbers of panes do not match between ")+
                       x->window()->name()+" and "+z->window()->name()).c_str());
   std::vector<const Pane*>::const_iterator zit, zend, xit;
   Pane **yit=NULL;
   Attribute *y=NULL;
   data_type *yval=NULL;
   if ( ytype == BLAS_VOID) {
     yval = reinterpret_cast<data_type *>( yout);
     *yval = data_type(0);
   }
   else {
     y = reinterpret_cast<Attribute *>(yout);
     if ( !y->is_windowed()) {
       y->window()->panes(ypanes);
       COM_assertion_msg(xpanes.size() == ypanes.size(),
                         (std::string("Numbers of panes do not match between ")+
                          x->fullname()+" and "+y->fullname()).c_str());
       yit = &ypanes[0];
     }
     else {
       COM_assertion_msg( y->size_of_items()==1,
                          (std::string("Numbers of items do not match between ")+
                           x->fullname()+" and "+y->fullname()).c_str());
       yval = reinterpret_cast<data_type *>( y->pointer());
       COM_assertion_msg( yval, (std::string("Caught NULL pointer in ")+
                                 y->fullname()).c_str());
     }
   }
   const int ynum_dims = ytype != BLAS_VOID?y->size_of_components():0;
   COM_assertion_msg( ytype==BLAS_VOID || (ynum_dims==1 || ynum_dims==num_dims),
                      (std::string("Numbers of components do not match between ")+
                       z->fullname()+" and "+y->fullname()).c_str());
   // Initialize pointer to multiplicities
   const Pane ** mit=NULL;
   const int *mval=NULL;
   if ( mults != NULL) {
     COM_assertion_msg( COM_compatible_types( COM_INT, mults->data_type()) &&
                        mults->size_of_components()==1,
                        (std::string("Multiplier ")+mults->fullname()+
                         "must be integer scalars.").c_str());
     mults->window()->panes(mpanes);
     COM_assertion_msg(xpanes.size() == mpanes.size(),
                       (std::string("Numbers of panes do not match between ")+
                        x->window()->name()+" and "+
                        mults->window()->name()).c_str());
     mit = &mpanes[0];
   }
   // Initialize y to 0 for BLAS_VOID or window attribute
   if ( ytype == BLAS_VOID) {
     *yval = data_type(0);
   }
   else {
     if ( y->is_windowed()) {
       for ( int i=0; i<ynum_dims; ++i) yval[i] = data_type(0);
     }
   }
   for( zit=zpanes.begin(), zend=zpanes.end(), xit=xpanes.begin();
        zit!=zend; ++zit, ++xit, yit+=( ytype!=BLAS_VOID && yit)) {
     const Attribute *pz = (*zit)->attribute(z->id());
     const int  length = pz->size_of_items();
     int  zstrd=get_stride<BLAS_VEC2D>(pz);
     const bool zstg = num_dims!=zstrd;
     const Attribute *px = (*xit)->attribute(x->id());
     int  xstrd = get_stride<BLAS_VEC2D>(px);
     COM_assertion_msg(length == px->size_of_items(),
                       (std::string("Numbers of items do not match between ")+
                        x->fullname()+" and "+z->fullname()+
                        " on pane "+to_str((*zit)->id())).c_str());
     const bool xstg = num_dims!=xstrd;
     Attribute *py = y;
     if ( ytype != BLAS_VOID && !y->is_windowed()) {
       // Obtain py and initialize to 0
       py = (*yit)->attribute(y->id());
       const int ynum_comp = py->size_of_components();
       const int ylen = py->size_of_items();
       COM_assertion_msg( ylen==1 || ylen==length,
                          (std::string("Numbers of items do not match between ")+
                           y->fullname()+" and "+z->fullname()+
                           " on pane "+to_str((*zit)->id())).c_str());
       yval = reinterpret_cast<data_type *>( py->pointer());
       if ( py->stride()==ynum_comp) {
         for ( int i=0, ni=ynum_comp*ylen; i<ni; ++i) yval[i] = data_type(0);
       }
       else {
         // Loop through the number of components
         for (int i=0; i<ynum_comp; ++i) {
           Attribute *py_i = ynum_comp>1?(*yit)->attribute( y->id()+i+1):py;
           data_type *yv_i = reinterpret_cast<data_type*>(py_i->pointer());
           const int strd=get_stride<BLAS_VEC2D>(py_i);
           // loop through the stride
           for ( int j=0, nj=ylen*strd; j<nj; j+=strd) yv_i[j] = data_type(0);
         }
       }
     }
     int ystrd = get_stride<ytype>(py);
     const bool ystg = py && (ynum_dims!=num_dims || ynum_dims!=ystrd);
     // Obtain the multiplier
     if ( mults != NULL) {
       const Attribute *pm = (*mit)->attribute(mults->id());
       COM_assertion_msg( pm->size_of_items()==length,
                          (std::string("Numbers of items do not match between ")+
                           mults->fullname()+" and "+z->fullname()+
                           " on pane "+to_str((*zit)->id())).c_str());
       mval = reinterpret_cast<const int*>( pm->pointer());
       ++mit;
     }
     // Optimized version for contiguous attributes
     if ( !xstg && !zstg && !ystg && mval == NULL) {
       const data_type *xval = (const data_type *)px->pointer();
       const data_type *zval = (const data_type *)pz->pointer();
       //Loop for each element/node and for each dimension
       for(Size i = 0, s = length*num_dims; i<s; ++i, ++xval, ++zval)
         getref<data_type,ytype,0>(yval,i,0,1) += *xval* *zval;
     }
     else { // General version
       //Loop for each dimension.
       for(int i = 0; i < num_dims; ++i) {
         const Attribute *pz_i = num_dims==1?pz:(*zit)->attribute(z->id()+i+1);
         const data_type *zval = (const data_type *)pz_i->pointer();
         zstrd=get_stride<BLAS_VEC2D>(pz_i);
         const Attribute *px_i = num_dims==1?px:(*xit)->attribute(x->id()+i+1);
         const data_type *xval = (const data_type *)px_i->pointer();
         xstrd=get_stride<BLAS_VEC2D>(px_i);
         if ( ytype != BLAS_VOID && !y->is_windowed()) {
           Attribute *py_i=ynum_dims==1?py:(*yit)->attribute(y->id()+i+1);
           yval = reinterpret_cast<data_type *>( py_i->pointer());
           ystrd = get_stride<ytype>( py_i);
         }
         if ( mval != NULL) {
           //Loop for each element/node.
           for(int j=0; j<length; ++j, xval+=xstrd,zval+=zstrd)
             getref<data_type,ytype,1>( yval,j,i,ystrd) += *xval* *zval / mval[j];
         }
         else
           for(int j=0; j<length; ++j, xval+=xstrd,zval+=zstrd)
             getref<data_type,ytype,1>( yval,j,i,ystrd) += *xval* *zval;
       }
     }
   }
   if ( ( ytype==BLAS_VOID || ytype==BLAS_SCALAR || ytype==BLAS_VEC)
        && comm && *comm!=MPI_COMM_NULL && COMMPI_Initialized()) {
     int n = (ytype == BLAS_VEC) ? num_dims : 1;
     COM_Type att_type = x->data_type();
     data_type t = *yval;
     if ( att_type == COM_INT || att_type == COM_INTEGER) {
       MPI_Allreduce( &t, yval, n, MPI_INT, MPI_SUM, *comm);
     }
     else {
       MPI_Allreduce( &t, yval, n, MPI_DOUBLE, MPI_SUM, *comm);
     }
   }
 }
void copy (const Attribute * x, Attribute * y) static
Wrapper for copy.
Definition at line 333 of file op2args.C.
References Window::attributes(), COM_ALL, COM_assertion_msg, COM_ATTS, COM_CHAR, COM_CONN, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, COM_MESH, COM_PMESH, Attribute::data_type(), Attribute::fullname(), i, Attribute::id(), Window::name(), Attribute::window(), x, and z.
Referenced by Rocmop::add_aspect_ratios(), FaceOffset_3::balance_mass(), FaceOffset_3::compute_quadrics(), FaceOffset_3::filter_and_identify_ridge_edges(), init(), Rocprop::propagate(), Propagation_3::set_constraints(), Rocmop::smooth_surf_medial(), Rocmop::smooth_vol_mesq_ng(), and FaceOffset_3::time_stepping().
{
   switch ( x->id()) {
   case COM::COM_ATTS: {
     COM_assertion_msg( z->id() == COM::COM_ATTS,
                        "Aggregate attributes for copy must match.");
     // Obtain all the attributes of their corresponding windows
     std::vector< const Attribute*>  x_attrs;
     x->window()->attributes( x_attrs);
     std::vector< Attribute*>  z_attrs;
     z->window()->attributes( z_attrs);
     // Copy all the individual attributes
     COM_assertion_msg( x_attrs.size() == z_attrs.size(),
                        (std::string("Numbers of attributes do not match between ")+
                         x->window()->name()+" and "+z->window()->name()).c_str());
     for ( int i=x_attrs.size()-1; i>=0; --i)
       copy( x_attrs[i], z_attrs[i]);
     return;
   }
   case COM::COM_MESH:
   case COM::COM_PMESH:
   case COM::COM_CONN:
   case COM::COM_ALL:
     COM_assertion_msg(false, "Only the aggregate attribute atts is supported");
   default: ;
   }
   COM_Type src_type = x->data_type(), trg_type = z->data_type();
   if ( src_type == COM_INT || src_type == COM_INTEGER) {
     if ( trg_type == COM_DOUBLE || trg_type == COM_DOUBLE_PRECISION)
       copy_helper<assn<int,double> >( x, z);
     else
       copy_helper<assn<int,int> >( x, z);
   }
   else if ( src_type == COM_CHAR) {
     if ( trg_type == COM_INT || trg_type == COM_INTEGER)
       copy_helper<assn<char,int> >( x, z);
     else if ( trg_type == COM_DOUBLE || trg_type == COM_DOUBLE_PRECISION)
       copy_helper<assn<char,double> >( x, z);
     else
       copy_helper<assn<char,char> >( x, z);
   }
   else {
     COM_assertion_msg( src_type==COM_DOUBLE || src_type==COM_DOUBLE_PRECISION,
                        (std::string("Unsupported data type in ")+
                         x->fullname()).c_str());
     copy_helper<assn<double,double> >( x, z);
   }
 }
void copy_helper (const Attribute * x, Attribute * z) static protected
Definition at line 315 of file op2args.C.
References Attribute::is_windowed(), Attribute::size_of_components(), x, and z.
{
   int xncomp = x->size_of_components();
   if ( x->is_windowed()) {
     if ( xncomp == 1)
       gen2arg<Op,BLAS_SCALAR>(z, const_cast<Attribute*>(x), Op());
     else
       gen2arg<Op,BLAS_VEC>(z, const_cast<Attribute*>(x), Op());
   }
   else {
     if ( xncomp == 1)
       gen2arg<Op,BLAS_SCNE>(z, const_cast<Attribute*>(x), Op());
     else
       gen2arg<Op,BLAS_VEC2D>(z, const_cast<Attribute*>(x), Op());
   }
 }
void copy_scalar (const void * x, Attribute * y) static
Operation wrapper for copy (x is a scalar pointer).
Definition at line 583 of file op2args.C.
References COM_assertion_msg, COM_CHAR, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), x, and z.
Referenced by FaceOffset_3::balance_mass(), FaceOffset_3::build_ridge_neighbor_list(), FaceOffset_3::compute_anisotropic_vertex_centers(), Window_manifold_2::compute_mcn(), Rocmop::compute_medial_quadric(), FaceOffset_3::compute_quadrics(), Window_manifold_2::compute_shortest_edgelen_nodes(), Propagation_3::convert_constraints(), FaceOffset_3::denoise_surface(), Propagation_3::determine_constraint_boundary(), FaceOffset_3::distribute_volume_e2n(), FaceOffset_3::filter_and_identify_ridge_edges(), Rocmop::get_redist_safe_factor(), init(), FaceOffset_3::mark_weak_vertices(), FaceOffset_3::nulaplacian_smooth(), FaceOffset_3::reclassify_ridge_vertices(), Rocmop::redistribute_vertices_ridge(), Rocmop::redistribute_vertices_smooth(), reduce_MPI(), Rocmop::smooth_vol_mesq_ng(), and FaceOffset_3::time_stepping().
{
   COM_Type att_type = z->data_type();
   typedef assn<int,int>          assn_int;
   typedef assn<char,char>        assn_chr;
   typedef assn<double,double>    assn_dbl;
   if ( att_type == COM_INT || att_type == COM_INTEGER)
     gen2arg<assn_int,BLAS_VOID>(z, const_cast<void*>(x), assn_int());
   else if ( att_type == COM_DOUBLE || att_type == COM_DOUBLE_PRECISION) {
     gen2arg<assn_dbl,BLAS_VOID>(z, const_cast<void*>(x), assn_dbl());
   }
   else {
     COM_assertion_msg( att_type==COM_CHAR,
                        (std::string("Unsupported data type in ")+
                         z->fullname()).c_str());
     gen2arg<assn_chr,BLAS_VOID>(z, const_cast<void*>(x), assn_chr());
   }
 }
void div (const Attribute * x, const Attribute * y, Attribute * z) static
Operation wrapper for division.
Definition at line 269 of file op3args.C.
References calcChoose(), COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), and Attribute::fullname().
Referenced by rflu_modrepair3d::angfnd(), FaceOffset_3::compute_anisotropic_vertex_centers(), Window_manifold_2::compute_mcn(), FaceOffset_3::compute_quadrics(), computeflux(), FaceOffset_3::denoise_surface(), init(), rflo_viscousfluxpatch(), and Rocmop::smooth_vol_mesq_ng().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calcChoose(x, y, z, std::divides<int>());
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calcChoose(x, y, z, std::divides<double>());
   }
 }
void div_scalar (const Attribute * x, const void * y, Attribute * z, int swap = 0) static
Operation wrapper for division with y as a scalar pointer.
Definition at line 363 of file op3args.C.
References BLAS_VOID, COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), x, y, and z.
Referenced by Rocmop::constrain_displacements(), Rocmop::get_usr_disp(), and init().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calc<std::divides<int>,BLAS_VOID>(z, x, y, std::divides<int>(), swap);
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calc<std::divides<double>,BLAS_VOID>(z, x, y, std::divides<double>(), swap);
   }
 }
void dot (const Attribute * x, const Attribute * y, Attribute * z, const Attribute * mults = NULL) static
Wrapper for dot product.
Wrapper for 2-norm.
Definition at line 279 of file dots.C.
References dot_MPI().
Referenced by angle_rad_3d(), FaceOffset_3::balance_mass(), and init().
 { dot_MPI( x, y, z, NULL, mults); }
void dot_MPI (const Attribute * x, const Attribute * y, Attribute * z, const MPI_Comm * comm = NULL, const Attribute * mults = NULL) static
Wrapper for dot product.
Definition at line 226 of file dots.C.
References COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), Attribute::fullname(), Attribute::is_windowed(), Attribute::size_of_components(), x, y, and z.
Referenced by dot(), init(), nrm2(), and nrm2_MPI().
{
   COM_Type att_type = x->data_type();
   const int zncomp = z->size_of_components();
   if ( att_type == COM_INT || att_type == COM_INTEGER) {
     if ( z->is_windowed()) {
       if ( zncomp == 1)
         calcDot<int,BLAS_SCALAR>(z, x, y, comm, mults);
       else
         calcDot<int,BLAS_VEC>(z, x, y, comm, mults);
     }
     else {
       if ( zncomp == 1)
         calcDot<int,BLAS_SCNE>(z, x, y, comm, mults);
       else
         calcDot<int,BLAS_VEC2D>(z, x, y, comm, mults);
     }
   }
   else {
     COM_assertion_msg( att_type==COM_DOUBLE || att_type==COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        x->fullname()).c_str());
     if ( z->is_windowed()) {
       if ( zncomp == 1)
         calcDot<double,BLAS_SCALAR>(z, x, y, comm, mults);
       else
         calcDot<double,BLAS_VEC>(z, x, y, comm, mults);
     }
     else {
       if ( zncomp == 1)
         calcDot<double,BLAS_SCNE>(z, x, y, comm, mults);
       else
         calcDot<double,BLAS_VEC2D>(z, x, y, comm, mults);
     }
   }
 }
void dot_scalar (const Attribute * x, const Attribute * y, void * z, const Attribute * mults = NULL) static
Wrapper for 2-norm with z as a scalar pointer.
Definition at line 283 of file dots.C.
References dot_scalar_MPI().
Referenced by init().
 { dot_scalar_MPI( x, y, z, NULL, mults); }
void dot_scalar_MPI (const Attribute * x, const Attribute * y, void * z, const MPI_Comm * comm = NULL, const Attribute * mults = NULL) static
Wrapper for 2-norm with z as a scalar pointer.
Definition at line 264 of file dots.C.
References COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), x, y, and z.
Referenced by dot_scalar(), init(), nrm2_scalar(), and nrm2_scalar_MPI().
{
   COM_Type att_type = x->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calcDot<int,BLAS_VOID>(z, x, y, comm, mults);
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        x->fullname()).c_str());
     calcDot<double,BLAS_VOID>(z, x, y, comm, mults);
   }
 }
void finalize (const std::string & name) static
Delete window for Rocblas.
Definition at line 112 of file Rocblas.C.
References COM_delete_window().
Referenced by Rocblas_unload_module(), rocblas_unload_module(), ROCBLAS_UNLOAD_MODULE(), rocblas_unload_module_(), and ROCBLAS_UNLOAD_MODULE_().
{
   COM_delete_window( name.c_str());
 }
void gen2arg (Attribute * z, void * yin, FuncType opp) static protected
Performs the operation opp(x, y)
Definition at line 114 of file op2args.C.
References BLAS_SCNE, BLAS_VEC, BLAS_VEC2D, BLAS_VOID, COM_assertion_msg, COM_compatible_types(), Attribute::data_type(), Attribute::fullname(), i, Pane::id(), Attribute::id(), Attribute::is_windowed(), j, Mesquite::length(), Window::name(), Attribute::pane(), Window::panes(), Attribute::pointer(), s, Attribute::size_of_components(), Attribute::size_of_items(), to_str(), Attribute::window(), y, and z.
{
   typedef typename FuncType::argument_type  argument_type;
   typedef typename FuncType::result_type    result_type;
   int num_dims = z->size_of_components();
   std::vector<Pane*> zpanes;
   std::vector<Pane*>::iterator zit, zend;
   z->window()->panes(zpanes);
   std::vector<Pane*> ypanes;
   Pane **yit=NULL;
   Attribute *y=NULL;
   argument_type *yval=NULL;
   if ( ytype == BLAS_VOID) {
     yval = reinterpret_cast<argument_type *>( yin);
     COM_assertion_msg( yval, std::string("Caught NULL pointer in scalar \
 operand when processing "+z->fullname()).c_str());
   }
   else {
     y = reinterpret_cast<Attribute *>(yin);
     bool type_coercion = compare_types<argument_type,result_type>();
     COM_assertion_msg( type_coercion ||
                        COM_compatible_types(z->data_type(), y->data_type()),
                        (std::string("Incompatible data types between ")+
                         z->fullname()+" and "+y->fullname()).c_str());
     if ( !y->is_windowed()) {
       y->window()->panes(ypanes);
       COM_assertion_msg(zpanes.size() == ypanes.size(),
                         (std::string("Numbers of panes do not match between ")+
                          y->window()->name()+" and "+z->window()->name()).c_str());
       yit = &ypanes[0];
     }
     else {
       if ( y->size_of_items()!=1) {
         std::cout << "Rocbals Error: The size-of-items of attribute "
                   << y->fullname() << " on pane " << y->pane()->id()
                   << " is " << y->size_of_items() << std::endl;
         COM_assertion_msg( y->size_of_items()==1, "If an argument is a window \
 attribute, then its number of items must be 1.");
       }
       yval = reinterpret_cast<argument_type *>( y->pointer());
       COM_assertion_msg( yval, (std::string("Caught NULL pointer in ")+
                                 y->fullname()).c_str());
     }
   }
   const int ynum_dims = ytype != BLAS_VOID?y->size_of_components():0;
   COM_assertion_msg( ytype==BLAS_VOID || (ynum_dims==1 || ynum_dims==num_dims),
                      (std::string("Numbers of components do not match between ")+
                       y->fullname()+" and "+z->fullname()).c_str());
   if ( z->is_windowed()) {
     COM_assertion_msg( ytype == BLAS_VOID || y->is_windowed(),
                        (std::string("Wrong type of operand")+
                         y->fullname()).c_str());
     int zs=get_stride<BLAS_VEC2D>(z);
     int ys=get_stride<ytype>(y);
     result_type *zval = (result_type *)z->pointer();
     int   length = z->size_of_items();
     COM_assertion_msg( length==0 || ytype == BLAS_VOID || zval && yval,
                        (std::string("Caught NULL pointer in w-attribute ")+
                         z->fullname()+" or "+y->fullname()).c_str());
     if (  (length==1 || num_dims == zs) && ytype != BLAS_VEC) {
       for ( Size i = 0, s = num_dims*length; i < s; ++i, ++zval)
         opp( *zval, getref<argument_type,ytype,0>(yval,i,0,1));
     }
     else {
       for(int i = 0; i < num_dims; ++i) {
         Attribute *z_i = num_dims==1?z:z+i+1;
         zval = (result_type *)z_i->pointer();
         zs = get_stride<BLAS_VEC2D>(z_i);
         if ( ytype != BLAS_VOID) {
           Attribute *y_i=ynum_dims==1?y:y+i+1;
           yval = reinterpret_cast<argument_type *>( y_i->pointer());
           ys = get_stride<ytype>( y_i);
         }
         for(int j=0; j<length; ++j, zval+=zs)
           opp( *zval, getref<argument_type,ytype,1>(yval,j,i,ys));
       }
     }
     return;
   }
   // otherwise:
   for( zit=zpanes.begin(), zend=zpanes.end(); zit!=zend;
        ++zit, yit+=( ytype!=BLAS_VOID&&yit)) {
     Attribute *pz = (*zit)->attribute(z->id());
     const int  length = pz->size_of_items();
     int  zstrd=get_stride<BLAS_VEC2D>(pz);
     const bool zstg = length>1 && num_dims!=zstrd;
     Attribute *py = ytype!=BLAS_VOID&&yit?(*yit)->attribute(y->id()):y;
     int ystrd = get_stride<ytype>(py);
     const bool ystg = py && (ynum_dims!=num_dims || ynum_dims!=ystrd);
     COM_assertion_msg( ytype!=BLAS_SCNE && ytype!=BLAS_VEC2D ||
                        length == int(py->size_of_items()) || ystrd==0,
                        (std::string("Numbers of items do not match between ")+
                         y->fullname()+" and "+z->fullname()+
                         " on pane "+to_str((*zit)->id())).c_str());
     // Optimized version for contiguous attributes
     if ( !zstg && !ystg && ytype != BLAS_VEC &&
          (ytype != BLAS_SCNE || num_dims==1)) {
       result_type *zval = reinterpret_cast<result_type *>(pz->pointer());
       if ( ytype != BLAS_VOID && yit)
         yval = reinterpret_cast<argument_type *>(py->pointer());
         COM_assertion_msg( length==0 || ytype == BLAS_VOID || zval && yval,
                            (std::string("Caught NULL pointer in ")+
                             z->fullname()+" or "+y->fullname()+" on pane "+
                             to_str( (*zit)->id())).c_str());
       if ( zval)
         //Loop for each element/node and for each dimension
         for(int i = 0, s = length*num_dims; i < s; ++i, ++zval)
           opp(*zval, getref<argument_type,ytype,0>(yval,i,0,1));
     }
     else { // General version
       //Loop for each dimension.
       for(int i = 0; i < num_dims; ++i) {
         Attribute *pz_i = num_dims==1?pz:(*zit)->attribute(z->id()+i+1);
         result_type *zval = (result_type *)pz_i->pointer();
         zstrd=get_stride<BLAS_VEC2D>(pz_i);
         if ( ytype != BLAS_VOID && yit) {
           Attribute *py_i=ynum_dims==1?py:(*yit)->attribute(y->id()+i+1);
           yval = reinterpret_cast<argument_type *>( py_i->pointer());
           ystrd = get_stride<ytype>( py_i);
         }
         COM_assertion_msg( length==0 || ytype == BLAS_VOID || zval && yval,
                            (std::string("Caught NULL pointer in ")+
                             z->fullname()+" or "+y->fullname()+" on pane "+
                             to_str( (*zit)->id())).c_str());
         if ( zval)
           for(int j=0; j < length; ++j, zval+=zstrd)
             opp( *zval, getref<argument_type,ytype,1>(yval,j,i,ystrd));
       }
     }
   }
 }
int get_stride (const Attribute * attr) inline static protected
Definition at line 291 of file Rocblas.h.
References BLAS_SCNE, BLAS_VEC, BLAS_VEC2D, Attribute::size_of_items(), and Attribute::stride().
{
   if ( attr_type == BLAS_SCNE || attr_type == BLAS_VEC2D) {
     if ( attr->size_of_items()>1)
       return attr->stride();
     else
       return 0;
   }
   else if ( attr_type == BLAS_VEC)
     return 0;
   else
     return 1;
 }
data_type & getref (data_type * base, const int r, const int c, const int nc) inline static protected
Definition at line 306 of file Rocblas.h.
References BLAS_SCNE, BLAS_VEC, and BLAS_VEC2D.
{
   if ( attr_type == BLAS_SCNE || attr_type == BLAS_VEC2D && is_staggered)
     return base[r*nc];
   else if ( attr_type == BLAS_VEC2D)
     return base[r*nc+c];
   else if ( attr_type == BLAS_VEC)
     return base[c];
   else
     return *base;
 }
const data_type & getref (const data_type * base, const int r, const int c, const int nc) inline static protected
Definition at line 319 of file Rocblas.h.
References BLAS_SCNE, BLAS_VEC, and BLAS_VEC2D.
{
   if ( attr_type == BLAS_SCNE || attr_type == BLAS_VEC2D && is_staggered)
     return base[r*nc];
   else if ( attr_type == BLAS_VEC2D)
     return base[r*nc+c];
   else if ( attr_type == BLAS_VEC)
     return base[c];
   else
     return *base;
 }
void init (const std::string & name) static
Creates window for Rocblas and registers functions.
Definition at line 37 of file Rocblas.C.
References acos(), add(), add_scalar(), axpy(), axpy_scalar(), COM_INT, COM_METADATA, COM_MPI_COMM, COM_new_window(), COM_set_function(), COM_VOID, COM_window_init_done(), copy(), copy_scalar(), div(), div_scalar(), dot(), dot_MPI(), dot_scalar(), dot_scalar_MPI(), limit1(), max_MPI(), max_scalar_MPI(), maxof_scalar(), min_MPI(), min_scalar_MPI(), mul(), mul_scalar(), neg(), nrm2(), nrm2_MPI(), nrm2_scalar(), nrm2_scalar_MPI(), rand(), rand_scalar(), sqrt(), sub(), sub_scalar(), sum_MPI(), sum_scalar_MPI(), and swap().
Referenced by Rocblas_load_module(), rocblas_load_module(), ROCBLAS_LOAD_MODULE(), rocblas_load_module_(), and ROCBLAS_LOAD_MODULE_().
{
   const COM_Type arg4_types[]  = { COM_METADATA, COM_METADATA, COM_METADATA, COM_METADATA };
   const COM_Type arg4c_types[]  = { COM_METADATA, COM_METADATA, COM_METADATA, COM_MPI_COMM, COM_METADATA };
   const COM_Type arg4a_types[] = { COM_VOID, COM_METADATA, COM_METADATA, COM_METADATA };
   const COM_Type arg3_types[]  = { COM_METADATA, COM_METADATA, COM_METADATA };
   const COM_Type arg4cso_types[] = { COM_METADATA, COM_VOID, COM_METADATA, COM_INT };
   const COM_Type arg4mmvm_types[] = { COM_METADATA, COM_METADATA, COM_VOID, COM_METADATA };
   const COM_Type arg4mmvcm_types[] = { COM_METADATA, COM_METADATA, COM_VOID, COM_MPI_COMM, COM_METADATA };
   const COM_Type arg2_types[]  = { COM_METADATA, COM_METADATA };
   const COM_Type arg2s_types[] = { COM_VOID, COM_METADATA };
   COM_new_window(name.c_str());
   COM_set_function((name+".add").c_str(), (Func_ptr)add, "iio", arg3_types);
   COM_set_function((name+".sub").c_str(), (Func_ptr)sub, "iio", arg3_types);
   COM_set_function((name+".mul").c_str(), (Func_ptr)mul, "iio", arg3_types);
   COM_set_function((name+".div").c_str(), (Func_ptr)div, "iio", arg3_types);
   COM_set_function((name+".limit1").c_str(),
                    (Func_ptr)limit1, "iio", arg3_types);
   COM_set_function((name+".add_scalar").c_str(), (Func_ptr)add_scalar, "iioI",
                    arg4cso_types);
   COM_set_function((name+".sub_scalar").c_str(), (Func_ptr)sub_scalar, "iioI",
                    arg4cso_types);
   COM_set_function((name+".mul_scalar").c_str(), (Func_ptr)mul_scalar, "iioI",
                    arg4cso_types);
   COM_set_function((name+".div_scalar").c_str(), (Func_ptr)div_scalar, "iioI",
                    arg4cso_types);
   COM_set_function((name+".maxof_scalar").c_str(), (Func_ptr)maxof_scalar, "iioI", arg4cso_types);
   COM_set_function((name+".neg").c_str(), (Func_ptr)neg, "io", arg2_types);
   COM_set_function((name+".sqrt").c_str(), (Func_ptr)sqrt, "io", arg2_types);
   COM_set_function((name+".acos").c_str(), (Func_ptr)acos, "io", arg2_types);
   COM_set_function((name+".dot").c_str(), (Func_ptr)dot, "iioI", arg4_types);
   COM_set_function((name+".dot_scalar").c_str(), (Func_ptr)dot_scalar, "iioI", arg4mmvm_types);
   COM_set_function((name+".dot_MPI").c_str(), (Func_ptr)dot_MPI, "iioII", arg4c_types);
   COM_set_function((name+".dot_scalar_MPI").c_str(), (Func_ptr)dot_scalar_MPI, "iioII", arg4mmvcm_types);
   COM_set_function((name+".nrm2").c_str(), (Func_ptr)nrm2, "ioI", &arg4_types[1]);
   COM_set_function((name+".nrm2_scalar").c_str(), (Func_ptr)nrm2_scalar, "ioI", &arg4mmvm_types[1]);
   COM_set_function((name+".nrm2_MPI").c_str(), (Func_ptr)nrm2_MPI, "ioII", &arg4c_types[1]);
   COM_set_function((name+".nrm2_scalar_MPI").c_str(), (Func_ptr)nrm2_scalar_MPI, "ioII", &arg4mmvcm_types[1]);
   COM_set_function((name+".swap").c_str(), (Func_ptr)swap, "bb", arg2_types);
   COM_set_function((name+".copy").c_str(), (Func_ptr)copy, "io", arg2_types);
   COM_set_function((name+".rand").c_str(), (Func_ptr)rand, "io", arg2_types);
   COM_set_function((name+".copy_scalar").c_str(), (Func_ptr)copy_scalar,
                    "io", arg2s_types);
   COM_set_function((name+".rand_scalar").c_str(), (Func_ptr)rand_scalar,
                    "io", arg2s_types);
   COM_set_function((name+".axpy").c_str(), (Func_ptr)axpy, "iiio",
                    arg4_types);
   COM_set_function((name+".axpy_scalar").c_str(), (Func_ptr)axpy_scalar,
                    "iiio", arg4a_types);
   COM_Type types[] = {COM_METADATA, COM_METADATA, COM_MPI_COMM};
   COM_set_function((name+".min_MPI").c_str(),
                    (Func_ptr)min_MPI, "ioI", types);
   COM_set_function((name+".max_MPI").c_str(),
                    (Func_ptr)max_MPI, "ioI", types);
   COM_set_function((name+".sum_MPI").c_str(),
                    (Func_ptr)sum_MPI, "ioI", types);
   types[1] = COM_VOID;
   COM_set_function((name+".min_scalar_MPI").c_str(),
                    (Func_ptr)min_scalar_MPI, "ioI", types);
   COM_set_function((name+".max_scalar_MPI").c_str(),
                    (Func_ptr)max_scalar_MPI, "ioI", types);
   COM_set_function((name+".sum_scalar_MPI").c_str(),
                    (Func_ptr)sum_scalar_MPI, "ioI", types);
   COM_window_init_done(name.c_str());
 }
void limit1 (const Attribute * x, const Attribute * y, Attribute * z) static
Operation wrapper for limit1.
Definition at line 284 of file op3args.C.
References calcChoose(), COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), and Attribute::fullname().
Referenced by init().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calcChoose(x, y, z, limit1v<int>());
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calcChoose(x, y, z, limit1v<double>());
   }
 }
void max_MPI (const Attribute * x, Attribute * y, const MPI_Comm * comm = NULL) static
Wrapper for max.
Definition at line 708 of file op2args.C.
References BLAS_MAX, x, and z.
Referenced by init().
{
   reduce_MPI< maxv<int>, maxv<double>, BLAS_MAX>( x, z, comm,
                                                   -0x7FFFFFFF, -HUGE_VAL);
 }
void max_scalar_MPI (const Attribute * x, void * y, const MPI_Comm * comm = NULL) static
Operation wrapper for max (y is a scalar pointer).
Definition at line 763 of file op2args.C.
References BLAS_MAX, x, and y.
Referenced by init().
{
   reduce_scalar_MPI< maxv<int>, maxv<double>, BLAS_MAX>(x, y, comm,
                                                         -0x7FFFFFFF, -HUGE_VAL);
 }
void maxof_scalar (const Attribute * x, const void * y, Attribute * z, int swap = 0) static
Operation wrapper for addition with y as a scalar pointer.
Definition at line 315 of file op3args.C.
References BLAS_VOID, COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), x, y, and z.
Referenced by init().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calc<maxof<int>,BLAS_VOID>(z, x, y, maxof<int>(), swap);
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calc<maxof<double>,BLAS_VOID>(z, x, y, maxof<double>(), swap);
   }
 }
void min_MPI (const Attribute * x, Attribute * y, const MPI_Comm * comm = NULL) static
Wrapper for min.
Definition at line 714 of file op2args.C.
References BLAS_MIN, x, and z.
Referenced by init().
{
   reduce_MPI< minv<int>, minv<double>, BLAS_MIN>( x, z, comm,
                                                  0x7FFFFFFF, HUGE_VAL);
 }
void min_scalar_MPI (const Attribute * x, void * y, const MPI_Comm * comm = NULL) static
Operation wrapper for min (y is a scalar pointer).
Definition at line 771 of file op2args.C.
References BLAS_MIN, x, and y.
Referenced by init().
{
   reduce_scalar_MPI< minv<int>, minv<double>, BLAS_MIN>( x, y, comm,
                                                          0x7FFFFFFF, HUGE_VAL);
 }
void mul (const Attribute * x, const Attribute * y, Attribute * z) static
Operation wrapper for multiplication.
Definition at line 253 of file op3args.C.
References calcChoose(), COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), and Attribute::fullname().
Referenced by init(), MarkerParticles_3::multiply_nodal_normals(), Window_manifold_2::perturb_mesh(), and turb_flowlmupdateloglay().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calcChoose(x, y, z, std::multiplies<int>());
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calcChoose(x, y, z, std::multiplies<double>());
   }
 }
void mul_scalar (const Attribute * x, const void * y, Attribute * z, int swap = 0) static
Operation wrapper for multiplication with y as a scalar pointer.
Definition at line 347 of file op3args.C.
References BLAS_VOID, COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), x, y, and z.
Referenced by init(), FaceOffset_3::rescale_displacements(), rescale_object(), MarkerParticles_3::time_stepping(), and FaceOffset_3::time_stepping().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calc<std::multiplies<int>,BLAS_VOID>(z, x, y, std::multiplies<int>(), swap);
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calc<std::multiplies<double>,BLAS_VOID>(z, x, y, std::multiplies<double>(), swap);
   }
 }
void neg (const Attribute * x, Attribute * y) static
Wrapper for neg (y=-x).
Definition at line 455 of file op2args.C.
References BLAS_SCALAR, BLAS_SCNE, BLAS_VEC, BLAS_VEC2D, COM_assertion_msg, COM_CHAR, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), Attribute::fullname(), Attribute::is_windowed(), Attribute::size_of_components(), x, and z.
Referenced by init().
{
   COM_Type att_type = x->data_type();
   const int xncomp = x->size_of_components();
   if ( att_type == COM_INT || att_type == COM_INTEGER) {
     if ( x->is_windowed()) {
       if ( xncomp == 1)
         gen2arg<nega<int>,BLAS_SCALAR>(z, const_cast<Attribute*>(x), nega<int>());
       else
         gen2arg<nega<int>,BLAS_VEC>(z, const_cast<Attribute*>(x), nega<int>());
     }
     else {
       if ( xncomp == 1)
         gen2arg<nega<int>,BLAS_SCNE>(z, const_cast<Attribute*>(x), nega<int>());
       else
         gen2arg<nega<int>,BLAS_VEC2D>(z, const_cast<Attribute*>(x), nega<int>());
     }
   }
   else if ( att_type == COM_CHAR) {
     if ( x->is_windowed()) {
       if ( xncomp == 1)
         gen2arg<nega<char>,BLAS_SCALAR>(z, const_cast<Attribute*>(x), nega<char>());
       else
         gen2arg<nega<char>,BLAS_VEC>(z, const_cast<Attribute*>(x), nega<char>());
     }
     else {
       if ( xncomp == 1)
         gen2arg<nega<char>,BLAS_SCNE>(z, const_cast<Attribute*>(x), nega<char>());
       else
         gen2arg<nega<char>,BLAS_VEC2D>(z, const_cast<Attribute*>(x), nega<char>());
     }
   }
   else {
     COM_assertion_msg( att_type==COM_DOUBLE || att_type==COM_DOUBLE_PRECISION,
                        (std::string("Unsupported data type in ")+
                         x->fullname()).c_str());
     if ( x->is_windowed()) {
       if ( xncomp == 1)
         gen2arg<nega<double>,BLAS_SCALAR>(z, const_cast<Attribute*>(x), nega<double>());
       else
         gen2arg<nega<double>,BLAS_VEC>(z, const_cast<Attribute*>(x), nega<double>());
     }
     else {
       if ( xncomp == 1)
         gen2arg<nega<double>,BLAS_SCNE>(z, const_cast<Attribute*>(x), nega<double>());
       else
         gen2arg<nega<double>,BLAS_VEC2D>(z, const_cast<Attribute*>(x), nega<double>());
     }
   }
 }
void nrm2 (const Attribute * x, Attribute * y, const Attribute * mults = NULL) static
Wrapper for 2-norm.
Definition at line 288 of file dots.C.
References dot_MPI().
Referenced by init().
 { dot_MPI( x, x, y, NULL, mults); }
void nrm2_MPI (const Attribute * x, Attribute * y, const MPI_Comm * comm = NULL, const Attribute * mults = NULL) static
Wrapper for 2-norm with MPI.
Definition at line 298 of file dots.C.
References dot_MPI().
Referenced by init().
 { dot_MPI ( x, x, y, comm, mults); }
void nrm2_scalar (const Attribute * x, void * y, const Attribute * mults = NULL) static
Wrapper for 2-norm with y as a scalar pointer.
Definition at line 293 of file dots.C.
References dot_scalar_MPI().
Referenced by init().
 { dot_scalar_MPI ( x, x, y, NULL, mults); }
void nrm2_scalar_MPI (const Attribute * x, void * y, const MPI_Comm * comm, const Attribute * mults = NULL) static
Wrapper for 2-norm with y as a scalar pointer with MPI.
Definition at line 303 of file dots.C.
References dot_scalar_MPI().
Referenced by init().
 { dot_scalar_MPI ( x, x, y, comm, mults); }
void rand (const Attribute * a, Attribute * z) static
Generate a random number between 0 and $a$ for each entry in z.
Definition at line 388 of file op2args.C.
References Window::attributes(), BLAS_SCALAR, BLAS_SCNE, BLAS_VEC, BLAS_VEC2D, COM_ALL, COM_assertion_msg, COM_ATTS, COM_CONN, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, COM_MESH, COM_PMESH, Attribute::data_type(), Attribute::fullname(), i, Attribute::id(), Attribute::is_windowed(), Window::name(), Attribute::size_of_components(), Attribute::window(), x, and z.
Referenced by init().
{
   switch ( x->id()) {
   case COM::COM_ATTS: {
     COM_assertion_msg( z->id() == COM::COM_ATTS,
                        "Aggregate attributes for copy must match.");
     // Obtain all the attributes of their corresponding windows
     std::vector< const Attribute*>  x_attrs;
     x->window()->attributes( x_attrs);
     std::vector< Attribute*>  z_attrs;
     z->window()->attributes( z_attrs);
     // Copy all the individual attributes
     COM_assertion_msg( x_attrs.size() == z_attrs.size(),
                        (std::string("Numbers of attributes do not match between ")+
                         x->window()->name()+" and "+z->window()->name()).c_str());
     for ( int i=x_attrs.size()-1; i>=0; --i)
       rand( x_attrs[i], z_attrs[i]);
     return;
   }
   case COM::COM_MESH:
   case COM::COM_PMESH:
   case COM::COM_CONN:
   case COM::COM_ALL:
     COM_assertion_msg(false, "Only the aggregate attribute atts is supported");
   default: ;
   }
   COM_Type att_type = x->data_type();
   const int xncomp = x->size_of_components();
   if ( att_type == COM_INT || att_type == COM_INTEGER) {
     if ( x->is_windowed()) {
       if ( xncomp == 1)
         gen2arg<random<int>,BLAS_SCALAR>(z, const_cast<Attribute*>(x), random<int>());
       else
         gen2arg<random<int>,BLAS_VEC>(z, const_cast<Attribute*>(x), random<int>());
     }
     else {
       if ( xncomp == 1)
         gen2arg<random<int>,BLAS_SCNE>(z, const_cast<Attribute*>(x), random<int>());
       else
         gen2arg<random<int>,BLAS_VEC2D>(z, const_cast<Attribute*>(x), random<int>());
     }
   }
   else {
     COM_assertion_msg( att_type==COM_DOUBLE || att_type==COM_DOUBLE_PRECISION,
                        (std::string("Unsupported data type in ")+
                         x->fullname()).c_str());
     if ( x->is_windowed()) {
       if ( xncomp == 1)
         gen2arg<random<double>,BLAS_SCALAR>(z, const_cast<Attribute*>(x), random<double>());
       else
         gen2arg<random<double>,BLAS_VEC>(z, const_cast<Attribute*>(x), random<double>());
     }
     else {
       if ( xncomp == 1)
         gen2arg<random<double>,BLAS_SCNE>(z, const_cast<Attribute*>(x), random<double>());
       else
         gen2arg<random<double>,BLAS_VEC2D>(z, const_cast<Attribute*>(x), random<double>());
     }
   }
 }
void rand_scalar (const void * a, Attribute * z) static
Generate a random number between 0 and $a$ for each entry in z.
Definition at line 604 of file op2args.C.
References BLAS_VOID, COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), and z.
Referenced by init(), and Window_manifold_2::perturb_mesh().
{
   COM_Type att_type = z->data_type();
   if ( att_type == COM_INT || att_type == COM_INTEGER)
     gen2arg<random<int>,BLAS_VOID>(z, const_cast<void*>(a), random<int>());
   else {
     COM_assertion_msg( att_type==COM_DOUBLE || att_type==COM_DOUBLE_PRECISION,
                        (std::string("Unsupported data type in ")+
                         z->fullname()).c_str());
     gen2arg<random<double>,BLAS_VOID>(z, const_cast<void*>(a), random<double>());
   }
 }
void reduce_MPI (const Attribute * x, Attribute * z, const MPI_Comm * comm, int initialI, double initialD) inline static protected
Definition at line 630 of file op2args.C.
References COM_assertion_msg, COM_CHAR, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, COMMPI_Initialized(), convert2mpiop(), copy_scalar(), Attribute::data_type(), Attribute::fullname(), Attribute::is_windowed(), Attribute::pointer(), Attribute::size_of_components(), and x.
{
   COM_Type att_type = z->data_type();
   const int zncomp = z->size_of_components();
   if ( att_type == COM_INT || att_type == COM_INTEGER) {
     copy_scalar( &initialI, z);
     if ( z->is_windowed()) {
       if ( zncomp == 1)
         gen2arg<OPint,BLAS_SCALAR>(const_cast<Attribute*>(x), z, OPint());
       else
         gen2arg<OPint,BLAS_VEC>(const_cast<Attribute*>(x), z, OPint());
       if ( comm && *comm!=MPI_COMM_NULL && COMMPI_Initialized()) {
         std::vector<int> t((int*)z->pointer(), ((int*)z->pointer())+zncomp);
         MPI_Allreduce( &t[0], z->pointer(), zncomp, MPI_INT,
                        convert2mpiop(OPMPI), *comm);
       }
     }
     else {
       if ( zncomp == 1)
         gen2arg<OPint,BLAS_SCNE>(const_cast<Attribute*>(x), z, OPint());
       else
         gen2arg<OPint,BLAS_VEC2D>(const_cast<Attribute*>(x), z, OPint());
     }
   }
   else if ( att_type == COM_CHAR) {
     copy_scalar( &initialI, z);
     if ( z->is_windowed()) {
       if ( zncomp == 1)
         gen2arg<OPint,BLAS_SCALAR>(const_cast<Attribute*>(x), z, OPint());
       else
         gen2arg<OPint,BLAS_VEC>(const_cast<Attribute*>(x), z, OPint());
       if ( comm && *comm!=MPI_COMM_NULL && COMMPI_Initialized()) {
         std::vector<char> t((char*)z->pointer(), ((char*)z->pointer())+zncomp);
         MPI_Allreduce( &t[0], z->pointer(), zncomp, MPI_CHAR,
                        convert2mpiop(OPMPI), *comm);
       }
     }
     else {
       if ( zncomp == 1)
         gen2arg<OPint,BLAS_SCNE>(const_cast<Attribute*>(x), z, OPint());
       else
         gen2arg<OPint,BLAS_VEC2D>(const_cast<Attribute*>(x), z, OPint());
     }
   }
   else {
     COM_assertion_msg( att_type==COM_DOUBLE || att_type==COM_DOUBLE_PRECISION,
                        (std::string("Unsupported data type in ")+
                         z->fullname()).c_str());
     copy_scalar( &initialD, z);
     if ( z->is_windowed()) {
       if ( zncomp == 1)
         gen2arg<OPdbl,BLAS_SCALAR>(const_cast<Attribute*>(x), z, OPdbl());
       else
         gen2arg<OPdbl,BLAS_VEC>(const_cast<Attribute*>(x), z, OPdbl());
       if ( comm && *comm!=MPI_COMM_NULL && COMMPI_Initialized()) {
         std::vector<double> t( (double*)z->pointer(),
                                ((double*)z->pointer())+zncomp);
         MPI_Allreduce( &t[0], z->pointer(), zncomp, MPI_DOUBLE,
                        convert2mpiop(OPMPI), *comm);
       }
     }
     else {
       if ( zncomp == 1)
         gen2arg<OPdbl,BLAS_SCNE>(const_cast<Attribute*>(x), z, OPdbl());
       else
         gen2arg<OPdbl,BLAS_VEC2D>(const_cast<Attribute*>(x), z, OPdbl());
     }
   }
 }
void reduce_scalar_MPI (const Attribute * x, void * y, const MPI_Comm * comm, int initialI, double initialD) inline static protected
Definition at line 726 of file op2args.C.
References COM_assertion_msg, COM_CHAR, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, COMMPI_Initialized(), convert2mpiop(), Attribute::data_type(), Attribute::fullname(), and x.
{
   COM_Type att_type = x->data_type();
   if ( att_type == COM_INT || att_type == COM_INTEGER) {
     *(int*)y = initialI;
     gen2arg<OPint,BLAS_VOID>(const_cast<Attribute*>(x), y, OPint());
     if ( comm && *comm!=MPI_COMM_NULL && COMMPI_Initialized()) {
       int t = *(int*)y;
       MPI_Allreduce( &t, y, 1, MPI_INT, convert2mpiop(OPMPI), *comm);
     }
   }
   else if ( att_type == COM_CHAR) {
     *(char*)y = initialI;
     gen2arg<OPint,BLAS_VOID>(const_cast<Attribute*>(x), y, OPint());
     if ( comm && *comm!=MPI_COMM_NULL && COMMPI_Initialized()) {
       char t = *(char*)y;
       MPI_Allreduce( &t, y, 1, MPI_CHAR, convert2mpiop(OPMPI), *comm);
     }
   }
   else {
     COM_assertion_msg( att_type==COM_DOUBLE || att_type==COM_DOUBLE_PRECISION,
                        (std::string("Unsupported data type in ")+
                         x->fullname()).c_str());
     *(double*)y = initialD;
     gen2arg<OPdbl,BLAS_VOID>(const_cast<Attribute*>(x), y, OPdbl());
     if ( comm && *comm!=MPI_COMM_NULL && COMMPI_Initialized()) {
       double t = *(double*)y;
       MPI_Allreduce( &t, y, 1, MPI_DOUBLE, convert2mpiop(OPMPI), *comm);
     }
   }
 }
void sqrt (const Attribute * x, Attribute * y) static
Wrapper for sqrt (y=sqrt(x)).
Definition at line 507 of file op2args.C.
References BLAS_SCALAR, BLAS_SCNE, BLAS_VEC, BLAS_VEC2D, COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), Attribute::fullname(), Attribute::is_windowed(), Attribute::size_of_components(), x, and z.
Referenced by Window_manifold_2::compute_shortest_edgelen_nodes(), and init().
{
   COM_Type att_type = x->data_type();
   const int xncomp = x->size_of_components();
   if ( att_type == COM_INT || att_type == COM_INTEGER) {
     if ( x->is_windowed()) {
       if ( xncomp == 1)
         gen2arg<sqrta<int>,BLAS_SCALAR>(z, const_cast<Attribute*>(x), sqrta<int>());
       else
         gen2arg<sqrta<int>,BLAS_VEC>(z, const_cast<Attribute*>(x), sqrta<int>());
     }
     else {
       if ( xncomp == 1)
         gen2arg<sqrta<int>,BLAS_SCNE>(z, const_cast<Attribute*>(x), sqrta<int>());
       else
         gen2arg<sqrta<int>,BLAS_VEC2D>(z, const_cast<Attribute*>(x), sqrta<int>());
     }
   }
   else {
     COM_assertion_msg( att_type==COM_DOUBLE || att_type==COM_DOUBLE_PRECISION,
                        (std::string("Unsupported data type in ")+
                         x->fullname()).c_str());
     if ( x->is_windowed()) {
       if ( xncomp == 1)
         gen2arg<sqrta<double>,BLAS_SCALAR>(z, const_cast<Attribute*>(x), sqrta<double>());
       else
         gen2arg<sqrta<double>,BLAS_VEC>(z, const_cast<Attribute*>(x), sqrta<double>());
     }
     else {
       if ( xncomp == 1)
         gen2arg<sqrta<double>,BLAS_SCNE>(z, const_cast<Attribute*>(x), sqrta<double>());
       else
         gen2arg<sqrta<double>,BLAS_VEC2D>(z, const_cast<Attribute*>(x), sqrta<double>());
     }
   }
 }
void sub (const Attribute * x, const Attribute * y, Attribute * z) static
Operation wrapper for subtraction.
Definition at line 237 of file op3args.C.
References calcChoose(), COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), and Attribute::fullname().
Referenced by FaceOffset_3::balance_mass(), Rocmop::get_usr_disp(), init(), Rocprop::propagate(), and Rocmop::smooth().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calcChoose(x, y, z, std::minus<int>());
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calcChoose(x, y, z, std::minus<double>());
   }
 }
void sub_scalar (const Attribute * x, const void * y, Attribute * z, int swap = 0) static
Operation wrapper for subtraction with y as a scalar pointer.
Definition at line 331 of file op3args.C.
References BLAS_VOID, COM_assertion_msg, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, Attribute::data_type(), x, y, and z.
Referenced by init(), and Window_manifold_2::perturb_mesh().
 {
   COM_Type att_type = z->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     calc<std::minus<int>,BLAS_VOID>(z, x, y, std::minus<int>(), swap);
   else {
     COM_assertion_msg(att_type == COM_DOUBLE||att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        z->fullname()).c_str());
     calc<std::minus<double>,BLAS_VOID>(z, x, y, std::minus<double>(), swap);
   }
 }
void sum_MPI (const Attribute * x, Attribute * y, const MPI_Comm * comm = NULL) static
Wrapper for sum.
Definition at line 720 of file op2args.C.
References BLAS_SUM, x, and z.
Referenced by init().
{
   reduce_MPI< sumv<int>, sumv<double>, BLAS_SUM>( x, z, comm, 0, 0);
 }
void sum_scalar_MPI (const Attribute * x, void * y, const MPI_Comm * comm = NULL) static
Operation wrapper for sum (y is a scalar pointer).
Definition at line 778 of file op2args.C.
References BLAS_SUM, x, and y.
Referenced by init().
{
   reduce_scalar_MPI< sumv<int>, sumv<double>, BLAS_SUM>( x, y, comm, 0, 0);
 }
void swap (Attribute * x, Attribute * y) static
Wrapper for swap.
Definition at line 271 of file op2args.C.
References Window::attributes(), BLAS_VEC2D, COM_ALL, COM_assertion_msg, COM_ATTS, COM_CHAR, COM_CONN, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_INT, COM_INTEGER, COM_MESH, COM_PMESH, Attribute::data_type(), i, Attribute::id(), Window::name(), Attribute::window(), x, and y.
Referenced by init().
{
   switch ( x->id()) {
   case COM::COM_ATTS: {
     COM_assertion_msg( y->id() == COM::COM_ATTS,
                        "Aggregate attributes for swap must match.");
     // Obtain all the attributes of their corresponding windows
     std::vector< Attribute*>  x_attrs;
     x->window()->attributes( x_attrs);
     std::vector< Attribute*>  y_attrs;
     y->window()->attributes( y_attrs);
     COM_assertion_msg( x_attrs.size() == y_attrs.size(),
                        (std::string("Numbers of attributes do not match between ")+
                         x->window()->name()+" and "+y->window()->name()).c_str());
     // Copy all the individual attributes
     for ( int i=x_attrs.size()-1; i>=0; --i)
       swap( x_attrs[i], y_attrs[i]);
     return;
   }
   case COM::COM_MESH:
   case COM::COM_PMESH:
   case COM::COM_CONN:
   case COM::COM_ALL:
     COM_assertion_msg(false, "Only the aggregate attribute atts is supported");
   default: ;
   }
   COM_Type att_type = x->data_type();
   if(att_type == COM_INT || att_type == COM_INTEGER)
     gen2arg<swapp<int>,BLAS_VEC2D>(x, y, swapp<int>());
   else if(att_type == COM_CHAR)
     gen2arg<swapp<char>,BLAS_VEC2D>(x, y, swapp<char>());
   else {
     COM_assertion_msg(att_type == COM_DOUBLE || att_type == COM_DOUBLE_PRECISION,
                       (std::string("Unsupported data type in ")+
                        x->fullname()).c_str());
     gen2arg<swapp<double>,BLAS_VEC2D>(x, y, swapp<double>());
   }
 }
static std::string to_str (int i) inline static protected
Definition at line 283 of file Rocblas.h.
Referenced by axpy_gen(), calc(), calcDot(), and gen2arg().
{
     char buf[10];
     std::sprintf( buf, "%d", i);
     return buf;
   }
The documentation for this class was generated from the following files:
Rocblas.h
axpy.C
dots.C
op2args.C
op3args.C
Rocblas.C