Rocstar: MeshImplVertIter Class Reference
MeshImplVertIter Class Reference
VertexIterator for MeshImpl.
#include <MeshImplData.hpp>
Public Member Functions
MeshImplVertIter (MeshImplData *data)
virtual ~MeshImplVertIter ()
virtual void restart ()
Moves the iterator back to the first entity in the list.
virtual void operator++ ()
++iterator
virtual Mesh::VertexHandle operator* () const
*iterator.
virtual bool is_at_end () const
Returns false until the iterator has been advanced PAST the last entity.
MeshImplVertIter (MeshImplData *data)
virtual ~MeshImplVertIter ()
virtual void restart ()
Moves the iterator back to the first entity in the list.
virtual void operator++ ()
++iterator
virtual Mesh::VertexHandle operator* () const
*iterator.
virtual bool is_at_end () const
Returns false until the iterator has been advanced PAST the last entity.
Public Member Functions inherited from EntityIterator
virtual ~EntityIterator ()
Private Attributes
MeshImplData * mesh
size_t index
Detailed Description
VertexIterator for MeshImpl.
Iterate over valid vertex indices
Definition at line 245 of file includeLinks/MeshImplData.hpp.
Constructor & Destructor Documentation
MeshImplVertIter (MeshImplData * data) inline
Definition at line 253 of file includeLinks/MeshImplData.hpp.
References MeshImplVertIter::restart().
       : mesh(data) { restart(); }
~MeshImplVertIter () virtual
Definition at line 703 of file Mesh/MeshImplData.cpp.
   {}
MeshImplVertIter (MeshImplData * data) inline
Definition at line 253 of file src/Mesh/MeshImplData.hpp.
References MeshImplVertIter::restart().
       : mesh(data) { restart(); }
virtual ~MeshImplVertIter () virtual
Member Function Documentation
bool is_at_end () const virtual
Returns false until the iterator has been advanced PAST the last entity.
Once is_at_end() returns true, *iterator returns 0.
Implements EntityIterator.
Definition at line 727 of file Mesh/MeshImplData.cpp.
References MeshImplVertIter::index, MeshImplData::max_vertex_index(), and MeshImplVertIter::mesh.
 {
   return index >= mesh->max_vertex_index();
 }
virtual bool is_at_end () const virtual
Returns false until the iterator has been advanced PAST the last entity.
Once is_at_end() returns true, *iterator returns 0.
Implements EntityIterator.
Mesh::VertexHandle operator* () const virtual
*iterator.
Return the handle currently being pointed at by the iterator.
Implements EntityIterator.
Definition at line 722 of file Mesh/MeshImplData.cpp.
References MeshImplVertIter::index.
 {
   return reinterpret_cast<Mesh::VertexHandle>(index);
 }
virtual Mesh::VertexHandle operator* () const virtual
*iterator.
Return the handle currently being pointed at by the iterator.
Implements EntityIterator.
void operator++ () virtual
++iterator
Implements EntityIterator.
Definition at line 713 of file Mesh/MeshImplData.cpp.
References MeshImplVertIter::index, MeshImplData::is_corner_node(), MeshImplData::is_vertex_valid(), and MeshImplVertIter::mesh.
 {
   ++index;
   while (index < mesh->max_vertex_index() &&
          (!mesh->is_vertex_valid(index) ||
           !mesh->is_corner_node(index)))
     ++index;
 }
virtual void operator++ () virtual
++iterator
Implements EntityIterator.
void restart () virtual
Moves the iterator back to the first entity in the list.
Implements EntityIterator.
Definition at line 706 of file Mesh/MeshImplData.cpp.
References MeshImplVertIter::index, MeshImplData::is_vertex_valid(), and MeshImplVertIter::mesh.
Referenced by MeshImplVertIter::MeshImplVertIter().
 {
   index = 0;
   if (!mesh->is_vertex_valid( index ))
     operator++();
 }
virtual void restart () virtual
Moves the iterator back to the first entity in the list.
Implements EntityIterator.
Member Data Documentation
size_t index private
Definition at line 249 of file includeLinks/MeshImplData.hpp.
Referenced by MeshImplVertIter::is_at_end(), MeshImplVertIter::operator*(), MeshImplVertIter::operator++(), and MeshImplVertIter::restart().
MeshImplData * mesh private
Definition at line 248 of file includeLinks/MeshImplData.hpp.
Referenced by MeshImplVertIter::is_at_end(), MeshImplVertIter::operator++(), and MeshImplVertIter::restart().
The documentation for this class was generated from the following files:
includeLinks/MeshImplData.hpp
Mesh/MeshImplData.cpp