Rocstar: rflu_modflowhardcode Module Reference
rflu_modflowhardcode Module Reference
Public Member Functions
subroutine, public rflu_getparamshardcodepacoust (pTot, aTot)
subroutine, public rflu_getparamshardcodeproudman (dInc, mInj, vInj, pTot)
subroutine, public rflu_getparamshardcoderingleb (pTot, tTot)
subroutine, public rflu_getparamshardcodessvortex (ri, Mi, pTot, tTot)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModFlowHardCode.F90,v $ $Revision: 1.6 $'
Detailed Description
Definition at line 42 of file RFLU_ModFlowHardCode.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_getparamshardcodepacoust (real(rfreal), intent(out) pTot, real(rfreal), intent(out) aTot)
Definition at line 86 of file RFLU_ModFlowHardCode.F90.
Referenced by rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), and rflu_initflowhardcode().
subroutine, public rflu_getparamshardcodeproudman (real(rfreal), intent(out) dInc, real(rfreal), intent(out) mInj, real(rfreal), intent(out) vInj, real(rfreal), intent(out) pTot)
Definition at line 115 of file RFLU_ModFlowHardCode.F90.
Referenced by rflu_computeexactflowerror(), rflu_modextractflowdata::rflu_extractflowdataproudman(), rflu_initbcdatahardcode(), and rflu_initflowhardcode().
subroutine, public rflu_getparamshardcoderingleb (real(rfreal), intent(out) pTot, real(rfreal), intent(out) tTot)
Definition at line 144 of file RFLU_ModFlowHardCode.F90.
Referenced by rflu_computeexactflowerror(), rflu_initbcdatahardcode(), and rflu_initflowhardcode().
subroutine, public rflu_getparamshardcodessvortex (real(rfreal), intent(out) ri, real(rfreal), intent(out) Mi, real(rfreal), intent(out) pTot, real(rfreal), intent(out) tTot)
Definition at line 173 of file RFLU_ModFlowHardCode.F90.
Referenced by rflu_computeexactflowerror(), rflu_initbcdatahardcode(), and rflu_initflowhardcode().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModFlowHardCode.F90,v $ $Revision: 1.6 $' private
Definition at line 59 of file RFLU_ModFlowHardCode.F90.
The documentation for this module was generated from the following file:
RFLU_ModFlowHardCode.F90