Rocstar: m_rocburn_2d Module Reference
m_rocburn_2d Module Reference
Public Member Functions
subroutine check_alloc (ierr)
subroutine init_wrapper (G_b, initial_time, comm, MAN_INIT, inSurf, inInt, IN_obt_attr)
subroutine initialize (G_b, MAN_INIT, inSurf, inInt, INIT_0D, INIT_1D, IN_obt_attr)
subroutine finalize (G_b)
subroutine update_wrapper (G_b, timestamp, dt, MAN_UPDATE)
subroutine update (G_b, timestamp, dt, MAN_UPDATE, GET_FILM_COEFF_1D, GET_TIME_STEP_1D, GET_BURNING_RATE_1D)
Public Attributes
integer, parameter model_apn = 1
integer, parameter model_py = 2
integer, parameter model_zn = 3
integer, parameter no_tbl = 0
character(*), parameter iowin = "Burn"
character(*), parameter intwin = "BurnInt"
Detailed Description
Definition at line 23 of file rocburn_2D.f90.
Member Function/Subroutine Documentation
subroutine check_alloc (integer, intent(in) ierr)
Definition at line 53 of file rocburn_2D.f90.
References Aff_transformation_repS2< FT >::print().
Referenced by initialize(), and m_rocburn_1d_zn::initialize_0d().
subroutine finalize (type(list_block), pointer G_b)
Definition at line 374 of file rocburn_2D.f90.
Referenced by rocburn_load_module().
subroutine init_wrapper (type(list_block), pointer G_b, real(dbl), intent(in) initial_time, integer, intent(in) comm, integer, intent(in) MAN_INIT, character(*), intent(in) inSurf, character(*), intent(in) inInt, integer, intent(in) IN_obt_attr)
Definition at line 61 of file rocburn_2D.f90.
Referenced by rocburn_load_module().
subroutine initialize (type(list_block), pointer G_b, integer, intent(in) MAN_INIT, character(*), intent(in) inSurf, character(*), intent(in) inInt, INIT_0D, INIT_1D, integer, intent(in) IN_obt_attr)
Definition at line 83 of file rocburn_2D.f90.
References check_alloc(), ic, and Matrix3D::zero().
Referenced by rflo_sendboundaryvalues(), and rocburn_load_module().
subroutine update (type(list_block), pointer G_b, real(dbl), intent(in) timestamp, real(dbl), intent(in) dt, integer, intent(in) MAN_UPDATE, GET_FILM_COEFF_1D, GET_TIME_STEP_1D, GET_BURNING_RATE_1D)
Definition at line 412 of file rocburn_2D.f90.
References Color::alpha(), m_calcdist::calcdist_2d(), m_rocburn_1d_apn::get_burning_rate_1d(), m_rocburn_1d_zn::get_film_coeff_1d(), setup_py::get_time_step_1d(), ic, and Matrix3D::zero().
Referenced by rocburn_load_module().
subroutine update_wrapper (type(list_block), pointer G_b, real(dbl), intent(in) timestamp, real(dbl), intent(in) dt, integer, intent(in) MAN_UPDATE)
Definition at line 399 of file rocburn_2D.f90.
Referenced by rocburn_load_module().
Member Data Documentation
character(*), parameter intwin = "BurnInt"
Definition at line 47 of file rocburn_2D.f90.
character(*), parameter iowin = "Burn"
Definition at line 46 of file rocburn_2D.f90.
integer, parameter model_apn = 1
Definition at line 43 of file rocburn_2D.f90.
integer, parameter model_py = 2
Definition at line 43 of file rocburn_2D.f90.
integer, parameter model_zn = 3
Definition at line 43 of file rocburn_2D.f90.
integer, parameter no_tbl = 0
Definition at line 44 of file rocburn_2D.f90.
The documentation for this module was generated from the following file:
rocburn_2D.f90