Rocstar: MobileObject Class Reference
MobileObject Class Reference
provides communication for complex objects.
#include <COMM.H>
Public Member Functions
MobileObject ()
void ** GetBufPtr ()
const void * GetBuffer () const
void * GetBuffer ()
int BufSize ()
virtual int PrepareBuffer (size_t bsize)
virtual int Pack (void **inbuf=NULL)
virtual int UnPack (const void *outbuf=NULL)
virtual void DestroyBuffer ()
virtual ~MobileObject ()
Protected Attributes
void * _buf
bool _mine
int _bsize
Detailed Description
provides communication for complex objects.
The MobileObject provides buffering and an interface for complex objects to use communication routines.
Definition at line 27 of file COMM.H.
Constructor & Destructor Documentation
MobileObject () inline
Definition at line 34 of file COMM.H.
 : _buf(NULL), _mine(false), _bsize(0) {};
virtual ~MobileObject () inline virtual
Definition at line 50 of file COMM.H.
References MobileObject::DestroyBuffer().
       {
         DestroyBuffer();
       };
Member Function Documentation
int BufSize () inline
Definition at line 38 of file COMM.H.
References MobileObject::_bsize.
 { return(_bsize); };
virtual void DestroyBuffer () inline virtual
Definition at line 42 of file COMM.H.
References MobileObject::_bsize, MobileObject::_buf, and MobileObject::_mine.
Referenced by CommunicatorObject::_AllGatherMO(), CommunicatorObject::_GatherMO(), and MobileObject::~MobileObject().
       {
         if(_buf && _mine)
           delete [] (char*)_buf;
         _buf = NULL;
         _mine = false;
         _bsize = 0;
       };
const void* GetBuffer () const inline
Definition at line 36 of file COMM.H.
References MobileObject::_buf.
Referenced by CommunicatorObject::_AllGatherMO(), CommunicatorObject::_GatherMO(), and CommunicatorObject::BroadCast().
 { return (_buf); };
void* GetBuffer () inline
Definition at line 37 of file COMM.H.
References MobileObject::_buf.
 {return (_buf); };
void** GetBufPtr () inline
Definition at line 35 of file COMM.H.
References MobileObject::_buf.
 { return(_buf ? &_buf : NULL); };
int Pack (void ** inbuf = NULL) virtual
Definition at line 22 of file COMM.C.
References MobileObject::_bsize, MobileObject::_buf, MobileObject::_mine, and IRAD::Util::String2Buf().
Referenced by CommunicatorObject::_AllGatherMO(), CommunicatorObject::_GatherMO(), and CommunicatorObject::BroadCast().
     {
       if(_buf && _mine){
         delete [] (char *)_buf;
         _buf = NULL;
         _mine = false;
       }
       std::ostringstream Ostr;
       // Ostr << *this;
       if(!inbuf){
         int nchar = Util::String2Buf(Ostr.str(),&_buf);
         if(_buf){
           _mine = true;
           _bsize = nchar;
           return(_bsize);
         }
       }
       else {
         // Caller must free inbuf, else it leaks
         int nchar = Util::String2Buf(Ostr.str(),inbuf);
         if(*inbuf){
           _buf = *inbuf;
           _mine = false;
           _bsize = nchar;
           return(_bsize);
         }
       }
       return 0;
     };
int PrepareBuffer (size_t bsize) virtual
Definition at line 10 of file COMM.C.
References MobileObject::_bsize, MobileObject::_buf, and MobileObject::_mine.
Referenced by CommunicatorObject::BroadCast().
     {
       if(_buf && _mine)
         delete [] (char *)_buf;
       _buf = new char [bsize];
       if(!_buf)
         return 0;
       _bsize = bsize;
       _mine = true;
       return _bsize;
     };
int UnPack (const void * outbuf = NULL) virtual
Definition at line 52 of file COMM.C.
References MobileObject::_bsize, MobileObject::_buf, and MobileObject::_mine.
Referenced by CommunicatorObject::BroadCast().
     {
       if(!inbuf){
         if(!_buf)
           return 1;
         std::istringstream Istr(std::string((const char *)_buf));
         //      Istr >> *this;
         if(_mine){
           delete [] (char *)_buf;
           _buf  = NULL;
           _mine = false;
           _bsize = 0;
         }
         return(0);
       }
       else{
         std::istringstream Istr(std::string((const char *)inbuf));
         //      Istr >> *this;
         return(0);
       }
       return 0;
     };
Member Data Documentation
int _bsize protected
Definition at line 32 of file COMM.H.
Referenced by MobileObject::BufSize(), MobileObject::DestroyBuffer(), MobileObject::Pack(), MobileObject::PrepareBuffer(), and MobileObject::UnPack().
void* _buf protected
Definition at line 30 of file COMM.H.
Referenced by MobileObject::DestroyBuffer(), MobileObject::GetBuffer(), MobileObject::GetBufPtr(), MobileObject::Pack(), MobileObject::PrepareBuffer(), and MobileObject::UnPack().
bool _mine protected
Definition at line 31 of file COMM.H.
Referenced by MobileObject::DestroyBuffer(), MobileObject::Pack(), MobileObject::PrepareBuffer(), and MobileObject::UnPack().
The documentation for this class was generated from the following files:
COMM.H
COMM.C