Rocstar: halfspace3d Class Reference
halfspace3d Class Reference
#include <vector3d.h>
Public Types
typedef const vector3d cv
Public Member Functions
halfspace3d ()
halfspace3d (cv &p1, cv &p2, cv &p3)
halfspace3d (cv &p1, cv &p2, cv &p3, cv &in)
halfspace3d (cv &norm, cv &p0)
void init (cv &p1, cv &p2, cv &p3)
void initCheck (cv &p1, cv &p2, cv &p3, cv &in)
real side (cv &pt) const
real intersect (cv &pos, cv &dir) const
vector3d intersectPt (cv &start, cv &dir) const
Public Attributes
vector3d n
real d
Detailed Description
Definition at line 182 of file vector3d.h.
Member Typedef Documentation
typedef const vector3d cv
Definition at line 188 of file vector3d.h.
Constructor & Destructor Documentation
halfspace3d () inline
Definition at line 189 of file vector3d.h.
 {}
halfspace3d (cv & p1, cv & p2, cv & p3) inline
Definition at line 190 of file vector3d.h.
References init().
 {init(p1,p2,p3);}
halfspace3d (cv & p1, cv & p2, cv & p3, cv & in) inline
Definition at line 191 of file vector3d.h.
References initCheck().
 {initCheck(p1,p2,p3,in);}
halfspace3d (cv & norm, cv & p0) inline
Definition at line 193 of file vector3d.h.
References d, vector3d::dot(), n, and nvc::norm().
 {n=norm;d=-n.dot(p0);}
Member Function Documentation
void init (cv & p1, cv & p2, cv & p3) inline
Definition at line 197 of file vector3d.h.
References nvc::cross(), d, vector3d::dot(), and n.
Referenced by halfspace3d(), and initCheck().
{
                 n=(p2-p1).cross(p3-p1);
                 d=-n.dot(p1);
         }
void initCheck (cv & p1, cv & p2, cv & p3, cv & in) inline
Definition at line 203 of file vector3d.h.
References d, init(), n, and side().
Referenced by halfspace3d().
         { init(p1,p2,p3); if (side(in)<0) {n=-n;d=-d;} }
real intersect (cv & pos, cv & dir) const inline
Definition at line 212 of file vector3d.h.
References d, vector3d::dot(), and n.
Referenced by intersectPt().
                 {return -(d+n.dot(pos))/n.dot(dir);}
vector3d intersectPt (cv & start, cv & dir) const inline
Definition at line 217 of file vector3d.h.
References intersect().
         {
                 return start+dir*intersect(start,dir);
         }
real side (cv & pt) const inline
Definition at line 208 of file vector3d.h.
References d, vector3d::dot(), and n.
Referenced by c3d6nm(), and initCheck().
         {return n.dot(pt)+d;}
Member Data Documentation
real d
Definition at line 186 of file vector3d.h.
Referenced by halfspace3d(), init(), initCheck(), intersect(), and side().
vector3d n
Definition at line 185 of file vector3d.h.
Referenced by halfspace3d(), init(), initCheck(), intersect(), and side().
The documentation for this class was generated from the following file:
vector3d.h