Rocstar: m_rocburn_interface_data Module Reference
m_rocburn_interface_data Module Reference
Data Types
type block
type g_burn_1d
type list_block
Public Member Functions
subroutine associate_pointer (attr, ptr)
Public Attributes
integer, parameter dbl = SELECTED_REAL_KIND(P=14, R=30)
Detailed Description
Definition at line 23 of file 01.burn_interface_data.f90.
Member Function/Subroutine Documentation
subroutine associate_pointer (type(list_block), pointer attr, type(list_block), pointer ptr)
Definition at line 143 of file 01.burn_interface_data.f90.
References Node::attr(), and Aff_transformationS2< FT >::ptr().
Referenced by rocburn_load_module(), rocburn_unload_module(), rocflo_load_module(), rocflo_unload_module(), rocflu_load_module(), rocflu_unload_module(), rocfrac_load_module(), and rocfrac_unload_module().
Member Data Documentation
integer, parameter dbl = SELECTED_REAL_KIND(P=14, R=30)
Definition at line 45 of file 01.burn_interface_data.f90.
The documentation for this module was generated from the following file:
01.burn_interface_data.f90