Rocstar: RFC_Data< _Tag > Class Template Reference
RFC_Data< _Tag > Class Template Reference
#include <RFC_Window_transfer.h>
Public Types
typedef RFC_Data_const< _Tag > Base
typedef Vector_n Value
typedef Array_n Value_nonconst
typedef Array_n_const Value_const
typedef unsigned int Size
typedef _Tag Tag
Public Types inherited from RFC_Data_const< _Tag >
typedef Vector_n Value
typedef Array_n Value_nonconst
typedef Array_n_const Value_const
typedef unsigned int Size
typedef _Tag Tag
Public Member Functions
RFC_Data ()
RFC_Data (RFC_Window_transfer &win, const char *aname)
RFC_Data (COM::Attribute *a)
RFC_Data (int i, int d)
Value_nonconst get_value (RFC_Pane_transfer *p, int v)
Value_const get_value (const RFC_Pane_transfer *p, int v) const
void set_value (RFC_Pane_transfer *p, int v, const Value_const &vec)
Value_nonconst get_value (Real *buf, int v) const
Value_const get_value (const Real *buf, int v) const
void set_value (Real *buf, int v, const Value_const &vec)
Tag tag () const
Public Member Functions inherited from RFC_Data_const< _Tag >
RFC_Data_const ()
RFC_Data_const (const RFC_Window_transfer &win, const char *aname)
RFC_Data_const (const COM::Attribute *a)
RFC_Data_const (int i, int d)
int id () const
Size dimension () const
bool is_valid (const RFC_Pane_transfer *p, int i) const
Value_const get_value (const RFC_Pane_transfer *p, int v) const
Value_const get_value (const Real *buf, int v) const
Tag tag () const
Additional Inherited Members
Protected Attributes inherited from RFC_Data_const< _Tag >
int _id
unsigned int _dim
Detailed Description
template<class _Tag>
class RFC_Data< _Tag >
Definition at line 42 of file RFC_Window_transfer.h.
Member Typedef Documentation
typedef RFC_Data_const<_Tag> Base
Definition at line 282 of file RFC_Window_transfer.h.
typedef unsigned int Size
Definition at line 286 of file RFC_Window_transfer.h.
typedef _Tag Tag
Definition at line 287 of file RFC_Window_transfer.h.
typedef Vector_n Value
Definition at line 283 of file RFC_Window_transfer.h.
typedef Array_n_const Value_const
Definition at line 285 of file RFC_Window_transfer.h.
typedef Array_n Value_nonconst
Definition at line 284 of file RFC_Window_transfer.h.
Constructor & Destructor Documentation
RFC_Data () inline
Definition at line 289 of file RFC_Window_transfer.h.
 {}
RFC_Data (RFC_Window_transfer & win, const char * aname) inline
Definition at line 290 of file RFC_Window_transfer.h.
 : Base( win, aname) {}
RFC_Data (COM::Attribute * a) inline
Definition at line 291 of file RFC_Window_transfer.h.
 :  Base( a) {}
RFC_Data (int i, int d) inline
Definition at line 292 of file RFC_Window_transfer.h.
 :  Base(i, d) {}
Member Function Documentation
Value_nonconst get_value (RFC_Pane_transfer * p, int v) inline
Definition at line 295 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, RFC_Pane_transfer::pointer(), and RFC_assertion.
Referenced by Transfer_base::integrate_subface(), Transfer_base::interpolate_fe(), Transfer_base::invert(), Transfer_base::precondition_Jacobi(), Transfer_base::saxpy(), Transfer_base::scale(), and Transfer_base::transfer_2f().
{
     RFC_assertion( v>=1);
     return Value_nonconst( p->pointer( _id) + (v-1)*_dim, _dim);
   }
Value_const get_value (const RFC_Pane_transfer * p, int v) const inline
Definition at line 300 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, RFC_Pane_transfer::pointer(), and RFC_assertion.
{
     RFC_assertion( v>=1);
     return Value_const( p->pointer( _id) + (v-1)*_dim, _dim);
   }
Value_nonconst get_value (Real * buf, int v) const inline
Definition at line 309 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, and RFC_assertion.
{
     RFC_assertion( v>=1);
     return Value_nonconst( buf + (v-1)*_dim, _dim);
   }
Value_const get_value (const Real * buf, int v) const inline
Definition at line 313 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, and RFC_assertion.
{
     RFC_assertion( v>=1);
     return Value_const( buf + (v-1)*_dim, _dim);
   }
void set_value (RFC_Pane_transfer * p, int v, const Value_const & vec) inline
Definition at line 304 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, Array_n_const::begin(), copy, Array_n_const::dimension(), Array_n_const::end(), RFC_Pane_transfer::pointer(), and RFC_assertion.
Referenced by Transfer_base::copy_vec().
{
     RFC_assertion( _dim == vec.dimension() && v>=1);
     std::copy( vec.begin(), vec.end(), p->pointer( _id) + (v-1)*_dim);
   }
void set_value (Real * buf, int v, const Value_const & vec) inline
Definition at line 317 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, Array_n_const::begin(), copy, Array_n_const::dimension(), Array_n_const::end(), and RFC_assertion.
{
     RFC_assertion( _dim == vec.dimension() && v>=1);
     std::copy( vec.begin(), vec.end(), buf + (v-1)*_dim);
   }
Tag tag () const inline
Definition at line 322 of file RFC_Window_transfer.h.
 { return Tag(); }
The documentation for this class was generated from the following file:
RFC_Window_transfer.h