Rocstar: rflu_modtimezoom Module Reference
rflu_modtimezoom Module Reference
Data Types
type t_timezoom
Public Member Functions
subroutine, public rflu_timezoomdriver (regions)
subroutine rflu_timezoomsumresiduals (Regions)
subroutine, public rflu_unzoomgridspeeds (pRegion)
subroutine, public rflu_zoomgridspeeds (pRegion)
Public Attributes
type(t_timezoom), public timezoom
Private Member Functions
subroutine rflu_timezoomcomputebulkvars (regions)
subroutine rflu_timezoomsumaddsource (regions)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModTimeZoom.F90,v $'
Detailed Description
Definition at line 32 of file RFLU_ModTimeZoom.F90.
Member Function/Subroutine Documentation
subroutine rflu_timezoomcomputebulkvars (type(t_region), dimension(:), pointer regions) private
Definition at line 85 of file RFLU_ModTimeZoom.F90.
References moderror::errorstop(), i, icell, max(), sqrt(), x, y, and z.
Referenced by rflu_timezoomdriver().
subroutine, public rflu_timezoomdriver (type(t_region), dimension(:), pointer regions)
Definition at line 72 of file RFLU_ModTimeZoom.F90.
References rflu_timezoomcomputebulkvars(), and rflu_timezoomsumaddsource().
Referenced by rungekuttamp().
subroutine rflu_timezoomsumaddsource (type(t_region), dimension(:), pointer regions) private
Definition at line 172 of file RFLU_ModTimeZoom.F90.
References icell, max(), rflu_modgridspeedutils::rflu_descalegridspeed(), rflu_modgridspeedutils::rflu_scalegridspeed(), rflu_timezoomsumresiduals(), x, y, and z.
Referenced by rflu_timezoomdriver().
subroutine rflu_timezoomsumresiduals (type(t_region), dimension(:), pointer Regions)
Definition at line 309 of file RFLU_ModTimeZoom.F90.
References moderror::errorstop(), icell, x, y, and z.
Referenced by rflu_timezoomsumaddsource().
subroutine, public rflu_unzoomgridspeeds (type(t_region), pointer pRegion)
Definition at line 388 of file RFLU_ModTimeZoom.F90.
Referenced by rflu_timestepping().
subroutine, public rflu_zoomgridspeeds (type(t_region), pointer pRegion)
Definition at line 461 of file RFLU_ModTimeZoom.F90.
Referenced by rflu_timestepping().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModTimeZoom.F90,v $' private
Definition at line 62 of file RFLU_ModTimeZoom.F90.
type (t_timezoom), public timezoom
Definition at line 56 of file RFLU_ModTimeZoom.F90.
The documentation for this module was generated from the following file:
RFLU_ModTimeZoom.F90