Rocstar: CornerTagHandles Class Reference
CornerTagHandles Class Reference
Utility class to manage tag handles for corner tags.
#include <CornerTag.hpp>
Public Member Functions
CornerTagHandles (const char *tag_name, Mesh::TagType type, unsigned tag_len)
TagHandle get_handle (Mesh *mesh, unsigned num_corners, MsqError &err)
Get the tag handle for storing this tag type with the specified number of values (corners).
void save_load_tags (bool load, PatchData *pd, size_t elem_index, void *data, size_t tag_byes, MsqError &err)
CornerTagHandles (const char *tag_name, Mesh::TagType type, unsigned tag_len)
TagHandle get_handle (Mesh *mesh, unsigned num_corners, MsqError &err)
Get the tag handle for storing this tag type with the specified number of values (corners).
void save_load_tags (bool load, PatchData *pd, size_t elem_index, void *data, size_t tag_byes, MsqError &err)
Static Public Member Functions
static Mesh * get_current_mesh (PatchData *pd)
static size_t size (Mesh::TagType type)
static int num_corners (PatchData *pd, int elem_index)
static Mesh * get_current_mesh (PatchData *pd)
static size_t size (Mesh::TagType type)
static int num_corners (PatchData *pd, int elem_index)
Private Attributes
const msq_std::string tagName
const Mesh::TagType tagType
const unsigned tagLen
msq_std::vector< TagHandle > cornerHandles
Detailed Description
Utility class to manage tag handles for corner tags.
Tags on corners are saved as an array of values on the corresponding element. As tags must be of a constant size, this necessitates using different tags for elements with different numbers of corners. This class manages the set of all tag handles for a given corner tag, where the specific tag handle can be retrieved by specifying the number of corners in the element.
Definition at line 54 of file includeLinks/CornerTag.hpp.
Constructor & Destructor Documentation
CornerTagHandles (const char * tag_name, Mesh::TagType type, unsigned tag_len) inline
Definition at line 57 of file includeLinks/CornerTag.hpp.
     : tagName( tag_name ),
       tagType(type),
       tagLen(tag_len)
     {}
CornerTagHandles (const char * tag_name, Mesh::TagType type, unsigned tag_len) inline
Definition at line 57 of file src/Mesh/CornerTag.hpp.
     : tagName( tag_name ),
       tagType(type),
       tagLen(tag_len)
     {}
Member Function Documentation
Mesh * get_current_mesh (PatchData * pd) static
Definition at line 50 of file Mesh/CornerTag.cpp.
References MeshSet::get_current_mesh(), and PatchData::get_mesh_set().
Referenced by CornerTagHandles::save_load_tags().
 {
   return pd->get_mesh_set() ? pd->get_mesh_set()->get_current_mesh() : 0;
 }
static Mesh* get_current_mesh (PatchData * pd) static
TagHandle get_handle (Mesh * mesh, unsigned num_corners, MsqError & err)
Get the tag handle for storing this tag type with the specified number of values (corners).
Definition at line 55 of file Mesh/CornerTag.cpp.
References CornerTagHandles::cornerHandles, MsqError::INVALID_ARG, MSQ_ERRZERO, MSQ_SETERR, CornerTagHandles::size(), Mesh::tag_create(), Mesh::tag_get(), Mesh::tag_properties(), CornerTagHandles::tagLen, CornerTagHandles::tagName, and CornerTagHandles::tagType.
Referenced by CornerTagHandles::save_load_tags().
 {
     // Resize vector as necessary
   if (corners >= cornerHandles.size())
   {
     cornerHandles.resize( corners+1, 0 );
   }
     // Get handle if we don't already have it
   if (!cornerHandles[corners])
   {
       // Construct tag name
     char numbuf[16];
     sprintf(numbuf, "%d", corners );
     msq_std::string name = tagName + numbuf;
       // Try to get existing handle
     cornerHandles[corners] = mesh->tag_get( name, err );  MSQ_ERRZERO(err);
       // If got handle, make sure type is correct
     if (cornerHandles[corners])
     {
       Mesh::TagType type;
       unsigned size;
       mesh->tag_properties( cornerHandles[corners], name, type, size, err );
       MSQ_ERRZERO(err);
       if (type != tagType || size != corners*tagLen)
       {
         MSQ_SETERR(err)("Invalid tag type", MsqError::INVALID_ARG );
         return 0;
       }
     }
       // If didn't get handle, try to create it
     else
     {
       cornerHandles[corners] = mesh->tag_create( name, tagType, tagLen * corners, 0, err );
       MSQ_ERRZERO(err);
     }
   }
   return cornerHandles[corners];
 }
TagHandle get_handle (Mesh * mesh, unsigned num_corners, MsqError & err)
Get the tag handle for storing this tag type with the specified number of values (corners).
int num_corners (PatchData * pd, int elem_index) static
Definition at line 44 of file Mesh/CornerTag.cpp.
References PatchData::element_by_index(), and MsqMeshEntity::vertex_count().
Referenced by CornerTagHandles::save_load_tags().
 {
   return pd->element_by_index(elem_index).vertex_count();
 }
static int num_corners (PatchData * pd, int elem_index) static
void save_load_tags (bool load, PatchData * pd, size_t elem_index, void * data, size_t tag_byes, MsqError & err)
Definition at line 98 of file Mesh/CornerTag.cpp.
References CornerTagHandles::get_current_mesh(), PatchData::get_element_array(), PatchData::get_element_handles_array(), CornerTagHandles::get_handle(), MSQ_CHKERR, MSQ_ERRRTN, CornerTagHandles::num_corners(), Mesh::tag_get_element_data(), Mesh::tag_set_element_data(), and MsqMeshEntity::vertex_count().
 {
   Mesh* mesh = get_current_mesh( pd );
   if (!mesh) // this happens for some tests in the test suite.
     return;
   MsqMeshEntity* elem_array = pd->get_element_array( err );
   unsigned num_corners = elem_array[elem_index].vertex_count();
   const Mesh::ElementHandle handle = pd->get_element_handles_array()[elem_index];
   TagHandle tag = get_handle( mesh, num_corners, err ); MSQ_ERRRTN(err);
   if (load)
     mesh->tag_get_element_data( tag, 1, &handle, data, err );
   else
     mesh->tag_set_element_data( tag, 1, &handle, data, err );
   MSQ_CHKERR(err);
 }
void save_load_tags (bool load, PatchData * pd, size_t elem_index, void * data, size_t tag_byes, MsqError & err)
static size_t size (Mesh::TagType type) static
size_t size (Mesh::TagType type) static
Definition at line 32 of file Mesh/CornerTag.cpp.
References Mesh::BOOL, Mesh::BYTE, Mesh::DOUBLE, Mesh::HANDLE, and Mesh::INT.
Referenced by CornerTag< T >::CornerTag(), and CornerTagHandles::get_handle().
 {
   switch (type) {
     case Mesh::BYTE:   return 1;
     case Mesh::BOOL:   return sizeof(bool);
     case Mesh::INT:    return sizeof(int);
     case Mesh::DOUBLE: return sizeof(double);
     case Mesh::HANDLE: return sizeof(Mesh::EntityHandle);
     default:           return 0;
   }
 }
Member Data Documentation
msq_std::vector< TagHandle > cornerHandles private
Definition at line 84 of file includeLinks/CornerTag.hpp.
Referenced by CornerTagHandles::get_handle().
const unsigned tagLen private
Definition at line 82 of file includeLinks/CornerTag.hpp.
Referenced by CornerTagHandles::get_handle().
const msq_std::string tagName private
Definition at line 80 of file includeLinks/CornerTag.hpp.
Referenced by CornerTagHandles::get_handle().
const Mesh::TagType tagType private
Definition at line 81 of file includeLinks/CornerTag.hpp.
Referenced by CornerTagHandles::get_handle().
The documentation for this class was generated from the following files:
includeLinks/CornerTag.hpp
Mesh/CornerTag.cpp