Rocstar: points Class Reference
points Class Reference
#include <points.h>
Public Member Functions
points ()
points (int num_points)
points (const points &p)
points & operator= (const points &p)
virtual ~points ()
virtual points * clone ()
void set_num_points (int n)
void set_num_vars (int n)
void set_num_indep_vars (int indep_vars)
int get_num_points ()
int get_num_vars ()
int get_num_indep_vars ()
void set_point_val (int point_number, int var, long double val)
void clear_dep_vars (int point_number)
pnt get_point (int n)
virtual int get_closest (long double *coord)
virtual std::vector< int > get_connected_points (int point_num)
virtual void sort ()
long double largest_val (int dim)
long double smallest_val (int dim)
Static Public Member Functions
static void delete_all (std::vector< points * > points_vector)
static bool contains_null (std::vector< points * > points_vector)
Protected Attributes
int num_points
int num_vars
int num_indep_vars
pnt ** pt_str
bitmap pt_set
Detailed Description
Definition at line 30 of file points.h.
Constructor & Destructor Documentation
points ()
Definition at line 7 of file points.cpp.
References num_indep_vars, num_points, num_vars, and pt_str.
Referenced by clone().
               {
     this->num_points = 0;
     this->num_vars = 0;
     this->num_indep_vars = 0;
     this->pt_str = NULL;
     return;
 }
points (int num_points)
points (const points & p)
Definition at line 30 of file points.cpp.
References bitmap::check_value(), i, num_indep_vars, num_points, num_vars, pt_set, and pt_str.
{
     num_points = p.num_points;
     num_vars = p.num_vars;
     num_indep_vars = p.num_indep_vars;
     if(num_points > 0)
         pt_str = new pnt*[num_points];
     pt_set = p.pt_set;
     for(int i=0; i<num_points; i++){
         if(pt_set.check_value(i)){
             pt_str[i] = new pnt( *(p.pt_str[i]) );
         }
     }
 }
~points () virtual
Definition at line 15 of file points.cpp.
References bitmap::check_value(), i, num_points, pt_set, and pt_str.
                {
     if(num_points > 0){
         for(int i=0; i<num_points; i++){
             if(pt_set.check_value(i)){
                 delete pt_str[i];
             }
         }
         delete[] pt_str;
     }
     return;
 }
Member Function Documentation
void clear_dep_vars (int point_number)
Definition at line 171 of file points.cpp.
References i, num_indep_vars, pt_str, and pnt::vals.
{
     long double *temp = new long double[num_indep_vars];
     for(int i=0; i<num_indep_vars; i++){
         temp[i] = pt_str[point_number]->vals[i];
     }
     delete[] pt_str[point_number]->vals;
     pt_str[point_number]->vals = temp;
 }
points * clone () virtual
Reimplemented in manual_index_pts, indexed_points, and connect_points.
Definition at line 80 of file points.cpp.
References points().
Referenced by Interpolate::bilinear().
                      {
     return new points(*this);
 }
bool contains_null (std::vector< points * > points_vector) static
Definition at line 237 of file points.cpp.
Referenced by compareFiles().
{
     for(int set_num = 0; set_num < points_vector.size(); set_num++){
         if(points_vector[set_num] == NULL)
             return true;
     }
     return false;
 }
void delete_all (std::vector< points * > points_vector) static
Definition at line 227 of file points.cpp.
Referenced by compareFiles().
{
     for(int set_num = 0; set_num < points_vector.size(); set_num++){
         if(points_vector[set_num] != NULL){
             delete points_vector[set_num];
         }
     }
     points_vector.erase(points_vector.begin(), points_vector.end());
 }
int get_closest (long double * coord) virtual
Reimplemented in indexed_points, and connect_points.
Definition at line 192 of file points.cpp.
Referenced by Interpolate::bilinear().
{
     return -1;
 }
std::vector< int > get_connected_points (int point_num) virtual
Reimplemented in indexed_points, and connect_points.
Definition at line 196 of file points.cpp.
Referenced by Interpolate::getCell().
{
     std::vector<int> ret;
     return ret;
 }
int get_num_indep_vars ()
Definition at line 125 of file points.cpp.
References num_indep_vars.
Referenced by TecplotOrderedWriter::addOrderedPartition(), Interpolate::bilinear(), and TecplotOrderedWriter::writePoints().
{
     return num_indep_vars;
 }
int get_num_points ()
Definition at line 117 of file points.cpp.
References num_points.
Referenced by Interpolate::bilinear(), calcAverageValue(), partition::get_num_points(), maxPoint(), minPoint(), printPointValues(), set_num_points(), and TecplotOrderedWriter::writePoints().
{
     return num_points;
 }
int get_num_vars ()
Definition at line 121 of file points.cpp.
References num_vars.
Referenced by TecplotOrderedWriter::addOrderedPartition(), Interpolate::bilinear(), and TecplotOrderedWriter::writePoints().
{
     return num_vars;
 }
pnt get_point (int n)
Definition at line 183 of file points.cpp.
References bitmap::check_value(), pt_set, and pt_str.
Referenced by Interpolate::bilinear(), calcAverageValue(), partition::get_point(), Interpolate::getCell(), maxPoint(), minPoint(), printPointValues(), Interpolate::sortPoints(), and TecplotOrderedWriter::writePoints().
{
     if(pt_set.check_value(n))
         return *(pt_str[n]);
     else{
         pnt blank;
         return blank;
     }
 }
long double largest_val (int dim)
Definition at line 205 of file points.cpp.
References i, num_points, pt_str, and pnt::vals.
{
     long double largest = -std::numeric_limits<long double>::infinity();
     for(int i=0; i<num_points; i++){
         if(pt_str[i]->vals[dim] > largest)
             largest = pt_str[i]->vals[dim];
     }
     return largest;
 }
points & operator= (const points & p)
Definition at line 51 of file points.cpp.
References bitmap::check_value(), i, num_indep_vars, num_points, num_vars, pt_set, and pt_str.
Referenced by connect_points::operator=(), and indexed_points::operator=().
{
     if(this != &p){
         for(int i=0; i<num_points; i++){
             if(pt_set.check_value(i))
                 delete pt_str[i];
         }
         if(pt_str != NULL)
             delete[] pt_str;
         num_points = p.num_points;
         num_vars = p.num_vars;
         num_indep_vars = p.num_indep_vars;
         pt_set = p.pt_set;
         pt_str = new pnt*[num_points];
         for(int i=0; i<num_points; i++){
             if(pt_set.check_value(i)){
                 pt_str[i] = new pnt( *(p.pt_str[i]) );
             }
         }
     }
     return *this;
 }
void set_num_indep_vars (int indep_vars)
Definition at line 113 of file points.cpp.
References num_indep_vars.
Referenced by tpz_ordered::parse_data(), and tpz_fequad::parse_data().
{
     num_indep_vars = indep_vars;
 }
void set_num_points (int n)
Definition at line 84 of file points.cpp.
References bitmap::check_value(), get_num_points(), i, num_points, pt_set, pt_str, and bitmap::set_size().
Referenced by tpz_ordered::parse_data(), and tpz_fequad::parse_data().
{
     if(num_points <= 0){
         pt_str = new pnt*[n];
     }
     else{
         pnt **temp;
         temp = new pnt*[n];
         for(int i=0; i<get_num_points(); i++){
             if(pt_set.check_value(i)){
                 temp[i] = pt_str[i];
                 delete pt_str[i];
             }
         }
         delete[] pt_str;
         pt_str = temp;
     }
     this->num_points = n;
     pt_set.set_size(n);
 }
void set_num_vars (int n)
Definition at line 109 of file points.cpp.
References num_vars.
Referenced by tpz_ordered::parse_data(), and tpz_fequad::parse_data().
{
     num_vars = n;
 }
void set_point_val (int point_number, int var, long double val)
Definition at line 129 of file points.cpp.
References bitmap::check_value(), num_points, num_vars, pt_set, pt_str, bitmap::set_value(), pnt::size, and pnt::vals.
Referenced by Interpolate::bilinear(), tpz_ordered::parse_data(), and tpz_fequad::parse_data().
{
     //Check point index
     if(point_number > num_points)
         return;
     //Check if the pnt object has already been created
     if(pt_set.check_value(point_number)){
         //Check size of point object
         if(pt_str[point_number]->size != num_vars && num_vars > pt_str[point_number]->size){
             pnt *temp = new pnt;
             temp->vals = new long double[num_vars];
             temp->size = num_vars;
             for(int m=0; m<pt_str[point_number]->size; m++){
                 temp->vals[m] = pt_str[point_number]->vals[m];
             }
             delete[] pt_str[point_number]->vals;
             delete[] pt_str[point_number];
             pt_str[point_number] = temp;
         }
         if(pt_str[point_number]->size > var)
             pt_str[point_number]->vals[var] = val;
     }
     else{
         pt_str[point_number] = new pnt;
         pt_str[point_number]->vals = new long double[num_vars];
         pt_str[point_number]->size = num_vars;
         pt_set.set_value(point_number);
         if(pt_str[point_number]->size > var)
             pt_str[point_number]->vals[var] = val;
     }
 }
long double smallest_val (int dim)
Definition at line 216 of file points.cpp.
References i, num_points, pt_str, and pnt::vals.
{
     long double smallest = std::numeric_limits<long double>::infinity();
     for(int i=0; i<num_points; i++){
         if(pt_str[i]->vals[dim] < smallest)
             smallest = pt_str[i]->vals[dim];
     }
     return smallest;
 }
void sort () virtual
Reimplemented in indexed_points, and connect_points.
Definition at line 201 of file points.cpp.
                  {
     return;
 }
Member Data Documentation
int num_indep_vars protected
Definition at line 82 of file points.h.
Referenced by clear_dep_vars(), connect_points::get_closest(), indexed_points::get_closest(), get_num_indep_vars(), operator=(), points(), and set_num_indep_vars().
int num_points protected
Definition at line 80 of file points.h.
Referenced by connect_points::connect_points(), connect_points::get_closest(), indexed_points::get_closest(), get_num_points(), largest_val(), operator=(), connect_points::operator=(), points(), connect_points::set_connectivity(), set_num_points(), set_point_val(), smallest_val(), and ~points().
int num_vars protected
Definition at line 81 of file points.h.
Referenced by get_num_vars(), operator=(), points(), set_num_vars(), and set_point_val().
bitmap pt_set protected
Definition at line 89 of file points.h.
Referenced by get_point(), operator=(), points(), set_num_points(), set_point_val(), and ~points().
pnt** pt_str protected
Definition at line 85 of file points.h.
Referenced by clear_dep_vars(), connect_points::get_closest(), indexed_points::get_closest(), indexed_points::get_indexed_point(), get_point(), largest_val(), operator=(), points(), set_num_points(), set_point_val(), smallest_val(), and ~points().
The documentation for this class was generated from the following files:
points.h
points.cpp