Rocstar: LaplacianIQ Class Reference
LaplacianIQ Class Reference
#include <LaplacianIQ.hpp>
Public Member Functions
LaplacianIQ ()
Constructor sets the instructions in the queue.
virtual ~LaplacianIQ ()
Destructor must delete the objects inserted in the queue.
LaplacianIQ ()
Constructor sets the instructions in the queue.
virtual ~LaplacianIQ ()
Destructor must delete the objects inserted in the queue.
Public Member Functions inherited from InstructionQueue
InstructionQueue ()
virtual ~InstructionQueue ()
void add_target_calculator (TargetCalculator *tc, MsqError &err)
void add_preconditioner (QualityImprover *instr, MsqError &err)
adds a QualityImprover at the end of the instruction list
void remove_preconditioner (size_t index, MsqError &err)
removes a QualityImprover* from the instruction queue
void insert_preconditioner (QualityImprover *instr, size_t index, MsqError &err)
inserts a QualityImprover* into the instruction queue.
void add_quality_assessor (QualityAssessor *instr, MsqError &err)
adds a QualityAssessor to the instruction queue.
void remove_quality_assessor (size_t index, MsqError &err)
removes a QualityAssessor* from the instruction queue
void insert_quality_assessor (QualityAssessor *instr, size_t index, MsqError &err)
inserts a QualityAssessor* into the instruction queue.
void set_master_quality_improver (QualityImprover *instr, MsqError &err)
void disable_automatic_quality_assessment ()
void enable_automatic_quality_assessment ()
void disable_automatic_midnode_adjustment ()
void enable_automatic_midnode_adjustment ()
virtual void run_instructions (MeshSet &msc, MsqError &err)
This function is virtual so that it may be redefined in the wraper classes.
void clear ()
void trap_floating_point_exception (bool enable)
Generate SIGFPE whenever a floating point exception occurs.
bool trap_floating_point_exception () const
InstructionQueue ()
virtual ~InstructionQueue ()
void add_target_calculator (TargetCalculator *tc, MsqError &err)
void add_preconditioner (QualityImprover *instr, MsqError &err)
void remove_preconditioner (size_t index, MsqError &err)
void insert_preconditioner (QualityImprover *instr, size_t index, MsqError &err)
void add_quality_assessor (QualityAssessor *instr, MsqError &err)
void remove_quality_assessor (size_t index, MsqError &err)
void insert_quality_assessor (QualityAssessor *instr, size_t index, MsqError &err)
void set_master_quality_improver (QualityImprover *instr, MsqError &err)
void disable_automatic_quality_assessment ()
void enable_automatic_quality_assessment ()
void disable_automatic_midnode_adjustment ()
void enable_automatic_midnode_adjustment ()
virtual void run_instructions (MeshSet &msc, MsqError &err)
This function is virtual so that it may be redefined in the wraper classes.
void clear ()
void trap_floating_point_exception (bool enable)
Generate SIGFPE whenever a floating point exception occurs.
bool trap_floating_point_exception () const
Private Attributes
ShapeQualityMetric * inverseMeanRatio
LaplacianSmoother * lapl1
QualityAssessor * mQA
TerminationCriterion * mTerm
Detailed Description
Definition at line 60 of file includeLinks/LaplacianIQ.hpp.
Constructor & Destructor Documentation
LaplacianIQ () inline
Constructor sets the instructions in the queue.
Definition at line 70 of file includeLinks/LaplacianIQ.hpp.
References TerminationCriterion::add_criterion_type_with_int(), PatchDataUser::add_culling_method(), InstructionQueue::add_quality_assessor(), LaplacianIQ::inverseMeanRatio, LaplacianIQ::lapl1, QualityAssessor::MAXIMUM, LaplacianIQ::mQA, MSQ_CHKERR, LaplacianIQ::mTerm, PatchData::NO_BOUNDARY_VTX, TerminationCriterion::NUMBER_OF_ITERATES, InstructionQueue::set_master_quality_improver(), and QualityImprover::set_outer_termination_criterion().
                     {
          MsqError err;
          // creates a mean ratio quality metric ...
          inverseMeanRatio = new IdealWeightInverseMeanRatio(err);
          // creates the laplacian smoother  procedures
          lapl1 = new LaplacianSmoother(err);
          mQA = new QualityAssessor(inverseMeanRatio,QualityAssessor::MAXIMUM, err);
          //**************Set stopping criterion****************
          mTerm = new TerminationCriterion();
          mTerm->add_criterion_type_with_int(TerminationCriterion::NUMBER_OF_ITERATES,10,err);
             lapl1->set_outer_termination_criterion(mTerm);
             // sets a culling method on the first QualityImprover
             lapl1->add_culling_method(PatchData::NO_BOUNDARY_VTX);
             // adds 1 pass of pass1
             this->add_quality_assessor(mQA,err); MSQ_CHKERR(err);
             this->set_master_quality_improver(lapl1, err); MSQ_CHKERR(err);
             this->add_quality_assessor(mQA,err); MSQ_CHKERR(err);
       }
virtual ~LaplacianIQ () inline virtual
Destructor must delete the objects inserted in the queue.
Definition at line 95 of file includeLinks/LaplacianIQ.hpp.
References LaplacianIQ::inverseMeanRatio, LaplacianIQ::lapl1, LaplacianIQ::mQA, and LaplacianIQ::mTerm.
       {
          delete inverseMeanRatio;
          delete lapl1;
          delete mQA;
          delete mTerm;
       }
LaplacianIQ () inline
Constructor sets the instructions in the queue.
Definition at line 70 of file src/Control/Wrappers/LaplacianIQ.hpp.
References TerminationCriterion::add_criterion_type_with_int(), PatchDataUser::add_culling_method(), InstructionQueue::add_quality_assessor(), LaplacianIQ::inverseMeanRatio, LaplacianIQ::lapl1, QualityAssessor::MAXIMUM, LaplacianIQ::mQA, MSQ_CHKERR, LaplacianIQ::mTerm, PatchData::NO_BOUNDARY_VTX, TerminationCriterion::NUMBER_OF_ITERATES, InstructionQueue::set_master_quality_improver(), and QualityImprover::set_outer_termination_criterion().
                     {
          MsqError err;
          // creates a mean ratio quality metric ...
          inverseMeanRatio = new IdealWeightInverseMeanRatio(err);
          // creates the laplacian smoother  procedures
          lapl1 = new LaplacianSmoother(err);
          mQA = new QualityAssessor(inverseMeanRatio,QualityAssessor::MAXIMUM, err);
          //**************Set stopping criterion****************
          mTerm = new TerminationCriterion();
          mTerm->add_criterion_type_with_int(TerminationCriterion::NUMBER_OF_ITERATES,10,err);
             lapl1->set_outer_termination_criterion(mTerm);
             // sets a culling method on the first QualityImprover
             lapl1->add_culling_method(PatchData::NO_BOUNDARY_VTX);
             // adds 1 pass of pass1
             this->add_quality_assessor(mQA,err); MSQ_CHKERR(err);
             this->set_master_quality_improver(lapl1, err); MSQ_CHKERR(err);
             this->add_quality_assessor(mQA,err); MSQ_CHKERR(err);
       }
virtual ~LaplacianIQ () inline virtual
Destructor must delete the objects inserted in the queue.
Definition at line 95 of file src/Control/Wrappers/LaplacianIQ.hpp.
References LaplacianIQ::inverseMeanRatio, LaplacianIQ::lapl1, LaplacianIQ::mQA, and LaplacianIQ::mTerm.
       {
          delete inverseMeanRatio;
          delete lapl1;
          delete mQA;
          delete mTerm;
       }
Member Data Documentation
ShapeQualityMetric * inverseMeanRatio private
Definition at line 62 of file includeLinks/LaplacianIQ.hpp.
Referenced by LaplacianIQ::LaplacianIQ(), and LaplacianIQ::~LaplacianIQ().
LaplacianSmoother * lapl1 private
Definition at line 63 of file includeLinks/LaplacianIQ.hpp.
Referenced by LaplacianIQ::LaplacianIQ(), and LaplacianIQ::~LaplacianIQ().
QualityAssessor * mQA private
Definition at line 64 of file includeLinks/LaplacianIQ.hpp.
Referenced by LaplacianIQ::LaplacianIQ(), and LaplacianIQ::~LaplacianIQ().
TerminationCriterion * mTerm private
Definition at line 65 of file includeLinks/LaplacianIQ.hpp.
Referenced by LaplacianIQ::LaplacianIQ(), and LaplacianIQ::~LaplacianIQ().
The documentation for this class was generated from the following file:
includeLinks/LaplacianIQ.hpp