Rocstar: Halfedge_overlay Class Reference
Halfedge_overlay Class Reference
#include <HDS_overlay.h>
Public Types
typedef Halfedge_overlay Self
typedef Vertex_overlay Vertex
typedef Facet_overlay Facet
typedef Tag_true Supports_halfedge_prev
typedef Tag_true Supports_halfedge_vertex
typedef Tag_true Supports_halfedge_facet
Public Member Functions
Halfedge_overlay ()
Vertex_overlay * vertex ()
const Vertex_overlay * vertex () const
void set_opposite (Halfedge_overlay *h)
void set_next (Halfedge_overlay *h)
void set_prev (Halfedge_overlay *h)
void set_vertex (Vertex_overlay *_v)
void set_facet (Facet_overlay *_f)
Halfedge_overlay * opposite ()
const Halfedge_overlay * opposite () const
Halfedge_overlay * next ()
const Halfedge_overlay * next () const
Halfedge_overlay * prev ()
const Halfedge_overlay * prev () const
Facet_overlay * facet ()
const Facet_overlay * facet () const
bool is_border () const
Vertex_overlay * origin ()
const Vertex_overlay * origin () const
Vertex_overlay * destination ()
const Vertex_overlay * destination () const
Protected Attributes
Halfedge_overlay * nxt
char * prv
Facet_overlay * f
Vertex_overlay * v
Private Member Functions
bool is_primary () const
void set_primary ()
void unset_primary ()
Detailed Description
Definition at line 81 of file HDS_overlay.h.
Member Typedef Documentation
typedef Facet_overlay Facet
Definition at line 85 of file HDS_overlay.h.
typedef Halfedge_overlay Self
Definition at line 83 of file HDS_overlay.h.
typedef Tag_true Supports_halfedge_facet
Definition at line 89 of file HDS_overlay.h.
typedef Tag_true Supports_halfedge_prev
Definition at line 87 of file HDS_overlay.h.
typedef Tag_true Supports_halfedge_vertex
Definition at line 88 of file HDS_overlay.h.
typedef Vertex_overlay Vertex
Definition at line 84 of file HDS_overlay.h.
Constructor & Destructor Documentation
Halfedge_overlay () inline
Definition at line 98 of file HDS_overlay.h.
 : nxt(NULL), prv(NULL), f(NULL), v(NULL) {}
Member Function Documentation
Vertex_overlay* destination () inline
Definition at line 137 of file HDS_overlay.h.
References vertex().
Referenced by Overlay::convert_nat_coordinates(), RFC_Pane_overlay::evaluate_normals(), RFC_Window_overlay::evaluate_normals(), RFC_Pane_overlay::get_normal(), HDS_accessor< Tag_true >::get_normal(), Overlay_primitives::get_point(), RFC_Pane_overlay::get_tangent(), RFC_Window_overlay::get_tangent(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Overlay::project_adjacent_green_vertices(), Overlay::project_next_vertex(), Overlay::sq_length(), and Vertex_set::Vertex_set().
 { return vertex(); }
const Vertex_overlay* destination () const inline
Definition at line 138 of file HDS_overlay.h.
References vertex().
 { return vertex(); }
Facet_overlay* facet () inline
Definition at line 129 of file HDS_overlay.h.
References f.
Referenced by Overlay::convert_nat_coordinates(), HDS_accessor< Tag_true >::get_facet(), Overlay::get_nat_coor(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), Overlay::intersect_link_helper(), Overlay::number_subfaces(), and Vertex_set::Vertex_set().
 { return f; }
const Facet_overlay* facet () const inline
Definition at line 130 of file HDS_overlay.h.
References f.
 { return f;}
bool is_border () const inline
Definition at line 131 of file HDS_overlay.h.
References f.
Referenced by Overlay::count_subnodes(), RFC_Window_overlay::evaluate_normals(), RFC_Pane_overlay::get_counterpart(), HDS_accessor< Tag_true >::get_halfedge(), Overlay::get_inodes_of_face(), HDS_accessor< Tag_true >::get_next(), RFC_Pane_overlay::get_normal(), HDS_accessor< Tag_true >::get_opposite(), Overlay_primitives::get_point(), HDS_accessor< Tag_true >::get_prev(), RFC_Pane_overlay::get_primary(), Overlay_primitives::intersect(), Overlay::intersect_link(), Overlay::intersect_link_helper(), HDS_accessor< Tag_true >::is_border(), RFC_Pane_overlay::is_physical_border(), RFC_Pane_overlay::is_primary(), RFC_Window_overlay::is_same_node(), Overlay::number_a_subnode(), and HDS_accessor< Tag_true >::set_parent().
 { return f==0; }
bool is_primary () const inline private
Definition at line 140 of file HDS_overlay.h.
References prv.
Referenced by opposite(), prev(), set_prev(), set_primary(), and unset_primary().
 { return (prv-(char*)0)&1; }
Halfedge_overlay* next () inline
Definition at line 120 of file HDS_overlay.h.
References nxt.
Referenced by RFC_Pane_overlay::build_hds(), Overlay::convert_nat_coordinates(), Vertex_set::count_edges(), Overlay::count_edges(), Overlay::get_nat_coor(), HDS_accessor< Tag_true >::get_next(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Normal_set::Normal_set(), Overlay::overlay_init(), Overlay_primitives::project_onto_element(), HDS_accessor< Tag_true >::set_parent(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return nxt;}
const Halfedge_overlay* next () const inline
Definition at line 121 of file HDS_overlay.h.
References nxt.
 { return nxt;}
Halfedge_overlay* opposite () inline
Definition at line 118 of file HDS_overlay.h.
References is_primary().
Referenced by HDS_accessor< Tag_true >::get_next(), HDS_accessor< Tag_true >::get_opposite(), HDS_accessor< Tag_true >::get_prev(), origin(), HDS_accessor< Tag_true >::set_parent(), and Overlay_primitives::snap_blue_ridge_vertex().
 { return is_primary() ? this+1 : this-1; }
const Halfedge_overlay* opposite () const inline
Definition at line 119 of file HDS_overlay.h.
References is_primary().
 { return is_primary() ? this+1 : this-1; }
Vertex_overlay* origin () inline
Definition at line 135 of file HDS_overlay.h.
References opposite(), and vertex().
Referenced by Overlay::convert_nat_coordinates(), Overlay::count_subnodes(), Overlay_primitives::get_point(), RFC_Window_overlay::get_tangent(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Overlay::match_features_0(), Overlay::number_a_subnode(), Overlay::overlay_init(), Overlay::project_next_vertex(), Overlay::sq_length(), and Vertex_set::Vertex_set().
 { return opposite()->vertex(); }
const Vertex_overlay* origin () const inline
Definition at line 136 of file HDS_overlay.h.
References opposite(), and vertex().
 { return opposite()->vertex(); }
Halfedge_overlay* prev () inline
Definition at line 123 of file HDS_overlay.h.
References is_primary(), and prv.
Referenced by Overlay::get_nat_coor(), Overlay::get_next_inode_cw(), RFC_Pane_overlay::get_normal(), HDS_accessor< Tag_true >::get_prev(), Overlay::intersect_link(), Overlay::intersect_link_helper(), Overlay_primitives::project_onto_element(), set_prev(), and Overlay_primitives::snap_blue_ridge_vertex().
   { return (Halfedge_overlay*)(prv-is_primary()); }
const Halfedge_overlay* prev () const inline
Definition at line 125 of file HDS_overlay.h.
References is_primary(), and prv.
   { return (Halfedge_overlay*)(prv-is_primary()); }
void set_facet (Facet_overlay * _f) inline
Definition at line 116 of file HDS_overlay.h.
References f.
 { f = _f; }
void set_next (Halfedge_overlay * h) inline
Definition at line 112 of file HDS_overlay.h.
References nxt.
 { nxt = h; }
void set_opposite (Halfedge_overlay * h) inline
Definition at line 110 of file HDS_overlay.h.
References set_primary(), and unset_primary().
   { if ( h>this) set_primary(); else unset_primary(); }
void set_prev (Halfedge_overlay * h) inline
Definition at line 113 of file HDS_overlay.h.
References is_primary(), prev(), prv, and RFC_assertion.
   { prv = ((char*)h)+is_primary(); RFC_assertion( prev()==h); }
void set_primary () inline private
Definition at line 141 of file HDS_overlay.h.
References is_primary(), and prv.
Referenced by set_opposite().
 { if ( !is_primary()) prv+=1; }
void set_vertex (Vertex_overlay * _v) inline
Definition at line 115 of file HDS_overlay.h.
References v.
 { v = _v;}
void unset_primary () inline private
Definition at line 142 of file HDS_overlay.h.
References is_primary(), and prv.
Referenced by set_opposite().
 { if ( is_primary())  prv-=1; }
Vertex_overlay* vertex () inline
Definition at line 106 of file HDS_overlay.h.
References v.
Referenced by destination(), RFC_Pane_overlay::get_counterpart(), HDS_accessor< Tag_true >::get_hds(), HDS_accessor< Tag_true >::get_pane(), HDS_accessor< Tag_true >::get_vertex(), RFC_Window_overlay::is_feature_1(), RFC_Pane_overlay::is_physical_border(), origin(), RFC_Window_overlay::unset_strong_edge(), and Vertex_set::Vertex_set().
 { return v;}
const Vertex_overlay* vertex () const inline
Definition at line 107 of file HDS_overlay.h.
References v.
 { return v;}
Member Data Documentation
Facet_overlay* f protected
Definition at line 94 of file HDS_overlay.h.
Referenced by facet(), is_border(), and set_facet().
Halfedge_overlay* nxt protected
Definition at line 92 of file HDS_overlay.h.
Referenced by next(), and set_next().
char* prv protected
Definition at line 93 of file HDS_overlay.h.
Referenced by is_primary(), prev(), set_prev(), set_primary(), and unset_primary().
Vertex_overlay* v protected
Definition at line 95 of file HDS_overlay.h.
Referenced by set_vertex(), and vertex().
The documentation for this class was generated from the following file:
HDS_overlay.h