Rocstar: rflu_modplottingvars Module Reference
rflu_modplottingvars Module Reference
Public Member Functions
subroutine, public rflu_buildplottingvarmaps (pRegion)
subroutine rflu_computeplottingvarsvort (pRegion)
subroutine, public rflu_computeplottingvarswrapper (pRegion)
subroutine, public rflu_countplottingvars (pRegion)
subroutine, public rflu_createplottingvarmaps (pRegion)
subroutine, public rflu_createplottingvars (pRegion)
subroutine, public rflu_createplottingvarsvert (pRegion)
logical function, public rflu_decidecomputeplottingvars (pRegion)
subroutine, public rflu_destroyplottingvarmaps (pRegion)
subroutine, public rflu_destroyplottingvars (pRegion)
subroutine, public rflu_destroyplottingvarsvert (pRegion)
subroutine, public rflu_printplottingvarsinfo (pRegion)
Private Member Functions
subroutine rflu_buildplottingvarnames (pRegion)
subroutine rflu_computeplottingvarscore (pRegion)
subroutine rflu_computeplottingvarsdisc (pRegion)
subroutine rflu_computeplottingvarsgraderr (pRegion)
subroutine rflu_initplottingvars (pRegion)
subroutine rflu_initplottingvarsvert (pRegion)
subroutine rflu_nullifyplottingvarmaps (pRegion)
subroutine rflu_nullifyplottingvars (pRegion)
subroutine rflu_nullifyplottingvarsvert (pRegion)
Private Attributes
character(chrlen), parameter,
private rcsidentstring = '$RCSfile: RFLU_ModPlottingVars.F90,v $ $Revision: 1.15 $'
Detailed Description
Definition at line 39 of file RFLU_ModPlottingVars.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildplottingvarmaps (type(t_region), pointer pRegion)
Definition at line 113 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and StopWatch::stop().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregions(), rflu_postprocessregions_ens(), and rflu_postprocessregionscommon1().
subroutine rflu_buildplottingvarnames (type(t_region), pointer pRegion) private
Definition at line 201 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_countplottingvars().
subroutine rflu_computeplottingvarscore (type(t_region), pointer pRegion) private
Definition at line 350 of file RFLU_ModPlottingVars.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_moddifferentiationcells::rflu_computegradcellswrapper(), and s.
Referenced by rflu_computeplottingvarswrapper().
subroutine rflu_computeplottingvarsdisc (type(t_region), pointer pRegion) private
Definition at line 701 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_moddifferentiationcells::rflu_computegradcellswrapper(), sqrt(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflu_computeplottingvarswrapper().
subroutine rflu_computeplottingvarsgraderr (type(t_region), pointer pRegion) private
Definition at line 864 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_moddifferentiationcells::rflu_computegradcellswrapper(), rflu_modexactflow::rflu_setexactflowlinear(), rflu_modexactflow::rflu_setexactflowtrig(), x, y, and z.
Referenced by rflu_computeplottingvarswrapper().
subroutine rflu_computeplottingvarsvort (type(t_region), pointer pRegion)
Definition at line 1131 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_moddifferentiationcells::rflu_computegradcellswrapper().
Referenced by rflu_computeplottingvarswrapper().
subroutine, public rflu_computeplottingvarswrapper (type(t_region), pointer pRegion)
Definition at line 1294 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_computeplottingvarscore(), rflu_computeplottingvarsdisc(), rflu_computeplottingvarsgraderr(), rflu_computeplottingvarsvort(), rflu_modconvertcv::rflu_convertcvcons2prim(), and rflu_modconvertcv::rflu_convertcvprim2cons().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().
subroutine, public rflu_countplottingvars (type(t_region), pointer pRegion)
Definition at line 1405 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_buildplottingvarnames().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregions(), rflu_postprocessregions_ens(), and rflu_postprocessregionscommon1().
subroutine, public rflu_createplottingvarmaps (type(t_region), pointer pRegion)
Definition at line 1576 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyplottingvarmaps().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregions(), rflu_postprocessregions_ens(), and rflu_postprocessregionscommon1().
subroutine, public rflu_createplottingvars (type(t_region), pointer pRegion)
Definition at line 1657 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_initplottingvars(), and rflu_nullifyplottingvars().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().
subroutine, public rflu_createplottingvarsvert (type(t_region), pointer pRegion)
Definition at line 1742 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_initplottingvarsvert(), and rflu_nullifyplottingvarsvert().
Referenced by rflu_allocmemvertwrapper().
logical function, public rflu_decidecomputeplottingvars (type(t_region), pointer pRegion)
Definition at line 1819 of file RFLU_ModPlottingVars.F90.
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), and rflu_postprocessregionscommon2().
subroutine, public rflu_destroyplottingvarmaps (type(t_region), pointer pRegion)
Definition at line 1892 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyplottingvarmaps().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregions(), rflu_postprocessregions_ens(), and rflu_postprocessregionscommon2().
subroutine, public rflu_destroyplottingvars (type(t_region), pointer pRegion)
Definition at line 1974 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyplottingvars().
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregionscommon2().
subroutine, public rflu_destroyplottingvarsvert (type(t_region), pointer pRegion)
Definition at line 2056 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyplottingvarsvert().
Referenced by rflu_deallocmemvertwrapper().
subroutine rflu_initplottingvars (type(t_region), pointer pRegion) private
Definition at line 2128 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createplottingvars().
subroutine rflu_initplottingvarsvert (type(t_region), pointer pRegion) private
Definition at line 2205 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createplottingvarsvert().
subroutine rflu_nullifyplottingvarmaps (type(t_region), pointer pRegion) private
Definition at line 2284 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createplottingvarmaps(), and rflu_destroyplottingvarmaps().
subroutine rflu_nullifyplottingvars (type(t_region), pointer pRegion) private
Definition at line 2347 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createplottingvars(), and rflu_destroyplottingvars().
subroutine rflu_nullifyplottingvarsvert (type(t_region), pointer pRegion) private
Definition at line 2411 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createplottingvarsvert(), and rflu_destroyplottingvarsvert().
subroutine, public rflu_printplottingvarsinfo (type(t_region), pointer pRegion)
Definition at line 2475 of file RFLU_ModPlottingVars.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregions(), rflu_postprocessregions_ens(), and rflu_postprocessregionscommon1().
Member Data Documentation
character(chrlen), parameter, private rcsidentstring = '$RCSfile: RFLU_ModPlottingVars.F90,v $ $Revision: 1.15 $' private
Definition at line 63 of file RFLU_ModPlottingVars.F90.
The documentation for this module was generated from the following file:
RFLU_ModPlottingVars.F90