Rocstar: rflu_modrocstario Module Reference
rflu_modrocstario Module Reference
Public Member Functions
subroutine, public rflu_genx_buildrocinpanestrings (pRegion, paneStringVol, paneStringSurf)
subroutine, public rflu_genx_closerocinctrlfiles (global)
logical function, public rflu_genx_decidereadfile (global)
logical function, public rflu_genx_decidewritefile (global)
subroutine, public rflu_genx_getdataflow (pRegion)
subroutine, public rflu_genx_getdatagspeedssurf (pRegion)
subroutine, public rflu_genx_getdatagspeedsvol (pRegion)
subroutine, public rflu_genx_getdatainterf (pRegion)
subroutine, public rflu_genx_getdimensions (pRegion)
subroutine, public rflu_genx_getdimensionsderived (pRegion)
subroutine, public rflu_genx_getgrid (pRegion)
subroutine, public rflu_genx_openrocinctrlfiles (global)
subroutine, public rflu_genx_putdataflow (pRegion)
subroutine, public rflu_genx_putdatagspeedssurf (pRegion)
subroutine, public rflu_genx_putdatagspeedsvol (pRegion)
subroutine, public rflu_genx_putdatainterf (pRegion)
subroutine, public rflu_genx_putgrid (pRegion)
subroutine, public rflu_genx_putgridsurf (pRegion)
subroutine, public rflu_genx_putgridvol (pRegion)
subroutine, public rflu_genx_readwindow (pRegion, windowType)
subroutine, public rflu_genx_writerocinctrlfiles (global, iProc, paneStringVol, paneStringSurf)
subroutine, public rflu_genx_getglobaldata (Global)
Public Attributes
integer, parameter, public genx_window_type_surf = 1
integer, parameter, public genx_window_type_vol = 2
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRocstarIO.F90,v $ $Revision: 1.15 $'
Detailed Description
Definition at line 39 of file RFLU_ModRocstarIO.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_genx_buildrocinpanestrings (type(t_region), pointer pRegion, character(*), intent(inout) paneStringVol, character(*), intent(inout) paneStringSurf)
Definition at line 131 of file RFLU_ModRocstarIO.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflumap().
subroutine, public rflu_genx_closerocinctrlfiles (type(t_global), pointer global)
Definition at line 227 of file RFLU_ModRocstarIO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modrocstarutils::rflu_genx_buildtimestring().
logical function, public rflu_genx_decidereadfile (type(t_global), pointer global)
Definition at line 324 of file RFLU_ModRocstarIO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_readconvgridwrapper(), rflu_modreadwriteflow::rflu_readflowwrapper(), and rflu_modreadwritegrid::rflu_readgridwrapper().
logical function, public rflu_genx_decidewritefile (type(t_global), pointer global)
Definition at line 389 of file RFLU_ModRocstarIO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_moddimensions::rflu_writedimensionswrapper(), rflu_modreadwriteflow::rflu_writeflowwrapper(), rflu_modreadwritegridspeeds::rflu_writegridspeedswrapper(), and rflu_modreadwritegrid::rflu_writegridwrapper().
subroutine, public rflu_genx_getdataflow (type(t_region), pointer pRegion)
Definition at line 455 of file RFLU_ModRocstarIO.F90.
Referenced by rflu_modreadwriteflow::rflu_readflowwrapper().
subroutine, public rflu_genx_getdatagspeedssurf (type(t_region), pointer pRegion)
Definition at line 559 of file RFLU_ModRocstarIO.F90.
Referenced by rflu_modreadwritegridspeeds::rflu_readgridspeedswrapper().
subroutine, public rflu_genx_getdatagspeedsvol (type(t_region), pointer pRegion)
Definition at line 647 of file RFLU_ModRocstarIO.F90.
Referenced by rflu_modreadwritegridspeeds::rflu_readgridspeedswrapper().
subroutine, public rflu_genx_getdatainterf (type(t_region), pointer pRegion)
Definition at line 732 of file RFLU_ModRocstarIO.F90.
Referenced by rflu_initflowsolver().
subroutine, public rflu_genx_getdimensions (type(t_region), pointer pRegion)
Definition at line 899 of file RFLU_ModRocstarIO.F90.
References moderror::errorstop(), ibeg, iend, and rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_moddimensions::rflu_readdimensionswrapper().
subroutine, public rflu_genx_getdimensionsderived (type(t_region), pointer pRegion)
Definition at line 1182 of file RFLU_ModRocstarIO.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_initflowsolver(), rfluinit(), and rflupart().
subroutine, public rflu_genx_getglobaldata (type(t_global), pointer Global)
Definition at line 2809 of file RFLU_ModRocstarIO.F90.
Referenced by rflu_initflowsolver().
subroutine, public rflu_genx_getgrid (type(t_region), pointer pRegion)
Definition at line 1281 of file RFLU_ModRocstarIO.F90.
Referenced by rflu_readconvgridwrapper(), and rflu_modreadwritegrid::rflu_readgridwrapper().
subroutine, public rflu_genx_openrocinctrlfiles (type(t_global), pointer global)
Definition at line 1426 of file RFLU_ModRocstarIO.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), rflu_modrocstarutils::rflu_genx_buildtimestring(), and Attribute::status().
Referenced by rflumap().
subroutine, public rflu_genx_putdataflow (type(t_region), pointer pRegion)
Definition at line 1526 of file RFLU_ModRocstarIO.F90.
References modbuildfilenames::buildregionidstring(), Function::communicator(), rflu_modrocstarutils::rflu_genx_buildpaneid(), rflu_modrocstarutils::rflu_genx_buildtimestring(), rflu_modrocstarutils::rflu_genx_getfilestemgridvol(), and rflu_modrocstarutils::rflu_genx_getfilestemmixtvol().
Referenced by rflu_modreadwriteflow::rflu_writeflowwrapper().
subroutine, public rflu_genx_putdatagspeedssurf (type(t_region), pointer pRegion)
Definition at line 1668 of file RFLU_ModRocstarIO.F90.
References modbuildfilenames::buildregionidstring(), Function::communicator(), moderror::deregisterfunction(), moderror::registerfunction(), rflu_modrocstarutils::rflu_genx_buildpaneid(), rflu_modrocstarutils::rflu_genx_buildtimestring(), rflu_modrocstarutils::rflu_genx_getfilestemgridsurf(), and rflu_modrocstarutils::rflu_genx_getfilestemgspsurf().
Referenced by rflu_modreadwritegridspeeds::rflu_writegridspeedswrapper().
subroutine, public rflu_genx_putdatagspeedsvol (type(t_region), pointer pRegion)
Definition at line 1819 of file RFLU_ModRocstarIO.F90.
References modbuildfilenames::buildregionidstring(), Function::communicator(), moderror::deregisterfunction(), moderror::registerfunction(), rflu_modrocstarutils::rflu_genx_buildpaneid(), rflu_modrocstarutils::rflu_genx_buildtimestring(), rflu_modrocstarutils::rflu_genx_getfilestemgridvol(), and rflu_modrocstarutils::rflu_genx_getfilestemgspvol().
Referenced by rflu_modreadwritegridspeeds::rflu_writegridspeedswrapper().
subroutine, public rflu_genx_putdatainterf (type(t_region), pointer pRegion)
Definition at line 1948 of file RFLU_ModRocstarIO.F90.
References modbuildfilenames::buildregionidstring(), Function::communicator(), rflu_modrocstarutils::rflu_genx_buildpaneid(), rflu_modrocstarutils::rflu_genx_buildtimestring(), rflu_modrocstarutils::rflu_genx_getfilestemgridsurf(), and rflu_modrocstarutils::rflu_genx_getfilestemmixtsurf().
subroutine, public rflu_genx_putgrid (type(t_region), pointer pRegion)
Definition at line 2154 of file RFLU_ModRocstarIO.F90.
References rflu_genx_putgridsurf(), and rflu_genx_putgridvol().
Referenced by rflu_modreadwritegrid::rflu_writegridwrapper().
subroutine, public rflu_genx_putgridsurf (type(t_region), pointer pRegion)
Definition at line 2219 of file RFLU_ModRocstarIO.F90.
References modbuildfilenames::buildregionidstring(), Function::communicator(), moderror::deregisterfunction(), moderror::registerfunction(), rflu_modrocstarutils::rflu_genx_buildpaneid(), rflu_modrocstarutils::rflu_genx_buildtimestring(), and rflu_modrocstarutils::rflu_genx_getfilestemgridsurf().
Referenced by rflu_genx_putgrid().
subroutine, public rflu_genx_putgridvol (type(t_region), pointer pRegion)
Definition at line 2413 of file RFLU_ModRocstarIO.F90.
References modbuildfilenames::buildregionidstring(), Function::communicator(), moderror::deregisterfunction(), moderror::registerfunction(), rflu_modrocstarutils::rflu_genx_buildpaneid(), rflu_modrocstarutils::rflu_genx_buildtimestring(), and rflu_modrocstarutils::rflu_genx_getfilestemgridvol().
Referenced by rflu_genx_putgrid().
subroutine, public rflu_genx_readwindow (type(t_region), pointer pRegion, integer, intent(in) windowType)
Definition at line 2547 of file RFLU_ModRocstarIO.F90.
References modbuildfilenames::buildregionidstring(), Function::communicator(), moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modrocstarutils::rflu_genx_buildpaneid(), rflu_modrocstarutils::rflu_genx_buildtimestring(), rflu_modrocstarutils::rflu_genx_getfilestemgridsurf(), and rflu_modrocstarutils::rflu_genx_getfilestemgridvol().
Referenced by rfluinit(), and rflupart().
subroutine, public rflu_genx_writerocinctrlfiles (type(t_global), pointer global, integer, intent(in) iProc, character(*) paneStringVol, character(*) paneStringSurf)
Definition at line 2662 of file RFLU_ModRocstarIO.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_modrocstarutils::rflu_genx_buildtimestring(), rflu_modrocstarutils::rflu_genx_getfilestemsurf(), and rflu_modrocstarutils::rflu_genx_getfilestemvol().
Referenced by rflumap().
Member Data Documentation
integer, parameter, public genx_window_type_surf = 1
Definition at line 99 of file RFLU_ModRocstarIO.F90.
integer, parameter, public genx_window_type_vol = 2
Definition at line 99 of file RFLU_ModRocstarIO.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModRocstarIO.F90,v $ $Revision: 1.15 $' private
Definition at line 92 of file RFLU_ModRocstarIO.F90.
The documentation for this module was generated from the following file:
RFLU_ModRocstarIO.F90