Rocstar: rflu_modallocatememory Module Reference
rflu_modallocatememory Module Reference
Public Member Functions
subroutine, public rflu_allocatememorygspeeds (pRegion)
subroutine, public rflu_allocatememorysol (pRegion)
subroutine, public rflu_allocatememorysolcv (pRegion)
subroutine, public rflu_allocatememorysoldv (pRegion)
subroutine, public rflu_allocatememorysolgv (pRegion)
subroutine, public rflu_allocatememorysoltv (pRegion)
subroutine, public rflu_allocatememorytstep (pRegion)
subroutine, public rflu_allocatememorytstep_c (pRegion)
subroutine, public rflu_allocatememorytstep_i (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModAllocateMemory.F90,v $ $Revision: 1.16 $'
Detailed Description
Definition at line 39 of file RFLU_ModAllocateMemory.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_allocatememorygspeeds (type(t_region), pointer pRegion)
Definition at line 98 of file RFLU_ModAllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modgridspeedutils::rflu_decideneedgridspeeds().
Referenced by rflu_allocatememory(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rfluinit(), and rflupart().
subroutine, public rflu_allocatememorysol (type(t_region), pointer pRegion)
Definition at line 281 of file RFLU_ModAllocateMemory.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_allocatememorysolcv(), rflu_allocatememorysoldv(), rflu_allocatememorysolgv(), and rflu_allocatememorysoltv().
Referenced by rflu_allocatememory().
subroutine, public rflu_allocatememorysolcv (type(t_region), pointer pRegion)
Definition at line 347 of file RFLU_ModAllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_allocatememorysol(), and rflu_allocmemsolwrapper().
subroutine, public rflu_allocatememorysoldv (type(t_region), pointer pRegion)
Definition at line 429 of file RFLU_ModAllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_allocatememorysol(), and rflu_allocmemsolwrapper().
subroutine, public rflu_allocatememorysolgv (type(t_region), pointer pRegion)
Definition at line 505 of file RFLU_ModAllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_allocatememorysol(), and rflu_allocmemsolwrapper().
subroutine, public rflu_allocatememorysoltv (type(t_region), pointer pRegion)
Definition at line 585 of file RFLU_ModAllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_allocatememorysol(), and rflu_allocmemsolwrapper().
subroutine, public rflu_allocatememorytstep (type(t_region), pointer pRegion)
Definition at line 665 of file RFLU_ModAllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), ic, moderror::registerfunction(), rflu_modoles::rflu_createintegralsoles(), rflu_modoles::rflu_createstencilsweightsoles(), and rflu_decideneedbgradface().
Referenced by rflu_allocatememory().
subroutine, public rflu_allocatememorytstep_c (type(t_region), pointer pRegion)
Definition at line 1058 of file RFLU_ModAllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_allocatememory().
subroutine, public rflu_allocatememorytstep_i (type(t_region), pointer pRegion)
Definition at line 1171 of file RFLU_ModAllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_allocatememory().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModAllocateMemory.F90,v $ $Revision: 1.16 $' private
Definition at line 70 of file RFLU_ModAllocateMemory.F90.
The documentation for this module was generated from the following file:
RFLU_ModAllocateMemory.F90