Rocstar: Direction_2< R, T > Class Template Reference
Direction_2< R, T > Class Template Reference
#include <cartesian_classes.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Vector_2_base RVector_2
typedef R::Direction_2_base RDirection_2
Public Member Functions
Direction_2 ()
Direction_2 (const CGAL::Direction_2< R > &d)
Direction_2 (const RDirection_2 &d)
Direction_2 (const RVector_2 &v)
Direction_2 (const RT &x, const RT &y)
bool operator== (const CGAL::Direction_2< R > &d) const
bool operator!= (const CGAL::Direction_2< R > &d) const
bool operator>= (const CGAL::Direction_2< R > &d) const
bool operator<= (const CGAL::Direction_2< R > &d) const
bool operator> (const CGAL::Direction_2< R > &d) const
bool operator< (const CGAL::Direction_2< R > &d) const
bool counterclockwise_in_between (const CGAL::Direction_2< R > &d1, const CGAL::Direction_2< R > &d2) const
CGAL::Vector_2< R > vector () const
CGAL::Vector_2< R > to_vector () const
CGAL::Direction_2< R > transform (const CGAL::Aff_transformation_2< R > &t) const
CGAL::Direction_2< R > operator- () const
RT delta (int i) const
RT dx () const
RT dy () const
Detailed Description
template<class R, class T = typename R::Rep_tag>
class Direction_2< R, T >
Definition at line 66 of file cartesian_classes.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 87 of file Direction_2.h.
typedef R_ R
Definition at line 85 of file Direction_2.h.
typedef R::Direction_2_base RDirection_2
Definition at line 89 of file Direction_2.h.
typedef R::RT RT
Definition at line 86 of file Direction_2.h.
typedef R::Vector_2_base RVector_2
Definition at line 88 of file Direction_2.h.
Constructor & Destructor Documentation
Direction_2 () inline
Definition at line 92 of file Direction_2.h.
   {}
Direction_2 (const CGAL::Direction_2< R > & d) inline
Definition at line 95 of file Direction_2.h.
     : RDirection_2((const RDirection_2&)d)
   {}
Direction_2 (const RDirection_2< R, T > & d) inline
Definition at line 100 of file Direction_2.h.
     : RDirection_2(d)
   {}
Direction_2 (const RVector_2 & v) inline
Definition at line 105 of file Direction_2.h.
     : RDirection_2(v)
   {}
Direction_2 (const RT & x, const RT & y) inline
Definition at line 109 of file Direction_2.h.
     :  RDirection_2(x,y)
   {}
Member Function Documentation
bool counterclockwise_in_between (const CGAL::Direction_2< R > & d1, const CGAL::Direction_2< R > & d2) const inline
Definition at line 138 of file Direction_2.h.
   { return RDirection_2::counterclockwise_in_between(d1,d2); }
RT delta (int i) const inline
Definition at line 159 of file Direction_2.h.
Referenced by bc_enforce(), c3d6nm(), cst_coh(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_cocprslowterms(), peri_copgradupdate(), peri_derivedinputvalues(), peri_initsolution(), peri_printuserinput(), rflo_roedissipfirst(), rflo_roedissipsecond(), turb_lesesgmodel4(), v3d10_ale(), and v3d10_r_bar().
   { return RDirection_2::delta(i); }
RT dx () const inline
Definition at line 163 of file Direction_2.h.
Referenced by rflu_modrepair3d::angfnd(), plag_rflu_correctmixtproperties(), data_py::polint(), rflu_modrepair3d::replace(), rflo_modelliptsmoothing::rflo_elliptgridgauss2d(), rflo_modelliptsmoothing::rflo_elliptgridjac2d(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modelliptsmoothing::rflo_elliptgridsmooregion(), rflo_modelliptsmoothing::rflo_elliptgridsor2d(), rflo_exchangednoderecv(), rflo_exchangegeometrycopy(), rflo_exchangegeometryrecv(), rflo_modgridcontrolmap::rflo_gridcontrolmap2d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modbilinearpatch::rflu_blin_findclosestpoint(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationbfaces::rflu_computegradbfaces(), rflu_moddifferentiationcells::rflu_computegradcells_2d(), rflu_moddifferentiationcells::rflu_computegradcells_3d(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationcells::rflu_computegradcellsfast_2d(), rflu_moddifferentiationcells::rflu_computegradcellsfast_3d(), rflu_moddifferentiationfaces::rflu_computegradfaces(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_modweights::rflu_computestencilmoments2d1(), rflu_modweights::rflu_computestencilmoments3d1(), rflu_modgridutils::rflu_distortgrid(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_modincelltest::rflu_ict_testfacequadbilinear(), rflu_modinterpolation::rflu_interpcells2face(), rflu_modinterpolation::rflu_interpcells2facepatch(), rflu_modinterpolation::rflu_interpcells2faces(), rflu_modlimiters::rflu_limitgradcellssimple(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modrepair3d::rflu_repair3d(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxc2_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_scalarsecondpatch(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_timestepviscous(), rflu_modrepair3d::smooth(), solve_x(), rflu_modrepair3d::tessel(), and rflu_modrepair3d::tetmod().
   { return RDirection_2::dx(); }
RT dy () const inline
Definition at line 167 of file Direction_2.h.
Referenced by rflu_modrepair3d::angfnd(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_copgradupdate(), plag_rflu_correctmixtproperties(), rflu_modrepair3d::replace(), rflo_modelliptsmoothing::rflo_elliptgridgauss2d(), rflo_modelliptsmoothing::rflo_elliptgridjac2d(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modelliptsmoothing::rflo_elliptgridsmooregion(), rflo_modelliptsmoothing::rflo_elliptgridsor2d(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangegeometrycopy(), rflo_exchangegeometryrecv(), rflo_modgridcontrolmap::rflo_gridcontrolmap2d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_laplacegridsmoo(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modbilinearpatch::rflu_blin_findclosestpoint(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationbfaces::rflu_computegradbfaces(), rflu_moddifferentiationcells::rflu_computegradcells_2d(), rflu_moddifferentiationcells::rflu_computegradcells_3d(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationcells::rflu_computegradcellsfast_2d(), rflu_moddifferentiationcells::rflu_computegradcellsfast_3d(), rflu_moddifferentiationfaces::rflu_computegradfaces(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_modweights::rflu_computestencilmoments2d1(), rflu_modweights::rflu_computestencilmoments3d1(), rflu_modgridutils::rflu_distortgrid(), rflu_modextractflowdata::rflu_extractflowdatablasius(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_modincelltest::rflu_ict_testfacequadbilinear(), rflu_modinterpolation::rflu_interpcells2face(), rflu_modinterpolation::rflu_interpcells2facepatch(), rflu_modinterpolation::rflu_interpcells2faces(), rflu_modlimiters::rflu_limitgradcellssimple(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modrepair3d::rflu_repair3d(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxc2_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_scalarsecondpatch(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_timestepviscous(), rflu_modrepair3d::smooth(), rflu_modrepair3d::tessel(), and rflu_modrepair3d::tetmod().
   { return RDirection_2::dy(); }
bool operator!= (const CGAL::Direction_2< R > & d) const inline
Definition at line 118 of file Direction_2.h.
   { return !(*this == d); }
CGAL::Direction_2<R> operator- () const inline
Definition at line 155 of file Direction_2.h.
References operator-().
   { return RDirection_2::operator-(); }
bool operator< (const CGAL::Direction_2< R > & d) const inline
Definition at line 134 of file Direction_2.h.
   { return RDirection_2::operator<(d); }
bool operator<= (const CGAL::Direction_2< R > & d) const inline
Definition at line 126 of file Direction_2.h.
   { return RDirection_2::operator<=(d); }
bool operator== (const CGAL::Direction_2< R > & d) const inline
Definition at line 114 of file Direction_2.h.
References operator==().
   { return RDirection_2::operator==(d); }
bool operator> (const CGAL::Direction_2< R > & d) const inline
Definition at line 130 of file Direction_2.h.
   { return RDirection_2::operator>(d); }
bool operator>= (const CGAL::Direction_2< R > & d) const inline
Definition at line 122 of file Direction_2.h.
   { return RDirection_2::operator>=(d); }
CGAL::Vector_2<R> to_vector () const inline
Definition at line 147 of file Direction_2.h.
   { return (CGAL::Vector_2<R>)RDirection_2::to_vector(); }
CGAL::Direction_2<R> transform (const CGAL::Aff_transformation_2< R > & t) const inline
Definition at line 151 of file Direction_2.h.
   { return RDirection_2::transform(t); }
CGAL::Vector_2<R> vector () const inline
Definition at line 143 of file Direction_2.h.
   { return (CGAL::Vector_2<R>)RDirection_2::to_vector(); }
The documentation for this class was generated from the following files:
cartesian_classes.h
Direction_2.h