Rocstar: rflu_moddeallocatememory Module Reference
rflu_moddeallocatememory Module Reference
Public Member Functions
subroutine, public rflu_deallocatememorygspeeds (pRegion)
subroutine, public rflu_deallocatememorysol (pRegion)
subroutine, public rflu_deallocatememorysolcv (pRegion)
subroutine, public rflu_deallocatememorysoldv (pRegion)
subroutine, public rflu_deallocatememorysolgv (pRegion)
subroutine, public rflu_deallocatememorysoltv (pRegion)
subroutine, public rflu_deallocatememorytstep (pRegion)
subroutine, public rflu_deallocatememorytstep_c (pRegion)
subroutine, public rflu_deallocatememorytstep_i (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModDeallocateMemory.F90,v $ $Revision: 1.11 $'
Detailed Description
Definition at line 39 of file RFLU_ModDeallocateMemory.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_deallocatememorygspeeds (type(t_region), pointer pRegion)
Definition at line 98 of file RFLU_ModDeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_deallocatememory(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon2(), rfluinit(), and rflupart().
subroutine, public rflu_deallocatememorysol (type(t_region), pointer pRegion)
Definition at line 235 of file RFLU_ModDeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_deallocatememorysolcv(), rflu_deallocatememorysoldv(), rflu_deallocatememorysolgv(), and rflu_deallocatememorysoltv().
Referenced by rflu_deallocatememory().
subroutine, public rflu_deallocatememorysolcv (type(t_region), pointer pRegion)
Definition at line 302 of file RFLU_ModDeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_deallocatememorysol(), and rflu_deallocmemsolwrapper().
subroutine, public rflu_deallocatememorysoldv (type(t_region), pointer pRegion)
Definition at line 384 of file RFLU_ModDeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_deallocatememorysol(), and rflu_deallocmemsolwrapper().
subroutine, public rflu_deallocatememorysolgv (type(t_region), pointer pRegion)
Definition at line 453 of file RFLU_ModDeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_deallocatememorysol(), and rflu_deallocmemsolwrapper().
subroutine, public rflu_deallocatememorysoltv (type(t_region), pointer pRegion)
Definition at line 520 of file RFLU_ModDeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_deallocatememorysol(), and rflu_deallocmemsolwrapper().
subroutine, public rflu_deallocatememorytstep (type(t_region), pointer pRegion)
Definition at line 597 of file RFLU_ModDeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_decideneedbgradface(), and rflu_modoles::rflu_destroystencilsweightsoles().
Referenced by rflu_deallocatememory().
subroutine, public rflu_deallocatememorytstep_c (type(t_region), pointer pRegion)
Definition at line 904 of file RFLU_ModDeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_deallocatememory().
subroutine, public rflu_deallocatememorytstep_i (type(t_region), pointer pRegion)
Definition at line 996 of file RFLU_ModDeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_deallocatememory().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModDeallocateMemory.F90,v $ $Revision: 1.11 $' private
Definition at line 70 of file RFLU_ModDeallocateMemory.F90.
The documentation for this module was generated from the following file:
RFLU_ModDeallocateMemory.F90