Rocstar: TetElement Class Reference
TetElement Class Reference
#include <TetElement.hpp>
Public Member Functions
TetElement ()
TetElement (Node **thenodes)
~TetElement ()
virtual int getNumNodes () const
virtual int getNumFaces () const
Public Member Functions inherited from Element
Element (Type type)
~Element ()
int getID () const
void setID (int theID)
Node ** getNodes ()
Face ** getFaces ()
Type getElementType () const
boolean isCohesive () const
int getMaterialType () const
void setMaterialType (int mtype)
virtual void setFromNodes (Node **thenodes)
void replaceNode (Node *node, Node *new_node)
void replaceFace (Face *face, Face *new_face)
virtual void replaceFaceNode (Node *node, Node *new_node, Face *face)
Protected Member Functions
virtual void setFaceFromNodes (int num, Node **nodes)
virtual void setFromMyNodes ()
virtual double getMinEdgeLength ()
Protected Member Functions inherited from Element
void setFace (int num, Face *face)
Additional Inherited Members
Public Types inherited from Element
enum Type {
e_tet, e_hex, e_tri_cohesive, e_quad_cohesive,
e_MAX_TYPE
}
enum fType { e_tri, e_quad, e_MAX_FACE_TYPE }
enum MaterialType { e_unset_material = -1 }
Static Public Member Functions inherited from Element
static Element * create (int id, Type type)
static void setMesh (Mesh *emesh)
Protected Attributes inherited from Element
Type d_eType
int d_ID
Node ** d_nodes
Face ** d_faces
int d_materialType
Static Protected Attributes inherited from Element
static Mesh * s_mesh = 0
Detailed Description
Definition at line 9 of file TetElement.hpp.
Constructor & Destructor Documentation
TetElement ()
Definition at line 7 of file TetElement.cpp.
References Element::d_faces, Element::d_nodes, getNumFaces(), and getNumNodes().
                        :
 Element( e_tet ){
   d_nodes = new Node*[getNumNodes()];
   d_faces = new Face*[getNumFaces()];
 }
TetElement (Node ** thenodes)
Definition at line 16 of file TetElement.cpp.
References Element::d_faces, Element::d_nodes, getNumFaces(), getNumNodes(), and Element::setFromNodes().
                                        :
 Element( e_tet ){
   d_nodes = new Node*[getNumNodes()];
   d_faces = new Face*[getNumFaces()];
   setFromNodes( thenodes );
 }
~TetElement ()
Definition at line 25 of file TetElement.cpp.
References Element::d_faces, Element::d_nodes, getNumFaces(), getNumNodes(), i, Node::removeElement(), and Face::removeElement().
{
   int numn = getNumNodes();
   int i;
   for( i = 0; i < numn; i++ ){
     d_nodes[i]->removeElement( this );
   }
   int numf = getNumFaces();
   for( i = 0; i < numf; i++ ){
     d_faces[i]->removeElement( this );
   }
 }
Member Function Documentation
double getMinEdgeLength () protected virtual
Reimplemented from Element.
Definition at line 84 of file TetElement.cpp.
References Element::d_nodes, MVec::distance_between(), Node::getPosition(), and i.
{
    double minEdge = 1E+25;
    double currentLength;
    MVec pos[4];
    //there are six edge lengths to check:
    //0 -> 1, 0 -> 2, 0 -> 3
    //1 -> 2, 1 -> 3, 2 -> 3
    // for nodes numbered 0, 1, 2, 3
    for (int i=0; i<4; i++) {
         pos[i] = d_nodes[i]->getPosition();
    }
    currentLength = pos[0].distance_between(pos[1]);
    if (currentLength < minEdge) minEdge = currentLength;
    currentLength = pos[0].distance_between(pos[2]);
    if (currentLength < minEdge) minEdge = currentLength;
    currentLength = pos[0].distance_between(pos[3]);
    if (currentLength < minEdge) minEdge = currentLength;
    currentLength = pos[1].distance_between(pos[2]);
    if (currentLength < minEdge) minEdge = currentLength;
    currentLength = pos[1].distance_between(pos[2]);
    if (currentLength < minEdge) minEdge = currentLength;
    currentLength = pos[2].distance_between(pos[3]);
    if (currentLength < minEdge) minEdge = currentLength;
    assert(minEdge < 1E+24);
    return(minEdge);
 }
int getNumFaces () const virtual
Implements Element.
Definition at line 41 of file TetElement.cpp.
Referenced by TetElement(), and ~TetElement().
 { return 4; }
int getNumNodes () const virtual
Implements Element.
Definition at line 38 of file TetElement.cpp.
Referenced by TetElement(), and ~TetElement().
 { return 4; }
void setFaceFromNodes (int num, Node ** nodes) protected virtual
Implements Element.
Definition at line 45 of file TetElement.cpp.
References Mesh::addFace(), Element::s_mesh, Element::setFace(), and Node::sharedFace().
Referenced by setFromMyNodes().
{
   // find if face exist (if not creates it)
   Face* face = nodes[0]->sharedFace( nodes[1], nodes[2] );
   if( !face ){
     face = new TriFace( nodes );
     s_mesh->addFace( face );
   }
   setFace( num, face );
 }
void setFromMyNodes () protected virtual
Implements Element.
Definition at line 57 of file TetElement.cpp.
References Element::d_nodes, and setFaceFromNodes().
{
   // !!! check ordering
   Node *nodes[3];
   nodes[0] = d_nodes[1];
   nodes[1] = d_nodes[3];
   nodes[2] = d_nodes[2];
   setFaceFromNodes( 0, nodes );
   nodes[0] = d_nodes[2];
   nodes[1] = d_nodes[3];
   nodes[2] = d_nodes[0];
   setFaceFromNodes( 1, nodes );
   nodes[0] = d_nodes[0];
   nodes[1] = d_nodes[3];
   nodes[2] = d_nodes[1];
   setFaceFromNodes( 2, nodes );
   nodes[0] = d_nodes[0];
   nodes[1] = d_nodes[1];
   nodes[2] = d_nodes[2];
   setFaceFromNodes( 3, nodes );
 }
The documentation for this class was generated from the following files:
TetElement.hpp
TetElement.cpp