Rocstar: m_rocburn_1d_zn Module Reference
m_rocburn_1d_zn Module Reference
Public Member Functions
subroutine check_alloc (ierr)
subroutine initialize_0d (G_ZN, comm, Indir, nxmax, To_read)
subroutine initialize_1d (G_ZN, bflag, P_mks, To, rhoc_mks, p_coor, rb_mks, Toa, fr, Tn, Tflame)
subroutine get_film_coeff_1d (G_ZN, p_coor, Ts, T_euler, P, qc, qcPrime)
subroutine get_time_step_1d (G_ZN, rb, Toa, dt_max)
subroutine get_burning_rate_1d (G_ZN, delt, P_mks, To, Tn, qc_mks, qc_old_mks, qr_mks, qr_old_mks, rhoc_mks, Toa, rb_mks, fr, bflag, Tnp1, Tflame)
subroutine finalize_0d (G_ZN)
Detailed Description
Definition at line 23 of file Rocburn_1D_ZN.f90.
Member Function/Subroutine Documentation
subroutine check_alloc (integer, intent(in) ierr)
Definition at line 66 of file Rocburn_1D_ZN.f90.
References Aff_transformation_repS2< FT >::print().
subroutine finalize_0d (type (g_burn_1d), pointer G_ZN)
Definition at line 371 of file Rocburn_1D_ZN.f90.
subroutine get_burning_rate_1d (type (g_burn_1d), pointer G_ZN, real(dbl), intent(in) delt, real(dbl), intent(in) P_mks, real(dbl), intent(in) To, real(dbl), dimension(:), intent(in) Tn, real(dbl), intent(in) qc_mks, real(dbl), intent(in) qc_old_mks, real(dbl), intent(in) qr_mks, real(dbl), intent(in) qr_old_mks, real(dbl), intent(in) rhoc_mks, real(dbl), intent(inout) Toa, real(dbl), intent(inout) rb_mks, real(dbl), intent(inout) fr, integer, intent(inout) bflag, real(dbl), dimension(:), intent(out) Tnp1, real(dbl), intent(out) Tflame)
Definition at line 259 of file Rocburn_1D_ZN.f90.
References StopWatch::stop(), zn_calc_burning_rate(), and zn_sswsb().
subroutine get_film_coeff_1d (type (g_burn_1d), pointer G_ZN, real(dbl), dimension(3), intent(in) p_coor, real(dbl), intent(in) Ts, real(dbl), intent(in) T_euler, real(dbl), intent(in) P, real(dbl), intent(out) qc, real(dbl), intent(out) qcPrime)
Definition at line 205 of file Rocburn_1D_ZN.f90.
Referenced by m_init_1dmodules::rocburn_init_funcs_py(), m_init_1dmodules::rocburn_init_funcs_zn(), and m_rocburn_2d::update().
subroutine get_time_step_1d (type (g_burn_1d), pointer G_ZN, real(dbl), intent(in) rb, real(dbl), intent(in) Toa, real(dbl), intent(out) dt_max)
Definition at line 229 of file Rocburn_1D_ZN.f90.
References min().
subroutine initialize_0d (type(g_burn_1d), pointer G_ZN, integer, intent(in) comm, character(*), intent(in) Indir, integer, intent(out) nxmax, real(dbl), intent(out) To_read)
Definition at line 74 of file Rocburn_1D_ZN.f90.
References m_rocburn_2d::check_alloc(), zn_gen_grid(), and zn_input_0d().
subroutine initialize_1d (type(g_burn_1d), pointer G_ZN, integer, intent(inout) bflag, real(dbl), intent(in) P_mks, real(dbl), intent(in) To, real(dbl), intent(in) rhoc_mks, real(dbl), dimension(3), intent(in) p_coor, real(dbl), intent(out) rb_mks, real(dbl), intent(out) Toa, real(dbl), intent(out) fr, real(dbl), dimension(:), intent(out) Tn, real(dbl), intent(out) Tflame)
Definition at line 141 of file Rocburn_1D_ZN.f90.
References zn_sswsb().
The documentation for this module was generated from the following file:
Rocburn_1D_ZN.f90