Rocstar: Remesher_Simmetrix Class Reference
Remesher_Simmetrix Class Reference
#include <Remesher_Simmetrix.h>
Public Member Functions
Remesher_Simmetrix (const char *logfile=NULL)
Initialize the remesher.
virtual ~Remesher_Simmetrix ()
Finalize the remesher.
virtual void remesh_serial (Manifold *wm, COM::Attribute *mesh_out, double lave, double fangle)
void set_global_mesh_size (int type, double val)
void set_fangle (double fangle)
void set_short_ratio (double r)
Protected Member Functions
void * window_to_simmesh (const COM::Window *outwin)
void simmesh_to_window (void *mesh, COM::Window *outwin)
Protected Attributes
int _size_type
double _size_val
double _fangle
double _shrtRatio
Static Protected Attributes
static int instances = 0
This file provides a wrapper to invoke GeomSim from Simmetrix to remesh a surface mesh.
Additional Inherited Members
Private Member Functions inherited from Remesher_base
virtual ~Remesher_base ()
Detailed Description
Definition at line 33 of file Remesher_Simmetrix.h.
Constructor & Destructor Documentation
Remesher_Simmetrix (const char * logfile = NULL) explicit
Initialize the remesher.
In particular, initialize MeshSim.
Definition at line 39 of file Remesher_Simmetrix.C.
References instances.
   : _size_type(0), _size_val(0.), _fangle(0), _shrtRatio(5) {
   if ( logfile) Sim_logOn( logfile);
   if ( instances == 0) {
     MS_init(); // start up MeshSim
     Sim_registerKey("cen002 surface 20060331 0 mTcaTqnWjLIUId26P29r3w=="); // for surface
     Sim_registerKey("cen002 discrete 20060331 0 8VnUzbSAnldsPdfPbpWFVw=="); // for discrete
     SimDiscrete_start(0);
   }
   ++instances;
 }
~Remesher_Simmetrix () virtual
Finalize the remesher.
In particular, finalize MeshSim.
Definition at line 56 of file Remesher_Simmetrix.C.
References instances.
{
   --instances;
   if ( instances==0) {
     SimDiscrete_stop(0);
     MS_exit();
     Sim_logOff();
     Sim_unregisterAllKeys();
   }
 }
Member Function Documentation
void remesh_serial (Manifold * wm, COM::Attribute * mesh_out, double lave, double fangle) virtual
Implements Remesher_base.
Definition at line 150 of file Remesher_Simmetrix.C.
References _fangle, _shrtRatio, _size_type, _size_val, set_fangle(), set_global_mesh_size(), set_short_ratio(), simmesh_to_window(), and window_to_simmesh().
{
   std::cout << "Setting average edge length to " << lave << std::endl;
   std::cout << "Setting feature angle to " << fangle << std::endl;
   // Set options
   set_global_mesh_size( 1, lave);
   set_fangle( fangle);
   set_short_ratio( 5);
   COM::Window *outwin = mesh_out->window();
   // Serialize input mesh and put into output mesh
   wm->serialize_window( outwin);
   pMesh mesh = (pMesh)window_to_simmesh( outwin);
   pDiscreteModel model = DM_createFromMesh( mesh, true);
   if ( _fangle>0) {
     // Perform feature detection
     double angleRadian = _fangle/180*3.14159265358979;
     DM_findEdgesByFaceNormals( model, angleRadian);
     DM_eliminateDanglingEdges( model);
   }
   DM_completeTopology( model);
   // Obtain a new copy of the mesh for alteration
   pMesh newMesh = DM_getMeshCopy( model);
   pACase newCase = MS_newMeshCase(model);
   // set the desired mesh size
   if ( _size_type != 0)
   {
      pModelMember mdomain = GM_domain(model);
      MS_setMeshSize(newCase,mdomain, _size_type, _size_val,0);
   }
   // Modify the surface mesh so that it conforms to the new size
   DM_modifySurfaceMesh( newMesh, newCase ,0,0,0,0, /* swap, split, min, and max angles*/
                         0, 0, /* Collapes face and edge angles */
                         0, _shrtRatio, 0);
   simmesh_to_window( newMesh, outwin);
   M_release(newMesh);
   GM_release((SGModel *) model);
 }
void set_fangle (double fangle) inline
Definition at line 53 of file Remesher_Simmetrix.h.
References _fangle.
Referenced by remesh_serial().
 { _fangle = fangle; }
void set_global_mesh_size (int type, double val) inline
Definition at line 48 of file Remesher_Simmetrix.h.
References _size_type, and _size_val.
Referenced by remesh_serial().
   { _size_type = type; _size_val = val; }
void set_short_ratio (double r) inline
Definition at line 57 of file Remesher_Simmetrix.h.
References _shrtRatio.
Referenced by remesh_serial().
 { _shrtRatio = r; }
void simmesh_to_window (void * mesh, COM::Window * outwin) protected
Definition at line 102 of file Remesher_Simmetrix.C.
References COM_assertion_msg, COM_NC, face, i, and j.
Referenced by remesh_serial().
{
   pMesh mesh = (pMesh)m;
   // Obtain the panes
   std::vector<COM::Pane*> panes;
   outwin->panes(panes);
   COM_assertion_msg( panes.size() == 1, "Window must be a serial one");
   int pid = panes[0]->id();
   // Obtain coordinates
   COM::Attribute *coor = panes[0]->attribute( COM::COM_NC);
   outwin->set_size( coor->name(), pid, M_numVertices(mesh));
   double *coors;
   outwin->resize_array( coor, (void**)&coors);
   VIter vIter = M_vertexIter(mesh);
   pVertex vertex;
   for (int i=0; (vertex=VIter_next(vIter)); ++i) {
     EN_setID((pEntity)vertex, i+1);
     V_coord(vertex, &coors[3*i]);
   }
   VIter_delete(vIter);
   // Obtain connectivity
   std::vector<COM::Connectivity*> elems;
   panes[0]->elements( elems);
   outwin->set_size( elems[0]->name(), pid, M_numFaces(mesh));
   int *tris;
   outwin->resize_array( elems[0], (void**)&tris);
   FIter fIter = M_faceIter(mesh);
   pFace face;
   for (int i=0; (face = FIter_next(fIter)); ++i){
     pPList fVerts = F_vertices(face,1);
     int j;
     for(j=0; j < 3; j++){
       vertex = (pVertex)PList_item( fVerts, j);
       tris[3*i+j] = EN_id((pEntity)vertex);
     }
   }
   FIter_delete(fIter);
 }
void * window_to_simmesh (const COM::Window * outwin) protected
Definition at line 68 of file Remesher_Simmetrix.C.
References COM_assertion_msg, and i.
Referenced by remesh_serial().
{
   // Obtain the list of panes
   std::vector<const COM::Pane*> panes;
   outwin->panes(panes);
   COM_assertion_msg( panes.size() == 1, "Window must be a serial one");
   // Get the sizes
   int numVerts = panes[0]->size_of_nodes();
   int numElems = panes[0]->size_of_elements();
   // Get the pointers to
   std::vector<const COM::Connectivity*> elems;
   panes[0]->elements( elems);
   COM_assertion_msg( elems.size() == 1 &&
                      elems[0]->element_type()==COM::Connectivity::TRI3,
                      "Window must be a serial one");
   pMesh mesh = M_new(0,0);
   // Initialize pMesh.
   std::vector<int> elemTypes(numElems, 5 /* Triangles */);
   /* offset nodal IDs to start from 0 */
   int *tris = const_cast<int*>(elems[0]->pointer());
   std::vector<int> tris_vec( numElems*3,0);
   for ( int i=0; i<numElems*3; ++i)
     tris_vec[i] = tris[i]-1;
   double *coors = const_cast<double*>(panes[0]->coordinates());
   M_importFromData( mesh, numVerts, coors, numElems, &elemTypes[0],
                     &tris_vec[0], NULL, NULL);
   return mesh;
 }
Member Data Documentation
double _fangle protected
Definition at line 70 of file Remesher_Simmetrix.h.
Referenced by remesh_serial(), and set_fangle().
double _shrtRatio protected
Definition at line 71 of file Remesher_Simmetrix.h.
Referenced by remesh_serial(), and set_short_ratio().
int _size_type protected
Definition at line 68 of file Remesher_Simmetrix.h.
Referenced by remesh_serial(), and set_global_mesh_size().
double _size_val protected
Definition at line 69 of file Remesher_Simmetrix.h.
Referenced by remesh_serial(), and set_global_mesh_size().
PROP_BEGIN_NAMESPACE int instances = 0 static protected
This file provides a wrapper to invoke GeomSim from Simmetrix to remesh a surface mesh.
Definition at line 67 of file Remesher_Simmetrix.h.
Referenced by Remesher_Simmetrix(), and ~Remesher_Simmetrix().
The documentation for this class was generated from the following files:
Remesher_Simmetrix.h
Remesher_Simmetrix.C