Rocstar: VectorS3< FT > Class Template Reference
VectorS3< FT > Class Template Reference
#include <simple_cartesian_classes.h>
Public Types
typedef VectorS3< FT > Self
typedef DirectionS3< FT > Direction
typedef Aff_transformationS3< FT > Aff_transformation
Public Member Functions
VectorS3 ()
VectorS3 (const Null_vector &)
VectorS3 (const FT &x, const FT &y, const FT &z)
VectorS3 (const FT &x, const FT &y, const FT &z, const FT &w)
bool operator== (const VectorS3< FT > &p) const
bool operator!= (const VectorS3< FT > &p) const
bool operator== (const Null_vector &) const
bool operator!= (const Null_vector &) const
const FT & x () const
const FT & y () const
const FT & z () const
const FT & cartesian (int i) const
const FT & operator[] (int i) const
const FT & hx () const
const FT & hy () const
const FT & hz () const
FT hw () const
FT homogeneous (int i) const
int dimension () const
VectorS3< FT > operator+ (const VectorS3< FT > &w) const
VectorS3< FT > operator- (const VectorS3< FT > &w) const
VectorS3< FT > operator- () const
FT operator* (const VectorS3< FT > &w) const
VectorS3< FT > operator/ (const FT &c) const
DirectionS3< FT > direction () const
VectorS3< FT > transform (const Aff_transformationS3< FT > &) const
VectorS3 (const PointS3< FT > &p)
VectorS3 (const DirectionS3< FT > &p)
VectorS3 ()
VectorS3 (const Null_vector &)
VectorS3 (const FT &hx, const FT &hy, const FT &hz, const FT &hw)
VectorS3 (const FT &x, const FT &y, const FT &z)
~VectorS3 ()
Self & operator= (const Self &v)
bool operator== (const Self &v) const
bool operator== (const Null_vector &) const
bool operator!= (const Null_vector &) const
int id () const
FT hx () const
FT hy () const
FT hz () const
FT hw () const
FT homogeneous (int i) const
const FT & x () const
const FT & y () const
const FT & z () const
FT & x ()
FT & y ()
FT & z ()
const FT & cartesian (int i) const
FT & cartesian (int i)
FT & operator[] (int i)
const FT & operator[] (int i) const
int dimension () const
Self operator+ (const Self &v) const
Self operator- (const Self &v) const
Self operator- (const Null_vector &) const
Self operator- () const
Self & operator+= (const Self &v)
Self & operator-= (const Self &v)
FT operator* (const Self &v) const
Self operator/ (const FT &c) const
Self & operator*= (const FT c)
Self & operator/= (const FT c)
Self & operator*= (const Self &v)
Self & operator/= (const Self &v)
Self transform (const Aff_transformation &t) const
const Direction & direction () const
FT squared_norm () const
Public Attributes
FT e0
FT e1
FT e2
Protected Attributes
FT _x
FT _y
FT _z
Friends
class DirectionS3< FT >
Detailed Description
template<class FT>
class VectorS3< FT >
Definition at line 73 of file simple_cartesian_classes.h.
Member Typedef Documentation
typedef Aff_transformationS3<FT> Aff_transformation
Definition at line 35 of file include/CGAL/SimpleCartesian/VectorS3.h.
typedef DirectionS3<FT> Direction
Definition at line 34 of file include/CGAL/SimpleCartesian/VectorS3.h.
typedef VectorS3<FT> Self
Definition at line 33 of file include/CGAL/SimpleCartesian/VectorS3.h.
Constructor & Destructor Documentation
VectorS3 () inline
Definition at line 69 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
 {}
VectorS3 (const Null_vector &) inline
Definition at line 70 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
                    : e0(FT(0)), e1(FT(0)), e2(FT(0)) {}
VectorS3 (const FT & x, const FT & y, const FT & z) inline
Definition at line 72 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
                     : e0(x), e1(y), e2(z) {}
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE VectorS3 (const FT & x, const FT & y, const FT & z, const FT & w)
Definition at line 124 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References DirectionS3< FT >::e0, DirectionS3< FT >::e1, DirectionS3< FT >::e2, x, y, and z.
 {
   if (w != FT(1))
   {
     e0 = x/w;
     e1 = y/w;
     e2 = z/w;
   }
   else
   {
     e0 = x;
     e1 = y;
     e2 = z;
   }
 }
VectorS3 (const PointS3< FT > & p) inline
Definition at line 141 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References DirectionS3< FT >::e0, PointS3< FT >::e0, DirectionS3< FT >::e1, PointS3< FT >::e1, DirectionS3< FT >::e2, and PointS3< FT >::e2.
 {
   e0 = p.e0;
   e1 = p.e1;
   e2 = p.e2;
 }
VectorS3 (const DirectionS3< FT > & p) inline
Definition at line 149 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References DirectionS3< FT >::e0, DirectionS3< FT >::e1, and DirectionS3< FT >::e2.
 {
   e0 = d.e0;
   e1 = d.e1;
   e2 = d.e2;
 }
VectorS3 () inline
Definition at line 37 of file include/CGAL/SimpleCartesian/VectorS3.h.
 {}
VectorS3 (const Null_vector &) inline
Definition at line 39 of file include/CGAL/SimpleCartesian/VectorS3.h.
 : _x(0), _y(0), _z(0) {}
VectorS3 (const FT & hx, const FT & hy, const FT & hz, const FT & hw) inline
Definition at line 40 of file include/CGAL/SimpleCartesian/VectorS3.h.
     : _x(hx/hw), _y(hy/hw), _z(hz/hw) {}
VectorS3 (const FT & x, const FT & y, const FT & z) inline
Definition at line 42 of file include/CGAL/SimpleCartesian/VectorS3.h.
 : _x(x), _y(y), _z(z) {}
~VectorS3 () inline
Definition at line 43 of file include/CGAL/SimpleCartesian/VectorS3.h.
 {}
Member Function Documentation
const FT& cartesian (int i) const inline
Definition at line 72 of file include/CGAL/SimpleCartesian/VectorS3.h.
References CGAL_kernel_precondition, VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
{
     CGAL_kernel_precondition( i >= 0 && i <= 2 );
     return (i==0) ? x() :
            (i==1) ? y() : z() ;
   }
FT& cartesian (int i) inline
Definition at line 78 of file include/CGAL/SimpleCartesian/VectorS3.h.
References CGAL_kernel_precondition, VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
{
     CGAL_kernel_precondition( i >= 0 && i <= 2 );
     return (i==0) ? x() :
            (i==1) ? y() : z() ;
   }
const FT & cartesian (int i) const inline
Definition at line 200 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References CGAL_kernel_precondition, x, y, and z.
Referenced by VectorS3< FT >::homogeneous(), and VectorS3< FT >::operator[]().
 {
   CGAL_kernel_precondition( (i>=0) && (i<3) );
   return (i==0) ? x() :
          (i==1) ? y() : z();
 }
int dimension () const inline
Definition at line 87 of file include/CGAL/SimpleCartesian/VectorS3.h.
 { return 3; }
int dimension () const inline
Definition at line 216 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
 { return 3; }
DirectionS3< FT > direction () const inline
Definition at line 295 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
 { return DirectionS3<FT>(*this); }
const Direction& direction () const inline
Definition at line 123 of file include/CGAL/SimpleCartesian/VectorS3.h.
     { return reinterpret_cast<const Direction&>(*this); }
FT homogeneous (int i) const inline
Definition at line 63 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::cartesian().
 { return (i == 3) ? FT(1) : cartesian(i); }
FT homogeneous (int i) const
Definition at line 244 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
 { return (i==3) ? FT(1) : cartesian(i); }
FT hw () const inline
Definition at line 62 of file include/CGAL/SimpleCartesian/VectorS3.h.
 { return FT(1); }
FT hw () const
Definition at line 239 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
 { return FT(1); }
FT hx () const inline
Definition at line 59 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x.
 { return _x; }
const FT & hx () const inline
Definition at line 222 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References DirectionS3< FT >::e0.
 { return e0; }
FT hy () const inline
Definition at line 60 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_y.
 { return _y; }
const FT & hy () const inline
Definition at line 228 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References DirectionS3< FT >::e1.
 { return e1; }
FT hz () const inline
Definition at line 61 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_z.
 { return _z; }
const FT & hz () const inline
Definition at line 234 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References DirectionS3< FT >::e2.
 { return e2; }
int id () const inline
Definition at line 57 of file include/CGAL/SimpleCartesian/VectorS3.h.
 { return (int)this; }
bool operator!= (const Null_vector &) const inline
Definition at line 54 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { return _x!=FT(0) || _y!=FT(0) || _z!=FT(0); }
bool operator!= (const VectorS3< FT > & p) const inline
Definition at line 164 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References v.
 { return !(*this == v); }
bool operator!= (const Null_vector & v) const inline
Definition at line 176 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References v.
 { return !(*this == v); }
FT operator* (const VectorS3< FT > & w) const inline
Definition at line 268 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References x, VectorS3< FT >::x(), y, VectorS3< FT >::y(), z, and VectorS3< FT >::z().
 { return x() * w.x() + y() * w.y() + z() * w.z() ; }
FT operator* (const Self & v) const inline
Definition at line 105 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { return _x * v._x + _y * v._y + _z*v._z; }
Self& operator*= (const FT c) inline
Definition at line 109 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { _x *= c; _y *=c; _z *= c; return *this; }
Self& operator*= (const Self & v) inline
Definition at line 114 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { _x *= v._x; _y *=v._y; _z *=v._z; return *this; }
Self operator+ (const Self & v) const inline
Definition at line 89 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { return Self(_x + v._x, _y + v._y, _z + v._z); }
VectorS3< FT > operator+ (const VectorS3< FT > & w) const inline
Definition at line 250 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References x, VectorS3< FT >::x(), y, VectorS3< FT >::y(), z, and VectorS3< FT >::z().
 { return VectorS3<FT>(x() + w.x(), y() + w.y(), z() + w.z()) ; }
Self& operator+= (const Self & v) inline
Definition at line 96 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
{
     _x += v._x; _y+=v._y; _z+=v._z;
     return *this;
   }
Self operator- (const Self & v) const inline
Definition at line 91 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { return Self(_x - v._x, _y - v._y, _z - v._z); }
Self operator- (const Null_vector &) const inline
Definition at line 93 of file include/CGAL/SimpleCartesian/VectorS3.h.
 { return *this; }
Self operator- () const inline
Definition at line 94 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
 { return Self(-_x, -_y, -_z); }
VectorS3< FT > operator- (const VectorS3< FT > & w) const inline
Definition at line 256 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References x, VectorS3< FT >::x(), y, VectorS3< FT >::y(), z, and VectorS3< FT >::z().
 { return VectorS3<FT>(x() - w.x(), y() - w.y(), z() - w.z()) ; }
VectorS3< FT > operator- () const inline
Definition at line 262 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References x, y, and z.
 { return VectorS3<FT>(-x(), -y(), -z()) ; }
Self& operator-= (const Self & v) inline
Definition at line 100 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
{
     _x -= v._x; _y-=v._y; _z-=v._z;
     return *this;
   }
VectorS3< FT > operator/ (const FT & c) const inline
Definition at line 280 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References x, y, and z.
 { return VectorS3<FT>( x()/c, y()/c, z()/c) ; }
Self operator/ (const FT & c) const inline
Definition at line 107 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
 { return Self( _x/c, _y/c, _z/c); }
Self& operator/= (const FT c) inline
Definition at line 111 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { _x /= c; _y /=c; _z /= c; return *this; }
Self& operator/= (const Self & v) inline
Definition at line 116 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { _x /= v._x; _y /=v._y; _z /=v._z; return *this; }
Self& operator= (const Self & v) inline
Definition at line 45 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
{
     _x=v._x; _y=v._y; _z=v._z;
     return *this;
   }
bool operator== (const Self & v) const inline
Definition at line 50 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { return _x==v._x && _y==v._y && _z==v._z; }
bool operator== (const Null_vector &) const inline
Definition at line 52 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
     { return _x==FT(0) && _y==FT(0) && _z==FT(0); }
bool operator== (const VectorS3< FT > & p) const
Definition at line 158 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References x, VectorS3< FT >::x(), y, VectorS3< FT >::y(), z, and VectorS3< FT >::z().
 { return (x() == v.x()) && (y() == v.y()) && (z() == v.z()) ; }
bool operator== (const Null_vector &) const
Definition at line 170 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References x, y, and z.
 { return (x() == FT(0)) && (y() == FT(0)) && (z() == FT(0)) ; }
FT& operator[] (int i) inline
Definition at line 84 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::cartesian().
 { return cartesian(i); }
const FT& operator[] (int i) const inline
Definition at line 85 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::cartesian().
 { return cartesian(i); }
const FT & operator[] (int i) const inline
Definition at line 210 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
 { return cartesian(i); }
FT squared_norm () const inline
Definition at line 126 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x, VectorS3< FT >::_y, and VectorS3< FT >::_z.
 { return _x*_x+_y*_y+_z*_z; }
VectorS3< FT > transform (const Aff_transformationS3< FT > & t) const
Definition at line 301 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References Aff_transformationS3< FT >::transform().
 { return t.transform(*this); }
Self transform (const Aff_transformation & t) const inline
Definition at line 119 of file include/CGAL/SimpleCartesian/VectorS3.h.
References Aff_transformationS3< FT >::transform().
     { return t.transform(*this); }
const FT& x () const inline
Definition at line 65 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x.
 { return _x; }
FT& x () inline
Definition at line 68 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_x.
 { return _x; }
const FT & x () const inline
Definition at line 182 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References DirectionS3< FT >::e0.
Referenced by VectorS3< FT >::cartesian(), cross_product(), VectorS3< FT >::operator*(), operator*(), VectorS3< FT >::operator+(), operator+(), PointS3< FT >::operator+=(), VectorS3< FT >::operator-(), operator-(), PointS3< FT >::operator-=(), operator<<(), VectorS3< FT >::operator==(), operator>>(), PlaneS3< FT >::PlaneS3(), PlaneS3< FT >::to_2d(), PlaneS3< FT >::to_plane_basis(), Aff_transformation_repS3< FT >::transform(), and Scaling_repS3< FT >::transform().
 { return e0; }
const FT& y () const inline
Definition at line 66 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_y.
 { return _y; }
FT& y () inline
Definition at line 69 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_y.
 { return _y; }
const FT & y () const inline
Definition at line 188 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References DirectionS3< FT >::e1.
Referenced by VectorS3< FT >::cartesian(), cross_product(), VectorS3< FT >::operator*(), operator*(), VectorS3< FT >::operator+(), operator+(), PointS3< FT >::operator+=(), VectorS3< FT >::operator-(), operator-(), PointS3< FT >::operator-=(), operator<<(), VectorS3< FT >::operator==(), operator>>(), PlaneS3< FT >::PlaneS3(), PlaneS3< FT >::to_2d(), PlaneS3< FT >::to_plane_basis(), Aff_transformation_repS3< FT >::transform(), and Scaling_repS3< FT >::transform().
 { return  e1; }
const FT& z () const inline
Definition at line 67 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_z.
 { return _z; }
FT& z () inline
Definition at line 70 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::_z.
 { return _z; }
const FT & z () const inline
Definition at line 194 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
References DirectionS3< FT >::e2.
Referenced by VectorS3< FT >::cartesian(), cross_product(), VectorS3< FT >::operator*(), operator*(), VectorS3< FT >::operator+(), operator+(), PointS3< FT >::operator+=(), VectorS3< FT >::operator-(), operator-(), PointS3< FT >::operator-=(), operator<<(), VectorS3< FT >::operator==(), operator>>(), PlaneS3< FT >::PlaneS3(), PlaneS3< FT >::to_2d(), PlaneS3< FT >::to_plane_basis(), Aff_transformation_repS3< FT >::transform(), and Scaling_repS3< FT >::transform().
 { return  e2; }
Friends And Related Function Documentation
friend class DirectionS3< FT > friend
Definition at line 66 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
Member Data Documentation
FT _x protected
Definition at line 128 of file include/CGAL/SimpleCartesian/VectorS3.h.
Referenced by VectorS3< FT >::hx(), VectorS3< FT >::operator!=(), VectorS3< FT >::operator*(), VectorS3< FT >::operator*=(), VectorS3< FT >::operator+(), VectorS3< FT >::operator+=(), VectorS3< FT >::operator-(), VectorS3< FT >::operator-=(), VectorS3< FT >::operator/(), VectorS3< FT >::operator/=(), VectorS3< FT >::operator=(), VectorS3< FT >::operator==(), VectorS3< FT >::squared_norm(), and VectorS3< FT >::x().
FT _y protected
Definition at line 128 of file include/CGAL/SimpleCartesian/VectorS3.h.
Referenced by VectorS3< FT >::hy(), VectorS3< FT >::operator!=(), VectorS3< FT >::operator*(), VectorS3< FT >::operator*=(), VectorS3< FT >::operator+(), VectorS3< FT >::operator+=(), VectorS3< FT >::operator-(), VectorS3< FT >::operator-=(), VectorS3< FT >::operator/(), VectorS3< FT >::operator/=(), VectorS3< FT >::operator=(), VectorS3< FT >::operator==(), VectorS3< FT >::squared_norm(), and VectorS3< FT >::y().
FT _z protected
Definition at line 128 of file include/CGAL/SimpleCartesian/VectorS3.h.
Referenced by VectorS3< FT >::hz(), VectorS3< FT >::operator!=(), VectorS3< FT >::operator*(), VectorS3< FT >::operator*=(), VectorS3< FT >::operator+(), VectorS3< FT >::operator+=(), VectorS3< FT >::operator-(), VectorS3< FT >::operator-=(), VectorS3< FT >::operator/(), VectorS3< FT >::operator/=(), VectorS3< FT >::operator=(), VectorS3< FT >::operator==(), VectorS3< FT >::squared_norm(), and VectorS3< FT >::z().
FT e0
Definition at line 110 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
Referenced by DirectionS3< FT >::DirectionS3(), and PointS3< FT >::PointS3().
FT e1
Definition at line 111 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
Referenced by DirectionS3< FT >::DirectionS3(), and PointS3< FT >::PointS3().
FT e2
Definition at line 112 of file CGAL/include/CGAL/SimpleCartesian/VectorS3.h.
Referenced by DirectionS3< FT >::DirectionS3(), and PointS3< FT >::PointS3().
The documentation for this class was generated from the following files:
simple_cartesian_classes.h
include/CGAL/SimpleCartesian/VectorS3.h