Rocstar: rflu_modforcesmoments Module Reference
rflu_modforcesmoments Module Reference
Public Member Functions
subroutine, public rflu_computeglobalforcesmoments (regions)
subroutine, public rflu_computelocalforcesmoments (pRegion)
subroutine, public rflu_createforcesmoments (pRegion)
subroutine, public rflu_createglobalthrustflags (pRegion)
subroutine, public rflu_destroyforcesmoments (pRegion)
subroutine, public rflu_destroyglobalthrustflags (pRegion)
subroutine, public rflu_printglobalforcesmoments (pRegion)
subroutine, public rflu_setglobalthrustflags (regions)
subroutine, public rflu_writeglobalforcesmoments (pRegion)
Private Member Functions
subroutine, private rflu_initforcesmoments (pRegion)
subroutine, private rflu_initglobalthrustflags (pRegion)
subroutine, private rflu_nullifyforcesmoments (pRegion)
subroutine, private rflu_nullifyglobalthrustflags (pRegion)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModForcesMoments.F90,v $ $Revision: 1.11 $'
Detailed Description
Definition at line 39 of file RFLU_ModForcesMoments.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_computeglobalforcesmoments (type(t_region), dimension(:), pointer regions)
Definition at line 113 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
subroutine, public rflu_computelocalforcesmoments (type(t_region), pointer pRegion)
Definition at line 694 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
subroutine, public rflu_createforcesmoments (type(t_region), pointer pRegion)
Definition at line 909 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_initforcesmoments().
Referenced by rflu_initflowsolver().
subroutine, public rflu_createglobalthrustflags (type(t_region), pointer pRegion)
Definition at line 1072 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_initglobalthrustflags().
Referenced by rflu_initflowsolver().
subroutine, public rflu_destroyforcesmoments (type(t_region), pointer pRegion)
Definition at line 1148 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyforcesmoments().
Referenced by rflu_endflowsolver().
subroutine, public rflu_destroyglobalthrustflags (type(t_region), pointer pRegion)
Definition at line 1302 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyglobalthrustflags().
Referenced by rflu_endflowsolver().
subroutine, private rflu_initforcesmoments (type(t_region), pointer pRegion) private
Definition at line 1377 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createforcesmoments().
subroutine, private rflu_initglobalthrustflags (type(t_region), pointer pRegion) private
Definition at line 1532 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createglobalthrustflags().
subroutine, private rflu_nullifyforcesmoments (type(t_region), pointer pRegion) private
Definition at line 1600 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_destroyforcesmoments().
subroutine, private rflu_nullifyglobalthrustflags (type(t_region), pointer pRegion) private
Definition at line 1685 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_destroyglobalthrustflags().
subroutine, public rflu_printglobalforcesmoments (type(t_region), pointer pRegion)
Definition at line 1751 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
subroutine, public rflu_setglobalthrustflags (type(t_region), dimension(:), pointer regions)
Definition at line 1868 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), nvals, and moderror::registerfunction().
Referenced by rflu_initflowsolver().
subroutine, public rflu_writeglobalforcesmoments (type(t_region), pointer pRegion)
Definition at line 2021 of file RFLU_ModForcesMoments.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: RFLU_ModForcesMoments.F90,v $ $Revision: 1.11 $' private
Definition at line 60 of file RFLU_ModForcesMoments.F90.
The documentation for this module was generated from the following file:
RFLU_ModForcesMoments.F90