Rocstar: Kdtree_d< Traits >::Box Class Reference
Kdtree_d< Traits >::Box Class Reference
#include <kdtree_d.h>
Public Member Functions
Box ()
Box (const Box &box)
Box (const Point &l, const Point &r, int _dim)
Box (int _dim)
ExtPoint & get_vertex (bool f_left)
void set_left (Point &l)
void set_right (Point &r)
const ExtPoint & get_left () const
const ExtPoint & get_right () const
void set_coord_left (int k, Point &p)
void set_coord_right (int k, Point &p)
bool is_in (const Box &o) const
bool is_in (const Point &o) const
bool is_coord_in_range (int k, const Point &o) const
bool is_intersect (const Box &o) const
bool is_intersect_in_dim (int d, const Box &o) const
bool is_intersect_in_dim_closed (int d, const Box &o) const
bool intersect (Box &o)
bool is_empty () const
bool is_empty_open () const
int comp (const Box &o) const
~Box ()
Public Attributes
int dim
ExtPoint left
ExtPoint right
Detailed Description
template<class Traits>
class Kdtree_d< Traits >::Box
Definition at line 349 of file kdtree_d.h.
Constructor & Destructor Documentation
Box () inline
Definition at line 359 of file kdtree_d.h.
     {
     }
Box (const Box & box) inline
Definition at line 363 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::dim, Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
     {
       dim = box.dim;
       left = box.left;
       right = box.right;
     }
Box (const Point & l, const Point & r, int _dim) inline
Definition at line 371 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::dim, Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
     {
       dim = _dim;
       left = ExtPoint( l, dim );
       right = ExtPoint( r, dim );
     }
Box (int _dim) inline
Definition at line 378 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::dim.
                      : left( ExtPoint::MINUS_INFINITY, _dim ),
                        right( ExtPoint::PLUS_INFINITY, _dim )
     {
       dim = _dim;
     }
~Box () inline
Definition at line 548 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::dim, Kdtree_d< Traits >::Box::left, Kdtree_d< Traits >::Box::right, and Kdtree_d< Traits >::ExtPoint::term().
     {
       left.term();
       right.term();
       dim = 0;
     }
Member Function Documentation
int comp (const Box & o) const inline
Definition at line 536 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare_vector(), Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
Referenced by plag_processeulerfield().
     {
       int  res;
       res = left.compare_vector( o.left );
       if  ( res != 0 )
         return  res;
       return  right.compare_vector( o.right );
     }
const ExtPoint& get_left () const inline
Definition at line 400 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::left.
Referenced by Kdtree_d< Traits >::Box::intersect(), Kdtree_d< Traits >::Box::is_intersect_in_dim(), and Kdtree_d< Traits >::Box::is_intersect_in_dim_closed().
     {
       return left;
     }
const ExtPoint& get_right () const inline
Definition at line 405 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::right.
Referenced by Kdtree_d< Traits >::Box::intersect(), Kdtree_d< Traits >::Box::is_intersect_in_dim(), and Kdtree_d< Traits >::Box::is_intersect_in_dim_closed().
     {
       return right;
     }
ExtPoint& get_vertex (bool f_left) inline
Definition at line 384 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
Referenced by Kdtree_d< Traits >::Node::Plane::split().
     {
       return  f_left? left : right;
     }
bool intersect (Box & o) inline
Definition at line 494 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::Box::dim, Kdtree_d< Traits >::ExtPoint::dimension(), Kdtree_d< Traits >::Box::get_left(), Kdtree_d< Traits >::Box::get_right(), i, Kdtree_d< Traits >::Box::is_empty(), Kdtree_d< Traits >::Box::left, Kdtree_d< Traits >::Box::right, and Kdtree_d< Traits >::ExtPoint::set_coord().
     {
       int dim = left.dimension();
       for (int i = 0; i < dim; i++)
       {
         // left is the maximal of the lefts
         if (left.compare(i, o.get_left()) == -1)
           left.set_coord(i, o.get_left());
         // right is the minimal of the rights
         if (right.compare(i, o.get_right()) == 1)
           right.set_coord(i, o.get_right());
       }
       return !(is_empty());
     }
bool is_coord_in_range (int k, const Point & o) const inline
Definition at line 454 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), k, Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
     {
       return  ( ! ( (left.compare( k, o ) > 0 )
                     ||  (right.compare( k, o ) <= 0 ) ) );
     }
bool is_empty () const inline
Definition at line 512 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::Box::dim, Kdtree_d< Traits >::ExtPoint::dimension(), i, Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
Referenced by Kdtree_d< Traits >::Box::intersect().
     {
       int dim = left.dimension();
       for (int i = 0; i < dim; i++)
       {
         if (left.compare(i, right) == 1)
           return true;
       }
       return false;
     }
bool is_empty_open () const inline
Definition at line 524 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::Box::dim, Kdtree_d< Traits >::ExtPoint::dimension(), i, Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
     {
       int dim = left.dimension();
       for (int i = 0; i < dim; i++)
       {
         if ( left.compare(i, right) >= 0 )
           return true;
       }
       return false;
     }
bool is_in (const Box & o) const inline
Definition at line 424 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::Box::dim, Kdtree_d< Traits >::ExtPoint::dimension(), i, Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
Referenced by Kdtree_d< Traits >::Node::copy_subtree_points(), Kdtree_d< Traits >::Node::search(), and Kdtree_d< Traits >::Node::search_recursive().
     {
       int dim = left.dimension();
       for (int i = 0; i < dim; i++)
       {
         if ( (left.compare(i, o.get_left()) > 0 )
              ||  (right.compare(i, o.get_right()) < 0 ) )
           return false;
       }
       return true;
     }
bool is_in (const Point & o) const inline
Definition at line 440 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::Box::dim, Kdtree_d< Traits >::ExtPoint::dimension(), i, Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
     {
       int dim = left.dimension();
       for (int i = 0; i < dim; i++)
       {
         if ( (left.compare( i, o ) > 0 ) ||
              (right.compare( i, o ) <= 0 ) )
           return false;
       }
       return true;
     }
bool is_intersect (const Box & o) const inline
Definition at line 462 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::Box::dim, Kdtree_d< Traits >::ExtPoint::dimension(), i, Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
     {
       int dim = left.dimension();
       for (int i = 0; i < dim; i++)
       {
         if ( (left.compare(i, o.get_right()) >= 0) ||
              (right.compare(i, o.get_left()) <= 0) )
           return false;
       }
       return true;
     }
bool is_intersect_in_dim (int d, const Box & o) const inline
Definition at line 478 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::Box::get_left(), Kdtree_d< Traits >::Box::get_right(), Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
     {
       return  (! ( (left.compare( d, o.get_right() ) >= 0 )
                    ||  (right.compare( d, o.get_left() ) <= 0) ));
     }
bool is_intersect_in_dim_closed (int d, const Box & o) const inline
Definition at line 487 of file kdtree_d.h.
References Kdtree_d< Traits >::ExtPoint::compare(), Kdtree_d< Traits >::Box::get_left(), Kdtree_d< Traits >::Box::get_right(), Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::Box::right.
Referenced by Kdtree_d< Traits >::Node::search_recursive().
     {
       return  (! ( (left.compare( d, o.get_right() ) > 0 )
                    ||  (right.compare( d, o.get_left() ) < 0) ));
     }
void set_coord_left (int k, Point & p) inline
Definition at line 411 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::left, and Kdtree_d< Traits >::ExtPoint::set_coord().
     {
       left.set_coord( k, p );
     }
void set_coord_right (int k, Point & p) inline
Definition at line 417 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::right, and Kdtree_d< Traits >::ExtPoint::set_coord().
     {
       right.set_coord( k, p );
     }
void set_left (Point & l) inline
Definition at line 390 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::dim, and Kdtree_d< Traits >::Box::left.
     {
       left = ExtPoint( l, dim );
     };
void set_right (Point & r) inline
Definition at line 395 of file kdtree_d.h.
References Kdtree_d< Traits >::Box::dim, and Kdtree_d< Traits >::Box::right.
     {
       right = ExtPoint( r, dim );
     }
Member Data Documentation
int dim
Definition at line 352 of file kdtree_d.h.
Referenced by Kdtree_d< Traits >::Box::Box(), Kdtree_d< Traits >::Box::intersect(), Kdtree_d< Traits >::Box::is_empty(), Kdtree_d< Traits >::Box::is_empty_open(), Kdtree_d< Traits >::Box::is_in(), Kdtree_d< Traits >::Box::is_intersect(), Kdtree_d< Traits >::Box::set_left(), Kdtree_d< Traits >::Box::set_right(), and Kdtree_d< Traits >::Box::~Box().
ExtPoint left
Definition at line 353 of file kdtree_d.h.
Referenced by Kdtree_d< Traits >::Box::Box(), Kdtree_d< Traits >::Box::comp(), Kdtree_d< Traits >::Box::get_left(), Kdtree_d< Traits >::Box::get_vertex(), Kdtree_d< Traits >::Box::intersect(), Kdtree_d< Traits >::Box::is_coord_in_range(), Kdtree_d< Traits >::Box::is_empty(), Kdtree_d< Traits >::Box::is_empty_open(), Kdtree_d< Traits >::Box::is_in(), Kdtree_d< Traits >::Box::is_intersect(), Kdtree_d< Traits >::Box::is_intersect_in_dim(), Kdtree_d< Traits >::Box::is_intersect_in_dim_closed(), Kdtree_d< Traits >::Box::set_coord_left(), Kdtree_d< Traits >::Box::set_left(), and Kdtree_d< Traits >::Box::~Box().
ExtPoint right
Definition at line 353 of file kdtree_d.h.
Referenced by Kdtree_d< Traits >::Box::Box(), Kdtree_d< Traits >::Box::comp(), Kdtree_d< Traits >::Box::get_right(), Kdtree_d< Traits >::Box::get_vertex(), Kdtree_d< Traits >::Box::intersect(), Kdtree_d< Traits >::Box::is_coord_in_range(), Kdtree_d< Traits >::Box::is_empty(), Kdtree_d< Traits >::Box::is_empty_open(), Kdtree_d< Traits >::Box::is_in(), Kdtree_d< Traits >::Box::is_intersect(), Kdtree_d< Traits >::Box::is_intersect_in_dim(), Kdtree_d< Traits >::Box::is_intersect_in_dim_closed(), Kdtree_d< Traits >::Box::set_coord_right(), Kdtree_d< Traits >::Box::set_right(), and Kdtree_d< Traits >::Box::~Box().
The documentation for this class was generated from the following file:
kdtree_d.h