Rocstar: rflo_modfinitedifference Module Reference
rflo_modfinitedifference Module Reference
Public Member Functions
subroutine, public rflo_findiffcompi (ibeg, iend, jbeg, jend, kbeg, kend, ndum, iNOff, ijNOff, idb, ide, var, dvar)
subroutine, public rflo_findiffcompj (ibeg, iend, jbeg, jend, kbeg, kend, ndum, iNOff, ijNOff, idb, ide, var, dvar)
subroutine, public rflo_findiffcompk (ibeg, iend, jbeg, jend, kbeg, kend, ndum, iNOff, ijNOff, idb, ide, var, dvar)
subroutine, public rflo_findiffcompii (ibeg, iend, jbeg, jend, kbeg, kend, ndum, iNOff, ijNOff, idb, ide, var, dvar)
subroutine, public rflo_findiffcompjj (ibeg, iend, jbeg, jend, kbeg, kend, ndum, iNOff, ijNOff, idb, ide, var, dvar)
subroutine, public rflo_findiffcompkk (ibeg, iend, jbeg, jend, kbeg, kend, ndum, iNOff, ijNOff, idb, ide, var, dvar)
subroutine, public rflo_findiffcompis (ni, nj, idb, ide, var, dvar)
subroutine, public rflo_findiffcompjs (ni, nj, idb, ide, var, dvar)
subroutine, public rflo_findiffcompiis (ni, nj, idb, ide, var, dvar)
subroutine, public rflo_findiffcompjjs (ni, nj, idb, ide, var, dvar)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModFiniteDifference.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 37 of file RFLO_ModFiniteDifference.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_findiffcompi (integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer ndum, integer iNOff, integer ijNOff, integer idb, integer ide, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer dvar)
Definition at line 96 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad3d(), and rflo_modgridcontrolmap::rflo_gridphysgrad3d().
subroutine, public rflo_findiffcompii (integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer ndum, integer iNOff, integer ijNOff, integer idb, integer ide, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer dvar)
Definition at line 358 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc3d().
subroutine, public rflo_findiffcompiis (integer ni, integer nj, integer idb, integer ide, real(rfreal), dimension(:,:,:), pointer var, real(rfreal), dimension(:,:,:), pointer dvar)
Definition at line 771 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, j, ni, nj, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc2d().
subroutine, public rflo_findiffcompis (integer ni, integer nj, integer idb, integer ide, real(rfreal), dimension(:,:,:), pointer var, real(rfreal), dimension(:,:,:), pointer dvar)
Definition at line 621 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, j, ni, nj, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc2d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad2d(), and rflo_modgridcontrolmap::rflo_gridphysgrad2d().
subroutine, public rflo_findiffcompj (integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer ndum, integer iNOff, integer ijNOff, integer idb, integer ide, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer dvar)
Definition at line 180 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad3d(), and rflo_modgridcontrolmap::rflo_gridphysgrad3d().
subroutine, public rflo_findiffcompjj (integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer ndum, integer iNOff, integer ijNOff, integer idb, integer ide, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer dvar)
Definition at line 443 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc3d().
subroutine, public rflo_findiffcompjjs (integer ni, integer nj, integer idb, integer ide, real(rfreal), dimension(:,:,:), pointer var, real(rfreal), dimension(:,:,:), pointer dvar)
Definition at line 845 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, j, ni, nj, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc2d().
subroutine, public rflo_findiffcompjs (integer ni, integer nj, integer idb, integer ide, real(rfreal), dimension(:,:,:), pointer var, real(rfreal), dimension(:,:,:), pointer dvar)
Definition at line 694 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, j, ni, nj, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc2d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad2d(), and rflo_modgridcontrolmap::rflo_gridphysgrad2d().
subroutine, public rflo_findiffcompk (integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer ndum, integer iNOff, integer ijNOff, integer idb, integer ide, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer dvar)
Definition at line 269 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad3d(), and rflo_modgridcontrolmap::rflo_gridphysgrad3d().
subroutine, public rflo_findiffcompkk (integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer ndum, integer iNOff, integer ijNOff, integer idb, integer ide, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer dvar)
Definition at line 533 of file RFLO_ModFiniteDifference.F90.
References Polyhedron_incremental_builder_3< HDS >::error(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and StopWatch::stop().
Referenced by rflo_modgridcontrolmap::rflo_gridcontrolfunc3d().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModFiniteDifference.F90,v $ $Revision: 1.4 $' private
Definition at line 68 of file RFLO_ModFiniteDifference.F90.
The documentation for this module was generated from the following file:
RFLO_ModFiniteDifference.F90