Rocstar: rocfracmain Module Reference
rocfracmain Module Reference
Public Member Functions
subroutine, public rocfracinitialize (glb, InitialTime, MPI_COMM_ROCSTAR, MAN_init, surfIn, volIn, obtain_attr)
subroutine, public rocfracfinalize (glb)
subroutine, public rocfracsoln (glb, CurrentTime, CurrentTimeStep, MAN_update_inbuff)
subroutine rocfracinterfacebuff (glb)
subroutine rocfracupdateinbuff (glb, alpha)
subroutine, public rocfracinitialize (glb, InitialTime, MPI_COMM_ROCSTAR, MAN_init, surfIn, volIn, obtain_attr)
subroutine, public rocfracfinalize (glb)
subroutine, public rocfracsoln (glb, CurrentTime, CurrentTimeStep, MAN_update_inbuff)
subroutine rocfracinterfacebuff (glb)
subroutine rocfracupdateinbuff (glb, alpha)
Detailed Description
Definition at line 54 of file RocFracMain.f90.
Member Function/Subroutine Documentation
subroutine, public rocfracfinalize (type(rocfrac_global), pointer glb)
Definition at line 1124 of file RocFracMain.f90.
Referenced by rocfrac_load_module().
subroutine, public rocfracfinalize (type(rocfrac_global), pointer glb)
Definition at line 1236 of file MP/Source/RocFracMain.f90.
References implicit_finalize(), and thermal_finalize().
subroutine, public rocfracinitialize (type(rocfrac_global), pointer glb, real*8, intent(in) InitialTime, integer, intent(in) MPI_COMM_ROCSTAR, integer, intent(in) MAN_init, character(*), intent(in) surfIn, character(*), intent(in) volIn, integer, intent(in) obtain_attr)
Definition at line 111 of file RocFracMain.f90.
References Line_2< R, T >::a(), enhanced_elem_maps_hex(), feminp(), findprobe(), get_mat_stiffness(), i, j, k, readsdv(), rocfracinterfacebuff(), rocfracsubinterface::rocfracinterfaceinitial(), updatemassmatrix(), v3d4_volume(), vol_elem_mat(), vol_elem_mat_matous(), and volratio().
Referenced by rocfrac_load_module().
subroutine, public rocfracinitialize (type(rocfrac_global), pointer glb, real*8, intent(in) InitialTime, integer, intent(in) MPI_COMM_ROCSTAR, integer, intent(in) MAN_init, character(*), intent(in) surfIn, character(*), intent(in) volIn, integer, intent(in) obtain_attr)
Definition at line 111 of file MP/Source/RocFracMain.f90.
References Line_2< R, T >::a(), conductivitytensor(), enhanced_elem_maps_hex(), feminp(), findprobe(), get_mat_stiffness(), i, implicit_initialize(), j, k, Aff_transformation_repS2< FT >::print(), readsdv(), rocfracinterfacebuff(), rocfracsubinterface::rocfracinterfaceinitial(), thermal_initialize(), updatemassmatrix(), v3d4_volume(), vol_elem_mat(), vol_elem_mat_matous(), vol_elem_mat_ortho(), and volratio().
subroutine rocfracinterfacebuff (type(rocfrac_global) glb)
Definition at line 1992 of file MP/Source/RocFracMain.f90.
References k.
subroutine rocfracinterfacebuff (type(rocfrac_global) glb)
Definition at line 1839 of file RocFracMain.f90.
References k.
Referenced by rocfracinitialize(), and rocfracsoln().
subroutine, public rocfracsoln (type(rocfrac_global), pointer glb, real*8, intent(in) CurrentTime, real*8, intent(in) CurrentTimeStep, integer, intent(in) MAN_update_inbuff)
Definition at line 1138 of file RocFracMain.f90.
References Color::alpha(), bc_enforce(), GEM_DomainBoundary::debug(), fluidpressload(), heatfluxload(), i, j, k, max_dt_solid(), principal_stress(), rocfracinterfacebuff(), tractload_hex(), tractloadpress_hex(), tractpressload(), updatemassmatrix(), updaterbar(), updatestructuralsoln::updatestructural(), updatestructuralsoln::updatestructuralht(), v3d10_ale(), v3d4_ale(), and v3d4_volume().
Referenced by rocfrac_load_module().
subroutine, public rocfracsoln (type(rocfrac_global), pointer glb, real*8, intent(in) CurrentTime, real*8, intent(in) CurrentTimeStep, integer, intent(in) MAN_update_inbuff)
Definition at line 1265 of file MP/Source/RocFracMain.f90.
References Color::alpha(), bc_enforce(), GEM_DomainBoundary::debug(), fluidpressload(), heatload_hex(), i, implicit_soln(), j, k, max(), max_dt_solid(), principal_stress(), Aff_transformation_repS2< FT >::print(), rocfracinterfacebuff(), sqrt(), thermal_soln(), tractload_hex(), tractloadpress_hex(), tractpressload(), updatemassmatrix(), updaterbar(), updatestructuralsoln::updatestructural(), updatestructuralsoln::updatestructuralht(), v3d10_ale(), v3d4_ale(), and v3d4_volume().
subroutine rocfracupdateinbuff (type(rocfrac_global), pointer glb, real*8, intent(in) alpha)
Definition at line 2126 of file MP/Source/RocFracMain.f90.
References i.
subroutine rocfracupdateinbuff (type(rocfrac_global), pointer glb, real*8, intent(in) alpha)
Definition at line 2007 of file RocFracMain.f90.
References i.
Referenced by rocfrac_load_module().
The documentation for this module was generated from the following files:
RocFracMain.f90
MP/Source/RocFracMain.f90