Rocstar: ScalarMultiplyQualityMetric Class Reference
ScalarMultiplyQualityMetric Class Reference
Multiplies quality metric value by a number (a double).
#include <ScalarMultiplyQualityMetric.hpp>
Public Member Functions
ScalarMultiplyQualityMetric (QualityMetric *qm1, double scalar_double, MsqError &err)
virtual ~ScalarMultiplyQualityMetric ()
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &value, MsqError &err)
bool evaluate_vertex (PatchData &pd, MsqVertex *vertex, double &value, MsqError &err)
ScalarMultiplyQualityMetric (QualityMetric *qm1, double scalar_double, MsqError &err)
virtual ~ScalarMultiplyQualityMetric ()
bool evaluate_element (PatchData &pd, MsqMeshEntity *element, double &value, MsqError &err)
Evaluate the metric for an element.
bool evaluate_vertex (PatchData &pd, MsqVertex *vertex, double &value, MsqError &err)
Evaluate the metric for a vertex.
Public Member Functions inherited from QualityMetric
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Calls compute_vertex_numerical_gradient if gradType equals NUMERCIAL_GRADIENT. Calls compute_vertex_analytical_gradient if gradType equals ANALYTICAL_GRADIENT;.
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
virtual ~QualityMetric ()
MetricType get_metric_type ()
void set_element_evaluation_mode (ElementEvaluationMode mode, MsqError &err)
Sets the evaluation mode for the ELEMENT_BASED metrics.
ElementEvaluationMode get_element_evaluation_mode ()
Returns the evaluation mode for the metric.
void set_averaging_method (AveragingMethod method, MsqError &err)
void set_feasible_constraint (int alpha)
int get_feasible_constraint ()
Returns the feasible flag for this metric.
void set_name (msq_std::string st)
Sets the name of this metric.
msq_std::string get_name ()
Returns the name of this metric (as a string).
double vertex_barrier_function (double det, double delta)
Escobar Barrier Function for Shape and Other Metrics.
void set_gradient_type (GRADIENT_TYPE grad)
Sets gradType for this metric.
void set_hessian_type (HESSIAN_TYPE ht)
Sets hessianType for this metric.
bool compute_vertex_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_gradient() or compute_element_analytical_gradient() for gradType equal NUMERICAL_GRADIENT or ANALYTICAL_GRADIENT, respectively.
bool compute_element_gradient_expanded (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
bool compute_element_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
For MetricType == ELEMENT_BASED. Calls either compute_element_numerical_hessian() or compute_element_analytical_hessian() for hessianType equal NUMERICAL_HESSIAN or ANALYTICAL_HESSIAN, respectively.
void set_negate_flag (int neg)
int get_negate_flag ()
Returns negateFlag.
virtual void change_metric_type (MetricType t, MsqError &err)
Private Attributes
QualityMetric * qualMetric
double scaleFactor
Additional Inherited Members
Public Types inherited from QualityMetric
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
enum MetricType {
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY,
MT_UNDEFINED, VERTEX_BASED, ELEMENT_BASED, VERTEX_BASED_FREE_ONLY
}
enum ElementEvaluationMode {
EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS, QUADRATIC_GAUSS_POINTS,
CUBIC_GAUSS_POINTS, EEM_UNDEFINED, ELEMENT_VERTICES, LINEAR_GAUSS_POINTS,
QUADRATIC_GAUSS_POINTS, CUBIC_GAUSS_POINTS
}
enum AveragingMethod {
NONE, LINEAR, RMS, HMS,
MINIMUM, MAXIMUM, HARMONIC, GEOMETRIC,
SUM, SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION,
MAX_OVER_MIN, MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED, NONE,
LINEAR, RMS, HMS, MINIMUM,
MAXIMUM, HARMONIC, GEOMETRIC, SUM,
SUM_SQUARED, GENERALIZED_MEAN, STANDARD_DEVIATION, MAX_OVER_MIN,
MAX_MINUS_MIN, SUM_OF_RATIOS_SQUARED
}
enum GRADIENT_TYPE { NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT, NUMERICAL_GRADIENT, ANALYTICAL_GRADIENT }
enum HESSIAN_TYPE { NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN, NUMERICAL_HESSIAN, ANALYTICAL_HESSIAN }
Protected Member Functions inherited from QualityMetric
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
QualityMetric ()
void set_metric_type (MetricType t)
This function should be used in the constructor of every concrete quality metric.
double average_metrics (const double metric_values[], const int &num_values, MsqError &err)
average_metrics takes an array of length num_values and averages the contents using averaging method data member avgMethod .
double average_metric_and_weights (double metric_values[], int num_metric_values, MsqError &err)
Given a list of metric values, calculate the average metric valude according to the current avgMethod and write into the passed metric_values array the the value weight/count to use when averaging gradient vectors for the metric.
double weighted_average_metrics (const double coef[], const double metric_values[], const int &num_values, MsqError &err)
takes an array of coefficients and an array of metrics (both of length num_value) and averages the contents using averaging method 'method'.
bool compute_vertex_numerical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
bool compute_element_numerical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Non-virtual function which numerically computes the gradient of a QualityMetric of a given element for a given set of free vertices on that element. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
virtual bool compute_vertex_analytical_gradient (PatchData &pd, MsqVertex &vertex, MsqVertex *vertices[], Vector3D grad_vec[], int num_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is VERTEX_BASED.
virtual bool compute_element_analytical_gradient (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], int num_free_vtx, double &metric_value, MsqError &err)
Virtual function that computes the gradient of the QualityMetric analytically. The base class implementation of this function simply prints a warning and calls compute_numerical_gradient to calculate the gradient. This is used by metric which mType is ELEMENT_BASED. For parameters, see compute_element_gradient() .
bool compute_element_numerical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
virtual bool compute_element_analytical_hessian (PatchData &pd, MsqMeshEntity *element, MsqVertex *free_vtces[], Vector3D grad_vec[], Matrix3D hessian[], int num_free_vtx, double &metric_value, MsqError &err)
Protected Attributes inherited from QualityMetric
AveragingMethod avgMethod
int feasible
msq_std::string metricName
Detailed Description
Multiplies quality metric value by a number (a double).
Definition at line 49 of file includeLinks/ScalarMultiplyQualityMetric.hpp.
Constructor & Destructor Documentation
ScalarMultiplyQualityMetric (QualityMetric * qm1, double scalar_double, MsqError & err)
Ensures that qm1 is not NULL. If qm1 is only valid on a certain feasible, then the composite metric has the same constraint. The composite metric also has the same negate flag as qm1.
Definition at line 41 of file QualityMetric/ScalarMultiplyQualityMetric.cpp.
References QualityMetric::feasible, QualityMetric::get_feasible_constraint(), QualityMetric::get_metric_type(), QualityMetric::get_negate_flag(), MsqError::INVALID_ARG, MSQ_SETERR, QualityMetric::set_metric_type(), QualityMetric::set_name(), and QualityMetric::set_negate_flag().
   : qualMetric(qm1), scaleFactor(scalar_double)
 {
   if(qm1 == NULL){
     MSQ_SETERR(err)("NULL pointer", MsqError::INVALID_ARG);
     return;
   }
   feasible=qm1->get_feasible_constraint();
   int n_flag=qm1->get_negate_flag();
   set_negate_flag(n_flag);
   set_metric_type(qm1->get_metric_type());
   set_name("Scalar Multiply Quality Metric");
 }
virtual ~ScalarMultiplyQualityMetric () inline virtual
Definition at line 61 of file includeLinks/ScalarMultiplyQualityMetric.hpp.
         {  }
ScalarMultiplyQualityMetric (QualityMetric * qm1, double scalar_double, MsqError & err)
Ensures that qm1 is not NULL. If qm1 is only valid on a certain feasible, then the composite metric has the same constraint. The composite metric also has the same negate flag as qm1.
virtual ~ScalarMultiplyQualityMetric () inline virtual
Definition at line 61 of file src/QualityMetric/ScalarMultiplyQualityMetric.hpp.
         {  }
Member Function Documentation
bool evaluate_element (PatchData & pd, MsqMeshEntity * element, double & value, MsqError & err) virtual
Returns scalar times qMetric1->evaluate_element(element, err).
Reimplemented from QualityMetric.
Definition at line 61 of file QualityMetric/ScalarMultiplyQualityMetric.cpp.
References QualityMetric::evaluate_element(), MSQ_ERRZERO, ScalarMultiplyQualityMetric::qualMetric, and ScalarMultiplyQualityMetric::scaleFactor.
 {
   bool valid_flag;
   double metric1;
   valid_flag=qualMetric->evaluate_element(pd, element, metric1, err); MSQ_ERRZERO(err);
   if(!valid_flag)
     return false;
   value = scaleFactor*metric1;
   return valid_flag;
 }
bool evaluate_element (PatchData & , MsqMeshEntity * , double & , MsqError & err) virtual
Evaluate the metric for an element.
Reimplemented from QualityMetric.
bool evaluate_vertex (PatchData & , MsqVertex * , double & , MsqError & err) virtual
Evaluate the metric for a vertex.
Reimplemented from QualityMetric.
bool evaluate_vertex (PatchData & pd, MsqVertex * vert, double & value, MsqError & err) virtual
Returns scalar times qMetric1->evaluate_vertex(...).
Reimplemented from QualityMetric.
Definition at line 77 of file QualityMetric/ScalarMultiplyQualityMetric.cpp.
References QualityMetric::evaluate_vertex(), MSQ_ERRZERO, ScalarMultiplyQualityMetric::qualMetric, and ScalarMultiplyQualityMetric::scaleFactor.
 {
   bool valid_flag;
   double metric1;
   valid_flag=qualMetric->evaluate_vertex(pd, vert, metric1, err); MSQ_ERRZERO(err);
   if(!valid_flag)
     return false;
   value = scaleFactor*metric1;
   return valid_flag;
 }
Member Data Documentation
QualityMetric * qualMetric private
Definition at line 71 of file includeLinks/ScalarMultiplyQualityMetric.hpp.
Referenced by ScalarMultiplyQualityMetric::evaluate_element(), and ScalarMultiplyQualityMetric::evaluate_vertex().
double scaleFactor private
Definition at line 72 of file includeLinks/ScalarMultiplyQualityMetric.hpp.
Referenced by ScalarMultiplyQualityMetric::evaluate_element(), and ScalarMultiplyQualityMetric::evaluate_vertex().
The documentation for this class was generated from the following files:
includeLinks/ScalarMultiplyQualityMetric.hpp
QualityMetric/ScalarMultiplyQualityMetric.cpp