Rocstar: rflu_modlimiters Module Reference
rflu_modlimiters Module Reference
Public Member Functions
subroutine, public rflu_computelimiterbarthjesp (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad, lim)
subroutine, public rflu_computelimitervenkat (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, grad, lim)
subroutine, public rflu_createlimiter (pRegion, iBegGrad, iEndGrad, lim)
subroutine, public rflu_destroylimiter (pRegion, lim)
subroutine, public rflu_limitgradcells (pRegion, iBegGrad, iEndGrad, grad, lim)
subroutine, public rflu_limitgradcellssimple (pRegion, iBegVar, iEndVar, iBegGrad, iEndGrad, var, varInfo, grad)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModLimiters.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file RFLU_ModLimiters.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_computelimiterbarthjesp (type(t_region), pointer pRegion, integer iBegVar, integer iEndVar, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad, real(rfreal), dimension(:,:), pointer lim)
Definition at line 101 of file RFLU_ModLimiters.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), min(), moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by cellgradientsmp(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), and rflu_modresidual::rflu_res_computeresidual().
subroutine, public rflu_computelimitervenkat (type(t_region), pointer pRegion, integer iBegVar, integer iEndVar, integer iBegGrad, integer iEndGrad, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:,:), pointer grad, real(rfreal), dimension(:,:), pointer lim)
Definition at line 310 of file RFLU_ModLimiters.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), min(), moderror::registerfunction(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by cellgradientsmp(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), and rflu_modresidual::rflu_res_computeresidual().
subroutine, public rflu_createlimiter (type(t_region), pointer pRegion, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer lim)
Definition at line 531 of file RFLU_ModLimiters.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by cellgradientsmp(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), and rflu_modresidual::rflu_res_computeresidual().
subroutine, public rflu_destroylimiter (type(t_region), pointer pRegion, real(rfreal), dimension(:,:), pointer lim)
Definition at line 604 of file RFLU_ModLimiters.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by cellgradientsmp(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), and rflu_modresidual::rflu_res_computeresidual().
subroutine, public rflu_limitgradcells (type(t_region), pointer pRegion, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:,:), pointer grad, real(rfreal), dimension(:,:), pointer lim)
Definition at line 679 of file RFLU_ModLimiters.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by cellgradientsmp(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), and rflu_modresidual::rflu_res_computeresidual().
subroutine, public rflu_limitgradcellssimple (type(t_region), pointer pRegion, integer, intent(in) iBegVar, integer, intent(in) iEndVar, integer, intent(in) iBegGrad, integer, intent(in) iEndGrad, real(rfreal), dimension(:,:), pointer var, integer, dimension(:), pointer varInfo, real(rfreal), dimension(:,:,:), pointer grad)
Definition at line 765 of file RFLU_ModLimiters.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), and moderror::registerfunction().
Referenced by cellgradientsmp(), explicitmultistage(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), and rflu_modresidual::rflu_res_computeresidual().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModLimiters.F90,v $ $Revision: 1.5 $' private
Definition at line 65 of file RFLU_ModLimiters.F90.
The documentation for this module was generated from the following file:
RFLU_ModLimiters.F90