Rocstar: rflu_modresidual Module Reference
rflu_modresidual Module Reference
Public Member Functions
subroutine, public rflu_res_computeresidual (pRegion)
subroutine, public rflu_getresidualsupport1 (pRegion, icg, rs, rsSizeMax, rsSize)
subroutine, public rflu_getresidualsupport2 (pRegion, icg, rs, rsSizeMax, rsSize)
subroutine, public rflu_res_setcvold (pRegion)
subroutine, public rflu_res_setdiss (pRegion)
subroutine, public rflu_res_setrhs (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModResidual.F90,v $ $Revision: 1.18 $'
Detailed Description
Definition at line 39 of file RFLU_ModResidual.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_getresidualsupport1 (type(t_region), pointer pRegion, integer, intent(in) icg, integer, dimension(:) rs, integer, intent(inout) rsSizeMax, integer, intent(out) rsSize)
Definition at line 322 of file RFLU_ModResidual.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), rs(), and StopWatch::stop().
Referenced by rflu_modcoloring::rflu_col_buildcolorings(), and rflu_modpetscnewtonkrylov::rflu_petsc_createcoloring().
subroutine, public rflu_getresidualsupport2 (type(t_region), pointer pRegion, integer, intent(in) icg, integer, dimension(:) rs, integer, intent(inout) rsSizeMax, integer, intent(out) rsSize)
Definition at line 477 of file RFLU_ModResidual.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), moderror::registerfunction(), rs(), and StopWatch::stop().
Referenced by rflu_modcoloring::rflu_col_buildcolorings(), and rflu_modpetscnewtonkrylov::rflu_petsc_createcoloring().
subroutine, public rflu_res_computeresidual (type(t_region), pointer pRegion)
Definition at line 99 of file RFLU_ModResidual.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_moddifferentiationbfaces::rflu_computebfgradconstrwrapper(), rflu_computefluxinv(), rflu_moddifferentiationbfaces::rflu_computegradbfaceswrapper(), rflu_moddifferentiationcells::rflu_computegradcellswrapper(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_moddifferentiationfaces::rflu_computegradfaceswrapper(), rflu_modlimiters::rflu_computelimiterbarthjesp(), rflu_modlimiters::rflu_computelimitervenkat(), rflu_modconvertcv::rflu_convertcvcons2prim(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_modlimiters::rflu_createlimiter(), rflu_decideneedbgradface(), rflu_modlimiters::rflu_destroylimiter(), rflu_modviscousflux::rflu_enforceheatflux(), rflu_modlimiters::rflu_limitgradcells(), rflu_modlimiters::rflu_limitgradcellssimple(), rflu_res_setdiss(), rflu_res_setrhs(), rflu_modviscousflux::rflu_viscousfluxes(), rflu_modviscousflux::rflu_viscousfluxespatches(), rflu_modweno::rflu_wenogradcellswrapper(), and rflu_modweno::rflu_wenogradcellsxyzwrapper().
Referenced by rflu_modpetscnewtonkrylov::rflu_petsc_formresidual().
subroutine, public rflu_res_setcvold (type (t_region), pointer pRegion)
Definition at line 716 of file RFLU_ModResidual.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
subroutine, public rflu_res_setdiss (type (t_region), pointer pRegion)
Definition at line 798 of file RFLU_ModResidual.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_res_computeresidual().
subroutine, public rflu_res_setrhs (type (t_region), pointer pRegion)
Definition at line 882 of file RFLU_ModResidual.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_res_computeresidual().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModResidual.F90,v $ $Revision: 1.18 $' private
Definition at line 68 of file RFLU_ModResidual.F90.
The documentation for this module was generated from the following file:
RFLU_ModResidual.F90