Rocstar: plag_modeulerian Module Reference
plag_modeulerian Module Reference
Public Member Functions
subroutine, public plag_calceulerianfield (pRegion)
subroutine, public plag_createeulerianfield (pRegion, pPlag)
subroutine, public plag_destroyeulerianfield (pRegion, pPlag)
subroutine, public plag_initeulerianfield (pRegion, pPlag)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_ModEulerian.F90,v $ $Revision: 1.8 $'
Detailed Description
Definition at line 39 of file PLAG_ModEulerian.F90.
Member Function/Subroutine Documentation
subroutine, public plag_calceulerianfield (type(t_region), pointer pRegion)
Definition at line 122 of file PLAG_ModEulerian.F90.
References moderror::deregisterfunction(), ic, idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), and CImg< T >::sum().
Referenced by modstatsroutines::getstatistics().
subroutine, public plag_createeulerianfield (pRegion, type(t_plag), pointer pPlag)
Definition at line 287 of file PLAG_ModEulerian.F90.
References moderror::deregisterfunction(), moderror::errorstop(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), and rflo_getdimensdummy().
Referenced by plag_allocatememory().
subroutine, public plag_destroyeulerianfield (pRegion, type(t_plag), pointer pPlag)
Definition at line 389 of file PLAG_ModEulerian.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public plag_initeulerianfield (pRegion, type(t_plag), pointer pPlag)
Definition at line 471 of file PLAG_ModEulerian.F90.
References moderror::deregisterfunction(), moderror::errorstop(), icell, idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), and CImg< T >::sum().
Referenced by plag_initmemory().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_ModEulerian.F90,v $ $Revision: 1.8 $' private
Definition at line 67 of file PLAG_ModEulerian.F90.
The documentation for this module was generated from the following file:
PLAG_ModEulerian.F90