Rocstar: Bbox_2 Class Reference
Bbox_2 Class Reference
#include <Bbox_2.h>
Public Member Functions
Bbox_2 ()
Bbox_2 (double x_min, double y_min, double x_max, double y_max)
bool operator== (const Bbox_2 &b) const
bool operator!= (const Bbox_2 &b) const
int dimension () const
double xmin () const
double ymin () const
double xmax () const
double ymax () const
double max (int i) const
double min (int i) const
Bbox_2 operator+ (const Bbox_2 &b) const
Bbox_2 ()
Bbox_2 (double x_min, double y_min, double x_max, double y_max)
int dimension () const
double xmin () const
double ymin () const
double xmax () const
double ymax () const
double min (int i) const
double max (int i) const
Bbox_2 operator+ (const Bbox_2 &b) const
Bbox_2 & operator+= (const Bbox_2 &b)
Private Attributes
double _min [2]
double _max [2]
Detailed Description
Definition at line 65 of file CGAL/include/CGAL/Bbox_2.h.
Constructor & Destructor Documentation
CGAL_BEGIN_NAMESPACE Bbox_2 ()
Definition at line 56 of file Bbox_2.C.
Referenced by operator+().
 { new ( static_cast< void*>(ptr)) Fourtuple<double>(); }
Bbox_2 (double x_min, double y_min, double x_max, double y_max)
Definition at line 59 of file Bbox_2.C.
 {
   new ( static_cast< void*>(ptr)) Fourtuple<double>(x_min, y_min,
                                                     x_max, y_max);
 }
Bbox_2 () inline
Definition at line 36 of file include/CGAL/Bbox_2.h.
References _max, and _min.
            {
     _min[0] = _min[1] = HUGE_VAL;
     _max[0] = _max[1] = -HUGE_VAL;
   }
Bbox_2 (double x_min, double y_min, double x_max, double y_max) inline
Definition at line 40 of file include/CGAL/Bbox_2.h.
References _max, and _min.
   { _min[0]=x_min; _min[1]=y_min; _max[0]=x_max; _max[1]=y_max; }
Member Function Documentation
int dimension () const inline
Definition at line 48 of file include/CGAL/Bbox_2.h.
 { return 2; }
int dimension () const inline
Definition at line 91 of file CGAL/include/CGAL/Bbox_2.h.
 { return 2; }
double max (int i) const inline
Definition at line 63 of file include/CGAL/Bbox_2.h.
References CGAL_kernel_precondition, xmax(), and ymax().
{
     CGAL_kernel_precondition( (i == 0 ) || ( i == 1 ) );
     if(i == 0) {
       return xmax();
     }
     return ymax();
   }
double max (int i) const inline
Definition at line 125 of file CGAL/include/CGAL/Bbox_2.h.
References CGAL_kernel_precondition, xmax(), and ymax().
 {
   CGAL_kernel_precondition( (i == 0 ) || ( i == 1 ) );
   if(i == 0) { return xmax(); }
   return ymax();
 }
double min (int i) const inline
Definition at line 55 of file include/CGAL/Bbox_2.h.
References CGAL_kernel_precondition, xmin(), and ymin().
{
     CGAL_kernel_precondition( (i == 0 ) || ( i == 1 ) );
     if(i == 0) {
       return xmin();
     }
     return ymin();
   }
double min (int i) const inline
Definition at line 116 of file CGAL/include/CGAL/Bbox_2.h.
References CGAL_kernel_precondition, xmin(), and ymin().
 {
   CGAL_kernel_precondition( (i == 0 ) || ( i == 1 ) );
   if(i == 0) { return xmin(); }
   return ymin();
 }
bool operator!= (const Bbox_2 & b) const
Definition at line 72 of file Bbox_2.C.
 {
   return ! (b == *this);
 }
Bbox_2 operator+ (const Bbox_2 & b) const inline
Definition at line 71 of file include/CGAL/Bbox_2.h.
{
     Bbox_2 box=*this;  box+=b;  return box;
   }
Bbox_2 operator+ (const Bbox_2 & b) const inline
Definition at line 131 of file CGAL/include/CGAL/Bbox_2.h.
References Bbox_2(), max(), min(), xmax(), xmin(), ymax(), and ymin().
 {
   return Bbox_2(std::min(xmin(), b.xmin()),
                 std::min(ymin(), b.ymin()),
                 std::max(xmax(), b.xmax()),
                 std::max(ymax(), b.ymax()));
 }
Bbox_2& operator+= (const Bbox_2 & b) inline
Definition at line 75 of file include/CGAL/Bbox_2.h.
References _max, _min, max(), and min().
{
     _min[0] = std::min(_min[0], b._min[0]);
     _min[1] = std::min(_min[1], b._min[1]);
     _max[0] = std::max(_max[0], b._max[0]);
     _max[1] = std::max(_max[1], b._max[1]);
     return *this;
   }
bool operator== (const Bbox_2 & b) const
Definition at line 66 of file Bbox_2.C.
References xmax(), xmin(), ymax(), and ymin().
 {
   return    xmin() == b.xmin() && xmax() == b.xmax()
          && ymin() == b.ymin() && ymax() == b.ymax();
 }
double xmax () const inline
Definition at line 51 of file include/CGAL/Bbox_2.h.
References _max.
 { return _max[0]; }
double xmax () const inline
Definition at line 106 of file CGAL/include/CGAL/Bbox_2.h.
Referenced by do_overlap(), do_overlap_eps(), do_overlap_strict(), setup_py::grid(), max(), operator+(), operator<<(), operator==(), peri_cocnlinitsolution(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), plag_rflu_initsolutionrandom(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_openprobefile(), rflu_modoles::rflu_buildstencilsoles(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modprobes::rflu_findprobecells(), rflu_pickregionscoord(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modgeometrytools::rflu_testinboundbox(), rocflo_blocks(), and select_bbx().
 { return ptr->e2; }
double xmin () const inline
Definition at line 49 of file include/CGAL/Bbox_2.h.
References _min.
 { return _min[0]; }
double xmin () const inline
Definition at line 96 of file CGAL/include/CGAL/Bbox_2.h.
Referenced by do_overlap(), do_overlap_eps(), do_overlap_strict(), min(), operator+(), operator<<(), operator==(), peri_cocnlinitsolution(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), plag_rflu_initsolutionrandom(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_openprobefile(), rflu_modoles::rflu_buildstencilsoles(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modprobes::rflu_findprobecells(), rflu_initflowhardcode(), rflu_pickregionscoord(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modgeometrytools::rflu_testinboundbox(), rocflo_blocks(), and select_bbx().
 { return ptr->e0; }
double ymax () const inline
Definition at line 52 of file include/CGAL/Bbox_2.h.
References _max.
 { return _max[1]; }
double ymax () const inline
Definition at line 111 of file CGAL/include/CGAL/Bbox_2.h.
Referenced by do_overlap(), do_overlap_eps(), do_overlap_strict(), max(), operator+(), operator<<(), operator==(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_3d(), plag_rflu_initsolutionrandom(), prep_modbcdistribution::profinflowvttaylorcyl(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_openprobefile(), rflu_modoles::rflu_buildstencilsoles(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modprobes::rflu_findprobecells(), rflu_pickregionscoord(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modgeometrytools::rflu_testinboundbox(), rocflo_blocks(), and select_bbx().
 { return ptr->e3; }
double ymin () const inline
Definition at line 50 of file include/CGAL/Bbox_2.h.
References _min.
 { return _min[1]; }
double ymin () const inline
Definition at line 101 of file CGAL/include/CGAL/Bbox_2.h.
Referenced by do_overlap(), do_overlap_eps(), do_overlap_strict(), min(), operator+(), operator<<(), operator==(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_3d(), plag_rflu_initsolutionrandom(), prep_modbcdistribution::profinflowvttaylorcyl(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_openprobefile(), rflu_modoles::rflu_buildstencilsoles(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modprobes::rflu_findprobecells(), rflu_initflowhardcode(), rflu_pickregionscoord(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modgeometrytools::rflu_testinboundbox(), rocflo_blocks(), and select_bbx().
 { return ptr->e1; }
Member Data Documentation
double _max[2] private
Definition at line 85 of file include/CGAL/Bbox_2.h.
Referenced by Bbox_2(), operator+=(), xmax(), and ymax().
double _min[2] private
Definition at line 85 of file include/CGAL/Bbox_2.h.
Referenced by Bbox_2(), operator+=(), xmin(), and ymin().
The documentation for this class was generated from the following files:
CGAL/include/CGAL/Bbox_2.h
include/CGAL/Bbox_2.h
Bbox_2.C