Rocstar: SegmentS3< FT > Class Template Reference
SegmentS3< FT > Class Template Reference
#include <SegmentS3.h>
Public Member Functions
SegmentS3 ()
SegmentS3 (const PointS3< FT > &sp, const PointS3< FT > &ep)
bool has_on (const PointS3< FT > &p) const
bool collinear_has_on (const PointS3< FT > &p) const
bool operator== (const SegmentS3< FT > &s) const
bool operator!= (const SegmentS3< FT > &s) const
PointS3< FT > start () const
PointS3< FT > end () const
PointS3< FT > source () const
PointS3< FT > target () const
PointS3< FT > min () const
PointS3< FT > max () const
PointS3< FT > vertex (int i) const
PointS3< FT > point (int i) const
PointS3< FT > operator[] (int i) const
FT squared_length () const
DirectionS3< FT > direction () const
LineS3< FT > supporting_line () const
SegmentS3 opposite () const
SegmentS3 transform (const Aff_transformationS3< FT > &t) const
bool is_degenerate () const
Bbox_3 bbox () const
Public Attributes
PointS3< FT > e0
PointS3< FT > e1
Detailed Description
template<class FT>
class SegmentS3< FT >
Definition at line 61 of file SegmentS3.h.
Constructor & Destructor Documentation
SegmentS3 () inline
Definition at line 63 of file SegmentS3.h.
 {}
SegmentS3 (const PointS3< FT > & sp, const PointS3< FT > & ep) inline
Definition at line 64 of file SegmentS3.h.
                    : e0(sp), e1(ep) {}
Member Function Documentation
Bbox_3 bbox () const inline
Definition at line 219 of file SegmentS3.h.
 { return source().bbox() + target().bbox(); }
bool collinear_has_on (const PointS3< FT > & p) const inline
Definition at line 258 of file SegmentS3.h.
References collinear_are_ordered_along_line().
 { return collinear_are_ordered_along_line(source(), p, target()); }
DirectionS3< FT > direction () const inline
Definition at line 184 of file SegmentS3.h.
 { return DirectionS3<FT>( target() - source() ); }
PointS3< FT > end () const
Definition at line 120 of file SegmentS3.h.
Referenced by LineS3< FT >::LineS3(), and PlaneS3< FT >::PlaneS3().
 { return e1; }
bool has_on (const PointS3< FT > & p) const
Definition at line 252 of file SegmentS3.h.
References are_ordered_along_line().
 { return are_ordered_along_line(source(), p, target()); }
bool is_degenerate () const inline
Definition at line 212 of file SegmentS3.h.
 { return source() == target(); }
PointS3< FT > max () const inline
Definition at line 147 of file SegmentS3.h.
References lexicographically_xyz_smaller().
 {
   return (lexicographically_xyz_smaller(source(),target())) ? target()
                                                             : source();
 }
PointS3< FT > min () const inline
Definition at line 137 of file SegmentS3.h.
References lexicographically_xyz_smaller().
 {
   return (lexicographically_xyz_smaller(source(),target())) ? source()
                                                             : target();
 }
bool operator!= (const SegmentS3< FT > & s) const inline
Definition at line 110 of file SegmentS3.h.
References s.
 { return !(*this == s); }
bool operator== (const SegmentS3< FT > & s) const inline
Definition at line 103 of file SegmentS3.h.
References SegmentS3< FT >::source(), and SegmentS3< FT >::target().
 { return (source() == s.source())  && (target() == s.target()); }
PointS3< FT > operator[] (int i) const inline
Definition at line 171 of file SegmentS3.h.
 { return vertex(i); }
SegmentS3< FT > opposite () const inline
Definition at line 198 of file SegmentS3.h.
 { return SegmentS3<FT>(target(), source()); }
PointS3< FT > point (int i) const inline
Definition at line 164 of file SegmentS3.h.
 { return (i%2 == 0) ? source() : target(); }
PointS3< FT > source () const
Definition at line 125 of file SegmentS3.h.
Referenced by SegmentS3< FT >::operator==().
 { return e0; }
FT squared_length () const inline
Definition at line 177 of file SegmentS3.h.
References squared_distance().
 { return squared_distance(target(), source()); }
PointS3< FT > start () const
Definition at line 115 of file SegmentS3.h.
Referenced by LineS3< FT >::LineS3(), and PlaneS3< FT >::PlaneS3().
 { return e0; }
LineS3< FT > supporting_line () const inline
Definition at line 191 of file SegmentS3.h.
 { return LineS3<FT>(*this); }
PointS3< FT > target () const
Definition at line 130 of file SegmentS3.h.
Referenced by SegmentS3< FT >::operator==().
 { return e1; }
SegmentS3< FT > transform (const Aff_transformationS3< FT > & t) const inline
Definition at line 205 of file SegmentS3.h.
References Aff_transformationS3< FT >::transform().
 { return SegmentS3<FT>(t.transform(source()), t.transform(target())); }
PointS3< FT > vertex (int i) const inline
Definition at line 157 of file SegmentS3.h.
 { return (i%2 == 0) ? source() : target(); }
Member Data Documentation
PointS3<FT> e0
Definition at line 96 of file SegmentS3.h.
PointS3<FT> e1
Definition at line 97 of file SegmentS3.h.
The documentation for this class was generated from the following file:
SegmentS3.h