Rocstar: Exponent Class Reference
Exponent Class Reference
#include <Exponent.hpp>
Public Types
typedef double(Exponent::* constMemberPtr)(double) const
typedef double(Exponent::* constMemberPtr)(double) const
Public Member Functions
Exponent ()
Exponent (double exponent)
double raise (double value) const
void set_exponent (double exponent)
Exponent & operator= (double d)
operator double () const
double pow0 (double x) const
double pow1 (double x) const
double squareRoot (double x) const
double cubeRoot (double x) const
double powTwoThirds (double x) const
double pow2 (double x) const
double powPositiveInt (double x) const
double std_pow (double x) const
double inverse (double x) const
double invSquareRoot (double x) const
double powThreeHalves (double x) const
double invSquare (double x) const
double powNegativeInt (double x) const
Exponent ()
Exponent (double exponent)
double raise (double value) const
void set_exponent (double exponent)
Exponent & operator= (double d)
operator double () const
double pow0 (double x) const
double pow1 (double x) const
double squareRoot (double x) const
double cubeRoot (double x) const
double powTwoThirds (double x) const
double pow2 (double x) const
double powPositiveInt (double x) const
double std_pow (double x) const
double inverse (double x) const
double invSquareRoot (double x) const
double powThreeHalves (double x) const
double invSquare (double x) const
double powNegativeInt (double x) const
Static Public Member Functions
static constMemberPtr get_func_ptr (double exponent)
static constMemberPtr get_func_ptr (double exponent)
Private Attributes
double mExponent
constMemberPtr funcPointer
Detailed Description
Definition at line 43 of file includeLinks/Exponent.hpp.
Member Typedef Documentation
typedef double(Exponent::* constMemberPtr)(double) const
Definition at line 47 of file includeLinks/Exponent.hpp.
typedef double(Exponent::* constMemberPtr)(double) const
Definition at line 47 of file src/Misc/Exponent.hpp.
Constructor & Destructor Documentation
Exponent () inline
Definition at line 50 of file includeLinks/Exponent.hpp.
                 : funcPointer( 0 )
       {}
Exponent (double exponent) inline
Definition at line 53 of file includeLinks/Exponent.hpp.
       : mExponent(exponent),
         funcPointer( get_func_ptr( exponent ) )
       {}
Exponent () inline
Definition at line 50 of file src/Misc/Exponent.hpp.
                 : funcPointer( 0 )
       {}
Exponent (double exponent) inline
Definition at line 53 of file src/Misc/Exponent.hpp.
       : mExponent(exponent),
         funcPointer( get_func_ptr( exponent ) )
       {}
Member Function Documentation
double cubeRoot (double x) const
Definition at line 85 of file Misc/Exponent.cpp.
References Mesquite::cbrt().
Referenced by Exponent::get_func_ptr().
 { return Mesquite::cbrt( x ); }
double cubeRoot (double x) const
Exponent::constMemberPtr get_func_ptr (double exponent) static
Definition at line 42 of file Misc/Exponent.cpp.
References Exponent::cubeRoot(), Exponent::inverse(), Exponent::invSquare(), Exponent::invSquareRoot(), Exponent::pow0(), Exponent::pow1(), Exponent::pow2(), Exponent::powNegativeInt(), Exponent::powPositiveInt(), Exponent::powThreeHalves(), Exponent::powTwoThirds(), Exponent::squareRoot(), and Exponent::std_pow().
Referenced by Exponent::set_exponent().
 {
   if (exponent == 0.0)
     return &Exponent::pow0;
   else if (exponent == 1.0)
     return &Exponent::pow1;
   else if (exponent == 0.5)
     return &Exponent::squareRoot;
   else if (exponent == 1./3.)
     return &Exponent::cubeRoot;
   else if (exponent == 2./3.)
     return &Exponent::powTwoThirds;
   else if (exponent == 2.0)
     return &Exponent::pow2;
   else if (exponent == -1.0)
     return &Exponent::inverse;
   else if (exponent == -0.5)
     return &Exponent::invSquareRoot;
   else if (exponent == 1.5)
     return &Exponent::powThreeHalves;
   else if (exponent == -2.0)
     return &Exponent::invSquare;
   else if (msq_stdc::floor(exponent) == exponent)
   {
     if (exponent > 0.0)
       return &Exponent::powPositiveInt;
     else
       return &Exponent::powNegativeInt;
   }
   else
     return &Exponent::std_pow;
 }
static constMemberPtr get_func_ptr (double exponent) static
double inverse (double x) const
double inverse (double x) const
Definition at line 88 of file Misc/Exponent.cpp.
References x.
Referenced by Exponent::get_func_ptr().
 { return 1.0 / x; }
double invSquare (double x) const
double invSquare (double x) const
Definition at line 91 of file Misc/Exponent.cpp.
References x.
Referenced by Exponent::get_func_ptr().
 { return 1.0 / (x*x); }
double invSquareRoot (double x) const
double invSquareRoot (double x) const
Definition at line 89 of file Misc/Exponent.cpp.
References sqrt().
Referenced by Exponent::get_func_ptr().
 { return 1.0 / msq_stdc::sqrt(x); }
operator double () const inline
Definition at line 66 of file includeLinks/Exponent.hpp.
References Exponent::mExponent.
       { return mExponent; }
operator double () const inline
Definition at line 66 of file src/Misc/Exponent.hpp.
References Exponent::mExponent.
       { return mExponent; }
Exponent& operator= (double d) inline
Definition at line 63 of file includeLinks/Exponent.hpp.
References Exponent::set_exponent().
       { set_exponent(d); return *this; }
Exponent& operator= (double d) inline
Definition at line 63 of file src/Misc/Exponent.hpp.
References Exponent::set_exponent().
       { set_exponent(d); return *this; }
double pow0 (double x) const
double pow0 (double x) const
Definition at line 81 of file Misc/Exponent.cpp.
Referenced by Exponent::get_func_ptr().
 { return 1.0;   }
double pow1 (double x) const
double pow1 (double x) const
Definition at line 82 of file Misc/Exponent.cpp.
References x.
Referenced by Exponent::get_func_ptr().
 { return x;     }
double pow2 (double x) const
double pow2 (double x) const
Definition at line 83 of file Misc/Exponent.cpp.
References x.
Referenced by Exponent::get_func_ptr().
 { return x * x; }
double powNegativeInt (double x) const
double powNegativeInt (double x) const
Definition at line 101 of file Misc/Exponent.cpp.
References i, Exponent::mExponent, and x.
Referenced by Exponent::get_func_ptr().
 {
   double result = x;
   for (int i = (-(int)mExponent) - 1; i > 0; --i)
     result *= x;
   return 1.0/result;
 }
double powPositiveInt (double x) const
Definition at line 93 of file Misc/Exponent.cpp.
References i, Exponent::mExponent, and x.
Referenced by Exponent::get_func_ptr().
 {
   double result = x;
   for (int i = (int)mExponent - 1; i > 0; --i)
     result *= x;
   return result;
 }
double powPositiveInt (double x) const
double powThreeHalves (double x) const
Definition at line 90 of file Misc/Exponent.cpp.
References sqrt().
Referenced by Exponent::get_func_ptr().
 { return x*x*x / msq_stdc::sqrt(x); }
double powThreeHalves (double x) const
double powTwoThirds (double x) const
Definition at line 86 of file Misc/Exponent.cpp.
References Mesquite::cbrt_sqr().
Referenced by Exponent::get_func_ptr().
 { return Mesquite::cbrt_sqr(x); }
double powTwoThirds (double x) const
double raise (double value) const inline
Definition at line 58 of file src/Misc/Exponent.hpp.
References Exponent::funcPointer.
       { return (this->*funcPointer)( value ); }
double raise (double value) const inline
Definition at line 58 of file includeLinks/Exponent.hpp.
References Exponent::funcPointer.
Referenced by Mesquite::pow().
       { return (this->*funcPointer)( value ); }
void set_exponent (double exponent)
Definition at line 75 of file Misc/Exponent.cpp.
References Exponent::funcPointer, Exponent::get_func_ptr(), and Exponent::mExponent.
Referenced by Exponent::operator=().
 {
   mExponent = exponent;
   funcPointer = get_func_ptr( exponent );
 }
void set_exponent (double exponent)
double squareRoot (double x) const
Definition at line 84 of file Misc/Exponent.cpp.
References sqrt().
Referenced by Exponent::get_func_ptr().
 { return msq_stdc::sqrt( x ); }
double squareRoot (double x) const
double std_pow (double x) const
double std_pow (double x) const
Definition at line 87 of file Misc/Exponent.cpp.
References Exponent::mExponent, and Mesquite::pow().
Referenced by Exponent::get_func_ptr().
 { return msq_stdc::pow( x, mExponent ); }
Member Data Documentation
constMemberPtr funcPointer private
Definition at line 86 of file includeLinks/Exponent.hpp.
Referenced by Exponent::raise(), and Exponent::set_exponent().
double mExponent private
Definition at line 85 of file includeLinks/Exponent.hpp.
Referenced by Exponent::operator double(), Exponent::powNegativeInt(), Exponent::powPositiveInt(), Exponent::set_exponent(), and Exponent::std_pow().
The documentation for this class was generated from the following files:
includeLinks/Exponent.hpp
Misc/Exponent.cpp