Rocstar: PatchDataMem< X > Class Template Reference
PatchDataMem< X > Class Template Reference
#include <PatchDataMem.hpp>
Public Types
typedef X * iterator
typedef const X * const_iterator
typedef X * iterator
typedef const X * const_iterator
Public Member Functions
PatchDataMem ()
PatchDataMem (size_t size)
PatchDataMem (const PatchDataMem< X > &)
~PatchDataMem ()
size_t size () const
bool empty () const
const X & operator[] (size_t index) const
X & operator[] (size_t index)
const X * to_array () const
X * to_array ()
void resize (size_t new_size)
void clear ()
PatchDataMem< X > & operator= (const PatchDataMem< X > &)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
PatchDataMem ()
PatchDataMem (size_t size)
PatchDataMem (const PatchDataMem< X > &)
~PatchDataMem ()
size_t size () const
bool empty () const
const X & operator[] (size_t index) const
X & operator[] (size_t index)
const X * to_array () const
X * to_array ()
void resize (size_t new_size)
void clear ()
PatchDataMem< X > & operator= (const PatchDataMem< X > &)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Private Types
enum { SHRINK_PERCENT = 10 }
enum { SHRINK_PERCENT = 10 }
Private Member Functions
void resize_storage (size_t size)
void resize_storage (size_t size)
Private Attributes
size_t arrayLength
size_t activeSize
X * arrayData
Detailed Description
template<typename X>
class Mesquite::PatchDataMem< X >
Definition at line 35 of file includeLinks/PatchDataMem.hpp.
Member Typedef Documentation
typedef const X* const_iterator
Definition at line 72 of file includeLinks/PatchDataMem.hpp.
typedef const X* const_iterator
Definition at line 72 of file src/Mesh/PatchDataMem.hpp.
typedef X* iterator
Definition at line 71 of file src/Mesh/PatchDataMem.hpp.
typedef X* iterator
Definition at line 71 of file includeLinks/PatchDataMem.hpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
SHRINK_PERCENT
Shink memory when used portion is less than this percent.
Definition at line 37 of file includeLinks/PatchDataMem.hpp.
        {
     SHRINK_PERCENT = 10
   };
anonymous enum private
Enumerator
SHRINK_PERCENT
Shink memory when used portion is less than this percent.
Definition at line 37 of file src/Mesh/PatchDataMem.hpp.
        {
     SHRINK_PERCENT = 10
   };
Constructor & Destructor Documentation
PatchDataMem () inline
Definition at line 80 of file includeLinks/PatchDataMem.hpp.
   : arrayLength(0),
     activeSize(0),
     arrayData(0)
   {}
PatchDataMem (size_t size) inline
Definition at line 87 of file includeLinks/PatchDataMem.hpp.
References PatchDataMem< X >::resize().
   : arrayLength(0),
     activeSize(0),
     arrayData(0)
   { resize( size ); }
PatchDataMem (const PatchDataMem< X > & other) inline
Definition at line 94 of file includeLinks/PatchDataMem.hpp.
References PatchDataMem< X >::operator=().
   : arrayLength(0),
     activeSize(0),
     arrayData(0)
   { operator=(other); }
~PatchDataMem () inline
Definition at line 101 of file includeLinks/PatchDataMem.hpp.
   { clear(); free( arrayData ); }
PatchDataMem () inline
PatchDataMem (size_t size) inline
PatchDataMem (const PatchDataMem< X > &) inline
~PatchDataMem () inline
Member Function Documentation
PatchDataMem< X >::iterator begin () inline
Definition at line 129 of file includeLinks/PatchDataMem.hpp.
Referenced by PatchData::generate_vertex_to_element_data().
   { return arrayData; }
iterator begin () inline
PatchDataMem< X >::const_iterator begin () const inline
Definition at line 133 of file includeLinks/PatchDataMem.hpp.
   { return arrayData; }
const_iterator begin () const inline
void clear () inline
Definition at line 187 of file includeLinks/PatchDataMem.hpp.
References i.
Referenced by PatchData::clear(), PatchData::initialize_data(), and PatchData::reorder().
 {
   for (size_t i = 0; i < activeSize; ++i)
     arrayData[i].~X();
   activeSize = 0;
 }
void clear () inline
bool empty () const inline
bool empty (void) const inline
Definition at line 125 of file includeLinks/PatchDataMem.hpp.
Referenced by PatchData::generate_vertex_to_element_data(), and PatchData::get_vertex_element_adjacencies().
   { return !activeSize; }
PatchDataMem< X >::iterator end () inline
Definition at line 137 of file includeLinks/PatchDataMem.hpp.
Referenced by PatchData::generate_vertex_to_element_data().
   { return arrayData + activeSize; }
iterator end () inline
PatchDataMem< X >::const_iterator end () const inline
Definition at line 141 of file includeLinks/PatchDataMem.hpp.
   { return arrayData + activeSize; }
const_iterator end () const inline
PatchDataMem< X > & operator= (const PatchDataMem< X > & other) inline
Definition at line 195 of file includeLinks/PatchDataMem.hpp.
References PatchDataMem< X >::activeSize, PatchDataMem< X >::arrayData, and i.
Referenced by PatchDataMem< X >::PatchDataMem().
 {
   clear();
   if (other.activeSize)
   {
     if (arrayLength < other.activeSize ||
         (SHRINK_PERCENT * other.activeSize) < arrayLength)
       resize_storage( other.activeSize );
     activeSize = other.activeSize;
     for (size_t i = 0; i < activeSize; ++i)
     {
       //arrayData[i].X( other.arrayData[i] );
       new (arrayData + i) X( other.arrayData[i] );
     }
   }
   return *this;
 }
PatchDataMem<X>& operator= (const PatchDataMem< X > &) inline
const X & operator[] (size_t index) const inline
Definition at line 117 of file includeLinks/PatchDataMem.hpp.
   { return arrayData[index]; }
const X& operator[] (size_t index) const inline
X & operator[] (size_t index) inline
Definition at line 121 of file includeLinks/PatchDataMem.hpp.
   { return arrayData[index]; }
X& operator[] (size_t index) inline
void resize (size_t new_size) inline
void resize (size_t new_size) inline
Definition at line 161 of file includeLinks/PatchDataMem.hpp.
References i.
Referenced by PatchData::allocate_storage(), PatchData::generate_vertex_to_element_data(), MeshSet::get_next_elem_on_vert_patch(), MeshSet::get_next_global_patch(), PatchData::get_subpatch(), PatchData::initialize_data(), and PatchDataMem< X >::PatchDataMem().
 {
   if (new_size > activeSize)
   {
     if (new_size > arrayLength)
       resize_storage( new_size );
     for (size_t i = activeSize; i < new_size; ++i)
     {
       //arrayData[i].X();
       new (arrayData + i) X();
     }
     activeSize = new_size;
   }
   else if (new_size < activeSize)
   {
     for (size_t i = new_size; i < activeSize; ++i)
       arrayData[i].~X();
     activeSize = new_size;
     if (activeSize && ((SHRINK_PERCENT*activeSize) < arrayLength))
       resize_storage( new_size );
   }
 }
void resize_storage (size_t size) inline private
Definition at line 145 of file includeLinks/PatchDataMem.hpp.
References i.
 {
   assert( new_size >= activeSize );
   X* new_array = (X*)malloc( sizeof(X) * new_size );
   for (size_t i = 0; i < activeSize; ++i)
   {
     //new_array[i].X( arrayData[i] );
     new (new_array + i) X( arrayData[i] );
     arrayData[i].~X();
   }
   free( arrayData );
   arrayData = new_array;
   arrayLength = new_size;
 }
void resize_storage (size_t size) inline private
size_t size () const inline
Definition at line 105 of file includeLinks/PatchDataMem.hpp.
Referenced by PatchData::generate_vertex_to_element_data(), MeshSet::get_next_global_patch(), PatchData::initialize_data(), Mesquite::operator<<(), and PatchData::reorder().
   { return activeSize; }
size_t size () const inline
const X* to_array () const inline
const X * to_array () const inline
Definition at line 109 of file includeLinks/PatchDataMem.hpp.
   { return arrayData; }
X * to_array () inline
Definition at line 113 of file includeLinks/PatchDataMem.hpp.
   { return arrayData; }
X* to_array () inline
Member Data Documentation
size_t activeSize private
Definition at line 44 of file includeLinks/PatchDataMem.hpp.
Referenced by PatchDataMem< X >::operator=().
X * arrayData private
Definition at line 45 of file includeLinks/PatchDataMem.hpp.
Referenced by PatchDataMem< X >::operator=().
size_t arrayLength private
Definition at line 43 of file includeLinks/PatchDataMem.hpp.
The documentation for this class was generated from the following file:
includeLinks/PatchDataMem.hpp