Rocstar: rocfracsubinterface Module Reference
rocfracsubinterface Module Reference
Public Member Functions
subroutine, public rocfracinterfaceinitial (glb, obtain_attr, surfIn)
subroutine, public rocfracinterfaceupdate (glb, CurrentTime, CurrentTimeStep, MAN_update_inbuff)
subroutine, public readsdv (glb, myid)
subroutine, public rocfracinterfaceinitial (glb, obtain_attr, surfIn)
subroutine, public rocfracinterfaceupdate (glb, CurrentTime, CurrentTimeStep, MAN_update_inbuff)
subroutine, public readsdv (glb, myid)
Detailed Description
Definition at line 54 of file RocFracSubInterface.f90.
Member Function/Subroutine Documentation
subroutine, public readsdv (type(rocfrac_global), pointer glb, integer myid)
Definition at line 624 of file RocFracSubInterface.f90.
subroutine, public readsdv (type(rocfrac_global), pointer glb, integer myid)
Definition at line 629 of file MP/Source/RocFracSubInterface.f90.
subroutine, public rocfracinterfaceinitial (type(rocfrac_global) glb, integer, intent(in) obtain_attr, character(*), intent(in) surfIn)
Definition at line 62 of file MP/Source/RocFracSubInterface.f90.
References Line_2< R, T >::a(), i, j, Attribute::pane(), Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
subroutine, public rocfracinterfaceinitial (type(rocfrac_global) glb, integer, intent(in) obtain_attr, character(*), intent(in) surfIn)
Definition at line 63 of file RocFracSubInterface.f90.
References Line_2< R, T >::a(), i, j, Attribute::pane(), and StopWatch::stop().
Referenced by rocfracmain::rocfracinitialize().
subroutine, public rocfracinterfaceupdate (type(rocfrac_global), pointer glb, real*8, intent(in) CurrentTime, real*8, intent(in) CurrentTimeStep, integer, intent(in) MAN_update_inbuff)
Definition at line 564 of file RocFracSubInterface.f90.
Referenced by rocfrac_load_module().
subroutine, public rocfracinterfaceupdate (type(rocfrac_global), pointer glb, real*8, intent(in) CurrentTime, real*8, intent(in) CurrentTimeStep, integer, intent(in) MAN_update_inbuff)
Definition at line 570 of file MP/Source/RocFracSubInterface.f90.
The documentation for this module was generated from the following file:
RocFracSubInterface.f90