Rocstar: rflu_modrocstaradmin Module Reference
rflu_modrocstaradmin Module Reference
Public Member Functions
subroutine, public rflu_genx_buildgridsurf (pRegion)
subroutine, public rflu_genx_buildpconn (pRegion)
subroutine, public rflu_genx_closerocinctrlfiles (global)
subroutine, public rflu_genx_createattrdisp (pRegion)
subroutine, public rflu_genx_createattrflow (pRegion)
subroutine, public rflu_genx_createattrgridsurf (pRegion)
subroutine, public rflu_genx_createattrgspeeds (pRegion)
subroutine, public rflu_genx_createattrinterf (pRegion)
subroutine, public rflu_genx_createattrstats (pRegion)
subroutine, public rflu_genx_createattrturb (pRegion)
subroutine, public rflu_genx_createattrwrapper (pRegion)
subroutine, public rflu_genx_createdatainterf (pRegion)
subroutine, public rflu_genx_creategridsurf (pRegion)
subroutine, public rflu_genx_createpconn (pRegion)
subroutine, public rflu_genx_createwindows (pRegion, communicator)
subroutine, public rflu_genx_createwindowsdone (pRegion)
subroutine, public rflu_genx_destroydatainterf (pRegion)
subroutine, public rflu_genx_destroygridsurf (pRegion)
subroutine, public rflu_genx_destroypconn (pRegion)
subroutine, public rflu_genx_hardcodewindowname (global)
subroutine, public rflu_genx_initrocman (pRegion, handle)
subroutine, public rflu_genx_readctrlfile (global)
subroutine, public rflu_genx_registerdataflow (pRegion)
subroutine, public rflu_genx_registerdatagspeeds (pRegion)
subroutine, public rflu_genx_registerdatainterf (pRegion)
subroutine, public rflu_genx_registerdatastats (pRegion)
subroutine, public rflu_genx_registerdataturb (pRegion)
subroutine, public rflu_genx_registerdatawrapper (pRegion)
subroutine, public rflu_genx_registerdisp (pRegion)
subroutine, public rflu_genx_registergrid (pRegion)
subroutine, public rflu_genx_registergridsurf (pRegion)
subroutine, public rflu_genx_registergridvol (pRegion)
subroutine, public rflu_genx_setconnsize (pRegion)
subroutine, public rflu_genx_storecommunicator (global, communicator)
subroutine, public rflu_genx_storenameshandles (global, surfWinNameInput, volWinNameInput, handleObtain)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModGENXAdmin.F90,v $ $Revision: 1.26 $'
Detailed Description
Definition at line 39 of file RFLU_ModRocstarAdmin.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_genx_buildgridsurf (type(t_region), pointer pRegion)
Definition at line 137 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modboundlists::rflu_buildbfaceloclists().
Referenced by rflupart().
subroutine, public rflu_genx_buildpconn (type(t_region), pointer pRegion)
Definition at line 225 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), and rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflupart().
subroutine, public rflu_genx_closerocinctrlfiles (type(t_global), pointer global)
Definition at line 484 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modrocstarutils::rflu_genx_buildtimestring().
Referenced by rflumap().
subroutine, public rflu_genx_createattrdisp (type(t_region), pointer pRegion)
Definition at line 581 of file RFLU_ModRocstarAdmin.F90.
Referenced by rflu_genx_createattrwrapper().
subroutine, public rflu_genx_createattrflow (type(t_region), pointer pRegion)
Definition at line 642 of file RFLU_ModRocstarAdmin.F90.
Referenced by rflu_genx_createattrwrapper(), and rfluinit().
subroutine, public rflu_genx_createattrgridsurf (type(t_region), pointer pRegion)
Definition at line 720 of file RFLU_ModRocstarAdmin.F90.
Referenced by rflu_genx_createattrwrapper(), rfluinit(), and rflupart().
subroutine, public rflu_genx_createattrgspeeds (type(t_region), pointer pRegion)
Definition at line 791 of file RFLU_ModRocstarAdmin.F90.
Referenced by rflu_genx_createattrwrapper(), rfluinit(), and rflupart().
subroutine, public rflu_genx_createattrinterf (type(t_region), pointer pRegion)
Definition at line 867 of file RFLU_ModRocstarAdmin.F90.
Referenced by rflu_genx_createattrwrapper(), and rfluinit().
subroutine, public rflu_genx_createattrstats (type(t_region), pointer pRegion)
Definition at line 962 of file RFLU_ModRocstarAdmin.F90.
References stat_rflu_modrocstaradmin::stat_rflu_genxcreateattr().
Referenced by rflu_genx_createattrwrapper().
subroutine, public rflu_genx_createattrturb (type(t_region), pointer pRegion)
Definition at line 1011 of file RFLU_ModRocstarAdmin.F90.
References turb_rflu_modrocstaradmin::turb_rflu_genxcreateattr().
Referenced by rflu_genx_createattrwrapper().
subroutine, public rflu_genx_createattrwrapper (type(t_region), pointer pRegion)
Definition at line 1060 of file RFLU_ModRocstarAdmin.F90.
References rflu_genx_createattrdisp(), rflu_genx_createattrflow(), rflu_genx_createattrgridsurf(), rflu_genx_createattrgspeeds(), rflu_genx_createattrinterf(), rflu_genx_createattrstats(), and rflu_genx_createattrturb().
Referenced by rflu_initflowsolver().
subroutine, public rflu_genx_createdatainterf (type(t_region), pointer pRegion)
Definition at line 1127 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modrocstartools::rflu_genx_initbflag().
Referenced by rflu_allocatememorywrapper().
subroutine, public rflu_genx_creategridsurf (type(t_region), pointer pRegion)
Definition at line 1405 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modboundlists::rflu_createbfaceloclists(), and rflu_modrocstarutils::rflu_genx_setcnstrtype().
Referenced by rflu_initflowsolver(), rfluinit(), and rflupart().
subroutine, public rflu_genx_createpconn (type(t_region), pointer pRegion)
Definition at line 1514 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), and rflupart().
subroutine, public rflu_genx_createwindows (type(t_region), pointer pRegion, integer, intent(in), optional communicator)
Definition at line 1674 of file RFLU_ModRocstarAdmin.F90.
References Function::communicator().
Referenced by rflu_initflowsolver(), rfluinit(), and rflupart().
subroutine, public rflu_genx_createwindowsdone (type(t_region), pointer pRegion)
Definition at line 1761 of file RFLU_ModRocstarAdmin.F90.
Referenced by rflu_initflowsolver().
subroutine, public rflu_genx_destroydatainterf (type(t_region), pointer pRegion)
Definition at line 1825 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
subroutine, public rflu_genx_destroygridsurf (type(t_region), pointer pRegion)
Definition at line 2023 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modboundlists::rflu_destroybfaceloclists().
Referenced by rfluinit(), and rflupart().
subroutine, public rflu_genx_destroypconn (type(t_region), pointer pRegion)
Definition at line 2129 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_genx_hardcodewindowname (type(t_global), pointer global)
Definition at line 2220 of file RFLU_ModRocstarAdmin.F90.
Referenced by rfluinit(), and rflupart().
subroutine, public rflu_genx_initrocman (type(t_region), pointer pRegion, integer, intent(in) handle)
Definition at line 2269 of file RFLU_ModRocstarAdmin.F90.
References MeshImplTags::handle().
Referenced by rflu_initflowsolver().
subroutine, public rflu_genx_readctrlfile (type(t_global), pointer global)
Definition at line 2348 of file RFLU_ModRocstarAdmin.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, max(), min(), moderror::registerfunction(), and Attribute::status().
Referenced by rflu_initflowsolver(), rfluinit(), rflumap(), and rflupart().
subroutine, public rflu_genx_registerdataflow (type(t_region), pointer pRegion)
Definition at line 2509 of file RFLU_ModRocstarAdmin.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_genx_registerdatawrapper(), and rfluinit().
subroutine, public rflu_genx_registerdatagspeeds (type(t_region), pointer pRegion)
Definition at line 2638 of file RFLU_ModRocstarAdmin.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_genx_registerdatawrapper(), and rfluinit().
subroutine, public rflu_genx_registerdatainterf (type(t_region), pointer pRegion)
Definition at line 2760 of file RFLU_ModRocstarAdmin.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_genx_registerdatawrapper().
subroutine, public rflu_genx_registerdatastats (type(t_region), pointer pRegion)
Definition at line 2907 of file RFLU_ModRocstarAdmin.F90.
References stat_rflu_modrocstaradmin::stat_rflu_genxregisterdata().
Referenced by rflu_genx_registerdatawrapper().
subroutine, public rflu_genx_registerdataturb (type(t_region), pointer pRegion)
Definition at line 2956 of file RFLU_ModRocstarAdmin.F90.
References turb_rflu_modrocstaradmin::turb_rflu_genxregisterdata().
Referenced by rflu_genx_registerdatawrapper().
subroutine, public rflu_genx_registerdatawrapper (type(t_region), pointer pRegion)
Definition at line 3005 of file RFLU_ModRocstarAdmin.F90.
References rflu_genx_registerdataflow(), rflu_genx_registerdatagspeeds(), rflu_genx_registerdatainterf(), rflu_genx_registerdatastats(), rflu_genx_registerdataturb(), and rflu_genx_registerdisp().
Referenced by rflu_initflowsolver().
subroutine, public rflu_genx_registerdisp (type(t_region), pointer pRegion)
Definition at line 3071 of file RFLU_ModRocstarAdmin.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_genx_registerdatawrapper().
subroutine, public rflu_genx_registergrid (type(t_region), pointer pRegion)
Definition at line 3157 of file RFLU_ModRocstarAdmin.F90.
References rflu_genx_registergridsurf(), and rflu_genx_registergridvol().
Referenced by rflupart().
subroutine, public rflu_genx_registergridsurf (type(t_region), pointer pRegion)
Definition at line 3243 of file RFLU_ModRocstarAdmin.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_genx_registergrid(), rflu_initflowsolver(), rfluinit(), and rflupart().
subroutine, public rflu_genx_registergridvol (type(t_region), pointer pRegion)
Definition at line 3435 of file RFLU_ModRocstarAdmin.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_genx_registergrid(), rflu_initflowsolver(), rfluinit(), and rflupart().
subroutine, public rflu_genx_setconnsize (type(t_region), pointer pRegion)
Definition at line 3611 of file RFLU_ModRocstarAdmin.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rfluinit().
subroutine, public rflu_genx_storecommunicator (type(t_global), pointer global, integer, intent(in) communicator)
Definition at line 3703 of file RFLU_ModRocstarAdmin.F90.
References Function::communicator().
Referenced by rflu_initflowsolver(), rfluinit(), and rflupart().
subroutine, public rflu_genx_storenameshandles (type(t_global), pointer global, character(*), intent(in) surfWinNameInput, character(*), intent(in) volWinNameInput, integer, intent(in) handleObtain)
Definition at line 3756 of file RFLU_ModRocstarAdmin.F90.
References moderror::errorstop().
Referenced by rflu_initflowsolver(), rfluinit(), and rflupart().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModGENXAdmin.F90,v $ $Revision: 1.26 $' private
Definition at line 103 of file RFLU_ModRocstarAdmin.F90.
The documentation for this module was generated from the following file:
RFLU_ModRocstarAdmin.F90