Rocstar: rflo_modmovegridutil Module Reference
rflo_modmovegridutil Module Reference
Public Member Functions
subroutine, public rflo_movegridqflatpatch (region, patch, iPatch)
subroutine, public rflo_movegridcurvedpatch (region, patch, iPatch)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModMoveGridUtil.F90,v $ $Revision: 1.5 $'
Detailed Description
Definition at line 39 of file RFLO_ModMoveGridUtil.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_movegridcurvedpatch (type(t_region) region, type(t_patch), pointer patch, integer iPatch)
Definition at line 276 of file RFLO_ModMoveGridUtil.F90.
References moderror::deregisterfunction(), ibeg, iend, jbeg, jend, kbeg, p1, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint2d(), s, and sqrt().
Referenced by rflo_modmovegridelliptglo::rflo_mgelliptbnddeformation().
subroutine, public rflo_movegridqflatpatch (type(t_region) region, type(t_patch), pointer patch, integer iPatch)
Definition at line 89 of file RFLO_ModMoveGridUtil.F90.
References moderror::deregisterfunction(), moderror::errorstop(), ibeg, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint1d(), s, and sqrt().
Referenced by rflo_modmovegridelliptglo::rflo_mgelliptbnddeformation().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModMoveGridUtil.F90,v $ $Revision: 1.5 $' private
Definition at line 62 of file RFLO_ModMoveGridUtil.F90.
The documentation for this module was generated from the following file:
RFLO_ModMoveGridUtil.F90