Rocstar: Aff_transformation_repS2< FT > Class Template Reference
Aff_transformation_repS2< FT > Class Template Reference
#include <Aff_transformationS2.h>
Public Member Functions
Aff_transformation_repS2 ()
Aff_transformation_repS2 (const FT &m11, const FT &m12, const FT &m21, const FT &m22)
Aff_transformation_repS2 (const FT &m11, const FT &m12, const FT &m13, const FT &m21, const FT &m22, const FT &m23)
~Aff_transformation_repS2 ()
PointS2< FT > transform (const PointS2< FT > &p) const
VectorS2< FT > transform (const VectorS2< FT > &v) const
DirectionS2< FT > transform (const DirectionS2< FT > &dir) const
Aff_transformationS2< FT > inverse () const
Aff_transformationS2< FT > operator* (const Aff_transformation_rep_baseS2< FT > &t)
Aff_transformationS2< FT > compose (const Translation_repS2< FT > &t) const
virtual Aff_transformationS2< FT > compose (const Rotation_repS2< FT > &t) const
virtual Aff_transformationS2< FT > compose (const Scaling_repS2< FT > &t) const
virtual Aff_transformationS2< FT > compose (const Aff_transformation_repS2< FT > &t) const
virtual bool is_even () const
virtual FT cartesian (int i, int j) const
virtual std::ostream & print (std::ostream &os) const
Public Member Functions inherited from Aff_transformation_rep_baseS2< FT >
virtual ~Aff_transformation_rep_baseS2 ()
Private Attributes
FT t11
FT t12
FT t13
FT t21
FT t22
FT t23
Friends
class Translation_repS2< FT >
class Rotation_repS2< FT >
class Scaling_repS2< FT >
class Aff_transformationS2< FT >
Additional Inherited Members
Protected Member Functions inherited from Leda_like_rep
Leda_like_rep ()
virtual ~Leda_like_rep ()
Protected Attributes inherited from Leda_like_rep
int count
Detailed Description
template<class FT>
class Aff_transformation_repS2< FT >
Definition at line 80 of file Aff_transformationS2.h.
Constructor & Destructor Documentation
Aff_transformation_repS2 () inline
Definition at line 139 of file Aff_transformationS2.h.
   {}
Aff_transformation_repS2 (const FT & m11, const FT & m12, const FT & m21, const FT & m22) inline
Definition at line 142 of file Aff_transformationS2.h.
     : t11(m11), t12(m12), t13(0),
       t21(m21), t22(m22), t23(0)
   {}
Aff_transformation_repS2 (const FT & m11, const FT & m12, const FT & m13, const FT & m21, const FT & m22, const FT & m23) inline
Definition at line 148 of file Aff_transformationS2.h.
     : t11(m11), t12(m12), t13(m13),
       t21(m21), t22(m22), t23(m23)
   {}
~Aff_transformation_repS2 () inline
Definition at line 154 of file Aff_transformationS2.h.
   {}
Member Function Documentation
virtual FT cartesian (int i, int j) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 251 of file Aff_transformationS2.h.
References Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, and Aff_transformation_repS2< FT >::t23.
   {
     switch (i)
     {
     case 0: switch (j)
             {
               case 0: return t11;
               case 1: return t12;
               case 2: return t13;
             }
     case 1: switch (j)
             {
               case 0: return t21;
               case 1: return t22;
               case 2: return t23;
             }
     case 2: switch (j)
             {
               case 0: return FT(0);
               case 1: return FT(0);
               case 2: return FT(1);
             }
     }
     return FT(0);
   }
Aff_transformationS2<FT> compose (const Translation_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 204 of file Aff_transformationS2.h.
References Translation_repS2< FT >::_translationvector, Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, and Aff_transformation_repS2< FT >::t23.
   {
     return Aff_transformationS2<FT>(t11,
                                     t12,
                                     t13 + t._translationvector.x(),
                                     t21,
                                     t22,
                                     t23 + t._translationvector.y());
   }
virtual Aff_transformationS2<FT> compose (const Rotation_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 214 of file Aff_transformationS2.h.
References Rotation_repS2< FT >::_cosinus, Rotation_repS2< FT >::_sinus, Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, and Aff_transformation_repS2< FT >::t23.
   {
     return Aff_transformationS2<FT>(t._cosinus*t11 - t._sinus*t21,
                                     t._cosinus*t12 - t._sinus*t22,
                                     t._cosinus*t13 - t._sinus*t23,
                                     t._sinus*t11 + t._cosinus*t21,
                                     t._sinus*t12 + t._cosinus*t22,
                                     t._sinus*t13 + t._cosinus*t23);
   }
virtual Aff_transformationS2<FT> compose (const Scaling_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 224 of file Aff_transformationS2.h.
References Scaling_repS2< FT >::_scalefactor, Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, and Aff_transformation_repS2< FT >::t23.
   {
      return Aff_transformationS2<FT>(t._scalefactor * t11,
                                      t._scalefactor * t12,
                                      t._scalefactor * t13,
                                      t._scalefactor * t21,
                                      t._scalefactor * t22,
                                      t._scalefactor * t23);
   }
virtual Aff_transformationS2<FT> compose (const Aff_transformation_repS2< FT > & t) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 234 of file Aff_transformationS2.h.
References Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, and Aff_transformation_repS2< FT >::t23.
   {
     return Aff_transformationS2<FT>(t.t11*t11 + t.t12*t21,
                                     t.t11*t12 + t.t12*t22,
                                     t.t11*t13 + t.t12*t23 + t.t13,
                                     t.t21*t11 + t.t22*t21,
                                     t.t21*t12 + t.t22*t22,
                                     t.t21*t13 + t.t22*t23 + t.t23 );
   }
Aff_transformationS2<FT> inverse () const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 180 of file Aff_transformationS2.h.
References Mesquite::det(), Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, and Aff_transformation_repS2< FT >::t23.
   {
     FT det = FT(1) / (t11 * t22 - t12 * t21);
     return Aff_transformationS2<FT>(
       det * t22,    det * (-t12), det * (t12*t23-t13*t22),
       det * (-t21), det * t11 ,   det * (t13*t21-t11*t23));
   }
virtual bool is_even () const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 246 of file Aff_transformationS2.h.
References POSITIVE, sign_of_determinant2x2(), Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t21, and Aff_transformation_repS2< FT >::t22.
   {
     return sign_of_determinant2x2(t11, t12, t21, t22) == POSITIVE;
   }
Aff_transformationS2<FT> operator* (const Aff_transformation_rep_baseS2< FT > & t) inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 198 of file Aff_transformationS2.h.
References Aff_transformation_rep_baseS2< FT >::compose().
   {
     return t.compose(*this);
   }
virtual std::ostream& print (std::ostream & os) const inline virtual
Definition at line 277 of file Aff_transformationS2.h.
References Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, and Aff_transformation_repS2< FT >::t23.
Referenced by a_d_tensors(), ainv(), apn_input_0d(), arruda_boyce(), arruda_boyce_cauchy(), burn_initialize(), m_rocburn_1d_apn::check_alloc(), m_rocburn_1d_zn::check_alloc(), m_rocburn_2d::check_alloc(), compositestiffnes(), createk(), createm(), cst_coh(), element_sub(), eshelby(), feminp(), glbthermcap(), glbthermstiff(), setup_py::grid(), heat_transfer_sub(), homogenizedmat(), implicit_initialize(), implicit_soln(), implicit_v3d8_mass_consistent(), implicit_v3d8_me_k(), updatestructuralsoln::internalforce_v3d10(), invert2(), linked_list2::list_procelemlist(), locthermcap_v3d8(), locthermstiff_v3d8(), matmodel_elastic(), matmodel_hyperelastic(), matous_const_model(), matvol_sub(), mesh2d(), mesh2doverlay(), meshsoft_sub(), micromechanical_sub(), newcommlist(), newton(), partition_ceff(), plag_allocatememorypost(), plag_binsortnozzleinlet(), plag_binsortspatialdist(), plag_cecellsexchange(), plag_cecellsrecvdata(), plag_cecellssendsize(), plag_corncellsloaddata(), plag_corncellsloadsendbuff(), plag_edgecellsloaddata(), plag_edgecellsloadsendbuff(), plag_modinjection::plag_invokeconsrandejec(), plag_processeulerfield(), plag_readsolutionfilepost(), plag_readstatpost(), plag_writestattecascii(), read_io_files(), read_patran(), readinp(), readsdv(), rflo_modforcesmoments::rflo_openforcemomcofile(), rflo_openprobefile(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rocburn_load_module(), rocfracmain::rocfracinitialize(), rocfracsubinterface::rocfracinterfaceinitial(), rocfracprep(), rocfracmain::rocfracsoln(), rockout_8node(), scale_mesh(), solve_x(), testconst(), thermal_initialize(), thermal_soln(), tractpressload(), v3d10_capacitance(), v3d10_mass(), v3d4(), v3d4_capacitance(), v3d4_mass(), v3d4_nl_arruda_boyce(), v3d4_thermalexp(), v3d4_thermalexp2(), v3d4n_mass(), vol_elem_mat_matous(), volratio(), write_output_2(), zn(), zn_calc_burning_rate(), zn_gen_grid(), zn_input_0d(), and zn_sswsb().
   {
     os << "Aff_transformationS2(" << t11 << " " << t12 << " " << t13 << std::endl;
     os << "                     " << t21 << " " << t22 << " " << t23 << ")";
     return os;
   }
PointS2<FT> transform (const PointS2< FT > & p) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 157 of file Aff_transformationS2.h.
References Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t13, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, Aff_transformation_repS2< FT >::t23, PointS2< FT >::x(), and PointS2< FT >::y().
   {
     return PointS2<FT>(t11 * p.x() + t12 * p.y() + t13,
                        t21 * p.x() + t22 * p.y() + t23);
   }
VectorS2<FT> transform (const VectorS2< FT > & v) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 165 of file Aff_transformationS2.h.
References Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, VectorS2< FT >::x(), and VectorS2< FT >::y().
   {
     return VectorS2<FT>(t11 * v.x() + t12 * v.y(),
                         t21 * v.x() + t22 * v.y());
   }
DirectionS2<FT> transform (const DirectionS2< FT > & dir) const inline virtual
Implements Aff_transformation_rep_baseS2< FT >.
Definition at line 173 of file Aff_transformationS2.h.
References Aff_transformation_repS2< FT >::t11, Aff_transformation_repS2< FT >::t12, Aff_transformation_repS2< FT >::t21, Aff_transformation_repS2< FT >::t22, v, DirectionS2< FT >::vector(), VectorS2< FT >::x(), and VectorS2< FT >::y().
   {
     VectorS2<FT> v = dir.vector();
     return DirectionS2<FT>(t11 * v.x() + t12 * v.y(),
                            t21 * v.x() + t22 * v.y());
   }
Friends And Related Function Documentation
friend class Aff_transformationS2< FT > friend
Definition at line 135 of file Aff_transformationS2.h.
friend class Rotation_repS2< FT > friend
Definition at line 133 of file Aff_transformationS2.h.
friend class Scaling_repS2< FT > friend
Definition at line 134 of file Aff_transformationS2.h.
friend class Translation_repS2< FT > friend
Definition at line 132 of file Aff_transformationS2.h.
Member Data Documentation
FT t11 private
Definition at line 285 of file Aff_transformationS2.h.
Referenced by Aff_transformation_repS2< FT >::cartesian(), Aff_transformation_repS2< FT >::compose(), Translation_repS2< FT >::compose(), Rotation_repS2< FT >::compose(), Scaling_repS2< FT >::compose(), Aff_transformation_repS2< FT >::inverse(), Aff_transformation_repS2< FT >::is_even(), Aff_transformation_repS2< FT >::print(), and Aff_transformation_repS2< FT >::transform().
FT t12 private
Definition at line 285 of file Aff_transformationS2.h.
Referenced by Aff_transformation_repS2< FT >::cartesian(), Aff_transformation_repS2< FT >::compose(), Translation_repS2< FT >::compose(), Rotation_repS2< FT >::compose(), Scaling_repS2< FT >::compose(), Aff_transformation_repS2< FT >::inverse(), Aff_transformation_repS2< FT >::is_even(), Aff_transformation_repS2< FT >::print(), and Aff_transformation_repS2< FT >::transform().
FT t13 private
Definition at line 285 of file Aff_transformationS2.h.
Referenced by Aff_transformation_repS2< FT >::cartesian(), Aff_transformation_repS2< FT >::compose(), Translation_repS2< FT >::compose(), Rotation_repS2< FT >::compose(), Scaling_repS2< FT >::compose(), Aff_transformation_repS2< FT >::inverse(), Aff_transformation_repS2< FT >::print(), and Aff_transformation_repS2< FT >::transform().
FT t21 private
Definition at line 286 of file Aff_transformationS2.h.
Referenced by Aff_transformation_repS2< FT >::cartesian(), Aff_transformation_repS2< FT >::compose(), Translation_repS2< FT >::compose(), Rotation_repS2< FT >::compose(), Scaling_repS2< FT >::compose(), Aff_transformation_repS2< FT >::inverse(), Aff_transformation_repS2< FT >::is_even(), Aff_transformation_repS2< FT >::print(), and Aff_transformation_repS2< FT >::transform().
FT t22 private
Definition at line 286 of file Aff_transformationS2.h.
Referenced by Aff_transformation_repS2< FT >::cartesian(), Aff_transformation_repS2< FT >::compose(), Translation_repS2< FT >::compose(), Rotation_repS2< FT >::compose(), Scaling_repS2< FT >::compose(), Aff_transformation_repS2< FT >::inverse(), Aff_transformation_repS2< FT >::is_even(), Aff_transformation_repS2< FT >::print(), and Aff_transformation_repS2< FT >::transform().
FT t23 private
Definition at line 286 of file Aff_transformationS2.h.
Referenced by Aff_transformation_repS2< FT >::cartesian(), Aff_transformation_repS2< FT >::compose(), Translation_repS2< FT >::compose(), Rotation_repS2< FT >::compose(), Scaling_repS2< FT >::compose(), Aff_transformation_repS2< FT >::inverse(), Aff_transformation_repS2< FT >::print(), and Aff_transformation_repS2< FT >::transform().
The documentation for this class was generated from the following file:
Aff_transformationS2.h