Rocstar: ComLineObject Class Reference
ComLineObject Class Reference
Command line processing.
#include <ComLine.H>
Public Member Functions
ComLineObject ()
Default constructor.
ComLineObject (const char *args[])
Constructor.
ComLineObject (ComLineObject &incom)
Copy constructor.
void Copy (ComLineObject &incom)
Copy method.
int ProcessCommandLine (const char *args[])
One fell swoop processing of command line.
std::string GetRawComLine () const
Raw Command Line Access.
void SetRawComLine (const std::string &incl)
Raw Command Line Access.
int ProcessOptions ()
Processes all command line tokens.
void Record (const char *args[])
Minimal recording of command line.
void AddOption (char s, const std::string &l, int=0)
User interface to describe simple option.
void AddOption (char s, const std::string &l, int, const std::string argname)
User interface to describe option with argument.
void AddArgument (const std::string &a, int reqd=0)
User interface to describe an application argument.
void AddArgHelp (const std::string &a, const std::string &help)
Specify the usage info for application argument.
void SetArgName (const std::string opstr, const std::string argname)
Specify name of an option argument.
void SetArgName (char s, const std::string &argname)
Specify name of an option argument.
void AddHelp (char s, const std::string &help)
Specify usage for an option.
void AddHelp (const std::string &l, const std::string &help)
Specify usage for an option.
std::string GetOpStringByType (int mintype, int maxtype)
Obtains option strings by type.
std::string GetHelp (char s)
Obtain the usage string for an option.
std::string GetHelp (const std::string &l)
Obtain the usage string for an option.
char GetShort (const std::string &l)
Obtain the short one char option from the long word version.
std::string GetLong (const char &s)
Obtain the long word option from the short char version.
std::string ShortUsage ()
Generate short usage string.
std::string LongUsage ()
Generate long usage string.
std::string GetOption (const char &s)
Get the value of an option.
std::string GetOption (const std::string &l)
Get the value of an option.
std::string ErrorReport ()
Error reporting.
std::string ProgramName () const
Program name access.
std::vector< std::string > GetArgs () const
Argument access.
void SetDescription (const std::string &desc)
Set description string.
void SetNotes (const std::string &notes)
Set notes string.
void WriteRC (std::ostream &Ostr) const
Write an RC string that can be used for config.
void ReadRC (const std::string &RCString)
Read a config from RC string.
template<typename NumType >
void ProcessRange (NumType &t1, NumType &t2, const std::string stinter)
Process a range in the format "t1:t2".
template<typename NumType >
void ResolveOption (NumType &t2, const std::string stinter)
Resolve an option (i.e.
virtual void Initialize (void)
virtual function for program specific Initialization.
virtual ~ComLineObject ()
Protected Attributes
std::string _description
application description.
std::string _notes
Notes to be displayed at the end of LongUsage().
std::string _program_name
the name of the program
std::string _line
unformatted command line
std::vector< std::string > _error_messages
stores error messages
std::vector< std::string > _nonops
stores non-option arguments
std::map< char, std::string > _options
stores the value of each option
std::map< char, std::string > _help
stores the help string for each op
std::map< char, std::string > _argname
stores a name for arguments
std::map< char, int > _type
stores the type of option
std::vector< std::pair
< std::string, int > > _args
application arguments;
std::map< std::string,
std::string > _arghelp
help string for args
Friends
std::ostream & operator<< (std::ostream &Out, const ComLineObject &cl)
std::istream & operator>> (std::istream &In, ComLineObject &cl)
Additional Inherited Members
Public Attributes inherited from vector< T >
T elements
STL member.
Detailed Description
Command line processing.
Provides a quick and easy way to deal with the arguments coming into an application from the command line. Several useful methods for parsing the command line tokens and generation of detailed usage information are provided for the application.
Command line tokens are separated into three kinds. The zeroth kind is the first command line token which is the name of the program as it was invoked on the command line. This token is stripped of any absolute path information and stored. The first kind are options. Any command line token which begins with a "-" is interpreted as an option. There are several types of options:
Type 0) A simple flag.
Type 1) May accept an option argument. An option argument is the command line token immediatly following the option token.
Type 2) Requires an option argument.
Type 3) Non-optional option. Application requires this option to function.
Option usage is summarized by the following table.
Type Description Usage Value
0 simple flag -t .true.
1 argument optional -t or -t [arg] .true. or [arg]
2 argument required -t <arg> <arg>
3 required w/arg -t <arg> <arg>
The second kind of command line tokens are arguments to the application. These kind of tokens are simply all the tokens not used up in the processing of the zeroth and first kinds of command line tokens. A mechanism for specifying whether these kind of tokens are required or optional is also provided.
Definition at line 60 of file ComLine.H.
Constructor & Destructor Documentation
ComLineObject () inline
Default constructor.
Definition at line 98 of file ComLine.H.
 {};
ComLineObject (const char * args[]) inline
Constructor.
Typically, args comes directly from argv. One must be careful about environments in which extra arguments are stored in argv. A good example is MPI. MPI_Init(&argc,&argv) should be invoked before any ComLineObject is constructed.
Definition at line 107 of file ComLine.H.
References ComLineObject::Record().
       {
         Record(args);
       };
ComLineObject (ComLineObject & incom)
Copy constructor.
Definition at line 123 of file ComLine.C.
References ComLineObject::Copy().
     {
       Copy(incom);
     };
virtual ~ComLineObject () inline virtual
Definition at line 381 of file ComLine.H.
 {};
Member Function Documentation
void AddArgHelp (const std::string & a, const std::string & help) inline
Specify the usage info for application argument.
This function is provided for the specification of the usage information for application arguments. This is called after the argument has been set by AddArgument(...). The string specified in "help" string is displayed in the output of LongUsage().
Definition at line 192 of file ComLine.H.
References ComLineObject::_arghelp.
Referenced by FlotsamComLine::Initialize(), DDFComLine::Initialize(), TestComLine::Initialize(), ProfaneComLine::Initialize(), ExampleProgramComLine::Initialize(), and DriverProgramComLine::Initialize().
       {
         _arghelp[a] = help;
       };
void AddArgument (const std::string & a, int reqd = 0) inline
User interface to describe an application argument.
This function is provided for the specification of an argument to the application (i.e. a non-option argument), and whether the argument is required for the application to function. The function arguments are the name of the argument, and an integer which is > 0 for required application arguments.
Definition at line 179 of file ComLine.H.
References ComLineObject::_args.
Referenced by FlotsamComLine::Initialize(), DDFComLine::Initialize(), TestComLine::Initialize(), ProfaneComLine::Initialize(), ExampleProgramComLine::Initialize(), and DriverProgramComLine::Initialize().
       {
         _args.push_back(std::make_pair<std::string,int>(a,reqd));
       };
void AddHelp (char s, const std::string & help) inline
Specify usage for an option.
Function is used to set the usage string for an option which is displayed in the output of LongUsage().
Definition at line 222 of file ComLine.H.
References ComLineObject::_help, and s.
Referenced by FlotsamComLine::Initialize(), RTSComLine::Initialize(), DDFComLine::Initialize(), TestComLine::Initialize(), ProfaneComLine::Initialize(), CheckResultsComLine::Initialize(), ExampleProgramComLine::Initialize(), and DriverProgramComLine::Initialize().
 { _help[s] = help;};
void AddHelp (const std::string & l, const std::string & help) inline
Specify usage for an option.
Function is used to set the usage string for an option which is displayed in the output of LongUsage().
Definition at line 229 of file ComLine.H.
References ComLineObject::_help, and ComLineObject::GetShort().
       {
         _help[GetShort(l)] = help;
       };
void AddOption (char s, const std::string & l, int atype = 0)
User interface to describe simple option.
This function is provided for the specification of a simple option. The arguments are the short, single letter option, the long "word" version, and the type of the option. If the option is of the type which may have or requires an argument itself, then the argument will be given the default name, "arg".
Definition at line 295 of file ComLine.C.
References ComLineObject::_argname, ComLineObject::_help, ComLineObject::_options, ComLineObject::_type, and s.
Referenced by FlotsamComLine::Initialize(), RTSComLine::Initialize(), DDFComLine::Initialize(), TestComLine::Initialize(), ProfaneComLine::Initialize(), CheckResultsComLine::Initialize(), ExampleProgramComLine::Initialize(), and DriverProgramComLine::Initialize().
     {
       this->push_back(std::make_pair<char,std::string>(s,l));
       _options[s] = std::string("");
       _type[s] = atype;
       if(atype > 0)
         _argname[s] = "arg";
       _help[s] = std::string("");
     }
void AddOption (char s, const std::string & l, int type, const std::string argname)
User interface to describe option with argument.
This function is provided for the specification of an option along with a name for it's argument. Argument names are useful for the generation of usage information to the user. The arguments are the short, single letter option, the long "word" version, the type, and the argument name.
Definition at line 305 of file ComLine.C.
References ComLineObject::_argname, ComLineObject::_help, ComLineObject::_options, ComLineObject::_type, and s.
     {
       this->push_back(std::make_pair<char,std::string>(s,l));
       _options[s] = std::string("");
       _type[s] = type;
       _argname[s] = argname;
       _help[s] = std::string("");
     }
void Copy (ComLineObject & incom)
Copy method.
Definition at line 128 of file ComLine.C.
References ComLineObject::_arghelp, ComLineObject::_argname, ComLineObject::_args, ComLineObject::_description, ComLineObject::_error_messages, ComLineObject::_help, ComLineObject::_line, ComLineObject::_nonops, ComLineObject::_notes, ComLineObject::_options, ComLineObject::_program_name, and ComLineObject::_type.
Referenced by ComLineObject::ComLineObject().
     {
       _description.erase();
       _notes.erase();
       _program_name.erase();
       _line.erase();
       _error_messages.resize(0);
       _nonops.resize(0);
       _options.clear();
       _help.clear();
       _argname.clear();
       _type.clear();
       _args.resize(0);
       _arghelp.clear();
       this->resize(0);
       _description.assign(incom._description);
       _notes.assign(incom._notes);
       _program_name.assign(incom._program_name);
       _line.assign(incom._line);
       std::vector<std::string>::iterator ici = incom._error_messages.begin();
       while(ici != incom._error_messages.end())
         _error_messages.push_back(*ici++);
       ici = incom._nonops.begin();
       while(ici != incom._nonops.end())
         _nonops.push_back(*ici++);
       std::map<char,std::string>::iterator icmi = incom._options.begin();
       while(icmi != incom._options.end()){
         _options[icmi->first] = icmi->second;
         icmi++;
       }
       icmi = incom._help.begin();
       while(icmi != incom._help.end()){
         _help[icmi->first] = icmi->second;
         icmi++;
       }
       icmi = incom._argname.begin();
       while(icmi != incom._argname.end()){
         _argname[icmi->first] = icmi->second;
         icmi++;
       }
       std::map<char,int>::iterator icti = incom._type.begin();
       while(icti != incom._type.end()){
         _type[icti->first] = icti->second;
         icti++;
       }
       std::vector<std::pair<std::string,int> >::iterator icai = incom._args.begin();
       while(icai != incom._args.end())
         _args.push_back(*icai++);
       std::map<std::string,std::string>::iterator icahi = incom._arghelp.begin();
       while(icahi != incom._arghelp.end()){
         _arghelp[icahi->first] = icahi->second;
         icahi++;
       }
       ComLineObject::iterator cli = incom.begin();
       while(cli != incom.end())
         this->push_back(*cli++);
     };
std::string ErrorReport ()
Error reporting.
Returns a report of the errors encountered in the ProcessOptions() function.
Definition at line 470 of file ComLine.C.
References ComLineObject::_error_messages, ComLineObject::_program_name, and IRAD::Util::DumpContents().
Referenced by IRAD::DiffDataFiles(), TestProgram::Initialize(), main(), Rocstar::ParallelTest(), GridConversion::ParallelTest(), IRAD::Profiler::Profane(), IRAD::RunTest(), Rocstar::Test(), and GridConversion::Test().
     {
       std::ostringstream Ostr;
       Ostr << _program_name << " command line errors: " << std::endl;
       Util::DumpContents(Ostr,_error_messages);
       return(Ostr.str());
     }
std::vector<std::string> GetArgs () const inline
Argument access.
Definition at line 309 of file ComLine.H.
References ComLineObject::_nonops.
Referenced by IRAD::DiffDataFiles(), main(), and IRAD::Profiler::Profane().
 { return _nonops;};
std::string GetHelp (char s) inline
Obtain the usage string for an option.
Definition at line 243 of file ComLine.H.
References ComLineObject::_help.
 {return(_help[s]);};
std::string GetHelp (const std::string & l) inline
Obtain the usage string for an option.
Definition at line 247 of file ComLine.H.
References ComLineObject::_help, and ComLineObject::GetShort().
 {return(_help[GetShort(l)]);};
std::string GetLong (const char & s)
Obtain the long word option from the short char version.
Definition at line 221 of file ComLine.C.
Referenced by ComLineObject::ProcessOptions().
     {
       std::vector<std::pair<char,std::string> >::iterator ti = this->begin();
       while(ti != this->end()){
         if(ti->first == s)
           return(ti->second);
         ti++;
       }
       return("");
     }
std::string GetOpStringByType (int mintype, int maxtype)
Obtains option strings by type.
Internal utility function for building a string of option characters which are of a certain type.
Definition at line 232 of file ComLine.C.
References ComLineObject::_type.
Referenced by ComLineObject::ShortUsage().
     {
       std::ostringstream Ostr;
       std::vector<std::pair<char,std::string> >::iterator oi = this->begin();
       while(oi != this->end()){
         if(_type[oi->first] >= mintype && _type[oi->first] <= maxtype)
           Ostr << oi->first;
         oi++;
       }
       return(Ostr.str());
     }
std::string GetOption (const char & s) inline
Get the value of an option.
Returns the value of the specified option. If the option has not been set on the command line, then the value will be an empty string.
Definition at line 286 of file ComLine.H.
References ComLineObject::_options.
Referenced by IRAD::Util::CheckResults(), IRAD::DiffDataFiles(), TestProgram::Initialize(), main(), GridConversion::ParallelTest(), Rocstar::ParallelTest(), ComLineObject::ProcessOptions(), IRAD::Profiler::Profane(), IRAD::RunTest(), Rocstar::Test(), and GridConversion::Test().
 {return(_options[s]);};
std::string GetOption (const std::string & l) inline
Get the value of an option.
Returns the value of the specified option. If the option has not been set on the command line, then the value will be an empty string.
Definition at line 294 of file ComLine.H.
References ComLineObject::_options, and ComLineObject::GetShort().
 {return(_options[GetShort(l)]);};
std::string GetRawComLine () const inline
Raw Command Line Access.
Definition at line 130 of file ComLine.H.
References ComLineObject::_line, and ComLineObject::_program_name.
 { return (_program_name+std::string(" ")+_line);};
char GetShort (const std::string & l)
Obtain the short one char option from the long word version.
Definition at line 284 of file ComLine.C.
Referenced by ComLineObject::AddHelp(), ComLineObject::GetHelp(), ComLineObject::GetOption(), ComLineObject::ProcessOptions(), and ComLineObject::SetArgName().
     {
       std::vector<std::pair<char,std::string> >::iterator ti = this->begin();
       while(ti != this->end()){
         if(ti->second == l)
           return(ti->first);
         ti++;
       }
       return('\0');
     };
virtual void Initialize (void) inline virtual
virtual function for program specific Initialization.
Reimplemented in DriverProgramComLine, ExampleProgramComLine, CheckResultsComLine, ProfaneComLine, TestComLine, DDFComLine, TestComLine, TestComLine, RTSComLine, and FlotsamComLine.
Definition at line 380 of file ComLine.H.
 {};
std::string LongUsage ()
Generate long usage string.
Generates a long usage string similar to what one would see in the typical UNIX man-like description. Each option is shown with it's short and long version, along with usage information for each option and argument if such information has been specified with AddHelp, or AddArgHelp, respectively. Note that the format of this usage string follows the convention that optional quantities are enclosed in []'s while required quantities are enclosed in <>'s.
Definition at line 188 of file ComLine.C.
References ComLineObject::_arghelp, ComLineObject::_argname, ComLineObject::_args, ComLineObject::_description, ComLineObject::_help, ComLineObject::_notes, ComLineObject::_program_name, ComLineObject::_type, and ComLineObject::ShortUsage().
Referenced by IRAD::Util::CheckResults(), IRAD::DiffDataFiles(), TestProgram::Initialize(), main(), GridConversion::ParallelTest(), Rocstar::ParallelTest(), IRAD::Profiler::Profane(), IRAD::RunTest(), GridConversion::Test(), and Rocstar::Test().
     {
       std::ostringstream Ostr;
       if(!_description.empty())
         Ostr << _description << std::endl << std::endl;
       Ostr << _program_name << " Usage: " << std::endl
            << std::endl << ShortUsage() << std::endl << std::endl;
       std::vector<std::pair<char,std::string> >::const_iterator ti = this->begin();
       while(ti != this->end()){
         Ostr << "\t" << "-" << ti->first << ",--" << ti->second
              << (_type[ti->first] > 0 ? (_type[ti->first]==1 ? " [" : " <") : "")
              << _argname[ti->first]
              << (_type[ti->first] > 0 ? (_type[ti->first]==1 ? "]" : ">") : "")
              << std::endl << "\t\t" << _help[ti->first];
         ti++;
         if(ti != this->end())
           Ostr << std::endl << std::endl;
       }
       Ostr << std::endl << std::endl;
       std::vector<std::pair<std::string,int> >::const_iterator ai = _args.begin();
       while(ai != _args.end()){
         Ostr << "\t" << (ai->second ? "<" : "[") << ai->first
              << (ai->second ? ">" : "]") << std::endl << "\t\t"
              << _arghelp[ai->first];
         ai++;
         if(ai != _args.end())
           Ostr << std::endl << std::endl;
       }
       if(!_notes.empty())
         Ostr << std::endl << _notes;
       return(Ostr.str());
     }
int ProcessCommandLine (const char * args[]) inline
One fell swoop processing of command line.
Definition at line 122 of file ComLine.H.
References ComLineObject::ProcessOptions(), and ComLineObject::Record().
       {
         Record(args);
         return(ProcessOptions());
       };
int ProcessOptions ()
Processes all command line tokens.
This function examines all the command line tokens, sorts them into their respective types, and assigns their values. The number of errors encountered during processing is returned.
Definition at line 327 of file ComLine.C.
References ComLineObject::_argname, ComLineObject::_args, ComLineObject::_error_messages, ComLineObject::_line, ComLineObject::_nonops, ComLineObject::_options, ComLineObject::_type, ComLineObject::GetLong(), ComLineObject::GetOption(), ComLineObject::GetShort(), and IRAD::Util::TokenizeString().
Referenced by IRAD::Util::CheckResults(), IRAD::DiffDataFiles(), main(), GridConversion::ParallelTest(), Rocstar::ParallelTest(), ComLineObject::ProcessCommandLine(), IRAD::Profiler::Profane(), IRAD::RunTest(), GridConversion::Test(), and Rocstar::Test().
     {
       bool end_of_ops = false;
       int errs = 0;
       std::vector<std::string> args;
       TokenizeString(args,_line);
       std::vector<std::string>::iterator ai = args.begin();
       while(ai != args.end()){
         std::string this_argument = *ai++;
         std::string next_argument;
         if(ai != args.end())
           next_argument = *ai--;
         std::string::iterator si = this_argument.begin();
         if(*si == '-' && !end_of_ops){
           si++;
           if(si == this_argument.end())
             end_of_ops = true;
           if(*si != '-') { // then we are processing a short option
             while(si != this_argument.end()){
               char flag_char = *si++;
               std::vector<std::pair<char,std::string> >::iterator oi = this->begin();
               bool found = false;
               while((oi != this->end()) && !found){
                 if(flag_char == oi->first){
                   found = true;
                   if(si == this_argument.end()){  // means it's not a string of flags
                     if(_type[flag_char] != 0){
                       if(!next_argument.empty() && next_argument[0] != '-'){
                         _options[flag_char] = next_argument;
                         ai++;
                       }
                       else if(_type[flag_char] > 1){ // next arg wasn't valid, err if reqd
                         errs++;
                         std::ostringstream Ostr;
                         Ostr << "Option -" << flag_char << " requires an argument.";
                         _error_messages.push_back(Ostr.str());
                       }
                       else
                         _options[flag_char] = ".true.";
                     }
                     else
                       _options[flag_char] = ".true.";
                   }
                   else{ // it's a string of flags
                     if(_type[flag_char] > 1){ // it requires an argument, can't be in a flag string
                       errs++;
                       std::ostringstream Ostr;
                       Ostr << "Option -" << flag_char << " requires an argument.";
                       _error_messages.push_back(Ostr.str());
                     }
                     else
                       _options[flag_char] = ".true.";
                   }
                 }
                 oi++;
               }
               if(!found){
                 errs++;
                 std::ostringstream Ostr;
                 Ostr << "Option -" << flag_char << " is unrecognized.";
                 _error_messages.push_back(Ostr.str());
               }
             }
           }
           else { // we are processing a long option
             std::string opstring = this_argument.substr(2);
             char flag_char = GetShort(opstring);
             if(flag_char != '\0'){
               if(_type[flag_char] != 0){
                 if(!next_argument.empty() && next_argument[0] != '-'){
                   _options[flag_char] = next_argument;
                   ai++;
                 }
                 else if(_type[flag_char] > 1){
                   errs++;
                   std::ostringstream Ostr;
                   Ostr << "Option --" << GetLong(flag_char)
                        << " requires an argument.";
                   _error_messages.push_back(Ostr.str());
                 }
                 else
                   _options[flag_char] = ".true.";
               }
               else
                 _options[flag_char] = ".true.";
             }
             else{
               errs++;
               std::ostringstream Ostr;
               Ostr << "Option --" << opstring << " is unrecognized.";
               _error_messages.push_back(Ostr.str());
             }
           }
         }
         else { // non option arguments
           _nonops.push_back(this_argument);
         }
         if(ai != args.end())
           ai++;
       }
       // After finished parsing all arguments, go back and determine
       // whether any required input was missing.
       //
       // First, process the options
       std::vector<std::pair<char,std::string> >::iterator oi = this->begin();
       while(oi != this->end()){
         if(GetOption(oi->first).empty() && _type[oi->first]==3){
           errs++;
           std::ostringstream Ostr;
           Ostr << "Required option: -" << oi->first << ",--" << oi->second
                << " <" << _argname[oi->first] << "> was not specified.";
           _error_messages.push_back(Ostr.str());
         }
         oi++;
       }
       // Next, make sure there were enough nonop args
       unsigned int nreqd_args = 0;
       std::vector<std::pair<std::string,int> >::iterator aai = _args.begin();
       while(aai != _args.end()){
         if(aai->second > 0)
           nreqd_args++;
         aai++;
       }
       if(nreqd_args > _nonops.size()){
         errs++;
         std::ostringstream Ostr;
         Ostr << "Missing required arguments.";
         _error_messages.push_back(Ostr.str());
       }
       return(errs);
     }
void ProcessRange (NumType & t1, NumType & t2, const std::string stinter) inline
Process a range in the format "t1:t2".
Definition at line 330 of file ComLine.H.
References x.
Referenced by IRAD::Util::CheckResults().
       {
         if(!stinter.empty()){
           std::string::size_type x = stinter.find(":");
           std::string t1s = stinter;
           std::string t2s = stinter;
           if(x != std::string::npos){
             t1s = stinter.substr(0,x);
             t2s = stinter.substr(x+1);
             if(!t2s.empty()){
               std::istringstream Istr(t2s);
               Istr >> t2;
             }
           }
           else {
             t1s.erase();
           }
           if(!t1s.empty()){
             std::istringstream Istr(t1s);
             Istr >> t1;
           }
           if(!t2s.empty()){
             std::istringstream Istr(t2s);
             Istr >> t2;
           }
         }
       };
std::string ProgramName () const inline
Program name access.
Definition at line 305 of file ComLine.H.
References ComLineObject::_program_name.
Referenced by main(), and IRAD::Profiler::Profane().
 { return _program_name;};
void ReadRC (const std::string & RCString)
Read a config from RC string.
Definition at line 479 of file ComLine.C.
 {return;}
void Record (const char * args[])
Minimal recording of command line.
This function simply parses the command line to extract the executble name and record the full command line in a string.
Definition at line 314 of file ComLine.C.
References ComLineObject::_line, ComLineObject::_program_name, i, and IRAD::Util::stripdirs().
Referenced by ComLineObject::ComLineObject(), and ComLineObject::ProcessCommandLine().
     {
       int i = 1;
       std::ostringstream Ostr;
       _program_name.assign(stripdirs(args[0]));
       while(args[i]){
         Ostr << args[i++];
         if(args[i])
           Ostr << " ";
       }
       _line.assign(Ostr.str());
     }
void ResolveOption (NumType & t2, const std::string stinter) inline
Resolve an option (i.e.
obtain it's "value").
Definition at line 362 of file ComLine.H.
       {
         if(stinter == ".true." || stinter == ".TRUE."){
           t2 = 1;
           return;
         }
         if(stinter == ".false." || stinter == ".FALSE."){
           t2 = 0;
           return;
         }
         if(!stinter.empty()){
           std::istringstream Istr(stinter);
           Istr >> t2;
         }
       };
void SetArgName (const std::string opstr, const std::string argname) inline
Specify name of an option argument.
Function is used to set the argument name for an option if the option can use an argument.
Definition at line 202 of file ComLine.H.
References ComLineObject::_argname, and ComLineObject::GetShort().
       {
         _argname[GetShort(opstr)] = argname;
       };
void SetArgName (char s, const std::string & argname) inline
Specify name of an option argument.
Function is used to set the argument name for an option if the option can use an argument.
Definition at line 212 of file ComLine.H.
References ComLineObject::_argname, and s.
       {
         _argname[s] = argname;
       };
void SetDescription (const std::string & desc) inline
Set description string.
Definition at line 313 of file ComLine.H.
References ComLineObject::_description.
 { _description.assign(desc); };
void SetNotes (const std::string & notes) inline
Set notes string.
Definition at line 317 of file ComLine.H.
References ComLineObject::_notes.
 { _notes.assign(notes); };
void SetRawComLine (const std::string & incl)
Raw Command Line Access.
Definition at line 459 of file ComLine.C.
References ComLineObject::_line, and ComLineObject::_program_name.
     {
       std::istringstream Istr(incl);
       Istr >> _program_name;
       std::string token;
       Istr >> _line;
       while(Istr >> token)
         _line += (std::string(" ")+token);
     }
std::string ShortUsage ()
Generate short usage string.
Generates a short usage string similar to what one would see in the typical short command line usage output for a UNIX command. Note that the format of this usage string follows the convention that optional quantities are enclosed in []'s while required quantities are enclosed in <>'s.
Definition at line 244 of file ComLine.C.
References ComLineObject::_argname, ComLineObject::_args, ComLineObject::_program_name, ComLineObject::_type, and ComLineObject::GetOpStringByType().
Referenced by IRAD::DiffDataFiles(), TestProgram::Initialize(), ComLineObject::LongUsage(), main(), GridConversion::ParallelTest(), Rocstar::ParallelTest(), IRAD::Profiler::Profane(), IRAD::RunTest(), Rocstar::Test(), and GridConversion::Test().
     {
       std::ostringstream Ostr;
       std::string flagstring = GetOpStringByType(0,0);
       Ostr << _program_name << " ";
       if(!flagstring.empty())
         Ostr << "[-" << flagstring << "] ";
       std::string optionals = GetOpStringByType(1,2);
       if(!optionals.empty()){
         std::string::iterator oi = optionals.begin();
         Ostr << "[";
         while(oi != optionals.end()){
           Ostr << "-" << *oi
                << (_type[*oi] == 1 ? " [" : " <")
                << _argname[*oi]
                << (_type[*oi] == 1 ? "] " : "> ");
           oi++;
         }
         Ostr << "] ";
       }
       std::string reqd = GetOpStringByType(3,3);
       if(!reqd.empty()){
         std::string::iterator oi = reqd.begin();
         Ostr << "<";
         while(oi != reqd.end()){
           Ostr << "-" << *oi << " <" << _argname[*oi]
                << "> ";
           oi++;
         }
         Ostr << "> ";
       }
       std::vector<std::pair<std::string,int> >::iterator ai = _args.begin();
       while(ai != _args.end()){
         Ostr << (ai->second > 0 ? "<" : "[") << ai->first
              << (ai->second > 0 ? "> ": "] ");
         ai++;
       }
       return(Ostr.str());
     };
void WriteRC (std::ostream & Ostr) const
Write an RC string that can be used for config.
Definition at line 478 of file ComLine.C.
 {return;}
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & Out, const ComLineObject & cl) friend
Definition at line 86 of file ComLine.C.
     {
       if(!cl._description.empty())
         Out << "<description>\n" << cl._description << "</description>\n";
       Out << "<options>\n";
       ComLineObject::const_iterator cli = cl.begin();
       while(cli != cl.end()){
         char opchar = cli->first;
         std::map<char,int>::const_iterator ti = cl._type.find(opchar);
         Out << cli->first << " " << cli->second << " "
             << (ti == cl._type.end() ? 0 : ti->second);
         if(ti != cl._type.end()){
           std::map<char,std::string>::const_iterator ai = cl._argname.find(opchar);
           Out << " " << (ai == cl._argname.end() ? "(unspecified)" : ai->second);
         }
         std::map<char,std::string>::const_iterator hi = cl._help.find(opchar);
         Out << "\n<help>\n" << (hi == cl._help.end() ? "(unspecified)" : hi->second)
             << "\n</help>\n";
         cli++;
       }
       Out << "</options>\n";
       if(!cl._args.empty()){
         Out << "<arguments>\n";
         std::vector<std::pair<std::string,int> >::const_iterator ai = cl._args.begin();
         while(ai != cl._args.end()){
           std::map<std::string,std::string>::const_iterator ahi = cl._arghelp.find(ai->first);
           Out << ai->first << " " << ai->second
               << "\n<help>\n" << (ahi == cl._arghelp.end() ? "(unspecified)" : ahi->second)
               << "\n</help>\n";
           ai++;
         }
         Out << "</arguments>\n";
       }
       return(Out);
     }
std::istream& operator>> (std::istream & In, ComLineObject & cl) friend
Definition at line 14 of file ComLine.C.
     {
       std::string line;
       std::string::size_type x;
       line = Util::GetNextContent(In);
       x = line.find("<description>");
       if(x != std::string::npos){
         Util::GetContentUntil(In,cl._description,"</description>");
         line = Util::GetNextContent(In);
       }
       x = line.find("<options>");
       if(x == std::string::npos){
         cl._error_messages.push_back("Config file format error - options section misplaced?.");
         return(In);
       }
       std::string options_content;
       Util::GetContentUntil(In,options_content,"</options>");
       std::istringstream Istr(options_content);
       while(std::getline(Istr,line)){
         std::istringstream OpIn(line);
         std::string token;
         char opchar;
         int optype;
         OpIn >> opchar;
         OpIn >> token;
         OpIn >> optype;
         cl.push_back(std::make_pair(opchar,token));
         cl._type[opchar] = optype;
         if(optype > 0){
           std::string token;
           OpIn >> token;
           cl._argname[opchar] = token;
         }
         std::getline(Istr,line);
         x = line.find("<help>");
         if(x == std::string::npos){
           cl._error_messages.push_back("Configuration input format error in option help section.");
           return(In);
         }
         cl._help[opchar] = "";
         Util::GetContentUntil(Istr,cl._help[opchar],"</help>");
       }
       line = Util::GetNextContent(In);
       if(line.empty())
         return(In);
       x = line.find("<arguments>");
       if(x == std::string::npos){
         cl._error_messages.push_back("Configuration intput format error in argument section.");
         return(In);
       }
       std::string argsection;
       Util::GetContentUntil(In,argsection,"</arguments>");
       Istr.str(argsection);
       while(std::getline(Istr,line)){
         std::istringstream ArgIn(line);
         std::string argname;
         int argtype;
         ArgIn >> argname >> argtype;
         cl._arghelp[argname] = argtype;
         std::string tag;
         ArgIn >> tag;
         std::string::size_type x = tag.find("<help>");
         if(x == std::string::npos){
           cl._error_messages.push_back("Configuration input format error in arghelp section.");
           return(In);
         }
         cl._arghelp[argname] = "";
         Util::GetContentUntil(In,cl._arghelp[argname],"</help>");
       }
       return(In);
     }
Member Data Documentation
std::map<std::string,std::string> _arghelp protected
help string for args
Definition at line 93 of file ComLine.H.
Referenced by ComLineObject::AddArgHelp(), ComLineObject::Copy(), ComLineObject::LongUsage(), IRAD::Util::operator<<(), and IRAD::Util::operator>>().
std::map<char,std::string> _argname protected
stores a name for arguments
Definition at line 87 of file ComLine.H.
Referenced by ComLineObject::AddOption(), ComLineObject::Copy(), ComLineObject::LongUsage(), IRAD::Util::operator<<(), IRAD::Util::operator>>(), ComLineObject::ProcessOptions(), ComLineObject::SetArgName(), and ComLineObject::ShortUsage().
std::vector<std::pair<std::string,int> > _args protected
application arguments;
Definition at line 91 of file ComLine.H.
Referenced by ComLineObject::AddArgument(), ComLineObject::Copy(), ComLineObject::LongUsage(), IRAD::Util::operator<<(), ComLineObject::ProcessOptions(), and ComLineObject::ShortUsage().
std::string _description protected
application description.
This description will be dumped as the first section of the output of LongUsage().
Definition at line 71 of file ComLine.H.
Referenced by ComLineObject::Copy(), FlotsamComLine::Initialize(), RTSComLine::Initialize(), DDFComLine::Initialize(), TestComLine::Initialize(), ProfaneComLine::Initialize(), CheckResultsComLine::Initialize(), ExampleProgramComLine::Initialize(), DriverProgramComLine::Initialize(), ComLineObject::LongUsage(), IRAD::Util::operator<<(), IRAD::Util::operator>>(), and ComLineObject::SetDescription().
std::vector<std::string> _error_messages protected
stores error messages
Definition at line 79 of file ComLine.H.
Referenced by ComLineObject::Copy(), ComLineObject::ErrorReport(), IRAD::Util::operator>>(), and ComLineObject::ProcessOptions().
std::map<char,std::string> _help protected
stores the help string for each op
Definition at line 85 of file ComLine.H.
Referenced by ComLineObject::AddHelp(), ComLineObject::AddOption(), ComLineObject::Copy(), ComLineObject::GetHelp(), ComLineObject::LongUsage(), IRAD::Util::operator<<(), and IRAD::Util::operator>>().
std::string _line protected
unformatted command line
Definition at line 77 of file ComLine.H.
Referenced by ComLineObject::Copy(), ComLineObject::GetRawComLine(), ComLineObject::ProcessOptions(), ComLineObject::Record(), and ComLineObject::SetRawComLine().
std::vector<std::string> _nonops protected
stores non-option arguments
Definition at line 81 of file ComLine.H.
Referenced by ComLineObject::Copy(), ComLineObject::GetArgs(), and ComLineObject::ProcessOptions().
std::string _notes protected
Notes to be displayed at the end of LongUsage().
Definition at line 73 of file ComLine.H.
Referenced by ComLineObject::Copy(), ComLineObject::LongUsage(), and ComLineObject::SetNotes().
std::map<char,std::string> _options protected
stores the value of each option
Definition at line 83 of file ComLine.H.
Referenced by ComLineObject::AddOption(), ComLineObject::Copy(), ComLineObject::GetOption(), and ComLineObject::ProcessOptions().
std::string _program_name protected
the name of the program
Definition at line 75 of file ComLine.H.
Referenced by ComLineObject::Copy(), ComLineObject::ErrorReport(), ComLineObject::GetRawComLine(), ComLineObject::LongUsage(), ComLineObject::ProgramName(), ComLineObject::Record(), ComLineObject::SetRawComLine(), and ComLineObject::ShortUsage().
std::map<char,int> _type protected
stores the type of option
Definition at line 89 of file ComLine.H.
Referenced by ComLineObject::AddOption(), ComLineObject::Copy(), ComLineObject::GetOpStringByType(), ComLineObject::LongUsage(), IRAD::Util::operator<<(), IRAD::Util::operator>>(), ComLineObject::ProcessOptions(), and ComLineObject::ShortUsage().
The documentation for this class was generated from the following files:
ComLine.H
ComLine.C