Rocstar: rflo_modmovegridframe Module Reference
rflo_modmovegridframe Module Reference
Public Member Functions
subroutine, public rflo_movegridframe (regions)
subroutine, public rflo_mgframecornpoints (regions)
subroutine, public rflo_mgframebroadcast (regions, iselect, iter)
subroutine, public rflo_mgframesrchneighbors (regions)
subroutine rflo_mgframecorrectneighbors (regions)
subroutine rflo_mgframemovecorners (regions)
subroutine rflo_mgframesurfaces (regions, someMoved, iType)
subroutine rflo_mgframerestoreexternal (region)
subroutine rflo_mgframeedges (region, iType, boundMoved, allExternal, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframeinterfaces (regions, iType)
subroutine rflo_mgframebnddeformation (region, boundMoved, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine, public rflo_movegridframe (regions)
subroutine, public rflo_mgframecornpoints (regions)
subroutine, public rflo_mgframebroadcast (regions, iselect, iter)
subroutine, public rflo_mgframesrchneighbors (regions)
subroutine rflo_mgframecorrectneighbors (regions)
subroutine rflo_mgframemovecorners (regions)
subroutine rflo_mgframeorthoshift (regions)
subroutine rflo_mgframesurfaces (regions, someMoved, iType)
subroutine rflo_mgframerestoreexternal (region)
subroutine rflo_mgframeedgeso (region, iType, boundMoved, allExternal, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframeedges (region, edgeMoved, xyzOld, dNode)
subroutine rflo_mgframeinterfaces (regions, iType)
subroutine rflo_mgframebnddeformation0 (region, boundMoved, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframebnddeformation (region, xyzOld, dNode)
subroutine, public rflo_movegridframe (regions)
subroutine, public rflo_mgframecornpoints (regions)
subroutine, public rflo_mgframebroadcast (regions, iselect, iter)
subroutine, public rflo_mgframesrchneighbors (regions)
subroutine rflo_mgframecorrectneighbors (regions)
subroutine rflo_mgframemovecorners (regions)
subroutine rflo_mgframesurfaces (regions, someMoved, iType)
subroutine rflo_mgframerestoreexternal (region)
subroutine rflo_mgframeedgeso (region, iType, boundMoved, allExternal, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframeedges (region, edgeMoved, xyzOld, dNode)
subroutine rflo_mgframeinterfaces (regions, iType)
subroutine rflo_mgframebnddeformation (region, boundMoved, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine, public rflo_movegridframe (regions)
subroutine, public rflo_mgframecornpoints (regions)
subroutine, public rflo_mgframebroadcast (regions, iselect, iter)
subroutine, public rflo_mgframesrchneighbors (regions)
subroutine rflo_mgframecorrectneighbors (regions)
subroutine rflo_mgframemovecorners (regions)
subroutine rflo_mgframesurfaces (regions, someMoved, iType)
subroutine rflo_mgframerestoreexternal (region)
subroutine rflo_mgframeedgeso (region, iType, boundMoved, allExternal, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframeedges (region, edgeMoved, xyzOld, dNode)
subroutine rflo_mgframeinterfaces (regions, iType)
subroutine rflo_mgframebnddeformation0 (region, boundMoved, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframebnddeformation (region, xyzOld, dNode)
subroutine, public rflo_movegridframe (regions)
subroutine, public rflo_mgframecornpoints (regions)
subroutine, public rflo_mgframebroadcast (regions, iselect, iter)
subroutine, public rflo_mgframesrchneighbors (regions)
subroutine rflo_mgframecorrectneighbors (regions)
subroutine rflo_mgframemovecorners (regions)
subroutine rflo_mgframeorthoshift (regions)
subroutine rflo_mgframesurfaces (regions, someMoved, iType)
subroutine rflo_mgframerestoreexternal (region)
subroutine rflo_mgframeedgeso (region, iType, boundMoved, allExternal, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframeedges (region, edgeMoved, xyzOld, dNode)
subroutine rflo_mgframeinterfaces (regions, iType)
subroutine rflo_mgframebnddeformation0 (region, boundMoved, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframebnddeformation (region, xyzOld, dNode)
subroutine, public rflo_movegridframe (regions)
subroutine, public rflo_mgframecornpoints (regions)
subroutine, public rflo_mgframebroadcast (regions, iselect, iter)
subroutine, public rflo_mgframesrchneighbors (regions)
subroutine rflo_mgframecorrectneighbors (regions)
subroutine rflo_mgframemovecorners (regions)
subroutine rflo_mgframeorthoshift (regions)
subroutine rflo_mgframesurfaces (regions, someMoved, iType)
subroutine rflo_mgframerestoreexternal (region)
subroutine rflo_mgframeedgeso (region, iType, boundMoved, allExternal, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframeedges (region, edgeMoved, xyzOld, dNode)
subroutine rflo_mgframeinterfaces (regions, iType)
subroutine rflo_mgframebnddeformation0 (region, boundMoved, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
subroutine rflo_mgframebnddeformation (region, xyzOld, dNode)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModMoveGridConform.F90,v $ $Revision: 1.33 $'
Detailed Description
Definition at line 69 of file RFLO_ModMoveGridConform.F90.
Member Function/Subroutine Documentation
subroutine rflo_mgframebnddeformation (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 1986 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, p1, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint2d(), s, and sqrt().
Referenced by rflo_mgframeinterfaces(), and rflo_mgframesurfaces().
subroutine rflo_mgframebnddeformation (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 2764 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, p1, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint2d(), s, and sqrt().
subroutine rflo_mgframebnddeformation (type(t_region) region, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 3571 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), ibeg, iend, jbeg, jend, kbeg, p1, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint2d(), s, and sqrt().
subroutine rflo_mgframebnddeformation (type(t_region) region, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 3421 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), ibeg, iend, jbeg, jend, kbeg, p1, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint2d(), s, and sqrt().
subroutine rflo_mgframebnddeformation (type(t_region) region, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 3601 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), ibeg, iend, jbeg, jend, kbeg, p1, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint2d(), s, and sqrt().
subroutine rflo_mgframebnddeformation (type(t_region) region, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 3276 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), ibeg, iend, jbeg, jend, kbeg, p1, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint2d(), s, and sqrt().
subroutine rflo_mgframebnddeformation0 (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 3202 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, p1, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint2d(), s, and sqrt().
subroutine rflo_mgframebnddeformation0 (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 3382 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, p1, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint2d(), s, and sqrt().
subroutine rflo_mgframebnddeformation0 (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 3057 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, p1, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint2d(), s, and sqrt().
subroutine rflo_mgframebnddeformation0 (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 3352 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, p1, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint2d(), s, and sqrt().
subroutine, public rflo_mgframebroadcast (type(t_region), dimension(:), pointer regions, integer iselect, integer iter)
Definition at line 617 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_initgridprocedures(), rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), rflo_mgframeorthoshift(), and rflo_mgframesurfaces().
subroutine, public rflo_mgframebroadcast (type(t_region), dimension(:), pointer regions, integer iselect, integer iter)
Definition at line 637 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
subroutine, public rflo_mgframebroadcast (type(t_region), dimension(:), pointer regions, integer iselect, integer iter)
Definition at line 629 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
subroutine, public rflo_mgframebroadcast (type(t_region), dimension(:), pointer regions, integer iselect, integer iter)
Definition at line 674 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
subroutine, public rflo_mgframebroadcast (type(t_region), dimension(:), pointer regions, integer iselect, integer iter)
Definition at line 658 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
subroutine, public rflo_mgframebroadcast (type(t_region), dimension(:), pointer regions, integer iselect, integer iter)
Definition at line 628 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
subroutine, public rflo_mgframecornpoints (type(t_region), dimension(:), pointer regions)
Definition at line 363 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), ibeg, iend, ipnbeg, ipnend, jbeg, jend, jpnbeg, jpnend, kbeg, kpnbeg, max(), moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine, public rflo_mgframecornpoints (type(t_region), dimension(:), pointer regions)
Definition at line 369 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), ibeg, iend, ipnbeg, ipnend, jbeg, jend, jpnbeg, jpnend, kbeg, kpnbeg, max(), moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine, public rflo_mgframecornpoints (type(t_region), dimension(:), pointer regions)
Definition at line 386 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), ibeg, iend, ipnbeg, ipnend, jbeg, jend, jpnbeg, jpnend, kbeg, kpnbeg, max(), moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine, public rflo_mgframecornpoints (type(t_region), dimension(:), pointer regions)
Definition at line 368 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), ibeg, iend, ipnbeg, ipnend, jbeg, jend, jpnbeg, jpnend, kbeg, kpnbeg, max(), moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine, public rflo_mgframecornpoints (type(t_region), dimension(:), pointer regions)
Definition at line 384 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), ibeg, iend, ipnbeg, ipnend, jbeg, jend, jpnbeg, jpnend, kbeg, kpnbeg, max(), moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine, public rflo_mgframecornpoints (type(t_region), dimension(:), pointer regions)
Definition at line 398 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), ibeg, iend, ipnbeg, ipnend, jbeg, jend, jpnbeg, jpnend, kbeg, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
Referenced by rflo_initgridprocedures().
subroutine rflo_mgframecorrectneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 1238 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ic, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getnodeoffset(), and sqrt().
subroutine rflo_mgframecorrectneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 1284 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ic, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getnodeoffset(), and sqrt().
subroutine rflo_mgframecorrectneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 1117 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ic, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getnodeoffset(), and sqrt().
Referenced by rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), and rflo_mgframesurfaces().
subroutine rflo_mgframecorrectneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 1172 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ic, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getnodeoffset(), and sqrt().
subroutine rflo_mgframecorrectneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 1259 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ic, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getnodeoffset(), and sqrt().
subroutine rflo_mgframecorrectneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 1157 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ic, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getnodeoffset(), and sqrt().
subroutine rflo_mgframeedges (type(t_region) region, integer iType, logical, dimension(6) boundMoved, logical, dimension(6) allExternal, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 1642 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint1d(), s, and sqrt().
Referenced by rflo_mgframeinterfaces(), and rflo_mgframesurfaces().
subroutine rflo_mgframeedges (type(t_region) region, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 1866 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), setup_py::grid(), ibeg, ic, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint1d(), s, and sqrt().
subroutine rflo_mgframeedges (type(t_region) region, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 2195 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), setup_py::grid(), ibeg, ic, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint1d(), s, and sqrt().
subroutine rflo_mgframeedges (type(t_region) region, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 2240 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), setup_py::grid(), ibeg, ic, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint1d(), s, and sqrt().
subroutine rflo_mgframeedges (type(t_region) region, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 1916 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), setup_py::grid(), ibeg, ic, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint1d(), s, and sqrt().
subroutine rflo_mgframeedges (type(t_region) region, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 2210 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), setup_py::grid(), ibeg, ic, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_tfint1d(), s, and sqrt().
subroutine rflo_mgframeedgeso (type(t_region) region, integer iType, logical, dimension(6) boundMoved, logical, dimension(6) allExternal, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 1674 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint1d(), s, and sqrt().
subroutine rflo_mgframeedgeso (type(t_region) region, integer iType, logical, dimension(6) boundMoved, logical, dimension(6) allExternal, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 2003 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint1d(), s, and sqrt().
subroutine rflo_mgframeedgeso (type(t_region) region, integer iType, logical, dimension(6) boundMoved, logical, dimension(6) allExternal, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 2048 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint1d(), s, and sqrt().
Referenced by rflo_mgframeinterfaces(), and rflo_mgframesurfaces().
subroutine rflo_mgframeedgeso (type(t_region) region, integer iType, logical, dimension(6) boundMoved, logical, dimension(6) allExternal, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 1724 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint1d(), s, and sqrt().
subroutine rflo_mgframeedgeso (type(t_region) region, integer iType, logical, dimension(6) boundMoved, logical, dimension(6) allExternal, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 2018 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint1d(), s, and sqrt().
subroutine rflo_mgframeinterfaces (type(t_region), dimension(:), pointer regions, integer iType)
Definition at line 3027 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), setup_py::grid(), max(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_clearsendrequests(), rflo_edgedeformation(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_mgframebnddeformation(), rflo_mgframeedges(), and rflo_mgframeedgeso().
subroutine rflo_mgframeinterfaces (type(t_region), dimension(:), pointer regions, integer iType)
Definition at line 1826 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_clearsendrequests(), rflo_edgedeformation(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_mgframeedges(), and rflo_mgframerestoreexternal().
Referenced by rflo_movegridframe().
subroutine rflo_mgframeinterfaces (type(t_region), dimension(:), pointer regions, integer iType)
Definition at line 3207 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), setup_py::grid(), max(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_clearsendrequests(), rflo_edgedeformation(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_mgframebnddeformation(), rflo_mgframeedges(), rflo_mgframeedgeso(), and rflo_mgframerestoreexternal().
subroutine rflo_mgframeinterfaces (type(t_region), dimension(:), pointer regions, integer iType)
Definition at line 2883 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_clearsendrequests(), rflo_edgedeformation(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_mgframebnddeformation(), rflo_mgframeedges(), rflo_mgframeedgeso(), and rflo_mgframerestoreexternal().
subroutine rflo_mgframeinterfaces (type(t_region), dimension(:), pointer regions, integer iType)
Definition at line 2585 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_clearsendrequests(), rflo_edgedeformation(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_mgframeedgeso(), and rflo_mgframerestoreexternal().
subroutine rflo_mgframeinterfaces (type(t_region), dimension(:), pointer regions, integer iType)
Definition at line 3177 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), setup_py::grid(), max(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_clearsendrequests(), rflo_edgedeformation(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_mgframebnddeformation(), rflo_mgframeedges(), rflo_mgframeedgeso(), and rflo_mgframerestoreexternal().
subroutine rflo_mgframemovecorners (type(t_region), dimension(:), pointer regions)
Definition at line 1435 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), modtools::isnan(), k, moderror::registerfunction(), sqrt(), and CImg< T >::sum().
subroutine rflo_mgframemovecorners (type(t_region), dimension(:), pointer regions)
Definition at line 1306 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), modtools::isnan(), k, moderror::registerfunction(), and sqrt().
subroutine rflo_mgframemovecorners (type(t_region), dimension(:), pointer regions)
Definition at line 1321 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), modtools::isnan(), k, moderror::registerfunction(), sqrt(), and CImg< T >::sum().
subroutine rflo_mgframemovecorners (type(t_region), dimension(:), pointer regions)
Definition at line 1387 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), modtools::isnan(), k, moderror::registerfunction(), sqrt(), and CImg< T >::sum().
subroutine rflo_mgframemovecorners (type(t_region), dimension(:), pointer regions)
Definition at line 1264 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), ic, ipnbeg, ipnend, modtools::isnan(), jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and sqrt().
Referenced by rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), and rflo_mgframesurfaces().
subroutine rflo_mgframemovecorners (type(t_region), dimension(:), pointer regions)
Definition at line 1408 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), modtools::isnan(), k, moderror::registerfunction(), sqrt(), and CImg< T >::sum().
subroutine rflo_mgframeorthoshift (type(t_region), dimension(:), pointer regions)
Definition at line 1558 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), setup_py::grid(), k, moderror::registerfunction(), rflo_mgframebroadcast(), rflo_modvectortensor::rflo_normcrossprod(), and sqrt().
subroutine rflo_mgframeorthoshift (type(t_region), dimension(:), pointer regions)
Definition at line 1609 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), setup_py::grid(), k, moderror::registerfunction(), rflo_mgframebroadcast(), rflo_modvectortensor::rflo_normcrossprod(), and sqrt().
Referenced by rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), and rflo_mgframesurfaces().
subroutine rflo_mgframeorthoshift (type(t_region), dimension(:), pointer regions)
Definition at line 1579 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), setup_py::grid(), k, moderror::registerfunction(), rflo_mgframebroadcast(), rflo_modvectortensor::rflo_normcrossprod(), and sqrt().
subroutine rflo_mgframerestoreexternal (type(t_region) region)
Definition at line 1586 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), setup_py::grid(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine rflo_mgframerestoreexternal (type(t_region) region)
Definition at line 1915 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), setup_py::grid(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine rflo_mgframerestoreexternal (type(t_region) region)
Definition at line 1636 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), setup_py::grid(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine rflo_mgframerestoreexternal (type(t_region) region)
Definition at line 1556 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), setup_py::grid(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
Referenced by rflo_mgframeinterfaces(), and rflo_mgframesurfaces().
subroutine rflo_mgframerestoreexternal (type(t_region) region)
Definition at line 1960 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), setup_py::grid(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine rflo_mgframerestoreexternal (type(t_region) region)
Definition at line 1930 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), setup_py::grid(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine, public rflo_mgframesrchneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 849 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ibeg, ic, iend, ipcbeg, ipcend, ipnbeg, ipnend, j, jbeg, jend, jpcbeg, jpcend, jpnbeg, jpnend, k, kbeg, kpcbeg, kpnbeg, max(), min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and sqrt().
subroutine, public rflo_mgframesrchneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 870 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ibeg, ic, iend, ipcbeg, ipcend, ipnbeg, ipnend, j, jbeg, jend, jpcbeg, jpcend, jpnbeg, jpnend, k, kbeg, kpcbeg, kpnbeg, max(), min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and sqrt().
subroutine, public rflo_mgframesrchneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 765 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ibeg, ic, iend, ipcbeg, ipcend, ipnbeg, ipnend, j, jbeg, jend, jpcbeg, jpcend, jpnbeg, jpnend, k, kbeg, kpcbeg, kpnbeg, min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and sqrt().
Referenced by rflo_initgridprocedures().
subroutine, public rflo_mgframesrchneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 828 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ibeg, ic, iend, ipcbeg, ipcend, ipnbeg, ipnend, j, jbeg, jend, jpcbeg, jpcend, jpnbeg, jpnend, k, kbeg, kpcbeg, kpnbeg, max(), min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and sqrt().
subroutine, public rflo_mgframesrchneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 793 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ibeg, ic, iend, ipcbeg, ipcend, ipnbeg, ipnend, j, jbeg, jend, jpcbeg, jpcend, jpnbeg, jpnend, k, kbeg, kpcbeg, kpnbeg, min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and sqrt().
subroutine, public rflo_mgframesrchneighbors (type(t_region), dimension(:), pointer regions)
Definition at line 786 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), dist(), moderror::errorstop(), setup_py::grid(), i, ibeg, ic, iend, ipcbeg, ipcend, ipnbeg, ipnend, j, jbeg, jend, jpcbeg, jpcend, jpnbeg, jpnend, k, kbeg, kpcbeg, kpnbeg, min(), moderror::registerfunction(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and sqrt().
subroutine rflo_mgframesurfaces (type(t_region), dimension(:), pointer regions, logical someMoved, integer iType)
Definition at line 1786 of file RFLO_ModMoveGridNconform3.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_arclengthbounds(), rflo_boundarydeformation(), rflo_edgedeformation(), rflo_getdeformation(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_mgframebnddeformation(), rflo_mgframebroadcast(), rflo_mgframecorrectneighbors(), rflo_mgframeedges(), rflo_mgframemovecorners(), rflo_mgframeorthoshift(), and rflo_mgframerestoreexternal().
subroutine rflo_mgframesurfaces (type(t_region), dimension(:), pointer regions, logical someMoved, integer iType)
Definition at line 1418 of file RFLO_ModMoveGridConform.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_arclengthbounds(), rflo_boundarydeformation(), rflo_edgedeformation(), rflo_getdeformation(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_mgframebnddeformation(), rflo_mgframebroadcast(), rflo_mgframecorrectneighbors(), rflo_mgframeedges(), rflo_mgframemovecorners(), and rflo_mgframerestoreexternal().
Referenced by rflo_movegridframe().
subroutine rflo_mgframesurfaces (type(t_region), dimension(:), pointer regions, logical someMoved, integer iType)
Definition at line 1816 of file RFLO_ModMoveGridFrame.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_arclengthbounds(), rflo_boundarydeformation(), rflo_edgedeformation(), rflo_getdeformation(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_mgframebnddeformation(), rflo_mgframebroadcast(), rflo_mgframecorrectneighbors(), rflo_mgframeedges(), rflo_mgframemovecorners(), rflo_mgframeorthoshift(), and rflo_mgframerestoreexternal().
subroutine rflo_mgframesurfaces (type(t_region), dimension(:), pointer regions, logical someMoved, integer iType)
Definition at line 1494 of file RFLO_ModMoveGridNconform2.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_arclengthbounds(), rflo_boundarydeformation(), rflo_edgedeformation(), rflo_getdeformation(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_mgframebnddeformation(), rflo_mgframebroadcast(), rflo_mgframecorrectneighbors(), rflo_mgframeedges(), rflo_mgframemovecorners(), and rflo_mgframerestoreexternal().
subroutine rflo_mgframesurfaces (type(t_region), dimension(:), pointer regions, logical someMoved, integer iType)
Definition at line 1771 of file RFLO_ModMoveGridNconform4.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_arclengthbounds(), rflo_boundarydeformation(), rflo_edgedeformation(), rflo_getdeformation(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_mgframebnddeformation(), rflo_mgframebroadcast(), rflo_mgframecorrectneighbors(), rflo_mgframeedges(), rflo_mgframemovecorners(), and rflo_mgframeorthoshift().
subroutine rflo_mgframesurfaces (type(t_region), dimension(:), pointer regions, logical someMoved, integer iType)
Definition at line 1448 of file RFLO_ModMoveGridNconform.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_arclengthbounds(), rflo_boundarydeformation(), rflo_edgedeformation(), rflo_getdeformation(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), rflo_mgframebnddeformation(), rflo_mgframebroadcast(), rflo_mgframecorrectneighbors(), rflo_mgframeedgeso(), rflo_mgframemovecorners(), and rflo_mgframerestoreexternal().
subroutine, public rflo_movegridframe (type(t_region), dimension(:), pointer regions)
Definition at line 98 of file RFLO_ModMoveGridNconform4.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacevectors(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_copygeometrydummy(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_modgridmetrics::rflo_gridqualityglobal(), rflo_laplacegridsmoo(), rflo_mgframeinterfaces(), rflo_mgframesurfaces(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), sqrt(), and x.
subroutine, public rflo_movegridframe (type(t_region), dimension(:), pointer regions)
Definition at line 98 of file RFLO_ModMoveGridFrame.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_copygeometrydummy(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_modgridmetrics::rflo_gridqualityglobal(), rflo_laplacegridsmoo(), rflo_mgframeinterfaces(), rflo_mgframesurfaces(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), sqrt(), and x.
subroutine, public rflo_movegridframe (type(t_region), dimension(:), pointer regions)
Definition at line 97 of file RFLO_ModMoveGridNconform.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_copygeometrydummy(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_laplacegridsmoo(), rflo_mgframeinterfaces(), rflo_mgframesurfaces(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), sqrt(), and x.
subroutine, public rflo_movegridframe (type(t_region), dimension(:), pointer regions)
Definition at line 98 of file RFLO_ModMoveGridNconform3.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_copygeometrydummy(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_modgridmetrics::rflo_gridqualityglobal(), rflo_laplacegridsmoo(), rflo_mgframeinterfaces(), rflo_mgframesurfaces(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), sqrt(), and x.
subroutine, public rflo_movegridframe (type(t_region), dimension(:), pointer regions)
Definition at line 127 of file RFLO_ModMoveGridConform.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_copygeometrydummy(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_laplacegridsmoo(), rflo_mgframeinterfaces(), rflo_mgframesurfaces(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), sqrt(), and x.
Referenced by rflo_dualtimestepping(), and rflo_timestepping().
subroutine, public rflo_movegridframe (type(t_region), dimension(:), pointer regions)
Definition at line 97 of file RFLO_ModMoveGridNconform2.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_copygeometrydummy(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_laplacegridsmoo(), rflo_mgframeinterfaces(), rflo_mgframesurfaces(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), sqrt(), and x.
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModMoveGridConform.F90,v $ $Revision: 1.33 $' private
Definition at line 101 of file RFLO_ModMoveGridConform.F90.
The documentation for this module was generated from the following files:
RFLO_ModMoveGridConform.F90
RFLO_ModMoveGridFrame.F90
RFLO_ModMoveGridNconform.F90
RFLO_ModMoveGridNconform2.F90
RFLO_ModMoveGridNconform3.F90
RFLO_ModMoveGridNconform4.F90