Rocstar: CVector Class Reference
CVector Class Reference
#include <GeoPrimitives.H>
Public Member Functions
CVector ()
CVector (double ix, double iy, double iz=0.0)
CVector (const CPoint &p1, const CPoint &p2)
CVector (const CPoint &p)
CVector (const double *a)
CVector (const CVector &v)
CVector & init (const CPoint &p)
CVector & init (const double *a)
CVector & init (const CVector &v)
CVector & init (double ix, double iy, double iz)
CVector & init (const CPoint &p1, const CPoint &p2)
CVector & init ()
double norm () const
double mag () const
double mag2 () const
CVector & normalize ()
CVector unit () const
double operator* (const CVector &v2) const
CVector operator* (double num) const
CVector & operator*= (double num)
CVector operator% (const CVector &v2) const
CVector & copy (const CVector &v2)
CVector & operator= (const CVector &v2)
CVector & operator= (const CPoint &p)
CVector & operator%= (const CVector &v2)
CVector operator+ (const CVector &v2) const
CVector operator- (const CVector &v2) const
CVector & operator+= (const CVector &v2)
CVector & operator+= (const CPoint &p)
CVector & operator-= (const CVector &v2)
double & x ()
double x () const
CVector & x (double i)
double & y ()
double y () const
CVector & y (double i)
double & z ()
double z () const
CVector & z (double i)
const double & operator[] (unsigned int i) const
double & operator[] (unsigned int i)
bool operator== (const CVector &v) const
bool operator< (const CVector &v) const
bool operator> (const CVector &v) const
bool operator<= (const CVector &v) const
bool operator>= (const CVector &v) const
Protected Attributes
double V [3]
Friends
CVector operator* (double, const CVector &)
std::ostream & operator<< (std::ostream &, const CVector &)
std::istream & operator>> (std::istream &, CVector &)
Detailed Description
Definition at line 204 of file GeoPrimitives.H.
Constructor & Destructor Documentation
CVector () inline
Definition at line 211 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] = V[1] = V[2] = 0.;
     };
CVector (double ix, double iy, double iz = 0.0) inline
Definition at line 215 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
     };
CVector (const CPoint & p1, const CPoint & p2) inline
Definition at line 221 of file GeoPrimitives.H.
References CVector::V, CVector::x(), CVector::y(), and CVector::z().
     {
       V[0] = (p2 - p1).x();
       V[1] = (p2 - p1).y();
       V[2] = (p2 - p1).z();
     };
CVector (const CPoint & p) inline
Definition at line 227 of file GeoPrimitives.H.
References CVector::V, CPoint::x(), CPoint::y(), and CPoint::z().
     {
       V[0] = p.x();
       V[1] = p.y();
       V[2] = p.z();
     };
CVector (const double * a) inline
Definition at line 233 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
     };
CVector (const CVector & v) inline
Definition at line 239 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] = v.V[0];
       V[1] = v.V[1];
       V[2] = v.V[2];
     };
Member Function Documentation
CVector& copy (const CVector & v2) inline
Definition at line 340 of file GeoPrimitives.H.
References CVector::V.
Referenced by CVector::operator%=(), CVector::operator-=(), and CVector::operator=().
     {
       V[0] = v2.V[0];
       V[1] = v2.V[1];
       V[2] = v2.V[2];
       return(*this);
     };
CVector& init (const CPoint & p) inline
Definition at line 245 of file GeoPrimitives.H.
References CVector::V.
Referenced by Mesh::FindPointInCells(), Mesh::FindPointInMesh(), Mesh::FindPointInMesh_2(), Mesh::GlobalFindPointInMesh(), main(), Mesh::GenericElement::shapef_jacobian_at(), and GeoPrim::Transpose().
     {
       V[0] = p[0];
       V[1] = p[1];
       V[2] = p[2];
       return(*this);
     };
CVector& init (const double * a) inline
Definition at line 252 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] = a[0];
       V[1] = a[1];
       V[2] = a[2];
       return(*this);
     };
CVector& init (const CVector & v) inline
Definition at line 259 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] = v[0];
       V[1] = v[1];
       V[2] = v[2];
       return(*this);
     };
CVector& init (double ix, double iy, double iz) inline
Definition at line 266 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] = ix;
       V[1] = iy;
       V[2] = iz;
       return(*this);
     };
CVector& init (const CPoint & p1, const CPoint & p2) inline
Definition at line 273 of file GeoPrimitives.H.
References CVector::V, CVector::x(), CVector::y(), and CVector::z().
     {
       V[0] = (p2 - p1).x();
       V[1] = (p2 - p1).y();
       V[2] = (p2 - p1).z();
       return(*this);
     };
CVector& init () inline
Definition at line 280 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] = V[1] = V[2] = 0.0;
       return(*this);
     };
double mag (void) const inline
Definition at line 289 of file GeoPrimitives.H.
References CVector::norm().
Referenced by GeoPrim::Distance(), and main().
     {
       return (norm());
     };
double mag2 () const inline
Definition at line 293 of file GeoPrimitives.H.
References CVector::V.
Referenced by GeoPrim::Distance(), and splitquadface().
     {
       return ((V[0]*V[0])+(V[1]*V[1])+(V[2]*V[2]));
     };
double norm () const inline
Definition at line 285 of file GeoPrimitives.H.
References sqrt(), and CVector::V.
Referenced by CLineSegment::length(), CVector::mag(), CVector::normalize(), CVector::operator<(), CVector::operator>(), and CVector::unit().
     {
       return(sqrt((V[0] * V[0]) + (V[1] * V[1]) + (V[2] * V[2])));
     };
CVector& normalize () inline
Definition at line 297 of file GeoPrimitives.H.
References CVector::norm(), and CVector::V.
Referenced by CPlane::CPlane(), CLine::has_point(), and Mesh::GenericCell_2::shapef_jacobian_at().
     {
       double n = norm();
       V[0] /= n;
       V[1] /= n;
       V[2] /= n;
       return(*this);
     };
CVector operator% (const CVector & v2) const inline
Definition at line 332 of file GeoPrimitives.H.
References v, and CVector::V.
     {
       CVector v;
       v.V[0] = ((v2.V[2] * V[1]) - (v2.V[1] * V[2]));
       v.V[1] = ((v2.V[0] * V[2]) - (v2.V[2] * V[0]));
       v.V[2] = ((v2.V[1] * V[0]) - (v2.V[0] * V[1]));
       return(v);
     };
CVector& operator%= (const CVector & v2) inline
Definition at line 358 of file GeoPrimitives.H.
References CVector::copy().
     {
       return(copy((*this)%v2));
     };
double operator* (const CVector & v2) const inline
Definition at line 314 of file GeoPrimitives.H.
References CVector::V.
     {
       return((V[0] * v2.V[0]) +
              (V[1] * v2.V[1]) +
              (V[2] * v2.V[2]));
     };
CVector operator* (double num) const inline
Definition at line 320 of file GeoPrimitives.H.
References CVector::V.
     {
       CVector rv(num*V[0],num*V[1],num*V[2]);
       return(rv);
     };
CVector& operator*= (double num) inline
Definition at line 325 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] *= num;
       V[1] *= num;
       V[2] *= num;
       return(*this);
     };
CVector operator+ (const CVector & v2) const inline
Definition at line 362 of file GeoPrimitives.H.
References v, and CVector::V.
     {
       CVector v(V[0] + v2.V[0], V[1] + v2.V[1], V[2] + v2.V[2]);
       return(v);
     };
CVector& operator+= (const CVector & v2) inline
Definition at line 371 of file GeoPrimitives.H.
References CVector::V.
     {
       V[0] += v2.V[0];
       V[1] += v2.V[1];
       V[2] += v2.V[2];
       return(*this);
     };
CVector& operator+= (const CPoint & p) inline
Definition at line 378 of file GeoPrimitives.H.
References CVector::V, CPoint::x(), CPoint::y(), and CPoint::z().
     {
       V[0] += p.x();
       V[1] += p.y();
       V[2] += p.z();
       return(*this);
     };
CVector operator- (const CVector & v2) const inline
Definition at line 367 of file GeoPrimitives.H.
     {
       return((*this) + (-1.0 * v2));
     };
CVector& operator-= (const CVector & v2) inline
Definition at line 385 of file GeoPrimitives.H.
References CVector::copy().
     {
       return(copy((*this) - v2));
     };
bool operator< (const CVector & v) const inline
Definition at line 444 of file GeoPrimitives.H.
References CVector::norm().
     {
       return (norm() < v.norm());
     };
bool operator<= (const CVector & v) const inline
Definition at line 452 of file GeoPrimitives.H.
     {
       return ( (*this < v) ||
                (*this == v));
     };
CVector& operator= (const CVector & v2) inline
Definition at line 347 of file GeoPrimitives.H.
References CVector::copy().
     {
       return(copy(v2));
     };
CVector& operator= (const CPoint & p) inline
Definition at line 351 of file GeoPrimitives.H.
References CVector::V, CPoint::x(), CPoint::y(), and CPoint::z().
     {
       V[0] = p.x();
       V[1] = p.y();
       V[2] = p.z();
       return(*this);
     };
bool operator== (const CVector & v) const inline
Definition at line 438 of file GeoPrimitives.H.
References GeoPrim::TOL, and CVector::V.
     {
       return( (fabs(V[0] - v.V[0]) < TOL) &&
               (fabs(V[1] - v.V[1]) < TOL) &&
               (fabs(V[2] - v.V[2]) < TOL) );
     };
bool operator> (const CVector & v) const inline
Definition at line 448 of file GeoPrimitives.H.
References CVector::norm().
     {
       return (norm() > v.norm());
     };
bool operator>= (const CVector & v) const inline
Definition at line 457 of file GeoPrimitives.H.
     {
       return ( (*this > v) ||
                (*this == v) );
     };
const double& operator[] (unsigned int i) const inline
Definition at line 428 of file GeoPrimitives.H.
References CVector::V.
     {
       if(i > 2) i = 0;
       return(V[i]);
     };
double& operator[] (unsigned int i) inline
Definition at line 433 of file GeoPrimitives.H.
References CVector::V.
     {
       if(i > 2) i = 0;
       return(V[i]);
     };
CVector unit () const inline
Definition at line 305 of file GeoPrimitives.H.
References CVector::norm(), v, and CVector::V.
Referenced by CLine::has_point(), and CPlane::operator==().
     {
       CVector v(*this);
       double n = norm();
       v.V[0] /= n;
       v.V[1] /= n;
       v.V[2] /= n;
       return(v);
     };
double& x () inline
Definition at line 389 of file GeoPrimitives.H.
References CVector::V.
Referenced by CPlane::A(), CBox::around(), C3Vector::C3Vector(), CPlane::contains_point(), CPlane::CPlane(), CVector::CVector(), CPlane::D(), GeoPrim::Distance(), Mesh::GenericElement::dshape_func(), CVector::init(), Mesh::GenericCell_2::interpolate(), Mesh::GenericElement::interpolate(), Mesh::GenericElement::jacobian(), GeoPrim::operator<<(), Mesh::GenericElement::shape_func(), CBox::size(), and GeoPrim::Transpose_2x3().
     {
       return(V[0]);
     };
double x () const inline
Definition at line 393 of file GeoPrimitives.H.
References CVector::V.
     {
       return(V[0]);
     };
CVector& x (double i) inline
Definition at line 397 of file GeoPrimitives.H.
References i, and CVector::V.
     {
       V[0] = i;
       return(*this);
     };
double& y () inline
Definition at line 402 of file GeoPrimitives.H.
References CVector::V.
Referenced by CBox::around(), CPlane::B(), C3Vector::C3Vector(), CPlane::contains_point(), CVector::CVector(), CPlane::D(), GeoPrim::Distance(), Mesh::GenericElement::dshape_func(), CVector::init(), Mesh::GenericCell_2::interpolate(), Mesh::GenericElement::interpolate(), Mesh::GenericElement::jacobian(), GeoPrim::operator<<(), Mesh::GenericElement::shape_func(), CBox::size(), and GeoPrim::Transpose_2x3().
     {
       return(V[1]);
     };
double y () const inline
Definition at line 406 of file GeoPrimitives.H.
References CVector::V.
     {
       return(V[1]);
     };
CVector& y (double i) inline
Definition at line 410 of file GeoPrimitives.H.
References i, and CVector::V.
     {
       V[1] = i;
       return(*this);
     };
double& z () inline
Definition at line 415 of file GeoPrimitives.H.
References CVector::V.
Referenced by CBox::around(), CPlane::C(), C3Vector::C3Vector(), CPlane::contains_point(), CVector::CVector(), CPlane::D(), GeoPrim::Distance(), Mesh::GenericElement::dshape_func(), CVector::init(), Mesh::GenericElement::interpolate(), Mesh::GenericElement::jacobian(), GeoPrim::operator<<(), Mesh::GenericElement::shape_func(), CBox::size(), and GeoPrim::Transpose_2x3().
     {
       return(V[2]);
     };
double z () const inline
Definition at line 419 of file GeoPrimitives.H.
References CVector::V.
     {
       return(V[2]);
     };
CVector& z (double i) inline
Definition at line 423 of file GeoPrimitives.H.
References i, and CVector::V.
     {
       V[2] = i;
       return(*this);
     };
Friends And Related Function Documentation
CVector operator* (double scalar, const CVector & v) friend
Definition at line 132 of file GeoPrimitives.C.
   {
     GeoPrim::CVector rv(v);
     return(rv *= scalar);
   }
std::ostream& operator<< (std::ostream & oS, const CVector & v) friend
Definition at line 90 of file GeoPrimitives.C.
   {
     oS << v.x() << "  " << v.y() << "  " << v.z();
     return(oS);
   }
std::istream& operator>> (std::istream & iS, GeoPrim::CVector & v) friend
Definition at line 97 of file GeoPrimitives.C.
   {
     iS >> v[0] >> v[1] >> v[2];
     return(iS);
   }
Member Data Documentation
double V[3] protected
Definition at line 209 of file GeoPrimitives.H.
Referenced by CVector::copy(), CVector::CVector(), CVector::init(), CVector::mag2(), CVector::norm(), CVector::normalize(), CVector::operator%(), CVector::operator*(), CVector::operator*=(), CVector::operator+(), CVector::operator+=(), CVector::operator=(), CVector::operator==(), CVector::operator[](), CVector::unit(), CVector::x(), CVector::y(), and CVector::z().
The documentation for this class was generated from the following file:
GeoPrimitives.H