Rocstar: rflo_modmovegridelliptglo Module Reference
rflo_modmovegridelliptglo Module Reference
Public Member Functions
subroutine, public rflo_movegridelliptglo (regions)
subroutine, public rflo_mgelliptbnddeformation (region)
subroutine rflo_mgelliptsurfacesglo (regions, someMoved)
subroutine rflo_mgelliptinterfacesglo (regions)
subroutine rflo_mgelliptedgesglo (region, boundMoved, edgeMoved, arcLen12, arcLen34, arcLen56, xyzRef, xyzOld, dNode)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModMoveGridElliptGlo.F90,v $ $Revision: 1.18 $'
Detailed Description
Definition at line 40 of file RFLO_ModMoveGridElliptGlo.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_mgelliptbnddeformation (type(t_region) region)
Definition at line 340 of file RFLO_ModMoveGridElliptGlo.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_modelliptsmoothing::rflo_elliptgridgauss2d(), rflo_modelliptsmoothing::rflo_elliptgridjac2d(), rflo_modelliptsmoothing::rflo_elliptgridsor2d(), rflo_modmovegridutil::rflo_movegridcurvedpatch(), and rflo_modmovegridutil::rflo_movegridqflatpatch().
Referenced by rflo_modmovegridelliptfra::rflo_movegridelliptfra(), and rflo_movegridelliptglo().
subroutine rflo_mgelliptedgesglo (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzRef, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 709 of file RFLO_ModMoveGridElliptGlo.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint1d(), s, and sqrt().
Referenced by rflo_mgelliptinterfacesglo(), and rflo_mgelliptsurfacesglo().
subroutine rflo_mgelliptinterfacesglo (type(t_region), dimension(:), pointer regions)
Definition at line 554 of file RFLO_ModMoveGridElliptGlo.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_clearsendrequests(), rflo_edgedeformation(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), and rflo_mgelliptedgesglo().
Referenced by rflo_movegridelliptglo().
subroutine rflo_mgelliptsurfacesglo (type(t_region), dimension(:), pointer regions, logical someMoved)
Definition at line 438 of file RFLO_ModMoveGridElliptGlo.F90.
References moderror::deregisterfunction(), setup_py::grid(), moderror::registerfunction(), rflo_arclengthbounds(), rflo_boundarydeformation(), rflo_edgedeformation(), rflo_edgedeformationstraight(), rflo_getdeformation(), and rflo_mgelliptedgesglo().
Referenced by rflo_movegridelliptglo().
subroutine, public rflo_movegridelliptglo (type(t_region), dimension(:), pointer regions)
Definition at line 92 of file RFLO_ModMoveGridElliptGlo.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), moderror::registerfunction(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacevectors(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_copygeometrydummy(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modelliptsmoothing::rflo_elliptgridsmooregion(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_modgridmetrics::rflo_gridqualityglobal(), rflo_laplacegridsmoo(), rflo_mgelliptbnddeformation(), rflo_mgelliptinterfacesglo(), rflo_mgelliptsurfacesglo(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), sqrt(), and x.
Referenced by rflo_dualtimestepping(), and rflo_timestepping().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModMoveGridElliptGlo.F90,v $ $Revision: 1.18 $' private
Definition at line 65 of file RFLO_ModMoveGridElliptGlo.F90.
The documentation for this module was generated from the following file:
RFLO_ModMoveGridElliptGlo.F90