Rocstar: CBox Class Reference
CBox Class Reference
#include <GeoPrimitives.H>
Public Member Functions
CBox ()
CBox (const std::vector< CPoint > &pv)
CBox (const double *points, unsigned int n)
CBox (const CPoint &ip1, const CPoint &ip2)
CBox (const CBox &box)
const CPoint & P1 () const
const CPoint & P2 () const
bool empty () const
CPoint & P1 ()
CPoint & P2 ()
void init (const double *points, unsigned int n)
CBox & operator= (const CBox &b)
CBox around (const CPoint &p) const
bool operator== (const CBox &b) const
CPoint & min ()
const CPoint & min () const
CPoint & max ()
const CPoint & max () const
bool contains (const CPoint &p) const
bool contains (const double *p) const
double size () const
bool operator< (const CBox &b) const
bool operator> (const CBox &b) const
void AddPoint (const CPoint &p)
void merge (const CBox &b)
bool collide (const CBox &b) const
CBox intersect (const CBox &b) const
Protected Attributes
CPoint p1
CPoint p2
Private Attributes
bool initd
Friends
std::ostream & operator<< (std::ostream &, const CBox &)
Detailed Description
Definition at line 1126 of file GeoPrimitives.H.
Constructor & Destructor Documentation
CBox () inline
Definition at line 1134 of file GeoPrimitives.H.
References CBox::initd, CBox::p1, CBox::p2, and CPoint::reset().
     {
       p1.reset();
       p2.reset();
       initd=false;
     };
CBox (const std::vector< CPoint > & pv) inline
Definition at line 1140 of file GeoPrimitives.H.
References CBox::initd, CBox::p1, CBox::p2, CPoint::x(), CPoint::y(), and CPoint::z().
     {
       std::vector<CPoint>::const_iterator pvi = pv.begin();
       p1.x(pvi->x());
       p2.x(p1.x());
       p1.y(pvi->y());
       p2.y(p1.y());
       p1.z(pvi->z());
       p2.z(p1.z());
       pvi++;
       while(pvi != pv.end()){
         if(pvi->x() < p1.x()) p1.x(pvi->x());
         if(pvi->x() > p2.x()) p2.x(pvi->x());
         if(pvi->y() < p1.y()) p1.y(pvi->y());
         if(pvi->y() > p2.y()) p2.y(pvi->y());
         if(pvi->z() < p1.z()) p1.z(pvi->z());
         if(pvi->z() > p2.z()) p2.z(pvi->z());
         pvi++;
       }
       initd = true;
     }
CBox (const double * points, unsigned int n) inline
Definition at line 1161 of file GeoPrimitives.H.
References i, CBox::initd, CBox::p1, CBox::p2, CPoint::x(), CPoint::y(), and CPoint::z().
     {
       p1.x(points[0]);
       p1.y(points[1]);
       p1.z(points[2]);
       p2 = p1;
       for(unsigned int i = 1;i<n;i++){
         if(points[i*3] < p1.x()) p1.x(points[i*3]);
         if(points[i*3] > p2.x()) p2.x(points[i*3]);
         if(points[(i*3)+1] < p1.y()) p1.y(points[(i*3)+1]);
         if(points[(i*3)+1] > p2.y()) p2.y(points[(i*3)+1]);
         if(points[(i*3)+2] < p1.z()) p1.z(points[(i*3)+2]);
         if(points[(i*3)+2] > p2.z()) p2.z(points[(i*3)+2]);
       }
       initd = true;
     };
CBox (const CPoint & ip1, const CPoint & ip2) inline
Definition at line 1177 of file GeoPrimitives.H.
References CBox::initd.
       : p1(ip1),p2(ip2)
     {initd = true;};
CBox (const CBox & box) inline
Definition at line 1180 of file GeoPrimitives.H.
References CBox::initd.
       : p1(box.p1),p2(box.p2)
     {initd = true;};
Member Function Documentation
void AddPoint (const CPoint & p) inline
Definition at line 1275 of file GeoPrimitives.H.
References CBox::initd, CBox::p1, CBox::p2, CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by Mesh::FindPointInMesh(), and Mesh::FindPointInMesh_2().
     {
       if(!initd){
         p1 = p;
         p2 = p;
         initd = true;
       }
       else{
         if(p.x() < p1.x()) p1.x() = p.x();
         if(p.x() > p2.x()) p2.x() = p.x();
         if(p.y() < p1.y()) p1.y() = p.y();
         if(p.y() > p2.y()) p2.y() = p.y();
         if(p.z() < p1.z()) p1.z() = p.z();
         if(p.z() > p2.z()) p2.z() = p.z();
       }
     };
CBox around (const CPoint & p) const inline
Definition at line 1213 of file GeoPrimitives.H.
References CBox::p1, CBox::p2, v, CPoint::x(), CVector::x(), CPoint::y(), CVector::y(), CPoint::z(), and CVector::z().
Referenced by Mesh::FindPointInMesh(), and Mesh::FindPointInMesh_2().
     {
       CVector v(p1,p2);
       CPoint minp(p.x()-fabs(v.x()/2.0),
                 p.y()-fabs(v.y()/2.0),
                   p.z()-fabs(v.z()/2.0));
       CPoint maxp(p.x()+fabs(v.x()/2.0),
                   p.y()+fabs(v.y()/2.0),
                   p.z()+fabs(v.z()/2.0));
       CBox box(minp,maxp);
       return(box);
     };
bool collide (const CBox & b) const inline
Definition at line 1309 of file GeoPrimitives.H.
References CBox::empty(), CBox::p1, CBox::p2, CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by CBox::intersect().
     {
       if(this->empty() || b.empty())
         return(false);
       return(!(b.p2.x() < p1.x() || b.p1.x() > p2.x()) &&
              !(b.p2.y() < p1.y() || b.p1.y() > p2.y()) &&
              !(b.p2.z() < p1.z() || b.p1.z() > p2.z()));
     };
bool contains (const CPoint & p) const inline
Definition at line 1249 of file GeoPrimitives.H.
References CBox::p1, CBox::p2, CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by Mesh::FindElementsInBox().
     {
     return( p.x() <= p2.x() && p.x() >= p1.x() &&
             p.y() <= p2.y() && p.y() >= p1.y() &&
             p.z() <= p2.z() && p.z() >= p1.z() );
     };
bool contains (const double * p) const inline
Definition at line 1255 of file GeoPrimitives.H.
References CBox::p1, CBox::p2, CPoint::x(), CPoint::y(), and CPoint::z().
     {
       return( p[0] <= p2.x() && p[0] >= p1.x() &&
               p[1] <= p2.y() && p[1] >= p1.y() &&
               p[2] <= p2.z() && p[2] >= p1.z() );
     };
bool empty (void) const inline
Definition at line 1185 of file GeoPrimitives.H.
References CBox::p1, CBox::p2, GeoPrim::TOL, CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by CBox::collide(), Mesh::CollideMeshWithBox(), Mesh::GetMeshBoxes(), and main().
                        {return ((std::fabs(p2.x()-p1.x()) < TOL) ||
                                 (std::fabs(p2.y()-p1.y()) < TOL) ||
                                 (std::fabs(p2.z()-p1.z()) < TOL));};
void init (const double * points, unsigned int n) inline
Definition at line 1190 of file GeoPrimitives.H.
References i, CBox::initd, CBox::p1, CBox::p2, CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by Mesh::GetMeshBoxes().
     {
       initd = true;
       p1.x(points[0]);
       p1.y(points[1]);
       p1.z(points[2]);
       p2 = p1;
       for(unsigned int i = 1;i<n;i++){
         if(points[i*3] < p1.x()) p1.x(points[i*3]);
         if(points[i*3] > p2.x()) p2.x(points[i*3]);
         if(points[(i*3)+1] < p1.y()) p1.y(points[(i*3)+1]);
         if(points[(i*3)+1] > p2.y()) p2.y(points[(i*3)+1]);
         if(points[(i*3)+2] < p1.z()) p1.z(points[(i*3)+2]);
         if(points[(i*3)+2] > p2.z()) p2.z(points[(i*3)+2]);
       }
     };
CBox intersect (const CBox & b) const inline
Definition at line 1317 of file GeoPrimitives.H.
References CBox::collide(), CBox::p1, CBox::p2, CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by Mesh::CollideCellsWithBox(), and Mesh::CollideMeshWithBox().
     {
       CBox retval;
       if(collide(b)){
         retval.p1.x(b.p1.x() > p1.x() ? b.p1.x() : p1.x());
         retval.p1.y(b.p1.y() > p1.y() ? b.p1.y() : p1.y());
         retval.p1.z(b.p1.z() > p1.z() ? b.p1.z() : p1.z());
         retval.p2.x(b.p2.x() < p2.x() ? b.p2.x() : p2.x());
         retval.p2.y(b.p2.y() < p2.y() ? b.p2.y() : p2.y());
         retval.p2.z(b.p2.z() < p2.z() ? b.p2.z() : p2.z());
       }
       return(retval);
     };
CPoint& max (void) inline
Definition at line 1241 of file GeoPrimitives.H.
References CBox::p2.
     {
       return(p2);
     };
const CPoint& max (void) const inline
Definition at line 1245 of file GeoPrimitives.H.
References CBox::p2.
     {
       return(p2);
     };
void merge (const CBox & b) inline
Definition at line 1291 of file GeoPrimitives.H.
References CBox::initd, CBox::p1, CBox::p2, CPoint::x(), CPoint::y(), and CPoint::z().
Referenced by main().
     {
       if(initd){
         CPoint p(p1);
         p1.x((b.p1.x() > p1.x() ? p.x() : b.p1.x()));
         p1.y((b.p1.y() > p1.y() ? p.y() : b.p1.y()));
         p1.z((b.p1.z() > p1.z() ? p.z() : b.p1.z()));
         p = p2;
         p2.x(b.p2.x() < p2.x() ? p.x() : b.p2.x());
         p2.y(b.p2.y() < p2.y() ? p.y() : b.p2.y());
         p2.z(b.p2.z() < p2.z() ? p.z() : b.p2.z());
       }
       else {
         p1 = b.p1;
         p2 = b.p2;
         initd = true;
       }
     };
CPoint& min () inline
Definition at line 1233 of file GeoPrimitives.H.
References CBox::p1.
     {
     return(p1);
     };
const CPoint& min () const inline
Definition at line 1237 of file GeoPrimitives.H.
References CBox::p1.
     {
       return(p1);
     };
bool operator< (const CBox & b) const inline
Definition at line 1267 of file GeoPrimitives.H.
References CBox::size().
     {
       return(this->size() < b.size());
     };
CBox& operator= (const CBox & b) inline
Definition at line 1206 of file GeoPrimitives.H.
References CBox::initd, CBox::p1, and CBox::p2.
     {
       p1 = b.p1;
       p2 = b.p2;
       initd = true;
       return(*this);
     };
bool operator== (const CBox & b) const inline
Definition at line 1225 of file GeoPrimitives.H.
References CBox::p1, and CBox::p2.
     {
       return(p1 == b.p1 && p2 == b.p2);
     };
bool operator> (const CBox & b) const inline
Definition at line 1271 of file GeoPrimitives.H.
References CBox::size().
     {
       return(this->size() > b.size());
     };
const CPoint& P1 () const inline
Definition at line 1183 of file GeoPrimitives.H.
References CBox::p1.
Referenced by Mesh::GenerateCartesianGrid(), main(), and GeoPrim::operator<<().
 {return p1;};
CPoint& P1 () inline
Definition at line 1188 of file GeoPrimitives.H.
References CBox::p1.
 {return p1;};
const CPoint& P2 () const inline
Definition at line 1184 of file GeoPrimitives.H.
References CBox::p2.
Referenced by Mesh::GenerateCartesianGrid(), main(), and GeoPrim::operator<<().
 {return p2;};
CPoint& P2 () inline
Definition at line 1189 of file GeoPrimitives.H.
References CBox::p2.
 {return p2;};
double size () const inline
Definition at line 1262 of file GeoPrimitives.H.
References CBox::p1, CBox::p2, v, CVector::x(), CVector::y(), and CVector::z().
Referenced by CBox::operator<(), and CBox::operator>().
     {
       CVector v(p1,p2);
       return(fabs(v.x()*v.y()*v.z()));
     };
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & oS, const CBox & b) friend
Definition at line 55 of file GeoPrimitives.C.
   {
     oS << b.P1() << "  " << b.P2();
     return(oS);
   }
Member Data Documentation
bool initd private
Definition at line 1129 of file GeoPrimitives.H.
Referenced by CBox::AddPoint(), CBox::CBox(), CBox::init(), CBox::merge(), and CBox::operator=().
CPoint p1 protected
Definition at line 1131 of file GeoPrimitives.H.
Referenced by CBox::AddPoint(), CBox::around(), CBox::CBox(), CBox::collide(), CBox::contains(), CBox::empty(), CBox::init(), CBox::intersect(), CBox::merge(), CBox::min(), CBox::operator=(), CBox::operator==(), CBox::P1(), and CBox::size().
CPoint p2 protected
Definition at line 1132 of file GeoPrimitives.H.
Referenced by CBox::AddPoint(), CBox::around(), CBox::CBox(), CBox::collide(), CBox::contains(), CBox::empty(), CBox::init(), CBox::intersect(), CBox::max(), CBox::merge(), CBox::operator=(), CBox::operator==(), CBox::P2(), and CBox::size().
The documentation for this class was generated from the following file:
GeoPrimitives.H