Rocstar: RFC_Data_const< _Tag > Class Template Reference
RFC_Data_const< _Tag > Class Template Reference
#include <RFC_Window_transfer.h>
Public Types
typedef Vector_n Value
typedef Array_n Value_nonconst
typedef Array_n_const Value_const
typedef unsigned int Size
typedef _Tag Tag
Public Member Functions
RFC_Data_const ()
RFC_Data_const (const RFC_Window_transfer &win, const char *aname)
RFC_Data_const (const COM::Attribute *a)
RFC_Data_const (int i, int d)
int id () const
Size dimension () const
bool is_valid (const RFC_Pane_transfer *p, int i) const
Value_const get_value (const RFC_Pane_transfer *p, int v) const
Value_const get_value (const Real *buf, int v) const
Tag tag () const
Protected Attributes
int _id
unsigned int _dim
Detailed Description
template<class _Tag>
class RFC_Data_const< _Tag >
Definition at line 43 of file RFC_Window_transfer.h.
Member Typedef Documentation
typedef unsigned int Size
Definition at line 242 of file RFC_Window_transfer.h.
typedef _Tag Tag
Definition at line 243 of file RFC_Window_transfer.h.
typedef Vector_n Value
Definition at line 239 of file RFC_Window_transfer.h.
typedef Array_n_const Value_const
Definition at line 241 of file RFC_Window_transfer.h.
typedef Array_n Value_nonconst
Definition at line 240 of file RFC_Window_transfer.h.
Constructor & Destructor Documentation
RFC_Data_const () inline
Definition at line 245 of file RFC_Window_transfer.h.
 : _id(0), _dim(0) {}
RFC_Data_const (const RFC_Window_transfer & win, const char * aname) inline
Definition at line 246 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, and RFC_Window_base::attribute().
{
     const COM::Attribute *a = win.attribute( aname);
     _id = a->id(); _dim = a->size_of_components();
   }
RFC_Data_const (const COM::Attribute * a) inline
Definition at line 250 of file RFC_Window_transfer.h.
     : _id(a->id()), _dim(a->size_of_components()) {}
RFC_Data_const (int i, int d) inline
Definition at line 252 of file RFC_Window_transfer.h.
     : _id( i), _dim(d) {}
Member Function Documentation
Size dimension () const inline
Definition at line 256 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim.
Referenced by Transfer_base::compute_load_vector_wra(), RFC_Window_transfer::init_facial_buffers(), Transfer_base::init_load_vector(), RFC_Window_transfer::init_nodal_buffers(), Transfer_base::integrate(), Transfer_base::interpolate_fe(), Transfer_base::minmax(), Transfer_base::multiply_mass_mat_and_x(), RFC_Window_transfer::reduce_maxabs_to_all(), RFC_Window_transfer::reduce_to_all(), RFC_Window_transfer::replicate_data(), and Transfer_base::transfer_2f().
 { return _dim; }
Value_const get_value (const RFC_Pane_transfer * p, int v) const inline
Definition at line 261 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, RFC_Data_const< _Tag >::_id, RFC_Pane_transfer::pointer(), and RFC_assertion.
Referenced by Transfer_base::copy_vec(), Transfer_base::dot(), Transfer_base::dot2(), Transfer_base::make_field(), Transfer_base::minmax(), Transfer_base::norm2(), Transfer_base::precondition_Jacobi(), and Transfer_base::saxpy().
{
     RFC_assertion( v>=1);
     return Value_const( p->pointer( _id) + (v-1)*_dim, _dim);
   }
Value_const get_value (const Real * buf, int v) const inline
Definition at line 266 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_dim, and RFC_assertion.
{
     RFC_assertion( v>=1);
     return Value_const( buf + (v-1)*_dim, _dim);
   }
int id () const inline
Definition at line 255 of file RFC_Window_transfer.h.
References RFC_Data_const< _Tag >::_id.
Referenced by Transfer_base::copy_vec(), Transfer_base::dot(), Transfer_base::dot2(), Transfer_base::init_load_vector(), Transfer_base::interpolate_fe(), Transfer_base::invert(), Transfer_base::make_field(), Transfer_base::minmax(), Transfer_base::multiply_mass_mat_and_x(), Transfer_base::norm2(), Transfer_base::precondition_Jacobi(), RFC_Window_transfer::reduce_maxabs_to_all(), RFC_Window_transfer::reduce_to_all(), RFC_Window_transfer::replicate_data(), Transfer_base::saxpy(), Transfer_base::scale(), and Transfer_base::transfer_2f().
 { return _id; }
bool is_valid (const RFC_Pane_transfer * p, int i) const inline
Definition at line 257 of file RFC_Window_transfer.h.
   { return true; }
Tag tag () const inline
Definition at line 271 of file RFC_Window_transfer.h.
Referenced by peul_receivecorneredgecells(), peul_sendcorneredgecells(), plag_cecellsrecvsize(), plag_cecellssendsize(), plag_rflo_recvmetrics(), plag_rflo_modstats::plag_rflo_recvstatbuff(), plag_rflo_sendmetrics(), plag_rflo_modstats::plag_rflo_sendstatbuffconf(), plag_rflu_modcomm::plag_rflu_isendcounters(), plag_rflu_modcomm::plag_rflu_recvcounters(), radi_floflimrecvcornedgecells(), radi_floflimrecvdummyvals(), radi_floflimsendcornedgecells(), radi_floflimsenddummyconf(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangegeometryprepare(), rflo_exchangegeometryrecv(), rflo_exchangegeometrysend(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffs(), rflo_receivecorneredgecells(), rflo_receivedummyvals(), rflo_sendcorneredgecells(), rflo_senddummyconf(), rflo_modpatchaerocoeffs::rflo_writepatchaerocoeffs(), rflo_modforcesmoments::rflo_writepatchcoeffsinfo(), rflu_modmpi::rflu_mpi_isendcelldata(), rflu_modmpi::rflu_mpi_recvcelldata(), turb_floransrecvcornedgecells(), turb_floransrecvdummyvals(), turb_floranssendcornedgecells(), and turb_floranssenddummyconf().
 { return Tag(); }
Member Data Documentation
unsigned int _dim protected
Definition at line 274 of file RFC_Window_transfer.h.
Referenced by RFC_Data_const< _Tag >::dimension(), RFC_Data_const< _Tag >::get_value(), RFC_Data< _Tag >::get_value(), RFC_Data_const< _Tag >::RFC_Data_const(), and RFC_Data< _Tag >::set_value().
int _id protected
Definition at line 273 of file RFC_Window_transfer.h.
Referenced by RFC_Data_const< _Tag >::get_value(), RFC_Data< _Tag >::get_value(), RFC_Data_const< _Tag >::id(), RFC_Data_const< _Tag >::RFC_Data_const(), and RFC_Data< _Tag >::set_value().
The documentation for this class was generated from the following file:
RFC_Window_transfer.h