Rocstar: m_init_1dmodules Module Reference
m_init_1dmodules Module Reference
Data Types
interface COM_set_data
Public Member Functions
subroutine rocburn_init_funcs_apn (mname)
subroutine rocburn_init_funcs_py (mname)
subroutine rocburn_init_funcs_zn (mname)
Detailed Description
Definition at line 40 of file Rocburn_load_module.f90.
Member Function/Subroutine Documentation
subroutine rocburn_init_funcs_apn (character(*), intent(in) mname)
Definition at line 60 of file Rocburn_load_module.f90.
References m_rocburn_1d_apn::finalize_0d(), m_rocburn_1d_apn::get_burning_rate_1d(), m_rocburn_1d_apn::initialize_0d(), and m_rocburn_1d_apn::initialize_1d().
Referenced by rocburn_load_module().
subroutine rocburn_init_funcs_py (character(*), intent(in) mname)
Definition at line 71 of file Rocburn_load_module.f90.
References m_rocburn_1d_apn::finalize_0d(), m_rocburn_1d_apn::get_burning_rate_1d(), m_rocburn_1d_zn::get_film_coeff_1d(), setup_py::get_time_step_1d(), m_rocburn_1d_apn::initialize_0d(), and m_rocburn_1d_apn::initialize_1d().
Referenced by rocburn_load_module().
subroutine rocburn_init_funcs_zn (character(*), intent(in) mname)
Definition at line 84 of file Rocburn_load_module.f90.
References m_rocburn_1d_apn::finalize_0d(), m_rocburn_1d_apn::get_burning_rate_1d(), m_rocburn_1d_zn::get_film_coeff_1d(), setup_py::get_time_step_1d(), m_rocburn_1d_apn::initialize_0d(), and m_rocburn_1d_apn::initialize_1d().
Referenced by rocburn_load_module().
The documentation for this module was generated from the following file:
Rocburn_load_module.f90