Rocstar: TestBase Class Reference
TestBase Class Reference
Public Member Functions
virtual ~TestBase ()
virtual int f1 ()
virtual int f2 ()
Protected Attributes
int protected_data
Private Attributes
int private_data
Detailed Description
Definition at line 4107 of file meshtest1.C.
Constructor & Destructor Documentation
virtual ~TestBase () inline virtual
Definition at line 4113 of file meshtest1.C.
 {};
Member Function Documentation
virtual int f1 () inline virtual
Definition at line 4114 of file meshtest1.C.
Referenced by accumulatexyzwork(), rflo_timestepviscous(), and rflu_modbessel::rflu_jyndd().
 { return 0; };
virtual int f2 () inline virtual
Definition at line 4115 of file meshtest1.C.
Referenced by accumulatexyzwork(), and rflo_timestepviscous().
 { return 0; };
Member Data Documentation
int private_data private
Definition at line 4109 of file meshtest1.C.
int protected_data protected
Definition at line 4111 of file meshtest1.C.
The documentation for this class was generated from the following file:
meshtest1.C