Rocstar: rflu_modvertexlists Module Reference
rflu_modvertexlists Module Reference
Public Member Functions
subroutine, public rflu_buildvert2celllist (pRegion)
subroutine, public rflu_createvert2celllist (pRegion)
subroutine, public rflu_destroyvert2celllist (pRegion)
subroutine, public rflu_nullifyvert2celllist (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModVertexLists.F90,v $ $Revision: 1.4 $'
Detailed Description
Definition at line 39 of file RFLU_ModVertexLists.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_buildvert2celllist (type(t_region), pointer pRegion)
Definition at line 94 of file RFLU_ModVertexLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modcellfaceedgeinfo::rflu_getglobalcelltype().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflupart(), and rflupick().
subroutine, public rflu_createvert2celllist (type(t_region), pointer pRegion)
Definition at line 327 of file RFLU_ModVertexLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyvert2celllist().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflupart(), and rflupick().
subroutine, public rflu_destroyvert2celllist (type(t_region), pointer pRegion)
Definition at line 421 of file RFLU_ModVertexLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_nullifyvert2celllist().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflupart(), and rflupick().
subroutine, public rflu_nullifyvert2celllist (type(t_region), pointer pRegion)
Definition at line 515 of file RFLU_ModVertexLists.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_createvert2celllist(), and rflu_destroyvert2celllist().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModVertexLists.F90,v $ $Revision: 1.4 $' private
Definition at line 65 of file RFLU_ModVertexLists.F90.
The documentation for this module was generated from the following file:
RFLU_ModVertexLists.F90