Rocstar: Color Class Reference
Color Class Reference
#include <Color.h>
Public Member Functions
Color ()
Color (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha=120)
unsigned char r () const
unsigned char g () const
unsigned char b () const
unsigned char red () const
unsigned char green () const
unsigned char blue () const
unsigned char alpha () const
void set_alpha (unsigned char a)
bool operator== (const Color &c) const
bool operator!= (const Color &c) const
Color & operator= (const Color &c)
Private Attributes
unsigned char _red
unsigned char _green
unsigned char _blue
unsigned char _alpha
Detailed Description
Definition at line 58 of file Color.h.
Constructor & Destructor Documentation
Color () inline
Definition at line 60 of file Color.h.
 {}
Color (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha = 120) inline
Definition at line 61 of file Color.h.
     : _red(red), _green(green), _blue(blue), _alpha(alpha)
   {}
Member Function Documentation
unsigned char alpha () const inline
Definition at line 75 of file Color.h.
References _alpha.
Referenced by explicitmultistage(), huang_const_model(), implicit_v3d8_me_k(), matvol_sub(), operator=(), peri_copgradupdate(), plag_injcmakeparticle(), plag_rand1logskewed(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_updateboundaryvalues(), rflu_updateinbuffwrapper(), rocfracmain::rocfracsoln(), tensormul(), m_rocburn_2d::update(), updateboundaryconditionsmp(), v3d4n(), v3d4n_mass(), v3d4n_neohookeancompress(), v3d4n_neohookeanincompress(), v3d4n_nl(), and v3d4n_nl_arruda_boyce().
 {return _alpha;}
unsigned char b () const inline
Definition at line 70 of file Color.h.
References _blue.
Referenced by a_d_tensors(), cmpct1(), cmpct2(), compositestiffnes(), modtools::comppythag(), modsortsearch::findcommonsortedintegers(), modtools::floatequal(), modtools::floatgreater(), modtools::floatless(), kronecker_product(), matmul2(), modsortsearch::mergesortedintegers(), pythag(), modsortsearch::quicksortintegerinteger(), modsortsearch::quicksortrfrealinteger(), modsortsearch::removecommonsortedintegers(), modsortsearch::removecommonsortedintegersfancy(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modoles::rflu_buildsymmetrymapsoles(), rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_computeintegral3oles(), rflu_computeweightsoles(), rflu_modoles::rflu_getqposinvoles(), rflu_modoles::rflu_getqposoles(), rflu_modpetscpoisson::rflu_petsc_solvepressurepoisson(), rflu_modexactflow::rflu_setexactflowlinear(), rflu_modexactflow::rflu_setexactflowtrig(), modtools::swapintegers(), modtools::swaprfreals(), tensormul(), tridg(), v3d10_thermal(), v3d4_thermal(), and vecmatvecmul().
 {return _blue;}
unsigned char blue () const inline
Definition at line 74 of file Color.h.
References _blue.
Referenced by operator<<(), operator=(), and operator==().
 {return _blue;}
unsigned char g () const inline
Definition at line 69 of file Color.h.
References _green.
Referenced by bcondinflowperf(), bcondinjectionperf(), eshelby(), jacobi(), mixtperf_c2_grt(), mixtperf_c_co2guvw(), mixtperf_c_dgp(), mixtperf_c_ghovm2(), mixtperf_c_grt(), mixtperf_co2_cguvw(), mixtperf_d_cgp(), mixtperf_d_dogma(), mixtperf_eo_dgpuvw(), mixtperf_eo_dgpvm(), mixtperf_eo_grtuvw(), mixtperf_p_ddogpo(), mixtperf_p_deogvm2(), mixtperf_p_gmapo(), mixtperf_p_gpotto(), mixtperf_po_cgpuvw(), mixtperf_po_gptto(), mixtperf_r_cpg(), mixtperf_t_cgr(), mixtperf_t_gmato(), mixtperf_vm_c2co2g(), setup_py::readtable(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modbilinearpatch::rflu_blin_findclosestpoint(), rflu_modoles::rflu_buildsymmetrymapsoles(), rflu_modboundxvutils::rflu_bxv_compenergypatch(), rflu_modboundxvutils::rflu_bxv_compmomenergypatch(), rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_centralfirstpatch(), rflu_centralsecondpatch(), rflu_computeintegral3oles(), rflu_computevertexvariables(), rflu_computeweightsoles(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_modoles::rflu_getqposinvoles(), rflu_modoles::rflu_getqposoles(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_initflowhardcode(), rflu_initflowhardcodelim(), rflu_initflowscratch(), rflu_modnscbc::rflu_nscbc_comprhsff(), rflu_modnscbc::rflu_nscbc_comprhsifveltemp(), rflu_modnscbc::rflu_nscbc_comprhsof(), rflu_modnscbc::rflu_nscbc_comprhssw(), rflu_modnscbc::rflu_nscbc_initff(), rflu_modnscbc::rflu_nscbc_initiftotang(), rflu_modnscbc::rflu_nscbc_initifveltemp(), rflu_modnscbc::rflu_nscbc_initof(), rflu_modnscbc::rflu_nscbc_initsw(), rflu_modroeflux::rflu_roe_computeflux1_tcp(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxc2_tcp(), rflu_modroeflux::rflu_roe_computefluxd1_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_setdependentvars(), spec_checkuserinput(), setup_py::steadytemp(), tql1(), tql2(), tred1(), tred2(), and turb_flucv2cons().
 {return _green;}
unsigned char green () const inline
Definition at line 73 of file Color.h.
References _green.
Referenced by operator<<(), operator=(), and operator==().
 {return _green;}
bool operator!= (const Color & c) const inline
Definition at line 84 of file Color.h.
   {
     return !( (*this) == c);
   }
Color& operator= (const Color & c) inline
Definition at line 89 of file Color.h.
References _alpha, _blue, _green, _red, alpha(), blue(), green(), and red().
   {
     _red = c.red();
     _green = c.green();
     _blue = c.blue();
     _alpha = c.alpha();
     return *this;
   }
bool operator== (const Color & c) const inline
Definition at line 77 of file Color.h.
References blue(), green(), and red().
   {
     return ( (red() == c.red()) &&
              (green() == c.green()) &&
              (blue() == c.blue()) );
   }
unsigned char r () const inline
Definition at line 68 of file Color.h.
References _red.
Referenced by bc_enforce(), flimiterlp(), get_enhanced_map(), get_mixed_map(), get_shape(), get_shape20(), matous_const_model(), mixtperf_c2_grt(), mixtperf_c_grt(), mixtperf_cv_cpr(), mixtperf_d_prt(), mixtperf_eo_grtuvw(), mixtperf_g_cpr(), mixtperf_m_r(), mixtperf_p_drt(), mixtperf_t_cgr(), mixtperf_t_dpr(), operatorj(), plag_rflu_correctmixtproperties(), principal_stress(), pythag(), modsortsearch::quicksortinteger(), modsortsearch::quicksortintegerinteger(), modsortsearch::quicksortrfreal(), modsortsearch::quicksortrfrealinteger(), modrandom::randnormal(), rflu_modboundxvutils::rflu_bxv_compenergypatch(), rflu_modboundxvutils::rflu_bxv_compmomenergypatch(), rflu_modboundconvertcv::rflu_bxv_convertcvcons2prim(), rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_modboundxvutils::rflu_bxv_setdependentvarspatch(), rflu_modexactflow::rflu_computeexactflowculick(), rflu_modexactflow::rflu_computeexactflowpacoust(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_computevertexvariables(), rflu_modconvertcv::rflu_convertcvcons2prim(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_modextractflowdata::rflu_extractflowdatablasius(), rflu_modextractflowdata::rflu_extractflowdatalinefarf(), rflu_modextractflowdata::rflu_extractflowdatanscbc(), rflu_modextractflowdata::rflu_extractflowdataproudman(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modextractflowdata::rflu_extractflowdatasod(), rflu_modextractflowdata::rflu_extractflowdatasommspi(), rflu_modextractflowdata::rflu_extractflowdatastg1d(), rflu_modextractflowdata::rflu_extractflowdatastg2d(), rflu_modextractflowdatautils::rflu_extractshocklocation1d(), rflu_initflowscratch(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_modnscbc::rflu_nscbc_comprhsff(), rflu_modnscbc::rflu_nscbc_comprhsifveltemp(), rflu_modnscbc::rflu_nscbc_comprhsof(), rflu_modnscbc::rflu_nscbc_comprhssw(), rflu_modreadwritegrid::rflu_readgridascii(), rflu_modreadwritegrid::rflu_readgridbinary(), rflu_modreadwritegridspeeds::rflu_readgridspeedsascii(), rflu_modreadwritegridspeeds::rflu_readgridspeedsbinary(), rflu_modconvertcv::rflu_scalarconvertcvprim2cons(), rflu_setdependentvars(), rflu_setgasvars(), shcalc_3d10(), rflu_modrepair3d::snglar(), spec_rflu_modchemistry::spec_rflu_integratechemsrcterm(), sphere_imp_contains_point_3d(), tql1(), tql2(), turb_flucv2cons(), turb_flucv2prim(), and vol_elem_mat_ortho().
 {return _red;}
unsigned char red () const inline
Definition at line 72 of file Color.h.
References _red.
Referenced by operator<<(), operator=(), and operator==().
 {return _red;}
void set_alpha (unsigned char a) inline
Definition at line 76 of file Color.h.
References _alpha.
 {_alpha=a;}
Member Data Documentation
unsigned char _alpha private
Definition at line 102 of file Color.h.
Referenced by alpha(), operator=(), and set_alpha().
unsigned char _blue private
Definition at line 101 of file Color.h.
Referenced by b(), blue(), and operator=().
unsigned char _green private
Definition at line 100 of file Color.h.
Referenced by g(), green(), and operator=().
unsigned char _red private
Definition at line 99 of file Color.h.
Referenced by operator=(), r(), and red().
The documentation for this class was generated from the following file:
Color.h