Rocstar: CopyBurnFromParentMesh Class Reference
CopyBurnFromParentMesh Class Reference
#include <basic_actions.h>
Public Member Functions
CopyBurnFromParentMesh (BurnAgent *bag, FluidAgent *fag)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from Action
Action (void *p=0, char *name=NULL)
Action (int n, const char *at[], int *i=NULL, void *p=0, char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
BurnAgent * bagent
FluidAgent * fagent
std::string burn_mesh
std::string parent_mesh
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from Action
int get_attribute_handle (int i)
int get_attribute_handle_const (int i)
int get_attribute_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from Action
char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Detailed Description
Definition at line 238 of file basic_actions.h.
Constructor & Destructor Documentation
CopyBurnFromParentMesh (BurnAgent * bag, FluidAgent * fag)
Definition at line 827 of file basic_actions.C.
References Action::set_attr(), and Action::set_io().
                                                                              :
   Action(0, (const char**)NULL, NULL, NULL, (char *)"CopyBurnFromParentMesh"),
             bagent(bag), fagent(fag)
 {
   set_io( 0, (int *)NULL);
   set_attr(0, (const char**)NULL);
 }
Member Function Documentation
void init (double t) virtual
Reimplemented from Action.
Definition at line 836 of file basic_actions.C.
References bagent, burn_mesh, Agent::get_surface_window(), MAN_DEBUG, parent_mesh, and BurnAgent::parentWin.
{
   burn_mesh = bagent->get_surface_window()+".mesh";
   parent_mesh = bagent->parentWin+".mesh";
   MAN_DEBUG(3, ("Rocstar: CopyBurnFromParentMesh::init() with t:%e %s  %s.\n", t, burn_mesh.c_str(), parent_mesh.c_str()));
 }
void run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 842 of file basic_actions.C.
References burn_mesh, COM_copy_attribute(), MAN_DEBUG, and parent_mesh.
{
   MAN_DEBUG(3, ("Rocstar: CopyBurnFromParentMesh::run() with t:%e dt:%e %s %s.\n", t, dt, burn_mesh.c_str(), parent_mesh.c_str()));
   COM_copy_attribute( burn_mesh.c_str(), parent_mesh.c_str());
 /*
     // ????????
   double v = 0.0;
   int f_du_alp_hdl = COM_get_attribute_handle(fagent->get_surface_window()+".du_alp");
   COM_call_function( RocBlas::copy_scalar, &v, &f_du_alp_hdl);
 */
 }
Member Data Documentation
BurnAgent* bagent private
Definition at line 244 of file basic_actions.h.
Referenced by init().
std::string burn_mesh private
Definition at line 246 of file basic_actions.h.
Referenced by init(), and run().
FluidAgent* fagent private
Definition at line 245 of file basic_actions.h.
std::string parent_mesh private
Definition at line 246 of file basic_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
basic_actions.h
basic_actions.C