Rocstar: adjRec Class Reference
adjRec Class Reference
#include <adj.h>
Public Member Functions
void * operator new (size_t s)
void operator delete (void *ptr)
adjRec (face *b_, const blockLoc &l_, adjRec *next_=NULL)
face * getFace (void)
const face * getFace (void) const
const blockLoc & getLoc (void) const
adjRec * getNext (void)
void print (void)
bool isExternal (void) const
Static Public Attributes
static allocPool< adjRec > pool
Private Attributes
face * b
blockLoc l
adjRec * next
Detailed Description
Definition at line 103 of file adj.h.
Constructor & Destructor Documentation
adjRec (face * b_, const blockLoc & l_, adjRec * next_ = NULL) inline
Definition at line 112 of file adj.h.
                 :b(b_), l(l_), next(next_) { }
Member Function Documentation
face* getFace (void) inline
Definition at line 114 of file adj.h.
References b.
Referenced by adjList::isExternal().
 {return b;}
const face* getFace (void) const inline
Definition at line 115 of file adj.h.
References b.
 {return b;}
const blockLoc& getLoc (void) const inline
Definition at line 116 of file adj.h.
References l.
Referenced by adjList::isExternal().
 {return l;}
adjRec* getNext (void) inline
Definition at line 117 of file adj.h.
References next.
Referenced by adjList::getLength(), adjList::getLoc(), adjList::hasFace(), adjList::hasLoc(), node::intersect(), adjList::isExternal(), and adjList::~adjList().
 {return next;}
bool isExternal (void) const
void operator delete (void * ptr) inline
Definition at line 110 of file adj.h.
References allocPool< T >::free(), and pool.
 { pool.free(ptr); }
void* operator new (size_t s) inline
Definition at line 109 of file adj.h.
References allocPool< T >::alloc(), and pool.
 { return pool.alloc(); }
void print (void)
Definition at line 68 of file adj.cpp.
References b, face::getBlock(), block::getBlockNumber(), next, and print().
Referenced by print(), and adjList::print().
 {
         printf("%d",b->getBlock()->getBlockNumber()+1);
         if (next!=NULL) {
                 printf(" -> "); next->print();
         } else
                 printf(".\n");
 }
Member Data Documentation
face* b private
Definition at line 104 of file adj.h.
Referenced by getFace(), and print().
blockLoc l private
Definition at line 105 of file adj.h.
Referenced by getLoc().
adjRec* next private
Definition at line 106 of file adj.h.
Referenced by getNext(), and print().
allocPool< adjRec > pool static
Definition at line 108 of file adj.h.
Referenced by operator delete(), and operator new().
The documentation for this class was generated from the following files:
adj.h
adj.cpp