Rocstar: mblockData::blockPatches Class Reference
mblockData::blockPatches Class Reference
Public Member Functions
void init (block *b)
void write (FILE *out, mblockData &d, block *b)
void swap (int &a, int &b)
int getPatchNumber (patch *forPatch, int *retFace=NULL)
int totalPatches (void) const
Public Attributes
vector< patch * > patches [block::nFaces]
Detailed Description
Definition at line 67 of file writemblock.cpp.
Member Function Documentation
int getPatchNumber (patch * forPatch, int * retFace = NULL) inline
Definition at line 76 of file writemblock.cpp.
References block::nFaces, and patches.
Referenced by mblockData::getPatchListWith().
                 {
                         //Find that patch in our list
                         int patchNo=0;
                         for (int f=0;f<block::nFaces;f++)
                         for (unsigned int p=0;p<patches[f].size();p++)
                                 if (patches[f][p]==forPatch) {
                                         if (retFace!=NULL) *retFace=f;
                                         return patchNo;
                                 }
                                 else
                                         patchNo++;
                         fprintf(stderr,"Can't match patch in %s!\n",__FILE__);
                         abort();
                         return 0;
                 }
void init (block * b) inline
Definition at line 70 of file writemblock.cpp.
References block::getFace(), face::getPatches(), block::nFaces, and patches.
{
                         for (int f=0;f<block::nFaces;f++)
                                 patches[f]=b->getFace(f).getPatches();
                 }
void swap (int & a, int & b) inline
Definition at line 75 of file writemblock.cpp.
 {int tmp=a;a=b;b=tmp;}
int totalPatches (void) const inline
Definition at line 92 of file writemblock.cpp.
References block::nFaces, and patches.
Referenced by write().
{
                         int ret=0;
                         for (int f=0;f<block::nFaces;f++)
                           ret+=patches[f].size();
                         return ret;
                 }
void write (FILE * out, mblockData & d, block * b)
Definition at line 168 of file writemblock.cpp.
References block::getBlockNumber(), block::getDim(), block::nFaces, patches, totalPatches(), and writeMblock().
Referenced by mblockData::write().
 {
         //Write the block header:
         fprintf(out,"# Charm++ Mblock framework block boundary condition file\n");
         fprintf(out,"1.0 # Version number\n");
         fprintf(out,"%d   %d %d %d  # Block number and size\n",b->getBlockNumber(),
                 b->getDim()[0],b->getDim()[1],b->getDim()[2]);
         fprintf(out,"%d %d # Number of faces, patches\n",block::nFaces,totalPatches());
         for (int f=0;f<block::nFaces;f++)
         {
                 fprintf(out,"\n%d  # Number of patches on this face\n",
                         (int)patches[f].size());
                 for (unsigned int p=0;p<patches[f].size();p++)
                         patches[f][p]->writeMblock(out,d);
         }
 }
Member Data Documentation
vector<patch *> patches[block::nFaces]
Definition at line 69 of file writemblock.cpp.
Referenced by mblockData::getPatchListWith(), getPatchNumber(), init(), totalPatches(), and write().
The documentation for this class was generated from the following file:
writemblock.cpp