Rocstar: Rocprop Class Reference
Rocprop Class Reference
#include <Rocprop.h>
Public Types
enum { PROP_FO, PROP_MP }
Public Member Functions
Rocprop ()
Defautl constructor.
virtual ~Rocprop ()
void initialize (const COM::Attribute *pmesh, SURF::Rocsurf *rsurf=NULL)
Initialize Rocprop with given mesh.
void perturb_mesh (COM::Attribute *pmesh, const double &alpha)
Perturb the given mesh by alpha times shortest edge length.
void set_constraints (const COM::Attribute *cnstr_types)
Set the types and directions of constraints Propagation_3::set_constraints.
void set_bounds (const COM::Attribute *bnd)
Set the bounds Propagation_3::set_bounds.
void propagate (const COM::Attribute *pmesh, COM::Attribute *vel, const double *dt, COM::Attribute *du, double *dt_elapsed=NULL, int *code=NULL)
Propagates the interface.
void set_remesher (void *rem, int *owner=0)
Register remesher. Rocprop does not own the remesher.
void remesh_serial (COM::Attribute *mesh_out, double *lave=NULL, double *fangle=NULL)
Invoke serial remeshing.
void set_option (const char *opt, const char *val)
Set options for propagation.
virtual Manifold * manifold ()
int validate_object () const
Static Public Member Functions
static void load (const std::string &mname)
static void unload (const std::string &mname)
Protected Types
enum { PROP_COOKIE =7627873 }
Protected Attributes
SURF::Rocsurf * _parent
Propagation_3 * _prop
COM::Window * _win
COM::Window * _buf
Remesher_base * _rem
int _rem_owner
int _prop_method
char _wf_expn
char _wght_scheme
char _nrm_dfsn
char _feature_layer
double _eig_thres
double _courant
double _fangle_strong
double _fangle_weak
double _fangle_turn
int _verb
const COM::Attribute * _cnstr_types
const COM::Attribute * _cnstr_bound
double _time_lb
int _smoother
int _rediter
int _conserv
int _rank
int _cookie
Detailed Description
Definition at line 44 of file Rocprop.h.
Member Enumeration Documentation
anonymous enum
Enumerator
PROP_FO
PROP_MP
Definition at line 46 of file Rocprop.h.
 { PROP_FO, PROP_MP};
anonymous enum protected
Enumerator
PROP_COOKIE
Definition at line 129 of file Rocprop.h.
 { PROP_COOKIE=7627873};
Constructor & Destructor Documentation
Rocprop () inline
Defautl constructor.
Definition at line 49 of file Rocprop.h.
             : _parent(NULL), _prop(NULL), _win(NULL), _buf(NULL), _rem(NULL),
               _prop_method(PROP_FO), _wf_expn(-1), _wght_scheme(-1),
               _nrm_dfsn(-1), _feature_layer(-1), _eig_thres(-1),
               _courant( -1), _fangle_strong(-1),
               _fangle_weak(-1), _fangle_turn(-1), _verb(0), _cnstr_types(NULL),
               _cnstr_bound(NULL), _time_lb(1./128), _smoother( -1), _rediter(4),
               _conserv(-1), _cookie(PROP_COOKIE) {}
~Rocprop () virtual
Definition at line 35 of file Rocprop.C.
                   {
   // Delete Window_manifold_2, Window, and Propagation_3 objects.
   if ( _wm) { delete _wm; _wm = NULL; }
   if ( _buf){ delete _buf; _buf = NULL; }
   if ( _prop) { delete _prop; _prop = NULL; }
   if ( _rem && _rem_owner) { delete _rem; _rem = NULL; }
 }
Member Function Documentation
void initialize (const COM::Attribute * pmesh, SURF::Rocsurf * rsurf = NULL)
Initialize Rocprop with given mesh.
Definition at line 44 of file Rocprop.C.
References COM_assertion_msg, COM_CONN, COM_NC, COM_PCONN, COMMPI_Comm_rank(), COMMPI_Initialized(), and Rocsurf::initialize().
Referenced by load().
 {
   COM_assertion_msg( validate_object()==0, "Invalid object");
   COM_assertion_msg( pmesh, "Mesh must be present");
   _win = const_cast<COM::Window*>(pmesh->window());
   _parent = rsurf;
   MPI_Comm comm = _win->get_communicator();
   if ( COMMPI_Initialized())  _rank = COMMPI_Comm_rank(comm);
   else _rank = 0;
   if ( _parent==NULL) {
     // Initialize the superclass
     Rocsurf::initialize( pmesh);
   }
   else {
     // If has a parent, then use the Window_manifold_2 of parent
     // and clear up this object's Window_manifold_2 if created.
     if ( _wm) { delete _wm; _wm = NULL; }
     COM_assertion_msg(rsurf->manifold(), "Manifold of parent must exist");
   }
   // Delete propagation object
   if ( _prop) { delete _prop; _prop = NULL; }
   // Create a buffer window to clone the coordinates but use nc and pconn.
   if ( _buf) delete _buf;
   _buf = new COM::Window( _win->name()+"-propbuffer", comm);
   _buf->inherit( _win->attribute( COM::COM_CONN), "",
                  COM::Pane::INHERIT_USE, true, NULL, 0);
   _buf->inherit( _win->attribute( COM::COM_NC), "",
                  COM::Pane::INHERIT_USE, true, NULL, 0);
   _buf->inherit( _win->attribute( COM::COM_NC), "oldnc",
                  COM::Pane::INHERIT_CLONE, true, NULL, 0);
   _buf->inherit( _win->attribute( COM::COM_PCONN), "",
                  COM::Pane::INHERIT_USE, true, NULL, 0);
   _buf->init_done();
 }
void load (const std::string & mname) static
Definition at line 322 of file Rocprop.C.
References COM_DOUBLE, COM_INT, COM_METADATA, COM_new_attribute(), COM_new_window(), COM_RAWDATA, COM_set_member_function(), COM_set_object(), COM_STRING, COM_VOID, COM_window_init_done(), Rocsurf::compute_edge_lengths(), initialize(), perturb_mesh(), propagate(), remesh_serial(), set_bounds(), set_constraints(), set_option(), and set_remesher().
Referenced by Rocprop_load_module(), rocprop_load_module(), ROCPROP_LOAD_MODULE(), rocprop_load_module_(), and ROCPROP_LOAD_MODULE_().
{
   Rocprop *rp = new Rocprop();
   COM_new_window( mname.c_str());
   std::string glb=mname+".global";
   COM_new_attribute( glb.c_str(), 'w', COM_VOID, 1, "");
   COM_set_object( glb.c_str(), 0, rp);
   COM_Type types[7];
   types[0] = types[2] = COM_RAWDATA; types[1] = COM_METADATA;
   COM_set_member_function( (mname+".initialize").c_str(),
                            (Member_func_ptr)(&Rocprop::initialize),
                            glb.c_str(), "biB", types);
   COM_set_member_function( (mname+".set_constraints").c_str(),
                            (Member_func_ptr)(&Rocprop::set_constraints),
                            glb.c_str(), "bi", types);
   COM_set_member_function( (mname+".set_bounds").c_str(),
                            (Member_func_ptr)(&Rocprop::set_bounds),
                            glb.c_str(), "bi", types);
   types[2] = COM_DOUBLE;
   COM_set_member_function( (mname+".perturb_mesh").c_str(),
                            (Member_func_ptr)(&Rocprop::perturb_mesh),
                            glb.c_str(), "bbi", types);
   types[2] = types[4] = COM_METADATA; types[3] = types[5] = COM_DOUBLE;
   types[6]=COM_INT;
   COM_set_member_function( (mname+".propagate").c_str(),
                            (Member_func_ptr)(&Rocprop::propagate),
                            glb.c_str(), "bibioOO", types);
   types[1] = types[2] = COM_STRING;
   COM_set_member_function( (mname+".set_option").c_str(),
                            (Member_func_ptr)(&Rocprop::set_option),
                            glb.c_str(), "bii", types);
   types[1] = COM_METADATA; types[2] = types[3] = COM_DOUBLE;
   COM_set_member_function( (mname+".remesh_serial").c_str(),
                            (Member_func_ptr)(&Rocprop::remesh_serial),
                            glb.c_str(), "boII", types);
   types[1] = COM_VOID; types[2] = COM_INT;
   COM_set_member_function( (mname+".set_remesher").c_str(),
                            (Member_func_ptr)(&Rocprop::set_remesher),
                            glb.c_str(), "biI", types);
   // Register inherited member functions from Rocsurf.
   std::string glb_surf=mname+".global_surf";
   Rocsurf *surf = rp;
   COM_new_attribute( glb_surf.c_str(), 'w', COM_VOID, 1, "");
   COM_set_object( glb_surf.c_str(), 0, surf);
   types[1] = types[2] = types[3] = COM_DOUBLE;
   COM_set_member_function( (mname+".compute_edge_lengths").c_str(),
                            (Member_func_ptr)(&Rocsurf::compute_edge_lengths),
                            glb_surf.c_str(), "boOO", types);
   COM_window_init_done( mname.c_str());
 }
virtual Manifold* manifold () inline virtual
Definition at line 120 of file Rocprop.h.
References _parent.
   { return _wm?_wm:(_parent?_parent->manifold():NULL); }
void perturb_mesh (COM::Attribute * pmesh, const double & alpha)
Perturb the given mesh by alpha times shortest edge length.
Definition at line 85 of file Rocprop.C.
References COM_assertion_msg.
Referenced by load().
{
   COM_assertion_msg( validate_object()==0, "Invalid object");
   // If Rocprop is not yet initialized, call the initialization routine.
   SURF::Window_manifold_2 *wm = manifold();
   if ( wm == NULL)
   { initialize( pmesh, _parent); wm = manifold(); }
   wm->perturb_mesh( alpha);
 }
void propagate (const COM::Attribute * pmesh, COM::Attribute * vel, const double * dt, COM::Attribute * du, double * dt_elapsed = NULL, int * code = NULL)
Propagates the interface.
This function subcycles until it reachs given time step or sub-time-step becomes too small. If the time step became too small, then abort if code is NULL, or return -1 if code is not NULL.
Definition at line 106 of file Rocprop.C.
References Rocblas::add(), COM_assertion, COM_assertion_msg, COM_NC, Rocblas::copy(), i, and Rocblas::sub().
Referenced by load().
 {
   COM_assertion_msg( validate_object()==0, "Invalid object");
   // If Rocprop is not yet initialized, call the initialization routine.
   SURF::Window_manifold_2 *wm = manifold();
   if ( wm == NULL)
   { initialize( pmesh, _parent); wm = manifold(); }
   COM_assertion_msg( pmesh->window() == _win,
                      "Rocprop was initialized for a different window");
   // If the propagation object is not yet created, create a default one.
   if ( _prop == NULL) {
     if ( _prop_method == PROP_FO)
       _prop = new FaceOffset_3( wm, _buf);
     else
       _prop = new MarkerParticles_3( wm, _buf);
   }
   // Save the coordinates into buffers
   COM::Attribute *nc = _buf->attribute( COM::COM_NC);
   COM::Attribute *oldnc = _buf->attribute( "oldnc");
   Rocblas::copy( nc, oldnc);
   // Initialize constraints
   _prop->set_constraints( _cnstr_types);
   _prop->set_bounds( _cnstr_bound);
   _prop->set_verbose(_verb);
   // Set tolerance for eigenvalues.
   if ( _prop_method == PROP_FO) {
     if ( _eig_thres>=0)
       ((FaceOffset_3*)_prop)->set_eigen_threshold( _eig_thres);
     if ( _courant>=0)
       ((FaceOffset_3*)_prop)->set_courant_constant( _courant);
     if ( _fangle_strong>=0)
       ((FaceOffset_3*)_prop)->set_fangle_strong( _fangle_strong);
     if ( _fangle_weak>=0)
       ((FaceOffset_3*)_prop)->set_fangle_weak( _fangle_weak);
     if ( _fangle_turn>=0)
       ((FaceOffset_3*)_prop)->set_fangle_turn( _fangle_turn);
     if ( _wf_expn>=0)
       ((FaceOffset_3*)_prop)->set_wavefrontal_expansion( _wf_expn);
     if ( _nrm_dfsn>=0)
       ((FaceOffset_3*)_prop)->set_normal_diffusion( _nrm_dfsn);
     if ( _feature_layer>=0)
       ((FaceOffset_3*)_prop)->set_feature_layer( _feature_layer);
     if ( _wght_scheme>=0)
       ((FaceOffset_3*)_prop)->set_weighting_scheme( _wght_scheme);
     if ( _smoother>=0)
       ((FaceOffset_3*)_prop)->set_smoother( _smoother);
     if ( _conserv>=0)
       ((FaceOffset_3*)_prop)->set_conserve( _conserv);
   }
   COM::Attribute *spd = spds_io ?
     _buf->inherit( spds_io, "rpr_spd_buf",
                    COM::Pane::INHERIT_USE, true, NULL, 0) : NULL;
   _buf->init_done( false);
   // Subcycle to take small time steps
   double t = 0, t_rem = *dt;
   while ( t_rem > 0 || *dt==0) {
     // Time stepping
     int smoothed=(_rediter>0);
     double max_dt = _prop->time_stepping( spd, t_rem, du, &smoothed);
     if ( _verb && _rank==0)
       std::cout << "Rocprop: Subcycling with time step " << max_dt << std::endl;
     t = *dt - (t_rem-max_dt);
     t_rem = *dt - t;
     if ( t_rem > 0 && max_dt < *dt * _time_lb) {
       // If code is present, then set it to nonzero value
       // if time step is large.
       if ( code) {
         *code = -1;
         std::cerr << "Rocprop: Given time step could not be reached" << std::endl;
         break;
       }
       else if ( dt_elapsed==NULL) {
         std::cerr << "Rocprop: Time step is smaller than the lower bound "
                   << *dt*_time_lb << '=' << *dt << '*' << _time_lb
                   << "\nMesh is too distorted. Stopping..." << std::endl;
         COM_assertion( max_dt >= *dt * _time_lb); abort();
       }
     }
     if ( code) *code = 0;
     // Add the dispments to the current coordinates
     Rocblas::add( nc, du, nc);
     // Reset the speed function
     if ( _cnstr_bound && spd && spd->is_elemental())
       _prop->bound_facial_speed( spd);
     // If propagation method is face offsetting, then perform mesh smoothing
     // by face offsetting with time step equal to 0.
     if ( _prop_method == PROP_FO) {
       for ( int i=smoothed; i<_rediter; ++i) {
         if ( _verb && _rank==0)
           std::cout << "Rocprop: Perform additional mesh smoothing" << std::endl;
         _prop->time_stepping( NULL, 0, du, NULL);
         Rocblas::add( nc, du, nc);
       }
     }
     // If user request for elapsed time, then do not subcycle.
     if ( dt_elapsed) { *dt_elapsed = t; break; }
     else if ( *dt==0) break;
   }
   // Compute displacements and recover the original coordinates
   Rocblas::sub( nc, oldnc, du);
   Rocblas::copy( oldnc, nc);
   // Deallocate spds_buf
   if ( spd) _buf->delete_attribute( spd->name());
   _buf->init_done( false);
 }
void remesh_serial (COM::Attribute * mesh_out, double * lave = NULL, double * fangle = NULL)
Invoke serial remeshing.
Definition at line 307 of file Rocprop.C.
References COM_assertion, COMMPI_Comm_rank(), COMMPI_Initialized(), and MPI_COMM_WORLD.
Referenced by load().
{
   COM_assertion( !COMMPI_Initialized() || COMMPI_Comm_rank(MPI_COMM_WORLD)==0);
   if ( _rem) {
     double l = lave?*lave:0.;
     if ( l==0) compute_edge_lengths( &l, NULL, NULL);
     _rem->remesh_serial( _wm, mesh_out, l, fangle?*fangle:0.);
   }
   else {
     if ( !COMMPI_Initialized() || COMMPI_Comm_rank( MPI_COMM_WORLD)==0)
       std::cerr << "No remesher was registered" << std::endl;
   }
 }
void set_bounds (const COM::Attribute * bnd)
Set the bounds Propagation_3::set_bounds.
Definition at line 101 of file Rocprop.C.
References COM_assertion_msg.
Referenced by load().
{
   COM_assertion_msg( validate_object()==0, "Invalid object");
   _cnstr_bound = bnd;
 }
void set_constraints (const COM::Attribute * cnstr_types)
Set the types and directions of constraints Propagation_3::set_constraints.
Definition at line 96 of file Rocprop.C.
References COM_assertion_msg.
Referenced by load().
{
   COM_assertion_msg( validate_object()==0, "Invalid object");
   _cnstr_types = cnstr_types;
 }
void set_option (const char * opt, const char * val)
Set options for propagation.
The options supported are: "method": "mp" (marker particles, default), "fo" (face offsetting) "wavefrontal": 0 or 1 (for true or false) "weight": weighting scheme "eigthres": encoding relative threshold for null space. "dirthres": encoding relative threshold for tangent space. "courant": encoding courant constant (between 0 and 1) "fangle": feature face angle, between 0 and 180. "fmode": "auto" (propagate calls f-d automatically), and "manual" "smoother": mesh smoother. "rediter": redistribution iterations. "verbose": verbose level.
Definition at line 234 of file Rocprop.C.
References cimg_library::cimg::atof(), COM_assertion, COM_assertion_msg, cimg_library::cimg::option(), SMOOTHER_ANGLE_WEIGHTED_CENTROID, SMOOTHER_ANISOTROPIC, SMOOTHER_LAPLACIAN, and SMOOTHER_NONE.
Referenced by load().
 {
   COM_assertion_msg( validate_object()==0, "Invalid object");
   std::string option;
   if ( opt) option = opt;
   if ( option == "method") {
     std::string value(val);
     int old_method = _prop_method;
     if ( value == "fo") // Face offsetting
       _prop_method = PROP_FO;
     else
       _prop_method = PROP_MP; // Marker particle
     // Remove old object if method is changed.
     if ( _prop_method != old_method && _prop)
     { delete _prop; _prop=NULL; }
   }
   else if ( option == "eigthres") {
     _eig_thres = std::atof( val);
   }
   else if ( option == "smoother") {
     std::string value(val);
     if ( value == "none")
       _smoother = SMOOTHER_NONE;
     else if ( value == "centroid")
       _smoother = SMOOTHER_ANGLE_WEIGHTED_CENTROID;
     else if ( value == "anisotropic")
       _smoother = SMOOTHER_ANISOTROPIC;
     else {
       COM_assertion( value == "Laplacian" || value == "laplacian");
       _smoother = SMOOTHER_LAPLACIAN;
     }
   }
   else if ( option == "rediter") {
     _rediter = std::atoi( val);
   }
   else if ( option == "conserv") {
     _conserv = std::atoi( val);
   }
   else if ( option == "courant") {
     _courant = std::atof( val);
   }
   else if ( option == "wavefrontal") {
     _wf_expn = std::atoi( val);
   }
   else if ( option == "weight") {
     _wght_scheme = std::atoi( val);
   }
   else if ( option == "normaldif") {
     _nrm_dfsn = std::atoi( val);
   }
   else if ( option == "feature_layer") {
     _feature_layer = std::atoi( val);
   }
   else if ( option == "sangle" || option == "fangle_strong") {
     _fangle_strong = std::atof( val);
   }
   else if ( option == "fangle" || option=="fangle_weak") {
     _fangle_weak = std::atof( val);
   }
   else if ( option == "tangle" || option == "fangle_tun") {
     _fangle_turn = std::atof( val);
   }
   else if ( option == "verbose")
     _verb = atoi( val);
   else
     COM_assertion_msg( false, (std::string("Unknown option ")+option).c_str());
 }
void set_remesher (void * rem, int * owner = 0) inline
Register remesher. Rocprop does not own the remesher.
Definition at line 89 of file Rocprop.h.
References _rem, and _rem_owner.
Referenced by load().
{
     if ( _rem && _rem_owner) delete _rem;
     _rem = (Remesher_base*)rem;
     _rem_owner = owner && *owner;
   }
void unload (const std::string & mname) static
Definition at line 386 of file Rocprop.C.
References COM_assertion_msg, COM_delete_window(), COM_get_object(), and validate_object().
Referenced by Rocprop_unload_module(), rocprop_unload_module(), ROCPROP_UNLOAD_MODULE(), rocprop_unload_module_(), and ROCPROP_UNLOAD_MODULE_().
{
   Rocprop *rp;
   std::string glb=mname+".global";
   COM_get_object( glb.c_str(), 0, &rp);
   COM_assertion_msg( rp->validate_object()==0, "Invalid object");
   delete rp;
   COM_delete_window( mname.c_str());
 }
int validate_object () const inline
Definition at line 123 of file Rocprop.h.
References _cookie, PROP_COOKIE, and Rocsurf::validate_object().
Referenced by unload().
{
     if ( _cookie != PROP_COOKIE) return -1;
     else return Rocsurf::validate_object();
   }
Member Data Documentation
COM::Window* _buf protected
Definition at line 134 of file Rocprop.h.
const COM::Attribute* _cnstr_bound protected
Definition at line 153 of file Rocprop.h.
const COM::Attribute* _cnstr_types protected
Definition at line 152 of file Rocprop.h.
int _conserv protected
Definition at line 158 of file Rocprop.h.
int _cookie protected
Definition at line 161 of file Rocprop.h.
Referenced by validate_object().
double _courant protected
Definition at line 146 of file Rocprop.h.
double _eig_thres protected
Definition at line 145 of file Rocprop.h.
double _fangle_strong protected
Definition at line 147 of file Rocprop.h.
double _fangle_turn protected
Definition at line 149 of file Rocprop.h.
double _fangle_weak protected
Definition at line 148 of file Rocprop.h.
char _feature_layer protected
Definition at line 144 of file Rocprop.h.
char _nrm_dfsn protected
Definition at line 143 of file Rocprop.h.
SURF::Rocsurf* _parent protected
Definition at line 131 of file Rocprop.h.
Referenced by manifold().
Propagation_3* _prop protected
Definition at line 132 of file Rocprop.h.
int _prop_method protected
Definition at line 139 of file Rocprop.h.
int _rank protected
Definition at line 159 of file Rocprop.h.
int _rediter protected
Definition at line 157 of file Rocprop.h.
Remesher_base* _rem protected
Definition at line 136 of file Rocprop.h.
Referenced by set_remesher().
int _rem_owner protected
Definition at line 138 of file Rocprop.h.
Referenced by set_remesher().
int _smoother protected
Definition at line 156 of file Rocprop.h.
double _time_lb protected
Definition at line 155 of file Rocprop.h.
int _verb protected
Definition at line 151 of file Rocprop.h.
char _wf_expn protected
Definition at line 141 of file Rocprop.h.
char _wght_scheme protected
Definition at line 142 of file Rocprop.h.
COM::Window* _win protected
Definition at line 133 of file Rocprop.h.
The documentation for this class was generated from the following files:
Rocprop.h
Rocprop.C