Rocstar: Segment_3< R, T > Class Template Reference
Segment_3< R, T > Class Template Reference
#include <cartesian_classes.h>
Public Types
typedef R_ R
typedef R::RT RT
typedef R::FT FT
typedef R::Segment_3_base RSegment_3
Public Member Functions
Segment_3 ()
Segment_3 (const CGAL::Segment_3< R > &s)
Segment_3 (const CGAL::Point_3< R > &sp, const CGAL::Point_3< R > &ep)
Segment_3 (const RSegment_3 &s)
bool has_on (const CGAL::Point_3< R > &p) const
bool operator== (const CGAL::Segment_3< R > &s) const
bool operator!= (const CGAL::Segment_3< R > &s) const
CGAL::Point_3< R > start () const
CGAL::Point_3< R > end () const
CGAL::Point_3< R > source () const
CGAL::Point_3< R > target () const
CGAL::Point_3< R > min () const
CGAL::Point_3< R > max () const
CGAL::Point_3< R > vertex (int i) const
CGAL::Point_3< R > operator[] (int i) const
FT squared_length () const
CGAL::Direction_3< R > direction () const
CGAL::Segment_3< R > opposite () const
CGAL::Segment_3< R > transform (const CGAL::Aff_transformation_3< R > &t) const
CGAL::Line_3< R > supporting_line () const
bool is_degenerate () const
Bbox_3 bbox () const
Detailed Description
template<class R, class T = typename R::Rep_tag>
class Segment_3< R, T >
Definition at line 83 of file cartesian_classes.h.
Member Typedef Documentation
typedef R::FT FT
Definition at line 87 of file Segment_3.h.
typedef R_ R
Definition at line 85 of file Segment_3.h.
typedef R::Segment_3_base RSegment_3
Definition at line 88 of file Segment_3.h.
typedef R::RT RT
Definition at line 86 of file Segment_3.h.
Constructor & Destructor Documentation
Segment_3 () inline
Definition at line 90 of file Segment_3.h.
               : RSegment_3()
   {}
Segment_3 (const CGAL::Segment_3< R > & s) inline
Definition at line 92 of file Segment_3.h.
                                        : RSegment_3(s)
   {}
Segment_3 (const CGAL::Point_3< R > & sp, const CGAL::Point_3< R > & ep) inline
Definition at line 94 of file Segment_3.h.
     : RSegment_3(sp,ep)
   {}
Segment_3 (const RSegment_3< R, T > & s) inline
Definition at line 97 of file Segment_3.h.
                                   : RSegment_3(s)
   {}
Member Function Documentation
Bbox_3 bbox () const inline
Definition at line 134 of file Segment_3.h.
References Segment_3< R, T >::source(), and Segment_3< R, T >::target().
   { return source().bbox() + target().bbox(); }
CGAL::Direction_3<R> direction () const inline
Definition at line 124 of file Segment_3.h.
   { return RSegment_3::direction(); }
CGAL::Point_3<R> end () const inline
Definition at line 108 of file Segment_3.h.
   { return RSegment_3::end(); }
bool has_on (const CGAL::Point_3< R > & p) const inline
Definition at line 100 of file Segment_3.h.
   { return RSegment_3::has_on(p); }
bool is_degenerate () const inline
Definition at line 132 of file Segment_3.h.
   { return RSegment_3::is_degenerate(); }
CGAL::Point_3<R> max () const inline
Definition at line 116 of file Segment_3.h.
References max().
   { return RSegment_3::max(); }
CGAL::Point_3<R> min () const inline
Definition at line 114 of file Segment_3.h.
References min().
   { return RSegment_3::min(); }
bool operator!= (const CGAL::Segment_3< R > & s) const inline
Definition at line 104 of file Segment_3.h.
References s.
   { return !(*this == s); }
bool operator== (const CGAL::Segment_3< R > & s) const inline
Definition at line 102 of file Segment_3.h.
References operator==().
   { return RSegment_3::operator==(s); }
CGAL::Point_3<R> operator[] (int i) const inline
Definition at line 120 of file Segment_3.h.
References Segment_3< R, T >::vertex().
   { return vertex(i); }
CGAL::Segment_3<R> opposite () const inline
Definition at line 126 of file Segment_3.h.
References Segment_3< R, T >::source(), and Segment_3< R, T >::target().
   { return CGAL::Segment_3<R>(target(),source()); }
CGAL::Point_3<R> source () const inline
Definition at line 110 of file Segment_3.h.
Referenced by Segment_3< R, T >::bbox(), and Segment_3< R, T >::opposite().
   { return RSegment_3::source(); }
FT squared_length () const inline
Definition at line 122 of file Segment_3.h.
   { return RSegment_3::squared_length(); }
CGAL::Point_3<R> start () const inline
Definition at line 106 of file Segment_3.h.
   { return RSegment_3::start(); }
CGAL::Line_3<R> supporting_line () const inline
Definition at line 130 of file Segment_3.h.
   { return RSegment_3::supporting_line(); }
CGAL::Point_3<R> target () const inline
Definition at line 112 of file Segment_3.h.
Referenced by Segment_3< R, T >::bbox(), and Segment_3< R, T >::opposite().
   { return RSegment_3::target(); }
CGAL::Segment_3<R> transform (const CGAL::Aff_transformation_3< R > & t) const inline
Definition at line 128 of file Segment_3.h.
   { return RSegment_3::transform(t); }
CGAL::Point_3<R> vertex (int i) const inline
Definition at line 118 of file Segment_3.h.
Referenced by Segment_3< R, T >::operator[]().
   { return RSegment_3::vertex(i); }
The documentation for this class was generated from the following files:
cartesian_classes.h
Segment_3.h