Rocstar: MassTransfer_SF_ALE Class Reference
MassTransfer_SF_ALE Class Reference
#include <transfer_actions.h>
Public Member Functions
MassTransfer_SF_ALE (FluidAgent *ag, SolidAgent *sag, BurnAgent *bag, const std::string f_mdot)
void init (double t)
void run (double t, double dt, double alpha)
Public Member Functions inherited from InterMeshTransfer
InterMeshTransfer (FluidAgent *fag, SolidAgent *sag, char *name=NULL)
Public Member Functions inherited from Action
Action (void *p=0, char *name=NULL)
Action (int n, const char *at[], int *i=NULL, void *p=0, char *name=NULL)
Action (int n, const std::string at[], int *i=NULL, void *p=0, char *name=NULL)
virtual ~Action ()
virtual void declare (Scheduler &)
virtual void finalize ()
virtual char * name ()
void set_name (const char *name)
virtual void print (FILE *f)
virtual void print_toposort (FILE *f)
virtual void schedule ()
Private Attributes
BurnAgent * bagent
int f_mdot_hdl
int b_rhos_hdl
int b_rb_hdl
int fb_mdot_hdl
int f_total_disp_hdl
int f_nc_hdl
int f_nc_t0_hdl
int s_mdot_hdl
int RFC_transfer
Additional Inherited Members
Protected Types inherited from Action
enum { IN =1, OUT =2, INOUT =3 }
Protected Member Functions inherited from InterMeshTransfer
void load_rocface (const RocmanControl_parameters *param)
Protected Member Functions inherited from Action
int get_attribute_handle (int i)
int get_attribute_handle_const (int i)
int get_attribute_handle (const std::string str)
void set_attr (int n, const std::string at[], int *id=NULL)
void set_attr (int n, const char *at[], int *id=NULL)
void set_io (int n, const int *io)
void set_io (const char *io)
int get_io (int i)
Protected Attributes inherited from InterMeshTransfer
FluidAgent * fagent
SolidAgent * sagent
Protected Attributes inherited from Action
char * action_name
char ** attr
int * idx
int count
void * usr_ptr
std::vector< int > inout
Detailed Description
Definition at line 187 of file transfer_actions.h.
Constructor & Destructor Documentation
MassTransfer_SF_ALE (FluidAgent * ag, SolidAgent * sag, BurnAgent * bag, const std::string f_mdot)
Definition at line 916 of file transfer_actions.C.
References bagent, COM_DOUBLE, InterMeshTransfer::fagent, BurnAgent::iburn_all, FluidAgent::ifluid_i, Action::OUT, BurnAgent::parentWin, Agent::register_new_attribute(), Agent::register_use_attribute(), Action::set_attr(), and Action::set_io().
                                                         :
   InterMeshTransfer(fag, sag, (char *)"MassTransfer_SF_ALE"),
                  bagent(bag)
 {
   int io[] = {OUT};
   set_io( 1, io);
   std::string atts[1];
   atts[0] = f_mdot;
   set_attr(1, atts);
   fagent->register_new_attribute(fagent->ifluid_i, ".rhos", 'e', COM_DOUBLE, 1, "kg/(m^3)");
   fagent->register_new_attribute(fagent->ifluid_i, ".mdot", 'e', COM_DOUBLE, 1, "kg/(m^2 s)");
   bagent->register_use_attribute( bagent->iburn_all, ".rhos", bagent->parentWin, ".rhos");
 }
Member Function Documentation
void init (double t) virtual
Reimplemented from Action.
Definition at line 933 of file transfer_actions.C.
References b_rb_hdl, b_rhos_hdl, bagent, COM_get_attribute_handle(), COM_get_function_handle(), f_mdot_hdl, f_nc_hdl, f_nc_t0_hdl, f_total_disp_hdl, InterMeshTransfer::fagent, fb_mdot_hdl, FluidAgent::fluidBufB, FluidAgent::fluidBufNG, Action::get_attribute_handle(), Agent::get_coupling(), Coupling::get_rocmancontrol_param(), BurnAgent::iburn_ng, InterMeshTransfer::load_rocface(), RFC_transfer, s_mdot_hdl, InterMeshTransfer::sagent, and SolidAgent::solidBuf.
{
   //f_mdot_hdl = COM_get_attribute_handle( fagent->fluidBufNG+".mdot");
   f_mdot_hdl = get_attribute_handle( 0);
   b_rhos_hdl = COM_get_attribute_handle( bagent->iburn_ng+".rhos");
   b_rb_hdl = COM_get_attribute_handle( bagent->iburn_ng+".rb");
   fb_mdot_hdl = COM_get_attribute_handle( fagent->fluidBufB+".mdot");
     // ALE
   f_total_disp_hdl = COM_get_attribute_handle(fagent->fluidBufNG+".total_disp");
   f_nc_hdl = COM_get_attribute_handle( fagent->fluidBufNG+".nc");
   f_nc_t0_hdl = COM_get_attribute_handle( fagent->fluidBufNG+".nc_t0");
   s_mdot_hdl = COM_get_attribute_handle( sagent->solidBuf+".mdot");
   load_rocface(fagent->get_coupling()->get_rocmancontrol_param());
   RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
 }
void run (double t, double dt, double alpha) virtual
Reimplemented from Action.
Definition at line 951 of file transfer_actions.C.
References RocBlas::add, b_rb_hdl, b_rhos_hdl, COM_call_function(), RocBlas::copy_scalar, f_mdot_hdl, f_nc_hdl, f_nc_t0_hdl, f_total_disp_hdl, InterMeshTransfer::fagent, fb_mdot_hdl, Agent::get_comm_rank(), MAN_DEBUG, RocBlas::mul, RFC_transfer, s_mdot_hdl, InterMeshTransfer::sagent, and SolidAgent::withALE.
{
   MAN_DEBUG(3, ("[%d] Rocstar: MassTransfer_SF_ALE::run() with t:%e dt:%e.\n", fagent->get_comm_rank(), t, dt));
   if (sagent->withALE) {
     COM_call_function( RocBlas::add,  &f_nc_t0_hdl, &f_total_disp_hdl, &f_nc_hdl);
     COM_call_function( RFC_transfer, &s_mdot_hdl, &f_mdot_hdl);
   }
   else {
     double zero = 0.0;
     COM_call_function( RocBlas::copy_scalar, &zero, &f_mdot_hdl);
     COM_call_function( RocBlas::mul, &b_rhos_hdl, &b_rb_hdl, &fb_mdot_hdl);
   }
 }
Member Data Documentation
int b_rb_hdl private
Definition at line 194 of file transfer_actions.h.
Referenced by init(), and run().
int b_rhos_hdl private
Definition at line 194 of file transfer_actions.h.
Referenced by init(), and run().
BurnAgent* bagent private
Definition at line 193 of file transfer_actions.h.
Referenced by init(), and MassTransfer_SF_ALE().
int f_mdot_hdl private
Definition at line 194 of file transfer_actions.h.
Referenced by init(), and run().
int f_nc_hdl private
Definition at line 195 of file transfer_actions.h.
Referenced by init(), and run().
int f_nc_t0_hdl private
Definition at line 195 of file transfer_actions.h.
Referenced by init(), and run().
int f_total_disp_hdl private
Definition at line 195 of file transfer_actions.h.
Referenced by init(), and run().
int fb_mdot_hdl private
Definition at line 194 of file transfer_actions.h.
Referenced by init(), and run().
int RFC_transfer private
Definition at line 196 of file transfer_actions.h.
Referenced by init(), and run().
int s_mdot_hdl private
Definition at line 195 of file transfer_actions.h.
Referenced by init(), and run().
The documentation for this class was generated from the following files:
transfer_actions.h
transfer_actions.C