Rocstar: MeshImplElemIter Class Reference
MeshImplElemIter Class Reference
ElementIterator for MeshImpl.
#include <MeshImplData.hpp>
Public Member Functions
MeshImplElemIter (MeshImplData *data)
virtual ~MeshImplElemIter ()
virtual void restart ()
Moves the iterator back to the first entity in the list.
virtual void operator++ ()
++iterator
virtual Mesh::ElementHandle operator* () const
*iterator.
virtual bool is_at_end () const
Returns false until the iterator has been advanced PAST the last entity.
MeshImplElemIter (MeshImplData *data)
virtual ~MeshImplElemIter ()
virtual void restart ()
Moves the iterator back to the first entity in the list.
virtual void operator++ ()
++iterator
virtual Mesh::ElementHandle operator* () const
*iterator.
virtual bool is_at_end () const
Returns false until the iterator has been advanced PAST the last entity.
Public Member Functions inherited from EntityIterator
virtual ~EntityIterator ()
Private Attributes
MeshImplData * mesh
size_t index
Detailed Description
ElementIterator for MeshImpl.
Iterate over valid element indices
Definition at line 273 of file includeLinks/MeshImplData.hpp.
Constructor & Destructor Documentation
MeshImplElemIter (MeshImplData * data) inline
Definition at line 281 of file includeLinks/MeshImplData.hpp.
References MeshImplElemIter::restart().
       : mesh(data) { restart(); }
~MeshImplElemIter () virtual
Definition at line 734 of file Mesh/MeshImplData.cpp.
   {}
MeshImplElemIter (MeshImplData * data) inline
Definition at line 281 of file src/Mesh/MeshImplData.hpp.
References MeshImplElemIter::restart().
       : mesh(data) { restart(); }
virtual ~MeshImplElemIter () virtual
Member Function Documentation
bool is_at_end () const virtual
Returns false until the iterator has been advanced PAST the last entity.
Once is_at_end() returns true, *iterator returns 0.
Implements EntityIterator.
Definition at line 756 of file Mesh/MeshImplData.cpp.
References MeshImplElemIter::index, MeshImplData::max_element_index(), and MeshImplElemIter::mesh.
 {
   return index >= mesh->max_element_index();
 }
virtual bool is_at_end () const virtual
Returns false until the iterator has been advanced PAST the last entity.
Once is_at_end() returns true, *iterator returns 0.
Implements EntityIterator.
Mesh::ElementHandle operator* () const virtual
*iterator.
Return the handle currently being pointed at by the iterator.
Implements EntityIterator.
Definition at line 751 of file Mesh/MeshImplData.cpp.
References MeshImplElemIter::index.
 {
   return reinterpret_cast<Mesh::ElementHandle>(index);
 }
virtual Mesh::ElementHandle operator* () const virtual
*iterator.
Return the handle currently being pointed at by the iterator.
Implements EntityIterator.
void operator++ () virtual
++iterator
Implements EntityIterator.
Definition at line 744 of file Mesh/MeshImplData.cpp.
References MeshImplElemIter::index, MeshImplData::is_element_valid(), and MeshImplElemIter::mesh.
 {
   ++index;
   while (index < mesh->max_element_index() && !mesh->is_element_valid(index))
     ++index;
 }
virtual void operator++ () virtual
++iterator
Implements EntityIterator.
void restart () virtual
Moves the iterator back to the first entity in the list.
Implements EntityIterator.
Definition at line 737 of file Mesh/MeshImplData.cpp.
References MeshImplElemIter::index, MeshImplData::is_element_valid(), and MeshImplElemIter::mesh.
Referenced by MeshImplElemIter::MeshImplElemIter().
 {
   index = 0;
   if (!mesh->is_element_valid( index ))
     operator++();
 }
virtual void restart () virtual
Moves the iterator back to the first entity in the list.
Implements EntityIterator.
Member Data Documentation
size_t index private
Definition at line 277 of file includeLinks/MeshImplData.hpp.
Referenced by MeshImplElemIter::is_at_end(), MeshImplElemIter::operator*(), MeshImplElemIter::operator++(), and MeshImplElemIter::restart().
MeshImplData * mesh private
Definition at line 276 of file includeLinks/MeshImplData.hpp.
Referenced by MeshImplElemIter::is_at_end(), MeshImplElemIter::operator++(), and MeshImplElemIter::restart().
The documentation for this class was generated from the following files:
includeLinks/MeshImplData.hpp
Mesh/MeshImplData.cpp