Rocstar: stat_rflu_modrocstaradmin Module Reference
stat_rflu_modrocstaradmin Module Reference
Public Member Functions
subroutine, public stat_rflu_genxcreateattr (pRegion)
subroutine, public stat_rflu_genxregisterdata (pRegion)
subroutine, public stat_rflu_genxgetdata (pRegion)
subroutine, public stat_rflu_genxcreateattr (pRegion)
subroutine, public stat_rflu_genxregisterdata (pRegion)
subroutine, public stat_rflu_genxgetdata (pRegion)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: STAT_RFLU_ModRocstarAdmin.F90,v $ $Revision: 1.8 $'
Detailed Description
Definition at line 39 of file STAT_RFLU_ModGenxAdmin.F90.
Member Function/Subroutine Documentation
subroutine, public stat_rflu_genxcreateattr (type(t_region), pointer pRegion)
Definition at line 101 of file STAT_RFLU_ModGenxAdmin.F90.
Referenced by rflu_modrocstaradmin::rflu_genx_createattrstats().
subroutine, public stat_rflu_genxcreateattr (type(t_region), pointer pRegion)
Definition at line 101 of file STAT_RFLU_ModRocstarAdmin.F90.
subroutine, public stat_rflu_genxgetdata (type(t_region), pointer pRegion)
Definition at line 318 of file STAT_RFLU_ModRocstarAdmin.F90.
subroutine, public stat_rflu_genxgetdata (type(t_region), pointer pRegion)
Definition at line 318 of file STAT_RFLU_ModGenxAdmin.F90.
Referenced by modstatsroutines::initstatistics().
subroutine, public stat_rflu_genxregisterdata (type(t_region), pointer pRegion)
Definition at line 161 of file STAT_RFLU_ModGenxAdmin.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Referenced by rflu_modrocstaradmin::rflu_genx_registerdatastats().
subroutine, public stat_rflu_genxregisterdata (type(t_region), pointer pRegion)
Definition at line 161 of file STAT_RFLU_ModRocstarAdmin.F90.
References rflu_modrocstarutils::rflu_genx_buildpaneid().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: STAT_RFLU_ModRocstarAdmin.F90,v $ $Revision: 1.8 $' private
Definition at line 70 of file STAT_RFLU_ModGenxAdmin.F90.
The documentation for this module was generated from the following files:
STAT_RFLU_ModGenxAdmin.F90
STAT_RFLU_ModRocstarAdmin.F90