Rocstar: modtools Module Reference
modtools Module Reference
Public Member Functions
subroutine swapintegers (a, b)
subroutine swaprfreals (a, b)
real(rfreal) function makenonzero (x)
LOGICAL function floatequal (a, b, tolIn)
LOGICAL function floatgreater (a, b)
LOGICAL function floatless (a, b)
INTEGER function compfact (n)
real(rfreal) function comppythag (a, b)
logical function isnan (x)
Detailed Description
Definition at line 41 of file ModTools.F90.
Member Function/Subroutine Documentation
INTEGER function compfact (integer, intent(in) n)
Definition at line 156 of file ModTools.F90.
References i, and n.
Referenced by rflu_moddifferentiationfaces::rflu_computegradconstrained(), and rflu_modstencilsutils::rflu_computestencilweights().
real(rfreal) function comppythag (real(rfreal), intent(in) a, real(rfreal), intent(in) b)
Definition at line 174 of file ModTools.F90.
References Line_2< R, T >::a(), Color::b(), and sqrt().
LOGICAL function floatequal (real(rfreal), intent(in) a, real(rfreal), intent(in) b, real(rfreal), intent(in), optional tolIn)
Definition at line 99 of file ModTools.F90.
References Line_2< R, T >::a(), and Color::b().
Referenced by inrt_checkuserinput(), rflu_moddimensionality::rflu_123d_checkgeometrykernel(), rflu_modstencilsbfaces::rflu_buildbf2cstencil_1d(), rflu_modstencilsfaces::rflu_buildf2cstencil_1d(), rflu_modoles::rflu_buildstencilsoles(), rflu_modpatchutils::rflu_checkpatchbcconsistency(), rflu_modconstraintutils::rflu_getconstrtype(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_modpatchutils::rflu_getpatchnormaldirection(), rflu_setmovegridoptions(), rflu_modpatchutils::rflu_setpatchflatflags(), and rflu_modsymmetryperiodic::rflu_sype_buildtransforms().
LOGICAL function floatgreater (real(rfreal), intent(in) a, real(rfreal), intent(in) b)
Definition at line 124 of file ModTools.F90.
References Line_2< R, T >::a(), and Color::b().
LOGICAL function floatless (real(rfreal), intent(in) a, real(rfreal), intent(in) b)
Definition at line 140 of file ModTools.F90.
References Line_2< R, T >::a(), and Color::b().
Referenced by rflo_modforcesmoments::rflo_openforcemomcofile(), rflo_openprobefile(), and rflu_modprobes::rflu_openprobefiles().
logical function isnan (real(rfreal), intent(in) x)
Definition at line 201 of file ModTools.F90.
References x.
Referenced by plag_modcheckvars::plag_checkvalidity(), rflo_checkvalidity(), rflo_modmovegridframe::rflo_mgframemovecorners(), rflu_checkvalidity(), and rflu_checkvalidity_gl().
real(rfreal) function makenonzero (real(rfreal), intent(in) x)
Definition at line 85 of file ModTools.F90.
References sign(), and x.
Referenced by bcondinflowperf(), bcondinflowperf_gl(), rflu_computeenerdissoles(), rflu_computeintegral3oles(), rflu_computeweightsoles(), rflu_modoles::rflu_definecorrelation221(), rflu_modoles::rflu_definecorrelation431(), rflu_modoles::rflu_definecorrelation432(), rflu_modoles::rflu_definecorrelation541(), rflu_modoles::rflu_definecorrelation542(), rflu_printchangeinfo(), rflu_printwriteconvergence(), and writeconvergence().
subroutine swapintegers (integer, intent(inout) a, integer, intent(inout) b)
Definition at line 53 of file ModTools.F90.
References Line_2< R, T >::a(), Color::b(), and Line_2< R, T >::c().
Referenced by rflu_modsymmetryperiodic::rflu_sype_augmentcelllists().
subroutine swaprfreals (real(rfreal), intent(inout) a, real(rfreal), intent(inout) b)
Definition at line 69 of file ModTools.F90.
References Line_2< R, T >::a(), Color::b(), and Line_2< R, T >::c().
Referenced by rflu_modbilinearpatch::rflu_blin_computexsectline(), and rflu_modsymmetryperiodic::rflu_sype_augmentcelllists().
The documentation for this module was generated from the following file:
ModTools.F90