Rocstar: rflu_modpartitionregionutils Module Reference
rflu_modpartitionregionutils Module Reference
Public Member Functions
subroutine, public rflu_part_addvirtualcellsinv1 (pRegion, pRegionSerial, vc, nCellsVirtMax, nCellsVirt)
subroutine, public rflu_part_addvirtualcellsinv2 (pRegion, pRegionSerial, vc, nCellsVirtMax, nCellsVirt)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPartitionRegionUtils.F90,v $ $Revision: 1.8 $'
Detailed Description
Definition at line 39 of file RFLU_ModPartitionRegionUtils.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_part_addvirtualcellsinv1 (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial, integer, dimension(ncellsvirtmax), intent(inout) vc, integer, intent(in) nCellsVirtMax, integer, intent(out) nCellsVirt)
Definition at line 97 of file RFLU_ModPartitionRegionUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), and moderror::registerfunction().
Referenced by rflu_modpartitionregion::rflu_part_addvirtualcells().
subroutine, public rflu_part_addvirtualcellsinv2 (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial, integer, dimension(ncellsvirtmax), intent(inout) vc, integer, intent(in) nCellsVirtMax, integer, intent(out) nCellsVirt)
Definition at line 237 of file RFLU_ModPartitionRegionUtils.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), i, idir, j, Mesh::GenericCell_2::nvert(), modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modtopologyutils::rflu_buildfacevertlist(), rflu_modtopologyutils::rflu_buildvertcellnghblist(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), and rflu_modstencilscells::rflu_setinfoc2cstencilwrapper().
Referenced by rflu_modpartitionregion::rflu_part_addvirtualcells().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModPartitionRegionUtils.F90,v $ $Revision: 1.8 $' private
Definition at line 62 of file RFLU_ModPartitionRegionUtils.F90.
The documentation for this module was generated from the following file:
RFLU_ModPartitionRegionUtils.F90