Rocstar: bitmap Class Reference
bitmap Class Reference
#include <util.h>
Public Member Functions
bitmap ()
~bitmap ()
bitmap (const bitmap &b)
bitmap & operator= (const bitmap &b)
void set_size (int n)
int get_size ()
void set_value (int n)
void unset_value (int n)
bool check_value (int n)
Private Attributes
int * map
bool map_set
int size
Detailed Description
Definition at line 93 of file utilities/rc_cmp/util.h.
Constructor & Destructor Documentation
bitmap ()
Definition at line 454 of file utilities/rc_cmp/util.cpp.
References map_set.
               {
     map_set = false;
     return;
 }
~bitmap ()
Definition at line 459 of file utilities/rc_cmp/util.cpp.
References map, and map_set.
                {
     if(map_set)
         delete[] map;
 }
bitmap (const bitmap & b)
Definition at line 464 of file utilities/rc_cmp/util.cpp.
References i, map, map_set, and size.
{
     size = b.size;
     map_set = b.map_set;
     int arr_size = size / (sizeof(int)*8);
     arr_size++;
     if(map_set){
         map = new int[arr_size];
         for(int i=0; i<arr_size; i++){
             map[i] = b.map[i];
         }
     }
 }
Member Function Documentation
bool check_value (int n)
Definition at line 579 of file utilities/rc_cmp/util.cpp.
References map, and size.
Referenced by points::get_point(), points::operator=(), points::points(), points::set_num_points(), points::set_point_val(), and points::~points().
{
     if(n >= size || n < 0)
         return false;
     int index = n / (sizeof(int) * 8);
     int num   = n % (sizeof(int) * 8);
     int entry = map[index];
     entry = entry >> num;
     entry = entry & 0x00000001;
     if(entry == 0x00000001)
         return true;
     return false;
 }
int get_size ()
Definition at line 542 of file utilities/rc_cmp/util.cpp.
References size.
                     {
     return size;
 }
bitmap & operator= (const bitmap & b)
Definition at line 480 of file utilities/rc_cmp/util.cpp.
References i, map, map_set, and size.
{
     if(this != &b){
         if(map_set)
             delete[] map;
         size = b.size;
         map_set = b.map_set;
         int arr_size = size / (sizeof(int)*8);
         arr_size++;
         if(map_set){
             map = new int[arr_size];
             for(int i=0; i<arr_size; i++){
                 int temp = b.map[i];
                 map[i] = temp;
             }
         }
     }
     return *this;
 }
void set_size (int n)
Definition at line 506 of file utilities/rc_cmp/util.cpp.
References i, map, map_set, and size.
Referenced by points::set_num_points().
{
     int new_size = n / (sizeof(int)*8);
     new_size++;
     int old_size = size / (sizeof(int)*8);
     old_size++;
     if(!map_set){
         map = new int[ new_size ];
         for(int i=0; i < new_size; i++){
             map[i] = 0;
         }
     }
     else{
         int *temp;
         temp = new int[ new_size ];
         for(int i=0; i < new_size; i++){
             temp[i] = 0;
         }
         for(int i=0; i < old_size; i++){
             temp[i] = map[i];
         }
         delete[] map;
         map = temp;
     }
     size = n;
     map_set = true;
 }
void set_value (int n)
Definition at line 546 of file utilities/rc_cmp/util.cpp.
References map.
Referenced by points::set_point_val().
{
     int index = n / (sizeof(int) * 8);
     int num   = n % (sizeof(int) * 8);
     int entry = map[index];
     int set = 0x00000001;
     set = set << num;
     entry = entry | set;
     map[index] = entry;
 }
void unset_value (int n)
Definition at line 562 of file utilities/rc_cmp/util.cpp.
References map.
{
     int index = n / (sizeof(int) * 8);
     int num   = n % (sizeof(int) * 8);
     int entry = map[index];
     int set = 0x00000001;
     set = set << num;
     set = ~set;
     entry = entry & set;
     map[index] = entry;
 }
Member Data Documentation
int* map private
Definition at line 118 of file utilities/rc_cmp/util.h.
Referenced by bitmap(), check_value(), operator=(), set_size(), set_value(), unset_value(), and ~bitmap().
bool map_set private
Definition at line 120 of file utilities/rc_cmp/util.h.
Referenced by bitmap(), operator=(), set_size(), and ~bitmap().
int size private
Definition at line 123 of file utilities/rc_cmp/util.h.
Referenced by bitmap(), check_value(), get_size(), operator=(), and set_size().
The documentation for this class was generated from the following files:
utilities/rc_cmp/util.h
utilities/rc_cmp/util.cpp