Rocstar: Halfedge_data_structure_using_vector< V, H, F > Class Template Reference
Halfedge_data_structure_using_vector< V, H, F > Class Template Reference
#include <Halfedge_data_structure_using_vector.h>
Public Types
typedef
Halfedge_data_structure_using_vector
< V, H, F > Self
typedef _HDS_vector_vertex< V,
H, F > Vertex
typedef _HDS_vector_halfedge
< V, H, F > Halfedge
typedef _HDS_vector_facet< V,
H, F > Facet
typedef Vertex::Point Point
typedef Facet::Normal Normal
typedef Facet::Plane Plane
typedef Halfedge_vector::size_type Size
typedef
Halfedge_vector::difference_type Difference
typedef
Vertex::Supports_vertex_halfedge Supports_vertex_halfedge
typedef
Halfedge::Supports_halfedge_prev Supports_halfedge_prev
typedef
Halfedge::Supports_halfedge_vertex Supports_halfedge_vertex
typedef
Halfedge::Supports_halfedge_facet Supports_halfedge_facet
typedef
Facet::Supports_facet_halfedge Supports_facet_halfedge
typedef
Vertex::Supports_vertex_point Supports_vertex_point
typedef Facet::Supports_facet_plane Supports_facet_plane
typedef
Facet::Supports_facet_normal Supports_facet_normal
typedef Tag_false Supports_removal
typedef
std::random_access_iterator_tag iterator_category
typedef Vertex_vector::iterator Vertex_iterator
typedef Halfedge_vector::iterator Halfedge_iterator
typedef Facet_vector::iterator Facet_iterator
typedef N_step_adaptor
< Halfedge_iterator,
2, Halfedge &, Halfedge
*, Halfedge, std::ptrdiff_t,
iterator_category > Edge_iterator
typedef
Vertex_vector::const_iterator Vertex_const_iterator
typedef
Halfedge_vector::const_iterator Halfedge_const_iterator
typedef
Facet_vector::const_iterator Facet_const_iterator
typedef N_step_adaptor
< Halfedge_const_iterator,
2, const Halfedge &, const
Halfedge *, Halfedge,
std::ptrdiff_t,
iterator_category > Edge_const_iterator
typedef
Halfedge_data_structure_using_vector
< V, H, F > Self
typedef _HDS_vector_vertex< V,
H, F > Vertex
typedef _HDS_vector_halfedge
< V, H, F > Halfedge
typedef _HDS_vector_facet< V,
H, F > Facet
typedef Vertex::Point Point
typedef Facet::Normal Normal
typedef Facet::Plane Plane
typedef Halfedge_vector::size_type Size
typedef
Halfedge_vector::difference_type Difference
typedef
Vertex::Supports_vertex_halfedge Supports_vertex_halfedge
typedef
Halfedge::Supports_halfedge_prev Supports_halfedge_prev
typedef
Halfedge::Supports_halfedge_vertex Supports_halfedge_vertex
typedef
Halfedge::Supports_halfedge_facet Supports_halfedge_facet
typedef
Facet::Supports_facet_halfedge Supports_facet_halfedge
typedef
Vertex::Supports_vertex_point Supports_vertex_point
typedef Facet::Supports_facet_plane Supports_facet_plane
typedef
Facet::Supports_facet_normal Supports_facet_normal
typedef Tag_false Supports_removal
typedef
std::random_access_iterator_tag iterator_category
typedef Vertex_vector::iterator Vertex_iterator
typedef Halfedge_vector::iterator Halfedge_iterator
typedef Facet_vector::iterator Facet_iterator
typedef N_step_adaptor
< Halfedge_iterator,
2, Halfedge &, Halfedge
*, Halfedge, std::ptrdiff_t,
iterator_category > Edge_iterator
typedef
Vertex_vector::const_iterator Vertex_const_iterator
typedef
Halfedge_vector::const_iterator Halfedge_const_iterator
typedef
Facet_vector::const_iterator Facet_const_iterator
typedef N_step_adaptor
< Halfedge_const_iterator,
2, const Halfedge &, const
Halfedge *, Halfedge,
std::ptrdiff_t,
iterator_category > Edge_const_iterator
Public Member Functions
Halfedge_data_structure_using_vector ()
Halfedge_data_structure_using_vector (Size v, Size h, Size f)
void reserve (Size v, Size h, Size f)
Halfedge_data_structure_using_vector (const Self &hds)
Self & operator= (const Self &hds)
Size size_of_vertices () const
Size size_of_halfedges () const
Size size_of_facets () const
Size capacity_of_vertices () const
Size capacity_of_halfedges () const
Size capacity_of_facets () const
std::size_t bytes () const
std::size_t bytes_reserved () const
Vertex_iterator vertices_begin ()
Vertex_iterator vertices_end ()
Halfedge_iterator halfedges_begin ()
Halfedge_iterator halfedges_end ()
Facet_iterator facets_begin ()
Facet_iterator facets_end ()
Edge_iterator edges_begin ()
Edge_iterator edges_end ()
Vertex_const_iterator vertices_begin () const
Vertex_const_iterator vertices_end () const
Halfedge_const_iterator halfedges_begin () const
Halfedge_const_iterator halfedges_end () const
Facet_const_iterator facets_begin () const
Facet_const_iterator facets_end () const
Edge_const_iterator edges_begin () const
Edge_const_iterator edges_end () const
Vertex * new_vertex ()
Vertex * new_vertex (const Vertex *v)
Vertex * new_vertex (const Point &p)
Halfedge * new_edge ()
Halfedge * new_edge (const Halfedge *he)
Facet * new_facet ()
Facet * new_facet (const Facet *f)
void delete_all ()
void vertex_pop_back ()
void edge_pop_back ()
void facet_pop_back ()
Size size_of_border_halfedges () const
Size size_of_border_edges () const
Halfedge_iterator border_halfedges_begin ()
Edge_iterator border_edges_begin ()
Halfedge_const_iterator border_halfedges_begin () const
Edge_const_iterator border_edges_begin () const
void normalize_border ()
Halfedge_data_structure_using_vector ()
Halfedge_data_structure_using_vector (Size v, Size h, Size f)
void reserve (Size v, Size h, Size f)
Halfedge_data_structure_using_vector (const Self &hds)
Self & operator= (const Self &hds)
Size size_of_vertices () const
Size size_of_halfedges () const
Size size_of_facets () const
Size capacity_of_vertices () const
Size capacity_of_halfedges () const
Size capacity_of_facets () const
std::size_t bytes () const
std::size_t bytes_reserved () const
Vertex_iterator vertices_begin ()
Vertex_iterator vertices_end ()
Halfedge_iterator halfedges_begin ()
Halfedge_iterator halfedges_end ()
Facet_iterator facets_begin ()
Facet_iterator facets_end ()
Edge_iterator edges_begin ()
Edge_iterator edges_end ()
Vertex_const_iterator vertices_begin () const
Vertex_const_iterator vertices_end () const
Halfedge_const_iterator halfedges_begin () const
Halfedge_const_iterator halfedges_end () const
Facet_const_iterator facets_begin () const
Facet_const_iterator facets_end () const
Edge_const_iterator edges_begin () const
Edge_const_iterator edges_end () const
Vertex * new_vertex ()
Vertex * new_vertex (const Vertex *v)
Vertex * new_vertex (const Point &p)
Halfedge * new_edge ()
Halfedge * new_edge (const Halfedge *he)
Facet * new_facet ()
Facet * new_facet (const Facet *f)
void delete_all ()
void vertex_pop_back ()
void edge_pop_back ()
void facet_pop_back ()
Size size_of_border_halfedges () const
Size size_of_border_edges () const
Halfedge_iterator border_halfedges_begin ()
Edge_iterator border_edges_begin ()
Halfedge_const_iterator border_halfedges_begin () const
Edge_const_iterator border_edges_begin () const
void normalize_border ()
Protected Types
typedef std::vector< Vertex > Vertex_vector
typedef std::vector< Halfedge > Halfedge_vector
typedef std::vector< Facet > Facet_vector
typedef std::vector< Vertex > Vertex_vector
typedef std::vector< Halfedge > Halfedge_vector
typedef std::vector< Facet > Facet_vector
Protected Member Functions
void update_opposite (Halfedge_iterator h)
void update_opposite (Edge_iterator h)
void update_prev (Halfedge_iterator, Halfedge_iterator, std::vector< Halfedge_iterator >, Tag_false)
void update_prev (Halfedge_iterator h, Halfedge_iterator base, std::vector< Halfedge_iterator > inv, Tag_true)
void update_vertex (Halfedge_iterator, Tag_false, Tag_false)
void update_vertex (Halfedge_iterator, Tag_true, Tag_false)
void update_vertex (Halfedge_iterator, Tag_false, Tag_true)
void update_vertex (Halfedge_iterator h, Tag_true, Tag_true)
void update_facet (Halfedge_iterator, Tag_false, Tag_false)
void update_facet (Halfedge_iterator, Tag_true, Tag_false)
void update_facet (Halfedge_iterator, Tag_false, Tag_true)
void update_facet (Halfedge_iterator h, Tag_true, Tag_true)
void update_opposite (Halfedge_iterator h)
void update_opposite (Edge_iterator h)
void update_prev (Halfedge_iterator, Halfedge_iterator, const std::vector< Halfedge_iterator > &, Tag_false)
void update_prev (Halfedge_iterator h, Halfedge_iterator base, const std::vector< Halfedge_iterator > &inv, Tag_true)
void update_vertex (Halfedge_iterator, Tag_false, Tag_false)
void update_vertex (Halfedge_iterator, Tag_true, Tag_false)
void update_vertex (Halfedge_iterator, Tag_false, Tag_true)
void update_vertex (Halfedge_iterator h, Tag_true, Tag_true)
void update_facet (Halfedge_iterator, Tag_false, Tag_false)
void update_facet (Halfedge_iterator, Tag_true, Tag_false)
void update_facet (Halfedge_iterator, Tag_false, Tag_true)
void update_facet (Halfedge_iterator h, Tag_true, Tag_true)
Protected Attributes
Vertex_vector vertices
Halfedge_vector halfedges
Facet_vector facets
Size nb_border_halfedges
Size nb_border_edges
Halfedge_iterator border_halfedges
Private Member Functions
void pointer_update (Vertex_const_iterator v_old, Halfedge_const_iterator h_old, Facet_const_iterator f_old)
void pointer_update (Vertex_const_iterator v_old, Halfedge_const_iterator h_old, Facet_const_iterator f_old)
Detailed Description
template<class V, class H, class F>
class Halfedge_data_structure_using_vector< V, H, F >
Definition at line 172 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
Member Typedef Documentation
typedef Halfedge_vector::difference_type Difference
Definition at line 193 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge_vector::difference_type Difference
Definition at line 215 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef N_step_adaptor< Halfedge_const_iterator, 2, const Halfedge&, const Halfedge*, Halfedge, std::ptrdiff_t, iterator_category> Edge_const_iterator
Definition at line 230 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef N_step_adaptor< Halfedge_const_iterator, 2, const Halfedge&, const Halfedge*, Halfedge, std::ptrdiff_t, iterator_category> Edge_const_iterator
Definition at line 252 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef N_step_adaptor< Halfedge_iterator, 2, Halfedge&, Halfedge*, Halfedge, std::ptrdiff_t, iterator_category> Edge_iterator
Definition at line 219 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef N_step_adaptor< Halfedge_iterator, 2, Halfedge&, Halfedge*, Halfedge, std::ptrdiff_t, iterator_category> Edge_iterator
Definition at line 241 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_facet<V,H,F> Facet
Definition at line 177 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_facet<V,H,F> Facet
Definition at line 199 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet_vector::const_iterator Facet_const_iterator
Definition at line 223 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet_vector::const_iterator Facet_const_iterator
Definition at line 245 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet_vector::iterator Facet_iterator
Definition at line 212 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet_vector::iterator Facet_iterator
Definition at line 234 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef std::vector<Facet> Facet_vector protected
Definition at line 188 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef std::vector<Facet> Facet_vector protected
Definition at line 210 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_halfedge<V,H,F> Halfedge
Definition at line 176 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_halfedge<V,H,F> Halfedge
Definition at line 198 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge_vector::const_iterator Halfedge_const_iterator
Definition at line 222 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge_vector::const_iterator Halfedge_const_iterator
Definition at line 244 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge_vector::iterator Halfedge_iterator
Definition at line 211 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge_vector::iterator Halfedge_iterator
Definition at line 233 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef std::vector<Halfedge> Halfedge_vector protected
Definition at line 187 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef std::vector<Halfedge> Halfedge_vector protected
Definition at line 209 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef std::random_access_iterator_tag iterator_category
Definition at line 208 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef std::random_access_iterator_tag iterator_category
Definition at line 230 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Normal Normal
Definition at line 181 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Normal Normal
Definition at line 203 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Plane Plane
Definition at line 182 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Plane Plane
Definition at line 204 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex::Point Point
Definition at line 180 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex::Point Point
Definition at line 202 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge_data_structure_using_vector<V,H,F> Self
Definition at line 174 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge_data_structure_using_vector<V,H,F> Self
Definition at line 196 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge_vector::size_type Size
Definition at line 190 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge_vector::size_type Size
Definition at line 212 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Supports_facet_halfedge Supports_facet_halfedge
Definition at line 201 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Supports_facet_halfedge Supports_facet_halfedge
Definition at line 223 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Supports_facet_normal Supports_facet_normal
Definition at line 205 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Supports_facet_normal Supports_facet_normal
Definition at line 227 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Supports_facet_plane Supports_facet_plane
Definition at line 204 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Facet::Supports_facet_plane Supports_facet_plane
Definition at line 226 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge::Supports_halfedge_facet Supports_halfedge_facet
Definition at line 200 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge::Supports_halfedge_facet Supports_halfedge_facet
Definition at line 222 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge::Supports_halfedge_prev Supports_halfedge_prev
Definition at line 196 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge::Supports_halfedge_prev Supports_halfedge_prev
Definition at line 218 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge::Supports_halfedge_vertex Supports_halfedge_vertex
Definition at line 198 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Halfedge::Supports_halfedge_vertex Supports_halfedge_vertex
Definition at line 220 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Tag_false Supports_removal
Definition at line 207 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Tag_false Supports_removal
Definition at line 229 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex::Supports_vertex_halfedge Supports_vertex_halfedge
Definition at line 195 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex::Supports_vertex_halfedge Supports_vertex_halfedge
Definition at line 217 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex::Supports_vertex_point Supports_vertex_point
Definition at line 203 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex::Supports_vertex_point Supports_vertex_point
Definition at line 225 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_vertex<V,H,F> Vertex
Definition at line 175 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef _HDS_vector_vertex<V,H,F> Vertex
Definition at line 197 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex_vector::const_iterator Vertex_const_iterator
Definition at line 221 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex_vector::const_iterator Vertex_const_iterator
Definition at line 243 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex_vector::iterator Vertex_iterator
Definition at line 210 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef Vertex_vector::iterator Vertex_iterator
Definition at line 232 of file include/CGAL/Halfedge_data_structure_using_vector.h.
typedef std::vector<Vertex> Vertex_vector protected
Definition at line 186 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
typedef std::vector<Vertex> Vertex_vector protected
Definition at line 208 of file include/CGAL/Halfedge_data_structure_using_vector.h.
Constructor & Destructor Documentation
Halfedge_data_structure_using_vector () inline
Definition at line 251 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
         : nb_border_halfedges(0), nb_border_edges(0),
           border_halfedges( Halfedge_iterator(NULL)) {}
Halfedge_data_structure_using_vector (Size v, Size h, Size f) inline
Definition at line 256 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
         : nb_border_halfedges(0), nb_border_edges(0),
           border_halfedges( Halfedge_iterator(NULL)) {
         // a polyhedron `P' with storage reserved for v vertices, h
         // halfedges, and f facets. The reservation sizes are a hint for
         // optimizing storage allocation. They are not used here.
         vertices.reserve(v);
         halfedges.reserve(h);
         facets.reserve(f);
     }
Halfedge_data_structure_using_vector (const Self & hds) inline
Definition at line 284 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, Halfedge_data_structure_using_vector< V, H, F >::pointer_update(), and Halfedge_data_structure_using_vector< V, H, F >::vertices.
     :  vertices( hds.vertices),
        halfedges( hds.halfedges),
        facets( hds.facets),
        nb_border_halfedges( hds.nb_border_halfedges),
        nb_border_edges( hds.nb_border_edges),
        border_halfedges( hds.border_halfedges)
     {
         pointer_update( hds.vertices.begin(),
                         hds.halfedges.begin(),
                         hds.facets.begin());
     }
Halfedge_data_structure_using_vector () inline
Definition at line 273 of file include/CGAL/Halfedge_data_structure_using_vector.h.
         : nb_border_halfedges(0), nb_border_edges(0),
           border_halfedges( Halfedge_iterator(NULL)) {}
Halfedge_data_structure_using_vector (Size v, Size h, Size f) inline
Definition at line 278 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
         : nb_border_halfedges(0), nb_border_edges(0),
           border_halfedges( Halfedge_iterator(NULL)) {
         // a polyhedron `P' with storage reserved for v vertices, h
         // halfedges, and f facets. The reservation sizes are a hint for
         // optimizing storage allocation. They are not used here.
         vertices.reserve(v);
         halfedges.reserve(h);
         facets.reserve(f);
     }
Halfedge_data_structure_using_vector (const Self & hds) inline
Definition at line 306 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, Halfedge_data_structure_using_vector< V, H, F >::pointer_update(), and Halfedge_data_structure_using_vector< V, H, F >::vertices.
     :  vertices( hds.vertices),
        halfedges( hds.halfedges),
        facets( hds.facets),
        nb_border_halfedges( hds.nb_border_halfedges),
        nb_border_edges( hds.nb_border_edges),
        border_halfedges( hds.border_halfedges)
     {
         pointer_update( hds.vertices.begin(),
                         hds.halfedges.begin(),
                         hds.facets.begin());
     }
Member Function Documentation
Edge_iterator border_edges_begin () inline
Definition at line 513 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges_begin().
{
         // ... trial to make Edge_iterator obsolete.
         return Edge_iterator(border_halfedges_begin());
     }
Edge_const_iterator border_edges_begin () const inline
Definition at line 526 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges_begin().
{
         return Edge_const_iterator(border_halfedges_begin());
     }
Edge_iterator border_edges_begin () inline
Definition at line 535 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges_begin().
{
         // ... trial to make Edge_iterator obsolete.
         return Edge_iterator(border_halfedges_begin());
     }
Edge_const_iterator border_edges_begin () const inline
Definition at line 548 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges_begin().
{
         return Edge_const_iterator(border_halfedges_begin());
     }
Halfedge_iterator border_halfedges_begin () inline
Definition at line 502 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::border_edges_begin().
{
         // halfedge iterator starting with the border edges. The range [
         // `halfedges_begin(), border_halfedges_begin()') denotes all
         // non-border edges. The range [`border_halfedges_begin(),
         // halfedges_end()') denotes all border edges. Precondition:
         // `normalize_border()' has been called and no halfedge insertion
         // or removal and no change in border status of the halfedges have
         // occured since then.
         return Halfedge_iterator( border_halfedges);
     }
Halfedge_const_iterator border_halfedges_begin () const inline
Definition at line 518 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges.
{
         // CGAL_assertion( border_halfedges);
         // return Halfedge_const_iterator( border_halfedges);
         return // static_cast -- MSVC identity loss... DVP
         Halfedge_const_iterator(static_cast<Halfedge_iterator>
                     (border_halfedges));
     }
Halfedge_iterator border_halfedges_begin () inline
Definition at line 524 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges.
{
         // halfedge iterator starting with the border edges. The range [
         // `halfedges_begin(), border_halfedges_begin()') denotes all
         // non-border edges. The range [`border_halfedges_begin(),
         // halfedges_end()') denotes all border edges. Precondition:
         // `normalize_border()' has been called and no halfedge insertion
         // or removal and no change in border status of the halfedges have
         // occured since then.
         return Halfedge_iterator( border_halfedges);
     }
Halfedge_const_iterator border_halfedges_begin () const inline
Definition at line 540 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges.
{
         // CGAL_assertion( border_halfedges);
         // return Halfedge_const_iterator( border_halfedges);
         return // static_cast -- MSVC identity loss... DVP
         Halfedge_const_iterator(static_cast<Halfedge_iterator>
                     (border_halfedges));
     }
std::size_t bytes () const inline
Definition at line 325 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
         return sizeof(Self)
                + vertices.size()  * sizeof( Vertex)
                + halfedges.size() * sizeof( Halfedge)
                + facets.size()    * sizeof( Facet);
     }
std::size_t bytes () const inline
Definition at line 347 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
         return sizeof(Self)
                + vertices.size()  * sizeof( Vertex)
                + halfedges.size() * sizeof( Halfedge)
                + facets.size()    * sizeof( Facet);
     }
std::size_t bytes_reserved () const inline
Definition at line 331 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
         return sizeof(Self)
                + vertices.capacity()  * sizeof( Vertex)
                + halfedges.capacity() * sizeof( Halfedge)
                + facets.capacity()    * sizeof( Facet);
     }
std::size_t bytes_reserved () const inline
Definition at line 353 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
         return sizeof(Self)
                + vertices.capacity()  * sizeof( Vertex)
                + halfedges.capacity() * sizeof( Halfedge)
                + facets.capacity()    * sizeof( Facet);
     }
Size capacity_of_facets () const inline
Definition at line 323 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.capacity();}
Size capacity_of_facets () const inline
Definition at line 345 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.capacity();}
Size capacity_of_halfedges () const inline
Definition at line 322 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.capacity();}
Size capacity_of_halfedges () const inline
Definition at line 344 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.capacity();}
Size capacity_of_vertices () const inline
Definition at line 321 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.capacity();}
Size capacity_of_vertices () const inline
Definition at line 343 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.capacity();}
void delete_all () inline
Definition at line 436 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges, Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, Halfedge_data_structure_using_vector< V, H, F >::nb_border_edges, Halfedge_data_structure_using_vector< V, H, F >::nb_border_halfedges, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::operator=().
                       {
                 vertices.erase(  vertices.begin(),  vertices.end());
                 halfedges.erase( halfedges.begin(), halfedges.end());
                 facets.erase(    facets.begin(),    facets.end());
                 nb_border_halfedges = 0;
                 nb_border_edges = 0;
                 border_halfedges = Halfedge_iterator(NULL);
     }
void delete_all () inline
Definition at line 458 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges, Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, Halfedge_data_structure_using_vector< V, H, F >::nb_border_edges, Halfedge_data_structure_using_vector< V, H, F >::nb_border_halfedges, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
                       {
                 vertices.erase(  vertices.begin(),  vertices.end());
                 halfedges.erase( halfedges.begin(), halfedges.end());
                 facets.erase(    facets.begin(),    facets.end());
                 nb_border_halfedges = 0;
                 nb_border_edges = 0;
                 border_halfedges = Halfedge_iterator(NULL);
     }
void edge_pop_back () inline
Definition at line 447 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
{
                 halfedges.pop_back();
                 halfedges.pop_back();
     }
void edge_pop_back () inline
Definition at line 469 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
{
                 halfedges.pop_back();
                 halfedges.pop_back();
     }
Edge_iterator edges_begin () inline
Definition at line 345 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges_begin().
 { return Edge_iterator(halfedges_begin());}
Edge_const_iterator edges_begin () const inline
Definition at line 362 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges_begin().
{
         return Edge_const_iterator(halfedges_begin());
     }
Edge_iterator edges_begin () inline
Definition at line 367 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges_begin().
 { return Edge_iterator(halfedges_begin());}
Edge_const_iterator edges_begin () const inline
Definition at line 384 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges_begin().
{
         return Edge_const_iterator(halfedges_begin());
     }
Edge_iterator edges_end () inline
Definition at line 350 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges_end().
 { return Edge_iterator(halfedges_end());}
Edge_const_iterator edges_end () const inline
Definition at line 365 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges_end().
{
         return Edge_const_iterator(halfedges_end());
     }
Edge_iterator edges_end () inline
Definition at line 372 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges_end().
 { return Edge_iterator(halfedges_end());}
Edge_const_iterator edges_end () const inline
Definition at line 387 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges_end().
{
         return Edge_const_iterator(halfedges_end());
     }
void facet_pop_back () inline
Definition at line 452 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { facets.pop_back(); }
void facet_pop_back () inline
Definition at line 474 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { facets.pop_back(); }
Facet_iterator facets_begin () inline
Definition at line 342 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.begin();}
Facet_const_iterator facets_begin () const inline
Definition at line 359 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.begin();}
Facet_iterator facets_begin () inline
Definition at line 364 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.begin();}
Facet_const_iterator facets_begin () const inline
Definition at line 381 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.begin();}
Facet_iterator facets_end () inline
Definition at line 343 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.end();}
Facet_const_iterator facets_end () const inline
Definition at line 360 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.end();}
Facet_iterator facets_end () inline
Definition at line 365 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.end();}
Facet_const_iterator facets_end () const inline
Definition at line 382 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.end();}
Halfedge_iterator halfedges_begin () inline
Definition at line 340 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::edges_begin().
 { return halfedges.begin();}
Halfedge_const_iterator halfedges_begin () const inline
Definition at line 357 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.begin();}
Halfedge_iterator halfedges_begin () inline
Definition at line 362 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.begin();}
Halfedge_const_iterator halfedges_begin () const inline
Definition at line 379 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.begin();}
Halfedge_iterator halfedges_end () inline
Definition at line 341 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::edges_end().
 { return halfedges.end();}
Halfedge_const_iterator halfedges_end () const inline
Definition at line 358 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.end();}
Halfedge_iterator halfedges_end () inline
Definition at line 363 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.end();}
Halfedge_const_iterator halfedges_end () const inline
Definition at line 380 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.end();}
Halfedge* new_edge () inline
Definition at line 393 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::halfedges.
{
                 CGAL_assertion( halfedges.size() + 1 < halfedges.capacity());
                 // creates a new pair of opposite border halfedges.
                 halfedges.push_back( Halfedge());
                 Halfedge* h = & (halfedges.back());
                 halfedges.push_back( Halfedge());
                 Halfedge* g = & (halfedges.back());
                 CGAL_assertion( h + 1 == g);
                 CGAL_assertion( (char*)g - (char*)h == sizeof( Halfedge));
                 h->H::set_opposite(g);
                 g->H::set_opposite(h);
                 return h;
     }
Halfedge* new_edge (const Halfedge * he) inline
Definition at line 407 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, Halfedge_data_structure_using_vector< V, H, F >::halfedges, and _HDS_vector_halfedge< V, H, F >::opposite().
{
                 CGAL_assertion( halfedges.size() + 1 < halfedges.capacity());
                 // creates a new pair of opposite border halfedges.
                 halfedges.push_back( *he);
                 Halfedge* h = & (halfedges.back());
                 halfedges.push_back( *(he->opposite()));
                 Halfedge* g = & (halfedges.back());
                 h->H::set_opposite(g);
                 g->H::set_opposite(h);
                 return h;
     }
Halfedge* new_edge () inline
Definition at line 415 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::halfedges.
{
                 CGAL_assertion( halfedges.size() + 1 < halfedges.capacity());
                 // creates a new pair of opposite border halfedges.
                 halfedges.push_back( Halfedge());
                 Halfedge* h = & (halfedges.back());
                 halfedges.push_back( Halfedge());
                 Halfedge* g = & (halfedges.back());
                 CGAL_assertion( h + 1 == g);
                 CGAL_assertion( (char*)g - (char*)h == sizeof( Halfedge));
                 h->H::set_opposite(g);
                 g->H::set_opposite(h);
                 return h;
     }
Halfedge* new_edge (const Halfedge * he) inline
Definition at line 429 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, Halfedge_data_structure_using_vector< V, H, F >::halfedges, and _HDS_vector_halfedge< V, H, F >::opposite().
{
                 CGAL_assertion( halfedges.size() + 1 < halfedges.capacity());
                 // creates a new pair of opposite border halfedges.
                 halfedges.push_back( *he);
                 Halfedge* h = & (halfedges.back());
                 halfedges.push_back( *(he->opposite()));
                 Halfedge* g = & (halfedges.back());
                 h->H::set_opposite(g);
                 g->H::set_opposite(h);
                 return h;
     }
Facet* new_facet () inline
Definition at line 419 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::facets.
                       {
                 CGAL_assertion( facets.size() < facets.capacity());
                 facets.push_back( Facet());
                 return & (facets.back());
     }
Facet* new_facet (const Facet * f) inline
Definition at line 425 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
{
                 facets.push_back( *f);
                 return & (facets.back());
     }
Facet* new_facet () inline
Definition at line 441 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::facets.
                       {
                 CGAL_assertion( facets.size() < facets.capacity());
                 facets.push_back( Facet());
                 return & (facets.back());
     }
Facet* new_facet (const Facet * f) inline
Definition at line 447 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
{
                 facets.push_back( *f);
                 return & (facets.back());
     }
Vertex* new_vertex () inline
Definition at line 375 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
                 CGAL_assertion( vertices.size() < vertices.capacity());
                 vertices.push_back( Vertex());
                 return & (vertices.back());
     }
Vertex* new_vertex (const Vertex * v) inline
Definition at line 381 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
                 CGAL_assertion( vertices.size() < vertices.capacity());
                 vertices.push_back( *v);
                 return & (vertices.back());
     }
Vertex* new_vertex (const Point & p) inline
Definition at line 387 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
                 CGAL_assertion( vertices.size() < vertices.capacity());
                 vertices.push_back( Vertex(p));
                 return & (vertices.back());
     }
Vertex* new_vertex () inline
Definition at line 397 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
                 CGAL_assertion( vertices.size() < vertices.capacity());
                 vertices.push_back( Vertex());
                 return & (vertices.back());
     }
Vertex* new_vertex (const Vertex * v) inline
Definition at line 403 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
                 CGAL_assertion( vertices.size() < vertices.capacity());
                 vertices.push_back( *v);
                 return & (vertices.back());
     }
Vertex* new_vertex (const Point & p) inline
Definition at line 409 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
                 CGAL_assertion( vertices.size() < vertices.capacity());
                 vertices.push_back( Vertex(p));
                 return & (vertices.back());
     }
void normalize_border ()
Definition at line 574 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_assertion, i, k, opposite(), and swap().
{
     nb_border_halfedges = 0;
     nb_border_edges = 0;
     border_halfedges = halfedges_end();
     // Lets run one partition step over the array of halfedges.
     // First find a pivot -- that means a border edge.
     Edge_iterator ll = edges_begin();
     while ( ll != edges_end() && (! (*ll).is_border()) &&
             (!(*ll).opposite()->is_border() ))
         ++ll;
     if ( ll == edges_end())
         // Done. No border edges found.
         return;
     // An array of pointers to update the changed halfedge pointers.
     typedef std::vector<Halfedge_iterator> HVector;
     HVector hvector;
     hvector.reserve( halfedges.size());
     // Initialize it.
     for ( Halfedge_iterator i = halfedges_begin(); i!=halfedges_end();++i){
         hvector.push_back( i);
     }
     CGAL_assertion( hvector.size() == halfedges.size());
     typename HVector::iterator llhv = hvector.begin()+2*(ll-edges_begin());
     // Start with the partitioning.
     Edge_iterator rr = edges_end();
     --rr;
     typename HVector::iterator rrhv = hvector.end();
     --rrhv;
     --rrhv;
                           // Pivot is in *ll
                           // Elements in [rr+1..end) >= pivot (border)
                           // Elements in [begin..ll) <  pivot (non border)
     while (ll < rr) {
                           // Pivot is in *ll, ll <= rr.
         while ( rr > ll && ((*rr).is_border() ||
                             (*rr).opposite()->is_border())) {
             if ( ! (*rr).opposite()->is_border()) {
                 std::swap( *rr, *((*rr).opposite()));
                 update_opposite( rr);
                 std::swap( *rrhv, *(rrhv+1));
             }
             --rr;
             --rrhv;
             --rrhv;
         }
                           // Elements in [rr+1..end) >= pivot (border)
                           // *rr <= pivot, ll <= rr.
         std::swap( *((*ll).opposite()), *((*rr).opposite()));
         std::swap( *ll, *rr);
         update_opposite( ll);
         update_opposite( rr);
         std::swap( *(llhv+1), *(rrhv+1));
         std::swap( *llhv, *rrhv);
                           // Elements in [begin..ll) < pivot
                           // Pivot is in *rr, ll <= rr.
         while ( !(*ll).is_border() && !(*ll).opposite()->is_border()) {
             ++ll;
             ++llhv;
             ++llhv;
         }
                           // Elements in [begin..ll) < pivot
                           // *ll >= pivot
                           // ll <= rr (since *rr is pivot.)
         CGAL_assertion( ll <= rr);
         CGAL_assertion( llhv <= rrhv);
         std::swap( *((*ll).opposite()), *((*rr).opposite()));
         std::swap( *ll, *rr);
         update_opposite( ll);
         update_opposite( rr);
         std::swap( *(llhv+1), *(rrhv+1));
         std::swap( *llhv, *rrhv);
         if ( ! (*rr).opposite()->is_border()) {
             std::swap( *rr, *((*rr).opposite()));
             update_opposite( rr);
             std::swap( *rrhv, *(rrhv+1));
         }
         --rr;
         --rrhv;
         --rrhv;
                           // Elements in [rr+1..end) >= pivot
                           // Pivot is in *ll
     }
     CGAL_assertion( llhv >= rrhv);
                           // rr + 1 >= ll >= rr
                           // Elements in [rr+1..end) >= pivot
                           // Elemente in [begin..ll) <  pivot
                           // Pivot is in a[ll]
     if ( ll == rr) {
         // Check for the possibly missed swap.
         if ( (*rr).is_border() && ! ((*rr).opposite()->is_border())) {
             std::swap( *rr, *((*rr).opposite()));
             update_opposite( rr);
             std::swap( *rrhv, *(rrhv+1));
         }
     }
     CGAL_assertion( (*ll).opposite()->is_border());
     CGAL_assertion( ll == edges_begin() || ! (*(ll-1)).is_border());
     CGAL_assertion( ll == edges_begin() ||
                ! (*(ll-1)).opposite()->is_border());
     border_halfedges = Halfedge_iterator( &*ll);
     nb_border_edges = (edges_end() - ll);
     nb_border_halfedges = 0;
     HVector inv_vector( halfedges.size());
     // Initialize inverse index.
     for ( typename HVector::iterator k = hvector.begin();
           k != hvector.end(); ++k){
         inv_vector[*k - halfedges_begin()] =
             halfedges_begin() + (k - hvector.begin());
     }
     // Update halfedge pointers.
     for (Halfedge_iterator h =halfedges_begin(); h != halfedges_end();++h){
         (*h).set_next( &* (inv_vector[ (*h).next() - &(halfedges.front())]));
         update_prev(   h, halfedges.begin(), inv_vector,
                        Supports_halfedge_prev());
         update_vertex( h, Supports_halfedge_vertex(),
                           Supports_vertex_halfedge());
         if ( (*h).is_border())
             nb_border_halfedges++;
         else
             update_facet(  h, Supports_halfedge_facet(),
                               Supports_facet_halfedge());
     }
 }
void normalize_border ()
Self& operator= (const Self & hds) inline
Definition at line 297 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges, Halfedge_data_structure_using_vector< V, H, F >::delete_all(), Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, Halfedge_data_structure_using_vector< V, H, F >::nb_border_edges, Halfedge_data_structure_using_vector< V, H, F >::nb_border_halfedges, Halfedge_data_structure_using_vector< V, H, F >::pointer_update(), and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
         if ( this != &hds) {
             delete_all();
             vertices            = hds.vertices;
             halfedges           = hds.halfedges;
             facets              = hds.facets;
             nb_border_halfedges = hds.nb_border_halfedges;
             nb_border_edges     = hds.nb_border_edges;
             border_halfedges    = hds.border_halfedges;
             pointer_update( hds.vertices.begin(),
                             hds.halfedges.begin(),
                             hds.facets.begin());
         }
         return *this;
     }
Self& operator= (const Self & hds) inline
Definition at line 319 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::border_halfedges, Halfedge_data_structure_using_vector< V, H, F >::delete_all(), Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, Halfedge_data_structure_using_vector< V, H, F >::nb_border_edges, Halfedge_data_structure_using_vector< V, H, F >::nb_border_halfedges, Halfedge_data_structure_using_vector< V, H, F >::pointer_update(), and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
         if ( this != &hds) {
             delete_all();
             vertices            = hds.vertices;
             halfedges           = hds.halfedges;
             facets              = hds.facets;
             nb_border_halfedges = hds.nb_border_halfedges;
             nb_border_edges     = hds.nb_border_edges;
             border_halfedges    = hds.border_halfedges;
             pointer_update( hds.vertices.begin(),
                             hds.halfedges.begin(),
                             hds.facets.begin());
         }
         return *this;
     }
void pointer_update (Vertex_const_iterator v_old, Halfedge_const_iterator h_old, Facet_const_iterator f_old) private
Definition at line 545 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References CGAL_F_UPDATE, CGAL_H_UPDATE, CGAL_H_UPDATE_I, CGAL_V_UPDATE, Halfedge_data_structure_decorator< _HDS >::get_facet(), Halfedge_data_structure_decorator< _HDS >::get_prev(), Halfedge_data_structure_decorator< _HDS >::get_vertex(), Halfedge_data_structure_decorator< _HDS >::set_facet(), Halfedge_data_structure_decorator< _HDS >::set_facet_halfedge(), Halfedge_data_structure_decorator< _HDS >::set_prev(), Halfedge_data_structure_decorator< _HDS >::set_vertex(), and Halfedge_data_structure_decorator< _HDS >::set_vertex_halfedge().
Referenced by Halfedge_data_structure_using_vector< V, H, F >::Halfedge_data_structure_using_vector(), Halfedge_data_structure_using_vector< V, H, F >::operator=(), and Halfedge_data_structure_using_vector< V, H, F >::reserve().
{
     // Update own pointers assuming that they lived previously
     // in a halfedge data structure with vector starting addresses
     // as given as parameters v_old, h_old, f_old.
     Halfedge_data_structure_decorator<Self> D;
     Vertex_iterator   v_new = vertices.begin();
     Halfedge_iterator h_new = halfedges.begin();
     Facet_iterator    f_new = facets.begin();
     for ( Halfedge_iterator h = halfedges.begin(); h != halfedges.end(); ++h) {
         h->set_next( CGAL_H_UPDATE( h->next()));
         h->H::set_opposite( CGAL_H_UPDATE( h->opposite()));
         D.set_prev( &*h, CGAL_H_UPDATE( D.get_prev( &*h)));
         D.set_vertex( &*h, CGAL_V_UPDATE( D.get_vertex( &*h)));
         D.set_vertex_halfedge( &*h);
         D.set_facet( &*h, CGAL_F_UPDATE( D.get_facet( &*h)));
         if ( ! h->is_border())
             D.set_facet_halfedge( &*h);
     }
     border_halfedges = CGAL_H_UPDATE_I( border_halfedges);
 }
void pointer_update (Vertex_const_iterator v_old, Halfedge_const_iterator h_old, Facet_const_iterator f_old) private
void reserve (Size v, Size h, Size f) inline
Definition at line 267 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References check_tag(), Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, Halfedge_data_structure_using_vector< V, H, F >::pointer_update(), and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
         // reserve storage for v vertices, h halfedges, and f facets. The
         // reservation sizes are a hint for optimizing storage allocation.
         // If the `capacity' is already greater than the requested size
         // nothing happens. If the `capacity' changes all iterators and
         // circulators invalidates. Function is void here.
         Vertex_iterator   v_old = vertices.begin();
         Halfedge_iterator h_old = halfedges.begin();
         Facet_iterator    f_old = facets.begin();
         if ( check_tag( Supports_halfedge_vertex()))
             vertices.reserve(v);
         halfedges.reserve(h);
         if ( check_tag( Supports_halfedge_facet()))
             facets.reserve(f);
         pointer_update( v_old, h_old, f_old);
     }
void reserve (Size v, Size h, Size f) inline
Definition at line 289 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References check_tag(), Halfedge_data_structure_using_vector< V, H, F >::facets, Halfedge_data_structure_using_vector< V, H, F >::halfedges, Halfedge_data_structure_using_vector< V, H, F >::pointer_update(), and Halfedge_data_structure_using_vector< V, H, F >::vertices.
{
         // reserve storage for v vertices, h halfedges, and f facets. The
         // reservation sizes are a hint for optimizing storage allocation.
         // If the `capacity' is already greater than the requested size
         // nothing happens. If the `capacity' changes all iterators and
         // circulators invalidates. Function is void here.
         Vertex_iterator   v_old = vertices.begin();
         Halfedge_iterator h_old = halfedges.begin();
         Facet_iterator    f_old = facets.begin();
         if ( check_tag( Supports_halfedge_vertex()))
             vertices.reserve(v);
         halfedges.reserve(h);
         if ( check_tag( Supports_halfedge_facet()))
             facets.reserve(f);
         pointer_update( v_old, h_old, f_old);
     }
Size size_of_border_edges () const inline
Definition at line 494 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::nb_border_edges.
 { return nb_border_edges;}
Size size_of_border_edges () const inline
Definition at line 516 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::nb_border_edges.
 { return nb_border_edges;}
Size size_of_border_halfedges () const inline
Definition at line 487 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::nb_border_halfedges.
 { return nb_border_halfedges;}
Size size_of_border_halfedges () const inline
Definition at line 509 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::nb_border_halfedges.
 { return nb_border_halfedges;}
Size size_of_facets () const inline
Definition at line 319 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.size();}
Size size_of_facets () const inline
Definition at line 341 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::facets.
 { return facets.size();}
Size size_of_halfedges () const inline
Definition at line 317 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.size();}
Size size_of_halfedges () const inline
Definition at line 339 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::halfedges.
 { return halfedges.size();}
Size size_of_vertices () const inline
Definition at line 316 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.size();}
Size size_of_vertices () const inline
Definition at line 338 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.size();}
void update_facet (Halfedge_iterator , Tag_false , Tag_false) inline protected
Definition at line 477 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_facet (Halfedge_iterator , Tag_true , Tag_false) inline protected
Definition at line 478 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_facet (Halfedge_iterator , Tag_false , Tag_true) inline protected
Definition at line 479 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_facet (Halfedge_iterator h, Tag_true , Tag_true) inline protected
Definition at line 480 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
{
         h->facet()->set_halfedge(&*h);
     }
void update_facet (Halfedge_iterator , Tag_false , Tag_false) inline protected
Definition at line 499 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_facet (Halfedge_iterator , Tag_true , Tag_false) inline protected
Definition at line 500 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_facet (Halfedge_iterator , Tag_false , Tag_true) inline protected
Definition at line 501 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_facet (Halfedge_iterator h, Tag_true , Tag_true) inline protected
Definition at line 502 of file include/CGAL/Halfedge_data_structure_using_vector.h.
{
         h->facet()->set_halfedge(&*h);
     }
void update_opposite (Halfedge_iterator h) inline protected
Definition at line 456 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::update_opposite().
{
                 Halfedge_iterator g = h + 1;
                 h->H::set_opposite( &*g);
                 g->H::set_opposite( &*h);
     }
void update_opposite (Edge_iterator h) inline protected
Definition at line 461 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::update_opposite().
{
         update_opposite( Halfedge_iterator( &* h));
     }
void update_opposite (Halfedge_iterator h) inline protected
Definition at line 478 of file include/CGAL/Halfedge_data_structure_using_vector.h.
{
                 Halfedge_iterator g = h + 1;
                 h->H::set_opposite( &*g);
                 g->H::set_opposite( &*h);
     }
void update_opposite (Edge_iterator h) inline protected
Definition at line 483 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::update_opposite().
{
         update_opposite( Halfedge_iterator( &* h));
     }
void update_prev (Halfedge_iterator , Halfedge_iterator , std::vector< Halfedge_iterator > , Tag_false) inline protected
Definition at line 465 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
                                                              {}
void update_prev (Halfedge_iterator h, Halfedge_iterator base, std::vector< Halfedge_iterator > inv, Tag_true) inline protected
Definition at line 467 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
{
         h->set_prev( &*(inv[ Halfedge_iterator(h->prev()) - base]));
     }
void update_prev (Halfedge_iterator , Halfedge_iterator , const std::vector< Halfedge_iterator > & , Tag_false) inline protected
Definition at line 487 of file include/CGAL/Halfedge_data_structure_using_vector.h.
                                                                     {}
void update_prev (Halfedge_iterator h, Halfedge_iterator base, const std::vector< Halfedge_iterator > & inv, Tag_true) inline protected
Definition at line 489 of file include/CGAL/Halfedge_data_structure_using_vector.h.
{
         h->set_prev( &*(inv[ Halfedge_iterator(h->prev()) - base]));
     }
void update_vertex (Halfedge_iterator , Tag_false , Tag_false) inline protected
Definition at line 471 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_vertex (Halfedge_iterator , Tag_true , Tag_false) inline protected
Definition at line 472 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_vertex (Halfedge_iterator , Tag_false , Tag_true) inline protected
Definition at line 473 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_vertex (Halfedge_iterator h, Tag_true , Tag_true) inline protected
Definition at line 474 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
{
         h->vertex()->set_halfedge(&*h);
     }
void update_vertex (Halfedge_iterator , Tag_false , Tag_false) inline protected
Definition at line 493 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_vertex (Halfedge_iterator , Tag_true , Tag_false) inline protected
Definition at line 494 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_vertex (Halfedge_iterator , Tag_false , Tag_true) inline protected
Definition at line 495 of file include/CGAL/Halfedge_data_structure_using_vector.h.
 {}
void update_vertex (Halfedge_iterator h, Tag_true , Tag_true) inline protected
Definition at line 496 of file include/CGAL/Halfedge_data_structure_using_vector.h.
{
         h->vertex()->set_halfedge(&*h);
     }
void vertex_pop_back () inline
Definition at line 445 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { vertices.pop_back(); }
void vertex_pop_back () inline
Definition at line 467 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { vertices.pop_back(); }
Vertex_iterator vertices_begin () inline
Definition at line 338 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.begin();}
Vertex_const_iterator vertices_begin () const inline
Definition at line 355 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.begin();}
Vertex_iterator vertices_begin () inline
Definition at line 360 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.begin();}
Vertex_const_iterator vertices_begin () const inline
Definition at line 377 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.begin();}
Vertex_iterator vertices_end () inline
Definition at line 339 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.end();}
Vertex_const_iterator vertices_end () const inline
Definition at line 356 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.end();}
Vertex_iterator vertices_end () inline
Definition at line 361 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.end();}
Vertex_const_iterator vertices_end () const inline
Definition at line 378 of file include/CGAL/Halfedge_data_structure_using_vector.h.
References Halfedge_data_structure_using_vector< V, H, F >::vertices.
 { return vertices.end();}
Member Data Documentation
Halfedge_iterator border_halfedges protected
Definition at line 238 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::border_halfedges_begin(), Halfedge_data_structure_using_vector< V, H, F >::delete_all(), and Halfedge_data_structure_using_vector< V, H, F >::operator=().
Facet_vector facets protected
Definition at line 235 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::bytes(), Halfedge_data_structure_using_vector< V, H, F >::bytes_reserved(), Halfedge_data_structure_using_vector< V, H, F >::capacity_of_facets(), Halfedge_data_structure_using_vector< V, H, F >::delete_all(), Halfedge_data_structure_using_vector< V, H, F >::facet_pop_back(), Halfedge_data_structure_using_vector< V, H, F >::facets_begin(), Halfedge_data_structure_using_vector< V, H, F >::facets_end(), Halfedge_data_structure_using_vector< V, H, F >::Halfedge_data_structure_using_vector(), Halfedge_data_structure_using_vector< V, H, F >::new_facet(), Halfedge_data_structure_using_vector< V, H, F >::operator=(), Halfedge_data_structure_using_vector< V, H, F >::reserve(), and Halfedge_data_structure_using_vector< V, H, F >::size_of_facets().
Halfedge_vector halfedges protected
Definition at line 234 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::bytes(), Halfedge_data_structure_using_vector< V, H, F >::bytes_reserved(), Halfedge_data_structure_using_vector< V, H, F >::capacity_of_halfedges(), Halfedge_data_structure_using_vector< V, H, F >::delete_all(), Halfedge_data_structure_using_vector< V, H, F >::edge_pop_back(), Halfedge_data_structure_using_vector< V, H, F >::Halfedge_data_structure_using_vector(), Halfedge_data_structure_using_vector< V, H, F >::halfedges_begin(), Halfedge_data_structure_using_vector< V, H, F >::halfedges_end(), Halfedge_data_structure_using_vector< V, H, F >::new_edge(), Halfedge_data_structure_using_vector< V, H, F >::operator=(), Halfedge_data_structure_using_vector< V, H, F >::reserve(), and Halfedge_data_structure_using_vector< V, H, F >::size_of_halfedges().
Size nb_border_edges protected
Definition at line 237 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::delete_all(), Halfedge_data_structure_using_vector< V, H, F >::operator=(), and Halfedge_data_structure_using_vector< V, H, F >::size_of_border_edges().
Size nb_border_halfedges protected
Definition at line 236 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::delete_all(), Halfedge_data_structure_using_vector< V, H, F >::operator=(), and Halfedge_data_structure_using_vector< V, H, F >::size_of_border_halfedges().
Vertex_vector vertices protected
Definition at line 233 of file CGAL/include/CGAL/Halfedge_data_structure_using_vector.h.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::bytes(), Halfedge_data_structure_using_vector< V, H, F >::bytes_reserved(), Halfedge_data_structure_using_vector< V, H, F >::capacity_of_vertices(), Halfedge_data_structure_using_vector< V, H, F >::delete_all(), Halfedge_data_structure_using_vector< V, H, F >::Halfedge_data_structure_using_vector(), Halfedge_data_structure_using_vector< V, H, F >::new_vertex(), Halfedge_data_structure_using_vector< V, H, F >::operator=(), Halfedge_data_structure_using_vector< V, H, F >::reserve(), Halfedge_data_structure_using_vector< V, H, F >::size_of_vertices(), Halfedge_data_structure_using_vector< V, H, F >::vertex_pop_back(), Halfedge_data_structure_using_vector< V, H, F >::vertices_begin(), and Halfedge_data_structure_using_vector< V, H, F >::vertices_end().
The documentation for this class was generated from the following file:
CGAL/include/CGAL/Halfedge_data_structure_using_vector.h