Rocstar: WTargetCalculator Class Reference
WTargetCalculator Class Reference
This is a concrete class.
#include <WTargetCalculator.hpp>
Public Member Functions
virtual ~WTargetCalculator ()
virtual destructor ensures use of polymorphism during destruction
virtual void compute_target_matrices (PatchData &pd, MsqError &err)
virtual ~WTargetCalculator ()
virtual destructor ensures use of polymorphism during destruction
virtual void compute_target_matrices (PatchData &pd, MsqError &err)
This function provides the corner matrices for all elements on the Patch.
Public Member Functions inherited from TargetCalculator
TargetCalculator ()
virtual ~TargetCalculator ()
virtual destructor ensures use of polymorphism during destruction
void compute_guide_matrices (enum guide_type type, PatchData &ref_pd, size_t elem_ind, Matrix3D A[], int num, MsqError &err)
Computes the guide corner matrices A for a given element index in the reference patch.
Matrix3D compute_V_3D (const Matrix3D &A, MsqError &err)
Matrix3D compute_Q_3D (const Matrix3D &A, MsqError &err)
Matrix3D compute_Delta_3D (const Matrix3D &A, MsqError &err)
void compute_default_target_matrices (PatchData &pd, MsqError &err)
Compute the default "isotropic" target matrices that are often used in the computation of reference-based target matrices.
void compute_reference_corner_matrices (PatchData &pd, MsqError &err)
Compute the corner matrices for the reference mesh refMesh.
void compute_target_matrices_and_check_det (PatchData &pd, MsqError &err)
This function wraps compute_target_matrices and checks that the determinant of each target is positive.
void reset_reference_meshset (MsqError &err)
Reset the reference mesh so it starts from the first vertex again.
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
virtual msq_std::string get_name ()
Returns the algorithm name.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
TargetCalculator ()
virtual ~TargetCalculator ()
virtual destructor ensures use of polymorphism during destruction
void compute_guide_matrices (enum guide_type type, PatchData &ref_pd, size_t elem_ind, Matrix3D A[], int num, MsqError &err)
Computes the guide corner matrices A for a given element index in the reference patch.
Matrix3D compute_V_3D (const Matrix3D &A, MsqError &err)
Matrix3D compute_Q_3D (const Matrix3D &A, MsqError &err)
Matrix3D compute_Delta_3D (const Matrix3D &A, MsqError &err)
void compute_default_target_matrices (PatchData &pd, MsqError &err)
Compute the default "isotropic" target matrices that are often used in the computation of reference-based target matrices.
void compute_reference_corner_matrices (PatchData &pd, MsqError &err)
Compute the corner matrices for the reference mesh refMesh.
void compute_target_matrices_and_check_det (PatchData &pd, MsqError &err)
This function wraps compute_target_matrices and checks that the determinant of each target is positive.
void reset_reference_meshset (MsqError &err)
Reset the reference mesh so it starts from the first vertex again.
virtual double loop_over_mesh (MeshSet &ms, MsqError &err)
This is the "run" function of PatchDataUser. It can do anything really.
virtual msq_std::string get_name ()
Returns the algorithm name.
virtual AlgorithmType get_algorithm_type ()
Return the algorithm type (to avoid RTTI use).
Public Member Functions inherited from PatchDataUser
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
virtual ~PatchDataUser ()
virtual void set_patch_type (PatchData::PatchType patch_type, MsqError &err, int param1=0, int param2=0)
Sets the Patch Type.
PatchData::PatchType get_patch_type ()
Returns the Patch Type.
int get_nb_layers (MsqError &err)
Returns number of layers (if relevant for partition algorythm).
void add_culling_method (enum PatchData::culling_method cm)
Sets on the culling method passed as argument.
void no_culling_method ()
Sets off all culling methods.
void remove_culling_method (enum PatchData::culling_method cm)
Sets off the culling method passed as argument.
long unsigned int get_culling_method_bits ()
Returns the bitset containing culling methods flags.
void set_all_parameters (PatchDataParameters &params)
PatchDataParameters & get_all_parameters ()
Returns the PatchDataParameters object.
void set_global_patch (PatchData *pd, MsqError &err)
Sets the Global Patch, so that it can be use by contiguoug PatchDataUser.
PatchData * get_global_patch ()
Returns the Global Patch.
void no_global_patch ()
Sets the Global Patch pointer to NULL.
Protected Member Functions
WTargetCalculator ()
the constructor is protected since this is not intended to be a concrete class.
WTargetCalculator ()
the constructor is protected since this is not intended to be a concrete class.
Protected Member Functions inherited from PatchDataUser
PatchDataUser ()
PatchDataUser ()
Protected Attributes
enum guide_type guideMatrix
Protected Attributes inherited from TargetCalculator
MeshSet * refMesh
Additional Inherited Members
Public Types inherited from TargetCalculator
enum Lambda_type { REGULAR, AVERAGE, REGULAR, AVERAGE }
enum guide_type {
Ad, AK, A0, Ar,
As, Ab, Ac, Ap,
Ae, Af, Ax, Ad,
AK, A0, Ar, As,
Ab, Ac, Ap, Ae,
Af, Ax
}
enum Lambda_type { REGULAR, AVERAGE, REGULAR, AVERAGE }
enum guide_type {
Ad, AK, A0, Ar,
As, Ab, Ac, Ap,
Ae, Af, Ax, Ad,
AK, A0, Ar, As,
Ab, Ac, Ap, Ae,
Af, Ax
}
Public Types inherited from PatchDataUser
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
enum AlgorithmType {
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR,
QUALITY_IMPROVER, QUALITY_ASSESSOR, MESH_TRANSFORM, TARGET_CALCULATOR
}
Static Public Member Functions inherited from TargetCalculator
static void initialize_default_target_matrices (Matrix3D &tri_M3D, Matrix3D &quad_M3D, Matrix3D &tet_M3D, Matrix3D &hex_M3D)
static double compute_Lambda (const Matrix3D &A, MsqError &err)
Note that this function is static, i.e. it can be used independently of an object.
static void initialize_default_target_matrices (Matrix3D &tri_M3D, Matrix3D &quad_M3D, Matrix3D &tet_M3D, Matrix3D &hex_M3D)
static double compute_Lambda (const Matrix3D &A, MsqError &err)
Detailed Description
This is a concrete class.
Definition at line 49 of file includeLinks/WTargetCalculator.hpp.
Constructor & Destructor Documentation
WTargetCalculator () inline protected
the constructor is protected since this is not intended to be a concrete class.
Concrete classes will instantiate the various guide enums in their constructor.
Definition at line 54 of file includeLinks/WTargetCalculator.hpp.
 {};
virtual ~WTargetCalculator () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 58 of file includeLinks/WTargetCalculator.hpp.
       {};
WTargetCalculator () inline protected
the constructor is protected since this is not intended to be a concrete class.
Concrete classes will instantiate the various guide enums in their constructor.
Definition at line 54 of file src/TargetCalculator/WTargetCalculator.hpp.
 {};
virtual ~WTargetCalculator () inline virtual
virtual destructor ensures use of polymorphism during destruction
Definition at line 58 of file src/TargetCalculator/WTargetCalculator.hpp.
       {};
Member Function Documentation
void compute_target_matrices (PatchData & pd, MsqError & err) virtual
The type of targets computed by this function is selected by the constructor of the base classes.
Implements TargetCalculator.
Definition at line 48 of file TargetCalculator/WTargetCalculator.cpp.
References TargetCalculator::compute_guide_matrices(), PatchDataUser::get_all_parameters(), PatchData::get_element_array(), MeshSet::get_next_patch(), WTargetCalculator::guideMatrix, i, MSQ_ERRRTN, MSQ_FUNCTION_TIMER, Mesquite::MSQ_MAX_NUM_VERT_PER_ENT, PatchData::num_elements(), PatchData::num_vertices(), TargetCalculator::refMesh, PatchData::targetMatrices, and MsqMeshEntity::vertex_count().
 {
   MSQ_FUNCTION_TIMER( "WTargetCalculator::compute_target_matrice" );
   size_t num_elements=pd.num_elements();
   PatchData ref_pd, *ref_pd_ptr;
   if ( refMesh != 0 ) {
     // If there is a reference mesh, gets a patch ref_pd equivalent to the patch pd of the main mesh.
     PatchDataParameters ref_pd_params(this->get_all_parameters());
     refMesh->get_next_patch(ref_pd, ref_pd_params, err); MSQ_ERRRTN(err);
     // Make sure topology of ref_pd and pd are equal
     assert( num_elements == ref_pd.num_elements() );
     size_t num_vertices=pd.num_vertices();
     assert( num_vertices == ref_pd.num_vertices() );
     ref_pd_ptr = &ref_pd;
   }
   else {
     // the reference patch is the same as the working patch if there is no reference mesh.
     ref_pd_ptr = &pd;
   }
   MsqMeshEntity* elems = pd.get_element_array(err); MSQ_ERRRTN(err);
   MsqMeshEntity* elems_ref = ref_pd_ptr->get_element_array(err); MSQ_ERRRTN(err);
   Matrix3D W_guides[MSQ_MAX_NUM_VERT_PER_ENT];
   TargetMatrix matrices[MSQ_MAX_NUM_VERT_PER_ENT];
   for (size_t i=0; i<num_elements; ++i) {
     int nve = elems[i].vertex_count();
     assert( nve = elems_ref[i].vertex_count() );
     compute_guide_matrices(guideMatrix, *ref_pd_ptr, i, W_guides, nve, err); MSQ_ERRRTN(err);
     for (int c = 0; c < nve; ++c)
       matrices[c] = W_guides[c];
     pd.targetMatrices.set_element_corner_tags( &pd, i, matrices, err ); MSQ_ERRRTN(err);
   }
   //if ( refMesh != 0 ) delete ref_pd;
 }
virtual void compute_target_matrices (PatchData & pd, MsqError & err) virtual
This function provides the corner matrices for all elements on the Patch.
Useful functionality includes: MsqMeshEntity::set_tag, MsqTag::target_matrix, MsqTag::scalar .
Implements TargetCalculator.
Member Data Documentation
enum guide_type guideMatrix protected
Definition at line 64 of file includeLinks/WTargetCalculator.hpp.
Referenced by WTargetCalculator::compute_target_matrices(), DeformingDomainGuides841::DeformingDomainGuides841(), and ShapeGuides811::ShapeGuides811().
The documentation for this class was generated from the following files:
includeLinks/WTargetCalculator.hpp
TargetCalculator/WTargetCalculator.cpp