Rocstar: ObjectFactory< ObjectType > Class Template Reference
ObjectFactory< ObjectType > Class Template Reference
#include <DLTools.H>
Public Member Functions
ObjectFactory ()
virtual ObjectType * Create ()
virtual void Destroy (ObjectType *objptr)
virtual void SetCreate (ObjectType *(*increate)())
virtual void SetDestroy (void(*indestroy)(ObjectType *))
virtual ~ObjectFactory ()
Public Attributes
virtual ObjectType *(*)() CreatePtr ()
virtual void(*)(ObjectType *) DestroyPtr ()
Protected Attributes
ObjectType *(* _create)()
void(* _destroy)(ObjectType *)
Detailed Description
template<typename ObjectType>
class Sys::ObjectFactory< ObjectType >
Definition at line 17 of file DLTools.H.
Constructor & Destructor Documentation
ObjectFactory () inline
Definition at line 22 of file DLTools.H.
                     : _create(NULL), _destroy(NULL)
     {};
virtual ~ObjectFactory () inline virtual
Definition at line 30 of file DLTools.H.
 {};
Member Function Documentation
virtual ObjectType* Create () inline virtual
Definition at line 24 of file DLTools.H.
References ObjectFactory< ObjectType >::_create.
 {return((*_create)());                    };
virtual void Destroy (ObjectType * objptr) inline virtual
Definition at line 27 of file DLTools.H.
 {(*_destroy)(objptr);  };
virtual void SetCreate (ObjectType *(*)() increate) inline virtual
Definition at line 28 of file DLTools.H.
References ObjectFactory< ObjectType >::_create.
 {_create = increate;};
virtual void SetDestroy (void(*)(ObjectType *) indestroy) inline virtual
Definition at line 29 of file DLTools.H.
References ObjectFactory< ObjectType >::_destroy.
 {_destroy = indestroy; };
Member Data Documentation
ObjectType*(* _create)() protected
Definition at line 19 of file DLTools.H.
Referenced by ObjectFactory< ObjectType >::Create(), and ObjectFactory< ObjectType >::SetCreate().
void(* _destroy)(ObjectType *) protected
Definition at line 20 of file DLTools.H.
Referenced by ObjectFactory< ObjectType >::SetDestroy().
virtual ObjectType*(*)() CreatePtr() inline
Definition at line 25 of file DLTools.H.
 {return(_create);                   };
virtual void(*)(ObjectType*) DestroyPtr() inline
Definition at line 26 of file DLTools.H.
 {return(_destroy);      };
The documentation for this class was generated from the following file:
DLTools.H