Rocstar: plag_modrkinit Module Reference
plag_modrkinit Module Reference
Public Member Functions
subroutine, public plag_rkinitprimary (region, iStage)
subroutine, public plag_injctilerkinit (region, iStage)
Private Member Functions
subroutine plag_rkinitgenericint (region, iStage, icBeg, icEnd, ivBeg, ivEnd, aiv, aivOld)
subroutine plag_rkinitgenericreal (region, iStage, icBeg, icEnd, ivBeg, ivEnd, rv, rvOld)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModRkInit.F90,v $ $Revision: 1.8 $'
Detailed Description
Definition at line 39 of file PLAG_ModRkInit.F90.
Member Function/Subroutine Documentation
subroutine, public plag_injctilerkinit (type(t_region), intent(inout), target region, integer, intent(in) iStage)
Definition at line 390 of file PLAG_ModRkInit.F90.
References moderror::deregisterfunction(), plag_rkinitgenericreal(), and moderror::registerfunction().
Referenced by plag_rkinit().
subroutine plag_rkinitgenericint (type(t_region) region, integer, intent(in) iStage, integer, intent(in) icBeg, integer, intent(in) icEnd, integer, intent(in) ivBeg, integer, intent(in) ivEnd, integer, dimension(:,:), pointer aiv, integer, dimension(:,:), pointer aivOld) private
Definition at line 99 of file PLAG_ModRkInit.F90.
References moderror::deregisterfunction(), moderror::errorstop(), ic, icbeg, icend, and moderror::registerfunction().
Referenced by plag_rkinitprimary().
subroutine plag_rkinitgenericreal (type(t_region) region, integer, intent(in) iStage, integer, intent(in) icBeg, integer, intent(in) icEnd, integer, intent(in) ivBeg, integer, intent(in) ivEnd, real(rfreal), dimension(:,:), pointer rv, real(rfreal), dimension(:,:), pointer rvOld) private
Definition at line 191 of file PLAG_ModRkInit.F90.
References moderror::deregisterfunction(), moderror::errorstop(), ic, icbeg, icend, and moderror::registerfunction().
Referenced by plag_injctilerkinit(), and plag_rkinitprimary().
subroutine, public plag_rkinitprimary (type(t_region), intent(inout), target region, integer, intent(in) iStage)
Definition at line 277 of file PLAG_ModRkInit.F90.
References moderror::deregisterfunction(), plag_rkinitgenericint(), plag_rkinitgenericreal(), and moderror::registerfunction().
Referenced by plag_rkinit().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: PLAG_ModRkInit.F90,v $ $Revision: 1.8 $' private
Definition at line 64 of file PLAG_ModRkInit.F90.
The documentation for this module was generated from the following file:
PLAG_ModRkInit.F90