Rocstar: prep_modbcdistribution Module Reference
prep_modbcdistribution Module Reference
Public Member Functions
subroutine, public bcdistributionfiles (regions)
subroutine bcoutflowdistrib (regions, ithRead, bcTitle, distrib)
Private Member Functions
subroutine bcslipwalldistrib (regions, ithRead, bcTitle, distrib)
subroutine bcnoslipdistrib (regions, ithRead, bcTitle, distrib)
subroutine bcinflowtotangdistrib (regions, ithRead, bcTitle, distrib)
subroutine bcinflowveldistrib (regions, ithRead, bcTitle, distrib)
subroutine bcfarfdistrib (regions, ithRead, bcTitle, distrib)
subroutine bcinjectdistrib (regions, ithRead, bcTitle, distrib)
subroutine readpatchsection (global, fileID, nvals, keys, vals, brbeg, brend, prbeg, prend, distrib, profType, fname, defined)
subroutine writebctofile (global, fname, patch)
subroutine profinflowvttaylorcyl (global, patch, nvals, switch, keys, defined, vals)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: PREP_ModBcDistribution.F90,v $ $Revision: 1.9 $'
Detailed Description
Definition at line 39 of file PREP_ModBcDistribution.F90.
Member Function/Subroutine Documentation
subroutine, public bcdistributionfiles (type(t_region), dimension(:), pointer regions)
Definition at line 92 of file PREP_ModBcDistribution.F90.
References bccaseloop(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), Attribute::status(), and CImg< T >::sum().
Referenced by rocflo_init().
subroutine bcfarfdistrib (type(t_region), dimension(:), pointer regions, integer ithRead, integer bcTitle, integer distrib) private
Definition at line 1253 of file PREP_ModBcDistribution.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), min(), prbeg, prend, readpatchsection(), and moderror::registerfunction().
Referenced by bccaseloop().
subroutine bcinflowtotangdistrib (type(t_region), dimension(:), pointer regions, integer ithRead, integer bcTitle, integer distrib) private
Definition at line 530 of file PREP_ModBcDistribution.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), min(), prbeg, prend, readpatchsection(), and moderror::registerfunction().
Referenced by bccaseloop().
subroutine bcinflowveldistrib (type(t_region), dimension(:), pointer regions, integer ithRead, integer bcTitle, integer distrib) private
Definition at line 741 of file PREP_ModBcDistribution.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, iend, j, jbeg, jend, k, kbeg, min(), nvals, prbeg, prend, profinflowvttaylorcyl(), readpatchsection(), moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and writebctofile().
Referenced by bccaseloop().
subroutine bcinjectdistrib (type(t_region), dimension(:), pointer regions, integer ithRead, integer bcTitle, integer distrib) private
Definition at line 1398 of file PREP_ModBcDistribution.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), min(), prbeg, prend, readpatchsection(), and moderror::registerfunction().
Referenced by bccaseloop().
subroutine bcnoslipdistrib (type(t_region), dimension(:), pointer regions, integer ithRead, integer bcTitle, integer distrib) private
Definition at line 355 of file PREP_ModBcDistribution.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), min(), prbeg, prend, readpatchsection(), and moderror::registerfunction().
Referenced by bccaseloop().
subroutine bcoutflowdistrib (type(t_region), dimension(:), pointer regions, integer ithRead, integer bcTitle, integer distrib)
Definition at line 1078 of file PREP_ModBcDistribution.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), min(), prbeg, prend, readpatchsection(), and moderror::registerfunction().
Referenced by bccaseloop().
subroutine bcslipwalldistrib (type(t_region), dimension(:), pointer regions, integer ithRead, integer bcTitle, integer distrib) private
Definition at line 250 of file PREP_ModBcDistribution.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), min(), prbeg, prend, readpatchsection(), and moderror::registerfunction().
Referenced by bccaseloop().
subroutine profinflowvttaylorcyl (type(t_global), pointer global, type(t_patch), pointer patch, integer nvals, integer switch, character(*), dimension(nvals) keys, logical, dimension(nvals) defined, real(rfreal), dimension(nvals) vals) private
Definition at line 1742 of file PREP_ModBcDistribution.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), i, j, nvals, moderror::registerfunction(), sign(), sqrt(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by bcinflowveldistrib().
subroutine readpatchsection (type(t_global), pointer global, integer fileID, integer nvals, character(*), dimension(nvals) keys, real(rfreal), dimension(nvals) vals, integer brbeg, integer brend, integer prbeg, integer prend, integer distrib, integer profType, character(*) fname, logical, dimension(nvals) defined) private
Definition at line 1559 of file PREP_ModBcDistribution.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), CImg< T >::line(), max(), min(), nvals, prbeg, prend, and moderror::registerfunction().
Referenced by bcfarfdistrib(), bcinflowtotangdistrib(), bcinflowveldistrib(), bcinjectdistrib(), bcnoslipdistrib(), bcoutflowdistrib(), bcslipwalldistrib(), peul_readbcfarfsection(), peul_readbcinflowsection(), peul_readbcinjectsection(), rflo_readbcfarfsection(), rflo_readbcinflowtotangsection(), rflo_readbcinflowvelsection(), rflo_readbcinjectapnsection(), rflo_readbcinjectmratesection(), rflo_readbcnoslipsection(), rflo_readbcoutflowsection(), rflo_readbcslipwallsection(), rflo_readtbcsection(), rflu_modreadbcinputfile::rflu_readbcfarfsection(), rflu_modreadbcinputfile::rflu_readbcinflowtotangsection(), rflu_modreadbcinputfile::rflu_readbcinflowveltempsection(), rflu_modreadbcinputfile::rflu_readbcinjectsection(), rflu_modreadbcinputfile::rflu_readbcnoslipwallheatsect(), rflu_modreadbcinputfile::rflu_readbcnoslipwalltempsect(), rflu_modreadbcinputfile::rflu_readbcoutflowsection(), rflu_modreadbcinputfile::rflu_readbcperiodicsection(), rflu_modreadbcinputfile::rflu_readbcslipwallsection(), rflu_modreadbcinputfile::rflu_readbcsymmetrysection(), rflu_modreadbcinputfile::rflu_readbcvirtualsection(), rflu_readtbcsection(), spec_rflu_readbcfarfsection(), spec_rflu_readbcinflowsection(), spec_rflu_readbcinjectsection(), spec_rflu_readbcsectiondummy(), and turb_cowlmreadbcsection().
subroutine writebctofile (type(t_global), pointer global, character(*) fname, type(t_patch), pointer patch) private
Definition at line 1659 of file PREP_ModBcDistribution.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, j, moderror::registerfunction(), and Attribute::status().
Referenced by bcinflowveldistrib().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: PREP_ModBcDistribution.F90,v $ $Revision: 1.9 $' private
Definition at line 69 of file PREP_ModBcDistribution.F90.
The documentation for this module was generated from the following file:
PREP_ModBcDistribution.F90