Rocstar: rflo_modlaplacesmoothing Module Reference
rflo_modlaplacesmoothing Module Reference
Public Member Functions
subroutine, public rflo_laplacegridsmoo (regions, resid)
subroutine, public rflo_laplacegridpatch (region, patch)
subroutine, public rflo_laplacegridjump (region, patch)
subroutine, public rflo_laplacegridsolve (region)
subroutine rflo_laplacegridortho (region)
Private Member Functions
subroutine rflo_laplacegridortho1 (region)
subroutine rflo_laplacegridortho2 (region)
subroutine rflo_projectquadcorner (ocell, eps, cofgp, cofgm, cfc, xyzc, xyzp)
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModLaplaceSmoothing.F90,v $ $Revision: 1.13 $'
Detailed Description
Definition at line 37 of file RFLO_ModLaplaceSmoothing.F90.
Member Function/Subroutine Documentation
subroutine, public rflo_laplacegridjump (type(t_region) region, type(t_patch) patch)
Definition at line 592 of file RFLO_ModLaplaceSmoothing.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine rflo_laplacegridortho (type(t_region) region)
Definition at line 1135 of file RFLO_ModLaplaceSmoothing.F90.
References accumulatexyzwork(), moderror::deregisterfunction(), moderror::errorstop(), i, idcbeg, idcend, idnbeg, idnend, ipnbeg, ipnend, j, jdcbeg, jdcend, jdnbeg, jdnend, jpnbeg, jpnend, k, kdcbeg, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_calcfacevectors(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_laplacegridsmoo().
subroutine rflo_laplacegridortho1 (type(t_region) region) private
Definition at line 1548 of file RFLO_ModLaplaceSmoothing.F90.
References accumulatexyzwork(), moderror::deregisterfunction(), moderror::errorstop(), i, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
subroutine rflo_laplacegridortho2 (type(t_region) region) private
Definition at line 1803 of file RFLO_ModLaplaceSmoothing.F90.
References accumulatexyzwork(), moderror::deregisterfunction(), moderror::errorstop(), i, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
subroutine, public rflo_laplacegridpatch (type(t_region) region, type(t_patch) patch)
Definition at line 520 of file RFLO_ModLaplaceSmoothing.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
subroutine, public rflo_laplacegridsmoo (type(t_region), dimension(:), pointer regions, real(rfreal) resid)
Definition at line 89 of file RFLO_ModLaplaceSmoothing.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), setup_py::grid(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_calccellcentroids(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_changeinteriorgrid(), rflo_clearsendrequests(), rflo_copygeometrydummy(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_laplacegridortho(), rflo_laplacegridpatch(), and rflo_laplacegridsolve().
subroutine, public rflo_laplacegridsolve (type(t_region) region)
Definition at line 666 of file RFLO_ModLaplaceSmoothing.F90.
References Plane_3< R, T >::d(), moderror::deregisterfunction(), dist(), i, ic, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and sqrt().
subroutine rflo_projectquadcorner (real(rfreal) ocell, real(rfreal) eps, real(rfreal), dimension(:) cofgp, real(rfreal), dimension(:) cofgm, real(rfreal), dimension(:) cfc, real(rfreal), dimension(:) xyzc, real(rfreal), dimension(:) xyzp) private
Definition at line 2048 of file RFLO_ModLaplaceSmoothing.F90.
References dot_product().
Referenced by accumulatexyzwork().
Member Data Documentation
character(chrlen) rcsidentstring = '$RCSfile: RFLO_ModLaplaceSmoothing.F90,v $ $Revision: 1.13 $' private
Definition at line 64 of file RFLO_ModLaplaceSmoothing.F90.
The documentation for this module was generated from the following file:
RFLO_ModLaplaceSmoothing.F90