Rocstar: plag_modsurfstats Module Reference
plag_modsurfstats Module Reference
Public Member Functions
subroutine, public plag_createsurfstats (pRegion)
subroutine, public plag_destroysurfstats (pRegion)
subroutine, public plag_gathersurfstats (pRegion, pPlag, pStatsPlag, ifl, iPcl, thetaAngle)
subroutine, public plag_readsurfstatswrapper (pRegion)
subroutine, public plag_writesurfstatswrapper (pRegion)
Private Member Functions
subroutine, private plag_closesurfstats (pRegion)
subroutine, private plag_createsurfstatskernel (pRegion, pStatsPlag)
subroutine, private plag_destroysurfstatskernel (global, pStatsPlag)
subroutine, private plag_initsurfstats (pRegion, pStatsPlag)
subroutine, private plag_nullifysurfstats (pRegion)
subroutine, private plag_opensurfstatsascii (pRegion, fileStatus, fileExists)
subroutine, private plag_opensurfstatsbinary (pRegion, fileStatus, fileExists)
subroutine, private plag_readsurfstatsascii (pRegion)
subroutine, private plag_readsurfstatsbinary (pRegion)
subroutine, private plag_readsurfstatskernelascii (pRegion, pStatsPlag)
subroutine, private plag_readsurfstatskernelbinary (pRegion, pStatsPlag)
integer function, private plag_setbinindex (global, binMethod, nBins, diamMicron, diamBin, diamMin, diamMax)
subroutine, private plag_writesurfstatsascii (pRegion)
subroutine, private plag_writesurfstatsbinary (pRegion)
subroutine, private plag_writesurfstatskernelascii (pRegion, pStatsPlag)
subroutine, private plag_writesurfstatskernelbinary (pRegion, pStatsPlag)
Private Attributes
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_ModSurfStats.F90,v $ $Revision: 1.13 $'
Detailed Description
Definition at line 39 of file PLAG_ModSurfStats.F90.
Member Function/Subroutine Documentation
subroutine, private plag_closesurfstats (type(t_region), pointer pRegion) private
Definition at line 124 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_readsurfstatswrapper(), and plag_writesurfstatswrapper().
subroutine, public plag_createsurfstats (type(t_region), pointer pRegion)
Definition at line 206 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_createsurfstatskernel(), plag_initsurfstats(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), and rflu_postprocessregionscommon1().
subroutine, private plag_createsurfstatskernel (type(t_region), pointer pRegion, type(t_surfstats_plag), dimension(:), pointer pStatsPlag) private
Definition at line 314 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_createsurfstats().
subroutine, public plag_destroysurfstats (type(t_region), pointer pRegion)
Definition at line 402 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_destroysurfstatskernel(), plag_nullifysurfstats(), and moderror::registerfunction().
Referenced by rflu_endflowsolver(), and rflu_postprocessregionscommon2().
subroutine, private plag_destroysurfstatskernel (type(t_global), pointer global, type(t_surfstats_plag), dimension(:), pointer pStatsPlag) private
Definition at line 489 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_destroysurfstats().
subroutine, public plag_gathersurfstats (type(t_region), pointer pRegion, type(t_plag), pointer pPlag, type(t_surfstats_plag), dimension(:), pointer pStatsPlag, integer, intent(in) ifl, integer, intent(in) iPcl, real(kind=rfreal), intent(in) thetaAngle)
Definition at line 569 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), plag_setbinindex(), moderror::registerfunction(), sqrt(), and CImg< T >::sum().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), and plag_rflu_modfindcells::plag_rflu_findcellstrajsafe().
subroutine, private plag_initsurfstats (type(t_region), pointer pRegion, type(t_surfstats_plag), dimension(:), pointer pStatsPlag) private
Definition at line 708 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_createsurfstats().
subroutine, private plag_nullifysurfstats (type(t_region), pointer pRegion) private
Definition at line 794 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_destroysurfstats().
subroutine, private plag_opensurfstatsascii (type(t_region), pointer pRegion, integer, intent(in) fileStatus, logical, intent(out), optional fileExists) private
Definition at line 880 of file PLAG_ModSurfStats.F90.
References buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by plag_readsurfstatswrapper(), and plag_writesurfstatswrapper().
subroutine, private plag_opensurfstatsbinary (type(t_region), pointer pRegion, integer, intent(in) fileStatus, logical, intent(out), optional fileExists) private
Definition at line 1001 of file PLAG_ModSurfStats.F90.
References buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by plag_readsurfstatswrapper(), and plag_writesurfstatswrapper().
subroutine, private plag_readsurfstatsascii (type(t_region), pointer pRegion) private
Definition at line 1118 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_readsurfstatskernelascii(), and moderror::registerfunction().
Referenced by plag_readsurfstatswrapper().
subroutine, private plag_readsurfstatsbinary (type(t_region), pointer pRegion) private
Definition at line 1276 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_readsurfstatskernelbinary(), and moderror::registerfunction().
Referenced by plag_readsurfstatswrapper().
subroutine, private plag_readsurfstatskernelascii (type(t_region), pointer pRegion, type(t_surfstats_plag), dimension(:), pointer pStatsPlag) private
Definition at line 1435 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_readsurfstatsascii().
subroutine, private plag_readsurfstatskernelbinary (type(t_region), pointer pRegion, type(t_surfstats_plag), dimension(:), pointer pStatsPlag) private
Definition at line 1527 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_readsurfstatsbinary().
subroutine, public plag_readsurfstatswrapper (type(t_region), pointer pRegion)
Definition at line 1623 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_closesurfstats(), plag_opensurfstatsascii(), plag_opensurfstatsbinary(), plag_readsurfstatsascii(), plag_readsurfstatsbinary(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), and rflu_postprocessregionscommon1().
integer function, private plag_setbinindex (type(t_global), pointer global, integer, intent(in) binMethod, integer, intent(in) nBins, real(kind=rfreal), intent(in) diamMicron, real(kind=rfreal), intent(in) diamBin, real(kind=rfreal), intent(in) diamMin, real(kind=rfreal), intent(in) diamMax) private
Definition at line 1719 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), min(), and moderror::registerfunction().
Referenced by plag_gathersurfstats().
subroutine, private plag_writesurfstatsascii (type(t_region), pointer pRegion) private
Definition at line 1790 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), plag_writesurfstatskernelascii(), and moderror::registerfunction().
Referenced by plag_writesurfstatswrapper().
subroutine, private plag_writesurfstatsbinary (type(t_region), pointer pRegion) private
Definition at line 1909 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), plag_writesurfstatskernelbinary(), and moderror::registerfunction().
Referenced by plag_writesurfstatswrapper().
subroutine, private plag_writesurfstatskernelascii (type(t_region), pointer pRegion, type(t_surfstats_plag), dimension(:), pointer pStatsPlag) private
Definition at line 2032 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_writesurfstatsascii().
subroutine, private plag_writesurfstatskernelbinary (type(t_region), pointer pRegion, type(t_surfstats_plag), dimension(:), pointer pStatsPlag) private
Definition at line 2124 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_writesurfstatsbinary().
subroutine, public plag_writesurfstatswrapper (type(t_region), pointer pRegion)
Definition at line 2214 of file PLAG_ModSurfStats.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_closesurfstats(), plag_opensurfstatsascii(), plag_opensurfstatsbinary(), plag_writesurfstatsascii(), plag_writesurfstatsbinary(), and moderror::registerfunction().
Referenced by rflu_endflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().
Member Data Documentation
character(chrlen), private rcsidentstring = '$RCSfile: PLAG_ModSurfStats.F90,v $ $Revision: 1.13 $' private
Definition at line 65 of file PLAG_ModSurfStats.F90.
The documentation for this module was generated from the following file:
PLAG_ModSurfStats.F90