Rocstar: rflu_modcommlists Module Reference
rflu_modcommlists Module Reference
Public Member Functions
subroutine, public rflu_comm_buildcommlists (regions)
subroutine rflu_comm_buildcommlistscells (regions)
subroutine rflu_comm_buildcommlistsvert (regions)
subroutine, public rflu_comm_checkcountborders (regions)
subroutine, public rflu_comm_countborders (pRegion, pRegionSerial)
subroutine, public rflu_comm_countbordersserial (pRegion)
subroutine, public rflu_comm_createbordercntr (pRegion, nBordersMaxOpt)
subroutine, public rflu_comm_createborders (pRegion, createMode)
subroutine, public rflu_comm_createcommlists (pRegion)
subroutine, public rflu_comm_destroybordercntr (pRegion)
subroutine, public rflu_comm_destroyborders (pRegion)
subroutine, public rflu_comm_destroycommlists (pRegion)
subroutine, public rflu_comm_getproclocregids (pRegion)
subroutine, public rflu_comm_readcommlists (pRegion)
subroutine, public rflu_comm_writecommlists (pRegion)
Public Attributes
integer, parameter, public create_borders_mode_dim_known = 1
integer, parameter, public create_borders_mode_dim_unknown = 2
Private Attributes
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCommLists.F90,v $ $Revision: 1.14 $'
Detailed Description
Definition at line 39 of file RFLU_ModCommLists.F90.
Member Function/Subroutine Documentation
subroutine, public rflu_comm_buildcommlists (type(t_region), dimension(:), pointer regions)
Definition at line 106 of file RFLU_ModCommLists.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_comm_buildcommlistscells(), rflu_comm_buildcommlistsvert(), and rflu_modsymmetryperiodic::rflu_sype_havesypepatches().
Referenced by rflupart().
subroutine rflu_comm_buildcommlistscells (type(t_region), dimension(:), pointer regions)
Definition at line 192 of file RFLU_ModCommLists.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and rflu_modsymmetryperiodic::rflu_sype_getactualserialcell().
Referenced by rflu_comm_buildcommlists().
subroutine rflu_comm_buildcommlistsvert (type(t_region), dimension(:), pointer regions)
Definition at line 540 of file RFLU_ModCommLists.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), max(), modsortsearch::quicksortinteger(), moderror::registerfunction(), modsortsearch::removecommonsortedintegersfancy(), rflu_modtopologyutils::rflu_buildcellvertlist(), rflu_modsymmetryperiodic::rflu_sype_getrelatedvertex(), rflu_modsymmetryperiodic::rflu_sype_havesypepatches(), and StopWatch::stop().
Referenced by rflu_comm_buildcommlists().
subroutine, public rflu_comm_checkcountborders (type(t_region), dimension(:), pointer regions)
Definition at line 994 of file RFLU_ModCommLists.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_comm_createbordercntr(), and rflu_comm_destroybordercntr().
Referenced by rflupart().
subroutine, public rflu_comm_countborders (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 1142 of file RFLU_ModCommLists.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), modsortsearch::quicksortinteger(), moderror::registerfunction(), rflu_comm_createbordercntr(), rflu_comm_destroybordercntr(), rflu_modsymmetryperiodic::rflu_sype_getactualserialcell(), rflu_modsymmetryperiodic::rflu_sype_havesypepatches(), and StopWatch::stop().
Referenced by rflupart().
subroutine, public rflu_comm_countbordersserial (type(t_region), pointer pRegion)
Definition at line 1341 of file RFLU_ModCommLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflupart().
subroutine, public rflu_comm_createbordercntr (type(t_region), pointer pRegion, integer, intent(in), optional nBordersMaxOpt)
Definition at line 1446 of file RFLU_ModCommLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_comm_checkcountborders(), rflu_comm_countborders(), and rflupart().
subroutine, public rflu_comm_createborders (type(t_region), pointer pRegion, integer, intent(in), optional createMode)
Definition at line 1537 of file RFLU_ModCommLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver(), and rflupart().
subroutine, public rflu_comm_createcommlists (type(t_region), pointer pRegion)
Definition at line 1677 of file RFLU_ModCommLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowsolver().
subroutine, public rflu_comm_destroybordercntr (type(t_region), pointer pRegion)
Definition at line 1799 of file RFLU_ModCommLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_comm_checkcountborders(), rflu_comm_countborders(), and rflupart().
subroutine, public rflu_comm_destroyborders (type(t_region), pointer pRegion)
Definition at line 1877 of file RFLU_ModCommLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_endflowsolver().
subroutine, public rflu_comm_destroycommlists (type(t_region), pointer pRegion)
Definition at line 1969 of file RFLU_ModCommLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_endflowsolver().
subroutine, public rflu_comm_getproclocregids (type(t_region), pointer pRegion)
Definition at line 2093 of file RFLU_ModCommLists.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modregionmapping::rflu_closeregionmappingfile(), rflu_modregionmapping::rflu_getproclocregids(), and rflu_modregionmapping::rflu_openregionmappingfile().
Referenced by rflu_initflowsolver().
subroutine, public rflu_comm_readcommlists (type(t_region), pointer pRegion)
Definition at line 2245 of file RFLU_ModCommLists.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_initflowsolver().
subroutine, public rflu_comm_writecommlists (type(t_region), pointer pRegion)
Definition at line 2509 of file RFLU_ModCommLists.F90.
References buildfilenamebasic(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflupart().
Member Data Documentation
integer, parameter, public create_borders_mode_dim_known = 1
Definition at line 75 of file RFLU_ModCommLists.F90.
integer, parameter, public create_borders_mode_dim_unknown = 2
Definition at line 75 of file RFLU_ModCommLists.F90.
character(chrlen) rcsidentstring = '$RCSfile: RFLU_ModCommLists.F90,v $ $Revision: 1.14 $' private
Definition at line 72 of file RFLU_ModCommLists.F90.
The documentation for this module was generated from the following file:
RFLU_ModCommLists.F90