Rocstar: clop.H File Reference
clop.H File Reference
#include <cstdlib>
Classes
class clop
Macros
#define F_FUNC(x) x
#define RFLUCONV F_FUNC(RFLUCONV)
#define RFLUINIT F_FUNC(RFLUINIT)
#define RFLUMAP F_FUNC(RFLUMAP)
#define RFLUMP F_FUNC(RFLUMP)
#define RFLUPART F_FUNC(RFLUPART)
#define RFLUPICK F_FUNC(RFLUPICK)
#define RFLUPOST F_FUNC(RFLUPOST)
Functions
vector< string > Vectize (const char **)
vector< string > Vectize (const char **, int)
const string stripdir (const string &)
bool GetOp (const string &ops, const vector< string > &args)
bool GetOp (const string &ops, string &rv, const vector< string > &args)
bool CheckOps (const vector< string > &args, string &badop)
void AddOp (const string &lo, const char &so)
Macro Definition Documentation
#define F_FUNC (x) x
Definition at line 96 of file clop.H.
#define RFLUCONV F_FUNC(RFLUCONV)
Definition at line 113 of file clop.H.
#define RFLUINIT F_FUNC(RFLUINIT)
Definition at line 114 of file clop.H.
Referenced by main().
#define RFLUMAP F_FUNC(RFLUMAP)
Definition at line 115 of file clop.H.
Referenced by main().
#define RFLUMP F_FUNC(RFLUMP)
Definition at line 116 of file clop.H.
#define RFLUPART F_FUNC(RFLUPART)
Definition at line 117 of file clop.H.
Referenced by main().
#define RFLUPICK F_FUNC(RFLUPICK)
Definition at line 118 of file clop.H.
#define RFLUPOST F_FUNC(RFLUPOST)
Definition at line 119 of file clop.H.
Function Documentation
void AddOp (const string & lo, const char & so)
Referenced by main().
bool CheckOps (const vector< string > & args, string & badop)
bool GetOp (const string & ops, const vector< string > & args)
Referenced by main().
bool GetOp (const string & ops, string & rv, const vector< string > & args)
const string stripdir (const string &)
Referenced by main().
vector<string> Vectize (const char **)
Definition at line 182 of file clop.C.
References i.
Referenced by main().
 {
   vector<string> retVal;
   int i = 0;
   while(in[i] != NULL)
     retVal.push_back(in[i++]);
   return retVal;
 }
vector<string> Vectize (const char ** , int)
Definition at line 192 of file clop.C.
References i.
 {
   vector<string> retVal;
   if(n <= 0) return retVal;
   int i = 0;
   while((in[i] != NULL) && i < n)
     retVal.push_back(in[i++]);
   return retVal;
 }