Rocstar: Color.C File Reference
Color.C File Reference
#include <CGAL/IO/Color.h>
Variables
CGAL_BEGIN_NAMESPACE const Color BLACK = Color(0, 0, 0)
const Color WHITE = Color(255, 255, 255)
const Color GRAY = Color(100,100,100)
const Color GREEN = Color(0, 255, 0)
const Color DEEPBLUE = Color(10, 0, 100)
const Color BLUE = Color(0, 0, 255)
const Color VIOLET = Color(255, 0, 255)
const Color PURPLE = Color(100, 0, 70)
const Color RED = Color(255, 0, 0)
const Color ORANGE = Color(235, 150, 0)
const Color YELLOW = Color(255, 255, 0)
Variable Documentation
CGAL_BEGIN_NAMESPACE const Color BLACK = Color(0, 0, 0)
Definition at line 55 of file Color.C.
const Color BLUE = Color(0, 0, 255)
Definition at line 62 of file Color.C.
Referenced by Overlay::convert_nat_coordinates(), Overlay::get_subnode_copies(), Overlay::get_subnode_id(), INode::halfedge(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_blue_with_green(), Overlay::match_features_0(), INode::nat_coor(), Overlay::number_subfaces(), Overlay::number_subnodes(), Overlay::Overlay(), Overlay::overlay_init(), INode::parent_type(), Overlay::project_adjacent_green_vertices(), Overlay::project_next_vertex(), INode::set_parent(), Overlay::set_subnode_id(), Overlay::verify_inode(), Overlay::write_inodes_tec(), Overlay::write_inodes_vec(), Overlay::write_overlay_off(), and Overlay::write_overlay_tec().
const Color DEEPBLUE = Color(10, 0, 100)
Definition at line 61 of file Color.C.
const Color GRAY = Color(100,100,100)
Definition at line 57 of file Color.C.
const Color GREEN = Color(0, 255, 0)
Definition at line 59 of file Color.C.
Referenced by Overlay::associate_green_vertices(), Overlay::get_subnode_copies(), Overlay::get_subnode_id(), INode::halfedge(), Overlay::insert_edge_into_queue(), Overlay::insert_node_in_blue_edge(), Overlay::insert_node_in_green_edge(), Overlay::intersect_blue_with_green(), Overlay::match_features_0(), INode::nat_coor(), Overlay::number_subfaces(), Overlay::number_subnodes(), Overlay::Overlay(), Overlay::overlay_init(), INode::parent_type(), Overlay::project_adjacent_green_vertices(), Overlay::project_next_vertex(), INode::set_parent(), Overlay::set_subnode_id(), Overlay::sort_on_green_edges(), Overlay::verify_inode(), Overlay::write_inodes_tec(), Overlay::write_inodes_vec(), Overlay::write_overlay_off(), and Overlay::write_overlay_tec().
const Color ORANGE = Color(235, 150, 0)
Definition at line 67 of file Color.C.
const Color PURPLE = Color(100, 0, 70)
Definition at line 64 of file Color.C.
const Color RED = Color(255, 0, 0)
Definition at line 66 of file Color.C.
const Color VIOLET = Color(255, 0, 255)
Definition at line 63 of file Color.C.
const Color WHITE = Color(255, 255, 255)
Definition at line 56 of file Color.C.
const Color YELLOW = Color(255, 255, 0)
Definition at line 68 of file Color.C.