Rocstar: commpi.h File Reference
commpi.h File Reference
Contains declarations of MPI subroutines used in Roccom.
#include <mpi.h>
Functions
int COMMPI_Comm_rank (MPI_Comm c)
int COMMPI_Comm_size (MPI_Comm c)
int COMMPI_Initialized ()
int COMMPI_Irecv (void *buf, int count, MPI_Datatype datatype, int src, int tag, MPI_Comm comm, MPI_Request *request)
Begins a nonblocking receive.
template<class T >
int COMMPI_Comm_c2f (T t)
template<>
int COMMPI_Comm_c2f (int t)
template<>
int COMMPI_Comm_c2f (unsigned int t)
template<class T >
T COMMPI_Comm_f2c (int c, T)
template<>
int COMMPI_Comm_f2c (int t, int)
template<>
unsigned int COMMPI_Comm_f2c (int t, unsigned int)
Nonblocking communicaiton
int COMMPI_Isend (void *buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm, MPI_Request *request)
Begins a nonblocking send.
Detailed Description
Contains declarations of MPI subroutines used in Roccom.
If DUMMY_MPI is not define, it includes the true mpi.h. Otherwise, it provides a dummy MPI interface for serial codes.
See also
commpi.C
Definition in file commpi.h.
Function Documentation
int COMMPI_Comm_c2f (T t) inline
Definition at line 190 of file commpi.h.
Referenced by Roccom_base::call_function(), and COM_F_FUNC2().
 { return MPI_Comm_c2f( t); }
int COMMPI_Comm_c2f (int t) inline
Definition at line 194 of file commpi.h.
 { return t; }
int COMMPI_Comm_c2f (unsigned int t) inline
Definition at line 198 of file commpi.h.
 { return t; }
T COMMPI_Comm_f2c (int c, T) inline
Definition at line 202 of file commpi.h.
Referenced by Roccom_base::call_function(), and COM_F_FUNC2().
 { return MPI_Comm_f2c( c); }
int COMMPI_Comm_f2c (int t, int) inline
Definition at line 206 of file commpi.h.
 { return t; }
unsigned int COMMPI_Comm_f2c (int t, unsigned int) inline
Definition at line 210 of file commpi.h.
 { return t; }
int COMMPI_Comm_rank (MPI_Comm c) inline
Definition at line 162 of file commpi.h.
References rank.
Referenced by Coupling::baseInit(), Pane_communicator::begin_update(), RFC_Window_transfer::comm_rank(), Rocon::constrain_displacements(), debug_int_print(), debug_print(), Rocon::find_intersections(), Rocprop::initialize(), Rocon::initialize(), main(), Propagation_3::Propagation_3(), Control_parameters::read(), Agent::read_by_control_file(), Rocprop::remesh_serial(), Roccom_base::Roccom_base(), Pane_ghost_connectivity::send_pane_info(), and Roccom_base::set_function().
 { int rank; MPI_Comm_rank( c, &rank); return rank; }
int COMMPI_Comm_size (MPI_Comm c) inline
Definition at line 165 of file commpi.h.
Referenced by RFC_Window_transfer::comm_size(), init_profiling(), and FaceOffset_3::rescale_displacements().
 { int size; MPI_Comm_size( c, &size); return size; }
int COMMPI_Initialized () inline
Definition at line 168 of file commpi.h.
Referenced by Roccom_base::abort(), Rocmop::agree_double(), Rocmop::agree_int(), assertion_fail(), Pane_communicator::begin_update(), Rocblas::calcDot(), Rocmop::check_input_pconn(), RFC_Window_transfer::comm_rank(), RFC_Window_transfer::comm_size(), COMMPI_Irecv(), COMMPI_Isend(), Rocsurf::compute_center(), Rocsurf::compute_edge_lengths(), Rocon::constrain_displacements(), FaceOffset_3::FaceOffset_3(), FaceOffset_3::filter_and_identify_ridge_edges(), Rocon::find_intersections(), Roccom_base::get_communicator(), glob_error(), Rocprop::initialize(), Rocon::initialize(), FaceOffset_3::insert_boundary_edges(), Rocsurf::integrate(), main(), Rocmop::obtain_extremal_dihedrals(), output_solution(), Pane_connectivity::pconn_nblocks(), Rocmop::perturb_stationary(), postcondition_fail(), precondition_fail(), Rocmop::print_extremal_dihedrals(), Rocmop::print_legible(), Rocmop::print_mquality(), Rocmop::print_quality(), Propagation_3::Propagation_3(), Rocin::read_by_control_file(), Rocmop::read_config_file(), Rocin::read_windows(), Rocblas::reduce_MPI(), Rocblas::reduce_scalar_MPI(), Rocprop::remesh_serial(), FaceOffset_3::rescale_displacements(), Roccom_base::Roccom_base(), Pane_ghost_connectivity::send_pane_info(), Roccom_base::set_profiling_barrier(), Rocmop::smooth_vol_mesq_ng(), Rocout::write_rocin_control_file(), Condition::~Condition(), and Mutex::~Mutex().
 { int flag; MPI_Initialized( &flag); return flag; }
int COMMPI_Irecv (void * buf, int count, MPI_Datatype datatype, int src, int tag, MPI_Comm comm, MPI_Request * request)
Begins a nonblocking receive.
Definition at line 131 of file commpi.C.
References COM_recv(), and COMMPI_Initialized().
Referenced by Pane_communicator::begin_update(), and Pane_ghost_connectivity::send_pane_info().
{
 #ifndef DUMMY_MPI
   if ( COMMPI_Initialized())
     return MPI_Irecv( buf, count, datatype, src, tag, comm, request);
 #endif
   try {
     if ( sendQ == NULL) sendQ = new Msg_Queue();
     if ( recvQ == NULL) recvQ = new Msg_Queue();
   }
   catch (...) {
     std::cerr << "Out of memory" << std::endl;
     std::abort();
   }
   return COM_recv( *sendQ, *recvQ, buf, count, datatype, tag);
 }
int COMMPI_Isend (void * buf, int count, MPI_Datatype datatype, int dest, int tag, MPI_Comm comm, MPI_Request * request)
Begins a nonblocking send.
Definition at line 112 of file commpi.C.
References COM_send(), and COMMPI_Initialized().
Referenced by Pane_communicator::begin_update(), and Pane_ghost_connectivity::send_pane_info().
{
 #ifndef DUMMY_MPI
   if ( COMMPI_Initialized())
     return MPI_Isend( buf, count, datatype, dest, tag, comm, request);
 #endif
   try {
     if ( sendQ == NULL) sendQ = new Msg_Queue();
     if ( recvQ == NULL) recvQ = new Msg_Queue();
   }
   catch (...) {
     std::cerr << "Out of memory" << std::endl;
     std::abort();
   }
   return COM_send( *sendQ, *recvQ, buf, count, datatype, tag);
 }