Rocstar: comp_row_support.f90 File Reference
comp_row_support.f90 File Reference
Functions/Subroutines
subroutine comp_row_add (ndim, gndim, nrows1, nrows2, nnz1, nnz2, nstart1, rp1, cval1, aval1, nstart2, rp2, cval2, aval2)
subroutine comp_row_vecmult (gndim, nrows1, nnz1, nstart1, rp1, cval1, aval1, vec, ans)
subroutine comp_row_mat (ndim, A, nstart, nrows)
subroutine comp_row_addval (ndim, nrows, nnz, nstart, rp, cval, aval, ipos, jpos, val)
subroutine comp_row_getval (ndim, nrows, nnz, nstart, rp, cval, aval, ipos, jpos, val)
subroutine comp_row_resize (ndim, nrows, nnz, nstart, rp, cval, aval, newnstart, newnrows)
Function/Subroutine Documentation
subroutine comp_row_add (integer ndim, integer gndim, integer nrows1, integer nrows2, integer nnz1, integer nnz2, integer nstart1, integer, dimension(nrows1+1) rp1, integer, dimension(nnz1) cval1, real(kind=wp), dimension(nnz1) aval1, integer nstart2, integer, dimension(nrows2+1) rp2, integer, dimension(nnz2) cval2, real(kind=wp), dimension(nnz2) aval2)
Definition at line 89 of file comp_row_support.f90.
References i, and j.
Referenced by createm(), implicit_soln(), and thermal_soln().
subroutine comp_row_addval (integer ndim, integer nrows, integer nnz, integer nstart, integer, dimension(nrows+1) rp, integer, dimension(nnz) cval, real(kind=wp), dimension(nnz) aval, integer ipos, integer jpos, real(kind=wp) val)
Definition at line 410 of file comp_row_support.f90.
References i.
Referenced by createk(), createm(), glbthermcap(), glbthermstiff(), and implicit_v3d8_mass_consistent().
subroutine comp_row_getval (integer ndim, integer nrows, integer nnz, integer nstart, integer, dimension(nrows+1) rp, integer, dimension(nnz) cval, real(kind=wp), dimension(nnz) aval, integer ipos, integer jpos, real(kind=wp) val)
Definition at line 511 of file comp_row_support.f90.
References i.
Referenced by createk(), createm(), glbthermcap(), and glbthermstiff().
subroutine comp_row_mat (integer ndim, real(kind=wp), dimension(1:ndim,1:ndim) A, integer nstart, integer nrows)
Definition at line 331 of file comp_row_support.f90.
References Line_2< R, T >::a(), i, and j.
subroutine comp_row_resize (integer ndim, integer nrows, integer nnz, integer nstart, integer, dimension(nrows+1) rp, integer, dimension(nnz) cval, real(kind=wp), dimension(nnz) aval, integer newnstart, integer newnrows)
Definition at line 592 of file comp_row_support.f90.
References i, and j.
Referenced by createk(), createm(), glbthermcap(), and glbthermstiff().
subroutine comp_row_vecmult (integer gndim, integer nrows1, integer nnz1, integer nstart1, integer, dimension(nrows1+1) rp1, integer, dimension(nnz1) cval1, real(kind=wp), dimension(nnz1) aval1, real(kind=wp), dimension(gndim) vec, real(kind=wp), dimension(nrows1) ans)
Definition at line 254 of file comp_row_support.f90.
References i, and j.
Referenced by get_fint(), and intload().