Rocstar: compute_curvature.C File Reference
compute_curvature.C File Reference
#include "Manifold_2.h"
#include "Generic_element_2.h"
#include "../Rocblas/include/Rocblas.h"
Functions
static SURF_BEGIN_NAMESPACE double sign (double x)
static double compute_lbop_weights (Point_3< Real > *ps, Real *ws)
Function Documentation
static double compute_lbop_weights (Point_3< Real > * ps, Real * ws) static
Definition at line 39 of file compute_curvature.C.
References Vector_3< Type >::cross_product(), Generic_element_2::get_gp_nat_coor(), Generic_element_2::get_gp_weight(), Generic_element_2::get_num_gp(), i, Vector_3< Type >::norm(), and v.
Referenced by Window_manifold_2::compute_mcn().
{
   ws[0] = ws[1] = ws[2] = 0.;
   Generic_element_2 e(4);
   int size = e.get_num_gp();
   double area = 0;
   for (int i=0; i<size; i++){
     // Compute tangents at quadrature points.
     Vector_2<Real> nc;
     e.get_gp_nat_coor(i, nc);
     const Real &xi=nc[0], &eta=nc[1];
     const Vector_3<Real> u = (1-eta)*(ps[1]-ps[0])+eta*(ps[2]-ps[3]);
     const Vector_3<Real> v = (1-xi)* (ps[3]-ps[0])+xi* (ps[2]-ps[1]);
     // Obtain the weights and local area of quadrature point
     const Real weight = e.get_gp_weight( i);
     // Evaluate the weights for Laplace-Beltrami operator
     const Real jacobi_det = u.cross_product(u,v).norm();
     const Real uv = u*v;
     const Real su = weight * ((1-eta)*uv-(1-xi)*(u*u))/jacobi_det;
     const Real sv = weight * ((1-xi)*uv-(1-eta)*(v*v))/jacobi_det;
     ws[0] += (1-eta)*sv -xi*su;
     ws[1] += xi*su + eta*sv;
     ws[2] += (1-xi)*su - eta*sv;;
     area  += weight * jacobi_det;
   }
   return area;
 }
static SURF_BEGIN_NAMESPACE double sign (double x) inline static
Definition at line 31 of file compute_curvature.C.
Referenced by bcondoutflowperf(), bcondoutflowperf_gl(), compare_xC2(), compare_y_at_xC2(), Window_manifold_2::compute_mcn(), equal_directionC2(), equal_directionC3(), equal_lineC2(), findpdf(), modtools::makenonzero(), Sgn< NT >::operator()(), DirectionS2< FT >::operator==(), DirectionS3< FT >::operator==(), LineS2< FT >::operator==(), LineS2< FT >::oriented_side(), PlaneS3< FT >::oriented_side(), prep_modbcdistribution::profinflowvttaylorcyl(), rflo_modboundaryconditions::rflo_bcondoutflowperf(), rflo_extrapintcellscal(), rflo_extrapintcellvec(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_convfluxoles(), rflu_modextractflowdatautils::rflu_extractshocklocation1d(), rflu_modrocstartools::rflu_genx_constraindisp(), rflu_modrocstartools::rflu_genx_initbflag(), rflu_setmovegridoptions(), rflu_modpatchutils::rflu_setpatchflatflags(), side_of_oriented_lineC2(), side_of_oriented_planeC3(), sign_of_determinant3x3(), sign_of_determinant4x4(), sign_of_determinant5x5(), sign_of_determinant6x6(), spec_rflu_sourceterms_gl(), tql1(), tql2(), tred1(), tred2(), turb_floextrapintcellscal(), turb_floextrapintcellvec(), turb_floextrapolcellvec(), turb_floextrapolfacevec(), and rflu_modrepair3d::volcom().
{
   return (x>=0) ? 1 : -1;
 }