Rocstar: kernel_ftC2.h File Reference
constructions/kernel_ftC2.h File Reference
#include <CGAL/determinant.h>
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE
CGAL_KERNEL_INLINE void midpointC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, FT &x, FT &y)
template<class FT >
CGAL_KERNEL_LARGE_INLINE void circumcenter_translateC2 (const FT &dqx, const FT &dqy, const FT &drx, const FT &dry, FT &dcx, FT &dcy)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE void circumcenterC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry, FT &x, FT &y)
template<class FT >
void line_from_pointsC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, FT &a, FT &b, FT &c)
template<class FT >
void line_from_point_directionC2 (const FT &px, const FT &py, const FT &dx, const FT &dy, FT &a, FT &b, FT &c)
template<class FT >
CGAL_KERNEL_INLINE void bisector_of_pointsC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, FT &a, FT &b, FT &c)
template<class FT >
FT line_y_at_xC2 (const FT &a, const FT &b, const FT &c, const FT &x)
template<class FT >
void line_get_pointC2 (const FT &a, const FT &b, const FT &c, int i, FT &x, FT &y)
template<class FT >
void perpendicular_through_pointC2 (const FT &la, const FT &lb, const FT &px, const FT &py, FT &a, FT &b, FT &c)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE void line_project_pointC2 (const FT &la, const FT &lb, const FT &lc, const FT &px, const FT &py, FT &x, FT &y)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE FT squared_circumradiusC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry, FT &x, FT &y)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE FT squared_circumradiusC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry)
template<class FT >
CGAL_KERNEL_INLINE FT squared_distanceC2 (const FT &px, const FT &py, const FT &qx, const FT &qy)
template<class FT >
CGAL_KERNEL_INLINE FT scaled_distance_to_lineC2 (const FT &la, const FT &lb, const FT &lc, const FT &px, const FT &py)
template<class FT >
CGAL_KERNEL_INLINE FT scaled_distance_to_directionC2 (const FT &la, const FT &lb, const FT &px, const FT &py)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE FT scaled_distance_to_lineC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry)
Function Documentation
CGAL_KERNEL_INLINE void bisector_of_pointsC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, FT & a, FT & b, FT & c)
Definition at line 134 of file constructions/kernel_ftC2.h.
References CGAL_NTS, and square().
 {
   a = FT(2)*(px - qx);
   b = FT(2)*(py - qy);
   c = CGAL_NTS square(qx) + CGAL_NTS square(qy) -
       CGAL_NTS square(px) - CGAL_NTS square(py);
 }
CGAL_KERNEL_LARGE_INLINE void circumcenter_translateC2 (const FT & dqx, const FT & dqy, const FT & drx, const FT & dry, FT & dcx, FT & dcy)
Definition at line 69 of file constructions/kernel_ftC2.h.
References CGAL_kernel_assertion, CGAL_NTS, det2x2_by_formula(), and square().
Referenced by circumcenterC2(), and squared_circumradiusC2().
 {
   // Given 3 points P, Q, R, this function takes as input:
   // qx-px, qy-py, rx-px, ry-py.  And returns cx-px, cy-py,
   // where (cx, cy) are the coordinates of the circumcenter C.
   // What we do is intersect the bisectors.
   FT r2 = CGAL_NTS square(drx) + CGAL_NTS square(dry);
   FT q2 = CGAL_NTS square(dqx) + CGAL_NTS square(dqy);
   FT den = FT(2) * det2x2_by_formula(dqx, dqy, drx, dry);
   // The 3 points aren't collinear.
   // Hopefully, this is already checked at the upper level.
   CGAL_kernel_assertion ( den != FT(0) );
   // One possible optimization here is to precompute 1/den, to avoid one
   // division.  However, we loose precision, and it's maybe not worth it (?).
   dcx =   det2x2_by_formula (dry, dqy, r2, q2) / den;
   dcy = - det2x2_by_formula (drx, dqx, r2, q2) / den;
 }
CGAL_KERNEL_MEDIUM_INLINE void circumcenterC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry, FT & x, FT & y)
Definition at line 95 of file constructions/kernel_ftC2.h.
References circumcenter_translateC2().
 {
   circumcenter_translateC2(qx-px, qy-py, rx-px, ry-py, x, y);
   x += px;
   y += py;
 }
void line_from_point_directionC2 (const FT & px, const FT & py, const FT & dx, const FT & dy, FT & a, FT & b, FT & c) inline
Definition at line 122 of file constructions/kernel_ftC2.h.
 {
   a = - dy;
   b = dx;
   c = px*dy - py*dx;
 }
void line_from_pointsC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, FT & a, FT & b, FT & c) inline
Definition at line 108 of file constructions/kernel_ftC2.h.
 {
   a = py - qy;
   b = qx - px;
   // Suggested by Serge Pashkov (psw@rt.kiam.ru) for better numeric stability.
   c = -px*a - py*b;
   // c = px*qy - py*qx;
 }
void line_get_pointC2 (const FT & a, const FT & b, const FT & c, int i, FT & x, FT & y) inline
Definition at line 155 of file constructions/kernel_ftC2.h.
 {
   if (b==FT(0))
     {
       x = (-b-c)/a + FT(i)*b;
       y = FT(1) - FT(i)*a;
     }
   else
     {
       x = FT(1) + FT(i)*b;
       y = -(a+c)/b - FT(i)*a;
     }
 }
CGAL_KERNEL_MEDIUM_INLINE void line_project_pointC2 (const FT & la, const FT & lb, const FT & lc, const FT & px, const FT & py, FT & x, FT & y)
Definition at line 185 of file constructions/kernel_ftC2.h.
References CGAL_NTS, and square().
 {
 #if 1
   // Original old version
   if (la==FT(0)) // horizontal line
   {
     x = px;
     y = -lc/lb;
   }
   else if (lb==FT(0)) // vertical line
   {
     x = -lc/la;
     y = py;
   }
   else
   {
     FT ab = la/lb, ba = lb/la, ca = lc/la;
     y = ( -px + ab*py - ca ) / ( ba + ab );
     x = -ba * y - ca;
   }
 #else
   // New version, with more multiplications, but less divisions and tests.
   // Let's compare the results of the 2, benchmark them, as well as check
   // the precision with the intervals.
   FT a2 = CGAL_NTS square(la);
   FT b2 = CGAL_NTS square(lb);
   FT d = a2 + b2;
   x = (la * (lb * py - lc) - px * b2) / d;
   y = (lb * (lc - la * px) + py * a2) / d;
 #endif
 }
FT line_y_at_xC2 (const FT & a, const FT & b, const FT & c, const FT & x) inline
Definition at line 147 of file constructions/kernel_ftC2.h.
 {
   return (-a*x-c) / b;
 }
CGAL_BEGIN_NAMESPACE CGAL_KERNEL_INLINE void midpointC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, FT & x, FT & y)
Definition at line 58 of file constructions/kernel_ftC2.h.
 {
   x = (px+qx) / FT(2);
   y = (py+qy) / FT(2);
 }
void perpendicular_through_pointC2 (const FT & la, const FT & lb, const FT & px, const FT & py, FT & a, FT & b, FT & c) inline
Definition at line 173 of file constructions/kernel_ftC2.h.
 {
   a = -lb;
   b = la;
   c = lb * px - la * py;
 }
CGAL_KERNEL_INLINE FT scaled_distance_to_directionC2 (const FT & la, const FT & lb, const FT & px, const FT & py)
Definition at line 269 of file constructions/kernel_ftC2.h.
Referenced by cmp_signed_dist_to_directionC2().
 {
   // scalar product with direction
   return la*px + lb*py;
 }
CGAL_KERNEL_INLINE FT scaled_distance_to_lineC2 (const FT & la, const FT & lb, const FT & lc, const FT & px, const FT & py)
Definition at line 258 of file constructions/kernel_ftC2.h.
Referenced by cmp_signed_dist_to_lineC2().
 {
   // for comparisons, use distance_to_directionsC2 instead
   // since lc is irrelevant
   return la*px + lb*py + lc;
 }
CGAL_KERNEL_MEDIUM_INLINE FT scaled_distance_to_lineC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry)
Definition at line 279 of file constructions/kernel_ftC2.h.
References det2x2_by_formula().
 {
   return det2x2_by_formula(px-rx,py-ry,qx-rx,qy-ry);
 }
CGAL_KERNEL_MEDIUM_INLINE FT squared_circumradiusC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry, FT & x, FT & y)
Definition at line 222 of file constructions/kernel_ftC2.h.
References CGAL_NTS, circumcenter_translateC2(), and square().
 {
   circumcenter_translateC2(qx-px, qy-py, rx-px, ry-py, x, y);
   FT r2 = CGAL_NTS square(x) + CGAL_NTS square(y);
   x += px;
   y += py;
   return r2;
 }
CGAL_KERNEL_MEDIUM_INLINE FT squared_circumradiusC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry)
Definition at line 237 of file constructions/kernel_ftC2.h.
References CGAL_NTS, circumcenter_translateC2(), square(), x, and y.
 {
   FT x, y;
   circumcenter_translateC2(qx-px, qy-py, rx-px, ry-py, x, y);
   return CGAL_NTS square(x) + CGAL_NTS square(y);
 }
CGAL_KERNEL_INLINE FT squared_distanceC2 (const FT & px, const FT & py, const FT & qx, const FT & qy)
Definition at line 249 of file constructions/kernel_ftC2.h.
References CGAL_NTS, and square().
Referenced by cmp_dist_to_pointC2().
 {
   return CGAL_NTS square(px-qx) + CGAL_NTS square(py-qy);
 }