Rocstar: Constants_A2_B2.f90 File Reference
Constants_A2_B2.f90 File Reference
Functions/Subroutines
subroutine constant_w (Gm, G2, K2, Km, a_eta, a_zeta, vm, v2, W)
subroutine constants_a2_b2 (e, f, h, vm, v2, A2, B2)
Function/Subroutine Documentation
subroutine constant_w (real*8 Gm, real*8 G2, real*8 K2, real*8 Km, real*8 a_eta, real*8 a_zeta, real*8 vm, real*8 v2, real*8, dimension(1:6,1:6) W)
Definition at line 53 of file Constants_A2_B2.f90.
References constants_a2_b2().
Referenced by operatorj().
subroutine constants_a2_b2 (real*8 e, real*8 f, real*8 h, real*8 vm, real*8 v2, real*8 A2, real*8 B2)
Definition at line 109 of file Constants_A2_B2.f90.
Referenced by constant_w().