Rocstar: kernel_ftC3.h File Reference
constructions/kernel_ftC3.h File Reference
#include <CGAL/determinant.h>
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE
CGAL_KERNEL_INLINE void midpointC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, FT &x, FT &y, FT &z)
template<class FT >
void circumcenterC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz, const FT &sx, const FT &sy, const FT &sz, FT &x, FT &y, FT &z)
template<class FT >
void circumcenterC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &sx, const FT &sy, const FT &sz, FT &x, FT &y, FT &z)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE void point_on_lineC3 (const FT &lpx, const FT &lpy, const FT &lpz, const FT &ldx, const FT &ldy, const FT &ldz, int i, FT &x, FT &y, FT &z)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE void projection_lineC3 (const FT &px, const FT &py, const FT &pz, const FT &lpx, const FT &lpy, const FT &lpz, const FT &ldx, const FT &ldy, const FT &ldz, FT &x, FT &y, FT &z)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE void plane_from_pointsC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz, FT &pa, FT &pb, FT &pc, FT &pd)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE void plane_from_point_directionC3 (const FT &px, const FT &py, const FT &pz, const FT &dx, const FT &dy, const FT &dz, FT &pa, FT &pb, FT &pc, FT &pd)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE void point_on_planeC3 (const FT &pa, const FT &pb, const FT &pc, const FT &pd, FT &x, FT &y, FT &z)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE void projection_planeC3 (const FT &pa, const FT &pb, const FT &pc, const FT &pd, const FT &px, const FT &py, const FT &pz, FT &x, FT &y, FT &z)
template<class FT >
CGAL_KERNEL_INLINE FT squared_distanceC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
template<class FT >
CGAL_KERNEL_INLINE FT scaled_distance_to_directionC3 (const FT &pa, const FT &pb, const FT &pc, const FT &px, const FT &py, const FT &pz)
template<class FT >
CGAL_KERNEL_INLINE FT scaled_distance_to_planeC3 (const FT &pa, const FT &pb, const FT &pc, const FT &pd, const FT &px, const FT &py, const FT &pz)
template<class FT >
CGAL_KERNEL_INLINE FT scaled_distance_to_planeC3 (const FT &ppx, const FT &ppy, const FT &ppz, const FT &pqx, const FT &pqy, const FT &pqz, const FT &prx, const FT &pry, const FT &prz, const FT &px, const FT &py, const FT &pz)
Function Documentation
void circumcenterC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz, const FT & sx, const FT & sy, const FT & sz, FT & x, FT & y, FT & z)
Definition at line 70 of file constructions/kernel_ftC3.h.
References CGAL_kernel_assertion, CGAL_NTS, det3x3_by_formula(), Mesquite::inv(), and square().
Referenced by circumcenter().
 {
   // Translate s to origin to simplify the expression.
   FT psx = px-sx;
   FT psy = py-sy;
   FT psz = pz-sz;
   FT ps2 = CGAL_NTS square(psx) + CGAL_NTS square(psy) + CGAL_NTS square(psz);
   FT qsx = qx-sx;
   FT qsy = qy-sy;
   FT qsz = qz-sz;
   FT qs2 = CGAL_NTS square(qsx) + CGAL_NTS square(qsy) + CGAL_NTS square(qsz);
   FT rsx = rx-sx;
   FT rsy = ry-sy;
   FT rsz = rz-sz;
   FT rs2 = CGAL_NTS square(rsx) + CGAL_NTS square(rsy) + CGAL_NTS square(rsz);
   FT num_x = det3x3_by_formula(psy,psz,ps2,
                                qsy,qsz,qs2,
                                rsy,rsz,rs2);
   FT num_y = det3x3_by_formula(psx,psz,ps2,
                                qsx,qsz,qs2,
                                rsx,rsz,rs2);
   FT num_z = det3x3_by_formula(psx,psy,ps2,
                                qsx,qsy,qs2,
                                rsx,rsy,rs2);
   FT den   = det3x3_by_formula(psx,psy,psz,
                                qsx,qsy,qsz,
                                rsx,rsy,rsz);
   CGAL_kernel_assertion( den != FT(0) );
   FT inv = FT(1)/(FT(2) * den);
   x = sx + num_x*inv;
   y = sy - num_y*inv;
   z = sz + num_z*inv;
 }
void circumcenterC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & sx, const FT & sy, const FT & sz, FT & x, FT & y, FT & z)
Definition at line 112 of file constructions/kernel_ftC3.h.
References CGAL_kernel_assertion, CGAL_NTS, det3x3_by_formula(), Mesquite::inv(), and square().
 {
   // Translate s to origin to simplify the expression.
   FT psx = px-sx;
   FT psy = py-sy;
   FT psz = pz-sz;
   FT ps2 = CGAL_NTS square(psx) + CGAL_NTS square(psy) + CGAL_NTS square(psz);
   FT qsx = qx-sx;
   FT qsy = qy-sy;
   FT qsz = qz-sz;
   FT qs2 = CGAL_NTS square(qsx) + CGAL_NTS square(qsy) + CGAL_NTS square(qsz);
   FT rsx = psy*qsz-psz*qsy;
   FT rsy = psz*qsx-psx*qsz;
   FT rsz = psx*qsy-psy*qsx;
   FT num_x = det3x3_by_formula(psy,psz,ps2,
                                qsy,qsz,qs2,
                                rsy,rsz,FT(0));
   FT num_y = det3x3_by_formula(psx,psz,ps2,
                                qsx,qsz,qs2,
                                rsx,rsz,FT(0));
   FT num_z = det3x3_by_formula(psx,psy,ps2,
                                qsx,qsy,qs2,
                                rsx,rsy,FT(0));
   FT den   = det3x3_by_formula(psx,psy,psz,
                                qsx,qsy,qsz,
                                rsx,rsy,rsz);
   CGAL_kernel_assertion( den != FT(0) );
   FT inv = FT(1)/(FT(2) * den);
   x = sx + num_x*inv;
   y = sy - num_y*inv;
   z = sz + num_z*inv;
 }
CGAL_BEGIN_NAMESPACE CGAL_KERNEL_INLINE void midpointC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, FT & x, FT & y, FT & z)
Definition at line 58 of file constructions/kernel_ftC3.h.
Referenced by midpoint().
 {
   FT half = FT(1) / FT(2);
   x = (px+qx) * half;
   y = (py+qy) * half;
   z = (pz+qz) * half;
 }
CGAL_KERNEL_MEDIUM_INLINE void plane_from_point_directionC3 (const FT & px, const FT & py, const FT & pz, const FT & dx, const FT & dy, const FT & dz, FT & pa, FT & pb, FT & pc, FT & pd)
Definition at line 205 of file constructions/kernel_ftC3.h.
 {
   // d is the normal direction
   pa = dx; pb = dy; pc = dz; pd = -dx*px - dy*py - dz*pz;
 }
CGAL_KERNEL_MEDIUM_INLINE void plane_from_pointsC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz, FT & pa, FT & pb, FT & pc, FT & pd)
Definition at line 184 of file constructions/kernel_ftC3.h.
 {
   FT rpx = px-rx;
   FT rpy = py-ry;
   FT rpz = pz-rz;
   FT rqx = qx-rx;
   FT rqy = qy-ry;
   FT rqz = qz-rz;
   // Cross product rp * rq
   pa = rpy*rqz - rqy*rpz;
   pb = rpz*rqx - rqz*rpx;
   pc = rpx*rqy - rqx*rpy;
   pd = - pa*rx - pb*ry - pc*rz;
 }
CGAL_KERNEL_MEDIUM_INLINE void point_on_lineC3 (const FT & lpx, const FT & lpy, const FT & lpz, const FT & ldx, const FT & ldy, const FT & ldz, int i, FT & x, FT & y, FT & z)
Definition at line 153 of file constructions/kernel_ftC3.h.
 {
   x = lpx + ldx*FT(i);
   y = lpy + ldy*FT(i);
   z = lpz + ldz*FT(i);
 }
CGAL_KERNEL_MEDIUM_INLINE void point_on_planeC3 (const FT & pa, const FT & pb, const FT & pc, const FT & pd, FT & x, FT & y, FT & z)
Definition at line 216 of file constructions/kernel_ftC3.h.
 {
   x = y = z = FT(0);
   if (pa != FT(0))      x = -pd/pa;
   else if (pb != FT(0)) y = -pd/pb;
   else                  z = -pd/pc;
 }
CGAL_KERNEL_MEDIUM_INLINE void projection_lineC3 (const FT & px, const FT & py, const FT & pz, const FT & lpx, const FT & lpy, const FT & lpz, const FT & ldx, const FT & ldy, const FT & ldz, FT & x, FT & y, FT & z)
Definition at line 166 of file constructions/kernel_ftC3.h.
 {
   // projects p on the line l
   FT dpx = px-lpx;
   FT dpy = py-lpy;
   FT dpz = pz-lpz;
   FT lambda = (ldx*dpx+ldy*dpy+ldz*dpz) / (ldx*ldx+ldy*ldy+ldz*ldz);
   x = lpx + lambda * ldx;
   y = lpy + lambda * ldy;
   z = lpz + lambda * ldz;
 }
CGAL_KERNEL_MEDIUM_INLINE void projection_planeC3 (const FT & pa, const FT & pb, const FT & pc, const FT & pd, const FT & px, const FT & py, const FT & pz, FT & x, FT & y, FT & z)
Definition at line 228 of file constructions/kernel_ftC3.h.
Referenced by projection().
 {
   // the equation of the plane is Ax+By+Cz+D=0
   // the normal direction is (A,B,C)
   // the projected point is p-lambda(A,B,C) where
   // A(x-lambda A) + B(y-lambda B) + C(z-lambda C) + D = 0
   FT num = pa*px + pb*py + pc*pz + pd;
   FT den = pa*pa + pb*pb + pc*pc;
   FT lambda = num / den;
   x = px - lambda * pa;
   y = py - lambda * pb;
   z = pz - lambda * pc;
 }
CGAL_KERNEL_INLINE FT scaled_distance_to_directionC3 (const FT & pa, const FT & pb, const FT & pc, const FT & px, const FT & py, const FT & pz)
Definition at line 259 of file constructions/kernel_ftC3.h.
Referenced by cmp_signed_dist_to_directionC3().
 {
   return pa*px + pb*py + pc*pz;
 }
CGAL_KERNEL_INLINE FT scaled_distance_to_planeC3 (const FT & pa, const FT & pb, const FT & pc, const FT & pd, const FT & px, const FT & py, const FT & pz)
Definition at line 268 of file constructions/kernel_ftC3.h.
Referenced by scaled_distance_to_plane().
 {
   return pa*px + pb*py + pc*pz + pd;
 }
CGAL_KERNEL_INLINE FT scaled_distance_to_planeC3 (const FT & ppx, const FT & ppy, const FT & ppz, const FT & pqx, const FT & pqy, const FT & pqz, const FT & prx, const FT & pry, const FT & prz, const FT & px, const FT & py, const FT & pz)
Definition at line 278 of file constructions/kernel_ftC3.h.
References det3x3_by_formula().
 {
   return det3x3_by_formula(ppx-px,ppy-py,ppz-pz,
                            pqx-px,pqy-py,pqz-pz,
                            prx-px,pry-py,prz-pz);
 }
CGAL_KERNEL_INLINE FT squared_distanceC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 249 of file constructions/kernel_ftC3.h.
References CGAL_NTS, and square().
Referenced by cmp_dist_to_pointC3(), and squared_distance().
 {
   return CGAL_NTS square(px-qx) + CGAL_NTS square(py-qy) +
          CGAL_NTS square(pz-qz);
 }