Rocstar: ControlVolume.F90 File Reference
ControlVolume.F90 File Reference
Functions/Subroutines
subroutine volumetetra (xyzNodes, faceVecs, volume)
subroutine volumepyramid (xyzNodes, faceVecs, volume)
subroutine volumeprism (xyzNodes, faceVecs, volume)
subroutine volumehexa (xyzNodes, faceVecs, volume)
Function/Subroutine Documentation
subroutine volumehexa (real(rfreal), dimension(3,8) xyzNodes, real(rfreal), dimension(3,6) faceVecs, real(rfreal) volume)
Definition at line 110 of file ControlVolume.F90.
References volume().
Referenced by rflo_calccontrolvolumes(), rflo_calcgridspeeds(), rflo_copymatrixcorners(), and rflo_copyvectorcorners().
subroutine volumeprism (real(rfreal), dimension(3,6) xyzNodes, real(rfreal), dimension(3,5) faceVecs, real(rfreal) volume)
Definition at line 91 of file ControlVolume.F90.
subroutine volumepyramid (real(rfreal), dimension(3,5) xyzNodes, real(rfreal), dimension(3,5) faceVecs, real(rfreal) volume)
Definition at line 72 of file ControlVolume.F90.
subroutine volumetetra (real(rfreal), dimension(3,4) xyzNodes, real(rfreal), dimension(3,4) faceVecs, real(rfreal) volume)
Definition at line 53 of file ControlVolume.F90.