Rocstar: RFLU_DeallocMemSolWrapper.F90 File Reference
conv/RFLU_DeallocMemSolWrapper.F90 File Reference
Functions/Subroutines
subroutine rflu_deallocmemsolwrapper (pRegion)
Function/Subroutine Documentation
subroutine rflu_deallocmemsolwrapper (type(t_region), pointer pRegion)
Definition at line 44 of file conv/RFLU_DeallocMemSolWrapper.F90.
References moderror::deregisterfunction(), plag_rflu_deallocmemsol(), plag_rflu_deallocmemsoltile(), moderror::registerfunction(), rflu_moddeallocatememory::rflu_deallocatememorysolcv(), and spec_rflu_deallocatememorysol().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflu_postprocessregionscommon2(), rfluconv(), and rfluinit().