Rocstar: Coupling.C File Reference
Coupling.C File Reference
#include "rocman.h"
Functions
COM_EXTERN_MODULE (Rocblas)
COM_EXTERN_MODULE (Rocface)
COM_EXTERN_MODULE (Rocsurf)
COM_EXTERN_MODULE (Rocprop)
void RocstarShutdown (int=0)
void _load_rocface (FluidAgent *fagent, SolidAgent *sagent, const RocmanControl_parameters *param)
Function Documentation
void _load_rocface (FluidAgent * fagent, SolidAgent * sagent, const RocmanControl_parameters * param)
Definition at line 43 of file transfer_actions.C.
Referenced by FullyCoupling::reload_rocface().
 {
   int rank = fagent->get_comm_rank();
     // INIT_ROCFACE of rocman.f90
   if (COM_get_window_handle( "RFC") <=0 ) {
     if(rank == 0)
       MAN_DEBUG(3, ("Rocstar: load module RocFace.\n"));
     COM_LOAD_MODULE_STATIC_DYNAMIC( Rocface, "RFC");
     int RFC_setv = COM_get_function_handle( "RFC.set_verbose");
     COM_call_function( RFC_setv, &param->rfc_verb);
 #if 0
       // if remeshed
     MAN_DEBUG(3, ("Rocstar: remeshed: %d.\n", param->remeshed));
     if (param->remeshed) {
       double t = fagent->get_coupling()->get_control_param()->current_time;
       compute_overlay( fagent, sagent, t);
     }
 #endif
     // load overlay
     MPI_Comm comm = fagent->get_communicator();
     int RFC_read = COM_get_function_handle( "RFC.read_overlay");
     int fluid_mesh = COM_get_attribute_handle_const( fagent->fluidBufNG+".mesh");
     int solid_mesh = COM_get_attribute_handle_const( sagent->solidBuf+".mesh");
     std::string rfc_dir = "Rocman/"+fagent->get_modinstance_name()+sagent->get_modinstance_name()+"/";
     //std::string rfc_dir = "Rocman/RocfloRocsolid/";
     std::string fluid_dir = rfc_dir+"ifluid";
     std::string solid_dir = rfc_dir+"isolid";
     if(rank == 0)
       MAN_DEBUG(2, ("Rocstar: read RocFace overlay mesh from %s.\n", rfc_dir.c_str()));
     COM_call_function( RFC_read, &fluid_mesh, &solid_mesh, &comm, fluid_dir.c_str(), solid_dir.c_str(), "HDF");
     int RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
     int RFC_interpolate = COM_get_function_handle("RFC.interpolate");
     COM_set_profiling_barrier( RFC_transfer, comm);
     COM_set_profiling_barrier( RFC_interpolate, comm);
   }
 }
COM_EXTERN_MODULE (Rocblas)
COM_EXTERN_MODULE (Rocface)
COM_EXTERN_MODULE (Rocsurf)
COM_EXTERN_MODULE (Rocprop)
void RocstarShutdown (int status = 0)
Definition at line 59 of file rocstar_driver.C.
References COM_finalize().
Referenced by Coupling::Interrupt(), and Coupling::ProcessInterrupt().
 {
   /* Finalize Roccom. */
   COM_finalize();
 #ifdef ROCPROF
   Rocprof_Finalize(true);
 #endif
   /* Close down MPI. */
   MPI_Finalize();
   exit(status);
 }