Rocstar: createM.f90 File Reference
createM.f90 File Reference
Functions/Subroutines
subroutine createm (global)
Function/Subroutine Documentation
subroutine createm (type(rocfrac_global) global)
Definition at line 53 of file createM.f90.
References comp_row_add(), comp_row_addval(), comp_row_getval(), comp_row_resize(), i, implicit_v3d8_mass(), implicit_v3d8_mass_consistent(), inode, j, jnode, Aff_transformation_2< R_ >::m(), and Aff_transformation_repS2< FT >::print().
Referenced by implicit_initialize().