Rocstar: DescaleGridSpeeds.F90 File Reference
DescaleGridSpeeds.F90 File Reference
Functions/Subroutines
subroutine descalegridspeeds (region)
Function/Subroutine Documentation
subroutine descalegridspeeds (type(t_region) region)
Definition at line 48 of file DescaleGridSpeeds.F90.
References moderror::deregisterfunction(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), and Kdtree_d< Traits >::ExtPoint::term().
Referenced by rflo_timestepping().