Rocstar: DirectionS3.h File Reference
DirectionS3.h File Reference
#include <CGAL/SimpleCartesian/VectorS3.h>
Classes
class DirectionS3< FT >
Functions
template<class FT >
std::ostream & operator<< (std::ostream &os, const DirectionS3< FT > &d)
template<class FT >
std::istream & operator>> (std::istream &is, DirectionS3< FT > &p)
Function Documentation
std::ostream& operator<< (std::ostream & os, const DirectionS3< FT > & d)
Definition at line 202 of file DirectionS3.h.
References IO::ASCII, IO::BINARY, IO::mode, v, write(), VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
 {
   VectorS3<FT> v = d.vector();
   switch(os.iword(IO::mode)) {
     case IO::ASCII :
         return os << v.x() << ' ' << v.y()  << ' ' << v.z();
     case IO::BINARY :
         write(os, v.x());
         write(os, v.y());
         write(os, v.z());
         return os;
     default:
         os << "DirectionS3(" << v.x() << ", " << v.y() << ", " << v.z() << ")";
         return os;
     }
 }
std::istream& operator>> (std::istream & is, DirectionS3< FT > & p)
Definition at line 222 of file DirectionS3.h.
References IO::ASCII, IO::BINARY, CGAL_kernel_assertion_msg, IO::mode, read(), x, y, and z.
 {
     FT x, y, z;
     switch(is.iword(IO::mode)) {
     case IO::ASCII :
         is >> x >> y >> z;
         break;
     case IO::BINARY :
         read(is, x);
         read(is, y);
         read(is, z);
         break;
     default:
         CGAL_kernel_assertion_msg(false,"Stream must be in ascii or binary mode");
         // throw ios_base::failure("Stream must be in ascii or binary mode");
         break;
     }
     p = DirectionS3<FT>(x, y, z);
     return is;
 }