Rocstar: DirectionS2.h File Reference
DirectionS2.h File Reference
#include <CGAL/SimpleCartesian/VectorS2.h>
Classes
class DirectionS2< FT >
Functions
template<class FT >
std::ostream & operator<< (std::ostream &os, const DirectionS2< FT > &d)
template<class FT >
std::istream & operator>> (std::istream &is, DirectionS2< FT > &p)
Function Documentation
std::ostream& operator<< (std::ostream & os, const DirectionS2< FT > & d)
Definition at line 230 of file DirectionS2.h.
References IO::ASCII, IO::BINARY, IO::mode, v, write(), VectorS2< FT >::x(), and VectorS2< FT >::y().
 {
     VectorS2<FT> v = d.vector();
     switch(os.iword(IO::mode)) {
     case IO::ASCII :
         return os << v.x() << ' ' << v.y();
     case IO::BINARY :
         write(os, v.x());
         write(os, v.y());
         return os;
     default:
         return os << "DirectionS2(" << v.x() << ", " << v.y() << ')';
     }
 }
std::istream& operator>> (std::istream & is, DirectionS2< FT > & p)
Definition at line 250 of file DirectionS2.h.
References IO::ASCII, IO::BINARY, IO::mode, read(), x, and y.
 {
     FT x, y;
     switch(is.iword(IO::mode)) {
     case IO::ASCII :
         is >> x >> y;
         break;
     case IO::BINARY :
         read(is, x);
         read(is, y);
         break;
     default:
         std::cerr << std::endl << "Stream must be in ascii or binary mode" << std::endl;
         break;
     }
     p = DirectionS2<FT>(x, y);
     return is;
 }