Rocstar: distance_predicatesS3.h File Reference
distance_predicatesS3.h File Reference
#include <CGAL/SimpleCartesian/PointS3.h>
#include <CGAL/SimpleCartesian/PlaneS3.h>
#include <CGAL/predicates/kernel_ftC3.h>
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE
CGAL_KERNEL_LARGE_INLINE
Comparison_result cmp_dist_to_point (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r)
template<class FT >
CGAL_KERNEL_LARGE_INLINE bool has_larger_dist_to_point (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r)
template<class FT >
CGAL_KERNEL_LARGE_INLINE bool has_smaller_dist_to_point (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r)
template<class FT >
CGAL_KERNEL_LARGE_INLINE
Comparison_result cmp_signed_dist_to_plane (const PlaneS3< FT > &h, const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
CGAL_KERNEL_LARGE_INLINE bool has_larger_signed_dist_to_plane (const PlaneS3< FT > &h, const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
CGAL_KERNEL_LARGE_INLINE bool has_smaller_signed_dist_to_plane (const PlaneS3< FT > &h, const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
CGAL_KERNEL_LARGE_INLINE
Comparison_result cmp_signed_dist_to_plane (const PointS3< FT > &hp, const PointS3< FT > &hq, const PointS3< FT > &hr, const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
CGAL_KERNEL_LARGE_INLINE bool has_larger_signed_dist_to_plane (const PointS3< FT > &hp, const PointS3< FT > &hq, const PointS3< FT > &hr, const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
CGAL_KERNEL_LARGE_INLINE bool has_smaller_signed_dist_to_plane (const PointS3< FT > &hp, const PointS3< FT > &hq, const PointS3< FT > &hr, const PointS3< FT > &p, const PointS3< FT > &q)
Function Documentation
CGAL_BEGIN_NAMESPACE CGAL_KERNEL_LARGE_INLINE Comparison_result cmp_dist_to_point (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r)
Definition at line 63 of file distance_predicatesS3.h.
References cmp_dist_to_pointC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   return cmp_dist_to_pointC3(p.x(),p.y(),p.z(),
                              q.x(),q.y(),q.z(),
                              r.x(),r.y(),r.z());
 }
CGAL_KERNEL_LARGE_INLINE Comparison_result cmp_signed_dist_to_plane (const PlaneS3< FT > & h, const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 98 of file distance_predicatesS3.h.
References PlaneS3< FT >::a(), PlaneS3< FT >::b(), PlaneS3< FT >::c(), cmp_signed_dist_to_directionC3(), q, x, PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   return cmp_signed_dist_to_directionC3(h.a(),h.b(),h.c(),
                                         p.x(),p.y(),p.z(),
                                         q,x(),q.y(),q.z());
 }
CGAL_KERNEL_LARGE_INLINE Comparison_result cmp_signed_dist_to_plane (const PointS3< FT > & hp, const PointS3< FT > & hq, const PointS3< FT > & hr, const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 133 of file distance_predicatesS3.h.
References cmp_signed_dist_to_planeC3(), q, x, PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   return cmp_signed_dist_to_planeC3(hp.x(),hp.y(),hp.z(),
                                     hq.x(),hq.y(),hq.z(),
                                     hr.x(),hr.y(),hr.z(),
                                     p.x(),p.y(),p.z(),
                                     q,x(),q.y(),q.z());
 }
CGAL_KERNEL_LARGE_INLINE bool has_larger_dist_to_point (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r)
Definition at line 75 of file distance_predicatesS3.h.
References has_larger_dist_to_pointC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by p_Less_rotate_ccw_E< Point >::operator()().
 {
   return has_larger_dist_to_pointC3(p.x(),p.y(),p.z(),
                                     q.x(),q.y(),q.z(),
                                     r.x(),r.y(),r.z());
 }
CGAL_KERNEL_LARGE_INLINE bool has_larger_signed_dist_to_plane (const PlaneS3< FT > & h, const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 110 of file distance_predicatesS3.h.
References PlaneS3< FT >::a(), PlaneS3< FT >::b(), PlaneS3< FT >::c(), has_larger_signed_dist_to_directionC3(), q, x, PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   return has_larger_signed_dist_to_directionC3(h.a(),h.b(),h.c(),
                                                p.x(),p.y(),p.z(),
                                                q,x(),q.y(),q.z());
 }
CGAL_KERNEL_LARGE_INLINE bool has_larger_signed_dist_to_plane (const PointS3< FT > & hp, const PointS3< FT > & hq, const PointS3< FT > & hr, const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 149 of file distance_predicatesS3.h.
References has_larger_signed_dist_to_planeC3(), q, x, PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   return has_larger_signed_dist_to_planeC3(hp.x(),hp.y(),hp.z(),
                                            hq.x(),hq.y(),hq.z(),
                                            hr.x(),hr.y(),hr.z(),
                                            p.x(),p.y(),p.z(),
                                            q,x(),q.y(),q.z());
 }
CGAL_KERNEL_LARGE_INLINE bool has_smaller_dist_to_point (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r)
Definition at line 87 of file distance_predicatesS3.h.
References has_smaller_dist_to_pointC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by p_Less_dist_to_point< Point >::operator()().
 {
   return has_smaller_dist_to_pointC3(p.x(),p.y(),p.z(),
                                      q.x(),q.y(),q.z(),
                                      r.x(),r.y(),r.z());
 }
CGAL_KERNEL_LARGE_INLINE bool has_smaller_signed_dist_to_plane (const PlaneS3< FT > & h, const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 122 of file distance_predicatesS3.h.
References PlaneS3< FT >::a(), PlaneS3< FT >::b(), PlaneS3< FT >::c(), has_smaller_signed_dist_to_directionC3(), q, x, PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   return has_smaller_signed_dist_to_directionC3(h.a(),h.b(),h.c(),
                                                 p.x(),p.y(),p.z(),
                                                 q,x(),q.y(),q.z());
 }
CGAL_KERNEL_LARGE_INLINE bool has_smaller_signed_dist_to_plane (const PointS3< FT > & hp, const PointS3< FT > & hq, const PointS3< FT > & hr, const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 165 of file distance_predicatesS3.h.
References has_smaller_signed_dist_to_planeC3(), q, x, PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   return has_smaller_signed_dist_to_planeC3(hp.x(),hp.y(),hp.z(),
                                             hq.x(),hq.y(),hq.z(),
                                             hr.x(),hr.y(),hr.z(),
                                             p.x(),p.y(),p.z(),
                                             q,x(),q.y(),q.z());
 }