Rocstar: double.h File Reference
double.h File Reference
#include <CGAL/basic.h>
#include <CGAL/tags.h>
#include <cmath>
#include <CGAL/IEEE_754_unions.h>
Namespaces
NTS
Functions
CGAL_BEGIN_NAMESPACE double to_double (double d)
double sqrt (double d)
bool is_integral (const double d)
Number_tag number_type_tag (double)
bool is_valid (double d)
bool is_finite (double d)
io_Operator io_tag (double)
template<class NT >
NT abs (const NT &x)
CGAL_TEMPLATE_NULL double abs (const double &d)
Function Documentation
io_Operator io_tag (double) inline
Definition at line 200 of file double.h.
 { return io_Operator(); }
bool is_finite (double d) inline
Definition at line 190 of file double.h.
References is_valid().
Referenced by construct_if_finite(), and Line_2_Line_2_pair< R >::intersection_type().
 { return (d == d) && (is_valid(d-d)); }
bool is_integral (const double d) inline
Definition at line 78 of file double.h.
 { return ceil(d) == d; }
bool is_valid (double d) inline
Definition at line 185 of file double.h.
Referenced by is_finite().
 { return (d == d); }
Number_tag number_type_tag (double) inline
Definition at line 83 of file double.h.
 { return Number_tag(); }
double sqrt (double d) inline
Definition at line 73 of file double.h.
Referenced by CImg< uintT >::_display_object3d(), CImg< uintT >::_draw_ellipse(), CImg< uintT >::_draw_object3d(), CImg< uintT >::_draw_spline(), CImg< uintT >::_get_select(), cimg_library::cimg::_pythagore(), a_d_tensors(), accumulatexyzwork(), rflu_modrepair3d::angfnd(), angle(), angle_rad_3d(), arruda_boyce(), arruda_boyce_cauchy(), AspectRatioGammaQualityMetric::AspectRatioGammaQualityMetric(), QualityMetric::average_metric_and_weights(), QualityMetric::average_metrics(), bcondinflowperf(), bcondinflowperf_gl(), bcondoutflowperf(), bcondoutflowperf_gl(), CImg< uintT >::blur_anisotropic(), Propagation_3::bound_radial_disp(), c3d6nm(), rflu_modrepair3d::cavbnd(), rflu_modrepair3d::cavity(), rflu_modrepair3d::circum(), rflu_modrepair3d::circum2(), rflu_modrepair3d::coarsn(), Matrix3D::column_length(), modtools::comppythag(), Geo_Metric_Base_2::compute_aspects(), Geo_Metric_Base_3::compute_aspects(), GeneralizedConditionNumberQualityMetric::compute_condition_number(), compute_fnormal_error(), Rocmop::compute_medial_quadric(), FaceOffset_3::compute_quadrics(), Alg_Metric_Base_3::compute_shape(), Alg_Metric_Base_2::compute_shape(), Window_manifold_2::compute_shortest_edgelen_elements(), Alg_Metric_Base_3::compute_skew(), Alg_Metric_Base_2::compute_skew(), compute_vnormal_error(), computeavgco(), computefacewidth(), computeflux(), computefluxtot(), NonSmoothSteepestDescent::condition3x3(), ShapeQualityMetric::condition_number_3d(), RFC_Window_overlay::cos_edge_angle(), RFC_Window_overlay::cos_face_angle(), cst_coh(), rflu_modrepair3d::densfn(), RFC_Window_overlay::detect_features(), rflu_modrepair3d::dihed(), Halfedge::dihedral_angle(), dist(), vector3d::dist(), MVec::distance_between(), CImg< uintT >::distance_hamilton(), CImg< uintT >::draw_arrow(), CImg< uintT >::draw_plasma(), dsyevq3(), dsytrd3(), edge_length(), rflu_modrepair3d::edglen(), CImg< uintT >::eigen(), Rocmop::eigen_analyze_vertex(), Window_manifold_2::elements_to_nodes(), enhanced_elem_maps_hex(), enorm_3d(), CImg< T >::_cimg_math_parser::eval(), FaceOffset_3::eval_angle(), AspectRatioGammaQualityMetric::evaluate_element(), rflu_modrepair3d::facear(), rflu_modrepair3d::fangle(), FindMagnitudeRange(), findprobe(), fluidpressload(), func1(), g_fcn_ridft2(), g_fcn_ridft3(), Mesquite::g_gdft_2(), Mesquite::g_gdft_2_v0(), Mesquite::g_gdft_2_v1(), Mesquite::g_gdft_2_v2(), Mesquite::g_gdft_3(), Mesquite::g_gdft_3_v0(), Mesquite::g_gdft_3_v1(), Mesquite::g_gdft_3_v2(), Mesquite::g_gdft_3_v3(), DistanceFromTarget::get_barrier_function(), Rocmop::get_constraint_directions(), CImg< uintT >::get_correlate(), CImg< uintT >::get_distance(), Overlay_primitives::get_face_normal(), CImg< uintT >::get_gradient(), Pane_connectivity::get_local_boundary_nodes(), CImg< uintT >::get_matrix_at(), CImg< uintT >::get_norm(), QualityAssessor::Assessor::get_rms(), QualityAssessor::Assessor::get_stddev(), FaceOffset_3::get_tangents(), CkSampleT< real, ret >::getStddev(), cimg_library::cimg::grand(), h_fcn_ridft2(), h_fcn_ridft3(), Mesquite::h_gdft_2(), Mesquite::h_gdft_2_v0(), Mesquite::h_gdft_2_v1(), Mesquite::h_gdft_2_v2(), Mesquite::h_gdft_3(), Mesquite::h_gdft_3_v0(), Mesquite::h_gdft_3_v1(), Mesquite::h_gdft_3_v2(), Mesquite::h_gdft_3_v3(), heatfluxload(), heatload_hex(), homogenizedmat(), NonSmoothSteepestDescent::init_max_step_length(), FluRegion::InitVolumeSoln(), inrt_calcdrag(), inrt_calcheattransfernonburn(), inrt_calcscouring(), Overlay::insert_node_in_blue_edge(), Overlay_primitives::intersect(), Exponent::invSquareRoot(), jacobi(), Generic_element_2::Jacobian_det(), MVec::length(), Vector3D::length(), Mesquite::length(), m_fcn_ridft2(), m_fcn_ridft3(), Mesquite::m_gdft_2(), Mesquite::m_gdft_3(), vector3d::mag(), CImg< uintT >::magnitude(), main(), Overlay::match_features_0(), matmodel_elastic(), matmodel_hyperelastic(), matous_const_model(), matvol_sub(), max_dt_solid(), max_sqrt_element(), min_sqrt_element(), mixtgasliq_c(), mixtgasliq_p(), mixtliq_c_bp(), mixtperf_c_co2guvw(), mixtperf_c_dgp(), mixtperf_c_ghovm2(), mixtperf_c_grt(), mixtperf_vm_c2co2g(), MVec::move_to_line(), CImg< uintT >::noise(), CPoint::norm(), Vector_3< Real >::norm(), nvc::norm(), Vector_2< T >::norm(), CVector::norm(), C3Vector::Norm(), norm_and_clean_constraints(), Vector_3< Real >::normalize(), Rocsurf::normalize(), Vector_2< T >::normalize(), RFC_Window_overlay::normalize(), CImg< uintT >::normalize(), rflu_modrepair3d::octfnd(), one_sided_normal(), Rocblas::sqrta< T >::operator()(), SteepestDescent::optimize_vertex_positions(), Transfer_base::pcg(), perfgasdependentvars(), perfgastransportvars(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_derivedinputvalues(), peul_centralflux(), peul_centralfluxpatch(), peul_residualsmoothingcoeffs(), peul_spectralradii(), plag_modsurfstats::plag_gathersurfstats(), plag_injcejectparticle(), plag_injctilecalcrhs(), plag_modinjection::plag_invokeconsrandejec(), plag_rflu_modfindcells::plag_rflu_computedisttot(), plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), plag_rflu_modfindcells::plag_rflu_findcellstrajsafe(), planenorm(), planenorm3d(), CImg< uintT >::pow(), Exponent::powThreeHalves(), cimg_library::cimg::prand(), principal_stress(), CImg< uintT >::print(), prep_modbcdistribution::profinflowvttaylorcyl(), Overlay::project_adjacent_green_vertices(), CImg< uintT >::PSNR(), Mesquite::QR(), radi_diffradflux(), radi_diffradfluxpatch(), radi_flimdifffluxpatch(), radi_floflimcentfluxpatch(), radi_fluxlimiter(), radi_rflo_flimressmoothingcoeff(), rflu_modrepair3d::radrat(), modrandom::randnormal(), read_patran(), Rocmop::redistribute_vertices_smooth(), FaceOffset_3::reset_default_parameters(), rflo_arclengthbounds(), rflo_modgridmetrics::rflo_arclengthpatch(), rflo_modboundaryconditions::rflo_bcondfarfield(), rflo_modboundaryconditions::rflo_bcondinflow(), rflo_modboundaryconditions::rflo_bcondinjection(), rflo_modboundaryconditions::rflo_bcondinjectionapn(), rflo_modboundaryconditions::rflo_bcondinjectioninit(), rflo_modboundaryconditions::rflo_bcondoutflow(), rflo_modboundaryconditions::rflo_bcondoutflowperf(), rflo_modgridregionshape::rflo_blockskewedcell(), rflo_boundarydeformation(), rflo_calcfacevectors(), rflo_calcthrust(), rflo_centralfluxpatch(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_edgedeformation(), rflo_edgedeformationstraight(), rflo_getdeformation(), rflo_modgridcontrolmap::rflo_gridcontrolmap2d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_modgridregionshape::rflo_gridflatpatch(), rflo_gridremesh(), rflo_laplacegridsolve(), rflo_modlaplacesmoothing::rflo_laplacegridsolve(), rflo_modmovegridelliptfra::rflo_mgelliptboundaries(), rflo_modmovegridelliptfra::rflo_mgelliptedgesfra(), rflo_modmovegridelliptglo::rflo_mgelliptedgesglo(), rflo_modmovegridframe::rflo_mgframebnddeformation(), rflo_modmovegridframe::rflo_mgframebnddeformation0(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframeedges(), rflo_modmovegridframe::rflo_mgframeedgeso(), rflo_modmovegridframe::rflo_mgframemovecorners(), rflo_modmovegridframe::rflo_mgframeorthoshift(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_modmovegridutil::rflo_movegridcurvedpatch(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_modmovegridutil::rflo_movegridqflatpatch(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_modvectortensor::rflo_normcrossprod(), rflo_residualnorm(), rflo_residualsmoothingcoeffs(), rflo_roedissipfirst(), rflo_roedissipsecond(), rflo_roefluxpatch(), rflo_sendboundaryvalues(), rflo_timestepinviscid(), rflo_timestepviscous(), rflo_modvolmeshsmoothing::rflo_vmsprojectvertices(), rflu_modbilinearpatch::rflu_blin_computenormal(), rflu_modbilinearpatch::rflu_blin_computexsectline(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modgeometry::rflu_buildbvertexnormals(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_modgeometry::rflu_buildgeometry(), rflu_modoles::rflu_buildstencilsoles(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch_gl(), rflu_checkgridspeeds(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_modexactflow::rflu_computeexactflowculick(), rflu_computeexactflowerror(), rflu_modexactflow::rflu_computeexactflowpacoust(), rflu_computeexactflowprobeerror(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_moddifferentiationbfaces::rflu_computegradbfaces(), rflu_moddifferentiationcells::rflu_computegradcells_2d(), rflu_moddifferentiationcells::rflu_computegradcells_3d(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationcells::rflu_computegradcellsfast_2d(), rflu_moddifferentiationcells::rflu_computegradcellsfast_3d(), rflu_moddifferentiationfaces::rflu_computegradfaces(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_modplottingvars::rflu_computeplottingvarsdisc(), rflu_modweights::rflu_computestencilmoments2d1(), rflu_modweights::rflu_computestencilmoments3d1(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_modextractflowdata::rflu_extractflowdatablasius(), rflu_modextractflowdata::rflu_extractflowdatalinefarf(), rflu_modextractflowdata::rflu_extractflowdataskews(), rflu_modrocstartools::rflu_genx_constraindisp(), rflu_modrocstartools::rflu_genx_initbflag(), rflu_modrocstartools::rflu_genx_movegrid(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_initbcdatahardcode(), rflu_initflowhardcode(), rflu_modinterpolation::rflu_interpcells2face(), rflu_modinterpolation::rflu_interpcells2facepatch(), rflu_modinterpolation::rflu_interpcells2faces(), rflu_movegriddisp(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modoctree::rflu_queryoctree(), rflu_residualnorm(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux1_tcp(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxd1_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_modrindstates::rflu_setrindstateslipwallperf(), rflu_settransportvars(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_timestepviscous(), rflu_modtimezoom::rflu_timezoomcomputebulkvars(), CImg< uintT >::RGBtoHSI(), rocfracmain::rocfracsoln(), CImg< uintT >::rotation_matrix(), rvav_blasiussolution(), rvav_computeerror(), rvav_extractvariables(), FaceOffset_3::set_courant_constant(), smallestelement(), rflu_modrepair3d::snglar(), FaceOffset_3::solve_quadratic_func(), CImg< uintT >::sphere3d(), splitquadface(), CImg< uintT >::sqrt(), Exponent::squareRoot(), rflu_modrepair3d::struct(), CImg< uintT >::SVD(), TerminationCriterion::terminate(), rflu_modrepair3d::tetang(), rflu_modrepair3d::tetar(), rflu_modrepair3d::tetar2(), rflu_modrepair3d::tetar3(), tractload(), tractloaddef(), tractpressload(), tractpressloaddef(), TRAIL_FluInitVolSoln(), tred1(), tred2(), tri_area(), turb_coranswalldistov(), turb_derivedinputvalues(), turb_floranssacentfluxpatch(), turb_floranssaroefluxpatch(), turb_flowlmmetric(), turb_flowlmupdateloglay(), turb_flulesbmij(), turb_lescalceddyvis(), turb_lesesgmodel4(), turb_lesmij(), turb_ranssasourceterms(), turb_rflo_ransressmoothingcoeff(), turb_rflo_writesolution(), turb_rflu_writesolutionascii(), turb_rflu_writesolutionbinary(), turb_visfluxeddypatch(), turb_wlmfluxpatch(), turb_wlminitia(), turb_wlmreyanalogy(), turb_wlmupdatebndlay(), unit_normal(), nvc::unitize(), FullyCoupling::update_distances(), updatetbcstochastic(), NonSmoothSteepestDescent::validity_check(), CImg< uintT >::variancemean(), QualityMetric::vertex_barrier_function(), vol_elem_mat_matous(), rflu_modrepair3d::volput(), writetecplotascii(), and writetecplotbinary().
 { return std::sqrt(d); }
CGAL_BEGIN_NAMESPACE double to_double (double d) inline
Definition at line 68 of file double.h.
Referenced by PointS2< FT >::bbox(), PointS3< FT >::bbox(), and rational_rotation_approximation().
 { return d; }