Rocstar: Element.cpp File Reference
Element.cpp File Reference
#include "Element.hpp"
#include "HexElement.hpp"
#include "TetElement.hpp"
#include "TCoElement.hpp"
#include "QCoElement.hpp"
#include "Node.hpp"
#include "Face.hpp"
#include "Mesh.hpp"
#include <assert.h>
#include <math.h>
Functions
istream & operator>> (istream &stream, Element &elem)
ostream & operator<< (ostream &stream, Element &elem)
Function Documentation
ostream& operator<< (ostream & stream, Element & elem)
Definition at line 91 of file Element.cpp.
References Element::d_eType, Element::d_ID, Element::d_materialType, Element::d_nodes, Node::getID(), Element::getNumNodes(), and i.
{
         stream << elem.d_ID << '\t' << elem.d_eType << '\t' << elem.d_materialType;
         // write nodes out to file.
         //OK, we have to special-case the cohesive elements due to
         //the strange way that they are supposed to be output.  So,
         //the tet-cohesive element needs to have 1-2-3 as usual, but then "4" should be
         //the node that matches up with node 3, instead of node 1.  Thus, since
         //the elements are stored 1-2-3 4-5-6, with 4 matched with 1, 5 matched
         //with 2, etc., we have to output 1-2-3-6-4-5.  Similarly, for the
         //quad cohesive, we output 1-2-3-4-8-5-6-7.
         switch(elem.d_eType) {
         case 2:  //e_tri_cohesive
                 stream << '\t' << elem.d_nodes[0]->getID();
                 stream << '\t' << elem.d_nodes[1]->getID();
                 stream << '\t' << elem.d_nodes[2]->getID();
                 stream << '\t' << elem.d_nodes[5]->getID();
                 stream << '\t' << elem.d_nodes[3]->getID();
                 stream << '\t' << elem.d_nodes[4]->getID();
                 stream << endl;
                 break;
         case 3:  //e_quad_cohesive
                 stream << '\t' << elem.d_nodes[0]->getID();
                 stream << '\t' << elem.d_nodes[1]->getID();
                 stream << '\t' << elem.d_nodes[2]->getID();
                 stream << '\t' << elem.d_nodes[3]->getID();
                 stream << '\t' << elem.d_nodes[7]->getID();
                 stream << '\t' << elem.d_nodes[4]->getID();
                 stream << '\t' << elem.d_nodes[5]->getID();
                 stream << '\t' << elem.d_nodes[6]->getID();
                 stream << endl;
                 break;
         default:
                 //put out in the order it's stored in the d_nodes array.
                 //default for normal tet and brick elements.
                 int numn = elem.getNumNodes();
                 int i;
                 for( i = 0; i < numn; i++ ){
                 stream << '\t' << elem.d_nodes[i]->getID();
                 }
                 stream << endl;
         }
         return stream;
 }
istream& operator>> (istream & stream, Element & elem)
Definition at line 70 of file Element.cpp.
References Node::addElement(), Element::d_materialType, Element::d_nodes, Mesh::getNode(), Element::getNumNodes(), i, Element::s_mesh, and Element::setFromMyNodes().
{
   // read material
   stream >> elem.d_materialType;
   // read nodes & set
   int numn = elem.getNumNodes();
   int i;
   for( i = 0; i < numn; i++ ){
     int node_id;
     stream >> node_id;
     Node *node = elem.s_mesh->getNode(node_id);
     elem.d_nodes[i] = node;
     node->addElement( &elem );
   }
   elem.setFromMyNodes();
   return stream;
 }