Rocstar: face.cpp File Reference
face.cpp File Reference
#include <stdio.h>
#include "makeflo.h"
#include "face.h"
Classes
class facet
Functions
static int firstSet (const blockLoc &l)
static int findOther (int a, int b)
static void matchOrientations (orient_t &orient, const blockLoc &sX, const blockLoc &sY, const blockLoc &dX, const blockLoc &dY)
bool isDisjoint (const blockSpan &a, const blockSpan &b)
Function Documentation
static int findOther (int a, int b) static
Definition at line 83 of file face.cpp.
Referenced by face::face(), matchOrientations(), and face::nodeForCoord().
 {
         int ret=0;
         while (a==ret || b==ret)
                 ret++; //Keep looking
         return ret; //Found it!
 }
static int firstSet (const blockLoc & l) static
Definition at line 70 of file face.cpp.
References i.
Referenced by matchOrientations().
 {
         for (int i=0;i<3;i++)
                 if (l[i]!=0)
                         return i;
         //If we get here, all coordinates are zero-- very bad
         fprintf(stderr,"ERROR! %s:%d> Orientation vector all zeros!\n",
                __FILE__,__LINE__);
         abort();
         return -1;
 }
bool isDisjoint (const blockSpan & a, const blockSpan & b)
Definition at line 167 of file face.cpp.
References blockSpan::end, and blockSpan::start.
Referenced by face::buildPatches().
{
         for (int axis=0;axis<2;axis++) {
                 if (a.start[axis]>=b.end[axis]-1) return true;
                 if (b.start[axis]>=a.end[axis]-1) return true;
         }
         return false;//No separating axis-- must have a shared point
 }
static void matchOrientations (orient_t & orient, const blockLoc & sX, const blockLoc & sY, const blockLoc & dX, const blockLoc & dY) static
Definition at line 95 of file face.cpp.
References findOther(), and firstSet().
Referenced by face::buildPatches().
 {
         //Compute the block orientations in the face X and Y axes
         int sOX=firstSet(sX),sOY=firstSet(sY);
         int dOX=firstSet(dX),dOY=firstSet(dY);
         //Match up the orientations along the face
         orient[sOX]=dOX;
         orient[sOY]=dOY;
         //The remaining orientation is found by the
         // process of elimination
         orient[findOther(sOX,sOY)]=findOther(dOX,dOY);
 }