Rocstar: FaceCentroid.F90 File Reference
FaceCentroid.F90 File Reference
Functions/Subroutines
subroutine facecentroidtria (xyz, fCenX, fCenY, fCenZ)
subroutine facecentroidquad (xyz, fCenX, fCenY, fCenZ)
Function/Subroutine Documentation
subroutine facecentroidquad (real(rfreal), dimension(3,4), intent(in) xyz, real(rfreal), intent(out) fCenX, real(rfreal), intent(out) fCenY, real(rfreal), intent(out) fCenZ)
Definition at line 73 of file FaceCentroid.F90.
Referenced by rflu_modgeometry::rflu_buildgeometry(), rflu_computegridspeeds(), and rflu_modcobalt::rflu_convcobalt2rocflu().
subroutine facecentroidtria (real(rfreal), dimension(3,3), intent(in) xyz, real(rfreal), intent(out) fCenX, real(rfreal), intent(out) fCenY, real(rfreal), intent(out) fCenZ)
Definition at line 47 of file FaceCentroid.F90.
Referenced by rflu_modgeometry::rflu_buildgeometry(), rflu_computegridspeeds(), and rflu_modcobalt::rflu_convcobalt2rocflu().