Rocstar: FaceVector.F90 File Reference
FaceVector.F90 File Reference
Functions/Subroutines
subroutine facevectortria (xyzNodes, fVecX, fVecY, fVecZ)
subroutine facevectorquad (xyzNodes, fVecX, fVecY, fVecZ)
Function/Subroutine Documentation
subroutine facevectorquad (real(rfreal), dimension(3,4) xyzNodes, real(rfreal) fVecX, real(rfreal) fVecY, real(rfreal) fVecZ)
Definition at line 80 of file FaceVector.F90.
Referenced by rflo_calcfacevectors(), rflo_calcgridspeeds(), rflu_modgeometry::rflu_buildgeometry(), rflu_computegridspeeds(), and rflu_modcobalt::rflu_convcobalt2rocflu().
subroutine facevectortria (real(rfreal), dimension(3,3) xyzNodes, real(rfreal) fVecX, real(rfreal) fVecY, real(rfreal) fVecZ)
Definition at line 49 of file FaceVector.F90.
Referenced by rflu_modgeometry::rflu_buildgeometry(), rflu_computegridspeeds(), rflu_modcobalt::rflu_convcobalt2rocflu(), and splitquadface().