Rocstar: feminp.f90 File Reference
feminp.f90 File Reference
Functions/Subroutines
subroutine feminp (glb, myid)
subroutine prefix_sub (glb)
subroutine ale_sub (glb)
subroutine nrun_sub (glb)
subroutine dynamic_sub (glb, keywd)
subroutine dummytract_sub (glb, keywd)
subroutine matmodel_hyperelastic (glb, keywd, tmp_E, tmp_xnu, tmp_rho, tmp_alpha, tmp_iSolnType)
subroutine matmodel_elastic (glb, keywd, tmp_E, tmp_xnu, tmp_rho, tmp_alpha, tmp_iSolnType)
subroutine matvol_sub (glb, tmp_E, tmp_xnu, tmp_rho, tmp_alpha, tmp_iSolnType)
subroutine matcoh_sub (glb)
subroutine pload1_sub (glb)
subroutine nodeio_sub (myid)
subroutine boundary_sub (glb)
subroutine boundaryht_sub (glb)
subroutine boundarymm_sub (glb)
subroutine amplitude_sub (glb, keywd)
subroutine element_sub (glb, keywd)
subroutine heat_transfer_sub (glb, keywd, tmp_KappaHT, tmp_Cp, tmp_iSolnTypeHT)
subroutine probe_sub (glb)
subroutine micromechanical_sub (glb, keywd, tmp_E, tmp_xnu, tmp_rho, tmp_alpha, tmp_iSolnType)
subroutine initialcondition_sub (glb, keywd)
Function/Subroutine Documentation
subroutine ale_sub (type(rocfrac_global) glb)
Definition at line 459 of file feminp.f90.
Referenced by feminp().
subroutine amplitude_sub (type(rocfrac_global) glb, character keywd)
Definition at line 1002 of file feminp.f90.
References i, locchr(), and Action::run().
Referenced by feminp().
subroutine boundary_sub (type(rocfrac_global) glb)
Definition at line 888 of file feminp.f90.
References i.
Referenced by feminp().
subroutine boundaryht_sub (type(rocfrac_global) glb)
Definition at line 926 of file feminp.f90.
References i.
Referenced by feminp().
subroutine boundarymm_sub (type(rocfrac_global) glb)
Definition at line 965 of file feminp.f90.
References i.
Referenced by feminp().
subroutine dummytract_sub (type(rocfrac_global) glb, character(len=200) keywd)
Definition at line 548 of file feminp.f90.
References locchr().
Referenced by feminp().
subroutine dynamic_sub (type(rocfrac_global) glb, character(len=200) keywd)
Definition at line 511 of file feminp.f90.
References locchr(), and rchar().
Referenced by feminp().
subroutine element_sub (type(rocfrac_global) glb, character(len=200) keywd)
Definition at line 1076 of file feminp.f90.
References locchr(), Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
Referenced by feminp(), and readinp().
subroutine feminp (type(rocfrac_global) glb, integer myid)
Definition at line 53 of file feminp.f90.
References ale_sub(), amplitude_sub(), boundary_sub(), boundaryht_sub(), boundarymm_sub(), dummytract_sub(), dynamic_sub(), element_sub(), heat_transfer_sub(), i, initialcondition_sub(), matcoh_sub(), matmodel_elastic(), matmodel_hyperelastic(), matvol_sub(), max(), micromechanical_sub(), nodeio_sub(), nrun_sub(), pload1_sub(), prefix_sub(), Aff_transformation_repS2< FT >::print(), probe_sub(), Attribute::status(), StopWatch::stop(), and x.
Referenced by rocfracmain::rocfracinitialize().
subroutine heat_transfer_sub (type(rocfrac_global) glb, character keywd, real*8, dimension(1:10) tmp_KappaHT, real*8, dimension(1:10) tmp_Cp, integer, dimension(1:10) tmp_iSolnTypeHT)
Definition at line 1135 of file feminp.f90.
References i, j, and Aff_transformation_repS2< FT >::print().
Referenced by feminp().
subroutine initialcondition_sub (type(rocfrac_global) glb, character(len=200) keywd)
Definition at line 1373 of file feminp.f90.
References locchr().
Referenced by feminp().
subroutine matcoh_sub (type(rocfrac_global) glb)
Definition at line 817 of file feminp.f90.
References i.
Referenced by feminp().
subroutine matmodel_elastic (type(rocfrac_global) glb, character keywd, real*8, dimension(1:10) tmp_E, real*8, dimension(1:10) tmp_xnu, real*8, dimension(1:10) tmp_rho, real*8, dimension(1:10) tmp_alpha, integer, dimension(1:10) tmp_iSolnType)
Definition at line 698 of file feminp.f90.
References i, locchr(), max(), Aff_transformation_repS2< FT >::print(), and sqrt().
Referenced by feminp().
subroutine matmodel_hyperelastic (type(rocfrac_global) glb, character keywd, real*8, dimension(1:10) tmp_E, real*8, dimension(1:10) tmp_xnu, real*8, dimension(1:10) tmp_rho, real*8, dimension(1:10) tmp_alpha, integer, dimension(1:10) tmp_iSolnType)
Definition at line 591 of file feminp.f90.
References conchr(), i, key, max(), Aff_transformation_repS2< FT >::print(), and sqrt().
Referenced by feminp().
subroutine matvol_sub (type(rocfrac_global) glb, real*8, dimension(1:10) tmp_E, real*8, dimension(1:10) tmp_xnu, real*8, dimension(1:10) tmp_rho, real*8, dimension(1:10) tmp_alpha, integer, dimension(1:10) tmp_iSolnType)
Definition at line 780 of file feminp.f90.
References i, max(), Aff_transformation_repS2< FT >::print(), sqrt(), and StopWatch::stop().
Referenced by feminp(), and readinp().
subroutine micromechanical_sub (type(rocfrac_global) glb, character keywd, real*8, dimension(1:10) tmp_E, real*8, dimension(1:10) tmp_xnu, real*8, dimension(1:10) tmp_rho, real*8, dimension(1:10) tmp_alpha, integer, dimension(1:10) tmp_iSolnType)
Definition at line 1224 of file feminp.f90.
References homogenizedmat(), i, locchr(), Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
Referenced by feminp().
subroutine nodeio_sub (integer myid)
Definition at line 857 of file feminp.f90.
References i.
Referenced by feminp().
subroutine nrun_sub (type(rocfrac_global) glb)
Definition at line 491 of file feminp.f90.
Referenced by feminp().
subroutine pload1_sub (type(rocfrac_global) glb)
Definition at line 842 of file feminp.f90.
Referenced by feminp().
subroutine prefix_sub (type(rocfrac_global) glb)
Definition at line 431 of file feminp.f90.
Referenced by feminp(), and readinp().
subroutine probe_sub (type(rocfrac_global) glb)
Definition at line 1186 of file feminp.f90.
References i.
Referenced by feminp().