Rocstar: Fluid_finalize.F90 File Reference
Fluid_finalize.F90 File Reference
Functions/Subroutines
subroutine fluid_finalize (globalGenx)
Function/Subroutine Documentation
subroutine fluid_finalize (type(t_globalgenx), pointer globalGenx)
Definition at line 43 of file Fluid_finalize.F90.
References rflo_endflowsolver(), and rflu_endflowsolver().
Referenced by rocflo_load_module(), and rocflu_load_module().