Rocstar: FluRegion.H File Reference
FluRegion.H File Reference
Classes
class FluVolumeSoln
class FluSurfSoln
class FluPatch
class FluBorder
class FluRegion
Functions
istream & SkipLines (istream &, unsigned int=1)
Function Documentation
istream& SkipLines (istream & , unsigned int = 1)
Referenced by FluRegion::PopRemBordIndFILE(), FluRegion::ReadFluCOM(), FluRegion::ReadFluDIM(), FluRegion::ReadFluGridASCII(), FluRegion::ReadFluSolnASCII(), FluRegion::ReadGSPASCII(), TRAIL_FluPopRemBordIndFILE(), TRAIL_FluReadCOM(), TRAIL_FluReadDIM(), and TRAIL_FluReadGridASCII().