Rocstar: FluRegion.C File Reference
FluRegion.C File Reference
#include <iostream>
#include <vector>
#include <string>
#include <iomanip>
#include <sstream>
#include <fstream>
#include <map>
#include <list>
#include <cmath>
#include <cassert>
#include "roccom.h"
#include "GEM.H"
#include "FluRegion.H"
Functions
istream & SkipLines (istream &ioo, unsigned int n)
Function Documentation
istream& SkipLines (istream & ioo, unsigned int n)
Definition at line 1825 of file FluRegion.C.
Referenced by FluRegion::PopRemBordIndFILE(), FluRegion::ReadFluCOM(), FluRegion::ReadFluDIM(), FluRegion::ReadFluGridASCII(), FluRegion::ReadFluSolnASCII(), and FluRegion::ReadGSPASCII().
 {
   string line;
   unsigned int l = 0;
   while(l++ < n)
     getline(ioo,line);
   return(ioo);
 }