Rocstar: functions_on_enums.h File Reference
functions_on_enums.h File Reference
#include <CGAL/config.h>
#include <CGAL/enum.h>
Functions
template<class T >
CGAL_BEGIN_NAMESPACE T opposite (const T &t)
CGAL_TEMPLATE_NULL Sign opposite (const Sign &o)
CGAL_TEMPLATE_NULL Oriented_side opposite (const Oriented_side &os)
CGAL_TEMPLATE_NULL Bounded_side opposite (const Bounded_side &bs)
Function Documentation
CGAL_BEGIN_NAMESPACE T opposite (const T & t) inline
Definition at line 67 of file functions_on_enums.h.
Referenced by Halfedge_data_structure_using_vector< V, H, F >::normalize_border(), Ray_3< R, T >::opposite(), _HDS_vector_halfedge< V, H, F >::opposite(), Line_3< R, T >::opposite(), Ray_2< R, T >::opposite(), Plane_3< R, T >::opposite(), and Line_2< R >::opposite().
 { return -t; }
CGAL_TEMPLATE_NULL Sign opposite (const Sign & o) inline
Definition at line 73 of file functions_on_enums.h.
 { return (Sign)(-(int)o); }
CGAL_TEMPLATE_NULL Oriented_side opposite (const Oriented_side & os) inline
Definition at line 79 of file functions_on_enums.h.
 { return (Oriented_side)(-(int)os); }
CGAL_TEMPLATE_NULL Bounded_side opposite (const Bounded_side & bs) inline
Definition at line 85 of file functions_on_enums.h.
 { return (Bounded_side)(-(int)bs); }