Rocstar: genstar.C File Reference
genstar.C File Reference
#include <iostream>
#include <iomanip>
#include <vector>
#include <string>
#include <fstream>
#include <sstream>
#include <map>
#include <list>
#include <cassert>
#include <cstdlib>
#include "GEM.H"
#include "FluRegion.H"
#include "mpi.h"
#include "roccom.h"
Functions
COM_EXTERN_MODULE (Rocout)
int main (int argc, char *argv[])
Function Documentation
COM_EXTERN_MODULE (Rocout)
int main (int argc, char * argv[])
Definition at line 49 of file genstar.C.
References FluRegion::_borders, FluRegion::_patches, COM_finalize(), COM_init(), FluRegion::CreateRegionMapFile(), GEM_Partition::debug(), GEM_Partition::DestroyWindows(), GEM_Partition::InitRoccomWindows(), MPI_COMM_WORLD, n, rank, FluRegion::ReadRegionASCII(), FluRegion::RegisterFluSurfaceMesh(), FluRegion::RegisterSurfaceSoln(), FluRegion::RegisterVolumeSoln(), FluRegion::WriteFluGridASCII(), FluRegion::WriteFluNative(), FluRegion::WriteFluSolnASCII(), GEM_Partition::WriteRocstar(), and y.
 {
   if(argc < 4){
     cerr << "genstar <source_prefix> <target_prefix> <npartitions>" << endl;
     return(1);
   }
   int nproc = 1;
   int rank = 0;
   //#ifdef _TRAIL_MPI_
   MPI_Init(&argc,&argv);
   MPI_Comm_size(MPI_COMM_WORLD,&nproc);
   MPI_Comm_rank(MPI_COMM_WORLD,&rank);
   //#ifdef _ROCSTAR_X_
   COM_init(&argc,&argv);
   //#endif
   //#endif
   bool verbose = true;
   string source_prefix(argv[1]);
   string targ_prefix(argv[2]);
   unsigned int npart;
   string snpart(argv[3]);
   istringstream Istr(snpart);
   Istr >> npart;
   unsigned int N;
   int R;
   unsigned int first;
   if(npart < (unsigned int)nproc){
     N = 1;
     first = rank;
   }
   else{
     N = npart/nproc;
     R = npart - (nproc*N);
     if(rank < R){
       first = rank * N + rank;
       N++;
     }
     else
       first = rank * N + R;
   }
   if(!rank)
     cout << rank << ": Processing " << npart << " partitions." << endl;
   if(verbose)
     cout << rank << ": Local partitions: (" << N << "," << first
          << ")" << endl;
   int part_index = first;
   unsigned int n = 0;
   while(n < N){
     if(!rank && verbose)
       cout << "Processing " << part_index++ << "." << endl;
     FluRegion fluregion;
     fluregion.debug();
     bool unsteady = true;
     double t = 0.0;
     unsigned int niter = 0;
     fluregion.ReadRegionASCII(source_prefix,part_index,niter,t,unsteady);
     fluregion.WriteFluNative(targ_prefix);
     fluregion.WriteFluGridASCII(targ_prefix,t,unsteady);
     fluregion.WriteFluSolnASCII(targ_prefix,niter,t,unsteady);
     fluregion.CreateRegionMapFile(targ_prefix,npart,npart);
     //#ifdef _ROCSTAR_X_
     fluregion.InitRoccomWindows("flu",fluregion._borders,fluregion._patches);
     fluregion.RegisterFluSurfaceMesh();
     fluregion.RegisterVolumeSoln(true);
     fluregion.RegisterSurfaceSoln(false);
     fluregion.InitDone();
     string::size_type y = targ_prefix.find_last_of("/");
     string targ_dir = targ_prefix.substr(0,y);
     fluregion.WriteRocstar(targ_dir);
     fluregion.DestroyWindows();
     //#endif
     n++;
   }
   //#ifdef _TRAIL_MPI_
   MPI_Finalize();
   //#endif
     //#ifdef _ROCSTAR_X_
   COM_finalize();
   //#endif
   return(0);
 }