Rocstar: geometry.h File Reference
geometry.h File Reference
Geometric helper function header file.
#include "mopbasic.h"
#include <cmath>
#include <vector>
Functions
MOP_BEGIN_NAMESPACE void min_max3 (double a1, double a2, double a3, double &min, double &max)
Find minimum and maximum of 3 numbers.
void min_max4 (double a1, double a2, double a3, double a4, double &min, double &max)
Find minimum and maximum of 4 numbers.
void min_max6 (double a1, double a2, double a3, double a4, double a5, double a6, double &min, double &max)
Find minimum and maximum of 6 numbers.
void min_max12 (double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8, double a9, double a10, double a11, double a12, double &min, double &max)
Find minimum and maximum of 12 numbers.
double angle (Vector_3< double > v1, Vector_3< double > v2)
Compute the angle between two vectors.
double f_angle (Vector_3< double > v1, Vector_3< double >v2)
Compute the angle between two faces.
double dotP (const Vector_3< double > &v1, const Vector_3< double > &v2)
Compute the dot Product of two vectors.
void crossP (const Vector_3< double > &v1, const Vector_3< double > &v2, Vector_3< double > &v3)
Compute the cross Product of two vectors.
void unit_normal (const Vector_3< double > &v1, const Vector_3< double > &v2, Vector_3< double > &v3)
Compute the unit vector normal to two input vectors.
double edge_length (const Vector_3< double > &v)
Compute the edge length of a vector.
double tri_area (const Vector_3< double > &v1, const Vector_3< double > &v2, const Vector_3< double > &v3)
Compute the area of a triangle defined by its three sides as vectors.
double tet_vol (const Vector_3< double > &a, const Vector_3< double > &b, const Vector_3< double > &c)
Compute the volume of a tetrahedron given three edges from a point as vectors.
void printv (const Vector_3< double > &v)
Print a vector.
Detailed Description
Geometric helper function header file.
Definition in file geometry.h.
Function Documentation
double angle (Vector_3< double > v1, Vector_3< double > v2)
Compute the angle between two vectors.
Definition at line 61 of file geometry.C.
References cimg_library::acos(), dot_product(), dotP(), nvc::norm2(), and sqrt().
Referenced by Geo_Metric_Base_2::compute_angles(), Geo_Metric_Base_3::compute_angles(), Rocmop::compute_medial_quadric(), FaceOffset_3::compute_quadrics(), CImg< uintT >::cone3d(), CFacet::contains_point(), CImg< uintT >::cylinder3d(), CImg< uintT >::draw_arrow(), f_angle(), and CImg< uintT >::FFT().
{
   double dot_product, norm1, norm2, angle;
   dot_product = dotP(v1,v2);
   norm1 = sqrt(dotP(v1,v1)); norm2 = sqrt(dotP(v2,v2));
   angle = acos(dot_product/(norm1*norm2));
   assert(dot_product/(norm1*norm2) <=1 && dot_product/(norm1*norm2)>= -1);
   angle *= (double)180; angle  = angle/M_PI;
   return angle;
 }
void crossP (const Vector_3< double > & v1, const Vector_3< double > & v2, Vector_3< double > & v3) inline
Compute the cross Product of two vectors.
Definition at line 70 of file geometry.h.
Referenced by tet_vol(), and unit_normal().
{
   v3[0]= (v1[1]*v2[2]-v2[1]*v1[2]); v3[1]= (v2[0]*v1[2]-v1[0]*v2[2]);
   v3[2]= (v1[0]*v2[1]-v2[0]*v1[1]);
 }
double dotP (const Vector_3< double > & v1, const Vector_3< double > & v2) inline
Compute the dot Product of two vectors.
Definition at line 64 of file geometry.h.
Referenced by angle(), tet_vol(), and unit_normal().
{
   return (v1[0]*v2[0] + v1[1]*v2[1] + v1[2]*v2[2]);
 }
double edge_length (const Vector_3< double > & v)
Compute the edge length of a vector.
Definition at line 89 of file geometry.C.
References sqrt().
Referenced by Geo_Metric_Base_2::compute_aspects(), Geo_Metric_Base_3::compute_aspects(), and tri_area().
{
   return sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2]);
 }
double f_angle (Vector_3< double > v1, Vector_3< double > v2)
Compute the angle between two faces.
Definition at line 72 of file geometry.C.
References angle().
Referenced by Geo_Metric_Base_3::compute_angles().
{
   return double(180) - angle(v1,v2);
 }
void min_max12 (double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8, double a9, double a10, double a11, double a12, double & min, double & max)
Find minimum and maximum of 12 numbers.
Definition at line 53 of file geometry.C.
References min_max6().
Referenced by Geo_Metric_Base_3::compute_angles().
{
   double min2, max2;
   min_max6(a1,a2,a3,a4,a5,a6,min,max); min_max6(a7,a8,a9,a10,a11,a12,min2,max2);
   min = (min < min2)? min : min2;      max = (max > max2)? max : max2;
 }
MOP_BEGIN_NAMESPACE void min_max3 (double a1, double a2, double a3, double & min, double & max)
Find minimum and maximum of 3 numbers.
Definition at line 36 of file geometry.C.
Referenced by Geo_Metric_Base_2::compute_angles(), min_max4(), and min_max6().
{
 min = ( a1 < a2 )? a1 : a2;    max = ( a1 > a2 )? a1 : a2;
 min = ( min < a3 ) ? min : a3; max = ( max > a3 ) ? max : a3;
 }
void min_max4 (double a1, double a2, double a3, double a4, double & min, double & max)
Find minimum and maximum of 4 numbers.
Definition at line 41 of file geometry.C.
References min_max3().
Referenced by Geo_Metric_Base_2::compute_angles().
{
   min_max3(a1,a2,a3,min,max);
   min = (min < a4)? min : a4; max = (max > a4)? max : a4;
 }
void min_max6 (double a1, double a2, double a3, double a4, double a5, double a6, double & min, double & max)
Find minimum and maximum of 6 numbers.
Definition at line 46 of file geometry.C.
References min_max3().
Referenced by Geo_Metric_Base_3::compute_angles(), and min_max12().
{
   double min2, max2;
   min_max3(a1,a2,a3,min,max);     min_max3(a4,a5,a6,min2,max2);
   min = (min < min2)? min : min2; max = (max > max2)? max : max2;
 }
void printv (const Vector_3< double > & v)
Print a vector.
Definition at line 76 of file geometry.C.
{
   cout << v[0] <<"  " << v[1] << "  " << v[2] << endl;
 }
double tet_vol (const Vector_3< double > & a, const Vector_3< double > & b, const Vector_3< double > & c)
Compute the volume of a tetrahedron given three edges from a point as vectors.
Definition at line 103 of file geometry.C.
References NTS::abs(), crossP(), and dotP().
Referenced by Geo_Metric_Base_3::compute_aspects().
{
   Vector_3<double> temp;
   crossP(b,c,temp);
   return  (1/(double)6) * abs (dotP(a,temp)  ) ;
 }
double tri_area (const Vector_3< double > & v1, const Vector_3< double > & v2, const Vector_3< double > & v3)
Compute the area of a triangle defined by its three sides as vectors.
Definition at line 93 of file geometry.C.
References edge_length(), s, and sqrt().
Referenced by Geo_Metric_Base_3::compute_aspects().
{
   double a = edge_length(v1);
   double b = edge_length(v2);
   double c = edge_length(v3);
   double s = .5 * (a+b+c);
   return sqrt( s * (s-a) * (s-b) * (s-c) );
 }
void unit_normal (const Vector_3< double > & v1, const Vector_3< double > & v2, Vector_3< double > & v3)
Compute the unit vector normal to two input vectors.
Definition at line 80 of file geometry.C.
References crossP(), dotP(), and sqrt().
Referenced by Geo_Metric_Base_3::compute_angles().
{
   crossP(v1,v2,v3);
   double normalizer = sqrt( dotP (v3,v3) );
   if (normalizer == 0) return;
   v3[0] = v3[0]/normalizer; v3[1] = v3[1]/normalizer; v3[2] = v3[2]/normalizer;
 }