Rocstar: Public Interface for Overlay
Public Interface for Overlay
Functions
bool is_same_node (Vertex *v1, Vertex *v2)
Check whether given two vertices correspond to the same physical point.
void create_overlay_data ()
void delete_overlay_data ()
void determine_counterparts ()
void unmark_alledges ()
const Halfedge * get_an_unmarked_halfedge () const
Halfedge * get_an_unmarked_halfedge ()
Detailed Description
Function Documentation
void create_overlay_data ()
Definition at line 532 of file RFC_Window_overlay.C.
References RFC_Window_base::_pane_set, and RFC_Pane_overlay::create_overlay_data().
Referenced by Overlay::overlay().
{
   // Loop through panes
   Pane_set::iterator pit=_pane_set.begin(), piend=_pane_set.end();
   for ( ; pit != piend; ++pit) {
     RFC_Pane_overlay &p = (RFC_Pane_overlay &)*pit->second;
     p.create_overlay_data();
   }
 }
void delete_overlay_data ()
Definition at line 542 of file RFC_Window_overlay.C.
References RFC_Window_base::_pane_set, RFC_Pane_overlay::delete_overlay_data(), RFC_Pane_base::is_master(), and RFC_Window_derived< RFC_Pane_overlay >::pane().
Referenced by Overlay::overlay().
{
   // Loop through the panes to remove the buffer spaces
   Pane_set::iterator pit, piend;
   for (pit=_pane_set.begin(), piend=_pane_set.end(); pit != piend; ++pit) {
     RFC_Pane_overlay &pane = (RFC_Pane_overlay &)*pit->second;
     if ( !pane.is_master()) continue;
     pane.delete_overlay_data();
   }
 }
void determine_counterparts ()
Definition at line 482 of file RFC_Window_overlay.C.
References RFC_Window_base::_pane_set, and iend.
Referenced by RFC_Window_overlay::RFC_Window_overlay().
{
   // Construct a mapping from vertex pair to border edges
   Pane_set::iterator it=_pane_set.begin(), iend=_pane_set.end();
   for (; it != iend; ++it)
     ((RFC_Pane_overlay*)it->second)->construct_bvpair2edge();
   // Construct mapping from panal border edges to their counterpart.
   for ( it = _pane_set.begin(); it != iend; ++it)
     ((RFC_Pane_overlay*)it->second)->determine_counterparts();
   // Clear the mapping
   for ( it = _pane_set.begin(); it != iend; ++it)
     ((RFC_Pane_overlay*)it->second)->_bv2edges.clear();
 }
const RFC_Window_overlay::Halfedge * get_an_unmarked_halfedge () const
Definition at line 93 of file RFC_Window_overlay.C.
References RFC_Pane_overlay::_hds, RFC_Window_base::_pane_set, RFC_Pane_overlay::is_on_feature(), RFC_Pane_overlay::marked(), and RFC_Window_derived< RFC_Pane_overlay >::pane().
Referenced by RFC_Window_overlay::get_an_unmarked_halfedge(), and Overlay::overlay_init().
{
   const Halfedge *hbrd=NULL;
   for ( Pane_set::const_iterator pit=_pane_set.begin();
         pit != _pane_set.end(); ++pit) {
     const RFC_Pane_overlay &pane =
       reinterpret_cast<const RFC_Pane_overlay &>(*pit->second);
     RFC_Pane_overlay::HDS::Halfedge_const_iterator
       hit=pane._hds.halfedges_begin(), hend=pane._hds.border_halfedges_begin();
     for ( ; hit != hend; ++hit) if (!pane.marked( &*hit)) {
       if ( hbrd==NULL && pane.is_on_feature(hit->origin()))
         hbrd = &*hit;
       else if ( !pane.is_on_feature(hit->origin()))
         return &*hit;
     }
   }
   return hbrd;
 }
RFC_Window_overlay::Halfedge * get_an_unmarked_halfedge ()
Definition at line 114 of file RFC_Window_overlay.C.
References RFC_Window_overlay::get_an_unmarked_halfedge().
{
   return const_cast<Halfedge*>( ((const Self*)this)->
                                 get_an_unmarked_halfedge());
 }
bool is_same_node (Vertex * v1, Vertex * v2)
Check whether given two vertices correspond to the same physical point.
Definition at line 121 of file RFC_Window_overlay.C.
References RFC_Pane_overlay::get_primary(), Vertex_overlay::halfedge(), Halfedge_overlay::is_border(), and Vertex_overlay::pane().
{
   if ( v1==v2) return true;
   if ( !v1->halfedge()->is_border() || !v2->halfedge()->is_border())
     return false;
   return v1->pane()->get_primary( v1) == v2->pane()->get_primary( v2);
 }
void unmark_alledges ()
Definition at line 498 of file RFC_Window_overlay.C.
References RFC_Pane_overlay::_e_marks, RFC_Window_base::_pane_set, and iend.
Referenced by Overlay::intersect_blue_with_green().
{
   Pane_set::iterator it=_pane_set.begin(), iend=_pane_set.end();
   for ( ; it != iend; ++it) {
     RFC_Pane_overlay &p = (RFC_Pane_overlay &)*it->second;
     fill( p._e_marks.begin(), p._e_marks.end(), 0);
   }
 }