Rocstar: Feature-Detection Helpers
Feature-Detection Helpers
Functions
void set_feature_0 (Vertex *v) const
void set_on_feature (Vertex *v) const
bool is_feature_0 (const Vertex *v) const
bool is_on_feature (const Vertex *v) const
bool is_feature_1 (const Halfedge *h) const
void unset_strong_edge (Halfedge *h) const
Detailed Description
Function Documentation
bool is_feature_0 (const Vertex * v) const inline private
Definition at line 452 of file RFC_Window_overlay.h.
References RFC_Pane_overlay::is_feature_0(), and Vertex_overlay::pane().
Referenced by RFC_Window_overlay::evaluate_normals().
   { return v->pane()->is_feature_0(v); }
bool is_feature_1 (const Halfedge * h) const inline private
Definition at line 456 of file RFC_Window_overlay.h.
References RFC_Pane_overlay::is_feature_1(), Vertex_overlay::pane(), and Halfedge_overlay::vertex().
Referenced by RFC_Window_overlay::evaluate_normals().
   { return h->vertex()->pane()->is_feature_1(h); }
bool is_on_feature (const Vertex * v) const inline private
Definition at line 454 of file RFC_Window_overlay.h.
References RFC_Pane_overlay::is_on_feature(), and Vertex_overlay::pane().
   { return v->pane()->is_on_feature(v); }
void set_feature_0 (Vertex * v) const inline private
Definition at line 447 of file RFC_Window_overlay.h.
References Vertex_overlay::pane(), and RFC_Pane_overlay::set_feature_0().
   { v->pane()->set_feature_0( v); }
void set_on_feature (Vertex * v) const inline private
Definition at line 449 of file RFC_Window_overlay.h.
References Vertex_overlay::pane(), and RFC_Pane_overlay::set_on_feature().
   { v->pane()->set_on_feature( v); }
void unset_strong_edge (Halfedge * h) const inline private
Definition at line 458 of file RFC_Window_overlay.h.
References Vertex_overlay::pane(), RFC_Pane_overlay::unset_strong_edge(), and Halfedge_overlay::vertex().
   { h->vertex()->pane()->unset_strong_edge(h); }