Rocstar: Manipulation of Strong Vertices
Manipulation of Strong Vertices
Functions
void identify_features_0 ()
Identify the 0-features.
Feature_list_0::iterator remove_feature_0 (Feature_list_0::iterator i)
Remove the given 0-feature from the list.
Detailed Description
Function Documentation
void identify_features_0 () protected
Identify the 0-features.
Definition at line 555 of file RFC_Window_overlay_fea.C.
References NTS::abs(), acc, HDS_accessor< _MP >::get_destination(), HDS_accessor< _MP >::get_origin(), HDS_accessor< _MP >::get_pane(), i, RFC_assertion, RFC_assertion_code, RFC_Pane_overlay::set_feature_0(), RFC_Pane_overlay::unset_feature_0(), and v.
{
   Feature_list_1                 new_flist;
   _f_list_1.swap( new_flist);
   Feature_list_1::iterator flit;
   // Split feature curves at known feature vertices
   for ( flit=new_flist.begin(); flit!=new_flist.end(); ++flit) {
     Feature_list_1 subf;
     Feature_1::iterator fit=flit->begin(),fprev=fit;
     for ( ++fit; fit!=flit->end(); ++fit) {
       if ( is_feature_0( acc.get_origin( *fit))) {
         subf.push_back( Feature_1( fprev,fit));
         fprev=fit;
       }
     }
     if ( is_feature_0( acc.get_origin( *flit->begin())) || subf.empty()) {
       subf.push_back( Feature_1( fprev,fit));
     }
     else {
       Feature_1 &newf=subf.front();
       newf.insert( newf.begin(), fprev, flit->end());
     }
     // Assign the ranks and mark the ones with rank 2.
     for (Feature_list_1::iterator sit=subf.begin(); sit!=subf.end(); ++sit) {
       _f_list_1.push_back( *sit);
     }
   }
   // Determine the ranks of the vertices
   RFC_assertion( _f0_ranks.empty());
   for ( flit=_f_list_1.begin(); flit!=_f_list_1.end(); ++flit) {
     Vertex *src = acc.get_origin(flit->front());
     Vertex *dst = acc.get_destination(flit->back());
     map<Vertex*,int>::iterator i=_f0_ranks.find(src);
     if ( i==_f0_ranks.end())
       _f0_ranks.insert(make_pair(src,-1-(src==dst)));
     else
       i->second = abs(i->second)+1+(src==dst);
     if ( src!=dst) {
       if ( (i=_f0_ranks.find(dst))==_f0_ranks.end())
         _f0_ranks.insert(make_pair(dst,-1));
       else
         i->second = abs(i->second)+1;
     }
   }
   // Determine the connectivity at rank-2 vertices.
   std::map<Vertex*,std::vector<Feature_1*> >   turn_maps;
   for ( flit=_f_list_1.begin(); flit!=_f_list_1.end(); ++flit) {
     // Assign the ranks and mark the ones with rank 2.
     Vertex *src = acc.get_origin(flit->front());
     map<Vertex*,int>::iterator i=_f0_ranks.find(src);
     if ( i!=_f0_ranks.end() && abs(i->second)==2)
       turn_maps[ src].push_back( &*flit);
     Vertex *dst = acc.get_destination(flit->back());
     i=_f0_ranks.find(dst);
     if ( i!=_f0_ranks.end() && abs(i->second)==2)
       turn_maps[ dst].push_back( &*flit);
   }
   if ( !turn_maps.empty()) {
     std::map<Vertex*,std::vector<Feature_1*> >::iterator i;
     RFC_assertion_code(for ( i=turn_maps.begin(); i!=turn_maps.end(); ++i)
                        RFC_assertion( i->second.size()==2));
     new_flist.clear();
     // Merge at weak rank-2 vertices
     for ( flit=_f_list_1.begin(); flit!=_f_list_1.end(); ++flit) {
       if ( flit->empty()) continue;
       Feature_1 &f1 = *flit;
       bool  modified=false;
       Vertex *src = acc.get_origin(f1.front());
       Vertex *dst = acc.get_destination(f1.back());
       if ( src==dst) {
         if ( (i=turn_maps.find( src)) != turn_maps.end()) {
           turn_maps.erase( i);
           if ( !is_strong_ad( src)) {
             acc.get_pane( src)->unset_feature_0(src);
             _f0_ranks.erase( _f0_ranks.find(src));
           }
           else {
             acc.get_pane( src)->set_feature_0(src);
             _f0_ranks[src]=2;
           }
         }
       }
       else for ( int c=0; c<2; ++c) {
         for (;;) {
           Vertex *v=(c?acc.get_destination(f1.back()):
                      acc.get_origin(f1.front()));
           if ( (i=turn_maps.find( v))==turn_maps.end()) break;
           Feature_1 *f2;
           if ( (f2 = i->second[0]) == &f1) f2 = i->second[1];
           turn_maps.erase( i);
           if ( is_feature_0(v)) {
             acc.get_pane( v)->unset_feature_0(v);
             _f0_ranks.erase( _f0_ranks.find(v));
           }
           if ( f2 == &f1) break;
           merge_features_1( v, f1, *f2);
           Vertex *u;
           if ( (u=acc.get_destination(f1.back())) != v &&
                (i=turn_maps.find(u)) != turn_maps.end()) {
             if ( i->second[0] == f2) i->second[0] = &f1;
             if ( i->second[1] == f2) i->second[1] = &f1;
           }
           else if ((u=acc.get_origin(f1.front())) != v &&
                    (i=turn_maps.find(u)) != turn_maps.end()) {
             if ( i->second[0] == f2) i->second[0] = &f1;
             if ( i->second[1] == f2) i->second[1] = &f1;
           }
           modified = true;
         }
       }
       // Split at strong rank-2 vertices.
       if ( modified) {
         Feature_list_1 subf;
         int dropped=0;
         subdiv_feature_curve( f1, subf, dropped);
         RFC_assertion( dropped==0);
         f1.clear();
         for (Feature_list_1::iterator it=subf.begin(); it!=subf.end(); ++it) {
           new_flist.push_back( Feature_1());
           Vertex *v=acc.get_origin(it->front());
           if ( is_feature_0(v) && _f0_ranks.find(v)==_f0_ranks.end())
             _f0_ranks[ v] = 2;
           new_flist.back().swap( *it);
         }
       }
       else {
         new_flist.push_back( Feature_1());
         new_flist.back().swap( f1);
       }
     }
     _f_list_1.swap( new_flist);
   }
   RFC_assertion( turn_maps.empty());
   // Fill 0-feature list
   for ( map<Vertex*,int>::iterator it=_f0_ranks.begin();
         it!=_f0_ranks.end(); ++it) {
     // Adjust the rank for termini
     if ( it->second == -1 && is_strong_ad( it->first)) it->second = 1;
     RFC_assertion( is_feature_0( it->first));
     _f_list_0.push_back( Feature_0( it->first));
   }
   _f_list_0.sort();
 }
RFC_Window_overlay::Feature_list_0::iterator remove_feature_0 (Feature_list_0::iterator i)
Remove the given 0-feature from the list.
Definition at line 715 of file RFC_Window_overlay_fea.C.
References acc, HDS_accessor< _MP >::get_pane(), RFC_Pane_overlay::unset_feature_0(), and v.
Referenced by Overlay::match_features_0().
{
   Vertex *v = i->vertex();
   acc.get_pane(v)->unset_feature_0(v);
   return _f_list_0.erase(i);
 }