Rocstar: Handle.h File Reference
Handle.h File Reference
#include <CGAL/Handle_for.h>
Classes
class Leda_like_rep
class Leda_like_handle
Typedefs
typedef Leda_like_rep Rep
Functions
unsigned long id (const Leda_like_handle &x)
template<class T >
bool identical (const T &t1, const T &t2)
Variables
CGAL_END_NAMESPACE
CGAL_BEGIN_NAMESPACE typedef
Leda_like_handle Handle
Typedef Documentation
typedef Leda_like_rep Rep
Definition at line 138 of file Handle.h.
Function Documentation
unsigned long id (const Leda_like_handle & x) inline
Definition at line 107 of file Handle.h.
References Leda_like_handle::PTR.
Referenced by Rocout::add_attribute(), add_ghost_nodes2D(), addpres(), arruda_boyce_cauchy(), artificialdamping(), bc_enforce(), buildfilenamebasic(), buildfilenamesteady(), buildfilenameunsteady(), cauchystressprinc(), Window::delete_attribute(), Pane::delete_attribute(), ProfilerObj::FunctionEntry(), identical(), Pane::insert(), neoinccauchystress(), operator>>(), Rocout::put_attribute(), read_io_files(), read_patran(), ProfilerObj::ReadSummaryFiles(), rflo_dualtstinit(), rflo_dualtstpredict(), rflo_dualtstshift(), rflo_dualtststerm(), HDF4::SDfileinfo(), HDF4::SDfindattr(), modstatsroutines::statdataaccumulation1(), TRAIL_WriteWindow(), Rocout::write_attribute(), write_output_2(), and writegeneric().
 { return (unsigned long)x.PTR; }
bool identical (const T & t1, const T & t2) inline
Definition at line 113 of file Handle.h.
References id().
 { return id(t1) == id(t2); }
Variable Documentation
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE typedef Leda_like_handle Handle
Definition at line 137 of file Handle.h.