Rocstar: hdf2pltV2.C File Reference
hdf2pltV2.C File Reference
This utility converts a set of HDF files to a single multi-zone TECPLOT file to visualize within tecplot.
#include <string>
#include <iostream>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <cstring>
#include <cstdlib>
#include <cassert>
#include <vector>
#include <map>
#include <utility>
#include <algorithm>
#include "TAIL.H"
#include "PrimitiveTypes.H"
#include "roccom.h"
#include "PaneConnectivity.hpp"
#include "MeshPointIdToGlobalIdMap.hpp"
Enumerations
enum DataItemType { NODEDATA, CELLDATA }
The data item type.
Functions
COM_EXTERN_MODULE (Rocin)
COM_EXTERN_MODULE (Rocmap)
void showUsage ()
Displays usage information to Standard-out about the different switches and command line arguments that can be used with this program.
void parseArguments (int argc, char **argv)
Parses the command line arguments.
std::string getWindow ()
Loads the set of HDF files into a single window.
void writePlotFile ()
Generates a single zone plot file from the stitched mesh.
void printWindow (const std::string &windowName)
Prints the window with the given name.
std::string convertWindow (const std::string &wname)
Converts the window from block-structured format to unstructured format.
void writeVtkFiles (std::vector< Mesh::UnstructuredMesh > &m)
Writes the set of meshes into separate VTK files that can be visualized with Paraview.
void getPaneConnnectivity (const std::string &wname)
This method calls Rocmap to query the pane connectivity information for the given window.
void maskPoints ()
This method is called from getPaneConnectivity() to mask the flag the mesh points that are shared on each grid.
void stitchGrids ()
This method will stitch the grids into a single, global grid.
void stitchSolutionData (MeshPointIdToGlobalIdMap *hash)
This method will stitch the partitioned solution for the single grid.
int addToGlobalNodeList (const double x, const double y, const double z, std::vector< double > &nodelist)
This method adds the vertex with the given x,y,z coordinates to the global node list and returns the assigned global id (index).
void updateHash (const int meshPaneId, const int pointId, const int globalId, MeshPointIdToGlobalIdMap *hash)
This method updates a MeshPointIdToGlobalIdMap hash with the mesh panes and point IDs mapping to the global ID.
void writeVtkData ()
Writes the merged grid and its data in VTK UNSTRUCTURED_GRID file format.
void printVtk (std::vector< double > &vlist, std::vector< std::vector< int > > &elist)
This method prints the global grid in VTK file format.
int main (int argc, char **argv)
Program main.
void stitchSolutionData (MeshPointIdToGlobalIdMap *hash, MeshPointIdToGlobalIdMap *ehash)
This method will stitch the partitioned solution for the single grid.
void getPaneConnectivity (const std::string &wName)
Computes the pane connectivity using Rocmap.
Variables
struct {
bool readControlFile
Data is read from the control file.
bool withGhost
Ghost nodes will be used.
bool blocks
Input data is block-structured grid.
bool vtk
Writes vtk files.
std::string cntrlfile
Control file string.
std::string fileregx
File regular expression.
std::string outputfile
Output file to write the file.
std::string prgmname
The program name.
int numberOfPanes
The number of panes, aka number of sub-domains.
std::vector< int > paneIds
Array of paneIds.
std::vector
< Mesh::UnstructuredMesh > meshes
The list of grids to write.
std::vector< std::vector< bool > > mask
Masks the points that are shared (true) share (false) not shared.
std::vector< SolnMetaData > smdv
The solution Metadata.
std::vector< std::vector
< std::vector< double > > > solution
The solution data.
std::vector< PaneConnectivity > pconns
Inter-zone (pane) connectivity information.
std::map< int, int > paneIds2index
Maps the pane ids to the index in the corresponding vectors.
std::vector< std::vector
< double > > globalSolution
Contains the global solution.
std::vector< bool > solutionignore
Masks the data to be ignored.
std::vector< double > globalNodeList
The global node list.
std::vector< std::vector< int > > globalElementList
The global element list.
} Program
Detailed Description
This utility converts a set of HDF files to a single multi-zone TECPLOT file to visualize within tecplot.
Note
Based on the initial hdf2plt base-code.
Date
Aug 3, 2009
Author
George Zagaris (gzaga.nosp@m.ris@.nosp@m.illin.nosp@m.ois..nosp@m.edu)
Definition in file hdf2pltV2.C.
Enumeration Type Documentation
enum DataItemType
The data item type.
Enumerator
NODEDATA
CELLDATA
Definition at line 40 of file hdf2pltV2.C.
 { NODEDATA, CELLDATA };
Function Documentation
int addToGlobalNodeList (const double x, const double y, const double z, std::vector< double > & nodelist)
This method adds the vertex with the given x,y,z coordinates to the global node list and returns the assigned global id (index).
Parameters
x the x–coordinate of the vector being added.
y the y–coordinate of the vector being added.
z the z–coordinate of the vector being added.
nodelist the global node list where the new node will be inserted.
Returns
GlobalID the global id of the vertex added.
Postcondition
nodelist.size() is incremented by 3.
GlobalID >= 0.
Definition at line 951 of file hdf2pltV2.C.
Referenced by stitchGrids().
 {
         nodelist.push_back( x );
         nodelist.push_back( y );
         nodelist.push_back( z );
         return( (nodelist.size( )/3)-1 );
 }
COM_EXTERN_MODULE (Rocin)
COM_EXTERN_MODULE (Rocmap)
std::string convertWindow (const std::string & wName)
Converts the window from block-structured format to unstructured format.
Utilizes Roctail to convert the panes to an unstructured grid format.
This function is called iff -block-structured is supplied to the command line.
Parameters
wname the name of the window.
Returns
newWindowName the name of the window that contains the grids in an unstructured format.
Parameters
wName the window name.
Returns
S new window name which holds the unstructured mesh data.
Definition at line 1422 of file hdf2pltV2.C.
References COM_new_window(), COM_window_init_done(), i, and Program.
Referenced by printWindow().
 {
         std::cout << "\n\n\n";
         std::cout << "Converting window to Unstructured mesh...";
         std::cout.flush( );
         TAIL_Window2UnstructuredMesh( wName, Program.meshes, Program.smdv, Program.solution, 0, true );
         std::cout << "[DONE]\n";
 //      for( int i=0; i < Program.solution.size( ); ++i )
 //      {
 //              std::cout << "I: " << i << std::endl;
 //              for( int j=0; j < Program.solution[ i ].size( ); ++j )
 //              {
 //                      std::cout << "\tJ: " << j << " Name: " << Program.smdv[ j ].name << " Location: " << Program.smdv[ j ].loc;
 //                      std::cout << " Number of components: " << Program.smdv[ j ].ncomp << std::endl;
 //                      for( int k=0; k < Program.solution[ i ][ j ].size( ); ++k )
 //                      {
 //                              std::cout << "\t\t k[" << k << "]:" << Program.solution[ i ][ j ][ k ] << std::endl;
 //                      }
 //              }
 //      }
 //      assert( false );
         #ifdef ASSERT_ON
                 assert( Program.meshes.size( ) == Program.numberOfPanes );
         #endif
   std::string newWindow( "unstructured" );
   COM_new_window( newWindow.c_str( ) );
         for( int i=0; i < Program.meshes.size( ); ++i )
         {
                 TAIL_UnstructuredMesh2Pane( newWindow, Program.paneIds[ i ],
                          Program.meshes[ i ], Program.smdv[ i ], Program.solution[ i ], 0 );
         }
   COM_window_init_done( newWindow.c_str( ) );
 //      #ifdef ASSERT_ON
 //              assert( Program.solution.size( ) == Program.numberOfPanes );
 //              for( int i=0; i < Program.solution.size( ); ++i )
 //              {
 //                      assert( Program.solution[ i ].size( ) == Program.smdv.size( ) );
 //                      for( int j=0; j < Program.solution[ i ].size( ); ++j )
 //                      {
 //                              assert( Program.solution[ i ][ j ].size( ) > 0 );
 //                      }
 //              }
 //      #endif
         return newWindow;
 }
void getPaneConnectivity (const std::string & wName)
Computes the pane connectivity using Rocmap.
Note
Based on Rocmap's User/Developer guid.
Parameters
wname the window name.
Definition at line 1302 of file hdf2pltV2.C.
References COM_call_function(), COM_get_array(), COM_get_attribute_handle(), COM_get_function_handle(), COM_get_size(), i, maskPoints(), and Program.
Referenced by printWindow().
 {
         Program.pconns.resize( Program.numberOfPanes );
         std::cout << "Getting the pane connectivity...";
         int MAP_compute_pconn = COM_get_function_handle( "MAP.compute_pconn" );
         int mesh_hndl                     = COM_get_attribute_handle( ( wName + ".mesh" ).c_str( ) );
         int pconn_hndl                          = COM_get_attribute_handle( ( wName + ".pconn" ).c_str( ) );
         COM_call_function( MAP_compute_pconn, &mesh_hndl, &pconn_hndl );
         for( int i=0; i < Program.numberOfPanes; ++i )
         {
                 /* Get the pconn array */
                 int *pconn = NULL;
                 COM_get_array( ( wName + ".pconn" ).c_str( ),   /* Window Name (in) */
                                                                                 Program.paneIds[ i ],                                   /* Pane Id (in) */
                                                                                 &pconn  );                                                                              /* pconn array (in/out) */
                 #ifdef ASSERT_ON
                         assert( pconn != NULL );
                 #endif
                 int size = -1;
                 int gs   = -1;
                 COM_get_size( ( wName + ".pconn" ).c_str( ),    /* Window Name (in) */
                                                                          Program.paneIds[ i ],                                  /* Pane Id (in) */
                                                                          &size,                                                                                                 /* Size of the pconn array (in/out) */
                                                                          &gs );                                                                                                 /* ghost node size  (in/out) */
                 #ifdef ASSERT_ON
                         assert( size >= 0 );
                         assert( gs == 0 );
                 #endif
                 Program.pconns[ i ].constructPaneConnectivityFromArray( pconn, size );
                 delete [] pconn;
                 pconn = NULL;
         }
         std::cout << "[DONE]\n";
         maskPoints( );
 }
void getPaneConnnectivity (const std::string & wname)
This method calls Rocmap to query the pane connectivity information for the given window.
A PaneConnectivity object is constructed for each mesh and the shared nodes are flaged for each mesh.
Parameters
wname the window name.
See also
Rocstar::Rocin::Utilities::PaneConnectivity.hpp
std::string getWindow ()
Loads the set of HDF files into a single window.
Returns a window consisting of the HDF input files.
Each sub-domain, or block, or zone is stored on a separate pane of the window. Moreover, the data layout is changed to contiguous from the default stacked layout of HDF files.
Returns
WindowName the name of the window.
s the window name.
Note
The window layout is changed to contiguous and the number of panes and paneIds is obtained.
Definition at line 1540 of file hdf2pltV2.C.
References COM_call_function(), COM_clone_attribute(), COM_delete_attribute(), COM_delete_window(), COM_get_function_handle(), COM_get_panes(), COM_new_window(), COM_window_init_done(), i, and Program.
Referenced by main().
 {
         std::string win_in;
         if( Program.readControlFile )
           win_in = Program.cntrlfile;
         else
           win_in = Program.fileregx;
         std::string::size_type st = win_in.find_last_of('/');
         if (st != std::string::npos)
                 win_in.erase(0, st+1);
         st = win_in.find_first_not_of("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ");
         if (st != std::string::npos)
                 win_in.erase(st);
   // Initialize an empty time string
   int  len = 15;
   char timeStr[16];
   timeStr[0] = '\0';
   if( Program.readControlFile )
   {
                 std::cout << "Reading by control file " << Program.cntrlfile << " into window " << win_in << "...";
                 int IN_read = COM_get_function_handle( "IN.read_by_control_file" );
                 COM_call_function( IN_read,Program.cntrlfile.c_str( ),
                                                                                                 win_in.c_str(),NULL,timeStr,&len        );
                 std::cout << "[DONE]\n";
         }
         else
         {
                 std::cout << "Reading HDF file(s) " << Program.fileregx << " into window " << win_in << "...";
                 int IN_read = COM_get_function_handle( "IN.read_window");
                 COM_call_function( IN_read,Program.fileregx.c_str( ),
                                                                                                 win_in.c_str(),NULL,NULL,timeStr,&len   );
                 std::cout << "[DONE]\n";
         }
   // Change the memory layout to contiguous
   // Taken from from Roctail::TAIL_HDF2Window
   std::string win_out( "win_out" );
   COM_new_window( win_out.c_str( ) );
         COM_clone_attribute( (win_out+".all").c_str(), (win_in+".all").c_str(), 1 );
         COM_window_init_done( win_out.c_str( ) );
         // Delete the old memory layout.
         COM_delete_attribute(( win_in+".atts").c_str( ) );
         COM_delete_window( win_in.c_str( ) );
         // Get the number of panes and the corresponding paneIds
         int *paneids = NULL;
         COM_get_panes( win_out.c_str(), &(Program.numberOfPanes), &paneids );
         Program.paneIds.resize( Program.numberOfPanes );
         // Compute the paneId2index mapping
         for( int i=0; i < Program.numberOfPanes; ++i )
         {
                 Program.paneIds[ i ] = paneids[ i ];
                 #ifdef ASSERT_ON
                         assert( Program.paneIds2index.find( Program.paneIds[ i ] ) ==
                                                         Program.paneIds2index.end( ) );
                 #endif
                 Program.paneIds2index[ Program.paneIds[ i ] ] = i;
         }
         delete [] paneids; paneids = NULL;
         #ifdef ASSERT_ON
                 assert( Program.paneIds2index.size( ) == Program.numberOfPanes );
         #endif
         return win_out;
 }
int main (int argc, char ** argv)
Program main.
Parameters
argc the argument counter.
argv the argument vector.
Returns
0 if success, else, false.
Definition at line 412 of file hdf2pltV2.C.
References COM_finalize(), COM_init(), getWindow(), parseArguments(), printWindow(), and Program.
 {
         /* Parse the user-supplied command line */
         parseArguments( argc, argv );
         /* Print program information to STDOUT */
         Program.printInfo( );
         /* Initialize Roccom Environment */
         COM_init( &argc, &argv );
         /* Load all required modules */
         Program.loadModules( );
   /* Get window */
         std::string windowname = getWindow( );
         std::cout << "Read window: " << windowname << std::endl;
         std::cout << "Number of panes: " << Program.numberOfPanes << std::endl;
         /* Print window */
         printWindow( windowname );
         /* Unload modules */
         Program.unloadModules( );
         /* Finalize the COM Environment */
         COM_finalize( );
         return 0;
 }
void maskPoints ()
This method is called from getPaneConnectivity() to mask the flag the mesh points that are shared on each grid.
Masks the points that are shared based on the pane connectivity.
Precondition
Program.mask.size() == 0.
Program.numberOfPanes >= 1.
Program.pconns.size() == Program.numberOfPanes.
Program.paneIds.size() == Program.numberOfPanes.
Postcondition
Program.mask.size() == Program.numberOfPanes.
Program.mask[ i ] is created for each mesh, m_i, 0 <= i <= Program.numberOfPanes.
Program.mask is created for each mesh.
Precondition
Program.paneIds
Program.mask.size() == 0.
Program.numberOfPanes >= 1.
Program.pconnSizes[ i ] >= 0, 0 <= i < Program.numberOfPanes.
Program.pconns[ i ] != NULL, 0 <= i < Program.numberOfPanes.
Definition at line 1234 of file hdf2pltV2.C.
References PaneConnectivity::getNodesSharedWithRemotePane(), PaneConnectivity::getNumberOfNodesSharedWithRemotePane(), PaneConnectivity::getRemotePaneIds(), i, and Program.
Referenced by getPaneConnectivity().
 {
         #ifdef ASSERT_ON
                 assert( Program.mask.size( ) == 0 );
                 assert( Program.numberOfPanes >= 1 );
                 assert( Program.pconns.size( ) == Program.numberOfPanes );
                 assert( Program.paneIds.size( ) == Program.numberOfPanes );
         #endif
         Program.mask.resize( Program.numberOfPanes );
         for( int pane=0; pane < Program.numberOfPanes; ++pane )
         {
                 /* Initially no nodes are shared so the entire mask is set to false */
                 Program.mask[ pane ].resize( Program.meshes[ pane ].nc.Size( ),false );
                 /* Get pointer to the pane connectivity object corresponding to this pane */
                 PaneConnectivity *pconPtr = &( Program.pconns[ pane ] );
                 #ifdef ASSERT_ON
                         assert( pconPtr != NULL );
                 #endif
                 /* Get the remote pane ids connecting to this pane */
                 std::vector< int > remotePaneIds;
                 pconPtr ->getRemotePaneIds( remotePaneIds );
                 #ifdef ASSERT_ON
                         assert( pconPtr ->getNumberOfConnections( ) == remotePaneIds.size( ) );
                 #endif
           /* For all remote panes, get the local shared nodes that are shared with each remote pane */
                 for( int rmtPane=0; rmtPane < remotePaneIds.size( ); ++rmtPane )
                 {
 //                      std::cout << "Pane: [" << Program.paneIds[ pane ] << "] shares ";
 //                      std::cout << pconPtr ->getNumberOfNodesSharedWithRemotePane( remotePaneIds[ rmtPane ] );
 //                      std::cout << " Remote pane: [" << remotePaneIds[ rmtPane ] << "]\n";
                         int id = remotePaneIds[ rmtPane ];
                         std::vector< int > nodeList = pconPtr ->getNodesSharedWithRemotePane( id );
                         #ifdef ASSERT_ON
                                 assert( nodeList.size( ) == pconPtr ->getNumberOfNodesSharedWithRemotePane( id ) );
                         #endif
                         for( int i=0; i < nodeList.size( ); ++i )
{
                                 int nodeId = nodeList[ i ];
                                 #ifdef ASSERT_ON
                                         assert( nodeId >= 0 && nodeId < Program.mask[ pane ].size( ) );
                                 #endif
                                 Program.mask[ pane ][ nodeId ] = true;
                         } /* For all shared nodes in the node list */
                 } /* End For all remote panes */
         } /* End For all panes, i.e., zones or sub-domains */
 }
void parseArguments (int argc, char ** argv)
Parses the command line arguments.
Parses the user-supplied command line arguments.
Parameters
argc the argument counter.
argv the argument vector.
Precondition
argc >= 1.
argv != NULL.
Parameters
argc the argument counter
argv the argument vector
Definition at line 1622 of file hdf2pltV2.C.
References i, Program, and showUsage().
Referenced by main().
 {
         Program.prgmname                                = std::string( argv[ 0 ] );
         Program.withGhost                 = false;
         Program.readControlFile = false;
         Program.blocks                                  = false;
         Program.vtk                                                     = false;
         Program.numberOfPanes   = 0;
         Program.cntrlfile                       = "";
         Program.fileregx                                = "";
         for( int i=1; i < argc; ++i )
         {
                 if( std::strcmp( argv[ i ], "-g" ) == 0 )
                 {
                         Program.withGhost = true;
                 }
                 else if( std::strcmp( argv[ i ], "-c" ) == 0 )
                 {
                         Program.readControlFile = true;
                         Program.cntrlfile = std::string( argv[ ++i ] );
                 }
                 else if( std::strcmp( argv[ i ], "-o" ) == 0 )
                 {
                         Program.outputfile = std::string( argv[ ++i ] );
                 }
                 else if( std::strcmp( argv[ i ], "-regex") == 0 )
                 {
                         Program.fileregx = std::string( argv[ ++i ] );
                 }
                 else if( std::strcmp( argv[ i ], "-block-structured") == 0  )
                 {
                         Program.blocks = true;
                 }
                 else if( std::strcmp( argv[ i ], "-vtk" ) == 0 )
                 {
                         Program.vtk = true;
                 }
                 else if( std::strcmp( argv[ i ], "-h") == 0  )
                 {
                         showUsage( );
                         exit( 0 );
                 }
         }
         if( Program.cntrlfile == "" && Program.fileregx == "" )
         {
                 std::cerr << "Error parsing command line input!\n";
                 showUsage( );
                 exit( -1 );
         }
 }
void printVtk (std::vector< double > & vlist, std::vector< std::vector< int > > & elist)
This method prints the global grid in VTK file format.
Note
Mostly used for debugging.
Parameters
vlist the global vertex list.
elist the element list.
Definition at line 822 of file hdf2pltV2.C.
References i, and j.
Referenced by stitchGrids().
 {
          std::ofstream ofs;
          ofs.open( std::string( "global_mesh.vtk" ).c_str( ) );
          if( !ofs.is_open( ) )
                 {
                         std::cerr << "Cannot write global VTK file! " << std::endl;
                         std::cerr << "File: " << __FILE__                                               << std::endl;
                         std::cerr << "Line: " << __LINE__                                               << std::endl;
                         assert( false );
                 }
                 ofs << "# vtk DataFile Version 3.0\n";
                 ofs << "Global Mesh Output" << std::endl;
                 ofs << "ASCII\n";
                 ofs << "DATASET UNSTRUCTURED_GRID\n";
                 ofs << "POINTS " << vlist.size( )/3 << " double\n";
                 for( int i=0; i < vlist.size( )/3; ++i )
                 {
                         ofs << vlist[ i*3   ] << " ";
                         ofs << vlist[ i*3+1 ] << " ";
                         ofs << vlist[ i*3+2 ] << "\n";
                 }
                 int maxnodes = 0; /* the maximum number of nodes per element */
                 for( int i=0; i < elist.size( ); ++i )
                 {
                         if( maxnodes < elist[ i ].size( ) )
                                 maxnodes = elist[ i ].size( );
                 }
                 ofs << "CELLS " << elist.size( ) << " " << elist.size( )*( maxnodes+1) << "\n";
                 for( int i=0; i < elist.size( ); ++i  )
                 {
                         ofs <<  elist[ i ].size( ) << " ";
                         for( int j=0; j < elist[ i ].size( ); ++j )
                                 ofs <<  elist[ i ][ j ]<< " ";
                         ofs << std::endl;
                 }
                 ofs << "CELL_TYPES " << elist.size( ) << std::endl;
                 for( int i=0; i < elist.size( ); ++i )
                 {
                         if( elist[ i ].size( ) == 8 )
                                 ofs << "12\n";
                         else if( elist[ i ].size( ) == 4 )
                                 ofs << "10\n";
                         else {
                                 std::cerr << "Undefined element type!\n";
                                 std::cerr << "File: " << __FILE__ << std::endl;
                                 std::cerr << "Line: " << __LINE__ << std::endl;
                         }
                 }
                 ofs.close( );
 }
void printWindow (const std::string & wName)
Prints the window with the given name.
This function prints the panes/grids in the window a into a Tecplot file.
Parameters
windowName the name of the window.
wname The name of the window.
Definition at line 1483 of file hdf2pltV2.C.
References convertWindow(), getPaneConnectivity(), Program, stitchGrids(), writePlotFile(), writeVtkData(), and writeVtkFiles().
Referenced by main().
 {
         std::string window = wName;
         if( Program.blocks )
         {
                 std::cout << "Converting block-structured grids to unstructured...\n";
                 std::cout.flush( );
                 window = convertWindow( wName );
                 std::cout << "[DONE]\n";
                 std::cout.flush( );
         }
         else
         {
                 //TODO: Load the Unstructured meshes from the window to the data-structures.
                 std::cerr << "Unstructured grids are currently not supported!\n";
                 std::cerr << "If your data-set consists of block structured grids make sure the -block-structured argument is supplied at the command line.\n";
                 std::cerr << "File: " << __FILE__ << std::endl;
                 std::cerr << "Line: " << __LINE__ << std::endl;
                 std::cerr << "core dumping...\n";
                 assert( false );
         }
         /* Get the pane connectivity and mask the shared points. */
         getPaneConnectivity( window );
         #ifdef ASSERT_ON
                 if( Program.vtk )
                 {
                         std::cout << "Writting VTK files...";
                          writeVtkFiles( Program.meshes );
                         std::cout << "[DONE]\n";
                 }
         #endif
         // TODO: delete the window and panes, the data is now
         // stored in the separate data-structures, hence it is
         // no longer needed.
         stitchGrids( );
         if( Program.vtk )
                 writeVtkData( );
         writePlotFile( );
 }
void showUsage ()
Displays usage information to Standard-out about the different switches and command line arguments that can be used with this program.
Prints usage and examples to STDOUT.
Definition at line 1682 of file hdf2pltV2.C.
Referenced by parseArguments().
 {
         std::cout << "HDF2PLT OPTIONS:\n";
         std::cout << "-regex \"{somestring}*.hdf\" : Specifies a set of hdf files\n";
         std::cout << "-g : Enables ghost node inclusion in the output file\n";
         std::cout << "-c {cntrlfile} : Specifies a control file to use\n";
         std::cout << "-block-structured: Indicates the the input files are block-structured grids which must be converted to unstructured format\n";
         std::cout << "-o {outputfile} : Specifies output file name. Note, do not append a file extension. A file extension will be automatically appended.\n";
         std::cout << "-vtk : Enables printing of VTK files as well.\n";
         std::cout << "-h : Prints this help menu.\n";
         std::cout << "Examples:\n";
         std::cout << "\thdf2plt -g -regex \"fluid*.hdf\" -block-structured -o output\n";
         std::cout.flush( );
 }
void stitchGrids ()
This method will stitch the grids into a single, global grid.
Precondition
Program.meshes.size() == Program.numberOfPanes
Program.pconns.size() == Program.numberOfPanes
Postcondition
Program.globalMesh is constructed.
Definition at line 1131 of file hdf2pltV2.C.
References addToGlobalNodeList(), Mesh::UnstructuredMesh::con, Mesh::Connectivity::Esize(), i, MeshPointIdToGlobalIdMap::insert(), Mesh::UnstructuredMesh::nc, Mesh::Connectivity::Nelem(), Mesh::Connectivity::Node(), printVtk(), Program, Mesh::NodalCoordinates::Size(), stitchSolutionData(), updateHash(), Mesh::NodalCoordinates::y(), and Mesh::NodalCoordinates::z().
Referenced by printWindow().
 {
         std::cout << "Stitching grids...";
   std::cout.flush( );
         #ifdef ASSERT_ON
                 assert( Program.meshes.size( )  == Program.numberOfPanes );
                 assert( Program.pconns.size( )  == Program.numberOfPanes );
                 assert( Program.paneIds.size( ) == Program.numberOfPanes );
         #endif
         MeshPointIdToGlobalIdMap  hash; /* Node Hash */
         MeshPointIdToGlobalIdMap ehash; /* Element Hash */
         for( int i=0; i < Program.meshes.size( ); ++i )
         {
                 int meshPaneId                                                   = Program.paneIds[ i ];
                 Mesh::UnstructuredMesh *mesh = &( Program.meshes[ i ] );
                 #ifdef ASSERT_ON
                         assert( mesh != NULL );
                 #endif
                 int count = 0;
                 for( int node=0; node < mesh ->nc.Size( ); ++node )
                 {
                         if( ! Program.isNodeShared( i, node ) )
{
                                 /* insert the node */
                                 int globalId = addToGlobalNodeList(
                                                                                                         mesh ->nc.x( node+1 ), mesh ->nc.y( node+1 ), mesh ->nc.z( node+1 ),
                                                                                                         Program.globalNodeList );
                                 #ifdef ASSERT_ON
                                         assert( ! hash.exists( meshPaneId, node ) );
                                 #endif
                                 hash.insert( meshPaneId, node, globalId );
                         }
                         else if( !hash.exists( meshPaneId, node ) )
{
                                 /* insert the node */
                                 int globalId = addToGlobalNodeList(
                                                                                                         mesh ->nc.x( node+1 ), mesh ->nc.y( node+1 ), mesh ->nc.z( node+1 ),
                                                                                                         Program.globalNodeList );
                                 /* update the hash */
                                 updateHash( meshPaneId, node, globalId, &hash );
                         }
                 } /* End for all nodes */
                 for( int element=0; element < mesh ->con.Nelem( ); ++element )
                 {
                         int size = mesh ->con.Esize( element+1 );
                         std::vector< int > elt;
                         elt.resize( size );
                         for( int i=0; i < size; ++i )
{
                                 int localId  = mesh ->con.Node( element+1, i+1 )-1;
                                 #ifdef ASSERT_ON
                                   assert( hash.exists( meshPaneId, localId ) );
                                 #endif
                                 int globalId = hash.getGlobalId( meshPaneId, localId );
                                 elt[ i ]                = globalId;
                         }
                         Program.globalElementList.push_back( elt );
                         int globalElementId = Program.globalElementList.size( )-1;
                         ehash.insert( meshPaneId, element, globalElementId );
                 } /* End for all elements */
         } /* End for all meshes */
         std::cout << "[DONE]\n";
         std::cout << "Total number of nodes: "          << (Program.globalNodeList.size( )/3) << std::endl;
         std::cout << "Total number of elements: " << Program.globalElementList.size( )  << std::endl;
         #ifdef ASSERT_ON
                 printVtk( Program.globalNodeList, Program.globalElementList );
         #endif
         stitchSolutionData( &hash, &ehash );
 }
void stitchSolutionData (MeshPointIdToGlobalIdMap * hash)
This method will stitch the partitioned solution for the single grid.
Parameters
hash a hash of the local mesh points to the corresponding global Id.
Precondition
hash != NULL
Referenced by stitchGrids().
void stitchSolutionData (MeshPointIdToGlobalIdMap * hash, MeshPointIdToGlobalIdMap * ehash)
This method will stitch the partitioned solution for the single grid.
Parameters
hash a hash of the local mesh points to the corresponding global Id.
ehash a hash of the lobal element ids to the corresponding global element Id.
Precondition
hash != NULL && ehash != NULL.
hash ->size() > 0 && ehash ->size() > 0..
Program.globalNodeList.size() > 0.
Program.globalElementList.size() > 0.
Program.solution.size() == Program.numberOfPanes.
Definition at line 971 of file hdf2pltV2.C.
References CELLDATA, MeshPointIdToGlobalIdMap::getGlobalId(), i, NODEDATA, and Program.
 {
         Program.solutionignore.resize( Program.smdv.size( ), false );
         std::cout << "Stitching the solution...";
         std::cout.flush( );
         #ifdef ASSERT_ON
                 assert( hash != NULL && ehash != NULL );
                 assert( Program.globalNodeList.size( ) > 0 );
                 assert( Program.globalElementList.size( ) > 0 );
                 assert( hash ->size( ) > 0 && ehash ->size( ) > 0 );
                 assert( Program.solution.size( ) == Program.numberOfPanes );
         #endif
         /* Initialize the global solution vector */
         Program.globalSolution.resize( Program.smdv.size( ) );
         for( int i=0; i < Program.globalSolution.size( ); ++i )
         {
                 if( Program.getDataItemType( i ) == NODEDATA )
                         Program.globalSolution[ i ].resize( Program.globalNodeList.size( )*Program.smdv[ i ].ncomp,      0.0 );
                 else if( Program.getDataItemType( i ) == CELLDATA )
                         Program.globalSolution[ i ].resize( Program.globalElementList.size( )*Program.smdv[ i ].ncomp, 0.0 );
                 else {
                         std::cerr << "Code should not reach here!\n";
                         std::cerr << "File: " << __FILE__ << std::endl;
                         std::cerr << "Line: " << __LINE__ << std::endl;
                         assert( false );
                 }
         }
         for( int paneidx=0; paneidx < Program.numberOfPanes; ++paneidx )
         {
                 int paneId = Program.paneIds[ paneidx ];
                 #ifdef ASSERT_ON
                         assert( Program.solution[ paneidx ].size( ) == Program.smdv.size( ) );
                 #endif
                 for( int dataidx=0; dataidx < Program.solution[ paneidx].size( ); ++dataidx )
                 {
                         #ifdef ASSERT_ON
                                 assert( dataidx >= 0 && dataidx < Program.solution[paneidx].size( ) );
                         #endif
                         if( Program.getDataItemType( dataidx ) == NODEDATA )
{
                           if( Program.solution[ paneidx ][ dataidx ].size( ) == 0 )
{
                                 Program.solutionignore[ dataidx ] = true;
                                 Program.globalSolution[ dataidx ].resize( 0 );
                           }
                           else
{
                                 int N                    = Program.smdv[ dataidx ].ncomp;
                                 int NumNodes = Program.meshes[ paneidx ].nc.Size( );
                                 #ifdef ASSERT_ON
                                   assert( Program.meshes[ paneidx ].nc.Size( )*N == Program.solution[ paneidx ][ dataidx ].size( ) );
                                         #endif
                                 for( int localNodeId=0; localNodeId < NumNodes; ++localNodeId )
{
                                                 #ifdef ASSERT_ON
                                                         assert( hash ->exists( paneId, localNodeId ) );
                                                 #endif
                                                 int globalId = hash ->getGlobalId( paneId, localNodeId );
                                         for( int component=0; component < N; ++component )
{
                                                 int gidx = globalId*N+component;     /* The global index */
                                                 int lidx = localNodeId*N+component;  /* The local index  */
                                                         #ifdef ASSERT_ON
                                                                 assert( gidx >= 0 && gidx < Program.globalSolution[ dataidx ].size( ) );
                                                                 assert( lidx >= 0 && lidx < Program.solution[ paneidx ][ dataidx ].size( ) );
                                                         #endif
                                                         Program.globalSolution[ dataidx ][ gidx ] = Program.solution[ paneidx ][ dataidx ][ lidx ];
                                         } // End for all components
                                 } // End for all nodes
                           } // End else
                         } // End if NodeData
                         else if( Program.getDataItemType( dataidx ) == CELLDATA )
{
                                 if( Program.solution[ paneidx ][ dataidx ].size( ) == 0 )
{
                                         Program.solutionignore[ dataidx ] = true;
                                         Program.globalSolution[ dataidx ].resize( 0 );
                                 }
                                 else
{
                                         int N                             = Program.smdv[ dataidx ].ncomp;
                                         int NumElements = Program.meshes[ paneidx ].con.Nelem( );
                                         #ifdef ASSERT_ON
                                                 assert( Program.meshes[ paneidx ].con.Nelem( )*N == Program.solution[ paneidx ][ dataidx ].size( ) );
                                         #endif
                                         for( int localElement=0; localElement < NumElements; ++ localElement )
{
                                                 #ifdef ASSERT_ON
                                                         assert( ehash ->exists( paneId, localElement ) );
                                                 #endif
                                                 int globalId = ehash ->getGlobalId( paneId, localElement );
                                                 for( int component=0; component < N; ++component )
{
                                                         int gidx = globalId*N+component;                        /* The global index */
                                                         int lidx = localElement*N+component;    /* The local index */
                                                         #ifdef ASSERT_ON
                                                                 assert( gidx >= 0 && gidx < Program.globalSolution[ dataidx ].size( ) );
                                                                 assert( lidx >= 0 && lidx < Program.solution[ paneidx ][ dataidx ].size( ) );
                                                         #endif
                                                         Program.globalSolution[ dataidx ][ gidx ] = Program.solution[ paneidx ][ dataidx ][ lidx ];
                                                 } // End for all components
                                         } // End for all elements
                                 } // End else
                         } // End if CellData
                         else
{
                                 std::cerr << "Code should not reach here!\n";
                                 std::cerr << "File: " << __FILE__ << std::endl;
                                 std::cerr << "Line: " << __LINE__ << std::endl;
                                 assert( false );
                         }
                 } /* End for all solution data */
         } /* End For all panes */
         std::cout << "[DONE]\n";
 }
void updateHash (const int meshPaneId, const int pointId, const int globalId, MeshPointIdToGlobalIdMap * hash)
This method updates a MeshPointIdToGlobalIdMap hash with the mesh panes and point IDs mapping to the global ID.
Parameters
meshPaneId the pane id of the mesh that the local point id belongs to.
pointId the point id of the point assigned a new global ID.
globalId the global Id to be assigned to the given point.
hash pointer to the has data-structure to be updated.
Precondition
Program.hasPane(meshPaneId) == true.
pointId >= 0 && pointId < Program.meshes[ Program.getPaneIndex(meshPaneId) ].nc.Size()
globalId >= 0.
hash != NULL.
Definition at line 894 of file hdf2pltV2.C.
References i, MeshPointIdToGlobalIdMap::insert(), key, and Program.
Referenced by stitchGrids().
 {
         #ifdef ASSERT_ON
                 assert( Program.hasPane( meshPaneId ) );
                 assert( pointId >= 0 && pointId < Program.meshes[ Program.getPaneIndex( meshPaneId ) ].nc.Size( ) );
                 assert( globalId >= 0 );
                 assert( hash != NULL );
         #endif
         hash ->insert( meshPaneId, pointId, globalId );
         int idx = Program.getPaneIndex( meshPaneId );
         #ifdef ASSERT_ON
                 assert( idx >= 0 && idx < Program.numberOfPanes );
         #endif
   std::vector< std::pair< int, int > > connections;
         Program.getPaneConnectivity( idx ) ->getPointConnectionPairs( pointId, connections );
         for( int i=0; i < connections.size( ); ++i )
         {
                 int remotePaneId = connections[ i ].first;
                 int nodeIndex            = connections[ i ].second;
                 #ifdef ASSERT_ON
                         assert( Program.hasPane( remotePaneId ) );
                 #endif
                 int remotePoint                                         = Program.getPaneConnectivity( Program.getPaneIndex( remotePaneId ) )->getSharedPointIdAt( meshPaneId, nodeIndex );
                 std::pair< int, int > key = std::make_pair( remotePaneId, remotePoint );
                 #ifdef ASSERT_ON
                         assert( remotePoint >= 0 && remotePoint < Program.meshes[ Program.getPaneIndex( remotePaneId ) ].nc.Size( ) );
                         assert( Program.isNodeShared( Program.getPaneIndex( remotePaneId ), remotePoint ) == true );
                 #endif
                 if( !hash ->exists( remotePaneId, remotePoint ) )
                         hash ->insert( remotePaneId, remotePoint, globalId );
         }
 }
void writePlotFile ()
Generates a single zone plot file from the stitched mesh.
Generates a single zone plot file from the merged mesh.
Precondition
Program.globalNodeList.size() > 0.
Program.globalElementList.size() > 0.
Program.smdv.size() > 0.
Program.globalSolution.size() == Program.smdv.size().
Program.solutionignore.size() == Program.smdv.size().
Program.outputfile != ""
Postcondition
A VTK formatted file is written in Program.outputfile.vtk
Note
The extension in the outputfile will be appended.
Precondition
Program.globalNodeList.size() > 0.
Program.globalElementList.size() > 0.
Program.smdv.size() > 0.
Program.globalSolution.size() == Program.smdv.size().
Program.solutionignore.size() == Program.smdv.size().
Program.outputfile != ""
Postcondition
A Tecplot formatted file is written in Program.outputfile.plt
Note
The extension in the outputfile will be appended.
Definition at line 459 of file hdf2pltV2.C.
References CELLDATA, i, j, and Program.
Referenced by printWindow().
 {
         std::cout << "Writing TECPLOT file...";
         std::cout.flush( );
         #ifdef ASSERT_ON
                 assert( Program.globalNodeList.size( ) >  0     );
                 assert( Program.globalElementList.size( ) > 0 );
                 assert( Program.smdv.size( ) > 0 );
                 assert( Program.globalSolution.size( ) == Program.smdv.size( ) );
                 assert( Program.solutionignore.size( ) == Program.smdv.size( ) );
                 assert( Program.outputfile != "" );
         #endif
                 std::ofstream ofs;
                 ofs.open( std::string(Program.outputfile + ".dat").c_str( ) );
                 if( !ofs.is_open( ) )
                 {
                         std::cerr << "Cannot write TECPLOT file: " << Program.outputfile+".vtk" << std::endl;
                         std::cerr << "File: " << __FILE__                << std::endl;
                         std::cerr << "Line: " << __LINE__                << std::endl;
                         assert( false );
                 }
                 /* Write title */
                 ofs << "TITLE=\"" << Program.outputfile << " " << __DATE__ << "\"" << std::endl;
                 /* Write Variables */
                 int variableCount = 3;
                 std::vector< int > ecenteredidx;
                 ofs << "VARIABLES= \"X\", \"Y\", \"Z\"";
                 for( int i=0; i < Program.smdv.size( ); ++i )
                 {
                         if( !Program.solutionignore[ i ] )
{
                                 if( Program.smdv[ i ].ncomp > 1 )
{
                                          for( int component=0; component < Program.smdv[ i ].ncomp; ++component )
{
                                                  ofs << ", \"";
                                                  ofs << component+1 << "-" << Program.smdv[ i ].name;
                                                  ofs << "\"";
                                                  ++variableCount;
                                                  if( Program.getDataItemType( i ) == CELLDATA )
                                                          ecenteredidx.push_back( variableCount );
                                          }
                                 }
                                 else
{
                                         ofs << ", \"" << Program.smdv[ i ].name << "\"";
                                         ++variableCount;
                                         if( Program.getDataItemType( i ) == CELLDATA )
                                                 ecenteredidx.push_back( variableCount );
                                 }
                         } /* End if solution is not ignored */
                 } /* End for all variables */
                 /* Write Zone header */
                 ofs << std::endl;
                 ofs << "ZONE " << "NODES=" << Program.globalNodeList.size( )/3 << " ";
                 ofs << "ELEMENTS=" << Program.globalElementList.size( ) << " ";
                 ofs << "ZONETYPE=" << Program.getTecplotZoneType( ) << " ";
                 ofs << "DATAPACKING=BLOCK ";
                 if( !ecenteredidx.empty( ) )
                 {
                         ofs << "VARLOCATION=([";
                         ofs << ecenteredidx[ 0 ];
                         for( int i=1; i < ecenteredidx.size( ); ++i )
                                 ofs << "," << ecenteredidx[ i ];
                         ofs << "]=CELLCENTERED)";
                 }
                 ofs << std::endl;
                 /* Write nodes */
                 for( int i=0; i < 3; ++i )
                 {
                         switch( i )
{
                                 case 0:
                                         ofs << "# Begin X\n";
                                         break;
                                 case 1:
                                         ofs << "# Begin Y\n";
                                         break;
                                 case 2:
                                         ofs << "# Begin Z\n";
                                         break;
                                 default:
                                         std::cerr << "Error: Code should not reach here!\n";
                                         std::cerr << "File: " << __FILE__ << std::endl;
                                         std::cerr << "Line: " << __LINE__ << std::endl;
                                         std::cerr << "core dumping...\n";
                                         assert( false );
                         }
                         for( int node=0; node < Program.globalNodeList.size( )/3; ++node )
{
                                 ofs << Program.globalNodeList[ node*3 + i] << " ";
                                 if( node % 10 == 9 )
                                         ofs << std::endl;
                         }
                         ofs << std::endl;
                 }/* End for all dimensions */
                 /* End Write nodes */
                 /* Write the solution */
                 for( int i=0; i < Program.globalSolution.size( ); ++i )
                 {
                         if( ! Program.solutionignore[ i ] )
{
                                 if( Program.smdv[ i ].ncomp > 1 )
{
                                         for( int component=0; component < Program.smdv[ i ].ncomp; ++component )
{
                                                 ofs << "\n# Begin " << component+1 << "-" << Program.smdv[ i ].name << std::endl;
                                                 int stride   = Program.smdv[ i ].ncomp;
                                                 int NumItems = Program.globalSolution[ i ].size( )/stride;
                                                 for( int dataidx=0; dataidx < NumItems; ++dataidx )
{
                                                         ofs << Program.globalSolution[ i ][ dataidx*stride+component ] << " ";
                                                         if( dataidx % 10 == 9 )
                                                                 ofs << std::endl;
                                                 }
                                         }
                                 }
                                 else
{
                                         ofs << "\n# Begin " << Program.smdv[ i ].name << std::endl;
                                         for( int dataidx=0; dataidx < Program.globalSolution[ i ].size( ); ++dataidx )
{
                                                 ofs << Program.globalSolution[ i ][ dataidx ] << " ";
                                                 if( dataidx % 10 == 9 )
                                                         ofs << std::endl;
                                         }
                                 }
                                 ofs << std::endl;
                         } /* End if solution is not ignored */
                 }
                 /* End write solution */
                 /* Write the element connectivity */
                 ofs << std::endl << "# Begin Element Connectivity\n";
                 for( int i=0; i < Program.globalElementList.size( ); ++i )
                 {
                         for( int j=0; j < Program.globalElementList[ i ].size( ); ++j )
{
                                 ofs << Program.globalElementList[ i ][ j ]+1 << " ";
                         }
                         ofs << std::endl;
                 }
                 /* End write the element connectivity */
                 ofs.close( );
                 std::cout << "[DONE]\n";
 }
void writeVtkData ()
Writes the merged grid and its data in VTK UNSTRUCTURED_GRID file format.
Precondition
Program.globalNodeList.size() > 0.
Program.globalElementList.size() > 0.
Program.smdv.size() > 0.
Program.globalSolution.size() == Program.smdv.size().
Program.solutionignore.size() == Program.smdv.size().
Program.outputfile != ""
Postcondition
A VTK formatted file is written in Program.outputfile.vtk
Note
The extension in the outputfile will be appended.
Definition at line 645 of file hdf2pltV2.C.
References CELLDATA, i, j, NODEDATA, and Program.
Referenced by printWindow().
 {
         std::cout << "Writing VTK data...";
         std::cout.flush( );
         #ifdef ASSERT_ON
                 assert( Program.globalNodeList.size( ) >  0     );
                 assert( Program.globalElementList.size( ) > 0 );
                 assert( Program.smdv.size( ) > 0 );
                 assert( Program.globalSolution.size( ) == Program.smdv.size( ) );
                 assert( Program.solutionignore.size( ) == Program.smdv.size( ) );
                 assert( Program.outputfile != "" );
         #endif
         std::ofstream ofs;
         ofs.open( std::string(Program.outputfile + ".vtk").c_str( ) );
         if( !ofs.is_open( ) )
         {
                 std::cerr << "Cannot write VTK file: " << Program.outputfile+".vtk" << std::endl;
                 std::cerr << "File: " << __FILE__                << std::endl;
                 std::cerr << "Line: " << __LINE__                << std::endl;
                 assert( false );
         }
         /* STEP 1: Write the header */
         ofs << "# vtk DataFile Version 3.0\n";
         ofs << "Global Mesh Output" << std::endl;
         ofs << "ASCII\n";
         ofs << "DATASET UNSTRUCTURED_GRID\n";
         ofs << "POINTS " << Program.globalNodeList.size( )/3 << " double\n";
         /* STEP 2: Write the nodes */
         for( int i=0; i < Program.globalNodeList.size( )/3; ++i )
         {
                 ofs << Program.globalNodeList[ i*3       ] << " ";
                 ofs << Program.globalNodeList[ i*3+1 ] << " ";
                 ofs << Program.globalNodeList[ i*3+2 ] << std::endl;
         }
         /* STEP 3: Write the max element size */
         int maxnodes = 0; /* the maximum number of nodes per element */
         for( int i=0; i < Program.globalElementList.size( ); ++i )
         {
                 if( maxnodes < Program.globalElementList[ i ].size( ) )
                         maxnodes = Program.globalElementList[ i ].size( );
         }
         /* STEP 4: Write the element connectivity */
         ofs << "CELLS " << Program.globalElementList.size( ) << " " << Program.globalElementList.size( )*( maxnodes+1) << "\n";
         for( int i=0; i < Program.globalElementList.size( ); ++i  )
         {
                 ofs <<  Program.globalElementList[ i ].size( ) << " ";
                 for( int j=0; j < Program.globalElementList[ i ].size( ); ++j )
                         ofs <<  Program.globalElementList[ i ][ j ]<< " ";
                 ofs << std::endl;
         }
         /* STEP 5: Write the cell types */
         ofs << "CELL_TYPES " << Program.globalElementList.size( ) << std::endl;
         for( int i=0; i < Program.globalElementList.size( ); ++i )
         {
                 if( Program.globalElementList[ i ].size( ) == 8 )
                         ofs << "12\n";
                 else if( Program.globalElementList[ i ].size( ) == 4 )
                         ofs << "10\n";
                 else {
                         std::cerr << "Undefined element type!\n";
                         std::cerr << "File: " << __FILE__ << std::endl;
                         std::cerr << "Line: " << __LINE__ << std::endl;
                 }
         }
         /* STEP 6: Write the solution data attached to the points */
         bool wroteHeader = false;
         for( int i=0; i < Program.globalSolution.size( ); ++i )
         {
                 if( ! Program.solutionignore[ i ] && Program.getDataItemType( i ) == NODEDATA  )
                 {
                         int N = Program.globalNodeList.size( )/3;
                         int NC      = Program.smdv[ i ].ncomp;
                         if(!wroteHeader)
{
                                 ofs << "POINT_DATA " << N << std::endl;
                                 wroteHeader = true;
                         }
                         if( NC == 1 )
{
                                         ofs << "SCALARS " << Program.smdv[ i ].name << " double" << std::endl;
                                         ofs << "LOOKUP_TABLE default\n";
                         }
                         else if( NC == 3 )
{
                                 ofs << "VECTORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         else
{
                                 ofs << "TENSORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         for( int j=0; j < N; ++j )
{
                                 for( int component=0; component < NC; ++component )
{
                                         ofs << Program.globalSolution[ i ][ j*NC+component ] << " ";
                                 }
                                 ofs << std::endl;
                         }
                 } /* End if the solution is not ignored */
         } /* End for all solution data */
         /* STEP 6: Write the solution data attached to the cells */
         wroteHeader = false;
         for( int i=0; i < Program.globalSolution.size( ); ++i )
         {
                 if( ! Program.solutionignore[ i ] && Program.getDataItemType( i ) == CELLDATA )
                 {
                         int N                   = Program.globalElementList.size();
                         int NC      = Program.smdv[ i ].ncomp;
                         if( !wroteHeader )
{
                                 ofs << "CELL_DATA " << N << std::endl;
                                 wroteHeader = true;
                         }
                         if( NC == 1 )
{
                                         ofs << "SCALARS " << Program.smdv[ i ].name << " double" << std::endl;
                                         ofs << "LOOKUP_TABLE default\n";
                         }
                         else if( NC == 3 )
{
                                 ofs << "VECTORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         else
{
                                 ofs << "TENSORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         for( int j=0; j < N; ++j )
{
                                 for( int component=0; component < NC; ++component )
{
                                         ofs << Program.globalSolution[ i ][ j*NC+component ] << " ";
                                 }
                                 ofs << std::endl;
                         }
                 } /* End if the solution is not ignored */
         } /* End for all solution data */
         ofs.close( );
         std::cout << "[DONE]\n";
 }
void writeVtkFiles (std::vector< Mesh::UnstructuredMesh > & meshes)
Writes the set of meshes into separate VTK files that can be visualized with Paraview.
Writes VTK files for the corresponding meshes.
The format of the files is {outputFile}.paneId.vtk.
Note
This method is mainly used for debugging.
Parameters
m the set of meshes.
meshes List of meshes in the current window.
Definition at line 1354 of file hdf2pltV2.C.
References i, j, and Program.
Referenced by printWindow().
 {
         // TODO: Generalize this function for any type of mesh.
         for( int m=0; m < meshes.size( ); ++m )
         {
                 std::ostringstream oss; oss.clear( );
                 oss << Program.outputfile << "." << Program.paneIds[ m ] << ".vtk";
                 std::ofstream ofs;
                 ofs.open( oss.str( ).c_str( ) );
                 if( !ofs.is_open( ) )
                 {
                         std::cerr << "Cannot write VTK file: " << oss.str( ) << std::endl;
                         std::cerr << "File: " << __FILE__ << std::endl;
                         std::cerr << "Line: " << __LINE__ << std::endl;
                         assert( false );
                 }
                 ofs << "# vtk DataFile Version 3.0\n";
                 ofs << oss.str( ) << std::endl;
                 ofs << "ASCII\n";
                 ofs << "DATASET UNSTRUCTURED_GRID\n";
                 ofs << "POINTS " << meshes[ m ].nc.Size( ) << " double\n";
                 for( int i=1; i <= meshes[ m ].nc.Size( ); ++i )
                 {
                         ofs << meshes[ m ].nc.x( i ) << " ";
                         ofs << meshes[ m ].nc.y( i ) << " ";
                         ofs << meshes[ m ].nc.z( i ) << "\n";
                 }
                 ofs << "CELLS " << meshes[ m ].con.Nelem( ) << " " << meshes[ m ].con.Nelem( )*9 << "\n";
                 for( int e=1; e <= meshes[ m ].con.Nelem( ); ++e )
                 {
                         ofs <<  "8 ";
                         for( int j=1; j <= 8; ++j )
                                 ofs << meshes[ m ].con.Node( e, j )-1<< " ";
                         ofs << std::endl;
                 }
                 ofs << "CELL_TYPES " << meshes[ m ].con.Nelem( ) << std::endl;
                 for( int e=1; e <= meshes[ m ].con.Nelem( ); ++ e )
                         ofs << "12\n";
                 ofs << "POINT_DATA " << Program.mask[ m ].size( ) << std::endl;
                 ofs << "SCALARS SharedNodes double\nLOOKUP_TABLE default\n";
                 for( int i=0; i < Program.mask[ m ].size( ); ++i )
                 {
                         if( Program.mask[ m ][ i ] )
                                 ofs << "1\n";
                         else
                                 ofs << "0\n";
                 }
                 ofs.close( );
         }
 }
Variable Documentation
bool blocks
Input data is block-structured grid.
Definition at line 51 of file hdf2pltV2.C.
Referenced by __scalegrd.f90__(), COM_print_window(), main(), and readBlock().
std::string cntrlfile
Control file string.
Definition at line 53 of file hdf2pltV2.C.
std::string fileregx
File regular expression.
Definition at line 54 of file hdf2pltV2.C.
std::vector< std::vector< int > > globalElementList
The global element list.
Definition at line 73 of file hdf2pltV2.C.
std::vector< double > globalNodeList
The global node list.
Definition at line 72 of file hdf2pltV2.C.
std::vector< std::vector< double > > globalSolution
Contains the global solution.
Definition at line 70 of file hdf2pltV2.C.
std::vector< std::vector< bool > > mask
Masks the points that are shared (true) share (false) not shared.
Definition at line 62 of file hdf2pltV2.C.
Referenced by CImg< uintT >::_draw_text(), CImgList< uintT >::_font(), CImg< uintT >::_load_bmp(), CImg< uintT >::get_correlate(), CImg< uintT >::get_dilate(), CImg< uintT >::get_erode(), and CImg< uintT >::get_resize_halfXY().
std::vector< Mesh::UnstructuredMesh > meshes
The list of grids to write.
Definition at line 61 of file hdf2pltV2.C.
int numberOfPanes
The number of panes, aka number of sub-domains.
Definition at line 59 of file hdf2pltV2.C.
std::string outputfile
Output file to write the file.
Definition at line 55 of file hdf2pltV2.C.
std::vector< int > paneIds
Array of paneIds.
Definition at line 60 of file hdf2pltV2.C.
Referenced by COM_print_window(), project_window(), Rocout::write_attr_internal(), and Rocout::write_rocin_control_file().
std::map< int, int > paneIds2index
Maps the pane ids to the index in the corresponding vectors.
Definition at line 66 of file hdf2pltV2.C.
std::vector< PaneConnectivity > pconns
Inter-zone (pane) connectivity information.
Definition at line 65 of file hdf2pltV2.C.
std::string prgmname
The program name.
Definition at line 58 of file hdf2pltV2.C.
struct { ... } Program
Referenced by convertWindow(), getPaneConnectivity(), getWindow(), main(), maskPoints(), parseArguments(), printWindow(), stitchGrids(), stitchSolutionData(), updateHash(), writePlotFile(), Mesh::writeVtkData(), and writeVtkFiles().
bool readControlFile
Data is read from the control file.
Definition at line 49 of file hdf2pltV2.C.
std::vector< SolnMetaData > smdv
The solution Metadata.
Definition at line 63 of file hdf2pltV2.C.
std::vector< std::vector< std::vector< double > > > solution
The solution data.
Definition at line 64 of file hdf2pltV2.C.
std::vector< bool > solutionignore
Masks the data to be ignored.
Definition at line 71 of file hdf2pltV2.C.
bool vtk
Writes vtk files.
Definition at line 52 of file hdf2pltV2.C.
bool withGhost
Ghost nodes will be used.
Definition at line 50 of file hdf2pltV2.C.