Rocstar: HomogenizedMat.f90 File Reference
HomogenizedMat.f90 File Reference
Functions/Subroutines
subroutine homogenizedmat (Density, Em, PRm, Ep, PRp, cm, cd_fastest)
subroutine compositestiffnes (Lm, L2, Mm, M2, cm, c2, alpha1, alpha2, L_bar, M_bar, Lo)
subroutine eshelby (Shape, Mo, Lo, P, S)
subroutine invert2 (Inv_in, a, nrow)
Function/Subroutine Documentation
subroutine compositestiffnes (real*8, dimension(1:6,1:6) Lm, real*8, dimension(1:6,1:6) L2, real*8, dimension(1:6,1:6) Mm, real*8, dimension(1:6,1:6) M2, real*8 cm, real*8 c2, real*8 alpha1, real*8 alpha2, real*8, dimension(1:6,1:6) L_bar, real*8, dimension(1:6,1:6) M_bar, real*8, dimension(1:6,1:6) Lo)
Definition at line 135 of file HomogenizedMat.f90.
References Line_2< R, T >::a(), Color::b(), Line_2< R, T >::c(), eshelby(), i, invert2(), j, Aff_transformation_repS2< FT >::print(), s, and StopWatch::stop().
Referenced by homogenizedmat(), and vol_elem_mat_matous().
subroutine eshelby (integer Shape, real*8, dimension(1:6,1:6) Mo, real*8, dimension(1:6,1:6) Lo, real*8, dimension(1:6,1:6) P, real*8, dimension(1:6,1:6) S)
Definition at line 250 of file HomogenizedMat.f90.
References Color::g(), k, Aff_transformation_repS2< FT >::print(), s, and StopWatch::stop().
Referenced by a_d_tensors(), and compositestiffnes().
subroutine homogenizedmat (real*8 Density, real*8 Em, real*8 PRm, real*8 Ep, real*8 PRp, real*8 cm, real*8 cd_fastest)
Definition at line 54 of file HomogenizedMat.f90.
References compositestiffnes(), invert2(), max(), Aff_transformation_repS2< FT >::print(), and sqrt().
Referenced by micromechanical_sub().
subroutine invert2 (real*8, dimension(1:nrow,1:nrow) Inv_in, real*8, dimension(1:nrow,1:nrow) a, integer nrow)
Definition at line 298 of file HomogenizedMat.f90.
References Line_2< R, T >::a(), i, j, k, ncol, nrow, Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
Referenced by a_d_tensors(), compositestiffnes(), homogenizedmat(), operatorj(), and vol_elem_mat_matous().