Rocstar: HUANG_Const_Model.f90 File Reference
HUANG_Const_Model.f90 File Reference
Functions/Subroutines
subroutine huang_const_model (dfgrad, matrix, nmatrix, particle, nparticle, nparticletype, interfac, ninterfac, stress, strain, ilarge, ismall)
Function/Subroutine Documentation
subroutine huang_const_model (real*8, dimension(3,3) dfgrad, real*8, dimension(nmatrix) matrix, nmatrix, real*8, dimension(nparticle,nparticletype) particle, nparticle, nparticletype, real*8, dimension(ninterfac) interfac, ninterfac, real*8, dimension(3,3) stress, real*8, dimension(3,3) strain, real*8 ilarge, real*8 ismall)
Definition at line 53 of file HUANG_Const_Model.f90.
References Color::alpha(), Line_2< R, T >::c(), i, j, and CImg< T >::matrix().
Referenced by v3d10_nl_huang().