Rocstar: implicit_initialize.f90 File Reference
implicit_initialize.f90 File Reference
Functions/Subroutines
subroutine implicit_initialize (global)
Function/Subroutine Documentation
subroutine implicit_initialize (type(rocfrac_global) global)
Definition at line 74 of file implicit_initialize.f90.
References createk(), createm(), i, initcomm1(), initcomm2(), j, Aff_transformation_2< R_ >::m(), min(), and Aff_transformation_repS2< FT >::print().
Referenced by rocfracmain::rocfracinitialize().