Rocstar: implicit_soln.f90 File Reference
implicit_soln.f90 File Reference
Functions/Subroutines
subroutine implicit_soln (delt, t, fext_in, global)
Function/Subroutine Documentation
subroutine implicit_soln (real(kind=wp) delt, real(kind=wp) t, real(kind=wp), dimension(1:3*global%numnp) fext_in, type(rocfrac_global) global)
Definition at line 53 of file implicit_soln.f90.
References Line_2< R, T >::a(), comp_row_add(), Plane_3< R, T >::d(), get_fint(), i, implicit_bc_enforce(), j, k, Aff_transformation_2< R_ >::m(), Aff_transformation_repS2< FT >::print(), removebcs_meff(), removebcs_newa(), removebcs_pbar(), and v.
Referenced by rocfracmain::rocfracsoln().