Rocstar: Bbox_2.h File Reference
include/CGAL/Bbox_2.h File Reference
#include <CGAL/basic.h>
#include <cmath>
#include <CGAL/cgalopt.h>
Classes
class Bbox_2
Functions
std::ostream & operator<< (std::ostream &os, const Bbox_2 &b)
std::istream & operator>> (std::istream &is, Bbox_2 &b)
bool do_overlap (const Bbox_2 &bb1, const Bbox_2 &bb2)
bool do_overlap_eps (const Bbox_2 &bb1, const Bbox_2 &bb2, const double eps)
bool do_overlap_strict (const Bbox_2 &bb1, const Bbox_2 &bb2)
template<class InIter >
Bbox_2 get_Bbox_2 (InIter first, InIter last)
Function Documentation
bool do_overlap (const Bbox_2 & bb1, const Bbox_2 & bb2) inline
Definition at line 138 of file include/CGAL/Bbox_2.h.
References Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), and Bbox_2::ymin().
 {
   // check for emptiness ??
   if (bb1.xmax() < bb2.xmin() || bb2.xmax() < bb1.xmin())
     return false;
   if (bb1.ymax() < bb2.ymin() || bb2.ymax() < bb1.ymin())
     return false;
   return true;
 }
bool do_overlap_eps (const Bbox_2 & bb1, const Bbox_2 & bb2, const double eps) inline
Definition at line 155 of file include/CGAL/Bbox_2.h.
References Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), and Bbox_2::ymin().
{
   // check for emptiness ??
   if (bb1.xmax()+eps < bb2.xmin() || bb2.xmax()+eps < bb1.xmin())
     return false;
   if (bb1.ymax()+eps < bb2.ymin() || bb2.ymax()+eps < bb1.ymin())
     return false;
   return true;
 }
bool do_overlap_strict (const Bbox_2 & bb1, const Bbox_2 & bb2) inline
Definition at line 165 of file include/CGAL/Bbox_2.h.
References Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), and Bbox_2::ymin().
 {
   if (bb1.xmax() <= bb2.xmin() || bb2.xmax() <= bb1.xmin())
     return false;
   if (bb1.ymax() <= bb2.ymin() || bb2.ymax() <= bb1.ymin())
     return false;
   return true;
 }
Bbox_2 get_Bbox_2 (InIter first, InIter last)
Definition at line 175 of file include/CGAL/Bbox_2.h.
{
   Bbox_2  box;
   while (first != last) {
     box += first->bbox();
     ++first;
   }
   return box;
 }
std::ostream& operator<< (std::ostream & os, const Bbox_2 & b) inline
Definition at line 91 of file include/CGAL/Bbox_2.h.
References IO::ASCII, IO::BINARY, IO::mode, write(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), and Bbox_2::ymin().
 {
   switch(os.iword(IO::mode)) {
   case IO::ASCII :
     os << b.xmin() << ' ' << b.ymin() << ' '
        << b.xmax() << ' ' << b.ymax();
     break;
   case IO::BINARY :
     write(os, b.xmin());
     write(os, b.ymin());
     write(os, b.xmax());
     write(os, b.ymax());
     break;
   default:
     os << "Bbox_2(" << b.xmin() << ", " << b.ymin() << ", "
        << b.xmax() << ", " << b.ymax() << ")";
     break;
   }
   return os;
 }
std::istream& operator>> (std::istream & is, Bbox_2 & b) inline
Definition at line 118 of file include/CGAL/Bbox_2.h.
References IO::ASCII, IO::BINARY, IO::mode, and read().
 {
   double xmin, ymin, xmax, ymax;
   switch(is.iword(IO::mode)) {
   case IO::ASCII :
     is >> xmin >> ymin >> xmax >> ymax;
     break;
   case IO::BINARY :
     read(is, xmin);
     read(is, ymin);
     read(is, xmax);
     read(is, ymax);
     break;
   }
   b = Bbox_2(xmin, ymin, xmax, ymax);
   return is;
 }