Rocstar: VectorS2.h File Reference
include/CGAL/SimpleCartesian/VectorS2.h File Reference
Classes
class VectorS2< FT >
Functions
template<class _RR >
VectorS2< _RR > operator* (const _RR &c, const VectorS2< _RR > &v)
template<class _RR >
std::ostream & operator<< (std::ostream &os, const VectorS2< _RR > &v)
template<class _RR >
std::istream & operator>> (std::istream &is, VectorS2< _RR > &v)
Function Documentation
VectorS2<_RR> operator* (const _RR & c, const VectorS2< _RR > & v) inline
Definition at line 119 of file include/CGAL/SimpleCartesian/VectorS2.h.
References VectorS2< FT >::x(), and VectorS2< FT >::y().
{
   return VectorS2<_RR>( c* v.x(), c * v.y());
 }
std::ostream& operator<< (std::ostream & os, const VectorS2< _RR > & v)
Definition at line 124 of file include/CGAL/SimpleCartesian/VectorS2.h.
References IO::ASCII, IO::BINARY, IO::mode, v, and write().
{
   switch(os.iword(IO::mode)) {
   case IO::ASCII :
     return os << v.x() << ' ' << v.y();
   case IO::BINARY :
     write(os, v.x());
     write(os, v.y());
     return os;
   default:
     return os << "VectorS2(" << v.x() << ", " << v.y() << ')';
   }
 }
std::istream& operator>> (std::istream & is, VectorS2< _RR > & v)
Definition at line 138 of file include/CGAL/SimpleCartesian/VectorS2.h.
References IO::ASCII, IO::BINARY, IO::mode, read(), VectorS2< FT >::x(), and VectorS2< FT >::y().
{
   switch(is.iword(IO::mode)) {
   case IO::ASCII :
     is >> v.x() >> v.y();
     break;
   case IO::BINARY :
     read(is, v.x());
     read(is, v.y());
     break;
   default:
     std::cerr << "\nStream must be in ascii or binary mode\n";
     break;
   }
   return is;
 }