Rocstar: PointS2.h File Reference
include/CGAL/SimpleCartesian/PointS2.h File Reference
#include <CGAL/Origin.h>
#include <CGAL/SimpleCartesian/VectorS2.h>
#include <CGAL/SimpleCartesian/Aff_transformationS2.h>
#include <CGAL/Bbox_2.h>
#include <CGAL/number_utils.h>
Classes
class PointS2< FT >
Functions
template<class FT >
CGAL_END_NAMESPACE
CGAL_BEGIN_NAMESPACE PointS2
< FT > operator+ (const PointS2< FT > &p, const VectorS2< FT > &v)
template<class FT >
PointS2< FT > operator- (const PointS2< FT > &p, const VectorS2< FT > &v)
template<class FT >
PointS2< FT > operator+ (const Origin &, const VectorS2< FT > &v)
template<class FT >
PointS2< FT > operator- (const Origin &, const VectorS2< FT > &v)
template<class FT >
VectorS2< FT > operator- (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
VectorS2< FT > operator- (const PointS2< FT > &p, const Origin &)
template<class FT >
VectorS2< FT > operator- (const Origin &, const PointS2< FT > &p)
template<class FT >
std::ostream & operator<< (std::ostream &os, const PointS2< FT > &p)
template<class FT >
std::istream & operator>> (std::istream &is, PointS2< FT > &p)
Function Documentation
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE PointS2<FT> operator+ (const PointS2< FT > & p, const VectorS2< FT > & v) inline
Definition at line 108 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::x(), VectorS2< FT >::x(), PointS2< FT >::y(), and VectorS2< FT >::y().
 { return PointS2<FT>(p.x() + v.x(), p.y() + v.y()) ; }
PointS2<FT> operator+ (const Origin & , const VectorS2< FT > & v) inline
Definition at line 120 of file include/CGAL/SimpleCartesian/PointS2.h.
References v.
 { return PointS2<FT>(v) ; }
PointS2<FT> operator- (const PointS2< FT > & p, const VectorS2< FT > & v) inline
Definition at line 114 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::x(), VectorS2< FT >::x(), PointS2< FT >::y(), and VectorS2< FT >::y().
 { return PointS2<FT>(p.x() - v.x(), p.y() - v.y()) ; }
PointS2<FT> operator- (const Origin & , const VectorS2< FT > & v) inline
Definition at line 125 of file include/CGAL/SimpleCartesian/PointS2.h.
References v.
 { return PointS2<FT>(-v) ; }
VectorS2<FT> operator- (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 131 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 { return VectorS2<FT>(p.x() - q.x(), p.y() - q.y()) ; }
VectorS2<FT> operator- (const PointS2< FT > & p, const Origin &) inline
Definition at line 137 of file include/CGAL/SimpleCartesian/PointS2.h.
 { return VectorS2<FT>(p) ; }
VectorS2<FT> operator- (const Origin & , const PointS2< FT > & p) inline
Definition at line 143 of file include/CGAL/SimpleCartesian/PointS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
 { return VectorS2<FT>(-p.x(), -p.y()) ; }
std::ostream& operator<< (std::ostream & os, const PointS2< FT > & p)
Definition at line 150 of file include/CGAL/SimpleCartesian/PointS2.h.
References IO::ASCII, IO::BINARY, IO::mode, and write().
 {
     switch(os.iword(IO::mode))
     {
     case IO::ASCII :
         return os << p.x() << ' ' << p.y();
     case IO::BINARY :
         write(os, p.x());
         write(os, p.y());
         return os;
     default:
         return os << "PointS2(" << p.x() << ", " << p.y() << ')';
     }
 }
std::istream& operator>> (std::istream & is, PointS2< FT > & p)
Definition at line 169 of file include/CGAL/SimpleCartesian/PointS2.h.
References IO::ASCII, IO::BINARY, CGAL_kernel_assertion_msg, IO::mode, read(), x, and y.
 {
     FT x, y;
     switch(is.iword(IO::mode))
     {
     case IO::ASCII :
         is >> x >> y;
         break;
     case IO::BINARY :
         read(is, x);
         read(is, y);
         break;
     default:
         CGAL_kernel_assertion_msg(false,"Stream must be in ascii or binary mode");
         // throw ios_base::failure("Stream must be in ascii or binary mode");
     }
     p = PointS2<FT>(x, y);
     return is;
 }