Rocstar: Bbox_3.h File Reference
include/CGAL/Bbox_3.h File Reference
#include <CGAL/basic.h>
#include <cmath>
#include <CGAL/cgalopt.h>
Classes
class Bbox_3
Functions
bool do_overlap (const Bbox_3 &bb1, const Bbox_3 &bb2)
std::ostream & operator<< (std::ostream &os, const Bbox_3 &b)
std::istream & operator>> (std::istream &is, Bbox_3 &b)
bool do_overlap_eps (const Bbox_3 &bb1, const Bbox_3 &bb2, const double eps)
bool do_overlap_strict (const Bbox_3 &bb1, const Bbox_3 &bb2)
template<class InIter >
Bbox_3 get_Bbox_3 (InIter first, InIter last)
Function Documentation
bool do_overlap (const Bbox_3 & bb1, const Bbox_3 & bb2) inline
Definition at line 96 of file include/CGAL/Bbox_3.h.
References Bbox_3::xmax(), Bbox_3::xmin(), Bbox_3::ymax(), Bbox_3::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
 {
   // check for emptiness ??
   if (bb1.xmax() < bb2.xmin() || bb2.xmax() < bb1.xmin())
     return false;
   if (bb1.ymax() < bb2.ymin() || bb2.ymax() < bb1.ymin())
     return false;
   if (bb1.zmax() < bb2.zmin() || bb2.zmax() < bb1.zmin())
     return false;
   return true;
 }
bool do_overlap_eps (const Bbox_3 & bb1, const Bbox_3 & bb2, const double eps) inline
Definition at line 174 of file include/CGAL/Bbox_3.h.
References Bbox_3::xmax(), Bbox_3::xmin(), Bbox_3::ymax(), Bbox_3::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
{
   // check for emptiness ??
   if (bb1.xmax()+eps < bb2.xmin() || bb2.xmax()+eps < bb1.xmin())
     return false;
   if (bb1.ymax()+eps < bb2.ymin() || bb2.ymax()+eps < bb1.ymin())
     return false;
   if (bb1.zmax()+eps < bb2.zmin() || bb2.zmax()+eps < bb1.zmin())
     return false;
   return true;
 }
bool do_overlap_strict (const Bbox_3 & bb1, const Bbox_3 & bb2) inline
Definition at line 186 of file include/CGAL/Bbox_3.h.
References Bbox_3::xmax(), Bbox_3::xmin(), Bbox_3::ymax(), Bbox_3::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
 {
   // check for emptiness ??
   if (bb1.xmax() <= bb2.xmin() || bb2.xmax() <= bb1.xmin())
     return false;
   if (bb1.ymax() <= bb2.ymin() || bb2.ymax() <= bb1.ymin())
     return false;
   if (bb1.zmax() <= bb2.zmin() || bb2.zmax() <= bb1.zmin())
     return false;
   return true;
 }
Bbox_3 get_Bbox_3 (InIter first, InIter last)
Definition at line 199 of file include/CGAL/Bbox_3.h.
{
   Bbox_3  box;
   while (first != last) {
     box += first->bbox();
     ++first;
   }
   return box;
 }
std::ostream& operator<< (std::ostream & os, const Bbox_3 & b) inline
Definition at line 111 of file include/CGAL/Bbox_3.h.
References IO::ASCII, IO::BINARY, IO::mode, write(), Bbox_3::xmax(), Bbox_3::xmin(), Bbox_3::ymax(), Bbox_3::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
 {
   switch(os.iword(IO::mode))
     {
     case IO::ASCII :
       return os << b.xmin() << ' ' << b.ymin() << ' ' << b.zmin() << ' '
                 << b.xmax() << ' ' << b.ymax() << ' ' << b.zmax();
     case IO::BINARY :
       write(os, b.xmin());
       write(os, b.ymin());
       write(os, b.zmin());
       write(os, b.xmax());
       write(os, b.ymax());
       write(os, b.zmax());
       return os;
     default:
       os << "Bbox_3((" << b.xmin()
          << ", "       << b.ymin()
          << ", "       << b.zmin() << "), (";
       os <<               b.xmax()
          << ", "       << b.ymax()
          << ", "       << b.zmax() << "))";
       return os;
     }
 }
std::istream& operator>> (std::istream & is, Bbox_3 & b) inline
Definition at line 143 of file include/CGAL/Bbox_3.h.
References IO::ASCII, IO::BINARY, IO::mode, and read().
 {
   double xmin, ymin, zmin, xmax, ymax, zmax;
   switch(is.iword(IO::mode))
     {
     case IO::ASCII :
       is >> xmin >> ymin >> zmin >> xmax >> ymax >> zmax ;
       break;
     case IO::BINARY :
       read(is, xmin);
       read(is, ymin);
       read(is, zmin);
       read(is, xmax);
       read(is, ymax);
       read(is, zmax);
       break;
     }
   b = Bbox_3(xmin, ymin, zmin, xmax, ymax, zmax);
   return is;
 }