Rocstar: VectorS3.h File Reference
include/CGAL/SimpleCartesian/VectorS3.h File Reference
Classes
class VectorS3< FT >
Functions
template<class FT >
VectorS3< FT > operator* (const FT &c, const VectorS3< FT > &w)
template<class FT >
VectorS3< FT > cross_product (const VectorS3< FT > &v, const VectorS3< FT > &w)
template<class FT >
std::ostream & operator<< (std::ostream &os, const VectorS3< FT > &v)
template<class FT >
std::istream & operator>> (std::istream &is, VectorS3< FT > &v)
Function Documentation
VectorS3<FT> cross_product (const VectorS3< FT > & v, const VectorS3< FT > & w)
Definition at line 139 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
 {
     return VectorS3<FT>( v.y() * w.z() - v.z() * w.y() ,
                          v.z() * w.x() - v.x() * w.z() ,
                          v.x() * w.y() - v.y() * w.x() );
 }
VectorS3<FT> operator* (const FT & c, const VectorS3< FT > & w) inline
Definition at line 134 of file include/CGAL/SimpleCartesian/VectorS3.h.
References VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
 { return VectorS3<FT>( c* w.x(), c * w.y(), c * w.z()) ; }
std::ostream& operator<< (std::ostream & os, const VectorS3< FT > & v)
Definition at line 147 of file include/CGAL/SimpleCartesian/VectorS3.h.
References IO::ASCII, IO::BINARY, IO::mode, v, and write().
 {
   switch(os.iword(IO::mode)) {
   case IO::ASCII :
     return os << v.x() << ' ' << v.y()  << ' ' << v.z();
   case IO::BINARY :
     write(os, v.x());
     write(os, v.y());
     write(os, v.z());
     return os;
   default:
     os << "VectorS3(" << v.x() << ", " << v.y() <<  ", " << v.z() << ")";
     return os;
   }
 }
std::istream& operator>> (std::istream & is, VectorS3< FT > & v)
Definition at line 164 of file include/CGAL/SimpleCartesian/VectorS3.h.
References IO::ASCII, IO::BINARY, IO::mode, read(), VectorS3< FT >::x(), VectorS3< FT >::y(), and VectorS3< FT >::z().
 {
   switch(is.iword(IO::mode)) {
   case IO::ASCII :
     is >> v.x() >> v.y() >> v.z();
         break;
   case IO::BINARY :
     read(is, v.x());
     read(is, v.y());
     read(is, v.z());
     break;
   default:
     std::cerr << "\nStream must be in ascii or binary mode\n";
     break;
   }
   return is;
 }