Rocstar: RFLU_DeallocMemSolWrapper.F90 File Reference
init/RFLU_DeallocMemSolWrapper.F90 File Reference
Functions/Subroutines
subroutine rflu_deallocmemsolwrapper (pRegion)
Function/Subroutine Documentation
subroutine rflu_deallocmemsolwrapper (type(t_region), pointer pRegion)
Definition at line 45 of file init/RFLU_DeallocMemSolWrapper.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_moddeallocatememory::rflu_deallocatememorysolcv(), rflu_moddeallocatememory::rflu_deallocatememorysoldv(), rflu_moddeallocatememory::rflu_deallocatememorysolgv(), spec_rflu_deallocatememoryeev(), and spec_rflu_deallocatememorysol().