Rocstar: initK.f90 File Reference
initK.f90 File Reference
Functions/Subroutines
subroutine numknnz (NumNp, NumEl, ElConnVol, nnz)
subroutine initk (NumNp, NumEl, ElConnVol, nnz, rp, cval, aval)
Function/Subroutine Documentation
subroutine initk (integer NumNp, integer NumEl, integer, dimension(1:8,1:numel) ElConnVol, integer nnz, integer, dimension(1:3*gnumnp+1) rp, integer, dimension(1:nnz) cval, integer, dimension(1:nnz) aval)
Definition at line 197 of file initK.f90.
References i, j, k, and Aff_transformation_2< R_ >::m().
Referenced by implicit_v3d8_me_k().
subroutine numknnz (integer NumNp, integer NumEl, integer, dimension(1:8,1:numel) ElConnVol, integer nnz)
Definition at line 78 of file initK.f90.
References i, j, k, and Aff_transformation_2< R_ >::m().
Referenced by implicit_v3d8_me_k().