Rocstar: InitCommunicationMP.F90 File Reference
InitCommunicationMP.F90 File Reference
Functions/Subroutines
subroutine initcommunicationmp (regions, iReg, istage)
Function/Subroutine Documentation
subroutine initcommunicationmp (type(t_region), dimension(:), pointer regions, integer iReg, integer istage)
Definition at line 45 of file InitCommunicationMP.F90.
References moderror::deregisterfunction(), peul_boundaryconditionssend(), moderror::registerfunction(), rflo_modboundaryconditions::rflo_boundaryconditionssend(), and turb_rflo_ransbndconditionssend().
Referenced by rungekuttamp().