Rocstar: INRT_ReadBoilingRegulation.F90 File Reference
INRT_ReadBoilingRegulation.F90 File Reference
Functions/Subroutines
subroutine inrt_readboilingregulation (regions)
Function/Subroutine Documentation
subroutine inrt_readboilingregulation (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file INRT_ReadBoilingRegulation.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), rflu_modrepair3d::input(), inrt_defineboilingregulation(), inrt_setmaterial(), modinterfacesio::ReadBothRegionSection::readbothregionsection(), modinterfacesio::ReadBothSection::readbothsection(), and moderror::registerfunction().
Referenced by inrt_readinputfile().