Rocstar: INRT_UserInput.F90 File Reference
INRT_UserInput.F90 File Reference
Functions/Subroutines
subroutine inrt_userinput (regions)
Function/Subroutine Documentation
subroutine inrt_userinput (type (t_region), dimension(:), pointer regions)
Definition at line 44 of file INRT_UserInput.F90.
References moderror::deregisterfunction(), inrt_checkuserinput(), inrt_computemaxedges(), inrt_initialize(), inrt_readinputfile(), and moderror::registerfunction().
Referenced by rflo_getuserinput(), and rflu_getuserinput().