Rocstar: INRT_ReadInputFile.F90 File Reference
INRT_ReadInputFile.F90 File Reference
Functions/Subroutines
subroutine inrt_readinputfile (regions)
Function/Subroutine Documentation
subroutine inrt_readinputfile (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file INRT_ReadInputFile.F90.
References moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, inrt_readboilingregulation(), inrt_readburning(), inrt_readdefaultsection(), inrt_readdrag(), inrt_readheattransfernonburn(), inrt_readscouring(), CImg< T >::line(), moderror::registerfunction(), and Attribute::status().
Referenced by inrt_userinput().