Rocstar: INRT_PrintUserInput.F90 File Reference
INRT_PrintUserInput.F90 File Reference
Functions/Subroutines
subroutine inrt_printuserinput (region)
character(13) function defstr (eq)
character(10) function nodestr (ind)
character(1) function permstr (perm)
character(5) function tedgestr (tEdge)
character(20) function fullactvstr (actv)
character(40) function fullpermstr (perm)
Function/Subroutine Documentation
character(13) function inrt_printuserinput::defstr (logical, intent(in) eq)
Definition at line 246 of file INRT_PrintUserInput.F90.
character(20) function inrt_printuserinput::fullactvstr (integer, intent(in) actv)
Definition at line 340 of file INRT_PrintUserInput.F90.
Referenced by inrt_printuserinput().
character(40) function inrt_printuserinput::fullpermstr (integer, intent(in) perm)
Definition at line 362 of file INRT_PrintUserInput.F90.
Referenced by inrt_printuserinput().
subroutine inrt_printuserinput (type(t_region), intent(in) region)
Definition at line 43 of file INRT_PrintUserInput.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), fullactvstr(), fullpermstr(), rflu_modrepair3d::input(), makenumberedkeys(), nodestr(), permstr(), moderror::registerfunction(), and tedgestr().
Referenced by rflo_printuserinput(), and rflu_printuserinput().
character(10) function inrt_printuserinput::nodestr (integer, intent(in) ind)
Definition at line 258 of file INRT_PrintUserInput.F90.
References moderror::errorstop().
Referenced by inrt_printuserinput().
character(1) function inrt_printuserinput::permstr (integer, intent(in) perm)
Definition at line 284 of file INRT_PrintUserInput.F90.
References moderror::errorstop().
Referenced by inrt_printuserinput().
character(5) function inrt_printuserinput::tedgestr (integer, intent(in) tEdge)
Definition at line 309 of file INRT_PrintUserInput.F90.
References moderror::errorstop().
Referenced by inrt_printuserinput().