Rocstar: INRT_SetPermission.F90 File Reference
INRT_SetPermission.F90 File Reference
Functions/Subroutines
subroutine inrt_setpermission (global, val, perm)
Function/Subroutine Documentation
subroutine inrt_setpermission (type(t_global), pointer global, real(rfreal), intent(in) val, integer, intent(out) perm)
Definition at line 42 of file INRT_SetPermission.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by inrt_readburning(), inrt_readdefaultsection(), inrt_readdrag(), inrt_readheattransfernonburn(), and inrt_readscouring().