Rocstar: INRT_DefineScouring.F90 File Reference
INRT_DefineScouring.F90 File Reference
Functions/Subroutines
subroutine inrt_definescouring (region)
Function/Subroutine Documentation
subroutine inrt_definescouring (type(t_region), intent(inout) region)
Definition at line 57 of file INRT_DefineScouring.F90.
References moderror::deregisterfunction(), moderror::errorstop(), rflu_modrepair3d::input(), inrt_allocateauxillary(), Mesh::GenericCell_2::nedges(), and moderror::registerfunction().
Referenced by inrt_readscouring().