Rocstar: INRT_ReadMaterialInput.F90 File Reference
INRT_ReadMaterialInput.F90 File Reference
Functions/Subroutines
subroutine inrt_readmaterialinput (global)
Function/Subroutine Documentation
subroutine inrt_readmaterialinput (type(t_global), pointer global)
Definition at line 44 of file INRT_ReadMaterialInput.F90.
References buildfilenameplain(), moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, CImg< T >::line(), modinterfacesio::ReadBothSection::readbothsection(), moderror::registerfunction(), and Attribute::status().
Referenced by readinputfile().