Rocstar: INRT_SetMaterial.F90 File Reference
INRT_SetMaterial.F90 File Reference
Functions/Subroutines
subroutine inrt_setmaterial (global, material, name)
Function/Subroutine Documentation
subroutine inrt_setmaterial (type(t_global), pointer global, type(t_material), pointer material, character(*), intent(in) name)
Definition at line 43 of file INRT_SetMaterial.F90.
References moderror::deregisterfunction(), moderror::errorstop(), Attribute::name(), and moderror::registerfunction().
Referenced by inrt_readboilingregulation(), inrt_readburning(), peul_readconpartptypesection(), peul_readconpartsection(), plag_readdispartncontsection(), and spec_readspectypesection().