Rocstar: INRT_DetermineTokens.F90 File Reference
INRT_DetermineTokens.F90 File Reference
Functions/Subroutines
subroutine inrt_determinetokens (region, inrt)
Function/Subroutine Documentation
subroutine inrt_determinetokens (type(t_region), intent(inout) region, type(t_inrt_interact), pointer inrt)
Definition at line 49 of file INRT_DetermineTokens.F90.
References moderror::deregisterfunction(), rflu_modrepair3d::input(), min(), and moderror::registerfunction().
Referenced by inrt_readburning(), inrt_readdrag(), inrt_readheattransfernonburn(), and inrt_readscouring().