Rocstar: INRT_AugmentConSources.F90 File Reference
INRT_AugmentConSources.F90 File Reference
Functions/Subroutines
subroutine inrt_augmentconsources (region, iInrt)
Function/Subroutine Documentation
subroutine inrt_augmentconsources (type(t_region), intent(inout) region, integer, intent(in) iInrt)
Definition at line 47 of file INRT_AugmentConSources.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by inrt_sourceterms().