Rocstar: modinterfacesio::ReadBothRegionSection Interface Reference
modinterfacesio::ReadBothRegionSection Interface Reference
Public Member Functions
subroutine readbothregionsection (global, fileID, nvals, nStrVals, keys, strKeys, vals, strVals, brbeg, brend, defined, strDefined)
Detailed Description
Definition at line 56 of file ModInterfacesIO.F90.
Member Function/Subroutine Documentation
subroutine readbothregionsection (type(t_global), pointer global, integer fileID, integer nvals, integer nStrVals, character(*), dimension(nvals) keys, character(*), dimension(nstrvals) strKeys, real(rfreal), dimension(nvals) vals, character(*), dimension(nstrvals) strVals, integer brbeg, integer brend, logical, dimension(nvals) defined, logical, dimension(nstrvals) strDefined)
Definition at line 56 of file ModInterfacesIO.F90.
References brbeg.
Referenced by inrt_readboilingregulation(), inrt_readburning(), and peul_readconpartsection().
The documentation for this interface was generated from the following file:
ModInterfacesIO.F90