Rocstar: modinterfacesio::ReadSection Interface Reference
modinterfacesio::ReadSection Interface Reference
Public Member Functions
subroutine readsection (global, fileID, nvals, keys, vals, defined)
Detailed Description
Definition at line 232 of file ModInterfacesIO.F90.
Member Function/Subroutine Documentation
subroutine readsection (type(t_global), pointer global, integer fileID, integer nvals, character(*), dimension(nvals) keys, real(rfreal), dimension(nvals) vals, logical, dimension(nvals) defined)
Definition at line 232 of file ModInterfacesIO.F90.
Referenced by inrt_readdefaultsection(), inrt_readdrag(), inrt_readheattransfernonburn(), inrt_readscouring(), peri_readperisection(), plag_readdispartinitsection(), plag_readdispartsection(), readaccelerationsection(), readflowsection(), readforcessection(), readformatssection(), readinitflowsection(), readmixturesection(), readmultigridsection(), readnumericssection(), readpostsection(), readprepsection(), readprobesection(), readrandomsection(), readreferencesection(), readrocketsection(), readthrustsection(), readtimestepsection(), readtimezoomingsection(), readtransformsection(), readviscositysection(), rflo_readregionmapsection(), rvav_readsectionstream1(), rvav_readsectionstream2(), spec_readspecsection(), spec_readspectypesection(), and turb_readturbsection().
The documentation for this interface was generated from the following file:
ModInterfacesIO.F90