Rocstar: modinterfacesio::ReadBothSection Interface Reference
modinterfacesio::ReadBothSection Interface Reference
Public Member Functions
subroutine readbothsection (global, fileID, nvals, nStrVals, keys, strKeys, vals, strVals, defined, strDefined)
Detailed Description
Definition at line 69 of file ModInterfacesIO.F90.
Member Function/Subroutine Documentation
subroutine readbothsection (type(t_global), pointer global, integer fileID, integer nvals, integer nStrVals, character(*), dimension(nvals) keys, character(*), dimension(nstrvals) strKeys, real(rfreal), dimension(nvals) vals, character(*), dimension(nstrvals) strVals, logical, dimension(nvals) defined, logical, dimension(nstrvals) strDefined)
Definition at line 69 of file ModInterfacesIO.F90.
Referenced by inrt_readboilingregulation(), inrt_readburning(), inrt_readmaterialinput(), peul_readconpartptypesection(), and spec_readspectypesection().
The documentation for this interface was generated from the following file:
ModInterfacesIO.F90