Rocstar: IntLoad.f90 File Reference
IntLoad.f90 File Reference
Functions/Subroutines
subroutine intload (ndim, nrows, nnz, nstart, rp, cval, aval, tempin, rint)
Function/Subroutine Documentation
subroutine intload (integer ndim, integer nrows, integer nnz, integer nstart, integer, dimension(nrows+1) rp, integer, dimension(nnz) cval, real(kind=wp), dimension(nnz) aval, real(kind=wp), dimension(nrows) tempin, real(kind=wp), dimension(nrows) rint)
Definition at line 30 of file IntLoad.f90.
References comp_row_vecmult(), i, j, and Aff_transformation_2< R_ >::m().
Referenced by thermal_soln().