Rocstar: io.h File Reference
io.h File Reference
#include <iostream>
#include <CGAL/IO/io_tags.h>
#include <CGAL/IO/Color.h>
#include <CGAL/Object.h>
Classes
class IO
Functions
IO::Mode get_mode (std::ios &i)
IO::Mode set_ascii_mode (std::ios &i)
IO::Mode set_binary_mode (std::ios &i)
IO::Mode set_pretty_mode (std::ios &i)
IO::Mode set_mode (std::ios &i, IO::Mode m)
bool is_pretty (std::ios &i)
bool is_ascii (std::ios &i)
bool is_binary (std::ios &i)
io_Read_write io_tag (char)
template<class T >
void write (std::ostream &os, const T &t, const io_Read_write &)
template<class T >
void write (std::ostream &os, const T &t, const io_Operator &)
template<class T >
void write (std::ostream &os, const T &t, const io_Extract_insert &)
template<class T >
void write (std::ostream &os, const T &t)
template<class T >
void read (std::istream &is, T &t, const io_Read_write &)
template<class T >
void read (std::istream &is, T &t, const io_Operator &)
template<class T >
void read (std::istream &is, T &t, const io_Extract_insert &)
template<class T >
void read (std::istream &is, T &t)
std::ostream & operator<< (std::ostream &out, const Color &col)
std::istream & operator>> (std::istream &is, Color &col)
Function Documentation
IO::Mode get_mode (std::ios & i)
Definition at line 64 of file io.C.
References IO::mode.
Referenced by set_ascii_mode(), set_binary_mode(), set_mode(), and set_pretty_mode().
 {
     return static_cast<IO::Mode>(i.iword(IO::mode));
 }
io_Read_write io_tag (char) inline
Definition at line 90 of file io.h.
 { return io_Read_write(); }
bool is_ascii (std::ios & i)
Definition at line 111 of file io.C.
References IO::ASCII, and IO::mode.
 {
     return i.iword(IO::mode) == IO::ASCII;
 }
bool is_binary (std::ios & i)
Definition at line 118 of file io.C.
References IO::BINARY, and IO::mode.
 {
     return i.iword(IO::mode) == IO::BINARY;
 }
bool is_pretty (std::ios & i)
Definition at line 105 of file io.C.
References IO::mode, and IO::PRETTY.
 {
     return i.iword(IO::mode) == IO::PRETTY;
 }
std::ostream& operator<< (std::ostream & out, const Color & col) inline
Definition at line 166 of file io.h.
References IO::ASCII, IO::BINARY, Color::blue(), Color::green(), IO::mode, Color::red(), and write().
 {
     switch(out.iword(IO::mode)) {
     case IO::ASCII :
         return out << static_cast<int>(col.red())   << ' '
                    << static_cast<int>(col.green()) << ' '
                    << static_cast<int>(col.blue());
     case IO::BINARY :
         write(out, static_cast<int>(col.red()));
         write(out, static_cast<int>(col.green()));
         write(out, static_cast<int>(col.blue()));
         return out;
     default:
         return out << "Color(" << static_cast<int>(col.red()) << ", "
                    << static_cast<int>(col.green()) << ", "
                    << static_cast<int>(col.blue()) << ')';
     }
 }
std::istream& operator>> (std::istream & is, Color & col) inline
Definition at line 186 of file io.h.
References IO::ASCII, IO::BINARY, IO::mode, and read().
 {
     int r, g, b;
     switch(is.iword(IO::mode)) {
     case IO::ASCII :
         is >> r >> g >> b;
         break;
     case IO::BINARY :
         read(is, r);
         read(is, g);
         read(is, b);
         break;
     default:
         std::cerr << "" << std::endl;
         std::cerr << "Stream must be in ascii or binary mode" << std::endl;
         break;
     }
     col = Color(r,g,b);
     return is;
 }
void read (std::istream & is, T & t, const io_Read_write &) inline
Definition at line 132 of file io.h.
Referenced by operator>>(), tpz_ordered::parse_data(), tpz_fequad::parse_data(), read(), and RFC_Pane_base::read_binary().
 {
     is.read((char*)&t, sizeof(t));
 }
void read (std::istream & is, T & t, const io_Operator &) inline
Definition at line 141 of file io.h.
 {
     is >> t;
 }
void read (std::istream & is, T & t, const io_Extract_insert &) inline
Definition at line 150 of file io.h.
 {
     extract(is, t);
 }
void read (std::istream & is, T & t) inline
Definition at line 159 of file io.h.
References io_tag(), and read().
 {
     read(is, t, io_tag(t));
 }
IO::Mode set_ascii_mode (std::ios & i)
Definition at line 70 of file io.C.
References IO::ASCII, get_mode(), and IO::mode.
Referenced by Overlay::write_inodes_tec(), Overlay::write_inodes_vec(), Overlay::write_overlay_off(), and RFC_Pane_base::write_tec_ascii().
 {
     IO::Mode m = get_mode(i);
     i.iword(IO::mode) = IO::ASCII;
     return m;
 }
IO::Mode set_binary_mode (std::ios & i)
Definition at line 79 of file io.C.
References IO::BINARY, get_mode(), and IO::mode.
 {
     IO::Mode m = get_mode(i);
     i.iword(IO::mode) = IO::BINARY;
     return m;
 }
IO::Mode set_mode (std::ios & i, IO::Mode m)
Definition at line 97 of file io.C.
References get_mode(), and IO::mode.
 {
     IO::Mode old = get_mode(i);
     i.iword(IO::mode) = m;
     return old;
 }
IO::Mode set_pretty_mode (std::ios & i)
Definition at line 88 of file io.C.
References get_mode(), IO::mode, and IO::PRETTY.
 {
     IO::Mode m = get_mode(i);
     i.iword(IO::mode) = IO::PRETTY;
     return m;
 }
void write (std::ostream & os, const T & t, const io_Read_write &) inline
Definition at line 96 of file io.h.
Referenced by operator<<(), write(), and RFC_Pane_base::write_binary().
 {
     os.write((char*)&t, sizeof(t));
 }
void write (std::ostream & os, const T & t, const io_Operator &) inline
Definition at line 105 of file io.h.
 {
     os << t;
 }
void write (std::ostream & os, const T & t, const io_Extract_insert &) inline
Definition at line 114 of file io.h.
 {
     insert(os, t);
 }
void write (std::ostream & os, const T & t) inline
Definition at line 123 of file io.h.
References io_tag(), and write().
 {
     write(os, t, io_tag(t));
 }