Rocstar: io.C File Reference
io.C File Reference
#include <CGAL/basic.h>
#include <CGAL/IO/io.h>
Macros
#define CGAL_IO_C
Functions
IO::Mode get_mode (std::ios &i)
IO::Mode set_ascii_mode (std::ios &i)
IO::Mode set_binary_mode (std::ios &i)
IO::Mode set_pretty_mode (std::ios &i)
IO::Mode set_mode (std::ios &i, IO::Mode m)
bool is_pretty (std::ios &i)
bool is_ascii (std::ios &i)
bool is_binary (std::ios &i)
Macro Definition Documentation
#define CGAL_IO_C
Definition at line 53 of file io.C.
Function Documentation
IO::Mode get_mode (std::ios & i)
Definition at line 64 of file io.C.
References IO::mode.
Referenced by set_ascii_mode(), set_binary_mode(), set_mode(), and set_pretty_mode().
 {
     return static_cast<IO::Mode>(i.iword(IO::mode));
 }
bool is_ascii (std::ios & i)
Definition at line 111 of file io.C.
References IO::ASCII, and IO::mode.
 {
     return i.iword(IO::mode) == IO::ASCII;
 }
bool is_binary (std::ios & i)
Definition at line 118 of file io.C.
References IO::BINARY, and IO::mode.
 {
     return i.iword(IO::mode) == IO::BINARY;
 }
bool is_pretty (std::ios & i)
Definition at line 105 of file io.C.
References IO::mode, and IO::PRETTY.
 {
     return i.iword(IO::mode) == IO::PRETTY;
 }
IO::Mode set_ascii_mode (std::ios & i)
Definition at line 70 of file io.C.
References IO::ASCII, get_mode(), and IO::mode.
Referenced by Overlay::write_inodes_tec(), Overlay::write_inodes_vec(), Overlay::write_overlay_off(), and RFC_Pane_base::write_tec_ascii().
 {
     IO::Mode m = get_mode(i);
     i.iword(IO::mode) = IO::ASCII;
     return m;
 }
IO::Mode set_binary_mode (std::ios & i)
Definition at line 79 of file io.C.
References IO::BINARY, get_mode(), and IO::mode.
 {
     IO::Mode m = get_mode(i);
     i.iword(IO::mode) = IO::BINARY;
     return m;
 }
IO::Mode set_mode (std::ios & i, IO::Mode m)
Definition at line 97 of file io.C.
References get_mode(), and IO::mode.
 {
     IO::Mode old = get_mode(i);
     i.iword(IO::mode) = m;
     return old;
 }
IO::Mode set_pretty_mode (std::ios & i)
Definition at line 88 of file io.C.
References get_mode(), IO::mode, and IO::PRETTY.
 {
     IO::Mode m = get_mode(i);
     i.iword(IO::mode) = IO::PRETTY;
     return m;
 }