Rocstar: KtInitCRS.f90 File Reference
KtInitCRS.f90 File Reference
Functions/Subroutines
subroutine ktnumnnz (NumNp, NumEl, ElConnVol, nnz)
subroutine ktinitcrs (NumNp, NumEl, ElConnVol, nnz, rp, cval, aval)
Function/Subroutine Documentation
subroutine ktinitcrs (integer NumNp, integer NumEl, integer, dimension(1:8,1:numel) ElConnVol, integer nnz, integer, dimension(1:gnumnp+1) rp, integer, dimension(1:nnz) cval, integer, dimension(1:nnz) aval)
Definition at line 146 of file KtInitCRS.f90.
References i, j, k, and Aff_transformation_2< R_ >::m().
Referenced by locthermstiff_v3d8().
subroutine ktnumnnz (integer NumNp, integer NumEl, integer, dimension(1:8,1:numel) ElConnVol, integer nnz)
Definition at line 26 of file KtInitCRS.f90.
References i, j, k, and Aff_transformation_2< R_ >::m().
Referenced by locthermstiff_v3d8().