Rocstar: Line_2_Line_2_intersection.h File Reference
Line_2_Line_2_intersection.h File Reference
#include <CGAL/Line_2.h>
#include <CGAL/Point_2.h>
#include <CGAL/utils.h>
#include <CGAL/number_utils.h>
#include <CGAL/Object.h>
Classes
class Line_2_Line_2_pair< R >
Functions
template<class R >
bool do_intersect (const Line_2< R > &p1, const Line_2< R > &p2)
template<class R >
CGAL_END_NAMESPACE
CGAL_BEGIN_NAMESPACE Object intersection (const Line_2< R > &line1, const Line_2< R > &line2)
template<class R , class POINT , class RT >
CGAL_END_NAMESPACE
CGAL_BEGIN_NAMESPACE bool construct_if_finite (POINT &pt, RT x, RT y, RT w, R &)
Function Documentation
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE bool construct_if_finite (POINT & pt, RT x, RT y, RT w, R &)
Definition at line 165 of file Line_2_Line_2_intersection.h.
References CGAL_kernel_precondition, and is_finite().
Referenced by Line_2_Line_2_pair< R >::intersection_type().
 {
     typedef typename R::FT FT;
     CGAL_kernel_precondition(::CGAL::is_finite(x)
                              && ::CGAL::is_finite(y)
                              && w != RT(0));
     if (!::CGAL::is_finite(FT(x)/FT(w)) || !::CGAL::is_finite(FT(y)/FT(w)))
         return false;
     pt = POINT(x, y, w);
     return true;
 }
bool do_intersect (const Line_2< R > & p1, const Line_2< R > & p2) inline
Definition at line 123 of file Line_2_Line_2_intersection.h.
Referenced by Overlay::intersect_link_helper().
 {
     typedef Line_2_Line_2_pair<R> pair_t;
     pair_t pair(&p1, &p2);
     return pair.intersection_type() != pair_t::NO;
 }
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE Object intersection (const Line_2< R > & line1, const Line_2< R > & line2)
Definition at line 140 of file Line_2_Line_2_intersection.h.
Referenced by main(), and Intersect::operator()().
 {
     typedef Line_2_Line_2_pair<R> is_t;
     is_t linepair(&line1, &line2);
     switch (linepair.intersection_type()) {
     case is_t::NO:
     default:
         return Object();
     case is_t::POINT: {
         Point_2<R> pt;
         linepair.intersection(pt);
         return Object(new Wrapper< Point_2<R> >(pt));
     }
     case is_t::LINE:
         return Object(new Wrapper< Line_2<R> >(line1));
     }
 }