Rocstar: LocThermStiff_v3d8.f90 File Reference
LocThermStiff_v3d8.f90 File Reference
Functions/Subroutines
subroutine locthermstiff_v3d8 (coor, ElConnVol, dmat, numnp, NumEL, MatType, NumMatType)
Function/Subroutine Documentation
subroutine locthermstiff_v3d8 (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:8,1:numel) ElConnVol, real*8, dimension(3,3) dmat, integer numnp, integer NumEL, integer, dimension(1:numel) MatType, integer NumMatType)
Definition at line 30 of file LocThermStiff_v3d8.f90.
References coord, Polyhedron_incremental_builder_3< HDS >::error(), get_jacobien(), get_shape(), i, j, k, ktinitcrs(), ktnumnnz(), Aff_transformation_2< R_ >::m(), and Aff_transformation_repS2< FT >::print().
Referenced by glbthermstiff().