Rocstar: LocThermCap_v3d8.f90 File Reference
LocThermCap_v3d8.f90 File Reference
Functions/Subroutines
subroutine locthermcap_v3d8 (NumEl, NumNP, NumMat, coor, nodes, MatType, ri, rho, cap, ElConnVol)
Function/Subroutine Documentation
subroutine locthermcap_v3d8 (integer NumEl, integer NumNP, integer NumMat, real(kind=wp), dimension(1:3,1:numnp) coor, integer, dimension(1:8,1:numel) nodes, integer, dimension(1:numel) MatType, real(kind=wp), dimension(1:3,1:8) ri, real(kind=wp), dimension(1:nummat) rho, real(kind=wp), dimension(1:nummat) cap, integer, dimension(1:8,1:numel) ElConnVol)
Definition at line 32 of file LocThermCap_v3d8.f90.
References Polyhedron_incremental_builder_3< HDS >::error(), get_jacobien(), get_shape(), i, j, k, n, and Aff_transformation_repS2< FT >::print().
Referenced by glbthermcap().