Rocstar: main.F90 File Reference
main.F90 File Reference
Functions/Subroutines
program rflucells
Function/Subroutine Documentation
program rflucells ()
Definition at line 46 of file main.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_allocatememorywrapper(), rflu_builddatastruct(), rflu_modfacelist::rflu_buildfacelist(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modfacelist::rflu_createfacelist(), rflu_deallocatememorywrapper(), rflu_getspecialcells(), rflu_getuserinput(), rflu_initglobal(), rflu_printgridinfo(), rflu_printheader(), rflu_moddimensions::rflu_readdimensions(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_modinterfacesutilities::RFLU_ReadInputFile::rflu_readinputfile(), rflu_writespecialcells(), rflu_writeversionstring(), and StopWatch::stop().