Rocstar: MakeNumberedKeys.F90 File Reference
MakeNumberedKeys.F90 File Reference
Functions/Subroutines
subroutine makenumberedkeys (keys, indBegin, string, numBegin, numEnd, numSkip)
Function/Subroutine Documentation
subroutine makenumberedkeys (character(*), dimension(:) keys, integer, intent(in) indBegin, character(*), intent(in) string, integer, intent(in) numBegin, integer, intent(in) numEnd, integer, intent(in) numSkip)
Definition at line 48 of file MakeNumberedKeys.F90.
References type< T >::string().
Referenced by inrt_printuserinput(), inrt_readburning(), inrt_readdefaultsection(), inrt_readscouring(), peul_readbcfarfsection(), peul_readbcinflowsection(), peul_readbcinjectsection(), spec_rflu_readbcfarfsection(), spec_rflu_readbcinflowsection(), spec_rflu_readbcinjectsection(), and spec_rflu_readbcsectiondummy().