Rocstar: Manifold_2.h File Reference
Manifold_2.h File Reference
#include "surfbasic.h"
#include "../Rocmap/include/Simple_manifold_2.h"
Classes
class Pane_manifold_2
This class implements a data structure for 2-manifold on each pane.
class Window_manifold_2
This class implements a data structure for 2-manifold over a whole window, which can be composed of multiple panes.
class Node
This class encapsulate a node over a window manifold.
class Halfedge
This class encapsulate a halfedge over a window manifold.
Namespaces
MAP
Typedefs
typedef MAP::Facet_ID Edge_ID
Enumerations
enum Access_Mode { REAL_PANE, WHOLE_PANE, ACROSS_PANE }
Functions
Vector_3< Real > get_normal (const Halfedge &h, const Vector_2< Real > &nc)
Get the face normal of a point in the element incident on h.
Vector_3< Real > get_deformed_normal (const Halfedge &h, const Vector_2< Real > &nc, const COM::Attribute *disp)
Get the normal of the deformed shape (coordinates plus given displacements) of the incident facet of a halfedge.
Vector_3< Real > get_tangent (const Halfedge &h)
Get the tangent of the given halfedge.
Typedef Documentation
typedef MAP::Facet_ID Edge_ID
Definition at line 49 of file Manifold_2.h.
Enumeration Type Documentation
enum Access_Mode
Enumerator
REAL_PANE
WHOLE_PANE
ACROSS_PANE
Definition at line 52 of file Manifold_2.h.
 { REAL_PANE, WHOLE_PANE, ACROSS_PANE };
Function Documentation
Vector_3<Real> get_deformed_normal (const Halfedge & h, const Vector_2< Real > & nc, const COM::Attribute * disp)
Get the normal of the deformed shape (coordinates plus given displacements) of the incident facet of a halfedge.
Definition at line 1263 of file Manifold_2.C.
References Node::addr(), COM_assertion, COM_assertion_msg, Vector_3< Type >::cross_product(), Generic_element_2::Jacobian(), Halfedge::next(), Halfedge::origin(), Node::point(), and v.
Referenced by Halfedge::deformed_normal().
 {
   COM_assertion_msg( disp, "Unexpected NULL pointer");
   COM_assertion_msg( disp->is_nodal(), "disp must be nodal attribute");
   // Obtain the deformed coordinates
   Point_3<Real> points[4];
   int ne = 0;
   Halfedge hit = h;
   do {
     Node v=hit.origin();
     points[ne] = v.point() + *(Vector_3<Real>*)v.addr( disp);
     ++ne;
     COM_assertion( ne<=4);
   } while ( (hit=hit.next()) != h);
   // Evaluate the Jacobian and the cross product
   Vector_3<Real> J[2];
   Generic_element_2(ne).Jacobian( points, nc, J);
   return Vector_3<Real>::cross_product( J[0], J[1]);
 }
Vector_3<Real> get_normal (const Halfedge & h, const Vector_2< Real > & nc)
Get the face normal of a point in the element incident on h.
Definition at line 1240 of file Manifold_2.C.
References Vector_3< Type >::cross_product(), Pane_manifold_2::get_bd_normal(), Halfedge::id(), Halfedge::is_border(), Generic_element_2::Jacobian(), Halfedge::pane(), Halfedge::pane_manifold(), Element_node_vectors_k_const< Value >::set(), and Element_node_enumerator::size_of_edges().
Referenced by Halfedge::normal().
{
   if ( h.is_border()) {
     // Precondition: boundary normal must have been updated.
     return h.pane_manifold()->get_bd_normal( h.id());
   }
   Element_node_enumerator ene( h.pane(), h.id().eid());
   const int ne = ene.size_of_edges();
   Generic_element_2 e(ne);
   // First evaluate face normal
   Element_node_vectors_k_const<Point_3<Real> > ps;
   ps.set((const Point_3<Real>*)(h.pane()->coordinates()), ene,1);
   Vector_3<Real> J[2];
   e.Jacobian( ps, nc, J);
   return Vector_3<Real>::cross_product( J[0], J[1]);
 }
Vector_3<Real> get_tangent (const Halfedge & h) inline
Get the tangent of the given halfedge.
Definition at line 704 of file Manifold_2.h.
References Halfedge::tangent().
Referenced by RFC_Window_overlay::cos_edge_angle(), and RFC_Window_overlay::detect_features().
 { return h.tangent(); }