Rocstar: Matous_Const_Model.f90 File Reference
Matous_Const_Model.f90 File Reference
Functions/Subroutines
subroutine matous_const_model (cd, cb, p1, p2, Yin, SoftParam, Km, K2, Gm, G2, vm, nu2, a_eta, a_zeta, cm, c2, Lo, Lm, L2, Mm, M2, L_bar, strain, DelStrain, s11, s22, s33, s12, s13, s23, ielem)
Function/Subroutine Documentation
subroutine matous_const_model (real(kind=wp) cd, real(kind=wp) cb, real(kind=wp) p1, real(kind=wp) p2, real(kind=wp) Yin, real(kind=wp) SoftParam, real(kind=wp) Km, real(kind=wp) K2, real(kind=wp) Gm, real(kind=wp) G2, real(kind=wp) vm, real(kind=wp) nu2, real(kind=wp) a_eta, real(kind=wp) a_zeta, real(kind=wp) cm, real(kind=wp) c2, real(kind=wp), dimension(1:6,1:6) Lo, real(kind=wp), dimension(1:6,1:6) Lm, real(kind=wp), dimension(1:6,1:6) L2, real(kind=wp), dimension(1:6,1:6) Mm, real(kind=wp), dimension(1:6,1:6) M2, real(kind=wp), dimension(1:6,1:6) L_bar, real(kind=wp), dimension(1:6) strain, real(kind=wp), dimension(1:6) DelStrain, real(kind=wp) s11, real(kind=wp) s22, real(kind=wp) s33, real(kind=wp) s12, real(kind=wp) s13, real(kind=wp) s23, integer ielem)
Definition at line 53 of file Matous_Const_Model.f90.
References a_d_tensors(), operatorj(), Aff_transformation_repS2< FT >::print(), Color::r(), sqrt(), StopWatch::stop(), vecmatvecmul(), and y.
Referenced by v3d10_nl_matous().