Rocstar: MixtLiq_C.F90 File Reference
MixtLiq_C.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtliq_c_bp (Bp)
real(rfreal) function mixtliq_c2_bp (Bp)
Function/Subroutine Documentation
real(rfreal) function mixtliq_c2_bp (real(rfreal), intent(in) Bp)
Definition at line 54 of file MixtLiq_C.F90.
Referenced by bcondinflowperf_gl(), bcondoutflowperf_gl(), rflu_centralsecondpatch_gl(), rflu_checkpositivity_gl(), rflu_checkvalidity_gl(), rflu_computevertexvariables(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux2_gl(), and rflu_setdependentvars().
real(rfreal) function mixtliq_c_bp (real(rfreal), intent(in) Bp)
Definition at line 39 of file MixtLiq_C.F90.
References sqrt().