Rocstar: MixtPerf_C.F90 File Reference
MixtPerf_C.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtperf_c_co2guvw (Co2, G, U, V, W)
real(rfreal) function mixtperf_c_dgp (D, G, P)
real(rfreal) function mixtperf_c_ghovm2 (G, Ho, Vm2)
real(rfreal) function mixtperf_c_grt (G, R, T)
real(rfreal) function mixtperf_c2_grt (G, R, T)
real(rfreal) function mixtperf_co2_cguvw (C, G, U, V, W)
Function/Subroutine Documentation
real(rfreal) function mixtperf_c2_grt (real(rfreal), intent(in) G, real(rfreal), intent(in) R, real(rfreal), intent(in) T)
Definition at line 101 of file MixtPerf_C.F90.
References Color::g(), and Color::r().
Referenced by bcondinflowperf(), bcondinflowperf_gl(), bcondoutflowperf_gl(), rflu_centralsecondpatch_gl(), rflu_checkpositivity_gl(), rflu_checkvalidity_gl(), rflu_computevertexvariables(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux2_gl(), and rflu_setdependentvars().
real(rfreal) function mixtperf_c_co2guvw (real(rfreal), intent(in) Co2, real(rfreal), intent(in) G, real(rfreal), intent(in) U, real(rfreal), intent(in) V, real(rfreal), intent(in) W)
Definition at line 40 of file MixtPerf_C.F90.
References Color::g(), sqrt(), and v.
Referenced by bcondinflowperf().
real(rfreal) function mixtperf_c_dgp (real(rfreal), intent(in) D, real(rfreal), intent(in) G, real(rfreal), intent(in) P)
Definition at line 56 of file MixtPerf_C.F90.
References Plane_3< R, T >::d(), Color::g(), and sqrt().
Referenced by bcondfarfieldperf(), bcondinflowperf(), bcondoutflowperf(), rflo_modboundaryconditions::rflo_bcondinflowvpperf(), rflo_modboundaryconditions::rflo_bcondinflowvtperf(), rflo_modboundaryconditions::rflo_bcondoutflowperf(), rflu_computevertexvariables(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_initbcdatahardcode(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), and rflu_modrindstates::rflu_setrindstateslipwallperf().
real(rfreal) function mixtperf_c_ghovm2 (real(rfreal), intent(in) G, real(rfreal), intent(in) Ho, real(rfreal), intent(in) Vm2)
Definition at line 71 of file MixtPerf_C.F90.
References Color::g(), and sqrt().
Referenced by rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modroeflux::rflu_roe_computeflux1_tcp(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxd1_tcp(), and rflu_modroeflux::rflu_roe_computefluxd2_tcp().
real(rfreal) function mixtperf_c_grt (real(rfreal), intent(in) G, real(rfreal), intent(in) R, real(rfreal), intent(in) T)
Definition at line 86 of file MixtPerf_C.F90.
References Color::g(), Color::r(), and sqrt().
Referenced by bcondfarfieldperf(), bcondinflowperf(), perfgasdependentvars(), rflo_modboundaryconditions::rflo_bcondinflowvpperf(), rflo_modboundaryconditions::rflo_bcondinflowvtperf(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modboundxvutils::rflu_bxv_setdependentvarspatch(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_computevertexvariables(), rflu_setdependentvars(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_timestepinviscid(), and rflu_timestepviscous().
real(rfreal) function mixtperf_co2_cguvw (real(rfreal), intent(in) C, real(rfreal), intent(in) G, real(rfreal), intent(in) U, real(rfreal), intent(in) V, real(rfreal), intent(in) W)
Definition at line 116 of file MixtPerf_C.F90.
References Line_2< R, T >::c(), Color::g(), and v.
Referenced by bcondinflowperf().