Rocstar: MixtPerf_R.F90 File Reference
MixtPerf_R.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtperf_r_cpg (Cp, G)
real(rfreal) function mixtperf_r_m (M)
Function/Subroutine Documentation
real(rfreal) function mixtperf_r_cpg (real(rfreal), intent(in) Cp, real(rfreal), intent(in) G)
Definition at line 39 of file MixtPerf_R.F90.
References Color::g().
Referenced by perfgasgasvars(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch_gl(), rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_initbcdatahardcode(), rflu_initflowhardcode(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_setgasvars(), and spec_rflu_sourceterms_gl().
real(rfreal) function mixtperf_r_m (real(rfreal), intent(in) M)
Definition at line 54 of file MixtPerf_R.F90.
References Aff_transformation_2< R_ >::m().
Referenced by bcondfarfieldperf(), bcondinflowperf(), bcondinjectionperf(), bcondoutflowperf(), inrt_vaporenergyconversion(), perfgasdependentvars(), peri_cocprslowterms(), plag_rflu_correctmixtproperties(), rflo_modboundaryconditions::rflo_bcondinflowvpperf(), rflo_modboundaryconditions::rflo_bcondinflowvtperf(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflowperf(), rflo_checkvalidity(), rflo_correctcorneredgecells(), rflo_sendboundaryvalues(), rflo_sendboundaryvaluesalpha(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modboundxvutils::rflu_bxv_compenergypatch(), rflu_modboundxvutils::rflu_bxv_compmomenergypatch(), rflu_modboundconvertcv::rflu_bxv_convertcvcons2prim(), rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_modboundxvutils::rflu_bxv_setdependentvarspatch(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_checkpositivity(), rflu_checkpositivity_gl(), rflu_checkvalidity(), rflu_checkvalidity_gl(), rflu_computevertexvariables(), rflu_modconvertcv::rflu_convertcvcons2prim(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_initflowhardcode(), rflu_initflowhardcodelim(), rflu_initflowscratch(), rflu_modnscbc::rflu_nscbc_comprhsff(), rflu_modnscbc::rflu_nscbc_comprhsifveltemp(), rflu_modnscbc::rflu_nscbc_comprhsof(), rflu_modnscbc::rflu_nscbc_comprhssw(), rflu_modnscbc::rflu_nscbc_initff(), rflu_modnscbc::rflu_nscbc_initiftotang(), rflu_modnscbc::rflu_nscbc_initifveltemp(), rflu_modnscbc::rflu_nscbc_initof(), rflu_modnscbc::rflu_nscbc_initsw(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_setdependentvars(), rflu_setgasvars(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_modrindstates::rflu_setrindstateinjectperf(), rflu_modrindstates::rflu_setrindstateslipwallperf(), rflu_timestepinviscid(), rflu_timestepviscous(), spec_checkuserinput(), spec_rflu_modchemistry::spec_rflu_integratechemsrcterm(), spec_rflu_sourceterms_gl(), turb_flucv2cons(), and turb_flucv2prim().