Rocstar: MixtPerf_D.F90 File Reference
MixtPerf_D.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtperf_d_cgp (C, G, P)
real(rfreal) function mixtperf_d_dogma (Do, G, Ma)
real(rfreal) function mixtperf_d_prt (P, R, T)
Function/Subroutine Documentation
real(rfreal) function mixtperf_d_cgp (real(rfreal), intent(in) C, real(rfreal), intent(in) G, real(rfreal), intent(in) P)
Definition at line 40 of file MixtPerf_D.F90.
References Line_2< R, T >::c(), and Color::g().
Referenced by rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), and rflu_initflowhardcode().
real(rfreal) function mixtperf_d_dogma (real(rfreal), intent(in) Do, real(rfreal), intent(in) G, real(rfreal), intent(in) Ma)
Definition at line 55 of file MixtPerf_D.F90.
References Color::g().
Referenced by rflu_modexactflow::rflu_computeexactflowssvortex().
real(rfreal) function mixtperf_d_prt (real(rfreal), intent(in) P, real(rfreal), intent(in) R, real(rfreal), intent(in) T)
Definition at line 71 of file MixtPerf_D.F90.
References Color::r().
Referenced by bcondfarfieldperf(), bcondinflowperf(), bcondinflowperf_gl(), bcondinjectionperf(), bcondoutflowperf_gl(), rflo_modboundaryconditions::rflo_bcondinflowvpperf(), rflo_modboundaryconditions::rflo_bcondinflowvtperf(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_correctcorneredgecells(), rflo_sendboundaryvalues(), rflo_sendboundaryvaluesalpha(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_computevertexvariables(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_initflowhardcode(), rflu_initflowscratch(), rflu_modnscbc::rflu_nscbc_initifveltemp(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_setdependentvars(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_modrindstates::rflu_setrindstateinjectperf(), spec_rflu_modchemistry::spec_rflu_integratechemsrcterm(), and spec_rflu_sourceterms_gl().