Rocstar: MixtPerf_Cv.F90 File Reference
MixtPerf_Cv.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtperf_cv_cpr (Cp, R)
Function/Subroutine Documentation
real(rfreal) function mixtperf_cv_cpr (real(rfreal), intent(in) Cp, real(rfreal), intent(in) R)
Definition at line 39 of file MixtPerf_Cv.F90.
References Color::r().
Referenced by rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch_gl(), rflu_checkpositivity_gl(), rflu_checkvalidity_gl(), rflu_computevertexvariables(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_initflowhardcode(), rflu_initflowscratch(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_setdependentvars(), and spec_rflu_sourceterms_gl().