Rocstar: MixtPerf_E.F90 File Reference
MixtPerf_E.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtperf_eo_dgpuvw (D, G, P, U, V, W)
real(rfreal) function mixtperf_eo_dgpvm (D, G, P, Vm)
real(rfreal) function mixtperf_eo_grtuvw (G, R, T, U, V, W)
Function/Subroutine Documentation
real(rfreal) function mixtperf_eo_dgpuvw (real(rfreal), intent(in) D, real(rfreal), intent(in) G, real(rfreal), intent(in) P, real(rfreal), intent(in) U, real(rfreal), intent(in) V, real(rfreal), intent(in) W)
Definition at line 40 of file MixtPerf_E.F90.
References Plane_3< R, T >::d(), Color::g(), and v.
Referenced by bcondfarfieldperf(), bcondinflowperf(), bcondinjectionperf(), bcondoutflowperf(), rflo_modboundaryconditions::rflo_bcondinflowvpperf(), rflo_modboundaryconditions::rflo_bcondinflowvtperf(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflowperf(), rflo_correctcorneredgecells(), rflu_modboundxvutils::rflu_bxv_compenergypatch(), rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_computeexactflowerror(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_initflowhardcode(), rflu_initflowhardcodelim(), rflu_initflowscratch(), rflu_modnscbc::rflu_nscbc_initff(), rflu_modnscbc::rflu_nscbc_initifveltemp(), rflu_modnscbc::rflu_nscbc_initof(), rflu_modnscbc::rflu_nscbc_initsw(), rflu_modroeflux::rflu_roe_computefluxc2_tcp(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), and turb_flucv2cons().
real(rfreal) function mixtperf_eo_dgpvm (real(rfreal), intent(in) D, real(rfreal), intent(in) G, real(rfreal), intent(in) P, real(rfreal), intent(in) Vm)
Definition at line 55 of file MixtPerf_E.F90.
References Plane_3< R, T >::d(), and Color::g().
Referenced by bcondfarfieldperf(), bcondinflowperf(), peri_cocnlinitsolution(), peri_cocprinitsolution(), and rflu_modrindstates::rflu_setrindstatefarfieldperf().
real(rfreal) function mixtperf_eo_grtuvw (real(rfreal), intent(in) G, real(rfreal), intent(in) R, real(rfreal), intent(in) T, real(rfreal), intent(in) U, real(rfreal), intent(in) V, real(rfreal), intent(in) W)
Definition at line 70 of file MixtPerf_E.F90.
References Color::g(), Color::r(), and v.
Referenced by rflu_modboundxvutils::rflu_bxv_compmomenergypatch(), and spec_rflu_modchemistry::spec_rflu_integratechemsrcterm().