Rocstar: MixtGasLiq_P.F90 File Reference
MixtGasLiq_P.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtgasliq_p (DYl, DYv, DYg, Cl2, Cv2, Cg2, D, Dz, Po, To, Bp, Bt, T)
Function/Subroutine Documentation
real(rfreal) function mixtgasliq_p (real(rfreal), intent(in) DYl, real(rfreal), intent(in) DYv, real(rfreal), intent(in) DYg, real(rfreal), intent(in) Cl2, real(rfreal), intent(in) Cv2, real(rfreal), intent(in) Cg2, real(rfreal), intent(in) D, real(rfreal), intent(in) Dz, real(rfreal), intent(in) Po, real(rfreal), intent(in) To, real(rfreal), intent(in) Bp, real(rfreal), intent(in) Bt, real(rfreal), intent(in) T)
Definition at line 40 of file MixtGasLiq_P.F90.
References Direction_3< R, T >::dz(), and sqrt().
Referenced by rflu_centralsecondpatch_gl(), rflu_checkpositivity_gl(), rflu_checkvalidity_gl(), rflu_computevertexvariables(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), and rflu_setdependentvars().