Rocstar: MixtGasLiq_C.F90 File Reference
MixtGasLiq_C.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtgasliq_c (Cvm, D, P, Dl, Dv, Dg, VFl, VFv, VFg, Cl2, Cv2, Cg2, Bl2, Bv2, Bg2)
Function/Subroutine Documentation
real(rfreal) function mixtgasliq_c (real(rfreal), intent(in) Cvm, real(rfreal), intent(in) D, real(rfreal), intent(in) P, real(rfreal), intent(in) Dl, real(rfreal), intent(in) Dv, real(rfreal), intent(in) Dg, real(rfreal), intent(in) VFl, real(rfreal), intent(in) VFv, real(rfreal), intent(in) VFg, real(rfreal), intent(in) Cl2, real(rfreal), intent(in) Cv2, real(rfreal), intent(in) Cg2, real(rfreal), intent(in) Bl2, real(rfreal), intent(in) Bv2, real(rfreal), intent(in) Bg2)
Definition at line 39 of file MixtGasLiq_C.F90.
References d, denom, and sqrt().
Referenced by bcondinflowperf_gl(), bcondoutflowperf_gl(), rflu_centralsecondpatch_gl(), rflu_computevertexvariables(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux2_gl(), and rflu_setdependentvars().