Rocstar: MixtPerf_P.F90 File Reference
MixtPerf_P.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtperf_p_deogvm2 (D, Eo, G, Vm2)
real(rfreal) function mixtperf_p_drt (D, R, T)
real(rfreal) function mixtperf_p_gmapo (G, Ma, Po)
real(rfreal) function mixtperf_p_ddogpo (D, Do, G, Po)
real(rfreal) function mixtperf_p_gpotto (G, Po, T, To)
real(rfreal) function mixtperf_po_gptto (G, P, T, To)
real(rfreal) function mixtperf_po_cgpuvw (C, G, P, U, V, W)
Function/Subroutine Documentation
real(rfreal) function mixtperf_p_ddogpo (real(rfreal), intent(in) D, real(rfreal), intent(in) Do, real(rfreal), intent(in) G, real(rfreal), intent(in) Po)
Definition at line 85 of file MixtPerf_P.F90.
References Plane_3< R, T >::d(), and Color::g().
Referenced by rflu_modexactflow::rflu_computeexactflowssvortex().
real(rfreal) function mixtperf_p_deogvm2 (real(rfreal), intent(in) D, real(rfreal), intent(in) Eo, real(rfreal), intent(in) G, real(rfreal), intent(in) Vm2)
Definition at line 39 of file MixtPerf_P.F90.
References Plane_3< R, T >::d(), and Color::g().
Referenced by bcondfarfieldperf(), bcondoutflowperf(), perfgasdependentvars(), rflo_modboundaryconditions::rflo_bcondoutflowperf(), rflo_checkvalidity(), rflu_modboundxvutils::rflu_bxv_setdependentvarspatch(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_checkpositivity(), rflu_checkvalidity(), rflu_computevertexvariables(), rflu_setdependentvars(), and rflu_modrindstates::rflu_setrindstatefarfieldperf().
real(rfreal) function mixtperf_p_drt (real(rfreal), intent(in) D, real(rfreal), intent(in) R, real(rfreal), intent(in) T)
Definition at line 54 of file MixtPerf_P.F90.
References Plane_3< R, T >::d(), and Color::r().
Referenced by rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_computeexactflowerror(), rflu_initbcdatahardcode(), rflu_initflowhardcode(), and rflu_modnscbc::rflu_nscbc_initifveltemp().
real(rfreal) function mixtperf_p_gmapo (real(rfreal), intent(in) G, real(rfreal), intent(in) Ma, real(rfreal), intent(in) Po)
Definition at line 69 of file MixtPerf_P.F90.
References Color::g().
Referenced by bcondinflowperf(), and rflu_modexactflow::rflu_computeexactflowssvortex().
real(rfreal) function mixtperf_p_gpotto (real(rfreal), intent(in) G, real(rfreal), intent(in) Po, real(rfreal), intent(in) T, real(rfreal), intent(in) To)
Definition at line 100 of file MixtPerf_P.F90.
References Color::g().
Referenced by bcondinflowperf().
real(rfreal) function mixtperf_po_cgpuvw (real(rfreal), intent(in) C, real(rfreal), intent(in) G, real(rfreal), intent(in) P, real(rfreal), intent(in) U, real(rfreal), intent(in) V, real(rfreal), intent(in) W)
Definition at line 130 of file MixtPerf_P.F90.
References Line_2< R, T >::c(), Color::g(), and v.
Referenced by bcondinflowperf().
real(rfreal) function mixtperf_po_gptto (real(rfreal), intent(in) G, real(rfreal), intent(in) P, real(rfreal), intent(in) T, real(rfreal), intent(in) To)
Definition at line 115 of file MixtPerf_P.F90.
References Color::g().
Referenced by bcondinflowperf().