Rocstar: MixtPerf_M.F90 File Reference
MixtPerf_M.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtperf_m_r (R)
Function/Subroutine Documentation
real(rfreal) function mixtperf_m_r (real(rfreal), intent(in) R)
Definition at line 39 of file MixtPerf_M.F90.
References Color::r().
Referenced by perfgasgasvars(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), and rflu_setgasvars().