Rocstar: MixtPerf_G.F90 File Reference
MixtPerf_G.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtperf_g_cpr (Cp, R)
Function/Subroutine Documentation
real(rfreal) function mixtperf_g_cpr (real(rfreal), intent(in) Cp, real(rfreal), intent(in) R)
Definition at line 39 of file MixtPerf_G.F90.
References Color::r().
Referenced by bcondfarfieldperf(), bcondinflowperf(), bcondinjectionperf(), bcondoutflowperf(), inrt_vaporenergyconversion(), perfgasdependentvars(), peri_cocprslowterms(), rflo_modboundaryconditions::rflo_bcondinflowvpperf(), rflo_modboundaryconditions::rflo_bcondinflowvtperf(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflowperf(), rflo_checkvalidity(), rflo_correctcorneredgecells(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modboundxvutils::rflu_bxv_compenergypatch(), rflu_modboundxvutils::rflu_bxv_compmomenergypatch(), rflu_modboundconvertcv::rflu_bxv_convertcvprim2cons(), rflu_modboundxvutils::rflu_bxv_setdependentvarspatch(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_checkpositivity(), rflu_checkvalidity(), rflu_computevertexvariables(), rflu_modconvertcv::rflu_convertcvprim2cons(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_initflowhardcode(), rflu_initflowhardcodelim(), rflu_initflowscratch(), rflu_modnscbc::rflu_nscbc_comprhsff(), rflu_modnscbc::rflu_nscbc_comprhsifveltemp(), rflu_modnscbc::rflu_nscbc_comprhsof(), rflu_modnscbc::rflu_nscbc_comprhssw(), rflu_modnscbc::rflu_nscbc_initff(), rflu_modnscbc::rflu_nscbc_initiftotang(), rflu_modnscbc::rflu_nscbc_initifveltemp(), rflu_modnscbc::rflu_nscbc_initof(), rflu_modnscbc::rflu_nscbc_initsw(), rflu_setdependentvars(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_modrindstates::rflu_setrindstateinjectperf(), rflu_modrindstates::rflu_setrindstateslipwallperf(), rflu_timestepinviscid(), rflu_timestepviscous(), spec_rflu_modchemistry::spec_rflu_integratechemsrcterm(), and turb_flucv2cons().