Rocstar: MixtPerf_T.F90 File Reference
MixtPerf_T.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtperf_t_cgr (C, G, R)
real(rfreal) function mixtperf_t_cphovm2 (Cp, Ho, Vm2)
real(rfreal) function mixtperf_t_cveovm2 (Cv, Eo, Vm2)
real(rfreal) function mixtperf_t_dpr (D, P, R)
real(rfreal) function mixtperf_t_gmato (G, Ma, To)
real(rfreal) function mixtperf_to_cptuvw (Cp, T, U, V, W)
Function/Subroutine Documentation
real(rfreal) function mixtperf_t_cgr (real(rfreal), intent(in) C, real(rfreal), intent(in) G, real(rfreal), intent(in) R)
Definition at line 40 of file MixtPerf_T.F90.
References Line_2< R, T >::c(), Color::g(), and Color::r().
Referenced by bcondinflowperf().
real(rfreal) function mixtperf_t_cphovm2 (real(rfreal), intent(in) Cp, real(rfreal), intent(in) Ho, real(rfreal), intent(in) Vm2)
Definition at line 55 of file MixtPerf_T.F90.
real(rfreal) function mixtperf_t_cveovm2 (real(rfreal), intent(in) Cv, real(rfreal), intent(in) Eo, real(rfreal), intent(in) Vm2)
Definition at line 70 of file MixtPerf_T.F90.
Referenced by bcondinflowperf_gl(), bcondoutflowperf_gl(), rflu_checkpositivity_gl(), rflu_checkvalidity_gl(), rflu_computevertexvariables(), and rflu_setdependentvars().
real(rfreal) function mixtperf_t_dpr (real(rfreal), intent(in) D, real(rfreal), intent(in) P, real(rfreal), intent(in) R)
Definition at line 85 of file MixtPerf_T.F90.
References Plane_3< R, T >::d(), and Color::r().
Referenced by perfgasdependentvars(), plag_rflu_correctmixtproperties(), rflo_checkvalidity(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modboundconvertcv::rflu_bxv_convertcvcons2prim(), rflu_modboundxvutils::rflu_bxv_setdependentvarspatch(), rflu_checkpositivity(), rflu_checkvalidity(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_computevertexvariables(), rflu_modconvertcv::rflu_convertcvcons2prim(), rflu_initbcdatahardcode(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxd2_tcp(), rflu_setdependentvars(), and turb_flucv2prim().
real(rfreal) function mixtperf_t_gmato (real(rfreal), intent(in) G, real(rfreal), intent(in) Ma, real(rfreal), intent(in) To)
Definition at line 100 of file MixtPerf_T.F90.
References Color::g().
Referenced by bcondinflowperf().
real(rfreal) function mixtperf_to_cptuvw (real(rfreal), intent(in) Cp, real(rfreal), intent(in) T, real(rfreal), intent(in) U, real(rfreal), intent(in) V, real(rfreal), intent(in) W)
Definition at line 115 of file MixtPerf_T.F90.
References v.