Rocstar: MixtLiq_D.F90 File Reference
MixtLiq_D.F90 File Reference
Functions/Subroutines
real(rfreal) function mixtliq_d_dobpppobttto (Dz, Bp, Bt, P, Po, T, To)
Function/Subroutine Documentation
real(rfreal) function mixtliq_d_dobpppobttto (real(rfreal), intent(in) Dz, real(rfreal), intent(in) Bp, real(rfreal), intent(in) Bt, real(rfreal), intent(in) P, real(rfreal), intent(in) Po, real(rfreal), intent(in) T, real(rfreal), intent(in) To)
Definition at line 40 of file MixtLiq_D.F90.
References Direction_3< R, T >::dz().
Referenced by bcondinflowperf_gl(), bcondoutflowperf_gl(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch_gl(), rflu_computevertexvariables(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_initflowscratch(), rflu_modroeflux::rflu_roe_computeflux1_gl(), rflu_modroeflux::rflu_roe_computeflux2_gl(), rflu_setdependentvars(), and spec_rflu_sourceterms_gl().