Rocstar: FindProbe.f90 File Reference
MP/Source/FindProbe.f90 File Reference
Functions/Subroutines
subroutine findprobe (glb, myid)
subroutine sphere_imp_contains_point_3d (r, center, p, inside)
Function/Subroutine Documentation
subroutine findprobe (type(rocfrac_global) glb, integer myid)
Definition at line 53 of file MP/Source/FindProbe.f90.
References i, j, max(), smallestelement(), sphere_imp_contains_point_3d(), sqrt(), and CImg< T >::sum().
subroutine sphere_imp_contains_point_3d (real (kind = 8) r, real (kind = 8), dimension(ndim) center, real (kind = 8), dimension(ndim) p, logical inside)
Definition at line 177 of file MP/Source/FindProbe.f90.
References Color::r(), and CImg< T >::sum().