Rocstar: arruda_boyce.cauchy.f90 File Reference
MP/Source/arruda_boyce.cauchy.f90 File Reference
Functions/Subroutines
subroutine arruda_boyce_cauchy (F11, F12, F13, F21, F22, F23, F31, F32, F33, Cchy11, Cchy22, Cchy33, Cchy12, Cchy13, Cchy23, ielem, mu, kappa)
Function/Subroutine Documentation
subroutine arruda_boyce_cauchy (real*8 F11, real*8 F12, real*8 F13, real*8 F21, real*8 F22, real*8 F23, real*8 F31, real*8 F32, real*8 F33, real*8 Cchy11, real*8 Cchy22, real*8 Cchy33, real*8 Cchy12, real*8 Cchy13, real*8 Cchy23, integer ielem, real*8 mu, real*8 kappa)
Definition at line 53 of file MP/Source/arruda_boyce.cauchy.f90.
References id(), k, n, Aff_transformation_repS2< FT >::print(), rs(), solve_x(), sqrt(), and CImg< T >::sum().