Rocstar: cst_coh.f90 File Reference
MP/Source/cst_coh.f90 File Reference
Functions/Subroutines
subroutine cst_coh (coor, lmc, matc, R_co, d, deltan, deltat, sigmax, taumax, Sinit, Sthresh, nstep, numnp, numco, numat_coh, delta, numploadelem, idpressload, pressload, numboundmesh, idmesh, rmesh, nboundtype, num_fail_coh, index_fail_coh, npress, nmesh, ielem_coh, iface_coh)
Function/Subroutine Documentation
subroutine cst_coh (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:6,1:numco) lmc, integer, dimension(1:numco) matc, real*8, dimension(1:3*numnp) R_co, real*8, dimension(1:3*numnp) d, real*8, dimension(1:numat_coh) deltan, real*8, dimension(1:numat_coh) deltat, real*8, dimension(1:numat_coh) sigmax, real*8, dimension(1:numat_coh) taumax, real*8, dimension(1:numat_coh) Sinit, real*8, dimension(1:3,1:numco) Sthresh, integer nstep, integer numnp, integer numco, integer numat_coh, real*8 delta, integer numploadelem, integer, dimension(1:5,1:npress) idpressload, real*8, dimension(1:3,1:npress) pressload, integer numboundmesh, integer, dimension(1:4,1:nmesh) idmesh, real*8, dimension(1:3,1:nmesh) rmesh, integer, dimension(1:numnp) nboundtype, integer num_fail_coh, integer, dimension(1:numco) index_fail_coh, integer npress, integer nmesh, integer, dimension(1:2,1:numco) ielem_coh, integer, dimension(1:2,1:numco) iface_coh)
Definition at line 53 of file MP/Source/cst_coh.f90.
References Plane_3< R, T >::d(), Direction_2< R, T >::delta(), i, j, Aff_transformation_2< R_ >::m(), parameter(), Aff_transformation_repS2< FT >::print(), sqrt(), and x.