Rocstar: feminp.f90 File Reference
MP/Source/feminp.f90 File Reference
Functions/Subroutines
subroutine feminp (glb, myid)
subroutine prefix_sub (glb)
subroutine ale_sub (glb)
subroutine nrun_sub (glb)
subroutine dynamic_sub (glb, keywd)
subroutine dummytract_sub (glb, keywd)
subroutine matmodel_hyperelastic (glb, keywd, tmp_E, tmp_xnu, tmp_rho, tmp_alpha, tmp_iSolnType)
subroutine matmodel_elastic (glb, keywd, tmp_E, tmp_xnu, tmp_rho, tmp_alpha, tmp_iSolnType, tmp_MatOrtho)
subroutine matvol_sub (glb, tmp_E, tmp_xnu, tmp_rho, tmp_alpha, tmp_iSolnType)
subroutine matcoh_sub (glb)
subroutine pload1_sub (glb)
subroutine nodeio_sub (myid)
subroutine boundary_sub (glb)
subroutine boundaryht_sub (glb)
subroutine boundarymm_sub (glb)
subroutine amplitude_sub (glb, keywd)
subroutine element_sub (glb, keywd)
subroutine heat_transfer_sub (glb, keywd, tmp_KappaHT, tmp_Cp, tmp_iSolnTypeHT)
subroutine probe_sub (glb)
subroutine micromechanical_sub (glb, keywd, tmp_E, tmp_xnu, tmp_rho, tmp_alpha, tmp_iSolnType)
subroutine initialcondition_sub (glb, keywd)
Function/Subroutine Documentation
subroutine ale_sub (type(rocfrac_global) glb)
Definition at line 459 of file MP/Source/feminp.f90.
subroutine amplitude_sub (type(rocfrac_global) glb, character keywd)
Definition at line 1064 of file MP/Source/feminp.f90.
References i, locchr(), and Action::run().
subroutine boundary_sub (type(rocfrac_global) glb)
Definition at line 950 of file MP/Source/feminp.f90.
References i.
subroutine boundaryht_sub (type(rocfrac_global) glb)
Definition at line 988 of file MP/Source/feminp.f90.
References i.
subroutine boundarymm_sub (type(rocfrac_global) glb)
Definition at line 1027 of file MP/Source/feminp.f90.
References i.
subroutine dummytract_sub (type(rocfrac_global) glb, character(len=200) keywd)
Definition at line 557 of file MP/Source/feminp.f90.
References locchr().
subroutine dynamic_sub (type(rocfrac_global) glb, character(len=200) keywd)
Definition at line 511 of file MP/Source/feminp.f90.
References locchr(), and rchar().
subroutine element_sub (type(rocfrac_global) glb, character(len=200) keywd)
Definition at line 1138 of file MP/Source/feminp.f90.
References locchr(), Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
subroutine feminp (type(rocfrac_global) glb, integer myid)
Definition at line 53 of file MP/Source/feminp.f90.
References ale_sub(), amplitude_sub(), boundary_sub(), boundaryht_sub(), boundarymm_sub(), dummytract_sub(), dynamic_sub(), element_sub(), heat_transfer_sub(), i, initialcondition_sub(), matcoh_sub(), matmodel_elastic(), matmodel_hyperelastic(), matvol_sub(), max(), micromechanical_sub(), nodeio_sub(), nrun_sub(), pload1_sub(), prefix_sub(), Aff_transformation_repS2< FT >::print(), probe_sub(), Attribute::status(), StopWatch::stop(), and x.
subroutine heat_transfer_sub (type(rocfrac_global) glb, character keywd, real*8, dimension(1:10) tmp_KappaHT, real*8, dimension(1:10) tmp_Cp, integer, dimension(1:10) tmp_iSolnTypeHT)
Definition at line 1197 of file MP/Source/feminp.f90.
References i, j, and Aff_transformation_repS2< FT >::print().
subroutine initialcondition_sub (type(rocfrac_global) glb, character(len=200) keywd)
Definition at line 1434 of file MP/Source/feminp.f90.
References locchr().
subroutine matcoh_sub (type(rocfrac_global) glb)
Definition at line 879 of file MP/Source/feminp.f90.
References i.
subroutine matmodel_elastic (type(rocfrac_global) glb, character keywd, real*8, dimension(1:10) tmp_E, real*8, dimension(1:10) tmp_xnu, real*8, dimension(1:10) tmp_rho, real*8, dimension(1:10) tmp_alpha, integer, dimension(1:10) tmp_iSolnType, integer, dimension(1:10) tmp_MatOrtho)
Definition at line 707 of file MP/Source/feminp.f90.
References i, locchr(), max(), Aff_transformation_repS2< FT >::print(), and sqrt().
subroutine matmodel_hyperelastic (type(rocfrac_global) glb, character keywd, real*8, dimension(1:10) tmp_E, real*8, dimension(1:10) tmp_xnu, real*8, dimension(1:10) tmp_rho, real*8, dimension(1:10) tmp_alpha, integer, dimension(1:10) tmp_iSolnType)
Definition at line 600 of file MP/Source/feminp.f90.
References conchr(), i, key, max(), Aff_transformation_repS2< FT >::print(), and sqrt().
subroutine matvol_sub (type(rocfrac_global) glb, real*8, dimension(1:10) tmp_E, real*8, dimension(1:10) tmp_xnu, real*8, dimension(1:10) tmp_rho, real*8, dimension(1:10) tmp_alpha, integer, dimension(1:10) tmp_iSolnType)
Definition at line 842 of file MP/Source/feminp.f90.
References i, max(), Aff_transformation_repS2< FT >::print(), sqrt(), and StopWatch::stop().
subroutine micromechanical_sub (type(rocfrac_global) glb, character keywd, real*8, dimension(1:10) tmp_E, real*8, dimension(1:10) tmp_xnu, real*8, dimension(1:10) tmp_rho, real*8, dimension(1:10) tmp_alpha, integer, dimension(1:10) tmp_iSolnType)
Definition at line 1286 of file MP/Source/feminp.f90.
References homogenizedmat(), i, locchr(), Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
subroutine nodeio_sub (integer myid)
Definition at line 919 of file MP/Source/feminp.f90.
References i.
subroutine nrun_sub (type(rocfrac_global) glb)
Definition at line 491 of file MP/Source/feminp.f90.
subroutine pload1_sub (type(rocfrac_global) glb)
Definition at line 904 of file MP/Source/feminp.f90.
subroutine prefix_sub (type(rocfrac_global) glb)
Definition at line 431 of file MP/Source/feminp.f90.
subroutine probe_sub (type(rocfrac_global) glb)
Definition at line 1248 of file MP/Source/feminp.f90.
References i.