Rocstar: bc_enforce.f90 File Reference
MP/Source/bc_enforce.f90 File Reference
Functions/Subroutines
subroutine bc_enforce (numbound, numnp, id, r, slope, prop, vb, ab, v, a, d, delta, Rnet, xm, DampEnabled, CurrTime)
Function/Subroutine Documentation
subroutine bc_enforce (integer numbound, integer numnp, integer, dimension(1:4,numbound) id, real*8, dimension(1:3,numbound) r, real*8 slope, real*8 prop, real*8, dimension(1:3*numbound) vb, real*8, dimension(1:3*numbound) ab, real*8, dimension(1:3*numnp) v, real*8, dimension(1:3*numnp) a, real*8, dimension(1:3*numnp) d, real*8 delta, real*8, dimension(1:3*numnp) Rnet, real*8, dimension(1:numnp) xm, logical DampEnabled, real*8 CurrTime)
Definition at line 53 of file MP/Source/bc_enforce.f90.
References Line_2< R, T >::a(), Plane_3< R, T >::d(), Direction_2< R, T >::delta(), i, id(), Color::r(), CLine::slope(), and v.