Rocstar: vol_elem_mat_matous.f90 File Reference
MP/Source/vol_elem_mat_matous.f90 File Reference
Functions/Subroutines
subroutine vol_elem_mat_matous (glb)
Function/Subroutine Documentation
subroutine vol_elem_mat_matous (type(rocfrac_global) glb)
Definition at line 53 of file MP/Source/vol_elem_mat_matous.f90.
References compositestiffnes(), i, invert2(), j, Aff_transformation_repS2< FT >::print(), and sqrt().