Rocstar: PlaneNorm.f90 File Reference
MP/Source/PlaneNorm.f90 File Reference
Functions/Subroutines
subroutine planenorm (x1, y1, z1, x2, y2, z2, x3, y3, z3, xn, yn, zn, same)
subroutine cross0_3d (x0, y0, z0, x1, y1, z1, x2, y2, z2, x3, y3, z3)
real *8 function calcoffset (x1, y1, z1, x2, y2, z2)
real *8 function offset (vNorm, x2, y2, z2)
Function/Subroutine Documentation
real*8 function calcoffset (real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2)
Definition at line 175 of file MP/Source/PlaneNorm.f90.
References calcoffset().
subroutine cross0_3d (real*8 x0, real*8 y0, real*8 z0, real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2, real*8 x3, real*8 y3, real*8 z3)
Definition at line 125 of file MP/Source/PlaneNorm.f90.
real*8 function offset (real*8, dimension(1:3) vNorm, real*8 x2, real*8 y2, real*8 z2)
Definition at line 211 of file MP/Source/PlaneNorm.f90.
References offset().
subroutine planenorm (real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2, real*8 x3, real*8 y3, real*8 z3, real*8 xn, real*8 yn, real*8 zn, integer same)
Definition at line 53 of file MP/Source/PlaneNorm.f90.
References cross0_3d(), sqrt(), and zn().