Rocstar: A_D_tensors.f90 File Reference
MP/Source/A_D_tensors.f90 File Reference
Functions/Subroutines
subroutine a_d_tensors (Lo, Lm, L2, Mm, M2, cm, cb, cd, Dbm, Dbb, Dbd, Dmm, Dmb, Dmd, Ddm, Ddb, Ddd, A2, Am, L_bar)
subroutine vecmatvecmul (a, B, c, ndim, scaler)
Function/Subroutine Documentation
subroutine a_d_tensors (real*8, dimension(1:6,1:6) Lo, real*8, dimension(1:6,1:6) Lm, real*8, dimension(1:6,1:6) L2, real*8, dimension(1:6,1:6) Mm, real*8, dimension(1:6,1:6) M2, real*8 cm, real*8 cb, real*8 cd, real*8, dimension(1:6,1:6) Dbm, real*8, dimension(1:6,1:6) Dbb, real*8, dimension(1:6,1:6) Dbd, real*8, dimension(1:6,1:6) Dmm, real*8, dimension(1:6,1:6) Dmb, real*8, dimension(1:6,1:6) Dmd, real*8, dimension(1:6,1:6) Ddm, real*8, dimension(1:6,1:6) Ddb, real*8, dimension(1:6,1:6) Ddd, real*8, dimension(1:6,1:6) A2, real*8, dimension(1:6,1:6) Am, real*8, dimension(1:6,1:6) L_bar)
Definition at line 53 of file MP/Source/A_D_tensors.f90.
References Line_2< R, T >::a(), Color::b(), Line_2< R, T >::c(), GEM_DomainBoundary::debug(), eshelby(), i, invert2(), j, Aff_transformation_repS2< FT >::print(), s, sqrt(), and StopWatch::stop().
subroutine vecmatvecmul (real*8, dimension(1:ndim) a, real*8, dimension(1:ndim,1:ndim) B, real*8, dimension(1:ndim) c, integer ndim, real*8 scaler)
Definition at line 556 of file MP/Source/A_D_tensors.f90.
References Line_2< R, T >::a(), Color::b(), Line_2< R, T >::c(), i, j, and k.