Rocstar: msh2hdf.C File Reference
msh2hdf.C File Reference
#include "MSH_Reader.h"
#include "roccom.h"
#include <iostream>
#include <sstream>
Functions
COM_EXTERN_MODULE (Rocout)
int main (int argc, char *argv[])
Function Documentation
COM_EXTERN_MODULE (Rocout)
int main (int argc, char * argv[])
Definition at line 35 of file msh2hdf.C.
References COM_call_function(), COM_finalize(), COM_free_buffer(), COM_get_attribute_handle_const(), COM_get_function_handle(), COM_get_panes(), COM_init(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_new_window(), COM_window_init_done(), i, and MSH_Reader::read_mesh().
{
   COM_init( &argc, &argv);
   if ( argc < 2) {
     cout << "Usage: " << argv[0] << " <msh_file> [hdf_name] " << endl;
     return -1;
   }
   char *firstdot=strchr( argv[1], '.');
   const string wname(argv[1], firstdot? firstdot-argv[1]: strlen( argv[1]));
   std::cout << "Reading surface mesh file \"" << argv[1] << '"' << endl;
   COM_new_window( wname.c_str());
   MSH_Reader().read_mesh( argv[1], wname);
   COM_window_init_done( wname.c_str());
   // Output mesh
   COM_LOAD_MODULE_STATIC_DYNAMIC(Rocout, "OUT");
   int OUT_write = COM_get_function_handle( "OUT.write_attribute");
   int mesh = COM_get_attribute_handle_const( (wname+".mesh").c_str());
   std::string fname( argc>=3 ? argv[2] : (wname+".hdf").c_str());
   int separate_files = fname.find( ".hdf") == string::npos;
   if ( !separate_files) {
     std::cout << "Writing HDF file(s) " << fname << endl;
     COM_call_function( OUT_write, fname.c_str(), &mesh, (char*)wname.c_str(), "000");
   }
   else {
     int npanes, *paneIDs;
     COM_get_panes( wname.c_str(), &npanes, &paneIDs);
     for ( int i=0; i<npanes; ++i) {
       std::ostringstream ostr;
       ostr << fname;
       ostr.fill('0'); ostr.width(5);
       ostr << paneIDs[i] << ".hdf";
       std::cout << "Writing HDF file(s) " << ostr.str() << endl;
       COM_call_function( OUT_write, ostr.str().c_str(), &mesh,
                          (char*)wname.c_str(),
                          "000", NULL, NULL, &paneIDs[i]);
     }
     COM_free_buffer( &paneIDs);
   }
   COM_finalize();
   return 0;
 }