Rocstar: nvc Namespace Reference
nvc Namespace Reference
Classes
class NVec
Typedefs
typedef unsigned int id_t
typedef NVec< 3, double > Vec3D
typedef NVec< 3, double > Vector3D
typedef NVec< 3, double > Point3D
typedef NVec< 4, float > rgbColor
typedef NVec< 3, double > Vertex3D
typedef NVec< 3, double > Normal3D
typedef NVec< 2, float > TexCoord
typedef NVec< 3, unsigned int > Tri
typedef NVec< 3, unsigned int > Quad
typedef NVec< 2, unsigned int > IdxHEdge
Functions
template<int DIM, typename T >
ostream & operator<< (ostream &out, const NVec< DIM, T > &v)
template<int DIM, typename T >
std::istream & operator>> (std::istream &in, NVec< DIM, T > &v)
template<int DIM, typename T >
bool operator== (const NVec< DIM, T > &v1, const NVec< DIM, T > &v2)
template<int DIM, typename T >
NVec< DIM, T > operator+ (const NVec< DIM, T > &u, const NVec< DIM, T > &v)
template<int DIM, typename T >
NVec< DIM, T > operator+= (NVec< DIM, T > &u, const NVec< DIM, T > &v)
template<int DIM, typename T >
NVec< DIM, T > operator- (const NVec< DIM, T > &u, const NVec< DIM, T > &v)
template<int DIM, typename T >
NVec< DIM, T > operator- (const NVec< DIM, T > &v)
template<int DIM, class T , class N >
NVec< DIM, T > operator* (N s, const NVec< DIM, T > &v)
template<int DIM, class T , class N >
NVec< DIM, T > operator* (const NVec< DIM, T > &v, N s)
template<int DIM, class T , class N >
NVec< DIM, T > operator/ (const NVec< DIM, T > &v, N s)
template<int DIM, class T , class N >
NVec< DIM, T > operator/= (NVec< DIM, T > &v, N s)
template<int DIM, typename T >
T operator* (const NVec< DIM, T > &u, const NVec< DIM, T > &v)
template<typename T >
NVec< 3, T > cross (const NVec< 3, T > &u, const NVec< 3, T > &v)
template<int DIM, typename T >
T norm2 (const NVec< DIM, T > &v)
template<int DIM, typename T >
T norm (const NVec< DIM, T > &v)
template<int DIM, typename T >
void unitize (NVec< DIM, T > &v)
template<int DIM, typename T >
T euclid_distance (const NVec< DIM, T > &u, const NVec< DIM, T > &v)
template<int DIM, typename T >
T angle (const NVec< DIM, T > &u, const NVec< DIM, T > &v)
template<int DIM, typename T >
T angle_unitized (const NVec< DIM, T > &u, const NVec< DIM, T > &v)
Typedef Documentation
typedef unsigned int id_t
Definition at line 217 of file Rocon/include/NVec.h.
typedef NVec< 2, unsigned int > IdxHEdge
Definition at line 227 of file Rocon/include/NVec.h.
typedef NVec< 3, double > Normal3D
Definition at line 223 of file Rocon/include/NVec.h.
typedef NVec< 3, double > Point3D
Definition at line 220 of file Rocon/include/NVec.h.
typedef NVec< 3, unsigned int > Quad
Definition at line 226 of file Rocon/include/NVec.h.
typedef NVec< 4, float > rgbColor
Definition at line 221 of file Rocon/include/NVec.h.
typedef NVec< 2, float > TexCoord
Definition at line 224 of file Rocon/include/NVec.h.
typedef NVec< 3, unsigned int > Tri
Definition at line 225 of file Rocon/include/NVec.h.
typedef NVec< 3, double > Vec3D
Definition at line 218 of file Rocon/include/NVec.h.
typedef NVec< 3, double > Vector3D
Definition at line 219 of file Rocon/include/NVec.h.
typedef NVec< 3, double > Vertex3D
Definition at line 222 of file Rocon/include/NVec.h.
Function Documentation
T angle (const NVec< DIM, T > & u, const NVec< DIM, T > & v) inline
Definition at line 207 of file Rocon/include/NVec.h.
References cimg_library::acos(), and norm().
   {
     return acos((u*v)/(norm(u) * norm(v)));
   }
T angle_unitized (const NVec< DIM, T > & u, const NVec< DIM, T > & v) inline
Definition at line 213 of file Rocon/include/NVec.h.
References cimg_library::acos().
   {
     return acos(u*v);
   }
NVec< 3, T > cross (const NVec< 3, T > & u, const NVec< 3, T > & v) inline
Definition at line 185 of file Rocon/include/NVec.h.
Referenced by Mesquite::h_fcn_2e(), Mesquite::h_fcn_2i(), Mesquite::h_fcn_3e(), Mesquite::h_fcn_3e_v3(), Mesquite::h_fcn_3i(), h_fcn_ridft2(), h_fcn_ridft3(), halfspace3d::init(), and intersect_ray_triangle().
     {
       return NVec<3,T>( u[1]*v[2] - v[1]*u[2],
                         -u[0]*v[2] + v[0]*u[2],
                         u[0]*v[1] - v[0]*u[1] );
     }
T euclid_distance (const NVec< DIM, T > & u, const NVec< DIM, T > & v) inline
Definition at line 203 of file Rocon/include/NVec.h.
References norm().
Referenced by KNN_Grid< Tri >::k_nearest().
   { return norm(v-u); }
T norm (const NVec< DIM, T > & v) inline
Definition at line 195 of file Rocon/include/NVec.h.
References norm2(), and sqrt().
Referenced by angle(), c2005(), Rocmop::check_displacements(), Mesh::NodalCoordinates::closest_node(), Mesh::NodalCoordinates::closest_point(), Rocmop::constrain_displacements(), euclid_distance(), halfspace3d::halfspace3d(), main(), SteepestDescent::optimize_vertex_positions(), tpz_ordered::parse_data(), tpz_fequad::parse_data(), Rocmop::smooth_vol_mesq_ng(), and PatchData::update_cached_normals().
 { return sqrt(norm2(v)); }
T norm2 (const NVec< DIM, T > & v) inline
Definition at line 193 of file Rocon/include/NVec.h.
References v.
Referenced by angle(), norm(), and unitize().
 { return v*v; }
NVec< DIM, T > operator* (N s, const NVec< DIM, T > & v) inline
Definition at line 139 of file Rocon/include/NVec.h.
References i, and n.
     {
       NVec<DIM,T> n;
       for(int i=0;i<DIM;i++)
         n[i]=s*v[i];
       return n;
     }
NVec< DIM, T > operator* (const NVec< DIM, T > & v, N s) inline
Definition at line 148 of file Rocon/include/NVec.h.
References v.
     { return s*v; }
T operator* (const NVec< DIM, T > & u, const NVec< DIM, T > & v) inline
Definition at line 169 of file Rocon/include/NVec.h.
References i, and n.
   {
     T n = 0;
     for(int i=0;i<DIM;i++)
       n += (u[i]*v[i]);
     return n;
   }
NVec< DIM, T > operator+ (const NVec< DIM, T > & u, const NVec< DIM, T > & v) inline
Definition at line 104 of file Rocon/include/NVec.h.
References i, and n.
     {
       NVec<DIM,T> n;
       for(int i=0;i<DIM;i++)
         n[i]=u[i]+v[i];
       return n;
     }
NVec< DIM, T > operator+= (NVec< DIM, T > & u, const NVec< DIM, T > & v) inline
Definition at line 113 of file Rocon/include/NVec.h.
References i.
     {
       for(int i=0;i<DIM;i++)
         u[i]=u[i]+v[i];
       return u;
     }
NVec< DIM, T > operator- (const NVec< DIM, T > & u, const NVec< DIM, T > & v) inline
Definition at line 122 of file Rocon/include/NVec.h.
References i, and n.
     {
       NVec<DIM,T> n;
       for(int i=0;i<DIM;i++)
         n[i]=u[i]-v[i];
       return n;
     }
NVec< DIM, T > operator- (const NVec< DIM, T > & v) inline
Definition at line 130 of file Rocon/include/NVec.h.
References i, and n.
     {
       NVec<DIM,T> n;
       for(int i=0;i<DIM;i++)
         n[i]=-v[i];
       return n;
     }
NVec< DIM, T > operator/ (const NVec< DIM, T > & v, N s) inline
Definition at line 152 of file Rocon/include/NVec.h.
References i, n, and s.
     {
       NVec<DIM,T> n;
       for(int i=0;i<DIM;i++)
         n[i]=v[i]/(T)s;
       return n;
     }
NVec< DIM, T > operator/= (NVec< DIM, T > & v, N s) inline
Definition at line 161 of file Rocon/include/NVec.h.
References i, s, and v.
     {
       for(int i=0;i<DIM;i++)
         v[i]=v[i]/(T)s;
       return v;
     }
ostream & operator<< (ostream & out, const NVec< DIM, T > & v) inline
Definition at line 76 of file Rocon/include/NVec.h.
References i, and v.
   {
     //out << "( ";
     for(int i =0;i<DIM-1;i++) out << v[i] << " ";
     out << v[DIM-1];
     //out << " )";
     return out;
   }
bool operator== (const NVec< DIM, T > & v1, const NVec< DIM, T > & v2) inline
Definition at line 93 of file Rocon/include/NVec.h.
References i.
   {
     for(int i =0;i<DIM;i++)
       if (v1[i] != v2[i]) return false;
     return true;
   }
std::istream & operator>> (std::istream & in, NVec< DIM, T > & v) inline
Definition at line 86 of file Rocon/include/NVec.h.
References i.
   {
     for(int i =0;i<DIM;i++) in >> v[i];
     return in;
   }
void unitize (NVec< DIM, T > & v) inline
Definition at line 197 of file Rocon/include/NVec.h.
References norm2(), and sqrt().
   {
     T l = norm2(v);
     if( l!=1.0 && l!=0.0 )  v /= sqrt(l);
   }