Rocstar: GeoPrim Namespace Reference
GeoPrim Namespace Reference
Classes
class C3Facet
class C3Plane
class C3Vector
/brief Cartesian 3 Vector
class CBox
class CFacet
class CLine
class CLineSegment
class CPlane
class CPoint
class CVector
Typedefs
typedef C3Vector C3Point
Functions
template<typename PointContainer >
C3Point C3Centroid (const PointContainer &pc)
template<typename PointContainer >
CPoint Centroid (const PointContainer &pc)
void Transpose (CVector matrix[])
void Transpose_2x3 (CVector matrix[], double tpose[][2])
double Distance (const CPoint &p, const CLine &l)
double Distance (const C3Point &p, const CLine &l)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::CBox &b)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::CPoint &p)
std::istream & operator>> (std::istream &iS, GeoPrim::CPoint &p)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::CVector &v)
std::istream & operator>> (std::istream &iS, GeoPrim::CVector &v)
std::ostream & operator<< (std::ostream &oS, const GeoPrim::C3Vector &v)
std::istream & operator>> (std::istream &iS, GeoPrim::C3Vector &v)
GeoPrim::CPoint operator* (double scalar, const GeoPrim::CPoint &p)
GeoPrim::C3Vector operator* (double scalar, const GeoPrim::C3Vector &v)
GeoPrim::CVector operator* (double scalar, const GeoPrim::CVector &v)
Variables
const double TOL = 1e-16
const double PI = 4.0*atan(1.0)
Typedef Documentation
typedef C3Vector C3Point
Definition at line 763 of file GeoPrimitives.H.
Function Documentation
C3Point GeoPrim::C3Centroid (const PointContainer & pc)
Definition at line 1481 of file GeoPrimitives.H.
References pi, x, y, and z.
Referenced by C3Facet::Centroid().
   {
     double x = 0.0;
     double y = 0.0;
     double z = 0.0;
     double np = 1.0/static_cast<double>(pc.size());
     typename PointContainer::const_iterator pi = pc.begin();
     while(pi != pc.end()){
       x += (*pi)->x();
       y += (*pi)->y();
       z += (*pi)->z();
       pi++;
     }
     x *= np;
     y *= np;
     z *= np;
     return(C3Point(x,y,z));
   };
CPoint GeoPrim::Centroid (const PointContainer & pc)
Definition at line 1501 of file GeoPrimitives.H.
References pi, x, y, and z.
Referenced by CFacet::centroid().
   {
     double x = 0.0;
     double y = 0.0;
     double z = 0.0;
     double np = 1.0/static_cast<double>(pc.size());
     typename PointContainer::const_iterator pi = pc.begin();
     while(pi != pc.end()){
       x += pi->x();
       y += pi->y();
       z += pi->z();
       pi++;
     }
     x *= np;
     y *= np;
     z *= np;
     return(CPoint(x,y,z));
   };
double GeoPrim::Distance (const C3Point & p, const CLine & l)
Definition at line 45 of file GeoPrimitives.C.
References C3Vector::Mag(), CVector::mag2(), CLine::p, v, CLine::v, CPoint::x(), CVector::x(), C3Vector::x(), CPoint::y(), CVector::y(), C3Vector::y(), CPoint::z(), CVector::z(), and C3Vector::z().
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     C3Point p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     C3Vector v(p,p2);
     return(v.Mag());
   }
double Distance (const CPoint & p, const CLine & l)
Definition at line 35 of file GeoPrimitives.C.
References CVector::mag(), CVector::mag2(), CLine::p, v, CLine::v, CPoint::x(), CVector::x(), CPoint::y(), CVector::y(), CPoint::z(), and CVector::z().
   {
     double u = (((p.x() - l.p.x())*l.v.x() + (p.y() - l.p.y())*l.v.y() +
                  (p.z() - l.p.z())*l.v.z())/l.v.mag2());
     CPoint p2(l.p.x()+(u*l.v.x()),l.p.y()+(u*l.v.y()),l.p.z()+(u*l.v.z()));
     CVector v(p,p2);
     return(v.mag());
   }
GeoPrim::CPoint GeoPrim::operator* (double scalar, const GeoPrim::CPoint & p)
Definition at line 117 of file GeoPrimitives.C.
References CPoint::x(), CPoint::y(), and CPoint::z().
   {
     GeoPrim::CPoint rv(p);
     rv.x() *= scalar;
     rv.y() *= scalar;
     rv.z() *= scalar;
     return(rv);
   }
GeoPrim::C3Vector GeoPrim::operator* (double scalar, const GeoPrim::C3Vector & v)
Definition at line 126 of file GeoPrimitives.C.
   {
     GeoPrim::C3Vector rv(v);
     return(rv *= scalar);
   }
GeoPrim::CVector GeoPrim::operator* (double scalar, const GeoPrim::CVector & v)
Definition at line 132 of file GeoPrimitives.C.
   {
     GeoPrim::CVector rv(v);
     return(rv *= scalar);
   }
std::ostream& GeoPrim::operator<< (std::ostream & oS, const GeoPrim::CBox & b)
Definition at line 55 of file GeoPrimitives.C.
References CBox::P1(), and CBox::P2().
   {
     oS << b.P1() << "  " << b.P2();
     return(oS);
   }
std::ostream& GeoPrim::operator<< (std::ostream & oS, const GeoPrim::CPoint & p)
Definition at line 62 of file GeoPrimitives.C.
References CPoint::x(), CPoint::y(), and CPoint::z().
   {
     oS << p.x() << "  " << p.y() << "  " << p.z();
     return(oS);
   }
std::ostream& GeoPrim::operator<< (std::ostream & oS, const GeoPrim::CVector & v)
Definition at line 90 of file GeoPrimitives.C.
References CVector::x(), CVector::y(), and CVector::z().
   {
     oS << v.x() << "  " << v.y() << "  " << v.z();
     return(oS);
   }
std::ostream& GeoPrim::operator<< (std::ostream & oS, const GeoPrim::C3Vector & v)
Definition at line 104 of file GeoPrimitives.C.
References C3Vector::x(), C3Vector::y(), and C3Vector::z().
   {
     oS << v.x() << "  " << v.y() << "  " << v.z();
     return(oS);
   }
std::istream& GeoPrim::operator>> (std::istream & iS, GeoPrim::CPoint & p)
Definition at line 69 of file GeoPrimitives.C.
   {
     iS >> p[0] >> p[1] >> p[2];
     return(iS);
   }
std::istream& GeoPrim::operator>> (std::istream & iS, GeoPrim::CVector & v)
Definition at line 97 of file GeoPrimitives.C.
   {
     iS >> v[0] >> v[1] >> v[2];
     return(iS);
   }
std::istream& GeoPrim::operator>> (std::istream & iS, GeoPrim::C3Vector & v)
Definition at line 111 of file GeoPrimitives.C.
   {
     iS >> v[0] >> v[1] >> v[2];
     return(iS);
   }
void Transpose (CVector matrix[])
Definition at line 11 of file GeoPrimitives.C.
References CVector::init(), x, y, and z.
Referenced by Mesh::GenericCell_2::shapef_jacobian_at(), and Mesh::GenericElement::shapef_jacobian_at().
   {
     CVector tpose[3];
     tpose[0].init(matrix[0].x(),matrix[1].x(),matrix[2].x());
     tpose[1].init(matrix[0].y(),matrix[1].y(),matrix[2].y());
     tpose[2].init(matrix[0].z(),matrix[1].z(),matrix[2].z());
     matrix[0].init(tpose[0]);
     matrix[1].init(tpose[1]);
     matrix[2].init(tpose[2]);
   }
void Transpose_2x3 (CVector matrix[], double tpose[][2])
Definition at line 24 of file GeoPrimitives.C.
References CVector::x(), CVector::y(), and CVector::z().
   {
     tpose[0][0] = matrix[0].x();
     tpose[1][0] = matrix[0].y();
     tpose[2][0] = matrix[0].z();
     tpose[0][1] = matrix[1].x();
     tpose[1][1] = matrix[1].y();
     tpose[2][1] = matrix[1].z();
   }
Variable Documentation
const double PI = 4.0*atan(1.0)
Definition at line 18 of file GeoPrimitives.H.
Referenced by CFacet::contains_point().
const double TOL = 1e-16
Definition at line 17 of file GeoPrimitives.H.
Referenced by CPlane::contains_point(), C3Plane::contains_point(), CFacet::contains_point(), determine_probe_value(), CBox::empty(), Numerics::fpointequals(), CLine::has_point(), CPoint::operator==(), CVector::operator==(), and C3Vector::operator==().