Rocstar: IRAD Namespace Reference
IRAD Namespace Reference
IllinoisRocstar Application Development
IllinoisRocstar Application Development.
Namespaces
Comm
MPI Interface.
Global
Base global namespace.
Meta
Metadata constructs.
Primitive
Basic primitive types.
Profiler
Performance profiling.
Sys
Unix system utilities.
Util
General support utilities.
Classes
class CheckResultsComLine
The ComLineObject for the example programs.
class DDFComLine
ComLine object for test running utility.
class RTSComLine
ComLine object for test running utility.
class TestComLine
ComLineObject for testing app.
class TestProgram
Typedefs
typedef
Global::ParallelGlobalObj
< Comm::CommunicatorObject,
std::string, int,
Profiler::ProfilerObj > TestGlobal
Functions
int CheckResults (int argc, char *argv[])
Check numerical results utility.
int DiffDataFiles (int argc, char *argv[])
Compare two data files within a given tolerance.
int RunTest (int argc, char *argv[])
Runs test programs and scripts through a standard interface.
int TestResults (int argc, char *argv[])
Test results utility.
bool isNumber (std::string sCheck)
int MyTestProgram (int argc, char *argv[])
int TestTCPInterface (int argc, char *argv[])
Test utility for the TCP Interface.
Detailed Description
IllinoisRocstar Application Development.
The IRAD toolkit provides several application development support capabilities which help with the rapid development of serial and parallel applications with uniform look and feel and facilities which allow the developed applications to integrate into the IllinoisRocstar software development environment.
Function Documentation
int IRAD::CheckResults (int argc, char * argv[])
Check numerical results utility.
Parameters
argc integer indicating how many words are in the command line.
argv string words of the command line.
Returns
0 if test was successful, 1 if not.
This utility numerically checks the numbers on a line that matches a specified string. The lines in the file are assumed to have the following format:
UniqueString : <numerical entries>="">
This utility will perform the indicated test(s) on the numerical entires associated with the "UniqueString" identifier given as input. The result is a binary YES(1) or NO(0) which is output to stdout as:
TestName = 1||0
If the test passed(=YES), this utility returns a 0, otherwise it returns 1.
Definition at line 8 of file CheckResults.C.
References ComLineObject::GetOption(), CheckResultsComLine::Initialize(), ComLineObject::LongUsage(), max(), ComLineObject::ProcessOptions(), ComLineObject::ProcessRange(), and x.
Referenced by main().
 {
   CheckResultsComLine comline((const char **)argv);
   comline.Initialize();
   int clerr = comline.ProcessOptions();
   if(!comline.GetOption("help").empty()){
     std::cout << comline.LongUsage() << std::endl;
     return(0);
   }
   int verb_level = 1;
   std::string sverb = comline.GetOption("verbosity");
   std::istringstream Istr(sverb);
   Istr >> verb_level;
   if(verb_level < 0 || verb_level > 3)
     verb_level = 1;
   double lower_limit = -std::numeric_limits<double>::max();
   double upper_limit = std::numeric_limits<double>::max();
   std::string range = comline.GetOption("range");
   std::string ident = comline.GetOption("identifier");
   std::string name = comline.GetOption("name");
   bool passed = false;
   if(name.empty())
     name = ident;
   if(verb_level > 2)
     std::cerr << "Identifier: " << ident << std::endl;
   comline.ProcessRange<double>(lower_limit,upper_limit,range);
   if(verb_level > 2)
     std::cerr << "Processed range: (" << lower_limit << ":" << upper_limit
               << ")" << std::endl;
   std::string line;
   while(std::getline(std::cin,line)){
     std::string::size_type x = line.find(ident);
     if(x != std::string::npos){
       x = line.find(":");
       if(x != std::string::npos){
         std::string snumbers = line.substr(x+1);
         std::istringstream NumIn(snumbers);
         double cnum = 0;
         NumIn >> cnum;
         passed = ((cnum >= lower_limit) && (cnum <= upper_limit));
         if(verb_level)
           std::cout << name << " = " << (passed ? 1 : 0) << std::endl;
         if((verb_level > 1) && !passed){
           std::cerr << "Test failed: " << cnum << " is not in range ("
                     << lower_limit << ":" << upper_limit << ")" << std::endl;
         }
         break;
       }
     }
   }
   if(!passed)
     return(1);
   return(0);
 }
int DiffDataFiles (int argc, char * argv[])
Compare two data files within a given tolerance.
Parameters
argc The number of command line arguments
argv The command line arguments
Returns
0 on success, 1 otherwise
Command-line interface for diffdatafiles:
       diffdatafiles [-h] [-v [level] ] <file1> <file2>
       -h,--help
            Print out long version of help and exit.
       -v,--verblevel [level]
            Set the verbosity level. (default = 1)
This function is designed to compare two data files with numerical solution data in mind. It will compare data within a given tolerence.
Definition at line 30 of file DiffDataFiles.C.
References ComLineObject::ErrorReport(), ComLineObject::GetArgs(), ComLineObject::GetOption(), DDFComLine::Initialize(), isNumber(), ComLineObject::LongUsage(), ComLineObject::ProcessOptions(), and ComLineObject::ShortUsage().
Referenced by main().
   {
     DDFComLine comline((const char **)(argv));
     // The call to comline.Initialize() reads the command line arguments
     // from the array passed in the previous line.
     comline.Initialize();
     // The ProcessOptions() call does detailed examination of the command
     // line arguments to check for user errors or other problems. This call
     // will return non-zero if there were errors on the commandline.
     int clerr = comline.ProcessOptions();
     // Check if the user just wanted to get the help and exit
     if(!comline.GetOption("help").empty()){
       // Print out the "long usage" (i.e. help) message to stdout
       std::cout << comline.LongUsage() << std::endl;
       return(0);
     }
     if(clerr){
       std::cout << comline.ErrorReport() << std::endl
                 << std::endl << comline.ShortUsage() << std::endl;
       return(1);
     }
     // These outstreams allow the output to file to be set up and separated
     // from the stdout.
     std::ofstream Ouf;
     std::ostream *Out = &std::cout;
     // The next few lines populate some strings based on the
     // users input from the commandline.
     std::string OutFileName(comline.GetOption("output"));
     std::vector<std::string> FileNames = comline.GetArgs();
     std::string sverb(comline.GetOption("verblevel"));
     std::string sTolerance(comline.GetOption("tolerance"));
     std::string sNoBlank(comline.GetOption("blank"));
     int retval = 0;
     // The following block parses and sets the verbosity level
     int verblevel = 1;
     if(!sverb.empty()){
       if(sverb != ".true."){
         std::istringstream Istr(sverb);
         Istr >> verblevel;
         if(verblevel < 0)
           verblevel = 1;
       }
     }
     // If the user only wants to compare numbers in the file set the bool for that
     bool numbers = false;
     if(!comline.GetOption("numbers").empty()){
       numbers = true;
     }
     // If there is a tolerance set the bool and convert the tolerance to a double
     bool useTol = false;
     double tolerance = 1.0e-12;
     if(!sTolerance.empty()){
       useTol = true;
       if(sTolerance != ".true."){
         std::istringstream Istr(sTolerance);
         Istr >> tolerance;
       }
     }
     //The tolerance flag must be used if the numbers flag is used
     else if(numbers){
       useTol = true;
     }
     // If the flag to ignore blank space is used set the bool
     bool noBlank = false;
     if(!sNoBlank.empty())
       noBlank = true;
     if(verblevel > 2){
       std::cout << "IRAD::DiffDataFiles> Starting up with the following environment:" << std::endl
                 << "IRAD::DiffDataFiles> FileName1 = " << FileNames[0] << std::endl
                 << "IRAD::DiffDataFiles> FileName2 = " << FileNames[1] << std::endl
                 << "IRAD::DiffDataFiles> Verbosity = " << verblevel << std::endl
                 << "IRAD::DiffDataFiles> OutFileName = " << OutFileName << std::endl
                 << "IRAD::DiffDataFiles> IgnoreBlank = " << noBlank << std::endl
                 << "IRAD::DiffDataFiles> NumbersOnly = " << numbers << std::endl
                 << "IRAD::DiffDataFiles> Tolerance = ";
       if(useTol)
         std::cout << tolerance;
       std::cout << std::endl;
     }
     // This block sets up the output file if the user specified one
     bool keep_outfile = false;
     if(!OutFileName.empty()){
       keep_outfile = true;
       Ouf.open(OutFileName.c_str());
       if(!Ouf){
         std::cout << "IRAD::DiffDataFiles> Error: Could not open output file, "
                   <<  OutFileName << " for output. Exiting (fail)." << std::endl;
         return(1);
       }
       Out = &Ouf;
     }
     // Open the two files for reading
     std::ifstream InFile1;
     std::ifstream InFile2;
     InFile1.open(FileNames[0].c_str());
     if(!InFile1){
       std::cout << "IRAD::DiffDataFiles> Error: Could not open input file, "
                 <<  FileNames[0] << " for reading. Exiting (fail)." << std::endl;
       return(1);
     }
     InFile2.open(FileNames[1].c_str());
     if(!InFile2){
       std::cout << "IRAD::DiffDataFiles> Error: Could not open input file, "
                 <<  FileNames[1] << " for reading. Exiting (fail)." << std::endl;
       return(1);
     }
     // Read in the two files and compare
     std::string line1,line2, string1, string2, printString1="", printString2="";
     std::stringstream ss1, ss2, ssPrint1, ssPrint2;
     int lineNo = 0;
     bool lineDiff = false, numDiff = false;
     *Out << "File     line:              content" << std::endl;
     while(!InFile1.eof() || !InFile2.eof()){
       lineNo++;
       if(!InFile1.eof())
         std::getline(InFile1,line1);
       if(!InFile2.eof())
         std::getline(InFile2,line2);
       //compare line by line as strings(including white space)
       if(!noBlank && !useTol){
         if(line1 != line2){
             ssPrint1 << line1;
             ssPrint2 << line2;
             lineDiff = true;
             retval = 1;
         }
       }
       //compare each individual word in the file
       else{
         ss1 << line1;
         ss2 << line2;
         while(ss1 >> string1){
           ss2 >> string2;
           if(string1 != string2){
             if(useTol){
               if(!isNumber(string1) || !isNumber(string2)){
                 if(!numbers)
                   numDiff = true;
               }
               else{
                 std::stringstream convert;
                 double val1, val2;
                 convert << string1;
                 convert >> val1;
                 convert.clear();
                 convert.str("");
                 convert << string2;
                 convert >> val2;
                 if(fabs(val1 - val2) > tolerance)
                   numDiff = true;
                 else{
                   ssPrint1 << std::scientific << std::setw(20) << val1 << " ";
                   ssPrint2 << std::scientific << std::setw(20) << val2 << " ";
                 }
               }
             }
             if(!useTol || numDiff){
               lineDiff = true;
               retval = 1;
               printString1 += '[' + string1 + "]";
               printString2 += '[' + string2 + "]";
               ssPrint1 << std::setw(20) << printString1 << " ";
               ssPrint2 << std::setw(20) << printString2 << " ";
             }
           }
           else{
             ssPrint1 << std::setw(20) << string1 << " ";
             ssPrint2 << std::setw(20) << string2 << " ";
           }
           string1 = string2 = "";
           printString1 = printString2 = "";
           numDiff = false;
         }
         while(ss2 >> string2){
           if(isNumber(string2) || !numbers){
             lineDiff = true;
             printString1 += '[' + string1 + "]";
             printString2 += '[' + string2 + "]";
             ssPrint1 << std::setw(20) << printString1 << " ";
             ssPrint2 << std::setw(20) << printString2 << " ";
             retval = 1;
           }
         }
         printString1 = printString2 = string2 = "";
       }
       if(lineDiff){
         *Out << std::setw(4) << std::right << "1" << " " << std::setw(8)
              << lineNo << ": " << ssPrint1.str() << std::endl
              << std::setw(4) << std::right << "2" << " " << std::setw(8)
              << lineNo << ": " << ssPrint2.str() << std::endl;
       }
       ss1.clear();
       ss2.clear();
       ss1.str("");
       ss2.str("");
       ssPrint1.clear();
       ssPrint2.clear();
       ssPrint1.str("");
       ssPrint2.str("");
       lineDiff = false;
     }
     if(InFile1.eof() != InFile2.eof()){
       retval = 1;
     }
     if(keep_outfile)
       Ouf.close();
     return(retval);
   }
bool IRAD::isNumber (std::string sCheck)
Definition at line 18 of file DiffDataFiles.C.
References i.
Referenced by DiffDataFiles().
{
     if(sCheck == "")
       return false;
     for(int i=0; i < sCheck.size();i++){
       if(!isdigit(sCheck[i]) && sCheck[i] != 'e' && sCheck[i] != 'E'
          && sCheck[i] != '.' && sCheck[i] != '+' && sCheck[i] != '-'){
         return false;
       }
     }
     return true;
   }
int RunTest (int argc, char * argv[])
Runs test programs and scripts through a standard interface.
Parameters
argc The number of command line arguments
argv The command line arguments
Returns
0 on success, 1 otherwise
Command-line interface for runtest:
       runtest [-h] [-v [level] -o <filename> -l <filename> -f <filename> -H <HostName> -p <filename> ]
       -h,--help
            Print out long version of help and exit.
       -v,--verblevel [level]
            Set the verbosity level. (default = 1)
       -o,--output <filename>
            Set the output file to <filename>. (default = stdout)
       -l,--list <filename>
            Set the list file name to <filename>.The list file should be a text file with one test name per line.
       -f,--file <filename>
            Run the particular test specified by <filename>.
       -H,--hostname <HostName>
       -p,--platforms <filename>
            Set the platforms file to <filename>. (default = ./share/Platforms/platforms)
This function is designed to run complex tests by invoking test programs and scripts.
Definition at line 17 of file RunTest.C.
References ComLineObject::ErrorReport(), IRAD::Sys::FILEEXISTS(), ComLineObject::GetOption(), IRAD::Sys::Hostname(), RTSComLine::Initialize(), ComLineObject::LongUsage(), ComLineObject::ProcessOptions(), IRAD::Sys::Remove(), ComLineObject::ShortUsage(), IRAD::Sys::SymLink(), IRAD::Sys::TempFileName(), and x.
Referenced by main().
   {
     RTSComLine comline((const char **)(argv));
     // The call to comline.Initialize() reads the command line arguments
     // from the array passed in the previous line.
     comline.Initialize();
     // The ProcessOptions() call does detailed examination of the command
     // line arguments to check for user errors or other problems. This call
     // will return non-zero if there were errors on the commandline.
     int clerr = comline.ProcessOptions();
     // Check if the user just wanted to get the help and exit
     if(!comline.GetOption("help").empty()){
       // Print out the "long usage" (i.e. help) message to stdout
       std::cout << comline.LongUsage() << std::endl;
       return(0);
     }
     if(clerr){
       std::cout << comline.ErrorReport() << std::endl
                 << std::endl << comline.ShortUsage() << std::endl;
       return(1);
     }
     // These outstreams allow the output to file to be set up and separated
     // from the stdout.
     //    std::ofstream Ouf;
     //    std::ostream *Out = &std::cout;
     // The next few lines populate some strings based on the
     // users input from the commandline.
     std::string OutFileName(comline.GetOption("output"));
     //    std::string TestName(comline.GetOption("name"));
     std::string ListName(comline.GetOption("list"));
     std::string FileName(comline.GetOption("file"));
     std::string sverb(comline.GetOption("verblevel"));
     std::string HostName(comline.GetOption("hostname"));
     std::string PlatformsName(comline.GetOption("platforms"));
     std::string SourceDirectory(comline.GetOption("srcdir"));
     std::string BinaryDirectory(comline.GetOption("bindir"));
     std::string ScriptArgument(comline.GetOption("argument"));
     if(PlatformsName.empty() && ListName.empty() && FileName.empty()){
       std::cout  << comline.ShortUsage() << std::endl
                  << "IRAD::RunTest> Error: One of --list or --platform or --file"
                  << " must be specified. Exiting (fail)." << std::endl;
       return(1);
     }
     if((!PlatformsName.empty() && !ListName.empty())||
        (!FileName.empty() && (!PlatformsName.empty() || !ListName.empty()))){
       std::cout << comline.ShortUsage() << std::endl;
       std::cout << "IRAD::RunTest> Error: Ambigous settings. --list, --platform, and"
                 << " --file are mutually exclusive. Exiting (fail)." << std::endl;
       return(1);
     }
     if(!HostName.empty() && PlatformsName.empty()){
       std::cout << "IRAD::RunTest> Warning: Hostname option is meaningless without platforms file."
                 << std::endl;
     }
     // The following block parses and sets the verbosity level
     int verblevel = 1;
     if(!sverb.empty()){
       verblevel = 1;
       if(sverb != ".true."){
         std::istringstream Istr(sverb);
         Istr >> verblevel;
         if(verblevel < 0)
           verblevel = 1;
       }
     }
     if(verblevel > 2)
       std::cout << "IRAD::RunTest> Starting up with the following environment:" << std::endl
                 << "IRAD::RunTest> OutFileName = " << OutFileName << std::endl
                 << "IRAD::RunTest> ListName = " << ListName << std::endl
                 << "IRAD::RunTest> FileName = " << FileName << std::endl
                 << "IRAD::RunTest> HostName = " << HostName << std::endl
                 << "IRAD::RunTest> PlatformsName = " << PlatformsName << std::endl
                 << "IRAD::RunTest> SourceDirectory = " << SourceDirectory << std::endl
                 << "IRAD::RunTest> BinaryDirectory = " << BinaryDirectory << std::endl;
     // This block sets up the output file if the user specified one
     bool keep_outfile = false;
     if(!OutFileName.empty()){
       keep_outfile = true;
       //      Ouf.open(OutFileName.c_str());
       //      if(!Ouf){
       //        std::cout << "IRAD::RunTests> Error: Could not open output file, "
       //                  <<  OutFileName << " for test output. Exiting (fail)." << std::endl;
       //        return(1);
       //      }
       //      Out = &Ouf;
     }
     else{
       std::string name_stub("test_script.o");
       IRAD::Sys::TempFileName(name_stub);
       OutFileName = name_stub;
     }
     if(HostName.empty())
       HostName = IRAD::Sys::Hostname();
     //    if(PlatformsName.empty())
     //      PlatformsName = "./share/platforms/parallel_platforms";
     std::string BasePath;
     if(!PlatformsName.empty()){
       // Open up the platforms file and find the host
       std::ifstream PlatInf;
       std::string::size_type x = PlatformsName.find_last_of("/");
       if(x != std::string::npos)
         BasePath.assign(PlatformsName.substr(0,x+1));
       PlatInf.open(PlatformsName.c_str());
       if(!PlatInf){
         std::cout << "IRAD::RunTest> Error: Could not open platforms file, "
                   << PlatformsName << " for resolving platform-specific tests for "
                   << HostName << ". Exiting (fail)." << std::endl;
         return(1);
       }
       //      std::string PlatformFileName;
       std::string splatform;
       while(std::getline(PlatInf,splatform) && ListName.empty()){
         std::istringstream Istr(splatform);
         std::string platform_name;
         std::string running_name;
         Istr >> platform_name >> running_name;
         if(HostName == platform_name)
           ListName.assign(running_name);
       }
       if(ListName.empty()){
         std::cout << "IRAD::RunTest> Error: Could not find a platform file "
                   << "for " << HostName << ". Exiting (fail)." << std::endl;
         return(1);
       }
     }
     // Now we either have a list, or a single named test.
     std::vector<std::string> TestFileNames;
     if(!ListName.empty()){
       // Support both relative and absolute path
       std::ifstream ListInf;
       ListInf.open(ListName.c_str());
       if(!ListInf){
         if(!BasePath.empty()){
           std::string RelName(BasePath+ListName);
           ListInf.open(RelName.c_str());
         }
         if(!ListInf){
           std::cout << "IRAD::RunTest> Error: Could not open list file, "
                     << ListName << ". Exiting (fail)." << std::endl;
           return(1);
         }
       }
       if(BasePath.empty()){
         std::string::size_type x = ListName.find_last_of("/");
         if(x != std::string::npos)
           BasePath.assign(ListName.substr(0,x+1));
       }
       std::string raw_test_name;
       while(std::getline(ListInf,raw_test_name)){
         if(!IRAD::Sys::FILEEXISTS(raw_test_name)){
           std::string RelName(BasePath+raw_test_name);
           if(!IRAD::Sys::FILEEXISTS(RelName)){
             std::cout << "IRAD::RunTest> Warning: Could not find test "
                       << raw_test_name << " from " << ListName << "."
                       << std::endl;
           }
           else{
             TestFileNames.push_back(RelName);
           }
         }
         else{
           TestFileNames.push_back(raw_test_name);
         }
       }
       ListInf.close();
     }
     else { // An explicit filename must have been given
       if(!IRAD::Sys::FILEEXISTS(FileName)){
         std::cout << "IRAD::RunTest> Error: Could not find specified test, "
                   << FileName << ". Exiting (fail)." << std::endl;
         return(1);
       }
       TestFileNames.push_back(FileName);
     }
     // Now we have a list of full paths to tests to run
     int err = 0;
     std::vector<std::string>::iterator ti = TestFileNames.begin();
     while(ti != TestFileNames.end()){
       // The following block simply makes a link to the testing
       // script in the current directory for running.
       std::string TestPath(*ti++);
       std::string TestName(TestPath);
       std::string::size_type x = TestName.find_last_of("/");
       if(x != std::string::npos)
         TestName = TestName.substr(x+1);
       std::string LocalTest("./"+TestName);
       if(verblevel > 1)
         std::cout << "IRAD::RunTest> Linking " << TestPath << " to " << LocalTest << std::endl;
       if(IRAD::Sys::SymLink(TestPath,LocalTest)){
         err++;
         std::cout << "IRAD::RunTest> Warning: Could not create symbolic link "
                   << "to " << TestPath << " at " << LocalTest << "."
                   << std::endl;
       }
       if(verblevel > 1)
         std::cout << "IRAD::RunTest> Running " << TestName << "." << std::endl;
       std::string TmpComOut(IRAD::Sys::TempFileName(OutFileName));
       std::string Command(LocalTest+" "+TmpComOut);
       if(!SourceDirectory.empty())
         Command = Command + " " + SourceDirectory;
       if(!BinaryDirectory.empty())
         Command = Command + " " + BinaryDirectory;
       if(!ScriptArgument.empty())
         Command = Command + " " + ScriptArgument;
       if(verblevel > 1)
         std::cout << "IRAD::RunTest> Running command: " << Command << std::endl;
       IRAD::Sys::InProcess TestProcess(Command);
       std::string testoutline;
       while(std::getline(TestProcess,testoutline)){
         if(verblevel)
           std::cout << testoutline << std::endl;
       }
       IRAD::Sys::Remove(LocalTest);
       std::ifstream ComInf(TmpComOut.c_str());
       if(!ComInf){
         std::cout << "IRAD::RunTest> Warning: Cannot access test results from "
                   << TestName << ". Continuing." << std::endl;
         err++;
       }
       else {
         std::ofstream Ouf;
         Ouf.open(OutFileName.c_str(),std::ios::app);
         if(!Ouf){
           std::cout << "IRAD::RunTest> Error: Cannot open outfile, " << OutFileName
                     << ". Exiting (fail)." << std::endl;
           return(1);
         }
         std::string comline;
         while(std::getline(ComInf,comline))
           Ouf << comline << std::endl;
         ComInf.close();
         Ouf.close();
         IRAD::Sys::Remove(TmpComOut);
       }
     }
     if(err && (verblevel > 1))
       std::cout << "IRAD::RunTest> Warning: " << err << " errors occurred during testing."
                 << std::endl;
     if(!keep_outfile){
       std::ifstream Inf;
       Inf.open(OutFileName.c_str());
       if(!Inf){
         std::cout << "IRAD::RunTest> Error: Could not open test output"
                   << ". Test must have gone wrong.  Exiting (fail)."
                   << std::endl;
         return(1);
       }
       std::string line;
       while(std::getline(Inf,line))
         std::cout << line << std::endl;
       Inf.close();
       IRAD::Sys::Remove(OutFileName);
     }
     return(err);
   }
int TestResults (int argc, char * argv[])
Test results utility.
Parameters
argc integer indicating how many words are in the command line.
argv string words of the command line.
Returns
0 if test was successful, 1 if not.
Usage:
testresults <Name of Test> <File test results>
This utility gets the results of a named test from a file. The file is assumed to have the results from the named tests in the following format:
     NameOfTest1=1 # passed test
     NameOfTest2=0 # failed test
     NameOfTest3 = 1 # also passed
If the test passed, this utility returns a 0, otherwise it returns 1.
Definition at line 15 of file TestResults.C.
References x.
Referenced by main().
   {
     bool verbose = false;
     std::istream *Ins = &std::cin;
     std::ifstream Inf;
     if(argc < 2){
       std::cout << "Usage:\n\n"
                 << argv[0] << " [name of test] <testing results file>"
                 << std::endl;
       return(1);
     }
     std::string name_of_test(argv[1]);
     std::string name_of_results_file(argv[2]);
     if(argc > 2){
       Inf.open(argv[2]);
       if(!Inf){
         std::cout << "Error: Could not open indicated results file, "
                   << argv[2] << "." << std::endl;
         return(1);
       }
       Ins = &Inf;
     }
     if(argc > 3)
       verbose = true;
     std::string line;
     if(verbose)
       std::cout << "Searching for " << name_of_test << " in "
                 << name_of_results_file << std::endl;
     while(std::getline(*Ins,line)){
       std::string::size_type x = line.find("=");
       if(x != std::string::npos){
         std::string testname(line.substr(0,x));
         std::string testresult(line.substr(x+1));
         testname = testname.substr(0,name_of_test.size());
         if(testname == name_of_test){
           if(verbose)
             std::cout << "Found " << name_of_test << ", reading result from "
                       << testresult << std::endl;
           std::istringstream Istr(testresult);
           int result = -1;
           Istr >> result;
           if(result == 1)
             return(0);
           else
             return(1);
         }
       }
     }
     return(1);
   }
int IRAD::TestTCPInterface (int argc, char * argv[])
Test utility for the TCP Interface.
Parameters
argc number of arguments
argv command line token strings
Returns
0 on success, non-zero otherwise
Definition at line 20 of file TestTCPInterface.C.
References Server::Accept(), FDSetMan::AddInDescriptor(), FDSetMan::AddIODescriptor(), Client::Connect(), Server::Descriptor(), Client::Descriptor(), FDSetMan::ReadyForInput(), FDSetMan::ReadyForOutput(), FDSetMan::Select(), Server::SimpleInit(), and cimg_library::cimg::sleep().
Referenced by main().
   {
     if(!argv[1])
       std::exit(1);
     std::string mode(argv[1]);
     if(mode == "server"){
       Sys::Net::Server server;
       server.SimpleInit();
       int mother_descriptor = server.Descriptor();
       int client_descriptor = server.Accept();
       std::cout << "Accepted connection on descriptor: " << client_descriptor
                 << std::endl;
       Sys::FDSetMan setman;
       setman.AddInDescriptor(mother_descriptor);
       setman.AddIODescriptor(client_descriptor);
       bool done = false;
       int nsend = 0;
       int nrecv = 0;
       bool do_output = false;
       bool do_input = false;
       Sys::fdistream clientInStr(client_descriptor);
       Sys::fdostream clientOutStr(client_descriptor);
       while(!done){
         int nio = setman.Select(4.0); // select timeout is 2 seconds
         //      std::cout << nio << " descriptors are ready for io." << std::endl;
         if(setman.ReadyForInput(client_descriptor)){
           std::cout << "Client has input to process." << std::endl;
           do_input = true;
           std::cout << "Receiving message number " << ++nrecv
                     << " from client." << std::endl;
           std::string clientstring;
           std::getline(clientInStr,clientstring);
           std::cout << "Client sent: " << clientstring << std::endl;
           if(clientstring.find("final") != std::string::npos)
             done = true;
           if(!done)
             clientOutStr << "Server recvd " << nrecv << ", sent "
                          << ++nsend << std::endl;
           else
             clientOutStr << "Server recvd " << nrecv << ", send "
                          << ++nsend << " <final>" << std::endl;
         }
       }
     }
     else{
       if(!argv[2])
         std::exit(1);
       std::string host(argv[2]);
       Sys::Net::Client client;
       if(client.Connect(host)){
         std::cerr << "Client failed to connect to " << host << std::endl;
         std::exit(1);
       }
       std::cout << "CLient is connected to " << host << " on "
                 << client.Descriptor() << std::endl;
       Sys::FDSetMan setman;
       setman.AddIODescriptor(client.Descriptor());
       Sys::fdostream fdOut(client.Descriptor());
       Sys::fdistream fdIn(client.Descriptor());
       fdOut << "I am the client, and this is my initial message." << std::endl;
       int nsend = 0;
       int nrecv = 0;
       int nlines = 0;
       bool done = false;
       bool done_sending = false;
       while(!done){
         setman.Select(2.0);
         bool recv_time = (setman.ReadyForInput(client.Descriptor()) > 0);
         bool send_time = (setman.ReadyForOutput(client.Descriptor()) > 0);
         if(recv_time){
           std::cout << "Ready to receive message " << ++nrecv
                     << " from server." << std::endl;
           std::string line;
           std::getline(fdIn,line);
           if(!line.empty())
             std::cout << "line(" << ++nlines << ") from server: " << line << std::endl;
           else
             std::cout << "No line received." << std::endl;
           if(!done_sending){
             std::cout << "Sending message " << ++nsend << " to server." << std::endl;
             fdOut << "I am the client, and I am sending message number " << nsend
                   << std::endl;
             if(nsend == 2)
               done_sending = true;
           }
           else{
             std::cout << "Sending final" << std::endl;
             fdOut << "final" << std::endl;
             done = true;
           }
         }
       }
       std::cout << "These lines were left over: " << std::endl;
       std::string line;
       while(std::getline(fdIn,line))
         std::cout << line << std::endl;
       sleep(30);
     }
     std::exit(0);
   }