Rocstar: Mesh Namespace Reference
Mesh Namespace Reference
Everything mesh.
Functions
int GenerateCartesianGrid (Mesh::NodalCoordinates &nc, Mesh::BSExtent< Mesh::IndexType > &gridextent, std::vector< Mesh::IndexType > &gridsizes, GeoPrim::CBox &box)
template<typename OuterCont , typename OutCont , typename InnerCont , typename MapType >
void MapElements (OuterCont &src, OutCont &trg, MapType &m)
template<typename ListContainerType , typename ListType >
IndexType MaxNodeId (const ListContainerType &fc)
Return the maximum of all elements of a multicontainer.
template<typename OuterCont , typename InnerCont , typename OutCont >
void Flatten (OuterCont &con, OutCont &ocon)
Populate OutCont with a flat list of entries from a multicontainer.
template<typename OuterContType >
IndexType GetTotalSize (OuterContType &con)
Return the total number of entries in a multicontainer.
template<typename OuterContType , typename InnerContType , typename RetCont , typename idxtype >
void Container2CSR (RetCont &xadj, RetCont &adj, OuterContType &source)
template<typename ListContainerType , typename ListType >
void CreateAdjacentNodeList (std::vector< std::list< IndexType > > &anodelist, ListContainerType &fc, IndexType nnodes=0)
Given an array of adjacent node lists (like an array of face connectivities), this function will loop thru and create a list of unique adjacent nodes for each node with the nodes that are actually adjacent in the lists
template<typename ListContainerType , typename ListType >
void AdjEList (std::vector< std::list< IndexType > > &aelist, ListContainerType &dual_con, unsigned long nel=0)
Given an array of adjacent node lists (like an array of face connectivities), this function will loop thru and create a list of unique adjacent nodes for each node Note that this is a little different from the AdjNodeList because in this version every node in each list is considered adjacent.
template<typename ConType , typename IConType >
IndexType NumberOfEdges (ConType &con)
template<typename ContainerType , typename Icont >
void FormGraph (const ContainerType &adjlist)
int ReadMesh (const std::string &path, Mesh::UnstructuredMesh &mesh)
int GetMeshCentroids (Mesh::NodalCoordinates &nc, Mesh::Connectivity &conn, std::vector< double > &centroids)
int CollideCellsWithBox (Mesh::NodalCoordinates &nc, Mesh::Connectivity &conn, GeoPrim::CBox &box, std::vector< Mesh::IndexType > &candidates, std::vector< Mesh::IndexType > &cells)
int CollideMeshWithBox (Mesh::NodalCoordinates &nc, Mesh::Connectivity &conn, GeoPrim::CBox &box, std::vector< Mesh::IndexType > &cells)
bool NewtonRaphson (GeoPrim::CVector &natc, IndexType elnum, const GenericElement &el, const Connectivity &ec, const NodalCoordinates &nc, const GeoPrim::CPoint &point)
Newton-Raphson method, customized for using the GeoPrimitives and computational mesh constructs.
bool NewtonRaphson_2 (GeoPrim::CVector &natc, IndexType elnum, const GenericCell_2 &el, const Connectivity &ec, const NodalCoordinates &nc, const GeoPrim::CPoint &point)
Newton-Raphson method, customized for using the GeoPrimitives and computational mesh constructs.
bool LUDcmp (GeoPrim::CVector a[], int indx[])
void LUBksb (GeoPrim::CVector a[], int indx[], GeoPrim::CVector &b)
void GetCoordinateBounds (NodalCoordinates &nc, std::vector< double > &)
void GetMeshBoxes (const NodalCoordinates &nc, const Connectivity &ec, GeoPrim::CBox &mesh_box, GeoPrim::CBox &small_box, GeoPrim::CBox &large_box)
Bounding boxes for a mesh.
void FindElementsInBox (const GeoPrim::CBox &box, const NodalCoordinates &nc, const Connectivity &dc,std::list< IndexType > &elements)
Get elements in box.
Mesh::IndexType FindPointInCells (const GeoPrim::CPoint &p,const NodalCoordinates &nc,const Connectivity &ec,const std::vector< Mesh::IndexType > &elements,GeoPrim::CVector &natc)
Locate element containing given physical point.
Mesh::IndexType GlobalFindPointInMesh (const GeoPrim::CPoint &p, const NodalCoordinates &nc, const Connectivity &ec, const Connectivity &dc, const GeoPrim::CBox &box, GeoPrim::CVector &natc)
Mesh::IndexType FindPointInMesh_2 (const GeoPrim::CPoint &p,const NodalCoordinates &nc,const Connectivity &ec,const Connectivity &dc,const GeoPrim::CBox &box,GeoPrim::CVector &natc)
Locate element containing given physical point.
Mesh::IndexType FindPointInMesh (const GeoPrim::CPoint &p,const NodalCoordinates &nc,const Connectivity &ec,const Connectivity &dc,const GeoPrim::CBox &box,GeoPrim::CVector &natc)
Locate element containing given physical point.
void writeVtkData ()
Writes the merged grid and its data in VTK UNSTRUCTURED_GRID file format.
void writeVtkFiles (std::vector< Mesh::UnstructuredMesh > &m)
Writes the set of meshes into separate VTK files that can be visualized with Paraview.
void printVtk (std::vector< double > &vlist, std::vector< std::vector< int > > &elist)
This method prints the global grid in VTK file format.
std::istream & operator>> (std::istream &iSt, Mesh::GeometricEntity &ge)
std::istream & operator>> (std::istream &iSt, Mesh::Connectivity &ec)
std::istream & operator>> (std::istream &iSt, Mesh::NodalCoordinates &nc)
std::ostream & operator<< (std::ostream &oSt, const Mesh::NodalCoordinates &nc)
std::ostream & operator<< (std::ostream &oSt, const Mesh::Connectivity &ec)
std::ostream & operator<< (std::ostream &oSt, const Mesh::GeometricEntity &ge)
void writeVtkData (NodalCoordinates &nc, Connectivity &con, const std::string &filename, std::vector< double > &soln)
Writes the merged grid and its data in VTK UNSTRUCTURED_GRID file format.
Detailed Description
Everything mesh.
VTK utilities for the Mesh data structures Author: George Zagaris (gzaga.nosp@m.ris@.nosp@m.illin.nosp@m.ois..nosp@m.edu)
The Mesh namespace encapsulates all the mesh-related data structures and algorithms that operate on them.
Function Documentation
void Mesh::AdjEList (std::vector< std::list< IndexType > > & aelist, ListContainerType & dual_con, unsigned long nel = 0)
Given an array of adjacent node lists (like an array of face connectivities), this function will loop thru and create a list of unique adjacent nodes for each node Note that this is a little different from the AdjNodeList because in this version every node in each list is considered adjacent.
Definition at line 189 of file Mesh.H.
   {
     if(nel == 0)
       nel = MaxNodeId<ListContainerType,ListType>(dual_con);
     aelist.resize(nel);
     typename ListContainerType::iterator lci = dual_con.begin();
     while(lci != dual_con.end())
       {
         typename ListType::iterator li = lci->begin();
         while(li != lci->end()){
           IndexType this_node = *li++ - 1;
           typename ListType::iterator li2 = li;
           while(li2 != lci->end()){
             IndexType nexnode = *li2++ - 1;
             aelist[this_node].push_back(nexnode+1);
             aelist[nexnode].push_back(this_node+1);
           }
         }
         lci++;
       }
     for(IndexType node = 0;node < nel;node++)
       {
         aelist[node].sort();
         aelist[node].unique();
       }
   }
int Mesh::CollideCellsWithBox (Mesh::NodalCoordinates & nc, Mesh::Connectivity & conn, GeoPrim::CBox & box, std::vector< Mesh::IndexType > & candidates, std::vector< Mesh::IndexType > & cells)
Definition at line 128 of file Mesh.C.
References Mesh::Connectivity::Esize(), CBox::intersect(), and Mesh::Connectivity::Node().
Referenced by main().
  {
     std::vector<IndexType>::iterator ci = candidates.begin();
     while(ci != candidates.end()){
       unsigned int cell_id = *ci++;
       unsigned int esize = conn.Esize(cell_id);
       std::vector<GeoPrim::CPoint> element_points(esize);
       // Make a vector of the element points
       for(IndexType node = 1;node <= esize;node++){
         GeoPrim::CPoint ep(nc[conn.Node(cell_id,node)]);
         element_points[node-1] = ep;
       }
       // Make the bounding box for the element
       GeoPrim::CBox ebox(element_points);
       // collide the ebox with the box
       GeoPrim::CBox cbox(box.intersect(ebox));
       if(!cbox.empty())
         cells.push_back(cell_id);
     }
   };
int Mesh::CollideMeshWithBox (Mesh::NodalCoordinates & nc, Mesh::Connectivity & conn, GeoPrim::CBox & box, std::vector< Mesh::IndexType > & cells)
Definition at line 154 of file Mesh.C.
References CBox::empty(), Mesh::Connectivity::Esize(), CBox::intersect(), and Mesh::Connectivity::Node().
Referenced by main().
   {
     unsigned int nelem = conn.size();
     IndexType n = 1;
     while(n <= nelem){
       unsigned int esize = conn.Esize(n);
       std::vector<GeoPrim::CPoint> element_points(esize);
       // Make a vector of the element points
       for(IndexType node = 1;node <= esize;node++){
         GeoPrim::CPoint ep(nc[conn.Node(n,node)]);
         element_points[node-1] = ep;
       }
       // Make the bounding box for the element
       GeoPrim::CBox ebox(element_points);
       // collide the ebox with the box
       GeoPrim::CBox cbox = box.intersect(ebox);
       if(!cbox.empty())
         cells.push_back(n);
       n++;
     }
   };
void Mesh::Container2CSR (RetCont & xadj, RetCont & adj, OuterContType & source)
Definition at line 127 of file Mesh.H.
   {
     IndexType number_of_elements = source.size();
     xadj.resize(number_of_elements+1);
     IndexType number_entries = GetTotalSize<OuterContType>(source);
     adj.reserve(number_entries);
     typename OuterContType::iterator si = source.begin();
     IndexType elm = 0;
     xadj[elm++] = 0;
     while(si != source.end()){
       typename InnerContType::iterator ei = si->begin();
       xadj[elm] = static_cast<idxtype>(si->size() + xadj[elm-1]);
       elm++;
       while(ei != si->end())
         adj.push_back(static_cast<idxtype>(*ei++-1));
       si++;
     }
   };
void Mesh::CreateAdjacentNodeList (std::vector< std::list< IndexType > > & anodelist, ListContainerType & fc, IndexType nnodes = 0)
Given an array of adjacent node lists (like an array of face connectivities), this function will loop thru and create a list of unique adjacent nodes for each node with the nodes that are actually adjacent in the lists
Definition at line 153 of file Mesh.H.
   {
     if(nnodes == 0)
       nnodes = MaxNodeId<ListContainerType,ListType>(fc);
     anodelist.resize(nnodes);
     typename ListContainerType::iterator lci = fc.begin();
     while(lci != fc.end())
       {
         typename ListType::iterator li = lci->begin();
         while(li != lci->end()){
           IndexType this_node = *li++ - 1;
           IndexType next_node = 0;
           if(li == lci->end())
             next_node = *(lci->begin());
           else
             next_node = *li++;
           anodelist[this_node].push_back(next_node);
           anodelist[next_node-1].push_back(this_node+1);
         }
         lci++;
       }
     for(IndexType node = 0;node < nnodes;node++)
       {
         anodelist[node].sort();
         anodelist[node].unique();
       }
   }
void Mesh::FindElementsInBox (const GeoPrim::CBox & box, const NodalCoordinates & nc, const Connectivity & dc, std::list< IndexType > & elements)
Get elements in box.
Given a box in a cartesian space, this function will populate a list<IndexType> with all the elements that lie within.
Inputs: CBox object (see GeoPrimitives.H) NodalCoordinates object ElementConnectivity object DualConnectivity object list<IndexType> stores results
Definition at line 1167 of file Mesh.C.
References CBox::contains(), and i.
Referenced by FindPointInMesh(), and FindPointInMesh_2().
   {
     int nnodes = nc.Size();
     for(int i = 1;i <= nnodes;i++){
       GeoPrim::CPoint p(nc[i]);
       if(box.contains(p)){
         std::vector<IndexType>::const_iterator dci = dc[i-1].begin();
         while(dci != dc[i-1].end()){
           elements.push_back(*dci++);
         }
       }
     }
     if(!elements.empty()){
       elements.sort();
       elements.unique();
     }
   }
Mesh::IndexType Mesh::FindPointInCells (const GeoPrim::CPoint & p, const NodalCoordinates & nc, const Connectivity & ec, const std::vector< Mesh::IndexType > & elements, GeoPrim::CVector & natc)
Locate element containing given physical point.
This function will locate which element in a mesh contains a specified point by constructing a box around the point and solving (by Newton-Raphson) the system for each element that touches the box until the element is found.
Inputs: A point in cartesian, ie (X,Y,Z), coordinates A Nodal Coordinates object for the mesh An Element Connectivity object for the mesh Dual Connectivity object for the mesh CBox specifying the parameters of the box use
Returns: An integer indicating which element in the connectivity object contains the point. A 0 will indicate that the point could not be located.
The natural coordinates of the point in the containing element is returned in natc
Definition at line 1213 of file Mesh.C.
References HTOL, CVector::init(), LTOL, and NewtonRaphson().
Referenced by main(), and test().
   {
     //    GeoPrim::CBox bounds(box.around(p));
     //    std::list<IndexType> elements;
     //    FindElementsInBox(bounds, nc, dc, elements);
     std::vector<IndexType>::const_iterator ei = elements.begin();
     while(ei != elements.end()){
       GeoPrim::CVector guess;
       unsigned int esize = ec.Esize(*ei);
       if(esize == 4 || esize == 10)
         guess.init(.25,.25,.25);
       else if (esize == 8 || esize == 20)
         guess.init(.5,.5,.5);
       else
         assert(false);
       natc.init(guess);
       // Solve the non-linear system using newton-raphson with an
       // initial guess as the center of the theoretical element.
       if(!NewtonRaphson(natc,*ei,GenericElement(esize),ec,nc,p)){
         //      double dist = 0.0;
         //      Mesh::IndexType closest_node = nc.closest_node(p,&dist);
         //      std::cout << "Mesh::FindPointInMesh: Error: Closest approach: " << dist
         //                << " at node " << closest_node << "." << std::endl
         //                << "Mesh::FindPointInMesh: Element(" << *ei << ") = (";
         //      IRAD::Util::DumpContents(std::cout,ec[*ei-1],",");
         //      std::cout << ")" << std::endl;
         //      std::cout << "Point: " << p << std::endl
         //                << "Nodes: " << std::endl;
         //      std::vector<Mesh::IndexType>::const_iterator ni = ec[*ei-1].begin();
         //      while(ni != ec[*ei-1].end()){
         //        std::cout << ni - ec[*ei-1].begin() << ": " << GeoPrim::C3Point(nc[*ni]) << std::endl;
         //        ni++;
         //      }
         //      assert(false);
         return(0);
       }
       if(natc[0] >= LTOL && natc[0] <= HTOL &&
          natc[1] >= LTOL && natc[1] <= HTOL &&
          natc[2] >= LTOL && natc[2] <= HTOL){
         if(esize == 4 || esize == 10){
           if((natc[0]+natc[1]+natc[2]) <= HTOL)
             return (*ei);
         }
         else if(esize == 8 || esize == 20)
           return(*ei);
         else{
           std::cerr << "Mesh::FindPointInMesh: Error: Cannot handle"
                     << " this element type. (yet)" << std::endl;
           exit(1);
         }
       }
       ei++;
     }
     return (0);
   }
Mesh::IndexType Mesh::FindPointInMesh (const GeoPrim::CPoint & p, const NodalCoordinates & nc, const Connectivity & ec, const Connectivity & dc, const GeoPrim::CBox & box, GeoPrim::CVector & natc)
Locate element containing given physical point.
This function will locate which element in a mesh contains a specified point by constructing a box around the point and solving (by Newton-Raphson) the system for each element that touches the box until the element is found.
Inputs: A point in cartesian, ie (X,Y,Z), coordinates A Nodal Coordinates object for the mesh An Element Connectivity object for the mesh Dual Connectivity object for the mesh CBox specifying the parameters of the box use
Returns: An integer indicating which element in the connectivity object contains the point. A 0 will indicate that the point could not be located.
The natural coordinates of the point in the containing element is returned in natc
Definition at line 1298 of file Mesh.C.
References CBox::AddPoint(), CBox::around(), dist(), FindElementsInBox(), HTOL, CVector::init(), LTOL, NewtonRaphson(), and ni.
   {
     GeoPrim::CBox bounds(box.around(p));
     std::list<IndexType> elements;
     FindElementsInBox(bounds, nc, dc, elements);
     std::list<IndexType>::iterator ei = elements.begin();
     while(ei != elements.end()){
       GeoPrim::CVector guess;
       unsigned int esize = ec.Esize(*ei);
       if(esize == 4 || esize == 10)
         guess.init(.25,.25,.25);
       else if (esize == 8 || esize == 20)
         guess.init(.5,.5,.5);
       natc.init(guess);
       // Solve the non-linear system using newton-raphson with an
       // initial guess as the center of the theoretical element.
       if(!NewtonRaphson(natc,*ei,GenericElement(esize),ec,nc,p)){
         double dist = 0.0;
         Mesh::IndexType closest_node = nc.closest_node(p,&dist);
         std::cout << "Mesh::FindPointInMesh: Error: Closest approach: " << dist
                   << " at node " << closest_node << "." << std::endl
                   << "Mesh::FindPointInMesh: Element(" << *ei << ") = (";
         IRAD::Util::DumpContents(std::cout,ec[*ei-1],",");
         std::cout << ")" << std::endl;
         std::vector<Mesh::IndexType>::const_iterator ei2 = dc[closest_node-1].begin();
         GeoPrim::CBox new_bounds;
         while(ei2 != dc[closest_node-1].end()){
           // For every element touching this node
           std::vector<Mesh::IndexType>::const_iterator ni = ec[*ei2-1].begin();
           while(ni != ec[*ei2-1].end())
             new_bounds.AddPoint(nc[*ni++]);
           ei2++;
         }
         std::cout << "Mesh::FindPointInMesh: Bounding box of failed search: "
                   << new_bounds << std::endl;
         return(0);
       }
       if(natc[0] >= LTOL && natc[0] <= HTOL &&
          natc[1] >= LTOL && natc[1] <= HTOL &&
          natc[2] >= LTOL && natc[2] <= HTOL){
         if(esize == 4 || esize == 10){
           if((natc[0]+natc[1]+natc[2]) <= HTOL)
             return (*ei);
         }
         else if(esize == 8 || esize == 20)
           return(*ei);
         else{
           std::cerr << "Mesh::FindPointInMesh: Error: Cannot handle"
                     << " this element type. (yet)" << std::endl;
           exit(1);
         }
       }
       ei++;
     }
     return (0);
   }
Mesh::IndexType Mesh::FindPointInMesh_2 (const GeoPrim::CPoint & p, const NodalCoordinates & nc, const Connectivity & ec, const Connectivity & dc, const GeoPrim::CBox & box, GeoPrim::CVector & natc)
Locate element containing given physical point.
This function will locate which element in a mesh contains a specified point by constructing a box around the point and solving (by Newton-Raphson) the system for each element that touches the box until the element is found.
Inputs: A point in cartesian, ie (X,Y,Z), coordinates A Nodal Coordinates object for the mesh An Element Connectivity object for the mesh Dual Connectivity object for the mesh CBox specifying the parameters of the box use
Returns: An integer indicating which element in the connectivity object contains the point. A 0 will indicate that the point could not be located.
The natural coordinates of the point in the containing element is returned in natc
Definition at line 1386 of file Mesh.C.
References CBox::AddPoint(), CBox::around(), dist(), FindElementsInBox(), HTOL, CVector::init(), LTOL, NewtonRaphson_2(), and ni.
Referenced by main().
   {
     GeoPrim::CBox bounds(box.around(p));
     std::list<IndexType> elements;
     FindElementsInBox(bounds, nc, dc, elements);
     std::list<IndexType>::iterator ei = elements.begin();
     while(ei != elements.end()){
       GeoPrim::CVector guess;
       unsigned int esize = ec.Esize(*ei);
       if(esize == 3 || esize == 6)
         guess.init(.25,.25,0);
       else if (esize == 4 || esize == 8)
         guess.init(.5,.5,0);
       natc.init(guess);
       // Solve the non-linear system using newton-raphson with an
       // initial guess as the center of the theoretical element.
       if(!NewtonRaphson_2(natc,*ei,GenericCell_2(esize),ec,nc,p)){
         double dist = 0.0;
         Mesh::IndexType closest_node = nc.closest_node(p,&dist);
         std::cout << "Mesh::FindPointInMesh: Error: Closest approach: " << dist
                   << " at node " << closest_node << "." << std::endl
                   << "Mesh::FindPointInMesh: Element(" << *ei << ") = (";
         IRAD::Util::DumpContents(std::cout,ec[*ei-1],",");
         std::cout << ")" << std::endl;
         std::vector<Mesh::IndexType>::const_iterator ei2 = dc[closest_node-1].begin();
         GeoPrim::CBox new_bounds;
         while(ei2 != dc[closest_node-1].end()){
           // For every element touching this node
           std::vector<Mesh::IndexType>::const_iterator ni = ec[*ei2-1].begin();
           while(ni != ec[*ei2-1].end())
             new_bounds.AddPoint(nc[*ni++]);
           ei2++;
         }
         std::cout << "Mesh::FindPointInMesh: Bounding box of failed search: "
                   << new_bounds << std::endl;
         return(0);
       }
       if(natc[0] >= LTOL && natc[0] <= HTOL &&
          natc[1] >= LTOL && natc[1] <= HTOL)
         {
           if(esize == 3 || esize == 6){
             if(((natc[0]+natc[1]) <= HTOL))
               return (*ei);
           }
           else if(esize == 4 || esize == 8)
             return(*ei);
           else{
             std::cerr << "Mesh::FindPointInMesh: Error: Cannot handle"
                       << " this element type. (yet)" << std::endl;
             exit(1);
           }
         }
       ei++;
     }
     return (0);
   }
void Mesh::Flatten (OuterCont & con, OutCont & ocon)
Populate OutCont with a flat list of entries from a multicontainer.
Definition at line 101 of file Mesh.H.
{
     typename OuterCont::iterator cci = con.begin();
     ocon.resize(0);
     while(cci != con.end()){
       typename InnerCont::iterator ccni = cci->begin();
       while(ccni != cci->end())
         ocon.push_back(*ccni++);
       cci++;
     }
   };
void Mesh::FormGraph (const ContainerType & adjlist)
Definition at line 239 of file Mesh.H.
   {
     // empty for now
   };
int Mesh::GenerateCartesianGrid (Mesh::NodalCoordinates & nc, Mesh::BSExtent< Mesh::IndexType > & gridextent, std::vector< Mesh::IndexType > & gridsizes, GeoPrim::CBox & box)
Definition at line 13 of file BSMesh.C.
References i, Mesh::BSExtent< T >::Init(), Mesh::NodalCoordinates::init(), j, k, CBox::P1(), CBox::P2(), CPoint::x(), C3Vector::x(), CPoint::y(), C3Vector::y(), z, CPoint::z(), and C3Vector::z().
   {
     if(gridsizes.size() != 3)
       return 1;
     // sizes is ncells
     Mesh::IndexType ncells_x = gridsizes[0];
     Mesh::IndexType ncells_y = gridsizes[1];
     Mesh::IndexType ncells_z = gridsizes[2];
     Mesh::IndexType nnodes_x = ncells_x + 1;
     Mesh::IndexType nnodes_y = ncells_y + 1;
     Mesh::IndexType nnodes_z = ncells_z + 1;
     std::vector<Mesh::IndexType> flatextent(6);
     flatextent[0] = 1;
     flatextent[1] = nnodes_x;
     flatextent[2] = 1;
     flatextent[3] = nnodes_y;
     flatextent[4] = 1;
     flatextent[5] = nnodes_z;
     gridextent.Init(flatextent);
     unsigned int npoints = flatextent[1]*flatextent[3]*flatextent[5];
     nc.init(npoints);
     std::vector<double> xcoords(ncells_x+1);
     std::vector<double> ycoords(ncells_y+1);
     GeoPrim::CPoint p(box.P2() - box.P1());
     double h_x = (ncells_x > 0 ? p.x()/ncells_x : 0);
     double h_y = (ncells_y > 0 ? p.y()/ncells_y : 0);
     double h_z = (ncells_z > 0 ? p.z()/ncells_z : 0);
     for(unsigned int i = 0;i < nnodes_y;i++)
       ycoords[i] = i*h_y + box.P1().y();
     for(unsigned int i = 0;i < nnodes_x;i++)
       xcoords[i] = i*h_x + box.P1().x();
     unsigned int point_id = 1;
     for(unsigned int k = 0;k < nnodes_z;k++){
       double z = k*h_z + box.P1().z();
       for(unsigned int j = 0;j < nnodes_y;j++){
         for(unsigned int i = 0;i < nnodes_x;i++){
           GeoPrim::C3Point gridpoint(nc[point_id++]);
           gridpoint.x() = xcoords[i];
           gridpoint.y() = ycoords[j];
           gridpoint.z() = z;
         }
       }
     }
   }
void Mesh::GetCoordinateBounds (NodalCoordinates & nc, std::vector< double > & bnds)
Definition at line 194 of file Mesh.C.
References max(), and min().
Referenced by main().
   {
     bnds.resize(6);
     bnds[0] = bnds[2] = bnds[4] = std::numeric_limits<double>::max();
     bnds[1] = bnds[3] = bnds[5] = std::numeric_limits<double>::min();
     Mesh::IndexType number_of_nodes = nc.Size();
     for(Mesh::IndexType nn = 1;nn <= number_of_nodes;nn++){
       if(nc.x(nn) < bnds[0])
         bnds[0] = nc.x(nn);
       if(nc.x(nn) > bnds[1])
         bnds[1] = nc.x(nn);
       if(nc.y(nn) < bnds[2])
         bnds[2] = nc.y(nn);
       if(nc.y(nn) > bnds[3])
         bnds[3] = nc.y(nn);
       if(nc.z(nn) < bnds[4])
         bnds[4] = nc.z(nn);
       if(nc.z(nn) > bnds[5])
         bnds[5] = nc.z(nn);
     }
   };
void Mesh::GetMeshBoxes (const NodalCoordinates & nc, const Connectivity & ec, GeoPrim::CBox & mesh_box, GeoPrim::CBox & small_box, GeoPrim::CBox & large_box)
Bounding boxes for a mesh.
This function will determine some bounding boxes for the mesh. Namely, it gets a box for the entire mesh, one for the smallest element and one for the largest.
Definition at line 1125 of file Mesh.C.
References CBox::empty(), and CBox::init().
Referenced by main().
   {
     mesh_box.init(nc[1],nc.size());
     small_box = mesh_box;
     IndexType nelem = ec.Nelem();
     IndexType n = 1;
     while(n <= nelem){
       unsigned int esize = ec.Esize(n);
       std::vector<GeoPrim::CPoint> element_points(esize);
       // Make a vector of the element points
       for(IndexType node = 1;node <= esize;node++){
         GeoPrim::CPoint ep(nc[ec.Node(n,node)]);
         element_points[node-1] = ep;
       }
       // Make the bounding box for the element
       GeoPrim::CBox box(element_points);
       if(!box.empty()){
         if(box < small_box) small_box = box;
         if(box > large_box) large_box = box;
       }
       n++;
     }
   }
int Mesh::GetMeshCentroids (Mesh::NodalCoordinates & nc, Mesh::Connectivity & conn, std::vector< double > & centroids)
Definition at line 180 of file Mesh.C.
References Mesh::GenericElement::Centroid(), and i.
Referenced by main().
   {
     unsigned int nelem = conn.size();
     centroids.resize(3*nelem,0.0);
     for(int i = 0;i < nelem;i++){
       GeoPrim::C3Point p(&(centroids[3*i]));
       Mesh::GenericElement e;
       e.Centroid(conn[i],nc,p);
       //      std::cout << "a" << i+1 << ": " << p << std::endl;
     }
   };
IndexType Mesh::GetTotalSize (OuterContType & con)
Return the total number of entries in a multicontainer.
Definition at line 114 of file Mesh.H.
Referenced by main().
   {
     IndexType total_size = 0;
     typename OuterContType::iterator ci = con.begin();
     while(ci != con.end()){
       total_size += ci->size();
       ci++;
     }
     return(total_size);
   };
Mesh::IndexType Mesh::GlobalFindPointInMesh (const GeoPrim::CPoint & p, const NodalCoordinates & nc, const Connectivity & ec, const Connectivity & dc, const GeoPrim::CBox & box, GeoPrim::CVector & natc)
Definition at line 1642 of file Mesh.C.
References HTOL, CVector::init(), LTOL, and NewtonRaphson().
   {
     GeoPrim::CVector guess;
     int ein = 1;
     int ein_size = ec.Nelem();
     while(ein <= ein_size){
       unsigned int esize = ec.Esize(ein);
       if(esize == 4 || esize == 10)
         guess.init(.25,.25,.25);
       else if (esize == 8 || esize == 20)
         guess.init(.5,.5,.5);
       natc.init(guess);
       // Solve the non-linear system using newton-raphson with an
       // initial guess as the center of the theoretical element.
       if(!NewtonRaphson(natc,ein,GenericElement(esize),ec,nc,p)){
         std::cerr << "GlobalFindPointInMesh: error NewtonRaphson failed."
                   << std::endl;
         return(0);
       }
       if(natc[0] >= LTOL && natc[0] <= HTOL &&
          natc[1] >= LTOL && natc[1] <= HTOL &&
          natc[2] >= LTOL && natc[2] <= HTOL){
         if(esize == 4 || esize == 10){
           if((natc[0]+natc[1]+natc[2]) <= HTOL){
             return (ein);
           }
         }
         else if(esize == 8 || esize == 20)
           return(ein);
         else{
           std::cerr << "GlobalFindPointInMesh: Error: Cannot handle"
                     << " this element type. (yet)" << std::endl;
           exit(1);
         }
       }
       ein++;
     }
     return(0);
   }
void Mesh::LUBksb (GeoPrim::CVector a[], int indx[], GeoPrim::CVector & b)
Definition at line 2047 of file Mesh.C.
References i, and j.
Referenced by NewtonRaphson(), and NewtonRaphson_2().
   {
     int i,ii=0,ip,j;
     double sum;
     for (i=0;i<3;i++) {
       ip=indx[i];
       sum=b[ip];
       b[ip]=b[i];
       if (ii){
         for (j=ii;j<=i-1;j++)
           sum -= a[i][j]*b[j];
       }
       else if (sum)
         ii=i;
       b[i]=sum;
     }
     for (i=2;i>=0;i--) {
       sum=b[i];
       for (j=i+1;j<3;j++)
         sum -= a[i][j]*b[j];
       b[i]=sum/a[i][i];
     }
   }
bool Mesh::LUDcmp (GeoPrim::CVector a[], int indx[])
Definition at line 1988 of file Mesh.C.
References i, j, k, and LUDTINY.
Referenced by NewtonRaphson(), and NewtonRaphson_2().
   {
     int i,j,k;
     int imax = 0;
     double big,dum,sum,temp;
     GeoPrim::CVector vv;
     for (i=0;i<3;i++) {
       big=0.0;
       for (j=0;j<3;j++)
         if ((temp=fabs(a[i][j])) > big) big=temp;
       if (big == 0.0){
         //      std::cerr << "LUDcmp::error: Singular matrix" << std::endl;
         return(false);
       }
       vv[i]=1.0/big;
     }
     for (j=0;j<3;j++) {
       for (i=0;i<j;i++) {
         sum=a[i][j];
         for (k=0;k<i;k++)
           sum -= a[i][k]*a[k][j];
         a[i][j]=sum;
       }
       big=0.0;
       for (i=j;i<3;i++) {
         sum=a[i][j];
         for (k=0;k<j;k++)
           sum -= a[i][k]*a[k][j];
         a[i][j]=sum;
         if ( (dum=vv[i]*fabs(sum)) >= big) {
           big=dum;
           imax=i;
         }
       }
       if (j != imax) {
         for (k=0;k<3;k++) {
           dum=a[imax][k];
           a[imax][k]=a[j][k];
           a[j][k]=dum;
         }
         vv[imax]=vv[j];
       }
       indx[j]=imax;
       if (a[j][j] == 0.0) a[j][j]=LUDTINY;
       if (j != 3) {
         dum=1.0/(a[j][j]);
         for (i=j+1;i<3;i++)
           a[i][j] *= dum;
       }
     }
     return (true);
   }
void Mesh::MapElements (OuterCont & src, OutCont & trg, MapType & m)
Definition at line 68 of file Mesh.H.
Referenced by main().
   {
     trg.resize(src.size());
     typename OuterCont::iterator sci = src.begin();
     typename OutCont::iterator oci = trg.begin();
     while(sci != src.end()){
       typename InnerCont::iterator ici = sci->begin();
       while(ici != sci->end())
         oci->push_back(m[*ici++]);
       sci++;
       oci++;
     }
   };
IndexType Mesh::MaxNodeId (const ListContainerType & fc)
Return the maximum of all elements of a multicontainer.
Definition at line 84 of file Mesh.H.
   {
     IndexType maxid = 0;
     typename ListContainerType::const_iterator lci = fc.begin();
     while(lci != fc.end()){
       typename ListType::const_iterator li = lci->begin();
       while(li != lci->end()){
         if(maxid < *li)
           maxid = *li;
         li++;
       }
     }
     return(maxid);
   };
bool Mesh::NewtonRaphson (GeoPrim::CVector & natc, IndexType elnum, const GenericElement & el, const Connectivity & ec, const NodalCoordinates & nc, const GeoPrim::CPoint & point)
Newton-Raphson method, customized for using the GeoPrimitives and computational mesh constructs.
Parameters: double natc[] = initial guess at the natural coordinates IndexType elnum = index of the mesh element to use const ElementConnectivity &ec = The element connectivity for the mesh const NodalCoordinates &nc = The nodal coordinates for the mesh const CPoint &point = the point at which we wish a solution
Definition at line 1883 of file Mesh.C.
References i, k, LUBksb(), and LUDcmp().
Referenced by FindPointInCells(), FindPointInMesh(), and GlobalFindPointInMesh().
   {
     int k,i;
     int ntrial = 100; // Number of iterations before giving up
     double errx,errf;
     int indx[3];
     double errtol = 1e-12;
     GeoPrim::CVector p;
     GeoPrim::CVector fvec;
     GeoPrim::CVector fjac[3];
     for (k=0;k<ntrial;k++) {
       //      std::cout << k << std::endl;
       el.shapef_jacobian_at(point,natc,elnum,ec,nc,fvec,fjac);
       errf=0.0;
       for (i=0;i<3;i++){
         //      if(fvec[i] < errtol)
         //        fvec[i] = 0.0;
         errf += fabs(fvec[i]);
       }
       if (errf <= errtol)
         return (true);
       p = -1.0 * fvec;
       //      std::cout << "Jac: "  << fjac[0] << std::endl
       //                << "Jac: "  << fjac[1] << std::endl
       //                << "Jac: "  << fjac[2] << std::endl
       //                << "fv : "  << fvec    << std::endl
       //                << "nc : "  << natc    << std::endl
       //        << "err: "  << errf    << std::endl;
       if(!LUDcmp(fjac,indx)){
         //      std::cerr << "NewtonRaphson::error: LUDcmp failed." << std::endl;
         //      std::cout << "Jac: " << fjac[0] << std::endl
         //                << "Jac: " << fjac[1] << std::endl
         //                << "Jac: " << fjac[2] << std::endl;
         return(false);
       }
       LUBksb(fjac,indx,p);
       errx=0.0;
       for (i=0;i<3;i++)
         errx += fabs(p[i]);
       natc += p;
       if (errx <= errtol)
         return (true);
     }
     //    std::cerr << "NewtonRaphson::warning: reached maximum iterations" << std::endl;
     return (false);
   }
bool Mesh::NewtonRaphson_2 (GeoPrim::CVector & natc, IndexType elnum, const GenericCell_2 & el, const Connectivity & ec, const NodalCoordinates & nc, const GeoPrim::CPoint & point)
Newton-Raphson method, customized for using the GeoPrimitives and computational mesh constructs.
Parameters: double natc[] = initial guess at the natural coordinates IndexType elnum = index of the mesh element to use const ElementConnectivity &ec = The element connectivity for the mesh const NodalCoordinates &nc = The nodal coordinates for the mesh const CPoint &point = the point at which we wish a solution
Definition at line 1946 of file Mesh.C.
References i, k, LUBksb(), LUDcmp(), and TOL.
Referenced by FindPointInMesh_2().
   {
     int k,i;
     int ntrial = 10; // Number of iterations before giving up
     double errx,errf;
     int indx[3];
     GeoPrim::CVector p;
     GeoPrim::CVector fvec;
     GeoPrim::CVector fjac[3];
     for (k=0;k<ntrial;k++) {
       el.shapef_jacobian_at(point,natc,elnum,ec,nc,fvec,fjac);
       errf=0.0;
       for (i=0;i<3;i++)
         errf += fabs(fvec[i]);
       if (errf <= TOL)
         return (true);
       p = -1.0 * fvec;
       if(!LUDcmp(fjac,indx)){
         //      std::cerr << "NewtonRaphson::error: LUDcmp failed." << std::endl;
         return(false);
       }
       LUBksb(fjac,indx,p);
       errx=0.0;
       for (i=0;i<3;i++)
         errx += fabs(p[i]);
       natc += p;
       if (errx <= TOL)
         return (true);
     }
     //    std::cerr << "NewtonRaphson::warning: reached maximum iterations" << std::endl;
     return (false);
   }
IndexType Mesh::NumberOfEdges (ConType & con)
Definition at line 218 of file Mesh.H.
   {
     typename ConType::iterator ci = con.begin();
     IndexType node = 0;
     IndexType nedges = 0;
     while(ci != con.end())
       {
         IndexType tnode = ++node;
         typename IConType::iterator eni = ci->begin();
         while(eni != ci->end())
           {
             IndexType anode = *eni++;
             if((tnode) < anode)
               nedges++;
           }
         ci++;
       }
     return(nedges);
   }
std::ostream& Mesh::operator<< (std::ostream & oSt, const Mesh::NodalCoordinates & nc)
Definition at line 2128 of file Mesh.C.
References Mesh::NodalCoordinates::size().
   {
     //  if(nc.size() == 0) return(oSt);
     oSt.setf(std::ios::scientific);
     oSt.setf(std::ios::showpoint);
     oSt << std::setprecision(10) << std::setiosflags(std::ios::left);
     oSt << nc.size();
     if(nc.size() > 0) oSt << "\n";
     for(IndexType n = 1;n <= nc.size() ;n++){
       oSt << std::setw(16) << nc[n][0] << "\t"
           << std::setw(16) << nc[n][1] << "\t"
           << std::setw(16) << nc[n][2];
       if(n != nc.size())
         oSt << std::endl;
     }
     return (oSt);
   }
std::ostream& Mesh::operator<< (std::ostream & oSt, const Mesh::Connectivity & ec)
Definition at line 2146 of file Mesh.C.
References ni.
   {
     oSt << std::setiosflags(std::ios::left) << ec.size();
     if(ec.size() == 0) return(oSt);
     oSt << "\n";
     Mesh::Connectivity::const_iterator ci = ec.begin();
     while(ci != ec.end()){
       std::vector<IndexType>::const_iterator ni = ci->begin();
       while(ni != ci->end()){
         oSt << *ni++;
         if(ni != ci->end())
           oSt << "\t";
       }
       ci++;
       if(ci != ec.end())
         oSt << "\n";
     }
     return(oSt);
   }
std::ostream& Mesh::operator<< (std::ostream & oSt, const Mesh::GeometricEntity & ge)
Definition at line 2166 of file Mesh.C.
References Mesh::GeometricEntity::_collections.
   {
     if(ge.first.empty()) return(oSt);
     oSt << std::setiosflags(std::ios::left) << ge.first << "\n";
     oSt << ge._collections;
     return(oSt);
   }
std::istream& Mesh::operator>> (std::istream & iSt, Mesh::GeometricEntity & ge)
Definition at line 2074 of file Mesh.C.
References Mesh::GeometricEntity::_collections.
   {
     std::string line;
     std::getline(iSt,line);
     std::istringstream Istr(line);
     Istr >> ge.first;
     iSt >> ge._collections;
     ge.second = ge._collections.size();
     return(iSt);
   }
std::istream& Mesh::operator>> (std::istream & iSt, Mesh::Connectivity & ec)
Definition at line 2085 of file Mesh.C.
References Mesh::Connectivity::_nelem, i, Mesh::Connectivity::Resize(), and swap().
   {
     std::string line;
     std::getline(iSt,line);
     std::istringstream Istr(line);
     IndexType nelem = 0;
     Istr >> nelem;
     if(nelem > 0){
       ec.Resize(nelem);
       ec._nelem = nelem;
       for(IndexType i = 0;i < nelem;i++){
         std::getline(iSt,line);
         std::istringstream Istr2(line);
         IndexType node;
         ec[i].reserve(8);
         while(Istr2 >> node)
           ec[i].push_back(node);
         std::vector<Mesh::IndexType>(ec[i]).swap(ec[i]);
       }
     }
     return(iSt);
   }
std::istream& Mesh::operator>> (std::istream & iSt, Mesh::NodalCoordinates & nc)
Definition at line 2108 of file Mesh.C.
References Mesh::NodalCoordinates::init(), and Mesh::NodalCoordinates::size().
   {
     //  if(nc.size() == 0) return (iSt);
     std::string line;
     IndexType nnodes;
     std::getline(iSt,line);
     std::istringstream Istr(line);
     Istr >> nnodes;
     if(nnodes > 0){
       nc.init(nnodes);
       for(IndexType n = 1;n <= nc.size();n++){
         double *inPtr = nc[n];
         std::getline(iSt,line);
         std::istringstream Istr2(line);
         Istr2 >> inPtr[0] >> inPtr[1] >> inPtr[2];
       }
     }
     return(iSt);
   }
void Mesh::printVtk (std::vector< double > & vlist, std::vector< std::vector< int > > & elist)
This method prints the global grid in VTK file format.
Note
Mostly used for debugging.
Parameters
vlist the global vertex list.
elist the element list.
Definition at line 73 of file MeshVTK.C.
References i, and j.
   {
     std::ofstream ofs;
     ofs.open( std::string( "global_mesh.vtk" ).c_str( ) );
     if( !ofs.is_open( ) )
       {
         std::cerr << "Cannot write global VTK file! " << std::endl;
         std::cerr << "File: " << __FILE__                                               << std::endl;
         std::cerr << "Line: " << __LINE__                                               << std::endl;
         assert( false );
       }
     ofs << "# vtk DataFile Version 3.0\n";
     ofs << "Global Mesh Output" << std::endl;
     ofs << "ASCII\n";
     ofs << "DATASET UNSTRUCTURED_GRID\n";
     ofs << "POINTS " << vlist.size( )/3 << " double\n";
     for( int i=0; i < vlist.size( )/3; ++i )
       {
         ofs << vlist[ i*3   ] << " ";
         ofs << vlist[ i*3+1 ] << " ";
         ofs << vlist[ i*3+2 ] << "\n";
       }
     int maxnodes = 0; /* the maximum number of nodes per element */
     for( int i=0; i < elist.size( ); ++i )
       {
         if( maxnodes < elist[ i ].size( ) )
           maxnodes = elist[ i ].size( );
       }
     ofs << "CELLS " << elist.size( ) << " " << elist.size( )*( maxnodes+1) << "\n";
     for( int i=0; i < elist.size( ); ++i  )
       {
         ofs <<  elist[ i ].size( ) << " ";
         for( int j=0; j < elist[ i ].size( ); ++j )
           ofs <<  elist[ i ][ j ]<< " ";
         ofs << std::endl;
       }
     ofs << "CELL_TYPES " << elist.size( ) << std::endl;
     for( int i=0; i < elist.size( ); ++i )
       {
         if( elist[ i ].size( ) == 8 )
           ofs << "12\n";
         else if( elist[ i ].size( ) == 4 )
           ofs << "10\n";
         else {
           std::cerr << "Undefined element type!\n";
           std::cerr << "File: " << __FILE__ << std::endl;
           std::cerr << "Line: " << __LINE__ << std::endl;
         }
       }
     ofs.close( );
   }
int Mesh::ReadMesh (const std::string & path, Mesh::UnstructuredMesh & mesh)
Definition at line 1694 of file Mesh.C.
References Mesh::UnstructuredMesh::con, and Mesh::UnstructuredMesh::nc.
   {
     std::ifstream Inf;
     Inf.open(path.c_str());
     if(!Inf)
       return(1);
     Inf >> mesh.nc >> mesh.con;
     if(!Inf)
       return(1);
     Inf.close();
     return(0);
   }
void Mesh::writeVtkData ()
Writes the merged grid and its data in VTK UNSTRUCTURED_GRID file format.
Precondition
Program.globalNodeList.size() > 0.
Program.globalElementList.size() > 0.
Program.smdv.size() > 0.
Program.globalSolution.size() == Program.smdv.size().
Program.solutionignore.size() == Program.smdv.size().
Program.outputfile != ""
Postcondition
A VTK formatted file is written in Program.outputfile.vtk
Note
The extension in the outputfile will be appended.
Definition at line 645 of file hdf2pltV2.C.
References CELLDATA, i, j, NODEDATA, and Program.
Referenced by printWindow().
 {
         std::cout << "Writing VTK data...";
         std::cout.flush( );
         #ifdef ASSERT_ON
                 assert( Program.globalNodeList.size( ) >  0     );
                 assert( Program.globalElementList.size( ) > 0 );
                 assert( Program.smdv.size( ) > 0 );
                 assert( Program.globalSolution.size( ) == Program.smdv.size( ) );
                 assert( Program.solutionignore.size( ) == Program.smdv.size( ) );
                 assert( Program.outputfile != "" );
         #endif
         std::ofstream ofs;
         ofs.open( std::string(Program.outputfile + ".vtk").c_str( ) );
         if( !ofs.is_open( ) )
         {
                 std::cerr << "Cannot write VTK file: " << Program.outputfile+".vtk" << std::endl;
                 std::cerr << "File: " << __FILE__                << std::endl;
                 std::cerr << "Line: " << __LINE__                << std::endl;
                 assert( false );
         }
         /* STEP 1: Write the header */
         ofs << "# vtk DataFile Version 3.0\n";
         ofs << "Global Mesh Output" << std::endl;
         ofs << "ASCII\n";
         ofs << "DATASET UNSTRUCTURED_GRID\n";
         ofs << "POINTS " << Program.globalNodeList.size( )/3 << " double\n";
         /* STEP 2: Write the nodes */
         for( int i=0; i < Program.globalNodeList.size( )/3; ++i )
         {
                 ofs << Program.globalNodeList[ i*3       ] << " ";
                 ofs << Program.globalNodeList[ i*3+1 ] << " ";
                 ofs << Program.globalNodeList[ i*3+2 ] << std::endl;
         }
         /* STEP 3: Write the max element size */
         int maxnodes = 0; /* the maximum number of nodes per element */
         for( int i=0; i < Program.globalElementList.size( ); ++i )
         {
                 if( maxnodes < Program.globalElementList[ i ].size( ) )
                         maxnodes = Program.globalElementList[ i ].size( );
         }
         /* STEP 4: Write the element connectivity */
         ofs << "CELLS " << Program.globalElementList.size( ) << " " << Program.globalElementList.size( )*( maxnodes+1) << "\n";
         for( int i=0; i < Program.globalElementList.size( ); ++i  )
         {
                 ofs <<  Program.globalElementList[ i ].size( ) << " ";
                 for( int j=0; j < Program.globalElementList[ i ].size( ); ++j )
                         ofs <<  Program.globalElementList[ i ][ j ]<< " ";
                 ofs << std::endl;
         }
         /* STEP 5: Write the cell types */
         ofs << "CELL_TYPES " << Program.globalElementList.size( ) << std::endl;
         for( int i=0; i < Program.globalElementList.size( ); ++i )
         {
                 if( Program.globalElementList[ i ].size( ) == 8 )
                         ofs << "12\n";
                 else if( Program.globalElementList[ i ].size( ) == 4 )
                         ofs << "10\n";
                 else {
                         std::cerr << "Undefined element type!\n";
                         std::cerr << "File: " << __FILE__ << std::endl;
                         std::cerr << "Line: " << __LINE__ << std::endl;
                 }
         }
         /* STEP 6: Write the solution data attached to the points */
         bool wroteHeader = false;
         for( int i=0; i < Program.globalSolution.size( ); ++i )
         {
                 if( ! Program.solutionignore[ i ] && Program.getDataItemType( i ) == NODEDATA  )
                 {
                         int N = Program.globalNodeList.size( )/3;
                         int NC      = Program.smdv[ i ].ncomp;
                         if(!wroteHeader)
{
                                 ofs << "POINT_DATA " << N << std::endl;
                                 wroteHeader = true;
                         }
                         if( NC == 1 )
{
                                         ofs << "SCALARS " << Program.smdv[ i ].name << " double" << std::endl;
                                         ofs << "LOOKUP_TABLE default\n";
                         }
                         else if( NC == 3 )
{
                                 ofs << "VECTORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         else
{
                                 ofs << "TENSORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         for( int j=0; j < N; ++j )
{
                                 for( int component=0; component < NC; ++component )
{
                                         ofs << Program.globalSolution[ i ][ j*NC+component ] << " ";
                                 }
                                 ofs << std::endl;
                         }
                 } /* End if the solution is not ignored */
         } /* End for all solution data */
         /* STEP 6: Write the solution data attached to the cells */
         wroteHeader = false;
         for( int i=0; i < Program.globalSolution.size( ); ++i )
         {
                 if( ! Program.solutionignore[ i ] && Program.getDataItemType( i ) == CELLDATA )
                 {
                         int N                   = Program.globalElementList.size();
                         int NC      = Program.smdv[ i ].ncomp;
                         if( !wroteHeader )
{
                                 ofs << "CELL_DATA " << N << std::endl;
                                 wroteHeader = true;
                         }
                         if( NC == 1 )
{
                                         ofs << "SCALARS " << Program.smdv[ i ].name << " double" << std::endl;
                                         ofs << "LOOKUP_TABLE default\n";
                         }
                         else if( NC == 3 )
{
                                 ofs << "VECTORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         else
{
                                 ofs << "TENSORS " << Program.smdv[ i ].name << " double" << std::endl;
                         }
                         for( int j=0; j < N; ++j )
{
                                 for( int component=0; component < NC; ++component )
{
                                         ofs << Program.globalSolution[ i ][ j*NC+component ] << " ";
                                 }
                                 ofs << std::endl;
                         }
                 } /* End if the solution is not ignored */
         } /* End for all solution data */
         ofs.close( );
         std::cout << "[DONE]\n";
 }
void Mesh::writeVtkData (NodalCoordinates & nc, Connectivity & con, const std::string & filename, std::vector< double > & soln)
Writes the merged grid and its data in VTK UNSTRUCTURED_GRID file format.
Precondition
Program.globalNodeList.size() > 0.
Program.globalElementList.size() > 0.
Program.smdv.size() > 0.
Program.globalSolution.size() == Program.smdv.size().
Program.solutionignore.size() == Program.smdv.size().
Program.outputfile != ""
Postcondition
A VTK formatted file is written in Program.outputfile.vtk
Note
The extension in the outputfile will be appended.
Definition at line 143 of file MeshVTK.C.
References i, and j.
   {
     std::cout << "Writing VTK data...";
     std::cout.flush( );
     std::ofstream ofs;
     ofs.open( filename.c_str());
     if( !ofs.is_open( ) )
       {
         std::cerr << "Cannot write VTK file: " << filename << std::endl;
         std::cerr << "File: " << __FILE__                << std::endl;
         std::cerr << "Line: " << __LINE__                << std::endl;
         assert( false );
       }
     unsigned int nnodes = nc.NNodes();
     /* STEP 1: Write the header */
     ofs << "# vtk DataFile Version 3.0\n";
     ofs << "Global Mesh Output" << std::endl;
     ofs << "ASCII\n";
     ofs << "DATASET UNSTRUCTURED_GRID\n";
     ofs << "POINTS " << nnodes << " double\n";
     /* STEP 2: Write the nodes */
     for( int i=1; i < nnodes; ++i )
       {
         ofs << GeoPrim::C3Point(&(nc[i])) << std:endl;
       }
     /* STEP 3: Write the max element size */
     int maxnodes = 0; /* the maximum number of nodes per element */
     unsigned int nelem = con.size();
     con.SyncSizes();
     for( int i=0; i < nelem; ++i )
       {
         unsigned int esize = con[i].size();
         if(maxnodes < esize)
           maxnodes = esize;
       }
     /* STEP 4: Write the element connectivity */
     ofs << "CELLS " << nelem << " " << nelem*( maxnodes+1) << "\n";
     for( int i=0; i < nelem; ++i  )
       {
         ofs <<  con.Esize(i) << " ";
         for( int j=0; j < con.Esize(i); ++j )
           ofs <<  con[ i ][ j ]-1 << " ";
         ofs << std::endl;
       }
     /* STEP 5: Write the cell types */
     ofs << "CELL_TYPES " << nelem << std::endl;
     for( int i=0; i < nelem; ++i )
       {
         if( con.Esize(i) == 8 )
           ofs << "12\n";
         else if( con.Esize(i) == 4 )
           ofs << "10\n";
         else {
           std::cerr << "Undefined element type!\n";
           std::cerr << "File: " << __FILE__ << std::endl;
           std::cerr << "Line: " << __LINE__ << std::endl;
         }
       }
     /* STEP 6: Write the solution data attached to the points */
      bool wroteHeader = false;
      std::vector<std::string> Name(5);
      Name[0] = "rho";
      Name[1] = "rho-u";
      Name[2] = "rho-v";
      Name[3] = "rho-w";
      Name[4] = "rho-E";
      if(!soln.empty()){
        for( int i=0; i < 5; ++i )
          {
            if( !wroteHeader )
              {
                ofs << "CELL_DATA " << nelem << std::endl;
                wroteHeader = true;
              }
            ofs << "SCALARS " << Name[i] << " double" << std::endl;
            ofs << "LOOKUP_TABLE default\n";
            for( int j=0; j < nelem; ++j )
              {
                ofs << soln[ i*nelem + j ] << " ";
              }
            ofs << std::endl;
          }
      }
      ofs.close( );
      std::cout << "[DONE]\n";
   }
void Mesh::writeVtkFiles (std::vector< Mesh::UnstructuredMesh > & m)
Writes the set of meshes into separate VTK files that can be visualized with Paraview.
The format of the files is {outputFile}.paneId.vtk.
Note
This method is mainly used for debugging.
Parameters
m the set of meshes.
Definition at line 9 of file MeshVTK.C.
References i, and j.
   {
     // TODO: Generalize this function for any type of mesh.
     for( int m=0; m < meshes.size( ); ++m )
       {
         std::ostringstream oss; oss.clear( );
         oss << Program.outputfile << "." << Program.paneIds[ m ] << ".vtk";
         std::ofstream ofs;
         ofs.open( oss.str( ).c_str( ) );
         if( !ofs.is_open( ) )
           {
             std::cerr << "Cannot write VTK file: " << oss.str( ) << std::endl;
             std::cerr << "File: " << __FILE__ << std::endl;
             std::cerr << "Line: " << __LINE__ << std::endl;
             assert( false );
           }
         ofs << "# vtk DataFile Version 3.0\n";
         ofs << oss.str( ) << std::endl;
         ofs << "ASCII\n";
         ofs << "DATASET UNSTRUCTURED_GRID\n";
         ofs << "POINTS " << meshes[ m ].nc.Size( ) << " double\n";
         for( int i=1; i <= meshes[ m ].nc.Size( ); ++i )
           {
             ofs << meshes[ m ].nc.x( i ) << " ";
             ofs << meshes[ m ].nc.y( i ) << " ";
             ofs << meshes[ m ].nc.z( i ) << "\n";
           }
         ofs << "CELLS " << meshes[ m ].con.Nelem( ) << " " << meshes[ m ].con.Nelem( )*9 << "\n";
         for( int e=1; e <= meshes[ m ].con.Nelem( ); ++e )
           {
             ofs <<  "8 ";
             for( int j=1; j <= 8; ++j )
               ofs << meshes[ m ].con.Node( e, j )-1<< " ";
             ofs << std::endl;
           }
         ofs << "CELL_TYPES " << meshes[ m ].con.Nelem( ) << std::endl;
         for( int e=1; e <= meshes[ m ].con.Nelem( ); ++ e )
           ofs << "12\n";
         ofs << "POINT_DATA " << Program.mask[ m ].size( ) << std::endl;
         ofs << "SCALARS SharedNodes double\nLOOKUP_TABLE default\n";
         for( int i=0; i < Program.mask[ m ].size( ); ++i )
           {
             if( Program.mask[ m ][ i ] )
               ofs << "1\n";
             else
               ofs << "0\n";
           }
         ofs.close( );
       }
   }