Rocstar: Numerics Namespace Reference
Numerics Namespace Reference
Functions
double AbsoluteValue (double a)
Returns the absolute value of the value a.
double ___safe_fpt_division (const double f1, const double f2)
Performs a safe floating point division f1/f2.
bool fpointequals (const double a, const double b, double TOL=1e-9)
Checks if two floating numbers are "nearly" equal.
Function Documentation
double Numerics::___safe_fpt_division (const double f1, const double f2) inline
Performs a safe floating point division f1/f2.
Parameters
f1 numerator
f2 denominator
Returns
f1/f2
Precondition
f1 >= 0
f2 >= 0
Postcondition
0 <= f1/f2 <= std::numeric_limits<double>::max()
Definition at line 37 of file FloatingPointComparisson.hpp.
References max(), and min().
Referenced by fpointequals().
{
                                         #ifdef ASSERT_ON
                                          assert( f1 >= static_cast< double >( 0 ) );
                                          assert( f2 >= static_cast< double >( 0 ) );
                                         #endif
                                          /* Avoid overflow */
                                          if( f2 < static_cast< double >( 1 ) && f1 > f2*std::numeric_limits< double >::max( ) )
                                                  return std::numeric_limits<double>::max( );
                                          /* Avoid underflow */
                                          if( f1 == static_cast< double >( 0 ) ||
                                          f2 > static_cast< double >( 1 ) && f1 < f2*std::numeric_limits< double >::min( ) )
                                                  return static_cast< double >( 0 );
                                          return( f1/f2 );
                                  }
double Numerics::AbsoluteValue (double a) inline
Returns the absolute value of the value a.
Parameters
a the value whose absolute value is queried
Returns
abs the absolute value of a abs(a).
Postcondition
abs > 0
Definition at line 23 of file FloatingPointComparisson.hpp.
Referenced by fpointequals().
{
                                  return( ( ( a < static_cast< double >( 0 ) )? -a : a ) );
                          }
bool Numerics::fpointequals (const double a, const double b, double TOL = 1e-9) inline
Checks if two floating numbers are "nearly" equal.
Parameters
a first floating number to check
b second floating number to check
Returns
s true if a =~ b, else false.
Note
This implementation is based on Knuth, The Art of Computer Programming (vol II).
Definition at line 64 of file FloatingPointComparisson.hpp.
References ___safe_fpt_division(), AbsoluteValue(), and GeoPrim::TOL.
Referenced by BoundingBox::hasPoint().
{
                                          double diff      = a-b;
                                          double adiff     = AbsoluteValue( diff );
                                          double d1                = ___safe_fpt_division( adiff, AbsoluteValue( a ) );
                                          double d2                = ___safe_fpt_division( adiff, AbsoluteValue( b ) );
                                          bool predicate1  = (d1 <= TOL);
                                          bool predicate2  = (d2 <= TOL);
                                          if( (predicate1 || predicate2) )
                                                  return true;
                                          return false;
                                  }