Rocstar: cimg_library::cimg Namespace Reference
cimg_library::cimg Namespace Reference
Namespace that encompasses low-level functions and variables of the CImg Library.
Classes
struct last
struct superset
struct superset2
struct superset3
struct superset< bool, char >
struct superset< bool, double >
struct superset< bool, float >
struct superset< bool, int >
struct superset< bool, long >
struct superset< bool, short >
struct superset< bool, signed char >
struct superset< bool, unsigned char >
struct superset< bool, unsigned int >
struct superset< bool, unsigned long >
struct superset< bool, unsigned short >
struct superset< char, double >
struct superset< char, float >
struct superset< char, int >
struct superset< char, long >
struct superset< char, short >
struct superset< char, signed char >
struct superset< char, unsigned char >
struct superset< char, unsigned int >
struct superset< char, unsigned long >
struct superset< char, unsigned short >
struct superset< float, double >
struct superset< int, double >
struct superset< int, float >
struct superset< int, long >
struct superset< int, unsigned int >
struct superset< int, unsigned long >
struct superset< long, double >
struct superset< long, float >
struct superset< short, double >
struct superset< short, float >
struct superset< short, int >
struct superset< short, long >
struct superset< short, unsigned int >
struct superset< short, unsigned long >
struct superset< short, unsigned short >
struct superset< signed char, char >
struct superset< signed char, double >
struct superset< signed char, float >
struct superset< signed char, int >
struct superset< signed char, long >
struct superset< signed char, short >
struct superset< signed char, unsigned char >
struct superset< signed char, unsigned int >
struct superset< signed char, unsigned long >
struct superset< signed char, unsigned short >
struct superset< unsigned char, char >
struct superset< unsigned char, double >
struct superset< unsigned char, float >
struct superset< unsigned char, int >
struct superset< unsigned char, long >
struct superset< unsigned char, short >
struct superset< unsigned char, signed char >
struct superset< unsigned char, unsigned int >
struct superset< unsigned char, unsigned long >
struct superset< unsigned char, unsigned short >
struct superset< unsigned int, char >
struct superset< unsigned int, double >
struct superset< unsigned int, float >
struct superset< unsigned int, int >
struct superset< unsigned int, long >
struct superset< unsigned int, short >
struct superset< unsigned int, signed char >
struct superset< unsigned int, unsigned long >
struct superset< unsigned long, char >
struct superset< unsigned long, double >
struct superset< unsigned long, float >
struct superset< unsigned long, int >
struct superset< unsigned long, long >
struct superset< unsigned long, short >
struct superset< unsigned long, signed char >
struct superset< unsigned short, char >
struct superset< unsigned short, double >
struct superset< unsigned short, float >
struct superset< unsigned short, int >
struct superset< unsigned short, long >
struct superset< unsigned short, short >
struct superset< unsigned short, signed char >
struct superset< unsigned short, unsigned int >
struct superset< unsigned short, unsigned long >
struct type
struct type< bool >
struct type< char >
struct type< double >
struct type< float >
struct type< int >
struct type< long >
struct type< short >
struct type< signed char >
struct type< unsigned char >
struct type< unsigned int >
struct type< unsigned long >
struct type< unsigned short >
Functions
void info ()
Print informations about CImg environement variables.
unsigned int & exception_mode ()
Get/set the current CImg exception mode.
int dialog (const char *title, const char *msg, const char *button1_txt="OK", const char *button2_txt=0, const char *button3_txt=0, const char *button4_txt=0, const char *button5_txt=0, const char *button6_txt=0, const bool centering=false)
double eval (const char *const expression, const double x=0, const double y=0, const double z=0, const double v=0)
Evaluate math expression.
void warn (const char *format,...)
Display a warning message.
int system (const char *const command, const char *const module_name=0)
template<typename T >
T & temporary (const T &)
Return a reference to a temporary variable of type T.
template<typename T >
void swap (T &a, T &b)
Exchange values of variables a and b.
template<typename T1 , typename T2 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2)
Exchange values of variables (a1,a2) and (b1,b2).
template<typename T1 , typename T2 , typename T3 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3)
Exchange values of variables (a1,a2,a3) and (b1,b2,b3).
template<typename T1 , typename T2 , typename T3 , typename T4 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4)
Exchange values of variables (a1,a2,...,a4) and (b1,b2,...,b4).
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4, T5 &a5, T5 &b5)
Exchange values of variables (a1,a2,...,a5) and (b1,b2,...,b5).
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4, T5 &a5, T5 &b5, T6 &a6, T6 &b6)
Exchange values of variables (a1,a2,...,a6) and (b1,b2,...,b6).
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4, T5 &a5, T5 &b5, T6 &a6, T6 &b6, T7 &a7, T7 &b7)
Exchange values of variables (a1,a2,...,a7) and (b1,b2,...,b7).
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
void swap (T1 &a1, T1 &b1, T2 &a2, T2 &b2, T3 &a3, T3 &b3, T4 &a4, T4 &b4, T5 &a5, T5 &b5, T6 &a6, T6 &b6, T7 &a7, T7 &b7, T8 &a8, T8 &b8)
Exchange values of variables (a1,a2,...,a8) and (b1,b2,...,b8).
bool endianness ()
Return the current endianness of the CPU.
template<typename T >
void invert_endianness (T *const buffer, const unsigned int size)
Invert endianness of a memory buffer.
template<typename T >
T & invert_endianness (T &a)
Invert endianness of a single variable.
unsigned long time ()
Get the value of a system timer with a millisecond precision.
void sleep (const unsigned int milliseconds)
Sleep for a certain numbers of milliseconds.
unsigned int _sleep (const unsigned int milliseconds, unsigned long &timer)
unsigned int wait (const unsigned int milliseconds)
Wait for a certain number of milliseconds since the last call.
void srand ()
template<typename T >
const T rol (const T a, const unsigned int n=1)
Return a left bitwise-rotated number.
template<typename T >
const T ror (const T a, const unsigned int n=1)
Return a right bitwise-rotated number.
template<typename T >
T abs (const T a)
Return the absolute value of a number.
bool abs (const bool a)
unsigned char abs (const unsigned char a)
unsigned short abs (const unsigned short a)
unsigned int abs (const unsigned int a)
unsigned long abs (const unsigned long a)
double abs (const double a)
float abs (const float a)
int abs (const int a)
template<typename T >
T sqr (const T val)
Return the square of a number.
int xln (const int x)
Return 1 + log_10(x).
template<typename t1 , typename t2 >
cimg::superset< t1, t2 >::type min (const t1 &a, const t2 &b)
Return the minimum value between two numbers.
template<typename t1 , typename t2 , typename t3 >
cimg::superset2< t1, t2, t3 >::type min (const t1 &a, const t2 &b, const t3 &c)
Return the minimum value between three numbers.
template<typename t1 , typename t2 , typename t3 , typename t4 >
cimg::superset3< t1, t2, t3,
t4 >::type min (const t1 &a, const t2 &b, const t3 &c, const t4 &d)
Return the minimum value between four numbers.
template<typename t1 , typename t2 >
cimg::superset< t1, t2 >::type max (const t1 &a, const t2 &b)
Return the maximum value between two numbers.
template<typename t1 , typename t2 , typename t3 >
cimg::superset2< t1, t2, t3 >::type max (const t1 &a, const t2 &b, const t3 &c)
Return the maximum value between three numbers.
template<typename t1 , typename t2 , typename t3 , typename t4 >
cimg::superset3< t1, t2, t3,
t4 >::type max (const t1 &a, const t2 &b, const t3 &c, const t4 &d)
Return the maximum value between four numbers.
template<typename T >
T sign (const T x)
Return the sign of a number.
template<typename T >
unsigned int nearest_pow2 (const T x)
Return the nearest power of 2 higher than a given number.
template<typename T >
T mod (const T &x, const T &m)
Return the modulo of a number.
int mod (const bool x, const bool m)
int mod (const char x, const char m)
int mod (const short x, const short m)
int mod (const int x, const int m)
int mod (const long x, const long m)
int mod (const unsigned char x, const unsigned char m)
int mod (const unsigned short x, const unsigned short m)
int mod (const unsigned int x, const unsigned int m)
int mod (const unsigned long x, const unsigned long m)
template<typename T >
T minmod (const T a, const T b)
Return the minmod of two numbers.
double rand ()
Return a random variable between [0,1] with respect to an uniform distribution.
double crand ()
Return a random variable between [-1,1] with respect to an uniform distribution.
double grand ()
Return a random variable following a gaussian distribution and a standard deviation of 1.
unsigned int prand (const double z)
Return a random variable following a Poisson distribution of parameter z.
double round (const double x, const double y, const int rounding_type=0)
Return a rounded number.
double _pythagore (double a, double b)
char uncase (const char x)
Remove the 'case' of an ASCII character.
void uncase (char *const string)
Remove the 'case' of a C string.
float atof (const char *const str)
Read a float number from a C-string.
int strncasecmp (const char *const s1, const char *const s2, const int l)
Compare the first n characters of two C-strings, ignoring the case.
int strcasecmp (const char *const s1, const char *const s2)
Compare two C-strings, ignoring the case.
bool strpare (char *const s, const char delimiter=' ', const bool symmetric=false)
Remove useless delimiters on the borders of a C-string.
void strclean (char *const s)
Remove useless spaces and symmetric delimiters ', " and ` from a C-string.
void strescape (char *const s)
Replace explicit escape sequences '' in C-strings.
const char * basename (const char *const s)
Compute the basename of a filename.
const char * filenamerand ()
void winformat_string (char *const s)
const char * temporary_path (const char *const user_path=0, const bool reinit_path=false)
Return or set path to store temporary files.
const char * imagemagick_path (const char *const user_path=0, const bool reinit_path=false)
Return or set path to the ImageMagick's convert tool.
const char * graphicsmagick_path (const char *const user_path=0, const bool reinit_path=false)
Return path of the GraphicsMagick's gm tool.
const char * medcon_path (const char *const user_path=0, const bool reinit_path=false)
Return or set path of the XMedcon tool.
const char * ffmpeg_path (const char *const user_path=0, const bool reinit_path=false)
Return or set path to the 'ffmpeg' command.
const char * gzip_path (const char *const user_path=0, const bool reinit_path=false)
Return or set path to the 'gzip' command.
const char * gunzip_path (const char *const user_path=0, const bool reinit_path=false)
Return or set path to the 'gunzip' command.
const char * dcraw_path (const char *const user_path=0, const bool reinit_path=false)
Return or set path to the 'dcraw' command.
const char * split_filename (const char *const filename, char *const body=0)
Split a filename into two strings 'body' and 'extension'.
char * number_filename (const char *const filename, const int number, const unsigned int n, char *const string)
Create a numbered version of a filename.
std::FILE * fopen (const char *const path, const char *const mode)
Open a file, and check for possible errors.
int fclose (std::FILE *file)
Close a file, and check for possible errors.
const char * file_type (std::FILE *const file, const char *const filename)
Try to guess the image format of a filename, using its magick numbers.
template<typename T >
int fread (T *const ptr, const unsigned int nmemb, std::FILE *stream)
Read file data, and check for possible errors.
template<typename T >
int fwrite (const T *ptr, const unsigned int nmemb, std::FILE *stream)
Write data to a file, and check for possible errors.
const char * option (const char *const name, const int argc, const char *const *const argv, const char *defaut, const char *const usage=0)
bool option (const char *const name, const int argc, const char *const *const argv, const bool defaut, const char *const usage=0)
int option (const char *const name, const int argc, const char *const *const argv, const int defaut, const char *const usage=0)
char option (const char *const name, const int argc, const char *const *const argv, const char defaut, const char *const usage=0)
float option (const char *const name, const int argc, const char *const *const argv, const float defaut, const char *const usage=0)
double option (const char *const name, const int argc, const char *const *const argv, const double defaut, const char *const usage=0)
const char * argument (const unsigned int nb, const int argc, const char *const *const argv, const unsigned int nb_singles=0,...)
template<typename t >
int dialog (const char *title, const char *msg, const char *button1_txt, const char *button2_txt, const char *button3_txt, const char *button4_txt, const char *button5_txt, const char *button6_txt, const CImg< t > &logo, const bool centering=false)
Display a dialog box, where a user can click standard buttons.
Variables
const char t_normal [] = { 0 }
const char *const t_red = cimg::t_normal
const char *const *const t_bold = cimg::t_normal
const char *const *const *const t_purple = cimg::t_normal
const char *const *const
*const *const t_green = cimg::t_normal
const unsigned int keyESC = 1U
const unsigned int keyF1 = 2U
const unsigned int keyF2 = 3U
const unsigned int keyF3 = 4U
const unsigned int keyF4 = 5U
const unsigned int keyF5 = 6U
const unsigned int keyF6 = 7U
const unsigned int keyF7 = 8U
const unsigned int keyF8 = 9U
const unsigned int keyF9 = 10U
const unsigned int keyF10 = 11U
const unsigned int keyF11 = 12U
const unsigned int keyF12 = 13U
const unsigned int keyPAUSE = 14U
const unsigned int key1 = 15U
const unsigned int key2 = 16U
const unsigned int key3 = 17U
const unsigned int key4 = 18U
const unsigned int key5 = 19U
const unsigned int key6 = 20U
const unsigned int key7 = 21U
const unsigned int key8 = 22U
const unsigned int key9 = 23U
const unsigned int key0 = 24U
const unsigned int keyBACKSPACE = 25U
const unsigned int keyINSERT = 26U
const unsigned int keyHOME = 27U
const unsigned int keyPAGEUP = 28U
const unsigned int keyTAB = 29U
const unsigned int keyQ = 30U
const unsigned int keyW = 31U
const unsigned int keyE = 32U
const unsigned int keyR = 33U
const unsigned int keyT = 34U
const unsigned int keyY = 35U
const unsigned int keyU = 36U
const unsigned int keyI = 37U
const unsigned int keyO = 38U
const unsigned int keyP = 39U
const unsigned int keyDELETE = 40U
const unsigned int keyEND = 41U
const unsigned int keyPAGEDOWN = 42U
const unsigned int keyCAPSLOCK = 43U
const unsigned int keyA = 44U
const unsigned int keyS = 45U
const unsigned int keyD = 46U
const unsigned int keyF = 47U
const unsigned int keyG = 48U
const unsigned int keyH = 49U
const unsigned int keyJ = 50U
const unsigned int keyK = 51U
const unsigned int keyL = 52U
const unsigned int keyENTER = 53U
const unsigned int keySHIFTLEFT = 54U
const unsigned int keyZ = 55U
const unsigned int keyX = 56U
const unsigned int keyC = 57U
const unsigned int keyV = 58U
const unsigned int keyB = 59U
const unsigned int keyN = 60U
const unsigned int keyM = 61U
const unsigned int keySHIFTRIGHT = 62U
const unsigned int keyARROWUP = 63U
const unsigned int keyCTRLLEFT = 64U
const unsigned int keyAPPLEFT = 65U
const unsigned int keyALT = 66U
const unsigned int keySPACE = 67U
const unsigned int keyALTGR = 68U
const unsigned int keyAPPRIGHT = 69U
const unsigned int keyMENU = 70U
const unsigned int keyCTRLRIGHT = 71U
const unsigned int keyARROWLEFT = 72U
const unsigned int keyARROWDOWN = 73U
const unsigned int keyARROWRIGHT = 74U
const unsigned int keyPAD0 = 75U
const unsigned int keyPAD1 = 76U
const unsigned int keyPAD2 = 77U
const unsigned int keyPAD3 = 78U
const unsigned int keyPAD4 = 79U
const unsigned int keyPAD5 = 80U
const unsigned int keyPAD6 = 81U
const unsigned int keyPAD7 = 82U
const unsigned int keyPAD8 = 83U
const unsigned int keyPAD9 = 84U
const unsigned int keyPADADD = 85U
const unsigned int keyPADSUB = 86U
const unsigned int keyPADMUL = 87U
const unsigned int keyPADDIV = 88U
const double valuePI = 3.14159265358979323846
Definition of the mathematical constant PI.
const unsigned int font7x11 [7 *11 *256/32]
const unsigned int font10x13 [256 *10 *13/32]
const unsigned int font8x17 [8 *17 *256/32]
const unsigned int font10x19 [10 *19 *256/32]
const unsigned int font12x24 [12 *24 *256/32]
const unsigned int font16x32 [16 *32 *256/32]
const unsigned int font19x38 [19 *38 *256/32]
const unsigned int font29x57 [29 *57 *256/32]
const unsigned char logo40x38 [4576]
Detailed Description
Namespace that encompasses low-level functions and variables of the CImg Library.
Most of the functions and variables within this namespace are used by the library for low-level processing. Nevertheless, documented variables and functions of this namespace may be used safely in your own source code.
Warning
Never write using namespace cimg_library::cimg; in your source code, since a lot of functions of the cimg:: namespace have prototypes similar to standard C functions that could defined in the global namespace ::.
Function Documentation
double cimg_library::cimg::_pythagore (double a, double b) inline
Definition at line 4881 of file CImg.h.
References abs(), and sqrt().
Referenced by CImg< uintT >::SVD().
{
       const double absa = cimg::abs(a), absb = cimg::abs(b);
       if (absa>absb) { const double tmp = absb/absa; return absa*std::sqrt(1.0+tmp*tmp); }
       else { const double tmp = absa/absb; return (absb==0?0:absb*std::sqrt(1.0+tmp*tmp)); }
     }
unsigned int cimg_library::cimg::_sleep (const unsigned int milliseconds, unsigned long & timer) inline
Definition at line 4635 of file CImg.h.
References sleep(), and time().
Referenced by wait(), and CImgDisplay::wait().
{
       if (!timer) timer = cimg::time();
       const unsigned long current_time = cimg::time();
       if (current_time>=timer+milliseconds) { timer = current_time; return 0; }
       const unsigned long time_diff = timer + milliseconds - current_time;
       timer = current_time + time_diff;
       cimg::sleep(time_diff);
       return (unsigned int)time_diff;
     }
T cimg_library::cimg::abs (const T a) inline
Return the absolute value of a number.
Note
This function is different from std::abs() or std::fabs() because it is able to consider a variable of any type, without cast needed.
Definition at line 4687 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d(), CImg< uintT >::_draw_ellipse(), CImg< uintT >::_draw_object3d(), CImg< uintT >::_draw_scanline(), CImg< uintT >::_get_select(), CImg< uintT >::_load_bmp(), CImg< uintT >::_LU(), _pythagore(), CImg< uintT >::abs(), CImg< uintT >::distance_hamilton(), CImg< uintT >::draw_axis(), CImg< uintT >::draw_fill(), CImg< uintT >::draw_gaussian(), CImg< uintT >::draw_image(), CImg< uintT >::draw_line(), CImg< uintT >::draw_mandelbrot(), CImg< uintT >::draw_plasma(), CImg< uintT >::draw_point(), CImg< uintT >::draw_quiver(), CImg< uintT >::draw_rectangle(), CImg< uintT >::draw_spline(), CImg< uintT >::draw_triangle(), CImg< T >::_cimg_math_parser::eval(), CImg< uintT >::get_blur_patch(), CImg< uintT >::get_displacement_field(), CImg< uintT >::get_norm(), CImg< uintT >::get_rotate(), CImg< uintT >::get_select_graph(), CImg< uintT >::magnitude(), CImg< uintT >::sharpen(), CImg< uintT >::SVD(), CImg< uintT >::symmetric_eigen(), CImg< uintT >::translate(), and CImg< uintT >::variancemean().
{
       return a>=0?a:-a;
     }
bool cimg_library::cimg::abs (const bool a) inline
Definition at line 4690 of file CImg.h.
{
       return a;
     }
unsigned char cimg_library::cimg::abs (const unsigned char a) inline
Definition at line 4693 of file CImg.h.
{
       return a;
     }
unsigned short cimg_library::cimg::abs (const unsigned short a) inline
Definition at line 4696 of file CImg.h.
{
       return a;
     }
unsigned int cimg_library::cimg::abs (const unsigned int a) inline
Definition at line 4699 of file CImg.h.
{
       return a;
     }
unsigned long cimg_library::cimg::abs (const unsigned long a) inline
Definition at line 4702 of file CImg.h.
{
       return a;
     }
double cimg_library::cimg::abs (const double a) inline
Definition at line 4705 of file CImg.h.
{
       return std::fabs(a);
     }
float cimg_library::cimg::abs (const float a) inline
Definition at line 4708 of file CImg.h.
{
       return (float)std::fabs((double)a);
     }
int cimg_library::cimg::abs (const int a) inline
Definition at line 4711 of file CImg.h.
References cimg_library::abs().
{
       return std::abs(a);
     }
const char* cimg_library::cimg::argument (const unsigned int nb, const int argc, const char *const *const argv, const unsigned int nb_singles = 0, ...) inline
Definition at line 5682 of file CImg.h.
References i, k, option(), and strcasecmp().
{
       for (int k = 1, pos = 0; k<argc;) {
         const char *const item = argv[k];
         bool option = (*item=='-'), single_option = false;
         if (option) {
           va_list ap;
           va_start(ap,nb_singles);
           for (unsigned int i = 0; i<nb_singles; ++i) if (!cimg::strcasecmp(item,va_arg(ap,char*))) { single_option = true; break; }
           va_end(ap);
         }
         if (option) { ++k; if (!single_option) ++k; }
         else { if (pos++==(int)nb) return item; else ++k; }
       }
       return 0;
     }
float cimg_library::cimg::atof (const char *const str) inline
Read a float number from a C-string.
Note
This function is quite similar to std::atof(), but that it allows the retrieval of fractions as in "1/2".
Definition at line 4905 of file CImg.h.
References x, and y.
Referenced by main(), option(), ComSwitch::parseValuesFromArguments(), Rocin::read_parameter_file(), remesh(), and Rocprop::set_option().
{
       float x = 0,y = 1;
       if (!str) return 0; else { std::sscanf(str,"%g/%g",&x,&y); return x/y; }
     }
const char* cimg_library::cimg::basename (const char *const s) inline
Compute the basename of a filename.
Definition at line 4989 of file CImg.h.
References cimg_file_separator.
Referenced by CImg< uintT >::_save_cpp(), and option().
{
       const char *p = 0;
       for (const char *np = s; np>=s && (p=np); np = std::strchr(np,cimg_file_separator)+1) {}
       return p;
     }
double cimg_library::cimg::crand () inline
Return a random variable between [-1,1] with respect to an uniform distribution.
Definition at line 4840 of file CImg.h.
References rand().
Referenced by CImg< uintT >::noise().
{
       return 1-2*cimg::rand();
     }
const char* cimg_library::cimg::dcraw_path (const char *const user_path = 0, const bool reinit_path = false) inline
Return or set path to the 'dcraw' command.
Definition at line 5439 of file CImg.h.
References fclose(), fopen(), and winformat_string().
Referenced by CImg< uintT >::load_dcraw_external().
{
       static char *st_path = 0;
       if (reinit_path && st_path) { delete[] st_path; st_path = 0; }
       if (user_path) {
         if (!st_path) st_path = new char[1024];
         std::memset(st_path,0,1024);
         std::strncpy(st_path,user_path,1023);
       } else if (!st_path) {
         st_path = new char[1024];
         std::memset(st_path,0,1024);
         bool path_found = false;
         std::FILE *file = 0;
 #if cimg_OS==2
         if (!path_found) {
           std::sprintf(st_path,".\\dcraw.exe");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"dcraw.exe");
 #else
         if (!path_found) {
           std::sprintf(st_path,"./dcraw");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"dcraw");
 #endif
         winformat_string(st_path);
       }
       return st_path;
     }
int dialog (const char * title, const char * msg, const char * button1_txt = "OK", const char * button2_txt = 0, const char * button3_txt = 0, const char * button4_txt = 0, const char * button5_txt = 0, const char * button6_txt = 0, const bool centering = false) inline
Definition at line 37329 of file CImg.h.
References dialog().
{
     return dialog(title,msg,button1_txt,button2_txt,button3_txt,button4_txt,button5_txt,button6_txt,
                   CImg<unsigned char>::logo40x38(),centering);
   }
int cimg_library::cimg::dialog (const char * title, const char * msg, const char * button1_txt, const char * button2_txt, const char * button3_txt, const char * button4_txt, const char * button5_txt, const char * button6_txt, const CImg< t > & logo, const bool centering = false) inline
Display a dialog box, where a user can click standard buttons.
Up to 6 buttons can be defined in the dialog window. This function returns when a user clicked one of the button or closed the dialog window.
Parameters
title = Title of the dialog window.
msg = Main message displayed inside the dialog window.
button1_txt = Label of the 1st button.
button2_txt = Label of the 2nd button.
button3_txt = Label of the 3rd button.
button4_txt = Label of the 4th button.
button5_txt = Label of the 5th button.
button6_txt = Label of the 6th button.
logo = Logo image displayed at the left of the main message. This parameter is optional.
centering = Tell to center the dialog window on the screen.
Returns
The button number (from 0 to 5), or -1 if the dialog window has been closed by the user.
Note
If a button text is set to 0, then the corresponding button (and the followings) won't appear in the dialog box. At least one button is necessary.
Definition at line 37190 of file CImg.h.
References CImgDisplay::button, by, cimg_stdout, cimglist_for, CImgDisplay::dimx(), CImgList< T >::dimx(), CImgDisplay::dimy(), CImg< T >::display(), CImg< T >::draw_line(), CImgDisplay::is_closed, CImgDisplay::is_resized, CImgDisplay::key, keyARROWDOWN, keyARROWLEFT, keyARROWRIGHT, keyARROWUP, keyENTER, keyESC, keyTAB, max(), CImgDisplay::mouse_x, CImgDisplay::mouse_y, CImgDisplay::move(), CImgDisplay::resize(), CImgDisplay::screen_dimx(), CImgDisplay::screen_dimy(), CImg< T >::transfer_to(), CImgList< T >::transfer_to(), and CImgDisplay::wait().
Referenced by dialog().
{
 #if cimg_display!=0
     const unsigned char
       black[] = { 0,0,0 }, white[] = { 255,255,255 }, gray[] = { 200,200,200 }, gray2[] = { 150,150,150 };
     // Create buttons and canvas graphics
     CImgList<unsigned char> buttons, cbuttons, sbuttons;
     if (button1_txt) { CImg<unsigned char>().draw_text(0,0,button1_txt,black,gray,1,13).transfer_to(buttons);
       if (button2_txt) { CImg<unsigned char>().draw_text(0,0,button2_txt,black,gray,1,13).transfer_to(buttons);
         if (button3_txt) { CImg<unsigned char>().draw_text(0,0,button3_txt,black,gray,1,13).transfer_to(buttons);
           if (button4_txt) { CImg<unsigned char>().draw_text(0,0,button4_txt,black,gray,1,13).transfer_to(buttons);
             if (button5_txt) { CImg<unsigned char>().draw_text(0,0,button5_txt,black,gray,1,13).transfer_to(buttons);
               if (button6_txt) { CImg<unsigned char>().draw_text(0,0,button6_txt,black,gray,1,13).transfer_to(buttons);
               }}}}}}
     if (!buttons.width)
       throw CImgArgumentException("cimg::dialog() : No buttons have been defined. At least one is necessary");
     unsigned int bw = 0, bh = 0;
     cimglist_for(buttons,l) { bw = cimg::max(bw,buttons[l].width); bh = cimg::max(bh,buttons[l].height); }
     bw+=8; bh+=8;
     if (bw<64) bw=64;
     if (bw>128) bw=128;
     if (bh<24) bh=24;
     if (bh>48) bh=48;
     CImg<unsigned char> button(bw,bh,1,3);
     button.draw_rectangle(0,0,bw-1,bh-1,gray);
     button.draw_line(0,0,bw-1,0,white).draw_line(0,bh-1,0,0,white);
     button.draw_line(bw-1,0,bw-1,bh-1,black).draw_line(bw-1,bh-1,0,bh-1,black);
     button.draw_line(1,bh-2,bw-2,bh-2,gray2).draw_line(bw-2,bh-2,bw-2,1,gray2);
     CImg<unsigned char> sbutton(bw,bh,1,3);
     sbutton.draw_rectangle(0,0,bw-1,bh-1,gray);
     sbutton.draw_line(0,0,bw-1,0,black).draw_line(bw-1,0,bw-1,bh-1,black);
     sbutton.draw_line(bw-1,bh-1,0,bh-1,black).draw_line(0,bh-1,0,0,black);
     sbutton.draw_line(1,1,bw-2,1,white).draw_line(1,bh-2,1,1,white);
     sbutton.draw_line(bw-2,1,bw-2,bh-2,black).draw_line(bw-2,bh-2,1,bh-2,black);
     sbutton.draw_line(2,bh-3,bw-3,bh-3,gray2).draw_line(bw-3,bh-3,bw-3,2,gray2);
     sbutton.draw_line(4,4,bw-5,4,black,1,0xAAAAAAAA,true).draw_line(bw-5,4,bw-5,bh-5,black,1,0xAAAAAAAA,false);
     sbutton.draw_line(bw-5,bh-5,4,bh-5,black,1,0xAAAAAAAA,false).draw_line(4,bh-5,4,4,black,1,0xAAAAAAAA,false);
     CImg<unsigned char> cbutton(bw,bh,1,3);
     cbutton.draw_rectangle(0,0,bw-1,bh-1,black).draw_rectangle(1,1,bw-2,bh-2,gray2).draw_rectangle(2,2,bw-3,bh-3,gray);
     cbutton.draw_line(4,4,bw-5,4,black,1,0xAAAAAAAA,true).draw_line(bw-5,4,bw-5,bh-5,black,1,0xAAAAAAAA,false);
     cbutton.draw_line(bw-5,bh-5,4,bh-5,black,1,0xAAAAAAAA,false).draw_line(4,bh-5,4,4,black,1,0xAAAAAAAA,false);
     cimglist_for(buttons,ll) {
       CImg<unsigned char>(cbutton).draw_image(1+(bw-buttons[ll].dimx())/2,1+(bh-buttons[ll].dimy())/2,buttons[ll]).
         transfer_to(cbuttons);
       CImg<unsigned char>(sbutton).draw_image((bw-buttons[ll].dimx())/2,(bh-buttons[ll].dimy())/2,buttons[ll]).
         transfer_to(sbuttons);
       CImg<unsigned char>(button).draw_image((bw-buttons[ll].dimx())/2,(bh-buttons[ll].dimy())/2,buttons[ll]).
         transfer_to(buttons[ll]);
     }
     CImg<unsigned char> canvas;
     if (msg) CImg<unsigned char>().draw_text(0,0,"%s",black,gray,1,13,msg).transfer_to(canvas);
     const unsigned int
       bwall = (buttons.width-1)*(12+bw) + bw,
       w = cimg::max(196U,36+logo.width+canvas.width, 24+bwall),
       h = cimg::max(96U,36+canvas.height+bh,36+logo.height+bh),
       lx = 12 + (canvas.data?0:((w-24-logo.width)/2)),
       ly = (h-12-bh-logo.height)/2,
       tx = lx+logo.width+12,
       ty = (h-12-bh-canvas.height)/2,
       bx = (w-bwall)/2,
       by = h-12-bh;
     if (canvas.data)
       canvas = CImg<unsigned char>(w,h,1,3).
         draw_rectangle(0,0,w-1,h-1,gray).
         draw_line(0,0,w-1,0,white).draw_line(0,h-1,0,0,white).
         draw_line(w-1,0,w-1,h-1,black).draw_line(w-1,h-1,0,h-1,black).
         draw_image(tx,ty,canvas);
     else
       canvas = CImg<unsigned char>(w,h,1,3).
         draw_rectangle(0,0,w-1,h-1,gray).
         draw_line(0,0,w-1,0,white).draw_line(0,h-1,0,0,white).
         draw_line(w-1,0,w-1,h-1,black).draw_line(w-1,h-1,0,h-1,black);
     if (logo.data) canvas.draw_image(lx,ly,logo);
     unsigned int xbuttons[6] = { 0 };
     cimglist_for(buttons,lll) { xbuttons[lll] = bx+(bw+12)*lll; canvas.draw_image(xbuttons[lll],by,buttons[lll]); }
     // Open window and enter events loop
     CImgDisplay disp(canvas,title?title:" ",0,false,centering?true:false);
     if (centering) disp.move((CImgDisplay::screen_dimx()-disp.dimx())/2,
                              (CImgDisplay::screen_dimy()-disp.dimy())/2);
     bool stopflag = false, refresh = false;
     int oselected = -1, oclicked = -1, selected = -1, clicked = -1;
     while (!disp.is_closed && !stopflag) {
       if (refresh) {
         if (clicked>=0) CImg<unsigned char>(canvas).draw_image(xbuttons[clicked],by,cbuttons[clicked]).display(disp);
         else {
           if (selected>=0) CImg<unsigned char>(canvas).draw_image(xbuttons[selected],by,sbuttons[selected]).display(disp);
           else canvas.display(disp);
         }
         refresh = false;
       }
       disp.wait(15);
       if (disp.is_resized) disp.resize(disp);
       if (disp.button&1)  {
         oclicked = clicked;
         clicked = -1;
         cimglist_for(buttons,l)
           if (disp.mouse_y>=(int)by && disp.mouse_y<(int)(by+bh) &&
               disp.mouse_x>=(int)xbuttons[l] && disp.mouse_x<(int)(xbuttons[l]+bw)) {
             clicked = selected = l;
             refresh = true;
           }
         if (clicked!=oclicked) refresh = true;
       } else if (clicked>=0) stopflag = true;
       if (disp.key) {
         oselected = selected;
         switch (disp.key) {
         case cimg::keyESC : selected=-1; stopflag=true; break;
         case cimg::keyENTER : if (selected<0) selected = 0; stopflag = true; break;
         case cimg::keyTAB :
         case cimg::keyARROWRIGHT :
         case cimg::keyARROWDOWN : selected = (selected+1)%buttons.width; break;
         case cimg::keyARROWLEFT :
         case cimg::keyARROWUP : selected = (selected+buttons.width-1)%buttons.width; break;
         }
         disp.key = 0;
         if (selected!=oselected) refresh = true;
       }
     }
     if (!disp) selected = -1;
     return selected;
 #else
     std::fprintf(cimg_stdout,"<%s>\n\n%s\n\n",title,msg);
     return -1+0*(int)(button1_txt-button2_txt+button3_txt-button4_txt+button5_txt-button6_txt+logo.width+(int)centering);
 #endif
   }
bool cimg_library::cimg::endianness () inline
Return the current endianness of the CPU.
Returns
false for "Little Endian", true for "Big Endian".
Definition at line 4572 of file CImg.h.
References x.
Referenced by CImgList< uintT >::_load_cimg(), CImg< uintT >::_load_inr(), CImg< uintT >::_load_png(), CImg< uintT >::_load_pnm(), CImgList< uintT >::_save_cimg(), CImg< uintT >::_save_inr(), CImg< uintT >::_save_png(), CImg< uintT >::_save_pnm(), info(), and CImgList< uintT >::load_parrec().
{
       const int x = 1;
       return ((unsigned char*)&x)[0]?false:true;
     }
double eval (const char *const expression, const double x = 0, const double y = 0, const double z = 0, const double v = 0) inline
Evaluate math expression.
Definition at line 37338 of file CImg.h.
References CImgList< T >::empty().
Referenced by main().
{
     static const CImg<float> empty;
     return empty.eval(expression,x,y,z,v);
   }
unsigned int& cimg_library::cimg::exception_mode () inline
Get/set the current CImg exception mode.
The way error messages are handled by CImg can be changed dynamically, using this function. Possible values are :
0 to hide debug messages (quiet mode, but exceptions are still thrown).
1 to display debug messages on standard error (console).
2 to display debug messages in modal windows (default behavior).
3 to do as 1 + add extra warnings (may slow down the code !).
4 to do as 2 + add extra warnings (may slow down the code !).
Definition at line 1940 of file CImg.h.
References cimg_debug.
Referenced by CImg< uintT >::fill(), CImg< uintT >::load(), CImgList< uintT >::load(), CImgList< uintT >::load_ffmpeg_external(), CImg< uintT >::load_other(), CImg< uintT >::max(), CImg< uintT >::min(), CImg< uintT >::operator%=(), CImg< uintT >::operator&=(), CImg< uintT >::operator*=(), CImg< uintT >::operator+=(), CImg< uintT >::operator-=(), CImg< uintT >::operator/=(), CImg< uintT >::operator=(), CImg< uintT >::operator^=(), CImg< uintT >::operator|=(), CImg< uintT >::pow(), CImg< uintT >::save_other(), and warn().
 { static unsigned int mode = cimg_debug; return mode; }
int cimg_library::cimg::fclose (std::FILE * file) inline
Close a file, and check for possible errors.
Definition at line 5507 of file CImg.h.
References warn().
Referenced by CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), CImg< uintT >::_load_analyze(), CImg< uintT >::_load_ascii(), CImg< uintT >::_load_bmp(), CImgList< uintT >::_load_cimg(), CImg< uintT >::_load_dlm(), CImg< uintT >::_load_inr(), CImg< uintT >::_load_jpeg(), CImg< uintT >::_load_off(), CImg< uintT >::_load_pandore(), CImg< uintT >::_load_png(), CImg< uintT >::_load_pnm(), CImg< uintT >::_load_raw(), CImg< uintT >::_load_rgb(), CImg< uintT >::_load_rgba(), CImgList< uintT >::_load_yuv(), CImg< uintT >::_save_ascii(), CImg< uintT >::_save_bmp(), CImgList< uintT >::_save_cimg(), CImg< uintT >::_save_cpp(), CImg< uintT >::_save_dlm(), CImgList< uintT >::_save_empty_cimg(), CImg< uintT >::_save_inr(), CImg< uintT >::_save_jpeg(), CImg< uintT >::_save_off(), CImg< uintT >::_save_pandore(), CImg< uintT >::_save_png(), CImg< uintT >::_save_pnm(), CImg< uintT >::_save_raw(), CImg< uintT >::_save_rgb(), CImg< uintT >::_save_rgba(), CImgList< uintT >::_save_yuv(), dcraw_path(), ffmpeg_path(), file_type(), fileExists(), Rocout::get_fname(), get_restart_time(), CImg< uintT >::get_select_graph(), graphicsmagick_path(), gunzip_path(), gzip_path(), imagemagick_path(), init_profiling(), CImg< uintT >::load_dcraw_external(), CImgList< uintT >::load_ffmpeg_external(), CImg< uintT >::load_graphicsmagick_external(), CImg< uintT >::load_gzip_external(), CImgList< uintT >::load_gzip_external(), CImg< uintT >::load_imagemagick_external(), CImg< uintT >::load_medcon_external(), CImgList< uintT >::load_parrec(), medcon_path(), Scheduler::print(), Coupling::print(), Roccom_base::print_profile(), read_general(), read_reg(), Coupling::read_restart_info(), MeshImpl::read_vtk(), CImg< uintT >::save_analyze(), CImgList< uintT >::save_ffmpeg_external(), CImg< uintT >::save_graphicsmagick_external(), CImg< uintT >::save_gzip_external(), CImgList< uintT >::save_gzip_external(), CImg< uintT >::save_imagemagick_external(), CImg< uintT >::save_medcon_external(), temporary_path(), FullyCoupling::update_distances(), FullyCoupling::update_integrals(), write_bounds(), Coupling::write_restart_info(), writeFlo(), writeMblock(), writeTop(), bcReader::~bcReader(), and FileTokenizer::~FileTokenizer().
{
       if (!file) warn("cimg::fclose() : Cannot close (null) file");
       if (!file || file==stdin || file==stdout) return 0;
       const int errn = std::fclose(file);
       if (errn!=0) warn("cimg::fclose() : Error %d during file closing",errn);
       return errn;
     }
const char* cimg_library::cimg::ffmpeg_path (const char *const user_path = 0, const bool reinit_path = false) inline
Return or set path to the 'ffmpeg' command.
Definition at line 5346 of file CImg.h.
References fclose(), fopen(), and winformat_string().
Referenced by CImgList< uintT >::load_ffmpeg_external().
{
       static char *st_path = 0;
       if (reinit_path && st_path) { delete[] st_path; st_path = 0; }
       if (user_path) {
         if (!st_path) st_path = new char[1024];
         std::memset(st_path,0,1024);
         std::strncpy(st_path,user_path,1023);
       } else if (!st_path) {
         st_path = new char[1024];
         std::memset(st_path,0,1024);
         bool path_found = false;
         std::FILE *file = 0;
 #if cimg_OS==2
         if (!path_found) {
           std::sprintf(st_path,".\\ffmpeg.exe");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"ffmpeg.exe");
 #else
         if (!path_found) {
           std::sprintf(st_path,"./ffmpeg");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"ffmpeg");
 #endif
         winformat_string(st_path);
       }
       return st_path;
     }
const char* cimg_library::cimg::file_type (std::FILE *const file, const char *const filename) inline
Try to guess the image format of a filename, using its magick numbers.
Definition at line 5516 of file CImg.h.
References fclose(), fopen(), and fread().
Referenced by CImg< uintT >::load().
{
       static const char
         *const _pnm = "pnm",
         *const _bmp = "bmp",
         *const _gif = "gif",
         *const _jpeg = "jpeg",
         *const _off = "off",
         *const _pan = "pan",
         *const _png = "png",
         *const _tiff = "tiff";
       if (!filename && !file) throw CImgArgumentException("cimg::file_type() : Cannot load (null) filename.");
       std::FILE *const nfile = file?file:cimg::fopen(filename,"rb");
       const char *ftype = 0, *head;
       char header[2048] = { 0 }, item[1024] = { 0 };
       const unsigned char *const uheader = (unsigned char*)header;
       int err;
       const unsigned int siz = (unsigned int)std::fread(header,2048,1,nfile);   // Read first 2048 bytes.
       if (!file) cimg::fclose(nfile);
       if (!ftype) { // Check for BMP format.
         if (header[0]=='B' && header[1]=='M') ftype = _bmp;
       }
       if (!ftype) { // Check for GIF format.
         if (header[0]=='G' && header[1]=='I' && header[2]=='F' && header[3]=='8' && header[5]=='a' &&
             (header[4]=='7' || header[4]=='9')) ftype = _gif;
       }
       if (!ftype) { // Check for JPEG format.
         if (uheader[0]==0xFF && uheader[1]==0xD8 && uheader[2]==0xFF) ftype = _jpeg;
       }
       if (!ftype) { // Check for OFF format.
         if (header[0]=='O' && header[1]=='F' && header[2]=='F' && header[3]=='\n') ftype = _off;
       }
       if (!ftype) { // Check for PAN format.
         if (header[0]=='P' && header[1]=='A' && header[2]=='N' && header[3]=='D' && header[4]=='O' &&
             header[5]=='R' && header[6]=='E') ftype = _pan;
       }
       if (!ftype) { // Check for PNG format.
         if (uheader[0]==0x89 && uheader[1]==0x50 && uheader[2]==0x4E && uheader[3]==0x47 &&
             uheader[4]==0x0D && uheader[5]==0x0A && uheader[6]==0x1A && uheader[7]==0x0A) ftype = _png;
       }
       if (!ftype) { // Check for PNM format.
         head = header;
         while (head<header+siz && (err=std::sscanf(head,"%1023[^\n]",item))!=EOF && (item[0]=='#' || !err))
           head+=1+(err?std::strlen(item):0);
         if (std::sscanf(item," P%d",&err)==1) ftype = _pnm;
       }
       if (!ftype) { // Check for TIFF format.
         if ((uheader[0]==0x49 && uheader[1]==0x49) || (uheader[0]==0x4D && uheader[1]==0x4D)) ftype = _tiff;
       }
       return ftype;
     }
const char* cimg_library::cimg::filenamerand () inline
Definition at line 4996 of file CImg.h.
References k, rand(), srand(), and v.
Referenced by CImg< uintT >::load_dcraw_external(), CImgList< uintT >::load_ffmpeg_external(), CImg< uintT >::load_graphicsmagick_external(), CImg< uintT >::load_gzip_external(), CImgList< uintT >::load_gzip_external(), CImg< uintT >::load_imagemagick_external(), CImg< uintT >::load_medcon_external(), CImgList< uintT >::save_ffmpeg_external(), CImg< uintT >::save_graphicsmagick_external(), CImg< uintT >::save_gzip_external(), CImgList< uintT >::save_gzip_external(), CImg< uintT >::save_imagemagick_external(), CImg< uintT >::save_medcon_external(), and temporary_path().
{
       static char randomid[9] = { 0,0,0,0,0,0,0,0,0 };
       cimg::srand();
       for (unsigned int k = 0; k<8; ++k) {
         const int v = (int)std::rand()%3;
         randomid[k] = (char)(v==0?('0'+(std::rand()%10)):(v==1?('a'+(std::rand()%26)):('A'+(std::rand()%26))));
       }
       return randomid;
     }
std::FILE* cimg_library::cimg::fopen (const char *const path, const char *const mode) inline
Open a file, and check for possible errors.
Definition at line 5494 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), CImg< uintT >::_load_analyze(), CImg< uintT >::_load_ascii(), CImg< uintT >::_load_bmp(), CImgList< uintT >::_load_cimg(), CImg< uintT >::_load_dlm(), CImg< uintT >::_load_inr(), CImg< uintT >::_load_jpeg(), CImg< uintT >::_load_off(), CImg< uintT >::_load_pandore(), CImg< uintT >::_load_png(), CImg< uintT >::_load_pnm(), CImg< uintT >::_load_raw(), CImg< uintT >::_load_rgb(), CImg< uintT >::_load_rgba(), CImgList< uintT >::_load_yuv(), CImg< uintT >::_save_ascii(), CImg< uintT >::_save_bmp(), CImgList< uintT >::_save_cimg(), CImg< uintT >::_save_cpp(), CImg< uintT >::_save_dlm(), CImgList< uintT >::_save_empty_cimg(), CImg< uintT >::_save_inr(), CImg< uintT >::_save_jpeg(), CImg< uintT >::_save_off(), CImg< uintT >::_save_pandore(), CImg< uintT >::_save_png(), CImg< uintT >::_save_pnm(), CImg< uintT >::_save_raw(), CImg< uintT >::_save_rgb(), CImg< uintT >::_save_rgba(), CImgList< uintT >::_save_yuv(), Coupling::baseInit(), dcraw_path(), ffmpeg_path(), file_type(), fileExists(), Rocout::get_fname(), get_restart_time(), CImg< uintT >::get_select_graph(), graphicsmagick_path(), gunzip_path(), gzip_path(), imagemagick_path(), init_profiling(), CImg< uintT >::load_dcraw_external(), CImgList< uintT >::load_ffmpeg_external(), CImg< uintT >::load_graphicsmagick_external(), CImg< uintT >::load_gzip_external(), CImgList< uintT >::load_gzip_external(), CImg< uintT >::load_imagemagick_external(), CImg< uintT >::load_medcon_external(), CImgList< uintT >::load_parrec(), medcon_path(), Scheduler::print(), Coupling::print(), Roccom_base::print_profile(), Agent::read_by_control_file(), read_general(), read_reg(), Coupling::read_restart_info(), MeshImpl::read_vtk(), readBoundaries(), CImg< uintT >::save_analyze(), CImgList< uintT >::save_ffmpeg_external(), CImg< uintT >::save_graphicsmagick_external(), CImg< uintT >::save_gzip_external(), CImgList< uintT >::save_gzip_external(), CImg< uintT >::save_imagemagick_external(), CImg< uintT >::save_medcon_external(), temporary_path(), FullyCoupling::update_distances(), FullyCoupling::update_integrals(), write_bounds(), Coupling::write_restart_info(), writeFlo(), writeMblock(), and writeTop().
{
       if(!path || !mode)
         throw CImgArgumentException("cimg::fopen() : File '%s', cannot open with mode '%s'.",
                                     path?path:"(null)",mode?mode:"(null)");
       if (path[0]=='-') return (mode[0]=='r')?stdin:stdout;
       std::FILE *dest = std::fopen(path,mode);
       if (!dest)
         throw CImgIOException("cimg::fopen() : File '%s', cannot open file %s",
                               path,mode[0]=='r'?"for reading.":(mode[0]=='w'?"for writing.":"."),path);
       return dest;
     }
int cimg_library::cimg::fread (T *const ptr, const unsigned int nmemb, std::FILE * stream) inline
Read file data, and check for possible errors.
Definition at line 5569 of file CImg.h.
References warn().
Referenced by CImg< uintT >::_load_analyze(), CImg< uintT >::_load_bmp(), CImg< uintT >::_load_pandore(), CImg< uintT >::_load_png(), CImg< uintT >::_load_pnm(), CImg< uintT >::_load_raw(), CImg< uintT >::_load_rgb(), CImg< uintT >::_load_rgba(), CImgList< uintT >::_load_yuv(), file_type(), FileTokenizer::get_newline(), FileTokenizer::get_string(), CImgList< uintT >::load_parrec(), readDouble(), gridgenBinaryFormatter< float >::readDouble(), readInt(), and gridgenBinaryFormatter< float >::readInt().
{
       if (!ptr || nmemb<=0 || !stream)
         throw CImgArgumentException("cimg::fread() : Cannot read %u x %u bytes of file pointer '%p' in buffer '%p'",
                                     nmemb,sizeof(T),stream,ptr);
       const unsigned long wlimitT = 63*1024*1024, wlimit = wlimitT/sizeof(T);
       unsigned int toread = nmemb, alread = 0, ltoread = 0, lalread = 0;
       do {
         ltoread = (toread*sizeof(T))<wlimitT?toread:wlimit;
         lalread = (unsigned int)std::fread((void*)(ptr+alread),sizeof(T),ltoread,stream);
         alread+=lalread;
         toread-=lalread;
       } while (ltoread==lalread && toread>0);
       if (toread>0) warn("cimg::fread() : File reading problems, only %u/%u elements read",alread,nmemb);
       return alread;
     }
int cimg_library::cimg::fwrite (const T * ptr, const unsigned int nmemb, std::FILE * stream) inline
Write data to a file, and check for possible errors.
Definition at line 5587 of file CImg.h.
References warn().
Referenced by CImg< uintT >::_save_bmp(), CImgList< uintT >::_save_cimg(), CImg< uintT >::_save_inr(), CImg< uintT >::_save_pnm(), CImg< uintT >::_save_raw(), CImg< uintT >::_save_rgb(), CImg< uintT >::_save_rgba(), CImgList< uintT >::_save_yuv(), CImg< uintT >::save_analyze(), and writeMblock().
{
       if (!ptr || !stream)
         throw CImgArgumentException("cimg::fwrite() : Cannot write %u x %u bytes of file pointer '%p' from buffer '%p'",
                                     nmemb,sizeof(T),stream,ptr);
       if (nmemb<=0) return 0;
       const unsigned long wlimitT = 63*1024*1024, wlimit = wlimitT/sizeof(T);
       unsigned int towrite = nmemb, alwrite = 0, ltowrite = 0, lalwrite = 0;
       do {
         ltowrite = (towrite*sizeof(T))<wlimitT?towrite:wlimit;
         lalwrite = (unsigned int)std::fwrite((void*)(ptr+alwrite),sizeof(T),ltowrite,stream);
         alwrite+=lalwrite;
         towrite-=lalwrite;
       } while (ltowrite==lalwrite && towrite>0);
       if (towrite>0) warn("cimg::fwrite() : File writing problems, only %u/%u elements written",alwrite,nmemb);
       return alwrite;
     }
double cimg_library::cimg::grand () inline
Return a random variable following a gaussian distribution and a standard deviation of 1.
Definition at line 4845 of file CImg.h.
References cimg_library::log(), rand(), and sqrt().
Referenced by CImg< uintT >::draw_plasma(), CImg< T >::_cimg_math_parser::eval(), CImg< uintT >::noise(), and prand().
{
       double x1, w;
       do {
         const double x2 = 2*cimg::rand() - 1.0;
         x1 = 2*cimg::rand()-1.0;
         w = x1*x1 + x2*x2;
       } while (w<=0 || w>=1.0);
       return x1*std::sqrt((-2*std::log(w))/w);
     }
const char* cimg_library::cimg::graphicsmagick_path (const char *const user_path = 0, const bool reinit_path = false) inline
Return path of the GraphicsMagick's gm tool.
Definition at line 5198 of file CImg.h.
References fclose(), fopen(), k, and winformat_string().
Referenced by info(), CImg< uintT >::load_graphicsmagick_external(), and CImg< uintT >::save_graphicsmagick_external().
{
       static char *st_path = 0;
       if (reinit_path && st_path) { delete[] st_path; st_path = 0; }
       if (user_path) {
         if (!st_path) st_path = new char[1024];
         std::memset(st_path,0,1024);
         std::strncpy(st_path,user_path,1023);
       } else if (!st_path) {
         st_path = new char[1024];
         std::memset(st_path,0,1024);
         bool path_found = false;
         std::FILE *file = 0;
 #if cimg_OS==2
         const char* pf_path = programfiles_path();
         if (!path_found) {
           std::sprintf(st_path,".\\gm.exe");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"%s\\GRAPHI~1.%.2d-\\gm.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"%s\\GRAPHI~1.%d-Q\\gm.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"%s\\GRAPHI~1.%d\\gm.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"%s\\GRAPHI~1.%.2d-\\VISUA~1\\BIN\\gm.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"%s\\GRAPHI~1.%d-Q\\VISUA~1\\BIN\\gm.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"%s\\GRAPHI~1.%d\\VISUA~1\\BIN\\gm.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"C:\\GRAPHI~1.%.2d-\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"C:\\GRAPHI~1.%d-Q\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"C:\\GRAPHI~1.%d\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"C:\\GRAPHI~1.%.2d-\\VISUA~1\\BIN\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"C:\\GRAPHI~1.%d-Q\\VISUA~1\\BIN\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"C:\\GRAPHI~1.%d\\VISUA~1\\BIN\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"D:\\GRAPHI~1.%.2d-\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"D:\\GRAPHI~1.%d-Q\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"D:\\GRAPHI~1.%d\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"D:\\GRAPHI~1.%.2d-\\VISUA~1\\BIN\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"D:\\GRAPHI~1.%d-Q\\VISUA~1\\BIN\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"D:\\GRAPHI~1.%d\\VISUA~1\\BIN\\gm.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"gm.exe");
 #else
         if (!path_found) {
           std::sprintf(st_path,"./gm");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"gm");
 #endif
         winformat_string(st_path);
       }
       return st_path;
     }
const char* cimg_library::cimg::gunzip_path (const char *const user_path = 0, const bool reinit_path = false) inline
Return or set path to the 'gunzip' command.
Definition at line 5408 of file CImg.h.
References fclose(), fopen(), and winformat_string().
Referenced by CImg< uintT >::load_gzip_external(), and CImgList< uintT >::load_gzip_external().
{
       static char *st_path = 0;
       if (reinit_path && st_path) { delete[] st_path; st_path = 0; }
       if (user_path) {
         if (!st_path) st_path = new char[1024];
         std::memset(st_path,0,1024);
         std::strncpy(st_path,user_path,1023);
       } else if (!st_path) {
         st_path = new char[1024];
         std::memset(st_path,0,1024);
         bool path_found = false;
         std::FILE *file = 0;
 #if cimg_OS==2
         if (!path_found) {
           std::sprintf(st_path,".\\gunzip.exe");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"gunzip.exe");
 #else
         if (!path_found) {
           std::sprintf(st_path,"./gunzip");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"gunzip");
 #endif
         winformat_string(st_path);
       }
       return st_path;
     }
const char* cimg_library::cimg::gzip_path (const char *const user_path = 0, const bool reinit_path = false) inline
Return or set path to the 'gzip' command.
Definition at line 5377 of file CImg.h.
References fclose(), fopen(), and winformat_string().
Referenced by CImg< uintT >::save_gzip_external(), and CImgList< uintT >::save_gzip_external().
{
       static char *st_path = 0;
       if (reinit_path && st_path) { delete[] st_path; st_path = 0; }
       if (user_path) {
         if (!st_path) st_path = new char[1024];
         std::memset(st_path,0,1024);
         std::strncpy(st_path,user_path,1023);
       } else if (!st_path) {
         st_path = new char[1024];
         std::memset(st_path,0,1024);
         bool path_found = false;
         std::FILE *file = 0;
 #if cimg_OS==2
         if (!path_found) {
           std::sprintf(st_path,".\\gzip.exe");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"gzip.exe");
 #else
         if (!path_found) {
           std::sprintf(st_path,"./gzip");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"gzip");
 #endif
         winformat_string(st_path);
       }
       return st_path;
     }
const char* cimg_library::cimg::imagemagick_path (const char *const user_path = 0, const bool reinit_path = false) inline
Return or set path to the ImageMagick's convert tool.
Definition at line 5094 of file CImg.h.
References fclose(), fopen(), k, and winformat_string().
Referenced by info(), CImg< uintT >::load_imagemagick_external(), and CImg< uintT >::save_imagemagick_external().
{
       static char *st_path = 0;
       if (reinit_path && st_path) { delete[] st_path; st_path = 0; }
       if (user_path) {
         if (!st_path) st_path = new char[1024];
         std::memset(st_path,0,1024);
         std::strncpy(st_path,user_path,1023);
       } else if (!st_path) {
         st_path = new char[1024];
         std::memset(st_path,0,1024);
         bool path_found = false;
         std::FILE *file = 0;
 #if cimg_OS==2
         const char *pf_path = programfiles_path();
         if (!path_found) {
           std::sprintf(st_path,".\\convert.exe");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"%s\\IMAGEM~1.%.2d-\\convert.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"%s\\IMAGEM~1.%d-Q\\convert.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"%s\\IMAGEM~1.%d\\convert.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"%s\\IMAGEM~1.%.2d-\\VISUA~1\\BIN\\convert.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"%s\\IMAGEM~1.%d-Q\\VISUA~1\\BIN\\convert.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"%s\\IMAGEM~1.%d\\VISUA~1\\BIN\\convert.exe",pf_path,k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"C:\\IMAGEM~1.%.2d-\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"C:\\IMAGEM~1.%d-Q\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"C:\\IMAGEM~1.%d\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"C:\\IMAGEM~1.%.2d-\\VISUA~1\\BIN\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"C:\\IMAGEM~1.%d-Q\\VISUA~1\\BIN\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"C:\\IMAGEM~1.%d\\VISUA~1\\BIN\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"D:\\IMAGEM~1.%.2d-\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"D:\\IMAGEM~1.%d-Q\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"D:\\IMAGEM~1.%d\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=10 && !path_found; --k) {
           std::sprintf(st_path,"D:\\IMAGEM~1.%.2d-\\VISUA~1\\BIN\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 9; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"D:\\IMAGEM~1.%d-Q\\VISUA~1\\BIN\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         for (int k = 32; k>=0 && !path_found; --k) {
           std::sprintf(st_path,"D:\\IMAGEM~1.%d\\VISUA~1\\BIN\\convert.exe",k);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"convert.exe");
 #else
         if (!path_found) {
           std::sprintf(st_path,"./convert");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"convert");
 #endif
         winformat_string(st_path);
       }
       return st_path;
     }
void info () inline
Print informations about CImg environement variables.
Printing is done on the standard error output.
Definition at line 5702 of file CImg.h.
References cimg_debug, cimg_display, cimg_OS, cimg_stdout, cimg_version, endianness(), graphicsmagick_path(), imagemagick_path(), medcon_path(), t_bold, t_green, t_normal, t_red, and temporary_path().
Referenced by FaceOffset_3::compute_eigenvectors(), Rocmop::compute_eigenvectors(), PatchData::have_computed_info(), main(), and PatchData::note_have_info().
{
       char tmp[1024] = { 0 };
       std::fprintf(cimg_stdout,"\n %sCImg Library %u.%u.%u%s, compiled %s ( %s ) with the following flags :\n\n",
                    cimg::t_red,cimg_version/100,(cimg_version/10)%10,cimg_version%10,
                    cimg::t_normal,__DATE__,__TIME__);
       std::fprintf(cimg_stdout,"  > Operating System :       %s%-13s%s %s('cimg_OS'=%d)%s\n",
                    cimg::t_bold,
                    cimg_OS==1?"Unix":(cimg_OS==2?"Windows":"Unknow"),
                    cimg::t_normal,cimg::t_green,
                    cimg_OS,
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > CPU endianness :         %s%s Endian%s\n",
                    cimg::t_bold,
                    cimg::endianness()?"Big":"Little",
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Debug messages :         %s%-13s%s %s('cimg_debug'=%d)%s\n",
                    cimg::t_bold,
                    cimg_debug==0?"Quiet":(cimg_debug==1?"Console":(cimg_debug==2?"Dialog":(cimg_debug==3?"Console+Warnings":"Dialog+Warnings"))),
                    cimg::t_normal,cimg::t_green,
                    cimg_debug,
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Stricts warnings :       %s%-13s%s %s('cimg_strict_warnings' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_strict_warnings
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Using VT100 messages :   %s%-13s%s %s('cimg_use_vt100' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_vt100
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Display type :           %s%-13s%s %s('cimg_display'=%d)%s\n",
                    cimg::t_bold,
                    cimg_display==0?"No display":
                    (cimg_display==1?"X11":
                     (cimg_display==2?"Windows GDI":
                      (cimg_display==3?"Carbon":"Unknow"))),
                    cimg::t_normal,cimg::t_green,
                    cimg_display,
                    cimg::t_normal);
 #if cimg_display==1
       std::fprintf(cimg_stdout,"  > Using XShm for X11 :     %s%-13s%s %s('cimg_use_xshm' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_xshm
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Using XRand for X11 :    %s%-13s%s %s('cimg_use_xrandr' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_xrandr
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
 #endif
       std::fprintf(cimg_stdout,"  > Using OpenMP :           %s%-13s%s %s('cimg_use_openmp' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_openmp
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Using PNG library :      %s%-13s%s %s('cimg_use_png' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_png
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Using JPEG library :     %s%-13s%s %s('cimg_use_jpeg' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_jpeg
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Using TIFF library :     %s%-13s%s %s('cimg_use_tiff' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_tiff
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Using Magick++ library : %s%-13s%s %s('cimg_use_magick' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_magick
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Using FFTW3 library :    %s%-13s%s %s('cimg_use_fftw3' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_fftw3
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"  > Using LAPACK library :   %s%-13s%s %s('cimg_use_lapack' %s)%s\n",
                    cimg::t_bold,
 #ifdef cimg_use_lapack
                    "Yes",cimg::t_normal,cimg::t_green,"defined",
 #else
                    "No",cimg::t_normal,cimg::t_green,"undefined",
 #endif
                    cimg::t_normal);
       std::sprintf(tmp,"\"%.1020s\"",cimg::imagemagick_path());
       std::fprintf(cimg_stdout,"  > Path of ImageMagick :    %s%-13s%s\n",
                    cimg::t_bold,
                    tmp,
                    cimg::t_normal);
       std::sprintf(tmp,"\"%.1020s\"",cimg::graphicsmagick_path());
       std::fprintf(cimg_stdout,"  > Path of GraphicsMagick : %s%-13s%s\n",
                    cimg::t_bold,
                    tmp,
                    cimg::t_normal);
       std::sprintf(tmp,"\"%.1020s\"",cimg::medcon_path());
       std::fprintf(cimg_stdout,"  > Path of 'medcon' :       %s%-13s%s\n",
                    cimg::t_bold,
                    tmp,
                    cimg::t_normal);
       std::sprintf(tmp,"\"%.1020s\"",cimg::temporary_path());
       std::fprintf(cimg_stdout,"  > Temporary path :         %s%-13s%s\n",
                    cimg::t_bold,
                    tmp,
                    cimg::t_normal);
       std::fprintf(cimg_stdout,"\n");
     }
void cimg_library::cimg::invert_endianness (T *const buffer, const unsigned int size) inline
Invert endianness of a memory buffer.
Definition at line 4579 of file CImg.h.
References i, and swap().
Referenced by CImg< uintT >::_load_analyze(), CImg< uintT >::_load_pandore(), CImg< uintT >::_load_png(), CImg< uintT >::_load_pnm(), CImg< uintT >::_load_raw(), CImgList< uintT >::_save_cimg(), CImg< uintT >::_save_png(), CImg< uintT >::_save_pnm(), invert_endianness(), CImg< uintT >::invert_endianness(), and CImgList< uintT >::load_parrec().
{
       if (size) switch (sizeof(T)) {
       case 1 : break;
       case 2 : { for (unsigned short *ptr = (unsigned short*)buffer+size; ptr>(unsigned short*)buffer; ) {
         const unsigned short val = *(--ptr);
         *ptr = (unsigned short)((val>>8)|((val<<8)));
       }} break;
       case 4 : { for (unsigned int *ptr = (unsigned int*)buffer+size; ptr>(unsigned int*)buffer; ) {
         const unsigned int val = *(--ptr);
         *ptr = (val>>24)|((val>>8)&0xff00)|((val<<8)&0xff0000)|(val<<24);
       }} break;
       default : { for (T* ptr = buffer+size; ptr>buffer; ) {
         unsigned char *pb = (unsigned char*)(--ptr), *pe = pb + sizeof(T);
         for (int i = 0; i<(int)sizeof(T)/2; ++i) swap(*(pb++),*(--pe));
       }}
       }
     }
T& cimg_library::cimg::invert_endianness (T & a) inline
Invert endianness of a single variable.
Definition at line 4599 of file CImg.h.
References invert_endianness().
{
       invert_endianness(&a,1);
       return a;
     }
cimg::superset<t1,t2>::type cimg_library::cimg::max (const t1 & a, const t2 & b) inline
Return the maximum value between two numbers.
Definition at line 4749 of file CImg.h.
Referenced by CImg< uintT >::_cubic_atX(), CImg< uintT >::_cubic_atXY(), CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_draw_ellipse(), CImg< uintT >::_draw_object3d(), CImg< uintT >::_draw_scanline(), CImg< uintT >::_load_dlm(), CImgList< uintT >::assign(), CImg< uintT >::autocrop(), CImg< uintT >::blur(), CImg< uintT >::blur_bilateral(), CImgList< uintT >::CImgList(), CImg< uintT >::cubic_atX(), CImg< uintT >::cubic_atXY(), dialog(), CImg< uintT >::distance_hamilton(), CImg< uintT >::draw_fill(), CImg< uintT >::draw_gaussian(), CImg< uintT >::draw_image(), CImg< uintT >::draw_line(), CImg< uintT >::draw_mandelbrot(), CImg< uintT >::draw_plasma(), CImg< uintT >::draw_point(), CImg< uintT >::draw_quiver(), CImg< uintT >::draw_rectangle(), CImg< uintT >::draw_spline(), CImg< uintT >::draw_triangle(), CImg< uintT >::edge_tensors(), CImg< T >::_cimg_math_parser::eval(), CImgList< uintT >::get_append(), CImg< uintT >::get_blur_patch(), CImg< uintT >::get_displacement_field(), CImg< uintT >::get_distance(), CImg< uintT >::get_identity_matrix(), CImg< uintT >::get_resize(), CImg< uintT >::get_rotate(), CImg< uintT >::identity_matrix(), CImg< uintT >::load_tiff(), max(), CImg< uintT >::max(), CImg< uintT >::resize_object3d(), CImg< uintT >::RGBtoHSL(), CImg< uintT >::RGBtoHSV(), CImg< uintT >::sharpen(), and CImg< uintT >::SVD().
{
       typedef typename cimg::superset<t1,t2>::type t1t2;
       return (t1t2)(a>=b?a:b);
     }
cimg::superset2<t1,t2,t3>::type cimg_library::cimg::max (const t1 & a, const t2 & b, const t3 & c) inline
Return the maximum value between three numbers.
Definition at line 4756 of file CImg.h.
References max().
{
       typedef typename cimg::superset2<t1,t2,t3>::type t1t2t3;
       return (t1t2t3)cimg::max(cimg::max(a,b),c);
     }
cimg::superset3<t1,t2,t3,t4>::type cimg_library::cimg::max (const t1 & a, const t2 & b, const t3 & c, const t4 & d) inline
Return the maximum value between four numbers.
Definition at line 4763 of file CImg.h.
References max().
{
       typedef typename cimg::superset3<t1,t2,t3,t4>::type t1t2t3t4;
       return (t1t2t3t4)cimg::max(cimg::max(a,b,c),d);
     }
const char* cimg_library::cimg::medcon_path (const char *const user_path = 0, const bool reinit_path = false) inline
Return or set path of the XMedcon tool.
Definition at line 5302 of file CImg.h.
References fclose(), fopen(), and winformat_string().
Referenced by info(), CImg< uintT >::load_medcon_external(), and CImg< uintT >::save_medcon_external().
{
       static char *st_path = 0;
       if (reinit_path && st_path) { delete[] st_path; st_path = 0; }
       if (user_path) {
         if (!st_path) st_path = new char[1024];
         std::memset(st_path,0,1024);
         std::strncpy(st_path,user_path,1023);
       } else if (!st_path) {
         st_path = new char[1024];
         std::memset(st_path,0,1024);
         bool path_found = false;
         std::FILE *file = 0;
 #if cimg_OS==2
         const char* pf_path = programfiles_path();
         if (!path_found) {
           std::sprintf(st_path,".\\medcon.bat");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) {
           std::sprintf(st_path,".\\medcon.exe");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) {
           std::sprintf(st_path,"%s\\XMedCon\\bin\\medcon.bat",pf_path);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) {
           std::sprintf(st_path,"%s\\XMedCon\\bin\\medcon.exe",pf_path);
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"medcon.bat");
 #else
         if (!path_found) {
           std::sprintf(st_path,"./medcon");
           if ((file=std::fopen(st_path,"r"))!=0) { std::fclose(file); path_found = true; }
         }
         if (!path_found) std::strcpy(st_path,"medcon");
 #endif
         winformat_string(st_path);
       }
       return st_path;
     }
cimg::superset<t1,t2>::type cimg_library::cimg::min (const t1 & a, const t2 & b) inline
Return the minimum value between two numbers.
Definition at line 4728 of file CImg.h.
Referenced by CImg< uintT >::_cubic_atX(), CImg< uintT >::_cubic_atXY(), CImg< uintT >::_display_object3d(), CImg< uintT >::_draw_object3d(), CImg< uintT >::_draw_scanline(), CImg< uintT >::_get_select(), CImg< uintT >::_load_bmp(), CImg< uintT >::_load_pnm(), CImg< uintT >::_load_rgb(), CImg< uintT >::_load_rgba(), CImgList< uintT >::_save_cimg(), CImg< uintT >::atan2(), CImg< uintT >::autocrop(), CImg< uintT >::cubic_atX(), CImg< uintT >::cubic_atXY(), CImg< uintT >::dot(), CImg< uintT >::draw_line(), CImg< uintT >::draw_point(), CImg< uintT >::draw_polygon(), CImg< uintT >::draw_spline(), CImg< uintT >::draw_triangle(), CImg< T >::_cimg_math_parser::eval(), CImg< uintT >::get_BayertoRGB(), CImg< uintT >::get_CMYtoCMYK(), CImg< uintT >::get_resize(), CImg< uintT >::get_rotate(), CImg< uintT >::get_split(), CImg< uintT >::max(), min(), CImg< uintT >::min(), CImg< uintT >::pow(), CImg< uintT >::quantize(), CImg< uintT >::RGBtoHSI(), CImg< uintT >::RGBtoHSL(), CImg< uintT >::RGBtoHSV(), CImg< uintT >::set_vector_at(), and CImg< uintT >::SVD().
{
       typedef typename cimg::superset<t1,t2>::type t1t2;
       return (t1t2)(a<=b?a:b);
     }
cimg::superset2<t1,t2,t3>::type cimg_library::cimg::min (const t1 & a, const t2 & b, const t3 & c) inline
Return the minimum value between three numbers.
Definition at line 4735 of file CImg.h.
References min().
{
       typedef typename cimg::superset2<t1,t2,t3>::type t1t2t3;
       return (t1t2t3)cimg::min(cimg::min(a,b),c);
     }
cimg::superset3<t1,t2,t3,t4>::type cimg_library::cimg::min (const t1 & a, const t2 & b, const t3 & c, const t4 & d) inline
Return the minimum value between four numbers.
Definition at line 4742 of file CImg.h.
References min().
{
       typedef typename cimg::superset3<t1,t2,t3,t4>::type t1t2t3t4;
       return (t1t2t3t4)cimg::min(cimg::min(a,b,c),d);
     }
T cimg_library::cimg::minmod (const T a, const T b) inline
Return the minmod of two numbers.
minmod(a,b) is defined to be :
minmod(a,b) = min(a,b), if a and b have the same sign.
minmod(a,b) = 0, if a and b have different signs.
Definition at line 4828 of file CImg.h.
Referenced by CImg< uintT >::sharpen().
{
       return a*b<=0?0:(a>0?(a<b?a:b):(a<b?b:a));
     }
T cimg_library::cimg::mod (const T & x, const T & m) inline
Return the modulo of a number.
Note
This modulo function accepts negative and floating-points modulo numbers, as well as variable of any type.
Definition at line 4788 of file CImg.h.
Referenced by CImg< uintT >::draw_grid(), CImg< T >::_cimg_math_parser::eval(), CImg< uintT >::get_rotate(), CImg< uintT >::get_warp(), Coupling::normalize_modname(), CImg< uintT >::operator%=(), round(), and CImg< uintT >::translate().
{
       const double dx = (double)x, dm = (double)m;
       if (x<0) { return (T)(dm+dx+dm*std::floor(-dx/dm)); }
       return (T)(dx-dm*std::floor(dx/dm));
     }
int cimg_library::cimg::mod (const bool x, const bool m) inline
Definition at line 4793 of file CImg.h.
{
       return m?(x?1:0):0;
     }
int cimg_library::cimg::mod (const char x, const char m) inline
Definition at line 4796 of file CImg.h.
{
       return x>=0?x%m:(x%m?m+x%m:0);
     }
int cimg_library::cimg::mod (const short x, const short m) inline
Definition at line 4799 of file CImg.h.
{
       return x>=0?x%m:(x%m?m+x%m:0);
     }
int cimg_library::cimg::mod (const int x, const int m) inline
Definition at line 4802 of file CImg.h.
{
       return x>=0?x%m:(x%m?m+x%m:0);
     }
int cimg_library::cimg::mod (const long x, const long m) inline
Definition at line 4805 of file CImg.h.
{
       return x>=0?x%m:(x%m?m+x%m:0);
     }
int cimg_library::cimg::mod (const unsigned char x, const unsigned char m) inline
Definition at line 4808 of file CImg.h.
{
       return x%m;
     }
int cimg_library::cimg::mod (const unsigned short x, const unsigned short m) inline
Definition at line 4811 of file CImg.h.
{
       return x%m;
     }
int cimg_library::cimg::mod (const unsigned int x, const unsigned int m) inline
Definition at line 4814 of file CImg.h.
{
       return x%m;
     }
int cimg_library::cimg::mod (const unsigned long x, const unsigned long m) inline
Definition at line 4817 of file CImg.h.
{
       return x%m;
     }
unsigned int cimg_library::cimg::nearest_pow2 (const T x) inline
Return the nearest power of 2 higher than a given number.
Definition at line 4776 of file CImg.h.
References i.
Referenced by CImgList< uintT >::assign(), and CImgList< uintT >::CImgList().
{
       unsigned int i = 1;
       while (x>i) i<<=1;
       return i;
     }
char* cimg_library::cimg::number_filename (const char *const filename, const int number, const unsigned int n, char *const string) inline
Create a numbered version of a filename.
Definition at line 5483 of file CImg.h.
References split_filename().
Referenced by CImg< uintT >::save(), and CImgList< uintT >::save().
{
       if (!filename) { if (string) string[0] = 0; return 0; }
       char format[1024] = { 0 }, body[1024] = { 0 };
       const char *ext = cimg::split_filename(filename,body);
       if (n>0) std::sprintf(format,"%s_%%.%ud.%s",body,n,ext);
       else std::sprintf(format,"%s_%%d.%s",body,ext);
       std::sprintf(string,format,number);
       return string;
     }
const char* cimg_library::cimg::option (const char *const name, const int argc, const char *const *const argv, const char * defaut, const char *const usage = 0) inline
Definition at line 5604 of file CImg.h.
References basename(), cimg_stdout, k, t_bold, t_green, t_normal, and t_red.
Referenced by argument(), get_parameter_list(), Agent::init_callback(), option(), ComSwitch::readOptions(), Rocprop::set_option(), Rocmop::set_value(), and Rocout::write_parameter_file().
{
       static bool first = true, visu = false;
       const char *res = 0;
       if (first) {
         first=false;
         visu = (cimg::option("-h",argc,argv,(char*)0)!=0);
         visu |= (cimg::option("-help",argc,argv,(char*)0)!=0);
         visu |= (cimg::option("--help",argc,argv,(char*)0)!=0);
       }
       if (!name && visu) {
         if (usage) {
           std::fprintf(cimg_stdout,"\n %s%s%s",cimg::t_red,cimg::basename(argv[0]),cimg::t_normal);
           std::fprintf(cimg_stdout," : %s",usage);
           std::fprintf(cimg_stdout," (%s, %s)\n\n",__DATE__,__TIME__);
         }
         if (defaut) std::fprintf(cimg_stdout,"%s\n",defaut);
       }
       if (name) {
         if (argc>0) {
           int k = 0;
           while (k<argc && std::strcmp(argv[k],name)) ++k;
           res = (k++==argc?defaut:(k==argc?argv[--k]:argv[k]));
         } else res = defaut;
         if (visu && usage) std::fprintf(cimg_stdout,"    %s%-16s%s %-24s %s%s%s\n",
                                         cimg::t_bold,name,cimg::t_normal,res?res:"0",cimg::t_green,usage,cimg::t_normal);
       }
       return res;
     }
bool cimg_library::cimg::option (const char *const name, const int argc, const char *const *const argv, const bool defaut, const char *const usage = 0) inline
Definition at line 5634 of file CImg.h.
References option(), s, and strcasecmp().
{
       const char *s = cimg::option(name,argc,argv,(char*)0);
       const bool res = s?(cimg::strcasecmp(s,"false") && cimg::strcasecmp(s,"off") && cimg::strcasecmp(s,"0")):defaut;
       cimg::option(name,0,0,res?"true":"false",usage);
       return res;
     }
int cimg_library::cimg::option (const char *const name, const int argc, const char *const *const argv, const int defaut, const char *const usage = 0) inline
Definition at line 5642 of file CImg.h.
References option(), and s.
{
       const char *s = cimg::option(name,argc,argv,(char*)0);
       const int res = s?std::atoi(s):defaut;
       char tmp[256] = { 0 };
       std::sprintf(tmp,"%d",res);
       cimg::option(name,0,0,tmp,usage);
       return res;
     }
char cimg_library::cimg::option (const char *const name, const int argc, const char *const *const argv, const char defaut, const char *const usage = 0) inline
Definition at line 5652 of file CImg.h.
References option(), and s.
{
       const char *s = cimg::option(name,argc,argv,(char*)0);
       const char res = s?s[0]:defaut;
       char tmp[8] = { 0 };
       tmp[0] = res;
       cimg::option(name,0,0,tmp,usage);
       return res;
     }
float cimg_library::cimg::option (const char *const name, const int argc, const char *const *const argv, const float defaut, const char *const usage = 0) inline
Definition at line 5662 of file CImg.h.
References atof(), option(), and s.
{
       const char *s = cimg::option(name,argc,argv,(char*)0);
       const float res = s?cimg::atof(s):defaut;
       char tmp[256] = { 0 };
       std::sprintf(tmp,"%g",res);
       cimg::option(name,0,0,tmp,usage);
       return res;
     }
double cimg_library::cimg::option (const char *const name, const int argc, const char *const *const argv, const double defaut, const char *const usage = 0) inline
Definition at line 5672 of file CImg.h.
References atof(), option(), and s.
{
       const char *s = cimg::option(name,argc,argv,(char*)0);
       const double res = s?cimg::atof(s):defaut;
       char tmp[256] = { 0 };
       std::sprintf(tmp,"%g",res);
       cimg::option(name,0,0,tmp,usage);
       return res;
     }
unsigned int cimg_library::cimg::prand (const double z) inline
Return a random variable following a Poisson distribution of parameter z.
Definition at line 4856 of file CImg.h.
References cimg_library::exp(), grand(), k, rand(), s, sqrt(), and y.
Referenced by CImg< uintT >::noise().
{
       if (z<=1.0e-10) return 0;
       if (z>100.0) return (unsigned int)((std::sqrt(z) * cimg::grand()) + z);
       unsigned int k = 0;
       const double y = std::exp(-z);
       for (double s = 1.0; s>=y; ++k) s*=cimg::rand();
       return k-1;
     }
double cimg_library::cimg::rand () inline
Return a random variable between [0,1] with respect to an uniform distribution.
Definition at line 4833 of file CImg.h.
References srand().
Referenced by crand(), CImg< T >::_cimg_math_parser::eval(), filenamerand(), grand(), main(), CImg< uintT >::noise(), Rocblas::random< T >::operator()(), Rocblas::random< double >::operator()(), Rocmop::perturb_stationary(), prand(), CImg< uintT >::rand(), Randomize::randomize_vertex(), and srand().
{
       static bool first_time = true;
       if (first_time) { cimg::srand(); first_time = false; }
       return (double)std::rand()/RAND_MAX;
     }
const T cimg_library::cimg::rol (const T a, const unsigned int n = 1) inline
Return a left bitwise-rotated number.
Definition at line 4671 of file CImg.h.
{
       return n?(T)((a<<n)|(a>>((sizeof(T)<<3)-n))):a;
     }
const T cimg_library::cimg::ror (const T a, const unsigned int n = 1) inline
Return a right bitwise-rotated number.
Definition at line 4677 of file CImg.h.
Referenced by CImg< uintT >::_load_bmp().
{
       return n?(T)((a>>n)|(a<<((sizeof(T)<<3)-n))):a;
     }
double cimg_library::cimg::round (const double x, const double y, const int rounding_type = 0) inline
Return a rounded number.
Parameters
x is the number to be rounded.
y is the rounding precision.
rounding_type defines the type of rounding (0=nearest, -1=backward, 1=forward).
Definition at line 4871 of file CImg.h.
References mod(), x, and y.
Referenced by CImg< T >::_cimg_math_parser::eval(), and CImg< uintT >::round().
{
       if (y<=0) return x;
       const double delta = cimg::mod(x,y);
       if (delta==0.0) return x;
       const double
         backward = x - delta,
         forward = backward + y;
       return rounding_type<0?backward:(rounding_type>0?forward:(2*delta<y?backward:forward));
     }
T cimg_library::cimg::sign (const T x) inline
Return the sign of a number.
Definition at line 4770 of file CImg.h.
Referenced by CImg< uintT >::distance_hamilton(), CImg< T >::_cimg_math_parser::eval(), and CImg< uintT >::sharpen().
{
       return (x<0)?(T)(-1):(x==0?(T)0:(T)1);
     }
void cimg_library::cimg::sleep (const unsigned int milliseconds) inline
Sleep for a certain numbers of milliseconds.
This function frees the CPU ressources during the sleeping time. It may be used to temporize your program properly, without wasting CPU time.
Definition at line 4624 of file CImg.h.
Referenced by _sleep().
{
 #if cimg_OS==1
       struct timespec tv;
       tv.tv_sec = milliseconds/1000;
       tv.tv_nsec = (milliseconds%1000)*1000000;
       nanosleep(&tv,0);
 #elif cimg_OS==2
       Sleep(milliseconds);
 #endif
     }
const char* cimg_library::cimg::split_filename (const char *const filename, char *const body = 0) inline
Split a filename into two strings 'body' and 'extension'.
Definition at line 5470 of file CImg.h.
Referenced by CImg< uintT >::_load_analyze(), CImg< uintT >::load(), CImgList< uintT >::load(), CImg< uintT >::load_gzip_external(), CImgList< uintT >::load_gzip_external(), CImg< uintT >::load_medcon_external(), CImgList< uintT >::load_parrec(), number_filename(), CImg< uintT >::save(), CImgList< uintT >::save(), CImg< uintT >::save_analyze(), CImg< uintT >::save_gzip_external(), CImgList< uintT >::save_gzip_external(), and CImg< uintT >::save_medcon_external().
{
       if (!filename) { if (body) body[0] = 0; return 0; }
       const char *p = 0; for (const char *np = filename; np>=filename && (p=np); np = std::strchr(np,'.')+1) {}
       if (p==filename) {
         if (body) std::strcpy(body,filename);
         return filename + std::strlen(filename);
       }
       const unsigned int l = p - filename - 1;
       if (body) { std::memcpy(body,filename,l); body[l] = 0; }
       return p;
     }
T cimg_library::cimg::sqr (const T val) inline
Return the square of a number.
Definition at line 4717 of file CImg.h.
Referenced by CImg< uintT >::_draw_object3d(), CImg< uintT >::get_BayertoRGB(), CImg< uintT >::get_distance(), CImg< uintT >::get_index(), and QualityAssessor::Assessor::get_stddev().
{
       return val*val;
     }
void cimg_library::cimg::srand () inline
Definition at line 4658 of file CImg.h.
References rand(), and time().
Referenced by filenamerand(), main(), and rand().
{
       static bool first_time = true;
       if (first_time) {
         std::srand(cimg::time());
         unsigned char *const rand_ptr = new unsigned char[1+std::rand()%2048];
         std::srand((unsigned int)std::rand() + *(unsigned int*)(void*)rand_ptr);
         delete[] rand_ptr;
         first_time = false;
       }
     }
int cimg_library::cimg::strcasecmp (const char *const s1, const char *const s2) inline
Compare two C-strings, ignoring the case.
Note
This function is defined since it is not provided by all compilers (not an ANSI function).
Definition at line 4928 of file CImg.h.
References strncasecmp().
Referenced by CImg< uintT >::_load_analyze(), CImg< uintT >::_save_inr(), argument(), FindFirstGeometryDataset(), CImg< uintT >::get_hessian(), Scheduler::ActionItem::hasInput(), Scheduler::ActionItem::hasOutput(), CImg< uintT >::load(), CImgList< uintT >::load(), CImg< uintT >::load_gzip_external(), CImgList< uintT >::load_gzip_external(), option(), rocstar_driver(), CImg< uintT >::save(), CImgList< uintT >::save(), CImg< uintT >::save_analyze(), CImg< uintT >::save_gzip_external(), CImgList< uintT >::save_gzip_external(), and scan_files_HDF4().
{
       if (!s1) return s2?-1:0;
       const unsigned int l1 = std::strlen(s1), l2 = std::strlen(s2);
       return cimg::strncasecmp(s1,s2,1+(l1<l2?l1:l2));
     }
void cimg_library::cimg::strclean (char *const s) inline
Remove useless spaces and symmetric delimiters ', " and ` from a C-string.
Definition at line 4950 of file CImg.h.
References strpare().
Referenced by CImg< T >::_cimg_math_parser::_cimg_math_parser().
{
       if (!s) return;
       strpare(s,' ',false);
       for (bool need_iter = true; need_iter; ) {
         need_iter = false;
         need_iter |= strpare(s,'\'',true);
         need_iter |= strpare(s,'\"',true);
         need_iter |= strpare(s,'`',true);
       }
     }
void cimg_library::cimg::strescape (char *const s) inline
Replace explicit escape sequences '' in C-strings.
Definition at line 4962 of file CImg.h.
References cimg_strescape.
{
 #define cimg_strescape(ci,co) case ci: *nd = co; ++ns; break;
       static unsigned int val = 0;
       for (char *ns = s, *nd = s; *ns || (bool)(*nd=0); ++nd) if (*ns=='\\') switch (*(++ns)) {
         cimg_strescape('n','\n');
         cimg_strescape('t','\t');
         cimg_strescape('v','\v');
         cimg_strescape('b','\b');
         cimg_strescape('r','\r');
         cimg_strescape('f','\f');
         cimg_strescape('a','\a');
         cimg_strescape('\\','\\');
         cimg_strescape('\?','\?');
         cimg_strescape('\'','\'');
         cimg_strescape('\"','\"');
       case 0 : *nd = 0; break;
       case '0' : case '1' : case '2' : case '3' : case '4' : case '5' : case '6' : case '7' :
         std::sscanf(ns,"%o",&val); while (*ns>='0' && *ns<='7') ++ns;
         *nd = val; break;
       case 'x':
         std::sscanf(++ns,"%x",&val); while ((*ns>='0' && *ns<='7') || (*ns>='a' && *ns<='f') || (*ns>='A' && *ns<='F')) ++ns;
         *nd = val; break;
       default : *nd='\\';
       } else *nd = *(ns++);
     }
int cimg_library::cimg::strncasecmp (const char *const s1, const char *const s2, const int l) inline
Compare the first n characters of two C-strings, ignoring the case.
Note
This function is defined since it is not provided by all compilers (not an ANSI function).
Definition at line 4915 of file CImg.h.
References k, and uncase().
Referenced by CImg< uintT >::_get_permute_axes(), CImgList< uintT >::_load_cimg(), CImg< uintT >::_load_inr_header(), CImg< uintT >::_load_off(), CImg< uintT >::_load_pandore(), CImgList< uintT >::_save_cimg(), CImg< uintT >::load(), CImgList< uintT >::load(), CImg< uintT >::save_analyze(), scan_files_HDF4(), and strcasecmp().
{
       if (!l) return 0;
       if (!s1) return s2?-1:0;
       const char *ns1 = s1, *ns2 = s2;
       int k, diff = 0; for (k = 0; k<l && !(diff = uncase(*ns1)-uncase(*ns2)); ++k) { ++ns1; ++ns2; }
       return k!=l?diff:0;
     }
bool cimg_library::cimg::strpare (char *const s, const char delimiter = ' ', const bool symmetric = false) inline
Remove useless delimiters on the borders of a C-string.
Definition at line 4935 of file CImg.h.
Referenced by strclean().
{
       if (!s) return false;
       const int l = (int)std::strlen(s);
       int p, q;
       if (symmetric) for (p = 0, q = l-1; p<q && s[p]==delimiter && s[q]==delimiter; ++p) --q;
       else {
         for (p = 0; p<l && s[p]==delimiter; ) ++p;
         for (q = l-1; q>p && s[q]==delimiter; ) --q;
       }
       const int n = q - p + 1;
       if (n!=l) { std::memmove(s,s+p,n); s[n] = 0; return true; }
       return false;
     }
void cimg_library::cimg::swap (T & a, T & b) inline
Exchange values of variables a and b.
Definition at line 4522 of file CImg.h.
Referenced by CImg< uintT >::_draw_triangle(), CImg< uintT >::_get_select(), CImg< uintT >::_LU(), CImg< uintT >::_quicksort(), CImg< uintT >::dijkstra(), CImg< uintT >::draw_line(), CImg< uintT >::draw_plasma(), CImg< uintT >::draw_triangle(), CImg< uintT >::FFT(), CImg< uintT >::get_hessian(), CImg< uintT >::get_index(), CImg< uintT >::get_select_graph(), invert_endianness(), CImg< uintT >::isosurface3d(), CImg< uintT >::kth_smallest(), CImgList< uintT >::reverse_object3d(), swap(), CImg< uintT >::swap(), CImgList< uintT >::swap(), and CImg< uintT >::transpose().
 { T t = a; a = b; b = t; }
void cimg_library::cimg::swap (T1 & a1, T1 & b1, T2 & a2, T2 & b2) inline
Exchange values of variables (a1,a2) and (b1,b2).
Definition at line 4526 of file CImg.h.
References swap().
{
       cimg::swap(a1,b1); cimg::swap(a2,b2);
     }
void cimg_library::cimg::swap (T1 & a1, T1 & b1, T2 & a2, T2 & b2, T3 & a3, T3 & b3) inline
Exchange values of variables (a1,a2,a3) and (b1,b2,b3).
Definition at line 4532 of file CImg.h.
References swap().
{
       cimg::swap(a1,b1,a2,b2); cimg::swap(a3,b3);
     }
void cimg_library::cimg::swap (T1 & a1, T1 & b1, T2 & a2, T2 & b2, T3 & a3, T3 & b3, T4 & a4, T4 & b4) inline
Exchange values of variables (a1,a2,...,a4) and (b1,b2,...,b4).
Definition at line 4538 of file CImg.h.
References swap().
{
       cimg::swap(a1,b1,a2,b2,a3,b3); cimg::swap(a4,b4);
     }
void cimg_library::cimg::swap (T1 & a1, T1 & b1, T2 & a2, T2 & b2, T3 & a3, T3 & b3, T4 & a4, T4 & b4, T5 & a5, T5 & b5) inline
Exchange values of variables (a1,a2,...,a5) and (b1,b2,...,b5).
Definition at line 4544 of file CImg.h.
References swap().
{
       cimg::swap(a1,b1,a2,b2,a3,b3,a4,b4); cimg::swap(a5,b5);
     }
void cimg_library::cimg::swap (T1 & a1, T1 & b1, T2 & a2, T2 & b2, T3 & a3, T3 & b3, T4 & a4, T4 & b4, T5 & a5, T5 & b5, T6 & a6, T6 & b6) inline
Exchange values of variables (a1,a2,...,a6) and (b1,b2,...,b6).
Definition at line 4550 of file CImg.h.
References swap().
{
       cimg::swap(a1,b1,a2,b2,a3,b3,a4,b4,a5,b5); cimg::swap(a6,b6);
     }
void cimg_library::cimg::swap (T1 & a1, T1 & b1, T2 & a2, T2 & b2, T3 & a3, T3 & b3, T4 & a4, T4 & b4, T5 & a5, T5 & b5, T6 & a6, T6 & b6, T7 & a7, T7 & b7) inline
Exchange values of variables (a1,a2,...,a7) and (b1,b2,...,b7).
Definition at line 4556 of file CImg.h.
References swap().
{
       cimg::swap(a1,b1,a2,b2,a3,b3,a4,b4,a5,b5,a6,b6); cimg::swap(a7,b7);
     }
void cimg_library::cimg::swap (T1 & a1, T1 & b1, T2 & a2, T2 & b2, T3 & a3, T3 & b3, T4 & a4, T4 & b4, T5 & a5, T5 & b5, T6 & a6, T6 & b6, T7 & a7, T7 & b7, T8 & a8, T8 & b8) inline
Exchange values of variables (a1,a2,...,a8) and (b1,b2,...,b8).
Definition at line 4563 of file CImg.h.
References swap().
{
       cimg::swap(a1,b1,a2,b2,a3,b3,a4,b4,a5,b5,a6,b6,a7,b7); cimg::swap(a8,b8);
     }
int cimg_library::cimg::system (const char *const command, const char *const module_name = 0) inline
Note
This function is similar to std::system() and is here because using the std:: version on Windows may open undesired consoles.
Definition at line 4491 of file CImg.h.
References FALSE, and pi.
Referenced by COM_F_FUNC2(), CImg< uintT >::load_dcraw_external(), CImgList< uintT >::load_ffmpeg_external(), CImg< uintT >::load_graphicsmagick_external(), CImg< uintT >::load_gzip_external(), CImgList< uintT >::load_gzip_external(), CImg< uintT >::load_imagemagick_external(), CImg< uintT >::load_medcon_external(), Coupling::restart_at_time(), CImgList< uintT >::save_ffmpeg_external(), CImg< uintT >::save_graphicsmagick_external(), CImg< uintT >::save_gzip_external(), CImgList< uintT >::save_gzip_external(), CImg< uintT >::save_imagemagick_external(), and CImg< uintT >::save_medcon_external().
{
 #if cimg_OS==2
       PROCESS_INFORMATION pi;
       STARTUPINFO si;
       std::memset(&pi,0,sizeof(PROCESS_INFORMATION));
       std::memset(&si,0,sizeof(STARTUPINFO));
       GetStartupInfo(&si);
       si.cb = sizeof(si);
       si.wShowWindow = SW_HIDE;
       si.dwFlags |= SW_HIDE;
       const BOOL res = CreateProcess((LPCTSTR)module_name,(LPTSTR)command,0,0,FALSE,0,0,0,&si,&pi);
       if (res) {
         WaitForSingleObject(pi.hProcess, INFINITE);
         CloseHandle(pi.hThread);
         CloseHandle(pi.hProcess);
         return 0;
       } else
 #endif
         return std::system(command);
       return module_name?0:1;
     }
T& cimg_library::cimg::temporary (const T &) inline
Return a reference to a temporary variable of type T.
Definition at line 4515 of file CImg.h.
Referenced by CImg< uintT >::at(), CImgList< uintT >::atN(), CImgList< uintT >::atNX(), CImgList< uintT >::atNXY(), CImgList< uintT >::atNXYZ(), CImgList< uintT >::atNXYZV(), CImg< uintT >::atX(), CImg< uintT >::atXY(), CImg< uintT >::atXYZ(), and CImg< uintT >::atXYZV().
{
       static T temp;
       return temp;
     }
const char* cimg_library::cimg::temporary_path (const char *const user_path = 0, const bool reinit_path = false) inline
Return or set path to store temporary files.
Definition at line 5017 of file CImg.h.
References _cimg_test_temporary_path, fclose(), filenamerand(), fopen(), and winformat_string().
Referenced by info(), CImg< uintT >::load_dcraw_external(), CImgList< uintT >::load_ffmpeg_external(), CImg< uintT >::load_graphicsmagick_external(), CImg< uintT >::load_gzip_external(), CImgList< uintT >::load_gzip_external(), CImg< uintT >::load_imagemagick_external(), CImgList< uintT >::save_ffmpeg_external(), CImg< uintT >::save_graphicsmagick_external(), CImg< uintT >::save_gzip_external(), CImgList< uintT >::save_gzip_external(), and CImg< uintT >::save_imagemagick_external().
{
 #define _cimg_test_temporary_path(p) \
       if (!path_found) { \
         std::sprintf(st_path,"%s",p); \
         std::sprintf(tmp,"%s%c%s",st_path,cimg_file_separator,filetmp); \
         if ((file=std::fopen(tmp,"wb"))!=0) { std::fclose(file); std::remove(tmp); path_found = true; } \
       }
       static char *st_path = 0;
       if (reinit_path && st_path) { delete[] st_path; st_path = 0; }
       if (user_path) {
         if (!st_path) st_path = new char[1024];
         std::memset(st_path,0,1024);
         std::strncpy(st_path,user_path,1023);
       } else if (!st_path) {
         st_path = new char[1024];
         std::memset(st_path,0,1024);
         bool path_found = false;
         char tmp[1024] = { 0 }, filetmp[512] = { 0 };
         std::FILE *file = 0;
         std::sprintf(filetmp,"%s.tmp",cimg::filenamerand());
         char *tmpPath = getenv("TMP");
         if (!tmpPath) { tmpPath = getenv("TEMP"); winformat_string(tmpPath); }
         if (tmpPath) _cimg_test_temporary_path(tmpPath);
 #if cimg_OS==2
         _cimg_test_temporary_path("C:\\WINNT\\Temp");
         _cimg_test_temporary_path("C:\\WINDOWS\\Temp");
         _cimg_test_temporary_path("C:\\Temp");
         _cimg_test_temporary_path("C:");
         _cimg_test_temporary_path("D:\\WINNT\\Temp");
         _cimg_test_temporary_path("D:\\WINDOWS\\Temp");
         _cimg_test_temporary_path("D:\\Temp");
         _cimg_test_temporary_path("D:");
 #else
         _cimg_test_temporary_path("/tmp");
         _cimg_test_temporary_path("/var/tmp");
 #endif
         if (!path_found) {
           st_path[0] = 0;
           std::strcpy(tmp,filetmp);
           if ((file=std::fopen(tmp,"wb"))!=0) { std::fclose(file); std::remove(tmp); path_found = true; }
         }
         if (!path_found)
           throw CImgIOException("cimg::temporary_path() : Unable to find a temporary path accessible for writing\n"
                                 "you have to set the macro 'cimg_temporary_path' to a valid path where you have writing access :\n"
                                 "#define cimg_temporary_path \"path\" (before including 'CImg.h')");
       }
       return st_path;
     }
unsigned long cimg_library::cimg::time () inline
Get the value of a system timer with a millisecond precision.
Definition at line 4605 of file CImg.h.
Referenced by _sleep(), InterpolateBase::extrapolate_Linear(), CImgDisplay::frames_per_second(), main(), Rocin::read_windows(), flowprobe::ReadProbeData(), ComputeMeshMotion::run(), srand(), wait(), and write_hdf().
{
 #if cimg_OS==1
       struct timeval st_time;
       gettimeofday(&st_time,0);
       return (unsigned long)(st_time.tv_usec/1000 + st_time.tv_sec*1000);
 #elif cimg_OS==2
       static SYSTEMTIME st_time;
       GetSystemTime(&st_time);
       return (unsigned long)(st_time.wMilliseconds + 1000*(st_time.wSecond + 60*(st_time.wMinute + 60*st_time.wHour)));
 #else
       return 0;
 #endif
     }
char cimg_library::cimg::uncase (const char x) inline
Remove the 'case' of an ASCII character.
Definition at line 4888 of file CImg.h.
Referenced by CImg< uintT >::_autocrop(), CImg< T >::_cimg_math_parser::_cimg_math_parser(), CImg< uintT >::assign(), CImg< uintT >::autocrop(), CImg< uintT >::deriche(), CImg< uintT >::FFT(), CImgList< uintT >::get_append(), CImg< uintT >::get_gradient(), CImg< uintT >::get_haar(), CImg< uintT >::get_split(), CImg< uintT >::mirror(), strncasecmp(), and uncase().
{
       return (char)((x<'A'||x>'Z')?x:x-'A'+'a');
     }
void cimg_library::cimg::uncase (char *const string) inline
Remove the 'case' of a C string.
Acts in-place.
Definition at line 4896 of file CImg.h.
References uncase().
{
       if (string) for (char *ptr = string; *ptr; ++ptr) *ptr = uncase(*ptr);
     }
unsigned int cimg_library::cimg::wait (const unsigned int milliseconds) inline
Wait for a certain number of milliseconds since the last call.
This function is equivalent to sleep() but the waiting time is computed with regard to the last call of wait(). It may be used to temporize your program properly.
Definition at line 4650 of file CImg.h.
References _sleep(), and time().
{
       static unsigned long timer = 0;
       if (!timer) timer = cimg::time();
       return _sleep(milliseconds,timer);
     }
void cimg_library::cimg::warn (const char * format, ...) inline
Display a warning message.
Parameters
format is a C-string describing the format of the message, as in std::printf().
Definition at line 4470 of file CImg.h.
References cimg_stdout, exception_mode(), t_normal, and t_red.
Referenced by CImg< uintT >::_load_analyze(), CImg< uintT >::_load_ascii(), CImg< uintT >::_load_jpeg(), CImg< uintT >::_load_off(), CImg< uintT >::_load_pnm(), CImgList< uintT >::_load_yuv(), CImg< uintT >::_save_bmp(), CImgList< uintT >::_save_cimg(), CImg< uintT >::_save_dlm(), CImg< uintT >::_save_jpeg(), CImg< uintT >::_save_png(), CImg< uintT >::_save_pnm(), CImg< uintT >::_save_rgb(), CImg< uintT >::_save_rgba(), CImg< uintT >::assign(), CImg< uintT >::eigen(), fclose(), CImgList< uintT >::FFT(), fread(), fwrite(), CImg< uintT >::invert(), CImgList< uintT >::load_ffmpeg(), CImg< uintT >::load_tiff(), CImgList< uintT >::load_tiff(), CImgList< uintT >::operator[](), CImgList< uintT >::remove(), CImg< uintT >::save_magick(), CImg< uintT >::solve(), and CImg< uintT >::symmetric_eigen().
{
       if (cimg::exception_mode()>=1) {
         char message[8192] = { 0 };
         std::va_list ap;
         va_start(ap,format);
         std::vsprintf(message,format,ap);
         va_end(ap);
 #ifdef cimg_strict_warnings
         throw CImgWarningException(message);
 #else
         std::fprintf(cimg_stdout,"\n%s# CImg Warning%s :\n%s\n",cimg::t_red,cimg::t_normal,message);
 #endif
       }
     }
void cimg_library::cimg::winformat_string (char *const s) inline
Definition at line 5007 of file CImg.h.
Referenced by dcraw_path(), ffmpeg_path(), graphicsmagick_path(), gunzip_path(), gzip_path(), imagemagick_path(), medcon_path(), and temporary_path().
{
       if (s && s[0]) {
 #if cimg_OS==2
         char *const ns = new char[MAX_PATH];
         if (GetShortPathNameA(s,ns,MAX_PATH)) std::strcpy(s,ns);
 #endif
       }
     }
int cimg_library::cimg::xln (const int x) inline
Return 1 + log_10(x).
Definition at line 4722 of file CImg.h.
References cimg_library::log10().
{
       return x>0?(int)(1+std::log10((double)x)):1;
     }
Variable Documentation
const unsigned int font10x13[256 *10 *13/32]
Definition at line 2805 of file CImg.h.
Referenced by CImgList< uintT >::font().
const unsigned int font10x19[10 *19 *256/32]
Definition at line 2935 of file CImg.h.
Referenced by CImgList< uintT >::font().
const unsigned int font12x24[12 *24 *256/32]
Definition at line 3030 of file CImg.h.
Referenced by CImgList< uintT >::font().
const unsigned int font16x32[16 *32 *256/32]
Definition at line 3169 of file CImg.h.
Referenced by CImgList< uintT >::font().
const unsigned int font19x38[19 *38 *256/32]
Definition at line 3403 of file CImg.h.
Referenced by CImgList< uintT >::font().
const unsigned int font29x57[29 *57 *256/32]
Definition at line 3729 of file CImg.h.
Referenced by CImgList< uintT >::font().
const unsigned int font7x11[7 *11 *256/32]
Definition at line 2764 of file CImg.h.
Referenced by CImgList< uintT >::font().
const unsigned int font8x17[8 *17 *256/32]
Definition at line 2868 of file CImg.h.
Referenced by CImgList< uintT >::font().
const unsigned int key0 = 24U
Definition at line 2694 of file CImg.h.
const unsigned int key1 = 15U
Definition at line 2685 of file CImg.h.
Referenced by CImgDisplay::is_key().
const unsigned int key2 = 16U
Definition at line 2686 of file CImg.h.
Referenced by CImgDisplay::is_key().
const unsigned int key3 = 17U
Definition at line 2687 of file CImg.h.
Referenced by CImgDisplay::is_key().
const unsigned int key4 = 18U
Definition at line 2688 of file CImg.h.
Referenced by CImgDisplay::is_key().
const unsigned int key5 = 19U
Definition at line 2689 of file CImg.h.
Referenced by CImgDisplay::is_key().
const unsigned int key6 = 20U
Definition at line 2690 of file CImg.h.
Referenced by CImgDisplay::is_key().
const unsigned int key7 = 21U
Definition at line 2691 of file CImg.h.
Referenced by CImgDisplay::is_key().
const unsigned int key8 = 22U
Definition at line 2692 of file CImg.h.
Referenced by CImgDisplay::is_key().
const unsigned int key9 = 23U
Definition at line 2693 of file CImg.h.
const unsigned int keyA = 44U
Definition at line 2714 of file CImg.h.
const unsigned int keyALT = 66U
Definition at line 2736 of file CImg.h.
Referenced by CImg< uintT >::_display().
const unsigned int keyALTGR = 68U
Definition at line 2738 of file CImg.h.
const unsigned int keyAPPLEFT = 65U
Definition at line 2735 of file CImg.h.
const unsigned int keyAPPRIGHT = 69U
Definition at line 2739 of file CImg.h.
const unsigned int keyARROWDOWN = 73U
Definition at line 2743 of file CImg.h.
Referenced by CImg< uintT >::_display(), dialog(), and CImg< uintT >::display_graph().
const unsigned int keyARROWLEFT = 72U
Definition at line 2742 of file CImg.h.
Referenced by CImg< uintT >::_display(), dialog(), and CImg< uintT >::display_graph().
const unsigned int keyARROWRIGHT = 74U
Definition at line 2744 of file CImg.h.
Referenced by CImg< uintT >::_display(), dialog(), and CImg< uintT >::display_graph().
const unsigned int keyARROWUP = 63U
Definition at line 2733 of file CImg.h.
Referenced by CImg< uintT >::_display(), dialog(), and CImg< uintT >::display_graph().
const unsigned int keyB = 59U
Definition at line 2729 of file CImg.h.
const unsigned int keyBACKSPACE = 25U
Definition at line 2695 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyC = 57U
Definition at line 2727 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), and CImg< uintT >::get_select_graph().
const unsigned int keyCAPSLOCK = 43U
Definition at line 2713 of file CImg.h.
const unsigned int keyCTRLLEFT = 64U
Definition at line 2734 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), and CImg< uintT >::get_select_graph().
const unsigned int keyCTRLRIGHT = 71U
Definition at line 2741 of file CImg.h.
const unsigned int keyD = 46U
Definition at line 2716 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), and CImg< uintT >::get_select_graph().
const unsigned int keyDELETE = 40U
Definition at line 2710 of file CImg.h.
const unsigned int keyE = 32U
Definition at line 2702 of file CImg.h.
const unsigned int keyEND = 41U
Definition at line 2711 of file CImg.h.
const unsigned int keyENTER = 53U
Definition at line 2723 of file CImg.h.
Referenced by dialog().
const unsigned int keyESC = 1U
Definition at line 2671 of file CImg.h.
Referenced by dialog().
const unsigned int keyF = 47U
Definition at line 2717 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), and CImg< uintT >::get_select_graph().
const unsigned int keyF1 = 2U
Definition at line 2672 of file CImg.h.
const unsigned int keyF10 = 11U
Definition at line 2681 of file CImg.h.
const unsigned int keyF11 = 12U
Definition at line 2682 of file CImg.h.
const unsigned int keyF12 = 13U
Definition at line 2683 of file CImg.h.
const unsigned int keyF2 = 3U
Definition at line 2673 of file CImg.h.
const unsigned int keyF3 = 4U
Definition at line 2674 of file CImg.h.
const unsigned int keyF4 = 5U
Definition at line 2675 of file CImg.h.
const unsigned int keyF5 = 6U
Definition at line 2676 of file CImg.h.
const unsigned int keyF6 = 7U
Definition at line 2677 of file CImg.h.
const unsigned int keyF7 = 8U
Definition at line 2678 of file CImg.h.
const unsigned int keyF8 = 9U
Definition at line 2679 of file CImg.h.
const unsigned int keyF9 = 10U
Definition at line 2680 of file CImg.h.
const unsigned int keyG = 48U
Definition at line 2718 of file CImg.h.
const unsigned int keyH = 49U
Definition at line 2719 of file CImg.h.
const unsigned int keyHOME = 27U
Definition at line 2697 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyI = 37U
Definition at line 2707 of file CImg.h.
const unsigned int keyINSERT = 26U
Definition at line 2696 of file CImg.h.
const unsigned int keyJ = 50U
Definition at line 2720 of file CImg.h.
const unsigned int keyK = 51U
Definition at line 2721 of file CImg.h.
const unsigned int keyL = 52U
Definition at line 2722 of file CImg.h.
const unsigned int keyM = 61U
Definition at line 2731 of file CImg.h.
const unsigned int keyMENU = 70U
Definition at line 2740 of file CImg.h.
const unsigned int keyN = 60U
Definition at line 2730 of file CImg.h.
const unsigned int keyO = 38U
Definition at line 2708 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d(), and CImg< uintT >::_get_select().
const unsigned int keyP = 39U
Definition at line 2709 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::_display_object3d().
const unsigned int keyPAD0 = 75U
Definition at line 2745 of file CImg.h.
const unsigned int keyPAD1 = 76U
Definition at line 2746 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPAD2 = 77U
Definition at line 2747 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPAD3 = 78U
Definition at line 2748 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPAD4 = 79U
Definition at line 2749 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPAD5 = 80U
Definition at line 2750 of file CImg.h.
Referenced by CImg< uintT >::_display().
const unsigned int keyPAD6 = 81U
Definition at line 2751 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPAD7 = 82U
Definition at line 2752 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPAD8 = 83U
Definition at line 2753 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPAD9 = 84U
Definition at line 2754 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPADADD = 85U
Definition at line 2755 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPADDIV = 88U
Definition at line 2758 of file CImg.h.
const unsigned int keyPADMUL = 87U
Definition at line 2757 of file CImg.h.
const unsigned int keyPADSUB = 86U
Definition at line 2756 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::display_graph().
const unsigned int keyPAGEDOWN = 42U
Definition at line 2712 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::_get_select().
const unsigned int keyPAGEUP = 28U
Definition at line 2698 of file CImg.h.
Referenced by CImg< uintT >::_display(), and CImg< uintT >::_get_select().
const unsigned int keyPAUSE = 14U
Definition at line 2684 of file CImg.h.
const unsigned int keyQ = 30U
Definition at line 2700 of file CImg.h.
const unsigned int keyR = 33U
Definition at line 2703 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), and CImg< uintT >::get_select_graph().
const unsigned int keyS = 45U
Definition at line 2715 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), and CImg< uintT >::get_select_graph().
const unsigned int keySHIFTLEFT = 54U
Definition at line 2724 of file CImg.h.
Referenced by CImg< uintT >::_display().
const unsigned int keySHIFTRIGHT = 62U
Definition at line 2732 of file CImg.h.
const unsigned int keySPACE = 67U
Definition at line 2737 of file CImg.h.
const unsigned int keyT = 34U
Definition at line 2704 of file CImg.h.
const unsigned int keyTAB = 29U
Definition at line 2699 of file CImg.h.
Referenced by dialog().
const unsigned int keyU = 36U
Definition at line 2706 of file CImg.h.
const unsigned int keyV = 58U
Definition at line 2728 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d().
const unsigned int keyW = 31U
Definition at line 2701 of file CImg.h.
const unsigned int keyX = 56U
Definition at line 2726 of file CImg.h.
const unsigned int keyY = 35U
Definition at line 2705 of file CImg.h.
const unsigned int keyZ = 55U
Definition at line 2725 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d().
const unsigned char logo40x38[4576]
Initial value:
= {
      177,200,200,200,3,123,123,0,36,200,200,200,1,123,123,0,2,255,255,0,1,189,189,189,1,0,0,0,34,200,200,200,
      1,123,123,0,4,255,255,0,1,189,189,189,1,0,0,0,1,123,123,123,32,200,200,200,1,123,123,0,5,255,255,0,1,0,0,
      0,2,123,123,123,30,200,200,200,1,123,123,0,6,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,29,200,200,200,
      1,123,123,0,7,255,255,0,1,0,0,0,2,123,123,123,28,200,200,200,1,123,123,0,8,255,255,0,1,189,189,189,1,0,0,0,
      2,123,123,123,27,200,200,200,1,123,123,0,9,255,255,0,1,0,0,0,2,123,123,123,26,200,200,200,1,123,123,0,10,255,
      255,0,1,189,189,189,1,0,0,0,2,123,123,123,25,200,200,200,1,123,123,0,3,255,255,0,1,189,189,189,3,0,0,0,1,189,
      189,189,3,255,255,0,1,0,0,0,2,123,123,123,24,200,200,200,1,123,123,0,4,255,255,0,5,0,0,0,3,255,255,0,1,189,
      189,189,1,0,0,0,2,123,123,123,23,200,200,200,1,123,123,0,4,255,255,0,5,0,0,0,4,255,255,0,1,0,0,0,2,123,123,123,
      22,200,200,200,1,123,123,0,5,255,255,0,5,0,0,0,4,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,21,200,200,200,
      1,123,123,0,5,255,255,0,5,0,0,0,5,255,255,0,1,0,0,0,2,123,123,123,20,200,200,200,1,123,123,0,6,255,255,0,5,0,0,
      0,5,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,19,200,200,200,1,123,123,0,6,255,255,0,1,123,123,0,3,0,0,0,1,
      123,123,0,6,255,255,0,1,0,0,0,2,123,123,123,18,200,200,200,1,123,123,0,7,255,255,0,1,189,189,189,3,0,0,0,1,189,
      189,189,6,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,17,200,200,200,1,123,123,0,8,255,255,0,3,0,0,0,8,255,255,
      0,1,0,0,0,2,123,123,123,16,200,200,200,1,123,123,0,9,255,255,0,1,123,123,0,1,0,0,0,1,123,123,0,8,255,255,0,1,189,
      189,189,1,0,0,0,2,123,123,123,15,200,200,200,1,123,123,0,9,255,255,0,1,189,189,189,1,0,0,0,1,189,189,189,9,255,255,
      0,1,0,0,0,2,123,123,123,14,200,200,200,1,123,123,0,11,255,255,0,1,0,0,0,10,255,255,0,1,189,189,189,1,0,0,0,2,123,
      123,123,13,200,200,200,1,123,123,0,23,255,255,0,1,0,0,0,2,123,123,123,12,200,200,200,1,123,123,0,11,255,255,0,1,189,
      189,189,2,0,0,0,1,189,189,189,9,255,255,0,1,189,189,189,1,0,0,0,2,123,123,123,11,200,200,200,1,123,123,0,11,255,255,
      0,4,0,0,0,10,255,255,0,1,0,0,0,2,123,123,123,10,200,200,200,1,123,123,0,12,255,255,0,4,0,0,0,10,255,255,0,1,189,189,
      189,1,0,0,0,2,123,123,123,9,200,200,200,1,123,123,0,12,255,255,0,1,189,189,189,2,0,0,0,1,189,189,189,11,255,255,0,1,
      0,0,0,2,123,123,123,9,200,200,200,1,123,123,0,27,255,255,0,1,0,0,0,3,123,123,123,8,200,200,200,1,123,123,0,26,255,
      255,0,1,189,189,189,1,0,0,0,3,123,123,123,9,200,200,200,1,123,123,0,24,255,255,0,1,189,189,189,1,0,0,0,4,123,123,
      123,10,200,200,200,1,123,123,0,24,0,0,0,5,123,123,123,12,200,200,200,27,123,123,123,14,200,200,200,25,123,123,123,86,
      200,200,200,91,49,124,118,124,71,32,124,95,49,56,114,52,82,121,0}
Definition at line 4440 of file CImg.h.
Referenced by CImg< uintT >::logo40x38().
const char* const * const t_bold = cimg::t_normal
Definition at line 1924 of file CImg.h.
Referenced by info(), and option().
const char* const * const * const * const t_green = cimg::t_normal
Definition at line 1925 of file CImg.h.
Referenced by info(), and option().
const char t_normal[] = { 0 }
Definition at line 1923 of file CImg.h.
Referenced by info(), option(), and warn().
const char* const * const * const t_purple = cimg::t_normal
Definition at line 1925 of file CImg.h.
const char* const t_red = cimg::t_normal
Definition at line 1924 of file CImg.h.
Referenced by info(), option(), and warn().
const double valuePI = 3.14159265358979323846
Definition of the mathematical constant PI.
Definition at line 2761 of file CImg.h.
Referenced by CImg< T >::_cimg_math_parser::_cimg_math_parser(), CImg< uintT >::_draw_ellipse(), CImg< uintT >::blur_anisotropic(), CImg< uintT >::cone3d(), CImg< uintT >::cylinder3d(), CImg< uintT >::draw_arrow(), CImg< uintT >::FFT(), CImg< uintT >::get_rotate(), CImg< uintT >::HSItoRGB(), CImg< uintT >::RGBtoHSI(), and CImg< uintT >::torus3d().