Rocstar: IRAD::Profiler Namespace Reference
IRAD::Profiler Namespace Reference
IllinoisRocstar Application Development
Performance profiling.
Classes
struct cumulative_stats
Utility struct.
struct parallel_stats
Utility struct.
struct scalability_stats
Utility struct.
class Event
Marks construct entry/exit.
class DummyProfilerObj
noop profiler
class ProfilerObj
Performance profiling object.
class ProfaneComLine
ComLineObject for profane.
Typedefs
typedef std::map< std::string,
unsigned int > FunctionMap
construct name to unique id.
typedef std::map< unsigned int,
std::string > ConfigMap
construct name to unique id.
typedef std::map< unsigned int,
cumulative_stats > StatMap
typedef std::list< std::pair
< unsigned int, StatMap > > PStatList
typedef std::map< unsigned int,
parallel_stats > PStatMap
typedef std::map< unsigned int,
PStatMap > ScalaMap
typedef std::list< std::pair
< unsigned int, std::list
< Event > > > PEventList
typedef std::map< unsigned int,
scalability_stats > ScalaStatMap
Enumerations
enum {
IMIN_T =0, IMAX_T, IMEAN_T, IMIN_E,
IMAX_E, IMEAN_E, IMIN_S, IMAX_S,
IMEAN_S, EMIN_T, EMAX_T, EMEAN_T,
EMIN_E, EMAX_E, EMEAN_E, EMIN_S,
EMAX_S, EMEAN_S
}
Functions
std::ostream & operator<< (std::ostream &ost, const Event &e)
EVENT's stream operator.
std::istream & operator>> (std::istream &ist, Event &e)
EVENT's stream operator.
double Time ()
Simple timer.
int Profane (int argc, char *argv[])
The performance analysis post processor.
struct timeval operator- (const struct timeval &t1, const struct timeval &t2)
faster timeval math
struct timeval & operator-= (struct timeval &t1, const struct timeval &t2)
faster timeval math
struct timeval operator+ (const struct timeval &t1, const struct timeval &t2)
faster timeval math
struct timeval & operator+= (struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator== (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator!= (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator< (const timeval &t1, const timeval &t2)
faster timeval math
bool operator> (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator<= (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator>= (const struct timeval &t1, const struct timeval &t2)
faster timeval math
bool operator< (const std::pair< unsigned int, std::list< Event > > &p1, const std::pair< unsigned int, std::list< Event > > &p2)
Event math.
Detailed Description
Performance profiling.
Typedef Documentation
typedef std::map<unsigned int,std::string> ConfigMap
construct name to unique id.
Definition at line 274 of file Profiler.H.
typedef std::map< std::string, unsigned int > FunctionMap
construct name to unique id.
Definition at line 270 of file Profiler.H.
typedef std::list< std::pair< unsigned int, std::list< Event > > > PEventList
Definition at line 279 of file Profiler.H.
typedef std::list< std::pair< unsigned int, StatMap > > PStatList
Definition at line 276 of file Profiler.H.
typedef std::map< unsigned int, parallel_stats > PStatMap
Definition at line 277 of file Profiler.H.
typedef std::map< unsigned int, PStatMap > ScalaMap
Definition at line 278 of file Profiler.H.
typedef std::map< unsigned int, scalability_stats > ScalaStatMap
Definition at line 281 of file Profiler.H.
typedef std::map< unsigned int, cumulative_stats > StatMap
Definition at line 275 of file Profiler.H.
Enumeration Type Documentation
anonymous enum
Enumerator
IMIN_T
IMAX_T
IMEAN_T
IMIN_E
IMAX_E
IMEAN_E
IMIN_S
IMAX_S
IMEAN_S
EMIN_T
EMAX_T
EMEAN_T
EMIN_E
EMAX_E
EMEAN_E
EMIN_S
EMAX_S
EMEAN_S
Definition at line 857 of file Profiler.C.
          {IMIN_T=0,IMAX_T,IMEAN_T,IMIN_E,IMAX_E,IMEAN_E,
           IMIN_S,IMAX_S,IMEAN_S,EMIN_T,EMAX_T,EMEAN_T,
           EMIN_E,EMAX_E,EMEAN_E,EMIN_S,EMAX_S,EMEAN_S};
Function Documentation
bool IRAD::Profiler::operator!= (const struct timeval & t1, const struct timeval & t2) inline
faster timeval math
Definition at line 75 of file Profiler.C.
     {
       return(!(t1==t2));
     }
struct timeval IRAD::Profiler::operator+ (const struct timeval & t1, const struct timeval & t2)
faster timeval math
Definition at line 42 of file Profiler.C.
     {
       struct timeval rtv;
       rtv.tv_usec = t1.tv_usec + t2.tv_usec;
       rtv.tv_sec = t1.tv_sec + t2.tv_sec;
       return(rtv);
     }
struct timeval& IRAD::Profiler::operator+= (struct timeval & t1, const struct timeval & t2)
faster timeval math
Definition at line 54 of file Profiler.C.
     {
       t1.tv_usec += t2.tv_usec;
       t1.tv_sec  += t2.tv_sec;
       return(t1);
     }
struct timeval IRAD::Profiler::operator- (const struct timeval & t1, const struct timeval & t2)
faster timeval math
Definition at line 19 of file Profiler.C.
Referenced by Direction_3< R, T >::operator-(), Vector_3< Real >::operator-(), Direction_2< R, T >::operator-(), and Vector_2< T >::operator-().
     {
       struct timeval rtv;
       rtv.tv_usec = t1.tv_usec - t2.tv_usec;
       rtv.tv_sec  = t1.tv_sec - t2.tv_sec;
       return(rtv);
     }
struct timeval& IRAD::Profiler::operator-= (struct timeval & t1, const struct timeval & t2)
faster timeval math
Definition at line 31 of file Profiler.C.
     {
       t1.tv_usec -= t2.tv_usec;
       t1.tv_sec -= t2.tv_sec;
       return(t1);
     }
bool IRAD::Profiler::operator< (const timeval & t1, const timeval & t2) inline
faster timeval math
Definition at line 84 of file Profiler.C.
Referenced by Direction_2< R, T >::operator<().
     {
       return((t1.tv_sec + (t1.tv_usec/1000000.0)) <
              (t2.tv_sec + (t2.tv_usec/1000000.0)));
     }
bool IRAD::Profiler::operator< (const std::pair< unsigned int, std::list< Event > > & p1, const std::pair< unsigned int, std::list< Event > > & p2)
Event math.
Definition at line 123 of file Profiler.C.
References p1.
     {
       return (p1.first < p2.first);
     };
std::ostream & operator<< (std::ostream & ost, const Event & e)
EVENT's stream operator.
Output function for Event.
Definition at line 131 of file Profiler.C.
References Event::_exclusive, Event::_id, Event::_inclusive, and Event::_timestamp.
     {
       ost << e._id << " " << e._timestamp << " "
           << e._inclusive << " " << e._exclusive;
       return(ost);
     }
bool IRAD::Profiler::operator<= (const struct timeval & t1, const struct timeval & t2) inline
faster timeval math
Definition at line 104 of file Profiler.C.
Referenced by Direction_2< R, T >::operator<=().
     {
       return((t1 < t2) || (t1 == t2));
     }
bool IRAD::Profiler::operator== (const struct timeval & t1, const struct timeval & t2) inline
faster timeval math
Definition at line 65 of file Profiler.C.
Referenced by Ray_3< R, T >::operator==(), Segment_3< R, T >::operator==(), Direction_3< R, T >::operator==(), Vector_2< T >::operator==(), Vector_3< Real >::operator==(), Point_3< Real >::operator==(), Direction_2< R, T >::operator==(), Line_3< R, T >::operator==(), Point_2< R >::operator==(), Ray_2< R, T >::operator==(), Segment_2< R >::operator==(), Plane_3< R, T >::operator==(), and Line_2< R >::operator==().
     {
       return((t1.tv_sec + (t1.tv_usec/1000000.0)) ==
              (t2.tv_sec + (t2.tv_usec/1000000.0)));
     }
bool IRAD::Profiler::operator> (const struct timeval & t1, const struct timeval & t2) inline
faster timeval math
Definition at line 94 of file Profiler.C.
Referenced by Direction_2< R, T >::operator>().
     {
       return((t1.tv_sec + (t1.tv_usec/1000000.0)) >
              (t2.tv_sec + (t2.tv_usec/1000000.0)));
     }
bool IRAD::Profiler::operator>= (const struct timeval & t1, const struct timeval & t2) inline
faster timeval math
Definition at line 113 of file Profiler.C.
Referenced by Direction_2< R, T >::operator>=().
     {
       return((t1 > t2) || (t1 == t2));
     }
std::istream & operator>> (std::istream & ist, Event & e)
EVENT's stream operator.
Input function for Event.
Definition at line 140 of file Profiler.C.
References Event::_exclusive, Event::_id, Event::_inclusive, and Event::_timestamp.
     {
       ist >> e._id >> e._timestamp >> e._inclusive >> e._exclusive;
       return(ist);
     }
double IRAD::Profiler::Time () inline
Simple timer.
Time returns the time in seconds from the system time. The user is responsible for adding the appropriate offset to make this number relative to the current execution.
Definition at line 259 of file Profiler.H.
Referenced by ProfilerObj::Finalize(), ProfilerObj::FunctionEntry(), ProfilerObj::FunctionExit(), and ProfilerObj::Init().
     {
       struct timeval tv;
       gettimeofday(&tv,NULL);
       double t = tv.tv_sec + tv.tv_usec/1000000.;
       return(t);
     }