Rocstar: GridConversion::DriverProgram Namespace Reference
GridConversion::DriverProgram Namespace Reference
Encapsulate GridConversion-specific code constructs.
Classes
class DriverProgramComLine
The ComLineObject for the example programs.
class SerialProgram
Implementation of the basic parts of the serial program example.
Typedefs
typedef IRAD::Profiler::ProfilerObj ProfilerType
Convenience type definition for Profiler object.
typedef std::string StackType
Convenience type definition for program stack.
typedef
IRAD::Global::GlobalObj
< StackType, int, ProfilerType > GlobalType
Convenience type definition for the serial global object.
typedef DriverProgramComLine ComLineType
Convenience type definition for the Main comline object.
typedef IRAD::Global::Program
< GlobalType, ComLineType > SerialProgramType
Convenience type definition for the serial program.
typedef
GridConversion::DriverProgram::SerialProgram SEProgramType
Convenience definition for serial program type.
Functions
template<typename ProgramType >
int Driver (int argc, char *argv[])
Unified driver for the example programs.
Detailed Description
Encapsulate GridConversion-specific code constructs.
Based off the example program from IRProject For Example Program: This namespace contains all of the base code constructs that are used in the example programs. These example programs have several features which make them very easy to integrate in composite software systems.
Program is entirely encapsulated in program object
All screen output is automatically tagged with the program name
Common look-and-feel interface
Interface functionality allows menu-driven integration
Other convenient features of this API are:
Built-in stack tracing for debugging
Built-in profiling utilities
Advanced command-line handling
Built-in parallelism
Typedef Documentation
typedef DriverProgramComLine ComLineType
Convenience type definition for the Main comline object.
Definition at line 118 of file DriverProgram.H.
typedef IRAD::Global::GlobalObj<StackType,int,ProfilerType> GlobalType
Convenience type definition for the serial global object.
The global object encapsulates all of the built-in functionalities for a program. Its interface and implementation are defined in IRAD/include/Global.H
Definition at line 56 of file DriverProgram.H.
typedef IRAD::Profiler::ProfilerObj ProfilerType
Convenience type definition for Profiler object.
Definition at line 44 of file DriverProgram.H.
typedef GridConversion::DriverProgram::SerialProgram SEProgramType
Convenience definition for serial program type.
Definition at line 551 of file DriverProgram.H.
typedef IRAD::Global::Program<GlobalType,ComLineType> SerialProgramType
Convenience type definition for the serial program.
For a detailed description of the program type, see IRAD::Global::Program documentation.
Definition at line 125 of file DriverProgram.H.
typedef std::string StackType
Convenience type definition for program stack.
Definition at line 48 of file DriverProgram.H.
Function Documentation
int GridConversion::DriverProgram::Driver (int argc, char * argv[])
Unified driver for the example programs.
This driver is exactly the same for both the serial and parallel example programs. It is a direct replacement for main and is responsible for creating the "Program object" and calling its Initialization, Run, and Finalize methods.
Definition at line 515 of file DriverProgram.H.
References SerialProgram::Initialize(), SerialProgram::Run(), and SerialProgram::VerbLevel().
     {
       ProgramType MyProgram(argc,argv);
       int retval = MyProgram.Initialize();
       if(retval){
         if(retval > 0){ // then there was an error
           MyProgram.ErrOut("Error in Program Initialization.\n");
           return(1);
         }
         else return(0); // no error, but the program should not continue
       }
       if(MyProgram.VerbLevel() > 1)
         MyProgram.StdOut("Calling RUN.\n");
       if(MyProgram.Run()){
         MyProgram.ErrOut("Error in Program RUN method.\n");
         return(1);
       }
       if(MyProgram.VerbLevel() > 1){
         std::ostringstream Ostr;
         MyProgram.Report(Ostr);
         MyProgram.StdOut(Ostr.str());
         MyProgram.StdOut("Calling Finalize.\n");
       }
       if(MyProgram.Finalize()){
         MyProgram.ErrOut("Error in Program Finalization.\n");
         return(1);
       }
       if(MyProgram.VerbLevel() > 1)
         MyProgram.StdOut("All done.\n");
       return(0);
     }