Rocstar: Mesquite Namespace Reference
Mesquite Namespace Reference
Used to hold the error state and return it to the application.
Classes
struct ActiveSet
class AddQualityMetric
Combines two quality metrics (qMetric1 and qMetric2 defined in the parent class CompositeQualityMetric) by addition for two- and three-diminsional elements. Note: This function should not be used to combine a node-based metric with an element-based metric.
class ASMQualityMetric
Computes the ASM (Area Smoothness Metric) of the given element.
class AspectRatioGammaQualityMetric
Object for computing the aspect ratio gamma of simplicial elements.
class CompositeOFAdd
Adds two ObjectiveFunction values together.
class CompositeOFMultiply
Multiplies two ObjectiveFunction values together.
class CompositeOFScalarAdd
Adds a scalar to a given ObjectiveFunction.
class CompositeOFScalarMultiply
Scales a given an ObjectiveFunction.
class ConditionNumberQualityMetric
Computes the condition number of given element.
class ConjugateGradient
Optimizes the objective function using the Polack-Ribiere scheme.
class CornerJacobianQualityMetric
Computes the volume or area of the element, as appropriate. This metric uses the average of the corner Jacobian determinants for the approximation to the volume of hex.
class CornerTag
A class for caching and managing Tags on element corners.
class CornerTagHandles
Utility class to manage tag handles for corner tags.
class DeformingDomainGuides841
Deforming Domain Mesh Tracking. Use with I-DFT or R-DFT.
class DeformingDomainGuides843
Deforming Domain with Angle Improvement. Use with I-DFT or R-DFT.
class DeformingDomainGuides844
Deforming Domain with Angle Improvement, non-Unit AR. Use with R-DFT.
class DistanceFromTarget
Base class for the computation of the distance from target between the target matrices W and the actual corner matrices A.
class DomainTSTT
class EdgeLengthQualityMetric
Computes the lengths of the edges connected to given a vertex..
class EdgeLengthRangeQualityMetric
Computes the edge length range metric for a given vertex.
class EntityIterator
Iterates through a set of entities. An EntityIterator is typically obtained via Mesh::vertex_iterator() or Mesh::element_iterator(). An iterator obtained in this way iterates over the set of all vertices/elements in the Mesh from which the iterator was obtained.
class Exponent
class FeasibleNewton
High Performance implementation of the Feasible Newton algorythm.
class FileTokenizer
Parse a file as space-separated tokens.
class FunctionTimer
class GeneralizedConditionNumberQualityMetric
Computes the condition number of given element. The``condition number" is scaled between one and infinity, with an ideal element having condition number one.
class GeomEntTSTT
class GeomTSTT
A base class describing a Mesquite::MeshDomain implemented on top of the TSTT geometry and classification interfaces.
class GeomTSTTCommon
Common code for specific implementations of MeshDomain on TSTT interfaces.
class I_DFT
Class containing the target corner matrices for the context based smoothing.
class I_DFT_Generalized
I_DFT metric where mAlpha, mBeta, mGamma, and UseBarrierDelta can be set be the user. Defaults are mAlpha = .5, mBeta = 1, mGamma = 2/3.
class I_DFT_InverseMeanRatio
I_DFT metric with mAlpha = 1/3, mBeta = 0.0, mGamma = 2/3.
class I_DFT_NoBarrier
I_DFT metric with mAlpha = .5, mBeta = 1, mGamma = 0.
class I_DFT_StrongBarrier
I_DFT metric with mAlpha = .5, mBeta = 1, mGamma = 2/3.
class I_DFT_WeakBarrier
I_DFT metric with mAlpha = .5, mBeta = 1, mGamma = 2/3.
class IdealWeightInverseMeanRatio
Computes the inverse mean ratio of given element.
class IdealWeightMeanRatio
Computes the mean ratio quality metric of given element.
class InstructionQueue
An InstructionQueue object gathers Mesquite Instructions and ensures that the instruction queue is coherent for mesh improvement and/or mesh quality assessment purposes.
class LaplacianIQ
class LaplacianSmoother
class LInfTemplate
Computes the L_infinity objective function for a given patch, i.e., LInfTemplate::concrete_evaluate returns the maximum absolute value of the quality metric values on 'patch'.
class LocalSizeQualityMetric
Computes the local size metric for a given vertex.
class LPtoPTemplate
Calculates the L_p objective function raised to the pth power. That is, sums the p_th powers of (the absolute value of) the quality metric values.
class LVQDTargetCalculator
This is an intermediary class. Concrete classes will simply instantiate the various guide enums in their constructor.
class Matrix3D
3*3 Matric class, row-oriented, 0-based [i][j] indexing.
class MaxTemplate
Computes the maximum quality metric value.
class MeanMidNodeMover
Class to adjust positions of higher-order nodes.
class Mesh
A Mesquite::Mesh is a collection of mesh elements which are composed of mesh vertices. Intermediate objects are not accessible through this interface (where intermediate objects include things like the faces of a hex, or an element's edges).
class MeshDomain
class MeshImpl
MeshImpl is a Mesquite implementation of the Mesh interface. Applications can also provide their own implementation of the interface.
class MeshImplData
Class to store mesh representation for MeshImpl.
class MeshImplElemIter
ElementIterator for MeshImpl.
class MeshImplTags
Store tags and tag data for Mesquite's native mesh representation.
class MeshImplVertIter
VertexIterator for MeshImpl.
class MeshSet
The MeshSet class stores one or more Mesquite::Mesh pointers and manages access to the mesh information.
class MeshTransform
class MeshTSTT
The name of the tag (integer) used internally by MeshTSTT to eliminate duplicate vertices.
class MeshTSTTImpl
Implementation of MeshTSTT.
class MsqDebug
Run-time activation/deactivation of debug flags.
class MsqError
Used to hold the error state and return it to the application.
class MsqFPE
Utility class used by InstructionQueue SIGFPE option.
class MsqFreeVertexIndexIterator
iterates over indexes of free vetices in a PatchData.
class MsqHessian
Vector3D is the object that effeciently stores the objective function Hessian each entry is a Matrix3D object (i.e. a vertex Hessian).
class MsqInterrupt
Class to watch for user-interrupt (SIGINT, ctrl-C)
class MsqMeshEntity
MsqMeshEntity is the Mesquite object that stores information about the elements in the mesh.
class MsqPrintError
Utility class for printing error data - used in Mesquite tests.
class MsqVertex
MsqVertex is the Mesquite object that stores information about the vertices in the mesh.
class MultiplyQualityMetric
Combines two quality metrics (qMetric1 and qMetric2 defined in the parent class CompositeQualityMetric) by multiplication for two- and three-diminsional elements. Note: This function should not be used to combine a node-based metric with an element-based metric.
class NonSmoothSteepestDescent
class NullImprover
class ObjectiveFunction
Base class for concrete Objective Functions ObjectiveFunction contains a pointer to a QualityMetric. If the ObjectiveFunction is associated with more than one QualityMetric (i.e., the Objective is a composite, and the composed ObjectiveFunctions are associated with different QualityMetrics), then the QualityMetric pointer is set to NULL..
class ParameterSet
class PatchData
class PatchDataMem
class PatchDataParameters
class PatchDataUser
This should be the parent class of all algorithms retrieving information from a MeshSet object.
class PatchDataVerticesMemento
Contains a copy of the coordinates of a PatchData.
class PlanarDomain
class PowerQualityMetric
Raises a single quality metrics (qMetric1) to an arbitrary power (a double value, scaleAlpha) for two- and three-diminsional elements.
class QualityAssessor
A QualityAssessor instance can be inserted into an InstructionQueue to calculate and summarize registered QualityMetrics for the mesh.
class QualityImprover
Base class for all quality improvers. Mote that the PatchData settings are inherited from the PathDataUser class.
class QualityMetric
Base class for concrete quality metrics.
class Randomize
Randomly perftubs the (un-culled) vertices.
class RezoneGuides832
Rezone with Angle Improvement. Use with I-DFT.
class RI_DFT
Class containing the target corner matrices for the context based smoothing.
class ScalarAddQualityMetric
Adds a number (a double) to the quality metric value.
class ScalarMultiplyQualityMetric
Multiplies quality metric value by a number (a double).
class ShapeGuides811
Shape Improvement with Unit Aspect Ratio. Use with sR-DFT.
class ShapeGuides812
Shape Improvement with non-Unit Aspect Ratio. Use with sR-DFT.
class ShapeImprovementWrapper
Wrapper which performs a Feasible Newton solve using an objective function template with inverse mean ratio.
class ShapeQualityMetric
class ShapeSizeGuides821
Shape and Size Improvement with Unit Aspect Ratio and Equidistributed Size. Use with R-DFT.
class ShapeSizeGuides822
Shape and Size Improvement with Unit Aspect Ratio and Preserved Size. Use with R-DFT.
class ShapeSizeGuides823
Shape and Size Improvement with non-Unit Aspect Ratio and Equidistributed Size. Use with R-DFT.
class ShapeSizeGuides824
Shape and Size Improvement with non-Unit Aspect Ratio and Preserved Size. Use with R-DFT.
class sI_DFT
Class containing the target corner matrices for the context based smoothing.
class SIDLIterator
Iterate over a sidl array of TSTT entity handles.
class SmartLaplacianSmoother
class SmoothnessQualityMetric
class SphericalDomain
class sRI_DFT
Class containing the target corner matrices for the context based smoothing.
class SteepestDescent
class StopWatch
class StopWatchCollection
struct TagDescription
class TargetCalculator
Base class that provides the interface for computing the target corner matrices used in the context based smoothing.
class TargetMatrix
Class containing the target corner matrices for the context based smoothing.
class TerminationCriterion
The TerminationCriterion class contains functionality to terminate the VertexMover's optimization.
class Timer
class TopologyInfo
Information about different element topologies.
class TopologyModifier
class TSTTArrIter
TSTT iterator using array-iterator interface and buffer of handles.
class TSTTIterator
Wrapper around single-entity TSTT interator.
class UntangleBetaQualityMetric
The untangle beta quality metric.
class UntangleQualityMetric
class Vector3D
Vector3D is the object that effeciently stores information about about three-deminsional vectors. It is also the parent class of MsqVertex.
class VertexConditionNumberQualityMetric
Computes the condition numbers of the corner's of elements connected to the given vertex and then averages those values.
class VertexMover
class VolumeQualityMetric
class WTargetCalculator
This is a concrete class.
Typedefs
typedef EntityIterator VertexIterator
typedef EntityIterator ElementIterator
typedef void * TagHandle
Type used to refer to a tag defintion.
typedef int StatusCode
typedef double real
typedef void(* msq_sig_handler_t)(int)
Enumerations
enum DomainHint { NO_DOMAIN_HINT, PLANAR_DOMAIN, LOCAL_PALANAR, SMOOTH_DOMAIN }
A hint on the characteristics of the domain that Mesquite may use to determine what, if any, scheme to use to cache characteristics of the geometric domain.
enum StatusCodeValues { MSQ_FAILURE = 0, MSQ_SUCCESS }
enum EntityTopology {
POLYGON =7, TRIANGLE =8, QUADRILATERAL =9, POLYHEDRON =10,
TETRAHEDRON =11, HEXAHEDRON =12, PRISM =13, PYRAMID =14,
SEPTAHEDRON =15, MIXED
}
enum ReleaseType { STABLE_RELEASE, BETA, ALPHA }
Functions
size_t vertices_in_topology (EntityTopology)
const char * version_string (bool include_build_number=false)
unsigned int major_version_number ()
unsigned int minor_version_number ()
unsigned int build_number ()
Mesquite::ReleaseType release_type ()
template<class T >
T MSQ_MIN_2 (T a, T b)
template<class T >
T MSQ_MAX_2 (T a, T b)
double cbrt (double d)
double cbrt_sqr (double d)
double pow (double value, const Exponent &exp)
bool m_gdft_2 (double &obj, const Vector3D x[3], const Vector3D &n, const Matrix3D &invR, const Matrix3D &Q, const double alpha=0.5, const Exponent &gamma=1.0, const double delta=0.0, const double beta=0.0)
bool g_gdft_2 (double &obj, Vector3D g_obj[3], const Vector3D x[3], const Vector3D &n, const Matrix3D &invR, const Matrix3D &Q, const double alpha=0.5, const Exponent &gamma=1.0, const double delta=0.0, const double beta=0.0)
bool h_gdft_2 (double &obj, Vector3D g_obj[3], Matrix3D h_obj[6], const Vector3D x[3], const Vector3D &n, const Matrix3D &invR, const Matrix3D &Q, const double alpha=0.5, const Exponent &gamma=1.0, const double delta=0.0, const double beta=0.0)
bool m_gdft_3 (double &obj, const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool g_gdft_3 (double &obj, Vector3D g_obj[4], const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool h_gdft_3 (double &obj, Vector3D g_obj[4], Matrix3D h_obj[10], const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool g_gdft_2_v0 (double &obj, Vector3D &g_obj, const Vector3D x[3], const Vector3D &n, const Matrix3D &invR, const Matrix3D &Q, const double alpha=0.5, const Exponent &gamma=1.0, const double delta=0.0, const double beta=0.0)
bool g_gdft_2_v1 (double &obj, Vector3D &g_obj, const Vector3D x[3], const Vector3D &n, const Matrix3D &invR, const Matrix3D &Q, const double alpha=0.5, const Exponent &gamma=1.0, const double delta=0.0, const double beta=0.0)
bool g_gdft_2_v2 (double &obj, Vector3D &g_obj, const Vector3D x[3], const Vector3D &n, const Matrix3D &invR, const Matrix3D &Q, const double alpha=0.5, const Exponent &gamma=1.0, const double delta=0.0, const double beta=0.0)
bool h_gdft_2_v0 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[3], const Vector3D &n, const Matrix3D &invR, const Matrix3D &Q, const double alpha=0.5, const Exponent &gamma=1.0, const double delta=0.0, const double beta=0.0)
bool h_gdft_2_v1 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[3], const Vector3D &n, const Matrix3D &invR, const Matrix3D &Q, const double alpha=0.5, const Exponent &gamma=1.0, const double delta=0.0, const double beta=0.0)
bool h_gdft_2_v2 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[3], const Vector3D &n, const Matrix3D &invR, const Matrix3D &Q, const double alpha=0.5, const Exponent &gamma=1.0, const double delta=0.0, const double beta=0.0)
bool g_gdft_3_v0 (double &obj, Vector3D &g_obj, const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool g_gdft_3_v1 (double &obj, Vector3D &g_obj, const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool g_gdft_3_v2 (double &obj, Vector3D &g_obj, const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool g_gdft_3_v3 (double &obj, Vector3D &g_obj, const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool h_gdft_3_v0 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool h_gdft_3_v1 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool h_gdft_3_v2 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
bool h_gdft_3_v3 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[4], const Matrix3D &invR, const Matrix3D &Q, const double alpha=1.0/3.0, const Exponent &gamma=2.0/3.0, const double delta=0.0, const double beta=0.0)
void centroid_smooth_mesh (PatchData &pd, size_t num_adj_vtx, msq_std::vector< size_t > adj_vtx_ind, size_t free_ind, size_t dimension, MsqError &err)
msq_stdio::ostream & operator<< (msq_stdio::ostream &s, const Matrix3D &A)
msq_stdio::istream & operator>> (msq_stdio::istream &s, Matrix3D &A)
bool operator== (const Matrix3D &lhs, const Matrix3D &rhs)
bool operator!= (const Matrix3D &lhs, const Matrix3D &rhs)
const Matrix3D operator+ (const Matrix3D &A, const Matrix3D &B)
const Matrix3D operator- (const Matrix3D &A, const Matrix3D &B)
const Matrix3D mult_element (const Matrix3D &A, const Matrix3D &B)
Multiplies entry by entry. This is NOT a matrix multiplication.
double Frobenius_2 (const Matrix3D &A)
Return the square of the Frobenius norm of A, i.e. sum (diag (A' * A))
Matrix3D transpose (const Matrix3D &A)
const Matrix3D operator* (const Matrix3D &A, const Matrix3D &B)
const Matrix3D operator* (const double &s, const Matrix3D &A)
friend function to allow for commutatative property of scalar mulitplication.
int matmult (Matrix3D &C, const Matrix3D &A, const Matrix3D &B)
const Vector3D operator* (const Matrix3D &A, const Vector3D &x)
Computes .
const Vector3D operator* (const Vector3D &x, const Matrix3D &A)
Computes .
void eqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqTransAx (Vector3D &v, const Matrix3D &A, const Vector3D &x)
void plusEqaA (Matrix3D &B, const double a, const Matrix3D &A)
double det (const Matrix3D &A)
void inv (Matrix3D &Ainv, const Matrix3D &A)
void timesInvA (Matrix3D &B, const Matrix3D &A)
void QR (Matrix3D &Q, Matrix3D &R, const Matrix3D &A)
bool m_fcn_2e (double &obj, const Vector3D x[3], const Vector3D &n, const double a, const Exponent &b, const Exponent &c)
bool g_fcn_2e (double &obj, Vector3D g_obj[3], const Vector3D x[3], const Vector3D &n, const double a, const Exponent &b, const Exponent &c)
bool h_fcn_2e (double &obj, Vector3D g_obj[3], Matrix3D h_obj[6], const Vector3D x[3], const Vector3D &n, const double a, const Exponent &b, const Exponent &c)
bool m_fcn_2i (double &obj, const Vector3D x[3], const Vector3D &n, const double a, const Exponent &b, const Exponent &c, const Vector3D &d)
bool g_fcn_2i (double &obj, Vector3D g_obj[3], const Vector3D x[3], const Vector3D &n, const double a, const Exponent &b, const Exponent &c, const Vector3D &d)
bool h_fcn_2i (double &obj, Vector3D g_obj[3], Matrix3D h_obj[6], const Vector3D x[3], const Vector3D &n, const double a, const Exponent &b, const Exponent &c, const Vector3D &d)
bool m_fcn_3e (double &obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool g_fcn_3e (double &obj, Vector3D g_obj[4], const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool h_fcn_3e (double &obj, Vector3D g_obj[4], Matrix3D h_obj[10], const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool g_fcn_3e_v3 (double &obj, Vector3D &g_obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool g_fcn_3e_v0 (double &obj, Vector3D &g_obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool g_fcn_3e_v1 (double &obj, Vector3D &g_obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool g_fcn_3e_v2 (double &obj, Vector3D &g_obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool h_fcn_3e_v3 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool h_fcn_3e_v0 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool h_fcn_3e_v1 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool h_fcn_3e_v2 (double &obj, Vector3D &g_obj, Matrix3D &h_obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c)
bool m_fcn_3i (double &obj, const Vector3D x[4], const double a, const Exponent &b, const Exponent &c, const Vector3D &d)
bool g_fcn_3i (double &obj, Vector3D g_obj[4], const Vector3D x[4], const double a, const Exponent &b, const Exponent &c, const Vector3D &d)
int h_fcn_3i (double &obj, Vector3D g_obj[4], Matrix3D h_obj[10], const Vector3D x[4], const double a, const Exponent &b, const Exponent &c, const Vector3D &d)
void test_aomd (void)
msq_stdio::ostream & operator<< (msq_stdio::ostream &, const MsqError &)
Print message and stack trace.
msq_stdio::ostream & operator<< (msq_stdio::ostream &, const MsqError::Trace &)
Print MsqError::Trace.
void axpy (Vector3D res[], size_t size_r, const MsqHessian &H, const Vector3D x[], size_t size_x, const Vector3D y[], size_t size_y, MsqError &)
msq_stdio::ostream & operator<< (msq_stdio::ostream &s, const MsqHessian &h)
Prints out the MsqHessian blocks.
msq_stdio::ostream & operator<< (msq_stdio::ostream &, StopWatchCollection &coll)
void print_timing_diagnostics (int debugflag)
void print_timing_diagnostics (msq_stdio::ostream &stream)
static msq_std::string process_tstt_error (TSTTB::Error &tstt_err)
template<class T >
static T * convert_from_sidl_vector (sidl::array< T > &array)
template<class T >
static sidl::array< T > alloc_sidl_vector (size_t size)
template<class T >
static sidl::array< T > alloc_sidl_vector (size_t size, T init)
template<class S , class T >
static void copy_from_sidl (sidl::array< S > &source, T *target)
template<class T >
static sidl::array< T > convert_to_sidl_vector (T *array, size_t size)
const Vector3D operator+ (const Vector3D &lhs, const Vector3D &rhs)
const Vector3D operator- (const Vector3D &lhs, const Vector3D &rhs)
const Vector3D operator* (const Vector3D &lhs, const double scalar)
const Vector3D operator* (const double scalar, const Vector3D &rhs)
const Vector3D operator/ (const Vector3D &lhs, const double scalar)
double operator% (const Vector3D &lhs, const Vector3D &rhs)
double inner (const Vector3D lhs[], const Vector3D rhs[], int n)
double operator% (const double scalar, const Vector3D &rhs)
double operator% (const Vector3D &lhs, const double scalar)
const Vector3D operator* (const Vector3D &lhs, const Vector3D &rhs)
msq_stdio::ostream & operator<< (msq_stdio::ostream &s, const Mesquite::Vector3D &v)
double length (Vector3D *const v, int n)
double Linf (Vector3D *const v, int n)
bool operator== (const Vector3D &v1, const Vector3D &v2)
bool operator!= (const Vector3D &v1, const Vector3D &v2)
ostream & operator<< (ostream &stream, const MsqMeshEntity &entity)
ostream & operator<< (ostream &stream, const PatchData &pd)
static msq_std::string process_tstt_error (TSTTB::Error &tstt_err)
template<class T >
static T * convert_from_sidl_vector (sidl::array< T > &array)
template<class T >
static sidl::array< T > alloc_sidl_vector (size_t size)
template<class T >
static sidl::array< T > alloc_sidl_vector (size_t size, T init)
template<class S , class T >
static void copy_from_sidl (sidl::array< S > &source, T *target)
template<class T >
static sidl::array< T > convert_to_sidl_vector (T *array, size_t size)
void msq_sigint_handler (int)
Variables
const int MSQ_MAX_NUM_VERT_PER_ENT =8
const int MSQ_HIST_SIZE =7
static const double MSQ_SQRT_TWO = msq_stdc::sqrt(2.0)
static const double MSQ_SQRT_THREE = msq_stdc::sqrt(3.0)
static const double MSQ_SQRT_THREE_DIV_TWO =MSQ_SQRT_THREE/2.0
static const double MSQ_SQRT_THREE_INV =1.0/MSQ_SQRT_THREE
static const double MSQ_SQRT_TWO_INV =1.0/MSQ_SQRT_TWO
static const double MSQ_SQRT_TWO_DIV_SQRT_THREE =MSQ_SQRT_TWO/MSQ_SQRT_THREE
static const double MSQ_ONE_THIRD = 1.0 / 3.0
static const double MSQ_TWO_THIRDS = 2.0 / 3.0
static const double MSQ_3RT_2_OVER_6RT_3 = msq_stdc::pow(2/MSQ_SQRT_THREE, MSQ_ONE_THIRD)
const unsigned MSQ_UINT_MAX = ~(unsigned)0
const int MSQ_INT_MAX = MSQ_UINT_MAX >> 1
const int MSQ_INT_MIN = ~MSQ_INT_MAX
const double MSQ_DBL_MIN = 1.0E-30
const double MSQ_MIN = MSQ_DBL_MIN
const double MSQ_DBL_MAX = 1.0E30
const double MSQ_MAX = MSQ_DBL_MAX
const double MSQ_MAX_CAP = 1.e6
const char *const VERTEX_BYTE_TAG_NAME = "MesquiteVertexByte"
The name of the tag (integer) that Mesquite will use to store internal data.
const char *const VERTEX_FIXED_TAG_NAME = "MesquiteVertexFixed"
The name of the tag (integer) Mesquite expects to be non-zero for vertices which are not to be moved by Mesquite.
Mesquite::StopWatchCollection GlobalStopWatches
const unsigned long GRAD_FLAGS
const unsigned long OF_FLAGS
const char *const vtk_type_names []
const msq_std::vector< size_t > dummy_list
const Vector3D dummy_vtx
msq_sig_handler_t oldHandler = SIG_ERR
const int DEFAULT_HISTOGRAM_INTERVALS = 10
Detailed Description
Used to hold the error state and return it to the application.
Copyright 2003 Sandia Corporation and the University of Chicago. Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation and Contract W-31-109-ENG-38 with the University of Chicago, the U.S. Government retains certain rights in this software.
Author
Jason Kraftcheck
Date
2004-09-17
Typedef Documentation
typedef EntityIterator ElementIterator
Definition at line 60 of file MeshInterface.hpp.
typedef void(* msq_sig_handler_t)(int)
Definition at line 34 of file Misc/MsqInterrupt.cpp.
typedef double real
Definition at line 84 of file Mesquite.hpp.
typedef int StatusCode
Definition at line 82 of file Mesquite.hpp.
typedef void* TagHandle
Type used to refer to a tag defintion.
Definition at line 63 of file MeshInterface.hpp.
typedef EntityIterator VertexIterator
Definition at line 58 of file MeshInterface.hpp.
Enumeration Type Documentation
enum DomainHint
A hint on the characteristics of the domain that Mesquite may use to determine what, if any, scheme to use to cache characteristics of the geometric domain.
Enumerator
NO_DOMAIN_HINT
PLANAR_DOMAIN
LOCAL_PALANAR
SMOOTH_DOMAIN
Definition at line 446 of file MeshInterface.hpp.
                   {
     NO_DOMAIN_HINT,     //< Do not make any assumptions about the domain.
     PLANAR_DOMAIN,      //< Domain is planar
     LOCAL_PALANAR,      //< Domain is close to planar
     SMOOTH_DOMAIN       //< Domain is C1-continuous
  };
enum EntityTopology
Enumerator
POLYGON
TRIANGLE
QUADRILATERAL
POLYHEDRON
TETRAHEDRON
HEXAHEDRON
PRISM
PYRAMID
SEPTAHEDRON
MIXED
Definition at line 92 of file Mesquite.hpp.
   {
     POLYGON =7,
     TRIANGLE =8,
     QUADRILATERAL =9,
     POLYHEDRON =10,
     TETRAHEDRON =11,
     HEXAHEDRON =12,
     PRISM =13,
     PYRAMID =14,
     SEPTAHEDRON =15,
     MIXED
   };
enum ReleaseType
Enumerator
STABLE_RELEASE
BETA
ALPHA
Definition at line 111 of file Mesquite.hpp.
   {
     STABLE_RELEASE,
     BETA,
     ALPHA
   };
enum StatusCodeValues
Enumerator
MSQ_FAILURE
MSQ_SUCCESS
Definition at line 86 of file Mesquite.hpp.
   {
     MSQ_FAILURE = 0,
     MSQ_SUCCESS
   };
Function Documentation
static sidl::array<T> Mesquite::alloc_sidl_vector (size_t size) inline static
Definition at line 26 of file includeLinks/TSTTUtil.hpp.
Referenced by MeshTSTTImpl::tag_get_data(), and MeshTSTTImpl::tag_set_data().
 {
   int32_t lower = 0;
   int32_t upper = size - 1;
   return sidl::array<T>::createCol( 1, &lower, &upper );
 }
static sidl::array<T> Mesquite::alloc_sidl_vector (size_t size) inline static
Definition at line 26 of file src/Mesh/TSTTUtil.hpp.
 {
   int32_t lower = 0;
   int32_t upper = size - 1;
   return sidl::array<T>::createCol( 1, &lower, &upper );
 }
static sidl::array<T> Mesquite::alloc_sidl_vector (size_t size, T init) inline static
Definition at line 33 of file includeLinks/TSTTUtil.hpp.
References convert_from_sidl_vector().
 {
   sidl::array<T> result = alloc_sidl_vector<T>(size);
   T* ptr = convert_from_sidl_vector( result );
   for ( T* const end = ptr + size; ptr != end; ++ptr)
     *ptr = init;
   return result;
 }
static sidl::array<T> Mesquite::alloc_sidl_vector (size_t size, T init) inline static
Definition at line 33 of file src/Mesh/TSTTUtil.hpp.
References convert_from_sidl_vector().
 {
   sidl::array<T> result = alloc_sidl_vector<T>(size);
   T* ptr = convert_from_sidl_vector( result );
   for ( T* const end = ptr + size; ptr != end; ++ptr)
     *ptr = init;
   return result;
 }
void axpy (Vector3D res[], size_t size_r, const MsqHessian & H, const Vector3D x[], size_t size_x, const Vector3D y[], size_t size_y, MsqError &) inline
Parameters
res array of Vector3D in which the result is stored.
size_r size of the res array.
x vector multiplied by the Hessian.
size_x size of the x array.
y vector added to the Hessian vector product. Set to 0 (NULL) if not needed.
size_y size of the y array. Set to 0 if not needed.
Definition at line 187 of file includeLinks/MsqHessian.hpp.
References eqAx(), i, j, MsqHessian::mColIndex, MsqHessian::mEntries, MsqHessian::mRowStart, MsqHessian::mSize, plusEqAx(), and plusEqTransAx().
     {
       if ((size_r != H.mSize) || (size_x != H.mSize) ||
           (size_y != H.mSize && size_y != 0)) {
         // throw an error
       }
       Vector3D tmpx, tmpm; // for cache opt.
       size_t* col = H.mColIndex;
       const size_t nn = H.mSize;
       size_t rl; // row length
       size_t el; // entries index
       size_t lo;
       size_t c;  // column index
       size_t i, j;
       if (y != 0) {
         for (i = 0; i < nn; ++i) {
           res[i] = y[i];
         }
       }
       else {          // y == 0
         for (i = 0; i < nn; ++i) {
           res[i] = 0.;
         }
       }
       el = 0;
       for (i = 0; i < nn; ++i) {
         rl = H.mRowStart[i+1] - H.mRowStart[i];
         lo = *col++;
         // Diagonal entry
         tmpx = x[i];
         eqAx(tmpm, H.mEntries[el], tmpx);
         ++el;
         //Non-diagonal entries
         for (j = 1; j < rl; ++j) {
           c = *col++;
           //          res[i] += H.mEntries[e] * x[c];
           plusEqAx(tmpm, H.mEntries[el], x[c]);
           //          res[c] += transpose(H.mEntries[e]) * tmpxi;
           plusEqTransAx(res[c], H.mEntries[el], tmpx);
           ++el;
         }
         res[lo] += tmpm;
       }
     }
unsigned int build_number ()
Definition at line 56 of file Misc/MesquiteVersion.cpp.
References MSQ_BUILD_NUMBER.
 {
   return MSQ_BUILD_NUMBER;
 }
double Mesquite::cbrt (double d) inline
Definition at line 182 of file Mesquite.hpp.
References MSQ_ONE_THIRD, and pow().
Referenced by cbrt_sqr(), TargetCalculator::compute_Delta_3D(), TargetCalculator::compute_Lambda(), TargetCalculator::compute_Q_3D(), and Exponent::cubeRoot().
 {
 #ifdef HAVE_CBRT
   return ::cbrt( d );
 #else
   return msq_stdc::pow( d, MSQ_ONE_THIRD );
 #endif
 }
double Mesquite::cbrt_sqr (double d) inline
Definition at line 191 of file Mesquite.hpp.
References cbrt(), MSQ_TWO_THIRDS, and pow().
Referenced by Exponent::powTwoThirds().
 {
 #ifdef HAVE_CBRT
   return ::cbrt(d*d);
 #else
   return msq_stdc::pow( d, MSQ_TWO_THIRDS );
 #endif
 }
void centroid_smooth_mesh (PatchData & pd, size_t num_adj_vtx, msq_std::vector< size_t > adj_vtx_ind, size_t free_ind, size_t dimension, MsqError & err) inline
Definition at line 76 of file includeLinks/LaplacianSmoother.hpp.
References PatchData::get_vertex_array(), MsqError::INVALID_ARG, j, and MSQ_SETERR.
Referenced by SmartLaplacianSmoother::optimize_vertex_positions(), and LaplacianSmoother::optimize_vertex_positions().
   {
     MsqVertex* verts=pd.get_vertex_array(err);
     msq_std::vector<size_t>::iterator iter;
     size_t j;
     double scale_val=1.0;
     if (num_adj_vtx==0) {
       MSQ_SETERR(err)("Number of incident vertices is zero",MsqError::INVALID_ARG);
       return;
     }
     else
       scale_val=1.0/((double) num_adj_vtx);
     double avg[3];
       //loop over the two or three dimensions
     for(j=0;j<dimension;++j) {
         //set the iterator to the beginning ob adj_vtx_ind
       iter=adj_vtx_ind.begin();
       avg[j] = 0.;
       while(iter != adj_vtx_ind.end()){
         avg[j]+=verts[*iter][j];
         ++iter;
       }
         //divide the average by the number of adj. verts
       verts[free_ind][j] = avg[j]*scale_val;
     }
     return;
   }
static T* Mesquite::convert_from_sidl_vector (sidl::array< T > & array) inline static
Definition at line 23 of file includeLinks/TSTTUtil.hpp.
Referenced by alloc_sidl_vector(), MeshTSTTImpl::cache_adjacent_elements(), GeomTSTTCommon::closest_and_normal(), GeomTSTTCommon::move_to(), GeomTSTTCommon::normal(), and MeshTSTTImpl::vertex_get_attached_elements().
 {  return reinterpret_cast<T*>(array._get_ior()->d_firstElement); }
static T* Mesquite::convert_from_sidl_vector (sidl::array< T > & array) inline static
Definition at line 23 of file src/Mesh/TSTTUtil.hpp.
 {  return reinterpret_cast<T*>(array._get_ior()->d_firstElement); }
static sidl::array<T> Mesquite::convert_to_sidl_vector (T * array, size_t size) inline static
Definition at line 51 of file includeLinks/TSTTUtil.hpp.
Referenced by GeomTSTTCommon::closest_and_normal(), MeshTSTTImpl::elements_get_attached_vertices(), MeshTSTTImpl::elements_get_topologies(), MeshTSTTImpl::get_all_mesh(), MeshTSTTImpl::get_vertex_use_count(), GeomTSTTCommon::move_to(), GeomTSTTCommon::normal(), MeshTSTTImpl::popupate_input_elements(), MeshTSTTImpl::tag_get_data(), MeshTSTTImpl::tag_set_data(), MeshTSTTImpl::vertex_set_coordinates(), MeshTSTTImpl::vertices_are_on_boundary(), MeshTSTTImpl::vertices_get_byte(), MeshTSTTImpl::vertices_get_coordinates(), and MeshTSTTImpl::vertices_set_byte().
 {
   sidl::array<T> result;
   int32_t lower = 0, upper = size - 1, stride = 1;
   result.borrow( array, 1, &lower, &upper, &stride );
   return result;
 }
static sidl::array<T> Mesquite::convert_to_sidl_vector (T * array, size_t size) inline static
Definition at line 51 of file src/Mesh/TSTTUtil.hpp.
 {
   sidl::array<T> result;
   int32_t lower = 0, upper = size - 1, stride = 1;
   result.borrow( array, 1, &lower, &upper, &stride );
   return result;
 }
static void Mesquite::copy_from_sidl (sidl::array< S > & source, T * target) inline static
Definition at line 42 of file includeLinks/TSTTUtil.hpp.
References i.
Referenced by MeshTSTTImpl::elements_get_attached_vertices().
 {
   typename sidl::array<S>::iterator i = source.begin();
   for (; i != source.end(); ++i, ++target)
     *target = (T)*i;
 }
static void Mesquite::copy_from_sidl (sidl::array< S > & source, T * target) inline static
Definition at line 42 of file src/Mesh/TSTTUtil.hpp.
References i.
 {
   typename sidl::array<S>::iterator i = source.begin();
   for (; i != source.end(); ++i, ++target)
     *target = (T)*i;
 }
double det (const Matrix3D & A) inline
Definition at line 549 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
Referenced by TargetCalculator::compute_Lambda(), TargetCalculator::compute_Q_3D(), TargetCalculator::compute_target_matrices_and_check_det(), sRI_DFT::evaluate_element(), sI_DFT::evaluate_element(), PatchData::get_barrier_delta(), Overlay_primitives::intersect(), intersect_triangle(), intersect_triangle1(), intersect_triangle2(), intersect_triangle3(), inv(), Aff_transformation_repS2< FT >::inverse(), FaceOffset_3::obtain_constrained_directions(), FaceOffset_3::solve_quadratic_func(), and timesInvA().
{
     return (  A.v_[0]*(A.v_[4]*A.v_[8]-A.v_[7]*A.v_[5])
             -A.v_[1]*(A.v_[3]*A.v_[8]-A.v_[6]*A.v_[5])
             +A.v_[2]*(A.v_[3]*A.v_[7]-A.v_[6]*A.v_[4]) );
   }
void eqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) inline
Definition at line 522 of file includeLinks/Matrix3D.hpp.
References Vector3D::mCoords, and Matrix3D::v_.
Referenced by axpy().
   {
      v.mCoords[0] = A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] = A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] = A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
double Frobenius_2 (const Matrix3D & A) inline
Return the square of the Frobenius norm of A, i.e. sum (diag (A' * A))
Definition at line 326 of file includeLinks/Matrix3D.hpp.
References i.
Referenced by sI_DFT::evaluate_element(), and sRI_DFT::evaluate_element().
   {
     double fro=0.;
     for (int i=0; i<3; ++i) {
         fro += A[0][i]*A[0][i] + A[1][i]*A[1][i] + A[2][i]*A[2][i] ;
     }
     return fro;
   }
bool g_fcn_2e (double & obj, Vector3D g_obj[3], const Vector3D x[3], const Vector3D & n, const double a, const Exponent & b, const Exponent & c) inline
Definition at line 170 of file includeLinks/MeanRatioFunctions.hpp.
References isqrt3, MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), and IdealWeightMeanRatio::compute_element_analytical_gradient().
 {
   double matr[9], f;
   double adj_m[9], g;           // adj_m[2,5,8] not used
   double loc1, loc2, loc3;
   /* Calculate M = [A*inv(W) n] */
   matr[0] = x[1][0] - x[0][0];
   matr[1] = (2.0*x[2][0] - x[1][0] - x[0][0])*isqrt3;
   matr[2] = n[0];
   matr[3] = x[1][1] - x[0][1];
   matr[4] = (2.0*x[2][1] - x[1][1] - x[0][1])*isqrt3;
   matr[5] = n[1];
   matr[6] = x[1][2] - x[0][2];
   matr[7] = (2.0*x[2][2] - x[1][2] - x[0][2])*isqrt3;
   matr[8] = n[2];
   /* Calculate det([n M]). */
   loc1 = matr[4]*matr[8] - matr[5]*matr[7];
   loc2 = matr[2]*matr[7] - matr[1]*matr[8];
   loc3 = matr[1]*matr[5] - matr[2]*matr[4];
   g = matr[0]*loc1 + matr[3]*loc2 + matr[6]*loc3;
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] +
       matr[3]*matr[3] + matr[4]*matr[4] +
       matr[6]*matr[6] + matr[7]*matr[7];
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   adj_m[0] = matr[0]*f + loc1*g;
   adj_m[3] = matr[3]*f + loc2*g;
   adj_m[6] = matr[6]*f + loc3*g;
   loc1 = matr[0]*g;
   loc2 = matr[3]*g;
   loc3 = matr[6]*g;
   adj_m[1] = matr[1]*f + loc3*matr[5] - loc2*matr[8];
   adj_m[4] = matr[4]*f + loc1*matr[8] - loc3*matr[2];
   adj_m[7] = matr[7]*f + loc2*matr[2] - loc1*matr[5];
   loc1 = isqrt3*adj_m[1];
   g_obj[0][0] = -adj_m[0] - loc1;
   g_obj[1][0] =  adj_m[0] - loc1;
   g_obj[2][0] = 2.0*loc1;
   loc1 = isqrt3*adj_m[4];
   g_obj[0][1] = -adj_m[3] - loc1;
   g_obj[1][1] =  adj_m[3] - loc1;
   g_obj[2][1] = 2.0*loc1;
   loc1 = isqrt3*adj_m[7];
   g_obj[0][2] = -adj_m[6] - loc1;
   g_obj[1][2] =  adj_m[6] - loc1;
   g_obj[2][2] = 2.0*loc1;
   return true;
 }
bool g_fcn_2i (double & obj, Vector3D g_obj[3], const Vector3D x[3], const Vector3D & n, const double a, const Exponent & b, const Exponent & c, const Vector3D & d) inline
Definition at line 584 of file includeLinks/MeanRatioFunctions.hpp.
References MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), and IdealWeightMeanRatio::compute_element_analytical_gradient().
 {
   double matr[9], f;
   double adj_m[9], g;            // adj_m[2,5,8] not used
   double loc1, loc2, loc3;
   /* Calculate M = [A*inv(W) n] */
   matr[0] = d[0]*(x[1][0] - x[0][0]);
   matr[1] = d[1]*(x[2][0] - x[0][0]);
   matr[2] = n[0];
   matr[3] = d[0]*(x[1][1] - x[0][1]);
   matr[4] = d[1]*(x[2][1] - x[0][1]);
   matr[5] = n[1];
   matr[6] = d[0]*(x[1][2] - x[0][2]);
   matr[7] = d[1]*(x[2][2] - x[0][2]);
   matr[8] = n[2];
   /* Calculate det([n M]). */
   loc1 = matr[4]*matr[8] - matr[5]*matr[7];
   loc2 = matr[2]*matr[7] - matr[1]*matr[8];
   loc3 = matr[1]*matr[5] - matr[2]*matr[4];
   g = matr[0]*loc1 + matr[3]*loc2 + matr[6]*loc3;
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] +
       matr[3]*matr[3] + matr[4]*matr[4] +
       matr[6]*matr[6] + matr[7]*matr[7];
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   adj_m[0] = d[0]*(matr[0]*f + loc1*g);
   adj_m[3] = d[0]*(matr[3]*f + loc2*g);
   adj_m[6] = d[0]*(matr[6]*f + loc3*g);
   loc1 = matr[0]*g;
   loc2 = matr[3]*g;
   loc3 = matr[6]*g;
   adj_m[1] = d[1]*(matr[1]*f + loc3*matr[5] - loc2*matr[8]);
   adj_m[4] = d[1]*(matr[4]*f + loc1*matr[8] - loc3*matr[2]);
   adj_m[7] = d[1]*(matr[7]*f + loc2*matr[2] - loc1*matr[5]);
   g_obj[0][0] = -adj_m[0] - adj_m[1];
   g_obj[1][0] =  adj_m[0];
   g_obj[2][0] =  adj_m[1];
   g_obj[0][1] = -adj_m[3] - adj_m[4];
   g_obj[1][1] =  adj_m[3];
   g_obj[2][1] =  adj_m[4];
   g_obj[0][2] = -adj_m[6] - adj_m[7];
   g_obj[1][2] =  adj_m[6];
   g_obj[2][2] =  adj_m[7];
   return true;
 }
bool g_fcn_3e (double & obj, Vector3D g_obj[4], const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 973 of file includeLinks/MeanRatioFunctions.hpp.
References isqrt3, isqrt6, MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), and IdealWeightMeanRatio::compute_element_analytical_gradient().
 {
   double matr[9], f;
   double adj_m[9], g;
   double loc1, loc2, loc3;
   /* Calculate M = A*inv(W). */
   f       = x[1][0] + x[0][0];
   matr[0] = x[1][0] - x[0][0];
   matr[1] = (2.0*x[2][0] - f)*isqrt3;
   matr[2] = (3.0*x[3][0] - x[2][0] - f)*isqrt6;
   f       = x[1][1] + x[0][1];
   matr[3] = x[1][1] - x[0][1];
   matr[4] = (2.0*x[2][1] - f)*isqrt3;
   matr[5] = (3.0*x[3][1] - x[2][1] - f)*isqrt6;
   f       = x[1][2] + x[0][2];
   matr[6] = x[1][2] - x[0][2];
   matr[7] = (2.0*x[2][2] - f)*isqrt3;
   matr[8] = (3.0*x[3][2] - x[2][2] - f)*isqrt6;
   /* Calculate det(M). */
   loc1 = matr[4]*matr[8] - matr[5]*matr[7];
   loc2 = matr[5]*matr[6] - matr[3]*matr[8];
   loc3 = matr[3]*matr[7] - matr[4]*matr[6];
   g = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] + matr[2]*matr[2] +
       matr[3]*matr[3] + matr[4]*matr[4] + matr[5]*matr[5] +
       matr[6]*matr[6] + matr[7]*matr[7] + matr[8]*matr[8];
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   adj_m[0] = matr[0]*f + loc1*g;
   adj_m[1] = matr[1]*f + loc2*g;
   adj_m[2] = matr[2]*f + loc3*g;
   loc1 = matr[0]*g;
   loc2 = matr[1]*g;
   loc3 = matr[2]*g;
   adj_m[3] = matr[3]*f + loc3*matr[7] - loc2*matr[8];
   adj_m[4] = matr[4]*f + loc1*matr[8] - loc3*matr[6];
   adj_m[5] = matr[5]*f + loc2*matr[6] - loc1*matr[7];
   adj_m[6] = matr[6]*f + loc2*matr[5] - loc3*matr[4];
   adj_m[7] = matr[7]*f + loc3*matr[3] - loc1*matr[5];
   adj_m[8] = matr[8]*f + loc1*matr[4] - loc2*matr[3];
   loc1 = isqrt3*adj_m[1];
   loc2 = isqrt6*adj_m[2];
   loc3 = loc1 + loc2;
   g_obj[0][0] = -adj_m[0] - loc3;
   g_obj[1][0] = adj_m[0] - loc3;
   g_obj[2][0] = 2.0*loc1 - loc2;
   g_obj[3][0] = 3.0*loc2;
   loc1 = isqrt3*adj_m[4];
   loc2 = isqrt6*adj_m[5];
   loc3 = loc1 + loc2;
   g_obj[0][1] = -adj_m[3] - loc3;
   g_obj[1][1] = adj_m[3] - loc3;
   g_obj[2][1] = 2.0*loc1 - loc2;
   g_obj[3][1] = 3.0*loc2;
   loc1 = isqrt3*adj_m[7];
   loc2 = isqrt6*adj_m[8];
   loc3 = loc1 + loc2;
   g_obj[0][2] = -adj_m[6] - loc3;
   g_obj[1][2] = adj_m[6] - loc3;
   g_obj[2][2] = 2.0*loc1 - loc2;
   g_obj[3][2] = 3.0*loc2;
   return true;
 }
bool g_fcn_3e_v0 (double & obj, Vector3D & g_obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 1681 of file includeLinks/MeanRatioFunctions.hpp.
References g_fcn_3e_v3().
 {
   static Vector3D my_x[4];
   my_x[0] = x[1];
   my_x[1] = x[3];
   my_x[2] = x[2];
   my_x[3] = x[0];
   return g_fcn_3e_v3(obj, g_obj, my_x, a, b, c);
 }
bool g_fcn_3e_v1 (double & obj, Vector3D & g_obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 1693 of file includeLinks/MeanRatioFunctions.hpp.
References g_fcn_3e_v3().
 {
   static Vector3D my_x[4];
   my_x[0] = x[0];
   my_x[1] = x[2];
   my_x[2] = x[3];
   my_x[3] = x[1];
   return g_fcn_3e_v3(obj, g_obj, my_x, a, b, c);
 }
bool g_fcn_3e_v2 (double & obj, Vector3D & g_obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 1705 of file includeLinks/MeanRatioFunctions.hpp.
References g_fcn_3e_v3().
 {
   static Vector3D my_x[4];
   my_x[0] = x[1];
   my_x[1] = x[0];
   my_x[2] = x[3];
   my_x[3] = x[2];
   return g_fcn_3e_v3(obj, g_obj, my_x, a, b, c);
 }
bool g_fcn_3e_v3 (double & obj, Vector3D & g_obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 1629 of file includeLinks/MeanRatioFunctions.hpp.
References isqrt3, isqrt6, MSQ_MIN, pow(), and tisqrt6.
Referenced by g_fcn_3e_v0(), g_fcn_3e_v1(), and g_fcn_3e_v2().
 {
   double matr[9], f, g;
   double loc1, loc2, loc3;
   /* Calculate M = A*inv(W). */
   f       = x[1][0] + x[0][0];
   matr[0] = x[1][0] - x[0][0];
   matr[1] = (2.0*x[2][0] - f)*isqrt3;
   matr[2] = (3.0*x[3][0] - x[2][0] - f)*isqrt6;
   f       = x[1][1] + x[0][1];
   matr[3] = x[1][1] - x[0][1];
   matr[4] = (2.0*x[2][1] - f)*isqrt3;
   matr[5] = (3.0*x[3][1] - x[2][1] - f)*isqrt6;
   f       = x[1][2] + x[0][2];
   matr[6] = x[1][2] - x[0][2];
   matr[7] = (2.0*x[2][2] - f)*isqrt3;
   matr[8] = (3.0*x[3][2] - x[2][2] - f)*isqrt6;
   /* Calculate det(M). */
   loc1 = matr[4]*matr[8] - matr[5]*matr[7];
   loc2 = matr[5]*matr[6] - matr[3]*matr[8];
   loc3 = matr[3]*matr[7] - matr[4]*matr[6];
   g = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] + matr[2]*matr[2] +
       matr[3]*matr[3] + matr[4]*matr[4] + matr[5]*matr[5] +
       matr[6]*matr[6] + matr[7]*matr[7] + matr[8]*matr[8];
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   g_obj[0] = tisqrt6*(matr[2]*f + loc3*g);
   loc1 = matr[0]*g;
   loc2 = matr[1]*g;
   g_obj[1] = tisqrt6*(matr[5]*f + loc2*matr[6] - loc1*matr[7]);
   g_obj[2] = tisqrt6*(matr[8]*f + loc1*matr[4] - loc2*matr[3]);
   return true;
 }
bool g_fcn_3i (double & obj, Vector3D g_obj[4], const Vector3D x[4], const double a, const Exponent & b, const Exponent & c, const Vector3D & d) inline
Definition at line 1895 of file includeLinks/MeanRatioFunctions.hpp.
References MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_gradient(), and IdealWeightMeanRatio::compute_element_analytical_gradient().
 {
   double matr[9], f;
   double adj_m[9], g;
   double loc1, loc2, loc3;
   /* Calculate M = A*inv(W). */
   matr[0] = d[0]*(x[1][0] - x[0][0]);
   matr[1] = d[1]*(x[2][0] - x[0][0]);
   matr[2] = d[2]*(x[3][0] - x[0][0]);
   matr[3] = d[0]*(x[1][1] - x[0][1]);
   matr[4] = d[1]*(x[2][1] - x[0][1]);
   matr[5] = d[2]*(x[3][1] - x[0][1]);
   matr[6] = d[0]*(x[1][2] - x[0][2]);
   matr[7] = d[1]*(x[2][2] - x[0][2]);
   matr[8] = d[2]*(x[3][2] - x[0][2]);
   /* Calculate det(M). */
   loc1 = matr[4]*matr[8] - matr[5]*matr[7];
   loc2 = matr[5]*matr[6] - matr[3]*matr[8];
   loc3 = matr[3]*matr[7] - matr[4]*matr[6];
   g = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] + matr[2]*matr[2] +
       matr[3]*matr[3] + matr[4]*matr[4] + matr[5]*matr[5] +
       matr[6]*matr[6] + matr[7]*matr[7] + matr[8]*matr[8];
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   adj_m[0] = d[0]*(matr[0]*f + loc1*g);
   adj_m[1] = d[1]*(matr[1]*f + loc2*g);
   adj_m[2] = d[2]*(matr[2]*f + loc3*g);
   loc1 = matr[0]*g;
   loc2 = matr[1]*g;
   loc3 = matr[2]*g;
   adj_m[3] = d[0]*(matr[3]*f + loc3*matr[7] - loc2*matr[8]);
   adj_m[4] = d[1]*(matr[4]*f + loc1*matr[8] - loc3*matr[6]);
   adj_m[5] = d[2]*(matr[5]*f + loc2*matr[6] - loc1*matr[7]);
   adj_m[6] = d[0]*(matr[6]*f + loc2*matr[5] - loc3*matr[4]);
   adj_m[7] = d[1]*(matr[7]*f + loc3*matr[3] - loc1*matr[5]);
   adj_m[8] = d[2]*(matr[8]*f + loc1*matr[4] - loc2*matr[3]);
   g_obj[0][0] = -adj_m[0] - adj_m[1] - adj_m[2];
   g_obj[1][0] =  adj_m[0];
   g_obj[2][0] =  adj_m[1];
   g_obj[3][0] =  adj_m[2];
   g_obj[0][1] = -adj_m[3] - adj_m[4] - adj_m[5];
   g_obj[1][1] =  adj_m[3];
   g_obj[2][1] =  adj_m[4];
   g_obj[3][1] =  adj_m[5];
   g_obj[0][2] = -adj_m[6] - adj_m[7] - adj_m[8];
   g_obj[1][2] =  adj_m[6];
   g_obj[2][2] =  adj_m[7];
   g_obj[3][2] =  adj_m[8];
   return true;
 }
bool g_gdft_2 (double & obj, Vector3D g_obj[3], const Vector3D x[3], const Vector3D & n, const Matrix3D & invR, const Matrix3D & Q, const double alpha = 0.5, const Exponent & gamma = 1.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 210 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     double adjm[9], loc1, loc2, loc3, loc4;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + n[0]*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + n[1]*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + n[2]*invR[2][2];
     /* Calculate det(M). */
     loc1 = matr[4]*matr[8] - matr[5]*matr[7];
     loc2 = matr[5]*matr[6] - matr[3]*matr[8];
     loc3 = matr[3]*matr[7] - matr[4]*matr[6];
     t1 = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc4 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc4;
     /* Calculate the derivative of the objective function. */
     f = 2.0 * loc4;
     g = -gamma * obj / t2;
     /* Calculate adjoint matrix */
     adjm[0] = f*matd[0] + g*loc1;
     adjm[1] = f*matd[1] + g*loc2;
     adjm[2] = f*matd[2] + g*loc3;
     loc1 = g*matr[0];
     loc2 = g*matr[1];
     loc3 = g*matr[2];
     adjm[3] = f*matd[3] + loc3*matr[7] - loc2*matr[8];
     adjm[4] = f*matd[4] + loc1*matr[8] - loc3*matr[6];
     adjm[5] = f*matd[5] + loc2*matr[6] - loc1*matr[7];
     adjm[6] = f*matd[6] + loc2*matr[5] - loc3*matr[4];
     adjm[7] = f*matd[7] + loc3*matr[3] - loc1*matr[5];
     adjm[8] = f*matd[8] + loc1*matr[4] - loc2*matr[3];
     /* Construct gradients */
     g_obj[1][0] = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[2][0] =                    invR[1][1]*adjm[1]+invR[1][2]*adjm[2];
     g_obj[0][0] = -g_obj[1][0] - g_obj[2][0];
     g_obj[1][1] = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[2][1] =                    invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     g_obj[0][1] = -g_obj[1][1] - g_obj[2][1];
     g_obj[1][2] = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     g_obj[2][2] =                    invR[1][1]*adjm[7]+invR[1][2]*adjm[8];
     g_obj[0][2] = -g_obj[1][2] - g_obj[2][2];
     return true;
   }
bool g_gdft_2_v0 (double & obj, Vector3D & g_obj, const Vector3D x[3], const Vector3D & n, const Matrix3D & invR, const Matrix3D & Q, const double alpha = 0.5, const Exponent & gamma = 1.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 1216 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     double adjm[9], loc1, loc2, loc3, loc4;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + n[0]*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + n[1]*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + n[2]*invR[2][2];
     /* Calculate det(M). */
     loc1 = matr[4]*matr[8] - matr[5]*matr[7];
     loc2 = matr[5]*matr[6] - matr[3]*matr[8];
     loc3 = matr[3]*matr[7] - matr[4]*matr[6];
     t1 = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc4 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc4;
     /* Calculate the derivative of the objective function. */
     f = 2.0 * loc4;
     g = -gamma * obj / t2;
     /* Calculate adjoint matrix */
     adjm[0] = f*matd[0] + g*loc1;
     adjm[1] = f*matd[1] + g*loc2;
     adjm[2] = f*matd[2] + g*loc3;
     loc1 = g*matr[0];
     loc2 = g*matr[1];
     loc3 = g*matr[2];
     adjm[3] = f*matd[3] + loc3*matr[7] - loc2*matr[8];
     adjm[4] = f*matd[4] + loc1*matr[8] - loc3*matr[6];
     adjm[5] = f*matd[5] + loc2*matr[6] - loc1*matr[7];
     adjm[6] = f*matd[6] + loc2*matr[5] - loc3*matr[4];
     adjm[7] = f*matd[7] + loc3*matr[3] - loc1*matr[5];
     adjm[8] = f*matd[8] + loc1*matr[4] - loc2*matr[3];
     /* Construct gradients */
     g_obj[0]  = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[0] +=                    invR[1][1]*adjm[1]+invR[1][2]*adjm[2];
     g_obj[0]  = -g_obj[0];
     g_obj[1]  = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[1] +=                    invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     g_obj[1]  = -g_obj[1];
     g_obj[2]  = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     g_obj[2] +=                    invR[1][1]*adjm[7]+invR[1][2]*adjm[8];
     g_obj[2]  = -g_obj[2];
     return true;
   }
bool g_gdft_2_v1 (double & obj, Vector3D & g_obj, const Vector3D x[3], const Vector3D & n, const Matrix3D & invR, const Matrix3D & Q, const double alpha = 0.5, const Exponent & gamma = 1.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 1316 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     double adjm[9], loc1, loc2, loc3, loc4;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + n[0]*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + n[1]*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + n[2]*invR[2][2];
     /* Calculate det(M). */
     loc1 = matr[4]*matr[8] - matr[5]*matr[7];
     loc2 = matr[5]*matr[6] - matr[3]*matr[8];
     loc3 = matr[3]*matr[7] - matr[4]*matr[6];
     t1 = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc4 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc4;
     /* Calculate the derivative of the objective function. */
     f = 2.0 * loc4;
     g = -gamma * obj / t2;
     /* Calculate adjoint matrix */
     adjm[0] = f*matd[0] + g*loc1;
     adjm[1] = f*matd[1] + g*loc2;
     adjm[2] = f*matd[2] + g*loc3;
     loc1 = g*matr[0];
     loc2 = g*matr[1];
     loc3 = g*matr[2];
     adjm[3] = f*matd[3] + loc3*matr[7] - loc2*matr[8];
     adjm[4] = f*matd[4] + loc1*matr[8] - loc3*matr[6];
     adjm[5] = f*matd[5] + loc2*matr[6] - loc1*matr[7];
     adjm[6] = f*matd[6] + loc2*matr[5] - loc3*matr[4];
     adjm[7] = f*matd[7] + loc3*matr[3] - loc1*matr[5];
     adjm[8] = f*matd[8] + loc1*matr[4] - loc2*matr[3];
     /* Construct gradients */
     g_obj[0] = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[1] = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[2] = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     return true;
   }
bool g_gdft_2_v2 (double & obj, Vector3D & g_obj, const Vector3D x[3], const Vector3D & n, const Matrix3D & invR, const Matrix3D & Q, const double alpha = 0.5, const Exponent & gamma = 1.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 1408 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     double adjm[6], loc1, loc2, loc3, loc4;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + n[0]*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + n[1]*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + n[2]*invR[2][2];
     /* Calculate det(M). */
     loc1 = matr[4]*matr[8] - matr[5]*matr[7];
     loc2 = matr[5]*matr[6] - matr[3]*matr[8];
     loc3 = matr[3]*matr[7] - matr[4]*matr[6];
     t1 = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc4 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc4;
     /* Calculate the derivative of the objective function. */
     f = 2.0 * loc4;
     g = -gamma * obj / t2;
     /* Calculate adjoint matrix */
     adjm[0] = f*matd[1] + g*loc2;
     adjm[1] = f*matd[2] + g*loc3;
     loc1 = g*matr[0];
     loc2 = g*matr[1];
     loc3 = g*matr[2];
     adjm[2] = f*matd[4] + loc1*matr[8] - loc3*matr[6];
     adjm[3] = f*matd[5] + loc2*matr[6] - loc1*matr[7];
     adjm[4] = f*matd[7] + loc3*matr[3] - loc1*matr[5];
     adjm[5] = f*matd[8] + loc1*matr[4] - loc2*matr[3];
     /* Construct gradients */
     g_obj[0] = invR[1][1]*adjm[0]+invR[1][2]*adjm[1];
     g_obj[1] = invR[1][1]*adjm[2]+invR[1][2]*adjm[3];
     g_obj[2] = invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     return true;
   }
bool g_gdft_3 (double & obj, Vector3D g_obj[4], const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 709 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     double adjm[9], loc1, loc2, loc3, loc4;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     loc1 = matr[4]*matr[8] - matr[5]*matr[7];
     loc2 = matr[5]*matr[6] - matr[3]*matr[8];
     loc3 = matr[3]*matr[7] - matr[4]*matr[6];
     t1 = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc4 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc4;
     /* Calculate the derivative of the objective function. */
     f = 2.0 * loc4;
     g = -gamma * obj / t2;
     /* Calculate adjoint matrix */
     adjm[0] = f*matd[0] + g*loc1;
     adjm[1] = f*matd[1] + g*loc2;
     adjm[2] = f*matd[2] + g*loc3;
     loc1 = g*matr[0];
     loc2 = g*matr[1];
     loc3 = g*matr[2];
     adjm[3] = f*matd[3] + loc3*matr[7] - loc2*matr[8];
     adjm[4] = f*matd[4] + loc1*matr[8] - loc3*matr[6];
     adjm[5] = f*matd[5] + loc2*matr[6] - loc1*matr[7];
     adjm[6] = f*matd[6] + loc2*matr[5] - loc3*matr[4];
     adjm[7] = f*matd[7] + loc3*matr[3] - loc1*matr[5];
     adjm[8] = f*matd[8] + loc1*matr[4] - loc2*matr[3];
     /* Construct gradients */
     g_obj[1][0] = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[2][0] =                    invR[1][1]*adjm[1]+invR[1][2]*adjm[2];
     g_obj[3][0] =                                       invR[2][2]*adjm[2];
     g_obj[0][0] = -g_obj[1][0] - g_obj[2][0] - g_obj[3][0];
     g_obj[1][1] = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[2][1] =                    invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     g_obj[3][1] =                                       invR[2][2]*adjm[5];
     g_obj[0][1] = -g_obj[1][1] - g_obj[2][1] - g_obj[3][1];
     g_obj[1][2] = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     g_obj[2][2] =                    invR[1][1]*adjm[7]+invR[1][2]*adjm[8];
     g_obj[3][2] =                                       invR[2][2]*adjm[8];
     g_obj[0][2] = -g_obj[1][2] - g_obj[2][2] - g_obj[3][2];
     return true;
   }
bool g_gdft_3_v0 (double & obj, Vector3D & g_obj, const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 2173 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     double adjm[9], loc1, loc2, loc3, loc4;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     loc1 = matr[4]*matr[8] - matr[5]*matr[7];
     loc2 = matr[5]*matr[6] - matr[3]*matr[8];
     loc3 = matr[3]*matr[7] - matr[4]*matr[6];
     t1 = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc4 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc4;
     /* Calculate the derivative of the objective function. */
     f = 2.0 * loc4;
     g = -gamma * obj / t2;
     /* Calculate adjoint matrix */
     adjm[0] = f*matd[0] + g*loc1;
     adjm[1] = f*matd[1] + g*loc2;
     adjm[2] = f*matd[2] + g*loc3;
     loc1 = g*matr[0];
     loc2 = g*matr[1];
     loc3 = g*matr[2];
     adjm[3] = f*matd[3] + loc3*matr[7] - loc2*matr[8];
     adjm[4] = f*matd[4] + loc1*matr[8] - loc3*matr[6];
     adjm[5] = f*matd[5] + loc2*matr[6] - loc1*matr[7];
     adjm[6] = f*matd[6] + loc2*matr[5] - loc3*matr[4];
     adjm[7] = f*matd[7] + loc3*matr[3] - loc1*matr[5];
     adjm[8] = f*matd[8] + loc1*matr[4] - loc2*matr[3];
     /* Construct gradients */
     g_obj[0]  = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[0] +=                    invR[1][1]*adjm[1]+invR[1][2]*adjm[2];
     g_obj[0] +=                                       invR[2][2]*adjm[2];
     g_obj[0]  = -g_obj[0];
     g_obj[1]  = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[1] +=                    invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     g_obj[1] +=                                       invR[2][2]*adjm[5];
     g_obj[1]  = -g_obj[1];
     g_obj[2]  = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     g_obj[2] +=                    invR[1][1]*adjm[7]+invR[1][2]*adjm[8];
     g_obj[2] +=                                       invR[2][2]*adjm[8];
     g_obj[2]  = -g_obj[2];
     return true;
   }
bool g_gdft_3_v1 (double & obj, Vector3D & g_obj, const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 2279 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     double adjm[9], loc1, loc2, loc3, loc4;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     loc1 = matr[4]*matr[8] - matr[5]*matr[7];
     loc2 = matr[5]*matr[6] - matr[3]*matr[8];
     loc3 = matr[3]*matr[7] - matr[4]*matr[6];
     t1 = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc4 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc4;
     /* Calculate the derivative of the objective function. */
     f = 2.0 * loc4;
     g = -gamma * obj / t2;
     /* Calculate adjoint matrix */
     adjm[0] = f*matd[0] + g*loc1;
     adjm[1] = f*matd[1] + g*loc2;
     adjm[2] = f*matd[2] + g*loc3;
     loc1 = g*matr[0];
     loc2 = g*matr[1];
     loc3 = g*matr[2];
     adjm[3] = f*matd[3] + loc3*matr[7] - loc2*matr[8];
     adjm[4] = f*matd[4] + loc1*matr[8] - loc3*matr[6];
     adjm[5] = f*matd[5] + loc2*matr[6] - loc1*matr[7];
     adjm[6] = f*matd[6] + loc2*matr[5] - loc3*matr[4];
     adjm[7] = f*matd[7] + loc3*matr[3] - loc1*matr[5];
     adjm[8] = f*matd[8] + loc1*matr[4] - loc2*matr[3];
     /* Construct gradients */
     g_obj[0] = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[1] = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[2] = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     return true;
   }
bool g_gdft_3_v2 (double & obj, Vector3D & g_obj, const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 2374 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     double adjm[6], loc1, loc2, loc3, loc4;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     loc1 = matr[4]*matr[8] - matr[5]*matr[7];
     loc2 = matr[5]*matr[6] - matr[3]*matr[8];
     loc3 = matr[3]*matr[7] - matr[4]*matr[6];
     t1 = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc4 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc4;
     /* Calculate the derivative of the objective function. */
     f = 2.0 * loc4;
     g = -gamma * obj / t2;
     /* Calculate adjoint matrix */
     adjm[0] = f*matd[1] + g*loc2;
     adjm[1] = f*matd[2] + g*loc3;
     loc1 = g*matr[0];
     loc2 = g*matr[1];
     loc3 = g*matr[2];
     adjm[2] = f*matd[4] + loc1*matr[8] - loc3*matr[6];
     adjm[3] = f*matd[5] + loc2*matr[6] - loc1*matr[7];
     adjm[4] = f*matd[7] + loc3*matr[3] - loc1*matr[5];
     adjm[5] = f*matd[8] + loc1*matr[4] - loc2*matr[3];
     /* Construct gradients */
     g_obj[0] = invR[1][1]*adjm[0]+invR[1][2]*adjm[1];
     g_obj[1] = invR[1][1]*adjm[2]+invR[1][2]*adjm[3];
     g_obj[2] = invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     return true;
   }
bool g_gdft_3_v3 (double & obj, Vector3D & g_obj, const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 2466 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     double loc1, loc2, loc3, loc4;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     loc1 = matr[4]*matr[8] - matr[5]*matr[7];
     loc2 = matr[5]*matr[6] - matr[3]*matr[8];
     loc3 = matr[3]*matr[7] - matr[4]*matr[6];
     t1 = matr[0]*loc1 + matr[1]*loc2 + matr[2]*loc3;
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc4 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc4;
     /* Calculate the derivative of the objective function. */
     f = 2.0 * loc4;
     g = -gamma * obj / t2;
     /* Construct gradients */
     loc1 = g*matr[0];
     loc2 = g*matr[1];
     g_obj[0] = invR[2][2]*(f*matd[2] + g*loc3);
     g_obj[1] = invR[2][2]*(f*matd[5] + loc2*matr[6] - loc1*matr[7]);
     g_obj[2] = invR[2][2]*(f*matd[8] + loc1*matr[4] - loc2*matr[3]);
     return true;
   }
bool h_fcn_2e (double & obj, Vector3D g_obj[3], Matrix3D h_obj[6], const Vector3D x[3], const Vector3D & n, const double a, const Exponent & b, const Exponent & c) inline
Definition at line 244 of file includeLinks/MeanRatioFunctions.hpp.
References A, nvc::cross(), Matrix3D::fill_lower_triangle(), isqrt3, MSQ_MIN, pow(), and tisqrt3.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), and IdealWeightMeanRatio::compute_element_analytical_hessian().
 {
   double matr[9], f;
   double adj_m[9], g;           // adj_m[2,5,8] not used
   double dg[9];                 // dg[2,5,8] not used
   double loc0, loc1, loc2, loc3, loc4;
   double A[12], J_A[6], J_B[9], J_C[9], cross;  // only 2x2 corners used
   /* Calculate M = [A*inv(W) n] */
   matr[0] = x[1][0] - x[0][0];
   matr[1] = (2.0*x[2][0] - x[1][0] - x[0][0])*isqrt3;
   matr[2] = n[0];
   matr[3] = x[1][1] - x[0][1];
   matr[4] = (2.0*x[2][1] - x[1][1] - x[0][1])*isqrt3;
   matr[5] = n[1];
   matr[6] = x[1][2] - x[0][2];
   matr[7] = (2.0*x[2][2] - x[1][2] - x[0][2])*isqrt3;
   matr[8] = n[2];
   /* Calculate det([n M]). */
   dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
   dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
   dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
   g = matr[0]*dg[0] + matr[3]*dg[3] + matr[6]*dg[6];
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] +
       matr[3]*matr[3] + matr[4]*matr[4] +
       matr[6]*matr[6] + matr[7]*matr[7];
   loc3 = f;
   loc4 = g;
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
   dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
   dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
   adj_m[0] = matr[0]*f + dg[0]*g;
   adj_m[1] = matr[1]*f + dg[1]*g;
   adj_m[3] = matr[3]*f + dg[3]*g;
   adj_m[4] = matr[4]*f + dg[4]*g;
   adj_m[6] = matr[6]*f + dg[6]*g;
   adj_m[7] = matr[7]*f + dg[7]*g;
   loc1 = isqrt3*adj_m[1];
   g_obj[0][0] = -adj_m[0] - loc1;
   g_obj[1][0] =  adj_m[0] - loc1;
   g_obj[2][0] = 2.0*loc1;
   loc1 = isqrt3*adj_m[4];
   g_obj[0][1] = -adj_m[3] - loc1;
   g_obj[1][1] =  adj_m[3] - loc1;
   g_obj[2][1] = 2.0*loc1;
   loc1 = isqrt3*adj_m[7];
   g_obj[0][2] = -adj_m[6] - loc1;
   g_obj[1][2] =  adj_m[6] - loc1;
   g_obj[2][2] = 2.0*loc1;
   /* Calculate the hessian of the objective.                   */
   loc0 = f;                     /* Constant on nabla^2 f       */
   loc1 = g;                     /* Constant on nabla^2 g       */
   cross = f * c / loc4;         /* Constant on nabla g nabla f */
   f = f * (b-1) / loc3;         /* Constant on nabla f nabla f */
   g = g * (c-1) / loc4;         /* Constant on nabla g nabla g */
   f *= 2.0;                     /* Modification for nabla f    */
   /* First block of rows */
   loc3 = matr[0]*f + dg[0]*cross;
   loc4 = dg[0]*g + matr[0]*cross;
   J_A[0] = loc0 + loc3*matr[0] + loc4*dg[0];
   J_A[1] = loc3*matr[1] + loc4*dg[1];
   J_B[0] = loc3*matr[3] + loc4*dg[3];
   J_B[1] = loc3*matr[4] + loc4*dg[4];
   J_C[0] = loc3*matr[6] + loc4*dg[6];
   J_C[1] = loc3*matr[7] + loc4*dg[7];
   loc3 = matr[1]*f + dg[1]*cross;
   loc4 = dg[1]*g + matr[1]*cross;
   J_A[3] = loc0 + loc3*matr[1] + loc4*dg[1];
   J_B[3] = loc3*matr[3] + loc4*dg[3];
   J_B[4] = loc3*matr[4] + loc4*dg[4];
   J_C[3] = loc3*matr[6] + loc4*dg[6];
   J_C[4] = loc3*matr[7] + loc4*dg[7];
   /* First diagonal block */
   loc2 = isqrt3*J_A[1];
   A[0] = -J_A[0] - loc2;
   A[1] =  J_A[0] - loc2;
   loc2 = isqrt3*J_A[3];
   A[4] = -J_A[1] - loc2;
   A[5] =  J_A[1] - loc2;
   A[6] = 2.0*loc2;
   loc2 = isqrt3*A[4];
   h_obj[0][0][0] = -A[0] - loc2;
   h_obj[1][0][0] =  A[0] - loc2;
   h_obj[2][0][0] = 2.0*loc2;
   loc2 = isqrt3*A[5];
   h_obj[3][0][0] = A[1] - loc2;
   h_obj[4][0][0] = 2.0*loc2;
   h_obj[5][0][0] = tisqrt3*A[6];
   /* First off-diagonal block */
   loc2 = matr[8]*loc1;
   J_B[1] += loc2;
   J_B[3] -= loc2;
   loc2 = isqrt3*J_B[3];
   A[0] = -J_B[0] - loc2;
   A[1] =  J_B[0] - loc2;
   A[2] = 2.0*loc2;
   loc2 = isqrt3*J_B[4];
   A[4] = -J_B[1] - loc2;
   A[5] =  J_B[1] - loc2;
   A[6] = 2.0*loc2;
   loc2 = isqrt3*A[4];
   h_obj[0][0][1] = -A[0] - loc2;
   h_obj[1][0][1] =  A[0] - loc2;
   h_obj[2][0][1] = 2.0*loc2;
   loc2 = isqrt3*A[5];
   h_obj[1][1][0] = -A[1] - loc2;
   h_obj[3][0][1] =  A[1] - loc2;
   h_obj[4][0][1] = 2.0*loc2;
   loc2 = isqrt3*A[6];
   h_obj[2][1][0] = -A[2] - loc2;
   h_obj[4][1][0] =  A[2] - loc2;
   h_obj[5][0][1] = 2.0*loc2;
   /* Second off-diagonal block */
   loc2 = matr[5]*loc1;
   J_C[1] -= loc2;
   J_C[3] += loc2;
   loc2 = isqrt3*J_C[3];
   A[0] = -J_C[0] - loc2;
   A[1] =  J_C[0] - loc2;
   A[2] = 2.0*loc2;
   loc2 = isqrt3*J_C[4];
   A[4] = -J_C[1] - loc2;
   A[5] =  J_C[1] - loc2;
   A[6] = 2.0*loc2;
   loc2 = isqrt3*A[4];
   h_obj[0][0][2] = -A[0] - loc2;
   h_obj[1][0][2] =  A[0] - loc2;
   h_obj[2][0][2] = 2.0*loc2;
   loc2 = isqrt3*A[5];
   h_obj[1][2][0] = -A[1] - loc2;
   h_obj[3][0][2] =  A[1] - loc2;
   h_obj[4][0][2] = 2.0*loc2;
   loc2 = isqrt3*A[6];
   h_obj[2][2][0] = -A[2] - loc2;
   h_obj[4][2][0] =  A[2] - loc2;
   h_obj[5][0][2] = 2.0*loc2;
   /* Second block of rows */
   loc3 = matr[3]*f + dg[3]*cross;
   loc4 = dg[3]*g + matr[3]*cross;
   J_A[0] = loc0 + loc3*matr[3] + loc4*dg[3];
   J_A[1] = loc3*matr[4] + loc4*dg[4];
   J_B[0] = loc3*matr[6] + loc4*dg[6];
   J_B[1] = loc3*matr[7] + loc4*dg[7];
   loc3 = matr[4]*f + dg[4]*cross;
   loc4 = dg[4]*g + matr[4]*cross;
   J_A[3] = loc0 + loc3*matr[4] + loc4*dg[4];
   J_B[3] = loc3*matr[6] + loc4*dg[6];
   J_B[4] = loc3*matr[7] + loc4*dg[7];
   /* Second diagonal block */
   loc2 = isqrt3*J_A[1];
   A[0] = -J_A[0] - loc2;
   A[1] =  J_A[0] - loc2;
   loc2 = isqrt3*J_A[3];
   A[4] = -J_A[1] - loc2;
   A[5] =  J_A[1] - loc2;
   A[6] = 2.0*loc2;
   loc2 = isqrt3*A[4];
   h_obj[0][1][1] = -A[0] - loc2;
   h_obj[1][1][1] =  A[0] - loc2;
   h_obj[2][1][1] = 2.0*loc2;
   loc2 = isqrt3*A[5];
   h_obj[3][1][1] = A[1] - loc2;
   h_obj[4][1][1] = 2.0*loc2;
   h_obj[5][1][1] = tisqrt3*A[6];
   /* Third off-diagonal block */
   loc2 = matr[2]*loc1;
   J_B[1] += loc2;
   J_B[3] -= loc2;
   loc2 = isqrt3*J_B[3];
   A[0] = -J_B[0] - loc2;
   A[1] =  J_B[0] - loc2;
   A[2] = 2.0*loc2;
   loc2 = isqrt3*J_B[4];
   A[4] = -J_B[1] - loc2;
   A[5] =  J_B[1] - loc2;
   A[6] = 2.0*loc2;
   loc2 = isqrt3*A[4];
   h_obj[0][1][2] = -A[0] - loc2;
   h_obj[1][1][2] =  A[0] - loc2;
   h_obj[2][1][2] = 2.0*loc2;
   loc2 = isqrt3*A[5];
   h_obj[1][2][1] = -A[1] - loc2;
   h_obj[3][1][2] =  A[1] - loc2;
   h_obj[4][1][2] = 2.0*loc2;
   loc2 = isqrt3*A[6];
   h_obj[2][2][1] = -A[2] - loc2;
   h_obj[4][2][1] =  A[2] - loc2;
   h_obj[5][1][2] = 2.0*loc2;
   /* Third block of rows */
   loc3 = matr[6]*f + dg[6]*cross;
   loc4 = dg[6]*g + matr[6]*cross;
   J_A[0] = loc0 + loc3*matr[6] + loc4*dg[6];
   J_A[1] = loc3*matr[7] + loc4*dg[7];
   loc3 = matr[7]*f + dg[7]*cross;
   loc4 = dg[7]*g + matr[7]*cross;
   J_A[3] = loc0 + loc3*matr[7] + loc4*dg[7];
   /* Third diagonal block */
   loc2 = isqrt3*J_A[1];
   A[0] = -J_A[0] - loc2;
   A[1] =  J_A[0] - loc2;
   loc2 = isqrt3*J_A[3];
   A[4] = -J_A[1] - loc2;
   A[5] =  J_A[1] - loc2;
   A[6] = 2.0*loc2;
   loc2 = isqrt3*A[4];
   h_obj[0][2][2] = -A[0] - loc2;
   h_obj[1][2][2] =  A[0] - loc2;
   h_obj[2][2][2] = 2.0*loc2;
   loc2 = isqrt3*A[5];
   h_obj[3][2][2] = A[1] - loc2;
   h_obj[4][2][2] = 2.0*loc2;
   h_obj[5][2][2] = tisqrt3*A[6];
   // completes diagonal blocks.
   h_obj[0].fill_lower_triangle();
   h_obj[3].fill_lower_triangle();
   h_obj[5].fill_lower_triangle();
   return true;
 }
bool h_fcn_2i (double & obj, Vector3D g_obj[3], Matrix3D h_obj[6], const Vector3D x[3], const Vector3D & n, const double a, const Exponent & b, const Exponent & c, const Vector3D & d) inline
Definition at line 656 of file includeLinks/MeanRatioFunctions.hpp.
References A, nvc::cross(), Matrix3D::fill_lower_triangle(), MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), and IdealWeightMeanRatio::compute_element_analytical_hessian().
 {
   double matr[9], f;
   double adj_m[9], g;           // adj_m[2,5,8] not used
   double dg[9];                 // dg[2,5,8] not used
   double loc0, loc1, loc2, loc3, loc4;
   double A[12], J_A[6], J_B[9], J_C[9], cross;  // only 2x2 corners used
   const double scale[3] = {
     d[0]*d[0], d[0]*d[1],
                d[1]*d[1]
   };
   /* Calculate M = [A*inv(W) n] */
   matr[0] = d[0]*(x[1][0] - x[0][0]);
   matr[1] = d[1]*(x[2][0] - x[0][0]);
   matr[2] = n[0];
   matr[3] = d[0]*(x[1][1] - x[0][1]);
   matr[4] = d[1]*(x[2][1] - x[0][1]);
   matr[5] = n[1];
   matr[6] = d[0]*(x[1][2] - x[0][2]);
   matr[7] = d[1]*(x[2][2] - x[0][2]);
   matr[8] = n[2];
   /* Calculate det([n M]). */
   dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
   dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
   dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
   g = matr[0]*dg[0] + matr[3]*dg[3] + matr[6]*dg[6];
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] +
       matr[3]*matr[3] + matr[4]*matr[4] +
       matr[6]*matr[6] + matr[7]*matr[7];
   loc3 = f;
   loc4 = g;
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
   dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
   dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
   adj_m[0] = d[0]*(matr[0]*f + dg[0]*g);
   adj_m[1] = d[1]*(matr[1]*f + dg[1]*g);
   adj_m[3] = d[0]*(matr[3]*f + dg[3]*g);
   adj_m[4] = d[1]*(matr[4]*f + dg[4]*g);
   adj_m[6] = d[0]*(matr[6]*f + dg[6]*g);
   adj_m[7] = d[1]*(matr[7]*f + dg[7]*g);
   g_obj[0][0] = -adj_m[0] - adj_m[1];
   g_obj[1][0] =  adj_m[0];
   g_obj[2][0] =  adj_m[1];
   g_obj[0][1] = -adj_m[3] - adj_m[4];
   g_obj[1][1] =  adj_m[3];
   g_obj[2][1] =  adj_m[4];
   g_obj[0][2] = -adj_m[6] - adj_m[7];
   g_obj[1][2] =  adj_m[6];
   g_obj[2][2] =  adj_m[7];
   /* Calculate the hessian of the objective.                   */
   loc0 = f;                     /* Constant on nabla^2 f       */
   loc1 = g;                     /* Constant on nabla^2 g       */
   cross = f * c / loc4;         /* Constant on nabla g nabla f */
   f = f * (b-1) / loc3;         /* Constant on nabla f nabla f */
   g = g * (c-1) / loc4;         /* Constant on nabla g nabla g */
   f *= 2.0;                     /* Modification for nabla f    */
   /* First block of rows */
   loc3 = matr[0]*f + dg[0]*cross;
   loc4 = dg[0]*g + matr[0]*cross;
   J_A[0] = loc0 + loc3*matr[0] + loc4*dg[0];
   J_A[1] = loc3*matr[1] + loc4*dg[1];
   J_B[0] = loc3*matr[3] + loc4*dg[3];
   J_B[1] = loc3*matr[4] + loc4*dg[4];
   J_C[0] = loc3*matr[6] + loc4*dg[6];
   J_C[1] = loc3*matr[7] + loc4*dg[7];
   loc3 = matr[1]*f + dg[1]*cross;
   loc4 = dg[1]*g + matr[1]*cross;
   J_A[3] = loc0 + loc3*matr[1] + loc4*dg[1];
   J_B[3] = loc3*matr[3] + loc4*dg[3];
   J_B[4] = loc3*matr[4] + loc4*dg[4];
   J_C[3] = loc3*matr[6] + loc4*dg[6];
   J_C[4] = loc3*matr[7] + loc4*dg[7];
   /* First diagonal block */
   J_A[0] *= scale[0];
   J_A[1] *= scale[1];
   J_A[3] *= scale[2];
   A[0] = -J_A[0] - J_A[1];
   A[4] = -J_A[1] - J_A[3];
   h_obj[0][0][0] = -A[0] - A[4];
   h_obj[1][0][0] =  A[0];
   h_obj[2][0][0] =  A[4];
   h_obj[3][0][0] = J_A[0];
   h_obj[4][0][0] = J_A[1];
   h_obj[5][0][0] = J_A[3];
   /* First off-diagonal block */
   loc2 = matr[8]*loc1;
   J_B[1] += loc2;
   J_B[3] -= loc2;
   J_B[0] *= scale[0];
   J_B[1] *= scale[1];
   J_B[3] *= scale[1];
   J_B[4] *= scale[2];
   A[0] = -J_B[0] - J_B[3];
   A[4] = -J_B[1] - J_B[4];
   h_obj[0][0][1] = -A[0] - A[4];
   h_obj[1][0][1] =  A[0];
   h_obj[2][0][1] =  A[4];
   h_obj[1][1][0] = -J_B[0] - J_B[1];
   h_obj[3][0][1] =  J_B[0];
   h_obj[4][0][1] =  J_B[1];
   h_obj[2][1][0] = -J_B[3] - J_B[4];
   h_obj[4][1][0] =  J_B[3];
   h_obj[5][0][1] =  J_B[4];
   /* Second off-diagonal block */
   loc2 = matr[5]*loc1;
   J_C[1] -= loc2;
   J_C[3] += loc2;
   J_C[0] *= scale[0];
   J_C[1] *= scale[1];
   J_C[3] *= scale[1];
   J_C[4] *= scale[2];
   A[0] = -J_C[0] - J_C[3];
   A[4] = -J_C[1] - J_C[4];
   h_obj[0][0][2] = -A[0] - A[4];
   h_obj[1][0][2] =  A[0];
   h_obj[2][0][2] =  A[4];
   h_obj[1][2][0] = -J_C[0] - J_C[1];
   h_obj[3][0][2] =  J_C[0];
   h_obj[4][0][2] =  J_C[1];
   h_obj[2][2][0] = -J_C[3] - J_C[4];
   h_obj[4][2][0] =  J_C[3];
   h_obj[5][0][2] =  J_C[4];
   /* Second block of rows */
   loc3 = matr[3]*f + dg[3]*cross;
   loc4 = dg[3]*g + matr[3]*cross;
   J_A[0] = loc0 + loc3*matr[3] + loc4*dg[3];
   J_A[1] = loc3*matr[4] + loc4*dg[4];
   J_B[0] = loc3*matr[6] + loc4*dg[6];
   J_B[1] = loc3*matr[7] + loc4*dg[7];
   loc3 = matr[4]*f + dg[4]*cross;
   loc4 = dg[4]*g + matr[4]*cross;
   J_A[3] = loc0 + loc3*matr[4] + loc4*dg[4];
   J_B[3] = loc3*matr[6] + loc4*dg[6];
   J_B[4] = loc3*matr[7] + loc4*dg[7];
   /* Second diagonal block */
   J_A[0] *= scale[0];
   J_A[1] *= scale[1];
   J_A[3] *= scale[2];
   A[0] = -J_A[0] - J_A[1];
   A[4] = -J_A[1] - J_A[3];
   h_obj[0][1][1] = -A[0] - A[4];
   h_obj[1][1][1] =  A[0];
   h_obj[2][1][1] =  A[4];
   h_obj[3][1][1] = J_A[0];
   h_obj[4][1][1] = J_A[1];
   h_obj[5][1][1] = J_A[3];
   /* Third off-diagonal block */
   loc2 = matr[2]*loc1;
   J_B[1] += loc2;
   J_B[3] -= loc2;
   J_B[0] *= scale[0];
   J_B[1] *= scale[1];
   J_B[3] *= scale[1];
   J_B[4] *= scale[2];
   A[0] = -J_B[0] - J_B[3];
   A[4] = -J_B[1] - J_B[4];
   h_obj[0][1][2] = -A[0] - A[4];
   h_obj[1][1][2] =  A[0];
   h_obj[2][1][2] =  A[4];
   h_obj[1][2][1] = -J_B[0] - J_B[1];
   h_obj[3][1][2] =  J_B[0];
   h_obj[4][1][2] =  J_B[1];
   h_obj[2][2][1] = -J_B[3] - J_B[4];
   h_obj[4][2][1] =  J_B[3];
   h_obj[5][1][2] =  J_B[4];
   /* Third block of rows */
   loc3 = matr[6]*f + dg[6]*cross;
   loc4 = dg[6]*g + matr[6]*cross;
   J_A[0] = loc0 + loc3*matr[6] + loc4*dg[6];
   J_A[1] = loc3*matr[7] + loc4*dg[7];
   loc3 = matr[7]*f + dg[7]*cross;
   loc4 = dg[7]*g + matr[7]*cross;
   J_A[3] = loc0 + loc3*matr[7] + loc4*dg[7];
   /* Third diagonal block */
   J_A[0] *= scale[0];
   J_A[1] *= scale[1];
   J_A[3] *= scale[2];
   A[0] = -J_A[0] - J_A[1];
   A[4] = -J_A[1] - J_A[3];
   h_obj[0][2][2] = -A[0] - A[4];
   h_obj[1][2][2] =  A[0];
   h_obj[2][2][2] =  A[4];
   h_obj[3][2][2] = J_A[0];
   h_obj[4][2][2] = J_A[1];
   h_obj[5][2][2] = J_A[3];
   // completes diagonal blocks.
   h_obj[0].fill_lower_triangle();
   h_obj[3].fill_lower_triangle();
   h_obj[5].fill_lower_triangle();
   return true;
 }
bool h_fcn_3e (double & obj, Vector3D g_obj[4], Matrix3D h_obj[10], const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 1062 of file includeLinks/MeanRatioFunctions.hpp.
References A, nvc::cross(), Matrix3D::fill_lower_triangle(), isqrt3, isqrt6, MSQ_MIN, pow(), tisqrt3, and tisqrt6.
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), and IdealWeightMeanRatio::compute_element_analytical_hessian().
 {
   std::cout << "";
   double matr[9], f;
   double adj_m[9], g;
   double dg[9], loc0, loc1, loc2, loc3, loc4;
   double A[12], J_A[6], J_B[9], J_C[9], cross;
   /* Calculate M = A*inv(W). */
   f       = x[1][0] + x[0][0];
   matr[0] = x[1][0] - x[0][0];
   matr[1] = (2.0*x[2][0] - f)*isqrt3;
   matr[2] = (3.0*x[3][0] - x[2][0] - f)*isqrt6;
   f       = x[1][1] + x[0][1];
   matr[3] = x[1][1] - x[0][1];
   matr[4] = (2.0*x[2][1] - f)*isqrt3;
   matr[5] = (3.0*x[3][1] - x[2][1] - f)*isqrt6;
   f       = x[1][2] + x[0][2];
   matr[6] = x[1][2] - x[0][2];
   matr[7] = (2.0*x[2][2] - f)*isqrt3;
   matr[8] = (3.0*x[3][2] - x[2][2] - f)*isqrt6;
   /* Calculate det(M). */
   dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
   dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
   dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
   g = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] + matr[2]*matr[2] +
       matr[3]*matr[3] + matr[4]*matr[4] + matr[5]*matr[5] +
       matr[6]*matr[6] + matr[7]*matr[7] + matr[8]*matr[8];
   loc3 = f;
   loc4 = g;
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
   dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
   dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
   dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
   dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
   dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
   adj_m[0] = matr[0]*f + dg[0]*g;
   adj_m[1] = matr[1]*f + dg[1]*g;
   adj_m[2] = matr[2]*f + dg[2]*g;
   adj_m[3] = matr[3]*f + dg[3]*g;
   adj_m[4] = matr[4]*f + dg[4]*g;
   adj_m[5] = matr[5]*f + dg[5]*g;
   adj_m[6] = matr[6]*f + dg[6]*g;
   adj_m[7] = matr[7]*f + dg[7]*g;
   adj_m[8] = matr[8]*f + dg[8]*g;
   loc0 = isqrt3*adj_m[1];
   loc1 = isqrt6*adj_m[2];
   loc2 = loc0 + loc1;
   g_obj[0][0] = -adj_m[0] - loc2;
   g_obj[1][0] = adj_m[0] - loc2;
   g_obj[2][0] = 2.0*loc0 - loc1;
   g_obj[3][0] = 3.0*loc1;
   loc0 = isqrt3*adj_m[4];
   loc1 = isqrt6*adj_m[5];
   loc2 = loc0 + loc1;
   g_obj[0][1] = -adj_m[3] - loc2;
   g_obj[1][1] = adj_m[3] - loc2;
   g_obj[2][1] = 2.0*loc0 - loc1;
   g_obj[3][1] = 3.0*loc1;
   loc0 = isqrt3*adj_m[7];
   loc1 = isqrt6*adj_m[8];
   loc2 = loc0 + loc1;
   g_obj[0][2] = -adj_m[6] - loc2;
   g_obj[1][2] = adj_m[6] - loc2;
   g_obj[2][2] = 2.0*loc0 - loc1;
   g_obj[3][2] = 3.0*loc1;
   /* Calculate the hessian of the objective.                   */
   loc0 = f;                     /* Constant on nabla^2 f       */
   loc1 = g;                     /* Constant on nabla^2 g       */
   cross = f * c / loc4;         /* Constant on nabla g nabla f */
   f = f * (b-1) / loc3;         /* Constant on nabla f nabla f */
   g = g * (c-1) / loc4;         /* Constant on nabla g nabla g */
   f *= 2.0;                     /* Modification for nabla f    */
   /* First block of rows */
   loc3 = matr[0]*f + dg[0]*cross;
   loc4 = dg[0]*g + matr[0]*cross;
   J_A[0] = loc0 + loc3*matr[0] + loc4*dg[0];
   J_A[1] = loc3*matr[1] + loc4*dg[1];
   J_A[2] = loc3*matr[2] + loc4*dg[2];
   J_B[0] = loc3*matr[3] + loc4*dg[3];
   J_B[1] = loc3*matr[4] + loc4*dg[4];
   J_B[2] = loc3*matr[5] + loc4*dg[5];
   J_C[0] = loc3*matr[6] + loc4*dg[6];
   J_C[1] = loc3*matr[7] + loc4*dg[7];
   J_C[2] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[1]*f + dg[1]*cross;
   loc4 = dg[1]*g + matr[1]*cross;
   J_A[3] = loc0 + loc3*matr[1] + loc4*dg[1];
   J_A[4] = loc3*matr[2] + loc4*dg[2];
   J_B[3] = loc3*matr[3] + loc4*dg[3];
   J_B[4] = loc3*matr[4] + loc4*dg[4];
   J_B[5] = loc3*matr[5] + loc4*dg[5];
   J_C[3] = loc3*matr[6] + loc4*dg[6];
   J_C[4] = loc3*matr[7] + loc4*dg[7];
   J_C[5] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[2]*f + dg[2]*cross;
   loc4 = dg[2]*g + matr[2]*cross;
   J_A[5] = loc0 + loc3*matr[2] + loc4*dg[2];
   J_B[6] = loc3*matr[3] + loc4*dg[3];
   J_B[7] = loc3*matr[4] + loc4*dg[4];
   J_B[8] = loc3*matr[5] + loc4*dg[5];
   J_C[6] = loc3*matr[6] + loc4*dg[6];
   J_C[7] = loc3*matr[7] + loc4*dg[7];
   J_C[8] = loc3*matr[8] + loc4*dg[8];
   /* First diagonal block */
   loc2 = isqrt3*J_A[1];
   loc3 = isqrt6*J_A[2];
   loc4 = loc2 + loc3;
   A[0] = -J_A[0] - loc4;
   A[1] =  J_A[0] - loc4;
   loc2 = isqrt3*J_A[3];
   loc3 = isqrt6*J_A[4];
   loc4 = loc2 + loc3;
   A[4] = -J_A[1] - loc4;
   A[5] =  J_A[1] - loc4;
   A[6] = 2.0*loc2 - loc3;
   loc2 = isqrt3*J_A[4];
   loc3 = isqrt6*J_A[5];
   loc4 = loc2 + loc3;
   A[8] = -J_A[2] - loc4;
   A[9] =  J_A[2] - loc4;
   A[10] = 2.0*loc2 - loc3;
   A[11] = 3.0*loc3;
   loc2 = isqrt3*A[4];
   loc3 = isqrt6*A[8];
   loc4 = loc2 + loc3;
   h_obj[0][0][0] = -A[0] - loc4;
   h_obj[1][0][0] =  A[0] - loc4;
   h_obj[2][0][0] = 2.0*loc2 - loc3;
   h_obj[3][0][0] = 3.0*loc3;
   loc2 = isqrt3*A[5];
   loc3 = isqrt6*A[9];
   h_obj[4][0][0] = A[1] - loc2 - loc3;
   h_obj[5][0][0] = 2.0*loc2 - loc3;
   h_obj[6][0][0] = 3.0*loc3;
   loc3 = isqrt6*A[10];
   h_obj[7][0][0] = tisqrt3*A[6] - loc3;
   h_obj[8][0][0] = 3.0*loc3;
   h_obj[9][0][0] = tisqrt6*A[11];
   /* First off-diagonal block */
   loc2 = matr[8]*loc1;
   J_B[1] += loc2;
   J_B[3] -= loc2;
   loc2 = matr[7]*loc1;
   J_B[2] -= loc2;
   J_B[6] += loc2;
   loc2 = matr[6]*loc1;
   J_B[5] += loc2;
   J_B[7] -= loc2;
   loc2 = isqrt3*J_B[3];
   loc3 = isqrt6*J_B[6];
   loc4 = loc2 + loc3;
   A[0] = -J_B[0] - loc4;
   A[1] =  J_B[0] - loc4;
   A[2] = 2.0*loc2 - loc3;
   A[3] = 3.0*loc3;
   loc2 = isqrt3*J_B[4];
   loc3 = isqrt6*J_B[7];
   loc4 = loc2 + loc3;
   A[4] = -J_B[1] - loc4;
   A[5] =  J_B[1] - loc4;
   A[6] = 2.0*loc2 - loc3;
   A[7] = 3.0*loc3;
   loc2 = isqrt3*J_B[5];
   loc3 = isqrt6*J_B[8];
   loc4 = loc2 + loc3;
   A[8] = -J_B[2] - loc4;
   A[9] =  J_B[2] - loc4;
   A[10] = 2.0*loc2 - loc3;
   A[11] = 3.0*loc3;
   loc2 = isqrt3*A[4];
   loc3 = isqrt6*A[8];
   loc4 = loc2 + loc3;
   h_obj[0][0][1] = -A[0] - loc4;
   h_obj[1][0][1] =  A[0] - loc4;
   h_obj[2][0][1] = 2.0*loc2 - loc3;
   h_obj[3][0][1] = 3.0*loc3;
   loc2 = isqrt3*A[5];
   loc3 = isqrt6*A[9];
   loc4 = loc2 + loc3;
   h_obj[1][1][0] = -A[1] - loc4;
   h_obj[4][0][1] =  A[1] - loc4;
   h_obj[5][0][1] = 2.0*loc2 - loc3;
   h_obj[6][0][1] = 3.0*loc3;
   loc2 = isqrt3*A[6];
   loc3 = isqrt6*A[10];
   loc4 = loc2 + loc3;
   h_obj[2][1][0] = -A[2] - loc4;
   h_obj[5][1][0] =  A[2] - loc4;
   h_obj[7][0][1] = 2.0*loc2 - loc3;
   h_obj[8][0][1] = 3.0*loc3;
   loc2 = isqrt3*A[7];
   loc3 = isqrt6*A[11];
   loc4 = loc2 + loc3;
   h_obj[3][1][0] = -A[3] - loc4;
   h_obj[6][1][0] =  A[3] - loc4;
   h_obj[8][1][0] = 2.0*loc2 - loc3;
   h_obj[9][0][1] = 3.0*loc3;
   /* Second off-diagonal block */
   loc2 = matr[5]*loc1;
   J_C[1] -= loc2;
   J_C[3] += loc2;
   loc2 = matr[4]*loc1;
   J_C[2] += loc2;
   J_C[6] -= loc2;
   loc2 = matr[3]*loc1;
   J_C[5] -= loc2;
   J_C[7] += loc2;
   loc2 = isqrt3*J_C[3];
   loc3 = isqrt6*J_C[6];
   loc4 = loc2 + loc3;
   A[0] = -J_C[0] - loc4;
   A[1] =  J_C[0] - loc4;
   A[2] = 2.0*loc2 - loc3;
   A[3] = 3.0*loc3;
   loc2 = isqrt3*J_C[4];
   loc3 = isqrt6*J_C[7];
   loc4 = loc2 + loc3;
   A[4] = -J_C[1] - loc4;
   A[5] =  J_C[1] - loc4;
   A[6] = 2.0*loc2 - loc3;
   A[7] = 3.0*loc3;
   loc2 = isqrt3*J_C[5];
   loc3 = isqrt6*J_C[8];
   loc4 = loc2 + loc3;
   A[8] = -J_C[2] - loc4;
   A[9] =  J_C[2] - loc4;
   A[10] = 2.0*loc2 - loc3;
   A[11] = 3.0*loc3;
   loc2 = isqrt3*A[4];
   loc3 = isqrt6*A[8];
   loc4 = loc2 + loc3;
   h_obj[0][0][2] = -A[0] - loc4;
   h_obj[1][0][2] =  A[0] - loc4;
   h_obj[2][0][2] = 2.0*loc2 - loc3;
   h_obj[3][0][2] = 3.0*loc3;
   loc2 = isqrt3*A[5];
   loc3 = isqrt6*A[9];
   loc4 = loc2 + loc3;
   h_obj[1][2][0] = -A[1] - loc4;
   h_obj[4][0][2] =  A[1] - loc4;
   h_obj[5][0][2] = 2.0*loc2 - loc3;
   h_obj[6][0][2] = 3.0*loc3;
   loc2 = isqrt3*A[6];
   loc3 = isqrt6*A[10];
   loc4 = loc2 + loc3;
   h_obj[2][2][0] = -A[2] - loc4;
   h_obj[5][2][0] =  A[2] - loc4;
   h_obj[7][0][2] = 2.0*loc2 - loc3;
   h_obj[8][0][2] = 3.0*loc3;
   loc2 = isqrt3*A[7];
   loc3 = isqrt6*A[11];
   loc4 = loc2 + loc3;
   h_obj[3][2][0] = -A[3] - loc4;
   h_obj[6][2][0] =  A[3] - loc4;
   h_obj[8][2][0] = 2.0*loc2 - loc3;
   h_obj[9][0][2] = 3.0*loc3;
   /* Second block of rows */
   loc3 = matr[3]*f + dg[3]*cross;
   loc4 = dg[3]*g + matr[3]*cross;
   J_A[0] = loc0 + loc3*matr[3] + loc4*dg[3];
   J_A[1] = loc3*matr[4] + loc4*dg[4];
   J_A[2] = loc3*matr[5] + loc4*dg[5];
   J_B[0] = loc3*matr[6] + loc4*dg[6];
   J_B[1] = loc3*matr[7] + loc4*dg[7];
   J_B[2] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[4]*f + dg[4]*cross;
   loc4 = dg[4]*g + matr[4]*cross;
   J_A[3] = loc0 + loc3*matr[4] + loc4*dg[4];
   J_A[4] = loc3*matr[5] + loc4*dg[5];
   J_B[3] = loc3*matr[6] + loc4*dg[6];
   J_B[4] = loc3*matr[7] + loc4*dg[7];
   J_B[5] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[5]*f + dg[5]*cross;
   loc4 = dg[5]*g + matr[5]*cross;
   J_A[5] = loc0 + loc3*matr[5] + loc4*dg[5];
   J_B[6] = loc3*matr[6] + loc4*dg[6];
   J_B[7] = loc3*matr[7] + loc4*dg[7];
   J_B[8] = loc3*matr[8] + loc4*dg[8];
   /* Second diagonal block */
   loc2 = isqrt3*J_A[1];
   loc3 = isqrt6*J_A[2];
   loc4 = loc2 + loc3;
   A[0] = -J_A[0] - loc4;
   A[1] =  J_A[0] - loc4;
   loc2 = isqrt3*J_A[3];
   loc3 = isqrt6*J_A[4];
   loc4 = loc2 + loc3;
   A[4] = -J_A[1] - loc4;
   A[5] =  J_A[1] - loc4;
   A[6] = 2.0*loc2 - loc3;
   loc2 = isqrt3*J_A[4];
   loc3 = isqrt6*J_A[5];
   loc4 = loc2 + loc3;
   A[8] = -J_A[2] - loc4;
   A[9] =  J_A[2] - loc4;
   A[10] = 2.0*loc2 - loc3;
   A[11] = 3.0*loc3;
   loc2 = isqrt3*A[4];
   loc3 = isqrt6*A[8];
   loc4 = loc2 + loc3;
   h_obj[0][1][1] = -A[0] - loc4;
   h_obj[1][1][1] =  A[0] - loc4;
   h_obj[2][1][1] = 2.0*loc2 - loc3;
   h_obj[3][1][1] = 3.0*loc3;
   loc2 = isqrt3*A[5];
   loc3 = isqrt6*A[9];
   h_obj[4][1][1] = A[1] - loc2 - loc3;
   h_obj[5][1][1] = 2.0*loc2 - loc3;
   h_obj[6][1][1] = 3.0*loc3;
   loc3 = isqrt6*A[10];
   h_obj[7][1][1] = tisqrt3*A[6] - loc3;
   h_obj[8][1][1] = 3.0*loc3;
   h_obj[9][1][1] = tisqrt6*A[11];
   /* Third off-diagonal block */
   loc2 = matr[2]*loc1;
   J_B[1] += loc2;
   J_B[3] -= loc2;
   loc2 = matr[1]*loc1;
   J_B[2] -= loc2;
   J_B[6] += loc2;
   loc2 = matr[0]*loc1;
   J_B[5] += loc2;
   J_B[7] -= loc2;
   loc2 = isqrt3*J_B[3];
   loc3 = isqrt6*J_B[6];
   loc4 = loc2 + loc3;
   A[0] = -J_B[0] - loc4;
   A[1] =  J_B[0] - loc4;
   A[2] = 2.0*loc2 - loc3;
   A[3] = 3.0*loc3;
   loc2 = isqrt3*J_B[4];
   loc3 = isqrt6*J_B[7];
   loc4 = loc2 + loc3;
   A[4] = -J_B[1] - loc4;
   A[5] =  J_B[1] - loc4;
   A[6] = 2.0*loc2 - loc3;
   A[7] = 3.0*loc3;
   loc2 = isqrt3*J_B[5];
   loc3 = isqrt6*J_B[8];
   loc4 = loc2 + loc3;
   A[8] = -J_B[2] - loc4;
   A[9] =  J_B[2] - loc4;
   A[10] = 2.0*loc2 - loc3;
   A[11] = 3.0*loc3;
   loc2 = isqrt3*A[4];
   loc3 = isqrt6*A[8];
   loc4 = loc2 + loc3;
   h_obj[0][1][2] = -A[0] - loc4;
   h_obj[1][1][2] =  A[0] - loc4;
   h_obj[2][1][2] = 2.0*loc2 - loc3;
   h_obj[3][1][2] = 3.0*loc3;
   loc2 = isqrt3*A[5];
   loc3 = isqrt6*A[9];
   loc4 = loc2 + loc3;
   h_obj[1][2][1] = -A[1] - loc4;
   h_obj[4][1][2] =  A[1] - loc4;
   h_obj[5][1][2] = 2.0*loc2 - loc3;
   h_obj[6][1][2] = 3.0*loc3;
   loc2 = isqrt3*A[6];
   loc3 = isqrt6*A[10];
   loc4 = loc2 + loc3;
   h_obj[2][2][1] = -A[2] - loc4;
   h_obj[5][2][1] =  A[2] - loc4;
   h_obj[7][1][2] = 2.0*loc2 - loc3;
   h_obj[8][1][2] = 3.0*loc3;
   loc2 = isqrt3*A[7];
   loc3 = isqrt6*A[11];
   loc4 = loc2 + loc3;
   h_obj[3][2][1] = -A[3] - loc4;
   h_obj[6][2][1] =  A[3] - loc4;
   h_obj[8][2][1] = 2.0*loc2 - loc3;
   h_obj[9][1][2] = 3.0*loc3;
   /* Third block of rows */
   loc3 = matr[6]*f + dg[6]*cross;
   loc4 = dg[6]*g + matr[6]*cross;
   J_A[0] = loc0 + loc3*matr[6] + loc4*dg[6];
   J_A[1] = loc3*matr[7] + loc4*dg[7];
   J_A[2] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[7]*f + dg[7]*cross;
   loc4 = dg[7]*g + matr[7]*cross;
   J_A[3] = loc0 + loc3*matr[7] + loc4*dg[7];
   J_A[4] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[8]*f + dg[8]*cross;
   loc4 = dg[8]*g + matr[8]*cross;
   J_A[5] = loc0 + loc3*matr[8] + loc4*dg[8];
   /* Third diagonal block */
   loc2 = isqrt3*J_A[1];
   loc3 = isqrt6*J_A[2];
   loc4 = loc2 + loc3;
   A[0] = -J_A[0] - loc4;
   A[1] =  J_A[0] - loc4;
   loc2 = isqrt3*J_A[3];
   loc3 = isqrt6*J_A[4];
   loc4 = loc2 + loc3;
   A[4] = -J_A[1] - loc4;
   A[5] =  J_A[1] - loc4;
   A[6] = 2.0*loc2 - loc3;
   loc2 = isqrt3*J_A[4];
   loc3 = isqrt6*J_A[5];
   loc4 = loc2 + loc3;
   A[8] = -J_A[2] - loc4;
   A[9] =  J_A[2] - loc4;
   A[10] = 2.0*loc2 - loc3;
   A[11] = 3.0*loc3;
   loc2 = isqrt3*A[4];
   loc3 = isqrt6*A[8];
   loc4 = loc2 + loc3;
   h_obj[0][2][2] = -A[0] - loc4;
   h_obj[1][2][2] =  A[0] - loc4;
   h_obj[2][2][2] = 2.0*loc2 - loc3;
   h_obj[3][2][2] = 3.0*loc3;
   loc2 = isqrt3*A[5];
   loc3 = isqrt6*A[9];
   h_obj[4][2][2] = A[1] - loc2 - loc3;
   h_obj[5][2][2] = 2.0*loc2 - loc3;
   h_obj[6][2][2] = 3.0*loc3;
   loc3 = isqrt6*A[10];
   h_obj[7][2][2] = tisqrt3*A[6] - loc3;
   h_obj[8][2][2] = 3.0*loc3;
   h_obj[9][2][2] = tisqrt6*A[11];
   // completes diagonal blocks.
   h_obj[0].fill_lower_triangle();
   h_obj[4].fill_lower_triangle();
   h_obj[7].fill_lower_triangle();
   h_obj[9].fill_lower_triangle();
   return true;
 }
bool h_fcn_3e_v0 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 1805 of file includeLinks/MeanRatioFunctions.hpp.
References h_fcn_3e_v3().
 {
   static Vector3D my_x[4];
   my_x[0] = x[1];
   my_x[1] = x[3];
   my_x[2] = x[2];
   my_x[3] = x[0];
   return h_fcn_3e_v3(obj, g_obj, h_obj, my_x, a, b, c);
 }
bool h_fcn_3e_v1 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 1818 of file includeLinks/MeanRatioFunctions.hpp.
References h_fcn_3e_v3().
 {
   static Vector3D my_x[4];
   my_x[0] = x[0];
   my_x[1] = x[2];
   my_x[2] = x[3];
   my_x[3] = x[1];
   return h_fcn_3e_v3(obj, g_obj, h_obj, my_x, a, b, c);
 }
bool h_fcn_3e_v2 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 1831 of file includeLinks/MeanRatioFunctions.hpp.
References h_fcn_3e_v3().
 {
   static Vector3D my_x[4];
   my_x[0] = x[1];
   my_x[1] = x[0];
   my_x[2] = x[3];
   my_x[3] = x[2];
   return h_fcn_3e_v3(obj, g_obj, h_obj, my_x, a, b, c);
 }
bool h_fcn_3e_v3 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 1717 of file includeLinks/MeanRatioFunctions.hpp.
References nvc::cross(), Matrix3D::fill_lower_triangle(), isqrt3, isqrt6, MSQ_MIN, pow(), and tisqrt6.
Referenced by h_fcn_3e_v0(), h_fcn_3e_v1(), and h_fcn_3e_v2().
 {
   double matr[9], f, g;
   double dg[9], loc0, loc1, loc3, loc4;
   double cross;
   /* Calculate M = A*inv(W). */
   f       = x[1][0] + x[0][0];
   matr[0] = x[1][0] - x[0][0];
   matr[1] = (2.0*x[2][0] - f)*isqrt3;
   matr[2] = (3.0*x[3][0] - x[2][0] - f)*isqrt6;
   f       = x[1][1] + x[0][1];
   matr[3] = x[1][1] - x[0][1];
   matr[4] = (2.0*x[2][1] - f)*isqrt3;
   matr[5] = (3.0*x[3][1] - x[2][1] - f)*isqrt6;
   f       = x[1][2] + x[0][2];
   matr[6] = x[1][2] - x[0][2];
   matr[7] = (2.0*x[2][2] - f)*isqrt3;
   matr[8] = (3.0*x[3][2] - x[2][2] - f)*isqrt6;
   /* Calculate det(M). */
   dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
   dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
   dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
   g = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] + matr[2]*matr[2] +
       matr[3]*matr[3] + matr[4]*matr[4] + matr[5]*matr[5] +
       matr[6]*matr[6] + matr[7]*matr[7] + matr[8]*matr[8];
   loc3 = f;
   loc4 = g;
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
   dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
   g_obj[0] = tisqrt6*(matr[2]*f + dg[2]*g);
   g_obj[1] = tisqrt6*(matr[5]*f + dg[5]*g);
   g_obj[2] = tisqrt6*(matr[8]*f + dg[8]*g);
   /* Calculate the hessian of the objective.                   */
   loc0 = f;                     /* Constant on nabla^2 f       */
   loc1 = g;                     /* Constant on nabla^2 g       */
   cross = f * c / loc4;         /* Constant on nabla g nabla f */
   f = f * (b-1) / loc3;         /* Constant on nabla f nabla f */
   g = g * (c-1) / loc4;         /* Constant on nabla g nabla g */
   f *= 2.0;                     /* Modification for nabla f    */
   /* First block of rows */
   loc3 = matr[2]*f + dg[2]*cross;
   loc4 = dg[2]*g + matr[2]*cross;
   h_obj[0][0] = 1.5*(loc0 + loc3*matr[2] + loc4*dg[2]);
   h_obj[0][1] = 1.5*(loc3*matr[5] + loc4*dg[5]);
   h_obj[0][2] = 1.5*(loc3*matr[8] + loc4*dg[8]);
   /* Second block of rows */
   loc3 = matr[5]*f + dg[5]*cross;
   loc4 = dg[5]*g + matr[5]*cross;
   h_obj[1][1] = 1.5*(loc0 + loc3*matr[5] + loc4*dg[5]);
   h_obj[1][2] = 1.5*(loc3*matr[8] + loc4*dg[8]);
   /* Third block of rows */
   loc3 = matr[8]*f + dg[8]*cross;
   loc4 = dg[8]*g + matr[8]*cross;
   h_obj[2][2] = 1.5*(loc0 + loc3*matr[8] + loc4*dg[8]);
   // completes diagonal block.
   h_obj.fill_lower_triangle();
   return true;
 }
int h_fcn_3i (double & obj, Vector3D g_obj[4], Matrix3D h_obj[10], const Vector3D x[4], const double a, const Exponent & b, const Exponent & c, const Vector3D & d) inline
Definition at line 1973 of file includeLinks/MeanRatioFunctions.hpp.
References A, nvc::cross(), Matrix3D::fill_lower_triangle(), MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), and IdealWeightMeanRatio::compute_element_analytical_hessian().
 {
   double matr[9], f;
   double adj_m[9], g;
   double dg[9], loc0, loc1, loc2, loc3, loc4;
   double A[3], J_A[6], J_B[9], J_C[9], cross;
   const double scale[6] = {
     d[0]*d[0], d[0]*d[1], d[0]*d[2],
     d[1]*d[1], d[1]*d[2],
     d[2]*d[2]
   };
   /* Calculate M = A*inv(W). */
   matr[0] = d[0]*(x[1][0] - x[0][0]);
   matr[1] = d[1]*(x[2][0] - x[0][0]);
   matr[2] = d[2]*(x[3][0] - x[0][0]);
   matr[3] = d[0]*(x[1][1] - x[0][1]);
   matr[4] = d[1]*(x[2][1] - x[0][1]);
   matr[5] = d[2]*(x[3][1] - x[0][1]);
   matr[6] = d[0]*(x[1][2] - x[0][2]);
   matr[7] = d[1]*(x[2][2] - x[0][2]);
   matr[8] = d[2]*(x[3][2] - x[0][2]);
   /* Calculate det(M). */
   dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
   dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
   dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
   g = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] + matr[2]*matr[2] +
     matr[3]*matr[3] + matr[4]*matr[4] + matr[5]*matr[5] +
     matr[6]*matr[6] + matr[7]*matr[7] + matr[8]*matr[8];
   loc3 = f;
   loc4 = g;
   /* Calculate objective function. */
   obj  = a * pow(f, b) * pow(g, c);
   /* Calculate the derivative of the objective function.    */
   f = b * obj / f;              /* Constant on nabla f      */
   g = c * obj / g;              /* Constant on nable g      */
   f *= 2.0;                     /* Modification for nabla f */
   dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
   dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
   dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
   dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
   dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
   dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
   adj_m[0] = d[0]*(matr[0]*f + dg[0]*g);
   adj_m[1] = d[1]*(matr[1]*f + dg[1]*g);
   adj_m[2] = d[2]*(matr[2]*f + dg[2]*g);
   adj_m[3] = d[0]*(matr[3]*f + dg[3]*g);
   adj_m[4] = d[1]*(matr[4]*f + dg[4]*g);
   adj_m[5] = d[2]*(matr[5]*f + dg[5]*g);
   adj_m[6] = d[0]*(matr[6]*f + dg[6]*g);
   adj_m[7] = d[1]*(matr[7]*f + dg[7]*g);
   adj_m[8] = d[2]*(matr[8]*f + dg[8]*g);
   g_obj[0][0] = -adj_m[0] - adj_m[1] - adj_m[2];
   g_obj[1][0] =  adj_m[0];
   g_obj[2][0] =  adj_m[1];
   g_obj[3][0] =  adj_m[2];
   g_obj[0][1] = -adj_m[3] - adj_m[4] - adj_m[5];
   g_obj[1][1] =  adj_m[3];
   g_obj[2][1] =  adj_m[4];
   g_obj[3][1] =  adj_m[5];
   g_obj[0][2] = -adj_m[6] - adj_m[7] - adj_m[8];
   g_obj[1][2] =  adj_m[6];
   g_obj[2][2] =  adj_m[7];
   g_obj[3][2] =  adj_m[8];
   /* Calculate the hessian of the objective.                   */
   loc0 = f;                     /* Constant on nabla^2 f       */
   loc1 = g;                     /* Constant on nabla^2 g       */
   cross = f * c / loc4;         /* Constant on nabla g nabla f */
   f = f * (b-1) / loc3;         /* Constant on nabla f nabla f */
   g = g * (c-1) / loc4;         /* Constant on nabla g nabla g */
   f *= 2.0;                     /* Modification for nabla f    */
   /* First block of rows */
   loc3 = matr[0]*f + dg[0]*cross;
   loc4 = dg[0]*g + matr[0]*cross;
   J_A[0] = loc0 + loc3*matr[0] + loc4*dg[0];
   J_A[1] = loc3*matr[1] + loc4*dg[1];
   J_A[2] = loc3*matr[2] + loc4*dg[2];
   J_B[0] = loc3*matr[3] + loc4*dg[3];
   J_B[1] = loc3*matr[4] + loc4*dg[4];
   J_B[2] = loc3*matr[5] + loc4*dg[5];
   J_C[0] = loc3*matr[6] + loc4*dg[6];
   J_C[1] = loc3*matr[7] + loc4*dg[7];
   J_C[2] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[1]*f + dg[1]*cross;
   loc4 = dg[1]*g + matr[1]*cross;
   J_A[3] = loc0 + loc3*matr[1] + loc4*dg[1];
   J_A[4] = loc3*matr[2] + loc4*dg[2];
   J_B[3] = loc3*matr[3] + loc4*dg[3];
   J_B[4] = loc3*matr[4] + loc4*dg[4];
   J_B[5] = loc3*matr[5] + loc4*dg[5];
   J_C[3] = loc3*matr[6] + loc4*dg[6];
   J_C[4] = loc3*matr[7] + loc4*dg[7];
   J_C[5] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[2]*f + dg[2]*cross;
   loc4 = dg[2]*g + matr[2]*cross;
   J_A[5] = loc0 + loc3*matr[2] + loc4*dg[2];
   J_B[6] = loc3*matr[3] + loc4*dg[3];
   J_B[7] = loc3*matr[4] + loc4*dg[4];
   J_B[8] = loc3*matr[5] + loc4*dg[5];
   J_C[6] = loc3*matr[6] + loc4*dg[6];
   J_C[7] = loc3*matr[7] + loc4*dg[7];
   J_C[8] = loc3*matr[8] + loc4*dg[8];
   /* First diagonal block */
   J_A[0] *= scale[0];
   J_A[1] *= scale[1];
   J_A[2] *= scale[2];
   J_A[3] *= scale[3];
   J_A[4] *= scale[4];
   J_A[5] *= scale[5];
   A[0] = -J_A[0] - J_A[1] - J_A[2];
   A[1] = -J_A[1] - J_A[3] - J_A[4];
   A[2] = -J_A[2] - J_A[4] - J_A[5];
   h_obj[0][0][0] = -A[0] - A[1] - A[2];
   h_obj[1][0][0] =  A[0];
   h_obj[2][0][0] =  A[1];
   h_obj[3][0][0] =  A[2];
   h_obj[4][0][0] = J_A[0];
   h_obj[5][0][0] = J_A[1];
   h_obj[6][0][0] = J_A[2];
   h_obj[7][0][0] = J_A[3];
   h_obj[8][0][0] = J_A[4];
   h_obj[9][0][0] = J_A[5];
   /* First off-diagonal block */
   loc2 = matr[8]*loc1;
   J_B[1] += loc2;
   J_B[3] -= loc2;
   loc2 = matr[7]*loc1;
   J_B[2] -= loc2;
   J_B[6] += loc2;
   loc2 = matr[6]*loc1;
   J_B[5] += loc2;
   J_B[7] -= loc2;
   J_B[0] *= scale[0];
   J_B[1] *= scale[1];
   J_B[2] *= scale[2];
   J_B[3] *= scale[1];
   J_B[4] *= scale[3];
   J_B[5] *= scale[4];
   J_B[6] *= scale[2];
   J_B[7] *= scale[4];
   J_B[8] *= scale[5];
   A[0] = -J_B[0] - J_B[3] - J_B[6];
   A[1] = -J_B[1] - J_B[4] - J_B[7];
   A[2] = -J_B[2] - J_B[5] - J_B[8];
   h_obj[0][0][1] = -A[0] - A[1] - A[2];
   h_obj[1][0][1] =  A[0];
   h_obj[2][0][1] =  A[1];
   h_obj[3][0][1] =  A[2];
   h_obj[1][1][0] = -J_B[0] - J_B[1] - J_B[2];
   h_obj[4][0][1] =  J_B[0];
   h_obj[5][0][1] =  J_B[1];
   h_obj[6][0][1] =  J_B[2];
   h_obj[2][1][0] = -J_B[3] - J_B[4] - J_B[5];
   h_obj[5][1][0] =  J_B[3];
   h_obj[7][0][1] =  J_B[4];
   h_obj[8][0][1] =  J_B[5];
   h_obj[3][1][0] = -J_B[6] - J_B[7] - J_B[8];
   h_obj[6][1][0] =  J_B[6];
   h_obj[8][1][0] =  J_B[7];
   h_obj[9][0][1] =  J_B[8];
   /* Second off-diagonal block */
   loc2 = matr[5]*loc1;
   J_C[1] -= loc2;
   J_C[3] += loc2;
   loc2 = matr[4]*loc1;
   J_C[2] += loc2;
   J_C[6] -= loc2;
   loc2 = matr[3]*loc1;
   J_C[5] -= loc2;
   J_C[7] += loc2;
   J_C[0] *= scale[0];
   J_C[1] *= scale[1];
   J_C[2] *= scale[2];
   J_C[3] *= scale[1];
   J_C[4] *= scale[3];
   J_C[5] *= scale[4];
   J_C[6] *= scale[2];
   J_C[7] *= scale[4];
   J_C[8] *= scale[5];
   A[0] = -J_C[0] - J_C[3] - J_C[6];
   A[1] = -J_C[1] - J_C[4] - J_C[7];
   A[2] = -J_C[2] - J_C[5] - J_C[8];
   h_obj[0][0][2] = -A[0] - A[1] - A[2];
   h_obj[1][0][2] =  A[0];
   h_obj[2][0][2] =  A[1];
   h_obj[3][0][2] =  A[2];
   h_obj[1][2][0] = -J_C[0] - J_C[1] - J_C[2];
   h_obj[4][0][2] =  J_C[0];
   h_obj[5][0][2] =  J_C[1];
   h_obj[6][0][2] =  J_C[2];
   h_obj[2][2][0] = -J_C[3] - J_C[4] - J_C[5];
   h_obj[5][2][0] =  J_C[3];
   h_obj[7][0][2] =  J_C[4];
   h_obj[8][0][2] =  J_C[5];
   h_obj[3][2][0] = -J_C[6] - J_C[7] - J_C[8];
   h_obj[6][2][0] =  J_C[6];
   h_obj[8][2][0] =  J_C[7];
   h_obj[9][0][2] =  J_C[8];
   /* Second block of rows */
   loc3 = matr[3]*f + dg[3]*cross;
   loc4 = dg[3]*g + matr[3]*cross;
   J_A[0] = loc0 + loc3*matr[3] + loc4*dg[3];
   J_A[1] = loc3*matr[4] + loc4*dg[4];
   J_A[2] = loc3*matr[5] + loc4*dg[5];
   J_B[0] = loc3*matr[6] + loc4*dg[6];
   J_B[1] = loc3*matr[7] + loc4*dg[7];
   J_B[2] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[4]*f + dg[4]*cross;
   loc4 = dg[4]*g + matr[4]*cross;
   J_A[3] = loc0 + loc3*matr[4] + loc4*dg[4];
   J_A[4] = loc3*matr[5] + loc4*dg[5];
   J_B[3] = loc3*matr[6] + loc4*dg[6];
   J_B[4] = loc3*matr[7] + loc4*dg[7];
   J_B[5] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[5]*f + dg[5]*cross;
   loc4 = dg[5]*g + matr[5]*cross;
   J_A[5] = loc0 + loc3*matr[5] + loc4*dg[5];
   J_B[6] = loc3*matr[6] + loc4*dg[6];
   J_B[7] = loc3*matr[7] + loc4*dg[7];
   J_B[8] = loc3*matr[8] + loc4*dg[8];
   /* Second diagonal block */
   J_A[0] *= scale[0];
   J_A[1] *= scale[1];
   J_A[2] *= scale[2];
   J_A[3] *= scale[3];
   J_A[4] *= scale[4];
   J_A[5] *= scale[5];
   A[0] = -J_A[0] - J_A[1] - J_A[2];
   A[1] = -J_A[1] - J_A[3] - J_A[4];
   A[2] = -J_A[2] - J_A[4] - J_A[5];
   h_obj[0][1][1] = -A[0] - A[1] - A[2];
   h_obj[1][1][1] =  A[0];
   h_obj[2][1][1] =  A[1];
   h_obj[3][1][1] =  A[2];
   h_obj[4][1][1] = J_A[0];
   h_obj[5][1][1] = J_A[1];
   h_obj[6][1][1] = J_A[2];
   h_obj[7][1][1] = J_A[3];
   h_obj[8][1][1] = J_A[4];
   h_obj[9][1][1] = J_A[5];
   /* Third off-diagonal block */
   loc2 = matr[2]*loc1;
   J_B[1] += loc2;
   J_B[3] -= loc2;
   loc2 = matr[1]*loc1;
   J_B[2] -= loc2;
   J_B[6] += loc2;
   loc2 = matr[0]*loc1;
   J_B[5] += loc2;
   J_B[7] -= loc2;
   J_B[0] *= scale[0];
   J_B[1] *= scale[1];
   J_B[2] *= scale[2];
   J_B[3] *= scale[1];
   J_B[4] *= scale[3];
   J_B[5] *= scale[4];
   J_B[6] *= scale[2];
   J_B[7] *= scale[4];
   J_B[8] *= scale[5];
   A[0] = -J_B[0] - J_B[3] - J_B[6];
   A[1] = -J_B[1] - J_B[4] - J_B[7];
   A[2] = -J_B[2] - J_B[5] - J_B[8];
   h_obj[0][1][2] = -A[0] - A[1] - A[2];
   h_obj[1][1][2] =  A[0];
   h_obj[2][1][2] =  A[1];
   h_obj[3][1][2] =  A[2];
   h_obj[1][2][1] = -J_B[0] - J_B[1] - J_B[2];
   h_obj[4][1][2] =  J_B[0];
   h_obj[5][1][2] =  J_B[1];
   h_obj[6][1][2] =  J_B[2];
   h_obj[2][2][1] = -J_B[3] - J_B[4] - J_B[5];
   h_obj[5][2][1] =  J_B[3];
   h_obj[7][1][2] =  J_B[4];
   h_obj[8][1][2] =  J_B[5];
   h_obj[3][2][1] = -J_B[6] - J_B[7] - J_B[8];
   h_obj[6][2][1] =  J_B[6];
   h_obj[8][2][1] =  J_B[7];
   h_obj[9][1][2] =  J_B[8];
   /* Third block of rows */
   loc3 = matr[6]*f + dg[6]*cross;
   loc4 = dg[6]*g + matr[6]*cross;
   J_A[0] = loc0 + loc3*matr[6] + loc4*dg[6];
   J_A[1] = loc3*matr[7] + loc4*dg[7];
   J_A[2] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[7]*f + dg[7]*cross;
   loc4 = dg[7]*g + matr[7]*cross;
   J_A[3] = loc0 + loc3*matr[7] + loc4*dg[7];
   J_A[4] = loc3*matr[8] + loc4*dg[8];
   loc3 = matr[8]*f + dg[8]*cross;
   loc4 = dg[8]*g + matr[8]*cross;
   J_A[5] = loc0 + loc3*matr[8] + loc4*dg[8];
   /* Third diagonal block */
   J_A[0] *= scale[0];
   J_A[1] *= scale[1];
   J_A[2] *= scale[2];
   J_A[3] *= scale[3];
   J_A[4] *= scale[4];
   J_A[5] *= scale[5];
   A[0] = -J_A[0] - J_A[1] - J_A[2];
   A[1] = -J_A[1] - J_A[3] - J_A[4];
   A[2] = -J_A[2] - J_A[4] - J_A[5];
   h_obj[0][2][2] = -A[0] - A[1] - A[2];
   h_obj[1][2][2] =  A[0];
   h_obj[2][2][2] =  A[1];
   h_obj[3][2][2] =  A[2];
   h_obj[4][2][2] = J_A[0];
   h_obj[5][2][2] = J_A[1];
   h_obj[6][2][2] = J_A[2];
   h_obj[7][2][2] = J_A[3];
   h_obj[8][2][2] = J_A[4];
   h_obj[9][2][2] = J_A[5];
   // completes diagonal blocks.
   h_obj[0].fill_lower_triangle();
   h_obj[4].fill_lower_triangle();
   h_obj[7].fill_lower_triangle();
   h_obj[9].fill_lower_triangle();
   return true;
 }
bool h_gdft_2 (double & obj, Vector3D g_obj[3], Matrix3D h_obj[6], const Vector3D x[3], const Vector3D & n, const Matrix3D & invR, const Matrix3D & Q, const double alpha = 0.5, const Exponent & gamma = 1.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 310 of file includeLinks/I_DFTFamilyFunctions.hpp.
References A, Matrix3D::fill_lower_triangle(), MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_hessian().
   {
     double matr[9], f, t1, t2;
     double matd[9], g, t3, loc1;
     double adjm[9], dg[9], dobj_df, dobj_dfdg, dobj_dg, dobj_dgdg;
     double J_A[6], J_B[10], J_C[10], J_D[6], J_E[10], J_F[6];
     double A[9];
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + n[0]*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + n[1]*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + n[2]*invR[2][2];
     /* Calculate det(M). */
     dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
     dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
     dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
     dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
     dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
     dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
     dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
     dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
     dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
     t1 = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = t1*t1 + 4.0*delta*delta;
     t3 = sqrt(t2);
     g = t1 + t3;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc1 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc1;
     /* Calculate the derivative of the objective function. */
     t3 = 1.0 / t3;
     dobj_df = 2.0 * loc1;
     dobj_dg = -gamma * obj * t3;
     dobj_dfdg = -gamma * dobj_df * t3;
     dobj_dgdg = dobj_dg * ((-gamma - 1.0)*t3 + 4.0*delta*delta/(t2*g));
     /* Calculate adjoint matrix */
     adjm[0] = dobj_df*matd[0] + dobj_dg*dg[0];
     adjm[1] = dobj_df*matd[1] + dobj_dg*dg[1];
     adjm[2] = dobj_df*matd[2] + dobj_dg*dg[2];
     adjm[3] = dobj_df*matd[3] + dobj_dg*dg[3];
     adjm[4] = dobj_df*matd[4] + dobj_dg*dg[4];
     adjm[5] = dobj_df*matd[5] + dobj_dg*dg[5];
     adjm[6] = dobj_df*matd[6] + dobj_dg*dg[6];
     adjm[7] = dobj_df*matd[7] + dobj_dg*dg[7];
     adjm[8] = dobj_df*matd[8] + dobj_dg*dg[8];
     /* Construct gradients */
     g_obj[1][0] = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[2][0] =                    invR[1][1]*adjm[1]+invR[1][2]*adjm[2];
     g_obj[0][0] = -g_obj[1][0] - g_obj[2][0];
     g_obj[1][1] = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[2][1] =                    invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     g_obj[0][1] = -g_obj[1][1] - g_obj[2][1];
     g_obj[1][2] = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     g_obj[2][2] =                    invR[1][1]*adjm[7]+invR[1][2]*adjm[8];
     g_obj[0][2] = -g_obj[1][2] - g_obj[2][2];
     /* Start of the Hessian evaluation */
     adjm[0] = dobj_dg*matr[0]; matd[0] *= dobj_dfdg;
     adjm[1] = dobj_dg*matr[1]; matd[1] *= dobj_dfdg;
     adjm[2] = dobj_dg*matr[2]; matd[2] *= dobj_dfdg;
     adjm[3] = dobj_dg*matr[3]; matd[3] *= dobj_dfdg;
     adjm[4] = dobj_dg*matr[4]; matd[4] *= dobj_dfdg;
     adjm[5] = dobj_dg*matr[5]; matd[5] *= dobj_dfdg;
     adjm[6] = dobj_dg*matr[6]; matd[6] *= dobj_dfdg;
     adjm[7] = dobj_dg*matr[7]; matd[7] *= dobj_dfdg;
     adjm[8] = dobj_dg*matr[8]; matd[8] *= dobj_dfdg;
     /* Blocks for the Hessian construction */
     loc1 = dobj_dgdg*dg[0] + matd[0];
     J_A[0] = dobj_df + dg[0]*(matd[0] + loc1);
     J_A[1] = dg[0]*matd[1] + loc1*dg[1];
     J_A[2] = dg[0]*matd[2] + loc1*dg[2];
     J_B[0] = dg[0]*matd[3] + loc1*dg[3];
     J_B[1] = dg[0]*matd[4] + loc1*dg[4] + adjm[8];
     J_B[2] = dg[0]*matd[5] + loc1*dg[5] - adjm[7];
     J_C[0] = dg[0]*matd[6] + loc1*dg[6];
     J_C[1] = dg[0]*matd[7] + loc1*dg[7] - adjm[5];
     J_C[2] = dg[0]*matd[8] + loc1*dg[8] + adjm[4];
     loc1 = dobj_dgdg*dg[1] + matd[1];
     J_A[3] = dobj_df + dg[1]*(matd[1] + loc1);
     J_A[4] = dg[1]*matd[2] + loc1*dg[2];
     J_B[3] = dg[1]*matd[3] + loc1*dg[3] - adjm[8];
     J_B[4] = dg[1]*matd[4] + loc1*dg[4];
     J_B[5] = dg[1]*matd[5] + loc1*dg[5] + adjm[6];
     J_C[3] = dg[1]*matd[6] + loc1*dg[6] + adjm[5];
     J_C[4] = dg[1]*matd[7] + loc1*dg[7];
     J_C[5] = dg[1]*matd[8] + loc1*dg[8] - adjm[3];
     loc1 = dobj_dgdg*dg[2] + matd[2];
     J_A[5] = dobj_df + dg[2]*(matd[2] + loc1);
     J_B[6] = dg[2]*matd[3] + loc1*dg[3] + adjm[7];
     J_B[7] = dg[2]*matd[4] + loc1*dg[4] - adjm[6];
     J_B[8] = dg[2]*matd[5] + loc1*dg[5];
     J_C[6] = dg[2]*matd[6] + loc1*dg[6] - adjm[4];
     J_C[7] = dg[2]*matd[7] + loc1*dg[7] + adjm[3];
     J_C[8] = dg[2]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[3] + matd[3];
     J_D[0] = dobj_df + dg[3]*(matd[3] + loc1);
     J_D[1] = dg[3]*matd[4] + loc1*dg[4];
     J_D[2] = dg[3]*matd[5] + loc1*dg[5];
     J_E[0] = dg[3]*matd[6] + loc1*dg[6];
     J_E[1] = dg[3]*matd[7] + loc1*dg[7] + adjm[2];
     J_E[2] = dg[3]*matd[8] + loc1*dg[8] - adjm[1];
     loc1 = dobj_dgdg*dg[4] + matd[4];
     J_D[3] = dobj_df + dg[4]*(matd[4] + loc1);
     J_D[4] = dg[4]*matd[5] + loc1*dg[5];
     J_E[3] = dg[4]*matd[6] + loc1*dg[6] - adjm[2];
     J_E[4] = dg[4]*matd[7] + loc1*dg[7];
     J_E[5] = dg[4]*matd[8] + loc1*dg[8] + adjm[0];
     loc1 = dobj_dgdg*dg[5] + matd[5];
     J_D[5] = dobj_df + dg[5]*(matd[5] + loc1);
     J_E[6] = dg[5]*matd[6] + loc1*dg[6] + adjm[1];
     J_E[7] = dg[5]*matd[7] + loc1*dg[7] - adjm[0];
     J_E[8] = dg[5]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[6] + matd[6];
     J_F[0] = dobj_df + dg[6]*(matd[6] + loc1);
     J_F[1] = dg[6]*matd[7] + loc1*dg[7];
     J_F[2] = dg[6]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[7] + matd[7];
     J_F[3] = dobj_df + dg[7]*(matd[7] + loc1);
     J_F[4] = dg[7]*matd[8] + loc1*dg[8];
     J_F[5] = dobj_df + dg[8]*(2.0*matd[8] + dobj_dgdg*dg[8]);
     /* Assemble matrix products */
     /* dx / dx */
     A[1]  =  J_A[0]*invR[0][0] + J_A[1]*invR[0][1] + J_A[2]*invR[0][2];
     A[2]  =                      J_A[1]*invR[1][1] + J_A[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_A[1]*invR[0][0] + J_A[3]*invR[0][1] + J_A[4]*invR[0][2];
     A[5]  =                      J_A[3]*invR[1][1] + J_A[4]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_A[2]*invR[0][0] + J_A[4]*invR[0][1] + J_A[5]*invR[0][2];
     A[8]  =                      J_A[4]*invR[1][1] + J_A[5]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[1][0][0] =  A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[2][0][0] =                    A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[0][0][0] = -h_obj[1][0][0] - h_obj[2][0][0];
     h_obj[3][0][0] =  A[1]*invR[0][0] + A[4]*invR[0][1] + A[7]*invR[0][2];
     h_obj[4][0][0] =                    A[4]*invR[1][1] + A[7]*invR[1][2];
     h_obj[5][0][0] =                    A[5]*invR[1][1] + A[8]*invR[1][2];
     /* dx / dy */
     A[1]  =  J_B[0]*invR[0][0] + J_B[1]*invR[0][1] + J_B[2]*invR[0][2];
     A[2]  =                      J_B[1]*invR[1][1] + J_B[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_B[3]*invR[0][0] + J_B[4]*invR[0][1] + J_B[5]*invR[0][2];
     A[5]  =                      J_B[4]*invR[1][1] + J_B[5]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_B[6]*invR[0][0] + J_B[7]*invR[0][1] + J_B[8]*invR[0][2];
     A[8]  =                      J_B[7]*invR[1][1] + J_B[8]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[1][1][0] = A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[3][0][1] = A[1]*invR[0][0] + A[4]*invR[0][1] + A[7]*invR[0][2];
     h_obj[4][0][1] = A[2]*invR[0][0] + A[5]*invR[0][1] + A[8]*invR[0][2];
     h_obj[2][1][0] = A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[4][1][0] = A[4]*invR[1][1] + A[7]*invR[1][2];
     h_obj[5][0][1] = A[5]*invR[1][1] + A[8]*invR[1][2];
     h_obj[0][0][1] = -h_obj[1][1][0] - h_obj[2][1][0];
     h_obj[1][0][1] = -h_obj[3][0][1] - h_obj[4][1][0];
     h_obj[2][0][1] = -h_obj[4][0][1] - h_obj[5][0][1];
     /* dx / dz */
     A[1]  =  J_C[0]*invR[0][0] + J_C[1]*invR[0][1] + J_C[2]*invR[0][2];
     A[2]  =                      J_C[1]*invR[1][1] + J_C[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_C[3]*invR[0][0] + J_C[4]*invR[0][1] + J_C[5]*invR[0][2];
     A[5]  =                      J_C[4]*invR[1][1] + J_C[5]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_C[6]*invR[0][0] + J_C[7]*invR[0][1] + J_C[8]*invR[0][2];
     A[8]  =                      J_C[7]*invR[1][1] + J_C[8]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[1][2][0] = A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[3][0][2] = A[1]*invR[0][0] + A[4]*invR[0][1] + A[7]*invR[0][2];
     h_obj[4][0][2] = A[2]*invR[0][0] + A[5]*invR[0][1] + A[8]*invR[0][2];
     h_obj[2][2][0] = A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[4][2][0] = A[4]*invR[1][1] + A[7]*invR[1][2];
     h_obj[5][0][2] = A[5]*invR[1][1] + A[8]*invR[1][2];
     h_obj[0][0][2] = -h_obj[1][2][0] - h_obj[2][2][0];
     h_obj[1][0][2] = -h_obj[3][0][2] - h_obj[4][2][0];
     h_obj[2][0][2] = -h_obj[4][0][2] - h_obj[5][0][2];
     /* dy / dy */
     A[1]  =  J_D[0]*invR[0][0] + J_D[1]*invR[0][1] + J_D[2]*invR[0][2];
     A[2]  =                      J_D[1]*invR[1][1] + J_D[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_D[1]*invR[0][0] + J_D[3]*invR[0][1] + J_D[4]*invR[0][2];
     A[5]  =                      J_D[3]*invR[1][1] + J_D[4]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_D[2]*invR[0][0] + J_D[4]*invR[0][1] + J_D[5]*invR[0][2];
     A[8]  =                      J_D[4]*invR[1][1] + J_D[5]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[1][1][1] =  A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[2][1][1] =                    A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[0][1][1] = -h_obj[1][1][1] - h_obj[2][1][1];
     h_obj[3][1][1] =  A[1]*invR[0][0] + A[4]*invR[0][1] + A[7]*invR[0][2];
     h_obj[4][1][1] =                    A[4]*invR[1][1] + A[7]*invR[1][2];
     h_obj[5][1][1] =                    A[5]*invR[1][1] + A[8]*invR[1][2];
     /* dy / dz */
     A[1]  =  J_E[0]*invR[0][0] + J_E[1]*invR[0][1] + J_E[2]*invR[0][2];
     A[2]  =                      J_E[1]*invR[1][1] + J_E[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_E[3]*invR[0][0] + J_E[4]*invR[0][1] + J_E[5]*invR[0][2];
     A[5]  =                      J_E[4]*invR[1][1] + J_E[5]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_E[6]*invR[0][0] + J_E[7]*invR[0][1] + J_E[8]*invR[0][2];
     A[8]  =                      J_E[7]*invR[1][1] + J_E[8]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[1][2][1] = A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[3][1][2] = A[1]*invR[0][0] + A[4]*invR[0][1] + A[7]*invR[0][2];
     h_obj[4][1][2] = A[2]*invR[0][0] + A[5]*invR[0][1] + A[8]*invR[0][2];
     h_obj[2][2][1] = A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[4][2][1] = A[4]*invR[1][1] + A[7]*invR[1][2];
     h_obj[5][1][2] = A[5]*invR[1][1] + A[8]*invR[1][2];
     h_obj[0][1][2] = -h_obj[1][2][1] - h_obj[2][2][1];
     h_obj[1][1][2] = -h_obj[3][1][2] - h_obj[4][2][1];
     h_obj[2][1][2] = -h_obj[4][1][2] - h_obj[5][1][2];
     /* dz / dz */
     A[1]  =  J_F[0]*invR[0][0] + J_F[1]*invR[0][1] + J_F[2]*invR[0][2];
     A[2]  =                      J_F[1]*invR[1][1] + J_F[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_F[1]*invR[0][0] + J_F[3]*invR[0][1] + J_F[4]*invR[0][2];
     A[5]  =                      J_F[3]*invR[1][1] + J_F[4]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_F[2]*invR[0][0] + J_F[4]*invR[0][1] + J_F[5]*invR[0][2];
     A[8]  =                      J_F[4]*invR[1][1] + J_F[5]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[1][2][2] =  A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[2][2][2] =                    A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[0][2][2] = -h_obj[1][2][2] - h_obj[2][2][2];
     h_obj[3][2][2] =  A[1]*invR[0][0] + A[4]*invR[0][1] + A[7]*invR[0][2];
     h_obj[4][2][2] =                    A[4]*invR[1][1] + A[7]*invR[1][2];
     h_obj[5][2][2] =                    A[5]*invR[1][1] + A[8]*invR[1][2];
     /* Complete diagonal blocks */
     h_obj[0].fill_lower_triangle();
     h_obj[3].fill_lower_triangle();
     h_obj[5].fill_lower_triangle();
     return true;
   }
bool h_gdft_2_v0 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[3], const Vector3D & n, const Matrix3D & invR, const Matrix3D & Q, const double alpha = 0.5, const Exponent & gamma = 1.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 1497 of file includeLinks/I_DFTFamilyFunctions.hpp.
References A, Matrix3D::fill_lower_triangle(), MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_hessian().
   {
     double matr[9], f, t1, t2;
     double matd[9], g, t3, loc1;
     double adjm[9], dg[9], dobj_df, dobj_dfdg, dobj_dg, dobj_dgdg;
     double J_A[6], J_B[10], J_C[10], J_D[6], J_E[10], J_F[6];
     double A[9];
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + n[0]*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + n[1]*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + n[2]*invR[2][2];
     /* Calculate det(M). */
     dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
     dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
     dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
     dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
     dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
     dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
     dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
     dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
     dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
     t1 = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = t1*t1 + 4.0*delta*delta;
     t3 = sqrt(t2);
     g = t1 + t3;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc1 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc1;
     /* Calculate the derivative of the objective function. */
     t3 = 1.0 / t3;
     dobj_df = 2.0 * loc1;
     dobj_dg = -gamma * obj * t3;
     dobj_dfdg = -gamma * dobj_df * t3;
     dobj_dgdg = dobj_dg * ((-gamma - 1.0)*t3 + 4.0*delta*delta/(t2*g));
     /* Calculate adjoint matrix */
     adjm[0] = dobj_df*matd[0] + dobj_dg*dg[0];
     adjm[1] = dobj_df*matd[1] + dobj_dg*dg[1];
     adjm[2] = dobj_df*matd[2] + dobj_dg*dg[2];
     adjm[3] = dobj_df*matd[3] + dobj_dg*dg[3];
     adjm[4] = dobj_df*matd[4] + dobj_dg*dg[4];
     adjm[5] = dobj_df*matd[5] + dobj_dg*dg[5];
     adjm[6] = dobj_df*matd[6] + dobj_dg*dg[6];
     adjm[7] = dobj_df*matd[7] + dobj_dg*dg[7];
     adjm[8] = dobj_df*matd[8] + dobj_dg*dg[8];
     /* Construct gradients */
     g_obj[0]  = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[0] +=                    invR[1][1]*adjm[1]+invR[1][2]*adjm[2];
     g_obj[0]  = -g_obj[0];
     g_obj[1]  = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[1] +=                    invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     g_obj[1]  = -g_obj[1];
     g_obj[2]  = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     g_obj[2] +=                    invR[1][1]*adjm[7]+invR[1][2]*adjm[8];
     g_obj[2]  = -g_obj[2];
     /* Start of the Hessian evaluation */
     adjm[0] = dobj_dg*matr[0]; matd[0] *= dobj_dfdg;
     adjm[1] = dobj_dg*matr[1]; matd[1] *= dobj_dfdg;
     adjm[2] = dobj_dg*matr[2]; matd[2] *= dobj_dfdg;
     adjm[3] = dobj_dg*matr[3]; matd[3] *= dobj_dfdg;
     adjm[4] = dobj_dg*matr[4]; matd[4] *= dobj_dfdg;
     adjm[5] = dobj_dg*matr[5]; matd[5] *= dobj_dfdg;
     adjm[6] = dobj_dg*matr[6]; matd[6] *= dobj_dfdg;
     adjm[7] = dobj_dg*matr[7]; matd[7] *= dobj_dfdg;
     adjm[8] = dobj_dg*matr[8]; matd[8] *= dobj_dfdg;
     /* Blocks for the Hessian construction */
     loc1 = dobj_dgdg*dg[0] + matd[0];
     J_A[0] = dobj_df + dg[0]*(matd[0] + loc1);
     J_A[1] = dg[0]*matd[1] + loc1*dg[1];
     J_A[2] = dg[0]*matd[2] + loc1*dg[2];
     J_B[0] = dg[0]*matd[3] + loc1*dg[3];
     J_B[1] = dg[0]*matd[4] + loc1*dg[4] + adjm[8];
     J_B[2] = dg[0]*matd[5] + loc1*dg[5] - adjm[7];
     J_C[0] = dg[0]*matd[6] + loc1*dg[6];
     J_C[1] = dg[0]*matd[7] + loc1*dg[7] - adjm[5];
     J_C[2] = dg[0]*matd[8] + loc1*dg[8] + adjm[4];
     loc1 = dobj_dgdg*dg[1] + matd[1];
     J_A[3] = dobj_df + dg[1]*(matd[1] + loc1);
     J_A[4] = dg[1]*matd[2] + loc1*dg[2];
     J_B[3] = dg[1]*matd[3] + loc1*dg[3] - adjm[8];
     J_B[4] = dg[1]*matd[4] + loc1*dg[4];
     J_B[5] = dg[1]*matd[5] + loc1*dg[5] + adjm[6];
     J_C[3] = dg[1]*matd[6] + loc1*dg[6] + adjm[5];
     J_C[4] = dg[1]*matd[7] + loc1*dg[7];
     J_C[5] = dg[1]*matd[8] + loc1*dg[8] - adjm[3];
     loc1 = dobj_dgdg*dg[2] + matd[2];
     J_A[5] = dobj_df + dg[2]*(matd[2] + loc1);
     J_B[6] = dg[2]*matd[3] + loc1*dg[3] + adjm[7];
     J_B[7] = dg[2]*matd[4] + loc1*dg[4] - adjm[6];
     J_B[8] = dg[2]*matd[5] + loc1*dg[5];
     J_C[6] = dg[2]*matd[6] + loc1*dg[6] - adjm[4];
     J_C[7] = dg[2]*matd[7] + loc1*dg[7] + adjm[3];
     J_C[8] = dg[2]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[3] + matd[3];
     J_D[0] = dobj_df + dg[3]*(matd[3] + loc1);
     J_D[1] = dg[3]*matd[4] + loc1*dg[4];
     J_D[2] = dg[3]*matd[5] + loc1*dg[5];
     J_E[0] = dg[3]*matd[6] + loc1*dg[6];
     J_E[1] = dg[3]*matd[7] + loc1*dg[7] + adjm[2];
     J_E[2] = dg[3]*matd[8] + loc1*dg[8] - adjm[1];
     loc1 = dobj_dgdg*dg[4] + matd[4];
     J_D[3] = dobj_df + dg[4]*(matd[4] + loc1);
     J_D[4] = dg[4]*matd[5] + loc1*dg[5];
     J_E[3] = dg[4]*matd[6] + loc1*dg[6] - adjm[2];
     J_E[4] = dg[4]*matd[7] + loc1*dg[7];
     J_E[5] = dg[4]*matd[8] + loc1*dg[8] + adjm[0];
     loc1 = dobj_dgdg*dg[5] + matd[5];
     J_D[5] = dobj_df + dg[5]*(matd[5] + loc1);
     J_E[6] = dg[5]*matd[6] + loc1*dg[6] + adjm[1];
     J_E[7] = dg[5]*matd[7] + loc1*dg[7] - adjm[0];
     J_E[8] = dg[5]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[6] + matd[6];
     J_F[0] = dobj_df + dg[6]*(matd[6] + loc1);
     J_F[1] = dg[6]*matd[7] + loc1*dg[7];
     J_F[2] = dg[6]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[7] + matd[7];
     J_F[3] = dobj_df + dg[7]*(matd[7] + loc1);
     J_F[4] = dg[7]*matd[8] + loc1*dg[8];
     J_F[5] = dobj_df + dg[8]*(2.0*matd[8] + dobj_dgdg*dg[8]);
     /* Assemble matrix products */
     /* dx / dx */
     A[1]  =  J_A[0]*invR[0][0] + J_A[1]*invR[0][1] + J_A[2]*invR[0][2];
     A[2]  =                      J_A[1]*invR[1][1] + J_A[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_A[1]*invR[0][0] + J_A[3]*invR[0][1] + J_A[4]*invR[0][2];
     A[5]  =                      J_A[3]*invR[1][1] + J_A[4]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_A[2]*invR[0][0] + J_A[4]*invR[0][1] + J_A[5]*invR[0][2];
     A[8]  =                      J_A[4]*invR[1][1] + J_A[5]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[0][0]  =  A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[0][0] +=                    A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[0][0]  = -h_obj[0][0];
     /* dx / dy */
     A[1]  =  J_B[0]*invR[0][0] + J_B[1]*invR[0][1] + J_B[2]*invR[0][2];
     A[2]  =                      J_B[1]*invR[1][1] + J_B[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_B[3]*invR[0][0] + J_B[4]*invR[0][1] + J_B[5]*invR[0][2];
     A[5]  =                      J_B[4]*invR[1][1] + J_B[5]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_B[6]*invR[0][0] + J_B[7]*invR[0][1] + J_B[8]*invR[0][2];
     A[8]  =                      J_B[7]*invR[1][1] + J_B[8]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[0][1]  = A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[0][1] +=                   A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[0][1]  = -h_obj[0][1];
     /* dx / dz */
     A[1]  =  J_C[0]*invR[0][0] + J_C[1]*invR[0][1] + J_C[2]*invR[0][2];
     A[2]  =                      J_C[1]*invR[1][1] + J_C[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_C[3]*invR[0][0] + J_C[4]*invR[0][1] + J_C[5]*invR[0][2];
     A[5]  =                      J_C[4]*invR[1][1] + J_C[5]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_C[6]*invR[0][0] + J_C[7]*invR[0][1] + J_C[8]*invR[0][2];
     A[8]  =                      J_C[7]*invR[1][1] + J_C[8]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[0][2]  = A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[0][2] +=                   A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[0][2]  = -h_obj[0][2];
     /* dy / dy */
     A[1]  =  J_D[0]*invR[0][0] + J_D[1]*invR[0][1] + J_D[2]*invR[0][2];
     A[2]  =                      J_D[1]*invR[1][1] + J_D[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_D[1]*invR[0][0] + J_D[3]*invR[0][1] + J_D[4]*invR[0][2];
     A[5]  =                      J_D[3]*invR[1][1] + J_D[4]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_D[2]*invR[0][0] + J_D[4]*invR[0][1] + J_D[5]*invR[0][2];
     A[8]  =                      J_D[4]*invR[1][1] + J_D[5]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[1][1]  =  A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[1][1] +=                    A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[1][1]  = -h_obj[1][1];
     /* dy / dz */
     A[1]  =  J_E[0]*invR[0][0] + J_E[1]*invR[0][1] + J_E[2]*invR[0][2];
     A[2]  =                      J_E[1]*invR[1][1] + J_E[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_E[3]*invR[0][0] + J_E[4]*invR[0][1] + J_E[5]*invR[0][2];
     A[5]  =                      J_E[4]*invR[1][1] + J_E[5]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_E[6]*invR[0][0] + J_E[7]*invR[0][1] + J_E[8]*invR[0][2];
     A[8]  =                      J_E[7]*invR[1][1] + J_E[8]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[1][2]  = A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[1][2] +=                   A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[1][2] = -h_obj[1][2];
     /* dz / dz */
     A[1]  =  J_F[0]*invR[0][0] + J_F[1]*invR[0][1] + J_F[2]*invR[0][2];
     A[2]  =                      J_F[1]*invR[1][1] + J_F[2]*invR[1][2];
     A[0]  = -A[1] - A[2];
     A[4]  =  J_F[1]*invR[0][0] + J_F[3]*invR[0][1] + J_F[4]*invR[0][2];
     A[5]  =                      J_F[3]*invR[1][1] + J_F[4]*invR[1][2];
     A[3]  = -A[4] - A[5];
     A[7]  =  J_F[2]*invR[0][0] + J_F[4]*invR[0][1] + J_F[5]*invR[0][2];
     A[8]  =                      J_F[4]*invR[1][1] + J_F[5]*invR[1][2];
     A[6]  = -A[7] - A[8];
     h_obj[2][2]  =  A[0]*invR[0][0] + A[3]*invR[0][1] + A[6]*invR[0][2];
     h_obj[2][2] +=                    A[3]*invR[1][1] + A[6]*invR[1][2];
     h_obj[2][2]  = -h_obj[2][2];
     /* Complete diagonal blocks */
     h_obj.fill_lower_triangle();
     return true;
   }
bool h_gdft_2_v1 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[3], const Vector3D & n, const Matrix3D & invR, const Matrix3D & Q, const double alpha = 0.5, const Exponent & gamma = 1.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 1785 of file includeLinks/I_DFTFamilyFunctions.hpp.
References A, Matrix3D::fill_lower_triangle(), MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_hessian().
   {
     double matr[9], f, t1, t2;
     double matd[9], g, t3, loc1;
     double adjm[9], dg[9], dobj_df, dobj_dfdg, dobj_dg, dobj_dgdg;
     double J_A[6], J_B[10], J_C[10], J_D[6], J_E[10], J_F[6];
     double A[3];
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + n[0]*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + n[1]*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + n[2]*invR[2][2];
     /* Calculate det(M). */
     dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
     dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
     dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
     dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
     dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
     dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
     dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
     dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
     dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
     t1 = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = t1*t1 + 4.0*delta*delta;
     t3 = sqrt(t2);
     g = t1 + t3;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc1 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc1;
     /* Calculate the derivative of the objective function. */
     t3 = 1.0 / t3;
     dobj_df = 2.0 * loc1;
     dobj_dg = -gamma * obj * t3;
     dobj_dfdg = -gamma * dobj_df * t3;
     dobj_dgdg = dobj_dg * ((-gamma - 1.0)*t3 + 4.0*delta*delta/(t2*g));
     /* Calculate adjoint matrix */
     adjm[0] = dobj_df*matd[0] + dobj_dg*dg[0];
     adjm[1] = dobj_df*matd[1] + dobj_dg*dg[1];
     adjm[2] = dobj_df*matd[2] + dobj_dg*dg[2];
     adjm[3] = dobj_df*matd[3] + dobj_dg*dg[3];
     adjm[4] = dobj_df*matd[4] + dobj_dg*dg[4];
     adjm[5] = dobj_df*matd[5] + dobj_dg*dg[5];
     adjm[6] = dobj_df*matd[6] + dobj_dg*dg[6];
     adjm[7] = dobj_df*matd[7] + dobj_dg*dg[7];
     adjm[8] = dobj_df*matd[8] + dobj_dg*dg[8];
     /* Construct gradients */
     g_obj[0] = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[1] = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[2] = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     /* Start of the Hessian evaluation */
     adjm[0] = dobj_dg*matr[0]; matd[0] *= dobj_dfdg;
     adjm[1] = dobj_dg*matr[1]; matd[1] *= dobj_dfdg;
     adjm[2] = dobj_dg*matr[2]; matd[2] *= dobj_dfdg;
     adjm[3] = dobj_dg*matr[3]; matd[3] *= dobj_dfdg;
     adjm[4] = dobj_dg*matr[4]; matd[4] *= dobj_dfdg;
     adjm[5] = dobj_dg*matr[5]; matd[5] *= dobj_dfdg;
     adjm[6] = dobj_dg*matr[6]; matd[6] *= dobj_dfdg;
     adjm[7] = dobj_dg*matr[7]; matd[7] *= dobj_dfdg;
     adjm[8] = dobj_dg*matr[8]; matd[8] *= dobj_dfdg;
     /* Blocks for the Hessian construction */
     loc1 = dobj_dgdg*dg[0] + matd[0];
     J_A[0] = dobj_df + dg[0]*(matd[0] + loc1);
     J_A[1] = dg[0]*matd[1] + loc1*dg[1];
     J_A[2] = dg[0]*matd[2] + loc1*dg[2];
     J_B[0] = dg[0]*matd[3] + loc1*dg[3];
     J_B[1] = dg[0]*matd[4] + loc1*dg[4] + adjm[8];
     J_B[2] = dg[0]*matd[5] + loc1*dg[5] - adjm[7];
     J_C[0] = dg[0]*matd[6] + loc1*dg[6];
     J_C[1] = dg[0]*matd[7] + loc1*dg[7] - adjm[5];
     J_C[2] = dg[0]*matd[8] + loc1*dg[8] + adjm[4];
     loc1 = dobj_dgdg*dg[1] + matd[1];
     J_A[3] = dobj_df + dg[1]*(matd[1] + loc1);
     J_A[4] = dg[1]*matd[2] + loc1*dg[2];
     J_B[3] = dg[1]*matd[3] + loc1*dg[3] - adjm[8];
     J_B[4] = dg[1]*matd[4] + loc1*dg[4];
     J_B[5] = dg[1]*matd[5] + loc1*dg[5] + adjm[6];
     J_C[3] = dg[1]*matd[6] + loc1*dg[6] + adjm[5];
     J_C[4] = dg[1]*matd[7] + loc1*dg[7];
     J_C[5] = dg[1]*matd[8] + loc1*dg[8] - adjm[3];
     loc1 = dobj_dgdg*dg[2] + matd[2];
     J_A[5] = dobj_df + dg[2]*(matd[2] + loc1);
     J_B[6] = dg[2]*matd[3] + loc1*dg[3] + adjm[7];
     J_B[7] = dg[2]*matd[4] + loc1*dg[4] - adjm[6];
     J_B[8] = dg[2]*matd[5] + loc1*dg[5];
     J_C[6] = dg[2]*matd[6] + loc1*dg[6] - adjm[4];
     J_C[7] = dg[2]*matd[7] + loc1*dg[7] + adjm[3];
     J_C[8] = dg[2]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[3] + matd[3];
     J_D[0] = dobj_df + dg[3]*(matd[3] + loc1);
     J_D[1] = dg[3]*matd[4] + loc1*dg[4];
     J_D[2] = dg[3]*matd[5] + loc1*dg[5];
     J_E[0] = dg[3]*matd[6] + loc1*dg[6];
     J_E[1] = dg[3]*matd[7] + loc1*dg[7] + adjm[2];
     J_E[2] = dg[3]*matd[8] + loc1*dg[8] - adjm[1];
     loc1 = dobj_dgdg*dg[4] + matd[4];
     J_D[3] = dobj_df + dg[4]*(matd[4] + loc1);
     J_D[4] = dg[4]*matd[5] + loc1*dg[5];
     J_E[3] = dg[4]*matd[6] + loc1*dg[6] - adjm[2];
     J_E[4] = dg[4]*matd[7] + loc1*dg[7];
     J_E[5] = dg[4]*matd[8] + loc1*dg[8] + adjm[0];
     loc1 = dobj_dgdg*dg[5] + matd[5];
     J_D[5] = dobj_df + dg[5]*(matd[5] + loc1);
     J_E[6] = dg[5]*matd[6] + loc1*dg[6] + adjm[1];
     J_E[7] = dg[5]*matd[7] + loc1*dg[7] - adjm[0];
     J_E[8] = dg[5]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[6] + matd[6];
     J_F[0] = dobj_df + dg[6]*(matd[6] + loc1);
     J_F[1] = dg[6]*matd[7] + loc1*dg[7];
     J_F[2] = dg[6]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[7] + matd[7];
     J_F[3] = dobj_df + dg[7]*(matd[7] + loc1);
     J_F[4] = dg[7]*matd[8] + loc1*dg[8];
     J_F[5] = dobj_df + dg[8]*(2.0*matd[8] + dobj_dgdg*dg[8]);
     /* Assemble matrix products */
     /* dx / dx */
     A[0]  =  J_A[0]*invR[0][0] + J_A[1]*invR[0][1] + J_A[2]*invR[0][2];
     A[1]  =  J_A[1]*invR[0][0] + J_A[3]*invR[0][1] + J_A[4]*invR[0][2];
     A[2]  =  J_A[2]*invR[0][0] + J_A[4]*invR[0][1] + J_A[5]*invR[0][2];
     h_obj[0][0] =  A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dx / dy */
     A[0]  =  J_B[0]*invR[0][0] + J_B[1]*invR[0][1] + J_B[2]*invR[0][2];
     A[1]  =  J_B[3]*invR[0][0] + J_B[4]*invR[0][1] + J_B[5]*invR[0][2];
     A[2]  =  J_B[6]*invR[0][0] + J_B[7]*invR[0][1] + J_B[8]*invR[0][2];
     h_obj[0][1] = A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dx / dz */
     A[0]  =  J_C[0]*invR[0][0] + J_C[1]*invR[0][1] + J_C[2]*invR[0][2];
     A[1]  =  J_C[3]*invR[0][0] + J_C[4]*invR[0][1] + J_C[5]*invR[0][2];
     A[2]  =  J_C[6]*invR[0][0] + J_C[7]*invR[0][1] + J_C[8]*invR[0][2];
     h_obj[0][2] = A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dy / dy */
     A[0]  =  J_D[0]*invR[0][0] + J_D[1]*invR[0][1] + J_D[2]*invR[0][2];
     A[1]  =  J_D[1]*invR[0][0] + J_D[3]*invR[0][1] + J_D[4]*invR[0][2];
     A[2]  =  J_D[2]*invR[0][0] + J_D[4]*invR[0][1] + J_D[5]*invR[0][2];
     h_obj[1][1] =  A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dy / dz */
     A[0]  =  J_E[0]*invR[0][0] + J_E[1]*invR[0][1] + J_E[2]*invR[0][2];
     A[1]  =  J_E[3]*invR[0][0] + J_E[4]*invR[0][1] + J_E[5]*invR[0][2];
     A[2]  =  J_E[6]*invR[0][0] + J_E[7]*invR[0][1] + J_E[8]*invR[0][2];
     h_obj[1][2] = A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dz / dz */
     A[0]  =  J_F[0]*invR[0][0] + J_F[1]*invR[0][1] + J_F[2]*invR[0][2];
     A[1]  =  J_F[1]*invR[0][0] + J_F[3]*invR[0][1] + J_F[4]*invR[0][2];
     A[2]  =  J_F[2]*invR[0][0] + J_F[4]*invR[0][1] + J_F[5]*invR[0][2];
     h_obj[2][2] =  A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* Complete diagonal blocks */
     h_obj.fill_lower_triangle();
     return true;
   }
bool h_gdft_2_v2 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[3], const Vector3D & n, const Matrix3D & invR, const Matrix3D & Q, const double alpha = 0.5, const Exponent & gamma = 1.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 1999 of file includeLinks/I_DFTFamilyFunctions.hpp.
References A, Matrix3D::fill_lower_triangle(), MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_hessian().
   {
     double matr[9], f, t1, t2;
     double matd[9], g, t3, loc1;
     double adjm[6], dg[9], dobj_df, dobj_dfdg, dobj_dg, dobj_dgdg;
     double J_A[3], J_B[4], J_C[4], J_D[3], J_E[4], J_F[3];
     double A[2];
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + n[0]*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + n[1]*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + n[2]*invR[2][2];
     /* Calculate det(M). */
     dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
     dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
     dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
     dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
     dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
     dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
     dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
     t1 = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = t1*t1 + 4.0*delta*delta;
     t3 = sqrt(t2);
     g = t1 + t3;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc1 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc1;
     /* Calculate the derivative of the objective function. */
     t3 = 1.0 / t3;
     dobj_df = 2.0 * loc1;
     dobj_dg = -gamma * obj * t3;
     dobj_dfdg = -gamma * dobj_df * t3;
     dobj_dgdg = dobj_dg * ((-gamma - 1.0)*t3 + 4.0*delta*delta/(t2*g));
     /* Calculate adjoint matrix */
     adjm[0] = dobj_df*matd[1] + dobj_dg*dg[1];
     adjm[1] = dobj_df*matd[2] + dobj_dg*dg[2];
     adjm[2] = dobj_df*matd[4] + dobj_dg*dg[4];
     adjm[3] = dobj_df*matd[5] + dobj_dg*dg[5];
     adjm[4] = dobj_df*matd[7] + dobj_dg*dg[7];
     adjm[5] = dobj_df*matd[8] + dobj_dg*dg[8];
     /* Construct gradients */
     g_obj[0] = invR[1][1]*adjm[0]+invR[1][2]*adjm[1];
     g_obj[1] = invR[1][1]*adjm[2]+invR[1][2]*adjm[3];
     g_obj[2] = invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     /* Start of the Hessian evaluation */
     adjm[0] = dobj_dg*matr[0];
     adjm[1] = dobj_dg*matr[3];
     adjm[2] = dobj_dg*matr[6];
     matd[1] *= dobj_dfdg;
     matd[2] *= dobj_dfdg;
     matd[4] *= dobj_dfdg;
     matd[5] *= dobj_dfdg;
     matd[7] *= dobj_dfdg;
     matd[8] *= dobj_dfdg;
     /* Blocks for the Hessian construction */
     loc1 = dobj_dgdg*dg[1] + matd[1];
     J_A[0] = dobj_df + dg[1]*(matd[1] + loc1);
     J_A[1] = dg[1]*matd[2] + loc1*dg[2];
     J_B[0] = dg[1]*matd[4] + loc1*dg[4];
     J_B[1] = dg[1]*matd[5] + loc1*dg[5] + adjm[2];
     J_C[0] = dg[1]*matd[7] + loc1*dg[7];
     J_C[1] = dg[1]*matd[8] + loc1*dg[8] - adjm[1];
     loc1 = dobj_dgdg*dg[2] + matd[2];
     J_A[2] = dobj_df + dg[2]*(matd[2] + loc1);
     J_B[2] = dg[2]*matd[4] + loc1*dg[4] - adjm[2];
     J_B[3] = dg[2]*matd[5] + loc1*dg[5];
     J_C[2] = dg[2]*matd[7] + loc1*dg[7] + adjm[1];
     J_C[3] = dg[2]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[4] + matd[4];
     J_D[0] = dobj_df + dg[4]*(matd[4] + loc1);
     J_D[1] = dg[4]*matd[5] + loc1*dg[5];
     J_E[0] = dg[4]*matd[7] + loc1*dg[7];
     J_E[1] = dg[4]*matd[8] + loc1*dg[8] + adjm[0];
     loc1 = dobj_dgdg*dg[5] + matd[5];
     J_D[2] = dobj_df + dg[5]*(matd[5] + loc1);
     J_E[2] = dg[5]*matd[7] + loc1*dg[7] - adjm[0];
     J_E[3] = dg[5]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[7] + matd[7];
     J_F[0] = dobj_df + dg[7]*(matd[7] + loc1);
     J_F[1] = dg[7]*matd[8] + loc1*dg[8];
     J_F[2] = dobj_df + dg[8]*(2.0*matd[8] + dobj_dgdg*dg[8]);
     /* Assemble matrix products */
     /* dx / dx */
     A[0]  = J_A[0]*invR[1][1] + J_A[1]*invR[1][2];
     A[1]  = J_A[1]*invR[1][1] + J_A[2]*invR[1][2];
     h_obj[0][0] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dx / dy */
     A[0]  = J_B[0]*invR[1][1] + J_B[1]*invR[1][2];
     A[1]  = J_B[2]*invR[1][1] + J_B[3]*invR[1][2];
     h_obj[0][1] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dx / dz */
     A[0]  = J_C[0]*invR[1][1] + J_C[1]*invR[1][2];
     A[1]  = J_C[2]*invR[1][1] + J_C[3]*invR[1][2];
     h_obj[0][2] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dy / dy */
     A[0]  = J_D[0]*invR[1][1] + J_D[1]*invR[1][2];
     A[1]  = J_D[1]*invR[1][1] + J_D[2]*invR[1][2];
     h_obj[1][1] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dy / dz */
     A[0]  = J_E[0]*invR[1][1] + J_E[1]*invR[1][2];
     A[1]  = J_E[2]*invR[1][1] + J_E[3]*invR[1][2];
     h_obj[1][2] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dz / dz */
     A[0]  = J_F[0]*invR[1][1] + J_F[1]*invR[1][2];
     A[1]  = J_F[1]*invR[1][1] + J_F[2]*invR[1][2];
     h_obj[2][2] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* Complete diagonal blocks */
     h_obj.fill_lower_triangle();
     return true;
   }
bool h_gdft_3 (double & obj, Vector3D g_obj[4], Matrix3D h_obj[10], const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 815 of file includeLinks/I_DFTFamilyFunctions.hpp.
References A, Matrix3D::fill_lower_triangle(), MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_hessian().
   {
     double matr[9], f, t1, t2;
     double matd[9], g, t3, loc1;
     double adjm[9], dg[9], dobj_df, dobj_dfdg, dobj_dg, dobj_dgdg;
     double J_A[6], J_B[10], J_C[10], J_D[6], J_E[10], J_F[6];
     double A[12];
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
     dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
     dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
     dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
     dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
     dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
     dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
     dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
     dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
     t1 = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = t1*t1 + 4.0*delta*delta;
     t3 = sqrt(t2);
     g = t1 + t3;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc1 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc1;
     /* Calculate the derivative of the objective function. */
     t3 = 1.0 / t3;
     dobj_df = 2.0 * loc1;
     dobj_dg = -gamma * obj * t3;
     dobj_dfdg = -gamma * dobj_df * t3;
     dobj_dgdg = dobj_dg * ((-gamma - 1.0)*t3 + 4.0*delta*delta/(t2*g));
     /* Calculate adjoint matrix */
     adjm[0] = dobj_df*matd[0] + dobj_dg*dg[0];
     adjm[1] = dobj_df*matd[1] + dobj_dg*dg[1];
     adjm[2] = dobj_df*matd[2] + dobj_dg*dg[2];
     adjm[3] = dobj_df*matd[3] + dobj_dg*dg[3];
     adjm[4] = dobj_df*matd[4] + dobj_dg*dg[4];
     adjm[5] = dobj_df*matd[5] + dobj_dg*dg[5];
     adjm[6] = dobj_df*matd[6] + dobj_dg*dg[6];
     adjm[7] = dobj_df*matd[7] + dobj_dg*dg[7];
     adjm[8] = dobj_df*matd[8] + dobj_dg*dg[8];
     /* Construct gradients */
     g_obj[1][0] = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[2][0] =                    invR[1][1]*adjm[1]+invR[1][2]*adjm[2];
     g_obj[3][0] =                                       invR[2][2]*adjm[2];
     g_obj[0][0] = -g_obj[1][0] - g_obj[2][0] - g_obj[3][0];
     g_obj[1][1] = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[2][1] =                    invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     g_obj[3][1] =                                       invR[2][2]*adjm[5];
     g_obj[0][1] = -g_obj[1][1] - g_obj[2][1] - g_obj[3][1];
     g_obj[1][2] = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     g_obj[2][2] =                    invR[1][1]*adjm[7]+invR[1][2]*adjm[8];
     g_obj[3][2] =                                       invR[2][2]*adjm[8];
     g_obj[0][2] = -g_obj[1][2] - g_obj[2][2] - g_obj[3][2];
     /* Start of the Hessian evaluation */
     adjm[0] = dobj_dg*matr[0]; matd[0] *= dobj_dfdg;
     adjm[1] = dobj_dg*matr[1]; matd[1] *= dobj_dfdg;
     adjm[2] = dobj_dg*matr[2]; matd[2] *= dobj_dfdg;
     adjm[3] = dobj_dg*matr[3]; matd[3] *= dobj_dfdg;
     adjm[4] = dobj_dg*matr[4]; matd[4] *= dobj_dfdg;
     adjm[5] = dobj_dg*matr[5]; matd[5] *= dobj_dfdg;
     adjm[6] = dobj_dg*matr[6]; matd[6] *= dobj_dfdg;
     adjm[7] = dobj_dg*matr[7]; matd[7] *= dobj_dfdg;
     adjm[8] = dobj_dg*matr[8]; matd[8] *= dobj_dfdg;
     /* Blocks for the Hessian construction */
     loc1 = dobj_dgdg*dg[0] + matd[0];
     J_A[0] = dobj_df + dg[0]*(matd[0] + loc1);
     J_A[1] = dg[0]*matd[1] + loc1*dg[1];
     J_A[2] = dg[0]*matd[2] + loc1*dg[2];
     J_B[0] = dg[0]*matd[3] + loc1*dg[3];
     J_B[1] = dg[0]*matd[4] + loc1*dg[4] + adjm[8];
     J_B[2] = dg[0]*matd[5] + loc1*dg[5] - adjm[7];
     J_C[0] = dg[0]*matd[6] + loc1*dg[6];
     J_C[1] = dg[0]*matd[7] + loc1*dg[7] - adjm[5];
     J_C[2] = dg[0]*matd[8] + loc1*dg[8] + adjm[4];
     loc1 = dobj_dgdg*dg[1] + matd[1];
     J_A[3] = dobj_df + dg[1]*(matd[1] + loc1);
     J_A[4] = dg[1]*matd[2] + loc1*dg[2];
     J_B[3] = dg[1]*matd[3] + loc1*dg[3] - adjm[8];
     J_B[4] = dg[1]*matd[4] + loc1*dg[4];
     J_B[5] = dg[1]*matd[5] + loc1*dg[5] + adjm[6];
     J_C[3] = dg[1]*matd[6] + loc1*dg[6] + adjm[5];
     J_C[4] = dg[1]*matd[7] + loc1*dg[7];
     J_C[5] = dg[1]*matd[8] + loc1*dg[8] - adjm[3];
     loc1 = dobj_dgdg*dg[2] + matd[2];
     J_A[5] = dobj_df + dg[2]*(matd[2] + loc1);
     J_B[6] = dg[2]*matd[3] + loc1*dg[3] + adjm[7];
     J_B[7] = dg[2]*matd[4] + loc1*dg[4] - adjm[6];
     J_B[8] = dg[2]*matd[5] + loc1*dg[5];
     J_C[6] = dg[2]*matd[6] + loc1*dg[6] - adjm[4];
     J_C[7] = dg[2]*matd[7] + loc1*dg[7] + adjm[3];
     J_C[8] = dg[2]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[3] + matd[3];
     J_D[0] = dobj_df + dg[3]*(matd[3] + loc1);
     J_D[1] = dg[3]*matd[4] + loc1*dg[4];
     J_D[2] = dg[3]*matd[5] + loc1*dg[5];
     J_E[0] = dg[3]*matd[6] + loc1*dg[6];
     J_E[1] = dg[3]*matd[7] + loc1*dg[7] + adjm[2];
     J_E[2] = dg[3]*matd[8] + loc1*dg[8] - adjm[1];
     loc1 = dobj_dgdg*dg[4] + matd[4];
     J_D[3] = dobj_df + dg[4]*(matd[4] + loc1);
     J_D[4] = dg[4]*matd[5] + loc1*dg[5];
     J_E[3] = dg[4]*matd[6] + loc1*dg[6] - adjm[2];
     J_E[4] = dg[4]*matd[7] + loc1*dg[7];
     J_E[5] = dg[4]*matd[8] + loc1*dg[8] + adjm[0];
     loc1 = dobj_dgdg*dg[5] + matd[5];
     J_D[5] = dobj_df + dg[5]*(matd[5] + loc1);
     J_E[6] = dg[5]*matd[6] + loc1*dg[6] + adjm[1];
     J_E[7] = dg[5]*matd[7] + loc1*dg[7] - adjm[0];
     J_E[8] = dg[5]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[6] + matd[6];
     J_F[0] = dobj_df + dg[6]*(matd[6] + loc1);
     J_F[1] = dg[6]*matd[7] + loc1*dg[7];
     J_F[2] = dg[6]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[7] + matd[7];
     J_F[3] = dobj_df + dg[7]*(matd[7] + loc1);
     J_F[4] = dg[7]*matd[8] + loc1*dg[8];
     J_F[5] = dobj_df + dg[8]*(2.0*matd[8] + dobj_dgdg*dg[8]);
     /* Assemble matrix products */
     /* dx / dx */
     A[1]  =  J_A[0]*invR[0][0] + J_A[1]*invR[0][1] + J_A[2]*invR[0][2];
     A[2]  =                      J_A[1]*invR[1][1] + J_A[2]*invR[1][2];
     A[3]  =                                          J_A[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_A[1]*invR[0][0] + J_A[3]*invR[0][1] + J_A[4]*invR[0][2];
     A[6]  =                      J_A[3]*invR[1][1] + J_A[4]*invR[1][2];
     A[7]  =                                          J_A[4]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_A[2]*invR[0][0] + J_A[4]*invR[0][1] + J_A[5]*invR[0][2];
     A[10] =                      J_A[4]*invR[1][1] + J_A[5]*invR[1][2];
     A[11] =                                          J_A[5]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[1][0][0] =  A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[2][0][0] =                    A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[3][0][0] =                                      A[8]*invR[2][2];
     h_obj[0][0][0] = -h_obj[1][0][0] - h_obj[2][0][0] - h_obj[3][0][0];
     h_obj[4][0][0] =  A[1]*invR[0][0] + A[5]*invR[0][1] + A[9]*invR[0][2];
     h_obj[5][0][0] =                    A[5]*invR[1][1] + A[9]*invR[1][2];
     h_obj[6][0][0] =                                      A[9]*invR[2][2];
     h_obj[7][0][0] =                    A[6]*invR[1][1] + A[10]*invR[1][2];
     h_obj[8][0][0] =                                      A[10]*invR[2][2];
     h_obj[9][0][0] =                                      A[11]*invR[2][2];
     /* dx / dy */
     A[1]  =  J_B[0]*invR[0][0] + J_B[1]*invR[0][1] + J_B[2]*invR[0][2];
     A[2]  =                      J_B[1]*invR[1][1] + J_B[2]*invR[1][2];
     A[3]  =                                          J_B[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_B[3]*invR[0][0] + J_B[4]*invR[0][1] + J_B[5]*invR[0][2];
     A[6]  =                      J_B[4]*invR[1][1] + J_B[5]*invR[1][2];
     A[7]  =                                          J_B[5]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_B[6]*invR[0][0] + J_B[7]*invR[0][1] + J_B[8]*invR[0][2];
     A[10] =                      J_B[7]*invR[1][1] + J_B[8]*invR[1][2];
     A[11] =                                          J_B[8]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[1][1][0] = A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[4][0][1] = A[1]*invR[0][0] + A[5]*invR[0][1] + A[9]*invR[0][2];
     h_obj[5][0][1] = A[2]*invR[0][0] + A[6]*invR[0][1] + A[10]*invR[0][2];
     h_obj[6][0][1] = A[3]*invR[0][0] + A[7]*invR[0][1] + A[11]*invR[0][2];
     h_obj[2][1][0] = A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[5][1][0] = A[5]*invR[1][1] + A[9]*invR[1][2];
     h_obj[7][0][1] = A[6]*invR[1][1] + A[10]*invR[1][2];
     h_obj[8][0][1] = A[7]*invR[1][1] + A[11]*invR[1][2];
     h_obj[3][1][0] = A[8]*invR[2][2];
     h_obj[6][1][0] = A[9]*invR[2][2];
     h_obj[8][1][0] = A[10]*invR[2][2];
     h_obj[9][0][1] = A[11]*invR[2][2];
     h_obj[0][0][1] = -h_obj[1][1][0] - h_obj[2][1][0] - h_obj[3][1][0];
     h_obj[1][0][1] = -h_obj[4][0][1] - h_obj[5][1][0] - h_obj[6][1][0];
     h_obj[2][0][1] = -h_obj[5][0][1] - h_obj[7][0][1] - h_obj[8][1][0];
     h_obj[3][0][1] = -h_obj[6][0][1] - h_obj[8][0][1] - h_obj[9][0][1];
     /* dx / dz */
     A[1]  =  J_C[0]*invR[0][0] + J_C[1]*invR[0][1] + J_C[2]*invR[0][2];
     A[2]  =                      J_C[1]*invR[1][1] + J_C[2]*invR[1][2];
     A[3]  =                                          J_C[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_C[3]*invR[0][0] + J_C[4]*invR[0][1] + J_C[5]*invR[0][2];
     A[6]  =                      J_C[4]*invR[1][1] + J_C[5]*invR[1][2];
     A[7]  =                                          J_C[5]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_C[6]*invR[0][0] + J_C[7]*invR[0][1] + J_C[8]*invR[0][2];
     A[10] =                      J_C[7]*invR[1][1] + J_C[8]*invR[1][2];
     A[11] =                                          J_C[8]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[1][2][0] = A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[4][0][2] = A[1]*invR[0][0] + A[5]*invR[0][1] + A[9]*invR[0][2];
     h_obj[5][0][2] = A[2]*invR[0][0] + A[6]*invR[0][1] + A[10]*invR[0][2];
     h_obj[6][0][2] = A[3]*invR[0][0] + A[7]*invR[0][1] + A[11]*invR[0][2];
     h_obj[2][2][0] = A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[5][2][0] = A[5]*invR[1][1] + A[9]*invR[1][2];
     h_obj[7][0][2] = A[6]*invR[1][1] + A[10]*invR[1][2];
     h_obj[8][0][2] = A[7]*invR[1][1] + A[11]*invR[1][2];
     h_obj[3][2][0] = A[8]*invR[2][2];
     h_obj[6][2][0] = A[9]*invR[2][2];
     h_obj[8][2][0] = A[10]*invR[2][2];
     h_obj[9][0][2] = A[11]*invR[2][2];
     h_obj[0][0][2] = -h_obj[1][2][0] - h_obj[2][2][0] - h_obj[3][2][0];
     h_obj[1][0][2] = -h_obj[4][0][2] - h_obj[5][2][0] - h_obj[6][2][0];
     h_obj[2][0][2] = -h_obj[5][0][2] - h_obj[7][0][2] - h_obj[8][2][0];
     h_obj[3][0][2] = -h_obj[6][0][2] - h_obj[8][0][2] - h_obj[9][0][2];
     /* dy / dy */
     A[1]  =  J_D[0]*invR[0][0] + J_D[1]*invR[0][1] + J_D[2]*invR[0][2];
     A[2]  =                      J_D[1]*invR[1][1] + J_D[2]*invR[1][2];
     A[3]  =                                          J_D[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_D[1]*invR[0][0] + J_D[3]*invR[0][1] + J_D[4]*invR[0][2];
     A[6]  =                      J_D[3]*invR[1][1] + J_D[4]*invR[1][2];
     A[7]  =                                          J_D[4]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_D[2]*invR[0][0] + J_D[4]*invR[0][1] + J_D[5]*invR[0][2];
     A[10] =                      J_D[4]*invR[1][1] + J_D[5]*invR[1][2];
     A[11] =                                          J_D[5]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[1][1][1] =  A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[2][1][1] =                    A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[3][1][1] =                                      A[8]*invR[2][2];
     h_obj[0][1][1] = -h_obj[1][1][1] - h_obj[2][1][1] - h_obj[3][1][1];
     h_obj[4][1][1] =  A[1]*invR[0][0] + A[5]*invR[0][1] + A[9]*invR[0][2];
     h_obj[5][1][1] =                    A[5]*invR[1][1] + A[9]*invR[1][2];
     h_obj[6][1][1] =                                      A[9]*invR[2][2];
     h_obj[7][1][1] =                    A[6]*invR[1][1] + A[10]*invR[1][2];
     h_obj[8][1][1] =                                      A[10]*invR[2][2];
     h_obj[9][1][1] =                                      A[11]*invR[2][2];
     /* dy / dz */
     A[1]  =  J_E[0]*invR[0][0] + J_E[1]*invR[0][1] + J_E[2]*invR[0][2];
     A[2]  =                      J_E[1]*invR[1][1] + J_E[2]*invR[1][2];
     A[3]  =                                          J_E[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_E[3]*invR[0][0] + J_E[4]*invR[0][1] + J_E[5]*invR[0][2];
     A[6]  =                      J_E[4]*invR[1][1] + J_E[5]*invR[1][2];
     A[7]  =                                          J_E[5]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_E[6]*invR[0][0] + J_E[7]*invR[0][1] + J_E[8]*invR[0][2];
     A[10] =                      J_E[7]*invR[1][1] + J_E[8]*invR[1][2];
     A[11] =                                          J_E[8]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[1][2][1] = A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[4][1][2] = A[1]*invR[0][0] + A[5]*invR[0][1] + A[9]*invR[0][2];
     h_obj[5][1][2] = A[2]*invR[0][0] + A[6]*invR[0][1] + A[10]*invR[0][2];
     h_obj[6][1][2] = A[3]*invR[0][0] + A[7]*invR[0][1] + A[11]*invR[0][2];
     h_obj[2][2][1] = A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[5][2][1] = A[5]*invR[1][1] + A[9]*invR[1][2];
     h_obj[7][1][2] = A[6]*invR[1][1] + A[10]*invR[1][2];
     h_obj[8][1][2] = A[7]*invR[1][1] + A[11]*invR[1][2];
     h_obj[3][2][1] = A[8]*invR[2][2];
     h_obj[6][2][1] = A[9]*invR[2][2];
     h_obj[8][2][1] = A[10]*invR[2][2];
     h_obj[9][1][2] = A[11]*invR[2][2];
     h_obj[0][1][2] = -h_obj[1][2][1] - h_obj[2][2][1] - h_obj[3][2][1];
     h_obj[1][1][2] = -h_obj[4][1][2] - h_obj[5][2][1] - h_obj[6][2][1];
     h_obj[2][1][2] = -h_obj[5][1][2] - h_obj[7][1][2] - h_obj[8][2][1];
     h_obj[3][1][2] = -h_obj[6][1][2] - h_obj[8][1][2] - h_obj[9][1][2];
     /* dz / dz */
     A[1]  =  J_F[0]*invR[0][0] + J_F[1]*invR[0][1] + J_F[2]*invR[0][2];
     A[2]  =                      J_F[1]*invR[1][1] + J_F[2]*invR[1][2];
     A[3]  =                                          J_F[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_F[1]*invR[0][0] + J_F[3]*invR[0][1] + J_F[4]*invR[0][2];
     A[6]  =                      J_F[3]*invR[1][1] + J_F[4]*invR[1][2];
     A[7]  =                                          J_F[4]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_F[2]*invR[0][0] + J_F[4]*invR[0][1] + J_F[5]*invR[0][2];
     A[10] =                      J_F[4]*invR[1][1] + J_F[5]*invR[1][2];
     A[11] =                                          J_F[5]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[1][2][2] =  A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[2][2][2] =                    A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[3][2][2] =                                      A[8]*invR[2][2];
     h_obj[0][2][2] = -h_obj[1][2][2] - h_obj[2][2][2] - h_obj[3][2][2];
     h_obj[4][2][2] =  A[1]*invR[0][0] + A[5]*invR[0][1] + A[9]*invR[0][2];
     h_obj[5][2][2] =                    A[5]*invR[1][1] + A[9]*invR[1][2];
     h_obj[6][2][2] =                                      A[9]*invR[2][2];
     h_obj[7][2][2] =                    A[6]*invR[1][1] + A[10]*invR[1][2];
     h_obj[8][2][2] =                                      A[10]*invR[2][2];
     h_obj[9][2][2] =                                      A[11]*invR[2][2];
     /* Complete diagonal blocks */
     h_obj[0].fill_lower_triangle();
     h_obj[4].fill_lower_triangle();
     h_obj[7].fill_lower_triangle();
     h_obj[9].fill_lower_triangle();
     return true;
   }
bool h_gdft_3_v0 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 2547 of file includeLinks/I_DFTFamilyFunctions.hpp.
References A, Matrix3D::fill_lower_triangle(), MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_hessian().
   {
     double matr[9], f, t1, t2;
     double matd[9], g, t3, loc1;
     double adjm[9], dg[9], dobj_df, dobj_dfdg, dobj_dg, dobj_dgdg;
     double J_A[6], J_B[10], J_C[10], J_D[6], J_E[10], J_F[6];
     double A[12];
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
     dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
     dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
     dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
     dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
     dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
     dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
     dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
     dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
     t1 = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = t1*t1 + 4.0*delta*delta;
     t3 = sqrt(t2);
     g = t1 + t3;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc1 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc1;
     /* Calculate the derivative of the objective function. */
     t3 = 1.0 / t3;
     dobj_df = 2.0 * loc1;
     dobj_dg = -gamma * obj * t3;
     dobj_dfdg = -gamma * dobj_df * t3;
     dobj_dgdg = dobj_dg * ((-gamma - 1.0)*t3 + 4.0*delta*delta/(t2*g));
     /* Calculate adjoint matrix */
     adjm[0] = dobj_df*matd[0] + dobj_dg*dg[0];
     adjm[1] = dobj_df*matd[1] + dobj_dg*dg[1];
     adjm[2] = dobj_df*matd[2] + dobj_dg*dg[2];
     adjm[3] = dobj_df*matd[3] + dobj_dg*dg[3];
     adjm[4] = dobj_df*matd[4] + dobj_dg*dg[4];
     adjm[5] = dobj_df*matd[5] + dobj_dg*dg[5];
     adjm[6] = dobj_df*matd[6] + dobj_dg*dg[6];
     adjm[7] = dobj_df*matd[7] + dobj_dg*dg[7];
     adjm[8] = dobj_df*matd[8] + dobj_dg*dg[8];
     /* Construct gradients */
     g_obj[0]  = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[0] +=                    invR[1][1]*adjm[1]+invR[1][2]*adjm[2];
     g_obj[0] +=                                       invR[2][2]*adjm[2];
     g_obj[0]  = -g_obj[0];
     g_obj[1]  = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[1] +=                    invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     g_obj[1] +=                                       invR[2][2]*adjm[5];
     g_obj[1]  = -g_obj[1];
     g_obj[2]  = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     g_obj[2] +=                    invR[1][1]*adjm[7]+invR[1][2]*adjm[8];
     g_obj[2] +=                                       invR[2][2]*adjm[8];
     g_obj[2]  = -g_obj[2];
     /* Start of the Hessian evaluation */
     adjm[0] = dobj_dg*matr[0]; matd[0] *= dobj_dfdg;
     adjm[1] = dobj_dg*matr[1]; matd[1] *= dobj_dfdg;
     adjm[2] = dobj_dg*matr[2]; matd[2] *= dobj_dfdg;
     adjm[3] = dobj_dg*matr[3]; matd[3] *= dobj_dfdg;
     adjm[4] = dobj_dg*matr[4]; matd[4] *= dobj_dfdg;
     adjm[5] = dobj_dg*matr[5]; matd[5] *= dobj_dfdg;
     adjm[6] = dobj_dg*matr[6]; matd[6] *= dobj_dfdg;
     adjm[7] = dobj_dg*matr[7]; matd[7] *= dobj_dfdg;
     adjm[8] = dobj_dg*matr[8]; matd[8] *= dobj_dfdg;
     /* Blocks for the Hessian construction */
     loc1 = dobj_dgdg*dg[0] + matd[0];
     J_A[0] = dobj_df + dg[0]*(matd[0] + loc1);
     J_A[1] = dg[0]*matd[1] + loc1*dg[1];
     J_A[2] = dg[0]*matd[2] + loc1*dg[2];
     J_B[0] = dg[0]*matd[3] + loc1*dg[3];
     J_B[1] = dg[0]*matd[4] + loc1*dg[4] + adjm[8];
     J_B[2] = dg[0]*matd[5] + loc1*dg[5] - adjm[7];
     J_C[0] = dg[0]*matd[6] + loc1*dg[6];
     J_C[1] = dg[0]*matd[7] + loc1*dg[7] - adjm[5];
     J_C[2] = dg[0]*matd[8] + loc1*dg[8] + adjm[4];
     loc1 = dobj_dgdg*dg[1] + matd[1];
     J_A[3] = dobj_df + dg[1]*(matd[1] + loc1);
     J_A[4] = dg[1]*matd[2] + loc1*dg[2];
     J_B[3] = dg[1]*matd[3] + loc1*dg[3] - adjm[8];
     J_B[4] = dg[1]*matd[4] + loc1*dg[4];
     J_B[5] = dg[1]*matd[5] + loc1*dg[5] + adjm[6];
     J_C[3] = dg[1]*matd[6] + loc1*dg[6] + adjm[5];
     J_C[4] = dg[1]*matd[7] + loc1*dg[7];
     J_C[5] = dg[1]*matd[8] + loc1*dg[8] - adjm[3];
     loc1 = dobj_dgdg*dg[2] + matd[2];
     J_A[5] = dobj_df + dg[2]*(matd[2] + loc1);
     J_B[6] = dg[2]*matd[3] + loc1*dg[3] + adjm[7];
     J_B[7] = dg[2]*matd[4] + loc1*dg[4] - adjm[6];
     J_B[8] = dg[2]*matd[5] + loc1*dg[5];
     J_C[6] = dg[2]*matd[6] + loc1*dg[6] - adjm[4];
     J_C[7] = dg[2]*matd[7] + loc1*dg[7] + adjm[3];
     J_C[8] = dg[2]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[3] + matd[3];
     J_D[0] = dobj_df + dg[3]*(matd[3] + loc1);
     J_D[1] = dg[3]*matd[4] + loc1*dg[4];
     J_D[2] = dg[3]*matd[5] + loc1*dg[5];
     J_E[0] = dg[3]*matd[6] + loc1*dg[6];
     J_E[1] = dg[3]*matd[7] + loc1*dg[7] + adjm[2];
     J_E[2] = dg[3]*matd[8] + loc1*dg[8] - adjm[1];
     loc1 = dobj_dgdg*dg[4] + matd[4];
     J_D[3] = dobj_df + dg[4]*(matd[4] + loc1);
     J_D[4] = dg[4]*matd[5] + loc1*dg[5];
     J_E[3] = dg[4]*matd[6] + loc1*dg[6] - adjm[2];
     J_E[4] = dg[4]*matd[7] + loc1*dg[7];
     J_E[5] = dg[4]*matd[8] + loc1*dg[8] + adjm[0];
     loc1 = dobj_dgdg*dg[5] + matd[5];
     J_D[5] = dobj_df + dg[5]*(matd[5] + loc1);
     J_E[6] = dg[5]*matd[6] + loc1*dg[6] + adjm[1];
     J_E[7] = dg[5]*matd[7] + loc1*dg[7] - adjm[0];
     J_E[8] = dg[5]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[6] + matd[6];
     J_F[0] = dobj_df + dg[6]*(matd[6] + loc1);
     J_F[1] = dg[6]*matd[7] + loc1*dg[7];
     J_F[2] = dg[6]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[7] + matd[7];
     J_F[3] = dobj_df + dg[7]*(matd[7] + loc1);
     J_F[4] = dg[7]*matd[8] + loc1*dg[8];
     J_F[5] = dobj_df + dg[8]*(2.0*matd[8] + dobj_dgdg*dg[8]);
     /* Assemble matrix products */
     /* dx / dx */
     A[1]  =  J_A[0]*invR[0][0] + J_A[1]*invR[0][1] + J_A[2]*invR[0][2];
     A[2]  =                      J_A[1]*invR[1][1] + J_A[2]*invR[1][2];
     A[3]  =                                          J_A[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_A[1]*invR[0][0] + J_A[3]*invR[0][1] + J_A[4]*invR[0][2];
     A[6]  =                      J_A[3]*invR[1][1] + J_A[4]*invR[1][2];
     A[7]  =                                          J_A[4]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_A[2]*invR[0][0] + J_A[4]*invR[0][1] + J_A[5]*invR[0][2];
     A[10] =                      J_A[4]*invR[1][1] + J_A[5]*invR[1][2];
     A[11] =                                          J_A[5]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[0][0]  =  A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[0][0] +=                    A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[0][0] +=                                      A[8]*invR[2][2];
     h_obj[0][0]  = -h_obj[0][0];
     /* dx / dy */
     A[1]  =  J_B[0]*invR[0][0] + J_B[1]*invR[0][1] + J_B[2]*invR[0][2];
     A[2]  =                      J_B[1]*invR[1][1] + J_B[2]*invR[1][2];
     A[3]  =                                          J_B[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_B[3]*invR[0][0] + J_B[4]*invR[0][1] + J_B[5]*invR[0][2];
     A[6]  =                      J_B[4]*invR[1][1] + J_B[5]*invR[1][2];
     A[7]  =                                          J_B[5]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_B[6]*invR[0][0] + J_B[7]*invR[0][1] + J_B[8]*invR[0][2];
     A[10] =                      J_B[7]*invR[1][1] + J_B[8]*invR[1][2];
     A[11] =                                          J_B[8]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[0][1]  = A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[0][1] +=                   A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[0][1] +=                                     A[8]*invR[2][2];
     h_obj[0][1]  = -h_obj[0][1];
     /* dx / dz */
     A[1]  =  J_C[0]*invR[0][0] + J_C[1]*invR[0][1] + J_C[2]*invR[0][2];
     A[2]  =                      J_C[1]*invR[1][1] + J_C[2]*invR[1][2];
     A[3]  =                                          J_C[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_C[3]*invR[0][0] + J_C[4]*invR[0][1] + J_C[5]*invR[0][2];
     A[6]  =                      J_C[4]*invR[1][1] + J_C[5]*invR[1][2];
     A[7]  =                                          J_C[5]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_C[6]*invR[0][0] + J_C[7]*invR[0][1] + J_C[8]*invR[0][2];
     A[10] =                      J_C[7]*invR[1][1] + J_C[8]*invR[1][2];
     A[11] =                                          J_C[8]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[0][2]  = A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[0][2] +=                   A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[0][2] +=                                     A[8]*invR[2][2];
     h_obj[0][2]  = -h_obj[0][2];
     /* dy / dy */
     A[1]  =  J_D[0]*invR[0][0] + J_D[1]*invR[0][1] + J_D[2]*invR[0][2];
     A[2]  =                      J_D[1]*invR[1][1] + J_D[2]*invR[1][2];
     A[3]  =                                          J_D[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_D[1]*invR[0][0] + J_D[3]*invR[0][1] + J_D[4]*invR[0][2];
     A[6]  =                      J_D[3]*invR[1][1] + J_D[4]*invR[1][2];
     A[7]  =                                          J_D[4]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_D[2]*invR[0][0] + J_D[4]*invR[0][1] + J_D[5]*invR[0][2];
     A[10] =                      J_D[4]*invR[1][1] + J_D[5]*invR[1][2];
     A[11] =                                          J_D[5]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[1][1]  =  A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[1][1] +=                    A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[1][1] +=                                      A[8]*invR[2][2];
     h_obj[1][1]  = -h_obj[1][1];
     /* dy / dz */
     A[1]  =  J_E[0]*invR[0][0] + J_E[1]*invR[0][1] + J_E[2]*invR[0][2];
     A[2]  =                      J_E[1]*invR[1][1] + J_E[2]*invR[1][2];
     A[3]  =                                          J_E[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_E[3]*invR[0][0] + J_E[4]*invR[0][1] + J_E[5]*invR[0][2];
     A[6]  =                      J_E[4]*invR[1][1] + J_E[5]*invR[1][2];
     A[7]  =                                          J_E[5]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_E[6]*invR[0][0] + J_E[7]*invR[0][1] + J_E[8]*invR[0][2];
     A[10] =                      J_E[7]*invR[1][1] + J_E[8]*invR[1][2];
     A[11] =                                          J_E[8]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[1][2]  = A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[1][2] += A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[1][2] += A[8]*invR[2][2];
     h_obj[1][2]  = -h_obj[1][2];
     /* dz / dz */
     A[1]  =  J_F[0]*invR[0][0] + J_F[1]*invR[0][1] + J_F[2]*invR[0][2];
     A[2]  =                      J_F[1]*invR[1][1] + J_F[2]*invR[1][2];
     A[3]  =                                          J_F[2]*invR[2][2];
     A[0]  = -A[1] - A[2] - A[3];
     A[5]  =  J_F[1]*invR[0][0] + J_F[3]*invR[0][1] + J_F[4]*invR[0][2];
     A[6]  =                      J_F[3]*invR[1][1] + J_F[4]*invR[1][2];
     A[7]  =                                          J_F[4]*invR[2][2];
     A[4]  = -A[5] - A[6] - A[7];
     A[9]  =  J_F[2]*invR[0][0] + J_F[4]*invR[0][1] + J_F[5]*invR[0][2];
     A[10] =                      J_F[4]*invR[1][1] + J_F[5]*invR[1][2];
     A[11] =                                          J_F[5]*invR[2][2];
     A[8]  = -A[9] - A[10] - A[11];
     h_obj[2][2]  =  A[0]*invR[0][0] + A[4]*invR[0][1] + A[8]*invR[0][2];
     h_obj[2][2] +=                    A[4]*invR[1][1] + A[8]*invR[1][2];
     h_obj[2][2] +=                                      A[8]*invR[2][2];
     h_obj[2][2]  = -h_obj[2][2];
     /* Complete diagonal blocks */
     h_obj.fill_lower_triangle();
     return true;
   }
bool h_gdft_3_v1 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 2865 of file includeLinks/I_DFTFamilyFunctions.hpp.
References A, Matrix3D::fill_lower_triangle(), MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_hessian().
   {
     double matr[9], f, t1, t2;
     double matd[9], g, t3, loc1;
     double adjm[9], dg[9], dobj_df, dobj_dfdg, dobj_dg, dobj_dgdg;
     double J_A[6], J_B[10], J_C[10], J_D[6], J_E[10], J_F[6];
     double A[12];
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
     dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
     dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
     dg[3] = matr[2]*matr[7] - matr[1]*matr[8];
     dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
     dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
     dg[6] = matr[1]*matr[5] - matr[2]*matr[4];
     dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
     dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
     t1 = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = t1*t1 + 4.0*delta*delta;
     t3 = sqrt(t2);
     g = t1 + t3;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc1 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc1;
     /* Calculate the derivative of the objective function. */
     t3 = 1.0 / t3;
     dobj_df = 2.0 * loc1;
     dobj_dg = -gamma * obj * t3;
     dobj_dfdg = -gamma * dobj_df * t3;
     dobj_dgdg = dobj_dg * ((-gamma - 1.0)*t3 + 4.0*delta*delta/(t2*g));
     /* Calculate adjoint matrix */
     adjm[0] = dobj_df*matd[0] + dobj_dg*dg[0];
     adjm[1] = dobj_df*matd[1] + dobj_dg*dg[1];
     adjm[2] = dobj_df*matd[2] + dobj_dg*dg[2];
     adjm[3] = dobj_df*matd[3] + dobj_dg*dg[3];
     adjm[4] = dobj_df*matd[4] + dobj_dg*dg[4];
     adjm[5] = dobj_df*matd[5] + dobj_dg*dg[5];
     adjm[6] = dobj_df*matd[6] + dobj_dg*dg[6];
     adjm[7] = dobj_df*matd[7] + dobj_dg*dg[7];
     adjm[8] = dobj_df*matd[8] + dobj_dg*dg[8];
     /* Construct gradients */
     g_obj[0] = invR[0][0]*adjm[0]+invR[0][1]*adjm[1]+invR[0][2]*adjm[2];
     g_obj[1] = invR[0][0]*adjm[3]+invR[0][1]*adjm[4]+invR[0][2]*adjm[5];
     g_obj[2] = invR[0][0]*adjm[6]+invR[0][1]*adjm[7]+invR[0][2]*adjm[8];
     /* Start of the Hessian evaluation */
     adjm[0] = dobj_dg*matr[0]; matd[0] *= dobj_dfdg;
     adjm[1] = dobj_dg*matr[1]; matd[1] *= dobj_dfdg;
     adjm[2] = dobj_dg*matr[2]; matd[2] *= dobj_dfdg;
     adjm[3] = dobj_dg*matr[3]; matd[3] *= dobj_dfdg;
     adjm[4] = dobj_dg*matr[4]; matd[4] *= dobj_dfdg;
     adjm[5] = dobj_dg*matr[5]; matd[5] *= dobj_dfdg;
     adjm[6] = dobj_dg*matr[6]; matd[6] *= dobj_dfdg;
     adjm[7] = dobj_dg*matr[7]; matd[7] *= dobj_dfdg;
     adjm[8] = dobj_dg*matr[8]; matd[8] *= dobj_dfdg;
     /* Blocks for the Hessian construction */
     loc1 = dobj_dgdg*dg[0] + matd[0];
     J_A[0] = dobj_df + dg[0]*(matd[0] + loc1);
     J_A[1] = dg[0]*matd[1] + loc1*dg[1];
     J_A[2] = dg[0]*matd[2] + loc1*dg[2];
     J_B[0] = dg[0]*matd[3] + loc1*dg[3];
     J_B[1] = dg[0]*matd[4] + loc1*dg[4] + adjm[8];
     J_B[2] = dg[0]*matd[5] + loc1*dg[5] - adjm[7];
     J_C[0] = dg[0]*matd[6] + loc1*dg[6];
     J_C[1] = dg[0]*matd[7] + loc1*dg[7] - adjm[5];
     J_C[2] = dg[0]*matd[8] + loc1*dg[8] + adjm[4];
     loc1 = dobj_dgdg*dg[1] + matd[1];
     J_A[3] = dobj_df + dg[1]*(matd[1] + loc1);
     J_A[4] = dg[1]*matd[2] + loc1*dg[2];
     J_B[3] = dg[1]*matd[3] + loc1*dg[3] - adjm[8];
     J_B[4] = dg[1]*matd[4] + loc1*dg[4];
     J_B[5] = dg[1]*matd[5] + loc1*dg[5] + adjm[6];
     J_C[3] = dg[1]*matd[6] + loc1*dg[6] + adjm[5];
     J_C[4] = dg[1]*matd[7] + loc1*dg[7];
     J_C[5] = dg[1]*matd[8] + loc1*dg[8] - adjm[3];
     loc1 = dobj_dgdg*dg[2] + matd[2];
     J_A[5] = dobj_df + dg[2]*(matd[2] + loc1);
     J_B[6] = dg[2]*matd[3] + loc1*dg[3] + adjm[7];
     J_B[7] = dg[2]*matd[4] + loc1*dg[4] - adjm[6];
     J_B[8] = dg[2]*matd[5] + loc1*dg[5];
     J_C[6] = dg[2]*matd[6] + loc1*dg[6] - adjm[4];
     J_C[7] = dg[2]*matd[7] + loc1*dg[7] + adjm[3];
     J_C[8] = dg[2]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[3] + matd[3];
     J_D[0] = dobj_df + dg[3]*(matd[3] + loc1);
     J_D[1] = dg[3]*matd[4] + loc1*dg[4];
     J_D[2] = dg[3]*matd[5] + loc1*dg[5];
     J_E[0] = dg[3]*matd[6] + loc1*dg[6];
     J_E[1] = dg[3]*matd[7] + loc1*dg[7] + adjm[2];
     J_E[2] = dg[3]*matd[8] + loc1*dg[8] - adjm[1];
     loc1 = dobj_dgdg*dg[4] + matd[4];
     J_D[3] = dobj_df + dg[4]*(matd[4] + loc1);
     J_D[4] = dg[4]*matd[5] + loc1*dg[5];
     J_E[3] = dg[4]*matd[6] + loc1*dg[6] - adjm[2];
     J_E[4] = dg[4]*matd[7] + loc1*dg[7];
     J_E[5] = dg[4]*matd[8] + loc1*dg[8] + adjm[0];
     loc1 = dobj_dgdg*dg[5] + matd[5];
     J_D[5] = dobj_df + dg[5]*(matd[5] + loc1);
     J_E[6] = dg[5]*matd[6] + loc1*dg[6] + adjm[1];
     J_E[7] = dg[5]*matd[7] + loc1*dg[7] - adjm[0];
     J_E[8] = dg[5]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[6] + matd[6];
     J_F[0] = dobj_df + dg[6]*(matd[6] + loc1);
     J_F[1] = dg[6]*matd[7] + loc1*dg[7];
     J_F[2] = dg[6]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[7] + matd[7];
     J_F[3] = dobj_df + dg[7]*(matd[7] + loc1);
     J_F[4] = dg[7]*matd[8] + loc1*dg[8];
     J_F[5] = dobj_df + dg[8]*(2.0*matd[8] + dobj_dgdg*dg[8]);
     /* Assemble matrix products */
     /* dx / dx */
     A[0] = J_A[0]*invR[0][0] + J_A[1]*invR[0][1] + J_A[2]*invR[0][2];
     A[1] = J_A[1]*invR[0][0] + J_A[3]*invR[0][1] + J_A[4]*invR[0][2];
     A[2] = J_A[2]*invR[0][0] + J_A[4]*invR[0][1] + J_A[5]*invR[0][2];
     h_obj[0][0] = A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dx / dy */
     A[0] = J_B[0]*invR[0][0] + J_B[1]*invR[0][1] + J_B[2]*invR[0][2];
     A[1] = J_B[3]*invR[0][0] + J_B[4]*invR[0][1] + J_B[5]*invR[0][2];
     A[2] = J_B[6]*invR[0][0] + J_B[7]*invR[0][1] + J_B[8]*invR[0][2];
     h_obj[0][1] = A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dx / dz */
     A[0] = J_C[0]*invR[0][0] + J_C[1]*invR[0][1] + J_C[2]*invR[0][2];
     A[1] = J_C[3]*invR[0][0] + J_C[4]*invR[0][1] + J_C[5]*invR[0][2];
     A[2] = J_C[6]*invR[0][0] + J_C[7]*invR[0][1] + J_C[8]*invR[0][2];
     h_obj[0][2] = A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dy / dy */
     A[0] = J_D[0]*invR[0][0] + J_D[1]*invR[0][1] + J_D[2]*invR[0][2];
     A[1] = J_D[1]*invR[0][0] + J_D[3]*invR[0][1] + J_D[4]*invR[0][2];
     A[2] = J_D[2]*invR[0][0] + J_D[4]*invR[0][1] + J_D[5]*invR[0][2];
     h_obj[1][1] = A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dy / dz */
     A[0] = J_E[0]*invR[0][0] + J_E[1]*invR[0][1] + J_E[2]*invR[0][2];
     A[1] = J_E[3]*invR[0][0] + J_E[4]*invR[0][1] + J_E[5]*invR[0][2];
     A[2] = J_E[6]*invR[0][0] + J_E[7]*invR[0][1] + J_E[8]*invR[0][2];
     h_obj[1][2] = A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* dz / dz */
     A[0] = J_F[0]*invR[0][0] + J_F[1]*invR[0][1] + J_F[2]*invR[0][2];
     A[1] = J_F[1]*invR[0][0] + J_F[3]*invR[0][1] + J_F[4]*invR[0][2];
     A[2] = J_F[2]*invR[0][0] + J_F[4]*invR[0][1] + J_F[5]*invR[0][2];
     h_obj[2][2] = A[0]*invR[0][0] + A[1]*invR[0][1] + A[2]*invR[0][2];
     /* Complete diagonal blocks */
     h_obj.fill_lower_triangle();
     return true;
   }
bool h_gdft_3_v2 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 3082 of file includeLinks/I_DFTFamilyFunctions.hpp.
References A, Matrix3D::fill_lower_triangle(), MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_hessian().
   {
     double matr[9], f, t1, t2;
     double matd[9], g, t3, loc1;
     double adjm[6], dg[9], dobj_df, dobj_dfdg, dobj_dg, dobj_dgdg;
     double J_A[3], J_B[4], J_C[4], J_D[3], J_E[4], J_F[3];
     double A[2];
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
     dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
     dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
     dg[4] = matr[0]*matr[8] - matr[2]*matr[6];
     dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
     dg[7] = matr[2]*matr[3] - matr[0]*matr[5];
     dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
     t1 = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = t1*t1 + 4.0*delta*delta;
     t3 = sqrt(t2);
     g = t1 + t3;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc1 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc1;
     /* Calculate the derivative of the objective function. */
     t3 = 1.0 / t3;
     dobj_df = 2.0 * loc1;
     dobj_dg = -gamma * obj * t3;
     dobj_dfdg = -gamma * dobj_df * t3;
     dobj_dgdg = dobj_dg * ((-gamma - 1.0)*t3 + 4.0*delta*delta/(t2*g));
     /* Calculate adjoint matrix */
     adjm[0] = dobj_df*matd[1] + dobj_dg*dg[1];
     adjm[1] = dobj_df*matd[2] + dobj_dg*dg[2];
     adjm[2] = dobj_df*matd[4] + dobj_dg*dg[4];
     adjm[3] = dobj_df*matd[5] + dobj_dg*dg[5];
     adjm[4] = dobj_df*matd[7] + dobj_dg*dg[7];
     adjm[5] = dobj_df*matd[8] + dobj_dg*dg[8];
     /* Construct gradients */
     g_obj[0] = invR[1][1]*adjm[0]+invR[1][2]*adjm[1];
     g_obj[1] = invR[1][1]*adjm[2]+invR[1][2]*adjm[3];
     g_obj[2] = invR[1][1]*adjm[4]+invR[1][2]*adjm[5];
     /* Start of the Hessian evaluation */
     adjm[0] = dobj_dg*matr[0];
     adjm[1] = dobj_dg*matr[3];
     adjm[2] = dobj_dg*matr[6];
     matd[1] *= dobj_dfdg;
     matd[2] *= dobj_dfdg;
     matd[4] *= dobj_dfdg;
     matd[5] *= dobj_dfdg;
     matd[7] *= dobj_dfdg;
     matd[8] *= dobj_dfdg;
     /* Blocks for the Hessian construction */
     loc1 = dobj_dgdg*dg[1] + matd[1];
     J_A[0] = dobj_df + dg[1]*(matd[1] + loc1);
     J_A[1] = dg[1]*matd[2] + loc1*dg[2];
     J_B[0] = dg[1]*matd[4] + loc1*dg[4];
     J_B[1] = dg[1]*matd[5] + loc1*dg[5] + adjm[2];
     J_C[0] = dg[1]*matd[7] + loc1*dg[7];
     J_C[1] = dg[1]*matd[8] + loc1*dg[8] - adjm[1];
     loc1 = dobj_dgdg*dg[2] + matd[2];
     J_A[2] = dobj_df + dg[2]*(matd[2] + loc1);
     J_B[2] = dg[2]*matd[4] + loc1*dg[4] - adjm[2];
     J_B[3] = dg[2]*matd[5] + loc1*dg[5];
     J_C[2] = dg[2]*matd[7] + loc1*dg[7] + adjm[1];
     J_C[3] = dg[2]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[4] + matd[4];
     J_D[0] = dobj_df + dg[4]*(matd[4] + loc1);
     J_D[1] = dg[4]*matd[5] + loc1*dg[5];
     J_E[0] = dg[4]*matd[7] + loc1*dg[7];
     J_E[1] = dg[4]*matd[8] + loc1*dg[8] + adjm[0];
     loc1 = dobj_dgdg*dg[5] + matd[5];
     J_D[2] = dobj_df + dg[5]*(matd[5] + loc1);
     J_E[2] = dg[5]*matd[7] + loc1*dg[7] - adjm[0];
     J_E[3] = dg[5]*matd[8] + loc1*dg[8];
     loc1 = dobj_dgdg*dg[7] + matd[7];
     J_F[0] = dobj_df + dg[7]*(matd[7] + loc1);
     J_F[1] = dg[7]*matd[8] + loc1*dg[8];
     J_F[2] = dobj_df + dg[8]*(2.0*matd[8] + dobj_dgdg*dg[8]);
     /* Assemble matrix products */
     /* dx / dx */
     A[0] = J_A[0]*invR[1][1] + J_A[1]*invR[1][2];
     A[1] = J_A[1]*invR[1][1] + J_A[2]*invR[1][2];
     h_obj[0][0] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dx / dy */
     A[0] = J_B[0]*invR[1][1] + J_B[1]*invR[1][2];
     A[1] = J_B[2]*invR[1][1] + J_B[3]*invR[1][2];
     h_obj[0][1] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dx / dz */
     A[0] = J_C[0]*invR[1][1] + J_C[1]*invR[1][2];
     A[1] = J_C[2]*invR[1][1] + J_C[3]*invR[1][2];
     h_obj[0][2] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dy / dy */
     A[0] = J_D[0]*invR[1][1] + J_D[1]*invR[1][2];
     A[1] = J_D[1]*invR[1][1] + J_D[2]*invR[1][2];
     h_obj[1][1] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dy / dz */
     A[0] = J_E[0]*invR[1][1] + J_E[1]*invR[1][2];
     A[1] = J_E[2]*invR[1][1] + J_E[3]*invR[1][2];
     h_obj[1][2] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* dz / dz */
     A[0] = J_F[0]*invR[1][1] + J_F[1]*invR[1][2];
     A[1] = J_F[1]*invR[1][1] + J_F[2]*invR[1][2];
     h_obj[2][2] = A[0]*invR[1][1] + A[1]*invR[1][2];
     /* Complete diagonal blocks */
     h_obj.fill_lower_triangle();
     return true;
   }
bool h_gdft_3_v3 (double & obj, Vector3D & g_obj, Matrix3D & h_obj, const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 3259 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_hessian().
   {
     double matr[9], f, t1, t2;
     double matd[9], g, t3, loc1;
     double dg[9], dobj_df, dobj_dfdg, dobj_dg, dobj_dgdg;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     dg[0] = matr[4]*matr[8] - matr[5]*matr[7];
     dg[1] = matr[5]*matr[6] - matr[3]*matr[8];
     dg[2] = matr[3]*matr[7] - matr[4]*matr[6];
     dg[5] = matr[1]*matr[6] - matr[0]*matr[7];
     dg[8] = matr[0]*matr[4] - matr[1]*matr[3];
     t1 = matr[0]*dg[0] + matr[1]*dg[1] + matr[2]*dg[2];
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = t1*t1 + 4.0*delta*delta;
     t3 = sqrt(t2);
     g = t1 + t3;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     loc1 = alpha * pow(2.0, gamma) / pow(g, gamma);
     obj = f * loc1;
     /* Calculate the derivative of the objective function. */
     t3 = 1.0 / t3;
     dobj_df = 2.0 * loc1;
     dobj_dg = -gamma * obj * t3;
     dobj_dfdg = -gamma * dobj_df * t3;
     dobj_dgdg = dobj_dg * ((-gamma - 1.0)*t3 + 4.0*delta*delta/(t2*g));
     /* Construct gradients */
     g_obj[0] = invR[2][2]*(dobj_df*matd[2] + dobj_dg*dg[2]);
     g_obj[1] = invR[2][2]*(dobj_df*matd[5] + dobj_dg*dg[5]);
     g_obj[2] = invR[2][2]*(dobj_df*matd[8] + dobj_dg*dg[8]);
     /* Start of the Hessian evaluation */
     t1 = invR[2][2]*invR[2][2];
     matd[2] *= dobj_dfdg;
     matd[5] *= dobj_dfdg;
     matd[8] *= dobj_dfdg;
     /* Blocks for the Hessian construction */
     loc1 = dobj_dgdg*dg[2] + matd[2];
     h_obj[0][0] = t1*(dobj_df + dg[2]*(matd[2] + loc1));
     h_obj[0][1] = t1*(dg[2]*matd[5] + loc1*dg[5]);
     h_obj[0][2] = t1*(dg[2]*matd[8] + loc1*dg[8]);
     loc1 = dobj_dgdg*dg[5] + matd[5];
     h_obj[1][1] = t1*(dobj_df + dg[5]*(matd[5] + loc1));
     h_obj[1][2] = t1*(dg[5]*matd[8] + loc1*dg[8]);
     h_obj[2][2] = t1*(dobj_df + dg[8]*(2.0*matd[8] + dobj_dgdg*dg[8]));
     /* Complete diagonal blocks */
     h_obj.fill_lower_triangle();
     return true;
   }
double inner (const Vector3D lhs[], const Vector3D rhs[], int n) inline
Dot product for arrays of Vector3Ds. see also operator% .
Definition at line 340 of file includeLinks/Vector3D.hpp.
References i.
Referenced by MsqHessian::cg_solver(), and FeasibleNewton::optimize_vertex_positions().
   {
     int i;
     double dot=0;
     for (i=0; i<n; ++i)
       dot+= lhs[i].mCoords[0] * rhs[i].mCoords[0] +
             lhs[i].mCoords[1] * rhs[i].mCoords[1] +
             lhs[i].mCoords[2] * rhs[i].mCoords[2];
     return dot;
   }
void inv (Matrix3D & Ainv, const Matrix3D & A) inline
Definition at line 555 of file includeLinks/Matrix3D.hpp.
References det(), and Matrix3D::v_.
Referenced by circumcenterC3(), RI_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), RI_DFT::evaluate_element(), and I_DFT::evaluate_element().
{
     double inv_detA = 1 / (det(A));
     Ainv[0][0] = inv_detA*( A.v_[4]*A.v_[8]-A.v_[5]*A.v_[7] );
     Ainv[0][1] = inv_detA*( A.v_[2]*A.v_[7]-A.v_[8]*A.v_[1] );
     Ainv[0][2] = inv_detA*( A.v_[1]*A.v_[5]-A.v_[4]*A.v_[2] );
     Ainv[1][0] = inv_detA*( A.v_[5]*A.v_[6]-A.v_[8]*A.v_[3] );
     Ainv[1][1] = inv_detA*( A.v_[0]*A.v_[8]-A.v_[6]*A.v_[2] );
     Ainv[1][2] = inv_detA*( A.v_[2]*A.v_[3]-A.v_[5]*A.v_[0] );
     Ainv[2][0] = inv_detA*( A.v_[3]*A.v_[7]-A.v_[6]*A.v_[4] );
     Ainv[2][1] = inv_detA*( A.v_[1]*A.v_[6]-A.v_[7]*A.v_[0] );
     Ainv[2][2] = inv_detA*( A.v_[0]*A.v_[4]-A.v_[3]*A.v_[1] );
     return;
   }
double length (Vector3D *const v, int n) inline
Definition at line 400 of file includeLinks/Vector3D.hpp.
References j, and sqrt().
Referenced by TerminationCriterion::accumulate_inner(), Rocblas::axpy_gen(), CImg< uintT >::blur_anisotropic(), Rocblas::calc(), Rocblas::calcDot(), MsqHessian::cg_solver(), COM_F_FUNC2(), GeneralizedConditionNumberQualityMetric::compute_condition_number(), MsqMeshEntity::compute_corner_normals(), MsqMeshEntity::compute_unsigned_area(), In_place_list_n< T, managed >::destroy(), CImg< uintT >::draw_arrow(), AspectRatioGammaQualityMetric::evaluate_element(), Rocblas::gen2arg(), init_structured_mesh(), init_unstructure_mesh(), initUnstructuredMesh(), io_hdf_data(), io_pane_connectivity(), main(), In_place_list_n< T, managed >::merge(), SphericalDomain::normal_at(), FeasibleNewton::optimize_vertex_positions(), tpz_ordered::parse_data(), tpz_fequad::parse_data(), Rocmop::perturb_stationary(), Randomize::randomize_vertex(), TerminationCriterion::reset_inner(), HDF4::SDgetdatastrs(), squared_sum(), MesqPane::tag_create(), and MeshTSTTImpl::tag_create().
   {
     double l=0;
     for (int j=0; j<n; ++j)
       l += v[j].mCoords[0]*v[j].mCoords[0] +
            v[j].mCoords[1]*v[j].mCoords[1] +
            v[j].mCoords[2]*v[j].mCoords[2];
     return msq_stdc::sqrt(l);
   }
double Linf (Vector3D *const v, int n) inline
Definition at line 409 of file includeLinks/Vector3D.hpp.
References i, and max().
Referenced by ConjugateGradient::optimize_vertex_positions(), and TerminationCriterion::reset_inner().
   {
     double max=0;
     //loop over the length of the array
     for(int i=0;i<n;++i){
       if ( max < msq_stdc::fabs(v[i][0]) )   max=msq_stdc::fabs(v[i][0]) ;
       if ( max < msq_stdc::fabs(v[i][1]) )   max=msq_stdc::fabs(v[i][1]) ;
       if ( max < msq_stdc::fabs(v[i][2]) )   max=msq_stdc::fabs(v[i][2]) ;
     }
     //return the value of the largest entry in the array
     return max;
   }
bool m_fcn_2e (double & obj, const Vector3D x[3], const Vector3D & n, const double a, const Exponent & b, const Exponent & c) inline
Definition at line 131 of file includeLinks/MeanRatioFunctions.hpp.
References isqrt3, MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightMeanRatio::evaluate_element().
 {
   double matr[9], f;
   double g;
   /* Calculate M = [A*inv(W) n] */
   matr[0] = x[1][0] - x[0][0];
   matr[1] = (2.0*x[2][0] - x[1][0] - x[0][0])*isqrt3;
   matr[2] = n[0];
   matr[3] = x[1][1] - x[0][1];
   matr[4] = (2.0*x[2][1] - x[1][1] - x[0][1])*isqrt3;
   matr[5] = n[1];
   matr[6] = x[1][2] - x[0][2];
   matr[7] = (2.0*x[2][2] - x[1][2] - x[0][2])*isqrt3;
   matr[8] = n[2];
   /* Calculate det(M). */
   g = matr[0]*(matr[4]*matr[8] - matr[5]*matr[7]) +
       matr[3]*(matr[2]*matr[7] - matr[1]*matr[8]) +
       matr[6]*(matr[1]*matr[5] - matr[2]*matr[4]);
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] +
       matr[3]*matr[3] + matr[4]*matr[4] +
       matr[6]*matr[6] + matr[7]*matr[7];
   /* Calculate objective function. */
   obj = a * pow(f, b) * pow(g, c);
   return true;
 }
bool m_fcn_2i (double & obj, const Vector3D x[3], const Vector3D & n, const double a, const Exponent & b, const Exponent & c, const Vector3D & d) inline
Definition at line 543 of file includeLinks/MeanRatioFunctions.hpp.
References MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightMeanRatio::evaluate_element().
 {
   double matr[9];
   double f;
   double g;
   /* Calculate M = A*inv(W). */
   matr[0] = d[0]*(x[1][0] - x[0][0]);
   matr[1] = d[1]*(x[2][0] - x[0][0]);
   matr[2] = n[0];
   matr[3] = d[0]*(x[1][1] - x[0][1]);
   matr[4] = d[1]*(x[2][1] - x[0][1]);
   matr[5] = n[1];
   matr[6] = d[0]*(x[1][2] - x[0][2]);
   matr[7] = d[1]*(x[2][2] - x[0][2]);
   matr[8] = n[2];
   /* Calculate det(M). */
   g = matr[0]*(matr[4]*matr[8] - matr[5]*matr[7]) +
       matr[3]*(matr[2]*matr[7] - matr[1]*matr[8]) +
       matr[6]*(matr[1]*matr[5] - matr[2]*matr[4]);
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] +
       matr[3]*matr[3] + matr[4]*matr[4] +
       matr[6]*matr[6] + matr[7]*matr[7];
   /* Calculate objective function. */
   obj = a * pow(f, b) * pow(g, c);
   return true;
 }
bool m_fcn_3e (double & obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c) inline
Definition at line 931 of file includeLinks/MeanRatioFunctions.hpp.
References isqrt3, isqrt6, MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightMeanRatio::evaluate_element().
 {
   double matr[9], f;
   double g;
   /* Calculate M = A*inv(W). */
   f       = x[1][0] + x[0][0];
   matr[0] = x[1][0] - x[0][0];
   matr[1] = (2.0*x[2][0] - f)*isqrt3;
   matr[2] = (3.0*x[3][0] - x[2][0] - f)*isqrt6;
   f       = x[1][1] + x[0][1];
   matr[3] = x[1][1] - x[0][1];
   matr[4] = (2.0*x[2][1] - f)*isqrt3;
   matr[5] = (3.0*x[3][1] - x[2][1] - f)*isqrt6;
   f       = x[1][2] + x[0][2];
   matr[6] = x[1][2] - x[0][2];
   matr[7] = (2.0*x[2][2] - f)*isqrt3;
   matr[8] = (3.0*x[3][2] - x[2][2] - f)*isqrt6;
   /* Calculate det(M). */
   g = matr[0]*(matr[4]*matr[8] - matr[5]*matr[7]) +
       matr[1]*(matr[5]*matr[6] - matr[3]*matr[8]) +
       matr[2]*(matr[3]*matr[7] - matr[4]*matr[6]);
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] + matr[2]*matr[2] +
       matr[3]*matr[3] + matr[4]*matr[4] + matr[5]*matr[5] +
       matr[6]*matr[6] + matr[7]*matr[7] + matr[8]*matr[8];
   /* Calculate objective function. */
   obj = a * pow(f, b) * pow(g, c);
   return true;
 }
bool m_fcn_3i (double & obj, const Vector3D x[4], const double a, const Exponent & b, const Exponent & c, const Vector3D & d) inline
Definition at line 1855 of file includeLinks/MeanRatioFunctions.hpp.
References MSQ_MIN, and pow().
Referenced by IdealWeightInverseMeanRatio::evaluate_element(), and IdealWeightMeanRatio::evaluate_element().
 {
   double matr[9], f;
   double g;
   /* Calculate M = A*inv(W). */
   matr[0] = d[0]*(x[1][0] - x[0][0]);
   matr[1] = d[1]*(x[2][0] - x[0][0]);
   matr[2] = d[2]*(x[3][0] - x[0][0]);
   matr[3] = d[0]*(x[1][1] - x[0][1]);
   matr[4] = d[1]*(x[2][1] - x[0][1]);
   matr[5] = d[2]*(x[3][1] - x[0][1]);
   matr[6] = d[0]*(x[1][2] - x[0][2]);
   matr[7] = d[1]*(x[2][2] - x[0][2]);
   matr[8] = d[2]*(x[3][2] - x[0][2]);
   /* Calculate det(M). */
   g = matr[0]*(matr[4]*matr[8] - matr[5]*matr[7]) +
       matr[1]*(matr[5]*matr[6] - matr[3]*matr[8]) +
       matr[2]*(matr[3]*matr[7] - matr[4]*matr[6]);
   if (g < MSQ_MIN) { obj = g; return false; }
   /* Calculate norm(M). */
   f = matr[0]*matr[0] + matr[1]*matr[1] + matr[2]*matr[2] +
       matr[3]*matr[3] + matr[4]*matr[4] + matr[5]*matr[5] +
       matr[6]*matr[6] + matr[7]*matr[7] + matr[8]*matr[8];
   /* Calculate objective function. */
   obj = a * pow(f, b) * pow(g, c);
   return true;
 }
bool m_gdft_2 (double & obj, const Vector3D x[3], const Vector3D & n, const Matrix3D & invR, const Matrix3D & Q, const double alpha = 0.5, const Exponent & gamma = 1.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 147 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), and I_DFT::evaluate_element().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + n[0]*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + n[1]*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + n[2]*invR[2][2];
     /* Calculate det(M). */
     t1 = matr[0]*(matr[4]*matr[8] - matr[5]*matr[7]) +
          matr[3]*(matr[2]*matr[7] - matr[1]*matr[8]) +
          matr[6]*(matr[1]*matr[5] - matr[2]*matr[4]);
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     obj = alpha * pow(2.0, gamma) * f / pow(g, gamma);
     return true;
   }
bool m_gdft_3 (double & obj, const Vector3D x[4], const Matrix3D & invR, const Matrix3D & Q, const double alpha = 1.0/3.0, const Exponent & gamma = 2.0/3.0, const double delta = 0.0, const double beta = 0.0) inline
Definition at line 643 of file includeLinks/I_DFTFamilyFunctions.hpp.
References MSQ_MIN, pow(), and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), and I_DFT::evaluate_element().
   {
     double matr[9], f, t1, t2;
     double matd[9], g;
     /* Calculate M = A*inv(R). */
     f       = x[1][0] - x[0][0];
     g       = x[2][0] - x[0][0];
     t1      = x[3][0] - x[0][0];
     matr[0] = f*invR[0][0];
     matr[1] = f*invR[0][1] + g*invR[1][1];
     matr[2] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][1] - x[0][1];
     g       = x[2][1] - x[0][1];
     t1      = x[3][1] - x[0][1];
     matr[3] = f*invR[0][0];
     matr[4] = f*invR[0][1] + g*invR[1][1];
     matr[5] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     f       = x[1][2] - x[0][2];
     g       = x[2][2] - x[0][2];
     t1      = x[3][2] - x[0][2];
     matr[6] = f*invR[0][0];
     matr[7] = f*invR[0][1] + g*invR[1][1];
     matr[8] = f*invR[0][2] + g*invR[1][2] + t1*invR[2][2];
     /* Calculate det(M). */
     t1 = matr[0]*(matr[4]*matr[8] - matr[5]*matr[7]) +
          matr[3]*(matr[2]*matr[7] - matr[1]*matr[8]) +
          matr[6]*(matr[1]*matr[5] - matr[2]*matr[4]);
     if ((0.0 == delta) && (t1 < MSQ_MIN)) { obj = t1; return false; }
     /* Calculate sqrt(det(M)^2 + 4*delta^2) and denominator. */
     t2 = sqrt(t1*t1 + 4.0*delta*delta);
     g = t1 + t2;
     /* Calculate N = M - beta*Q. */
     matd[0] = matr[0] - beta*Q[0][0];
     matd[1] = matr[1] - beta*Q[0][1];
     matd[2] = matr[2] - beta*Q[0][2];
     matd[3] = matr[3] - beta*Q[1][0];
     matd[4] = matr[4] - beta*Q[1][1];
     matd[5] = matr[5] - beta*Q[1][2];
     matd[6] = matr[6] - beta*Q[2][0];
     matd[7] = matr[7] - beta*Q[2][1];
     matd[8] = matr[8] - beta*Q[2][2];
     /* Calculate norm(N) */
     f = matd[0]*matd[0] + matd[1]*matd[1] + matd[2]*matd[2] +
         matd[3]*matd[3] + matd[4]*matd[4] + matd[5]*matd[5] +
         matd[6]*matd[6] + matd[7]*matd[7] + matd[8]*matd[8];
     /* Calculate objective function. */
     obj = alpha * pow(2.0, gamma) * f / pow(g, gamma);
     return true;
   }
unsigned int major_version_number ()
Definition at line 46 of file Misc/MesquiteVersion.cpp.
References MSQ_MAJOR_VERSION.
 {
   return MSQ_MAJOR_VERSION;
 }
int matmult (Matrix3D & C, const Matrix3D & A, const Matrix3D & B) inline
Definition at line 470 of file includeLinks/Matrix3D.hpp.
References i, j, and k.
   {
     double sum;
     const double* row_i;
     const double* col_k;
     for (size_t i=0; i<3; ++i)
       for (size_t k=0; k<3; ++k)
         {
           row_i  = &(A[i][0]);
           col_k  = &(B[0][k]);
           sum = 0;
           for (size_t j=0; j<3; ++j)
             {
               sum  += *row_i * *col_k;
               row_i++;
               col_k += 3;
             }
           C[i][k] = sum;
         }
     return 0;
   }
unsigned int minor_version_number ()
Definition at line 51 of file Misc/MesquiteVersion.cpp.
References MSQ_MINOR_VERSION.
 {
   return MSQ_MINOR_VERSION;
 }
T Mesquite::MSQ_MAX_2 (T a, T b) inline
Definition at line 178 of file Mesquite.hpp.
 { return a > b ? a : b; }
T Mesquite::MSQ_MIN_2 (T a, T b) inline
Definition at line 177 of file Mesquite.hpp.
 { return a < b ? a : b; }
void msq_sigint_handler (int)
Definition at line 38 of file Misc/MsqInterrupt.cpp.
References oldHandler, MsqInterrupt::set_handler(), and MsqInterrupt::set_interrupt().
Referenced by MsqInterrupt::set_handler().
 {
   MsqInterrupt::set_interrupt();
   if (oldHandler != SIG_DFL && oldHandler != SIG_IGN)
     oldHandler( SIGINT );
   MsqInterrupt::set_handler();
 }
const Matrix3D mult_element (const Matrix3D & A, const Matrix3D & B) inline
Multiplies entry by entry. This is NOT a matrix multiplication.
Definition at line 312 of file includeLinks/Matrix3D.hpp.
References i.
   {
     Matrix3D tmp;
     size_t i;
     for (i=0; i<3; ++i) {
       tmp[i][0] = A[i][0] * B[i][0];
       tmp[i][1] = A[i][1] * B[i][1];
       tmp[i][2] = A[i][2] * B[i][2];
     }
     return tmp;
   }
bool operator!= (const Matrix3D & lhs, const Matrix3D & rhs) inline
Definition at line 278 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
   {
     return (memcmp(lhs.v_, rhs.v_, 9*sizeof(double)) != 0);
   }
bool operator!= (const Vector3D & v1, const Vector3D & v2) inline
Definition at line 442 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
     { return v1.mCoords[0] != v2.mCoords[0] ||
              v1.mCoords[1] != v2.mCoords[1] ||
              v1.mCoords[2] != v2.mCoords[2]; }
double operator% (const Vector3D & lhs, const Vector3D & rhs) inline
Definition at line 331 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     return( lhs.mCoords[0] * rhs.mCoords[0] +
             lhs.mCoords[1] * rhs.mCoords[1] +
             lhs.mCoords[2] * rhs.mCoords[2] );
   }
double operator% (const double scalar, const Vector3D & rhs) inline
Definition at line 352 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     return( scalar * (rhs.mCoords[0] + rhs.mCoords[1] + rhs.mCoords[2]) );
   }
double operator% (const Vector3D & lhs, const double scalar) inline
Definition at line 357 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     return( scalar * (lhs.mCoords[0] + lhs.mCoords[1] + lhs.mCoords[2]) );
   }
const Vector3D operator* (const Vector3D & lhs, const double scalar) inline
Definition at line 309 of file includeLinks/Vector3D.hpp.
References Vector3D::x(), Vector3D::y(), and Vector3D::z().
   {
     return Vector3D(lhs.x() * scalar,
                     lhs.y() * scalar,
                     lhs.z() * scalar);
   }
const Vector3D operator* (const double scalar, const Vector3D & rhs) inline
Definition at line 316 of file includeLinks/Vector3D.hpp.
References Vector3D::x(), Vector3D::y(), and Vector3D::z().
   {
     return Vector3D(rhs.x() * scalar,
                     rhs.y() * scalar,
                     rhs.z() * scalar);
   }
const Vector3D operator* (const Vector3D & lhs, const Vector3D & rhs) inline
Definition at line 362 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
   {
     return Vector3D(lhs.mCoords[1]*rhs.mCoords[2]-lhs.mCoords[2]*rhs.mCoords[1],
                     lhs.mCoords[2]*rhs.mCoords[0]-lhs.mCoords[0]*rhs.mCoords[2],
                     lhs.mCoords[0]*rhs.mCoords[1]-lhs.mCoords[1]*rhs.mCoords[0]);
   }
const Matrix3D operator* (const Matrix3D & A, const Matrix3D & B) inline
Returns
A*B
Definition at line 436 of file includeLinks/Matrix3D.hpp.
References i, j, and k.
   {
     Matrix3D tmp;
     double sum;
     for (size_t i=0; i<3; ++i)
       for (size_t k=0; k<3; ++k)
         {
           sum = 0;
           for (size_t j=0; j<3; j++)
             sum = sum +  A[i][j] * B[j][k];
           tmp[i][k] = sum;
         }
     return tmp;
   }
const Matrix3D operator* (const double & s, const Matrix3D & A) inline
friend function to allow for commutatative property of scalar mulitplication.
Definition at line 463 of file includeLinks/Matrix3D.hpp.
    {
      return (A.operator*(s));
    }
const Vector3D operator* (const Matrix3D & A, const Vector3D & x) inline
Computes .
Definition at line 494 of file includeLinks/Matrix3D.hpp.
References i.
   {
     Vector3D tmp; // initializes to 0
     for (size_t i=0; i<3; ++i)
       {
         const double* rowi = A[i];
         tmp[i] = rowi[0]*x[0] + rowi[1]*x[1] + rowi[2]*x[2];
       }
     return tmp;
   }
const Vector3D operator* (const Vector3D & x, const Matrix3D & A) inline
Computes .
This function implicitly considers the transpose of vector x times the matrix A and it is implicit that the returned vector must be transposed.
Definition at line 510 of file includeLinks/Matrix3D.hpp.
References i, and j.
   {
     Vector3D res(0., 0., 0.);
     for (size_t i=0; i<3; ++i)
       {
         const double* rowi = A[i];
         for (size_t j=0; j<3; ++j)
           res[j] += rowi[j] * x[i];
       }
     return res;
   }
const Matrix3D operator+ (const Matrix3D & A, const Matrix3D & B) inline
Returns
A+B
Definition at line 284 of file includeLinks/Matrix3D.hpp.
References i.
   {
     Matrix3D tmp;
     size_t i;
     for (i=0; i<3; ++i) {
       tmp[i][0] = A[i][0] + B[i][0];
       tmp[i][1] = A[i][1] + B[i][1];
       tmp[i][2] = A[i][2] + B[i][2];
     }
     return tmp;
   }
const Vector3D operator+ (const Vector3D & lhs, const Vector3D & rhs) inline
Definition at line 295 of file includeLinks/Vector3D.hpp.
References Vector3D::x(), Vector3D::y(), and Vector3D::z().
   {
     return Vector3D(lhs.x() + rhs.x(),
                     lhs.y() + rhs.y(),
                     lhs.z() + rhs.z());
   }
const Matrix3D operator- (const Matrix3D & A, const Matrix3D & B) inline
Returns
A-B
Definition at line 298 of file includeLinks/Matrix3D.hpp.
References i.
   {
     Matrix3D tmp;
     size_t i;
     for (i=0; i<3; ++i) {
       tmp[i][0] = A[i][0] - B[i][0];
       tmp[i][1] = A[i][1] - B[i][1];
       tmp[i][2] = A[i][2] - B[i][2];
     }
     return tmp;
   }
const Vector3D operator- (const Vector3D & lhs, const Vector3D & rhs) inline
Definition at line 302 of file includeLinks/Vector3D.hpp.
References Vector3D::x(), Vector3D::y(), and Vector3D::z().
   {
     return Vector3D(lhs.x() - rhs.x(),
                     lhs.y() - rhs.y(),
                     lhs.z() - rhs.z());
   }
const Vector3D operator/ (const Vector3D & lhs, const double scalar) inline
Definition at line 323 of file includeLinks/Vector3D.hpp.
References Vector3D::x(), Vector3D::y(), and Vector3D::z().
   {
     assert (scalar != 0);
     return Vector3D(lhs.x() / scalar,
                     lhs.y() / scalar,
                     lhs.z() / scalar);
   }
msq_stdio::ostream & operator<< (msq_stdio::ostream & str, Mesquite::StopWatchCollection & coll)
Definition at line 311 of file Misc/MsqTimer.cpp.
References StopWatchCollection::get_keys_sorted_by_time(), StopWatchCollection::get_string(), i, StopWatchCollection::number_of_starts(), and StopWatchCollection::total_time().
 {
   msq_std::vector<Mesquite::StopWatchCollection::Key> sorted_keys;
   Mesquite::GlobalStopWatches.get_keys_sorted_by_time(sorted_keys);
   int number_of_keys=sorted_keys.size();
   int i =0;
   str<<"\nTIME        | NUM. STARTS | TIMER NAME ("<<number_of_keys<<" timers)\n";
   for(i=0;i<number_of_keys;++i){
           str<<msq_stdio::setiosflags(msq_stdio::ios::left)
              <<msq_stdio::setw(13)
              <<Mesquite::GlobalStopWatches.total_time(sorted_keys[i])
              <<" "
              <<msq_stdio::setw(13)
              <<Mesquite::GlobalStopWatches.number_of_starts(sorted_keys[i])
              <<" "
              <<Mesquite::GlobalStopWatches.get_string(sorted_keys[i])
              <<msq_stdio::endl;
   }
   return str;
 }
msq_stdio::ostream & operator<< (msq_stdio::ostream & s, const Matrix3D & A) inline
Definition at line 250 of file includeLinks/Matrix3D.hpp.
References i, j, and s.
   {
     for (size_t i=0; i<3; ++i)
       {
         for (size_t j=0; j<3; ++j)
           s << A[i][j] << " ";
         s << "\n";
       }
     return s;
   }
msq_stdio::ostream & operator<< (msq_stdio::ostream & s, const MsqHessian & h)
Prints out the MsqHessian blocks.
Definition at line 507 of file Misc/MsqHessian.cpp.
References i, j, MsqHessian::mColIndex, MsqHessian::mEntries, MsqHessian::mRowStart, MsqHessian::mSize, and s.
 {
   size_t i,j;
   s << "MsqHessian of size: " << h.mSize <<"x"<< h.mSize << "\n";
   for (i=0; i<h.mSize; ++i) {
     s << " ROW " << i << " ------------------------\n";
     for (j=h.mRowStart[i]; j<h.mRowStart[i+1]; ++j) {
       s << "   column " << h.mColIndex[j] << " ----\n";
       s << h.mEntries[j];
     }
   }
   return s;
 }
msq_stdio::ostream & operator<< (msq_stdio::ostream & s, const Mesquite::Vector3D & v)
Definition at line 44 of file Misc/Vector3D.cpp.
 {
     return s << v[0] << ' ' << v[1] << ' ' << v[2] << ' ' << msq_stdio::endl;
 }
ostream & operator<< (ostream & stream, const MsqMeshEntity & entity)
Definition at line 919 of file Mesh/MsqMeshEntity.cpp.
References i, MsqMeshEntity::vertex_count(), and MsqMeshEntity::vertexIndices.
 {
   size_t num_vert = entity.vertex_count();
   stream << "MsqMeshEntity " << &entity << " with vertices ";
   for (size_t i = 0; i < num_vert; ++i)
     stream << entity.vertexIndices[i] << " ";
   stream << endl;
   return stream;
 }
ostream & operator<< (ostream & stream, const PatchData & pd)
Definition at line 1270 of file Mesh/PatchData.cpp.
References PatchData::AVERAGE_DET3D, PatchData::computedInfos, PatchData::domainSet, PatchData::elementArray, PatchData::ELEMENTS_ON_VERTEX_PATCH, PatchData::GLOBAL_PATCH, PatchData::have_computed_info(), PatchData::haveComputedInfos, HEXAHEDRON, i, j, PatchData::MAX_EDGE_LENGTH, PatchData::MAX_UNSIGNED_AREA, PatchData::meshSet, PatchData::MIN_EDGE_LENGTH, PatchData::MIN_UNSIGNED_AREA, PatchData::MINMAX_SIGNED_DET2D, PatchData::MINMAX_SIGNED_DET3D, MsqVertex::MSQ_COORDS_CHANGED, MsqVertex::MSQ_HARD_FIXED, MsqVertex::MSQ_SOFT_FIXED, PatchData::mType, PatchData::num_elements(), PatchData::num_nodes(), PatchData::num_vertices(), POLYGON, POLYHEDRON, PRISM, PYRAMID, QUADRILATERAL, PatchDataMem< X >::size(), TETRAHEDRON, TRIANGLE, PatchData::vertAdjacencyArray, PatchData::vertAdjacencyOffsets, PatchData::vertexArray, and PatchData::VERTICES_ON_VERTEX_PATCH.
 {
    size_t i;
    stream << "Vertices: " << endl;
    for (i = 0; i < pd.num_nodes(); ++i)
    {
       if (i == pd.num_vertices())
         stream << "Higher-Order Nodes: " << endl;
       stream << i << ". ("
              << pd.vertexArray[i].x() << ","
              << pd.vertexArray[i].y() << ","
              << pd.vertexArray[i].z()
              << ") ";
       if (pd.vertexArray[i].is_flag_set( MsqVertex::MSQ_SOFT_FIXED ))
         stream << "S";
       if (pd.vertexArray[i].is_flag_set( MsqVertex::MSQ_HARD_FIXED ))
         stream << "H";
       if (pd.vertexArray[i].is_flag_set( MsqVertex::MSQ_COORDS_CHANGED ))
         stream << "C";
       if (pd.vertAdjacencyArray.size())
       {
         size_t j = pd.vertAdjacencyOffsets[i];
         size_t end = pd.vertAdjacencyOffsets[i+1];
         for ( ; j < end; ++j )
           stream << " " << pd.vertAdjacencyArray[j];
       }
       stream << endl;
    }
    stream << "Elements: " << endl;
    for (i = 0; i < pd.num_elements(); ++i)
    {
       stream << i << ". ";
       switch (pd.elementArray[i].get_element_type()) {
         case POLYGON:       stream << "Polygon";    break;
         case TRIANGLE:      stream << "Tri";        break;
         case QUADRILATERAL: stream << "Quad";       break;
         case POLYHEDRON:    stream << "Polyhedron"; break;
         case TETRAHEDRON:   stream << "Tet";        break;
         case HEXAHEDRON:    stream << "Hex";        break;
         case PRISM:         stream << "Wedge";      break;
         case PYRAMID:       stream << "Pyr";        break;
         default:            stream << "Unknown";    break;
       }
       stream << pd.elementArray[i].node_count() << ": ";
       for (size_t j = 0; j < pd.elementArray[i].node_count(); ++j)
         stream << pd.elementArray[i].get_vertex_index_array()[j] << " ";
       stream << endl;
    }
    stream << endl;
    stream << "MeshSet: " << (pd.meshSet?"yes":"no") << endl;
    stream << "domainSet: " << (pd.domainSet?"true":"false") << endl;
    stream << "mType: " << (pd.mType==PatchData::VERTICES_ON_VERTEX_PATCH?"vert-on-vert":
                            pd.mType==PatchData::ELEMENTS_ON_VERTEX_PATCH?"elem-on-vert":
                            pd.mType==PatchData::GLOBAL_PATCH?"global":"unknown") << endl;
    if (pd.haveComputedInfos)
    {
      stream << "ComputedInfos:" << endl;
      if (pd.have_computed_info(PatchData::MIN_UNSIGNED_AREA))
        stream << "\t MIN_UNSINGED_AREA = " << pd.computedInfos[PatchData::MIN_UNSIGNED_AREA] << endl;
      if (pd.have_computed_info(PatchData::MAX_UNSIGNED_AREA))
        stream << "\t MAX_UNSIGNED_AREA = " << pd.computedInfos[PatchData::MAX_UNSIGNED_AREA] << endl;
      if (pd.have_computed_info(PatchData::MIN_EDGE_LENGTH))
        stream << "\t MIN_EDGE_LENGTH = " << pd.computedInfos[PatchData::MIN_EDGE_LENGTH] << endl;
      if (pd.have_computed_info(PatchData::MAX_EDGE_LENGTH))
        stream << "\t MAX_EDGE_LENGTH = " << pd.computedInfos[PatchData::MAX_EDGE_LENGTH] << endl;
      if (pd.have_computed_info(PatchData::MINMAX_SIGNED_DET2D))
        stream << "\t MINMAX_SIGNED_DET2D = " << pd.computedInfos[PatchData::MINMAX_SIGNED_DET2D] << endl;
      if (pd.have_computed_info(PatchData::MINMAX_SIGNED_DET3D))
        stream << "\t MINMAX_SIGNED_DET3D = " << pd.computedInfos[PatchData::MINMAX_SIGNED_DET3D] << endl;
      if (pd.have_computed_info(PatchData::AVERAGE_DET3D))
        stream << "\t AVERAGE_DET3D = " << pd.computedInfos[PatchData::AVERAGE_DET3D] << endl;
   }
   return stream << endl;
 }
bool operator== (const Matrix3D & lhs, const Matrix3D & rhs) inline
Definition at line 274 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
   {
     return (memcmp(lhs.v_, rhs.v_, 9*sizeof(double)) == 0);
   }
bool operator== (const Vector3D & v1, const Vector3D & v2) inline
Definition at line 437 of file includeLinks/Vector3D.hpp.
References Vector3D::mCoords.
     { return v1.mCoords[0] == v2.mCoords[0] &&
              v1.mCoords[1] == v2.mCoords[1] &&
              v1.mCoords[2] == v2.mCoords[2]; }
msq_stdio::istream & operator>> (msq_stdio::istream & s, Matrix3D & A) inline
Definition at line 261 of file includeLinks/Matrix3D.hpp.
References i, j, and s.
   {
     for (size_t i=0; i<3; i++)
       for (size_t j=0; j<3; j++)
         {
           s >>  A[i][j];
         }
     return s;
   }
void plusEqaA (Matrix3D & B, const double a, const Matrix3D & A) inline
Definition at line 543 of file includeLinks/Matrix3D.hpp.
References Matrix3D::v_.
{
     B.v_[0] += a*A.v_[0]; B.v_[1] += a*A.v_[1]; B.v_[2] += a*A.v_[2];
     B.v_[3] += a*A.v_[3]; B.v_[4] += a*A.v_[4]; B.v_[5] += a*A.v_[5];
     B.v_[6] += a*A.v_[6]; B.v_[7] += a*A.v_[7]; B.v_[8] += a*A.v_[8];
   }
void plusEqAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) inline
Definition at line 529 of file includeLinks/Matrix3D.hpp.
References Vector3D::mCoords, and Matrix3D::v_.
Referenced by axpy().
   {
      v.mCoords[0] += A.v_[0]*x[0] + A.v_[1]*x.mCoords[1] + A.v_[2]*x.mCoords[2];
      v.mCoords[1] += A.v_[3]*x[0] + A.v_[4]*x.mCoords[1] + A.v_[5]*x.mCoords[2];
      v.mCoords[2] += A.v_[6]*x[0] + A.v_[7]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
void plusEqTransAx (Vector3D & v, const Matrix3D & A, const Vector3D & x) inline
Definition at line 536 of file includeLinks/Matrix3D.hpp.
References Vector3D::mCoords, and Matrix3D::v_.
Referenced by axpy().
   {
      v.mCoords[0] += A.v_[0]*x.mCoords[0] + A.v_[3]*x.mCoords[1] + A.v_[6]*x.mCoords[2];
      v.mCoords[1] += A.v_[1]*x.mCoords[0] + A.v_[4]*x.mCoords[1] + A.v_[7]*x.mCoords[2];
      v.mCoords[2] += A.v_[2]*x.mCoords[0] + A.v_[5]*x.mCoords[1] + A.v_[8]*x.mCoords[2];
   }
double pow (double value, const Exponent & exp) inline
Definition at line 89 of file includeLinks/Exponent.hpp.
References Exponent::raise().
Referenced by CImg< uintT >::_draw_ellipse(), QualityMetric::average_metrics(), QualityAssessor::Assessor::calculate_histogram_range(), cbrt(), cbrt_sqr(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), Alg_Metric_Base_3::compute_shape(), Alg_Metric_Base_3::compute_skew(), dist(), MVec::distance_between(), CImg< uintT >::draw_axis(), CImg< uintT >::edge_tensors(), CImg< T >::_cimg_math_parser::eval(), sRI_DFT::evaluate_element(), sI_DFT::evaluate_element(), PowerQualityMetric::evaluate_element(), PowerQualityMetric::evaluate_vertex(), g_fcn_2e(), g_fcn_2i(), g_fcn_3e(), g_fcn_3e_v3(), g_fcn_3i(), g_fcn_ridft2(), g_fcn_ridft3(), g_gdft_2(), g_gdft_2_v0(), g_gdft_2_v1(), g_gdft_2_v2(), g_gdft_3(), g_gdft_3_v0(), g_gdft_3_v1(), g_gdft_3_v2(), g_gdft_3_v3(), CImg< uintT >::get_displacement_field(), CImg< uintT >::get_select_graph(), h_fcn_2e(), h_fcn_2i(), h_fcn_3e(), h_fcn_3e_v3(), h_fcn_3i(), h_fcn_ridft2(), h_fcn_ridft3(), h_gdft_2(), h_gdft_2_v0(), h_gdft_2_v1(), h_gdft_2_v2(), h_gdft_3(), h_gdft_3_v0(), h_gdft_3_v1(), h_gdft_3_v2(), h_gdft_3_v3(), TargetCalculator::initialize_default_target_matrices(), CImg< uintT >::LabtoXYZ(), m_fcn_2e(), m_fcn_2i(), m_fcn_3e(), m_fcn_3i(), m_fcn_ridft2(), m_fcn_ridft3(), m_gdft_2(), m_gdft_3(), CImg< uintT >::pow(), CImg< uintT >::RGBtoHSI(), IdealWeightInverseMeanRatio::set_metric_power(), CImg< uintT >::sharpen(), Exponent::std_pow(), and TRAIL_TimeString().
   { return exp.raise( value ); }
void print_timing_diagnostics (int debugflag) inline
Definition at line 188 of file includeLinks/MsqTimer.hpp.
References GlobalStopWatches, and MSQ_DBGOUT.
     { MSQ_DBGOUT(debugflag) << GlobalStopWatches; }
void print_timing_diagnostics (msq_stdio::ostream & stream) inline
Definition at line 191 of file includeLinks/MsqTimer.hpp.
References GlobalStopWatches.
     { stream << GlobalStopWatches; }
static msq_std::string Mesquite::process_tstt_error (TSTTB::Error & tstt_err) inline static
Definition at line 9 of file src/Mesh/TSTTUtil.hpp.
References MSQ_DBGOUT.
 {
   msq_std::string str;
   msq_std::string result("TSTT ERROR: ");
   result += tstt_err.getNote();
   MSQ_DBGOUT(1) << "TSTT Error:" << msq_std::endl;
   MSQ_DBGOUT(1) << tstt_err.getNote() << msq_std::endl;
   tstt_err.getDescription(str);
   MSQ_DBGOUT(1) << str << msq_std::endl;
   MSQ_DBGOUT(1) << tstt_err.getTrace() << msq_std::endl;
   return result;
 }
static msq_std::string Mesquite::process_tstt_error (TSTTB::Error & tstt_err) inline static
Definition at line 9 of file includeLinks/TSTTUtil.hpp.
References MSQ_DBGOUT.
Referenced by MeshTSTTImpl::cache_adjacent_elements(), DomainTSTT::closest_point(), GeomEntTSTT::closest_point(), GeomTSTT::create(), MeshTSTTImpl::element_get_attached_vertex_count(), MeshTSTTImpl::element_get_topology(), MeshTSTTImpl::element_iterator(), MeshTSTTImpl::elements_get_attached_vertices(), MeshTSTTImpl::elements_get_topologies(), MeshTSTTImpl::get_all_mesh(), MeshTSTTImpl::get_all_sizes(), MeshTSTTImpl::get_geometric_dimension(), MeshTSTTImpl::get_vertex_use_count(), MeshTSTTImpl::MeshTSTTImpl(), DomainTSTT::normal_at(), GeomEntTSTT::normal_at(), TSTTIterator::operator++(), TSTTArrIter::operator++(), TSTTIterator::restart(), TSTTArrIter::restart(), MeshTSTTImpl::set_active_set(), MeshTSTTImpl::set_int_tag(), DomainTSTT::snap_to(), GeomEntTSTT::snap_to(), MeshTSTTImpl::tag_create(), MeshTSTTImpl::tag_delete(), MeshTSTTImpl::tag_get(), MeshTSTTImpl::tag_get_data(), MeshTSTTImpl::tag_properties(), MeshTSTTImpl::tag_set_data(), TSTTIterator::TSTTIterator(), MeshTSTTImpl::vertex_get_byte(), MeshTSTTImpl::vertex_is_fixed(), MeshTSTTImpl::vertex_iterator(), MeshTSTTImpl::vertex_set_byte(), MeshTSTTImpl::vertex_set_coordinates(), MeshTSTTImpl::vertices_are_on_boundary(), MeshTSTTImpl::vertices_get_byte(), MeshTSTTImpl::vertices_get_coordinates(), MeshTSTTImpl::vertices_set_byte(), MeshTSTTImpl::~MeshTSTTImpl(), and TSTTArrIter::~TSTTArrIter().
 {
   msq_std::string str;
   msq_std::string result("TSTT ERROR: ");
   result += tstt_err.getNote();
   MSQ_DBGOUT(1) << "TSTT Error:" << msq_std::endl;
   MSQ_DBGOUT(1) << tstt_err.getNote() << msq_std::endl;
   tstt_err.getDescription(str);
   MSQ_DBGOUT(1) << str << msq_std::endl;
   MSQ_DBGOUT(1) << tstt_err.getTrace() << msq_std::endl;
   return result;
 }
void QR (Matrix3D & Q, Matrix3D & R, const Matrix3D & A) inline
Definition at line 593 of file includeLinks/Matrix3D.hpp.
References A, and sqrt().
Referenced by I_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_hessian(), and I_DFT::evaluate_element().
{
     // Compute the QR factorization of A.  This code uses the
     // Modified Gram-Schmidt method for computing the factorization.
     // The Householder version is more stable, but costs twice as many
     // floating point operations.
     Q = A;
     R[0][0] = sqrt(Q[0][0]*Q[0][0] + Q[1][0]*Q[1][0] + Q[2][0]*Q[2][0]);
     R[1][0] = 0.0L;
     R[2][0] = 0.0L;
     Q[0][0] /= R[0][0];
     Q[1][0] /= R[0][0];
     Q[2][0] /= R[0][0];
     R[0][1]  = Q[0][0]*Q[0][1] + Q[1][0]*Q[1][1] + Q[2][0]*Q[2][1];
     Q[0][1] -= Q[0][0]*R[0][1];
     Q[1][1] -= Q[1][0]*R[0][1];
     Q[2][1] -= Q[2][0]*R[0][1];
     R[0][2]  = Q[0][0]*Q[0][2] + Q[1][0]*Q[1][2] + Q[2][0]*Q[2][2];
     Q[0][2] -= Q[0][0]*R[0][2];
     Q[1][2] -= Q[1][0]*R[0][2];
     Q[2][2] -= Q[2][0]*R[0][2];
     R[1][1] = sqrt(Q[0][1]*Q[0][1] + Q[1][1]*Q[1][1] + Q[2][1]*Q[2][1]);
     R[2][1] = 0.0L;
     Q[0][1] /= R[1][1];
     Q[1][1] /= R[1][1];
     Q[2][1] /= R[1][1];
     R[1][2]  = Q[0][1]*Q[0][2] + Q[1][1]*Q[1][2] + Q[2][1]*Q[2][2];
     Q[0][2] -= Q[0][1]*R[1][2];
     Q[1][2] -= Q[1][1]*R[1][2];
     Q[2][2] -= Q[2][1]*R[1][2];
     R[2][2] = sqrt(Q[0][2]*Q[0][2] + Q[1][2]*Q[1][2] + Q[2][2]*Q[2][2]);
     Q[0][2] /= R[2][2];
     Q[1][2] /= R[2][2];
     Q[2][2] /= R[2][2];
     return;
   }
Mesquite::ReleaseType release_type ()
Definition at line 61 of file Misc/MesquiteVersion.cpp.
References ALPHA.
 {
   return Mesquite::ALPHA;
 }
void test_aomd (void)
void timesInvA (Matrix3D & B, const Matrix3D & A) inline
Definition at line 572 of file includeLinks/Matrix3D.hpp.
References det(), and Matrix3D::v_.
Referenced by DistanceFromTarget::compute_T_matrices().
{
     Matrix3D Ainv;
     double inv_detA = 1 / ( det(A) );
     Ainv[0][0] = inv_detA*( A.v_[4]*A.v_[8]-A.v_[5]*A.v_[7] );
     Ainv[0][1] = inv_detA*( A.v_[2]*A.v_[7]-A.v_[8]*A.v_[1] );
     Ainv[0][2] = inv_detA*( A.v_[1]*A.v_[5]-A.v_[4]*A.v_[2] );
     Ainv[1][0] = inv_detA*( A.v_[5]*A.v_[6]-A.v_[8]*A.v_[3] );
     Ainv[1][1] = inv_detA*( A.v_[0]*A.v_[8]-A.v_[6]*A.v_[2] );
     Ainv[1][2] = inv_detA*( A.v_[2]*A.v_[3]-A.v_[5]*A.v_[0] );
     Ainv[2][0] = inv_detA*( A.v_[3]*A.v_[7]-A.v_[6]*A.v_[4] );
     Ainv[2][1] = inv_detA*( A.v_[1]*A.v_[6]-A.v_[7]*A.v_[0] );
     Ainv[2][2] = inv_detA*( A.v_[0]*A.v_[4]-A.v_[3]*A.v_[1] );
     B = B*Ainv;
   }
Matrix3D transpose (const Matrix3D & A) inline
Definition at line 335 of file includeLinks/Matrix3D.hpp.
References i.
Referenced by RI_DFT::compute_element_analytical_hessian(), IdealWeightInverseMeanRatio::compute_element_analytical_hessian(), IdealWeightMeanRatio::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), and sRI_DFT::evaluate_element().
   {
     Matrix3D S;
     size_t i;
     for (i=0; i<3; ++i) {
         S[size_t(0)][i] = A[i][0];
         S[size_t(1)][i] = A[i][1];
         S[size_t(2)][i] = A[i][2];
     }
     return S;
   }
const char * version_string (bool include_build_number = false)
Definition at line 39 of file Misc/MesquiteVersion.cpp.
References MSQ_BUILD_STRING, and MSQ_VERSION_STRING.
Referenced by InstructionQueue::run_instructions().
 {
   if (include_build_number)
     return MSQ_VERSION_STRING MSQ_BUILD_STRING;
   return MSQ_VERSION_STRING;
 }
size_t vertices_in_topology (Mesquite::EntityTopology topo) inline
Definition at line 530 of file MeshInterface.hpp.
 {
   return TopologyInfo::corners( topo );
 }
Variable Documentation
const int DEFAULT_HISTOGRAM_INTERVALS = 10
Definition at line 62 of file QualityAssessor/QualityAssessor.cpp.
Referenced by QualityAssessor::add_quality_assessment().
const msq_std::vector< size_t > dummy_list
Definition at line 37 of file Mesh/MeshImplData.cpp.
Referenced by MeshImplData::element_connectivity(), and MeshImplData::vertex_adjacencies().
const Vector3D dummy_vtx
Definition at line 38 of file Mesh/MeshImplData.cpp.
Referenced by MeshImplData::get_vertex_coords().
Mesquite::StopWatchCollection GlobalStopWatches
Definition at line 186 of file src/Misc/MsqTimer.hpp.
Referenced by print_timing_diagnostics(), FunctionTimer::start(), and FunctionTimer::~FunctionTimer().
const unsigned long GRAD_FLAGS
Initial value:
= TerminationCriterion::GRADIENT_L2_NORM_ABSOLUTE |
                                 TerminationCriterion::GRADIENT_INF_NORM_ABSOLUTE |
                                 TerminationCriterion::GRADIENT_L2_NORM_RELATIVE |
                                 TerminationCriterion::GRADIENT_INF_NORM_RELATIVE
Definition at line 51 of file Control/TerminationCriterion.cpp.
Referenced by TerminationCriterion::accumulate_inner(), TerminationCriterion::accumulate_outer(), TerminationCriterion::reset_inner(), and TerminationCriterion::reset_outer().
const double MSQ_3RT_2_OVER_6RT_3 = msq_stdc::pow(2/MSQ_SQRT_THREE, MSQ_ONE_THIRD) static
Definition at line 130 of file Mesquite.hpp.
Referenced by MsqMeshEntity::compute_corner_matrices(), RI_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), RI_DFT::evaluate_element(), I_DFT::evaluate_element(), and TargetCalculator::initialize_default_target_matrices().
const double MSQ_DBL_MAX = 1.0E30
Definition at line 170 of file Mesquite.hpp.
Referenced by PatchData::get_barrier_delta(), and PatchData::get_minmax_element_unsigned_area().
const double MSQ_DBL_MIN = 1.0E-30
Definition at line 158 of file Mesquite.hpp.
Referenced by ShapeQualityMetric::condition_number_2d(), ShapeQualityMetric::condition_number_3d(), and DistanceFromTarget::get_barrier_function().
const int MSQ_HIST_SIZE =7
Definition at line 121 of file Mesquite.hpp.
const int MSQ_INT_MAX = MSQ_UINT_MAX >> 1
Definition at line 141 of file Mesquite.hpp.
const int MSQ_INT_MIN = ~MSQ_INT_MAX
Definition at line 147 of file Mesquite.hpp.
const double MSQ_MAX = MSQ_DBL_MAX
Definition at line 172 of file Mesquite.hpp.
Referenced by NonSmoothSteepestDescent::find_active_set().
const double MSQ_MAX_CAP = 1.e6
Definition at line 173 of file Mesquite.hpp.
Referenced by QualityMetric::average_metrics(), GeneralizedConditionNumberQualityMetric::compute_condition_number(), ShapeQualityMetric::condition_number_2d(), ShapeQualityMetric::condition_number_3d(), ConditionNumberQualityMetric::evaluate_element(), CornerJacobianQualityMetric::evaluate_element(), UntangleBetaQualityMetric::evaluate_element(), AspectRatioGammaQualityMetric::evaluate_element(), VertexConditionNumberQualityMetric::evaluate_vertex(), and ConjugateGradient::optimize_vertex_positions().
const int MSQ_MAX_NUM_VERT_PER_ENT =8
Definition at line 120 of file Mesquite.hpp.
Referenced by LPtoPTemplate::compute_analytical_gradient(), LPtoPTemplate::compute_analytical_hessian(), TargetCalculator::compute_reference_corner_matrices(), WTargetCalculator::compute_target_matrices(), LVQDTargetCalculator::compute_target_matrices(), sRI_DFT::evaluate_element(), ConditionNumberQualityMetric::evaluate_element(), sI_DFT::evaluate_element(), UntangleBetaQualityMetric::evaluate_element(), PatchData::get_average_Lambda_3d(), and PatchData::get_barrier_delta().
const double MSQ_MIN = MSQ_DBL_MIN
Definition at line 160 of file Mesquite.hpp.
Referenced by QualityMetric::average_metric_and_weights(), QualityMetric::average_metrics(), GeneralizedConditionNumberQualityMetric::compute_condition_number(), ASMQualityMetric::evaluate_element(), AspectRatioGammaQualityMetric::evaluate_element(), g_fcn_2e(), g_fcn_2i(), g_fcn_3e(), g_fcn_3e_v3(), g_fcn_3i(), g_fcn_ridft2(), g_fcn_ridft3(), g_gdft_2(), g_gdft_2_v0(), g_gdft_2_v1(), g_gdft_2_v2(), g_gdft_3(), g_gdft_3_v0(), g_gdft_3_v1(), g_gdft_3_v2(), g_gdft_3_v3(), PatchData::get_barrier_delta(), ConjugateGradient::get_step(), h_fcn_2e(), h_fcn_2i(), h_fcn_3e(), h_fcn_3e_v3(), h_fcn_3i(), h_fcn_ridft2(), h_fcn_ridft3(), h_gdft_2(), h_gdft_2_v0(), h_gdft_2_v1(), h_gdft_2_v2(), h_gdft_3(), h_gdft_3_v0(), h_gdft_3_v1(), h_gdft_3_v2(), h_gdft_3_v3(), m_fcn_2e(), m_fcn_2i(), m_fcn_3e(), m_fcn_3i(), m_fcn_ridft2(), m_fcn_ridft3(), m_gdft_2(), m_gdft_3(), PowerQualityMetric::PowerQualityMetric(), and IdealWeightInverseMeanRatio::set_metric_power().
const double MSQ_ONE_THIRD = 1.0 / 3.0 static
Definition at line 128 of file Mesquite.hpp.
Referenced by cbrt(), RI_DFT::compute_element_analytical_gradient(), I_DFT::compute_element_analytical_gradient(), RI_DFT::compute_element_analytical_hessian(), I_DFT::compute_element_analytical_hessian(), sI_DFT::evaluate_element(), sRI_DFT::evaluate_element(), RI_DFT::evaluate_element(), and I_DFT::evaluate_element().
const double MSQ_SQRT_THREE = msq_stdc::sqrt(3.0) static
Definition at line 123 of file Mesquite.hpp.
Referenced by ConditionNumberQualityMetric::evaluate_element(), UntangleBetaQualityMetric::evaluate_element(), VertexConditionNumberQualityMetric::evaluate_vertex(), and TargetCalculator::initialize_default_target_matrices().
const double MSQ_SQRT_THREE_DIV_TWO =MSQ_SQRT_THREE/2.0 static
Definition at line 124 of file Mesquite.hpp.
const double MSQ_SQRT_THREE_INV =1.0/MSQ_SQRT_THREE static
Definition at line 125 of file Mesquite.hpp.
Referenced by MsqMeshEntity::compute_weighted_jacobian(), ConditionNumberQualityMetric::evaluate_element(), UntangleBetaQualityMetric::evaluate_element(), and VertexConditionNumberQualityMetric::evaluate_vertex().
const double MSQ_SQRT_TWO = msq_stdc::sqrt(2.0) static
Definition at line 122 of file Mesquite.hpp.
Referenced by ConditionNumberQualityMetric::evaluate_element(), UntangleBetaQualityMetric::evaluate_element(), VertexConditionNumberQualityMetric::evaluate_vertex(), and TargetCalculator::initialize_default_target_matrices().
const double MSQ_SQRT_TWO_DIV_SQRT_THREE =MSQ_SQRT_TWO/MSQ_SQRT_THREE static
Definition at line 127 of file Mesquite.hpp.
const double MSQ_SQRT_TWO_INV =1.0/MSQ_SQRT_TWO static
Definition at line 126 of file Mesquite.hpp.
Referenced by MsqMeshEntity::compute_weighted_jacobian().
const double MSQ_TWO_THIRDS = 2.0 / 3.0 static
Definition at line 129 of file Mesquite.hpp.
Referenced by cbrt_sqr(), sI_DFT::evaluate_element(), and I_DFT::I_DFT().
const unsigned MSQ_UINT_MAX = ~(unsigned)0
Definition at line 135 of file Mesquite.hpp.
const unsigned long OF_FLAGS
Initial value:
= TerminationCriterion::QUALITY_IMPROVEMENT_ABSOLUTE |
                                 TerminationCriterion::QUALITY_IMPROVEMENT_RELATIVE |
                                 TerminationCriterion::SUCCESSIVE_IMPROVEMENTS_ABSOLUTE |
                                 TerminationCriterion::SUCCESSIVE_IMPROVEMENTS_RELATIVE
Definition at line 55 of file Control/TerminationCriterion.cpp.
Referenced by TerminationCriterion::accumulate_inner(), TerminationCriterion::accumulate_outer(), TerminationCriterion::reset_inner(), and TerminationCriterion::reset_outer().
msq_sig_handler_t oldHandler = SIG_ERR
Definition at line 35 of file Misc/MsqInterrupt.cpp.
Referenced by MsqInterrupt::allow(), MsqInterrupt::disable(), MsqInterrupt::enable(), msq_sigint_handler(), MsqInterrupt::set_handler(), and MsqInterrupt::~MsqInterrupt().
const char *const VERTEX_BYTE_TAG_NAME = "MesquiteVertexByte"
The name of the tag (integer) that Mesquite will use to store internal data.
Definition at line 64 of file includeLinks/MeshTSTT.hpp.
Referenced by MeshTSTTImpl::MeshTSTTImpl().
const char *const VERTEX_FIXED_TAG_NAME = "MesquiteVertexFixed"
The name of the tag (integer) Mesquite expects to be non-zero for vertices which are not to be moved by Mesquite.
Definition at line 69 of file includeLinks/MeshTSTT.hpp.
Referenced by MeshTSTTImpl::MeshTSTTImpl().
const char *const vtk_type_names
Initial value:
= { "bit",
                                       "char",
                                       "unsigned_char",
                                       "short",
                                       "unsigned_short",
                                       "int",
                                       "unsigned_int",
                                       "long",
                                       "unsigned_long",
                                       "float",
                                       "double",
                                       0 }
Definition at line 1156 of file Mesh/MeshImpl.cpp.
Referenced by MeshImpl::vtk_read_field(), MeshImpl::vtk_read_polydata(), MeshImpl::vtk_read_rectilinear_grid(), MeshImpl::vtk_read_scalar_attrib(), MeshImpl::vtk_read_structured_grid(), MeshImpl::vtk_read_tensor_attrib(), MeshImpl::vtk_read_texture_attrib(), MeshImpl::vtk_read_unstructured_grid(), and MeshImpl::vtk_read_vector_attrib().