Rocstar: Rocstar::TestFixture Namespace Reference
Rocstar::TestFixture Namespace Reference
Namespace for storing simple test utility fixtures.
Functions
double F1 (double x)
Simple test function fixture returns .
double F2 (double x)
Simple test function fixture returns .
Detailed Description
Namespace for storing simple test utility fixtures.
Function Documentation
double Rocstar::TestFixture::F1 (double x)
Simple test function fixture returns .
F1 is a 1st order function in x that has unity integral over [0,1].
Definition at line 34 of file RocstarTest.H.
Referenced by TestingObject< ResultsType >::Test__MidPointQuadrature(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
 { return (2.0*x); };
double Rocstar::TestFixture::F2 (double x)
Simple test function fixture returns .
F2 is quadratic function in x and integrates to unity over [0,1].
Definition at line 40 of file RocstarTest.H.
Referenced by TestingObject< ResultsType >::Test__MidPointQuadrature(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
 { return (3.0*x*x); };