Rocstar: cimg_library Namespace Reference
cimg_library Namespace Reference
This namespace encompasses all classes and functions of the CImg library.
Namespaces
cimg
Namespace that encompasses low-level functions and variables of the CImg Library.
Classes
struct CImg
Class representing an image (up to 4 dimensions wide), each pixel being of type T.
struct CImgArgumentException
struct CImgDisplay
This class represents a window which can display CImg images and handles mouse and keyboard events.
struct CImgDisplayException
struct CImgException
Instances of this class are thrown when errors occur during a CImg library function call.
struct CImgInstanceException
struct CImgIOException
struct CImgList
Class representing list of images CImg<T>.
struct CImgWarningException
Functions
_cimg_create_ext_operators (bool) _cimg_create_ext_operators(unsigned char) _cimg_create_ext_operators(char) _cimg_create_ext_operators(signed char) _cimg_create_ext_operators(unsigned short) _cimg_create_ext_operators(short) _cimg_create_ext_operators(unsigned int) _cimg_create_ext_operators(int) _cimg_create_ext_operators(unsigned long) _cimg_create_ext_operators(long) _cimg_create_ext_operators(float) _cimg_create_ext_operators(double) template< typename T > inline CImg< _cimg_Tfloat > operator+(const char *const expression
template<typename T >
CImg< _cimg_Tfloat > operator- (const char *const expression, const CImg< T > &img)
template<typename T >
CImg< _cimg_Tfloat > operator* (const char *const expression, const CImg< T > &img)
template<typename T >
CImg< _cimg_Tfloat > operator/ (const char *const expression, const CImg< T > &img)
template<typename T >
CImg< T > operator& (const char *const expression, const CImg< T > &img)
template<typename T >
CImg< T > operator| (const char *const expression, const CImg< T > &img)
template<typename T >
CImg< T > operator^ (const char *const expression, const CImg< T > &img)
template<typename T >
CImg< _cimg_Tfloat > sqr (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > sqrt (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > exp (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > log (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > log10 (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > abs (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > cos (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > sin (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > tan (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > acos (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > asin (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > atan (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > cosh (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > sinh (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > tanh (const CImg< T > &instance)
template<typename T >
CImg< T > transpose (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > invert (const CImg< T > &instance)
template<typename T >
CImg< _cimg_Tfloat > pseudoinvert (const CImg< T > &instance)
Variables
const CImg< T > &img return img expression
Detailed Description
This namespace encompasses all classes and functions of the CImg library.
This namespace is defined to avoid functions and class names collisions that could happen with the include of other C++ header files. Anyway, it should not happen often and you should reasonnably start most of your CImg-based programs with
#include "CImg.h"
using namespace cimg_library;
to simplify the declaration of CImg Library variables afterwards.
Function Documentation
cimg_library::_cimg_create_ext_operators (bool) const
CImg<_cimg_Tfloat> cimg_library::abs (const CImg< T > & instance) inline
Definition at line 6031 of file CImg.h.
References CImg< T >::get_abs().
Referenced by cimg_library::cimg::abs().
{
     return instance.get_abs();
   }
CImg<_cimg_Tfloat> cimg_library::acos (const CImg< T > & instance) inline
Definition at line 6051 of file CImg.h.
References CImg< T >::get_acos().
Referenced by CImg< uintT >::acos(), angle(), nvc::angle(), nvc::angle_unitized(), RFC_Window_overlay::comp_angle_defect(), Rocmop::compute_medial_quadric(), CFacet::contains_point(), RFC_Window_overlay::detect_features(), Halfedge::dihedral_angle(), RFC_Window_overlay::dump_strong_edges(), Window_manifold_2::elements_to_nodes(), CImg< T >::_cimg_math_parser::eval(), FaceOffset_3::eval_angle(), FaceOffset_3::filter_and_identify_ridge_edges(), Overlay_primitives::get_face_normal(), FaceOffset_3::get_fangle_turn_radians(), Vector3D::interior_angle(), RFC_Window_overlay::is_rstrong_ea(), Rocblas::acosa< T >::operator()(), RFC_Window_overlay::print_features(), Rocmop::redistribute_vertices_smooth(), and CImg< uintT >::RGBtoHSI().
{
     return instance.get_acos();
   }
CImg<_cimg_Tfloat> cimg_library::asin (const CImg< T > & instance) inline
Definition at line 6056 of file CImg.h.
References CImg< T >::get_asin().
Referenced by CImg< uintT >::_display_object3d(), CImg< uintT >::asin(), CImg< T >::_cimg_math_parser::eval(), and main().
{
     return instance.get_asin();
   }
CImg<_cimg_Tfloat> cimg_library::atan (const CImg< T > & instance) inline
Definition at line 6061 of file CImg.h.
References CImg< T >::get_atan().
Referenced by CImg< uintT >::atan(), Rocmop::eigen_analyze_vertex(), and CImg< T >::_cimg_math_parser::eval().
{
     return instance.get_atan();
   }
CImg<_cimg_Tfloat> cimg_library::cos (const CImg< T > & instance) inline
Definition at line 6036 of file CImg.h.
References CImg< T >::get_cos().
Referenced by CImg< uintT >::_draw_ellipse(), CImg< uintT >::blur_anisotropic(), CImg< uintT >::cone3d(), CImg< uintT >::cos(), CImg< uintT >::cylinder3d(), RFC_Window_overlay::detect_features(), CImg< uintT >::draw_arrow(), CImg< uintT >::eigen(), CImg< T >::_cimg_math_parser::eval(), CImg< uintT >::FFT(), func2(), func3(), CImg< uintT >::get_rotate(), Vortex_flow::get_velocity(), LeVeque_flow::get_velocity(), CImg< uintT >::HSItoRGB(), RFC_Window_overlay::init_feature_parameters(), main(), rational_rotation_approximation(), FaceOffset_3::reset_default_parameters(), CImg< uintT >::rotation_matrix(), FaceOffset_3::set_fangle_turn(), and CImg< uintT >::torus3d().
{
     return instance.get_cos();
   }
CImg<_cimg_Tfloat> cimg_library::cosh (const CImg< T > & instance) inline
Definition at line 6066 of file CImg.h.
References CImg< T >::get_cosh().
Referenced by CImg< uintT >::cosh(), and CImg< T >::_cimg_math_parser::eval().
{
     return instance.get_cosh();
   }
CImg<_cimg_Tfloat> cimg_library::exp (const CImg< T > & instance) inline
Definition at line 6016 of file CImg.h.
References CImg< T >::get_exp().
Referenced by CImg< T >::_cimg_math_parser::_cimg_math_parser(), QualityMetric::average_metric_and_weights(), CImg< uintT >::blur_anisotropic(), CImg< uintT >::deriche(), CImg< uintT >::draw_gaussian(), CImg< T >::_cimg_math_parser::eval(), CImg< uintT >::exp(), CImg< uintT >::get_blur_patch(), ModifyExponents(), and cimg_library::cimg::prand().
{
     return instance.get_exp();
   }
CImg<_cimg_Tfloat> cimg_library::invert (const CImg< T > & instance) inline
Definition at line 6086 of file CImg.h.
References CImg< T >::get_invert().
Referenced by CImgList< uintT >::FFT(), and CImgList< uintT >::get_FFT().
{
     return instance.get_invert();
   }
CImg<_cimg_Tfloat> cimg_library::log (const CImg< T > & instance) inline
Definition at line 6021 of file CImg.h.
References CImg< T >::get_log().
Referenced by QualityMetric::average_metric_and_weights(), CImg< uintT >::draw_mandelbrot(), CImg< T >::_cimg_math_parser::eval(), CImg< uintT >::get_displacement_field(), cimg_library::cimg::grand(), CImg< uintT >::log(), TestingObject< ResultsType >::Test__MidPointQuadrature(), and TestingObject< ResultsType >::Test__TrapezoidQuadrature().
{
     return instance.get_log();
   }
CImg<_cimg_Tfloat> cimg_library::log10 (const CImg< T > & instance) inline
Definition at line 6026 of file CImg.h.
References CImg< T >::get_log10().
Referenced by QualityAssessor::Assessor::calculate_histogram_range(), CImg< uintT >::draw_axis(), CImg< T >::_cimg_math_parser::eval(), CImg< uintT >::get_select_graph(), CImg< uintT >::log10(), QualityAssessor::Assessor::print_histogram(), CImg< uintT >::PSNR(), and cimg_library::cimg::xln().
{
     return instance.get_log10();
   }
CImg<T> cimg_library::operator& (const char *const expression, const CImg< T > & img) inline
Definition at line 5991 of file CImg.h.
References expression.
{
     return img & expression;
   }
CImg<_cimg_Tfloat> cimg_library::operator* (const char *const expression, const CImg< T > & img) inline
Definition at line 5981 of file CImg.h.
References expression.
{
     return img*expression;
   }
CImg<_cimg_Tfloat> cimg_library::operator- (const char *const expression, const CImg< T > & img) inline
Definition at line 5976 of file CImg.h.
References CImg< T >::depth, CImg< T >::dim, CImg< T >::height, and CImg< T >::width.
{
     return (CImg<_cimg_Tfloat>(img.width,img.height,img.depth,img.dim)=expression)-=img;
   }
CImg<_cimg_Tfloat> cimg_library::operator/ (const char *const expression, const CImg< T > & img) inline
Definition at line 5986 of file CImg.h.
References CImg< T >::get_invert().
{
     return expression*img.get_invert();
   }
CImg<T> cimg_library::operator^ (const char *const expression, const CImg< T > & img) inline
Definition at line 6001 of file CImg.h.
References expression.
{
     return img ^ expression;
   }
CImg<T> cimg_library::operator| (const char *const expression, const CImg< T > & img) inline
Definition at line 5996 of file CImg.h.
References expression.
{
     return img | expression;
   }
CImg<_cimg_Tfloat> cimg_library::pseudoinvert (const CImg< T > & instance) inline
Definition at line 6091 of file CImg.h.
References CImg< T >::get_pseudoinvert().
{
     return instance.get_pseudoinvert();
   }
CImg<_cimg_Tfloat> cimg_library::sin (const CImg< T > & instance) inline
Definition at line 6041 of file CImg.h.
References CImg< T >::get_sin().
Referenced by CImg< uintT >::_draw_ellipse(), CImg< uintT >::blur_anisotropic(), COM_print_window(), Rocmop::compute_medial_quadric(), CImg< uintT >::cone3d(), CImg< uintT >::cylinder3d(), CImg< uintT >::draw_arrow(), CImg< uintT >::eigen(), Window_manifold_2::elements_to_nodes(), CImg< T >::_cimg_math_parser::eval(), CImg< uintT >::FFT(), func2(), func3(), Rocout::get_fname(), CImg< uintT >::get_rotate(), Vortex_flow::get_velocity(), LeVeque_flow::get_velocity(), init_speed_arrays(), is_whole(), load_data_HDF4(), main(), new_attributes(), PrintConn(), rational_rotation_approximation(), Rocin::read_by_control_file(), CImg< uintT >::rotation_matrix(), scan_files_HDF4(), CImg< uintT >::sin(), CImg< uintT >::torus3d(), write_attr_CGNS(), and Rocout::write_rocin_control_file().
{
     return instance.get_sin();
   }
CImg<_cimg_Tfloat> cimg_library::sinh (const CImg< T > & instance) inline
Definition at line 6071 of file CImg.h.
References CImg< T >::get_sinh().
Referenced by CImg< T >::_cimg_math_parser::eval(), and CImg< uintT >::sinh().
{
     return instance.get_sinh();
   }
CImg<_cimg_Tfloat> cimg_library::sqr (const CImg< T > & instance) inline
Definition at line 6006 of file CImg.h.
References CImg< T >::get_sqr().
{
     return instance.get_sqr();
   }
CImg<_cimg_Tfloat> cimg_library::sqrt (const CImg< T > & instance) inline
Definition at line 6011 of file CImg.h.
References CImg< T >::get_sqrt().
{
     return instance.get_sqrt();
   }
CImg<_cimg_Tfloat> cimg_library::tan (const CImg< T > & instance) inline
Definition at line 6046 of file CImg.h.
References CImg< T >::get_tan().
Referenced by CImg< T >::_cimg_math_parser::eval(), FaceOffset_3::reset_default_parameters(), FaceOffset_3::set_fangle_weak(), and CImg< uintT >::tan().
{
     return instance.get_tan();
   }
CImg<_cimg_Tfloat> cimg_library::tanh (const CImg< T > & instance) inline
Definition at line 6076 of file CImg.h.
References CImg< T >::get_tanh().
Referenced by CImg< T >::_cimg_math_parser::eval(), and CImg< uintT >::tanh().
{
     return instance.get_tanh();
   }
CImg<T> cimg_library::transpose (const CImg< T > & instance) inline
Definition at line 6081 of file CImg.h.
References CImg< T >::get_transpose().
{
     return instance.get_transpose();
   }
Variable Documentation
const CImg<T>& img return img expression
Definition at line 5972 of file CImg.h.
Referenced by CImg< uintT >::fill(), CImg< uintT >::operator%=(), operator&(), CImg< uintT >::operator&=(), operator*(), CImg< uintT >::operator*=(), CImg< uintT >::operator+=(), CImg< uintT >::operator-=(), CImg< uintT >::operator/=(), operator^(), CImg< uintT >::operator^=(), operator|(), and CImg< uintT >::operator|=().