Rocstar: CGAL::NTS Namespace Reference
CGAL::NTS Namespace Reference
Functions
template<class NT >
bool is_zero (const NT &x)
template<class NT >
bool is_one (const NT &x)
template<class NT >
bool is_negative (const NT &x)
template<class NT >
bool is_positive (const NT &x)
template<class NT >
CGAL_KERNEL_INLINE Sign sign (const NT &x)
template<class NT >
CGAL_KERNEL_INLINE Sign lexicographical_sign (const NT &x, const NT &y)
template<class NT >
CGAL_KERNEL_INLINE NT abs (const NT &x)
template<class NT >
CGAL_KERNEL_INLINE const NT & min (const NT &x, const NT &y)
template<class NT >
CGAL_KERNEL_INLINE const NT & max (const NT &x, const NT &y)
template<class NT >
CGAL_KERNEL_INLINE
Comparison_result compare (const NT &n1, const NT &n2)
template<class NT >
NT square (const NT &n)
Function Documentation
CGAL_KERNEL_INLINE NT CGAL::NTS::abs (const NT & x)
Definition at line 209 of file number_utils.h.
References x.
Referenced by FaceOffset_3::build_ridge_neighbor_list(), SegmentS2< FT >::collinear_has_on(), RFC_Window_overlay::comp_angle_defect(), compare_deltax_deltayC2(), Alg_Metric_Base_3::compute_shape(), Alg_Metric_Base_3::compute_skew(), Propagation_3::convert_constraints(), Pane_connectivity::create_b2map(), Bbox_3::do_match(), FaceOffset_3::eigen_analyze_vertex(), Rocmop::eigen_analyze_vertex(), Rocmop::get_constraint_directions(), Overlay::get_green_parent(), RFC_Window_overlay::identify_features_0(), init_constraints_labscale(), init_constraints_myacm(), init_constraints_staraft(), init_constraints_starslice(), Overlay::insert_node_in_blue_edge(), Overlay::intersect_link_helper(), Segment_2_Segment_2_pair< R >::intersection_type(), FaceOffset_3::is_acute_corner(), FaceOffset_3::is_acute_ridge(), nHops(), FaceOffset_3::nulaplacian_smooth(), FaceOffset_3::obtain_constrained_directions(), FaceOffset_3::obtain_face_offset(), Rocblas::limit1v< T >::operator()(), Abs< NT >::operator()(), output_solution(), rational_rotation_approximation(), FaceOffset_3::reclassify_ridge_vertices(), reduce_maxabs(), reduce_minabs(), FaceOffset_3::solve_quadratic_func(), TestingObject< ResultsType >::Test__MidPointQuadrature(), TestingObject< ResultsType >::Test__TrapezoidQuadrature(), tet_vol(), and Element_node_enumerator::vertex().
 { return (x < NT(0)) ? -x: x; }
CGAL_KERNEL_INLINE Comparison_result CGAL::NTS::compare (const NT & n1, const NT & n2)
Definition at line 227 of file number_utils.h.
References EQUAL, LARGER, and SMALLER.
 {
   if (n1 < n2)
   {
     return SMALLER ;
   }
   return (n2 < n1) ? LARGER : EQUAL;
 }
bool CGAL::NTS::is_negative (const NT & x) inline
Definition at line 185 of file number_utils.h.
 { return x < NT(0); }
bool CGAL::NTS::is_one (const NT & x) inline
Definition at line 179 of file number_utils.h.
 { return x == NT(1); }
bool CGAL::NTS::is_positive (const NT & x) inline
Definition at line 191 of file number_utils.h.
References x.
 { return NT(0) < x; }
bool CGAL::NTS::is_zero (const NT & x) inline
Definition at line 173 of file number_utils.h.
 { return x == NT(0); }
CGAL_KERNEL_INLINE Sign CGAL::NTS::lexicographical_sign (const NT & x, const NT & y)
Definition at line 203 of file number_utils.h.
References CGAL_NTS, and sign().
 { return (x == NT(0)) ? CGAL_NTS sign(y) : CGAL_NTS sign(x); }
CGAL_KERNEL_INLINE const NT& CGAL::NTS::max (const NT & x, const NT & y)
Definition at line 221 of file number_utils.h.
References x.
 { return (x < y) ? y : x; }
CGAL_KERNEL_INLINE const NT& CGAL::NTS::min (const NT & x, const NT & y)
Definition at line 215 of file number_utils.h.
References x.
 { return (y < x) ? y : x; }
CGAL_KERNEL_INLINE Sign CGAL::NTS::sign (const NT & x)
Definition at line 197 of file number_utils.h.
References NEGATIVE, POSITIVE, x, and ZERO.
Referenced by lexicographical_sign().
 { return (x < NT(0)) ? NEGATIVE : (NT(0) < x) ? POSITIVE : ZERO; }
NT CGAL::NTS::square (const NT & n) inline
Definition at line 239 of file number_utils.h.
 { return n*n; }