Rocstar: OperatorJ.f90 File Reference
OperatorJ.f90 File Reference
Functions/Subroutines
subroutine operatorj (Lm, Ld, Lb, L2, Lbar, Mm, M2, cm, cb, cd, Dbm, Dbb, Dbd, Dmm, Dmb, Dmd, Ddm, Ddb, Ddd, Am, Ab, Ad, A2, Km, K2, Gm, G2, vm, v2, a_eta, a_zeta, OpJ, N, Ninv, R, Rinv, Q2, Qm, W)
Function/Subroutine Documentation
subroutine operatorj (real*8, dimension(1:6,1:6) Lm, real*8, dimension(1:6,1:6) Ld, real*8, dimension(1:6,1:6) Lb, real*8, dimension(1:6,1:6) L2, real*8, dimension(1:6,1:6) Lbar, real*8, dimension(1:6,1:6) Mm, real*8, dimension(1:6,1:6) M2, real*8 cm, real*8 cb, real*8 cd, real*8, dimension(1:6,1:6) Dbm, real*8, dimension(1:6,1:6) Dbb, real*8, dimension(1:6,1:6) Dbd, real*8, dimension(1:6,1:6) Dmm, real*8, dimension(1:6,1:6) Dmb, real*8, dimension(1:6,1:6) Dmd, real*8, dimension(1:6,1:6) Ddm, real*8, dimension(1:6,1:6) Ddb, real*8, dimension(1:6,1:6) Ddd, real*8, dimension(1:6,1:6) Am, real*8, dimension(1:6,1:6) Ab, real*8, dimension(1:6,1:6) Ad, real*8, dimension(1:6,1:6) A2, real*8 Km, real*8 K2, real*8 Gm, real*8 G2, real*8 vm, real*8 v2, real*8 a_eta, real*8 a_zeta, real*8, dimension(1:6,1:6) OpJ, real*8, dimension(1:6,1:6) N, real*8, dimension(1:6,1:6) Ninv, real*8, dimension(1:6,1:6) R, real*8, dimension(1:6,1:6) Rinv, real*8, dimension(1:6,1:6) Q2, real*8, dimension(1:6,1:6) Qm, real*8, dimension(1:6,1:6) W)
Definition at line 53 of file OperatorJ.f90.
References constant_w(), invert2(), and Color::r().
Referenced by matous_const_model().