Rocstar: Overlay_1d.C File Reference
Overlay_1d.C File Reference
#include "Overlay.h"
#include <cstdio>
#include <iterator>
Functions
static bool equal (const Bbox_3 &b1, const Bbox_3 &b2, Real tol_r)
Function Documentation
static bool equal (const Bbox_3 & b1, const Bbox_3 & b2, Real tol_r) static
Definition at line 87 of file Overlay_1d.C.
References max(), Bbox_3::xmax(), Bbox_3::xmin(), Bbox_3::ymax(), Bbox_3::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by In_place_list_n< T, managed >::operator!=(), and In_place_list_n< T, managed >::operator==().
{
   Bbox_3 u = b1+b2;
   Real tol_a = std::max(std::max(u.xmax()-u.xmin(), u.ymax()-u.ymin()),
                         u.zmax()-u.zmin()) * tol_r;
   return ( std::max( std::fabs(b1.xmin()-b2.xmin()),
                      std::fabs(b1.xmax()-b2.xmax())) <= tol_a &&
            std::max( std::fabs(b1.ymin()-b2.ymin()),
                      std::fabs(b1.ymax()-b2.ymax())) <= tol_a &&
            std::max( std::fabs(b1.zmin()-b2.zmin()),
                      std::fabs(b1.zmax()-b2.zmax())) <= tol_a);
 }