Rocstar: Pane_boundary.C File Reference
Pane_boundary.C File Reference
#include <map>
#include <algorithm>
#include <cassert>
#include <cstdlib>
#include <iostream>
#include <sstream>
#include "Pane_boundary.h"
Classes
struct Four_tuple< T >
A structure used to represent element faces.
Typedefs
typedef std::map< Four_tuple,
Facet_ID > Corners2Face_Map
Functions
static void check_face_unique (const Four_tuple &face_corners, const Facet_ID &fid, std::vector< Corners2Face_Map > &c2f_vec, int &num_external_face, int &counter)
double square (double x)
Typedef Documentation
typedef std::map< Four_tuple, Facet_ID> Corners2Face_Map
Definition at line 73 of file Pane_boundary.C.
Function Documentation
static void check_face_unique (const Four_tuple & face_corners, const Facet_ID & fid, std::vector< Corners2Face_Map > & c2f_vec, int & num_external_face, int & counter) static
Definition at line 79 of file Pane_boundary.C.
Referenced by Pane_boundary::determine_border_nodes_3().
{
   // Sort the node ids of the face
   Four_tuple sorted_ns( face_corners);
   std::sort( &sorted_ns[0], &sorted_ns[4]);
   // Check whether the sorted node-list is in vec2facemap_vec
   // by trying to insert it
   Corners2Face_Map &c2f = c2f_vec[sorted_ns[1]-1];
   std::pair<Corners2Face_Map::iterator, bool>
     ans = c2f.insert( std::make_pair(sorted_ns, fid));
   // If the node-list already exists, then remove it from vecFaceMap
   if ( !ans.second) {
     counter++;
     c2f.erase( ans.first);
     --num_external_face;
   }
   // Otherwise, insertion succeeded.
   else ++num_external_face;
 }
double square (double x) inline
Definition at line 243 of file Pane_boundary.C.
References x.
Referenced by bisector_of_pointsC2(), circumcenter_translateC2(), circumcenterC3(), init_constraints_myacm(), init_constraints_starslice(), init_speed_arrays(), line_project_pointC2(), Pane_boundary::min_squared_edge_len(), Square< NT >::operator()(), side_of_oriented_sphereC3(), squared_circumradiusC2(), squared_distanceC2(), and squared_distanceC3().
 { return x*x; }