Rocstar: Pane_connectivity.C File Reference
Pane_connectivity.C File Reference
#include <set>
#include <map>
#include <cassert>
#include <algorithm>
#include <iostream>
#include "kdtree_d.h"
#include "Pane_connectivity.h"
#include "Pane_boundary.h"
Classes
class Point_3_ref
class KD_tree_3
class KD_tree_pntref_3
Typedefs
typedef std::pair< int, int > pair_int
typedef std::pair< int, int > Node_ID
Functions
static void convert_nodelist (const std::vector< bool > &bs, std::vector< int > &nodes)
static void make_kd_tree (const std::vector< int > &nodes, const std::vector< Point_3< Real > > &pnts, std::vector< Point_3< Real > > &bbox, KD_tree_pntref_3 &ktree)
static bool intersect_bbox (const Point_3< Real > &bmin1, const Point_3< Real > &bmax1, const Point_3< Real > &bmin2, const Point_3< Real > &bmax2, Real eps)
static bool intersect_bbox (const Point_3< Real > &bmin, const Point_3< Real > &bmax, const std::vector< Point_3< Real > > &bbox, Real tol)
static void collect_coincident_nodes (const std::vector< int > &r_nodes, const std::vector< Point_3< Real > > &r_pnts, const std::vector< Point_3< Real > > &bbox, KD_tree_pntref_3 &ktree, double tol, std::vector< int > &nodes, std::vector< Point_3< Real > > &pnts)
Typedef Documentation
typedef std::pair<int,int> Node_ID
Definition at line 69 of file Pane_connectivity.C.
typedef std::pair<int,int> pair_int
Definition at line 68 of file Pane_connectivity.C.
Function Documentation
static void collect_coincident_nodes (const std::vector< int > & r_nodes, const std::vector< Point_3< Real > > & r_pnts, const std::vector< Point_3< Real > > & bbox, KD_tree_pntref_3 & ktree, double tol, std::vector< int > & nodes, std::vector< Point_3< Real > > & pnts) static
Definition at line 379 of file Pane_connectivity.C.
References i, intersect_bbox(), Point_3< T >::x(), Point_3< T >::y(), and Point_3< T >::z().
Referenced by Pane_connectivity::collect_boundary_nodes().
{
   unsigned int count = 0;
   while (count<r_nodes.size()) {
     const Point_3<Real> &xmin=r_pnts[count], &xmax=r_pnts[count+1];
     if ( !intersect_bbox( xmin, xmax, bbox, tol))
     { count += 2+r_nodes[count+1]; continue; }
     int pane = r_nodes[count++];
     int nn = 0;
     for ( int i=0, n = r_nodes[count++]; i<n; ++i, ++count) {
       const Point_3<Real> &p=r_pnts[count];
       Point_3_ref lb(p.x()-tol, p.y()-tol, p.z()-tol);
       Point_3_ref ub(p.x()+tol, p.y()+tol, p.z()+tol);
       KD_tree_pntref_3::Box box( lb, ub, 3);
       std::vector< Point_3_ref>  outList; outList.reserve(4);
       ktree.search( std::back_inserter( outList), box);
       if ( !outList.empty()) {
         if ( nn==0) {
           nodes.push_back( -pane); // Use negative for remote panes
           nodes.push_back( 0);
           pnts.push_back( xmin); pnts.push_back( xmax);
         }
         nodes.push_back( r_nodes[count]);
         pnts.push_back( p);
         ++nn;
       }
     }
     if ( nn>0) *(nodes.end()-nn-1) = nn;
   }
 }
static void convert_nodelist (const std::vector< bool > & bs, std::vector< int > & nodes) static
Definition at line 87 of file Pane_connectivity.C.
References i, and s.
Referenced by Pane_connectivity::get_local_boundary_nodes().
{
   nodes.clear();
   const int s = bs.size();
   for ( int i=0; i<s; ++i)
     if ( bs[i]) nodes.push_back( i+1);
 }
static bool intersect_bbox (const Point_3< Real > & bmin1, const Point_3< Real > & bmax1, const Point_3< Real > & bmin2, const Point_3< Real > & bmax2, Real eps) static
Definition at line 355 of file Pane_connectivity.C.
References Point_3< T >::x(), Point_3< T >::y(), and Point_3< T >::z().
Referenced by collect_coincident_nodes(), and intersect_bbox().
{
   // check for emptiness ??
   if (bmax1.x()+eps < bmin2.x() || bmax2.x()+eps < bmin1.x())
     return false;
   if (bmax1.y()+eps < bmin2.y() || bmax2.y()+eps < bmin1.y())
     return false;
   if (bmax1.z()+eps < bmin2.z() || bmax2.z()+eps < bmin1.z())
     return false;
   return true;
 }
static bool intersect_bbox (const Point_3< Real > & bmin, const Point_3< Real > & bmax, const std::vector< Point_3< Real > > & bbox, Real tol) static
Definition at line 369 of file Pane_connectivity.C.
References i, and intersect_bbox().
{
   for ( int i=0, n=bbox.size(); i<n; i+=2) {
     if ( intersect_bbox( bmin, bmax, bbox[i], bbox[i+1], tol))
       return true;
   }
   return false;
 }
static void make_kd_tree (const std::vector< int > & nodes, const std::vector< Point_3< Real > > & pnts, std::vector< Point_3< Real > > & bbox, KD_tree_pntref_3 & ktree) static
Definition at line 334 of file Pane_connectivity.C.
References i.
Referenced by Pane_connectivity::collect_boundary_nodes(), and Pane_connectivity::create_b2map().
{
   if ( nodes.empty()) return;
   assert( nodes.size() == pnts.size());
   std::vector< Point_3_ref> b; b.reserve( pnts.size());
   bbox.clear();
   unsigned int count = 0;
   while (count<nodes.size()) {
     bbox.push_back( pnts[count]);
     bbox.push_back( pnts[++count]);
     for ( int i=0, n = nodes[count++]; i<n; ++i, ++count) {
       b.push_back( Point_3_ref(pnts[count],count));
     }
   }
   ktree.build( b);
 }