Rocstar: Pane_communicator.C File Reference
Pane_communicator.C File Reference
Handles communication of shared nodes across panes.
#include <cassert>
#include <cstring>
#include "Pane_communicator.h"
#include "Pane_connectivity.h"
#include "roccom.h"
Functions
template<class T >
void reduce_int (MPI_Op op, T *a, T *b, int size) throw (int)
Local level implementation of reduce operations.
template<class T >
void reduce_real (MPI_Op op, T *a, T *b, int size) throw (int)
Local level implementation of reduce operations.
template<class T >
void reduce_maxabs (T *a, T *b, int size) throw (int)
template<class T >
void reduce_minabs (T *a, T *b, int size) throw (int)
template<class T >
void reduce_diff (T *a, T *b, int size) throw (int)
template<class T >
void update_value (T *a, T *b, int size) throw (int)
Detailed Description
Handles communication of shared nodes across panes.
Definition in file Pane_communicator.C.
Function Documentation
void reduce_diff (T * a, T * b, int size) throw (int)
Definition at line 478 of file Pane_communicator.C.
References i, and j.
Referenced by Pane_communicator::reduce_diff_on_shared_nodes().
{
   bool isa_nonzero=0;
   for (int i=0; ; ++i) {
     if ( a[i]!=0) { isa_nonzero = 1; break; }
     else if (i==size) return;
   }
   bool isb_nonzero=0;
   for (int i=0; i<size; ++i)
     if ( b[i]!=0) { isb_nonzero = 1; break; }
   if ( isb_nonzero)
     for (int j=0; j<size; ++j) b[j] -= a[j];
   else
     for (int j=0; j<size; ++j) b[j] = a[j];
 }
void reduce_int (MPI_Op op, T * a, T * b, int size) throw (int)
Local level implementation of reduce operations.
Definition at line 365 of file Pane_communicator.C.
References i, max(), min(), MPI_BOR, MPI_LAND, MPI_LOR, MPI_MAX, MPI_MIN, MPI_PROD, and MPI_SUM.
Referenced by Pane_communicator::reduce_on_shared_nodes().
{
   if (op == MPI_SUM)
     { for (int i=0; i<size; ++i) b[i] += a[i]; }
   else if ( op == MPI_PROD)
     { for (int i=0; i<size; ++i) b[i] *= a[i]; }
   else if ( op == MPI_MAX)
     { for (int i=0; i<size; ++i) b[i] = std::max(a[i], b[i]); }
   else if ( op == MPI_MIN)
     { for (int i=0; i<size; ++i) b[i] = std::min(a[i], b[i]); }
   else if ( op == MPI_BOR)
     { for (int i=0; i<size; ++i) b[i] |= a[i]; }
   else if ( op == MPI_BAND)
     { for (int i=0; i<size; ++i) b[i] &= a[i]; }
   else if ( op == MPI_LOR)
     { for (int i=0; i<size; ++i) b[i] = a[i] || b[i]; }
   else if ( op == MPI_LAND)
     { for (int i=0; i<size; ++i) b[i] = a[i] && b[i]; }
   else throw(-1);
 }
void reduce_maxabs (T * a, T * b, int size) throw (int)
Definition at line 464 of file Pane_communicator.C.
References NTS::abs(), and i.
Referenced by Pane_communicator::reduce_maxabs_on_shared_nodes().
{
   for (int i=0; i<size; ++i) {
     if ( std::abs( a[i])>std::abs(b[i])) b[i] = a[i];
   }
 }
void reduce_minabs (T * a, T * b, int size) throw (int)
Definition at line 471 of file Pane_communicator.C.
References NTS::abs(), and i.
Referenced by Pane_communicator::reduce_minabs_on_shared_nodes().
{
   for (int i=0; i<size; ++i) {
     if ( std::abs( a[i])<std::abs(b[i])) b[i] = a[i];
   }
 }
void reduce_real (MPI_Op op, T * a, T * b, int size) throw (int)
Local level implementation of reduce operations.
Definition at line 387 of file Pane_communicator.C.
References i, max(), min(), MPI_MAX, MPI_MIN, MPI_PROD, and MPI_SUM.
Referenced by Pane_communicator::reduce_on_shared_nodes().
{
   if (op == MPI_SUM)
     { for (int i=0; i<size; ++i) b[i] += a[i]; }
   else if ( op == MPI_PROD)
     { for (int i=0; i<size; ++i) b[i] *= a[i]; }
   else if ( op == MPI_MAX)
     { for (int i=0; i<size; ++i) b[i] = std::max(a[i], b[i]); }
   else if ( op == MPI_MIN)
     { for (int i=0; i<size; ++i) b[i] = std::min(a[i], b[i]); }
   else throw(-1);
 }
void update_value (T * a, T * b, int size) throw (int)
Definition at line 686 of file Pane_communicator.C.
References i.
Referenced by Pane_communicator::update_ghost_values().
{
   for (int i=0; i<size; ++i) {
     b[i] = a[i];
   }
 }