Rocstar: PartitionCeff.f90 File Reference
PartitionCeff.f90 File Reference
Functions/Subroutines
subroutine partition_ceff (ndim, nrows, nnz, nstart, rp1, cval, aval, newnrows, newnstart, newndim, ProcTemp, global)
subroutine prescribedload (nrows, nstart, NumTemp, TempBC, Ceff_fp, ProcTemp)
Function/Subroutine Documentation
subroutine partition_ceff (integer ndim, integer nrows, integer nnz, integer nstart, integer, dimension(nrows+1) rp1, integer, dimension(nnz) cval, real(kind=wp), dimension(nnz) aval, integer newnrows, integer newnstart, integer newndim, real(kind=wp), dimension(lnumnp) ProcTemp, type(rocfrac_global) global)
Definition at line 36 of file PartitionCeff.f90.
References i, j, Aff_transformation_2< R_ >::m(), prescribedload(), and Aff_transformation_repS2< FT >::print().
Referenced by thermal_soln().
subroutine prescribedload (integer nrows, integer nstart, integer NumTemp, integer, dimension(numtemp) TempBC, real(kind=wp), dimension(nrows-numtemp,gnumtemp) Ceff_fp, real(kind=wp), dimension(lnumnp) ProcTemp)
Definition at line 419 of file PartitionCeff.f90.
References i, j, and Aff_transformation_2< R_ >::m().
Referenced by partition_ceff().