Rocstar: PerfgasDependentVars.F90 File Reference
PerfgasDependentVars.F90 File Reference
Functions/Subroutines
subroutine perfgasdependentvars (inBeg, inEnd, indCp, indMol, cv, gv, dv)
Function/Subroutine Documentation
subroutine perfgasdependentvars (integer inBeg, integer inEnd, integer indCp, integer indMol, real(rfreal), dimension(:,:), pointer cv, real(rfreal), dimension(:,:), pointer gv, real(rfreal), dimension(:,:), pointer dv)
Definition at line 50 of file PerfgasDependentVars.F90.
References ic, mixtperf_c_grt(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_r_m(), mixtperf_t_dpr(), and sqrt().
Referenced by mixtureproperties().