Rocstar: PERI_InitSolution.F90 File Reference
PERI_InitSolution.F90 File Reference
Functions/Subroutines
subroutine peri_initsolution (regions, iReg)
Function/Subroutine Documentation
subroutine peri_initsolution (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 44 of file PERI_InitSolution.F90.
References Direction_2< R, T >::delta(), moderror::deregisterfunction(), moderror::errorstop(), rflu_modrepair3d::input(), ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, max(), min(), peri_cocnlinitsolution(), peri_cocprinitsolution(), moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_getflowsolution().