Rocstar: PERI_coCprInitSolutionFlu.F90 File Reference
PERI_coCprInitSolutionFlu.F90 File Reference
Functions/Subroutines
subroutine peri_cocprinitsolution (region)
Function/Subroutine Documentation
subroutine peri_cocprinitsolution (type (t_region) region)
Definition at line 49 of file PERI_coCprInitSolutionFlu.F90.
References Direction_2< R, T >::delta(), moderror::deregisterfunction(), mixtperf_eo_dgpvm(), pi, moderror::registerfunction(), and sqrt().