Rocstar: PERI_coCnlInitSolutionFlo.F90 File Reference
PERI_coCnlInitSolutionFlo.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine peri_cocnlinitsolution (region)
Function/Subroutine Documentation
subroutine peri_cocnlinitsolution (type (t_region) region)
Definition at line 43 of file PERI_coCnlInitSolutionFlo.F90.
References Direction_2< R, T >::delta(), moderror::deregisterfunction(), Direction_2< R, T >::dy(), moderror::errorstop(), i, icorner, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, mixtperf_eo_dgpvm(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getnodeoffset(), and sqrt().
Referenced by peri_initsolution().