Rocstar: PERI_coPgradUpdateFlo.F90 File Reference
PERI_coPgradUpdateFlo.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine peri_copgradupdate (region)
Function/Subroutine Documentation
subroutine peri_copgradupdate (type(t_region) region)
Definition at line 46 of file PERI_coPgradUpdateFlo.F90.
References Color::alpha(), Direction_2< R, T >::delta(), moderror::deregisterfunction(), moderror::errorstop(), i, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, min(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), and rflo_getnodeoffset().
Referenced by peri_solutionupdate().