Rocstar: PERI_UserInput.F90 File Reference
PERI_UserInput.F90 File Reference
Functions/Subroutines
subroutine peri_userinput (regions)
Function/Subroutine Documentation
subroutine peri_userinput (type (t_region), dimension(:), pointer regions)
Definition at line 46 of file PERI_UserInput.F90.
References moderror::deregisterfunction(), peri_checkparaminput(), peri_derivedinputvalues(), peri_initinputvalues(), peri_readinputfile(), and moderror::registerfunction().
Referenced by rflo_getuserinput(), and rflu_getuserinput().