Rocstar: PERI_ReadInputFile.F90 File Reference
PERI_ReadInputFile.F90 File Reference
Functions/Subroutines
subroutine peri_readinputfile (regions)
Function/Subroutine Documentation
subroutine peri_readinputfile (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file PERI_ReadInputFile.F90.
References moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, CImg< T >::line(), peri_readperisection(), moderror::registerfunction(), and Attribute::status().
Referenced by peri_userinput().