Rocstar: PEUL_ReadInputFile.F90 File Reference
PEUL_ReadInputFile.F90 File Reference
Functions/Subroutines
subroutine peul_readinputfile (regions)
Function/Subroutine Documentation
subroutine peul_readinputfile (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file PEUL_ReadInputFile.F90.
References brbeg, moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, CImg< T >::line(), peul_readconpartptypesection(), peul_readconpartsection(), moderror::registerfunction(), and Attribute::status().
Referenced by peul_userinput().