Rocstar: PEUL_ReadSolutionRegion.F90 File Reference
PEUL_ReadSolutionRegion.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine peul_readsolutionregion (iReg, regions)
Function/Subroutine Documentation
subroutine peul_readsolutionregion (integer, intent(in) iReg, type(t_region), dimension(:), pointer regions)
Definition at line 50 of file PEUL_ReadSolutionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, idcbeg, idcend, ipnbeg, ipnend, j, jdcbeg, jdcend, jpnbeg, jpnend, k, kdcbeg, kpnbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_readdatafileint(), rflo_readdatafilereal(), and Attribute::status().
Referenced by peul_rocflo_post().