Rocstar: PEUL_AllocateMemory.F90 File Reference
PEUL_AllocateMemory.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine peul_allocatememory (region)
Function/Subroutine Documentation
subroutine peul_allocatememory (type(t_region), intent(inout) region)
Definition at line 45 of file PEUL_AllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), idcbeg, idcend, idnbeg, idnend, jdcbeg, jdcend, jdnbeg, jdnend, kdcbeg, kdnbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), and rflo_getnodeoffset().
Referenced by rflo_domemoryallocation().