Rocstar: PEUL_BoundaryConditionsSet.F90 File Reference
PEUL_BoundaryConditionsSet.F90 File Reference
Functions/Subroutines
subroutine peul_boundaryconditionsset (regions, iReg)
Function/Subroutine Documentation
subroutine peul_boundaryconditionsset (type(t_region), dimension(:), pointer regions, integer, intent(in) iReg)
Definition at line 46 of file PEUL_BoundaryConditionsSet.F90.
References moderror::deregisterfunction(), moderror::errorstop(), peul_bcondinflow(), peul_bcondinjection(), peul_bcondoutflow(), peul_bcondslipwall(), peul_bcondsymmetry(), peul_exchangedummyconf(), and moderror::registerfunction().
Referenced by updateboundaryconditionsmp().