Rocstar: PEUL_BcondOutflow.F90 File Reference
PEUL_BcondOutflow.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine peul_bcondoutflow (region, patch)
Function/Subroutine Documentation
subroutine peul_bcondoutflow (type(t_region), intent(inout) region, type(t_patch), intent(in) patch)
Definition at line 44 of file PEUL_BcondOutflow.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by peul_boundaryconditionsset().