Rocstar: PEUL_CentralFluxPatch.F90 File Reference
PEUL_CentralFluxPatch.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine peul_centralfluxpatch (region, patch)
Function/Subroutine Documentation
subroutine peul_centralfluxpatch (type(t_region), intent(inout) region, type(t_patch), intent(in) patch)
Definition at line 45 of file PEUL_CentralFluxPatch.F90.
References bcondinjectionperf(), moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by peul_centralflux().