Rocstar: PEUL_UserInput.F90 File Reference
PEUL_UserInput.F90 File Reference
Functions/Subroutines
subroutine peul_userinput (regions)
Function/Subroutine Documentation
subroutine peul_userinput (type (t_region), dimension(:), pointer regions)
Definition at line 44 of file PEUL_UserInput.F90.
References moderror::deregisterfunction(), peul_derivedinputvalues(), peul_initinputvalues(), peul_readbcinputfile(), peul_readinputfile(), and moderror::registerfunction().
Referenced by rflo_getuserinput().