Rocstar: PEUL_BoundaryConditionsSend.F90 File Reference
PEUL_BoundaryConditionsSend.F90 File Reference
Functions/Subroutines
subroutine peul_boundaryconditionssend (regions, iReg)
Function/Subroutine Documentation
subroutine peul_boundaryconditionssend (type(t_region), dimension(:), pointer regions, integer, intent(in) iReg)
Definition at line 45 of file PEUL_BoundaryConditionsSend.F90.
References moderror::deregisterfunction(), peul_sendcorneredgecells(), peul_senddummyconf(), and moderror::registerfunction().
Referenced by initcommunicationmp().