Rocstar: PEUL_ExchangeDummyConf.F90 File Reference
PEUL_ExchangeDummyConf.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine peul_exchangedummyconf (region, regionSrc, patch, patchSrc)
Function/Subroutine Documentation
subroutine peul_exchangedummyconf (type(t_region), intent(inout) region, type(t_region), intent(in) regionSrc, type(t_patch), intent(inout) patch, type(t_patch), intent(in) patchSrc)
Definition at line 48 of file PEUL_ExchangeDummyConf.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, modindexing::indijkmap(), j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and rflo_getpatchmapping().
Referenced by peul_boundaryconditionsset().