Rocstar: PLAG_RFLO_RecvMetrics.F90 File Reference
PLAG_RFLO_RecvMetrics.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine plag_rflo_recvmetrics (regions, iReg)
Function/Subroutine Documentation
subroutine plag_rflo_recvmetrics (type(t_region), dimension(:), pointer regions, integer, intent(in) iReg)
Definition at line 46 of file PLAG_RFLO_RecvMetrics.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, icorner, iend, j, jbeg, jend, k, kbeg, Mesh::GenericCell_2::nedges(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getedgecellsindices(), rflo_getnodeoffset(), Ray_2< R, T >::source(), Attribute::status(), and RFC_Data_const< _Tag >::tag().
Referenced by plag_rflo_sendrecvmetrics().