Rocstar: PLAG_RFLU_DeallocMemSol.F90 File Reference
PLAG_RFLU_DeallocMemSol.F90 File Reference
Functions/Subroutines
subroutine plag_rflu_deallocmemsol (pRegion, pPlag)
Function/Subroutine Documentation
subroutine plag_rflu_deallocmemsol (type(t_region), pointer pRegion, type(t_plag), pointer pPlag)
Definition at line 45 of file PLAG_RFLU_DeallocMemSol.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_modreallocatememory::plag_reallocmem(), rflu_deallocatememorywrapper(), rflu_deallocmemsolwrapper(), and rfluinit().