Rocstar: PLAG_ReflectParticleData.F90 File Reference
PLAG_ReflectParticleData.F90 File Reference
Functions/Subroutines
subroutine plag_reflectparticledata (pPatch, pPlag, ifl, iPcl, xLocOld, yLocOld, zLocOld, xLoc, yLoc, zLoc, xTraj, yTraj, zTraj)
Function/Subroutine Documentation
subroutine plag_reflectparticledata (type(t_patch), pointer pPatch, type(t_plag), pointer pPlag, integer, intent(in) ifl, integer, intent(in) iPcl, real(rfreal), intent(inout) xLocOld, real(rfreal), intent(inout) yLocOld, real(rfreal), intent(inout) zLocOld, real(rfreal), intent(inout) xLoc, real(rfreal), intent(inout) yLoc, real(rfreal), intent(inout) zLoc, real(rfreal), intent(inout), optional xTraj, real(rfreal), intent(inout), optional yTraj, real(rfreal), intent(inout), optional zTraj)
Definition at line 69 of file PLAG_ReflectParticleData.F90.
References reflectposition(), and reflectvector().
Referenced by plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), and plag_rflu_modfindcells::plag_rflu_findcellstrajsafe().