Rocstar: PLAG_ReadDisPartnContSection.F90 File Reference
PLAG_ReadDisPartnContSection.F90 File Reference
Functions/Subroutines
subroutine plag_readdispartncontsection (regions)
Function/Subroutine Documentation
subroutine plag_readdispartncontsection (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file PLAG_ReadDisPartnContSection.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), inrt_setmaterial(), modinterfacesio::ReadListSection::readlistsection(), modinterfacesio::ReadPrefixedListSection::readprefixedlistsection(), and moderror::registerfunction().
Referenced by plag_readinputfile().