Rocstar: PLAG_AllocateMemory.F90 File Reference
PLAG_AllocateMemory.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine plag_allocatememory (region)
Function/Subroutine Documentation
subroutine plag_allocatememory (type(t_region) region)
Definition at line 44 of file PLAG_AllocateMemory.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), moderror::errorstop(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, plag_allocatememorytile(), plag_modeulerian::plag_createeulerianfield(), plag_modstats::plag_createstat(), plag_initmemory(), plag_injctileinitialize(), moderror::registerfunction(), rflo_getdimensdummynodes(), and rflo_getnodeoffset().
Referenced by rflo_domemoryallocation().