Rocstar: PLAG_CECellsSendRecvWrapper.F90 File Reference
PLAG_CECellsSendRecvWrapper.F90 File Reference
Functions/Subroutines
subroutine plag_cecellssendrecvwrapper (regions)
Function/Subroutine Documentation
subroutine plag_cecellssendrecvwrapper (type(t_region), dimension(:), pointer regions)
Definition at line 45 of file PLAG_CECellsSendRecvWrapper.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_cecellsclearrequestsdata(), plag_cecellsclearrequestssize(), plag_cecellsrecvdata(), plag_cecellsrecvsize(), plag_cecellssenddata(), plag_cecellssendsize(), and moderror::registerfunction().
Referenced by plag_cecellswrapper().