Rocstar: PLAG_CECellsWrapper.F90 File Reference
PLAG_CECellsWrapper.F90 File Reference
Functions/Subroutines
subroutine plag_cecellswrapper (regions)
Function/Subroutine Documentation
subroutine plag_cecellswrapper (type(t_region), dimension(:), pointer regions)
Definition at line 44 of file PLAG_CECellsWrapper.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_cecellsexchange(), plag_cecellsgetbuffersize(), plag_cecellsloaddatawrapper(), plag_cecellssendrecvwrapper(), and moderror::registerfunction().
Referenced by updateboundaryconditionsmp().