Rocstar: PLAG_RFLU_InitSolSerialWrapper.F90 File Reference
PLAG_RFLU_InitSolSerialWrapper.F90 File Reference
Functions/Subroutines
subroutine plag_rflu_initsolserialwrapper (pRegion)
Function/Subroutine Documentation
subroutine plag_rflu_initsolserialwrapper (type(t_region), pointer pRegion)
Definition at line 44 of file PLAG_RFLU_InitSolSerialWrapper.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_rflu_initsolserial_1d(), plag_rflu_initsolserial_3d(), and moderror::registerfunction().
Referenced by rfluinit().