Rocstar: PLAG_InitSolution.F90 File Reference
PLAG_InitSolution.F90 File Reference
Functions/Subroutines
subroutine plag_initsolution (iReg, region)
Function/Subroutine Documentation
subroutine plag_initsolution (integer iReg, type(t_region) region)
Definition at line 45 of file PLAG_InitSolution.F90.
References moderror::deregisterfunction(), plag_calcderivedvariables(), plag_intrpmixtproperties(), and moderror::registerfunction().
Referenced by rflo_getflowsolution().