Rocstar: PLAG_CECellsFaceCentroids.F90 File Reference
PLAG_CECellsFaceCentroids.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine plag_cecellsfacecentroids (regions, iReg)
Function/Subroutine Documentation
subroutine plag_cecellsfacecentroids (type(t_region), dimension(:), pointer regions, integer, intent(in) iReg)
Definition at line 45 of file PLAG_CECellsFaceCentroids.F90.
References moderror::deregisterfunction(), modindexing::getijk(), i, ibeg, icorner, iend, j, jbeg, jend, k, kbeg, Mesh::GenericCell_2::nedges(), Mesh::GenericElement::nfaces(), plag_rflo_getfacemapping(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getedgecellsindices(), and rflo_getnodeoffset().
Referenced by plag_rflo_setmetrics().