Rocstar: PLAG_InitPatchData.F90 File Reference
PLAG_InitPatchData.F90 File Reference
Functions/Subroutines
subroutine plag_initpatchdata (pRegion)
Function/Subroutine Documentation
subroutine plag_initpatchdata (type(t_region), pointer pRegion)
Definition at line 47 of file PLAG_InitPatchData.F90.
References moderror::deregisterfunction(), plag_injcmakeparticle(), modrandom::rand1uniform(), and moderror::registerfunction().
Referenced by rfluinit().