Rocstar: PLAG_PatchBufferSendRecv.F90 File Reference
PLAG_PatchBufferSendRecv.F90 File Reference
Functions/Subroutines
subroutine plag_patchbuffersendrecv (regions)
Function/Subroutine Documentation
subroutine plag_patchbuffersendrecv (type(t_region), dimension(:), pointer regions)
Definition at line 44 of file PLAG_PatchBufferSendRecv.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_appenddatafrombuffers(), plag_bufferdatarecv(), plag_bufferdatasend(), plag_buffersizerecv(), plag_buffersizesend(), plag_cleardatasendrequests(), plag_clearsizesendrequests(), and moderror::registerfunction().
Referenced by plag_patchupdatewrapper().