Rocstar: PLAG_StatMapping.F90 File Reference
PLAG_StatMapping.F90 File Reference
Functions/Subroutines
subroutine plag_statmapping (global)
Function/Subroutine Documentation
subroutine plag_statmapping (type(t_global), pointer global)
Definition at line 45 of file PLAG_StatMapping.F90.
References moderror::deregisterfunction(), moderror::errorstop(), genxstatnaming(), and moderror::registerfunction().
Referenced by modstatsroutines::statmapping().