Rocstar: PLAG_RFLO_FindGridMapping.F90 File Reference
PLAG_RFLO_FindGridMapping.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine plag_rflo_findgridmapping (regions)
subroutine plag_rflo_findsourcecell (regions, iReg, iLev, ic, jc, kc, found, iRegSrc, indexMapMat)
subroutine plag_rflo_sourcecell (region, regionSrc, patch, patchSrc, iLev, ic, jc, kc, found, indexMapMat)
subroutine plag_rflo_getfacemapping (mapMat, srcDir, srcFace)
Function/Subroutine Documentation
subroutine plag_rflo_findgridmapping (type(t_region), dimension(:), pointer regions)
Definition at line 45 of file PLAG_RFLO_FindGridMapping.F90.
References moderror::deregisterfunction(), modindexing::getijk(), i, ibeg, ic, icorner, iend, j, jbeg, jc, jend, k, kbeg, kc, Mesh::GenericCell_2::nedges(), plag_rflo_findsourcecell(), plag_rflo_getfacemapping(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getedgecellsindices(), and rflo_getnodeoffset().
Referenced by plag_rflo_setmetrics().
subroutine plag_rflo_findsourcecell (type(t_region), dimension(:), pointer regions, integer, intent(in) iReg, integer, intent(in) iLev, integer, intent(inout) ic, integer, intent(inout) jc, integer, intent(inout) kc, logical, intent(out) found, integer, intent(out) iRegSrc, integer, dimension(3,4), intent(out) indexMapMat)
Definition at line 215 of file PLAG_RFLO_FindGridMapping.F90.
References moderror::deregisterfunction(), ibeg, ic, iend, ipcbeg, ipcend, jbeg, jc, jend, jpcbeg, jpcend, kbeg, kc, kpcbeg, plag_rflo_sourcecell(), moderror::registerfunction(), rflo_getdimensphys(), and rflo_getpatchindices().
Referenced by plag_rflo_findgridmapping().
subroutine plag_rflo_getfacemapping (integer, dimension(3,4), intent(in) mapMat, integer, dimension(3), intent(out) srcDir, integer, dimension(6), intent(out) srcFace)
Definition at line 582 of file PLAG_RFLO_FindGridMapping.F90.
References idir, jdir, and kdir.
Referenced by plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_rflo_findgridmapping(), and plag_rflo_sendmetrics().
subroutine plag_rflo_sourcecell (type(t_region) region, type(t_region) regionSrc, type(t_patch), pointer patch, type(t_patch), pointer patchSrc, integer, intent(in) iLev, integer, intent(inout) ic, integer, intent(inout) jc, integer, intent(inout) kc, logical, intent(inout) found, integer, dimension(3,4), intent(out) indexMapMat)
Definition at line 482 of file PLAG_RFLO_FindGridMapping.F90.
References moderror::deregisterfunction(), modindexing::getijk(), ibeg, ic, icell, idir, iend, modindexing::indijkmap(), ipcbeg, ipcend, jbeg, jc, jdir, jend, jpcbeg, jpcend, kbeg, kc, kdir, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getpatchdirection(), rflo_getpatchindices(), and rflo_getpatchmapping().
Referenced by plag_rflo_findsourcecell().