Rocstar: PLAG_RFLU_InitSolutionRandom.F90 File Reference
PLAG_RFLU_InitSolutionRandom.F90 File Reference
Functions/Subroutines
subroutine plag_rflu_initsolutionrandom (pRegion)
Function/Subroutine Documentation
subroutine plag_rflu_initsolutionrandom (type(t_region), pointer pRegion)
Definition at line 44 of file PLAG_RFLU_InitSolutionRandom.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modrandom::rand1uniform(), moderror::registerfunction(), CImg< T >::sum(), v, Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by rfluinit().