Rocstar: plagprep.C File Reference
plagprep.C File Reference
This utility code reads in the *.top file information and generates the initial particle solution by finding the injecting surfaces.
#include <iostream>
#include <cstdlib>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <cstring>
Functions
void showUsage ()
Displays usage information for this utility.
bool parseCmdParameters (int argc, char **argv)
Parses the user-supplied parameters for this utility.
void searchTopFile ()
Searches the prjname.top file for injecting boundary conditions.
int main (int argc, char **argv)
Program main.
Variables
std::string prjname
<
std::string outputfile
The number of blocks, read from the *.top file.
int numberOfBlocks
int bndrycondition
The boundary condition corresponding to an injecting surface.
Detailed Description
This utility code reads in the *.top file information and generates the initial particle solution by finding the injecting surfaces.
The injecting surface are identified by a user-supplied boundary condition that corresponds to the boundary condition used to indicate an injecting surface in the *.top file.
Date
Nov 12, 2009
Author
George Zagaris (gzaga.nosp@m.ris@.nosp@m.illin.nosp@m.ois..nosp@m.edu)
Definition in file plagprep.C.
Function Documentation
int main (int argc, char ** argv)
Program main.
Parameters
argc the argument counter.
argv the argument vector.
Returns
rc the return code.
Note
rc != iff an error occured.
Definition at line 76 of file plagprep.C.
References bndrycondition, outputfile, parseCmdParameters(), prjname, searchTopFile(), and showUsage().
 {
         std::cout << __DATE__ << " Running program: " << argv[ 0 ] << std::endl;
         std::cout << "Parsing command line parameters...";
         if( parseCmdParameters( argc, argv ) )
         {
                 std::cout << "[DONE]\n";
                 std::cout << "Searching " << prjname << ".top for BC=" << bndrycondition << "...";
                  searchTopFile( );
                 std::cout << "[DONE]\n";
                 std::cout << "Output is saved at " << outputfile << "!\n";
         }
         else
         {
                 std::cout << "[DONE]\n";
                 std::cerr << "Error parsing command line parameters!\n";
                 std::cerr << "File: " << __FILE__ << std::endl;
                 std::cerr << "Line: " << __LINE__ << std::endl;
                 showUsage( );
                 return(-1 );
         }
         return( 0 );
 }
bool parseCmdParameters (int argc, char ** argv)
Parses the user-supplied parameters for this utility.
Parameters
argc the argument counter.
argv the argument vector.
Returns
status true if the command line parameters are parsed successfully, otherwise false.
Definition at line 183 of file plagprep.C.
References bndrycondition, i, numberOfBlocks, outputfile, prjname, and showUsage().
Referenced by main().
 {
         prjname                                                 = "";
         outputfile                                      = "";
         numberOfBlocks                  = 0;
         bndrycondition                  = 91;
         for( int i=1; i < argc; ++i )
         {
                 if( std::strcmp( argv[ i ], "-bc") == 0 )
                 {
                         bndrycondition = std::atoi( argv[ ++i ] );
                 }
                 else if( std::strcmp( argv[ i ], "-p") == 0 )
                 {
                         prjname    = std::string( argv[ ++i ] );
                         outputfile = prjname + std::string( ".sola_0.00000E+00" );
                 }
                 else if( std::strcmp( argv[ i ], "-h") == 0  )
                 {
                         showUsage( );
                         exit( 0 );
                 }
         }
         if( prjname == "" )
                 return false;
         return true;
 }
void searchTopFile ()
Searches the prjname.top file for injecting boundary conditions.
Postcondition
an prjname.plag_sola_0.00000E+00 is written.
Definition at line 113 of file plagprep.C.
References bndrycondition, i, j, numberOfBlocks, outputfile, and prjname.
Referenced by main().
 {
         std::string dummyline;
         std::ofstream ofs;
         ofs.open( outputfile.c_str( ) );
         if( !ofs.is_open( ) )
         {
                 std::cerr << "\n Error: Cannot open output file " << outputfile << std::endl;
                 std::cerr << "File: " << __FILE__ << std::endl;
                 std::cerr << "Line: " << __LINE__ << std::endl;
         }
         ofs << "0.00E+000\n";
         std::ifstream  ifs;
         ifs.open( ( prjname+std::string(".top") ).c_str( ) );
         if( !ifs.is_open( ) )
         {
                 std::cerr << "\n Error: Cannot open input file " << prjname+std::string(".top") << std::endl;
                 std::cerr << "File: " << __FILE__ << std::endl;
                 std::cerr << "Line: " << __LINE__ << std::endl;
         }
         std::getline( ifs, dummyline );
         std::getline( ifs, dummyline );
         ifs >> numberOfBlocks;
         std::getline( ifs, dummyline );
         for( int i=1; i <= numberOfBlocks; ++i )
                 ofs << i << " 0 0\n";
         int blockidx,bc,npatches;
         for( int i=0; i < numberOfBlocks; ++i )
         {
                 ifs >> blockidx;
                 std::getline( ifs, dummyline );
                 ifs >> npatches;
                 std::getline( ifs, dummyline );
                 for( int j=0; j < npatches; ++j )
                 {
                         ifs >> bc;
                         std::getline( ifs, dummyline );
                         if( bc == bndrycondition )
                                 ofs << blockidx << " 0\n";
                 }
         }
         ofs.close( );
         ifs.close( );
 }
void showUsage ()
Displays usage information for this utility.
Definition at line 170 of file plagprep.C.
Referenced by main(), and parseCmdParameters().
 {
         std::cout << "plagprep -- generates the initial particle solution dump at t=0\n";
         std::cout << "OPTIONS:\n";
         std::cout << "-bc {bc} sets the boundary condition used to identify injection surfaces. Default is 91.\n";
         std::cout << "-p {projectname} sets the project name, essentially the filename without the suffix.\n";
         std::cout << "-h prints this help menu.\n";
         std::cout << "Usage: ./plagprep -p titan_60s_MP\n";
         std::cout.flush( );
 }
Variable Documentation
int bndrycondition
The boundary condition corresponding to an injecting surface.
Supplied by the user and represents the boundary condition that will be searched in the prjname.top file.
Definition at line 42 of file plagprep.C.
Referenced by main(), parseCmdParameters(), and searchTopFile().
int numberOfBlocks
Definition at line 35 of file plagprep.C.
Referenced by parseCmdParameters(), and searchTopFile().
std::string outputfile
The number of blocks, read from the *.top file.
Definition at line 32 of file plagprep.C.
Referenced by main(), parseCmdParameters(), and searchTopFile().
std::string prjname
<
The project name, supplied by the user. The output file, computed based on prjname.
Definition at line 29 of file plagprep.C.
Referenced by main(), parseCmdParameters(), and searchTopFile().