Rocstar: PLAG_RFLU_Update.F90 File Reference
PLAG_RFLU_Update.F90 File Reference
Functions/Subroutines
subroutine plag_rflu_update (pRegion, iStage)
Function/Subroutine Documentation
subroutine plag_rflu_update (type(t_region), pointer pRegion, integer, intent(in) iStage)
Definition at line 47 of file PLAG_RFLU_Update.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_calcbreakup(), plag_calcrhsposition(), plag_modreallocatememory::plag_reallocmemwrapper(), plag_rflu_modfindcells::plag_rflu_computedisttot(), plag_rflu_modfindcells::plag_rflu_findcellsbrutemod(), plag_rflu_modfindcells::plag_rflu_findcellslohner(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), plag_rflu_modfindcells::plag_rflu_findcellstrajsafe(), plag_rflu_modcomm::plag_rflu_initsendcounters(), plag_rflu_injectiondriver(), moderror::registerfunction(), rflu_decideprint(), and rkupdategeneric().
Referenced by plag_rkupdatewrapper().