Rocstar: PLAG_InCellTest.F90 File Reference
PLAG_InCellTest.F90 File Reference
Functions/Subroutines
subroutine plag_incelltest (region, posPlag, indexSearch, ijkNR, ijkNRI, ijkNRJ, ijkNRK, indexNew, cellLocate)
Function/Subroutine Documentation
subroutine plag_incelltest (type(t_region) region, real(rfreal), dimension(3), intent(in) posPlag, integer, dimension(4), intent(in) indexSearch, integer, intent(in) ijkNR, integer, intent(in) ijkNRI, integer, intent(in) ijkNRJ, integer, intent(in) ijkNRK, integer, dimension(4), intent(out) indexNew, logical, intent(out) cellLocate)
Definition at line 49 of file PLAG_InCellTest.F90.
References moderror::deregisterfunction(), dot_product(), and moderror::registerfunction().
Referenced by plag_getcellindices().