Rocstar: PLAG_PatchGetBufferSize.F90 File Reference
PLAG_PatchGetBufferSize.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine plag_patchgetbuffersize (region)
Function/Subroutine Documentation
subroutine plag_patchgetbuffersize (type(t_region) region)
Definition at line 43 of file PLAG_PatchGetBufferSize.F90.
References moderror::deregisterfunction(), i, ibeg, ic, idir, iend, inode, j, jbeg, jc, jdir, jend, jnode, k, kbeg, kc, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by plag_patchupdate().