Rocstar: PLAG_InjcMakeParticle.F90 File Reference
PLAG_InjcMakeParticle.F90 File Reference
Functions/Subroutines
subroutine plag_injcmakeparticle (region, injcDiamDist, diam, spLoad)
real(rfreal) function plag_rand1logskewed (dPeak, sDev, dMin, dMax, alpha, power, rdata)
Function/Subroutine Documentation
subroutine plag_injcmakeparticle (type(t_region) region, integer injcDiamDist, real(rfreal) diam, real(rfreal) spLoad)
Definition at line 47 of file PLAG_InjcMakeParticle.F90.
References Color::alpha(), moderror::deregisterfunction(), moderror::errorstop(), plag_rand1logskewed(), modrandom::rand1imposedpdf(), modrandom::rand1lognormal(), modrandom::rand1uniform(), and moderror::registerfunction().
Referenced by plag_initpatchdata(), plag_injcejectparticle(), plag_injctileinitialize(), plag_modinjection::plag_invokeconsrandejec(), and plag_modinjection::plag_invokeejecmodel1().
real(rfreal) function plag_injcmakeparticle::plag_rand1logskewed (real(rfreal), intent(in) dPeak, real(rfreal), intent(in) sDev, real(rfreal), intent(in) dMin, real(rfreal), intent(in) dMax, real(rfreal), intent(in) alpha, real(rfreal), intent(in) power, type(t_rand_data), intent(inout) rdata)
Definition at line 140 of file PLAG_InjcMakeParticle.F90.
References Color::alpha(), modrandom::rand1lognormal(), and modrandom::rand1uniform().
Referenced by plag_injcmakeparticle().