Rocstar: PLAG_InjcTileInitialize.F90 File Reference
PLAG_InjcTileInitialize.F90 File Reference
Functions/Subroutines
subroutine plag_injctileinitialize (region)
Function/Subroutine Documentation
subroutine plag_injctileinitialize (type(t_region) region)
Definition at line 44 of file PLAG_InjcTileInitialize.F90.
References moderror::deregisterfunction(), plag_injcmakeparticle(), modrandom::rand1uniform(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and CImg< T >::sum().
Referenced by plag_allocatememory().