Rocstar: PLAG_RFLU_DeallocMemTStep.F90 File Reference
PLAG_RFLU_DeallocMemTStep.F90 File Reference
Functions/Subroutines
subroutine plag_rflu_deallocmemtstep (pRegion, pPlag)
Function/Subroutine Documentation
subroutine plag_rflu_deallocmemtstep (type(t_region), pointer pRegion, type(t_plag), pointer pPlag)
Definition at line 45 of file PLAG_RFLU_DeallocMemTStep.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by plag_modreallocatememory::plag_reallocmem(), and rflu_deallocatememorywrapper().