Rocstar: PLAG_PatchUpdateWrapper.F90 File Reference
PLAG_PatchUpdateWrapper.F90 File Reference
Functions/Subroutines
subroutine plag_patchupdatewrapper (regions)
Function/Subroutine Documentation
subroutine plag_patchupdatewrapper (type(t_region), dimension(:), pointer regions)
Definition at line 44 of file PLAG_PatchUpdateWrapper.F90.
References moderror::deregisterfunction(), plag_noncvupdate(), plag_patchbuffersendrecv(), plag_patchupdate(), and moderror::registerfunction().
Referenced by updateboundaryconditionsmp().