Rocstar: PLAG_PatchExchangeConf.F90 File Reference
PLAG_PatchExchangeConf.F90 File Reference
Functions/Subroutines
subroutine plag_patchexchangeconf (region, regionDes, patch, patchDes, iReg, iRegDes)
Function/Subroutine Documentation
subroutine plag_patchexchangeconf (type(t_region) region, type(t_region) regionDes, type(t_patch) patch, type(t_patch) patchDes, integer iReg, integer iRegDes)
Definition at line 54 of file PLAG_PatchExchangeConf.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modindexing::getijk(), ibeg, idir, iend, modindexing::indijkmap(), jbeg, jdir, jend, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and rflo_getpatchmapping().
Referenced by plag_boundaryconditionsset().