Rocstar: PLAG_RFLU_InitSolFromSerial.F90 File Reference
PLAG_RFLU_InitSolFromSerial.F90 File Reference
Functions/Subroutines
subroutine plag_rflu_initsolfromserial (pRegion, pRegionSerial)
Function/Subroutine Documentation
subroutine plag_rflu_initsolfromserial (type(t_region), pointer pRegion, type(t_region), pointer pRegionSerial)
Definition at line 46 of file PLAG_RFLU_InitSolFromSerial.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), j, max(), min(), moderror::registerfunction(), rflu_modrenumberings::rflu_rnmb_buildsc2pcmap(), rflu_modrenumberings::rflu_rnmb_createpbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_createpc2scmap(), rflu_modrenumberings::rflu_rnmb_createpv2svmap(), rflu_modrenumberings::rflu_rnmb_destroypbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_destroypv2svmap(), rflu_modrenumberings::rflu_rnmb_destroysc2pcmap(), rflu_modrenumberings::rflu_rnmb_readpxx2sxxmaps(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by rfluinit().