Rocstar: PLAG_ReadStatPost.F90 File Reference
PLAG_ReadStatPost.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine plag_readstatpost (regions, iReg)
Function/Subroutine Documentation
subroutine plag_readstatpost (type(t_region), dimension(:), pointer regions, integer, intent(in) iReg)
Definition at line 48 of file PLAG_ReadStatPost.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, idcbeg, idcend, modindexing::indijkmap(), j, jdcbeg, jdcend, k, kdcbeg, Aff_transformation_repS2< FT >::print(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getpatchdirection(), rflo_getpatchindices(), rflo_getpatchmapping(), rflo_readdatafileint(), rflo_readdatafilereal(), rflo_writedatafileint(), rflo_writedatafilereal(), and Attribute::status().
Referenced by rocpart_post().