Rocstar: PLAG_InjcEjectParticle.F90 File Reference
PLAG_InjcEjectParticle.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine plag_injcejectparticle (region, iReg)
subroutine plag_rflo_ejectparticle (region, pPlag, pTilePlag, iTile, lbound, iNOff, ijNOff, i, j, k, sxn, syn, szn, area, plagVolRatio)
subroutine plag_injcsetpositions (lbound, iNOff, ijNOff, i, j, k, sNormal, cellHeight, posPlag)
subroutine plag_injctestcell (region, iNOff, ijNOff, i, j, k, posPlag, cellLocate)
Function/Subroutine Documentation
subroutine plag_injcejectparticle (type(t_region) region, integer iReg)
Definition at line 46 of file PLAG_InjcEjectParticle.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, pi, plag_injcmakeparticle(), plag_injcsetinjection(), plag_rflo_ejectparticle(), modrandom::rand1uniform(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), sqrt(), and CImg< T >::sum().
Referenced by plag_update().
subroutine plag_injcejectparticle::plag_injcsetpositions (integer, intent(in) lbound, integer, intent(in) iNOff, integer, intent(in) ijNOff, integer, intent(in) i, integer, intent(in) j, integer, intent(in) k, real(rfreal), dimension(3), intent(in) sNormal, real(rfreal), intent(in) cellHeight, real(rfreal), dimension(3), intent(out) posPlag)
Definition at line 660 of file PLAG_InjcEjectParticle.F90.
References dot_product(), i, inode, j, jnode, k, and modrandom::rand1uniform().
Referenced by plag_rflo_ejectparticle().
subroutine plag_injcejectparticle::plag_injctestcell (type(t_region) region, integer, intent(in) iNOff, integer, intent(in) ijNOff, integer, intent(in) i, integer, intent(in) j, integer, intent(in) k, real(rfreal), dimension(3), intent(in) posPlag, logical, intent(out) cellLocate)
Definition at line 799 of file PLAG_InjcEjectParticle.F90.
References dot_product(), i, j, k, and CImg< T >::sum().
Referenced by plag_rflo_ejectparticle().
subroutine plag_injcejectparticle::plag_rflo_ejectparticle (type(t_region) region, type(t_plag), pointer pPlag, type(t_tile_plag), pointer pTilePlag, integer, intent(in) iTile, integer, intent(in) lbound, integer, intent(in) iNOff, integer, intent(in) ijNOff, integer, intent(in) i, integer, intent(in) j, integer, intent(in) k, real(rfreal), intent(in) sxn, real(rfreal), intent(in) syn, real(rfreal), intent(in) szn, real(rfreal), intent(in) area, real(rfreal), intent(in) plagVolRatio)
Definition at line 488 of file PLAG_InjcEjectParticle.F90.
References moderror::errorstop(), i, j, k, plag_injcsetpositions(), and plag_injctestcell().
Referenced by plag_injcejectparticle().