Rocstar: PLAG_RFLO_SendMetrics.F90 File Reference
PLAG_RFLO_SendMetrics.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine plag_rflo_sendmetrics (regions, iReg)
Function/Subroutine Documentation
subroutine plag_rflo_sendmetrics (type(t_region), dimension(:), pointer regions, integer, intent(in) iReg)
Definition at line 45 of file PLAG_RFLO_SendMetrics.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modindexing::getijk(), icorner, Mesh::GenericCell_2::nedges(), Mesh::GenericElement::nfaces(), plag_rflo_getfacemapping(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getedgecellsindices(), rflo_getnodeoffset(), and RFC_Data_const< _Tag >::tag().
Referenced by plag_rflo_sendrecvmetrics().