Rocstar: PLAG_RFLU_InitSolSerial_3D.F90 File Reference
PLAG_RFLU_InitSolSerial_3D.F90 File Reference
Functions/Subroutines
subroutine plag_rflu_initsolserial_3d (pRegion)
Function/Subroutine Documentation
subroutine plag_rflu_initsolserial_3d (type(t_region), pointer pRegion)
Definition at line 44 of file PLAG_RFLU_InitSolSerial_3D.F90.
References moderror::deregisterfunction(), moderror::errorstop(), min(), moderror::registerfunction(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_modoctree::rflu_buildoctree(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modoctree::rflu_createoctree(), rflu_modfacelist::rflu_destroycell2facelist(), rflu_modoctree::rflu_destroyoctree(), rflu_modincelltest::rflu_ict_testincell(), rflu_modoctree::rflu_queryoctree(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by plag_rflu_initsolserialwrapper().