Rocstar: PLAG_CalcDerivedVariables.F90 File Reference
PLAG_CalcDerivedVariables.F90 File Reference
Functions/Subroutines
subroutine plag_calcderivedvariables (region)
Function/Subroutine Documentation
subroutine plag_calcderivedvariables (type(t_region), intent(inout), target region)
Definition at line 43 of file PLAG_CalcDerivedVariables.F90.
References moderror::deregisterfunction(), pi, moderror::registerfunction(), and CImg< T >::sum().
Referenced by plag_initsolution(), plag_noncvupdate(), plag_rflu_modcomm::plag_rflu_commdriver(), and rocpart_post().