Rocstar: PLAG_ProcessEulerField.F90 File Reference
PLAG_ProcessEulerField.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine plag_processeulerfield (regions, iReg, nPclsSum)
Function/Subroutine Documentation
subroutine plag_processeulerfield (type(t_region), dimension(:), pointer regions, integer, intent(in) iReg, integer, intent(in) nPclsSum)
Definition at line 54 of file PLAG_ProcessEulerField.F90.
References Line_2< R, T >::a(), aver(), Kdtree_d< Traits >::Box::comp(), moderror::deregisterfunction(), moderror::errorstop(), form, setup_py::grid(), i, ic, idcbeg, idcend, idnbeg, idnend, ipcbeg, ipcend, ipnbeg, ipnend, j, jdcbeg, jdcend, jdnbeg, jdnend, jpcbeg, jpcend, jpnbeg, jpnend, k, kdcbeg, kdnbeg, kpcbeg, kpnbeg, Aff_transformation_repS2< FT >::print(), moderror::registerfunction(), rflo_copygeometrydummy(), rflo_generatecoarsegrids(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_readgridregion(), Attribute::status(), CImg< T >::sum(), v, and x.
Referenced by rocpart_post().