Rocstar: PLAG_ReadInputFile.F90 File Reference
PLAG_ReadInputFile.F90 File Reference
Functions/Subroutines
subroutine plag_readinputfile (regions)
Function/Subroutine Documentation
subroutine plag_readinputfile (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file PLAG_ReadInputFile.F90.
References moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, CImg< T >::line(), plag_readdispartinitsection(), plag_readdispartncontsection(), plag_readdispartsection(), moderror::registerfunction(), and Attribute::status().
Referenced by plag_userinput().