Rocstar: PLAG_RFLU_InitSolSerial_1D.F90 File Reference
PLAG_RFLU_InitSolSerial_1D.F90 File Reference
Functions/Subroutines
subroutine plag_rflu_initsolserial_1d (pRegion)
Function/Subroutine Documentation
subroutine plag_rflu_initsolserial_1d (type(t_region), pointer pRegion)
Definition at line 47 of file PLAG_RFLU_InitSolSerial_1D.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modfacelist::rflu_destroycell2facelist(), rflu_modincelltest::rflu_ict_testincell(), Bbox_2::xmax(), and Bbox_2::xmin().
Referenced by plag_rflu_initsolserialwrapper().