Rocstar: PLAG_BufferDataSend.F90 File Reference
PLAG_BufferDataSend.F90 File Reference
Functions/Subroutines
subroutine plag_bufferdatasend (regions, iReg)
Function/Subroutine Documentation
subroutine plag_bufferdatasend (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 44 of file PLAG_BufferDataSend.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modindexing::getijk(), modindexing::indijkmap(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and rflo_getpatchmapping().
Referenced by plag_patchbuffersendrecv().