Rocstar: PLAG_CalcFaceCentroids.F90 File Reference
PLAG_CalcFaceCentroids.F90 File Reference
Macros
#define IndIJK(x, y, z, o1, o2) ((x) + ((y) -1)*o1 + ((z)-1)*o2)
Functions/Subroutines
subroutine plag_calcfacecentroids (region)
Macro Definition Documentation
#define IndIJK (x, y, z, o1, o2) ((x) + ((y) -1)*o1 + ((z)-1)*o2)
Function/Subroutine Documentation
subroutine plag_calcfacecentroids (type(t_region) region)
Definition at line 43 of file PLAG_CalcFaceCentroids.F90.
References moderror::deregisterfunction(), i, idnbeg, idnend, j, jdnbeg, jdnend, k, kdnbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummynodes(), and rflo_getnodeoffset().
Referenced by plag_rflo_setmetrics().