Rocstar: PLAG_RFLO_SetMetrics.F90 File Reference
PLAG_RFLO_SetMetrics.F90 File Reference
Functions/Subroutines
subroutine plag_rflo_setmetrics (regions)
Function/Subroutine Documentation
subroutine plag_rflo_setmetrics (type(t_region), dimension(:), pointer regions)
Definition at line 44 of file PLAG_RFLO_SetMetrics.F90.
References moderror::deregisterfunction(), plag_calcfacecentroids(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_copyfacevectors(), plag_rflo_findgridmapping(), plag_rflo_sendrecvmetrics(), and moderror::registerfunction().
Referenced by rflo_initflowsolver(), and rflo_timestepping().