Rocstar: PlaneNorm.f90 File Reference
PlaneNorm.f90 File Reference
Functions/Subroutines
subroutine planenorm (x1, y1, z1, x2, y2, z2, x3, y3, z3, xn, yn, zn, same)
subroutine cross0_3d (x0, y0, z0, x1, y1, z1, x2, y2, z2, x3, y3, z3)
real *8 function calcoffset (x1, y1, z1, x2, y2, z2)
real *8 function offset (vNorm, x2, y2, z2)
Function/Subroutine Documentation
real*8 function calcoffset (real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2)
Definition at line 175 of file PlaneNorm.f90.
Referenced by calcoffset(), and volratio().
subroutine cross0_3d (real*8 x0, real*8 y0, real*8 z0, real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2, real*8 x3, real*8 y3, real*8 z3)
Definition at line 125 of file PlaneNorm.f90.
Referenced by planenorm().
real*8 function offset (real*8, dimension(1:3) vNorm, real*8 x2, real*8 y2, real*8 z2)
Definition at line 211 of file PlaneNorm.f90.
Referenced by Attribute::append_array(), BuildBorderStiffness(), Roccom_base::call_function(), GEM_Partition::Cell2Elem(), COM_copy_array(), com_obtain_array_f(), Roccom_base::copy_array(), Window::copy_array(), Attribute::copy_array(), copy_array_common(), MeshImplData::copy_mesh(), Pane_connectivity::create_b2map(), Mesh::BSExtent< T >::CreateUnstructuredMesh(), FaceOffset_3::denoise_surface(), GEM_Partition::Elem2Cell(), Connectivity::get_addr(), Simple_manifold_2::get_borders(), Simple_manifold_2::get_edge_index(), MesqPane::invert(), offset(), scan_files_HDF4(), Connectivity::set_offset(), Attribute::set_pointer(), Fileselect::testTecplot(), MesqPane::vertex_get_byte(), MesqPane::vertex_set_byte(), MesqPane::vertex_set_coordinates(), MesqPane::vertices_get_byte(), MesqPane::vertices_get_coordinates(), MesqPane::vertices_set_byte(), volratio(), write_attr_CGNS(), and WriteElements().
subroutine planenorm (real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2, real*8 x3, real*8 y3, real*8 z3, real*8 xn, real*8 yn, real*8 zn, integer same)
Definition at line 53 of file PlaneNorm.f90.
References cross0_3d(), sqrt(), and zn().
Referenced by volratio().