Rocstar: point_vector_definitions_3.C File Reference
point_vector_definitions_3.C File Reference
Macros
#define CGAL_POINT_VECTOR_DEFINITIONS_3_C
Functions
template<class R >
CGAL_BEGIN_NAMESPACE Vector_3< R > point_to_vector_conversion (const Point_3< R > &p)
template<class R >
Point_3< R > vector_to_point_conversion (const Vector_3< R > &v)
template<class R >
Point_3< R > operator+ (const Point_3< R > &p, const Vector_3< R > &v)
template<class R >
Point_3< R > operator- (const Point_3< R > &p, const Vector_3< R > &v)
template<class R >
Point_3< R > operator+ (const Origin &, const Vector_3< R > &v)
template<class R >
Point_3< R > operator- (const Origin &, const Vector_3< R > &v)
template<class R >
Vector_3< R > operator- (const Point_3< R > &p, const Point_3< R > &q)
template<class R >
Vector_3< R > operator- (const Point_3< R > &p, const Origin &)
template<class R >
Vector_3< R > operator- (const Origin &, const Point_3< R > &p)
Macro Definition Documentation
#define CGAL_POINT_VECTOR_DEFINITIONS_3_C
Definition at line 53 of file point_vector_definitions_3.C.
Function Documentation
Point_3<R> operator+ (const Point_3< R > & p, const Vector_3< R > & v) inline
Definition at line 72 of file point_vector_definitions_3.C.
References v.
 {
   typedef typename  R::Point_3_base  RPoint_3;
   typedef typename  R::Vector_3_base  RVector_3;
   return Point_3<R>((const RPoint_3& )p + (const RVector_3& )v) ;
 }
Point_3<R> operator+ (const Origin & , const Vector_3< R > & v) inline
Definition at line 92 of file point_vector_definitions_3.C.
References vector_to_point_conversion().
 { return vector_to_point_conversion(v) ; }
Point_3<R> operator- (const Point_3< R > & p, const Vector_3< R > & v) inline
Definition at line 82 of file point_vector_definitions_3.C.
References v.
 {
   typedef typename  R::Point_3_base  RPoint_3;
   typedef typename  R::Vector_3_base  RVector_3;
   return Point_3<R>((const RPoint_3& )p - (const RVector_3& )v) ;
 }
Point_3<R> operator- (const Origin & , const Vector_3< R > & v) inline
Definition at line 98 of file point_vector_definitions_3.C.
References vector_to_point_conversion().
 { return vector_to_point_conversion(-v) ; }
Vector_3<R> operator- (const Point_3< R > & p, const Point_3< R > & q) inline
Definition at line 104 of file point_vector_definitions_3.C.
 {
   typedef typename  R::Point_3_base  RPoint_3;
   return Vector_3<R>((const RPoint_3& )p - (const RPoint_3& )q) ;
 }
Vector_3<R> operator- (const Point_3< R > & p, const Origin &) inline
Definition at line 113 of file point_vector_definitions_3.C.
References point_to_vector_conversion().
 { return point_to_vector_conversion(p) ; }
Vector_3<R> operator- (const Origin & , const Point_3< R > & p) inline
Definition at line 119 of file point_vector_definitions_3.C.
References ORIGIN.
 {
   typedef typename  R::Point_3_base  RPoint_3;
   return Vector_3<R>(ORIGIN - (const RPoint_3& )p) ;
 }
CGAL_BEGIN_NAMESPACE Vector_3<R> point_to_vector_conversion (const Point_3< R > & p) inline
Definition at line 60 of file point_vector_definitions_3.C.
Referenced by operator-().
 { return Vector_3<R>(p); }
Point_3<R> vector_to_point_conversion (const Vector_3< R > & v) inline
Definition at line 66 of file point_vector_definitions_3.C.
References v.
Referenced by operator+(), and operator-().
 { return Point_3<R>(v); }