Rocstar: point_vector_definitions_2.C File Reference
point_vector_definitions_2.C File Reference
Macros
#define CGAL_POINT_VECTOR_DEFINITIONS_2_C
Functions
template<class R >
CGAL_BEGIN_NAMESPACE Vector_2< R > point_to_vector_conversion (const Point_2< R > &p)
template<class R >
Point_2< R > vector_to_point_conversion (const Vector_2< R > &v)
template<class R >
Point_2< R > operator+ (const Point_2< R > &p, const Vector_2< R > &v)
template<class R >
Point_2< R > operator- (const Point_2< R > &p, const Vector_2< R > &v)
template<class R >
Point_2< R > operator+ (const Origin &, const Vector_2< R > &v)
template<class R >
Point_2< R > operator- (const Origin &, const Vector_2< R > &v)
template<class R >
Vector_2< R > operator- (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
Vector_2< R > operator- (const Point_2< R > &p, const Origin &)
template<class R >
Vector_2< R > operator- (const Origin &, const Point_2< R > &p)
Macro Definition Documentation
#define CGAL_POINT_VECTOR_DEFINITIONS_2_C
Definition at line 53 of file point_vector_definitions_2.C.
Function Documentation
Point_2<R> operator+ (const Point_2< R > & p, const Vector_2< R > & v) inline
Definition at line 72 of file point_vector_definitions_2.C.
References v.
 {
   typedef typename  R::Point_2_base  RPoint_2;
   typedef typename  R::Vector_2_base  RVector_2;
   return Point_2<R>((const RPoint_2& )p + (const RVector_2& )v) ;
 }
Point_2<R> operator+ (const Origin & , const Vector_2< R > & v) inline
Definition at line 92 of file point_vector_definitions_2.C.
References vector_to_point_conversion().
 { return vector_to_point_conversion(v) ; }
Point_2<R> operator- (const Point_2< R > & p, const Vector_2< R > & v) inline
Definition at line 82 of file point_vector_definitions_2.C.
References v.
 {
   typedef typename  R::Point_2_base  RPoint_2;
   typedef typename  R::Vector_2_base  RVector_2;
   return Point_2<R>((const RPoint_2& )p - (const RVector_2& )v) ;
 }
Point_2<R> operator- (const Origin & , const Vector_2< R > & v) inline
Definition at line 98 of file point_vector_definitions_2.C.
References vector_to_point_conversion().
Referenced by Direction_3< R, T >::operator-(), Vector_3< Real >::operator-(), Direction_2< R, T >::operator-(), and Vector_2< T >::operator-().
 { return vector_to_point_conversion(-v) ; }
Vector_2<R> operator- (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 104 of file point_vector_definitions_2.C.
 {
   typedef typename  R::Point_2_base  RPoint_2;
   return Vector_2<R>((const RPoint_2& )p - (const RPoint_2& )q) ;
 }
Vector_2<R> operator- (const Point_2< R > & p, const Origin &) inline
Definition at line 113 of file point_vector_definitions_2.C.
References point_to_vector_conversion().
 { return point_to_vector_conversion(p) ; }
Vector_2<R> operator- (const Origin & , const Point_2< R > & p) inline
Definition at line 119 of file point_vector_definitions_2.C.
References ORIGIN.
 {
   typedef typename  R::Point_2_base  RPoint_2;
   return Vector_2<R>(ORIGIN - (const RPoint_2& )p) ;
 }
CGAL_BEGIN_NAMESPACE Vector_2<R> point_to_vector_conversion (const Point_2< R > & p) inline
Definition at line 60 of file point_vector_definitions_2.C.
Referenced by operator-().
 { return Vector_2<R>(p); }
Point_2<R> vector_to_point_conversion (const Vector_2< R > & v) inline
Definition at line 66 of file point_vector_definitions_2.C.
References v.
Referenced by operator+(), and operator-().
 { return Point_2<R>(v); }