Rocstar: Point_2.h File Reference
Point_2.h File Reference
#include <CGAL/point_vector_declarations_2.h>
#include <CGAL/Vector_2.h>
#include <CGAL/point_vector_definitions_2.C>
#include <CGAL/Aff_transformation_2.h>
Classes
class Point_2< T >
Functions
template<class R >
std::ostream & operator<< (std::ostream &os, const Point_2< R > &p)
template<class R >
std::istream & operator>> (std::istream &is, Point_2< R > &p)
template<class R >
Point_2< R > operator+ (const Origin &o, const Vector_2< R > &v)
template<class R >
Point_2< R > operator- (const Origin &o, const Vector_2< R > &v)
template<class R >
Vector_2< R > operator- (const Point_2< R > &p, const Origin &)
template<class R >
CGAL_END_NAMESPACE
CGAL_BEGIN_NAMESPACE bool operator== (const Origin &o, const Point_2< R > &p)
template<class R >
bool operator!= (const Origin &o, const Point_2< R > &p)
Function Documentation
bool operator!= (const Origin & o, const Point_2< R > & p) inline
Definition at line 245 of file Point_2.h.
 { return p != o; }
Point_2<R> operator+ (const Origin & o, const Vector_2< R > & v) inline
Definition at line 92 of file point_vector_definitions_2.C.
 { return vector_to_point_conversion(v) ; }
Point_2<R> operator- (const Origin & o, const Vector_2< R > & v) inline
Definition at line 98 of file point_vector_definitions_2.C.
Referenced by Direction_3< R, T >::operator-(), Vector_3< Real >::operator-(), Direction_2< R, T >::operator-(), and Vector_2< T >::operator-().
 { return vector_to_point_conversion(-v) ; }
Vector_2<R> operator- (const Point_2< R > & p, const Origin &) inline
Definition at line 113 of file point_vector_definitions_2.C.
 { return point_to_vector_conversion(p) ; }
std::ostream& operator<< (std::ostream & os, const Point_2< R > & p)
Definition at line 189 of file Point_2.h.
 {
   typedef typename  R::Point_2_base  RPoint_2;
   return os << (const RPoint_2&)p;
 }
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE bool operator== (const Origin & o, const Point_2< R > & p) inline
Definition at line 239 of file Point_2.h.
Referenced by Ray_3< R, T >::operator==(), Segment_3< R, T >::operator==(), Direction_3< R, T >::operator==(), Vector_2< T >::operator==(), Vector_3< Real >::operator==(), Point_3< Real >::operator==(), Direction_2< R, T >::operator==(), Line_3< R, T >::operator==(), Point_2< R >::operator==(), Ray_2< R, T >::operator==(), Segment_2< R >::operator==(), Plane_3< R, T >::operator==(), and Line_2< R >::operator==().
 { return p == o; }
std::istream& operator>> (std::istream & is, Point_2< R > & p)
Definition at line 199 of file Point_2.h.
 {
   typedef typename  R::Point_2_base  RPoint_2;
   return is >> (RPoint_2&)p;
 }