Rocstar: RFLU_AllocMemSolWrapper.F90 File Reference
post/RFLU_AllocMemSolWrapper.F90 File Reference
Functions/Subroutines
subroutine rflu_allocmemsolwrapper (pRegion)
Function/Subroutine Documentation
subroutine rflu_allocmemsolwrapper (type(t_region), pointer pRegion)
Definition at line 44 of file post/RFLU_AllocMemSolWrapper.F90.
References moderror::deregisterfunction(), plag_rflu_allocmemsol(), plag_rflu_allocmemsoltile(), moderror::registerfunction(), rflu_modallocatememory::rflu_allocatememorysolcv(), rflu_modallocatememory::rflu_allocatememorysoldv(), rflu_modallocatememory::rflu_allocatememorysolgv(), rflu_modallocatememory::rflu_allocatememorysoltv(), spec_rflu_allocatememoryeev(), and spec_rflu_allocatememorysol().