Rocstar: POST_WriteTecplotAscii.F90 File Reference
POST_WriteTecplotAscii.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine writetecplotascii (iReg, region)
Function/Subroutine Documentation
subroutine writetecplotascii (integer iReg, type(t_region) region)
Definition at line 44 of file POST_WriteTecplotAscii.F90.
References Line_2< R, T >::a(), aver(), aver1d(), averdiv(), Line_2< R, T >::c(), moderror::deregisterfunction(), moderror::errorstop(), form, i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), sqrt(), Attribute::status(), v, and x.
Referenced by peul_rocflo_post(), and rocflo_post().