Rocstar: POST_Average.F90 File Reference
POST_Average.F90 File Reference
Functions/Subroutines
double precision function aver1d (cell, var)
double precision function aver (cell, iEq, var)
double precision function averdiv (cell, iEq1, var1, iEq2, var2)
Function/Subroutine Documentation
double precision function aver (integer, dimension(8) cell, integer iEq, real(rfreal), dimension(:,:), pointer var)
Definition at line 68 of file POST_Average.F90.
Referenced by aver(), plag_processeulerfield(), plag_writestattecascii(), writegeneric(), writetecplotascii(), and writetecplotbinary().
double precision function aver1d (integer, dimension(8) cell, real(rfreal), dimension(:), pointer var)
Definition at line 47 of file POST_Average.F90.
Referenced by aver1d(), writegeneric(), writetecplotascii(), and writetecplotbinary().
double precision function averdiv (integer, dimension(8) cell, integer iEq1, real(rfreal), dimension(:,:), pointer var1, integer iEq2, real(rfreal), dimension(:,:), pointer var2)
Definition at line 89 of file POST_Average.F90.
Referenced by averdiv(), writegeneric(), writetecplotascii(), and writetecplotbinary().