Rocstar: predicates_on_pointsS3.h File Reference
predicates_on_pointsS3.h File Reference
#include <CGAL/predicates/kernel_ftC3.h>
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE
Comparison_result compare_lexicographically_xyz (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
Comparison_result compare_lexicographically_xy (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool lexicographically_xyz_smaller_or_equal (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool lexicographically_xyz_smaller (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool lexicographically_xy_smaller (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool x_equal (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool y_equal (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool z_equal (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool equal_xy (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool equal_xyz (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
Comparison_result compare_x (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
Comparison_result compare_y (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
Comparison_result compare_z (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool less_x (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool less_y (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool less_z (const PointS3< FT > &p, const PointS3< FT > &q)
template<class FT >
bool collinear (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r)
template<class FT >
Orientation orientation (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r, const PointS3< FT > &s)
template<class FT >
bool coplanar (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r, const PointS3< FT > &s)
template<class FT >
bool are_positive_oriented (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r, const PointS3< FT > &s)
template<class FT >
bool are_negative_oriented (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r, const PointS3< FT > &s)
template<class FT >
bool are_ordered_along_line (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r)
template<class FT >
bool collinear_are_ordered_along_line (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r)
template<class FT >
bool are_strictly_ordered_along_line (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r)
template<class FT >
bool collinear_are_strictly_ordered_along_line (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r)
template<class FT >
Orientation coplanar_orientation (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r, const PointS3< FT > &s)
template<class FT >
Oriented_side side_of_oriented_sphere (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r, const PointS3< FT > &s, const PointS3< FT > &test)
template<class FT >
Bounded_side side_of_bounded_sphere (const PointS3< FT > &p, const PointS3< FT > &q, const PointS3< FT > &r, const PointS3< FT > &s, const PointS3< FT > &test)
Function Documentation
bool are_negative_oriented (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r, const PointS3< FT > & s) inline
Definition at line 210 of file predicates_on_pointsS3.h.
References NEGATIVE, and orientation().
 {
   return orientation(p,q,r,s) == NEGATIVE;
 }
bool are_ordered_along_line (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r) inline
Definition at line 221 of file predicates_on_pointsS3.h.
References collinear(), and collinear_are_ordered_along_line().
 {
   return (collinear(p, q, r)) ? collinear_are_ordered_along_line(p, q, r)
                               : false;
 }
bool are_positive_oriented (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r, const PointS3< FT > & s) inline
Definition at line 199 of file predicates_on_pointsS3.h.
References orientation(), and POSITIVE.
 {
   return orientation(p,q,r,s) == POSITIVE;
 }
bool are_strictly_ordered_along_line (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r) inline
Definition at line 246 of file predicates_on_pointsS3.h.
References collinear(), and collinear_are_strictly_ordered_along_line().
 {
   return (collinear(p, q, r))
          ? collinear_are_strictly_ordered_along_line(p, q, r)
          : false;
 }
bool collinear (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r)
Definition at line 162 of file predicates_on_pointsS3.h.
References collinearC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by are_ordered_along_line(), are_strictly_ordered_along_line(), collinear_are_ordered_along_line(), collinear_are_strictly_ordered_along_line(), and coplanar_orientation().
 {
   return collinearC3(p.x(), p.y(), p.z(),
                      q.x(), q.y(), q.z(),
                      r.x(), r.y(), r.z());
 }
bool collinear_are_ordered_along_line (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r) inline
Definition at line 232 of file predicates_on_pointsS3.h.
References CGAL_kernel_exactness_precondition, collinear(), collinear_are_ordered_along_lineC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by are_ordered_along_line().
 {
   CGAL_kernel_exactness_precondition( collinear(p, q, r) );
   return collinear_are_ordered_along_lineC3(p.x(),p.y(),p.z(),
                                             q.x(),q.y(),q.z(),
                                             r.x(),r.y(),r.z());
 }
bool collinear_are_strictly_ordered_along_line (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r) inline
Definition at line 259 of file predicates_on_pointsS3.h.
References CGAL_kernel_exactness_precondition, collinear(), collinear_are_strictly_ordered_along_lineC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by are_strictly_ordered_along_line().
 {
   CGAL_kernel_exactness_precondition( collinear(p, q, r) );
   return collinear_are_strictly_ordered_along_lineC3(p.x(),p.y(),p.z(),
                                                      q.x(),q.y(),q.z(),
                                                      r.x(),r.y(),r.z());
 }
Comparison_result compare_lexicographically_xy (const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 68 of file predicates_on_pointsS3.h.
References compare_lexicographically_xyC2(), PointS3< FT >::x(), and PointS3< FT >::y().
Referenced by lexicographically_xy_smaller().
 {
   return compare_lexicographically_xyC2(p.x(),p.y(),
                                         q.x(),q.y());
 }
CGAL_BEGIN_NAMESPACE Comparison_result compare_lexicographically_xyz (const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 60 of file predicates_on_pointsS3.h.
References compare_lexicographically_xyzC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by lexicographically_xyz_smaller(), lexicographically_xyz_smaller_or_equal(), and Compare_xyz::operator()().
 {
   return compare_lexicographically_xyzC3(p.x(),p.y(),p.z(),
                                          q.x(),q.y(),q.z());
 }
Comparison_result compare_x (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 125 of file predicates_on_pointsS3.h.
References CGAL_NTS, CGAL::compare(), and PointS3< FT >::x().
 { return CGAL_NTS compare(p.x(), q.x()); }
Comparison_result compare_y (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 132 of file predicates_on_pointsS3.h.
References CGAL_NTS, CGAL::compare(), and PointS3< FT >::y().
 { return CGAL_NTS compare(p.y(), q.y()); }
Comparison_result compare_z (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 139 of file predicates_on_pointsS3.h.
References CGAL_NTS, CGAL::compare(), and PointS3< FT >::z().
Referenced by RayS3< FT >::collinear_has_on(), and Compare_z::operator()().
 { return CGAL_NTS compare(p.z(), q.z()); }
bool coplanar (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r, const PointS3< FT > & s) inline
Definition at line 188 of file predicates_on_pointsS3.h.
References COLLINEAR, and orientation().
Referenced by coplanar_orientation(), and Coplanar::operator()().
 {
   return orientation(p, q, r, s) == COLLINEAR;
 }
Orientation coplanar_orientation (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r, const PointS3< FT > & s)
Definition at line 272 of file predicates_on_pointsS3.h.
References CGAL_kernel_exactness_precondition, collinear(), coplanar(), coplanar_orientationC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
 {
   CGAL_kernel_exactness_precondition( ! collinear(p, q, r) );
   CGAL_kernel_exactness_precondition( coplanar(s, p, q, r) );
   return coplanar_orientationC3(p.x(), p.y(), p.z(),
                                 q.x(), q.y(), q.z(),
                                 r.x(), r.y(), r.z(),
                                 s.x(), s.y(), s.z());
 }
bool equal_xy (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 113 of file predicates_on_pointsS3.h.
References PointS3< FT >::x(), and PointS3< FT >::y().
 { return p.x() == q.x() && p.y() == q.y(); }
bool equal_xyz (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 119 of file predicates_on_pointsS3.h.
References PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by Equal_xyz::operator()().
 { return p.x() == q.x() && p.y() == q.y() && p.z() == q.z(); }
bool less_x (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 145 of file predicates_on_pointsS3.h.
References PointS3< FT >::x().
 { return p.x() < q.x(); }
bool less_y (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 151 of file predicates_on_pointsS3.h.
References PointS3< FT >::y().
 { return p.y() < q.y(); }
bool less_z (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 157 of file predicates_on_pointsS3.h.
References PointS3< FT >::z().
 { return p.z() < q.z(); }
bool lexicographically_xy_smaller (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 88 of file predicates_on_pointsS3.h.
References compare_lexicographically_xy(), and SMALLER.
 { return compare_lexicographically_xy(p,q) == SMALLER; }
bool lexicographically_xyz_smaller (const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 82 of file predicates_on_pointsS3.h.
References compare_lexicographically_xyz(), and SMALLER.
Referenced by SegmentS3< FT >::max(), SegmentS3< FT >::min(), Less_xyz::operator()(), and PointS3< FT >::operator<().
 { return compare_lexicographically_xyz(p,q) == SMALLER; }
bool lexicographically_xyz_smaller_or_equal (const PointS3< FT > & p, const PointS3< FT > & q)
Definition at line 76 of file predicates_on_pointsS3.h.
References compare_lexicographically_xyz(), and LARGER.
 { return compare_lexicographically_xyz(p,q) != LARGER; }
Orientation orientation (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r, const PointS3< FT > & s) inline
Definition at line 174 of file predicates_on_pointsS3.h.
References orientationC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by are_negative_oriented(), are_positive_oriented(), and coplanar().
 {
   return orientationC3(p.x(), p.y(), p.z(),
                        q.x(), q.y(), q.z(),
                        r.x(), r.y(), r.z(),
                        s.x(), s.y(), s.z());
 }
Bounded_side side_of_bounded_sphere (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r, const PointS3< FT > & s, const PointS3< FT > & test)
Definition at line 304 of file predicates_on_pointsS3.h.
References side_of_bounded_sphereC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by Side_of_bounded_sphere::operator()().
 {
   return side_of_bounded_sphereC3(p.x(),p.y(),p.z(),
                                   q.x(),q.y(),q.z(),
                                   r.x(),r.y(),r.z(),
                                   s.x(),s.y(),s.z(),
                                   test.x(),test.y(),test.z());
 }
Oriented_side side_of_oriented_sphere (const PointS3< FT > & p, const PointS3< FT > & q, const PointS3< FT > & r, const PointS3< FT > & s, const PointS3< FT > & test)
Definition at line 288 of file predicates_on_pointsS3.h.
References side_of_oriented_sphereC3(), PointS3< FT >::x(), PointS3< FT >::y(), and PointS3< FT >::z().
Referenced by Side_of_oriented_sphere::operator()().
 {
   return side_of_oriented_sphereC3(p.x(),p.y(),p.z(),
                                    q.x(),q.y(),q.z(),
                                    r.x(),r.y(),r.z(),
                                    s.x(),s.y(),s.z(),
                                    test.x(),test.y(),test.z());
 }
bool x_equal (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 94 of file predicates_on_pointsS3.h.
References PointS3< FT >::x().
 { return p.x() == q.x(); }
bool y_equal (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 101 of file predicates_on_pointsS3.h.
References PointS3< FT >::y().
 { return p.y() == q.y(); }
bool z_equal (const PointS3< FT > & p, const PointS3< FT > & q) inline
Definition at line 107 of file predicates_on_pointsS3.h.
References PointS3< FT >::z().
Referenced by Equal_z::operator()().
 { return p.z() == q.z(); }