Rocstar: predicates_on_pointsS2.h File Reference
predicates_on_pointsS2.h File Reference
#include <CGAL/SimpleCartesian/simple_cartesian_classes.h>
#include <CGAL/SimpleCartesian/PointS2.h>
#include <CGAL/predicates/kernel_ftC2.h>
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE bool x_equal (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
bool y_equal (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
bool equal_xy (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
bool less_x (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
bool less_y (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
Comparison_result compare_x (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
Comparison_result compare_y (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
Comparison_result compare_deltax_deltay (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r, const PointS2< FT > &s)
template<class FT >
Comparison_result compare_lexicographically_xy (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
bool lexicographically_xy_smaller_or_equal (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
bool lexicographically_xy_smaller (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
Comparison_result compare_lexicographically_yx (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
bool lexicographically_yx_smaller_or_equal (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
bool lexicographically_yx_smaller (const PointS2< FT > &p, const PointS2< FT > &q)
template<class FT >
Orientation orientation (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
bool collinear (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
bool collinear_are_ordered_along_line (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
bool are_ordered_along_line (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
bool collinear_are_strictly_ordered_along_line (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
bool are_strictly_ordered_along_line (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
bool leftturn (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
bool leftturn (const Origin &o, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
bool rightturn (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
bool rightturn (const Origin &o, const PointS2< FT > &q, const PointS2< FT > &r)
template<class FT >
Oriented_side side_of_oriented_circle (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r, const PointS2< FT > &test)
template<class FT >
Bounded_side side_of_bounded_circle (const PointS2< FT > &p, const PointS2< FT > &q, const PointS2< FT > &r, const PointS2< FT > &test)
Function Documentation
bool are_ordered_along_line (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 206 of file predicates_on_pointsS2.h.
References collinear(), and collinear_are_ordered_along_line().
 {
   if (!collinear(p, q, r)) { return false; }
   return collinear_are_ordered_along_line(p, q, r);
 }
bool are_strictly_ordered_along_line (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 229 of file predicates_on_pointsS2.h.
References collinear(), and collinear_are_strictly_ordered_along_line().
 {
   if (!collinear(p, q, r)) { return false; }
   return collinear_are_strictly_ordered_along_line(p, q, r);
 }
bool collinear (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 182 of file predicates_on_pointsS2.h.
References COLLINEAR, and orientation().
Referenced by are_ordered_along_line(), and are_strictly_ordered_along_line().
 {
   return (orientation(p,q,r) == COLLINEAR);
 }
bool collinear_are_ordered_along_line (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 194 of file predicates_on_pointsS2.h.
References collinear_are_ordered_along_lineC2(), PointS2< FT >::x(), and PointS2< FT >::y().
Referenced by are_ordered_along_line().
 {
   return collinear_are_ordered_along_lineC2
              (p.x(),p.y(),q.x(),q.y(),r.x(),r.y());
 }
bool collinear_are_strictly_ordered_along_line (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 217 of file predicates_on_pointsS2.h.
References collinear_are_strictly_ordered_along_lineC2(), PointS2< FT >::x(), and PointS2< FT >::y().
Referenced by are_strictly_ordered_along_line().
 {
   return collinear_are_strictly_ordered_along_lineC2
                (p.x(),p.y(),q.x(),q.y(),r.x(),r.y());
 }
Comparison_result compare_deltax_deltay (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r, const PointS2< FT > & s) inline
Definition at line 106 of file predicates_on_pointsS2.h.
References compare_deltax_deltayC2(), PointS2< FT >::x(), and PointS2< FT >::y().
 {
   return compare_deltax_deltayC2(p.x(), q.x(), r.y(), s.y());
 }
Comparison_result compare_lexicographically_xy (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 117 of file predicates_on_pointsS2.h.
References compare_lexicographically_xyC2(), PointS2< FT >::x(), and PointS2< FT >::y().
Referenced by lexicographically_xy_smaller(), and lexicographically_xy_smaller_or_equal().
 {
   return compare_lexicographically_xyC2(p.x(),p.y(),q.x(),q.y());
 }
Comparison_result compare_lexicographically_yx (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 144 of file predicates_on_pointsS2.h.
References compare_lexicographically_xyC2(), PointS2< FT >::x(), and PointS2< FT >::y().
Referenced by lexicographically_yx_smaller(), and lexicographically_yx_smaller_or_equal().
 {
   return compare_lexicographically_xyC2(p.y(),p.x(),q.y(),q.x());
 }
Comparison_result compare_x (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 94 of file predicates_on_pointsS2.h.
References CGAL_NTS, CGAL::compare(), and PointS2< FT >::x().
 { return CGAL_NTS compare(p.x(), q.x()); }
Comparison_result compare_y (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 100 of file predicates_on_pointsS2.h.
References CGAL_NTS, CGAL::compare(), and PointS2< FT >::y().
 { return CGAL_NTS compare(p.y(), q.y()); }
bool equal_xy (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 76 of file predicates_on_pointsS2.h.
References PointS2< FT >::x(), and PointS2< FT >::y().
Referenced by Equal_xy::operator()().
 { return (p.x() == q.x()) && (p.y() == q.y()); }
bool leftturn (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 240 of file predicates_on_pointsS2.h.
References LEFTTURN, and orientation().
 {
   return (orientation(p,q,r) == LEFTTURN );
 }
bool leftturn (const Origin & o, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 250 of file predicates_on_pointsS2.h.
References LEFTTURN, orientationC2(), PointS2< FT >::x(), and PointS2< FT >::y().
 {
    return (orientationC2(FT(0), FT(0), q.x(), q.y(), r.x(), r.y())
            == LEFTTURN );
 }
bool less_x (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 82 of file predicates_on_pointsS2.h.
References PointS2< FT >::x().
Referenced by Less_x::operator()().
 { return (p.x() < q.x()); }
bool less_y (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 88 of file predicates_on_pointsS2.h.
References PointS2< FT >::y().
Referenced by Less_y::operator()(), and Less_z::operator()().
 { return (p.y() < q.y()); }
bool lexicographically_xy_smaller (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 135 of file predicates_on_pointsS2.h.
References compare_lexicographically_xy(), and SMALLER.
 {
   return compare_lexicographically_xy(p,q) == SMALLER ;
 }
bool lexicographically_xy_smaller_or_equal (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 126 of file predicates_on_pointsS2.h.
References compare_lexicographically_xy(), and LARGER.
 {
   return ( !( compare_lexicographically_xy(p,q) == LARGER ) );
 }
bool lexicographically_yx_smaller (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 163 of file predicates_on_pointsS2.h.
References compare_lexicographically_yx(), and SMALLER.
 {
     return compare_lexicographically_yx(p,q) == SMALLER ;
 }
bool lexicographically_yx_smaller_or_equal (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 154 of file predicates_on_pointsS2.h.
References compare_lexicographically_yx(), and LARGER.
 {
     return  !( compare_lexicographically_yx(p,q) == LARGER ) ;
 }
Orientation orientation (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 172 of file predicates_on_pointsS2.h.
References orientationC2(), PointS2< FT >::x(), and PointS2< FT >::y().
Referenced by collinear(), and leftturn().
 {
     return orientationC2(p.x(), p.y(), q.x(), q.y(), r.x(), r.y());
 }
bool rightturn (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 261 of file predicates_on_pointsS2.h.
References orientationC2(), RIGHTTURN, PointS2< FT >::x(), and PointS2< FT >::y().
 {
    return (orientationC2(p.x(), p.y(), q.x(), q.y(), r.x(), r.y())
            == RIGHTTURN);
 }
bool rightturn (const Origin & o, const PointS2< FT > & q, const PointS2< FT > & r) inline
Definition at line 272 of file predicates_on_pointsS2.h.
References orientationC2(), RIGHTTURN, PointS2< FT >::x(), and PointS2< FT >::y().
 {
    return (orientationC2(FT(0), FT(0), q.x(), q.y(), r.x(), r.y())
            == RIGHTTURN);
 }
Bounded_side side_of_bounded_circle (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r, const PointS2< FT > & test) inline
Definition at line 296 of file predicates_on_pointsS2.h.
References side_of_bounded_circleC2(), PointS2< FT >::x(), and PointS2< FT >::y().
 {
   return side_of_bounded_circleC2
              (p.x(),p.y(),q.x(),q.y(),r.x(),r.y(),test.x(),test.y());
 }
Oriented_side side_of_oriented_circle (const PointS2< FT > & p, const PointS2< FT > & q, const PointS2< FT > & r, const PointS2< FT > & test) inline
Definition at line 283 of file predicates_on_pointsS2.h.
References side_of_oriented_circleC2(), PointS2< FT >::x(), and PointS2< FT >::y().
 {
   return side_of_oriented_circleC2
              (p.x(),p.y(),q.x(),q.y(),r.x(),r.y(),test.x(),test.y());
 }
CGAL_BEGIN_NAMESPACE bool x_equal (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 64 of file predicates_on_pointsS2.h.
References PointS2< FT >::x().
 { return p.x() == q.x(); }
bool y_equal (const PointS2< FT > & p, const PointS2< FT > & q) inline
Definition at line 70 of file predicates_on_pointsS2.h.
References PointS2< FT >::y().
 { return p.y() == q.y(); }