Rocstar: predicates_on_points_2.h File Reference
predicates_on_points_2.h File Reference
#include <CGAL/Point_2.h>
Functions
template<class R >
CGAL_BEGIN_NAMESPACE bool x_equal (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool y_equal (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
Comparison_result compare_x (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
Comparison_result compare_y (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
Comparison_result compare_deltax_deltay (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r, const Point_2< R > &s)
template<class R >
Comparison_result compare_lexicographically_xy (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool lexicographically_xy_smaller_or_equal (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool lexicographically_xy_smaller (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool lexicographically_xy_larger_or_equal (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool lexicographically_xy_larger (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
Comparison_result compare_lexicographically_yx (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool lexicographically_yx_smaller_or_equal (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool lexicographically_yx_smaller (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool lexicographically_yx_larger_or_equal (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool lexicographically_yx_larger (const Point_2< R > &p, const Point_2< R > &q)
template<class R >
bool are_ordered_along_line (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r)
template<class R >
bool collinear_are_ordered_along_line (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r)
template<class R >
bool are_strictly_ordered_along_line (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r)
template<class R >
bool collinear_are_strictly_ordered_along_line (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r)
template<class R >
bool collinear (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r)
template<class R >
bool leftturn (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r)
template<class R >
bool rightturn (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r)
template<class R >
bool rightturn (const Origin &o, const Point_2< R > &q, const Point_2< R > &r)
template<class R >
Orientation orientation (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r)
template<class R >
Oriented_side side_of_oriented_circle (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r, const Point_2< R > &test)
template<class R >
Bounded_side side_of_bounded_circle (const Point_2< R > &p, const Point_2< R > &q, const Point_2< R > &r, const Point_2< R > &test)
Function Documentation
bool are_ordered_along_line (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r) inline
Definition at line 247 of file predicates_on_points_2.h.
Referenced by SegmentS3< FT >::has_on(), and Are_ordered_along_line::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return are_ordered_along_line((const RPoint_2&)p,
                                 (const RPoint_2&)q,
                                 (const RPoint_2&)r);
 }
bool are_strictly_ordered_along_line (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r) inline
Definition at line 273 of file predicates_on_points_2.h.
Referenced by Are_strictly_ordered_along_line::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return are_strictly_ordered_along_line((const RPoint_2&)p,
                                          (const RPoint_2&)q,
                                          (const RPoint_2&)r);
 }
bool collinear (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r) inline
Definition at line 298 of file predicates_on_points_2.h.
Referenced by are_ordered_along_line(), are_strictly_ordered_along_line(), collinear_are_ordered_along_line(), collinear_are_strictly_ordered_along_line(), SegmentS2< FT >::collinear_has_on(), RayS3< FT >::collinear_has_on(), coplanar_orientation(), SegmentS2< FT >::has_on(), RayS3< FT >::has_on(), LineS3< FT >::has_on(), RayS2< FT >::has_on(), and Collinear::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return (collinear((const RPoint_2&)p,
                     (const RPoint_2&)q,
                     (const RPoint_2&)r));
 }
bool collinear_are_ordered_along_line (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r) inline
Definition at line 260 of file predicates_on_points_2.h.
Referenced by are_ordered_along_line(), SegmentS3< FT >::collinear_has_on(), p_Less_rotate_ccw< Point >::operator()(), p_Less_rotate_ccw_safer< Point >::operator()(), and Collinear_are_ordered_along_line::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return collinear_are_ordered_along_line((const RPoint_2&)p,
                                           (const RPoint_2&)q,
                                           (const RPoint_2&)r);
 }
bool collinear_are_strictly_ordered_along_line (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r) inline
Definition at line 285 of file predicates_on_points_2.h.
Referenced by are_strictly_ordered_along_line(), and Collinear_are_strictly_ordered_along_line::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return
   collinear_are_strictly_ordered_along_line((const RPoint_2&)p,
                                             (const RPoint_2&)q,
                                             (const RPoint_2&)r);
 }
Comparison_result compare_deltax_deltay (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r, const Point_2< R > & s) inline
Definition at line 121 of file predicates_on_points_2.h.
 {
   typedef typename R::Point_2_base  RPoint_2;
   return compare_deltax_deltay((const RPoint_2&)p,
                                (const RPoint_2&)q,
                                (const RPoint_2&)r,
                                (const RPoint_2&)s);
 }
Comparison_result compare_lexicographically_xy (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 136 of file predicates_on_points_2.h.
Referenced by CGAL::do_intersect(), lexicographically_xy_smaller(), lexicographically_xy_smaller_or_equal(), and Compare_xy::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return  compare_lexicographically_xy((const RPoint_2&)p,
                                        (const RPoint_2&)q);
 }
Comparison_result compare_lexicographically_yx (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 192 of file predicates_on_points_2.h.
Referenced by lexicographically_yx_smaller(), and lexicographically_yx_smaller_or_equal().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return  compare_lexicographically_yx((const RPoint_2&)p,
                                        (const RPoint_2&)q);
 }
Comparison_result compare_x (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 102 of file predicates_on_points_2.h.
Referenced by RayS3< FT >::collinear_has_on(), RayS2< FT >::collinear_has_on(), and Compare_x::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return compare_x((const RPoint_2&)p, (const RPoint_2&)q);
 }
Comparison_result compare_y (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 111 of file predicates_on_points_2.h.
Referenced by RayS3< FT >::collinear_has_on(), RayS2< FT >::collinear_has_on(), and Compare_y::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return compare_y((const RPoint_2&)p, (const RPoint_2&)q);
 }
bool leftturn (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r) inline
Definition at line 311 of file predicates_on_points_2.h.
Referenced by Triangulation::in_cone(), p_Left_of_line_2p< Point >::operator()(), p_Left_of_line_2p_safer< Point >::operator()(), p_Leftturn< Point >::operator()(), CGAL::seg_seg_do_intersect_contained(), and CGAL::seg_seg_do_intersect_crossing().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return leftturn((const RPoint_2&)p,
                   (const RPoint_2&)q,
                   (const RPoint_2&)r);
 }
bool lexicographically_xy_larger (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 180 of file predicates_on_points_2.h.
References lexicographically_xy_smaller_or_equal().
Referenced by p_Greater_xy< Point >::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return !lexicographically_xy_smaller_or_equal((const RPoint_2&)p,
                                                 (const RPoint_2&)q);
 }
bool lexicographically_xy_larger_or_equal (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 169 of file predicates_on_points_2.h.
References lexicographically_xy_smaller().
 {
   typedef typename R::Point_2_base  RPoint_2;
  return !lexicographically_xy_smaller((const RPoint_2&)p,
                                       (const RPoint_2&)q);
 }
bool lexicographically_xy_smaller (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 158 of file predicates_on_points_2.h.
Referenced by CGAL::do_intersect(), lexicographically_xy_larger_or_equal(), SegmentS2< FT >::max(), SegmentS2< FT >::min(), p_Less_xy< Point >::operator()(), p_Less_dist_to_line_2p< Point >::operator()(), p_Less_negative_dist_to_line_2p< Point >::operator()(), r_Less_negative_dist_to_line< R >::operator()(), r_Less_dist_to_line< R >::operator()(), r_Less_in_direction< R >::operator()(), Less_xy::operator()(), and PointS2< FT >::operator<().
 {
   typedef typename R::Point_2_base  RPoint_2;
  return lexicographically_xy_smaller((const RPoint_2&)p,
                                      (const RPoint_2&)q);
 }
bool lexicographically_xy_smaller_or_equal (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 147 of file predicates_on_points_2.h.
Referenced by lexicographically_xy_larger().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return lexicographically_xy_smaller_or_equal((const RPoint_2&)p,
                                                (const RPoint_2&)q);
 }
bool lexicographically_yx_larger (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 236 of file predicates_on_points_2.h.
References lexicographically_yx_smaller_or_equal().
Referenced by p_Greater_yx< Point >::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return !lexicographically_yx_smaller_or_equal((const RPoint_2&)p,
                                                 (const RPoint_2&)q);
 }
bool lexicographically_yx_larger_or_equal (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 225 of file predicates_on_points_2.h.
References lexicographically_yx_smaller().
 {
   typedef typename R::Point_2_base  RPoint_2;
  return !lexicographically_yx_smaller((const RPoint_2&)p,
                                       (const RPoint_2&)q);
 }
bool lexicographically_yx_smaller (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 214 of file predicates_on_points_2.h.
Referenced by CGAL::do_intersect(), lexicographically_yx_larger_or_equal(), p_Less_yx< Point >::operator()(), and Less_yx::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
  return lexicographically_yx_smaller((const RPoint_2&)p,
                                      (const RPoint_2&)q);
 }
bool lexicographically_yx_smaller_or_equal (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 203 of file predicates_on_points_2.h.
Referenced by lexicographically_yx_larger().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return lexicographically_yx_smaller_or_equal((const RPoint_2&)p,
                                                (const RPoint_2&)q);
 }
Orientation orientation (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r) inline
Definition at line 348 of file predicates_on_points_2.h.
Referenced by are_negative_oriented(), are_positive_oriented(), collinear(), coplanar(), leftturn(), p_Less_rotate_ccw< Point >::operator()(), p_Less_rotate_ccw_safer< Point >::operator()(), p_Less_rotate_ccw_E< Point >::operator()(), p_Orientation< Point >::operator()(), CGAL::seg_seg_do_intersect_contained(), and CGAL::seg_seg_do_intersect_crossing().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return orientation((const RPoint_2&)p,
                      (const RPoint_2&)q,
                      (const RPoint_2&)r);
 }
bool rightturn (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r) inline
Definition at line 324 of file predicates_on_points_2.h.
Referenced by Triangulation::in_cone(), p_Right_of_line_2p< Point >::operator()(), p_Rightturn< Point >::operator()(), rightturn(), CGAL::seg_seg_do_intersect_contained(), and CGAL::seg_seg_do_intersect_crossing().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return rightturn((const RPoint_2&)p,
                    (const RPoint_2&)q,
                    (const RPoint_2&)r);
 }
bool rightturn (const Origin & o, const Point_2< R > & q, const Point_2< R > & r) inline
Definition at line 337 of file predicates_on_points_2.h.
References rightturn().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return rightturn(o, (const RPoint_2&)q, (const RPoint_2&)r);
 }
Bounded_side side_of_bounded_circle (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r, const Point_2< R > & test) inline
Definition at line 376 of file predicates_on_points_2.h.
Referenced by Side_of_bounded_circle::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return side_of_bounded_circle((const RPoint_2&)p,
                                 (const RPoint_2&)q,
                                 (const RPoint_2&)r,
                                 (const RPoint_2&)test);
 }
Oriented_side side_of_oriented_circle (const Point_2< R > & p, const Point_2< R > & q, const Point_2< R > & r, const Point_2< R > & test) inline
Definition at line 361 of file predicates_on_points_2.h.
Referenced by Side_of_oriented_circle::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return side_of_oriented_circle((const RPoint_2&)p,
                                  (const RPoint_2&)q,
                                  (const RPoint_2&)r,
                                  (const RPoint_2&)test);
 }
CGAL_BEGIN_NAMESPACE bool x_equal (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 83 of file predicates_on_points_2.h.
Referenced by Equal_x::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return x_equal((const RPoint_2&)p, (const RPoint_2&)q);
 }
bool y_equal (const Point_2< R > & p, const Point_2< R > & q) inline
Definition at line 92 of file predicates_on_points_2.h.
Referenced by Equal_y::operator()().
 {
   typedef typename R::Point_2_base  RPoint_2;
   return y_equal((const RPoint_2&)p, (const RPoint_2&)q);
 }