Rocstar: kernel_ftC2.h File Reference
predicates/kernel_ftC2.h File Reference
#include <CGAL/number_utils.h>
#include <CGAL/predicates/sign_of_determinant.h>
#include <CGAL/constructions/kernel_ftC2.h>
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE
CGAL_KERNEL_MEDIUM_INLINE bool equal_lineC2 (const FT &l1a, const FT &l1b, const FT &l1c, const FT &l2a, const FT &l2b, const FT &l2c)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Comparison_result compare_xC2 (const FT &px, const FT &la, const FT &lb, const FT &lc, const FT &ha, const FT &hb, const FT &hc)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Comparison_result compare_xC2 (const FT &la, const FT &lb, const FT &lc, const FT &h1a, const FT &h1b, const FT &h1c, const FT &h2a, const FT &h2b, const FT &h2c)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Comparison_result compare_xC2 (const FT &l1a, const FT &l1b, const FT &l1c, const FT &h1a, const FT &h1b, const FT &h1c, const FT &l2a, const FT &l2b, const FT &l2c, const FT &h2a, const FT &h2b, const FT &h2c)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Comparison_result compare_y_at_xC2 (const FT &px, const FT &py, const FT &la, const FT &lb, const FT &lc)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Comparison_result compare_y_at_xC2 (const FT &px, const FT &l1a, const FT &l1b, const FT &l1c, const FT &l2a, const FT &l2b, const FT &l2c)
template<class FT >
CGAL_KERNEL_LARGE_INLINE
Comparison_result compare_y_at_xC2 (const FT &l1a, const FT &l1b, const FT &l1c, const FT &l2a, const FT &l2b, const FT &l2c, const FT &ha, const FT &hb, const FT &hc)
template<class FT >
CGAL_KERNEL_LARGE_INLINE
Comparison_result compare_y_at_xC2 (const FT &l1a, const FT &l1b, const FT &l1c, const FT &l2a, const FT &l2b, const FT &l2c, const FT &h1a, const FT &h1b, const FT &h1c, const FT &h2a, const FT &h2b, const FT &h2c)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool equal_directionC2 (const FT &dx1, const FT &dy1, const FT &dx2, const FT &dy2)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Comparison_result compare_angle_with_x_axisC2 (const FT &dx1, const FT &dy1, const FT &dx2, const FT &dy2)
template<class FT >
Comparison_result compare_deltax_deltayC2 (const FT &px, const FT &qx, const FT &ry, const FT &sy)
template<class FT >
Comparison_result compare_lexicographically_xyC2 (const FT &px, const FT &py, const FT &qx, const FT &qy)
template<class FT >
Orientation orientationC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool collinear_are_ordered_along_lineC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool collinear_are_strictly_ordered_along_lineC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry)
template<class FT >
CGAL_KERNEL_LARGE_INLINE
Oriented_side side_of_oriented_circleC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry, const FT &tx, const FT &ty)
template<class FT >
CGAL_KERNEL_LARGE_INLINE
Bounded_side side_of_bounded_circleC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry, const FT &tx, const FT &ty)
template<class FT >
Comparison_result cmp_dist_to_pointC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry)
template<class FT >
bool has_larger_dist_to_pointC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry)
template<class FT >
bool has_smaller_dist_to_pointC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry)
template<class FT >
Comparison_result cmp_signed_dist_to_directionC2 (const FT &la, const FT &lb, const FT &px, const FT &py, const FT &qx, const FT &qy)
template<class FT >
bool has_larger_signed_dist_to_directionC2 (const FT &la, const FT &lb, const FT &px, const FT &py, const FT &qx, const FT &qy)
template<class FT >
bool has_smaller_signed_dist_to_directionC2 (const FT &la, const FT &lb, const FT &px, const FT &py, const FT &qx, const FT &qy)
template<class FT >
Comparison_result cmp_signed_dist_to_lineC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry, const FT &sx, const FT &sy)
template<class FT >
bool has_larger_signed_dist_to_lineC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry, const FT &sx, const FT &sy)
template<class FT >
bool has_smaller_signed_dist_to_lineC2 (const FT &px, const FT &py, const FT &qx, const FT &qy, const FT &rx, const FT &ry, const FT &sx, const FT &sy)
template<class FT >
Oriented_side side_of_oriented_lineC2 (const FT &a, const FT &b, const FT &c, const FT &x, const FT &y)
Function Documentation
Comparison_result cmp_dist_to_pointC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry) inline
Definition at line 329 of file predicates/kernel_ftC2.h.
References CGAL_NTS, CGAL::compare(), and squared_distanceC2().
Referenced by has_larger_dist_to_pointC2(), and has_smaller_dist_to_pointC2().
 {
   return CGAL_NTS compare(squared_distanceC2(px,py,qx,qy),
                           squared_distanceC2(px,py,rx,ry));
 }
Comparison_result cmp_signed_dist_to_directionC2 (const FT & la, const FT & lb, const FT & px, const FT & py, const FT & qx, const FT & qy) inline
Definition at line 362 of file predicates/kernel_ftC2.h.
References CGAL_NTS, CGAL::compare(), and scaled_distance_to_directionC2().
Referenced by has_larger_signed_dist_to_directionC2(), and has_smaller_signed_dist_to_directionC2().
 {
   return CGAL_NTS compare(scaled_distance_to_directionC2(la,lb,px,py),
                           scaled_distance_to_directionC2(la,lb,qx,qy));
 }
Comparison_result cmp_signed_dist_to_lineC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry, const FT & sx, const FT & sy) inline
Definition at line 395 of file predicates/kernel_ftC2.h.
References CGAL_NTS, CGAL::compare(), and scaled_distance_to_lineC2().
Referenced by has_larger_signed_dist_to_lineC2(), and has_smaller_signed_dist_to_lineC2().
 {
   return CGAL_NTS compare(scaled_distance_to_lineC2(px,py,qx,qy,rx,ry),
                           scaled_distance_to_lineC2(px,py,qx,qy,sx,sy));
 }
CGAL_KERNEL_MEDIUM_INLINE bool collinear_are_ordered_along_lineC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry)
Definition at line 257 of file predicates/kernel_ftC2.h.
Referenced by collinear_are_ordered_along_line().
 {
   if (px < qx) return !(rx < qx);
   if (qx < px) return !(qx < rx);
   if (py < qy) return !(ry < qy);
   if (qy < py) return !(qy < ry);
   return true; // p==q
 }
CGAL_KERNEL_MEDIUM_INLINE bool collinear_are_strictly_ordered_along_lineC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry)
Definition at line 272 of file predicates/kernel_ftC2.h.
Referenced by collinear_are_strictly_ordered_along_line().
 {
   if (px < qx) return (qx < rx);
   if (qx < px) return (rx < qx);
   if (py < qy) return (qy < ry);
   if (qy < py) return (ry < qy);
   return false;
 }
CGAL_KERNEL_MEDIUM_INLINE Comparison_result compare_angle_with_x_axisC2 (const FT & dx1, const FT & dy1, const FT & dx2, const FT & dy2)
Definition at line 204 of file predicates/kernel_ftC2.h.
References LARGER, sign_of_determinant2x2(), and SMALLER.
 {
   // angles are in [-pi,pi], and the angle between Ox and d1 is compared
   // with the angle between Ox and d2
   int quadrant_1 = (dx1 >= FT(0)) ? ((dy1 >= FT(0))?1:4)
                                   : ((dy1 >= FT(0))?2:3);
   int quadrant_2 = (dx2 >= FT(0)) ? ((dy2 >= FT(0))?1:4)
                                   : ((dy2 >= FT(0))?2:3);
   // We can't use CGAL_NTS compare(quadrant_1,quadrant_2) because in case
   // of tie, we need additional computation
   if (quadrant_1 > quadrant_2)
     return LARGER;
   else if (quadrant_1 < quadrant_2)
     return SMALLER;
   return Comparison_result(-sign_of_determinant2x2(dx1,dy1,dx2,dy2));
 }
Comparison_result compare_deltax_deltayC2 (const FT & px, const FT & qx, const FT & ry, const FT & sy) inline
Definition at line 225 of file predicates/kernel_ftC2.h.
References NTS::abs(), CGAL_NTS, and CGAL::compare().
Referenced by compare_deltax_deltay().
 {
   return CGAL_NTS compare(CGAL_NTS abs(px-qx), CGAL_NTS abs(ry-sy));
 }
Comparison_result compare_lexicographically_xyC2 (const FT & px, const FT & py, const FT & qx, const FT & qy) inline
Definition at line 235 of file predicates/kernel_ftC2.h.
References CGAL_NTS, CGAL::compare(), and EQUAL.
Referenced by compare_lexicographically_xy(), and compare_lexicographically_yx().
 {
   Comparison_result c = CGAL_NTS compare(px,qx);
   return (c != EQUAL) ? c : CGAL_NTS compare(py,qy);
 }
CGAL_KERNEL_MEDIUM_INLINE Comparison_result compare_xC2 (const FT & px, const FT & la, const FT & lb, const FT & lc, const FT & ha, const FT & hb, const FT & hc)
Definition at line 76 of file predicates/kernel_ftC2.h.
References CGAL_kernel_assertion, CGAL_NTS, CGAL::compare(), det2x2_by_formula(), s, sign(), and ZERO.
 {
   // The abscissa of the intersection point is num/den.
   FT num = det2x2_by_formula( lb, lc, hb, hc);
   FT den = det2x2_by_formula( la, lb, ha, hb);
   Sign s = CGAL_NTS sign(den);
   CGAL_kernel_assertion( s != ZERO );
   return Comparison_result( s * CGAL_NTS compare( px * den, num) );
 }
CGAL_KERNEL_MEDIUM_INLINE Comparison_result compare_xC2 (const FT & la, const FT & lb, const FT & lc, const FT & h1a, const FT & h1b, const FT & h1c, const FT & h2a, const FT & h2b, const FT & h2c)
Definition at line 91 of file predicates/kernel_ftC2.h.
References CGAL_NTS, det2x2_by_formula(), and sign().
 {
   /*
   FT num1 = det2x2_by_formula( lb, lc, h1b, h1c);
   FT den1 = det2x2_by_formula( la, lb, h1a, h1b);
   FT num2 = det2x2_by_formula( lb, lc, h2b, h2c);
   FT den2 = det2x2_by_formula( la, lb, h2a, h2b);
   Sign s = Sign (CGAL_NTS sign(den1) * CGAL_NTS sign(den2));
   CGAL_kernel_assertion( s != ZERO );
   return Comparison_result( s * sign_of_determinant2x2(num1,
                                                        num2, den1, den2));
   */
   FT num1 = det2x2_by_formula( la, lc, h1a, h1c);
   FT num2 = det2x2_by_formula( la, lc, h2a, h2c);
   FT num  = det2x2_by_formula(h1a,h1c,h2a,h2c)*lb
             + det2x2_by_formula(num1,num2,h1b,h2b);
   FT den1 = det2x2_by_formula( la, lb, h1a, h1b);
   FT den2 = det2x2_by_formula( la, lb, h2a, h2b);
   return Comparison_result( CGAL_NTS sign(lb) * CGAL_NTS sign(num) *
                             CGAL_NTS sign(den1) * CGAL_NTS sign(den2));
 }
CGAL_KERNEL_MEDIUM_INLINE Comparison_result compare_xC2 (const FT & l1a, const FT & l1b, const FT & l1c, const FT & h1a, const FT & h1b, const FT & h1c, const FT & l2a, const FT & l2b, const FT & l2c, const FT & h2a, const FT & h2b, const FT & h2c)
Definition at line 118 of file predicates/kernel_ftC2.h.
References CGAL_kernel_assertion, CGAL_NTS, det2x2_by_formula(), s, sign(), sign_of_determinant2x2(), and ZERO.
 {
   FT num1 = det2x2_by_formula( l1b, l1c, h1b, h1c);
   FT den1 = det2x2_by_formula( l1a, l1b, h1a, h1b);
   FT num2 = det2x2_by_formula( l2b, l2c, h2b, h2c);
   FT den2 = det2x2_by_formula( l2a, l2b, h2a, h2b);
   Sign s = Sign (CGAL_NTS sign(den1) * CGAL_NTS sign(den2));
   CGAL_kernel_assertion( s != ZERO );
   return Comparison_result( s * sign_of_determinant2x2(num1, num2,
                                                        den1, den2));
 }
CGAL_KERNEL_MEDIUM_INLINE Comparison_result compare_y_at_xC2 (const FT & px, const FT & py, const FT & la, const FT & lb, const FT & lc)
Definition at line 136 of file predicates/kernel_ftC2.h.
References CGAL_kernel_assertion, CGAL_NTS, s, sign(), and ZERO.
 {
   Sign s = CGAL_NTS sign(lb);
   CGAL_kernel_assertion( s != ZERO );
   return Comparison_result (s * CGAL_NTS sign(la*px + lb*py + lc));
 }
CGAL_KERNEL_MEDIUM_INLINE Comparison_result compare_y_at_xC2 (const FT & px, const FT & l1a, const FT & l1b, const FT & l1c, const FT & l2a, const FT & l2b, const FT & l2c)
Definition at line 147 of file predicates/kernel_ftC2.h.
References CGAL_kernel_assertion, CGAL_NTS, s, sign(), sign_of_determinant2x2(), and ZERO.
 {
   Sign s = Sign (CGAL_NTS sign(l1b) * CGAL_NTS sign(l2b));
   CGAL_kernel_assertion( s != ZERO );
   return Comparison_result ( s * sign_of_determinant2x2(l2a*px+l2c, l2b,
                                                         l1a*px+l1c, l1b));
 }
CGAL_KERNEL_LARGE_INLINE Comparison_result compare_y_at_xC2 (const FT & l1a, const FT & l1b, const FT & l1c, const FT & l2a, const FT & l2b, const FT & l2c, const FT & ha, const FT & hb, const FT & hc)
Definition at line 160 of file predicates/kernel_ftC2.h.
References CGAL_kernel_assertion, CGAL_NTS, s, sign(), sign_of_determinant2x2(), sign_of_determinant3x3(), and ZERO.
 {
   Sign s = Sign (sign_of_determinant2x2(l1a, l1b, l2a, l2b) *
                  CGAL_NTS sign(hb));
   CGAL_kernel_assertion( s != ZERO );
   return Comparison_result( s * sign_of_determinant3x3(l1a, l1b, l1c,
                                                        l2a, l2b, l2c,
                                                        ha,  hb,  hc));
 }
CGAL_KERNEL_LARGE_INLINE Comparison_result compare_y_at_xC2 (const FT & l1a, const FT & l1b, const FT & l1c, const FT & l2a, const FT & l2b, const FT & l2c, const FT & h1a, const FT & h1b, const FT & h1c, const FT & h2a, const FT & h2b, const FT & h2c)
Definition at line 175 of file predicates/kernel_ftC2.h.
References CGAL_kernel_assertion, CGAL_NTS, det2x2_by_formula(), s, sign(), sign_of_determinant2x2(), and ZERO.
 {
   // The abscissa of the intersection point is num/den.
   FT num = det2x2_by_formula( l1b, l1c, l2b, l2c);
   FT den = det2x2_by_formula( l1a, l1b, l2a, l2b);
   Sign s = Sign (CGAL_NTS sign(h1b) * CGAL_NTS sign(h2b) * CGAL_NTS sign(den));
   CGAL_kernel_assertion( s != ZERO );
   return Comparison_result ( s * sign_of_determinant2x2(h2a*num+h2c*den, h2b,
                                                         h1a*num+h1c*den, h1b));
 }
CGAL_KERNEL_MEDIUM_INLINE bool equal_directionC2 (const FT & dx1, const FT & dy1, const FT & dx2, const FT & dy2)
Definition at line 192 of file predicates/kernel_ftC2.h.
References CGAL_NTS, sign(), sign_of_determinant2x2(), and ZERO.
 {
   return CGAL_NTS sign(dx1) == CGAL_NTS sign(dx2)
       && CGAL_NTS sign(dy1) == CGAL_NTS sign(dy2)
       && sign_of_determinant2x2(dx1, dy1, dx2, dy2) == ZERO;
 }
CGAL_BEGIN_NAMESPACE CGAL_KERNEL_MEDIUM_INLINE bool equal_lineC2 (const FT & l1a, const FT & l1b, const FT & l1c, const FT & l2a, const FT & l2b, const FT & l2c)
Definition at line 60 of file predicates/kernel_ftC2.h.
References CGAL_NTS, sign(), sign_of_determinant2x2(), and ZERO.
 {
     if (sign_of_determinant2x2(l1a, l1b, l2a, l2b) != ZERO)
         return false; // Not parallel.
     CGAL::Sign s1a = CGAL_NTS sign(l1a);
     if (s1a != ZERO)
         return s1a == CGAL_NTS sign(l2a)
             && sign_of_determinant2x2(l1a, l1c, l2a, l2c) == ZERO;
     return CGAL_NTS sign(l1b) == CGAL_NTS sign(l2b)
         && sign_of_determinant2x2(l1b, l1c, l2b, l2c) == ZERO;
 }
bool has_larger_dist_to_pointC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry) inline
Definition at line 341 of file predicates/kernel_ftC2.h.
References cmp_dist_to_pointC2(), and LARGER.
 {
   return cmp_dist_to_pointC2(px,py,qx,qy,rx,ry) == LARGER;
 }
bool has_larger_signed_dist_to_directionC2 (const FT & la, const FT & lb, const FT & px, const FT & py, const FT & qx, const FT & qy) inline
Definition at line 374 of file predicates/kernel_ftC2.h.
References cmp_signed_dist_to_directionC2(), and LARGER.
 {
   return cmp_signed_dist_to_directionC2(la,lb,px,py,qx,qy) == LARGER;
 }
bool has_larger_signed_dist_to_lineC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry, const FT & sx, const FT & sy) inline
Definition at line 408 of file predicates/kernel_ftC2.h.
References cmp_signed_dist_to_lineC2(), and LARGER.
 {
   return cmp_signed_dist_to_lineC2(px,py,qx,qy,rx,ry,sx,sy) == LARGER;
 }
bool has_smaller_dist_to_pointC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry) inline
Definition at line 352 of file predicates/kernel_ftC2.h.
References cmp_dist_to_pointC2(), and SMALLER.
 {
   return cmp_dist_to_pointC2(px,py,qx,qy,rx,ry) == SMALLER;
 }
bool has_smaller_signed_dist_to_directionC2 (const FT & la, const FT & lb, const FT & px, const FT & py, const FT & qx, const FT & qy) inline
Definition at line 385 of file predicates/kernel_ftC2.h.
References cmp_signed_dist_to_directionC2(), and SMALLER.
 {
   return cmp_signed_dist_to_directionC2(la,lb,px,py,qx,qy) == SMALLER;
 }
bool has_smaller_signed_dist_to_lineC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry, const FT & sx, const FT & sy) inline
Definition at line 420 of file predicates/kernel_ftC2.h.
References cmp_signed_dist_to_lineC2(), and SMALLER.
 {
   return cmp_signed_dist_to_lineC2(px,py,qx,qy,rx,ry,sx,sy) == SMALLER;
 }
Orientation orientationC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry) inline
Definition at line 245 of file predicates/kernel_ftC2.h.
References sign_of_determinant2x2().
Referenced by coplanar_orientationC3(), leftturn(), orientation(), rightturn(), and side_of_bounded_circleC2().
 {
   return Orientation (sign_of_determinant2x2(px-rx, py-ry,
                                              qx-rx, qy-ry));
 }
CGAL_KERNEL_LARGE_INLINE Bounded_side side_of_bounded_circleC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry, const FT & tx, const FT & ty)
Definition at line 315 of file predicates/kernel_ftC2.h.
References orientationC2(), and side_of_oriented_circleC2().
Referenced by side_of_bounded_circle().
 {
   // Note: if the code of these is inlined, and if they are implemented
   // in a good way, some CSE can be done by the compiler.
   return Bounded_side( side_of_oriented_circleC2(px,py,qx,qy,rx,ry,tx,ty)
                                  * orientationC2(px,py,qx,qy,rx,ry) );
 }
CGAL_KERNEL_LARGE_INLINE Oriented_side side_of_oriented_circleC2 (const FT & px, const FT & py, const FT & qx, const FT & qy, const FT & rx, const FT & ry, const FT & tx, const FT & ty)
Definition at line 286 of file predicates/kernel_ftC2.h.
References sign_of_determinant2x2().
Referenced by side_of_bounded_circleC2(), and side_of_oriented_circle().
 {
   // Oriented_side(
   //  sign_of_determinant4x4(px, py, px*px + py*py, 1,
   //                         qx, qy, qx*qx + qy*qy, 1,
   //                         rx, ry, rx*rx + ry*ry, 1,
   //                         tx, ty, tx*tx + ty*ty, 1));
   // We first translate so that t is the new origin.
   FT ptx = px-tx;
   FT pty = py-ty;
   FT qtx = qx-tx;
   FT qty = qy-ty;
   FT rtx = rx-tx;
   FT rty = ry-ty;
 // The usual 3x3 formula can be simplified a little bit to a 2x2.
 //           sign_of_determinant3x3(ptx, pty, square(ptx) + square(pty),
 //                                  qtx, qty, square(qtx) + square(qty),
 //                                  rtx, rty, square(rtx) + square(rty)));
   return Oriented_side( sign_of_determinant2x2(
                              ptx*qty - pty*qtx, qtx*(qx-px) + qty*(qy-py),
                              ptx*rty - pty*rtx, rtx*(rx-px) + rty*(ry-py)));
 }
Oriented_side side_of_oriented_lineC2 (const FT & a, const FT & b, const FT & c, const FT & x, const FT & y) inline
Definition at line 431 of file predicates/kernel_ftC2.h.
References CGAL_NTS, and sign().
 {
   return Oriented_side(CGAL_NTS sign(a*x+b*y+c));
 }