Rocstar: kernel_ftC3.h File Reference
predicates/kernel_ftC3.h File Reference
#include <CGAL/predicates/sign_of_determinant.h>
#include <CGAL/predicates/kernel_ftC2.h>
#include <CGAL/constructions/kernel_ftC3.h>
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE
CGAL_KERNEL_MEDIUM_INLINE
Comparison_result compare_lexicographically_xyzC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool strict_dominanceC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool dominanceC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool collinearC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Orientation orientationC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz, const FT &sx, const FT &sy, const FT &sz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Orientation coplanar_orientationC3 (const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz, const FT &sx, const FT &sy, const FT &sz, const FT &px, const FT &py, const FT &pz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool collinear_are_ordered_along_lineC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool collinear_are_strictly_ordered_along_lineC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool equal_directionC3 (const FT &dx1, const FT &dy1, const FT &dz1, const FT &dx2, const FT &dy2, const FT &dz2)
template<class FT >
CGAL_KERNEL_LARGE_INLINE
Oriented_side side_of_oriented_planeC3 (const FT &a, const FT &b, const FT &c, const FT &d, const FT &px, const FT &py, const FT &pz)
template<class FT >
CGAL_KERNEL_LARGE_INLINE
Oriented_side side_of_oriented_sphereC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz, const FT &sx, const FT &sy, const FT &sz, const FT &tx, const FT &ty, const FT &tz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Bounded_side side_of_bounded_sphereC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz, const FT &sx, const FT &sy, const FT &sz, const FT &tx, const FT &ty, const FT &tz)
template<class FT >
CGAL_KERNEL_INLINE
Comparison_result cmp_dist_to_pointC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool has_larger_dist_to_pointC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool has_smaller_dist_to_pointC3 (const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz, const FT &rx, const FT &ry, const FT &rz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Comparison_result cmp_signed_dist_to_directionC3 (const FT &pa, const FT &pb, const FT &pc, const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool has_larger_signed_dist_to_directionC3 (const FT &pa, const FT &pb, const FT &pc, const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool has_smaller_signed_dist_to_directionC3 (const FT &pa, const FT &pb, const FT &pc, const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE
Comparison_result cmp_signed_dist_to_planeC3 (const FT &ppx, const FT &ppy, const FT &ppz, const FT &pqx, const FT &pqy, const FT &pqz, const FT &prx, const FT &pry, const FT &prz, const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool has_larger_signed_dist_to_planeC3 (const FT &ppx, const FT &ppy, const FT &ppz, const FT &pqx, const FT &pqy, const FT &pqz, const FT &prx, const FT &pry, const FT &prz, const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
template<class FT >
CGAL_KERNEL_MEDIUM_INLINE bool has_smaller_signed_dist_to_planeC3 (const FT &ppx, const FT &ppy, const FT &ppz, const FT &pqx, const FT &pqy, const FT &pqz, const FT &prx, const FT &pry, const FT &prz, const FT &px, const FT &py, const FT &pz, const FT &qx, const FT &qy, const FT &qz)
Function Documentation
CGAL_KERNEL_INLINE Comparison_result cmp_dist_to_pointC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz)
Definition at line 259 of file predicates/kernel_ftC3.h.
References CGAL_NTS, CGAL::compare(), and squared_distanceC3().
Referenced by cmp_dist_to_point(), has_larger_dist_to_pointC3(), and has_smaller_dist_to_pointC3().
 {
   return CGAL_NTS compare(squared_distanceC3(px,py,pz,qx,qy,qz),
                           squared_distanceC3(px,py,pz,rx,ry,rz));
 }
CGAL_KERNEL_MEDIUM_INLINE Comparison_result cmp_signed_dist_to_directionC3 (const FT & pa, const FT & pb, const FT & pc, const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 292 of file predicates/kernel_ftC3.h.
References CGAL_NTS, CGAL::compare(), and scaled_distance_to_directionC3().
Referenced by cmp_signed_dist_to_plane(), has_larger_signed_dist_to_directionC3(), and has_smaller_signed_dist_to_directionC3().
 {
   return CGAL_NTS compare(scaled_distance_to_directionC3(pa,pb,pc,px,py,pz),
                           scaled_distance_to_directionC3(pa,pb,pc,qx,qy,qz));
 }
CGAL_KERNEL_MEDIUM_INLINE Comparison_result cmp_signed_dist_to_planeC3 (const FT & ppx, const FT & ppy, const FT & ppz, const FT & pqx, const FT & pqy, const FT & pqz, const FT & prx, const FT & pry, const FT & prz, const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 328 of file predicates/kernel_ftC3.h.
References sign_of_determinant3x3().
Referenced by cmp_signed_dist_to_plane(), has_larger_signed_dist_to_planeC3(), and has_smaller_signed_dist_to_planeC3().
 {
   return Comparison_result(sign_of_determinant3x3(
               pqx-ppx, pqy-ppy, pqz-ppz,
               prx-ppx, pry-ppy, prz-ppz,
               qx-px,   qy-py,   qz-pz));
 }
CGAL_KERNEL_MEDIUM_INLINE bool collinear_are_ordered_along_lineC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz)
Definition at line 149 of file predicates/kernel_ftC3.h.
Referenced by collinear_are_ordered_along_line().
 {
   if (px < qx) return !(rx < qx);
   if (qx < px) return !(qx < rx);
   if (py < qy) return !(ry < qy);
   if (qy < py) return !(qy < ry);
   if (pz < qz) return !(rz < qz);
   if (qz < pz) return !(qz < rz);
   return true; // p==q
 }
CGAL_KERNEL_MEDIUM_INLINE bool collinear_are_strictly_ordered_along_lineC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz)
Definition at line 167 of file predicates/kernel_ftC3.h.
Referenced by collinear_are_strictly_ordered_along_line().
 {
   if (px < qx) return (qx < rx);
   if (qx < px) return (rx < qx);
   if (py < qy) return (qy < ry);
   if (qy < py) return (ry < qy);
   if (pz < qz) return (qz < rz);
   if (qz < pz) return (rz < qz);
   return false; // p==q
 }
CGAL_KERNEL_MEDIUM_INLINE bool collinearC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz)
Definition at line 96 of file predicates/kernel_ftC3.h.
References sign_of_determinant2x2(), and ZERO.
Referenced by collinear().
 {
   FT dpx = px-rx;
   FT dqx = qx-rx;
   FT dpy = py-ry;
   FT dqy = qy-ry;
   if (sign_of_determinant2x2(dpx, dqx, dpy, dqy) != ZERO)
       return false;
   FT dpz = pz-rz;
   FT dqz = qz-rz;
   return sign_of_determinant2x2(dpx, dqx, dpz, dqz) == ZERO
       && sign_of_determinant2x2(dpy, dqy, dpz, dqz) == ZERO;
 }
CGAL_BEGIN_NAMESPACE CGAL_KERNEL_MEDIUM_INLINE Comparison_result compare_lexicographically_xyzC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 61 of file predicates/kernel_ftC3.h.
References CGAL_NTS, CGAL::compare(), and EQUAL.
Referenced by compare_lexicographically_xyz().
 {
   Comparison_result c = CGAL_NTS compare(px, qx);
   if (c != EQUAL) return c;
   c = CGAL_NTS compare(py, qy);
   if (c != EQUAL) return c;
   return CGAL_NTS compare(pz, qz);
 }
CGAL_KERNEL_MEDIUM_INLINE Orientation coplanar_orientationC3 (const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz, const FT & sx, const FT & sy, const FT & sz, const FT & px, const FT & py, const FT & pz)
Definition at line 129 of file predicates/kernel_ftC3.h.
References COLLINEAR, and orientationC2().
Referenced by coplanar_orientation().
 {
   Orientation oxy_qrs = orientationC2(qx,qy,rx,ry,sx,sy);
   if (oxy_qrs != COLLINEAR)
       return Orientation( oxy_qrs * orientationC2(qx,qy,rx,ry,px,py));
   Orientation oyz_qrs = orientationC2(qy,qz,ry,rz,sy,sz);
   if (oyz_qrs != COLLINEAR)
       return Orientation( oyz_qrs * orientationC2(qy,qz,ry,rz,py,pz));
   Orientation oxz_qrs = orientationC2(qx,qz,rx,rz,sx,sz);
   assert(oxz_qrs != COLLINEAR);
   return Orientation( oxz_qrs * orientationC2(qx,qz,rx,rz,px,pz));
 }
CGAL_KERNEL_MEDIUM_INLINE bool dominanceC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 85 of file predicates/kernel_ftC3.h.
References CGAL_NTS, CGAL::compare(), and SMALLER.
 {
   return CGAL_NTS compare(px, qx) != SMALLER &&
          CGAL_NTS compare(py, qy) != SMALLER &&
          CGAL_NTS compare(pz, qz) != SMALLER;
 }
CGAL_KERNEL_MEDIUM_INLINE bool equal_directionC3 (const FT & dx1, const FT & dy1, const FT & dz1, const FT & dx2, const FT & dy2, const FT & dz2)
Definition at line 184 of file predicates/kernel_ftC3.h.
References CGAL_NTS, sign(), sign_of_determinant2x2(), and ZERO.
 {
   return sign_of_determinant2x2(dx1, dy1, dx2, dy2) == ZERO
       && sign_of_determinant2x2(dx1, dz1, dx2, dz2) == ZERO
       && sign_of_determinant2x2(dy1, dz1, dy2, dz2) == ZERO
       && CGAL_NTS sign(dx1) == CGAL_NTS sign(dx2)
       && CGAL_NTS sign(dy1) == CGAL_NTS sign(dy2)
       && CGAL_NTS sign(dz1) == CGAL_NTS sign(dz2);
 }
CGAL_KERNEL_MEDIUM_INLINE bool has_larger_dist_to_pointC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz)
Definition at line 271 of file predicates/kernel_ftC3.h.
References cmp_dist_to_pointC3(), and LARGER.
Referenced by has_larger_dist_to_point().
 {
   return cmp_dist_to_pointC3(px,py,pz,qx,qy,qz,rx,ry,rz) == LARGER;
 }
CGAL_KERNEL_MEDIUM_INLINE bool has_larger_signed_dist_to_directionC3 (const FT & pa, const FT & pb, const FT & pc, const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 305 of file predicates/kernel_ftC3.h.
References cmp_signed_dist_to_directionC3(), and LARGER.
Referenced by has_larger_signed_dist_to_plane().
 {
   return cmp_signed_dist_to_directionC3(pa,pb,pc,px,py,pz,qx,qy,qz) == LARGER;
 }
CGAL_KERNEL_MEDIUM_INLINE bool has_larger_signed_dist_to_planeC3 (const FT & ppx, const FT & ppy, const FT & ppz, const FT & pqx, const FT & pqy, const FT & pqz, const FT & prx, const FT & pry, const FT & prz, const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 345 of file predicates/kernel_ftC3.h.
References cmp_signed_dist_to_planeC3(), and LARGER.
Referenced by has_larger_signed_dist_to_plane().
 {
     return cmp_signed_dist_to_planeC3(ppx, ppy, ppz, pqx, pqy, pqz,
             prx, pry, prz, px, py, pz, qx, qy, qz) == LARGER;
 }
CGAL_KERNEL_MEDIUM_INLINE bool has_smaller_dist_to_pointC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz)
Definition at line 282 of file predicates/kernel_ftC3.h.
References cmp_dist_to_pointC3(), and SMALLER.
Referenced by has_smaller_dist_to_point().
 {
   return cmp_dist_to_pointC3(px,py,pz,qx,qy,qz,rx,ry,rz) == SMALLER;
 }
CGAL_KERNEL_MEDIUM_INLINE bool has_smaller_signed_dist_to_directionC3 (const FT & pa, const FT & pb, const FT & pc, const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 317 of file predicates/kernel_ftC3.h.
References cmp_signed_dist_to_directionC3(), and SMALLER.
Referenced by has_smaller_signed_dist_to_plane().
 {
   return cmp_signed_dist_to_directionC3(pa,pb,pc,px,py,pz,qx,qy,qz) == SMALLER;
 }
CGAL_KERNEL_MEDIUM_INLINE bool has_smaller_signed_dist_to_planeC3 (const FT & ppx, const FT & ppy, const FT & ppz, const FT & pqx, const FT & pqy, const FT & pqz, const FT & prx, const FT & pry, const FT & prz, const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 360 of file predicates/kernel_ftC3.h.
References cmp_signed_dist_to_planeC3(), and SMALLER.
Referenced by has_smaller_signed_dist_to_plane().
 {
     return cmp_signed_dist_to_planeC3(ppx, ppy, ppz, pqx, pqy, pqz,
             prx, pry, prz, px, py, pz, qx, qy, qz) == SMALLER;
 }
CGAL_KERNEL_MEDIUM_INLINE Orientation orientationC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz, const FT & sx, const FT & sy, const FT & sz)
Definition at line 115 of file predicates/kernel_ftC3.h.
References sign_of_determinant3x3().
Referenced by orientation(), and side_of_bounded_sphereC3().
 {
   return Orientation(sign_of_determinant3x3(qx-px,rx-px,sx-px,
                                             qy-py,ry-py,sy-py,
                                             qz-pz,rz-pz,sz-pz));
 }
CGAL_KERNEL_MEDIUM_INLINE Bounded_side side_of_bounded_sphereC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz, const FT & sx, const FT & sy, const FT & sz, const FT & tx, const FT & ty, const FT & tz)
Definition at line 238 of file predicates/kernel_ftC3.h.
References orientationC3(), s, and side_of_oriented_sphereC3().
Referenced by side_of_bounded_sphere().
 {
   Oriented_side s = side_of_oriented_sphereC3(px, py, pz,
                                               qx, qy, qz,
                                               rx, ry, rz,
                                               sx, sy, sz,
                                               tx, ty, tz);
   Orientation o = orientationC3(px, py, pz,
                                 qx, qy, qz,
                                 rx, ry, rz,
                                 sx, sy, sz);
   return Bounded_side(s * o);
 }
CGAL_KERNEL_LARGE_INLINE Oriented_side side_of_oriented_planeC3 (const FT & a, const FT & b, const FT & c, const FT & d, const FT & px, const FT & py, const FT & pz)
Definition at line 198 of file predicates/kernel_ftC3.h.
References CGAL_NTS, and sign().
 {
   return Oriented_side(CGAL_NTS sign(a*px + b*py + c*pz +d));
 }
CGAL_KERNEL_LARGE_INLINE Oriented_side side_of_oriented_sphereC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz, const FT & rx, const FT & ry, const FT & rz, const FT & sx, const FT & sy, const FT & sz, const FT & tx, const FT & ty, const FT & tz)
Definition at line 207 of file predicates/kernel_ftC3.h.
References CGAL_NTS, sign_of_determinant4x4(), and square().
Referenced by side_of_bounded_sphereC3(), and side_of_oriented_sphere().
 {
   FT ptx = px - tx;
   FT pty = py - ty;
   FT ptz = pz - tz;
   FT pt2 = CGAL_NTS square(ptx) + CGAL_NTS square(pty) + CGAL_NTS square(ptz);
   FT qtx = qx - tx;
   FT qty = qy - ty;
   FT qtz = qz - tz;
   FT qt2 = CGAL_NTS square(qtx) + CGAL_NTS square(qty) + CGAL_NTS square(qtz);
   FT rtx = rx - tx;
   FT rty = ry - ty;
   FT rtz = rz - tz;
   FT rt2 = CGAL_NTS square(rtx) + CGAL_NTS square(rty) + CGAL_NTS square(rtz);
   FT stx = sx - tx;
   FT sty = sy - ty;
   FT stz = sz - tz;
   FT st2 = CGAL_NTS square(stx) + CGAL_NTS square(sty) + CGAL_NTS square(stz);
   return Oriented_side(sign_of_determinant4x4(ptx,pty,ptz,pt2,
                                               rtx,rty,rtz,rt2,
                                               qtx,qty,qtz,qt2,
                                               stx,sty,stz,st2));
 }
CGAL_KERNEL_MEDIUM_INLINE bool strict_dominanceC3 (const FT & px, const FT & py, const FT & pz, const FT & qx, const FT & qy, const FT & qz)
Definition at line 74 of file predicates/kernel_ftC3.h.
References CGAL_NTS, CGAL::compare(), and LARGER.
 {
   return CGAL_NTS compare(px, qx) == LARGER &&
          CGAL_NTS compare(py, qy) == LARGER &&
          CGAL_NTS compare(pz, qz) == LARGER;
 }