Rocstar: PREP_GetGrid.F90 File Reference
PREP_GetGrid.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine getgrid (gridLevel, iReg, regions)
Function/Subroutine Documentation
subroutine getgrid (integer gridLevel, integer iReg, type(t_region), dimension(:), pointer regions)
Definition at line 45 of file PREP_GetGrid.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idnbeg, idnend, iend, j, jbeg, jdnbeg, jdnend, jend, k, kbeg, kdnbeg, moderror::registerfunction(), rflo_copygeometrydummy(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and rflo_readgridregion().
Referenced by rocflo_init().