Rocstar: PREP_Main.F90 File Reference
PREP_Main.F90 File Reference
Functions/Subroutines
program rocflo_init
Function/Subroutine Documentation
program rocflo_init ()
Definition at line 44 of file PREP_Main.F90.
References Line_2< R, T >::a(), prep_modbcdistribution::bcdistributionfiles(), buildversionstring(), checkbcvalidity(), moderror::deregisterfunction(), moderror::errorstop(), genxinitsolution(), genxwritesolution(), getgrid(), initializeflowfield(), initinputvalues(), COM_exception::msg(), printprepinput(), readbcinputfile(), readinputfile(), moderror::registerfunction(), rflo_readregiontopology(), rflo_writesolutionregion(), and StopWatch::stop().