Rocstar: PREP_GenxWriteSolution.F90 File Reference
PREP_GenxWriteSolution.F90 File Reference
Functions/Subroutines
subroutine genxwritesolution (gridLevel, iReg, region, wins, winv)
Function/Subroutine Documentation
subroutine genxwritesolution (integer gridLevel, integer iReg, type(t_region) region, character(chrlen) wins, character(chrlen) winv)
Definition at line 48 of file PREP_GenxWriteSolution.F90.
References moderror::deregisterfunction(), moderror::errorstop(), genxwriterocinout(), moderror::registerfunction(), Rocout::set_option(), and write_attr().
Referenced by rocflo_init().