Rocstar: PREP_InitGenxInterface.F90 File Reference
PREP_InitGenxInterface.F90 File Reference
Functions/Subroutines
subroutine rflo_initgenxinterfaceprep (iReg, region, wins, winv)
Function/Subroutine Documentation
subroutine rflo_initgenxinterfaceprep (integer iReg, type(t_region) region, character(chrlen) wins, character(chrlen) winv)
Definition at line 45 of file PREP_InitGenxInterface.F90.
References moderror::deregisterfunction(), moderror::errorstop(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, moderror::registerfunction(), and rflo_getdimensdummynodes().
Referenced by genxinitsolution().