Rocstar: principal_stress.f90 File Reference
principal_stress.f90 File Reference
Functions/Subroutines
subroutine principal_stress (s11, s22, s33, s12, s23, s13, istrgss, NumElVol, SVonMises)
Function/Subroutine Documentation
subroutine principal_stress (real*8, dimension(1:istrgss,1:numelvol) s11, real*8, dimension(1:istrgss,1:numelvol) s22, real*8, dimension(1:istrgss,1:numelvol) s33, real*8, dimension(1:istrgss,1:numelvol) s12, real*8, dimension(1:istrgss,1:numelvol) s23, real*8, dimension(1:istrgss,1:numelvol) s13, integer istrgss, integer NumElVol, real*8, dimension(1:numelvol) SVonMises)
Definition at line 53 of file principal_stress.f90.
References Line_2< R, T >::a(), i, j, Color::r(), s, sqrt(), x, y, and z.
Referenced by rocfracmain::rocfracsoln().