Rocstar: RADI_floFlimCentFluxPatch.F90 File Reference
RADI_floFlimCentFluxPatch.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine radi_floflimcentfluxpatch (region, patch)
Function/Subroutine Documentation
subroutine radi_floflimcentfluxpatch (type(t_region) region, type(t_patch) patch)
Definition at line 45 of file RADI_floFlimCentFluxPatch.F90.
References bcondinjectionperf(), moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by radi_floflimcentflux().