Rocstar: RADI_floFlimCorrCornEdgeCells.F90 File Reference
RADI_floFlimCorrCornEdgeCells.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine radi_floflimcorrcornedgecells (region, patch, radBcType)
Function/Subroutine Documentation
subroutine radi_floflimcorrcornedgecells (type(t_region) region, type(t_patch) patch, integer radBcType)
Definition at line 46 of file RADI_floFlimCorrCornEdgeCells.F90.
References moderror::deregisterfunction(), i, ibeg, idcbeg, idcend, idir, iend, ipcbeg, ipcend, j, jbeg, jdcbeg, jdcend, jdir, jend, jpcbeg, jpcend, k, kbeg, kdcbeg, kdir, kpcbeg, max(), min(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensphys(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by radi_rflo_flimbndconditionsrecv().