Rocstar: RADI_floFlimBcondSymmetry.F90 File Reference
RADI_floFlimBcondSymmetry.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine radi_floflimbcondsymmetry (region, patch)
Function/Subroutine Documentation
subroutine radi_floflimbcondsymmetry (type(t_region) region, type(t_patch) patch)
Definition at line 46 of file RADI_floFlimBcondSymmetry.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by radi_rflo_flimbndconditionsset().