Rocstar: RADI_FlimDiffFlux.F90 File Reference
RADI_FlimDiffFlux.F90 File Reference
Functions/Subroutines
subroutine radi_flimdiffflux (region)
subroutine computeflux (ijk)
Function/Subroutine Documentation
subroutine radi_flimdiffflux::computeflux (integer ijk)
Definition at line 174 of file RADI_FlimDiffFlux.F90.
References i, ibeg, iend, ipcbeg, ipcend, j, jbeg, jend, jpcbeg, jpcend, k, kbeg, kpcbeg, and sqrt().
subroutine radi_flimdiffflux (region)
Definition at line 44 of file RADI_FlimDiffFlux.F90.
References computeflux(), moderror::deregisterfunction(), ipcbeg, ipcend, jpcbeg, jpcend, kpcbeg, radi_flimdifffluxpatch(), moderror::registerfunction(), rflo_calcgradvector(), rflo_getcelloffset(), rflo_getdimensphys(), and rflo_getnodeoffset().