Rocstar: RADI_floFlimSetCornEdgeCells.F90 File Reference
RADI_floFlimSetCornEdgeCells.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine radi_floflimsetcornedgecells (region)
subroutine averageedgecells (ijkD, ijkC1, ijkC2, nCv, tcv)
Function/Subroutine Documentation
subroutine radi_floflimsetcornedgecells::averageedgecells (integer ijkD, integer ijkC1, integer ijkC2, integer nCv, real(rfreal), dimension(:,:), pointer tcv)
Definition at line 201 of file RADI_floFlimSetCornEdgeCells.F90.
Referenced by radi_floflimsetcornedgecells(), and turb_floranssetcornedgecells().
subroutine radi_floflimsetcornedgecells (type(t_region) region)
Definition at line 46 of file RADI_floFlimSetCornEdgeCells.F90.
References averageedgecells(), moderror::deregisterfunction(), i, idcbeg, idcend, ipcbeg, ipcend, j, jdcbeg, jdcend, jpcbeg, jpcend, k, kdcbeg, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), and rflo_getdimensphys().
Referenced by radi_rflo_flimbndconditionsrecv().