Rocstar: RADI_rFLO_FlimBndConditionsSet.F90 File Reference
RADI_rFLO_FlimBndConditionsSet.F90 File Reference
Functions/Subroutines
subroutine radi_rflo_flimbndconditionsset (regions, iReg)
Function/Subroutine Documentation
subroutine radi_rflo_flimbndconditionsset (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 46 of file RADI_rFLO_FlimBndConditionsSet.F90.
References moderror::deregisterfunction(), moderror::errorstop(), radi_floflimbconddiffuse(), radi_floflimbcondinjection(), radi_floflimbcondsymmetry(), radi_floflimbcondzerograd(), radi_floflimexchangedummyconf(), and moderror::registerfunction().