Rocstar: RADI_rFLO_FlimSpectralRadii.F90 File Reference
RADI_rFLO_FlimSpectralRadii.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine radi_rflo_flimspectralradii (region)
Function/Subroutine Documentation
subroutine radi_rflo_flimspectralradii (type(t_region), intent(inout) region)
Definition at line 43 of file RADI_rFLO_FlimSpectralRadii.F90.
References moderror::deregisterfunction(), i, idcbeg, idcend, j, jdcbeg, jdcend, k, kdcbeg, moderror::registerfunction(), rflo_copymatrixcorners(), rflo_copymatrixedges(), rflo_copymatrixpatches(), rflo_copyvectorcorners(), rflo_copyvectoredges(), rflo_copyvectorpatches(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensphys(), rflo_getnodeoffset(), and v.