Rocstar: RandInitGenxInterface.F90 File Reference
RandInitGenxInterface.F90 File Reference
Functions/Subroutines
subroutine randinitgenxinterface (regions, wins, winv)
Function/Subroutine Documentation
subroutine randinitgenxinterface (type(t_region), dimension(:), pointer regions, character(chrlen) wins, character(chrlen) winv)
Definition at line 43 of file RandInitGenxInterface.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflo_initgenxinterface().