Rocstar: read_parameter_file.C File Reference
read_parameter_file.C File Reference
#include <iostream>
#include <fstream>
#include <iomanip>
#include <cstdlib>
#include "roccom_c++.h"
#include "Rocin.h"
Functions
void eat_whitespace_until (std::string &str, const char &c, int start=0)
void get_parameter_list (std::vector< std::pair< std::string, std::string > > &param_list, const char *file_name)
Function Documentation
void eat_whitespace_until (std::string & str, const char & c, int start = 0)
Definition at line 149 of file read_parameter_file.C.
References i, and ni.
Referenced by get_parameter_list().
{
   for(int i=start, ni=str.size(); i<ni&&str[i]!=c; ++i){
     if(str[i] == ' ' || str[i] == '\t'){
       str.erase(i,1);
       --i;
     }
   }
 }
void get_parameter_list (std::vector< std::pair< std::string, std::string > > & param_list, const char * file_name)
Definition at line 158 of file read_parameter_file.C.
References COM_assertion_msg, eat_whitespace_until(), and cimg_library::cimg::option().
Referenced by Rocin::read_parameter_file().
{
   //open parameter file for input
   std::ifstream param_file(file_name);
   COM_assertion_msg(param_file,
                     "Specified parameter file not found.");
   string cur_line, option, value;
   string::size_type cur_pos;
   // get one line of the file at a time
   while (getline(param_file,cur_line)){
     cur_pos = cur_line.find('#');
     if(cur_pos != string::npos)
       cur_line.erase(cur_pos, cur_line.size()-cur_pos);
     // remove whitespace up to first '='
     eat_whitespace_until(cur_line, (char)61);
     // If the line only contained whitespace and comments,
     // go to the next line.
     if(cur_line.size()==0)
       continue;
     // Now find the first '='
     cur_pos = cur_line.find_first_of("=");
     COM_assertion_msg(cur_pos != string::npos  && cur_pos !=0,
                       (std::string("Parameter file '")
                        + file_name + "' has an invalid line.").c_str());
     option.assign(cur_line,0,cur_pos);
     value.assign(cur_line,cur_pos+1,string::npos);
     //eat all whitspace in the value up to the first '"'
     eat_whitespace_until(value, '"');
     //if the value has quotes, then make sure they are only at
     //beginning and ending of the string
     cur_pos = value.find('"');
     if(cur_pos != string::npos){
       COM_assertion_msg(cur_pos == 0,
                         "Parameter file has invalid value format");
       value.erase(0,1);
       cur_pos = value.rfind('"');
       // This should get rid of any whitespace after the last quotation mark
       eat_whitespace_until(value, '"', (int)cur_pos+1);
       COM_assertion_msg(cur_pos == value.size()-1,
                         "Parameter file has invalid value format");
       value.erase(cur_pos,1);
       COM_assertion_msg(value.find('"') == string::npos,
                         "Parameter file has invalid value format");
     }
     // quotations are never allowed in the option
     cur_pos = option.find_first_of("\"");
     COM_assertion_msg(cur_pos == string::npos,
                       "Unexpected quotation mark found in an option.");
     param_list.push_back(std::make_pair(option,value));
   }
 }