Rocstar: readinp.cpp File Reference
readinp.cpp File Reference
#include <stdio.h>
#include "makeflo.h"
#include "adj.h"
Classes
class bcReader
Macros
#define BC_EXTENTION ".inp"
#define ERR "Error reading " BC_EXTENTION " file: "
Functions
void checkSpan (const blockSpan &s, const char *what)
const char * readBoundaries (vector< block * > &blocks, const char *inMesh)
Macro Definition Documentation
#define BC_EXTENTION ".inp"
Definition at line 132 of file readinp.cpp.
#define ERR "Error reading " BC_EXTENTION " file: "
Definition at line 133 of file readinp.cpp.
Referenced by readBoundaries().
Function Documentation
void checkSpan (const blockSpan & s, const char * what)
Definition at line 123 of file readinp.cpp.
References blockSpan::end, makefloParam::levelBad, makefloParam::multigridError(), parameters, and blockSpan::start.
Referenced by readBoundaries().
{
         for (int axis=0;axis<3;axis++)
                 if ((s.start[axis]&parameters.levelBad)
                   ||((s.end[axis]-1)&parameters.levelBad)) {
                         fprintf(stderr,"%s",what);
                         parameters.multigridError();
                 }
 }
const char* readBoundaries (vector< block * > & blocks, const char * inMesh)
Definition at line 135 of file readinp.cpp.
References block::addBC(), checkSpan(), ERR, cimg_library::cimg::fopen(), block::getDim(), bcReader::read(), and bcReader::skipLine().
Referenced by main().
 {
         FILE *in=fopen(inMesh,"r");
         if (in==NULL) {
                 fprintf(stderr,"Cannot open boundary condition file '%s'.\n",inMesh);
                 fprintf(stderr,"Continuing without external boundary conditions\n");
                 return NULL;//Ignore missing BC file
         }
         bcReader r(in);
         //Check the file header:
         int solver;
         if (!r.read(&solver)) return ERR "Bad file header (line 1)";
         if (solver!=1) return ERR "Must use Gridgen generic solver";
         int nBlocks;
         if (!r.read(&nBlocks)) return ERR "Bad file header (line 2)";
         if (nBlocks!=(int)blocks.size()) return ERR "mesh's block count does not match";
         //Read each block
         for (int bn=0;bn<nBlocks;bn++) {
                 block *b=blocks[bn];
                 //Check the block size
                 blockDim dim;
                 if (!r.read(dim)) return ERR "Cannot read block size";
                 if (dim!=b->getDim()) return ERR "mesh's block size does not match";
                 //Skip over the block name line
                 r.skipLine();
                 r.skipLine();
                 //Get the patch count and loop over patches
                 int nPatch;
                 if (!r.read(&nPatch)) return ERR "Cannot read patch count";
                 for (int p=0;p<nPatch;p++) {
                         //Get the patch dimensions
                         blockSpan span;
                         if (!r.read(span)) return ERR "Cannot read patch dimensions";
                         //Get the patch type and handle patch
                         int type;
                         if (!r.read(&type)) return ERR "Cannot read patch type";
                         if (type>=0)
                         {//External boundary condition--add to block
                                 b->addBC(span,type);
                                 char errBuf[200];
                                 sprintf(errBuf,"Bad boundary condition for block %d\n",1+bn);
                                 checkSpan(span,errBuf);
                         }
                         else
                         {//Internal boundary condition-- read and ignore
                                 blockSpan dest;
                                 if (!r.read(dest)) return ERR "Cannot read internal patch dimensions";
                                 int destBlock;
                                 if (!r.read(&destBlock)) return ERR "Cannot read destination block";
                                 destBlock--; //Make zero-based
                         }
                 }
         }
         return NULL;//Everything worked
 }