Rocstar: ReadInputFile.F90 File Reference
ReadInputFile.F90 File Reference
Functions/Subroutines
subroutine readinputfile (regions)
Function/Subroutine Documentation
subroutine readinputfile (type(t_region), dimension(:), pointer regions)
Definition at line 45 of file ReadInputFile.F90.
References buildfilenameplain(), moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, inrt_readmaterialinput(), CImg< T >::line(), readaccelerationsection(), readflowsection(), readforcessection(), readformatssection(), readinitflowsection(), readmixturesection(), readmultigridsection(), readnumericssection(), readpostsection(), readprepsection(), readprobesection(), readrandomsection(), readreferencesection(), readrocketsection(), readstatisticsection(), readthrustsection(), readtimestepsection(), readtimezoomingsection(), readtransformsection(), readviscositysection(), moderror::registerfunction(), and Attribute::status().
Referenced by peul_rocflo_post(), rflo_userinput(), rflu_userinput(), rocflo_init(), rocflo_post(), rocflo_toflu(), rocpart_post(), rocvav_post(), rvav_readfilestream1(), rvav_readfilestream2(), and rvav_readfilestream2comput().