Rocstar: ReadMixtureSection.F90 File Reference
ReadMixtureSection.F90 File Reference
Functions/Subroutines
subroutine readmixturesection (regions)
Function/Subroutine Documentation
subroutine readmixturesection (type(t_region), dimension(:), pointer regions)
Definition at line 44 of file ReadMixtureSection.F90.
References moderror::deregisterfunction(), nvals, modinterfacesio::ReadSection::readsection(), and moderror::registerfunction().
Referenced by readinputfile().