Rocstar: readhdf.cpp File Reference
readhdf.cpp File Reference
#include <stdio.h>
#include "gridutil.h"
#include "mfhdf.h"
Macros
#define chk(x) checkHDFerr(x,__FILE__,__LINE__)
Functions
static int checkHDFerr (int errCode, const char *fName, int lineNo)
const char * read_hdf (const char *filename, blockConsumer &dest)
Macro Definition Documentation
#define chk (x) checkHDFerr(x,__FILE__,__LINE__)
Definition at line 66 of file readhdf.cpp.
Referenced by read_hdf().
Function Documentation
static int checkHDFerr (int errCode, const char * fName, int lineNo) static
Definition at line 67 of file readhdf.cpp.
{
         if (errCode==-1) {
                 fprintf(stderr,"HDF I/O Error in (%s:%d)\n",
                         fName,lineNo);
                 exit(23);
         }
         return errCode;
 }
const char* read_hdf (const char * filename, blockConsumer & dest)
Definition at line 76 of file readhdf.cpp.
References blockConsumer::allocateBlock(), chk, blockConsumer::consume(), coord, blockConsumer::freeBlock(), blockDim::getSize(), i, and rank.
Referenced by read_file().
 {
         int32 i, d;
         //Open the input file
         int32 sd_id = SDstart(filename, DFACC_READ);
         if (sd_id==-1) return "Couldn't open HDF input file!";
         //Select the X, Y, and Z components
         int32 sds_id[3];
         for (i=0;i<3;i++) sds_id[i]=chk(SDselect(sd_id,5+4*i));
         //Determine the ni, nj, and nk dimensions
         blockDim dim;
         /* This doesn't work.
         for (d=0;d<3;d++) {
                 int32 dim_id = chk(SDgetdimid(sds_id[0],d));
                 char dim_name[200];
                 int32 dim_size, data_type, n_attrs;
                 chk(SDdiminfo(dim_id, dim_name, &dim_size, &data_type, &n_attrs));
                 dim[2-d]=dim_size;
         }
         */
         char name[200];
         int32 rank, size[3], data_type, n_attrs;
         chk(SDgetinfo(sds_id[0], name, &rank, size, &data_type, &n_attrs));
         dim[0]=size[2];
         dim[1]=size[1];
         dim[2]=size[0];
         //Allocate storage for the X, Y, and Z output
         vector3d *locs=dest.allocateBlock(dim);
         //Read each of X, Y, and Z
         int nLocs=dim.getSize();
         double *coord=new double[nLocs];
         for (i=0;i<3;i++)
         {
                 int32 start[3]={0,0,0};
                 int32 edges[3];
                 for (d=0;d<3;d++) edges[d]=dim[2-d];
                 chk(SDreaddata(sds_id[i], start, NULL, edges, coord));
                 //Copy this coordinate into locs
                 for (int l=0;l<nLocs;l++) locs[l][i]=coord[l];
         }
         delete[] coord;
         //Pass locations to consumer
         dest.consume(dim,locs);
         dest.freeBlock(locs);
         //Close the file and return
         for (i=0;i<3;i++) chk(SDendaccess(sds_id[i]));
         chk(SDend(sd_id));
         return NULL;
 }