Rocstar: readsdv.C File Reference
readsdv.C File Reference
#include "roccom.h"
#include <vector>
#include <iostream>
Classes
struct Subdiv
Functions
void Rocin_load_module (const char *)
Load the module Rocin into Roccom using the given module name.
void Rocin_unload_module (const char *)
Unload the module Rocin from Roccom.
void read_pane_sp (std::string &fname, const std::string &prefix, int pid, Subdiv &sd)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 137 of file readsdv.C.
References COM_finalize(), COM_init(), and read_pane_sp().
{
   COM_init( &argc, &argv);
   if ( argc<3) {
     std::cerr << "Usage: " << argv[0] << " <file-name> <prefix> <pane_id>\n"
               << "Example: " << argv[0] << "A_101_sdv.hdf A 101" << std::endl;
     exit(-1);
   }
   std::string fname = argv[1], prefix = argv[2];
   int pid = std::atoi(argv[3]);
   // Reading the given pane from the file into the structure.
   Subdiv sd;
   read_pane_sp( fname, prefix, pid, sd);
   COM_finalize();
 }
void read_pane_sp (std::string & fname, const std::string & prefix, int pid, Subdiv & sd)
Definition at line 52 of file readsdv.C.
References COM_call_function(), COM_copy_array(), COM_delete_window(), COM_get_attribute_handle(), COM_get_function_handle(), COM_get_size(), MPI_COMM_SELF, Rocin_load_module(), Rocin_unload_module(), Subdiv::subface_counterparts, Subdiv::subface_nat_coors, Subdiv::subface_offsets, Subdiv::subface_parents, Subdiv::subfaces, Subdiv::subnode_counterparts, Subdiv::subnode_ncs, Subdiv::subnode_parents, and Subdiv::subnode_subIDs.
Referenced by main().
{
   // Load Rocin into Roccom
   Rocin_load_module( "SDV_IN");
   // Obtain function handles to Rocin functions
   int hdl_read = COM_get_function_handle( "SDV_IN.read_windows");
   int hdl_obtain = COM_get_function_handle( "SDV_IN.obtain_attribute");
   // Define the base-window and sdv-window names
   std::string bufprefix = "__BUF";
   std::string sdv_material = prefix+"_sdv";
   std::string sdv_wname = bufprefix+sdv_material;
   // Read the pane from the given file. Note that the file contains both
   // the parent and the subdivided windows. Read only the subdivided one.
   MPI_Comm comm_self = MPI_COMM_SELF;
   COM_call_function( hdl_read, fname.c_str(), bufprefix.c_str(),
                      sdv_material.c_str(), &comm_self);
   int hdl_all = COM_get_attribute_handle( (sdv_wname+".all").c_str());
   COM_call_function( hdl_obtain, &hdl_all, &hdl_all, &pid);
   // Obtain number of sub-nodes, sub-faces, nodes, and faces
   int nsubn, nsubf, nn, nf;
   COM_get_size( (sdv_wname+".sn_parent_fcID").c_str(), pid, &nsubn);
   COM_get_size( (sdv_wname+".:t3").c_str(), pid, &nsubf);
   COM_get_size( (sdv_wname+".sn_subID").c_str(), pid, &nn);
   COM_get_size( (sdv_wname+".sf_offset").c_str(), pid, &nf);
   // Obtain the connectivity
   sd.subfaces.resize( 3*nsubf);
   COM_copy_array( (sdv_wname+".:t3").c_str(), pid, &sd.subfaces[0], 3);
   // NOTE: The last argument (3) indicates that three sub-node IDs are stored
   // consecutively for each sub-face. Use the number one (1) if the first
   // sub-nodes of all sub-faces are stored together followed by the second
   // sub-nodes and then third.
   // Obtain subnode_parents, subnode_ncs, and subnode_counterparts
   sd.subnode_parents.resize( nsubn);
   COM_copy_array( (sdv_wname+".sn_parent_fcID").c_str(),
                   pid, &sd.subnode_parents[0]);
   sd.subnode_ncs.resize( 2*nsubn);
   COM_copy_array( (sdv_wname+".sn_parent_ncs").c_str(), pid, &sd.subnode_ncs[0], 2);
   // NOTE: The last argument (2) indicates that the two local coordinates are
   // stored consecutively. Use the number one (1) if the first local parameter
   // (xi) of all sub-nodes are stored together followed by the second one (eta).
   sd.subnode_subIDs.resize( nn);
   COM_copy_array( (sdv_wname+".sn_subID").c_str(), pid, &sd.subnode_subIDs[0]);
   sd.subnode_counterparts.resize( nsubn);
   COM_copy_array( (sdv_wname+".sn_cntpt_ndID").c_str(),
                   pid, &sd.subnode_counterparts[0]);
   sd.subface_parents.resize( nsubf);
   COM_copy_array( (sdv_wname+".sf_parent").c_str(), pid, &sd.subface_parents[0]);
   sd.subface_nat_coors.resize( nsubf*6);
   COM_copy_array( (sdv_wname+".sf_ncs").c_str(), pid,
                   &sd.subface_nat_coors[0], 6);
   // NOTE: The last argument (6) indicates that the local coordinates are
   // stored consecutively (xi1, eta1, xi2, eta2, xi3, eta3). Use the number
   // one (1) if the xi1 for all nodes are stored together and then xi2, etc..
   // Obtain subface_offsets
   sd.subface_offsets.resize( nf);
   COM_copy_array( (sdv_wname+".sf_offset").c_str(), pid, &sd.subface_offsets[0]);
   sd.subface_counterparts.resize( nsubf);
   COM_copy_array( (sdv_wname+".sf_cntpt_fcID").c_str(), pid,
                   &sd.subface_counterparts[0]);
   // Delete the window created by Rocin.
   COM_delete_window( sdv_wname.c_str());
   // Unload Rocin from Roccom.
   Rocin_unload_module( "SDV_IN");
 }
void Rocin_load_module (const char * name)
Load the module Rocin into Roccom using the given module name.
This module provides three subroutines: "read_windows", "read_by_control_file", and "obtain_attribute".
Definition at line 3035 of file Rocin.C.
References Rocin::init().
Referenced by COM_F_FUNC2(), and read_pane_sp().
 { Rocin::init( std::string(name)); }
void Rocin_unload_module (const char *)
Unload the module Rocin from Roccom.
Definition at line 3038 of file Rocin.C.
References Rocin::finalize().
Referenced by COM_F_FUNC2(), and read_pane_sp().
 { Rocin::finalize( std::string(name)); }