Rocstar: ReadPostSection.F90 File Reference
ReadPostSection.F90 File Reference
Functions/Subroutines
subroutine readpostsection (global)
Function/Subroutine Documentation
subroutine readpostsection (type(t_global), pointer global)
Definition at line 44 of file ReadPostSection.F90.
References moderror::deregisterfunction(), nvals, modinterfacesio::ReadSection::readsection(), and moderror::registerfunction().
Referenced by readinputfile().