Rocstar: readgrd.cpp File Reference
readgrd.cpp File Reference
#include <stdio.h>
#include "gridutil.h"
Classes
class gridgenGrdFormatter
Abstracts the file format of a gridgen .grd file.
class gridgenAsciiFormatter
ASCII format input file:
class gridgenBinaryFormatter< coordT >
Machine binary input file:
class gridgenBinaryFloatFormatter
class gridgenBinaryDoubleFormatter
Typedefs
typedef int grdb_int_t
typedef double grdb_coord_t
Functions
static const char * readInt (FILE *f, int *dest)
static const char * readDouble (FILE *f, double *dest)
const char * read_general (const char *gridFile, gridgenGrdFormatter &fmt, blockConsumer &dest)
const char * read_grd (const char *gridFile, blockConsumer &dest)
const char * read_grds (const char *gridFile, blockConsumer &dest)
const char * read_grdd (const char *gridFile, blockConsumer &dest)
Typedef Documentation
typedef double grdb_coord_t
Definition at line 84 of file readgrd.cpp.
typedef int grdb_int_t
Definition at line 83 of file readgrd.cpp.
Function Documentation
const char* read_general (const char * gridFile, gridgenGrdFormatter & fmt, blockConsumer & dest)
Definition at line 152 of file readgrd.cpp.
References blockConsumer::allocateBlock(), blockConsumer::consume(), cimg_library::cimg::fclose(), cimg_library::cimg::fopen(), blockConsumer::freeBlock(), blockDim::getSize(), i, gridgenGrdFormatter::readDouble(), gridgenGrdFormatter::readInt(), and gridgenGrdFormatter::setFile().
Referenced by read_grd(), read_grdd(), and read_grds().
 {
         const char *err;
         //Open the input file
         FILE *f=fopen(gridFile,"r");
         if (f==NULL) return "Couldn't open input .grd file";
         fmt.setFile(f);
         //Read the header
         int nBlocks=0;
         if (NULL!=(err=fmt.readInt(&nBlocks))) return err;
         //Read the block sizes
         blockDim *dims=new blockDim[nBlocks];
         int b;
         for (b=0;b<nBlocks;b++) {
                 int nx,ny,nz;
                 if (NULL!=(err=fmt.readInt(&nx))) return err;
                 if (NULL!=(err=fmt.readInt(&ny))) return err;
                 if (NULL!=(err=fmt.readInt(&nz))) return err;
                 dims[b]=blockDim(nx,ny,nz);
         }
         //Read and consume each block's coordinates
         for (b=0;b<nBlocks;b++) {
                 int nLocs=dims[b].getSize();
                 vector3d *locs=dest.allocateBlock(dims[b]);
                 for (int c=0;c<3;c++) //*outer* loop is coordinate axis
                   for (int i=0;i<nLocs;i++) {//*inner* loop is location #
                         double loc;
                         if (NULL!=(err=fmt.readDouble(&loc))) return err;
                         locs[i][c]=loc;
                   }
                 if (NULL!=(err=dest.consume(dims[b],locs))) return err;
                 dest.freeBlock(locs);
         }
         //Finish up
         delete[] dims;
         fclose(f);
         return NULL; //Everything worked
 }
const char* read_grd (const char * gridFile, blockConsumer & dest)
Definition at line 196 of file readgrd.cpp.
References read_general().
Referenced by read_file().
 {
         gridgenAsciiFormatter fmt;
         return read_general(gridFile,fmt,dest);
 }
const char* read_grdd (const char * gridFile, blockConsumer & dest)
Definition at line 206 of file readgrd.cpp.
References read_general().
Referenced by read_file().
 {
         gridgenBinaryDoubleFormatter fmt;
         return read_general(gridFile,fmt,dest);
 }
const char* read_grds (const char * gridFile, blockConsumer & dest)
Definition at line 201 of file readgrd.cpp.
References read_general().
Referenced by read_file().
 {
         gridgenBinaryFloatFormatter fmt;
         return read_general(gridFile,fmt,dest);
 }
static const char* readDouble (FILE * f, double * dest) static
Definition at line 96 of file readgrd.cpp.
References cimg_library::cimg::fread().
{
         grdb_coord_t g;
         if (1!=fread(&g,sizeof(g),1,f))
                 return "Error reading coordinate from .grdb file";
         *dest=g;
         return NULL;
 }
static const char* readInt (FILE * f, int * dest) static
Definition at line 87 of file readgrd.cpp.
References cimg_library::cimg::fread().
{
         grdb_int_t g;
         if (1!=fread(&g,sizeof(g),1,f))
                 return "Error reading integer from .grdb file";
         *dest=g;
         return NULL;
 }