Rocstar: ReadReferenceSection.F90 File Reference
ReadReferenceSection.F90 File Reference
Functions/Subroutines
subroutine readreferencesection (global)
Function/Subroutine Documentation
subroutine readreferencesection (type(t_global), pointer global)
Definition at line 43 of file ReadReferenceSection.F90.
References moderror::deregisterfunction(), nvals, modinterfacesio::ReadSection::readsection(), and moderror::registerfunction().
Referenced by readinputfile().