Rocstar: ReflectPosition.F90 File Reference
ReflectPosition.F90 File Reference
Functions/Subroutines
subroutine reflectposition (nx, ny, nz, xc, yc, zc, xComp, yComp, zComp)
Function/Subroutine Documentation
subroutine reflectposition (real(rfreal), intent(in) nx, real(rfreal), intent(in) ny, real(rfreal), intent(in) nz, real(rfreal), intent(in) xc, real(rfreal), intent(in) yc, real(rfreal), intent(in) zc, real(rfreal), intent(inout) xComp, real(rfreal), intent(inout) yComp, real(rfreal), intent(inout) zComp)
Definition at line 55 of file ReflectPosition.F90.
References Kdtree_d< Traits >::ExtPoint::term().
Referenced by plag_reflectparticledata(), and rflu_modsymmetryperiodic::rflu_sype_augmentvertexlists().