Rocstar: removeBCs.f90 File Reference
removeBCs.f90 File Reference
Functions/Subroutines
subroutine removebcs_meff (ndim, nrows, nnz, nstart, rp1, cval, aval, newnrows, newnstart, newndim, global)
subroutine removebcs_pbar (nstart, ndim, pbar, newndim, newpbar)
subroutine removebcs_newa (nstart, ndim, a, newndim, newa)
Function/Subroutine Documentation
subroutine removebcs_meff (integer ndim, integer nrows, integer nnz, integer nstart, integer, dimension(nrows+1) rp1, integer, dimension(nnz) cval, real(kind=wp), dimension(nnz) aval, integer newnrows, integer newnstart, integer newndim, type(rocfrac_global) global)
Definition at line 84 of file removeBCs.f90.
References i, j, and Aff_transformation_2< R_ >::m().
Referenced by implicit_soln().
subroutine removebcs_newa (integer nstart, integer ndim, real(kind=wp), dimension(ndim) a, integer newndim, real(kind=wp), dimension(newndim) newa)
Definition at line 373 of file removeBCs.f90.
References Line_2< R, T >::a(), i, and Aff_transformation_2< R_ >::m().
Referenced by implicit_soln().
subroutine removebcs_pbar (integer nstart, integer ndim, real(kind=wp), dimension(ndim) pbar, integer newndim, real(kind=wp), dimension(newndim) newpbar)
Definition at line 304 of file removeBCs.f90.
References i, and Aff_transformation_2< R_ >::m().
Referenced by implicit_soln().