Rocstar: RFC_Window_base_IO_binary.C File Reference
RFC_Window_base_IO_binary.C File Reference
#include "RFC_Window_base.h"
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <cassert>
Functions
RFC_BEGIN_NAME_SPACE void write (std::ostream &os, const int t)
void read (std::istream &is, int &t)
void swap_endian (short int &t)
void swap_endian (int &t)
void swap_endian (float &t)
void swap_endian (double &t)
Function Documentation
void read (std::istream & is, int & t) inline
Definition at line 40 of file RFC_Window_base_IO_binary.C.
Referenced by RFC_Pane_base::read_binary().
{
   is.read((char*)&t, sizeof(int));
 }
void swap_endian (short int & t) inline
Definition at line 45 of file RFC_Window_base_IO_binary.C.
References swap().
Referenced by RFC_Pane_base::read_binary().
{
   char *c = (char*)&t;
   std::swap( c[0],c[1]);
 }
void swap_endian (int & t) inline
Definition at line 51 of file RFC_Window_base_IO_binary.C.
References swap().
                      {
   char *c = (char*)&t;
   std::swap( c[0],c[3]); std::swap( c[1],c[2]);
 }
void swap_endian (float & t) inline
Definition at line 57 of file RFC_Window_base_IO_binary.C.
References swap().
{
   char *c = (char*)&t;
   std::swap( c[0],c[3]); std::swap( c[1],c[2]);
 }
void swap_endian (double & t) inline
Definition at line 63 of file RFC_Window_base_IO_binary.C.
References swap().
{
   char *c = (char*)&t;
   std::swap( c[0],c[7]); std::swap( c[1],c[6]);
   std::swap( c[2],c[5]); std::swap( c[3],c[4]);
 }
RFC_BEGIN_NAME_SPACE void write (std::ostream & os, const int t) inline
Definition at line 35 of file RFC_Window_base_IO_binary.C.
Referenced by RFC_Pane_base::write_binary().
{
   os.write((char*)&t, sizeof(int));
 }