Rocstar: RFC_Window_base_IO_tecplot.C File Reference
RFC_Window_base_IO_tecplot.C File Reference
#include "RFC_Window_base.h"
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <cassert>
Functions
static void write_attr (std::ostream &os, const COM::Attribute *attr, int i)
Function Documentation
static void write_attr (std::ostream & os, const COM::Attribute * attr, int i) static
Definition at line 55 of file RFC_Window_base_IO_tecplot.C.
References COM_DOUBLE, COM_DOUBLE_PRECISION, COM_FLOAT, COM_INT, COM_INTEGER, COM_REAL, and j.
Referenced by genxwritesolution(), Scheduler::ActionItem::hasOutput(), mesh2d(), mesh2doverlay(), Scheduler::ActionItem::n_write(), Scheduler::ActionItem::print(), rocfracprep(), RFC_Pane_base::write_tec_ij(), RFC_Pane_base::write_tec_mixed(), and RFC_Pane_base::write_tec_tri().
{
   const int dim = attr->size_of_components();
   switch ( attr->data_type()) {
   case COM_DOUBLE:
   case COM_DOUBLE_PRECISION: {
     const double *values = reinterpret_cast<const double*>(attr->pointer());
     for ( int j=0; j<dim; ++j) os << ' ' << values[i*dim+j];
     break;
   }
   case COM_FLOAT:
   case COM_REAL: {
     const float *values = reinterpret_cast<const float*>(attr->pointer());
     for ( int j=0; j<dim; ++j) os << ' ' << values[i*dim+j];
     break;
   }
   case COM_INT:
   case COM_INTEGER: {
     const int *values = reinterpret_cast<const int*>(attr->pointer());
     for ( int j=0; j<dim; ++j) os << ' ' << values[i*dim+j];
     break;
   }
   default:
     assert(false); abort();
   }
 }