Rocstar: RFC_Window_base_IO.C File Reference
RFC_Window_base_IO.C File Reference
#include "RFC_Window_base.h"
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <cassert>
#include <sstream>
#include <cstring>
Classes
class Pane_friend
Functions
void Rocin_load_module (const char *)
Load the module Rocin into Roccom using the given module name.
void Rocin_unload_module (const char *)
Unload the module Rocin from Roccom.
void Rocout_load_module (const char *)
Load the module Rocout into Roccom using the given module name.
void Rocout_unload_module (const char *)
Unload the module Rocout from Roccom.
Function Documentation
void Rocin_load_module (const char * name)
Load the module Rocin into Roccom using the given module name.
This module provides three subroutines: "read_windows", "read_by_control_file", and "obtain_attribute".
Definition at line 3035 of file Rocin.C.
Referenced by RFC_Window_base::read_sdv().
 { Rocin::init( std::string(name)); }
void Rocin_unload_module (const char *)
Unload the module Rocin from Roccom.
Definition at line 3038 of file Rocin.C.
Referenced by RFC_Window_base::read_sdv().
 { Rocin::finalize( std::string(name)); }
void Rocout_load_module (const char * name)
Load the module Rocout into Roccom using the given module name.
This module provides one subroutine: "write_attribute".
Definition at line 873 of file Rocout.C.
References Rocout::init().
Referenced by COM_F_FUNC2(), and RFC_Window_base::write_sdv().
 { Rocout::init( std::string(name)); }
void Rocout_unload_module (const char *)
Unload the module Rocout from Roccom.
Definition at line 876 of file Rocout.C.
References Rocout::finalize().
Referenced by COM_F_FUNC2(), and RFC_Window_base::write_sdv().
 { Rocout::finalize( std::string(name)); }