Rocstar: RFLO_CalcGradVector.F90 File Reference
RFLO_CalcGradVector.F90 File Reference
Functions/Subroutines
subroutine rflo_calcgradvector (region, iBegV, iEndV, iBegG, iEndG, var, gradi, gradj, gradk)
subroutine checkindxrange
Function/Subroutine Documentation
subroutine rflo_calcgradvector::checkindxrange ()
Definition at line 138 of file RFLO_CalcGradVector.F90.
References moderror::errorstop(), gradi(), gradj(), i, idnbeg, idnend, j, jdnbeg, jdnend, k, kdnbeg, Aff_transformation_2< R_ >::m(), rflo_getcelloffset(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), and StopWatch::stop().
Referenced by rflo_calcgradvector().
subroutine rflo_calcgradvector (type(t_region) region, integer iBegV, integer iEndV, integer iBegG, integer iEndG, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer gradi, real(rfreal), dimension(:,:), pointer gradj, real(rfreal), dimension(:,:), pointer gradk)
Definition at line 55 of file RFLO_CalcGradVector.F90.
References checkindxrange(), moderror::deregisterfunction(), gradi(), gradj(), moderror::registerfunction(), rflo_calcgradconnbc(), rflo_calcgraddummy(), rflo_calcgradfaces(), rflo_calcgradphysbc(), rflo_copyedgefacenorm(), rflo_copyedgefaceparal(), and rflo_getdimensphys().
Referenced by radi_flimdiffflux(), turb_coviscousfluxes(), turb_lesgeteddyvis(), turb_ranssavisflux(), and viscousfluxes().