Rocstar: RFLO_CalcGradDummy.F90 File Reference
RFLO_CalcGradDummy.F90 File Reference
Functions/Subroutines
subroutine rflo_calcgraddummy (region, patch, iBegV, iEndV, iBegG, iEndG, gradi, gradj, gradk)
Function/Subroutine Documentation
subroutine rflo_calcgraddummy (type(t_region) region, type(t_patch) patch, integer iBegV, integer iEndV, integer iBegG, integer iEndG, real(rfreal), dimension(:,:), pointer gradi, real(rfreal), dimension(:,:), pointer gradj, real(rfreal), dimension(:,:), pointer gradk)
Definition at line 51 of file RFLO_CalcGradDummy.F90.
References moderror::deregisterfunction(), gradi(), gradj(), ibeg, idir, iend, inode, jbeg, jdir, jend, jnode, kbeg, kdir, moderror::registerfunction(), rflo_calcgraddummyconn(), rflo_calcgraddummyphys(), rflo_calcgraddummysymm(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_calcgradvector().