Rocstar: RFLO_ExchangeCornerEdgeCells.F90 File Reference
RFLO_ExchangeCornerEdgeCells.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_exchangecorneredgecells (regions, iReg)
Function/Subroutine Documentation
subroutine rflo_exchangecorneredgecells (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 45 of file RFLO_ExchangeCornerEdgeCells.F90.
References moderror::deregisterfunction(), i, ibeg, icell, icorner, iend, j, jbeg, jend, k, kbeg, mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getcornercellsindices(), and rflo_getedgecellsindices().
Referenced by rflo_modboundaryconditions::rflo_boundaryconditionsrecv().