Rocstar: RFLO_ReadBcOutflowSection.F90 File Reference
RFLO_ReadBcOutflowSection.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_readbcoutflowsection (regions)
Function/Subroutine Documentation
subroutine rflo_readbcoutflowsection (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file RFLO_ReadBcOutflowSection.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), min(), prbeg, prend, prep_modbcdistribution::readpatchsection(), moderror::registerfunction(), and rflo_readbcfromfile().
Referenced by rflo_readbcinputfile().