Rocstar: RFLO_ReadSolutionRegion.F90 File Reference
RFLO_ReadSolutionRegion.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_readsolutionregion (iReg, regions)
Function/Subroutine Documentation
subroutine rflo_readsolutionregion (integer iReg, type(t_region), dimension(:), pointer regions)
Definition at line 52 of file RFLO_ReadSolutionRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, idcbeg, idcend, ipnbeg, ipnend, j, jdcbeg, jdcend, jpnbeg, jpnend, k, kdcbeg, kpnbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_readdatafileint(), rflo_readdatafilereal(), and Attribute::status().
Referenced by peul_rocflo_post(), rocflo_post(), rocvav_post(), rvav_readfilestream1(), rvav_readfilestream2(), and rvav_readfilestream2comput().