Rocstar: RFLO_GetPatchMapping.F90 File Reference
RFLO_GetPatchMapping.F90 File Reference
Functions/Subroutines
subroutine rflo_getpatchmapping (lb, lbs, l1SrcDir, l2SrcDir, align, idir, jdir, kdir, idirSrc, jdirSrc, kdirSrc, ibeg, iend, jbeg, jend, kbeg, kend, ibegSrc, iendSrc, jbegSrc, jendSrc, kbegSrc, kendSrc, mapMat)
Function/Subroutine Documentation
subroutine rflo_getpatchmapping (integer lb, integer lbs, integer l1SrcDir, integer l2SrcDir, logical align, integer idir, integer jdir, integer kdir, integer idirSrc, integer jdirSrc, integer kdirSrc, integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer ibegSrc, integer iendSrc, integer jbegSrc, integer jendSrc, integer kbegSrc, integer kendSrc, integer, dimension(3,4) mapMat)
Definition at line 64 of file RFLO_GetPatchMapping.F90.
References vector3d::dir(), ibeg, idir, iend, jbeg, jdir, jend, kbeg, and kdir.
Referenced by convertflo2flumesh(), peul_exchangedummyconf(), plag_bufferdatasend(), plag_patchexchangeconf(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_copystatbuff(), plag_rflo_sourcecell(), radi_floflimexchangedummyconf(), rflo_exchangednodecopy(), rflo_exchangedummyconf(), rflo_exchangegeometrycopy(), rflo_sourcecell(), and turb_floransexchangedummyconf().