Rocstar: RFLO_C2fAvgCoeffs.F90 File Reference
RFLO_C2fAvgCoeffs.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_c2favgcoeffs (region)
subroutine computeavgco (ijk)
Function/Subroutine Documentation
subroutine rflo_c2favgcoeffs::computeavgco (integer ijk)
Definition at line 132 of file RFLO_C2fAvgCoeffs.F90.
References i, ibeg, idcbeg, idcend, idir, iend, j, jbeg, jdcbeg, jdcend, jdir, jend, k, kbeg, kdcbeg, kdir, max(), and sqrt().
subroutine rflo_c2favgcoeffs (type(t_region) region)
Definition at line 44 of file RFLO_C2fAvgCoeffs.F90.
References computeavgco(), moderror::deregisterfunction(), idcbeg, idcend, idir, jdcbeg, jdcend, jdir, kdcbeg, kdir, moderror::registerfunction(), rflo_c2favgcoeffsdegec(), rflo_c2favgcoeffsdummy(), rflo_c2favgcoeffspatch(), rflo_copyedgefacenorm(), rflo_copyedgefaceparal(), rflo_getcelloffset(), rflo_getdimensdummy(), and rflo_getnodeoffset().
Referenced by rflo_modgridmetrics::rflo_calcgridmetrics(), rflo_movegridblocks(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), and rflo_modvolmeshsmoothing::rflo_movegridvms().