Rocstar: RFLO_C2fAvgCoeffsDummyPhys.F90 File Reference
RFLO_C2fAvgCoeffsDummyPhys.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_c2favgcoeffsdummyphys (region, lbound, idir, jdir, kdir, indBeg, indEnd, jndBeg, jndEnd, kndBeg, kndEnd)
Function/Subroutine Documentation
subroutine rflo_c2favgcoeffsdummyphys (type(t_region) region, integer lbound, integer idir, integer jdir, integer kdir, integer indBeg, integer indEnd, integer jndBeg, integer jndEnd, integer kndBeg, integer kndEnd)
Definition at line 49 of file RFLO_C2fAvgCoeffsDummyPhys.F90.
References moderror::deregisterfunction(), i, idir, j, jdir, k, kdir, moderror::registerfunction(), and rflo_getnodeoffset().
Referenced by rflo_c2favgcoeffsdummy().