Rocstar: RFLO_RoeFluxPatch.F90 File Reference
RFLO_RoeFluxPatch.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_roefluxpatch (region, patch)
Function/Subroutine Documentation
subroutine rflo_roefluxpatch (type(t_region) region, type(t_patch) patch)
Definition at line 45 of file RFLO_RoeFluxPatch.F90.
References bcondinjectionperf(), moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), rhs, and sqrt().
Referenced by rflo_roefluxfirst(), and rflo_roefluxsecond().