Rocstar: RFLO_SetMstageCoeffs.F90 File Reference
RFLO_SetMstageCoeffs.F90 File Reference
Functions/Subroutines
subroutine rflo_setmstagecoeffs (global, input, nrkSteps)
Function/Subroutine Documentation
subroutine rflo_setmstagecoeffs (type(t_global), pointer global, type(t_mixt_input) input, integer nrkSteps)
Definition at line 44 of file RFLO_SetMstageCoeffs.F90.
References moderror::errorstop(), rflu_modrepair3d::input(), and min().
Referenced by rflo_derivedinputvalues(), and rflo_dualtimestepping().