Rocstar: RFLO_CalcFaceCentroids.F90 File Reference
RFLO_CalcFaceCentroids.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_calcfacecentroids (region)
subroutine computefacectr (ijk)
Function/Subroutine Documentation
subroutine rflo_calcfacecentroids::computefacectr (integer ijk)
Definition at line 101 of file RFLO_CalcFaceCentroids.F90.
References i, ibeg, idir, idnbeg, idnend, iend, j, jbeg, jdir, jdnbeg, jdnend, jend, k, kbeg, kdir, and kdnbeg.
Referenced by rflo_calcfacecentroids().
subroutine rflo_calcfacecentroids (type(t_region) region)
Definition at line 42 of file RFLO_CalcFaceCentroids.F90.
References computefacectr(), moderror::deregisterfunction(), idir, idnbeg, idnend, jdir, jdnbeg, jdnend, kdir, kdnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), and rflo_getnodeoffset().
Referenced by rflo_modgridmetrics::rflo_calcgridmetrics(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), and rflo_modmovegridframe::rflo_movegridframe().