Rocstar: RFLO_UserInput.F90 File Reference
RFLO_UserInput.F90 File Reference
Functions/Subroutines
subroutine rflo_userinput (regions)
Function/Subroutine Documentation
subroutine rflo_userinput (type (t_region), dimension(:), pointer regions)
Definition at line 45 of file RFLO_UserInput.F90.
References moderror::deregisterfunction(), moderror::errorstop(), COM_exception::msg(), readinputfile(), moderror::registerfunction(), rflo_checkuserinput(), rflo_derivedinputvalues(), rflo_initinputvalues(), rflo_mapregionsprocessors(), rflo_readbcinputfile(), and rflo_readregionmapsection().
Referenced by rflo_getuserinput().