Rocstar: RFLO_ModLaplaceSmoothing.F90 File Reference
RFLO_ModLaplaceSmoothing.F90 File Reference
#include "Indexing.h"
Data Types
module rflo_modlaplacesmoothing
Functions/Subroutines
subroutine accumulatexyzwork (sf, fc1, fc2, fc3, fc4)
subroutine accumulatexyzwork (cfac)
subroutine accumulatexyzwork
Function/Subroutine Documentation
subroutine rflo_laplacegridortho::accumulatexyzwork (real(rfreal), dimension(:,:), pointer sf, real(rfreal), dimension(xcoord:zcoord) fc1, real(rfreal), dimension(xcoord:zcoord) fc2, real(rfreal), dimension(xcoord:zcoord) fc3, real(rfreal), dimension(xcoord:zcoord) fc4)
Definition at line 1486 of file RFLO_ModLaplaceSmoothing.F90.
References dot_product(), and sqrt().
Referenced by rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_modlaplacesmoothing::rflo_laplacegridortho1(), and rflo_modlaplacesmoothing::rflo_laplacegridortho2().
subroutine rflo_laplacegridortho2::accumulatexyzwork ()
Definition at line 1964 of file RFLO_ModLaplaceSmoothing.F90.
References dot_product(), TestBase::f1(), and TestBase::f2().
subroutine rflo_laplacegridortho1::accumulatexyzwork (real(rfreal), dimension(:,:), pointer cfac)
Definition at line 1743 of file RFLO_ModLaplaceSmoothing.F90.
References rflo_modlaplacesmoothing::rflo_projectquadcorner().