Rocstar: RFLO_ReadRegionTopology.F90 File Reference
RFLO_ReadRegionTopology.F90 File Reference
Functions/Subroutines
subroutine rflo_readregiontopology (global, regions)
Function/Subroutine Documentation
subroutine rflo_readregiontopology (type(t_global), pointer global, type(t_region), dimension(:), pointer regions)
Definition at line 45 of file RFLO_ReadRegionTopology.F90.
References moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, COM_exception::msg(), moderror::registerfunction(), and Attribute::status().
Referenced by peul_rocflo_post(), rflo_initflowsolver(), rocflo_blocks(), rocflo_init(), rocflo_post(), rocflo_split(), rocflo_surf(), rocflo_toflu(), rocpart_post(), rocvav_post(), rvav_readfilestream1(), rvav_readfilestream2(), and rvav_readfilestream2comput().