Rocstar: RFLO_InitFlowSolver.F90 File Reference
RFLO_InitFlowSolver.F90 File Reference
Functions/Subroutines
subroutine rflo_initflowsolver (casename, verbLevel, global, regions)
Function/Subroutine Documentation
subroutine rflo_initflowsolver (character(*) casename, integer verbLevel, type(t_global), pointer global, type(t_region), dimension(:), pointer regions)
Definition at line 49 of file RFLO_InitFlowSolver.F90.
References Line_2< R, T >::a(), buildversionstring(), Function::communicator(), moderror::deregisterfunction(), moderror::errorstop(), form, modstatsroutines::initstatistics(), inrt_buildversionstring(), min(), Rocin::obtain_attribute(), peri_buildversionstring(), peul_buildversionstring(), plag_buildversionstring(), plag_rflo_setmetrics(), radi_buildversionstring(), moderror::registerfunction(), rflo_modgridmetrics::rflo_calcgridmetrics(), rflo_checkminimumcells(), rflo_checkregionfaces(), rflo_domemoryallocation(), rflo_findsourcepatches(), rflo_findsourceregions(), rflo_findthrustpatches(), rflo_getflowsolution(), rflo_getgeometry(), rflo_getuserinput(), rflo_initgenxinterface(), rflo_initgridprocedures(), rflo_moddegeneratecornedge::rflo_markdegeneratvert(), rflo_openconverfile(), rflo_modforcesmoments::rflo_openforcemomcofile(), rflo_openprobefile(), rflo_openthrustfile(), rflo_randominit(), rflo_readregiontopology(), rflo_modrestartinfo::rflo_readrestartinfo(), rflo_sendboundaryvalues(), rflo_moddegeneratecornedge::rflo_writedegeneratec(), spec_buildversionstring(), modstatsroutines::statbuildversionstring(), modstatsroutines::statmapping(), Attribute::status(), turb_buildversionstring(), turb_calcmetrics(), and x.
Referenced by main(), and rocflo_load_module().