Rocstar: RFLO_BoundaryDeformation.F90 File Reference
RFLO_BoundaryDeformation.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_boundarydeformation (region, boundMoved, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOld, dNode)
Function/Subroutine Documentation
subroutine rflo_boundarydeformation (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 50 of file RFLO_BoundaryDeformation.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, p1, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint2d(), s, and sqrt().
Referenced by rflo_modmovegridelliptfra::rflo_mgelliptinterfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptinterfacesglo(), rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptsurfacesglo(), rflo_modmovegridframe::rflo_mgframeinterfaces(), rflo_modmovegridframe::rflo_mgframesurfaces(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_movegridinterfaces(), rflo_movegridsurfaces(), and rflo_modvolmeshsmoothing::rflo_movegridvms().