Rocstar: RFLO_GetDimensions.F90 File Reference
RFLO_GetDimensions.F90 File Reference
Functions/Subroutines
subroutine rflo_getdimensdummy (region, iLev, idcbeg, idcend, jdcbeg, jdcend, kdcbeg, kdcend)
subroutine rflo_getdimensphys (region, iLev, ipcbeg, ipcend, jpcbeg, jpcend, kpcbeg, kpcend)
subroutine rflo_getdimensdummynodes (region, iLev, idnbeg, idnend, jdnbeg, jdnend, kdnbeg, kdnend)
subroutine rflo_getdimensphysnodes (region, iLev, ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, kpnend)
subroutine rflo_getcelloffset (region, iLev, iCellOffset, ijCellOffset)
subroutine rflo_getnodeoffset (region, iLev, iNodeOffset, ijNodeOffset)
subroutine rflo_getedgecellsindices (region, iLev, iedge, iebeg, ieend, jebeg, jeend, kebeg, keend)
subroutine rflo_getcornercellsindices (region, iLev, icorner, icbeg, icend, jcbeg, jcend, kcbeg, kcend)
Function/Subroutine Documentation
subroutine rflo_getcelloffset (type(t_region) region, integer iLev, integer iCellOffset, integer ijCellOffset)
Definition at line 235 of file RFLO_GetDimensions.F90.
References moderror::deregisterfunction(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), and rflo_getdimensdummy().
Referenced by checkindxrange(), convectivefluxes(), explicitmultistage(), initializeflowfield(), inrt_twodimaverage(), inrt_vaporenergyconversion(), peri_allocatememory(), peri_cnlforceterm(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_cocprslowterms(), peri_copgradupdate(), peul_allocatememory(), peul_bcondinflow(), peul_bcondinjection(), peul_bcondoutflow(), peul_bcondslipwall(), peul_bcondsymmetry(), peul_centraldissipation(), peul_centralflux(), peul_centralfluxpatch(), peul_convectivefluxes(), peul_correctcorneredgecells(), peul_enforcepositivity(), peul_exchangecorneredgecells(), peul_exchangedummyconf(), peul_readsolution(), peul_readsolutionregion(), peul_receivecorneredgecells(), peul_receivedummyvals(), peul_residualsmoothing(), peul_residualsmoothingcoeffs(), peul_rocflo_post(), peul_senddummyconf(), peul_setcorneredgecells(), peul_sourceeqeul(), peul_spectralradii(), peul_writesolution(), plag_bufferdatasend(), plag_modeulerian::plag_calceulerianfield(), plag_calcfacecentroids(), plag_cecellsexchange(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_cecellsgetbuffersize(), plag_corncellsloaddata(), plag_modeulerian::plag_createeulerianfield(), plag_modstats::plag_createstat(), plag_edgecellsloaddata(), plag_getcellindices(), plag_getcellindicesoutflow(), plag_incelltestrobust(), plag_modeulerian::plag_initeulerianfield(), plag_modstats::plag_initstat(), plag_injcejectparticle(), plag_injctilecalcrhs(), plag_injctileinitialize(), plag_intrpmixtproperties(), plag_patchexchangeconf(), plag_patchgetbuffersize(), plag_processeulerfield(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_copystatbuff(), plag_rflo_findgridmapping(), plag_rflo_modstats::plag_rflo_readstat(), plag_rflo_recvmetrics(), plag_rflo_modstats::plag_rflo_recvstatbuff(), plag_rflo_sendmetrics(), plag_rflo_modstats::plag_rflo_sendstatbuffconf(), plag_rflo_sourcecell(), plag_rflo_modstats::plag_rflo_writestat(), plag_writestattecascii(), radi_allocatememory(), radi_calcefftemp(), radi_diffradflux(), radi_diffradfluxpatch(), radi_diffradintens(), radi_extinctioncoef(), radi_flimconvectivefluxes(), radi_flimdiffflux(), radi_flimdifffluxpatch(), radi_flimemsinit(), radi_flimemsupdate(), radi_flimrkinit(), radi_flimrkupdate(), radi_flimsourceterms(), radi_floflimbconddiffuse(), radi_floflimbcondinjection(), radi_floflimbcondsymmetry(), radi_floflimbcondzerograd(), radi_floflimcentflux(), radi_floflimcentfluxpatch(), radi_floflimcentraldissipation(), radi_floflimcorrcornedgecells(), radi_floflimexchangedummyconf(), radi_floflimexchcornedgecells(), radi_floflimrecvcornedgecells(), radi_floflimrecvdummyvals(), radi_floflimsenddummyconf(), radi_floflimsetcornedgecells(), radi_fluxlimiter(), radi_initgenxinterface(), radi_mixtsourcetermsflim(), radi_peulsourcetermsflim(), radi_plagsourcetermsflim(), radi_rflo_flimressmoothing(), radi_rflo_flimressmoothingcoeff(), radi_rflo_flimspectralradii(), radi_rflo_readsolution(), radi_rflo_writesolution(), rflo_allocatememory(), rflo_modboundaryconditions::rflo_bcondfarfield(), rflo_modboundaryconditions::rflo_bcondinflow(), rflo_modboundaryconditions::rflo_bcondinjection(), rflo_modboundaryconditions::rflo_bcondinjectionapn(), rflo_modboundaryconditions::rflo_bcondinjectioninit(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflow(), rflo_modboundaryconditions::rflo_bcondslipwall(), rflo_modboundaryconditions::rflo_bcondsymmetry(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcforces(), rflo_calcgradconnbc(), rflo_calcgradfaces(), rflo_calcgradphysbc(), rflo_calcmassflow(), rflo_calcthrust(), rflo_calctotalmass(), rflo_centraldissipation(), rflo_centralflux(), rflo_centralfluxpatch(), rflo_checkmetrics(), rflo_checkregionfaces(), rflo_checkvalidity(), rflo_computeintegralvalues(), rflo_copymatrixcorners(), rflo_copymatrixedges(), rflo_copymatrixpatches(), rflo_copyvectorcorners(), rflo_copyvectoredges(), rflo_copyvectorpatches(), rflo_correctcorneredgecells(), rflo_dualtstinit(), rflo_dualtstpredict(), rflo_dualtstshift(), rflo_dualtststerm(), rflo_exchangecorneredgecells(), rflo_exchangedummyconf(), rflo_extrapintcellscal(), rflo_extrapintcellvec(), rflo_findthrustpatches(), rflo_getboundaryvalues(), rflo_getflowsolution(), rflo_gridremesh(), rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_modlaplacesmoothing::rflo_laplacegridortho1(), rflo_modlaplacesmoothing::rflo_laplacegridortho2(), rflo_openprobefile(), rflo_readsolution(), rflo_readsolutionregion(), rflo_readstat(), rflo_readstatregion(), rflo_receivecorneredgecells(), rflo_receivedummyvals(), rflo_residualnorm(), rflo_residualsmoothing(), rflo_residualsmoothingcoeffs(), rflo_roedissipfirst(), rflo_roedissipsecond(), rflo_roefluxfirst(), rflo_roefluxpatch(), rflo_roefluxsecond(), rflo_sendboundaryvalues(), rflo_sendboundaryvaluesalpha(), rflo_senddummyconf(), rflo_setcorneredgecells(), rflo_sourcecell(), rflo_modstatsboundaryconditions::rflo_statbcondcopy(), rflo_modstatsboundaryconditions::rflo_statbcondextrap(), rflo_modstatsboundaryconditions::rflo_statbcondnegate(), rflo_timestepinviscid(), rflo_timestepviscous(), rflo_viscousflux(), rflo_viscousfluxpatch(), rflo_modvolmeshsmoothing::rflo_vmsprojectvertices(), rflo_writesolution(), rflo_writesolutionregion(), rflo_writestat(), rflo_zerodummycells(), rkinitmp(), rkupdatemp(), rocflo_post(), rocvav_post(), rvav_blasiussolution(), rvav_computeanalyticalsolution(), rvav_extractvariables(), rvav_gammbumpsolution(), rvav_proudmanculicksolution(), rvav_readfilestream1(), rvav_readfilestream2(), rvav_readfilestream2comput(), sourceterms(), modstatsroutines::statdatasampling(), turb_allocatememory(), turb_calcvortic(), turb_coranswalldistov(), turb_coviscousfluxes(), turb_floextrapintcellscal(), turb_floextrapintcellvec(), turb_floextrapolcellvec(), turb_flofacevolume(), turb_flolesgenc2f(), turb_flolesgencocc(), turb_flolesgenfiltcc(), turb_flolesunifiltcc(), turb_floransbcondinflow(), turb_floransbcondinjection(), turb_floransbcondnoslipwall(), turb_floransbcondsymmetry(), turb_floransbcondzerograd(), turb_floranscentraldissipation(), turb_floranscorrcornedgecells(), turb_floransexchangedummyconf(), turb_floransexchcornedgecells(), turb_floransrecvcornedgecells(), turb_floransrecvdummyvals(), turb_floranssacentflux(), turb_floranssacentfluxpatch(), turb_floranssaroe1stflux(), turb_floranssaroe2ndflux(), turb_floranssaroefluxpatch(), turb_floranssenddummyconf(), turb_floranssetcornedgecells(), turb_flowlmmetric(), turb_flowlmupdateloglay(), turb_getmodelstresscell(), turb_gettvcell(), turb_initgenxinterface(), turb_lescalceddyvis(), turb_lesesgmodel4(), turb_ransconvectivefluxes(), turb_ransemsinit(), turb_ransemsupdate(), turb_ransrkinit(), turb_ranssageteddyvis(), turb_ranssasourceterms(), turb_ranssavisflux(), turb_ranssavisfluxpatch(), turb_ranstotaltv(), turb_ranswalldistovpatch(), turb_rflo_ransressmoothing(), turb_rflo_ransressmoothingcoeff(), turb_rflo_ransspectralradii(), turb_rflo_readsolution(), turb_rflo_readsolutionregion(), turb_rflo_writesolution(), turb_statccollector(), turb_vfluxhybrid(), turb_vfluxhybridpatch(), turb_visfluxeddy(), turb_visfluxeddypatch(), turb_wlmfluxpatch(), turb_wlminitia(), turb_wlmreyanalogy(), updatedependentvarsmp(), writegeneric(), writeprobe(), writetecplotascii(), and writetecplotbinary().
subroutine rflo_getcornercellsindices (type(t_region) region, integer iLev, integer icorner, integer icbeg, integer icend, integer jcbeg, integer jcend, integer kcbeg, integer kcend)
Definition at line 424 of file RFLO_GetDimensions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), icbeg, icend, icorner, idcbeg, idcend, ipcbeg, ipcend, jcbeg, jcend, jdcbeg, jdcend, jpcbeg, jpcend, kcbeg, kdcbeg, kpcbeg, moderror::registerfunction(), rflo_getdimensdummy(), and rflo_getdimensphys().
Referenced by peul_exchangecorneredgecells(), peul_receivecorneredgecells(), plag_cecellsexchange(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_cecellsgetbuffersize(), plag_corncellsloaddata(), plag_rflo_findgridmapping(), plag_rflo_recvmetrics(), plag_rflo_sendmetrics(), radi_floflimexchcornedgecells(), radi_floflimrecvcornedgecells(), rflo_c2eavgcoeffsdegec(), rflo_c2favgcoeffsdegec(), rflo_copymatrixcorners(), rflo_copyvectorcorners(), rflo_exchangecorneredgecells(), rflo_findsourceregions(), rflo_receivecorneredgecells(), turb_floransexchcornedgecells(), and turb_floransrecvcornedgecells().
subroutine rflo_getdimensdummy (type(t_region) region, integer iLev, integer idcbeg, integer idcend, integer jdcbeg, integer jdcend, integer kdcbeg, integer kdcend)
Definition at line 67 of file RFLO_GetDimensions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, and moderror::registerfunction().
Referenced by convectivefluxes(), explicitmultistage(), initializeflowfield(), inrt_vaporenergyconversion(), peri_allocatememory(), peul_allocatememory(), peul_convectivefluxes(), peul_correctcorneredgecells(), peul_readsolution(), peul_readsolutionregion(), peul_rocflo_post(), peul_setcorneredgecells(), peul_spectralradii(), peul_writesolution(), plag_modeulerian::plag_calceulerianfield(), plag_cecellsgetbuffersize(), plag_modeulerian::plag_createeulerianfield(), plag_modstats::plag_createstat(), plag_modeulerian::plag_initeulerianfield(), plag_modstats::plag_initstat(), plag_intrpmixtproperties(), plag_processeulerfield(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_readstat(), plag_rflo_modstats::plag_rflo_writestat(), plag_writestattecascii(), radi_allocatememory(), radi_calcefftemp(), radi_diffradflux(), radi_diffradintens(), radi_extinctioncoef(), radi_flimconvectivefluxes(), radi_flimemsinit(), radi_flimemsupdate(), radi_flimrkinit(), radi_flimrkupdate(), radi_flimsourceterms(), radi_floflimcorrcornedgecells(), radi_floflimsetcornedgecells(), radi_fluxlimiter(), radi_initgenxinterface(), radi_mixtsourcetermsflim(), radi_peulsourcetermsflim(), radi_plagsourcetermsflim(), radi_rflo_flimspectralradii(), radi_rflo_readsolution(), radi_rflo_writesolution(), rflo_allocatememory(), rflo_c2eavgcoeffs(), rflo_c2favgcoeffs(), rflo_calccontrolvolumes(), rflo_checkmetrics(), rflo_copymatrixcorners(), rflo_copyvectorcorners(), rflo_correctcorneredgecells(), rflo_dualtstinit(), rflo_dualtstpredict(), rflo_dualtstshift(), rflo_dualtststerm(), rflo_extrapintcellscal(), rflo_extrapintcellvec(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getedgecellsindices(), rflo_getflowsolution(), rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_readsolution(), rflo_readsolutionregion(), rflo_readstat(), rflo_readstatregion(), rflo_setcorneredgecells(), rflo_timestepinviscid(), rflo_timestepviscous(), rflo_writesolution(), rflo_writesolutionregion(), rflo_writestat(), rflo_zerodummycells(), rkinitmp(), rkupdatemp(), rocflo_post(), rocvav_post(), rvav_blasiussolution(), rvav_computeanalyticalsolution(), rvav_gammbumpsolution(), rvav_proudmanculicksolution(), rvav_readfilestream1(), rvav_readfilestream2(), rvav_readfilestream2comput(), sourceterms(), modstatsroutines::statdatasampling(), turb_allocatememory(), turb_calcvortic(), turb_checkparaminput(), turb_coviscousfluxes(), turb_floextrapintcellscal(), turb_floextrapintcellvec(), turb_floextrapolcellvec(), turb_flofacewidth(), turb_flolesgenc2f(), turb_flolesgencocc(), turb_flolesgenfiltcc(), turb_flolesunifiltcc(), turb_floranscorrcornedgecells(), turb_floranssetcornedgecells(), turb_getmodelstresscell(), turb_gettvcell(), turb_initgenxinterface(), turb_ransconvectivefluxes(), turb_ransemsinit(), turb_ransemsupdate(), turb_ransrkinit(), turb_ranssageteddyvis(), turb_ranssasourceterms(), turb_ranstotaltv(), turb_rflo_ransspectralradii(), turb_rflo_readsolution(), turb_rflo_readsolutionregion(), turb_rflo_writesolution(), turb_statccollector(), and updatedependentvarsmp().
subroutine rflo_getdimensdummynodes (type(t_region) region, integer iLev, integer idnbeg, integer idnend, integer jdnbeg, integer jdnend, integer kdnbeg, integer kdnend)
Definition at line 151 of file RFLO_GetDimensions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, and moderror::registerfunction().
Referenced by checkindxrange(), convertflo2flumesh(), descalegridspeeds(), genxinitsolution(), getgrid(), peul_allocatememory(), peul_rocflo_post(), peul_sourceeqeul(), plag_allocatememory(), plag_calcfacecentroids(), plag_copyfacevectors(), plag_initgenxinterface(), plag_processeulerfield(), plag_writestattecascii(), radi_allocatememory(), rflo_allocatememory(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_copyedgefacenorm(), rflo_copyedgefaceparal(), rflo_copygeometrydummy(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs3d(), rflo_getnodeoffset(), rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad3d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_modgridcontrolmap::rflo_gridphysgrad3d(), rflo_initavgcoeffs(), rflo_initgenxinterface(), rflo_initgenxinterfaceprep(), rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_modlaplacesmoothing::rflo_laplacegridortho1(), rflo_modlaplacesmoothing::rflo_laplacegridortho2(), rflo_modlaplacesmoothing::rflo_laplacegridsolve(), rflo_laplacegridsolve(), rflo_modvolmeshsmoothing::rflo_vmslaplaceperturb(), rflo_modvolmeshsmoothing::rflo_vmslaplaceprocedure(), rflo_modvolmeshsmoothing::rflo_vmsprojectvertices(), rocflo_2dto3d(), rocflo_blocks(), rocflo_post(), rocflo_split(), rocflo_surf(), rocvav_post(), rvav_readfilestream1(), rvav_readfilestream2(), rvav_readfilestream2comput(), scalegridspeeds(), splitgrid(), turb_allocatememory(), turb_coviscousfluxes(), turb_floextrapolfacevec(), turb_flofacevolume(), turb_flolesaverageface(), turb_flolesgencocc(), turb_flolesgencoff(), turb_flolesgenfiltff(), turb_flolesunifiltff(), turb_initsolution(), turb_lescontract(), turb_leshij(), turb_leslij(), and turb_lesmij().
subroutine rflo_getdimensphys (type(t_region) region, integer iLev, integer ipcbeg, integer ipcend, integer jpcbeg, integer jpcend, integer kpcbeg, integer kpcend)
Definition at line 109 of file RFLO_GetDimensions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), ipcbeg, ipcend, jpcbeg, jpcend, kpcbeg, and moderror::registerfunction().
Referenced by inrt_twodimaverage(), peri_cnlforceterm(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_cocprslowterms(), peri_copgradupdate(), peul_centraldissipation(), peul_centralflux(), peul_correctcorneredgecells(), peul_enforcepositivity(), peul_residualsmoothing(), peul_residualsmoothingcoeffs(), peul_setcorneredgecells(), peul_sourceeqeul(), peul_spectralradii(), plag_cecellsgetbuffersize(), plag_corncellsloaddata(), plag_edgecellsloaddata(), plag_getcellindices(), plag_getcellindicesoutflow(), plag_incelltestrobust(), plag_intrpmixtproperties(), plag_patchloaddatabuffers(), plag_patchremovedataoutflow(), plag_processeulerfield(), plag_rflo_findsourcecell(), plag_rflo_sourcecell(), plag_wallbounce(), plag_writestattecascii(), radi_diffradflux(), radi_extinctioncoef(), radi_flimdiffflux(), radi_floflimcentflux(), radi_floflimcentraldissipation(), radi_floflimcorrcornedgecells(), radi_floflimsetcornedgecells(), radi_rflo_flimressmoothing(), radi_rflo_flimressmoothingcoeff(), radi_rflo_flimspectralradii(), rflo_modgridregionshape::rflo_blockskewedcell(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcgradconnbc(), rflo_calcgradvector(), rflo_calctotalmass(), rflo_centraldissipation(), rflo_centralflux(), rflo_checkmetrics(), rflo_checkregionfaces(), rflo_checkvalidity(), rflo_computeintegralvalues(), rflo_copymatrixcorners(), rflo_copymatrixedges(), rflo_copyvectorcorners(), rflo_copyvectoredges(), rflo_correctcorneredgecells(), rflo_dualtstpredict(), rflo_findsourcecell(), rflo_findsourcecellinvert(), rflo_findsourceregions(), rflo_getcornercellsindices(), rflo_getedgecellsindices(), rflo_getpatchindices(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_openprobefile(), rflo_residualnorm(), rflo_residualsmoothing(), rflo_residualsmoothingcoeffs(), rflo_roedissipfirst(), rflo_roedissipsecond(), rflo_roefluxfirst(), rflo_roefluxsecond(), rflo_setcorneredgecells(), rflo_sourcecell(), rflo_timestepinviscid(), rflo_timestepviscous(), rflo_viscousflux(), rflo_zerodummycells(), rvav_blasiussolution(), rvav_computeanalyticalsolution(), rvav_gammbumpsolution(), rvav_proudmanculicksolution(), turb_coranswalldistov(), turb_flolesgenc2f(), turb_floranscentraldissipation(), turb_floranscorrcornedgecells(), turb_floranssacentflux(), turb_floranssaroe1stflux(), turb_floranssaroe2ndflux(), turb_floranssetcornedgecells(), turb_getmodelstresscell(), turb_gettvcell(), turb_lescalceddyvis(), turb_lesesgmodel4(), turb_ranssavisflux(), turb_rflo_ransressmoothing(), turb_rflo_ransressmoothingcoeff(), turb_rflo_ransspectralradii(), turb_vfluxhybrid(), turb_visfluxeddy(), and writeprobe().
subroutine rflo_getdimensphysnodes (type(t_region) region, integer iLev, integer ipnbeg, integer ipnend, integer jpnbeg, integer jpnend, integer kpnbeg, integer kpnend)
Definition at line 193 of file RFLO_GetDimensions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, and moderror::registerfunction().
Referenced by convertflo2flumesh(), peri_initsolution(), peul_readsolution(), peul_readsolutionregion(), peul_writesolution(), plag_incelltestrobust(), plag_processeulerfield(), plag_writestattecascii(), rflo_allocatememory(), rflo_arclengthbounds(), rflo_boundarydeformation(), rflo_calcgradfaces(), rflo_calcgridspeeds(), rflo_changeinteriorgrid(), rflo_copyedgefacenorm(), rflo_copyedgefaceparal(), rflo_copygeometrydummy(), rflo_edgedeformation(), rflo_edgedeformationstraight(), rflo_modelliptsmoothing::rflo_elliptgridgauss3d(), rflo_modelliptsmoothing::rflo_elliptgridjac3d(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modelliptsmoothing::rflo_elliptgridsmooregion(), rflo_modelliptsmoothing::rflo_elliptgridsor3d(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs2d(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs3d(), rflo_generatecoarsegrids(), rflo_getdeformation(), rflo_getpatchindicesnodes(), rflo_modgridcontrolmap::rflo_gridcontrolmap2d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_gridremesh(), rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_modlaplacesmoothing::rflo_laplacegridortho1(), rflo_modlaplacesmoothing::rflo_laplacegridortho2(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsolve(), rflo_laplacegridsolve(), rflo_moddegeneratecornedge::rflo_markdegeneratvert(), rflo_modmovegridelliptfra::rflo_mgelliptboundaries(), rflo_modmovegridelliptfra::rflo_mgelliptedgesfra(), rflo_modmovegridelliptglo::rflo_mgelliptedgesglo(), rflo_modmovegridframe::rflo_mgframebnddeformation(), rflo_modmovegridframe::rflo_mgframebnddeformation0(), rflo_modmovegridframe::rflo_mgframebroadcast(), rflo_modmovegridframe::rflo_mgframecornpoints(), rflo_modmovegridframe::rflo_mgframeedges(), rflo_modmovegridframe::rflo_mgframeedgeso(), rflo_modmovegridframe::rflo_mgframemovecorners(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_readbcinflowvelsection(), rflo_readgrid(), rflo_readgridregion(), rflo_readsolution(), rflo_readsolutionregion(), rflo_modvolmeshsmoothing::rflo_vmsaveragevertices(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rflo_modvolmeshsmoothing::rflo_vmslaplaceperturb(), rflo_modvolmeshsmoothing::rflo_vmsprojectvertices(), rflo_writegrid(), rflo_writegridregion(), rflo_writesolution(), rflo_writesolutionregion(), rocflo_2dto3d(), rocflo_blocks(), rocflo_post(), turb_flolesaverageface(), writegeneric(), writetecplotascii(), and writetecplotbinary().
subroutine rflo_getedgecellsindices (type(t_region) region, integer iLev, integer iedge, integer iebeg, integer ieend, integer jebeg, integer jeend, integer kebeg, integer keend)
Definition at line 299 of file RFLO_GetDimensions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), idcbeg, idcend, ieend, ipcbeg, ipcend, jdcbeg, jdcend, jebeg, jeend, jpcbeg, jpcend, kdcbeg, kebeg, kpcbeg, moderror::registerfunction(), rflo_getdimensdummy(), and rflo_getdimensphys().
Referenced by peul_exchangecorneredgecells(), peul_receivecorneredgecells(), plag_cecellsexchange(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_cecellsgetbuffersize(), plag_edgecellsloaddata(), plag_rflo_findgridmapping(), plag_rflo_recvmetrics(), plag_rflo_sendmetrics(), radi_floflimexchcornedgecells(), radi_floflimrecvcornedgecells(), rflo_c2eavgcoeffsdegec(), rflo_c2favgcoeffsdegec(), rflo_copymatrixcorners(), rflo_copymatrixedges(), rflo_copyvectorcorners(), rflo_copyvectoredges(), rflo_exchangecorneredgecells(), rflo_moddegeneratecornedge::rflo_finddegeneratcell(), rflo_findsourceregions(), rflo_receivecorneredgecells(), turb_floransexchcornedgecells(), and turb_floransrecvcornedgecells().
subroutine rflo_getnodeoffset (type(t_region) region, integer iLev, integer iNodeOffset, integer ijNodeOffset)
Definition at line 267 of file RFLO_GetDimensions.F90.
References moderror::deregisterfunction(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, moderror::registerfunction(), and rflo_getdimensdummynodes().
Referenced by prep_modbcdistribution::bcinflowveldistrib(), checkindxrange(), convertflo2flumesh(), convertflo2flupatch(), descalegridspeeds(), genxinitsolution(), getgrid(), initializeflowfield(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_copgradupdate(), peri_initsolution(), peul_allocatememory(), peul_centralflux(), peul_centralfluxpatch(), peul_readsolution(), peul_readsolutionregion(), peul_rocflo_post(), peul_sourceeqeul(), peul_spectralradii(), peul_writesolution(), plag_allocatememory(), plag_calcfacecentroids(), plag_cecellsfacecentroids(), plag_cecellsfacevectors(), plag_copyfacevectors(), plag_getcellindices(), plag_getcellindicesoutflow(), plag_incelltestrobust(), plag_injcejectparticle(), plag_injctilecalcrhs(), plag_injctileinitialize(), plag_patchgetbuffersize(), plag_processeulerfield(), plag_rflo_findgridmapping(), plag_rflo_recvmetrics(), plag_rflo_sendmetrics(), plag_wallbounce(), plag_writestattecascii(), radi_allocatememory(), radi_diffradflux(), radi_diffradfluxpatch(), radi_flimdiffflux(), radi_flimdifffluxpatch(), radi_floflimcentflux(), radi_floflimcentfluxpatch(), radi_fluxlimiter(), radi_rflo_flimspectralradii(), radi_rflo_writesolution(), rflo_allocatememory(), rflo_arclengthbounds(), rflo_modgridmetrics::rflo_arclengthpatch(), rflo_modboundaryconditions::rflo_bcondfarfield(), rflo_modboundaryconditions::rflo_bcondinflow(), rflo_modboundaryconditions::rflo_bcondinjection(), rflo_modboundaryconditions::rflo_bcondinjectionapn(), rflo_modboundaryconditions::rflo_bcondinjectioninit(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflow(), rflo_modgridregionshape::rflo_blockskewedcell(), rflo_boundarydeformation(), rflo_c2eavgcoeffs(), rflo_c2eavgcoeffsdegec(), rflo_c2favgcoeffs(), rflo_c2favgcoeffsdegec(), rflo_c2favgcoeffsdummyconn(), rflo_c2favgcoeffsdummyphys(), rflo_c2favgcoeffspatch(), rflo_calccellcentroids(), rflo_calccontrolvolumes(), rflo_calcfacecentroids(), rflo_calcfacevectors(), rflo_calcforces(), rflo_calcgradconnbc(), rflo_calcgraddummyconn(), rflo_calcgraddummyphys(), rflo_calcgraddummysymm(), rflo_calcgradfaces(), rflo_calcgradphysbc(), rflo_calcgridspeeds(), rflo_calcmassflow(), rflo_calcthrust(), rflo_centralflux(), rflo_centralfluxpatch(), rflo_changeinteriorgrid(), rflo_checkmetrics(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_copyedgefacenorm(), rflo_copyedgefaceparal(), rflo_copygeometrydummy(), rflo_copymatrixcorners(), rflo_copyvectorcorners(), rflo_correctcorneredgecells(), rflo_edgedeformation(), rflo_edgedeformationstraight(), rflo_modelliptsmoothing::rflo_elliptgridgauss2d(), rflo_modelliptsmoothing::rflo_elliptgridgauss3d(), rflo_modelliptsmoothing::rflo_elliptgridjac2d(), rflo_modelliptsmoothing::rflo_elliptgridjac3d(), rflo_modelliptsmoothing::rflo_elliptgridpatch(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modelliptsmoothing::rflo_elliptgridsmooregion(), rflo_modelliptsmoothing::rflo_elliptgridsor2d(), rflo_modelliptsmoothing::rflo_elliptgridsor3d(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs2d(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs3d(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangegeometrycopy(), rflo_exchangegeometrylevels(), rflo_exchangegeometryprepare(), rflo_exchangegeometryrecv(), rflo_exchangegeometrysend(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_findthrustpatches(), rflo_generatecoarsegrids(), rflo_getdeformation(), rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad3d(), rflo_modgridcontrolmap::rflo_gridcontrolmap2d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_modgridregionshape::rflo_gridflatpatch(), rflo_modgridcontrolmap::rflo_gridphysgrad2d(), rflo_modgridcontrolmap::rflo_gridphysgrad3d(), rflo_gridremesh(), rflo_initavgcoeffs(), rflo_modlaplacesmoothing::rflo_laplacegridjump(), rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_modlaplacesmoothing::rflo_laplacegridortho1(), rflo_modlaplacesmoothing::rflo_laplacegridortho2(), rflo_modlaplacesmoothing::rflo_laplacegridpatch(), rflo_laplacegridpatch(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsolve(), rflo_laplacegridsolve(), rflo_moddegeneratecornedge::rflo_markdegeneratvert(), rflo_modmovegridelliptfra::rflo_mgelliptboundaries(), rflo_modmovegridelliptfra::rflo_mgelliptedgesfra(), rflo_modmovegridelliptglo::rflo_mgelliptedgesglo(), rflo_modmovegridframe::rflo_mgframebnddeformation(), rflo_modmovegridframe::rflo_mgframebnddeformation0(), rflo_modmovegridframe::rflo_mgframebroadcast(), rflo_modmovegridframe::rflo_mgframecornpoints(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframeedges(), rflo_modmovegridframe::rflo_mgframeedgeso(), rflo_modmovegridframe::rflo_mgframemovecorners(), rflo_modmovegridframe::rflo_mgframerestoreexternal(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_modmovegridframe::rflo_mgframesurfaces(), rflo_modmovegridutil::rflo_movegridcurvedpatch(), rflo_modmovegridutil::rflo_movegridqflatpatch(), rflo_openprobefile(), rflo_readgrid(), rflo_readgridregion(), rflo_readsolution(), rflo_readsolutionregion(), rflo_roedissipfirst(), rflo_roedissipsecond(), rflo_roefluxfirst(), rflo_roefluxpatch(), rflo_roefluxsecond(), rflo_sendboundaryvalues(), rflo_timestepinviscid(), rflo_timestepviscous(), rflo_viscousflux(), rflo_viscousfluxpatch(), rflo_modvolmeshsmoothing::rflo_vmsaveragevertices(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rflo_modvolmeshsmoothing::rflo_vmslaplaceperturb(), rflo_modvolmeshsmoothing::rflo_vmslaplaceprocedure(), rflo_modvolmeshsmoothing::rflo_vmsprojectvertices(), rflo_modvolmeshsmoothing::rflo_vmsrestorebounddeform(), rflo_writegrid(), rflo_writegridregion(), rflo_writesolution(), rflo_writesolutionregion(), rocflo_2dto3d(), rocflo_blocks(), rocflo_post(), rocflo_split(), rocflo_surf(), rocvav_post(), rvav_readfilestream1(), rvav_readfilestream2(), rvav_readfilestream2comput(), scalegridspeeds(), splitgrid(), turb_allocatememory(), turb_calcvortic(), turb_coranswalldistov(), turb_coviscousfluxes(), turb_floextrapolfacevec(), turb_flofacevolume(), turb_flofacewidth(), turb_flofacewidthdummyconn(), turb_flofacewidthdummyphys(), turb_flolesaverageface(), turb_flolesgenc2f(), turb_flolesgencocc(), turb_flolesgencoff(), turb_flolesgenfiltff(), turb_flolesunifiltff(), turb_floranssacentflux(), turb_floranssacentfluxpatch(), turb_floranssaroe1stflux(), turb_floranssaroe2ndflux(), turb_floranssaroefluxpatch(), turb_flowlmmetric(), turb_getmodelstresscell(), turb_gettvcell(), turb_initsolution(), turb_lescalceddyvis(), turb_lescontract(), turb_leshij(), turb_leslij(), turb_lesmij(), turb_ranssavisflux(), turb_ranssavisfluxpatch(), turb_ranswalldistovpatch(), turb_rflo_ransspectralradii(), turb_vfluxhybrid(), turb_vfluxhybridpatch(), turb_visfluxeddy(), turb_visfluxeddypatch(), turb_wlmfluxpatch(), writesurfacegrid(), writetecplotascii(), and writetecplotbinary().