Rocstar: RFLO_LaplaceGridSmoo.F90 File Reference
RFLO_LaplaceGridSmoo.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_laplacegridsmoo (regions, resid)
Function/Subroutine Documentation
subroutine rflo_laplacegridsmoo (type(t_region), dimension(:), pointer regions, real(rfreal) resid)
Definition at line 45 of file RFLO_LaplaceGridSmoo.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), setup_py::grid(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_calcfacevectors(), rflo_changeinteriorgrid(), rflo_clearsendrequests(), rflo_copygeometrydummy(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_generatecoarsegrids(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_laplacegridpatch(), and rflo_laplacegridsolve().
Referenced by rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), and rflo_modvolmeshsmoothing::rflo_movegridvms().