Rocstar: RFLO_CalcGradFaces.F90 File Reference
RFLO_CalcGradFaces.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_calcgradfaces (region, ilev, iBegV, iEndV, iBegG, iEndG, var, gradi, gradj, gradk)
subroutine rflo_copyedgegrad
Function/Subroutine Documentation
subroutine rflo_calcgradfaces (type(t_region) region, integer ilev, integer iBegV, integer iEndV, integer iBegG, integer iEndG, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer gradi, real(rfreal), dimension(:,:), pointer gradj, real(rfreal), dimension(:,:), pointer gradk)
Definition at line 54 of file RFLO_CalcGradFaces.F90.
References moderror::deregisterfunction(), gradi(), gradj(), i, j, k, moderror::registerfunction(), rflo_copyedgegrad(), rflo_getcelloffset(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_calcgradvector().
subroutine rflo_calcgradfaces::rflo_copyedgegrad ()
Definition at line 406 of file RFLO_CalcGradFaces.F90.
References gradi(), gradj(), i, j, and k.
Referenced by rflo_calcgradfaces().