Rocstar: RFLO_EdgeDeformationStraight.F90 File Reference
RFLO_EdgeDeformationStraight.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_edgedeformationstraight (region, boundMoved, edgeStraight, edgeMoved, arcLen12, arcLen34, arcLen56, xyzOrig, xyzOld, dNode)
Function/Subroutine Documentation
subroutine rflo_edgedeformationstraight (type(t_region) region, logical, dimension(6) boundMoved, logical, dimension(12) edgeStraight, logical, dimension(12) edgeMoved, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56, real(rfreal), dimension(:,:), pointer xyzOrig, real(rfreal), dimension(:,:), pointer xyzOld, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 53 of file RFLO_EdgeDeformationStraight.F90.
References moderror::deregisterfunction(), ipnbeg, ipnend, jpnbeg, jpnend, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_tfint1d(), s, and sqrt().
Referenced by rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptsurfacesglo(), and rflo_movegridsurfaces().