Rocstar: RFLO_RoeDissipFirst.F90 File Reference
RFLO_RoeDissipFirst.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_roedissipfirst (region)
real(rfreal) function entropy_corr1 (z, d)
Function/Subroutine Documentation
real(rfreal) function rflo_roedissipfirst::entropy_corr1 (real(rfreal) z, real(rfreal) d)
Definition at line 428 of file RFLO_RoeDissipFirst.F90.
References Plane_3< R, T >::d(), and z.
Referenced by rflo_roedissipfirst().
subroutine rflo_roedissipfirst (type(t_region) region)
Definition at line 44 of file RFLO_RoeDissipFirst.F90.
References Direction_2< R, T >::delta(), moderror::deregisterfunction(), entropy_corr1(), i, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getnodeoffset(), and sqrt().
Referenced by numericaldissipation().