Rocstar: RFLO_GetUserInput.F90 File Reference
RFLO_GetUserInput.F90 File Reference
Functions/Subroutines
subroutine rflo_getuserinput (regions)
Function/Subroutine Documentation
subroutine rflo_getuserinput (type (t_region), dimension(:), pointer regions)
Definition at line 44 of file RFLO_GetUserInput.F90.
References moderror::deregisterfunction(), inrt_userinput(), peri_userinput(), peul_userinput(), plag_userinput(), modinterfacesradiation::RADI_UserInput::radi_userinput(), moderror::registerfunction(), rflo_checkbcinput(), rflo_checkderiveduserinput(), rflo_copytopologylevels(), rflo_printuserinput(), rflo_readtbcinputfile(), rflo_userinput(), spec_userinput(), and turb_userinput().
Referenced by rflo_initflowsolver().