Rocstar: RFLO_SetCornerEdgeCells.F90 File Reference
RFLO_SetCornerEdgeCells.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_setcorneredgecells (region)
subroutine rflo_averageedgecells (ijkD, ijkC1, ijkC2, gasModel, cv, region)
Function/Subroutine Documentation
subroutine rflo_setcorneredgecells::rflo_averageedgecells (integer ijkD, integer ijkC1, integer ijkC2, integer gasModel, real(rfreal), dimension(:,:), pointer cv, type(t_region) region)
Definition at line 201 of file RFLO_SetCornerEdgeCells.F90.
References mixtureproperties().
Referenced by rflo_setcorneredgecells().
subroutine rflo_setcorneredgecells (type(t_region) region)
Definition at line 46 of file RFLO_SetCornerEdgeCells.F90.
References moderror::deregisterfunction(), i, idcbeg, idcend, ipcbeg, ipcend, j, jdcbeg, jdcend, jpcbeg, jpcend, k, kdcbeg, kpcbeg, moderror::registerfunction(), rflo_averageedgecells(), rflo_getcelloffset(), rflo_getdimensdummy(), and rflo_getdimensphys().
Referenced by rflo_modboundaryconditions::rflo_boundaryconditionsrecv().