Rocstar: RFLO_CopyMatrixDummy.F90 File Reference
RFLO_CopyMatrixDummy.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_copymatrixpatches (iLev, region, mat)
subroutine rflo_copymatrixedges (iLev, region, mat)
subroutine rflo_copymatrixcorners (iLev, region, mat)
Function/Subroutine Documentation
subroutine rflo_copymatrixcorners (integer iLev, type(t_region) region, real(rfreal), dimension(:,:), pointer mat)
Definition at line 199 of file RFLO_CopyMatrixDummy.F90.
References moderror::deregisterfunction(), i, ibeg, iend, ipcbeg, ipcend, j, jbeg, jend, jpcbeg, jpcend, k, kbeg, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getdimensdummy(), rflo_getdimensphys(), rflo_getedgecellsindices(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and volumehexa().
Referenced by peul_spectralradii(), radi_rflo_flimspectralradii(), rflo_timestepinviscid(), rflo_timestepviscous(), and turb_rflo_ransspectralradii().
subroutine rflo_copymatrixedges (integer iLev, type(t_region) region, real(rfreal), dimension(:,:), pointer mat)
Definition at line 126 of file RFLO_CopyMatrixDummy.F90.
References moderror::deregisterfunction(), i, ibeg, iend, ipcbeg, ipcend, j, jbeg, jend, jpcbeg, jpcend, k, kbeg, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), and rflo_getedgecellsindices().
Referenced by peul_spectralradii(), radi_rflo_flimspectralradii(), rflo_timestepinviscid(), rflo_timestepviscous(), and turb_rflo_ransspectralradii().
subroutine rflo_copymatrixpatches (integer iLev, type(t_region) region, real(rfreal), dimension(:,:), pointer mat)
Definition at line 54 of file RFLO_CopyMatrixDummy.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by peul_spectralradii(), radi_rflo_flimspectralradii(), rflo_timestepinviscid(), rflo_timestepviscous(), and turb_rflo_ransspectralradii().