Rocstar: RFLO_ReadStatRegion.F90 File Reference
RFLO_ReadStatRegion.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_readstatregion (iReg, regions)
Function/Subroutine Documentation
subroutine rflo_readstatregion (integer iReg, type(t_region), dimension(:), pointer regions)
Definition at line 49 of file RFLO_ReadStatRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, idcbeg, idcend, j, jdcbeg, jdcend, k, kdcbeg, max(), COM_exception::msg(), n, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_readdatafileint(), rflo_readdatafilereal(), and Attribute::status().
Referenced by rocflo_post().