Rocstar: RFLO_CalcGradConnBc.F90 File Reference
RFLO_CalcGradConnBc.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_calcgradconnbc (region, patch, iConBc, iBegV, iEndV, iBegG, iEndG, var, gradi, gradj, gradk)
subroutine rflo_setindexrange
subroutine rflo_calcsidegrad
subroutine rflo_copypatchedgegrad
Function/Subroutine Documentation
subroutine rflo_calcgradconnbc (type(t_region) region, type(t_patch) patch, integer, dimension(6) iConBc, integer iBegV, integer iEndV, integer iBegG, integer iEndG, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer gradi, real(rfreal), dimension(:,:), pointer gradj, real(rfreal), dimension(:,:), pointer gradk)
Definition at line 57 of file RFLO_CalcGradConnBc.F90.
References moderror::deregisterfunction(), gradi(), gradj(), ibeg, idir, iend, ipcbeg, ipcend, jbeg, jdir, jend, jpcbeg, jpcend, kbeg, kdir, kpcbeg, moderror::registerfunction(), rflo_calcsidegrad(), rflo_copypatchedgegrad(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and rflo_setindexrange().
Referenced by rflo_calcgradvector().
subroutine rflo_calcgradconnbc::rflo_calcsidegrad ()
Definition at line 190 of file RFLO_CalcGradConnBc.F90.
References gradi(), gradj(), i, idir, inode, j, jdir, jnode, k, and kdir.
Referenced by rflo_calcgradconnbc().
subroutine rflo_calcgradconnbc::rflo_copypatchedgegrad ()
Definition at line 565 of file RFLO_CalcGradConnBc.F90.
References gradi(), gradj(), i, ibeg, j, jbeg, k, and kbeg.
Referenced by rflo_calcgradconnbc().
subroutine rflo_calcgradconnbc::rflo_setindexrange ()
Definition at line 168 of file RFLO_CalcGradConnBc.F90.
References ibeg, idir, iend, jbeg, jdir, jend, kbeg, and kdir.
Referenced by rflo_calcgradconnbc().