Rocstar: RFLO_FindSourceRegions.F90 File Reference
RFLO_FindSourceRegions.F90 File Reference
Functions/Subroutines
subroutine rflo_findsourceregions (regions)
Function/Subroutine Documentation
subroutine rflo_findsourceregions (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file RFLO_FindSourceRegions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, ic, icell, icorner, iend, ipcbeg, ipcend, j, jbeg, jc, jend, jpcbeg, jpcend, k, kbeg, kc, kpcbeg, moderror::registerfunction(), rflo_moddegeneratecornedge::rflo_finddegeneratcell(), rflo_findsourcecell(), rflo_findsourcecellinvert(), rflo_getcornercellsindices(), rflo_getdimensphys(), rflo_getedgecellsindices(), and CImg< T >::rotate().
Referenced by rflo_initflowsolver().