Rocstar: RFLO_FindSourceCell.F90 File Reference
RFLO_FindSourceCell.F90 File Reference
Functions/Subroutines
subroutine rflo_findsourcecell (regions, iReg, iLev, ic, jc, kc, icell, found, rotate, iRegSrc)
subroutine rflo_sourcecell (region, regionSrc, patch, patchSrc, iLev, ic, jc, kc, icell, found)
Function/Subroutine Documentation
subroutine rflo_findsourcecell (type(t_region), dimension(:), pointer regions, integer iReg, integer iLev, integer ic, integer jc, integer kc, integer icell, logical found, logical rotate, integer iRegSrc)
Definition at line 52 of file RFLO_FindSourceCell.F90.
References moderror::deregisterfunction(), ibeg, ic, icell, iend, ipcbeg, ipcend, jbeg, jc, jend, jpcbeg, jpcend, kbeg, kc, kpcbeg, moderror::registerfunction(), rflo_getdimensphys(), rflo_getpatchindices(), rflo_sourcecell(), and CImg< T >::rotate().
Referenced by rflo_findsourceregions().
subroutine rflo_sourcecell (type(t_region) region, type(t_region) regionSrc, type(t_patch), pointer patch, type(t_patch), pointer patchSrc, integer iLev, integer ic, integer jc, integer kc, integer icell, logical found)
Definition at line 323 of file RFLO_FindSourceCell.F90.
References moderror::deregisterfunction(), modindexing::getijk(), ibeg, ic, icell, idir, iend, modindexing::indijkmap(), ipcbeg, ipcend, jbeg, jc, jdir, jend, jpcbeg, jpcend, kbeg, kc, kdir, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getpatchdirection(), rflo_getpatchindices(), and rflo_getpatchmapping().
Referenced by rflo_findsourcecell(), and rflo_findsourcecellinvert().