Rocstar: RFLO_ReceiveCornerEdgeCells.F90 File Reference
RFLO_ReceiveCornerEdgeCells.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_receivecorneredgecells (regions, iReg)
Function/Subroutine Documentation
subroutine rflo_receivecorneredgecells (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 46 of file RFLO_ReceiveCornerEdgeCells.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, icorner, iend, j, jbeg, jend, k, kbeg, mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getedgecellsindices(), Ray_2< R, T >::source(), Attribute::status(), and RFC_Data_const< _Tag >::tag().
Referenced by rflo_modboundaryconditions::rflo_boundaryconditionsrecv().