Rocstar: RFLO_WriteDataFile.F90 File Reference
RFLO_WriteDataFile.F90 File Reference
Functions/Subroutines
subroutine rflo_writedatafileint (global, fileId, form, nDim1, nDim2, ivar)
subroutine rflo_writedatafilereal (global, fileId, form, nDim1, nDim2, var)
Function/Subroutine Documentation
subroutine rflo_writedatafileint (type(t_global), pointer global, integer fileId, integer form, integer nDim1, integer nDim2, integer, dimension(:,:) ivar)
Definition at line 50 of file RFLO_WriteDataFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, and moderror::registerfunction().
Referenced by peul_writesolution(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_writestat(), plag_writesolution(), radi_rflo_writesolution(), rflo_writegrid(), rflo_writegridregion(), rflo_modpatchaerocoeffs::rflo_writepatchaerocoeffs(), rflo_writerandomstate(), rflo_writesolution(), rflo_writesolutionregion(), rflo_writestat(), and turb_rflo_writesolution().
subroutine rflo_writedatafilereal (type(t_global), pointer global, integer fileId, integer form, integer nDim1, integer nDim2, real(rfreal), dimension(:,:) var)
Definition at line 99 of file RFLO_WriteDataFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, and moderror::registerfunction().
Referenced by peul_writesolution(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_writestat(), plag_writesolution(), radi_rflo_writesolution(), rflo_writegrid(), rflo_writegridregion(), rflo_modpatchaerocoeffs::rflo_writepatchaerocoeffs(), rflo_writerandomstate(), rflo_writesolution(), rflo_writesolutionregion(), rflo_writestat(), and turb_rflo_writesolution().