Rocstar: RFLO_CheckMetrics.F90 File Reference
RFLO_CheckMetrics.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_checkmetrics (iReg, region)
Function/Subroutine Documentation
subroutine rflo_checkmetrics (integer iReg, type(t_region) region)
Definition at line 45 of file RFLO_CheckMetrics.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, idcbeg, idcend, ipcbeg, ipcend, j, jdcbeg, jdcend, jpcbeg, jpcend, k, kdcbeg, kpcbeg, min(), COM_exception::msg(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensphys(), rflo_getnodeoffset(), sqrt(), and CImg< T >::sum().
Referenced by rflo_modgridmetrics::rflo_calcgridmetrics(), rflo_movegridblocks(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), and rflo_modvolmeshsmoothing::rflo_movegridvms().