Rocstar: RFLO_DoMemoryAllocation.F90 File Reference
RFLO_DoMemoryAllocation.F90 File Reference
Functions/Subroutines
subroutine rflo_domemoryallocation (regions)
Function/Subroutine Documentation
subroutine rflo_domemoryallocation (type (t_region), dimension(:), pointer regions)
Definition at line 43 of file RFLO_DoMemoryAllocation.F90.
References allocatememorywork(), moderror::deregisterfunction(), moderror::errorstop(), peri_allocatememory(), peul_allocatedatabuffers(), peul_allocatememory(), plag_allocatedatabuffers(), plag_allocatememory(), radi_allocatememory(), moderror::registerfunction(), rflo_allocatedatabuffers(), rflo_allocatememory(), turb_allocatememory(), and turb_rflo_ransallocdatabuffers().
Referenced by rflo_initflowsolver().