Rocstar: RFLO_CalcFaceVectors.F90 File Reference
RFLO_CalcFaceVectors.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_calcfacevectors (region)
Function/Subroutine Documentation
subroutine rflo_calcfacevectors (type(t_region) region)
Definition at line 45 of file RFLO_CalcFaceVectors.F90.
References moderror::deregisterfunction(), facevectorquad(), i, idnbeg, idnend, j, jdnbeg, jdnend, k, kdnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), and sqrt().
Referenced by rflo_modgridmetrics::rflo_calcgridmetrics(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modgridregionshape::rflo_findfunkyblocks(), rflo_modlaplacesmoothing::rflo_laplacegridortho(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_movegridblocks(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), and rflo_modvolmeshsmoothing::rflo_vmslaplaceprocedure().