Rocstar: RFLO_GetPatchDimens.F90 File Reference
RFLO_GetPatchDimens.F90 File Reference
Functions/Subroutines
subroutine rflo_getpatchindices (region, patch, iLev, ibeg, iend, jbeg, jend, kbeg, kend)
subroutine rflo_getpatchindicesnodes (region, patch, iLev, ibeg, iend, jbeg, jend, kbeg, kend)
subroutine rflo_getpatchdirection (patch, idir, jdir, kdir)
Function/Subroutine Documentation
subroutine rflo_getpatchdirection (type(t_patch) patch, integer idir, integer jdir, integer kdir)
Definition at line 215 of file RFLO_GetPatchDimens.F90.
References idir, jdir, and kdir.
Referenced by convertflo2flumesh(), peul_bcondinflow(), peul_bcondinjection(), peul_bcondoutflow(), peul_bcondslipwall(), peul_bcondsymmetry(), peul_centralfluxpatch(), peul_correctcorneredgecells(), peul_exchangedummyconf(), plag_appenddatafrombuffers(), plag_bufferdatasend(), plag_getcellindicesoutflow(), plag_injcejectparticle(), plag_injctilecalcrhs(), plag_injctileinitialize(), plag_patchexchangeconf(), plag_patchgetbuffersize(), plag_patchloaddatabuffers(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_copystatbuff(), plag_rflo_sourcecell(), plag_wallbounce(), radi_diffradfluxpatch(), radi_flimdifffluxpatch(), radi_floflimbconddiffuse(), radi_floflimbcondinjection(), radi_floflimbcondsymmetry(), radi_floflimbcondzerograd(), radi_floflimcentfluxpatch(), radi_floflimcorrcornedgecells(), radi_floflimexchangedummyconf(), rflo_modboundaryconditions::rflo_bcondfarfield(), rflo_modboundaryconditions::rflo_bcondinflow(), rflo_modboundaryconditions::rflo_bcondinjection(), rflo_modboundaryconditions::rflo_bcondinjectionapn(), rflo_modboundaryconditions::rflo_bcondinjectioninit(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflow(), rflo_modboundaryconditions::rflo_bcondslipwall(), rflo_modboundaryconditions::rflo_bcondsymmetry(), rflo_c2favgcoeffsdummy(), rflo_c2favgcoeffspatch(), rflo_calcforces(), rflo_calcgradconnbc(), rflo_calcgraddummy(), rflo_calcgradphysbc(), rflo_calcmassflow(), rflo_calcthrust(), rflo_centralfluxpatch(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_copymatrixcorners(), rflo_copymatrixpatches(), rflo_copyvectorcorners(), rflo_copyvectorpatches(), rflo_correctcorneredgecells(), rflo_exchangednodecopy(), rflo_exchangedummyconf(), rflo_exchangegeometrycopy(), rflo_exchangegeometrylevels(), rflo_findthrustpatches(), rflo_roefluxpatch(), rflo_sendboundaryvalues(), rflo_sourcecell(), rflo_modstatsboundaryconditions::rflo_statbcondcopy(), rflo_modstatsboundaryconditions::rflo_statbcondextrap(), rflo_modstatsboundaryconditions::rflo_statbcondnegate(), rflo_viscousfluxpatch(), turb_flofacewidthdummy(), turb_floransbcondinflow(), turb_floransbcondinjection(), turb_floransbcondnoslipwall(), turb_floransbcondsymmetry(), turb_floransbcondzerograd(), turb_floranscorrcornedgecells(), turb_floransexchangedummyconf(), turb_floranssacentfluxpatch(), turb_floranssaroefluxpatch(), turb_flowlmmetric(), turb_flowlmupdateloglay(), turb_ranssavisfluxpatch(), turb_ranswalldistovpatch(), turb_vfluxhybridpatch(), turb_visfluxeddypatch(), turb_wlmfluxpatch(), and turb_wlmreyanalogy().
subroutine rflo_getpatchindices (type(t_region) region, type(t_patch) patch, integer iLev, integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend)
Definition at line 61 of file RFLO_GetPatchDimens.F90.
References moderror::deregisterfunction(), ibeg, iend, ipcbeg, ipcend, jbeg, jend, jpcbeg, jpcend, kbeg, kpcbeg, moderror::registerfunction(), and rflo_getdimensphys().
Referenced by convertflo2flumesh(), convertflo2flupatch(), peul_bcondinflow(), peul_bcondinjection(), peul_bcondoutflow(), peul_bcondslipwall(), peul_bcondsymmetry(), peul_centralfluxpatch(), peul_correctcorneredgecells(), peul_exchangedummyconf(), peul_readbcinjectsection(), peul_receivedummyvals(), peul_senddummyconf(), plag_appenddatafrombuffers(), plag_bufferdatasend(), plag_getcellindicesoutflow(), plag_injcejectparticle(), plag_injctilecalcrhs(), plag_injctileinitialize(), plag_patchexchangeconf(), plag_patchgetbuffersize(), plag_patchloaddatabuffers(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_copystatbuff(), plag_rflo_findsourcecell(), plag_rflo_modstats::plag_rflo_recvstatbuff(), plag_rflo_modstats::plag_rflo_sendstatbuffconf(), plag_rflo_sourcecell(), plag_wallbounce(), radi_diffradfluxpatch(), radi_flimdifffluxpatch(), radi_floflimbconddiffuse(), radi_floflimbcondinjection(), radi_floflimbcondsymmetry(), radi_floflimbcondzerograd(), radi_floflimcentfluxpatch(), radi_floflimcorrcornedgecells(), radi_floflimexchangedummyconf(), radi_floflimrecvdummyvals(), radi_floflimsenddummyconf(), rflo_modboundaryconditions::rflo_bcondfarfield(), rflo_modboundaryconditions::rflo_bcondinflow(), rflo_modboundaryconditions::rflo_bcondinjection(), rflo_modboundaryconditions::rflo_bcondinjectionapn(), rflo_modboundaryconditions::rflo_bcondinjectioninit(), rflo_modboundaryconditions::rflo_bcondnoslipwall(), rflo_modboundaryconditions::rflo_bcondoutflow(), rflo_modboundaryconditions::rflo_bcondslipwall(), rflo_modboundaryconditions::rflo_bcondsymmetry(), rflo_c2favgcoeffsdummy(), rflo_c2favgcoeffspatch(), rflo_calcforces(), rflo_calcgradconnbc(), rflo_calcgraddummy(), rflo_calcgradphysbc(), rflo_calcmassflow(), rflo_calcthrust(), rflo_centralfluxpatch(), rflo_checkregionfaces(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_copymatrixcorners(), rflo_copymatrixpatches(), rflo_copyvectorcorners(), rflo_copyvectorpatches(), rflo_correctcorneredgecells(), rflo_exchangedummyconf(), rflo_moddegeneratecornedge::rflo_finddegeneratcell(), rflo_findsourcecell(), rflo_findsourcecellinvert(), rflo_findthrustpatches(), rflo_getboundaryvalues(), rflo_receivedummyvals(), rflo_roefluxpatch(), rflo_sendboundaryvalues(), rflo_sendboundaryvaluesalpha(), rflo_senddummyconf(), rflo_sourcecell(), rflo_modstatsboundaryconditions::rflo_statbcondcopy(), rflo_modstatsboundaryconditions::rflo_statbcondextrap(), rflo_modstatsboundaryconditions::rflo_statbcondnegate(), rflo_viscousfluxpatch(), turb_flofacewidthdummy(), turb_floransbcondinflow(), turb_floransbcondinjection(), turb_floransbcondnoslipwall(), turb_floransbcondsymmetry(), turb_floransbcondzerograd(), turb_floranscorrcornedgecells(), turb_floransexchangedummyconf(), turb_floransrecvdummyvals(), turb_floranssacentfluxpatch(), turb_floranssaroefluxpatch(), turb_floranssenddummyconf(), turb_flowlmmetric(), turb_flowlmupdateloglay(), turb_ranssavisfluxpatch(), turb_ranswalldistovpatch(), turb_vfluxhybridpatch(), turb_visfluxeddypatch(), turb_wlmfluxpatch(), turb_wlminitia(), turb_wlmreyanalogy(), and turb_wlmtauwallmapping().
subroutine rflo_getpatchindicesnodes (type(t_region) region, type(t_patch) patch, integer iLev, integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend)
Definition at line 138 of file RFLO_GetPatchDimens.F90.
References moderror::deregisterfunction(), ibeg, iend, ipnbeg, ipnend, jbeg, jend, jpnbeg, jpnend, kbeg, kpnbeg, moderror::registerfunction(), and rflo_getdimensphysnodes().
Referenced by prep_modbcdistribution::bcinflowveldistrib(), convertflo2flumesh(), convertflo2flupatch(), genxinitsolution(), getbndverttype(), getgrid(), rflo_modgridmetrics::rflo_arclengthpatch(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_modelliptsmoothing::rflo_elliptgridgauss2d(), rflo_modelliptsmoothing::rflo_elliptgridjac2d(), rflo_modelliptsmoothing::rflo_elliptgridpatch(), rflo_modelliptsmoothing::rflo_elliptgridsor2d(), rflo_exchangednodecopy(), rflo_exchangednoderecv(), rflo_exchangednodesend(), rflo_exchangegeometrycopy(), rflo_exchangegeometrylevels(), rflo_exchangegeometryprepare(), rflo_exchangegeometryrecv(), rflo_exchangegeometrysend(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_findthrustpatches(), rflo_getdeformation(), rflo_modgridregionshape::rflo_gridflatpatch(), rflo_modgridcontrolmap::rflo_gridphysgrad2d(), rflo_modlaplacesmoothing::rflo_laplacegridjump(), rflo_modlaplacesmoothing::rflo_laplacegridpatch(), rflo_laplacegridpatch(), rflo_modmovegridframe::rflo_mgframebnddeformation(), rflo_modmovegridframe::rflo_mgframecornpoints(), rflo_modmovegridframe::rflo_mgframeedges(), rflo_modmovegridframe::rflo_mgframerestoreexternal(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_modmovegridframe::rflo_mgframesurfaces(), rflo_modmovegridutil::rflo_movegridcurvedpatch(), rflo_modmovegridutil::rflo_movegridqflatpatch(), rflo_sendboundaryvalues(), rflo_modvolmeshsmoothing::rflo_vmsrestorebounddeform(), and writesurfacegrid().