Rocstar: RFLO_ExchangeDummyConf.F90 File Reference
RFLO_ExchangeDummyConf.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_exchangedummyconf (region, regionSrc, patch, patchSrc)
Function/Subroutine Documentation
subroutine rflo_exchangedummyconf (type(t_region) region, type(t_region) regionSrc, type(t_patch) patch, type(t_patch) patchSrc)
Definition at line 48 of file RFLO_ExchangeDummyConf.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, modindexing::indijkmap(), j, jbeg, jdir, jend, k, kbeg, kdir, mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and rflo_getpatchmapping().
Referenced by rflo_modboundaryconditions::rflo_boundaryconditionsset().