Rocstar: RFLO_DualTstUtil.F90 File Reference
RFLO_DualTstUtil.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_dualtstinit (regions, timeLevel)
subroutine rflo_dualtstpredict (region)
subroutine rflo_dualtststerm (region)
subroutine rflo_dualtstshift (region)
Function/Subroutine Documentation
subroutine rflo_dualtstinit (type(t_region), dimension(:), pointer regions, integer timeLevel)
Definition at line 50 of file RFLO_DualTstUtil.F90.
References moderror::deregisterfunction(), ic, id(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), and rflo_getdimensdummy().
Referenced by rflo_dualtimestepping().
subroutine rflo_dualtstpredict (type(t_region) region)
Definition at line 158 of file RFLO_DualTstUtil.F90.
References moderror::deregisterfunction(), i, ic, id(), idcbeg, idcend, ipcbeg, ipcend, j, jdcbeg, jdcend, jpcbeg, jpcend, k, kdcbeg, kpcbeg, mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), and rflo_getdimensphys().
Referenced by rflo_dualtimestepping().
subroutine rflo_dualtstshift (type(t_region) region)
Definition at line 418 of file RFLO_DualTstUtil.F90.
References moderror::deregisterfunction(), ic, id(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), and rflo_getdimensdummy().
Referenced by rflo_dualtimestepping().
subroutine rflo_dualtststerm (type(t_region) region)
Definition at line 290 of file RFLO_DualTstUtil.F90.
References moderror::deregisterfunction(), ic, id(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), and rflo_getdimensdummy().
Referenced by rflo_dualtimestepping().