Rocstar: RFLO_ExchangeGeometryLevels.F90 File Reference
RFLO_ExchangeGeometryLevels.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_exchangegeometrylevels (region, iPatch)
Function/Subroutine Documentation
subroutine rflo_exchangegeometrylevels (type(t_region) region, integer iPatch)
Definition at line 45 of file RFLO_ExchangeGeometryLevels.F90.
References moderror::deregisterfunction(), i, idir, j, jdir, k, kdir, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchdirection(), and rflo_getpatchindicesnodes().
Referenced by rflo_exchangegeometry().