Rocstar: RFLO_ExchangeDnodeRecv.F90 File Reference
RFLO_ExchangeDnodeRecv.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_exchangednoderecv (region, regionSrc, patch, patchSrc, average, dNode)
Function/Subroutine Documentation
subroutine rflo_exchangednoderecv (type(t_region) region, type(t_region) regionSrc, type(t_patch) patch, type(t_patch) patchSrc, logical average, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 51 of file RFLO_ExchangeDnodeRecv.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), Ray_2< R, T >::source(), Attribute::status(), and RFC_Data_const< _Tag >::tag().
Referenced by rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_modmovegridelliptfra::rflo_mgelliptinterfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptinterfacesglo(), rflo_modmovegridframe::rflo_mgframeinterfaces(), rflo_movegridinterfaces(), and rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate().