Rocstar: RFLO_FindSourceCellInvert.F90 File Reference
RFLO_FindSourceCellInvert.F90 File Reference
Functions/Subroutines
subroutine rflo_findsourcecellinvert (regions, iReg, iLev, ic, jc, kc, icell, found, rotate, iRegSrc)
Function/Subroutine Documentation
subroutine rflo_findsourcecellinvert (type(t_region), dimension(:), pointer regions, integer iReg, integer iLev, integer ic, integer jc, integer kc, integer icell, logical found, logical rotate, integer iRegSrc)
Definition at line 54 of file RFLO_FindSourceCellInvert.F90.
References moderror::deregisterfunction(), ibeg, ic, icell, iend, ipcbeg, ipcend, jbeg, jc, jend, jpcbeg, jpcend, kbeg, kc, kpcbeg, moderror::registerfunction(), rflo_getdimensphys(), rflo_getpatchindices(), rflo_sourcecell(), and CImg< T >::rotate().
Referenced by rflo_findsourceregions().