Rocstar: RFLO_ViscousFlux.F90 File Reference
RFLO_ViscousFlux.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_viscousflux (region, indxMu, indxTCo, tv)
subroutine computeflux (ijk)
Function/Subroutine Documentation
subroutine rflo_viscousflux::computeflux (integer ijk)
Definition at line 125 of file RFLO_ViscousFlux.F90.
References Rocblas::div(), dot_product(), i, ibeg, idir, iend, ipcbeg, ipcend, j, jbeg, jdir, jend, jpcbeg, jpcend, k, kbeg, kdir, and kpcbeg.
Referenced by radi_flimdiffflux(), rflo_viscousflux(), and turb_ranssavisflux().
subroutine rflo_viscousflux (type(t_region) region, integer indxMu, integer indxTCo, real(rfreal), dimension(:,:), pointer tv)
Definition at line 48 of file RFLO_ViscousFlux.F90.
References computeflux(), moderror::deregisterfunction(), idir, ipcbeg, ipcend, jdir, jpcbeg, jpcend, kdir, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getnodeoffset(), and rflo_viscousfluxpatch().
Referenced by turb_coviscousfluxes(), and viscousfluxes().