Rocstar: RFLO_Tfint.F90 File Reference
RFLO_Tfint.F90 File Reference
Functions/Subroutines
subroutine rflo_tfint1d (s, p1, p2, xyz)
subroutine rflo_tfint2d (s1, s2, s3, s4, e1, e2, e3, e4, p1, p2, p3, p4, xyz)
Function/Subroutine Documentation
subroutine rflo_tfint1d (real(rfreal) s, real(rfreal), dimension(3) p1, real(rfreal), dimension(3) p2, real(rfreal), dimension(3) xyz)
Definition at line 59 of file RFLO_Tfint.F90.
References p1, and s.
Referenced by rflo_edgedeformation(), rflo_edgedeformationstraight(), rflo_modmovegridelliptfra::rflo_mgelliptedgesfra(), rflo_modmovegridelliptglo::rflo_mgelliptedgesglo(), rflo_modmovegridframe::rflo_mgframeedges(), rflo_modmovegridframe::rflo_mgframeedgeso(), and rflo_modmovegridutil::rflo_movegridqflatpatch().
subroutine rflo_tfint2d (real(rfreal) s1, real(rfreal) s2, real(rfreal) s3, real(rfreal) s4, real(rfreal), dimension(3) e1, real(rfreal), dimension(3) e2, real(rfreal), dimension(3) e3, real(rfreal), dimension(3) e4, real(rfreal), dimension(3) p1, real(rfreal), dimension(3) p2, real(rfreal), dimension(3) p3, real(rfreal), dimension(3) p4, real(rfreal), dimension(3) xyz)
Definition at line 76 of file RFLO_Tfint.F90.
References p1.
Referenced by rflo_boundarydeformation(), rflo_modmovegridelliptfra::rflo_mgelliptboundaries(), rflo_modmovegridframe::rflo_mgframebnddeformation(), rflo_modmovegridframe::rflo_mgframebnddeformation0(), and rflo_modmovegridutil::rflo_movegridcurvedpatch().