Rocstar: RFLO_WriteGridRegion.F90 File Reference
RFLO_WriteGridRegion.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_writegridregion (iReg, regions)
Function/Subroutine Documentation
subroutine rflo_writegridregion (integer iReg, type(t_region), dimension(:), pointer regions)
Definition at line 51 of file RFLO_WriteGridRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_writedatafileint(), rflo_writedatafilereal(), and Attribute::status().
Referenced by rocflo_2dto3d(), and rocflo_split().