Rocstar: RFLO_ArcLengthBounds.F90 File Reference
RFLO_ArcLengthBounds.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_arclengthbounds (region, xyz, arcLen12, arcLen34, arcLen56)
Function/Subroutine Documentation
subroutine rflo_arclengthbounds (type(t_region) region, real(rfreal), dimension(:,:), pointer xyz, real(rfreal), dimension(:,:), pointer arcLen12, real(rfreal), dimension(:,:), pointer arcLen34, real(rfreal), dimension(:,:), pointer arcLen56)
Definition at line 48 of file RFLO_ArcLengthBounds.F90.
References moderror::deregisterfunction(), i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and sqrt().
Referenced by rflo_modmovegridelliptfra::rflo_mgelliptsurfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptsurfacesglo(), rflo_modmovegridframe::rflo_mgframesurfaces(), and rflo_movegridsurfaces().