Rocstar: RFLO_CorrectCornerEdgeCells.F90 File Reference
RFLO_CorrectCornerEdgeCells.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_correctcorneredgecells (region, patch, bcType)
Function/Subroutine Documentation
subroutine rflo_correctcorneredgecells (type(t_region) region, type(t_patch) patch, integer bcType)
Definition at line 46 of file RFLO_CorrectCornerEdgeCells.F90.
References moderror::deregisterfunction(), i, ibeg, idcbeg, idcend, idir, iend, inode, ipcbeg, ipcend, j, jbeg, jdcbeg, jdcend, jdir, jend, jnode, jpcbeg, jpcend, k, kbeg, kdcbeg, kdir, kpcbeg, max(), min(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_r_m(), mixtureproperties(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensphys(), rflo_getnodeoffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_modboundaryconditions::rflo_boundaryconditionsrecv().