Rocstar: RFLO_CalcGradPhysBc.F90 File Reference
RFLO_CalcGradPhysBc.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_calcgradphysbc (region, patch, iBegV, iEndV, iBegG, iEndG, var, gradi, gradj, gradk)
subroutine rflo_finishgradpatchlinear
subroutine rflo_finishgradpatchconstant
Function/Subroutine Documentation
subroutine rflo_calcgradphysbc (type(t_region) region, type(t_patch) patch, integer iBegV, integer iEndV, integer iBegG, integer iEndG, real(rfreal), dimension(:,:), pointer var, real(rfreal), dimension(:,:), pointer gradi, real(rfreal), dimension(:,:), pointer gradj, real(rfreal), dimension(:,:), pointer gradk)
Definition at line 55 of file RFLO_CalcGradPhysBc.F90.
References moderror::deregisterfunction(), gradi(), gradj(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_finishgradpatchconstant(), rflo_finishgradpatchlinear(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_calcgradvector().
subroutine rflo_calcgradphysbc::rflo_finishgradpatchconstant ()
Definition at line 266 of file RFLO_CalcGradPhysBc.F90.
References i, ibeg, iend, inode, j, jbeg, jend, jnode, k, and kbeg.
Referenced by rflo_calcgradphysbc().
subroutine rflo_calcgradphysbc::rflo_finishgradpatchlinear ()
Definition at line 221 of file RFLO_CalcGradPhysBc.F90.
References i, idir, inode, j, jdir, jnode, k, and kdir.
Referenced by rflo_calcgradphysbc().