Rocstar: RFLO_ReadGridRegion.F90 File Reference
RFLO_ReadGridRegion.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_readgridregion (iReg, regions)
Function/Subroutine Documentation
subroutine rflo_readgridregion (integer iReg, type(t_region), dimension(:), pointer regions)
Definition at line 50 of file RFLO_ReadGridRegion.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, i, ipnbeg, ipnend, j, jpnbeg, jpnend, k, kpnbeg, moderror::registerfunction(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_readdatafileint(), rflo_readdatafilereal(), and Attribute::status().
Referenced by convertflo2flumesh(), genxinitsolution(), getgrid(), peul_rocflo_post(), plag_processeulerfield(), plag_writestattecascii(), rocflo_blocks(), rocflo_post(), rocflo_split(), rocflo_surf(), rocvav_post(), rvav_readfilestream1(), rvav_readfilestream2(), and rvav_readfilestream2comput().