Rocstar: RFLO_InitRocstarInterface.F90 File Reference
RFLO_InitRocstarInterface.F90 File Reference
Functions/Subroutines
subroutine rflo_initgenxinterface (regions, handle, solver, inSurf, inVolPlag, obtain_attribute)
Function/Subroutine Documentation
subroutine rflo_initgenxinterface (type(t_region), dimension(:), pointer regions, integer, intent(in) handle, integer, intent(in) solver, character(*) inSurf, character(*) inVolPlag, integer, intent(in) obtain_attribute)
Definition at line 44 of file RFLO_InitRocstarInterface.F90.
References moderror::deregisterfunction(), moderror::errorstop(), MeshImplTags::handle(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, Rocin::obtain_attribute(), peul_initgenxinterface(), plag_initgenxinterface(), radi_initgenxinterface(), randinitgenxinterface(), moderror::registerfunction(), rflo_getdimensdummynodes(), and turb_initgenxinterface().