Rocstar: RFLO_CalcGradDummyConn.F90 File Reference
RFLO_CalcGradDummyConn.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_calcgraddummyconn (region, lbound, idir, jdir, kdir, indBeg, indEnd, jndBeg, jndEnd, kndBeg, kndEnd, iBegV, iEndV, iBegG, iEndG, gradi, gradj, gradk)
Function/Subroutine Documentation
subroutine rflo_calcgraddummyconn (type(t_region) region, integer lbound, integer idir, integer jdir, integer kdir, integer indBeg, integer indEnd, integer jndBeg, integer jndEnd, integer kndBeg, integer kndEnd, integer iBegV, integer iEndV, integer iBegG, integer iEndG, real(rfreal), dimension(:,:), pointer gradi, real(rfreal), dimension(:,:), pointer gradj, real(rfreal), dimension(:,:), pointer gradk)
Definition at line 50 of file RFLO_CalcGradDummyConn.F90.
References moderror::deregisterfunction(), gradi(), gradj(), i, idir, j, jdir, k, kdir, moderror::registerfunction(), and rflo_getnodeoffset().
Referenced by rflo_calcgraddummy().