Rocstar: RFLO_OpenProbeFile.F90 File Reference
RFLO_OpenProbeFile.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_openprobefile (regions)
Function/Subroutine Documentation
subroutine rflo_openprobefile (type (t_region), dimension(:), pointer regions)
Definition at line 44 of file RFLO_OpenProbeFile.F90.
References centroidhexa(), moderror::deregisterfunction(), moderror::errorstop(), modtools::floatless(), form, i, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, max(), min(), Aff_transformation_repS2< FT >::print(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getnodeoffset(), Attribute::status(), Bbox_2::xmax(), Bbox_2::xmin(), Bbox_2::ymax(), Bbox_2::ymin(), Bbox_3::zmax(), and Bbox_3::zmin().
Referenced by rflo_initflowsolver().