Rocstar: RFLO_ExchangeDnodeSend.F90 File Reference
RFLO_ExchangeDnodeSend.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_exchangednodesend (region, regionSrc, patch, dNode)
Function/Subroutine Documentation
subroutine rflo_exchangednodesend (type(t_region) region, type(t_region) regionSrc, type(t_patch) patch, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 48 of file RFLO_ExchangeDnodeSend.F90.
References moderror::deregisterfunction(), dot_product(), moderror::errorstop(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), and RFC_Data_const< _Tag >::tag().
Referenced by rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_modmovegridelliptfra::rflo_mgelliptinterfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptinterfacesglo(), rflo_modmovegridframe::rflo_mgframeinterfaces(), rflo_movegridinterfaces(), and rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate().