Rocstar: RFLO_CheckValidity.F90 File Reference
RFLO_CheckValidity.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_checkvalidity (region)
Function/Subroutine Documentation
subroutine rflo_checkvalidity (type(t_region), target region)
Definition at line 43 of file RFLO_CheckValidity.F90.
References Line_2< R, T >::a(), moderror::deregisterfunction(), i, ipcbeg, ipcend, modtools::isnan(), j, jpcbeg, jpcend, k, kpcbeg, min(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_r_m(), mixtperf_t_dpr(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), StopWatch::stop(), v, and x.
Referenced by afterupdatemp(), and explicitmultistage().