Rocstar: RFLO_LaplaceGridPatch.F90 File Reference
RFLO_LaplaceGridPatch.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_laplacegridpatch (region, patch)
Function/Subroutine Documentation
subroutine rflo_laplacegridpatch (type(t_region) region, type(t_patch) patch)
Definition at line 44 of file RFLO_LaplaceGridPatch.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().
Referenced by rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), and rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate().