Rocstar: RFLO_ClearSendRequests.F90 File Reference
RFLO_ClearSendRequests.F90 File Reference
Functions/Subroutines
subroutine rflo_clearsendrequests (regions, iReg, geometry)
Function/Subroutine Documentation
subroutine rflo_clearsendrequests (type(t_region), dimension(:), pointer regions, integer iReg, logical geometry)
Definition at line 46 of file RFLO_ClearSendRequests.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), and Attribute::status().
Referenced by explicitmultistage(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_exchangegeometry(), rflo_exchangegeometryprepare(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_modmovegridelliptfra::rflo_mgelliptinterfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptinterfacesglo(), rflo_modmovegridframe::rflo_mgframeinterfaces(), rflo_movegridinterfaces(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), and updateboundaryconditionsmp().