Rocstar: RFLO_ExchangeGeometry.F90 File Reference
RFLO_ExchangeGeometry.F90 File Reference
Functions/Subroutines
subroutine rflo_exchangegeometry (regions)
Function/Subroutine Documentation
subroutine rflo_exchangegeometry (type(t_region), dimension(:), pointer regions)
Definition at line 44 of file RFLO_ExchangeGeometry.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_clearsendrequests(), rflo_exchangegeometrycopy(), rflo_exchangegeometrylevels(), rflo_exchangegeometryprepare(), rflo_exchangegeometryrecv(), and rflo_exchangegeometrysend().
Referenced by rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_flowsolver(), rflo_getgeometry(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_laplacegridsmoo(), rflo_movegridblocks(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_modvolmeshsmoothing::rflo_movegridvms(), and rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate().