Rocstar: RFLO_ReadDataFile.F90 File Reference
RFLO_ReadDataFile.F90 File Reference
Functions/Subroutines
subroutine rflo_readdatafileint (global, fileId, form, nDim1, nDim2, ivar)
subroutine rflo_readdatafilereal (global, fileId, form, nDim1, nDim2, var)
Function/Subroutine Documentation
subroutine rflo_readdatafileint (type(t_global), pointer global, integer fileId, integer form, integer nDim1, integer nDim2, integer, dimension(:,:) ivar)
Definition at line 49 of file RFLO_ReadDataFile.F90.
References moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, and moderror::registerfunction().
Referenced by peul_readsolution(), peul_readsolutionregion(), plag_readsolution(), plag_readsolutionfilepost(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_readstat(), radi_rflo_readsolution(), rflo_readgrid(), rflo_readgridregion(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffs(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffsreg(), rflo_readrandomstate(), rflo_readsolution(), rflo_readsolutionregion(), rflo_readstat(), rflo_readstatregion(), turb_rflo_readsolution(), and turb_rflo_readsolutionregion().
subroutine rflo_readdatafilereal (type(t_global), pointer global, integer fileId, integer form, integer nDim1, integer nDim2, real(rfreal), dimension(:,:) var)
Definition at line 98 of file RFLO_ReadDataFile.F90.
References moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, and moderror::registerfunction().
Referenced by peul_readsolution(), peul_readsolutionregion(), plag_readsolution(), plag_readsolutionfilepost(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_readstat(), radi_rflo_readsolution(), rflo_readgrid(), rflo_readgridregion(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffs(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffsreg(), rflo_readrandomstate(), rflo_readsolution(), rflo_readsolutionregion(), rflo_readstat(), rflo_readstatregion(), turb_rflo_readsolution(), and turb_rflo_readsolutionregion().