Rocstar: RFLO_CopyEdgeFaceParal.F90 File Reference
RFLO_CopyEdgeFaceParal.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_copyedgefaceparal (region, iFBeg, iFEnd, fvari, fvarj, fvark)
Function/Subroutine Documentation
subroutine rflo_copyedgefaceparal (type(t_region) region, integer iFBeg, integer iFEnd, real(rfreal), dimension(:,:), pointer fvari, real(rfreal), dimension(:,:), pointer fvarj, real(rfreal), dimension(:,:), pointer fvark)
Definition at line 55 of file RFLO_CopyEdgeFaceParal.F90.
References averagevecvar(), moderror::deregisterfunction(), fvarj(), i, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by rflo_c2favgcoeffs(), rflo_calcgradvector(), and turb_flofacewidth().