Rocstar: RFLO_ExchangeDnodeCopy.F90 File Reference
RFLO_ExchangeDnodeCopy.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_exchangednodecopy (region, regionSrc, patch, patchSrc, average, dNode, dNodeSrc)
Function/Subroutine Documentation
subroutine rflo_exchangednodecopy (type(t_region) region, type(t_region) regionSrc, type(t_patch) patch, type(t_patch) patchSrc, logical average, real(rfreal), dimension(:,:), pointer dNode, real(rfreal), dimension(:,:), pointer dNodeSrc)
Definition at line 54 of file RFLO_ExchangeDnodeCopy.F90.
References moderror::deregisterfunction(), dot_product(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), i, ibeg, idir, iend, modindexing::indijkmap(), j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindicesnodes(), and rflo_getpatchmapping().
Referenced by rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_modmovegridelliptfra::rflo_mgelliptinterfacesfra(), rflo_modmovegridelliptglo::rflo_mgelliptinterfacesglo(), rflo_modmovegridframe::rflo_mgframeinterfaces(), rflo_movegridinterfaces(), and rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate().