Rocstar: RFLO_C2eAvgCoeffsDegec.F90 File Reference
RFLO_C2eAvgCoeffsDegec.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_c2eavgcoeffsdegec (region)
subroutine calcavgco
Function/Subroutine Documentation
subroutine rflo_c2eavgcoeffsdegec::calcavgco ()
Definition at line 115 of file RFLO_C2eAvgCoeffsDegec.F90.
References i, ibeg, iend, j, jbeg, jend, k, and kbeg.
Referenced by rflo_c2eavgcoeffsdegec(), and rflo_c2favgcoeffsdegec().
subroutine rflo_c2eavgcoeffsdegec (type(t_region) region)
Definition at line 40 of file RFLO_C2eAvgCoeffsDegec.F90.
References calcavgco(), moderror::deregisterfunction(), ibeg, icorner, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getcornercellsindices(), rflo_getedgecellsindices(), and rflo_getnodeoffset().
Referenced by rflo_c2eavgcoeffs().