Rocstar: RFLO_ViscousFluxPatch.F90 File Reference
RFLO_ViscousFluxPatch.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_viscousfluxpatch (region, patch, indxMu, indxTCo, tv)
Function/Subroutine Documentation
subroutine rflo_viscousfluxpatch (type(t_region) region, type(t_patch) patch, integer indxMu, integer indxTCo, real(rfreal), dimension(:,:), pointer tv)
Definition at line 49 of file RFLO_ViscousFluxPatch.F90.
References moderror::deregisterfunction(), Rocblas::div(), dot_product(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_viscousflux().