Rocstar: RFLO_LaplaceGridSolve.F90 File Reference
RFLO_LaplaceGridSolve.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_laplacegridsolve (region)
Function/Subroutine Documentation
subroutine rflo_laplacegridsolve (type(t_region) region)
Definition at line 45 of file RFLO_LaplaceGridSolve.F90.
References d, denom, moderror::deregisterfunction(), dist(), i, ic, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), and sqrt().
Referenced by rflo_laplacegridsmoo(), and rflo_modlaplacesmoothing::rflo_laplacegridsmoo().