Rocstar: RFLO_GetGeometry.F90 File Reference
RFLO_GetGeometry.F90 File Reference
Functions/Subroutines
subroutine rflo_getgeometry (regions, iread)
Function/Subroutine Documentation
subroutine rflo_getgeometry (type (t_region), dimension(:), pointer regions, integer iread)
Definition at line 44 of file RFLO_GetGeometry.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflo_modgridmetrics::rflo_arclengthpatch(), rflo_copygeometrydummy(), rflo_exchangegeometry(), rflo_extrapolategeometry(), rflo_modgridregionshape::rflo_findfunkyblocks(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_generatecoarsegrids(), rflo_modgridcontrolmap::rflo_gridcontrolfunc2d(), rflo_modgridcontrolmap::rflo_gridcontrolfunc3d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad2d(), rflo_modgridcontrolmap::rflo_gridcontrolgrad3d(), rflo_modgridcontrolmap::rflo_gridcontrolmap2d(), rflo_modgridcontrolmap::rflo_gridcontrolmap3d(), rflo_modgridregionshape::rflo_gridflatpatch(), rflo_readgrid(), and rflo_modforcesmoments::rflo_writepatchcoeffsinfo().
Referenced by rflo_initflowsolver().