Rocstar: RFLO_GenerateCoarseGrids.F90 File Reference
RFLO_GenerateCoarseGrids.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_generatecoarsegrids (region)
Function/Subroutine Documentation
subroutine rflo_generatecoarsegrids (type(t_region) region)
Definition at line 44 of file RFLO_GenerateCoarseGrids.F90.
References moderror::deregisterfunction(), i, j, k, moderror::registerfunction(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by getgrid(), peul_rocflo_post(), plag_processeulerfield(), plag_writestattecascii(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_flowsolver(), rflo_getgeometry(), rflo_gridremesh(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_movegridblocks(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rocflo_post(), and rocflo_surf().