Rocstar: RFLO_GetFlowSolution.F90 File Reference
RFLO_GetFlowSolution.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_getflowsolution (regions)
Function/Subroutine Documentation
subroutine rflo_getflowsolution (type (t_region), dimension(:), pointer regions)
Definition at line 44 of file RFLO_GetFlowSolution.F90.
References moderror::deregisterfunction(), idcbeg, idcend, inrt_twodimaverage(), jdcbeg, jdcend, kdcbeg, mixtureproperties(), peri_initsolution(), peul_initsolution(), peul_readsolution(), plag_initsolution(), plag_readsolution(), modinterfacesradiation::RADI_InitSolution::radi_initsolution(), moderror::registerfunction(), rflo_modboundaryconditions::rflo_bcondinjectioninit(), rflo_getboundaryvalues(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_modinitialization::rflo_initnoncvsolution(), rflo_limiterreference(), rflo_readrandomstate(), rflo_readsolution(), turb_initsolution(), and turb_rflo_readsolution().
Referenced by rflo_initflowsolver().