Rocstar: RFLO_ExchangeGeometryRecv.F90 File Reference
RFLO_ExchangeGeometryRecv.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_exchangegeometryrecv (region, regionSrc, patch, patchSrc)
Function/Subroutine Documentation
subroutine rflo_exchangegeometryrecv (type(t_region) region, type(t_region) regionSrc, type(t_patch) patch, type(t_patch) patchSrc)
Definition at line 50 of file RFLO_ExchangeGeometryRecv.F90.
References cos, moderror::deregisterfunction(), dx, dy, Direction_3< R, T >::dz(), moderror::errorstop(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchindicesnodes(), sin, Ray_2< R, T >::source(), Attribute::status(), and RFC_Data_const< _Tag >::tag().
Referenced by rflo_exchangegeometry().