Rocstar: RFLO_CalcGradConnBc.h File Reference
RFLO_CalcGradConnBc.h File Reference
Functions
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR **Arising
OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE **USE OR
OTHER DEALINGS WITH THE
SOFTWARE
**********************************************************************INTERFACE
SUBROUTINE RFLO_CalcGradConnBc (region, patch, iConBc, iBegV, iEndV, iBegG, iEndG,&var, gradi, gradj, gradk) USE ModDataTypes USE ModDataStruct
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR **Arising
OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE **USE OR
OTHER DEALINGS WITH THE
SOFTWARE
**********************************************************************INTERFACE
SUBROUTINE iEndG REAL (RFREAL)
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR **Arising
OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE **USE OR
OTHER DEALINGS WITH THE
SOFTWARE
**********************************************************************INTERFACE
SUBROUTINE iEndG gradi (:,:)
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR **Arising
OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE **USE OR
OTHER DEALINGS WITH THE
SOFTWARE
**********************************************************************INTERFACE
SUBROUTINE iEndG gradj (:,:)
Variables
**********************************************************************Rocstar
Simulation Suite ** Copyright
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC ** Champaign
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com **** License
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY KIND
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR IMPLIED
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF MERCHANTABILITY
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER ** LIABILITY
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF CONTRACT
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR OTHERWISE
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR **Arising FROM
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR **Arising
OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE **USE OR
OTHER DEALINGS WITH THE
SOFTWARE
**********************************************************************INTERFACE
SUBROUTINE ONLY
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR **Arising
OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE **USE OR
OTHER DEALINGS WITH THE
SOFTWARE
**********************************************************************INTERFACE
SUBROUTINE iBegV
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR **Arising
OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE **USE OR
OTHER DEALINGS WITH THE
SOFTWARE
**********************************************************************INTERFACE
SUBROUTINE iEndV
**********************************************************************Rocstar
Simulation Suite Illinois
Rocstar LLC All rights
reserved ****Illinois Rocstar
LLC IL **www illinoisrocstar
com **sales illinoisrocstar
com WITHOUT WARRANTY OF ANY
**EXPRESS OR INCLUDING BUT NOT
LIMITED TO THE WARRANTIES **OF
FITNESS FOR A PARTICULAR
PURPOSE AND **NONINFRINGEMENT
IN NO EVENT SHALL THE
CONTRIBUTORS OR **COPYRIGHT
HOLDERS BE LIABLE FOR ANY
DAMAGES OR OTHER WHETHER IN AN
ACTION OF TORT OR **Arising
OUT OF OR IN CONNECTION WITH
THE SOFTWARE OR THE **USE OR
OTHER DEALINGS WITH THE
SOFTWARE
**********************************************************************INTERFACE
SUBROUTINE iBegG
Function Documentation
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR * * Arising OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE* * USE OR OTHER DEALINGS WITH THE SOFTWARE* ********************************************************************* INTERFACE SUBROUTINE iEndG gradi (: , :)
Referenced by checkindxrange(), peul_sourceeqeul(), radi_diffradflux(), radi_fluxlimiter(), rflo_calcgradconnbc(), rflo_modinterfaceslibrary::RFLO_CalcGradConnBc::rflo_calcgradconnbc(), rflo_modinterfaceslibrary::RFLO_CalcGradDummy::rflo_calcgraddummy(), rflo_calcgraddummy(), rflo_calcgraddummyconn(), rflo_modinterfaceslibrary::RFLO_CalcGradDummyConn::rflo_calcgraddummyconn(), rflo_calcgraddummyphys(), rflo_modinterfaceslibrary::RFLO_CalcGradDummyPhys::rflo_calcgraddummyphys(), rflo_modinterfaceslibrary::RFLO_CalcGradDummySymm::rflo_calcgraddummysymm(), rflo_calcgraddummysymm(), rflo_modinterfaceslibrary::RFLO_CalcGradFaces::rflo_calcgradfaces(), rflo_calcgradfaces(), rflo_modinterfaceslibrary::RFLO_CalcGradPhysBc::rflo_calcgradphysbc(), rflo_calcgradphysbc(), rflo_modinterfaceslibrary::RFLO_CalcGradVector::rflo_calcgradvector(), rflo_calcgradvector(), rflo_calcsidegrad(), rflo_copyedgegrad(), rflo_copypatchedgegrad(), turb_calcvortic(), turb_coviscousfluxes(), and turb_lesgeteddyvis().
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR * * Arising OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE* * USE OR OTHER DEALINGS WITH THE SOFTWARE* ********************************************************************* INTERFACE SUBROUTINE iEndG gradj (: , :)
Referenced by checkindxrange(), peul_sourceeqeul(), radi_diffradflux(), radi_fluxlimiter(), rflo_calcgradconnbc(), rflo_modinterfaceslibrary::RFLO_CalcGradConnBc::rflo_calcgradconnbc(), rflo_modinterfaceslibrary::RFLO_CalcGradDummy::rflo_calcgraddummy(), rflo_calcgraddummy(), rflo_calcgraddummyconn(), rflo_modinterfaceslibrary::RFLO_CalcGradDummyConn::rflo_calcgraddummyconn(), rflo_calcgraddummyphys(), rflo_modinterfaceslibrary::RFLO_CalcGradDummyPhys::rflo_calcgraddummyphys(), rflo_modinterfaceslibrary::RFLO_CalcGradDummySymm::rflo_calcgraddummysymm(), rflo_calcgraddummysymm(), rflo_modinterfaceslibrary::RFLO_CalcGradFaces::rflo_calcgradfaces(), rflo_calcgradfaces(), rflo_modinterfaceslibrary::RFLO_CalcGradPhysBc::rflo_calcgradphysbc(), rflo_calcgradphysbc(), rflo_modinterfaceslibrary::RFLO_CalcGradVector::rflo_calcgradvector(), rflo_calcgradvector(), rflo_calcsidegrad(), rflo_copyedgegrad(), rflo_copypatchedgegrad(), turb_calcvortic(), turb_coviscousfluxes(), and turb_lesgeteddyvis().
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR * * Arising OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE* * USE OR OTHER DEALINGS WITH THE SOFTWARE* ********************************************************************* INTERFACE SUBROUTINE iEndG REAL (RFREAL)
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR * * Arising OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE* * USE OR OTHER DEALINGS WITH THE SOFTWARE* ********************************************************************* INTERFACE SUBROUTINE RFLO_CalcGradConnBc (region , patch , iConBc , iBegV , iEndV , iBegG , iEndG , & var, gradi , gradj , gradk)
Variable Documentation
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC* * Champaign
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF CONTRACT
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite* * Copyright
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR * * Arising FROM
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR * * Arising OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE* * USE OR OTHER DEALINGS WITH THE SOFTWARE* ********************************************************************* INTERFACE SUBROUTINE iBegG
Definition at line 28 of file RFLO_CalcGradConnBc.h.
**********************************************************************Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved ****Illinois Rocstar LLC IL **www illinoisrocstar com **sales illinoisrocstar com WITHOUT WARRANTY OF ANY **EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES **OF FITNESS FOR A PARTICULAR PURPOSE AND **NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR **COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR **Arising OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE **USE OR OTHER DEALINGS WITH THE SOFTWARE **********************************************************************INTERFACE SUBROUTINE knode kend kndEnd iBegV
Definition at line 28 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR * * Arising OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE* * USE OR OTHER DEALINGS WITH THE SOFTWARE* ********************************************************************* INTERFACE SUBROUTINE iEndV
Definition at line 28 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR IMPLIED
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY KIND
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER* * LIABILITY
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com* * * * License
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF MERCHANTABILITY
Definition at line 3 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR * * Arising OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE* * USE OR OTHER DEALINGS WITH THE SOFTWARE* ********************************************************************* INTERFACE SUBROUTINE ONLY
Definition at line 28 of file RFLO_CalcGradConnBc.h.
********************************************************************* * Rocstar Simulation Suite Illinois Rocstar LLC All rights reserved* * * * Illinois Rocstar LLC IL* * www illinoisrocstar com* * sales illinoisrocstar com WITHOUT WARRANTY OF ANY * * EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES* * OF FITNESS FOR A PARTICULAR PURPOSE AND* * NONINFRINGEMENT IN NO EVENT SHALL THE CONTRIBUTORS OR* * COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR OTHERWISE
Definition at line 3 of file RFLO_CalcGradConnBc.h.