Rocstar: RFLO_C2fAvgCoeffsPatch.F90 File Reference
RFLO_C2fAvgCoeffsPatch.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_c2favgcoeffspatch (region, patch)
subroutine avgcopatchlinear
subroutine avgcopatchconstant
Function/Subroutine Documentation
subroutine rflo_c2favgcoeffspatch::avgcopatchconstant ()
Definition at line 181 of file RFLO_C2fAvgCoeffsPatch.F90.
References i, ibeg, iend, inode, j, jbeg, jend, jnode, k, and kbeg.
Referenced by rflo_c2favgcoeffspatch().
subroutine rflo_c2favgcoeffspatch::avgcopatchlinear ()
Definition at line 160 of file RFLO_C2fAvgCoeffsPatch.F90.
References i, ibeg, iend, inode, j, jbeg, jend, jnode, k, and kbeg.
Referenced by rflo_c2favgcoeffspatch().
subroutine rflo_c2favgcoeffspatch (type(t_region) region, type(t_patch) patch)
Definition at line 47 of file RFLO_C2fAvgCoeffsPatch.F90.
References avgcopatchconstant(), avgcopatchlinear(), moderror::deregisterfunction(), ibeg, idir, iend, inode, jbeg, jdir, jend, jnode, kbeg, kdir, moderror::registerfunction(), rflo_getnodeoffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by rflo_c2favgcoeffs().