Rocstar: RFLO_ExchangeDummyIreg.F90 File Reference
RFLO_ExchangeDummyIreg.F90 File Reference
Functions/Subroutines
subroutine rflo_exchangedummyireg (region, regionSrc, patch, patchSrc)
Function/Subroutine Documentation
subroutine rflo_exchangedummyireg (type(t_region) region, type(t_region) regionSrc, type(t_patch) patch, type(t_patch) patchSrc)
Definition at line 49 of file RFLO_ExchangeDummyIreg.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflo_modboundaryconditions::rflo_boundaryconditionsset().