Rocstar: RFLO_CalcCellCentroids.F90 File Reference
RFLO_CalcCellCentroids.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_calccellcentroids (region)
Function/Subroutine Documentation
subroutine rflo_calccellcentroids (type(t_region) region)
Definition at line 43 of file RFLO_CalcCellCentroids.F90.
References centroidhexa(), moderror::deregisterfunction(), i, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), and rflo_getnodeoffset().
Referenced by rflo_modgridmetrics::rflo_calcgridmetrics(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_movegridblocks(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_modvolmeshsmoothing::rflo_vmslaplaceprocedure(), and rvav_computeanalyticalsolution().