Rocstar: RFLO_CopyGeometryDummy.F90 File Reference
RFLO_CopyGeometryDummy.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_copygeometrydummy (region)
Function/Subroutine Documentation
subroutine rflo_copygeometrydummy (type(t_region) region)
Definition at line 45 of file RFLO_CopyGeometryDummy.F90.
References moderror::deregisterfunction(), i, idnbeg, idnend, ipnbeg, ipnend, j, jdnbeg, jdnend, jpnbeg, jpnend, k, kdnbeg, kpnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), and rflo_getnodeoffset().
Referenced by getgrid(), peul_rocflo_post(), plag_processeulerfield(), plag_writestattecascii(), rflo_modelliptsmoothing::rflo_elliptgridsmoo(), rflo_flowsolver(), rflo_getgeometry(), rflo_gridremesh(), rflo_laplacegridsmoo(), rflo_modlaplacesmoothing::rflo_laplacegridsmoo(), rflo_movegridblocks(), rflo_modmovegridelliptfra::rflo_movegridelliptfra(), rflo_modmovegridelliptglo::rflo_movegridelliptglo(), rflo_modmovegridframe::rflo_movegridframe(), rflo_movegridglobal(), rflo_modvolmeshsmoothing::rflo_movegridvms(), rflo_modvolmeshsmoothing::rflo_vmslaplaceiterate(), rocflo_post(), rocflo_surf(), and rvav_computeanalyticalsolution().