Rocstar: RFLO_CopyVectorDummy.F90 File Reference
RFLO_CopyVectorDummy.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_copyvectorpatches (iLev, region, vec)
subroutine rflo_copyvectoredges (iLev, region, vec)
subroutine rflo_copyvectorcorners (iLev, region, vec)
Function/Subroutine Documentation
subroutine rflo_copyvectorcorners (integer iLev, type(t_region) region, real(rfreal), dimension(:), pointer vec)
Definition at line 198 of file RFLO_CopyVectorDummy.F90.
References moderror::deregisterfunction(), i, ibeg, iend, ipcbeg, ipcend, j, jbeg, jend, jpcbeg, jpcend, k, kbeg, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getcornercellsindices(), rflo_getdimensdummy(), rflo_getdimensphys(), rflo_getedgecellsindices(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and volumehexa().
Referenced by peul_spectralradii(), radi_rflo_flimspectralradii(), rflo_calccontrolvolumes(), rflo_timestepinviscid(), rflo_timestepviscous(), and turb_rflo_ransspectralradii().
subroutine rflo_copyvectoredges (integer iLev, type(t_region) region, real(rfreal), dimension(:), pointer vec)
Definition at line 125 of file RFLO_CopyVectorDummy.F90.
References moderror::deregisterfunction(), i, ibeg, iend, ipcbeg, ipcend, j, jbeg, jend, jpcbeg, jpcend, k, kbeg, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), and rflo_getedgecellsindices().
Referenced by peul_spectralradii(), radi_rflo_flimspectralradii(), rflo_calccontrolvolumes(), rflo_timestepinviscid(), rflo_timestepviscous(), and turb_rflo_ransspectralradii().
subroutine rflo_copyvectorpatches (integer iLev, type(t_region) region, real(rfreal), dimension(:), pointer vec)
Definition at line 53 of file RFLO_CopyVectorDummy.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), and rflo_getpatchindices().
Referenced by peul_spectralradii(), radi_rflo_flimspectralradii(), rflo_calccontrolvolumes(), rflo_timestepinviscid(), rflo_timestepviscous(), and turb_rflo_ransspectralradii().