Rocstar: RFLU_DestroyGrid.F90 File Reference
RFLU_DestroyGrid.F90 File Reference
Functions/Subroutines
subroutine rflu_destroygrid (pRegion)
Function/Subroutine Documentation
subroutine rflu_destroygrid (type(t_region), pointer pRegion)
Definition at line 45 of file RFLU_DestroyGrid.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_deallocatememorywrapper(), rflu_endflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregions(), rflu_postprocessregions_ens(), rflu_postprocessregionscommon1(), rflu_postprocessregionscommon2(), rfluconv(), rfluinit(), rflumap(), rflupart(), and rflupick().