Rocstar: RFLU_ReadTbcSection.F90 File Reference
RFLU_ReadTbcSection.F90 File Reference
Functions/Subroutines
subroutine rflu_readtbcsection (pRegion, tbcType)
Function/Subroutine Documentation
subroutine rflu_readtbcsection (type(t_region), pointer pRegion, integer, intent(in) tbcType)
Definition at line 46 of file RFLU_ReadTbcSection.F90.
References moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), CImg< T >::line(), nvals, prbeg, prend, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by rflu_readtbcinputfile().