Rocstar: RFLU_InvertMatrixSVD.F90 File Reference
RFLU_InvertMatrixSVD.F90 File Reference
Functions/Subroutines
subroutine rflu_invertmatrixsvd (global, nRows, nCols, a, aInv, sCount)
Function/Subroutine Documentation
subroutine rflu_invertmatrixsvd (type(t_global), pointer global, integer, intent(in) nRows, integer, intent(in) nCols, real(rfreal), dimension(nrows,ncols) a, real(rfreal), dimension(ncols,nrows) aInv, integer, intent(out), optional sCount)
Definition at line 50 of file RFLU_InvertMatrixSVD.F90.
References Line_2< R, T >::a(), ainv(), moderror::deregisterfunction(), rflu_modinterfaceslibrary::dgesdd::dgesdd(), moderror::errorstop(), i, j, moderror::registerfunction(), and s.
Referenced by rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_moddifferentiationbfaces::rflu_computegradbfaces(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_modstencilsutils::rflu_computestencilweights(), and rflu_computeweightsoles().