Rocstar: RFLU_DeallocMemVertWrapper.F90 File Reference
RFLU_DeallocMemVertWrapper.F90 File Reference
Functions/Subroutines
subroutine rflu_deallocmemvertwrapper (pRegion)
Function/Subroutine Documentation
subroutine rflu_deallocmemvertwrapper (type(t_region), pointer pRegion)
Definition at line 44 of file RFLU_DeallocMemVertWrapper.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_deallocatememoryvert(), rflu_modplottingvars::rflu_destroyplottingvarsvert(), and spec_rflu_deallocatememoryvert().
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), and rflu_postprocessregionscommon2().