Rocstar: rflupart.F90 File Reference
rflupart.F90 File Reference
Functions/Subroutines
subroutine rflupart (caseString, verbLevel)
Function/Subroutine Documentation
subroutine rflupart (character(*) caseString, integer, intent(in) verbLevel)
Definition at line 48 of file rflupart.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_modallocatememory::rflu_allocatememorygspeeds(), rflu_modregionmapping::rflu_applyregionmapping(), rflu_modboundlists::rflu_buildbcellmlist(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_builddatastruct(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modcellmapping::rflu_buildloc2globcellmapping(), rflu_modpatchutils::rflu_buildpatchneighbormaps(), rflu_modvertexlists::rflu_buildvert2celllist(), rflu_modpatchutils::rflu_checkpatchbcconsistency(), rflu_modcoloring::rflu_col_createcoloring(), rflu_modcoloring::rflu_col_destroycoloring(), rflu_modcoloring::rflu_col_writecoloring(), rflu_modcommlists::rflu_comm_buildcommlists(), rflu_modcommlists::rflu_comm_checkcountborders(), rflu_modcommlists::rflu_comm_countborders(), rflu_modcommlists::rflu_comm_countbordersserial(), rflu_modcommlists::rflu_comm_createbordercntr(), rflu_modcommlists::rflu_comm_createborders(), rflu_modcommlists::rflu_comm_destroybordercntr(), rflu_modcommlists::rflu_comm_writecommlists(), rflu_modpatchutils::rflu_computepatchnormalslocal(), rflu_modboundlists::rflu_createbcellmlist(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modfacelist::rflu_createfacelist(), rflu_modgeometry::rflu_creategeometry(), rflu_creategrid(), rflu_modpatchutils::rflu_createpatchneighbormaps(), rflu_modregionmapping::rflu_createregionmapping(), rflu_modvertexlists::rflu_createvert2celllist(), rflu_moddeallocatememory::rflu_deallocatememorygspeeds(), rflu_modgridspeedutils::rflu_decideneedgridspeeds(), rflu_modboundlists::rflu_destroybcellmlist(), rflu_modboundlists::rflu_destroybvertexlists(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), rflu_modfacelist::rflu_destroycell2facelist(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modgeometry::rflu_destroygeometry(), rflu_destroygrid(), rflu_modpatchutils::rflu_destroypatchneighbormaps(), rflu_modregionmapping::rflu_destroyregionmapping(), rflu_modvertexlists::rflu_destroyvert2celllist(), rflu_modgridutils::rflu_distortgrid(), rflu_modrocstaradmin::rflu_genx_buildgridsurf(), rflu_modrocstaradmin::rflu_genx_buildpconn(), rflu_modrocstaradmin::rflu_genx_createattrgridsurf(), rflu_modrocstaradmin::rflu_genx_createattrgspeeds(), rflu_modrocstaradmin::rflu_genx_creategridsurf(), rflu_modrocstaradmin::rflu_genx_createpconn(), rflu_modrocstaradmin::rflu_genx_createwindows(), rflu_modrocstaradmin::rflu_genx_destroygridsurf(), rflu_modrocstaradmin::rflu_genx_destroypconn(), rflu_modrocstario::rflu_genx_getdimensionsderived(), rflu_modrocstaradmin::rflu_genx_hardcodewindowname(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modrocstario::rflu_genx_readwindow(), rflu_modrocstaradmin::rflu_genx_registergrid(), rflu_modrocstaradmin::rflu_genx_registergridsurf(), rflu_modrocstaradmin::rflu_genx_registergridvol(), rflu_modrocstaradmin::rflu_genx_storecommunicator(), rflu_modrocstaradmin::rflu_genx_storenameshandles(), rflu_getuserinput(), rflu_modregionmapping::rflu_imposeregionmappingserial(), rflu_initglobal(), rflu_modpartitionregion::rflu_part_addvirtualcells(), rflu_modpartitionregion::rflu_part_buildborderfacelist(), rflu_modpartitionregion::rflu_part_buildcelllists(), rflu_modpartitionregion::rflu_part_buildpatchlists(), rflu_modpartitionregion::rflu_part_buildreg2cellmap(), rflu_modpartitionregion::rflu_part_buildvertexdata(), rflu_modpartitionregion::rflu_part_buildvertexlists(), rflu_modpartitionregion::rflu_part_createcelllists(), rflu_modpartitionregion::rflu_part_createpatchlists(), rflu_modpartitionregion::rflu_part_createreg2cellmap(), rflu_modpartitionregion::rflu_part_destroycelllists(), rflu_modpartitionregion::rflu_part_destroypatchlists(), rflu_modpartitionregion::rflu_part_destroyvertexdata(), rflu_modpartitionregion::rflu_part_partitionregion(), rflu_modpartitionregion::rflu_part_renumbervertexlists(), rflu_printgridinfo(), rflu_printheader(), rflu_printwarninfo(), rflu_randominit(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), rflu_readconvgridwrapper(), rflu_moddimensions::rflu_readdimensions(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_readrestartinfo(), rflu_modboundlists::rflu_renumberbfacelists(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap(), rflu_modrenumberings::rflu_rnmb_buildsc2pcmap(), rflu_modrenumberings::rflu_rnmb_buildsv2pvmap(), rflu_modrenumberings::rflu_rnmb_createpbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_createpc2scmap(), rflu_modrenumberings::rflu_rnmb_createpv2svmap(), rflu_modrenumberings::rflu_rnmb_createsc2rmap(), rflu_modrenumberings::rflu_rnmb_destroypbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_destroypc2scmap(), rflu_modrenumberings::rflu_rnmb_destroypv2svmap(), rflu_modrenumberings::rflu_rnmb_destroysbc2pcmap(), rflu_modrenumberings::rflu_rnmb_destroysc2pcmap(), rflu_modrenumberings::rflu_rnmb_destroysc2rmap(), rflu_modrenumberings::rflu_rnmb_destroysv2pvmap(), rflu_modrenumberings::rflu_rnmb_readpxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_writepxx2sxxmaps(), rflu_modrenumberings::rflu_rnmb_writesc2rmap(), rflu_modstencilscells::rflu_setinfoc2cstencilwrapper(), rflu_moddimensions::rflu_setmaxdimensions(), rflu_setmoduletype(), rflu_modregionmapping::rflu_setregionmappingserial(), rflu_setrestarttimeflag(), rflu_modsymmetryperiodic::rflu_sype_addvirtualcells(), rflu_modsymmetryperiodic::rflu_sype_buildp2vclist(), rflu_modsymmetryperiodic::rflu_sype_buildp2vclistserial(), rflu_modsymmetryperiodic::rflu_sype_buildtransforms(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modsymmetryperiodic::rflu_sype_createvertexmaps(), rflu_modsymmetryperiodic::rflu_sype_destroyp2vclist(), rflu_modsymmetryperiodic::rflu_sype_havesypepatches(), rflu_modsymmetryperiodic::rflu_sype_writetransforms(), rflu_user_enforcepatchcoords(), rflu_moddimensions::rflu_writedimensions(), rflu_moddimensions::rflu_writedimensionsborders(), rflu_modreadwritegrid::rflu_writegridwrapper(), rflu_modcellmapping::rflu_writeloc2globcellmapping(), rflu_writerestartinfo(), rflu_writeversionstring(), scalerotatevector(), and StopWatch::stop().
Referenced by main().