Rocstar: RFLU_CreateRegions.F90 File Reference
RFLU_CreateRegions.F90 File Reference
Functions/Subroutines
subroutine rflu_createregions (global, iLev, levels)
Function/Subroutine Documentation
subroutine rflu_createregions (type(t_global), pointer global, integer, intent(in) iLev, type(t_level), dimension(:), pointer levels)
Definition at line 48 of file RFLU_CreateRegions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_builddatastruct().