Rocstar: RFLU_ComputeIntegral5OLES.F90 File Reference
RFLU_ComputeIntegral5OLES.F90 File Reference
Functions/Subroutines
subroutine rflu_computeintegral5oles (pRegion)
Function/Subroutine Documentation
subroutine rflu_computeintegral5oles (type(t_region), pointer pRegion)
Definition at line 44 of file RFLU_ComputeIntegral5OLES.F90.
References moderror::deregisterfunction(), moderror::errorstop(), j, k, key, Aff_transformation_2< R_ >::m(), moderror::registerfunction(), rflu_allocatedcuhrearrays(), rflu_computedcuhreinfo(), rflu_deallocatedcuhrearrays(), rflu_modoles::rflu_definecorrelation540(), rflu_modoles::rflu_definecorrelation541(), rflu_modoles::rflu_definecorrelation542(), rflu_modoles::rflu_geti4posoles(), rflu_modoles::rflu_getqposoles(), rflu_modoles::rflu_mapm2ijkl(), and rflu_modoles::rflu_setmapfunnz2funcorr44().
Referenced by rflu_computeintegrals1245oles().