Rocstar: RFLU_ComputeIntegral1OLES.F90 File Reference
RFLU_ComputeIntegral1OLES.F90 File Reference
Functions/Subroutines
subroutine rflu_computeintegral1oles (pRegion)
Function/Subroutine Documentation
subroutine rflu_computeintegral1oles (type(t_region), pointer pRegion)
Definition at line 44 of file RFLU_ComputeIntegral1OLES.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, key, Aff_transformation_2< R_ >::m(), moderror::registerfunction(), rflu_allocatedcuhrearrays(), rflu_computedcuhreinfo(), rflu_deallocatedcuhrearrays(), rflu_modoles::rflu_definecorrelation32(), rflu_modoles::rflu_geti1posoles(), rflu_modoles::rflu_mapk2ij(), and rflu_modoles::rflu_setmapfunnz2funcorr32().
Referenced by rflu_computeintegrals1245oles().