Rocstar: RFLU_SetGasVars.F90 File Reference
RFLU_SetGasVars.F90 File Reference
Functions/Subroutines
subroutine rflu_setgasvars (pRegion, icgBeg, icgEnd)
Function/Subroutine Documentation
subroutine rflu_setgasvars (type(t_region), pointer pRegion, integer, intent(in) icgBeg, integer, intent(in) icgEnd)
Definition at line 46 of file RFLU_SetGasVars.F90.
References moderror::deregisterfunction(), moderror::errorstop(), mixtperf_m_r(), mixtperf_r_cpg(), mixtperf_r_m(), Color::r(), and moderror::registerfunction().
Referenced by rflu_initflowhardcodelimwrapper(), rflu_initflowhardcodewrapper(), rflu_initflowscratchwrapper(), rflu_setvars(), and rfluinit().