Rocstar: RFLU_InitGlobal.F90 File Reference
RFLU_InitGlobal.F90 File Reference
Functions/Subroutines
subroutine rflu_initglobal (casename, verbLevel, communicator, global)
Function/Subroutine Documentation
subroutine rflu_initglobal (character(*), intent(in) casename, integer, intent(in) verbLevel, integer, intent(in) communicator, type(t_global), pointer global)
Definition at line 47 of file RFLU_InitGlobal.F90.
References Function::communicator().
Referenced by rflu_initflowsolver(), rflucells(), rfluconv(), rfluinit(), rflumap(), rflupart(), rflupick(), and rflupost().