Rocstar: RFLU_ComputeDCUHREInfo.F90 File Reference
RFLU_ComputeDCUHREInfo.F90 File Reference
Functions/Subroutines
subroutine rflu_computedcuhreinfo (global, NDIM, NF, KEY, MAXCLS, NW)
Function/Subroutine Documentation
subroutine rflu_computedcuhreinfo (type(t_global), pointer global, integer, intent(in) NDIM, integer, intent(in) NF, integer, intent(in) KEY, integer, intent(inout) MAXCLS, integer, intent(out) NW)
Definition at line 49 of file RFLU_ComputeDCUHREInfo.F90.
References moderror::deregisterfunction(), moderror::errorstop(), key, max(), and moderror::registerfunction().
Referenced by rflu_computeintegral1oles(), rflu_computeintegral2oles(), rflu_computeintegral4oles(), and rflu_computeintegral5oles().