Rocstar: RFLU_PostProcessRegions.F90 File Reference
RFLU_PostProcessRegions.F90 File Reference
Functions/Subroutines
subroutine rflu_postprocessregions (levels)
Function/Subroutine Documentation
subroutine rflu_postprocessregions (type(t_level), dimension(:), pointer levels)
Definition at line 44 of file RFLU_PostProcessRegions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modplottingvars::rflu_buildplottingvarmaps(), rflu_closepostinfo(), rflu_modplottingvars::rflu_countplottingvars(), rflu_modplottingvars::rflu_createplottingvarmaps(), rflu_destroygrid(), rflu_modplottingvars::rflu_destroyplottingvarmaps(), rflu_openpostinfo(), rflu_postprocessregionscommon1(), rflu_postprocessregionscommon2(), rflu_modplottingvars::rflu_printplottingvarsinfo(), rflu_readpostinfo(), rflu_setpatchplotflags(), rflu_modtecplot::rflu_tec_builddatafieldsurf(), rflu_modtecplot::rflu_tec_builddatafieldvol(), rflu_modtecplot::rflu_tec_builddatapatch(), rflu_modtecplot::rflu_tec_builddatapatchstats(), rflu_modtecplot::rflu_tec_closefilefield(), rflu_modtecplot::rflu_tec_closefilepatch(), rflu_modtecplot::rflu_tec_closefilepatchstats(), rflu_modtecplot::rflu_tec_closefilepnt(), rflu_modtecplot::rflu_tec_destroydatafieldsurf(), rflu_modtecplot::rflu_tec_destroydatafieldvol(), rflu_modtecplot::rflu_tec_destroydatapatch(), rflu_modtecplot::rflu_tec_init(), rflu_modtecplot::rflu_tec_openfilefield(), rflu_modtecplot::rflu_tec_openfilepatch(), rflu_modtecplot::rflu_tec_openfilepatchstats(), rflu_modtecplot::rflu_tec_openfilepnt(), rflu_modtecplot::rflu_tec_writefilefieldsurf(), rflu_modtecplot::rflu_tec_writefilefieldvol(), rflu_modtecplot::rflu_tec_writefilepatch(), and rflu_modtecplot::rflu_tec_writefilepnt().
Referenced by rflupost().