Rocstar: RFLU_AllocateMemory.F90 File Reference
RFLU_AllocateMemory.F90 File Reference
Functions/Subroutines
subroutine rflu_allocatememory (pRegion)
Function/Subroutine Documentation
subroutine rflu_allocatememory (type(t_region), pointer pRegion)
Definition at line 44 of file RFLU_AllocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modallocatememory::rflu_allocatememorygspeeds(), rflu_modallocatememory::rflu_allocatememorysol(), rflu_modallocatememory::rflu_allocatememorytstep(), rflu_modallocatememory::rflu_allocatememorytstep_c(), and rflu_modallocatememory::rflu_allocatememorytstep_i().
Referenced by rflu_allocatememorywrapper().