Rocstar: RFLU_CloseRestartInfo.F90 File Reference
RFLU_CloseRestartInfo.F90 File Reference
Functions/Subroutines
subroutine rflu_closerestartinfo (global)
Function/Subroutine Documentation
subroutine rflu_closerestartinfo (type(t_global), pointer global)
Definition at line 44 of file RFLU_CloseRestartInfo.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_readrestartinfo(), and rflu_writerestartinfo().