Rocstar: rflupick.F90 File Reference
rflupick.F90 File Reference
Functions/Subroutines
subroutine rflupick (caseString, stampString, verbLevel)
Function/Subroutine Documentation
subroutine rflupick (character(*) caseString, character(*) stampString, integer, intent(in) verbLevel)
Definition at line 46 of file rflupick.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_modregionmapping::rflu_applyregionmapping(), rflu_modstencilsbfaces::rflu_buildbf2cstencilwrapper(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_builddatastruct(), rflu_modstencilsfaces::rflu_buildf2cstencilwrapper(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modstencilsvert::rflu_buildstencilvert2cell(), rflu_modvertexlists::rflu_buildvert2celllist(), rflu_closepostinfo(), rflu_modstencilsbfaces::rflu_createbf2cstencilwrapper(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modstencilsfaces::rflu_createf2cstencilwrapper(), rflu_modfacelist::rflu_createfacelist(), rflu_modgeometry::rflu_creategeometry(), rflu_creategrid(), rflu_modregionmapping::rflu_createregionmapping(), rflu_modstencilsvert::rflu_createstencilvert2cell(), rflu_modvertexlists::rflu_createvert2celllist(), rflu_decideneedbgradface(), rflu_modstencilsbfaces::rflu_destroybf2cstencilwrapper(), rflu_modboundlists::rflu_destroybvertexlists(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), rflu_modfacelist::rflu_destroycell2facelist(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modstencilsfaces::rflu_destroyf2cstencilwrapper(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modgeometry::rflu_destroygeometry(), rflu_destroygrid(), rflu_modregionmapping::rflu_destroyregionmapping(), rflu_modstencilsvert::rflu_destroystencilvert2cell(), rflu_modvertexlists::rflu_destroyvert2celllist(), rflu_getuserinput(), rflu_modregionmapping::rflu_imposeregionmappingserial(), rflu_initglobal(), rflu_openpostinfo(), rflu_pickregionscoord(), rflu_pickregionsmanual(), rflu_pickspecialcells(), rflu_pickspecialfaces(), rflu_printgridinfo(), rflu_printheader(), rflu_printwarninfo(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), rflu_moddimensions::rflu_readdimensions(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_modinterfacesutilities::RFLU_ReadInputFile::rflu_readinputfile(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_modboundlists::rflu_renumberbfacelists(), rflu_modstencilsbfaces::rflu_setinfobf2cstencilwrapper(), rflu_modstencilscells::rflu_setinfoc2cstencilwrapper(), rflu_modstencilsfaces::rflu_setinfof2cstencilwrapper(), rflu_modstencilsvert::rflu_setinfostencilvert2cell(), rflu_modregionmapping::rflu_setregionmappingserial(), rflu_writepostinfo(), rflu_writeversionstring(), and StopWatch::stop().