Rocstar: RFLU_CheckValidity.F90 File Reference
RFLU_CheckValidity.F90 File Reference
Functions/Subroutines
subroutine rflu_checkvalidity (pRegion)
Function/Subroutine Documentation
subroutine rflu_checkvalidity (type(t_region), pointer pRegion)
Definition at line 47 of file RFLU_CheckValidity.F90.
References moderror::deregisterfunction(), moderror::errorstop(), modtools::isnan(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_r_m(), mixtperf_t_dpr(), moderror::registerfunction(), rflu_printlocinfo(), and v.
Referenced by rflu_checkvaliditywrapper(), and rflu_modnewtonkrylov::rflu_nk_timestepping().