Rocstar: RFLU_GetUserInput.F90 File Reference
RFLU_GetUserInput.F90 File Reference
Functions/Subroutines
subroutine rflu_getuserinput (regions, inPrep)
Function/Subroutine Documentation
subroutine rflu_getuserinput (type(t_region), dimension(:), pointer regions, logical, optional inPrep)
Definition at line 52 of file RFLU_GetUserInput.F90.
References moderror::deregisterfunction(), inrt_userinput(), peri_userinput(), plag_userinput(), modinterfacesradiation::RADI_UserInput::radi_userinput(), moderror::registerfunction(), rflu_checkderiveduserinput(), rflu_printuserinput(), rflu_setderiveduserinput(), rflu_userinput(), spec_userinput(), and turb_userinput().
Referenced by rflu_initflowsolver(), rflucells(), rfluconv(), rfluinit(), rflumap(), rflupart(), rflupick(), and rflupost().