Rocstar: RFLU_CreateGrid.F90 File Reference
RFLU_CreateGrid.F90 File Reference
Functions/Subroutines
subroutine rflu_creategrid (pRegion)
Function/Subroutine Documentation
subroutine rflu_creategrid (type(t_region), pointer pRegion)
Definition at line 51 of file RFLU_CreateGrid.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_allocatememorywrapper(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregions_ens(), rflu_postprocessregionscommon1(), rfluconv(), rfluinit(), rflumap(), rflupart(), rflupick(), and turb_initinputvalues().