Rocstar: RFLU_ComputeIntegral4OLES.F90 File Reference
RFLU_ComputeIntegral4OLES.F90 File Reference
Functions/Subroutines
subroutine rflu_computeintegral4oles (pRegion)
Function/Subroutine Documentation
subroutine rflu_computeintegral4oles (type(t_region), pointer pRegion)
Definition at line 44 of file RFLU_ComputeIntegral4OLES.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, key, Aff_transformation_2< R_ >::m(), moderror::registerfunction(), rflu_allocatedcuhrearrays(), rflu_computedcuhreinfo(), rflu_deallocatedcuhrearrays(), rflu_modoles::rflu_definecorrelation430(), rflu_modoles::rflu_definecorrelation431(), rflu_modoles::rflu_definecorrelation432(), rflu_modoles::rflu_geti4posoles(), rflu_modoles::rflu_mapl2ijk(), and rflu_modoles::rflu_setmapfunnz2funcorr43().
Referenced by rflu_computeintegrals1245oles().