Rocstar: RFLU_PrintLocInfo.F90 File Reference
RFLU_PrintLocInfo.F90 File Reference
Functions/Subroutines
subroutine rflu_printlocinfo (pRegion, locUnsorted, nLocUnsorted, locInfoMode, outputMode)
Function/Subroutine Documentation
subroutine rflu_printlocinfo (type(t_region), pointer pRegion, integer, dimension(1:nlocunsorted,min_val:max_val), intent(inout) locUnsorted, integer, intent(in) nLocUnsorted, integer, intent(in) locInfoMode, integer, intent(in) outputMode)
Definition at line 57 of file RFLU_PrintLocInfo.F90.
References modsortsearch::binarysearchinteger(), moderror::deregisterfunction(), moderror::errorstop(), ic, modsortsearch::mergesortedintegers(), modsortsearch::quicksortinteger(), moderror::registerfunction(), modsortsearch::simplifysortedintegers(), and v.
Referenced by rflu_modgeometry::rflu_buildgeometry(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_checkpositivity(), rflu_checkpositivity_gl(), rflu_checkvalidity(), rflu_checkvalidity_gl(), rflu_computeexactflowerror(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_printchangeinfo(), rflu_printflowinfo(), rflu_scalarcheckpositivity(), and spec_rflu_printflowinfo().