Rocstar: RFLU_CentralSecondPatch_GL.F90 File Reference
RFLU_CentralSecondPatch_GL.F90 File Reference
Functions/Subroutines
subroutine rflu_centralsecondpatch_gl (pRegion, pPatch)
Function/Subroutine Documentation
subroutine rflu_centralsecondpatch_gl (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 46 of file RFLU_CentralSecondPatch_GL.F90.
References bcondinflowperf_gl(), bcondoutflowperf_gl(), moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), max(), min(), mixtgasliq_c(), mixtgasliq_p(), mixtliq_c2_bp(), mixtliq_d_dobpppobttto(), mixtperf_c2_grt(), mixtperf_cv_cpr(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_p_drt(), mixtperf_r_cpg(), mixtperf_r_m(), moderror::registerfunction(), rflu_decideprint(), rflu_modgridspeedutils::rflu_descalegridspeed(), rflu_printlocinfo(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_modrindstates::rflu_setrindstateinjectperf(), rflu_modrindstates::rflu_setrindstateslipwallperf(), and sqrt().
Referenced by rflu_modhllcflux::rflu_hllc_computeflux2_gl(), and rflu_modroeflux::rflu_roe_computeflux2_gl().