Rocstar: RFLU_GetCvLoc.F90 File Reference
RFLU_GetCvLoc.F90 File Reference
Functions/Subroutines
INTEGER function rflu_getcvloc (global, fluidModel, var)
Function/Subroutine Documentation
INTEGER function rflu_getcvloc (type(t_global), pointer global, integer, intent(in) fluidModel, integer, intent(in) var)
Definition at line 44 of file RFLU_GetCvLoc.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_initflowscratch(), rflu_invflux_i(), rflu_modpetscpoisson::rflu_petsc_solvepressurepoisson(), rflu_printflowinfo(), rflu_modreadwriteflow::rflu_readflowascii(), rflu_modreadwriteflow::rflu_readflowbinary(), rflu_setvarinfo(), rflu_modreadwriteflow::rflu_writeflowascii(), and rflu_modreadwriteflow::rflu_writeflowbinary().