Rocstar: RFLU_UserInput.F90 File Reference
RFLU_UserInput.F90 File Reference
Functions/Subroutines
subroutine rflu_userinput (regions)
Function/Subroutine Documentation
subroutine rflu_userinput (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file RFLU_UserInput.F90.
References moderror::deregisterfunction(), readinputfile(), moderror::registerfunction(), rflu_checkuserinput(), rflu_derivedinputvalues(), and rflu_initinputvalues().
Referenced by rflu_getuserinput().