Rocstar: RFLU_DecideNeedBGradFace.F90 File Reference
RFLU_DecideNeedBGradFace.F90 File Reference
Functions/Subroutines
logical function rflu_decideneedbgradface (pRegion, pPatch)
Function/Subroutine Documentation
logical function rflu_decideneedbgradface (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 45 of file RFLU_DecideNeedBGradFace.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by rflu_modallocatememory::rflu_allocatememorytstep(), rflu_moddeallocatememory::rflu_deallocatememorytstep(), rflu_modexplicitmultistage::rflu_ems_computeresidual(), rflu_endflowsolver(), rflu_initflowsolver(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_modnscbc::rflu_nscbc_comprhs(), rflu_modresidual::rflu_res_computeresidual(), rflu_timestepping(), rflupick(), spec_rflu_allocatememorytstep(), spec_rflu_deallocatememorytstep(), turb_lesgeteddyvis(), turb_ranssavisflux(), viscousfluxes(), and viscousfluxesmp().