Rocstar: RFLU_EndFlowSolver.F90 File Reference
RFLU_EndFlowSolver.F90 File Reference
Functions/Subroutines
subroutine rflu_endflowsolver (levels)
Function/Subroutine Documentation
subroutine rflu_endflowsolver (type(t_level), dimension(:), pointer levels)
Definition at line 44 of file RFLU_EndFlowSolver.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_moddimensions::plag_calcnpclsglobal(), plag_modsurfstats::plag_destroysurfstats(), plag_moddimensions::plag_printnpclsglobal(), plag_moddimensions::plag_rflu_writedimensions(), plag_modsurfstats::plag_writesurfstatswrapper(), moderror::registerfunction(), rflu_modboundxvutils::rflu_bxv_destroyvarscv(), rflu_modboundxvutils::rflu_bxv_destroyvarsdv(), rflu_modboundxvutils::rflu_bxv_destroyvarststep(), rflu_modboundxvutils::rflu_bxv_writevarswrapper(), rflu_modprobes::rflu_closeprobefiles(), rflu_modcommlists::rflu_comm_destroyborders(), rflu_modcommlists::rflu_comm_destroycommlists(), rflu_deallocatememorywrapper(), rflu_decideneedbgradface(), rflu_modfacelist::rflu_destroyavface2borderlist(), rflu_modfacelist::rflu_destroyavface2patchlist(), rflu_modstencilsbfaces::rflu_destroybf2cstencilwrapper(), rflu_modbfacegradaccesslist::rflu_destroybfacegradaccesslist(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modedgelist::rflu_destroyedgelist(), rflu_modstencilsfaces::rflu_destroyf2cstencilwrapper(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modforcesmoments::rflu_destroyforcesmoments(), rflu_modgeometry::rflu_destroygeometry(), rflu_modforcesmoments::rflu_destroyglobalthrustflags(), rflu_destroygrid(), rflu_modstencilscells::rflu_destroylistcc2cstencil(), rflu_modstencilsfaces::rflu_destroylistcf2cstencil(), rflu_modpatchcoeffs::rflu_destroypatchcoeffs(), rflu_modoles::rflu_destroystencilsweightsoles(), rflu_modweights::rflu_destroywtsbf2cwrapper(), rflu_modweights::rflu_destroywtsc2cwrapper(), rflu_modweights::rflu_destroywtsf2cwrapper(), rflu_modmpi::rflu_mpi_destroybufferipclsend(), rflu_modmpi::rflu_mpi_destroybufferswrapper(), rflu_modnscbc::rflu_nscbc_decidehavenscbc(), rflu_modpetscnewtonkrylov::rflu_petsc_destroyjacobian(), rflu_modpetscnewtonkrylov::rflu_petsc_destroyvectors(), rflu_modpetscadmin::rflu_petsc_finalize(), rflu_printflowinfowrapper(), rflu_printgridinfo(), rflu_printwarninfo(), rflu_moddimensions::rflu_writedimensionswrapper(), rflu_modreadwriteflow::rflu_writeflowwrapper(), rflu_modreadwritegridspeeds::rflu_writegridspeedswrapper(), rflu_modreadwritegrid::rflu_writegridwrapper(), rflu_modpatchcoeffs::rflu_writepatchcoeffswrapper(), rflu_writerestartinfo(), and rflu_writestat().
Referenced by fluid_finalize(), and rflump().