Rocstar: RFLU_SetVarsWrapper.F90 File Reference
RFLU_SetVarsWrapper.F90 File Reference
Functions/Subroutines
subroutine rflu_setvarswrapper (pRegion, icgBeg, icgEnd)
Function/Subroutine Documentation
subroutine rflu_setvarswrapper (type(t_region), pointer pRegion, integer, intent(in) icgBeg, integer, intent(in) icgEnd)
Definition at line 46 of file RFLU_SetVarsWrapper.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_setvarscontwrapper(), and rflu_setvarsdiscwrapper().
Referenced by integratesourcetermsmp(), rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), and rflu_postprocessregionscommon2().