Rocstar: RFLU_InitBcDataHardCode.F90 File Reference
RFLU_InitBcDataHardCode.F90 File Reference
Functions/Subroutines
subroutine rflu_initbcdatahardcode (pRegion)
Function/Subroutine Documentation
subroutine rflu_initbcdatahardcode (type(t_region), pointer pRegion)
Definition at line 45 of file RFLU_InitBcDataHardCode.F90.
References CImg< T >::atan2(), Plane_3< R, T >::d(), moderror::deregisterfunction(), moderror::errorstop(), mixtperf_c_dgp(), mixtperf_p_drt(), mixtperf_r_cpg(), mixtperf_t_dpr(), moderror::registerfunction(), rflu_modexactflow::rflu_computeexactflowproudman(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_modflowhardcode::rflu_getparamshardcodeproudman(), rflu_modflowhardcode::rflu_getparamshardcoderingleb(), rflu_modflowhardcode::rflu_getparamshardcodessvortex(), sqrt(), v, x, and y.
Referenced by rfluinit().