Rocstar: rfluconv.F90 File Reference
rfluconv.F90 File Reference
Functions/Subroutines
subroutine rfluconv (caseString, stampString, verbLevel)
Function/Subroutine Documentation
subroutine rfluconv (character(*) caseString, character(*) stampString, integer, intent(in) verbLevel)
Definition at line 46 of file rfluconv.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_allocmemsolwrapper(), rflu_modregionmapping::rflu_applyregionmapping(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_builddatastruct(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modtetmesh::rflu_convrocflu2tetmesh(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modfacelist::rflu_createfacelist(), rflu_modgeometry::rflu_creategeometry(), rflu_creategrid(), rflu_modregionmapping::rflu_createregionmapping(), rflu_deallocmemsolwrapper(), rflu_modboundlists::rflu_destroybvertexlists(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modgeometry::rflu_destroygeometry(), rflu_destroygrid(), rflu_modregionmapping::rflu_destroyregionmapping(), rflu_getuserinput(), rflu_modregionmapping::rflu_imposeregionmappingserial(), rflu_initglobal(), rflu_printflowinfo(), rflu_printgridinfo(), rflu_printheader(), rflu_printwarninfo(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), rflu_moddimensions::rflu_readdimensions(), rflu_modreadwriteflow::rflu_readflowwrapper(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_modboundlists::rflu_renumberbfacelists(), rflu_modregionmapping::rflu_setregionmappingserial(), rflu_setvarinfowrapper(), rflu_modstl::rflu_stl_writesurfgridascii(), rflu_modreadwriteflow::rflu_writeflowwrapper(), rflu_modreadwritegrid::rflu_writegridwrapper(), rflu_modtetmesh::rflu_writesurfgridtetmesh(), rflu_writeversionstring(), and StopWatch::stop().