Rocstar: RFLU_PostProcessRegionsCommon2.F90 File Reference
RFLU_PostProcessRegionsCommon2.F90 File Reference
Functions/Subroutines
subroutine rflu_postprocessregionscommon2 (pRegion)
Function/Subroutine Documentation
subroutine rflu_postprocessregionscommon2 (type(t_region), pointer pRegion)
Definition at line 44 of file RFLU_PostProcessRegionsCommon2.F90.
References moderror::deregisterfunction(), plag_modsurfstats::plag_destroysurfstats(), moderror::registerfunction(), rflu_moddeallocatememory::rflu_deallocatememorygspeeds(), rflu_deallocmemsolwrapper(), rflu_deallocmemvertwrapper(), rflu_decidebuildgeometry(), rflu_modplottingvars::rflu_decidecomputeplottingvars(), rflu_modboundlists::rflu_destroybvertexlists(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modgeometry::rflu_destroygeometry(), rflu_destroygrid(), rflu_modpatchcoeffs::rflu_destroypatchcoeffs(), rflu_modplottingvars::rflu_destroyplottingvarmaps(), rflu_modplottingvars::rflu_destroyplottingvars(), rflu_printflowinfowrapper(), rflu_setvarinfowrapper(), and rflu_setvarswrapper().
Referenced by rflu_postprocessregions(), and rflu_postprocessregions_ens().