Rocstar: RFLU_PostProcessRegionsCommon1.F90 File Reference
RFLU_PostProcessRegionsCommon1.F90 File Reference
Functions/Subroutines
subroutine rflu_postprocessregionscommon1 (pRegion, postInfoFileExists)
Function/Subroutine Documentation
subroutine rflu_postprocessregionscommon1 (type(t_region), pointer pRegion, logical, intent(in) postInfoFileExists)
Definition at line 44 of file RFLU_PostProcessRegionsCommon1.F90.
References moderror::deregisterfunction(), plag_modsurfstats::plag_createsurfstats(), plag_modsurfstats::plag_readsurfstatswrapper(), moderror::registerfunction(), rflu_modallocatememory::rflu_allocatememorygspeeds(), rflu_allocmemsolwrapper(), rflu_allocmemvertwrapper(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modplottingvars::rflu_buildplottingvarmaps(), rflu_modstencilsvert::rflu_buildstencilvert2cell(), rflu_modvertexlists::rflu_buildvert2celllist(), rflu_closepostinfo(), rflu_modprobes::rflu_closeprobefiles(), rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), rflu_modplottingvars::rflu_computeplottingvarswrapper(), rflu_modweights::rflu_computewtsc2cwrapper(), rflu_modplottingvars::rflu_countplottingvars(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modfacelist::rflu_createfacelist(), rflu_modgeometry::rflu_creategeometry(), rflu_creategrid(), rflu_modpatchcoeffs::rflu_createpatchcoeffs(), rflu_modplottingvars::rflu_createplottingvarmaps(), rflu_modplottingvars::rflu_createplottingvars(), rflu_modstencilsvert::rflu_createstencilvert2cell(), rflu_modvertexlists::rflu_createvert2celllist(), rflu_modweights::rflu_createwtsc2cwrapper(), rflu_deallocmemsolwrapper(), rflu_deallocmemvertwrapper(), rflu_decidebuildgeometry(), rflu_decidebuildstencilsweights(), rflu_modplottingvars::rflu_decidecomputeplottingvars(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), rflu_modfacelist::rflu_destroycell2facelist(), rflu_destroygrid(), rflu_modstencilsvert::rflu_destroystencilvert2cell(), rflu_modvertexlists::rflu_destroyvert2celllist(), rflu_modweights::rflu_destroywtsc2cwrapper(), rflu_modextractflowdata::rflu_extractflowdata(), rflu_modprobes::rflu_findprobecells(), rflu_interpolatewrapper(), rflu_openpostinfo(), rflu_modprobes::rflu_openprobefiles(), rflu_printflowinfowrapper(), rflu_printgridinfo(), rflu_printheader(), rflu_modplottingvars::rflu_printplottingvarsinfo(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), rflu_moddimensions::rflu_readdimensionswrapper(), rflu_modreadwriteflow::rflu_readflowwrapper(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modpatchcoeffs::rflu_readpatchcoeffswrapper(), rflu_readpostinfo(), rflu_modboundlists::rflu_renumberbfacelists(), rflu_modstencilscells::rflu_setinfoc2cstencilwrapper(), rflu_modstencilsvert::rflu_setinfostencilvert2cell(), rflu_setpatchplotflags(), rflu_setvarinfowrapper(), and rflu_setvarswrapper().
Referenced by rflu_postprocessregions(), and rflu_postprocessregions_ens().