Rocstar: RFLU_InitFlowHardCode.F90 File Reference
RFLU_InitFlowHardCode.F90 File Reference
Functions/Subroutines
subroutine rflu_initflowhardcode (pRegion)
Function/Subroutine Documentation
subroutine rflu_initflowhardcode (type(t_region), pointer pRegion)
Definition at line 45 of file RFLU_InitFlowHardCode.F90.
References Line_2< R, T >::a(), CImg< T >::atan2(), Line_2< R, T >::c(), Plane_3< R, T >::d(), moderror::deregisterfunction(), moderror::errorstop(), Color::g(), max(), min(), mixtgasliq_eo_cvmtvm2(), mixtperf_cv_cpr(), mixtperf_d_cgp(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_p_drt(), mixtperf_r_cpg(), mixtperf_r_m(), moderror::registerfunction(), rflu_modexactflow::rflu_computeexactflowculick(), rflu_modexactflow::rflu_computeexactflowpacoust(), rflu_modexactflow::rflu_computeexactflowproudman(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_modflowhardcode::rflu_getparamshardcodepacoust(), rflu_modflowhardcode::rflu_getparamshardcodeproudman(), rflu_modflowhardcode::rflu_getparamshardcoderingleb(), rflu_modflowhardcode::rflu_getparamshardcodessvortex(), rflu_modbessel::rflu_jyzom(), rflu_modexactflow::rflu_setexactflowlinear(), rflu_modexactflow::rflu_setexactflowtrig(), sqrt(), v, x, Bbox_2::xmin(), y, Bbox_2::ymin(), z, and Bbox_3::zmin().
Referenced by rflu_initflowhardcodewrapper().