Rocstar: RFLU_ComputeIntegral3OLES.F90 File Reference
RFLU_ComputeIntegral3OLES.F90 File Reference
Functions/Subroutines
subroutine rflu_computeintegral3oles (region)
Function/Subroutine Documentation
subroutine rflu_computeintegral3oles (type(t_region) region)
Definition at line 49 of file RFLU_ComputeIntegral3OLES.F90.
References Line_2< R, T >::a(), Color::b(), Plane_3< R, T >::d(), moderror::deregisterfunction(), moderror::errorstop(), Color::g(), j, k, Aff_transformation_2< R_ >::m(), modtools::makenonzero(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), rflu_modoles::rflu_geti1posoles(), rflu_modoles::rflu_geti4posoles(), rflu_modoles::rflu_getlposoles(), rflu_modoles::rflu_getqposoles(), and Kdtree_d< Traits >::ExtPoint::term().