Rocstar: RFLU_ReadRestartInfo.F90 File Reference
RFLU_ReadRestartInfo.F90 File Reference
Functions/Subroutines
subroutine rflu_readrestartinfo (global)
Function/Subroutine Documentation
subroutine rflu_readrestartinfo (type(t_global), pointer global)
Definition at line 44 of file RFLU_ReadRestartInfo.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_closerestartinfo(), and rflu_openrestartinfo().
Referenced by rflu_initflowsolver(), rfluinit(), rflumap(), and rflupart().