Rocstar: RFLU_ComputeStencilSize.F90 File Reference
RFLU_ComputeStencilSize.F90 File Reference
Functions/Subroutines
integer function rflu_computestencilsize (global, factor, order)
Function/Subroutine Documentation
integer function rflu_computestencilsize (type(t_global), pointer global, integer, intent(in) factor, integer, intent(in) order)
Definition at line 50 of file RFLU_ComputeStencilSize.F90.
References moderror::deregisterfunction(), Generic_element_2::order(), and moderror::registerfunction().
Referenced by rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_modstencilsutils::rflu_computestencilsize(), rflu_modstencilsutils::rflu_computestencilweights(), rflu_modstencilsbfaces::rflu_setinfobf2cstencil(), rflu_modstencilscells::rflu_setinfoc2cstencil(), rflu_modstencilsfaces::rflu_setinfof2cstencil(), and rflu_modstencilsvert::rflu_setinfostencilvert2cell().