Rocstar: RFLU_TimeStepViscous.F90 File Reference
RFLU_TimeStepViscous.F90 File Reference
Functions/Subroutines
subroutine rflu_timestepviscous (pRegion)
Function/Subroutine Documentation
subroutine rflu_timestepviscous (type(t_region), pointer pRegion)
Definition at line 45 of file RFLU_TimeStepViscous.F90.
References moderror::deregisterfunction(), Direction_2< R, T >::dx(), Direction_2< R, T >::dy(), Direction_3< R, T >::dz(), moderror::errorstop(), mixtperf_c_grt(), mixtperf_g_cpr(), mixtperf_r_m(), moderror::registerfunction(), rflu_modgridspeedutils::rflu_descalegridspeed(), rflu_modrindstates::rflu_setrindstateinjectperf(), and sqrt().
Referenced by explicitmultistage(), rflu_modnewtonkrylov::rflu_nk_timestepping(), and rflu_timestepping().