Rocstar: RFLU_DecideBuildGeometry.F90 File Reference
RFLU_DecideBuildGeometry.F90 File Reference
Functions/Subroutines
logical function rflu_decidebuildgeometry (global)
Function/Subroutine Documentation
logical function rflu_decidebuildgeometry (type(t_global), pointer global)
Definition at line 45 of file RFLU_DecideBuildGeometry.F90.
Referenced by rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), and rflu_postprocessregionscommon2().