Rocstar: RFLU_CentralFirstPatch_GL.F90 File Reference
RFLU_CentralFirstPatch_GL.F90 File Reference
Functions/Subroutines
subroutine rflu_centralfirstpatch_gl (pRegion, pPatch)
Function/Subroutine Documentation
subroutine rflu_centralfirstpatch_gl (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 46 of file RFLU_CentralFirstPatch_GL.F90.
References bcondinflowperf_gl(), bcondoutflowperf_gl(), moderror::deregisterfunction(), moderror::errorstop(), max(), min(), mixtliq_d_dobpppobttto(), mixtperf_cv_cpr(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_p_drt(), mixtperf_r_cpg(), mixtperf_r_m(), moderror::registerfunction(), rflu_decideprint(), rflu_modgridspeedutils::rflu_descalegridspeed(), rflu_printlocinfo(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_modrindstates::rflu_setrindstateinjectperf(), rflu_modrindstates::rflu_setrindstateslipwallperf(), and sqrt().
Referenced by rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modroeflux::rflu_roe_computeflux1_gl(), and rflu_modroeflux::rflu_roe_computeflux2_gl().