Rocstar: RFLU_AllocateDCUHREArrays.F90 File Reference
RFLU_AllocateDCUHREArrays.F90 File Reference
Functions/Subroutines
subroutine rflu_allocatedcuhrearrays (nDim, nFunNZ, nFun)
subroutine rflu_deallocatedcuhrearrays
Function/Subroutine Documentation
subroutine rflu_allocatedcuhrearrays (integer, intent(in) nDim, integer, intent(in) nFunNZ, integer, intent(in) nFun)
Definition at line 45 of file RFLU_AllocateDCUHREArrays.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_computeintegral1oles(), rflu_computeintegral2oles(), rflu_computeintegral4oles(), and rflu_computeintegral5oles().
subroutine rflu_deallocatedcuhrearrays ()
Definition at line 108 of file RFLU_AllocateDCUHREArrays.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_computeintegral1oles(), rflu_computeintegral2oles(), rflu_computeintegral4oles(), and rflu_computeintegral5oles().