Rocstar: RFLU_InitFlowSolver.F90 File Reference
RFLU_InitFlowSolver.F90 File Reference
Functions/Subroutines
subroutine rflu_initflowsolver (casename, verbLevel, global, levels)
Function/Subroutine Documentation
subroutine rflu_initflowsolver (character(chrlen), intent(in) casename, integer, intent(in) verbLevel, type(t_global), pointer global, type(t_level), dimension(:), pointer levels)
Definition at line 46 of file RFLU_InitFlowSolver.F90.
References Function::communicator(), moderror::deregisterfunction(), moderror::errorstop(), modstatsroutines::initstatistics(), plag_modsurfstats::plag_createsurfstats(), plag_modsurfstats::plag_readsurfstatswrapper(), moderror::registerfunction(), rflu_moddimensionality::rflu_123d_checkgeometrywrapper(), rflu_moddimensionality::rflu_123d_checktopology(), rflu_allocatememorytbc(), rflu_allocatememorywrapper(), rflu_modregionmapping::rflu_applyregionmapping(), rflu_modfacelist::rflu_buildavface2borderlist(), rflu_modfacelist::rflu_buildavface2patchlist(), rflu_modstencilsbfaces::rflu_buildbf2cstencilwrapper(), rflu_modbfacegradaccesslist::rflu_buildbfacegradaccesslist(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_builddatastruct(), rflu_modedgelist::rflu_buildedge2celllist(), rflu_modedgelist::rflu_buildedgelist(), rflu_modstencilsfaces::rflu_buildf2cstencilwrapper(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modstencilscells::rflu_buildlistcc2cstencil(), rflu_modstencilsfaces::rflu_buildlistcf2cstencil(), rflu_modoles::rflu_buildstencilsoles(), rflu_modoles::rflu_buildsymmetrymapsoles(), rflu_modvertexlists::rflu_buildvert2celllist(), rflu_modboundxvutils::rflu_bxv_createvarscv(), rflu_modboundxvutils::rflu_bxv_createvarsdv(), rflu_modboundxvutils::rflu_bxv_createvarststep(), rflu_modboundxvutils::rflu_bxv_readvarswrapper(), rflu_modboundxvutils::rflu_bxv_setdependentvars(), rflu_checkcouplinginput(), rflu_modpatchutils::rflu_checkpatchbcconsistency(), rflu_modcommlists::rflu_comm_createborders(), rflu_modcommlists::rflu_comm_createcommlists(), rflu_modcommlists::rflu_comm_getproclocregids(), rflu_modcommlists::rflu_comm_readcommlists(), rflu_modgeometry::rflu_computefacedist(), rflu_modoles::rflu_computegeometrictermsoles(), rflu_computeintegrals1245oles(), rflu_computeintegralvalues(), rflu_modpatchutils::rflu_computepatchnormalsglobal(), rflu_modpatchutils::rflu_computepatchnormalslocal(), rflu_modweights::rflu_computewtsbf2cwrapper(), rflu_modweights::rflu_computewtsc2cwrapper(), rflu_modweights::rflu_computewtsf2cwrapper(), rflu_modfacelist::rflu_createavface2borderlist(), rflu_modfacelist::rflu_createavface2patchlist(), rflu_modstencilsbfaces::rflu_createbf2cstencilwrapper(), rflu_modbfacegradaccesslist::rflu_createbfacegradaccesslist(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modedgelist::rflu_createedge2celllist(), rflu_modedgelist::rflu_createedgelist(), rflu_modstencilsfaces::rflu_createf2cstencilwrapper(), rflu_modgeometry::rflu_createfacedist(), rflu_modfacelist::rflu_createfacelist(), rflu_modforcesmoments::rflu_createforcesmoments(), rflu_modgeometry::rflu_creategeometry(), rflu_modforcesmoments::rflu_createglobalthrustflags(), rflu_creategrid(), rflu_modpatchcoeffs::rflu_createpatchcoeffs(), rflu_modregionmapping::rflu_createregionmapping(), rflu_modvertexlists::rflu_createvert2celllist(), rflu_modweights::rflu_createwtsbf2cwrapper(), rflu_modweights::rflu_createwtsc2cwrapper(), rflu_modweights::rflu_createwtsf2cwrapper(), rflu_decideneedbgradface(), rflu_modgridspeedutils::rflu_decideneedgridspeeds(), rflu_modreadwritebcdatafile::rflu_decidereadwritebcdatafile(), rflu_modedgelist::rflu_destroyedge2celllist(), rflu_modregionmapping::rflu_destroyregionmapping(), rflu_modvertexlists::rflu_destroyvert2celllist(), rflu_modoles::rflu_enforcesymmetryoles(), rflu_modprobes::rflu_findprobecells(), rflu_modoles::rflu_findprototypefacesoles(), rflu_modrocstaradmin::rflu_genx_createattrwrapper(), rflu_modrocstaradmin::rflu_genx_creategridsurf(), rflu_modrocstaradmin::rflu_genx_createpconn(), rflu_modrocstaradmin::rflu_genx_createwindows(), rflu_modrocstaradmin::rflu_genx_createwindowsdone(), rflu_modrocstario::rflu_genx_getdatainterf(), rflu_modrocstario::rflu_genx_getdimensionsderived(), rflu_modrocstario::rflu_genx_getglobaldata(), rflu_modrocstartools::rflu_genx_initbflag(), rflu_modrocstaradmin::rflu_genx_initrocman(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modrocstaradmin::rflu_genx_registerdatawrapper(), rflu_modrocstaradmin::rflu_genx_registergridsurf(), rflu_modrocstaradmin::rflu_genx_registergridvol(), rflu_modrocstaradmin::rflu_genx_storecommunicator(), rflu_modrocstaradmin::rflu_genx_storenameshandles(), rflu_getboundaryvalues(), rflu_getuserinput(), rflu_modincelltest::rflu_ict_computetolerance(), rflu_modregionmapping::rflu_imposeregionmappingserial(), rflu_initglobal(), rflu_modgridspeedutils::rflu_initgridspeedscalefactor(), rflu_movegridwrapper(), rflu_modmpi::rflu_mpi_clearrequestwrapper(), rflu_modmpi::rflu_mpi_copywrapper(), rflu_modmpi::rflu_mpi_createbufferipclsend(), rflu_modmpi::rflu_mpi_createbufferswrapper(), rflu_modmpi::rflu_mpi_isendwrapper(), rflu_modmpi::rflu_mpi_recvwrapper(), rflu_modmpi::rflu_mpi_settagswrapper(), rflu_modnscbc::rflu_nscbc_decidehavenscbc(), rflu_openconverfile(), rflu_modprobes::rflu_openprobefiles(), rflu_openstatsfileoles(), rflu_opentotalmassfile(), rflu_modpetscnewtonkrylov::rflu_petsc_createjacobian(), rflu_modpetscnewtonkrylov::rflu_petsc_createvectors(), rflu_modpetscadmin::rflu_petsc_init(), rflu_printflowinfo(), rflu_printgridinfo(), rflu_printheader(), rflu_modprobes::rflu_printprobeinfo(), rflu_putboundaryvalues(), rflu_randominit(), rflu_modreadwritebcdatafile::rflu_readbcdatafile(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), rflu_moddimensions::rflu_readdimensionswrapper(), rflu_modreadwriteflow::rflu_readflowwrapper(), rflu_modreadwritegridspeeds::rflu_readgridspeedswrapper(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_readintegrals1245oles(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_readrestartinfo(), rflu_readtbcinputfile(), rflu_modrelatedpatches::rflu_relp_transformwrapper(), rflu_modboundlists::rflu_renumberbfacelists(), rflu_modforcesmoments::rflu_setglobalthrustflags(), rflu_modstencilsbfaces::rflu_setinfobf2cstencilwrapper(), rflu_modstencilscells::rflu_setinfoc2cstencilwrapper(), rflu_modstencilsfaces::rflu_setinfof2cstencilwrapper(), rflu_setmoduletype(), rflu_setmovegridoptions(), rflu_setrestarttimeflag(), rflu_setvarinfowrapper(), rflu_setvarscontwrapper(), rflu_setvarsdiscwrapper(), rflu_setvarswrapper(), rflu_modsymmetryperiodic::rflu_sype_havesypepatches(), rflu_modsymmetryperiodic::rflu_sype_readtransforms(), rflu_writeintegrals1245oles(), rflu_writeversionstring(), modstatsroutines::statmapping(), and writetotalmass().
Referenced by rflump(), and rocflu_load_module().