Rocstar: RFLU_CentralFirstPatch.F90 File Reference
RFLU_CentralFirstPatch.F90 File Reference
Functions/Subroutines
subroutine rflu_centralfirstpatch (pRegion, pPatch)
Function/Subroutine Documentation
subroutine rflu_centralfirstpatch (type(t_region), pointer pRegion, type(t_patch), pointer pPatch)
Definition at line 46 of file RFLU_CentralFirstPatch.F90.
References bcondfarfieldperf(), bcondinflowperf(), bcondoutflowperf(), moderror::deregisterfunction(), moderror::errorstop(), Color::g(), max(), min(), mixtperf_d_prt(), mixtperf_eo_dgpuvw(), mixtperf_g_cpr(), mixtperf_p_deogvm2(), mixtperf_p_drt(), mixtperf_r_m(), moderror::registerfunction(), rflu_decideprint(), rflu_modgridspeedutils::rflu_descalegridspeed(), rflu_printlocinfo(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_modrindstates::rflu_setrindstateinjectperf(), rflu_modrindstates::rflu_setrindstateslipwallperf(), and rhs.
Referenced by rflu_modausmflux::rflu_ausm_computeflux1(), rflu_modausmflux::rflu_ausm_computeflux2_mpsd(), rflu_modausmflux::rflu_ausm_computeflux2_mtcp(), rflu_modausmflux::rflu_ausm_computeflux2_tcp(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_invflux_i(), rflu_modroeflux::rflu_roe_computeflux1_tcp(), rflu_modroeflux::rflu_roe_computeflux2_tcp(), rflu_modroeflux::rflu_roe_computefluxc1(), and rflu_modroeflux::rflu_roe_computefluxc2_tcp().