Rocstar: RFLU_ReadConvGridWrapper.F90 File Reference
RFLU_ReadConvGridWrapper.F90 File Reference
Functions/Subroutines
subroutine rflu_readconvgridwrapper (pRegion)
Function/Subroutine Documentation
subroutine rflu_readconvgridwrapper (type(t_region), pointer pRegion)
Definition at line 44 of file RFLU_ReadConvGridWrapper.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_modcentaur::rflu_convcentaur2rocflu(), rflu_modcobalt::rflu_convcobalt2rocflu(), rflu_modgambit::rflu_convgambit2rocflu(), rflu_modmesh3d::rflu_convmesh3d2rocflu(), rflu_modtetmesh::rflu_convtetmesh2rocflu(), rflu_modvgridns::rflu_convvgridns2rocflu(), rflu_modrocstario::rflu_genx_decidereadfile(), rflu_modrocstario::rflu_genx_getgrid(), rflu_modcentaur::rflu_readgridcentaurascii(), rflu_modcentaur::rflu_readgridcentaurbinary(), rflu_modcobalt::rflu_readgridcobalt(), rflu_modgambit::rflu_readgridgambitneutral(), rflu_modmesh3d::rflu_readgridmesh3d(), rflu_modtetmesh::rflu_readgridtetmesh(), and rflu_modvgridns::rflu_readgridvgridns().
Referenced by rflupart().