Rocstar: RFLU_DecidePrint.F90 File Reference
RFLU_DecidePrint.F90 File Reference
Functions/Subroutines
logical function rflu_decideprint (global)
Function/Subroutine Documentation
logical function rflu_decideprint (type(t_global), pointer global)
Definition at line 46 of file RFLU_DecidePrint.F90.
References moderror::deregisterfunction(), and moderror::registerfunction().
Referenced by plag_rflu_update(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_modnewtonkrylov::rflu_nk_timestepping(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_timestepping(), and spec_rflu_enforcebounds().