Rocstar: RFLU_OpenPostInfo.F90 File Reference
RFLU_OpenPostInfo.F90 File Reference
Functions/Subroutines
subroutine rflu_openpostinfo (global, fileStatus, fileExists)
Function/Subroutine Documentation
subroutine rflu_openpostinfo (type(t_global), pointer global, integer, intent(in) fileStatus, logical, intent(out) fileExists)
Definition at line 49 of file RFLU_OpenPostInfo.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_postprocessregions(), rflu_postprocessregions_ens(), rflu_postprocessregionscommon1(), and rflupick().