Rocstar: RFLU_PostProcessRegions_ENS.F90 File Reference
RFLU_PostProcessRegions_ENS.F90 File Reference
Functions/Subroutines
subroutine rflu_postprocessregions_ens (levels)
Function/Subroutine Documentation
subroutine rflu_postprocessregions_ens (type(t_level), dimension(:), pointer levels)
Definition at line 48 of file RFLU_PostProcessRegions_ENS.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), rflu_modplottingvars::rflu_buildplottingvarmaps(), rflu_closepostinfo(), rflu_modplottingvars::rflu_countplottingvars(), rflu_creategrid(), rflu_modplottingvars::rflu_createplottingvarmaps(), rflu_destroygrid(), rflu_modplottingvars::rflu_destroyplottingvarmaps(), rflu_modensight::rflu_ens_builddatainfo(), rflu_modensight::rflu_ens_closefileflowwrapper(), rflu_modensight::rflu_ens_closefilegeometry(), rflu_modensight::rflu_ens_destroydatainfo(), rflu_modensight::rflu_ens_initpartnumber(), rflu_modensight::rflu_ens_mapregion2server(), rflu_modensight::rflu_ens_openfileflowwrapper(), rflu_modensight::rflu_ens_openfilegeometry(), rflu_modensight::rflu_ens_storepartnumber(), rflu_modensight::rflu_ens_writefilecase(), rflu_modensight::rflu_ens_writeflowwrapper(), rflu_modensight::rflu_ens_writegridwrapper(), rflu_openpostinfo(), rflu_postprocessregionscommon1(), rflu_postprocessregionscommon2(), rflu_modplottingvars::rflu_printplottingvarsinfo(), rflu_moddimensions::rflu_readdimensionswrapper(), and rflu_readpostinfo().
Referenced by rflupost().