Rocstar: RFLU_MergePostProcessRegions.F90 File Reference
RFLU_MergePostProcessRegions.F90 File Reference
Functions/Subroutines
subroutine rflu_mergepostprocessregions (levels)
Function/Subroutine Documentation
subroutine rflu_mergepostprocessregions (type(t_level), dimension(:), pointer levels)
Definition at line 44 of file RFLU_MergePostProcessRegions.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_moddimensions::plag_printdimensions(), plag_moddimensions::plag_setdimensions(), moderror::registerfunction(), rflu_modallocatememory::rflu_allocatememorygspeeds(), rflu_allocmemsolwrapper(), rflu_allocmemvertwrapper(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_modstencilscells::rflu_buildc2cstencilwrapper(), rflu_modfacelist::rflu_buildcell2facelist(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modplottingvars::rflu_buildplottingvarmaps(), rflu_modstencilsvert::rflu_buildstencilvert2cell(), rflu_modvertexlists::rflu_buildvert2celllist(), rflu_modprobes::rflu_closeprobefiles(), rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), rflu_modplottingvars::rflu_computeplottingvarswrapper(), rflu_modweights::rflu_computewtsc2cwrapper(), rflu_modplottingvars::rflu_countplottingvars(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modstencilscells::rflu_createc2cstencilwrapper(), rflu_modfacelist::rflu_createcell2facelist(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modfacelist::rflu_createfacelist(), rflu_modgeometry::rflu_creategeometry(), rflu_creategrid(), rflu_modpatchcoeffs::rflu_createpatchcoeffs(), rflu_modplottingvars::rflu_createplottingvarmaps(), rflu_modplottingvars::rflu_createplottingvars(), rflu_modstencilsvert::rflu_createstencilvert2cell(), rflu_modvertexlists::rflu_createvert2celllist(), rflu_modweights::rflu_createwtsc2cwrapper(), rflu_moddeallocatememory::rflu_deallocatememorygspeeds(), rflu_deallocmemsolwrapper(), rflu_deallocmemvertwrapper(), rflu_decidebuildgeometry(), rflu_modplottingvars::rflu_decidecomputeplottingvars(), rflu_modboundlists::rflu_destroybvertexlists(), rflu_modstencilscells::rflu_destroyc2cstencilwrapper(), rflu_modfacelist::rflu_destroycell2facelist(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modgeometry::rflu_destroygeometry(), rflu_destroygrid(), rflu_modpatchcoeffs::rflu_destroypatchcoeffs(), rflu_modplottingvars::rflu_destroyplottingvarmaps(), rflu_modplottingvars::rflu_destroyplottingvars(), rflu_modstencilsvert::rflu_destroystencilvert2cell(), rflu_modvertexlists::rflu_destroyvert2celllist(), rflu_modweights::rflu_destroywtsc2cwrapper(), rflu_modensight::rflu_ens_builddatainfo(), rflu_modensight::rflu_ens_closefileflowwrapper(), rflu_modensight::rflu_ens_closefilegeometry(), rflu_modensight::rflu_ens_destroydatainfo(), rflu_modensight::rflu_ens_openfileflowwrapper(), rflu_modensight::rflu_ens_openfilegeometry(), rflu_modensight::rflu_ens_storepartnumber(), rflu_modensight::rflu_ens_writefilecase(), rflu_modensight::rflu_ens_writeflowwrapper(), rflu_modensight::rflu_ens_writegridwrapper(), rflu_modextractflowdata::rflu_extractflowdata(), rflu_modprobes::rflu_findprobecells(), rflu_interpolatewrapper(), rflu_modmergeregions::rflu_merg_mergegrid(), rflu_modmergeregions::rflu_merg_mergepatchcoeffs(), rflu_modmergeregions::rflu_merg_mergesolwrapper(), rflu_modprobes::rflu_openprobefiles(), rflu_printflowinfowrapper(), rflu_printgridinfo(), rflu_printheader(), rflu_modplottingvars::rflu_printplottingvarsinfo(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), rflu_moddimensions::rflu_readdimensionswrapper(), rflu_modreadwriteflow::rflu_readflowwrapper(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modpatchcoeffs::rflu_readpatchcoeffswrapper(), rflu_modboundlists::rflu_renumberbfacelists(), rflu_modrenumberings::rflu_rnmb_createpbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_createpc2scmap(), rflu_modrenumberings::rflu_rnmb_createpv2svmap(), rflu_modrenumberings::rflu_rnmb_destroypbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_destroypc2scmap(), rflu_modrenumberings::rflu_rnmb_destroypv2svmap(), rflu_modrenumberings::rflu_rnmb_readpxx2sxxmaps(), rflu_modstencilscells::rflu_setinfoc2cstencilwrapper(), rflu_modstencilsvert::rflu_setinfostencilvert2cell(), rflu_setpatchplotflags(), rflu_setvarinfowrapper(), rflu_setvars(), rflu_setvarswrapper(), rflu_modtecplot::rflu_tec_builddatafieldsurf(), rflu_modtecplot::rflu_tec_builddatafieldvol(), rflu_modtecplot::rflu_tec_builddatapatch(), rflu_modtecplot::rflu_tec_builddatapatchstats(), rflu_modtecplot::rflu_tec_closefilefield(), rflu_modtecplot::rflu_tec_closefilepatch(), rflu_modtecplot::rflu_tec_closefilepatchstats(), rflu_modtecplot::rflu_tec_closefilepnt(), rflu_modtecplot::rflu_tec_destroydatafieldsurf(), rflu_modtecplot::rflu_tec_destroydatafieldvol(), rflu_modtecplot::rflu_tec_destroydatapatch(), rflu_modtecplot::rflu_tec_init(), rflu_modtecplot::rflu_tec_openfilefield(), rflu_modtecplot::rflu_tec_openfilepatch(), rflu_modtecplot::rflu_tec_openfilepatchstats(), rflu_modtecplot::rflu_tec_openfilepnt(), rflu_modtecplot::rflu_tec_writefilefieldsurf(), rflu_modtecplot::rflu_tec_writefilefieldvol(), rflu_modtecplot::rflu_tec_writefilepatch(), rflu_modtecplot::rflu_tec_writefilepnt(), rflu_moddimensions::rflu_writedimensionswrapper(), rflu_modreadwriteflow::rflu_writeflowwrapper(), rflu_modreadwritegrid::rflu_writegridwrapper(), and rflu_modcellmapping::rflu_writeloc2globcellmapping().
Referenced by rflupost().