Rocstar: RFLU_ComputeExactFlowProbeError.F90 File Reference
RFLU_ComputeExactFlowProbeError.F90 File Reference
Functions/Subroutines
subroutine rflu_computeexactflowprobeerror (pRegion)
Function/Subroutine Documentation
subroutine rflu_computeexactflowprobeerror (type(t_region), pointer pRegion)
Definition at line 46 of file RFLU_ComputeExactFlowProbeError.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, max(), min(), mixtperf_d_cgp(), mixtperf_r_cpg(), moderror::registerfunction(), rflu_modexactflow::rflu_computeexactflowpacoust(), rflu_modflowhardcode::rflu_getparamshardcodepacoust(), rflu_modbessel::rflu_jyzom(), sqrt(), Attribute::status(), x, y, and z.
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().