Rocstar: RFLU_ComputeIntegral2OLES.F90 File Reference
RFLU_ComputeIntegral2OLES.F90 File Reference
Functions/Subroutines
subroutine rflu_computeintegral2oles (pRegion)
Function/Subroutine Documentation
subroutine rflu_computeintegral2oles (type(t_region), pointer pRegion)
Definition at line 44 of file RFLU_ComputeIntegral2OLES.F90.
References moderror::deregisterfunction(), moderror::errorstop(), j, key, moderror::registerfunction(), rflu_allocatedcuhrearrays(), rflu_computedcuhreinfo(), rflu_deallocatedcuhrearrays(), rflu_modoles::rflu_definecorrelation220(), rflu_modoles::rflu_definecorrelation221(), rflu_modoles::rflu_geti1posoles(), rflu_modoles::rflu_getlposoles(), rflu_modoles::rflu_mapk2ij(), and rflu_modoles::rflu_setmapfunnz2funcorr22().
Referenced by rflu_computeintegrals1245oles().