Rocstar: RFLU_ComputeExactFlowError.F90 File Reference
RFLU_ComputeExactFlowError.F90 File Reference
Functions/Subroutines
subroutine rflu_computeexactflowerror (pRegion)
Function/Subroutine Documentation
subroutine rflu_computeexactflowerror (type(t_region), pointer pRegion)
Definition at line 45 of file RFLU_ComputeExactFlowError.F90.
References moderror::deregisterfunction(), moderror::errorstop(), max(), min(), mixtperf_d_cgp(), mixtperf_eo_dgpuvw(), mixtperf_p_drt(), mixtperf_r_cpg(), moderror::registerfunction(), rflu_modexactflow::rflu_computeexactflowpacoust(), rflu_modexactflow::rflu_computeexactflowproudman(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_modexactflow::rflu_computeexactflowssvortex(), rflu_moddifferentiationcells::rflu_computegradcellswrapper(), rflu_modflowhardcode::rflu_getparamshardcodepacoust(), rflu_modflowhardcode::rflu_getparamshardcodeproudman(), rflu_modflowhardcode::rflu_getparamshardcoderingleb(), rflu_modflowhardcode::rflu_getparamshardcodessvortex(), rflu_modbessel::rflu_jyzom(), rflu_printlocinfo(), rflu_modexactflow::rflu_setexactflowlinear(), rflu_modexactflow::rflu_setexactflowtrig(), rflu_modboundarytests::rflu_testisboundarycell(), sqrt(), Kdtree_d< Traits >::ExtPoint::term(), x, y, and z.
Referenced by rflu_mergepostprocessregions(), and rflu_postprocessregionscommon1().