Rocstar: RFLU_ReadTbcInputFile.F90 File Reference
RFLU_ReadTbcInputFile.F90 File Reference
Functions/Subroutines
subroutine rflu_readtbcinputfile (pRegion)
Function/Subroutine Documentation
subroutine rflu_readtbcinputfile (type(t_region), pointer pRegion)
Definition at line 46 of file RFLU_ReadTbcInputFile.F90.
References moderror::deregisterfunction(), moderror::errorstop(), form, CImg< T >::line(), moderror::registerfunction(), rflu_readtbcsection(), and Attribute::status().
Referenced by rflu_initflowsolver().