Rocstar: rfluinit.F90 File Reference
rfluinit.F90 File Reference
Functions/Subroutines
subroutine rfluinit (caseString, verbLevel)
Function/Subroutine Documentation
subroutine rfluinit (character(*) caseString, integer, intent(in) verbLevel)
Definition at line 45 of file rfluinit.F90.
References moderror::deregisterfunction(), moderror::errorstop(), plag_moddatastruct::plag_dstr_buildcell2pcllist(), plag_moddatastruct::plag_dstr_createpcllistcsr(), plag_moddatastruct::plag_dstr_destroycell2pcllist(), plag_moddatastruct::plag_dstr_destroypcllistcsr(), plag_initpatchdata(), plag_rflu_allocmemsol(), plag_rflu_allocmemsoltile(), plag_rflu_deallocmemsol(), plag_rflu_deallocmemsoltile(), plag_rflu_initsolfromserial(), plag_rflu_initsolserialwrapper(), plag_rflu_initsolutionrandom(), plag_rflu_initsolutionscratch(), plag_moddimensions::plag_rflu_writedimensions(), plag_rflu_writesolutionascii(), plag_rflu_writesolutionbinary(), plag_moddimensions::plag_setdimensions(), plag_moddimensions::plag_setmaxdimensions(), moderror::registerfunction(), rflu_modallocatememory::rflu_allocatememorygspeeds(), rflu_allocmemsolwrapper(), rflu_modregionmapping::rflu_applyregionmapping(), rflu_modboundlists::rflu_buildbvertexlists(), rflu_builddatastruct(), rflu_modfacelist::rflu_buildfacelist(), rflu_modgeometry::rflu_buildgeometry(), rflu_modcellmapping::rflu_buildglob2loccellmapping(), rflu_modboundxvutils::rflu_bxv_createvarscv(), rflu_modboundxvutils::rflu_bxv_createvarsdv(), rflu_modboundxvutils::rflu_bxv_destroyvarscv(), rflu_modboundxvutils::rflu_bxv_destroyvarsdv(), rflu_modboundxvutils::rflu_bxv_initvars(), rflu_modboundxvutils::rflu_bxv_writevarswrapper(), rflu_modboundlists::rflu_createbvertexlists(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modfacelist::rflu_createfacelist(), rflu_modgeometry::rflu_creategeometry(), rflu_creategrid(), rflu_modregionmapping::rflu_createregionmapping(), rflu_moddeallocatememory::rflu_deallocatememorygspeeds(), rflu_deallocmemsolwrapper(), rflu_modgridspeedutils::rflu_decideneedgridspeeds(), rflu_modreadwritebcdatafile::rflu_decidereadwritebcdatafile(), rflu_modboundlists::rflu_destroybvertexlists(), rflu_modcellmapping::rflu_destroycellmapping(), rflu_modfacelist::rflu_destroyfacelist(), rflu_modgeometry::rflu_destroygeometry(), rflu_destroygrid(), rflu_modregionmapping::rflu_destroyregionmapping(), rflu_modrocstaradmin::rflu_genx_createattrflow(), rflu_modrocstaradmin::rflu_genx_createattrgridsurf(), rflu_modrocstaradmin::rflu_genx_createattrgspeeds(), rflu_modrocstaradmin::rflu_genx_createattrinterf(), rflu_modrocstaradmin::rflu_genx_creategridsurf(), rflu_modrocstaradmin::rflu_genx_createwindows(), rflu_modrocstaradmin::rflu_genx_destroygridsurf(), rflu_modrocstario::rflu_genx_getdimensionsderived(), rflu_modrocstaradmin::rflu_genx_hardcodewindowname(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modrocstario::rflu_genx_readwindow(), rflu_modrocstaradmin::rflu_genx_registerdataflow(), rflu_modrocstaradmin::rflu_genx_registerdatagspeeds(), rflu_modrocstaradmin::rflu_genx_registergridsurf(), rflu_modrocstaradmin::rflu_genx_registergridvol(), rflu_modrocstaradmin::rflu_genx_setconnsize(), rflu_modrocstaradmin::rflu_genx_storecommunicator(), rflu_modrocstaradmin::rflu_genx_storenameshandles(), rflu_getuserinput(), rflu_modregionmapping::rflu_imposeregionmappingserial(), rflu_initbcdatahardcode(), rflu_initflowhardcodelimwrapper(), rflu_initflowhardcodewrapper(), rflu_initflowscratchwrapper(), rflu_initflowserialwrapper(), rflu_initglobal(), rflu_modnscbc::rflu_nscbc_decidehavenscbc(), rflu_printflowinfowrapper(), rflu_printgridinfo(), rflu_printheader(), rflu_printwarninfo(), rflu_randominit(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), rflu_moddimensions::rflu_readdimensions(), rflu_moddimensions::rflu_readdimensionswrapper(), rflu_modreadwriteflow::rflu_readflowwrapper(), rflu_modreadwritegrid::rflu_readgridwrapper(), rflu_modcellmapping::rflu_readloc2globcellmapping(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_readrestartinfo(), rflu_modboundlists::rflu_renumberbfacelists(), rflu_modrenumberings::rflu_rnmb_createpbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_createpc2scmap(), rflu_modrenumberings::rflu_rnmb_createpv2svmap(), rflu_modrenumberings::rflu_rnmb_destroypbf2sbfmap(), rflu_modrenumberings::rflu_rnmb_destroypc2scmap(), rflu_modrenumberings::rflu_rnmb_destroypv2svmap(), rflu_modrenumberings::rflu_rnmb_readpxx2sxxmaps(), rflu_setdependentvars(), rflu_setgasvars(), rflu_setmoduletype(), rflu_modregionmapping::rflu_setregionmappingserial(), rflu_setrestarttimeflag(), rflu_setvarinfowrapper(), rflu_modreadwritebcdatafile::rflu_writebcdatafile(), rflu_modreadwriteflow::rflu_writeflowwrapper(), rflu_modreadwritegridspeeds::rflu_writegridspeedswrapper(), rflu_writeversionstring(), scalerotatevector(), and StopWatch::stop().
Referenced by main().