Rocstar: RFLU_DeallocateMemory.F90 File Reference
RFLU_DeallocateMemory.F90 File Reference
Functions/Subroutines
subroutine rflu_deallocatememory (pRegion)
Function/Subroutine Documentation
subroutine rflu_deallocatememory (type(t_region), pointer pRegion)
Definition at line 44 of file RFLU_DeallocateMemory.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_moddeallocatememory::rflu_deallocatememorygspeeds(), rflu_moddeallocatememory::rflu_deallocatememorysol(), rflu_moddeallocatememory::rflu_deallocatememorytstep(), rflu_moddeallocatememory::rflu_deallocatememorytstep_c(), and rflu_moddeallocatememory::rflu_deallocatememorytstep_i().
Referenced by rflu_deallocatememorywrapper().