Rocstar: rflumap.F90 File Reference
rflumap.F90 File Reference
Functions/Subroutines
subroutine rflumap (caseString, mapOption, nRegions, nProcs, verbLevel)
Function/Subroutine Documentation
subroutine rflumap (character(*) caseString, integer, intent(in) mapOption, integer, intent(in) nRegions, integer, intent(in) nProcs, integer, intent(in) verbLevel)
Definition at line 48 of file rflumap.F90.
References moderror::errorstop(), rflu_modregionmapping::rflu_applyregionmapping(), rflu_builddatastruct(), rflu_modregionmapping::rflu_buildregionmappingsimple(), rflu_modregionmapping::rflu_checkregionmapping(), rflu_modregionmapping::rflu_closeregionmappingfile(), rflu_creategrid(), rflu_modregionmapping::rflu_createregionmapping(), rflu_destroygrid(), rflu_modregionmapping::rflu_destroyregionmapping(), rflu_modrocstario::rflu_genx_buildrocinpanestrings(), rflu_modrocstaradmin::rflu_genx_closerocinctrlfiles(), rflu_modrocstario::rflu_genx_openrocinctrlfiles(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modrocstario::rflu_genx_writerocinctrlfiles(), rflu_getuserinput(), rflu_initglobal(), rflu_modregionmapping::rflu_openregionmappingfile(), rflu_printheader(), rflu_printwarninfo(), rflu_moddimensions::rflu_readdimensions(), rflu_modregionmapping::rflu_readregionmappingfile(), rflu_readrestartinfo(), rflu_setrestarttimeflag(), rflu_modregionmapping::rflu_writeregionmappingfile(), rflu_writeversionstring(), and StopWatch::stop().
Referenced by main().