Rocstar: RkInitMP.F90 File Reference
RkInitMP.F90 File Reference
Functions/Subroutines
subroutine rkinitmp (region, istage)
Function/Subroutine Documentation
subroutine rkinitmp (type(t_region), intent(inout), target region, integer, intent(in) istage)
Definition at line 44 of file RkInitMP.F90.
References moderror::deregisterfunction(), moderror::errorstop(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, plag_rkinit(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflu_modnscbc::rflu_nscbc_decidehavenscbc(), rkinitgeneric(), rkinitsd(), scalegridspeeds(), and turb_rkinit().
Referenced by rungekuttamp().