Rocstar: RkInitSD.F90 File Reference
RkInitSD.F90 File Reference
Functions/Subroutines
subroutine rkinitsd (region, icBeg, icEnd, ivBeg, ivEnd, sd)
Function/Subroutine Documentation
subroutine rkinitsd (type(t_region) region, integer, intent(in) icBeg, integer, intent(in) icEnd, integer, intent(in) ivBeg, integer, intent(in) ivEnd, real(rfreal), dimension(:,:), pointer sd)
Definition at line 50 of file RkInitSD.F90.
References moderror::deregisterfunction(), ic, icbeg, icend, and moderror::registerfunction().
Referenced by rkinitmp().