Rocstar: Rocblas.C File Reference
Rocblas.C File Reference
Implementation of Rocblas.
#include "Rocblas.h"
Functions
void Rocblas_load_module (const char *name)
Calls Rocblas initialization function.
void Rocblas_unload_module (const char *name)
void rocblas_load_module (const char *name, int length)
void rocblas_unload_module (const char *name, int length)
void rocblas_load_module_ (const char *name, int length)
void rocblas_unload_module_ (const char *name, int length)
void ROCBLAS_LOAD_MODULE (const char *name, int length)
void ROCBLAS_UNLOAD_MODULE (const char *name, int length)
void ROCBLAS_LOAD_MODULE_ (const char *name, int length)
void ROCBLAS_UNLOAD_MODULE_ (const char *name, int length)
Detailed Description
Implementation of Rocblas.
Definition in file Rocblas.C.
Function Documentation
void Rocblas_load_module (const char * name)
Calls Rocblas initialization function.
Definition at line 118 of file Rocblas.C.
References Rocblas::init().
Referenced by main().
{
   Rocblas::init(std::string(name));
 }
void rocblas_load_module (const char * name, int length)
Definition at line 128 of file Rocblas.C.
References Rocblas::init().
 { Rocblas::init( std::string(name, length)); }
void ROCBLAS_LOAD_MODULE (const char * name, int length)
Definition at line 138 of file Rocblas.C.
References Rocblas::init().
 { Rocblas::init( std::string(name, length)); }
void rocblas_load_module_ (const char * name, int length)
Definition at line 133 of file Rocblas.C.
References Rocblas::init().
 { Rocblas::init( std::string(name, length)); }
void ROCBLAS_LOAD_MODULE_ (const char * name, int length)
Definition at line 143 of file Rocblas.C.
References Rocblas::init().
 { Rocblas::init( std::string(name, length)); }
void Rocblas_unload_module (const char * name)
Definition at line 121 of file Rocblas.C.
References Rocblas::finalize().
Referenced by main().
{
   Rocblas::finalize(std::string(name));
 }
void rocblas_unload_module (const char * name, int length)
Definition at line 130 of file Rocblas.C.
References Rocblas::finalize().
 { Rocblas::finalize( std::string(name, length)); }
void ROCBLAS_UNLOAD_MODULE (const char * name, int length)
Definition at line 140 of file Rocblas.C.
References Rocblas::finalize().
 { Rocblas::finalize( std::string(name, length)); }
void rocblas_unload_module_ (const char * name, int length)
Definition at line 135 of file Rocblas.C.
References Rocblas::finalize().
 { Rocblas::finalize( std::string(name, length)); }
void ROCBLAS_UNLOAD_MODULE_ (const char * name, int length)
Definition at line 145 of file Rocblas.C.
References Rocblas::finalize().
 { Rocblas::finalize( std::string(name, length)); }