Rocstar: Rocburn_load_module.f90 File Reference
Rocburn_load_module.f90 File Reference
Data Types
module m_init_1dmodules
interface m_init_1dmodules::COM_set_data
Functions/Subroutines
subroutine rocburn_load_module (module_name)
subroutine rocburn_unload_module (module_name)
Function/Subroutine Documentation
subroutine rocburn_load_module (character(*), intent(in) module_name)
Definition at line 98 of file Rocburn_load_module.f90.
References m_rocburn_interface_data::associate_pointer(), m_rocburn_2d::finalize(), m_rocburn_2d::init_wrapper(), m_rocburn_2d::initialize(), Aff_transformation_repS2< FT >::print(), m_init_1dmodules::rocburn_init_funcs_apn(), m_init_1dmodules::rocburn_init_funcs_py(), m_init_1dmodules::rocburn_init_funcs_zn(), m_rocburn_2d::update(), and m_rocburn_2d::update_wrapper().
Referenced by BurnAgent::load_module().
subroutine rocburn_unload_module (character(*), intent(in) module_name)
Definition at line 221 of file Rocburn_load_module.f90.
References m_rocburn_interface_data::associate_pointer().
Referenced by BurnAgent::unload_module().