Rocstar: rocburn_2D.f90 File Reference
Rocburn_PY/test/rocburn_2D.f90 File Reference
Functions/Subroutines
program burn_initialize
Function/Subroutine Documentation
program burn_initialize ()
Definition at line 25 of file Rocburn_PY/test/rocburn_2D.f90.
References update_py::burn_get_burning_rate1d(), setup_py::burn_init_0d(), init_py::burn_init_1d(), i, Aff_transformation_repS2< FT >::print(), StopWatch::stop(), and Matrix3D::zero().