Rocstar: Rocblas.h File Reference
Rocblas.h File Reference
Definition for Rocblas API.
#include <cstdio>
#include "roccom.h"
#include "roccom_devel.h"
Classes
class Rocblas
struct Rocblas::assn< T_src, T_trg >
struct Rocblas::random< T >
struct Rocblas::swapp< T >
struct Rocblas::maxv< T >
struct Rocblas::minv< T >
struct Rocblas::sumv< T >
struct Rocblas::nega< T >
struct Rocblas::sqrta< T >
struct Rocblas::acosa< T >
struct Rocblas::limit1v< T >
struct Rocblas::maxof< T >
Functions
void Rocblas_load_module (const char *name)
Calls Rocblas initialization function.
void Rocblas_unload_module (const char *name)
Detailed Description
Definition for Rocblas API.
Definition in file Rocblas.h.
Function Documentation
void Rocblas_load_module (const char * name)
Calls Rocblas initialization function.
Definition at line 118 of file Rocblas.C.
References Rocblas::init().
Referenced by main().
{
   Rocblas::init(std::string(name));
 }
void Rocblas_unload_module (const char * name)
Definition at line 121 of file Rocblas.C.
References Rocblas::finalize().
Referenced by main().
{
   Rocblas::finalize(std::string(name));
 }