Rocstar: roccom_c.h File Reference
roccom_c.h File Reference
This file contains the C wrapper for Roccom_base.
#include "roccom_basic.h"
#include "commpi.h"
#include <string.h>
Macros
#define LOAD_MODULE_WRAPPER(mixed, lower, UPPER)
Functions
Initialization and finalization
void COM_init (int *argc, char ***argv)
void COM_finalize ()
int COM_initialized ()
void COM_abort (int ierr)
void COM_set_default_communicator (MPI_Comm comm)
MPI_Comm COM_get_default_communicator ()
Module management
void COM_load_module (const char *libname, const char *winname)
void COM_unload_module (const char *libname, const char *winname)
Window and pane management
void COM_new_window (const char *w_str, MPI_Comm c)
void COM_delete_window (const char *str)
void COM_delete_pane (const char *w_str, const int pane_id)
void COM_window_init_done (const char *w_str, int pane_changed)
Attribute management
void COM_new_attribute (const char *wa_str, const char loc, const int type, int ncomp, const char *unit)
Registering an attribute type.
void COM_delete_attribute (const char *wa_str)
Delete an existing attribute.
void COM_set_size (const char *wa_str, int pane_id, int size, int ng)
Set sizes of for a specific attribute.
void COM_set_array (const char *wa_str, int pane_id, void *addr, int strd, int cap)
Associates an array with an attribute for a specific pane.
void COM_set_bounds (const char *wa_str, int pane_id, const void *lbound, const void *ubound)
Set the lower and upper bounds of an attribute.
void COM_allocate_array (const char *wa_str, int pane_id, void **addr, int strd, int cap)
Allocate space for an attribute on a specific pane and return the address by setting addr.
void COM_resize_array (const char *wa_str, int pane_id, void **addr, int strd, int cap)
Resize an attribute on a specific pane and return the address by setting addr.
void COM_append_array (const char *wa_str, int pane_id, const void *val, int v_strd, int v_size)
Append an array to the end of the attribute on a specific pane and return the new address by setting addr.
void COM_use_attribute (const char *wname, const char *attr, int with_ghost, const char *ptnname, int val)
Use the subset of panes of another window of which the given pane attribute has value val.
void COM_clone_attribute (const char *wname, const char *attr, int with_ghost, const char *ptnname, int val)
Clone the subset of panes of another window of which the given pane attribute has value val.
void COM_copy_attribute (const char *wname, const char *attr, int with_ghost, const char *ptnname, int val)
Copy an attribute onto another.
void COM_copy_attribute_handles (int trg_hdl, int src_hdl, int with_ghost, int ptn_hdl, int val)
void COM_deallocate_array (const char *wa_str, const int pid)
Deallocate space for an attribute in a pane, asuming the memory was allocated allocate_mesh or allocate_attribute.
void COM_get_size (const char *wa_str, int pane_id, int *size, int *ng)
Get the sizes of an attribute.
void COM_get_attribute (const char *wa_str, char *loc, int *type, int *ncomp, char *unit, int n)
Get the sizes of an attribute.
void COM_get_array (const char *wa_str, int pane_id, void **addr, int *strd, int *cap)
Get the address for an attribute on a specific pane.
void COM_copy_array (const char *wa_str, int pane_id, void *val, int v_strd, int v_size, int offset)
Copy an array from an attribute on a specific pane into a given buffer.
void COM_get_bounds (const char *wa_str, int pane_id, void *lbound, void *ubound)
Get the lower and upper bounds of an attribute.
int COM_check_bounds (const char *wa_str, int pane_id)
Check the lower and upper bounds of an attribute for a specific pane.
Information retrieval
void COM_get_communicator (const char *wname, MPI_Comm *comm)
void COM_get_panes (const char *wname, int *npanes, int **pane_ids, int rank)
void COM_get_attributes (const char *wname, int *na, char **names)
void COM_get_connectivities (const char *wname, int pane_id, int *nc, char **names)
void COM_get_parent (const char *waname, int pane_id, char **parent)
void COM_free_buffer (char **buf)
int COM_get_window_handle (const char *wname)
int COM_get_attribute_handle (const char *waname)
int COM_get_attribute_handle_const (const char *waname)
int COM_get_function_handle (const char *wfname)
int COM_get_status (const char *waname, const int pane_id)
Function management
void COM_set_function (const char *wf_str, Func_ptr func, const char *intents, const COM_Type *types)
void COM_set_member_function (const char *wf_str, Func_ptr func, const char *wa_str, const char *intents, const COM_Type *types)
void COM_call_function (const int wf, int argc,...)
void COM_icall_function (const int wf, int argc,...)
void COM_wait (const int id)
int COM_test (const int id)
Tracing and profiling tools
void COM_set_verbose (int i)
void COM_set_debug (bool debug)
void COM_set_profiling (int i)
void COM_set_profiling_barrier (int hdl, MPI_Comm comm)
void COM_print_profile (const char *fname, const char *header)
Miscellaneous
int COM_get_sizeof (const COM_Type type, int c)
int COM_compatible_types (COM_Type type1, COM_Type type2)
int COM_get_error_code ()
Detailed Description
This file contains the C wrapper for Roccom_base.
All the functions defined here directly correpond to the public member functions of Roccom_base.
See Also
roccom_c.C, roccom_c++.h
Definition in file roccom_c.h.
Macro Definition Documentation
#define LOAD_MODULE_WRAPPER (mixed, lower, UPPER)
Value:
\
  void mixed ## _load_module( const char * mod) {                       \
    extern void COM_F_FUNC2( lower ## _load_module, UPPER ## _LOAD_MODULE) \
      ( const char *mod, long int len);                                 \
                                                                        \
    long int len = strlen(mod);                                         \
    COM_F_FUNC2( lower ## _load_module, UPPER ## _LOAD_MODULE)          \
      ( mod, len);                                                      \
  }                                                                     \
                                                                        \
  void mixed ## _unload_module( const char * mod) {                     \
    extern void COM_F_FUNC2( lower ## _unload_module, UPPER ## _UNLOAD_MODULE) \
      ( const char *mod, long int len);                                 \
                                                                        \
    long int len = strlen(mod);                                         \
    COM_F_FUNC2( lower ## _unload_module, UPPER ## _UNLOAD_MODULE)      \
      ( mod, len);                                                      \
  }
Definition at line 47 of file roccom_c.h.
Function Documentation
void COM_abort (int ierr) inline
Definition at line 64 of file roccom_c++.h.
 { COM::Roccom_base::abort( ierr); }
void COM_allocate_array (const char * wa_str, int pane_id, void ** addr, int strd, int cap) inline
Allocate space for an attribute on a specific pane and return the address by setting addr.
Allocate for all panes if pane-id is 0, in which case, do not set addr.
Definition at line 196 of file roccom_c++.h.
References COM_get_roccom().
Referenced by RFC_Window_overlay::print_features(), MSH_Reader::read_pane_coors(), SMF_Reader::read_pane_coors(), OBJ_Reader::read_pane_coors(), Neutral_Reader::read_pane_coors(), IM_Reader::read_pane_coors(), OBJ_Reader::read_pane_elems(), MSH_Reader::read_pane_elems(), SMF_Reader::read_pane_elems(), Neutral_Reader::read_pane_elems(), IM_Reader::read_pane_elems(), and RFC_Pane_base::register_sdv_attributes().
 { COM_get_roccom()->allocate_array( wa_str, pane_id, addr, strd, cap); }
void COM_append_array (const char * wa_str, int pane_id, const void * val, int v_strd, int v_size) inline
Append an array to the end of the attribute on a specific pane and return the new address by setting addr.
Definition at line 214 of file roccom_c++.h.
References COM_get_roccom().
Referenced by RFC_Pane_base::register_sdv_attributes().
 { COM_get_roccom()->append_array( wa_str, pane_id, val, v_strd, v_size); }
void COM_call_function (const int wf, int argc, ...)
Definition at line 48 of file roccom_c.C.
References COM_assertion_msg, COM_get_roccom(), i, and Function::MAX_NUMARG.
{
   COM_assertion_msg( argc <= Function::MAX_NUMARG, "Too many arguments") ;
   int i;
   void *args[Function::MAX_NUMARG];
   va_list   ap;
   va_start( ap, argc);
   for ( i=0; i<argc; ++i) {
     args[i] = va_arg( ap, void*);
   }
   va_end( ap);
   COM_get_roccom()->call_function( wf, argc, args);
 }
int COM_check_bounds (const char * wa_str, int pane_id) inline
Check the lower and upper bounds of an attribute for a specific pane.
Definition at line 320 of file roccom_c++.h.
References COM_get_roccom().
 { return COM_get_roccom()->check_bounds( wa_str, pane_id); }
void COM_clone_attribute (const char * wname, const char * attr, int with_ghost, const char * ptnname, int val) inline
Clone the subset of panes of another window of which the given pane attribute has value val.
Definition at line 234 of file roccom_c++.h.
References COM_get_roccom().
Referenced by CloneAttribute::create(), FluidAgent::create_buffer_all(), BurnAgent::create_buffer_all(), SolidAgent::create_buffer_all(), getWindow(), Rocon::initialize(), read_file(), FluidAgent::read_restart_data(), SolidAgent::read_restart_data(), TRAIL_ExtractSurf0(), TRAIL_File2Window(), and TRAIL_HDF2Window().
 { COM_get_roccom()->clone_attribute(wname, attr, wg, ptnname, val); }
int COM_compatible_types (COM_Type type1, COM_Type type2) inline
Definition at line 563 of file roccom_c++.h.
Referenced by Rocblas::axpy_gen(), Propagation_3::bound_facial_speed(), Rocblas::calc(), Rocblas::calcDot(), Rocsurf::compute_element_areas(), Window_manifold_2::compute_normals(), Pane_boundary::determine_borders(), Rocmop::determine_physical_border(), Window_manifold_2::elements_to_nodes(), Rocblas::gen2arg(), Rocsurf::integrate(), Propagation_3::set_bounds(), Window_manifold_2::shortest_edge_length(), Rocmop::smoother_specific_init(), Window_manifold_2::update_bd_flags(), Window_manifold_2::update_bd_normals(), and Window_manifold_2::update_bdedge_bitmap().
 { return COM::Attribute::compatible_types( type1, type2); }
void COM_copy_array (const char * wa_str, int pane_id, void * val, int v_strd, int v_size, int offset) inline
Copy an array from an attribute on a specific pane into a given buffer.
Definition at line 311 of file roccom_c++.h.
References COM_get_roccom(), and offset().
Referenced by read_pane_sp(), and RFC_Pane_base::read_rocin().
 { COM_get_roccom()->copy_array( wa_str, pane_id, val, v_strd, v_size, offset); }
void COM_copy_attribute (const char * wname, const char * attr, int with_ghost, const char * ptnname, int val) inline
Copy an attribute onto another.
Definition at line 244 of file roccom_c++.h.
References COM_get_roccom().
Referenced by TemperatureTransfer_SF::run(), HeatTransfer_FS::run(), CopyBurnFromParentMesh::run(), CopyBflagFromBurn::run(), and Agent::store_solutions().
 { COM_get_roccom()->copy_attribute(wname, attr, wg, ptnname, val); }
void COM_copy_attribute_handles (int trg_hdl, int src_hdl, int with_ghost, int ptn_hdl, int val)
void COM_deallocate_array (const char * wa_str, const int pid) inline
Deallocate space for an attribute in a pane, asuming the memory was allocated allocate_mesh or allocate_attribute.
Definition at line 262 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->deallocate_array(wa_str, pid); }
void COM_delete_attribute (const char * wa_str) inline
Delete an existing attribute.
Definition at line 128 of file roccom_c++.h.
References COM_get_roccom().
Referenced by getWindow(), main(), read_file(), IM_Reader::read_winmesh(), TRAIL_File2Window(), and TRAIL_HDF2Window().
 { COM_get_roccom()->delete_attribute( wa_str); }
void COM_delete_pane (const char * w_str, const int pane_id) inline
Definition at line 110 of file roccom_c++.h.
References COM_get_roccom().
Referenced by read_file(), TRAIL_File2Window(), and RFC_Window_base::write_sdv().
 { COM_get_roccom()->delete_pane( str, pid) ; }
void COM_delete_window (const char * str) inline
Definition at line 94 of file roccom_c++.h.
References COM_get_roccom().
Referenced by SolidAgent::create_buffer_all(), GEM_Partition::DestroyWindows(), BurnAgent::finalize(), FluidAgent::finalize(), SolidAgent::finalize(), Rocblas::finalize(), Rocout::finalize(), Rocin::finalize(), getWindow(), Rocon::init_from_file(), BurnAgent::init_module(), FluidAgent::init_module(), SolidAgent::init_module(), RFC_Window_transfer::init_recv_buffer(), Rocon::initialize(), main(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), read_pane_sp(), RFC_Window_base::read_sdv(), remesh(), TRAIL_AutoSurfer(), TRAIL_File2Window(), TRAIL_HDF2Window(), TRAIL_RemeshWrite(), TRAIL_RocmopSmooth(), TRAIL_RocpropSmoothSurf(), TRAIL_TransferSurfDataFILE(), Rocmap::unload(), Rocsurf::unload(), Rocmop::unload(), Rocon::unload(), Rocprop::unload(), and RFC_Window_base::write_sdv().
 { COM_get_roccom()->delete_window(wname); }
void COM_finalize () inline
Definition at line 59 of file roccom_c++.h.
Referenced by main(), and RocstarShutdown().
 { COM::Roccom_base::finalize(); }
void COM_free_buffer (char ** buf) inline
Definition at line 401 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->free_buffer( buf); }
void COM_get_array (const char * wa_str, int pane_id, void ** addr, int * strd, int * cap)
Get the address for an attribute on a specific pane.
Referenced by broadcast_win_attributes(), Rocon::burnout(), Rocon::burnout_filter(), COM_print_window(), Rocon::constrain_displacements(), debug_int_print(), debug_print(), Rocon::find_intersections(), getPaneConnectivity(), HeatTransfer_FS::init(), init_attributes(), init_constraints_acmflu(), init_constraints_acmfrac(), init_constraints_labscale(), init_constraints_myacm(), init_constraints_staraft(), init_constraints_starslice(), init_normals(), init_speed(), Rocon::initialize(), load_data_HDF4(), main(), read_file(), TRAIL_Att2Vec(), TRAIL_AutoSurfer(), TRAIL_Copy2Attribute(), TRAIL_ExtractPanes(), TRAIL_ExtractSurf0(), TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), TRAIL_FE2FD_Transfer(), TRAIL_File2Window(), TRAIL_FixRocstarData(), TRAIL_GetPanelAttribute(), TRAIL_SetAttribute(), TRAIL_SurfaceMesh2Window(), TRAIL_TransferSurfDataFILE(), and TRAIL_UnstructuredMesh2Pane().
void COM_get_attribute (const char * wa_str, char * loc, int * type, int * ncomp, char * unit, int n)
Get the sizes of an attribute.
Information retrieval Get the information about an attribute.
The opposite of set_size.
The opposite of new_attribute.
Definition at line 80 of file roccom_c.C.
References COM_get_roccom(), copy, max(), min(), and n.
 {
   std::string unit;
   COM_get_roccom()->get_attribute( wa_str, loc, type, size, &unit);
   if ( u_str && u_len) {
     int len=unit.size(), n=std::min(len, int(u_len));
     std::copy( unit.c_str(), unit.c_str()+n, u_str);
     std::fill_n( u_str+1+n, std::max(0,int(u_len-len)), 0);
   }
 }
int COM_get_attribute_handle (const char * waname) inline
Definition at line 412 of file roccom_c++.h.
References COM_get_roccom().
Referenced by build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), COM_print_window(), compute_area(), compute_overlay(), compute_quadric_normals(), compute_volume(), compute_weighted_normals(), NewAttribute::create(), CloneAttribute::create(), UseAttribute::create(), FluidAgent::create_buffer_all(), BurnAgent::create_buffer_all(), SolidAgent::create_buffer_all(), GEM_DomainBoundary::Create_com_surfsoln(), GEM_Partition::Create_com_volsoln(), Action::get_attribute_handle(), getPaneConnectivity(), InterpolateBase::init(), Extrapolate_Linear::init(), Extrapolate_Central::init(), LoadTransfer_FSc_ALE::init(), GetDeformedMesh_ALE::init(), MeshMotionTransfer_SF::init(), ComputeFluidLoad_ALE::init(), MeshMotionTransferISS::init(), ComputeMeshMotion::init(), FluidPropagateSurface::init(), TransferBurnRate_FS_ALE::init(), MassTransfer_SF_ALE::init(), MassTransfer::init(), ZoomInterface::init(), HeatTransfer_FS::init(), ComputeRhofvf::init(), ComputeBurnPane::init(), SolidPropagateSurface_ALE::init(), Reset_du_alp::init(), init_attributes(), init_constraints(), init_constraints_acmflu(), init_constraints_acmfrac(), init_constraints_labscale(), init_constraints_myacm(), init_constraints_staraft(), init_constraints_starslice(), Rocon::init_from_file(), init_normals(), RFC_Window_transfer::init_recv_buffer(), main(), output_solution(), read_file(), read_pane_sp(), FluidAgent::read_restart_data(), BurnAgent::read_restart_data(), SolidAgent::read_restart_data(), RFC_Pane_base::read_rocin(), RFC_Window_base::read_sdv(), IM_Reader::read_winmesh(), remesh(), SurfDiver::run(), ComputeFaceCenters::run(), TRAIL_Add_Attributes(), TRAIL_AutoSurfer(), TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate2(), TRAIL_FE2FD_Transfer(), TRAIL_File2Window(), TRAIL_HDF2Window(), TRAIL_RocmopSmooth(), TRAIL_RocpropSmoothSurf(), TRAIL_TransferSurfDataFILE(), TRAIL_WriteWindow(), Agent::write_data_files(), and RFC_Window_base::write_sdv().
 { return COM_get_roccom()->get_attribute_handle( waname); }
int COM_get_attribute_handle_const (const char * waname) inline
Definition at line 420 of file roccom_c++.h.
References COM_get_roccom().
Referenced by _load_rocface(), BurnAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Action::get_attribute_handle_const(), InterpolateBase::init(), LoadTransfer_FS::init(), LoadTransfer_FSc_ALE::init(), SurfDiver::init(), ComputeFluidLoad_ALE::init(), BurnAgent::init_module(), main(), RFC_Window_overlay::print_features(), FluidAgent::read_restart_data(), BurnAgent::read_restart_data(), and SolidAgent::read_restart_data().
 { return COM_get_roccom()->get_attribute_handle_const( waname); }
void COM_get_attributes (const char * wname, int * na, char ** names) inline
Definition at line 379 of file roccom_c++.h.
References COM_get_roccom().
{
   std::string str;
   COM_get_roccom()->get_attributes( wname, na, str, names);
 }
void COM_get_bounds (const char * wa_str, int pane_id, void * lbound, void * ubound) inline
Get the lower and upper bounds of an attribute.
Definition at line 316 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->get_bounds( wa_str, pane_id, lbound, ubound); }
void COM_get_communicator (const char * wname, MPI_Comm * comm) inline
Definition at line 346 of file roccom_c++.h.
References COM_get_roccom().
Referenced by TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate(), and TRAIL_FD2FE_WinCreate2().
 { *comm = COM_get_roccom()->get_communicator( wname); }
void COM_get_connectivities (const char * wname, int pane_id, int * nc, char ** names) inline
Definition at line 385 of file roccom_c++.h.
References COM_get_roccom().
{
   std::string str;
   COM_get_roccom()->get_connectivities( wname, pane_id, nc, str, names);
 }
MPI_Comm COM_get_default_communicator () inline
Definition at line 69 of file roccom_c++.h.
Referenced by compute_overlay(), GetCommunicator(), Rocin::read_by_control_file(), Rocin::read_windows(), SurfDiver::run(), TRAIL_FE2FD_Transfer(), and Rocout::write_rocin_control_file().
 { return COM::Roccom_base::get_default_communicator(); }
int COM_get_error_code () inline
Definition at line 566 of file roccom_c++.h.
References COM_get_roccom().
 { return COM_get_roccom()->get_error_code(); }
int COM_get_function_handle (const char * wfname) inline
Definition at line 428 of file roccom_c++.h.
References COM_get_roccom().
Referenced by _load_rocface(), build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), compute_area(), compute_fnormal_error(), compute_overlay(), compute_quadric_normals(), compute_vnormal_error(), compute_volume(), compute_weighted_normals(), Agent::create_window(), getPaneConnectivity(), getWindow(), LoadTransfer_FS::init(), LoadTransfer_FSc_ALE::init(), LoadTransferOnly_FSc_ALE::init(), GetDeformedMesh_ALE::init(), SurfDiver::init(), MeshMotionTransfer_SF::init(), DeformationVelTransfer_SF::init(), MeshMotionTransferISS::init(), TransferSolidDensity::init(), FluidPropagateSurface::init(), TransferBurnRate_FS_ALE::init(), MassTransfer_SF_ALE::init(), TemperatureTransfer_SF::init(), HeatTransfer_FS::init(), RemeshInit::init(), ComputePconn::init(), SolidPropagateSurface_ALE::init(), init_attributes(), init_constraints(), init_constraints_acmflu(), init_constraints_acmfrac(), init_constraints_labscale(), init_constraints_myacm(), init_constraints_staraft(), init_constraints_starslice(), Rocon::init_from_file(), Agent::init_function_handles(), init_normals(), init_parameters(), RFC_Window_transfer::init_recv_buffer(), RocBlas::initHandles(), load_rocon(), load_rocprop(), main(), output_solution(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), read_pane_sp(), RFC_Window_base::read_sdv(), IM_Reader::read_winmesh(), remesh(), ComputeFaceCenters::run(), TRAIL_AutoSurfer(), TRAIL_FE2FD_Transfer(), TRAIL_File2Window(), TRAIL_HDF2Window(), TRAIL_RocmopSmooth(), TRAIL_RocpropSmoothSurf(), TRAIL_TransferSurfDataFILE(), TRAIL_WriteWindow(), Control_parameters::update_communicator(), FullyCoupling::update_distances(), and RFC_Window_base::write_sdv().
 { return COM_get_roccom()->get_function_handle( wfname); }
void COM_get_panes (const char * wname, int * npanes, int ** pane_ids, int rank) inline
Definition at line 372 of file roccom_c++.h.
References COM_get_roccom(), and rank.
{
   std::vector<int> vec;
   COM_get_roccom()->get_panes( wname, vec, rank, pane_ids);
   if ( npanes) *npanes = vec.size();
 }
void COM_get_parent (const char * waname, int pane_id, char ** parent) inline
Definition at line 391 of file roccom_c++.h.
References COM_get_roccom().
{
   std::string str;
   COM_get_roccom()->get_parent( waname, pane_id, str, parent);
 }
void COM_get_size (const char * wa_str, int pane_id, int * size, int * ng) inline
Get the sizes of an attribute.
The opposite of set_size.
Definition at line 274 of file roccom_c++.h.
References COM_get_roccom().
Referenced by Rocon::burnout(), Rocon::burnout_filter(), COM_print_window(), Rocon::constrain_displacements(), Rocon::find_intersections(), getPaneConnectivity(), init_constraints_acmflu(), init_constraints_acmfrac(), init_constraints_labscale(), init_constraints_myacm(), init_constraints_staraft(), init_constraints_starslice(), init_speed(), Rocon::initialize(), main(), read_pane_sp(), RFC_Pane_base::read_rocin(), TRAIL_Att2Vec(), TRAIL_GetWindowSolnData(), and TRAIL_Window2UnstructuredMesh().
 { COM_get_roccom()->get_size( wa_str, pane_id, size, ng); }
int COM_get_sizeof (const COM_Type type, int c) inline
Definition at line 560 of file roccom_c++.h.
References get_sizeof().
Referenced by Window_manifold_2::accumulate_bd_values(), Node::addr(), Halfedge::addr(), Pane_communicator::begin_update(), broadcast_win_attributes(), Pane_communicator::init(), Pane_communicator::reduce_average_on_shared_nodes(), Pane_communicator::reduce_diff_on_shared_nodes(), Pane_communicator::reduce_maxabs_on_shared_nodes(), Pane_communicator::reduce_minabs_on_shared_nodes(), Pane_communicator::reduce_on_shared_nodes(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), TRAIL_FD2FE_Transfer(), TRAIL_FE2FD_Transfer(), and Pane_communicator::update_ghost_values().
 { return COM::Attribute::get_sizeof( type, c); }
int COM_get_status (const char * waname, const int pane_id) inline
Definition at line 431 of file roccom_c++.h.
References COM_get_roccom().
Referenced by load_data_HDF4().
 { return COM_get_roccom()->get_status( waname, pane_id); }
int COM_get_window_handle (const char * wname) inline
Definition at line 404 of file roccom_c++.h.
References COM_get_roccom().
Referenced by _load_rocface(), AttributeBase::assign(), Extrapolate_Central::init(), FluidPropagateSurface::init(), SolidPropagateSurface_ALE::init(), load_rocmap(), load_rocon(), load_rocprop(), load_rocsurf(), SMF_Reader::read_mesh(), Neutral_Reader::read_mesh(), OBJ_Reader::read_mesh(), MSH_Reader::read_mesh(), IM_Reader::read_mesh(), Rocin::read_parameter_file(), Coupling::restart_at_time(), Agent::split_surface_window(), and Rocout::write_parameter_file().
 { return COM_get_roccom()->get_window_handle( wname); }
void COM_icall_function (const int wf, int argc, ...)
Definition at line 64 of file roccom_c.C.
References COM_assertion_msg, COM_get_roccom(), i, and Function::MAX_NUMARG.
{
   COM_assertion_msg( argc <= Function::MAX_NUMARG, "Too many arguments") ;
   int i;
   void *args[Function::MAX_NUMARG];
   va_list   ap;
   va_start( ap, argc);
   for ( i=0; i<argc-1; ++i) {
     args[i] = va_arg( ap, void*);
   }
   int *status = va_arg( ap, int *);
   va_end( ap);
   COM_get_roccom()->icall_function( wf, argc, args, status);
 }
void COM_init (int * argc, char *** argv) inline
Definition at line 57 of file roccom_c++.h.
Referenced by main().
 { COM::Roccom_base::init( argc, argv); }
int COM_initialized () inline
Definition at line 62 of file roccom_c++.h.
 { return COM::Roccom_base::initialized(); }
void COM_load_module (const char * libname, const char * winname) inline
Definition at line 75 of file roccom_c++.h.
References COM_get_roccom().
Referenced by BurnAgent::load_module(), FluidAgent::load_module(), SolidAgent::load_module(), and main().
 { COM_get_roccom()->load_module( libname, winname); }
void COM_new_attribute (const char * wa_str, const char loc, const int type, int ncomp, const char * unit) inline
Registering an attribute type.
wa_str is the attribute's name in the format "window.attribute". loc is the code for the location of the data, which can be 'w' for window attribute, 'p' for pane attribute, 'n' for node attribute, or 'e' for element attribute. type is the data type of the attribute. For C/C++, it can be COM_CHAR, COM_UNSIGNED_CHAR, COM_BYTE, COM_SHORT, COM_UNSIGNED_SHORT, COM_INT, COM_UNSIGNED, COM_LONG, COM_UNSIGNED_LONG, COM_FLOAT0, COM_DOUBLE1, COM_LONG_DOUBLE, COM_LONG_LONG_INT, or a derived data type. For Fortran, it can be COM_CHARACTER, COM_INTEGER, COM_LOGICAL, COM_REAL, COM_DOUBLE_PRECISION, COM_COMPLEX, COM_DOUBLE_COMPLEX. size is the length of the attribute in the given data type
Definition at line 118 of file roccom_c++.h.
References COM_get_roccom().
Referenced by Coupling::baseInit(), NewAttribute::create(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), GEM_DomainBoundary::Create_com_surfsoln(), GEM_Partition::Create_com_volsoln(), Agent::create_window(), Rocout::init(), Rocin::init(), init_attributes(), Rocsurf::load(), Rocmop::load(), Rocon::load(), Rocprop::load(), main(), makeWindow(), new_attributes(), RFC_Window_base::new_sdv_attributes(), RFC_Window_overlay::print_features(), Rocin::read_parameter_file(), Rocin::register_panes(), FluRegion::RegisterFluSurfaceMesh(), FluRegion::RegisterSurfaceSoln(), FluRegion::RegisterVolumeSoln(), TRAIL_Add_Attributes(), TRAIL_AutoSurfer(), TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), TRAIL_FluRegisterSurfMesh(), TRAIL_FluRegisterSurfSoln(), TRAIL_FluRegisterVolSoln(), TRAIL_RocmopSmooth(), TRAIL_RocpropSmoothSurf(), and TRAIL_TransferSurfDataFILE().
 { COM_get_roccom()->new_attribute( wa_str, loc, type, ncomp, unit); }
void COM_new_window (const char * w_str, MPI_Comm c) inline
Definition at line 86 of file roccom_c++.h.
References COM_get_roccom().
Referenced by Coupling::baseInit(), build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), convertWindow(), FluidAgent::create_buffer_all(), BurnAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), Agent::create_window(), getWindow(), Rocblas::init(), Rocout::init(), Rocin::init(), Rocon::initialize(), GEM_Partition::InitRoccomWindows(), FluidAgent::input(), BurnAgent::input(), Rocmap::load(), Rocsurf::load(), Rocmop::load(), Rocon::load(), Rocprop::load(), main(), makeWindow(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), Neutral_Reader::read_mesh(), OBJ_Reader::read_mesh(), SMF_Reader::read_mesh(), MSH_Reader::read_mesh(), IM_Reader::read_mesh(), Rocin::read_parameter_file(), Rocin::read_windows(), remesh(), Agent::split_surface_window(), TRAIL_ExtractSurf0(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), TRAIL_File2Window(), TRAIL_HDF2Window(), TRAIL_RemeshWrite(), TRAIL_RocmopSmooth(), TRAIL_RocpropSmoothSurf(), TRAIL_SurfaceMesh2Window(), and RFC_Window_base::write_sdv().
 { COM_get_roccom()->new_window(wname, c); }
void COM_print_profile (const char * fname, const char * header) inline
Definition at line 557 of file roccom_c++.h.
References COM_get_roccom().
Referenced by main(), and rocstar_driver().
 { COM_get_roccom()->print_profile( fname, header); }
void COM_resize_array (const char * wa_str, int pane_id, void ** addr, int strd, int cap) inline
Resize an attribute on a specific pane and return the address by setting addr.
Resize for all panes if pane-id is 0, in which case, do not set addr. The difference between resize and allocate is that resize will reallocate memory only if the current array cannot accomodate the requested capacity.
Definition at line 200 of file roccom_c++.h.
References COM_get_roccom().
Referenced by NewAttribute::create(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), init_attributes(), init_constraints_staraft(), load_data_HDF4(), main(), new_attributes(), Rocin::read_parameter_file(), IM_Reader::read_winmesh(), TRAIL_AutoSurfer(), TRAIL_Copy2Attribute(), TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), TRAIL_FixRocstarData(), TRAIL_SetAttribute(), TRAIL_SurfaceMesh2Window(), TRAIL_TransferSurfDataFILE(), and TRAIL_UnstructuredMesh2Pane().
 { COM_get_roccom()->resize_array( wa_str, pane_id, addr, strd, cap); }
void COM_set_array (const char * wa_str, int pane_id, void * addr, int strd, int cap) inline
Associates an array with an attribute for a specific pane.
Definition at line 156 of file roccom_c++.h.
References COM_get_roccom().
Referenced by add_ghost_nodes2D(), build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), GEM_DomainBoundary::Create_com_surfsoln(), GEM_Partition::Create_com_volsoln(), GEM_Partition::CreatePconn(), main(), GEM_Partition::PopulateVolumeWindow(), IM_Reader::read_pane_ij(), GEM_DomainBoundary::Register_com_surfmesh(), GEM_Partition::Register_com_volconn(), Rocin::register_panes(), FluRegion::RegisterFluSurfaceMesh(), FluPatch::RegisterSoln(), FluRegion::RegisterVolumeSoln(), TRAIL_FluRegisterSurfMesh(), TRAIL_FluRegisterSurfSoln(), TRAIL_FluRegisterVolSoln(), TRAIL_RocmopSmooth(), and TRAIL_RocpropSmoothSurf().
 { COM_get_roccom()->set_array( wa_str, pane_id, addr, strd, cap); }
void COM_set_bounds (const char * wa_str, int pane_id, const void * lbound, const void * ubound) inline
Set the lower and upper bounds of an attribute.
Definition at line 176 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->set_bounds( wa_str, pane_id, lbound, ubound); }
void COM_set_debug (bool debug) inline
Definition at line 546 of file roccom_c++.h.
References COM_get_roccom().
Referenced by rocstar_driver().
 { COM_get_roccom()->set_debug( debug); }
void COM_set_default_communicator (MPI_Comm comm) inline
Definition at line 67 of file roccom_c++.h.
Referenced by compute_overlay(), SurfDiver::run(), TRAIL_AutoSurfer(), TRAIL_FE2FD_Transfer(), and Control_parameters::update_communicator().
 { COM::Roccom_base::set_default_communicator( comm); }
void COM_set_function (const char * wf_str, Func_ptr func, const char * intents, const COM_Type * types) inline
Definition at line 323 of file roccom_c++.h.
References COM_get_roccom().
Referenced by Rocblas::init(), Rocmap::load(), and Rocsurf::load().
 { COM_get_roccom()->set_function( wf_str, func, intents, types); }
void COM_set_member_function (const char * wf_str, Func_ptr func, const char * wa_str, const char * intents, const COM_Type * types) inline
Definition at line 339 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->set_member_function( wf_str, func, wa_str, intents, types); }
void COM_set_profiling (int i) inline
Definition at line 550 of file roccom_c++.h.
References COM_get_roccom().
Referenced by compute_overlay(), main(), rocstar_driver(), SurfDiver::run(), and TRAIL_RemeshWrite().
 { COM_get_roccom()->set_profiling( i); }
void COM_set_profiling_barrier (int hdl, MPI_Comm comm) inline
Definition at line 554 of file roccom_c++.h.
References COM_get_roccom().
Referenced by _load_rocface(), Agent::init_function_handles(), load_rocprop(), and main().
 { COM_get_roccom()->set_profiling_barrier( hdl, comm); }
void COM_set_size (const char * wa_str, int pane_id, int size, int ng) inline
Set sizes of for a specific attribute.
Definition at line 136 of file roccom_c++.h.
References COM_get_roccom().
Referenced by build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), GEM_Partition::CreatePconn(), init_attributes(), init_constraints_staraft(), main(), new_attributes(), GEM_Partition::PopulateVolumeWindow(), MSH_Reader::read_pane_coors(), SMF_Reader::read_pane_coors(), OBJ_Reader::read_pane_coors(), Neutral_Reader::read_pane_coors(), IM_Reader::read_pane_coors(), OBJ_Reader::read_pane_elems(), MSH_Reader::read_pane_elems(), SMF_Reader::read_pane_elems(), Neutral_Reader::read_pane_elems(), IM_Reader::read_pane_elems(), Rocin::read_parameter_file(), GEM_DomainBoundary::Register_com_surfmesh(), GEM_Partition::Register_com_volconn(), Rocin::register_panes(), RFC_Pane_base::register_sdv_attributes(), FluRegion::RegisterFluSurfaceMesh(), FluPatch::RegisterSoln(), FluRegion::RegisterVolumeSoln(), TRAIL_Copy2Attribute(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), TRAIL_FluRegisterSurfMesh(), TRAIL_FluRegisterSurfSoln(), TRAIL_FluRegisterVolSoln(), TRAIL_RocpropSmoothSurf(), TRAIL_SetAttribute(), TRAIL_SurfaceMesh2Window(), and TRAIL_UnstructuredMesh2Pane().
 { COM_get_roccom()->set_size( wa_str, pane_id, size, ng); }
void COM_set_verbose (int i) inline
Definition at line 543 of file roccom_c++.h.
References COM_get_roccom().
Referenced by main(), and rocstar_driver().
 { COM_get_roccom()->set_verbose( i); }
int COM_test (const int id) inline
Definition at line 540 of file roccom_c++.h.
References COM_get_roccom().
 { return COM_get_roccom()->test( id); }
void COM_unload_module (const char * libname, const char * winname) inline
Definition at line 78 of file roccom_c++.h.
References COM_get_roccom().
Referenced by BurnAgent::unload_module(), FluidAgent::unload_module(), and SolidAgent::unload_module().
 { COM_get_roccom()->unload_module( libname, winname?winname:""); }
void COM_use_attribute (const char * wname, const char * attr, int with_ghost, const char * ptnname, int val) inline
Use the subset of panes of another window of which the given pane attribute has value val.
Definition at line 224 of file roccom_c++.h.
References COM_get_roccom().
Referenced by AttributeBase::assign(), UseAttribute::create(), BurnAgent::create_buffer_all(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), BurnAgent::init_module(), RFC_Window_overlay::print_features(), and Agent::split_surface_window().
 { COM_get_roccom()->use_attribute(wname, attr, wg, ptnname, val); }
void COM_wait (const int id) inline
Definition at line 537 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->wait( id); }
void COM_window_init_done (const char * w_str, int pane_changed) inline
Definition at line 102 of file roccom_c++.h.
References COM_get_roccom().
Referenced by build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), compute_overlay(), convertWindow(), FluidAgent::create_buffer_all(), BurnAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), Agent::create_registered_attributes(), Agent::create_window(), getWindow(), Rocblas::init(), Rocout::init(), Rocin::init(), init_attributes(), Rocon::init_from_file(), BurnAgent::init_module(), Rocon::initialize(), FluidAgent::input(), BurnAgent::input(), Rocmap::load(), Rocsurf::load(), Rocmop::load(), Rocon::load(), Rocprop::load(), main(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), Rocin::read_parameter_file(), Rocin::read_windows(), RFC_Pane_base::register_sdv_attributes(), remesh(), SurfDiver::run(), Agent::split_surface_window(), TRAIL_Add_Attributes(), TRAIL_ExtractSurf0(), TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate2(), TRAIL_File2Window(), TRAIL_FixRocstarData(), TRAIL_HDF2Window(), TRAIL_RocmopSmooth(), TRAIL_SurfaceMesh2Window(), GEM_Partition::WindowInitDone(), and RFC_Window_base::write_sdv().
 { COM_get_roccom()->window_init_done( w_str, pane_changed); }