Rocstar: Roccom_base.C File Reference
Roccom_base.C File Reference
Contains the base implementation of Roccom.
#include <iostream>
#include <sys/time.h>
#include <algorithm>
#include <dlfcn.h>
#include <cctype>
#include <cstring>
#include <cstdlib>
#include <cstdio>
#include <sstream>
#include "Roccom_base.h"
#include "commpi.h"
Classes
class COM_Object_derived
Functions
static void remove_arg (int *argc, char ***argv, int i)
Remove an argument from the argument list.
void print_type (std::ostream &os, COM_Type type)
static double get_wtime ()
Variables
COM_END_NAME_SPACE void * p_xargc
Circumvent problem with missing variables.
void * p_xargv
Detailed Description
Contains the base implementation of Roccom.
The more advanced implementations should reimplement the following: window_init_done, delete_window, delete_pane, and call_function, icall_function.
See also
Roccom_base.h, Window.h
Definition in file Roccom_base.C.
Function Documentation
static double get_wtime () inline static
Definition at line 1734 of file Roccom_base.C.
Referenced by Roccom_base::call_function().
{
   ::timeval tv;
   gettimeofday( &tv, NULL);
   return tv.tv_sec + tv.tv_usec*1.e-6;
 }
void print_type (std::ostream & os, COM_Type type)
Definition at line 480 of file Roccom_base.C.
References COM_CHAR, COM_CHARACTER, COM_DOUBLE, COM_DOUBLE_PRECISION, COM_F90POINTER, COM_FLOAT, COM_INT, COM_INTEGER, COM_LOGICAL, COM_LONG, COM_METADATA, COM_MPI_COMMC, COM_MPI_COMMF, COM_OBJECT, COM_REAL, COM_STRING, and COM_VOID.
Referenced by Roccom_base::get_attribute(), Roccom_base::new_attribute(), Roccom_base::set_function(), and Roccom_base::set_member_function_helper().
{
   switch (type) {
   case COM_STRING:
     os << "STRING"; break;
   case COM_METADATA:
     os << "METADATA"; break;
   case COM_VOID:
     os << "VOID"; break;
   case COM_OBJECT:
     os << "COM_Object"; break;
   case COM_F90POINTER:
     os << "F90POINTER"; break;
   case COM_CHAR: case COM_CHARACTER:
     os << "CHAR"; break;
   case COM_DOUBLE:
   case COM_DOUBLE_PRECISION:
     os << "double"; break;
   case COM_INT:
   case COM_LONG:
   case COM_INTEGER:
     os << "int"; break;
   case COM_FLOAT:
   case COM_REAL:
     os << "float"; break;
   case COM_LOGICAL:
     os << "logical"; break;
   case COM_MPI_COMMC:
   case COM_MPI_COMMF:
     os << "MPI_Comm"; break;
   default:
     os << "type(" << type << ")";
   }
 }
static void remove_arg (int * argc, char *** argv, int i) inline static
Remove an argument from the argument list.
Definition at line 78 of file Roccom_base.C.
Referenced by Roccom_base::Roccom_base().
{
   for ( int j=i; j<*argc-1; ++j) (*argv)[j]=(*argv)[j+1];
   --*argc;
 }
Variable Documentation
COM_END_NAME_SPACE void* p_xargc
Circumvent problem with missing variables.
Definition at line 2274 of file Roccom_base.C.
void* p_xargv
Definition at line 2275 of file Roccom_base.C.