Rocstar: roccom_c++.h File Reference
roccom_c++.h File Reference
Contains the wrapper routines for C++ binding of Roccom API.
#include <cstdlib>
#include <cstring>
#include <cassert>
#include "Roccom_base.h"
Macros
#define COM_set_bounds_prototype(type)
#define COM_get_array_prototype(type)
#define COM_get_array_const_prototype(type)
Functions
void COM_init (int *argc, char ***argv)
void COM_finalize ()
int COM_initialized ()
void COM_abort (int ierr)
void COM_set_default_communicator (MPI_Comm comm)
MPI_Comm COM_get_default_communicator ()
void COM_load_module (const char *libname, const char *winname)
void COM_unload_module (const char *libname, const char *winname=NULL)
void COM_close_module (const char *libname, const char *winname=NULL)
void COM_new_window (const char *wname, MPI_Comm c=MPI_COMM_NULL)
void COM_new_window (const std::string wname, MPI_Comm c=MPI_COMM_NULL)
void COM_delete_window (const char *wname)
void COM_delete_window (const std::string wname)
void COM_window_init_done (const char *w_str, int pane_changed=true)
void COM_window_init_done (const std::string w_str, int pane_changed=true)
void COM_delete_pane (const char *str, int pid)
void COM_delete_pane (const std::string str, int pid)
void COM_new_attribute (const char *wa_str, const char loc, const int type, int ncomp, const char *unit)
Registering an attribute type.
void COM_new_attribute (const std::string wa_str, const char loc, const int type, int ncomp, const char *unit)
void COM_delete_attribute (const char *wa_str)
Delete an existing attribute.
void COM_delete_attribute (const std::string wa_str)
void COM_set_size (const char *wa_str, int pane_id, int size, int ng=0)
Set sizes of for a specific attribute.
void COM_set_size (const std::string wa_str, int pane_id, int size, int ng=0)
template<class Type >
void COM_set_object (const char *wa_str, int pane_id, Type *addr)
template<class Type >
void COM_get_object (const char *wa_str, int pane_id, Type **addr)
void COM_set_array (const char *wa_str, int pane_id, void *addr, int strd=0, int cap=0)
Associates an array with an attribute for a specific pane.
void COM_set_array_const (const char *wa_str, int pane_id, const void *addr, int strd=0, int cap=0)
void COM_set_array (const std::string wa_str, int pane_id, void *addr, int strd=0, int cap=0)
void COM_set_array_const (const std::string wa_str, int pane_id, const void *addr, int strd=0, int cap=0)
void COM_set_bounds (const char *wa_str, int pane_id, const void *lbound, const void *ubound)
Set the lower and upper bounds of an attribute.
void COM_set_bounds (const std::string wa_str, int pane_id, const void *lbound, const void *ubound)
COM_set_bounds_prototype (char) COM_set_bounds_prototype(int) COM_set_bounds_prototype(float) COM_set_bounds_prototype(double) inline void COM_allocate_array(const char *wa_str
void COM_icall_function (const int wf, int argc,...)
void COM_call_function (const int wf)
void COM_call_function (const int wf, const void *wa)
void COM_call_function (const int wf, const void *wa1, const void *wa2)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6)
void COM_call_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7)
void COM_icall_function (const int wf, int *id)
void COM_icall_function (const int wf, const void *wa, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, int *id)
void COM_icall_function (const int wf, const void *wa1, const void *wa2, const void *wa3, const void *wa4, const void *wa5, const void *wa6, const void *wa7, int *id)
void COM_wait (const int id)
int COM_test (const int id)
void COM_set_verbose (int i)
void COM_set_debug (bool debug)
void COM_set_profiling (int i)
void COM_set_profiling_barrier (int hdl, MPI_Comm comm)
void COM_print_profile (const char *fname, const char *header)
int COM_get_sizeof (const COM_Type type, int c)
int COM_compatible_types (COM_Type type1, COM_Type type2)
int COM_get_error_code ()
Variables
int pane_id =0
int void ** addr =NULL
int void int strd =0
int void int int cap
Detailed Description
Contains the wrapper routines for C++ binding of Roccom API.
All the functions are inlined and hence have smaller runtime overhead compared with the C binding.
See also
roccom_c.h
Definition in file roccom_c++.h.
Macro Definition Documentation
#define COM_get_array_const_prototype (type)
Value:
inline void COM_get_array_const(const char *wa_str, int pane_id, \
                          const type **addr, int *strd=NULL, int *cap=NULL) \
{ COM_get_roccom()->get_array(wa_str, pane_id, \
                               (void**)addr, strd, cap, true); }
#define COM_get_array_prototype (type)
Value:
inline void COM_get_array(const char *wa_str, int pane_id, \
                           type **addr, int *strd=NULL, int *cap=NULL) \
{ COM_get_roccom()->get_array(wa_str, pane_id, (void**)addr, strd, cap); }
#define COM_set_bounds_prototype (type)
Value:
inline void COM_set_bounds(const char *wa_str, int pane_id, \
                            type lbound, type ubound) \
{ COM_get_roccom()->set_bounds(wa_str, pane_id, &lbound, &ubound); }
Definition at line 185 of file roccom_c++.h.
Function Documentation
void COM_abort (int ierr) inline
Definition at line 64 of file roccom_c++.h.
 { COM::Roccom_base::abort( ierr); }
void COM_call_function (const int wf) inline
Definition at line 442 of file roccom_c++.h.
References COM_get_roccom().
Referenced by _load_rocface(), InterpolateBase::backup(), build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), Agent::check_convergence_help(), compute_area(), compute_fnormal_error(), FluidAgent::compute_integrals(), SolidAgent::compute_integrals(), compute_overlay(), compute_quadric_normals(), compute_vnormal_error(), compute_volume(), compute_weighted_normals(), FluidAgent::create_buffer_all(), InterpolateBase::extrapolate_Linear(), Agent::finalize(), getPaneConnectivity(), getWindow(), InterpolateBase::init(), GetDeformedMesh::init(), GetDeformedMesh_ALE::init(), MeshMotionTransferISS::init(), init_attributes(), init_constraints(), init_constraints_acmflu(), init_constraints_acmfrac(), init_constraints_labscale(), init_constraints_myacm(), init_constraints_staraft(), init_constraints_starslice(), FluidAgent::init_convergence(), Rocon::init_from_file(), BurnAgent::init_module(), FluidAgent::init_module(), SolidAgent::init_module(), init_normals(), init_parameters(), RFC_Window_transfer::init_recv_buffer(), load_rocon(), load_rocprop(), main(), FluidAgent::output_restart_files(), output_solution(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), Agent::read_by_control_file(), read_file(), read_pane_sp(), BurnAgent::read_restart_data(), FluidAgent::read_restart_data(), SolidAgent::read_restart_data(), RFC_Window_base::read_sdv(), IM_Reader::read_winmesh(), remesh(), SetValueDouble::run(), LoadTransfer_FS::run(), Extrapolate_Linear::run(), CopyValue::run(), Extrapolate_Central::run(), LoadTransfer_FSc_ALE::run(), Interpolate_Linear::run(), Interpolate_Constant::run(), Interpolate_Central::run(), LoadTransferOnly_FSc_ALE::run(), GetDeformedMesh::run(), PhysicsAction::run(), GetDeformedMesh_ALE::run(), SurfDiver::run(), MeshMotionTransfer_SF::run(), ComputeFluidLoad_ALE::run(), DeformationVelTransfer_SF::run(), ComputeMeshMotion::run(), MeshMotionTransferISS::run(), ComputeFaceCenters::run(), TransferSolidDensity::run(), FluidPropagateSurface::run(), TransferBurnRate_FS_ALE::run(), MassTransfer_SF_ALE::run(), MassTransfer::run(), TemperatureTransfer_SF::run(), ZoomInterface::run(), HeatTransfer_FS::run(), ComputeRhofvf::run(), ComputeBurnPane::run(), RemeshInit::run(), ComputePconn::run(), SolidPropagateSurface_ALE::run(), Reset_du_alp::run(), TRAIL_AutoSurfer(), TRAIL_FE2FD_Transfer(), TRAIL_File2Window(), TRAIL_HDF2Window(), TRAIL_RocmopSmooth(), TRAIL_RocpropSmoothSurf(), TRAIL_TransferSurfDataFILE(), TRAIL_WriteWindow(), Control_parameters::update_communicator(), FullyCoupling::update_distances(), Agent::write_control_file(), Agent::write_data_files(), and RFC_Window_base::write_sdv().
 { COM_get_roccom()->call_function( wf, 0, 0); }
void COM_call_function (const int wf, const void * wa) inline
Definition at line 444 of file roccom_c++.h.
References COM_get_roccom().
{
   COM_get_roccom()->call_function( wf, 1, (void**)&wa);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2) inline
Definition at line 447 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2};
   COM_get_roccom()->call_function( wf, 2, (void **)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3) inline
Definition at line 452 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3 };
   COM_get_roccom()->call_function( wf, 3, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4) inline
Definition at line 457 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3, wa4 };
   COM_get_roccom()->call_function( wf, 4, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5) inline
Definition at line 464 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5 };
   COM_get_roccom()->call_function( wf, 5, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6) inline
Definition at line 471 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6 };
   COM_get_roccom()->call_function( wf, 6, (void**)args);
 }
void COM_call_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7) inline
Definition at line 479 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7 };
   COM_get_roccom()->call_function( wf, 7, (void**)args);
 }
void COM_close_module (const char * libname, const char * winname = NULL) inline
Definition at line 81 of file roccom_c++.h.
References COM_get_roccom().
Referenced by BurnAgent::unload_module(), FluidAgent::unload_module(), and SolidAgent::unload_module().
 { COM_get_roccom()->unload_module( libname, winname?winname:"", 0); }
int COM_compatible_types (COM_Type type1, COM_Type type2) inline
Definition at line 563 of file roccom_c++.h.
Referenced by Rocblas::axpy_gen(), Propagation_3::bound_facial_speed(), Rocblas::calc(), Rocblas::calcDot(), Rocsurf::compute_element_areas(), Window_manifold_2::compute_normals(), Pane_boundary::determine_borders(), Rocmop::determine_physical_border(), Window_manifold_2::elements_to_nodes(), Rocblas::gen2arg(), Rocsurf::integrate(), Propagation_3::set_bounds(), Window_manifold_2::shortest_edge_length(), Rocmop::smoother_specific_init(), Window_manifold_2::update_bd_flags(), Window_manifold_2::update_bd_normals(), and Window_manifold_2::update_bdedge_bitmap().
 { return COM::Attribute::compatible_types( type1, type2); }
void COM_delete_attribute (const char * wa_str) inline
Delete an existing attribute.
Definition at line 128 of file roccom_c++.h.
References COM_get_roccom().
Referenced by getWindow(), main(), read_file(), IM_Reader::read_winmesh(), TRAIL_File2Window(), and TRAIL_HDF2Window().
 { COM_get_roccom()->delete_attribute( wa_str); }
void COM_delete_attribute (const std::string wa_str) inline
Definition at line 132 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->delete_attribute( wa_str.c_str()); }
void COM_delete_pane (const char * str, int pid) inline
Definition at line 110 of file roccom_c++.h.
References COM_get_roccom().
Referenced by read_file(), TRAIL_File2Window(), and RFC_Window_base::write_sdv().
 { COM_get_roccom()->delete_pane( str, pid) ; }
void COM_delete_pane (const std::string str, int pid) inline
Definition at line 114 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->delete_pane( str.c_str(), pid) ; }
void COM_delete_window (const char * wname) inline
Definition at line 94 of file roccom_c++.h.
References COM_get_roccom().
Referenced by SolidAgent::create_buffer_all(), GEM_Partition::DestroyWindows(), BurnAgent::finalize(), FluidAgent::finalize(), SolidAgent::finalize(), Rocblas::finalize(), Rocout::finalize(), Rocin::finalize(), getWindow(), Rocon::init_from_file(), BurnAgent::init_module(), FluidAgent::init_module(), SolidAgent::init_module(), RFC_Window_transfer::init_recv_buffer(), Rocon::initialize(), main(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), read_pane_sp(), RFC_Window_base::read_sdv(), remesh(), TRAIL_AutoSurfer(), TRAIL_File2Window(), TRAIL_HDF2Window(), TRAIL_RemeshWrite(), TRAIL_RocmopSmooth(), TRAIL_RocpropSmoothSurf(), TRAIL_TransferSurfDataFILE(), Rocmap::unload(), Rocsurf::unload(), Rocmop::unload(), Rocon::unload(), Rocprop::unload(), and RFC_Window_base::write_sdv().
 { COM_get_roccom()->delete_window(wname); }
void COM_delete_window (const std::string wname) inline
Definition at line 98 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->delete_window(wname.c_str()); }
void COM_finalize () inline
Definition at line 59 of file roccom_c++.h.
Referenced by main(), and RocstarShutdown().
 { COM::Roccom_base::finalize(); }
MPI_Comm COM_get_default_communicator () inline
Definition at line 69 of file roccom_c++.h.
Referenced by compute_overlay(), GetCommunicator(), Rocin::read_by_control_file(), Rocin::read_windows(), SurfDiver::run(), TRAIL_FE2FD_Transfer(), and Rocout::write_rocin_control_file().
 { return COM::Roccom_base::get_default_communicator(); }
int COM_get_error_code () inline
Definition at line 566 of file roccom_c++.h.
References COM_get_roccom().
 { return COM_get_roccom()->get_error_code(); }
void COM_get_object (const char * wa_str, int pane_id, Type ** addr) inline
Definition at line 152 of file roccom_c++.h.
References COM_get_roccom().
Referenced by Rocout::finalize(), Rocin::finalize(), Rocsurf::unload(), Rocmop::unload(), Rocon::unload(), and Rocprop::unload().
 { COM_get_roccom()->get_object( wa_str, pane_id, (void**)addr); }
int COM_get_sizeof (const COM_Type type, int c) inline
Definition at line 560 of file roccom_c++.h.
References get_sizeof().
Referenced by Window_manifold_2::accumulate_bd_values(), Node::addr(), Halfedge::addr(), Pane_communicator::begin_update(), broadcast_win_attributes(), Pane_communicator::init(), Pane_communicator::reduce_average_on_shared_nodes(), Pane_communicator::reduce_diff_on_shared_nodes(), Pane_communicator::reduce_maxabs_on_shared_nodes(), Pane_communicator::reduce_minabs_on_shared_nodes(), Pane_communicator::reduce_on_shared_nodes(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), TRAIL_FD2FE_Transfer(), TRAIL_FE2FD_Transfer(), and Pane_communicator::update_ghost_values().
 { return COM::Attribute::get_sizeof( type, c); }
void COM_icall_function (const int wf, int argc, ...)
Definition at line 64 of file roccom_c.C.
{
   COM_assertion_msg( argc <= Function::MAX_NUMARG, "Too many arguments") ;
   int i;
   void *args[Function::MAX_NUMARG];
   va_list   ap;
   va_start( ap, argc);
   for ( i=0; i<argc-1; ++i) {
     args[i] = va_arg( ap, void*);
   }
   int *status = va_arg( ap, int *);
   va_end( ap);
   COM_get_roccom()->icall_function( wf, argc, args, status);
 }
void COM_icall_function (const int wf, int * id) inline
Definition at line 488 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->icall_function( wf, 0, 0, id); }
void COM_icall_function (const int wf, const void * wa, int * id) inline
Definition at line 490 of file roccom_c++.h.
References COM_get_roccom().
{
   COM_get_roccom()->icall_function( wf, 1, (void**)&wa, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, int * id) inline
Definition at line 493 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2};
   COM_get_roccom()->icall_function( wf, 2, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, int * id) inline
Definition at line 498 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3 };
   COM_get_roccom()->icall_function( wf, 3, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, int * id) inline
Definition at line 504 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3, wa4 };
   COM_get_roccom()->icall_function( wf, 4, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, int * id) inline
Definition at line 511 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5 };
   COM_get_roccom()->icall_function( wf, 5, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, int * id) inline
Definition at line 519 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6 };
   COM_get_roccom()->icall_function( wf, 6, (void **)args, id);
 }
void COM_icall_function (const int wf, const void * wa1, const void * wa2, const void * wa3, const void * wa4, const void * wa5, const void * wa6, const void * wa7, int * id) inline
Definition at line 527 of file roccom_c++.h.
References COM_get_roccom().
{
   const void *args[] = { wa1, wa2, wa3, wa4, wa5, wa6, wa7 };
   COM_get_roccom()->icall_function( wf, 7, (void **)args, id);
 }
void COM_init (int * argc, char *** argv) inline
Definition at line 57 of file roccom_c++.h.
Referenced by main().
 { COM::Roccom_base::init( argc, argv); }
int COM_initialized () inline
Definition at line 62 of file roccom_c++.h.
 { return COM::Roccom_base::initialized(); }
void COM_load_module (const char * libname, const char * winname) inline
Definition at line 75 of file roccom_c++.h.
References COM_get_roccom().
Referenced by BurnAgent::load_module(), FluidAgent::load_module(), SolidAgent::load_module(), and main().
 { COM_get_roccom()->load_module( libname, winname); }
void COM_new_attribute (const char * wa_str, const char loc, const int type, int ncomp, const char * unit) inline
Registering an attribute type.
wa_str is the attribute's name in the format "window.attribute". loc is the code for the location of the data, which can be 'w' for window attribute, 'p' for pane attribute, 'n' for node attribute, or 'e' for element attribute. type is the data type of the attribute. For C/C++, it can be COM_CHAR, COM_UNSIGNED_CHAR, COM_BYTE, COM_SHORT, COM_UNSIGNED_SHORT, COM_INT, COM_UNSIGNED, COM_LONG, COM_UNSIGNED_LONG, COM_FLOAT0, COM_DOUBLE1, COM_LONG_DOUBLE, COM_LONG_LONG_INT, or a derived data type. For Fortran, it can be COM_CHARACTER, COM_INTEGER, COM_LOGICAL, COM_REAL, COM_DOUBLE_PRECISION, COM_COMPLEX, COM_DOUBLE_COMPLEX. size is the length of the attribute in the given data type
Definition at line 118 of file roccom_c++.h.
References COM_get_roccom().
Referenced by Coupling::baseInit(), NewAttribute::create(), FluidAgent::create_buffer_all(), SolidAgent::create_buffer_all(), GEM_DomainBoundary::Create_com_surfsoln(), GEM_Partition::Create_com_volsoln(), Agent::create_window(), Rocout::init(), Rocin::init(), init_attributes(), Rocsurf::load(), Rocmop::load(), Rocon::load(), Rocprop::load(), main(), makeWindow(), new_attributes(), RFC_Window_base::new_sdv_attributes(), RFC_Window_overlay::print_features(), Rocin::read_parameter_file(), Rocin::register_panes(), FluRegion::RegisterFluSurfaceMesh(), FluRegion::RegisterSurfaceSoln(), FluRegion::RegisterVolumeSoln(), TRAIL_Add_Attributes(), TRAIL_AutoSurfer(), TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), TRAIL_FluRegisterSurfMesh(), TRAIL_FluRegisterSurfSoln(), TRAIL_FluRegisterVolSoln(), TRAIL_RocmopSmooth(), TRAIL_RocpropSmoothSurf(), and TRAIL_TransferSurfDataFILE().
 { COM_get_roccom()->new_attribute( wa_str, loc, type, ncomp, unit); }
void COM_new_attribute (const std::string wa_str, const char loc, const int type, int ncomp, const char * unit) inline
Definition at line 123 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->new_attribute( wa_str.c_str(), loc, type, ncomp, unit); }
void COM_new_window (const char * wname, MPI_Comm c = MPI_COMM_NULL) inline
Definition at line 86 of file roccom_c++.h.
References COM_get_roccom().
Referenced by Coupling::baseInit(), build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), convertWindow(), FluidAgent::create_buffer_all(), BurnAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), Agent::create_window(), getWindow(), Rocblas::init(), Rocout::init(), Rocin::init(), Rocon::initialize(), GEM_Partition::InitRoccomWindows(), FluidAgent::input(), BurnAgent::input(), Rocmap::load(), Rocsurf::load(), Rocmop::load(), Rocon::load(), Rocprop::load(), main(), makeWindow(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), Neutral_Reader::read_mesh(), OBJ_Reader::read_mesh(), SMF_Reader::read_mesh(), MSH_Reader::read_mesh(), IM_Reader::read_mesh(), Rocin::read_parameter_file(), Rocin::read_windows(), remesh(), Agent::split_surface_window(), TRAIL_ExtractSurf0(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), TRAIL_File2Window(), TRAIL_HDF2Window(), TRAIL_RemeshWrite(), TRAIL_RocmopSmooth(), TRAIL_RocpropSmoothSurf(), TRAIL_SurfaceMesh2Window(), and RFC_Window_base::write_sdv().
 { COM_get_roccom()->new_window(wname, c); }
void COM_new_window (const std::string wname, MPI_Comm c = MPI_COMM_NULL) inline
Definition at line 90 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->new_window(wname.c_str(), c); }
void COM_print_profile (const char * fname, const char * header) inline
Definition at line 557 of file roccom_c++.h.
References COM_get_roccom().
Referenced by main(), and rocstar_driver().
 { COM_get_roccom()->print_profile( fname, header); }
void COM_set_array (const char * wa_str, int pane_id, void * addr, int strd = 0, int cap = 0) inline
Associates an array with an attribute for a specific pane.
Definition at line 156 of file roccom_c++.h.
References cap, COM_get_roccom(), and strd.
Referenced by add_ghost_nodes2D(), build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), GEM_DomainBoundary::Create_com_surfsoln(), GEM_Partition::Create_com_volsoln(), GEM_Partition::CreatePconn(), main(), GEM_Partition::PopulateVolumeWindow(), IM_Reader::read_pane_ij(), GEM_DomainBoundary::Register_com_surfmesh(), GEM_Partition::Register_com_volconn(), Rocin::register_panes(), FluRegion::RegisterFluSurfaceMesh(), FluPatch::RegisterSoln(), FluRegion::RegisterVolumeSoln(), TRAIL_FluRegisterSurfMesh(), TRAIL_FluRegisterSurfSoln(), TRAIL_FluRegisterVolSoln(), TRAIL_RocmopSmooth(), and TRAIL_RocpropSmoothSurf().
 { COM_get_roccom()->set_array( wa_str, pane_id, addr, strd, cap); }
void COM_set_array (const std::string wa_str, int pane_id, void * addr, int strd = 0, int cap = 0) inline
Definition at line 166 of file roccom_c++.h.
References addr, cap, COM_get_roccom(), pane_id, and strd.
 { COM_get_roccom()->set_array( wa_str.c_str(), pane_id, addr, strd, cap); }
void COM_set_array_const (const char * wa_str, int pane_id, const void * addr, int strd = 0, int cap = 0) inline
Definition at line 160 of file roccom_c++.h.
References cap, COM_get_roccom(), and strd.
Referenced by Rocsurf::load(), main(), and RFC_Pane_base::register_sdv_attributes().
 { COM_get_roccom()->set_array( wa_str, pane_id,
                                const_cast<void*>(addr), strd, cap, true); }
void COM_set_array_const (const std::string wa_str, int pane_id, const void * addr, int strd = 0, int cap = 0) inline
Definition at line 170 of file roccom_c++.h.
References addr, cap, COM_get_roccom(), pane_id, and strd.
 { COM_get_roccom()->set_array( wa_str.c_str(), pane_id,
                                const_cast<void*>(addr), strd, cap, true); }
void COM_set_bounds (const char * wa_str, int pane_id, const void * lbound, const void * ubound) inline
Set the lower and upper bounds of an attribute.
Definition at line 176 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->set_bounds( wa_str, pane_id, lbound, ubound); }
void COM_set_bounds (const std::string wa_str, int pane_id, const void * lbound, const void * ubound) inline
Definition at line 181 of file roccom_c++.h.
References COM_get_roccom(), and pane_id.
 { COM_get_roccom()->set_bounds( wa_str.c_str(), pane_id, lbound, ubound); }
COM_set_bounds_prototype (char) const
void COM_set_debug (bool debug) inline
Definition at line 546 of file roccom_c++.h.
References COM_get_roccom().
Referenced by rocstar_driver().
 { COM_get_roccom()->set_debug( debug); }
void COM_set_default_communicator (MPI_Comm comm) inline
Definition at line 67 of file roccom_c++.h.
Referenced by compute_overlay(), SurfDiver::run(), TRAIL_AutoSurfer(), TRAIL_FE2FD_Transfer(), and Control_parameters::update_communicator().
 { COM::Roccom_base::set_default_communicator( comm); }
void COM_set_object (const char * wa_str, int pane_id, Type * addr) inline
Definition at line 144 of file roccom_c++.h.
References COM_assertion_msg, and COM_get_roccom().
Referenced by Coupling::baseInit(), Agent::create_window(), Rocout::init(), Rocin::init(), Rocsurf::load(), Rocmop::load(), Rocon::load(), and Rocprop::load().
{
   COM_assertion_msg( addr && COM_Object(*addr).validate_object()==0,
                      "Invalid casting");
   COM_get_roccom()->set_object( wa_str, pane_id, addr, (COM_Object*)(addr));
 }
void COM_set_profiling (int i) inline
Definition at line 550 of file roccom_c++.h.
References COM_get_roccom().
Referenced by compute_overlay(), main(), rocstar_driver(), SurfDiver::run(), and TRAIL_RemeshWrite().
 { COM_get_roccom()->set_profiling( i); }
void COM_set_profiling_barrier (int hdl, MPI_Comm comm) inline
Definition at line 554 of file roccom_c++.h.
References COM_get_roccom().
Referenced by _load_rocface(), Agent::init_function_handles(), load_rocprop(), and main().
 { COM_get_roccom()->set_profiling_barrier( hdl, comm); }
void COM_set_size (const char * wa_str, int pane_id, int size, int ng = 0) inline
Set sizes of for a specific attribute.
Definition at line 136 of file roccom_c++.h.
References COM_get_roccom().
Referenced by build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), GEM_Partition::CreatePconn(), init_attributes(), init_constraints_staraft(), main(), new_attributes(), GEM_Partition::PopulateVolumeWindow(), MSH_Reader::read_pane_coors(), SMF_Reader::read_pane_coors(), OBJ_Reader::read_pane_coors(), Neutral_Reader::read_pane_coors(), IM_Reader::read_pane_coors(), OBJ_Reader::read_pane_elems(), MSH_Reader::read_pane_elems(), SMF_Reader::read_pane_elems(), Neutral_Reader::read_pane_elems(), IM_Reader::read_pane_elems(), Rocin::read_parameter_file(), GEM_DomainBoundary::Register_com_surfmesh(), GEM_Partition::Register_com_volconn(), Rocin::register_panes(), RFC_Pane_base::register_sdv_attributes(), FluRegion::RegisterFluSurfaceMesh(), FluPatch::RegisterSoln(), FluRegion::RegisterVolumeSoln(), TRAIL_Copy2Attribute(), TRAIL_FD2FE_WinCreate(), TRAIL_FD2FE_WinCreate2(), TRAIL_FluRegisterSurfMesh(), TRAIL_FluRegisterSurfSoln(), TRAIL_FluRegisterVolSoln(), TRAIL_RocpropSmoothSurf(), TRAIL_SetAttribute(), TRAIL_SurfaceMesh2Window(), and TRAIL_UnstructuredMesh2Pane().
 { COM_get_roccom()->set_size( wa_str, pane_id, size, ng); }
void COM_set_size (const std::string wa_str, int pane_id, int size, int ng = 0) inline
Definition at line 140 of file roccom_c++.h.
References COM_get_roccom(), and pane_id.
 { COM_get_roccom()->set_size( wa_str.c_str(), pane_id, size, ng); }
void COM_set_verbose (int i) inline
Definition at line 543 of file roccom_c++.h.
References COM_get_roccom().
Referenced by main(), and rocstar_driver().
 { COM_get_roccom()->set_verbose( i); }
int COM_test (const int id) inline
Definition at line 540 of file roccom_c++.h.
References COM_get_roccom().
 { return COM_get_roccom()->test( id); }
void COM_unload_module (const char * libname, const char * winname = NULL) inline
Definition at line 78 of file roccom_c++.h.
References COM_get_roccom().
Referenced by BurnAgent::unload_module(), FluidAgent::unload_module(), and SolidAgent::unload_module().
 { COM_get_roccom()->unload_module( libname, winname?winname:""); }
void COM_wait (const int id) inline
Definition at line 537 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->wait( id); }
void COM_window_init_done (const char * w_str, int pane_changed = true) inline
Definition at line 102 of file roccom_c++.h.
References COM_get_roccom().
Referenced by build_unstr_hex(), build_unstr_prism(), build_unstr_prism_tet(), build_unstr_prism_tet_2(), build_unstr_pyr(), build_unstr_tet_2(), compute_overlay(), convertWindow(), FluidAgent::create_buffer_all(), BurnAgent::create_buffer_all(), SolidAgent::create_buffer_all(), Agent::create_buffer_all(), Agent::create_registered_attributes(), Agent::create_window(), getWindow(), Rocblas::init(), Rocout::init(), Rocin::init(), init_attributes(), Rocon::init_from_file(), BurnAgent::init_module(), Rocon::initialize(), FluidAgent::input(), BurnAgent::input(), Rocmap::load(), Rocsurf::load(), Rocmop::load(), Rocon::load(), Rocprop::load(), main(), RFC_Window_overlay::print_features(), Control_parameters::read(), RocmanControl_parameters::read(), read_file(), Rocin::read_parameter_file(), Rocin::read_windows(), RFC_Pane_base::register_sdv_attributes(), remesh(), SurfDiver::run(), Agent::split_surface_window(), TRAIL_Add_Attributes(), TRAIL_ExtractSurf0(), TRAIL_FD2FE_Transfer(), TRAIL_FD2FE_WinCreate2(), TRAIL_File2Window(), TRAIL_FixRocstarData(), TRAIL_HDF2Window(), TRAIL_RocmopSmooth(), TRAIL_SurfaceMesh2Window(), GEM_Partition::WindowInitDone(), and RFC_Window_base::write_sdv().
 { COM_get_roccom()->window_init_done( w_str, pane_changed); }
void COM_window_init_done (const std::string w_str, int pane_changed = true) inline
Definition at line 106 of file roccom_c++.h.
References COM_get_roccom().
 { COM_get_roccom()->window_init_done( w_str.c_str(), pane_changed); }
Variable Documentation
int void** addr =NULL
Definition at line 197 of file roccom_c++.h.
Referenced by Window::alloc_array(), Roccom_base::allocate_array(), broadcast_win_attributes(), com_get_address_f(), com_obtain_array_f(), com_obtain_array_helper(), com_set_address_f(), COM_set_array(), COM_set_array_const(), com_set_array_const_f(), com_set_array_const_helper(), com_set_array_f(), com_set_array_helper(), Pane_connectivity::create_b2map(), Pane_ghost_connectivity::finalize_pconn(), Roccom_base::get_array(), Window::get_array(), get_array_common(), io_pane_attribute(), main(), Rocin::read_parameter_file(), Pane::reinit_attr(), Window::reinit_attr(), Pane::reinit_conn(), Window::reinit_conn(), RFC_Window_transfer::replicate_data(), Window::resize_array(), Roccom_base::resize_array(), rflu_modhashtable::rflu_hashedge(), rflu_modhashtable::rflu_hashface(), rflu_modhashtable::rflu_hashfuncprimary(), rflu_modhashtable::rflu_hashfuncsecondary(), rflu_modhashtable::rflu_hashvertex(), rflu_modhashtable::rflu_hashvertexfancy(), rflu_modhashtable::rflu_unhashbface(), Roccom_base::set_array(), and Window::set_array().
int void int int cap
Definition at line 197 of file roccom_c++.h.
Referenced by Window::alloc_array(), Connectivity::allocate(), Attribute::allocate(), Roccom_base::allocate_array(), Rocon::burnout(), com_obtain_array_f(), COM_print_window(), COM_set_array(), COM_set_array_const(), com_set_array_const_f(), com_set_array_f(), Pane_connectivity::create_b2map(), debug_int_print(), debug_print(), Roccom_base::get_array(), Window::get_array(), get_array_common(), HeatTransfer_FS::init(), locthermcap_v3d8(), Pane::reinit_attr(), Window::reinit_attr(), Pane::reinit_conn(), Window::reinit_conn(), Window::resize_array(), Roccom_base::resize_array(), Roccom_base::set_array(), Window::set_array(), Connectivity::set_pointer(), and Attribute::set_pointer().
int pane_id =0
Definition at line 196 of file roccom_c++.h.
Referenced by Window::alloc_array(), Window::append_array(), Partition::BuildPartitionBoundaries(), Rocon::burnout(), Rocon::burnout_filter(), com_append_array_f(), COM_F_FUNC2(), com_obtain_array_f(), COM_set_array(), COM_set_array_const(), com_set_array_const_f(), com_set_array_f(), COM_set_bounds(), COM_set_size(), Rocon::constrain_displacements(), Window::copy_array(), Overlay::count_subnodes(), GEM_DomainBoundary::Create_com_surfsoln(), GEM_Partition::Create_com_volsoln(), GEM_Partition::CreatePconn(), Window::dealloc_array(), Roccom_base::delete_pane(), Pane_ghost_connectivity::finalize_pconn(), Rocon::find_intersections(), Roccom_base::get_array(), Window::get_array(), Roccom_base::get_connectivities(), Pane_ghost_connectivity::get_node_total_order(), Roccom_base::get_parent(), RFC_Window_transfer::init_recv_buffer(), main(), Overlay::number_a_subnode(), GEM_Partition::PopulateVolumeWindow(), RFC_Pane_base::read_binary(), read_file(), RFC_Pane_base::read_rocin(), RFC_Window_base::read_sdv(), GEM_DomainBoundary::Register_com_surfmesh(), RFC_Pane_base::register_sdv_attributes(), FluPatch::RegisterSoln(), FluRegion::RegisterVolumeSoln(), Window::resize_array(), Window::set_array(), Roccom_base::set_bounds(), Overlay::set_subnode_id(), TRAIL_Att2Vec(), TRAIL_AutoSurfer(), TRAIL_Copy2Attribute(), TRAIL_ExtractSurf0(), TRAIL_FD2FE_Transfer(), TRAIL_FE2FD_Transfer(), TRAIL_FixRocstarData(), TRAIL_GetWindowSolnData(), TRAIL_SetAttribute(), TRAIL_TransferSurfDataFILE(), TRAIL_Window2UnstructuredMesh(), TRAIL_WriteWindow(), and RFC_Window_base::write_sdv().
int void int strd =0
Definition at line 197 of file roccom_c++.h.
Referenced by Window::alloc_array(), Connectivity::allocate(), Attribute::allocate(), Roccom_base::allocate_array(), Attribute::append_array(), broadcast_win_attributes(), Rocblas::calcDot(), com_obtain_array_f(), COM_print_window(), COM_set_array(), COM_set_array_const(), com_set_array_const_f(), com_set_array_f(), Attribute::copy_array(), Window_manifold_2::elements_to_nodes(), Roccom_base::get_array(), Window::get_array(), get_array_common(), Roccom_base::get_object(), io_pane_attribute(), Pane::reinit_attr(), Window::reinit_attr(), Pane::reinit_conn(), Window::reinit_conn(), Window::resize_array(), Roccom_base::resize_array(), Element_node_vectors_k_const< Value >::set(), Element_vectors_k_const< Value >::set(), Roccom_base::set_array(), Window::set_array(), Connectivity::set_pointer(), and Attribute::set_pointer().