Rocstar: Roccom_base.h File Reference
Roccom_base.h File Reference
Contains declaration of the base class for Roccom implementations.
#include "roccom_devel.h"
#include "maps.h"
#include <set>
Classes
class Roccom_base
This file indirectly includes the following files: iostream, map, string, vector, and roccom_basic.h.
Functions
COM_END_NAME_SPACE
COM::Roccom_base * COM_get_roccom ()
void COM_set_roccom (COM::Roccom_base *p)
Detailed Description
Contains declaration of the base class for Roccom implementations.
See Also
Roccom_base.C
Definition in file Roccom_base.h.
Function Documentation
COM_END_NAME_SPACE COM::Roccom_base* COM_get_roccom () inline
Definition at line 537 of file Roccom_base.h.
References COM_assertion_msg.
Referenced by COM_allocate_array(), COM_append_array(), com_append_array_helper(), COM_call_function(), COM_check_bounds(), COM_clone_attribute(), COM_close_module(), COM_copy_array(), COM_copy_attribute(), COM_deallocate_array(), COM_delete_attribute(), COM_delete_pane(), COM_delete_window(), COM_F_FUNC2(), COM_free_buffer(), COM_get_attribute(), COM_get_attribute_handle(), COM_get_attribute_handle_const(), COM_get_attributes(), COM_get_bounds(), COM_get_communicator(), COM_get_connectivities(), COM_get_error_code(), COM_get_function_handle(), COM_get_modules(), COM_get_object(), COM_get_panes(), COM_get_parent(), COM_get_size(), COM_get_status(), COM_get_window_handle(), COM_get_windows(), COM_icall_function(), COM_load_module(), COM_new_attribute(), COM_new_window(), com_obtain_array_helper(), COM_print_profile(), COM_resize_array(), COM_set_array(), COM_set_array_const(), com_set_array_const_helper(), com_set_array_helper(), COM_set_bounds(), COM_set_debug(), COM_set_function(), COM_set_member_function(), COM_set_object(), COM_set_profiling(), COM_set_profiling_barrier(), COM_set_size(), COM_set_verbose(), COM_test(), COM_unload_module(), COM_use_attribute(), COM_wait(), COM_window_init_done(), output_solution(), project_window(), PointPropagate::propagate_faces(), PointPropagate::propagate_nodes(), Rocin::read_parameter_file(), RFC_Pane_base::read_rocin(), rescale_object(), and Rocout::write_parameter_file().
 { COM::Roccom_base *roccom=COM::Roccom_base::get_roccom();
   COM_assertion_msg(roccom,
                     "Roccom must be initialized before any Roccom calls.");
   return roccom;
 }
void COM_set_roccom (COM::Roccom_base * p) inline
Definition at line 544 of file Roccom_base.h.
 { COM::Roccom_base::set_roccom(p); }