Rocstar: RocFracLoadModule.f90 File Reference
RocFracLoadModule.f90 File Reference
Functions/Subroutines
subroutine rocfrac_load_module (module_name)
subroutine rocfrac_unload_module (module_name)
Function/Subroutine Documentation
subroutine rocfrac_load_module (character(*), intent(in) module_name)
Definition at line 53 of file RocFracLoadModule.f90.
References m_rocburn_interface_data::associate_pointer(), integralcheck::checkintegral(), rocfracmain::rocfracfinalize(), rocfracmain::rocfracinitialize(), rocfracsubinterface::rocfracinterfaceupdate(), rocfracmain::rocfracsoln(), and rocfracmain::rocfracupdateinbuff().
Referenced by SolidAgent::load_module().
subroutine rocfrac_unload_module (character(*), intent(in) module_name)
Definition at line 126 of file RocFracLoadModule.f90.
References m_rocburn_interface_data::associate_pointer().
Referenced by SolidAgent::unload_module().