Rocstar: BuildVersionString.F90 File Reference
rocflo/BuildVersionString.F90 File Reference
Functions/Subroutines
subroutine buildversionstring (versionString)
Function/Subroutine Documentation
subroutine buildversionstring (character(*) versionString)
Definition at line 48 of file rocflo/BuildVersionString.F90.
References Kdtree_d< Traits >::build().
Referenced by peul_rocflo_post(), rflo_initflowsolver(), rflu_printheader(), rflu_writeversionstring(), rocflo_2dto3d(), rocflo_blocks(), rocflo_init(), rocflo_post(), rocflo_split(), rocflo_surf(), rocflo_toflu(), rocpart_post(), and rocvav_post().