Rocstar: RFLU_DeallocateMemoryWrapper.F90 File Reference
rocflu/RFLU_DeallocateMemoryWrapper.F90 File Reference
Functions/Subroutines
subroutine rflu_deallocatememorywrapper (pRegion)
Function/Subroutine Documentation
subroutine rflu_deallocatememorywrapper (type(t_region), pointer pRegion)
Definition at line 44 of file rocflu/RFLU_DeallocateMemoryWrapper.F90.
References moderror::deregisterfunction(), peri_rflu_deallocatememory(), plag_inrt_deallocmemtstep(), plag_rflu_deallocmemsol(), plag_rflu_deallocmemsoltile(), plag_rflu_deallocmemtstep(), plag_rflu_deallocmemtsteptile(), moderror::registerfunction(), rflu_deallocatememory(), rflu_destroygrid(), spec_rflu_deallocatememory(), spec_rflu_deallocatememoryeev(), and turb_rflu_deallocatememory().
Referenced by rflu_endflowsolver(), and rflucells().