Rocstar: RFLU_AllocateMemoryWrapper.F90 File Reference
rocflu/RFLU_AllocateMemoryWrapper.F90 File Reference
Functions/Subroutines
subroutine rflu_allocatememorywrapper (pRegion)
Function/Subroutine Documentation
subroutine rflu_allocatememorywrapper (type(t_region), pointer pRegion)
Definition at line 44 of file rocflu/RFLU_AllocateMemoryWrapper.F90.
References moderror::deregisterfunction(), peri_allocatememory(), plag_inrt_allocmemtstep(), plag_rflu_allocmemsol(), plag_rflu_allocmemsoltile(), plag_rflu_allocmemtstep(), plag_rflu_allocmemtsteptile(), radi_allocatememory(), moderror::registerfunction(), rflu_allocatememory(), rflu_modrocstaradmin::rflu_genx_createdatainterf(), spec_rflu_allocatememory(), spec_rflu_allocatememoryeev(), and turb_allocatememory().
Referenced by rflu_initflowsolver(), and rflucells().