Rocstar: RFLU_PrintHeader.F90 File Reference
rocflu/RFLU_PrintHeader.F90 File Reference
Functions/Subroutines
subroutine rflu_printheader (global)
Function/Subroutine Documentation
subroutine rflu_printheader (type(t_global), pointer global)
Definition at line 44 of file rocflu/RFLU_PrintHeader.F90.
References buildversionstring(), moderror::deregisterfunction(), plag_buildversionstring(), moderror::registerfunction(), spec_buildversionstring(), and turb_buildversionstring().
Referenced by rflu_initflowsolver(), rflu_mergepostprocessregions(), rflu_postprocessregionscommon1(), rflucells(), rfluconv(), rfluinit(), rflumap(), rflupart(), rflupick(), and rflupost().