Rocstar: util.h File Reference
RocfluidMP/utilities/rocflo/makeflo/util.h File Reference
#include <string>
Functions
bool incrementAscii (char *cur)
bool fileExists (const char *fName)
bool endsWith (const char *a, const char *suffix)
string replaceExtention (const string &a, const string &newSuffix)
const char * fortranifyString (const char *src)
Function Documentation
bool endsWith (const char * a, const char * suffix)
Definition at line 67 of file RocfluidMP/utilities/rocflo/makeflo/util.cpp.
Referenced by main(), read_file(), and writeBlocks().
 {
         int al=strlen(a);
         int sl=strlen(suffix);
         if (al<sl) return false;
         const char *a_suff=&a[al-sl];
         return 0==strcmp(a_suff,suffix);
 }
bool fileExists (const char * fName)
Definition at line 78 of file RocfluidMP/utilities/rocflo/makeflo/util.cpp.
References cimg_library::cimg::fclose(), and cimg_library::cimg::fopen().
Referenced by read_multiple().
{
         FILE *f=fopen(fName,"rb");
         if (f==NULL)
                 return false;
         else {
                 fclose(f);
                 return true;
         }
 }
const char* fortranifyString (const char * src)
Definition at line 116 of file RocfluidMP/utilities/rocflo/makeflo/util.cpp.
References i.
Referenced by read_file(), and write_fortran().
 {
         const int bufLen=500;
         static char buf[bufLen];
         strcpy(buf,src);
         //Pad with spaces
         for (int i=strlen(buf);i<bufLen;i++) buf[i]=' ';
         buf[bufLen-1]=0; //Zero-terminate for C use
         return buf;
 }
bool incrementAscii (char * cur)
Definition at line 90 of file RocfluidMP/utilities/rocflo/makeflo/util.cpp.
References i.
Referenced by read_multiple(), and writeBlocks().
 {
         //Starting from end, work backwards until we reach
         // the first decimal digit.
         int i=strlen(cur)-1;
         while (i>=0 && !isdigit(cur[i])) i--;
         if (i<0) return false; //No digits found
         //Carry loop
         while (true) {
                 //Increment the current digit
                 cur[i]++;
                 if (cur[i]!='9'+1)
                         break; //No carry needed-- finished
                 //Otherwise, wrap around and carry to next digit
                 cur[i]='0';
                 i--;
                 if (i<0 || !isdigit(cur[i])) return false; //Too many carries
         }
         return true;
 }
string replaceExtention (const string & a, const string & newSuffix)
Definition at line 128 of file RocfluidMP/utilities/rocflo/makeflo/util.cpp.
Referenced by main().
 {
         string ret(a);
         int dotLoc=ret.rfind(".");
         if (dotLoc==-1) return ret.append(newSuffix);
         return ret.erase(dotLoc).append(newSuffix);
 }