Rocstar: Rocin.C File Reference
Rocin.C File Reference
Implementation of Rocing for creation of Roccom window(s) from HDF files.
#include <algorithm>
#include <set>
#include <cmath>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <cstring>
#include <strings.h>
#include <errno.h>
#include <vector>
#include <list>
#include <glob.h>
#include <fnmatch.h>
#include <unistd.h>
#include <sys/types.h>
#include <dirent.h>
#include "Directory.H"
#include "Rocin.h"
Classes
class AutoCloser< T1, T2 >
Automatically close open files, datasets, etc.
Macros
#define DEBUG_MSG(x)
#define HDF4_CHECK_RET(routine, args, retval)
Perform HDF4 error-checking.
#define HDF4_CHECK(routine, args) HDF4_CHECK_RET(routine, args,)
Functions
static int glob_error (const char *epath, int gerrno)
Error callback for glob.
template<class T >
T cast_err_func (int(*glob)(const char *, int, T, glob_t *), int(*errfunc)(const char *, int))
Cast glob_error for portability (IBMSP has a different prototype)
static int32 FindFirstGeometryDataset (int32 sd_id, const std::string &geomFile, const std::string &matName, const std::string &label, int32 hIndex, int32 *index)
Find the first geometry dataset for the given block.
static void scan_files_HDF4 (int pathc, char *pathv[], BlockMM_HDF4 &blocks, std::string &time, std::map< int32, COM_Type > &HDF2COM)
Extract metadata from the list of files.
static void load_data_HDF4 (BlockMM_HDF4::iterator p, const BlockMM_HDF4::iterator &end, const std::string &window, const MPI_Comm *comm, int rank, int nprocs)
static void new_attributes (BlockMM_HDF4::iterator hdf4, const BlockMM_HDF4::iterator &hdf4End, const std::string &window, const MPI_Comm *comm, int rank, int nprocs)
static void broadcast_win_attributes (bool isEmpty, const std::string &window, const MPI_Comm *comm, int rank, int nprocs)
template<class BLOCK >
void free_blocks (BLOCK &blocks)
std::string CWD ()
void Rocin_load_module (const char *name)
Load the module Rocin into Roccom using the given module name.
void Rocin_unload_module (const char *name)
Unload the module Rocin from Roccom.
void COM_F_FUNC2 (rocin_load_module, ROCIN_LOAD_MODULE) const
void COM_F_FUNC2 (rocin_unload_module, ROCIN_UNLOAD_MODULE) const
Detailed Description
Implementation of Rocing for creation of Roccom window(s) from HDF files.
Definition in file Rocin.C.
Macro Definition Documentation
#define DEBUG_MSG (x)
Definition at line 80 of file Rocin.C.
Referenced by Rocin::init(), load_data_HDF4(), new_attributes(), Rocin::read_windows(), Rocin::register_panes(), and scan_files_HDF4().
#define HDF4_CHECK (routine, args) HDF4_CHECK_RET(routine, args,)
Definition at line 173 of file Rocin.C.
Referenced by FindFirstGeometryDataset(), load_data_HDF4(), and scan_files_HDF4().
#define HDF4_CHECK_RET (routine, args, retval)
Value:
{                                             \
    if((routine args) == FAIL) {              \
      sleep(1);                               \
      if((routine args) == FAIL) {            \
    sleep(1);                            \
        if((routine args) == FAIL) {          \
      sleep(1);                          \
          if((routine args) == FAIL) {                      \
            std::cerr << "Rocstar: Error: " #routine " (line "          \
                      << __LINE__ << " in " << __FILE__ << ") failed: " \
                      << HDF4::error_msg() << std::endl;                \
            retval;                                                     \
          } } } }                                                       \
  }
Perform HDF4 error-checking.
Check the return value of the HDF4 function and print an error message if it is FAIL
Parameters
routine The HDF4 function to call. (Input)
args The argument list, in parentheses. (Input)
val The return value. (Input)
Definition at line 147 of file Rocin.C.
Referenced by FindFirstGeometryDataset(), load_data_HDF4(), and scan_files_HDF4().
Function Documentation
static void broadcast_win_attributes (bool isEmpty, const std::string & window, const MPI_Comm * comm, int rank, int nprocs) static
Definition at line 2156 of file Rocin.C.
References addr, COM_free_buffer(), COM_get_array(), COM_get_attribute(), COM_get_attributes(), COM_get_sizeof(), empty(), i, and strd.
Referenced by Rocin::read_windows().
 {
   // Build an MPI message to synchronize variable names.
   int empty = isEmpty ? 1 : 0;
   std::vector<int> is_empty(nprocs);
   if ( *comm != MPI_COMM_NULL)
     MPI_Allgather(&empty, 1, MPI_INT, &is_empty[0], 1, MPI_INT, *comm);
   else
     is_empty[0] = empty;
   // Broadcast from the nonempty processor with highest rank.
   int last_empty=-1, root=-1;
   for (int i=0; i<nprocs; ++i) {
     if ( is_empty[i]) last_empty = i;
     else root = i;
   }
   if ( last_empty<0) return; // No need to broadcast.
   // Obtain the list of attributes
   int na; char *atts;
   COM_get_attributes( window.c_str(), &na, &atts);
   // Loop through the attributes
   std::istringstream is(atts);
   for ( int i=0; i<na; ++i) {
     // Obtain the attribute name
     std::string aname;  is >> aname;
     char loc;
     int  type, ncomp;
     COM_get_attribute( (window+"."+aname).c_str(), &loc, &type, &ncomp, NULL);
     if ( loc !='w') continue; // Skip non-window attributes;
     void *addr;
     int count, strd;
     COM_get_array( (window+"."+aname).c_str(), 0, &addr, &strd, &count);
     int len = COM_get_sizeof( type, count*ncomp);
     if ( *comm != MPI_COMM_NULL)
       MPI_Bcast( addr, len, MPI_CHAR, root, *comm);
   }
   COM_free_buffer( &atts);
 }
T cast_err_func (int(*)(const char *, int, T, glob_t *) glob, int(*)(const char *, int) errfunc) inline
Cast glob_error for portability (IBMSP has a different prototype)
Definition at line 133 of file Rocin.C.
Referenced by Rocin::read_windows().
 { return reinterpret_cast<T>(errfunc); }
void COM_F_FUNC2 (rocin_load_module , ROCIN_LOAD_MODULE) const
Definition at line 3044 of file Rocin.C.
References Mesquite::length(), and Rocin_load_module().
 { Rocin_load_module( std::string(name, length).c_str()); }
void COM_F_FUNC2 (rocin_unload_module , ROCIN_UNLOAD_MODULE) const
Definition at line 3046 of file Rocin.C.
References Mesquite::length(), and Rocin_unload_module().
 { Rocin_unload_module( std::string(name, length).c_str()); }
std::string CWD ()
Definition at line 2764 of file Rocin.C.
Referenced by Rocin::read_windows().
 {
   char buf[1024];
   return(std::string(getcwd(buf,1024)));
 }
static int32 FindFirstGeometryDataset (int32 sd_id, const std::string & geomFile, const std::string & matName, const std::string & label, int32 hIndex, int32 * index) static
Find the first geometry dataset for the given block.
The dataset may be right after the block header or in an external file. The caller is responsible for closing the sd_id.
Definition at line 288 of file Rocin.C.
References HDF4_CHECK, HDF4_CHECK_RET, MAX_NC_NAME, MAX_NC_VARS, rank, HDF4::SDend(), HDF4::SDendaccess(), HDF4::SDfileinfo(), HDF4::SDgetdatastrs(), HDF4::SDstart(), HDF4::Select(), and cimg_library::cimg::strcasecmp().
Referenced by scan_files_HDF4().
 {
   int32 geom_id;
   if (geomFile.empty()) {
     // We're not using a separate geometry file, so just return the dataset
     // immediately after the block header.
     geom_id = sd_id;
     *index = hIndex + 1;
     return geom_id;
   }
   // Open the geometry file.
   HDF4_CHECK_RET(geom_id = HDF4::SDstart, (geomFile.c_str(), DFACC_READ),
                  return FAIL);
   // Get the number of datasets.
   int32 dsCount = MAX_NC_VARS, nAttrs, status;
   HDF4_CHECK(HDF4::SDfileinfo, (geom_id, &dsCount, &nAttrs));
   int32 sds_id, rank, size[5], dType;
   char name[MAX_NC_NAME];
   // We're looking for the dataset for this material and section.
   std::string target = matName + '|' + label;
   // Scan through the datasets of the geometry file.
   for (*index=0; *index<dsCount; ++(*index)) {
     HDF4_CHECK_RET(sds_id = HDF4::Select,
                    (geom_id, *index, name, &rank, size, &dType, &nAttrs, dsCount),
                    HDF4::SDend(geom_id); return FAIL);
     HDF4_CHECK_RET(status = HDF4::SDgetdatastrs,
                    (sds_id, NULL, NULL, NULL, name, MAX_NC_NAME),
                    HDF4::SDendaccess(sds_id); continue);
     HDF4::SDendaccess(sds_id);
     // Check if this is the right dataset.
     if (strcasecmp(target.c_str(), name) == 0) { // We've found it!
       return geom_id;
     }
   }
   // No luck.
   HDF4::SDend(geom_id);
   return FAIL;
 }
void free_blocks (BLOCK & blocks)
Definition at line 2345 of file Rocin.C.
Referenced by Rocin::read_windows().
 {
   typename BLOCK::iterator p;
   for (p=blocks.begin(); p!=blocks.end(); ++p)
     delete (*p).second;
   blocks.clear();
 }
static int glob_error (const char * epath, int gerrno) static
Error callback for glob.
Definition at line 122 of file Rocin.C.
References COMMPI_Initialized().
Referenced by Rocin::read_windows().
 {
   if ( !COMMPI_Initialized())
     std::cerr << "Rocstar: Error (glob): error in pattern `" << epath << "': "
               << strerror(gerrno) << std::endl;
   return 0;
 }
static void load_data_HDF4 (BlockMM_HDF4::iterator p, const BlockMM_HDF4::iterator & end, const std::string & window, const MPI_Comm * comm, int rank, int nprocs) static
Definition at line 885 of file Rocin.C.
References COM_DOUBLE, COM_get_array(), COM_get_status(), COM_INT, COM_resize_array(), DEBUG_MSG, HDF4_CHECK, HDF4_CHECK_RET, i, Block_HDF4::m_file, Block_HDF4::m_geomFile, Block_HDF4::m_gridInfo, Block_HDF4::m_indices, Block_HDF4::m_numNodes, Block_HDF4::m_paneId, Block_HDF4::m_variables, max(), s, HDF4::SDend(), HDF4::SDendaccess(), HDF4::SDreaddata(), HDF4::SDselect(), HDF4::SDstart(), cimg_library::sin(), and Block_HDF4::time_level.
Referenced by Rocin::read_windows().
 {
   int local, i, ne = 0;
   Block_HDF4* block;
   std::string name;
   bool structured = 0;
   int32 sd_id = 0, sds_id, start[3], size[3];
   void* data;
   std::vector<int32>::iterator r;
   std::vector<GridInfo_HDF4>::iterator s;
   int with_pane=0;
   for ( ; p!=end; ++p, ++with_pane) {
     block = (*p).second;
     // Panes are a local construct, so make sure that this pane is local.
     local = COM_get_status( window.c_str(), block->m_paneId)>=0;
     if (!local) continue;
     if (block->m_geomFile.empty()) {
       HDF4_CHECK_RET(sd_id = HDF4::SDstart,
                      (block->m_file.c_str(), DFACC_READ),
                      continue);
     } else {
       HDF4_CHECK_RET(sd_id = HDF4::SDstart,
                      (block->m_geomFile.c_str(), DFACC_READ),
                      continue);
     }
     structured = (block->m_gridInfo.size() &&
                   block->m_gridInfo.front().m_name.substr(0,3)== ":st");
     // Let Roccom manage memory for nodal coordinates
     // Moved allocation outside of dimension loop.  Not sure if this fully
     // accounts for single registration of "nc" versus "1-nc", "2-nc", etc.
     name = window + ".nc";
     DEBUG_MSG("Calling COM_resize_array( name == '" << name << "', paneid == " << block->m_paneId << ", ptr == NULL, arg == 0 )");
     COM_resize_array(name.c_str(), block->m_paneId, NULL, 1);
     // Read the nodal coordinates.
     for (i=0; i<3; ++i) {
       // Read the mesh only if number of nodes is positive
       name = window + '.' + (char)('1' + i) + "-nc";
       COM_get_array(name.c_str(), block->m_paneId, &data);
       if (block->m_numNodes && data) {
         HDF4_CHECK_RET(sds_id = HDF4::SDselect, (sd_id, block->m_indices[i]),
                        continue);
         AutoCloser<int32, intn> auto1(sds_id, HDF4::SDendaccess);
         if (structured) {
           start[0] = start[1] = start[2] = 0;
           HDF4_CHECK(HDF4::SDreaddata,
                      (sds_id, start, NULL, block->m_gridInfo.front().m_size, data));
         } else {
           start[0] = 0;
           size[0] = block->m_numNodes;
           HDF4_CHECK(HDF4::SDreaddata, (sds_id, start, NULL, size, data));;
         }
 #ifdef DEBUG_DUMP_PREFIX
         {
           std::ofstream fout((DEBUG_DUMP_PREFIX + name + '.' + block->time_level + ".hdf").c_str());
           DebugDump(fout, block->m_numNodes, COM_DOUBLE, data);
         }
 #endif // DEBUG_DUMP_PREFIX
       }
     }
     // Read the connectivity tables.
     if (!structured) {
       ne = 0;
       for (s=block->m_gridInfo.begin(); s!=block->m_gridInfo.end(); ++s) {
         name = window + "." + (*s).m_name;
         DEBUG_MSG("Calling COM_resize_array( name == '" << name << "', paneid == " << block->m_paneId << ", ptr == " << &data << ", arg == 1 )");
         COM_resize_array(name.c_str(), block->m_paneId, &data, 1);
         start[0] = start[1] = 0;
         std::istringstream sin((*s).m_name);
         sin.get(); sin.get(); // Get rid if the leading two letter.
         sin >> size[0];
         size[1] = (*s).m_numElements;
         ne += (*s).m_numElements;
         if ( size[1] && data) {
           HDF4_CHECK_RET(sds_id = HDF4::SDselect, (sd_id, (*s).m_index),
                          continue);
           HDF4_CHECK(HDF4::SDreaddata, (sds_id, start, NULL, size, data));
 #ifdef DEBUG_DUMP_PREFIX
         {
           std::ofstream fout((DEBUG_DUMP_PREFIX + name + '.' + block->time_level + ".hdf").c_str());
           DebugDump(fout, size[0] * size[1], COM_INT, data);
         }
 #endif // DEBUG_DUMP_PREFIX
           HDF4::SDendaccess(sds_id);
         }
       }
     }
     if (!block->m_geomFile.empty()) {
       HDF4::SDend(sd_id);
       HDF4_CHECK_RET(sd_id = HDF4::SDstart, (block->m_file.c_str(), DFACC_READ),
                      continue);
     }
     // Read the attribute data.
     std::vector<VarInfo_HDF4>::iterator q;
     for (q=block->m_variables.begin(); q!=block->m_variables.end(); ++q) {
       // Skip NULL attributes.
       if ( (*q).m_is_null[0]) continue;
       // Read in window attribute only for the first pane.
       if ( with_pane && (*q).m_position=='w') continue;
       int loop = 1;
       //edited
       name = window + '.' + (*q).m_name;
       if ( (*q).m_position!='w')  { // Allocate for nonwindow attribute
         DEBUG_MSG("Calling COM_resize_array( name == '" << name << "', paneid == " << block->m_paneId << ", ptr == " << &data << ", arg == 1 )");
         COM_resize_array(name.c_str(), block->m_paneId, &data,1);
       } else {
         COM_get_array(name.c_str(), 0, &data);
       }
       for (r=(*q).m_indices.begin();
            r!=(*q).m_indices.end(); ++r, ++loop) {
         // If scalar, name = window.attribute
         // If vector, name = window.#-attribute
         if( (*q).m_indices.size()==1)
           name = window + '.' + (*q).m_name;
         else {
           std::ostringstream sout;
           sout << window << '.' << loop << '-' << (*q).m_name;
           name = sout.str();
         }
         COM_get_array(name.c_str(), block->m_paneId,&data);
         bool nonempty;
         if (structured && ((*q).m_position=='n' || (*q).m_position=='e')) {
           start[0] = start[1] = start[2] = 0;
           if ((*q).m_position == 'n') {
             size[0] = block->m_gridInfo.front().m_size[0];
             size[1] = block->m_gridInfo.front().m_size[1];
             size[2] = block->m_gridInfo.front().m_size[2];
           } else {
             size[0] = std::max(int32(1),
                                block->m_gridInfo.front().m_size[0]-1);
             size[1] = std::max(int32(1),
                                block->m_gridInfo.front().m_size[1]-1);
             size[2] = std::max(int32(1),
                                block->m_gridInfo.front().m_size[2]-1);
           }
           nonempty = block->m_numNodes && data;
         } else {
           start[0] = 0;
           size[0] = (*q).m_nitems;
           nonempty = size[0] && data;
         }
         if ( nonempty) {
           HDF4_CHECK_RET(sds_id = HDF4::SDselect, (sd_id, *r), continue);
           HDF4_CHECK(HDF4::SDreaddata, (sds_id, start, NULL, size, data));
 #ifdef DEBUG_DUMP_PREFIX
           {
             std::ofstream fout((DEBUG_DUMP_PREFIX + name + '.' + block->time_level + ".hdf").c_str());
             DebugDump(fout, (*q).m_nitems, (*q).m_dataType, data);
           }
 #endif // DEBUG_DUMP_PREFIX
           HDF4::SDendaccess(sds_id);
         }
       }
     }
     HDF4::SDend(sd_id);
   }
 }
static void new_attributes (BlockMM_HDF4::iterator hdf4, const BlockMM_HDF4::iterator & hdf4End, const std::string & window, const MPI_Comm * comm, int rank, int nprocs) static
Definition at line 2035 of file Rocin.C.
References COM_new_attribute(), COM_resize_array(), COM_set_size(), DEBUG_MSG, i, and cimg_library::sin().
Referenced by Rocin::read_windows().
 {
   // Build an MPI message to synchronize variable names.
   std::ostringstream sout;
   std::set<std::string> added;
   while (hdf4 != hdf4End) {
     std::vector<VarInfo_HDF4> &vars = hdf4->second->m_variables;
     std::vector<VarInfo_HDF4>::const_iterator q;
     for (q=vars.begin(); q!=vars.end(); ++q){
       if (added.count((*q).m_name) == 0) {
         sout << (*q).m_name << '!' << (*q).m_position << '!'
              << (*q).m_dataType << '!' << (*q).m_indices.size()
              << '!' << (*q).m_units << '!';
         if ( (*q).m_position=='w')
           sout << (*q).m_nitems << '!' << (*q).m_ng;
         sout << '|';
         added.insert((*q).m_name);
       }
     }
     ++hdf4;
   }
 #ifdef USE_CGNS
   while (cgns != cgnsEnd) {
     std::vector<VarInfo_CGNS> &vars = cgns->second->m_variables;
     std::vector<VarInfo_CGNS>::const_iterator q;
     for (q=vars.begin(); q!=vars.end(); ++q){
       if (added.count((*q).m_name) == 0) {
         sout << (*q).m_name << '!' << (*q).m_position << '!'
              << (*q).m_dataType << '!' << (*q).m_indices.size()
              << '!' << (*q).m_units << '!';
         if ( (*q).m_position=='w')
           sout << (*q).m_nitems << '!' << (*q).m_ng;
         sout << '|';
         added.insert((*q).m_name);
       }
     }
     ++cgns;
   }
 #endif // USE_CGNS
   // Get the lengths of all of the messages.
   std::string msg = sout.str();
   int len = msg.length();
   std::vector<int> lengths(nprocs);
   if ( *comm != MPI_COMM_NULL)
     MPI_Allgather(&len, 1, MPI_INT, &lengths[0], 1, MPI_INT, *comm);
   else
     lengths[0] = len;
   // Compute the total length and displacements for each process's message.
   int globlen = lengths[0];
   std::vector<int> disp(nprocs, 0);
   for (int i=1; i<nprocs; ++i) {
     globlen += lengths[i];
     disp[i] = disp[i-1] + lengths[i-1];
   }
   // Give each process a huge glob with every attribute of every process.
   std::vector<char> buffer(len+1,'\0');
   std::vector<char> glob(globlen+1,'\0');
   std::strcpy( &buffer[0], msg.c_str());
   if ( *comm != MPI_COMM_NULL)
     MPI_Allgatherv(&buffer[0], len, MPI_CHAR, &glob[0], &lengths[0], &disp[0],
                    MPI_CHAR, *comm);
   else
     glob = buffer;
 //std::cout << "glob == \"" << &glob[0] << '"' << std::endl;
   std::string name;
   char buf[256];
   char position;
   COM_Type dType;
   int numComponents;
   char* token = &glob[0];
   added.clear();
   // printf("parsing string: '%s'\n",token);
   while (1) {
     char *nextToken = strchr(token,'|');
     if (nextToken==0) break;
     *nextToken++=0; /* eliminate and advance over separator */
     // printf("parsed token: '%s'\n",token);
     std::istringstream sin(token);
     sin.getline(buf, sizeof(buf), '!');
     if (added.count(buf) == 0) {
       added.insert(buf);
       name = window + '.';
       name += buf;
       position = sin.get(); sin.get();
       sin >> dType; sin.get();
       sin >> numComponents; sin.get();
       sin.getline(buf, sizeof(buf), '!');
       DEBUG_MSG("Calling COM_new_attribute( name == '" << name << "', position == '" << position << "', datatype == " << dType << ", nComp == " << numComponents << ", units == '" << buf << "' )");
       COM_new_attribute(name.c_str(), position, dType, numComponents, buf);
       if ( position == 'w') { // Set size and allocate for window attributes
         int nitems, ng;
         sin >> nitems; sin.get();
         sin >> ng; sin.get();
         DEBUG_MSG("Calling COM_set_size( name == '" << name << "', paneid == 0, nitems == " << nitems << ", nghost == " << ng << " )");
         COM_set_size(name.c_str(), 0, nitems, ng);
         DEBUG_MSG("Calling COM_resize_array( name == '" << name << "', paneid == 0 )");
         COM_resize_array(name.c_str(), 0);
       }
     }
     token = nextToken;
   }
 }
void Rocin_load_module (const char * name)
Load the module Rocin into Roccom using the given module name.
This module provides three subroutines: "read_windows", "read_by_control_file", and "obtain_attribute".
Definition at line 3035 of file Rocin.C.
References Rocin::init().
Referenced by COM_F_FUNC2(), main(), read_pane_sp(), and RFC_Window_base::read_sdv().
 { Rocin::init( std::string(name)); }
void Rocin_unload_module (const char * name)
Unload the module Rocin from Roccom.
Definition at line 3038 of file Rocin.C.
References Rocin::finalize().
Referenced by COM_F_FUNC2(), read_pane_sp(), and RFC_Window_base::read_sdv().
 { Rocin::finalize( std::string(name)); }
static void scan_files_HDF4 (int pathc, char * pathv[], BlockMM_HDF4 & blocks, std::string & time, std::map< int32, COM_Type > & HDF2COM) static
Extract metadata from the list of files.
Open each file, scan the datasets, identify the windows, panes, and attributes.
          istringstream is apparently fragile, so we'll use atoi instead.
      std::istringstream sin2(ghost);
      sin2 >> gc;
Check if there are more data. if (!sin2.eof()) { if (sin2.get() == ',') { ghostPoints = gc; sin2 >> gc; } } if (gc < 0) std::cerr << "Rocstar: Error: Bad num ghosts " << gc << " from string: " << ghost << std::endl; ghostCells.push_back(gc); Check if there are more data. while (!sin2.eof()) { if (sin2.get() == ',') { sin2 >> gc; if (gc < 0) std::cerr << "Rocstar: Error: Bad ghosts " << gc << std::endl; ghostCells.push_back(gc); } }
Definition at line 343 of file Rocin.C.
References COM_assertion_msg, DEBUG_MSG, FindFirstGeometryDataset(), HDF4_CHECK, HDF4_CHECK_RET, i, Block_HDF4::m_gridInfo, VarInfo_HDF4::m_indices, VarInfo_HDF4::m_is_null, VarInfo_HDF4::m_name, Block_HDF4::m_numGhostNodes, Block_HDF4::m_numNodes, Block_HDF4::m_variables, MAX_NC_NAME, offset(), rank, HDF4::SDend(), HDF4::SDendaccess(), HDF4::SDfileinfo(), HDF4::SDgetdatastrs(), HDF4::SDreaddata(), HDF4::SDstart(), HDF4::Select(), cimg_library::sin(), cimg_library::cimg::strcasecmp(), and cimg_library::cimg::strncasecmp().
Referenced by Rocin::read_windows().
 {
   int32 sd_id, geom_id, sds_id, nDataSets, nAttrs, index, index3;
   int32 rank, dType, start[1];
   int32 size[5] = { 0, 0, 0, 0, 0 };
   int32 geomIdx[3];
   char name[MAX_NC_NAME], label[MAX_NC_NAME];
   char timeLevel[MAX_NC_NAME], units[MAX_NC_NAME];
   char matName[MAX_NC_NAME], varName[MAX_NC_NAME], varType[MAX_NC_NAME];
   int xyz;
   int numPoints=0, ghostPoints, gc, gridType=0;
   std::vector<int> ghostCells;
   char grid[32], ghost[32], location;
   std::string geomFile;
   char buffer[1024];
   Block_HDF4* block;
   int i;
   blocks.clear();
   // Iterate through each file.
   for (i=0; i<pathc; ++i) {
     // Make sure this is an HDF file.
     if (strcmp(&pathv[i][strlen(pathv[i])-4], ".hdf") != 0
         && strcmp(&pathv[i][strlen(pathv[i])-5], ".hdf4") != 0)
       continue;
     HDF4_CHECK_RET(sd_id = HDF4::SDstart, (pathv[i], DFACC_READ), continue);
     AutoCloser<int32, intn> auto0(sd_id, HDF4::SDend);
     // Determine the number of datasets.
     HDF4_CHECK_RET(HDF4::SDfileinfo, (sd_id, &nDataSets, &nAttrs),
                    continue);
     // Iterate through the datasets.
     for (index=0; index<nDataSets; ++index) {
       // Select each non-"fakeDim" dataset in the file.
       HDF4_CHECK_RET(sds_id = HDF4::Select,
                      (sd_id, index, name, &rank, size, &dType, &nAttrs, nDataSets),
                      continue);
       {
         AutoCloser<int32, intn> auto1(sds_id, HDF4::SDendaccess);
         // Get the paneId ('label'), time level ('timeLevel'),
         // dataset type ('varName'), and window name ('matName').
         HDF4_CHECK_RET(HDF4::SDgetdatastrs,
                        (sds_id, label, timeLevel, varName, matName, MAX_NC_NAME),
                        continue);
         // If this isn't a block header, then it isn't interesting.
         if (strncasecmp(varName, "block header", 12) != 0) {
           continue;
         } else {
           // Otherwise, set the time level if not yet set, and skip
           // the blocks that have different time levels.
           if (time.empty())
             time = timeLevel;
           else if (time != timeLevel)
             continue;
         }
         // Block header datasets should have only one dimension.
         if (rank != 1) {
           std::cerr << "Rocstar: Warning: Dataset " << index << " in file " << pathv[i]
                     << " is marked as a block header, but its rank is not 1 "
                     << "(rank ==  " << rank << ')' << std::endl;
           continue;
         }
         ghostCells.clear();
         geomFile.erase();
         if (dType == DFNT_CHAR8) {
           // This data file is written for version 1.1.  Good!
           start[0] = 0;
           std::vector<char8> data(size[0]);
           HDF4_CHECK_RET(HDF4::SDreaddata,
                          (sds_id, start, NULL, size, (VOIDP)&data[0]),
                          continue);
           // Parse the data into grid type, ghost info, and external
           // geometry file.
           std::istringstream sin(&data[0]);
           sin.getline(grid, sizeof(grid), '|');
           sin.getline(ghost, sizeof(ghost), '|');
           buffer[0] = '\0';
           sin >> buffer;
           // The first token is the grid type.
           if (strcasecmp(grid, "structured") == 0 || strcmp(grid, "2") == 0) {
             gridType = 2;
           } else if (strcasecmp(grid, "unstructured") == 0
                      || strcmp(grid, "3") == 0) {
             gridType = 3;
           } else if (strcasecmp(grid, "discontinuous") == 0
                      || strcmp(grid, "4") == 0) {
             gridType = 4;
           } else if (strcasecmp(grid, "polydata") == 0
                      || strcmp(grid, "5") == 0) {
             gridType = 5;
           } else {
             std::cerr << "Rocstar: Warning: The block header (dataset " << index
                       << " in file " << pathv[i] << ") does not have a "
                       << "valid grid type (grid = " << grid << ')'
                       << std::endl;
           }
           // The second token is the number of ghost points and cells.  If
           // there is a single number, then this is (probably) the number of
           // layers of ghost cells on a structured grid.  Otherwise, it's the
           // number of ghost points followed by the number of ghost cells of
           // each connectivity table of an unstructured grid.
           // WARNING: When using external grid files, the ghost data will
           // probably not be accurate!
           ghostPoints = 0;
           gc = atoi(ghost);
           char* c = strchr(ghost, ',');
           if (c != NULL) {
             ++c;
             ghostPoints = gc;
             gc = atoi(c);
             c = strchr(c, ',');
           }
           if (gc < 0) std::cerr << "Rocstar: Warning: Bad num ghosts " << gc << " from string: " << ghost << std::endl;
           ghostCells.push_back(gc);
           // Check if there are more data.
           while (c != NULL) {
             ++c;
             gc = atoi(c);
             c = strchr(c, ',');
             if (gc < 0) std::cerr << "Rocstar: Warning: Bad ghosts " << gc << std::endl;
             ghostCells.push_back(gc);
           }
           // The third token (if present) is an external geometry file.
           if (buffer[0] != '\0') {
             if (buffer[0] == '/') {
               geomFile = buffer;
             } else {
               // Normalize the filename.
               geomFile = pathv[i];
               std::string::size_type pos = geomFile.find_last_of('/');
               if (pos != std::string::npos) {
                 geomFile.erase(pos + 1);
                 geomFile += buffer;
                 // If normalized filename does not exist, then
                 // try to find the mesh file with the given name.
                 struct stat sb;
                 if (stat(geomFile.c_str(), &sb) != 0)
                   geomFile = buffer;
               }
               else
                 geomFile = buffer;
             }
             // Make sure the file exists.
             struct stat sb;
             if (stat(geomFile.c_str(), &sb) != 0) {
               std::cerr << "Rocstar: Warning: The block header (dataset " << index
                         << " in file " << pathv[i] << ") has an invalid "
                         << "filename for the external geometry data.  The "
                         << "file does not exist: " << geomFile << std::endl;
               continue;
             }
           }
         } else {
           std::cerr << "Rocstar: Warning: Dataset " << index << " in file " << pathv[i]
                     << " is marked as a block header, but its datatype is "
                     << "not char8." << std::endl;
           continue;
         }
       }
       geom_id = FindFirstGeometryDataset(sd_id, geomFile, matName, label,
                                          index, &index3);
       if (geom_id == FAIL) {
         std::cerr << "Rocstar: Warning: Could not open geometry dataset for section "
                   << label << " of material " << matName << std::endl;
         continue;
       }
       // Collect data on the nodal coordinate datasets.
       for (xyz=0; xyz<6; xyz+=2,++index3) {
         HDF4_CHECK_RET(sds_id = HDF4::Select,
                        (geom_id, index3, name, &rank, size, &dType, &nAttrs),
                        continue);
         AutoCloser<int32, intn> auto2(sds_id, HDF4::SDendaccess);
         geomIdx[xyz/2] = index3;
         if (xyz == 0) {
           units[0] = '\0';
           if ((gridType == 2 && rank != 3) || (gridType != 2 && rank != 1)) {
             numPoints = size[0] = size[1] = size[2] = 0;
             geomIdx[0] = geomIdx[1] = geomIdx[2] = FAIL;
             break;
           }
           HDF4_CHECK(HDF4::SDgetdatastrs,
                      (sds_id, name, units, NULL, varType, MAX_NC_NAME));
           if (gridType == 2) {
             numPoints = size[0] * size[1] * size[2];
           } else {
             char* pos = strchr(name, '|');
             if (pos && *(pos+2)=='0')
               numPoints = ghostPoints = 0; // Empty pane.
             else {
               numPoints = size[0];
               // Get a trustworthy count of the number of ghost nodes.
               std::istringstream in(pos+3);
               in >> ghostPoints;
             }
           }
         }
       }
       // Determine the pane id.  Skip any non-numeric prefix such as "block".
       std::string lbl(label);
       std::string::size_type pos = lbl.find_first_of("0123456789");
       if (pos != std::string::npos)
         lbl.erase(0, pos);
       std::istringstream sin(lbl);
       int paneId;
       sin >> paneId;
       // Create and initialize a Block object.
       block = new Block_HDF4(pathv[i], geomFile, geomIdx, paneId, timeLevel,
                         units, numPoints, ghostPoints);
       // Add grid info.
       if (gridType == 2) {
         // Structured grids only have dimensions.
         block->m_gridInfo.push_back(GridInfo_HDF4(size, ghostCells[0]));
       } else {
         // Get info for each connectivity table.  If we were given ghost
         // cell info, then we know how many connectivity tables we have.
         // Otherwise we have to keep going until we find a dataset that is
         // obviously not a connectivity table.
         std::vector<int>::iterator p;
         for (p=ghostCells.begin();
              ghostCells.empty() || p!=ghostCells.end();
              ++p,++index3) {
           sds_id = HDF4::Select(geom_id, index3, name, &rank, size,
                                 &dType, &nAttrs);
           if (sds_id == FAIL) {
             if (!ghostCells.empty())
               std::cerr << "Rocstar: Warning: Select() failed on connectivity dataset "
                         << index3 << " in file "
                         << (geomFile.empty() ? pathv[i] : geomFile.c_str())
                         << std::endl;
             break;
           }
           AutoCloser<int32, intn> auto3(sds_id, HDF4::SDendaccess);
           // If the rank isn't 2, then it's not a connectivity table.
           if (rank != 2) {
             break;
           }
           // Get metadata on the connectivity table.
           HDF4_CHECK_RET(HDF4::SDgetdatastrs,
                          (sds_id, label, units, varName, varType, MAX_NC_NAME),
                          continue);
           int ghostCount = 0;
           if (!ghostCells.empty())
             ghostCount = *p;
           // A connectivity table must start with ':'
           if (varName[0] != ':') { /* Old, pre-roccom3 dataset */
             /* HIDEOUS HACK: should figure out real element type */
             if (gridType == 3 || gridType == 4) {
               if (size[0] == 4)
                 strcpy(varName,":T4:");
               else if (size[0] == 5)
                 strcpy(varName,":P5:");
               else if (size[0] == 6)
                 strcpy(varName,":P6:");
               else if (size[0] == 8)
                 strcpy(varName,":B8:");
               else if (size[0] == 10)
                 strcpy(varName,":T10:");
               else if (size[0] == 20)
                 strcpy(varName,":B20:");
               else
                 strcpy(varName,":unknown");
             } else if (gridType == 5) {
               if (size[0] == 3)
                 strcpy(varName,":t3:");
               else if (size[0] == 4)
                 strcpy(varName,":q4:");
               else if (size[0] == 6)
                 strcpy(varName,":t6:");
               else if (size[0] == 8)
                 strcpy(varName,":q8:");
               else
                 strcpy(varName,":unknown");
             } else {
               strcpy(varName,":unknown");
             }
             if (1) {
               std::cerr << "Rocstar: Warning: reading old-style connectivity dataset "
                       << varName << " from " << index3 << " in file "
                       << (geomFile.empty() ? pathv[i] : geomFile.c_str())
                       << std::endl;
             }
           } else {
             // If the table is empty, set number of elements to 0.
             char* pos = strchr(label, '|');
             if (pos && *(pos+2)=='0') {
               size[1] = ghostCount = 0;
             } else {
               // Get a trustworthy count of the number of ghost elements.
               std::istringstream in(pos+3);
               in >> ghostCount;
             }
           }
           if (size[1]<0 || ghostCount < 0) {
             std::cerr << "Rocstar: Error: Bad number of element or ghosts for attribute " << varName << " nElem=" << size[1] << " nGhost=" << ghostCount << std::endl;
             COM_assertion_msg(0,
                         "Bad number of element or ghosts for attribute.");
           }
           // Store the mesh info.
           block->m_gridInfo.push_back(GridInfo_HDF4(varName, size[1], ghostCount, index3));
         }
       }
       if (geom_id != sd_id) {
         HDF4::SDend(geom_id);
       } else {
         index = index3;
       }
       // Now search for datasets with variable data.
       for (++index; index<nDataSets; ++index) {
         HDF4_CHECK_RET(sds_id = HDF4::Select,
                        (sd_id, index, name, &rank, size, &dType, &nAttrs, nDataSets),
                        continue);
         AutoCloser<int32, intn> auto4(sds_id, HDF4::SDendaccess);
         // Get metadata on the variable.
         HDF4_CHECK_RET(HDF4::SDgetdatastrs,
                        (sds_id, label, units, varName, varType, MAX_NC_NAME),
                        continue);
         if (varName[0] == '\0' || varName[0] == ':') {
           // Hmm, this is a geometry dataset.
           continue;
         }
         if (strncasecmp(varName, "block header", 12) == 0) {
           // We've found another block header.  We're done.
           // Reverse index by one, as it will be incremented by the outer-loop
           --index;
           break;
         }
         // Determine the location. Format of label is (FIXME: complete?)
         //    "<component letter: 1,2,3,x,y,z>-<attribute>"
         //    "|<location letter: w,p,c,n,e>"
         //    " AT TIME <time SS.MMMUUU> "
         int ng=0; bool is_null=false;
         location = 'w';
         if ( label[0] != ':') {
           char* pos = strchr(label, '|');
           if (pos == NULL) {
             /* Old HDF file without nice labels. For backward compatability,
                guess the data location from the size of the data:
             */
             int sz=size[0]; // Should this be size[rank-1]?
             location='p'; /* guess a panel attribute */
             int num=block->m_numNodes, g=block->m_numGhostNodes;
             if (num==sz) {location='n'; ng=0; /* nodes */ }
             num+=g;
             if (num==sz) {location='n'; ng=g; /* nodes and ghosts */ }
             if (1) {
               num=block->m_gridInfo[0].m_numElements; g=block->m_gridInfo[0].m_numGhostElements;
               if (num==sz) {location='e'; ng=0; /* elements */ }
               num+=g;
               if (num==sz) {location='e'; ng=g; /* elements and ghosts */ }
             }
             if (0) { /* annoying compatability warning */
                std::cerr << "Rocstar: Warning: Compatability warning: guessing variable '"
                       << varName << "' in dataset " << index << " in file "
                       << pathv[i] << " with label " << label
                       << " is of type " << location
                       << "(" << sz << ")" << std::endl;
                /* display size of variable */
                std::cerr << "    size of variable: ";
                for (int i=0;i<rank;i++) std::cerr<<size[i]<<',';
                std::cerr << std::endl;
             }
           }
           else { /* New HDF file: gives location of data directly. */
             location = *(pos + 1);
             // Also obtain the number of ghost items
             if ( *(pos+2) == '0')
               { size[0] = ng = 0; is_null=true; }
             else if ( (*(pos + 2)==',' || *(pos + 2)=='@'))
               { ng = std::atoi( pos+3); is_null=*(pos + 2)=='@'; }
           }
         }
         // Determine which component of the variable we're analyzing.
         std::istringstream str(varType);
         int vType = 0;
         str>> vType;
         int nc = 0;
         switch (vType) {
         case 0:
           // Scalar data.
           nc = 1;
           break;
         case 1:
           // First component of vector data.
           nc = 3;
           break;
         case 11:
           // First component of tensor data.
           nc = 9;
           break;
         case 2: case 3: {
           // Second or third component of vector data.
           VarInfo_HDF4 &vi = block->m_variables.back();
           if (vi.m_name != varName || vi.m_indices.size() != 3) {
             // We shouldn't be seeing 2 or 3 before we see 1.
             std::cerr << "Rocstar: Warning: Found a vector component named " << varName
                       << " for which there is no X component at "
                       << " dataset " << index << " (" << name
                       << ") in file " << pathv[i] << std::endl;
             continue;
           }
           vi.m_indices[vType-1] = index;
           vi.m_is_null[vType-1] = is_null;
           continue;
         }
         case 12: case 13:
         case 21: case 22: case 23:
         case 31: case 32: case 33: {
           // Second, third, etc component of tensor data.
           VarInfo_HDF4 &vi = block->m_variables.back();
           if (vi.m_name != varName || vi.m_indices.size() != 9) {
             // We shouldn't be seeing any of these before we see 11.
             std::cerr << "Rocstar: Warning: Found a tensor component named " << varName
                       << " for which there is no (0,0) component at "
                       << "dataset " << index << " (" << name
                       << ") in file " << pathv[i] << std::endl;
             continue;
           }
           vi.m_indices[3*(vType/10)+(vType%10)-4] = index;
            vi.m_is_null[3*(vType/10)+(vType%10)-4] = is_null;
           continue;
         }
         default:
           // I don't know what kind of variable this is supposed to be.
           // Assuming scalar.
           vType = 0;
           nc = 1;
           break;
         }
         int offset = 0; // Starting point for actual attribute name.
         if ( varName[0]>='0' && varName[0]<='9') {
           if ( std::strncmp( varName, "1-", 2)==0)
             offset = 2; // Skip the "1-" part
           else { // Append to the back
             VarInfo_HDF4 &vi = block->m_variables.back();
             unsigned int id = std::atoi( varName);
             const char *aName = std::strchr(varName, '-');
             if ( aName==NULL || vi.m_name != (aName+1) ||
                  vi.m_indices.size() != id-1) {
               // The individual components must be stored consecutively
               std::cerr << "Rocstar: Warning: Found a vector named " << vi.m_name
                         << " whose components are not stored together "
                         << " in file " << pathv[i] << std::endl;
               continue;
             }
             vi.m_indices.push_back( index);
             vi.m_is_null.push_back( is_null);
             DEBUG_MSG("Correction: variable '" << vi.m_name << "' actually has "
                       << vi.m_indices.size() << " components.");
             continue;
           }
         }
         DEBUG_MSG("Found variable '" << &varName[offset] << "', location == '"
                   << location << "', nComp == " << nc << ", nItems == "
                   << size[0] << ", nGhost == " << ng << ", isNull == "
                   << is_null);
         block->m_variables.push_back
           (VarInfo_HDF4(&varName[offset], location, HDF2COM[dType],
                    units, nc, index, size[0], ng, is_null));
       }
       blocks.insert(BlockMM_HDF4::value_type(matName, block));
     }
   }
 }