Rocstar: Rocin.h File Reference
Rocin.h File Reference
Rocin creates a series of Roccom windows by reading in a list of files.
#include "roccom.h"
#include "HDF4.h"
#include "rocin_block.h"
#include "roccom_devel.h"
Classes
class Rocin
Functions
Module loading and unloading
void Rocin_load_module (const char *name)
Load the module Rocin into Roccom using the given module name.
void Rocin_unload_module (const char *name)
Unload the module Rocin from Roccom.
Detailed Description
Rocin creates a series of Roccom windows by reading in a list of files.
Rocin can also copy Roccom attributes from window to window. Only HDF4 files are supported in the current implementation.
Definition in file Rocin.h.
Function Documentation
void Rocin_load_module (const char * name)
Load the module Rocin into Roccom using the given module name.
This module provides three subroutines: "read_windows", "read_by_control_file", and "obtain_attribute".
Definition at line 3035 of file Rocin.C.
Referenced by COM_F_FUNC2(), main(), read_pane_sp(), and RFC_Window_base::read_sdv().
 { Rocin::init( std::string(name)); }
void Rocin_unload_module (const char * name)
Unload the module Rocin from Roccom.
Definition at line 3038 of file Rocin.C.
Referenced by COM_F_FUNC2(), read_pane_sp(), and RFC_Window_base::read_sdv().
 { Rocin::finalize( std::string(name)); }