Rocstar: Rocmop_1.C File Reference
Rocmop_1.C File Reference
#include "Rocblas.h"
#include "Rocmop_1.h"
#include "Rocmap.h"
#include "roccom.h"
#include "Pane_communicator.h"
#include "Pane_connectivity.h"
#include "Geometric_Metrics_3.h"
#include "PN_patch.h"
#include "geometry.h"
#include "mapbasic.h"
#include <iostream>
#include <iomanip>
#include <fstream>
Macros
#define NO_STRINGSTREAM 1
Functions
std::ifstream & get_next_line (std::ifstream &Inf, std::string &line, const char noop)
void Rocmop_load_module (const char *mname)
void Rocmop_unload_module (const char *mname)
void COM_F_FUNC2 (rocmop_load_module, ROCMOP_LOAD_MODULE) const
void COM_F_FUNC2 (rocmop_unload_module, ROCMOP_UNLOAD_MODULE) const
Macro Definition Documentation
#define NO_STRINGSTREAM 1
Definition at line 69 of file Rocmop_1.C.
Function Documentation
void COM_F_FUNC2 (rocmop_load_module , ROCMOP_LOAD_MODULE) const
Definition at line 1886 of file Rocmop_1.C.
References Mesquite::length(), and Rocmop::load().
 { Rocmop::load( std::string(mname, length)); }
void COM_F_FUNC2 (rocmop_unload_module , ROCMOP_UNLOAD_MODULE) const
Definition at line 1889 of file Rocmop_1.C.
References Mesquite::length(), and Rocmop::unload().
 { Rocmop::unload( std::string(mname, length)); }
std::ifstream& get_next_line (std::ifstream & Inf, std::string & line, const char noop)
Definition at line 106 of file Rocmop_1.C.
Referenced by Rocmop::read_config_file().
 {
   if(!Inf)
     return(Inf);
   std::getline(Inf,line);
   while((line.empty() || line[0] == ' ' || line[0] == noop) && Inf)
     std::getline(Inf,line);
   return(Inf);
 }
void Rocmop_load_module (const char * mname)
Definition at line 1879 of file Rocmop_1.C.
References Rocmop::load().
 { Rocmop::load( mname); }
void Rocmop_unload_module (const char * mname)
Definition at line 1882 of file Rocmop_1.C.
References Rocmop::unload().
 { Rocmop::unload( mname); }