Rocstar: Rocmap.C File Reference
Rocmap.C File Reference
#include "Rocmap.h"
#include "roccom.h"
#include "Pane_connectivity.h"
#include "Pane_communicator.h"
#include "Pane_boundary.h"
Functions
void Rocmap_load_module (const char *mname)
void Rocmap_unload_module (const char *mname)
void rocmap_load_module (const char *mname, long int length)
void rocmap_unload_module (const char *mname, long int length)
void ROCMAP_LOAD_MODULE (const char *mname, long int length)
void ROCMAP_UNLOAD_MODULE (const char *mname, long int length)
void rocmap_load_module_ (const char *mname, long int length)
void rocmap_unload_module_ (const char *mname, long int length)
void ROCMAP_LOAD_MODULE_ (const char *mname, long int length)
void ROCMAP_UNLOAD_MODULE_ (const char *mname, long int length)
Function Documentation
void Rocmap_load_module (const char * mname)
Definition at line 140 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( mname); }
void rocmap_load_module (const char * mname, long int length)
Definition at line 148 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( std::string(mname, length)); }
void ROCMAP_LOAD_MODULE (const char * mname, long int length)
Definition at line 154 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( std::string(mname, length)); }
void rocmap_load_module_ (const char * mname, long int length)
Definition at line 160 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( std::string(mname, length)); }
void ROCMAP_LOAD_MODULE_ (const char * mname, long int length)
Definition at line 166 of file Rocmap.C.
References Rocmap::load().
 { Rocmap::load( std::string(mname, length)); }
void Rocmap_unload_module (const char * mname)
Definition at line 143 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( mname); }
void rocmap_unload_module (const char * mname, long int length)
Definition at line 151 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( std::string(mname, length)); }
void ROCMAP_UNLOAD_MODULE (const char * mname, long int length)
Definition at line 157 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( std::string(mname, length)); }
void rocmap_unload_module_ (const char * mname, long int length)
Definition at line 163 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( std::string(mname, length)); }
void ROCMAP_UNLOAD_MODULE_ (const char * mname, long int length)
Definition at line 169 of file Rocmap.C.
References Rocmap::unload().
 { Rocmap::unload( std::string(mname, length)); }