Rocstar: Rocmop.C File Reference
Rocmop.C File Reference
#include "Rocblas.h"
#include "Rocmop.h"
#include "Rocmap.h"
#include "roccom.h"
#include "Pane_communicator.h"
#include "Pane_connectivity.h"
#include "Geometric_Metrics_3.h"
#include "PN_patch.h"
#include "geometry.h"
#include "mapbasic.h"
#include <iostream>
#include <iomanip>
#include <fstream>
Functions
void Rocmop_load_module (const char *mname)
void Rocmop_unload_module (const char *mname)
void COM_F_FUNC2 (rocmop_load_module, ROCMOP_LOAD_MODULE) const
void COM_F_FUNC2 (rocmop_unload_module, ROCMOP_UNLOAD_MODULE) const
Function Documentation
void COM_F_FUNC2 (rocmop_load_module , ROCMOP_LOAD_MODULE) const
Definition at line 957 of file Rocmop.C.
References Mesquite::length(), and Rocmop::load().
 { Rocmop::load( std::string(mname, length)); }
void COM_F_FUNC2 (rocmop_unload_module , ROCMOP_UNLOAD_MODULE) const
Definition at line 960 of file Rocmop.C.
References Mesquite::length(), and Rocmop::unload().
 { Rocmop::unload( std::string(mname, length)); }
void Rocmop_load_module (const char * mname)
Definition at line 950 of file Rocmop.C.
References Rocmop::load().
 { Rocmop::load( mname); }
void Rocmop_unload_module (const char * mname)
Definition at line 953 of file Rocmop.C.
References Rocmop::unload().
 { Rocmop::unload( mname); }