Rocstar: Rocon.C File Reference
Rocon.C File Reference
#include <string>
#include <cmath>
#include <iostream>
#include <sstream>
#include "Rocon.H"
#include "TRAIL.H"
#include "Parameters.H"
Functions
COM_EXTERN_MODULE (Rocin)
void CheckCoordinates (double *coords, int number_of_points, double tol)
void TransformCoordinates (double *coords, int number_of_points, double xfac, double yfac, double zfac)
void Rocon_load_module (const char *name)
void Rocon_unload_module (const char *name)
void rocon_load_module (const char *name, long int length)
void rocon_unload_module (const char *name, long int length)
void ROCON_LOAD_MODULE (const char *name, long int length)
void ROCON_UNLOAD_MODULE (const char *name, long int length)
void rocon_load_module_ (const char *name, long int length)
void rocon_unload_module_ (const char *name, long int length)
void ROCON_LOAD_MODULE_ (const char *name, long int length)
void ROCON_UNLOAD_MODULE_ (const char *name, long int length)
Function Documentation
void CheckCoordinates (double * coords, int number_of_points, double tol)
Definition at line 74 of file Rocon.C.
References i.
Referenced by Rocon::find_intersections(), Rocon::initialize(), and main().
 {
   for(int i = 0; i < number_of_points*3;i++)
     {
       if(std::fabs(coords[i]) < tol && (coords[i] != 0.0)){
         //      std::cout << "Rocon> WARNING: node " << (i/3)+1 << "/"
         //                << number_of_points << " "
         //        << (((i%3)==0 ? "x " : ((i%3) < 2) ? "y " : "z "))
         //                << "coordinate = " << coords[i] << std::endl;
         coords[i] = 0.0;
       }
     }
 }
COM_EXTERN_MODULE (Rocin)
void Rocon_load_module (const char * name)
Definition at line 869 of file Rocon.C.
References Rocon::load().
 { Rocon::load( std::string(name)); }
void rocon_load_module (const char * name, long int length)
Definition at line 875 of file Rocon.C.
References Rocon::load().
 { Rocon::load( std::string(name, length)); }
void ROCON_LOAD_MODULE (const char * name, long int length)
Definition at line 880 of file Rocon.C.
References Rocon::load().
 { Rocon::load( std::string(name, length)); }
void rocon_load_module_ (const char * name, long int length)
Definition at line 885 of file Rocon.C.
References Rocon::load().
 { Rocon::load( std::string(name, length)); }
void ROCON_LOAD_MODULE_ (const char * name, long int length)
Definition at line 890 of file Rocon.C.
References Rocon::load().
 { Rocon::load( std::string(name, length)); }
void Rocon_unload_module (const char * name)
Definition at line 871 of file Rocon.C.
References Rocon::unload().
 { Rocon::unload( std::string(name)); }
void rocon_unload_module (const char * name, long int length)
Definition at line 877 of file Rocon.C.
References Rocon::unload().
 { Rocon::unload( std::string(name, length)); }
void ROCON_UNLOAD_MODULE (const char * name, long int length)
Definition at line 882 of file Rocon.C.
References Rocon::unload().
 { Rocon::unload( std::string(name, length)); }
void rocon_unload_module_ (const char * name, long int length)
Definition at line 887 of file Rocon.C.
References Rocon::unload().
 { Rocon::unload( std::string(name, length)); }
void ROCON_UNLOAD_MODULE_ (const char * name, long int length)
Definition at line 892 of file Rocon.C.
References Rocon::unload().
 { Rocon::unload( std::string(name, length)); }
void TransformCoordinates (double * coords, int number_of_points, double xfac, double yfac, double zfac)
Definition at line 87 of file Rocon.C.
References i.
Referenced by Rocon::initialize().
 {
   for(int i = 0; i < number_of_points;i++)
     {
       coords[i*3] *= xfac;
       coords[i*3 + 1] *= yfac;
       coords[i*3 + 2] *= zfac;
     }
 }