Rocstar: Rocout.C File Reference
Rocout.C File Reference
Implementation of Rocout for creation of a data file from a Roccom window.
#include <sys/stat.h>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <algorithm>
#include <errno.h>
#include "Rocout.h"
#include "Rocout_hdf4.h"
Classes
struct WriteAttrInfo
Pass write_attribute arguments to the background worker thread.
Macros
#define SwitchOnDataType(dType, funcCall)
#define ERROR_MSG(msg)
Functions
static bool is_option_name (const std::string &name)
Return true if the given string is the name of a Rocout option.
static bool is_whole (const std::string &s)
static bool is_option_value (const std::string &name, const std::string &val)
Return true if the given Rocout option name/value pair is valid.
void Rocout_load_module (const char *name)
Load the module Rocout into Roccom using the given module name.
void Rocout_unload_module (const char *name)
Unload the module Rocout from Roccom.
void COM_F_FUNC2 (rocout_load_module, ROCOUT_LOAD_MODULE) const
void COM_F_FUNC2 (rocout_unload_module, ROCOUT_UNLOAD_MODULE) const
Variables
static USE_COM_NAME_SPACE const int MAX_ASYNC_WRITES = 10
Detailed Description
Implementation of Rocout for creation of a data file from a Roccom window.
Definition in file Rocout.C.
Macro Definition Documentation
#define ERROR_MSG (msg)
Value:
{ if (_options["errorhandle"] != "ignore") { \
    std::cerr << msg << std::endl; \
    if (_options["errorhandle"] == "abort") { \
      if (COMMPI_Initialized()) \
        MPI_Abort(MPI_COMM_WORLD, 0); \
      else \
        abort(); \
    } \
  } \
}
Definition at line 123 of file Rocout.C.
Referenced by Rocout::get_fname(), Rocout::read_control_file(), and Rocout::set_option().
#define SwitchOnDataType (dType, funcCall)
Definition at line 74 of file Rocout.C.
Function Documentation
void COM_F_FUNC2 (rocout_load_module , ROCOUT_LOAD_MODULE) const
Definition at line 882 of file Rocout.C.
References Mesquite::length(), and Rocout_load_module().
 { Rocout_load_module( std::string(name, length).c_str()); }
void COM_F_FUNC2 (rocout_unload_module , ROCOUT_UNLOAD_MODULE) const
Definition at line 884 of file Rocout.C.
References Mesquite::length(), and Rocout_unload_module().
 { Rocout_unload_module( std::string(name, length).c_str()); }
static bool is_option_name (const std::string & name) static
Return true if the given string is the name of a Rocout option.
Definition at line 497 of file Rocout.C.
Referenced by Rocout::read_control_file(), and Rocout::set_option().
 {
   return (name == "format" || name == "async" || name == "mode"
           || name == "localdir" || name == "rankwidth" || name == "pnidwidth"
           || name == "separator" || name == "errorhandle" || name == "rankdir"
           || name == "ghosthandle");
 }
static bool is_option_value (const std::string & name, const std::string & val) static
Return true if the given Rocout option name/value pair is valid.
Definition at line 519 of file Rocout.C.
References is_whole().
Referenced by Rocout::read_control_file(), and Rocout::set_option().
 {
   return ((name == "format"
            && (val == "HDF" || val == "HDF4" || val == "HDF5" || val == "CGNS"))
           || (name == "async"
               && (val == "on" || val == "off"))
           || (name == "mode"
               && (val == "w" || val == "a"))
           || (name == "localdir" /* && is_valid_path(val) */ )
           || ((name == "rankwidth" || name == "pnidwidth") && is_whole(val))
           || (name == "rankdir"
               && (val == "on" || val == "off"))
           || (name == "errorhandle"
               && (val == "abort" || val == "ignore" || val == "warn"))
           || (name == "ghosthandle"
               && (val == "write" || val == "ignore")));
 }
static bool is_whole (const std::string & s) static
Definition at line 506 of file Rocout.C.
References i, and cimg_library::sin().
Referenced by is_option_value().
 {
   if (s.empty())
     return false;
   std::istringstream sin(s);
   int i = 0;
   sin >> i;
   return (i >= 0 && sin.eof());
 }
void Rocout_load_module (const char * name)
Load the module Rocout into Roccom using the given module name.
This module provides one subroutine: "write_attribute".
Definition at line 873 of file Rocout.C.
References Rocout::init().
Referenced by COM_F_FUNC2(), main(), and RFC_Window_base::write_sdv().
 { Rocout::init( std::string(name)); }
void Rocout_unload_module (const char * name)
Unload the module Rocout from Roccom.
Definition at line 876 of file Rocout.C.
References Rocout::finalize().
Referenced by COM_F_FUNC2(), and RFC_Window_base::write_sdv().
 { Rocout::finalize( std::string(name)); }
Variable Documentation
USE_COM_NAME_SPACE const int MAX_ASYNC_WRITES = 10 static
Definition at line 49 of file Rocout.C.