Rocstar: Rocout_cgns.h File Reference
Rocout_cgns.h File Reference
Declaration of Rocout CGNS routines.
#include "roccom.h"
#include <string>
Functions
void write_attr_CGNS (const std::string &fname, const std::string &mfile, const COM::Attribute *attr, const char *material, const char *timelevel, int pane_id, const std::string &ghosthandle, const std::string &errorhandle, int mode)
Write the data for the given attribute to file.
Detailed Description
Declaration of Rocout CGNS routines.
Definition in file Rocout_cgns.h.
Function Documentation
void write_attr_CGNS (const std::string & fname_in, const std::string & mfile, const COM::Attribute * attr, const char * material, const char * timelevel, int pane_id, const std::string & ghosthandle, const std::string & errorhandle, int mode)
Write the data for the given attribute to file.
Write the given attribute to file using the CGNS format. The attribute may be a "mesh", "all" or some other predefined attribute.
Parameters
fname The name of the main datafile. (Input)
mname The name of the optional mesh datafile. (Input)
attr The attribute to write out. (Input)
material The name of the material. (Input)
timelevel The simulation time for this data. (Input)
pane_id The id for the local pane. (Input)
ghosthandle "ignore" or "write" on ghost data.
errorhandle "ignore", "warn", or "abort" on errors.
mode Write == 0, append == 1. (Input)
Write the given attribute to file using the CGNS format. The attribute may be a "mesh", "all" or some other predefined attribute.
Parameters
fname The name of the main datafile. (Input)
mname The name of the optional mesh datafile. (Input)
attr The attribute to write out. (Input)
material The name of the material. (Input)
timelevel The simulation time for this data. (Input)
pane_id The id for the local pane. (Input)
mode Write == 0, append == 1. (Input)
Definition at line 874 of file Rocout_cgns.C.
References A, Pane::attribute(), Pane::attributes(), Connectivity::BAR2, cg_array_core_write(), cg_array_info_by_name(), cg_base_find_or_create(), CG_CHECK, cg_exponents_as_string_write(), cg_integral_find_or_create(), cg_sol_find_or_create(), cg_zone_find_or_create(), COM2CGNS(), COM_ALL, COM_assertion, COM_assertion_msg, COM_ATTS, COM_CONN, COM_MESH, COM_NC, COM_NC1, COM_NC3, COM_PCONN, COM_PMESH, COM_RIDGES, Attribute::data_type(), DEBUG_MSG, Pane::dimension(), Pane::elements(), FindMagnitudeRange(), FindRange(), FindTraceRange(), get_sizeof(), i, Pane::id(), Attribute::id(), Pane::is_structured(), Pane::is_unstructured(), j, Attribute::location(), max(), min(), offset(), Window::pane(), Attribute::pointer(), rank, cimg_library::sin(), Pane::size_i(), Pane::size_j(), Pane::size_k(), Attribute::size_of_components(), Attribute::size_of_ghost_items(), Pane::size_of_ghost_layers(), Pane::size_of_ghost_nodes(), Attribute::size_of_items(), Pane::size_of_nodes(), Pane::size_of_real_elements(), Attribute::size_of_real_items(), Pane::size_of_real_nodes(), Attribute::stride(), SwitchOnCOMDataType, Attribute::unit(), and WriteElements().
Referenced by Rocout::write_attr_internal().
 {
   std::string fname(fname_in);
   bool writeGhost = (ghosthandle == "write");
   const Window* w = attr->window();
   COM_assertion(w != NULL);
   const Pane& pane = w->pane(pane_id);
   // Convert the timelevel from a string to a number.
   double timeValue;
   {
     std::istringstream sin(timelevel);
     sin >> timeValue;
   }
   // Covert the timeValue back to a string.  This "normalizes" the string.
   std::string timeLevel;
   {
     std::ostringstream sout;
     sout << timeValue;
     timeLevel = sout.str();
   }
   DEBUG_MSG("Writing to file '" << fname << "', mode == '"
             << (mode ? "append'" : "write'"));
   DEBUG_MSG("Using mesh file '" << mfile << "'");
   AutoCDer autoCD;
   std::string::size_type loc = fname.rfind('/');
   if (loc != std::string::npos) {
     chdir(fname.substr(0, loc).c_str());
     fname.erase(0, loc + 1);
   }
   // Open or create the file.
   int fn;
   if (mode == 0) {
     CG_CHECK(cg_open, (fname.c_str(), MODE_WRITE, &fn));
     CG_CHECK(cg_close, (fn));
   }
   CG_CHECK(cg_open, (fname.c_str(), MODE_MODIFY, &fn));
   // The file will be closed automagically when we exit this function.
   AutoCloser autoCloser(fn, errorhandle);
   // Find or create the base (corresponds to window/material).
   int i, B, nSteps = 0;
   std::vector<double> times;
   char buffer[33];
   std::string label;
   int cellDim = pane.dimension();
   int physDim = pane.attribute(COM::COM_NC)->size_of_components();
   CG_CHECK(cg_base_find_or_create, (fn, material, cellDim, physDim, &B,
                                     errorhandle));
   // Write the default Roccom units at the top.
   CG_CHECK(cg_goto, (fn, B, "end"));
   CG_CHECK(cg_units_write, (Kilogram, Meter, Second, Kelvin, Degree));
   // Read the time values in the BaseIterativeData_t node.
   if (mode > 0 && cg_biter_read(fn, B, buffer, &nSteps) == 0) {
     CG_CHECK(cg_goto, (fn, B, "BaseIterativeData_t", 1, "end"));
     times.resize(nSteps + 1);
     CG_CHECK(cg_array_read_as, (1, RealDouble, &(times[0])));
   } else {
     times.resize(1);
   }
   // Search for the current time.
   int timeIndex;
   for (timeIndex=0; timeIndex<nSteps; ++timeIndex)
     if (times[timeIndex] == timeValue)
       break;
   // Update the time values in the BaseIterativeData_t node if necessary.
   if (timeIndex == nSteps) {
     times[timeIndex] = timeValue;
     ++nSteps;
     // Write/rewrite the time values to the BaseIterativeData_t node.
     CG_CHECK(cg_biter_write, (fn, B, "TimeIterValues", nSteps));
     CG_CHECK(cg_goto, (fn, B, "BaseIterativeData_t", 1, "end"));
     CG_CHECK(cg_array_write, ("TimeValues", RealDouble, 1, &nSteps,
                               &(times[0])));
     --nSteps;
   }
   // Find or create the zone (corresponds to pane/section).  Use the pane
   // id as the zone name.
   std::string zoneName;
   {
     std::ostringstream sout;
     sout << std::setw(4) << std::setfill('0') << pane.id();
     zoneName = sout.str();
   }
   // Set up the sizes based on dimensionality and zone type.
   int Z, sizes[9] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
   ZoneType_t zType;
   i = 0;
   if (pane.is_structured()) {
     // Sizes should be core nodes/elements only.
     int ghost = pane.size_of_ghost_layers();
     sizes[i++] = pane.size_i() - 2 * ghost;
     sizes[i++] = pane.size_j() - 2 * ghost;
     if (physDim > 2 && cellDim > 2)
       sizes[i++] = pane.size_k() - 2 * ghost;
     sizes[i++] = sizes[0] - 1;
     sizes[i++] = sizes[1] - 1;
     if (physDim > 2 && cellDim > 2)
       sizes[i++] = sizes[2] - 1;
     zType = Structured;
   } else {
     sizes[0] = pane.size_of_real_nodes();
     sizes[1] = pane.size_of_real_elements();
     zType = Unstructured;
   }
   CG_CHECK(cg_zone_find_or_create, (fn, B, zoneName.c_str(), sizes,
                                     zType, &Z, errorhandle));
   // Create the name for the GridCoordinates_t node.
   std::string gridName("Grid");
   if (timeLevel.length() + gridName.length() > 32)
     gridName.erase(32 - timeLevel.length());
   gridName += timeLevel;
   // Create the name for the IntegralData_t node for window attributes.
   std::string winName("WinData");
   if (timeLevel.length() + winName.length() > 32)
     winName.erase(32 - timeLevel.length());
   winName += timeLevel;
   // Create the name for the IntegralData_t node for pane attributes.
   std::string paneName("PaneData");
   if (timeLevel.length() + paneName.length() > 32)
     paneName.erase(32 - timeLevel.length());
   paneName += timeLevel;
   // Create the name for the IntegralData_t node for conn attributes.
   std::string connName("ConnData");
   if (timeLevel.length() + connName.length() > 32)
     connName.erase(32 - timeLevel.length());
   connName += timeLevel;
   // Create the name for the FlowSolution_t node for element attributes.
   std::string elemName("ElemData");
   if (timeLevel.length() + elemName.length() > 32)
     elemName.erase(32 - timeLevel.length());
   elemName += timeLevel;
   // Create the name for the FlowSolution_t node for node attributes.
   std::string nodeName("NodeData");
   if (timeLevel.length() + nodeName.length() > 32)
     nodeName.erase(32 - timeLevel.length());
   nodeName += timeLevel;
   // Read and update the grid coordinate and solution names in the
   // ZoneIterativeData_t node.
   char (*gridNames)[32] = NULL;
   char (*nodeNames)[32] = NULL;
   int rank, size[3];
   if (mode > 0 && cg_ziter_read(fn, B, Z, buffer) == 0) {
     CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "ZoneIterativeData_t", 1, "end"));
     int numStr = nSteps;
     if (timeIndex >= nSteps)
       ++numStr;
     gridNames = (char(*)[32])new char[32*numStr];
     std::fill_n((char*)gridNames, 32 * numStr, '\0');
     nodeNames = (char(*)[32])new char[32*numStr];
     std::fill_n((char*)nodeNames, 32 * numStr, '\0');
     int A;
     DataType_t dataType;
     // Add the grid coordinates name to the GridCoordinatesPointers array,
     // unless it's already there.
     CG_CHECK(cg_array_info_by_name,
              ("GridCoordinatesPointers", &A, &dataType, &rank, size,
                errorhandle));
     COM_assertion_msg((dataType == Character && rank == 2
                        && size[1] == numStr),
                     "GridCoordinatesPointers in ZoneIterativeData is corrupt");
     CG_CHECK(cg_array_read, (A, gridNames));
     if (timeIndex < nSteps) {
       COM_assertion_msg(gridName == gridNames[timeIndex],
                     "GridCoordinatesPointers in ZoneIterativeData is corrupt");
     } else {
       std::strncpy(gridNames[timeIndex], gridName.c_str(), 32);
     }
     // Add the flow solutions name to the FlowSolutionsPointers array,
     // unless it's already there.
     CG_CHECK(cg_array_info_by_name,
              ("FlowSolutionsPointers", &A, &dataType, &rank, size,
               errorhandle));
     COM_assertion_msg((dataType == Character && rank == 2
                        && size[1] == numStr),
                       "FlowSolutionsPointers in ZoneIterativeData is corrupt");
     CG_CHECK(cg_array_read, (A, nodeNames));
     if (timeIndex < nSteps) {
       COM_assertion_msg(nodeName == nodeNames[timeIndex],
                       "FlowSolutionsPointers in ZoneIterativeData is corrupt");
     } else {
       std::strncpy(nodeNames[timeIndex], nodeName.c_str(), 32);
     }
   } else {
     cg_ziter_write(fn, B, Z, "ZoneIterativeData");
     gridNames = (char(*)[32])new char[32];
     std::fill_n((char*)gridNames, 32, '\0');
     std::strncpy(gridNames[timeIndex], gridName.c_str(), 32);
     nodeNames = (char(*)[32])new char[32];
     std::fill_n((char*)nodeNames, 32, '\0');
     std::strncpy(nodeNames[timeIndex], nodeName.c_str(), 32);
   }
   if (timeIndex == nSteps) {
     size[0] = 32;
     size[1] = ++nSteps;
     // Write/rewrite the grid coordinate and solution names in the
     // ZoneIterativeData_t node.
     CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "ZoneIterativeData_t", 1, "end"));
     CG_CHECK(cg_array_write,
              ("GridCoordinatesPointers", Character, 2, size, gridNames));
     CG_CHECK(cg_array_write,
              ("FlowSolutionsPointers", Character, 2, size, nodeNames));
   }
   delete[] (char*)gridNames;
   delete[] (char*)nodeNames;
   std::vector<char> buf;
   int mfn = fn, mB = B, mZ = Z, nGC = 0, G = 0, numItems, dType;
   int rind[6] = { 0, 0, 0, 0, 0, 0 };
   // Build a CGNS path to the current zone.
   std::string path("/"), range;
   path += material;
   path += '/' + zoneName + '/';
   // Write the grid coordinates and the connectivity tables, if any.
   if (attr->id() == COM::COM_MESH || attr->id() == COM::COM_PMESH
       || attr->id() == COM::COM_CONN
       || (attr->id() >= COM::COM_NC1 && attr->id() <= COM::COM_NC3)
       || attr->id() == COM::COM_NC || attr->id() == COM::COM_ALL) {
     // Find or create the grid coordinates and element tables.  If they're in a
     // different file, then we should create links from the main file to the
     // mesh file nodes.
     if (!mfile.empty()) {
       DEBUG_MSG("Writing to mesh file '" << mfile << "', mode == '"
                 << (mode ? "append'" : "write'"));
       CG_CHECK(cg_open,
                (mfile.c_str(), mode ? MODE_MODIFY : MODE_WRITE, &mfn));
       CG_CHECK(cg_base_find_or_create, (mfn, material, cellDim, physDim, &mB,
                                         errorhandle));
       CG_CHECK(cg_zone_find_or_create, (mfn, mB, zoneName.c_str(),
                                         sizes, zType, &mZ, errorhandle));
     }
     // The GridCoordinates node is referenced by the GridCoordinatesPointers,
     // so we should create it even if we don't put any data in it.
     // The first grid written must always be names "GridCoordinates".
     // Since we are naming our data based on timeLevel, we'll need to use
     // a link for the first one.
     CG_CHECK(cg_ngrids, (mfn, mB, mZ, &nGC));
     if (nGC == 0) {
       CG_CHECK(cg_grid_write, (mfn, mB, mZ, "GridCoordinates", &G));
       if (mfile.empty()) {
         CG_CHECK(cg_goto, (mfn, mB, "Zone_t", mZ, "end"));
         CG_CHECK(cg_link_write, (gridName.c_str(), "",
                                  (path + "GridCoordinates").c_str()));
       } else {
         // Create links from the data file to the mesh file.
         CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "end"));
         CG_CHECK(cg_ngrids, (fn, B, Z, &nGC));
         if (nGC == 0) {
           CG_CHECK(cg_link_write, ("GridCoordinates", mfile.c_str(),
                                    (path + "GridCoordinates").c_str()));
         }
         CG_CHECK(cg_link_write, (gridName.c_str(), mfile.c_str(),
                                  (path + "GridCoordinates").c_str()));
       }
     } else {
       if (mfile.empty()) {
         CG_CHECK(cg_grid_write, (mfn, mB, mZ, gridName.c_str(), &G));
       } else {
         // Create links from the data file to the mesh file.
         CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "end"));
         CG_CHECK(cg_ngrids, (fn, B, Z, &nGC));
         if (nGC == 0) {
           CG_CHECK(cg_link_write, ("GridCoordinates", mfile.c_str(),
                                    (path + "GridCoordinates").c_str()));
         }
         CG_CHECK(cg_link_write, (gridName.c_str(), mfile.c_str(),
                                  (path + "GridCoordinates").c_str()));
       }
     }
     if (attr->id() == COM::COM_MESH || attr->id() == COM::COM_PMESH
         || attr->id() == COM::COM_NC || attr->id() == COM::COM_ALL
         || (attr->id() >= COM::COM_NC1 && attr->id() <= COM::COM_NC3)) {
       // Write the actual mesh data.
       if (G > 0) {
         CG_CHECK(cg_goto, (mfn, mB, "Zone_t", mZ, "GridCoordinates_t", G,
                            "end"));
         if (pane.is_structured()) {
           rank = cellDim;
           size[0] = pane.size_i();
           size[1] = pane.size_j();
           size[2] = (physDim == 3 && cellDim == 3 ? pane.size_k(): 1);
           numItems = size[0] * size[1] * size[2];
           std::fill_n(rind, 2 * physDim, pane.size_of_ghost_layers());
         } else {
           rank = 1;
           size[0] = numItems = pane.size_of_nodes();
           std::fill_n(rind, 6, 0);
           rind[1] = pane.size_of_ghost_nodes();
         }
         // Write rind data.
         if (writeGhost)
           CG_CHECK(cg_rind_write, (rind));
         // std::string ranges[physDim];
         std::string ranges[3];
         int n, start = 0, finish = physDim;
         if (attr->id() >= COM::COM_NC1 && attr->id() <= COM::COM_NC3) {
           start = attr->id() - COM::COM_NC1;
           finish = start + 1;
         }
         for (n=start; n<finish; ++n) {
           const Attribute* nc = pane.attribute(COM::COM_NC1 + n);
           dType = nc->data_type();
           // Check for null/empty/strided data.
           const void* pData = nc->pointer();
           bool isNull = false;
           if (numItems <= 0) {
             buf.resize(COM::Attribute::get_sizeof(dType, 1), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData = &(buf[0]);
             size[0] = size[1] = size[2] = 1;
             ranges[n] = "EMPTY";
           } else if (pData == NULL) {
             buf.resize(COM::Attribute::get_sizeof(dType,
                                                   std::max(numItems, 1)), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData = &(buf[0]);
             // size[0] = size[1] = size[2] = 1;
             isNull = true;
             ranges[n] = "NULL";
           } else {
             int stride = nc->stride();
             if (stride > 1) {
               int dSize = COM::Attribute::get_sizeof(dType, 1);
               buf.resize(dSize * std::max(numItems, 1));
               for (i=0; i<numItems; ++i)
                 std::memcpy(&(buf[i*dSize]),
                             &(((const char*)pData)[i*stride*dSize]), dSize);
               pData = &(buf[0]);
             }
 #ifdef DEBUG_DUMP_PREFIX
             {
               std::ofstream fout((DEBUG_DUMP_PREFIX + std::string(material) + ".nc" + '_' + timeLevel + ".cgns").c_str(), std::ios_base::app);
               switch (COM2CGNS(dType)) {
                 case Character:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << (int)((const char*)pData)[i]
                          << '\n';
                     break;
                 case Integer:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const int*)pData)[i] << '\n';
                   break;
                 case RealSingle:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const float*)pData)[i] << '\n';
                   break;
                 case RealDouble:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const double*)pData)[i]
                          << '\n';
                   break;
                 default:
                   break;
               }
               fout << "###########################################\n";
             }
 #endif // DEBUG_DUMP_PREFIX
             SwitchOnCOMDataType(dType, FindRange(rank, size, rind,
                                                  (const COM_TT*)pData,
                                                  ranges[n]));
           }
           label = "Coordinate";
           label += (char)('X' + n);
           if (writeGhost) {
             CG_CHECK(cg_array_write, (label.c_str(), COM2CGNS(dType), rank,
                                       size, pData));
           } else {
             CG_CHECK(cg_array_core_write, (label.c_str(), COM2CGNS(dType), rank,
                                            rind, size, pData));
           }
           DEBUG_MSG("Writing attribute '" << (char)('x' + n) << "-nc', id == "
                     << nc->id() << ", components == "
                     << nc->size_of_components() << ", location == '"
                     << nc->location() << '\'');
         }
         // Write dimensional exponents and ranges.
         for (n=start; n<finish; ++n) {
           CG_CHECK(cg_goto, (mfn, mB, "Zone_t", mZ, "GridCoordinates_t", G,
                              "DataArray_t", n + 1, "end"));
           CG_CHECK(cg_descriptor_write, ("Range", ranges[n].c_str()));
           DEBUG_MSG("Writing descriptor 'Range': '" << ranges[n] << '\'');
           if (!attr->unit().empty()) {
             cg_exponents_as_string_write(attr->unit().c_str(), errorhandle);
             DEBUG_MSG("Writing descriptor 'Units': '" << attr->unit()
                       << '\'');
             CG_CHECK(cg_descriptor_write, ("Units", attr->unit().c_str()));
           } else { // Assume meters.
             cg_exponents_as_string_write("m", errorhandle);
             DEBUG_MSG("Writing descriptor 'Units': 'm'");
             CG_CHECK(cg_descriptor_write, ("Units", "m"));
           }
         }
       }
     }
     if (pane.is_unstructured() &&
         (attr->id() == COM::COM_MESH || attr->id() == COM::COM_PMESH
          || attr->id() == COM::COM_CONN || attr->id() == COM::COM_ALL)) {
       // Now do the element tables.
       int nS;
       CG_CHECK(cg_nsections, (mfn, mB, mZ, &nS));
       if (nS == 0) {
         if (!mfile.empty())
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "end"));
         std::vector<const Connectivity*> conns;
         pane.elements(conns);
         int S = 0;
         i = 0;
         std::vector<const Connectivity*>::const_iterator c;
         for (c=conns.begin(); c!=conns.end(); ++c) {
           int nItems = (*c)->size_of_items();
           int nGhost = (*c)->size_of_ghost_items();
           DEBUG_MSG("Writing attribute '" << (*c)->name() << "', nItems == "
                     << nItems << ", elemType == " << (*c)->element_type());
           if (nItems == 0) {
             label = "Empty" + (*c)->name();
             S = WriteElements(mfn, mB, mZ, (*c)->element_type(), nItems,
                               NULL, false, 0, (*c)->index_offset() + 1, label,
                               errorhandle);
           } else if ((*c)->pointer() == NULL) {
             label = "Null" + (*c)->name();
             S = WriteElements(mfn, mB, mZ, (*c)->element_type(), nItems,
                               NULL, false, 0, (*c)->index_offset() + 1, label,
                               errorhandle);
           } else {
           // Write out a table of real nodes.
             label = (*c)->name();
             S = WriteElements(mfn, mB, mZ, (*c)->element_type(), nItems,
                               (*c)->pointer(), ((*c)->stride() == 1),
                               (*c)->capacity(), (*c)->index_offset() + 1,
                               label, errorhandle);
           }
           // Write out a table of ghost nodes.
           if (nGhost > 0) {
             int elemRind[2] = { 0, nGhost };
             CG_CHECK(cg_goto, (mfn, mB, "Zone_t", mZ, "Elements_t", S, "end"));
             CG_CHECK(cg_rind_write, (elemRind));
           }
           // Link from the real file to the mesh file.
           if (!mfile.empty()) {
             CG_CHECK(cg_link_write, (label.c_str(), mfile.c_str(),
                                      (path + label).c_str()));
           }
         }
       }
     }
   } else if (!mfile.empty()) {
     // If we have a mesh file, we must link to the eternal GridCoordinates_t
     // and Elements_t nodes, even if attr->id() doesn't include mesh data.
     // First link the GridCoordinates_t node.
     CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "end"));
     CG_CHECK(cg_ngrids, (fn, B, Z, &nGC));
     if (nGC == 0) {
       CG_CHECK(cg_link_write, ("GridCoordinates", mfile.c_str(),
                                (path + "GridCoordinates").c_str()));
     }
     CG_CHECK(cg_link_write, (gridName.c_str(), mfile.c_str(),
                              (path + "GridCoordinates").c_str()));
     // Then link any Elements_t nodes.
     if (pane.is_unstructured()) {
       CG_CHECK(cg_open,
                (mfile.c_str(), MODE_READ, &mfn));
       CG_CHECK(cg_base_find_or_create, (mfn, material, cellDim, physDim, &mB,
                                         errorhandle));
       CG_CHECK(cg_zone_find_or_create, (mfn, mB, zoneName.c_str(),
                                         sizes, zType, &mZ, errorhandle));
       CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "end"));
       int S, nS;
       CG_CHECK(cg_nsections, (mfn, mB, mZ, &nS));
       char label[33];
       ElementType_t eType;
       int min, max, nBoundary, parent;
       for (S=1; S<=nS; ++S) {
         CG_CHECK(cg_section_read, (mfn, mB, mZ, S, label, &eType, &min, &max,
                                    &nBoundary, &parent));
         CG_CHECK(cg_link_write, (label, mfile.c_str(), (path + label).c_str()));
       }
     }
   }
   if (mfn != fn)
     CG_CHECK(cg_close, (mfn));
   // This node is referenced in the FlowSolutionPointers, so we should make
   // sure it exists even if its left empty.
   int T;
   CG_CHECK(cg_sol_find_or_create, (fn, B, Z, nodeName.c_str(), Vertex, &T,
                                    errorhandle));
   if (attr->id() == COM::COM_CONN || attr->id() == COM::COM_NC
       || (attr->id() >= COM::COM_NC1 && attr->id() <= COM::COM_NC3))
     return;
   // Write out attributes.  Window attributes should be stored in IntegralData
   // nodes under the base node.  Pane, element, and node attributes should be
   // stored under the zone node, pane attrs in IntegralData nodes, element and
   // node attributes in FlowSolution nodes.
   std::vector<const Attribute*> attrs;
   if (attr->id() != COM::COM_MESH && attr->id() != COM::COM_PMESH
       && attr->id() != COM::COM_PCONN && attr->id() != COM::COM_RIDGES)
     pane.attributes(attrs);
   if (attr->id() == COM::COM_ALL || attr->id() == COM::COM_PMESH) {
     attrs.insert(attrs.begin(), pane.attribute(COM::COM_RIDGES));
     attrs.insert(attrs.begin(), pane.attribute(COM::COM_PCONN));
   } else if (attr->id() == COM::COM_MESH) {
     attrs.insert(attrs.begin(), pane.attribute(COM::COM_RIDGES));
   } else if (COM::COM_PCONN) {
     attrs.insert(attrs.begin(), pane.attribute(COM::COM_PCONN));
   } else if (attr->id() == COM::COM_RIDGES) {
     attrs.insert(attrs.begin(), pane.attribute(COM::COM_RIDGES));
   }
   std::vector<const Attribute*>::const_iterator begin = attrs.begin();
   std::vector<const Attribute*>::const_iterator end = attrs.end();
   if (attr->id() == COM::COM_MESH && attr->id() != COM::COM_PMESH
       && attr->id() != COM::COM_ATTS && attr->id() != COM::COM_ALL) {
     while (begin != end && (*begin)->id() != attr->id())
       ++begin;
     COM_assertion_msg(begin != end,
                       "Rocout::write_attribute: can't find attribute in pane");
     end = begin + 1;
   }
   std::vector<const Attribute*>::const_iterator a;
   for (a=begin; a!=end; ++a) {
     DEBUG_MSG("Writing attribute '" << (*a)->name() << "', id == "
               << (*a)->id() << ", components == " << (*a)->size_of_components()
               << ", location == '" << (*a)->location() << "\', datatype == "
               << (*a)->data_type());
     int A, size[3], nComp = (*a)->size_of_components(), offset;
     const void* pData[9];
     dType = (*a)->data_type();
     switch ((*a)->location()) {
       case 'w':
         size[0] = numItems = (*a)->size_of_items();
         size[1] = size[2] = 1;
         rind[0] = 0;
         rind[1] = (*a)->size_of_ghost_items();
         CG_CHECK(cg_goto, (fn, B, "end"));
         CG_CHECK(cg_integral_find_or_create, (winName.c_str(), &T,
                                               errorhandle));
         CG_CHECK(cg_goto, (fn, B, "IntegralData_t", T, "end"));
         CG_CHECK(cg_narrays, (&offset));
         ++offset;
         for (A=0; A<nComp; ++A) {
           CG_CHECK(cg_goto, (fn, B, "IntegralData_t", T, "end"));
           label = (*a)->name();
           const Attribute* pa;
           if (nComp == 1)
             pa = pane.attribute((*a)->id());
           else {
             pa = pane.attribute((*a)->id() + A + 1);
             std::ostringstream sout;
             sout << label << '#' << A + 1 << "of" << nComp;
             label = sout.str();
           }
 #ifdef DEBUG_DUMP_PREFIX
           std::ofstream fout((DEBUG_DUMP_PREFIX + std::string(material) + '.' + (*a)->name() + '_' + timeLevel + ".cgns").c_str(), std::ios_base::app);
 #endif // DEBUG_DUMP_PREFIX
           bool isNull = false;
           pData[A] = pa->pointer();
           if (numItems <= (writeGhost ? 0 : rind[1])) {
             buf.resize(COM::Attribute::get_sizeof(dType, 1), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             size[0] = 1;
             if (!writeGhost)
               rind[1] = 0;
             range = "EMPTY";
           } else if (pData[A] == NULL) {
             buf.resize(COM::Attribute::get_sizeof(dType,
                                                   std::max(size[0], 1)), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             isNull = true;
             size[0] = 1;
             range = "NULL";
           } else {
             int stride = pa->stride();
             if (stride > 1) {
               int dSize = COM::Attribute::get_sizeof(dType, 1);
               buf.resize(dSize * std::max(numItems, 1));
               for (i=0; i<numItems; ++i)
                 std::memcpy(&(buf[i*dSize]),
                             &(((const char*)pData[A])[i*stride*dSize]), dSize);
               pData[A] = &(buf[0]);
             }
 #ifdef DEBUG_DUMP_PREFIX
             {
               switch (COM2CGNS(dType)) {
                 case Character:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << (int)((const char*)(pData[A]))[i]
                          << '\n';
                     break;
                 case Integer:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const int*)(pData[A]))[i] << '\n';
                   break;
                 case RealSingle:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const float*)(pData[A]))[i] << '\n';
                   break;
                 case RealDouble:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const double*)(pData[A]))[i]
                          << '\n';
                   break;
                 default:
                   break;
               }
               fout << "###########################################\n";
             }
 #endif // DEBUG_DUMP_PREFIX
             // SwitchOnCOMDataType(pa->data_type(),
             SwitchOnCOMDataType(dType,
                                 FindRange(1, size, rind,
                                           (const COM_TT*)pData[A], range));
           }
           if (writeGhost) {
             CG_CHECK(cg_array_write, (label.c_str(), COM2CGNS(dType),
                                       1, size, pData[A]));
           } else {
             CG_CHECK(cg_array_core_write, (label.c_str(), COM2CGNS(dType),
                                            1, rind, size, pData[A]));
           }
           CG_CHECK(cg_goto, (fn, B, "IntegralData_t", T, "DataArray_t",
                              A + offset, "end"));
           CG_CHECK(cg_descriptor_write, ("Range", range.c_str()));
           DEBUG_MSG("Writing descriptor 'Range': '" << range << '\'');
           if (!pa->unit().empty()) {
             cg_exponents_as_string_write(attr->unit().c_str(), errorhandle);
             CG_CHECK(cg_descriptor_write, ("Units", pa->unit().c_str()));
             DEBUG_MSG("Writing descriptor 'Units': '" << pa->unit() << '\'');
           }
           // We can't put a Rind_t node under a DataArray_t node.
           if (writeGhost) {
             std::ostringstream sout;
             sout << rind[1];
             CG_CHECK(cg_descriptor_write, ("Ghost", sout.str().c_str()));
             DEBUG_MSG("Writing descriptor 'Ghost': '" << sout.str() << '\'');
           }
         }
         break;
       case 'p':
         size[0] = numItems = (*a)->size_of_items();
         size[1] = size[2] = 1;
         rind[0] = 0;
         rind[1] = (*a)->size_of_ghost_items();
         DEBUG_MSG("numItems == " << numItems << ", numGhostItems == "
                   << rind[1]);
         CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "end"));
         CG_CHECK(cg_integral_find_or_create, (paneName.c_str(), &T,
                                               errorhandle));
         CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "IntegralData_t", T, "end"));
         CG_CHECK(cg_narrays, (&offset));
         ++offset;
         for (A=0; A<nComp; ++A) {
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "IntegralData_t", T, "end"));
           label = (*a)->name();
           const Attribute* pa;
           if (nComp == 1)
             pa = pane.attribute((*a)->id());
           else {
             pa = pane.attribute((*a)->id() + A + 1);
             std::ostringstream sout;
             sout << label << '#' << A + 1 << "of" << nComp;
             label = sout.str();
           }
 #ifdef DEBUG_DUMP_PREFIX
           std::ofstream fout((DEBUG_DUMP_PREFIX + std::string(material) + '.' + (*a)->name() + '_' + timeLevel + ".cgns").c_str(), std::ios_base::app);
 #endif // DEBUG_DUMP_PREFIX
           bool isNull = false;
           pData[A] = pa->pointer();
           if (numItems <= (writeGhost ? 0 : rind[1])) {
             buf.resize(COM::Attribute::get_sizeof(dType, 1), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             size[0] = 1;
             if (!writeGhost)
               rind[1] = 0;
             range = "EMPTY";
           } else if (pData[A] == NULL) {
             buf.resize(COM::Attribute::get_sizeof(dType,
                                                   std::max(size[0], 1)), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             isNull = true;
             size[0] = 1;
             range = "NULL";
           } else {
             int stride = pa->stride();
             if (stride > 1) {
               int dSize = COM::Attribute::get_sizeof(dType, 1);
               buf.resize(dSize * std::max(numItems, 1));
               for (i=0; i<numItems; ++i)
                 std::memcpy(&(buf[i*dSize]),
                             &(((const char*)pData[A])[i*stride*dSize]), dSize);
               pData[A] = &(buf[0]);
             }
 #ifdef DEBUG_DUMP_PREFIX
             {
               switch (COM2CGNS(dType)) {
                 case Character:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << (int)((const char*)(pData[A]))[i]
                          << '\n';
                     break;
                 case Integer:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const int*)(pData[A]))[i] << '\n';
                   break;
                 case RealSingle:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const float*)(pData[A]))[i] << '\n';
                   break;
                 case RealDouble:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const double*)(pData[A]))[i]
                          << '\n';
                   break;
                 default:
                   break;
               }
               fout << "###########################################\n";
             }
 #endif // DEBUG_DUMP_PREFIX
             SwitchOnCOMDataType(dType,
                                 FindRange(1, size, rind,
                                           (const COM_TT*)pData[A], range));
           }
           if (writeGhost) {
             CG_CHECK(cg_array_write, (label.c_str(), COM2CGNS(dType),
                                       1, size, pData[A]));
           } else {
             CG_CHECK(cg_array_core_write, (label.c_str(), COM2CGNS(dType),
                                            1, rind, size, pData[A]));
           }
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "IntegralData_t", T,
                              "DataArray_t", A + offset, "end"));
           CG_CHECK(cg_descriptor_write, ("Range", range.c_str()));
           DEBUG_MSG("Writing descriptor 'Range' == '" << range << '\'');
           if (!pa->unit().empty()) {
             cg_exponents_as_string_write(attr->unit().c_str(), errorhandle);
             DEBUG_MSG("Writing descriptor 'Units' == '" << pa->unit() << '\'');
             CG_CHECK(cg_descriptor_write, ("Units", pa->unit().c_str()));
           }
           // We can't put a Rind_t node under a DataArray_t node.
           if (writeGhost) {
             std::ostringstream sout;
             sout << rind[1];
             CG_CHECK(cg_descriptor_write, ("Ghost", sout.str().c_str()));
             DEBUG_MSG("Writing descriptor 'Ghost' == '" << sout.str() << '\'');
           }
         }
         if ((*a)->id() == COM::COM_PCONN) {
           // Create CGNS connectivity node.
         } else if ((*a)->id() == COM::COM_RIDGES) {
           DEBUG_MSG("Special COM_RIDGES handling: zType == "
                     << (zType == Structured ? "Structured" : "Unstructured")
                     << ", size_of_components() == "
                     << (*a)->size_of_components() << ", size_of_items() == "
                     << (*a)->size_of_items());
           if (zType == Unstructured && (*a)->size_of_components() == 2
               && (*a)->size_of_items() > 0) {
             // Create parallel base and zone with BAR_2 elements.
             std::string newName(material);
             newName += "_ridges";
             int RB;
             DEBUG_MSG("Creating base \"" << newName
                       << "\", cellDim == 1, physDim == " << physDim);
             CG_CHECK(cg_base_find_or_create, (fn, newName.c_str(), 1, physDim,
                                               &RB, errorhandle));
             // Write the default Roccom units at the top.
             CG_CHECK(cg_goto, (fn, RB, "end"));
             CG_CHECK(cg_units_write, (Kilogram, Meter, Second, Kelvin, Degree));
             std::string rpath("/");
             rpath += material;
             rpath += '/';
             // Check to see if a BaseIterativeData node exists.
             if (cg_goto(fn, RB, "BaseIterativeData_t", 1, "end") != 0) {
               // Link to the main BaseIterativeData_t node.
               DEBUG_MSG("Linking TimeIterValues  to "
                         << rpath + "TimeIterValues");
               CG_CHECK(cg_goto, (fn, RB, "end"));
               CG_CHECK(cg_link_write, ("TimeIterValues", "",
                                        (rpath + "TimeIterValues").c_str()));
             }
             // Find or create the zone (corresponds to pane/section).  Use the
             // pane id as the zone name.  Set up the sizes based on
             // dimensionality and zone type.
             int RZ, rsizes[9] = { 0, 0, 0, 0, 0, 0, 0, 0, 0 };
             rsizes[0] = sizes[0];
             rsizes[1] = (*a)->size_of_real_items();
             DEBUG_MSG("Creating zone \"" << zoneName << "\", size == [ "
                       << rsizes[0] << ", " << rsizes[1] << " ]");
             CG_CHECK(cg_zone_find_or_create, (fn, RB, zoneName.c_str(), rsizes,
                                               Unstructured, &RZ, errorhandle));
             // Check to see if a ZoneIterativeData node exists.
             if (cg_goto(fn, RB, "Zone_t", RZ,
                         "ZoneIterativeData_t", 1, "end") != 0) {
               CG_CHECK(cg_goto, (fn, RB, "Zone_t", RZ, "end"));
               rpath += zoneName;
               rpath += '/';
               // Link to the main ZoneIterativeData_t node.
               DEBUG_MSG("Linking ZoneIterativeData  to "
                         << rpath + "ZoneIterativeData");
               CG_CHECK(cg_link_write, ("ZoneIterativeData", "",
                                        (rpath + "ZoneIterativeData").c_str()));
               // Link to the main GridCoordinates_t node.
               DEBUG_MSG("Linking GridCoordinates  to "
                         << rpath + "GridCoordinates");
               CG_CHECK(cg_link_write, ("GridCoordinates", "",
                                        (rpath + "GridCoordinates").c_str()));
               DEBUG_MSG("Linking " << gridName << "  to " << rpath + gridName);
               CG_CHECK(cg_link_write, (gridName.c_str(), "",
                                        (rpath + gridName).c_str()));
               // Link to the FlowSolution_t node with nodal data.
               DEBUG_MSG("Linking " << nodeName << "  to "
                         << rpath + nodeName);
               CG_CHECK(cg_link_write, (nodeName.c_str(), "",
                                        (rpath + nodeName).c_str()));
             }
             const Attribute* pa[2];
             pa[0] = pane.attribute((*a)->id() + 1);
             pa[1] = pane.attribute((*a)->id() + 2);
             DEBUG_MSG("Retreived the 'ridges' components: '" << pa[0]->name()
                       << "' and '" << pa[1]->name() << '\'');
             // Now do the BAR_2 element tables.
             int RS = 0;
             int nItems = pa[0]->size_of_items();
             int nGhost = pa[0]->size_of_ghost_items();
             DEBUG_MSG("Writing " << nItems << " BAR_2 elements (with "
                       << nGhost << " ghost elements)");
             COM_assertion(nItems == pa[1]->size_of_items());
             COM_assertion(nGhost == pa[1]->size_of_ghost_items());
             COM_assertion((pa[0]->pointer()==NULL) == (pa[1]->pointer()==NULL));
             if (!writeGhost)
               nItems = pa[0]->size_of_real_items();
             // Write out a table of real nodes.
             label = (*a)->name();
             std::vector<int> bar(2 * nItems);
             for (i=0; i<2; ++i) {
               int* ptr = (int*)pa[i]->pointer();
               int j, stride = std::max(pa[i]->stride(), 1);
               for (j=0; j<nItems; ++j)
                 bar[2*j+i] = ptr[j*stride];
             }
             RS = WriteElements(mfn, RB, RZ, Connectivity::BAR2, nItems,
                                &bar[0], false, 0, 1, label, errorhandle);
             // Write out a table of ghost elements.
             if (writeGhost) {
               int elemRind[2] = { 0, nGhost };
               CG_CHECK(cg_goto,
                        (fn, RB, "Zone_t", RZ, "Elements_t", RS, "end"));
               CG_CHECK(cg_rind_write, (elemRind));
             }
           }
         } else if ((*a)->name() == "bcflag") {
           // Create CGNS boundary conditions node.
           // Boundary conditions might have other names, too.
         }
         break;
       case 'c':
         size[0] = numItems = (*a)->size_of_items();
         size[1] = size[2] = 1;
         rind[0] = 0;
         rind[1] = (*a)->size_of_ghost_items();
         CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "end"));
         CG_CHECK(cg_integral_find_or_create, (connName.c_str(), &T,
                                               errorhandle));
         CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "IntegralData_t", T, "end"));
         CG_CHECK(cg_narrays, (&offset));
         ++offset;
         for (A=0; A<nComp; ++A) {
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "IntegralData_t", T, "end"));
           label = (*a)->name();
           const Attribute* pa;
           if (nComp == 1)
             pa = pane.attribute((*a)->id());
           else {
             pa = pane.attribute((*a)->id() + A + 1);
             std::ostringstream sout;
             sout << label << '#' << A + 1 << "of" << nComp;
             label = sout.str();
           }
 #ifdef DEBUG_DUMP_PREFIX
           std::ofstream fout((DEBUG_DUMP_PREFIX + std::string(material) + '.' + (*a)->name() + '_' + timeLevel + ".cgns").c_str(), std::ios_base::app);
 #endif // DEBUG_DUMP_PREFIX
           bool isNull = false;
           pData[A] = pa->pointer();
           if (numItems <= (writeGhost ? 0 : rind[1])) {
             buf.resize(COM::Attribute::get_sizeof(dType, 1), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             size[0] = 1;
             if (!writeGhost)
               rind[1] = 0;
             range = "EMPTY";
           } else if (pData[A] == NULL) {
             buf.resize(COM::Attribute::get_sizeof(dType,
                                                   std::max(size[0], 1)), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             isNull = true;
             size[0] = 1;
             range = "NULL";
           } else {
             int stride = pa->stride();
             if (stride > 1) {
               int dSize = COM::Attribute::get_sizeof(dType, 1);
               buf.resize(dSize * std::max(numItems, 1));
               for (i=0; i<numItems; ++i)
                 std::memcpy(&(buf[i*dSize]),
                             &(((const char*)pData[A])[i*stride*dSize]), dSize);
               pData[A] = &(buf[0]);
             }
 #ifdef DEBUG_DUMP_PREFIX
             {
               switch (COM2CGNS(dType)) {
                 case Character:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << (int)((const char*)(pData[A]))[i]
                          << '\n';
                     break;
                 case Integer:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const int*)(pData[A]))[i] << '\n';
                   break;
                 case RealSingle:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const float*)(pData[A]))[i] << '\n';
                   break;
                 case RealDouble:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const double*)(pData[A]))[i]
                          << '\n';
                   break;
                 default:
                   break;
               }
               fout << "###########################################\n";
             }
 #endif // DEBUG_DUMP_PREFIX
             SwitchOnCOMDataType(dType,
                                 FindRange(1, size, rind,
                                           (const COM_TT*)pData[A], range));
           }
           if (writeGhost) {
             CG_CHECK(cg_array_write, (label.c_str(), COM2CGNS(dType),
                                       1, size, pData[A]));
           } else {
             CG_CHECK(cg_array_core_write, (label.c_str(), COM2CGNS(dType),
                                            1, rind, size, pData[A]));
           }
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "IntegralData_t", T,
                              "DataArray_t", A + offset, "end"));
           CG_CHECK(cg_descriptor_write, ("Range", range.c_str()));
           DEBUG_MSG("Writing descriptor 'Range': '" << range << '\'');
           if (!pa->unit().empty()) {
             cg_exponents_as_string_write(attr->unit().c_str(), errorhandle);
             CG_CHECK(cg_descriptor_write, ("Units", pa->unit().c_str()));
             DEBUG_MSG("Writing descriptor 'Units': '" << pa->unit() << '\'');
           }
           // We can't put a Rind_t node under a DataArray_t node.
           if (writeGhost) {
             std::ostringstream sout;
             sout << rind[1];
             CG_CHECK(cg_descriptor_write, ("Ghost", sout.str().c_str()));
             DEBUG_MSG("Writing descriptor 'Ghost': '" << sout.str() << '\'');
           }
         }
         break;
       case 'n':
         if (pane.is_structured()) {
           rank = cellDim;
           size[0] = pane.size_i();
           if (cellDim > 1) {
             size[1] = pane.size_j();
             size[2] = cellDim > 2 ? pane.size_k() : 1;
           } else {
             size[1] = size[2] = 1;
           }
           numItems = size[0] * size[1] * size[2];
           std::fill_n(rind, 2 * physDim, pane.size_of_ghost_layers());
         } else {
           rank = 1;
           size[0] = numItems = (*a)->size_of_items();
           size[1] = size[2] = 1;
           std::fill_n(rind, 6, 0);
           rind[1] = (*a)->size_of_ghost_items();
         }
         CG_CHECK(cg_sol_find_or_create, (fn, B, Z, nodeName.c_str(), Vertex, &T,
                                          errorhandle));
         CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T, "end"));
         CG_CHECK(cg_gridlocation_write, (Vertex));
         // Write rind data.
         if (writeGhost) {
           CG_CHECK(cg_rind_write, (rind));
           DEBUG_MSG("Ghost == " << rind[1]);
         }
         CG_CHECK(cg_narrays, (&offset));
         ++offset;
         for (A=0; A<nComp; ++A) {
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T, "end"));
           label = (*a)->name();
           const Attribute* pa;
           if (nComp == 1)
             pa = pane.attribute((*a)->id());
           else {
             pa = pane.attribute((*a)->id() + A + 1);
             if (nComp == physDim) {
               label += (char)('X' + (char)A);
             } else if (nComp == physDim * physDim) {
               label += (char)('X' + (char)(A / physDim));
               label += (char)('X' + (char)(A % physDim));
             } else {
               std::ostringstream sout;
               sout << label << '#' << A + 1 << "of" << nComp;
               label = sout.str();
             }
           }
 #ifdef DEBUG_DUMP_PREFIX
           std::ofstream fout((DEBUG_DUMP_PREFIX + std::string(material) + '.' + (*a)->name() + '_' + timeLevel + ".cgns").c_str(), std::ios_base::app);
 #endif // DEBUG_DUMP_PREFIX
           bool isNull = false;
           pData[A] = pa->pointer();
           if (numItems <= 0) {
             buf.resize(COM::Attribute::get_sizeof(dType, 1), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             size[0] = size[1] = size[2] = 1;
             range = "EMPTY";
           } else if (pData[A] == NULL) {
             buf.resize(COM::Attribute::get_sizeof(dType, std::max(numItems, 1)),
                                                   '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             isNull = true;
             // size[0] = size[1] = size[2] = 1;
             range = "NULL";
           } else {
             int stride = pa->stride();
             if (stride > 1) {
               int dSize = COM::Attribute::get_sizeof(dType, 1);
               buf.resize(dSize * std::max(numItems, 1));
               for (i=0; i<numItems; ++i) {
                 std::memcpy(&(buf[i*dSize]),
                             &(((const char*)pData[A])[i*stride*dSize]), dSize);
               }
               pData[A] = &(buf[0]);
             }
 #ifdef DEBUG_DUMP_PREFIX
             {
               switch (COM2CGNS(dType)) {
                 case Character:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << (int)((const char*)(pData[A]))[i]
                          << '\n';
                     break;
                 case Integer:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const int*)(pData[A]))[i] << '\n';
                   break;
                 case RealSingle:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const float*)(pData[A]))[i] << '\n';
                   break;
                 case RealDouble:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const double*)(pData[A]))[i]
                          << '\n';
                   break;
                 default:
                   break;
               }
               fout << "###########################################\n";
             }
 #endif // DEBUG_DUMP_PREFIX
             SwitchOnCOMDataType(dType,
                                 FindRange(rank, size, rind,
                                           (const COM_TT*)pData[A], range));
           }
           if (writeGhost) {
             DEBUG_MSG("Calling cg_array_write( name == '" << label
                       << "', dataType == "
                       << (COM2CGNS(dType) == RealSingle ? "float"
                          : (COM2CGNS(dType) == RealDouble ? "double"
                          : (COM2CGNS(dType) == Character ? "char" : "int?")))
                       << ", rank == " << rank << ", size[] = { " << size[0]
                       << ", " << size[1] << ", " << size[2] << " } )");
             CG_CHECK(cg_array_write, (label.c_str(), COM2CGNS(dType),
                                       rank, size, pData[A]));
           } else {
             DEBUG_MSG("Calling cg_array_core_write( name == '" << label
                       << "', dataType == "
                       << (COM2CGNS(dType) == RealSingle ? "float"
                          : (COM2CGNS(dType) == RealDouble ? "double"
                          : (COM2CGNS(dType) == Character ? "char" : "int?")))
                       << ", rank == " << rank << ", rind[] = { " << rind[0]
                       << ", " << rind[1] << ", " << rind[2] << ", " << rind[3]
                       << ", " << rind[4] << ", " << rind[5] << " }, size[] = { "
                       << size[0] << ", " << size[1] << ", " << size[2]
                       << " } )");
             CG_CHECK(cg_array_core_write, (label.c_str(), COM2CGNS(dType),
                                            rank, rind, size, pData[A]));
           }
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T,
                              "DataArray_t", A + offset, "end"));
           DEBUG_MSG("Calling cg_descriptor_write( name == 'Range', "
                     << "value == '" << range << "' )");
           CG_CHECK(cg_descriptor_write, ("Range", range.c_str()));
           if (!pa->unit().empty()) {
             cg_exponents_as_string_write(attr->unit().c_str(), errorhandle);
             DEBUG_MSG("Calling cg_descriptor_write( name == 'Units', "
                       << "value == '" << pa->unit() << "' )");
             CG_CHECK(cg_descriptor_write, ("Units", pa->unit().c_str()));
           }
         }
         // Vectors and tensors need a MagnitudeRange or TraceRange
         // descriptor under the first DataArray_t node.
         if (nComp == 3) {
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T,
                              "DataArray_t", offset, "end"));
           SwitchOnCOMDataType(dType,
                               FindMagnitudeRange(physDim, rank, size, rind,
                                                  (const COM_TT**)pData,
                                                  range));
           CG_CHECK(cg_descriptor_write, ("MagnitudeRange", range.c_str()));
         } else if (nComp == 9) {
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T,
                              "DataArray_t", offset, "end"));
           SwitchOnCOMDataType(dType,
                               FindTraceRange(physDim, rank, size, rind,
                                              (const COM_TT**)pData, range));
           CG_CHECK(cg_descriptor_write, ("TraceRange", range.c_str()));
         }
         break;
       case 'e':
         if (pane.is_structured()) {
           rank = cellDim;
           size[0] = pane.size_i() - 1;
           if (cellDim > 1) {
             size[1] = pane.size_j() - 1;
             size[2] = cellDim > 2 ? pane.size_k() - 1 : 1;
           } else {
             size[1] = size[2] = 1;
           }
           numItems = size[0] * size[1] * size[2];
           std::fill_n(rind, 2 * physDim, pane.size_of_ghost_layers());
         } else {
           rank = 1;
           size[0] = numItems = (*a)->size_of_items();
           size[1] = size[2] = 1;
           std::fill_n(rind, 6, 0);
           rind[1] = (*a)->size_of_ghost_items();
         }
         CG_CHECK(cg_sol_find_or_create, (fn, B, Z, elemName.c_str(), CellCenter,
                                          &T, errorhandle));
         CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T, "end"));
         CG_CHECK(cg_gridlocation_write, (CellCenter));
         // Write rind data.
         if (writeGhost) {
           CG_CHECK(cg_rind_write, (rind));
           DEBUG_MSG("Ghost == " << rind[1]);
         }
         CG_CHECK(cg_narrays, (&offset));
         ++offset;
         for (A=0; A<nComp; ++A) {
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T, "end"));
           label = (*a)->name();
           const Attribute* pa;
           if (nComp == 1)
             pa = pane.attribute((*a)->id());
           else {
             pa = pane.attribute((*a)->id() + A + 1);
             if (nComp == physDim) {
               label += (char)('X' + (char)A);
             } else if (nComp == physDim * physDim) {
               label += (char)('X' + (char)(A / physDim));
               label += (char)('X' + (char)(A % physDim));
             } else {
               std::ostringstream sout;
               sout << label << '#' << A + 1 << "of" << nComp;
               label = sout.str();
             }
           }
 #ifdef DEBUG_DUMP_PREFIX
           std::ofstream fout((DEBUG_DUMP_PREFIX + std::string(material) + '.' + (*a)->name() + '_' + timeLevel + ".cgns").c_str(), std::ios_base::app);
 #endif // DEBUG_DUMP_PREFIX
           bool isNull = false;
           pData[A] = pa->pointer();
           if (numItems <= 0) {
             buf.resize(COM::Attribute::get_sizeof(dType, 1), '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             size[0] = size[1] = size[2] = 1;
             range = "EMPTY";
           } else if (pData[A] == NULL) {
             buf.resize(COM::Attribute::get_sizeof(dType, std::max(numItems, 1)),
                                                   '\0');
             std::fill(buf.begin(), buf.end(), '\0');
             pData[A] = &(buf[0]);
             isNull = true;
             // size[0] = size[1] = size[2] = 1;
             range = "NULL";
           } else {
             int stride = pa->stride();
             if (stride > 1) {
               int dSize = COM::Attribute::get_sizeof(dType, 1);
               buf.resize(dSize * std::max(numItems, 1));
               for (i=0; i<numItems; ++i) {
                 std::memcpy(&(buf[i*dSize]),
                             &(((const char*)pData[A])[i*stride*dSize]), dSize);
               }
               pData[A] = &(buf[0]);
             }
 #ifdef DEBUG_DUMP_PREFIX
             {
               switch (COM2CGNS(dType)) {
                 case Character:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << (int)((const char*)(pData[A]))[i]
                          << '\n';
                     break;
                 case Integer:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const int*)(pData[A]))[i] << '\n';
                   break;
                 case RealSingle:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const float*)(pData[A]))[i] << '\n';
                   break;
                 case RealDouble:
                   for (i=0; i<numItems; ++i)
                     fout << i << " : " << ((const double*)(pData[A]))[i]
                          << '\n';
                   break;
                 default:
                   break;
               }
               fout << "###########################################\n";
             }
 #endif // DEBUG_DUMP_PREFIX
             SwitchOnCOMDataType(dType,
                                 FindRange(rank, size, rind,
                                           (const COM_TT*)pData[A], range));
           }
           if (writeGhost) {
             DEBUG_MSG("Calling cg_array_write( name == '" << label
                       << "', dataType == "
                       << (COM2CGNS(dType) == RealSingle ? "float"
                          : (COM2CGNS(dType) == RealDouble ? "double"
                          : (COM2CGNS(dType) == Character ? "char" : "int?")))
                       << ", rank == " << rank << ", size[] = { " << size[0]
                       << ", " << size[1] << ", " << size[2] << " } )");
             CG_CHECK(cg_array_write, (label.c_str(), COM2CGNS(dType),
                                       rank, size, pData[A]));
           } else {
             DEBUG_MSG("Calling cg_array_core_write( name == '" << label
                       << "', dataType == "
                       << (COM2CGNS(dType) == RealSingle ? "float"
                          : (COM2CGNS(dType) == RealDouble ? "double"
                          : (COM2CGNS(dType) == Character ? "char" : "int?")))
                       << ", rank == " << rank << ", rind[] = { " << rind[0]
                       << ", " << rind[1] << ", " << rind[2] << ", " << rind[3]
                       << ", " << rind[4] << ", " << rind[5] << " }, size[] = { "
                       << size[0] << ", " << size[1] << ", " << size[2]
                       << " } )");
             CG_CHECK(cg_array_core_write, (label.c_str(), COM2CGNS(dType),
                                            rank, rind, size, pData[A]));
           }
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T,
                              "DataArray_t", A + offset, "end"));
           DEBUG_MSG("Calling cg_descriptor_write( name == 'Range', "
                     << "value == '" << range << "' )");
           CG_CHECK(cg_descriptor_write, ("Range", range.c_str()));
           if (!pa->unit().empty()) {
             cg_exponents_as_string_write(attr->unit().c_str(), errorhandle);
             DEBUG_MSG("Calling cg_descriptor_write( name == 'Units', "
                       << "value == '" << pa->unit() << "' )");
             CG_CHECK(cg_descriptor_write, ("Units", pa->unit().c_str()));
           }
         }
         // Vectors and tensors need a MagnitudeRange or TraceRange
         // descriptor under the first DataArray_t node.
         if (nComp == 3) {
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T,
                              "DataArray_t", offset, "end"));
           SwitchOnCOMDataType(dType,
                               FindMagnitudeRange(physDim, rank, size, rind,
                                                  (const COM_TT**)pData,
                                                  range));
           CG_CHECK(cg_descriptor_write, ("MagnitudeRange", range.c_str()));
         } else if (nComp == 9) {
           CG_CHECK(cg_goto, (fn, B, "Zone_t", Z, "FlowSolution_t", T,
                              "DataArray_t", offset, "end"));
           SwitchOnCOMDataType(dType,
                               FindTraceRange(physDim, rank, size, rind,
                                              (const COM_TT**)pData, range));
           CG_CHECK(cg_descriptor_write, ("TraceRange", range.c_str()));
         }
         break;
     }
   }
 }