Rocstar: Rocout.h File Reference
Rocout.h File Reference
Rocout creates a series of Roccom windows by reading in a list of files.
#include <map>
#include "roccom.h"
#include "HDF4.h"
#include "roccom_devel.h"
Classes
class Rocout
Functions
Module loading and unloading
void Rocout_load_module (const char *name)
Load the module Rocout into Roccom using the given module name.
void Rocout_unload_module (const char *name)
Unload the module Rocout from Roccom.
Detailed Description
Rocout creates a series of Roccom windows by reading in a list of files.
Rocout can also copy Roccom attributes from window to window. Only HDF4 files are supported in the current implementation.
Definition in file Rocout.h.
Function Documentation
void Rocout_load_module (const char * name)
Load the module Rocout into Roccom using the given module name.
This module provides one subroutine: "write_attribute".
Definition at line 873 of file Rocout.C.
Referenced by COM_F_FUNC2(), main(), and RFC_Window_base::write_sdv().
 { Rocout::init( std::string(name)); }
void Rocout_unload_module (const char * name)
Unload the module Rocout from Roccom.
Definition at line 876 of file Rocout.C.
Referenced by COM_F_FUNC2(), and RFC_Window_base::write_sdv().
 { Rocout::finalize( std::string(name)); }