Rocstar: triangle.h File Reference
Rocprop/include/triangle.h File Reference
#include <math.h>
#include "NVec.h"
Macros
#define EPSILON 0.000001
#define CROSS(dest, v1, v2)
#define DOT(v1, v2) (v1[0]*v2[0]+v1[1]*v2[1]+v1[2]*v2[2])
#define SUB(dest, v1, v2)
Functions
int intersect_ray_triangle (const Vec3D &RP0, const Vec3D &dir, Vec3D &TV0, Vec3D &TV1, Vec3D &TV2, Vec3D &I)
int intersect_triangle (double orig[3], double dir[3], double vert0[3], double vert1[3], double vert2[3], double *t, double *u, double *v)
int intersect_triangle1 (double orig[3], double dir[3], double vert0[3], double vert1[3], double vert2[3], double *t, double *u, double *v)
int intersect_triangle2 (double orig[3], double dir[3], double vert0[3], double vert1[3], double vert2[3], double *t, double *u, double *v)
int intersect_triangle3 (double orig[3], double dir[3], double vert0[3], double vert1[3], double vert2[3], double *t, double *u, double *v)
bool rayIntersectsTriangle (double *p, double *d, double *v0, double *v1, double *v2, Vec3D &I)
Macro Definition Documentation
#define CROSS (dest, v1, v2)
Value:
dest[0]=v1[1]*v2[2]-v1[2]*v2[1]; \
          dest[1]=v1[2]*v2[0]-v1[0]*v2[2]; \
          dest[2]=v1[0]*v2[1]-v1[1]*v2[0];
Definition at line 15 of file Rocprop/include/triangle.h.
#define DOT (v1, v2) (v1[0]*v2[0]+v1[1]*v2[1]+v1[2]*v2[2])
Definition at line 19 of file Rocprop/include/triangle.h.
#define EPSILON 0.000001
Definition at line 14 of file Rocprop/include/triangle.h.
#define SUB (dest, v1, v2)
Value:
dest[0]=v1[0]-v2[0]; \
          dest[1]=v1[1]-v2[1]; \
          dest[2]=v1[2]-v2[2];
Definition at line 20 of file Rocprop/include/triangle.h.
Function Documentation
int intersect_ray_triangle (const Vec3D & RP0, const Vec3D & dir, Vec3D & TV0, Vec3D & TV1, Vec3D & TV2, Vec3D & I)
Definition at line 283 of file Rocon/src/ray-triangle.C.
References nvc::cross(), s, SMALL_NUM, and v.
 {
     Vec3D    u, v, n;             // triangle vectors
     Vec3D     w0, w;          // ray vectors
     double    r, a, b;             // params to calc ray-plane intersect
     // get triangle edge vectors and plane normal
     u = TV1 - TV0;
     v = TV2 - TV0;
     n = cross(u,v);             // cross product
     if (n == Vec3D(0,0,0))            // triangle is degenerate
         return 0;                 // do not deal with this case
     //dir = RP1 - RP0;             // ray direction vector
     w0 = RP0 - TV0;
     a = -1.0*(n*w0);
     b = n*dir;
     if (fabs(b) < SMALL_NUM) {     // ray is parallel to triangle plane
       if (a != 0)                // ray lies in triangle plane
                 //return 1;
       //else
                 return 0;             // ray disjoint from plane
     }
     // get intersect point of ray with triangle plane
     r = a / b;
     if (r < 0.0)                   // ray goes away from triangle
       return 0;                  // => no intersect
     if (r > 1.0)                   // ray goes away from triangle
       return 0;                                 //change by prateek, 0 instead of 3
     // for a segment, also test if (r > 1.0) => no intersect
     I = RP0 + (r * dir);           // intersect point of ray and plane
     // is I inside T?
     double    uu, uv, vv, wu, wv, D;
     uu = (u*u);
     uv = (u*v);
     vv = (v*v);
     w =  I - TV0;
     wu = w*u;
     wv = w*v;
     D = (uv * uv) -( uu * vv);
     // get and test parametric coords
     double s, t;
     s = (uv * wv - vv * wu) / D;
     if (s < 0.0 || s > 1.0)        // I is outside T
         return 0;
     t = (uv * wu - uu * wv) / D;
     if (t < 0.0 || (s + t) > 1.0)  // I is outside T
         return 0;
     return 1;                      // I is in T
 }
int intersect_triangle (double orig[3], double dir[3], double vert0[3], double vert1[3], double vert2[3], double * t, double * u, double * v)
Definition at line 344 of file Rocon/src/ray-triangle.C.
References CROSS, Mesquite::det(), DOT, EPSILON, and SUB.
Referenced by rayIntersectsTriangle().
 {
    double edge1[3], edge2[3], tvec[3], pvec[3], qvec[3];
    double det,inv_det;
    /* find vectors for two edges sharing vert0 */
    SUB(edge1, vert1, vert0);
    SUB(edge2, vert2, vert0);
    /* begin calculating determinant - also used to calculate U parameter */
    CROSS(pvec, dir, edge2);
    /* if determinant is near zero, ray lies in plane of triangle */
    det = DOT(edge1, pvec);
    if (det > -EPSILON && det < EPSILON)
      return 0;
    inv_det = 1.0 / det;
    /* calculate distance from vert0 to ray origin */
    SUB(tvec, orig, vert0);
    /* calculate U parameter and test bounds */
    *u = DOT(tvec, pvec) * inv_det;
    if (*u < 0.0 || *u > 1.0)
      return 0;
    /* prepare to test V parameter */
    CROSS(qvec, tvec, edge1);
    /* calculate V parameter and test bounds */
    *v = DOT(dir, qvec) * inv_det;
    if (*v < 0.0 || *u + *v > 1.0)
      return 0;
    /* calculate t, ray intersects triangle */
    *t = DOT(edge2, qvec) * inv_det;
    if(*t<0 || *t>1)
      return 0; //enforce that ray is line segment
    return 1;
 }
int intersect_triangle1 (double orig[3], double dir[3], double vert0[3], double vert1[3], double vert2[3], double * t, double * u, double * v)
Definition at line 393 of file Rocon/src/ray-triangle.C.
References CROSS, Mesquite::det(), DOT, EPSILON, and SUB.
 {
    double edge1[3], edge2[3], tvec[3], pvec[3], qvec[3];
    double det,inv_det;
    /* find vectors for two edges sharing vert0 */
    SUB(edge1, vert1, vert0);
    SUB(edge2, vert2, vert0);
    /* begin calculating determinant - also used to calculate U parameter */
    CROSS(pvec, dir, edge2);
    /* if determinant is near zero, ray lies in plane of triangle */
    det = DOT(edge1, pvec);
    if (det > EPSILON)
    {
       /* calculate distance from vert0 to ray origin */
       SUB(tvec, orig, vert0);
       /* calculate U parameter and test bounds */
       *u = DOT(tvec, pvec);
       if (*u < 0.0 || *u > det)
          return 0;
       /* prepare to test V parameter */
       CROSS(qvec, tvec, edge1);
       /* calculate V parameter and test bounds */
       *v = DOT(dir, qvec);
       if (*v < 0.0 || *u + *v > det)
          return 0;
    }
    else if(det < -EPSILON)
    {
       /* calculate distance from vert0 to ray origin */
       SUB(tvec, orig, vert0);
       /* calculate U parameter and test bounds */
       *u = DOT(tvec, pvec);
 /*      printf("*u=%f\n",(double)*u); */
 /*      printf("det=%f\n",det); */
       if (*u > 0.0 || *u < det)
          return 0;
       /* prepare to test V parameter */
       CROSS(qvec, tvec, edge1);
       /* calculate V parameter and test bounds */
       *v = DOT(dir, qvec) ;
       if (*v > 0.0 || *u + *v < det)
          return 0;
    }
    else return 0;  /* ray is parallell to the plane of the triangle */
    inv_det = 1.0 / det;
    /* calculate t, ray intersects triangle */
    *t = DOT(edge2, qvec) * inv_det;
    (*u) *= inv_det;
    (*v) *= inv_det;
    return 1;
 }
int intersect_triangle2 (double orig[3], double dir[3], double vert0[3], double vert1[3], double vert2[3], double * t, double * u, double * v)
Definition at line 464 of file Rocon/src/ray-triangle.C.
References CROSS, Mesquite::det(), DOT, EPSILON, and SUB.
 {
    double edge1[3], edge2[3], tvec[3], pvec[3], qvec[3];
    double det,inv_det;
    /* find vectors for two edges sharing vert0 */
    SUB(edge1, vert1, vert0);
    SUB(edge2, vert2, vert0);
    /* begin calculating determinant - also used to calculate U parameter */
    CROSS(pvec, dir, edge2);
    /* if determinant is near zero, ray lies in plane of triangle */
    det = DOT(edge1, pvec);
    /* calculate distance from vert0 to ray origin */
    SUB(tvec, orig, vert0);
    inv_det = 1.0 / det;
    if (det > EPSILON)
    {
       /* calculate U parameter and test bounds */
       *u = DOT(tvec, pvec);
       if (*u < 0.0 || *u > det)
          return 0;
       /* prepare to test V parameter */
       CROSS(qvec, tvec, edge1);
       /* calculate V parameter and test bounds */
       *v = DOT(dir, qvec);
       if (*v < 0.0 || *u + *v > det)
          return 0;
    }
    else if(det < -EPSILON)
    {
       /* calculate U parameter and test bounds */
       *u = DOT(tvec, pvec);
       if (*u > 0.0 || *u < det)
          return 0;
       /* prepare to test V parameter */
       CROSS(qvec, tvec, edge1);
       /* calculate V parameter and test bounds */
       *v = DOT(dir, qvec) ;
       if (*v > 0.0 || *u + *v < det)
          return 0;
    }
    else return 0;  /* ray is parallell to the plane of the triangle */
    /* calculate t, ray intersects triangle */
    *t = DOT(edge2, qvec) * inv_det;
    (*u) *= inv_det;
    (*v) *= inv_det;
    return 1;
 }
int intersect_triangle3 (double orig[3], double dir[3], double vert0[3], double vert1[3], double vert2[3], double * t, double * u, double * v)
Definition at line 529 of file Rocon/src/ray-triangle.C.
References CROSS, Mesquite::det(), DOT, EPSILON, and SUB.
 {
    double edge1[3], edge2[3], tvec[3], pvec[3], qvec[3];
    double det,inv_det;
    /* find vectors for two edges sharing vert0 */
    SUB(edge1, vert1, vert0);
    SUB(edge2, vert2, vert0);
    /* begin calculating determinant - also used to calculate U parameter */
    CROSS(pvec, dir, edge2);
    /* if determinant is near zero, ray lies in plane of triangle */
    det = DOT(edge1, pvec);
    /* calculate distance from vert0 to ray origin */
    SUB(tvec, orig, vert0);
    inv_det = 1.0 / det;
    CROSS(qvec, tvec, edge1);
    if (det > EPSILON)
    {
       *u = DOT(tvec, pvec);
       if (*u < 0.0 || *u > det)
          return 0;
       /* calculate V parameter and test bounds */
       *v = DOT(dir, qvec);
       if (*v < 0.0 || *u + *v > det)
          return 0;
    }
    else if(det < -EPSILON)
    {
       /* calculate U parameter and test bounds */
       *u = DOT(tvec, pvec);
       if (*u > 0.0 || *u < det)
          return 0;
       /* calculate V parameter and test bounds */
       *v = DOT(dir, qvec) ;
       if (*v > 0.0 || *u + *v < det)
          return 0;
    }
    else return 0;  /* ray is parallell to the plane of the triangle */
    *t = DOT(edge2, qvec) * inv_det;
    (*u) *= inv_det;
    (*v) *= inv_det;
    return 1;
 }
bool rayIntersectsTriangle (double * p, double * d, double * v0, double * v1, double * v2, Vec3D & I)
Definition at line 586 of file Rocon/src/ray-triangle.C.
References intersect_triangle(), j, P_triRay(), and v.
 {
         /*Vec3D org(p[0],p[1],p[2]);
         Vec3D dir(d[0],d[1],d[2]);
         Vec3D ver0(v0[0],v0[1],v0[2]);
         Vec3D ver1(v1[0],v1[1],v1[2]);
         Vec3D ver2(v2[0],v2[1],v2[2]);
         int result = intersect_ray_triangle(org,dir,ver0,ver1,ver2,I);*/
         /*RAYTRI * input = new RAYTRI;
         for(int i =0;i<3;++i)
         {
                 input->org[i] = p[i];
                 input->dir[i] = d[i];
                 input->v0[i] = v0[i];
                 input->v1[i] = v1[i];
                 input->v2[i] = v2[i];
                 input->end[i] = p[i]+d[i];
         }
         int result = c2005(input);*/
         /*double *t,*u,*v;
         t = new double;
         u = new double;
         v = new double;
         *t = *u = *v = 0;
         int result = intersect_triangle(p,d,v0,v1,v2,t,u,v);
         for(int j=0;j<3;j++)
         {
           I[j]=p[j]+ (*t)*d[j];//I[j]=v0[j]+ (*u)*v1[j] + (*v)*v2[j];
         }*/
         int result = P_triRay(p,d,v0,v1,v2,I);
         if(result)
         {       double *t,*u,*v;
                 t = new double;
                 u = new double;
                 v = new double;
                 *t = *u = *v = 0;
                 result = intersect_triangle(p,d,v0,v1,v2,t,u,v);
                 for(int j=0;j<3;j++)
                 {
                   I[j]=p[j]+ (*t)*d[j];
                 }
                 delete t;
                 delete u;
                 delete v;
         }
         return result;
 }