Rocstar: Rocprop.C File Reference
Rocprop.C File Reference
#include "Rocprop.h"
#include "../Rocblas/include/Rocblas.h"
#include "MarkerParticles_3.h"
#include "FaceOffset_3.h"
Functions
void Rocprop_load_module (const char *name)
void Rocprop_unload_module (const char *name)
void rocprop_load_module (const char *name, long int length)
void rocprop_unload_module (const char *name, long int length)
void ROCPROP_LOAD_MODULE (const char *name, long int length)
void ROCPROP_UNLOAD_MODULE (const char *name, long int length)
void rocprop_load_module_ (const char *name, long int length)
void rocprop_unload_module_ (const char *name, long int length)
void ROCPROP_LOAD_MODULE_ (const char *name, long int length)
void ROCPROP_UNLOAD_MODULE_ (const char *name, long int length)
Function Documentation
void Rocprop_load_module (const char * name)
Definition at line 399 of file Rocprop.C.
References Rocprop::load().
 { Rocprop::load( std::string(name)); }
void rocprop_load_module (const char * name, long int length)
Definition at line 405 of file Rocprop.C.
References Rocprop::load().
 { Rocprop::load( std::string(name, length)); }
void ROCPROP_LOAD_MODULE (const char * name, long int length)
Definition at line 410 of file Rocprop.C.
References Rocprop::load().
 { Rocprop::load( std::string(name, length)); }
void rocprop_load_module_ (const char * name, long int length)
Definition at line 415 of file Rocprop.C.
References Rocprop::load().
 { Rocprop::load( std::string(name, length)); }
void ROCPROP_LOAD_MODULE_ (const char * name, long int length)
Definition at line 420 of file Rocprop.C.
References Rocprop::load().
 { Rocprop::load( std::string(name, length)); }
void Rocprop_unload_module (const char * name)
Definition at line 401 of file Rocprop.C.
References Rocprop::unload().
 { Rocprop::unload( std::string(name)); }
void rocprop_unload_module (const char * name, long int length)
Definition at line 407 of file Rocprop.C.
References Rocprop::unload().
 { Rocprop::unload( std::string(name, length)); }
void ROCPROP_UNLOAD_MODULE (const char * name, long int length)
Definition at line 412 of file Rocprop.C.
References Rocprop::unload().
 { Rocprop::unload( std::string(name, length)); }
void rocprop_unload_module_ (const char * name, long int length)
Definition at line 417 of file Rocprop.C.
References Rocprop::unload().
 { Rocprop::unload( std::string(name, length)); }
void ROCPROP_UNLOAD_MODULE_ (const char * name, long int length)
Definition at line 422 of file Rocprop.C.
References Rocprop::unload().
 { Rocprop::unload( std::string(name, length)); }