Rocstar: RFLO_SendBoundaryValues.F90 File Reference
rocstar/RFLO_SendBoundaryValues.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_sendboundaryvalues (region, initialize)
Function/Subroutine Documentation
subroutine rflo_sendboundaryvalues (type(t_region) region, logical initialize)
Definition at line 44 of file rocstar/RFLO_SendBoundaryValues.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, m_rocburn_2d::initialize(), inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, mixtperf_d_prt(), mixtperf_r_m(), plag_setsizegenx(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), rflo_getpatchindicesnodes(), and sqrt().
Referenced by explicitmultistage(), rflo_dualtimestepping(), rflo_flowsolver(), rflo_flowsolverdummy(), rflo_initflowsolver(), rflo_timestepping(), and updateboundaryconditionsmp().