Rocstar: Rocsurf.C File Reference
Rocsurf.C File Reference
#include "Rocsurf.h"
#include "roccom.h"
#include "Manifold_2.h"
Functions
void Rocsurf_load_module (const char *mname)
void Rocsurf_unload_module (const char *mname)
void rocsurf_load_module (const char *mname, long int length)
void rocsurf_unload_module (const char *mname, long int length)
void ROCSURF_LOAD_MODULE (const char *mname, long int length)
void ROCSURF_UNLOAD_MODULE (const char *mname, long int length)
void rocsurf_load_module_ (const char *mname, long int length)
void rocsurf_unload_module_ (const char *mname, long int length)
void ROCSURF_LOAD_MODULE_ (const char *mname, long int length)
void ROCSURF_UNLOAD_MODULE_ (const char *mname, long int length)
Function Documentation
void Rocsurf_load_module (const char * mname)
Definition at line 229 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( mname); }
void rocsurf_load_module (const char * mname, long int length)
Definition at line 237 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( std::string(mname, length)); }
void ROCSURF_LOAD_MODULE (const char * mname, long int length)
Definition at line 243 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( std::string(mname, length)); }
void rocsurf_load_module_ (const char * mname, long int length)
Definition at line 249 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( std::string(mname, length)); }
void ROCSURF_LOAD_MODULE_ (const char * mname, long int length)
Definition at line 255 of file Rocsurf.C.
References Rocsurf::load().
 { Rocsurf::load( std::string(mname, length)); }
void Rocsurf_unload_module (const char * mname)
Definition at line 232 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( mname); }
void rocsurf_unload_module (const char * mname, long int length)
Definition at line 240 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( std::string(mname, length)); }
void ROCSURF_UNLOAD_MODULE (const char * mname, long int length)
Definition at line 246 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( std::string(mname, length)); }
void rocsurf_unload_module_ (const char * mname, long int length)
Definition at line 252 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( std::string(mname, length)); }
void ROCSURF_UNLOAD_MODULE_ (const char * mname, long int length)
Definition at line 258 of file Rocsurf.C.
References Rocsurf::unload().
 { Rocsurf::unload( std::string(mname, length)); }