Rocstar: rocstar.C File Reference
rocstar.C File Reference
#include <iostream>
#include <cstring>
#include <cstdlib>
#include "roccom.h"
#include "splash.h"
Classes
struct Command_Options
Functions
void rocstar_driver (int, int, bool)
void ReportUsage ()
void parse_commandline (int argc, char *argv[], Command_Options &opts)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 99 of file rocstar.C.
References COM_finalize(), COM_init(), Command_Options::debug, MPI_COMM_WORLD, Command_Options::nrun, parse_commandline(), rank, Command_Options::remeshed, rocstar_driver(), and Command_Options::verbose.
{
   /* Start MPI. */
   MPI_Init( &argc, &argv);
   int rank;
   MPI_Comm_rank(MPI_COMM_WORLD,&rank);
 #ifdef ROCPROF
   Rocprof_Init("Rocstar",rank);
 #endif
   /* Initialize Roccom */
   COM_init( &argc, &argv);
   Command_Options opts;
   parse_commandline( argc, argv, opts);
   int nrun = 1;
   rocstar_driver( opts.verbose, opts.remeshed, opts.debug);
   while (nrun < opts.nrun){
     if(rank == 0) std::cout << " Rocstar automatic restart " << nrun++ << std::endl;
     rocstar_driver(opts.verbose,opts.remeshed, opts.debug);
   }
   /* Finalize Roccom. */
   COM_finalize();
 #ifdef ROCPROF
   Rocprof_Finalize(true);
 #endif
   /* Close down MPI. */
   MPI_Finalize();
   return 0;
 }
void parse_commandline (int argc, char * argv[], Command_Options & opts)
Definition at line 66 of file rocstar.C.
References Command_Options::debug, i, MPI_COMM_WORLD, Command_Options::nrun, rank, Command_Options::remeshed, ReportUsage(), RocstarSplash(), and Command_Options::verbose.
Referenced by main().
{
   int rank;
   MPI_Comm_rank(MPI_COMM_WORLD,&rank);
   for ( int i=1; i<argc; ++i) {
     if ( std::strcmp(argv[i], "-v") == 0) {
       if ( argc>i+1 && argv[i+1][0]>='0' && argv[i+1][0]<='9')
       { opts.verbose = std::atoi( argv[i+1]); ++i; }
     }
     else if ( std::strcmp(argv[i], "-remeshed") == 0) {
       opts.remeshed = 1;
     }
     else if ( std::strcmp(argv[i], "-r") == 0) {
       opts.nrun = 1;
       if ( argc>i+1 && argv[i+1][0]>='1' && argv[i+1][0]<='9')
       { opts.nrun = std::atoi( argv[i+1]); ++i; }
     }
     else if ( std::strcmp(argv[i], "-d") == 0){
       opts.debug = true;
     }
     else if ( std::strcmp(argv[i], "-debug") == 0){
       opts.debug = true;
     }
     else if (rank == 0) {
       if(std::strcmp(argv[i],"-h"))
         std::cerr << "Rocstar: Unknown option " << argv[i] << std::endl;
       ReportUsage();
     }
   }
   if(opts.verbose > 0 && rank == 0)
     std::cout << RocstarSplash << std::endl;
 }
void ReportUsage ()
Definition at line 51 of file rocstar.C.
Referenced by parse_commandline().
 {
   std::cout << "rocstar [-h -d -v [0-2] -r [n] ]" << std::endl
             << std::endl
             << "Rocstar Help" << std::endl
             << "------------------------" << std::endl
             << " -h: help - prints this message" << std::endl
             << " -v: verbosity - optional verbosity level (default = 1)" << std::endl
             << " -r: runs - number of times to automatically restart (default = 0)" << std::endl
             << " -d: debug - turns on debugging messages for the run" << std::endl
             << "------------------------" << std::endl;
 }
void rocstar_driver (int , int , bool)
Definition at line 561 of file rocstar_driver.C.
References Coupling::check_convergence(), check_for_interrupt(), COM_print_profile(), COM_set_debug(), COM_set_profiling(), COM_set_verbose(), COM_UNLOAD_MODULE_STATIC_DYNAMIC, Control_parameters::communicator, Control_parameters::controlDebug, Control_parameters::controlVerb, create_coupling(), Control_parameters::cur_step, Control_parameters::current_dump, Control_parameters::current_time, Coupling::finalize(), RocBlas::init(), Coupling::init_convergence(), Coupling::initialize(), Control_parameters::LastOutputStep, Control_parameters::LastOutputTime, MAN_DEBUG, Control_parameters::maxNumPredCorrCycles, Control_parameters::maxNumTimeSteps, min(), MPI_COMM_WORLD, Control_parameters::myRank, Control_parameters::output_module, Coupling::output_restart_files(), Coupling::output_visualization_files(), Control_parameters::print(), RocmanControl_parameters::print(), Coupling::ProcessInterrupt(), reached_restartdump_time(), reached_simulation_time(), reached_visdump_time(), Control_parameters::read(), RocmanControl_parameters::read(), Coupling::read_restart_info(), RocmanControl_parameters::remeshed, Coupling::restart_at_time(), Coupling::run(), Coupling::schedule(), cimg_library::cimg::strcasecmp(), Control_parameters::time_step, Control_parameters::timingDataFile, Coupling::update_distances(), Coupling::update_integrals(), Coupling::write_restart_info(), and Control_parameters::zoomFactor.
Referenced by main().
{
   // Read in config files to initialize param
   Control_parameters  *param_ptr = new Control_parameters;
   Control_parameters  &param = *param_ptr;
   param.read();
   int comm_rank = param.myRank;
   param.controlVerb = verb;
   param.controlDebug = debug;
   // Read in rocman config files to initialize param
   RocmanControl_parameters  *rocman_param_ptr = new RocmanControl_parameters;
   RocmanControl_parameters  &rocman_param = *rocman_param_ptr;
   rocman_param.read( param.communicator, comm_rank);
   rocman_param.remeshed = remeshed;
   if ( comm_rank == 0 ) {
     if(debug)
       printf("Rocstar: Call CouplingInitialize\n");
     if(verb > 1){
      param.print();
      rocman_param.print();
     }
     COM_set_verbose( verb);  // shift by 2 to depress first level printing
     COM_set_debug( debug);
   }
   MPI_Barrier(MPI_COMM_WORLD);
   //  if(!comm_rank)
   //    std::cout << "Rocstar: creating coupling." << std::endl;
   // Construct coupling object and schedule the actions
   Coupling *coup = create_coupling( param, rocman_param);
   if(!coup){
     if(comm_rank == 0)
       std::cerr << "Rocstar: Error: No coupling created. Exiting." << std::endl;
     return;
   }
   coup->schedule();
   //  std::cout << "Rocstar(" << comm_rank << "): coupling created." << std::endl;
   MPI_Barrier(MPI_COMM_WORLD);
   //  if(!comm_rank)
   //    std::cout << "Rocstar: All couplings created." << std::endl;
   // visualization
   //  std::string fname = std::string(param.coupling_scheme) + ".gdl";
   //  coup->print(fname.c_str());
   // Load other service modules
   RocBlas::init();
   MPI_Barrier(MPI_COMM_WORLD);
   //  if(!comm_rank)
   //    std::cout << "Rocstar: Rocblas initd." << std::endl;
    // Have Roccom profile all the calls to COM_call_function.
   COM_set_profiling( 1);
   MPI_Barrier(MPI_COMM_WORLD);
   //  if(!comm_rank)
   //    std::cout << "Rocstar: profiling set." << std::endl;
   int with_pciter = (param.maxNumPredCorrCycles > 1);
   if ( comm_rank == 0 && verb > 1) {
     std::cout << "Rocstar: The maximum number of PC-iterations is " << param.maxNumPredCorrCycles << std::endl;
   }
   // in case of restarting, reset cur_step and current_time from Restart.txt
   coup->read_restart_info();
   MPI_Barrier(MPI_COMM_WORLD);
   if(!comm_rank && debug)
     std::cout << "Rocstar: Read restart information, initializing" << std::endl;
   // call input, init and run_initactions
   coup->initialize();
   //  std::cout << "Rocstar(" << comm_rank << "): Coupling initialized." << std::endl;
   MPI_Barrier(MPI_COMM_WORLD);
   //  if(!comm_rank)
   //    std::cout << "Rocstar: All couplings initd" << std::endl;
   if ( param.current_time == 0.0) {
     MPI_Barrier(param.communicator);
     if(comm_rank == 0 && verb > 0)
       std::cout << "Rocstar: Performing time 0 dump..." << std::endl;
     coup->update_integrals( param.current_time);
     coup->update_distances( param.current_time);
     coup->output_restart_files( param.current_time);
     MPI_Barrier(param.communicator);
     if(comm_rank == 0 && debug)
       std::cout << "Rocstar: done." << std::endl;
   }
   MPI_Barrier(param.communicator);
   param.LastOutputTime = param.current_time;
   param.LastOutputStep = param.cur_step;
   if (comm_rank == 0 && verb > 0) {
     std::cout << "Rocstar: Starting with step " << param.cur_step+1 << ", at time " << param.current_time << std::endl;
   }
   char  header[100];
   sprintf(header, "************** Initialization times at time step %d *****************\n", param.cur_step);
   COM_print_profile( param.timingDataFile.c_str(), header);
   COM_set_profiling( 1);     // Reset profiler;
   if (param.current_time == 0.0)
     coup->write_restart_info( param.current_time, 1);
     // March through time until either the specified maximum time or the maximum
     // number of time steps have been exceeded (whichever comes first).
   int InterfaceConverged;
   MPI_Barrier(param.communicator);
   //  if(comm_rank == 0)
   //    std::cout << "Rocstar: Preparig to step..." << std::endl;
   while ( !reached_simulation_time(param) ) {
     param.cur_step ++;
     for (int iPredCorr = 1; iPredCorr <= param.maxNumPredCorrCycles; iPredCorr++)
     {
       if ( comm_rank == 0  && verb > 0) {
         std::cout << "Rocstar:" << std::endl
                   << "Rocstar: ================================================================" << std::endl
                   << "Rocstar: System Time Step : " << param.cur_step << "   PC(" << iPredCorr << ")" << std::endl
                   << "Rocstar: ================================================================" << std::endl
                   << "Rocstar:" << std::endl
                   << "Rocstar: CurrentTime, CurrentTimeStep";
         if(verb > 1)
           std::cout << ", ZoomFactor";
         std::cout << ": "
                   << param.current_time << " "
                   << param.time_step << " ";
         if(verb > 1)
           std::cout << param.zoomFactor;
         std::cout << std::endl << "Rocstar:" << std::endl;
       }
       MPI_Barrier(param.communicator);
       //      if(comm_rank == 0)
       //        std::cout << "Rocstar: initializing convergence checking" << std::endl;
       if ( with_pciter)
         coup->init_convergence( iPredCorr);
       MPI_Barrier(param.communicator);
       //      if(comm_rank == 0)
       //        std::cout << "Rocstar: convergence checking initialized" << std::endl;
       // invoke time integration of coupling scheme by passing in
       // current time and desired time step and obtaining new time
       MPI_Barrier(param.communicator);
       //      if(comm_rank == 0)
       //        std::cout << "Rocstar: Running coupling.." << std::endl;
       double new_current_time = coup->run( param.current_time, param.time_step,
                                            iPredCorr, param.zoomFactor);
       // Check for interrupt
       check_for_interrupt(coup,param);
       //      std::cout << comm_rank << ": solver done on this rank." << std::endl;
       MPI_Barrier(param.communicator);
       //      if(comm_rank == 0)
       //        std::cout << "Rocstar: coupling done." << std::endl;
       InterfaceConverged = 1;
       if ( with_pciter)
         InterfaceConverged = coup->check_convergence();
       if ( comm_rank == 0 && debug )
         std::cout << "Rocstar:" << std::endl
                   << "Rocstar: iPredCorr = " << iPredCorr << " is done" << std::endl;
       if ( InterfaceConverged ) {
           param.current_time = new_current_time;
           if ( comm_rank == 0 && verb > 1)
               std::cout << "Rocstar: Success: predictor-corrector converged at time " << param.current_time << std::endl;
           break;
       }
       else {
           if ( comm_rank == 0 && debug ) {
             std::cout << "Rocstar:" << std::endl
                       << "Rocstar: Interface has -NOT- converged!" << std::endl
                       << "Rocstar: iPredCorr = " << iPredCorr << " is done" << std::endl;
           }
       }
     }   // end of iPredCorr
     // New function to parse flags set by interrupt returns false if no action
     if(coup->ProcessInterrupt())
       continue;
     if ( !InterfaceConverged) {
       if (comm_rank == 0)
         std::cerr << "Rocstar: Disaster: predictor-corrector did not converge" << std::endl;
       MPI_Abort( MPI_COMM_WORLD, -1);
     }
 #if 0
        // warm restart at step 3
     if (param.cur_step == 320) {
         static int didit = 0;     // do it only once
         if (!didit) {
           coup->restart_at_time(param.LastOutputTime, param.LastOutputStep);
           didit = 1;
           continue;               // skip the rest !
         }
     }
 #endif
     // if reached time for restart dump
     if ( reached_restartdump_time( param) ) {
       MPI_Barrier(param.communicator);
       // Compute integrals and write them into files for conservation-check
       coup->update_integrals( param.current_time);
       coup->update_distances( param.current_time);
       // invoke restart output (as well as visualization data)
       if(comm_rank == 0 && verb > 0)
         std::cout << "Rocstar: Dumping restart files... " << std::endl;
       coup->output_restart_files( param.current_time);
       coup->write_restart_info( param.current_time, param.cur_step+1);
       param.LastOutputTime = param.current_time;
       param.LastOutputStep = param.cur_step;
       param.current_dump++;
       MPI_Barrier(param.communicator);
       //if(comm_rank == 0)
         //std::cout << "done." << std::endl;
     }
     else if ( reached_visdump_time( param)) {
       if(comm_rank == 0 && verb > 0)
         std::cout << "Rocstar: Dumping coupling viz files." << std::endl;
       // output visualization files
       coup->output_visualization_files( param.current_time);
     }
       // Write out profile data
     if ( param.cur_step <= 100 || param.LastOutputTime == param.current_time) {
       sprintf(header, "************** Solver times up to time step %d since last output *********\n", param.cur_step);
       COM_print_profile( param.timingDataFile.c_str(), header);
       COM_set_profiling( 1);     // Reset profiler;
     }
     //if(comm_rank == 0)
       //std::cout << "Rocstar:" << std::endl;
   }   // end time step
     // Write final solution.
   if (param.current_time != param.LastOutputTime) {
     MPI_Barrier(param.communicator);
     if(comm_rank == 0 && verb > 0)
       std::cout << "Rocstar: Performing final dump..." << std::endl;
     coup->output_restart_files( param.current_time);
     coup->write_restart_info( param.current_time, std::min(param.cur_step, param.maxNumTimeSteps)+1);
     MPI_Barrier(param.communicator);
     if(comm_rank == 0 && debug)
       std::cout << "Rocstar: done." << std::endl;
   }
     // Finalize coupling
   coup->finalize();
 #ifdef WITH_PANDA
     // unload Rocpanda to exit gracefully
   if ( strcasecmp(param.output_module, "Rocpanda") == 0) {
     MAN_DEBUG(3, ("[%d] Rocstar: unload_module Rocpanda.\n", param.myRank));
     COM_UNLOAD_MODULE_STATIC_DYNAMIC( Rocpanda, "OUT");
   }
 #endif
     // Write out the final profile data
   sprintf(header, "************** Finalization times after time step %d *****************\n", param.cur_step);
   COM_print_profile( param.timingDataFile.c_str(), header);
   delete coup;
 }