Rocstar: RVAV_Main.F90 File Reference
RVAV_Main.F90 File Reference
Functions/Subroutines
program rocvav_post
Function/Subroutine Documentation
program rocvav_post ()
Definition at line 45 of file RVAV_Main.F90.
References buildversionstring(), moderror::deregisterfunction(), moderror::errorstop(), i, j, k, max(), min(), COM_exception::msg(), readinputfile(), moderror::registerfunction(), rflo_derivedinputvalues(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), rflo_initinputvalues(), rflo_readgridregion(), rflo_readregiontopology(), rflo_readsolutionregion(), rvav_computeanalyticalsolution(), rvav_computeerror(), rvav_computesimilarfield(), rvav_extractvariables(), rvav_plotresults(), rvav_readfilestream1(), rvav_readfilestream2(), rvav_readinputfile(), and StopWatch::stop().