Rocstar: RVAV_BlasiusSolution.F90 File Reference
RVAV_BlasiusSolution.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rvav_blasiussolution (fname, regionsS1)
subroutine linintpol (nFine, jTilde, nComp, crsCoord, finCoord, varFin, varVal)
Function/Subroutine Documentation
subroutine rvav_blasiussolution::linintpol (integer nFine, integer jTilde, integer nComp, real(rfreal) crsCoord, real(rfreal), dimension(nfine) finCoord, real(rfreal), dimension(ncomp,nfine) varFin, real(rfreal), dimension(ncomp) varVal)
Definition at line 251 of file RVAV_BlasiusSolution.F90.
Referenced by rvav_blasiussolution().
subroutine rvav_blasiussolution (character(*) fname, type (t_region), dimension(:), pointer regionsS1)
Definition at line 43 of file RVAV_BlasiusSolution.F90.
References moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, setup_py::grid(), i, idcbeg, idcend, ipcbeg, ipcend, j, jdcbeg, jdcend, jpcbeg, jpcend, k, kdcbeg, kpcbeg, linintpol(), max(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensphys(), sqrt(), and Attribute::status().
Referenced by rvav_computeanalyticalsolution().