Rocstar: RVAV_ExtractVariables.F90 File Reference
RVAV_ExtractVariables.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rvav_extractvariables (global, region, ibeg, iend, ijump, jbeg, jend, jjump, kbeg, kend, kjump, iCOff, ijCOff, variableIndex, fileType, indCp, indMol, ev)
Function/Subroutine Documentation
subroutine rvav_extractvariables (type(t_global), pointer global, type(t_region) region, integer ibeg, integer iend, integer ijump, integer jbeg, integer jend, integer jjump, integer kbeg, integer kend, integer kjump, integer iCOff, integer ijCOff, integer variableIndex, integer fileType, integer indCp, integer indMol, real(rfreal), dimension(:,:,:), pointer ev)
Definition at line 49 of file RVAV_ExtractVariables.F90.
References moderror::deregisterfunction(), setup_py::grid(), ibeg, ic, iend, jbeg, jend, kbeg, moderror::registerfunction(), rflo_getcelloffset(), and sqrt().
Referenced by rocvav_post().