Rocstar: RVAV_ReadFileStream2Comput.F90 File Reference
RVAV_ReadFileStream2Comput.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rvav_readfilestream2comput (regionsS1, regionsS2)
Function/Subroutine Documentation
subroutine rvav_readfilestream2comput (type (t_region), dimension(:), pointer regionsS1, type (t_region), dimension(:), pointer regionsS2)
Definition at line 45 of file RVAV_ReadFileStream2Comput.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, idcbeg, idcend, idnbeg, idnend, j, jdcbeg, jdcend, jdnbeg, jdnend, k, kdcbeg, kdnbeg, max(), min(), mixtureproperties(), COM_exception::msg(), readinputfile(), moderror::registerfunction(), rflo_derivedinputvalues(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), rflo_initinputvalues(), rflo_readgridregion(), rflo_readregiontopology(), and rflo_readsolutionregion().
Referenced by rvav_readfilestream2().