Rocstar: RVAV_ReadFileStream1.F90 File Reference
RVAV_ReadFileStream1.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rvav_readfilestream1 (regionsS1)
Function/Subroutine Documentation
subroutine rvav_readfilestream1 (type (t_region), dimension(:), pointer regionsS1)
Definition at line 43 of file RVAV_ReadFileStream1.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, idcbeg, idcend, idnbeg, idnend, j, jdcbeg, jdcend, jdnbeg, jdnend, k, kdcbeg, kdnbeg, max(), min(), mixtureproperties(), readinputfile(), moderror::registerfunction(), rflo_derivedinputvalues(), rflo_getcelloffset(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), rflo_initinputvalues(), rflo_readgridregion(), rflo_readregiontopology(), rflo_readsolutionregion(), and StopWatch::stop().
Referenced by rocvav_post().