Rocstar: scale.f90 File Reference
scale.f90 File Reference
Functions/Subroutines
program scale_mesh
Function/Subroutine Documentation
program scale_mesh ()
Definition at line 53 of file scale.f90.
References find_nodes(), i, j, Aff_transformation_repS2< FT >::print(), read_frac(), read_io_files(), Transfer_base::scale(), Attribute::status(), translate(), Attribute::unit(), and write_output_2().