Rocstar: Segment_2_Segment_2_intersection.h File Reference
Segment_2_Segment_2_intersection.h File Reference
#include <CGAL/Segment_2.h>
#include <CGAL/Point_2.h>
#include <CGAL/utils.h>
#include <CGAL/number_utils.h>
#include <cassert>
#include <CGAL/predicates_on_points_2.h>
#include <CGAL/Line_2.h>
#include <CGAL/Line_2_Line_2_intersection.h>
#include <CGAL/Object.h>
Classes
class Segment_2_Segment_2_pair< R >
Namespaces
CGAL
Functions
template<class R >
bool do_intersect (const Segment_2< R > &seg1, const Segment_2< R > &seg2)
template<class PT >
bool seg_seg_do_intersect_crossing (PT const &p1, PT const &p2, PT const &p3, PT const &p4)
template<class PT >
bool seg_seg_do_intersect_contained (PT const &p1, PT const &p2, PT const &p3, PT const &p4)
template<class R >
bool do_intersect (const Segment_2< R > &seg1, const Segment_2< R > &seg2)
template<class R >
CGAL_END_NAMESPACE
CGAL_BEGIN_NAMESPACE Object intersection (const Segment_2< R > &seg1, const Segment_2< R > &seg2)
Function Documentation
bool do_intersect (const Segment_2< R > & seg1, const Segment_2< R > & seg2) inline
Definition at line 242 of file Segment_2_Segment_2_intersection.h.
References compare_lexicographically_xy(), EQUAL, LARGER, lexicographically_xy_smaller(), lexicographically_yx_smaller(), CGAL::seg_seg_do_intersect_contained(), CGAL::seg_seg_do_intersect_crossing(), SMALLER, Segment_2< R, T >::source(), and Segment_2< R, T >::target().
Referenced by Triangulation::is_diagonalie().
 {
     typename R::Point_2 const & A1 = seg1.source();
     typename R::Point_2 const & A2 = seg1.target();
     typename R::Point_2 const & B1 = seg2.source();
     typename R::Point_2 const & B2 = seg2.target();
     if (lexicographically_yx_smaller(A1,A2)) {
         if (lexicographically_yx_smaller(B1,B2)) {
             if (lexicographically_yx_smaller(A2,B1)
              || lexicographically_yx_smaller(B2,A1))
                 return false;
         } else {
             if (lexicographically_yx_smaller(A2,B2)
              || lexicographically_yx_smaller(B1,A1))
                 return false;
         }
     } else {
         if (lexicographically_yx_smaller(B1,B2)) {
             if (lexicographically_yx_smaller(A1,B1)
              || lexicographically_yx_smaller(B2,A2))
                 return false;
         } else {
             if (lexicographically_yx_smaller(A1,B2)
              || lexicographically_yx_smaller(B1,A2))
                 return false;
         }
     }
     if (lexicographically_xy_smaller(A1,A2)) {
         if (lexicographically_xy_smaller(B1,B2)) {
             switch(compare_lexicographically_xy(A1,B1)) {
             case SMALLER:
                 switch(compare_lexicographically_xy(A2,B1)) {
                 case SMALLER:
                     return false;
                 case EQUAL:
                     return true;
                 case LARGER:
                     switch(compare_lexicographically_xy(A2,B2)) {
                     case SMALLER:
                         return seg_seg_do_intersect_crossing(A1,A2,B1,B2);
                     case EQUAL:
                         return true;
                     case LARGER:
                         return seg_seg_do_intersect_contained(A1,A2,B1,B2);
                     }
                 }
             case EQUAL:
                 return true;
             case LARGER:
                 switch(compare_lexicographically_xy(B2,A1)) {
                 case SMALLER:
                     return false;
                 case EQUAL:
                     return true;
                 case LARGER:
                     switch(compare_lexicographically_xy(B2,A2)) {
                     case SMALLER:
                         return seg_seg_do_intersect_crossing(B1,B2,A1,A2);
                     case EQUAL:
                         return true;
                     case LARGER:
                         return seg_seg_do_intersect_contained(B1,B2,A1,A2);
                     }
                 }
             }
         } else {
             switch(compare_lexicographically_xy(A1,B2)) {
             case SMALLER:
                 switch(compare_lexicographically_xy(A2,B2)) {
                 case SMALLER:
                     return false;
                 case EQUAL:
                     return true;
                 case LARGER:
                     switch(compare_lexicographically_xy(A2,B1)) {
                     case SMALLER:
                         return seg_seg_do_intersect_crossing(A1,A2,B2,B1);
                     case EQUAL:
                         return true;
                     case LARGER:
                         return seg_seg_do_intersect_contained(A1,A2,B2,B1);
                     }
                 }
             case EQUAL:
                 return true;
             case LARGER:
                 switch(compare_lexicographically_xy(B1,A1)) {
                 case SMALLER:
                     return false;
                 case EQUAL:
                     return true;
                 case LARGER:
                     switch(compare_lexicographically_xy(B1,A2)) {
                     case SMALLER:
                         return seg_seg_do_intersect_crossing(B2,B1,A1,A2);
                     case EQUAL:
                         return true;
                     case LARGER:
                         return seg_seg_do_intersect_contained(B2,B1,A1,A2);
                     }
                 }
             }
         }
     } else {
         if (lexicographically_xy_smaller(B1,B2)) {
             switch(compare_lexicographically_xy(A2,B1)) {
             case SMALLER:
                 switch(compare_lexicographically_xy(A1,B1)) {
                 case SMALLER:
                     return false;
                 case EQUAL:
                     return true;
                 case LARGER:
                     switch(compare_lexicographically_xy(A1,B2)) {
                     case SMALLER:
                         return seg_seg_do_intersect_crossing(A2,A1,B1,B2);
                     case EQUAL:
                         return true;
                     case LARGER:
                         return seg_seg_do_intersect_contained(A2,A1,B1,B2);
                     }
                 }
             case EQUAL:
                 return true;
             case LARGER:
                 switch(compare_lexicographically_xy(B2,A2)) {
                 case SMALLER:
                     return false;
                 case EQUAL:
                     return true;
                 case LARGER:
                     switch(compare_lexicographically_xy(B2,A1)) {
                     case SMALLER:
                         return seg_seg_do_intersect_crossing(B1,B2,A2,A1);
                     case EQUAL:
                         return true;
                     case LARGER:
                         return seg_seg_do_intersect_contained(B1,B2,A2,A1);
                     }
                 }
             }
         } else {
             switch(compare_lexicographically_xy(A2,B2)) {
             case SMALLER:
                 switch(compare_lexicographically_xy(A1,B2)) {
                 case SMALLER:
                     return false;
                 case EQUAL:
                     return true;
                 case LARGER:
                     switch(compare_lexicographically_xy(A1,B1)) {
                     case SMALLER:
                         return seg_seg_do_intersect_crossing(A2,A1,B2,B1);
                     case EQUAL:
                         return true;
                     case LARGER:
                         return seg_seg_do_intersect_contained(A2,A1,B2,B1);
                     }
                 }
             case EQUAL:
                 return true;
             case LARGER:
                 switch(compare_lexicographically_xy(B1,A2)) {
                 case SMALLER:
                     return false;
                 case EQUAL:
                     return true;
                 case LARGER:
                     switch(compare_lexicographically_xy(B1,A1)) {
                     case SMALLER:
                         return seg_seg_do_intersect_crossing(B2,B1,A2,A1);
                     case EQUAL:
                         return true;
                     case LARGER:
                         return seg_seg_do_intersect_contained(B2,B1,A2,A1);
                     }
                 }
             }
         }
     }
     assert(false);
     return false;
 }
CGAL_END_NAMESPACE CGAL_BEGIN_NAMESPACE Object intersection (const Segment_2< R > & seg1, const Segment_2< R > & seg2)
Definition at line 602 of file Segment_2_Segment_2_intersection.h.
 {
     typedef Segment_2_Segment_2_pair<R> is_t;
     is_t ispair(&seg1, &seg2);
     switch (ispair.intersection_type()) {
     case is_t::NO:
     default:
         return Object();
     case is_t::POINT: {
         Point_2<R> pt;
         ispair.intersection(pt);
         return Object(new Wrapper< Point_2<R> >(pt));
     }
     case is_t::SEGMENT: {
         Segment_2<R> iseg;
         ispair.intersection(iseg);
         return Object(new Wrapper< Segment_2<R> >(iseg));
     }
     }
 }