Rocstar: shcalc_3d10.f90 File Reference
shcalc_3d10.f90 File Reference
Functions/Subroutines
subroutine shcalc_3d10 (shfn, shdx, dv, dvsum, shdx_av, meshpos, ndim, nnode, nintk, xi, eta, zeta, shdxi, wsp2)
Function/Subroutine Documentation
subroutine shcalc_3d10 (real*8, dimension(nnode,nintk) shfn, real*8, dimension(ndim,nnode,nintk) shdx, real*8, dimension(nintk) dv, real*8 dvsum, real*8, dimension(ndim,nnode) shdx_av, real*8, dimension(ndim,nnode) meshpos, integer ndim, integer nnode, integer nintk, real*8, dimension(nintk) xi, real*8, dimension(nintk) eta, real*8, dimension(nintk) zeta, real*8, dimension(ndim,nnode,nintk) shdxi, real*8, dimension(3,3) wsp2)
Definition at line 65 of file shcalc_3d10.f90.
References ainv(), i, j, Color::r(), s, and Matrix3D::zero().
Referenced by v3d10_ale(), and v3d10_r_bar().