Rocstar: sign_of_determinant.h File Reference
sign_of_determinant.h File Reference
#include <CGAL/determinant.h>
Functions
template<class FT >
CGAL_BEGIN_NAMESPACE Sign sign_of_determinant2x2 (const FT &a00, const FT &a01, const FT &a10, const FT &a11)
template<class FT >
Sign sign_of_determinant3x3 (const FT &a00, const FT &a01, const FT &a02, const FT &a10, const FT &a11, const FT &a12, const FT &a20, const FT &a21, const FT &a22)
template<class FT >
Sign sign_of_determinant4x4 (const FT &a00, const FT &a01, const FT &a02, const FT &a03, const FT &a10, const FT &a11, const FT &a12, const FT &a13, const FT &a20, const FT &a21, const FT &a22, const FT &a23, const FT &a30, const FT &a31, const FT &a32, const FT &a33)
template<class FT >
CGAL_KERNEL_LARGE_INLINE Sign sign_of_determinant5x5 (const FT &a00, const FT &a01, const FT &a02, const FT &a03, const FT &a04, const FT &a10, const FT &a11, const FT &a12, const FT &a13, const FT &a14, const FT &a20, const FT &a21, const FT &a22, const FT &a23, const FT &a24, const FT &a30, const FT &a31, const FT &a32, const FT &a33, const FT &a34, const FT &a40, const FT &a41, const FT &a42, const FT &a43, const FT &a44)
template<class FT >
CGAL_KERNEL_LARGE_INLINE Sign sign_of_determinant6x6 (const FT &a00, const FT &a01, const FT &a02, const FT &a03, const FT &a04, const FT &a05, const FT &a10, const FT &a11, const FT &a12, const FT &a13, const FT &a14, const FT &a15, const FT &a20, const FT &a21, const FT &a22, const FT &a23, const FT &a24, const FT &a25, const FT &a30, const FT &a31, const FT &a32, const FT &a33, const FT &a34, const FT &a35, const FT &a40, const FT &a41, const FT &a42, const FT &a43, const FT &a44, const FT &a45, const FT &a50, const FT &a51, const FT &a52, const FT &a53, const FT &a54, const FT &a55)
Function Documentation
CGAL_BEGIN_NAMESPACE Sign sign_of_determinant2x2 (const FT & a00, const FT & a01, const FT & a10, const FT & a11) inline
Definition at line 63 of file sign_of_determinant.h.
References CGAL_NTS, and CGAL::compare().
Referenced by collinearC3(), compare_angle_with_x_axisC2(), compare_xC2(), compare_y_at_xC2(), equal_directionC2(), equal_directionC3(), equal_lineC2(), Aff_transformation_repS2< FT >::is_even(), orientationC2(), and side_of_oriented_circleC2().
 {
   return
     static_cast<Sign>(static_cast<int>(CGAL_NTS compare( a00*a11, a10*a01)));
 }
Sign sign_of_determinant3x3 (const FT & a00, const FT & a01, const FT & a02, const FT & a10, const FT & a11, const FT & a12, const FT & a20, const FT & a21, const FT & a22) inline
Definition at line 73 of file sign_of_determinant.h.
References CGAL_NTS, det3x3_by_formula(), and sign().
Referenced by cmp_signed_dist_to_planeC3(), compare_y_at_xC2(), Aff_transformation_repS3< FT >::is_even(), and orientationC3().
 {
   return CGAL_NTS sign(det3x3_by_formula(a00, a01, a02,
                                          a10, a11, a12,
                                          a20, a21, a22));
 }
Sign sign_of_determinant4x4 (const FT & a00, const FT & a01, const FT & a02, const FT & a03, const FT & a10, const FT & a11, const FT & a12, const FT & a13, const FT & a20, const FT & a21, const FT & a22, const FT & a23, const FT & a30, const FT & a31, const FT & a32, const FT & a33) inline
Definition at line 85 of file sign_of_determinant.h.
References CGAL_NTS, det4x4_by_formula(), and sign().
Referenced by side_of_oriented_sphereC3().
 {
   return CGAL_NTS sign(det4x4_by_formula(a00, a01, a02, a03,
                                          a10, a11, a12, a13,
                                          a20, a21, a22, a23,
                                          a30, a31, a32, a33));
 }
CGAL_KERNEL_LARGE_INLINE Sign sign_of_determinant5x5 (const FT & a00, const FT & a01, const FT & a02, const FT & a03, const FT & a04, const FT & a10, const FT & a11, const FT & a12, const FT & a13, const FT & a14, const FT & a20, const FT & a21, const FT & a22, const FT & a23, const FT & a24, const FT & a30, const FT & a31, const FT & a32, const FT & a33, const FT & a34, const FT & a40, const FT & a41, const FT & a42, const FT & a43, const FT & a44)
Definition at line 100 of file sign_of_determinant.h.
References CGAL_NTS, det5x5_by_formula(), and sign().
 {
   return CGAL_NTS sign(det5x5_by_formula(a00, a01, a02, a03, a04,
                                          a10, a11, a12, a13, a14,
                                          a20, a21, a22, a23, a24,
                                          a30, a31, a32, a33, a34,
                                          a40, a41, a42, a43, a44));
 }
CGAL_KERNEL_LARGE_INLINE Sign sign_of_determinant6x6 (const FT & a00, const FT & a01, const FT & a02, const FT & a03, const FT & a04, const FT & a05, const FT & a10, const FT & a11, const FT & a12, const FT & a13, const FT & a14, const FT & a15, const FT & a20, const FT & a21, const FT & a22, const FT & a23, const FT & a24, const FT & a25, const FT & a30, const FT & a31, const FT & a32, const FT & a33, const FT & a34, const FT & a35, const FT & a40, const FT & a41, const FT & a42, const FT & a43, const FT & a44, const FT & a45, const FT & a50, const FT & a51, const FT & a52, const FT & a53, const FT & a54, const FT & a55)
Definition at line 117 of file sign_of_determinant.h.
References CGAL_NTS, det6x6_by_formula(), and sign().
 {
   return CGAL_NTS sign(det6x6_by_formula(a00, a01, a02, a03, a04, a05,
                                          a10, a11, a12, a13, a14, a15,
                                          a20, a21, a22, a23, a24, a25,
                                          a30, a31, a32, a33, a34, a35,
                                          a40, a41, a42, a43, a44, a45,
                                          a50, a51, a52, a53, a54, a55));
 }