Rocstar: readinp.f90 File Reference
SourceIMP/utilities/RocfracPrep/readinp.f90 File Reference
Functions/Subroutines
subroutine readinp (ntime)
subroutine prefix_sub ()
subroutine nrun_sub (ntime)
subroutine matvol_sub ()
subroutine bc_sub ()
subroutine nodeio_sub ()
subroutine meshsoft_sub ()
subroutine ioformat_sub ()
subroutine element_sub (keywd)
Function/Subroutine Documentation
subroutine bc_sub ()
Definition at line 195 of file SourceIMP/utilities/RocfracPrep/readinp.f90.
References i.
subroutine element_sub (character(len=200) keywd)
Definition at line 282 of file SourceIMP/utilities/RocfracPrep/readinp.f90.
References locchr(), Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
subroutine ioformat_sub ()
Definition at line 269 of file SourceIMP/utilities/RocfracPrep/readinp.f90.
Referenced by readinp().
subroutine matvol_sub ()
Definition at line 171 of file SourceIMP/utilities/RocfracPrep/readinp.f90.
References Color::alpha(), i, max(), and sqrt().
subroutine meshsoft_sub ()
Definition at line 231 of file SourceIMP/utilities/RocfracPrep/readinp.f90.
References Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
Referenced by readinp().
subroutine nodeio_sub ()
Definition at line 212 of file SourceIMP/utilities/RocfracPrep/readinp.f90.
References i.
subroutine nrun_sub (integer ntime)
Definition at line 158 of file SourceIMP/utilities/RocfracPrep/readinp.f90.
subroutine prefix_sub ()
Definition at line 146 of file SourceIMP/utilities/RocfracPrep/readinp.f90.
subroutine readinp (integer ntime)
Definition at line 53 of file SourceIMP/utilities/RocfracPrep/readinp.f90.
References element_sub(), ioformat_sub(), matvol_sub(), meshsoft_sub(), prefix_sub(), Aff_transformation_repS2< FT >::print(), Attribute::status(), and StopWatch::stop().
Referenced by rocfracprep().