Rocstar: read_patran.f90 File Reference
SourceIMP/utilities/RocfracPrep/read_patran.f90 File Reference
Functions/Subroutines
subroutine read_patran (numvertx2d, dhmin, nprocs)
Function/Subroutine Documentation
subroutine read_patran (integer numvertx2d, real*8 dhmin, integer nprocs)
Definition at line 53 of file SourceIMP/utilities/RocfracPrep/read_patran.f90.
References linked_list2::add_surfmesh_hex8(), linked_list2::add_surfmesh_tri3(), linked_list2::add_surfmesh_tri6(), form, i, id(), j, kc, max(), min(), newcommlist(), Aff_transformation_repS2< FT >::print(), sqrt(), StopWatch::stop(), CImg< T >::sum(), and MsqFreeVertexIndexIterator::value().
Referenced by rocfracprep().