Rocstar: CharKeyWrd.f90 File Reference
Source/CharKeyWrd.f90 File Reference
Functions/Subroutines
subroutine locchr (text, varna, lvari, kpos0, kpos1, kpos2)
subroutine conchr (text, varna, lvari, kpos0, key)
subroutine dtext (text, lll)
subroutine dchar (char, key)
subroutine rchar (char, key)
Function/Subroutine Documentation
subroutine conchr (character(len=200) text, character(len=26) varna, integer lvari, integer kpos0, integer key)
Definition at line 149 of file Source/CharKeyWrd.f90.
References dtext(), and key.
Referenced by matmodel_hyperelastic().
subroutine dchar (character(len=16) char, integer key)
Definition at line 244 of file Source/CharKeyWrd.f90.
References k, and key.
subroutine dtext (character(len=200) text, integer lll)
Definition at line 207 of file Source/CharKeyWrd.f90.
Referenced by conchr().
subroutine locchr (character(len=200) text, character(len=26) varna, integer lvari, integer kpos0, integer kpos1, integer kpos2)
Definition at line 53 of file Source/CharKeyWrd.f90.
References k, and key.
Referenced by amplitude_sub(), dummytract_sub(), dynamic_sub(), element_sub(), initialcondition_sub(), matmodel_elastic(), and micromechanical_sub().
subroutine rchar (character(len=16) char, real*8 key)
Definition at line 285 of file Source/CharKeyWrd.f90.
References key.
Referenced by dynamic_sub().