Rocstar: SPEC_RFLU_ReadBcInputFile.F90 File Reference
SPEC_RFLU_ReadBcInputFile.F90 File Reference
Functions/Subroutines
subroutine spec_rflu_readbcinputfile (pRegion)
Function/Subroutine Documentation
subroutine spec_rflu_readbcinputfile (type(t_region), pointer pRegion)
Definition at line 45 of file SPEC_RFLU_ReadBcInputFile.F90.
References buildfilenameplain(), moderror::deregisterfunction(), moderror::errorstop(), form, CImg< T >::line(), moderror::registerfunction(), spec_rflu_readbcfarfsection(), spec_rflu_readbcinflowsection(), spec_rflu_readbcinjectsection(), spec_rflu_readbcsectiondummy(), and Attribute::status().
Referenced by rflu_modreadbcinputfile::rflu_readbcinputfilewrapper().