Rocstar: SPEC_RFLU_DeallocateMemoryEEv.F90 File Reference
SPEC_RFLU_DeallocateMemoryEEv.F90 File Reference
Functions/Subroutines
subroutine spec_rflu_deallocatememoryeev (pRegion)
Function/Subroutine Documentation
subroutine spec_rflu_deallocatememoryeev (type(t_region), pointer pRegion)
Definition at line 45 of file SPEC_RFLU_DeallocateMemoryEEv.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_deallocatememorywrapper(), and rflu_deallocmemsolwrapper().