Rocstar: SPEC_UserInput.F90 File Reference
SPEC_UserInput.F90 File Reference
Functions/Subroutines
subroutine spec_userinput (regions)
Function/Subroutine Documentation
subroutine spec_userinput (type(t_region), dimension(:), pointer regions)
Definition at line 44 of file SPEC_UserInput.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), spec_checkuserinput(), spec_derivedinputvalues(), spec_initinputvalues(), and spec_readinputfile().
Referenced by rflo_getuserinput(), and rflu_getuserinput().