Rocstar: SPEC_RFLU_AllocateMemoryEEv.F90 File Reference
SPEC_RFLU_AllocateMemoryEEv.F90 File Reference
Functions/Subroutines
subroutine spec_rflu_allocatememoryeev (pRegion)
Function/Subroutine Documentation
subroutine spec_rflu_allocatememoryeev (type(t_region), pointer pRegion)
Definition at line 45 of file SPEC_RFLU_AllocateMemoryEEv.F90.
References moderror::deregisterfunction(), moderror::errorstop(), and moderror::registerfunction().
Referenced by rflu_allocatememorywrapper(), and rflu_allocmemsolwrapper().