Rocstar: SPEC_RFLU_ReadBcInflowSection.F90 File Reference
SPEC_RFLU_ReadBcInflowSection.F90 File Reference
Functions/Subroutines
subroutine spec_rflu_readbcinflowsection (pRegion)
Function/Subroutine Documentation
subroutine spec_rflu_readbcinflowsection (type(t_region), pointer pRegion)
Definition at line 47 of file SPEC_RFLU_ReadBcInflowSection.F90.
References moderror::deregisterfunction(), moderror::errorstop(), makenumberedkeys(), prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().
Referenced by spec_rflu_readbcinputfile().