Rocstar: SPLT_SplitGrid.F90 File Reference
SPLT_SplitGrid.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine splitgrid (splitDirection, regionsOld, regionsNew)
Function/Subroutine Documentation
subroutine splitgrid (integer splitDirection, type(t_region), dimension(:), pointer regionsOld, type(t_region), dimension(:), pointer regionsNew)
Definition at line 44 of file SPLT_SplitGrid.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, idnbeg, idnend, j, jdnbeg, jdnend, k, kdnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), and rflo_getnodeoffset().
Referenced by rocflo_split().