Rocstar: SPLT_SplitTopology.F90 File Reference
SPLT_SplitTopology.F90 File Reference
Functions/Subroutines
subroutine splittopology (splitDirection, regionsOld, regionsNew)
Function/Subroutine Documentation
subroutine splittopology (integer splitDirection, type(t_region), dimension(:), pointer regionsOld, type(t_region), dimension(:), pointer regionsNew)
Definition at line 44 of file SPLT_SplitTopology.F90.
References copypatchdata(), moderror::deregisterfunction(), ibeg, iend, jbeg, jend, kbeg, and moderror::registerfunction().
Referenced by rocflo_split().