Rocstar: SPLT_CopyPatchData.F90 File Reference
SPLT_CopyPatchData.F90 File Reference
Functions/Subroutines
subroutine copypatchdata (regionsNew, patchOld, splitDirection, iReg, l1Off, l2Off, l1Cells, l2Cells)
Function/Subroutine Documentation
subroutine copypatchdata (type(t_region), dimension(:), pointer regionsNew, type(t_patch), pointer patchOld, integer splitDirection, integer iReg, integer l1Off, integer l2Off, integer l1Cells, integer l2Cells)
Definition at line 50 of file SPLT_CopyPatchData.F90.
References ibeg, jbeg, kbeg, max(), and min().
Referenced by splittopology().