Rocstar: SPLT_Main.F90 File Reference
SPLT_Main.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
program rocflo_split
Function/Subroutine Documentation
program rocflo_split ()
Definition at line 44 of file SPLT_Main.F90.
References buildversionstring(), moderror::deregisterfunction(), moderror::errorstop(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), rflo_readgridregion(), rflo_readregiontopology(), rflo_writegridregion(), rflo_writeregiontopology(), splitgrid(), splittopology(), and StopWatch::stop().