Rocstar: RFLO_GetDeformation.F90 File Reference
standalone/RFLO_GetDeformation.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine rflo_getdeformation (region, boundMoved, dNode)
Function/Subroutine Documentation
subroutine rflo_getdeformation (type(t_region) region, logical, dimension(6) boundMoved, real(rfreal), dimension(:,:), pointer dNode)
Definition at line 44 of file standalone/RFLO_GetDeformation.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getnodeoffset(), and rflo_getpatchindicesnodes().