Rocstar: Window::Pointer_descriptor Struct Reference
Window::Pointer_descriptor Struct Reference
#include <Window.h>
Public Member Functions
Pointer_descriptor (void *p, int d=-1)
void * at ()
Public Attributes
void * ptr
int dim
int n1
int n2
Detailed Description
Definition at line 65 of file Window.h.
Constructor & Destructor Documentation
Pointer_descriptor (void * p, int d = -1) inline explicit
Definition at line 66 of file Window.h.
       : ptr(p), dim(d), n1(0), n2(0) {}
Member Function Documentation
void* at () inline
Definition at line 68 of file Window.h.
References ptr.
Referenced by com_set_address_f(), tractload(), and tractloaddef().
 { return ptr; }
Member Data Documentation
int dim
Definition at line 71 of file Window.h.
int n1
Definition at line 72 of file Window.h.
Referenced by com_set_address_f().
int n2
Definition at line 72 of file Window.h.
Referenced by com_set_address_f().
void* ptr
Definition at line 70 of file Window.h.
Referenced by at(), com_obtain_array_helper(), and Roccom_base::get_array().
The documentation for this struct was generated from the following file:
Window.h