Rocstar: Host_face Struct Reference
Host_face Struct Reference
#include <HDS_overlay.h>
Public Member Functions
Host_face ()
Host_face (Halfedge_overlay *h, Parent_type t)
Halfedge_overlay * halfedge () const
Parent_type parent_type () const
bool operator== (const Host_face &h) const
bool operator!= (const Host_face &h) const
Private Attributes
char * _p
Detailed Description
Definition at line 290 of file HDS_overlay.h.
Constructor & Destructor Documentation
Host_face () inline
Definition at line 291 of file HDS_overlay.h.
 : _p(0) {};
Host_face (Halfedge_overlay * h, Parent_type t) inline
Definition at line 292 of file HDS_overlay.h.
References halfedge(), parent_type(), and RFC_assertion.
     : _p( (char*)(h) + (int(t)&3))
   { RFC_assertion( h==halfedge() && t==parent_type()); }
Member Function Documentation
Halfedge_overlay* halfedge () const inline
Definition at line 295 of file HDS_overlay.h.
References _p, and parent_type().
Referenced by INode::blue_halfedge(), Overlay::get_edge_pair_parents(), Overlay::get_next_inode(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), INode::green_halfedge(), INode::halfedge(), and Host_face().
   { return (Halfedge_overlay*)(_p-parent_type()); }
bool operator!= (const Host_face & h) const inline
Definition at line 300 of file HDS_overlay.h.
References _p.
 { return _p!=h._p; }
bool operator== (const Host_face & h) const inline
Definition at line 299 of file HDS_overlay.h.
References _p.
 { return _p==h._p; }
Parent_type parent_type () const inline
Definition at line 297 of file HDS_overlay.h.
References _p.
Referenced by INode::blue_parent_type(), Overlay::get_edge_pair_parents(), Overlay::get_next_inode(), Overlay::get_next_inode_ccw(), Overlay::get_next_inode_cw(), INode::green_parent_type(), halfedge(), Host_face(), and INode::parent_type().
   { return Parent_type(std::distance((char*)NULL,_p)&3); }
Member Data Documentation
char* _p private
Definition at line 302 of file HDS_overlay.h.
Referenced by halfedge(), operator!=(), operator==(), and parent_type().
The documentation for this struct was generated from the following file:
HDS_overlay.h