Rocstar: CImg< T >::_cimg_math_parser Struct Reference
CImg< T >::_cimg_math_parser Struct Reference
#include <CImg.h>
Public Member Functions
_cimg_math_parser (const char *const expression, const char *const funcname=0)
~_cimg_math_parser ()
unsigned int opcode (const char op, const unsigned int arg1=0, const unsigned int arg2=0, const unsigned int arg3=0, const unsigned int arg4=0, const unsigned int arg5=0)
unsigned int compile (char *const ss, char *const se)
template<typename t >
double eval (const CImg< t > &img, const double x, const double y, const double z, const double v)
double eval (const double x, const double y, const double z, const double v)
Public Attributes
CImgList< uintT > code
CImg< doubleT > mem
unsigned int mempos
unsigned int * level
unsigned int result
const char * calling_function
char * expr
Detailed Description
template<typename T = float>
struct cimg_library::CImg< T >::_cimg_math_parser
Definition at line 12218 of file CImg.h.
Constructor & Destructor Documentation
_cimg_math_parser (const char *const expression, const char *const funcname = 0) inline
Definition at line 12232 of file CImg.h.
References CImg< T >::assign(), CImg< T >::_cimg_math_parser::calling_function, CImg< T >::_cimg_math_parser::compile(), cimg_library::exp(), CImg< T >::_cimg_math_parser::expr, CImg< T >::_cimg_math_parser::level, CImg< T >::_cimg_math_parser::mem, CImg< T >::_cimg_math_parser::mempos, CImg< T >::pixel_type(), s, cimg_library::cimg::strclean(), cimg_library::cimg::uncase(), and cimg_library::cimg::valuePI.
                                                                                    :level(0),calling_function(funcname),expr(0) {
         static const char *const funcname0 = "cimg_math_parser";
         if (!funcname) calling_function = funcname0;
         if (!expression) return;
         unsigned int l0 = std::strlen(expression);
         expr = new char[l0+1];
         std::strcpy(expr,expression);
         cimg::strclean(expr);
         if (!*expr) return;
         char *d = expr; for (const char *s = expr; *s || (bool)(*d=0); ++s) if (*s!=' ') *(d++) = *s;
         const unsigned int l = d - expr;
         if (!l) return;
         cimg::uncase(expr);
         int lv = 0; // Count parenthesis level of expression.
         unsigned int *pd = level = new unsigned int[l];
         for (const char *ps = expr; *ps && lv>=0; ++ps) *(pd++) = (unsigned int)(*ps=='('?lv++:*ps==')'?--lv:lv);
         if (lv!=0) throw CImgArgumentException("CImg<%s>::%s() : Unbalanced parenthesis, in formula '%s'.",
                                                pixel_type(),calling_function,expr);
         mem.assign(1024); // Compile formula into serie of opcodes.
         mem[8] = cimg::valuePI; mem[9] = std::exp(1.0); mem[10] = 0; mempos = 11;
         result = compile(expr,expr+l);
       }
~_cimg_math_parser () inline
Definition at line 12254 of file CImg.h.
References CImg< T >::_cimg_math_parser::expr, and CImg< T >::_cimg_math_parser::level.
 { if (level) delete[] level; if (expr) delete[] expr; }
Member Function Documentation
unsigned int compile (char *const ss, char *const se) inline
Definition at line 12266 of file CImg.h.
References _cimg_fopcode0, _cimg_fopcode1, _cimg_fopcode2, _cimg_fopcode3, _cimg_fopcode5, _cimg_freturn, CImg< T >::_cimg_math_parser::calling_function, CImg< T >::_cimg_math_parser::code, CImg< T >::end(), CImg< T >::_cimg_math_parser::expr, i, CImg< T >::_cimg_math_parser::level, CImg< T >::_cimg_math_parser::mem, CImg< T >::_cimg_math_parser::mempos, CImg< T >::_cimg_math_parser::opcode(), CImg< T >::pixel_type(), CImg< T >::resize(), s, CImg< T >::size(), CImg< T >::transfer_to(), and CImg< T >::vector().
Referenced by CImg< T >::_cimg_math_parser::_cimg_math_parser().
{
         if (!ss || se<=ss || !*ss) throw CImgArgumentException("CImg<%s>::%s() : Missing item, in formula '%s'.",
                                                                pixel_type(),calling_function,expr);
         char
           *const se1 = se-1, *const se2 = se-2, *const se3 = se-3, *const se4 = se-4,
           *const ss1 = ss+1, *const ss2 = ss+2, *const ss3 = ss+3, *const ss4 = ss+4, *const ss5 = ss+5, *const ss6 = ss+6;
         const char saved_char = *se; *se = 0;
         const unsigned int clevel = level[ss-expr], clevel1 = clevel+1;
         // Look for a single value, variable or reccurent expression.
         char end = 0; double val = 0;
         if (std::sscanf(ss,"%lf%c",&val,&end)==1) {
           const unsigned int i = mempos++;
           mem[i] = val;
           _cimg_freturn(i);
         }
         if (ss1==se) switch (*ss) {
         case 'x' : _cimg_freturn(0); case 'y' : _cimg_freturn(1); case 'z' : _cimg_freturn(2); case 'v' : _cimg_freturn(3);
         case 'w' : _cimg_freturn(4); case 'h' : _cimg_freturn(5); case 'd' : _cimg_freturn(6); case 'c' : _cimg_freturn(7);
         case 'e' : _cimg_freturn(9);
         case 'u' : _cimg_fopcode0('U');
         case 'g' : _cimg_fopcode0('G');
         case 'i' : _cimg_fopcode0('I');
         }
         if (ss1==se1 && *ss=='p' && *ss1=='i') _cimg_freturn(8); // pi-value
         if (ss3==se) {
           if (*ss=='x' && *ss1=='/' && *ss2=='w') _cimg_fopcode0('0');
           if (*ss=='y' && *ss1=='/' && *ss2=='h') _cimg_fopcode0('1');
           if (*ss=='z' && *ss1=='/' && *ss2=='d') _cimg_fopcode0('2');
           if (*ss=='v' && *ss1=='/' && *ss2=='c') _cimg_fopcode0('3');
         }
         // Look for a unary of binary operators.
         for (char *s = ss1, *ns = 0; s<se3 && (ns=std::strstr(s,"and")) && ns<se3; s=ns+3)
           if (level[ns-expr]==clevel) _cimg_fopcode2('A',compile(ss,ns),compile(ns+3,se));
         for (char *s = ss1, *ns = 0; s<se2 && (ns=std::strstr(s,"&&")) && ns<se2; s=ns+2)
           if (level[ns-expr]==clevel) _cimg_fopcode2('A',compile(ss,ns),compile(ns+2,se));
         for (char *s = ss1, *ns = 0; s<se3 && (ns=std::strstr(s,"xor")) && ns<se3; s=ns+3)
           if (level[ns-expr]==clevel) _cimg_fopcode2('X',compile(ss,ns),compile(ns+3,se));
         for (char *s = ss1, *ns = 0; s<se2 && (ns=std::strstr(s,"or")) && ns<se2; s=ns+2)
           if (level[ns-expr]==clevel) _cimg_fopcode2('O',compile(ss,ns),compile(ns+2,se));
         for (char *s = ss1, *ns = 0; s<se2 && (ns=std::strstr(s,"||")) && ns<se2; s=ns+2)
           if (level[ns-expr]==clevel) _cimg_fopcode2('O',compile(ss,ns),compile(ns+2,se));
         for (char *s = ss1, *ns = 0; s<se2 && (ns=std::strstr(s,"<=")) && ns<se2; s=ns+2)
           if (level[ns-expr]==clevel) _cimg_fopcode2('l',compile(ss,ns),compile(ns+2,se));
         for (char *s = ss1, *ns = 0; s<se2 && (ns=std::strstr(s,">=")) && ns<se2; s=ns+2)
           if (level[ns-expr]==clevel) _cimg_fopcode2('g',compile(ss,ns),compile(ns+2,se));
         for (char *s = ss1, *ns = 0; s<se2 && (ns=std::strstr(s,"!=")) && ns<se2; s=ns+2)
           if (level[ns-expr]==clevel) _cimg_fopcode2('!',compile(ss,ns),compile(ns+2,se));
         for (char *s = ss1, *ns = 0; s<se2 && (ns=std::strstr(s,"==")) && ns<se2; s=ns+2)
           if (level[ns-expr]==clevel) _cimg_fopcode2('=',compile(ss,ns),compile(ns+2,se));
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,">")) && ns<se1; s=ns+1)
           if (level[ns-expr]==clevel) _cimg_fopcode2('>',compile(ss,ns),compile(ns+1,se));
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,"<")) && ns<se1; s=ns+1)
           if (level[ns-expr]==clevel) _cimg_fopcode2('<',compile(ss,ns),compile(ns+1,se));
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,"+")) && ns<se1; s=ns+1)
           if (level[ns-expr]==clevel) _cimg_fopcode2('+',compile(ss,ns),compile(ns+1,se));
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,"-")) && ns<se1; s=ns+1) {
           const char ps = *(ns-1);
           if (ps!='*' && ps!='/' && ps!='%' && ps!='^' && ps!='&' && ps!='|' && ps!='^' &&
               level[ns-expr]==clevel) _cimg_fopcode2('-',compile(ss,ns),compile(ns+1,se));
         }
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,"*")) && ns<se1; s=ns+1)
           if (level[ns-expr]==clevel) _cimg_fopcode2('*',compile(ss,ns),compile(ns+1,se));
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,"/")) && ns<se1; s=ns+1)
           if (level[ns-expr]==clevel) _cimg_fopcode2('/',compile(ss,ns),compile(ns+1,se));
         if (ss<se1) {
           if (*ss=='-') _cimg_fopcode1('o',compile(ss1,se));
           if (*ss=='+') _cimg_fopcode1('p',compile(ss1,se));
           if (*ss=='!') _cimg_fopcode1('n',compile(ss1,se));
           if (*ss=='~') _cimg_fopcode1('~',compile(ss1,se));
         }
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,"%")) && ns<se1; s=ns+1)
           if (level[ns-expr]==clevel) _cimg_fopcode2('%',compile(ss,ns),compile(ns+1,se));
         for (char *s = ss1, *ns = 0; s<se3 && (ns=std::strstr(s,"mod")) && ns<se3; s=ns+3)
           if (level[ns-expr]==clevel) _cimg_fopcode2('%',compile(ss,ns),compile(ns+3,se));
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,"&")) && ns<se1; s=ns+1)
           if (level[ns-expr]==clevel) _cimg_fopcode2('&',compile(ss,ns),compile(ns+1,se));
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,"|")) && ns<se1; s=ns+1)
           if (level[ns-expr]==clevel) _cimg_fopcode2('|',compile(ss,ns),compile(ns+1,se));
         for (char *s = ss1, *ns = 0; s<se1 && (ns=std::strstr(s,"^")) && ns<se1; s=ns+1)
           if (level[ns-expr]==clevel) _cimg_fopcode2('^',compile(ss,ns),compile(ns+1,se));
         // Look for a function call or a parenthesis.
         if (*se1==')') {
           if (*ss=='(') _cimg_freturn(compile(ss1,se1));
           if (!std::strncmp(ss,"sin(",4)) _cimg_fopcode1('s',compile(ss4,se1));
           if (!std::strncmp(ss,"cos(",4)) _cimg_fopcode1('c',compile(ss4,se1));
           if (!std::strncmp(ss,"tan(",4)) _cimg_fopcode1('t',compile(ss4,se1));
           if (!std::strncmp(ss,"asin(",5)) _cimg_fopcode1('S',compile(ss5,se1));
           if (!std::strncmp(ss,"acos(",5)) _cimg_fopcode1('C',compile(ss5,se1));
           if (!std::strncmp(ss,"atan(",5)) _cimg_fopcode1('T',compile(ss5,se1));
           if (!std::strncmp(ss,"sinh(",5)) _cimg_fopcode1('.',compile(ss5,se1));
           if (!std::strncmp(ss,"cosh(",5)) _cimg_fopcode1(',',compile(ss5,se1));
           if (!std::strncmp(ss,"tanh(",5)) _cimg_fopcode1(';',compile(ss5,se1));
           if (!std::strncmp(ss,"log10(",6)) _cimg_fopcode1('Q',compile(ss6,se1));
           if (!std::strncmp(ss,"log(",4)) _cimg_fopcode1('q',compile(ss4,se1));
           if (!std::strncmp(ss,"ln(",3)) _cimg_fopcode1('q',compile(ss3,se1));
           if (!std::strncmp(ss,"exp(",4)) _cimg_fopcode1('e',compile(ss4,se1));
           if (!std::strncmp(ss,"sqrt(",5)) _cimg_fopcode1('r',compile(ss5,se1));
           if (!std::strncmp(ss,"sign(",5)) _cimg_fopcode1('\\',compile(ss5,se1));
           if (!std::strncmp(ss,"rint(",5)) _cimg_fopcode1('i',compile(ss5,se1));
           if (!std::strncmp(ss,"abs(",4)) _cimg_fopcode1(':',compile(ss4,se1));
           if (!std::strncmp(ss,"atan2(",6)) {
             char *s1 = ss6; while (s1<se2 && (*s1!=',' || level[s1-expr]!=clevel1)) ++s1;
             _cimg_fopcode2('#',compile(ss6,s1),compile(s1+1,se1));
           }
           if (!std::strncmp(ss,"if(",3)) {
             char *s1 = ss3; while (s1<se4 && (*s1!=',' || level[s1-expr]!=clevel1)) ++s1;
             char *s2 = s1+1; while (s2<se2 && (*s2!=',' || level[s2-expr]!=clevel1)) ++s2;
             _cimg_fopcode3('?',compile(ss3,s1),compile(s1+1,s2),compile(s2+1,se1));
           }
           if (!std::strncmp(ss,"i(",2)) {
             unsigned int indx = 0, indy = 1, indz = 2, indv = 3, borders = 10;
             if (ss2!=se1) {
               char *s1 = ss2; while (s1<se2 && (*s1!=',' || level[s1-expr]!=clevel1)) ++s1;
               indx = compile(ss2,s1==se2?++s1:s1);
               if (s1<se1) {
                 char *s2 = s1+1; while (s2<se2 && (*s2!=',' || level[s2-expr]!=clevel1)) ++s2;
                 indy = compile(s1+1,s2==se2?++s2:s2);
                 if (s2<se1) {
                   char *s3 = s2+1; while (s3<se2 && (*s3!=',' || level[s3-expr]!=clevel1)) ++s3;
                   indz = compile(s2+1,s3==se2?++s3:s3);
                   if (s3<se1) {
                     char *s4 = s3+1; while (s4<se2 && (*s4!=',' || level[s4-expr]!=clevel1)) ++s4;
                     indv = compile(s3+1,s4==se2?++s4:s4);
                     if (s4<se1) borders = compile(s4+1,se1);
                   }
                 }
               }
             }
             _cimg_fopcode5('(',indx,indy,indz,indv,borders);
           }
           if (!std::strncmp(ss,"min(",4) || !std::strncmp(ss,"max(",4)) {
             CImgList<uintT> opcode;
             if (mempos>=mem.size()) mem.resize(-200,1,1,1,0); const unsigned int pos = mempos++;
             CImg<uintT>::vector(ss[1]=='i'?'m':'M',pos).transfer_to(opcode);
             for (char *s = ss4; s<se; ++s) {
               char *ns = s; while (ns<se && (*ns!=',' || level[ns-expr]!=clevel1) && (*ns!=')' || level[ns-expr]!=clevel)) ++ns;
               CImg<uintT>::vector(compile(s,ns)).transfer_to(opcode);
               s = ns;
             }
             (opcode>'y').transfer_to(code);
             _cimg_freturn(pos);
           }
         }
         // No known item found.
         char *item = new char[std::strlen(ss)];
         std::strcpy(item,ss);
         *se = saved_char;
         throw CImgArgumentException("CImg<%s>::%s() : Invalid item '%s', in expression '%s'.",
                                     pixel_type(),calling_function,item,expr);
         return 0;
       }
double eval (const CImg< t > & img, const double x, const double y, const double z, const double v) inline
Definition at line 12423 of file CImg.h.
References cimg_library::cimg::abs(), cimg_library::acos(), cimg_library::asin(), cimg_library::atan(), CImg< T >::_cimg_math_parser::calling_function, cimglist_for, CImg< T >::_cimg_math_parser::code, cimg_library::cos(), cimg_library::cosh(), cimg_library::exp(), cimg_library::cimg::grand(), CImg< T >::height, i, cimg_library::log(), cimg_library::log10(), cimg_library::cimg::max(), CImg< T >::_cimg_math_parser::mem, cimg_library::cimg::min(), cimg_library::cimg::mod(), CImg< T >::_cimg_math_parser::opcode(), CImg< T >::pixel_type(), Mesquite::pow(), cimg_library::cimg::rand(), CImg< T >::_cimg_math_parser::result, cimg_library::cimg::round(), cimg_library::cimg::sign(), cimg_library::sin(), cimg_library::sinh(), sqrt(), cimg_library::tan(), cimg_library::tanh(), v, x, y, and z.
Referenced by CImg< T >::_cimg_math_parser::eval(), CImg< T >::_marching2d_func_expr::operator()(), and CImg< T >::_marching3d_func_expr::operator()().
{
         if (!mem) return 0;
         mem[0] = x; mem[1] = y; mem[2] = z; mem[3] = v;
         mem[4] = img.dimx(); mem[5] = img.dimy(); mem[6] = img.dimz(); mem[7] = img.dimv();
         cimglist_for(code,l) {
           const CImg<uintT> &opcode = code[l];
           double &res = mem[opcode(1)];
           switch (opcode(0)) {
           case 'U' : res = cimg::rand(); break;
           case 'G' : res = cimg::grand(); break;
           case 'I' : res = (double)img.atXYZV((int)x,(int)y,(int)z,(int)v,0); break;
           case '0' : res = x/img.dimx(); break;
           case '1' : res = y/img.dimy(); break;
           case '2' : res = z/img.dimz(); break;
           case '3' : res = v/img.dimv(); break;
           case 'A' : res = (bool)mem[opcode(2)] && (bool)mem[opcode(3)]; break;
           case 'X' : res = (bool)mem[opcode(2)] ^ (bool)mem[opcode(3)]; break;
           case 'O' : res = (bool)mem[opcode(2)] || (bool)mem[opcode(3)]; break;
           case 'l' : res = (mem[opcode(2)] <= mem[opcode(3)]); break;
           case 'g' : res = (mem[opcode(2)] >= mem[opcode(3)]); break;
           case '!' : res = (mem[opcode(2)] != mem[opcode(3)]); break;
           case '=' : res = (mem[opcode(2)] == mem[opcode(3)]); break;
           case '>' : res = (mem[opcode(2)] > mem[opcode(3)]); break;
           case '<' : res = (mem[opcode(2)] < mem[opcode(3)]); break;
           case '+' : res = (mem[opcode(2)] + mem[opcode(3)]); break;
           case '-' : res = (mem[opcode(2)] - mem[opcode(3)]); break;
           case '*' : res = (mem[opcode(2)] * mem[opcode(3)]); break;
           case '/' : res = (mem[opcode(2)] / mem[opcode(3)]); break;
           case 'o' : res = -mem[opcode(2)]; break;
           case 'p' : res = mem[opcode(2)]; break;
           case 'n' : res = !mem[opcode(2)]; break;
           case '~' : res = ~(unsigned long)mem[opcode(2)]; break;
           case '%' : res = cimg::mod(mem[opcode(2)],mem[opcode(3)]); break;
           case '&' : res = ((unsigned long)mem[opcode(2)] & (unsigned long)mem[opcode(3)]); break;
           case '|' : res = ((unsigned long)mem[opcode(2)] | (unsigned long)mem[opcode(3)]); break;
           case '^' : res = std::pow(mem[opcode(2)],mem[opcode(3)]); break;
           case 's' : res = std::sin(mem[opcode(2)]); break;
           case 'c' : res = std::cos(mem[opcode(2)]); break;
           case 't' : res = std::tan(mem[opcode(2)]); break;
           case 'S' : res = std::asin(mem[opcode(2)]); break;
           case 'C' : res = std::acos(mem[opcode(2)]); break;
           case 'T' : res = std::atan(mem[opcode(2)]); break;
           case '.' : res = std::sinh(mem[opcode(2)]); break;
           case ',' : res = std::cosh(mem[opcode(2)]); break;
           case ';' : res = std::tanh(mem[opcode(2)]); break;
           case 'Q' : res = std::log10(mem[opcode(2)]); break;
           case 'q' : res = std::log(mem[opcode(2)]); break;
           case 'e' : res = std::exp(mem[opcode(2)]); break;
           case 'r' : res = std::sqrt(mem[opcode(2)]); break;
           case '\\' : res = cimg::sign(mem[opcode(2)]); break;
           case 'i' : res = cimg::round(mem[opcode(2)],1); break;
           case '(' : {
             const int v = (int)mem[opcode(5)];
             switch ((int)mem[opcode(6)]) {
             case 0 : res = (double)img.linear_atXYZ((float)mem[opcode(2)],
                                                     (float)mem[opcode(3)],
                                                     (float)mem[opcode(4)],
                                                     v<0?0:v>=img.dimv()?img.dimv()-1:v,0); break;
             case 1 : res = (double)img.linear_atXYZ((float)mem[opcode(2)],
                                                     (float)mem[opcode(3)],
                                                     (float)mem[opcode(4)],
                                                     v<0?0:v>=img.dimv()?img.dimv()-1:v); break;
             default : res = (double)img.linear_atXYZ((float)cimg::mod(mem[opcode(2)],(double)img.dimx()),
                                                      (float)cimg::mod(mem[opcode(3)],(double)img.dimy()),
                                                      (float)cimg::mod(mem[opcode(4)],(double)img.dimz()),
                                                      v<0?0:v>=img.dimv()?img.dimv()-1:v); break;
             }
           } break;
           case ':' : res = cimg::abs(mem[opcode(2)]); break;
           case '#' : res = std::atan2(mem[opcode(2)],mem[opcode(3)]); break;
           case '?' : res = mem[opcode(2)]?mem[opcode(3)]:mem[opcode(4)]; break;
           case 'm' : {
             double val = mem[opcode(2)];
             for (unsigned int i = 3; i<opcode.height; ++i) val = cimg::min(val,mem[opcode(i)]);
             res = val;
           } break;
           case 'M' : {
             double val = mem[opcode(2)];
             for (unsigned int i = 3; i<opcode.height; ++i) val = cimg::max(val,mem[opcode(i)]);
             res = val;
           } break;
           default :
             throw CImgArgumentException("CImg<%s>::%s() : Invalid opcode %d.",pixel_type(),calling_function,opcode(0));
           }
         }
         return mem[result];
       }
double eval (const double x, const double y, const double z, const double v) inline
Definition at line 12512 of file CImg.h.
References CImg< T >::empty(), and CImg< T >::_cimg_math_parser::eval().
{
         static const CImg<T> empty;
         return eval(empty,x,y,z,v);
       }
unsigned int opcode (const char op, const unsigned int arg1 = 0, const unsigned int arg2 = 0, const unsigned int arg3 = 0, const unsigned int arg4 = 0, const unsigned int arg5 = 0) inline
Definition at line 12257 of file CImg.h.
References CImg< T >::_cimg_math_parser::code, CImg< T >::_cimg_math_parser::mem, CImg< T >::_cimg_math_parser::mempos, CImg< T >::resize(), CImg< T >::size(), and CImg< T >::vector().
Referenced by CImg< T >::_cimg_math_parser::compile(), and CImg< T >::_cimg_math_parser::eval().
{
         if (mempos>=mem.size()) mem.resize(-200,1,1,1,0);
         const unsigned int pos = mempos++;
         CImg<uintT>::vector(op,pos,arg1,arg2,arg3,arg4,arg5).transfer_to(code);
         return pos;
       }
Member Data Documentation
const char* calling_function
Definition at line 12222 of file CImg.h.
Referenced by CImg< T >::_cimg_math_parser::_cimg_math_parser(), CImg< T >::_cimg_math_parser::compile(), and CImg< T >::_cimg_math_parser::eval().
CImgList<uintT> code
Definition at line 12219 of file CImg.h.
Referenced by CImg< T >::_cimg_math_parser::compile(), CImg< T >::_cimg_math_parser::eval(), and CImg< T >::_cimg_math_parser::opcode().
char* expr
Definition at line 12223 of file CImg.h.
Referenced by CImg< T >::_cimg_math_parser::_cimg_math_parser(), CImg< T >::_cimg_math_parser::compile(), and CImg< T >::_cimg_math_parser::~_cimg_math_parser().
unsigned int * level
Definition at line 12221 of file CImg.h.
Referenced by CImg< T >::_cimg_math_parser::_cimg_math_parser(), CImg< T >::_cimg_math_parser::compile(), and CImg< T >::_cimg_math_parser::~_cimg_math_parser().
CImg<doubleT> mem
Definition at line 12220 of file CImg.h.
Referenced by CImg< T >::_cimg_math_parser::_cimg_math_parser(), CImg< T >::_cimg_math_parser::compile(), CImg< T >::_cimg_math_parser::eval(), and CImg< T >::_cimg_math_parser::opcode().
unsigned int mempos
Definition at line 12221 of file CImg.h.
Referenced by CImg< T >::_cimg_math_parser::_cimg_math_parser(), CImg< T >::_cimg_math_parser::compile(), and CImg< T >::_cimg_math_parser::opcode().
unsigned int result
Definition at line 12221 of file CImg.h.
Referenced by CImg< T >::_cimg_math_parser::eval().
The documentation for this struct was generated from the following file:
CImg.h