Rocstar: CImgDisplay Struct Reference
CImgDisplay Struct Reference
This class represents a window which can display CImg images and handles mouse and keyboard events.
#include <CImg.h>
Public Member Functions
Overloaded Operators
template<typename t >
CImgDisplay & operator= (const CImg< t > &img)
template<typename t >
CImgDisplay & operator= (const CImgList< t > &list)
CImgDisplay & operator= (const CImgDisplay &disp)
Operator=().
operator bool () const
Return true if display is not empty.
Instance Checking
bool is_empty () const
Return true is display is empty.
bool is_key (const bool remove=false)
Test if any key has been pressed.
bool is_key (const unsigned int key1, const bool remove)
Test if a key has been pressed.
bool is_key (const unsigned int key1, const unsigned int key2, const bool remove)
Test if a key sequence has been typed.
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const bool remove)
Test if a key sequence has been typed.
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const bool remove)
Test if a key sequence has been typed.
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const bool remove)
Test if a key sequence has been typed.
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const unsigned int key6, const bool remove)
Test if a key sequence has been typed.
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const unsigned int key6, const unsigned int key7, const bool remove)
Test if a key sequence has been typed.
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const unsigned int key6, const unsigned int key7, const unsigned int key8, const bool remove)
Test if a key sequence has been typed.
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const unsigned int key6, const unsigned int key7, const unsigned int key8, const unsigned int key9, const bool remove)
Test if a key sequence has been typed.
bool is_key (const unsigned int *const keyseq, const unsigned int N, const bool remove=true)
Test if a key sequence has been typed.
void _update_iskey (const unsigned int key, const bool pressed=true)
Public Attributes
unsigned int width
Width of the display.
unsigned int height
Height of the display.
volatile unsigned int window_width
Width of the underlying window.
volatile unsigned int window_height
Height of the underlying window.
volatile int window_x
X-pos of the display on the screen.
volatile int window_y
Y-pos of the display on the screen.
volatile int mouse_x
X-coordinate of the mouse pointer on the display.
volatile int mouse_y
Y-coordinate of the mouse pointer on the display.
unsigned int normalization
Normalization type used for the display.
char * title
Display title.
volatile unsigned int buttons [512]
Button state of the mouse.
volatile unsigned int & button
volatile int wheel
Wheel state of the mouse.
volatile unsigned int & key
Key value if pressed.
volatile unsigned int keys [512]
volatile unsigned int & released_key
Key value if released.
volatile unsigned int released_keys [512]
volatile bool is_closed
Closed state of the window.
volatile bool is_resized
Resized state of the window.
volatile bool is_moved
Moved state of the window.
volatile bool is_event
Event state of the window.
volatile bool is_keyESC
Current state of the corresponding key (exists for all referenced keys).
volatile bool is_keyF1
volatile bool is_keyF2
volatile bool is_keyF3
volatile bool is_keyF4
volatile bool is_keyF5
volatile bool is_keyF6
volatile bool is_keyF7
volatile bool is_keyF8
volatile bool is_keyF9
volatile bool is_keyF10
volatile bool is_keyF11
volatile bool is_keyF12
volatile bool is_keyPAUSE
volatile bool is_key1
volatile bool is_key2
volatile bool is_key3
volatile bool is_key4
volatile bool is_key5
volatile bool is_key6
volatile bool is_key7
volatile bool is_key8
volatile bool is_key9
volatile bool is_key0
volatile bool is_keyBACKSPACE
volatile bool is_keyINSERT
volatile bool is_keyHOME
volatile bool is_keyPAGEUP
volatile bool is_keyTAB
volatile bool is_keyQ
volatile bool is_keyW
volatile bool is_keyE
volatile bool is_keyR
volatile bool is_keyT
volatile bool is_keyY
volatile bool is_keyU
volatile bool is_keyI
volatile bool is_keyO
volatile bool is_keyP
volatile bool is_keyDELETE
volatile bool is_keyEND
volatile bool is_keyPAGEDOWN
volatile bool is_keyCAPSLOCK
volatile bool is_keyA
volatile bool is_keyS
volatile bool is_keyD
volatile bool is_keyF
volatile bool is_keyG
volatile bool is_keyH
volatile bool is_keyJ
volatile bool is_keyK
volatile bool is_keyL
volatile bool is_keyENTER
volatile bool is_keySHIFTLEFT
volatile bool is_keyZ
volatile bool is_keyX
volatile bool is_keyC
volatile bool is_keyV
volatile bool is_keyB
volatile bool is_keyN
volatile bool is_keyM
volatile bool is_keySHIFTRIGHT
volatile bool is_keyARROWUP
volatile bool is_keyCTRLLEFT
volatile bool is_keyAPPLEFT
volatile bool is_keyALT
volatile bool is_keySPACE
volatile bool is_keyALTGR
volatile bool is_keyAPPRIGHT
volatile bool is_keyMENU
volatile bool is_keyCTRLRIGHT
volatile bool is_keyARROWLEFT
volatile bool is_keyARROWDOWN
volatile bool is_keyARROWRIGHT
volatile bool is_keyPAD0
volatile bool is_keyPAD1
volatile bool is_keyPAD2
volatile bool is_keyPAD3
volatile bool is_keyPAD4
volatile bool is_keyPAD5
volatile bool is_keyPAD6
volatile bool is_keyPAD7
volatile bool is_keyPAD8
volatile bool is_keyPAD9
volatile bool is_keyPADADD
volatile bool is_keyPADSUB
volatile bool is_keyPADMUL
volatile bool is_keyPADDIV
bool is_fullscreen
Fullscreen state of the display.
float fps_fps
float min
float max
unsigned long timer
unsigned long fps_frames
unsigned long fps_timer
Constructors / Destructor / Instance Management
~CImgDisplay ()
Destructor.
CImgDisplay ()
Create an empty display window.
CImgDisplay (const unsigned int dimw, const unsigned int dimh, const char *title=0, const unsigned int normalization_type=3, const bool fullscreen_flag=false, const bool closed_flag=false)
Create a display window with a specified size pwidth x height.
template<typename T >
CImgDisplay (const CImg< T > &img, const char *title=0, const unsigned int normalization_type=3, const bool fullscreen_flag=false, const bool closed_flag=false)
Create a display window from an image.
template<typename T >
CImgDisplay (const CImgList< T > &list, const char *title=0, const unsigned int normalization_type=3, const bool fullscreen_flag=false, const bool closed_flag=false)
Create a display window from an image list.
CImgDisplay (const CImgDisplay &disp)
Create a display window by copying another one.
CImgDisplay & assign ()
In-place version of the destructor.
CImgDisplay & assign (const unsigned int dimw, const unsigned int dimh, const char *title=0, const unsigned int normalization_type=3, const bool fullscreen_flag=false, const bool closed_flag=false)
In-place version of the previous constructor.
template<typename T >
CImgDisplay & assign (const CImg< T > &img, const char *title=0, const unsigned int normalization_type=3, const bool fullscreen_flag=false, const bool closed_flag=false)
In-place version of the previous constructor.
template<typename T >
CImgDisplay & assign (const CImgList< T > &list, const char *title=0, const unsigned int normalization_type=3, const bool fullscreen_flag=false, const bool closed_flag=false)
In-place version of the previous constructor.
CImgDisplay & assign (const CImgDisplay &disp)
In-place version of the previous constructor.
static CImgDisplay & empty ()
Return a reference to an empty display.
static unsigned int _fitscreen (const unsigned int dx, const unsigned int dy=1, const unsigned int dz=1, const int dmin=128, const int dmax=-85, const bool return_last=false)
Instance Characteristics
int dimx () const
Return display width.
int dimy () const
Return display height.
int window_dimx () const
Return display window width.
int window_dimy () const
Return display window height.
int window_posx () const
Return X-coordinate of the window.
int window_posy () const
Return Y-coordinate of the window.
float frames_per_second ()
Return the frame per second rate.
static int screen_dimx ()
Return the width of the screen resolution.
static int screen_dimy ()
Return the height of the screen resolution.
Display Manipulation
template<typename T >
CImgDisplay & display (const CImg< T > &img)
Display an image in a window.
template<typename T >
CImgDisplay & display (const CImgList< T > &list, const char axis='x', const char align='p')
Display an image list CImgList<T> into a display window.
template<typename T >
CImgDisplay & resize (const CImg< T > &img, const bool redraw=true)
Resize a display window with the size of an image.
CImgDisplay & resize (const CImgDisplay &disp, const bool redraw=true)
Resize a display window using the size of the given display disp.
CImgDisplay & resize (const bool redraw=true)
Resize a display window in its current size.
CImgDisplay & resize (const int width, const int height, const bool redraw=true)
Resize window.
CImgDisplay & fullscreen (const bool redraw=true)
Set fullscreen mode.
CImgDisplay & normalscreen (const bool redraw=true)
Set normal screen mode.
CImgDisplay & toggle_fullscreen (const bool redraw=true)
Toggle fullscreen mode.
CImgDisplay & show ()
Show a closed display.
CImgDisplay & close ()
Close a visible display.
CImgDisplay & move (const int posx, const int posy)
Move window.
CImgDisplay & show_mouse ()
Show mouse pointer.
CImgDisplay & hide_mouse ()
Hide mouse pointer.
CImgDisplay & set_mouse (const int posx, const int posy)
Move mouse pointer to a specific location.
CImgDisplay & set_title (const char *format,...)
Set the window title.
template<typename T >
CImgDisplay & render (const CImg< T > &img)
Render image buffer into GDI native image format.
CImgDisplay & paint ()
Re-paint image content in window.
template<typename T >
const CImgDisplay & snapshot (CImg< T > &img) const
Take a snapshot of the display in the specified image.
CImgDisplay & flush ()
Clear all events of the current display.
CImgDisplay & wait (const unsigned int milliseconds)
Synchronized waiting function. Same as cimg::wait().
CImgDisplay & wait ()
Wait for an event occuring on the current display.
template<typename t , typename T >
static void _render_resize (const T *ptrs, const unsigned int ws, const unsigned int hs, t *ptrd, const unsigned int wd, const unsigned int hd)
static void wait (CImgDisplay &disp1)
Wait for any event occuring on the display disp1.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2)
Wait for any event occuring either on the display disp1 or disp2.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3)
Wait for any event occuring either on the display disp1, disp2 or disp3.
static void wait (CImgDisplay &disp1, CImgDisplay &disp2, CImgDisplay &disp3, CImgDisplay &disp4)
Wait for any event occuring either on the display disp1, disp2, disp3 or disp4.
static void wait_all ()
Wait for a window event in any CImg window.
Detailed Description
This class represents a window which can display CImg images and handles mouse and keyboard events.
Creating a CImgDisplay instance opens a window that can be used to display a CImg<T> image of a CImgList<T> image list inside. When a display is created, associated window events (such as mouse motion, keyboard and window size changes) are handled and can be easily detected by testing specific CImgDisplay data fields. See cimg_displays for a complete tutorial on using the CImgDisplay class.
Definition at line 6114 of file CImg.h.
Constructor & Destructor Documentation
~CImgDisplay () inline
Destructor.
Definition at line 6313 of file CImg.h.
References CImgDisplay::assign().
                    {
       assign();
     }
CImgDisplay () inline
Create an empty display window.
Definition at line 6318 of file CImg.h.
                  :
       width(0),height(0),window_width(0),window_height(0),mouse_x(-1),mouse_y(-1),
       normalization(0),title(0),button(*buttons),wheel(0),key(*keys),released_key(*released_keys),
       is_closed(true),is_resized(false),is_moved(false),is_event(false),is_fullscreen(false),min(0),max(0) {}
CImgDisplay (const unsigned int dimw, const unsigned int dimh, const char * title = 0, const unsigned int normalization_type = 3, const bool fullscreen_flag = false, const bool closed_flag = false) inline
Create a display window with a specified size pwidth x height.
Parameters
dimw Width of the display window.
dimh Height of the display window.
title Title of the display window.
normalization_type Normalization type of the display window (0=none, 1=always, 2=once).
fullscreen_flag : Fullscreen mode.
closed_flag : Initially visible mode. A black image will be initially displayed in the display window.
Definition at line 6332 of file CImg.h.
References CImgDisplay::assign(), and CImgDisplay::title.
                                                                                :
       width(0),height(0),window_width(0),window_height(0),mouse_x(-1),mouse_y(-1),
       normalization(0),title(0),button(*buttons),wheel(0),key(*keys),released_key(*released_keys),
       is_closed(true),is_resized(false),is_moved(false),is_event(false),is_fullscreen(false),min(0),max(0) {
       assign(dimw,dimh,title,normalization_type,fullscreen_flag,closed_flag);
     }
CImgDisplay (const CImg< T > & img, const char * title = 0, const unsigned int normalization_type = 3, const bool fullscreen_flag = false, const bool closed_flag = false) inline explicit
Create a display window from an image.
Parameters
img : Image that will be used to create the display window.
title : Title of the display window
normalization_type : Normalization type of the display window.
fullscreen_flag : Fullscreen mode.
closed_flag : Initially visible mode.
Definition at line 6349 of file CImg.h.
References CImgDisplay::assign(), and CImgDisplay::title.
                                                                                         :
       width(0),height(0),window_width(0),window_height(0),mouse_x(-1),mouse_y(-1),
       normalization(0),title(0),button(*buttons),wheel(0),key(*keys),released_key(*released_keys),
       is_closed(true),is_resized(false),is_moved(false),is_event(false),is_fullscreen(false),min(0),max(0) {
       assign(img,title,normalization_type,fullscreen_flag,closed_flag);
     }
CImgDisplay (const CImgList< T > & list, const char * title = 0, const unsigned int normalization_type = 3, const bool fullscreen_flag = false, const bool closed_flag = false) inline explicit
Create a display window from an image list.
Parameters
list : The list of images to display.
title : Title of the display window
normalization_type : Normalization type of the display window.
fullscreen_flag : Fullscreen mode.
closed_flag : Initially visible mode.
Definition at line 6366 of file CImg.h.
References CImgDisplay::assign(), and CImgDisplay::title.
                                                                                         :
       width(0),height(0),window_width(0),window_height(0),mouse_x(-1),mouse_y(-1),
       normalization(0),title(0),button(*buttons),wheel(0),key(*keys),released_key(*released_keys),
       is_closed(true),is_resized(false),is_moved(false),is_event(false),is_fullscreen(false),min(0),max(0) {
       assign(list,title,normalization_type,fullscreen_flag,closed_flag);
     }
CImgDisplay (const CImgDisplay & disp) inline
Create a display window by copying another one.
Parameters
disp : Display window to copy.
Definition at line 6379 of file CImg.h.
References CImgDisplay::assign().
                                         :
       width(0),height(0),window_width(0),window_height(0),mouse_x(-1),mouse_y(-1),
       normalization(0),title(0),button(*buttons),wheel(0),key(*keys),released_key(*released_keys),
       is_closed(true),is_resized(false),is_moved(false),is_event(false),is_fullscreen(false),min(0),max(0) {
       assign(disp);
     }
Member Function Documentation
static unsigned int _fitscreen (const unsigned int dx, const unsigned int dy = 1, const unsigned int dz = 1, const int dmin = 128, const int dmax = -85, const bool return_last = false) inline static
Definition at line 6437 of file CImg.h.
References CImgDisplay::screen_dimx(), and CImgDisplay::screen_dimy().
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), and CImg< uintT >::get_select_graph().
{
       unsigned int nw = dx + (dz>1?dz:0), nh = dy + (dz>1?dz:0);
       const unsigned int
         sw = CImgDisplay::screen_dimx(), sh = CImgDisplay::screen_dimy(),
         mw = dmin<0?(unsigned int)(sw*-dmin/100):(unsigned int)dmin,
         mh = dmin<0?(unsigned int)(sh*-dmin/100):(unsigned int)dmin,
         Mw = dmax<0?(unsigned int)(sw*-dmax/100):(unsigned int)dmax,
         Mh = dmax<0?(unsigned int)(sh*-dmax/100):(unsigned int)dmax;
       if (nw<mw) { nh = nh*mw/nw; nh+=(nh==0); nw = mw; }
       if (nh<mh) { nw = nw*mh/nh; nw+=(nw==0); nh = mh; }
       if (nw>Mw) { nh = nh*Mw/nw; nh+=(nh==0); nw = Mw; }
       if (nh>Mh) { nw = nw*Mh/nh; nw+=(nw==0); nh = Mh; }
       if (nw<mw) nw = mw;
       if (nh<mh) nh = mh;
       if (return_last) return nh;
       return nw;
     }
static void _render_resize (const T * ptrs, const unsigned int ws, const unsigned int hs, t * ptrd, const unsigned int wd, const unsigned int hd) inline static
Definition at line 6742 of file CImg.h.
References s, x, and y.
{
       unsigned int *const offx = new unsigned int[wd], *const offy = new unsigned int[hd+1], *poffx, *poffy;
       float s, curr, old;
       s = (float)ws/wd;
       poffx = offx; curr = 0; for (unsigned int x = 0; x<wd; ++x) { old=curr; curr+=s; *(poffx++) = (unsigned int)curr-(unsigned int)old; }
       s = (float)hs/hd;
       poffy = offy; curr = 0; for (unsigned int y = 0; y<hd; ++y) { old=curr; curr+=s; *(poffy++) = ws*((unsigned int)curr-(unsigned int)old); }
       *poffy = 0;
       poffy = offy;
       for (unsigned int y = 0; y<hd; ) {
         const T *ptr = ptrs;
         poffx = offx;
         for (unsigned int x = 0; x<wd; ++x) { *(ptrd++) = *ptr; ptr+=*(poffx++); }
         ++y;
         unsigned int dy=*(poffy++);
         for (;!dy && y<hd; std::memcpy(ptrd, ptrd-wd, sizeof(t)*wd), ++y, ptrd+=wd, dy=*(poffy++)) {}
         ptrs+=dy;
       }
       delete[] offx; delete[] offy;
     }
void _update_iskey (const unsigned int key, const bool pressed = true) inline
Definition at line 6586 of file CImg.h.
References _cimg_iskey_case, A, GridConversion::TestFixture::F1(), and GridConversion::TestFixture::F2().
{
 #define _cimg_iskey_case(k) if (key==cimg::key##k) is_key##k = pressed;
       _cimg_iskey_case(ESC); _cimg_iskey_case(F1); _cimg_iskey_case(F2); _cimg_iskey_case(F3);
       _cimg_iskey_case(F4); _cimg_iskey_case(F5); _cimg_iskey_case(F6); _cimg_iskey_case(F7);
       _cimg_iskey_case(F8); _cimg_iskey_case(F9); _cimg_iskey_case(F10); _cimg_iskey_case(F11);
       _cimg_iskey_case(F12); _cimg_iskey_case(PAUSE); _cimg_iskey_case(1); _cimg_iskey_case(2);
       _cimg_iskey_case(3); _cimg_iskey_case(4); _cimg_iskey_case(5); _cimg_iskey_case(6);
       _cimg_iskey_case(7); _cimg_iskey_case(8); _cimg_iskey_case(9); _cimg_iskey_case(0);
       _cimg_iskey_case(BACKSPACE); _cimg_iskey_case(INSERT); _cimg_iskey_case(HOME);
       _cimg_iskey_case(PAGEUP); _cimg_iskey_case(TAB); _cimg_iskey_case(Q); _cimg_iskey_case(W);
       _cimg_iskey_case(E); _cimg_iskey_case(R); _cimg_iskey_case(T); _cimg_iskey_case(Y);
       _cimg_iskey_case(U); _cimg_iskey_case(I); _cimg_iskey_case(O); _cimg_iskey_case(P);
       _cimg_iskey_case(DELETE); _cimg_iskey_case(END); _cimg_iskey_case(PAGEDOWN);
       _cimg_iskey_case(CAPSLOCK); _cimg_iskey_case(A); _cimg_iskey_case(S); _cimg_iskey_case(D);
       _cimg_iskey_case(F); _cimg_iskey_case(G); _cimg_iskey_case(H); _cimg_iskey_case(J);
       _cimg_iskey_case(K); _cimg_iskey_case(L); _cimg_iskey_case(ENTER);
       _cimg_iskey_case(SHIFTLEFT); _cimg_iskey_case(Z); _cimg_iskey_case(X); _cimg_iskey_case(C);
       _cimg_iskey_case(V); _cimg_iskey_case(B); _cimg_iskey_case(N); _cimg_iskey_case(M);
       _cimg_iskey_case(SHIFTRIGHT); _cimg_iskey_case(ARROWUP); _cimg_iskey_case(CTRLLEFT);
       _cimg_iskey_case(APPLEFT); _cimg_iskey_case(ALT); _cimg_iskey_case(SPACE); _cimg_iskey_case(ALTGR);
       _cimg_iskey_case(APPRIGHT); _cimg_iskey_case(MENU); _cimg_iskey_case(CTRLRIGHT);
       _cimg_iskey_case(ARROWLEFT); _cimg_iskey_case(ARROWDOWN); _cimg_iskey_case(ARROWRIGHT);
       _cimg_iskey_case(PAD0); _cimg_iskey_case(PAD1); _cimg_iskey_case(PAD2);
       _cimg_iskey_case(PAD3); _cimg_iskey_case(PAD4); _cimg_iskey_case(PAD5);
       _cimg_iskey_case(PAD6); _cimg_iskey_case(PAD7); _cimg_iskey_case(PAD8);
       _cimg_iskey_case(PAD9); _cimg_iskey_case(PADADD); _cimg_iskey_case(PADSUB);
       _cimg_iskey_case(PADMUL); _cimg_iskey_case(PADDIV);
     }
CImgDisplay& assign () inline
In-place version of the destructor.
Definition at line 6388 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), CImgDisplay::assign(), CImgDisplay::CImgDisplay(), CImg< uintT >::display_graph(), CImgDisplay::empty(), CImg< uintT >::get_select_graph(), CImgDisplay::operator=(), and CImgDisplay::~CImgDisplay().
{
       return *this;
     }
CImgDisplay& assign (const unsigned int dimw, const unsigned int dimh, const char * title = 0, const unsigned int normalization_type = 3, const bool fullscreen_flag = false, const bool closed_flag = false) inline
In-place version of the previous constructor.
Definition at line 6393 of file CImg.h.
References CImgDisplay::title.
{
       throw CImgDisplayException("CImgDisplay() : Display has been required but is not available (cimg_display=0)");
       const char* avoid_warning = title + dimw + dimh + normalization_type + (int)fullscreen_flag + (int)closed_flag;
       avoid_warning = 0;
       return *this;
     }
CImgDisplay& assign (const CImg< T > & img, const char * title = 0, const unsigned int normalization_type = 3, const bool fullscreen_flag = false, const bool closed_flag = false) inline
In-place version of the previous constructor.
Definition at line 6404 of file CImg.h.
References CImgDisplay::assign(), CImgDisplay::title, and CImg< T >::width.
{
       throw CImgDisplayException("CImgDisplay()::assign() : Display has been required but is not available (cimg_display=0)");
       const char* avoid_warning = title + img.width + normalization_type + (int)fullscreen_flag + (int)closed_flag;
       avoid_warning = 0;
       return assign(0,0);
     }
CImgDisplay& assign (const CImgList< T > & list, const char * title = 0, const unsigned int normalization_type = 3, const bool fullscreen_flag = false, const bool closed_flag = false) inline
In-place version of the previous constructor.
Definition at line 6415 of file CImg.h.
References CImgDisplay::assign(), CImgDisplay::title, and CImgList< T >::width.
{
       throw CImgDisplayException("CImgDisplay()::assign() : Display has been required but is not available (cimg_display=0)");
       const char* avoid_warning = title + list.width + normalization_type + (int)fullscreen_flag + (int)closed_flag;
       avoid_warning = 0;
       return assign(0,0);
     }
CImgDisplay& assign (const CImgDisplay & disp) inline
In-place version of the previous constructor.
Definition at line 6425 of file CImg.h.
References CImgDisplay::assign(), CImgDisplay::height, and CImgDisplay::width.
{
       return assign(disp.width,disp.height);
     }
CImgDisplay& close () inline
Close a visible display.
Definition at line 6791 of file CImg.h.
{
       return *this;
     }
int dimx () const inline
Return display width.
Definition at line 6623 of file CImg.h.
References CImgDisplay::width.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), cimg_library::cimg::dialog(), CImg< uintT >::display_graph(), and CImg< uintT >::get_select_graph().
                      {
       return (int)width;
     }
int dimy () const inline
Return display height.
Definition at line 6628 of file CImg.h.
References CImgDisplay::height.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), cimg_library::cimg::dialog(), CImg< uintT >::display_graph(), and CImg< uintT >::get_select_graph().
                      {
       return (int)height;
     }
CImgDisplay& display (const CImg< T > & img) inline
Display an image in a window.
Definition at line 6689 of file CImg.h.
References CImg< T >::width.
Referenced by CImg< uintT >::_get_select(), CImgDisplay::display(), CImg< uintT >::display(), and CImgDisplay::operator=().
{
       unsigned int avoid_warning = img.width;
       avoid_warning = 0;
       return *this;
     }
CImgDisplay& display (const CImgList< T > & list, const char axis = 'x', const char align = 'p') inline
Display an image list CImgList<T> into a display window.
First, all images of the list are appended into a single image used for visualization, then this image is displayed in the current display window.
Parameters
list : The list of images to display.
axis : The axis used to append the image for visualization. Can be 'x' (default),'y','z' or 'v'.
align : Defines the relative alignment of images when displaying images of different sizes. Can be 'c' (centered, which is the default), 'p' (top alignment) and 'n' (bottom aligment).
Definition at line 6705 of file CImg.h.
References CImgDisplay::display(), and CImgList< T >::get_append().
{
       return display(list.get_append(axis,align));
     }
static CImgDisplay& empty (void) inline static
Return a reference to an empty display.
Definition at line 6431 of file CImg.h.
References CImgDisplay::assign().
{
       static CImgDisplay _empty;
       return _empty.assign();
     }
CImgDisplay& flush () inline
Clear all events of the current display.
Definition at line 6848 of file CImg.h.
References CImgDisplay::buttons, CImgDisplay::fps_fps, CImgDisplay::fps_frames, CImgDisplay::fps_timer, CImgDisplay::is_event, CImgDisplay::is_key0, CImgDisplay::is_key1, CImgDisplay::is_key2, CImgDisplay::is_key3, CImgDisplay::is_key4, CImgDisplay::is_key5, CImgDisplay::is_key6, CImgDisplay::is_key7, CImgDisplay::is_key8, CImgDisplay::is_key9, CImgDisplay::is_keyA, CImgDisplay::is_keyALT, CImgDisplay::is_keyALTGR, CImgDisplay::is_keyAPPLEFT, CImgDisplay::is_keyAPPRIGHT, CImgDisplay::is_keyARROWDOWN, CImgDisplay::is_keyARROWLEFT, CImgDisplay::is_keyARROWRIGHT, CImgDisplay::is_keyARROWUP, CImgDisplay::is_keyB, CImgDisplay::is_keyBACKSPACE, CImgDisplay::is_keyC, CImgDisplay::is_keyCAPSLOCK, CImgDisplay::is_keyCTRLLEFT, CImgDisplay::is_keyCTRLRIGHT, CImgDisplay::is_keyD, CImgDisplay::is_keyDELETE, CImgDisplay::is_keyE, CImgDisplay::is_keyEND, CImgDisplay::is_keyENTER, CImgDisplay::is_keyESC, CImgDisplay::is_keyF, CImgDisplay::is_keyF1, CImgDisplay::is_keyF10, CImgDisplay::is_keyF11, CImgDisplay::is_keyF12, CImgDisplay::is_keyF2, CImgDisplay::is_keyF3, CImgDisplay::is_keyF4, CImgDisplay::is_keyF5, CImgDisplay::is_keyF6, CImgDisplay::is_keyF7, CImgDisplay::is_keyF8, CImgDisplay::is_keyF9, CImgDisplay::is_keyG, CImgDisplay::is_keyH, CImgDisplay::is_keyHOME, CImgDisplay::is_keyI, CImgDisplay::is_keyINSERT, CImgDisplay::is_keyJ, CImgDisplay::is_keyK, CImgDisplay::is_keyL, CImgDisplay::is_keyM, CImgDisplay::is_keyMENU, CImgDisplay::is_keyN, CImgDisplay::is_keyO, CImgDisplay::is_keyP, CImgDisplay::is_keyPAD0, CImgDisplay::is_keyPAD1, CImgDisplay::is_keyPAD2, CImgDisplay::is_keyPAD3, CImgDisplay::is_keyPAD4, CImgDisplay::is_keyPAD5, CImgDisplay::is_keyPAD6, CImgDisplay::is_keyPAD7, CImgDisplay::is_keyPAD8, CImgDisplay::is_keyPAD9, CImgDisplay::is_keyPADADD, CImgDisplay::is_keyPADDIV, CImgDisplay::is_keyPADMUL, CImgDisplay::is_keyPADSUB, CImgDisplay::is_keyPAGEDOWN, CImgDisplay::is_keyPAGEUP, CImgDisplay::is_keyPAUSE, CImgDisplay::is_keyQ, CImgDisplay::is_keyR, CImgDisplay::is_keyS, CImgDisplay::is_keySHIFTLEFT, CImgDisplay::is_keySHIFTRIGHT, CImgDisplay::is_keySPACE, CImgDisplay::is_keyT, CImgDisplay::is_keyTAB, CImgDisplay::is_keyU, CImgDisplay::is_keyV, CImgDisplay::is_keyW, CImgDisplay::is_keyX, CImgDisplay::is_keyY, CImgDisplay::is_keyZ, CImgDisplay::is_moved, CImgDisplay::is_resized, CImgDisplay::keys, CImgDisplay::mouse_x, CImgDisplay::mouse_y, CImgDisplay::released_keys, CImgDisplay::timer, and CImgDisplay::wheel.
Referenced by CImg< uintT >::_display_object3d(), and CImg< uintT >::display_graph().
{
       std::memset((void*)buttons,0,512*sizeof(unsigned int));
       std::memset((void*)keys,0,512*sizeof(unsigned int));
       std::memset((void*)released_keys,0,512*sizeof(unsigned int));
       is_keyESC = is_keyF1 = is_keyF2 = is_keyF3 = is_keyF4 = is_keyF5 = is_keyF6 = is_keyF7 = is_keyF8 = is_keyF9 =
         is_keyF10 = is_keyF11 = is_keyF12 = is_keyPAUSE = is_key1 = is_key2 = is_key3 = is_key4 = is_key5 = is_key6 =
         is_key7 = is_key8 = is_key9 = is_key0 = is_keyBACKSPACE = is_keyINSERT = is_keyHOME = is_keyPAGEUP = is_keyTAB =
         is_keyQ = is_keyW = is_keyE = is_keyR = is_keyT = is_keyY = is_keyU = is_keyI = is_keyO = is_keyP = is_keyDELETE =
         is_keyEND = is_keyPAGEDOWN = is_keyCAPSLOCK = is_keyA = is_keyS = is_keyD = is_keyF = is_keyG = is_keyH = is_keyJ =
         is_keyK = is_keyL = is_keyENTER = is_keySHIFTLEFT = is_keyZ = is_keyX = is_keyC = is_keyV = is_keyB = is_keyN =
         is_keyM = is_keySHIFTRIGHT = is_keyARROWUP = is_keyCTRLLEFT = is_keyAPPLEFT = is_keyALT = is_keySPACE = is_keyALTGR = is_keyAPPRIGHT =
         is_keyMENU = is_keyCTRLRIGHT = is_keyARROWLEFT = is_keyARROWDOWN = is_keyARROWRIGHT = is_keyPAD0 = is_keyPAD1 = is_keyPAD2 =
         is_keyPAD3 = is_keyPAD4 = is_keyPAD5 = is_keyPAD6 = is_keyPAD7 = is_keyPAD8 = is_keyPAD9 = is_keyPADADD = is_keyPADSUB =
         is_keyPADMUL = is_keyPADDIV = false;
       is_resized = is_moved = is_event = false;
       fps_timer = fps_frames = timer = wheel = 0;
       mouse_x = mouse_y = -1;
       fps_fps = 0;
       return *this;
     }
float frames_per_second () inline
Return the frame per second rate.
Definition at line 6667 of file CImg.h.
References CImgDisplay::fps_fps, CImgDisplay::fps_frames, CImgDisplay::fps_timer, and cimg_library::cimg::time().
{
       if (!fps_timer) fps_timer = cimg::time();
       const float delta = (cimg::time()-fps_timer)/1000.0f;
       ++fps_frames;
       if (delta>=1) {
         fps_fps = fps_frames/delta;
         fps_frames = 0;
         fps_timer = cimg::time();
       }
       return fps_fps;
     }
CImgDisplay& fullscreen (const bool redraw = true) inline
Set fullscreen mode.
Definition at line 6765 of file CImg.h.
References CImgDisplay::is_empty(), CImgDisplay::is_fullscreen, and CImgDisplay::toggle_fullscreen().
{
       if (is_empty() || is_fullscreen) return *this;
       return toggle_fullscreen(redraw);
     }
CImgDisplay& hide_mouse () inline
Hide mouse pointer.
Definition at line 6808 of file CImg.h.
{
       return *this;
     }
bool is_empty () const inline
Return true is display is empty.
Definition at line 6493 of file CImg.h.
References CImgDisplay::height, and CImgDisplay::width.
Referenced by CImgDisplay::fullscreen(), CImgDisplay::normalscreen(), CImgDisplay::operator bool(), and CImgDisplay::wait().
{
       return (!width || !height);
     }
bool is_key (const bool remove = false) inline
Test if any key has been pressed.
Definition at line 6498 of file CImg.h.
References CImgDisplay::keys.
Referenced by CImgDisplay::is_key().
{
       for (unsigned int *ptrs=(unsigned int*)keys+512-1; ptrs>=keys; --ptrs) if (*ptrs) { if (remove) *ptrs = 0; return true; }
       return false;
     }
bool is_key (const unsigned int key1, const bool remove) inline
Test if a key has been pressed.
Definition at line 6504 of file CImg.h.
References CImgDisplay::keys.
{
       for (unsigned int *ptrs=(unsigned int*)keys+512-1; ptrs>=keys; --ptrs) if (*ptrs==key1) { if (remove) *ptrs = 0; return true; }
       return false;
     }
bool is_key (const unsigned int key1, const unsigned int key2, const bool remove) inline
Test if a key sequence has been typed.
Definition at line 6510 of file CImg.h.
References CImgDisplay::is_key(), and cimg_library::cimg::key1.
{
       const unsigned int seq[] = { key1, key2 };
       return is_key(seq,2,remove);
     }
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const bool remove) inline
Test if a key sequence has been typed.
Definition at line 6516 of file CImg.h.
References CImgDisplay::is_key(), cimg_library::cimg::key1, and cimg_library::cimg::key2.
{
       const unsigned int seq[] = { key1, key2, key3 };
       return is_key(seq,3,remove);
     }
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const bool remove) inline
Test if a key sequence has been typed.
Definition at line 6522 of file CImg.h.
References CImgDisplay::is_key(), cimg_library::cimg::key1, cimg_library::cimg::key2, and cimg_library::cimg::key3.
{
       const unsigned int seq[] = { key1, key2, key3, key4 };
       return is_key(seq,4,remove);
     }
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const bool remove) inline
Test if a key sequence has been typed.
Definition at line 6529 of file CImg.h.
References CImgDisplay::is_key(), cimg_library::cimg::key1, cimg_library::cimg::key2, cimg_library::cimg::key3, and cimg_library::cimg::key4.
{
       const unsigned int seq[] = { key1, key2, key3, key4, key5 };
       return is_key(seq,5,remove);
     }
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const unsigned int key6, const bool remove) inline
Test if a key sequence has been typed.
Definition at line 6536 of file CImg.h.
References CImgDisplay::is_key(), cimg_library::cimg::key1, cimg_library::cimg::key2, cimg_library::cimg::key3, cimg_library::cimg::key4, and cimg_library::cimg::key5.
{
       const unsigned int seq[] = { key1, key2, key3, key4, key5, key6 };
       return is_key(seq,6,remove);
     }
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const unsigned int key6, const unsigned int key7, const bool remove) inline
Test if a key sequence has been typed.
Definition at line 6543 of file CImg.h.
References CImgDisplay::is_key(), cimg_library::cimg::key1, cimg_library::cimg::key2, cimg_library::cimg::key3, cimg_library::cimg::key4, cimg_library::cimg::key5, and cimg_library::cimg::key6.
{
       const unsigned int seq[] = { key1, key2, key3, key4, key5, key6, key7 };
       return is_key(seq,7,remove);
     }
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const unsigned int key6, const unsigned int key7, const unsigned int key8, const bool remove) inline
Test if a key sequence has been typed.
Definition at line 6551 of file CImg.h.
References CImgDisplay::is_key(), cimg_library::cimg::key1, cimg_library::cimg::key2, cimg_library::cimg::key3, cimg_library::cimg::key4, cimg_library::cimg::key5, cimg_library::cimg::key6, and cimg_library::cimg::key7.
{
       const unsigned int seq[] = { key1, key2, key3, key4, key5, key6, key7, key8 };
       return is_key(seq,8,remove);
     }
bool is_key (const unsigned int key1, const unsigned int key2, const unsigned int key3, const unsigned int key4, const unsigned int key5, const unsigned int key6, const unsigned int key7, const unsigned int key8, const unsigned int key9, const bool remove) inline
Test if a key sequence has been typed.
Definition at line 6559 of file CImg.h.
References CImgDisplay::is_key(), cimg_library::cimg::key1, cimg_library::cimg::key2, cimg_library::cimg::key3, cimg_library::cimg::key4, cimg_library::cimg::key5, cimg_library::cimg::key6, cimg_library::cimg::key7, and cimg_library::cimg::key8.
{
       const unsigned int seq[] = { key1, key2, key3, key4, key5, key6, key7, key8, key9 };
       return is_key(seq,9,remove);
     }
bool is_key (const unsigned int *const keyseq, const unsigned int N, const bool remove = true) inline
Test if a key sequence has been typed.
Definition at line 6567 of file CImg.h.
References i, k, and CImgDisplay::keys.
{
       if (keyseq && N) {
         const unsigned int *const ps_end = keyseq+N-1, k = *ps_end, *const pk_end = (unsigned int*)keys+1+512-N;
         for (unsigned int *pk = (unsigned int*)keys; pk<pk_end; ) {
           if (*(pk++)==k) {
             bool res = true;
             const unsigned int *ps = ps_end, *pk2 = pk;
             for (unsigned int i=1; i<N; ++i) res = (*(--ps)==*(pk2++));
             if (res) {
               if (remove) std::memset((void*)(pk-1),0,sizeof(unsigned int)*N);
               return true;
             }
           }
         }
       }
       return false;
     }
CImgDisplay& move (const int posx, const int posy) inline
Move window.
Definition at line 6796 of file CImg.h.
Referenced by cimg_library::cimg::dialog().
{
       int avoid_warning = posx | posy;
       avoid_warning = 0;
       return *this;
     }
CImgDisplay& normalscreen (const bool redraw = true) inline
Set normal screen mode.
Definition at line 6771 of file CImg.h.
References CImgDisplay::is_empty(), CImgDisplay::is_fullscreen, and CImgDisplay::toggle_fullscreen().
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), and CImg< uintT >::get_select_graph().
{
       if (is_empty() || !is_fullscreen) return *this;
       return toggle_fullscreen(redraw);
     }
operator bool () const inline
Return true if display is not empty.
Definition at line 6481 of file CImg.h.
References CImgDisplay::is_empty().
{
       return !is_empty();
     }
CImgDisplay& operator= (const CImg< t > & img) inline
Definition at line 6465 of file CImg.h.
References CImgDisplay::display().
{
       return display(img);
     }
CImgDisplay& operator= (const CImgList< t > & list) inline
Definition at line 6471 of file CImg.h.
References CImgDisplay::display().
{
       return display(list);
     }
CImgDisplay& operator= (const CImgDisplay & disp) inline
Operator=().
Definition at line 6476 of file CImg.h.
References CImgDisplay::assign().
{
       return assign(disp);
     }
CImgDisplay& paint () inline
Re-paint image content in window.
Definition at line 6835 of file CImg.h.
{
       return *this;
     }
CImgDisplay& render (const CImg< T > & img) inline
Render image buffer into GDI native image format.
Definition at line 6828 of file CImg.h.
References CImg< T >::width.
{
       unsigned int avoid_warning = img.width;
       avoid_warning = 0;
       return *this;
     }
CImgDisplay& resize (const CImg< T > & img, const bool redraw = true) inline
Resize a display window with the size of an image.
Parameters
img : Input image. image.width and image.height give the new dimensions of the display window.
redraw : If true (default), the current displayed image in the display window will be bloc-interpolated to fit the new dimensions. If false, a black image will be drawn in the resized window.
Definition at line 6715 of file CImg.h.
References CImg< T >::height, and CImg< T >::width.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), CImg< uintT >::get_select_graph(), and CImgDisplay::resize().
{
       return resize(img.width,img.height,redraw);
     }
CImgDisplay& resize (const CImgDisplay & disp, const bool redraw = true) inline
Resize a display window using the size of the given display disp.
Definition at line 6720 of file CImg.h.
References CImgDisplay::height, CImgDisplay::resize(), and CImgDisplay::width.
{
       return resize(disp.width,disp.height,redraw);
     }
CImgDisplay& resize (const bool redraw = true) inline
Resize a display window in its current size.
Definition at line 6725 of file CImg.h.
References CImgDisplay::resize(), CImgDisplay::window_height, and CImgDisplay::window_width.
{
       resize(window_width,window_height,redraw);
       return *this;
     }
CImgDisplay& resize (const int width, const int height, const bool redraw = true) inline
Resize window.
Definition at line 6733 of file CImg.h.
{
       int avoid_warning = width | height | (int)redraw;
       avoid_warning = 0;
       return *this;
     }
static int screen_dimx () inline static
Return the width of the screen resolution.
Definition at line 6655 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImgDisplay::_fitscreen(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), and CImg< uintT >::get_select_graph().
{
       return 0;
     }
static int screen_dimy () inline static
Return the height of the screen resolution.
Definition at line 6660 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImgDisplay::_fitscreen(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), and CImg< uintT >::get_select_graph().
{
       return 0;
     }
CImgDisplay& set_mouse (const int posx, const int posy) inline
Move mouse pointer to a specific location.
Definition at line 6813 of file CImg.h.
{
       int avoid_warning = posx | posy;
       avoid_warning = 0;
       return *this;
     }
CImgDisplay& set_title (const char * format, ...) inline
Set the window title.
Definition at line 6820 of file CImg.h.
Referenced by CImg< uintT >::_display().
{
       const char *avoid_warning = format;
       avoid_warning = 0;
       return *this;
     }
CImgDisplay& show () inline
Show a closed display.
Definition at line 6786 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), CImg< uintT >::display_graph(), and CImg< uintT >::get_select_graph().
{
       return *this;
     }
CImgDisplay& show_mouse () inline
Show mouse pointer.
Definition at line 6803 of file CImg.h.
{
       return *this;
     }
const CImgDisplay& snapshot (CImg< T > & img) const inline
Take a snapshot of the display in the specified image.
Definition at line 6841 of file CImg.h.
References CImg< T >::assign(), CImgDisplay::height, and CImgDisplay::width.
Referenced by CImg< uintT >::assign(), CImg< uintT >::CImg(), and CImg< uintT >::operator=().
{
       img.assign(width,height,1,3,0);
       return *this;
     }
CImgDisplay& toggle_fullscreen (const bool redraw = true) inline
Toggle fullscreen mode.
Definition at line 6779 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d(), CImgDisplay::fullscreen(), and CImgDisplay::normalscreen().
{
       bool avoid_warning = redraw;
       avoid_warning = false;
       return *this;
     }
CImgDisplay& wait (const unsigned int milliseconds) inline
Synchronized waiting function. Same as cimg::wait().
Definition at line 6870 of file CImg.h.
References cimg_library::cimg::_sleep(), and CImgDisplay::timer.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), and CImg< uintT >::get_select_graph().
{
       cimg::_sleep(milliseconds,timer);
       return *this;
     }
CImgDisplay& wait () inline
Wait for an event occuring on the current display.
Definition at line 6876 of file CImg.h.
References CImgDisplay::is_empty().
{
       if (!is_empty()) wait(*this);
       return *this;
     }
static void wait (CImgDisplay & disp1) inline static
Wait for any event occuring on the display disp1.
Definition at line 6882 of file CImg.h.
References CImgDisplay::is_event, and CImgDisplay::wait_all().
{
       disp1.is_event = 0;
       while (!disp1.is_event) wait_all();
     }
static void wait (CImgDisplay & disp1, CImgDisplay & disp2) inline static
Wait for any event occuring either on the display disp1 or disp2.
Definition at line 6888 of file CImg.h.
References CImgDisplay::is_event, and CImgDisplay::wait_all().
{
       disp1.is_event = disp2.is_event = 0;
       while (!disp1.is_event && !disp2.is_event) wait_all();
     }
static void wait (CImgDisplay & disp1, CImgDisplay & disp2, CImgDisplay & disp3) inline static
Wait for any event occuring either on the display disp1, disp2 or disp3.
Definition at line 6894 of file CImg.h.
References CImgDisplay::is_event, and CImgDisplay::wait_all().
{
       disp1.is_event = disp2.is_event = disp3.is_event = 0;
       while (!disp1.is_event && !disp2.is_event && !disp3.is_event) wait_all();
     }
static void wait (CImgDisplay & disp1, CImgDisplay & disp2, CImgDisplay & disp3, CImgDisplay & disp4) inline static
Wait for any event occuring either on the display disp1, disp2, disp3 or disp4.
Definition at line 6900 of file CImg.h.
References CImgDisplay::is_event, and CImgDisplay::wait_all().
{
       disp1.is_event = disp2.is_event = disp3.is_event = disp4.is_event = 0;
       while (!disp1.is_event && !disp2.is_event && !disp3.is_event && !disp4.is_event) wait_all();
     }
static void wait_all () inline static
Wait for a window event in any CImg window.
Definition at line 6908 of file CImg.h.
Referenced by CImgDisplay::wait().
 {}
int window_dimx () const inline
Return display window width.
Definition at line 6633 of file CImg.h.
References CImgDisplay::window_width.
{
       return (int)window_width;
     }
int window_dimy () const inline
Return display window height.
Definition at line 6638 of file CImg.h.
References CImgDisplay::window_height.
{
       return (int)window_height;
     }
int window_posx () const inline
Return X-coordinate of the window.
Definition at line 6643 of file CImg.h.
References CImgDisplay::window_x.
{
       return window_x;
     }
int window_posy () const inline
Return Y-coordinate of the window.
Definition at line 6648 of file CImg.h.
References CImgDisplay::window_y.
{
       return window_y;
     }
Member Data Documentation
volatile unsigned int& button
Definition at line 6148 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), and CImg< uintT >::get_select_graph().
volatile unsigned int buttons[512]
Button state of the mouse.
Definition at line 6147 of file CImg.h.
Referenced by CImgDisplay::flush().
float fps_fps
Definition at line 6267 of file CImg.h.
Referenced by CImgDisplay::flush(), and CImgDisplay::frames_per_second().
unsigned long fps_frames
Definition at line 6268 of file CImg.h.
Referenced by CImgDisplay::flush(), and CImgDisplay::frames_per_second().
unsigned long fps_timer
Definition at line 6268 of file CImg.h.
Referenced by CImgDisplay::flush(), and CImgDisplay::frames_per_second().
unsigned int height
Height of the display.
Definition at line 6120 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), CImgDisplay::assign(), CImgDisplay::dimy(), CImg< uintT >::get_resize(), CImg< uintT >::get_select_graph(), CImgDisplay::is_empty(), CImg< uintT >::is_sameY(), CImgDisplay::resize(), CImg< uintT >::resize(), and CImgDisplay::snapshot().
volatile bool is_closed
Closed state of the window.
Definition at line 6162 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), CImg< uintT >::display_graph(), and CImg< uintT >::get_select_graph().
volatile bool is_event
Event state of the window.
Definition at line 6171 of file CImg.h.
Referenced by CImgDisplay::flush(), and CImgDisplay::wait().
bool is_fullscreen
Fullscreen state of the display.
Definition at line 6264 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d(), CImgDisplay::fullscreen(), and CImgDisplay::normalscreen().
volatile bool is_key0
Definition at line 6197 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_key1
Definition at line 6188 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_key2
Definition at line 6189 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_key3
Definition at line 6190 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_key4
Definition at line 6191 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_key5
Definition at line 6192 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_key6
Definition at line 6193 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_key7
Definition at line 6194 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_key8
Definition at line 6195 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_key9
Definition at line 6196 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyA
Definition at line 6217 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyALT
Definition at line 6239 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_get_select(), and CImgDisplay::flush().
volatile bool is_keyALTGR
Definition at line 6241 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyAPPLEFT
Definition at line 6238 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyAPPRIGHT
Definition at line 6242 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyARROWDOWN
Definition at line 6246 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyARROWLEFT
Definition at line 6245 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyARROWRIGHT
Definition at line 6247 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyARROWUP
Definition at line 6236 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyB
Definition at line 6232 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyBACKSPACE
Definition at line 6198 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyC
Definition at line 6230 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyCAPSLOCK
Definition at line 6216 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyCTRLLEFT
Definition at line 6237 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), CImg< uintT >::display_graph(), CImgDisplay::flush(), and CImg< uintT >::get_select_graph().
volatile bool is_keyCTRLRIGHT
Definition at line 6244 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyD
Definition at line 6219 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyDELETE
Definition at line 6213 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyE
Definition at line 6205 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyEND
Definition at line 6214 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyENTER
Definition at line 6226 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyESC
Current state of the corresponding key (exists for all referenced keys).
Definition at line 6174 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF
Definition at line 6220 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF1
Definition at line 6175 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF10
Definition at line 6184 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF11
Definition at line 6185 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF12
Definition at line 6186 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF2
Definition at line 6176 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF3
Definition at line 6177 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF4
Definition at line 6178 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF5
Definition at line 6179 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF6
Definition at line 6180 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF7
Definition at line 6181 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF8
Definition at line 6182 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyF9
Definition at line 6183 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyG
Definition at line 6221 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyH
Definition at line 6222 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyHOME
Definition at line 6200 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyI
Definition at line 6210 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyINSERT
Definition at line 6199 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyJ
Definition at line 6223 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyK
Definition at line 6224 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyL
Definition at line 6225 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyM
Definition at line 6234 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyMENU
Definition at line 6243 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyN
Definition at line 6233 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyO
Definition at line 6211 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyP
Definition at line 6212 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD0
Definition at line 6248 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD1
Definition at line 6249 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD2
Definition at line 6250 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD3
Definition at line 6251 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD4
Definition at line 6252 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD5
Definition at line 6253 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD6
Definition at line 6254 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD7
Definition at line 6255 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD8
Definition at line 6256 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAD9
Definition at line 6257 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPADADD
Definition at line 6258 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPADDIV
Definition at line 6261 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPADMUL
Definition at line 6260 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPADSUB
Definition at line 6259 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAGEDOWN
Definition at line 6215 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAGEUP
Definition at line 6201 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyPAUSE
Definition at line 6187 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyQ
Definition at line 6203 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyR
Definition at line 6206 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyS
Definition at line 6218 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keySHIFTLEFT
Definition at line 6227 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_get_select(), and CImgDisplay::flush().
volatile bool is_keySHIFTRIGHT
Definition at line 6235 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keySPACE
Definition at line 6240 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyT
Definition at line 6207 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyTAB
Definition at line 6202 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyU
Definition at line 6209 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyV
Definition at line 6231 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyW
Definition at line 6204 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyX
Definition at line 6229 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyY
Definition at line 6208 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_keyZ
Definition at line 6228 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_moved
Moved state of the window.
Definition at line 6168 of file CImg.h.
Referenced by CImgDisplay::flush().
volatile bool is_resized
Resized state of the window.
Definition at line 6165 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), CImgDisplay::flush(), and CImg< uintT >::get_select_graph().
volatile unsigned int& key
Key value if pressed.
Definition at line 6154 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), CImg< uintT >::display_graph(), and CImg< uintT >::get_select_graph().
volatile unsigned int keys[512]
Definition at line 6155 of file CImg.h.
Referenced by CImgDisplay::flush(), and CImgDisplay::is_key().
float max
Definition at line 6267 of file CImg.h.
float min
Definition at line 6267 of file CImg.h.
volatile int mouse_x
X-coordinate of the mouse pointer on the display.
Definition at line 6135 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), CImg< uintT >::display_graph(), CImgDisplay::flush(), and CImg< uintT >::get_select_graph().
volatile int mouse_y
Y-coordinate of the mouse pointer on the display.
Definition at line 6138 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), cimg_library::cimg::dialog(), CImg< uintT >::display_graph(), CImgDisplay::flush(), and CImg< uintT >::get_select_graph().
unsigned int normalization
Normalization type used for the display.
Definition at line 6141 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), CImg< uintT >::display_graph(), and CImg< uintT >::get_select_graph().
volatile unsigned int& released_key
Key value if released.
Definition at line 6158 of file CImg.h.
volatile unsigned int released_keys[512]
Definition at line 6159 of file CImg.h.
Referenced by CImgDisplay::flush().
unsigned long timer
Definition at line 6268 of file CImg.h.
Referenced by CImgDisplay::flush(), and CImgDisplay::wait().
char* title
Display title.
Definition at line 6144 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImgDisplay::assign(), CImgDisplay::CImgDisplay(), and CImgList< uintT >::display().
volatile int wheel
Wheel state of the mouse.
Definition at line 6151 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), CImg< uintT >::display_graph(), CImgDisplay::flush(), and CImg< uintT >::get_select_graph().
unsigned int width
Width of the display.
Definition at line 6117 of file CImg.h.
Referenced by CImg< uintT >::_display(), CImg< uintT >::_display_object3d(), CImg< uintT >::_get_select(), CImgDisplay::assign(), CImgDisplay::dimx(), CImg< uintT >::get_resize(), CImg< uintT >::get_select_graph(), CImgDisplay::is_empty(), CImg< uintT >::is_sameX(), CImgDisplay::resize(), CImg< uintT >::resize(), and CImgDisplay::snapshot().
volatile unsigned int window_height
Height of the underlying window.
Definition at line 6126 of file CImg.h.
Referenced by CImgDisplay::resize(), and CImgDisplay::window_dimy().
volatile unsigned int window_width
Width of the underlying window.
Definition at line 6123 of file CImg.h.
Referenced by CImgDisplay::resize(), and CImgDisplay::window_dimx().
volatile int window_x
X-pos of the display on the screen.
Definition at line 6129 of file CImg.h.
Referenced by CImgDisplay::window_posx().
volatile int window_y
Y-pos of the display on the screen.
Definition at line 6132 of file CImg.h.
Referenced by CImgDisplay::window_posy().
The documentation for this struct was generated from the following file:
CImg.h