Rocstar: Tuple_traits< T > Struct Template Reference
Tuple_traits< T > Struct Template Reference
#include <Tuple.h>
Public Types
typedef T Value
typedef const T Value_opposite
typedef T * Pointer
typedef const T * Const_pointer
typedef T & Reference
typedef const T & Init_reference
typedef const T & Const_reference
typedef T * Pointer_equivalent
Static Public Member Functions
static Reference ref (Pointer_equivalent p)
Detailed Description
template<class T>
struct Tuple_traits< T >
Definition at line 33 of file Tuple.h.
Member Typedef Documentation
typedef const T* Const_pointer
Definition at line 37 of file Tuple.h.
typedef const T& Const_reference
Definition at line 40 of file Tuple.h.
typedef const T& Init_reference
Definition at line 39 of file Tuple.h.
typedef T* Pointer
Definition at line 36 of file Tuple.h.
typedef T* Pointer_equivalent
Definition at line 41 of file Tuple.h.
typedef T& Reference
Definition at line 38 of file Tuple.h.
typedef T Value
Definition at line 34 of file Tuple.h.
typedef const T Value_opposite
Definition at line 35 of file Tuple.h.
Member Function Documentation
static Reference ref (Pointer_equivalent p) inline static
Definition at line 42 of file Tuple.h.
Referenced by Two_tuple< T >::operator[](), Three_tuple< int >::operator[](), and Four_tuple< T >::operator[]().
 { return *p; }
The documentation for this struct was generated from the following file:
Tuple.h