Rocstar: type< T > Struct Template Reference
type< T > Struct Template Reference
#include <CImg.h>
Static Public Member Functions
static const char * string ()
static bool is_float ()
static T min ()
static T max ()
static const char * format ()
static const char * format (const T val)
Detailed Description
template<typename T>
struct cimg_library::cimg::type< T >
Definition at line 2084 of file CImg.h.
Member Function Documentation
static const char* format () inline static
Definition at line 2096 of file CImg.h.
 { return "%s"; }
static const char* format (const T val) inline static
Definition at line 2097 of file CImg.h.
References s.
 { static const char *s = "unknown"; return s; }
static bool is_float () inline static
Definition at line 2093 of file CImg.h.
 { return false; }
static T max (void) inline static
Definition at line 2095 of file CImg.h.
Referenced by CImg< uintT >::_display_object3d(), CImg< uintT >::_draw_scanline(), CImg< uintT >::blur_anisotropic(), CImg< uintT >::dijkstra(), CImg< uintT >::draw_triangle(), CImg< uintT >::get_displacement_field(), CImg< uintT >::get_erode(), CImg< uintT >::get_index(), CImg< uintT >::noise(), and CImg< uintT >::PSNR().
 { return (T)-1>0?(T)-1:~((T)-1<<(8*sizeof(T)-1)); }
static T min () inline static
Definition at line 2094 of file CImg.h.
Referenced by CImg< uintT >::blur_anisotropic(), CImg< uintT >::draw_plasma(), and CImg< uintT >::get_dilate().
 { return (T)-1>0?(T)0:(T)-1<<(8*sizeof(T)-1); }
static const char* string () inline static
Definition at line 2085 of file CImg.h.
References s.
Referenced by data_declarations::length(), makenumberedkeys(), CImg< uintT >::pixel_type(), CImgList< uintT >::pixel_type(), and select_bbx().
{
         static const char* s[] = { "unknown",   "unknown8",   "unknown16",  "unknown24",
                                    "unknown32", "unknown40",  "unknown48",  "unknown56",
                                    "unknown64", "unknown72",  "unknown80",  "unknown88",
                                    "unknown96", "unknown104", "unknown112", "unknown120",
                                    "unknown128" };
         return s[(sizeof(T)<17)?sizeof(T):0];
       }
The documentation for this struct was generated from the following file:
CImg.h