Rocstar: Scheduler::ActionItem Struct Reference
Scheduler::ActionItem Struct Reference
#include <Scheduler.h>
Public Member Functions
ActionItem (Action *a)
unsigned int n_write ()
unsigned int n_read ()
char * name ()
Action * action ()
int fullfilled ()
int hasInput (const char *attr, int idx)
int hasOutput (const char *attr, int idx)
void print (FILE *f)
Public Attributes
Action * myaction
vector< const char * > read_attr
vector< int > read_idx
vector< const char * > write_attr
vector< int > write_idx
ActionList input
ActionList output
int print_flag
Detailed Description
Definition at line 57 of file Scheduler.h.
Constructor & Destructor Documentation
ActionItem (Action * a) inline
Definition at line 67 of file Scheduler.h.
 : myaction(a) {}
Member Function Documentation
Action* action () inline
Definition at line 71 of file Scheduler.h.
Referenced by __scalegrd.f90__(), Scheduler::finalize_actions(), Scheduler::init_actions(), Scheduler::print_helper(), Scheduler::run_actions(), and Scheduler::topological_sort().
 { return myaction; }
int fullfilled ()
Definition at line 367 of file Scheduler.C.
References i, n_write(), and output.
 {
   for (unsigned int i=0; i<n_write(); i++)
     if (output[i] == NULL) return 0;
   return 1;
 }
int hasInput (const char * attr, int idx)
Definition at line 374 of file Scheduler.C.
References i, and cimg_library::cimg::strcasecmp().
 {
   for (unsigned int i=0; i<n_read(); i++)
     if (strcasecmp(attr, read_attr[i]) == 0 && idx == read_idx[i]) return i;
   return -1;
 }
int hasOutput (const char * attr, int idx)
Definition at line 381 of file Scheduler.C.
References i, cimg_library::cimg::strcasecmp(), and write_attr().
Referenced by Scheduler::buildDDG().
 {
   for (unsigned int i=0; i<n_write(); i++)
     if (strcasecmp(attr, write_attr[i]) == 0 && idx == write_idx[i]) return i;
   return -1;
 }
unsigned int n_read () inline
Definition at line 69 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), Scheduler::print_helper(), and Scheduler::sanityCheck().
 { return read_attr.size(); }
unsigned int n_write () inline
Definition at line 68 of file Scheduler.h.
References write_attr().
Referenced by fullfilled(), Scheduler::print_helper(), and Scheduler::sanityCheck().
 { return write_attr.size(); }
char* name () inline
Definition at line 70 of file Scheduler.h.
Referenced by Scheduler::print_helper().
 { return myaction->name(); }
void print (FILE * f)
Definition at line 389 of file Scheduler.C.
References i, Scheduler::name(), and write_attr().
 {
   unsigned int i;
   fprintf(f, "=========== Action %s =============\n", name());
   for (i=0; i<n_read(); i++)
     printf("reads: %s %d \n", read_attr[i], read_idx[i]);
   for (i=0; i<n_write(); i++)
     printf("writes: %s %d \n", write_attr[i], write_idx[i]);
 }
Member Data Documentation
ActionList input
Definition at line 63 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), Scheduler::print_helper(), Scheduler::sanityCheck(), and Scheduler::topological_sort().
Action* myaction
Definition at line 58 of file Scheduler.h.
ActionList output
Definition at line 64 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), fullfilled(), Scheduler::print_helper(), and Scheduler::sanityCheck().
int print_flag
Definition at line 65 of file Scheduler.h.
Referenced by Scheduler::print_helper().
vector<const char *> read_attr
Definition at line 59 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), and Scheduler::print_helper().
vector<int> read_idx
Definition at line 60 of file Scheduler.h.
Referenced by Scheduler::buildDDG(), and Scheduler::print_helper().
vector<const char *> write_attr
Definition at line 61 of file Scheduler.h.
vector<int> write_idx
Definition at line 62 of file Scheduler.h.
The documentation for this struct was generated from the following files:
Scheduler.h
Scheduler.C