Rocstar: COM_exception Struct Reference
COM_exception Struct Reference
Encapsulates the states of an exception.
#include <roccom_exception.h>
Public Member Functions
msg (m)
COM_exception (const COM_exception &e)
Copy constructor.
Public Attributes
__pad0__: ierr(i)
Constructor from an error code and optionally an error message.
Error_code ierr
Error code.
std::string msg
Error message.
Detailed Description
Encapsulates the states of an exception.
Definition at line 61 of file roccom_exception.h.
Constructor & Destructor Documentation
COM_exception (const COM_exception & e) inline
Copy constructor.
Definition at line 66 of file roccom_exception.h.
     : ierr(e.ierr), msg(e.msg) {}
Member Function Documentation
msg (m) inline
Definition at line 64 of file roccom_exception.h.
Referenced by peul_readsolution(), peul_readsolutionregion(), peul_rocflo_post(), plag_readsolution(), plag_readsolutionfilepost(), plag_readstatpost(), plag_rflo_modstats::plag_rflo_readstat(), radi_rflo_readsolution(), rflo_checkbcinput(), rflo_checkmetrics(), rflo_checkminimumcells(), rflo_checkregionfaces(), rflo_findsourcepatches(), rflo_flowsolver(), rflo_getdimensdummy(), rflo_getdimensdummynodes(), rflo_getdimensphys(), rflo_getdimensphysnodes(), rflo_readgrid(), rflo_readgridregion(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffs(), rflo_modpatchaerocoeffs::rflo_readpatchaerocoeffsreg(), rflo_readrandomstate(), rflo_readregiontopology(), rflo_readsolution(), rflo_readsolutionregion(), rflo_readstat(), rflo_readstatregion(), rflo_userinput(), rflu_readstat(), rocflo_init(), rocflo_post(), rocflo_surf(), rocflo_toflu(), rocpart_post(), rocvav_post(), rvav_readfilestream2comput(), turb_rflo_readsolution(), and turb_rflo_readsolutionregion().
 : ierr(i), msg(m) {}
Member Data Documentation
__pad0__
Constructor from an error code and optionally an error message.
Definition at line 64 of file roccom_exception.h.
Error_code ierr
Error code.
Definition at line 69 of file roccom_exception.h.
Referenced by Roccom_base::delete_window(), and operator<<().
std::string msg
Error message.
Definition at line 70 of file roccom_exception.h.
Referenced by Roccom_base::allocate_array(), Window::append_array(), Roccom_base::append_array(), Roccom_base::call_function(), Roccom_base::clone_attribute(), Roccom_base::copy_array(), Window::copy_array(), Roccom_base::copy_attribute(), Roccom_base::deallocate_array(), Roccom_base::delete_attribute(), Roccom_base::delete_pane(), Roccom_base::delete_window(), Roccom_base::get_array(), Window::get_array(), Roccom_base::get_attribute(), Roccom_base::get_attribute_handle(), Roccom_base::get_attribute_handle_const(), Roccom_base::get_attributes(), Roccom_base::get_communicator(), Roccom_base::get_connectivities(), Roccom_base::get_f90pointer(), Roccom_base::get_function_handle(), Roccom_base::get_modules(), Roccom_base::get_panes(), Window::get_parent(), Roccom_base::get_parent(), Roccom_base::get_size(), Window::get_size(), Window::get_status(), Roccom_base::get_status(), Roccom_base::get_window_handle(), Roccom_base::get_windows(), Roccom_base::new_attribute(), Roccom_base::new_window(), operator<<(), Roccom_base::resize_array(), Roccom_base::set_array(), Roccom_base::set_f90pointer(), Roccom_base::set_function(), Roccom_base::set_member_function_helper(), Roccom_base::set_profiling_barrier(), Roccom_base::set_size(), Roccom_base::use_attribute(), and Roccom_base::window_init_done().
The documentation for this struct was generated from the following file:
roccom_exception.h