Rocstar: SURF_Main.F90 File Reference
SURF_Main.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
program rocflo_surf
Function/Subroutine Documentation
program rocflo_surf ()
Definition at line 47 of file SURF_Main.F90.
References Line_2< R, T >::a(), buildversionstring(), countinteractingpatches(), moderror::deregisterfunction(), moderror::errorstop(), form, idnbeg, idnend, jdnbeg, jdnend, kdnbeg, COM_exception::msg(), moderror::registerfunction(), rflo_copygeometrydummy(), rflo_copytopologylevels(), rflo_generatecoarsegrids(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), rflo_readbcinputfile(), rflo_readgridregion(), rflo_readregiontopology(), Attribute::status(), StopWatch::stop(), and writesurfacegrid().