Rocstar: Testarruda.f90 File Reference
tests/Testarruda.f90 File Reference
Functions/Subroutines
program testconst
Function/Subroutine Documentation
program testconst ()
Definition at line 53 of file tests/Testarruda.f90.
References vector3d::dir(), i, CImg< T >::matrix(), Aff_transformation_repS2< FT >::print(), and v3d10_nl_arruda_boyce().