Rocstar: TFLU_GetBndVertType.F90 File Reference
TFLU_GetBndVertType.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine getbndverttype (iReg, Regions)
Function/Subroutine Documentation
subroutine getbndverttype (integer iReg, type(t_region), dimension(:), pointer Regions)
Definition at line 51 of file TFLU_GetBndVertType.F90.
References moderror::deregisterfunction(), setup_py::grid(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), and rflo_getpatchindicesnodes().
Referenced by rocflo_toflu().