Rocstar: TFLU_Main.F90 File Reference
TFLU_Main.F90 File Reference
Functions/Subroutines
program rocflo_toflu
Function/Subroutine Documentation
program rocflo_toflu ()
Definition at line 43 of file TFLU_Main.F90.
References Line_2< R, T >::a(), buildversionstring(), convertflo2flumesh(), convertflo2flupatch(), correctnedges(), moderror::deregisterfunction(), moderror::errorstop(), getbndverttype(), setup_py::grid(), COM_exception::msg(), printtofluinput(), readinputfile(), moderror::registerfunction(), rflo_readregiontopology(), StopWatch::stop(), writeflucellmap(), writefludimens(), and writeflugrid().