Rocstar: TFLU_ConvertFlo2FluMesh.F90 File Reference
TFLU_ConvertFlo2FluMesh.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine convertflo2flumesh (iFlag, iReg, regions)
Function/Subroutine Documentation
subroutine convertflo2flumesh (integer iFlag, integer iReg, type(t_region), dimension(:), pointer regions)
Definition at line 61 of file TFLU_ConvertFlo2FluMesh.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), i, ibeg, idir, idnbeg, idnend, iend, ipnbeg, ipnend, j, jbeg, jdir, jdnbeg, jdnend, jend, jpnbeg, jpnend, k, kbeg, kdir, kdnbeg, kpnbeg, max(), min(), moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), rflo_getpatchindicesnodes(), rflo_getpatchmapping(), and rflo_readgridregion().
Referenced by rocflo_toflu().