Rocstar: thermal_soln.f90 File Reference
thermal_soln.f90 File Reference
Functions/Subroutines
subroutine thermal_soln (delt, t, rext_in, global, istep)
Function/Subroutine Documentation
subroutine thermal_soln (real(kind=wp) delt, real(kind=wp) t, real(kind=wp), dimension(1:global%numnp) rext_in, type(rocfrac_global) global, integer istep)
Definition at line 25 of file thermal_soln.f90.
References comp_row_add(), enforcethermalbc(), i, intload(), j, k, Aff_transformation_2< R_ >::m(), partition_ceff(), Aff_transformation_repS2< FT >::print(), removebcht_newtemp(), and removebcht_reff().
Referenced by rocfracmain::rocfracsoln().