Rocstar: thermal_initialize.f90 File Reference
thermal_initialize.f90 File Reference
Functions/Subroutines
subroutine thermal_initialize (global)
Function/Subroutine Documentation
subroutine thermal_initialize (type(rocfrac_global) global)
Definition at line 23 of file thermal_initialize.f90.
References glbthermcap(), glbthermstiff(), i, initcomm1(), initcomm2(), Aff_transformation_2< R_ >::m(), min(), and Aff_transformation_repS2< FT >::print().
Referenced by rocfracmain::rocfracinitialize().