Rocstar: Timing.h File Reference
Timing.h File Reference
#include <sys/time.h>
#include "rfc_basic.h"
Functions
RFC_BEGIN_NAME_SPACE double get_wtime ()
Function Documentation
RFC_BEGIN_NAME_SPACE double get_wtime () inline
Definition at line 33 of file Timing.h.
Referenced by RFC_Window_overlay::detect_features(), Transfer_base::interpolate_fe(), Transfer_base::loadtransfer(), Overlay::overlay(), Interpolator::transfer(), Transfer_base::transfer_2f(), and Transfer_base::transfer_2n().
{
   ::timeval tv;
   gettimeofday( &tv, NULL);
   return tv.tv_sec + tv.tv_usec*1.e-6;
 }