Rocstar: TractPressLoad.f90 File Reference
TractPressLoad.f90 File Reference
Functions/Subroutines
subroutine tractpressload (R_ex, numnp, InterfaceSFNumElems, InterfaceSFNumNodes, InterfaceSFElemConn, MapNodeSF, LwrBnd, UppBnd, coor, Disp, MapSFElVolEl, ElConnVol, iElType, NumElVol, TractPress)
Function/Subroutine Documentation
subroutine tractpressload (real*8, dimension(1:3*numnp) R_ex, integer numnp, integer InterfaceSFNumElems, integer InterfaceSFNumNodes, integer, dimension(1:uppbnd,1:interfacesfnumelems) InterfaceSFElemConn, integer, dimension(1:interfacesfnumnodes) MapNodeSF, integer LwrBnd, integer UppBnd, real*8, dimension(1:3,1:numnp) coor, real*8, dimension(1:3*numnp) Disp, integer, dimension(1:numelvol) MapSFElVolEl, integer, dimension(1:ieltype,1:numelvol) ElConnVol, integer iElType, integer NumElVol, real*8 TractPress)
Definition at line 53 of file TractPressLoad.f90.
References i, j, Aff_transformation_repS2< FT >::print(), sqrt(), and StopWatch::stop().
Referenced by rocfracmain::rocfracsoln().