Rocstar: TRAIL_UnixUtils.H File Reference
TRAIL_UnixUtils.H File Reference
#include <ostream>
#include <sys/types.h>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>
Classes
class Directory
Functions
std::string TRAIL_CWD (void)
void TRAIL_SafeRemove (const std::string &fname, const std::string &ext)
int TRAIL_CD (const std::string &path, std::ostream *=NULL)
bool TRAIL_FILEEXISTS (const std::string &fname)
bool TRAIL_ISDIR (const std::string &fname)
bool TRAIL_ISLINK (const std::string &fname)
int TRAIL_CreateDirectory (const std::string &fname)
std::string TRAIL_ResolveLink (const std::string &path)
std::string ResolveLink (const std::string &path)
Function Documentation
std::string ResolveLink (const std::string & path)
Definition at line 103 of file TRAIL_UnixUtils.C.
References s, and x.
Referenced by TRAIL_RemeshShuffle().
 {
   std::string retVal;
   char buf[1024];
   size_t s = readlink(path.c_str(),buf,1024);
   if(!(s <= 0)){
     buf[s] = '\0';
     retVal.assign(buf);
   }
   std::string::size_type x = retVal.find_last_of("/");
   if(x != std::string::npos)
     retVal.erase(x);
   return (retVal);
 }
int TRAIL_CD (const std::string & path, std::ostream * = NULL)
Definition at line 181 of file TRAIL_UnixUtils.C.
References TRAIL_CWD().
Referenced by TRAIL_AutoSurfer(), TRAIL_MergeRocinFiles(), TRAIL_RemeshWrite(), TRAIL_TransferSurfDataFILE(), and TRAIL_WriteWindow().
 {
   if(ouf)
     *ouf << "TRAIL_CD: Switching directory from "
          << TRAIL_CWD() << " to " << path << std::endl;
   int result = chdir(path.c_str());
   if(ouf)
     *ouf << "TRAIL_CD: CWD(" << TRAIL_CWD() << ")" << std::endl;
   return(result);
 }
int TRAIL_CreateDirectory (const std::string & fname)
Definition at line 81 of file TRAIL_UnixUtils.C.
Referenced by TRAIL_Debug(), TRAIL_RemeshAutoSurfer(), and TRAIL_RemeshWrite().
 {
   return(mkdir(fname.c_str(),S_IRGRP | S_IXGRP  | S_IRWXU));
 }
std::string TRAIL_CWD (void)
Definition at line 174 of file TRAIL_UnixUtils.C.
Referenced by TRAIL_AutoSurfer(), TRAIL_CD(), TRAIL_MergeRocinFiles(), TRAIL_RemeshAutoSurfer(), TRAIL_RemeshRunDirSetup(), TRAIL_RemeshWrite(), TRAIL_TransferSurfDataFILE(), TRAIL_WriteWindow(), and GEM_Partition::WriteRocstar().
 {
   char buf[1024];
   return(std::string(getcwd(buf,1024)));
 }
bool TRAIL_FILEEXISTS (const std::string & fname)
Definition at line 50 of file TRAIL_UnixUtils.C.
Referenced by TRAIL_RemeshWrite(), and TRAIL_SafeRemove().
 {
   struct stat fstat;
   if(lstat(fname.c_str(),&fstat))
     return false;
   return true;
 }
bool TRAIL_ISDIR (const std::string & fname)
Definition at line 59 of file TRAIL_UnixUtils.C.
Referenced by TRAIL_RemeshWrite().
 {
   struct stat fstat;
   if(stat(fname.c_str(),&fstat))
     return false;
   if(S_ISDIR(fstat.st_mode))
     return true;
   return false;
 }
bool TRAIL_ISLINK (const std::string & fname)
Definition at line 70 of file TRAIL_UnixUtils.C.
Referenced by TRAIL_RemeshWrite(), and TRAIL_SafeRemove().
 {
   struct stat fstat;
   if(lstat(fname.c_str(),&fstat))
     return false;
   if(S_ISLNK(fstat.st_mode))
     return true;
   return(false);
 }
std::string TRAIL_ResolveLink (const std::string & path)
Definition at line 87 of file TRAIL_UnixUtils.C.
References s, and x.
 {
   std::string retVal;
   char buf[1024];
   size_t s = readlink(path.c_str(),buf,1024);
   if(!(s <= 0)){
     buf[s] = '\0';
     retVal.assign(buf);
   }
   std::string::size_type x = retVal.find_last_of("/");
   if(x != std::string::npos)
     retVal.erase(x);
   return (retVal);
 }
void TRAIL_SafeRemove (const std::string & fname, const std::string & ext)
Definition at line 32 of file TRAIL_UnixUtils.C.
References n, TRAIL_FILEEXISTS(), and TRAIL_ISLINK().
Referenced by TRAIL_RemeshWrite().
 {
   if(!TRAIL_FILEEXISTS(fname))
     return;
   if(TRAIL_ISLINK(fname))
     unlink(fname.c_str());
   std::string savename_base(fname+"."+ext);
   std::string savename(savename_base);
   unsigned int n = 1;
   while(TRAIL_FILEEXISTS(savename)){
     std::ostringstream Ostr;
     Ostr << savename_base << n++;
     savename.assign(Ostr.str());
   }
   rename(fname.c_str(),savename.c_str());
 }