Rocstar: transfer_actions.C File Reference
transfer_actions.C File Reference
#include "basic_actions.h"
#include "transfer_actions.h"
#include "FluidAgent.h"
#include "SolidAgent.h"
#include "BurnAgent.h"
Functions
COM_EXTERN_MODULE (Rocsurf)
COM_EXTERN_MODULE (Rocface)
static void load_rocsurf ()
void compute_overlay (FluidAgent *fagent, SolidAgent *sagent, double t)
void _load_rocface (FluidAgent *fagent, SolidAgent *sagent, const RocmanControl_parameters *param)
Function Documentation
void _load_rocface (FluidAgent * fagent, SolidAgent * sagent, const RocmanControl_parameters * param)
Definition at line 43 of file transfer_actions.C.
References COM_call_function(), COM_get_attribute_handle_const(), COM_get_function_handle(), COM_get_window_handle(), COM_LOAD_MODULE_STATIC_DYNAMIC, COM_set_profiling_barrier(), compute_overlay(), Control_parameters::current_time, FluidAgent::fluidBufNG, Agent::get_comm_rank(), Agent::get_communicator(), Coupling::get_control_param(), Agent::get_coupling(), Agent::get_modinstance_name(), MAN_DEBUG, rank, RocmanControl_parameters::remeshed, RocmanControl_parameters::rfc_verb, and SolidAgent::solidBuf.
Referenced by SurfDiver::init(), InterMeshTransfer::load_rocface(), and FullyCoupling::reload_rocface().
 {
   int rank = fagent->get_comm_rank();
     // INIT_ROCFACE of rocman.f90
   if (COM_get_window_handle( "RFC") <=0 ) {
     if(rank == 0)
       MAN_DEBUG(3, ("Rocstar: load module RocFace.\n"));
     COM_LOAD_MODULE_STATIC_DYNAMIC( Rocface, "RFC");
     int RFC_setv = COM_get_function_handle( "RFC.set_verbose");
     COM_call_function( RFC_setv, &param->rfc_verb);
 #if 0
       // if remeshed
     MAN_DEBUG(3, ("Rocstar: remeshed: %d.\n", param->remeshed));
     if (param->remeshed) {
       double t = fagent->get_coupling()->get_control_param()->current_time;
       compute_overlay( fagent, sagent, t);
     }
 #endif
     // load overlay
     MPI_Comm comm = fagent->get_communicator();
     int RFC_read = COM_get_function_handle( "RFC.read_overlay");
     int fluid_mesh = COM_get_attribute_handle_const( fagent->fluidBufNG+".mesh");
     int solid_mesh = COM_get_attribute_handle_const( sagent->solidBuf+".mesh");
     std::string rfc_dir = "Rocman/"+fagent->get_modinstance_name()+sagent->get_modinstance_name()+"/";
     //std::string rfc_dir = "Rocman/RocfloRocsolid/";
     std::string fluid_dir = rfc_dir+"ifluid";
     std::string solid_dir = rfc_dir+"isolid";
     if(rank == 0)
       MAN_DEBUG(2, ("Rocstar: read RocFace overlay mesh from %s.\n", rfc_dir.c_str()));
     //COM_call_function( RFC_read, &fluid_mesh, &solid_mesh, &comm, fluid_dir.c_str(), solid_dir.c_str(), "HDF");
     COM_call_function( RFC_read, &fluid_mesh, &solid_mesh, &comm, fluid_dir.c_str(), solid_dir.c_str(), "CGNS");
     int RFC_transfer = COM_get_function_handle("RFC.least_squares_transfer");
     int RFC_interpolate = COM_get_function_handle("RFC.interpolate");
     COM_set_profiling_barrier( RFC_transfer, comm);
     COM_set_profiling_barrier( RFC_interpolate, comm);
   }
 }
COM_EXTERN_MODULE (Rocsurf)
COM_EXTERN_MODULE (Rocface)
void compute_overlay (FluidAgent * fagent, SolidAgent * sagent, double t)
Definition at line 192 of file Surfdiver.C.
References RocBlas::add, COM_call_function(), COM_get_attribute_handle(), COM_get_default_communicator(), COM_get_function_handle(), COM_set_default_communicator(), COM_set_profiling(), COM_window_init_done(), Agent::get_comm_rank(), Agent::get_communicator(), Agent::get_rocmod_name(), Agent::get_time_string(), MAN_DEBUG, read_file(), and SolidAgent::solidBuf.
Referenced by _load_rocface(), and SurfDiverAfterRemeshing::run().
{
   MAN_DEBUG(1, ("[%d] Rocstar: compute_overlay with t:%e .\n", fagent->get_comm_rank(), t));
   MPI_Comm comm = fagent->get_communicator();
   MPI_Barrier(comm);
     // run sequentially
   if (fagent->get_comm_rank() == 0) {
     MPI_Comm oldcomm = COM_get_default_communicator();
     COM_set_default_communicator( MPI_COMM_NULL);
       // need to turn off profiling as it may hang for npes > 1
     COM_set_profiling(0);
     //  read meshes
     std::string time_str;
     fagent->get_time_string(t, time_str);
     std::string fluid_file = fagent->get_rocmod_name()+"/Rocout/ifluid_"+time_str+".txt";
     std::string solid_file = sagent->get_rocmod_name()+"/Rocout/isolid_"+time_str+".txt";
     std::string outdir = "Rocman/"+fagent->get_rocmod_name()+sagent->get_rocmod_name()+"/";
     std::string fluid_wname = outdir+"ifluid";
     std::string solid_wname = outdir+"isolid";
       // load two meshes
     read_file( fluid_file.c_str(), fluid_wname.c_str(), 1.);
     COM_window_init_done( fluid_wname);
     read_file( solid_file.c_str(), solid_wname.c_str(), 1.);
     COM_window_init_done( solid_wname);
     int fluid_mesh1 = COM_get_attribute_handle( (fluid_wname+".mesh").c_str());
     int solid_mesh1 = COM_get_attribute_handle( (solid_wname+".mesh").c_str());
     const char *format = "HDF";
     // call Rocblas to get deformed data HERE
     int s_x_hdl = COM_get_attribute_handle( sagent->solidBuf + ".x");
     int s_uhat_hdl = COM_get_attribute_handle( sagent->solidBuf + ".uhat");
     int s_y_hdl = COM_get_attribute_handle( sagent->solidBuf + ".nc");
       // get deformed
     COM_call_function( RocBlas::add, &s_x_hdl, &s_uhat_hdl, &s_y_hdl);
     int RFC_overlay = COM_get_function_handle( "RFC.overlay");
     int RFC_write = COM_get_function_handle( "RFC.write_overlay");
     // mesh overlay
     MAN_DEBUG(2,("Starting mesh overlay... "));
     COM_call_function( RFC_overlay, &fluid_mesh1, &solid_mesh1);
     // output overlay mesh
     COM_call_function( RFC_write, &fluid_mesh1, &solid_mesh1,
                      fluid_wname.c_str(), solid_wname.c_str(), format);
     COM_set_default_communicator( oldcomm);
     COM_set_profiling(1);
   }   // end of PE 0
   MPI_Barrier(comm);
 }
static void load_rocsurf () inline static
Definition at line 34 of file transfer_actions.C.
References COM_get_window_handle(), and COM_LOAD_MODULE_STATIC_DYNAMIC.
Referenced by LoadTransfer_FS::init(), LoadTransfer_FSc_ALE::init(), LoadTransferOnly_FSc_ALE::init(), and GetDeformedMesh_ALE::init().
 {
   if (COM_get_window_handle("SURF") <= 0) {
     COM_LOAD_MODULE_STATIC_DYNAMIC( Rocsurf, "SURF");
   }
 }