Rocstar: TURB_floLesUniFiltCCJ.F90 File Reference
TURB_floLesUniFiltCCJ.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_flolesunifiltccj (global, nDum, ibeg, iend, jbeg, jend, kbeg, kend, iCOff, ijCOff, nDel, idBeg, idEnd, fact1, fact2, fVar, filtVar)
Function/Subroutine Documentation
subroutine turb_flolesunifiltccj (type(t_global), pointer global, integer nDum, integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer iCOff, integer ijCOff, integer, dimension(diri:dirk) nDel, integer idBeg, integer idEnd, real(rfreal), dimension(filwidth_four) fact1, real(rfreal), dimension(filwidth_four) fact2, real(rfreal), dimension(:,:), pointer fVar, real(rfreal), dimension(:,:), pointer filtVar)
Definition at line 52 of file TURB_floLesUniFiltCCJ.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and moderror::registerfunction().
Referenced by turb_flolesgenfiltcc(), and turb_flolesunifiltcc().