Rocstar: TURB_floWlmMetric.F90 File Reference
TURB_floWlmMetric.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_flowlmmetric (region, patch)
Function/Subroutine Documentation
subroutine turb_flowlmmetric (type(t_region) region, type(t_patch) patch)
Definition at line 48 of file TURB_floWlmMetric.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), Element_node_vectors_k_const< Value >::set(), and sqrt().
Referenced by turb_coviscousfluxes(), turb_initsolution(), and turb_lesmovegrid().