Rocstar: TURB_rFLO_RansBndConditionsSend.F90 File Reference
TURB_rFLO_RansBndConditionsSend.F90 File Reference
Functions/Subroutines
subroutine turb_rflo_ransbndconditionssend (regions, iReg)
Function/Subroutine Documentation
subroutine turb_rflo_ransbndconditionssend (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 45 of file TURB_rFLO_RansBndConditionsSend.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), turb_floranssendcornedgecells(), and turb_floranssenddummyconf().
Referenced by explicitmultistage(), and initcommunicationmp().