Rocstar: TURB_StatCCollector.F90 File Reference
TURB_StatCCollector.F90 File Reference
Functions/Subroutines
subroutine turb_statccollector (region, iBegSt, iEndSt, colVar)
Function/Subroutine Documentation
subroutine turb_statccollector (type(t_region) region, integer iBegSt, integer iEndSt, real(rfreal), dimension(:,:), pointer colVar)
Definition at line 48 of file TURB_StatCCollector.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, idcbeg, idcend, j, jdcbeg, jdcend, k, kdcbeg, Aff_transformation_2< R_ >::m(), moderror::registerfunction(), rflo_getcelloffset(), and rflo_getdimensdummy().
Referenced by turb_lesesgmodel4(), turb_vfluxhybrid(), and turb_visfluxeddy().