Rocstar: TURB_VisFluxEddy.F90 File Reference
TURB_VisFluxEddy.F90 File Reference
Functions/Subroutines
subroutine turb_visfluxeddy (region)
subroutine computefluxtot (ijk)
Function/Subroutine Documentation
subroutine turb_visfluxeddy::computefluxtot (integer ijk)
Definition at line 235 of file TURB_VisFluxEddy.F90.
References dot_product(), moderror::errorstop(), i, ibeg, ic, iend, ipcbeg, ipcend, j, jbeg, jend, jpcbeg, jpcend, k, kbeg, kpcbeg, sqrt(), and CImg< T >::trace().
subroutine turb_visfluxeddy (type(t_region), target region)
Definition at line 49 of file TURB_VisFluxEddy.F90.
References computefluxtot(), moderror::deregisterfunction(), ipcbeg, ipcend, jpcbeg, jpcend, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getnodeoffset(), CImg< T >::trace(), turb_lesesgmodel4(), turb_statccollector(), turb_visfluxeddypatch(), turb_wlmfluxpatch(), turb_wlmtauwallmapping(), and turb_wlmupdate().
Referenced by turb_coviscousfluxes(), and turb_lesfluxfixsmag().