Rocstar: TURB_LesLij.F90 File Reference
TURB_LesLij.F90 File Reference
Functions/Subroutines
subroutine turb_leslij (region, ijk, nDel, lij)
Function/Subroutine Documentation
subroutine turb_leslij (region, integer ijk, integer, dimension(diri:dirk) nDel, real(rfreal), dimension(:,:), pointer lij)
Definition at line 57 of file TURB_LesLij.F90.
References moderror::deregisterfunction(), idnbeg, idnend, jdnbeg, jdnend, kdnbeg, moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), rflu_modinterpolation::rflu_interpcells2faces(), turb_flolesgenfiltff(), and turb_flolesunifiltff().
Referenced by turb_lescoefdynmixd(), turb_lescoefdynsmag(), turb_lesfluxscalsim(), and turb_leshij().