Rocstar: TURB_floRansSetCornEdgeCells.F90 File Reference
TURB_floRansSetCornEdgeCells.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_floranssetcornedgecells (region)
subroutine averageedgecells (ijkD, ijkC1, ijkC2, nCv, tcv)
Function/Subroutine Documentation
subroutine turb_floranssetcornedgecells::averageedgecells (integer ijkD, integer ijkC1, integer ijkC2, integer nCv, real(rfreal), dimension(:,:), pointer tcv)
Definition at line 201 of file TURB_floRansSetCornEdgeCells.F90.
subroutine turb_floranssetcornedgecells (type(t_region) region)
Definition at line 46 of file TURB_floRansSetCornEdgeCells.F90.
References averageedgecells(), moderror::deregisterfunction(), i, idcbeg, idcend, ipcbeg, ipcend, j, jdcbeg, jdcend, jpcbeg, jpcend, k, kdcbeg, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensdummy(), and rflo_getdimensphys().
Referenced by turb_rflo_ransbndconditionsrecv().