Rocstar: TURB_floWlmUpdateLoglay.F90 File Reference
TURB_floWlmUpdateLoglay.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_flowlmupdateloglay (region, patch)
Function/Subroutine Documentation
subroutine turb_flowlmupdateloglay (type(t_region) region, type(t_patch) patch)
Definition at line 54 of file TURB_floWlmUpdateLoglay.F90.
References moderror::deregisterfunction(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, FloGridBlock::ksize(), min(), Rocblas::mul(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by turb_wlmupdate().