Rocstar: TURB_floLesGenCoCCUtil.F90 File Reference
TURB_floLesGenCoCCUtil.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_flolesgencocclo (global, ijk, ibeg, iend, jbeg, jend, kbeg, kend, minIdx, maxIdx, segId, iCOff, ijCOff, iNOff, ijNOff, ds, segm, ccCofA, ccCofB)
subroutine turb_flolesgencocchi (global, ijk, ibeg, iend, jbeg, jend, kbeg, kend, minIdx, maxIdx, segId, iCOff, ijCOff, iNOff, ijNOff, ds, segm, ccCofA, ccCofB)
Function/Subroutine Documentation
subroutine turb_flolesgencocchi (type(t_global), pointer global, integer ijk, integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer minIdx, integer maxIdx, integer segId, integer iCOff, integer ijCOff, integer iNOff, integer ijNOff, real(rfreal), dimension(minidx:maxidx) ds, real(rfreal), dimension(:,:), pointer segm, real(rfreal), dimension(:,:), pointer ccCofA, real(rfreal), dimension(:,:), pointer ccCofB)
Definition at line 196 of file TURB_floLesGenCoCCUtil.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and moderror::registerfunction().
Referenced by turb_flolesgencocc().
subroutine turb_flolesgencocclo (type(t_global), pointer global, integer ijk, integer ibeg, integer iend, integer jbeg, integer jend, integer kbeg, integer kend, integer minIdx, integer maxIdx, integer segId, integer iCOff, integer ijCOff, integer iNOff, integer ijNOff, real(rfreal), dimension(minidx:maxidx) ds, real(rfreal), dimension(:,:), pointer segm, real(rfreal), dimension(:,:), pointer ccCofA, real(rfreal), dimension(:,:), pointer ccCofB)
Definition at line 53 of file TURB_floLesGenCoCCUtil.F90.
References moderror::deregisterfunction(), i, ibeg, iend, j, jbeg, jend, k, kbeg, and moderror::registerfunction().
Referenced by turb_flolesgencocc().