Rocstar: TURB_RansEmsInit.F90 File Reference
TURB_RansEmsInit.F90 File Reference
Functions/Subroutines
subroutine turb_ransemsinit (region, istage)
Function/Subroutine Documentation
subroutine turb_ransemsinit (type(t_region) region, integer, intent(in) istage)
Definition at line 46 of file TURB_RansEmsInit.F90.
References moderror::deregisterfunction(), ic, idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_getcelloffset(), and rflo_getdimensdummy().
Referenced by turb_emsinit().