Rocstar: TURB_LesCalcEddyVis.F90 File Reference
TURB_LesCalcEddyVis.F90 File Reference
Functions/Subroutines
subroutine turb_lescalceddyvis (region, ibn, ien, ijk)
Function/Subroutine Documentation
subroutine turb_lescalceddyvis (region, integer ibn, integer ien, integer ijk)
Definition at line 47 of file TURB_LesCalcEddyVis.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, iend, ipcbeg, ipcend, j, jbeg, jend, jpcbeg, jpcend, k, kbeg, kpcbeg, max(), Mesh::GenericElement::nfaces(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getnodeoffset(), sqrt(), turb_flolesgenc2f(), turb_flulesc2f(), turb_lescoefdynmixd(), and turb_lescoefdynsmag().
Referenced by turb_lesfluxfixsmag(), and turb_lesgeteddyvis().