Rocstar: TURB_floLesAverageFace.F90 File Reference
TURB_floLesAverageFace.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_flolesaverageface (region, ijk, faceVar, avgFaceVar)
subroutine trapezoid1loop (ib, ie, lineVar, pointVar)
subroutine ensemble1loop (ib, ie, lineVar, pointVar)
subroutine trapezoid2loops (ib, ie, jb, je, nOff, surfVar, lineVar)
subroutine ensemble2loops (ib, ie, jb, je, nOff, surfVar, lineVar)
subroutine trapezoid3lijk (ib, ie, jb, je, kb, ke, volVar, surfVar)
subroutine trapezoid3likj (ib, ie, kb, ke, jb, je, volVar, surfVar)
subroutine trapezoid3ljik (jb, je, ib, ie, kb, ke, volVar, surfVar)
subroutine trapezoid3ljki (jb, je, kb, ke, ib, ie, volVar, surfVar)
subroutine trapezoid3lkij (kb, ke, ib, ie, jb, je, volVar, surfVar)
subroutine trapezoid3lkji (kb, ke, jb, je, ib, ie, volVar, surfVar)
subroutine ensemble3lijk (ib, ie, jb, je, kb, ke, volVar, surfVar)
subroutine ensemble3likj (ib, ie, kb, ke, jb, je, volVar, surfVar)
subroutine ensemble3ljik (jb, je, ib, ie, kb, ke, volVar, surfVar)
subroutine ensemble3ljki (jb, je, kb, ke, ib, ie, volVar, surfVar)
subroutine ensemble3lkij (kb, ke, ib, ie, jb, je, volVar, surfVar)
subroutine ensemble3lkji (kb, ke, jb, je, ib, ie, volVar, surfVar)
Function/Subroutine Documentation
subroutine turb_flolesaverageface::ensemble1loop (integer ib, integer ie, real(rfreal), dimension(:), pointer lineVar, real(rfreal) pointVar)
Definition at line 498 of file TURB_floLesAverageFace.F90.
References i, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::ensemble2loops (integer ib, integer ie, integer jb, integer je, integer nOff, real(rfreal), dimension(:), pointer surfVar, real(rfreal), dimension(:), pointer lineVar)
Definition at line 553 of file TURB_floLesAverageFace.F90.
References i, j, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::ensemble3lijk (integer ib, integer ie, integer jb, integer je, integer kb, integer ke, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 768 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::ensemble3likj (integer ib, integer ie, integer kb, integer ke, integer jb, integer je, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 796 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::ensemble3ljik (integer jb, integer je, integer ib, integer ie, integer kb, integer ke, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 824 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::ensemble3ljki (integer jb, integer je, integer kb, integer ke, integer ib, integer ie, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 852 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::ensemble3lkij (integer kb, integer ke, integer ib, integer ie, integer jb, integer je, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 880 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::ensemble3lkji (integer kb, integer ke, integer jb, integer je, integer ib, integer ie, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 908 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
subroutine turb_flolesaverageface::trapezoid1loop (integer ib, integer ie, real(rfreal), dimension(:), pointer lineVar, real(rfreal) pointVar)
Definition at line 472 of file TURB_floLesAverageFace.F90.
References i, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::trapezoid2loops (integer ib, integer ie, integer jb, integer je, integer nOff, real(rfreal), dimension(:), pointer surfVar, real(rfreal), dimension(:), pointer lineVar)
Definition at line 523 of file TURB_floLesAverageFace.F90.
References i, j, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::trapezoid3lijk (integer ib, integer ie, integer jb, integer je, integer kb, integer ke, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 580 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::trapezoid3likj (integer ib, integer ie, integer kb, integer ke, integer jb, integer je, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 611 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::trapezoid3ljik (integer jb, integer je, integer ib, integer ie, integer kb, integer ke, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 642 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::trapezoid3ljki (integer jb, integer je, integer kb, integer ke, integer ib, integer ie, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 673 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::trapezoid3lkij (integer kb, integer ke, integer ib, integer ie, integer jb, integer je, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 704 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
Referenced by turb_flolesaverageface().
subroutine turb_flolesaverageface::trapezoid3lkji (integer kb, integer ke, integer jb, integer je, integer ib, integer ie, real(rfreal), dimension(:), pointer volVar, real(rfreal), dimension(:), pointer surfVar)
Definition at line 735 of file TURB_floLesAverageFace.F90.
References i, j, k, and CImg< T >::sum().
subroutine turb_flolesaverageface (type(t_region) region, integer ijk, real(rfreal), dimension(:), pointer faceVar, real(rfreal), dimension(:), pointer avgFaceVar)
Definition at line 72 of file TURB_floLesAverageFace.F90.
References moderror::deregisterfunction(), ensemble1loop(), ensemble2loops(), ensemble3lijk(), ensemble3likj(), ensemble3ljik(), ensemble3ljki(), ensemble3lkij(), moderror::errorstop(), i, ibeg, idnbeg, idnend, iend, ipnbeg, ipnend, j, jbeg, jdnbeg, jdnend, jend, jpnbeg, jpnend, k, kbeg, kdnbeg, kpnbeg, max(), min(), moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getdimensphysnodes(), rflo_getnodeoffset(), trapezoid1loop(), trapezoid2loops(), trapezoid3lijk(), trapezoid3likj(), trapezoid3ljik(), trapezoid3ljki(), trapezoid3lkij(), turb_flolesgenfiltff(), and turb_flolesunifiltff().
Referenced by turb_lescontract().