Rocstar: TURB_floRansExchCornEdgeCells.F90 File Reference
TURB_floRansExchCornEdgeCells.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_floransexchcornedgecells (regions, iReg)
Function/Subroutine Documentation
subroutine turb_floransexchcornedgecells (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 45 of file TURB_floRansExchCornEdgeCells.F90.
References moderror::deregisterfunction(), i, ibeg, icell, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getcornercellsindices(), and rflo_getedgecellsindices().
Referenced by turb_rflo_ransbndconditionsrecv().