Rocstar: TURB_VisFluxEddyPatch.F90 File Reference
TURB_VisFluxEddyPatch.F90 File Reference
Functions/Subroutines
subroutine turb_visfluxeddypatch (region, patch)
Function/Subroutine Documentation
subroutine turb_visfluxeddypatch (type(t_region), target region, type(t_patch) patch)
Definition at line 49 of file TURB_VisFluxEddyPatch.F90.
References moderror::deregisterfunction(), dot_product(), moderror::errorstop(), i, ibeg, ic, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), sqrt(), and CImg< T >::trace().
Referenced by turb_visfluxeddy().