Rocstar: TURB_WlmReyAnalogy.F90 File Reference
TURB_WlmReyAnalogy.F90 File Reference
Functions/Subroutines
subroutine turb_wlmreyanalogy (region, patch)
Function/Subroutine Documentation
subroutine turb_wlmreyanalogy (type(t_region) region, type(t_patch) patch)
Definition at line 52 of file TURB_WlmReyAnalogy.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, j, jbeg, jdir, jend, k, kbeg, kdir, min(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by turb_wlmupdate().