Rocstar: TURB_coRansWallDistOVFlo.F90 File Reference
TURB_coRansWallDistOVFlo.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_coranswalldistov (regions)
Function/Subroutine Documentation
subroutine turb_coranswalldistov (type(t_region), dimension(:), pointer regions)
Definition at line 50 of file TURB_coRansWallDistOVFlo.F90.
References moderror::deregisterfunction(), CImg< T >::distance(), moderror::errorstop(), i, ic, ipcbeg, ipcend, j, jpcbeg, jpcend, k, kpcbeg, max(), min(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getnodeoffset(), sqrt(), Attribute::status(), turb_floextrapintcellscal(), and turb_ranswalldistovpatch().
Referenced by turb_calcmetrics().