Rocstar: TURB_floFaceWidth.F90 File Reference
TURB_floFaceWidth.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_flofacewidth (region)
subroutine computefacewidth (ijk)
Function/Subroutine Documentation
subroutine turb_flofacewidth::computefacewidth (integer ijk)
Definition at line 123 of file TURB_floFaceWidth.F90.
References i, ibeg, idcbeg, idcend, iend, j, jbeg, jdcbeg, jdcend, jend, k, kbeg, kdcbeg, and sqrt().
Referenced by turb_flofacewidth().
subroutine turb_flofacewidth (type(t_region) region)
Definition at line 44 of file TURB_floFaceWidth.F90.
References computefacewidth(), moderror::deregisterfunction(), idcbeg, idcend, jdcbeg, jdcend, kdcbeg, moderror::registerfunction(), rflo_copyedgefacenorm(), rflo_copyedgefaceparal(), rflo_getdimensdummy(), rflo_getnodeoffset(), and turb_flofacewidthdummy().
Referenced by turb_coviscousfluxes(), turb_initsolution(), and turb_lesmovegrid().