Rocstar: TURB_InitInputValues.F90 File Reference
TURB_InitInputValues.F90 File Reference
Functions/Subroutines
subroutine turb_initinputvalues (regions)
Function/Subroutine Documentation
subroutine turb_initinputvalues (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file TURB_InitInputValues.F90.
References moderror::deregisterfunction(), moderror::errorstop(), rflu_modrepair3d::input(), moderror::registerfunction(), rflu_creategrid(), rflu_modreadbcinputfile::rflu_readbcinputfilewrapper(), and rflu_moddimensions::rflu_readdimensions().
Referenced by turb_userinput().