Rocstar: TURB_WlmInitia.F90 File Reference
TURB_WlmInitia.F90 File Reference
Functions/Subroutines
subroutine turb_wlminitia (region, patch)
Function/Subroutine Documentation
subroutine turb_wlminitia (type(t_region) region, type(t_patch) patch)
Definition at line 44 of file TURB_WlmInitia.F90.
References moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, iend, j, jbeg, jend, k, kbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getpatchindices(), sqrt(), and v.
Referenced by turb_initsolution().