Rocstar: TURB_ReadInputFile.F90 File Reference
TURB_ReadInputFile.F90 File Reference
Functions/Subroutines
subroutine turb_readinputfile (regions)
Function/Subroutine Documentation
subroutine turb_readinputfile (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file TURB_ReadInputFile.F90.
References moderror::deregisterfunction(), Container_from_circulator< C >::end(), moderror::errorstop(), form, CImg< T >::line(), moderror::registerfunction(), Attribute::status(), and turb_readturbsection().
Referenced by peul_rocflo_post(), rocflo_post(), and turb_userinput().