Rocstar: TURB_UserInput.F90 File Reference
TURB_UserInput.F90 File Reference
Functions/Subroutines
subroutine turb_userinput (regions)
Function/Subroutine Documentation
subroutine turb_userinput (type (t_region), dimension(:), pointer regions)
Definition at line 46 of file TURB_UserInput.F90.
References moderror::deregisterfunction(), moderror::registerfunction(), turb_checkparaminput(), turb_derivedinputvalues(), turb_initinputvalues(), turb_readbcinputfile(), and turb_readinputfile().
Referenced by rflo_getuserinput(), and rflu_getuserinput().