Rocstar: TURB_rFLO_RansBndConditionsSet.F90 File Reference
TURB_rFLO_RansBndConditionsSet.F90 File Reference
Functions/Subroutines
subroutine turb_rflo_ransbndconditionsset (regions, iReg)
Function/Subroutine Documentation
subroutine turb_rflo_ransbndconditionsset (type(t_region), dimension(:), pointer regions, integer iReg)
Definition at line 46 of file TURB_rFLO_RansBndConditionsSet.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), turb_floransbcondinflow(), turb_floransbcondinjection(), turb_floransbcondnoslipwall(), turb_floransbcondsymmetry(), turb_floransbcondzerograd(), and turb_floransexchangedummyconf().
Referenced by explicitmultistage(), and updateboundaryconditionsmp().