Rocstar: TURB_floRansSARoeFluxPatch.F90 File Reference
TURB_floRansSARoeFluxPatch.F90 File Reference
#include "Indexing.h"
Functions/Subroutines
subroutine turb_floranssaroefluxpatch (region, patch)
Function/Subroutine Documentation
subroutine turb_floranssaroefluxpatch (type(t_region) region, type(t_patch) patch)
Definition at line 45 of file TURB_floRansSARoeFluxPatch.F90.
References bcondinjectionperf(), moderror::deregisterfunction(), moderror::errorstop(), i, ibeg, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and sqrt().
Referenced by turb_floranssaroe1stflux(), and turb_floranssaroe2ndflux().