Rocstar: TURB_rFLU_ReadSolutionASCII.F90 File Reference
TURB_rFLU_ReadSolutionASCII.F90 File Reference
Functions/Subroutines
subroutine turb_rflu_readsolutionascii (region)
Function/Subroutine Documentation
subroutine turb_rflu_readsolutionascii (type(t_region), pointer region)
Definition at line 43 of file TURB_rFLU_ReadSolutionASCII.F90.
References buildfilenamesteady(), buildfilenameunsteady(), moderror::deregisterfunction(), moderror::errorstop(), form, setup_py::grid(), j, moderror::registerfunction(), and Attribute::status().
Referenced by rflu_modreadwriteflow::rflu_readflowwrapper().