Rocstar: TURB_VFluxHybridPatch.F90 File Reference
TURB_VFluxHybridPatch.F90 File Reference
Functions/Subroutines
subroutine turb_vfluxhybridpatch (region, patch)
Function/Subroutine Documentation
subroutine turb_vfluxhybridpatch (type(t_region), target region, type(t_patch) patch)
Definition at line 47 of file TURB_VFluxHybridPatch.F90.
References moderror::deregisterfunction(), dot_product(), moderror::errorstop(), i, ibeg, ic, idir, iend, inode, j, jbeg, jdir, jend, jnode, k, kbeg, kdir, max(), moderror::registerfunction(), rflo_getcelloffset(), rflo_getnodeoffset(), rflo_getpatchdirection(), rflo_getpatchindices(), and CImg< T >::trace().
Referenced by turb_vfluxhybrid().