Rocstar: TURB_InitSolution.F90 File Reference
TURB_InitSolution.F90 File Reference
Functions/Subroutines
subroutine turb_initsolution (region)
Function/Subroutine Documentation
subroutine turb_initsolution (region)
Definition at line 50 of file TURB_InitSolution.F90.
References moderror::deregisterfunction(), moderror::errorstop(), setup_py::grid(), ic, idnbeg, idnend, jdnbeg, jdnend, kdnbeg, mixtureproperties(), moderror::registerfunction(), rflo_getdimensdummynodes(), rflo_getnodeoffset(), turb_flofacevolume(), turb_flofacewidth(), turb_flolesgencocc(), turb_flolesgencoff(), turb_flowlmmetric(), turb_flufacevolume(), turb_ranssageteddyvis(), and turb_wlminitia().
Referenced by rflo_getflowsolution(), and rflu_modreadwriteflow::rflu_readflowwrapper().