Rocstar: TURB_LesGetEddyVis.F90 File Reference
TURB_LesGetEddyVis.F90 File Reference
Functions/Subroutines
subroutine turb_lesgeteddyvis (region, ibc, iec, ibn, ien)
Function/Subroutine Documentation
subroutine turb_lesgeteddyvis (region, integer ibc, integer iec, integer ibn, integer ien)
Definition at line 49 of file TURB_LesGetEddyVis.F90.
References moderror::deregisterfunction(), moderror::errorstop(), gradi(), gradj(), moderror::registerfunction(), rflo_calcgradvector(), rflu_moddifferentiationbfaces::rflu_computegradbfaceswrapper(), rflu_moddifferentiationfaces::rflu_computegradfaceswrapper(), rflu_decideneedbgradface(), turb_lescalceddyvis(), and turb_lestestrhov().
Referenced by turb_coviscousfluxes().