Rocstar: TURB_VFluxHybrid.F90 File Reference
TURB_VFluxHybrid.F90 File Reference
Functions/Subroutines
subroutine turb_vfluxhybrid (region)
subroutine computefluxtot (ijk)
Function/Subroutine Documentation
subroutine turb_vfluxhybrid::computefluxtot (integer ijk)
Definition at line 233 of file TURB_VFluxHybrid.F90.
References dot_product(), moderror::errorstop(), i, ibeg, ic, iend, ipcbeg, ipcend, j, jbeg, jend, jpcbeg, jpcend, k, kbeg, kpcbeg, max(), and CImg< T >::trace().
Referenced by turb_vfluxhybrid(), and turb_visfluxeddy().
subroutine turb_vfluxhybrid (type(t_region), target region)
Definition at line 47 of file TURB_VFluxHybrid.F90.
References computefluxtot(), moderror::deregisterfunction(), ipcbeg, ipcend, jpcbeg, jpcend, kpcbeg, moderror::registerfunction(), rflo_getcelloffset(), rflo_getdimensphys(), rflo_getnodeoffset(), CImg< T >::trace(), turb_lesesgmodel4(), turb_statccollector(), turb_vfluxhybridpatch(), turb_wlmfluxpatch(), turb_wlmtauwallmapping(), and turb_wlmupdate().
Referenced by turb_coviscousfluxes(), and turb_lesfluxscalsim().