Rocstar: TURB_coWlmReadBcSectionFlu.F90 File Reference
TURB_coWlmReadBcSectionFlu.F90 File Reference
Functions/Subroutines
subroutine turb_cowlmreadbcsection (regions)
Function/Subroutine Documentation
subroutine turb_cowlmreadbcsection (type(t_region), dimension(:), pointer regions)
Definition at line 43 of file TURB_coWlmReadBcSectionFlu.F90.
References brbeg, moderror::deregisterfunction(), moderror::errorstop(), max(), min(), prbeg, prend, prep_modbcdistribution::readpatchsection(), and moderror::registerfunction().