Rocstar: main.C File Reference
utilities/rocflu/part/main.C File Reference
#include <iostream>
#include <vector>
#include <list>
#include <sstream>
#include "clop.H"
#include "FC.h"
Functions
void FC_GLOBAL (rflupart, RFLUPART) const
int main (int argc, char *argv[])
Function Documentation
void FC_GLOBAL (rflupart , RFLUPART) const
Definition at line 64 of file utilities/rocflu/part/main.C.
 {
   cout << endl << "Usage: " << pn << " -c <casename> [-v 0-2]" << endl << endl
        << "   -c | --casename  :  Specifies the casename" << endl
        << "   -v | --verbosity :  Verbosity level:" << endl
        << "                       0 - Quiet" << endl
        << "                       1 - Moderately verbose" << endl
        << "                       2 - Ridiculously verbose" << endl
        << "                       3 - Exteremly verbose" << endl
        << endl;
 }
int main (int argc, char * argv[])
Definition at line 81 of file utilities/rocflu/part/main.C.
References AddOp(), FC_GLOBAL, GetOp(), rflupart(), RFLUPART, stripdir(), Usage(), and Vectize().
 {
   // Get the commandline into a string vector - it's easier
   // to deal with that way.
   vector<string> args = Vectize((const char **)argv,argc);
   // Get the name of the executable by stripping off any leading
   // directory names
   string program_name(stripdir(args[0]));
   // Specify the allowable options to the program
   AddOp("casename",'c');
   AddOp("verbosity",'v');
   AddOp("help",'h');
   // Declare some variables for command line argument handling
   string casename;
   string sverb;
   int verbosity;
   bool help;
   bool isset;
   // See if the help option is specified, if so give'm the usage text
   if(help = GetOp("help",args)){
     Usage(program_name);
     exit(0);
   }
   // Process casename option, if it's not set then fail
   if(GetOp("casename",casename,args)){
     if(casename.empty()){ // casename was empty
       cerr << program_name
            << ": Expected casename after casename option."
            << " Use -h for usage instructions."
            << endl;
       exit(1);
     }
   }
   else{ // option not specified (but it's required!)
     cerr << program_name
          << ": Missing required casename option."
          << "  Use -h for usage instructions."
          << endl;
     exit(1);
   }
   // Process verbosity option
   if(GetOp("verbosity",sverb,args)){
     if(sverb.empty()){
       cerr << program_name
            << ": Expected verbosity level. "
            << "Use -h for usage instructions." << endl;
       exit(1);
     }
     istringstream Istr(sverb);
     Istr >> verbosity;
     if(verbosity < 0 || verbosity > 4){ // Some jerk specified a non numeric or negative
       cerr << program_name
            << ": Invalid verbosity value.  Use -h for usage "
            << "instructions." << endl;
       exit(1);
     }
   }
   else{ // Default verbosity
     verbosity = 1;
   }
   FC_GLOBAL(rflupart,RFLUPART)(casename.c_str(),&verbosity,casename.length());
 }