Rocstar: RocfracPrep.f90 File Reference
utilities/RocfracPrep/RocfracPrep.f90 File Reference
Data Types
type nodebc
type nodebc_lst
type sndrcv_buf
type proclist
type proclistrco
Functions/Subroutines
program rocfracprep
Function/Subroutine Documentation
program rocfracprep ()
Definition at line 53 of file utilities/RocfracPrep/RocfracPrep.f90.
References form, i, j, k, generic_list::li_init_list(), mesh2d(), mesh2doverlay(), n, nk, Aff_transformation_repS2< FT >::print(), linked_list::print_comm_list(), linked_list::print_vol_list(), read_patran(), readinp(), Rocout::set_option(), Attribute::status(), StopWatch::stop(), CImg< T >::sum(), linked_list::vol_insert_head(), linked_list::vol_insert_tail(), and write_attr().