Rocstar: RFLU_AllocateMemoryWrapper.F90 File Reference
utilities/rocflu/cells/RFLU_AllocateMemoryWrapper.F90 File Reference
Functions/Subroutines
subroutine rflu_allocatememorywrapper (pRegion, allocMode)
Function/Subroutine Documentation
subroutine rflu_allocatememorywrapper (type(t_region), pointer pRegion, integer, intent(in) allocMode)
Definition at line 46 of file utilities/rocflu/cells/RFLU_AllocateMemoryWrapper.F90.
References moderror::deregisterfunction(), moderror::errorstop(), moderror::registerfunction(), rflu_allocatememory(), rflu_modcellmapping::rflu_createcellmapping(), rflu_modfacelist::rflu_createfacelist(), and rflu_creategrid().