Rocstar: RFLU_WriteVersionString.F90 File Reference
utilities/rocflu/cells/RFLU_WriteVersionString.F90 File Reference
Functions/Subroutines
subroutine rflu_writeversionstring (global)
Function/Subroutine Documentation
subroutine rflu_writeversionstring (type(t_global), pointer global)
Definition at line 44 of file utilities/rocflu/cells/RFLU_WriteVersionString.F90.
References buildversionstring(), moderror::deregisterfunction(), moderror::errorstop(), form, moderror::registerfunction(), and Attribute::status().