Rocstar: NewCommList.f90 File Reference
utilities/RocfracPrep/NewCommList.f90 File Reference
Functions/Subroutines
subroutine newcommlist (NumEl, NumNP, NumProcs, NumVertex, NodeConn, ElPart, NumProcPerNd, ProcNdList, MaxNumberOfProcsToShareNode, NumElPerProc, NumNdPerProc)
Function/Subroutine Documentation
subroutine newcommlist (integer NumEl, integer NumNP, integer NumProcs, integer NumVertex, integer, dimension(1:numvertex,1:numel) NodeConn, integer, dimension(1:numel) ElPart, integer, dimension(1:numnp) NumProcPerNd, integer, dimension(1:numnp,1:maxnumberofprocstosharenode) ProcNdList, integer MaxNumberOfProcsToShareNode, integer, dimension(1:numprocs) NumElPerProc, integer, dimension(1:numprocs) NumNdPerProc)
Definition at line 53 of file utilities/RocfracPrep/NewCommList.f90.
References linked_list2::add_procelemlist(), linked_list::addcommnd(), i, j, k, Aff_transformation_2< R_ >::m(), Aff_transformation_repS2< FT >::print(), Aff_transformationS2< FT >::ptr(), and StopWatch::stop().