Rocstar: util.cpp File Reference
utilities/rc_cmp/util.cpp File Reference
#include "util.h"
Functions
string itoa (int n)
Convert an int to a string.
bool check_non_numeric_char (char test_char)
bool check_non_numeric_char_per (char test_char)
bool check_non_numeric_str (string test_str)
bool check_non_numeric_str_per (string test_str)
bool check_delimiters (char *delimit, int num, char test)
std::vector< string > readQuoteExpression (string rStack, string rNeedle)
Read expressions of the form x = "test" "100" "another test".
std::vector< string > readCommaExpression (string rStack, string rNeedle)
bool check_bool_arr (bool test[], int size)
long double dist (long double *coord1, long double *coord2, int size)
bool pnt_in_tri (pnt test, pnt p1, pnt p2, pnt p3)
bool side_check (pnt test, pnt p1, pnt p2, pnt check)
pnt cross_product (pnt vec1, pnt vec2)
long double dot_product (pnt vec1, pnt vec2)
long double nan ()
std::vector< string > str_tokenize (string full, string delimiters)
bool same_elements (std::vector< int > vector_1, std::vector< int > vector_2)
Function Documentation
bool check_bool_arr (bool test[], int size)
Definition at line 294 of file utilities/rc_cmp/util.cpp.
References i.
Referenced by Fileselect::testTecplot().
{
     for(int i=0; i<size; i++){
         if(!test[i])
             return false;
     }
     return true;
 }
bool check_delimiters (char * delimit, int num, char test)
Definition at line 51 of file utilities/rc_cmp/util.cpp.
References i.
Referenced by readCommaExpression(), and readQuoteExpression().
{
     //Default delimiters if none are specified
     if(delimit == NULL){
         num = 4;
         delimit = "\n\t \0";
     }
     //Check for delimiters
     for(int i=0; i < num; i++){
         if(test == delimit[i])
             return true;
     }
     return false;
 }
bool check_non_numeric_char (char test_char)
Definition at line 13 of file utilities/rc_cmp/util.cpp.
Referenced by check_non_numeric_str().
{
     int num = (int)test_char;
     if(num > 57 || num < 48)
         return true;
     return false;
 }
bool check_non_numeric_char_per (char test_char)
Definition at line 23 of file utilities/rc_cmp/util.cpp.
Referenced by check_non_numeric_str_per().
{
     int num = (int)test_char;
     if(num > 57 || num < 48 || test_char == '.')
         return true;
     return false;
 }
bool check_non_numeric_str (string test_str)
Definition at line 33 of file utilities/rc_cmp/util.cpp.
References check_non_numeric_char(), and i.
Referenced by tpz_ordered::parse_layout(), tpz_fequad::parse_layout(), ComSwitch::parseValuesFromArguments(), and Fileselect::testTecplot().
{
     for(int i=0; i<test_str.length(); i++){
         if(check_non_numeric_char(test_str[i]))
             return true;
     }
     return false;
 }
bool check_non_numeric_str_per (string test_str)
Definition at line 42 of file utilities/rc_cmp/util.cpp.
References check_non_numeric_char_per(), and i.
{
     for(int i=0; i<test_str.length(); i++){
         if(check_non_numeric_char_per(test_str[i]))
             return true;
     }
     return false;
 }
pnt cross_product (pnt vec1, pnt vec2)
Definition at line 370 of file utilities/rc_cmp/util.cpp.
References pnt::size, and pnt::vals.
Referenced by side_check().
{
     pnt ret;
     if(vec1.size < 3 || vec2.size < 3)
         return ret;
     ret.size = 3;
     ret.vals = new long double[3];
     ret.vals[0] = (vec1.vals[1]*vec2.vals[2] - vec1.vals[2]*vec2.vals[1]);
     ret.vals[1] = (vec1.vals[2]*vec2.vals[0] - vec1.vals[0]*vec2.vals[2]);
     ret.vals[2] = (vec1.vals[0]*vec2.vals[1] - vec1.vals[1]*vec2.vals[0]);
     return ret;
 }
long double dist (long double * coord1, long double * coord2, int size)
Definition at line 305 of file utilities/rc_cmp/util.cpp.
References i, Mesquite::pow(), and sqrt().
Referenced by Mesh::NodalCoordinates::closest_node(), Mesh::NodalCoordinates::closest_point(), rflu_modrepair3d::coarsn(), rflu_modrepair3d::densfn(), CImg< uintT >::dijkstra(), Mesh::FindPointInMesh(), Mesh::FindPointInMesh_2(), connect_points::get_closest(), indexed_points::get_closest(), CImg< uintT >::get_index(), Overlay::insert_node_in_blue_edge(), main(), rflu_modrepair3d::octfnd(), plag_rflu_modfindcells::plag_rflu_findcellstrajfast(), plag_rflu_modfindcells::plag_rflu_findcellstrajsafe(), project_window(), rflo_getdeformation(), rflo_modlaplacesmoothing::rflo_laplacegridsolve(), rflo_laplacegridsolve(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframemovecorners(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflu_modoles::rflu_buildstencilsoles(), rflu_modgeometrytools::rflu_computelinecellxsectfast(), rflu_modconstraintutils::rflu_getconstrtype(), rflu_modconstraintutils::rflu_getconstrvalue(), rflu_modoctree::rflu_queryoctree(), rflu_modrindstates::rflu_setrindstatefarfieldperf(), rflu_modstencilsutils::rflu_sortbfaces(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), and Rocmop::smooth_vol_mesq_ng().
{
     long double total = 0;
     for(int i=0; i<size; i++){
         total += pow( coord2[i] - coord1[i], 2 );
     }
     total = sqrt(total);
     return total;
 }
long double dot_product (pnt vec1, pnt vec2)
Definition at line 387 of file utilities/rc_cmp/util.cpp.
References i, nan(), pnt::size, and pnt::vals.
Referenced by accumulatexyzwork(), angle(), c3d6nm(), computeflux(), computefluxtot(), inrt_augmentdissources(), inrt_setparticletemp(), plag_getcellindicesoutflow(), plag_incelltest(), plag_modinjection::plag_injcsetpoolpos(), plag_injcsetpositions(), plag_injctestcell(), plag_injctilecalcrhs(), plag_rflu_injctilecalcrhs(), plag_wallbounce(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs2d(), rflo_modelliptsmoothing::rflo_elliptmatrixcoeffs3d(), rflo_exchangednodecopy(), rflo_exchangednodesend(), rflo_exchangegeometrycopy(), rflo_exchangegeometrysend(), rflo_modlaplacesmoothing::rflo_projectquadcorner(), rflo_viscousfluxpatch(), rflu_modgeometry::rflu_computefacedist(), side_check(), turb_vfluxhybridpatch(), turb_visfluxeddypatch(), and vol_elem_mat_ortho().
{
     if(vec1.size != vec2.size){
         return nan();
     }
     long double ret_val = 0.0;
     for(int i=0; i<vec1.size; i++){
         ret_val += vec1.vals[i] * vec2.vals[i];
     }
     return ret_val;
 }
string itoa (int n)
Convert an int to a string.
Parameters
n Integer to convert
Returns
String representation of the integer
Definition at line 6 of file utilities/rc_cmp/util.cpp.
References s.
Referenced by compareFiles(), datafile::LogFieldMappings(), tecplot_data::parse(), tpz_ordered::parse_data(), tpz_fequad::parse_data(), tpz_ordered::parse_layout(), tpz_fequad::parse_layout(), tecplot_data::read_header(), tecplot_data::zone_error_out(), and tecplot_data::zone_status_out().
                   {
     string s;
     std::stringstream out;
     out << n;
     return out.str();
 }
long double nan ()
Definition at line 401 of file utilities/rc_cmp/util.cpp.
Referenced by Interpolate::bilinear(), and dot_product().
                  {
     //Return NaN without compiler warning
     long double *zer = new long double;
     *zer = 0.0;
     long double ret = ( (*zer) / (*zer) );
     delete zer;
     return ret;
 }
bool pnt_in_tri (pnt test, pnt p1, pnt p2, pnt p3)
Definition at line 318 of file utilities/rc_cmp/util.cpp.
References side_check(), and pnt::size.
Referenced by Interpolate::getCell().
{
     if(test.size < 2 || p1.size < 2 || p2.size < 2 || p3.size < 2)
         return false;
     if( side_check(test, p1, p2, p3) &&
         side_check(test, p2, p3, p1) &&
         side_check(test, p3, p1, p2)   ){
             return true;
     }
     return false;
 }
std::vector<string> readCommaExpression (string rStack, string rNeedle)
Definition at line 187 of file utilities/rc_cmp/util.cpp.
References check_delimiters(), i, and j.
Referenced by tpz_ordered::parse_layout(), tpz_fequad::parse_layout(), Fileselect::testTecplot(), and tecplot_data::zone_detect().
{
     std::vector<string> null_res;
     //
     //Search for needle in stack
     //
     bool needle_found;
     int i;
     for(i=0; i < (rStack.length()-rNeedle.length()) + 1; i++){
         char check = '\0';
         if( i > 0 )
             check = rStack[i-1];
         if( i == 0 || check_delimiters(NULL, 0, check) ){
             needle_found = true;
             for(int j=0; j<rNeedle.length(); j++){
                 if( rStack[i+j] != rNeedle[j] )
                     needle_found = false;
             }
         }
         if(needle_found)
             break;
     }
     //Not found
     if(!needle_found)
         return null_res;
     i += rNeedle.length();
     //
     //Skip Whitespace, check for '='
     //
     char c = rStack[i];
     while(c == ' '){
         i++;
         c = rStack[i];
     }
     //Check for '='
     if(c != '=')
         return null_res;
     else
         i++;
     c = rStack[i];
     while(c == ' '){
         i++;
         c = rStack[i];
     }
     std::vector<string> values;
     //
     //Read Values
     //
     //Move back one character
     // - Neccessary due to loop
     i--;
     do{
         i++;
         c = rStack[i];
         //Skip whitespace
         while(c == ' '){
             i++;
             c = rStack[i];
         }
         //Read value
         string val("");
         while(c != ' ' && c != ',' && c != '='){
             val += rStack[i];
             i++;
             c = rStack[i];
         }
         if( c == '=')
             break;
         values.push_back(val);
     }
     while(c == ',');
     return values;
 }
std::vector<string> readQuoteExpression (string rStack, string rNeedle)
Read expressions of the form x = "test" "100" "another test".
Parameters
stack
Definition at line 77 of file utilities/rc_cmp/util.cpp.
References check_delimiters(), i, and j.
Referenced by tecplot_data::read_header().
{
     std::vector<string> null_res;
     //
     //Search for needle in stack
     //
     bool needle_found;
     int i;
     for(i=0; i < (rStack.length()-rNeedle.length()) + 1; i++){
         char check = '\0';
         if( i > 0 )
             check = rStack[i-1];
         if( i == 0 || check_delimiters(NULL, 0, check) ){
             needle_found = true;
             for(int j=0; j<rNeedle.length(); j++){
                 if( rStack[i+j] != rNeedle[j] )
                     needle_found = false;
             }
         }
         if(needle_found)
             break;
     }
     //Not found
     if(!needle_found)
         return null_res;
     i += rNeedle.length();
     //
     //Skip Whitespace, check for '='
     //
     char c = rStack[i];
     while(c == ' '){
         i++;
         c = rStack[i];
     }
     //Check for '='
     if(c != '=')
         return null_res;
     else
         i++;
     c = rStack[i];
     while(c == ' '){
         i++;
         c = rStack[i];
     }
     std::vector<string> values;
     //
     //Read Values
     //
     while(c == '"'){
         //Check for valid parentheses
         int end = rStack.length();
         i++;
         for(end=0; end<rStack.length(); end++){
             c = rStack[i+end];
             if(c == '"')
                 break;
         }
         //Read value
         string val("");
         int limit = end+i;
         for(i; i < limit; i++){
             val += rStack[i];
         }
         i++;
         values.push_back(val);
         //Skip whitespace
         c = rStack[i];
         while(c == ' '){
             i++;
             c = rStack[i];
         }
     }
     return values;
 }
bool same_elements (std::vector< int > vector_1, std::vector< int > vector_2)
Definition at line 430 of file utilities/rc_cmp/util.cpp.
Referenced by compareFiles().
{
     for(int vec1_element_num = 0; vec1_element_num < vector_1.size(); vec1_element_num++){
         bool match_found = false;
         for(int vec2_element_num = 0; vec2_element_num < vector_2.size(); vec2_element_num++){
             //check for matching element
             if(vector_1[vec1_element_num] == vector_2[vec2_element_num]){
                 match_found = true;
                 break;
             }
         }
         if(!match_found)
             return false;
     }
     return true;
 }
bool side_check (pnt test, pnt p1, pnt p2, pnt check)
Definition at line 332 of file utilities/rc_cmp/util.cpp.
References cross_product(), dot_product(), pnt::size, and pnt::vals.
Referenced by pnt_in_tri().
{
     //Line to check
     pnt line;
     line.size = 3;
     line.vals = new long double[3];
     line.vals[0] = p2.vals[0] - p1.vals[0];
     line.vals[1] = p2.vals[1] - p1.vals[1];
     line.vals[2] = 0.0;
     //Test point vector
     pnt tpt;
     tpt.size = 3;
     tpt.vals = new long double[3];
     tpt.vals[0] = test.vals[0] - p1.vals[0];
     tpt.vals[1] = test.vals[1] - p1.vals[1];
     tpt.vals[2] = 0.0;
     //Check point vector
     pnt checkvec;
     checkvec.size = 3;
     checkvec.vals = new long double[3];
     checkvec.vals[0] = check.vals[0] - p1.vals[0];
     checkvec.vals[1] = check.vals[1] - p1.vals[1];
     checkvec.vals[2] = 0.0;
     pnt res1 = cross_product(line, tpt);
     pnt res2 = cross_product(line, checkvec);
     if( dot_product(res1, res2) >= 0.0 )
         return true;
     return false;
 }
std::vector<string> str_tokenize (string full, string delimiters)
Definition at line 413 of file utilities/rc_cmp/util.cpp.
Referenced by ComSwitch::parseValuesFromArguments().
{
     std::vector<string> ret;
     string::size_type start = full.find_first_not_of(delimiters, 0);
     string::size_type end = full.find_first_of(delimiters, start);
     while(start != string::npos || end != string::npos){
         ret.push_back(full.substr(start, end-start));
         start = full.find_first_not_of(delimiters, end);
         end = full.find_first_of(delimiters, start);
     }
     return ret;
 }