Rocstar: v3d10_nl_arruda_boyce_damping.f90 File Reference
v3d10_nl_arruda_boyce_damping.f90 File Reference
Functions/Subroutines
subroutine v3d10_nl_arruda_boyce_damping (coor, matcstet, lmcstet, R_in, d, S11, S22, S33, S12, S23, S13, numnp, nstart, nend, numcstet, numat_vol, mu, kappa, rho, cd_fastest, DetFold, velo, dt)
Function/Subroutine Documentation
subroutine v3d10_nl_arruda_boyce_damping (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:numcstet) matcstet, integer, dimension(1:10,1:numcstet) lmcstet, real*8, dimension(1:3*numnp) R_in, real*8, dimension(1:3*numnp) d, real*8, dimension(1:4,1:numcstet) S11, real*8, dimension(1:4,1:numcstet) S22, real*8, dimension(1:4,1:numcstet) S33, real*8, dimension(1:4,1:numcstet) S12, real*8, dimension(1:4,1:numcstet) S23, real*8, dimension(1:4,1:numcstet) S13, integer numnp, integer nstart, integer nend, integer numcstet, integer numat_vol, real*8, dimension(1:numat_vol) mu, real*8, dimension(1:numat_vol) kappa, real*8, dimension(1:numat_vol) rho, real*8 cd_fastest, real*8, dimension(1:4, 1:numcstet) DetFold, real*8, dimension(1:3*numnp) velo, real*8 dt)
Definition at line 53 of file v3d10_nl_arruda_boyce_damping.f90.
References arruda_boyce(), artificialdamping(), Plane_3< R, T >::d(), i, and j.
Referenced by updatestructuralsoln::internalforce_v3d10().