Rocstar: v3d10_nl_huang.f90 File Reference
v3d10_nl_huang.f90 File Reference
Functions/Subroutines
subroutine v3d10_nl_huang (coor, matcstet, lmcstet, R_in, d, S11, S22, S33, S12, S23, S13, numnp, nstart, nend, numcstet, numat_vol, STATEV_Part1, STATEV_Part2, NSTATEV, MATRIX, NMATRIX, PARTICLE, NPARTICLE, NPARTICLETYPE, INTERFAC, NINTERFAC, StrainTrace)
Function/Subroutine Documentation
subroutine v3d10_nl_huang (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:numcstet) matcstet, integer, dimension(1:10,1:numcstet) lmcstet, real*8, dimension(1:3*numnp) R_in, real*8, dimension(1:3*numnp) d, real*8, dimension(1:4,1:numcstet) S11, real*8, dimension(1:4,1:numcstet) S22, real*8, dimension(1:4,1:numcstet) S33, real*8, dimension(1:4,1:numcstet) S12, real*8, dimension(1:4,1:numcstet) S23, real*8, dimension(1:4,1:numcstet) S13, integer numnp, integer nstart, integer nend, integer numcstet, integer numat_vol, real*8, dimension(1:numcstet) STATEV_Part1, real*8, dimension(1:numcstet) STATEV_Part2, integer NSTATEV, real*8, dimension(1:nmatrix) MATRIX, integer NMATRIX, real*8, dimension(1:nparticle,1:nparticletype) PARTICLE, integer NPARTICLE, integer NPARTICLETYPE, real*8, dimension(1:ninterfac) INTERFAC, integer NINTERFAC, real*8, dimension(1:numcstet) StrainTrace)
Definition at line 53 of file v3d10_nl_huang.f90.
References Plane_3< R, T >::d(), huang_const_model(), i, j, CImg< T >::matrix(), and s.
Referenced by updatestructuralsoln::internalforce_v3d10(), and testconst().