Rocstar: v3d4.f90 File Reference
v3d4.f90 File Reference
Functions/Subroutines
subroutine v3d4 (coor, matcstet, lmcstet, R_in, d, ci, S11, S22, S33, S12, S23, S13, numnp, nstart, nend, numcstet, numat_vol)
Function/Subroutine Documentation
subroutine v3d4 (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:numcstet) matcstet, integer, dimension(1:4,1:numcstet) lmcstet, real*8, dimension(1:3*numnp) R_in, real*8, dimension(1:3*numnp) d, real*8, dimension(1:9,1:numat_vol) ci, real*8, dimension(1:numcstet) S11, real*8, dimension(1:numcstet) S22, real*8, dimension(1:numcstet) S33, real*8, dimension(1:numcstet) S12, real*8, dimension(1:numcstet) S23, real*8, dimension(1:numcstet) S13, integer numnp, integer nstart, integer nend, integer numcstet, integer numat_vol)
Definition at line 53 of file v3d4.f90.
References Plane_3< R, T >::d(), i, j, Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
Referenced by updatestructuralsoln::internalforce_v3d4().