Rocstar: v3d4_NeoHookeanInCompressPrin.f90 File Reference
v3d4_NeoHookeanInCompressPrin.f90 File Reference
Functions/Subroutines
subroutine v3d4_neohookeanincompressprin (coor, matcstet, lmcstet, R_in, d, ci, S11, S22, S33, S12, S23, S13, numnp, nstart, nend, numcstet, numat_vol, xmu, xkappa, xlambda)
Function/Subroutine Documentation
subroutine v3d4_neohookeanincompressprin (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:numcstet) matcstet, integer, dimension(1:4,1:numcstet) lmcstet, real*8, dimension(1:3*numnp) R_in, real*8, dimension(1:3*numnp) d, real*8, dimension(1:9,1:numat_vol) ci, real*8, dimension(1:numcstet) S11, real*8, dimension(1:numcstet) S22, real*8, dimension(1:numcstet) S33, real*8, dimension(1:numcstet) S12, real*8, dimension(1:numcstet) S23, real*8, dimension(1:numcstet) S13, integer numnp, integer nstart, integer nend, integer numcstet, integer numat_vol, real*8 xmu, real*8 xkappa, real*8 xlambda)
Definition at line 53 of file v3d4_NeoHookeanInCompressPrin.f90.
References cauchystressprinc(), Plane_3< R, T >::d(), i, j, jacobi(), and StopWatch::stop().