Rocstar: v3d4_NeoHookeanInCompressDef.f90 File Reference
v3d4_NeoHookeanInCompressDef.f90 File Reference
Functions/Subroutines
subroutine v3d4_neohookeanincompressdef (coor, matcstet, lmcstet, R_in, d, ci, S11, S22, S33, S12, S23, S13, numnp, nstart, nend, numcstet, numat_vol, xmu, xkappa)
real *8 function rmat3_det (a)
subroutine neoinccauchystress (ndime, xmu, detf, btens, sigma)
subroutine addpres (ndime, press, sigma)
Function/Subroutine Documentation
subroutine addpres (integer ndime, real*8 press, real*8, dimension(1:3,1:3) sigma)
Definition at line 528 of file v3d4_NeoHookeanInCompressDef.f90.
References id().
Referenced by v3d4_neohookeanincompressdef().
subroutine neoinccauchystress (integer ndime, real*8 xmu, real*8 detf, real*8, dimension(1:3,1:3) btens, real*8, dimension(1:3,1:3) sigma)
Definition at line 484 of file v3d4_NeoHookeanInCompressDef.f90.
References id(), and CImg< T >::trace().
Referenced by v3d4_neohookeanincompressdef().
real*8 function rmat3_det (real*8, dimension(3,3) a)
Definition at line 450 of file v3d4_NeoHookeanInCompressDef.f90.
References Line_2< R, T >::a().
Referenced by rmat3_det(), and v3d4_neohookeanincompressdef().
subroutine v3d4_neohookeanincompressdef (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:numcstet) matcstet, integer, dimension(1:4,1:numcstet) lmcstet, real*8, dimension(1:3*numnp) R_in, real*8, dimension(1:3*numnp) d, real*8, dimension(1:9,1:numat_vol) ci, real*8, dimension(1:numcstet) S11, real*8, dimension(1:numcstet) S22, real*8, dimension(1:numcstet) S33, real*8, dimension(1:numcstet) S12, real*8, dimension(1:numcstet) S23, real*8, dimension(1:numcstet) S13, integer numnp, integer nstart, integer nend, integer numcstet, integer numat_vol, real*8, dimension(1:numat_vol) xmu, real*8, dimension(1:numat_vol) xkappa)
Definition at line 53 of file v3d4_NeoHookeanInCompressDef.f90.
References addpres(), Plane_3< R, T >::d(), i, ic, j, neoinccauchystress(), rmat3_det(), and StopWatch::stop().