Rocstar: v3d4_volume.f90 File Reference
v3d4_volume.f90 File Reference
Functions/Subroutines
subroutine v3d4_volume (coor, lmcstet, matcstet, rho, numnp, numcstet, numat_vol, Disp, nstart, nend, TotalMass, TotalGeomVolp, TotalGeomUndefVolp, NumVertx)
subroutine triangle_area_3d (x1, y1, z1, x2, y2, z2, x3, y3, z3, area)
subroutine cross_3d (x1, y1, z1, x2, y2, z2, x3, y3, z3)
real *8 function enorm_3d (x1, y1, z1)
Function/Subroutine Documentation
subroutine cross_3d (real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2, real*8 x3, real*8 y3, real*8 z3)
Definition at line 239 of file v3d4_volume.f90.
Referenced by triangle_area_3d().
real*8 function enorm_3d (real*8 x1, real*8 y1, real*8 z1)
Definition at line 292 of file v3d4_volume.f90.
References sqrt().
Referenced by enorm_3d(), and triangle_area_3d().
subroutine triangle_area_3d (real*8 x1, real*8 y1, real*8 z1, real*8 x2, real*8 y2, real*8 z2, real*8 x3, real*8 y3, real*8 z3, real*8 area)
Definition at line 208 of file v3d4_volume.f90.
References cross_3d(), and enorm_3d().
subroutine v3d4_volume (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:numvertx,1:numcstet) lmcstet, integer, dimension(1:numcstet) matcstet, real*8, dimension(1:numat_vol) rho, integer numnp, integer numcstet, integer numat_vol, real*8, dimension(1:3*numnp) Disp, integer nstart, integer nend, real*8 TotalMass, real*8 TotalGeomVolp, real*8 TotalGeomUndefVolp, integer NumVertx)
Definition at line 53 of file v3d4_volume.f90.
References i.
Referenced by rocfracmain::rocfracinitialize(), and rocfracmain::rocfracsoln().