Rocstar: v3d8_mass.f90 File Reference
v3d8_mass.f90 File Reference
Functions/Subroutines
subroutine v3d8_mass (coor, nodes, MatType, rho, xm, NumNP, NumEl, NumMat, nstart, nend)
Function/Subroutine Documentation
subroutine v3d8_mass (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:8,1:numel) nodes, integer, dimension(1:numel) MatType, real*8, dimension(1:nummat) rho, real*8, dimension(1:numnp) xm, integer NumNP, integer NumEl, integer NumMat, integer nstart, integer nend)
Definition at line 53 of file v3d8_mass.f90.
References coord, Polyhedron_incremental_builder_3< HDS >::error(), get_jacobien(), get_shape(), i, StopWatch::stop(), and x.
Referenced by updatemassmatrix().