Rocstar: v3d8_me.f90 File Reference
v3d8_me.f90 File Reference
Functions/Subroutines
subroutine v3d8_me (coor, MatType, ElConnVol, Rnet, disp, dmat, S11, S22, S33, S12, S23, S13, numnp, nstart, nend, NumEL, NumMatType, Aenh, enhanced_map, mixed_map)
subroutine get_shape (r, n, dn, igpt)
subroutine get_shape20 (r, n, dn, igpt)
subroutine get_jacobien (coords, mcrd, nnode, dn, jac, jacinv, detj, error)
subroutine tensormul (a, lda, n, achar, b, ldb, m, bchar, c, ldc, alpha, beta)
subroutine invert (a, nrow, det)
subroutine invert3x3 (a, det)
subroutine get_mixed_map (e_mixed, r, igpt)
subroutine get_enhanced_map (e_enhanced, r, igpt)
subroutine kronecker_product (a, lda, nda, b, ldb, ndb, c, ldc)
Function/Subroutine Documentation
subroutine get_enhanced_map (dimension(9,9) e_enhanced, dimension(3,*) r, igpt)
Definition at line 1572 of file v3d8_me.f90.
References Connectivity::dimension(), Color::r(), and Matrix3D::zero().
subroutine get_jacobien (dimension(1:3,1:nnode) coords, mcrd, nnode, dimension(nnode,mcrd) dn, double precision, dimension(mcrd,mcrd) jac, double precision, dimension(mcrd,mcrd) jacinv, detj, logical error)
Definition at line 1003 of file v3d8_me.f90.
References Connectivity::dimension(), Polyhedron_incremental_builder_3< HDS >::error(), invert3x3(), tensormul(), and Matrix3D::zero().
Referenced by implicit_v3d8_mass(), implicit_v3d8_mass_consistent(), implicit_v3d8_me_k(), locthermcap_v3d8(), locthermstiff_v3d8(), v3d8_mass(), and v3d8_me().
subroutine get_mixed_map (dimension(9,12) e_mixed, dimension(3,*) r, igpt)
Definition at line 1511 of file v3d8_me.f90.
References Connectivity::dimension(), Color::r(), and Matrix3D::zero().
subroutine get_shape (double precision, dimension(3,*) r, double precision, dimension(*) n, double precision, dimension(8,*) dn, igpt)
Definition at line 846 of file v3d8_me.f90.
References n, and Color::r().
Referenced by implicit_v3d8_mass(), implicit_v3d8_mass_consistent(), implicit_v3d8_me_k(), locthermcap_v3d8(), locthermstiff_v3d8(), v3d8_mass(), and v3d8_me().
subroutine get_shape20 (double precision, dimension(3,*) r, double precision, dimension(*) n, double precision, dimension(20,*) dn, igpt)
Definition at line 924 of file v3d8_me.f90.
References n, and Color::r().
subroutine invert (real*8, dimension(1:nrow,1:nrow) a, integer nrow, real*8 det)
Definition at line 1392 of file v3d8_me.f90.
References Line_2< R, T >::a(), i, j, k, ncol, and nrow.
Referenced by implicit_v3d8_me_k(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), and v3d8_me().
subroutine invert3x3 (double precision, dimension(3,3) a, double precision det)
Definition at line 1454 of file v3d8_me.f90.
References Line_2< R, T >::a(), and Matrix3D::zero().
Referenced by artificialdamping(), get_jacobien(), implicit_v3d8_me_k(), and v3d8_me().
subroutine kronecker_product (dimension(lda,nda) a, lda, nda, dimension(ldb,ndb) b, ldb, ndb, dimension(ldc,*) c, ldc)
Definition at line 1625 of file v3d8_me.f90.
References Line_2< R, T >::a(), Color::b(), Line_2< R, T >::c(), Connectivity::dimension(), iend, and jend.
Referenced by implicit_v3d8_me_k(), and v3d8_me().
subroutine tensormul (dimension(lda,*) a, lda, n, character*1 achar, dimension(ldb,*) b, ldb, m, character*1 bchar, dimension(ldc,*) c, ldc, alpha, beta)
Definition at line 1060 of file v3d8_me.f90.
References Line_2< R, T >::a(), Color::alpha(), Color::b(), Line_2< R, T >::c(), Connectivity::dimension(), i, j, k, Aff_transformation_2< R_ >::m(), max(), n, and StopWatch::stop().
Referenced by get_jacobien(), and implicit_v3d8_me_k().
subroutine v3d8_me (real*8, dimension(1:3,1:numnp) coor, integer, dimension(1:numel) MatType, integer, dimension(1:8,1:numel) ElConnVol, real*8, dimension(1:3*numnp) Rnet, real*8, dimension(1:3*numnp) disp, real*8, dimension(nummattype,9,9) dmat, real*8, dimension(1:numel) S11, real*8, dimension(1:numel) S22, real*8, dimension(1:numel) S33, real*8, dimension(1:numel) S12, real*8, dimension(1:numel) S23, real*8, dimension(1:numel) S13, integer numnp, integer nstart, integer nend, integer NumEL, integer NumMatType, real*8, dimension(1:9,1:numel) Aenh, real*8, dimension(1:8,1:9,1:9) enhanced_map, real*8, dimension(1:8,1:9,1:12) mixed_map)
Definition at line 53 of file v3d8_me.f90.
References coord, Polyhedron_incremental_builder_3< HDS >::error(), get_jacobien(), get_shape(), i, invert(), invert3x3(), j, k, kronecker_product(), and CImg< T >::sum().
Referenced by updatestructuralsoln::internalforce_v3d8().