Rocstar: Vector_n.h File Reference
Vector_n.h File Reference
#include "rfc_basic.h"
#include <functional>
Classes
class Array_n_const
class Array_n
class Vector_n
Functions
bool operator== (const Array_n_const &v1, const Array_n_const &v2)
Vector_n operator+ (const Array_n_const &v1, const Array_n_const &v2)
Vector_n operator- (const Array_n_const &v1, const Array_n_const &v2)
Real operator* (const Array_n_const &v1, const Array_n_const &v2)
Vector_n operator* (Real a, const Array_n_const &v1)
Vector_n operator* (const Array_n_const &v1, Real a)
Vector_n operator/ (const Array_n_const &v1, Real a)
Vector_n multiply (const Array_n_const &v1, const Array_n_const &v2)
Vector_n divide (const Array_n_const &v1, const Array_n_const &v2)
Vector_n min (const Array_n_const &v1, const Array_n_const &v2)
Vector_n max (const Array_n_const &v1, const Array_n_const &v2)
std::ostream & operator<< (std::ostream &os, const Array_n_const &v)
Function Documentation
Vector_n divide (const Array_n_const & v1, const Array_n_const & v2) inline
Definition at line 338 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, Array_n::_start, and RFC_assertion.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = (*q==0)? 1. : *p / *q;
   return v3;
 }
Vector_n max (const Array_n_const & v1, const Array_n_const & v2) inline
Definition at line 354 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, Array_n::_start, and RFC_assertion.
Referenced by Numerics::___safe_fpt_division(), Attribute::allocate(), artificialdamping(), bcondoutflowperf(), bcondoutflowperf_gl(), Propagation_3::bound_axial_disp(), Propagation_3::bound_radial_disp(), Propagation_3::bound_spherical_disp(), init_py::burn_get_film_coeff_1d(), c3d6nm(), Roccom_base::call_function(), rflu_modrepair3d::cavbnd(), rflu_modrepair3d::cavedg(), rflu_modrepair3d::cavity(), rflu_modrepair3d::coarsn(), rflu_modrepair3d::colaps(), Pane_connectivity::collect_nodes(), COM_get_attribute(), COM_print_window(), Geo_Metric_Base_3::compute_angles(), Rocsurf::compute_edge_lengths(), Rocmop::compute_medial_quadric(), computeavgco(), computefluxtot(), Control_parameters::Control_parameters(), convertflo2flumesh(), convertflo2flupatch(), copypatchdata(), RFC_Window_overlay::cos_edge_angle(), rflu_modrepair3d::datsrf(), rflu_modrepair3d::densfn(), RFC_Window_overlay::detect_features(), Rocmop::determine_physical_border(), rflu_modrepair3d::edglen(), Rocmop::eigen_analyze_vertex(), Transfer_base::element_load_vector(), Element_node_enumerator::Element_node_enumerator(), equal(), feminp(), FaceOffset_3::filter_and_identify_ridge_edges(), NonSmoothSteepestDescent::find_plane_points(), FindMagnitudeRange(), findprobe(), FindRange(), FindTraceRange(), PatchData::get_barrier_delta(), KNN_Grid< Tri >::get_cell_range(), Generic_element_2::get_gp_nat_coor(), Generic_element_2::get_gp_weight(), PatchData::get_minmax_element_unsigned_area(), Generic_element_2::get_num_gp(), Rocmop::get_redist_safe_factor(), FaceOffset_3::get_tangents(), Mesh::GetCoordinateBounds(), GetStatistics(), homogenizedmat(), Simple_manifold_2::init(), Window::init_done(), rflu_modrepair3d::input(), inrt_computemaxedges(), rflu_modrepair3d::insert(), KNN_Grid< Tri >::insertRange(), Overlay_primitives::intersect(), io_pane_attribute(), RFC_Window_overlay::is_strong_ad(), jacobi(), Mesquite::Linf(), load_data_HDF4(), rflu_modrepair3d::lock(), main(), matmodel_elastic(), matmodel_hyperelastic(), matvol_sub(), Segment_3< R, T >::max(), Segment_2< R >::max(), max_element__(), maxPoint(), min_element__(), Transfer_base::minmax(), rflu_modrepair3d::neighb(), rflu_modrepair3d::octfil(), rflu_modrepair3d::octfnd(), rflu_modoctree::octree(), Rocblas::maxv< T >::operator()(), Max< NT >::operator()(), Bbox_3::operator+(), Bbox_2::operator+(), Bbox_3::operator+=(), Bbox_2::operator+=(), Mesh::BSExtent< T >::Overlap(), Pane_connectivity::pconn_nblocks(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_initsolution(), peul_centraldissipation(), peul_initgenxinterface(), peul_readconpartsection(), peul_residualsmoothingcoeffs(), plag_cecellsexchange(), plag_corncellsloaddata(), plag_edgecellsloaddata(), plag_initgenxinterface(), plag_patchloaddatabuffers(), plag_readdispartsection(), plag_rflu_initsolfromserial(), plag_moddimensions::plag_setmaxdimensions(), QualityAssessor::Assessor::print_histogram(), radi_extinctioncoef(), radi_floflimcentraldissipation(), radi_floflimcorrcornedgecells(), radi_rflo_flimressmoothingcoeff(), rflu_modrepair3d::radrat(), read_io_files(), read_patran(), read_reg(), FloGridBlock::ReadBlock(), readmultigridsection(), prep_modbcdistribution::readpatchsection(), readprobesection(), setup_py::readtable(), readthrustsection(), readtimestepsection(), rflu_modrepair3d::recon(), Rocmop::redistribute_vertices_smooth(), reduce_int(), reduce_real(), PatchData::reorder(), rflu_modrepair3d::replace(), rflo_centraldissipation(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_correctcorneredgecells(), rflo_derivedinputvalues(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_findsourcepatches(), rflo_findthrustpatches(), rflo_mapregionsprocessors(), rflo_modmovegridframe::rflo_mgframecornpoints(), rflo_modmovegridframe::rflo_mgframeinterfaces(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_openprobefile(), rflo_readstat(), rflo_readstatregion(), rflo_residualsmoothingcoeffs(), rflo_timestepinviscid(), rflo_timestepviscous(), rflo_writestat(), rflu_modfacelist::rflu_buildavface2borderlist(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilscells::rflu_buildc2cstencilbasic(), rflu_modstencilscells::rflu_buildc2cstencilbasic_1d(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil_1d(), rflu_modgeometry::rflu_buildgeometry(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_modcommlists::rflu_comm_buildcommlistsvert(), rflu_moddifferentiationbfaces::rflu_computebfgradconstr(), rflu_computedcuhreinfo(), rflu_computeenerdissoles(), rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), rflu_modoles::rflu_computegeometrictermsoles(), rflu_moddifferentiationcells::rflu_computegradcellsconstr(), rflu_moddifferentiationfaces::rflu_computegradconstrained(), rflu_moddifferentiationfaces::rflu_computegradfacesconstr(), rflu_modlimiters::rflu_computelimiterbarthjesp(), rflu_modlimiters::rflu_computelimitervenkat(), rflu_modgeometrytools::rflu_computelinecellxsectfast(), rflu_modgeometrytools::rflu_computelinecellxsectsafe(), rflu_modpatchutils::rflu_computepatchnormalsglobal(), rflu_modpatchutils::rflu_computepatchnormalslocal(), rflu_modweights::rflu_computewtsbf2c(), rflu_modweights::rflu_computewtsf2c(), rflu_convfluxoles(), rflu_modweights::rflu_createwtsbf2c(), rflu_modweights::rflu_createwtsf2c(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_modincelltest::rflu_ict_computetolerance(), rflu_initflowhardcode(), rflu_modmpi::rflu_mpi_settag(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modoctree::rflu_queryoctree(), rflu_scalarfirst(), rflu_scalarsecond(), rflu_modstencilsbfaces::rflu_setinfobf2cstencil(), rflu_modstencilsbfaces::rflu_setinfobf2cstencil_1d(), rflu_modstencilsfaces::rflu_setinfof2cstencil(), rflu_modstencilsfaces::rflu_setinfof2cstencil_1d(), rflu_setmovegridoptions(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rflu_modtimezoom::rflu_timezoomcomputebulkvars(), rflu_modtimezoom::rflu_timezoomsumaddsource(), rocflo_2dto3d(), rocfracmain::rocfracsoln(), rocvav_post(), rvav_blasiussolution(), rvav_computeerror(), rvav_readfilestream1(), rvav_readfilestream2analyt(), rvav_readfilestream2comput(), rvav_readfilestream2experm(), HDF4::SDgetrange(), HDF4::SDsetrange(), Overlay::set_tolerance(), Connectivity::size_of_elements(), Connectivity::size_of_ghost_elements(), Connectivity::size_of_real_elements(), rflu_modrepair3d::smooth(), rflu_modrepair3d::snglar(), FaceOffset_3::solve_quadratic_func(), rflu_modrepair3d::struct(), RFC_Window_overlay::subdiv_feature_curve(), summary(), tensormul(), rflu_modrepair3d::tessel(), rflu_modrepair3d::tetang(), rflu_modrepair3d::tetloc(), rflu_modrepair3d::tetmv(), TRAIL_FD2FE_WinCreate(), TRAIL_Get_Block_Structured_Neighbors(), TRAIL_Search_Block_Structured_Pool(), rflu_modrepair3d::triswp(), turb_calcmetrics(), turb_coranswalldistov(), turb_cowlmreadbcsection(), turb_flolesaverageface(), turb_flolesgencocc(), turb_flolesgencoff(), turb_floranscentraldissipation(), turb_floranscorrcornedgecells(), turb_gettvcell(), turb_lescalceddyvis(), turb_lescontract(), turb_ransemsupdate(), turb_ranssageteddyvis(), turb_readturbsection(), turb_rflo_ransressmoothingcoeff(), turb_vfluxhybridpatch(), updatetbcstochastic(), write_attr_CGNS(), write_bounds(), and WriteElements().
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = std::max(*p,*q);
   return v3;
 }
Vector_n min (const Array_n_const & v1, const Array_n_const & v2) inline
Definition at line 346 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, Array_n::_start, and RFC_assertion.
Referenced by Numerics::___safe_fpt_division(), Attribute::allocate(), prep_modbcdistribution::bcfarfdistrib(), prep_modbcdistribution::bcinflowtotangdistrib(), prep_modbcdistribution::bcinflowveldistrib(), prep_modbcdistribution::bcinjectdistrib(), prep_modbcdistribution::bcnoslipdistrib(), prep_modbcdistribution::bcoutflowdistrib(), prep_modbcdistribution::bcslipwalldistrib(), Propagation_3::bound_axial_disp(), Propagation_3::bound_facial_speed(), Propagation_3::bound_nodal_motion(), Propagation_3::bound_radial_disp(), Propagation_3::bound_spherical_disp(), init_py::burn_get_film_coeff_1d(), c3d6nm(), rflu_modrepair3d::cavbnd(), rflu_modrepair3d::cavedg(), rflu_modrepair3d::cavity(), NonSmoothSteepestDescent::check_equilibrium(), rflu_modrepair3d::coarsn(), rflu_modrepair3d::colaps(), Pane_connectivity::collect_nodes(), COM_F_FUNC2(), COM_get_attribute(), Geo_Metric_Base_3::compute_angles(), FaceOffset_3::compute_anisotropic_vertex_centers(), Rocsurf::compute_edge_lengths(), Window_manifold_2::compute_shortest_edgelen_elements(), Window_manifold_2::compute_shortest_edgelen_nodes(), convertflo2flumesh(), Attribute::copy_array(), copypatchdata(), RFC_Window_overlay::cos_edge_angle(), RFC_Window_overlay::cos_face_angle(), Pane_connectivity::create_b2map(), rflu_modrepair3d::datsrf(), RFC_Window_overlay::detect_features(), Simple_manifold_2::determine_incident_halfedges(), rflu_modrepair3d::edgerm(), rflu_modrepair3d::edglen(), Transfer_base::element_load_vector(), NonSmoothSteepestDescent::find_plane_points(), FindMagnitudeRange(), FindRange(), FindTraceRange(), PatchData::get_barrier_delta(), m_rocburn_1d_apn::get_burning_rate_1d(), KNN_Grid< Tri >::get_cell_range(), Pane_connectivity::get_local_boundary_nodes(), PatchData::get_minmax_element_unsigned_area(), FaceOffset_3::get_tangents(), m_rocburn_1d_zn::get_time_step_1d(), Mesh::GetCoordinateBounds(), GetStatistics(), implicit_initialize(), m_rocburn_1d_apn::initialize_1d(), rflu_modrepair3d::input(), inrt_determinetokens(), inrt_readburning(), inrt_sourceterms(), rflu_modrepair3d::insert(), KNN_Grid< Tri >::insertRange(), RFC_Window_overlay::is_rstrong_ea(), jacobi(), rflu_modrepair3d::lock(), max_dt_solid(), max_element__(), Segment_3< R, T >::min(), Segment_2< R >::min(), min_element__(), Pane_boundary::min_squared_edge_len(), Transfer_base::minmax(), minPoint(), rflu_modrepair3d::neighb(), Rocblas::minv< T >::operator()(), Min< NT >::operator()(), Bbox_3::operator+(), Bbox_2::operator+(), Bbox_3::operator+=(), Bbox_2::operator+=(), Mesh::BSExtent< T >::Overlap(), Overlay::overlay(), peri_cocnlinitsolution(), peri_cocprinitsolution(), peri_copgradupdate(), peri_initsolution(), peul_readbcfarfsection(), peul_readbcinflowsection(), peul_readbcinjectsection(), peul_residualsmoothingcoeffs(), plag_moddatastruct::plag_dstr_buildcell2pcllist(), plag_moddatastruct::plag_dstr_recreatecell2pcllist(), plag_rflu_modfindcells::plag_rflu_findcellsoct(), plag_rflu_modfindcells::plag_rflu_findcellsoctkernel(), plag_rflu_modfindcells::plag_rflu_findcellsoctmod(), plag_rflu_initsolfromserial(), plag_rflu_initsolserial_3d(), plag_modsurfstats::plag_setbinindex(), RFC_Window_overlay::print_features(), QualityAssessor::Assessor::print_histogram(), radi_extinctioncoef(), radi_floflimcorrcornedgecells(), radi_rflo_flimressmoothingcoeff(), rflu_modrepair3d::radrat(), Rocin::read_by_control_file(), read_io_files(), read_patran(), read_reg(), FloGridBlock::ReadBlock(), prep_modbcdistribution::readpatchsection(), rflu_modrepair3d::recon(), Rocmop::redistribute_vertices_ridge(), Rocmop::redistribute_vertices_smooth(), reduce_int(), reduce_real(), rflu_modrepair3d::replace(), rflo_modboundaryconditions::rflo_bcondoutflowperf(), rflo_checkmetrics(), rflo_checkminimumcells(), rflo_checkvalidity(), rflo_modforcesmoments::rflo_computepatchforcemomco(), rflo_correctcorneredgecells(), rflo_dualtimestepping(), rflo_modforcesmoments::rflo_findpatchcoeffsglo(), rflo_findsourcepatches(), rflo_findthrustpatches(), rflo_modgridmetrics::rflo_gridqualityglobal(), rflo_initflowsolver(), rflo_modmovegridframe::rflo_mgframecorrectneighbors(), rflo_modmovegridframe::rflo_mgframesrchneighbors(), rflo_minimumtimestep(), rflo_openprobefile(), rflo_readbcfarfsection(), rflo_readbcinflowtotangsection(), rflo_readbcinflowvelsection(), rflo_readbcinjectapnsection(), rflo_readbcinjectmratesection(), rflo_readbcnoslipsection(), rflo_readbcoutflowsection(), rflo_readbcslipwallsection(), rflo_readtbcsection(), rflo_residualsmoothingcoeffs(), rflo_setmstagecoeffs(), rflo_timestepinviscid(), rflo_timestepviscous(), rflu_modstencilsbfaces::rflu_buildbf2cstencil(), rflu_modstencilscells::rflu_buildc2cstencil(), rflu_modstencilsfaces::rflu_buildf2cstencil(), rflu_centralfirstpatch(), rflu_centralfirstpatch_gl(), rflu_centralsecondpatch(), rflu_centralsecondpatch_gl(), rflu_computeexactflowerror(), rflu_computeexactflowprobeerror(), rflu_modexactflow::rflu_computeexactflowringleb(), rflu_modoles::rflu_computegeometrictermsoles(), rflu_modlimiters::rflu_computelimiterbarthjesp(), rflu_modlimiters::rflu_computelimitervenkat(), rflu_modpatchutils::rflu_computepatchnormalsglobal(), rflu_modpatchutils::rflu_computepatchnormalslocal(), rflu_modweights::rflu_computewtsx2c_1d(), rflu_derivedinputvalues(), rflu_modensight::rflu_ens_mapregion2server(), rflu_modprobes::rflu_findprobecells(), rflu_modrocstaradmin::rflu_genx_readctrlfile(), rflu_modhllcflux::rflu_hllc_computeflux1_gl(), rflu_modhllcflux::rflu_hllc_computeflux1_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux1_tcp(), rflu_modhllcflux::rflu_hllc_computeflux2_gl(), rflu_modhllcflux::rflu_hllc_computeflux2_mtcp(), rflu_modhllcflux::rflu_hllc_computeflux2_tcp(), rflu_initflowhardcode(), rflu_minimumtimestep(), rflu_movegridxyz(), rflu_modmpi::rflu_mpi_settag(), rflu_modnscbc::rflu_nscbc_compfirstpatchflux(), rflu_modnscbc::rflu_nscbc_comppatchflux(), rflu_modnscbc::rflu_nscbc_compsecondpatchflux(), rflu_modrenumberings::rflu_rnmb_buildsbc2pcmap3d(), rflu_scalarfirst(), rflu_scalarsecond(), rflu_modsymmetryperiodic::rflu_sype_buildvertexmaps(), rocstar_driver(), rocvav_post(), Coupling::run(), rvav_readfilestream1(), rvav_readfilestream2analyt(), rvav_readfilestream2comput(), rvav_readfilestream2experm(), HDF4::SDgetrange(), HDF4::SDsetrange(), rflu_modrepair3d::smooth(), rflu_modrepair3d::snglar(), spec_rflu_enforcebounds(), rflu_modrepair3d::struct(), RFC_Window_overlay::subdiv_feature_curve(), summary(), rflu_modrepair3d::tessel(), rflu_modrepair3d::tetang(), rflu_modrepair3d::tetmv(), thermal_initialize(), TRAIL_Get_Block_Structured_Neighbors(), TRAIL_Search_Block_Structured_Pool(), rflu_modrepair3d::triswp(), turb_coranswalldistov(), turb_cowlmreadbcsection(), turb_flolesaverageface(), turb_flolesgencocc(), turb_flolesgencoff(), turb_floranscorrcornedgecells(), turb_flowlmupdateloglay(), turb_rflo_ransressmoothingcoeff(), turb_wlmreyanalogy(), updatetbcstochastic(), write_attr_CGNS(), write_bounds(), and Overlay::write_inodes_tec().
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = std::min(*p,*q);
   return v3;
 }
Vector_n multiply (const Array_n_const & v1, const Array_n_const & v2) inline
Definition at line 330 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, Array_n::_start, and RFC_assertion.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = *p * *q;
   return v3;
 }
Real operator* (const Array_n_const & v1, const Array_n_const & v2) inline
Definition at line 300 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, and RFC_assertion.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Real t(0);
   for ( const Real *p=v1._start, *q=v2._start; p!=v1._end; ++p, ++q)
     t += *p * *q;
   return t;
 }
Vector_n operator* (Real a, const Array_n_const & v1) inline
Definition at line 309 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, and Array_n::_start.
{
   Vector_n v2( v1._end-v1._start);
   const Real *p=v1._start;
   for ( Real *q=v2._start; p!=v1._end; ++p, ++q) *q = a * *p;
   return v2;
 }
Vector_n operator* (const Array_n_const & v1, Real a) inline
Definition at line 316 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, and Array_n::_start.
{
   Vector_n v2( v1._end-v1._start);
   const Real *p=v1._start;
   for ( Real *q=v2._start; p!=v1._end; ++p, ++q) *q = a * *p;
   return v2;
 }
Vector_n operator+ (const Array_n_const & v1, const Array_n_const & v2) inline
Definition at line 282 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, Array_n::_start, and RFC_assertion.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r) *r = *p + *q;
   return v3;
 }
Vector_n operator- (const Array_n_const & v1, const Array_n_const & v2) inline
Definition at line 290 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, Array_n::_start, and RFC_assertion.
{
   RFC_assertion( v1._end-v1._start == v2._end-v2._start);
   Vector_n v3( v1._end-v1._start);
   const Real *p=v1._start, *q=v2._start;
   for ( Real *r=v3._start; p!=v1._end; ++p, ++q, ++r)
     *r = *p - *q;
   return v3;
 }
Vector_n operator/ (const Array_n_const & v1, Real a) inline
Definition at line 323 of file Vector_n.h.
References Array_n_const::_end, Array_n_const::_start, and Array_n::_start.
{
   Vector_n v2( v1._end-v1._start);
   const Real *p=v1._start;
   for ( Real *q=v2._start; p!=v1._end; ++p, ++q) *q = (a==0) ? 1.: *p / a;
   return v2;
 }
std::ostream& operator<< (std::ostream & os, const Array_n_const & v)
Definition at line 29 of file Vector_n.C.
References Array_n_const::begin(), and Array_n_const::end().
{
   const Real *p=v.begin();
   if ( p!=v.end()) for (;;) {
     os << *p;
     ++p;
     if ( p!=v.end())
       os << " ";
     else
       break;
   }
   return os;
 }
bool operator== (const Array_n_const & v1, const Array_n_const & v2) inline
Definition at line 274 of file Vector_n.h.
References Array_n_const::_end, and Array_n_const::_start.
{
   if ( v1._end-v1._start != v2._end-v2._start) return false;
   for ( const Real *p=v1._start, *q=v2._start; p!=v1._end; ++p,++q) {
     if ( *p != *q) return false;
   }
   return true;
 }