Rocstar: vol_elem_mat_ortho.f90 File Reference
vol_elem_mat_ortho.f90 File Reference
Functions/Subroutines
subroutine vol_elem_mat_ortho (ci_full, ci, NumMatVol, NumMatOrtho, MatOrtho, E11, E22, E33, xnu12, xnu13, xnu23, G12, G13, G23, vx1o, vy1o, vz1o, vx2o, vy2o, vz2o, vx3o, vy3o, vz3o)
Function/Subroutine Documentation
subroutine vol_elem_mat_ortho (real*8, dimension(1:6,1:6,1:nummatvol) ci_full, real*8, dimension(1:9,1:nummatvol) ci, integer NumMatVol, integer NumMatOrtho, integer, dimension(1:nummatvol) MatOrtho, real*8, dimension(1:nummatortho) E11, real*8, dimension(1:nummatortho) E22, real*8, dimension(1:nummatortho) E33, real*8, dimension(1:nummatortho) xnu12, real*8, dimension(1:nummatortho) xnu13, real*8, dimension(1:nummatortho) xnu23, real*8, dimension(1:nummatortho) G12, real*8, dimension(1:nummatortho) G13, real*8, dimension(1:nummatortho) G23, real*8, dimension(1:nummatortho) vx1o, real*8, dimension(1:nummatortho) vy1o, real*8, dimension(1:nummatortho) vz1o, real*8, dimension(1:nummatortho) vx2o, real*8, dimension(1:nummatortho) vy2o, real*8, dimension(1:nummatortho) vz2o, real*8, dimension(1:nummatortho) vx3o, real*8, dimension(1:nummatortho) vy3o, real*8, dimension(1:nummatortho) vz3o)
Definition at line 53 of file vol_elem_mat_ortho.f90.
References dot_product(), i, invert6x6(), Color::r(), x, y, and z.
Referenced by rocfracmain::rocfracinitialize().