Rocstar: VolRatio.f90 File Reference
VolRatio.f90 File Reference
Functions/Subroutines
subroutine volratio (n1, n2, n3, n4, AlphaR, coor, numnp, NdMassLump)
Function/Subroutine Documentation
subroutine volratio (integer n1, integer n2, integer n3, integer n4, real*8, dimension(1:4) AlphaR, real*8, dimension(1:3,1:numnp) coor, integer numnp, integer NdMassLump)
Definition at line 53 of file VolRatio.f90.
References calcoffset(), offset(), planenorm(), planenorm3d(), Aff_transformation_repS2< FT >::print(), StopWatch::stop(), and volume_lasserre_file().
Referenced by rocfracmain::rocfracinitialize().