Rocstar: Window.C File Reference
Window.C File Reference
This file contains the implementation of the Window object.
#include <iostream>
#include <cstdlib>
#include <cstdio>
#include "Window.h"
#include "roccom_assertion.h"
Functions
template<class Attr >
void get_size_common (const Attr *a, int pid, int *nitem, int *ng) throw (COM_exception)
template<class Attr >
void get_array_common (const Attr *a, int pid, Window::Pointer_descriptor &addr, int *strd, int *cap, bool is_const) throw (COM_exception)
template<class Attr >
void copy_array_common (const Attr *a, int pid, void *val, int v_strd, int v_size, int offset) throw (COM_exception)
Detailed Description
This file contains the implementation of the Window object.
See also
roccom_devel.h, Roccom_base.C
Definition in file Window.C.
Function Documentation
void copy_array_common (const Attr * a, int pid, void * val, int v_strd, int v_size, int offset) throw (COM_exception) inline
Definition at line 674 of file Window.C.
References append_frame, COM_ERR_NOT_A_WINDOW_ATTRIBUTE, Attribute::COPY_OUT, and offset().
Referenced by Window::copy_array().
{
   if ( pid==0 && a->location() != 'w')
     throw COM_exception( COM_ERR_NOT_A_WINDOW_ATTRIBUTE, append_frame
                          ( a->fullname(), Window::copy_size));
   const_cast<Attr*>(a)->copy_array( val, v_strd, v_size,
                                     offset, Attribute::COPY_OUT);
 }
void get_array_common (const Attr * a, int pid, Window::Pointer_descriptor & addr, int * strd, int * cap, bool is_const) throw (COM_exception)
Definition at line 602 of file Window.C.
References addr, append_frame, cap, COM_ERR_ATTRIBUTE_CONST, COM_ERR_INVALID_DIMENSION, COM_ERR_INVALID_SIZE, COM_ERR_NOT_A_WINDOW_ATTRIBUTE, Window::get_array(), and strd.
Referenced by Window::get_array().
{
   if ( !is_const && a->is_const() )
     throw COM_exception( COM_ERR_ATTRIBUTE_CONST, append_frame
                          (a->fullname(),Window::get_array));
   if ( pid==0 && a->location() != 'w')
     throw COM_exception( COM_ERR_NOT_A_WINDOW_ATTRIBUTE, append_frame
                          ( a->fullname(), Window::get_array));
   addr.ptr = (void*)(a->pointer());
   if ( addr.dim==1) {
     addr.n1 = a->capacity()*a->stride();
   }
   else if ( addr.dim == 2) {
     if ( a->stride()>=a->size_of_components()) {
       addr.n1 = a->stride();
       addr.n2 = a->capacity();
     }
     else {
       addr.n1 = a->capacity();
       addr.n2 = a->size_of_components();
     }
   }
   else {
     // Scalars must have capacity 1!
     if ( addr.dim==0 && (a->capacity()!=1 || a->size_of_components()!=1))
       throw COM_exception( COM_ERR_INVALID_SIZE, append_frame
                            (a->fullname(),Window::get_array));
     if ( addr.dim>2)
       throw COM_exception( COM_ERR_INVALID_DIMENSION, append_frame
                            (a->fullname(),Window::get_array));
   }
   if ( cap)  *cap = a->capacity();
   if ( strd) *strd = a->stride();
 }
void get_size_common (const Attr * a, int pid, int * nitem, int * ng) throw (COM_exception)
Definition at line 493 of file Window.C.
References append_frame, COM_ERR_NOT_A_WINDOW_ATTRIBUTE, and Window::get_size().
Referenced by Window::get_size().
 {
   if ( pid==0 && a->location() != 'w')
     throw COM_exception( COM_ERR_NOT_A_WINDOW_ATTRIBUTE, append_frame
                          ( a->fullname(), Window::get_size));
   if ( nitem) *nitem = a->size_of_items();
   if ( ng)    *ng = a->size_of_ghost_items();
 }