Rocstar: writetop.cpp File Reference
writetop.cpp File Reference
#include <stdio.h>
#include "makeflo.h"
#include "face.h"
Classes
class bcRecTop
class bcListTop
Functions
static void write5 (FILE *out, int face, int l1lo, int l1hi, int l2lo, int l2hi)
void node2block (int a, int b, int &o, int &p)
static void writeSpan (FILE *out, const blockSpan &s, const blockLoc &sign)
static void writePatchStart (FILE *out, int patchType)
static void writePatchMiddle (FILE *out, int connBlock)
static void writePatchEnd (FILE *out, int coupled)
static void writeBlock (FILE *out, const bcListTop &bc, const block *b)
const char * writeTop (vector< block * > &blocks, const char *inBcs, const char *outTop)
Function Documentation
void node2block (int a, int b, int & o, int & p)
Definition at line 148 of file writetop.cpp.
Referenced by writeSpan().
{
         if (a<b)
         { //Nodes are oriented the right way:
                 o=a;
                 p=b-2; //Minus 1 for node->block, minus 1 again for excl->incl
         } else {//Nodes run the other way:
                 o=a-1;
                 p=b-1;
         }
 }
static void write5 (FILE * out, int face, int l1lo, int l1hi, int l2lo, int l2hi) static
Definition at line 142 of file writetop.cpp.
Referenced by writeSpan(), and externalBCpatch::writeTop().
 {
         fprintf(out,"%d  %3d %3d  %3d %3d  ",face,l1lo,l1hi,l2lo,l2hi);
 }
static void writeBlock (FILE * out, const bcListTop & bc, const block * b) static
Definition at line 225 of file writetop.cpp.
References block::getBlockNumber(), block::getDim(), block::getFace(), block::getOriginalNumber(), face::getPatches(), block::nFaces, makefloParam::nLevels, and parameters.
Referenced by writeTop().
{
         int blockNo=b->getBlockNumber()+1;
         int nGridLevels=parameters.nLevels;
         fprintf(out,
                 "%d %d ! ======== BLOCK %d (Split from source block %d) ========\n",
                 blockNo,nGridLevels,blockNo,b->getOriginalNumber()+1);
         blockDim d=b->getDim();
         int f,nPatches=0;
         for (f=0;f<block::nFaces;f++)
                 nPatches+=b->getFace(f).getPatches().size();
         fprintf(out,
                 "%d %d %d %d     ! number of patches; block size (ni, nj, nk)\n",
                 nPatches,d[0]-1,d[1]-1,d[2]-1);
         //Loop over the faces, writing out each patch
         for (f=0;f<block::nFaces;f++) {
                 static int order[6]={0,3,1,4,2,5};
                 const vector<patch *> &patches=b->getFace(order[f]).getPatches();
                 int nPatches=patches.size();
                 //Loop over the patches
                 for (int p=0;p<nPatches;p++) {
                         patches[p]->writeTop(out,bc);
                 }
         }
 }
static void writePatchEnd (FILE * out, int coupled) static
Definition at line 189 of file writetop.cpp.
Referenced by externalBCpatch::writeTop(), and internalBCpatch::writeTop().
{
         fprintf(out,"  %d\n",coupled);
 }
static void writePatchMiddle (FILE * out, int connBlock) static
Definition at line 186 of file writetop.cpp.
Referenced by externalBCpatch::writeTop(), and internalBCpatch::writeTop().
{
         fprintf(out,"%5d    ",connBlock);
 }
static void writePatchStart (FILE * out, int patchType) static
Definition at line 183 of file writetop.cpp.
Referenced by externalBCpatch::writeTop(), and internalBCpatch::writeTop().
{
         fprintf(out,"%4d   ",patchType);
 }
static void writeSpan (FILE * out, const blockSpan & s, const blockLoc & sign) static
Definition at line 160 of file writetop.cpp.
References blockSpan::end, blockSpan::getFace(), node2block(), blockSpan::start, and write5().
Referenced by externalBCpatch::writeTop(), and internalBCpatch::writeTop().
 {
         //Map our face numbering (iMin, jMin, kMin, iMax, ...) to
         // rocfloMP face numbering (iMin,iMax, jMin,jMax, ...)
         const static int faceMap[6]=
                 {1,3,5,2,4,6};
         int face=faceMap[s.getFace()];
         // l1 and l2 axes parameterize the face
         int flatAxis=(s.getFace()%3);
         int l1Axis=(flatAxis+1)%3;
         int l2Axis=(flatAxis+2)%3;
         int l1S=s.start[l1Axis], l1E=s.end[l1Axis];
         int l2S=s.start[l2Axis], l2E=s.end[l2Axis];
         node2block(l1S,l1E, l1S,l1E);
         node2block(l2S,l2E, l2S,l2E);
         int l1Sign=sign[l1Axis];
         int l2Sign=sign[l2Axis];
         write5(out,face,
                 l1Sign*(1+l1S),l1Sign*(1+l1E),
                 l2Sign*(1+l2S),l2Sign*(1+l2E));
 }
const char* writeTop (vector< block * > & blocks, const char * inBcs, const char * outTop)
Definition at line 252 of file writetop.cpp.
References cimg_library::cimg::fclose(), cimg_library::cimg::fopen(), and writeBlock().
Referenced by main().
 {
         FILE *bcs=fopen(inBcs,"r");
         if (bcs==NULL) {
                 char *ret=(char *)malloc(sizeof(char)*1000);
                 sprintf(ret,"Couldn't open input .bcmp file '%s'!\n",inBcs);
                 return ret;
         }
         bcListTop bc(bcs);
         fclose(bcs);
         FILE *top=fopen(outTop,"w");
         if (top==NULL) return "Couldn't open output .top file!\n";
         //Print the .top file header
         int nBlocks=blocks.size();
         fprintf(top,"# RocfloMP topology file, generated by makeflo\n"
                     "# \n"
                     "%d  ! Total number of blocks in this file\n",
                     nBlocks);
         //Print out each block
         for (int bn=0;bn<nBlocks;bn++)
                 writeBlock(top,bc,blocks[bn]);
         fclose(top);
         return NULL; //Everything worked!
 }