Rocstar: writemblock.cpp File Reference
writemblock.cpp File Reference
#include <stdio.h>
#include "makeflo.h"
#include "face.h"
Classes
class mblockData
class mblockData::blockPatches
Functions
const char * writeMblock (vector< block * > &blocks, const char *outMblock)
internalBCpatch * createSendPatch (internalBCpatch *recv, int faceNo)
static void printSpan (FILE *out, const blockSpan &sp)
Function Documentation
internalBCpatch* createSendPatch (internalBCpatch * recv, int faceNo)
Definition at line 161 of file writemblock.cpp.
References internalBCpatch::dest, internalBCpatch::destSpan, internalBCpatch::orient, patch::src, and patch::srcSpan.
 {
         internalBCpatch *send=new internalBCpatch(NULL,recv->src,recv->dest,
                 recv->srcSpan,recv->destSpan,recv->orient);
         return send;
 }
static void printSpan (FILE * out, const blockSpan & sp) static
Definition at line 186 of file writemblock.cpp.
References blockSpan::end, s, and blockSpan::start.
Referenced by externalBCpatch::writeMblock(), and internalBCpatch::writeMblock().
 {
         const blockLoc &s(sp.start), &e(sp.end);
         fprintf(out,"   %d %d    %d %d    %d %d \n",
                s[0],e[0],s[1],e[1],s[2],e[2]);
 }
const char* writeMblock (vector< block * > & blocks, const char * outMblock)
Definition at line 134 of file writemblock.cpp.
References cimg_library::cimg::fclose(), fName, cimg_library::cimg::fopen(), cimg_library::cimg::fwrite(), parameters, makefloParam::topologyOnly, and mblockData::write().
Referenced by main(), and mblockData::blockPatches::write().
 {
         mblockData d(blocks);
         for (unsigned int b=0;b<blocks.size();b++) {
                 char fName[1024];
                 //Write the boundary descriptions
                 sprintf(fName,"%s%05d.bblk",outMblock,b);
                 FILE *fb=fopen(fName,"w");
                 if (fb==NULL) return "Couldn't create .bblk file";
                 d.write(blocks[b],fb);
                 fclose(fb);
                 //Write the mesh locations themselves
                 if (!parameters.topologyOnly) {
                         sprintf(fName,"%s%05d.mblk",outMblock,b);
                         FILE *fm=fopen(fName,"wb");
                         if (fm==NULL) return "Couldn't create .bblk file";
                         fwrite(&blocks[b]->getLoc(blockLoc(0,0,0)),sizeof(vector3d),
                                 blocks[b]->getDim().getSize(),fm);
                         fclose(fm);
                 }
         }
         return NULL;
 }