Rocstar: writehdf.cpp File Reference
writehdf.cpp File Reference
#include <stdio.h>
#include "gridutil.h"
#include "mfhdf.h"
Macros
#define chk(x) checkHDFerr(x,__FILE__,__LINE__)
Typedefs
typedef double REAL
Functions
static int checkHDFerr (int errCode, const char *fName, int lineNo)
const char * write_hdf (const blockDim &dim, const vector3d *locs, const char *filename)
Macro Definition Documentation
#define chk (x) checkHDFerr(x,__FILE__,__LINE__)
Definition at line 67 of file writehdf.cpp.
Referenced by write_hdf().
Typedef Documentation
typedef double REAL
Definition at line 65 of file writehdf.cpp.
Function Documentation
static int checkHDFerr (int errCode, const char * fName, int lineNo) static
Definition at line 68 of file writehdf.cpp.
{
         if (errCode==-1) {
                 fprintf(stderr,"HDF I/O Error in (%s:%d)\n",
                         fName,lineNo);
                 exit(23);
         }
         return errCode;
 }
const char* write_hdf (const blockDim & dim, const vector3d * locs, const char * filename)
Definition at line 77 of file writehdf.cpp.
References chk, blockDim::getSize(), i, cimg_library::cimg::time(), x, vector3d::x, y, vector3d::y, z, and vector3d::z.
Referenced by writeBlocks().
 {
         const int dataType=6;//double precision float
         REAL time=0.0;
         int32 timeLen=1;
         chk(DFSDsetdims(1,&timeLen));
         chk(DFSDsetNT(dataType));
         chk(DFSDputdata(filename, 1, &timeLen, &time));
         //Copy the data from C++ array to C arrays
         int len=dim.getSize();
         REAL *x=new REAL[len];
         REAL *y=new REAL[len];
         REAL *z=new REAL[len];
         blockLoc i;
         for (i[2]=0; i[2]<dim[2]; i[2]++)
         for (i[1]=0; i[1]<dim[1]; i[1]++)
         for (i[0]=0; i[0]<dim[0]; i[0]++)
         { //Copy data into separate, coordinate-wise arrays
                 int c_i=dim[i], f_i=dim[i];
                 x[f_i]=locs[c_i].x;
                 y[f_i]=locs[c_i].y;
                 z[f_i]=locs[c_i].z;
         }
         //Send the data off to HDF
         int32 dSize[3]; //Swap dimensions
         dSize[0]=dim[2]; dSize[1]=dim[1]; dSize[2]=dim[0];
         chk(DFSDsetdims(3,dSize));
         chk(DFSDsetNT(dataType));
         chk(DFSDadddata(filename, 3, dSize, x));
         chk(DFSDadddata(filename, 3, dSize, y));
         chk(DFSDadddata(filename, 3, dSize, z));
         //Clean up output arrays
         delete[] x; delete[] y; delete[] z;
         return NULL;
 }