Rocstar: writemsh.f90 File Reference
writemsh.f90 File Reference
Functions/Subroutines
subroutine write_msh (iblock, ni, nj, nk, x, y, z, F_name)
Function/Subroutine Documentation
subroutine write_msh (integer iblock, integer ni, integer nj, integer nk, double precision, dimension(ni,nj,nk) x, double precision, dimension(ni,nj,nk) y, double precision, dimension(ni,nj,nk) z, character (len=500) F_name)
Definition at line 58 of file writemsh.f90.
References Line_2< R, T >::a(), form, i, ElementList::index(), j, k, ni, nj, nk, StopWatch::total_time(), x, y, and z.
Referenced by writeBlocks().