Rocstar: writeflo.cpp File Reference
writeflo.cpp File Reference
#include <stdio.h>
#include "face.h"
Classes
class bcRec
class bcList
Functions
void writeHeader (FILE *out, int nBlocks, int nPEs)
string getSpan (const blockSpan &s)
void writeBlock (FILE *out, const bcList &bc, const block *b)
const char * writeFlo (vector< block * > &blocks, int nPEs, const char *inBcs, const char *outFlo)
Function Documentation
string getSpan (const blockSpan & s)
Definition at line 159 of file writeflo.cpp.
References blockSpan::end, and blockSpan::start.
Referenced by externalBCpatch::writeFlo(), and internalBCpatch::writeFlo().
 {
         char buf[200];
         sprintf(buf,"   %d %d    %d %d    %d %d",
                 1+s.start[0],s.end[0],
                 1+s.start[1],s.end[1],
                 1+s.start[2],s.end[2]);
         return buf;
 }
void writeBlock (FILE * out, const bcList & bc, const block * b)
Definition at line 198 of file writeflo.cpp.
References block::face2name, block::getBlockNumber(), block::getDim(), block::getFace(), block::getOriginalNumber(), face::getPatches(), bcList::lookup(), and block::nFaces.
Referenced by writeFlo().
{
         int blockNo=b->getBlockNumber()+1;
         fprintf(out,
                 "%d %d 1 ! BLOCK %d (Split from source block %d) ======================\n"
                 "\n",
                 blockNo,blockNo,blockNo,b->getOriginalNumber()+1);
         blockDim d=b->getDim();
         fprintf(out,
                 "%d %d %d     ! Block size (ni, nj, nk)\n",
                 d[0],d[1],d[2]);
         //Get the fluid initial conditions
         fprintf(out,"%s\n",bc.lookup(-1,"").c_str());
         //Loop over the faces
         for (int f=0;f<block::nFaces;f++) {
                 const vector<patch *> &patches=b->getFace(f).getPatches();
                 int nPatches=patches.size();
                 fprintf(out,
                         "%d            ! Block %d, Face (%s) has %d patch\n",
                         nPatches,blockNo,block::face2name[f],nPatches);
                 //Loop over the patches
                 for (int p=0;p<nPatches;p++) {
                         patches[p]->writeFlo(out,bc);
                 }
                 fprintf(out,"\n");
         }
         fprintf(out,
                 "ENDBBC\n"
                 "\n");
 }
const char* writeFlo (vector< block * > & blocks, int nPEs, const char * inBcs, const char * outFlo)
Definition at line 230 of file writeflo.cpp.
References cimg_library::cimg::fclose(), cimg_library::cimg::fopen(), writeBlock(), and writeHeader().
Referenced by main().
 {
         FILE *bcs=fopen(inBcs,"r");
         if (bcs==NULL) {
                 char *ret=(char *)malloc(sizeof(char)*1000);
                 sprintf(ret,"Couldn't open input .bc file '%s'!\n",inBcs);
                 return ret;
         }
         bcList bc(bcs);
         fclose(bcs);
         FILE *flo=fopen(outFlo,"w");
         if (flo==NULL) return "Couldn't open output .flo file!\n";
         //Print the .flo file header
         int nBlocks=blocks.size();
         writeHeader(flo,nBlocks,nPEs);
         //Print out each block
         for (int bn=0;bn<nBlocks;bn++)
                 writeBlock(flo,bc,blocks[bn]);
         fclose(flo);
         return NULL; //Everything worked!
 }
void writeHeader (FILE * out, int nBlocks, int nPEs)
Definition at line 148 of file writeflo.cpp.
Referenced by writeFlo().
{
         fprintf(out,
                 "%d %d       ! ndom, nproc\n"
                 "\n"
                 "PROC_MAP_AUTO\n"
                 "\n",
                 nBlocks,nPEs);
 }