Rocstar: ZN_calc_burning_rate.f90 File Reference
ZN_calc_burning_rate.f90 File Reference
Functions/Subroutines
subroutine zn_calc_burning_rate (G_ZN, delt, P, qr, To, rhoc, qr_old, fr_old, Toa, rb, Ts, fr, Tn, Tnp1)
subroutine zn (P, qr, To, Ts, Toa, rb, fr)
subroutine newton (x, J, e)
subroutine cmpct1 (imax, h, u, f, a, b, cc)
subroutine cmpct2 (imax, h, u, s, a, b, cc)
subroutine tridg (imax, a, b, c, d)
Function/Subroutine Documentation
subroutine zn_calc_burning_rate::cmpct1 (integer imax, real(dbl) h, real(dbl), dimension(imax) u, real(dbl), dimension(imax) f, real(dbl), dimension(:) a, real(dbl), dimension(:) b, real(dbl), dimension(:) cc)
Definition at line 471 of file ZN_calc_burning_rate.f90.
References Line_2< R, T >::a(), Color::b(), i, and tridg().
Referenced by zn_calc_burning_rate().
subroutine zn_calc_burning_rate::cmpct2 (integer imax, real(dbl) h, real(dbl), dimension(imax) u, real(dbl), dimension(imax) s, real(dbl), dimension(:) a, real(dbl), dimension(:) b, real(dbl), dimension(:) cc)
Definition at line 526 of file ZN_calc_burning_rate.f90.
References Line_2< R, T >::a(), Color::b(), i, s, and tridg().
Referenced by zn_calc_burning_rate().
subroutine zn_calc_burning_rate::newton (real(dbl), dimension(2) x, real(dbl), dimension(2,2) J, real(dbl), dimension(2) e)
Definition at line 432 of file ZN_calc_burning_rate.f90.
References i, j, Aff_transformation_repS2< FT >::print(), StopWatch::stop(), and x.
Referenced by zn(), and zn_sswsb().
subroutine zn_calc_burning_rate::tridg (integer imax, real(dbl), dimension(:) a, real(dbl), dimension(:) b, real(dbl), dimension(:) c, real(dbl), dimension(:) d)
Definition at line 584 of file ZN_calc_burning_rate.f90.
References Line_2< R, T >::a(), Color::b(), Line_2< R, T >::c(), Plane_3< R, T >::d(), and i.
Referenced by cmpct1(), and cmpct2().
subroutine zn_calc_burning_rate::zn (real(dbl) P, real(dbl) qr, real(dbl) To, real(dbl) Ts, real(dbl) Toa, real(dbl) rb, real(dbl) fr)
Definition at line 216 of file ZN_calc_burning_rate.f90.
References j, newton(), Aff_transformation_repS2< FT >::print(), and StopWatch::stop().
Referenced by planenorm(), and zn_calc_burning_rate().
subroutine zn_calc_burning_rate (type(g_burn_1d), pointer G_ZN, real(dbl), intent(in) delt, real(dbl), intent(in) P, real(dbl), intent(in) qr, real(dbl), intent(in) To, real(dbl), intent(in) rhoc, real(dbl), intent(in) qr_old, real(dbl), intent(in) fr_old, real(dbl), intent(inout) Toa, real(dbl), intent(inout) rb, real(dbl), intent(inout) Ts, real(dbl), intent(inout) fr, real(dbl), dimension(:), intent(in) Tn, real(dbl), dimension(:), intent(out) Tnp1)
Definition at line 60 of file ZN_calc_burning_rate.f90.
References cmpct1(), cmpct2(), i, Aff_transformation_repS2< FT >::print(), StopWatch::stop(), and zn().
Referenced by m_rocburn_1d_zn::get_burning_rate_1d().