#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# removing solution runtime files
cd fluid;
cleanTimeDirectories;
cleanCase;
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam history
# removing IMPACT and Elmer related runtime files
\rm prob*.dat
\rm *.hdf
\rm *.txt
\rm *.prof
\rm elmerfoamfsi*
cd beam3d;
\rm *.vtu
\rm *.pvtu
cd ../;
# removing openFoam solid solver related files
cd ../solid;
cleanTimeDirectories;
cleanCase;
\rm -rf constant/polyMesh/sets constant/polyMesh/*Zones*
\rm -rf VTK case.foam history

cd ..
./removeSerialLinks fluid solid
