#!/bin/csh

set SRCDIR = /csar/jiao/Rocstar
set OPTS = 'DEBUG=1 DUMMY_MPI=1 LIBSUF=a'

cd ${SRCDIR}/Roccom; gmake ${OPTS} clean; 
cvs update -dP; gmake ${OPTS} -j 4

cd ${SRCDIR}/Rocface; gmake ${OPTS} clean
cvs update -dP; gmake ${OPTS} -j 4

gmake ${OPTS} testall
